### PR TITLE
storage: refactor Raft proposal path in preparation for proposer-evaluated KV

### PR DESCRIPTION
**Pull request by tbg**
commit dbd0926d8b261f4e64143c45b79a6a48a5a26c3b
Author: Tobias Schottdorf tobias.schottdorf@gmail.com
Date:   Sat Oct 15 12:10:18 2016 -0400

```
storage: rename Replica Raft proposal methods

- proposeRaftCommand -> propose
  This is what the client calls, obtaining a channel to wait for the result or
  the error.
- prepareRaftCmdLocked -> evaluateProposalLocked
  This will be where proposer-evaluated KV is going to "happen". The method
  takes a BatchRequest (and a few tidbits of auxiliary information, at least
  currently) and returns a `*ProposalData` which contains the proposer-local
  state as well as the result of the evaluation of the command which is to be
  submitted to Raft.
- proposeRaftCommandFn -> submitProposalFn
- proposePendingCmdLocked -> submitProposalLocked
- insertRaftCommandLocked -> insertProposalLocked

defaultProposeRaftCommandLocked -> defaultSubmitProposalLocked
```

commit 2a484a989c967cd63d6d85c5b1bb8c9f593cd57c
Author: Tobias Schottdorf tobias.schottdorf@gmail.com
Date:   Sat Oct 15 11:54:59 2016 -0400

```
storage: replace pendingCmd with ProposalData
```

commit bcac3fb179ef9e50815f00fa28f6df523143e5d5
Author: Tobias Schottdorf tobias.schottdorf@gmail.com
Date:   Sat Oct 15 10:34:21 2016 -0400

```
storage: populate LocalProposalData

Move `engine.Batch`, `*roachpb.Error` and `*roachpb.BatchResponse` onto
`LocalProposalData` (which is where they belong and are easier to handle
with upcoming proposer-evaluated-Raft changes).
```

commit eacc119120a4c4d8854bab9611d2a0a6b24d706e
Author: Tobias Schottdorf tobias.schottdorf@gmail.com
Date:   Sat Oct 15 08:56:43 2016 -0400

```
roachpb: move RaftCommand to storagebase

This colocates it with ReplicatedProposalData for consolidation
in upcoming PRs.
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10004)

### CODE REVIEW

**Comment by tamird** [comment]
I don't understand the purpose of the 2nd commit, perhaps more description in the commit message would help.

---

Reviewed 11 of 11 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 2780 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8Q3SsvPE8Z4P8P1CX:-KU8Q3SsvPE8Z4P8P1CY:bjcpdim) ([raw file](https://github.com/cockroachdb/cockroach/blob/6629b1df7cc7d0b831c70c504181647ee9a0376d/pkg/storage/replica.go#L2780)):*
> ```Go
> 	ctx context.Context,
> 	index, leaseIndex uint64,
> 	originReplica roachpb.ReplicaDescriptor,
> ```

did you mean to remove this? mention in commit message or put in separate commit.

---

*[pkg/storage/replica.go, line 2945 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QxeeeFCpaEMVoteJ:-KU8QxeeeFCpaEMVoteK:bgf1rba) ([raw file](https://github.com/cockroachdb/cockroach/blob/eacc119120a4c4d8854bab9611d2a0a6b24d706e/pkg/storage/replica.go#L2945)):*
> ```Go
> 	}
> 
> 	if (pd.delta != enginepb.MVCCStats{}) {
> ```

don't you still want this assertion the return value of executeWriteBatch?

---

*[pkg/storage/replica.go, line 2667 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QR6WOmuOwSjzzxIb:-KU8QR6WOmuOwSjzzxIc:bdjc5l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcac3fb179ef9e50815f00fa28f6df523143e5d5/pkg/storage/replica.go#L2667)):*
> ```Go
> 		pd.Err = r.maybeSetCorrupt(ctx, pd.Err)
> 
> 		// TODO(tschottdorf): this fields should be zeroed earlier.
> ```

s/fields/field/

---

*[pkg/storage/replica_proposal.go, line 45 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QNeVtJxL4Bln4klZ:-KU8QNeVtJxL4Bln4kl_:b-iwjykb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcac3fb179ef9e50815f00fa28f6df523143e5d5/pkg/storage/replica_proposal.go#L45)):*
> ```Go
> type LocalProposalData struct {
> 	roachpb.ResponseWithError
> 	engine.Batch
> ```

wasn't there a TODO about this somewhere?

---

*[pkg/storage/replica_raftstorage.go, line 711 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QALCZuDx29bPfoKv:-KU8QALCZuDx29bPfoKw:b-svq3a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/eacc119120a4c4d8854bab9611d2a0a6b24d706e/pkg/storage/replica_raftstorage.go#L711)):*
> ```Go
> )
> 
> // encode a command ID, an encoded storagebase.RaftCommand, and whether the command
> ```

looks this might need re-wrapping

---

*[pkg/storage/replica_test.go, line 401 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8R_13u1r9aspSBT49:-KU8R_13u1r9aspSBT4A:bluh0i7) ([raw file](https://github.com/cockroachdb/cockroach/blob/346cd081b29dcd7d44c3c3f5181e11a7fe0723c9/pkg/storage/replica_test.go#L401)):*
> ```Go
> 	ba.Timestamp = r.store.Clock().Now()
> 	ba.Add(&roachpb.RequestLeaseRequest{Lease: *l})
> 	ch, _, err := r.propose(context.Background(), ba)
> ```

heh, should certainly be TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KU8R319DPfmpl1uRxoU:b-bin7ze)*

**Comment by tschottdorf** [comment]
I assume you mean this one:

> storage: replace pendingCmd with ProposalData

I added a commit message.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 2780 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8Q3SsvPE8Z4P8P1CX:-KU8cKmFXGPUHAYtJuyH:bbk3ecw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6629b1df7cc7d0b831c70c504181647ee9a0376d/pkg/storage/replica.go#L2780)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> did you mean to remove this? mention in commit message or put in separate commit.
</details>
Added to commit message.

---

*[pkg/storage/replica.go, line 2945 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QxeeeFCpaEMVoteJ:-KU8cjIo7HK9O9bzeJ7i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eacc119120a4c4d8854bab9611d2a0a6b24d706e/pkg/storage/replica.go#L2945)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> don't you still want this assertion the return value of executeWriteBatch?
</details>
Done.

---

*[pkg/storage/replica.go, line 2667 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QR6WOmuOwSjzzxIb:-KU8c4Xfi8LSGBEoPO9u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcac3fb179ef9e50815f00fa28f6df523143e5d5/pkg/storage/replica.go#L2667)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/fields/field/
</details>
Done.

---

*[pkg/storage/replica_proposal.go, line 45 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QNeVtJxL4Bln4klZ:-KU8clWiD5JKvCTK0NdU:bdu3in9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcac3fb179ef9e50815f00fa28f6df523143e5d5/pkg/storage/replica_proposal.go#L45)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wasn't there a TODO about this somewhere?
</details>
No, there's a TODO about adding the `WriteBatch`, which isn't happening just yet.

---

*[pkg/storage/replica_raftstorage.go, line 711 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8QALCZuDx29bPfoKv:-KU8d-laHXFFod-W4OzY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eacc119120a4c4d8854bab9611d2a0a6b24d706e/pkg/storage/replica_raftstorage.go#L711)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> looks this might need re-wrapping
</details>
Done.

---

*[pkg/storage/replica_test.go, line 401 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8R_13u1r9aspSBT49:-KU8d4d2NAsG2_PuiUqb:bghjzyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/346cd081b29dcd7d44c3c3f5181e11a7fe0723c9/pkg/storage/replica_test.go#L401)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> heh, should certainly be TODO.
</details>
I'm not sure what this comment is about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KU8brhlQ37DcjdvkQIG:b-22d37a)*

**Comment by tamird** [comment]
Actually I did mean the second commit:

> storage: populate LocalProposalData

> Move `engine.Batch`, `*roachpb.Error` and `*roachpb.BatchResponse` onto
`LocalProposalData` (which is where they belong and are easier to handle
with upcoming proposer-evaluated-Raft changes).

That description is rather opaque; it's basically "trust me, this helps". :confused: 

---

Reviewed 8 of 8 files at r5, 2 of 2 files at r6, 6 of 6 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_test.go, line 401 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8R_13u1r9aspSBT49:-KU8dmqZkSytDAJsiIax:b-eezv0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/346cd081b29dcd7d44c3c3f5181e11a7fe0723c9/pkg/storage/replica_test.go#L401)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I'm not sure what this comment is about.
</details>
The `context.Background()`. I left the comment as "satisfied" because it's optional; I only mention because you're acquiring the blame.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KU8eGw_gXM3ly0gcRR1:b-2rzmha)*

**Comment by tschottdorf** [comment]
I merged this into its parent commit. Let me know if the commit message is OK.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/storage/replica_test.go, line 401 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8R_13u1r9aspSBT49:-KU8fSQUGxQkknModlaO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/346cd081b29dcd7d44c3c3f5181e11a7fe0723c9/pkg/storage/replica_test.go#L401)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The `context.Background()`. I left the comment as "satisfied" because it's optional; I only mention because you're acquiring the blame.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KU8fOKUIrD0jx_NXtvK:b-r2kdm9)*

**Comment by tschottdorf** [comment]
^- I decided against this after all, but the commit message has been updated.

---

Review status: 8 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KU8h5jBVSsYXFVKRNKh:bcojdj6)*

**Comment by tamird** [comment]
Great, thanks for the update. :lgtm:

---

Reviewed 3 of 3 files at r9, 4 of 6 files at r11, 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_test.go, line 401 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8R_13u1r9aspSBT49:-KU8i3eA8fTFQ6-AWj-d:b-eaaa64) ([raw file](https://github.com/cockroachdb/cockroach/blob/346cd081b29dcd7d44c3c3f5181e11a7fe0723c9/pkg/storage/replica_test.go#L401)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Done.
</details>
You sure?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KU8iBSE7U97-yhG0RuN:b29atu0)*

**Comment by tschottdorf** [comment]
Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---

*[pkg/storage/replica_test.go, line 401 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KU8R_13u1r9aspSBT49:-KU8iVWVeClYccdJsuN3:b-u9qxbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/346cd081b29dcd7d44c3c3f5181e11a7fe0723c9/pkg/storage/replica_test.go#L401)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> You sure?
</details>
Oops, accidentally reverted. Re-reverted now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 11 files at r1, 1 of 8 files at r5, 4 of 6 files at r15, 3 of 3 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_proposal.go, line 50 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KUD9HD_cKEUkR6_WCjw:-KUD9HD_cKEUkR6_WCjx:bnefu91) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ca1d322a9a955d2bf0d892e747ffc511d034b73/pkg/storage/replica_proposal.go#L50)):*
> ```Go
> 	idKey           storagebase.CmdIDKey
> 	proposedAtTicks int
> 	done            chan roachpb.ResponseWithError // Used to signal waiting RPC handler
> ```

Now that LocalProposalData stores the response, should this be a `chan struct{}` to signal that the waiter needs to read the response from the LocalProposalData? I think it would be slightly cleaner to either store the response or send it over the channel but not both. 

---

*[pkg/storage/replica_proposal.go, line 54 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KUD8dLiAv6PN58KVF_F:-KUD8dLiAv6PN58KVF_G:b-pshfev) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ca1d322a9a955d2bf0d892e747ffc511d034b73/pkg/storage/replica_proposal.go#L54)):*
> ```Go
> 
> 	roachpb.ResponseWithError
> 	engine.Batch
> ```

Both of these fields should be named instead of embedded. It's especially confusing to see both `pd.Err` and `pd.ResponseWithError` used; I thought there were redundant error variables somewhere. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KUD9XiDtxatSEJcXLOE:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_proposal.go, line 50 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KUD9HD_cKEUkR6_WCjw:-KUH1MOcK0LtjjGfjIW8:bs7i12) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ca1d322a9a955d2bf0d892e747ffc511d034b73/pkg/storage/replica_proposal.go#L50)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Now that LocalProposalData stores the response, should this be a `chan struct{}` to signal that the waiter needs to read the response from the LocalProposalData? I think it would be slightly cleaner to either store the response or send it over the channel but not both. 
</details>
The proposer only sees the channel (in `addWriteCmd`), and I don't want to do hand it the `*ProposalData` instead, at least not that in this change.

---

*[pkg/storage/replica_proposal.go, line 54 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-KUD8dLiAv6PN58KVF_F:-KUH2n20MJRenKO25v_2:b-j8doo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ca1d322a9a955d2bf0d892e747ffc511d034b73/pkg/storage/replica_proposal.go#L54)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Both of these fields should be named instead of embedded. It's especially confusing to see both `pd.Err` and `pd.ResponseWithError` used; I thought there were redundant error variables somewhere. 
</details>
Made them named fields (and removed ResponseWithError). These structs aren't very clean yet (in particular, mix of exported and unexported fields), but I'll make sure to address that in future iterations when things stabilize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004)*

**Comment by tschottdorf** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10004#-:-KUH38xV11KlEayvHGk0:bz5mair)*

**Pull request merged**
