### PR TITLE
distsql, ui: query count metrics

### PR DESCRIPTION
**Pull request by couchand**
This adds metrics for counts of active DistSQL queries and flows, which
will give some visibility into the status of long-running queries.

Contributes to #12143.

### CODE REVIEW

**Comment by couchand** [comment]
cc: @arjunravinarayan @cuongdo @mrtracy

**Comment by cuongdo** [comment]
It's customary to attach screenshots of the changed admin UI page(s), so could you please do that?

Also, @RaduBerinde might have thoughts.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-:-KpIFdtp2CBMBw2A3NRo:bt4sr1m)*

**Comment by mrtracy** [comment]
Had some comments on the graphs and the metric structs, the actual usage of the metrics looks good.

---

Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/server/server.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIPsjI2_iU87erpfh5:-KpIPsjI2_iU87erpfh6:b25668a) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/server/server.go#L280)):*
> ```Go
> 	rootSQLMemoryMonitor.Start(context.Background(), nil, mon.MakeStandaloneBudget(s.cfg.SQLMemoryPoolSize))
> 
> 	distSQLMemMetrics := sql.MakeMemMetrics("distsql", cfg.HistogramWindowInterval())
> ```

By my eye, these metrics should likely be part of the new DistSQLMetrics struct.  It was a little difficult to read this because of the similarity with the new `distSQLMetrics` variable.

Since we're only using two of the metrics from the MemMetrics struct (out of the six described), maybe it would be more readable to put those two metrics directly on the DistSQLMetrics struct.

---

*[pkg/sql/distsqlrun/metrics.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIR8M6aJTkyN3T0wtw:-KpIR8M6aJTkyN3T0wtx:bb6ht2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/sql/distsqlrun/metrics.go#L1)):*
> ```Go
> // Copyright 2016 The Cockroach Authors.
> ```

2017

---

*[pkg/sql/distsqlrun/metrics.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpINeUcxduwJ4VqjO4c:-KpINeUcxduwJ4VqjO4d:bte7hyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/sql/distsqlrun/metrics.go#L41)):*
> ```Go
> 	metaQueriesActive := metric.Metadata{
> 		Name: "sql.distsql.queries.active",
> 		Help: "Number of currently active DistSQL queries"}
> ```

metric Metadata structs are defined in top-level `var` blocks everywhere else; they're essentially constants.  The one exception was sql.MakeMemMetrics.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIM56BXTQ0-UrMPMAE:-KpIM56CCZj8tbVwCsOn:b-c3euiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L56)):*
> ```XML
>       title="DistSQL Queries Active"
>       sources={nodeSources}
>       tooltip="The total number of active DistSQL queries on all nodes."
> ```

use ${tooltipSelection} here. It is either the string "across all nodes" or "on node X" if a single node is selected.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIMFg9Dp2RqijOhBUK:-KpIMFg9Dp2RqijOhBUL:b-5j1say) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L66)):*
> ```XML
>       title="DistSQL Flows Active, total"
>       sources={nodeSources}
>       tooltip="The total number of active DistSQL flows on all nodes."
> ```

${tooltipSelection}.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIMvbIaxmqTJFkhx2A:-KpIMvbIaxmqTJFkhx2B:bxdvty7) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L75)):*
> ```XML
>     <LineGraph
>       title="DistSQL Flows Active, by node"
>       sources={nodeSources}
> ```

Don't need to specify sources here, the sources are applied to the individual metrics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-:-KpIRcbrnGjorpNDWS1v:b-hz47rh)*

**Comment by couchand** [comment]
Inline feedback addressed (except for the one TODO comment added).  I've also added some questions myself about the charts, would appreciate any opinions there.

Will add screenshots when I get into the office, as my setup for making these charts show interesting data is there.

---

Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/server/server.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIPsjI2_iU87erpfh5:-KpKHIip-ZrwBLQRAy4-:b-42rz4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/server/server.go#L280)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

By my eye, these metrics should likely be part of the new DistSQLMetrics struct.  It was a little difficult to read this because of the similarity with the new `distSQLMetrics` variable.

Since we're only using two of the metrics from the MemMetrics struct (out of the six described), maybe it would be more readable to put those two metrics directly on the DistSQLMetrics struct.
</blockquote></details>

Totally agree, that's where I was thinking of going as a next step.  Even thought I had added a TODO.  Just added one now, will take care of that next.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpKHogfvc19sSqzAI9L:-KpKHoggsZM4iUZzzsGF:beynmkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L54)):*
> ```XML
> 
>     <LineGraph
>       title="DistSQL Queries Active"
> ```

I'm wondering if this should be labeled "in flight" to make it clearer what it's showing?  OTOH, "flows in flight" doesn't make much sense, and there's something to be said for keeping them consistent.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIM56BXTQ0-UrMPMAE:-KpKLc000t198DkCSQNY:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L56)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

use ${tooltipSelection} here. It is either the string "across all nodes" or "on node X" if a single node is selected.
</blockquote></details>

Nice.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpKI1ge86o8wNaNKUPa:-KpKI1ge86o8wNaNKUPb:bthtn35) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L64)):*
> ```XML
> 
>     <LineGraph
>       title="DistSQL Flows Active, total"
> ```

I'm going back and forth on whether sure this chart is all that valuable.  Split out by nodes seems to be more useful.  The only thing is that it would be nice if it were easier to see totals on the by nodes charts generally (where it makes sense).

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIMFg9Dp2RqijOhBUK:-KpKLdKNWxJiourh9En3:bhvvbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L66)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

${tooltipSelection}.
</blockquote></details>

Changed, but per my comment right above I may just remove this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-:-KpKMLDSJCXWkwVBP6-Q:b2r0585)*

**Comment by couchand** [comment]
screen shot 2017-07-18 at 9 41 42 am

**Comment by cuongdo** [comment]
These graphs look useful!

What do you think about changing "DistSQL Queries Active" to "DistSQL Active Queries"? Also, what about "Flows Active" to "Active Flows"?

**Comment by couchand** [comment]
I agree @cuongdo that sounds more natural.

**Comment by couchand** [comment]
After recent updates.  As you can see I've just gone ahead and removed the chart with the total count of flows in favor of the one broken down by node.
screen shot 2017-07-18 at 10 41 06 am

**Comment by arjunravinarayan** [comment]
:lgtm: on the DistSQL side, wait for Matt's LGTM on the visual side as well. These are useful metrics to have! I have a production cluster I'm poking right now where it would be useful to have these metrics, which is a great sign.

---

Reviewed 2 of 7 files at r1, 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/metrics.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpINeUcxduwJ4VqjO4c:-KpLGERtEblKSQzFa2tK:b7qi968) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/sql/distsqlrun/metrics.go#L41)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

metric Metadata structs are defined in top-level `var` blocks everywhere else; they're essentially constants.  The one exception was sql.MakeMemMetrics.
</blockquote></details>

Looks done to me. @couchand did you forget to ping this as done?

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpKHogfvc19sSqzAI9L:-KpLIPpc6SX_AhrOjd4a:b-5id1kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L54)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I'm wondering if this should be labeled "in flight" to make it clearer what it's showing?  OTOH, "flows in flight" doesn't make much sense, and there's something to be said for keeping them consistent.
</blockquote></details>

"Running Queries" is what I would have called it, but active queries seems fine.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpKI1ge86o8wNaNKUPa:-KpLIm8HDZ0MBdoSIFR2:bfjumq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L64)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I'm going back and forth on whether sure this chart is all that valuable.  Split out by nodes seems to be more useful.  The only thing is that it would be nice if it were easier to see totals on the by nodes charts generally (where it makes sense).
</blockquote></details>

I agree that split out by nodes is the most useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-:-KpLJ4VjinDeBXQncUB2:b-nsxadw)*

**Comment by couchand** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIPsjI2_iU87erpfh5:-KpLbTcWU8CfRfuP5iSk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/server/server.go#L280)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Totally agree, that's where I was thinking of going as a next step.  Even thought I had added a TODO.  Just added one now, will take care of that next.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/metrics.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIR8M6aJTkyN3T0wtw:-KpLbUUoWpb_GQaKuLIf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/sql/distsqlrun/metrics.go#L1)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

2017
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/metrics.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpINeUcxduwJ4VqjO4c:-KpLbVF6TO5Fl_-KFWPh:b-ate0go) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/sql/distsqlrun/metrics.go#L41)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Looks done to me. @couchand did you forget to ping this as done?
</blockquote></details>

I clicked the thumbs up, but apparently that doesn't propagate anywhere?  In any case, this is done.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpKHogfvc19sSqzAI9L:-KpLbfUgrKmthHthL-nX:b6ylkag) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L54)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

"Running Queries" is what I would have called it, but active queries seems fine.
</blockquote></details>

Fair point.  Leaving it unless somebody makes a good argument.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpKI1ge86o8wNaNKUPa:-KpLbeRTyv1_8rwC7gSj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L64)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I agree that split out by nodes is the most useful.
</blockquote></details>

Done.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIMvbIaxmqTJFkhx2A:-KpLbdeKC9ZLN4sYtMAf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L75)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Don't need to specify sources here, the sources are applied to the individual metrics.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050)*

**Comment by dianasaur323** [comment]
This looks great! The only question from me is whether or not "flows" is a concept people outside of CockroachDB will understand. If it isn't, let's try to use generally understandable terminology versus forcing users to rely on the tooltips. If yes, let's keep as is. Could you also make sure to include a tool tip defining the metric?

**Comment by arjunravinarayan** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/metrics.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpINeUcxduwJ4VqjO4c:-KpLg7O-nKQcu3TlMWPj:b-usphck) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/sql/distsqlrun/metrics.go#L41)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I clicked the thumbs up, but apparently that doesn't propagate anywhere?  In any case, this is done.
</blockquote></details>

The thumbs up is what the raiser of the issue does when they are happy with you doing the thing (and at Cockroach people don't always do this). But when you do the thing, you write an explicit response (there's a shorthand one-button "Done." you can use) so that they know to check the diff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050)*

**Comment by couchand** [comment]
@dianasaur323 Great point about the term "flows", it'd probably not clear unless you've studied the internals of DistSQL.  Do you have a suggestion for what to use instead?  The tooltips currently say "The total number of active DistSQL queries (across all nodes/on node #)." for the queries chart and "The number of DistSQL flows running on each node." for the flows one.  Are you looking for more details there, and do you have input on what that should say?  My guess is we need more clarification for the flows chart, but I'm not sure I know what it should say.

**Comment by cuongdo** [comment]
How about "workers" instead of "flows"? For someone technical, "workers" should be common enough terminology.

**Comment by couchand** [comment]
I'm a big fan of the concept of [Ubiquitous Language](https://www.martinfowler.com/bliki/UbiquitousLanguage.html) as described by Eric Evans in _Domain-Driven Design_.  I think there's a concern that by having different terms internally and externally for the same thing it can be hard to learn and describe precisely what it means.  If we think "flows" is going to be hard to bring people over to and we generally prefer "workers", we should use that everywhere, in the code base as well as in our own discussions.  If, however, we think "flows" is a good term (because it's more precise?) to describe them, we should use that everywhere, including in documentation and the Admin UI.  We can of course use "workers" or anything else to add clarification for new users in the docs & tooltips, but I'd argue that keeping the terminology consistent will be a big win in the long term.  Thoughts? @dianasaur323 @cuongdo @cockroachdb/distsql

**Comment by cuongdo** [comment]
I agree in principle. cc @RaduBerinde for his thoughts, since this would be a (hopefully mostly mechanical) code change

**Comment by RaduBerinde** [comment]
A flow is not a worker. It is (more or less) a *work item*. We don't quite have a clearly defined "worker" entity in DistSQL code (we have a "flow scheduler" that manages currently running flows), but if we pretend we do, then a worker processes flows. It's one thing to call the stat "workers" in the UI - which makes sense because the number of currently executing flows is conceptually equivalent to the number of active workers. But renaming "flow" to "worker" in the code makes no sense.

I question if having consistency between UI and internal details of our code is something we should strive for in all cases. The concept of the flow is a detail of distsql implementation, and a user should not be expected to understand these details.

Alternative wording for "DistSQL Flows Active, by node" is something along the lines of "number of DistSQL queries that are executing (in part) on node X". But "active DistSQL workers on node X" also works.

The "total number of active DistSQL flows on all nodes" stat is very hard to explain.  It is roughly the sum, for all running queries, of the number of nodes involved in that query. With the worker terminology, it's the total number of active DistSQL workers across all nodes. Either way, I'm not sure how useful is this stat. 
It can give you an idea of how widely queries are distributed (when comparing against the # of running queries); but then perhaps we want to instead divide this by the number of running queries and expose it as "average query distribution" (meaning that if it's 5, on distsql queries have 5 flows on 5 nodes on average).

**Comment by dianasaur323** [comment]
@couchand Sorry for the slow response to your comment. I think the distributed flow description needs to be a bit more accurate. We should either go with a really well defined "flow" or with worker, which I find intuitively easier to understand.

Latching onto what Radu said around internal terminology, I actually think DistSQL is also an internal term? Distributed SQL Queries, Total (Number of queries running through distributed SQL) seems fine to me?

Regarding flows by node, I'm grasping at straws, but perhaps one reason someone would want this would be to understand if certain nodes were hotter than others, and why? Would exposing average query distribution hide outliers, which is probably what people want to observe?

**Comment by RaduBerinde** [comment]
@dianasaur323 To be clear, I am proposing keeping the "per node" stat (which is indeed useful to see hot spots and imbalance) and replacing the "total # of flows" stat with "average query distribution". Note that "total # of flows" is different than "total # of distsql queries" (which we should keep).

**Comment by couchand** [comment]
If "a flow is not a worker" it seems pretty strange to make a chart showing a count of flows that we title as though it's a count of "workers".  It's actually showing something different than it says it's showing, which will be confusing for everyone: Cockroach devs using the chart for development, support when helping a client debugging, and a user-turned-contributor.  This all goes to the idea of Ubiquitous Language: "Translation blunts communication and makes knowledge crunching anemic ... A project needs a common language that is more robust than the lowest common denominator".

Changing DistSQL to Distributed SQL does seem like a net win.

@RaduBerinde the total flows chart has been dropped (see the latest screenshot).

**Comment by RaduBerinde** [comment]
A flow doesn't have to be a worker for the **count** of flows to be conceptually equivalent to a **count** of active workers. A car is not a parking space but the number of cars parked outside my building is the same as the number of occupied parking spaces.

I am good with naming it in terms of workers, or in a more generic description like the one I suggested above. I am against trying to document the term "flow" which we made up to talk about internal implementation (and may the "Ubiquitous Language" Gods strike me where I stand).

**Comment by RaduBerinde** [comment]
CC @andreimatei in case he has some thoughts here.

**Comment by couchand** [comment]
If I understand it correctly, the count of active flows won't be the count of active workers, then.  If a parking lot is completely full and the number of cars circulating looking for a spot is a large fraction of the total, then representing the number of occupied spots as the number of cars is misleading.

**Comment by RaduBerinde** [comment]
"Active flows" means flows which are currently executing. It does not include flows that are queued (circling cars).

**Comment by RaduBerinde** [comment]
(at least that's what I thought, I haven't looked at the code to see how we calculate it).
It's a good question whether we want the count to include queued flows (in which case, I agree that "workers" is not a good name).

**Comment by couchand** [comment]
Yes, it means the flow's "currently executing", but since it's running in a goroutine, as I understand it that flow might not be currently executing.  I guess without a precise definition for "worker" it's hard to know what the difference would be.  If it's not the same as a flow, what is it?  The goroutine running the flow, the thread or the processor, the flow scheduler that started it, or the node?  Or something else entirely?

All this is to say, "flows" has a nice precise definition that actually means something specific in our code.  I agree that it's important to explain it in a way that will be meaningful to a user.  But I don't think it's wise to introduce a new term that doesn't precisely describe what the statistic is showing.  As it is, we can point to a specific place in the code where the metric is calculated, and all the words around there say "flow", at least today.  In general I think the bar should be quite high to introduce a disconnect between the code that generates a metric and the label for the metric.

I've gone ahead and updated "DistSQL" to say "Distributed SQL" everywhere, and added some clarification in the description of the flows chart.  I'm inclined to leave "flows" in the title unless there's a strong opinion that this is bad.

**Comment by RaduBerinde** [comment]
If we keep flows, the tool tip should explain what they are. Along the lines of "DistSQL queries run on multiple nodes; the portion that is executed on a specific node is called a flow. The graphs show the number of flows running on each node."

**Comment by couchand** [comment]
That makes sense to add clarification, my last change expanded it a bit but I like your language better.  Updated.

**Comment by RaduBerinde** [comment]
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 65 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq3y5uXEW8qJrRYz9l6:-Kq3y5uXEW8qJrRYz9l7:b9qixlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L65)):*
> ```XML
>     <LineGraph
>       title="Distributed SQL Active Flows"
>       tooltip="Distributed queries run on multiple nodes, and a flow is the worker on a single node.  This is the number of flows on each node contributing to currently running distributed SQL queries."
> ```

Since we're keeping "flows", why are we also using the "worker" concept you have been arguing against?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050)*

**Comment by RaduBerinde** [comment]
CCing @knz also in case he has better suggestions for the titles/tooltips.

**Comment by knz** [comment]
Reviewed 2 of 7 files at r1, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/metrics.go, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq44MOGiJ7z-W_ZYPmQ:-Kq44MOIYrY8zx68UPSB:b-fqnesg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/sql/distsqlrun/metrics.go#L44)):*
> ```Go
> 	metaQueriesActive = metric.Metadata{
> 		Name: "sql.distsql.queries.active",
> 		Help: "Number of currently active distributed SQL queries"}
> ```

Number of distributed SQL queries currently active

---

*[pkg/sql/distsqlrun/metrics.go, line 50 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq444v_kGPsof0a5VZE:-Kq444v_kGPsof0a5VZF:bm44qw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/sql/distsqlrun/metrics.go#L50)):*
> ```Go
> 	metaFlowsActive = metric.Metadata{
> 		Name: "sql.distsql.flows.active",
> 		Help: "Number of currently active distributed SQL flows"}
> ```

Number of distributed SQL flows currently active

---

*[pkg/sql/distsqlrun/metrics.go, line 56 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq447jRuN8VrocFhsqA:-Kq447jRuN8VrocFhsqB:b99hqc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/sql/distsqlrun/metrics.go#L56)):*
> ```Go
> 	metaMemMaxBytes = metric.Metadata{
> 		Name: "sql.mem.distsql.max",
> 		Help: "Memory usage per sql statement for distsql"}
> ```

High water mark of the memory usage by SQL processors for distributed queries

---

*[pkg/sql/distsqlrun/metrics.go, line 59 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq448iqz5J573mqLZ9H:-Kq448iqz5J573mqLZ9I:b-foo950) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/sql/distsqlrun/metrics.go#L59)):*
> ```Go
> 	metaMemCurBytes = metric.Metadata{
> 		Name: "sql.mem.distsql.current",
> 		Help: "Current sql statement memory usage for distsql"}
> ```

Current memory usage by SQL processors for distributed queries

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-KpIM56BXTQ0-UrMPMAE:-Kq44TAoDF-HR3VC5Hmi:b-37g0ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/162af2a69be6b36d2bc745318cafcc62b927725e/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L56)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Nice.
</blockquote></details>

The total number of distributed SQL queries currently running ...

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 54 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq44pV-5vlPBKXfvDZc:-Kq44pV0U50f1kaVVPr8:b-lb66jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L54)):*
> ```XML
> 
>     <LineGraph
>       title="Distributed SQL Active Queries"
> ```

"Active distributed SQL queries"

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq44rj77YOXxrnB0LDa:-Kq44rj77YOXxrnB0LDb:baq324g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L64)):*
> ```XML
> 
>     <LineGraph
>       title="Distributed SQL Active Flows"
> ```

"Active flows supporting distributed SQL queries"

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 65 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-Kq3y5uXEW8qJrRYz9l6:-Kq44f7bjpoPc6QHD1n-:bgldykz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e21fa223bcaae0aa5c999e16b7755f1cc5fbc6/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Since we're keeping "flows", why are we also using the "worker" concept you have been arguing against?
</blockquote></details>

Yeah the word "worker" doesn't work for me at all. I suggest remove the first sentence altogether. Just keep "This is the number of ..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050)*

**Comment by dianasaur323** [comment]
The current approach you all have converged on sounds fine to me.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17050#-:-Kq4EYZS-AKBos-FBfjR:b-asoyl6)*

**Comment by couchand** [comment]
Can I get a final review from somebody on @cockroachdb/distsql please?

**Comment by RaduBerinde** [comment]
LGTM

**Comment by RaduBerinde** [comment]
Thanks @couchand!

**Pull request merged**
