### PR TITLE
kv/kvserver: allow the merge transaction to be pushed

### LINKED ISSUE #59308: kv: allow range merge txn to be pushed, even after lease transfer
Needed for non-blocking transactions: #52745.

Currently, the range merge transaction is [not allowed to be pushed](https://github.com/cockroachdb/cockroach/blob/10ba90ca5e68c5a78d73610e4a0a1ea0fb6eff95/pkg/kv/kvserver/replica_command.go#L564-L568) to a higher timestamp. In the case that it is pushed, the transaction will abort and retry. This poses an issue for non-blocking transactions, which will cause all writes to a range to be pushed. As is, this makes non-blocking transactions incompatible with range merges.

To fix this, we will need to allow the range merge transaction to be pushed, at least during its local range descriptor writes. The current proposal is to do something like https://github.com/cockroachdb/cockroach/pull/44090. We will stop observing the range merge's commit timestamp at the beginning of the transaction. Instead, we will manually refresh [1] the transaction immediately before the transaction's critical phase (i.e. immediately before issuing the `SubsumeRequest`). After doing so, we can observe the commit timestamp to block any future refreshes, though we don't expect to see any.

This will be enough to make range merges compatible with non-blocking transactions.

[1] @ajwerner will be adding support for this in or around #56588.

### PR DESCRIPTION
**Pull request by ajwerner**
Historically we have not allowed the merge transaction to be pushed. The
reason we disabled this was because of the hazard due to attempting to
refresh reads on the RHS of the merge after the SubsumeRequest has been
sent. The `SubsumeRequest` effectively freezes the RHS until the merge
commits or aborts. In order to side-step this hazard, this change ensures
that nothing should prevent the merge transaction from either committing
or aborting.

### kv/kvclient: add ManualRefresh support for transactions

This commit adds support for client-initiated refreshes of transactions.
The implementation is somewhat simplistic in that it hijacks existing
logic that occurs during the sending of a request. This makes the
implementation more uniform with the rest of the client library at
the cost of being somewhat awkward and implicit from a code-reading
perspective.

The motivation for this change is to provide the necessary tools to allow
the merge transaction to get pushed. The adoption follows in the next
commit.

Fixes #59308.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
This probably deserves some more advanced testing involving pushing the merge transaction after it has sent the `SubsumeRequest`.

**Review by nvb — COMMENTED** [review]
Thanks! :lgtm: 

> This probably deserves some more advanced testing involving pushing the merge transaction after it has sent the SubsumeRequest.

I'm going to be adding a test in to make sure that two ranges with `global_reads: true` can be merged, which will force the merge txn to get pushed when writing to local descriptors, so feel free to hold off on this test if you aren't feeling inspired to add it now.

> Reviewed 6 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-:-MTdGbY02r7SbDfQ1ART:b-8wsw7c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/sender.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdEzqD3ZRqdlMqwr7L:-MTdEzqD3ZRqdlMqwr7M:b-htyc1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0edc56ab84ded2967fab82d3661aac6e5ce8be63/pkg/kv/sender.go#L294)):*
> ```Go
> 	GetSteppingMode(ctx context.Context) (curMode SteppingMode)
> 
> 	// ForceRefreshTransaction attempts to refresh a transactions read timestamp
> ```

nit: same question about naming. Consider renaming to `ManualRefresh` and moving this next to `ManualRestart`.
___
*[pkg/kv/txn.go, line 1299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdEHo35Yi837t9dWXg:-MTdEHo35Yi837t9dWXh:b-oholue) ([raw file](https://github.com/cockroachdb/cockroach/blob/0edc56ab84ded2967fab82d3661aac6e5ce8be63/pkg/kv/txn.go#L1299)):*
> ```Go
> }
> 
> // ForceRefresh forces a refresh of the read timestamp of a transaction to
> ```

nit: did you consider the name `ManualRefresh` to parallel the existing `ManualRestart`?
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 2454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdFhxn1sZ1eycDcO7_:-MTdFhxn1sZ1eycDcO7a:b-4du09w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0edc56ab84ded2967fab82d3661aac6e5ce8be63/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2454)):*
> ```Go
> 				}
> 				require.NoError(t, <-errCh)
> 				require.NoError(t, txn.ForceRefresh(ctx))
> ```

Comment that the fact that this doesn't block on the testing machinery indicates that it's a no-op.
___
*[pkg/kv/kvserver/client_merge_test.go, line 1325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdGY66104F-qwbPGMx:-MTdGY66104F-qwbPGMy:bf1g6uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc1d7b869e9bbf74f3ecbc1f32e45afd63dc1e2a/pkg/kv/kvserver/client_merge_test.go#L1325)):*
> ```Go
> 	}
> 	if mergePostSplitTS.LessEq(splitTS) {
> 		t.Fatalf("expected merge to start before concurrent split, %v <= %v", mergePostSplitTS, splitTS)
> ```

`s/start before/finish after/`?

**Review by ajwerner — COMMENTED** [review]
>  so feel free to hold off on this test if you aren't feeling inspired to add it now.

Excellent

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-:-MTdQSU064hTfwzbnRx_:b3z4rhn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/sender.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdEzqD3ZRqdlMqwr7L:-MTdPtus-xL4HUlHkigY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0edc56ab84ded2967fab82d3661aac6e5ce8be63/pkg/kv/sender.go#L294)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: same question about naming. Consider renaming to `ManualRefresh` and moving this next to `ManualRestart`.
</blockquote></details>

Done.
___
*[pkg/kv/txn.go, line 1299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdEHo35Yi837t9dWXg:-MTdPvQ2CGVBP-iSMLjG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0edc56ab84ded2967fab82d3661aac6e5ce8be63/pkg/kv/txn.go#L1299)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: did you consider the name `ManualRefresh` to parallel the existing `ManualRestart`?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 2454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdFhxn1sZ1eycDcO7_:-MTdQ5gA6w2bsFFhIfoq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0edc56ab84ded2967fab82d3661aac6e5ce8be63/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2454)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Comment that the fact that this doesn't block on the testing machinery indicates that it's a no-op.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_merge_test.go, line 1325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60567#-MTdGY66104F-qwbPGMx:-MTdQPp_8Oji4sNJOj19:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc1d7b869e9bbf74f3ecbc1f32e45afd63dc1e2a/pkg/kv/kvserver/client_merge_test.go#L1325)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/start before/finish after/`?
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
