### PR TITLE
kv: cache RangeClosedTimestampPolicy in RangeCache, keep up to date

### PR DESCRIPTION
**Pull request by nvb**
Informs #52745.

This commit introduces the concept of a RangeClosedTimestampPolicy, which represents the policy used by the leaseholder of a range to establish and publish closed timestamps. The policy dictates how far in the past (lag) or in the future (lead) MVCC history is closed off. Currently, there are two RangeClosedTimestampPolicy:
- `LAG_BY_CLUSTER_SETTING`
- `LEAD_FOR_GLOBAL_READS`

After introducing these policies, the commit teaches the RangeCache about this information. In addition to a range's descriptor and lease, the cache will now maintain an up-to-date understanding of each range's closed timestamp policy.

Finally, the commit adds the policy to ClientRangeInfo and RangeInfo, so that the client <-> server RangeInfo protocol will ensure that the kv client is informed of each Range's closed timestamp policy and kept up to date when its cached information has gone stale.

Now that the kv client is aware of which ranges have configured their closed timestamps to serve global reads, it will be able to use this information in `CanSendToFollower` to target follower replicas for non-stale reads in read-only and read-write transactions.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Friendly ping on this.

**Review by andreimatei — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59505#-:-MSd8rl_D1fVKIC0MHeZ:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 1188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59505#-MSd8PgB3_t8sxxA0eZ8:-MSd8PgB3_t8sxxA0eZ9:b-dayx81) ([raw file](https://github.com/cockroachdb/cockroach/blob/78cf4740b55395216f4fe9f179761e4a95dea833/pkg/kv/kvclient/rangecache/range_cache.go#L1188)):*
> ```Go
> 	// cases where the two policies differ, we can't tell which one is old and
> 	// which is new. So we conservatively say that if the policy changes, we
> 	// will replace e with o. Closed timestamp policy changes are very rare, so
> ```

consider making it even more clear in this comment that the opposite decision is not really an option because then the cache would just be frozen to changes

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59505#-:-MSoUyYM13ieZ3RkTzkZ:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 1188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59505#-MSd8PgB3_t8sxxA0eZ8:-MSoUy9EDt-_zTrMDP4N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78cf4740b55395216f4fe9f179761e4a95dea833/pkg/kv/kvclient/rangecache/range_cache.go#L1188)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider making it even more clear in this comment that the opposite decision is not really an option because then the cache would just be frozen to changes
</blockquote></details>

Done.

**Pull request merged**
