### PR TITLE
monitoring: Added Splunk Dashboard xml files

### PR DESCRIPTION
**Pull request by fabiog1901**
Added helpful files to build your dashboards in Splunk using
Splunk HTTP Event Collector as your source.

Please see README.md for a detailed configuration example.

Epic: None

Release note (ops change): splunk dashboard templates
are available in the public repository under
/monitoring/splunk-dashboard/

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
Thanks for putting this up. Just update the commit message to follow standard formats and copy it over to the PR description before we merge.

Not strictly required but consider adding a `README` into the directory if there's any special info or nuance necessary to use these with splunk.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92330#-:-NHUy6E4Cu-nb0OJ27Eo:bwdoo5a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fabiog1901)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92330#-NHUxSMQCJxXyjbqnbw9):*
The commit message should follow this format:

```
migrations: Added Splunk Dashboard xml files

<add a note about how someone would use this>

Epic: None
Release note (ops change): splunk dashboard templates 
are available in the public repository under 
`/migrations/splunk-dashboard/`
```

First line usually has a package/category prefix.
Release notes are what get read and published by docs so this is where you can put customer-facing info.

Wrap newlines at 72 chars. Details are here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

**Review by andreimatei — COMMENTED** [review]
What "migrations" is the commit message talking about? Is it supposed to be "monitoring"?

Please put something in the dir's readme.md about how to set this up in splunk. The data is supposed to come from scraping the  prometheus vars, right? Googling did not immediately show me the connection between that and the "HTTP Event Collector".

Do you want a `docs-todo` label on this PR so that we hopefully get some proper docs?

Btw, can you attach a screenshot to give a taste of what it looks like?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92330#-:-NHV-iCxAk7jdRaydS3F:brxh1l5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @fabiog1901)

**Comment by fabiog1901** [comment]
Updated the files and added the README.md as requested. Below is what the Overview dashboard looks like.

image

**Review by dhartunian — COMMENTED** [review]
> What "migrations" is the commit message talking about? Is it supposed to be "monitoring"?

Sorry @andreimatei that was my bad. wires crossed when commenting.

Thanks for the detailed readme @fabiog1901. Once you squash and fix the commit description we should be good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92330#-:-NIILv0uESa4noi0OoZ0:brqxwjc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fabiog1901)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92330#-NHUxSMQCJxXyjbqnbw9):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

The commit message should follow this format:

```
migrations: Added Splunk Dashboard xml files

<add a note about how someone would use this>

Epic: None
Release note (ops change): splunk dashboard templates 
are available in the public repository under 
`/migrations/splunk-dashboard/`
```

First line usually has a package/category prefix.
Release notes are what get read and published by docs so this is where you can put customer-facing info.

Wrap newlines at 72 chars. Details are here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages
</blockquote></details>

This note should appear in the commit as well. Please squash PR into a single commit with a description identical to the PR.

**Review by dhartunian — APPROVED** [review]
LGTM. I pushed a squashed version of commits.

**Pull request merged**
