### PR TITLE
storage: restore nullability to avoid upgrade woes

### LINKED ISSUE #15819: storage: (*Replica).handleEvalResult called on Replica with zero in-memory, nonzero on-disk Lease
We were calling `handleEvalResult` on a replica that had zero Lease state, but nonzero on-disk Lease state.

```
F170509 20:02:12.165939 136 storage/replica.go:1353  [n5,s5,r2/5:/System/{-tsd}] on-disk and in-memory state diverged:
[Lease.Start.WallTime: 1494353965502260882 != 0 Lease.Expiration.WallTime: 1494360140105540031 != 0 Lease.Replica.NodeID: 3 != 0 Lease.Replica.StoreID: 3 != 0 Lease.Replica.ReplicaID: 3 != 0 Lease.DeprecatedStartStasis.WallTime: 1494360140105540031 != 0 Lease.ProposedTS: &hlc.Timestamp{WallTime:1494360131105562632, Logical:0} != nil]
```

Stack trace:

```
goroutine 136 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x1, 0x9e40b1c, 0x2c18620, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:858 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2c19e00, 0xc400000004, 0x24e206d, 0x12, 0x549, 0xc43631e000, 0x191)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:726 +0x56d
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f19ea15bd38, 0xc420cc2a50, 0x7f1900000004, 0x2, 0x1b4c4ef, 0x28, 0xc432ebb8a0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:158 +0x4b3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f19ea15bd38, 0xc420cc2a50, 0x1, 0xc400000004, 0x1b4c4ef, 0x28, 0xc432ebb8a0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7f19ea15bd38, 0xc420cc2a50, 0x1b4c4ef, 0x28, 0xc432ebb8a0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:162 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).assertStateRLocked(0xc420cd6000, 0x27e7060, 0xc4203f60b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1353 +0x40a
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).assertState(0xc420cd6000, 0x27e7060, 0xc4203f60b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1338 +0x8c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleEvalResult(0xc420cd6000, 0x7f19ea15bd38, 0xc420cc2a50, 0x0, 0xc42d6ca610, 0xe, 0x10, 0xc42d6ca620, 0xf, 0x10, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:790 +0x113
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc420cd6000, 0x7f19ea15bd38, 0xc420cc2a50, 0xc42d6ca5f0, 0x8, 0x29ba8b, 0x300000003, 0x3, 0x14bd0303a2756692, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3711 +0x837
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc420cd6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2878 +0xd70
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc420cbc000, 0x7f19ea15bd38, 0xc4330c6390, 0xc438324480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3110 +0xcc5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420cbc000, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3389 +0x172
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420183ef0, 0xc4206606e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:228 +0x24b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f19ea15bd38, 0xc421c36300)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4216984d0, 0xc4206606e0, 0xc421c29340)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad
```

### PR DESCRIPTION
**Pull request by tamird**
The previous change (c293630) was overzealous in marking this field
non-nullable, not realizing that doing so affects on-wire behaviour.
The result was nodes accepting trivial but non-nil leases as valid,
overwriting their memory state with them, and then crashing on a failed
assertion.

This changes documents the trap, and paves the way for a safer future
change.

Closes #15819.

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_proposal.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk5An950OZThvjOmld:-Kjk5An950OZThvjOmle:bqenfjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/replica_proposal.go#L621)):*
> ```Go
> 	// for a future change which makes storagebase.ReplicaState.Lease non-
> 	// nullable able to upgrade without crashing old nodes (see #15819).
> 	if newLease := rResult.State.Lease; newLease != nil && *newLease != (roachpb.Lease{}) {
> ```

If `newLease` is a pointer to a zero-valued lease, this block will be skipped, which means that `State.Lease` will never be set to nil and the assertion will still fail. 

---

*[pkg/storage/storagebase/state.proto, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk4V0lEbowkEVgZB4f:-Kjk4V0lEbowkEVgZB4g:by57g56) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/storagebase/state.proto#L55)):*
> ```protobuf
>   //
>   // Note that this message is both saved to disk and sent over the network.
>   // On disk, the lease is never nil (and never trivial), but it may be nil
> ```

That's not true. This proto is written to disk as a part of ReplicatedEvalResult with the nil lease. (I don't think the ReplicaState is ever written to disk on its own; it is a proto solely for its use in ReplicatedEvalResult). 

In `Replica.mu.state`, however, this field is guaranteed to be non-nil. 

Nit: Use "zero-valued" instead of "trivial". 

---

*[pkg/storage/storagebase/state.proto, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk6BE9rBu8dREY4Qzw:-Kjk6BE9rBu8dREY4Qzx:b-fit5p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/storagebase/state.proto#L58)):*
> ```protobuf
>   // when sent over the network as part of ReplicatedEvalResult.
>   //
>   // TODO(tamird): make this field non-nullable when an upgrade path exists.
> ```

Please remove this TODO. This is exactly a case where the distinction between nil and empty matters; we gain nothing by making this non-nullable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_proposal.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk5An950OZThvjOmld:-Kjk8eVv0WSq9D1Zw9aF:b-b6xklq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/replica_proposal.go#L621)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If `newLease` is a pointer to a zero-valued lease, this block will be skipped, which means that `State.Lease` will never be set to nil and the assertion will still fail. 
</blockquote></details>

Good point. Now that I'm paged back in, @bdarnell is right: this field is likely going to be nullable forever, and it makes sense for it to be that way, so no upgrade path is needed/desired.

---

*[pkg/storage/storagebase/state.proto, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk4V0lEbowkEVgZB4f:-Kjk8G_gNWFFaxUu7gq8:b-remgvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/storagebase/state.proto#L55)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

That's not true. This proto is written to disk as a part of ReplicatedEvalResult with the nil lease. (I don't think the ReplicaState is ever written to disk on its own; it is a proto solely for its use in ReplicatedEvalResult). 

In `Replica.mu.state`, however, this field is guaranteed to be non-nil. 

Nit: Use "zero-valued" instead of "trivial". 
</blockquote></details>

Sorry @tamird, mislead you here - the persisted lease of the on-disk replica state is never nil, but that isn't persisted as part of `ReplicaState` (just the `Lease` directly), and of course @bdarnell is right that it'll be on disk in the Raft log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_proposal.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk5An950OZThvjOmld:-Kjk7jergh-TE2PE_Zxq:b-iet1gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/replica_proposal.go#L621)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Good point. Now that I'm paged back in, @bdarnell is right: this field is likely going to be nullable forever, and it makes sense for it to be that way, so no upgrade path is needed/desired.
</blockquote></details>

My understanding was that it's not legal for newLease to be a pointer to a zero-valued lease. Done anyway, though.

---

*[pkg/storage/storagebase/state.proto, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk4V0lEbowkEVgZB4f:-Kjk8iXrCW3u3ThurcmM:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/storagebase/state.proto#L55)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

That's not true. This proto is written to disk as a part of ReplicatedEvalResult with the nil lease. (I don't think the ReplicaState is ever written to disk on its own; it is a proto solely for its use in ReplicatedEvalResult). 

In `Replica.mu.state`, however, this field is guaranteed to be non-nil. 

Nit: Use "zero-valued" instead of "trivial". 
</blockquote></details>

Updated.

---

*[pkg/storage/storagebase/state.proto, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk6BE9rBu8dREY4Qzw:-Kjk8kjMKtgPliZ_l68V:bh5trwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/storagebase/state.proto#L58)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Please remove this TODO. This is exactly a case where the distinction between nil and empty matters; we gain nothing by making this non-nullable. 
</blockquote></details>

The gain is in the semantics of the value of `Replica.mu.state`. As you point out above, it isn't strictly necessary for `Replica.mu.state` to be of this type (it can be a similar type with a value, rather than pointer, lease).

I've updated the TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830)*

**Comment by tschottdorf** [comment]
Reviewed 11 of 11 files at r1.
Review status: 8 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_proposal.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-Kjk5An950OZThvjOmld:-KjkAxsJqiAlbK_5_l4f:b9v284z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d1412f05de6073fcfc88e0a8814c2e2b423c19e/pkg/storage/replica_proposal.go#L621)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

My understanding was that it's not legal for newLease to be a pointer to a zero-valued lease. Done anyway, though.
</blockquote></details>

Your guard is basically correct, but Ben was pointing out that it wasn't actually future-proofing the upgrade path: If you had the code under discussion here running, and it was talking to a newer version that didn't have the field nullable, you'd receive `newLease == roachpb.Lease{}`, *not* set `rResult.State.Lease = nil`, and so the assertion at the bottom (which checks that `rResult.State == trivial{}` would fail (though at least you wouldn't clobber your in-memory state). You would have to have a top-level separate

```go
if rResult.State.Lease != nil && *rResult.State.Lease = (roachpb.Lease{}) {
  rResult.State.Lease = nil // for assertion, as the real path below
}
```

It's so easy to get these things wrong...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-:-KjkC_yQaBvu9Ha68yjL:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15830#-:-KjmwjdW5PhfF4HB5Pu5:bnfp4nl)*

**Comment by tamird** [comment]
TFYRs!

**Pull request merged**
