### PR TITLE
opt: fix stats estimation for geospatial index join condition

### LINKED ISSUE #51924: geoindex: example query not using inverted indexes
Repro:

* import https://github.com/otan-cockroach/geospatial_data/blob/master/osm_iceland/osm_iceland.sql with IMPORT PGDUMP
* run
```
select distinct on (p.way) p.way as way,l.highway as int_tc_type
	       from planet_osm_point p
	       join planet_osm_line l
	        on ST_DWithin(p.way,l.way, 100)
	       join (values
	        ('tertiary',1),
	        ('unclassified',2),
	        ('residential',3),
	        ('living_street',4),
	        ('service',5)
	       ) as v (highway,prio)
	        on v.highway=l.highway
	       where p.highway='turning_circle'
	       order by p.way,v.prio;
```

This plan does not use the inverted index and takes super long compared to PostGIS. Maybe it's the DISTINCT.

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, the estimated selectivity of a geospatial
join condition such as `st_dwithin(g1, g2, 100)` was 1/3. However,
this is in contrast to the estimated selectivity of an inverted
join operation, which is 1/100. This commit brings these two
cases in line so that the selectivity of a geospatial join
condition is 1/100.

Fixes #51924

Release note (performance improvement): Modified the cardinality
estimate for index-accelerated geospatial functions to make it more
likely for the optimizer to choose a geospatial inverted index join
during query planning. This results in more efficient plans in
most cases.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51963)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @otan, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKM8jC-a1FfrS5HtT2:-MDKM8jC-a1FfrS5HtT3:b-pu01la) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/memo/statistics_builder.go#L1131)):*
> ```Go
> 	}
> 
> 	if join.Op() == opt.InvertedJoinOp || hasGeoIndexJoinCond(h.filters) {
> ```

what causes `join.Op() == opt.InvertedJoinOp` to not be true, but `hasGeoIndexJoinCond()` to return true?
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKCcDWCTEFDjJVJAGH:-MDKCcDWCTEFDjJVJAGI:b-ps87ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L73)):*
> ```
> 	way GEOMETRY(POINT,3857) NULL,
> 	INVERTED INDEX planet_osm_point_way_idx (way),
> 	FAMILY "primary" (osm_id, access, "addr:housename", "addr:housenumber", "addr:interpolation", admin_level, aerialway, aeroway, amenity, area, barrier, bicycle, brand, bridge, boundary, building, capital, construction, covered, culvert, cutting, denomination, disused, ele, embankment, foot, "generator:source", harbour, highway, historic, horse, intermittent, junction, landuse, layer, leisure, lock, man_made, military, motorcar, name, "natural", office, oneway, operator, place, population, power, power_source, public_transport, railway, ref, religion, route, service, shop, sport, surface, toll, tourism, "tower:type", tunnel, water, waterway, wetland, width, wood, z_order, way, rowid)
> ```

where is this `rowid` coming from (it isn't in the earlier column list) -- is this the implicit primary key? 
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 1705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKLNkc0CHtYJr2-NZJ:-MDKLNkc0CHtYJr2-NZK:bmhbdgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L1705)):*
> ```
> opt format=show-stats
> SELECT
>     DISTINCT ON (p.way) p.way AS way, l.highway AS int_tc_type
> ```

where did we discover this query, or did we make it up?
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 1760 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKIdjS3-baEpKPVw2L:-MDKIdjS3-baEpKPVw2M:b8o2aq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L1760)):*
> ```
>       │         │    │    ├── inverted-expr
>       │         │    │    │    └── st_dwithin(p.way:69, l.way:140, 100.0)
>       │         │    │    ├── stats: [rows=3926737.36, distinct(29)=1, null(29)=0]
> ```

is this the output row count? Seems equal to the left row count `2632` multiplied by `149189/100` due to the `1/100`th selectivity. The stats for the enclosing `inner-join` that applies the `st_dwithin` filter to eliminate false positives look the same so we don't have a notion of false positives being removed by that inner-join, yes?
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 1762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKHcf3-iXHmP3ppNRw:-MDKHcf3-iXHmP3ppNRx:b-va8hy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L1762)):*
> ```
>       │         │    │    ├── stats: [rows=3926737.36, distinct(29)=1, null(29)=0]
>       │         │    │    ├── fd: ()-->(29)
>       │         │    │    ├── select
> ```

just curious: why is `p.highway` not being dropped after the select filter has been applied? And it seems to me that the `DISTINCT (p.way)` could be pushed down here before the inverted join (though given that all `p.way` values are distinct in this case it would not make the join do less work).

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51963)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @otan, and @sumeerbhola)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKM8jC-a1FfrS5HtT2:-MDKa4b7EqP8Fzs_4J_g:bu4ayuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/memo/statistics_builder.go#L1131)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what causes `join.Op() == opt.InvertedJoinOp` to not be true, but `hasGeoIndexJoinCond()` to return true?
</blockquote></details>

We always need to wrap the inverted join in a regular lookup join with the primary index in order to get back the original geospatial column and any other columns needed by the query. The problem was that the cardinality estimate of the regular lookup join was way higher than the inverted join, but they should be exactly the same (since we're using the primary key to look up into the primary index). The filter condition with the geospatial function will always be on the outer join since we need the original geospatial column.
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKCcDWCTEFDjJVJAGH:-MDKbFNA8sjRu6bCstqb:bijzims) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L73)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where is this `rowid` coming from (it isn't in the earlier column list) -- is this the implicit primary key? 
</blockquote></details>

Yea, rowid is the implicit primary key that is automatically created if there is no primary key in the schema.
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 1705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKLNkc0CHtYJr2-NZJ:-MDKbMfP8wfzubnO9F2i:bc8qfcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L1705)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where did we discover this query, or did we make it up?
</blockquote></details>

@otan found it. Should I include a reference to a particular website for either the schema/data or the query, Oliver?
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 1760 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKIdjS3-baEpKPVw2L:-MDKboiV22EBMyvjp8lb:bplbmso) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L1760)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this the output row count? Seems equal to the left row count `2632` multiplied by `149189/100` due to the `1/100`th selectivity. The stats for the enclosing `inner-join` that applies the `st_dwithin` filter to eliminate false positives look the same so we don't have a notion of false positives being removed by that inner-join, yes?
</blockquote></details>

We don't have a notion of false positives being removed yet. The 1/100 estimate is so rough that I think adding another constant for false positive removal wouldn't be very helpful. This PR is at least making the row count estimate for the enclosing inner join the same as the estimate for the inverted join. Prior to this PR it was over 30x *higher*, which is clearly wrong.
___
*[pkg/sql/opt/xform/testdata/external/planet-osm, line 1762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKHcf3-iXHmP3ppNRw:-MDKdR1gCa9LYZ8_BUa0:b-o6lmv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/xform/testdata/external/planet-osm#L1762)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just curious: why is `p.highway` not being dropped after the select filter has been applied? And it seems to me that the `DISTINCT (p.way)` could be pushed down here before the inverted join (though given that all `p.way` values are distinct in this case it would not make the join do less work).
</blockquote></details>

We might be missing some rules for column pruning or pushing down distinct with this new operator, but it may also not be possible given the way exploration rules and normalization rules are interleaved in the optimizer. I'll need to spend some time digging into this (but any fix would be separate from this PR).

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-MDKM8jC-a1FfrS5HtT2:-MDKibf60Qyoy2tpovyf:bpqyi5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/33eda2a6746d2afcdf23cadee94aeb93a42bb51d/pkg/sql/opt/memo/statistics_builder.go#L1131)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We always need to wrap the inverted join in a regular lookup join with the primary index in order to get back the original geospatial column and any other columns needed by the query. The problem was that the cardinality estimate of the regular lookup join was way higher than the inverted join, but they should be exactly the same (since we're using the primary key to look up into the primary index). The filter condition with the geospatial function will always be on the outer join since we need the original geospatial column.
</blockquote></details>

(correction: the row count estimate of the outer lookup join should actually be lower to account for  the filter condition removing the false positives, but at least now it's not higher...)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-:-MDKoY0x2FcMJU0UANY3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson, @otan, and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51963#-:-MDKtkNW4Y4xaXtGZsOZ:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mjibson, @otan, and @sumeerbhola)

**Review by madelynnblue — APPROVED** [review]

**Comment by rytaft** [comment]
TFTRs!

bors r+

**Pull request merged**
