### PR TITLE
sql: implement XA transaction SQL statements

### LINKED ISSUE #137325: sql/tests: TestRandomSyntaxGeneration failed [unexpected statement: *tree.RollbackPrepared]
sql/tests.TestRandomSyntaxGeneration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/18179422?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/18179422?buildTab=artifacts#/) on master @ [49cff91f3501494deaf038671bc643c194a0e3ca](https://github.com/cockroachdb/cockroach/commits/49cff91f3501494deaf038671bc643c194a0e3ca):

Random syntax error:

```
    rsg_test.go:964: Crash detected: server panic: pq: internal error: unexpected statement: *tree.RollbackPrepared
```
Query:

```
        ROLLBACK PREPARED 'string';
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #132558 sql/tests: TestRandomSyntaxGeneration failed [CREATE TENANT statement is not valid after parsing then formatting] [C-test-failure O-robot P-2 T-db-server branch-release-24.1.6-rc]
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxGeneration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by nvb**
Informs #22329.
Closes #137325.

This PR implements the statement handling for `PREPARE TRANSACTION <gid>`, `COMMIT PREPARED <gid>`, and `ROLLBACK PREPARED <gid>`, for parity with Postgres support. The implementation is based on the Postgres documentation and the Postgres source code.

The PR then implements the `pg_catalog.pg_prepared_xacts` system catalog table, which reads from `system.prepared_transactions`. This adds the remaining PG compatibility, so that XA in CockroachDB looks near-identical to XA in PostgreSQL.

Finally, the PR fixes the `pgjdbc` blocklist to reflect the current state of support for XA transactions in CockroachDB. With the newly added support for two-phase commit transactions, all tests in the `XADataSourceTest` test suite now pass except for `mappingOfConstraintViolations`, which is blocked by https://github.com/cockroachdb/cockroach/issues/31632 (DEFERRABLE foreign keys).

Release note (sql change): XA transaction support allows CockroachDB to participate in distributed transaction with other resources (e.g. databases, message queues, etc) using a two phase commit protocol.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work! i reviewed the final 3 commits of this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-:-OEKeWd0EhzHM2d_QjVp:b-ayn5p7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @nvanbenschoten)

___
*[`pkg/sql/two_phase_commit.go` line 227 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKc6T-BAKuH9mm9BOL:-OEKc6T-BAKuH9mm9BOM:brjobql) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L227)):*
nit: in most of our user facing docs we use the term "admin role" instead of "superuser" so let's make this say something like
> Must have the admin role or be the same user as the one that prepared the transaction.
___
*[`pkg/sql/two_phase_commit.go` line 49 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKWs-G2Mtou7n94kb4:-OEKWs-G2Mtou7n94kb5:b-1dhgyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L49)):*
> ```Go
> 	if prepareErr != nil {
> 		if rbErr := ex.state.mu.txn.Rollback(ctx); rbErr != nil {
> 			log.Warningf(ctx, "txn rollback failed: err=%s", rbErr)
> ```

just confirming; is it correct to not short-circuit here? the state machine will advance to the `NoTxn` state, but I'm not sure what that means if the transaction never rolled back.
___
*[`pkg/sql/two_phase_commit.go` line 66 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKXHLLER8v1A5Gu3ee:-OEKXHLLER8v1A5Gu3ef:basqk2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L66)):*
> ```Go
> 	// TODO(nvanbenschoten): why are these needed here (and in the equivalent
> 	// functions for commit and rollback)? Shouldn't they be handled by
> 	// connExecutor.resetExtraTxnState?
> ```

i'm curious what happened when these `close`s weren't added here?
___
*[`pkg/sql/two_phase_commit.go` line 81 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKXS4z-DKVoomwPHVW:-OEKXS4z-DKVoomwPHVX:bjf8gzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L81)):*
> ```Go
> 	// which would prevent it from being prepared.
> 	if ex.extraTxnState.descCollection.HasUncommittedDescriptors() {
> 		return errors.Errorf("cannot prepare transaction: uncommitted descriptors")
> ```

nit: could the error say something more user facing, like "cannot prepare a transaction that has already performed schema changes"

and should it have an error code like `InvalidTransactionState` (25000)?
___
*[`pkg/sql/two_phase_commit.go` line 86 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEK_G0C75j-LiAjcvre:-OEK_G0C75j-LiAjcvrf:b-nl67ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L86)):*
> ```Go
> 	// TODO(nvanbenschoten): add a Txn.Key method to get the transaction's key,
> 	// instead of using TestingCloneTxn.
> 	txnProto := ex.state.mu.txn.TestingCloneTxn()
> ```

nit: just curious if there are any known gotchas with using this testing function here. if so, including them in the comment would be useful.
___
*[`pkg/sql/two_phase_commit.go` line 97 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEK_V2gDc3eQDDoJQcZ:-OEK_V2gDc3eQDDoJQc_:b-8jx8r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L97)):*
> ```Go
> 		ctx,
> 		ex.server.cfg.InternalDB.Executor(),
> 		nil, /* sqlTxn */
> ```

is it correct to use a separate transaction for this?

as long as it is, then the more conventional approach would be to pass in the `InternalDB`, and then use `internalDB.DescsTxn(...)` or `internalDB.Txn(...)` in the callee. these are useful since they take care of some setup/teardown of the transaction.
___
*[`pkg/sql/two_phase_commit.go` line 110 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKaAve-E3jyGeO0BB0:-OEKaAve-E3jyGeO0BB1:b871t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L110)):*
> ```Go
> 		// v24.3 is no longer necessary.
> 		if pgerror.GetPGCode(err) == pgcode.UndefinedTable {
> 			return pgerror.Newf(pgcode.FeatureNotSupported, "PREPARE TRANSACTION unsupported in mixed-version cluster")
> ```

nit: instead of having this check here, let's make the first step of `execPrepareTransactionInOpenStateInternal` be something like:
```
	ex.planner.EvalContext().Settings.Version.IsActive(...)
```

the planner should already be set by this point, since that happens in the beginning of `execStmtInOpenState`
___
*[`pkg/sql/two_phase_commit.go` line 170 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKbow9B_QBZcv-AhT1:-OEKbowA8MVIkzeUmNij:b-aq3ixo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L170)):*
> ```Go
> 	err = deletePreparedTransaction(
> 		ctx,
> 		ex.server.cfg.InternalDB.Executor(),
> ```

similar comment as above, let's pass in `InternalDB` here instead.
___
*[`pkg/sql/two_phase_commit.go` line 278 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKcheTA0Xf8lCPFR6F:-OEKcheTA0Xf8lCPFR6G:b-2dj9zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L278)):*
> ```Go
> 		// TODO(nvanbenschoten): Remove this logic when mixed-version support with
> 		// v24.3 is no longer necessary.
> 		if pgerror.GetPGCode(err) == pgcode.UndefinedTable {
> ```

similar comment as above; we can eagerly check for the mixed version state and short-circuit
___
*[`pkg/internal/sqlsmith/sqlsmith.go` line 371 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKWKvx3z1c4ALdB-_U:-OEKWKvyE_P-YcEEiwN7:b-wejnjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/internal/sqlsmith/sqlsmith.go#L371)):*
> ```Go
> 		{2, makeCommit},
> 		{2, makeRollback},
> 		// TODO(nvanbenschoten): add two-phase commit statements.
> ```

do we already have tracking issues for the testing work that we are postponing for later?
___
*[`pkg/sql/pg_catalog.go` line 2426 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKdVn_3B9qZ4HyKRrG:-OEKdVn_3B9qZ4HyKRrH:bdvruqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e87e1785e0848864422293c7fc772debd097928/pkg/sql/pg_catalog.go#L2426)):*
> ```Go
> 	schema: vtable.PGCatalogPreparedXacts,
> 	populate: func(ctx context.Context, p *planner, dbContext catalog.DatabaseDescriptor, addRow func(...tree.Datum) error) error {
> 		rows, err := p.InternalSQLTxn().QueryBufferedEx(
> ```

this virtual table could be implemented as a view on system.prepared_transactions. those are generally easier to maintain, so we prefer that approach. take a look at pg_shdescription for example: https://github.com/cockroachdb/cockroach/blob/e235962cd824ddc585276609aedbfd9b47b6ef14/pkg/sql/pg_catalog.go#L1824-L1833

to implement the mixed version check, the view can additionally execute the `crdb_internal.is_at_least_version` function.

**Review by nvb — COMMENTED** [review]
TFTR! I've rebased this on master now that the KV PR has landed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-:-OELen296nsq76WZ4M8d:b-ate2p5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rafiss)

___
*[`pkg/internal/sqlsmith/sqlsmith.go` line 371 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKWKvx3z1c4ALdB-_U:-OELX7cnC5xNgPwTxIKK:b-cyf1hu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/internal/sqlsmith/sqlsmith.go#L371)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we already have tracking issues for the testing work that we are postponing for later?
</blockquote></details>

I opened https://github.com/cockroachdb/cockroach/issues/137636 to track this additional testing work. We can add to it if we think of anything more.
___
*[`pkg/sql/pg_catalog.go` line 2426 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKdVn_3B9qZ4HyKRrG:-OELeWlK9Su2xDtlrl-l:bv672vr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e87e1785e0848864422293c7fc772debd097928/pkg/sql/pg_catalog.go#L2426)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this virtual table could be implemented as a view on system.prepared_transactions. those are generally easier to maintain, so we prefer that approach. take a look at pg_shdescription for example: https://github.com/cockroachdb/cockroach/blob/e235962cd824ddc585276609aedbfd9b47b6ef14/pkg/sql/pg_catalog.go#L1824-L1833

to implement the mixed version check, the view can additionally execute the `crdb_internal.is_at_least_version` function.
</blockquote></details>

This almost works, but I'm struggling to get the handling of the non-existent table in the mixed-version case working correctly? Any suggestions for how to express that in SQL?
___
*[`pkg/sql/two_phase_commit.go` line 49 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKWs-G2Mtou7n94kb4:-OELYCrG0wxit6OGuyOz:b-d6ydvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L49)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just confirming; is it correct to not short-circuit here? the state machine will advance to the `NoTxn` state, but I'm not sure what that means if the transaction never rolled back.
</blockquote></details>

I don't think there's anything better we can do here. If the rollback fails then I guess the kv transaction is going to need to time out. Failing to advance the sql state machine to NoTxn doesn't really accomplish anything.

This is the same kind of logic that we have in `connExecutor.rollbackSQLTransaction`.
___
*[`pkg/sql/two_phase_commit.go` line 66 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKXHLLER8v1A5Gu3ee:-OELYKOI7Sf1SDORNfGh:b8qdayi) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L66)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm curious what happened when these `close`s weren't added here?
</blockquote></details>

Nothing bad happened, IIRC. I just noticed this when copying over some of this logic from `commitSQLTransactionInternal`. I kept the logic for symmetry, but I don't understand why it's needed in either place. Probably not necessary to bottom out on this here.
___
*[`pkg/sql/two_phase_commit.go` line 81 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKXS4z-DKVoomwPHVW:-OELYTTH3lbtrDEPP8wq:bx4nh62) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L81)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could the error say something more user facing, like "cannot prepare a transaction that has already performed schema changes"

and should it have an error code like `InvalidTransactionState` (25000)?
</blockquote></details>

Done and done.
___
*[`pkg/sql/two_phase_commit.go` line 86 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEK_G0C75j-LiAjcvre:-OELYVf2EeIykjeMUjNQ:b-er7iun) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L86)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: just curious if there are any known gotchas with using this testing function here. if so, including them in the comment would be useful.
</blockquote></details>

No gotchas. I think it's just named like this because we at one point decided that exposing the raw proto from the transaction was a "bad API" which should only be used in tests.

I addressed the TODO in a new commit.
___
*[`pkg/sql/two_phase_commit.go` line 97 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEK_V2gDc3eQDDoJQcZ:-OELYZkK8CQfT0vLNTmL:bxk3rx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L97)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is it correct to use a separate transaction for this?

as long as it is, then the more conventional approach would be to pass in the `InternalDB`, and then use `internalDB.DescsTxn(...)` or `internalDB.Txn(...)` in the callee. these are useful since they take care of some setup/teardown of the transaction.
</blockquote></details>

These need to use a separate transaction, because we don't want the bookkeeping in the `system.prepared_transactions` table to be part of the prepared transaction.

The `internalDB.DescsTxn(...)` or `internalDB.Txn(...)` approaches seem like a lot more boilerplate for kicking off a single-statement, implicit transaction. Is there a benefit to using them over passing a nil transaction?

The other benefit of the approach here is that I can call it with a nil transaction (and unbound Executor) in `cleanupAfterFailedPrepareTransaction` and the SQL transaction (and bound Executor) in `deletePreparedTxn`.

Happy to go with whatever approach you think is best.
___
*[`pkg/sql/two_phase_commit.go` line 110 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKaAve-E3jyGeO0BB0:-OELYnHK-iPXo-zgmYEJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L110)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: instead of having this check here, let's make the first step of `execPrepareTransactionInOpenStateInternal` be something like:
```
	ex.planner.EvalContext().Settings.Version.IsActive(...)
```

the planner should already be set by this point, since that happens in the beginning of `execStmtInOpenState`
</blockquote></details>

Done.
___
*[`pkg/sql/two_phase_commit.go` line 227 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKc6T-BAKuH9mm9BOL:-OELY2O1EeVE30nc3p7a:bj7e84w) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L227)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: in most of our user facing docs we use the term "admin role" instead of "superuser" so let's make this say something like
> Must have the admin role or be the same user as the one that prepared the transaction.
</blockquote></details>

This hint message comes straight from PG, so I figured I'd keep it identical. See https://github.com/postgres/postgres/blob/7a80e381d16c642d00ec6146ccdf1262a159c69e/src/backend/access/transam/twophase.c#L587.

Happy to change it if you feel strongly.
___
*[`pkg/sql/two_phase_commit.go` line 278 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKcheTA0Xf8lCPFR6F:-OELYq8-8zmq1HYqzaFy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L278)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar comment as above; we can eagerly check for the mixed version state and short-circuit
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @nvanbenschoten)

___
*[`pkg/sql/pg_catalog.go` line 2426 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKdVn_3B9qZ4HyKRrG:-OELiqiR55VUK78P5k5q:b-3h58vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e87e1785e0848864422293c7fc772debd097928/pkg/sql/pg_catalog.go#L2426)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This almost works, but I'm struggling to get the handling of the non-existent table in the mixed-version case working correctly? Any suggestions for how to express that in SQL?
</blockquote></details>

ah good point. i don't know a way around resolving the table name.

but since we do have a planner here, let's have this populate function short-circuit with a `p.IsActive` check rather than using error codes to learn if it's a mixed version state.
___
*[`pkg/sql/two_phase_commit.go` line 49 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKWs-G2Mtou7n94kb4:-OELfFWNEeuUXQQytFz_:br4x9zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think there's anything better we can do here. If the rollback fails then I guess the kv transaction is going to need to time out. Failing to advance the sql state machine to NoTxn doesn't really accomplish anything.

This is the same kind of logic that we have in `connExecutor.rollbackSQLTransaction`.
</blockquote></details>

i believe there is one state transition failure case where we simply end the session. i can't seem to find it now though, so i'm fine with leaving this as is.
___
*[`pkg/sql/two_phase_commit.go` line 66 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKXHLLER8v1A5Gu3ee:-OELi8Mf22BS63ySmCt3:b-9faroy) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nothing bad happened, IIRC. I just noticed this when copying over some of this logic from `commitSQLTransactionInternal`. I kept the logic for symmetry, but I don't understand why it's needed in either place. Probably not necessary to bottom out on this here.
</blockquote></details>

i see, thanks for explaining! i will take a cursory look into the history here separate from this PR.
___
*[`pkg/sql/two_phase_commit.go` line 97 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEK_V2gDc3eQDDoJQcZ:-OELgrEiEMISEc97DWZF:b-mr10j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L97)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

These need to use a separate transaction, because we don't want the bookkeeping in the `system.prepared_transactions` table to be part of the prepared transaction.

The `internalDB.DescsTxn(...)` or `internalDB.Txn(...)` approaches seem like a lot more boilerplate for kicking off a single-statement, implicit transaction. Is there a benefit to using them over passing a nil transaction?

The other benefit of the approach here is that I can call it with a nil transaction (and unbound Executor) in `cleanupAfterFailedPrepareTransaction` and the SQL transaction (and bound Executor) in `deletePreparedTxn`.

Happy to go with whatever approach you think is best.
</blockquote></details>

i do think we should stick with `internalDB` here. IMO it makes it more clear to readers that a separate transaction is going to be initiated.

it also takes care of releasing descriptor leases, which isn't super relevant right now, but it's very easy to forget about that if the code is extended more later, or if somebody looks at this as inspiration for a different function.

also IMO it's not a huge amount of boilerplate. it mostly comes down to a bit of added code indentation: https://github.com/cockroachdb/cockroach/blob/9f61a38b670e57873509568f67bb665e50cd1935/pkg/sql/show_cluster_setting.go#L58-L64
___
*[`pkg/sql/two_phase_commit.go` line 227 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKc6T-BAKuH9mm9BOL:-OELgLLa2p9H_Zx5TRJx:b8sw6zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L227)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This hint message comes straight from PG, so I figured I'd keep it identical. See https://github.com/postgres/postgres/blob/7a80e381d16c642d00ec6146ccdf1262a159c69e/src/backend/access/transam/twophase.c#L587.

Happy to change it if you feel strongly.
</blockquote></details>

thanks, i'm fine with using the term `superuser`
___
*[`pkg/sql/two_phase_commit.go` line 96 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OELgAV6-erh87Iow7x-:-OELgAV6-erh87Iow7x0:b-28qny5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2acda202b691786e3d7ecddee699c1eac878fc5/pkg/sql/two_phase_commit.go#L96)):*
> ```Go
> 	txnKey := txn.Key()
> 	if !txn.IsOpen() {
> 		return errors.AssertionFailedf("cannot prepare a transaction that is not open")
> ```

do we need one more check to make sure we're in an explicit transaction? if we're not in one, then it would be a user error.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129448)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 2426 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEKdVn_3B9qZ4HyKRrG:-OELpvzN8MWXwoSdF-y0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e87e1785e0848864422293c7fc772debd097928/pkg/sql/pg_catalog.go#L2426)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah good point. i don't know a way around resolving the table name.

but since we do have a planner here, let's have this populate function short-circuit with a `p.IsActive` check rather than using error codes to learn if it's a mixed version state.
</blockquote></details>

Done.
___
*[`pkg/sql/two_phase_commit.go` line 97 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEK_V2gDc3eQDDoJQcZ:-OELu-UC4aphOMlwdZGq:b-ihmyh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L97)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i do think we should stick with `internalDB` here. IMO it makes it more clear to readers that a separate transaction is going to be initiated.

it also takes care of releasing descriptor leases, which isn't super relevant right now, but it's very easy to forget about that if the code is extended more later, or if somebody looks at this as inspiration for a different function.

also IMO it's not a huge amount of boilerplate. it mostly comes down to a bit of added code indentation: https://github.com/cockroachdb/cockroach/blob/9f61a38b670e57873509568f67bb665e50cd1935/pkg/sql/show_cluster_setting.go#L58-L64
</blockquote></details>

Got it, I think I see how you wanted this to look. The nice part is that I now only need to pass one param (an `isql.Txn`) to these functions, instead of two (a `isql.Executor` and a `*kv.Txn`).

I put this cleanup in a separate commit to make it easier for you to review, to confirm that I'm understanding the suggestion correctly.

If you :thumbsup:, I'll squash the commit into the first one in this PR.
___
*[`pkg/sql/two_phase_commit.go` line 96 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OELgAV6-erh87Iow7x-:-OELr35i1siIUPS00P_Z:b-tf0va5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2acda202b691786e3d7ecddee699c1eac878fc5/pkg/sql/two_phase_commit.go#L96)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we need one more check to make sure we're in an explicit transaction? if we're not in one, then it would be a user error.
</blockquote></details>

That check is in `connExecutor.execStmtInNoTxnState`. There's a test for this in `two_phase_commit`, if you search for `there is no transaction in progress`.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-:-OEPIfeuCIdi6_oRNrbg:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @nvanbenschoten)

___
*[`pkg/sql/two_phase_commit.go` line 97 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/129448#-OEK_V2gDc3eQDDoJQcZ:-OEPHsIm0pt9qexwK6Oc:bpw5zzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee00cc8b8eec11a36ddd2e8b72fdfd6c9ebe0c2/pkg/sql/two_phase_commit.go#L97)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Got it, I think I see how you wanted this to look. The nice part is that I now only need to pass one param (an `isql.Txn`) to these functions, instead of two (a `isql.Executor` and a `*kv.Txn`).

I put this cleanup in a separate commit to make it easier for you to review, to confirm that I'm understanding the suggestion correctly.

If you :thumbsup:, I'll squash the commit into the first one in this PR.
</blockquote></details>

this looks great, thanks.

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
