### PR TITLE
opt: add support for some window frames

### PR DESCRIPTION
**Pull request by justinj**
This commit adds support for RANGE window frames that don't use OFFSET.

The remaining work for frames is:
* ROWS
* GROUPS
* OFFSET
* top-level window frames

Some material I've seen states that when a window function contains an
ORDER BY, the default FOLLOWING is CURRENT ROW, and otherwise it's
UNBOUNDED. It turns out this is actually incorrect - the default is
always CURRENT ROW.

The reason it might look like this is not true is that the semantics of
CURRENT ROW are such that the frame includes up to and including the
last "peer" of the row being considered, rather than the actual row
itself. A "peer" is a row that has the same values for the ORDER BY, and
so when there is an empty ORDER BY, every row in a partition is a peer,
and CURRENT ROW and UNBOUNDED have the same behaviour.

This peering behaviour can be seen in this query:
```
justin=# select * from x;
 a  | b
----+---
 10 | 1
 20 | 1
 30 | 1
 40 | 2
 50 | 2
 60 | 2
(6 rows)

justin=# select a, avg(a) over (order by b) from x;
 a  |         avg
----+---------------------
 10 | 20.0000000000000000
 20 | 20.0000000000000000
 30 | 20.0000000000000000
 40 | 35.0000000000000000
 50 | 35.0000000000000000
 60 | 35.0000000000000000
(6 rows)
```

UNBOUNDED PRECEDING to CURRENT ROW for each of the first three rows is
all of the first three rows, and for the last three rows it's the entire
partition (all the results).

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Cool stuff! Just some minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-:-Lex5hdJBw5BGLtYwaoo:b-j3bm8a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 3063 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex5mqQ2as_WV1_RlXf:-Lex5mqQ2as_WV1_RlXg:b-z1ryne) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/logictest/testdata/logic_test/window#L3063)):*
> ```
> 
> statement ok
> CREATE TABLE y (a INT PRIMARY KEY, b INT, c INT)
> ```

[nit] make the table name `abc`
___
*[pkg/sql/opt/memo/interner.go, line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex6BuI80OnWFD6k6Cx:-Lex6BuI80OnWFD6k6Cy:b-tgnj5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/memo/interner.go#L777)):*
> ```Go
> 	}
> 
> 	return l.Bounds.StartBound.BoundType == r.Bounds.StartBound.BoundType &&
> ```

Do we need to check the `Mode`?
___
*[pkg/sql/opt/optbuilder/scope.go, line 1015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex4oow9vxZapdUJYu7:-Lex4oow9vxZapdUJYu8:b-8gvqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/scope.go#L1015)):*
> ```Go
> 	}
> 
> 	if f.Frame.Mode != tree.RANGE ||
> ```

[nit] add parens (or split into separate `if`s), I actually didn't know OTOH what the precedence between `||` and `&&` is..
___
*[pkg/sql/opt/optbuilder/window.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex5EbX5qpTAXmEkJcW:-Lex5EbX5qpTAXmEkJcX:bf3zube) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/window.go#L150)):*
> ```Go
> 		// TODO(justin): check if these really need to be pointers in the AST node.
> 		if windowFrames[i].Bounds.StartBound == nil {
> 			windowFrames[i].Bounds.StartBound = &tree.WindowFrameBound{
> ```

My guess is that they don't, but the parser has to put it on the heap anyway so there's no cost to making it a pointer (as far as parsing is concerned at least).

These default values could be singletons.
___
*[pkg/sql/opt/optbuilder/testdata/window, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex6UHZCb7hEn84BzW6:-Lex6UHZCb7hEn84BzW7:bmbthr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/testdata/window#L897)):*
> ```
>       │    └── columns: k:1(int!null) v:2(int) w:3(int) f:4(float) d:5(decimal) s:6(string) b:7(bool)
>       └── windows
>            └── windows-item: from unbounded to current-row [type=decimal]
> ```

[nit] No idea if this is a good suggestion or not, but we could elide the default "from unbounded to current-row" to simplify the output

**Review by yuzefovich — COMMENTED** [review]
Nice work! LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-:-Lex7N5R8Fgo5ApAzLVc:b-kbrev2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex57aw4dsjGzzdcKMv:-Lex57aw4dsjGzzdcKMw:byzenh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/scope.go#L1017)):*
> ```Go
> 	if f.Frame.Mode != tree.RANGE ||
> 		f.Frame.Bounds.StartBound != nil &&
> 			f.Frame.Bounds.StartBound.BoundType == tree.OffsetPreceding ||
> ```

I think you're missing a couple of cases here: for example, `RANGE BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING` and `RANGE BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING` will be "supported" while they actually are not (yet).
___
*[pkg/sql/opt/optbuilder/window.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex6ocCEp7EQMt6oLU0:-Lex6ocCEp7EQMt6oLU1:b-ysuk15) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/window.go#L148)):*
> ```Go
> 		// Fill this in with the default so that we don't need nil checks
> 		// elsewhere.
> 		// TODO(justin): check if these really need to be pointers in the AST node.
> ```

I don't think they need to be pointers (not sure what was the reason that I used pointers in this case, maybe I was thinking it'd be more efficient, but these structs are very small, so it shouldn't matter).

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 7 of 19 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-:-Lf25NKT9F00Ta3Xps-I:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 3063 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex5mqQ2as_WV1_RlXf:-Lf-rMmn7ypqJpCcTOih:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/logictest/testdata/logic_test/window#L3063)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] make the table name `abc`
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/interner.go, line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex6BuI80OnWFD6k6Cx:-Lf-rQSW423M6OHv7Xpf:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/memo/interner.go#L777)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we need to check the `Mode`?
</blockquote></details>

Good call, done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex4oow9vxZapdUJYu7:-Lf-rjzc42j4SnZm8qfs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/scope.go#L1015)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add parens (or split into separate `if`s), I actually didn't know OTOH what the precedence between `||` and `&&` is..
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex57aw4dsjGzzdcKMv:-Lf-sMup3NpwWmJ5raiQ:b-kqc62) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/scope.go#L1017)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think you're missing a couple of cases here: for example, `RANGE BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING` and `RANGE BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING` will be "supported" while they actually are not (yet).
</blockquote></details>

Ah, I didn't even realize you could mix-and-match that way!
___
*[pkg/sql/opt/optbuilder/window.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex6ocCEp7EQMt6oLU0:-Lf64_Am-difQWBARZQW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/window.go#L148)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think they need to be pointers (not sure what was the reason that I used pointers in this case, maybe I was thinking it'd be more efficient, but these structs are very small, so it shouldn't matter).
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/window.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex5EbX5qpTAXmEkJcW:-Lf1f29uBJ42ARXKOa_r:b-c45s99) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/window.go#L150)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

My guess is that they don't, but the parser has to put it on the heap anyway so there's no cost to making it a pointer (as far as parsing is concerned at least).

These default values could be singletons.
</blockquote></details>

My hope was to avoid the nil checks, but upon further reflection having them isolated here seems ok. Made them singletons.
___
*[pkg/sql/opt/optbuilder/testdata/window, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex6UHZCb7hEn84BzW6:-Lf1cNsoAY2iHaiKfoKD:b-1q6gpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/testdata/window#L897)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] No idea if this is a good suggestion or not, but we could elide the default "from unbounded to current-row" to simplify the output
</blockquote></details>

Done. I went back and forth because I originally felt like window functions aren't widely-understood enough to be eliding things, but OTOH, most uses won't have to worry about the frame at all (hopefully) and so eliding things is a little friendlier (and it's just way more readable).

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-:-LfUvGfJA9fsnDdaJkVv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct_on, line 306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-LfUuLiuDlMds_vt_GoJ:-LfUuLiv3k8rjGjZXQll:bu64d4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3524e3d7795780f103729eae8e77604e3b5d19c/pkg/sql/opt/exec/execbuilder/testdata/distinct_on#L306)):*
> ```
>       │              distinct on  row_number                                                             ·                ·
>       └── window     ·            ·                                                                      (y, row_number)  ·
>            │         window 0     row_number() OVER (RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)  ·                ·
> ```

[nit] consider eliding the default frame info here too
___
*[pkg/sql/opt/optbuilder/window.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex5EbX5qpTAXmEkJcW:-LfUv0BU6zs-vQthSNIB:b5y8q3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/window.go#L150)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

My hope was to avoid the nil checks, but upon further reflection having them isolated here seems ok. Made them singletons.
</blockquote></details>

It would be reasonable to make these always non-nil (populate them with the default value during parsing).

**Review by justinj — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-:-LfVAkHfCH8bvRDcewlg:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct_on, line 306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-LfUuLiuDlMds_vt_GoJ:-LfV3O743gKaMdXnTIF2:biq1coc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3524e3d7795780f103729eae8e77604e3b5d19c/pkg/sql/opt/exec/execbuilder/testdata/distinct_on#L306)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] consider eliding the default frame info here too
</blockquote></details>

This is kind of gross and noisy but I think changing it the right way would involve making some changes to the parser and stringifier that I'd rather punt on for the time being.
___
*[pkg/sql/opt/optbuilder/window.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37534#-Lex5EbX5qpTAXmEkJcW:-LfV6eULAYe7e5NHp0IK:bcezinj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f92feb028aeebc69216b1ed2247ddce7b8d98109/pkg/sql/opt/optbuilder/window.go#L150)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It would be reasonable to make these always non-nil (populate them with the default value during parsing).
</blockquote></details>

This is definitely a good idea, but I'd rather punt on this too just because I don't want to get deep into parser stuff at the moment.

**Comment by justinj** [comment]
Weird looking failure, seems like a flake.

bors r+

**Pull request merged**
