### PR TITLE
mixedversion: add public API to disable individual mutators and rename `finalize` step

### PR DESCRIPTION
**Pull request by renatolabs**
With this API, tests are now able to disable individual mutators if
they are incompatible with the test (e.g., setting a cluster setting
that conflicts with what the test is trying to do). Tests should be
able to disable mutators with something like the following:

```go
mvt := mixedversion.NewTest(...,
    mixedversion.DisableMutators(mixedversion.ClusterSetting("foo")),
)
```

Note: this is just an example -- individual mutator implementatios are not
yet available.

**mixedversion: rename `finalizeUpgrade` step to `allowUpgrade`**
In the near future, we will randomly change the timing of this step so
that it is not immediately followed by migrations, as the name
previously suggested.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
This PR combines two minor steps that brings us closer to the first mutator implementation.

### Context: mixedversion test mutators

This PR is part of a larger effort to introduce the concept of plan _mutators_ to the mixedversion framework. For initial discussion, see [internal thread](https://cockroachlabs.slack.com/archives/C01UDP33CCS/p1700252725103829).

In short, mutators are components that modify (i.e., mutate) the original test plan generated by the mixedversion planner. These changes are supposed to introduce new test scenarios in ways that do not interfere with the vast majority of tests. Tests will have the ability to individually enable or disable specific mutators as necessary; by default, all mutators will apply under some probability.

There is a working implementation of the entire idea in the [rc/mixedversion-plan-mutators](https://github.com/renatolabs/cockroach/tree/rc/mixedversion-plan-mutators) branch, in case it is helpful to see parts of the entire picture. That branch includes the proposed mutator API and an implementation of a mutator that, when merged, will close #111595.

#### History

* #115118: where we introduced the `upgradePlan` data structure and allows the upgrade to isolate the steps associated with each upgrade performed during the test.
* #117498: where we removed the `ID()` function from `singleStepProtocol`, allowing IDs to be assigned to steps later in 
the process, after the entire plan has been generated (and, now, mutations have been applied).
* #117993 is one of the pillars of this work, defining the interface to be implemented by mutators, as well as how the mutations they produce are applied to the original test plan.

**Comment by renatolabs** [comment]
Rebased on top of current master to fix conflicts with recent changes (notably, #118333).

This is a small, incremental PR that shouldn't take too long to review. Mixed-version tests [pass](https://teamcity.cockroachdb.com/viewLog.html?buildId=13768774&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv) on this branch.

**Review by DarrylWong — COMMENTED** [review]
One small comment on the datadriven tests but otherwise LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118441#-:-NpWhUQiDIDQFw2hWoF8:bnmxlv9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go` line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118441#-NpWfr2a8BPpxqhJzbBt:-NpWfr2a8BPpxqhJzbBu:b-g2gaf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5387e6390ddbf80ff6a50780d5d859b2bf3e65c9/pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go#L62)):*
> ```Go
> 	originalMutators := planMutators
> 	resetMutators := func() {
> 		planMutators = originalMutators
> ```

`planMutators` is the actual list of mutators that will be available for mixed version tests right? As opposed to `remove_user_hooks` which is only available here.

If so, do we want to pull from that for these planner tests? I'm just envisioning a scenario where we have to change every test whenever we add a new mutator. Depending on how complex you expect these tests to be it might be easier to start from an empty list and add on mutators as needed.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118441)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go` line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118441#-NpWfr2a8BPpxqhJzbBt:-Np_oCyf6fMq_JWHVFwM:b-yoju28) ([raw file](https://github.com/cockroachdb/cockroach/blob/5387e6390ddbf80ff6a50780d5d859b2bf3e65c9/pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go#L62)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

`planMutators` is the actual list of mutators that will be available for mixed version tests right? As opposed to `remove_user_hooks` which is only available here.

If so, do we want to pull from that for these planner tests? I'm just envisioning a scenario where we have to change every test whenever we add a new mutator. Depending on how complex you expect these tests to be it might be easier to start from an empty list and add on mutators as needed.
</blockquote></details>

I like the idea; making them explicit will reduce noisy diffs and will allows us to be explicit about which mutators we're testing. Done, thanks for the suggestion.

**Review by DarrylWong — APPROVED** [review]

**Comment by renatolabs** [comment]
TFTR!

bors r=DarrylWong

**Pull request merged**
