### PR TITLE
Revert "kvstreamer: re-enable streamer by default"

### PR DESCRIPTION
**Pull request by yuzefovich**
This reverts commit b72c10955f5fab3f4d069568169d09a1934cbe15.

Informs: #78145.

### CODE REVIEW

**Comment by yuzefovich** [comment]
I have a suspicion that the streamer has increased the frequency of timeouts on the staging branch when bors'ing PRs.

**Review by cucaroach — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78201#-:-Myi8Tif1Q9BPmyPHXXp:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Never mind, I finally see an easy face-palm problem.

bors r-

**Pull request closed without merging**
