### PR TITLE
opt: calculate constraints lazily

### PR DESCRIPTION
**Pull request by RaduBerinde**
Instead of calculating constraints for every boolean expression, we
calculate them only when needed.

Building of constraints is triggered by `FiltersOp`, and constraints
are built recursively.

Note that most `build` tests are missing constraints because the
Filters operator is not present.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 42 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfKr6Y1OdU_8QOR-vH:-LCfKr6Y1OdU_8QOR-vI:bn56h36) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/logical_props_builder.go#L585)):*
> ```Go
> 
> 	// Calculate constraints for any expressions that could be filters.
> 	if ev.Operator() == opt.FiltersOp || ev.Operator() == opt.TrueOp || ev.Operator() == opt.FalseOp {
> ```

NIT: seems like a place for a `switch`

---

*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LCfMAyo3xCdY2gWdJg4:b-k6wvgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
> ```
>       │         └── max [type=int, outer=(1)]
>       │              └── variable: a.x [type=int, outer=(1)]
>       └── in [type=bool, outer=(4)]
> ```

I bet Rebecca was relying on the constraints being calculated in order to test that correct stats are generated. We'll have to figure out a good way to still do this. A couple ideas:

1. Use `opt` command instead.
2. Change optbuilder to construct the `Filters` operators itself - this would also have benefit of being slightly faster (but not sure if constraint builder would be able to look past non-flattened Filters)
3. Change `build` command to run several "required" optimizations
4. Add a new `buildnorm` command that runs several "required" optimizations

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfO3bWEO8keq-WnumZ:-LCfO3bWEO8keq-Wnum_:bp63jxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/norm/testdata/rules/decorrelate#L289)):*
> ```
>  │    │    │    │    └── filters [type=bool, outer=(7)]
>  │    │    │    │         └── is-not [type=bool, outer=(7)]
>  │    │    │    │              ├── eq [type=bool, outer=(7)]
> ```

How come this isn't annotated with a constraint, since it's under a `Filters` operator?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 42 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LChlf1NCUPuDUcCA6_1:b1x861w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I bet Rebecca was relying on the constraints being calculated in order to test that correct stats are generated. We'll have to figure out a good way to still do this. A couple ideas:

1. Use `opt` command instead.
2. Change optbuilder to construct the `Filters` operators itself - this would also have benefit of being slightly faster (but not sure if constraint builder would be able to look past non-flattened Filters)
3. Change `build` command to run several "required" optimizations
4. Add a new `buildnorm` command that runs several "required" optimizations
</blockquote></details>

@rytaft what do you think? I like option 2, I think it would work. Note that even without this change, `build` tests can't expect the constraints code to do its job in all cases because it may rely on scalar normalization rules; so it's just up to the testcase to use reasonable expressions.

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfO3bWEO8keq-WnumZ:-LChmFka5fpVo3wncKMT:be4pqof) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/norm/testdata/rules/decorrelate#L289)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come this isn't annotated with a constraint, since it's under a `Filters` operator?
</blockquote></details>

I guess we don't support `(IsNot (Eq ..) False)`. So the recursive constraint building stops there. Note that before this change, we still didn't have any constraints for `filters` itself. We just had this useless constraint on a sub-expression.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LCijDud54E123InFErm:b-yxvjdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

@rytaft what do you think? I like option 2, I think it would work. Note that even without this change, `build` tests can't expect the constraints code to do its job in all cases because it may rely on scalar normalization rules; so it's just up to the testcase to use reasonable expressions.
</blockquote></details>

Yea, we definitely need to make sure the constraints are built before the stats code runs. I don't think using `opt` would make a difference, since the stats will only be calculated once for each memo group. Option 2 seems like a good idea, but I think it may need to be combined with option 3 or 4 if the filter needs to be flattened.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LCikoXl28M6Wz8tXFA9:b30qokn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Yea, we definitely need to make sure the constraints are built before the stats code runs. I don't think using `opt` would make a difference, since the stats will only be calculated once for each memo group. Option 2 seems like a good idea, but I think it may need to be combined with option 3 or 4 if the filter needs to be flattened.
</blockquote></details>

Oh never mind - `opt` will probably work since the normalization transformations happen before the logical properties are calculated, correct?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 42 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LCiltrRD8piwDIX9_7e:bqtjqrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Oh never mind - `opt` will probably work since the normalization transformations happen before the logical properties are calculated, correct?
</blockquote></details>

Right, when normalization is on, we always have the normalized structure by the time we calculate constraints.

The only reason not to use `opt` is if we are testing some particular subtrees which would be harder to generate when rules are on.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 49 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfKr6Y1OdU_8QOR-vH:-LCjVwMl3Q6U8Y3TeUeG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/logical_props_builder.go#L585)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: seems like a place for a `switch`
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LCjW0CX83cBmeJBmvYb:bvhqw1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

No - try option 2 in order to keep the same subtrees (like you pointed out). I mean update the places in `optbuilder` where we call `ConstructSelect` and `constructJoin`
</blockquote></details>

Ok, done (in a separate commit). It seems to be working well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by rytaft** [comment]
Reviewed 3 of 42 files at r1, 1 of 1 files at r2, 2 of 31 files at r3.
Review status: 5 of 49 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LCjbstU49VgulykiFnc:bxedqnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ok, done (in a separate commit). It seems to be working well.
</blockquote></details>

You need to add filters in `optbuilder/groupby.go` for the HAVING filter as well.

Otherwise, looks good

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/memo/testdata/stats/groupby, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-LCfMAyo3xCdY2gWdJg3:-LCjiXNv3UL8cYGdsYVP:b5ly7sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5572a91d30a3d50cfdcb8d56f8d799b2001e64aa/pkg/sql/opt/memo/testdata/stats/groupby#L183)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

You need to add filters in `optbuilder/groupby.go` for the HAVING filter as well.

Otherwise, looks good
</blockquote></details>

Oh, great catch, thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r4.
Review status: 6 of 50 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-:-LCjnijQ7FOH41YSxdX_:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 6 of 50 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25593#-:-LCjqkCTBhAkeyKOFmbn:bnfp4nl)*

**Pull request merged**
