### PR TITLE
sql: fix decimal evaluation edge cases

### LINKED ISSUE #40929: sql: internal error: (-0E-2019):::DECIMAL: could not evaluate -0E-2019 as Datum type DDecimal from string "0E-2019": could not parse "0E-2019" as type decimal
```
CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT g FROM generate_series(NULL, NULL) AS g;

SELECT 0 / '-Infinity'::DECIMAL FROM tab_orig;
```

```
stack trace:
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/expr.go:78: processExpression()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/expr.go:161: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:145: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:776: InitWithEvalCtx()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:752: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/tablereader.go:92: newTableReader()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/processors.go:138: NewProcessor()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:165: makeProcessor()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:65: setupProcessors()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:48: Setup()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:331: setupFlow()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:404: SetupLocalSyncFlow()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:241: setupFlows()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:330: Run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:966: PlanAndRun()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:826: execWithDistSQLEngine()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:718: dispatchToExecutionEngine()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417: execStmtInOpenState()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98: execStmt()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1238: execCmd()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1167: run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:444: ServeConn()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584: func1()
runtime/asm_amd64.s:1337: goexit()
```

Jira issue: CRDB-5499

### LINKED ISSUE #103633: sql: 0::decimal/infinity returns 0E-2019 instead of 0
In PG:

```
otan=# select 0::decimal/'infinity';
 ?column?
----------
        0
(1 row)
```

In CRDB:

```
root@:26257/defaultdb> select 0::decimal/'infinity';
  ?column?
------------
  0E-2019
(1 row)


Time: 1ms total (execution 1ms / network 1ms)
```

The reason why it uses `E-2019` is because it uses the [HighPrecisionCtx](https://github.com/cockroachdb/cockroach/blob/b6f9e62b9940da5989f91b25019fb4574924163b/pkg/sql/sem/tree/decimal.go#L37-L38) to divide. We should probably not do that (or make the `apd` library not do that in `Divide`)

Note this is reporting correctly for non-infinity:
```
root@:26257/defaultdb> select 0 / 5::decimal;
  ?column?
------------
         0
(1 row)


Time: 1ms total (execution 1ms / network 0ms)
```

Issue from https://github.com/cockroachdb/cockroach/pull/102299

Jira issue: CRDB-28105

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, the logic for decimal and float division, floor division and mod operators was incorrect for a few edge cases involving `NaN` or `Infinity` values. For example, `'NaN'::DECIMAL / 0` would throw a division-by-zero error when it should evaluate to `NaN` and `0/'inf'::DECIMAL` returned `0E-2019` instead of just `0`.

This patch updates the special-case logic to mirror that of postgres, so division-by-zero errors always check the `NaN` case and the division by infinity case returns a `0` without extra digits.

Fixes #40929
Fixes #103633

Release note (bug fix): Fixed edge cases in decimal and float evaluation for division operators. `'NaN'::DECIMAL / 0` will now return `NaN` instead of a division-by-zero error, and `0 / 'inf'::DECIMAL` will return `0` instead of `0E-2019`.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106472)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-tMLi8i2I3kFiBdnv):*
Nice! We probably should've fixed it long time ago :sweat_smile: You should also adjust `sqlsmith` roachtest to remove the skip for the error due to #40929.
___
*[`pkg/sql/sem/tree/datum.go` line 1168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-rPSN5zlVuhGiyOob:-N_-rPSN5zlVuhGiyOoc:btglsxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/59ed56c2ffe487af86928dfc9c8e90ea18d9768a/pkg/sql/sem/tree/datum.go#L1168)):*
> ```Go
> 
> 	// DNaNDecimal is the decimal constant 'NaN'.
> 	DNaNDecimal = &DDecimal{Decimal: apd.Decimal{Form: apd.NaN}}
> ```

nit: it doesn't look like `DNaNDecimal` and `DPosInfDecimal` are used in other packages, so maybe not export them?
___
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-slbc554C8SYmC6dQ:-N_-slbc554C8SYmC6dR:bpsng7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/59ed56c2ffe487af86928dfc9c8e90ea18d9768a/pkg/sql/logictest/testdata/logic_test/decimal#L484)):*
> ```
> NaN        Infinity   NaN                      NaN   NaN
> -Infinity  NaN        NaN                      NaN   NaN
> -Infinity  -Infinity  0                        NaN   NaN
> ```

There are some minor differences from postgres in this table. I think `Inf % Inf` in PG returns NaN whereas we now return 0. It'd be good to adjust these queries a bit to add `ORDER BY x1, x2` and compare so that we match PG exactly.
___
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-tCUEDTUt9q99xKLD:-N_-tCUF6oqP7GCrz1Qh:b-mmarho) ([raw file](https://github.com/cockroachdb/cockroach/blob/59ed56c2ffe487af86928dfc9c8e90ea18d9768a/pkg/sql/logictest/testdata/logic_test/decimal#L627)):*
> ```
> # infinity. The results should only have one digit each.
> statement ok
> CREATE TABLE regression_40929 AS SELECT g FROM generate_series(1, 1) AS g;
> ```

nit: since we have `generate_series(1, 1)` we could simply it to just `VALUES (1)`, right?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106472)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-tMLi8i2I3kFiBdnv):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Nice! We probably should've fixed it long time ago :sweat_smile: You should also adjust `sqlsmith` roachtest to remove the skip for the error due to #40929.
</blockquote></details>

Good catch, Done.
___
*[`pkg/sql/sem/tree/datum.go` line 1168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-rPSN5zlVuhGiyOob:-N_0Psfc1P0pfMVfo8-S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59ed56c2ffe487af86928dfc9c8e90ea18d9768a/pkg/sql/sem/tree/datum.go#L1168)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it doesn't look like `DNaNDecimal` and `DPosInfDecimal` are used in other packages, so maybe not export them?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-slbc554C8SYmC6dQ:-N_0XnXE6bD-a4A8Do58:bqmpm8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/59ed56c2ffe487af86928dfc9c8e90ea18d9768a/pkg/sql/logictest/testdata/logic_test/decimal#L484)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

There are some minor differences from postgres in this table. I think `Inf % Inf` in PG returns NaN whereas we now return 0. It'd be good to adjust these queries a bit to add `ORDER BY x1, x2` and compare so that we match PG exactly.
</blockquote></details>

Oh, good catch - the infinity checks should check that the left side is `Finite`, not that it isn't `NaN`. I added an id column to ensure the ordering, since postgres is different for both NULL and NaN.
___
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_-tCUEDTUt9q99xKLD:-N_0XQWO2s5oJtxVLjZm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59ed56c2ffe487af86928dfc9c8e90ea18d9768a/pkg/sql/logictest/testdata/logic_test/decimal#L627)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: since we have `generate_series(1, 1)` we could simply it to just `VALUES (1)`, right?
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-:-N_0Z-vQ3XNmccBzvXhJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106472)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @herkolategan, and @renatolabs)

___
*[`pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go` line 343 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_9z2tbA-qyfz-luwrw:-N_9z2tbA-qyfz-luwrx:byx73bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/38fe3e8dd2e42f907797aac770f8ae7b9abba83b/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L343)):*
> ```Go
> 					colexecerror.ExpectedError(err)
> 				}
>         {{if .CheckRightIsInf}}
> ```

nit: the indentation is a bit off.
___
*[`pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go` line 599 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_9z5Hm1AIEFtSnrnVm:-N_9z5Hm1AIEFtSnrnVn:b-5v3gaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/38fe3e8dd2e42f907797aac770f8ae7b9abba83b/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L599)):*
> ```Go
> 					colexecerror.ExpectedError(err)
> 				}
>         {{if .CheckRightIsInf}}
> ```

nit: ditto.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106472)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, and @yuzefovich)

___
*[`pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go` line 343 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_9z2tbA-qyfz-luwrw:-N_FrPY36fjKpUBdEtrZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38fe3e8dd2e42f907797aac770f8ae7b9abba83b/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L343)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the indentation is a bit off.
</blockquote></details>

Done.
___
*[`pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go` line 599 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106472#-N_9z5Hm1AIEFtSnrnVm:-N_FrOak0op0uAkATBul:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38fe3e8dd2e42f907797aac770f8ae7b9abba83b/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L599)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: ditto.
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
Failure is a known flake: #106579

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Pull request merged**
