### PR TITLE
rangefeed: unconditionally use mux rangefeeds

### PR DESCRIPTION
**Pull request by erikgrinaker**
**rangefeed: use mux rangefeeds by default**

Touches #113029.
Release note (performance improvement): rangefeeds, the infrastructure for changefeeds, now use a more efficient multiplexing protocol.

**kvclient: remove `kv.rangefeed.catchup_scan_concurrency`**

This is only used for non-mux rangefeeds, which will be disabled shortly.

Release note (ops change): the setting `kv.rangefeed.catchup_scan_concurrency` has been removed. Catchup scans are throttled via `kv.rangefeed.concurrent_catchup_iterators` on a per-node basis.

**streamingccl: remove `physical_replication.producer.mux_rangefeeds.enabled`**

The mux rangefeed protocol will be enabled unconditionally shortly.

**kvclient: remove `COCKROACH_ENABLE_MULTIPLEXING_RANGEFEED`**

Mux rangefeeds will be enabled unconditionally.

**changefeedccl: remove `changefeed.mux_rangefeed.enabled`**

Mux rangefeeds are now used unconditionally in changefeeds. The code options are left in place to retain test coverage in mixed-version clusters with old non-mux clients.

Release note (ops change): the cluster setting `changefeed.mux_rangefeed.enabled` has been removed, and is in effect always enabled.

**kvfeed: remove mux rangefeed config options**

This patch always uses mux rangefeeds in kvfeed, via the default rangefeed config. The legacy protocol may be used in metamorphic tests.

**rangefeed: remove `WithMuxRangefeed` option**

Mux rangefeeds are now always enabled, except when disabled in metamorphic tests. The corresponding DistSender option `kvcoord.WithMuxRangeFeed()` is retained for test coverage.

**kvcoord: invert `WithMuxRangeFeed` to `Without`**

This patch inverts the DistSender option `WithMuxRangeFeed` as `WithoutMuxRangeFeed`, to ensure callers always use mux rangefeeds unless they explicitly opt out (only in tests).

**kvpb: update `RangeFeed` method deprecation notice**

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@miretskiy I'm inclined to enable these unconditionally (i.e. remove the settings and parameters) so that we can remove the legacy rangefeed protocol in 24.2, wdyt?

There is also a mixed-version concern here: 24.1 nodes will start sending mux rangefeed requests to 23.2 nodes -- are we confident enough in the 23.2 implementation to do this?

**Comment by miretskiy** [comment]
> @miretskiy I'm inclined to enable these unconditionally (i.e. remove the settings and parameters) so that we can remove the legacy rangefeed protocol in 24.2, wdyt?
> 
> There is also a mixed-version concern here: 24.1 nodes will start sending mux rangefeed requests to 23.2 nodes -- are we confident enough in the 23.2 implementation to do this?

Let's enable unconditionally.  We do have a mix-version test for mux rangefeed.  You will need to change mixed_version_cdc.go if you decide to go the route of removing old implementation.

**Review by miretskiy — APPROVED** [review]

**Comment by erikgrinaker** [comment]
Ok, will update this to remove the setting when I get a chance.

**Comment by erikgrinaker** [comment]
Ok, I've updated this to unconditionally use mux rangefeeds, except in metamorphic tests. We still retain the DistSender client support along with the config option, to ensure we have test coverage of the legacy protocol for use in mixed-version clusters. PTAL.

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 4 of 5 files at r5, 5 of 5 files at r6, 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114408)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @herkolategan, @msbutler, and @renatolabs)

___
*[`pkg/ccl/changefeedccl/changefeedbase/settings.go` line 227 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFEZP4-JL1niRe_c-L:-NnFEZP4-JL1niRe_c-M:bo44ojm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62272f9a5fafa8dda1628179c8b46745d9dba18/pkg/ccl/changefeedccl/changefeedbase/settings.go#L227)):*
> ```Go
> var UseMuxRangeFeed = settings.RegisterBoolSetting(
> 	settings.ApplicationLevel,
> 	"changefeed.mux_rangefeed.enabled",
> ```

this needs to be added to the `retiredSettings` map in `settings/registry.go`
___
*[`pkg/ccl/streamingccl/settings.go` line 63 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFEjLM2ucGdAPw8f4s:-NnFEjLNDP8DcGMFk1XB:bnlx697) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62272f9a5fafa8dda1628179c8b46745d9dba18/pkg/ccl/streamingccl/settings.go#L63)):*
> ```Go
> var StreamProducerMuxRangefeeds = settings.RegisterBoolSetting(
> 	settings.SystemOnly,
> 	"physical_replication.producer.mux_rangefeeds.enabled",
> ```

needs to be added to retiredSettings map.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 434 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFFBl8D90ccnKYPS4T:-NnFFBl8D90ccnKYPS4U:b8i7wpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/905cbd097858e4c3f4285df03e6595aa88c2280e/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L434)):*
> ```Go
> 		return false, err
> 	}
> 	// changefeed.mux_rangefeed.enabled only exists in 22.2 to 23.2 inclusive.
> ```

nit: comment mentions non-existent setting.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 438 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFFLly2n7XdStLSZOE:-NnFFLlzEuicBWgk1lNB:b-cj57hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/905cbd097858e4c3f4285df03e6595aa88c2280e/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L438)):*
> ```Go
> 		return false, nil
> 	}
> 	if cv.AtLeast(roachpb.MustParseVersion(v241CV)) {
> ```

should it be !v241?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFFT7c2lMpTEk5qKBg:-NnFFT7c2lMpTEk5qKBh:b-ttmy1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62272f9a5fafa8dda1628179c8b46745d9dba18/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L78)):*
> ```Go
> var catchupScanConcurrency = settings.RegisterIntSetting(
> 	settings.ApplicationLevel,
> 	"kv.rangefeed.catchup_scan_concurrency",
> ```

add to retiredSettings.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114408)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @miretskiy, @msbutler, and @renatolabs)

___
*[`pkg/ccl/changefeedccl/changefeedbase/settings.go` line 227 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFEZP4-JL1niRe_c-L:-NnFdslu5M2hyiQIw-vh:b-m656pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62272f9a5fafa8dda1628179c8b46745d9dba18/pkg/ccl/changefeedccl/changefeedbase/settings.go#L227)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

this needs to be added to the `retiredSettings` map in `settings/registry.go`
</blockquote></details>

Good call, thanks. Added all retired settings.
___
*[`pkg/ccl/streamingccl/settings.go` line 63 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFEjLM2ucGdAPw8f4s:-NnFdxfa27aDIefz6iO3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62272f9a5fafa8dda1628179c8b46745d9dba18/pkg/ccl/streamingccl/settings.go#L63)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

needs to be added to retiredSettings map.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 434 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFFBl8D90ccnKYPS4T:-NnFeNu96wfHtWgY-9iK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/905cbd097858e4c3f4285df03e6595aa88c2280e/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L434)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: comment mentions non-existent setting.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 438 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFFLly2n7XdStLSZOE:-NnFeOtr3xIUTHp20aeP:b-tbys9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/905cbd097858e4c3f4285df03e6595aa88c2280e/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L438)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should it be !v241?
</blockquote></details>

No, the setting is removed in 24.1, so we return false in that case. But I rewrote the predicate to hopefully make it clearer.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/114408#-NnFFT7c2lMpTEk5qKBg:-NnFeYxbDbuh7VfzvDLs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62272f9a5fafa8dda1628179c8b46745d9dba18/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L78)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

add to retiredSettings.
</blockquote></details>

Done.

**Comment by erikgrinaker** [comment]
CI failure is unrelated.

TFTR!

bors r+

**Pull request merged**
