### PR TITLE
changefeedccl: Release alloc when filtering.

### PR DESCRIPTION
**Pull request by miretskiy**
Release event alloc when changefeed expression filter
does not match.

Release note: None

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

**Comment by miretskiy** [comment]
@HonoreDB Sorry, just pushed another change to this PR to also remove some of the functions.
Can you PTAL.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

**Pull request merged**
