### PR TITLE
release-21.2: kv: enforce minimum Raft snapshot rate limit

### PR DESCRIPTION
**Pull request by nvb**
Backport 1/1 commits from #76209.

/cc @cockroachdb/release

Release justification: adds a new guardrail.

---

Related to #75728.

This commit enforces a minimum Raft snapshot rate limit of 1mb/s. We've seen
recent problems (#75728) related to mis-configured cluster settings, so it's
best to protect ourselves from this kind of misconfiguration.

```
root@127.0.0.1:26257/movr> set cluster setting kv.snapshot_rebalance.max_rate = '8';
ERROR: invalid value for kv.snapshot_rebalance.max_rate: snapshot rate cannot be set to a value below 1.0 MiB: 8 B

root@127.0.0.1:26257/movr> set cluster setting kv.snapshot_rebalance.max_rate = '8Kib';
ERROR: invalid value for kv.snapshot_rebalance.max_rate: snapshot rate cannot be set to a value below 1.0 MiB: 8.0 KiB

root@127.0.0.1:26257/movr> set cluster setting kv.snapshot_rebalance.max_rate = '8Mib';
SET CLUSTER SETTING
```

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]

**Review by aayushshah15 — APPROVED** [review]

**Comment by tbg** [comment]
If someone is running with 1mb (or anything below the limit really) and
they pick up this patch, will anything bad happen?

(sent from mobile, please excuse my brevity)

**Comment by nvanbenschoten** [comment]
No, it doesn't look like it. The two places where we re-validate and set cluster settings from earlier settings state are:
https://github.com/cockroachdb/cockroach/blob/c690b74a2319f18209de672d822f7acfbb45fbb4/pkg/server/settings_cache.go#L150-L152
and
https://github.com/cockroachdb/cockroach/blob/c690b74a2319f18209de672d822f7acfbb45fbb4/pkg/server/settingswatcher/settings_watcher.go#L292-L294

Both of these log a warning to the logs, but nothing worse. I've confirmed that I see the two warnings in the logs when I set the setting to `8 B` then upgrade past this change.

**Comment by tbg** [comment]
Thanks! And the result (i.e. what the server will be running with) will be the default setting in that case? We should somehow point out on the patch release that this will force that cluster setting to at least 8mb.

**Comment by tbg** [comment]
I suppose the release note says that so it's fine.

**Pull request merged**
