### PR TITLE
opt: add statistics quality testing framework

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds a new framework for testing the quality of statistics
estimation in the optimizer. The new framework is built into the existing
data-driven testing framework of the optimizer, and it compares actual
and estimated stats for a given relational expression.

Each test case contains input of the form `CREATE TABLE <name> AS <query>`,
and it returns formatted tabular output of the actual and estimated stats
for the provided query, as well as the estimation error. If the test is run with
`-rewrite-actual-stats=true`, it will recalculate the actual statistics for the
given expression. Otherwise, it will reuse the actual stats in the test output
(calculated previously) to compare against the estimated stats.

The purpose of using the `CREATE TABLE AS` syntax is twofold:
1. When we calculate the actual statistics, we need to create a table
   so we can run `CREATE STATISTICS` on it.
2. By creating named tables for earlier queries in the test file, we can
   use the output of those queries as input to later queries. We can also
   inject the statistics for those tables and store them in the test
   catalog for use by later queries.

I have added statistics quality tests for TPC-C queries as part of this
first commit. Later PRs will include tests for TPC-H and the Join Order
Benchmark.

This first commit does not cause tests to fail based on bad stats (e.g.,
if the error surpasses a given threshold), and it does not calculate any
overarching measure of quality over all test cases. These items are left
for future PRs.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
This is awesome!

My only thought is that it's kind of hard to get an actual sense for the quality of the stats based on these tests since the test file is so large that you can't really eyeball it to see what's good or bad. I think one thing that would help that is having some kind of `import-schema` directive like we've talked about before. But besides that I'm not sure what would make these results more "scannable", or at least having some way to draw one's attention to the stats that appear to need the most attention? Maybe some kind of exportable dashboard? Not sure! Maybe this won't be a problem when the main mode of interaction with the stats is making a change to how they're computed and just checking the diff to see if the error got better or worse.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-Lcq1WAl9c_i8vSvQCBB:b6s6hud)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpcc, line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-Lcprc6I48PyI7wG0gUr:-Lcprc6J9oDTPqZY-g6H:b-f23eml) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/memo/testdata/stats_quality/tpcc#L1078)):*
> ```
> ----
> column_names  row_count  distinct_count  null_count
> {rowid}       1          1               0
> ```

is it possible (or desirable) to hide the `rowid`? I think it's just a consequence of a `create table as` not having a specified PK?
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-Lcq3cq-CjpkVBwifvHj:-Lcq3cq-CjpkVBwifvHk:b2quy5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L114)):*
> ```Go
> 		"null_count_err",
> 	}
> 	res := make([]string, len(columns), len(columns)*(estimatedStats.ColStats.Count()+1))
> ```

no real strong opinion but any reason you didn't make this a `[][]string` instead?
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-LcpsqCvDLW-g8ini143:-LcpsqCvDLW-g8ini144:b-vtftd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L142)):*
> ```Go
> 			}
> 
> 			res = append(res, colNames)
> ```

not a big difference, but `append` is variadic:
```
res = append(res,
  ...,
  ...,
  ...,
)
```
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-LcptROe0IIY7LMW8UzB:-LcptROe0IIY7LMW8UzC:bupzxeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L159)):*
> ```Go
> 	}
> 
> 	st.injectStats(st.table, jsonStats)
> ```

I think this could use some explanation, or maybe some kind of overarching comment describing the philosophy of the framework, explaining that the idea is that we decompose the actual queries into a bunch of smaller queries and incrementally compute the stats, which is why this injection is needed to allow the subsequent queries to work off of good stats rather than bad stats.
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-Lcq5Tqd5ZMKVei5q7pG:-Lcq5Tqd5ZMKVei5q7pH:byhbs25) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L325)):*
> ```Go
> // and actual values. It returns a value between 0 (no error) and
> // 1 (max error).
> func (st *statsTester) fractionErr(estimated, actual float64) float64 {
> ```

What's the motivation for this measure of error? I thought the standard error formula was `(actual - estimated)/estimated`?

Did you look into the [q-error](http://www.vldb.org/pvldb/2/vldb09-657.pdf) at all (I haven't yet put in the time to grok it, but it seems [somehow] designed specifically for this)?

**Review by RaduBerinde — COMMENTED** [review]
Very cool!

I have an idea that would make it easier to get data about non-root nodes: currently we have to split up the queries ourselves (which might get hard with complicated queries) , and it is unreliable because we might or might not get the exact same plans.

Suppose we had a `saveTableNode` plan node with one input which is a pass-through node, but it also sets up a `createTableNode` and feeds it a copy of every row. Seems relatively easy to set up.

We would create these nodes as needed from the execbuilder and run the query. One reasonable way would be to do it for all relational nodes up to a certain depth (with the depth configurable).

The wrinkle is that we're using an external server. We can add a hidden session setting that does this automatically for all queries. That might actually be very useful for manual testing as well - not just for stats, but suppose you're debugging a query with bad results, this will make it easy to check the intermediate results.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-Ld3psk07ygpFWVOcioZ:b407rp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

**Review by rytaft — COMMENTED** [review]
TFTRs!

> you can't really eyeball it to see what's good or bad

Yea, I agree. I added a "<==" next to each error that's above the q-error threshold. Does this help? Happy to change to a different character string or something else if you have a better idea.

> import-schema directive

Can you remind me what this is? I'm struggling to remember

> Suppose we had a saveTableNode plan node with one input which is a pass-through node, but it also sets up a createTableNode...

Good idea! I'm still a bit fuzzy on the details but I think this would work. This is going to take some time, though...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-Ld4QfWi0Y1nYKtiHogN:b9kvc52)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpcc, line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-Lcprc6I48PyI7wG0gUr:-Ld4S6aP4iU1eQYQK4nt:b-fwpmyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/memo/testdata/stats_quality/tpcc#L1078)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

is it possible (or desirable) to hide the `rowid`? I think it's just a consequence of a `create table as` not having a specified PK?
</blockquote></details>

Yea, I could definitely filter it out. I'll hold of on doing this until I try to implement Radu's suggestion, since that will probably change some things.
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-Lcq3cq-CjpkVBwifvHj:-Ld4SHyI5ndOwNW7N949:bc46try) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L114)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

no real strong opinion but any reason you didn't make this a `[][]string` instead?
</blockquote></details>

Yea, because `formatValues` takes a `[]string` (I just copied it from `logic.go`)
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-LcpsqCvDLW-g8ini143:-Ld4T7Nw4rDFJTrs-AnM:blqn8yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L142)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

not a big difference, but `append` is variadic:
```
res = append(res,
  ...,
  ...,
  ...,
)
```
</blockquote></details>

Nice - done.
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-LcptROe0IIY7LMW8UzB:-Ld4U43SDztloRJXPQYH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L159)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think this could use some explanation, or maybe some kind of overarching comment describing the philosophy of the framework, explaining that the idea is that we decompose the actual queries into a bunch of smaller queries and incrementally compute the stats, which is why this injection is needed to allow the subsequent queries to work off of good stats rather than bad stats.
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/opttester/stats_tester.go, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-Lcq5Tqd5ZMKVei5q7pG:-Ld4UNYl2kn3rew3r7Y4:ba8lsks) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/testutils/opttester/stats_tester.go#L325)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

What's the motivation for this measure of error? I thought the standard error formula was `(actual - estimated)/estimated`?

Did you look into the [q-error](http://www.vldb.org/pvldb/2/vldb09-657.pdf) at all (I haven't yet put in the time to grok it, but it seems [somehow] designed specifically for this)? 
</blockquote></details>

Nice! I changed to using q-error. 

I did it this way before so that the error was always between 0 and 1 and we never got NaN as the error (which would happen with the formula for relative error `(actual - estimated)/actual`)

Also, I just fell into a deep rabbit hole learning about q-error and histograms based on minimizing q-error. [SAP HANA](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.645.6678&rep=rep1&type=pdf) uses something like this. Maybe something we can consider for the future.

**Review by RaduBerinde — COMMENTED** [review]
> > Suppose we had a saveTableNode plan node with one input which is a pass-through node, but it also sets up a createTableNode...

> Good idea! I'm still a bit fuzzy on the details but I think this would work. This is going to take some time, though...

If you agree it's a worthwhile direction to explore, I can help by trying to code up the `saveTableNode` code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-Ld5tL_dDLgyzjYhagip:b-uila99)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

**Comment by rytaft** [comment]
Thanks! Let's do some white boarding today to try to flesh out some of the details

**Comment by rytaft** [comment]
I added on to Radu's commit for the `saveTableNode` as the first commit, and updated the second commit to use that node. RFAL.

**Review by justinj — COMMENTED** [review]
:lgtm:

One thought I have is that this only checks the quality of the stats we have for *the chosen plan*, and not any other considered (sub) plans. For example, if we tended to overestimate the cost of plans then we could see good stats here, but better plans which were costed too high won't show up. I don't really have a great solution to this off the top of my head, though. Maybe we want to include a sampling of possible subplans as other test cases (along with a way to generate them?).

The `import-schema` thought was just to have some external definition of the TPCC schema that could be imported into multiple different tests, it's not a big deal.

> Reviewed 21 of 27 files at r2, 4 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-LeMp_ucCbUNZ82S9_rc:b-ktoscp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-LeO40r36YH3ig9wuncR:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

**Review by RaduBerinde — COMMENTED** [review]
This is cool!

I agree with Justin that we should think of how we could combine this with looking at more than the one plan, maybe a way to automatically report just those plans where we see large estimation errors. Hmm.. the statistics are really per memo group, so maybe we just need to look at memo groups that aren't part of the best plan. Maybe we want to run a query and save a table for each memo group, and look at each one separately? Anyway, lots of potential directions here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-LeO4Sb41HoBQ7PTYcGs:b-15ow4a)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

**Review by rytaft — COMMENTED** [review]
TFTRs! 

These are good ideas about also looking at the plans/memo groups that weren't chosen. I'll work on that idea for the next PR.

I like the `import-schema` idea to reduce the need to re-copy the TPC-C schema and stats. That can also be saved for another PR.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-:-LegxLnZ5LbMuNYNJmxC:b-4q7joc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpcc, line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36940#-Lcprc6I48PyI7wG0gUr:-LegtW-ACJjJqPrxF6B4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf3e799299bc2805d18d8630dee266be60230c50/pkg/sql/opt/memo/testdata/stats_quality/tpcc#L1078)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Yea, I could definitely filter it out. I'll hold of on doing this until I try to implement Radu's suggestion, since that will probably change some things.
</blockquote></details>

Done.

**Pull request merged**
