### PR TITLE
sql: introduce Transaction ID Cache

### PR DESCRIPTION
**Pull request by Azhng**
Previously, it was impossible to correlate an individual execution
of a transaction (identified via transaction ID) to this historical
execution statistics (identified via transaction fingerprint ID).

This commit introduces Transaction ID Cache (TxnIDCache), a FIFO
unordered buffer that stores the mapping from transaction ID to
transaction fingerprint ID. This buffer records the mapping at the
end of the transaction execution. The oldest entry in the buffer
will be evicted through FIFO policy. The default size of this
Transaction ID Cache is capped at 64 MB and it is configurable via
the sql.contention.txn_id_cache.max_size cluster setting.

Release note (sql change): Transaction ID to Transaction Fingerprint
ID mapping is now stored in the new Transaction ID Cache, a FIFO
unordered in-memory buffer. The size of the buffer is 64 MB by default
and configurable via sql.contention.txn_id_cache.max_size cluster
setting.

### CODE REVIEW

**Comment by Azhng** [comment]
Hmm, the initial implementation here looks like we have some pretty significant performance impacts for the avg latency.
We are seeing significant increase of latency across the board. 

| Branch          | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|-----------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| 38fab           | 31322.0 | 97.4%       |  140.6   |  28.3    | 62.9     |  79.7    | 1744.8   | 34359.7   |
| 38fab           | 31343.0 | 97.5%       |  122.2   |  31.5    | 71.3     |  88.1    | 167.8    | 28991.0   |
| 38fab           | 31354.6 | 97.5%       |  108.0   |  30.4    | 71.3     |  92.3    | 184.5    | 30064.8   |
| txn-id-cache    | 31357.2 | 97.5%       |  108.7   |  41.9    | 151.0    |  260.0   | 1208.0   | 14495.5   |
| txn-id-cache    | 31331.5 | 97.5%       |  143.4   |  71.3    | 218.1    |  318.8   | 1342.2   | 20401.1   |
| txn-id-cache    | 31262.0 | 97.2%       |  174.9   |  75.5    | 243.3    |  419.4   | 1744.8   | 32212.3   |

However, microbenchmark shows only very small delta of performance penalty

```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24       239µs ± 5%     237µs ± 3%   ~     (p=0.436 n=10+10)
FlowSetup/vectorize=true/distribute=false-24      228µs ± 4%     231µs ± 3%   ~     (p=0.247 n=10+10)
FlowSetup/vectorize=false/distribute=true-24      233µs ± 4%     232µs ± 5%   ~     (p=0.684 n=10+10)
FlowSetup/vectorize=false/distribute=false-24     222µs ± 3%     225µs ± 6%   ~     (p=0.165 n=10+10)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      30.4kB ± 1%    30.5kB ± 2%   ~     (p=0.814 n=9+9)
FlowSetup/vectorize=true/distribute=false-24     28.6kB ± 0%    28.6kB ± 0%   ~     (p=0.645 n=8+8)
FlowSetup/vectorize=false/distribute=true-24     37.5kB ± 5%    37.0kB ± 0%   ~     (p=0.661 n=10+9)
FlowSetup/vectorize=false/distribute=false-24    35.2kB ± 0%    35.1kB ± 0%   ~     (p=0.460 n=9+10)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         254 ± 0%       256 ± 4%   ~     (p=0.240 n=8+10)
FlowSetup/vectorize=true/distribute=false-24        240 ± 0%       240 ± 0%   ~     (p=0.471 n=9+9)
FlowSetup/vectorize=false/distribute=true-24        250 ± 0%       250 ± 0%   ~     (p=0.747 n=8+9)
FlowSetup/vectorize=false/distribute=false-24       236 ± 0%       236 ± 0%   ~     (all equal)
```

I'm not quite sure how to interpret this results, cc @yuzefovich  thoughts here?

**Comment by Azhng** [comment]
Progress Summary Dec 3rd.
---

I started out working with the simplest solution:
* single `syncutil.RWMutex` with `cache.UnorderedCache` which is backed by a Golang hashmap.
* Synchronous stats recording embedded in `recordTransaction`, which is called by the top-level `txnStateTransitionsApplyWrapper`. 

This approach caused latency spikes in 4node (n2) TPCC-2500 benchmark across the board. I suspected 2 possible culprit here:
1. we are experiencing mutex contentions
2. Golang's hashmap is too slow. 

I tested out each hypothesis with different prototype:
* I swapped out Golang's hashmap with a simple hand-rolled [circular buffer](https://github.com/Azhng/cockroach/blob/txn-id-cache-circular-buffer/pkg/sql/contention/transaction_id_cache.go#L34). This circular buffer is pre-allocated and never grow in size. Since there's no need for hashing or `interface{}` casting, this should be in theory a lot faster than hashmap. However, same benchmark showed similarly bad results. This tells me that Golang's hashmap is not the problem here
* I swapped out a single mutex and implemented a simple [hash-sharded](https://github.com/Azhng/cockroach/blob/txn-id-cache-hash-shard-lock/pkg/sql/contention/transaction_id_cache.go#L35) mutex. Where I hash the `txnID` before selecting the hash bucket and perform the write operation. This yields slightly improved latency, however, I think we can still do better.


After chatted with @jordanlewis, I started exploring implementing [async stats collection](https://github.com/Azhng/cockroach/blob/txn-id-cache-async/pkg/sql/contention/transaction_id_cache.go#L39):
* a single buffered channel with a goroutine as a consumer of that channel. This goroutine is spinned up upon SQL Server startup and insert `txnID` to `txnFingerprintID` mappings into the `cache.UnorderedCache` as they come in through the channel.
* Each connExecutor served as the producer of the channel and send in the `txnID` to `txnFingerprintID` mapping into the channel at the end of each transaction. 
* The channel is buffered and if the channel is full, the mapping is discarded. The channel size is hard coded to 1024.

Interestingly, this approach yields actually worse result than the simple single-mutex approach, with higher avg latency. Puzzled, I decided to implement a variant of this async stats collection, where the consumer goroutine's behavior is modified:
* when the consumer goroutine receives a mapping from the channel, it appends it to a [writer buffer](https://github.com/Azhng/cockroach/blob/txn-id-cache-async-batch/pkg/sql/contention/transaction_id_cache.go#L88). This writer buffer is small and here to batch all the mappings into a bigger batch. Once the writer's buffer is full, it then holds the write lock to the unordered cache and insert the entire writer buffer into the unordered cache. 

Effectively, this approach amortized the overhead of locking onto the mutex lock. This approach actually produced the best result among all the prototypes that I have experimented this week. This likely indicates that, even with Golang's channel, the biggest overhead likely comes from the mutex locking overhead. 

The caveat, in one instance of the testing, this approach produced extremely high p99 latency. I'm not sure if this could be directly related to the new component I was testing, or I should disregard it as an outlier. 

Here's all the benchmark results:

Note: `d0398` is the SHA of the master branch I used as a baseline reference. 

```
| Branch              | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|---------------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| d0398               | 31398.3 | 97.7%       |  67.7    |  31.5    | 65.0     |  79.7    | 121.6    | 23622.3   |
| d0398               | 31420.3 | 97.7%       |  60.2    |  31.5    | 65.0     |  79.7    | 130.0    | 15569.3   |
| txn-id-cache        | 31357.2 | 97.5%       |  108.7   |  41.9    | 151.0    |  260.0   | 1208.0   | 14495.5   |
| txn-id-cache        | 31331.5 | 97.5%       |  143.4   |  71.3    | 218.1    |  318.8   | 1342.2   | 20401.1   |
| txn-id-cache        | 31262.0 | 97.2%       |  174.9   |  75.5    | 243.3    |  419.4   | 1744.8   | 32212.3   |
| txn-id-hash-shard   | 31367.0 | 97.6%       |  101.4   |  60.8    | 151.0    |  184.5   | 268.4    | 20401.1   |
| txn-id-hash-shard   | 31375.1 | 97.6%       |  101.0   |  56.6    | 159.4    |  192.9   | 268.4    | 20401.1   |
| txn-id-circular-buf | 31294.9 | 97.3%       |  162.5   |  75.5    | 234.9    |  385.9   | 1476.4   | 24696.1   |
| txn-id-async        | 31298.1 | 97.4%       |  153.3   |  58.7    | 218.1    |  469.8   | 2013.3   | 15032.4   |
| txn-id-async        | 31291.8 | 97.3%       |  163.6   |  75.5    | 243.3    |  402.7   | 1811.9   | 17179.9   |
| txn-id-async-batch  | 31394.0 | 97.6%       |  85.6    |  41.9    | 104.9    |  130.0   | 209.7    | 22548.6   |
| txn-id-async-batch  | 31173.4 | 97.0%       |  268.5   |  50.3    | 142.6    |  184.5   | 10737.4  | 40802.2   |
| txn-id-async-batch  | 31388.5 | 97.6%       |  76.1    |  35.7    | 88.1     |  104.9   | 159.4    | 22548.6   |
```

Next step
---
Plan for next step: seems like the async batched design has showed promising result, this could potentially be a good direction to continue my exploration. 

Couple things I need to understand:
1. Are we filling up the channel faster than the consumer goroutine can insert into unordered cache? If this is the case, at what rate are we discarding messages? This should be easy to track since I have already implemented timeserie metrics to track this.
2. How can we replicate this performance degradation in microbenchmark? Microbenchmark is a lot faster to execute therefore a lot easier to iterate. If my hypothesis on the mutex contention being the culprit of the latency spikes, then I should be easily reproduces this with [microbenchmark](https://github.com/Azhng/cockroach/blob/bench-concurrent-e2e/pkg/bench/bench_test.go#L1232), (e.g. spin up a a lot of goroutines and spam `SELECT 1` at a server), however, I wasn't able to do so. Why is this? 
3. How can we improve on the async batching approach? One idea I've had is to batch the msg before the producer even send them into the Golang's channel. This can probably be implemented using a hash-sharded buffer. (I hope I can implement this without using a lock but only using atomic counter and latches). This should improve the throughput of the Golang's channel and amortize the cost of locking onto `runtime.futex` (that is used to synchronize channel access). Will this produce better results? I don't know, but I guess we will find out.

**Comment by Azhng** [comment]
Progress Update Dec 9

Spending a lot more time tuning the microbenchmark and it seems like we are now able to have a good idea of the performance impact through pprof's mutex profile. I think this is in line with what the TPCC benchmark showed us:

Before:

Screen Shot 2021-12-09 at 15 50 26

After:

Screen Shot 2021-12-09 at 15 50 39


However, I still haven't been able to find a way to use the microbenchmark to reveal the impact on end-to-end latency:

```
$ benchstat ~/tmp/baseline/bench ~/tmp/txn-id-vanilla/bench                                                                                            [15:42:42]
name                                     old time/op    new time/op    delta
ConcurrentSelect1/concurrentConn=64-24      746µs ± 9%     756µs ± 6%    ~     (p=0.579 n=10+10)
ConcurrentSelect1/concurrentConn=128-24    1.48ms ± 7%    1.48ms ± 4%    ~     (p=0.739 n=10+10)
ConcurrentSelect1/concurrentConn=256-24    3.17ms ± 2%    3.25ms ± 4%    ~     (p=0.101 n=8+10)
ConcurrentSelect1/concurrentConn=512-24    7.70ms ± 3%    8.10ms ± 4%  +5.30%  (p=0.000 n=9+9)

name                                     old us/op      new us/op      delta
ConcurrentSelect1/concurrentConn=64-24        710 ± 8%       722 ± 6%    ~     (p=0.255 n=10+10)
ConcurrentSelect1/concurrentConn=128-24     1.35k ± 7%     1.35k ± 4%    ~     (p=0.926 n=10+10)
ConcurrentSelect1/concurrentConn=256-24     2.72k ± 2%     2.74k ± 8%    ~     (p=0.740 n=7+10)
ConcurrentSelect1/concurrentConn=512-24     5.62k ± 8%     5.91k ±20%    ~     (p=0.050 n=9+9)

name                                     old alloc/op   new alloc/op   delta
ConcurrentSelect1/concurrentConn=64-24      898kB ± 0%     903kB ± 0%  +0.62%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=128-24    1.82MB ± 1%    1.83MB ± 0%  +0.79%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=256-24    3.75MB ± 0%    3.78MB ± 0%  +0.79%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=512-24    8.21MB ± 0%    8.31MB ± 1%  +1.16%  (p=0.000 n=9+10)

name                                     old allocs/op  new allocs/op  delta
ConcurrentSelect1/concurrentConn=64-24      9.56k ± 0%     9.75k ± 0%  +1.99%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=128-24     19.3k ± 0%     19.7k ± 0%  +2.11%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=256-24     39.6k ± 0%     40.4k ± 0%  +2.06%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=512-24     84.9k ± 0%     86.8k ± 0%  +2.25%  (p=0.000 n=9+10)
```

**Comment by Azhng** [comment]
Dec 14th update,

Turns out the easiest way to capture the performance degradation is to directly measure the overhead of `recordTransaction` using a histogram metrics, and using Golang's benchmarking framework to report that metrics.


Here's the benchmark result, the new measurement here is `overhead(ns/op)` and we can easily observe the skyrocketing overhead cost of transaction stats collection. 

```
$ benchstat ~/tmp/baseline/bench ~/tmp/txn-id-vanilla/bench                                                                                            [12:47:33]
name                                    old time/op          new time/op          delta
ConcurrentSelect1/concurrentConn=24-24           453µs ±11%           471µs ±11%       ~     (p=0.165 n=10+10)
ConcurrentSelect1/concurrentConn=48-24          1.15ms ±18%          1.27ms ±17%       ~     (p=0.052 n=10+10)
ConcurrentSelect1/concurrentConn=64-24          2.00ms ±12%          2.27ms ±31%    +13.57%  (p=0.029 n=10+10)

name                                    old ms/op            new ms/op            delta
ConcurrentSelect1/concurrentConn=24-24            0.28 ± 8%            0.30 ± 6%       ~     (p=0.165 n=10+10)
ConcurrentSelect1/concurrentConn=48-24            0.53 ± 4%            0.56 ± 3%     +5.99%  (p=0.000 n=10+9)
ConcurrentSelect1/concurrentConn=64-24            0.68 ± 4%            0.73 ± 4%     +8.00%  (p=0.000 n=9+10)

name                                    old overhead(ns/op)  new overhead(ns/op)  delta
ConcurrentSelect1/concurrentConn=24-24           2.68k ± 4%          13.60k ±11%   +407.90%  (p=0.000 n=8+8)
ConcurrentSelect1/concurrentConn=48-24           4.13k ±12%          39.19k ±18%   +848.56%  (p=0.000 n=10+8)
ConcurrentSelect1/concurrentConn=64-24           4.69k ± 8%          66.90k ±26%  +1326.04%  (p=0.000 n=8+10)

name                                    old alloc/op         new alloc/op         delta
ConcurrentSelect1/concurrentConn=24-24           369kB ± 1%           374kB ± 1%     +1.40%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=48-24           759kB ± 2%           774kB ± 2%     +2.00%  (p=0.002 n=10+10)
ConcurrentSelect1/concurrentConn=64-24          1.04MB ± 1%          1.08MB ± 4%     +3.45%  (p=0.000 n=10+10)

name                                    old allocs/op        new allocs/op        delta
ConcurrentSelect1/concurrentConn=24-24           3.67k ± 0%           3.75k ± 0%     +2.12%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=48-24           7.48k ± 1%           7.65k ± 1%     +2.28%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=64-24           10.2k ± 1%           10.5k ± 1%     +2.85%  (p=0.000 n=10+9)
```

This is a good starting point for us to use microbenchmark to approximate the result of the TPCC result.

**Comment by ajwerner** [comment]
drive-by: the data structure in `util/cache` isn't particularly good. My sense is that we could benefit from adopting https://github.com/dgraph-io/ristretto as the backing cache instead of the cache we have which requires a mutex.

**Comment by Azhng** [comment]
Thanks for the pointer @ajwerner! `ristretto` is very interesting, but after spending sometime reading through its code, it seems like this might not be very suitable for us due to very different access patterns. Ristretto optimizes for hit-ratio of the cache and has admission control mechanism (a bloom filter) where a Key-Value pair is only added into the cache if it has only been seen more than once. 

This is not desirable for us since TxnID is usually all unique and we should never repeated add two identical TxnID into the TxnID Cache. (unless UUID collision ?)

Though Ristretto's async + hash sharding hashmap approach looks very interesting and seems pretty straightforward to implement. I'll go ahead and implement that and see how it performs. 

---- 

After digging into Ristretto code, it seems like Ristretto uses buffered channel for its write path. I'm a bit concern with this approach since this will likely be bottleneck on the `runtime.futex` that is used to synchronized channel access, as we have seen before with index usage statistics and the `txn-id-cache-async` prototype. 

Perhaps some sort of buffering should be implemented before we send the data down into the channel, using a lightweight lock free ring buffer so we can amortize the cost of using the channel.

**Comment by ajwerner** [comment]
@Azhng I don't really buy your analysis. Sure, some of the features of ristretto won't help. What will help is that accesses and writes can be performed in parallel with very little synchronization relative to the caching structures we currently have which require mutual exclusion.

**Comment by ajwerner** [comment]
@Azhng let me try once more to encourage you to pop out the underlying implementation of the unordered cache with ristretto and make it safe for concurrent usage. If we're still not happy with the performance, then we can talk about how to improve it. I think that will be less work and more general gain and, honestly, if it's not fast enough, I'll volunteer to help you make something that is.

**Comment by ajwerner** [comment]
Spoke offline. The problem is that we need a more write optimized data-structure and that we don't care at all about read performance.

**Comment by Azhng** [comment]
Dec 16th progress update: 

----

I [implemented](https://github.com/cockroachdb/cockroach/compare/master...Azhng:txn-id-cache-async-batch-hash?expand=1) prototype with the batching mechanism similar to replica proposal buffer in the kvserver. This significantly lowered the txnID/txnFingerprintID pair collection by about 10% ~ 30%  compared to the existing 

```bash
$ benchstat ~/tmp/txn-id-async-batch-hash/bench ~/tmp/txn-id-async-batch-hash-buffer/bench                                                             
name                                    old overhead(ns/op)  new overhead(ns/op)  delta
ConcurrentSelect1/concurrentConn=24-24           4.56k ±42%           3.14k ± 7%  -31.19%  (p=0.000 n=9+9)
ConcurrentSelect1/concurrentConn=48-24           5.48k ±17%           4.83k ±23%  -11.82%  (p=0.025 n=10+10)
ConcurrentSelect1/concurrentConn=64-24           6.76k ±25%           5.50k ±16%  -18.58%  (p=0.000 n=10+10)
```

Though compared to the baseline this is still some overhead observed in the microbenchmark

```bash
$ benchstat ~/tmp/baseline/bench ~/tmp/txn-id-async-batch-hash-buffer/bench
name                                    old overhead(ns/op)  new overhead(ns/op)  delta
ConcurrentSelect1/concurrentConn=24-24           2.68k ± 4%           3.14k ± 7%  +17.21%  (p=0.000 n=8+9)
ConcurrentSelect1/concurrentConn=48-24           4.13k ±12%           4.83k ±23%  +16.95%  (p=0.001 n=10+10)
ConcurrentSelect1/concurrentConn=64-24           4.69k ± 8%           5.50k ±16%  +17.24%  (p=0.001 n=8+10)
```

In terms of TPCC performance, there's still some gap we need to close for the latency:  (note `txn-id-async-batch-hash-buffer` is the newest entry)

| Branch                              | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|-------------------------------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| d0398                               | 31398.3 | 97.7%       |  67.7    |  31.5    | 65.0     |  79.7    | 121.6    | 23622.3   |
| d0398                               | 31420.3 | 97.7%       |  60.2    |  31.5    | 65.0     |  79.7    | 130.0    | 15569.3   |
| txn-id-async                        | 31298.1 | 97.4%       |  153.3   |  58.7    | 218.1    |  469.8   | 2013.3   | 15032.4   |
| txn-id-async                        | 31291.8 | 97.3%       |  163.6   |  75.5    | 243.3    |  402.7   | 1811.9   | 17179.9   |
| txn-id-async-batch                  | 31394.0 | 97.6%       |  85.6    |  41.9    | 104.9    |  130.0   | 209.7    | 22548.6   |
| txn-id-async-batch                  | 31388.5 | 97.6%       |  76.1    |  35.7    | 88.1     |  104.9   | 159.4    | 22548.6   |
| txn-id-async-batch-hash             | 31393.7 | 97.6%       |  79.0    |  32.5    | 83.9     |  100.7   | 151.0    | 25769.8   |
| txn-id-async-batch-hash-buffer-256  | 31388.1 | 97.6%       |  86.8    |  35.7    | 83.9     |  104.9   | 151.0    | 26843.5   |
| txn-id-async-batch-hash-buffer-1024 | 31395.5 | 97.7%       |  79.8    |  37.7    | 92.3     |  109.1   | 159.4    | 24696.1   |



Not sure exactly why there's still a 15 ~ 20ms bump in latency number. I'll keep investigating tomorrow.

**Comment by Azhng** [comment]
Hmm though at this point I think I'll time-box myself for the investigation so I can keep working on the rest of the RFC. I'm starting to running out of ideas of where else I can optimize. I would rather take the perf hit now and come back to this later, than sink infinite amount of time to micro-optimize the last few microseconds of latency.

**Comment by Azhng** [comment]
Dec 17th update:

Finally we have a [prototype](https://github.com/cockroachdb/cockroach/compare/master...Azhng:txn-id-cache-async-batch-hash-shard-block?expand=1) that is fast enough and creates negligible performance impact. 

---

Stats Collection overhead

```
name                                    old overhead(ns/op)  new overhead(ns/op)  delta
ConcurrentSelect1/concurrentConn=24-24           2.68k ± 4%           2.68k ±10%     ~     (p=0.615 n=8+10)
ConcurrentSelect1/concurrentConn=48-24           4.13k ±12%           3.87k ±14%     ~     (p=0.128 n=10+8)
ConcurrentSelect1/concurrentConn=64-24           4.69k ± 8%           4.68k ±25%     ~     (p=0.315 n=8+10)
```

| Branch                               | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|--------------------------------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| master                                 | 31404.6 | 97.7%       |  65.4    |  30.4    | 62.9     |  79.7    | 125.8    | 19327.4   |
| txn-id-async-batch-hash-buffer-shard | 31412.9 | 97.7%       |  57.9     | 27.3  |    62.9     |  83.9    | 130.0    | 17179.9   |


It continued from the previous prototype from Dec 16th. However, instead of writing TxnID-TxnfingerprintID pair to a single global "lock-free" buffer, and flush that buffer into the channel, the new prototype creates a new write buffer for each connExecutor. 

However, there is an issue with this design: if the write buffer in the connExecutor is not full, we won't be able to flush the TxnID-TxnFingerprintID pair into the channel.

I think there are two solution to this problem:
1. Passive solution: We add a `lastFlushed` timestamp in the write buffer, and when we are inserting an new TxnID-TxnFingerprintID pair, we check the `lastFlushed` timestamp, if that timestamp is beyond certain threshold, then we preemptively perform a flush without waiting for the entire buffer to become full.
2. Active solution: We run a goroutine for each write buffer, (that is, we run a new goroutine for each connExecutor). This goroutine wakes up perodically to flush the buffer. (Say, every 10 seconds). 

I like the simplicity of the first solution, however, I'm a bit worried about the fact that if we have a long running (or even a hanging) transaction, it would block the flush of buffer. But perhaps I can just insert some sort of `ensureBufferFlushed()` call somewhere in the connExecutor to make it flush more often 🤔

**Comment by Azhng** [comment]
Going to close this draft PR since I've polluted it quite a bit with my progress update. Opened #74115

**Pull request closed without merging**
