### PR TITLE
 exec: refactor vectorized merge joiner to a state machine

### PR DESCRIPTION
**Pull request by georgeutsin**
Refactored the merge joiner to use a state machine to:
a) make it clearer what's going on
b) set the operator up for another refactor which removes the
output buffer.

Two different states, mjProberState and mjBuilderState were
added to differentiate between the two distinct phases.

The plan is to add to the mjBuilderState to be able to pause
the expansion of cross product as soon as the output gets
to the batch size, and then resume in the expansion in the
next iteration.

Benchamrk results after the refactor:
```
name                                      old time/op    new time/op    delta
MergeJoiner/rows=1024-8                     69.4µs ± 1%    69.6µs ± 0%        ~     (p=0.156 n=10+9)
MergeJoiner/rows=4096-8                      265µs ± 1%     266µs ± 1%        ~     (p=0.123 n=10+10)
MergeJoiner/rows=16384-8                    1.03ms ± 0%    1.04ms ± 1%      +0.70%  (p=0.001 n=10+10)
MergeJoiner/rows=1048576-8                  64.9ms ± 2%    64.9ms ± 1%        ~     (p=0.393 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8       69.3µs ± 1%    70.1µs ± 1%      +1.07%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=4096-8        266µs ± 2%     265µs ± 0%        ~     (p=0.684 n=10+10)
MergeJoiner/oneSideRepeat-rows=16384-8      1.06ms ± 3%    1.05ms ± 4%        ~     (p=0.190 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-8    67.5ms ± 2%    67.5ms ± 4%        ~     (p=0.971 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-8     70.4µs ± 1%    72.2µs ± 5%      +2.60%  (p=0.001 n=9+10)
MergeJoiner/bothSidesRepeat-rows=4096-8     1.37ms ± 1%    1.36ms ± 1%      -1.04%  (p=0.000 n=9+10)
MergeJoiner/bothSidesRepeat-rows=16384-8    18.8ms ± 1%    18.7ms ± 0%      -1.05%  (p=0.000 n=10+8)
MergeJoiner/bothSidesRepeat-rows=32768-8    82.6ms ± 1%    81.6ms ± 0%      -1.26%  (p=0.000 n=10+10)

name                                      old speed      new speed      delta
MergeJoiner/rows=1024-8                    944MB/s ± 1%   941MB/s ± 0%        ~     (p=0.156 n=10+9)
MergeJoiner/rows=4096-8                    990MB/s ± 1%   986MB/s ± 1%        ~     (p=0.123 n=10+10)
MergeJoiner/rows=16384-8                  1.02GB/s ± 0%  1.01GB/s ± 1%      -0.69%  (p=0.001 n=10+10)
MergeJoiner/rows=1048576-8                1.03GB/s ± 2%  1.03GB/s ± 1%        ~     (p=0.393 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8      945MB/s ± 1%   935MB/s ± 1%      -1.06%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=4096-8      984MB/s ± 2%   988MB/s ± 0%        ~     (p=0.684 n=10+10)
MergeJoiner/oneSideRepeat-rows=16384-8     994MB/s ± 3%   999MB/s ± 4%        ~     (p=0.190 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-8   995MB/s ± 2%   995MB/s ± 4%        ~     (p=0.971 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-8    931MB/s ± 1%   908MB/s ± 5%      -2.48%  (p=0.001 n=9+10)
MergeJoiner/bothSidesRepeat-rows=4096-8    191MB/s ± 1%   193MB/s ± 1%      +1.05%  (p=0.000 n=9+10)
MergeJoiner/bothSidesRepeat-rows=16384-8  55.6MB/s ± 1%  56.2MB/s ± 0%      +1.06%  (p=0.000 n=10+8)
MergeJoiner/bothSidesRepeat-rows=32768-8  25.4MB/s ± 1%  25.7MB/s ± 0%      +1.27%  (p=0.000 n=10+10)

name                                      old alloc/op   new alloc/op   delta
MergeJoiner/rows=1024-8                     4.24kB ± 0%    4.37kB ± 0%      +3.02%  (p=0.000 n=10+10)
MergeJoiner/rows=4096-8                     4.29kB ± 0%    4.61kB ± 0%      +7.47%  (p=0.000 n=10+10)
MergeJoiner/rows=16384-8                    4.38kB ± 0%    5.47kB ± 0%     +24.85%  (p=0.000 n=10+10)
MergeJoiner/rows=1048576-8                  19.7kB ± 0%    85.3kB ± 0%    +333.45%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8       4.24kB ± 0%    4.37kB ± 0%      +3.02%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=4096-8       4.29kB ± 0%    4.61kB ± 0%      +7.47%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=16384-8      4.38kB ± 0%    5.47kB ± 0%     +24.85%  (p=0.000 n=10+9)
MergeJoiner/oneSideRepeat-rows=1048576-8    19.7kB ± 0%    85.3kB ± 0%    +333.45%  (p=0.000 n=10+9)
MergeJoiner/bothSidesRepeat-rows=1024-8     4.24kB ± 0%    4.37kB ± 0%      +3.02%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=4096-8      433kB ± 0%     434kB ± 0%      +0.04%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16384-8    2.90MB ± 0%    2.90MB ± 0%      +0.03%  (p=0.000 n=10+8)
MergeJoiner/bothSidesRepeat-rows=32768-8    7.62MB ± 0%    7.62MB ± 0%      +0.03%  (p=0.000 n=10+10)

name                                      old allocs/op  new allocs/op  delta
MergeJoiner/rows=1024-8                       4.00 ± 0%      8.00 ± 0%    +100.00%  (p=0.000 n=10+10)
MergeJoiner/rows=4096-8                       4.00 ± 0%     14.00 ± 0%    +250.00%  (p=0.000 n=10+10)
MergeJoiner/rows=16384-8                      4.00 ± 0%     38.00 ± 0%    +850.00%  (p=0.000 n=10+10)
MergeJoiner/rows=1048576-8                    9.00 ± 0%   2059.00 ± 0%  +22777.78%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8         4.00 ± 0%      8.00 ± 0%    +100.00%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=4096-8         4.00 ± 0%     14.00 ± 0%    +250.00%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=16384-8        4.00 ± 0%     38.00 ± 0%    +850.00%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-8      9.00 ± 0%   2059.00 ± 0%  +22777.78%  (p=0.000 n=10+9)
MergeJoiner/bothSidesRepeat-rows=1024-8       4.00 ± 0%      8.00 ± 0%    +100.00%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=4096-8      5.20k ± 0%     5.21k ± 0%      +0.12%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16384-8     30.9k ± 0%     30.9k ± 0%      +0.10%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=32768-8     64.3k ± 0%     64.3k ± 0%      +0.10%  (p=0.000 n=10+10)
```

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
This is great!

Do you know what caused the spike in allocations in the benchmarks?

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-:-LaRx-s4BZNvGJRdXr2w:bmiubk9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/mergejoiner.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRs0ge-W-ybc4DSUus:-LaRs0ge-W-ybc4DSUut:b-rxhsnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L34)):*
> ```Go
> // mjBuilderState contains all the state required to execute in the build phase.
> type mjBuilderState struct {
> 	// Fields hold the input sources batches from which to build the cross products.
> ```

[nit]: "to hold".
___
*[pkg/sql/exec/mergejoiner.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRs78b4Ni5UNoIxxTR:-LaRs78b4Ni5UNoIxxTS:b-6oz86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L47)):*
> ```Go
> }
> 
> // mjProberState contains all the state required to execute in the probing phases.
> ```

[nit]: I think "phase".
___
*[pkg/sql/exec/mergejoiner.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtAdC9Uyy2CT9pz2P:-LaRtAdC9Uyy2CT9pz2Q:b-urcu7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L67)):*
> ```Go
> 	// globallyFinished is a flag to indicate whether the merge joiner has reached the end
> 	// of input, and thus should wrap up execution.
> 	globallyFinished bool
> ```

[nit]: `inputDone` might be a better name.
___
*[pkg/sql/exec/mergejoiner.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRt2KW8RhOuqSFLN04:-LaRt2KW8RhOuqSFLN05:bmc5uvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L156)):*
> ```Go
> 	groups circularGroupsBuffer
> 
> 	// Merge joiner state
> ```

[nit]: period.
___
*[pkg/sql/exec/mergejoiner.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRvYHj5ZQqitYuE6dw:-LaRvYHj5ZQqitYuE6dx:b90wdxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L184)):*
> ```Go
> }
> 
> func (c *mergeJoinOp) initWithBatchSize(outBatchSize uint16) {
> ```

[super nit]: choice of `c` as a receiver is a little weird, maybe `m` or `o` would be better?
___
*[pkg/sql/exec/mergejoiner.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtPPFAzO5a8ArrNq3:-LaRtPPFAzO5a8ArrNq4:b-wggglc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L221)):*
> ```Go
> // nextBatch takes a mergeJoinInput and returns the next batch. Also returns other handy state
> // such as the starting index (always 0) and selection vector.
> func nextBatch(input *mergeJoinInput) (int, coldata.Batch) {
> ```

It seems like we can remove this function.
___
*[pkg/sql/exec/mergejoiner.go, line 237 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtaHjC92v_LSyu2fj:-LaRtaHk--CtCJJWSUeg:bmc5uvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L237)):*
> ```Go
> }
> 
> // TODO (georgeutsin): remove saved output buffer and this associated function
> ```

[nit]: period.
___
*[pkg/sql/exec/mergejoiner.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtnQx0h-qGAkLcu5I:-LaRtnQx0h-qGAkLcu5J:b-luvcsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L312)):*
> ```Go
> // completeGroup extends the group in state given the source input.
> // To do this, we first check that the next batch is still the same group by checking all equality
> // columns except for the last minor equality column. Then we complete the group by Next'ing input
> ```

[nit]: "minor"?
___
*[pkg/sql/exec/mergejoiner.go, line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRvBjHEVdHJhhVtadQ:-LaRvBjHEVdHJhhVtadR:btn39mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L487)):*
> ```Go
> }
> 
> // build creates the cross product, and writes it to the out member.
> ```

[nit]: possibly "output member".
___
*[pkg/sql/exec/mergejoiner.go, line 551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRwSbf6i7qg7fmSn9G:-LaRwSbf6i7qg7fmSn9H:bjnmp4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L551)):*
> ```Go
> 			if c.sourceFinished() {
> 				c.state = mjSourceFinished
> 				break
> ```

Should we `continue` the loop here (and below) instead of `break`ing?

**Comment by yuzefovich** [comment]
Reviewable still doesn't want to post some of my comments. The empty ones are two missing periods and a word "minor" talking about "last minor equality column" (I think it can be removed).

**Review by georgeutsin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRs0ge-W-ybc4DSUus:-LaVgk4UE6U83vJpEq8I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L34)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: "to hold".
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRs78b4Ni5UNoIxxTR:-LaVgkbWEAaof9pLUqqd:bd68vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L47)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I think "phase".
</blockquote></details>

Theres the main probing phase, then there's a secondary probing phase where we continue the group that ended with the batch.
___
*[pkg/sql/exec/mergejoiner.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtAdC9Uyy2CT9pz2P:-LaVgrhK1TtvsREWzB1q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L67)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `inputDone` might be a better name.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRt2KW8RhOuqSFLN04:-LaVh-N98tIVo49wOZJy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L156)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: period.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRvYHj5ZQqitYuE6dw:-LaVh-yRB08JTBTYvLma:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L184)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: choice of `c` as a receiver is a little weird, maybe `m` or `o` would be better?
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtPPFAzO5a8ArrNq3:-LaVh0Vn7V-vOCXBtPjN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L221)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It seems like we can remove this function.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 237 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtaHjC92v_LSyu2fj:-LaVh1534fJwVJf2naaE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L237)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: period.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRtnQx0h-qGAkLcu5I:-LaVh3nj1EbMrCAQe_ol:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L312)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: "minor"?
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRvBjHEVdHJhhVtadQ:-LaVh4oS7ZcVjNSQlbTk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L487)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: possibly "output member".
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRwSbf6i7qg7fmSn9G:-LaVh5gOAYg_h6rbHDv0:bkf2rav) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L551)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Should we `continue` the loop here (and below) instead of `break`ing?
</blockquote></details>

I mean both are equivalent, but since we're in an infinite for loop. I think its better if we keep it as break since then it will be consistent if any states appear after their next states

**Review by georgeutsin — COMMENTED** [review]
@yuzefovich I'm not really sure what caused the spike in allocations, since its hard to really pin point the change when so many other things changed in this PR. The speed is staying the same and the overall new allocations are negligible compared to the output buffer allocations though.

Hopefully I'll be able to get more insight into this after the next PR, which removes the saved output buffer. After that point, the allocations should be stable enough to reliably spot regressions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-:-LaVl9Fb7FxRdMWqRd5e:b-2d6a14)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-:-LaW-sLLCbLpLUt_wsrk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRwSbf6i7qg7fmSn9G:-LaW-RmM3sZnau2Ixqyz:bz715iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L551)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

I mean both are equivalent, but since we're in an infinite for loop. I think its better if we keep it as break since then it will be consistent if any states appear after their next states
</blockquote></details>

I'm probably missing something, but where is the infinite loop you're referring to? I see one within this `Next` function,  and if we `break` out of it, we'll reach the end of the function, but if we `continue`, then the loop is truly infinite.

**Review by asubiotto — DISMISSED** [review]
Thanks for doing this, this is definitely clearer to me. I think you can squash that last `lint and review revisions` commit.

I haven't had the time to look much past the general setup but will do a deeper dive later on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-:-LaW1cZT8xQZ7aHxgkT6:bdh8yi0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaW1qHN4GMGD4hDg_ZF:-LaW1qHN4GMGD4hDg_ZG:b-zi8mv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbd4bcf391788ee281514b9c574760958cb5c06/pkg/sql/exec/mergejoiner.go#L78)):*
> ```Go
> 	// mjSetup is the entry state of the merge joiner where all the batches and indices
> 	// are properly set, regardless if Next was called the first time or the 1000th time.
> 	// This state also routes into the correct state based on the prober state after setup.
> ```

I don't think there should be "routing to state". Why not have each state return a next state to go to? This makes the code cleaner by avoiding extra conditionals
___
*[pkg/sql/exec/mergejoiner.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRt2KW8RhOuqSFLN04:-LaW33gG3TA3D1dQjWCo:b-v06ev0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L156)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: don't think this comment is necessary

**Review by georgeutsin — COMMENTED** [review]
I'll squash everything at the end, I just want to keep it easy to look at each commit diff in github in the mean time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-:-LaWEuefBlTMU5ieTSI0:bgg2gyo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaW1qHN4GMGD4hDg_ZF:-LaWCe9m4CZIMqNxPD2g:bmwch4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbd4bcf391788ee281514b9c574760958cb5c06/pkg/sql/exec/mergejoiner.go#L78)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think there should be "routing to state". Why not have each state return a next state to go to? This makes the code cleaner by avoiding extra conditionals
</blockquote></details>

I figured it's more intuitive to route to the right state from a single point of entry, since in the next PR, the multiple calls to the build phase add cycles to the original DAG (but we can contain the cycle to just the build phase if we route in the entry point)

Further, we need to init the prober state before each prober phase anyway, which is why I thought it would be nice to have a centralized entry point.

I'm open to discussion on this though
___
*[pkg/sql/exec/mergejoiner.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRt2KW8RhOuqSFLN04:-LaWBoxV9Jm_For6I4TQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L156)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: don't think this comment is necessary
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRwSbf6i7qg7fmSn9G:-LaWBwGJ2b6s9T-UozhO:b-kat5np) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L551)):*
> within this Next function,  and if we break out of it, we'll reach the end of the function, but if we continue, then the loop is truly infinite.
The break context refers to the switch. The for loop is up one level, so to break out of that, I'd need a labelled break.

I'm not actually sure if `continue` even works in this case, haven't tried.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-LaRwSbf6i7qg7fmSn9G:-LaWKCw099lnDT6h4jPm:b-ahte4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbe04cffafd1e8138051ac34c2f31f7f8fbc5b9/pkg/sql/exec/mergejoiner.go#L551)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

> within this Next function,  and if we break out of it, we'll reach the end of the function, but if we continue, then the loop is truly infinite.
The break context refers to the switch. The for loop is up one level, so to break out of that, I'd need a labelled break.

I'm not actually sure if `continue` even works in this case, haven't tried.
</blockquote></details>

Oh, yes, I forgot about `switch` - please disregard my comments here.

**Review by jordanlewis — COMMENTED** [review]
:lgtm: the state machine is much cleaner.

I was thinking about the benchmarks. I don't understand why the both sides repeated case is so slow. Even at the maximum group size of 32 rows, that's only 1024 output rows to buffer, which doesn't overflow a batch.

So, shouldn't there be no need to grow an output buffer past 1024 rows? As I see it, the output buffer should fill up completely at every group and then have the opportunity to get flushed before we advance to a new group. No?

Can you also double check that the benchmark gets the right number of output batches? It should be easily calculatable, right? Something like `((nBatches * batch size) / group size)^2 / batch size`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-:-LapOincD6eVKbhcR0kG:b-ky0l9p)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

**Review by georgeutsin — COMMENTED** [review]
Checking the number of output batches would exercise the assumption that output batches are maximal, but in the current state they are not. This is something I can add to the next PR though, if we want to introduce that. I'm just worried it might introduce a dependency/requirement we might not necessarily want

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35999#-:-LapfFFO45TVqILTeoLK:b-sbtwu3)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @yuzefovich)

**Pull request merged**
