### PR TITLE
kvserver: provide tenant id to Processor in OnDescChangedLocked

### PR DESCRIPTION
**Pull request by sumeerbhola**
The tenant id is known at the time when the RangeDescriptor is first set.
We simply pass the tenant id with every call to OnDescChangedLocked.

Informs #129129

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
First commit is from [#129521](https://github.com/cockroachdb/cockroach/pull/129521)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129578#-:-O5-aiXa1m-LH0YVGxQs:bn20ue8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129578#-:-O5EkdHg-bORBHLkQ1cv:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
