### PR TITLE
concurrency: small refactors in preparation for reservation removal

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details. 

Informs: https://github.com/cockroachdb/cockroach/issues/103361

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten I didn't bother cleaning `tryActiveWait` up in this patch -- I just made some minimal changes to make sure things functionally remain the same. I'm assuming that's okay, given we're basically rewriting the thing over in https://github.com/cockroachdb/cockroach/pull/102973.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103373)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaJ3Ji1LQA3s52b9HZ):*
s/non-transactional/transactional/
___
*[`-- commits` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaRe3BBFYfVQPpNl1p):*
nit: "preparation"
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaHrWu5Kk73my8fnVd:-NVaHrWu5Kk73my8fnVe:bny44jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d562afd83b7293139e45d5307f9047d2a18aebc/pkg/kv/kvserver/concurrency/lock_table.go#L2327)):*
> ```Go
> // from the lock's queuedReaders list. Returns whether the reader was the
> // distinguished waiter or not.
> // TODO(arul): Check that this doesn't cause e to escape to the heap.
> ```

`e` is already a pointer, so I don't think anything that isn't already on the heap is escaping to the heap.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQJZu4XP_W_Ks3gl_:-NVaQJZu4XP_W_Ks3gla:brs2hz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
> ```Go
> 		// OR it belongs to the same transaction that waiters in the lock wait queue
> 		// are waiting on, because a transaction doesn't push itself (it just sits
> 		// tight).
> ```

I know you don't want to use the term "reservation" anymore, but it would be helpful to mention that this case implies that the `waitingTxn` is in the queue and not holding the lock, otherwise this distinguished waiter would have been released by `releaseWritersFromTxn`.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQmx29r442vObXF8G:-NVaQmx29r442vObXF8H:byibuo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1342)):*
> ```Go
> }
> 
> // waitingTxn returns the transaction that requests in the lock wait queue are
> ```

nit: "waiting" isn't very descriptive in a structure where everyone is waiting for someone else. In some sense, this is the only txn that is not waiting. Is there a better for this?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2422 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaSUVODFDEJOU9Pi69:-NVaSUVODFDEJOU9Pi6A:b-nkg56y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75c8f29eb09194144084fa44bf3f8074268bbc0/pkg/kv/kvserver/concurrency/lock_table.go#L2422)):*
> ```Go
> 		l.tryMakeNewDistinguished()
> 	}
> 	return l.queuedWriters.Len() == 0 && l.waitingReaders.Len() == 0 && l.reservation == nil
> ```

Does this cause us to GC held locks that don't have waiters?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2500 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaUSZD6r_C_qJEaWGi:-NVaUSZE6KJXZ47DETMJ:b-n7n7x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75c8f29eb09194144084fa44bf3f8074268bbc0/pkg/kv/kvserver/concurrency/lock_table.go#L2500)):*
> ```Go
> // releases the first transactional writer it finds. The function is a no-op if
> // no transactional writer is present or if the first transactional writer is
> // not active. Any non-transactional writers before the first transactional
> ```

"no-op" is misleading here. Even if this is the case, the function can still release non-transaction waiters.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2510 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaUoCgCUPeBqF9ZOuJ:-NVaUoCgCUPeBqF9ZOuK:bwvb6n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75c8f29eb09194144084fa44bf3f8074268bbc0/pkg/kv/kvserver/concurrency/lock_table.go#L2510)):*
> ```Go
> 		panic("maybeReleaseFirstTransactionalWriter called when lock is held")
> 	}
> 	if l.waitingReaders.Len() != 0 {
> ```

Where did we enforce this in the `requestDone` caller? Don't we clear the readers after calling this function?

**Review by arulajmani — COMMENTED** [review]
Like we spoke about offline, I pulled out the 4th commit into its own thing over at https://github.com/cockroachdb/cockroach/pull/103478.

RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-:-NVb9xmc86yIgp2A-cs4:bhdpdek)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaHrWu5Kk73my8fnVd:-NVb9p0jEmal7QfeGm1G:b-hmoai2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d562afd83b7293139e45d5307f9047d2a18aebc/pkg/kv/kvserver/concurrency/lock_table.go#L2327)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`e` is already a pointer, so I don't think anything that isn't already on the heap is escaping to the heap.
</blockquote></details>

Ack, thanks for confirming.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQJZu4XP_W_Ks3gl_:-NVb4htI20W-ilvqz4Jl:bjz7n1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I know you don't want to use the term "reservation" anymore, but it would be helpful to mention that this case implies that the `waitingTxn` is in the queue and not holding the lock, otherwise this distinguished waiter would have been released by `releaseWritersFromTxn`.
</blockquote></details>

Added a comment. Do you think this deserves a panic instead?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQmx29r442vObXF8G:-NVb8hjY6uEzhAqqCotI:b2almw) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1342)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: "waiting" isn't very descriptive in a structure where everyone is waiting for someone else. In some sense, this is the only txn that is not waiting. Is there a better for this?
</blockquote></details>

I think this needs a new concept. For now, I've called this `distinguishedTxn` -- I'm not sure whether the parallel with `distinguishedWaiter` is a good thing or not. Definitely open to suggestions here. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2422 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaSUVODFDEJOU9Pi69:-NVb1OFFC5g_563bTZAn:bakczsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75c8f29eb09194144084fa44bf3f8074268bbc0/pkg/kv/kvserver/concurrency/lock_table.go#L2422)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this cause us to GC held locks that don't have waiters?
</blockquote></details>

Nice catch! I've fixed this condition to use `l.isEmptyLock` instead.

I wasn't sure why our existing tests weren't failing, so I tried crafting a test that would trigger this scenario. Turns out, we're being saved by this logic: https://github.com/cockroachdb/cockroach/blob/2e6d3c53703416e8e1ae227a3e22f1156512a6c5/pkg/kv/kvserver/concurrency/lock_table.go#L2859-L2865
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2500 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaUSZD6r_C_qJEaWGi:-NVacZxXAWdpPbtsD4Gs:b-pndefy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75c8f29eb09194144084fa44bf3f8074268bbc0/pkg/kv/kvserver/concurrency/lock_table.go#L2500)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"no-op" is misleading here. Even if this is the case, the function can still release non-transaction waiters.
</blockquote></details>

You're right. Improved this comment a bit, let me know what you think.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2510 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaUoCgCUPeBqF9ZOuJ:-NVaagst78GVchAiOJkY:bimerue) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75c8f29eb09194144084fa44bf3f8074268bbc0/pkg/kv/kvserver/concurrency/lock_table.go#L2510)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Where did we enforce this in the `requestDone` caller? Don't we clear the readers after calling this function?
</blockquote></details>

Yeah, but we only call into this function from `requestDone` if the lock isn't held, which means there can't be any waiting readers (as readers only queue behind held locks).

**Review by nvb — APPROVED** [review]
:lgtm: mod the discussion about naming. It feels important to get that right, given that it's a central concept in deadlock detection.

Thanks for splitting this into a separate PR, by the way. It's encouraging to see a green CI after these improvements.

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-:-NVbT6oRCvCQzcEBrcdA:b-vk4279)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQJZu4XP_W_Ks3gl_:-NVbNpc29LhYDQLcKm4Z:bh6uh4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Added a comment. Do you think this deserves a panic instead?
</blockquote></details>

Yeah, I think an assertion is appropriate. There are a lot of subtle and intertwined invariants in this data structure. I think we'd benefit from leaning into the use of more assertions. Even before https://github.com/cockroachdb/cockroach/issues/94986 lands, I would be enthusiastic about you defining an assertion utility at the bottom of this file and then using assertions throughout as you refactor. That's especially true now that you're splitting these functions apart, leading to more functions with subtle preconditions.

Something simple like the following would make this lightweight:
```go
func assert(cond bool, msg string) {
    if !cond {
        panic(msg)
    }
}
```
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQmx29r442vObXF8G:-NVbP5ofBWofBmIPV4WT:bh7fnci) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1342)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think this needs a new concept. For now, I've called this `distinguishedTxn` -- I'm not sure whether the parallel with `distinguishedWaiter` is a good thing or not. Definitely open to suggestions here. 
</blockquote></details>

To be honest, I don't think the "distinguished" parallel is helpful. If anything, it's confusing. I asked ChatGPT to weigh in. Some of the names I got from it were "blockerTxn", "blockingTxn", and "contenderTxn". It also said "firstInLine", which I thought was kind of nice, if we can separate it enough from the "wait-queue" to also be applicable to a lock holder.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103373)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQJZu4XP_W_Ks3gl_:-NVfb_fz2QbzNmTrsRK8:bhgppss) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I think an assertion is appropriate. There are a lot of subtle and intertwined invariants in this data structure. I think we'd benefit from leaning into the use of more assertions. Even before https://github.com/cockroachdb/cockroach/issues/94986 lands, I would be enthusiastic about you defining an assertion utility at the bottom of this file and then using assertions throughout as you refactor. That's especially true now that you're splitting these functions apart, leading to more functions with subtle preconditions.

Something simple like the following would make this lightweight:
```go
func assert(cond bool, msg string) {
    if !cond {
        panic(msg)
    }
}
```
</blockquote></details>

Done. In a future commit, I'll move all the panics sprinkled around this package to make use of this function instead. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQmx29r442vObXF8G:-NVfbgyOEZFS5iV4dSeH:b-g3sgdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1342)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To be honest, I don't think the "distinguished" parallel is helpful. If anything, it's confusing. I asked ChatGPT to weigh in. Some of the names I got from it were "blockerTxn", "blockingTxn", and "contenderTxn". It also said "firstInLine", which I thought was kind of nice, if we can separate it enough from the "wait-queue" to also be applicable to a lock holder.
</blockquote></details>

Changed to `claimantTxn`, after my own conversation with Chat GPT and conferring with you on Slack. Like I mentioned there, I'm not in love with this name but it seems like the best one we have for now. How do you feel about merging this and revisiting this naming if we can come up with something better in the next few weeks?

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103373)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQmx29r442vObXF8G:-NVjhxyZ96IyijEYW0Us:b7tpcro) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1342)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Changed to `claimantTxn`, after my own conversation with Chat GPT and conferring with you on Slack. Like I mentioned there, I'm not in love with this name but it seems like the best one we have for now. How do you feel about merging this and revisiting this naming if we can come up with something better in the next few weeks? 
</blockquote></details>

I feel good about that. I also find "claimed" to be a good description of what we are trying to describe here, especially after reading the comment, so we might not need to change it.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1300 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVjfa2W3yAcFAjt2deg:-NVjfa2W3yAcFAjt2deh:b9vo2wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c256a8bd95e016cf2e626c61ad60aa02e9a40ddb/pkg/kv/kvserver/concurrency/lock_table.go#L1300)):*
> ```Go
> 		// the lock is not held.
> 		assert(
> 			l.distinguishedWaiter == nil || !l.holder.locked, errors.AssertionFailedf(
> ```

We want to make these assertions as close to free as possible, so we'll need to avoid constructing errors ahead of time and then passing them in. Let's instead push this into the assertion function.

Also, is there a benefit to panicking with an `errors.AssertionFailed`, as opposed to a `fmt.Sprintf()`?

**Review by arulajmani — COMMENTED** [review]
TFTR! 

bors r=nvanbenschoten 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-:-NVkOvu986XX0SelXVWY:b-2fjird)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVaQmx29r442vObXF8G:-NVkOdUyE6uV3lpBuXKj:b-tly4j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/279d06a8ae717393008d2b65721b3c2d7d1afcad/pkg/kv/kvserver/concurrency/lock_table.go#L1342)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I feel good about that. I also find "claimed" to be a good description of what we are trying to describe here, especially after reading the comment, so we might not need to change it.
</blockquote></details>

Yeah, after reworking some of the comments that previously spoke about reservations, I'm warming up to this as well. The comment around `IsKeyLockedByConflictingTxn` did it for me.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1300 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/103373#-NVjfa2W3yAcFAjt2deg:-NVkOEyV5YgA67MJIrue:bnjs57m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c256a8bd95e016cf2e626c61ad60aa02e9a40ddb/pkg/kv/kvserver/concurrency/lock_table.go#L1300)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We want to make these assertions as close to free as possible, so we'll need to avoid constructing errors ahead of time and then passing them in. Let's instead push this into the assertion function.

Also, is there a benefit to panicking with an `errors.AssertionFailed`, as opposed to a `fmt.Sprintf()`?
</blockquote></details>

I don't think there is -- switched this to just using a string.

**Pull request merged**
