### PR TITLE
Makefile: fix dependency on settings pages

### PR DESCRIPTION
**Pull request by ajwerner**
I broke this in #58362.

Release note: None

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Review by knz — APPROVED** [review]
This could be defined using `=` instead of `:=` which would make it impervious to the ordering.

**Comment by ajwerner** [comment]
> This could be defined using = instead of := which would make it impervious to the ordering.

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
