### PR TITLE
sqlproxyccl: export methods needed in CC repo

### PR DESCRIPTION
**Pull request by darinpp**
Previously all methods of the sql proxy were private. Now we need a
minimum set to construct the su proxy in the CC repo. This exports
several methods: BackendDial, FrontendAdmit, SendErrToClient and
ConnectionCopy.

Also replacing backupLookupAddr with net.ResolveTCPAddr to break the
dependency on the pkg/base which in turn drags over a lot of code,
including some that has to be autogenerated and not supported in the CC
repo.

Release note: None

### CODE REVIEW

**Review by jaylim-crl — APPROVED** [review]
:lgtm: I think `net.ResolveTCPAddr` should be good enough for our use case. We just need to make sure we're passing in the right routing rule, which we are already doing. Also, we need to remove the relevant dependencies in the bazel build file.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66939#-:-MdFan0F2cPCqu1i9lCL:b-wca3gc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66939#-:-MdIH1Kc5niB7Q8foBLf:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @darinpp)

**Pull request merged**
