### PR TITLE
opt: opaque relational operator

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### optgen: panic early on unknown type

I had a case where adding an unknown type to a private resulted in a
cryptic segmentation violation. Normally an unknown type would
generate an error in the validator but in this case we don't get that
far.

This change makes optgen panic immediately when it encounters an
unknown type.

Release note: None

#### opt: opaque relational operator

We introduce `OpaqueRel`: a relational operator which contains a plan
generated outside of the optimizer.

External code registers an "opaque handler" for a specific AST node
type; the opaque handler generates the plan and returns it as "opaque
metadata". The opaque metadata is later passed to the exec factory.

In this change we add opaque handlers for all remaining SHOW variants
which use a custom planNode (and thus cannot be `delegate`d).

Informs #34848.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Note that as of this PR, if I disable HP fallback for all DML queries, all logic tests pass. There are some other tests that don't, because of `SELECT FROM [ EXPLAIN <unsupported-stmt> ]`.

**Comment by RaduBerinde** [comment]
Ping..

**Review by knz — COMMENTED** [review]
LGTM with a question on hashing

> Reviewed 2 of 2 files at r1, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-:-LigqfEa9jGNChON-lGN:bpo18mz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt_exec_factory.go, line 1590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-LigpdJA-rAqURokt2mh:-LigpdJA-rAqURokt2mi:bhhw800) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt_exec_factory.go#L1590)):*
> ```Go
> 	o, ok := metadata.(*opaqueMetadata)
> 	if !ok {
> 		return nil, errors.AssertionFailedf("unexpected OpaqueMedata object")
> ```

nit: `...object: %T", metadata)`
___
*[pkg/sql/opt/memo/interner.go, line 579 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-Ligpovb5iO2ccUZQETf:-Ligpovb5iO2ccUZQETg:bgv8ujj) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/memo/interner.go#L579)):*
> ```Go
> 
> func (h *hasher) HashOpaqueMetadata(val opt.OpaqueMetadata) {
> 	h.HashUint64(uint64(reflect.ValueOf(val).Pointer()))
> ```

Is this safe? If you have a plan generated, then it gets de-allocated, then the address gets reused for a different plan, the hash will compare the same. 
(Is there an additional string comparison if the hashes compare equal?)
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1791 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-Ligq2pD8hil9wneh81-:-Ligq2pD8hil9wneh810:bh3qktf) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/memo/logical_props_builder.go#L1791)):*
> ```Go
> 	BuildSharedProps(b.mem, op, &rel.Shared)
> 	rel.CanHaveSideEffects = true
> 	rel.CanMutate = true
> ```

Can you explain "CanMutate" a bit more?

I agree that in general a feature called "opaque plans" can do pretty much anything, *however* in the particular case of this PR and the use cases you're designing this for, it seems there are no mutations?
I don't know if setting this flag disables any optimizations, but if it does maybe you'll want to split opaque-read-only vs opaque-mutation.
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 257 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-LigqU7fBRq4xE-vF9bL:-LigqU7fBRq4xE-vF9bM:bpdo6hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L257)):*
> ```Go
> 	res, ok := m.types[friendlyName]
> 	if !ok {
> 		panic(fmt.Sprintf("%s is not registered as a valid type in metadata.go", friendlyName))
> ```

`panic(errors.NewAssertionFailedf)` perhaps

**Review by rytaft — APPROVED** [review]
:lgtm: once you address @knz's comments

> Reviewed 2 of 2 files at r1, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-:-LihTeJq7s1vMyuCl3R7:b-olf3f0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/util.go, line 169 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-LihTPyTDKwv3oE7Ic2Y:-LihTPyTDKwv3oE7Ic2Z:bat3k4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/optbuilder/util.go#L169)):*
> ```Go
> // typ    The type of the column.
> // expr   The expression this column refers to (if any).
> //
> ```

can you add a description of scalar?

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-:-Lihlfub0A5pcryW9Z61:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @knz, and @rytaft)

___
*[pkg/sql/opt/memo/interner.go, line 579 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-Ligpovb5iO2ccUZQETf:-LihjGGEDg_fhz5zeDAM:b-y8nny1) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/memo/interner.go#L579)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Is this safe? If you have a plan generated, then it gets de-allocated, then the address gets reused for a different plan, the hash will compare the same. 
(Is there an additional string comparison if the hashes compare equal?)
</blockquote></details>

We are always comparing against something that's stored in the interner, so the pointer is valid. When the hashes match, we use IsOpaqueMetadataEqual on the actual values.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1791 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-Ligq2pD8hil9wneh81-:-LihjQrCB4CsSduZabeV:b-txywvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/memo/logical_props_builder.go#L1791)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you explain "CanMutate" a bit more?

I agree that in general a feature called "opaque plans" can do pretty much anything, *however* in the particular case of this PR and the use cases you're designing this for, it seems there are no mutations?
I don't know if setting this flag disables any optimizations, but if it does maybe you'll want to split opaque-read-only vs opaque-mutation.
</blockquote></details>

AFAICT it's used to generate an error when it's part of a CTE that is not being used. I believe this will go away soon when we improve our support for CTEs.

Eventually, all remaining "leaf" plan nodes will be opaque operators. It is necessary to support `SELECT .. FROM [ EXPLAIN <some-op> ]` without using the HP.
___
*[pkg/sql/opt/optbuilder/util.go, line 169 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-LihTPyTDKwv3oE7Ic2Y:-Lihk1Ia66Cn0cgK46JD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/optbuilder/util.go#L169)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

can you add a description of scalar?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 257 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-LigqU7fBRq4xE-vF9bL:-Lihit92-PpCbunkXLrz:b-ivu4vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/666264a596b6d98f755d1c92aeb49d231dad3ebf/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L257)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`panic(errors.NewAssertionFailedf)` perhaps
</blockquote></details>

this is optgen which uses simple panics

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38445)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @knz)

**Review by justinj — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-:-Lii0i7P22ss2HBCUert:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @knz, and @RaduBerinde)

___
*[pkg/sql/opt_exec_factory.go, line 1590 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38445#-Lii-Edo1WpzohK2H7dU:-Lii-Edo1WpzohK2H7dV:b-8lojbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f6d4488720450002e2bd902ab6e059255925b7e/pkg/sql/opt_exec_factory.go#L1590)):*
> ```Go
> 	o, ok := metadata.(*opaqueMetadata)
> 	if !ok {
> 		return nil, errors.AssertionFailedf("unexpected OpaqueMedata object type %T", metadata)
> ```

nit: `Metadata`

**Pull request merged**
