### PR TITLE
server: properly config disk spill storage for shared-process tenant servers

### LINKED ISSUE #98247: sql: query fails with "disk budget exceeded" in multi-tenant mode
The SQL below succeeds in the demo with `--multitenant=false`, but errors with `--multitenant=true`:

```sql
CREATE TABLE a (a INT);
INSERT INTO a SELECT i FROM generate_series(10, 100000) g(i);
SELECT (SELECT bool_or(a = i) FROM a) FROM generate_series(1, 20) g(i);
```

```
ERROR: temp disk storage: disk budget exceeded: 1048576 bytes requested, 0 currently allocated, 0 bytes in budget
SQLSTATE: 53100
```

Jira issue: CRDB-25151
Epic: CRDB-23559

### PR DESCRIPTION
**Pull request by knz**
Fixes #98247.
Epic: CRDB-23559

Prior to this patch, the temp storage for secondary tenants was using
the "previously seen max actual usage" of the temp storage for the
surrounding KV node. So if not SQL query had been running yet, that
limit would be very low (or zero).

A better limit is to simply propagate the same as the KV node, which
is the one configured on the command line.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100869#-:-NSNL-7c6pu81sWxVsXB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

**Comment by knz** [comment]
bors r=yuzefovich

**Comment by knz** [comment]
bors r=yuzefovich

**Comment by knz** [comment]
CI flake is this #100853

**Pull request merged**
