### PR TITLE
opt: fix implicit lateral for SRFs when using JOIN syntax

### LINKED ISSUE #70342: sql: CTE source not available as function argument in JOIN target
NOTE: the underlying issue here may be misdiagnosed. Feel free to rename.

When passing the `Prefer: return=headers-only` or `Prefer: return=representation` HTTP header on a POST request to [request a newly inserted row's primary key](https://postgrest.org/en/v8.0/api.html#insertions-updates), PostgREST issues the following query:
```sql
  WITH pgrst_source AS (
                             WITH pgrst_payload AS (SELECT $1::JSONB AS json_data),
                                  pgrst_body AS (SELECT CASE WHEN json_typeof(json_data) = 'array' THEN json_data ELSE json_build_array(json_data) END AS val FROM pgrst_payload)
                           INSERT
                             INTO public.promo_codes (code)
                           SELECT code
                             FROM json_populate_recordset(NULL::public.promo_codes, (SELECT val FROM pgrst_body)) AS _
                        RETURNING public.promo_codes.*
                    )
SELECT '' AS total_result_set,
       pg_catalog.count(_postgrest_t) AS page_total,
       CASE
       WHEN pg_catalog.count(_postgrest_t) = 1
       THEN COALESCE(
        (
              WITH data AS (SELECT row_to_json(_) AS row FROM pgrst_source AS _ LIMIT 1)
            SELECT array_agg(json_data.key || '=' || COALESCE('eq.' || json_data.value, 'is.null'))
              FROM data CROSS JOIN json_each_text(data.row) AS json_data
             WHERE json_data.key IN ('code',)
        ),
        ARRAY[]::STRING[]
       )
       ELSE ARRAY[]::STRING[]
       END AS header,
       '' AS body,
       NULLIF(current_setting('response.headers', true), '') AS response_headers,
       NULLIF(current_setting('response.status', true), '') AS response_status
  FROM (SELECT * FROM pgrst_source) AS _postgrest_t;
```

Currently, this returns the following error:
```
ERROR: no data source matches prefix: data in this context
SQLSTATE: 42P01
```

I've simplified this down to the following incompatibility with Postgres:

### CockroachDB:
```sql
root@127.0.0.1:26257/movr> CREATE TABLE t (i INT PRIMARY KEY);
CREATE TABLE

root@127.0.0.1:26257/movr> WITH data AS (SELECT row_to_json(t) AS row FROM t)
SELECT count(*)
FROM data CROSS JOIN json_each_text(data.row);
ERROR: no data source matches prefix: data in this context
SQLSTATE: 42P01
```

### Postgres:
```sql
nathan=# CREATE TABLE t (i INT PRIMARY KEY);
CREATE TABLE

nathan=# WITH data AS (SELECT row_to_json(t) AS row FROM t)
SELECT count(*)
FROM data CROSS JOIN json_each_text(data.row);
 count
-------
     0
(1 row)
```

It appears that Cockroach does not correctly propagate the CTE source into the JOIN target's scope, so it cannot find `data` in `json_each_text(data.row)`.

Epic CRDB-10300

### PR DESCRIPTION
**Pull request by RaduBerinde**
When SRFs are used as a table, they imply that the join is lateral.
This works for the multiple table syntax, but not for the JOIN syntax.
This commit addresses this omission.

Fixes #70342.

Release note (bug fix): Fixes an incorrect "no data source matches
prefix" error for queries that use a set-returning function on the
right-hand side of a `JOIN` (unless `LATERAL` is explicitly
specified).

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71396#-:-MllIQNI-nHy4hUIKS2s:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: Good find!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71396#-:-MllTkkI27q4I8rkvmlR:b-q4hbyk)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/join.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71396#-MllTMuP8YOh8JNsiTZM:-MllTMuP8YOh8JNsiTZN:b-xcqxns) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f546a65e572e6008db69a2677e4ede5a48508cc/pkg/sql/opt/optbuilder/join.go#L44)):*
> ```Go
> 	// the left side.
> 	if t, ok := join.Right.(*tree.AliasedTableExpr); ok && t.Lateral {
> 		telemetry.Inc(sqltelemetry.LateralJoinUseCounter)
> ```

do we still need this telemetry?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71396)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/join.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71396#-MllTMuP8YOh8JNsiTZM:-MllTuGMDXXEPkaKj2Vk:biog6kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f546a65e572e6008db69a2677e4ede5a48508cc/pkg/sql/opt/optbuilder/join.go#L44)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do we still need this telemetry?
</blockquote></details>

Yeah, I removed it accidentally (and some tests failed on CI because of it). Moved it to `exprIsLateral`.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71396)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
