### PR TITLE
kv: support Leader lease construction and validation

### PR DESCRIPTION
**Pull request by nvb**
Part of #123847.
Part of #125237.
The remaining work for these issues is to test the integration with Raft once leader fortification is hooked up to `raft.Status.LeadSupportUntil`.

This commit adds the ability to construct a Leader lease and the ability to evaluate the validity of a Leader lease.

Construction of a Leader lease is straightforward. The Raft leader (fortified or not) is allowed to propose a Lease with a Term field set to the Leader's current term. This will bind the lease to the leadership term and permit the lease to inherit leader fortification support as its expiration (in addition to a minimum expiration). The lease remains valid for as long as the leader retains support from its quorum, which is all indirectly coordinated through Store Liveness.

Validation of a Leader lease is more complex due to an information asymmetry. The Raft leader knows its own term and its leader fortification support, so it can evaluate the lease's validity without ambiguity.

However, follower replicas do not have this information. Instead, they must rely on observing raft leadership changes to infer leader support. Specifically, a follower replica (during the lease's term) can not determine the leader support status of the lease unless it knows of a Raft leader at a later term (which may be itself). Knowledge of a Raft leader at a later term proves that the support for this earlier term (which the lease is associated with) has been lost, otherwise no new leader could have been elected. The ability to make this inference builds on the Raft leader fortification safety property.

If the follower replica (during the lease's term) does not know of a Raft leader at a later term, the leader's term may still be supported and the lease may still be valid. We cannot say for sure, so we must assume the lease is still valid and respect it. In cases where the leaseholder crashes, follower replicas must wait for raft to elect a new leader before any other replica (typically the new leader) can determine the (in)validity of the old lease and replace it.

Release note: None

### CODE REVIEW

**Review by miraradeva — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127211)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wgTVZ3WAp074iop4k:-O1wgTVZ3WAp074iop4l:b-6lcvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/replica_range_lease.go#L1213)):*
> ```Go
> 				// ERROR status on follower replicas instead of a VALID status, we will
> 				// hit this path more. Do we need to add the lease to this
> 				// NotLeaseHolder error to ensure fast redirection?
> ```

Does the `DistSender` already do the redirection? Or it just keeps trying other replicas?
___
*[`pkg/kv/kvserver/leases/build.go` line 493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wnHqm9Nyibk7xGpjK:-O1wnHqm9Nyibk7xGpjL:blbbqy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build.go#L493)):*
> ```Go
> 		// time, regardless of whether this is a promotion from an expiration-based
> 		// lease or not. This provides a lower bound for the lease's expiration,
> 		// independent of the leader fortification.
> ```

When this is not a promotion from an expiration-based lease, do we need the minimum expiration to be enforced for the correctness of the Lease Disjointness property, or for something else? My understanding was that the guarantees we get through leader fortification are enough for Lease Disjointness.
___
*[`pkg/kv/kvserver/leases/build.go` line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1womKd0R3CafNXc9-2:-O1womKd0R3CafNXc9-3:b-n13wj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build.go#L682)):*
> ```Go
> 		// Epoch-based leases may or may not have a minimum expiration time set.
> 	case roachpb.LeaseLeader:
> 		// Leader leases may or may not have a minimum expiration time set.
> ```

The comment in `leaseMinTimestamp` seems to indicate that we always set a min expiration for leader leases. We just don't validate it?
___
*[`pkg/kv/kvserver/leases/status.go` line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wsnmh-z1sfnlSFpGH:-O1wsnmh-z1sfnlSFpGI:b-mpvjsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L154)):*
> ```Go
> 		// For leader leases, evaluate the Raft leader support information
> 		// associated with the lease.
> 		if lease.Replica.StoreID == i.LocalStoreID {
> ```

Is this the same as `lease.OwnedBy(i.LocalStoreID)`?
___
*[`pkg/kv/kvserver/leases/status.go` line 189 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wu55FE8Rt8x_7uIZ3:-O1wu55FE8Rt8x_7uIZ4:b-hboxfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L189)):*
> ```Go
> 			// for the lease, but we know that it has either already expired or was
> 			// never even established due to a failure of the raft leader to fortify.
> 			// Either way, the leader of lease.Term cannot think this lease's leader
> ```

How do we know for sure that the lease has either expired or it was never fortified? My understanding of the previous comment (above `knownSuccessor`) is that at this point we don't know, and the lease may still be valid. Min expiration in the future is one way to be valid past this point, but is it the only way?
___
*[`pkg/kv/kvserver/leases/build_test.go` line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wv2Mz9onAJOpJsAm6:-O1wv2Mz9onAJOpJsAm7:b-4jcl12) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build_test.go#L422)):*
> ```Go
> 				input: defaultInput,
> 				expOutput: Output{
> 					NextLease: roachpb.Lease{
> ```

Is it possible to include the lease type in these expected `Lease` structs?
___
*[`pkg/kv/kvserver/leases/build_test.go` line 472 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wvKLN7sUmB25_XxW3:-O1wvKLN7sUmB25_XxW4:bko0gc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build_test.go#L472)):*
> ```Go
> 			},
> 			{
> 				name: "replace expiration, acquire lease lease, as raft follower",
> ```

nit: "leader lease"

**Review by arulajmani — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 6 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127211)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25O2u_2BVsf4EA2bR4:-O25O2u_2BVsf4EA2bR5:b63fuih) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/replica_range_lease.go#L707)):*
> ```Go
> 		Lease:              *r.mu.state.Lease,
> 	}
> 	// TODO(nvanbenschoten): evaluate whether this is too expensive to compute for
> ```

nit: should we open an issue for this? 
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wgTVZ3WAp074iop4k:-O25MAe26MTQc7x7uY73:b-u3yk1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/replica_range_lease.go#L1213)):*
The `DistSender` updates its cache with the lease specified in the `NLHE`. It then prefers to redirect to the leaseholder over a random replica. 

> Do we need to add the lease to this NotLeaseHolder error to ensure fast redirection?

I think so. 

Another interesting case is when a (say) a leader has crashed, the QSE has been served out, and a new leader is being elected. Say you hit a replica that's campaigning, and is either in `StateCandidate` or `StatePreCandidate`. Who should you redirect to? 

Do we want to have no lease information in the `NLHE` and let the `DistSender` continue on with its iteration, or do we want the `DistSender` to retry us after backing off (On the optimistic assumption that we'll win the election)?
___
*[`pkg/kv/kvserver/leases/build.go` line 493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wnHqm9Nyibk7xGpjK:-O25aa2vBGKMmX4ks7iJ:bl9a9dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build.go#L493)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

When this is not a promotion from an expiration-based lease, do we need the minimum expiration to be enforced for the correctness of the Lease Disjointness property, or for something else? My understanding was that the guarantees we get through leader fortification are enough for Lease Disjointness.
</blockquote></details>

There may be more to this, and I'm curious to hear what Nathan has to say, but I think one reason we need this is that we don't check if a leader is fortified or not when proposing a leader lease. `MinExpiration` ensures that the lease disjointness property is upheld even if the leader is unable to fortify. 
___
*[`pkg/kv/kvserver/leases/status.go` line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25cJaN20P38IRPvXuQ:-O25cJaN20P38IRPvXuR:b4gtz0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L167)):*
> ```Go
> 			// support status of the lease unless we know of a Raft leader at a later
> 			// term (which may be ourselves). Knowledge of a Raft leader at a later
> 			// term proves that the support for this earlier term (which the lease is
> ```

There's still the `MinExpiration` caveat though, right?

EDIT: it's talked about below, so disregard this. 
___
*[`pkg/kv/kvserver/leases/status.go` line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25fXSlEdxqrSx-hG_H:-O25fXSlEdxqrSx-hG_I:biarxa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L179)):*
> ```Go
> 			knownValid := i.Now.ToTimestamp().Less(lease.MinExpiration)
> 			if !knownSuccessor && !knownValid {
> 				// TODO(nvanbenschoten): we could introduce a new INDETERMINATE state
> ```

I'd be in favour of this. We could then return a speculative lease back up to the `DistSender` which points to the raft leader. This relates to your comment in `redirectOnOrAcquireLeaseForRequest`. Doesn't have to be in this PR, but if we're sold on the approach, let's capture it in an issue?
___
*[`pkg/kv/kvserver/leases/status.go` line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25eKnC4XdZmV-aq3G-:-O25eKnC4XdZmV-aq3G0:b-14qt95) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L187)):*
> but we know that it has either already expired or was
			// never even established due to a failure of the raft leader to fortify.

Related to my comment below, it's a bit confusing that this comes before we talk about the lease's minimum expiration. If the intention is to treat minimum expiration as a special case and not detract from the main point, consider adding an asterisk here to point to the blurb about minimum expiration.
___
*[`pkg/kv/kvserver/leases/status.go` line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25e6KAA441EmUi6Pny:-O25e6KAA441EmUi6Pnz:b-828wsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L192)):*
> ```Go
> 			// support is in the future.
> 			//
> 			// However, the lease's minimum expiration may still be in the future
> ```

nit: the placement of this paragraph feels a bit off as we're checking this above, with `KnownValid`.

**Review by nvb — COMMENTED** [review]
TFTRs! I've addressed the comments that can be addressed at this point. The remaining work for https://github.com/cockroachdb/cockroach/issues/123847 around the two TODOs will need to come after leader support is implemented at the raft level, so I'll hold off on addressing them in this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-:-O3-HJG21rryl69_5ODf:bhugpy2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25O2u_2BVsf4EA2bR4:-O3-BB5O9DQpyIpdOQPa:buxwzio) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/replica_range_lease.go#L707)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: should we open an issue for this?
</blockquote></details>

I was planning to use https://github.com/cockroachdb/cockroach/issues/125255 as our tracking issue for this. Added a link to the comment.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wgTVZ3WAp074iop4k:-O3-Gim20gfbTMnYBXhy:ban55nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/replica_range_lease.go#L1213)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The `DistSender` updates its cache with the lease specified in the `NLHE`. It then prefers to redirect to the leaseholder over a random replica. 

> Do we need to add the lease to this NotLeaseHolder error to ensure fast redirection?

I think so. 

Another interesting case is when a (say) a leader has crashed, the QSE has been served out, and a new leader is being elected. Say you hit a replica that's campaigning, and is either in `StateCandidate` or `StatePreCandidate`. Who should you redirect to? 

Do we want to have no lease information in the `NLHE` and let the `DistSender` continue on with its iteration, or do we want the `DistSender` to retry us after backing off (On the optimistic assumption that we'll win the election)?
</blockquote></details>

These are all good questions. Either approach will work to eventually redirect to the new leaseholder, though we could be smarter about who to redirect to, based on what we see in Raft.

I'll leave this TODO and the other in `status.go` for now as part of completing https://github.com/cockroachdb/cockroach/issues/123847, since I can't test changes in behavior until the leader support is plugged in a bit further. 
___
*[`pkg/kv/kvserver/leases/build.go` line 493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wnHqm9Nyibk7xGpjK:-O3-1oGU0SO37bz5FMXX:b-t6p8f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build.go#L493)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

There may be more to this, and I'm curious to hear what Nathan has to say, but I think one reason we need this is that we don't check if a leader is fortified or not when proposing a leader lease. `MinExpiration` ensures that the lease disjointness property is upheld even if the leader is unable to fortify.
</blockquote></details>

It's a little of both. We use the `MinExpiration` to ensure that the lease has some validity window even if the raft leader never ends up fortifying. That allows us to propose the lease even before we have fortified, and just allow fortification to be the extension mechanism.

That said, when not promoting from an expiration-based lease, the minimum expiration is not needed to enforce the Lease Disjointness property, because we will only propose the lease after the previous lease has expired and with a StartTime of now.

So MinExpiration is needed for correctness during a promotion, but is helpful in all cases. I'll add this to the commentary.
___
*[`pkg/kv/kvserver/leases/build.go` line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1womKd0R3CafNXc9-2:-O3-4rKV1LA0NZB_VihE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build.go#L682)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

The comment in `leaseMinTimestamp` seems to indicate that we always set a min expiration for leader leases. We just don't validate it?
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/leases/status.go` line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wsnmh-z1sfnlSFpGH:-O3-4xv_3oTWHVbb4taj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L154)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Is this the same as `lease.OwnedBy(i.LocalStoreID)`?
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/leases/status.go` line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25eKnC4XdZmV-aq3G-:-O3-74qdALVJ9DAdyVu2:b9whn89) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L187)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> but we know that it has either already expired or was
			// never even established due to a failure of the raft leader to fortify.

Related to my comment below, it's a bit confusing that this comes before we talk about the lease's minimum expiration. If the intention is to treat minimum expiration as a special case and not detract from the main point, consider adding an asterisk here to point to the blurb about minimum expiration.
</blockquote></details>

Done. I re-organized this logic to make things more clear.
___
*[`pkg/kv/kvserver/leases/status.go` line 189 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wu55FE8Rt8x_7uIZ3:-O3-7MQT40Q2rDaMkb0G:b9whn89) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L189)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

How do we know for sure that the lease has either expired or it was never fortified? My understanding of the previous comment (above `knownSuccessor`) is that at this point we don't know, and the lease may still be valid. Min expiration in the future is one way to be valid past this point, but is it the only way?
</blockquote></details>

Done. I re-organized this logic to make things more clear.
___
*[`pkg/kv/kvserver/leases/status.go` line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O25e6KAA441EmUi6Pny:-O3-7Mv46aSdkuTeNe4s:b9whn89) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/status.go#L192)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: the placement of this paragraph feels a bit off as we're checking this above, with `KnownValid`.
</blockquote></details>

Done. I re-organized this logic to make things more clear.
___
*[`pkg/kv/kvserver/leases/build_test.go` line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wv2Mz9onAJOpJsAm6:-O3-AlGd6_mjPNMXxej3:b-bwgghc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build_test.go#L422)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Is it possible to include the lease type in these expected `Lease` structs?
</blockquote></details>

The lease type is a function of the fields that are set in `roachpb.Lease` (see `Lease.Type`), so we'd need to jump through some hoops and add some redundancy to get something that looks like that.
___
*[`pkg/kv/kvserver/leases/build_test.go` line 472 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wvKLN7sUmB25_XxW3:-O3-B7_e8sc5oYpVNtU8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build_test.go#L472)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

nit: "leader lease"
</blockquote></details>

Done.

**Review by miraradeva — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-:-O381GVG7Lpaqb5VjlGA:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/leases/build.go` line 493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127211#-O1wnHqm9Nyibk7xGpjK:-O380sLb6kuweldUutUz:b9ca5ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/a927f07084588030335f85b2f6550a278a78b2ce/pkg/kv/kvserver/leases/build.go#L493)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's a little of both. We use the `MinExpiration` to ensure that the lease has some validity window even if the raft leader never ends up fortifying. That allows us to propose the lease even before we have fortified, and just allow fortification to be the extension mechanism.

That said, when not promoting from an expiration-based lease, the minimum expiration is not needed to enforce the Lease Disjointness property, because we will only propose the lease after the previous lease has expired and with a StartTime of now.

So MinExpiration is needed for correctness during a promotion, but is helpful in all cases. I'll add this to the commentary.
</blockquote></details>

Thanks, makes sense.

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
