### PR TITLE
backupccl: remove experimental marker from revision history

### PR DESCRIPTION
**Pull request by dt**
Release note (enterprise change): revision history backup and restore no longer considered experimental.

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by dt** [comment]
We could instead make the experimental label optional -- accept queries with and without it, with an `opt_experimental` rule -- but since this was a) never included in a stable release b) marked as experimental in alphas, I'm not convinced it is worth keeping the extra cruft around for all of 2.0

**Comment by knz** [comment]
> We could instead make the experimental label optional 

that's exactly the thing that you technically *cannot* do without starting to make the grammar ambiguous the next time we want to add a feature in that area.

Also exactly the reason why we need to prefix keywords with `experimental_...` instead of a separate keyword.

**Comment by knz** [comment]
see #22538.

**Comment by knz** [comment]
With an `experimental_xxx` keyword then it's possible to make the *scanner* recognize both forms without ambiguity, and then you'd be golden continuing to support the syntax even after the experimental bit was dropped

**Comment by dt** [comment]
@knz yeah, but in this case, the only reason to do it at all would be to maintain compatibility -- which means supporting the current, standalone form. In practice, i'm not actually that worried about the potential ambiguity issue here, since I assume we'd be removing the optional experimental label in the next version anyway, so new features wouldn't need to worry about it.

That said, I still don't think we need to do it at all, for the reasons mentioned above.

**Pull request merged**
