### PR TITLE
acceptance: Add which node an error came from in failure messages

### PR DESCRIPTION
**Pull request by a-robinson**
This helped me narrow down where to look when dealing with a failure.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11685)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/admin_test.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685#-KXkzzixcwiw9AgyoWIA:-KXkzzixcwiw9AgyoWIB:b4fs218) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a252cc2556aab92cfeedd1ffeae0cad9399df1/pkg/acceptance/admin_test.go#L56)):*
> ```Go
> 	for i := 1; i < c.NumNodes(); i++ {
> 		if err := c.Kill(i); err != nil {
> 			t.Fatalf("failed to kill node %d: %s", i, err)
> ```

put this extra detail inside `(*Container).Kill()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685#-:-KXl-32qOAbVXVKGJ7JL:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/admin_test.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685#-KXkzzixcwiw9AgyoWIA:-KXl0jTI0HDYe8ihBCJn:b5mvp15) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a252cc2556aab92cfeedd1ffeae0cad9399df1/pkg/acceptance/admin_test.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

put this extra detail inside `(*Container).Kill()`
</blockquote></details>

Unless I'm missing something (*Container).Kill doesn't know the node's position in the cluster, just its docker container ID/name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/admin_test.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685#-KXkzzixcwiw9AgyoWIA:-KXl1myni-Q_morljGRP:burhdko) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a252cc2556aab92cfeedd1ffeae0cad9399df1/pkg/acceptance/admin_test.go#L56)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Unless I'm missing something (*Container).Kill doesn't know the node's position in the cluster, just its docker container ID/name.
</blockquote></details>

Sorry, I meant cluster.Kill, which takes the integer node index.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/admin_test.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685#-KXkzzixcwiw9AgyoWIA:-KXl3hYYQ0jtqxeiZUJw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a252cc2556aab92cfeedd1ffeae0cad9399df1/pkg/acceptance/admin_test.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Sorry, I meant cluster.Kill, which takes the integer node index.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/cluster/localcluster.go, line 839 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685#-KXlFTs1b8qEUhX9WUH_:-KXlFTs1b8qEUhX9WUHa:b-3y6zl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fd5a35bbcfa16b4d92426832d0b7d01bddc221/pkg/acceptance/cluster/localcluster.go#L839)):*
> ```Go
> 	// The default timeout is 10 seconds.
> 	if err := l.Nodes[i].Restart(nil); err != nil {
> 		return errors.Wrapf(err, "failed to restart node %d", i)
> ```

FYI `errors.Wrapf(nil, "hello") == nil`. Just saying, no need to change this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11685)*

**Pull request merged**
