### PR TITLE
sql: renderNode and double sortNode elision

### LINKED ISSUE #16535: sql: renderNode not elided when column needs renaming
From https://github.com/cockroachdb/cockroach/pull/16533#issuecomment-308756655.

Whenever we need to rename a result column, `renderNode` cannot be elided.

```
root@:26257/> EXPLAIN (VERBOSE) select k, v FROM test.t;
+-------+------+-------+-------------+---------+----------+
| Level | Type | Field | Description | Columns | Ordering |
+-------+------+-------+-------------+---------+----------+
|     0 | scan |       |             | (k, v)  |          |
|     0 |      | table | t@primary   |         |          |
|     0 |      | spans | ALL         |         |          |
+-------+------+-------+-------------+---------+----------+
(3 rows)
root@:26257/> EXPLAIN (VERBOSE) SELECT k AS lol, v FROM test.t;
+-------+--------+----------+-------------+----------+----------+
| Level |  Type  |  Field   | Description | Columns  | Ordering |
+-------+--------+----------+-------------+----------+----------+
|     0 | render |          |             | (lol, v) |          |
|     0 |        | render 0 | test.t.k    |          |          |
|     0 |        | render 1 | test.t.v    |          |          |
|     1 | scan   |          |             | (k, v)   |          |
|     1 |        | table    | t@primary   |          |          |
|     1 |        | spans    | ALL         |          |          |
+-------+--------+----------+-------------+----------+----------+
(6 rows)
```

Some ideas:
 - when eliding renderNodes, see if we can rename the column of the source node instead of keeping the renderNode. This will probably depend on the node type (unless we want to add a `planNode` API to rename columns).
 - or, use a different mechanism to properly name the final columns. Once names are resolved, the names of intermediary columns inside a query are not important, only the final columns.

CC @knz

### PR DESCRIPTION
**Pull request by knz**
Fixes #16535.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588#-Kn-aGuX5J8ocRd0pwcw:-Kn-aGuYmMoy_PwTIFH-:b7edc2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e52856165a4a90fa74b5a3f7303f8443f367ffee/pkg/sql/expand_plan.go#L304)):*
> ```Go
> 	// Elide the render node if it renders its source as-is.
> 
> 	sourceCols := planColumns(r.source.plan)
> ```

We are mutating these columns. This is not ok given the current implementation of `planColumns` - what if the node has a fixed schema (e.g. `explainDistSQLNode`)?
BTW the doc for `planColumns` should explain what the caller can do w.r.t changing the columns

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588)*

**Comment by knz** [comment]
Solid feedback; thanks for noticing.

Fixed, PTAL.

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/plan_columns.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588#-Kn4alcJKCb1iXpQMQWv:-Kn4alcJKCb1iXpQMQWw:byb6il4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cd8221d55526680f6a58d5e7c3d276a65a8e555/pkg/sql/plan_columns.go#L46)):*
> ```Go
> }
> 
> func getPlanColumns(plan planNode, mut bool) sqlbase.ResultColumns {
> ```

could use a short comment explaining mut

---

*[pkg/sql/plan_columns.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588#-Kn4b_ItntUgrjrDL9P5:-Kn4b_Iu2p4BLhp26feU:be691ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cd8221d55526680f6a58d5e7c3d276a65a8e555/pkg/sql/plan_columns.go#L140)):*
> ```Go
> 	}
> 	c.columns = make(sqlbase.ResultColumns, len(cols))
> 	for i, col := range cols {
> ```

[nit] could just `copy(c.columns, cols)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588#-:-Kn4bx0MQspWv3qynf4h:b-uwkowd)*

**Comment by knz** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/plan_columns.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588#-Kn4alcJKCb1iXpQMQWv:-Kn57TuPN5RioCsVGgXI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cd8221d55526680f6a58d5e7c3d276a65a8e555/pkg/sql/plan_columns.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

could use a short comment explaining mut
</blockquote></details>

Done.

---

*[pkg/sql/plan_columns.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588#-Kn4b_ItntUgrjrDL9P5:-Kn57Utx8qNuscfsTkQm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cd8221d55526680f6a58d5e7c3d276a65a8e555/pkg/sql/plan_columns.go#L140)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could just `copy(c.columns, cols)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588)*

**Comment by RaduBerinde** [comment]
Reviewed 5 of 6 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16588)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
