### PR TITLE
sql/pgwire: Clean up writeBuffer interface

### PR DESCRIPTION
**Pull request by nvb**
This change:
- pulls error field codes into `serverErrFieldType`
- adds a `nullTerminate` method to `writeBuffer`
- creates a preserved error pattern for `writeBuffer`

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6641)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/encoding.go, line 163 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXRlo51PjdcbvKFFUT:-KHXRlo51PjdcbvKFFUU:-1126471365) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L163)):*
> ```Go
> func (b *writeBuffer) writeByte(c byte) {
> 	if b.err == nil {
> 		b.err = b.wrapped.WriteByte(c)
> ```

how do you feel about basically every method here calling `setError` instead of manually doing it?

---

*[sql/pgwire/encoding.go, line 249 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXS-96FYYTfba_G7e1:-KHXS-96FYYTfba_G7e2:1625195337) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L249)):*
> ```Go
> 	n, err := w.Write(bytes)
> 	b.bytecount.Inc(int64(n))
> 	return err
> ```

this is a bit subtle for my liking

---

*[sql/pgwire/encoding.go, line 254 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXRT58wa87Fj1mtKQu:-KHXRT58wa87Fj1mtKQv:1584442964) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L254)):*
> ```Go
> // setError sets the writeBuffer's error, if it does not already have one.
> func (b *writeBuffer) setError(err error) {
> 	if b.err != nil {
> ```

should be `== nil`, yeah?

---

*[sql/pgwire/v3.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXNwkuZ54ZQtr6Op0k:-KHXNwkuZ54ZQtr6Op0l:-241167450) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9fe79e3e520f1f26a33e339e0e55161339875c/sql/pgwire/v3.go#L69)):*
> ```Go
> )
> 
> //go:generate stringer -type=serverErrFieldType
> ```

do you need stringer here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/pgwire/encoding.go, line 163 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXRlo51PjdcbvKFFUT:-KH_L9RYBzIfUZ44P8tG:1570998637) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L163)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how do you feel about basically every method here calling `setError` instead of manually doing it?</details>
In theory I like it, but it would make things uglier and more obscure for wrapped writes with multiple return values (eg. `_, b.err = b.wrapped.Write(p)`). Plus `setError` would check the `b.err` status again.

---

*[sql/pgwire/encoding.go, line 249 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXS-96FYYTfba_G7e1:-KH_LFL5bwYklmxVxe2P:-1687133971) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L249)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is a bit subtle for my liking</details>
Do you mean the implicit `n == 0` when `err != nil`? Done.

---

*[sql/pgwire/encoding.go, line 254 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXRT58wa87Fj1mtKQu:-KH_LsSTzyCmvQDoIlK8:1483181885) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L254)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should be `== nil`, yeah?</details>
Good catch. Done.

---

*[sql/pgwire/v3.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXNwkuZ54ZQtr6Op0k:-KH_MANhzLaaEkziqgMr:352303231) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9fe79e3e520f1f26a33e339e0e55161339875c/sql/pgwire/v3.go#L69)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> do you need stringer here?</details>
We don't *need* it, but we're adding it for all the other enumerations here and it's nice to have for debugging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/pgwire/encoding.go, line 249 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXS-96FYYTfba_G7e1:-KH_NAyCM8FyWOSCqAoZ:-1018354451) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L249)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Do you mean the implicit `n == 0` when `err != nil`? Done.</details>
nah, I meant that this method doesn't set b.err because it is the "finisher". I think you can revert that thing you just changed here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/pgwire/encoding.go, line 249 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-KHXS-96FYYTfba_G7e1:-KH_NvxKNOljy7RxAf0T:2077551191) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3d3893bf3c00e5d76df86258cbee7909dd4b20/sql/pgwire/encoding.go#L249)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nah, I meant that this method doesn't set b.err because it is the "finisher". I think you can revert that thing you just changed here.</details>
It doesn't set `b.err` because it's explicitly resetting it. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> #### sql/pgwire: Clean up writeBuffer interface
> 
> This change:
> 
> - pulls error field codes into `serverErrFieldType`
> 
> - adds a `nullTerminate` method to `writeBuffer`
> 
> - creates a preserved error pattern for `writeBuffer`
> 
> 
> </details>


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-:-KH_VP7fF2jBx4-zCSwp:1417088721)*

**Comment by nvanbenschoten** [comment]
Thanks for the review.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> :lgtm:</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6641#-:-KH_YdanmcHRwRqnp1S_:-588504482)*

**Pull request merged**
