### PR TITLE
build,Makefile: break up the release process into two phases

### PR DESCRIPTION
**Pull request by danhhz**
I need the bound the time I can spend babysitting the next release if
anything goes wrong, so this is done in a purely additive manner which,
in the worst case, will allow falling back to the previous release
process. Once we're happy with the new one, we can clean up the old code
and scripts.

The first phase is to build provisional binaries. These are exactly the
bits we intend to ship as whatever version we're releasing. The
provisional SHA is marked in git by a tag with the form
`provisional_yyyymmddhhss_<semver>`. The various binaries (a combination
of platform, fully static vs not, race vs not) are uploaded to their
final places in s3, but nothing points at them.

At this point, the release coordinator will stage these binaries on the
long running clusters for verification. A followup PR will also allow
them to be used for a run of the nightly and weekly roachtests.

If any issues are found, a new SHA is selected, a new provisional tag is
pushed for it, binaries are built again, and verification is resumed.

Once we have provisional binaries that we're happy with, they're
blessed, which is the second phase. This makes and uploads the source
archive artifact. If the release is the latest stable release, it also
updates the various latest pointers.

The continuous publication of binaries for every green master build is
still supported but currently a bit of a hack. Ideally, the teamcity
build for it would work by releasing the provisional binaries and
immediately blessing them. However, the latest pointers work differently
between the two, so for now, this entire process is left inside the
provisional binaries step and blessing is disallowed for non-releases.
Perhaps we can unify the behaviors a bit and clean this up at some
point. The standalone workload binary is no longer continuously
published, since it's now built into the cockroach binary.

To pull all of this off, a small bit of functionality had to be added to
the Makefile. The version that a binary self reports is usually
determined automatically based on the "closest" git tag of whatever
checkout built it. We don't want the provisional tags to be considered
in this, so when we build the provisional binary, we need to override
the version. A BUILDINFO_TAG override is added for this to the various
ways to make a binary `make {mkrelease,build,...}` as well as `make
archive`.

As far as I can tell, everything is uploaded to the same place and with
the same folder and binary names as before, _except_ the folder inside
the artifact for the latest binary is now `cockroach_<semver>_<suffix`
instead of `cockroach_latest_<suffix>`. This should be fine, since both
`crl-stage-binaries` and `roachprod stage untar it with
`--strip-components 1`. (In fact, I think finally doing the TODO to
always make latest a redirect may be as simple as adding the `-L` flags
to curl in those two places.)

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
There are a number of loose ends to tie up, but this is ready for an initial pass. The `BUILDINFO_TAG` override ended up working quite well.

**Comment by danhhz** [comment]
Oh and if anyone stumbles on this, be aware that I'm still working out the least disruptive way to transition over to this (and on migrating the docs).

**Comment by danhhz** [comment]
Prototyped the doc update https://github.com/cockroachdb/cockroach/wiki/WIP-New-Release-Process. Looks like rolling_restart_cluster.sh will have to be updated to support release binaries. It currently only uses the edge binaries.

**Review by bdarnell — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33516)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/publish-provisional-artifacts/main.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33516#-LVfsSRRAp1zb8x6myDZ:-LVfsSRS8OA63Plqr4YT:bcr6zh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/05675ec3addd7f22c9738941519df6ec72880a53/pkg/cmd/publish-provisional-artifacts/main.go#L102)):*
> ```Go
> 	// The old behavior of publish-artifacts was to publish the binaries and
> 	// immediately bless them. The new release process breaks this up, but for
> 	// now setting neither will (hopefully) exactly match the old behavior.
> ```

Why do we need to match the old behavior if this is a new command?
___
*[pkg/cmd/publish-provisional-artifacts/main.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33516#-LVft26s0ia-7VXzT3HP:-LVft26s0ia-7VXzT3HQ:b-8hjb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/05675ec3addd7f22c9738941519df6ec72880a53/pkg/cmd/publish-provisional-artifacts/main.go#L150)):*
> ```Go
> 		// `beta` for `1.0.1-beta+metadata`
> 		if ver.PreRelease() == "" {
> 			// TODO(dan): This is what it did before, but isn't this wrong? It
> ```

Yeah, I think you're right. The "latest" link updated here is rarely (if ever) used, though. We use "latest" builds from the master branch, but I think whenever we use a release build it's a specified version. (at one point the idea was to have "latest-2.0", "latest-2.1", etc links, but I don't see that here now)
___
*[pkg/cmd/publish-provisional-artifacts/main.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33516#-LVfuV5UET63yqH7YN0C:-LVfuV5UET63yqH7YN0D:b6xszh) ([raw file](https://github.com/cockroachdb/cockroach/blob/05675ec3addd7f22c9738941519df6ec72880a53/pkg/cmd/publish-provisional-artifacts/main.go#L206)):*
> ```Go
> 			//
> 			// {suffix: ".deadlock", tags: "deadlock"},
> 			{suffix: ".race", goflags: "-race"},
> ```

While you're here, you can comment this out - we don't currently use these race binaries so they just waste build time. I'm not sure whether we're ever likely to bring them back.

**Review by danhhz — COMMENTED** [review]
Thanks for the review!

bors r=bdarnell

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33516#-:-LVi7zT17Vgbt6XqizvT:bwi49li)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/publish-provisional-artifacts/main.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33516#-LVfsSRRAp1zb8x6myDZ:-LVi6FuADjzbP5cT9vJs:b2zbnor) ([raw file](https://github.com/cockroachdb/cockroach/blob/05675ec3addd7f22c9738941519df6ec72880a53/pkg/cmd/publish-provisional-artifacts/main.go#L102)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why do we need to match the old behavior if this is a new command?
</blockquote></details>

We don't. Removed
___
*[pkg/cmd/publish-provisional-artifacts/main.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33516#-LVft26s0ia-7VXzT3HP:-LVi6LHNC1on2NRV_s_k:b3q6x1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/05675ec3addd7f22c9738941519df6ec72880a53/pkg/cmd/publish-provisional-artifacts/main.go#L150)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, I think you're right. The "latest" link updated here is rarely (if ever) used, though. We use "latest" builds from the master branch, but I think whenever we use a release build it's a specified version. (at one point the idea was to have "latest-2.0", "latest-2.1", etc links, but I don't see that here now)
</blockquote></details>

When I went to test everything end-to-end, I couldn't find anything that used this latest release build thingy, so I'm pretty sure you're right. "latest-2.0", "latest-2.1" sounds like a good idea and seems easy enough to add, but I'll leave it for a followup.
___
*[pkg/cmd/publish-provisional-artifacts/main.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33516#-LVfuV5UET63yqH7YN0C:-LVi6wXb66Imeyg8O5hH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05675ec3addd7f22c9738941519df6ec72880a53/pkg/cmd/publish-provisional-artifacts/main.go#L206)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

While you're here, you can comment this out - we don't currently use these race binaries so they just waste build time. I'm not sure whether we're ever likely to bring them back. 
</blockquote></details>

Done.

**Pull request merged**
