### PR TITLE
storage: test for failed snapshots' reservations

### LINKED ISSUE #10392: storage: test that declined snapshots clean up reservations
We're lacking test coverage that declined snapshots clean up reservations. `TestSendSnapshotThrottling` tests declined snapshots independent of their processing in `Store.HandleSnapshot`. 

See https://github.com/cockroachdb/cockroach/pull/10391

### PR DESCRIPTION
**Pull request by jordanlewis**
Add a test that ensures that failing to apply an incoming snapshot cleans up the reservation that was added for it. This fails as expected if run before #10391.

Also, clean up the extra colon from the "snapshot declined" log message.

Fixes #10392.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10398)

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVa5ckipcvReifIhkMk:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 2474 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaOxFZBQ2wLp6gdTcr:-KVaOxFZBQ2wLp6gdTcs:b-2jf55r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/store.go#L2474)):*
> ```Go
> // IncomingSnapshotStream is the minimal interface on a GRPC stream required
> // to receive a snapshot.
> type IncomingSnapshotStream interface {
> ```

`s/IncomingSnapshotStream/RaftSnapshotStream/g` or `s/IncomingSnapshotStream/SnapshotStream/g` for symmetry with `RaftMessageResponseStream`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVaPFazgLKrIQt30dfT:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 2474 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaOxFZBQ2wLp6gdTcr:-KVaPqMzF2LYURrsI97V:b-e7kuo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/store.go#L2474)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/IncomingSnapshotStream/RaftSnapshotStream/g` or `s/IncomingSnapshotStream/SnapshotStream/g` for symmetry with `RaftMessageResponseStream`.
</details>
I did it this way for symmetry with `OutgoingSnapshotStream`, which is the equivalent narrowed interface for the outgoing snapshot stream type. I think it makes sense to keep this wording, since the two stream types do need to be distinguished. `RaftMessageResponseStream` doesn't seem to need the same kind of duality.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398)*

**Comment by tamird** [comment]
Re the declined response never comes with a message: is that inherent, or just that we don't supply one? Seems like we could? should?

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 666 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaWo-e6jAlllgsyQ2b:-KVaWo-e6jAlllgsyQ2c:bf9ijoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/client_raft_test.go#L666)):*
> ```Go
> 	// "snapshot accepted" message.
> 	stream := fakeSnapshotStream{nil, errors.Errorf("")}
> 	if err := mtc.stores[1].HandleSnapshotStream(&header, stream); err == nil {
> ```

please check that the error is the expected one, not just any error.

---

*[pkg/storage/store.go, line 2482 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaWL0zbkStjCGt98IH:-KVaWL0zbkStjCGt98II:b5wag58) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/store.go#L2482)):*
> ```Go
> // HandleSnapshot reads an incoming streaming snapshot and applies it if
> // possible.
> func (s *Store) HandleSnapshot(
> ```

do both of these methods need to be exported? in fact, do they both need to exist? HandleSnapshot's signature is defined by `RaftMessageHandler`, which we control, so I don't see why we need both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVaW3E_QQduc7wI_rr7:bqzki5b)*

**Comment by jordanlewis** [comment]
It's inherent for now. Declined snapshots are always due to declined reservations. Declined reservations don't get a message bubbled up, so the recipient would be sending a static message which seems like a waste of network bandwidth until someone decides to either bubble up that message or make a new reason for snapshots to be declined.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/client_raft_test.go, line 666 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaWo-e6jAlllgsyQ2b:-KVaXNuYlmCkBl52aulX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/client_raft_test.go#L666)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> please check that the error is the expected one, not just any error.
</details>
Done.

---

*[pkg/storage/store.go, line 2482 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaWL0zbkStjCGt98IH:-KVaXPKDxq99EaI0MksS:b-8iyfuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/store.go#L2482)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> do both of these methods need to be exported? in fact, do they both need to exist? HandleSnapshot's signature is defined by `RaftMessageHandler`, which we control, so I don't see why we need both.
</details>
I believe the new method needs to be exported because the test that I added that exercises the method requires `multiTestContext` which lives in `storage_test`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVaX2ijYX8iMOd-5NXk:b-z37plu)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/client_raft_test.go, line 668 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaZcxE5oCqpbO8xypM:-KVaZcxE5oCqpbO8xypN:b-wq0lhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/77dff5f77ead8714b4a5fc2f9228120537a6ad31/pkg/storage/client_raft_test.go#L668)):*
> ```Go
> 	stream := fakeSnapshotStream{nil, expectedErr}
> 	if err := mtc.stores[1].HandleSnapshotStream(&header, stream); err != expectedErr {
> 		t.Fatal("expected error %v, but found %v", expectedErr, err)
> ```

this needs to be `Fatalf`. while you're in there, `expectedErr` should be %s

---

*[pkg/storage/store.go, line 2482 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaWL0zbkStjCGt98IH:-KVaZjlF-rtq4PUn--6y:b78884o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/store.go#L2482)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> I believe the new method needs to be exported because the test that I added that exercises the method requires `multiTestContext` which lives in `storage_test`.
</details>
OK, but why do we need two methods at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398)*

**Comment by tamird** [comment]
Right; that's what I mean - I would prefer that we leave the somewhat strange empty reason so that when someone does plumb that message up, it shows up where expected. The first commit here is setting a trap for future-us.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVaZqPsib7HJXFRoYvp:b-nll827)*

**Comment by jordanlewis** [comment]
I changed this to print a static message when the reason would be empty.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/client_raft_test.go, line 668 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaZcxE5oCqpbO8xypM:-KVa_YP55lTJwbTbVvE2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77dff5f77ead8714b4a5fc2f9228120537a6ad31/pkg/storage/client_raft_test.go#L668)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this needs to be `Fatalf`. while you're in there, `expectedErr` should be %s
</details>
Done.

---

*[pkg/storage/store.go, line 2482 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaWL0zbkStjCGt98IH:-KVa_ZB0qZ5WvhnrRgyl:bwyoit4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/store.go#L2482)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> OK, but why do we need two methods at all?
</details>
`HandleSnapshot` needs to have the signature that it does to satisfy the GRPC interface, and `MultiRaft_RaftSnapshotServer` has many methods that we never use - making a fake one is onerous and pointless. That's why I made a narrower interface for use in tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVa_Ei4KS3iAQHlsESN:bv1655q)*

**Comment by tamird** [comment]
Great! Thanks.

---

Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/store.go, line 2482 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaWL0zbkStjCGt98IH:-KVacNWJW8hhzq1DmV_t:bswae3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b8437c8a5cf6809ea0be61828a860f537ac3f6/pkg/storage/store.go#L2482)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> `HandleSnapshot` needs to have the signature that it does to satisfy the GRPC interface, and `MultiRaft_RaftSnapshotServer` has many methods that we never use - making a fake one is onerous and pointless. That's why I made a narrower interface for use in tests.
</details>
Discussed in person: GRPC never generates methods with the name `HandleFoo` - this interface is defined by `RaftMessageHandler` in raft_transport.go as I noted in the first comment in this thread.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVac_-_MuE-B7fQMEpH:b-5fqpeq)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 653 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaucL0ctPlyA4FX_xo:-KVaucL0ctPlyA4FX_xp:b-idgmgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59974366255ed259bf63b501da550b463875565/pkg/storage/client_raft_test.go#L653)):*
> ```Go
> 	defer mtc.Stop()
> 
> 	rng, err := mtc.stores[0].GetReplica(1)
> ```

s/rng/rep/g

---

*[pkg/storage/client_raft_test.go, line 665 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaukn12bY1GUtaJgdV:-KVaukn12bY1GUtaJgdW:b-1t60ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59974366255ed259bf63b501da550b463875565/pkg/storage/client_raft_test.go#L665)):*
> ```Go
> 	// This injects an error into HandleSnapshotStream when we try to send the
> 	// "snapshot accepted" message.
> 	expectedErr := errors.Errorf("")
> ```

optional nit: errors.New

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-:-KVaunEAYuYqCZJKyq-G:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 653 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398#-KVaucL0ctPlyA4FX_xo:-KVazhBFmIvQ9PFNvM9p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59974366255ed259bf63b501da550b463875565/pkg/storage/client_raft_test.go#L653)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/rng/rep/g
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10398)*

**Pull request merged**
