### PR TITLE
build: add check that floss target doesn't depend on ccl

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13170)

### CODE REVIEW

**Comment by tamird** [comment]
This should definitely report the forbidden dependencies themselves.

But also, can this be a go-based test? see buildutil.VerifyNoImports.

As an aside, it's really unfortunately that we have 3 places where we check dependencies.

**Comment by dt** [comment]
thank to grep not being silenced, it currently reports them as it goes, e.g. 
```
checking that FLOSS target does not depend on CCL tree...
github.com/cockroachdb/cockroach/pkg/ccl
github.com/cockroachdb/cockroach/pkg/ccl/buildccl
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl
github.com/cockroachdb/cockroach/pkg/ccl/storageccl
github.com/cockroachdb/cockroach/pkg/ccl/utilccl/intervalccl
found forbidden dependencies on CCL tree from FLOSS target.
```
That said, I'll switch it to `buildutil.VerifyNoImports`

**Comment by dt** [comment]
(switched to buildutil.VerifyNoImports)

**Comment by tamird** [comment]
lgtm

**Pull request merged**
