### PR TITLE
backupccl: unblock table restore of regional by row tables

### LINKED ISSUE #67269: backupccl: support restoring REGIONAL BY ROW tables individually
**Describe the problem**

Today, RESTORE does not support restoring REGIONAL BY ROW tables individually. The main challenge here is that RESTORE does not validate the multi-region column values for each row.

There are no plans to support this in the short-term, but filing for tracking in case there's enough user-demand to warrant implementing this feature.

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, we disallowed table restore of RBR tables.

An RBR table has a hidden `crdb_region` column that contais a
value equal to one of the members of the multiregion enum of the parent
database. When we backup a database containing an RBR table, we will
also backup this MR enum. On restore, when we realize that the RBR
table is dependent on a UDT, we will fetch the MR enum from the backup
and check if it is compatible with the MR enum in the restoring database.
Concretely, we will check that the MR enum in the backup has the same
logical and physical representation of a subset of the enum members on
the restoring clusters' MR enum. This check should be sufficient to
catch rows in an RBR table that might have a region that is not present
in the restoring cluster.

Fixes: #67269

Epic CRDB-10552

Release note (sql change): RESTORE TABLE for a regional by row table into
a multiregion database with the same regions as the backed up database, is
now allowed. It is important to note that by "same" regions we mean the
multi-region enum in the backing up cluster should have the same "logical"
and "physical" representation as the enum in the restoring cluster. From a
users perspective, this means that the regions (enum members) must have been
added in the same relative order on both clusters.

### CODE REVIEW

**Comment by adityamaru** [comment]
Commit 1 is from https://github.com/cockroachdb/cockroach/pull/71161.

**Review by ajstorm — CHANGES_REQUESTED** [review]
Cool to see this work get done.

> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-:-MlLJ6a724b6Nt8BBXND:bcs0979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @stevendanna)

___
*[-- commits, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLJSog4-tTM2NUuqOV):*

Nit: We can remove the double negative by changing this last line to "... now allowed".
___
*[pkg/ccl/backupccl/restore_job.go, line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLP-RF7GWfZhTqz5JP:-MlLP-RF7GWfZhTqz5JQ:b-wwajfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5d82b957d713a4ff239fd5bc6867edd8e91264/pkg/ccl/backupccl/restore_job.go#L293)):*
> ```Go
> }
> 
> func maybeProcessMultiRegionTable(
> ```

Nit: I find this naming a bit confusing, as the table here might not actually be a multi-region table just yet.  What about `processTableForMultiRegion`?
___
*[pkg/ccl/backupccl/restore_job.go, line 318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLJyW92HgXkrmJIg-9:-MlLJyW92HgXkrmJIg-A:b-jlr9ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5d82b957d713a4ff239fd5bc6867edd8e91264/pkg/ccl/backupccl/restore_job.go#L318)):*
> ```Go
> 		if table.GetLocalityConfig() != nil {
> 			return pgerror.Newf(pgcode.FeatureNotSupported,
> 				"cannot write descriptor for multi-region table %s into non-multi-region database %s",
> ```

Nit: If this is restore specific, does it make sense to change this to "cannot restore multi-region table %s..."?
___
*[pkg/ccl/backupccl/targets.go, line 611 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLQA21-XJmxOZNoD8O:-MlLQA21-XJmxOZNoD8P:b-15p5hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5d82b957d713a4ff239fd5bc6867edd8e91264/pkg/ccl/backupccl/targets.go#L611)):*
> ```Go
> 	if !database.IsMultiRegion() && table.GetLocalityConfig() != nil {
> 		return pgerror.Newf(pgcode.FeatureNotSupported,
> 			"cannot restore descriptor for multi-region table %s into non-multi-region database %s",
> ```

I understand the motivation here, but I'm wondering if we need/want to be more nuanced here.  I'd think that the only problem we'd have with restoring MR tables to non-MR databases is if they're RBR.  Could we allow restore of RBT and GLOBAL tables?  We'd have to strip out the LocalityConfig in doing so, but it might be a small easy win.

**Review by stevendanna — APPROVED** [review]
Overall, it looks like a step in the right direction to me. I like the comments and functions you extracted.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-:-MlLZwL629KibqpXy0Ad:baga1yx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[-- commits, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLYqEHBjYD1pwOAJSi):*
Not sure how detailed to get in this release note, but as you explained in standup, the enum's needing to have the same physical representation means that some tables likely still can't be restored even if, from the user's perspective, it looks like all the regions match. I'm assuming that is still the case in this PR.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @dt)

___
*[pkg/ccl/backupccl/targets.go, line 611 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLQA21-XJmxOZNoD8O:-Mljm7k_4WBvaVbGemjS:bs8tz5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5d82b957d713a4ff239fd5bc6867edd8e91264/pkg/ccl/backupccl/targets.go#L611)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I understand the motivation here, but I'm wondering if we need/want to be more nuanced here.  I'd think that the only problem we'd have with restoring MR tables to non-MR databases is if they're RBR.  Could we allow restore of RBT and GLOBAL tables?  We'd have to strip out the LocalityConfig in doing so, but it might be a small easy win.
</blockquote></details>

@ajstorm this sounds like a good idea, just to double-check nil'ing out the LocalityConfig for a RBT/Global Table is adequate to turn them into a non-MR table? I just want to make sure there is no other cleanup required.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @dt, and @otan)

___
*[pkg/ccl/backupccl/targets.go, line 611 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLQA21-XJmxOZNoD8O:-MlliiVy5LcqbCsCDbXt:bob3e6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5d82b957d713a4ff239fd5bc6867edd8e91264/pkg/ccl/backupccl/targets.go#L611)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

@ajstorm this sounds like a good idea, just to double-check nil'ing out the LocalityConfig for a RBT/Global Table is adequate to turn them into a non-MR table? I just want to make sure there is no other cleanup required.
</blockquote></details>

Worth confirming with @otan or @arulajmani, but my understanding is that's correct.  If the database had a `crdb_internal_region` type there would be more work to do, but since this isn't an MR database (and therefore, there's no type), it should just be removing the LocalityConfig.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dt, @otan, and @stevendanna)

___
*[-- commits, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlLYqEHBjYD1pwOAJSi):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Not sure how detailed to get in this release note, but as you explained in standup, the enum's needing to have the same physical representation means that some tables likely still can't be restored even if, from the user's perspective, it looks like all the regions match. I'm assuming that is still the case in this PR.
</blockquote></details>

Yup, that is still the case. Called it out in the release notes.

**Review by ajstorm — CHANGES_REQUESTED** [review]
That approach SGTM.

Was the reversion of the test changes in the last commit amend intentional?  If so, why?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-:-Mlrk6Cs7ju69Kp7k6w9:b-6kdbt3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @dt, @otan, and @stevendanna)

___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-Mlri2e78mXTILWfVuOg):*
Nit: "one of the regions that had been added to the parent database."?
___
*[-- commits, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlriicoDY4r5tyYyXlF):*
Doesn't it mean more than "that the regions must hav been added in the same relative order"?  Doesn't it also require that no other regions were added to the database in between the regions of concern? Additionally, I'd also think it would mean that any regions that precede said regions on the backing up cluster, must have corresponding regions on the restoring cluster.  In all practical terms, I'd think that this means that the regions both match, and were added in the same order, between the backing up database and the restoring database.  While it's possible for the code to handle more elaborate cases, I'd think it would be tricky for customers to rely on getting the ordering right.

**Review by adityamaru — COMMENTED** [review]
I previously had two commits in the PR. The first one was from https://github.com/cockroachdb/cockroach/pull/71161 which has been merged since. Not sure why it shows up as a revert in Reviewable but the test in `backup_test.go` is still there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-:-MlsmPpc9DiKLiEjFUc3:b-yfkvxo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @otan, and @stevendanna)

___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-Mlri2e78mXTILWfVuOg):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: "one of the regions that had been added to the parent database."?
</blockquote></details>

Done.
___
*[-- commits, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MlriicoDY4r5tyYyXlF):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Doesn't it mean more than "that the regions must hav been added in the same relative order"?  Doesn't it also require that no other regions were added to the database in between the regions of concern? Additionally, I'd also think it would mean that any regions that precede said regions on the backing up cluster, must have corresponding regions on the restoring cluster.  In all practical terms, I'd think that this means that the regions both match, and were added in the same order, between the backing up database and the restoring database.  While it's possible for the code to handle more elaborate cases, I'd think it would be tricky for customers to rely on getting the ordering right.
</blockquote></details>

You're right I confused myself. The code for restore checks that all the enum members of the backed-up type should be present in the type in the restoring cluster, and their logical/physical representations should be the same. I've changed the release notes to indicate that the regions must match, and be added in the same order.

**Review by ajstorm — APPROVED** [review]
Thanks for making the changes.

:lgtm: 

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-:-MltbNJ523SUPBfcGdQh:b1duk1a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @dt, @otan, and @stevendanna)

___
*[pkg/ccl/backupccl/restore_job.go, line 318 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71178#-MltZgx1-aZMwtQ_tvjL:-MltZgx1-aZMwtQ_tvjM:brkfapq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf35f790f29b77d1c8d725aed39c396e5180962/pkg/ccl/backupccl/restore_job.go#L318)):*
> ```Go
> 		if table.GetLocalityConfig() != nil {
> 			return pgerror.Newf(pgcode.FeatureNotSupported,
> 				"cannot restore multi-region table %s into non-multi-region database %s",
> ```

Nit: I didn't realize that this code path was used for import as well.  Perhaps we should change this to `cannot restore or create multi-region table %s in non-multi-region database %s`?

**Pull request merged**
