### PR TITLE
logictest: improve progress output

### PR DESCRIPTION
**Pull request by andreimatei**
Logictests would print some progress messages to stdout as they run.
Each file prints when it ends and, while it's running, it prints
messages when statements finish successfully (but only up to once per
2s). This patch adds a second-level timestamp to those messages, in
order to provide more clues in the output of timed out logictest
packages. Otherwise, I'm always left guessing if the package had been
making constant progress until the timeout, or if it got stuck at some
point.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Going to kick this over to @cockroachdb/sql-queries since they're the primary consumers of this format and ultimately need to be on board with the changes.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/logictest/logic.go, line 1283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72468#-MnhYBiA5ji_aFdN0WLz:-MnhYBiA5ji_aFdN0WM-:btvbvpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a015e7ae27a31915f2cf48d377e01291f9312e/pkg/sql/logictest/logic.go#L1283)):*
> ```Go
> func (t *logicTest) outf(format string, args ...interface{}) {
> 	if t.verbose {
> 		finalArgs := make([]interface{}, 1+len(args))
> ```

nit: maybe add a quick comment what we're doing with this `finalArgs` business.

I'm assuming that `log.Infof` below doesn't need to work with `finalArgs` because `log` itself will add a timestamp?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 1283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72468#-MnhYBiA5ji_aFdN0WLz:-Mu2dn8o72QRd-O5uvIi:bhj2ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a015e7ae27a31915f2cf48d377e01291f9312e/pkg/sql/logictest/logic.go#L1283)):*
> nit: maybe add a quick comment what we're doing with this finalArgs business.

please see now

> I'm assuming that log.Infof below doesn't need to work with finalArgs because log itself will add a timestamp?

right

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72468#-:-MuDWefiAe3yQTsIn7Pn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72468#-:-MuM7sX6B9-nZuGKs2Zt:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
