### PR TITLE
kvprober/log/cli: log to a dedicated channel, default sending that channel to a dedicated file

### PR DESCRIPTION
**Pull request by joshimhoff**
https://github.com/cockroachdb/cockroach/issues/61074

**log/cli: add a logging channel dedicated to the kvprober**

This commit adds a logging channel dedicated to the kvprober. By default this
channel will go to a dedicated file, as is done with the pebble log. Why do
this? It is useful to log info on every probe made by kvprober, even when the
probe is successful. This generates a lot of noise if sent to an existing
channel such as HEALTH. A dedicated channel cuts the noise, while still letting
us keep detailed records on all probes made by the kvprober.

Release justification: It is very low risk to add a new channel.
Release note: None.

**kvprober: log to the new kvprober channel**

This commit makes the kvprober log to the channel introduced in a previous
commit for this purpose.

Release justification: Component is behind a private cluster setting that
defaults to off.

Release note: None.

### CODE REVIEW

**Review by joshimhoff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff)

___
*[pkg/kv/kvprober/kvprober.go, line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69615#-MiNxqey6q1EnNhR6K5c:-MiNxqey6q1EnNhR6K5d:bgoveqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fced395e124d8aeb1917fcf801cbdd53436c1338/pkg/kv/kvprober/kvprober.go#L256)):*
> ```Go
> 	if err != nil {
> 		// TODO(josh): Write structured events with log.Structured.
> 		log.Kvprober.Errorf(ctx, "kv.Get(%s), r=%v failed with: %v", step.Key, step.RangeID, err)
> ```

A Q for reviewers: Perhaps we should log errors to both the HEALTH & KVPROBER channels, as an error is a signal of poor cluster health. Or is that a misuse of `pkg/util/log`?

**Comment by knz** [comment]
I'm not exactly sure why you used a separate channel? What was wrong with using HEALTH?

**Comment by knz** [comment]
Specifically, what is this "noise" and why is it a problem?

**Comment by joshimhoff** [comment]
We log every successful probe. We do one read probe every 5s per node in CC today. Soon we will do one read probe every 1s per node & one write probe every 5s per node in CC, or something like that. The log lines associated with successful probes are a bit much to include in the main CRDB log IMO. But I do think we want an exhaustive log somewhere, as successful probe doesn't indicate healthy if latencies are very high. A separate channel + the changes made in `cli` here get us a dedicated file for `kvprober` logs, which I think is nice, but I could also see logging `kvprober` errors only to the `HEALTH` channel, assuming it is not a mis-use of the channel construct to log a log line to two places when it applies to both categories.

Wdyt about this, Raphael?

**Comment by knz** [comment]
> The log lines associated with successful probes are a bit much to include in the main CRDB log IMO, which is where the HEALTH channel goes by default

This is a problem. IMHO we definitely want to move HEALTH somewhere else.

> We do one read probe every 5s per node in CC today. Soon we will do one read probe every 1s per node & one write probe every 5s per node in CC, or something like that.

HEALTH doesn't need to retain 100MB worth of data. We can lower the retention window for it to just 10MB. Then the frequency doesn't matter, doesn't it?

**Comment by joshimhoff** [comment]
Aside: I am happy to have written this PR & be having this convo as I now I have a mental model of the logging system, something I lacked previously.

> This is a problem. IMHO we definitely want to move HEALTH somewhere else.

You don't think log lines sent to the `HEALTH` channel should go to the main CRDB log? Can you say why? If not the main CRDB log, where would log lines sent to `HEALTH` channel go by default? A dedicated file just for the `HEALTH` channel?

**Comment by knz** [comment]
> where would log lines sent to HEALTH channel go by default? A dedicated file just for the HEALTH channel?

IMHO, they should go to a circular buffer in some CC monitoring service, and not stored.

We could perhaps retain the last 3 hours (~10MB) on each node, but again I'm not convinced of the utility.

**Comment by knz** [comment]
@joshimhoff I'll send a separate PR for the filtering and redirection of HEALTH, so in the meantime I think you can simplify this PR to reuse the health channel instead of defining a new channel.

**Comment by joshimhoff** [comment]
> I'll send a separate PR for the filtering and redirection of HEALTH, so in the meantime I think you can simplify this PR to reuse the health channel instead of defining a new channel.

Ack awesome. Without this PR, `kvprober` already writes to `HEALTH`: https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/kvprober.go#L315. So sounds like no work needed on the `kvprober` side, unless I am missing something.

**Comment by knz** [comment]
Superseded by #70388.

**Pull request closed without merging**
