### PR TITLE
coldata: remove Slice method from Bytes

### LINKED ISSUE #42670: colexec: a problem with modifying a slice of flat bytes
There is another problem with flat bytes implementation that was exposed by failed `postgresjoin` logic test when I ran it with `local-vec` config:
when we’re `Set`ting on a `Slice` of flat bytes, `maxSetIndex` field of the “parent” will not get updated (also the length of “parent” `b.data` remains unchanged). The problem occurs as follows:
```
b1 := NewBytes(10)
b2 := b1.Slice(0, 5)
b2.Set(0, "a")
b2.Set(1, "b")
b2.Set(2, "c")
// At this point we have:
// b1.maxSetIndex = 0
// len(b1.data) == 0
// b1.offsets == [0, 1, 2, 3] - correct
// Some time later we do this:
b1.maybeBackfillOffsets(5)
// and it will override b1.offsets = [0, 1, 1, 1, 1, 1]
```
I see a couple of solutions:
 - share `maxSetIndex` between all `Slice`s of a single `Bytes` object. It would be accessed atomically. This might be tricky to get correct and could have some unforeseen effects.
- remove `Slice` method entirely from `Bytes` interface. At the same time, we don’t want to lose bounds check elimination for other types, so this would require special-casing for `Bytes` type in many places in the templates
 - implement `Slice` method using `AppendSlice` (it will be something like
```
func (b *Bytes) Slice(start, end int) *Bytes) {
  res := NewBytes(end-start)
  return res.AppendSlice(b, 0 /* destIdx */, start, end)
}
```
The unfortunate thing with the last approach is that it will involve actually copying the data which goes against the expectation that “slicing is extremely fast.”

### PR DESCRIPTION
**Pull request by yuzefovich**
Slice method has been very tricky to get right, so we decided to remove
it from flat bytes implementation. Instead, we're introducing 'Window'
method that allows for specifying a "window" into the Bytes, but the
returned object is not allowed to be modified. In a similar vein,
Vec.Slice has been renamed to Vec.Window.

Fixes: #42670.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm:  In the first commit message: `s/now/not`

> Reviewed 23 of 23 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42664#-:-Lv5NSgFBJAJUZk4IRQo:b-4dv7hn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42664#-Lv5RWAE9lyzBI-wWufL:-Lv5RWAE9lyzBI-wWufM:b-4lijat) ([raw file](https://github.com/cockroachdb/cockroach/blob/6edfe1cfb8902be2fa5f7ca49329d7ae2bad3430/pkg/col/coldata/bytes.go#L76)):*
> ```Go
> 	// need to override that). I think it is ok, though, because although the
> 	// function modifies the "window" Bytes, it maintains the invariant that we
> 	// need to have. Thoughts?
> ```

I think it's fine to allow this on a window.
___
*[pkg/sql/logictest/logic.go, line 538 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42664#-Lv5S6Xa4IC8A0bkdNYY:-Lv5S6Xa4IC8A0bkdNYZ:bugt204) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b701ab17bbf75be3443fa77d89815c18f7c54f1/pkg/sql/logictest/logic.go#L538)):*
> ```Go
> 		"local",
> 		"local-vec-off",
> 		"local-vec",
> ```

What's the change to the run time of the logictests?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42664)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/col/coldata/bytes.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42664#-Lv5RWAE9lyzBI-wWufL:-Lv6Zxyn2bAdwXfPyLnz:b9ldnc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6edfe1cfb8902be2fa5f7ca49329d7ae2bad3430/pkg/col/coldata/bytes.go#L76)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it's fine to allow this on a window.
</blockquote></details>

Cool, thanks.
___
*[pkg/sql/logictest/logic.go, line 538 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42664#-Lv5S6Xa4IC8A0bkdNYY:-Lv6_Cii5EB7UEsn2Mvf:bi2kk09) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b701ab17bbf75be3443fa77d89815c18f7c54f1/pkg/sql/logictest/logic.go#L538)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What's the change to the run time of the logictests?
</blockquote></details>

I don't know - in theory, all the configs should run in parallel, so there shouldn't be any change, right?

**Comment by yuzefovich** [comment]
When I get back to this, I should work on adding types to be displayed with `EXPLAIN (VEC)`.

**Comment by yuzefovich** [comment]
I found another issue (#43269) that prevents us from adding `vec` configs to the default ones for the logic tests, so I removed the second commit from here.

TFTR!

bors r+

**Comment by yuzefovich** [comment]
Hm, one more try.

bors r+

**Pull request merged**
