### PR TITLE
sql, util: update CapturedIndexUsageStats payload

### LINKED ISSUE #85411: Collect MVCC statistics as telemetry data
This issue tracks collecting MVCC statistics in our cloud telemetry logging channel and pipeline as described [here](https://docs.google.com/document/d/1ZJ1IJaRGM4Ivo7sutplDjTJenzm1qaU96iOvfKkMbXs/edit?disco=AAAAb5lqz54). 

Initially, this will enable us to understand which workloads are suffering from performance issues due to MVCC garbage data.

### PR DESCRIPTION
**Pull request by Santamaura**
This PR adds the following fields to CapturedIndexUsageStats in order to be logged to the telemetry channel:
- is_visible
- is_sharded
- shard_bucket_count
- drop_time
- mod_time
- mod_time_logical
- audit_mode
- locality
- mvcc_stats

mvcc_stats defines mvcc stats related to each table name retrieved in the
CapturedIndexUsageStats query. The stats are the ones defined in storage/enginepb/mvcc.proto.

Fixes: #85411, #92170

Release note: None

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Very nice!

I might not be the best one on SQL Obs to give a full review, but I do have a few general comments/questions:

- I find it a bit confusing that we have table-specific information in an index usage log. Should this info live somewhere else?
- Given the above, should we gate the table-specific fields behind a cluster setting or just include all of them by default?
- Should the `TestCaptureMVCCStats` unit test check for more than the stats being empty? Should we have tests for the new fields?

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-:-NQQPZHdBGBfLv8w11Nw:b-gimtu5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQScpJ6pul7oBDmmGX:-NQQScpJ6pul7oBDmmGY:bsrdah8) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/util/log/eventpb/telemetry.proto#L255)):*
> ```protobuf
>   float mod_time_logical = 19 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];
> 
>   // AuditMode indicates if the table has audit logging set.
> ```

All of this information is at the table level. Should we update the descriptions/names to reflect that?



_Code quote:_
```protobuf
  // DropTime is the timestamp at which the table was dropped.
  string drop_time = 17 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];

  // ModTime is the timestamp at which the table was last modified.
  string mod_time = 18 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];

  // ModTimeLogical is the unix nanos at which the table was last modified.
  float mod_time_logical = 19 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];

  // AuditMode indicates if the table has audit logging set.
  string audit_mode = 20 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];

  // Locality is the location associated with the table.
  string locality = 21 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];

  // MVCCStats is a message containing replica stats related to a given table name.
  cockroach.storage.enginepb.MVCCStats mvcc_stats = 22 [(gogoproto.customname) = "MVCCStats", (gogoproto.jsontag) = ",omitempty"];
```

**Review by THardy98 — CHANGES_REQUESTED** [review]
Left some small nits but I'm not sure about the approach to get MVCC stats via ranges from `crdb_internal.ranges_no_leases`.
With range coalescing, a range can overlap but may not be fully encompassed by a table span. If we get all the ranges that overlap the table from `ranges_no_leases`, we're not accounting that the range may only partially overlap the table span, we include the MVCC stats for the range in its entirety.

Recently @zachlite refactored the `SpanStats` endpoint exactly to account for this, that would be a more accurate approach.

That being said, I'm not sure if this margin of error is acceptable @kevin-v-ngo .

> Reviewed 7 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-:-NQQTAnjCkZ6CtrRI9Mj:b6bfrkh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQSkL-3XYkaCWWjZ8x:-NQQSkL-3XYkaCWWjZ8y:bqrnip4) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/util/log/eventpb/telemetry.proto#L244)):*
> ```protobuf
> 
>   // ShardBucketCount indicates the number of shards the index is divided into.
>   int32 shard_bucket_count = 16 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];
> ```

Typically I don't think number values have redaction tags.
___
*[`pkg/util/log/eventpb/telemetry.proto` line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQSrIy-L3s88EgXFWz:-NQQSrIy-L3s88EgXFX-:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/util/log/eventpb/telemetry.proto#L253)):*
> ```protobuf
> 
>   // ModTimeLogical is the unix nanos at which the table was last modified.
>   float mod_time_logical = 19 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];
> ```

Ditto.
___
*[`pkg/sql/scheduledlogging/captured_index_usage_stats_test.go` line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQT3kVBc_Kn3k_Sfdn:-NQQT3kVBc_Kn3k_Sfdo:bwhaekl) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/sql/scheduledlogging/captured_index_usage_stats_test.go#L288)):*
> ```Go
> 	stats, err := captureMVCCStats(context.Background(), ie, "test", "test.test_table")
> 	require.NoError(t, err)
> 	require.True(t, (&enginepb.MVCCStats{}) != stats)
> ```

Is the test just to ensure that stats values are non-empty?

**Review by Santamaura — COMMENTED** [review]
> I find it a bit confusing that we have table-specific information in an index usage log. Should this info live somewhere else?

From my conversations with @kevin-v-ngo my understanding was that we wanted to bundle this with index usage stats as it would be convenient in snowflake to parse the data.

> Given the above, should we gate the table-specific fields behind a cluster setting or just include all of them by default?

We could but I'll let @kevin-v-ngo decide whether we want this.

> Should the TestCaptureMVCCStats unit test check for more than the stats being empty? Should we have tests for the new fields?

After some refactoring to use the `SpanStats` endpoint I decided to remove the test and just update the main test to check if some of the non empty fields were recorded.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-:-NQaC_A77uNICoYXWLvS:bbod75i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @koorosh, @THardy98, and @zachlite)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQSkL-3XYkaCWWjZ8x:-NQaDXSO8KS74Dyghb5J:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/util/log/eventpb/telemetry.proto#L244)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Typically I don't think number values have redaction tags.
</blockquote></details>

Removed.
___
*[`pkg/util/log/eventpb/telemetry.proto` line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQSrIy-L3s88EgXFWz:-NQaDZfI4ZAwBEG8FCfq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/util/log/eventpb/telemetry.proto#L253)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`pkg/util/log/eventpb/telemetry.proto` line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQScpJ6pul7oBDmmGX:-NQaD_R_2aKqv_vYIrnl:bohqzsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/util/log/eventpb/telemetry.proto#L255)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

All of this information is at the table level. Should we update the descriptions/names to reflect that?
</blockquote></details>

Agreed, done.
___
*[`pkg/sql/scheduledlogging/captured_index_usage_stats_test.go` line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-NQQT3kVBc_Kn3k_Sfdn:-NQaDcK_51tw91mvNACJ:b-1z2ke7) ([raw file](https://github.com/cockroachdb/cockroach/blob/daab34077dc77a82456c4de5f6417b1fc2695f78/pkg/sql/scheduledlogging/captured_index_usage_stats_test.go#L288)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Is the test just to ensure that stats values are non-empty?
</blockquote></details>

Yes, though it was removed and instead added onto the main test to check that we record data for some of the fields that can't be empty.

**Review by Santamaura — COMMENTED** [review]
> Left some small nits but I'm not sure about the approach to get MVCC stats via ranges from crdb_internal.ranges_no_leases.
With range coalescing, a range can overlap but may not be fully encompassed by a table span. If we get all the ranges that overlap the table from ranges_no_leases, we're not accounting that the range may only partially overlap the table span, we include the MVCC stats for the range in its entirety.

Updated so that we use `SpanStats` endpoint.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-:-NQaDy8N2csQKYrpnxBR:b8zhy8x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @koorosh, @THardy98, and @zachlite)

**Review by THardy98 — COMMENTED** [review]
I've recently been extending the `SpanStats` endpoint to account for multiple spans (https://github.com/cockroachdb/cockroach/pull/98490). Currently it will issue a node fan out *per* span which we've seen scales poorly with large schemas. Would it be possible to hold off on this until that gets in? @kevin-v-ngo 

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98172#-:-NQfLGNE2_nFGVbvbcSu:b-o8o33n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @koorosh, and @zachlite)

**Comment by Santamaura** [comment]
I realized we could have the mvcc stats based on the table id and index id so now it feels more natural to be in this payload.

**Comment by kevin-v-ngo** [comment]
Hi @Santamaura, @maryliag, and @THardy98. What's left for this PR? Would be great to capture this telemetry in 23.1.

**Comment by Santamaura** [comment]
> Hi @Santamaura, @maryliag, and @THardy98. What's left for this PR? Would be great to capture this telemetry in 23.1.

I might not be the most up to date with this but it should be good unless the `SpanStats` endpoint changes (or there were further code comments)

**Pull request closed without merging**
