### PR TITLE
sql: add virtual tables to expose remote DistSQL flows

### PR DESCRIPTION
**Pull request by yuzefovich**
**server: minor cleanup around listing of contention events**

This commit renames some things related to `ListContentionEvents` RPC to
something like `ListActivity*` in order to be reused by the follow-up
commit that will introduce `ListDistSQLFlows` RPC. Also, a couple of
redundant method implementations are removed.

Release note: None

**sql: add virtual tables to expose remote DistSQL flows**

This commit introduces two virtual tables
`crdb_internal.(node|cluster)_distsql_flows` that expose the information
about the DistSQL flows that have gone through the flow scheduler.
Notably, this information will not include any "local" flows (those
running on the gateway node for the query) because they don't go through
the flow scheduler.

The goal of these virtual tables is to provide more observability into
the state of the distributed query execution, especially when things are
shutdown in an ungraceful manner. Previously, the only way to see the
queued up or running flows would be via metrics.

This information is exposed via another couple of methods that are added
onto the status server, and it is required that the user is either
a superuser or has VIEWACTIVITY permissions.

Release note (sql change): a couple of virtual tables
`crdb_internal.(node|cluster)_distsql_flows` are added that expose the
information about the flows of the DistSQL execution scheduled on remote
nodes. These tables don't include any information about the
non-distributed queries nor about local flows (from the perspective of
the gateway node of the query).

### CODE REVIEW

**Comment by yuzefovich** [comment]
First two commits are a part of a separate PR.

**Comment by yuzefovich** [comment]
Thoughts about backporting this to 21.1? Seems like relatively low risk and probably beneficial enough.

I guess an open question is whether we want to backport #65073 too - I think Jordan and myself were thinking that it would be good to, after some baking period on master. I think the same logic can apply to this PR, and that's why I'm basing it on top of #65073.

**Comment by yuzefovich** [comment]
Extracted one commit into a separate PR and moved a couple of things between other commits.

**Comment by yuzefovich** [comment]
Friendly ping @RaduBerinde @mgartner

**Review by mgartner — APPROVED** [review]
This is cool! :lgtm: 

Probably worth a look from someone else more familiar with this code than me.

> Reviewed 7 of 7 files at r1, 42 of 42 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-:-MbbjcR_EElqFEUhHnxb:b-7z2z7b)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by yuzefovich** [comment]
TFTR!

I think @RaduBerinde is the most familiar with the relevant code on our team, but maybe @rytaft could give this a look too.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: Cool! I have a few comments but looks good overall, this will be useful!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-:-MbmWa3J5o8_qf4m7M1W:byxbwym)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[pkg/roachpb/api.proto, line 2254 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-MbmVz8LDm4PNKm-JZRB:-MbmVz8LDm4PNKm-JZRC:bkyfk86) ([raw file](https://github.com/cockroachdb/cockroach/blob/343a208a29682b53ee2da8e9ab341777ff1378ef/pkg/roachpb/api.proto#L2254)):*
> ```protobuf
> // NodeIDWithTimestamp is a message associating a NodeID with some arbitrary
> // timestamp (in the UTC timezone).
> message NodeIDWithTimestamp {
> ```

Any reason why this isn't defined inside `message DistSQLRemoteFlow`?
This could also include a "status" (`running` / `queued`) instead of dealing with multiple lists. This would also make it easier to add a new status later (e.g. `finished`).
___
*[pkg/server/status.go, line 2283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-MbmUjr174qkJZjeQEeE:-MbmUjr174qkJZjeQEeF:bxi941r) ([raw file](https://github.com/cockroachdb/cockroach/blob/343a208a29682b53ee2da8e9ab341777ff1378ef/pkg/server/status.go#L2283)):*
> ```Go
> // while adhering to the same contract.
> //
> // It is assumed that for a particular FlowID a single NodeID can appear in at
> ```

[nit] this sentence is unclear
___
*[pkg/server/serverpb/status.proto, line 698 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-MbmVftP1V48Dd5jUlFe:-MbmVftP1V48Dd5jUlFf:bgtkea) ([raw file](https://github.com/cockroachdb/cockroach/blob/343a208a29682b53ee2da8e9ab341777ff1378ef/pkg/server/serverpb/status.proto#L698)):*
> ```protobuf
> 
>   // RunningOn contains the nodes on which the flow is running, in a sorted
>   // order without duplicates. The intersection with QueuedOn is an empty set.
> ```

[nit] "intersection" is a bit ambiguous since we're talking about `(node_id, timestamp)` pairs. Saying that a node cannot appear in both lists would be more clear.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-:-MbnEW-A9OFSJWlrpDaT:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/server/status.go, line 2283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-MbmUjr174qkJZjeQEeE:-MbnDNCBAsJ3IPChToEJ:b-qj92pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/343a208a29682b53ee2da8e9ab341777ff1378ef/pkg/server/status.go#L2283)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this sentence is unclear
</blockquote></details>

Reworded.
___
*[pkg/server/serverpb/status.proto, line 698 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-MbmVftP1V48Dd5jUlFe:-MbnDQP548HbXoLp3wjW:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/343a208a29682b53ee2da8e9ab341777ff1378ef/pkg/server/serverpb/status.proto#L698)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "intersection" is a bit ambiguous since we're talking about `(node_id, timestamp)` pairs. Saying that a node cannot appear in both lists would be more clear.
</blockquote></details>

Refactored.
___
*[pkg/roachpb/api.proto, line 2254 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-MbmVz8LDm4PNKm-JZRB:-Mbn5a6I1fSTTiDLpbHR:b-7r9nud) ([raw file](https://github.com/cockroachdb/cockroach/blob/343a208a29682b53ee2da8e9ab341777ff1378ef/pkg/roachpb/api.proto#L2254)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Any reason why this isn't defined inside `message DistSQLRemoteFlow`?
This could also include a "status" (`running` / `queued`) instead of dealing with multiple lists. This would also make it easier to add a new status later (e.g. `finished`).
</blockquote></details>

Good point, refactored.

I believe this stuff cannot easily live in `serverpb` package due to dependency on `sql` (that's why I originally added `NodeIDWithTimestamp` into `roachpb`), so I moved the definition into `execinfrapb` package instead. I also included the status enum to have a single list of flows.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65727)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/roachpb/api.proto, line 2254 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65727#-MbmVz8LDm4PNKm-JZRB:-MbnG_hf3QdDqWVvJ-qt:b2yj58s) ([raw file](https://github.com/cockroachdb/cockroach/blob/343a208a29682b53ee2da8e9ab341777ff1378ef/pkg/roachpb/api.proto#L2254)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point, refactored.

I believe this stuff cannot easily live in `serverpb` package due to dependency on `sql` (that's why I originally added `NodeIDWithTimestamp` into `roachpb`), so I moved the definition into `execinfrapb` package instead. I also included the status enum to have a single list of flows.
</blockquote></details>

Hm, I don't think that there is a dependency between `serverpb` and `sql`, so I moved the proto definition back.

**Comment by yuzefovich** [comment]
Hm, looks like an unrelated flake.

bors r+

**Pull request merged**
