### PR TITLE
roachtest: convert secondary-index-multi-version to version upgrade f…

### LINKED ISSUE #49670: roachtest: secondary-index-multi-version failed
[(roachtest).secondary-index-multi-version failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1973913&tab=buildLog) on [master@fe74c9b3534ef364f7bf9410bb84ed2034e1624b](https://github.com/cockroachdb/cockroach/commits/fe74c9b3534ef364f7bf9410bb84ed2034e1624b):

```
		  |   | * 
		  |   | * - Your cluster is open for any client that can access <all your IP addresses>.
		  |   | * - Any user, even root, can log in without providing a password.
		  |   | * - Any user, connecting as root, can read or write any data in your cluster.
		  |   | * - There is no network encryption nor authentication, and thus no confidentiality.
		  |   | * 
		  |   | * Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v20.2/secure-a-cluster.html
		  |   | *
		  |   | *
		  |   | * WARNING: running 'cockroach start' without --join is deprecated.
		  |   | * Consider using 'cockroach start-single-node' or 'cockroach init' instead.
		  |   | *
		  |   | *
		  |   | * ERROR: ERROR: cockroach server exited with error: store <no-attributes>=/mnt/data1/cockroach, last used with cockroach version v19.2, is too old for running version v20.1-5 (which requires data from v20.1 or later)
		  |   | *
		  |   | ERROR: cockroach server exited with error: store <no-attributes>=/mnt/data1/cockroach, last used with cockroach version v19.2, is too old for running version v20.1-5 (which requires data from v20.1 or later)
		  |   | Failed running "start"
		  |   | E200528 10:05:53.902845 1 cli/error.go:374  ERROR: exit status 1
		  |   | ERROR: exit status 1
		  |   | Failed running "start"
		  | Wraps: (4) exit status 1
		  | Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *errutil.withMessage (4) *exec.ExitError: 
		  | I200528 10:05:53.924147 1 cluster_synced.go:1749  command failed
		Wraps: (2) exit status 1
		Error types: (1) *main.withCommandDetails (2) *exec.ExitError

	cluster.go:1512,context.go:135,cluster.go:1501,test_runner.go:825: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1973913-1590656638-21-n3cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 6883
		2: 6911
		1: dead
		Error: UNCLASSIFIED_PROBLEM: 1: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  | main.glob..func13
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1129
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:272
		  | github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:766
		  | github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852
		  | github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1799
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:203
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (3) 1: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errors.errorString

```

<details><summary>More</summary><p>

Artifacts: [/secondary-index-multi-version](https://teamcity.cockroachdb.com/viewLog.html?buildId=1973913&tab=artifacts#/secondary-index-multi-version)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asecondary-index-multi-version.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by rohany**
…ramework

Fixes #49670.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
The version upgrade framework was a pleasure to use! Nice work.

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49878)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany, @spaskob, and @tbg)

___
*[pkg/cmd/roachtest/secondary_indexes.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49878#-M9-wokoAbQ5lNdYDmFg:-M9-wokoAbQ5lNdYDmFh:beesyga) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a967c3d826aa5ffe8b3954d930589634cc6c2f5/pkg/cmd/roachtest/secondary_indexes.go#L134)):*
> ```
> registerSecondaryIndexesMultiVersionCluster
> ```
can you add prefix "schemachange/" in front of the. name as we do for all schema change roachtests.
nit: we have used "mixed-versions" in naming other mixed version node tests.

**Comment by rohany** [comment]
This roachtest isn't really a schema change though --it just checks that some operations on an index are backwards compatible.

**Comment by spaskob** [comment]
true but you set schema team as the owner. I don't feel strongly about this
but it may be nice to file it in a particular category. I'd check in with
Tobi.

**Comment by tbg** [comment]
We don't have good precedent on how tests should be named, but I think a `schemachange` prefix feels right here. (Ultimately, if Schema owns it they get to name it ;-) )

I skimmed the PR, looks good, glad this framework is working out for you!

**Review by tbg — APPROVED** [review]

**Comment by rohany** [comment]
Done, TFTRs!

bors r+

**Pull request merged**
