### PR TITLE
insights: add txn start and end time to insights experience

### PR DESCRIPTION
**Pull request by xinhaoz**
## Commit 1
This commit adds the following columns to
`crdb_internal.{node,cluster}_execution_insights`

- txn_start_time
- txn_end_time

Release note: None

## Commit 2
Part of: https://github.com/cockroachdb/cockroach/issues/90393

This commit adds the following fields to the txn insights
pages, note they are only available when the insight is not
from the txn contention events query. In a future PR, we will
remove the requirement to check for insights usign the txn
contention query, and this information will be available for
all txn insights:
- txn start
- txn end
- time elapsed

Release note (ui change): New fields in txn insight
pages:
- Start time: txn start time
- End time: txn end time
- Elapsed time: execution duration of the txn

image

### CODE REVIEW

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93222#-:-NJCOZJX9sLdN_BHvwKP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by matthewtodd** [comment]
I think you can fix most of the build failures with

```
./dev testlogic --files create_statements --rewrite
```

And for the rest, maybe it's something about the test fixtures?

```
FAIL src/insights/utils.spec.ts (89.426 s)
  ● test workload insights utils › mergeTxnInsightDetails › should merge objects when both are present

    TypeError: Cannot read properties of undefined (reading 'unix')

      395 |
      396 |     const appsFromStmts = getAppsFromStatementInsights(
    > 397 |       stmts,
          |             ^
      398 |       INTERNAL_APP_PREFIX,
      399 |     );
      400 |     expect(appsFromStmts.length).toEqual(appNames.length + 1);

      at testMergedAgainstContentionFields (src/insights/utils.spec.ts:397:37)
      at Object.<anonymous> (src/insights/utils.spec.ts:412:13)

  ● test workload insights utils › mergeTxnInsightDetails › should return details when txn insights from stmts aren't present

    TypeError: Cannot read properties of null (reading 'startTime')

      292 |     statementInsights?.forEach(stmt => {
      293 |       if (!stmt.insights?.length) return;
    > 294 |       stmtInsights.push({ ...txnInfo, ...stmt, query: stmt.query });
          |                                        ^
      295 |     });
      296 |   });
      297 |   return stmtInsights;

      at Object.mergeTxnInsightDetails (src/insights/utils.ts:294:40)
      at Object.<anonymous> (src/insights/utils.spec.ts:426:36)
```

**Review by maryliag — COMMENTED** [review]
The first card is getting long compared to the second, what if we move a few to the second column? wdyt @dongniwang ?

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93222#-:-NJjxk_253xu00sKpRph:bji7198)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by kevin-v-ngo** [comment]
> 

We should update "Application" to "Application Name" so it's consistent with the Application Name field and filter on our other pages (e.g., SQL Activity). I don't think we have "Retry reason" yet but we'd track it as part of the isolation conflict (40001 error) issue.

**Pull request closed without merging**
