### PR TITLE
opt: pass hash join equality columns and key hints from execbuilder

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: move join condition helpers to memo

Move the helpers to extract join equality columns and remaining
filters into `memo`.

Release note: None

#### opt: pass equality columns to factory in execbuilder

We are currently relying on code from the heuristic planner to
determine equality columns from a hash join. Fix this by passing the
equality columns from the optimizer.

There is a minor difference in handling in that the optimizer does not
allow the same column to be part of multiple equalities; we can
relax that in the future if necessary.

Release note: None

#### opt: pass down key hints for hash join

We pass down two flags indicating if the equality columns on each side
form a key on the input for that side. These hints can be used to
optimize execution (the initial use case is for the columnar execution
prototype, but it could be useful even for the current hash joiner).

Release note: None

### CODE REVIEW

**Review by changangela — COMMENTED** [review]
This looks great, thanks for adding this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-:-LRChh_d6HWnk_5MkPSf:ben1dfe)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/extract.go, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRChcen7L0MdbaKBdw-:-LRChcen7L0MdbaKBdw0:bx8i11s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a088ad480b9656baf7fedce330dd7981f99c9140/pkg/sql/opt/memo/extract.go#L151)):*
> ```Go
> 			continue
> 		}
> 		// Don't allow any column to show up twice.
> ```

Why do we need this constraint?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32258)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/extract.go, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRChcen7L0MdbaKBdw-:-LRD6frn58xBQEwvJH7m:bufujx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a088ad480b9656baf7fedce330dd7981f99c9140/pkg/sql/opt/memo/extract.go#L151)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Why do we need this constraint?
</blockquote></details>

It just made things easier to reason about. I don't think it's strictly necessary (hence the TODO) but there might be some consequences (e.g. for lookup joins, the code would need to be audited).

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 6 of 6 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-:-LRDZeFV-jP44reM8t9M:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt_exec_factory.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDWSy18Q0PiDDBSH33:-LRDWSy18Q0PiDDBSH34:b-axc5q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e7122ba5353e47cc2fac92eedaa4dbddbfd59a/pkg/sql/opt_exec_factory.go#L273)):*
> ```Go
> 	}
> 
> 	numEqCols := len(leftEqCols)
> ```

Is there a specific reason you're using one slice instead of two? Just to minimize allocations? Either way, I think this deserves a comment.
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDYR6n1iJKFpOp-4P7:-LRDYR6n1iJKFpOp-4P8:br7qcqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e7122ba5353e47cc2fac92eedaa4dbddbfd59a/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L202)):*
> ```
>            │              type         inner                                ·                                         ·
>            │              equality     (title) = (title)                    ·                                         ·
>            │              pred         (book = title) AND (shelf != shelf)  ·                                         ·
> ```

Did this plan get worse? If so, why?
___
*[pkg/sql/opt/memo/extract.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDUsyS1KNEtD5xgPcZ:-LRDUsyS1KNEtD5xgPc_:b-fff1dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed7067e87d48d1cb5804f77533245eaa0977adb/pkg/sql/opt/memo/extract.go#L214)):*
> ```Go
> 		if ok {
> 			a, b := leftVar.Col, rightVar.Col
> 			for i := range leftEq {
> ```

duplicate variable `i` is shadowing outer variable
___
*[pkg/sql/opt/memo/extract.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDTqg3ByZZT0zLaEwJ:-LRDTqg3ByZZT0zLaEwK:bzw3p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed7067e87d48d1cb5804f77533245eaa0977adb/pkg/sql/opt/memo/extract.go#L218)):*
> ```Go
> 					(a == rightEq[i] && b == leftEq[i]) {
> 					// Skip this condition.
> 					continue MAINLOOP
> ```

[nit] I'm always wary of this sort of GOTO pattern... but up to you if you want to change it or not

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32258)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt_exec_factory.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDWSy18Q0PiDDBSH33:-LRD_CuOE0eZu1gg8A9S:b-wsac73) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e7122ba5353e47cc2fac92eedaa4dbddbfd59a/pkg/sql/opt_exec_factory.go#L273)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is there a specific reason you're using one slice instead of two? Just to minimize allocations? Either way, I think this deserves a comment.
</blockquote></details>

Yeah seemed like an easy enough way to save a couple of allocations. Added a comment.
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDYR6n1iJKFpOp-4P7:-LRD_0RRCU52DO9aR17G:b-3kexap) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e7122ba5353e47cc2fac92eedaa4dbddbfd59a/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L202)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Did this plan get worse? If so, why?
</blockquote></details>

I mentioned in the description, the optimizer code doesn't allow duplicate columns (`title`). There's a TODO to relax that.
___
*[pkg/sql/opt/memo/extract.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDUsyS1KNEtD5xgPcZ:-LRDa-g8-BBHJ1Y9bgYE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed7067e87d48d1cb5804f77533245eaa0977adb/pkg/sql/opt/memo/extract.go#L214)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

duplicate variable `i` is shadowing outer variable
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDTqg3ByZZT0zLaEwJ:-LRDa09Y2Q8RjNtkct9r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed7067e87d48d1cb5804f77533245eaa0977adb/pkg/sql/opt/memo/extract.go#L218)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I'm always wary of this sort of GOTO pattern... but up to you if you want to change it or not
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 13 files at r4, 1 of 6 files at r5, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32258)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32258#-LRDYR6n1iJKFpOp-4P7:-LRDnFaIAL82uAlJZXv4:b5vjmdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e7122ba5353e47cc2fac92eedaa4dbddbfd59a/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I mentioned in the description, the optimizer code doesn't allow duplicate columns (`title`). There's a TODO to relax that.
</blockquote></details>

Got it - thanks!

**Pull request merged**
