### PR TITLE
sql, build: fix the links to documentation

### PR DESCRIPTION
**Pull request by knz**
CockroachDB side of the fix to https://github.com/cockroachdb/docs/issues/1822.

### CODE REVIEW

**Comment by knz** [comment]
This will need https://github.com/cockroachdb/docs/pull/1869 to merge before the new URLs can be checked in.

**Comment by benesch** [comment]
This is awesome, @knz!

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Makefile, line 163 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-Ksj-8nZL6_xHmGxeXxQ:-Ksj-8nZL6_xHmGxeXxR:be2n43m) ([raw file](https://github.com/cockroachdb/cockroach/blob/443f1d50d55e0d918f4eb73f6a139554865959fd/Makefile#L163)):*
> ```Makefile
> 
> # The build.utcTime format must remain in sync with TimeFormat in pkg/build/info.go.
> $(COCKROACH) build buildoss go-install: override LINKFLAGS += $(VERLINKFLAGS)
> ```

why not just make this recipe apply to `test` too?

---

*[Makefile, line 370 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-Ksj1CsY426dlqOOpJR7:-Ksj1CsY426dlqOOpJR8:b-h1vky8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0783fa4e2f3ec7b25e59cc8ebd9f4638209f049a/Makefile#L370)):*
> ```Makefile
> 
> .buildinfo/basebranch: | .buildinfo
> 	@git describe --tags |tr -d \\n > $@
> ```

Avoid including the junk that specifies the distance from tag?

```
git describe --tags --abbrev=0
```

---

*[pkg/build/info.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-Ksj0f2XLpWxDQ22eD_e:-Ksj0f2XLpWxDQ22eD_f:b334nnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0783fa4e2f3ec7b25e59cc8ebd9f4638209f049a/pkg/build/info.go#L62)):*
> ```Go
> // VersionPrefix returns the version prefix of the current build.
> func VersionPrefix() string {
> 	if baseBranch == "unknown" {
> ```

Then you can use our semver library:

```
v, err := version.NewVersion(baseBranch)
if err != nil {
    return "dev"
}
return "v" + version.Segments()[:2]
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-:-Ksj1zbKEkxvtD59fAmD:b89uywc)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Makefile, line 163 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-Ksj-8nZL6_xHmGxeXxQ:-Ksj_EYKkOW7V60tl7Bf:b-3ywzts) ([raw file](https://github.com/cockroachdb/cockroach/blob/443f1d50d55e0d918f4eb73f6a139554865959fd/Makefile#L163)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

why not just make this recipe apply to `test` too?
</blockquote></details>

Done. I didn't know this was possible! TIL :)

---

*[Makefile, line 370 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-Ksj1CsY426dlqOOpJR7:-Ksj_l_mWoKZxjb8n9-2:bb33jti) ([raw file](https://github.com/cockroachdb/cockroach/blob/0783fa4e2f3ec7b25e59cc8ebd9f4638209f049a/Makefile#L370)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Avoid including the junk that specifies the distance from tag?

```
git describe --tags --abbrev=0
```
</blockquote></details>

Done. Thanks for the hint!

---

*[pkg/build/info.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-Ksj0f2XLpWxDQ22eD_e:-KsjarDuihNJXRaDQJVU:b-awxfec) ([raw file](https://github.com/cockroachdb/cockroach/blob/0783fa4e2f3ec7b25e59cc8ebd9f4638209f049a/pkg/build/info.go#L62)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Then you can use our semver library:

```
v, err := version.NewVersion(baseBranch)
if err != nil {
    return "dev"
}
return "v" + version.Segments()[:2]
```
</blockquote></details>

Oh, nice :)
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990)*

**Comment by benesch** [comment]
:lgtm_strong:

Thanks for teaching the tests to build binaries with proper buildinfo; I've been meaning to fix that for a while.

---

Reviewed 9 of 9 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17990#-:-Ksjf4cD9_erJ-bDx0eP:bpltza9)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
