### PR TITLE
sql/parser: fix the grouping of a = ANY/SOME/ALL b <postfixop>

### LINKED ISSUE #19555: sql: parser is too permissive for ANY/ALL/SOME expressions
We accept expressions with the `ANY`, `ALL` and `SOME` with or without parentheses in their antecedents. For example, we permit the query:

```
SELECT 1 = ANY ARRAY[1];
```

This isn't valid SQL in PostgreSQL or MySQL, both of which require the antecedent to be parenthesized. We should probably require the same thing, because otherwise our precedence rules create confusing situations like the following:

```
root@:26257/> SELECT 1 = any array[1]:::int[];
pq: incompatible type annotation for 1 = ANY ARRAY[1] as int[], found type: bool
```

Relatedly, our expression formatter for this variety of expression omits the enclosing parentheses unless the antecedent contains another comparison expression. This is an actual bug, causing expressions to fail to roundtrip. It's solved in #19424.

### LINKED ISSUE #19778: sql: Parse followed by Format is not idempotent
Two non-roundtrippable statements found by the RSG:

rsg_test.go:294:  Parse followed by Format is not idempotent: "SELECT DEFAULT NOT ILIKE ANY ( SELECT error ) IS UNKNOWN IS UNKNOWN ident FROM ident " -> "SELECT ((DEFAULT NOT ILIKE ANY ((SELECT error))) IS NULL) IS NULL AS ident FROM ident" != "SELECT ((DEFAULT NOT ILIKE ANY (((SELECT error)))) IS NULL) IS NULL AS ident FROM ident"

Parse followed by Format is not idempotent: "PAUSE JOB DEFAULT NOT ILIKE ANY ( TABLE ONLY ( ident . PLANS ) @ ident WITH ORDINALITY ident ( ident ) )" -> "PAUSE JOB DEFAULT NOT ILIKE ANY ((TABLE ident.plans@ident WITH ORDINALITY AS ident (ident)))" != "PAUSE JOB DEFAULT NOT ILIKE ANY (((TABLE ident.plans@ident WITH ORDINALITY AS ident (ident))))"

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, an expression of the form `a = ANY b <postfix>`,
for example `1 = ANY 2::INT` would be parsed as `(a = ANY b)
<postfix>` (`((1) = ANY (2))::INT`), not the required `a = ANY (b
<postfix>)` (`(1) = ANY ((2)::INT)`).

This is incorrect on its face, and peeking at the pg grammar indeed
different from what pg does: the right operand of an ANY/SOME/ALL
comparisons must be an `a_expr`, not a `d_expr`.

Fixes  #19778.

Also reverts 5a729ee. Still fixes #19555.

### CODE REVIEW

**Comment by knz** [comment]
Will cherry-pick onto 1.1.

**Comment by nvanbenschoten** [comment]
Thanks for fixing this!

---

Reviewed 2 of 2 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/parse_test.go, line 1262 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-KyEqAnRdjoMpwLgGMM2:-KyEqAnRdjoMpwLgGMM3:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d31e9bfd68987099d0abbe9c166f65a2843fbe/pkg/sql/parser/parse_test.go#L1262)):*
> ```Go
> }
> 
> // TestParseTree checks that the implicit grouping done by the grammar
> ```

Nice test!

---

*[pkg/sql/parser/parse_test.go, line 1263 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-KyEpoI07nRBLXeiP4nZ:-KyEpoI07nRBLXeiP4n_:b-55dh4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d31e9bfd68987099d0abbe9c166f65a2843fbe/pkg/sql/parser/parse_test.go#L1263)):*
> ```Go
> 
> // TestParseTree checks that the implicit grouping done by the grammar
> // is properly reflected int he parse tree.
> ```

`s/he/the/`

---

*[pkg/sql/parser/parse_test.go, line 1276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-KyEq3IgQLMgGfmaxeE9:-KyEq3IgQLMgGfmaxeEA:bhag72) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d31e9bfd68987099d0abbe9c166f65a2843fbe/pkg/sql/parser/parse_test.go#L1276)):*
> ```Go
> 
> 	pfmt := *FmtSimple
> 	pfmt.alwaysParens = true
> ```

Why not just do `pfmt := fmtFlags{alwaysParens: true}`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-:-KyEqS-7td2EQGZ8a9Ay:b-whxd1j)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/parse_test.go, line 1263 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-KyEpoI07nRBLXeiP4nZ:-KyFv_YY3_iBlGBcpbqR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d31e9bfd68987099d0abbe9c166f65a2843fbe/pkg/sql/parser/parse_test.go#L1263)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/he/the/`
</blockquote></details>

Done.

---

*[pkg/sql/parser/parse_test.go, line 1276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-KyEq3IgQLMgGfmaxeE9:-KyFveHSDGIf_OoE7Q4_:bz6zrka) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d31e9bfd68987099d0abbe9c166f65a2843fbe/pkg/sql/parser/parse_test.go#L1276)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why not just do `pfmt := fmtFlags{alwaysParens: true}`?
</blockquote></details>

No reason. Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-:-KyH3FUiU1o9wVPcvVcu:bnfp4nl)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 7 of 7 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19801#-:-KyHBZPhmzXINBrDe3bT:bnfp4nl)*

**Pull request merged**
