### PR TITLE
pgwire: remove left over types refactor artifact

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
#36811 has been closed, so I tried removing this code, and the build is green. Is there anything I'm missing?

**Comment by yuzefovich** [comment]
cc @otan maybe you're familiar with some of this stuff

**Comment by yuzefovich** [comment]
@jordanlewis I think it should be ok now to merge this since the branch was cut and see whether anything breaks.

**Comment by otan** [comment]
missed this the first time around. I don't see anything wrong with this :0

**Review by jordanlewis — COMMENTED** [review]
:lgtm: - there may be problems that this causes, but we won't know until the nightly ORM tests and so on run...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44471#-:-M46S044DO190yrC-FoB:b-9fdx4y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
