### PR TITLE
sql: use integer placeholder IDs

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change modifies `tree.Placeholder` to store an integer ID
(between 1 and 65535) instead of a string. This saves silly
allocations in pgwire, and in a future change we can switch the
PlaceholderInfo maps to slices.

Informs #30086.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33515)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/placeholders.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVPMYfe-BDwyFUMaMax:-LVPMYff1b7Ik52eUxyN:b-8hcfra) ([raw file](https://github.com/cockroachdb/cockroach/blob/91aba0d506b9f4a840df748f06509baa7fcc728f/pkg/sql/sem/tree/placeholders.go#L29)):*
> ```Go
> 
> // PlaceholderTypes relates placeholder names to their resolved type.
> type PlaceholderTypes map[types.PlaceholderID]types.T
> ```

I think this should/could become a slice instead (properly encapsulated to grow it with the largest placeholder accessed). This is what pg does.
___
*[pkg/sql/sem/tree/placeholders.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVPMfml4TNg7GCICU6A:-LVPMfml4TNg7GCICU6B:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/91aba0d506b9f4a840df748f06509baa7fcc728f/pkg/sql/sem/tree/placeholders.go#L34)):*
> ```Go
> //
> // A nil value represents a NULL argument.
> type QueryArguments map[types.PlaceholderID]TypedExpr
> ```

ditto

**Comment by RaduBerinde** [comment]
I changed the maximum placeholder ID to 65536 because pgwire would in principle allow 65536 placeholders.

@knz yes, but not in this change, see the description (it's why this doesn't close the issue).

**Review by nvb — CHANGES_REQUESTED** [review]
Mostly :lgtm:. Thanks for looking into this! I have two questions though, neither of which need to block this PR.
1. should `PlaceholderID` be 0-indexed or 1-indexed. See my comment below.
2. Postgres disallows gaps in placeholder IDs; we don't. This isn't a big deal when we store placeholder IDs in a map, but the reason for introducing such a restriction becomes clear when storing placeholders in an array. Should we consider such a restriction? Note that we're already going to need some global inspection of all placeholder IDs in a statement when we move to backing the placeholders using an array because we'll need to determine how large to size the array.

> Reviewed 12 of 20 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-:-LVPsqKoC8diRbJjr8EV:bqf9bwb)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sem/types/types.go, line 396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVPrH3HC9Bwg24s0efY:-LVPrH3HC9Bwg24s0efZ:b-7oidsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/678787f528c16fcea063694691a7877595bed627/pkg/sql/sem/types/types.go#L396)):*
> PlaceholderID is the 1-based index of a placeholder.

> Placeholder names are 1-indexed; the arrays in the protocol are 0-indexed.

We should try to make sense of this mismatch. When we eventually move to storing these `PlaceholderID` types in a slice, do we want them to be 1-indexed or 0-indexed? I would assume the latter, but right now we're sticking with the former. 

After touching this code, do you think it's more invasive to store these values as 1-indexed integers and convert when touching the pgwire protocol (and soon array indexing) or 0-indexed integers and convert when parsing and formatting the placeholders as strings ("placeholder names")?

Another thing to consider is that if we stored these placeholders in their 0-indexed form then we could store them as `uint16`s instead of `uint32`s. That's minor, but it hints at what Postgres does.

**Review by nvb — APPROVED** [review]

**Review by knz — APPROVED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33515)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
I'm not fully up-to-speed on the details, so not sure if this applies, but I'd expect the user-visible labels to be 1-based ($1, $2, etc). Then, when they're stored in a slice, I'd then subtract 1 from the label on-the-fly so that there's no wastage in the slice:
```
myslice[paramIndex-1] = paramValue
```

**Comment by RaduBerinde** [comment]
The user visible labels will necessarily be `$1`, `$2` in any case. The question is if we want to use 0-based IDs internally (and add 1 when converting to a string like `$1`) or use 1-based IDs (and subtract 1 in various contexts, like the one you mentioned).

**Comment by RaduBerinde** [comment]
Note that we could provide PlaceholderID-to-int-index and int-index-to-PlaceholderID conversion helpers which would do the +1 and -1 internally. This could be a pretty clean solution.

**Comment by nvanbenschoten** [comment]
I like the idea of using some kind of type safety for this since we'll need to have the boundary somewhere, so it might as well lie along a type boundary. My preference is still:
- `string` = 1-indexed
- `PlaceholderID`/`int`/`int16` = 0-indexed

**Comment by RaduBerinde** [comment]
I gave it a shot with 0-indexed, it does seem cleaner, very few +/- 1 conversions. Renamed `PlaceholderID` to `PlaceholderIdx` to make it clear it maps to an index.

**Review by nvb — CHANGES_REQUESTED** [review]
Left a few nits, but otherwise this is so good! Thanks for trying the approach out. :lgtm_strong: 

> Reviewed 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-:-LVUMllS0nTVkT6X4o63:bma8n8o)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/expr.go, line 768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVULnznCSilDgcWvqdu:-LVULnznCSilDgcWvqdv:bl6133n) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2bd64773b34bbe4b598db60ecf42e0d9cba07/pkg/sql/sem/tree/expr.go#L768)):*
> ```Go
> 		return nil, err
> 	}
> 	if uval == 0 || uval > types.MaxPlaceholderIdx+1 {
> ```

nit: leave a comment explaining `types.MaxPlaceholderIdx+1`. It's far enough from the rest of this logic that it might be confusing to the casual reader.
___
*[pkg/sql/sem/tree/placeholders.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVUM6T3EocKJZ0pBQNu:-LVUM6T3EocKJZ0pBQNv:blwu5le) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2bd64773b34bbe4b598db60ecf42e0d9cba07/pkg/sql/sem/tree/placeholders.go#L46)):*
> ```Go
> 	sep := ""
> 	for k, v := range *qa {
> 		fmt.Fprintf(&buf, "%s$%d:%q", sep, k+1, v)
> ```

Can this be `fmt.Fprintf(&buf, "%s%s:%q", sep, k, v)`?
___
*[pkg/sql/sem/tree/placeholders.go, line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVUMXnQCs3eFdcJnkwJ:-LVUMXnQCs3eFdcJnkwK:b1f110s) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2bd64773b34bbe4b598db60ecf42e0d9cba07/pkg/sql/sem/tree/placeholders.go#L110)):*
> ```Go
> 	for pn := range p.Types {
> 		if _, ok := p.Values[pn]; !ok {
> 			missing = append(missing, fmt.Sprintf("$%d", pn+1))
> ```

Same question - can this be `missing = append(missing, pn.String())`?

**Review by nvb — APPROVED** [review]

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-:-LVVDFBd42id_PFGptP9:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/placeholders.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVUM6T3EocKJZ0pBQNu:-LVVCz3iA7ctKr_72LR_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2bd64773b34bbe4b598db60ecf42e0d9cba07/pkg/sql/sem/tree/placeholders.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can this be `fmt.Fprintf(&buf, "%s%s:%q", sep, k, v)`?
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/placeholders.go, line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LVUMXnQCs3eFdcJnkwJ:-LVVCzwBEJMdmqsh2pLQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c2bd64773b34bbe4b598db60ecf42e0d9cba07/pkg/sql/sem/tree/placeholders.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same question - can this be `missing = append(missing, pn.String())`?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33515)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33515)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[pkg/sql/pgwire/pgwire_test.go, line 2161 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33515#-LavhVe186nVAJfvMFRr:-LavhVe186nVAJfvMFRs:bdiwitr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5b365b805b6aedd305b2b89360b288b5b44e5a/pkg/sql/pgwire/pgwire_test.go#L2161)):*
> ```Go
> }
> 
> func TestPGWireTooManyArguments(t *testing.T) {
> ```

Hey @raduberinde are you aware that before deleting this test, it used to take 20s, apparently blocked on the following stack? Is there anything to see here?

```
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scopeColumn).getExprStr(0xc0038b15d0, 0xc002ac8070, 0x10)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope_column.go:71 +0xd9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).findExistingCol(0xc000f0e200, 0x67b84c0, 0xc0015d5000, 0xc000539b38)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:396 +0x114
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).finishBuildScalar(0xc0009ea0f0, 0x67b84c0, 0xc0015d5000, 0xbc25, 0xc000f0e100, 0xc000f0e200, 0xc003df9210, 0xc00000bc25)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:196 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc0009ea0f0, 0x67b84c0, 0xc0015d5000, 0xc000f0e100, 0xc000f0e200, 0xc003df9210, 0x0, 0xbc24)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:449 +0x35d
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildProjectionList(0xc0009ea0f0, 0xc000f0e100, 0xc000f0e200)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:137 +0x68
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc0009ea0f0, 0xc00111e990, 0x0, 0x0, 0x0, 0xc000f0e000, 0x400d8d3)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:522 +0x3ed
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc0009ea0f0, 0xc002346780, 0xc000f0e000, 0x1000007b70580)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:457 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc0009ea0f0, 0x67ab860, 0xc002346780, 0xc000f0e000, 0x4)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:187 +0xf1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc0009ea0f0, 0x0, 0x0)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:144 +0xf7
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc000538e18, 0x67a8560, 0xc0010da120, 0x67ab860, 0xc002346780, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:424 +0x2cb
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optionallyUseOptimizer(0xc000538e18, 0x67a8560, 0xc0010da120, 0x0, 0x0, 0x6069926, 0x9, 0x0, 0x1, 0x0, ...)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:549 +0xc4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func1(0xc000538a00, 0x67a8560, 0xc0010da120, 0xc00111ecf0, 0xc000d095c0, 0xc000578a00, 0x67ab860, 0xc002346780, 0x0, 0x0, ...)
	/Users/andrei/work3/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:212 +0x348
```

**Comment by RaduBerinde** [comment]
Hm, not surprised, that test built a query with 65536 columns (and the optbuilder has some quadratic loops). It's not a realistic case, I don't think it's there's anything we need to fix.

**Pull request merged**
