### PR TITLE
storage: minor cleanups from #13501

### PR DESCRIPTION
**Pull request by tamird**
Last commit is nitpicky, can remove if opinions emerge.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13761)

### CODE REVIEW

**Comment by petermattis** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/push_txn_queue.go, line 301 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUBxWkwkzz_sCiGy-:-KdgUBxWkwkzz_sCiGy0:b7c8519) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d6546643ff33d4ad675420cb6b7933cdce08ec2/pkg/storage/push_txn_queue.go#L301)):*
> ```Go
> 			now := ptq.store.Clock().Now().GoTime()
> 			pusheeTxnTimer.Reset(expiration.Sub(now))
> 		}
> ```

I don't find this easier to read. Nor do I find it harder to read. 

---

*[pkg/storage/push_txn_queue_test.go, line 162 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUmWPFiDv0t-233IT:-KdgUmWQuitnwqIFiJYo:b-k9skuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b498f9777f01acd7cca238a83c559493bdd1d0/pkg/storage/push_txn_queue_test.go#L162)):*
> ```Go
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> ```

Why is this better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761)*

**Comment by tamird** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/push_txn_queue.go, line 301 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUBxWkwkzz_sCiGy-:-KdgV-qSkxfHfZZumeRD:b-ovmmu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d6546643ff33d4ad675420cb6b7933cdce08ec2/pkg/storage/push_txn_queue.go#L301)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't find this easier to read. Nor do I find it harder to read. 
</blockquote></details>

This was motivated by the desire to avoid a manual cast to time.Duration (not readability).

---

*[pkg/storage/push_txn_queue_test.go, line 162 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUmWPFiDv0t-233IT:-KdgV5CouqIfX7PNTt02:bn17pru) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b498f9777f01acd7cca238a83c559493bdd1d0/pkg/storage/push_txn_queue_test.go#L162)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why is this better?
</blockquote></details>

Because it produces a line number that flags the error's circumstance. I've often been bitten by t.Fatal or t.Error in random functions making it hard to spot the offending invocation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/push_txn_queue.go, line 301 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUBxWkwkzz_sCiGy-:-KdgVf2C1JHkrjidDTTw:bj4cdis) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d6546643ff33d4ad675420cb6b7933cdce08ec2/pkg/storage/push_txn_queue.go#L301)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This was motivated by the desire to avoid a manual cast to time.Duration (not readability).
</blockquote></details>

Why is the cast to `time.Duration` problematic?

---

*[pkg/storage/push_txn_queue_test.go, line 162 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUmWPFiDv0t-233IT:-KdgWBAk-MoAjmyoaHiY:bi0xjcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b498f9777f01acd7cca238a83c559493bdd1d0/pkg/storage/push_txn_queue_test.go#L162)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Because it produces a line number that flags the error's circumstance. I've often been bitten by t.Fatal or t.Error in random functions making it hard to spot the offending invocation.
</blockquote></details>

Ok, though I would personally defer to the original author and I question the priority of a change like this. It's not like this test was flaky and you've been trying to debug it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761)*

**Comment by tamird** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/push_txn_queue.go, line 301 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUBxWkwkzz_sCiGy-:-KdgXITBF9idiv59cLkM:bglj733) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d6546643ff33d4ad675420cb6b7933cdce08ec2/pkg/storage/push_txn_queue.go#L301)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why is the cast to `time.Duration` problematic?
</blockquote></details>

Because it's breaking abstractions - WallTime and Logical would not be exported if the proto compiler provided this option.

---

*[pkg/storage/push_txn_queue_test.go, line 162 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUmWPFiDv0t-233IT:-KdgWv12_qJmbPy--TFs:b-y7vxfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b498f9777f01acd7cca238a83c559493bdd1d0/pkg/storage/push_txn_queue_test.go#L162)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok, though I would personally defer to the original author and I question the priority of a change like this. It's not like this test was flaky and you've been trying to debug it.
</blockquote></details>

Yes, that's not the case, but there is a cost of writing (any) tests this way - many tests are written by copying existing art.

This is not a priority, I was in this file because of the clock change (which I caught on another branch) and decided to change this while I was here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/push_txn_queue_test.go, line 162 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUmWPFiDv0t-233IT:-Ke4F-oAAmZhnGo78dTc:b690fdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b498f9777f01acd7cca238a83c559493bdd1d0/pkg/storage/push_txn_queue_test.go#L162)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Yes, that's not the case, but there is a cost of writing (any) tests this way - many tests are written by copying existing art.

This is not a priority, I was in this file because of the clock change (which I caught on another branch) and decided to change this while I was here.
</blockquote></details>

I'm thumbs-down on the changes to this testing code, though I'll let @spencerkimball speak up if he cares. The non-test changes LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761)*

**Comment by spencerkimball** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/push_txn_queue_test.go, line 162 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761#-KdgUmWPFiDv0t-233IT:-Ke50sgaOudxseOAT5P4:b-umjvjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b498f9777f01acd7cca238a83c559493bdd1d0/pkg/storage/push_txn_queue_test.go#L162)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm thumbs-down on the changes to this testing code, though I'll let @spencerkimball speak up if he cares. The non-test changes LGTM.
</blockquote></details>

It's fine by me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13761)*

**Comment by tamird** [comment]
TFYRs!

**Pull request merged**
