### PR TITLE
ui: typings depend on generated proto typings

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8598)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8598#-:-KPKQndXxKAcCJpx7XGx:bnfp4nl)*

**Comment by maxlang** [comment]
Should probably depend on generated/proto.d.ts instead. Otherwise it reinstall the typings each time I think.

**Comment by tamird** [comment]
It will not; this is why `typings.installed` is a thing.

**Comment by maxlang** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8598#-:-KPLxwbsLf-hMU0jVhDh:bnfp4nl)*

**Pull request merged**
