### PR TITLE
opt/opbench: add more cost tests

### PR DESCRIPTION
**Pull request by justinj**
This commit introduces more costing tests for some scans and sorts.

The plots some some room for improvement on the costing:

image

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Cool graph. I wonder what metric would help bring them more in-line. Maybe avg value size for each column.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-:-LbPea7ECGiK3Aq08ZxK:bc4pqa5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-:-LbQYBVyERs4n6VfQoDs:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/sql/opt/opbench/opbench_test.go, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-LbQXLgHAHawD_WxtRLk:-LbQXLgI6wNdSibmCWDc:b1sb1au) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b99723581d633269b8a725f7f7494cce530ecb/pkg/sql/opt/opbench/opbench_test.go#L552)):*
> ```Go
> 				(Table "%s")
> 				(Cols "$cols")
> 		  	(HardLimit $rows)
> ```

[nit] this isn't lined up
___
*[pkg/sql/opt/opbench/opbench_test.go, line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-LbQXqeJ5cptSklz8oPg:-LbQXqeK-tAUm6dndAuB:bygod63) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b99723581d633269b8a725f7f7494cce530ecb/pkg/sql/opt/opbench/opbench_test.go#L583)):*
> ```Go
> 		},
> 	}
> }
> ```

Seems like there's a lot of common code between `makeScanSpec` and `makeSortSpec` -- could some of it be  put into a helper function?
___
*[pkg/sql/opt/opbench/opbench_test.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-LbQX7l06I3fHsgl6Ggu:-LbQX7l06I3fHsgl6Ggv:bsq7zhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b99723581d633269b8a725f7f7494cce530ecb/pkg/sql/opt/opbench/opbench_test.go#L585)):*
> ```Go
> }
> 
> // SortLineitemSpec scans the lineitem table.
> ```

scans -> scans and sorts

**Review by justinj — COMMENTED** [review]
Thanks! I think avg value size would help, but I think there's an easier win which is tweaking the cost of a single column, since there's a moderately high fixed cost to that. I want to lay down some foundation for talking about the accuracy here before making real changes.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-:-LbTMa8z5ZaH-r0hLncn:b-1wr706)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/opbench/opbench_test.go, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-LbQXLgHAHawD_WxtRLk:-LbTMlsC65xPsg_rnIjp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b99723581d633269b8a725f7f7494cce530ecb/pkg/sql/opt/opbench/opbench_test.go#L552)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] this isn't lined up
</blockquote></details>

Done.
___
*[pkg/sql/opt/opbench/opbench_test.go, line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-LbQXqeJ5cptSklz8oPg:-LbTQht8CLmTTGJqS5K4:bmvgiji) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b99723581d633269b8a725f7f7494cce530ecb/pkg/sql/opt/opbench/opbench_test.go#L583)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like there's a lot of common code between `makeScanSpec` and `makeSortSpec` -- could some of it be  put into a helper function?
</blockquote></details>

Pulled out the part that builds the list of columns.
___
*[pkg/sql/opt/opbench/opbench_test.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36390#-LbQX7l06I3fHsgl6Ggu:-LbTQnNX7x8K_lcNszyp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b99723581d633269b8a725f7f7494cce530ecb/pkg/sql/opt/opbench/opbench_test.go#L585)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

scans -> scans and sorts
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36390)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
