### PR TITLE
colexec: add optimized versions of aggregate window functions

### LINKED ISSUE #37039: exec: add optimized versions of aggregates/window functions for certain window frames

### PR DESCRIPTION
**Pull request by DrewKimball**
**colexecwindow: add sliding window functionality to window framer**

This commit adds a method `slidingWindowIntervals` to `windowFramer`
operators that returns a set of `toAdd` intervals and a set of
`toRemove` intervals, which indicate the rows that should be added
to the current aggregation and those that should be removed, respectively.
This will be used to implement the sliding window optimization for
aggregate window functions such as `sum`.

**colexecwindow: implement sliding window aggregator**

This commit supplies a new operator, `slidingWindowAggregator`, which
is used for any window aggregate functions that implement the
`slidingWindowAggregateFunc` interface. Rather than aggregating over
the entire window frame for each row, the `slidingWindowAggregator`
operator aggregates over the rows that are in the current window
frame but were not in the previous, and removes from the aggregation
the rows that were in the previous window frame but not the current.
This allows window aggregate functions to be evaluated in linear rather
than quadratic time.

**colexec: implement sliding window optimization for sum window function**

This commit modifies the `sum` aggregate window function to implement
the `slidingWindowAggregateFunc`, which allows it to be used in a
sliding window context. This yields linear rather than quadratic scaling
in the worst case, and allows the vectorized engine to meet or exceed
parity with the row engine for `sum` window functions.

**colexec: implement sliding window optimization for count window function**

This commit modifies the count aggregate operator to implement the
`slidingWindowAggregateFunc` interface so that it can be used with
the sliding window optimization.

**colexec: implement sliding window optimization for average window function**

This commit modifies the `average` aggregate operator to implement the
`slidingWindowAggregateFunc` interface so that it can be used with the
sliding window optimization.

**colexec: optimize count_rows window function**

This commit implements an optimized version of `count_rows` that
calculates the size of the window frame as soon as the window frame
is calculated. This means that most of the overhead for `count_rows`
now comes from calculating the window frame, which is worst-case
linear time (previously, the step to retrieve the size of the frame
was quadratic, though with a small constant).

**colexec: optimize min and max window functions with default exclusion**

This commit modifies the 'min' and 'max' aggregate window functions
to implement the `slidingWindowAggregateFunc` interface, which allows
them to be used in a sliding window context. However, this is only
usable when the window frame never shrinks - e.g. it always contains
all rows from the previous frame.

This commit also provides implementations of `min` and `max` for use
when the window frame can shrink. The indices of the 'next best'
minimum or maximum values are stored in a priority queue that is
updated for each row. Using the priority queue allows the `min` and
`max` operators to avoid fully aggregating over the window frame
even when the previous best value goes out of scope. Note that this
implementation currently does not handle the case of non-default
exclusion clause, in which case we must fall back to the quadratic
approach.

Fixes: #37039

Release note (performance improvement): The vectorized engine can now
use the sliding-window approach to execute common aggregate functions 
as window functions. This allows aggregate window functions to be evaluated
in linear rather than quadratic time. Currently, sum, count, average, min, and 
max are executed using this approach.

### CODE REVIEW

**Comment by DrewKimball** [comment]
TODO: squash the commits into one before merging.

**Review by yuzefovich — COMMENTED** [review]
Very nice work! Mostly minor and nit comments from me.

> Reviewed 3 of 3 files at r1, 8 of 8 files at r2, 10 of 10 files at r3, 4 of 4 files at r4, 5 of 5 files at r5, 3 of 3 files at r6, 12 of 17 files at r7, 1 of 28 files at r8, 4 of 4 files at r9, 5 of 5 files at r10, 1 of 3 files at r11, 17 of 17 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-:-Mgwwm_a4emd3q20klMo:bk4s4mn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/colexec/colexecagg/avg_agg_tmpl.go, line 104 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwwVjB2m3MiiULw4Hh:-MgwwVjB2m3MiiULw4Hi:b-fi1xdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/avg_agg_tmpl.go#L104)):*
> ```Go
> 	// curCount keeps track of the number of elements that we've seen
> 	// belonging to the current group.
> 	curCount int64
> ```

Hm, I think for `avg` in particular `curCount` is the same as `numNonNull`, so we can actually remove the latter altogether.
___
*[pkg/sql/colexec/colexecagg/count_agg_tmpl.go, line 180 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwwYDr78mEzxHLDGMj:-MgwwYDr78mEzxHLDGMk:blphku0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/count_agg_tmpl.go#L180)):*
> ```Go
> 	vecs []coldata.Vec, inputIdxs []uint32, startIdx, endIdx int,
> ) {
> 	execgen.SETVARIABLESIZE(oldCurAggSize, a.curAgg)
> ```

nit: I missed this originally when I added this accounting, but in case of `count` and `count_rows` the `curAgg` is always `int64`, so there is no point in using `SETVARIABLESIZE`, and we should just remove it.
___
*[pkg/sql/colexec/colexecagg/count_agg_tmpl.go, line 261 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwwcb40-_nD3VwxYMc:-Mgwwcb40-_nD3VwxYMd:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/count_agg_tmpl.go#L261)):*
> ```Go
> // {{/*
> // _REMOVE_ROW removes the value of the ith row from the output for the
> // current aggregation. If this is the first row of the current aggregation, and
> ```

ditto
___
*[pkg/sql/colexec/colexecagg/min_max_agg_tmpl.go, line 205 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwqq_v8OyuvgQwoplz:-Mgwqq_w4pYyj9VAzxwj:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/min_max_agg_tmpl.go#L205)):*
> ```Go
> 		a.col.Set(outputIdx, a.curAgg)
> 	}
> 	// {{if and (not (eq "_AGGKIND" "Window")) (or (.IsBytesLike) (eq .VecMethod "Datum"))}}
> ```

Why did this change?
___
*[pkg/sql/colexec/colexecagg/sum_agg_tmpl.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwmVTeAlQgtvAygBEr:-MgwmVTeAlQgtvAygBEs:b-bot5eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e709b0fdf083b5b92c6caf0cfdd5b7e6e550e838/pkg/sql/colexec/colexecagg/sum_agg_tmpl.go#L98)):*
> ```Go
> 	// numNonNull tracks the number of non-null values we have seen for the group
> 	// that is currently being aggregated.
> 	numNonNull uint64
> ```

Hm, I'm wondering whether using `uint64` here all the time is a bit unfortunate for the case of the hash aggregation. There, we might have the number of buckets on the order of the number of input rows, and all of these buckets will be kept in memory. By switching from `bool` to `uint64` we might bump the struct into a larger struct size allocation-wise.

I'm thinking maybe we should use `byte` for ordered and hash aggregates and `uint64` for the window - seems like we would only need to change the struct definition here. WDYT?
___
*[pkg/sql/colexec/colexecagg/sum_agg_tmpl.go, line 348 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwiawm8WCJAia690P6:-Mgwiawn1kJRwq-J4gJ7:b-o1rz3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e709b0fdf083b5b92c6caf0cfdd5b7e6e550e838/pkg/sql/colexec/colexecagg/sum_agg_tmpl.go#L348)):*
> ```Go
> // {{/*
> // _REMOVE_ROW removes the value of the ith row from the output for the
> // current aggregation. If this is the first row of the current aggregation, and
> ```

nit: the second sentence seems incorrect/misleading.
___
*[pkg/sql/colexec/colexecwindow/count_rows_aggregator.go, line 74 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwwgnF46ade5l3uYru:-MgwwgnF46ade5l3uYrv:b-y9amzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/count_rows_aggregator.go#L74)):*
> ```Go
> // Init implements the bufferedWindower interface.
> func (a *countRowsWindowAggregator) Init(ctx context.Context) {
> 	if !a.InitHelper.Init(ctx) {
> ```

super nit: we can drop `if`.
___
*[pkg/sql/colexec/colexecwindow/min_max_queue.go, line 150 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwvvfI1HvFLhItCNkm:-MgwvvfI1HvFLhItCNkn:b-5fezdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/min_max_queue.go#L150)):*
> ```Go
> 		return true
> 	}
> 	if q.len() != cap(q.buffer) {
> ```

super nit: I think this condition is more likely to be `true` than the one above, so I would switch them.
___
*[pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go, line 80 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwt_Fe7I6oTYLdbW1O:-Mgwt_Fe7I6oTYLdbW1P:bef3wqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go#L80)):*
> ```Go
> 	framer       windowFramer
> 
> 	// A partial dequeue of indices into the current partition ordered by the
> ```

nit: I think folks usually uses `deque` to `dequeue` for double-ended queue.
___
*[pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go, line 101 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwrhVX3okem_EpmHd3:-MgwrhVX3okem_EpmHd4:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go#L101)):*
> ```Go
> // Init implements the bufferedWindower interface.
> func (b *minMaxRemovableAggBase) Init(ctx context.Context) {
> 	if !b.InitHelper.Init(ctx) {
> ```

ditto
___
*[pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwgTffDsfDYutJ04u5:-MgwgTffDsfDYutJ04u6:b-4net7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40b26c1a26d53f6f896dd1a0931bbc7c0c4899e/pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go#L63)):*
> ```Go
> 	// buffer half of the memory budget even though it will generally store less
> 	// columns than the queue.
> 	bufferMemLimit := int64(float64(args.MemoryLimit) * 0.5)
> ```

I can't seem to find where the second half of the memory limit is used.
___
*[pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go, line 106 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwrEc4DNQf5wluo08d:-MgwrEc4DNQf5wluo08e:b-nzm6j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go#L106)):*
> ```Go
> 					windower = newMaxRemovableAggregator(args, framer, buffer, outputType)
> 				}
> 				if err := closers.Close(); err != nil {
> ```

This seems suspicious.
___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwdEWQBROaARUsCo9s:-MgwdEWQBROaARUsCo9t:b-qbao1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d28d82d4473f9c3f66e6aa6af7ab924d77b9291/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L525)):*
> ```Go
> // rows that are a part of the current window frame, but not the previous one,
> // and rows that were a part of the previous window frame, but not the current
> // one. Note that getSlidingWindowIntervals appends to the provided 'toAdd' and
> ```

nit: it might be a bit cleaner to remove this from the contract and simply do `toAdd, toRemove = toAdd[:0], toRemove[:0]` in the very beginning. I think it should still work if those are `nil`.
___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgweIQ900zapbX4uAy4:-MgweIQADN62IfUGya2I:b-apemoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d28d82d4473f9c3f66e6aa6af7ab924d77b9291/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L528)):*
> ```Go
> // 'toRemove' slices, so they should be passed in with zero length.
> func getSlidingWindowIntervals(
> 	currIntervals, prevIntervals, toAdd, toRemove []windowInterval,
> ```

nit: I would also explicitly mention the ordering guarantees imposed on the input slices and provided for the output slices.
___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwdfCo8x0h1aBcAO2f:-MgwdfCo8x0h1aBcAO2g:bqb20y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d28d82d4473f9c3f66e6aa6af7ab924d77b9291/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L533)):*
> ```Go
> 	var prev, curr windowInterval
> 	setPrev, setCurr := true, true
> 	for {
> ```

nit: a general comment on what (and a bit about how) this loop accomplishes would be helpful.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68212)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colexecagg/avg_agg_tmpl.go, line 104 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwwVjB2m3MiiULw4Hh:-MgylldI2d342TcIHNWE:b-8xip0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/avg_agg_tmpl.go#L104)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I think for `avg` in particular `curCount` is the same as `numNonNull`, so we can actually remove the latter altogether.
</blockquote></details>

Huh, that's clever. Done.
___
*[pkg/sql/colexec/colexecagg/count_agg_tmpl.go, line 180 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwwYDr78mEzxHLDGMj:-MgymWBM23ZpuXGtqNX0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/count_agg_tmpl.go#L180)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I missed this originally when I added this accounting, but in case of `count` and `count_rows` the `curAgg` is always `int64`, so there is no point in using `SETVARIABLESIZE`, and we should just remove it.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecagg/count_agg_tmpl.go, line 261 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwwcb40-_nD3VwxYMc:-MgymXoA27wPMPfAN3TT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/count_agg_tmpl.go#L261)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecagg/min_max_agg_tmpl.go, line 205 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwqq_v8OyuvgQwoplz:-MgymaekDNNUTqE3Gpjr:brf0v39) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecagg/min_max_agg_tmpl.go#L205)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

The aggregation gets reused between frames for the window strategy, so we can't nil out the aggregation. I'll add a comment saying so.
___
*[pkg/sql/colexec/colexecagg/sum_agg_tmpl.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwmVTeAlQgtvAygBEr:-MgygfTj7kkTWHWzaV6c:bleqs0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e709b0fdf083b5b92c6caf0cfdd5b7e6e550e838/pkg/sql/colexec/colexecagg/sum_agg_tmpl.go#L98)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I'm wondering whether using `uint64` here all the time is a bit unfortunate for the case of the hash aggregation. There, we might have the number of buckets on the order of the number of input rows, and all of these buckets will be kept in memory. By switching from `bool` to `uint64` we might bump the struct into a larger struct size allocation-wise.

I'm thinking maybe we should use `byte` for ordered and hash aggregates and `uint64` for the window - seems like we would only need to change the struct definition here. WDYT?
</blockquote></details>

I'm not sure it's actually a problem, since structs get padded out to be a multiple of 8 bytes, so the struct has 1 byte for the bool and then 7 for padding: https://play.golang.org/p/xC47ejwQLym

But it's hard to be sure that this will always be the case, and if any fields get added in the future it could change things. So, I'll add it if you still think it's a good idea
___
*[pkg/sql/colexec/colexecagg/sum_agg_tmpl.go, line 348 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwiawm8WCJAia690P6:-Mgyhl19-EFlr3AiUgdD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e709b0fdf083b5b92c6caf0cfdd5b7e6e550e838/pkg/sql/colexec/colexecagg/sum_agg_tmpl.go#L348)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the second sentence seems incorrect/misleading.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/count_rows_aggregator.go, line 74 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwwgnF46ade5l3uYru:-Mgyi7diEUdy9QwTGprP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/count_rows_aggregator.go#L74)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: we can drop `if`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/min_max_queue.go, line 150 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwvvfI1HvFLhItCNkm:-MgyitqRDPyIcrEiu28F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/min_max_queue.go#L150)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: I think this condition is more likely to be `true` than the one above, so I would switch them.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go, line 80 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mgwt_Fe7I6oTYLdbW1O:-MgyjCRoBtUXEEYPmDzO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go#L80)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think folks usually uses `deque` to `dequeue` for double-ended queue.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go, line 101 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwrhVX3okem_EpmHd3:-MgyjEqy7FpQkjmmi14W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/min_max_removable_agg_tmpl.go#L101)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwgTffDsfDYutJ04u5:-MgytiJ94jdhS3DFqiZO:bpub0xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40b26c1a26d53f6f896dd1a0931bbc7c0c4899e/pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go#L63)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I can't seem to find where the second half of the memory limit is used.
</blockquote></details>

Hm, the `bufferedWindower` gets it from the `args` field, but that's actually a problem because it isn't adjusted for the reserved buffer memory, so we'd end up going over the limit. I guess I introduced this bug during some refactoring in the last PR. Fixed it (and also made the limit-passing more explicit).
___
*[pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go, line 106 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwrEc4DNQf5wluo08d:-MgyvI2l9c2f0LQe6FNH:bsuj5rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ad6a51de0bb0e552f9f4c1695063e2af19bee81/pkg/sql/colexec/colexecwindow/window_aggregator_tmpl.go#L106)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This seems suspicious.
</blockquote></details>

That it does. Removed the unnecessary `AggregateFunc` construction for the case when min and max are specialized.
___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwdEWQBROaARUsCo9s:-MgyjxMhBbkyDW5w1gNp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d28d82d4473f9c3f66e6aa6af7ab924d77b9291/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L525)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it might be a bit cleaner to remove this from the contract and simply do `toAdd, toRemove = toAdd[:0], toRemove[:0]` in the very beginning. I think it should still work if those are `nil`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgweIQ900zapbX4uAy4:-Mgyk7oG4y3Vb7DTp34J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d28d82d4473f9c3f66e6aa6af7ab924d77b9291/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L528)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I would also explicitly mention the ordering guarantees imposed on the input slices and provided for the output slices.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwdfCo8x0h1aBcAO2f:-Mgylh-EEK5gfTAYJgJL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d28d82d4473f9c3f66e6aa6af7ab924d77b9291/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L533)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: a general comment on what (and a bit about how) this loop accomplishes would be helpful.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 40 files at r13, 12 of 20 files at r14, 9 of 13 files at r15, 6 of 6 files at r16, 5 of 5 files at r17, 1 of 4 files at r18, 18 of 18 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-:-Mh-PA_H1nXEW6BM0j2p:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/colexec/colexecagg/sum_agg_tmpl.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-MgwmVTeAlQgtvAygBEr:-Mh-OzzED_ItjplYEfST:b-ojd5d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e709b0fdf083b5b92c6caf0cfdd5b7e6e550e838/pkg/sql/colexec/colexecagg/sum_agg_tmpl.go#L98)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I'm not sure it's actually a problem, since structs get padded out to be a multiple of 8 bytes, so the struct has 1 byte for the bool and then 7 for padding: https://play.golang.org/p/xC47ejwQLym

But it's hard to be sure that this will always be the case, and if any fields get added in the future it could change things. So, I'll add it if you still think it's a good idea
</blockquote></details>

Yeah, good point. This would matter if we had multiple single-byte fields. Never mind.
___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 540 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mh-Ezme1VJCvYTbzCHP:-Mh-Ezme1VJCvYTbzCHQ:b-n004yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a088567954dfdf418879c3d5cc52cee90a9810cd/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L540)):*
> ```Go
> 		// this, take advantage of the fact that both sets of intervals are in
> 		// ascending order, similar to merging sorted lists. Maintain indices into
> 		// each list, and iterate whichever index has the 'smaller' interval (e.g.)
> ```

super nit: the closing parenthesis probably should be after "ends first".

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68212)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[pkg/sql/colexec/colexecwindow/window_framer_tmpl.go, line 540 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68212#-Mh-Ezme1VJCvYTbzCHP:-Mh0PKtA6YiUFp18qOVG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a088567954dfdf418879c3d5cc52cee90a9810cd/pkg/sql/colexec/colexecwindow/window_framer_tmpl.go#L540)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: the closing parenthesis probably should be after "ends first".
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
TFTR!

**Comment by DrewKimball** [comment]
The bazel failures are a timeout and a multiregion test with no window functions, so I think they're unrelated.

**Pull request merged**
