### PR TITLE
storage: add WaitForApplication RPC to PerReplicaServer

### PR DESCRIPTION
**Pull request by benesch**
Add a long-poll RPC to the PerReplicaServer that blocks until the
addressed replica has applied the Raft command with the specified index.
This RPC will be used to ensure safe range merges, where we need to
guarantee that all replicas of the RHS are caught up before committing
the merge.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
It occurs to me that this might interact badly with @spencerkimball's work on dehydrating replicas.

**Review by tbg — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/stores_server.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJrx4V221YHxg2MgfL-:-LJrx4V36CUSzYsD8UhG:b-h7jjzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d27293bd7af36db49dfa857d4cb98d41765d38/pkg/storage/stores_server.go#L93)):*
> ```Go
> 		// TODO(benesch): this extra goroutine is unfortunate. sync.Cond does not
> 		// compose well with contexts (see golang/go#16620). Perhaps we could avoid
> 		// using sync.Cond to implement WaitForApplication?
> ```

I also think it's unfortunate that you have to throw broadcasts across the replica code. Would it be that terrible to just poll? I imagine that @nvanbenschoten's RangeFeed work might give you a more convenient hook in the future. (Polling should also avoid bad interactions with @spencerkimball's work). By the way, if you're running the merge on the leader, you could also check the Raft Progress for this follower before you even send out the RPC.

**Review by benesch — COMMENTED** [review]
Ok, RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-:-LJtTb6h9sCR5w7f3e8s:bkqtryl)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/stores_server.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJrx4V221YHxg2MgfL-:-LJtTMNoAmIIDqDM4vIa:b-5r9a2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d27293bd7af36db49dfa857d4cb98d41765d38/pkg/storage/stores_server.go#L93)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I also think it's unfortunate that you have to throw broadcasts across the replica code. Would it be that terrible to just poll? I imagine that @nvanbenschoten's RangeFeed work might give you a more convenient hook in the future. (Polling should also avoid bad interactions with @spencerkimball's work). By the way, if you're running the merge on the leader, you could also check the Raft Progress for this follower before you even send out the RPC.
</blockquote></details>

I suppose it's not that terrible! Done.

**Review by tbg — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/api.proto, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJtbpbHChxZO6-IHVHS:-LJtbpbIDTJXAiQkYVF9:b-jzvjt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/01987025095e29e14d70d526794dcf714a9eed1a/pkg/storage/api.proto#L58)):*
> ```protobuf
> 
> // WaitForApplicationRequest blocks until the addressed replica has applied the
> // command with the specified index.
> ```

Perhaps clarify that this is a Raft log index.
___
*[pkg/storage/client_raft_test.go, line 4012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJtcAD3596c1HZ_YoAF:-LJtcAD3596c1HZ_YoAG:b-5hz1jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/01987025095e29e14d70d526794dcf714a9eed1a/pkg/storage/client_raft_test.go#L4012)):*
> ```Go
> 			t.Fatal(pErr)
> 		}
> 		for j, errCh := range errChs {
> ```

`after := time.After(20*time.Millisecond)` and use `case <-after:` below instead of `default`?
___
*[pkg/storage/stores_server.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJtcWSu8oKYhiWs0OBt:-LJtcWSu8oKYhiWs0OBu:bouj9zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/01987025095e29e14d70d526794dcf714a9eed1a/pkg/storage/stores_server.go#L105)):*
> ```Go
> 			}
> 		}
> 		return ctx.Err()
> ```

This is probably doing the right thing, but to make me less nervous, could you write this as

```
if err := ctx.Err(); err != nil {
  return err
}
log.Fatal(ctx, "unreachable")

```

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/api.proto, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJtbpbHChxZO6-IHVHS:-LJthiYj-MX9JMxkvGWn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01987025095e29e14d70d526794dcf714a9eed1a/pkg/storage/api.proto#L58)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Perhaps clarify that this is a Raft log index.
</blockquote></details>

Done.
___
*[pkg/storage/client_raft_test.go, line 4012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJtcAD3596c1HZ_YoAF:-LJthtch33rtwJrxzRXb:b-jp4814) ([raw file](https://github.com/cockroachdb/cockroach/blob/01987025095e29e14d70d526794dcf714a9eed1a/pkg/storage/client_raft_test.go#L4012)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`after := time.After(20*time.Millisecond)` and use `case <-after:` below instead of `default`?
</blockquote></details>

Done. I reworked your suggestion slightly to avoid waiting 20ms for every errCh; with three nodes and four requests that actually adds up to a lot of time.
___
*[pkg/storage/stores_server.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJtcWSu8oKYhiWs0OBt:-LJtj_Q49YclzEApFFk7:bknmk5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/01987025095e29e14d70d526794dcf714a9eed1a/pkg/storage/stores_server.go#L105)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This is probably doing the right thing, but to make me less nervous, could you write this as

```
if err := ctx.Err(); err != nil {
  return err
}
log.Fatal(ctx, "unreachable")

```
</blockquote></details>

Done. I also reworked your suggestion slightly here; the function has to return something and

```
log.Fatal(cox, "unreachable")
return nil
```

reads rather funny to me.

**Review by bdarnell — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by benesch — COMMENTED** [review]
Ugh, deflaking this test required a new testing knob to turn off range quiescence. Any objections?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-:-LJvl8lQ6GCv70MUJsna:b-kuko3c)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by benesch — COMMENTED** [review]
@nvanbenschoten convinced me that we should be using the lease index here instead of the Raft log index. The merge transaction is perfectly happy to use either the lease index or the Raft log index, but using the lease index neatly fixes the test flakes without needing the aforementioned knob to turn off range quiescence. It's also generally nice for this RPC to be ever-so-slightly less reliant on Raft implementation details.

Please take one last look!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-:-LJvqmp09f_GEoBPtaDM:b-g2otxf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
:lgtm: now that we've switched to waiting for a specific lease applied index. Hopefully that will resolve the flakes you saw in the new test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-:-LJvrGOv6GtDOjn0NJmV:b-djzo6c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/stores_server.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJvqUij0SiTXiij1Kxo:-LJvqUij0SiTXiij1Kxp:b-2ml2wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0b3c0a26803a94c4e662b2da86ba3eab113ed3d/pkg/storage/stores_server.go#L88)):*
> ```Go
> 	resp := &WaitForApplicationResponse{}
> 	err := is.execStoreCommand(req.StoreRequestHeader, func(s *Store) error {
> 		// TODO(benesch): Once Replica changefeeds land, see if we can implement
> ```

`s/changefeeds/rangefeeds/`

I also don't think this will happen any time soon, so the TODO may not be worth it. There are no plans for rangefeeds to send events for operations that do not result in a newly-committed value or a new resolved timestamp. There are also no plans to expose raft/lease applied indices in rangefeed events.

**Review by bdarnell — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-:-LJxwX4O07TqC_wOCv0s:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by benesch — COMMENTED** [review]
Whew, thanks for the re-reviews. Landing!

bors r=bdarnell,nvanbenschoten,tschottdorf

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-:-LJy-nn88u8Pm1l5LzaA:b-edyrgv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/stores_server.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJvqUij0SiTXiij1Kxo:-LJy-k655pe3iQFzGl3n:b86231q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0b3c0a26803a94c4e662b2da86ba3eab113ed3d/pkg/storage/stores_server.go#L88)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/changefeeds/rangefeeds/`

I also don't think this will happen any time soon, so the TODO may not be worth it. There are no plans for rangefeeds to send events for operations that do not result in a newly-committed value or a new resolved timestamp. There are also no plans to expose raft/lease applied indices in rangefeed events.
</blockquote></details>

Ack. I'll clean this up in a future commit.

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28549)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/stores_server.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28549#-LJvqUij0SiTXiij1Kxo:-LJy2Gus-cgQGJpbkdLt:b-elpx1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0b3c0a26803a94c4e662b2da86ba3eab113ed3d/pkg/storage/stores_server.go#L88)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ack. I'll clean this up in a future commit.
</blockquote></details>

FWIW, I wasn't suggesting to establish a rangefeed here, but rather that Nathan has a similar need of doing something reactive with each Raft log application. It's worth revisiting when that has happened (chances are it won't be useful to replace this code) but I also don't think the TODO needs to be kept around.

**Pull request merged**
