### PR TITLE
opt: reorganize the exec.Engine interface

### PR DESCRIPTION
**Pull request by RaduBerinde**
The Engine interface is only used for testing. In this change we
rename it to TestEngine and define a TestEngineFactory (implemented by
sql.Executor) that replaces the NewExecEngine hack.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22598#-L5AQsrfCXys6sGgqIvK:-L5AQsrfCXys6sGgqIvL:bazjcne) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1b640e68a0c82dfb60ee31d821c505e233ea00/pkg/sql/executor_opt_interface.go#L30)):*
> ```Go
> 
> // NewTestEngine is part of the exec.TestEngineFactory interface.
> func (e *Executor) NewTestEngine() exec.TestEngine {
> ```

If this code is only used for testing it seems like it should go in `testutils` or some other place...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22598)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22598#-L5AQsrfCXys6sGgqIvK:-L5ASxyU6tXq9z18kv2N:b-yb0vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1b640e68a0c82dfb60ee31d821c505e233ea00/pkg/sql/executor_opt_interface.go#L30)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

If this code is only used for testing it seems like it should go in `testutils` or some other place...
</blockquote></details>

`execEngine` is used by the executor, just not through this interface. It's just this function that's testing-only (and moving it into a separate package would be tricky, we'd have to export other stuff)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22598)*

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22598#-L5AQsrfCXys6sGgqIvK:-L5AXDgWYA3oScyJNOA6:b2nhlkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1b640e68a0c82dfb60ee31d821c505e233ea00/pkg/sql/executor_opt_interface.go#L30)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`execEngine` is used by the executor, just not through this interface. It's just this function that's testing-only (and moving it into a separate package would be tricky, we'd have to export other stuff)
</blockquote></details>

Ok!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22598#-:-L5AXQ0yrnX2a_MsWC4p:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22598#-:-L5Fn0SLElzSRKxzvR_r:bnfp4nl)*

**Pull request merged**
