### PR TITLE
server: include more heap info in runtime stats

### PR DESCRIPTION
**Pull request by andreimatei**
This patch includes a few more memory stats in the runtime infor that we
log periodically. This is to attempt to clarify the relationship between
the go heap and the go "total" more. For example, currently you see
lines like this:
runtime stats: 13 GiB RSS, 544 goroutines, 5.3 GiB/3.6 GiB/8.2 GiB GO alloc/idle/total

The relationship between the idle and the total is ambiguous; some part
of idle is included, but another part (HeapReleased) was already
released to the OS and not included. By printing more, we'll hopefully
disambiguate, as well as get info on Go heap "fragmentation" - space
reserved in the heap spans but not currently in use.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
I feel that the updated log line will just be more confusing all we did is add more numbers. For example, can we subtract `HeapReleased` from `total` and end up with better numbers? The docs indicate that that's the real thing to look at:

```
// HeapIdle minus HeapReleased estimates the amount of memory
// that could be returned to the OS, but is being retained by
// the runtime so it can grow the heap without requesting more
// memory from the OS. If this difference is significantly
// larger than the heap size, it indicates there was a recent
// transient spike in live heap size.
HeapIdle uint64
```

It always takes me an hour to get familiar again with all the different memory counters and how they all play together. I don't want to force that upon anyone wishing to make sense of the runtime stats line. That line should be dumbed down as much as possible.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-:-MLlREF34tXQo1T3Lppt:b-68vizr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

**Review by knz — COMMENTED** [review]
FWIW there are now `memstat....txt` files generated in `logs/heap_profiler` which contain this information, also populated every 10s. Do we need to duplicate this info in the log file?

(I am tempted to suggest that yes, we could include it, but I wouldnt' mind having it on a different log line)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-:-MLmO2ZZ0HWhhYBZPW89:b26fyyc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

**Review by bdarnell — COMMENTED** [review]
> Do we need to duplicate this info in the log file?

I think duplicating at least basic stats in the log file is useful. We get log files (including fragments) a lot more often than we get full debug zips or heap profiles.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-:-MLn55me31oC_q0YpzYq:b-xnon8m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/server/status/runtime.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLn-1fm9AGU2PgPGWCn:-MLn-1fm9AGU2PgPGWCo:b-qz3unx) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee2922d602a23b0dd54ae3947e920201cf0e10c/pkg/server/status/runtime.go#L525)):*
> ```Go
> 		"runtime stats: %s RSS, %d goroutines, "+
> 			"%s/%s/%s GO alloc/idle/total%s "+
> 			"(HeapInuse: %s, HeapReleased: %s StackSys: %s), "+
> ```

It's weird that the formatting is different from the first three stats to the second. It may be more clear to use the latter key/value format for everything. Or maybe show an alloc/total ratio as the headline number (parallel to the cgo version) and demote "idle" into the parenthetical. Should we promote "InUse" to the top level stat instead of "alloc"?

What are the problems with the existing log line that we're trying to solve here? The gap between `go total + cgo total` and rss? The gap between `go alloc` and `go total`? 

My take after reviewing the MemStats docs is that we definitely want to include stack usage (and this could be a major chunk of missing memory. Bikeshed: I'd put this next to the goroutine count). I think that HeapReleased might be useful at explaining the difference between "go total" and RSS, but if that's the case maybe we should just stop subtracting it from Sys to compute the total. I don't feel like the internal stats like idle and inuse are very useful.

**Review by andreimatei — COMMENTED** [review]
> For example, can we subtract HeapReleased from total and end up with better numbers?

We already are: `goTotal := ms.Sys - ms.HeapReleased`. Maybe you meant something else. I've changed some figures, though. PTAL.

> It always takes me an hour to get familiar again with all the different memory counters and how they all play together.

For real bro. In a rando github comment I've seen somewhere, "they" have promised that a better API is coming, so maybe the situation will improve.

> That line should be dumbed down as much as possible.

Well, I'd say the line should aim to bring some intuitive quantities forward, but also print other figures that can help on occasion.

> I think duplicating at least basic stats in the log file is useful.

I too want this in stuff periodically in the log (hence this patch). Besides sometimes just having logs, I like that the info is single lines in the same file. The memstat files are one file per measurement, which is a lot harder to eyeball and track over time. Plus the memstats are only written sometimes - once per hour and whenever a new RSS highwater mark is set. I dunno, I basically like these log lines.
I think it'd be nice if we had them going to a separate log file, but I'm too lazy to do that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-:-MLoLBYdB59SNeH9iPys:blnne3d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/server/status/runtime.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLn-1fm9AGU2PgPGWCn:-MLoDmLi0Hi_eUAWN_H7:b1alprx) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee2922d602a23b0dd54ae3947e920201cf0e10c/pkg/server/status/runtime.go#L525)):*
> What are the problems with the existing log line that we're trying to solve here? The gap between go total + cgo total and rss? The gap between go alloc and go total?

Mostly the latter.


> maybe show an alloc/total ratio as the headline number (parallel to the cgo version) and demote "idle" into the parenthetical.

Done.

> Should we promote "InUse" to the top level stat instead of "alloc"?

I wouldn't... I'd leave "alloc"(`HeapAlloc`) up front, on the argument that `HeapAlloc` is supposed to correspond more to live objects and to what you see in a heap profile (although in practice it doesn't...). At least maybe if you look at a sequence of `HeapAlloc` measurements and take the one that happens immediately after a GC cycle, maybe that one doesn't include any garbage. Although the comment on `HeapAlloc` says that sweeping happens in between GC cycles and so the `HeapAlloc` quantity changes smoothly... 

>  Bikeshed: I'd put this (stacks) next to the goroutine count

Done

>  I think that HeapReleased might be useful at explaining the difference between "go total" and RSS, but if that's the case maybe we should just stop subtracting it from Sys to compute the total.

Well but I don't really see a discrepancy between "go total" (+cgo total) and RSS. If anything, the RSS is lower than that sum. Which makes me conclude that our RSS measurement includes HeapReleased. And even if it doesn't include it now, I think it will definitely include it in go 1.16 after the runtime [switches back to `madv_dontneed`](https://github.com/golang/go/issues/42330).
So I'd keep subtracting it from Sys to compute the total. I see `HeapReleased` as virtual address space with no backing - which should be mostly ignored (but I'd keep printing it in case I'm wrong).

> I don't feel like the internal stats like idle and inuse are very useful.

Even if they're not that useful, I don't think they hurt... But I think that they might prove useful. How about this: instead of printing inuse and idle, I'm now printing:
`HeapInuse - HeapAlloc` as "heap fragmentation" and `HeapIdle - HeapReleased` as "heap reserved". Maybe these are more intuitive quantities.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/server/status/runtime.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLn-1fm9AGU2PgPGWCn:-MLql6RI0SH198eQAk6S:b-uh30a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee2922d602a23b0dd54ae3947e920201cf0e10c/pkg/server/status/runtime.go#L525)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> What are the problems with the existing log line that we're trying to solve here? The gap between go total + cgo total and rss? The gap between go alloc and go total?

Mostly the latter.


> maybe show an alloc/total ratio as the headline number (parallel to the cgo version) and demote "idle" into the parenthetical.

Done.

> Should we promote "InUse" to the top level stat instead of "alloc"?

I wouldn't... I'd leave "alloc"(`HeapAlloc`) up front, on the argument that `HeapAlloc` is supposed to correspond more to live objects and to what you see in a heap profile (although in practice it doesn't...). At least maybe if you look at a sequence of `HeapAlloc` measurements and take the one that happens immediately after a GC cycle, maybe that one doesn't include any garbage. Although the comment on `HeapAlloc` says that sweeping happens in between GC cycles and so the `HeapAlloc` quantity changes smoothly... 

>  Bikeshed: I'd put this (stacks) next to the goroutine count

Done

>  I think that HeapReleased might be useful at explaining the difference between "go total" and RSS, but if that's the case maybe we should just stop subtracting it from Sys to compute the total.

Well but I don't really see a discrepancy between "go total" (+cgo total) and RSS. If anything, the RSS is lower than that sum. Which makes me conclude that our RSS measurement includes HeapReleased. And even if it doesn't include it now, I think it will definitely include it in go 1.16 after the runtime [switches back to `madv_dontneed`](https://github.com/golang/go/issues/42330).
So I'd keep subtracting it from Sys to compute the total. I see `HeapReleased` as virtual address space with no backing - which should be mostly ignored (but I'd keep printing it in case I'm wrong).

> I don't feel like the internal stats like idle and inuse are very useful.

Even if they're not that useful, I don't think they hurt... But I think that they might prove useful. How about this: instead of printing inuse and idle, I'm now printing:
`HeapInuse - HeapAlloc` as "heap fragmentation" and `HeapIdle - HeapReleased` as "heap reserved". Maybe these are more intuitive quantities.


</blockquote></details>

It looks like Ben is on board with making these stats here more extensive so I won't push back more, but, once you've settled down with him on something useful, please leave an exhaustive code comment on the chosen quantities and the signal they provide. I also share Ben's take that the current format is unintuitive and should see some streamlining.

On the whole, I look forward to getting more out of the runtime stats, so appreciate your work on this.
___
*[pkg/server/status/runtime.go, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLqlbP2ENXfv1JMksH5:-MLqlbP2ENXfv1JMksH6:b-m28mg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdb8dcfc1bd1b1b523a7bd56ba16d4a8e0fb27f/pkg/server/status/runtime.go#L522)):*
> ```Go
> 	// returns a safe value and collapse the entire log.Infof -> Safe ->
> 	// Sprintf sequence as a flat Infof call.
> 	log.Infof(ctx, "%s", redact.Safe(fmt.Sprintf(
> ```

It's hard enough to match up the placeholders with the variables here so consider using a template here:

```go
const tpl = `runtime stats: {{.RSS}}, {{.NumGoroutines}} goroutines (stacks: {{.StackBytes}}), `+
`{{.HeapAlloc}}/{{.SysMinusHeapReleased}} Go alloc/total{{.StaleMsg}} `+
`(heap fragmentation: {{.HeapInuseMinusAlloc}} heap reserved: {{.HeapIdleMinusReleased}} heap released: {{.HeapReleased}}), `+
`...`
template.Must(template.New("runtime stats").Parse(tpl).Execute(...)
```

**Review by andreimatei — COMMENTED** [review]
@bdarnell please give this another look


Looks like:
```
I201120 00:37:30.793824 80 server/status/runtime.go:552 ⋮ [n1] runtime stats: 98 MiB RSS, 283 goroutines (stacks: 4.2 MiB), 21 MiB/52 MiB Go alloc/total (heap fragmentation: 6.6 MiB, heap reserved: 8.7 MiB, heap released: 23 MiB), 9.9 MiB/21 MiB CGO alloc/total (14.4 CGO/sec), 1.3/0.9 %%(u/s)time, 0.0 %%gc (0x), 16 KiB/49 KiB (r/w)net
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-:-MMY4Wzo6m4dqSYqUADo:bezujn3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/server/status/runtime.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLn-1fm9AGU2PgPGWCn:-MMY2A_w3v42n43Nkcm3:b-lyjrc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eee2922d602a23b0dd54ae3947e920201cf0e10c/pkg/server/status/runtime.go#L525)):*
> please leave an exhaustive code comment on the chosen quantities and the signal they provide

Unfortunately this is easier said than done. I don't have anything to add to Go runtime's docs, and commenting the fields again I think can only be a disservice. Hopefully we'll get some insights that can be recorded around here.
___
*[pkg/server/status/runtime.go, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLqlbP2ENXfv1JMksH5:-MMY24ht8ppM5mSHz5qO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdb8dcfc1bd1b1b523a7bd56ba16d4a8e0fb27f/pkg/server/status/runtime.go#L522)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's hard enough to match up the placeholders with the variables here so consider using a template here:

```go
const tpl = `runtime stats: {{.RSS}}, {{.NumGoroutines}} goroutines (stacks: {{.StackBytes}}), `+
`{{.HeapAlloc}}/{{.SysMinusHeapReleased}} Go alloc/total{{.StaleMsg}} `+
`(heap fragmentation: {{.HeapInuseMinusAlloc}} heap reserved: {{.HeapIdleMinusReleased}} heap released: {{.HeapReleased}}), `+
`...`
template.Must(template.New("runtime stats").Parse(tpl).Execute(...)
```


</blockquote></details>

done

**Comment by jordanlewis** [comment]
Thanks for looking at this, very much appreciated. I like the new format and stats.

**Review by knz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/server/status/runtime.go, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLqlbP2ENXfv1JMksH5:-MMaHpxg-uOwH6TGP-pT:b-bohyed) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdb8dcfc1bd1b1b523a7bd56ba16d4a8e0fb27f/pkg/server/status/runtime.go#L522)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done
</blockquote></details>

Sorry tobias - this was not a great idea.

You are introducing a regression here - the information was previously properly non-redactable, and now it has become sensitive.

There are two problems here:

- the redact package does not know anything about templates (yet).

- if you simply mark the entire string blob as "safe", that will negate the protection against future mistakes that the machinery is supposed to provide: there won't be guardrails against a future maintainer adding sensitive information to the string by mistake.

(Besides - the entire templating machinery is extremely allocation-heavy. I appreciate we don't log this every millisecond, but still. )
___
*[pkg/server/status/runtime.go, line 552 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MMaIESS-NZ7zSaxwOUV:-MMaIESS-NZ7zSaxwOUW:b-hyh1zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8015a73084d553a43a77d3d692d78ee1ad9643ab/pkg/server/status/runtime.go#L552)):*
> ```Go
> 		log.Warningf(ctx, "failed to render runtime stats: %s", err)
> 	}
> 	log.Info(ctx, buf.String())
> ```

me, as the linter: "I can't let you do that, steve"

It's `log.Info(ctx, "%s", buf.String())` which emphasizes what I wrote above

**Comment by tbg** [comment]
Oops, sorry about that Andrei.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/server/status/runtime.go, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-MLqlbP2ENXfv1JMksH5:-MMaOPQg3cFvTwNBPG_2:b-hzhhk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdb8dcfc1bd1b1b523a7bd56ba16d4a8e0fb27f/pkg/server/status/runtime.go#L522)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Sorry tobias - this was not a great idea.

You are introducing a regression here - the information was previously properly non-redactable, and now it has become sensitive.

There are two problems here:

- the redact package does not know anything about templates (yet).

- if you simply mark the entire string blob as "safe", that will negate the protection against future mistakes that the machinery is supposed to provide: there won't be guardrails against a future maintainer adding sensitive information to the string by mistake.

(Besides - the entire templating machinery is extremely allocation-heavy. I appreciate we don't log this every millisecond, but still. )
</blockquote></details>

come on bro, don't kill me with this redaction stuff. This log line is never gonna be sensitive.

**Comment by knz** [comment]
>  This log line is never gonna be sensitive.

Says who?

It's also a matter of principle btw - we're setting up infrastructure for generations of maintainers to come. IT would be better if we don't litter the project with exceptions to the rules we're trying to put in place.

Maybe the lesson learned here is "build a templating facility in the `redact` package" and I'd be a-OK with that, but "please not right now". 

cheers

**Comment by andreimatei** [comment]
Says common sense, I would argue.
The principle is that you don't want to make redaction too tedious. You don't need to delegate all decisions about what's safe and what's not to the leaves of datastructures - like the current `TODO(knz): make utility wrapper around humanize.IBytes that returns a safe value` comment is implying; you can trust higher-level code to decree by fiat that "this whole crap is safe". Which also ties into #56933 where we're about to argue if it's OK to use `SafeValue` for a `Server.Config`. Yesterday I was looking at the logs produced by a server startup and I noticed that everything and its mother is redacted, and so I've opened that PR to try my hand and see what the experience of correcting one or two instances is. So far, the experience has not been great. I'm unsure what to do at every step, I don't really know where to look for guidance, and I'm not really interested in rewriting `String()` for a bunch of structs as it's just busy work.

Now rant over and back to this template. Here's how I see it: whatever API we provide, mistakes will be possible. If instead of the template we're arguing about here we'd use, say, a `redact.StringBuilder` and do 100 `builder.SafeString()` calls, then someone from the generations of maintainers to come might well copy-pasta one such call with some sensitive information in it. So all we can do is strive to minimize the chance of mistakes. And given how hard to conceive is for this template to ever get anything sensitive in it and, at the same time, for the person adding that sensitive data to not realize that this is printed unredacted, I think we're doing quite well on minimizing the chance for a mistake.
Let's also look at how the code is currently - a big-ass format string inside a `redact.Safe()`. It's just as easy for something sensitive to slip in there.

**Comment by knz** [comment]
> Yesterday I was looking at the logs produced by a server startup and I noticed that everything and its mother is redacted, and so I've opened that PR to try my hand and see what the experience of correcting one or two instances is. So far, the experience has not been great.

That is valuable feedback. The key question for me is "where do we go from there". 

Back in the days we evaluated alternatives. I personally see less intrusive approaches if we had access to a code preprocessor or a better type system (in particular, traits). But Go doesn't have that. I don't know myself how to do something better than what we did. But that doesn't mean that someone (maybe you) can't come along and propose something better.

The things to care about though are clear:

- we need to be extremely conservative. What we are selling customers comes in the neighborhood of "CRL would shut down if there's a bug in there".

- people make mistakes, *a lot*. All engineers just make mistakes and try to expedite their business. So the frameworks / tools we build must enforce whatever rules we define, automatically and thoroughly.

> And given how hard to conceive is for this template to ever get anything sensitive in it and, at the same time, for the person adding that sensitive data to not realize that this is printed unredacted, I think we're doing quite well on minimizing the chance for a mistake.

1) This function is already more than 10 LOCs long. Research tends to suggest that folk don't have an attention span larger than that. So yes, someone could modify the start of the function without looking at the end of it. How do you block this?

2) (This is actually an answer to the point above) All this output we're discussed here **does not have unit tests currently**. I believe in the power of feedback by unit test failures: someone who would go through the pain of updating the manual reference output in a unit test and would notice data outside of redaction markers, would be incentivized to think about this. **But there are no unit tests today on this output.** Maybe that's what's missing here.

> Let's also look at how the code is currently - a big-ass format string inside a redact.Safe(). It's just as easy for something sensitive to slip in there.

That is a mistake and a bug. I had noticed it the first time around but forgot to put a TODO. We can fix that independently of the conversation above.

**Review by bdarnell — APPROVED** [review]
:lgtm: 

On the question of principle, I agree with Andrei. We shouldn't let purism around our redaction scheme drive the structure of this code. I don't see a risk of this line becoming sensitive in the future. 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56468#-:-MMq1izU6JEhM2C1Pjf4:b-vv8hf6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

**Comment by andreimatei** [comment]
TFTRs!

bors r+

**Pull request merged**
