### PR TITLE
sql: refactor Ingest (previously called Import)

### PR DESCRIPTION
**Pull request by danhhz**
Trying to tighten up the terminology a bit, we're now calling what a user does
"import" and the bulk addition of data "ingest".

Also make Ingest take a path and a key range in Ingest instead of passing in a
RocksDBSstFileReader with all the files pre-added.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9375)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/backup.go, line 325 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-KRe9GF6EtC_X2hLAgJw:-KRe9GF6EtC_X2hLAgJx:bbi5fzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccfc4b5865f22ac39563eb55d98d11cf720448a/sql/backup.go#L325)):*
> ```Go
> 	// This loop makes restoring multiple tables O(N*M), where N is the number
> 	// of tables and M is the number of ranges. We could reduce this using an
> 	// interval tree if necessary.
> ```

I don't understand how an interval tree helps here.

---

*[sql/backup.go, line 327 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-KRe9DdNGZmEHMXGrpoM:-KRe9DdNGZmEHMXGrpoN:b-p4kiqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccfc4b5865f22ac39563eb55d98d11cf720448a/sql/backup.go#L327)):*
> ```Go
> 	// interval tree if necessary.
> 	for _, r := range ranges {
> 		if len(r.Path) == 0 {
> ```

When does this happen?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375)*

**Comment by paperstreet** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/backup.go, line 325 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-KRe9GF6EtC_X2hLAgJw:-KReCvDyAxqA78wS5Kd8:b-cilx4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccfc4b5865f22ac39563eb55d98d11cf720448a/sql/backup.go#L325)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I don't understand how an interval tree helps here.
</details>
You can construct an interval tree of the ranges and then you have M lookups that are O(log N)

---

*[sql/backup.go, line 327 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-KRe9DdNGZmEHMXGrpoM:-KReCOQeMI7TO-o5__ey:b-pqb6qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccfc4b5865f22ac39563eb55d98d11cf720448a/sql/backup.go#L327)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> When does this happen?
</details>
If the range is empty, we don't write an sstable (because it's an invalid sstable, apparently). https://github.com/cockroachdb/cockroach/blob/90ca039cbe24d862e3f85bb6661a7329ab12a334/sql/backup.go#L155-L161

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/backup.go, line 327 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-KRe9DdNGZmEHMXGrpoM:-KRePOBg31Z1k0jbq3wY:b-bajbcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccfc4b5865f22ac39563eb55d98d11cf720448a/sql/backup.go#L327)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> If the range is empty, we don't write an sstable (because it's an invalid sstable, apparently). https://github.com/cockroachdb/cockroach/blob/90ca039cbe24d862e3f85bb6661a7329ab12a334/sql/backup.go#L155-L161
</details>
I mean in what scenario will such a range be created? Or is this protection against something that probably shouldn't ever happen but might?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375)*

**Comment by paperstreet** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/backup.go, line 327 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-KRe9DdNGZmEHMXGrpoM:-KReS7pjn1zWuhUJgygM:b-5m71vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccfc4b5865f22ac39563eb55d98d11cf720448a/sql/backup.go#L327)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I mean in what scenario will such a range be created? Or is this protection against something that probably shouldn't ever happen but might?
</details>
Happens all the time in some of the system keyranges. I haven't looked into why. Now that we let users split tables, we definitely need to protect it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-:-KRhg8GkRJ0oD1kbBu3Y:bnfp4nl)*

**Comment by paperstreet** [comment]
Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9375#-:-KRiHoj7tQ8qHH4YDhdx:b-ucfknh)*

**Pull request merged**
