### PR TITLE
sql: rename EXPLAIN BUNDLE to EXPLAIN ANALYZE (DEBUG)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: clean up Explain AST

This change cleans up tree.Explain by parsing the options upfront and storing
the ExplainOptions directly. This change will make it easier to rename EXPLAIN
BUNDLE.

Release note: None

#### sql: rename EXPLAIN BUNDLE to EXPLAIN ANALYZE (DEBUG)

This change renames the EXPLAIN BUNDLE statement to
EXPLAIN ANALYZE (DEBUG).
We agreed on this syntax to avoid adding a new top-level keyword, and because
the statement has similar behavior with ANALYZE in that it executes the query.

The plan is to fold this back (for 20.2) into `EXPLAIN ANLYZE` which will be
changed to return more information than just a diagram.

Release note (sql change): Renamed EXPLAIN BUNDLE statement to
EXPLAIN ANALYZE (DEBUG).

Release justification: improvement in new functionality.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @awoods187

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46534#-:-M3GXOVA0YVXqBzbyLdU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/sem/tree/explain.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46534#-M3GTlOi8vgCJOKiRu7-:-M3GTlOi8vgCJOKiRu70:b-m0iyxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/255037244d8a46e5dd8a93007787789257fbbdb6/pkg/sql/sem/tree/explain.go#L47)):*
> ```Go
> 	// ExplainDistSQL shows the physical distsql plan for a query and whether a
> 	// query would be run in "auto" DISTSQL mode. See sql/explain_distsql.go for
> 	// details. Depending on ANALYZE, the plan can also be executed.
> ```

[nit] I'd say "If the ANALYZE option is included, the plan is also executed"
___
*[pkg/sql/sem/tree/explain.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46534#-M3GUAJI0TkQsiiYuQnj:-M3GUAJI0TkQsiiYuQnk:b-mai332) ([raw file](https://github.com/cockroachdb/cockroach/blob/255037244d8a46e5dd8a93007787789257fbbdb6/pkg/sql/sem/tree/explain.go#L58)):*
> ```Go
> 	ExplainVec
> 
> 	numExplainModes
> ```

this is a bit misleading -- it's actually one more than the number of explain modes
___
*[pkg/sql/sem/tree/explain.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46534#-M3GUKGd3sgRHVdnjNeO:-M3GUKGd3sgRHVdnjNeP:b-pb2ywa) ([raw file](https://github.com/cockroachdb/cockroach/blob/255037244d8a46e5dd8a93007787789257fbbdb6/pkg/sql/sem/tree/explain.go#L77)):*
> ```Go
> 
> func (m ExplainMode) String() string {
> 	if m == 0 || m > numExplainModes {
> ```

m >= numExplainModes
___
*[pkg/sql/sem/tree/explain.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46534#-M3GUehBAexMHW4r0snc:-M3GUehC5YrWDLZEt2bo:b7vsrro) ([raw file](https://github.com/cockroachdb/cockroach/blob/255037244d8a46e5dd8a93007787789257fbbdb6/pkg/sql/sem/tree/explain.go#L94)):*
> ```Go
> 	ExplainFlagEnv
> 	ExplainFlagCatalog
> 	numExplainFlags
> ```

Same comment as above -- it's one more than the number of flags
___
*[pkg/sql/sem/tree/explain.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46534#-M3GUYQr07i7s8N0lfvV:-M3GUYQr07i7s8N0lfvW:blwu5ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/255037244d8a46e5dd8a93007787789257fbbdb6/pkg/sql/sem/tree/explain.go#L116)):*
> ```Go
> 
> func (f ExplainFlag) String() string {
> 	if f == 0 || f > numExplainFlags {
> ```

f >= numExplainFlags

**Pull request merged**
