### PR TITLE
cli: skip TestUnavailableZip

### LINKED ISSUE #107738: cli: TestUnavailableZip flakes
1: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11089094?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

2: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11087369?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-30178

### PR DESCRIPTION
**Pull request by lidorcarmel**
Epic: none
Fixes: #107738

Release note: None

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]

**Review by herkolategan — APPROVED** [review]

**Comment by lidorcarmel** [comment]
thanks Aditya!

**Comment by rafiss** [comment]
It is incorrect that this PR "fixes" https://github.com/cockroachdb/cockroach/issues/107738. The test is still skipped, so that issue should remain open.

**Comment by lidorcarmel** [comment]
blathers backport 23.1

**Pull request merged**
