### PR TITLE
sql/ir: use a special character to highlight metavars in templates

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by petermattis** [comment]
The use of the special character is interesting, though I'm not sure if the need is compelling enough to justify the usage. A unique prefix would also suffice.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18398#-:-KtvslT_0AEN6ine3AbR:bl6p377)*

**Comment by knz** [comment]
Do you have a better suggestion?

**Comment by petermattis** [comment]
Does the template code need to be valid go code? If not, I'd use something like `<numRefsPerNode>`. If the template code does need to be valid go code, perhaps something like `META_numRefsPerNode`. 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18398#-:-Ku4zheZZqsoqtgFlERA:bz2atx1)*

**Comment by justinj** [comment]
I can see an argument against having "normal" characters given that metavariables could occur anywhere, including in strings. Does seem like a bit of a pain to work with though... I don't have a suggestion for something that would solve both problems short of moving to a homoiconic language :) so I'll give a weak +1 to using the unicode character, personally.

**Comment by knz** [comment]
Superseded by #19135.

**Pull request closed without merging**
