### PR TITLE
colexec: add DiskQueue to HashRouter

### LINKED ISSUE #44217: colexec: add DiskQueue to HashRouter
This issue tracks adding DiskQueue usage to the HashRouter, which will allow the HashRouter to spill to disk.

### PR DESCRIPTION
**Pull request by asubiotto**
This commit adds a spillingQueue, which is a circular coldata.Batch buffer that
spills to disk using a DiskQueue if the number of items or total memory usage
exceeds a given limit. The HashRouter now uses this to spill all outputs to
disk.

In order to create a DiskQueue, related infrastructure such as access to an
engine.FS and the temporary storage path has been plumbed down.

Disk monitoring will be added in a subsequent PR.

Release note: None (mostly adds infrastructure for disk-spilling, future
commits will call the use of this infrastructure out)

Closes #44217

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Very nice work!

I have some comments and a bunch of nits, but nothing major stands out to me.

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-:-M-MdoNe2hPZsvB9cWat:b-2ipker)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/allocator.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MTfZPCKmzJ2-olRPb:-M-MTfZPCKmzJ2-olRPc:b-pdonik) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/allocator.go#L72)):*
> ```Go
> // need to be used regularly, since most memory accounting necessary is done
> // through PerformOperation. Use this if you want to explicitly manage memory
> // accounted.
> ```

(nit): the end of the last sentence seems broken.
___
*[pkg/sql/colexec/execplan.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MU8qMC3Au6A2GSR-R:-M-MU8qMC3Au6A2GSR-S:b8fu7al) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/execplan.go#L950)):*
> ```Go
> // These should only be used when spilling to disk and an operator is made aware
> // of a memory usage limit separately.
> // The receiver is updated to have references to the unlimited memory monitor.
> ```

(nit): `s/references/reference/g`.
___
*[pkg/sql/colexec/routers.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MUMAQ0TzSQ9kInOxB:-M-MUMAQ0TzSQ9kInOxC:b-xp4neg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L76)):*
> ```Go
> 
> 	testingKnobs struct {
> 		// alwaysFlush, if set to true will always flush o.mu.pendingBatch to
> ```

(nit): `s/true will/true, will/g`.
___
*[pkg/sql/colexec/routers.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MUSEk5m-0N2Q-ZIRt:-M-MUSEk5m-0N2Q-ZIRu:b-v5t1h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L106)):*
> ```Go
> // newRouterOutputOp creates a new router output. The caller must ensure that
> // unblockedEventsChan is a buffered channel, as the router output will write to
> // it. The provided allocator must be not have a hard limit. The passed in
> ```

"must be not have".
___
*[pkg/sql/colexec/routers.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MUcoDDigV4CKqWtYp:-M-MUcoDDigV4CKqWtYq:bt2eka3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L110)):*
> ```Go
> // when it is exceeded.
> func newRouterOutputOp(
> 	allocator *Allocator,
> ```

It might be worth renaming `allocator` to `unlimitedAllocator` (I used this convention in the external sorter).
___
*[pkg/sql/colexec/routers.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MV3Yv3U8vwNU3OFEs:-M-MV3Yv3U8vwNU3OFEt:b-o8ilkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L163)):*
> ```Go
> 	var b coldata.Batch
> 	if o.mu.pendingBatch != nil && o.mu.data.empty() {
> 		// The only data available has not been flushed to the queue.
> ```

(nit): this sentence reads strangely to me, maybe something like "The only available data that has not been flush to the queue is in pendingBatch"?
___
*[pkg/sql/colexec/routers_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MXHpS7IAY8sDJlA9U:-M-MXHpS7IAY8sDJlA9V:bgoc32g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers_test.go#L50)):*
> ```Go
> // DiskQueueCfg that can be used to create a new DiskQueue. A cleanup function
> // is also returned as well as some default memory limits that are useful to
> // test with: 0 for an immediate spill a random memory limit up to 64 MiB, and
> ```

`s/immediate spill a random/immediate spill, a random/g`
___
*[pkg/sql/colexec/spilling_queue.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MYp6wD0kvsoVbIpSi:-M-MYp6wD0kvsoVbIpSj:b-74ryik) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L29)):*
> ```Go
> // are read from disk back into memory, that memory will be reclaimed.
> // NOTE: When a batch is returned, that batch's memory will still be tracked
> // using the allocator. Since the memory in use is fixed, a previously returned
> ```

"Since the memory in use is fixed" - this is not true for the variable-sizes types (i.e. bytes), right?
___
*[pkg/sql/colexec/spilling_queue.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-M_M2x3AGVPrWG9Zof:-M-M_M2x3AGVPrWG9Zog:bgmdwzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L51)):*
> ```Go
> 
> func newSpillingQueue(
> 	allocator *Allocator,
> ```

This is an unlimited allocator, right?
___
*[pkg/sql/colexec/spilling_queue.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-M_CLk4Wqxh27NnUOO:-M-M_CLk4Wqxh27NnUOP:bty6v56) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L55)):*
> ```Go
> 	memoryLimit int64,
> 	cfg colcontainer.DiskQueueCfg,
> 	batchSize int,
> ```

Is `batchSize` passed in mostly for testing purposes?
___
*[pkg/sql/colexec/spilling_queue.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MZEtAB1EbEy90D3_W:-M-MZEtAB1EbEy90D3_X:b-i0525z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L60)):*
> ```Go
> 	// writes/reads.
> 	memoryLimit -= int64(cfg.BufferSizeBytes)
> 	if memoryLimit < 0 {
> ```

Should we return an error if `memoryLimit` becomes negative? This would mean that we don't have enough memory for the buffer and we should bail, right?
___
*[pkg/sql/colexec/spilling_queue.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MaJOl2MOFmCfP4upj:-M-MaJOl2MOFmCfP4upk:berhpk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L117)):*
> ```Go
> 		// Note that there must be at least one element on disk.
> 		if q.curHeadIdx != q.curTailIdx {
> 			// TODO(asubiotto): Should these panics be errors?
> ```

I'd say it is a panic (although you should use `execerror.VectorizedInternalPanic` - the linter should complain :)).
___
*[pkg/sql/colexec/spilling_queue.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MbvE-6wFCVltGavQC:-M-MbvE-6wFCVltGavQD:b8rofwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L175)):*
> ```Go
> }
> 
> // isDone returns whether there are currently no items to be dequeued.
> ```

(nit): "isDone".
___
*[pkg/sql/colflow/vectorized_flow.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-McKlpD-dzgOBdmeQj:-M-McKlpD-dzgOBdmeQk:b-2ny46c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colflow/vectorized_flow.go#L118)):*
> ```Go
> 	}
> 	if err := f.Cfg.TempFS.DeleteDir(flowTempStoragePath); err != nil {
> 		// log error as a Warning but keep on going to close the memory
> ```

(nit): `s/log/Log/g`.
___
*[pkg/sql/colflow/vectorized_flow.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MccmDBC6z0Ona6tYS:-M-MccmDBC6z0Ona6tYT:b-tkn01h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colflow/vectorized_flow.go#L366)):*
> ```Go
> }
> 
> // createBufferingUnlimitedMemAccount instantiates an unlimited memory monitor.
> ```

`s/MemAccount/MemMonitor/g`.
___
*[pkg/sql/colflow/vectorized_flow.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-McmJ5El38Y4MdsBkB:-M-McmJ5El38Y4MdsBkC:bu5z265) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colflow/vectorized_flow.go#L369)):*
> ```Go
> // These should only be used when spilling to disk and an operator is made aware
> // of a memory usage limit separately.
> // The receiver is updated to have references to the unlimited memory monitor.
> ```

"references"
___
*[pkg/sql/logictest/logic.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MdVueAWKcT-d9L0sU:-M-MdVueAWKcT-d9L0sV:b-5mgkyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/logictest/logic.go#L484)):*
> ```Go
> 		overrideAutoStats:   "false",
> 		sqlExecUseDisk:      true,
> 		skipShort:           true,
> ```

We need to set `overrideVectorize` as well.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44776)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/allocator.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MTfZPCKmzJ2-olRPb:-M-QPKqwCF6LRMrodACx:bcyigrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/allocator.go#L72)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

(nit): the end of the last sentence seems broken.
</blockquote></details>

Done. (I think)
___
*[pkg/sql/colexec/execplan.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MU8qMC3Au6A2GSR-R:-M-QPWST5ttQZpVJMgP7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/execplan.go#L950)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

(nit): `s/references/reference/g`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/routers.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MUMAQ0TzSQ9kInOxB:-M-QPb6i3ui-et8H_C2X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L76)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

(nit): `s/true will/true, will/g`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/routers.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MUSEk5m-0N2Q-ZIRt:-M-QQXIUApPscc7LRMrF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L106)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

"must be not have".
</blockquote></details>

Done.
___
*[pkg/sql/colexec/routers.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MUcoDDigV4CKqWtYp:-M-QQXkXE5ehEPkmf5SN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L110)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It might be worth renaming `allocator` to `unlimitedAllocator` (I used this convention in the external sorter).
</blockquote></details>

Done.
___
*[pkg/sql/colexec/routers.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MV3Yv3U8vwNU3OFEs:-M-QQzYjEKtF8Q65bZ57:b4z5no4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L163)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

(nit): this sentence reads strangely to me, maybe something like "The only available data that has not been flush to the queue is in pendingBatch"?
</blockquote></details>

Done, better?
___
*[pkg/sql/colexec/routers_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MXHpS7IAY8sDJlA9U:-M-QRvWB1yMFNANSUJfA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers_test.go#L50)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`s/immediate spill a random/immediate spill, a random/g`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/spilling_queue.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MYp6wD0kvsoVbIpSi:-M-QStC4EQbPQSkuBIs3:b-jnosr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L29)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

"Since the memory in use is fixed" - this is not true for the variable-sizes types (i.e. bytes), right?
</blockquote></details>

Yeah, I think I was referring more to the number of items in `spillingQueue.items`.
___
*[pkg/sql/colexec/spilling_queue.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-M_M2x3AGVPrWG9Zof:-M-Qx8ET7ZLunYMaapRZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L51)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This is an unlimited allocator, right?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/spilling_queue.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-M_CLk4Wqxh27NnUOO:-M-QT0c75N2qVdIH4qdt:bf9tm9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L55)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is `batchSize` passed in mostly for testing purposes?
</blockquote></details>

Yeah, the router output has `outputBatchSize` which is set explicitly for some tests to test for handling those cases.
___
*[pkg/sql/colexec/spilling_queue.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MZEtAB1EbEy90D3_W:-M-QxL6q-AuvQU5BSq1C:b4b3rru) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L60)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Should we return an error if `memoryLimit` becomes negative? This would mean that we don't have enough memory for the buffer and we should bail, right?
</blockquote></details>

I don't think so at this stage, because we'll have a memory limit of 1 in logic tests. We've run into this a couple of times. It might make sense to replace a memory limit of 1 to mean "spill to disk" by a boolean that is more explicit. We should do this in another PR.
___
*[pkg/sql/colexec/spilling_queue.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MaJOl2MOFmCfP4upj:-M-Qy1DU82ZybB5JGImt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L117)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'd say it is a panic (although you should use `execerror.VectorizedInternalPanic` - the linter should complain :)).
</blockquote></details>

Done.
___
*[pkg/sql/colexec/spilling_queue.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MbvE-6wFCVltGavQC:-M-Qy50R7aOWiMSeNVee:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L175)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

(nit): "isDone".
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-McKlpD-dzgOBdmeQj:-M-Qy9Qm0jIRRxXWwzmc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colflow/vectorized_flow.go#L118)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

(nit): `s/log/Log/g`.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MccmDBC6z0Ona6tYS:-M-QyE4K48sOkpEYrJ2Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colflow/vectorized_flow.go#L366)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`s/MemAccount/MemMonitor/g`.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-McmJ5El38Y4MdsBkB:-M-QyHTM5rKAK5BwgqWd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colflow/vectorized_flow.go#L369)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

"references"
</blockquote></details>

Done.
___
*[pkg/sql/logictest/logic.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MdVueAWKcT-d9L0sU:-M-QyUBx1vMF9gpgI1m7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/logictest/logic.go#L484)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We need to set `overrideVectorize` as well.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44776)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/routers.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MV3Yv3U8vwNU3OFEs:-M-VI-GY-8BSS3nk8k0m:b-e5e2r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Done, better?
</blockquote></details>

Yes, thanks.

(nit): a comma before "but".
___
*[pkg/sql/colexec/spilling_queue.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MYp6wD0kvsoVbIpSi:-M-VIEgkDMcX3PkmBNga:b-tt02u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yeah, I think I was referring more to the number of items in `spillingQueue.items`.
</blockquote></details>

I see. I'd appreciate this clarification in the comment.
___
*[pkg/sql/colexec/spilling_queue.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MZEtAB1EbEy90D3_W:-M-VIehODIH8gWEKBiuS:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L60)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think so at this stage, because we'll have a memory limit of 1 in logic tests. We've run into this a couple of times. It might make sense to replace a memory limit of 1 to mean "spill to disk" by a boolean that is more explicit. We should do this in another PR.
</blockquote></details>

SGTM
___
*[pkg/sql/colflow/vectorized_flow.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-McKlpD-dzgOBdmeQj:-M-VItuN--vDPLrtwZjx:bi1va3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colflow/vectorized_flow.go#L118)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This one is not.
___
*[pkg/sql/logictest/logic.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MdVueAWKcT-d9L0sU:-M-VJ254DFwftFpzCjFP:bbmvaas) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/logictest/logic.go#L484)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It should be `experimental_on`.
___
*[pkg/storage/diskmap/disk_map.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-VJ8XnDVOIDvmxx7Us:-M-VJ8XnDVOIDvmxx7Ut:bpbulxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd5fd63193a3e0893ab3dbb54658de49c7c705b9/pkg/storage/diskmap/disk_map.go#L80)):*
> ```Go
> 
> // SortedDiskMap is an on-disk map. Keys are iterated over in sorted order.
> type SortedDiskMap interface /**/ {
> ```

What is this change?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44776)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/routers.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MV3Yv3U8vwNU3OFEs:-M-VtJ5A55PelsWYo8KF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/routers.go#L163)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, thanks.

(nit): a comma before "but".
</blockquote></details>

Done.
___
*[pkg/sql/colexec/spilling_queue.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MYp6wD0kvsoVbIpSi:-M-Vt_0cAMJ-1XDrCQAA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/colexec/spilling_queue.go#L29)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I see. I'd appreciate this clarification in the comment.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/logic.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-MdVueAWKcT-d9L0sU:-M-VtqHDAUi6el7vwHgp:b-8td1tr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3e674d2b8d18e62bef7dc08dbb986acc90e55d7/pkg/sql/logictest/logic.go#L484)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It should be `experimental_on`.
</blockquote></details>

Oops, thanks.j
___
*[pkg/storage/diskmap/disk_map.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-M-VJ8XnDVOIDvmxx7Us:-M-Vtu3S2yOwesBHgnPv:btupv1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd5fd63193a3e0893ab3dbb54658de49c7c705b9/pkg/storage/diskmap/disk_map.go#L80)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What is this change?
</blockquote></details>

:man_shrugging:

**Review by yuzefovich — APPROVED** [review]
:lgtm: but the build is red :/

> Reviewed 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-:-M-W3uO4BtVnC0IiedRU:b4ut9jf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Comment by asubiotto** [comment]
@sumeerbhola could you please take a look at the first commit? It just move the `engine.FS` interface to its own package so that `sql` can use the interface without importing all of `engine`.

**Comment by asubiotto** [comment]
The rest of the nits should be fixed, although it seemed like some router tests were failing under race. Tried to reproduce locally with `stressrace` but no luck so far. Want to see if it's still failing on CI.

**Review by sumeerbhola — COMMENTED** [review]
> @sumeerbhola could you please take a look at the first commit? It just move the engine.FS interface to its own package so that sql can use the interface without importing all of engine.

looks good

> Reviewed 1 of 33 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44776#-:-M-l0vu_0xBoncGaGP-t:b3bm8bb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

**Comment by asubiotto** [comment]
OK, the build should be green now. The issue was that some tests were using `testAllocator` and checking that a spilling queue didn't spill. However, since the `testAllocator` is used and not cleared between tests, these tests had to explicitly clear the `testAllocator` otherwise the in-use memory threshold would be exceeded.

**Comment by asubiotto** [comment]
TFTR!

bors r=yuzefovich

**Pull request merged**
