### PR TITLE
sql: allow multiple UDFs with in-exact type parameters of the same family

### PR DESCRIPTION
**Pull request by il9ue**
This patch makes it possible for udf to check #94146 
exact type matching for udf parameters
Added TypeList.MatchExact to apply udf parameter check only.

- Unit test for such family type parameter matching are provided
- e2e test are applied on udf logictest

Release note: None

### CODE REVIEW

**Comment by il9ue** [comment]
Hi @mgartner Could you please give any feedback?

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @il9ue)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5_8SF73FyIteMXjqY):*
We'll need a release note here.
___
*[`pkg/sql/sem/tree/function_definition.go` line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5YNhJDLAZeH_hVxox:-NM5YNhJDLAZeH_hVxoy:b-lth3io) ([raw file](https://github.com/cockroachdb/cockroach/blob/22494ce9fd519b2b7b499d81130c958e5671f058/pkg/sql/sem/tree/function_definition.go#L279)):*
> ```Go
> ) (QualifiedOverload, error) {
> 	matched := func(ol QualifiedOverload, schema string) bool {
> 		if ol.IsUDF {
> ```

Can you leave a TODO here like:

```
TODO(mgartner/chengxiong-ruan): Differentiate between functions defined with `Body` and UDFs, now that we use `Body` for built-in functions.
```

cc @chengxiong-ruan 
___
*[`pkg/sql/sem/tree/overload.go` line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5WncoBWwuesJT57If:-NM5WncoBWwuesJT57Ig:b4jzx9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/22494ce9fd519b2b7b499d81130c958e5671f058/pkg/sql/sem/tree/overload.go#L285)):*
> ```Go
> 	Match(types []*types.T) bool
> 
> 	MatchParams(types []*types.T) bool
> ```

How about  naming this `MatchIdentical` instead?

And can you add a description for this function? Something like:

```
MatchIdentical is similar to match but checks that the types are identical matches, instead of equivalent matches. See types.T.Equivalent and types.T.Identical.
```
___
*[`pkg/sql/sem/tree/overload.go` line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5YFrr1vXuIk9uL7-2:-NM5YFrr1vXuIk9uL7-3:bghh5h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/22494ce9fd519b2b7b499d81130c958e5671f058/pkg/sql/sem/tree/overload.go#L291)):*
> ```Go
> 	MatchAt(typ *types.T, i int) bool
> 
> 	MatchParamAt(typ *types.T, i int) bool
> ```

How about `MatchAtIdentical`? 

Also, please add a description for this function.
___
*[`pkg/sql/sem/tree/overload.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5Zpl1Ee1aHqSXgCjg:-NM5Zpl1Ee1aHqSXgCjh:b-wwcdca) ([raw file](https://github.com/cockroachdb/cockroach/blob/22494ce9fd519b2b7b499d81130c958e5671f058/pkg/sql/sem/tree/overload.go#L331)):*
> ```Go
> }
> 
> func (p ParamTypes) MatchParams(types []*types.T) bool {
> ```

Add a comment like:

```
// MatchParams is part of the TypeList interface.
```

Here and the other implementations below.
___
*[`pkg/sql/sem/tree/overload.go` line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5_-2h8rsFO_3MF62e:-NM5_-2iAhBTmjArjcCv:bhhyz15) ([raw file](https://github.com/cockroachdb/cockroach/blob/22494ce9fd519b2b7b499d81130c958e5671f058/pkg/sql/sem/tree/overload.go#L473)):*
> ```Go
> 
> func (VariadicType) MatchParams(types []*types.T) bool {
> 	return true
> ```

We should probably leave a TODO here that this will be incorrect once we add support for variadic UDFs.
___
*[`pkg/sql/sem/tree/overload.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5_5FP6gHFx4E_7PlX:-NM5_5FP6gHFx4E_7PlY:bhhyz15) ([raw file](https://github.com/cockroachdb/cockroach/blob/22494ce9fd519b2b7b499d81130c958e5671f058/pkg/sql/sem/tree/overload.go#L485)):*
> ```Go
> 
> func (VariadicType) MatchParamAt(typ *types.T, i int) bool {
> 	return true
> ```

We should probably leave a TODO here that this will be incorrect once we add support for variadic UDFs.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 2804 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NM5WOM-4nvGRz6WbF3M:-NM5WOM-4nvGRz6WbF3N:b-hale66) ([raw file](https://github.com/cockroachdb/cockroach/blob/22494ce9fd519b2b7b499d81130c958e5671f058/pkg/sql/logictest/testdata/logic_test/udf#L2804)):*
> ```
> SELECT f_94146(3276700) -- check with int (bigger than smallInt)
> ----
> 10
> ```

Can you add some more tests like:

```sql
SELECT f_94146(1::INT2);

SELECT f_94146(1::INT4);

SELECT f_94146(1::INT8);
```

These should all execute successfully.

**Comment by il9ue** [comment]
Hi @mgartner 
Could you give a review again? I made some changes to the comments you made.
Thanks.

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @il9ue)

___
*[`pkg/sql/sem/tree/function_definition.go` line 280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NMPVnrvA6ufSpQzyH1E:-NMPVnrvA6ufSpQzyH1F:b8sr5a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc66c2741b868ebd92e46c747553c2ad4fa4c1eb/pkg/sql/sem/tree/function_definition.go#L280)):*
> ```Go
> 	matched := func(ol QualifiedOverload, schema string) bool {
> 		if ol.IsUDF {
> 			// TODO(mgartner/chengxiong-ruan): Differentiate between functions defined with `Body` and UDFs,
> ```

nit: wrap comments at 80 characters.
___
*[`pkg/sql/sem/tree/overload.go` line 292 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NMPVwEmBt51uLW71TJ6:-NMPVwEmBt51uLW71TJ7:b-oi9xw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc66c2741b868ebd92e46c747553c2ad4fa4c1eb/pkg/sql/sem/tree/overload.go#L292)):*
> ```Go
> 	MatchAt(typ *types.T, i int) bool
> 	// MatchAtIdentical is similar to MatchAt but checks that the type at index i of
> 	// the Typelist matches type typ.
> ```

nit: ".. the Typelist matches type typ" => ".. the Typelist is identical to typ."
___
*[`pkg/sql/sem/tree/overload.go` line 492 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NMPW8zF0qd6eP04YAwN:-NMPW8zF0qd6eP04YAwO:b-ddzf0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc66c2741b868ebd92e46c747553c2ad4fa4c1eb/pkg/sql/sem/tree/overload.go#L492)):*
> ```Go
> 
> // MatchAtIdentical is part of the TypeList interface.
> // TODO : This will be incorrect once we add support for variadic UDFs
> ```

nit: TODO => TODO(mgartner)
___
*[`pkg/sql/sem/tree/type_check.go` line 3036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NMPXFFD4TO_cXml2KeJ:-NMPXFFD4TO_cXml2KeK:btzgi0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc66c2741b868ebd92e46c747553c2ad4fa4c1eb/pkg/sql/sem/tree/type_check.go#L3036)):*
> ```Go
> 			matchIdx := -1
> 			fnSet := make(map[string]bool)
> 			fnSigs := fetchFuncSignature(expr.Func.String(), overloads, oImpls)
> ```

Can we use `MatchParamsIdentical` here instead of stringifying function signatures to resolve the ambiguity? 

Note that part of the problem here is that our function resolution isn't quite right (see #75101). In an ideal world we'd match the logic described here: https://www.postgresql.org/docs/14/typeconv-func.html But we don't have a concept of preferred types yet, which makes this difficult. So the best we can do is approximate it.

**Comment by il9ue** [comment]
@mgartner I've applied the changes you commented on. Could you review it?

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @il9ue)

___
*[`pkg/sql/sem/tree/type_check.go` line 3036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NMPXFFD4TO_cXml2KeJ:-NMec-ZX26lv2gxkLun-:b-89s3b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc66c2741b868ebd92e46c747553c2ad4fa4c1eb/pkg/sql/sem/tree/type_check.go#L3036)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can we use `MatchParamsIdentical` here instead of stringifying function signatures to resolve the ambiguity? 

Note that part of the problem here is that our function resolution isn't quite right (see #75101). In an ideal world we'd match the logic described here: https://www.postgresql.org/docs/14/typeconv-func.html But we don't have a concept of preferred types yet, which makes this difficult. So the best we can do is approximate it. 
</blockquote></details>

@il9ue Did you see my previous comment here? I think we should find a way to get the correct behavior without stringifying the type signature.
___
*[`pkg/sql/sem/tree/overload_test.go` line 491 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NMecI_33i_SBLNxUG8u:-NMecI_33i_SBLNxUG8v:b-tv4nxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b8389157cb43c8f29b513a10e495d17d119ce95/pkg/sql/sem/tree/overload_test.go#L491)):*
> ```Go
> 			}
> 			overload, err := getMostSignificantOverload(
> 				tc.overloads, impls, filters, tc.searchPath, &expr, nil,
> ```

nit: label the `nil` argument like `nil /* typedInputExprs */`

**Review by il9ue — COMMENTED** [review]
applied comments. Thanks for the review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-:-NMkZCBo6N7cKlEW0Bp6:b-4jao3d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/sem/tree/type_check.go` line 3036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NMPXFFD4TO_cXml2KeJ:-NMkYiewEOiyc64BVXNS:b-46bi6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc66c2741b868ebd92e46c747553c2ad4fa4c1eb/pkg/sql/sem/tree/type_check.go#L3036)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

@il9ue Did you see my previous comment here? I think we should find a way to get the correct behavior without stringifying the type signature.
</blockquote></details>

I've made changes without any stringify

**Comment by il9ue** [comment]
@mgartner Kind reminder, I've applied changes to your latest comment. Could you give any feedback on this?

**Review by mgartner — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @il9ue)

___
*[`-- commits` line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NNCbfNx64KOBN1obG8m):*
Can you add a release note? For example:

```
Release note (bug fix): A bug has been fixed that caused errors when creating
multiple user-defined functions with the same name and different argument
types in the same type family. For example, it was impossible to create both
function `f(INT2)` and `f(INT4)`.
```
___
*[`pkg/sql/sem/tree/type_check.go` line 3046 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NNCb-zn-9RFuP2dzYOi:-NNCb-zn-9RFuP2dzYOj:b-my5mec) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e36fc1b60559e4f2c3fc1c2626d0b932224930/pkg/sql/sem/tree/type_check.go#L3046)):*
> ```Go
> 				srcParams := candidate.params()
> 				if len(srcParams.Types()) == 0 {
> 					udfExactDup = true
> ```

Can you explain why this conditional checking for zero arguments is necessary? It's not obvious to me.

**Comment by mgartner** [comment]
Looks great, just left a few more comments. Also, you'll need to rebase your branch on the latest version of `master` and resolve the conflicts in `pkg/sql/logictest/testdata/logic_test/udf`.

**Comment by il9ue** [comment]
> > Reviewed 1 of 4 files at r2, 3 of 3 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95334)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @il9ue)
> 
> _[`-- commits` line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NNCbfNx64KOBN1obG8m):_ Can you add a release note? For example:
> 
> ```
> Release note (bug fix): A bug has been fixed that caused errors when creating
> multiple user-defined functions with the same name and different argument
> types in the same type family. For example, it was impossible to create both
> function `f(INT2)` and `f(INT4)`.
> ```
> 
> _[`pkg/sql/sem/tree/type_check.go` line 3046 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95334#-NNCb-zn-9RFuP2dzYOi:-NNCb-zn-9RFuP2dzYOj:b-my5mec) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e36fc1b60559e4f2c3fc1c2626d0b932224930/pkg/sql/sem/tree/type_check.go#L3046)):_
> 
> > ```go
> > 				srcParams := candidate.params()
> > 				if len(srcParams.Types()) == 0 {
> > 					udfExactDup = true
> > ```
> 
> Can you explain why this conditional checking for zero arguments is necessary? It's not obvious to me.

Sure. The srcParam length check was just needed to avoid regression unit test function "TestGetMostSignificantOverload", where prepared overloads have "ParamTypes{}" as the Types field. It seems that in real-life scenario it won't be necessary though.

**Comment by il9ue** [comment]
> Looks great, just left a few more comments. Also, you'll need to rebase your branch on the latest version of `master` and resolve the conflicts in `pkg/sql/logictest/testdata/logic_test/udf`.

Thanks for the review! Let me prepare another patchset and provide it once again soon.

**Comment by il9ue** [comment]
Sorry, let me come up with another patchset. Messed up during sync!

**Pull request closed without merging**
