### PR TITLE
sql: fix panic in plan gist decoding

### LINKED ISSUE #83537: sql: plan gist decoder panics when table in plan has been dropped
Here's a logic test showing the panic:

```
statement ok
CREATE TABLE t (k INT PRIMARY KEY, a INT)

let $gist
EXPLAIN (GIST) INSERT INTO t VALUES (1, 10)

statement ok
DROP TABLE t

statement ok
SELECT crdb_internal.decode_plan_gist('$gist')
```

The stack trace looks like:

```
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:755
*   | [...repeated from below...]
* Wraps: (2) while executing: SELECT crdb_internal.decode_plan_gist(_)
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:755
*   | runtime.gopanic
*   |   /usr/local/opt/go/libexec/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   /usr/local/opt/go/libexec/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   /usr/local/opt/go/libexec/src/runtime/panic.go:1038
*   | runtime.panicmem
*   |   /usr/local/opt/go/libexec/src/runtime/panic.go:221
*   | runtime.sigpanic
*   |   /usr/local/opt/go/libexec/src/runtime/signal_unix.go:735
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.(*emitter).emitNodeAttributes
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:755
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.Emit.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:53
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.Emit
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:66
*   | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.DecodePlanGistToRows
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:153
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).DecodeGist                                                                                             *   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:694
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.(*gistPlanGenerator).Start
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/generator_builtins.go:505
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).nextInputRow
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:171
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).Next
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:254
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:231
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:93
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:99
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:107
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:242
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:246
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
```

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: fix panic in plan gist decoding

Previously, the plan gist decoder would set tables and indexes to nil in
`exec.Node`s when they could not be decoded, which can happen when
tables or indexes are dropped. This could cause node-crashing panics
because `explain.Emit` assumes that `exec.Node`s never have nil tables
or indexes.

This commit fixes the issue assigning two new structs to `exec.Node`
fields instead of `nil`: `unknownTable` which implements `cat.Table` and
`unknownIndex` which implements `cat.Index`. This avoids nil pointer
exceptions when `explain.Emit` tries to access these fields.

Fixes #83537

Release note (bug fix): A bug has been fixed which could crash nodes
when visiting the console statements page. This bug was present since
version 21.2.0.

#### sql: move panic catcher in plan gist decoder

This commit moves the panic catcher in `DecodePlanGistToPlan` to its
calling function `DecodePlanGistToRows`. This allows panics originating
in `Emit` to be caught without crashing nodes.

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83541#-:-N5m6-3J1F4TwxxaU8it:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[`pkg/sql/opt/exec/explain/plan_gist_factory.go` line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83541#-N5m3jbh1Jvnf2o0DZHs:-N5m3jbh1Jvnf2o0DZHt:b-8upio5) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c372a3dd860bfae5c1557d87e720c3ccc6c143/pkg/sql/opt/exec/explain/plan_gist_factory.go#L291)):*
> ```Go
> 		}
> 	}
> 	return &unknownTable{}
> ```

nit: Maybe we should guard this with `if pgerror.GetPGCode(err) == pgcode.UndefinedTable` and otherwise `panic(err)` to avoid obscuring some other kind of error.

**Review by mgartner — COMMENTED** [review]
Added a new commit that moves some panic-catching logic. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83541#-:-N5pEF7N--vGCBUgoqnq:b-4sehag)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

___
*[`pkg/sql/opt/exec/explain/plan_gist_factory.go` line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83541#-N5m3jbh1Jvnf2o0DZHs:-N5pEEAvCwKcMP6rNaGT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c372a3dd860bfae5c1557d87e720c3ccc6c143/pkg/sql/opt/exec/explain/plan_gist_factory.go#L291)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Maybe we should guard this with `if pgerror.GetPGCode(err) == pgcode.UndefinedTable` and otherwise `panic(err)` to avoid obscuring some other kind of error.
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83541#-:-N5r2J3-8l1pRygqs6fI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by cucaroach — APPROVED** [review]
Dropping tables and indexes, how did I not think to test that?  Thanks @mgartner!  :lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83541#-:-N5tkKs75EzJ16mQP1Gk:b27xz74)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Pull request merged**
