### PR TITLE
sql: add support for exclusive BETWEEN intervals

### PR DESCRIPTION
**Pull request by benesch**
The SQL standard requires that BETWEEN a AND b specify the closed
interval [a, b]. Half-open ranges tend to be more useful; range
partitioning schemes for example, are more naturally expressed with
half-open ranges like [a, b).

So, introduce a syntax extension that allows either end of the interval
to be prefixed with a new keyword, EXCL, indicating that that end of the
interval should be open. The new BETWEEN syntax is:

    BETWEEN [ASYMMETRIC|SYMMETRIC] [EXCL] a AND [EXCL] b

This has an unfortunate side effect: EXCL must be a reserved_keyword to
avoid shift/reduce conflicts. Suggestions welcome.

Ignore the first two commits; those are just prep work.

/cc @jordanlewis @knz @danhhz bikeshed away!

### CODE REVIEW

**Comment by benesch** [comment]
By the way, I'm expecting this PR to serve as a mini-RFC about whether this is a good idea. The pro is that we can reuse this in table partitioning:

```sql
CREATE TABLE (a INT PRIMARY KEY) PARTITION BY RANGE (a) (
  PARTITION p1 VALUES BETWEEN 1 AND EXCL 2,
  PARTITION p2 VALUES BETWEEN 2 AND EXCL 3,
)
```

The alternative,

```
CREATE TABLE (a INT PRIMARY KEY) PARTITION BY RANGE (a) (
  PARTITION p1 VALUES >= 1 AND VALUES < 2
  PARTITION p2 VALUES >= 2 AND VALUES < 3
)
```

implies that we might support `OR`, too, or perhaps arbitrary expressions—which we certainly do not.

**Review by jordanlewis — COMMENTED** [review]
Code LG.

I think it would be better to make the syntax something like:

```
exp BETWEEN exp [ INCL[USIVE] | EXCL[USIVE] ] AND expr [ INCL[USIVE] | EXCL[USIVE] ]
```

This way it's a little more consistent with other SQL syntax, which generally tries to be "human-readable". It's more natural IMO to say `3 BETWEEN 1 AND 4 EXCLUSIVE` than `3 BETWEEN 1 AND EXCLUSIVE 4`. Also, you get the symmetric incl/excl and the ability to write out the whole word if you want.

**Comment by benesch** [comment]
Yeah, I also like putting the modifier after the argument, but someone (maybe @danhhz?) was worried about people interpreting `BETWEEN 1 AND 4 EXCLUSIVE` as `(1, 4)` instead of `[1, 4)` because you could reasonably expect the `EXCLUSIVE` to apply to both bounds. 

Also, agreed that `[INCL[USIVE] | EXCL[USIVE]]` would be ideal, but I'm worried about introducing more reserved keywords than absolutely necessary. Even one might be one too many; not sure what our backwards-compatibility guarantees are here.

**Comment by danhhz** [comment]
Yeah, it was me. I find `BETWEEN 1 AND 4 EXCLUSIVE` to be quite ambiguous, so :-1: on that. More thoughts: I like having the inclusive symmetry, but I feel like the full `INCLUSIVE` and `EXCLUSIVE` are too common to reserve.

**Comment by benesch** [comment]
Worked around this with custom partitioning syntax. Closing.

**Pull request closed without merging**
