### PR TITLE
storage/txnwait: don't leak waiting queries in MaybeWaitForQuery

### PR DESCRIPTION
**Pull request by nvb**
Fixes #28849.

The theorized leak in #28849 was almost spot on. I instrumented the original
code and pointed 6 workload generators running `tpcc` with `wait=false` at a
single node (adding more workers to a single workload generator wasn't as good
at creating contention). I was pretty quickly able to see the size of
`Queue.mu.queries` grow on a few hot ranges due to context cancellation in
`MaybeWaitForQuery`. It turns out that both context cancellation and the
internal timeout in `MaybeWaitForQuery` (`maxWaitCh`) could result in a memory
leak.

This change fixes this leak by doing a better job ensuring that waiters clean up
after themselves if they stop waiting prematurely. In doing so, it simplifies
the `waitingQueries` structure by changing it from a slice of channels and a
useless `*roachpb.QueryTxnRequest` (that exacerbated the leak and turned out to
be quite useful in debugging it) to a single refcounted channel. With this
structure, its straightforward for waiters to unregister prematurely and clean
up associated resources if necessary.

I could not reproduce the same behavior with `tpcc` after this change. I wasn't
able to get the size of `Queue.mu.queries` to grow without bound.

Release note (bug fix): Fix memory leak when contended queries time out.

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
LGTM

good fix

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-:-LKg_JD5DCsK4XCkI5NQ:b6pttkb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/txnwait/queue_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKg_PCS7qdD8BiipMiY:-LKg_PCS7qdD8BiipMiZ:b-4tkcog) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/queue_test.go#L132)):*
> ```Go
> // TestMaybeWaitForQueryWithContextCancellation adds a new waiting query to the
> // queue and cancels its context. It then verifies that the query was cleaned
> // up. This tests against the leak observed in #28849. The test would fail
> ```

nit: I don't think there references to the bug are necessary
___
*[pkg/storage/txnwait/txnqueue.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKgXMgZ97yMiLPU-iwd:-LKgXMgZ97yMiLPU-iwe:b-3m1fq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/txnqueue.go#L346)):*
> ```Go
> func (q *Queue) releaseWaitingQueriesLocked(ctx context.Context, txnID uuid.UUID) {
> 	if w, ok := q.mu.queries[txnID]; ok {
> 		if log.V(1) {
> ```

`VEventf` pls, and severity 2 seems more consistent with the waiting counterpart
___
*[pkg/storage/txnwait/txnqueue.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKg_fpT9mz7J6q6NiMc:-LKg_fpT9mz7J6q6NiMd:b-4pwopr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/txnqueue.go#L593)):*
> ```Go
> func (q *Queue) MaybeWaitForQuery(
> 	ctx context.Context, repl ReplicaInterface, req *roachpb.QueryTxnRequest,
> ) *roachpb.Error {
> ```

is there a reason why this returns `pErr`? It doesn't do any RPCs, does it? Consider switching it, which would also simplify the test.
___
*[pkg/storage/txnwait/txnqueue.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKgYo_z1JTCr-q0X_o9:-LKgYo_z1JTCr-q0X_oA:b-o3y1zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/txnqueue.go#L653)):*
> ```Go
> 	}()
> 
> 	if log.V(2) {
> ```

pls take the opportunity to make this a `VEventf`. Looks like an important message to me.

**Review by andreimatei — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-:-LKg_s_N73fvSLaNyHOP:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-:-LKhTOD4DfdUjpogJH5c:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/txnwait/queue_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKg_PCS7qdD8BiipMiY:-LKhRu5-0Wqvdd9aQj7p:b9fkocz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/queue_test.go#L132)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I don't think there references to the bug are necessary
</blockquote></details>

Eh, we do it all over the place, especially in storage:

```
$ git grep -B 5 'testing.T' | grep -E '#\d+' | wc -l
41
```

Reworded to include the term "regression test".
___
*[pkg/storage/txnwait/txnqueue.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKgXMgZ97yMiLPU-iwd:-LKhSDM9BhB9Mw-C0IDs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/txnqueue.go#L346)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`VEventf` pls, and severity 2 seems more consistent with the waiting counterpart
</blockquote></details>

Done.
___
*[pkg/storage/txnwait/txnqueue.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKg_fpT9mz7J6q6NiMc:-LKhSfdZ0CigHmsJTmgA:b-n65xjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/txnqueue.go#L593)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is there a reason why this returns `pErr`? It doesn't do any RPCs, does it? Consider switching it, which would also simplify the test.
</blockquote></details>

I don't disagree in principle, but `*roachpb.Error` is the error type used by the rest of this package's external interface because it can perform RPCs, so it should stay consistent. We can make them all `error`s, so I'm not going to make any.
___
*[pkg/storage/txnwait/txnqueue.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29025#-LKgYo_z1JTCr-q0X_o9:-LKhSfESAi6A0BGgYSrW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b805ae223193023321a696938286ab4e705353fa/pkg/storage/txnwait/txnqueue.go#L653)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls take the opportunity to make this a `VEventf`. Looks like an important message to me.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
Planning to backport to 2.0 and 2.1.

**Comment by tschottdorf** [comment]
Thanks @nvanbenschoten!

**Pull request merged**
