### PR TITLE
cli: remove deprecated "zone" commands

### PR DESCRIPTION
**Pull request by solongordon**
I removed the "cockroach zone" commands, which have been deprecated
since 19.1. This will facilitate some of the zone usability improvements
we are making for 19.2. I left the commands there but they now return an
error with the equivalent SQL command.

Refers #20880

Release note (cli change): Removed the deprecated "cockroach zone" CLI
commands. Please use the equivalent "SHOW ZONE" and "CONFIGURE ZONE"
commands in a SQL client.

### CODE REVIEW

**Comment by solongordon** [comment]
We could also just remove `cockroach zone` entirely, but I thought it was worth keeping the helpful error messages which point to the equivalent SQL commands.

**Comment by rohany** [comment]
I think it's a good idea to keep the commands there and suggest what to do instead.

**Review by knz — APPROVED** [review]
:lgtm: modulo perhaps using `errors.WithHint` (try it out and decide for yourself if the UX is better)

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39177#-:-Ll33roMAZoU_CdOe31C:b6zhx5d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/cli/zone.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39177#-Ll33QJp8oN-IspV9dH9:-Ll33QJr4JhN5xj1VxT0:b-ax4kov) ([raw file](https://github.com/cockroachdb/cockroach/blob/35c81121365540747f403d9896225cd7fba3d6b0/pkg/cli/zone.go#L34)):*
> ```Go
> // and if present, outputs its YAML representation.
> func runGetZone(_ *cobra.Command, _ []string) error {
> 	return errors.New(
> ```

here and below, try this:

```go
returns errors.WithHint(
   errors.New("this command has been removed"),
   "Use SHOW ....")
```

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rohany and @solongordon)

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @rohany)

___
*[pkg/cli/zone.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39177#-Ll33QJp8oN-IspV9dH9:-Ll7gvdMEoiZM5RA90Gd:but5wu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/35c81121365540747f403d9896225cd7fba3d6b0/pkg/cli/zone.go#L34)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here and below, try this:

```go
returns errors.WithHint(
   errors.New("this command has been removed"),
   "Use SHOW ....")
```
</blockquote></details>

Done. Thank you for the HINT. :)

**Comment by solongordon** [comment]
Fixed an acceptance test I didn't notice I had broken.

bors r+

**Pull request merged**
