### PR TITLE
sql/distsqlplan: avoid excessive data copying

### PR DESCRIPTION
**Pull request by knz**
First commit from  #28937.
Needed for #28690.

The `ColumnType` struct is not trivially small. Also calling a
by-pointer method on a copy may cause it to escape on the heap. Avoid
making copies until necessary.

Release note: None

### CODE REVIEW

**Review by BramGruneir — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28942)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/physical_plan.go, line 891 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28942#-LKX-zfHDOlA7fyJ6mln:-LKX-zfI5qwEchOg8LQf:bbyl9wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbd7623ea82c4c5d23cdea33328af68d1ce6cdd5/pkg/sql/distsqlplan/physical_plan.go#L891)):*
> ```Go
> 			merged[i] = *leftType
> 		} else {
> 			return nil, errors.Errorf("conflicting ColumnTypes: %v and %v", leftType, rightType)
> ```

shouldn't these also be referenced?

Also, is %v correct here?  
And if ColumnType doesn't have a String() yet, it should.  I think I hit upon the annoyance of this while debugging recently.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28942)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/physical_plan.go, line 891 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28942#-LKX-zfHDOlA7fyJ6mln:-LKX59DIChyjR3JK1mRp:bqnoo92) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbd7623ea82c4c5d23cdea33328af68d1ce6cdd5/pkg/sql/distsqlplan/physical_plan.go#L891)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

shouldn't these also be referenced?

Also, is %v correct here?  
And if ColumnType doesn't have a String() yet, it should.  I think I hit upon the annoyance of this while debugging recently.
</blockquote></details>

It has already, it's implemented on the pointer type, so this fine.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28942#-:-LKYRvm_Aj9yehxSe_rb:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
thank you!

bors r+

**Pull request merged**
