### PR TITLE
rowflow: account for more memory usage of the row buffer

### LINKED ISSUE #55848: sql/rowflow: TestRouterDiskSpill failed
[(sql/rowflow).TestRouterDiskSpill failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2385090&tab=buildLog) on [master@4019977188f67504f39422997c32408150d4a88d](https://github.com/cockroachdb/cockroach/commits/4019977188f67504f39422997c32408150d4a88d):

Fatal error:
```
panic: test-monitor: unexpected 8 leftover bytes [recovered]
	panic: test-monitor: unexpected 8 leftover bytes [recovered]
	panic: test-monitor: unexpected 8 leftover bytes

```

Stack:
```
goroutine 199 [running]:
testing.tRunner.func1(0xc000324700)
	/usr/local/go/src/testing/testing.go:874 +0x69f
panic(0x32124c0, 0xc00098c100)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:103 +0x2ae
panic(0x32124c0, 0xc00098c100)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x4921ea0, 0xc0003be3c0, 0xc00053b500, 0x33a6a10, 0x20, 0xc0007eeec8, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:340 +0x3ff
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc000263540, 0x4921ea0, 0xc0003be3c0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:406 +0x475
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:391
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*EvalContext).Stop(0xc000304240, 0x4921ea0, 0xc0003be3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3344 +0x70
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:563 +0xec
testing.(*common).FailNow(0xc000324700)
	/usr/local/go/src/testing/testing.go:653 +0x5b
testing.(*common).Fatalf(0xc000324700, 0x33bde47, 0x29, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/testing.go:716 +0x9e
github.com/cockroachdb/cockroach/pkg/sql/rowflow.TestRouterDiskSpill(0xc000324700)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/routers_test.go:919 +0x1807
testing.tRunner(0xc000324700, 0x38669d8)
	/usr/local/go/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x652

```

<details><summary>Log preceding fatal error</summary><p>

```
  github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:406 +0x474
  github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*EvalContext).Stop()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:391 +0x6f
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
  testing.(*common).Fatalf()
      /usr/local/go/src/testing/testing.go:716 +0x9d
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.TestRouterDiskSpill()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/routers_test.go:919 +0x1806
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c00010e290 by goroutine 82:
  github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:663 +0xfe
  github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:534 +0xc8
  github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBudget()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:521 +0xba
  github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:413 +0xbb
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*routerBase).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:391 +0x580

Goroutine 72 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:64 +0x223

Goroutine 82 (finished) created at:
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*routerBase).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/routers.go:301 +0xcd
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.TestRouterDiskSpill()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/routers_test.go:826 +0x15fc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
--- FAIL: TestRouterDiskSpill (0.02s)
    routers_test.go:919: expected memory error when consuming rows
    testing.go:853: race detected during execution of test

```

</p></details>

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=2

```
make stressrace TESTS=TestRouterDiskSpill PKG=./pkg/sql/rowflow TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRouterDiskSpill.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we accounted for the memory usage of the row buffer from
which the rows are pushed from in the routers only when copying the rows
from the row container, but we also have another in-memory row buffer
that we can move the rows from which was missing the memory accounting.
This is now fixed which also deflakes the router disk spill test.

Fixes: #55848.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'm open to suggestions on how to actually de-flake the test without removing it, but I can't seem to figure it out. Locally the tests fails after a few hundred of iterations under stress as is.

**Review by asubiotto — COMMENTED** [review]
Thanks for looking at this. Does this also fix the race in #55848?

Could you describe the reason this fails in more detail? What does a rare case where this error does not occur look like? Even if the producer and consumer goroutines run concurrently, why does that affect the occurence of the error?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55877#-:-MKZLnz31eNJdvZzbA2_:b6p5aol)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
Yeah, it does fix the race too.

~To be honest, I don't understand the reason why the test as is is flaky - sometimes the expected memory error doesn't occur which (sometimes). I'd appreciate if you took a look.~

~I thought that one explanation for the flakiness could be that the limit on `test-monitor` is set pretty high so that we can add a bout half of all rows to the in-memory container before spilling to disk. Once the spilling occurs, then the memory account of the row container is cleared, and the consumer goroutine never buffers up enough rows in `rowBufToPushFrom` account to hit that limit. I tried this [diff](https://gist.github.com/yuzefovich/a503847f9369793ca214652ddbd9428f) to prototype a separate monitor with a limit of 1, but that still is flaky :/~

Never mind, I think I figured it out [here](https://github.com/yuzefovich/cockroach/commit/f949e173930f2d25f9edbf72872cd1b9abae854f). Will kick off a nightly stress on a gceworker.

**Comment by yuzefovich** [comment]
No failures in 400k run in over an hour, so I assume that fixes it, RFAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55877#-:-MKdfFJuD2DwV2dm15EQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
The build is red because of a logic test flake.

TFTR!

bors r+

**Pull request merged**
