### PR TITLE
crosscluster/logical: initial UDF-applier implementation

### PR DESCRIPTION
**Pull request by stevendanna**
This is a basic implementation of the "applier". Here, a user-provided
UDF is run against every row. The UDF's return value instructs the
replication processor how to handle the mutation.

Currently, this feature has some important caveats:

- Hidden columns are not handled correctly. As a result, it
  can't be used on multi-region tables or tables without an
  explicit index.

- Users attempting to change the row they are inserting need to
  know the canonical order of the columns in the table. This makes
  it rather hard to use for non-trivial tables.

There is much todo still:

- [x] Add the relevant timestamps as additional arguments to the function
- [x] Add the previous value as an additional argument to the function.
- [ ] This feature is not actually exposed to users and just available for unit testing.

Epic: none
Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126811)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[`pkg/ccl/crosscluster/logical/lww_row_processor.go` line 70 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126811#-O1IVJyq-QIgKO02RXTB:-O1IVJyq-QIgKO02RXTC:bsiyp8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e48f0a43f0e6268c5c5f9c3ba2cc4bf61943/pkg/ccl/crosscluster/logical/lww_row_processor.go#L70)):*
> ```Go
> 	AddTable(int32, catalog.TableDescriptor) error
> 	InsertRow(context.Context, isql.Txn, isql.Executor, cdcevent.Row, *cdcevent.Row, bool) (batchStats, error)
> 	DeleteRow(context.Context, isql.Txn, isql.Executor, cdcevent.Row, *cdcevent.Row) (batchStats, error)
> ```

nit: it might help to name the two `Row` parameters in this interface so that it's easier to understand these function definitions

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
I'm a little lukewarm on the log builtin; and we don't appear to be using the logged line in the test that calls it, right?

**Comment by stevendanna** [comment]
> I'm a little lukewarm on the log builtin; and we don't appear to be using the logged line in the test that calls it, right?

I don't mind dropping that for now. It really helped debug some things, but since this is going to be backported, seems a bit late in the game to be adding a new general purpose builtin.

**Comment by dt** [comment]
I rebased this over the descriptor map sig changes and will bors it once it is green to avoid picking up more merge conflicts. If anyone sees anything they don't like we can clean it up in followups.

**Comment by dt** [comment]
`TestUDFWithRandomTables` seems flaky, both before and after the rebase.

**Comment by dt** [comment]
skipped and filed as https://github.com/cockroachdb/cockroach/issues/127289

**Review by msbutler — APPROVED** [review]

**Comment by stevendanna** [comment]
blathers backport 24.2

**Pull request merged**
