### PR TITLE
sql: add check constraint

### LINKED ISSUE #2474: sql: support CHECK(expr) constraints
A `CHECK` constraint is an expression that is evaluated when a row is inserted or updated and must return `not-FALSE` in order for the check to pass. This enhancement should primarily be a matter of bookkeeping.

### PR DESCRIPTION
**Pull request by guanqun**
This partly fixes #2474 As I commented in the source code, there are still more TODOs such as more corner case checking, table constraint, update hook etc. But I think this is a good start as to see if I'm in the right direction. :)

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5010)

### CODE REVIEW

**Comment by petermattis** [comment]
This looks good. In case you weren't aware, there are also CHECK constraints at the table level which allows the constraint expression to refer to any column in the table. Tackling those would be good in a follow-on PR. 

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 4 of 4 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/insert.go, line 169 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZ0fy2BEo79ssSw3S:-KCQZ0fzBnwSF0EdcYm2:-716540477) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L169)):*
Add punctuation to the end of these comments.

---

*[sql/insert.go, line 173 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZWhSk_L35t0L9L_0:-KCQZWhT3l3iqWiqSaf2:-563554493) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L173)):*
Shouldn't this be looping over `checkExprs`?

---

*[sql/insert.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZ8jNhMs1DHuBDB8t:-KCQZ8jNhMs1DHuBDB8u:1654053697) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L174)):*
Rather that nesting like this, I find the code easier to read if you continue early:

```
  if col.CheckExpr == nil {
    continue
  }
  i, ok := colIDtoRowIndex[col.ID]
  if !ok {
    continue
  }
```

---

*[sql/insert.go, line 198 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQ_RPX3_r2YYlbPsHe:-KCQ_RPY2vkTPkZ0-FZQ:1827569897) ([raw file](https://github.com/cockroachdb/cockroach/blob/690b9333925f05e65778a92a7f8d53ad50bb1d80/sql/insert.go#L198)):*
We generally do not capitalize error messages so that they compose together better: `s/Failed/failed/g`. It would be good to reference the column that is failing the constraint (or the constraint that is failing). Something like: `CHECK constraint violated: (a > 0)`

---

*[sql/table.go, line 189 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZn-8Z3wNrdBlPzDD:-KCQZn-8Z3wNrdBlPzDE:-301878672) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/table.go#L189)):*
I believe the expression can only refer to the column it is attached to. I don't see you performing that check elsewhere, so expand the TODO comment here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-:-KCQaM_Al-WNLYSy-plo:213557780)*

**Comment by guanqun** [comment]
Yes, I'm aware of the table level CHECK constraints, I've added a TODO in the test case to remind me of this.

---

Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 169 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZ0fy2BEo79ssSw3S:-KCSt_Ofhe5mnVwHrzMc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L169)):*
Done.

---

*[sql/insert.go, line 173 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZWhSk_L35t0L9L_0:-KCStnxtS6ktnKGG_-Bg:-488952603) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L173)):*
I think both should work.

---

*[sql/insert.go, line 174 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZ8jNhMs1DHuBDB8t:-KCStkMp-2vhrHnaj1NW:-1253695909) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L174)):*
OK. I'll change to this style.

---

*[sql/insert.go, line 198 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQ_RPX3_r2YYlbPsHe:-KCStre08TYk9W8_Edmx:-2056411183) ([raw file](https://github.com/cockroachdb/cockroach/blob/690b9333925f05e65778a92a7f8d53ad50bb1d80/sql/insert.go#L198)):*
I see. And I'll add which constraint is being violated.

Actually each CHECK constraint should have its name, but I'll leave it as a TODO.

---

*[sql/table.go, line 189 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZn-8Z3wNrdBlPzDD:-KCSu6VrwH-x4ibm7gum:1900293759) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/table.go#L189)):*
There are several validation checks:
- refer to its column and no other column name is used.
- must have one column
- no aggregation function should be used.

I'll expand the TODO comments.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-:-KCStLlF3fwNAE22QE2F:-1081586966)*

**Comment by petermattis** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 173 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZWhSk_L35t0L9L_0:-KCTFYEpFsS1LlJDQEtr:-1520403372) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L173)):*
Ah, I didn't realize that `len(checkExprs) == len(tableDesc.Columns)`. I think it would be better to make `checkExprs` only contain actual `CHECK` constraints. I might be missing something below, but I don't see any need to know that `col.ID` once the check expressions are generated. 

---

*[sql/insert.go, line 445 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCTG8UPj8gW9vG-HMc3:-KCTG8UPj8gW9vG-HMc4:-1953850476) ([raw file](https://github.com/cockroachdb/cockroach/blob/690b9333925f05e65778a92a7f8d53ad50bb1d80/sql/insert.go#L445)):*
See my other comment. I think `checkExprs` should only actual `CHECK` expressions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010)*

**Comment by guanqun** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 173 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZWhSk_L35t0L9L_0:-KCTwRuwjMc0W3sYxG6T:-2110225087) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L173)):*
`checkExprs` is just an array of `parser.Expr`. `parser.Expr` doesn't contain the column index, and we need the column index to populate to the correct qualified variable.

If you prefer the compacted `checkExpr`, I can make a map (key: col id, value: Expr).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010)*

**Comment by petermattis** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 173 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010#-KCQZWhSk_L35t0L9L_0:-KCW5kPpWCk85-NwIvSL:-1162342659) ([raw file](https://github.com/cockroachdb/cockroach/blob/e565941660a821baa56a3c4e12979186d5fa5797/sql/insert.go#L173)):*
I must be missing something. Where in the loop below do you the column index? As far as I can tell you only use the column index to find the check expression. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5010)*

**Comment by petermattis** [comment]
Replaced by #6044.

**Pull request closed without merging**
