### PR TITLE
ui: don't download .dll.js bundles

### PR DESCRIPTION
**Pull request by sjbarag**
Loading the CockroachDB admin UI (served from port 8080) would previously download three JS files: `bundle.js`, `vendor.dll.js`, and `protos.dll.js`. Neither `vendor.dll.js` nor `protos.dll.js` need to be included via `<script/>` tag, as they're used only as build-time tooling to accelerate webpack builds. Only a single file -- `bundle.js` -- needs to be loaded for the admin UI to be functional, and Bazel-produced builds don't have any `.dll.js` files to serve. Don't load `.dll.js` files via index.html.

Since dll file aren't being served directly to users anymore, there's no need to embed them in the `cockroach` binary. Stop copying `.dll.js` files into `pkg/ui/dist{oss,ccl}` during builds, reducing the `cockroach` binary size by ~19MB (darwin, x86) when built with GNU make.

### CODE REVIEW

**Comment by sjbarag** [comment]
### Requests before this change:
requests-from-master

### Requests after this change:
requests-from-this-pr

Note, however, that there's basically no reduction in "DOMContentLoaded" or "Load" events.  `bundle.js` was previously downloaded in parallel with the `.dll.js` files, so there's no significant difference in perceived performance here.

**Review by dhartunian — APPROVED** [review]
:sparkles: :lgtm: :sparkles: 

We should backport this since it reduces the browser download by a significant amount!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78533#-:-MzGIdcJBfdypK3PbqVj:b-w83e47)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by nathanstilwell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78533)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by sjbarag** [comment]
21.2 backport created in https://github.com/cockroachdb/cockroach/pull/78668

**Pull request merged**
