### PR TITLE
kvserver, ui: record information about the type of lease transfer

### PR DESCRIPTION
**Pull request by aayushshah15**
In debugging a few roachtest failures (#61541) and other issues
(https://github.com/cockroachlabs/support/issues/893#issuecomment-818263346),
we've gained a lot by deducing the type of lease acquisition that
resulted in a given lease.

This commit persists this information through to `Replica`'s
`leaseHistory` and adds it to the lease history table on the range
report page in the Admin UI.

Screen Shot 2021-04-17 at 9 19 15 PM

Release note (ui change): The lease history section on the range report
page now shows the type of lease acquisition event that resulted in a
given lease.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Good idea!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-:-MYfm29qDqe2VDteSEht:b-ovwawk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @lunevalex)

___
*[pkg/kv/kvserver/replica_range_lease.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-MYfl-soAxtiz20tp4IK:-MYfl-soAxtiz20tp4IL:b2h55ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/1688bd5226a0a35f89bee1f6c7dad4bc2f137983/pkg/kv/kvserver/replica_range_lease.go#L261)):*
> ```Go
> 	var leaseReq roachpb.Request
> 	if transfer {
> 		reqLease.AcquisitionType = roachpb.LeaseAcquisitionType_Transfer
> ```

I think there is a slight preference to assign this is in `cmd_lease.go`'s `evalNewLease`, maybe right after we assign the lease sequence.
___
*[pkg/kv/kvserver/replica_range_lease.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-MYflJkZ8sQbsN7POSW_:-MYflJkZ8sQbsN7POSWa:b-ta2vyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1688bd5226a0a35f89bee1f6c7dad4bc2f137983/pkg/kv/kvserver/replica_range_lease.go#L261)):*
> ```Go
> 	var leaseReq roachpb.Request
> 	if transfer {
> 		reqLease.AcquisitionType = roachpb.LeaseAcquisitionType_Transfer
> ```

We should probably gate this on a cluster version, so that we don't start writing this field before all nodes know how to interpret it. Without that, we risk the field not round-tripping through a node that's not aware of its existence. I think that should be fine, given the ways in which leases move throughout the system, but I don't know that it's worth the risk.
___
*[pkg/roachpb/data.proto, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-MYfkh_TBzyidamQqVBO:-MYfkh_TBzyidamQqVBP:b1hovlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1688bd5226a0a35f89bee1f6c7dad4bc2f137983/pkg/roachpb/data.proto#L577)):*
> ```protobuf
>   // lease transfer.
>   Transfer = 1;
>   // Request indicates that the current lease is a result of a lease request.
> ```

`(non-cooperative)`

**Review by aayushshah15 — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-:-MZ4tYtt8BXqmNWVE3IP:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lunevalex and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_range_lease.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-MYflJkZ8sQbsN7POSW_:-MYg6l3NCR2sn8sqABLF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1688bd5226a0a35f89bee1f6c7dad4bc2f137983/pkg/kv/kvserver/replica_range_lease.go#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should probably gate this on a cluster version, so that we don't start writing this field before all nodes know how to interpret it. Without that, we risk the field not round-tripping through a node that's not aware of its existence. I think that should be fine, given the ways in which leases move throughout the system, but I don't know that it's worth the risk.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_range_lease.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-MYfl-soAxtiz20tp4IK:-MZ4tM_FEn430pGOTPT6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1688bd5226a0a35f89bee1f6c7dad4bc2f137983/pkg/kv/kvserver/replica_range_lease.go#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think there is a slight preference to assign this is in `cmd_lease.go`'s `evalNewLease`, maybe right after we assign the lease sequence.
</blockquote></details>

Done.
___
*[pkg/roachpb/data.proto, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-MYfkh_TBzyidamQqVBO:-MZ4tW9e7aUs6sVM61yV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1688bd5226a0a35f89bee1f6c7dad4bc2f137983/pkg/roachpb/data.proto#L577)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`(non-cooperative)`
</blockquote></details>

Done.

**Comment by aayushshah15** [comment]
@nvanbenschoten I'd appreciate another look from you regarding the latest revision if you wouldn't mind.

**Review by nvb — APPROVED** [review]
:lgtm:

Were you planning on backporting this change? I'm slightly hesitant about that, because we've seen this kind of change cause subtle bugs multiple times in the past. For instance, the change to `Lease.Equivalent` could have been easy to miss. It may be safer to land this on master and let it bake for a while (in which case, we may not be able to merge until the v21.2 cluster version is minted).

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63822#-:-MZEv40t5hqRFU7dRdOr:bil7eoc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lunevalex)

**Comment by aayushshah15** [comment]
>Were you planning on backporting this change?

Nah I wasn't, and I agree with what you said.

bors r+

**Pull request merged**
