### PR TITLE
sql/sqlbase: clean up foreign key table lookup code

### PR DESCRIPTION
**Pull request by BramGruneir**

### CODE REVIEW

**Comment by jordanlewis** [comment]
-1 on this change without including updated benchmark results from tests without foreign keys. This was added for a reason - in the hot path with no fks, there's no need to allocate a map. This does in fact show up in profiles.

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19680#-:-KxnQsJDo-j5hJX6d7TO:b-bwl926)*

**Comment by jordanlewis** [comment]
Err, I was actually thinking of something else. I've no idea if this shows up in profiles in the hot path without foreign keys - but I'm still interested in making sure you're not disabling an important performance optimization, hence the benchmark output ask.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19680#-:-KxnRlMaUwthbDUQrwUm:bodnxd4)*

**Comment by dt** [comment]
LGTM on the removal of the n^2 loop (though it would be good to mention that specifically in the commit).

I'd either do the benchmark @jordanlewis asked for, or just leave the lazy init of the map since it can't hurt.

**Comment by BramGruneir** [comment]
So I removed the always allocate the map.  And tried just running the benchmarks on the removal of the extra loop.  Mostly to learn how to run sql benchmarks than for anything else.  So here are the results for fun.

```
BENCHES=BenchmarkSQL/^Cockroach/InsertFK/count=1000 PKG=./pkg/sql ./scripts/bench master fk

name                                         old time/op    new time/op    delta
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     52.9ms ± 4%    55.9ms ±15%     ~     (p=0.278 n=9+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8      191ms ±15%     186ms ± 2%     ~     (p=0.606 n=8+9)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     366ms ± 7%     323ms ± 5%  -11.58%  (p=0.000 n=8+10)

name                                         old alloc/op   new alloc/op   delta
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     17.6MB ± 1%    17.6MB ± 1%     ~     (p=0.460 n=10+8)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8     73.1MB ± 1%    73.2MB ± 1%     ~     (p=0.912 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8     146MB ± 1%     144MB ± 1%   -1.83%  (p=0.000 n=9+9)

name                                         old allocs/op  new allocs/op  delta
SQL/Cockroach/InsertFK/count=1000/nFks=1-8       131k ±12%      128k ±13%     ~     (p=0.529 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8       499k ±12%      504k ±16%     ~     (p=0.853 n=10+10)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8      943k ± 1%      954k ± 5%     ~     (p=0.968 n=9+10)
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19680#-:-KxoY5zzv9gHW10cbcKp:bfkob5n)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19680#-:-KxoYyDB4UaoyYFByzba:bnfp4nl)*

**Comment by jordanlewis** [comment]
Thanks! Appreciate you learning about the benchmarks for this PR. I was actually mostly interested in the performance for inserts *without* fks though - would you mind sending some results for that as well?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19680#-:-Kxoa2JduXYHcQPT43xc:b-acxrc5)*

**Comment by jordanlewis** [comment]
Oh oops I didn't see that you put the lazy creation back in. Carry on :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19680#-:-KxoaG7J1vugtp09o_hW:b-hb2oh4)*

**Comment by BramGruneir** [comment]
Just for fun, I'm going to rerun it without the lazy allocation.  For both FK and non-FK.  Will post the results here.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19680#-:-Kxob9XZZmVa0simMW_c:buyj5ej)*

**Pull request merged**
