### PR TITLE
streamingest: add AOST to stream ingestion job

### PR DESCRIPTION
**Pull request by pbardea**
To be rebased on the PR that introduces the core changefeed stream client.

Release justification: low-risk (very experimental feature), high reward
(AOST stream ingestion)

Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
Still need to add tests (parser and otherwise) but should be ready for an initial look.

**Review by adityamaru — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/sql/parser/sql.y, line 2642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61037#-MUVbByoB4r-jG6KTVNG:-MUVbByoB4r-jG6KTVNH:b-h7erv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bea53c3f019b2c509526554706373ff151a15e/pkg/sql/parser/sql.y#L2642)):*
> ```Yacc
>     }
>   }
> | RESTORE targets FROM REPLICATION STREAM FROM string_or_placeholder_opt_list opt_as_of_clause
> ```

~Do we need parse tests?~ Just saw your comment above.
___
*[pkg/sql/parser/sql.y, line 2647 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61037#-MUVaykB9GghS9RTmypN:-MUVaykB9GghS9RTmypO:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bea53c3f019b2c509526554706373ff151a15e/pkg/sql/parser/sql.y#L2647)):*
> ```Yacc
>      Targets: $2.targetList(),
>      From: $7.stringOrPlaceholderOptList(),
>       AsOf: $8.asOfClause(),
> ```

nit: extra space

**Review by pbardea — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61037#-:-MUVdaCr-DhA8lBdbKVu:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/sql/parser/sql.y, line 2642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61037#-MUVbByoB4r-jG6KTVNG:-MUVdFqeCT0AnLhbEGGW:b-jpv8mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bea53c3f019b2c509526554706373ff151a15e/pkg/sql/parser/sql.y#L2642)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Do we need parse tests?
</blockquote></details>

Yep, I was going to add them after rebasing on https://github.com/cockroachdb/cockroach/pull/61036, but I think it'd be easier to merge this first and rebase that one.
___
*[pkg/sql/parser/sql.y, line 2647 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61037#-MUVaykB9GghS9RTmypN:-MUVdOEHDVrTD7f83O7c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bea53c3f019b2c509526554706373ff151a15e/pkg/sql/parser/sql.y#L2647)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: extra space
</blockquote></details>

Done.

**Comment by pbardea** [comment]
@dt Could you give this a look please, thanks! Some of this work will be followed up in https://github.com/cockroachdb/cockroach/pull/61036.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTR!
bors r=adityamaru,dt

**Pull request merged**
