### PR TITLE
schemachanger: address error message inconsistencies with legacy schema changer

### PR DESCRIPTION
**Pull request by fqazi**
These changes will address the following issues, which will also allow us to enable logictest support in a separate PR:

1. Cases where the declarative schema changer currently either does not generate an error message or generates a message that is inconsistent with the legacy schema changer.
2. A case inside DROP SCHEMA inside the legacy schema changer, where the message generated for privilege errors is not consistent with other DROP operations.
3. Fixing an issue inside the declarative schema changer where we should have been avoiding leased descriptors for event logging.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4G--P-euxkJzb3KZ2:-Mt4G--P-euxkJzb3KZ3:bcry386) ([raw file](https://github.com/cockroachdb/cockroach/blob/05192f8c284bbe031f235134b808b45db8140bb3/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L51)):*
> ```Go
> 			if n.DropBehavior == tree.DropRestrict && (nodeAdded || !schemaDroppedIDs.Empty()) {
> 				panic(pgerror.Newf(pgcode.DependentObjectsStillExist,
> 					"database %q is not empty and RESTRICT was specified", db.GetName()))
> ```

I feel like `RESTRICT` is the default so the previous error might have been clearer, no?



_Code quote:_
```Go
					"database %q has a non-empty schema %q and CASCADE was not specified", db.GetName(), schema.GetName()))
			}
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4G--P-euxkJzb3KZ2:-Mt4IOrN1NudGBzPHrzc:bw5ky8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/05192f8c284bbe031f235134b808b45db8140bb3/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L51)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like `RESTRICT` is the default so the previous error might have been clearer, no?
</blockquote></details>

Good point, let me fix the legacy schema changer instead for this one.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4G--P-euxkJzb3KZ2:-Mt4IsaX4aD-LiNdgqQK:b-rgjwu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/05192f8c284bbe031f235134b808b45db8140bb3/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L51)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Good point, let me fix the legacy schema changer instead for this one.
</blockquote></details>

Actually CASCADE is the default

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4G--P-euxkJzb3KZ2:-Mt4J0MB7btdrOAsosir:b-tzvu52) ([raw file](https://github.com/cockroachdb/cockroach/blob/05192f8c284bbe031f235134b808b45db8140bb3/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L51)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Actually CASCADE is the default
</blockquote></details>

Done.

Ignoring this, since CASCADE is the default

**Review by postamar — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/drop_schema.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4a-5J5ETUVsWExuZi:-Mt4a-5J5ETUVsWExuZj:b-gwmvli) ([raw file](https://github.com/cockroachdb/cockroach/blob/52039d5c2e5d50164e80487118d6d97fd64bd6b5/pkg/sql/drop_schema.go#L105)):*
> ```Go
> 			if !(isAdmin || hasOwnership) {
> 				return nil, pgerror.Newf(pgcode.InsufficientPrivilege,
> 					"permission denied to drop schema %q", sc.GetName())
> ```

I always wondered whether this was deliberate or not. @ajwerner once told me that the DROP privilege we have in CRDB is not a thing in postgres and is essentially a hack. It's possible that this code you removed is, in fact, the correct way to check privileges from DROP statements. This is worth checking with someone who actually knows how privileges are supposed to work, which is not my case.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4bkik4aR0iarzohW1:-Mt4bkik4aR0iarzohW2:bec1qpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a40df68f38d097acc8ae2e5ae5b05a387c6c0dd/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L123)):*
> ```Go
> 		})
> 		// Detect any sequence ownerships and clean them up no cascade
> 		// is required.
> ```

Is this comment still accurate?
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4bpLhDbc39UwYa3LM:-Mt4bpLhDbc39UwYa3LN:bhnhb80) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a40df68f38d097acc8ae2e5ae5b05a387c6c0dd/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L130)):*
> ```Go
> 			sequence := c.MustReadTable(sequenceOwnedBy.SequenceID)
> 			dropSequence(b, sequence, tree.DropCascade)
> 			if behavior != tree.DropCascade {
> ```

Is it normal that this test occurs after the call to `dropSequence`?
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4b3Gv7kzb63yj3z5X:-Mt4b3Gv7kzb63yj3z5Y:b-yv78pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a40df68f38d097acc8ae2e5ae5b05a387c6c0dd/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L141)):*
> ```Go
> 					}
> 				})
> 			}
> ```

This has way too many levels of nesting, can you improve this to make it more readable please?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/drop_schema.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4a-5J5ETUVsWExuZi:-Mt4dPo43SHevpiH3sd0:bhdhuyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/52039d5c2e5d50164e80487118d6d97fd64bd6b5/pkg/sql/drop_schema.go#L105)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I always wondered whether this was deliberate or not. @ajwerner once told me that the DROP privilege we have in CRDB is not a thing in postgres and is essentially a hack. It's possible that this code you removed is, in fact, the correct way to check privileges from DROP statements. This is worth checking with someone who actually knows how privileges are supposed to work, which is not my case.
</blockquote></details>

Okay, let me go and dig into this
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4bpLhDbc39UwYa3LM:-Mt4cs-jBVXGVVHyCfGB:bd88rd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a40df68f38d097acc8ae2e5ae5b05a387c6c0dd/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L130)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Is it normal that this test occurs after the call to `dropSequence`?
</blockquote></details>

Yes, the dependent element will be injected by the dropSequence decomposition. Let me clarify that with a comment

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/drop_schema.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4a-5J5ETUVsWExuZi:-Mt4kb-rAVx3Cm_Ru8vg:bq0vc23) ([raw file](https://github.com/cockroachdb/cockroach/blob/52039d5c2e5d50164e80487118d6d97fd64bd6b5/pkg/sql/drop_schema.go#L105)):*
> A schema can only be dropped by its owner or a superuser. Note that the owner can drop the schema (and thereby all contained objects) even if they do not own some of the objects within the schema.

https://www.postgresql.org/docs/13/sql-dropschema.html
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4l1Ry2njftyX1hMG4:-Mt4l1Ry2njftyX1hMG5:b8ck08p) ([raw file](https://github.com/cockroachdb/cockroach/blob/52039d5c2e5d50164e80487118d6d97fd64bd6b5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go#L49)):*
> ```Go
> 	if sc.SchemaKind() == catalog.SchemaUserDefined {
> 		b.MustOwn(sc)
> 	}
> ```

Was this removed to deal with the recursive call from `DROP DATABASE`? My guess is we may need to plumb some extra information or something. This sort of this is where the recursion starts to hurt. Seems like this captures the intention of the correct policy. 



_Code quote:_
```Go
	// For non-user defined schemas, another check will be
	// done each object as we go to drop them.
	if sc.SchemaKind() == catalog.SchemaUserDefined {
		b.MustOwn(sc)
	}
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/drop_schema.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4a-5J5ETUVsWExuZi:-Mt4v59F5sBLLwCOuqBr:b-s3225k) ([raw file](https://github.com/cockroachdb/cockroach/blob/52039d5c2e5d50164e80487118d6d97fd64bd6b5/pkg/sql/drop_schema.go#L105)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> A schema can only be dropped by its owner or a superuser. Note that the owner can drop the schema (and thereby all contained objects) even if they do not own some of the objects within the schema.

https://www.postgresql.org/docs/13/sql-dropschema.html
</blockquote></details>

Yeah, the two aren't functionally equivalent.  I'll fix the privilege stuff in the declarative schema changer to match.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/drop_schema.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4a-5J5ETUVsWExuZi:-Mt4wneZ3Jx1eamYQ9Lm:b-ecm3up) ([raw file](https://github.com/cockroachdb/cockroach/blob/52039d5c2e5d50164e80487118d6d97fd64bd6b5/pkg/sql/drop_schema.go#L105)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah, the two aren't functionally equivalent.  I'll fix the privilege stuff in the declarative schema changer to match.
</blockquote></details>

Done.
Fixed the message returned by the legacy schema changer to match the declarative schema changer, since I think this is clearer.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4l1Ry2njftyX1hMG4:-Mt5Cd3V51Ss7acw01yC:b-xim3up) ([raw file](https://github.com/cockroachdb/cockroach/blob/52039d5c2e5d50164e80487118d6d97fd64bd6b5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go#L49)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Was this removed to deal with the recursive call from `DROP DATABASE`? My guess is we may need to plumb some extra information or something. This sort of this is where the recursion starts to hurt. Seems like this captures the intention of the correct policy. 
</blockquote></details>

Yes, it was linked to recursive calls but I think the privilege check is already enforced in the normal DropSchema frontend, so its valid for these methods to not have them. @ajwerner Let me know your thoughts

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4bkik4aR0iarzohW1:-Mt5Djc70T5tx9X_rijt:b-8wp7qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a40df68f38d097acc8ae2e5ae5b05a387c6c0dd/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L123)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Is this comment still accurate?
</blockquote></details>

Done.

Changed the comment to 
		// Detect any sequence ownerships and clean them up if only the
		// cascade option is specified, specifically if other objects rely
		// on the sequence.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4b3Gv7kzb63yj3z5X:-Mt5Ed1tCGJBakzJNmYO:bi07eoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a40df68f38d097acc8ae2e5ae5b05a387c6c0dd/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L141)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This has way too many levels of nesting, can you improve this to make it more readable please?
</blockquote></details>

Done.

Think its much cleaner and less nested now.

**Review by postamar — COMMENTED** [review]
I'm happy if @ajwerner 's happy. Just one minor cleanup required.

> Reviewed 1 of 7 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-:-MtF7NBZ4fyozcBVxDbD:b-ufnt23)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-Mt4b3Gv7kzb63yj3z5X:-MtF5ybI-sdmswVOEgvx:b-jcacc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a40df68f38d097acc8ae2e5ae5b05a387c6c0dd/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L141)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.

Think its much cleaner and less nested now.
</blockquote></details>

Thanks! Much appreciated.
___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 1274 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-MtF6bjAECjwfLc9cqB9:-MtF6bjAECjwfLc9cqBA:bj48gtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/749883de83ea6ef450cf8a2227b7afbf20a0cbe1/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L1274)):*
> ```
> 
> statement ok
> SET experimental_use_new_schema_changer = 'on'
> ```

Isn't this redundant? see ~10 lines above also.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 1274 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-MtF6bjAECjwfLc9cqB9:-MtF9feV1FMoP3A09Zgh:bisz0ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/749883de83ea6ef450cf8a2227b7afbf20a0cbe1/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L1274)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Isn't this redundant? see ~10 lines above also.
</blockquote></details>

Done.

I dropped the one above, we need the second one after the user command for the session variable.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-:-MtJG7a76BG2-TVEjBaS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go, line 132 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74636#-MtJFuDd0K2lfiP0_voc:-MtJFuDd0K2lfiP0_vod:b-z0bize) ([raw file](https://github.com/cockroachdb/cockroach/blob/749883de83ea6ef450cf8a2227b7afbf20a0cbe1/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_table.go#L132)):*
> ```Go
> 			scpb.ForEachRelationDependedOnBy(c, func(status scpb.Status,
> 				targetStatus scpb.Status,
> 				depBy *scpb.RelationDependedOnBy) {
> ```

uber-nit: wrap this like:

```go
			scpb.ForEachRelationDependedOnBy(c, func(
				status scpb.Status,
				targetStatus scpb.Status,
				depBy *scpb.RelationDependedOnBy,
			) {
```



_Code quote:_
```Go
			scpb.ForEachRelationDependedOnBy(c, func(status scpb.Status,
				targetStatus scpb.Status,
				depBy *scpb.RelationDependedOnBy) {
```

**Comment by fqazi** [comment]
@ajwerner @postamar TFTR!

**Pull request merged**
