### PR TITLE
kvserver: don't quiesce with follower in StateProbe

### PR DESCRIPTION
**Pull request by tbg**
shouldReplicaQuiesce checks that all followers are fully caught up, but it's
still possible to have a follower in StateProbe (because we call
`rawNode.ReportUnreachable` when an outgoing message gets dropped).

Persistent StateProbe is problematic: we check for it before lease transfers, so
despite the follower being fully caught up, we'd refuse the transfer.

Unfortunately, this commit itself is not enough: even if the range is not
quiesced, it needs to replicate a new entry to rectify the situation (i.e.
switch follower back to StateReplicate). This is because at the time of writing,
receipt of a heartbeat response from the follower is not enough to move it back
to StateReplicate.
This was fixed upstream, in https://github.com/cockroachdb/cockroach/pull/103826.

However, this is still not enough! If the range quiesces successfully, and
*then* `ReportUnreachable` is called, we still end up in the same state; this is now tracked in https://github.com/cockroachdb/cockroach/issues/103828.

I ran into the above issue on
https://github.com/cockroachdb/cockroach/pull/99191, which adds persistent
circuit breakers, when stressing `TestStoreMetrics`. That test happens to
restart n2 when it's fully caught up and due to the persistence of the circuit
breakers when it comes up the leader will move it into StateProbe (since we can
end up dropping the first heartbeat sent to it as it comes up, since the breaker
hasn't untripped yet).

But, I believe that this bug is real even without this breaker re-work, just
harder to trigger.

Epic: none
Release note (bug fix): fixed a problem that could lead to erroneously refused
lease transfers (error message: "refusing to transfer lease to [...] because
target may need a Raft snapshot: replica in StateProbe"

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks! Backportable?

**Comment by tbg** [comment]
TFTR!
bors r=erikgrinaker

Backports should be fine, I'll give it a try.

[Test failures](https://teamcity.cockroachdb.com/viewLog.html?buildId=10226793&buildTypeId=Cockroach_BazelEssentialCi) in acceptance/version-upgrade are unrelated:

> Error: ***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: index element ?c😀ol6_9 of type jsonb is not indexable in a non-inverted index (SQLSTATE 42P16)

> Error: ***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: index element "c%vol9"_10 of type jsonb is not indexable in a non-inverted index (SQLSTATE 42P16)

**Comment by tbg** [comment]
I am stumped by how I've gotten this mixed version error three times in a row. The test has been flaky for a while, but I seem to be getting exceptionally unlucky (slack thread[^1]).
Going to run it a few more times locally just to check there can't possibly be anything in this PR triggering this (not sure how that would even be possible).

[^1]: https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1684931703555999

**Comment by tbg** [comment]
bors r=erikgrinaker

**Pull request merged**
