### PR TITLE
sql: make column values in index keys be encoded with the correct direction

### PR DESCRIPTION
**Pull request by andreimatei**
- added some missing DESC encoding functions
- this changes the encoding for things and restricts the range of varints that fit in a byte a bit

I don't think this is sufficient for DESC indexes to be actually used in correctly in queries - I have yet to look in detail at how a matching index is chosen for a query and how the direction is used.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3553)

### CODE REVIEW

**Comment by andreimatei** [comment]
Initially I've attempted a scheme where the encoding functions are oblivious to the direction of encoding, which is left to a KeyReader/Writer pair that conditionally do ones' complement. And this way you don't need the `Decreasing` versions of encoding/decoding for all data types. But I couldn't get that to perform quite as well even though I tried pretty hard. To make it perform acceptably the code was pretty ugly, and these encode/encodeDecreasing pairs are not actually that bad.


I'll add a test that mixes tuple and non-tuple constraints for a scan, to check that I haven't messed up that code in makeConstraints. It's a bit hairy.

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K6kDNokzcMCGfWybnvI:-540493276)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 19 of 33 files at r2.
Review status: 20 of 34 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[util/encoding/encoding.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kGqPzuAgXWIlDTLO7:-K6kGqPzuAgXWIlDTLO8:1723806986) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L72)):*
you should leave the zero value unoccupied `_ = iota`

---

*[util/encoding/encoding.go, line 481 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kF2hrff6d9TvY4W8j:-K6kF2hrff6d9TvY4W8k:1444892340) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L481)):*
is this actually needed? looks like it was there before

---

*[util/encoding/encoding.go, line 649 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kFlfbBBKmjYcSodWk:-K6kFlfbBBKmjYcSodWl:-1706210059) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L649)):*
seems like this would be simpler if inlined into EncodeTime along with the Decreasing variant since Direction is mostly being passed through.

---

*[util/encoding/float.go, line 105 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kGYBPzGCK78cVb8b6:-K6kGYBQ-K5BzDa4QZtT:-1452717959) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/float.go#L105)):*
why not inline? the code seems like it'd be simpler

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553)*

**Comment by tamird** [comment]
Reviewed 8 of 33 files at r2.
Review status: 28 of 34 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/structured.proto, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kJ5Kbc7ozx3MJpyNN:-K6kJ5KcAT8gP09QRaUI:-1002498122) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/sql/structured.proto#L91)):*
something about the grammar here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553)*

**Comment by petermattis** [comment]
The addition of the `encoding.Direction` parameter everywhere is burdensome. As an alternative, we could encode the direction in the sign-bit of the column ID, similar to how we encode the direction in the sign-bit for `Plan.Ordering()`. That is, negative column IDs would indicate that the column is encoded in descending order. At the very least, this would give symmetry with `plan.Ordering()`. We'd have to change the `ColumnID` type to be a `uint32`. 

I won't get a chance to completely review this change until this afternoon.

---

Review status: 28 of 34 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K6nH6SHNsJGgN4dMtzf:-453473684)*

**Comment by andreimatei** [comment]
But the direction is per column value in the (index) key, not per the whole key. Plus index keys don't have a ColumnID in them, right? We could encode it in the type marker, but then we lose a lot of range of one-byte integers. The way to abstract away the direction from most uses of encode-decode functions is to move it to a layer below the encoding - what I was talking about above with creating KeyReader/KeyWriter which know about the columns in advance and their directions, and have the encoding function output ascending bytes to the writer. I actually have that implemented, but... I became unconvinced of the utility, it comes with a performance penalty no matter how hard I try and it adds another thing you have to understand. And plus it makes things pretty weird with PrettyPrinters that don't (at least currently) understand the key structure.

If your objection is just superficially about having to pass the direction to encoding calls that previously didn't care about anything, like in logging and such, I considered having function versions that default to ascending. But I decided against it because it's too dangerous to forget about it in cases where it does matter, and it's not really so hard to pass this extra arg. An alternative we could consider is adding trampolines in packages like logging that pass Ascending further. Anyway, keep in mind that the work of changing all the existing function calls has been already done :)

?

---

Review status: 28 of 34 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K6nxLWrp2DxtZUJfbyP:-867300939)*

**Comment by petermattis** [comment]
At the key encoding level, the important information in an `IndexDescriptor` is `ColumnIDs []ColumnID` and `ColumnDirections []Direction`. I'm proposing you combine the two bits of information similar to how the result column index and direction are encoded in the first return value of `Plan.Ordering`. That is, there would be a single slice of `ColumnIDs []ColumnID` where `ColumnID` is defined:

```
type ColumnID int32

func MakeColumnID(id uint32, dir Direction) ColumnID {
  if dir == IndexDescriptor.Desc {
    return -ColumnID(id)
  }
  return ColumnID(id)
}

func (cid ColumnID) Value() uint32 {
  if cid < 0 {
    return uint32(-cid)
  }
  return uint32(cid)
}

func (cid ColumnID) Ascending() {
  return cid > 0
}
```

The extra arg isn't difficult to pass, yet there is utility in conciseness. There are other alternatives to an extra arg. For example, the [ByteOrder](https://golang.org/pkg/encoding/binary/#ByteOrder) interface provides for both big-endian and little-endian encoding without an extra argument.

---

Review status: 28 of 34 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K6o6rCizq4mhH5CX8XW:871638341)*

**Comment by petermattis** [comment]
Review status: 28 of 34 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[keys/printer_test.go, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oTbKdT7ZkC8BX2tSP:-K6oTbKdT7ZkC8BX2tSQ:460323006) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/keys/printer_test.go#L91)):*
I think you need some test cases for `{Bytes,Time}Desc`.

---

*[sql/select.go, line 538 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oWi3F8lOsi9K08tVp:-K6oWi3F8lOsi9K08tVq:-1419103027) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/sql/select.go#L538)):*
`s/we'll/we/g`

---

*[sql/select.go, line 637 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oVIw1CXWF5Huo-ubs:-K6oVIw1CXWF5Huo-ubt:-584926211) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/sql/select.go#L637)):*
Is passing the direction into the encoding routine sufficient, or does the direction also have to affect constraint generation? For example, let's say the where-clause is `a > 5` and there is an index `a DESC`. I think our constraint needs to be on the "end" portion so that the generated span is `/#-/5`. 

Definitely need some tests around this new code.

---

*[util/encoding/encoding.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oXDY6kdUq6Zu5G0eI:-K6oXDY7mjJEeTPaphsv:-226932836) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L64)):*
Do we need for NULLs to sort last when a column is encoded in descending order? I would think it is fine for NULLs to always sort first even when the other column value ordering changes.

---

*[util/encoding/encoding.go, line 79 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oQVkQaNtfV1zKMHJ3:-K6oQVkReoHyGOYEpYMn:1117938224) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L79)):*
I'm assuming you changed this for symmetry with the other encoding routines, but note that we never use the fixed-width encoding routines for indexes.

---

*[util/encoding/encoding.go, line 721 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oSue1eNCesIdfpyGZ:-K6oSue1eNCesIdfpyG_:-1143421700) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L721)):*
I'm curious why we need separate markers for `BytesDesc` and `TimeDesc`, but not for other types.

---

*[util/encoding/encoding_test.go, line 719 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oTM69Ne64X1PG3p38:-K6oTM69Ne64X1PG3p39:1659769235) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding_test.go#L719)):*
`BytesDesc` and `TimeDesc`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553)*

**Comment by andreimatei** [comment]
OK, as we discussed, I'm going to rename `encodeXXX(..., Ascending)` to `encodeXXXAscending()`.
As for encoding the direction as the sign of the ColId, let's wait until it's useful to do.


I've added a new commit that changes makeSpans() to properly deal with the descending keys, beyond the encoding.
I've had to introduce a `datum.Prev()`, mirroring the `datum.Next()`. Except `bytes` don't support a prev, so I had to do more work which makes the cases not totally symmetric.

---

Review status: 0 of 16 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[sql/select.go, line 538 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oWi3F8lOsi9K08tVp:-K7Oml6z_3KBemMfaZVt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/sql/select.go#L538)):*
Done.

---

*[sql/select.go, line 637 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oVIw1CXWF5Huo-ubs:-K7JKInMYEidY7bNvaFA:110029581) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/sql/select.go#L637)):*
Indeed, it's not nearly enough. I've refactored makeSpans and makeConstraints in the next commit.

---

*[sql/structured.proto, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kJ5Kbc7ozx3MJpyNN:-K6oXS4XkzrjKAOU3o66:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/sql/structured.proto#L91)):*
Done.

---

*[util/encoding/encoding.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oXDY6kdUq6Zu5G0eI:-K7OmpimMEWvZL0_VJNH:-1694893444) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L64)):*
well, you probably want the order to be different when you do ORDER ASC vs ORDER DESC? And it helps for them to sort last, makes constructing spans for desc indexes more symmetric to the regular case. Do you care?

---

*[util/encoding/encoding.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kGqPzuAgXWIlDTLO7:-K7OnAhMpIvAEgJscLZ6:-246710621) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L72)):*
as discussed, we don't test for invalid values anyway. But at Peter's request I'll remove most of the functions that take a dir argument, at which point maybe we could check. I'll keep it in mind.

---

*[util/encoding/encoding.go, line 481 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kF2hrff6d9TvY4W8j:-K6oYn4e3ZnjUblJHjlv:1206627692) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L481)):*
It's needed, but the reason is a little subtle. I've added a comment.

---

*[util/encoding/encoding.go, line 649 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6kFlfbBBKmjYcSodWk:-K7OnTySdhztb2U6UWPJ:-1353853683) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L649)):*
I'll split all of these into EncodeAscending/Descending.

---

*[util/encoding/encoding.go, line 721 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oSue1eNCesIdfpyGZ:-K7OnkDKiCmSjitg2qnL:622972878) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L721)):*
because this helps PrettyPrinters deal with desc encoding. For the others, we can decode anyway even if we get the direction wrong.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K7OmFaQJQTRVdmuPY7C:1226964523)*

**Comment by petermattis** [comment]
Review status: 0 of 41 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[sql/parser/datum.go, line 78 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RiHT2iIuUH8G4mWWQ:-K7RiHT3IR3SVV7yEora:194899275) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L78)):*
This isn't quite true (and the comment for `Next` has a similar flaw). Should not that it only holds if `!IsMin()`.

---

*[sql/parser/datum.go, line 761 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RjjZWYUSSDjwakO0q:-K7RjjZX2QbT_RWwtXZb:-34243811) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L761)):*
I'd make this panic symmetric with the one in `DValArg.Next`.

---

*[sql/scan.go, line 347 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RkGxqmkFojUeu940k:-K7RkGxqmkFojUeu940l:-751665076) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/scan.go#L347)):*
`s/even/ever/g`

---

*[sql/select.go, line 736 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RmraMHgC-OzivDvfY:-K7RmraMHgC-OzivDvfZ:1379678764) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select.go#L736)):*
No need for `util.Errorf` in a `panic` since the `panic` will generate a stack trace with the line number (i.e. `fmt.Errorf` or `fmt.Sprintf` is sufficient). Also, error messages generally are lower cased so they can be composed: `s/Unexpected/unexpected/g`. This comment applies elsewhere to this PR.

---

*[sql/select_test.go, line 156 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RpomgWG55SQtNwuwz:-K7RpomhuB_TDJL5E4BU:60130662) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select_test.go#L156)):*
Are you going to add more test cases here to test `DESC` columns?

---

*[sql/select_test.go, line 164 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnME5ti32XNzCul8k:-K7RnME5ti32XNzCul8l:1171545364) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select_test.go#L164)):*
What's the problem here?

---

*[sql/testdata/select, line 241 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnZbR3uiu2o8L5ZDS:-K7RnZbR3uiu2o8L5ZDT:1478800269) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/testdata/select#L241)):*
I like the standard of putting test casing referencing specific issues in separate files (i.e. `select_issue3587`). We should either agree to that standard or decide not to follow it. 

---

*[util/assert.go, line 20 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnxfNJV34aXBM5iSK:-K7RnxfNJV34aXBM5iSL:-1759390277) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/util/assert.go#L20)):*
This is interesting, though others should weigh in on if we want to add an assert-like interface.

---

*[util/assert.go, line 22 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RoYFY88BxgoHKnrJ-:-K7RoYFY88BxgoHKnrJ0:1703520446) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/util/assert.go#L22)):*
No need to call `ErrorfSkipFrames` here as the panic itself will have a stack trace and associated line numbers. You can do `fmt.Sprintf(format, a...)`.

---

*[util/encoding/encoding.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oXDY6kdUq6Zu5G0eI:-K7Rojhcmf6SY_3rw2xk:301114866) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L64)):*
I don't particularly care.  And I don't think the shrinking of the small int range is problematic.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553)*

**Comment by tamird** [comment]
Reviewed 1 of 34 files at r3, 32 of 38 files at r4, 3 of 4 files at r6.
Review status: 35 of 41 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[sql/parser/datum.go, line 76 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7TcQ04MlpxTDl2_-1z:-K7TcQ05eea_CSGyDgKY:-1160187447) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L76)):*
instead of this "trait", you could have:
```
type DatumWithPrev interface {
  Datum
  Prev() Datum
}
```
and do a type assertion at the callsite

---

*[sql/structured.go, line 78 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7TcrzQ8uY3vE2NRinZ:-K7TcrzQ8uY3vE2NRin_:413243722) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/structured.go#L78)):*
does this need to be exported?

---

*[util/encoding/encoding.go, line 800 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7OqAIzuwzlhQFMHnCQ:-K7OqAJ-2d_suiWBNSkL:1380465506) ([raw file](https://github.com/cockroachdb/cockroach/blob/5398b4c4e08747c0cbdce18e75f65b4d1138ec9a/util/encoding/encoding.go#L800)):*
useless parens here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553)*

**Comment by andreimatei** [comment]
renamed EncodeXXX(..., Asc) -> EncodeXXXAscending(...)
changed MakeConstraints to take the column dir into consideration, otherwise the "lastEnd" calculation in `makeSpans` was difficult.
added tests
removed Assertf. Doesn't look like it made the cut.

---

Review status: 9 of 41 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[keys/printer_test.go, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oTbKdT7ZkC8BX2tSP:-K7Om_xI0x3ZvNnJfi1_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/keys/printer_test.go#L91)):*
Done.

---

*[sql/parser/datum.go, line 76 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7TcQ04MlpxTDl2_-1z:-K7TtJC0rrEpXhN536Ky:-1199513847) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L76)):*
I could, and it would be... more object oriented... but would that be better?
I don't have a strong opinion, but I think it's ok for every datum to implement HasPrev() and force some thought about it. Plus in theory HasPrev() doens't need to be a static; some values might have a prev when other don't.

---

*[sql/parser/datum.go, line 78 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RiHT2iIuUH8G4mWWQ:-K7TxXmRr-5qKXAL21Vi:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L78)):*
Done.

---

*[sql/parser/datum.go, line 761 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RjjZWYUSSDjwakO0q:-K7TxhZMEWF3pgcYTl6y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L761)):*
Done.

---

*[sql/scan.go, line 347 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RkGxqmkFojUeu940k:-K7TxqxZV0MEwkunBMRZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/scan.go#L347)):*
Done.

---

*[sql/select.go, line 736 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RmraMHgC-OzivDvfY:-K7TYjWyIr8BElVRApBF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select.go#L736)):*
Done.

---

*[sql/select_test.go, line 156 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RpomgWG55SQtNwuwz:-K7sA4l7nmbEyhLHXfPj:-1632509430) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select_test.go#L156)):*
yes, added

---

*[sql/select_test.go, line 164 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnME5ti32XNzCul8k:-K7UFizlujoYIJYhM9D8:-484322514) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select_test.go#L164)):*
added the test below. As commented, the problem is that the pretty printer returns a funky string :)

---

*[sql/structured.go, line 78 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7TcrzQ8uY3vE2NRinZ:-K7U9ojwjSZzlLGx2CtU:1769808575) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/structured.go#L78)):*
no, made it private

---

*[sql/testdata/select, line 241 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnZbR3uiu2o8L5ZDS:-K7UA-YZQG9GdTH52ncX:-532098810) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/testdata/select#L241)):*
A single file would be simpler to look through and see what's covered and what isn't. Particularly when a bug like this doesn't require a very involved test. 
What's the advantage of separate files?

On a theoretical note, letting historical things like bugs organize your project seems like a poster child of "path dependent" development :) Like, if somebody had the foresight to add this test in the first place, the bug wouldn't have happened, but we still would have probably kept the test.

---

*[util/encoding/encoding.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oXDY6kdUq6Zu5G0eI:-K7TlFWD-Nu4T-Ls6bbq:-1242148562) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding.go#L64)):*
I think this is sane. It also helps to not permit ints to be encoded as `\xff\xff...` so it's clearer that it's correct to do a `bytes.PrefixEnd()` to encode the end constraint for`<= IntMax`

---

*[util/encoding/encoding.go, line 800 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7OqAIzuwzlhQFMHnCQ:-K7TqauMNUFdRzhrRoNY:289747943) ([raw file](https://github.com/cockroachdb/cockroach/blob/5398b4c4e08747c0cbdce18e75f65b4d1138ec9a/util/encoding/encoding.go#L800)):*
hey I'm sorry, I pushed some bad commits onto the branch on which this PR is based, and then I overwrote them. This is from when I was playing around.
Please only look at the last revision. I somehow assumed that nobody's going to look at this, since the tool is gonna show you the diff between the last revision you had comments on and the latest. I guess I don't really understand how reviewable ties comments to revisions, but then still seems to show you comments when you're not looking at the respective revision.

---

*[util/encoding/encoding_test.go, line 719 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K6oTM69Ne64X1PG3p38:-K7UGj3oPkCRHxp_ZbdX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842d18658afa8cf953da8f9fad593d57d2a305e/util/encoding/encoding_test.go#L719)):*
Done.

---

*[util/assert.go, line 20 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnxfNJV34aXBM5iSK:-K7TYni8OWRXifuqtTuQ:-453902037) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/util/assert.go#L20)):*
well, what do you think the consensus-building mechanism should me? Maybe this is a good opportunity to create an `eng@` mailing list, I've wanted it before too. I'll do that.

---

*[util/assert.go, line 22 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RoYFY88BxgoHKnrJ-:-K7Tk9_UP4N_9KFF4Oo0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/util/assert.go#L22)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K7s9h2juT4XHnPFr86X:-1073106949)*

**Comment by petermattis** [comment]
LGTM. Let's get this checked in soon. I'd like to see some additional `sql/testdata` tests added, but I think those can wait for a follow-on PR.

---

Review status: 9 of 41 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[keys/printer.go, line 343 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7vOMmaVYGSfuCGQbt3:-K7vOMmbFC36gZfZbvh2:1642930887) ([raw file](https://github.com/cockroachdb/cockroach/blob/5472c8d485816e4f77ccc30855e67495bdec27dd/keys/printer.go#L343)):*
If this is just for use in tests, let's move it to `printer_test.go`.

---

*[sql/parser/datum.go, line 761 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RjjZWYUSSDjwakO0q:-K7vO_ZnekWr5flv1QAn:22409020) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L761)):*
I think this should be: `panic(d.Type() + ".Prev not supported")`

---

*[sql/select_test.go, line 164 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnME5ti32XNzCul8k:-K7vP0Y73CqDsfn28nM_:-1607631613) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select_test.go#L164)):*
This approach (testing both ascending and descending columns is fine). I might have done something where the list of columns also contains the directions. That is, `"+a"` or `"a"` indicates ascending and `"-a"` indicates descending. This would have allowed mixed direction tests to naturally fit in here.

But let's not change this in this PR. The PR is already too large.

---

*[sql/select_test.go, line 368 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7vPRabTiWHtCDshAa_:-K7vPRabTiWHtCDshAaa:1777694946) ([raw file](https://github.com/cockroachdb/cockroach/blob/5472c8d485816e4f77ccc30855e67495bdec27dd/sql/select_test.go#L368)):*
Ah, you're using this function here too. Ignore my other comment.

---

*[sql/testdata/select, line 241 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnZbR3uiu2o8L5ZDS:-K7vQ6Oujw9-TNwXi33o:1866763648) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/testdata/select#L241)):*
The "path dependent" development doesn't bother me too much. But I'm fine with leaving this here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K7vQFmo8PhXqG8-o7uB:-721561168)*

**Comment by andreimatei** [comment]
yeah testdata needs something,which I'll add as soon as I trace to see if we do the rocksdb scan in the right direction now

---

Review status: 9 of 41 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/parser/datum.go, line 761 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RjjZWYUSSDjwakO0q:-K7vp9luWhx-rXeTJ1dS:1809079568) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/parser/datum.go#L761)):*
done, here and elsewhere

---

*[sql/select_test.go, line 164 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-K7RnME5ti32XNzCul8k:-K7vpckR28OBCZ2CG52d:-1557727082) ([raw file](https://github.com/cockroachdb/cockroach/blob/985a9a587ebe574314485ee2f59448ea0223182f/sql/select_test.go#L164)):*
I've considered adding mixed directions to this group of tests, but the truth is I couldn't decide which ones should get it. So the most reasonable idea I had was to do completely asc/completely desc for all of these, and add a few special mixed ones below. There indeed +a/-a would have been the way to go.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3553#-:-K7vqjCwLeHE1PYa59Ot:47154455)*

**Pull request merged**
