### PR TITLE
roachtest: wait for splits before starting worker for kv50/rangelookups/relocate

### LINKED ISSUE #39021: roachtest: kv50/rangelookups/relocate/nodes=8 failed
SHA: https://github.com/cockroachdb/cockroach/commits/1ad0ecc8cbddf82c9fedb5a5c5e533e72a657ff7

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=kv50/rangelookups/relocate/nodes=8 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1399000&tab=buildLog

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190722-1399000/kv50/rangelookups/relocate/nodes=8/run_1
	cluster.go:1726,kv.go:552,cluster.go:2069,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1563776264-39-n9cpu8:9 -- ./workload run kv --tolerate-errors --concurrency=512 --splits=1000 --duration=10m --read-percent=50 {pgurl:1-8} returned:
		stderr:
		
		stdout:
		: signal: killed
	cluster.go:2090,kv.go:600,kv.go:627,test_runner.go:691: pq: while adding target n3,s3: snapshot failed: (n3,s3):?: remote couldn't accept PREEMPTIVE snapshot 3bf3caa4 at applied index 15 with error: [n3,s3],r21: cannot apply snapshot: [n3,s3]: canApplySnapshotLocked: cannot add placeholder, have an existing placeholder range=21 [/Table/53-/Max) (placeholder)

```

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
Relocates were failing with `cannot add placeholder, have an existing placeholder` due to concurrent splits when splitting the tables during `workload run`. This commit adds a split step during to `workload init` to prevent these concurrent splits.

Release note: None

Fixes #39021. 

Alternatively, we can also add the error to `isExpectedRelocateError` but that doesn't seem ideal.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: 

Makes sense. Here you're using the splits as a proxy for whether the workload has finished its setup. There aren't too many thing which run concurrently with workload but I wonder if we have this sort of problem in a more subtle way in other places. A more complicated solution here could involve communicating with the workload process somehow, perhaps by having it create a file or expose its state. This works. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-:-LkxHtN6A-flJEsnuDpT:b-5epd2g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/cmd/roachtest/kv.go, line 570 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-LkxGO4t4md5PSylSmU7:-LkxGO4t4md5PSylSmU8:bwwdjs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3109a04cc268b3b82e4cd4675192db1b4df6b836/pkg/cmd/roachtest/kv.go#L570)):*
> ```Go
> 		})
> 
> 		// We only start running the workers when the initial splits have been
> ```

nit: you could use the [retry](https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/retry) package here. The defaults are pretty sane.

**Review by nvb — COMMENTED** [review]
Thanks for looking into this. One question I'm left with is whether we can add the `--splits` flag to the `init` step and use the `doneInit` chan like we were before?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-:-Lky9hcQ12gDSAxJ8EN9:b-2j1ghv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jeffrey-xiao)

___
*[pkg/cmd/roachtest/kv.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-Lky90dP1QTKh11cNSJD:-Lky90dP1QTKh11cNSJE:btauwwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de990ad7af46bcbef518cb59590cac31f6ad028/pkg/cmd/roachtest/kv.go#L557)):*
> ```Go
> 			defer close(doneWorkload)
> 			concurrency := ifLocal("", " --concurrency="+fmt.Sprint(nodes*64))
> 			splits := " --splits=" + fmt.Sprint(splits)
> ```

nit: `strconv.Itoa(splits)`
___
*[pkg/cmd/roachtest/kv.go, line 574 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-Lky8z93ANJj7YrmJ7lr:-Lky8z93ANJj7YrmJ7ls:bsntz9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de990ad7af46bcbef518cb59590cac31f6ad028/pkg/cmd/roachtest/kv.go#L574)):*
> ```Go
> 		// We only start running the workers when the initial splits have been
> 		// created. The relocate worker will fail with "cannot add placeholder,
> 		// have an existing placeholder" if there concurrent splits happening.
> ```

"if there are"
___
*[pkg/cmd/roachtest/kv.go, line 576 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-Lky9GfmCApvRCkWAbuq:-Lky9GfmCApvRCkWAbur:b-3ropn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de990ad7af46bcbef518cb59590cac31f6ad028/pkg/cmd/roachtest/kv.go#L576)):*
> ```Go
> 		// have an existing placeholder" if there concurrent splits happening.
> 		retryOpts := base.DefaultRetryOptions()
> 		for retryable := retry.StartWithCtx(ctx, retryOpts); retryable.Next(); {
> ```

Add a `t.Status` so that we know what's going on if this step gets stuck. Once you do that, we'll want to add another one once this finishes.

**Review by jeffrey-xiao — COMMENTED** [review]
The problem with the previous approach is that the splits happen as part of the run command of the workload and not the init step (See https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/cli/run.go#L351-L356).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-:-LkyBqse1lPyR9A7zwwI:b9ktey4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Comment by nvanbenschoten** [comment]
It's pretty bad that `workload init` takes a `--splits` flag but doesn't actually perform any splits. @danhhz do you see any issue with splitting tables in `runInit`? We already do so in `fixturesLoad` and `fixturesImport`.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39122)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/workload/workloadsql/workloadsql.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39122#-LlmjYisE9D1YB8vxyVv:-LlmjYisE9D1YB8vxyVw:bz63duv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fbbd5b2442ccb40f61ba783166ce656b7bdcd4f/pkg/workload/workloadsql/workloadsql.go#L43)):*
> ```Go
> 	}
> 
> 	const splitConcurrency = 384 // TODO(dan): Don't hardcode this.
> ```

This seems like a good place for this, but we now have a number of code paths that will call Split multiple times. We should audit those paths and figure out how to avoid the duplication. For instance, see `backupRestoreTestSetupWithParams`, `fixturesLoad`, `fixturesImport`, `runRun` when`*doInit || *drop`, etc.

**Comment by danhhz** [comment]
> It's pretty bad that workload init takes a --splits flag but doesn't actually perform any splits. @danhhz do you see any issue with splitting tables in runInit? We already do so in fixturesLoad and fixturesImport.

Ah, sorry I missed this! I'd actually like to go even further and split only in init and not in run (unless --init is also specified, but I'd also like to get rid of the --init flag on run)

**Review by nvb — APPROVED** [review]

**Review by danhhz — APPROVED** [review]
workload changes lgtm. i mentioned offline that there might be some weird fallout from this, which is why i hadn't done it myself, but @jeffrey-xiao indicated he was okay with that

**Comment by jeffrey-xiao** [comment]
TFTRs!

bors r+

**Pull request merged**
