### PR TITLE
build: use repository-local GOBIN for less finicky builds

### LINKED ISSUE #6886: build: make build problems with GOBIN
- When trying to follow the directions for [building from source](https://www.cockroachlabs.com/docs/install-cockroachdb.html). I couldn't run `make build` successfully

This is on Ubuntu 16.04
- What did you expect to see?
  normal build output
- What did you see instead?
  
  ```
  Makefile:240: .bootstrap: No such file or directory
  go get github.com/robfig/glock
  /bin/bash: ../../../../bin/glock: No such file or directory
  Makefile:237: recipe for target '.bootstrap' failed
  make: *** [.bootstrap] Error 127
  ```

I worked around it by unsetting $GOBIN (which then completed correctly)

### PR DESCRIPTION
**Pull request by benesch**
This commit adjusts our Makefile to set `GOBIN` to `$(REPO_ROOT)/bin` before
embarking upon a build. This has two benefits:

1. Previously, users who had set `GOBIN` to something other than the default `$GOPATH/bin` would have a broken build. We'd extend the `PATH` to include `$GOPATH/bin`, but `go install` would put binaries in `$GOBIN`, and later build steps would be unable to find the built tools. By forcing `GOBIN` to a known value in the Makefile, users can no longer break the build by having a non-default `GOBIN` set in their environment.

2. Since Go has a single global namespace for installed binaries (i.e., the `GOBIN` directory), if the user had installed a different version of one of our dependencies, or a different tool with a binary of the same name, we'd blow away that binary during our install process. Even worse, later re-installs of the other tool could blow away the version we installed without our build process noticing. Using a repository-local `GOBIN` solves this.

Fixes #6886.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14629)

### CODE REVIEW

**Comment by bdarnell** [comment]
The difference between `build` and `install` no longer makes sense with this change - the only difference before was that `build` put the binary in the local directory and `install` put it in the shared `$GOBIN`. We should either get rid of the `install` target and make `make build` run `go install` instead of `go build`, or only set `$GOBIN` when we're installing our build tools and continue to allow `make install` to output to the global `$GOBIN` (in either case we'd still add `$REPO_ROOT/bin` to `$PATH`). 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/common.mk, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-KgyeMD_hxvAiprAwwOd:-KgyeMDaSh3ocYYWdHlI:b-7dmo1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60c5c6bda27075cf7906885a0988c65bcb7c69c/build/common.mk#L55)):*
> ```Makefile
> export PATH := $(GOBIN):$(UI_ROOT)/node_modules/.bin:$(PATH)
> 
> $(info GOPATH set to $(GOPATH))
> ```

I don't think we need to log these all the time. It's helpful when we're working with non-isolated directories, but now that everything is private to cockroach we should just let it be silent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-:-KgyeetrmxvbkqR5OZVX:bywb4wr)*

**Comment by tamird** [comment]
:lgtm: mod ben's comment

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/common.mk, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-KgyeMD_hxvAiprAwwOd:-KgyicuEfMAvES2HDpJZ:b-u0j5o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60c5c6bda27075cf7906885a0988c65bcb7c69c/build/common.mk#L55)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think we need to log these all the time. It's helpful when we're working with non-isolated directories, but now that everything is private to cockroach we should just let it be silent.
</blockquote></details>

I'd keep the GOPATH line, but can you move it closer to where that's being set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-:-KgyilHJIwZnKx6CtqKg:brxa3nt)*

**Comment by benesch** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/common.mk, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-KgyeMD_hxvAiprAwwOd:-KgykjH75Rl8Xc6Fn5QR:b-3odo2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60c5c6bda27075cf7906885a0988c65bcb7c69c/build/common.mk#L55)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I'd keep the GOPATH line, but can you move it closer to where that's being set?
</blockquote></details>

Did @tamird's suggestion. @bdarnell did you feel strongly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/common.mk, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-KgyeMD_hxvAiprAwwOd:-KgyldxS5EjwNPcmMUPx:b-p18sjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60c5c6bda27075cf7906885a0988c65bcb7c69c/build/common.mk#L55)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Did @tamird's suggestion. @bdarnell did you feel strongly?
</blockquote></details>

No, it's fine to keep the gopath line.

---

*[build/common.mk, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-Kgylmt13z38aSU7Dkhi:-Kgylmt20ARoajrfc2HJ:bstekmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f05f0a8b97249e717671f5f9719eae18ed6d068/build/common.mk#L146)):*
> ```Makefile
> # Update the git hooks and install commands from dependencies into LOCAL_BIN
> # whenever they change.
> $(REPO_ROOT)/.bootstrap: export GOBIN := $(LOCAL_BIN)
> ```

We run `go install` in a few other places too (the `upload-coverage` target in this makefile, `protobuf.mk`, a few of the teamcity scripts). They all need this (except maybe the teamcity stuff, since that's a known environment), unless we can install everything we ever need here and get rid of all the other `go install` calls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-:-KgymJObRqs2G1_2sf8I:bnfp4nl)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/common.mk, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-Kgylmt13z38aSU7Dkhi:-Kgymvam-EchW_m6iNuS:bh3jfk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f05f0a8b97249e717671f5f9719eae18ed6d068/build/common.mk#L146)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We run `go install` in a few other places too (the `upload-coverage` target in this makefile, `protobuf.mk`, a few of the teamcity scripts). They all need this (except maybe the teamcity stuff, since that's a known environment), unless we can install everything we ever need here and get rid of all the other `go install` calls.
</blockquote></details>

Probably easier to un-override this in the install target?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629)*

**Comment by benesch** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/common.mk, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-Kgylmt13z38aSU7Dkhi:-Kgz0vxs9C0TUlV2jDfi:b-9f087o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f05f0a8b97249e717671f5f9719eae18ed6d068/build/common.mk#L146)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Probably easier to un-override this in the install target?
</blockquote></details>

Yep, done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[Makefile, line 117 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-Kgz5AXhUlt-OZOlnoIk:-Kgz5AXhUlt-OZOlnoIl:b-wf1l33) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0433cba8f408427ae92df242c795181cee4c1/Makefile#L117)):*
> ```Makefile
> # Special case: we install the cockroach binary to the user-specified GOBIN
> # (usually GOPATH/bin) rather than our repository-local GOBIN.
> install: GOBIN := $(ORIGINAL_GOBIN)
> ```

Does this do the right thing if GOBIN was unset initially? (i.e. does `go install` treat unset and empty variables the same?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-:-Kgz5QahlY37iOeIfYtr:bb6ywmx)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Makefile, line 117 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629#-Kgz5AXhUlt-OZOlnoIk:-Kgz61cqrsQbUHxJl7d0:b-65ejor) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0433cba8f408427ae92df242c795181cee4c1/Makefile#L117)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Does this do the right thing if GOBIN was unset initially? (i.e. does `go install` treat unset and empty variables the same?)
</blockquote></details>

It does, fortunately. https://github.com/golang/go/blob/178307c3a72a9da3d731fecf354630761d6b246c/src/cmd/dist/build.go#L110-L114

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14629)*

**Comment by dt** [comment]
```pkg/cli/context.go:168: running "stringer": fork/exec /go/src/github.com/cockroachdb/cockroach/bin/stringer: exec format error```

Do we need to use an arch suffix so that builder and host OS don't fight over the contents of the local bin dir?

**Comment by benesch** [comment]
@dt: #14704 finally landed to allow Docker and macOS to share!

**Pull request merged**
