### PR TITLE
metrics:  compute `InternalIntervalMetrics` without making calls to `GetInternalIntervalMetrics`

### PR DESCRIPTION
**Pull request by coolcom200**
Remove dependence on the `GetInternalIntervalMetrics` as this method resets the interval following each call. This results in issues if two clients interact with `GetInternalIntervalMetrics` as they will reset the other client’s interval. Ex: Client A calls every 5 seconds and Client B calls every 10 seconds. Client B will end up getting metrics at a 5-second interval since `GetInternalIntervalMetrics` resets the interval on each call.

The `admission.StoreMetrics` are updated to remove the `InternalIntervalField` as these metrics need to be computed based off the current metrics `admission.StoreMetrics.Metrics` and the previous metrics. The storage of the previous metrics is left up to the client. Removing the field was chosen instead of setting it to a `nil` value as it would be confusing to return the `StoreMetrics` and require the client to populate the field when they compute the necessary metrics.

For the admission control use case, the flush metrics are computed as part of `ioLoadListener.adjustTokens` with the previous metrics being initialized in `ioLoadListener.pebbleMetricsTick` and stored on the `ioLoadListenerState` as `cumFlushWriteThroughput`.

Additionally, make a copy of the `pebble.InternalIntervalMetrics` in order to move away from using the `pebble` version of the interval metrics as these metrics are now the responsibility of the caller to compute.

Release note: None
Epic: CRDB-17515

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @coolcom200 and @irfansharif)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd-fcsB9nK_Wj7IoLm):*
nit: necessary
___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd-k_XED0AjSO4TEeU):*
nit: goroutine
___
*[`pkg/util/admission/granter.go` line 651 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd0LQGCDG-GEJienEq:-NDd0LQGCDG-GEJienEr:b-9oov7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L651)):*
> ```Go
> }
> 
> // IntervalMetrics exposes metrics about internal subsystems, that can
> ```

Let's change the name to `storeInternalIntervalMetrics` (also making it package private).
Also simplify the comment to
// storeInternalIntervalMetrics exposes metrics about internal subsystems in the store,
// that are useful for admission control. These represent the metrics over ...
___
*[`pkg/util/admission/granter.go` line 659 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd0qx2B4N_tw7OWFcK:-NDd0qx2B4N_tw7OWFcL:bimpltb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L659)):*
> ```Go
> type IntervalMetrics struct {
> 	// LogWriter metrics.
> 	LogWriter struct {
> ```

make all of these package private
___
*[`pkg/util/admission/granter.go` line 686 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd0v4zD9sUm7y769v2:-NDd0v5-1y6-Z7xEp9QK:b-dgag6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L686)):*
> ```Go
> // StoreAndIntervalMetrics is a wrapper around StoreMetrics that also contains
> // the IntervalMetrics
> type StoreAndIntervalMetrics struct {
> ```

storeAndIntervalMetrics since it should be package private.
___
*[`pkg/util/admission/granter.go` line 687 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd4TBIDwrXGDf-mrSm:-NDd4TBIDwrXGDf-mrSn:b-21hq1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L687)):*
> ```Go
> // the IntervalMetrics
> type StoreAndIntervalMetrics struct {
> 	*StoreMetrics
> ```

StoreMetrics is being passed by value to `pebbleMetricsTick`. We should keep it as value and not a pointer.

But let's step back for a minute. The diff computation in `StoreGrantCoordinators` isn't a good place since it has to keep state about each store and all the slice index complexity (and not quite correct, since the index is not required to be stable every time we fetch the metrics).

We could move it to `GrantCoordinator.pebbleMetricsTick` since there is a GrantCoordinator per store. But this isn't really the role of `GrantCoordinator`, which isn't supposed to know about the details about store metrics. The `ioLoadListener` already converts cumulative to deltas for all the stuff it computes over, so that is the right place. Currently it does it in a somewhat adhoc manner and I would suggest something simpler for your change.

Define the following in io_load_listener.go (only the flush throughput for now, since that's all we use in admission control `adjustTokensInner`. We can add more later if needed)
```
// storeInternalMetrics can be used to represent both cumulative and interval state for internal store subsystems.
type storeInternalMetrics {
	// Flush loop metrics.
	Flush struct {
		// WriteThroughput is the flushing throughput.
		WriteThroughput pebble.ThroughputMetric
	}
}
```
```
type ioLoadListenerState {
     ...

     // Cumulative
     cumStoreInternalMetrics storeInternalMetrics
}
```
Put this early in ioLoadListernerState with all the other cumulative fields.

In `ioLoadListener.pebbleMetricsTick` in the initialization if-block copy this out. In the non-initialization path, do the subtraction and pass the delta as an explicit parameter to `ioLoadListener.adjustTokens`.

There are various tests that are currently calling `pebbleMetricsTick` and those tests are assuming they should pass a delta for this flush throughput, but now the callee assumes it is being given a cumulative. Luckily most of these tests were passing an empty delta, so they are not affected. The only non-superficial test change will be in `TestIOLoadListener`. See where that test has the following code
```
				var flushBytes, flushWorkSec, flushIdleSec int
				if d.HasArg("flush-bytes") {
					d.ScanArgs(t, "flush-bytes", &flushBytes)
					d.ScanArgs(t, "flush-work-sec", &flushWorkSec)
					d.ScanArgs(t, "flush-idle-sec", &flushIdleSec)
				}
				flushMetric := pebble.ThroughputMetric{
					Bytes:        int64(flushBytes),
					WorkDuration: time.Duration(flushWorkSec) * time.Second,
					IdleDuration: time.Duration(flushIdleSec) * time.Second,
				}
				im := &pebble.InternalIntervalMetrics{}
				im.Flush.WriteThroughput = flushMetric
```
Let's keep the testdata files unchanged, so that the testdata is still providing us interval values. So the test code needs to convert these interval values to cumulative. It can do so easily by keeping additional 3 variables `cumFlushBytes, cumFlushWorkSec, cumFlushIdleSec` declared above the call to `datadriven.RunTest`. Then add what the testcase provided to the current cumulative values and pass those in. Whenever the testcase does "init", to create a new ioLoadListener, set these cumulative values back to 0.

**Review by coolcom200 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 8 of 8 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @sumeerbhola)

___
*[`pkg/util/admission/granter.go` line 651 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd0LQGCDG-GEJienEq:-NDdMdZJ5ds7GErcAb6I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L651)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Let's change the name to `storeInternalIntervalMetrics` (also making it package private).
Also simplify the comment to
// storeInternalIntervalMetrics exposes metrics about internal subsystems in the store,
// that are useful for admission control. These represent the metrics over ...

</blockquote></details>

Done.
___
*[`pkg/util/admission/granter.go` line 659 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd0qx2B4N_tw7OWFcK:-NDdMf-P4ymfVXWJXufF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L659)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

make all of these package private
</blockquote></details>

Done.
___
*[`pkg/util/admission/granter.go` line 686 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd0v4zD9sUm7y769v2:-NDdMfxa8WcHKw14JcwI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L686)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

storeAndIntervalMetrics since it should be package private.
</blockquote></details>

Done.
___
*[`pkg/util/admission/granter.go` line 687 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDd4TBIDwrXGDf-mrSm:-NDe87r3-6amApxA4_2V:bzc8k2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c72f41d62bb7da289152ffa8b9dbc4d2873753f7/pkg/util/admission/granter.go#L687)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

StoreMetrics is being passed by value to `pebbleMetricsTick`. We should keep it as value and not a pointer.

But let's step back for a minute. The diff computation in `StoreGrantCoordinators` isn't a good place since it has to keep state about each store and all the slice index complexity (and not quite correct, since the index is not required to be stable every time we fetch the metrics).

We could move it to `GrantCoordinator.pebbleMetricsTick` since there is a GrantCoordinator per store. But this isn't really the role of `GrantCoordinator`, which isn't supposed to know about the details about store metrics. The `ioLoadListener` already converts cumulative to deltas for all the stuff it computes over, so that is the right place. Currently it does it in a somewhat adhoc manner and I would suggest something simpler for your change.

Define the following in io_load_listener.go (only the flush throughput for now, since that's all we use in admission control `adjustTokensInner`. We can add more later if needed)
```
// storeInternalMetrics can be used to represent both cumulative and interval state for internal store subsystems.
type storeInternalMetrics {
	// Flush loop metrics.
	Flush struct {
		// WriteThroughput is the flushing throughput.
		WriteThroughput pebble.ThroughputMetric
	}
}
```
```
type ioLoadListenerState {
     ...

     // Cumulative
     cumStoreInternalMetrics storeInternalMetrics
}
```
Put this early in ioLoadListernerState with all the other cumulative fields.

In `ioLoadListener.pebbleMetricsTick` in the initialization if-block copy this out. In the non-initialization path, do the subtraction and pass the delta as an explicit parameter to `ioLoadListener.adjustTokens`.

There are various tests that are currently calling `pebbleMetricsTick` and those tests are assuming they should pass a delta for this flush throughput, but now the callee assumes it is being given a cumulative. Luckily most of these tests were passing an empty delta, so they are not affected. The only non-superficial test change will be in `TestIOLoadListener`. See where that test has the following code
```
				var flushBytes, flushWorkSec, flushIdleSec int
				if d.HasArg("flush-bytes") {
					d.ScanArgs(t, "flush-bytes", &flushBytes)
					d.ScanArgs(t, "flush-work-sec", &flushWorkSec)
					d.ScanArgs(t, "flush-idle-sec", &flushIdleSec)
				}
				flushMetric := pebble.ThroughputMetric{
					Bytes:        int64(flushBytes),
					WorkDuration: time.Duration(flushWorkSec) * time.Second,
					IdleDuration: time.Duration(flushIdleSec) * time.Second,
				}
				im := &pebble.InternalIntervalMetrics{}
				im.Flush.WriteThroughput = flushMetric
```
Let's keep the testdata files unchanged, so that the testdata is still providing us interval values. So the test code needs to convert these interval values to cumulative. It can do so easily by keeping additional 3 variables `cumFlushBytes, cumFlushWorkSec, cumFlushIdleSec` declared above the call to `datadriven.RunTest`. Then add what the testcase provided to the current cumulative values and pass those in. Whenever the testcase does "init", to create a new ioLoadListener, set these cumulative values back to 0.
</blockquote></details>

Oh this is a way better way to organize the code! Thank you for bringing this up I have updated it!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-:-NDhXZrD1dsmUxEs3Scn:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @coolcom200, @irfansharif, and @sumeerbhola)

___
*[`-- commits` line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDhV5Kn9fFVzGea2rz3):*
Reminder to update the PR description to be the same as this commit.
___
*[`pkg/util/admission/io_load_listener.go` line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDhVLSjDJ1e7Cf1IKMA:-NDhVLSjDJ1e7Cf1IKMB:bnrdv66) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6b9572a6982478846d6ad33ce9970af80882537/pkg/util/admission/io_load_listener.go#L175)):*
> ```Go
> // store, that are useful for admission control. These represent the metrics
> // over the interval of time from the last call to retrieve these metrics. These
> // are not cumulative, unlike Metrics.
> ```

s/storeInternalIntervalMetrics/storeInternalMetrics

And change the comment to say something like:
These can represent either cumulative metrics, or over an interval of time. The latter is possible since the data representation here allows for subtraction between two cumulative storeInternalMetrics.

Actually, since you are calling `adjustTokensInner` with pebble.ThroughputMetric, just remove this wrapper struct. It is not adding any value, and we are not preserving the wrapping through the method calls. Then we simply have `cumFlushWriteThroughput` as a field in `ioLoadListenerState`.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88972)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @coolcom200, @irfansharif, and @sumeerbhola)

___
*[`pkg/util/admission/io_load_listener.go` line 313 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDiq_Mt39pelTRqlmRy:-NDiq_Mt39pelTRqlmRz:b-7qguis) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e07034ecef4493045f1c3719e67e332eb28f022/pkg/util/admission/io_load_listener.go#L313)):*
> ```Go
> 		io.diskBW.bytesWritten = metrics.DiskStats.BytesWritten
> 		io.diskBW.incomingLSMBytes = cumLSMIncomingBytes
> 		io.setCumulativeStoreInternalIntervalMetrics(metrics)
> ```

isn't this simply `io.cumFlushWriteThroughput = metrics.Flush.WriteThroughput`?

**Review by coolcom200 — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88972)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @sumeerbhola)

___
*[`-- commits` line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDhV5Kn9fFVzGea2rz3):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Reminder to update the PR description to be the same as this commit.
</blockquote></details>

Done.
___
*[`pkg/util/admission/io_load_listener.go` line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDhVLSjDJ1e7Cf1IKMA:-NE2FNSLCAqIz50vEU0X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6b9572a6982478846d6ad33ce9970af80882537/pkg/util/admission/io_load_listener.go#L175)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/storeInternalIntervalMetrics/storeInternalMetrics

And change the comment to say something like:
These can represent either cumulative metrics, or over an interval of time. The latter is possible since the data representation here allows for subtraction between two cumulative storeInternalMetrics.

Actually, since you are calling `adjustTokensInner` with pebble.ThroughputMetric, just remove this wrapper struct. It is not adding any value, and we are not preserving the wrapping through the method calls. Then we simply have `cumFlushWriteThroughput` as a field in `ioLoadListenerState`.
</blockquote></details>

Done.
___
*[`pkg/util/admission/io_load_listener.go` line 313 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-NDiq_Mt39pelTRqlmRy:-NE2FODvA2h5w-Hj9WMU:b-jht1hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e07034ecef4493045f1c3719e67e332eb28f022/pkg/util/admission/io_load_listener.go#L313)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

isn't this simply `io.cumFlushWriteThroughput = metrics.Flush.WriteThroughput`?
</blockquote></details>

Yes it is thank you for pointing this out! Updated!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88972#-:-NE2eKhF-VFoppUyMngD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

**Pull request merged**
