### PR TITLE
roachtest: adjust tpchvec and tpcdsvec

### PR DESCRIPTION
**Pull request by yuzefovich**
**roachtest: add new tpchvec config**

This commit adds a new `tpchvec/perf_no_stats` config that is the same
as `tpchvec/perf` except for the fact that stats creation is disabled.
The plans without stats are likely to be different, so it gives us an
easy way to get more test coverage. One caveat here is that query
9 without stats takes insanely long to run, so some new plumbing has
been added to skip that query.

Additionally, `tpcdsvec` has been adjusted. The test runs all queries
with and without stats present with `on` and `off` vectorize options.
However, when stats are not present, `on` config will be reduced to
`off` because of `vectorize_row_count_threshold` heuristic. This commit
disables that heuristic.

Release note: None

**roachtest: switch the config order in tpchvec/perf**

Let's see whether it makes difference to occasional failures of
`tpchvec/perf` which are very hard to explain.

This commit also changes the workload command for `perf` config to run
only against node 1, thus, eliminating one possible source of
"randomness" for the failures.

Addresses: #49955.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49966#-M9ORRO-1r3sx7nLHQ8B:-M9ORRO-1r3sx7nLHQ8C:bctjdxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7f503d47823910f0439c6ecc00971d1339a7ff/pkg/cmd/roachtest/tpchvec.go#L171)):*
> ```Go
> 	// Since this is a performance test, each query should be run with both
> 	// vectorize modes.
> 	return []bool{false, true}
> ```

As usual with these changes, could you do a quick local run to make sure nothing breaks?
___
*[pkg/cmd/roachtest/tpchvec.go, line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49966#-M9ORgRi-8DSGXMSc4cD:-M9ORgRi-8DSGXMSc4cE:bqwkb13) ([raw file](https://github.com/cockroachdb/cockroach/blob/79c79beb92d09758537a7cb018d0b19cdede0f62/pkg/cmd/roachtest/tpchvec.go#L425)):*
> ```Go
> 	testCase tpchVecTestCase,
> 	testRun func(ctx context.Context, t *test, c *cluster, version crdbVersion, tc tpchVecTestCase),
> 	disableStatsCreation bool,
> ```

Can you make the stats creation part of the base test and override that in `tpchVecPerfTest` instead of introducing a flag to this general function? It seems wrong to introduce an argument for all test cases when it is only used for one.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49966#-M9ORRO-1r3sx7nLHQ8B:-M9OjH9y5714W3YQi438:b-rz7kuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7f503d47823910f0439c6ecc00971d1339a7ff/pkg/cmd/roachtest/tpchvec.go#L171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

As usual with these changes, could you do a quick local run to make sure nothing breaks?
</blockquote></details>

Sure, kicked off the run of old `perf` and new `perf_no_stats` configs.
___
*[pkg/cmd/roachtest/tpchvec.go, line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49966#-M9ORgRi-8DSGXMSc4cD:-M9Odaij5il6lmWaHj7K:b7xlclw) ([raw file](https://github.com/cockroachdb/cockroach/blob/79c79beb92d09758537a7cb018d0b19cdede0f62/pkg/cmd/roachtest/tpchvec.go#L425)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can you make the stats creation part of the base test and override that in `tpchVecPerfTest` instead of introducing a flag to this general function? It seems wrong to introduce an argument for all test cases when it is only used for one.
</blockquote></details>

Done.

However, we can't easily move the stats creation into the base case because `tpchVecPerfTest` reuses that logic. I looked into whether we could create stats in the base and then delete them (when stats creation is disabled), but our docs say that you need to restart the nodes for the statistics cache to be cleared. I think it's ok that every test config will be determining whether it needs the stats or not.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49966#-M9ORRO-1r3sx7nLHQ8B:-M9Q2lGy9XcBDG2f-5kU:bh1dbwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7f503d47823910f0439c6ecc00971d1339a7ff/pkg/cmd/roachtest/tpchvec.go#L171)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Sure, kicked off the run of old `perf` and new `perf_no_stats` configs.
</blockquote></details>

I added a skip of query 9 for "no stats" case (because it was taking forever), and then rerun both `perf` and `perf_no_stats` configs, and the tests passed.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49966#-:-M9TF9di648zglDZXw3w:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Pull request merged**
