### PR TITLE
serverutils: clean up some interfaces

### PR DESCRIPTION
**Pull request by knz**
Epic: CRDB-18499
Part of solving #107058.
Informs #106772.

In this commit:

- `TestTenantInterface` renamed to `ApplicationLayerInterface`.

- `TestServerInterface` split into:

  - `StorageLayerInterface` containing most of the methods previously
    in `TestServerInterface`.

  - `TenantControlInterface` with just the methods relating to
    starting the service for secondary tenants.

- Relevant methods moved from `TestServerInterface` to
  `ApplicationLayerInterface`:

  - `ServingSQLAddr()` - renamed to `AdvSQLAddr()`
  - `RPCAddr()`
  - `LeaseManager()`
  - `DistSenderI()`
  - `MigrationServer()`
  - `SetDistSQLSpanResolver()`
  - `CollectionFactory()`
  - `SystemTableIDResolver()`

- Removed `HostSQLAddr()` - use `.SystemLayer().AdvSQLAddr()` instead.

- `AdvSQLAddr()` (previously `ServingSQLAddr()`) was
  simplified to always return the advertised SQL address for the
  current layer.

- Updated comments/docstrings for the interfaces.

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
I like the rename of TenantOrServer for sure and I also like the addition of SystemLayer(). 

I could see an argument for keeping an embedded ApplicationLayerInterface if we find transitioning tests to this API too difficult, but I'd prefer that we get to this more explicit access if we can.

**Review by yuzefovich — COMMENTED** [review]
I too like how it turns out, only a few nits from me.

> Reviewed 9 of 102 files at r3, 3 of 20 files at r4, 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-:-NaJgfeiAlkG0WzUPEiQ:b-amq6o1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @herkolategan, @knz, @shermanCRL, and @smg260)

___
*[`-- commits` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJbhc61Jt2PNcqfY2q):*
nit: probably worth calling out the change in `ServingSQLAddr` (which was the only place that had different logic when default test tenant was started), removal of `HostSQLAddr` method, and inclusion of `QueryTableID` and friends methods.
___
*[`-- commits` line 50 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJg9Wt4HCTqgvSR3TN):*
nit: did you mean "important interfaces"?
___
*[`pkg/server/testserver.go` line 462 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJbRnp6l7mmILHpfvl:-NaJbRnp6l7mmILHpfvm:biy9gvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c617efede2c033bd869aa556109034a0bc004ba4/pkg/server/testserver.go#L462)):*
> ```Go
> }
> 
> // SQLInstanceID is part of the serverutils.TestServerInterface XX.
> ```

nit: XXes on SQLInstanceID and StatusServer in the first commit.
___
*[`pkg/testutils/serverutils/api.go` line 466 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJgLeM76EDrUP9V5O7:-NaJgLeM76EDrUP9V5O8:bj8cauv) ([raw file](https://github.com/cockroachdb/cockroach/blob/018d40cd56fc65c6f91f314b9d5b65b43b83ab33/pkg/testutils/serverutils/api.go#L466)):*
> ```Go
> 	// TenantCapabilitiesReader retrieves a reference to the
> 	// capabilities reader.
> 	TenantCapabilitiesReader() tenantcapabilities.Reader
> ```

nit: should `TenantCapabilitiesReader` be in `TenantControlInterface`?
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJeRK0A0jpIFx5U6fi:-NaJeRK0A0jpIFx5U6fj:b-joiuyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c617efede2c033bd869aa556109034a0bc004ba4/pkg/testutils/serverutils/test_server_shim.go#L161)):*
> ```Go
> 	// TODO(knz): Rename this to StartApplicationService. Take the
> 	// deployment mode as parameter instead of using a separate method.
> 	StartTenant(ctx context.Context, params base.TestTenantArgs) (ApplicationLayerInterface, error)
> ```

nit: perhaps for the follow-up, but should we rename `base.TestTenantArgs` and alike too?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107612)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @herkolategan, @shermanCRL, @smg260, and @yuzefovich)

___
*[`-- commits` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJbhc61Jt2PNcqfY2q):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: probably worth calling out the change in `ServingSQLAddr` (which was the only place that had different logic when default test tenant was started), removal of `HostSQLAddr` method, and inclusion of `QueryTableID` and friends methods.
</blockquote></details>

Done.
___
*[`-- commits` line 50 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJg9Wt4HCTqgvSR3TN):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: did you mean "important interfaces"?
</blockquote></details>

Indeed. Thanks
___
*[`pkg/server/testserver.go` line 462 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJbRnp6l7mmILHpfvl:-NaM5T674O5vEmUqdll3:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c617efede2c033bd869aa556109034a0bc004ba4/pkg/server/testserver.go#L462)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: XXes on SQLInstanceID and StatusServer in the first commit.
</blockquote></details>

Fixed.
___
*[`pkg/testutils/serverutils/api.go` line 466 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJgLeM76EDrUP9V5O7:-NaM5W0NCd4XTafR1bj2:b-3fi7sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/018d40cd56fc65c6f91f314b9d5b65b43b83ab33/pkg/testutils/serverutils/api.go#L466)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should `TenantCapabilitiesReader` be in `TenantControlInterface`?
</blockquote></details>

I don't feel it should - it's not a control interface.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-NaJeRK0A0jpIFx5U6fi:-NaM6J5S93-XX21XhVWr:b-srx5jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c617efede2c033bd869aa556109034a0bc004ba4/pkg/testutils/serverutils/test_server_shim.go#L161)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps for the follow-up, but should we rename `base.TestTenantArgs` and alike too?
</blockquote></details>

Let's do it in a different PR.

**Review by herkolategan — COMMENTED** [review]
Lovely separation of concerns, and a welcome improvement. I think this will help overall readability in the tests as well. Didn't see anything I don't agree with. Thanks for doing this!

> Reviewed 70 of 102 files at r3, 3 of 20 files at r4, 3 of 117 files at r8, 115 of 115 files at r12, 1 of 1 files at r13, 112 of 112 files at r14, 2 of 2 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-:-NaN43rU0sNJ4aKyxQWn:bahx3hq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @shermanCRL, @smg260, and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Nice work! :lgtm:

> Reviewed 1 of 117 files at r8, 7 of 115 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107612#-:-NaNFzN53M26YryRvFUa:b-8ewgme)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @shermanCRL, and @smg260)

**Review by yuzefovich — APPROVED** [review]

**Comment by knz** [comment]
Let's try it!
But i'll avoid batching to ensure if it fails noone else is inconvenienced.

bors r=yuzefovich,stevendanna single on

**Comment by yuzefovich** [comment]
Looks like this PR is still included in a batch with others. Perhaps "bors r=..." and "single on" don't work together [ref](https://cockroachlabs.slack.com/archives/C0HM2DZ34/p1673378100878439?thread_ts=1673375031.618689&cid=C0HM2DZ34).

bors r+ single on

**Pull request merged**
