### PR TITLE
sql: update tpcc and tpch stats

### LINKED ISSUE #72332: opt: update scan cost model with column size from table statistics
This is follow-up work to #55697 to use column size information in the optimizer cost model for scans.

Epic: CRDB-10034

### PR DESCRIPTION
**Pull request by rharding6373**
This change rewrites the stats for tpcc and tpch to include the new
table statistic avg_size.

Fixes: #72332

Release note: None

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
I wrote up the steps I followed in a new wiki page for posterity (thanks to @rytaft for the initial instructions), so you may be interested in reviewing that, too: https://cockroachlabs.atlassian.net/wiki/spaces/SQLQUERIES/pages/2448720032/Running+New+TPCC+and+TPCH+Stats

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-:-Mwiqnj72Y74WppiAMzm:b-v767ej)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

**Review by rytaft — COMMENTED** [review]
Awesome! Thanks for writing this up.

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-:-MwiweHt9EqQXz47bHtP:b-qwo9ui)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpcc, line 1750 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-MwitaAS3OMwKd6uAgSC:-MwitaAS3OMwKd6uAgSD:b-hlvf08) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe85c83ed4e81afdd5f95e53d617a52e5b6a16bc/pkg/sql/opt/memo/testdata/stats_quality/tpcc#L1750)):*
> ```
> 
> ----Stats for consistency_12_merge_join_3----
> WARNING: No previous statistics output was found. To collect actual statistics,
> ```

Looks like you need to run this one with `-rewrite-actual-stats=true`. No need to worry about possible regressions since this is a consistency check, not part of the main benchmark, but would still be good to update the stats.

**Review by rharding6373 — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-:-Mwm7_FIC74-YiF9YNK8:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpcc, line 1750 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-MwitaAS3OMwKd6uAgSC:-Mwm7XFT7_Xcy-qju3ya:b-jkgjy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe85c83ed4e81afdd5f95e53d617a52e5b6a16bc/pkg/sql/opt/memo/testdata/stats_quality/tpcc#L1750)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Looks like you need to run this one with `-rewrite-actual-stats=true`. No need to worry about possible regressions since this is a consistency check, not part of the main benchmark, but would still be good to update the stats.
</blockquote></details>

Thanks for catching this! Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-:-Mwm9X3r9tfNh3Ov-jLK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[-- commits, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-Mwm91Wn9K1DPcbu2_t3):*
nit: don't forget to squash this one before you merge

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77019)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

___
*[-- commits, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77019#-Mwm91Wn9K1DPcbu2_t3):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: don't forget to squash this one before you merge
</blockquote></details>

Done.

**Pull request merged**
