### PR TITLE
sql: fix statement-bundle recreate

### PR DESCRIPTION
**Pull request by cucaroach**
Statement bundle recreate throws this error when starting:

```
ERROR: unimplemented: cannot use SHOW LAST QUERY STATISTICS as a statement source
SQLSTATE: 0A000
```

Fix it by disabling infer of result types which forces use of prepare
path which doesn't support observer statements.

Release justification: non-production code
Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
ok but please add a test.

It's also a bug fix, so you can add a release note. 

I also disagree with your release justification, it's a good bug fix and deserves to be justified as such.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-:-N9g9EGw2L_4-ZSye74g:b-9f3jog)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[`pkg/cli/statement_bundle.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-N9g96NQ6NhNJpFGHwZU:-N9g96NQ6NhNJpFGHwZV:b-lhh8s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9922028d1f344672a660abd3c486debafb5d59db/pkg/cli/statement_bundle.go#L182)):*
> ```Go
> 	// env.sql frequently does nothing and has syntax errors so just warn.
> 	if err := conn.Exec(ctx, string(bundle.env)); err != nil {
> 		cliCtx.PrintfUnlessEmbedded("WARNING: env.sql didn't load: %v", err)
> ```

nit: lowercase `warning`, and prefix it with `# `

**Review by yuzefovich — APPROVED** [review]
Thanks! I remember running into this at some point, :lgtm: It would also be good to backport this.

I agree with Raphael that a test would be good to add, but I'm not sure it deserves a release note - this is for `cockroach debug` command which I expect to be internal-only in general and `statement-bundle recreate` in particular since it is intended to be used exclusively by CRDB engineers.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-:-N9gJ22d0xrTKOK6JaPB:bua47p9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you for fixing this!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-:-N9gblgQ1e-L0FKuwSCf:b-l7y28j)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by cucaroach — COMMENTED** [review]
Okay figuring out how to test took longer than fixing the issue but such is life!   Now we can batch basic regressions, which is nice.  Also I removed the env.sql bit, I have more along that line I'll pull out into a separate PR.   RTAL!   TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-:-N9qdcIb1B4_P2umhWfA:b-ssqcf8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @knz, @michae2, and @yuzefovich)

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86303)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz, @michae2, and @yuzefovich)

___
*[`pkg/cli/statement_bundle.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-N9g96NQ6NhNJpFGHwZU:-N9qdtl8-nLpT0dq7qFh:b-j568pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dfd782873ac185372080552e186251487a99241/pkg/cli/statement_bundle.go#L182)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: lowercase `warning`, and prefix it with `# `
</blockquote></details>

removed, but curious, why the #?

**Review by cucaroach — COMMENTED** [review]
Yahor, 22.1.5 doesn't seem to have this problem so I don't think we need to backport or have you seen 22.1 branch fail like this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-:-N9qeoD9DWBGLJOVnM34:biewsh4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz, @michae2, and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
> Yahor, 22.1.5 doesn't seem to have this problem so I don't think we need to backport or have you seen 22.1 branch fail like this?

I thought I saw this failure mode on 22.1 binary, but I'm not certain, so I'm probably mistaken, nvm.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86303#-:-N9qnsZpAv_3RUEPAQ_V:bnxhtty)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz)

**Comment by knz** [comment]
i'd like to offer this alternative  #86484

I confirm 22.1 is not affected. This is caused by the move to pgx early in the 22.2 release cycle.

**Comment by cucaroach** [comment]
> i'd like to offer this alternative #86484
> 
> I confirm 22.1 is not affected. This is caused by the move to pgx early in the 22.2 release cycle.

Thanks @knz!   Glad I brought in more authoritative eyes to look at this!  Should I pare my changes down to just the unit test or did you add a smoke test for `statement-bundle recreate` and I just missed it?

**Comment by cucaroach** [comment]
This was all fixed via: https://github.com/cockroachdb/cockroach/pull/86484

**Pull request closed without merging**
