### PR TITLE
plpgsql: add support for FETCH and MOVE statements

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: implement builtin function for FETCH statements

This patch adds the undocumentd `crdb_internal.plpgsql_fetch` builtin function,
which seeks a cursor by the specified number of rows in the specified
direction, and then returns the row at the ending location (if any). It reuses
the same logic as the SQL FETCH and MOVE statements. Note that it differs from
the SQL behavior for the `ALL` variants, since it only returns one row. This is
consistent with PLpgSQL cursor behavior.

The builtin function has 4 parameters: the name of the cursor, the seek
direction (an integer representing `tree.FetchType`), the seek count
(0 if not applicable), and a tuple containing typed NULL values that represents
the expected return types for the columns. This type argument is similar to
the one for `crdb_internal.assignment_cast`, with one addition: the result
columns are padded with NULLs or truncated as necessary to fit the number
of expected types.

When the actual types returned by the cursor must be coerced to the expected
types, an explicit cast is used, but width truncation is disallowed. This is
in line with PG behavior, which allows casting a String to an Int, but does
not allow casting a string like 'abc' to a Char.

Informs #109709

Release note: None

#### plpgsql: add support for FETCH and MOVE statements

This patch adds support for the PLpgSQL FETCH and MOVE statements,
which seek and return rows from a cursor. This is handled by a builtin
function, `crdb_internal.plpgsql_fetch`, which calls into the same logic
that implements SQL FETCH and MOVE. Since it is possible to call `FETCH`
with `INTO` variables of different types, the `crdb_internal.plpgsql_fetch`
builtin takes an argument that supplies the expected column types as a
tuple of typed NULL values like this: `(NULL::INT, NULL::BOOL)`. The
actual types supplied by the cursor are coerced into the expected types.

Note that the current implementation does not support using dynamic
expressions in the FETCH/MOVE direction; only constant integer values.
Dynamic direction counts like `FORWARD x` are not allowed in SQL syntax,
but are allowed by PLpgSQL.

Informs #109709

Release note (sql change): Added support for PLpgSQL FETCH and MOVE
statements. Similar to SQL FETCH/MOVE statements, commands that would
seek the cursor backward will fail. In addition, expressions other than
constant integers are not yet supported for the `count` option.

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first two commits are from https://github.com/cockroachdb/cockroach/pull/110709.

**Review by rharding6373 — APPROVED** [review]
:lgtm: This is very cool work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-:-Nfm5q5k637IGOqwz58N:b-yr23mb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/sql_cursor.go` line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-Nfm-VEaCyvaFcqfZ5NX:-Nfm-VEaCyvaFcqfZ5NY:b-pf1zfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6f9682004771076594e4953c016f73de24c2ba/pkg/sql/sql_cursor.go#L324)):*
> ```Go
> 	withHold   bool
> 	// isContainer indicates that the rows for the cursor query have been read in
> 	// full, so there is no need to set the transaction sequence number.
> ```

For my ignorance, why is this called `isContainer` and not something like `allRowsRead`? I don't see the connection.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 574 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-Nfm3SBq6mgB0mQLjqie:-Nfm3SBq6mgB0mQLjqif:b-k0crh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e648b68da553aa6f4b10e6e824772b08ebf6381/pkg/sql/opt/optbuilder/plpgsql.go#L574)):*
> ```Go
> 				if t.Cursor.FetchType == tree.FetchAll || t.Cursor.FetchType == tree.FetchBackwardAll {
> 					panic(pgerror.New(
> 						pgcode.FeatureNotSupported, "FETCH statement cannot return multiple rows",
> ```

It would be nice to have telemetry for this feature.
___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_builtins` line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-Nfm2PP61n7ZR-v2WSZw:-Nfm2PP61n7ZR-v2WSZx:b-pjaqt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6f9682004771076594e4953c016f73de24c2ba/pkg/sql/logictest/testdata/logic_test/plpgsql_builtins#L189)):*
> ```
> #   Result Types: Tuple
> #
> # Codes for FETCH directions:
> ```

Could you add a test for 5, and also for invalid directions e.g., -1

**Review by DrewKimball — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-:-Nftros1BA8jshzf9gc2:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/sql_cursor.go` line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-Nfm-VEaCyvaFcqfZ5NX:-NftpvptBMq3VJy7xu4l:b-nupv86) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6f9682004771076594e4953c016f73de24c2ba/pkg/sql/sql_cursor.go#L324)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

For my ignorance, why is this called `isContainer` and not something like `allRowsRead`? I don't see the connection.
</blockquote></details>

The rows are held in a `rowContainer` for PLpgSQL cursors. I changed the name to `eagerExecution`, does that sound a bit better?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 574 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-Nfm3SBq6mgB0mQLjqie:-Nftri289fuTHE2kH77n:bqnq621) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e648b68da553aa6f4b10e6e824772b08ebf6381/pkg/sql/opt/optbuilder/plpgsql.go#L574)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It would be nice to have telemetry for this feature.
</blockquote></details>

Actually, postgres doesn't support this either.
___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_builtins` line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111318#-Nfm2PP61n7ZR-v2WSZw:-Nfts3vcDsPTh84QZoNw:b597n47) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6f9682004771076594e4953c016f73de24c2ba/pkg/sql/logictest/testdata/logic_test/plpgsql_builtins#L189)):*
>Could you add a test for 5

That one's at line 528. I think the test cases are exhaustive in terms of valid directions.

>and also for invalid directions e.g., -1

Good idea, done. I also added some parameter validation to the builtin function.

**Pull request merged**
