### PR TITLE
hlc: remove locking in Physical(Now|Time), addresses 30520

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes https://github.com/cockroachdb/cockroach/issues/30520

Release note (performance improvement): Remove locking when reading physical time

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Addresses #30520

I don't think Github will pick this up. Try one of these: https://help.github.com/articles/closing-issues-using-keywords/.

@bdarnell, want to take a look?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32225#-:-LR8TV3-AkAlZvRqN8lM:b8ay5fc)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/hlc/hlc.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32225#-LR8U3ZbC437fRb-hLdN:-LR8U3ZbC437fRb-hLdO:bo12iqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0cb42b46110be7159bb5c12c974dc057a958cf1/pkg/util/hlc/hlc.go#L222)):*
> ```Go
> }
> 
> // getPhysicalClock locks mu in order to access the physical clock, check for
> ```

Let's name these methods something even more clear. How about `getPhysicalClockAndCheck{Locked}`.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32225)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/hlc/hlc.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32225#-LR8U3ZbC437fRb-hLdN:-LR8ZhhT6vnUQpGyEEgu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0cb42b46110be7159bb5c12c974dc057a958cf1/pkg/util/hlc/hlc.go#L222)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's name these methods something even more clear. How about `getPhysicalClockAndCheck{Locked}`.
</blockquote></details>

Done.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32225)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
:lgtm: nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32225#-:-LR8mpy300LK6EMIJyj4:b-7yytuz)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
Ok, try now.

**Comment by jordanlewis** [comment]
Sweet! Does this have a noticeable performance impact on any of our tested workloads?

**Comment by nvanbenschoten** [comment]
We do see these two methods show up on large machines in CPU and mutex profiles. I've also seen them be the cause of goroutine preemption in execution traces. I'd spin up a single-node cluster with a 32-core machine and hit it with `kv95`. Take a look at the baseline throughput and those two profile types before and after this change. Let me know if you need help setting that all up.

**Pull request merged**
