### PR TITLE
opt: pass stronger ordering requirement through limit/offset

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add ordering property tests for limit/offset

Release note: None

#### opt: pass stronger ordering requirement through limit/offset

Limit and Offset currently only provide the ordering that they require
of their input. This change improves them to pass through stronger
orderings. For example, if the internal ordering is `a+,b+` and the
requirement on limit/offset is `a+,b+,c+`, the latter can be passed
through.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28076#-:-LIkxBAiCKfGc0LF1_AF:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/props/ordering_choice.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28076#-LIkwAl74Ink2yB53k3c:-LIkwAl74Ink2yB53k3d:blq2q47) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ba3c4c03158b75dc2630b84ce1b827018d71a7/pkg/sql/opt/props/ordering_choice.go#L239)):*
> ```Go
> //   +(1|2)            !subset of +1 opt(2)
> //
> func (oc *OrderingChoice) SubsetOf(other *OrderingChoice) bool {
> ```

I wonder if we should change the name of this to something like `LessRestrictiveThan` (and invert the result), since it's confusing that `+1,-2 is a subset of +1`. That would become `+1 is less restrictive than +1,-2`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28076)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/props/ordering_choice.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28076#-LIkwAl74Ink2yB53k3c:-LIky2wNBC4G03Pw3YXh:br9gf1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ba3c4c03158b75dc2630b84ce1b827018d71a7/pkg/sql/opt/props/ordering_choice.go#L239)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I wonder if we should change the name of this to something like `LessRestrictiveThan` (and invert the result), since it's confusing that `+1,-2 is a subset of +1`. That would become `+1 is less restrictive than +1,-2`.
</blockquote></details>

Indeed, this function gets me confused every time I use it. For some reason "less restrictive" still makes me think about it. How about `Implies` (without inverting)? That seems more in line with the logic of where it is being used.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/props/ordering_choice.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28076#-LIkwAl74Ink2yB53k3c:-LIkz1w595HsQRSMCWH-:b-ldkk8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ba3c4c03158b75dc2630b84ce1b827018d71a7/pkg/sql/opt/props/ordering_choice.go#L239)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Indeed, this function gets me confused every time I use it. For some reason "less restrictive" still makes me think about it. How about `Implies` (without inverting)? That seems more in line with the logic of where it is being used.
</blockquote></details>

I think the problem I have with "less restrictive" is that it can implicitly suggest that if you have two orderings, one must be "less restrictive" than the other, which is not the case.

**Review by andy-kimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28076)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/props/ordering_choice.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28076#-LIkwAl74Ink2yB53k3c:-LIl-5anDZX5sR59Xg85:bwbwn1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ba3c4c03158b75dc2630b84ce1b827018d71a7/pkg/sql/opt/props/ordering_choice.go#L239)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think the problem I have with "less restrictive" is that it can implicitly suggest that if you have two orderings, one must be "less restrictive" than the other, which is not the case.
</blockquote></details>

`Implies` works for me.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28076)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/props/ordering_choice.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28076#-LIkwAl74Ink2yB53k3c:-LIlGwG71Z3ipWFk-7I6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ba3c4c03158b75dc2630b84ce1b827018d71a7/pkg/sql/opt/props/ordering_choice.go#L239)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`Implies` works for me.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28076#-:-LIlM-_sEPut5d2_R1-t:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
