### PR TITLE
col*: remove coltypes.T type system

### LINKED ISSUE #43559: coltypes: refactor colexec types
Our current type system used in the vectorized engine has a big disadvantage:
- it is "lossful" - doing the conversion of `types.T -> coltypes.T -> types.T` will not always return the same type that it is started with.

This will very likely (if not already) cause issues and additional burden when we need to specialize the behavior of an operation based on the "actual" `types.T` type of a column, but we might not have that information anymore.

We should fix it. One idea that Jordan mentioned (which I agree with) is that coltypes should be an extension of normal `types` that will also hold a "physical type" - the way we represent it in Go.

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR removes `coltypes.T` type system which had several
drawbacks. I believe the main reason it was introduced in the first
place was that for the purposes of code generation we need to have
"something" to switch on to be able to choose the "resolved" overload
among many generated ones. The complication here is that we have cases
where multiple type families have the same physical representation (e.g.
`types.BytesFamily` and `types.StringFamily`), and we don't want to generate
the same code multiple times. Furthermore, we have cases where a single
type family (`types.IntFamily`) has different physical representation
based on the width of the type.

To address both of these limitations, that "something" will be
"canonical" type family and a width of the type.  "Canonical" type families
are representatives from a set of "equivalent" type families where
"equivalence" means having the same physical reprentation.

The overload structs have been refactored to introduce a hierarchy that
is useful in iterating over in the templates and also to have links
between different layers of that hierarchy among the corresponding
structs (so that in every "scope" in the template we have access to the
necessary fields). These structs are designed to be used by the code
generation with the following patterns:
```
//   switch canonicalTypeFamily {
//     switch width {
//       <resolved one arg overload>
//     }
//   }
//
//   switch leftCanonicalTypeFamily {
//     switch leftWidth {
//       switch rightCanonicalTypeFamily {
//         switch rightWidth {
//           <resolved two arg overload>
//         }
//       }
//     }
//   }
```

For every canonical type we add a special `anyWidth = -1` value of the
supported width that will be the default case for the width switch. For
example, for the types that don't pay attention to the width a code
snippet similar to the following will be generated:
```
//  switch width {
//    case -1:
//    default:
//      <do stuff>
//  }
```

All templates that use overloads have been refactored to use these
patterns. Additionally, refactored `overloads.go` has been split up in
multiple files.

Fixes: #43559.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think it is RFAL.

As described in the last paragraph of the PR description, there is still one thing that I'm not happy about, but I've been kinda stuck, and it's not that important to address other than for some code removal/simplification, and that can wait or be ignored.

**Comment by yuzefovich** [comment]
Results of running `colexec` benchmarks are [here](https://gist.github.com/yuzefovich/ce66486c83d8eb33badf5a48ab7a1d2a). There are some changes (mostly positive - reduced allocations), but nothing it too concerning and could be optimized separately, later.

**Review by asubiotto — CHANGES_REQUESTED** [review]
In general this looks pretty good! Great work.

> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-:-M6EeR3D0Hoz3D3y2hZQ:b3nbxes)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/vec.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ESXOZ1CpBoNAzEbYZ:-M6ESXOZ1CpBoNAzEbY_:b-2hds59) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/coldata/vec.go#L177)):*
> ```Go
> 	case types.DecimalFamily:
> 		return &memColumn{t: t, canonicalTypeFamily: canonicalTypeFamily, col: make([]apd.Decimal, n), nulls: nulls}
> 	case types.TimestampTZFamily:
> ```

What about `TimestampFamily`?
___
*[pkg/col/coldata/vec_tmpl.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ESIf619zr059zihtX:-M6ESIf619zr059zihtY:b-cbuuh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/coldata/vec_tmpl.go#L233)):*
> ```Go
> 			newVal := elem.(_GOTYPE)
> 			execgen.SET(target, rowIdx, newVal)
> 			// {{end}}
> ```

nit: the indentations are off for the width switches in this file
___
*[pkg/col/colserde/arrowbatchconverter.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ESdgc3uBT7dDJdcdy:-M6ESdgc3uBT7dDJdcdz:bfiji5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/colserde/arrowbatchconverter.go#L60)):*
> ```Go
> func NewArrowBatchConverter(typs []types.T) (*ArrowBatchConverter, error) {
> 	for i := range typs {
> 		if !typeconv.IsTypeSupported(&typs[i]) {
> ```

Can you use the `AllTypesSupported` function you added to `typeconv`?
___
*[pkg/col/typeconv/typeconv.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EP0dp5GzqHKxGmFNK:-M6EP0dp5GzqHKxGmFNL:b-lmgm12) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L25)):*
> ```Go
> // TypeFamilyToCanonicalTypeFamily maps all type families that are supported by
> // the vectorized engine to their "canonical" counterparts. "Canonical" type
> // families are representatives from a set of "equivalent" type families where
> ```

Instead of calling it a "Canonical" type family and having to explain what "canonical" means in this case, do you think it would be better to just call this `TypeFamilyToPhysicalTypeFamily`?
___
*[pkg/col/typeconv/typeconv.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EPbSbBdesbKPyFRwl:-M6EPbSbBdesbKPyFRwm:b-hqwno4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L63)):*
> ```Go
> 
> // IsTypeSupported returns whether t is supported by the vectorized engine.
> func IsTypeSupported(t *types.T) bool {
> ```

Might be more straightforward to access `TypeFamilyToCanonicalTypeFamily`, returning `true` if there is a corresponding element (and doing any family specific check after the access for ints for example). This'll avoid having to update this function too much.
___
*[pkg/col/typeconv/typeconv.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ETBQR0a_6OI7eoz5a:-M6ETBQS5wlrCq0GiXz3:b8px2gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L79)):*
> ```Go
> 		case 32:
> 			return true
> 		case 64:
> ```

I think you're missing the 0 width case here?
___
*[pkg/col/typeconv/typeconv.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EPzIgA75C24jWziZN:-M6EPzIgA75C24jWziZO:b-bq77hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L107)):*
> ```Go
> // be used at runtime. This method is unsafe because multiple logical types can
> // be represented by the same physical type.
> func UnsafeFromGoType(v interface{}) *types.T {
> ```

When is this used?
___
*[pkg/sql/colexec/rowstovec_tmpl.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EVOoV1jUlqU4nplxN:-M6EVOoV1jUlqU4nplxO:bsndjht) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/rowstovec_tmpl.go#L120)):*
> ```Go
> 			}
> 			if !converted {
> 				err = errors.Errorf("didn't convert EncDatumRows to ColVec for %s", t.Name())
> ```

Is there a way we can keep the ability to add a default case to the switch statement?
___
*[pkg/sql/colexec/execgen/placeholders.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EW3yaDS5rkxSmlXa1:-M6EW3yaDS5rkxSmlXa2:b-6ib2nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/placeholders.go#L42)):*
> ```Go
> // RETURNUNSAFEGET is a template function. Use this if you are not keeping data around
> // (including passing it to SET).
> func RETURNUNSAFEGET(target, i interface{}) interface{} {
> ```

Expand the comment to specify how it's different from UNSAFEGET.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EZjkH6pKdh04A2Ge6:-M6EZjkH6pKdh04A2Ge7:b-qyhbtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L77)):*
> ```Go
> // references to each other so that the necessary fields for the templating are
> // accessible via '.'. Only when we reach the bottom level (where
> // lastArgWidthOverload is) do we have the access to "resolved" overload
> ```

I think this comment could benefit from a bit more background (e.g. explaining what `lastArgWidthOverload` is). This code is pretty complicated to understand (at least for me and probably anyone new to the codebase), so the more documentation the better
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6E_CS43L8tyJg5K1S9:-M6E_CS43L8tyJg5K1SA:bjd9dz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L168)):*
> ```Go
> }
> 
> type argTypeOverload struct {
> ```

nit: comment
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6E_DxBENWpQRvDKLiW:-M6E_DxBENWpQRvDKLiX:bjd9dz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L191)):*
> ```Go
> }
> 
> type lastArgTypeOverload struct {
> ```

nit: comment
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6E_y924G_eXLnBlKcl:-M6E_y924G_eXLnBlKcm:b-u0oiw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L511)):*
> ```Go
> ) (newSameTypeOverloads []*oneArgOverload) {
> 	var combinableCanonicalTypeFamilies map[types.Family][]types.Family
> 	if base.IsBinOp {
> ```

nit: this seems better off as a switch statement
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6Ea3Ev5e6tVzKk-X3L:-M6Ea3Ev5e6tVzKk-X3M:b-dh5xqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L544)):*
> ```Go
> 					}
> 					var info *twoArgsResolvedOverloadInfo
> 					if base.IsBinOp {
> ```

This too
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 1932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6Edo0M5Lr__A2oU_ZY:-M6Edo0M5Lr__A2oU_ZZ:bduil1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L1932)):*
> ```Go
> 		switch b.Width {
> 		case 16:
> 			return "[]int16"
> ```

Why not handle these cases with `toPhysicalRepresentation`?
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 2245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EdkHv6aMvFz3tV4wn:-M6EdkHv6aMvFz3tV4wo:b-mi8iiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L2245)):*
> ```Go
> 		case 32:
> 			return "int32"
> 		case 64, anyWidth:
> ```

Is 0 an invalid width here?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48042)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/vec.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ESXOZ1CpBoNAzEbYZ:-M6NBRmK7Cs8ds_Lddp2:b-7qcorn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/coldata/vec.go#L177)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What about `TimestampFamily`?
</blockquote></details>

I chose `TimestampTZ` as the canonical family here because the behavior of our overloads is as if we're operating on `DTimestampTZ` (`DTimestamp` needs to be "normalized" into the time zone of eval context, and we don't do that).
___
*[pkg/col/coldata/vec_tmpl.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ESIf619zr059zihtX:-M6NBs_b7djJkaXQQXvU:b9n3jxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/coldata/vec_tmpl.go#L233)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: the indentations are off for the width switches in this file
</blockquote></details>

Yes, but we have no control over it - `{{end}}` is inside of `case` block whereas `{{range}}` is outside of it. We have cases like this in other places already, and it is unfortunate, but I don't think we can do anything about it.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ESdgc3uBT7dDJdcdy:-M6NCWu6Aq1J8hUz1dEe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/colserde/arrowbatchconverter.go#L60)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can you use the `AllTypesSupported` function you added to `typeconv`?
</blockquote></details>

Done.
___
*[pkg/col/typeconv/typeconv.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EP0dp5GzqHKxGmFNK:-M6NC_587R1ks0fkEPxJ:bvhaova) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L25)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of calling it a "Canonical" type family and having to explain what "canonical" means in this case, do you think it would be better to just call this `TypeFamilyToPhysicalTypeFamily`?
</blockquote></details>

To me that sounds slightly off - "type families" are logical concept, and it is not clear to me what "physical type family" would mean. I think what we want here is concise words that would mean "a type family representative among all type families that have the same physical representation". Maybe it's because it's already stuck in my mind, but I like "canonical" more than "physical" - "physical" could be a source of confusion to a reader while he might not know what "canonical" means, so he would need to look it up, but there would be no confusion.
___
*[pkg/col/typeconv/typeconv.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EPbSbBdesbKPyFRwl:-M6NF7yC33DJeknfMXSz:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L63)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be more straightforward to access `TypeFamilyToCanonicalTypeFamily`, returning `true` if there is a corresponding element (and doing any family specific check after the access for ints for example). This'll avoid having to update this function too much.
</blockquote></details>

Good point, done.
___
*[pkg/col/typeconv/typeconv.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6ETBQR0a_6OI7eoz5a:-M6NE8tj2oQJ0AYdRcxB:b-hemibx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L79)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you're missing the 0 width case here?
</blockquote></details>

I don't think so - here `t` is "true" type, and we support only ints with 16, 32, and 64 widths. In other places we do usually need a `0` case because dates and oids are mapped to `IntFamily` and could have `0` width.
___
*[pkg/col/typeconv/typeconv.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EPzIgA75C24jWziZN:-M6NFEZj08TvHUr0PPOT:b3pigkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/col/typeconv/typeconv.go#L107)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

When is this used?
</blockquote></details>

In two places: `colexec/utils_test.go` and `workload/workload.go`. This method already existed.
___
*[pkg/sql/colexec/rowstovec_tmpl.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EVOoV1jUlqU4nplxN:-M6NFVNt-2e5yNpFuHG8:bidszd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/rowstovec_tmpl.go#L120)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there a way we can keep the ability to add a default case to the switch statement?
</blockquote></details>

`anyWidth` will be replaced with `default`, and all canonical type families are expected to have `anyWidth` as their last supported width, so we can't have another `default` in "width switch".

We could have a `default` case for "family switch", added.
___
*[pkg/sql/colexec/execgen/placeholders.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EW3yaDS5rkxSmlXa1:-M6NHLBu8BMbuCUjsaKC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/placeholders.go#L42)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Expand the comment to specify how it's different from UNSAFEGET.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EZjkH6pKdh04A2Ge6:-M6NKSNf43CsdhK26tB9:b-s8nldu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L77)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this comment could benefit from a bit more background (e.g. explaining what `lastArgWidthOverload` is). This code is pretty complicated to understand (at least for me and probably anyone new to the codebase), so the more documentation the better
</blockquote></details>

Expanded the comment.

I find it extremely hard to articulate the purposes of these structs. I feel like the structs are quite artificial (i.e. there is no "pure" design behind them), and I structured them with two goals in mind - 1) desire to access necessary field for type and width switches using `.` in templates, and 2) ability to iterate over the structs and go "down" in the hierarchy.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6E_y924G_eXLnBlKcl:-M6NNgRq6DCuB0zA9iPi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L511)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: this seems better off as a switch statement
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6Ea3Ev5e6tVzKk-X3L:-M6NNhxE2GWzyCQesNSd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L544)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This too
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 1932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6Edo0M5Lr__A2oU_ZY:-M6NNp8QBOL_RR62gDoH:bsjj2l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L1932)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not handle these cases with `toPhysicalRepresentation`?
</blockquote></details>

Those two are different things: `GoTypeSliceName` returns the string for a "slice of values" whereas `toPhysicalRepresentation` returns the string for a "single value".
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 2245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EdkHv6aMvFz3tV4wn:-M6NOfog39nRfMWXOQ3l:b-yf9aqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L2245)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is 0 an invalid width here?
</blockquote></details>

Yes, it should be invalid - it would mean that the setup of overload structs or supported widths is somehow broken. Note that this method is only used during the code generation (i.e. not at runtime).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48042)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 1932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6Edo0M5Lr__A2oU_ZY:-M6NT2W238PPIvKaGtWr:b-unsbfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L1932)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Those two are different things: `GoTypeSliceName` returns the string for a "slice of values" whereas `toPhysicalRepresentation` returns the string for a "single value".
</blockquote></details>

The two functions are also used in a different way and during different times: `toPhysicalRepresentation` is used during initialization to populate overload-related structs, `GoTypeSliceName` is called during template execution and is invoked on the `.`, and that's why it has `argWidthOverloadBase` as the receiver.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-:-M6UPzYg7UQJjWXGPeZh:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EZjkH6pKdh04A2Ge6:-M6UP8STEsj83Nz3zOfc:bef2ua5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L77)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Expanded the comment.

I find it extremely hard to articulate the purposes of these structs. I feel like the structs are quite artificial (i.e. there is no "pure" design behind them), and I structured them with two goals in mind - 1) desire to access necessary field for type and width switches using `.` in templates, and 2) ability to iterate over the structs and go "down" in the hierarchy.
</blockquote></details>

It makes me kind of uneasy that it's so difficult to describe these structs. I don't think this is the time and place for a templating engine redesign, but it feels like we should make the effort to design this well at some point.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-:-M6V2Bst33vEnohwKmBS:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48042#-M6EZjkH6pKdh04A2Ge6:-M6V20ZoA82JrHgehCDa:btq7dm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d105cfa85124d0b8c5efb74efd477186cbb5c89/pkg/sql/colexec/execgen/cmd/execgen/overloads.go#L77)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It makes me kind of uneasy that it's so difficult to describe these structs. I don't think this is the time and place for a templating engine redesign, but it feels like we should make the effort to design this well at some point.
</blockquote></details>

This sounds like opening up a pandora box :scared:

**Pull request merged**
