### PR TITLE
roachprod: small fixes and refactors for pgurl

### PR DESCRIPTION
**Pull request by DarrylWong**
**roachprod: create certs for DefaultUser instead of roach**
Roachprod start creates certs for the default admin user.
Previously this user was named roach so the certs create
call created certs for user roach. However, now that the
user has changed to roachprod, this no longer works.

This change instead creates certs for DefaultUser, which
should reflect any changes to the naming.

**roachtest: remove roachtestutil.DefaultPGUrl**
This helper was created when most tests were running on insecure clusters.
This fact led to most urls being the same as no auth had to be done. However,
with secure mode being enabled on most tests, this is no longer true and most
tests stopped using this helper.

In the rare case it is used, usage varies a lot depending on the opts passed.
This defeats the purpose of it being the "default" url. This change replaces
DefaultPGUrl calls with roachprod.PGUrl instead.

**roachprod: create CockroachNodeCertsDir constant**
This change creates a constant for the default
crdb certs directory and uses it throughout roachprod
and roachtest instead of hardcoding "certs".

**roachprod: fix internal pgurls to have correct certs-dir and host**
Previously, internal pgurls would specify the certs-dir as c.localCertsDir,
a path is that is only present for the roachtest runner.

Additionally, internal pgurls now use localhost instead of the ip address.

This is done through a new PGURLOption, Localhost, which indicates if
localhost or the internal IP should be used. While it would be nice
to default to localhost for all internal pgurls, the way c.InternalIP
works is by parsing the InternalPgUrl.

Release note: None
Epic: None
Fixes: None

### CODE REVIEW

**Comment by DarrylWong** [comment]
[0.2 test run here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel?mode=builds)

😁 Gladly accepting alternative name ideas for the constant: 

https://github.com/cockroachdb/cockroach/blob/5df2a4bbbb12d2849a116067eea8e5a04d7e9424/pkg/roachprod/install/cluster_synced.go#L1611


Most of the diff is trivial - just replacing `certs` with the new constant, but also happy to split this up into four different PRs since most of the work is independent of each other.

**Comment by DarrylWong** [comment]
Ahh, upon further testing, it appears that it's not always okay to default to `localhost` for `InternalPgUrl`. Specifically, when we have a workload only node, it doesn't recognize `localhost` and needs the internal IP. It's not an issue to use the internal IP there since it doesn't look like workload verifies the host name. 

This isn't run into at all, since all workload calls use `{pgurl}`, but for correctness I'll leave it as just an option that the caller will have to specify instead of defaulting to it. `InternalPgUrl` is only used in two tests anyway.

Nothing should have changed but [rerunning internalpgurl related tests] just in case. (https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14099596?hideProblemsFromDependencies=false&hideTestsFromDependencies=false)

**Review by renatolabs — APPROVED** [review]
Nice improvements!

A few non-blocking questions/comments:

> when we have a workload only node, it doesn't recognize `localhost` and needs the internal IP

Could you elaborate? As far as I can tell, all current callers of `InternalPGUrl` now pass `Localhost: true`. What's a situation when we wouldn't need to do that?

*****

Not necessary in this PR, but something that will eventually come back to bite us is that we have _very_ similar logic for managing tenant certs. We can deal with this in follow up work, I'll be doing a bit of virtual cluster work in the near future so I feel I'll have to do something about it at that point.

https://github.com/cockroachdb/cockroach/blob/ee90e6426da817f429799690a0a310829f94c678/pkg/roachprod/install/cluster_synced.go#L1703

*****

Now that I took a closer look at the cert generation code, I'm not sure why we need _localhost_ at all. As far as I can tell, roachprod is explicitly passing the internal IP as a hostname when creating the cert (see below). Do you understand why we can't use the internal IP in the connection URL?

https://github.com/cockroachdb/cockroach/blob/ee90e6426da817f429799690a0a310829f94c678/pkg/roachprod/install/cluster_synced.go#L1830

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 29 of 29 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119323#-:-NrLNPaH6F_uL1i7Ud7Z:b-n9k1dv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

___
*[`pkg/cmd/roachprod/flags.go` line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119323#-NrLMrGm6jZM6jJ6BtK8:-NrLMrGm6jZM6jJ6BtK9:bspslrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9138b34b0f45f6aa7c4393bf80576e5b7a4263d6/pkg/cmd/roachprod/flags.go#L174)):*
> ```Go
> 		"external", false, "return pgurls for external connections")
> 	pgurlCmd.Flags().StringVar(&pgurlCertsDir,
> 		"certs-dir", fmt.Sprintf("./%s", install.CockroachNodeCertsDir), "cert dir to use for secure connections")
> ```

Pretty sure the `./` is not _necessary_, so we could drop the `fmt.Sprintf` if you want.
___
*[`pkg/roachprod/install/cluster_synced.go` line 1643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119323#-NrLMb0W8DCVfjBA7GRr:-NrLMb0W8DCVfjBA7GRs:b-wfz3ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dd1de457361b9b2fcaed209daac78f47fba4e4a/pkg/roachprod/install/cluster_synced.go#L1643)):*
> ```Go
> %[1]s cert create-ca --certs-dir=certs --ca-key=certs/ca.key
> %[1]s cert create-client root --certs-dir=certs --ca-key=certs/ca.key $TENANT_SCOPE_OPT
> %[1]s cert create-client testuser --certs-dir=certs --ca-key=certs/ca.key $TENANT_SCOPE_OPT
> ```

Curious: we don't really need `testuser`, yes? I see some tests seem to be using it but they could also just be using the `DefaultUser` now.

**Review by DarrylWong — COMMENTED** [review]
Discussed on slack but for notekeeping: `localhost` change has been reverted as we figured out it was a `psql` specific problem and the cert generation is fine for `InternalIP`. I'll write up an issue for the `psql` issue + proposed fix later (#119661).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119323#-:-NrLa2YMBYWNNOirMrC5:b8xkfqg)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachprod/flags.go` line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119323#-NrLMrGm6jZM6jJ6BtK8:-NrMivNi951seZTR9pKp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9138b34b0f45f6aa7c4393bf80576e5b7a4263d6/pkg/cmd/roachprod/flags.go#L174)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Pretty sure the `./` is not _necessary_, so we could drop the `fmt.Sprintf` if you want.
</blockquote></details>

Done.
___
*[`pkg/roachprod/install/cluster_synced.go` line 1643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119323#-NrLMb0W8DCVfjBA7GRr:-NrMrnydB-IMhrUzFF7m:bl1zv5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dd1de457361b9b2fcaed209daac78f47fba4e4a/pkg/roachprod/install/cluster_synced.go#L1643)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Curious: we don't really need `testuser`, yes? I see some tests seem to be using it but they could also just be using the `DefaultUser` now.
</blockquote></details>

No, I don't think so, removed it.

**Comment by DarrylWong** [comment]
[Reran the affected tests](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14139919?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true).

TFTR!

bors r=renatolabs

**Pull request merged**
