### PR TITLE
storage/engine: Reduce one copy in FindSplitKey by reusing previous key buf

### LINKED ISSUE #41602: storage/engine: optimize pebbleIterator.FindSplitKey
Noted during code review, `pebbleIterator.FindSplitKey()` copies the key on each iteration. Rather than pessimistically copying, we could simply call `Prev()` to back up to the correct key.  This would be done in the name of performance, so we should verify this impacts benchmarks. If it does, a similar change could be done to the RocksDB version of this function.

### PR DESCRIPTION
**Pull request by itsbilal**
Currently, we copy the best split key inside pebbleIterator.FindSplitKey so
that it can be returned to the caller at the very end. At the same time, we
also track the previous key in a separate buffer to aid with size tracking.

This change optimizes findSplitKey in the most common case to just return the
prevKey buffer instead of making a copy. If we come across the harder case
of a good key candidate followed by a span of invalid split keys, it still
makes the double copy just in case.

Fixes #41602 .

Release note: None.

### CODE REVIEW

**Comment by itsbilal** [comment]
Not a very significant improvement, but it does show up:

```
v1040-wn-rt-c-20-71:cockroach bilal$ benchstat ./bench_findsplitkey_old ./bench_findsplitkey_new
name                                     old time/op    new time/op    delta
MVCCFindSplitKey_Pebble/valueSize=32-12    51.8ms ± 2%    49.3ms ± 4%  -4.84%  (p=0.000 n=14+15)

name                                     old speed      new speed      delta
MVCCFindSplitKey_Pebble/valueSize=32-12  1.30GB/s ± 2%  1.36GB/s ± 5%  +5.14%  (p=0.000 n=14+15)
```

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42672)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_iterator.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuEzEWxDDGGV6gHH9X0:-LuEzEWxDDGGV6gHH9X1:b-mgx2j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L312)):*
> ```Go
> 			break
> 		}
> 	}
> ```

every time I've looked at this code I've disliked the duplication and sub-optimality of the above `noSplitSpans` loop and `isValidSplitKey` (sub optimal because it only removes `noSplitSpans` that are preceding `minSplitKey`) -- the duplication bothers me more.
___
*[pkg/storage/engine/pebble_iterator.go, line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuEoHjQAwliWQHVQStH:-LuEoHjQAwliWQHVQStI:b-wvgnv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L336)):*
> ```Go
> 			return bestSplitKey, nil
> 		}
> ```

This idea looks good, but I wonder if it can be written in a way that is simpler to understand. 
___
*[pkg/storage/engine/pebble_iterator.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuF07QT9hrvQi2kdIxL:-LuF07QUE4E9NW0T3E4L:b-luqtqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L350)):*
> ```Go
> 				bestSplitKey.Key = bestSplitKey.Key[:0]
> 				// Avoid comparing against minSplitKey on future iterations.
> 				mvccMinSplitKey.Key = nil
> ```

this can be set to nil even if only part of the if-condition is satisfied.
___
*[pkg/storage/engine/pebble_iterator.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuEzlWM6h0lFmxPXtSo:-LuEzlWM6h0lFmxPXtSp:b-3b0zge) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L380)):*
> ```Go
> 		// assuming it's a valid split key candidate.
> 		if (mvccMinSplitKey.Key == nil || !prevKey.Less(mvccMinSplitKey)) &&
> 			(len(noSplitSpans) == 0 || isValidSplitKey(prevKey.Key, noSplitSpans)) {
> ```

I don't think these checks are needed.
I tweaked the code here to make it more easy for me to understand, though ymmv.

```
func isValidSplitKey(key roachpb.Key, noSplitSpans []roachpb.Span) ([]roachpb.Span, bool) {
	var prefixToRemove int
	rv := true
	for i := range noSplitSpans {
		if key.Compare(noSplitSpans[i].EndKey) >= 0 {
			prefixToRemove = i
		}
		// We know key < EndKey. Is key >= StartKey
		if key.Compare(noSplitSpans[i].Key) >= 0 {
			rv = false
			break
		}
	}
	return noSplitSpans[prefixToRemove+1:], rv
}

// FindSplitKey implements the Iterator interface.
func (p *pebbleIterator) FindSplitKey(
	start, end, minSplitKey roachpb.Key, targetSize int64,
) (MVCCKey, error) {
	const timestampLen = 12

	sizeSoFar := int64(0)
	bestDiff := int64(math.MaxInt64)
	// found indicates that we have found a valid split key that is the best known so far.
	// an empty bestSplitKey => that split key is in prevKey, else it is in bestSplitKey.
	found := false
	prevKey := MVCCKey{}
	bestSplitKey := MVCCKey{}

	// Remove the no-split spans that precede the minimum split key.
	noSplitSpans := keys.NoSplitSpans
	noSplitSpans, _ = isValidSplitKey(minSplitKey, noSplitSpans)

	// Note that it is unnecessary to compare against "end" to decide to
	// terminate iteration because the iterator's upper bound has already been
	// set to end.
	mvccMinSplitKey := MakeMVCCMetadataKey(minSplitKey)
	p.SeekGE(MakeMVCCMetadataKey(start))
	for ; p.iter.Valid(); p.iter.Next() {
		mvccKey, err := DecodeMVCCKey(p.iter.Key())
		if err != nil {
			return MVCCKey{}, err
		}
		diff := targetSize - sizeSoFar
		if diff < 0 {
			diff = -diff
		}
		if diff > bestDiff {
			// We must have had a valid candidate in the past since we can't be worse than MaxInt64.
			if len(bestSplitKey.Key) == 0 {
				return prevKey, nil
			}
			return bestSplitKey, nil
		}
		// diff <= bestDiff.
		if mvccMinSplitKey.Key == nil || !mvccKey.Less(mvccMinSplitKey) {
			// Candidate since it is past the minimum split key.
			// Avoid comparing against minSplitKey on future iterations.
			mvccMinSplitKey.Key = nil
			valid := true
			if len(noSplitSpans) > 0 {
				noSplitSpans, valid = isValidSplitKey(mvccKey.Key, noSplitSpans)
			}
			if valid {
				// Valid candidate.
				bestDiff = diff
				found = true
				// Clear bestSplitKey since we will save the valid candidate in prevKey below.
				bestSplitKey.Key = bestSplitKey.Key[:0]

			} else {
				// Not valid. If the prevKey was a valid candidate, it must have cleared bestSplitKey,
				// in which case save it as the valid candidate.
				if found && len(bestSplitKey.Key) == 0 {
					bestSplitKey.Timestamp = prevKey.Timestamp
					bestSplitKey.Key = append(bestSplitKey.Key[:0], prevKey.Key...)
				}
			}
		}
		sizeSoFar += int64(len(p.iter.Value()))
		if mvccKey.IsValue() && bytes.Equal(prevKey.Key, mvccKey.Key) {
			// We only advanced timestamps, but not new mvcc keys.
			sizeSoFar += timestampLen
		} else {
			sizeSoFar += int64(len(mvccKey.Key) + 1)
			if mvccKey.IsValue() {
				sizeSoFar += timestampLen
			}
		}
		prevKey.Key = append(prevKey.Key[:0], mvccKey.Key...)
		prevKey.Timestamp = mvccKey.Timestamp
	}

	if found {
		if len(bestSplitKey.Key) == 0 {
			return prevKey, nil
		}
		return bestSplitKey, nil
	}
}
```

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42672)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/pebble_iterator.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuEzEWxDDGGV6gHH9X0:-LuIQ3ui-zgPQj1PYC8x:btu6t79) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L312)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

every time I've looked at this code I've disliked the duplication and sub-optimality of the above `noSplitSpans` loop and `isValidSplitKey` (sub optimal because it only removes `noSplitSpans` that are preceding `minSplitKey`) -- the duplication bothers me more.
</blockquote></details>

My statement was not very reasonable -- feel free to ignore.
___
*[pkg/storage/engine/pebble_iterator.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuF07QT9hrvQi2kdIxL:-LuIQHVZ2cWlg2QGe7Gs:b6ttux9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L350)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this can be set to nil even if only part of the if-condition is satisfied.
</blockquote></details>

My comment was unclear -- I meant to say that an alternative formulation could set it to nil as soon as `mvccKey` is past `mvccMinSplitKey`.
___
*[pkg/storage/engine/pebble_iterator.go, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuIR4_GBKGRHrq035GZ:-LuIR4_GBKGRHrq035G_:bh57njp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L384)):*
> ```Go
> 		}
> 	}
> 	return bestSplitKey, nil
> ```

How about a comment here that states both the cases that are possible here and why returning `bestSplitKey` in both is correct?

**Review by itsbilal — COMMENTED** [review]
Thanks for the review! I've addressed your comments. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-:-LuJfjFK9LGGAJSudcB6:b-ttge27)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_iterator.go, line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuEoHjQAwliWQHVQStH:-LuJg0xH8xX6zfEZSLMO:b-r9gzfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L336)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This idea looks good, but I wonder if it can be written in a way that is simpler to understand. 
</blockquote></details>

Realized that this part is practically redundant with the if statement at the end, so I replaced it with just a `break`.
___
*[pkg/storage/engine/pebble_iterator.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuF07QT9hrvQi2kdIxL:-LuJg-m96HtyU21-90BZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L350)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

My comment was unclear -- I meant to say that an alternative formulation could set it to nil as soon as `mvccKey` is past `mvccMinSplitKey`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/pebble_iterator.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuEzlWM6h0lFmxPXtSo:-LuJX1x25TSHqZHR8y21:b6ph8u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L380)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think these checks are needed.
I tweaked the code here to make it more easy for me to understand, though ymmv.

```
func isValidSplitKey(key roachpb.Key, noSplitSpans []roachpb.Span) ([]roachpb.Span, bool) {
	var prefixToRemove int
	rv := true
	for i := range noSplitSpans {
		if key.Compare(noSplitSpans[i].EndKey) >= 0 {
			prefixToRemove = i
		}
		// We know key < EndKey. Is key >= StartKey
		if key.Compare(noSplitSpans[i].Key) >= 0 {
			rv = false
			break
		}
	}
	return noSplitSpans[prefixToRemove+1:], rv
}

// FindSplitKey implements the Iterator interface.
func (p *pebbleIterator) FindSplitKey(
	start, end, minSplitKey roachpb.Key, targetSize int64,
) (MVCCKey, error) {
	const timestampLen = 12

	sizeSoFar := int64(0)
	bestDiff := int64(math.MaxInt64)
	// found indicates that we have found a valid split key that is the best known so far.
	// an empty bestSplitKey => that split key is in prevKey, else it is in bestSplitKey.
	found := false
	prevKey := MVCCKey{}
	bestSplitKey := MVCCKey{}

	// Remove the no-split spans that precede the minimum split key.
	noSplitSpans := keys.NoSplitSpans
	noSplitSpans, _ = isValidSplitKey(minSplitKey, noSplitSpans)

	// Note that it is unnecessary to compare against "end" to decide to
	// terminate iteration because the iterator's upper bound has already been
	// set to end.
	mvccMinSplitKey := MakeMVCCMetadataKey(minSplitKey)
	p.SeekGE(MakeMVCCMetadataKey(start))
	for ; p.iter.Valid(); p.iter.Next() {
		mvccKey, err := DecodeMVCCKey(p.iter.Key())
		if err != nil {
			return MVCCKey{}, err
		}
		diff := targetSize - sizeSoFar
		if diff < 0 {
			diff = -diff
		}
		if diff > bestDiff {
			// We must have had a valid candidate in the past since we can't be worse than MaxInt64.
			if len(bestSplitKey.Key) == 0 {
				return prevKey, nil
			}
			return bestSplitKey, nil
		}
		// diff <= bestDiff.
		if mvccMinSplitKey.Key == nil || !mvccKey.Less(mvccMinSplitKey) {
			// Candidate since it is past the minimum split key.
			// Avoid comparing against minSplitKey on future iterations.
			mvccMinSplitKey.Key = nil
			valid := true
			if len(noSplitSpans) > 0 {
				noSplitSpans, valid = isValidSplitKey(mvccKey.Key, noSplitSpans)
			}
			if valid {
				// Valid candidate.
				bestDiff = diff
				found = true
				// Clear bestSplitKey since we will save the valid candidate in prevKey below.
				bestSplitKey.Key = bestSplitKey.Key[:0]

			} else {
				// Not valid. If the prevKey was a valid candidate, it must have cleared bestSplitKey,
				// in which case save it as the valid candidate.
				if found && len(bestSplitKey.Key) == 0 {
					bestSplitKey.Timestamp = prevKey.Timestamp
					bestSplitKey.Key = append(bestSplitKey.Key[:0], prevKey.Key...)
				}
			}
		}
		sizeSoFar += int64(len(p.iter.Value()))
		if mvccKey.IsValue() && bytes.Equal(prevKey.Key, mvccKey.Key) {
			// We only advanced timestamps, but not new mvcc keys.
			sizeSoFar += timestampLen
		} else {
			sizeSoFar += int64(len(mvccKey.Key) + 1)
			if mvccKey.IsValue() {
				sizeSoFar += timestampLen
			}
		}
		prevKey.Key = append(prevKey.Key[:0], mvccKey.Key...)
		prevKey.Timestamp = mvccKey.Timestamp
	}

	if found {
		if len(bestSplitKey.Key) == 0 {
			return prevKey, nil
		}
		return bestSplitKey, nil
	}
}
```
</blockquote></details>

Good point, these checks are unnecessary now that I thought about it again - the `found && len(bestSplitKey) == 0` condition is true only when `prevKey` has already passed those checks earlier.

I've incorporate most of your comments as well as the `nil` minSplitKey optimization,  thanks for writing them up! I didn't quite copy your code completely since I prefer the flatter if statements the branch currently has, but I'm happy to hear your thoughts.
___
*[pkg/storage/engine/pebble_iterator.go, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuIR4_GBKGRHrq035GZ:-LuJfzrn03qGBd9wbzeq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a9c08f2d07978d424f858bfe78b2ea68aa86b3/pkg/storage/engine/pebble_iterator.go#L384)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about a comment here that states both the cases that are possible here and why returning `bestSplitKey` in both is correct?
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-:-LuYgsXu7GHra3H82kOU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_iterator.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuYUoEt1e_25OUImNyD:-LuYUoEt1e_25OUImNyE:b-nyimy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e407a20aaf8a8e789e33776c605956ad702bfb/pkg/storage/engine/pebble_iterator.go#L347)):*
> ```Go
> 			(len(noSplitSpans) == 0 || isValidSplitKey(mvccKey.Key, noSplitSpans)) {
> 			// This is a valid candidate for a split key.
> 			if diff < bestDiff {
> ```

Don't we already know we are in the `diff <= bestDiff` case here because of the earlier `if diff > bestDiff { break }` if-block? Is the equality case something we care to handle in a way to prefer the earlier candidate or just make this the new best? I am guessing equality is rare enough that we don't care.
___
*[pkg/storage/engine/pebble_iterator.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuYVvH02Z7jVJgK7GNY:-LuYVvH02Z7jVJgK7GNZ:b9cgnoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e407a20aaf8a8e789e33776c605956ad702bfb/pkg/storage/engine/pebble_iterator.go#L363)):*
> ```Go
> 			// a key that cannot be a split key (i.e. is in noSplitSpans). Instead
> 			// of tracking how many times we need to do Prev(), just copy the previous
> 			// key as the bestSplitKey for now.
> ```

nit: the "Instead ..." sentence is confusing for someone who doesn't have a history with previous code reviews. Perhaps omit it? Also, given that we need `prevKey` to deal with the `sizeSoFar` tracking, I think the current version is optimal -- we never need to do the `Prev()` thing. Is that consistent with your thinking?

**Review by itsbilal — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-:-LuZ8P2k8R0cUunN79xf:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_iterator.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuYUoEt1e_25OUImNyD:-LuZ5HZc1f6QXXsqX2UL:b-fhk71m) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e407a20aaf8a8e789e33776c605956ad702bfb/pkg/storage/engine/pebble_iterator.go#L347)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Don't we already know we are in the `diff <= bestDiff` case here because of the earlier `if diff > bestDiff { break }` if-block? Is the equality case something we care to handle in a way to prefer the earlier candidate or just make this the new best? I am guessing equality is rare enough that we don't care.
</blockquote></details>

Yeah, we're only going to see decreasing `diff`s here, so you're right. Equality should be rare enough that we don't care which `bestSplitKey` we pick. I guess the point of this if statement is readability more than anything else. I can remove it if you feel strongly.
___
*[pkg/storage/engine/pebble_iterator.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuYVvH02Z7jVJgK7GNY:-LuZ7N5YESVzs61qUvcl:bsqqygj) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e407a20aaf8a8e789e33776c605956ad702bfb/pkg/storage/engine/pebble_iterator.go#L363)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: the "Instead ..." sentence is confusing for someone who doesn't have a history with previous code reviews. Perhaps omit it? Also, given that we need `prevKey` to deal with the `sizeSoFar` tracking, I think the current version is optimal -- we never need to do the `Prev()` thing. Is that consistent with your thinking?
</blockquote></details>

I wrote that comment while I had a hypothetical solution in my mind where we avoid the double copy by iterating backward and by keeping track of how many times to iterate backward. But that makes less sense the further away from `bestSplitKey` we go. Either way, I've removed the Instead part, it probably confuses the reader more than anything else.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-:-LuZBs09CW0pOipamweP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_iterator.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42672#-LuYUoEt1e_25OUImNyD:-LuZBjeJAIx43MDCda-q:b5auj0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e407a20aaf8a8e789e33776c605956ad702bfb/pkg/storage/engine/pebble_iterator.go#L347)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah, we're only going to see decreasing `diff`s here, so you're right. Equality should be rare enough that we don't care which `bestSplitKey` we pick. I guess the point of this if statement is readability more than anything else. I can remove it if you feel strongly.
</blockquote></details>

What you have is fine.

**Comment by itsbilal** [comment]
Thanks for the review!

bors r+

**Pull request merged**
