### PR TITLE
multiregionccl,server: use cached sqlliveness.Reader, deflake ColdStartLatencyTest

### LINKED ISSUE #96334: multiregionccl: flake in TestColdStartLatency due to timeout during user login
This is different from previous flakes and refers to the user account retrieval during session authentication.

Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/8537864?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
          Error:        Received unexpected error:
                        failed to connect to `host=127.0.0.1 user=foo database=defaultdb`: server error (ERROR: internal error while retrieving user account memberships: operation "get-user-timeout" timed out after 10.002s (given timeout 10s): internal error while retrieving user account: aborted during DistSender.Send: context deadline exceeded (SQLSTATE 28000))
```

cc @rafiss for triage

Jira issue: CRDB-24073

### PR DESCRIPTION
**Pull request by ajwerner**
#### multitenantccl: deflake ColdStartLatencyTest
This test was flakey due to the closed timestamp sometimes not leading far
for global tables due to overload, and due to a cached liveness reader
not being used in distsql. The former was fixed in previous commits. The
latter is fixed here.

Fixes: https://github.com/cockroachdb/cockroach/issues/96334

#### sql: use CachedReader for uses with sqlinstance and the sql builtins
The CachedReader won't block, which in multi-region clusters is good. It will
mean that in some cases, it'll state that a sessions is alive when it most
certainly is not. Currently, nobody needs synchronous semantics.

This is a major part of fixing the TestColdStartLatency as sometimes
distsql planning would block. That's not acceptable -- the idea that
query physical planning can need to wait for a cross-region RPC is
unacceptable.

#### sqlliveness: re-arrange APIs to clarify when the API was blocking

By "default" the implementation of Reader was blocking and there was a method
to get a handle to a non-blocking CachedReader(). This asymmetry does not aid
understandability. The non-blocking reader came later, but it is generally the
more desirable interface.

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98368#-:-NQCj_hbCgS4sNLfS9Nq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @JeffSwenson)

___
*[`pkg/sql/planner.go` line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98368#-NQCjNjnAk4M4rr3tWNN:-NQCjNjnAk4M4rr3tWNO:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/299babf6f151a33f83deecf1722c3a66766bff17/pkg/sql/planner.go#L117)):*
> ```Go
> 	evalCtx.Codec = execCfg.Codec
> 	evalCtx.Tracer = execCfg.AmbientCtx.Tracer
> 	if execCfg.SQLLiveness != nil { // nil in some tests
> ```

Why did this change?

**Review by fqazi — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98368)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @JeffSwenson)

**Comment by ajwerner** [comment]
Latest commit is https://github.com/cockroachdb/cockroach/pull/98551

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98368#-:-NQVM8UN3LKQPHIv5lUZ:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @fqazi, and @JeffSwenson)

___
*[`pkg/sql/planner.go` line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98368#-NQCjNjnAk4M4rr3tWNN:-NQVLz_82NTZ-Gi9EAme:b-1g7g4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/299babf6f151a33f83deecf1722c3a66766bff17/pkg/sql/planner.go#L117)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

Because now we're calling a method on the object. In those tests, nothing used the nil value. The evalCtx and its rules about what needs a concrete implementation are a disaster.

**Pull request merged**
