### PR TITLE
exprgen: support for fake relational op

### LINKED ISSUE #30273: design and implement infrastructure for testing logical props and especially stats
Currently, the only way to "unit" test logical props and statistics is to come up with an expression that exercises whatever is being tested and figure out a SQL query for which the optimal plan is the desired expression. Both of these steps are non-trivial, and they are also fragile: a change in costing or statistics can easily invalidate existing tests.

We need to come up with a better framework; one in which we can build an single operator and specify logical props and stats for its children. Ideally it would be something that supports `-rewrite`.

CC @rytaft @andy-kimball

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #30273.
Closes #32103.

#### exprgen: add FakeRelOp

This commit adds a "fake" relational operator which contains all the
logical properties in its private, along with partial exprgen support.

This operator is intended to use as a child when testing the
derivation of logical props of a target operator.

Release note: None

#### optgen: support multi-line strings

Add support for multi-line strings using backquote. Will be useful for
exprgen, to include json statistics.

Release note: None

#### exprgen: json stats for fake ops

Support specifying FakeRel stats using the same JSON format we use for
`INJECT STATS`.

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
Exciting to see this!

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-:-LcXNy_H02QRz7Z5-bvs:bqvic1x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/ops/relational.opt, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXKAzr9HAhFidgdqRr:-LcXKAzr9HAhFidgdqRs:b-uo6z9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75d988ce40a965ba59cb4b2466517b547cc1afc/pkg/sql/opt/ops/relational.opt#L846)):*
> ```
> [Private]
> define FakeRelPrivate {
>     Props RelPropsPtr
> ```

Out of curiosity, what's the benefit of making this a pointer?
___
*[pkg/sql/opt/optgen/exprgen/private.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXL6Qb4wpYrQ-ryQEc:-LcXL6Qb4wpYrQ-ryQEd:b-6u0cqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75d988ce40a965ba59cb4b2466517b547cc1afc/pkg/sql/opt/optgen/exprgen/private.go#L162)):*
> ```Go
> 	pieces := strings.SplitN(str, "-", 2)
> 	if len(pieces) != 2 {
> 		panic(errorf("cardinality must be of the form \"[<min>] - [<max>]\": %s", str))
> ```

[nit] `[<min>] - [<max>]` -> `<min> - <max>`
___
*[pkg/sql/opt/optgen/exprgen/private.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXN3oaDaclJOkwYlBJ:-LcXN3oaDaclJOkwYlBK:b-d20ff6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2d41f27a15f2c03efcfc20fad76afe9394fba1/pkg/sql/opt/optgen/exprgen/private.go#L212)):*
> ```Go
> 		if !added {
> 			// The same set was already in a more recent statistic, ignore.
> 			continue
> ```

do you have any tests with multiple stats on the same column?
___
*[pkg/sql/opt/optgen/exprgen/testdata/fake, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXNDTpADkoEiOPZOWE:-LcXNDTpADkoEiOPZOWF:biedp2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2d41f27a15f2c03efcfc20fad76afe9394fba1/pkg/sql/opt/optgen/exprgen/testdata/fake#L50)):*
> ```
>  ├── columns: a:1(int!null) b:2(int!null) c:3(int)
>  ├── cardinality: [5 - 1000]
>  ├── stats: [rows=0]
> ```

why are the stats empty?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXKAzr9HAhFidgdqRr:-LcXe78cB189pcVDifGj:b4vx5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75d988ce40a965ba59cb4b2466517b547cc1afc/pkg/sql/opt/ops/relational.opt#L846)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Out of curiosity, what's the benefit of making this a pointer?
</blockquote></details>

Just so it can be interned as a pointer (otherwise I'd have to define interning for all its fields).
___
*[pkg/sql/opt/optgen/exprgen/private.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXL6Qb4wpYrQ-ryQEc:-LcXeCBJ7vVqCD2-q3vW:b-5fco24) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75d988ce40a965ba59cb4b2466517b547cc1afc/pkg/sql/opt/optgen/exprgen/private.go#L162)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] `[<min>] - [<max>]` -> `<min> - <max>`
</blockquote></details>

`[..]` means optional; `-`, `1-`, `-10` are all valid.
___
*[pkg/sql/opt/optgen/exprgen/private.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXN3oaDaclJOkwYlBJ:-LcXfbTP1IRDCwEnC9Np:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2d41f27a15f2c03efcfc20fad76afe9394fba1/pkg/sql/opt/optgen/exprgen/private.go#L212)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

do you have any tests with multiple stats on the same column?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/exprgen/testdata/fake, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXNDTpADkoEiOPZOWE:-LcXeZriBPSl8Y-cd7lN:bxnq0o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2d41f27a15f2c03efcfc20fad76afe9394fba1/pkg/sql/opt/optgen/exprgen/testdata/fake#L50)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why are the stats empty?
</blockquote></details>

Forgot to update the file, fixed.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-:-LcXiIrz9MIHnm9kJMr-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/sql/opt/ops/relational.opt, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXKAzr9HAhFidgdqRr:-LcXhoWJDbNrvthHcGAP:b5vjmdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75d988ce40a965ba59cb4b2466517b547cc1afc/pkg/sql/opt/ops/relational.opt#L846)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Just so it can be interned as a pointer (otherwise I'd have to define interning for all its fields).
</blockquote></details>

Got it - thanks!
___
*[pkg/sql/opt/optgen/exprgen/private.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXL6Qb4wpYrQ-ryQEc:-LcXhrzQ3kDuDvP65jzK:b-o9lrx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75d988ce40a965ba59cb4b2466517b547cc1afc/pkg/sql/opt/optgen/exprgen/private.go#L162)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`[..]` means optional; `-`, `1-`, `-10` are all valid.
</blockquote></details>

Ah ok makes sense

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36849)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/optgen/exprgen/private.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36849#-LcXj3Zc1RnaD11IhaY6:-LcXj3Zc1RnaD11IhaY7:blxl904) ([raw file](https://github.com/cockroachdb/cockroach/blob/359de6aa87e6bfa439b63706e7fa226857b0cd66/pkg/sql/opt/optgen/exprgen/private.go#L102)):*
> ```Go
> 
> 		case reflect.TypeOf(props.Statistics{}):
> 			return eg.statsFromStr(str)
> ```

Do you want to add support for FDs and outer columns too?

**Comment by RaduBerinde** [comment]
linter OOM

bors r+

**Pull request merged**
