### PR TITLE
sql,sqlbase,client: bootstrap TableDescriptor timestamps from MVCC

### PR DESCRIPTION
**Pull request by ajwerner**
This PR adds back the changes in #40581 and deals with the fallout that led to #40781 in the 3rd commit.

Release Justification: Fixes a bug formerly considered to be a release blocker.

### CODE REVIEW

**Comment by ajwerner** [comment]
There was some churn here because of a discovery: before 19.1 we did not set the `ModificationTime` on Version 1 of table descriptors and the `CreateAsOfTime` did not exist.

The logic in `TableDescriptor.maybeSetTimeFromMVCCTimestamp()` has been updated to reflect my now better understanding of `CreateAsOfTime` and the logic in restore has been made robust to missing values with a perhaps crude but effective fix in the last commit that now includes testing.

I'm hopeful we can agree to still put in this change as it's a real customer pain point and I understand that this revealed some added risk.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40793)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @lucy-zhang)

___
*[pkg/ccl/backupccl/restore.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowMQcuBLR67ZbiN_L-:-LowMQcuBLR67ZbiN_L0:bltmr7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/ccl/backupccl/restore.go#L48)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	"github.com/cockroachdb/errors"
> 	opentracing "github.com/opentracing/opentracing-go"
> ```

This got added again.
___
*[pkg/ccl/backupccl/restore.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowFr0A3GjlqJrAj9tO:-LowFr0A3GjlqJrAj9tP:b-sofz21) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/ccl/backupccl/restore.go#L78)):*
> ```Go
> 			return nil, errors.Wrapf(err, "failed to read backup descriptor")
> 		}
> 		for _, d := range desc.Descriptors {
> ```

I think all this should actually go in `readBackupDescriptor()`, which is ultimately what gets called whenever we read a backup descriptor (which happens in a few other places besides this one).
___
*[pkg/ccl/backupccl/restore.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowBysZ3trX4w1P8IZF:-LowBys_6iiUEPeoUKwm:b-egnxvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/ccl/backupccl/restore.go#L91)):*
> ```Go
> 			if t := d.GetTable(); t == nil {
> 				continue
> 			} else if t.Version == 1 && t.ModificationTime.IsEmpty() {
> ```

I had thought that we would never make a >=19.1 backup of a table descriptor without a `ModificationTime`. Even in 19.2, a table descriptor must be read before it is written to the backup descriptor, at which point a timestamp would have been set if it hadn't been set already, right?

(Also, is it possible to just indiscriminately set the `ModificationTime` to `1` whenever we restored a table? Is there any advantage to keeping the old timestamp?)
___
*[pkg/sql/sqlbase/structured.go, line 3305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowJ4qv1jDPDdXmc_T4:-LowJ4qw9BO0MqxZHUeR:b-f8ojh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/sql/sqlbase/structured.go#L3305)):*
> ```Go
> func (desc *TableDescriptor) maybeSetTimeFromMVCCTimestamp(ts hlc.Timestamp) {
> 	// CreateAsOfTime is used for CREATE TABLE ... AS SELECT ... and was
> 	// introduced in v19.1. In general it is not critical to set and we definitely
> ```

Sorry I forgot about the `CREATE TABLE AS` complications in my earlier review. I think this comment could be clearer about `CreateAsOfTime` being set if and only if the table was created from `CREATE TABLE AS`. (Though in practice I think it's harmless if the timestamp isn't set as long as the table isn't in the `ADD` state anymore. We only use it as a transaction timestamp when filling in the table.)

Along those same lines, maybe there should be an assertion that if `table.Adding() && table.IsAs()`, we either have the timestamp already set or have a value to set it to.
___
*[pkg/sql/sqlbase/structured.proto, line 826 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowLV8n4BzEC7NwuQmi:-LowLV8n4BzEC7NwuQmj:bly8gm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/sql/sqlbase/structured.proto#L826)):*
> ```protobuf
>   // version of a table and is populated from the MVCC timestamp of the read
>   // like ModificationTime. See Descriptor.Table().
>   // CreateAsOfSystemTime is used for CREATE TABLE ... AS SELECT ... and was
> ```

nit: `CREATE TABLE ... AS ...`

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40793)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @lucy-zhang)

___
*[pkg/ccl/backupccl/restore.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowMQcuBLR67ZbiN_L-:-LozSNPy9-uHmADjnc8k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/ccl/backupccl/restore.go#L48)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This got added again.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowFr0A3GjlqJrAj9tO:-LozQp5O5vTGzvPsuWyk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/ccl/backupccl/restore.go#L78)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I think all this should actually go in `readBackupDescriptor()`, which is ultimately what gets called whenever we read a backup descriptor (which happens in a few other places besides this one).
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowBysZ3trX4w1P8IZF:-Lowhmc919Yg_h6bFXAd:b-l2wk34) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/ccl/backupccl/restore.go#L91)):*
>I had thought that we would never make a >=19.1 backup of a table descriptor without a `ModificationTime`. 

True but we need to support restoring from backups made from any version. 

> (Also, is it possible to just indiscriminately set the ModificationTime to 1 whenever we restored a table? Is there any advantage to keeping the old timestamp?)

Seems like it should be. The main value of the old timestamp as far as I can tell is that it will correspond to the MVCC time range of keys which contain that physical format. It's totally possible that I misunderstand how restoring a table interacts with MVCC but my expectation is that the restored keys will carry the same timestamp as when they were exported. If that's false then I feel way less strongly about preserving the ModificationTime. 
___
*[pkg/sql/sqlbase/structured.go, line 3305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowJ4qv1jDPDdXmc_T4:-LozSFDHCb9bKwb6uJlI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/sql/sqlbase/structured.go#L3305)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Sorry I forgot about the `CREATE TABLE AS` complications in my earlier review. I think this comment could be clearer about `CreateAsOfTime` being set if and only if the table was created from `CREATE TABLE AS`. (Though in practice I think it's harmless if the timestamp isn't set as long as the table isn't in the `ADD` state anymore. We only use it as a transaction timestamp when filling in the table.)

Along those same lines, maybe there should be an assertion that if `table.Adding() && table.IsAs()`, we either have the timestamp already set or have a value to set it to.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 826 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowLV8n4BzEC7NwuQmi:-LozSM6w6d18Ml9u7wMC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/sql/sqlbase/structured.proto#L826)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: `CREATE TABLE ... AS ...`
</blockquote></details>

Done.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-:-LozaOUW5f4YuD1zZZxQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @lucy-zhang)

___
*[pkg/ccl/backupccl/restore.go, line 80 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Loz_VbJBVdCL6LZIQTl:-Loz_VbK2Mtt_YXTc3Pr:bz02vpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/ccl/backupccl/restore.go#L80)):*
> ```Go
> 		backupDescs[i] = desc
> 	}
> ```

nit: spurious diff
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 38 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Loz_oAtBNccAg9JwwGi:-Loz_oAtBNccAg9JwwGj:b-cod31x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/ccl/backupccl/restore_old_versions_test.go#L38)):*
> ```Go
> 	for _, dir := range dirs {
> 		require.True(t, dir.IsDir())
> 		t.Run(dir.Name(), restoreOldVersionTest(dir.Name()))
> ```

nit: pass `path.join(exportDirs, dir)` and localize `exportDirs` and `testdataBase` to this function.
___
*[pkg/ccl/backupccl/testdata/restore_old_versions/create.sql, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LozaB3sAVvJDySZJFBk:-LozaB3sAVvJDySZJFBl:bi3rmj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/ccl/backupccl/testdata/restore_old_versions/create.sql#L1)):*
> ```TSQL
> -- The below SQL is used to create the data that is then exported with BACKUP
> ```

I'm really happy that you wrote these tests, but can you please also paste in here somewhere the exact commands to produce the ssts?
___
*[pkg/sql/sqlbase/structured.go, line 3318 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Loza8CjCGf8ikxgRG8W:-Loza8CjCGf8ikxgRG8X:b-hjepry) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/sql/sqlbase/structured.go#L3318)):*
> ```Go
> 		desc.CreateAsOfTime = ts
> 	}
> ```

spurious diff

**Review by ajwerner — COMMENTED** [review]
TFTR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-:-LozetMd78d1ueUbUFPR:bz5m8k4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @lucy-zhang)

___
*[pkg/ccl/backupccl/restore.go, line 80 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Loz_VbJBVdCL6LZIQTl:-LozceZo7ophegngdifU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/ccl/backupccl/restore.go#L80)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: spurious diff
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 38 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Loz_oAtBNccAg9JwwGi:-LozeYsf-lHmdI_eN_1b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/ccl/backupccl/restore_old_versions_test.go#L38)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: pass `path.join(exportDirs, dir)` and localize `exportDirs` and `testdataBase` to this function.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/testdata/restore_old_versions/create.sql, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LozaB3sAVvJDySZJFBk:-LozeZvR1wncy0Lr0qA8:b-rgw2hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/ccl/backupccl/testdata/restore_old_versions/create.sql#L1)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm really happy that you wrote these tests, but can you please also paste in here somewhere the exact commands to produce the ssts?
</blockquote></details>

Added it to the test comment.
___
*[pkg/sql/sqlbase/structured.go, line 3318 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Loza8CjCGf8ikxgRG8W:-Lozejty7c2-ps-ifJwp:brwcdia) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df3d2f69c11a973f9459f7bf6c66ee2e4d41530/pkg/sql/sqlbase/structured.go#L3318)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

spurious diff
</blockquote></details>

I think I like this one.

**Comment by ajwerner** [comment]
@lucy-zhang can I have your stamp on this before I bors it?

**Review by thoszhang — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40793)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @lucy-zhang)

___
*[pkg/ccl/backupccl/restore.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-LowBysZ3trX4w1P8IZF:-Lp-nB_t2AM7JyBphUiB:b-4m2avh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7bdba9b7c0764a074c3fda0090c4bb9c28017e7/pkg/ccl/backupccl/restore.go#L91)):*
> True but we need to support restoring from backups made from any version.

Yeah, agreed, I actually just misread the comment/code previously.
___
*[pkg/sql/sqlbase/structured.go, line 3323 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Lp-vuSf8Xqh5tjIgnH_:-Lp-vuSf8Xqh5tjIgnHa:b-csnte5) ([raw file](https://github.com/cockroachdb/cockroach/blob/622a0819c08bada47d97afd0bfd998e8e1d6e878/pkg/sql/sqlbase/structured.go#L3323)):*
> ```Go
> 	if desc.Adding() && desc.IsAs() && desc.CreateAsOfTime.IsEmpty() {
> 		log.Fatalf(context.TODO(), "table descriptor for %q (%d.%d) is in the "+
> 			"ADD state and was creates with CREATE TABLE ... AS but does not have a "+
> ```

`created`

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-:-Lp-xNah9A0tKn5tbJKi:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.go, line 3323 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40793#-Lp-vuSf8Xqh5tjIgnH_:-Lp-xKQk1hpu60APMppn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/622a0819c08bada47d97afd0bfd998e8e1d6e878/pkg/sql/sqlbase/structured.go#L3323)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

`created`
</blockquote></details>

Done.

**Pull request merged**
