### PR TITLE
roachtest: fix tpchvec perf

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes a problem with "test case struct" resolution that was
introduced recently when we added `smithcmp` config to `tpchvec` test.
The root of the issue is that `testRun` function was made a part of the
`tpchVecTestCase` interface which doesn't really makes sense.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
See https://github.com/cockroachdb/cockroach/issues/47401#issuecomment-620472021

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48107#-M60BYcK9FQh2cAiBFlj:-M60BYcK9FQh2cAiBFlk:banoym4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01625e40558805df9fd6f25e21758e24aea2375/pkg/cmd/roachtest/tpchvec.go#L140)):*
> ```Go
> 	c *cluster,
> 	version crdbVersion,
> 	vectorizeOptions []bool,
> ```

I think this solution is confusing because we have the option to either use the passed in variable or call b.vectorizeOptions and the other `testRun` implementation ignores the arguments. The problem here is that there are no commonalities between the test types so putting this into an interface doesn't work cleanly. Instead, I think we should get rid of `testRun` and pass in a function to `runTPCHVec` one of which is the original and the other which is the new placeholder test.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48107#-M60BYcK9FQh2cAiBFlj:-M60Ql8m6j2wYaDGB_bX:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01625e40558805df9fd6f25e21758e24aea2375/pkg/cmd/roachtest/tpchvec.go#L140)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this solution is confusing because we have the option to either use the passed in variable or call b.vectorizeOptions and the other `testRun` implementation ignores the arguments. The problem here is that there are no commonalities between the test types so putting this into an interface doesn't work cleanly. Instead, I think we should get rid of `testRun` and pass in a function to `runTPCHVec` one of which is the original and the other which is the new placeholder test.
</blockquote></details>

Good point, done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48107#-:-M60fHjS1v_WCnQXoO2y:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
