### PR TITLE
ui: add time delta to lease timing in range report

### PR DESCRIPTION
**Pull request by andreimatei**
This patch changes the Lease Start and Lease Expiration in the range
report to also report the delta from now.
Looks like:
```
Lease Start:     2021-03-23 21:27:53
                 (2s 884ms ago)
LeaseExpiration: 2021-03-23 21:28:02
                 (6s 121ms in the future)
```

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:dog:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62495#-:-MWZsf0_Cnnamu1yYA9A:b-8evdil)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — APPROVED** [review]
:lgtm: just a few nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62495#-:-MWySGoKEZxoei_p4fq5:b-q4tpaw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/ui/src/views/reports/containers/range/print.ts, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62495#-MWyQtQW5NKbl3LL5Q8v:-MWyQtQW5NKbl3LL5Q8w:bcjrvqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d7adec1f17f5a5b0a88a6f8fde4ce1c896cb77/pkg/ui/src/views/reports/containers/range/print.ts#L109)):*
> ```XML
> ): string {
>   const time: moment.Moment = LongToMoment(timestamp.wall_time);
>   if (time == null) {
> ```

nit: If `timestamp.wall_time` is null, `LongToMoment` will return current time. Is this check necessary?
___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62495#-MWyRwLFEfzHBQiTOLtY:-MWyRwLFEfzHBQiTOLtZ:b2qzvxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d7adec1f17f5a5b0a88a6f8fde4ce1c896cb77/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L365)):*
> ```XML
>       };
>     }
>     if (FixLong(timestamp.wall_time) == FixLong(0)) {
> ```

nit: I always like to use `===` in JS/TS but in this particular case you're probably guaranteed that types are the same on the left/right hand sides.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62495)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ui/src/views/reports/containers/range/print.ts, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62495#-MWyQtQW5NKbl3LL5Q8v:-MXJsaml1IVuYnS5Qg3Y:b-gi90u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d7adec1f17f5a5b0a88a6f8fde4ce1c896cb77/pkg/ui/src/views/reports/containers/range/print.ts#L109)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: If `timestamp.wall_time` is null, `LongToMoment` will return current time. Is this check necessary?
</blockquote></details>

oh, hmm, that's not what I want actually. See now.
___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62495#-MWyRwLFEfzHBQiTOLtY:-MXJsnlxBpLY--T2Gt55:bnfwysw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d7adec1f17f5a5b0a88a6f8fde4ce1c896cb77/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L365)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: I always like to use `===` in JS/TS but in this particular case you're probably guaranteed that types are the same on the left/right hand sides.
</blockquote></details>

done

What's the deal with `==` vs `===`, btw?

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62495#-:-MYk5fLv6nvbJ4MYiVNw:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @tbg)

**Pull request merged**
