### PR TITLE
kvserver: deflake TestRebalancingAndCrossRegionZoneSnapshotMetrics

### LINKED ISSUE #137249: kv/kvserver: TestRebalancingAndCrossRegionZoneSnapshotMetrics failed
kv/kvserver.TestRebalancingAndCrossRegionZoneSnapshotMetrics [failed](https://tanzanite.cluster.engflow.com/invocations/default/29be128b-bbb2-4b8c-89de-c0a0168fe550?testReportRun=3&testReportShard=7&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [d18eb683b2759fd8814dacf0baa913f596074a17](https://github.com/cockroachdb/cockroach/commits/d18eb683b2759fd8814dacf0baa913f596074a17):

```
        	            	expected: map[string]kvserver_test.snapshotBytesMetrics{"":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:567}, ".cross-region":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:567}, ".cross-zone":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:0}, ".rebalancing":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:567}, ".recovery":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:0}}
        	            	actual  : map[string]kvserver_test.snapshotBytesMetrics{"":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:559}, ".cross-region":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:559}, ".cross-zone":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:0}, ".rebalancing":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:559}, ".recovery":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:0}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -3,3 +3,3 @@
        	            	   sentBytes: (int64) 0,
        	            	-  rcvdBytes: (int64) 567
        	            	+  rcvdBytes: (int64) 559
        	            	  },
        	            	@@ -7,3 +7,3 @@
        	            	   sentBytes: (int64) 0,
        	            	-  rcvdBytes: (int64) 567
        	            	+  rcvdBytes: (int64) 559
        	            	  },
        	            	@@ -15,3 +15,3 @@
        	            	   sentBytes: (int64) 0,
        	            	-  rcvdBytes: (int64) 567
        	            	+  rcvdBytes: (int64) 559
        	            	  },
        	Test:       	TestRebalancingAndCrossRegionZoneSnapshotMetrics/first_receiver
    --- FAIL: TestRebalancingAndCrossRegionZoneSnapshotMetrics/first_receiver (0.00s)
=== RUN   TestRebalancingAndCrossRegionZoneSnapshotMetrics/sender
    replica_learner_test.go:2371: 
        	Error Trace:	pkg/kv/kvserver/replica_learner_test.go:2371
        	Error:      	Not equal: 
        	            	expected: map[string]kvserver_test.snapshotBytesMetrics{"":kvserver_test.snapshotBytesMetrics{sentBytes:1356, rcvdBytes:0}, ".cross-region":kvserver_test.snapshotBytesMetrics{sentBytes:567, rcvdBytes:0}, ".cross-zone":kvserver_test.snapshotBytesMetrics{sentBytes:789, rcvdBytes:0}, ".rebalancing":kvserver_test.snapshotBytesMetrics{sentBytes:1356, rcvdBytes:0}, ".recovery":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:0}}
        	            	actual  : map[string]kvserver_test.snapshotBytesMetrics{"":kvserver_test.snapshotBytesMetrics{sentBytes:1348, rcvdBytes:0}, ".cross-region":kvserver_test.snapshotBytesMetrics{sentBytes:559, rcvdBytes:0}, ".cross-zone":kvserver_test.snapshotBytesMetrics{sentBytes:789, rcvdBytes:0}, ".rebalancing":kvserver_test.snapshotBytesMetrics{sentBytes:1348, rcvdBytes:0}, ".recovery":kvserver_test.snapshotBytesMetrics{sentBytes:0, rcvdBytes:0}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,3 +2,3 @@
        	            	  (string) "": (kvserver_test.snapshotBytesMetrics) {
        	            	-  sentBytes: (int64) 1356,
        	            	+  sentBytes: (int64) 1348,
        	            	   rcvdBytes: (int64) 0
        	            	@@ -6,3 +6,3 @@
        	            	  (string) (len=13) ".cross-region": (kvserver_test.snapshotBytesMetrics) {
        	            	-  sentBytes: (int64) 567,
        	            	+  sentBytes: (int64) 559,
        	            	   rcvdBytes: (int64) 0
        	            	@@ -14,3 +14,3 @@
        	            	  (string) (len=12) ".rebalancing": (kvserver_test.snapshotBytesMetrics) {
        	            	-  sentBytes: (int64) 1356,
        	            	+  sentBytes: (int64) 1348,
        	            	   rcvdBytes: (int64) 0
        	Test:       	TestRebalancingAndCrossRegionZoneSnapshotMetrics/sender
    --- FAIL: TestRebalancingAndCrossRegionZoneSnapshotMetrics/sender (0.00s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=7</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRebalancingAndCrossRegionZoneSnapshotMetrics.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45490

### PR DESCRIPTION
**Pull request by miraradeva**
The test ensures the snapshot byte metrics are correct by measuring the size of the snapshot right before it's sent to a learner. It is possible that a lease upgrade races with this calculation, so the expected snapshot size is wrt an expiration lease, while the snapshot size recorded by the metrics is wrt an epoch/leader lease. This may result in a different snapshot sizes (e.g. because epoch/leader leases do not set the DeprecatedStartStasis field).

This commit ensures the test waits for a lease upgrade before measuring the snapshot size.

Fixes: #137249

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137709#-:-OETc5q24GvZ04ToGXt6:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137709#-OETbPzL8w6-u4O76Lng:-OETbPzL8w6-u4O76Lnh:b6ol8u2):*
nit: I don't think this is possible with epoch leases, given there isn't a lease transfer. 

The reason this happens with leader leases is that when the test starts, there's no leader for the scratch range. As a result, the first lease that's proposed is an expiration based lease. A leader is elected and this lease is proposed. Once it's applied, we realize that we should be upgrading it to a leader lease and quickly do so.

If we're running with epoch based leases, we'll propose an epoch lease based to begin with. So this promotion to a different lease type case doesn't apply.
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137709#-OETc-Tc4bNbegnlnGPw:-OETc-Tc4bNbegnlnGPx:bldnpbp):*
Nice find on the difference here!

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137709)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137709#-OETbPzL8w6-u4O76Lng:-OEUNrKz3JUzbeq9_RVm:b-bqp3ps):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: I don't think this is possible with epoch leases, given there isn't a lease transfer. 

The reason this happens with leader leases is that when the test starts, there's no leader for the scratch range. As a result, the first lease that's proposed is an expiration based lease. A leader is elected and this lease is proposed. Once it's applied, we realize that we should be upgrading it to a leader lease and quickly do so.

If we're running with epoch based leases, we'll propose an epoch lease based to begin with. So this promotion to a different lease type case doesn't apply.
</blockquote></details>

Ah that makes a lot more sense. I was confused why this doesn't happen with epoch leases. I updated the comment in the test and the commit message.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137709#-:-OEUnm-F2jnWF6Ywtjiu:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137709#-OETbPzL8w6-u4O76Lng:-OEUnkqQDAFs8UVXNhxO:bdeavht):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Ah that makes a lot more sense. I was confused why this doesn't happen with epoch leases. I updated the comment in the test and the commit message.
</blockquote></details>

:fire:

**Comment by miraradeva** [comment]
TFTR!

The CI extended failure (`TestLogGrowthWhenRefreshingPendingCommands`) is unrelated.

bors r+

**Pull request merged**
