### PR TITLE
workload/ycsb: use separate rand.Source for scanLengthGen

### LINKED ISSUE #41065: roachtest: ycsb/E/nodes=3/cpu=32 failed
SHA: https://github.com/cockroachdb/cockroach/commits/c11a254ed74c59ac3ff083356d9a71b82db2c7d7

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=ycsb/E/nodes=3/cpu=32 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1505083&tab=artifacts#/ycsb/E/nodes=3/cpu=32

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190925-1505083/ycsb/E/nodes=3/cpu=32/run_1
	cluster.go:1762,ycsb.go:36,cluster.go:2118,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1569387937-55-n4cpu32:4 -- ./workload run ycsb --init --insert-count=1000000 --splits=100 --workload=E --concurrency=64 --histograms=perf/stats.json --ramp=1m --duration=10m {pgurl:1-3} returned:
		stderr:
		
		stdout:
		)
			/usr/local/go/src/runtime/proc.go:301 +0xef fp=0xc000a685f8 sp=0xc000a685d8 pc=0x43a39f
		runtime.selectgo(0xc000a68758, 0xc000a68748, 0x2, 0x0, 0x0)
			/usr/local/go/src/runtime/select.go:313 +0xcb8 fp=0xc000a68720 sp=0xc000a685f8 pc=0x449e78
		database/sql.(*Rows).awaitDone(0xc000dbc480, 0x1c049a0, 0xc0009ac700, 0x0, 0x0)
			/usr/local/go/src/database/sql/sql.go:2642 +0xcc fp=0xc000a687b8 sp=0xc000a68720 pc=0x50864c
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000a687c0 sp=0xc000a687b8 pc=0x467a31
		created by database/sql.(*Rows).initContextClose
			/usr/local/go/src/database/sql/sql.go:2630 +0xc1
		bash: line 1: 22453 Aborted                 (core dumped) bash -c "./workload run ycsb --init --insert-count=1000000 --splits=100 --workload=E --concurrency=64 --histograms=perf/stats.json --ramp=1m --duration=10m 'postgres://root@10.128.0.195:26257?sslmode=disable' 'postgres://root@10.128.0.194:26257?sslmode=disable' 'postgres://root@10.128.0.193:26257?sslmode=disable'"
		Error:  exit status 134
		: exit status 1

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #41065.

Two unsynchronized number generators were using the same underlying
rand.Source, which caused a crash in #41065.

Release justification: Testing only.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
This was only a problem with YCSB E, which is the only workload that performs scans and uses the `scanLengthGen`.

**Review by jordanlewis — APPROVED** [review]

**Comment by jordanlewis** [comment]
You need a release justification

**Comment by nvanbenschoten** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/40362.

bors r+

**Pull request merged**
