### PR TITLE
kv: clean up and better document txnInterceptor stack

### PR DESCRIPTION
**Pull request by nvb**
This PR includes a series of cleanup steps surrounding the `TxnCoordSender` and the `txnInterceptor` stack. The primary goal of this was to unify the interceptors where possible and to improve their documentation. The PR also adds some missing unit tests and points out where more should be added.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-:-LYauR5g-nw1k1L7j2zG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYarYxz8LDGrGFEyQoM:-LYarYxz8LDGrGFEyQoN:brucwjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_coord_sender.go#L216)):*
> ```Go
> 	// Note that EndTransaction(commit=false) requests can still be sent (via the
> 	// lockedSender interface) after this is called, and they're expected to be
> 	// forwarded along. The idea for this method is to stop background tasks.
> ```

Isn't this really entrusting the client.Txns to never send an extra EndTxn that would hit this code: https://github.com/cockroachdb/cockroach/blob/787e8165087b01cb2fc885bb18adb51ee5ac0f0b/pkg/kv/txn_coord_sender.go#L598-L600

Maybe that's true, but I thought sql could try to abort if it wasn't sure what had happened before.
___
*[pkg/kv/txn_coord_sender.go, line 469 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYat2UfBT9u54OZnlla:-LYat2UfBT9u54OZnllb:b-jqjub3) ([raw file](https://github.com/cockroachdb/cockroach/blob/17283b6d3770bfbb369b04c71baef2f00a24ba0e/pkg/kv/txn_coord_sender.go#L469)):*
> ```Go
> 			&tcs.interceptorAlloc.txnSeqNumAllocator,
> 			&tcs.interceptorAlloc.txnIntentCollector,
> 			&tcs.interceptorAlloc.txnPipeliner,
> ```

Can you elaborate on the ordering between the pipeliner and the refresher?
___
*[pkg/kv/txn_coord_sender.go, line 491 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatG5F0xQlf6nqjovF:-LYatG5F0xQlf6nqjovG:b-qouvoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/17283b6d3770bfbb369b04c71baef2f00a24ba0e/pkg/kv/txn_coord_sender.go#L491)):*
> ```Go
> 		// them; see #24798.
> 		tcs.interceptorAlloc.arr[2] = &tcs.interceptorAlloc.txnSpanRefresher
> 		tcs.interceptorStack = tcs.interceptorAlloc.arr[:3]
> ```

Explain why the others are absent, for example the metrics recorder.
___
*[pkg/kv/txn_interceptor_seq_num_allocator_test.go, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatWPMDPas3Bzr-6qL:-LYatWPMDPas3Bzr-6qM:bxqvv28) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded30014f06fb8dcbc11989045a5436543afa50/pkg/kv/txn_interceptor_seq_num_allocator_test.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

nit: 2019
___
*[pkg/kv/txn_interceptor_seq_num_allocator_test.go, line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatu8NAa3WVaVVCSb1:-LYatu8NAa3WVaVVCSb2:bktdvb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded30014f06fb8dcbc11989045a5436543afa50/pkg/kv/txn_interceptor_seq_num_allocator_test.go#L112)):*
> ```Go
> // TestSequenceNumberAllocationTxnRequests tests sequence number allocation's
> // interaction with transaction state requests (BeginTxn, HeartbeatTxn, and
> // EndTxn). Only EndTxn requests should be assigned unique sequence numbers.
> ```

This is just a choice for cleanliness, right? Would this matter for anything except perhaps the 1PC detection?
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYaqWk9-NqnoyxHQaDS:-LYaqWk9-NqnoyxHQaDT:bmfu491) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L31)):*
> ```Go
> //    through the interceptor is assigned the current largest sequence number. Each
> //    write request that travels through the interceptor is assigned a sequence
> //    number larger than any previously allocated.
> ```

Might be a good place to mention concurrent use of TxnCoordSenders for the same txn. I think we only do that while reading, and so there's no problem, right?
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYaqb_w1V53UVqOQcw2:-LYaqb_w1V53UVqOQcw3:b-8c4qy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L32)):*
> operations
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYarCX6CQfelioM1B88:-LYarCX6CQfelioM1B89:b-auxh2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L54)):*
> ```Go
> 	// TODO(andrei): let's get rid of this. It should be maintained
> 	// in the SQL level.
> 	// TODO(nvanbenschoten): convince Andrei to address this TODO.
> ```

You're dangerously close to starting a meme.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 44 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatTq54t1K-eFwVU_-:-LYatTq54t1K-eFwVU_0:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded30014f06fb8dcbc11989045a5436543afa50/pkg/kv/txn_interceptor_seq_num_allocator.go#L44)):*
> ```Go
> //    but the result of a write at a larger sequence number is, an error is
> //    returned.
> //
> ```

nit: extra line

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-:-LYboinC5KEuD4YP0G3z:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/txn_coord_sender.go, line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYarYxz8LDGrGFEyQoM:-LYbmoVn7qq_7St6YhxH:b-hiyb3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_coord_sender.go#L216)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't this really entrusting the client.Txns to never send an extra EndTxn that would hit this code: https://github.com/cockroachdb/cockroach/blob/787e8165087b01cb2fc885bb18adb51ee5ac0f0b/pkg/kv/txn_coord_sender.go#L598-L600

Maybe that's true, but I thought sql could try to abort if it wasn't sure what had happened before.
</blockquote></details>

I'm not sure I follow the question. What's wrong with the extra `EndTxn` hitting that code?
___
*[pkg/kv/txn_coord_sender.go, line 209 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbnh8u8v2lsl5WmPBJ:-LYbnh8u8v2lsl5WmPBK:b-x7u3uj) ([raw file](https://github.com/cockroachdb/cockroach/blob/666a72bd9c46f61e949ab6d70754ddbe39f420fe/pkg/kv/txn_coord_sender.go#L209)):*
> ```
> 	The method will always be called exactly once.
> ```

Please clarify when it's called. There's something wrong with "always exactly once".
___
*[pkg/kv/txn_coord_sender.go, line 456 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYboBP4E7eVFLB-X4Ep:-LYboBP4E7eVFLB-X4Eq:bbozkpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/17283b6d3770bfbb369b04c71baef2f00a24ba0e/pkg/kv/txn_coord_sender.go#L456)):*
> ```Go
> 	tcs.interceptorAlloc.txnLockGatekeeper = txnLockGatekeeper{
> 		wrapped: tcs.wrapped,
> 		mu:      &tcs.mu.Mutex,
> ```

how was this compiling?!
___
*[pkg/kv/txn_interceptor_heartbeater.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbf9h69hpo29vTmSfj:-LYbf9h69hpo29vTmSfk:befv1h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a222f3227df93a90e2f054882151d7b997c99/pkg/kv/txn_interceptor_heartbeater.go#L54)):*
> ```Go
> // progressively larger heartbeat timestamps.
> //
> // Interestingly, there are other mechanisms by which concurrent actors could
> ```

nit: add a NOTE: to this paragraph (which paragraph I like)
___
*[pkg/kv/txn_interceptor_heartbeater.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbfJnM2PcmuZHUWm3_:-LYbfJnM2PcmuZHUWm3a:b-bgajxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a222f3227df93a90e2f054882151d7b997c99/pkg/kv/txn_interceptor_heartbeater.go#L58)):*
> ```Go
> // actors communicate directly with transaction coordinators themselves. This
> // would avoid the need for transaction heartbeats and the PENDING transaction
> // state entirely, but it creates other complications. For instance, by not
> ```

nit: what I would say is that, more generally, we could rely on a node health plane to detect failed coordinators. IMO, there's too many words here on replicated group vs contacting one coordinator (cause I don't really see the replicated txn record state as a good thing; the liveness of the coordinator is what concerns us and that's not a property that can be replicated)
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbge5d5y4GEZeNcrT-:-LYbge5d5y4GEZeNcrT0:b294nq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L29)):*
> ```Go
> // 1. they are used to enforce an ordering between read and write operations in a
> //    single transaction that go to the same key. Each read request that travels
> //    through the interceptor is assigned the current largest sequence number. Each
> ```

s/current largest seq num/the seq num of the most recent write
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbgukj-SKZLATitbQn:-LYbgukj-SKZLATitbQo:bgegsfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L32)):*
> ```Go
> //    write request that travels through the interceptor is assigned a sequence
> //    number larger than any previously allocated.
> // 2. they are used to uniquely identify write operation. Because every write
> ```

why is 2 useful / why do we need to identify whatever? Can you please add more words here?
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbhL_PEfgRsJgqUC6e:-LYbhL_Q7GBNLDda2Tva:b-zd3u0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L41)):*
> ```Go
> //    number ignore writes in the same transaction at larger sequence numbers.
> //    Likewise, writes at a sequence number become no-ops if the result of the
> //    write is already present. If the result of the write is not already present
> ```

could you please add more words about what it means for the "write to already be present"? It means that an intent identical to the result of the evaluation exists, right? So what if the intent was overwritten by a write with a higher seq num? We lose replay protection in that case, right? Or do we still have it because a write with a lower seq num is a no-op? It'd be great to clarify this for my edification.

Really good comment generally, btw.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYarCX6CQfelioM1B88:-LYbhHayAnjituzfOqCC:b-86k91o) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L54)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You're dangerously close to starting a meme.
</blockquote></details>

put a peer ack bounty!

(for the record, I fought Spencer when he introduced this)

(pedantic: the name in the TODO is the name of the person to ask about it, not necessarily the person who'll do it. Although I would like to do it :P)

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-:-LYiK3SN4MLhm9D0rN9C:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

___
*[pkg/kv/txn_coord_sender.go, line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYarYxz8LDGrGFEyQoM:-LYiJQW7B0raN30LOtvG:b-sfno2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_coord_sender.go#L216)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not sure I follow the question. What's wrong with the extra `EndTxn` hitting that code?
</blockquote></details>

`cleanupTxnLocked` has its own internal logic to ensure that it only calls `closeLocked` once.
___
*[pkg/kv/txn_coord_sender.go, line 209 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbnh8u8v2lsl5WmPBJ:-LYiJJ0c9PEfHzo3e654:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/666a72bd9c46f61e949ab6d70754ddbe39f420fe/pkg/kv/txn_coord_sender.go#L209)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> 	The method will always be called exactly once.
> ```

Please clarify when it's called. There's something wrong with "always exactly once".

</blockquote></details>

Done.
___
*[pkg/kv/txn_coord_sender.go, line 456 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYboBP4E7eVFLB-X4Ep:-LYi6wZvBAkHbpmKnbdH:b-1t7juk) ([raw file](https://github.com/cockroachdb/cockroach/blob/17283b6d3770bfbb369b04c71baef2f00a24ba0e/pkg/kv/txn_coord_sender.go#L456)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how was this compiling?!
</blockquote></details>

Because the Mutex was embedded. I changed it because I'd rather have this explicit.
___
*[pkg/kv/txn_coord_sender.go, line 469 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYat2UfBT9u54OZnlla:-LYi7pS8EIjNxsehaPq4:bo8df4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/17283b6d3770bfbb369b04c71baef2f00a24ba0e/pkg/kv/txn_coord_sender.go#L469)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you elaborate on the ordering between the pipeliner and the refresher?
</blockquote></details>

Done. I also mentioned the role of the pipeliner on leaves.
___
*[pkg/kv/txn_coord_sender.go, line 491 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatG5F0xQlf6nqjovF:-LYi8QrJEuymDWFdinN5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17283b6d3770bfbb369b04c71baef2f00a24ba0e/pkg/kv/txn_coord_sender.go#L491)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Explain why the others are absent, for example the metrics recorder.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator_test.go, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatWPMDPas3Bzr-6qL:-LYiIEqt9sDbZ3kd7yrq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded30014f06fb8dcbc11989045a5436543afa50/pkg/kv/txn_interceptor_seq_num_allocator_test.go#L1)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: 2019
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator_test.go, line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatu8NAa3WVaVVCSb1:-LYiIGsf-cLMIq-nGVnK:b-1qkigh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded30014f06fb8dcbc11989045a5436543afa50/pkg/kv/txn_interceptor_seq_num_allocator_test.go#L112)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is just a choice for cleanliness, right? Would this matter for anything except perhaps the 1PC detection?
</blockquote></details>

Yeah, the thing it matters for is 1PC detection. I went back to document this but it's already there :smiley: 
___
*[pkg/kv/txn_interceptor_heartbeater.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbf9h69hpo29vTmSfj:-LYi8rvX8A-ASX_TBA0x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a222f3227df93a90e2f054882151d7b997c99/pkg/kv/txn_interceptor_heartbeater.go#L54)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: add a NOTE: to this paragraph (which paragraph I like)
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_heartbeater.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbfJnM2PcmuZHUWm3_:-LYiBFC06DJ3fQr6AikK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a222f3227df93a90e2f054882151d7b997c99/pkg/kv/txn_interceptor_heartbeater.go#L58)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: what I would say is that, more generally, we could rely on a node health plane to detect failed coordinators. IMO, there's too many words here on replicated group vs contacting one coordinator (cause I don't really see the replicated txn record state as a good thing; the liveness of the coordinator is what concerns us and that's not a property that can be replicated)
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbge5d5y4GEZeNcrT-:-LYiBus5Ce1jCGlE5-12:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L29)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/current largest seq num/the seq num of the most recent write
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYaqWk9-NqnoyxHQaDS:-LYiCthl28L0XktCBVbp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L31)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Might be a good place to mention concurrent use of TxnCoordSenders for the same txn. I think we only do that while reading, and so there's no problem, right?
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYaqb_w1V53UVqOQcw2:-LYiCyDPEEydzyX9mpPY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L32)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> operations
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbgukj-SKZLATitbQn:-LYiE0EcBhkK7_rDhlEf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L32)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why is 2 useful / why do we need to identify whatever? Can you please add more words here?
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYbhL_PEfgRsJgqUC6e:-LYiEaf9-f8rWrY2OTC-:bb3n27g) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L41)):*
> It means that an intent identical to the result of the evaluation exists, right?

Yes, that's correct.

> So what if the intent was overwritten by a write with a higher seq num? We lose replay protection in that case, right? Or do we still have it because a write with a lower seq num is a no-op?

We return a sequence missing error.

> It'd be great to clarify this for my edification.

I replaced the term "result of the write" with "an intent with the same sequence" to be a little more clear.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYarCX6CQfelioM1B88:-LYiH_FqB5XIlOQuPsBy:b7o8d0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/38080ef4d8d9f1c187fca958fdcf4ba3a513e43b/pkg/kv/txn_interceptor_seq_num_allocator.go#L54)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put a peer ack bounty!

(for the record, I fought Spencer when he introduced this)

(pedantic: the name in the TODO is the name of the person to ask about it, not necessarily the person who'll do it. Although I would like to do it :P)
</blockquote></details>

Feel free to ask me about convincing Andrei to address this TODO, although it's fine if other's convince him to do it too.

Removed because I don't think I'm ready for the fallout that comes with starting a meme.
___
*[pkg/kv/txn_interceptor_seq_num_allocator.go, line 44 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34850#-LYatTq54t1K-eFwVU_-:-LYiE9v8CxGUH4W_BKuU:b-h0fee2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded30014f06fb8dcbc11989045a5436543afa50/pkg/kv/txn_interceptor_seq_num_allocator.go#L44)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: extra line
</blockquote></details>

Yeah that was intentional. I find it looks really strange when an indented comment doesn't have a bit of padding before the type definition (see `txnPipeliner`). :man_shrugging:

**Pull request merged**
