### PR TITLE
sql, opt: support hint to disallow zigzag join, support bounded staleness checks

### LINKED ISSUE #67558: sql/opt: check query plan compatibility for bounded staleness reads
Part of #66020.
Needed for **stage 1**.

See https://github.com/cockroachdb/cockroach/blob/025c53decd8eb00cb70a1d410692026c9f8614dc/docs/RFCS/20210519_bounded_staleness_reads.md#sql-optimizer.

Epic CRDB-2527

### PR DESCRIPTION
**Pull request by rytaft**
**opt,sql: support hint to disallow zigzag join**

Release note (sql change): Added support for a new index hint,
`NO_ZIGZAG_JOIN`, which will prevent the optimizer from planning a
zigzag join for the specified table. The hint can be used in the
same way as other existing index hints. For example,
`SELECT * FROM table_name@{NO_ZIGZAG_JOIN};`.

**sql,opt: pass tree.SemaContext to the execbuilder**

This commit updates the execbuilder to include the `tree.SemaContext`
as one of its arguments. This will allow it to use the `AsOfSystemTime`
information in a following commit.

Release note: None

**opt: add execbuilder checks for bounded staleness queries**

This commit adds checks in the execbuilder to ensure that bounded staleness
can only be used with queries that touch at most one row. It also applies
hints for such queries in the optbuilder to ensure that an invalid plan is
not produced. In particular, the hints ensure that no plans with an index
join or zigzag join will be produced.

Fixes #67558

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Very cool! The main question I have is whether the interaction with LIMITs here matches the KV semantics we need for these queries, which is that they are only ever allowed to touch a single range.

> Reviewed 11 of 11 files at r1, 10 of 10 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-:-Mfi_3-Y9tZzWmp5XKP9:b-yzt0uo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @otan, and @rytaft)

___
*[pkg/ccl/logictestccl/testdata/logic_test/as_of, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiXsvv0NCTT7L3xa_H:-MfiXsvv0NCTT7L3xa_I:b2i711v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d1f34b3755df0b48a35757f58e20830b1ddbb55/pkg/ccl/logictestccl/testdata/logic_test/as_of#L214)):*
> ```
> # Scan is limited to one row, so it succeeds.
> statement ok
> SELECT * FROM t AS OF SYSTEM TIME with_max_staleness('1ms') WHERE k IS NULL LIMIT 1
> ```

This one is interesting. From KV's perspective, this is a multi-row scan with a limit. That means that the scan can span multiple ranges, but we expect it to short-circuit once it hits the first row. In practice, we expect that to very often be in the first range we hit, but there's no guarantee of that - we could have empty ranges. And more fundamentally, KV is going to see this and notice that the scan crosses range boundaries even before considering the limit, so it will reject the bounded staleness attempt [here](https://github.com/cockroachdb/cockroach/pull/68194/commits/de4c739a2e0fe7d5511322ede8a77427d85f0313#diff-c95dc7bff738ab9db8b48e841d746adecf5f8383c50ee0e6a7a66b8cd82e2099R1094-R1095) because it can't hit the single-range fast-path. So because of that, I'm not sure we'll be able to support it.
___
*[pkg/sql/opt/memo/expr.go, line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiVifRCN0b4IZj1yXe:-MfiVifRCN0b4IZj1yXf:b-ok9my9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/memo/expr.go#L364)):*
> ```Go
> // Empty returns true if there are no flags set.
> func (sf *ScanFlags) Empty() bool {
> 	return !sf.NoIndexJoin && !sf.ForceIndex && !sf.NoZigzagJoin
> ```

minor nit: Should we keep these conditions in the same order as the fields?
___
*[pkg/sql/opt/memo/expr_format.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiVtubAAtnO3tLYNNl:-MfiVtubAAtnO3tLYNNm:bd52f1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/memo/expr_format.go#L418)):*
> ```Go
> 				b.WriteString(" no-zigzag-join")
> 			}
> 			tp.Childf("flags:%s", b.String())
> ```

Should we `b.WriteString("flags:")` up above and then use `(Node).Child` to avid the extra string formatting in `(Node).Childf`?

Also, do we want this if there are no flags? I believe that was the behavior before.

**Review by mgartner — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @nvanbenschoten, @otan, and @rytaft)

___
*[pkg/ccl/logictestccl/testdata/logic_test/as_of, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiXsvv0NCTT7L3xa_H:-Mfim2se8l970PsnQnon:b5u4xuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d1f34b3755df0b48a35757f58e20830b1ddbb55/pkg/ccl/logictestccl/testdata/logic_test/as_of#L214)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This one is interesting. From KV's perspective, this is a multi-row scan with a limit. That means that the scan can span multiple ranges, but we expect it to short-circuit once it hits the first row. In practice, we expect that to very often be in the first range we hit, but there's no guarantee of that - we could have empty ranges. And more fundamentally, KV is going to see this and notice that the scan crosses range boundaries even before considering the limit, so it will reject the bounded staleness attempt [here](https://github.com/cockroachdb/cockroach/pull/68194/commits/de4c739a2e0fe7d5511322ede8a77427d85f0313#diff-c95dc7bff738ab9db8b48e841d746adecf5f8383c50ee0e6a7a66b8cd82e2099R1094-R1095) because it can't hit the single-range fast-path. So because of that, I'm not sure we'll be able to support it.
</blockquote></details>

Your comment brought up some concerns regarding column families. From KV's perspective is a scan of a single row that has multiple column families considered a multi-row scan? Are all column families of a row guaranteed to be in the same range? Is it worthwhile to have test cases with multiple column families here?
___
*[pkg/sql/opt/memo/expr_format.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiVtubAAtnO3tLYNNl:-MfikI5o0Rbny1LXxIwO:b-2nkps4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/memo/expr_format.go#L418)):*
> Also, do we want this if there are no flags? I believe that was the behavior before.

I think the `if !private.Flags.Empty() { .. }` handles that.
___
*[pkg/sql/opt/xform/select_funcs.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfikoJl0DmMKazc_RyO:-MfikoJl0DmMKazc_RyP:bl6313v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/xform/select_funcs.go#L921)):*
> ```Go
> 	}
> 
> 	if scanPrivate.Flags.NoZigzagJoin {
> ```

nit: you could combine this conditional with the one above
___
*[pkg/sql/opt/xform/select_funcs.go, line 1281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfilL7g-Qu7HjcKR3p6:-MfilL7g-Qu7HjcKR3p7:b-w2xxj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/xform/select_funcs.go#L1281)):*
> ```Go
> 	}
> 
> 	if scanPrivate.Flags.NoZigzagJoin {
> ```

nit: you could combine with above

**Comment by mgartner** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/as_of, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiXsvv0NCTT7L3xa_H:-MfimvMj7Gg2zVH9AE6h:b-iqdks6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d1f34b3755df0b48a35757f58e20830b1ddbb55/pkg/ccl/logictestccl/testdata/logic_test/as_of#L214)):*
> Is it worthwhile to have test cases with multiple column families here?

Disregard this - this should be covered by column family randomization.

**Review by rytaft — COMMENTED** [review]
TFTR! Fixed the LIMIT issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-:-MfisNSI-kDz0vBLY1od:b-a0m6t3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @nvanbenschoten, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/as_of, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiXsvv0NCTT7L3xa_H:-MfiqgknBjsClKugE3j5:bwnekyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d1f34b3755df0b48a35757f58e20830b1ddbb55/pkg/ccl/logictestccl/testdata/logic_test/as_of#L214)):*
> So because of that, I'm not sure we'll be able to support it.

Good catch! This now returns an error.

> From KV's perspective is a scan of a single row that has multiple column families considered a multi-row scan?

This is an important question, and I don't know the answer. @nvanbenschoten?
___
*[pkg/sql/opt/memo/expr.go, line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiVifRCN0b4IZj1yXe:-MfirQTi0VY3KOK_C7Cv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/memo/expr.go#L364)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

minor nit: Should we keep these conditions in the same order as the fields?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/expr_format.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiVtubAAtnO3tLYNNl:-MfirqYiDIW9ryOGN5hn:b-8xrcku) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/memo/expr_format.go#L418)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> Also, do we want this if there are no flags? I believe that was the behavior before.

I think the `if !private.Flags.Empty() { .. }` handles that.
</blockquote></details>

Done. (and @mgartner is right that `!private.Flags.Empty()` takes care of the second point)
___
*[pkg/sql/opt/xform/select_funcs.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfikoJl0DmMKazc_RyO:-MfisEEp0OZdK2ircFxW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/xform/select_funcs.go#L921)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could combine this conditional with the one above
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfilL7g-Qu7HjcKR3p6:-MfisFQn5rs_X7Ml9w-N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e46ddb259cd98b9dd8e3635018bb352a284843/pkg/sql/opt/xform/select_funcs.go#L1281)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could combine with above
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 16 files at r4, 8 of 10 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-:-Mfj4XJE5DKP1OfJvI6m:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @otan, and @rytaft)

___
*[pkg/ccl/logictestccl/testdata/logic_test/as_of, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiXsvv0NCTT7L3xa_H:-Mfj2mQj3S7VvO0eGeJQ:b-1fcgwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d1f34b3755df0b48a35757f58e20830b1ddbb55/pkg/ccl/logictestccl/testdata/logic_test/as_of#L214)):*
> From KV's perspective is a scan of a single row that has multiple column families considered a multi-row scan? Are all column families of a row guaranteed to be in the same range?

Good question. All keys for a row are stored in a single range, so point lookups for rows with multiple column families are allowed in this first stage of bounded staleness reads. If you're interested, this is all enforced in `keys.EnsureSafeSplitKey`.

> Is it worthwhile to have test cases with multiple column families here?

Yes, this is a good idea.
___
*[pkg/sql/opt/memo/expr.go, line 357 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-Mfj45eQ0dYZ1NEYN5nt:-Mfj45eQ0dYZ1NEYN5nu:b-vc6hb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77e90f0a861c67b1f823d628843a61077620c6f/pkg/sql/opt/memo/expr.go#L357)):*
> ```Go
> 	// ForceIndex forces the use of a specific index (specified in Index).
> 	// ForceIndex and NoIndexJoin cannot both be set at the same time.
> 	ForceIndex bool
> ```

Are `NoZigzagJoin` and `ForceIndex` also mutually exclusive?
___
*[pkg/sql/opt/memo/expr_format.go, line 404 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-Mfj4AadDVmxqtFFleik:-Mfj4AadDVmxqtFFleil:bx8c0wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77e90f0a861c67b1f823d628843a61077620c6f/pkg/sql/opt/memo/expr_format.go#L404)):*
> ```Go
> 			if private.Flags.NoIndexJoin {
> 				b.WriteString(" no-index-join")
> 			} else if private.Flags.ForceIndex {
> ```

nit: is it worth baking in the assumption that `NoIndexJoin` and `ForceIndex` aren't both set here? That seems like the kind of constraint that we're better off not relying on for correctness in a formatting function.

**Review by cucaroach — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 16 of 16 files at r4, 10 of 10 files at r5, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68141)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @rytaft)

___
*[pkg/sql/opt/memo/expr_format.go, line 417 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-Mfj3KsmChKkNraSQX_F:-Mfj3KsmChKkNraSQX_G:b-hcvep4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0170c6cbbdb213fcfff431e5fad7267e7349d02f/pkg/sql/opt/memo/expr_format.go#L417)):*
> ```Go
> 			}
> 			if private.Flags.NoZigzagJoin {
> 				b.WriteString(" no-zigzag-join")
> ```

Can you have a NoIndexJoin hint and a NoZigzagJoin hint?    I guess it makes sense, just checking.

**Review by cucaroach — COMMENTED** [review]
:LGTM: I didn't even bother looking at the bounded staleness stuff.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-:-Mfj4yAQ-sHYqIa4bQpu:b-mck7jy)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @rytaft)

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/memo/expr.go, line 357 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-Mfj45eQ0dYZ1NEYN5nt:-Mfj52Sr5E9ySUR_Jn5H:b-q8id40) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77e90f0a861c67b1f823d628843a61077620c6f/pkg/sql/opt/memo/expr.go#L357)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are `NoZigzagJoin` and `ForceIndex` also mutually exclusive?
</blockquote></details>

I don't think so. It's valid to want to scan one index but not perform a zigzag join. I don't see anything in the implementation of these flags that would prevent that.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68141)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @nvanbenschoten, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/as_of, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-MfiXsvv0NCTT7L3xa_H:-Mfj8OeBB84pD4P7i4Qv:b-tlcukh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d1f34b3755df0b48a35757f58e20830b1ddbb55/pkg/ccl/logictestccl/testdata/logic_test/as_of#L214)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> From KV's perspective is a scan of a single row that has multiple column families considered a multi-row scan? Are all column families of a row guaranteed to be in the same range?

Good question. All keys for a row are stored in a single range, so point lookups for rows with multiple column families are allowed in this first stage of bounded staleness reads. If you're interested, this is all enforced in `keys.EnsureSafeSplitKey`.

> Is it worthwhile to have test cases with multiple column families here?

Yes, this is a good idea.
</blockquote></details>

Ah that's great news. Column family randomization should cover the tests as @mgartner mentioned.
___
*[pkg/sql/opt/memo/expr.go, line 357 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-Mfj45eQ0dYZ1NEYN5nt:-Mfj8bHW-x2Iw9JSw9M4:bxc1h1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77e90f0a861c67b1f823d628843a61077620c6f/pkg/sql/opt/memo/expr.go#L357)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think so. It's valid to want to scan one index but not perform a zigzag join. I don't see anything in the implementation of these flags that would prevent that.
</blockquote></details>

^ what he said
___
*[pkg/sql/opt/memo/expr_format.go, line 417 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-Mfj3KsmChKkNraSQX_F:-Mfj9-UW75lCMAcGq-K8:b-54inf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0170c6cbbdb213fcfff431e5fad7267e7349d02f/pkg/sql/opt/memo/expr_format.go#L417)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Can you have a NoIndexJoin hint and a NoZigzagJoin hint?    I guess it makes sense, just checking.
</blockquote></details>

yea, you can have them together.
___
*[pkg/sql/opt/memo/expr_format.go, line 404 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68141#-Mfj4AadDVmxqtFFleik:-Mfj8tvpC9_WWja6fQ5G:bl8lja6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77e90f0a861c67b1f823d628843a61077620c6f/pkg/sql/opt/memo/expr_format.go#L404)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: is it worth baking in the assumption that `NoIndexJoin` and `ForceIndex` aren't both set here? That seems like the kind of constraint that we're better off not relying on for correctness in a formatting function.
</blockquote></details>

Good point. Fixed.

**Comment by rytaft** [comment]
I'm going to go ahead and merge this. Sorry for the incoming rebase, @cucaroach!

bors r+

**Comment by otan** [comment]
haha I was about to move AsOfSystemTime to the EvalContext. Oh well.

**Comment by rytaft** [comment]
bors r-

be my guest!

**Comment by cucaroach** [comment]
No sweat, he who commits first wins!

**Comment by otan** [comment]
im fine if you merge this, or pull the commit out for your PR. i was going to make it the same commit on top of nathan's PR, which is a while away and i don't want to block this!

**Comment by rytaft** [comment]
Ok, in that case I think I'll just merge this since I don't have much time today and I'm going on vacation tomorrow. I can easily revert the changes from my second commit once you add the AOST to EvalContext. Thanks!

bors r+

**Comment by rytaft** [comment]
Gah changed my mind since I see @otan 's PR is basically ready to go.

bors r-

**Comment by rytaft** [comment]
Going with the original plan. Will merge now and revert as needed later.

bors r+

**Comment by mgartner** [comment]
> bors r+
>> bors r-
>>> bors r+
>>>> bors r-
>>>>> bors r+

Well that was an emotional rollercoaster... It's great to show bors that its not the only one that can sensationalize a merge! 😉

**Comment by rytaft** [comment]
😂 Sorry for all the noise!

**Pull request merged**
