### PR TITLE
importccl: Support Importing data in  AVRO format

### LINKED ISSUE #30283: importccl: support importing Avro data
**FEATURE REQUEST**

Avro is a popular data interchange format.  Spanner for example supports data export in Avro format.  Ability to import data in Avro will reduce friction in adoption.  `avro cat` can be used to dump data in CSV and mostly works; however, the CSV file generated is not pure CSV compliant and cannot be used to CockroachDB.  

An Avro import tool should:

- [ ] suggest CockroachDB schema 
- [ ] allow field names translation in CockroachDB schema  
- [ ] reporting and skipping source rows that have errors but continue otherwise

### PR DESCRIPTION
**Pull request by miretskiy**
Add support for importing AVRO data into cockroach.

Importing AVRO file in OCF (object container) format is simple, since
OCF files contain embedded schema:

IMPORT TABLE t (...table definition...) AVRO DATA (dataUri, ...)

The import process tries to be flexible: avro and SQL types do not have to match
exactly.  As long as we can convert from avro datum to SQL datum, we perform the conversion.

In addition, by default, we ignore extraneous avro fields, and set missing SQL fields to 'NULL' value.
This permissive behavior maybe disabled via "WITH strict_validation" option.

We also support importing files containing AVRO records, in plaintext
(json) or binary format (avro fragments).  In order to import such files,
we must also specify avro schema definition:

IMPORT TABLE t (...table definition...) AVRO DATA (avroRecordsUri, ...) WITH data_as_json_records, schema_uri='schemaUri'

Option 'data_as_json_records' indicates that the data is encoded as json (either compact, or pretty printed), and that the json schema for these avro records can be found at 'schema_uri'.

Another example, this time importing binary (avro fragments) records:
IMPORT TABLE t (...table definition...) AVRO DATA (avroRecordsUri, ...) WITH data_as_binary_records, schema='{...inline schema definition...}'

Here, we indicate that the data is binary encoded avro records, and we also specify avro schema inline.

The default record separator for the avro records format is '\n', but that can be changed with 'records_terminated_by' option.

Avro data can also be imported into existing tables (IMPORT INTO...  AVRO DATA ...).

Release note (enterprise change):  Support Importing data in  AVRO format

### CODE REVIEW

**Review by spaskob — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43104)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @rolandcrosby, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 189 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvqWxN8kwz1M9Vy4vQ:-LvvqWxN8kwz1M9Vy4vR:bq1sqpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_processor_test.go#L189)):*
> ```Go
> }
> 
> // A do nothing bulk adder implementation.
> ```

what's the reason for this change?
___
*[pkg/ccl/importccl/import_processor_test.go, line 604 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvqkW_25KwdbRREh7b:-LvvqkW_25KwdbRREh7c:b1yi4ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_processor_test.go#L604)):*
> ```Go
> 
> 	registry.TestingResumerCreationKnobs = map[jobspb.Type]func(raw jobs.Resumer) jobs.Resumer{
> 		// Arrange for our special job resumer to be
> ```

doesn't this fit on 1 line?
___
*[pkg/ccl/importccl/import_processor_test.go, line 885 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-Lvvqsl31qyd_MfK8bX7:-Lvvqsl31qyd_MfK8bX8:b6ma45v) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_processor_test.go#L885)):*
> ```Go
> 			Enclose:        roachpb.MySQLOutfileOptions_Always,
> 			Encloser:       '"',
> 		}}
> ```

last brace should be on new line
___
*[pkg/ccl/importccl/import_stmt.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-Lvvr6HjBlUXEzmjhqFm:-Lvvr6HjBlUXEzmjhqFn:b-sbies1) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_stmt.go#L71)):*
> ```Go
> 	// Turn on strict validation when importing avro records.
> 	avroStrict = "strict_validation"
> ```

optionally remove the blank lines so that all options pertaining to avro are on paragraph
___
*[pkg/ccl/importccl/import_stmt.go, line 404 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvrJSfE0DQ68Ey4Ucr:-LvvrJSfE0DQ68Ey4Ucs:b1x59bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_stmt.go#L404)):*
> ```Go
> 			}
> 			format.PgDump.MaxRowSize = maxRowSize
> 		case "AVRO":
> ```

this is quite large, perhaps you can turn it into a parse function that lives in the avro file?
___
*[pkg/ccl/importccl/read_import_avro.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-Lvvoc70C_Cy8BbtuOt_:-Lvvoc70C_Cy8BbtuOta:bfzipr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L196)):*
> ```
> convertNative
> ```
nit: you can merge with the if case below 
asgn; if err != nil {...
___
*[pkg/ccl/importccl/read_import_avro.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvpJl34NHWmrYRp0pW:-LvvpJl34NHWmrYRp0pX:bystdj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L393)):*
> ```Go
> 		codec:      codec,
> 		buf:        bytes.NewBuffer(nil),
> 		minBufSize: 512,
> ```

perhaps add a comment on the how the magic constants were chosen.
___
*[pkg/ccl/importccl/read_import_avro.go, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvpTh12eU7wbZq_ToR:-LvvpTh12eU7wbZq_ToS:b-ouz3ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L431)):*
> ```Go
> 
> func (a *avroInputReader) start(group ctxgroup.Group) {
> ```

fit on 1 line?
___
*[pkg/ccl/importccl/read_import_avro.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvpiWbBMIBBzXQTVf7:-LvvpiWbBMIBBzXQTVf8:b-l2z4mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L474)):*
> ```Go
> 
> 		if err := stream.Row(ctx, inputIdx, count); err != nil {
> 			// TODO: Report corrupt rows.
> ```

i think we use TODO(username): format
___
*[pkg/ccl/importccl/testdata/avro/simple-sorted.json, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvrnGo7SRihnV3UBiU:-LvvrnGo7SRihnV3UBiV:b-jrbiys) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/testdata/avro/simple-sorted.json#L1)):*
> ```
> 
> ```
is it possible to add a comment on how this file was generated

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43104)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @rolandcrosby, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 189 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvqWxN8kwz1M9Vy4vQ:-LvvzYM19_OI8c81jA5X:b-bxpn9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_processor_test.go#L189)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

what's the reason for this change?
</blockquote></details>

This was described in the test refactoring commit.
Basically, the test TestImportHonorsResumePosition had too many assumptions built in.
It assumed that the data being imported is sorted.  In addition, it assumed that the schema always has a primary key.  I think these assumptions were too strinct (and this test failed when I tried to run it against avro).  I've made the changes so that the test captures the first N keys being imported and ensures those are not re-imported.  So, the minKeyAdder was no longer needed.
___
*[pkg/ccl/importccl/import_processor_test.go, line 604 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvqkW_25KwdbRREh7b:-Lvw-YZ79151ppESINsj:b-d97ct6) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_processor_test.go#L604)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

doesn't this fit on 1 line?
</blockquote></details>

Definitely > 80 characters. 
___
*[pkg/ccl/importccl/import_processor_test.go, line 885 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-Lvvqsl31qyd_MfK8bX7:-Lvw4E671E_MC8zyJMn8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_processor_test.go#L885)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

last brace should be on new line
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-Lvvr6HjBlUXEzmjhqFm:-Lvw0QH-4BSmHX-VahEH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_stmt.go#L71)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

optionally remove the blank lines so that all options pertaining to avro are on paragraph
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt.go, line 404 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvrJSfE0DQ68Ey4Ucr:-Lvw1Q7wETv6Z3Sxyqca:b-zielmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/import_stmt.go#L404)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

this is quite large, perhaps you can turn it into a parse function that lives in the avro file?
</blockquote></details>

Yeah... It's large.  I moved it to a helper method in this file.
I dont' think it makes sense to move it to avro file because all of the options are defined in the import statement and majority of parsing is about those options.
___
*[pkg/ccl/importccl/read_import_avro.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-Lvvoc70C_Cy8BbtuOt_:-Lvw4VXoDwvGeqXH5SRP:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L196)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

> ```
> convertNative
> ```
nit: you can merge with the if case below 
asgn; if err != nil {...
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_avro.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvpJl34NHWmrYRp0pW:-Lvw5_kZBXNiYab7szdA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L393)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

perhaps add a comment on the how the magic constants were chosen.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_avro.go, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvpTh12eU7wbZq_ToR:-Lvw5e168B9EY6_T1MV4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L431)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

fit on 1 line?
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_avro.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvpiWbBMIBBzXQTVf7:-Lvw45sdCyaN3Nx574te:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2e9ad0b41447b311d5db438cbeaf508425ecb6/pkg/ccl/importccl/read_import_avro.go#L474)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

i think we use TODO(username): format
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/testdata/avro/simple-sorted.json, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LvvrnGo7SRihnV3UBiU:-Lvvz5aM4UnX7TPtn3Ai:b-xmarjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/14be44ea1d736931a8272de780571c2f0740a522/pkg/ccl/importccl/testdata/avro/simple-sorted.json#L1)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

> ```
> 
> ```
is it possible to add a comment on how this file was generated
</blockquote></details>

Yes, it's described in the readme.md file.

**Review by spaskob — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r5, 3 of 9 files at r7, 2 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43104)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @rolandcrosby, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 904 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LwEDD2n19q-g4BKzyAL:-LwEDD2n19q-g4BKzyAM:bye7cdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c31277f0f9cf8c420a33e03c5c787cb0bcde54d/pkg/ccl/importccl/import_processor_test.go#L904)):*
> ```
>  
> ```
apparently we use a test package for that:
require.NoError(t, err)

it has also other useful staff for test assertions
___
*[pkg/ccl/importccl/read_import_avro.go, line 192 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LwEDdue9dLStsocRbrF:-LwEDdue9dLStsocRbrG:bkxfesd) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b38f1bfb898ce09c2faea7ffc0313896a86c26/pkg/ccl/importccl/read_import_avro.go#L192)):*
> ```Go
> }
> 
> // Emits row into DatumRowConverter
> ```

I think the convention for public functions is to start with the name of the function so: "Row emits ..."
also elsewhere
___
*[pkg/ccl/importccl/read_import_avro.go, line 340 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LwEEc1BA8pIlcrF3aOH:-LwEEc1BA8pIlcrF3aOI:b-dz1spy) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b38f1bfb898ce09c2faea7ffc0313896a86c26/pkg/ccl/importccl/read_import_avro.go#L340)):*
> ```
>  
> ```
I think all public functions need a comment?
___
*[pkg/ccl/importccl/read_import_avro_test.go, line 320 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LwEEsfp2h1j2QN0l6qA:-LwEEsfp2h1j2QN0l6qB:bnqg0pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b38f1bfb898ce09c2faea7ffc0313896a86c26/pkg/ccl/importccl/read_import_avro_test.go#L320)):*
> ```Go
> 							err = stream.Row(context.TODO(), 0, rowIdx)
> 						}
> 						if err != nil {
> ```

same: use require.NoError
___
*[pkg/ccl/importccl/read_import_avro_test.go, line 330 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-LwEEwvx2BOv3_558STC:-LwEEwvx2BOv3_558STD:b-1vys7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b38f1bfb898ce09c2faea7ffc0313896a86c26/pkg/ccl/importccl/read_import_avro_test.go#L330)):*
> ```Go
> 					}
> 
> 					if rowIdx != 10 {
> ```

require.NotEqual

**Review by spaskob — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43104#-:-LwFA2_s9lMLjkSWkhIk:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @rolandcrosby, and @spaskob)

**Comment by dt** [comment]
We should make sure that our Avro IMPORT format can read our Avro CDC output format, ideally including an automated test of that too -- @danhhz can probably chime in with more detail on exactly how we'd want to verify that, but in a brief chat with him he suggested looking into the "table sink".

FWIW, I guess that merging the initial implementation in this PR, since as an input format we intend to be permissive so any changes such a test revealed were needed would likely just broaden our supported inputs, but it would be nice to make sure we do get such a test in place before we call this done.

**Pull request merged**
