### PR TITLE
roachtest: post github issues on failure

### LINKED ISSUE #24894: roachtest: post issues
We run `roachtest` regularly on both master and `release-2.0`. A few tests are failing regularly, and with the expected growth in the number of tests this is unlikely to become better anytime soon.

roachtest failures should match the experience from our unit and acceptance testing in that they open issues for failed runs. This makes these failures visible to triage and assignable.

We do have notifications in a slack channel, but that does not create the same sense of responsiblity and is already not working well. These notifications are an auxiliary tool at best.

### PR DESCRIPTION
**Pull request by petermattis**
Refactored determination of the issue assignee, splitting it up between
determining the author of the failing line of code and the mapping the
author email to a github login.

Fixes #24894

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@tschottdorf #25596 was just a teaser. This is the PR that provides posting of github issues upon roachtest failure.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/internal/issues/issues_test.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25621#-LCj4UW91RusGNqEUET7:-LCj4UW91RusGNqEUET8:blki1zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8100e54e8e6668bbdca11a09c73f23b896349d93/pkg/cmd/internal/issues/issues_test.go#L88)):*
> ```Go
> 			testName:    "TestReplicateQueueRebalance",
> 			message: "	<autogenerated>:12: storage/replicate_queue_test.go:103, condition failed to evaluate within 45s: not balanced: [10 1 10 1 8]",
> 			author: "bran",
> ```

Is this intentionally bran?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25621#-:-LCj4f3a4kbx0PKw5WRm:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cmd/internal/issues/issues_test.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25621#-LCj4UW91RusGNqEUET7:-LCjRX845YTKwrmYDl8v:bxsahd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8100e54e8e6668bbdca11a09c73f23b896349d93/pkg/cmd/internal/issues/issues_test.go#L88)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Is this intentionally bran?
</blockquote></details>

Yes. Elsewhere in the file we use the name `hodor`. Bran and Hodor are friends (companions?) in Game of Thrones.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25621)*

**Comment by petermattis** [comment]
bors r=tschottdorf

**Pull request merged**
