### PR TITLE
clusterversion: remove some older versions

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This is RFAL, and I'm tagging people directly asking for reviews of different commits (so that all the aliases aren't notified):
- @erikgrinaker commits 1 and 4: `kv: remove TargetBytesAvoidExcess version gate`, `clusterversion: remove MVCCAddSSTable version`
- @andreimatei commits 2 and 9: `util/tracing: remove TraceIDDoesntImplyStructuredRecording version gate`, `rpc: remove SelectRPCsTakeTracingInfoInband version gate`
- @michae2 commits 3 and 7: `sql/stats: remove AlterSystemTableStatisticsAddAvgSizeCol version gate`, `clusterversion: remove noop version gates`
- @RichardJCai  commit 5 `upgrades: remove InsertPublicSchemaNamespaceEntryOnRestore migration`
- @chengxiong-ruan commit 6 `sql: remove UnsplitRangesInAsyncGCJobs version gate`
- @tbg commit 8 `kvserver: remove ProbeRequest version gate`
- @irfansharif commit 10: `upgrades: remove seed tenant span config migration`.

**Review by erikgrinaker — APPROVED** [review]
Thanks for the cleanup! Commits 1 and 4 LGTM.

**Review by chengxiong-ruan — APPROVED** [review]
:100: 
Thanks for doing this! Commit 6 LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84519#-:-N7GW_KD3rG4dVLY0w3E:bbuoc4z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, @michae2, @RichardJCai, and @tbg)

**Review by irfansharif — APPROVED** [review]
Commit 10 LGTM.

**Review by RichardJCai — APPROVED** [review]
`upgrades: remove InsertPublicSchemaNamespaceEntryOnRestore migration` LGTM

**Review by andreimatei — APPROVED** [review]
2 and 9 (`util/tracing: remove TraceIDDoesntImplyStructuredRecording version gate` and `rpc: remove SelectRPCsTakeTracingInfoInband version gate`) :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84519#-:-N7GlZX53GZYuIhWumrj:b-inssd0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2, @tbg, and @yuzefovich)

___
*[`pkg/util/tracing/tracer.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84519#-N7Gl53a1jR-m1ECjp1-:-N7Gl53a1jR-m1ECjp10:bhha00g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c609aead40e64197d7b1e17a1d3c781eaa34d605/pkg/util/tracing/tracer.go#L85)):*
> ```Go
> 	fieldNameOtelSpanID  = prefixTracerState + "otel_spanid"
> 
> 	// fieldNameDeprecatedVerboseTracing is the carrier key indicating that the trace
> ```

I think this can go

**Review by michae2 — COMMENTED** [review]
3 and 7 :lgtm:

> Reviewed 1 of 4 files at r2, 11 of 11 files at r3, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84519#-:-N7HEJbBDeWpBSgQWlig:b-hashtc)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2, @tbg, and @yuzefovich)

**Review by michae2 — APPROVED** [review]

**Review by yuzefovich — COMMENTED** [review]
I removed the 8th commit `kvserver: remove ProbeRequest version gate` and fixed up the tests.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84519#-:-N7HQT2REJ1KIuGrYKjG:b7k0koz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @michae2)

___
*[`pkg/util/tracing/tracer.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84519#-N7Gl53a1jR-m1ECjp1-:-N7HQSGEEJ8kLO1aeRn4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c609aead40e64197d7b1e17a1d3c781eaa34d605/pkg/util/tracing/tracer.go#L85)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this can go
</blockquote></details>

Done.

**Comment by erikgrinaker** [comment]
>I removed the 8th commit kvserver: remove ProbeRequest version gate and fixed up the tests.

Sorry, missed that. I can review it in Tobi's absence, if you open a new PR.

**Comment by yuzefovich** [comment]
>> I removed the 8th commit kvserver: remove ProbeRequest version gate and fixed up the tests.

> Sorry, missed that. I can review it in Tobi's absence, if you open a new PR.

No worries, it was a very small commit, so it's ok to lose it.

**Pull request merged**
