### PR TITLE
deps: update jaeger and grpc

### PR DESCRIPTION
**Pull request by knz**
Recommended by the compliance team. 
Informs (but not resolve) #66081.

The primary purpose of this commit is to upgrade the
github.com/jaegertracing/jaeger dependency to a version not affected by
https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJAEGERTRACINGJAEGERPKGKAFKAAUTH-674508.

The first version not affected is v1.18.1.
This is also the version picked by this commit.

We cannot upgrade to a more recent version because of the separate
issue #66081.

Updating jaeger also forces an upgrade of grpc to v1.38.0 (from v1.33).

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
There are 3 real dep upgrades in this PR:

- [x] golang.org/x/sys/unix - I reviewed this already.
- [x] google.golang.org/genproto/googleapis - I reviewed this already
- [ ] google.golang.org/grpc 

Interestingly, although this PR bumps the version of the jaeger package, only the version changes -- all the changes between 1.17 (prev version) and 1.18.1 (new version) are in files that we don't vendor.

@bdarnell or @erikgrinaker do you want to help with reviewing the grpc upgrade?

**Comment by erikgrinaker** [comment]
Looked over the gRPC changes and changelog, as well as the Protobuf updates, LGTM.

**Comment by knz** [comment]
TFYR!

bors r=erikgrinaker

**Comment by knz** [comment]
typo in comment

bors r=erikgrinaker

**Pull request merged**
