### PR TITLE
release-22.2: vendor: bump Pebble to 1becf8319204

### PR DESCRIPTION
**Pull request by jbowens**
```
1becf831 db: use uncompensated scores to smoothe compaction picking scores
```

Epic: none
Release note (bug fix): This commit reduces the impact of bulk deletions (DROP TABLEs, TRUNCATE TABLEs, or replica removals) on foreground traffic by altering storage engine compaction priorities.
Release justification: Mitigation against a common source of overload and cluster unavailability.

### CODE REVIEW

**Comment by jbowens** [comment]
Hrm, I'm realizing 22.2 is out of maintenance support. This would require an extraordinary release request and doesn't officially meet the requirements.

**Comment by RaduBerinde** [comment]
I think it can still be merged in case we create an extraordinary release for some other reason.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116473#-:-Nle4tYj6r86zUKp8t3f:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]

**Comment by jbowens** [comment]
TFTRs!

**Pull request merged**
