### PR TITLE
docgen: update template for http docs

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
Updated with split pages for request, response, and referenced types.

**Review by taroface — APPROVED** [review]
@mjibson Thank you! LGTM pending some header formatting adjustments.

Also, in today's Dev Inf meeting we talked about incorporating docstrings and request/response examples into full.md. I know we don't have the material now, but does this template allow for those contents to be included in the future?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53368#-:-MFgXA1N90Wnep5yCoUD:bqb5bfp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @taroface)

___
*[docs/generated/http/full.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53368#-MFb1zGfDNuTE8ddzf8R:-MFb1zGfDNuTE8ddzf8S:bd8wp9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/162cfec812a06259a9c51ca2be0bf11886a3851c/docs/generated/http/full.md#L7)):*
> ```Markdown
> 
> 
> ##### Request Parameters
> ```

These and all request/response parameter headings should be h4 and not h5. Sorry, I made a mistake in my earlier mockup.
___
*[docs/generated/http/hotranges-other.md, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53368#-MFgWIfEEvle1S_DYZCA:-MFgWIfEEvle1S_DYZCB:b-kqaj92) ([raw file](https://github.com/cockroachdb/cockroach/blob/e65b85b33ad10469c10fa4785e202e5170c5a218/docs/generated/http/hotranges-other.md#L4)):*
> ```Markdown
> 
> <a name="cockroach.server.serverpb.HotRangesResponse.HotRangesByNodeIdEntry"></a>
> ### HotRangesResponse.HotRangesByNodeIdEntry
> ```

Can each of these (parameter types) be h4? I'm thinking they should be one heading level below the request/response parameters (which we have at h3), to allow the following side nav:

**Review by madelynnblue — COMMENTED** [review]
Description strings are already in the full reference generated file.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53368#-:-MFgdjhw2KrGeEFvYnnk:b3qthhm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[docs/generated/http/full.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53368#-MFb1zGfDNuTE8ddzf8R:-MFgdwTCAB145CIaYGNK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/162cfec812a06259a9c51ca2be0bf11886a3851c/docs/generated/http/full.md#L7)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

These and all request/response parameter headings should be h4 and not h5. Sorry, I made a mistake in my earlier mockup.
</blockquote></details>

Done.
___
*[docs/generated/http/hotranges-other.md, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53368#-MFgWIfEEvle1S_DYZCA:-MFgeCWs0QSC056D0y5b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e65b85b33ad10469c10fa4785e202e5170c5a218/docs/generated/http/hotranges-other.md#L4)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Can each of these (parameter types) be h4? I'm thinking they should be one heading level below the request/response parameters (which we have at h3), to allow the following side nav:



</blockquote></details>

Done.

**Pull request merged**
