### PR TITLE
sql/sem/builtins,sql/paramparse: break tabledesc dep

### PR DESCRIPTION
**Pull request by ajwerner**
The TableStorageParamObserver meant that paramparse and transitively builtins
depended on tabledesc. This was unfortunate because we want seqexpr is depended
on by builtins and we want to use seqexpr in tabledesc, so we have to make
sure that builtins does not depend on tabledesc.

This commit achieves that goal by splitting out paramparse into two new packages:
 * paramparse/tableparamparse: contains the tabledesc-dependent impl of
   StorageParamObserver
 * paramparse/paramparseutil: contains utilities used by all of the impls and
   honestly a bunch of other random sql things to eval and interpret datums.

I don't really like the util package, so suggestions on how to make it better
are welcome.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
> I don't really like the util package, so suggestions on how to make it better

how about flipping the script a bit; leave what we moved to `tableparamparse` and `paramparseutil` inside `paramparse`, and moving the observer/SetParameters/etc. functions (the raw interfaces the builtins need) to a `paramsetter` (?) package.

**Comment by ajwerner** [comment]
You know what, I could move the utils back to paramparse. I'll do it when I get home.

**Comment by ajwerner** [comment]
You know what, I could move the utils back to paramparse. I'll do it when I get home.

**Comment by otan** [comment]
>  You know what, I could move the utils back to paramparse. I'll do it when I get home.

we are of the same hive mind :')

**Comment by ajwerner** [comment]
Easier to open a new PR.

**Comment by ajwerner** [comment]
Replaced by https://github.com/cockroachdb/cockroach/pull/82501.

**Pull request closed without merging**
