### PR TITLE
backupccl: check mismatched cluster regions on backup and restore

### PR DESCRIPTION
**Pull request by Elliebababa**
Previously, if a restore cluster mismatched the regions in backup
cluster, the data would be restored as if the zone configuration
does not exist because we did not do the region check for users.

This patch checks the regions used by backup at restore planning
phase, and hence users are aware of mismatched regions between
backup and restore cluster. If there's a mismatched region, users
can either update cluster localities or restore with option
`--skip-localities-check` to continue.
For serverless users, they are allowed to run restore with
`--skip-localities-check` specified.

Release note (enterprise change): Previously, if a restore
cluster mismatched the regions in backup cluster, the data would
be restored as if the zone configuration does not exist.
This patch checks the regions before restore and hence users
are aware of mismatched regions between backup and restore cluster.
If there's a mismatched region, users can either update cluster
localities or restore with option `--skip-localities-check` to
continue.

Epic CRDB-2599

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
@elliebababa it's great that we were able to get to this so quickly in 21.2 :tada: 

I had a look at the multi-region related files only, and left the restore-heavy files for @pbardea.  Generally it looks good, there are a few minor tweaks I suggested below.

> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-:-M_6PEBs5CsjMO5kiSvx:bwgh354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6IjYQ3w7SmW23WA5w:-M_6IjYR30At0drbtGEd:bhhbj7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L66)):*
> ```Go
> type DescRewriteMap map[descpb.ID]*jobspb.RestoreDetails_DescriptorRewrite
> 
> const multiTenantZoneConfigNo = 49854
> ```

Nit: Does it make sense to change this to `multiTenantZoneConfigIssueNumber`?  At first glance I was confused that this is referring to an issue.
___
*[pkg/ccl/backupccl/restore_planning.go, line 1673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6JgYk8QvFUc068swA:-M_6JgYk8QvFUc068swB:bsayqhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1673)):*
> ```Go
> 	}
> 
> 	if skipLocalitiesCheck || len(regionDesc) == 0 {
> ```

Nit: Does it make sense to split this check into two so that we check for `skipLocalitiesCheck` before we pull all the descriptors?  Might make things perform slightly better in that case.
___
*[pkg/ccl/backupccl/restore_planning.go, line 1693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6KNXz0ss8bKSB-Ssd:-M_6KNXz0ss8bKSB-Sse:b-vzr9gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1693)):*
> ```Go
> 	}
> 
> 	for _, desc := range regionDesc {
> ```

Before we do this, does it make sense to scan all of the descriptors and build a map of the region names?  That way in cases where we have a large number of databases to restore (with mostly overlapping regions), the calls to `findNodeOfRegion` will be proportional to the number of regions, and not the number of databases*regions.
___
*[pkg/ccl/backupccl/restore_planning.go, line 1700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6MG1L1G0WK43f_0p5:-M_6MG1L1G0WK43f_0p6:bmandis) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1700)):*
> ```Go
> 		for _, region := range regionNames {
> 			if nodeFound := findNodeOfRegion(nodesResponse.Nodes, region); !nodeFound {
> 				mismatchErr := errors.Newf("detected mismatch regions between restore cluster and backup cluster, "+
> ```

Nit: Can we make this a bit more verbose "detected a mismatch in regions between the restore cluster and the backup cluster"?
___
*[pkg/ccl/backupccl/restore_planning.go, line 1701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6MTCX91L-_q6RJrkd:-M_6MTCX91L-_q6RJrke:b-slbpwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1701)):*
> ```Go
> 			if nodeFound := findNodeOfRegion(nodesResponse.Nodes, region); !nodeFound {
> 				mismatchErr := errors.Newf("detected mismatch regions between restore cluster and backup cluster, "+
> 					"missing region %s.", region)
> ```

Nit: Is this the _first_ missing region detected?
___
*[pkg/ccl/backupccl/restore_planning.go, line 1702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6MZHW7epwgBDde5vy:-M_6MZHW7epwgBDde5vz:b-k7rxnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1702)):*
> ```Go
> 				mismatchErr := errors.Newf("detected mismatch regions between restore cluster and backup cluster, "+
> 					"missing region %s.", region)
> 				hintsMsg := fmt.Sprintf("please update cluster localities or restore with option %q.", restoreOptSkipLocalitiesCheck)
> ```

Nit: Can we be a bit more verbose here too?  Something like "there are two ways you can resolve this issue: 1) update the cluster to which you're restoring to ensure that the regions present on the node's --locality flags match those present in the backup image, or 2) restore with the %q option"?

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6KNXz0ss8bKSB-Ssd:-M_6ZfzK5NHTVk7xjBnc:b8f9lhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1693)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Before we do this, does it make sense to scan all of the descriptors and build a map of the region names?  That way in cases where we have a large number of databases to restore (with mostly overlapping regions), the calls to `findNodeOfRegion` will be proportional to the number of regions, and not the number of databases*regions.
</blockquote></details>

ah I see! Thanks for catching! Done.

**Review by pbardea — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @Elliebababa)

___
*[pkg/ccl/backupccl/restore_planning.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6IjYQ3w7SmW23WA5w:-M_6aCiRB-Ko9HbAty5J:b-htj77u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L66)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Does it make sense to change this to `multiTenantZoneConfigIssueNumber`?  At first glance I was confused that this is referring to an issue.
</blockquote></details>

Or perhaps even export `multitenancyZoneCfgIssueNo` in pkg/sql/set_zone_config.go and use that here so that references to that issue number are easily greppable.
___
*[pkg/sql/parser/sql.y, line 2782 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6cB0UAAVfC5KF4c-E:-M_6cB0UAAVfC5KF4c-F:b-f34k4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e5e3c0c3907219f7504dcf37b99b85a5a2a2454/pkg/sql/parser/sql.y#L2782)):*
> ```Yacc
>     $$.val = &tree.RestoreOptions{Detached: true}
>   }
> | SKIP_LOCALITIES_CHECK
> ```

Let's add this flag to the restore's parser tests in pkg/sql/parser/parse_test.go

**Review by pbardea — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @Elliebababa)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1707 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6dvk6DmhlV3l-pFKV:-M_6dvk6DmhlV3l-pFKW:b-sbcnnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb56fd79ac39ae6e64c84684308625fd53d06f5/pkg/ccl/backupccl/restore_planning.go#L1707)):*
> ```Go
> 	for region := range regionSet {
> 		if nodeFound := findNodeOfRegion(nodesResponse.Nodes, region); !nodeFound {
> 			mismatchErr := errors.Newf("detected a mismatch in regions between the restore cluster and the backup cluster, "+
> ```

Can we actually update this to list out all of the regions that are missing? I think as a user I would want to know all of the regions that I need to add to this cluster rather than needing to run the restore again and again to find all of the regions I need to add.

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1707 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6dvk6DmhlV3l-pFKV:-M_6imsY5VOCTkmEPdXr:bpx4nzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/afb56fd79ac39ae6e64c84684308625fd53d06f5/pkg/ccl/backupccl/restore_planning.go#L1707)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we actually update this to list out all of the regions that are missing? I think as a user I would want to know all of the regions that I need to add to this cluster rather than needing to run the restore again and again to find all of the regions I need to add.
</blockquote></details>

Aha, I see. Done.
___
*[pkg/sql/parser/sql.y, line 2782 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6cB0UAAVfC5KF4c-E:-M_6gynT-vTpXk-psyZd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e5e3c0c3907219f7504dcf37b99b85a5a2a2454/pkg/sql/parser/sql.y#L2782)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Let's add this flag to the restore's parser tests in pkg/sql/parser/parse_test.go
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]
Restore changes LGTM with nits -- nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-:-M_72qYe31CjyXervIU_:b-xxd8pk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @Elliebababa)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1914 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_72FNP2_3rwhKYRciI:-M_72FNP2_3rwhKYRciJ:b-456ifu) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a08b1476494c111960894bc6e29c8c2c4dbc80/pkg/ccl/backupccl/restore_planning.go#L1914)):*
> ```Go
> 		}
> 	}
> 	if err := checkClusterRegions(ctx, typesByID, p.ExecCfg().NodesStatusServer, restoreStmt.Options.SkipLocalitiesCheck, p.ExecCfg().Codec); err != nil {
> ```

nit: I have a preference of checking for the skip localities check flag here and then only running this check if that flag isn't present to clean up the arguments to the method and so this method actually just checks the cluster regions.
___
*[pkg/ccl/backupccl/testdata/backup-restore/multiregion, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_72Ykw8eFbOXK4xMMS:-M_72Ykw8eFbOXK4xMMT:b-ezfxcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a08b1476494c111960894bc6e29c8c2c4dbc80/pkg/ccl/backupccl/testdata/backup-restore/multiregion#L43)):*
> ```
> 
> # A new cluster with different localities settings.
> new-server name=s3 share-io-dir=s1 allow-implicit-access localities=us-east-1,eu-central-1,eu-north-1
> ```

can we remove either us-east or eu-central here so that we can test that the error message that reports more than 1 missing region works as expected
___
*[pkg/sql/set_zone_config.go, line 943 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_72irOAiI6AhWnJM8Q:-M_72irOAiI6AhWnJM8R:b-j5xtyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a08b1476494c111960894bc6e29c8c2c4dbc80/pkg/sql/set_zone_config.go#L943)):*
> ```Go
> }
> 
> // MultitenancyZoneCfgIssueNo points to the multitenancy zone config issue number
> ```

super-nit: `.` at the end of this line

**Review by ajstorm — APPROVED** [review]
All good on my side too.  Thanks again for making this change!

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-:-M_77XxM203XJMiThARV:b7nwxbh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @Elliebababa)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6KNXz0ss8bKSB-Ssd:-M_76kZ680kP6Kx6aLKT:b9bkkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1693)):*
<details><summary><i>Previously, Elliebababa wrote…</i></summary><blockquote>

ah I see! Thanks for catching! Done.
</blockquote></details>

Looks great!

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64758)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_6KNXz0ss8bKSB-Ssd:-M_7JAChBQQa5YNULkT8:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f585f9217dce911a449f4c51223192826891e870/pkg/ccl/backupccl/restore_planning.go#L1693)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks great!
</blockquote></details>

:)
___
*[pkg/ccl/backupccl/testdata/backup-restore/multiregion, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_72Ykw8eFbOXK4xMMS:-M_7CfXm0FZejS4zRbq2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a08b1476494c111960894bc6e29c8c2c4dbc80/pkg/ccl/backupccl/testdata/backup-restore/multiregion#L43)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

can we remove either us-east or eu-central here so that we can test that the error message that reports more than 1 missing region works as expected
</blockquote></details>

Done.
___
*[pkg/sql/set_zone_config.go, line 943 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64758#-M_72irOAiI6AhWnJM8Q:-M_7JGg44NPlhR3fRCJ6:b-ujivct) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a08b1476494c111960894bc6e29c8c2c4dbc80/pkg/sql/set_zone_config.go#L943)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

super-nit: `.` at the end of this line
</blockquote></details>

haha done.

**Review by pbardea — APPROVED** [review]

**Comment by Elliebababa** [comment]
TFTR!

bors r+

**Pull request merged**
