### PR TITLE
kv: extend the KV API to allow setting the OmitInRangefeeds txn attribute

### PR DESCRIPTION
**Pull request by miraradeva**
See individual commits.

Part of: #112991

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 51 of 52 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-:-NkVa3233WHBUA3sM1fT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @jbowens, @miraradeva, @nvanbenschoten, and @rharding6373)

___
*[`pkg/kv/sender.go` line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-NkV_lIpAWGgeG9MXoWv:-NkV_lIpAWGgeG9MXoWw:b-i4hrbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cf52b6ae77510135c272b8e9891fcacc235400/pkg/kv/sender.go#L129)):*
> ```Go
> 	// SetOmitInRangefeeds sets the OmitInRangefeeds attribute in the Transaction
> 	// proto.
> 	SetOmitInRangefeeds(omitInRangefeeds bool)
> ```

[nit] Will we ever call this with `false`? If not, we could simplify to `SetOmitInRangeFeeds()`.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115282)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @jbowens, @nvanbenschoten, and @rharding6373)

___
*[`pkg/kv/sender.go` line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-NkV_lIpAWGgeG9MXoWv:-NkVe_hKDTaLCVckzOOa:b-9p2o9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cf52b6ae77510135c272b8e9891fcacc235400/pkg/kv/sender.go#L129)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Will we ever call this with `false`? If not, we could simplify to `SetOmitInRangeFeeds()`.
</blockquote></details>

It will be called only with `true` in the general case, but I wasn't 100% sure what SQL will need. I'll let @andyyang890 chime in.

**Review by andyyang890 — APPROVED** [review]
Thanks! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-:-NkVxBWx2xQ3puJZ32WG:b-ftzx47)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jbowens, @miraradeva, @nvanbenschoten, @RaduBerinde, and @rharding6373)

___
*[`pkg/kv/sender.go` line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-NkV_lIpAWGgeG9MXoWv:-NkVxD-o074s83x9n95l:b-a9udmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cf52b6ae77510135c272b8e9891fcacc235400/pkg/kv/sender.go#L129)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

It will be called only with `true` in the general case, but I wasn't 100% sure what SQL will need. I'll let @andyyang890 chime in.
</blockquote></details>

Yeah, I think we currently only plan on calling this with `true`.
___
*[`pkg/kv/txn.go` line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-NkWPvFd4w4MXRVMUjMs:-NkWPvFd4w4MXRVMUjMt:b17svkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cf52b6ae77510135c272b8e9891fcacc235400/pkg/kv/txn.go#L461)):*
> ```Go
> // Transaction proto of the sender.
> //
> // SetOmitInRangefeeds must be called before any operations are performed on the
> ```

Should we maybe have an assertion for this expectation?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115282)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jbowens, @miraradeva, @nvanbenschoten, @RaduBerinde, and @rharding6373)

___
*[`pkg/kv/txn.go` line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-NkWPvFd4w4MXRVMUjMs:-NkWT_pZCqg3qQzW5GWh:bu2cd7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cf52b6ae77510135c272b8e9891fcacc235400/pkg/kv/txn.go#L461)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Should we maybe have an assertion for this expectation?
</blockquote></details>

Ah never mind, I see this is enforced in `*TxnCoordSender.SetOmitInRangefeeds` with the `tc.mu.active` check (I think?).

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115282)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andyyang890, @jbowens, @nvanbenschoten, and @RaduBerinde)

___
*[`pkg/kv/txn.go` line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-NkWPvFd4w4MXRVMUjMs:-NkpJNJfDSxrqNvdOVFL:b8pei5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cf52b6ae77510135c272b8e9891fcacc235400/pkg/kv/txn.go#L461)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Ah never mind, I see this is enforced in `*TxnCoordSender.SetOmitInRangefeeds` with the `tc.mu.active` check (I think?).
</blockquote></details>

Yes, that's right.

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-:-Nkqb3IG38JJIpP4vOgV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @nvanbenschoten, and @RaduBerinde)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 47 of 52 files at r1, 8 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115282#-:-Nksf8xg9wpClr9Z1bB1:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890 and @jbowens)

**Comment by miraradeva** [comment]
bors r=RaduBerinde,andyyang890,nvanbenschoten

**Comment by miraradeva** [comment]
bors r=RaduBerinde,andyyang890,nvanbenschoten

**Pull request merged**
