### PR TITLE
xform,geoindex: use geo inverted indexes for DWithin and DFullyWithin

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/xform/geo.go, line 353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBCFCdb8YEbl2t_eegW:-MBCFCdcAmOaCfe__nfF:bwixgf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb6499024b9ea082ff8aa88100607bde48c66e/pkg/sql/opt/xform/geo.go#L353)):*
> ```Go
> 
> 	// TODO: extract the additional constant parameters for DWithin and DFullyWithin.
> 	// Are they the FuncExpr.Exprs[2] and FuncExpr.Exprs[3]
> ```

I need help with this part.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/xform/geo.go, line 353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBCFCdb8YEbl2t_eegW:-MBCGQV5-dFOIqkW6CQK:bj5wchl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb6499024b9ea082ff8aa88100607bde48c66e/pkg/sql/opt/xform/geo.go#L353)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I need help with this part.
</blockquote></details>

Debugger shows the constant `tree.Expr` parameters are simply Datums so I'll just use them.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-:-MBEjQue4SDZUDFtXJOM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEiIf06O9EyhQ5liKX:-MBEiIf06O9EyhQ5liKY:b-lktvv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain#L44)):*
> ```
> 
> query TTT
> EXPLAIN SELECT k, k_plus_one FROM geo_table2 WHERE ST_DFullyWithin('POINT(3.0 3.0)'::geometry, geom, 1)
> ```

Not in this change, but explain tests should be in`opt/exec/execbuilder/testdata` (the logic tests are supposed to not change when only a plan changes).
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1985 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEgd9Y1AMTuKma-NiT:-MBEgd9Z7TpnadxmzAvX:bqrsjcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/custom_funcs.go#L1985)):*
> ```Go
> }
> 
> // HasTwoVariableArgs returns true if the first two arguments to the given
> ```

This is kind of clunky, it would be cleaner to have two functions `FirstArgIsVariable` and `SecondArgIsVariable` and call them both.

It would be great if we could do something like `$fn:(Function [ (Variable) (Variable) ... ]) &` but we need more functionality in `optgen`.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1987 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEgWwi6wnYng1y4WJw:-MBEgWwi6wnYng1y4WJx:b3tuaus) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/custom_funcs.go#L1987)):*
> ```Go
> // HasTwoVariableArgs returns true if the first two arguments to the given
> // function are variables.
> // TODO: what if both of the arguments are the same variable?
> ```

The rule conditions don't have to be 100% accurate, `GenerateGeoLookupJoins` will figure out what actually can be used.
___
*[pkg/sql/opt/xform/geo.go, line 353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBCFCdb8YEbl2t_eegW:-MBEg5E03LuppMPRqDvo:byfdz3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb6499024b9ea082ff8aa88100607bde48c66e/pkg/sql/opt/xform/geo.go#L353)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Debugger shows the constant `tree.Expr` parameters are simply Datums so I'll just use them.
</blockquote></details>

Use `memo.ExtractConstDatum()`.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1815 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEjHO15iBiezUBtJJF:-MBEjHO15iBiezUBtJJG:bsdn8lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/testdata/rules/join#L1815)):*
> ```
> FROM nyc_census_blocks AS c
> JOIN nyc_neighborhoods@nyc_neighborhoods_geo_idx AS n
> ON ST_DWithin(c.geom, n.geom, 50)
> ```

Add a test with the order of the arguments swapped.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEj3-SDD-imY0E3odY:-MBEj3-SDD-imY0E3odZ:b9omqq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/testdata/rules/select#L1455)):*
> ```
> 
> opt
> SELECT k FROM g WHERE ST_DWithin('POLYGON((0 0, 1 0, 1 1, 0 1, 0 0))'::geometry, geom, 2)
> ```

Should these work when the column is the first argument? If yes, we should swap the arguments in some of these tests

**Review by rytaft — APPROVED** [review]
:lgtm: once you address @raduberinde's comments

> Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-:-MBEmDzy2wVZ7zIGRv3O:b-g7l96y)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[pkg/sql/opt/xform/geo.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEjnK718DzGg9Rel6W:-MBEjnK718DzGg9Rel6X:b-mhfqy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/geo.go#L153)):*
> ```Go
> 		d, ok := additionalParams[0].(*tree.DFloat)
> 		if !ok {
> 			panic(errors.AssertionFailedf("parameter is not float"))
> ```

would be good to print the actual type of d here
___
*[pkg/sql/opt/xform/geo.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEju3e0WYEK5wTgFPz:-MBEju3e0WYEK5wTgFQ-:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/geo.go#L160)):*
> ```Go
> 			b, ok := additionalParams[1].(*tree.DBool)
> 			if !ok {
> 				panic(errors.AssertionFailedf("parameter is not bool"))
> ```

ditto
___
*[pkg/sql/opt/xform/geo.go, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEk_pE5mbqP2tl5uAQ:-MBEk_pE5mbqP2tl5uAR:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/geo.go#L195)):*
> ```Go
> 	d, ok := params[0].(*tree.DFloat)
> 	if !ok {
> 		panic(errors.AssertionFailedf("parameter is not float"))
> ```

ditto
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1815 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEjHO15iBiezUBtJJF:-MBElZ545he4wjQZJBHH:b-y0djls) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/testdata/rules/join#L1815)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Add a test with the order of the arguments swapped.
</blockquote></details>

That won't use the inverted join until I support commuting the args -- although it's fine to add a test case with a TODO.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEj3-SDD-imY0E3odY:-MBElm-nBqMREJoeVvca:bbihdih) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/testdata/rules/select#L1455)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should these work when the column is the first argument? If yes, we should swap the arguments in some of these tests
</blockquote></details>

I haven't added support yet -- there is a TODO in custom_funcs.go

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-:-MBGVPqJAJ_sI0xmElgw:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEiIf06O9EyhQ5liKX:-MBGMnNP-uqGelgjlctk:bgdu072) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain#L44)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not in this change, but explain tests should be in`opt/exec/execbuilder/testdata` (the logic tests are supposed to not change when only a plan changes).
</blockquote></details>

I've added a TODO. What about `EXPLAIN (DISTSQL)` -- that output is dependent on the data placement and there are other logic test files that check that output?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1985 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEgd9Y1AMTuKma-NiT:-MBGQWsu82W38U_R_GIV:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/custom_funcs.go#L1985)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is kind of clunky, it would be cleaner to have two functions `FirstArgIsVariable` and `SecondArgIsVariable` and call them both.

It would be great if we could do something like `$fn:(Function [ (Variable) (Variable) ... ]) &` but we need more functionality in `optgen`.
</blockquote></details>

Done
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1987 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEgWwi6wnYng1y4WJw:-MBGO4fT-s49GMnarVCG:b-f9bcga) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/custom_funcs.go#L1987)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The rule conditions don't have to be 100% accurate, `GenerateGeoLookupJoins` will figure out what actually can be used.
</blockquote></details>

Ah yes. It does nothing there if the variables are not the expected ones.
___
*[pkg/sql/opt/xform/geo.go, line 353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBCFCdb8YEbl2t_eegW:-MBGTI1H87IUggewQK7E:bezqi5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb6499024b9ea082ff8aa88100607bde48c66e/pkg/sql/opt/xform/geo.go#L353)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Use `memo.ExtractConstDatum()`.
</blockquote></details>

I'm quite unfamiliar with the subtleties of the different `Expr` types. This is a `tree.Expr` and not an `opt.Expr` so I couldn't use `memo.ExtractConstDatum`. The code below simply uses a type assertion to `tree.Datum`. 
___
*[pkg/sql/opt/xform/geo.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEjnK718DzGg9Rel6W:-MBGSL541_dSchoHj94s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/geo.go#L153)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to print the actual type of d here
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/geo.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEju3e0WYEK5wTgFPz:-MBGSLu9-B2I0APjeXsw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/geo.go#L160)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/geo.go, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEk_pE5mbqP2tl5uAQ:-MBGSNEG6zwZWTrh7RyY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/geo.go#L195)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1815 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEjHO15iBiezUBtJJF:-MBGU-JS5I7U9MgfuAnF:b-cyulo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/testdata/rules/join#L1815)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

That won't use the inverted join until I support commuting the args -- although it's fine to add a test case with a TODO.
</blockquote></details>

 I'm not keen on duplicating the same TODO (from `custom_funcs.go`) in many places so I've left this test unchanged.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBEj3-SDD-imY0E3odY:-MBGUIli8GsRLBz2g4xi:blm3dt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/32cd7ca3e3217cb969034d623c237d78c1d7e26a/pkg/sql/opt/xform/testdata/rules/select#L1455)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I haven't added support yet -- there is a TODO in custom_funcs.go
</blockquote></details>

I've left this unchanged in light of that existing TODO.

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @sumeerbhola)

___
*[pkg/sql/opt/xform/geo.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBGh55C2vC4pPqinyzp:-MBGh55C2vC4pPqinyzq:b-sdgbb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c2c5769a2a448ae42eb41170f1b11d45b6816f/pkg/sql/opt/xform/geo.go#L42)):*
> ```Go
> // be called on the output of the index operation to filter the results.
> // TODO(rytaft): add ST_DFullyWithin (geoindex.Covers) and ST_DWithin
> //  (geoindex.Intersects) once we add support for extending a geometry.
> ```

You can remove this TODO

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/geo.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-MBGh55C2vC4pPqinyzp:-MBYutMqEOBF4Sp5EqVU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c2c5769a2a448ae42eb41170f1b11d45b6816f/pkg/sql/opt/xform/geo.go#L42)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You can remove this TODO
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50912#-:-MBYyhqGDu733vjb-6ND:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
