### PR TITLE
sql, distsql: marshall EvalContext members through distsql requests

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, EvalContext data was not marshalled through flow
request, and distsql was rejecting builtin functions that needed it.
Flows used for schema change backfills were not subject to that
rejection so they were outright using an empty EvalContext (the column
backfiller had partial initilization for some timestamps).

This patch marshall this data and removes the distsql check against
builtins that use it. For regular queries this means that more queries
are supported (e.g. queries using timestamp casts, date and interval
arithmetic, now() and various others).

For schema changes, this means that a DEFAULT value of unique_rowid()
should work correctly (not sure what it did before, but nothing good in
the absence of the node identifier). As before, the evaluation of
expressions involved in backfills, at least for expressions that need to
be evaluated for each row, uses the UTC timezone; now it does this
explicitly, before it happened because the respective field was not set.
The Database field is empty for backfills and SearchPath is set to
"pg_catalog".
The timestamps returned by now() and friends during backfills are the
same for all rows processed by one attempt to perform the backfill (so
one node that dequeues the respective schemaChanger). Before, new
timestamps were generated once per "chunk" performed by a backfill
processor.

Some new functions for dealing with the session's time.Location are
needed to correctly marshall it regardless of whether it was initialized
from a system-defined tz (e.g. `SET TIME ZONE EST`) or an offset from
GMT (SET TIME ZONE -1).

I've incremented the minimum accepted distsql version because the
backfills now need the planner to have populated the timestamps and
also because we need queries from new gateways (which haven't checked
the old "contextDependent" to be rejected by old nodes).

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Kudos for getting this done the same day!
We do disallow new version flows in older version noses (the node's version is the maximum acceptable).

**Comment by petermattis** [comment]
`s/Evan/Eval` in the PR title.

No new tests is worrisome, though understandable given the rush. Can we follow up with some tests after this has been merged? For example, it seems possible to verify that the `unique_rowid()` values generated for backfill have non-zero low bits. And we can verify that timestamps used for backfill are identical.

**Comment by vivekmenezes** [comment]
I can work on some unittests for this pr while it gets reviewed this
morning. Thanks andrei

**Comment by knz** [comment]
Regarding the backfill: why not reusing the new protobuf you have created in the PR, to ship the evalctx where it's used for backfill?

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_running.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDCrKJvT2SZEc53qGq:-KjDCrKKAzCBNdKl3Jqs:b-hsz1on) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsql_running.go#L133)):*
> ```Go
> 	txn.EnsureProto()
> 
> 	evalCtxProto := distsqlrun.EvalContext{
> ```

Can you capture this initialization in a constructor function. Also please coordinate with @justinj to ensure the monitor added to EvalContext in #15402 is properly re-initialized on the other side of the RPC using this new proto. (I think it will be, but that needs to be checked)

---

*[pkg/sql/schema_changer.go, line 893 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDE3FiOoy_vU3T9KgC:-KjDE3FiOoy_vU3T9KgD:bzei15y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L893)):*
> ```Go
> 		SearchPath: parser.SearchPath{"pg_catalog"},
> 		Location:   &dummyLocationPtr,
> 		// The database is not supposed to be needed in schema changes, as there
> ```

This comment is stale unfortunately. current_schemas() needs it. We'll mark it as known limitation. 

---

*[pkg/sql/schema_changer.go, line 907 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDEPKVNUCFidbKzndV:-KjDEPKVNUCFidbKzndW:b-8tykqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L907)):*
> ```Go
> 	// TODO(andrei): Figure out if this is what we want, and whether the
> 	// timestamp from the session that enqueued the schema change
> 	// is/should be used for impure functions like now().
> ```

FWIW I think yes, this is what we want.

---

*[pkg/sql/vars.go, line 220 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDEezhcUxgzQwC152X:-KjDEezi9XqcQfCBTHZg:bhsy3mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/vars.go#L220)):*
> ```Go
> 	`time zone`: {
> 		Get: func(p *planner) string {
> 			_, origRepr, parsed := sqlbase.ParseFixedOffsetTimeZone(p.session.Location.String())
> ```

Can you explain in a comment why this is needed and why Location.String() is not adequate.

---

*[pkg/sql/distsqlrun/flow.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDF80tFcxzHz8IkOBa:-KjDF80u2a5PDi1qXN6A:b-a4wrp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsqlrun/flow.go#L234)):*
> ```Go
> 		}
> 	}
> 	proc, err := newProcessor(&f.FlowCtx, &ps.Core, &ps.Post, inputs, outputs)
> ```

`return newProcessor(...)`

---

*[pkg/sql/distsqlrun/server.go, line 180 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDFQOiVVUag67IfnRW:-KjDFQOiVVUag67IfnRX:b-whlgp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsqlrun/server.go#L180)):*
> ```Go
> 		Mon:        &monitor,
> 		Ctx: func() context.Context {
> 			// TODO(andrei): This is wrong. Each processor should override Ctx with its
> ```

Please file a follow-up issue to fix this one.

---

*[pkg/sql/parser/builtins.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDFeJIInBLc0LtTgHo:-KjDFeJIInBLc0LtTgHp:b4b9n6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/parser/builtins.go#L111)):*
> ```Go
> 	// determine if expressions can be evaluated on a different node without
> 	// sending over the EvalContext.
> 	distsqlBlacklist bool
> ```

`localOnly` sounds much better than `distsqlBlacklist`.

---

*[pkg/sql/parser/builtins.go, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDG1no-OoifZ_r1cxA:-KjDG1no-OoifZ_r1cxB:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/parser/builtins.go#L193)):*
> ```Go
> // DistSQLBlacklist returns true if the builtin is not supported by DistSQL.
> // See distsqlBlacklist.
> func (b Builtin) DistSQLBlacklist() bool {
> ```

ditto

---

*[pkg/sql/parser/expr.go, line 939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDG3aUO2-tADK48hOC:-KjDG3aUO2-tADK48hOD:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/parser/expr.go#L939)):*
> ```Go
> 
> // IsDistSQLBlacklist returns whether the function is not supported by DistSQL.
> func (node *FuncExpr) IsDistSQLBlacklist() bool {
> ```

ditto

---

*[pkg/sql/sqlbase/time_zone_util.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDGEJnv8ZAXuEKZ4Ba:-KjDGEJnv8ZAXuEKZ4Bb:b5icplh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/sqlbase/time_zone_util.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

year -> 2017

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-:-KjDGJ0TYM2pXXfj03z4:b-bv6ry2)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[pkg/sql/schema_changer.go, line 890 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDKnVUwG2bo6xFl4X-:-KjDKnVVv0wDgDKmoQZg:bn9hvlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L890)):*
> ```Go
> 	dummyLocationHolder := *time.UTC
> 	dummyLocationPtr := &dummyLocationHolder
> 	evalCtx := parser.EvalContext{
> ```

Does this evalCtx have a properly initialized Planner pointer? `pg_get_indexdef()`, `pg_get_userbyid()` need one.

NodeID still needs to be initialized.

Also see my comment at the beginning.

---

*[pkg/sql/distsqlrun/server.go, line 172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDKRTVKbDuPOn5jKgK:-KjDKRTVKbDuPOn5jKgL:b-bf1clf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsqlrun/server.go#L172)):*
> ```Go
> 		return ctx, nil, err
> 	}
> 	evalCtx := parser.EvalContext{
> ```

Does this evalCtx have a properly initialized Planner pointer? `pg_get_indexdef()`, `pg_get_userbyid()` need one. Otherwise you also need to mark them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628)*

**Comment by RaduBerinde** [comment]
Great stuff!

Can you briefly explain in the commit why the new functions around timezone/location stringification are necessary?

FWIW for tests on the non-backfill part, there were a few logic tests that were relying on the `ctxDependent` check (and now they're passing without it). There are also a few tests that fail if the location is not sent correctly if we let through the date casts also.

---

Review status: all files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDPJDta3cb_DciUfhK:-KjDPJDta3cb_DciUfhL:b-dygwbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsql_physical_planner.go#L138)):*
> ```Go
> 	case *parser.CastExpr:
> 		switch t.Type.(type) {
> 		case *parser.DateColType, *parser.TimestampTZColType:
> ```

We should let these through now too, no?

---

*[pkg/sql/schema_changer.go, line 890 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDKnVUwG2bo6xFl4X-:-KjDQ2-k96d9hbOaCXQP:b8i6b3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L890)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Does this evalCtx have a properly initialized Planner pointer? `pg_get_indexdef()`, `pg_get_userbyid()` need one.

NodeID still needs to be initialized.

Also see my comment at the beginning.
</blockquote></details>

Those are the two "blacklisted" functions (for that exact reason). We should include a comment explaining that.

---

*[pkg/sql/parser/builtins.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDS9TIZLjjJTNOsWI9:-KjDS9TIZLjjJTNOsWIA:b-skhua6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/parser/builtins.go#L108)):*
> ```Go
> 
> 	// Set to true when a function depends on members of the EvalContext that are
> 	// not marhslled by DistSQL (e.g. planner). Currently used for DistSQL to
> ```

marshalled

---

*[pkg/sql/parser/builtins.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDFeJIInBLc0LtTgHo:-KjDRvkox1J2wQMTc5Ub:b-g0lx2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/parser/builtins.go#L111)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`localOnly` sounds much better than `distsqlBlacklist`.
</blockquote></details>

But it's more generic and doesn't quite capture what is going on..

---

*[pkg/sql/sqlbase/time_zone_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDQSeGhqGQoBjVUmnD:-KjDQSeGhqGQoBjVUmnE:bn1ta11) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/sqlbase/time_zone_util.go#L53)):*
> ```Go
> // original representation specified by the user. The bool returned is true if
> // parsing was successful.
> func ParseFixedOffsetTimeZone(location string) (int, string, bool) {
> ```

It would help if we had an example.

[nit] I would also name the return values (while still not doing naked returns).

---

*[pkg/sql/sqlbase/time_zone_util.go, line 70 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDRkXUbmgrOjLxDcbp:-KjDRkXUbmgrOjLxDcbq:b-wqtsx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/sqlbase/time_zone_util.go#L70)):*
> ```Go
> 	origRepr := parts[1]
> 	if !strings.HasPrefix(origRepr, "(") || !strings.HasSuffix(origRepr, ")") {
> 		return 0, "", false
> ```

are these cases really the same as the case where we don't have the "fixed offset:" prefix? Seems like we would also want to return an error in this case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-:-KjDRRoCk5LhYPoJUSkJ:b-ap6ro1)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_running.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDCrKJvT2SZEc53qGq:-KjDVIsFp1j_PD5fNpoM:b-v4t3uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsql_running.go#L133)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you capture this initialization in a constructor function. Also please coordinate with @justinj to ensure the monitor added to EvalContext in #15402 is properly re-initialized on the other side of the RPC using this new proto. (I think it will be, but that needs to be checked)
</blockquote></details>

Can you add a comment at evalCtx saying that whenever we add a new field we should consider updating a new field here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628)*

**Comment by vivekmenezes** [comment]
https://github.com/vivekmenezes/cockroach/commit/684469f599d7597bcf55ba0c39687356fbfc418c

please do add any other column backfill tests you'd like to this commit

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[pkg/sql/schema_changer.go, line 891 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDfSLSh9UlgK2Y68qB:-KjDfSLTygSCGhPHMQgZ:b-fe6vie) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L891)):*
> pg_catalog
Make a constant `DefaultSearchPath` in `sqlbase` or somewhere common and use it both here and in `sql` where sessions are initialized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628)*

**Comment by andreimatei** [comment]
@radu added that explanation to the commit message and update the message accordingly for the version check - thanks!

@vivek added your test, thanks!

---

Review status: 10 of 21 files reviewed at latest revision, 17 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDPJDta3cb_DciUfhK:-KjDp80pSyzFuGKEoyQx:bo8hxwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsql_physical_planner.go#L138)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should let these through now too, no?
</blockquote></details>

yes, thanks for catching this

---

*[pkg/sql/distsql_running.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDCrKJvT2SZEc53qGq:-KjDpfo7EOaLPYa-_JBz:b-i46cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsql_running.go#L133)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can you add a comment at evalCtx saying that whenever we add a new field we should consider updating a new field here.
</blockquote></details>

@knz added a ctor

@vivek I had added this comment on parser.EvalContext.

---

*[pkg/sql/schema_changer.go, line 890 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDKnVUwG2bo6xFl4X-:-KjDyeQx4Qj6LQOCjnXZ:bvsr8ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L890)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Those are the two "blacklisted" functions (for that exact reason). We should include a comment explaining that.
</blockquote></details>

@knz NodeID is initialized on each node running a flow.

@radu added a comment about how the returned evalCtx is broken for distsqlBlacklist funs.

---

*[pkg/sql/schema_changer.go, line 891 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDfSLSh9UlgK2Y68qB:-KjE0dHpqRkwGX_mwBgu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L891)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> pg_catalog
Make a constant `DefaultSearchPath` in `sqlbase` or somewhere common and use it both here and in `sql` where sessions are initialized.
</blockquote></details>

Done.

---

*[pkg/sql/schema_changer.go, line 893 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDE3FiOoy_vU3T9KgC:-KjDyKcR4Xb9I5VPL0OS:byynilr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L893)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This comment is stale unfortunately. current_schemas() needs it. We'll mark it as known limitation. 
</blockquote></details>

added a note about current_schemas

---

*[pkg/sql/schema_changer.go, line 907 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDEPKVNUCFidbKzndV:-KjDyB5on1HlwTUITUCV:b-wlebxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L907)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

FWIW I think yes, this is what we want.
</blockquote></details>

in our conversation it sounded like you don't think that so much. But in any case, this is what we have for now. I'll create an issue to discuss more.

---

*[pkg/sql/vars.go, line 220 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDEezhcUxgzQwC152X:-KjE1BGDgXz0-dhnQeXg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/vars.go#L220)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you explain in a comment why this is needed and why Location.String() is not adequate.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/server.go, line 172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDKRTVKbDuPOn5jKgK:-KjE1ODWP3GTbEuyvlQL:biugahk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsqlrun/server.go#L172)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Does this evalCtx have a properly initialized Planner pointer? `pg_get_indexdef()`, `pg_get_userbyid()` need one. Otherwise you also need to mark them.
</blockquote></details>

they had been marked

---

*[pkg/sql/distsqlrun/server.go, line 180 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDFQOiVVUag67IfnRW:-KjE1QqQqCf29hRplkU2:b-d7bhn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsqlrun/server.go#L180)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please file a follow-up issue to fix this one.
</blockquote></details>

will do

---

*[pkg/sql/parser/builtins.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDS9TIZLjjJTNOsWI9:-KjEBExWNfyYzDm3YVrO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/parser/builtins.go#L108)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

marshalled
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/time_zone_util.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDGEJnv8ZAXuEKZ4Ba:-KjEBQSuvCV72pkgzHUx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/sqlbase/time_zone_util.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

year -> 2017
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/time_zone_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDQSeGhqGQoBjVUmnD:-KjECzGC84sBVnQSKZeg:b-gq6lss) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/sqlbase/time_zone_util.go#L53)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It would help if we had an example.

[nit] I would also name the return values (while still not doing naked returns).
</blockquote></details>

done and done

---

*[pkg/sql/sqlbase/time_zone_util.go, line 70 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDRkXUbmgrOjLxDcbp:-KjEB_OXkbldAh7G9aLt:b364fa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/sqlbase/time_zone_util.go#L70)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

are these cases really the same as the case where we don't have the "fixed offset:" prefix? Seems like we would also want to return an error in this case?
</blockquote></details>

yeah I thought about it... These will result in an error when the string is attempted to be parsed by `timeutil.LoadLocation()`.
And the other caller of this (SHOW TIME ZONE) can't deal with errors anyway, and so a malformed string like that will result in a malformed output from that statement.
I don't know... I'll leave it.

---

*[pkg/sql/distsqlrun/flow.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDF80tFcxzHz8IkOBa:-KjE1Lb2789ymeq2_oi6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/distsqlrun/flow.go#L234)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`return newProcessor(...)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-:-KjEIyyouYA0Jb3XiPmk:blot4aj)*

**Comment by knz** [comment]
:lgtm:
So many thanks for getting this ready so quick.

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjEJanwbrfryFWzCvip:-KjEJanwbrfryFWzCviq:b-1hjed0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7e88e5c79027952a6e7072855aefe7d2a7d97b/pkg/sql/distsql_physical_planner.go#L132)):*
> ```Go
> 	case *parser.FuncExpr:
> 		if t.IsDistSQLBlacklist() {
> 			v.err = errors.Errorf("blacklisted function %s not supported", t)
> ```

"function %s cannot be executed with distsql"

(I wouldn't like to see users see the word "blacklisted", that would raise questions)

---

*[pkg/sql/schema_changer.go, line 907 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjDEPKVNUCFidbKzndV:-KjEJtIuGw-z6lrFQO9p:b-utedeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ec554474d66bc079150acbf5b645b649434a118/pkg/sql/schema_changer.go#L907)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

in our conversation it sounded like you don't think that so much. But in any case, this is what we have for now. I'll create an issue to discuss more.
</blockquote></details>

I wrote "this is what we want" specifically regarding `now()` (see my comments on #15633) - the rest still needs discussion. But we can discuss later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-:-KjEKOj5zCet_34FV3qW:b-iui6zq)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-:-KjEL-LHi3DYGnyusMNT:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 20 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628#-KjEJanwbrfryFWzCvip:-KjEMaaevIaTNs1aVdHp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7e88e5c79027952a6e7072855aefe7d2a7d97b/pkg/sql/distsql_physical_planner.go#L132)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"function %s cannot be executed with distsql"

(I wouldn't like to see users see the word "blacklisted", that would raise questions)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15628)*

**Comment by vivekmenezes** [comment]
LGTM

**Pull request merged**
