### PR TITLE
pkg/server: Add last modified timestamp and coordinator ID to /jobs

### PR DESCRIPTION
**Pull request by benbardin**
These values were previously unavailable in UI, but are helpful for debugging..

Release note (ui change): Add last modified timestamp and coordinator ID to
Jobs page to aid in debugging jobs issues.

### CODE REVIEW

**Comment by benbardin** [comment]
Addresses https://github.com/cockroachdb/cockroach/issues/45017

**Comment by benbardin** [comment]
Screen Shot 2022-03-25 at 10 51 18 AM

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78501)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @dhartunian)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78501#-MzGJSGP9axUQbOL-i_j:-MzGJSGP9axUQbOL-i_k:b5fsfyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6464556f9baa19d21bfa5eedfed9ceb1fd2fa9f/pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx#L199)):*
> ```XML
>         content={<p>ID of the coordinating node.</p>}
>       >
>         {"Coordinator ID"}
> ```

Is it worth just saying "Coordinator Node" here?
___
*[pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78501#-MzGKchBBTg4iRoArkFS:-MzGKchBBTg4iRoArkFT:b-f72mup) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6464556f9baa19d21bfa5eedfed9ceb1fd2fa9f/pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx#L205)):*
> ```XML
>     // the default value of `0` is fine for sorting.
>     cell: job =>
>       Object.prototype.hasOwnProperty.call(job, "coordinator_id")
> ```

nit: This check is redundant in because the field is guaranteed to be there since the typescript protobuf definitions this code is compiled with contain the new field you added.

I think just doing ternary with `job.coordinator_id` is fine. The type here is likely a `Long` (as opposed to a primitive) which I think will be missing if this UI talks to an older version of the API.

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78501)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @dhartunian)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78501#-MzGKchBBTg4iRoArkFS:-MzGMLQN9wsIVzx_LwTx:bh3b7s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6464556f9baa19d21bfa5eedfed9ceb1fd2fa9f/pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx#L205)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: This check is redundant in because the field is guaranteed to be there since the typescript protobuf definitions this code is compiled with contain the new field you added.

I think just doing ternary with `job.coordinator_id` is fine. The type here is likely a `Long` (as opposed to a primitive) which I think will be missing if this UI talks to an older version of the API.
</blockquote></details>

Thanks David! The trouble is I'm actually _trying_ to display nothing when coordinator ID is NULL (in the database), which it often is for inactive jobs. If I use `hasOwnProperty`, this works; if I don't, calls to `.coordinator_id` will return `0` for the NULL case.

The other option would be to return a full message, which can _then_ be legally nullable in proto3, but seems a bit like overkill. Thoughts?

**Review by dhartunian — APPROVED** [review]
:lgtm: just squash the fixup and you're good to go

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78501#-:-MzMDLGy-WwWwTxne4mS:bxjrg0b)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @benbardin and @dhartunian)

___
*[-- commits, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78501#-MzMD2qyBZNYCsTLsFFn):*
you should squash the second commit into the first one. merges are via merge commit, not a squash/rebase so all commits are retained and each must be self-contained to a certain extent to facilitate clean reverts and backports.

**Pull request merged**
