### PR TITLE
storage: remove support for handling physically interleaved intents

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks for looking this over, good catches as always.

We have a fair bit of other code related to interleaved intents too, would be good to remove it all. Fine with a separate PR though. For example:

https://github.com/cockroachdb/cockroach/blob/6be337ee8b98587cf2d3bf5df9e99aa0bdaf2459/pkg/roachpb/api.proto#L2078-L2083

https://github.com/cockroachdb/cockroach/blob/631407117b712a45afcbe77b932fadd28faff4ce/pkg/cli/debug.go#L1217

https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/kv/db.go#L789

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-:-NDdWX_V9bhKezfSwqM5:b-cm5i4y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/intent_interleaving_iter.go` line 782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-NDdY_rI72jaXu71ncE8:-NDdY_rI72jaXu71ncE9:bq1ynxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b85b43da2fc705b3208e1fbb1c6476fa6463b20/pkg/storage/intent_interleaving_iter.go#L782)):*
> ```Go
> 		// iter could now be at a bare range key that is equal to the intentIter
> 		// key.
> 		if err := i.maybeSkipIntentRangeKey(); err != nil {
> ```

Good catch, thanks. This seems problematic. Can you pull this out as a separate commit or PR and write a token GA-blocker issue for it, so we can backport to 22.2.0?
___
*[`pkg/storage/intent_interleaving_iter_test.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-NDdYJyy4C7za7fZ7dAd:-NDdYJyy4C7za7fZ7dAe:b-3goazu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b85b43da2fc705b3208e1fbb1c6476fa6463b20/pkg/storage/intent_interleaving_iter_test.go#L185)):*
> ```Go
> }
> 
> // TODO(erikgrinaker,jackson): enhance TestIntentInterleavingIter with range
> ```

Is this not sufficiently covered by the `TestMVCCHistories` cases, which have a fair bit of intents in them?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

Created https://github.com/cockroachdb/cockroach/issues/89428 to point to your list.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-:-NDd_lpm4uqpK4BR04lr:b-8rqjm5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @jbowens)

___
*[`pkg/storage/intent_interleaving_iter.go` line 782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-NDdY_rI72jaXu71ncE8:-NDdajK3DGNfxO5UFqlj:b-hjmznu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b85b43da2fc705b3208e1fbb1c6476fa6463b20/pkg/storage/intent_interleaving_iter.go#L782)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Good catch, thanks. This seems problematic. Can you pull this out as a separate commit or PR and write a token GA-blocker issue for it, so we can backport to 22.2.0?
</blockquote></details>

I think it cannot occur in practice, so not really a GA-blocker.
- non-prefix iteration: even though `pebble.Iterator.*WithLimit` methods claim that the limit enforcement is best-effort, in practice it is not (to make the behavior deterministic for testing inside Pebble's metamorphic test). So if `i.iter.Next` stepped onto a new roachpb.Key, which is the only case where we could have a range but not a point, then `i.intentIterState == pebble.IterAtLimit` will also be true (since the previous limit would have been respected).
- prefix iteration: we cannot step onto a different `roachpb.Key` in `i.iter.Next`.

I made the change because I was worried about making an assumption about the Pebble implementation that may break in the future.
I'm a bit wary of backporting since when iterating over many MVCC versions of the same key, this extra call to `maybeSkipIntentRangeKey` can add cost, and don't want to add more performance work on top of what is already being done by folks for 22.2 regressions. Thoughts?
___
*[`pkg/storage/intent_interleaving_iter_test.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-NDdYJyy4C7za7fZ7dAd:-NDddVV11FeQ2OR3xk4d:b4rkk95) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b85b43da2fc705b3208e1fbb1c6476fa6463b20/pkg/storage/intent_interleaving_iter_test.go#L185)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is this not sufficiently covered by the `TestMVCCHistories` cases, which have a fair bit of intents in them?
</blockquote></details>

I took another look at TestMVCCHistories, and realized I had overlooked the iteration testing via the iter-* commands, which is quite comprehensive, so removed this todo.

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-:-NDdhT9S02w9RzO3kX_d:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/intent_interleaving_iter.go` line 782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89388#-NDdY_rI72jaXu71ncE8:-NDdh5kA5nXMPs9Mm96T:b-yqz9kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b85b43da2fc705b3208e1fbb1c6476fa6463b20/pkg/storage/intent_interleaving_iter.go#L782)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it cannot occur in practice, so not really a GA-blocker.
- non-prefix iteration: even though `pebble.Iterator.*WithLimit` methods claim that the limit enforcement is best-effort, in practice it is not (to make the behavior deterministic for testing inside Pebble's metamorphic test). So if `i.iter.Next` stepped onto a new roachpb.Key, which is the only case where we could have a range but not a point, then `i.intentIterState == pebble.IterAtLimit` will also be true (since the previous limit would have been respected).
- prefix iteration: we cannot step onto a different `roachpb.Key` in `i.iter.Next`.

I made the change because I was worried about making an assumption about the Pebble implementation that may break in the future.
I'm a bit wary of backporting since when iterating over many MVCC versions of the same key, this extra call to `maybeSkipIntentRangeKey` can add cost, and don't want to add more performance work on top of what is already being done by folks for 22.2 regressions. Thoughts?

</blockquote></details>

I see, thanks. In that case I agree, let's not much around with hot path backports this late in the game, and leave this for 23.1.

**Comment by sumeerbhola** [comment]
bors r=erikgrinaker

**Pull request merged**
