### PR TITLE
storage: remove EnablePebbleFormatVersionBlockProperties version gate

### PR DESCRIPTION
**Pull request by bananabrick**
A 21.2 version gate should be safe to remove. We will have already
stepped through the 21.2 cluster versions before deploying a 22.2
binary.

Unblocks https://github.com/cockroachdb/cockroach/issues/80663

Release justification: version gate removal
Release note: None

### CODE REVIEW

**Comment by bananabrick** [comment]
Should be good for review

**Review by jbowens — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @erikgrinaker)

___
*[`pkg/storage/sst_writer_test.go` line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86337#-N9l7JGo0hHaPQmzHnWL:-N9l7JGo0hHaPQmzHnWM:b-qbg52o) ([raw file](https://github.com/cockroachdb/cockroach/blob/13ffe7b1ec2112272a048cf61f54580364d414bd/pkg/storage/sst_writer_test.go#L89)):*
> ```Go
> 			name: "at feature gate",
> 			st: cluster.MakeTestingClusterSettingsWithVersions(
> 				clusterversion.ByKey(clusterversion.TODOPreV22_1),
> ```

can we rework these test cases for range keys?

I'm thinking turn this "at feature gate" test case into one that checks the `EnablePebbleFormatVersionRangeKeys` cluster version, expecting the `sstable.TableFormatPebblev2` table format. Change the "before feature gate" test case into one that checks the `clusterversion.EnablePebbleFormatVersionRangeKeys-1` cluster version, expecting the `sstable.TableFormatPebblev1` table format.
___
*[`pkg/upgrade/upgrademanager/manager_external_test.go` line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86337#-N9l86m4EkMHpUIlhy_9:-N9l86m59QTycip3AEFM:b2ta242) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aeed012d17275c1e5d0f504bf3e792a851b72db/pkg/upgrade/upgrademanager/manager_external_test.go#L528)):*
> ```Go
> 		return version
> 	}
> 	v0 := clusterversion.ClusterVersion{Version: clusterversion.TestingBinaryMinSupportedVersion}
> ```

I don't understand this change.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @erikgrinaker, and @jbowens)

___
*[`pkg/upgrade/upgrademanager/manager_external_test.go` line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86337#-N9l86m4EkMHpUIlhy_9:-N9lscjA-Vv8gA8JhwUa:b-45azq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aeed012d17275c1e5d0f504bf3e792a851b72db/pkg/upgrade/upgrademanager/manager_external_test.go#L528)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I don't understand this change.
</blockquote></details>

v0 was a 21.2 version which didn't have support for block prop collectors, and it caused a panic during the test.

**Review by jbowens — APPROVED** [review]
lgtm

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86337#-:-N9mtIBS04Vxspw0smyu:bb7k0qh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @erikgrinaker, and @jbowens)

___
*[`pkg/upgrade/upgrademanager/manager_external_test.go` line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86337#-N9l86m4EkMHpUIlhy_9:-N9mstXtB3NXz75XIVVP:b-7qd4pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aeed012d17275c1e5d0f504bf3e792a851b72db/pkg/upgrade/upgrademanager/manager_external_test.go#L528)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

v0 was a 21.2 version which didn't have support for block prop collectors, and it caused a panic during the test.
</blockquote></details>

hrm, should we update `clusterversion.binaryMinSupportedVersion` to be `V22_2` or do many tests still depend on it being 21.2?

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @erikgrinaker, and @jbowens)

___
*[`pkg/upgrade/upgrademanager/manager_external_test.go` line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86337#-N9l86m4EkMHpUIlhy_9:-N9n5t4b6TTwK1lEWcrw:biez5sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aeed012d17275c1e5d0f504bf3e792a851b72db/pkg/upgrade/upgrademanager/manager_external_test.go#L528)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

hrm, should we update `clusterversion.binaryMinSupportedVersion` to be `V22_2` or do many tests still depend on it being 21.2?
</blockquote></details>

I think the min supported version will be bumped once the versions gates are removed acc to this issue: https://github.com/cockroachdb/cockroach/issues/80663

**Comment by bananabrick** [comment]
TFTR

bors r+

**Comment by yuzefovich** [comment]
This needs a rebase to fix the merge conflict.

bors r-

**Review by erikgrinaker — APPROVED** [review]

**Pull request merged**
