### PR TITLE
ui: Animate zoom to contents

### LINKED ISSUE #23878: ui: clusterviz: animate zooms when you click a locality

### PR DESCRIPTION
**Pull request by mrtracy**
Animates the zoom-to-content transition using d3.

Resolves #23878

Release note: None

clusterzoomanim

### CODE REVIEW

**Review by vilterp — APPROVED** [review]
LGTM, verified locally. Let's wait for @couchand's thoughts tho.

**Comment by couchand** [comment]
sweet thanks.  LGTM modulo a few minor questions

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7eA2elwmpFyuWL9IGA:-L7eA2emqnOkezUSMelg:b-vbzjj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec0103ce5a9b990ba27ed6556901f98e1b4db13/pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx#L90)):*
> ```XML
>   }
> 
>   animateZoomState(zt: ZoomTransformer, init = false) {
> ```

it seems like this should just replace `updateZoomState`, and the `zoomExtent` part should move to the constructor.  the other use of it (in `onZoom`) has always seemed wrong, but i haven't had time to look into what it's doing.  feel free to correct me if i missed something critical there.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx, line 129 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7eB6S7J8Xb3toyHto5:-L7eB6S7J8Xb3toyHto6:bmiaav7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec0103ce5a9b990ba27ed6556901f98e1b4db13/pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx#L129)):*
> ```XML
>     // locality tree OR that new data has been added to the currently visible
>     // locality.
>     if (_.isEqual(localityLocations.map(ll => ll.location), prevLocalityLocations.map(ll => ll.location))) {
> ```

...then perhaps `prevLocalityLocations` should just keep the locations?  though my comment on the other PR still applies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-:-L7eBeAKEpAtvat0w0Uw:bb5god)*

**Comment by mrtracy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7eA2elwmpFyuWL9IGA:-L7fsppi5gAEFaSoXxk8:b1kyi7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec0103ce5a9b990ba27ed6556901f98e1b4db13/pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx#L90)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

it seems like this should just replace `updateZoomState`, and the `zoomExtent` part should move to the constructor.  the other use of it (in `onZoom`) has always seemed wrong, but i haven't had time to look into what it's doing.  feel free to correct me if i missed something critical there.
</blockquote></details>

I've refactored the zooming logic quite a bit, the relationship between the d3 zoom and the react zoom state should be much clearer now.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx, line 129 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7eB6S7J8Xb3toyHto5:-L7fszB-JjsUCJRUwbdd:b-cfo8wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec0103ce5a9b990ba27ed6556901f98e1b4db13/pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx#L129)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

...then perhaps `prevLocalityLocations` should just keep the locations?  though my comment on the other PR still applies.
</blockquote></details>

Done, now only using the locations here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883)*

**Comment by couchand** [comment]
I think there's a window resizing bug as I noted below.  I'm getting pulled away at the moment, but if you haven't looked into it before this afternoon I'll try to see if I can get it to manifest in actual usage.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx, line 153 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7jAXW0X07giLLVczSR:-L7jAXW0X07giLLVczSS:b4w6uu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c245f4eac657a8238932d549418610dd003371/pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx#L153)):*
> ```XML
>       zoomTransform: this.state.zoomTransform.withViewportSize(props.viewportSize),
>     });
>     this.rezoomToLocalities();
> ```

Didn't notice this before, but I don't think this is quite right... `setState` just queues a state update, so when `rezoomToLocalities` grabs `state.zoomTransform` it'll get the old one.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/zoom.ts, line 148 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7jBNaqH3Laq4n1onjB:-L7jBNaqH3Laq4n1onjC:bbjihto) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c245f4eac657a8238932d549418610dd003371/pkg/ui/ccl/src/views/clusterviz/containers/map/zoom.ts#L148)):*
> ```XML
>     const newZoom = _.clone(this);
>     const boundingSize = bounding.size();
>     newZoom._scale = Math.min(
> ```

I had thought this was the same code as in `minScale`, but looking back at it I see that here is uses `min` and there it uses `max`, and here it's using the box to zoom to, and there it's using the explicit bounds on the transformer.

I think there's a more general principle at play here, and an opportunity to make this more obvious, but it's almost certainly outside the scope of these changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-:-L7jCQ59ESqigkgqxSr1:b-5l9rjt)*

**Comment by couchand** [comment]
Also, thanks for taking care of implementing this and addressing all the comments.  This is really slick from the UI, and you've gotten the code to be pretty straightforward to understand what's happening!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-:-L7jCjPT72uXfYCkudrs:b-fdvqz2)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx, line 153 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7jAXW0X07giLLVczSR:-L7mDqhAqyfkXZ9B2xNf:b-ul7c1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c245f4eac657a8238932d549418610dd003371/pkg/ui/ccl/src/views/clusterviz/containers/map/mapLayout.tsx#L153)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Didn't notice this before, but I don't think this is quite right... `setState` just queues a state update, so when `rezoomToLocalities` grabs `state.zoomTransform` it'll get the old one.
</blockquote></details>

Fixed by making rezoomToLocalities() accept a ZoomTransformer.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/zoom.ts, line 148 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7jBNaqH3Laq4n1onjB:-L7mE30Nu3h5TL6MAgZP:b-uil0wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c245f4eac657a8238932d549418610dd003371/pkg/ui/ccl/src/views/clusterviz/containers/map/zoom.ts#L148)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I had thought this was the same code as in `minScale`, but looking back at it I see that here is uses `min` and there it uses `max`, and here it's using the box to zoom to, and there it's using the explicit bounds on the transformer.

I think there's a more general principle at play here, and an opportunity to make this more obvious, but it's almost certainly outside the scope of these changes.
</blockquote></details>

The difference is that the constructor wants to be as zoomed out as possible, while this wants to be as zoomed-in as possible.  The centering is the same in both cases, which was factored out.

You could try to factor the scale computation, which is taking either the min/max of the width and height ratios of two boxes, but factoring it out is more code than copying it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883)*

**Comment by couchand** [comment]
:lgtm: :shipit: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/zoom.ts, line 148 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-L7jBNaqH3Laq4n1onjB:-L82hT27b4Ku3jWiTIFn:bnwm8ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c245f4eac657a8238932d549418610dd003371/pkg/ui/ccl/src/views/clusterviz/containers/map/zoom.ts#L148)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

The difference is that the constructor wants to be as zoomed out as possible, while this wants to be as zoomed-in as possible.  The centering is the same in both cases, which was factored out.

You could try to factor the scale computation, which is taking either the min/max of the width and height ratios of two boxes, but factoring it out is more code than copying it.
</blockquote></details>

Yeah, I think it doesn't make sense to try to do here.  I was thinking perhaps it would be in the vector (geometry?) lib.  Perhaps methods to get bounding boxes of a particular aspect ratio inscribing/circumscribing a given box would do it?  In any case, just noting as a future opportunity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23883#-:-L82hvauBPzKBlmdlcbf:byzm7aw)*

**Pull request merged**
