### PR TITLE
trigram: support multi-byte string trigrams; perf improvements

### LINKED ISSUE #93744: sql: trigrams don't properly include multi-byte characters
For example:

PG
```
jordan=# SELECT show_trgm('Приветhi');
                                    show_trgm
---------------------------------------------------------------------------------
 {0x8eb714,0x998cbc,0xcd7927,0xe64e48,0xe72710,0xe96751,0x193782,0x233ac5,"hi "}
(1 row)
```

CRDB:

```
root@localhost:26257/defaultdb> select show_trgm('Приветhi');

       show_trgm
-----------------------
  {"  h"," hi","hi "}
(1 row)


Time: 0ms total (execution 0ms / network 0ms)
```

Jira issue: CRDB-22509

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #93744 
Related to #93830

- Add multi-byte character support
- Improve performance

```
name           old time/op    new time/op    delta
Similarity-32    1.72µs ± 0%    0.60µs ± 3%  -64.98%  (p=0.000 n=9+10)

name           old alloc/op   new alloc/op   delta
Similarity-32    1.32kB ± 0%    0.37kB ± 0%  -72.10%  (p=0.000 n=10+10)

name           old allocs/op  new allocs/op  delta
Similarity-32      15.0 ± 0%       6.0 ± 0%  -60.00%  (p=0.000 n=10+10)
```

Release note (sql change): previously, trigrams ignored multi-byte characters from input strings. This is now corrected.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Looks good, some comments and suggestions from me.

For a more fair comparison, it'd probably be good to add the benchmark in the first commit, keep the unicode fix in the second and run the benchmark to see the impact of the fix, and then the third commit would show improvements relative to the unicode fix. This way we'd also be able to see the impact on the benchmark of the whole PR. (Not that I'm advocating for not supporting multi-byte characters.)

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-:-NJlxEPB8P33w1aain1J:b-tmvelc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @mgartner)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJltiOpA3i5Fv55OASK):*
nit: should this be a `bug fix` category? Also, maybe `s/multi-byte/unicode` is more clear?
___
*[`pkg/util/trigram/trigram.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJly3jl4HV6Eep-NHS2:-NJly3jl4HV6Eep-NHS3:b-b5smqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/09f32a712d7a6439efc3414cc2bb79cde3fce8a6/pkg/util/trigram/trigram.go#L22)):*
> ```Go
> 
> // MakeTrigrams returns the downcased, sorted and de-duplicated trigrams for an
> // input string. Non-alphanumeric characters are treated as word boundaries.
> ```

nit: the second sentence here probably needs an update.
___
*[`pkg/util/trigram/trigram.go` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJlyXuD2zljlJbce9LZ:-NJlyXuD2zljlJbce9L_:bi9l8z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f123cc0010a42a62a8a6401e8383ac286f09ee82/pkg/util/trigram/trigram.go#L37)):*
> ```Go
> 	start := -1
> 	oneByteCharsOnly := true
> 	// This loop would be more ergonomic with strings.FieldsFunc, but doing so
> ```

nit: consider adding one more sentence before the current one to explain the high level goal of the loop. It'd probably be good to mention `start` and `end` values in that sentence.
___
*[`pkg/util/trigram/trigram.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJlyq9GBxuKhgmI-sbI:-NJlyq9GBxuKhgmI-sbJ:bvql0yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f123cc0010a42a62a8a6401e8383ac286f09ee82/pkg/util/trigram/trigram.go#L52)):*
> ```Go
> 				start = end
> 			}
> 			if r >= utf8.RuneSelf {
> ```

nit: it might be faster to replace the conditional with a boolean operation, i.e. something like `oneByteCharsOnly = oneBytesCharsOnly && r < utf8.RuneSelf`.
___
*[`pkg/util/trigram/trigram.go` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJlyCby2_2QGcQApwEj:-NJlyCby2_2QGcQApwEk:bfy86pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f123cc0010a42a62a8a6401e8383ac286f09ee82/pkg/util/trigram/trigram.go#L92)):*
> ```Go
> func generateTrigrams(appendTo []string, word string, pad bool, onlyOneByteChars bool) []string {
> 	if pad {
> 		var sb strings.Builder
> ```

Should we reuse the builder across `generateTrigrams` calls?

**Review by jordanlewis — COMMENTED** [review]
Updated benchmark to show the end to end benchmark change, before and after the mb change. I probably should have made 2 PRs here rather than combine them as the perf improvements were not related to worries about making things slower with multibyte, it's just that it's slow in general (see linked issue filed by @chrisseto).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-:-NJrvxl061o0s4a-R4MY:b-o79zvp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/util/trigram/trigram.go` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJlyCby2_2QGcQApwEj:-NJrtRQzCuZJjKEThIfb:b-pzs5nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f123cc0010a42a62a8a6401e8383ac286f09ee82/pkg/util/trigram/trigram.go#L92)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we reuse the builder across `generateTrigrams` calls?
</blockquote></details>

Reusing a builder doesn't do anything unless you are unsafely sharing the backing string memory - it's just a wrapper around a byte buffer.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-:-NJulpFC3ZvPCFcVOwGX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @mgartner)

___
*[`pkg/util/trigram/trigram.go` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJlyCby2_2QGcQApwEj:-NJukzNL-rcbsopdDI68:b9zvsnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f123cc0010a42a62a8a6401e8383ac286f09ee82/pkg/util/trigram/trigram.go#L92)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Reusing a builder doesn't do anything unless you are unsafely sharing the backing string memory - it's just a wrapper around a byte buffer.
</blockquote></details>

Oh, I was thinking about `bytes.Buffer` when I left this comment, nvm.
___
*[`pkg/util/trigram/trigram_test.go` line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-NJukQh83Y2UuF5WgCdJ:-NJukQh83Y2UuF5WgCdK:b1r19cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a6a348c8b871d9a7c1842f9284680da4723791/pkg/util/trigram/trigram_test.go#L104)):*
> ```Go
> 			}
> 		})
> 		fmt.Println(sink)
> ```

nit: this seems like a leftover.

**Comment by jordanlewis** [comment]
Flake (#94197)

bors r+

**Review by mgartner — COMMENTED** [review]
Thanks for fixing this!

> Reviewed 4 of 4 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93757#-:-NKJCsL8-kOs0rPRYZhj:b-whxd1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
