### PR TITLE
add mvcc column to SQLSmith, fix a bug that it found

### LINKED ISSUE #51316: sql: add the mvcc_timestamp column to sqlsmith
^

### PR DESCRIPTION
**Pull request by rohany**
See individual commits for details.

Fixes #51316.

@mjibson for first commit, @yuzefovich for the second.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

What about other processors that call `initRowFetcher`? Maybe `zigzagJoiner` can also produce MVCC column?

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51656#-:-MCmhLgg2XEld_fe-i72:b9w81yq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

**Review by madelynnblue — APPROVED** [review]

**Comment by rohany** [comment]
> What about other processors that call initRowFetcher? Maybe zigzagJoiner can also produce MVCC column?

Zigzag joiner is the remaining one. I'll tackle this separately.

cc @RaduBerinde for a small change to `check_expr.go` -- not sure how this wasn't caught in the CI run before.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

The checks only run in race mode and CI doesn't run most race tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51656#-:-MCn0IzHEROTFZXQaXM4:b-lbufv6)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rohany and @yuzefovich)

___
*[pkg/sql/opt_exec_factory.go, line 566 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51656#-MCn-yTS8KkfpMOn9rhb:-MCn-yTS8KkfpMOn9rhc:b-pp7awh) ([raw file](https://github.com/cockroachdb/cockroach/blob/845f3474e5f1bdbd60f35c189e37219aae820701/pkg/sql/opt_exec_factory.go#L566)):*
> ```Go
> 
> 	// Check if any system columns are requested, as they need special handling.
> 	tableScan.systemColumns, tableScan.systemColumnOrdinals = collectSystemColumnsFromCfg(&colCfg, tabDesc.TableDesc())
> ```

Shouldn't this be part of `initTable`? Feel strange that we do it separately. Plus in there we may be able to use `colCfg` to see if we need to do it at all

**Comment by rohany** [comment]
> Shouldn't this be part of initTable? Feel strange that we do it separately. Plus in there we may be able to use colCfg to see if we need to do it at all

Hmm now that you mention it, that seems better. I'll update this.

**Pull request merged**
