### PR TITLE
sql/opt/invertedexpr: avoid per-span allocations in GeoUnionKeySpansToSpanExpr

### PR DESCRIPTION
**Pull request by nvb**
This commit optimizes a few heap allocations in `GeoUnionKeySpansToSpanExpr` and
in `GeoRPKeyExprToSpanExpr` to avoid per-span/per-expression heap allocations.

Before this change, these heap allocations accounted for 27.52% of all heap
allocations (by object, `alloc_objects`) in a geospatial query of interest:

```
Type: alloc_objects
Time: Aug 21, 2020 at 4:59pm (UTC)
Active filters:
   focus=geoKeyToEncInvertedVal
Showing nodes accounting for 61277094, 27.52% of 222698492 total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                          15270121 99.79% |   github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoToSpan /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:46
                                             32768  0.21% |   github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoToSpan /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:45
  15302889  6.87%  6.87%   15302889  6.87%                | github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoKeyToEncInvertedVal /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:31
----------------------------------------------------------+-------------
                                          16187639 53.52% |   github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoToSpan /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:46
                                          14057686 46.48% |   github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoToSpan /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:45
         0     0%  6.87%   30245325 13.58%                | github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoKeyToEncInvertedVal /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:32
                                          30245325   100% |   github.com/cockroachdb/cockroach/pkg/sql/sqlbase.EncodeTableKey /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/column_type_encoding.go:75
----------------------------------------------------------+-------------
                                          15728880   100% |   github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoToSpan /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:46
         0     0%  6.87%   15728880  7.06%                | github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoKeyToEncInvertedVal /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:38
                                          15728880   100% |   github.com/cockroachdb/cockroach/pkg/roachpb.Key.PrefixEnd /go/src/github.com/cockroachdb/cockroach/pkg/roachpb/data.go:188
----------------------------------------------------------+-------------
```

These allocations were largely avoidable. This commit removes some of
them entirely and reworks the code structure in order to amortize the
unavoidable allocations over the set of keys being encoded. The result
is a large reduction in allocations. On the same workload, allocations
under `geoKeyToEncInvertedVal` dropped from **27.52%** of the workload
to **2.23%** of the workload:

```
Type: alloc_objects
Time: Aug 21, 2020 at 5:04pm (UTC)
Active filters:
   focus=geoKeyToEncInvertedVal
Showing nodes accounting for 3632555, 2.23% of 162651628 total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                           2014518 55.46% |   github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoToSpan /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:53
                                           1618037 44.54% |   github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoToSpan /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:54
         0     0%     0%    3632555  2.23%                | github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr.geoKeyToEncInvertedVal /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/invertedexpr/geo_expression.go:44
                                           3632555   100% |   github.com/cockroachdb/cockroach/pkg/util/encoding.EncodeUvarintAscending /go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:375
----------------------------------------------------------+-------------
```

When applied on top of #53181, this results in a **1.71%** speedup on
the following geospatial query:

```sql
SELECT Count(census.blkid), Count(subways.name)
FROM nyc_census_blocks AS census
JOIN nyc_subway_stations AS subways
ON ST_Intersects(subways.geom, census.geom);
```

```
name                                old ms    new ms    delta
Test/postgis_geometry_tutorial/nyc  136 ±12%  134 ±11%  -1.71%  (p=0.000 n=976+977)
```

In making this change, we also fix a bug where `geoindex.Key` (a uint64) was
being cast to a `tree.DInt` (an int64) during encoding. This could result in
overflow and could cause inverted key spans to be generated.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHKmCu6JVWRoChAGUf:-MFHKmCu6JVWRoChAGUg:b-t9rwk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/deff60341cc2e7b51fd068700f04a07ba87ec21e/pkg/sql/opt/invertedexpr/geo_expression.go#L65)):*
> ```Go
> 	}
> 	spans := make([]InvertedSpan, len(ukSpans))
> 	var b []byte // avoid per-span heap allocations
> ```

this is an interesting pattern to amortize allocation.
___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHMiiJA0zLIZ1OvNeO:-MFHMiiJA0zLIZ1OvNeP:b-xd379w) ([raw file](https://github.com/cockroachdb/cockroach/blob/deff60341cc2e7b51fd068700f04a07ba87ec21e/pkg/sql/opt/invertedexpr/geo_expression.go#L95)):*
> ```Go
> 		case geoindex.Key:
> 			var span InvertedSpan
> 			span, b = geoToSpan(geoindex.KeySpan{Start: e, End: e}, b)
> ```

I can't see a good reason why I wrote 2 loops instead of folding the earlier loop into this case. We don't need to generate the same span twice.
(this won't change your specific benchmark since it is not using an `RPKeyExpr`, but will help elsewhere)
___
*[pkg/sql/opt/xform/testdata/external/postgis-tutorial-idx, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHP0W11_7_taAS60Su:-MFHP0W11_7_taAS60Sv:bqgbfvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/86165b9435549aebb922f88bd0056b82e5d60715/pkg/sql/opt/xform/testdata/external/postgis-tutorial-idx#L42)):*
> ```
>       │              ├── inverted expression: /6
>       │              │    ├── tight: false
>       │              │    └── union spans: ["\x87\xff", "\x87\xff"]
> ```

Looks like we had some cellids that looked like negative values close to zero. 
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHQPg_2I7Wm1QtpeKg:-MFHQPg_2I7Wm1QtpeKh:bwmwtbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fbed29872c48dad6b1b0e1d6120d756d10dfb5/pkg/sql/opt/xform/testdata/rules/join#L3394)):*
> ```
>       │    │    │         ├── inverted expression: /18
>       │    │    │         │    ├── tight: false
>       │    │    │         │    └── union spans: ["\x89", "\xfd \x00\x00\x00\x00\x00\x00\x00")
> ```

didn't notice these spaces in these strings before -- must be because we are using `strconv.Quote(string(span.Start))` in `expression.go` `formatSpan`. Are roachpb.Spans typically formatted purely as hex? That would be easier to read.
___
*[pkg/sql/opt/xform/testdata/rules/limit, line 1178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHRw-73MQftTeOeJcf:-MFHRw-73MQftTeOeJcg:b-v2d3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fbed29872c48dad6b1b0e1d6120d756d10dfb5/pkg/sql/opt/xform/testdata/rules/limit#L1178)):*
> ```
>  │         │         ├── ["\xfd\x10\x00\x00\x00\x00\x00\x00\x00", "\xfd\x10\x00\x00\x00\x00\x00\x00\x00"]
>  │         │         ├── ["\xfd\x14\x00\x00\x00\x00\x00\x00\x00", "\xfd\x14\x00\x00\x00\x00\x00\x00\x00"]
>  │         │         └── ["\xfd\x14\x00\x00\x00\x00\x00\x00\x01", "\xfd\x16\x00\x00\x00\x00\x00\x00\x00")
> ```

I don't understand this change
With a "\xfd" prefix I think this is the `IntMax` path of `EncodeUvarintAscending`. So these must have been positive integers even after casting to int64. So why would anything change. Is this the effect of not using `PrefixEnd` -- I don't see how?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHMiiJA0zLIZ1OvNeO:-MFHkrgk61Wb8qkPS71O:b-k42bvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/deff60341cc2e7b51fd068700f04a07ba87ec21e/pkg/sql/opt/invertedexpr/geo_expression.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I can't see a good reason why I wrote 2 loops instead of folding the earlier loop into this case. We don't need to generate the same span twice.
(this won't change your specific benchmark since it is not using an `RPKeyExpr`, but will help elsewhere)
</blockquote></details>

Mind if I leave that as a follow-up PR for you?
___
*[pkg/sql/opt/xform/testdata/external/postgis-tutorial-idx, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHP0W11_7_taAS60Su:-MFHoQuB8_K3UJBRDBs5:b-fz78rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/86165b9435549aebb922f88bd0056b82e5d60715/pkg/sql/opt/xform/testdata/external/postgis-tutorial-idx#L42)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Looks like we had some cellids that looked like negative values close to zero. 
</blockquote></details>

That's interesting. \x87 means that the values was in the range `[-0xff, 0)` when encoded. So this must have been overflowing an int64 when cast from a uint64.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHQPg_2I7Wm1QtpeKg:-MFHnxDu-QpaJ6w3PvJS:b-8367as) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fbed29872c48dad6b1b0e1d6120d756d10dfb5/pkg/sql/opt/xform/testdata/rules/join#L3394)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

didn't notice these spaces in these strings before -- must be because we are using `strconv.Quote(string(span.Start))` in `expression.go` `formatSpan`. Are roachpb.Spans typically formatted purely as hex? That would be easier to read.
</blockquote></details>

Yes, typically spans are formatted using their `String` method, which attempts to pretty-print where possible, but falls back to hex when not possible. We might want to look into that here.
___
*[pkg/sql/opt/xform/testdata/rules/limit, line 1178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHRw-73MQftTeOeJcf:-MFHlQE88rHqo8rGYQoF:blzkbb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fbed29872c48dad6b1b0e1d6120d756d10dfb5/pkg/sql/opt/xform/testdata/rules/limit#L1178)):*
> Is this the effect of not using PrefixEnd

Yes, I think it is. `\xfd\x16` is not a valid varint encoding. However, it is the `PrefixNext()` of `EncodeUvarintAscending(1657324662872342527) = \xfd\x15\xff\xff\xff\xff\xff\xff\xff`. The value we see here is the result of `EncodeUvarintAscending(1657324662872342528)`. So the difference here is due to the switch away from `PrefixEnd`. Since there are no valid keys between these two possible encodings, the difference is immaterial and either is a valid end key.

**Review by sumeerbhola — APPROVED** [review]
Thanks for doing this!
:lgtm: 

> Reviewed 1 of 7 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-:-MFVuC9wAMPpx_Esg4Wh:bpwuzbv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFHMiiJA0zLIZ1OvNeO:-MFSwEkj7c1c0tTUCOYQ:b-z4a7ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/deff60341cc2e7b51fd068700f04a07ba87ec21e/pkg/sql/opt/invertedexpr/geo_expression.go#L95)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mind if I leave that as a follow-up PR for you?
</blockquote></details>

Yep, I'll do it.
___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFVrPFB9gB3AlvD4Ppv:-MFVrPFB9gB3AlvD4Ppw:b-oke4c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/opt/invertedexpr/geo_expression.go#L44)):*
> ```Go
> 	}
> 	prev := len(b)
> 	b = encoding.EncodeUvarintAscending(b, uint64(k))
> ```

can you add a comment like
// Set the capacity so that the caller appending to enc does not corrupt later keys. 
___
*[pkg/sql/rowenc/index_encoding.go, line 850 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFStO7U8I4vi_9lYnXk:-MFStO7U8I4vi_9lYnXl:ba9fwv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/rowenc/index_encoding.go#L850)):*
> ```Go
> }
> 
> func encodeGeoKeys(inKey []byte, geoKeys []geoindex.Key) (keys [][]byte, err error) {
> ```

looking at this again, just to completely satisfy my curiosity
Whenever `b` is not large enough it will need to be reallocated, so say it grows as `m, 2m, 4m, 8m, 16m`, where `m` is the length added in each loop iteration. Each time it will incur a copy, so `m + 2m + 4m + 8m =15m` bytes will be copied by the time it grows to `16m`. So aside from the copying that is performed in the `append(b, inKey...)`, with `p` loop iterations and total final length `n` this will incur `n` bytes copied and `log p` allocations. Correct? The old code also incurred `n` bytes copied since it did not allocate enough in the `outKey := make([]byte, len(inKey))`, and incurred `p` allocations. We could have changed the old code to incur no copies by over-allocating based on the worst case encoded length of a `DInt` (would break abstraction a bit).

I assume your experience is that the copying cost of the pattern you have changed this to, to not be much of a detractor, yes?
___
*[pkg/sql/rowenc/index_encoding.go, line 856 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFVttRl38FHUfR_wPve:-MFVttRl38FHUfR_wPvf:b-csb22r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/rowenc/index_encoding.go#L856)):*
> ```Go
> 		prev := len(b)
> 		b = append(b, inKey...)
> 		b = encoding.EncodeUvarintAscending(b, uint64(k))
> ```

can you add a comment like
// Set the capacity so that the caller appending to a key in keys does not corrupt later keys.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53215)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFVrPFB9gB3AlvD4Ppv:-MFWMfqk7m1IYOegwTgC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/opt/invertedexpr/geo_expression.go#L44)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment like
// Set the capacity so that the caller appending to enc does not corrupt later keys. 
</blockquote></details>

Done.
___
*[pkg/sql/rowenc/index_encoding.go, line 850 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFStO7U8I4vi_9lYnXk:-MFWO1WR-1yfwhoafF9P:bwiyxl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/rowenc/index_encoding.go#L850)):*
That's a very interesting point. My experience is that the copying cost is far outweighed by the allocator cost in these kinds of situations.

You could also make an argument that this approach is over-allocating by about 100%, in addition to the copying cost. But I think the previous approach would also average out to over-allocating by 100%. So I think that's actually a wash.

> We could have changed the old code to incur no copies by over-allocating based on the worst case encoded length of a DInt (would break abstraction a bit).

The worse-case encoded length of a DInt is 9 bytes. Do you have an idea of the distribution of values for `geoindex.Key`? If the distribution is uniform then we'd expect to use 9 bytes 50% of the time, 8 bytes 25% of the time, etc. That would mean that over-allocating upfront would almost certainly be worth it.

The same argument could be made for `geoKeyToEncInvertedVal` and its callers.
___
*[pkg/sql/rowenc/index_encoding.go, line 856 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFVttRl38FHUfR_wPve:-MFWMldo6QwMQQW4HtG5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/rowenc/index_encoding.go#L856)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment like
// Set the capacity so that the caller appending to a key in keys does not corrupt later keys. 
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53215)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/sql/rowenc/index_encoding.go, line 850 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFStO7U8I4vi_9lYnXk:-MFWjmXq2n_JEUcQScQb:b-msg498) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/rowenc/index_encoding.go#L850)):*
> If the distribution is uniform then we'd expect to use 9 bytes 50% of the time, 8 bytes 25% of the time, etc. That would mean that over-allocating upfront would almost certainly be worth it.

The distribution should be uniform. Geometry (not geography) will have 00 as the leading 2 bits, but that is still close enough.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53215)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[pkg/sql/rowenc/index_encoding.go, line 850 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFStO7U8I4vi_9lYnXk:-MFX-h6o2uZdUhMnTjye:b-bqrjdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/rowenc/index_encoding.go#L850)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> If the distribution is uniform then we'd expect to use 9 bytes 50% of the time, 8 bytes 25% of the time, etc. That would mean that over-allocating upfront would almost certainly be worth it.

The distribution should be uniform. Geometry (not geography) will have 00 as the leading 2 bits, but that is still close enough.

</blockquote></details>

Done (in a second commit). This should avoid the need to ever resize slices `encodeGeoKeys` or `GeoUnionKeySpansToSpanExpr`.

I don't have a benchmark environment set up right now. Are you ok merging this as is or would you like me to get numbers on this change first?

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-:-MFXMq7W9nF96Q7MO6lp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/sql/rowenc/index_encoding.go, line 850 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53215#-MFStO7U8I4vi_9lYnXk:-MFXLbyZ6Rukc8E93DXu:b-64y40i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53a295aff236786327f654d0f126153fee453b8/pkg/sql/rowenc/index_encoding.go#L850)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done (in a second commit). This should avoid the need to ever resize slices `encodeGeoKeys` or `GeoUnionKeySpansToSpanExpr`.

I don't have a benchmark environment set up right now. Are you ok merging this as is or would you like me to get numbers on this change first?
</blockquote></details>

Merging is fine.

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
