### PR TITLE
roachprod: making roachprod subcommands point to a new library

### PR DESCRIPTION
**Pull request by healthy-pod**
Previously, roachprod binary interfaced directly with roachorod's functionality
and there was no way for another tool to make use of that functionality.

This needed to change to create a library that can be used by roachprod binary
and also other tools.

This patch migrates the subcommands functionality to a new library and makes
the binary point to the new library.

Release note: None

### CODE REVIEW

**Review by rail — COMMENTED** [review]
Wooo! Sounds very exciting. This is my first pass.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-:-MmOPtnI4ps7Q47D-Z0m:bd7qssw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

___
*[pkg/cmd/roachprod/main.go, line 628 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmNxU8-5DLGSB9NYnXb:-MmNxU8-5DLGSB9NYnXc:b-m3q4l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L628)):*
> ```Go
> 	Args:  cobra.NoArgs,
> 	Run: wrap(func(cmd *cobra.Command, args []string) error {
> 		cachedHosts, err := roachprod.CachedHosts(cachedHostsCluster)
> ```

Looks like you moved the filtering logic from the CLI to the library. I like the idea, and think it would be even better if you can make the filtering part more flexible. In other words, let's not hardvcode the filtering logic and limit it to "teamcity" - we may change the CI or the naming schema at some point. Maybe add another parameter (optional?) where you pass either the prefix you want to exclude, or a function that would decide whether a hostname should be accepted or not. What do you think?
___
*[pkg/cmd/roachprod/main.go, line 686 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmNzzH69Lakwi-fLNNH:-MmNzzH69Lakwi-fLNNI:b-48656l) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L686)):*
> ```Go
> 	Args: cobra.RangeArgs(0, 1),
> 	Run: wrap(func(cmd *cobra.Command, args []string) error {
> 		return roachprod.List(quiet, listMine, listDetails, listJSON, args)
> ```

A nit: `roachprod.SetupSSH()` uses `quiet` as its last argument. I'd keep it consistent. Also it caries the least amount of mental load, so let's move it to the end. :)

Also, it feels like `List()` should return something that you print here, not only an error. Otherwise the library consumers would need to parse the output. In other words, the library shouldn't print anything, just let the consumers do that.
___
*[pkg/cmd/roachprod/main.go, line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmO62h8DINsOiT8be5M:-MmO62h8DINsOiT8be5N:b-kht8r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L851)):*
> ```Go
> 	Args: cobra.ExactArgs(1),
> 	Run: wrap(func(cmd *cobra.Command, args []string) error {
> 		newClusterOpts := roachprod.NewClusterOpts{
> ```

Hmm, `newClusterOpts` sounds like something for a *new* cluster. In other words, I was expecting to have something different for existing clusters. Maybe remove the "New" prefix? Or am I missing something?
___
*[pkg/cmd/roachprod/main.go, line 856 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOHk37DqlQUeQGHY3H:-MmOHk37DqlQUeQGHY3I:b-m8lu31) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L856)):*
> ```Go
> 			NodeEnv: nodeEnv, NumRacks: numRacks, MaxConcurrency: maxConcurrency,
> 		}
> 		return roachprod.Extend(newClusterOpts, extendLifetime, username)
> ```

Same here. The printing part should be done in `main()`.
___
*[pkg/cmd/roachprod/main.go, line 1038 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOIKnZ0121yNu7UEaV:-MmOIKnZ0121yNu7UEaW:b-1j8w3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L1038)):*
> ```Go
> 			NodeEnv: nodeEnv, NumRacks: numRacks, MaxConcurrency: maxConcurrency,
> 		}
> 		return roachprod.Monitor(newClusterOpts, monitorIgnoreEmptyNodes, monitorOneShot)
> ```

Same here. Print stuff here.
___
*[pkg/cmd/roachprod/main.go, line 1277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOJ3zm9OumFGZf4fXI:-MmOJ3zm9OumFGZf4fXJ:b7wx37j) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L1277)):*
> ```Go
> 			NodeEnv: nodeEnv, NumRacks: numRacks, MaxConcurrency: maxConcurrency,
> 		}
> 		return roachprod.SQL(newClusterOpts, args[1:])
> ```

Feels like this operation should return something, not quite sure what format we should use though...
___
*[pkg/cmd/roachprod/main.go, line 1293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOJYzK5B2H6Kanorlo:-MmOJYzL7Z3CM9rkDuho:b-azksp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L1293)):*
> ```Go
> 			NodeEnv: nodeEnv, NumRacks: numRacks, MaxConcurrency: maxConcurrency,
> 		}
> 		return roachprod.PgURL(newClusterOpts, external)
> ```

Something similar here. The library prints things instead of `main()`.
___
*[pkg/cmd/roachprod/main.go, line 1454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOJgYt7wT6DfrpjmCf:-MmOJgYt7wT6DfrpjmCg:b-xc4olp) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L1454)):*
> ```Go
> 			NodeEnv: nodeEnv, NumRacks: numRacks, MaxConcurrency: maxConcurrency,
> 		}
> 		return roachprod.AdminUrl(newClusterOpts, adminurlIPs, adminurlOpen, adminurlPath)
> ```

Same same. Print stuff here :)
___
*[pkg/roachprod/roachprod.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmO1aNhBViAts75L3rO:-MmO1aNi0HrVHtJ2qSBp:b6x9d1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/roachprod/roachprod.go#L89)):*
> ```Go
> 	// Acquire a filesystem lock so that two concurrent synchronizations of
> 	// roachprod state don't clobber each other.
> 	f, err := os.Create(lockFile)
> ```

Hmm, maybe we should also clean up this file after the operation is done. Apparently I have it :) 
___
*[pkg/roachprod/roachprod.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOKTxuDwRvg13XT7vH:-MmOKTxuDwRvg13XT7vI:busk94n) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/roachprod/roachprod.go#L138)):*
> ```Go
> 	if refreshDNS {
> 		if !quiet {
> 			fmt.Println("Refreshing DNS entries...")
> ```

I'd probably search for every `fmt` in this file and either replace it with logging or make sure that the printed value is returned to the caller. 
___
*[pkg/roachprod/roachprod.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmO13Bt9vO9Evrz-ccR:-MmO13Bt9vO9Evrz-ccS:b-8k31hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/roachprod/roachprod.go#L207)):*
> ```Go
> 	if listJSON {
> 		if listDetails {
> 			return errors.New("--json cannot be combined with --detail")
> ```

Can you move this check before you call `Sync()`. It'd be better to fail faster, without any network operations.
___
*[pkg/roachprod/utils.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOLQXIEQu4EI2GEVEZ:-MmOLQXIEQu4EI2GEVE_:b-rr740) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/roachprod/utils.go#L23)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/cmd/roachprod/config"
> 	"github.com/cockroachdb/cockroach/pkg/cmd/roachprod/install"
> 	"github.com/cockroachdb/cockroach/pkg/cmd/roachprod/vm"
> ```

I think this is OK for now, but it feels that a library shouldn't use anything from `pkg/cmd` in its final version.

Also, I'm not a big fan of file names like "util", "common", "misc", etc. :) Not sure how to name this one, but we can probably move some parts of it to other files.

**Review by healthy-pod — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71660)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod and @rail)

___
*[pkg/cmd/roachprod/main.go, line 628 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmNxU8-5DLGSB9NYnXb:-MnR4qFGDnWsTi95QhV1:biztw2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L628)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Looks like you moved the filtering logic from the CLI to the library. I like the idea, and think it would be even better if you can make the filtering part more flexible. In other words, let's not hardvcode the filtering logic and limit it to "teamcity" - we may change the CI or the naming schema at some point. Maybe add another parameter (optional?) where you pass either the prefix you want to exclude, or a function that would decide whether a hostname should be accepted or not. What do you think?
</blockquote></details>

Changed the library implementation to return unfiltered hosts to give users more flexibility with their filtering logic.
___
*[pkg/cmd/roachprod/main.go, line 686 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmNzzH69Lakwi-fLNNH:-MnR5KZmD_icMBtZuDxf:bdad07y) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L686)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

A nit: `roachprod.SetupSSH()` uses `quiet` as its last argument. I'd keep it consistent. Also it caries the least amount of mental load, so let's move it to the end. :)

Also, it feels like `List()` should return something that you print here, not only an error. Otherwise the library consumers would need to parse the output. In other words, the library shouldn't print anything, just let the consumers do that.
</blockquote></details>

quiet is no longer passed as a parameter to roachprod.SetupSSH() as I realized it's part of ClusterOpts struct (or install.SyncedCluster).
___
*[pkg/cmd/roachprod/main.go, line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmO62h8DINsOiT8be5M:-MnR5lsZ7ciy5fqhGpx0:bq0ain) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/cmd/roachprod/main.go#L851)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Hmm, `newClusterOpts` sounds like something for a *new* cluster. In other words, I was expecting to have something different for existing clusters. Maybe remove the "New" prefix? Or am I missing something?
</blockquote></details>

Realized that NewClusterOpts type is just a subset of install.SyncedCluster so used that instead.

**Review by healthy-pod — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71660)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod and @rail)

___
*[pkg/roachprod/roachprod.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmO1aNhBViAts75L3rO:-MnR6rip7LEjZAo_SI1U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/roachprod/roachprod.go#L89)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Hmm, maybe we should also clean up this file after the operation is done. Apparently I have it :) 
</blockquote></details>

Done.
___
*[pkg/roachprod/roachprod.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmO13Bt9vO9Evrz-ccR:-MnR6xLN3DGudKjf-LBC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/roachprod/roachprod.go#L207)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Can you move this check before you call `Sync()`. It'd be better to fail faster, without any network operations.
</blockquote></details>

Done.
___
*[pkg/roachprod/utils.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MmOLQXIEQu4EI2GEVEZ:-MnR6wCiCyv-RlkzjuyJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c2def07a5ef552abd15613f6a0cbdfbd74fb49/pkg/roachprod/utils.go#L23)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I think this is OK for now, but it feels that a library shouldn't use anything from `pkg/cmd` in its final version.

Also, I'm not a big fan of file names like "util", "common", "misc", etc. :) Not sure how to name this one, but we can probably move some parts of it to other files.
</blockquote></details>

Done.

**Review by rail — CHANGES_REQUESTED** [review]
I found a few nits. :)  Just wanted to address those before we merge.
I tries using the new CLI and everything that I tried worked perfectly! \o/
I also ran `local roachtest`against this PR and it worked flawlessly! See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ScratchProjectPutTcExperimentsInHere_RailLocalRoachtest/3670468

Very excited to see this merged ASAP! 

> Reviewed 53 of 83 files at r2, 31 of 40 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-:-MnW7vihCcT4TqFL8r0M:b-wd8d2z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod and @rail)

___
*[pkg/roachprod/vm/azure/flags.go, line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW73qF73vIphWhvxBr:-MnW73qF73vIphWhvxBs:bgcw74g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/azure/flags.go#L23)):*
> ```Go
> )
> 
> // ProviderOpts TODO
> ```

TODO please :)
___
*[pkg/roachprod/vm/azure/flags.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW76-A2FxNZ9cQCw4x:-MnW76-A2FxNZ9cQCw4y:b-tg1cmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/azure/flags.go#L45)):*
> ```Go
> var defaultZone = "1"
> 
> // DefaultProviderOpts TODO
> ```

And here :)
___
*[pkg/testutils/lint/lint_test.go, line 807 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7MZl2K7fiU0BXx46:-MnW7MZl2K7fiU0BXx47:b3ykvnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/testutils/lint/lint_test.go#L807)):*
> ```Go
> 			":!cli/debug_synctest.go",
> 			":!cmd/**",
> 			":!roachprod", // TODO: switch to contextutil
> ```

Can you file a GitHub issue and specify it here please.
___
*[pkg/testutils/lint/lint_test.go, line 1521 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7T4G1G8S48cSAY7r:-MnW7T4G1G8S48cSAY7s:b-nwrpmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/testutils/lint/lint_test.go#L1521)):*
> ```Go
> 			stream.GrepNot(`cockroach/pkg/testutils/lint: log$`),
> 			stream.GrepNot(`cockroach/pkg/util/sysutil: syscall$`),
> 			stream.GrepNot(`cockroach/pkg/roachprod/install: syscall$`), // TODO: switch to sysutil
> ```

The same here.
___
*[pkg/roachprod/install/cluster_synced.go, line 1197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW5qWpAFXMyg6NLAmj:-MnW5qWpAFXMyg6NLAmk:b-ej9dxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/install/cluster_synced.go#L1197)):*
> ```
> clog
> ```
A nit: is there any reason to use `clog` instead of `log`? I see `log` in other files.
___
*[pkg/roachprod/install/cockroach.go, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW62Jr0c14nVxJIhQv:-MnW62Jr0c14nVxJIhQw:b-2lez9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/install/cockroach.go#L38)):*
> ```
> TODO
> ```
Can you fill the place holder ;)
___
*[pkg/roachprod/vm/vm.go, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW6ER97g0Rm2IkFt8d:-MnW6ERA79g0uU8tbDfI:bu6jy9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/vm.go#L156)):*
> ```Go
> }
> 
> // DefaultCreateOpts TODO
> ```

Can you address the TODO. :)
BTW, it's so great to have all values in one structure - so much easier to read! :100: 
___
*[pkg/roachprod/vm/aws/aws.go, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW6gasDRumt1RuN2tg:-MnW6gasDRumt1RuN2th:b-tsso4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/aws/aws.go#L188)):*
> ```Go
> }
> 
> // DefaultProviderOpts TODO
> ```

Love the centralized structure! Can you address the TODO please :)
___
*[pkg/roachprod/vm/aws/support.go, line 192 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW6raD7iDLttwxdEig:-MnW6raD7iDLttwxdEih:b-pg2gdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/aws/support.go#L192)):*
> ```Go
> 	if err != nil {
> 		if exitErr := (*exec.ExitError)(nil); errors.As(err, &exitErr) {
> 			log.Infof(context.Background(), "%s", string(exitErr.Stderr))
> ```

Great to see unified logging!
___
*[pkg/roachprod/vm/gce/gcloud.go, line 173 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7AuB0KQlyM3EW5Jg:-MnW7AuB0KQlyM3EW5Jh:brp46qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/gce/gcloud.go#L173)):*
> ```Go
> }
> 
> // DefaultProviderOpts TODO
> ```

TODO \o/
___
*[pkg/roachprod/vm/gce/gcloud.go, line 276 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7FN85_ODXosJBHiy:-MnW7FN85_ODXosJBHiz:bse0ip0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/gce/gcloud.go#L276)):*
> ```Go
> }
> 
> // ConfigureCreateFlags TODO
> ```

TODO :)
___
*[pkg/roachprod/vm/gce/gcloud.go, line 309 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7H5_8PnlfNUcLI6m:-MnW7H5_8PnlfNUcLI6n:bse0ip0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/gce/gcloud.go#L309)):*
> ```Go
> }
> 
> // ConfigureClusterFlags TODO
> ```

TODO :)

**Review by healthy-pod — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71660)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod and @rail)

___
*[pkg/roachprod/vm/azure/flags.go, line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW73qF73vIphWhvxBr:-MnWd6-K5Skuk0sLnBZA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/azure/flags.go#L23)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

TODO please :)
</blockquote></details>

Done.
___
*[pkg/roachprod/vm/azure/flags.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW76-A2FxNZ9cQCw4x:-MnWd9T2ALCzAafJ2VhU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/azure/flags.go#L45)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

And here :)
</blockquote></details>

Done.
___
*[pkg/testutils/lint/lint_test.go, line 807 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7MZl2K7fiU0BXx46:-MnWj8BSDO4_71fsO6KO:b-1dgrne) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/testutils/lint/lint_test.go#L807)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Can you file a GitHub issue and specify it here please.
</blockquote></details>

Done.
https://github.com/cockroachdb/cockroach/issues/72328
___
*[pkg/testutils/lint/lint_test.go, line 1521 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7T4G1G8S48cSAY7r:-MnWj-fG5eD9F_hC_wpV:b-aaq2x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/testutils/lint/lint_test.go#L1521)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

The same here.
</blockquote></details>

Done. 
https://github.com/cockroachdb/cockroach/issues/72329
___
*[pkg/roachprod/install/cluster_synced.go, line 1197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW5qWpAFXMyg6NLAmj:-MnWcI-N7TlTiEDWtoSs:bbxvti7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/install/cluster_synced.go#L1197)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

> ```
> clog
> ```
A nit: is there any reason to use `clog` instead of `log`? I see `log` in other files.
</blockquote></details>

Absolutely no reason, done!
___
*[pkg/roachprod/install/cockroach.go, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW62Jr0c14nVxJIhQv:-MnWcRaB8f3uybc8xV0D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/install/cockroach.go#L38)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

> ```
> TODO
> ```
Can you fill the place holder ;)
</blockquote></details>

Done.
___
*[pkg/roachprod/vm/vm.go, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW6ER97g0Rm2IkFt8d:-MnWc_Hq5eTNuafGGa2u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/vm.go#L156)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Can you address the TODO. :)
BTW, it's so great to have all values in one structure - so much easier to read! :100: 
</blockquote></details>

Done.
___
*[pkg/roachprod/vm/aws/aws.go, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW6gasDRumt1RuN2tg:-MnWceryCPN8NVbikog9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/aws/aws.go#L188)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Love the centralized structure! Can you address the TODO please :)
</blockquote></details>

Done.
___
*[pkg/roachprod/vm/gce/gcloud.go, line 173 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7AuB0KQlyM3EW5Jg:-MnWdHXo6F07uL7Qi1w3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/gce/gcloud.go#L173)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

TODO \o/
</blockquote></details>

Done.
___
*[pkg/roachprod/vm/gce/gcloud.go, line 276 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7FN85_ODXosJBHiy:-MnWdH6b3XVaRv7N0QcZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/gce/gcloud.go#L276)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

TODO :)
</blockquote></details>

Done.
___
*[pkg/roachprod/vm/gce/gcloud.go, line 309 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-MnW7H5_8PnlfNUcLI6m:-MnWdGnU9dNufA9m0ihk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d44eb1502cbb261764711d9fae459214aebd6e4/pkg/roachprod/vm/gce/gcloud.go#L309)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

TODO :)
</blockquote></details>

Done.

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71660#-:-MnWqDgy3q7CSufcjP-3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @healthy-pod and @rail)

**Comment by healthy-pod** [comment]
bors r=rail

**Pull request merged**
