### PR TITLE
storage: Avoid transferring leases to draining stores

### PR DESCRIPTION
**Pull request by a-robinson**
I'm really hoping what I'm seeing was just an aberration, but as far as
I can tell the Allocator contains no logic to avoid transferring leases
to a draining store. What have we been thinking was stopping leases from
transferring back?

In local testing with verbose logging enabled, I was seeing leases
transfer back (or at least say that they were being transferred back)
to a draining store before it shut down, which was sometimes causing
brief (e.g. 3s) QPS outages.

Release note (bug fix): Avoid disruptions in performance when gracefully
shutting a node down.

Also, assuming I'm not making this problem up, are there any existing tests of draining that this could be reasonably added on to?

### CODE REVIEW

**Comment by a-robinson** [comment]
For more context, I ran into this by debugging why I could still reproduce #22573 on master even after the handful of fixes that have gone in recently.

Without this fix, I see the following ycsb output:

```
  1m39s        100.2          96 / 0 / 0           4 / 0           0 / 0
  1m40s         99.9          95 / 0 / 0           5 / 0           0 / 0
  1m41s         36.1          33 / 0 / 0           3 / 0           0 / 0
  1m42s          0.0           0 / 0 / 0           0 / 0           0 / 0
  1m43s          0.0           0 / 0 / 0           0 / 0           0 / 0
  1m44s          0.0           0 / 0 / 0           0 / 0           0 / 0
  1m45s          0.0           0 / 0 / 0           0 / 0           0 / 0
  1m46s          0.0           0 / 0 / 0           0 / 0           0 / 0
  1m47s         22.1          21 / 0 / 0           1 / 0           0 / 0
  1m48s        100.1          96 / 0 / 0           4 / 0           0 / 0
```

With the fix, I see no QPS dip at all, as expected from a graceful shutdown process.

**Comment by petermattis** [comment]
I looked around `TransferLeaseTarget` and couldn't see where draining nodes were being excluded either. I could have missed it though. Did you verify via additional log messages that we're actually transferring leases to draining messages? 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replicate_queue.go, line 534 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265#-L6WjoRlM5o7w42qKxIq:-L6WjoRlM5o7w42qKxIr:bd6u83z) ([raw file](https://github.com/cockroachdb/cockroach/blob/433ebdd6c2e412e8423a6182c30d197d4cfe2597/pkg/storage/replicate_queue.go#L534)):*
> ```Go
> 	// Filter out behind and non-live replicas.
> 	candidates := filterBehindReplicas(repl.RaftStatus(), desc.Replicas, 0 /* brandNewReplicaID */)
> 	candidates, _ = rq.allocator.storePool.liveAndDeadReplicas(desc.RangeID, candidates)
> ```

Feels like this should be baked into `TransferLeaseTarget` which would make adding a test easier. 

Btw, some of the comments in `TransferLeaseTarget` refer to rebalancing and seem inaccurate. Am I misunderstanding something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265#-:-L6Wl2FmT5lwnx-xPmyI:b-stgbn9)*

**Comment by a-robinson** [comment]
I didn't directly verify that the lease transfers happened, but the logs on both sides certainly indicated that they did. I verified that other nodes were trying to transfer leases to the draining store (`[replicate,n2,s2,r3/8:/System/NodeLiveness{-Max}] transferring lease to s4`) and that the draining store had the leases back for some ranges that it had previously transferred away, as indicated by `[replicate,n4,s4,r3/7:/System/NodeLiveness{-Max}] no rebalance target found, not enqueuing` messages that would instead say `needs lease; not adding` if the store didn't own the lease.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replicate_queue.go, line 534 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265#-L6WjoRlM5o7w42qKxIq:-L6X9KcPItxpLEEQkXz2:b1jca3) ([raw file](https://github.com/cockroachdb/cockroach/blob/433ebdd6c2e412e8423a6182c30d197d4cfe2597/pkg/storage/replicate_queue.go#L534)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Feels like this should be baked into `TransferLeaseTarget` which would make adding a test easier. 

Btw, some of the comments in `TransferLeaseTarget` refer to rebalancing and seem inaccurate. Am I misunderstanding something?
</blockquote></details>

I was concerned about that breaking existing tests, but it looks like that concern may have been overblown since I just tried it out without anything breaking. There's also the fact that we do filtering of replicas that are behind the leader out here rather than in `TransferLeaseTarget`, but you're right that it'll be easier to test with it in `TransferLeaseTarget`.

The comment on the `filteredDescs` logic right below here looks like it's meant for rebalancing, and even the code is of questionable value. I don't see anything else though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265#-:-L6X7ot38StPGqyXLA0z:b-o2viex)*

**Comment by asubiotto** [comment]
https://github.com/cockroachdb/cockroach/pull/11724 was supposed to add this functionality but the scope of the tests was wrong (limited to store pool). Thanks for finding this.

**Comment by a-robinson** [comment]
Thanks for the context, @asubiotto, that's what I needed to see. I guess this is the "future work" referenced there, although it isn't rejecting transfers on the draining node so much as hoping that gossip updates quickly enough to keep other stores from trying to transfer.

I'll put a new test together.

**Comment by asubiotto** [comment]
This PR is the actual work that #11724 was supposed to do. You're right that we still expect our liveness to update in time before the lease transfers away from the node happen. The future work referenced there is to solve that race condition (not sure how feasible that is since a lease transfer is a raft command), however, we could add a gossip propagation wait like we do in https://github.com/cockroachdb/cockroach/blob/d79f836047f4b761855168c488a9d04691b0627f/pkg/sql/distsqlrun/server.go#L215

**Comment by a-robinson** [comment]
Tests added (along with another very minor logic change to make the tests make more sense). PTAL.

I plan to cherry-pick this to both 1.1 and 2.0 if that's ok with you guys.

**Comment by asubiotto** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator_test.go, line 1198 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265#-L6YCRNgqBm3Gj69HfSk:-L6YCRNgqBm3Gj69HfSl:bfrfb8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc3546cea89f85855dba88ffb4f938197cb5438/pkg/storage/allocator_test.go#L1198)):*
> ```Go
> 
> 	// UNAVAILABLE is the node liveness status used for a node that's draining.
> 	nl.setNodeStatus(1, NodeLivenessStatus_UNAVAILABLE)
> ```

Is there a way to get this programmatically? e.g. make a dummy node liveness with draining set and call `LivenessStatus` on it? Might be unlikely that this status changes though and not worth it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265#-:-L6YDOxHVdeLeicOf9fT:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/allocator_test.go, line 1198 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265#-L6YCRNgqBm3Gj69HfSk:-L6YJR20lWl7J20h6Wxo:b11mbjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc3546cea89f85855dba88ffb4f938197cb5438/pkg/storage/allocator_test.go#L1198)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there a way to get this programmatically? e.g. make a dummy node liveness with draining set and call `LivenessStatus` on it? Might be unlikely that this status changes though and not worth it.
</blockquote></details>

Not without encoding a bunch of knowledge about how `Liveness.LivenessStatus` works into the code to populate a dummy `Liveness` object. Otherwise we wouldn't even make it to the `Draining` check in `Liveness.LivenessStatus`. And that sounds even less maintainable than this.

I agree with your point, but think that improving this is more trouble than it's worth.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23265)*

**Pull request merged**
