### PR TITLE
sql/sem/builtins: deflake TestSerialNormalizationWithUniqueUnorderedID

### LINKED ISSUE #107899: sql/sem/builtins: TestSerialNormalizationWithUniqueUnorderedID failed
sql/sem/builtins.TestSerialNormalizationWithUniqueUnorderedID [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11128415?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11128415?buildTab=artifacts#/) on master @ [45cd1c943d853c7701b782122bccbb7a62f1af5b](https://github.com/cockroachdb/cockroach/commits/45cd1c943d853c7701b782122bccbb7a62f1af5b):

```
    builtins_test.go:178: range 5: 12749
    builtins_test.go:178: range 6: 12838
    builtins_test.go:178: range 7: 12506
    test_server_shim.go:98: 
        Test server was configured to route SQL queries to a secondary tenant (virtual cluster).
        If you are only seeing a test failure when this message appears, there may be a problem
        specific to cluster virtualization or multi-tenancy.
        
        To investigate, consider using "COCKROACH_TEST_TENANT=true" to force-enable just
        the secondary tenant in all runs (or, alternatively, "false" to force-disable), or use
        "COCKROACH_INTERNAL_DISABLE_METAMORPHIC_TESTING=false" to disable all random test variables altogether.
*
* WARNING: test tenant requested by configuration, but code organization prevents start!
* OSS binaries do not include enterprise features
*
    builtins_test.go:176: Key counts in each split range
    builtins_test.go:178: range 0: 12458
    builtins_test.go:178: range 1: 12818
    builtins_test.go:178: range 2: 12788
    builtins_test.go:178: range 3: 12790
    builtins_test.go:178: range 4: 12296
    builtins_test.go:178: range 5: 12379
    builtins_test.go:178: range 6: 12281
    builtins_test.go:178: range 7: 12190
    builtins_test.go:200: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins_test.go:200
        	Error:      	Received unexpected error:
        	            	chiSquared value of 37.620000 must be less than criticalVal 35.258500 to guarantee distribution is relatively uniform
        	            	(1) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.TestSerialNormalizationWithUniqueUnorderedID.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins_test.go:194
        	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.WithMaxAttempts.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:195
        	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.Options.Do
        	            	  | 	github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:172
        	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.WithMaxAttempts
        	            	  | 	github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:194
        	            	  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.TestSerialNormalizationWithUniqueUnorderedID
        	            	  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins_test.go:112
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1446
        	            	  | runtime.goexit
        	            	  | 	GOROOT/src/runtime/asm_amd64.s:1594
        	            	Wraps: (2) chiSquared value of 37.620000 must be less than criticalVal 35.258500 to guarantee distribution is relatively uniform
        	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
        	Test:       	TestSerialNormalizationWithUniqueUnorderedID
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ad72371e92981b2b572c54a0422f4d25/logTestSerialNormalizationWithUniqueUnorderedID3541869364
--- FAIL: TestSerialNormalizationWithUniqueUnorderedID (78.73s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSerialNormalizationWithUniqueUnorderedID.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30250

### PR DESCRIPTION
**Pull request by andyyang890**
This patch increases the number of retries for this test to 3 and increases the number of rows inserted to an even larger number to hopefully reduce the number of flakes.

Fixes #107899

Release note: None

### CODE REVIEW

**Review by chrisseto — COMMENTED** [review]
Could you provide a bit more context in the commit message about why these changes could help reduce flakes? If I understand correctly, it seems like you're just increasing the sample sizes as that's more likely to result in a uniform distribution. Though I see some changes to the calculation of ChiSquared that I don't fully understand as well.

**Review by andyyang890 — COMMENTED** [review]
Thanks for your comments!

I decided to change it so we run the test multiple times and fail due to non-uniformity only if a majority of the runs fail due to non-uniformity. I also changed it to stop using `retry.WithMaxAttempts` since we still want any unrelated errors to fail the test.

The sample size change is mostly so that each bucket should have an even 10000 (instead of 12500) expected values, making it a bit easier to eyeball when we look at the logs.

I updated the commit message too, hope it's more clear now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108069#-:-NawZYMm0dVfB2BncNME:biziizi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @rafiss)

___
*[`pkg/sql/sem/builtins/builtins_test.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108069#gh-1283301346:-Naw_UaK7dqv6L0BPuAK:bliul10) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb6b57896228ce3449492d05afa139eac104ccd/pkg/sql/sem/builtins/builtins_test.go#L101)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

nit: can you quantify "large number" here with a lower bound or rough order of magnitude? 
```suggestion
// normalization can use unique_unordered_id() and a large number (>= 100000000000000000) of
```
</blockquote></details>

Added the actual number of insertions

**Review by andyyang890 — COMMENTED** [review]
Oh also, the chi-squared calculation changes is just a pure refactor to match the textbook formula (from the link in the function doc comment) so that it's easier to read.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108069#-:-Nawb4t4DcdP8UJzivnC:b-58rvm7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @rafiss)

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108069)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @chrisseto)

___
*[`pkg/sql/sem/builtins/builtins_test.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108069#-NayfXXe5PXWDT7XVn-e:-NayfXXe5PXWDT7XVn-f:b-yf8kad) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbcd656a2936e25f10643d8a27285542537b534c/pkg/sql/sem/builtins/builtins_test.go#L113)):*
> ```Go
> 	// is not in and of itself a huge concern. As such, we'll only fail the test if
> 	// a majority of our observations show statistically significant amounts of
> 	// non-uniformity.
> ```

relevant xkcd: https://xkcd.com/882/

but kidding aside, i actually do think this approach is fine since the important thing about this function is that it's unordered, not that it's statistically random. (the unordered-ness is important for the purpose of not generating sequential values for a primary index)

**Comment by andyyang890** [comment]
> relevant xkcd: https://xkcd.com/882/

heh 😄 

TFTR!

bors r=rafiss

**Pull request merged**
