### PR TITLE
sql,storage: some preliminary changes for KV projection pushdown

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR contains a couple of commits that are mostly mechanical changes in preparation of the KV pushdown work. Some microbenchmarks of this PR are [here](https://gist.github.com/yuzefovich/24d3238bc638cc1121fd345c68ca3d0b), and they show effectively no change in the scan speed.

Epic: CRDB-14837

Informs: #82323
Informs: #87610

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/colfetcher/cfetcher.go` line 522 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94348#-NKW5IMa3VH1BJgY6Vkk:-NKW5IMa3VH1BJgY6Vkl:bmz7ntr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de4021d5853d363776f14da86241c3470cfe481/pkg/sql/colfetcher/cfetcher.go#L522)):*
> ```Go
> 	cf.machine.state[0] = stateResetBatch
> 	cf.machine.state[1] = stateInitFetch
> 	return cf.fetcher.SetupNextFetch(
> ```

Should we handle the case where fetcher is nil?
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 748 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94348#-NKW9fM5BEqV5IZBDXZS:-NKW9fM5BEqV5IZBDXZT:b-o3soxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/92bab27d48a8637ab3e6d55e5eb8cbd689228b53/pkg/sql/row/kv_batch_fetcher.go#L748)):*
> ```Go
> // implementing some methods of the KVBatchFetcher interface related to
> // observability.
> type kvBatchFetcherO11yHelper struct {
> ```

What's up with the `011y`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/colfetcher/cfetcher.go` line 522 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94348#-NKW5IMa3VH1BJgY6Vkk:-NKtD4zh8uIeAr6BBdAR:b-engqjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de4021d5853d363776f14da86241c3470cfe481/pkg/sql/colfetcher/cfetcher.go#L522)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should we handle the case where fetcher is nil?
</blockquote></details>

This is not needed since we only call `SetupNextFetch` when running the flow if `Init` calls succeeded for all operators in the flow. We introduced the non-nil checks for observability-related methods because they are called at the end and can be called even if `Init` failed for some operators, which could leave some of the operators uninitialized.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 748 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94348#-NKW9fM5BEqV5IZBDXZS:-NKtDn8qD_PqyFQyK47E:bd8bf2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/92bab27d48a8637ab3e6d55e5eb8cbd689228b53/pkg/sql/row/kv_batch_fetcher.go#L748)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What's up with the `011y`?
</blockquote></details>

Short for `observability` :) Removed that from the struct name.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94348#-:-NKu-O6n3oL3-JpZQXa9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/row/kv_batch_fetcher.go` line 748 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94348#-NKW9fM5BEqV5IZBDXZS:-NKu-5Wr7KEl6HIgOPP9:bvkcm8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/92bab27d48a8637ab3e6d55e5eb8cbd689228b53/pkg/sql/row/kv_batch_fetcher.go#L748)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Short for `observability` :) Removed that from the struct name.
</blockquote></details>

Huh, hadn't heard that one before.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
