### PR TITLE
Remove Event Feed

### LINKED ISSUE #1531: storage: TestMultiStoreEventFeed counts wrong
The following test appears to have failed:

[#4214](https://circleci.com/gh/cockroachdb/cockroach/4214):

```
I0628 14:50:12.923111     322 range_command.go:837] initiating a split of range=2 ["b" - "\xff\xff") at key "z"
I0628 14:50:12.946720     322 range_command.go:1014] initiating a merge of range=3 ["z" - "\xff\xff") into range=2 ["b" - "z")
I0628 14:50:13.213604     322 multiraft.go:509] node 300000003: got message for unknown group 3; creating it
I0628 14:50:13.214234     322 multiraft.go:509] node 200000002: got message for unknown group 3; creating it
I0628 14:50:13.218772     322 range_command.go:774] range 3: new leader lease replica 1:1 00:00:00.000 +1.000s
--- FAIL: TestMultiStoreEventFeed-2 (0.74s)
	client_event_test.go:343: update counts did not match expected value. Actual values have been printed to compare with above expectation.
	client_event_test.go:344: Update count information:
		proto.StoreID(1): {
		  proto.Put:                  18,
		  proto.ConditionalPut:       7,
		  proto.Increment:            2,
		  proto.Delete:               2,
		  proto.EndTransaction:       6,
		  proto.InternalLeaderLease:  3,
		},
--
E0628 14:50:17.896658     322 queue.go:266] failure processing range range=2 ["b" - "\xff\xff") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
E0628 14:50:17.906982     322 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
--- PASS: TestStoreStatus-2 (0.09s)
=== RUN: ExampleAllocatorRebalancing
--- PASS: ExampleAllocatorRebalancing (0.08s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	6.610s
=== RUN TestBatchBasics-2
I0628 14:50:52.185678     445 rocksdb.go:88] opening in-memory rocksdb instance
I0628 14:50:52.186418     445 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics-2 (0.00s)
=== RUN TestBatchGet-2
I0628 14:50:52.187233     445 rocksdb.go:88] opening in-memory rocksdb instance
I0628 14:50:52.187412     445 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet-2 (0.00s)
=== RUN TestBatchMerge-2
I0628 14:50:52.188095     445 rocksdb.go:88] opening in-memory rocksdb instance
PASS
ok  	github.com/cockroachdb/cockroach/kv	24.871s
=== RUN TestHeartbeatSingleGroup-2
--- PASS: TestHeartbeatSingleGroup-2 (0.39s)
=== RUN TestHeartbeatMultipleGroupsJointLeader-2
panic: test timed out after 5m0s

goroutine 508 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 2 minutes]:
testing.RunTests(0xb65148, 0xd06b60, 0xa, 0xa, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/multiraft/storage.go:145 +0xb9b
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0x133
FAIL	github.com/cockroachdb/cockroach/multiraft	300.030s
=== RUN TestMemoryStorage-2
--- PASS: TestMemoryStorage-2 (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/multiraft/storagetest	0.041s
=== RUN TestClientCmdIDIsEmpty-2
--- PASS: TestClientCmdIDIsEmpty-2 (0.00s)
=== RUN TestResponseHeaderSetGoError-2
--- PASS: TestResponseHeaderSetGoError-2 (0.00s)
=== RUN TestResponseHeaderNilError-2
--- PASS: TestResponseHeaderNilError-2 (0.00s)

```
Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #4021: util: Deprecate Event Feeds, record metrics directly
Early in the development of Cockroach's metrics recording systems, we created an "Event Feed" which was meant to broadcast information about certain events through the cockroach system; events such as range splits, replica movement, completed RPCs, etc.  There were three assumptions made when this was developed:

1. We needed to hide details of metrics recording from low-level systems; the feed was a basic class that could live at the bottom of the dependency stack, and allow low-level systems to feed information to high-level systems (i.e. metrics collection).
2. We did not assume that metrics would be the only usage for these events; we thought it might prove to be a general-purpose way for internal cockroach systems to monitor other systems.
3. I chose to make this system asynchronous, thinking that concerns related to monitoring should not place a direct performance hit on critical systems.

None of these assumptions holds true anymore:
* Metrics registries can now serve the function of hiding details from a low-level system; low level systems interact with a simple metric objects, which can easily be manage by the higher-level metric recording system.
* There have been no other systems attempting to consume the event feed since its creation. In addition, we are now beginning to record important event information into persistent log-structured SQL tables.
* Finally, the feed has already been made synchronous; the asynchronous feed caused numerous bugs that were not worth the trouble.

Because of this, the Feed system should be deprecated; it is needlessly complicating our metrics collection system at this time.

### PR DESCRIPTION
**Pull request by mrtracy**
This commit removes the Event Feed from all cockroach systems. The feed was
previously being used to decouple the metric status system from lower-level
systems; however, `metric.Registry` has recently been created to perform that
task better. The new system is far more streamlined and easier to understand.

In the new factoring, each component in the server (e.g. `Store`, `SqlExecutor`)
creates a metric.Registry and directly adds metric counters to it. Each
component exposes this registry through the `Registry()` method. The server is
responsible for instantiating a `MetricsRecorder` object, and giving the
recorder a reference to all component registries. The recorder is responsible
for converting the metrics in each registry into time series data, status
  summaries or JSON output.

There is a bit of "ugly" code present in the recorder to continue supporting the
current structure of the StoreStatusSummary object. However, #4465 has been
logged (and mentioned in several TODOs) to tackle that issue in the short term.

Closes #4021
Closes #1531 (by removing the need for the test)

Opened #4583 to add additional testing in the short term.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4584)

### CODE REVIEW

**Comment by tamird** [comment]
Science dog on most of this, someone else should take a look.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[server/node.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAWSNPiwSwNIS51AZ5:-KBAWSNQL1I-Dch2zn_d:-2019541756) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/node.go#L534)):*
does the loop only trigger publishing or does it also trigger calculation? i ask because the word "periodically" appears twice.

---

*[server/status/recorder.go, line 85 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAWwAKde-EuBlMNvFc:-KBAWwAKde-EuBlMNvFd:368483270) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L85)):*
make an anonymous struct:
```
struct mu {
 sync.Mutex
 fieldsProtectedByMutex...
}
```

---

*[server/status/recorder.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAZwyD4P6kBw7H9Qfm:-KBAZwyD4P6kBw7H9Qfn:140394890) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L125)):*
remove this comma

---

*[server/status/recorder.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBA_7Rof7Lp-2aLdz6F:-KBA_7Rof7Lp-2aLdz6G:-714432608) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L154)):*
that's not an empty byte string, it's an empty json object.

---

*[server/status/recorder.go, line 193 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBA_QkV6_i0TSHJ8g2-:-KBA_QkV6_i0TSHJ8g20:-1393024112) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L193)):*
nit: strconv.Itoa avoids the cast

---

*[server/status/recorder.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBA_qI7Jl85ZzdRYzIM:-KBA_qI7Jl85ZzdRYzIN:-234941509) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L309)):*
can you put a comment here? i can't tell that `prefix` is a format string

---

*[storage/store.go, line 385 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAaAYdWEHOMzPwUE_E:-KBAaAYdWEHOMzPwUE_F:-19325394) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/storage/store.go#L385)):*
s/below/above/?

---

*[util/metric/metric.go, line 247 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAUkUn-OJUuJeeZfPf:-KBAUkUoLuwJUoGsBPcP:677713193) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/util/metric/metric.go#L247)):*
huh?

---

*[util/metric/registry_test.go, line 71 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAV8RQAEel6T8lr6F9:-KBAV8RQAEel6T8lr6FA:1636531087) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/util/metric/registry_test.go#L71)):*
the cases that expect nil and get non-nil should probably include the non-nil value in the error message. the case that expect non-nil should probably have a slightly stronger assertion that the right value is returned (is that possible?).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-:-KBAaKtCY7blpaRUfwgG:-786036987)*

**Comment by tschottdorf** [comment]
I'll wait for my review until the rebase. Appreciate a ping when that's happened.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-:-KBAkXhaej947UXl-Imx:-523593153)*

**Comment by mrtracy** [comment]
Review status: 12 of 22 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/node.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAWSNPiwSwNIS51AZ5:-KBEFPylPIePZigCuTWl:579034668) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/node.go#L534)):*
It triggers the calculation, although it's not really "publishing" anymore. I have a TODO here to refactor the name of the method.

---

*[server/status/recorder.go, line 85 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAWwAKde-EuBlMNvFc:-KBEFaXg_fl6oRFZOIWJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L85)):*
Done.

---

*[server/status/recorder.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAZwyD4P6kBw7H9Qfm:-KBEHL6jwdylU7YGTYhr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L125)):*
Done.

---

*[server/status/recorder.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBA_7Rof7Lp-2aLdz6F:-KBEHSeS6sjMY-eR2iou:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L154)):*
Done.

---

*[server/status/recorder.go, line 193 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBA_QkV6_i0TSHJ8g2-:-KBEHfjaaZpH58fvfOdk:1338331781) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L193)):*
nodeID is a RangeID, how would that work?

---

*[server/status/recorder.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBA_qI7Jl85ZzdRYzIM:-KBEI1BdQPPLhGYYPQfn:-91955757) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L309)):*
s/prefix/format

---

*[util/metric/metric.go, line 247 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAUkUn-OJUuJeeZfPf:-KBETSY9NSMhvGzh-vec:1030135486) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/util/metric/metric.go#L247)):*
the function, f. Every other metric struct's "Each()" implementation passes itself to the closure (visitor pattern), whereas Rate for some reason passes the closure its int64 value. This is inconsistent.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Comment by mrtracy** [comment]
Rebase from Cuong's PR is complete

---

Review status: 12 of 22 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-:-KBEmAs673n_j_MNrFhG:787535982)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/node.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAWSNPiwSwNIS51AZ5:-KBEouvbqtrg8aqsD5yV:-1354234574) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/node.go#L534)):*
OK, but I was just asking about the comment. Is it correct that "periodically" appears twice?

---

*[server/status/recorder.go, line 193 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBA_QkV6_i0TSHJ8g2-:-KBEp9r0F-8oOSf4iU_u:1470311337) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/status/recorder.go#L193)):*
oh, duh.

---

*[util/metric/metric.go, line 247 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAUkUn-OJUuJeeZfPf:-KBEpL22nb0e-J8qEGdH:908143248) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/util/metric/metric.go#L247)):*
right, ok. I was mostly confused at the mention of float64 when the function signature is `(string, interface{})`. Expand this TODO so that it can make sense to other readers.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Comment by mrtracy** [comment]
Review status: 18 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/node.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAWSNPiwSwNIS51AZ5:-KBEtA-SrS4VOXTA1Hia:1758359711) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/server/node.go#L534)):*
Fixed.

---

*[storage/store.go, line 385 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAaAYdWEHOMzPwUE_E:-KBErYtlfUOdRAVGCDT_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/storage/store.go#L385)):*
Done.

---

*[util/metric/metric.go, line 247 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAUkUn-OJUuJeeZfPf:-KBEs4ulk-6fEf4mWcHk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/util/metric/metric.go#L247)):*
Done.

---

*[util/metric/registry_test.go, line 71 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBAV8RQAEel6T8lr6F9:-KBErYGeV8FrhQ1TSySW:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/316ef65170f9b40b131616634b127abd1cd569a7/util/metric/registry_test.go#L71)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store.go, line 652 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBEvdADwfMuh2YBgEF8:-KBEvdADwfMuh2YBgEF9:-2060226583) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/storage/store.go#L652)):*
This also needs to add the stats for the range into the MVCCStats.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 22 files at r1, 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/node.go, line 539 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBFT1FmMd67_S0gfAII:-KBFT1FmMd67_S0gfAIJ:2139397888) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/node.go#L539)):*
You can't just `startPublishMetrics`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Comment by tschottdorf** [comment]
LGTM. Some minor comments, but looks good.

---

Reviewed 10 of 22 files at r1, 7 of 10 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/status/recorder.go, line 76 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGDVimEQxmZE2jRCUM:-KBGDVimEQxmZE2jRCUN:42129275) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/status/recorder.go#L76)):*
nit: reflow

---

*[server/status/recorder.go, line 161 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGEJZWHuXPGz_28NWU:-KBGEJZWHuXPGz_28NWV:1983553639) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/status/recorder.go#L161)):*
nit: no punctuation (?)

---

*[server/testserver.go, line 327 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGFX0kQKxTEGAQzk51:-KBGFX0kQKxTEGAQzk52:-1176700799) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/testserver.go#L327)):*
nit: `PGWire`?

---

*[storage/store.go, line 652 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBEvdADwfMuh2YBgEF8:-KBGG-2jeLamNszFx10S:111011531) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/storage/store.go#L652)):*
is this a reminder for yourself?

---

*[util/metric/metric.go, line 264 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGGDPYDYGKar97hj1M:-KBGGDPYDYGKar97hj1N:-781325223) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/util/metric/metric.go#L264)):*
could this be a quick fix as well? nit: double space.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-:-KBGGRBv3Oumv0_TThXI:-2021661422)*

**Comment by mrtracy** [comment]
Review status: 14 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/node.go, line 539 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBFT1FmMd67_S0gfAII:-KBJPLYT1f3lTTjAu2CS:-896747630) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/node.go#L539)):*
I went ahead and renamed this to `startComputePeriodicMetrics`, which is an accurate description.

---

*[server/status/recorder.go, line 76 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGDVimEQxmZE2jRCUM:-KBJPm_j0M7le9fZB6ac:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/status/recorder.go#L76)):*
Done.

---

*[server/status/recorder.go, line 161 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGEJZWHuXPGz_28NWU:-KBJQB6_amX2GhNwIfPw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/status/recorder.go#L161)):*
Done.

---

*[server/testserver.go, line 327 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGFX0kQKxTEGAQzk51:-KBJQLdPRu86fGVYBBoR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/server/testserver.go#L327)):*
Done.

---

*[storage/store.go, line 652 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBEvdADwfMuh2YBgEF8:-KBJ8PrFqOaHTQwzlfS-:1896913244) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/storage/store.go#L652)):*
Yes, I had a coding interview at 4 and then our meeting.

---

*[util/metric/metric.go, line 264 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBGGDPYDYGKar97hj1M:-KBJRE4yfBHvsMEpRGDV:1108458301) ([raw file](https://github.com/cockroachdb/cockroach/blob/014427a1519d7cb95cf036b2c014bdd417daebe4/util/metric/metric.go#L264)):*
I'll get it when i'm doing the StatusSummary overhaul.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Comment by tamird** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/node.go, line 559 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584#-KBJdrtL-Vplpr-X-LXn:-KBJdrtMmrnKo8eNtBi9:-574044656) ([raw file](https://github.com/cockroachdb/cockroach/blob/339a02d204ed8f4daf4dc59fc6c1bd9ad6f9df2c/server/node.go#L559)):*
s/complicated/the explanation you have above about not being incrementally computable/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4584)*

**Pull request merged**
