### PR TITLE
opt: fix greedy lookup join constraints

### LINKED ISSUE #75596: opt: do not greedily collect as many lookup join key columns as possible
When generating lookup joins, the optimizer greedily collects as many key columns as possible. This does not generate optimal lookup joins in all cases. For example:

```
exec-ddl
CREATE TABLE ab (
    a INT PRIMARY KEY,
    b INT NOT NULL,
    INDEX (b)
);
----

exec-ddl
CREATE TABLE cd (
    c INT NOT NULL,
    d INT NOT NULL,
    c_shard INT NOT NULL,
    PRIMARY KEY (c_shard, c),
    INDEX d_idx (d),
    CHECK (c_shard IN (0, 1, 2))
);
----

opt
SELECT * FROM ab INNER LOOKUP JOIN cd ON ab.a = cd.d AND ab.b = 1
----
inner-join (lookup cd@d_idx)
 ├── columns: a:1!null b:2!null c:5!null d:6!null c_shard:7!null
 ├── flags: force lookup join (into right side)
 ├── key columns: [1 11] = [6 7]
 ├── key: (5,7)
 ├── fd: ()-->(2), (5,7)-->(6), (1)==(6), (6)==(1)
 ├── inner-join (cross)
 │    ├── columns: a:1!null b:2!null "lookup_join_const_col_@7":11!null
 │    ├── multiplicity: left-rows(one-or-more), right-rows(zero-or-more)
 │    ├── fd: ()-->(2)
 │    ├── scan ab@ab_b_idx
 │    │    ├── columns: a:1!null b:2!null
 │    │    ├── constraint: /2/1: [/1 - /1]
 │    │    ├── key: (1)
 │    │    └── fd: ()-->(2)
 │    ├── values
 │    │    ├── columns: "lookup_join_const_col_@7":11!null
 │    │    ├── cardinality: [3 - 3]
 │    │    ├── (0,)
 │    │    ├── (1,)
 │    │    └── (2,)
 │    └── filters (true)
 └── filters (true)
```

The optimizer is able to add `c_shard:7` as a key column in the lookup join by using the check constraint filter. The join's input is crossed joined with the 3 possible values of `c_shard`. Filtering `c_shard` by all possible values has no affect on the selectivity of the join, and it triples the number of lookups that need to be performed. A better plan for this query would be:

```
inner-join (lookup cd@d_idx)
 ├── columns: a:1!null b:2!null c:5!null d:6!null c_shard:7!null
 ├── flags: force lookup join (into right side)
 ├── key columns: [1] = [6]
 ├── key: (5,7)
 ├── fd: ()-->(2), (5,7)-->(6), (1)==(6), (6)==(1)
 │    └── scan ab@ab_b_idx
 │         ├── columns: a:1!null b:2!null
 │         ├── constraint: /2/1: [/1 - /1]
 │         ├── key: (1)
 │         └── fd: ()-->(2)
 └── filters (true)
```

I'm not sure what the best solution is, but here are some ideas:

1. Some heuristic along the lines of "don't use a column as a key column if it's the last key column and it is constrained by a check constraint".
2. Generate a lookup join for each possible prefix of key columns of the index, and let the best cost lookup join win. This may better handle cases where a heuristic is lacking. For example:

```
exec-ddl
CREATE TABLE a (
    a INT PRIMARY KEY
);
----

exec-ddl
CREATE TABLE bcde (
    b INT PRIMARY KEY,
    c INT,
    d INT,
    e INT,
    INDEX (c, d)
);
----

opt
SELECT a, b FROM a INNER LOOKUP JOIN bcde ON a = c AND d IN (1, 2, 3)
----
project
 ├── columns: a:1!null b:4!null
 ├── key: (4)
 ├── fd: (4)-->(1)
 └── inner-join (lookup bcde@bcde_c_d_idx)
      ├── columns: a:1!null b:4!null c:5!null d:6!null
      ├── flags: force lookup join (into right side)
      ├── key columns: [1 10] = [5 6]
      ├── key: (4)
      ├── fd: (4)-->(5,6), (1)==(5), (5)==(1)
      ├── inner-join (cross)
      │    ├── columns: a:1!null "lookup_join_const_col_@6":10!null
      │    ├── multiplicity: left-rows(one-or-more), right-rows(zero-or-more)
      │    ├── scan a
      │    │    ├── columns: a:1!null
      │    │    └── key: (1)
      │    ├── values
      │    │    ├── columns: "lookup_join_const_col_@6":10!null
      │    │    ├── cardinality: [3 - 3]
      │    │    ├── (1,)
      │    │    ├── (2,)
      │    │    └── (3,)
      │    └── filters (true)
      └── filters (true)
```

Including `d:6` as a key column in the lookup join is beneficial if `d IN (1, 2, 3)` is highly selective, whereas omitting `d:6` from the key columns and eliminating the cross-join is beneficial if `d IN (1, 2, 3)` is not very selective. Note that we'd have to have accurate statistics for the selectivity of these joins in order to pick the best join, and I'm not sure the statistics we currently derive for these joins from the base table statistics would be sufficient.

Jira issue: CRDB-12737

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: lazily convert lookup join equality columns to lookup expr

Previously, the lookup join constraint builder would immediately convert
equality columns to an equality expression in the lookup expression when
it was determined that a lookup expression was required. Now, this
conversion happens after all the equality columns and the lookup
expression have been collected. This simplifies the logic.

Release note: None

#### opt: clarify foundEqualityCols in lookup join constraint builder

Release note: None

#### opt: fix greedy lookup join constraints

Previously, lookup joins would be planned that constrained as many index
columns as possible. This is not optimal when the last constrained
column is held to multiple values or a range which originated from an
optional filter for two reasons. First, the lookup join will not be more
selective because optional filters are truths about all rows in the
table. Second, the lookup join can be more expensive with additional
lookup expressions. In the case where the column is constrained to
multiple values, a lookup span is generated for each value,
significantly increasing the number of lookups performed for each input
row.

This commit makes the building of lookup join constraints less greedy.
The last constrained column will only be constrained to multiple values
or a range if the constraint originates from the query filter.

Fixes #75596

Release note (performance improvement): The optimizer now plans lookup
joins more efficiently in some cases.

### CODE REVIEW

**Comment by mgartner** [comment]
First two commits are from #81160.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-:-N1yHhqz8RejKa87EQzF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N1yGU3VCZb2BRyVSznY):*
nit: constrains -> constraints
___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N1yGeiP71zNBjeqzbIK:-N1yGeiP71zNBjeqzbIL:bxkmbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0858b5371d55082ad2a216baf662d8793df59bd2/pkg/sql/opt/lookupjoin/constraint_builder.go#L310)):*
> ```Go
> 			// constraint. They will only increase the number of lookup spans
> 			// without making the constraint more selective. We keep track of
> 			// the position of the expressions within lookupExpr so that we ca
> ```

nit: ca -> can
___
*[`pkg/sql/opt/lookupjoin/testdata/lookup_expr` line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N1yHIF_AzxhYki_zomJ:-N1yHIF_AzxhYki_zomK:b-dwezng) ([raw file](https://github.com/cockroachdb/cockroach/blob/0858b5371d55082ad2a216baf662d8793df59bd2/pkg/sql/opt/lookupjoin/testdata/lookup_expr#L98)):*
> ```
> ----
> lookup expression:
>   a = x
> ```

Should we have a way to convert back to key cols for cases like this? Or maybe instead of converting to lookup expr and converting back, we should wait to see if it turned out to be the last expr before converting in the first place?

**Comment by mgartner** [comment]
*[`pkg/sql/opt/lookupjoin/testdata/lookup_expr` line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N1yHIF_AzxhYki_zomJ:-N2CCjfLB4KEW0jP35r5:brl3gkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0858b5371d55082ad2a216baf662d8793df59bd2/pkg/sql/opt/lookupjoin/testdata/lookup_expr#L98)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should we have a way to convert back to key cols for cases like this? Or maybe instead of converting to lookup expr and converting back, we should wait to see if it turned out to be the last expr before converting in the first place?
</blockquote></details>

Ahh good catch. We should do definitely try to do something smarter in this case.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81162)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek and @rytaft)

___
*[`-- commits` line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N1yGU3VCZb2BRyVSznY):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: constrains -> constraints
</blockquote></details>

Done.
___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N1yGeiP71zNBjeqzbIK:-N5_tFJmADntdQ0011tu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0858b5371d55082ad2a216baf662d8793df59bd2/pkg/sql/opt/lookupjoin/constraint_builder.go#L310)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: ca -> can
</blockquote></details>

Done.
___
*[`pkg/sql/opt/lookupjoin/testdata/lookup_expr` line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N1yHIF_AzxhYki_zomJ:-N5_t-eB6PqvcPClBMP3:bxtz7zs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0858b5371d55082ad2a216baf662d8793df59bd2/pkg/sql/opt/lookupjoin/testdata/lookup_expr#L98)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ahh good catch. We should do definitely try to do something smarter in this case.
</blockquote></details>

I've moved the conversion until after the loop so we only convert when we need to. Great idea!

**Review by msirek — COMMENTED** [review]
> Reviewed 21 of 21 files at r4, 8 of 8 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81162)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 321 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N5fDyFB5phEt2G61d6Z:-N5fDyFB5phEt2G61d6_:b6py0fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/22e5a1e6b9c952896a3244a189ef5687cfc7151d/pkg/sql/opt/lookupjoin/constraint_builder.go#L321)):*
> ```Go
> 	// multiple values and it was derived from an optional filter. Also remove
> 	// the corresponding constant filter from constFilters and the origin filter
> 	// index from filterOrdsToRemove.
> ```

Should we try to remove more than just the last optional filter?  For example, in IN pred on `z` in this case:
```
lookup-constraints left=(a int, b int) right=(x int, v int not null as (x + 10) virtual, z INT, zz INT) index=(v, x, z, zz)
x = a
optional: z IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10) AND zz IN (1, 2, 3)
----
key cols:
  v = v_eq
  x = a
input projections:
  v_eq = a + 10
```
lookup-constraints left=(a int, b int) right=(x int, v int not null as (x + 10) virtual, z INT, zz INT) index=(v, x, z, zz)
x = a
optional: z IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10) AND zz IN (1, 2, 3)
----
input projections:
  v_eq = a + 10
lookup expression:
  ((z IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) AND (v_eq = v)) AND (a = x)
```
```

**Review by rytaft — APPROVED** [review]
:lgtm: Sorry for the delay!

> Reviewed 9 of 21 files at r4, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-:-N7be2ex4zS0e5DFHaZ1:b-8yidu2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder_test.go` line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81162#-N7bdviO9fgcF3SC2cqs:-N7bdviO9fgcF3SC2cqt:b-md8mbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0858b5371d55082ad2a216baf662d8793df59bd2/pkg/sql/opt/lookupjoin/constraint_builder_test.go#L155)):*
> ```Go
> 				}
> 				if len(lookupConstraint.KeyCols) > 0 && len(lookupConstraint.LookupExpr) > 0 {
> 					t.Errorf("expected lookup constraint to have either KeyCols or LookupExpr, not both")
> ```

Any reason you got rid of this check?

**Pull request closed without merging**
