### PR TITLE
kvcoord,roachpb: move a structured error to the new errors library

### LINKED ISSUE #74075: Unify structured error handling with "simple" (non-structured) errors
Currently non-structured errors are created using the vendored *errors* library [here](https://github.com/cockroachdb/vendored/tree/32b07eb223efa3515288fa484ebbce7feeafd365/github.com/cockroachdb/errors). On the other hand, structured errors are added to the [errors.proto](https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/errors.proto) and [errors.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/errors.go) files in *roachpb*.

See an example for a new structured error using the roachpb/errors way in [PR #73413](https://github.com/cockroachdb/cockroach/pull/73413), and a first draft for the new proposed structured error in [PR #73827](https://github.com/cockroachdb/cockroach/pull/73827).

- Can we avoid the registration of the encoder/decoder?
- Can we have an ID for each error without a centralized union (such as ErrorDetail)?
- Anything else?

Jira issue: CRDB-11906

### PR DESCRIPTION
**Pull request by lidorcarmel**
Exploring an alternative to PR 73413 - to use the new error
handling library for a new structured error.

The old way of using RefreshFailedError was deleted, and the new
way added, but renamed to RefreshFailedErrorV2, so that we can see
the diff.

This PR is still just a draft for now.

Closes #74075

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
I like it; isn't it great?

One thing that I'd want to ask @knz is whether we could modify the errors library such that we don't even need the `errors.RegisterLeafEncoder/RegisterLeafDecoder` calls when the error type is a proto. And another area I think we maybe could explore is making the marshalling processes resilient to changes in the error's type name (I assume currently it isn't, right)? The `ErrorDetails` union is resilient to that; I think it'd be nice if the errors lib closed that gap. I'm thinking something like a convention whereas error can optionally implement a `TypeID() uuid`, and having the unmarshalling be based on that stable id when present, rather than the less stable name.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-Mr2cgLV1qXVXjgeS6Lc:bski4od)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @lidorcarmel)

___
*[pkg/kv/kvserver/batcheval/cmd_refresh.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-Mr2cY3a4coKBLmVyxGg:-Mr2cY3a4coKBLmVyxGh:b-fegp26) ([raw file](https://github.com/cockroachdb/cockroach/blob/585b5c3156e10e8ae20dba6943762054f3494f5d/pkg/kv/kvserver/batcheval/cmd_refresh.go#L27)):*
> ```Go
> 	RegisterReadOnlyCommand(roachpb.Refresh, DefaultDeclareKeys, Refresh)
> 	pKey := errors.GetTypeKey(roachpb.RefreshFailedError{})
> 	errors.RegisterLeafEncoder(pKey, encodeRefreshFailedError)
> ```

I think these registrations should live in the roachpb package, next to the error

**Review by lidorcarmel — COMMENTED** [review]
The beauty is in the eyes of the beholder :) it's not bad but I expected it to be a bit cleaner. I do agree that if we get rid of the encoder/decoder it will be better.

How about this - let's stay with the "old" error handling as in the other PR, and I'll file an issue to:
- eliminate the encode/decode implementations (have something done by the library)
- see if it makes sense to migrate all the existing errors (is there a value in that?), or just put a DEPRECATED comment and use the new style structured errors for new things only. TBH I have zero intuition here.

WDYT?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-Mr4GIKSEjgXk3Fgg4L8:bcvv6w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/batcheval/cmd_refresh.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-Mr2cY3a4coKBLmVyxGg:-Mr4T_PkDIigstWav5zj:bxx4dvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/585b5c3156e10e8ae20dba6943762054f3494f5d/pkg/kv/kvserver/batcheval/cmd_refresh.go#L27)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think these registrations should live in the roachpb package, next to the error
</blockquote></details>

You're right! this is better. For some reason I thought it had to be in the init() of that package.. Thanks!

**Review by lidorcarmel — COMMENTED** [review]
BTW, for your second point - this sounds like proto 'oneof' - but then it's basically ErrorDetail message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-Mr7mhLc36zCwX_IIBum:brquusp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
> How about this - let's stay with the "old" error handling as in the other PR

All sounds good to me. 

> see if it makes sense to migrate all the existing errors (is there a value in that?)

Some value, in my book.

> BTW, for your second point - this sounds like proto 'oneof' - but then it's basically ErrorDetail message.

Right. But the whole point of the game is to close the compatibility gap versus `ErrorDetail` without the need for a centralized registry of all possible errors.
My problem with the `ErrorDetail` is that:
1) it's not complete. There's other errors that can happen on the server that are not represented in the enum.
2) It has too much in it. In particular it has error that can only happen in the kv stack on the client (not on the server), so you'd think they shouldn't need to be defined as protos (they don't cross the network), except they had to be protos until recently because KV was passing `pErr` around.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-Mr8i4EaCvMd98zqu6PU:b-8amkdr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @lidorcarmel)

___
*[pkg/roachpb/errors.go, line 1352 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-MtJRBVlCQ7ehJ5bevoY:-MtJRBVlCQ7ehJ5bevoZ:bscqxl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fdfa50ac34cb206bfc69f56b75b4e6045500356/pkg/roachpb/errors.go#L1352)):*
> ```Go
> func init() {
> 	pKey := errors.GetTypeKey(RefreshFailedError{})
> 	errors.RegisterLeafEncoder(pKey, encodeRefreshFailedError)
> ```

@knz claims you don't need these if the error is a proto

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/roachpb/errors.go, line 1352 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-MtJRBVlCQ7ehJ5bevoY:-MtJZtpj9rZcXpkakDaI:b-j07z5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fdfa50ac34cb206bfc69f56b75b4e6045500356/pkg/roachpb/errors.go#L1352)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

@knz claims you don't need these if the error is a proto
</blockquote></details>

yeah in this particular case, that's likely. do you want to try/test without? You can use `errors.EncodeError()` / `DecodeError()` to verify in a unit test.

**Review by lidorcarmel — COMMENTED** [review]
1. if everything is on the client, can/should we move from a protobuf to a struct?
2. Andrei, when you said `passing pErr around` above - by `pErr` did you mean `*roachpb.Error`?
3. if we want to send errors over gRPC, then I think renaming should work and we don't need a `TypeID() uuid` but I might be missing something. say we had:
```
service MyService {
  rpc GetSomething(GetRequest) returns(ErrorV1) {}
}
```
if we rename `ErrorV1` to  `ErrorV2` we should be good - the message name should not be sent over the wire.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-MtZR07P8OWpQbBRe-A6:b-g3hyy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/roachpb/errors.go, line 1352 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-MtJRBVlCQ7ehJ5bevoY:-MtZQ1hb27PqX98jksvV:bvxeu4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fdfa50ac34cb206bfc69f56b75b4e6045500356/pkg/roachpb/errors.go#L1352)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah in this particular case, that's likely. do you want to try/test without? You can use `errors.EncodeError()` / `DecodeError()` to verify in a unit test.
</blockquote></details>

indeed you're right, thank you both! looks much better now.

PTAL, I removed the old error and added RefreshFailedErrorV2 - different name for now just so that we can see all the affected code.

**Review by andreimatei — COMMENTED** [review]
This all looks good to me. But maybe the refresh error does not need to deal with serialization at all, like you say below.

> if everything is on the client, can/should we move from a protobuf to a struct?

I would say so.

> Andrei, when you said passing pErr around above - by pErr did you mean *roachpb.Error?

Yes. `pErr` is how we commonly name `*roachpb.Error` variables.

> if we want to send errors over gRPC, then I think renaming should work and we don't need a TypeID() uuid but I might be missing something. say we had:

Generally, a proto name indeed does not make it across the wire. However, in the case of the serialization done by the `errors` library, which uses `google.Any` (or whatever it's called), I think (assume?) that the name does make it across; I think there's a registry of protos indexed by type name. But I don't really know - @knz should speak the truth.
FWIW, I think the `errors` library does have some facilities for supporting renames - but I don't know if they're only one direction (new server supports both names) or how that interacts with protos.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-MuqtwPW1QQee6lZInhd:bp9qo0q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

**Review by knz — COMMENTED** [review]
>  in the case of the serialization done by the errors library, which uses google.Any (or whatever it's called), I think (assume?) that the name does make it across; I think there's a registry of protos indexed by type name.

Correct.

> I think the errors library does have some facilities for supporting renames

Yes, this was designed to support type renames and package migrations.

> but I don't know if they're only one direction (new server supports both names)

It's the other way around: it makes the new server inject the old name, so that the old server can still recognize it.

> or how that interacts with protos.

It's independent - it's only for the error types that are *not* protos.

> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-MutkU6RDqYq_Cc-lY6s:bypjnq4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @lidorcarmel)

___
*[pkg/kv/kvserver/batcheval/cmd_refresh_range_test.go, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-MutkzxW1Dcen_g2AyhP:-MutkzxX7RaAJzWpb9DY:b-inr94u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f766790c323e46012579deac9134d63f26a7dd71/pkg/kv/kvserver/batcheval/cmd_refresh_range_test.go#L15)):*
> ```Go
> import (
> 	"context"
> 	"errors"
> ```

cockroachdb/errors.
___
*[pkg/kv/kvserver/batcheval/cmd_refresh_test.go, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-Mutl0OjE0Rjeh7JSwnv:-Mutl0OjE0Rjeh7JSwnw:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f766790c323e46012579deac9134d63f26a7dd71/pkg/kv/kvserver/batcheval/cmd_refresh_test.go#L15)):*
> ```Go
> import (
> 	"context"
> 	"errors"
> ```

ditto

**Comment by lidorcarmel** [comment]
closed by mistake :( I'll fix..

**Review by lidorcarmel — COMMENTED** [review]
ok, finally an update:
- we need protos, at least for the `RefreshFailedError` because it goes over the wire.
- backward/forward compatibility are both fine, thanks to `RegisterTypeMigration` here https://github.com/cockroachdb/vendored/blob/b19e671990ef11e8e42c9593e0789633da820a8f/github.com/cockroachdb/errors/errbase/migrations.go#L19
- this change basically removes the need for `ErrorDetail`.

thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-MwdGMyW6Ecr7uRf-Ey-:b-lgrmcs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/kv/kvserver/batcheval/cmd_refresh_range_test.go, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-MutkzxW1Dcen_g2AyhP:-MwcfywUBfBcgYVQBU7_:bd6b69g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f766790c323e46012579deac9134d63f26a7dd71/pkg/kv/kvserver/batcheval/cmd_refresh_range_test.go#L15)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

cockroachdb/errors.
</blockquote></details>

Done. But then removed because this code changed on rebase, so we no longer need this import.
___
*[pkg/kv/kvserver/batcheval/cmd_refresh_test.go, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-Mutl0OjE0Rjeh7JSwnv:-MwcfzZqADdQOxp-T4OZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f766790c323e46012579deac9134d63f26a7dd71/pkg/kv/kvserver/batcheval/cmd_refresh_test.go#L15)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
> this change basically removes the need for ErrorDetail

Are we talking about the patch as is (i.e. only dealing with `RefreshFailedError`) or are you thinking about giving the treatment to all the `ErrorDetails` members? I guess I'm in favor of either, but if you only deal with `RefreshFailedError` then I'd add a comment to `ErrorDetails` referencing it; as long as that enum contains the majority of kvserver errors, I think it should try to at least reference the missing ones.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-Mx12yAd9K8n4o65Trfx:b-apbcds)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

**Review by lidorcarmel — COMMENTED** [review]
If this PR makes sense for `RefreshFailedError` then you're right, we should decide whether we want to only add a "deprecated" comment or migrate everything. I *think* that migrating everything is not a huge effort.. so it makes more sense, but I might be wrong..

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73827#-:-Mx1DChm2q4Hkv7zPx5t:b-ku30oo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

**Comment by lidorcarmel** [comment]
closing, after neglecting this one for too long.

**Pull request closed without merging**
