### PR TITLE
server: add lease and raft info to the range debug page

### PR DESCRIPTION
**Pull request by BramGruneir**
screen shot 2017-02-23 at 02 05 54

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13756)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: 

Need a better display for timestamps, though we'll want to see the raw values too (or have some sort of hover access to see them).

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/status.go, line 798 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-Kdg5QSLT9qFmrT54bAQ:-Kdg5QSLT9qFmrT54bAR:b-ukcbzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/848eb521e37bc6736376429d1f6044179f41e055/pkg/server/status.go#L798)):*
> ```Go
> 						} else {
> 							data.Replicas[desc.ReplicaID] = append(data.Replicas[desc.ReplicaID], desc)
> 						}
> ```

No need for the lookup. The body of the else-clause by itself is sufficient because `data.Replicas[desc.ReplicaID]` will return `nil` if `desc.ReplicaID` is not in the map.

---

*[pkg/server/status.go, line 960 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-Kdg5ifhmNZR5OjzVroj:-Kdg5ifhmNZR5OjzVrok:bor0wwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/848eb521e37bc6736376429d1f6044179f41e055/pkg/server/status.go#L960)):*
> ```Go
> // Call these functions so the unused check is appeased. They are used in
> // debugRangeTemplate.
> var _ = debugRangeData{}.ConvertRaftState("")
> ```

You don't have to call the functions, just make sure they are used. I believe this can be:

```
var _ = debugRangeData.ConvertRaftState
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-:-Kdg5wXTR-cD8Peemr_q:bwv2lr0)*

**Comment by BramGruneir** [comment]
I'll have timestamps fixed in the next update.

Thanks for the speedy review!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/status.go, line 798 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-Kdg5QSLT9qFmrT54bAQ:-Kdg6tXOCAYBy1NnQ3vS:b-esfcfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/848eb521e37bc6736376429d1f6044179f41e055/pkg/server/status.go#L798)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

No need for the lookup. The body of the else-clause by itself is sufficient because `data.Replicas[desc.ReplicaID]` will return `nil` if `desc.ReplicaID` is not in the map.
</blockquote></details>

nice, done

---

*[pkg/server/status.go, line 960 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-Kdg5ifhmNZR5OjzVroj:-KdgA03OIM42womCIXXP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/848eb521e37bc6736376429d1f6044179f41e055/pkg/server/status.go#L960)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You don't have to call the functions, just make sure they are used. I believe this can be:

```
var _ = debugRangeData.ConvertRaftState
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-:-KdgA2W8gF-pyBcKoEmz:b-g48sye)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/status.go, line 954 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgFKdzGEZw512KB3sj:-KdgFKdzGEZw512KB3sk:be3tbo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7e2a5f7b9dc785ff0eeb8e988f769a840020c20/pkg/server/status.go#L954)):*
> ```Go
> }
> 
> // Call these functions so the unused check is appeased. They are used in
> ```

This comment is now inaccurate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/status.go, line 954 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgFKdzGEZw512KB3sj:-KdgInNEx3XV24hRxmoi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7e2a5f7b9dc785ff0eeb8e988f769a840020c20/pkg/server/status.go#L954)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This comment is now inaccurate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/server/status.go, line 936 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgTTe8ARY9s56RMfey:-KdgTTe8ARY9s56RMfez:bgenkdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L936)):*
> ```Go
> 		}
> 		if d.RangeInfos[0].State.NumPending != d.RangeInfos[i].State.NumPending {
> 			d.HeaderClasses["Pending Commands"] = "warning"
> ```

It's expected for the number of pending commands to differ across replicas, so we should never highlight this row. (or maybe we want to highlight non-zero pending commands on non-lease-holders)

---

*[pkg/server/status.go, line 942 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgT_6rLTcNyk54-Kbv:-KdgT_6rLTcNyk54-Kbw:bggnymi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L942)):*
> ```Go
> 		}
> 		if d.RangeInfos[0].RaftState.HardState.Vote != d.RangeInfos[i].RaftState.HardState.Vote {
> 			d.HeaderClasses["Vote"] = "warning"
> ```

Differing votes are also normal. Let's move this up to below the "Leader" row and omit the "warning" highlighting. 

---

*[pkg/server/status.go, line 1112 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgUeKEukywyyOGkAew:-KdgUeKEukywyyOGkAex:b4r82fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L1112)):*
> ```Go
>             <DIV CLASS="cell {{index $.HeaderClasses "Pending Commands"}}">Pending Commands</DIV>
>             <DIV CLASS="cell {{index $.HeaderClasses "Term"}}">Term</DIV>
>             <DIV CLASS="cell {{index $.HeaderClasses "Vote"}}">Vote</DIV>
> ```

"Vote" (and probably "term") logically belong next to "leader". 

---

*[pkg/server/status.go, line 1113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgUbJxZKwuy0MBlUPV:-KdgUbJxZKwuy0MBlUPW:b-g7cn4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L1113)):*
> ```Go
>             <DIV CLASS="cell {{index $.HeaderClasses "Term"}}">Term</DIV>
>             <DIV CLASS="cell {{index $.HeaderClasses "Vote"}}">Vote</DIV>
>             <DIV CLASS="cell {{index $.HeaderClasses "Commit"}}">Commit</DIV>
> ```

"Commit" logically belongs between "applied" and "last index".

---

*[pkg/server/status.go, line 1167 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgVdxXEnuoKnGnIafx:-KdgVdxXEnuoKnGnIafy:b-6dzv4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L1167)):*
> ```Go
>               " TITLE="{{$det.RaftState.HardState.Vote}}">{{$det.RaftState.HardState.Vote}}</DIV>
>               <DIV CLASS="cell" TITLE="{{$det.RaftState.HardState.Commit}}">{{$det.RaftState.HardState.Commit}}</DIV>
>               {{range $repID, $rep := $.Replicas -}}
> ```

I'm unclear on what this part of the table is showing. The interesting case for RangeDescriptor.Replicas is when some nodes have replicas that others don't, so they won't always line up neatly across the columns. I think what we want here is just one row for "peers" and then list each node's view in a single cell. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/server/status.go, line 936 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgTTe8ARY9s56RMfey:-KdgwJpatp44opu9mPwU:b4gwuml) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L936)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's expected for the number of pending commands to differ across replicas, so we should never highlight this row. (or maybe we want to highlight non-zero pending commands on non-lease-holders)
</blockquote></details>

Sure, done and done. 

---

*[pkg/server/status.go, line 942 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgT_6rLTcNyk54-Kbv:-KdgyiDWNDYhXHewmmVV:bx4nh62) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L942)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Differing votes are also normal. Let's move this up to below the "Leader" row and omit the "warning" highlighting. 
</blockquote></details>

Done and done.

---

*[pkg/server/status.go, line 1112 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgUeKEukywyyOGkAew:-KdgzAqBNEk23nHMANVa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L1112)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"Vote" (and probably "term") logically belong next to "leader". 
</blockquote></details>

Done.

---

*[pkg/server/status.go, line 1113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgUbJxZKwuy0MBlUPV:-KdgzRiVimNmoaGvRTaA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L1113)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"Commit" logically belongs between "applied" and "last index".
</blockquote></details>

Done.

---

*[pkg/server/status.go, line 1167 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756#-KdgVdxXEnuoKnGnIafx:-KdgzSb7whXSuSCeYqER:bg1ixdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2119166625841e4302ce322a6086dc4ab227bcaa/pkg/server/status.go#L1167)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm unclear on what this part of the table is showing. The interesting case for RangeDescriptor.Replicas is when some nodes have replicas that others don't, so they won't always line up neatly across the columns. I think what we want here is just one row for "peers" and then list each node's view in a single cell. 
</blockquote></details>

This lines up quite well.  When there is no replica, it shows a `-` and it's quite clear there is an issue.  We can always refine it later, but I'd like to keep it as is for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13756)*

**Pull request merged**
