### PR TITLE
sql: minor clean-up.

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10594)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 1465 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594#-KWDpmPfPmpEQPTcPt0f:-KWDpmPfPmpEQPTcPt0g:b8yjb4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca27c56e6295c1560b2e83980baca92221602b9/pkg/sql/parser/eval.go#L1465)):*
> ```Go
> 	// SearchPath is the search path for databases used when encountering an
> 	// unqualified table name. Names in the search path are normalized already.
> 	// This must not modified (is shared from the session).
> ```

missing verb

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594#-:-KWDpoM6VfMZQK1EDI6J:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/eval.go, line 1465 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594#-KWDpmPfPmpEQPTcPt0f:-KWDsgbkdkFWy2kRhVMs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca27c56e6295c1560b2e83980baca92221602b9/pkg/sql/parser/eval.go#L1465)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> missing verb
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594#-:-KWDsi5hI4IPM2niTDXg:b-814cj3)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 1465 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594#-KWDpmPfPmpEQPTcPt0f:-KWDswEl2u3Zq2I-dmz0:b-hbcoar) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca27c56e6295c1560b2e83980baca92221602b9/pkg/sql/parser/eval.go#L1465)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Done.
</details>
you added a noun, the verb is still missing "This must not *be* modified".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 1465 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594#-KWDpmPfPmpEQPTcPt0f:-KWDt7oBeMVS7AKvhDam:bccjbmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca27c56e6295c1560b2e83980baca92221602b9/pkg/sql/parser/eval.go#L1465)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you added a noun, the verb is still missing "This must not *be* modified".
</details>
er, pronoun, not noun

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10594)*

**Comment by knz** [comment]
Ah I see thanks. Done.

**Pull request merged**
