### PR TITLE
kv: add WriteAtRequestTimestamp option to bulk adder

### PR DESCRIPTION
**Pull request by stevendanna**
This allows callers of the bulk adder to set this option. At the
moment, no callers use this option.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks!

**Comment by dt** [comment]
I think I have this in https://github.com/cockroachdb/cockroach/pull/74113

**Comment by stevendanna** [comment]
@dt yikes should have checked the outstanding prs. Thanks!

**Comment by erikgrinaker** [comment]
Whoops, thought that was merged already, and this was a straggler.

**Pull request closed without merging**
