### PR TITLE
acceptance: remove `elixir` test

### PR DESCRIPTION
**Pull request by rickystewart**
This test has been skipped for years. The tracking issue #52339 was
closed outright 3.5 years ago with the test being skipped. Doesn't seem
we benefit from this living in tree any more.

Epic: none
Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]

**Review by rafiss — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=rail,rafiss

**Comment by yuzefovich** [comment]
Seems like CI is red on this one.

bors r-

**Comment by rickystewart** [comment]
The failures appear to be unrelated flakes. Any failures from this change would be in `acceptance`, not `local roachtest`.

bors r=rail,rafiss

**Comment by rickystewart** [comment]
I don't know about the `bors` build, but the failure in my CI flaked due to [this issue](https://github.com/cockroachdb/cockroach/issues/121738).

**Pull request merged**
