### PR TITLE
rangefeed: surface unrecoverable errors and don't hopelessly retry 

### PR DESCRIPTION
**Pull request by irfansharif**
One such error is when the rangefeed falls behind to a point where the
frontier timestamp precedes the GC threshold, and thus will never work.
A new callback lets callers find out about the error, possibly to start
a new rangefeed with an initial scan.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvclient/rangefeed/config.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73086#-MpFlOTF1qV6MKXv4bEz:-MpFlOTF1qV6MKXv4bF-:bar75m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe4a46b15a3b4b5082421eb96a0e91268a1165/pkg/kv/kvclient/rangefeed/config.go#L50)):*
> ```Go
> type OnInitialScanError func(ctx context.Context, err error) (shouldFail bool)
> 
> // OnInternalError is called when the rangefeed exits with an internal error. One
> ```

Internal makes it seem like there’s no hope that the client is going to know what to do with the error. What about Permanent or Unrecoverable?
___
*[pkg/kv/kvclient/rangefeed/rangefeed_external_test.go, line 504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73086#-MpFlvnj81Az4hqYbdou:-MpFlvnj81Az4hqYbdov:bcykcsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe4a46b15a3b4b5082421eb96a0e91268a1165/pkg/kv/kvclient/rangefeed/rangefeed_external_test.go#L504)):*
> ```Go
> 
> 		if mu.internalErr == nil {
> 			return errors.New("expected internal error")
> ```

May as well check that the error is the expected one in terms of either type and structure or at least message.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/kv/kvclient/rangefeed/config.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73086#-MpFlOTF1qV6MKXv4bEz:-MpHNwLI21mjaNC59LBA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe4a46b15a3b4b5082421eb96a0e91268a1165/pkg/kv/kvclient/rangefeed/config.go#L50)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Internal makes it seem like there’s no hope that the client is going to know what to do with the error. What about Permanent or Unrecoverable?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/rangefeed/rangefeed_external_test.go, line 504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73086#-MpFlvnj81Az4hqYbdou:-MpHNxMd5T6R1hAHdZwl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe4a46b15a3b4b5082421eb96a0e91268a1165/pkg/kv/kvclient/rangefeed/rangefeed_external_test.go#L504)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

May as well check that the error is the expected one in terms of either type and structure or at least message. 
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by irfansharif** [comment]
Thanks Andrew!

bors r+

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73086#-:-MpHxA6J13ucG0mRHm16:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvclient/rangefeed/config.go, line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73086#-MpHwMu10Kn6CukbV3Vc:-MpHwMu10Kn6CukbV3Vd:b2ybno0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0ef1822613c1f49586c524177bf6b62cc92186e/pkg/kv/kvclient/rangefeed/config.go#L55)):*
> ```Go
> // thus will never work. The callback lets callers find out about such errors
> // (possibly, in our example, to start a new rangefeed with an initial scan).
> type OnUnrecoverableError func(ctx context.Context, err error)
> ```

nit: OnUnrecoverableError makes this sound more general than it is considering we only check if the frontier timestamp precedes the GC threshold. Consider naming this thing to be a bit more specific.

**Comment by irfansharif** [comment]
CI is pretty bad; skipping https://github.com/cockroachdb/cockroach/pull/73130.

**Pull request merged**
