### PR TITLE
cli: modify debug zip tenant ranges output to segment files by locality

### PR DESCRIPTION
**Pull request by abarganier**
In its previous form, the `tenant_ranges` component of the multitenant
debug.zip wrote the entirety of the range metadata to a single JSON
file. This made things difficult to parse in the corresponding
`hot-ranges-tenant.sh` script, since parsing JSON is tricky.

This patch changes the output format of tenant ranges to instead
write a single file for each range's metadata. The ranges will
be segmented by their locality. For example:

```
tenant_ranges/
├─ us-east4/
│  ├─ 46.json
│  ├─ 48.json
├─ us-west1/
│  ├─ 46.json
│  ├─ 46.json
├─ us-central1/
│  ├─ 48.json
│  ├─ 48.json

```

This allows us to provide metadata for all replicas while still
keeping the file output easy to parse.

With the output format change, we also add a `hot-ranges-tenant.sh`
script to generate the hottest ranges based on these files.

Release note: none

Release justification: low-risk updates to new functionality

### CODE REVIEW

**Comment by abarganier** [comment]
Note: Only the final commit is relevant to this PR.

The first 2 commits are reviewed here: https://github.com/cockroachdb/cockroach/pull/76892

The second 2 commits are reviewed here: https://github.com/cockroachdb/cockroach/pull/76743

**Review by rimadeodhar — COMMENTED** [review]
LG. Some minor suggestions and then we should be good to go.

> Reviewed 1 of 4 files at r2, 3 of 16 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-:-Mx6ajbyBHEzj_xvFiIm:by1p4ti)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @rimadeodhar)

___
*[pkg/cli/zip_cluster_wide.go, line 212 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-Mx6Y9i14Dv7xL4YiJbg:-Mx6Y9i14Dv7xL4YiJbh:b-5me66p) ([raw file](https://github.com/cockroachdb/cockroach/blob/83502c6c2d66a1d6f5388db03880f4bd657967ff/pkg/cli/zip_cluster_wide.go#L212)):*
> ```Go
> 				rangesFound += len(value.Ranges)
> 			}
> 			zc.clusterPrinter.info("%d tenant ranges found", rangesFound)
> ```

Nit: Feels like we are iterating over this map twice which might be expensive given the number of ranges can be pretty high. Can this info be printed after the second loop? That way, we can eliminate this loop altogether and just use the one loop to construct the range info as well as compute the total number of ranges returned?



_Code quote:_
```Go
			for _, value := range tenantRanges.RangesByLocality {
				rangesFound += len(value.Ranges)
			}
			zc.clusterPrinter.info("%d tenant ranges found", rangesFound)
			for locality, rangeList := range tenantRanges.RangesByLocality {
```
___
*[pkg/server/status.go, line 2044 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-Mx6Yu9sCj49xOXYzOB5:-Mx6Yu9sCj49xOXYzOB6:b-fff5p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/83502c6c2d66a1d6f5388db03880f4bd657967ff/pkg/server/status.go#L2044)):*
> ```Go
> 	tID, ok := roachpb.TenantFromContext(ctx)
> 	if !ok {
> 		return nil, errors.New("no tenant ID found in context")
> ```

I think returning a gRPC error here is more appropriate using `status.Error`
___
*[pkg/server/status.go, line 2122 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-Mx6ZcqO8bdrZvdxLgU1:-Mx6ZcqO8bdrZvdxLgU2:bc32umm) ([raw file](https://github.com/cockroachdb/cockroach/blob/83502c6c2d66a1d6f5388db03880f4bd657967ff/pkg/server/status.go#L2122)):*
> ```Go
> 		rep serverpb.RangeInfo,
> 	) (string, *serverpb.TenantRangeInfo) {
> 		topKLocksByWaiters := make([]serverpb.TenantRangeInfo_LockInfo, 0, len(rep.TopKLocksByWaitQueueWaiters))
> ```

Out of curiosity, do you know what this data is and how it used?

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback! Addressed your comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-:-MxAc5GhDUNv7jiXo_I_:be2i016)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[pkg/cli/zip_cluster_wide.go, line 212 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-Mx6Y9i14Dv7xL4YiJbg:-MxAXj_LAsJ7LxeLGO6P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83502c6c2d66a1d6f5388db03880f4bd657967ff/pkg/cli/zip_cluster_wide.go#L212)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: Feels like we are iterating over this map twice which might be expensive given the number of ranges can be pretty high. Can this info be printed after the second loop? That way, we can eliminate this loop altogether and just use the one loop to construct the range info as well as compute the total number of ranges returned?
</blockquote></details>

Done.
___
*[pkg/server/status.go, line 2044 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-Mx6Yu9sCj49xOXYzOB5:-MxAXrWF04YC6h3de9Np:bjik1ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/83502c6c2d66a1d6f5388db03880f4bd657967ff/pkg/server/status.go#L2044)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I think returning a gRPC error here is more appropriate using `status.Error`
</blockquote></details>

I'll implement this in the other PR https://github.com/cockroachdb/cockroach/pull/76743 - this PR is only relevant for the final commit :slightly_smiling_face: 
___
*[pkg/server/status.go, line 2122 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-Mx6ZcqO8bdrZvdxLgU1:-MxAY9jM3ir-PayrMq1-:bczzh5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/83502c6c2d66a1d6f5388db03880f4bd657967ff/pkg/server/status.go#L2122)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Out of curiosity, do you know what this data is and how it used?
</blockquote></details>

The TopKLockMetrics piece of ReplicaMetrics holds the metrics on the top K (where K = 3) locks by various orderings. Each holds information about the state of a single lock in a lockTable. In this case, the top-K is determined as the locks with the most waiters (readers + writers) in their wait-queue, ordered in descending order.

This is relevant to https://github.com/cockroachdb/cockroach/pull/76743, so let's continue discussing there if you have any additional feedback about this piece of the PR :slightly_smiling_face:

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 2 of 20 files at r7, 15 of 24 files at r10, 1 of 8 files at r11, 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77225)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @rimadeodhar)

___
*[pkg/cli/zip.go, line 289 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-MxBbnZWCUiEHer1S49o:-MxBbnZX0_Ywp8qZ4vJU:b-l5sfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e1043196ade34cda41234f4ce430ef8a98b0796/pkg/cli/zip.go#L289)):*
> ```Go
> 	}
> 
> 	// A script to summarize the hottest ranges for a tenant's range report.
> ```

Just to confirm my understanding, we get a tenant range report even against a storage server right? Since it will run the request as the system tenant?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77225)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[pkg/cli/zip.go, line 289 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77225#-MxBbnZWCUiEHer1S49o:-MxBd9pXEl4PJZt0ezJO:bn1yrds) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e1043196ade34cda41234f4ce430ef8a98b0796/pkg/cli/zip.go#L289)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Just to confirm my understanding, we get a tenant range report even against a storage server right? Since it will run the request as the system tenant?
</blockquote></details>

My experience when testing this against a storage server was that the system tenantID does not get set in the context when running debug.zip against a storage node directly.

We can see in the [authorization procedure](https://github.com/cockroachdb/cockroach/blob/master/pkg/rpc/auth.go#L126-L128) that if the node is a KV node, but the connection doesn't come from a SQL tenant server, then an [empty tenantID gets returned](https://github.com/cockroachdb/cockroach/blob/master/pkg/rpc/auth.go#L167). 

This leads the auth logic to [skip the `auth_tenant` checks, and call the handler immediately](https://github.com/cockroachdb/cockroach/blob/master/pkg/rpc/auth.go#L65-L70), where it fails the auth/validation in the endpoint since no tenant ID was not set in the context.

I find this preferable since `Ranges` is much more appropriate for the system tenant compared to `TenantRanges`, as it has more information and doesn't omit details that we obscure from non-system tenants.

**Comment by abarganier** [comment]
bors r=rimadeodhar

**Pull request merged**
