### PR TITLE
raft: ensure leaderMaxSupported does not regress when bumping terms

### LINKED ISSUE #133764: raft: ensure leadMaxSupported cannot regress when a leader bumps its term
**Describe the problem**

While staring at some raft code with @nvanbenschoten earlier today, as one does, we re-discovered this TODO:

https://github.com/cockroachdb/cockroach/blob/77b210b6a305793cbbbb7a83ab878961dea2d516/pkg/raft/raft.go#L1353-L1356

As written, it's possible for a raft leader to regress `leadMaxSupported` after it steps down, if it calls an election, doesn't win it, but de-fortifies followers and allowing another follower to win an election. This is possible because the TODO isn't addressed and this logic in `inFortifyLease`:

https://github.com/cockroachdb/cockroach/blob/77b210b6a305793cbbbb7a83ab878961dea2d516/pkg/raft/raft.go#L1480-L1486

---- 

To fix this, we could either:

1. Address the TODO and ensure `leadMaxSupported` is in the past by calling `CanDefortify` in `hup`.
2. OR remove the special case handling in `inFortifyLease` and check `supportingFortifedLeader` without exception in `hup`.

We settled on approach 2, as we no longer need this implicit de-fortification now that we have the explicit `MsgDeFortifyLeader` flow.

Jira issue: CRDB-43740

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, it was possible for a leader to regress leaderMaxSupported by calling an election at a higher term. This was because we weren't careful to recognize this case on the leader, and followers had special case handling that allowed a leader to override `inFortifyLease`. Together, this could cause lease regressions for LeaderLeases in some rare cases.

This patch fixes this issue by removing special case handling in `inFortifyLease`. We also remove a special case in the handling of `MsgHup` which allowed a leader to step down and campaign without de-fortifying itself.

Fixes https://github.com/cockroachdb/cockroach/issues/133764

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133873)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/raft.go` line 1270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATv0vo07VXbRRmGeQk:-OATv0vo07VXbRRmGeQl:b-3uz87l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1270)):*
> ```Go
> 	r.tick = r.tickElection
> 	// We're voting for ourselves. We shouldn't be supporting a fortified leader.
> 	assertTrue(!r.supportingFortifiedLeader(), "shouldn't become a candidate if we're supporting a fortified leader")
> ```

Can we lift up this assertion above `r.step`, like we have with the other precondition assertions in these "become" methods?
___
*[`pkg/raft/raft.go` line 1282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATuyKd8ca1DN9R5HfD:-OATuyKd8ca1DN9R5HfE:b-bvqn98) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1282)):*
> ```Go
> 	}
> 	assertTrue(!r.supportingFortifiedLeader() || r.lead == r.id,
> 		"should not be supporting a fortified leader when becoming pre-candidate; leader exempted",
> ```

Should we eliminate the "leader exempted" part?
___
*[`pkg/raft/raft.go` line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATvEUj-aaXT0znzdKZ:-OATvEUj-aaXT0znzdK_:bta1dg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1353)):*
> ```Go
> 	}
> 	// NB: Even an old leader that has since stepped down needs to de-fortify
> 	// itself before it can campaign at a higher term.
> ```

Could you add one more sentence about why that is?
___
*[`pkg/raft/testdata/fortification_followers_dont_prevote.txt` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATvmC9-Hr1vC-BCWsB:-OATvmC9-Hr1vC-BCWsC:b-b1zklw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/testdata/fortification_followers_dont_prevote.txt#L365)):*
> ```help
> 3: StateFollower (Voter) Term:2 Lead:2 LeadEpoch:1
> 
> # Lastly, ensure that the even the leader is not able to campaign at a higher
> ```

"that the even the"
___
*[`pkg/raft/testdata/fortification_followers_dont_prevote.txt` line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATvrV5Dbirb5sZchn0:-OATvrV5Dbirb5sZchn1:b-8dwjak) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/testdata/fortification_followers_dont_prevote.txt#L376)):*
> ```help
> DEBUG 2 ignoring MsgHup due to leader fortification
> 
> # Have 2 withdraw support from itself so it can move past the fortification
> ```

This is a store liveness withdrawal, right? Doesn't that make this an unrealistic test? Would it be better to wait for the self-defortification?

EDIT: I see that you're trying to test the disk stall case. If so, you can ignore what I said, but then maybe add that to the comment.
___
*[`pkg/raft/testdata/fortification_followers_dont_prevote.txt` line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATwNI62p6PnB5yRaTu:-OATwNI62p6PnB5yRaTv:b-sdut37) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/testdata/fortification_followers_dont_prevote.txt#L422)):*
> ```help
> 
> # Let's de-fortify {1,3}. First, sanity check that simply ticking doesn't send
> # out a de-fortification request, as leaderMaxSupported isn't in the past yet.
> ```

Do we need to stabilize to see this?

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-:-OAUdltBDqH5EyXpibM0:bb72pd0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATv0vo07VXbRRmGeQk:-OAUbT4y99dayuvnuSAZ:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1270)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we lift up this assertion above `r.step`, like we have with the other precondition assertions in these "become" methods?
</blockquote></details>

Done. 
___
*[`pkg/raft/raft.go` line 1282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATuyKd8ca1DN9R5HfD:-OAUbUBH0_a_Y03SuvEg:b-l2tt7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1282)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we eliminate the "leader exempted" part?
</blockquote></details>

Done, good catch.
___
*[`pkg/raft/raft.go` line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATvEUj-aaXT0znzdKZ:-OAUd_K23zfsRt3GwAYi:b-ezmr3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1353)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add one more sentence about why that is?
</blockquote></details>

Added some words. Was this what you had in mind?
___
*[`pkg/raft/testdata/fortification_followers_dont_prevote.txt` line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATvrV5Dbirb5sZchn0:-OAUcKwW42By7c1eYg7E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/testdata/fortification_followers_dont_prevote.txt#L376)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is a store liveness withdrawal, right? Doesn't that make this an unrealistic test? Would it be better to wait for the self-defortification?

EDIT: I see that you're trying to test the disk stall case. If so, you can ignore what I said, but then maybe add that to the comment.
</blockquote></details>

Done.
___
*[`pkg/raft/testdata/fortification_followers_dont_prevote.txt` line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATwNI62p6PnB5yRaTu:-OAUcNEh4FCcgRjDngWt:b-ewxth6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/testdata/fortification_followers_dont_prevote.txt#L422)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to stabilize to see this?
</blockquote></details>

Yeah, fixed.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133873)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/raft.go` line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATvEUj-aaXT0znzdKZ:-OAUnWww-AyaWt_kxT3F:b6zcrzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1353)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Added some words. Was this what you had in mind?
</blockquote></details>

That's part of it, but I was also thinking that we should say something about why an old leader that has since stepped down needs to de-fortify itself first. What is it waiting for? Why is waiting necessary for correctness?
___
*[`pkg/raft/raft.go` line 1283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OAUnQFl5OfprCFywHqg:-OAUnQFl5OfprCFywHqh:b-n01zxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a97b9e0a03e1e9fc44e542152e588e38f6ee6b/pkg/raft/raft.go#L1283)):*
> ```Go
> 	}
> 	assertTrue(!r.supportingFortifiedLeader(),
> 		"should not fortifying a leader when becoming pre-candidate",
> ```

"should not be"

Also, consider making a single line.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133873)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-OATvEUj-aaXT0znzdKZ:-OAVfglC5kKdNMxzfFl1:bp2s62l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a741e7ed20352232372ea3fc74a2d51edd402d4/pkg/raft/raft.go#L1353)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's part of it, but I was also thinking that we should say something about why an old leader that has since stepped down needs to de-fortify itself first. What is it waiting for? Why is waiting necessary for correctness?
</blockquote></details>

I was initially trying to avoid any talk about de-fortifying ourselves meaning `leadMaxSupported` is in the past. Just because we need to caveat the disk stall case, and then talk about why the disk stall case is still safe (because `inFortifyLease` doesn't treat campaigns from the old leader specially). 

I've expanded this comment, but truth be told, I don't like it too much. I'd be open to dropping it entirely if you feel similarly.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133873#-:-OAsOLLbA89jJJgnlGkt:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @iskettaneh)

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

**Comment by yuzefovich** [comment]
I _think_ the CI failed because of this PR:
```
testdata/fortification_followers_dont_vote.txt:415:
         
        expected:
        INFO 2 is starting a new election at term 4
        INFO 2 became candidate at term 5
        INFO 2 [logterm: 3, index: 12] sent MsgVote request to 1 at term 5
        INFO 2 [logterm: 3, index: 12] sent MsgVote request to 3 at term 5
        
        found:
        DEBUG 2 cannot campaign since it's not supported by a quorum in store liveness
```

bors r-

**Comment by arulajmani** [comment]
This merge skewed with https://github.com/cockroachdb/cockroach/pull/132915. I thought I was accounting for this case, but was missing a `support-expired reset`. Fixed, and this should be good to go.

bors r=nvanbenschoten

**Pull request merged**
