### PR TITLE
ui: Modifies events list and places a summary on the cluster page.

### PR DESCRIPTION
**Pull request by maxlang**
- Event times are now relative.
  - There is no event icon.
  - Only 10 events are shown. If the more events link is clicked
10 more events are shown each time.
  - Event styles have been changed to reflect the design.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12638)

### CODE REVIEW

**Comment by maxlang** [comment]
screen shot 2017-01-02 at 7 19 22 pm

**Comment by maxlang** [comment]
cc @kuanluo

**Comment by mrtracy** [comment]
LGTM! Very succinct.

**Comment by kuanluo** [comment]
LGTM!

**Pull request merged**
