### PR TITLE
roachtest: enable nightly test for django

### LINKED ISSUE #42675: roachtest: Enable django test suite in nightlies
Once the django-cockroachdb adapter is ready, we should do this.

### PR DESCRIPTION
**Pull request by rafiss**
We now have a stable release of django-cockroachdb, and tests should not
be flaky anymore.

closes #42675

Release note: none

### CODE REVIEW

**Comment by rohany** [comment]
LGTM -- you should look into running the full test suite + updating the blacklist at the same time (its pretty out of date).

**Review by apantel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44046)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel, @rafiss, and @rohany)

___
*[pkg/cmd/roachtest/django.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44046#-LzbrQJl7NHn2wtD4JUX:-LzbrQJl7NHn2wtD4JUY:b-q9xdhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d536425285efec26f323eea2b7bb5bb1c2fb4b0/pkg/cmd/roachtest/django.go#L142)):*
> ```Go
> 			ctx, c, node, "install django's dependencies", `
> 				cd /mnt/data1/django/tests &&
> 				sudo pip3 install -e ..
> ```

&& here? This could be clearer.
Otherwise LGTM.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44046)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @rohany)

___
*[pkg/cmd/roachtest/django.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44046#-LzbrQJl7NHn2wtD4JUX:-Lzc-RxxEU__SOxY4Cil:b-ug99s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d536425285efec26f323eea2b7bb5bb1c2fb4b0/pkg/cmd/roachtest/django.go#L142)):*
<details><summary><i>Previously, apantel (Adam Pantel) wrote…</i></summary><blockquote>

&& here? This could be clearer.
Otherwise LGTM.
</blockquote></details>

Yeah, there should be. thanks!

**Pull request merged**
