### PR TITLE
sql: fix possible race in runPlanInsidePlan

### LINKED ISSUE #116748: logictest: race around parallel checks
pkg/sql/logictest/tests/local-mixed-23.2/local-mixed-23_2_test.TestLogic_udf_fk [failed](https://tanzanite.cluster.engflow.com/invocations/default/cb776ceb-d010-496c-abe7-fb6410e6eaa3?testReportRun=1&testReportShard=17&testReportAttempt=1#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9sb2NhbC1taXhlZC0yMy4yOmxvY2FsLW1peGVkLTIzXzJfdGVzdA==) on master @ [5f76d93b2ad8d29c14c9b176753ec33cbf81e3fe](https://github.com/cockroachdb/cockroach/commits/5f76d93b2ad8d29c14c9b176753ec33cbf81e3fe):

```
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1957 +0x344
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3()
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1672 +0x1b0
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll()
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1675 +0x373
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2391 +0x9a4
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1931 +0x2375
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1108 +0x7aa7
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146 +0x184
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3372 +0x579
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145 +0x75d
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2227 +0x7e4
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2232 +0x2452
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2149 +0x3d5
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2149 +0x3d5
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:953 +0x21d
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:247 +0x572
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func3()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1001 +0x21c

Goroutine 90991 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:998 +0xa4f
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:814 +0xe24
  github.com/cockroachdb/cockroach/pkg/server.(*systemServerWrapper).serveConn()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_sql.go:164 +0x1d7
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_sql.go:84 +0x5c9
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux-fm()
      <autogenerated>:1 +0xc4
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1918 +0x26b
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:191 +0x1c6
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x278
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=17</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_udf_fk.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34751

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes a data race that was introduced in 187eabd0692fbfc9fe76affb5adf95a9eb49cf08. In particular, in that commit we made it so that `evalCtxFactory` method, in addition to creating a fresh copy of the eval context, also modifies the planner to point to the updated eval context. I believe this was needed so that `deferredRoutineSender` could be visible from the planner. However, `evalCtxFactory` method can be called concurrently (in the parallel checks code path), yet we'd be modifying the same `plannerCopy` object. This race is now eliminated by setting the deferred routine sender once on the eval context of the planner copy, meaning that the deferred routine sender will be visible from all code paths inside of `runPlanInsidePlan`. Additionally, this commit cleans up the factory method a bit to only create a copy of the eval context when used concurrently (which is what we do on the main code path in `execWithDistSQLEngine`).

Fixes: #116748.

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116803)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/apply_join.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116803#-Nm2xxuK5AxC7IUV_2uy:-Nm2xxuK5AxC7IUV_2uz:b-lxwjt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313990b8364c559612dbd2617ae70b4f79c6e6e/pkg/sql/apply_join.go#L294)):*
> ```Go
> 	plannerCopy.pausablePortal = nil
> 
> 	plannerCopy.extendedEvalCtx.RoutineSender = deferredRoutineSender
> ```

Shouldn't this happen on the copied `EvalContext`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116803)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/apply_join.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116803#-Nm2xxuK5AxC7IUV_2uy:-Nm2z3kt8j55ZYSiKSYd:bp5caua) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313990b8364c559612dbd2617ae70b4f79c6e6e/pkg/sql/apply_join.go#L294)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Shouldn't this happen on the copied `EvalContext`?
</blockquote></details>

`planner` object embeds `extendedEvalContext`, so here we're modifying a copy of the original eval context. Then, in all places within this function we treat `plannerCopy.extendedEvalContext` as the source of truth to go off. As a result, `params.p.extendedEvalCtx` isn't changed, but in all code paths within `runPlanInsidePlan` we do get the eval context in which `RoutineSender` is set, and this is exactly what we want, right?

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for the fix!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116803#-:-Nm30Qqz8r36RpPZtiON:b-72sm86)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/apply_join.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116803#-Nm2xxuK5AxC7IUV_2uy:-Nm30Eif-SmrTQUllP5p:bczvc8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313990b8364c559612dbd2617ae70b4f79c6e6e/pkg/sql/apply_join.go#L294)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`planner` object embeds `extendedEvalContext`, so here we're modifying a copy of the original eval context. Then, in all places within this function we treat `plannerCopy.extendedEvalContext` as the source of truth to go off. As a result, `params.p.extendedEvalCtx` isn't changed, but in all code paths within `runPlanInsidePlan` we do get the eval context in which `RoutineSender` is set, and this is exactly what we want, right?
</blockquote></details>

Oh, I was thinking that `ExtendedEvalContextCopyAndReset` would wipe out the setting. This is fine, then.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116803#-:-Nm31OiJ6Gt-iDhZeiVc:b-oduykh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/apply_join.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116803#-Nm2xxuK5AxC7IUV_2uy:-Nm314Fg0P8Ny-aA3EZz:b-4knffm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313990b8364c559612dbd2617ae70b4f79c6e6e/pkg/sql/apply_join.go#L294)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Oh, I was thinking that `ExtendedEvalContextCopyAndReset` would wipe out the setting. This is fine, then.
</blockquote></details>

Yeah, `ExtendedEvalContextCopyAndReset`is perhaps a somewhat unfortunate name - it doesn't reset anything, more like it makes a fresh copy of the eval context while updating a few fields to match those from the planner.

**Pull request merged**
