### PR TITLE
opt: plan lookup anti-, semi-, and leftjoins on indexes with virtual columns

### LINKED ISSUE #75873: opt: plan lookup anti-, semi-, and left joins on indexes with virtual columns
We don't currently plan lookup anti-, semi-, and left joins on indexes with virtual columns: https://github.com/cockroachdb/cockroach/blob/5fd739be5dbfcd8d08f83f7f0f24b302c85bb50d/pkg/sql/opt/xform/rules/join.opt#L215-L216

Planning anti- and semi-joins will depend on #75872, because decorrelation rules end up making projections of virtual column expressions with column IDs that do not match virtual column IDs in table metadata.

### PR DESCRIPTION
**Pull request by mgartner**
Fixes #75873

Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
Thanks for fixing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76697#-:-Mw2nycBAFBdoD2VJD5Y:b-whxd1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76697#-Mw2nDVF7iuPP89xwLc9:-Mw2nDVF7iuPP89xwLcA:boktf8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e5cf749ceac07469cd1c085febaf6759ffe3106/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L666)):*
> ```
>                           spans: /3/8765/0
> 
> # TODO(mgartner): The lookup join that checks for conflicts performs a lookup
> ```

Thanks for adding this TODO! it also applies to several other tests in this file and new tests from my pr #76358 :)
Do you plan to fix it for 22.1?

**Review by rytaft — APPROVED** [review]
:lgtm: good find!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76697#-:-Mw2pqCA6513gAv0FLU9:bbxruok)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @RaduBerinde)

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76697#-Mw2nDVF7iuPP89xwLc9:-Mw3E5t33Q-s9C08Jl1t:b-hetln6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e5cf749ceac07469cd1c085febaf6759ffe3106/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L666)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Thanks for adding this TODO! it also applies to several other tests in this file and new tests from my pr #76358 :)
Do you plan to fix it for 22.1?
</blockquote></details>

Yes, I plan on fixing it.

Unfortunately, I think the solution is to undo your previous changes which added the `UNIQUE WITHOUT INDEX` constraint to the table catalog. This is what's causing the issue, because it means that we select the `UNIQUE WITHOUT INDEX` as the arbiter, and therefore we build a left join with a filter that only has equality filters for the non-shard columns. Instead, we want to select the unique index with the shard columns as the arbiter, so that an equality condition on the shard column is included in the left join.

I'm sure I'll run into some problems that were handled easily by the synthetic `UNIQUE WITHOUT INDEX` constraint, but I don't see another way around  removing it.

**Review by msirek — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76697#-:-Mw4OntS4BZ3Ta55SRFk:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan and @RaduBerinde)

**Comment by mgartner** [comment]
TFTRs!

bots r+

**Comment by mgartner** [comment]
"bots" 🤦‍♂️ 

bors r+

**Pull request merged**
