### PR TITLE
util/tracing: use lightstep if COCKROACH_LIGHTSTEP_TOKEN is set

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6922)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/tracing/tracer.go, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-KIhjFO6ZAwyFOoYD-1C:-KIhjFO6ZAwyFOoYD-1D:-534892016) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27bc064b8ea40d127af8a7268f193dbf98a9b70/util/tracing/tracer.go#L27)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/util/caller"
> 	"github.com/cockroachdb/cockroach/util/envutil"
> 	"github.com/lightstep/lightstep-tracer-go"
> ```

does this need to be added to glock?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/tracing/tracer.go, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-KIhjFO6ZAwyFOoYD-1C:-KIhjcScc76zijuFr_Jk:-316264742) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27bc064b8ea40d127af8a7268f193dbf98a9b70/util/tracing/tracer.go#L27)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> does this need to be added to glock?
</details>
Yes it does. Thanks for catching that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922)*

**Comment by tamird** [comment]
Can this be done in `init` in the style suggested in their readme?

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Can this be done in `init` in the style suggested in their readme?
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-:-KIi6xUNv8X3gm3BI6x6:1417088721)*

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-:-KIi83jCvyhK9AIiiK-H:1417088721)*

**Comment by petermattis** [comment]
@tamird Their readme says to do the initialization in `main()`, but that is for a single global tracer which we aren't using. Where are you seeing docs suggesting tracer initialization be performed in an `init()` function?

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-:-KIiNJGFGZnb_nSaZZKF:-1566532848)*

**Comment by nvanbenschoten** [comment]
Looks like the commit/PR title needs to `s/ligtstep/lightstep/`

**Comment by nvanbenschoten** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Looks like the commit/PR title needs to `s/ligtstep/lightstep/`
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/tracing/tracer.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-KIicajUIL9vVUWPEkEk:-KIicajUIL9vVUWPEkEl:-815790422) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27bc064b8ea40d127af8a7268f193dbf98a9b70/util/tracing/tracer.go#L90)):*
> ```Go
> var newTracer = func() opentracing.Tracer {
> 	token := envutil.EnvOrDefaultString("lightstep_token", "")
> 	if token != "" {
> ```

Consider `if token := ...; token != "" {` to limit variable scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-:-KIicfa5Vvoxxe28-XZi:1417088721)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/tracing/tracer.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-KIicajUIL9vVUWPEkEk:-KIig21E8d2wDtaDkOmi:507652877) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27bc064b8ea40d127af8a7268f193dbf98a9b70/util/tracing/tracer.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Consider `if token := ...; token != "" {` to limit variable scope.
</details>
`var token = ...` should be outside this function, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-:-KIig-eyqjlRr09QJMum:1417088721)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[util/tracing/tracer.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-KIicajUIL9vVUWPEkEk:-KIiqXm8TXd5IcteKjY-:1449525757) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27bc064b8ea40d127af8a7268f193dbf98a9b70/util/tracing/tracer.go#L90)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `var token = ...` should be outside this function, too.
</details>
Moved `lightstepToken` outside of this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[util/tracing/tracer.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-KIicajUIL9vVUWPEkEk:-KIir8BZA2bYUbYZ6py-:1939308582) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27bc064b8ea40d127af8a7268f193dbf98a9b70/util/tracing/tracer.go#L90)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Moved `lightstepToken` outside of this function.
</details>
really picking nits here but

```
var newTracer func() opentracing.Tracer
func init() {
  if token := envutil.EnvOrDefaultString("lightstep_token", ""); token != "" {
    newTracer = func() opentracing.Tracer {
      return lightstep.NewTracer(lightstep.Options{AccessToken: token})
    }
  } else {
    newTracer = func() opentracing.Tracer {
      return basictracer.NewWithOptions(defaultOptions(func(_ basictracer.RawSpan) {}))
    }
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[util/tracing/tracer.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-KIicajUIL9vVUWPEkEk:-KIisjAquDGm4phxVXey:1455695431) ([raw file](https://github.com/cockroachdb/cockroach/blob/c27bc064b8ea40d127af8a7268f193dbf98a9b70/util/tracing/tracer.go#L90)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> really picking nits here but
> 
> ```
> var newTracer func() opentracing.Tracer
> func init() {
>   if token := envutil.EnvOrDefaultString("lightstep_token", ""); token != "" {
>     newTracer = func() opentracing.Tracer {
>       return lightstep.NewTracer(lightstep.Options{AccessToken: token})
>     }
>   } else {
>     newTracer = func() opentracing.Tracer {
>       return basictracer.NewWithOptions(defaultOptions(func(_ basictracer.RawSpan) {}))
>     }
>   }
> }
> ```
</details>
I'm not sure why that is better. `newTracer` is not called frequently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922)*

**Comment by tamird** [comment]
either way - you have my LGTM

**Comment by petermattis** [comment]
Note that I made a small addition to hide the lightstep command line flags. PTAL.

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Note that I made a small addition to hide the lightstep command line flags. PTAL.
</details>


---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6922#-:-KIjU3pqn7UtZuTisjFW:1417088721)*

**Pull request merged**
