### PR TITLE
build: upload nightly benchmarks to perfdata.golang.org

### PR DESCRIPTION
**Pull request by tamird**
This uses a service account I created for teamcity@cockroachlabs.com;
the secret will be placed in the TeamCity config after this is merged.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

How do we view the data on perfdata.golang.org? Is there going to be a dashboard somewhere?

Is the intention to enhance this tool to upload non-Go-benchmark data? For example, the data output by a load generator. Or will there be another tool for uploading non-Go-benchmark data?

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/benchmark/main.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW2QmmUaVnErLbdNai:-KlW2QmmUaVnErLbdNaj:b-xkxfn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L48)):*
> ```Go
> 
> const crdb = "github.com/cockroachdb/cockroach"
> const crdbSQL = "github.com/cockroachdb/cockroach/pkg/sql"
> ```

This looks unused.

---

*[pkg/cmd/benchmark/main.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW2ZsgmjdrTRjfE7L0:-KlW2ZsgmjdrTRjfE7L1:btzehn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L80)):*
> ```Go
> 
> 	{
> 		cmd := exec.CommandContext(ctx, "find", findDeleteArgs...)
> ```

It would be useful to sprinkle some comments around this code. For example: `Find and delete the per-package *.test binaries. We'll be rebuilding them below.`

---

*[pkg/cmd/benchmark/main.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW2iqDuTx5WbenstYq:-KlW2iqDuTx5WbenstYr:b9qzc3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L94)):*
> ```Go
> 		}
> 
> 		cmd := exec.CommandContext(ctx, "make", "-s", "testbuild", "TYPE="+typ)
> ```

`// Rebuild the per-package *.test binaries.`

---

*[pkg/cmd/benchmark/main.go, line 110 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW1h071porUpuoxhUD:-KlW1h071porUpuoxhUE:bt7xq70) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L110)):*
> ```Go
> 	u := client.NewUpload(ctx)
> 
> 	findCmd := exec.CommandContext(ctx, "find", findDeleteArgs[:len(findDeleteArgs)-1]...)
> ```

`// Find the *.test binaries we built.`

The above manipulation of `findDeleteArgs` is subtle. Perhaps define a `findArgs` and then define `findDeleteArgs` in terms of `findArgs`. 

---

*[pkg/cmd/benchmark/main.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW3aSF7eoZKi6ZkK-6:-KlW3aSF7eoZKi6ZkK-7:b-x6wyel) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L121)):*
> ```Go
> 		binaryPath, err := filepath.Abs(txt)
> 		if err != nil {
> 			return errors.Wrapf(err, "could not find test binary %s", txt)
> ```

You're not calling `u.Abort` on this code path.

---

*[pkg/cmd/benchmark/main.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW32P30cASnOnQ0QiS:-KlW32P30cASnOnQ0QiT:blg21dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L124)):*
> ```Go
> 		}
> 
> 		for i := 0; i < numIterations; i++ {
> ```

Is it better to run each benchmark `numIterations` times like this or to use `-test.count <numIterations>`? I use the latter all the time in local benchmarking.

---

*[pkg/cmd/benchmark/main.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW4P-S0egGWFFdOKtn:-KlW4P-S0egGWFFdOKto:bfeo5xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L126)):*
> ```Go
> 		for i := 0; i < numIterations; i++ {
> 			if err := func() error {
> 				w, err := u.CreateFile(fmt.Sprintf("bench%02d.txt", i))
> ```

This is reusing `bench0[0-4].txt` for each set of benchmarks. Is that kosher? 

I'm mildly surprised that it is ok to take so long between creating the `storage.Upload` and committing it. I would have thought it better to run all of the benchmarks generating a series of files, then create an upload and add all of the files to it. But if this works, ok.

---

*[pkg/cmd/benchmark/main.go, line 157 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW28tBAoXfDEzOL87o:-KlW28tCnzrCg9DOxo-6:b-x6wydz) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L157)):*
> ```Go
> 
> 	if err := scanner.Err(); err != nil {
> 		return errors.Wrap(err, "could not find new test binaries")
> ```

You're not calling `u.Abort` on this code path. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-:-KlW4-y1FN5DCyaMyUgc:b-yzacrz)*

**Comment by tamird** [comment]
The data is presented on perf.golang.org.

Yeah, the intention is to enhance this with other benchmark data, but the output will always have to be Go-benchmark-like.

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/benchmark/main.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW2QmmUaVnErLbdNai:-KlWwS1qTekKddhDP_Nf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L48)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This looks unused.
</blockquote></details>

Done.

---

*[pkg/cmd/benchmark/main.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW2ZsgmjdrTRjfE7L0:-KlWw_UlQ24XX0YQtz5w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L80)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It would be useful to sprinkle some comments around this code. For example: `Find and delete the per-package *.test binaries. We'll be rebuilding them below.`
</blockquote></details>

Done.

---

*[pkg/cmd/benchmark/main.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW2iqDuTx5WbenstYq:-KlWwdmNUwpa7z-ikEEu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L94)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`// Rebuild the per-package *.test binaries.`
</blockquote></details>

Done.

---

*[pkg/cmd/benchmark/main.go, line 110 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW1h071porUpuoxhUD:-KlWwnTAYEtiwKLx8LXZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L110)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`// Find the *.test binaries we built.`

The above manipulation of `findDeleteArgs` is subtle. Perhaps define a `findArgs` and then define `findDeleteArgs` in terms of `findArgs`. 
</blockquote></details>

Done.

---

*[pkg/cmd/benchmark/main.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW3aSF7eoZKi6ZkK-6:-KlWzFigX1_Uc_pIo6yS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L121)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You're not calling `u.Abort` on this code path.
</blockquote></details>

Done.

---

*[pkg/cmd/benchmark/main.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW32P30cASnOnQ0QiS:-KlWzGEN4r6GIWm_QzAD:bkas1c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L124)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is it better to run each benchmark `numIterations` times like this or to use `-test.count <numIterations>`? I use the latter all the time in local benchmarking.
</blockquote></details>

I don't think it matters, but I'm just following upstream's example, which results in a separate "file" for each upload. e.g. see "iteration" in the left panel: https://perf.golang.org/search?q=upload:20170531.13

---

*[pkg/cmd/benchmark/main.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW4P-S0egGWFFdOKtn:-KlWzP4Efl0kZ1sf1gP5:b-d36hgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L126)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is reusing `bench0[0-4].txt` for each set of benchmarks. Is that kosher? 

I'm mildly surprised that it is ok to take so long between creating the `storage.Upload` and committing it. I would have thought it better to run all of the benchmarks generating a series of files, then create an upload and add all of the files to it. But if this works, ok.
</blockquote></details>

I've rearranged this so there is no reuse - instead, each file contains the benchmark results for all packages.

I took a look at the implementation - doesn't look like any bytes hit the network until the call to `u.Upload`, so this seems safe.

---

*[pkg/cmd/benchmark/main.go, line 157 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW28tBAoXfDEzOL87o:-KlWzh2X_heOKYtpR3-i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L157)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You're not calling `u.Abort` on this code path. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-:-KlWziM9uMjQE1H2yKES:b-2q8toq)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/benchmark/main.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW4P-S0egGWFFdOKtn:-KlX-x7t0wlZ5pz_F2-q:b2otfs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L126)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I've rearranged this so there is no reuse - instead, each file contains the benchmark results for all packages.

I took a look at the implementation - doesn't look like any bytes hit the network until the call to `u.Upload`, so this seems safe.
</blockquote></details>

u.Commit, I mean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/benchmark/main.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlW4P-S0egGWFFdOKtn:-KlX0TS-WbvVCvmW2eQK:b1c4lzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ea2c016b17ce26a34bfa32c38640c5c034d78b/pkg/cmd/benchmark/main.go#L126)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

u.Commit, I mean.
</blockquote></details>

Oh, I'm wrong; this does actually do a (slow) multipart upload. I think it works, though we'll find out for sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255)*

**Comment by petermattis** [comment]
> The data is presented on perf.golang.org.

I'll need a little more hand holding than being pointed at perf.golang.org. How do I locate our benchmarks? How do a graph our data? Can we set up a wiki page with graphs? Or will we need a small webserver/dashboard?

> Yeah, the intention is to enhance this with other benchmark data, but the output will always have to be Go-benchmark-like.

Many of the load generators (`kv` and `ycsb`) output the final result in Go-benchmark format.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-:-KlYiXJtD_hR8cCnHPWx:b-uyj2jq)*

**Comment by tamird** [comment]
> I'll need a little more hand holding than being pointed at perf.golang.org.

Yep, I'll provide those instructions in follow-up work (once some data is actually uploaded).

Any last comments?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-:-KlYlVmmtKqo68wzh6qt:bq9gpbw)*

**Comment by bdarnell** [comment]
:lgtm: 

And for the record, the Go team is cool with third parties using their behcmark server?

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/teamcity-benchmarks.sh, line 6 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlZUwwhpzKiwzyJx2K0:-KlZUwwhpzKiwzyJx2K1:b-z463d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa677bca68b064c1fee41c3cffc45463f70b65c1/build/teamcity-benchmarks.sh#L6)):*
> ```Shell
> export BUILDER_HIDE_GOPATH_SRC=1
> 
> export BUILDER_HIDE_GOPATH_SRC=1
> ```

Twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-:-KlZVGqaKHdrkWqq5rF5:b-lg6hnq)*

**Comment by tamird** [comment]
Honestly, I wouldn't even know who to ask. I'll ask for forgiveness if they turn out not to be.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/teamcity-benchmarks.sh, line 6 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-KlZUwwhpzKiwzyJx2K0:-KlZWsoO7Y9igfGuLocB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa677bca68b064c1fee41c3cffc45463f70b65c1/build/teamcity-benchmarks.sh#L6)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Twice?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16255#-:-KlZWi6Nyh3PsOTKA60t:bi9ufvd)*

**Comment by bdarnell** [comment]
Ask on golang-dev? That's what they ask you to do for automated use of the go playground. It would be rude to do this without asking; we should give them a heads up to make sure they won't just delete our data or break compatibility without warning us.

**Comment by tamird** [comment]
Replied to https://groups.google.com/forum/#!searchin/golang-dev/perf.golang.org%7Csort:relevance/golang-dev/7cThjbB5MRU/-8aSAkiQBgAJ though it looks like my message is sitting in a moderation queue.

**Comment by tamird** [comment]
Looks like this is OK with the Go team.

**Pull request merged**
