### PR TITLE
server: refactor the sticky engine registry into a VFS registry

### LINKED ISSUE #107177: storage,server: replace StickyInMemEngines with vfs.FS registry
Many tests across the codebase make use of the `StickyInMemEnginesRegistry`. This registry dates back to before Pebble, and is used to preserve state across Engine `Close`s. Typically this is intended to test behavior across node restarts. Reusing the entire engine avoids exercising all the code paths associated with recovering engine state from a crash. We should change as many of these tests as we can to only reuse a vfs.MemFS. Additionally, we can add support for using `vfs.NewStrictMem` which can be used to simulate hard crashes by calling `SetIgnoreFsyncs(true)` before closing the Engine and `ResetToSyncedState` afterward to revert to the prior state.

Jira issue: CRDB-29934

### PR DESCRIPTION
**Pull request by jbowens**
The 'StickyInMemEngineRegistry' has historically been the method of preserving local physical state within tests across node/TestCluster restarts. This registry predates Pebble and its pure-Go VFS interface. This commit refactors the sticky engine registry into a registry of virtual filesystems. This improves test coverage by exercising storage engine teardown and recovery code.

The previous behavior of reusing the storage Engine without closing and re-opening is still supported with the server.ReuseEngines option.

Close #107177.
Epic: None
Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-:-Namyvxy1wrXa1RTKu9O:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/server/sticky_vfs.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NamyNO31ac4MUf36qe4:-NamyNO31ac4MUf36qe5:b1qvcdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L89)):*
> ```Go
> }
> 
> // Open implements the StickyInMemEnginesRegistry interface.
> ```

s/StickyInMemEnginesRegistry/StickyVFSRegistry/

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107829)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`pkg/server/sticky_vfs.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-Naqot17BRw9iEKcS3Hz:-Naqot17BRw9iEKcS3I-:b-a2ytos) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L44)):*
> ```Go
> // StickyVFSRegistry manages the lifecycle of sticky in-memory filesystems. It
> // is intended for use in demos and/or tests, where we want in-memory storage
> // nodes to persist between killed nodes.
> ```

nit: is this a `StickyVFSAndEngineRegistry`?
___
*[`pkg/server/sticky_vfs.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NaqpBXnAvruu1dFACCl:-NaqpBXnAvruu1dFACCm:bu2y9jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L47)):*
> ```Go
> type StickyVFSRegistry interface {
> 	// Open returns an engine associated with the given id. It will create a new
> 	// in-memory filesystem if one does not already exist. Otherwise, the new
> ```

It isn't clear whether each engine has its own in-memory FS.

I am also confused by the lifecycle of the FS and Engine and why this interface is structured in this manner which not very easy to follow (I realize we are inheriting this from `StickyInMemEnginesRegistry`, but perhaps we can clean this up?).

- It seems an FS is created once for an id, and is deleted by `CloseAllEngines`. The creation can happen either in Open or Get, whichever happens first for that id. What if the `StoreSpecs` are different? Given that we only need the id from the `StoreSpec` passed to `Get`, should we narrow that interface? Also it seems that `CloseAllEngines` is more like `WipeAllState` -- is my understanding correct? If yes, can we document this.

- An engine is created by `Open` and is closed by `CloseAllEngines`. It can also be individually closed, and the registry will know about it eventually due to the closed bool in the engine, but it doesn't really close the underlying engine. It doesn't close because with `reuseEngines` it doesn't want to close and open. But in the case of `!reuseEngines`, `Open` simply creates a new engine and never checks that the existing engine was closed -- which is odd.

I suppose our requirement is that anyone calling `Open` is either doing it for the first time ever for that id, or has already closed the engine for that id. And if `CloseAllEngines/WipeAllState` is called we don't care whether the caller has closed each engine or not -- it is the callers problem. Is that accurate?
___
*[`pkg/server/sticky_vfs.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NaqtWc82ST4AhyS6uMu:-NaqtWc82ST4AhyS6uMv:b-9i5ga4) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L105)):*
> ```Go
> 		if engine, engineOk := registry.engines[spec.StickyVFSID]; engineOk {
> 			if !engine.closed {
> 				return nil, errors.Errorf("sticky engine %s has not been closed", spec.StickyVFSID)
> ```

as mentioned before, should we do this check even when `!reuseEngines`, and actually close the underlying engine?
___
*[`pkg/server/sticky_vfs.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NaqrFVo6hMCSU0VS-0-:-NaqrFVo6hMCSU0VS-00:bendero) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L179)):*
> ```Go
> 		engine.closed = true
> 		engine.Engine.Close()
> 		delete(registry.entries, id)
> ```

why doesn't it delete from `registry.engines` too, given the underlying `FS` is no longer tracked?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107829)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/server/sticky_vfs.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-Naqot17BRw9iEKcS3Hz:-Nas8Ggy5fAuZHxg6SDW:bd4tc5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L44)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: is this a `StickyVFSAndEngineRegistry`?
</blockquote></details>

Related to the other comment; mechanically, yes, but hopefully not for long.
___
*[`pkg/server/sticky_vfs.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NaqpBXnAvruu1dFACCl:-Nas62efCWzCQgzYkVQ6:bo6mofc) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L47)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It isn't clear whether each engine has its own in-memory FS.

I am also confused by the lifecycle of the FS and Engine and why this interface is structured in this manner which not very easy to follow (I realize we are inheriting this from `StickyInMemEnginesRegistry`, but perhaps we can clean this up?).

- It seems an FS is created once for an id, and is deleted by `CloseAllEngines`. The creation can happen either in Open or Get, whichever happens first for that id. What if the `StoreSpecs` are different? Given that we only need the id from the `StoreSpec` passed to `Get`, should we narrow that interface? Also it seems that `CloseAllEngines` is more like `WipeAllState` -- is my understanding correct? If yes, can we document this.

- An engine is created by `Open` and is closed by `CloseAllEngines`. It can also be individually closed, and the registry will know about it eventually due to the closed bool in the engine, but it doesn't really close the underlying engine. It doesn't close because with `reuseEngines` it doesn't want to close and open. But in the case of `!reuseEngines`, `Open` simply creates a new engine and never checks that the existing engine was closed -- which is odd.

I suppose our requirement is that anyone calling `Open` is either doing it for the first time ever for that id, or has already closed the engine for that id. And if `CloseAllEngines/WipeAllState` is called we don't care whether the caller has closed each engine or not -- it is the callers problem. Is that accurate?

</blockquote></details>

This probably wasn't clear, but my intention is for this to be a VFS registry only. Tests should mostly (always?) re-open the store from the persisted state and not depend on in-memory unsynced engine state. Because that's not the interface we've previously provided, tests have accumulated dependencies on Engine state or the ability to use an Engine after `Close`. I think these usages should eventually be refactored away.

`CloseAllEngines` is only necessary when dependent on the old `ReuseEngines` behavior of reusing individual Engine instances, because otherwise the `Engine` is leaked. Otherwise, the registry is just a place to stash in-memory VFSes and it's up to the caller to be responsible for Close-ing their Engines and not concurrently accessing the same vfs.FS state.

I think the interface is not exactly what we want because we're split between these two worlds, and once we've updated the relevant tests we can consolidate on a clean VFS interface. I've renamed `ReuseEngines` to `ReuseEnginesDeprecated` to make this a little clearer.
___
*[`pkg/server/sticky_vfs.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NamyNO31ac4MUf36qe4:-Nas2Ff-ADsGe2G4tihj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L89)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

s/StickyInMemEnginesRegistry/StickyVFSRegistry/ 
</blockquote></details>

Done.
___
*[`pkg/server/sticky_vfs.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NaqrFVo6hMCSU0VS-0-:-Nas2KFf-rRKsoQ7z5aP:b-fm5gqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L179)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why doesn't it delete from `registry.engines` too, given the underlying `FS` is no longer tracked?
</blockquote></details>

This was a bug; done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-:-NavyD1Y6-fIjur8Qe9G:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @jbowens)

___
*[`pkg/server/sticky_vfs.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NaqpBXnAvruu1dFACCl:-Navy20A7tVd7YYUOA9w:b-ekfozx) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L47)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This probably wasn't clear, but my intention is for this to be a VFS registry only. Tests should mostly (always?) re-open the store from the persisted state and not depend on in-memory unsynced engine state. Because that's not the interface we've previously provided, tests have accumulated dependencies on Engine state or the ability to use an Engine after `Close`. I think these usages should eventually be refactored away.

`CloseAllEngines` is only necessary when dependent on the old `ReuseEngines` behavior of reusing individual Engine instances, because otherwise the `Engine` is leaked. Otherwise, the registry is just a place to stash in-memory VFSes and it's up to the caller to be responsible for Close-ing their Engines and not concurrently accessing the same vfs.FS state.

I think the interface is not exactly what we want because we're split between these two worlds, and once we've updated the relevant tests we can consolidate on a clean VFS interface. I've renamed `ReuseEngines` to `ReuseEnginesDeprecated` to make this a little clearer.
</blockquote></details>

nit: will there be another issue recording this plan after this PR closes #107177?

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-:-Naw1Xet0VAYSGkyCKIV:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/server/sticky_vfs.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107829#-NaqpBXnAvruu1dFACCl:-Naw1Nb0872s5kw1MAp4:b-1kv9ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/91d0ec709d28232f3f9472323bdca833fd9295be/pkg/server/sticky_vfs.go#L47)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: will there be another issue recording this plan after this PR closes #107177?
</blockquote></details>

Good call, filed #108119

**Pull request merged**
