### PR TITLE
sql: implement IterateStatementStats() for PersistedSQLStats

### PR DESCRIPTION
**Pull request by Azhng**
Depends on: #68555, #68620
Related to: #64743

Previously, IterateStatementStats() for PersistedSQLStats was
left unimplemented and it defaults to the implementation of
SQLStats.IterateStatementStats(). This means calls to
IterateStatementStats() on PersistedSQLStats cannot read
the statement statistitcs stored in system table.

This commit implements the IterateStatementStats() through
the new CombinedStmtStatsIterator which enables this method
to read both in-memory and persited statement statistics.

Release note: None

### CODE REVIEW

**Comment by Azhng** [comment]
This PR forks off #68555 and cherry picks the change from #68620. So only the last commit is the new addition.

`IterateTransactionStats()` is not yet implemented in this PR (it will be implemented in a follow up PR later) because most of the code will just be almost identical duplicate of this PR since they share very similar underlying APIs. I want to split the change into 2 PRs so the code change would be smaller.

**Comment by Azhng** [comment]
Rebased to master to remove the previous two merged commits from the branch.

**Review by maryliag — COMMENTED** [review]
> Reviewed 7 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68675)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sqlstats/ssprovider.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvtGTYBqfgQhlQVh0X:-MgvtGTYBqfgQhlQVh0Y:bbqd0sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b2e2c4cd21516918f07f4778b7f0e842469e3d1/pkg/sql/sqlstats/ssprovider.go#L87)):*
> ```Go
> // IteratorOptions provides the ability to the caller to change how it iterates
> // the statements and transactions.
> // TODO(azhng): we want to support pagination/continuation tokens as well as
> ```

are this todo no longer valid? was this implemented or dropped?
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvtTUM9eDRrxWiT5lD:-MgvtTUM9eDRrxWiT5lE:bvbcti4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L30)):*
> ```Go
> 
> 	mem struct {
> 		canBeAdvaned bool
> ```

nit: Advanced
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-Mgvu9ST7Q6YgdGN8gRS:-Mgvu9ST7Q6YgdGN8gRT:bw6l32y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L87)):*
> ```Go
> 	// If memIter is exhausted, but disk iterator can still move forward.
> 	// In this case, we promote the disk.Cur() and unpause the disk iterator if
> 	// it is paused and can be advanced.
> ```

nit: If memIter is exhausted, but the disk iterator can still move forward,
we promote the disk.Cur() and resume the disk iterator if it was paused.
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-Mgvufgb4EpErcVE_63-:-Mgvufgb4EpErcVE_630:b-df2x38) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L111)):*
> ```Go
> 	// If diskIter is exhausted, but mem iterator can still move forward.
> 	// In this case, we promote mem.Cur() and unpause mem iterator if it is paused
> 	// and can be advanced.
> ```

nit: If diskIter is exhausted, but the mem iterator can still move forward,
we promote the mem.Cur() and resume the mem iterator if it was paused.
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvuwXYDBPBiwV--dPI:-MgvuwXYDBPBiwV--dPJ:bcrcfme) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L122)):*
> ```Go
> 
> 	// Both iterators can be moved forward. Now we check the value of Cur()
> 	// for both iterator. We will have few scenarios:
> ```

nit: both iterators
nit: have a few
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-Mgvv1pg5PVC1YDA7o6c:-Mgvv1pg5PVC1YDA7o6d:b-mdxhom) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L125)):*
> ```Go
> 	// 1. mem.Cur() < disk.Cur()
> 	//    this case, we promote mem.Cur() to c.nextToRead. We then pause
> 	//    the disk iterator and unpause the mem iterator for next iteration.
> ```

nit: unpause > resume
nit: you can remove the `this case` of all 3 cases, go directly to `we promote...`
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvvRVV5tJFb9lascLc:-MgvvRVV5tJFb9lascLd:b-tcpql0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L128)):*
> ```Go
> 	// 2. mem.Cur() == disk.Cur()
> 	//    this case, we promote both mem.Cur() and disk.Cur() by merging both
> 	//    stats. We unpause both iterators for next iteration.
> ```

nit: unpause > resume
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvvWeiAt62ifLNnhaZ:-MgvvWeiAt62ifLNnha_:b-tcpql0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L131)):*
> ```Go
> 	// 3. mem.Cur() > disk.Cur()
> 	//    this case, we promote disk.Cur() to c.nextToRead. We then pause
> 	//    mem iterator and unpause disk iterator for next iteration.
> ```

nit: unpause > resume
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvxaDo1jp1Ax6KvZf3:-MgvxaDp6pVRzP_Iw7rZ:b-2ii262) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L171)):*
> ```Go
> 	// If and only if all three of the following fields are equal, lhs and rhs
> 	// are the same and they should be merged.
> 	if lhs.AggregatedTs.Equal(rhs.AggregatedTs) &&
> ```

isn't this case already being treated on the following checks? I can imagine this case would not be common, so you're making all other cases do this extra check without the need
___
*[pkg/sql/sqlstats/persistedsqlstats/mem_iterator.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvyB5aDUbU7zmxmNF8:-MgvyB5aDUbU7zmxmNF9:b2znc39) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/mem_iterator.go#L40)):*
> ```Go
> }
> 
> // Cur calls the m.StmtStatsIterator.Cur() but also populates the m.aggregatedTs
> ```

nit: ... Cur() and populates
___
*[pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-Mgw-tcR2FPNK01pnZGf:-Mgw-tcS8fooXmmR5zsn:bamg7v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go#L33)):*
> ```Go
> 	ctx context.Context, options *sqlstats.IteratorOptions, visitor sqlstats.StatementVisitor,
> ) (err error) {
> 	// We override the sorting options since otherwise we need to implement
> ```

nit: otherwise we would need
___
*[pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-Mgw0M1WCb4U1fuZsWYh:-Mgw0M1WCb4U1fuZsWYi:b3swvls) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go#L149)):*
> ```Go
> 	}
> 	stats.ID = roachpb.StmtFingerprintID(stmtFingerprintID)
> ```

nit: remove this blank line
___
*[pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-Mgw0Nj-6wYxbtT_kCKQ:-Mgw0Nj-6wYxbtT_kCKR:b3swvls) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go#L151)):*
> ```Go
> 
> 	stats.Key.PlanHash = uint64(tree.MustBeDInt(row[2]))
> ```

nit: remove this blank line

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68675)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/sql/sqlstats/ssprovider.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvtGTYBqfgQhlQVh0X:-MgwRFvN1DRXeD7klT0_:bqws844) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b2e2c4cd21516918f07f4778b7f0e842469e3d1/pkg/sql/sqlstats/ssprovider.go#L87)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

are this todo no longer valid? was this implemented or dropped?
</blockquote></details>

I didn't have a specific implementation in mind when I wrote the initial TODOs. My original thought is that the `statusServer` API would directly use this interface to handle API calls. 

Now that it has become clear that it would be better to let the `statusServer` to directly query the `crdb_internal` tables because we can directly leverage our entire SQL Engine to do all the filtering/grouping/projection logic instead of redoing them ourselves. 

Though, we should still implement the `StartTime` and `EndTime` fields here to support virtual index. This is so that we can issue a more optimal query against the system table. 
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-MgvxaDo1jp1Ax6KvZf3:-MgwQHfWEwUYMZFSdFnG:bdv8fhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57c03278cb713051f97fccd7c7b063d400678ef/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L171)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

isn't this case already being treated on the following checks? I can imagine this case would not be common, so you're making all other cases do this extra check without the need
</blockquote></details>

Ah good call. Removed this check.
I think this case would be common if we are forced to do premature flushes due to memory pressure.

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 19 files at r2, 2 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68675#-:-MhEH-lW5WrVEncohQP-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by Azhng** [comment]
bors r=maryliag

**Pull request merged**
