### PR TITLE
acceptance: use locally built cockroach binary by default

### PR DESCRIPTION
**Pull request by tamird**
I think we're going to have to make the nightlies depend on bleeding edge build (so that the binary can be downloaded) but that seems OK.

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:. Are we using tabs in scripts though?

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-:-KqxzxwZvrs_cvTawX9C:b41of3o)*

**Comment by tamird** [comment]
Changed to spaces.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/terraform/azure/variables.tf, line 2 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrBgWYF2F-5vAv9rPe0:-KrBgWYGpjoE24kVDI6H:bpc341b) ([raw file](https://github.com/cockroachdb/cockroach/blob/92b2b9dddf3eee91820d8978a703275c9c257e31/pkg/acceptance/terraform/azure/variables.tf#L2)):*
> ```HCL
> # Path to the cockroach binary. An empty value results in the latest official
> # binary being used.
> ```

What does "latest official" mean? 1.0.4 right now? Don't we want to test master in the nightlies or are the nightlies manually specifying that?

nvm, now saw the last commit.

---

*[pkg/acceptance/terraform/azure/variables.tf, line 17 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrBgNM0Hx07cjg3Cvnq:-KrBgNM0Hx07cjg3Cvnr:b6bdfv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/92b2b9dddf3eee91820d8978a703275c9c257e31/pkg/acceptance/terraform/azure/variables.tf#L17)):*
> ```HCL
> }
> 
> # SHA of the cockroach binary to pull down. If default, the latest is fetched.
> ```

LATEST as in, latest official?

---

*[pkg/acceptance/terraform/common/git.go, line 26 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrBhSVz7UdMZ77lkqEz:-KrBhSVz7UdMZ77lkqF-:b-obkei) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1bf096f9bc88a0bec03f5beffc8c2648c8c5d8/pkg/acceptance/terraform/common/git.go#L26)):*
> ```Go
> 
> func main() {
> 	var query map[string]string
> ```

What's query used for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-:-KrBhYb9M0LoOSOfF6aQ:bnfp4nl)*

**Comment by tamird** [comment]
@cuongdo this fixes the "number of writers exceeds nodes" error we were seeing. Could you have a look?

**Comment by cuongdo** [comment]
*[pkg/acceptance/allocator_test.go, line 51 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrGLN5EH4KgRbT9R9QY:-KrGLN5EH4KgRbT9R9QZ:b-8a9czj) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c527d9a4f5cecddfe26fdea10395f48262412/pkg/acceptance/allocator_test.go#L51)):*
> ```Go
> //   Note that the location has to be specified relative to the terraform
> //   working directory, so typically `-tf.cockroach-binary=../../cockroach`.
> //   This must be a linux binary; on a mac you must build with
> ```

The failure that occurs when the Linux binary does _not_ exist is bad: it results in:

1. Cluster create finishing
2. `cockroach-runner` failing due to the missing binary
3. `terraform destroy` failing because of the undefined Terraform variable `cockroach_binary`:
```
[cdocr@cdo-imac:cockroach]$ (cd /Users/cdocr/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/terraform/azure && terraform destroy -force -state rebal-3to5s-lovingbhaskara.tfstate && rm rebal-3to5s-lovingbhaskara.tfstate)
var.cockroach_binary
  Enter a value:
```

I suggest making the test for the Linux binary earlier in the test.

Also, I'm unclear if the `terraform destroy` issue is a more general thing that needs to be fixed. It might need a default value to allow the destroy to work properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457)*

**Comment by cuongdo** [comment]
*[pkg/acceptance/allocator_test.go, line 55 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrGNnshIq7BfWMGuKIg:-KrGNnshIq7BfWMGuKIh:b-hdg5m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c527d9a4f5cecddfe26fdea10395f48262412/pkg/acceptance/allocator_test.go#L55)):*
> ```Go
> //
> // Troubleshooting:
> // - The minimum recommended version of Terraform is 0.7.2. If you see strange
> ```

With the use of `terraform init`, is the min Terraform version now 0.10.0?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457)*

**Comment by cuongdo** [comment]
What's the suggested workflow for running tests locally now? The suggested command-line in `allocator_test.go` no longer works even after running `build/builder.sh make build`, because the test is now expecting `cockroach-linux-2.6.32-gnu-amd64` to exist, but it doesn't. `make build` doesn't add that suffix.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-:-KrGRRq0b8J10SZt9Qjb:bi6675w)*

**Comment by tamird** [comment]
Thanks for testing! I've updated those comments; the suggested workflow is now to use `teamcity-nightly-acceptance.sh`.

---

Review status: 2 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/acceptance/allocator_test.go, line 51 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrGLN5EH4KgRbT9R9QY:-KrWtis4fL7w8YpJnkMg:b-j6k7nz) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c527d9a4f5cecddfe26fdea10395f48262412/pkg/acceptance/allocator_test.go#L51)):*
Yeah, that destroy behaviour is annoying. Fixed it by adding defaults back - see https://github.com/hashicorp/terraform/issues/5425.

> I suggest making the test for the Linux binary earlier in the test.

Done.

---

*[pkg/acceptance/allocator_test.go, line 55 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrGNnshIq7BfWMGuKIg:-KrWgeIM24tpejHOTK9s:bif1b3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c527d9a4f5cecddfe26fdea10395f48262412/pkg/acceptance/allocator_test.go#L55)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

With the use of `terraform init`, is the min Terraform version now 0.10.0?
</blockquote></details>

No, as far as I can tell `terraform init` was introduced in 0.7.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-:-KrWrjphBORneC2hglEd:b-kl0p6w)*

**Review by jordanlewis — APPROVED** [review]
Seems good to me without a careful review, please hold off merging until @cuongdo gets a chance to re-test after you answered his question about local workflow.

**Comment by cuongdo** [comment]
*[build/teamcity-nightly-acceptance.sh, line 13 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrXez4oRxQUVVA7-ooa:-KrXez4oRxQUVVA7-oob:bl87t6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cd62c74e3cbd85afbe11617405944368cc56e4/build/teamcity-nightly-acceptance.sh#L13)):*
> ```Shell
> # Example use:
> #
> # COCKROACH_EXTRA_FLAGS='-tf.keep-cluster=failed' build/teamcity-nightly-acceptance.sh TestUpreplicate_1To3Small
> ```

I've tried running this command, and I get this:

```
build/teamcity-acceptance.sh: line 24: go-test-teamcity: command not found
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457)*

**Comment by cuongdo** [comment]
*[build/teamcity-nightly-acceptance.sh, line 13 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrXez4oRxQUVVA7-ooa:-KrXf2outmInYme7RMqK:b6eqndw) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cd62c74e3cbd85afbe11617405944368cc56e4/build/teamcity-nightly-acceptance.sh#L13)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

I've tried running this command, and I get this:

```
build/teamcity-acceptance.sh: line 24: go-test-teamcity: command not found
```
</blockquote></details>

(this is on my macOS dev machine)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457)*

**Comment by cuongdo** [comment]
*[build/teamcity-nightly-acceptance.sh, line 13 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-KrXez4oRxQUVVA7-ooa:-KrXgCRfWtnhTxw5ANvV:b-joarfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/20cd62c74e3cbd85afbe11617405944368cc56e4/build/teamcity-nightly-acceptance.sh#L13)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

(this is on my macOS dev machine)
</blockquote></details>

Never mind, didn't see step 3 above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457)*

**Comment by cuongdo** [comment]
My manual allocator test runs are looking good. `TestContinuousLoad_BlockWriter` is still failing because of the same issue that's affecting the nightly runs.

Given that many of the nightlies are currently failing, I'd say merge this and fix remaining issues in a separate PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17457#-:-KrXdx0JYxHJ8h1R6e9X:b-ldxrmn)*

**Comment by tamird** [comment]
@cuongdo I was wrong; this does require terraform 0.10+. I've updated the meta-runner to install it (it was previously installing 0.7.7).

I'll update the builder image as well, though it is not currently used for this purpose in CI.

**Pull request merged**
