### PR TITLE
roachtest: extend version-upgrade

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extends the version-upgrade test to verify that scanning a table with random types succeeds across versions. This can be useful, for example, when vectorized execution engine changes how it supports a type (natively vs datum-backed vector).

Informs: #102841.

Epic: None

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
A couple of things for consideration:

* Does this need to be a part of `acceptance/version-upgrade` (an acceptance test that runs as part of CI/bors)? Could it be a different test?
* Any chance we can keep a list of types instead of importing `pkg/sql`? While this is not the case currently, we ideally don't want roachtest to depend on it (see #96644).
* Do we need to spin up a new cluster just to test this feature? Maybe this kind of verification is a better fit for the `cockroach-go` logic test config?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the questions!

> Does this need to be a part of `acceptance/version-upgrade` (an acceptance test that runs as part of CI/bors)? Could it be a different test?

> Do we need to spin up a new cluster just to test this feature? Maybe this kind of verification is a better fit for the `cockroach-go` logic test config?

Let me ask a clarifying question first - do I understand it correctly that `acceptance/version-upgrade` always runs and due to mixed-version test framework it'll pick random operations from the ones defined in `runVersionUpgrade`? If so, my thinking behind including this new variant was that it'd _not_ require any more clusters to be created / any more test runs, it'll just make existing runs possibly a bit slower due to some additional operations that might get picked.

If we're concerned about about the test getting slower, then I'd advocate for replacing some existing things (like "JSONB" test feature from `versionUpgradeTestFeatures`) with this new random types thingy since the latter is superset of the former.

> Any chance we can keep a list of types instead of importing `pkg/sql`? While this is not the case currently, we ideally don't want roachtest to depend on it (see #96644).

Note that it doesn't import the whole `pkg/sql`, but `pkg/sql/randgen`. To me it seems acceptable to import this relatively low-level package into roachtest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119183#-:-NqdNC6yDQRFhw4I2ylC:bfkv9cn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @rytaft, and @srosenberg)

**Review by renatolabs — COMMENTED** [review]
> do I understand it correctly that `acceptance/version-upgrade` always runs

Yes, it always runs on CI (`roachtest local` mode), and it also runs on Roachtest Nightly builds, this time using real VMs.

> and due to mixed-version test framework it'll pick random operations from the ones defined in `runVersionUpgrade`?

No, the framework will run _all_ operations passed to `InMixedVersion`. There are plans in the future to create a test mode where a sample of the "operations" passed are called, but that's not the case now. That's why I was wondering about this and how it relates to increase in test time, especially in CI.

> this new random types thingy since the latter is superset of the former

This is a good point, and I think it would be a good change (we should probably keep the `persistent_db` check though).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119183#-:-NrB5RCBCi7BqEHzjXOX:bdopu63)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @srosenberg)

**Comment by yuzefovich** [comment]
Thanks for your input Renato on this change. I won't push forward on it (but I'll use it manually to verify what I wanted to test).

**Pull request closed without merging**
