### PR TITLE
sql: SELECT 1/3 return decimal out of range

### PR DESCRIPTION
**Pull request by louishust**
Release note: None

### CODE REVIEW

**Comment by louishust** [comment]
related to #25753

**Review by madelynnblue — COMMENTED** [review]
Thanks for this change. But thinking about it I believe we should perhaps:

1. remove LosslessCtx and just use HighPrecisionCtx instead
2. remove the cond.Inexact check

**Comment by nvanbenschoten** [comment]
@mjibson we just added the `cond.Inexact` check in `#25753` because of arguments like https://github.com/cockroachdb/cockroach/issues/25258#issuecomment-386344135.

I think this change is going in the right direction. Silent information loss is only justifiable if it is the result of an arithmetic computation. Literal values should not lose information without throwing an error, otherwise we're just making #25258 more rare without actually fixing the issue.

I think what we really need to do (which this change is approaching) is propagate precision during constant folding (like the TODO a few lines above suggests). This approach is most consistent with expectations and I believe it is the approach that scientific applications would be most accepting of. The following query in Postgres demonstrates this kind of significant figure propagation:

```
nathan=# select 1.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001/3;
                                             ?column?
--------------------------------------------------------------------------------------------------
 0.3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333334
(1 row)
```

@mjibson @knz do you have any reactions or insights about an approach like this?

In the meantime, I think we should revert #25597 until this is addressed.

**Comment by mjibson** [comment]
I thought postgres truncated decimals after 2000 digits but that's not the case. It appears to keep whatever you give it as a constant. You can add fine and it'll keep all the precision, but when you divide then it limits to 2000 digits (we do kinda similar stuff).

Is there a way to teach our constant handling to not run the Quo function if the divisor is `1`? I assume we can't just remove our use of rationals all together, so maybe that's a safe compromise?

**Comment by mjibson** [comment]
Nope, my suggestion is bad. I didn't understand the precision keeping mentioned above. It does indeed seem like we need to do that.

**Comment by louishust** [comment]
@nvanbenschoten can this pr be reviewed?

**Comment by mjibson** [comment]
This implementation isn't sufficient to match what postgres does, which is precision-matching:

```
postgres=# select 1./3;
        ?column?        
------------------------
 0.33333333333333333333
(1 row)

postgres=# select 1.00/3;
        ?column?        
------------------------
 0.33333333333333333333
(1 row)

postgres=# select 1.0000000000000000000000000000000000/3;
               ?column?               
--------------------------------------
 0.3333333333333333333333333333333333
(1 row)

postgres=# select 1/3.00000000000000000000000000000;
            ?column?             
---------------------------------
 0.33333333333333333333333333333
(1 row)
```

I think that's what we'd like to do instead of this. Although @knz and @nvanbenschoten may have other ideas.

**Comment by louishust** [comment]
@nvanbenschoten Ok

**Pull request closed without merging**
