### PR TITLE
sql: fix AS OF decimal parsing

### LINKED ISSUE #10241: sql: panic in AS OF SYSTEM TIME with positive exponent
```
SELECT 1 FROM t AS OF 1e1
```

Found with RSG.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #10241

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10242)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/as_of_test.go, line 122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1Puv8928tIEPRwSWx:-KV1Puv8928tIEPRwSWy:b-dzkwkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/as_of_test.go#L122)):*
> ```Go
> 	}
> 
> 	// Verify queries with positive scale work properly.
> ```

Its a little strange that the "verification" here is just that it hits a later error. Doesn't seem very durable to future changes.

---

*[pkg/sql/executor.go, line 1390 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1Qj-l_D_srzOx7A5d:-KV1Qj-l_D_srzOx7A5e:b-vnwz3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1390)):*
> ```Go
> 		ts.WallTime = int64(*d)
> 	case *parser.DDecimal:
> 		s := d.String()
> ```

This logic could use a brief comment explaining what it's doing (ie. "We format the decimal into a string and split...")

---

*[pkg/sql/executor.go, line 1391 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1Q9iEQxuqfdmQ_E_M:-KV1Q9iEQxuqfdmQ_E_N:bdeyp58) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1391)):*
> ```Go
> 	case *parser.DDecimal:
> 		s := d.String()
> 		parts := strings.SplitN(s, ".", 2)
> ```

You might want to assert that `len(parts) < 2` somewhere

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1QXnGewKw4nSZ3SR2:-KV1QXnGewKw4nSZ3SR3:bvn9n3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1399)):*
> ```Go
> 		if len(parts) > 1 {
> 			p := parts[1]
> 			if lp := len(p); lp > 10 {
> ```

Where is the `10` coming from here and below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1389 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV479e1-il0bR3xmnji:-KV479e2h29aA0-T00yg:b-anmokq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1389)):*
> ```Go
> 	case *parser.DInt:
> 		ts.WallTime = int64(*d)
> 	case *parser.DDecimal:
> ```

I am not too fond of this approach. If the textual representation of the value is relevant, then I'd rather store the text of the value in the syntax node (the `OrigString` of the token) and only convert it to a number in `isAsOf`. Having to go through two rounds of parse/print reeks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/as_of_test.go, line 122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1Puv8928tIEPRwSWx:-KV4A8rtMUBh4AKpcWUi:b6h3hvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/as_of_test.go#L122)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Its a little strange that the "verification" here is just that it hits a later error. Doesn't seem very durable to future changes.
</details>
True, but it was previously a panic, so this is useful to some degree to make sure we don't re-introduce that bug.

---

*[pkg/sql/executor.go, line 1389 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV479e1-il0bR3xmnji:-KV4BY9eNM0CA8Wemv-A:b-1tshpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1389)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I am not too fond of this approach. If the textual representation of the value is relevant, then I'd rather store the text of the value in the syntax node (the `OrigString` of the token) and only convert it to a number in `isAsOf`. Having to go through two rounds of parse/print reeks.
</details>
I don't understand how using OrigString works here without something first determining that we have a string, int, or decimal.

---

*[pkg/sql/executor.go, line 1390 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1Qj-l_D_srzOx7A5d:-KV4BXUZi5QGVBT1Bg-U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1390)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This logic could use a brief comment explaining what it's doing (ie. "We format the decimal into a string and split...")
</details>
Done.

---

*[pkg/sql/executor.go, line 1391 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1Q9iEQxuqfdmQ_E_M:-KV4AUOvZf1LshwndMug:b-44kyha) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1391)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> You might want to assert that `len(parts) < 2` somewhere
</details>
I guess I don't understand. SplitN(x, x, 2) guarantees that 1 <= len(parts) <= 2.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV1QXnGewKw4nSZ3SR2:-KV4BJ73r3LTmS9RxQPB:bm548ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1399)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Where is the `10` coming from here and below?
</details>
Added a comment about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/executor.go, line 1389 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-KV479e1-il0bR3xmnji:-KV4E5ZelwdknWOnCF_C:b-1t4bve) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce535154a6fc570b2b688dc16d4300187cdf3d6e/pkg/sql/executor.go#L1389)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I don't understand how using OrigString works here without something first determining that we have a string, int, or decimal.
</details>
Let me explain. The idea is that the Scanner does this determination for you already. So there are two bits of information available: 1) the type of token (SCONST/FCONST/ICONST) and 2) the text representation (OrigString). You could take both in the AsOf node, then swtich on the token type to determine what to do with the OrigString.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10242#-:-KV4n9NADYsrnWx2MU-m:bnfp4nl)*

**Pull request merged**
