### PR TITLE
opt: add a framework for testing the cost model

### PR DESCRIPTION
**Pull request by justinj**
This commit introduces the opbench framework.

opbench runs tests similar to the data-driven tests, but based around
parameterized queries. It checks the results against CSV files which
store the optimizer's estimated cost alongside some pre-recorded runtime
of each plan. The CSVs can then be analyzed either visually or
statistically to detect problems with the correlation between the
estimated and "actual" cost.

There's lots of future work here, mostly outlined in TODOs, but some big
ones include:

* general usability improvement,
* more queries/operators benchmarked,
* include a local script to generate a plot to eyeball the impact and
  justify PRs,
* provide an easy way to spin up a roachprod cluster to regenerate all
  the results (today it has to be pointed at a local cluster with TPCH
  already installed),
* roachperf integration to track correlation over time.

The CSV files produced can be directly consumed by some other process to either visualize or statistically analyze the correlation between our estimated cost and the actual cost. Example plot of the current checked in results:
image

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
This is really cool!

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-:-L_y7eqL2R4HBOjnfaac:b-8capno)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/opbench/cat.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xxEkkBUWd6Il72OQc:-L_xxEklBFrP5rt4f3_Y:b-ozze1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/cat.go#L35)):*
> ```Go
> 
> 	cat.ExecuteDDL(`
> 	ALTER TABLE region INJECT STATISTICS '[
> ```

Since auto stats collects stats on all columns now, is it worth injecting stats for all columns?
___
*[pkg/sql/opt/opbench/config.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xzA0QBQerQtKZTMeN:-L_xzA0QBQerQtKZTMeO:b3qtb4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/config.go#L32)):*
> ```Go
> // input is a named input to a plan, with a set value.
> type input struct {
> 	key   string
> ```

seems a bit odd that this is called "key" here, but "field" above. They refer to the same thing, right?
___
*[pkg/sql/opt/opbench/config.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xz_Pm9pA5Er7-zVTN:-L_xz_Pm9pA5Er7-zVTO:b-meils4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/config.go#L43)):*
> ```Go
> // A Configuration totally defines how the parameters for a given plan should
> // be set.
> type Configuration []input
> ```

Why not make this a map? Seems like you're using it as a map below...
___
*[pkg/sql/opt/opbench/config.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xzkfr2d2lZgiNeTCu:-L_xzkfr2d2lZgiNeTCv:b-dmzoct) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/config.go#L58)):*
> ```Go
> // Set sets a key to a value within the Configuration.
> func (c *Configuration) Set(k string, v float64) {
> 	*c = append(*c, input{k, v})
> ```

What if the key already exists in the Configuration?
___
*[pkg/sql/opt/opbench/opbench_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_y2Wv74snFKoubFRXV:-L_y2Wv74snFKoubFRXW:bqx7zwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/opbench_test.go#L95)):*
> ```Go
> }
> 
> // measureQuery runs a query against a running Cockroach and records how long
> ```

[nit] maybe "a running Cockroach cluster"? Although a running cockroach is a funny image....
___
*[pkg/sql/opt/opbench/opbench_test.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_y2xIKAXAwcUO4XYaG:-L_y2xIKAXAwcUO4XYaH:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/opbench_test.go#L100)):*
> ```Go
> 	db, err := sql.Open("postgres", *pgurl)
> 	if err != nil {
> 		return 0, errors.Wrap(err, "can only recompute actual results when pointed at a running Cockroach")
> ```

ditto
___
*[pkg/sql/opt/opbench/spec.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_y7QiLEcPol1KkqaE6:-L_y7QiMAkjGKDnFOEML:bvv7glr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/spec.go#L95)):*
> ```Go
> 
> // Benches is the set of benchmarks we run.
> var Benches = []*Spec{
> ```

It feels to me like the code from here down belongs in the test file....

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/opbench/cat.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xxEkkBUWd6Il72OQc:-La7Gk9d3CxpNmNH-W5z:b-671rgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/cat.go#L35)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Since auto stats collects stats on all columns now, is it worth injecting stats for all columns?
</blockquote></details>

That's a good idea! Done. Didn't bother updating our TPCH data-driven tests since I'd rather introduce some kind of "test schema" abstraction to unify all this stuff.
___
*[pkg/sql/opt/opbench/config.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xzA0QBQerQtKZTMeN:-LaGiJqN5sFoR6dvZJQp:b-yb4q1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/config.go#L32)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

seems a bit odd that this is called "key" here, but "field" above. They refer to the same thing, right?
</blockquote></details>

Yep! Deleted now though.
___
*[pkg/sql/opt/opbench/config.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xz_Pm9pA5Er7-zVTN:-LaGh_7g-1c_e519tsjW:b-i1ibse) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/config.go#L43)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why not make this a map? Seems like you're using it as a map below...
</blockquote></details>

Good call—a slice made sense in one of the earlier iterations of this framework but now a map is better for sure.
___
*[pkg/sql/opt/opbench/config.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_xzkfr2d2lZgiNeTCu:-LaGjJsu04cH4U3yidjI:b-k7mx7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/config.go#L58)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if the key already exists in the Configuration?
</blockquote></details>

Deleted.
___
*[pkg/sql/opt/opbench/opbench_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_y2Wv74snFKoubFRXV:-LaGjVQRC7aq3M2bp0Pl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/opbench_test.go#L95)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] maybe "a running Cockroach cluster"? Although a running cockroach is a funny image....
</blockquote></details>

Done.
___
*[pkg/sql/opt/opbench/opbench_test.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_y2xIKAXAwcUO4XYaG:-LaGjWMrB6_HZ2CM_fga:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/opbench_test.go#L100)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/opbench/spec.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_y7QiLEcPol1KkqaE6:-LaGl9n31TBXDVYNrxh9:bombmv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/spec.go#L95)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It feels to me like the code from here down belongs in the test file....
</blockquote></details>

Good call. Done.

**Comment by justinj** [comment]
Updated plot after rebasing on top of costing changes:
image

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/opbench/config.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGv65a7NbmXSXfVAPM:-LaGv65a7NbmXSXfVAPN:bgeypqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/config.go#L27)):*
> ```Go
> type Choice struct {
> 	Field   string
> 	Choices []float64
> ```

[nit] it's a bit odd that this field is called `Choices`, since you also call a set of many `Choice` structs choices.... Maybe `Values` or `Options` (or something else) might be better?
___
*[pkg/sql/opt/opbench/spec.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGwWX06BwuDJt40fIW:-LaGwWX06BwuDJt40fIX:b-cgjerc) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/spec.go#L26)):*
> ```Go
> // benchmark.
> // A Spec has "parameters", which are values that get substituted into
> // the Plan, and "InputNames", which are the values from which the parameters
> ```

I think you probably still mean "Inputs"
___
*[pkg/sql/opt/opbench/spec.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGw-1o2sD8lPUVsX2M:-LaGw-1o2sD8lPUVsX2N:b-ao5uzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/spec.go#L42)):*
> ```Go
> 	// InputNames is the set of possible InputNames, along with a set of potential values
> 	// for each. This allows enumerating all combinations of possible InputNames.
> 	Inputs []Choice
> ```

I think you probably didn't want to change the comment here.... 
___
*[pkg/sql/opt/opbench/testdata/tpch-hash-join.csv, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGwKoZ0YL8rbQrt8nS:-LaGwKoZ0YL8rbQrt8nT:b-ei5wr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/testdata/tpch-hash-join.csv#L2)):*
> ```CSV
> lineitem_rows,supplier_rows,estimated,actual
> 1000000,1000,1059539.141521,0.632029
> ```

Why did all these values change?

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/opbench/testdata/tpch-hash-join.csv, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGwKoZ0YL8rbQrt8nS:-LaGxUrJDpoPHQ4u8ojf:b-1rppq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/testdata/tpch-hash-join.csv#L2)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did all these values change?
</blockquote></details>

Ohh you mentioned that you rebased on costing changes -- never mind.

**Review by rytaft — COMMENTED** [review]
:lgtm: very nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-:-LaGxi1a0BkJ_fg5k2_N:bhnhlex)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35670)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/opbench/config.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGv65a7NbmXSXfVAPM:-LaHCwoW3UaayE4gOOKH:bje8w85) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/config.go#L27)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] it's a bit odd that this field is called `Choices`, since you also call a set of many `Choice` structs choices.... Maybe `Values` or `Options` (or something else) might be better?
</blockquote></details>

Good idea! Changed them both
___
*[pkg/sql/opt/opbench/opbench_test.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaHD9bUEeMFk6PjSaWX:-LaHD9bUEeMFk6PjSaWY:bejojm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a22456b4defc235f318283ae8cc9ef8b98373803/pkg/sql/opt/opbench/opbench_test.go#L225)):*
> ```Go
> 	// TODO(justin): we should support multiple catalogs, and each query
> 	// should specify which catalog it pertains to.
> 	catalog := opbench.MakeTPCHCatalog()
> ```

moved this up because I realized we were recreating it every time and it was making this test take ~500ms (now it takes ~80ms).
___
*[pkg/sql/opt/opbench/spec.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGwWX06BwuDJt40fIW:-LaH1n-S3dtO8PNzvsi6:b2z4taw) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/spec.go#L26)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you probably still mean "Inputs"
</blockquote></details>

oops, too aggressive with the goland rename...
___
*[pkg/sql/opt/opbench/spec.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGw-1o2sD8lPUVsX2M:-LaH26HD44w64M_7dtq-:bjja8wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/spec.go#L42)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you probably didn't want to change the comment here.... 
</blockquote></details>

oops! Fixed.
___
*[pkg/sql/opt/opbench/testdata/tpch-hash-join.csv, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGwKoZ0YL8rbQrt8nS:-LaH2F791RdEPMTh-i75:bqdjmtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/testdata/tpch-hash-join.csv#L2)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ohh you mentioned that you rebased on costing changes -- never mind.
</blockquote></details>

The change I rebased on top of was only to lookup joins, I think these changed because I put the actual stats in, which have slightly different row counts than the ones I initially put in (I had rounded them).

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35670)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/opbench/opbench_test.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaHD9bUEeMFk6PjSaWX:-LaHKbFj1BGsuBchz8w4:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/a22456b4defc235f318283ae8cc9ef8b98373803/pkg/sql/opt/opbench/opbench_test.go#L225)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

moved this up because I realized we were recreating it every time and it was making this test take ~500ms (now it takes ~80ms).
</blockquote></details>

nice!
___
*[pkg/sql/opt/opbench/spec.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGwWX06BwuDJt40fIW:-LaHKjkQ68N_jXsxa67H:bkbdh1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/spec.go#L26)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

oops, too aggressive with the goland rename...
</blockquote></details>

keep the capitalization, though
___
*[pkg/sql/opt/opbench/spec.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGw-1o2sD8lPUVsX2M:-LaHKqoI7R3rBaoBzE5i:b24ifzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/spec.go#L42)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

oops! Fixed.
</blockquote></details>

Still need to fix the first word in the sentence
___
*[pkg/sql/opt/opbench/testdata/tpch-hash-join.csv, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-LaGwKoZ0YL8rbQrt8nS:-LaHL02QDiQpIZqYfNW_:b1ubcge) ([raw file](https://github.com/cockroachdb/cockroach/blob/880e3c73782101705ad8e2609e0d337f55b9ce38/pkg/sql/opt/opbench/testdata/tpch-hash-join.csv#L2)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

The change I rebased on top of was only to lookup joins, I think these changed because I put the actual stats in, which have slightly different row counts than the ones I initially put in (I had rounded them).
</blockquote></details>

Makes sense

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 4 of 8 files at r2, 2 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-:-LaLLdGa2Itk-wtaRueR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/opbench/cat.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35670#-L_sKR1S8owexPoaKH7l:-L_sKR1S8owexPoaKH7m:b-9z6wht) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff7a8e6076804334edf6d49e007b38389f50b293/pkg/sql/opt/opbench/cat.go#L27)):*
> ```Go
> 
> 	cat.ExecuteDDL(`
> CREATE TABLE public.region (
> ```

[nit] this intermingling of code and queries is pretty annoying. we could put all of them in one string and split by `;`.  That will also help a bit towards the TODO above.

**Comment by justinj** [comment]
Changed the creation of the catalog, much better now.

Thanks for the reviews!

bors r+

**Pull request merged**
