### PR TITLE
sql: add support for `DELETE FROM ... USING`

### LINKED ISSUE #40963: sql: support DELETE FROM ... USING
Add support for the `USING` clause on `DELETE`, which allows joining multiple tables for a `DELETE` clause.

This appears similar to #7841, which tracked adding joins to `UPDATE`.

https://www.postgresql.org/docs/10/sql-delete.html

Epic: CRDB-5498

### PR DESCRIPTION
**Pull request by faizaanmadhani**
See commit messages for details.

Resolves: #40963

### CODE REVIEW

**Review by mgartner — CHANGES_REQUESTED** [review]
Nice work! I've review the first two commits and left some comments. I'll come back and review the final comment once you address some of those.

> Reviewed 8 of 8 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-:-NE6U6Tw-jE8aUzMAKAN:b-4ggjxo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6KeU51uZ8hIF-ZYs8):*
No need for a release note until the feature is completed, so make this `Release note: None`.
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6KCY32eAodeAZbOH1):*
nit: this -> This
___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6KIxrD9wduTMZBClS):*
Release notes are intended to be read by users. Optbuilder doesn't really mean anything to most users, so I'd leave this as `Release note: None`, and only put a release note on the final commit that completes the feature.
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6ObEoAAywgZ2kGh2Z:-NE6ObEoAAywgZ2kGh2_:brfrwh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac97aa1e983e4e55c78c405a79a3e0a6c3bde51/pkg/sql/opt/optbuilder/mutation_builder.go#L446)):*
> ```Go
> 
> 	// Set list of columns that will be fetched by the input expression.
> 	mb.setFetchColIDs(mb.outScope.cols)
> ```

I'm alarmed that prior to this commit we called `setFetchColIDs` with some potential non-fetch columns... I guess that didn't cause any problems. Regardless, moving `setFetchColIDs` up looks more correct to me. :+1: 
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6L0FPEGsys4t4quRm:-NE6L0FPEGsys4t4quRn:b-31yaxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/mutation_builder.go#L381)):*
> ```Go
> //		SELECT <cols>
> //		FROM <table>
> //	  USING <tables>
> ```

`USING` can't be used in a `SELECT` statement liked this, so this is confusing. What about something like:

```
SELECT <cols>
FROM <table> [, <using-tables>]
WHERE <where>
...
```
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6P-Y0DBW1-zr4DjTp:-NE6P-Y0DBW1-zr4DjTq:b-id0jnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/mutation_builder.go#L430)):*
> ```Go
> 	usingClausePresent := len(using) > 0
> 	if usingClausePresent {
> ```

nit: remove empty line here
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 436 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6PAMt8iRmiYIi7ZLh:-NE6PAMt8iRmiYIi7ZLi:but7xxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/mutation_builder.go#L436)):*
> ```Go
> 		mb.b.validateJoinTableNames(mb.fetchScope, usingScope)
> 
> 		mb.extraAccessibleCols = usingScope.cols
> ```

nit: A comment here similar to the one in `buildInputForUpdate` would be helpful. These `extraAccessibleCols` aren't widely used and they're tricky to understand.
___
*[`pkg/sql/parser/sql.y` line 4847 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6JP3VBj7UztN9PDzP:-NE6JP3VBj7UztN9PDzQ:b-r1g55o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac97aa1e983e4e55c78c405a79a3e0a6c3bde51/pkg/sql/parser/sql.y#L4847)):*
> ```Yacc
> opt_using_clause:
>   USING from_list {
>   $$.val = $2.tblExprs()
> ```

nit: indent >
___
*[`pkg/sql/parser/sql.y` line 4850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6JRAg73kG18hZNQf4:-NE6JRAg73kG18hZNQf5:b2sno9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac97aa1e983e4e55c78c405a79a3e0a6c3bde51/pkg/sql/parser/sql.y#L4850)):*
> ```Yacc
>  }
> | /* EMPTY */ {
> 	$$.val = tree.TableExprs{}
> ```

nit: use spaces to indent instead of tabs to match the rest of the file
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 490 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6QZj93JMwHpBW74aG:-NE6QZj93JMwHpBW74aH:b-7cg5jw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L490)):*
> ```
> 
> # ------------------------------------------------------------------------------
> # Test USING.
> ```

Some tests to add:

- test the validateJoinTableNames path by putting the same table in the USING clause multiple times
- 
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6R4pXA9u95MjpNHqq:-NE6R4pXA9u95MjpNHqr:b-g2g8nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L493)):*
> ```
> # ------------------------------------------------------------------------------
> 
> # Test a simple join with a filter
> ```

nit: end comments that are sentences with a period, here and below.
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6Pts5Ccm8AKlYj8cQ:-NE6Pts5Ccm8AKlYj8cR:b-8oe49q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L495)):*
> ```
> # Test a simple join with a filter
> build format=show-qual
> DELETE FROM u_a USING u_b WHERE c = u_b.a AND u_b.b = 'd'
> ```

nit: I think it'd be possible to use the existing tables for your tests, like `abcde`, `xyz`, and `uv`. They're named after their columns so it's easy to follow which columns come from where.
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6S8NVAwrQ1Pgg3sSa:-NE6S8NW7yDaZ-JN723p:b-wmdsgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L503)):*
> ```
>  └── select
>       ├── columns: t.public.u_a.a:6!null t.public.u_a.b:7 t.public.u_a.c:8!null t.public.u_a.crdb_internal_mvcc_timestamp:9 t.public.u_a.tableoid:10 t.public.u_b.a:11!null t.public.u_b.b:12!null t.public.u_b.crdb_internal_mvcc_timestamp:13 t.public.u_b.tableoid:14
>       ├── inner-join (cross)
> ```

If the input has duplicate rows, then we'll delete the same row multiple times - which is a waste of work. I'm not sure it'll necessary corrupt indexes, but the delete operator has only every operated on distinct rows, so it's safest to follow the pattern.

The join you've added can duplicate rows in the target table, so we'll need to eliminate those duplicates. See the distinct-on operator we build for `UPDATE .. FROM` — you can do something similar for `DELETE .. USING`.
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 754 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6U1ys7LnAmGApE1iU:-NE6U1ys7LnAmGApE1iV:brihifc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L754)):*
> ```
> CREATE TABLE pindex (
>   a DECIMAL(10, 2),
>   CHECK (a > 0)
> ```

This is a check constraint, not a partial index.
___
*[`pkg/sql/parser/testdata/delete` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6K0Zs7MzReiCUXYqr:-NE6K0Zs7MzReiCUXYqs:b5ve7lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac97aa1e983e4e55c78c405a79a3e0a6c3bde51/pkg/sql/parser/testdata/delete#L146)):*
> ```
> 
> parse
> DELETE FROM a USING b WHERE c = d AND e = f
> ```

Can you add some parser tests with multiple using tables?

**Review by faizaanmadhani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6S8NVAwrQ1Pgg3sSa:-NE81mf0-kMGYteh1CYm:b-vpawim) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L503)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If the input has duplicate rows, then we'll delete the same row multiple times - which is a waste of work. I'm not sure it'll necessary corrupt indexes, but the delete operator has only every operated on distinct rows, so it's safest to follow the pattern.

The join you've added can duplicate rows in the target table, so we'll need to eliminate those duplicates. See the distinct-on operator we build for `UPDATE .. FROM` — you can do something similar for `DELETE .. USING`.
</blockquote></details>

Done. Code to build `distinct-from` added to `mutation_builder.go`
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 754 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6U1ys7LnAmGApE1iU:-NE81d-5APhqmTPrkyj3:b-p3gjqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L754)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is a check constraint, not a partial index.
</blockquote></details>

Done. Test case maintained but comment changed and test to check partial indexes added below.

**Review by faizaanmadhani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6ObEoAAywgZ2kGh2Z:-NEBuDwp8c5sN__o-NZH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac97aa1e983e4e55c78c405a79a3e0a6c3bde51/pkg/sql/opt/optbuilder/mutation_builder.go#L446)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm alarmed that prior to this commit we called `setFetchColIDs` with some potential non-fetch columns... I guess that didn't cause any problems. Regardless, moving `setFetchColIDs` up looks more correct to me. :+1: 
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 490 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6QZj93JMwHpBW74aG:-NE82hOr5u7ryC2zvBTs:bs10184) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L490)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Some tests to add:

- test the validateJoinTableNames path by putting the same table in the USING clause multiple times
- 
</blockquote></details>

Done. This test is added below (second last test in file).

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r4, 17 of 17 files at r9, 5 of 5 files at r10, 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani and @michae2)

___
*[`-- commits` line 34 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHw-dpAQC48lY-Ab32):*
nit: cockroachdb => CockroachDB
___
*[`pkg/sql/delete.go` line 165 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHwXEzBP3pSLP56yBl:-NEHwXEzBP3pSLP56yBm:b-yiqt8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/delete.go#L165)):*
> ```Go
> 	var pm row.PartialIndexUpdateHelper
> 	if n := len(d.run.td.tableDesc().PartialIndexes()); n > 0 {
> 		offset := d.run.partialIndexDelValsOffset + d.run.numPassthrough
> ```

To keep `d.run.partialIndexDelValsOffset` true to its name, I think we should update it's value here instead: https://github.com/cockroachdb/cockroach/blob/3f87f2f6f18ac7f82f39929d7fd77bdec1735974/pkg/sql/opt_exec_factory.go#L1699

And the comment for it here shuld be updated too: https://github.com/cockroachdb/cockroach/blob/961e66f87350325fc2db0161fc1a8ccb9a8d8be2/pkg/sql/delete.go#L52-L54
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 487 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHu2G1-cUNDODPz2XU:-NEHu2G1-cUNDODPz2XV:bb7uqtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb79777c8e9b7d3c670fb6bfbb4e4c8ce5ff9bc/pkg/sql/opt/optbuilder/mutation_builder.go#L487)):*
> ```Go
> 		}
> 
> 		if !pkCols.Empty() {
> ```

nit: A table must have PK columns, so this check is unnecessary.
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 338 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHy0jM4GNT-qLSWWHV:-NEHy0jM4GNT-qLSWWHW:b-rva119) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L338)):*
> ```
> 5
> 
> # Test that USING works
> ```

nit: add period to the end of this comment and the ones below
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 345 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHy3BC1CmGfdbvjrSO:-NEHy3BC1CmGfdbvjrSP:b9r06zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L345)):*
> ```
>     b STRING,
>     c INT
> );
> ```

nit: for single-statements in `statement ok`, there is no need for the `;` at the end. I don't think we are terribly consistent, so it's up to you, but I think for the most part we leave it off.
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 366 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHyXF63MaVH0-FNwef:-NEHyXF63MaVH0-FNweg:bd7vs4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L366)):*
> ```
> );
> 
> statement count 4
> ```

nit: `statement ok` is fine here and below IMO - you're not testing INSERT so you don't need additional assertions 
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 376 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHykL77NrGsSePilQp:-NEHykL77NrGsSePilQq:bdps1wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L376)):*
> ```
> 
> query ITI rowsort
> SELECT * FROM u_a;
> ```

nit: you can remove this SELECT test
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 383 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHyg2H6ci6KvMJXAwl:-NEHyg2H6ci6KvMJXAwm:biz1qyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L383)):*
> ```
> 4  d  40
> 
> #Test a join with a filter
> ```

nit: space after `#`
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 462 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEI-9c77OfH7NIi_Ycx:-NEI-9c77OfH7NIi_Ycy:bmyppoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L462)):*
> ```
> # Test aliased table names, ORDER BY and LIMIT where ORDER BY references the target
> # table.
> query ITIIT rowsort
> ```

nit: remove `rowsort` since you have the `ORDER BY` in the query
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 483 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEI-Mlw7xUq1F5Zl9wi:-NEI-Mlw7xUq1F5Zl9wj:b-prqbjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L483)):*
> ```
> 
> query ITI rowsort
> SELECT * FROM u_a;
> ```

nit: this looks redundant
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 528 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEI-TSN21aiBMF-lD-w:-NEI-TSN21aiBMF-lD-x:b-ndkupo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L528)):*
> ```
> CREATE TABLE pindex (
>   a DECIMAL (10, 2),
>   CHECK (a > 0)
> ```

There's no partial index here, and no need for the check constraint.
___
*[`pkg/sql/opt/exec/explain/testdata/gists` line 746 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHzcDEDpE2pELDUqoa:-NEHzcDEDpE2pELDUqob:b8poodf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/opt/exec/explain/testdata/gists#L746)):*
> ```
> opt
> DELETE FROM foo WHERE a = 1
> ----
> ```

nit: this looks like left-over from testing that you can remove
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 754 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6U1ys7LnAmGApE1iU:-NEHv1uJ2JUHhLywrVkj:b84id13) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L754)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Done. Test case maintained but comment changed and test to check partial indexes added below.
</blockquote></details>

CHECK constraints aren't checked during deletes, so you can remove the `CHECK`, add the parital index directly into this CREATE TABLE, and remove the test directly below this one. I'd update the table name to match too.
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 800 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHuemp61mu2IGgOal7:-NEHuemp61mu2IGgOal8:b-k71pxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb79777c8e9b7d3c670fb6bfbb4e4c8ce5ff9bc/pkg/sql/opt/optbuilder/testdata/delete#L800)):*
> ```
> DELETE FROM abcde AS foo USING xyz AS bar WHERE bar.y > 0 ORDER BY foo.a DESC LIMIT 5;
> ----
> error (42P10): SELECT DISTINCT ON expressions must match initial ORDER BY expressions
> ```

This should succeed, shouldn't it?
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 1106 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHv_Zd7ZsWgtTuyqY2:-NEHv_Zd7ZsWgtTuyqY3:bnay6gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb79777c8e9b7d3c670fb6bfbb4e4c8ce5ff9bc/pkg/sql/opt/optbuilder/testdata/delete#L1106)):*
> ```
>       │              └── column2:14
>       └── projections
>            └── h:9 > 3 [as=partial_index_del1:15]
> ```

It'd be good to add a test where the target table has a compound primary key (more than 1 PK column, e.g. `CREATE TABLE (h INT, i INT, j INT, PRIMARY KEY (h, i))`) to ensure that the distinct-on groups by _all_ the PK columns.

**Comment by faizaanmadhani** [comment]
*[`pkg/sql/opt/optbuilder/testdata/delete` line 800 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHuemp61mu2IGgOal7:-NEIQHzs0Ow7nmjkJZMn:b8qnir4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb79777c8e9b7d3c670fb6bfbb4e4c8ce5ff9bc/pkg/sql/opt/optbuilder/testdata/delete#L800)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This should succeed, shouldn't it?
</blockquote></details>

(I think) It should. We have a similar logictest that also uses the target table in the ORDER BY that passes, so this is confusing.

After some digging, I figured out that this only happens if we're ordering on the non-primary key column of the target table while having a USING. Existing functionality does allow to do an ORDER BY with a non-primary key column in `DELETE` statements without `USING` clauses.

Similarly, if we check `UPDATE ... FROM` doing an ORDER BY with a column of a table that is not a primary key, this works so this test should pass.

**Review by faizaanmadhani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/delete.go` line 165 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHwXEzBP3pSLP56yBl:-NEMEZG6EW27kOMjctXp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/delete.go#L165)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

To keep `d.run.partialIndexDelValsOffset` true to its name, I think we should update it's value here instead: https://github.com/cockroachdb/cockroach/blob/3f87f2f6f18ac7f82f39929d7fd77bdec1735974/pkg/sql/opt_exec_factory.go#L1699

And the comment for it here shuld be updated too: https://github.com/cockroachdb/cockroach/blob/961e66f87350325fc2db0161fc1a8ccb9a8d8be2/pkg/sql/delete.go#L52-L54
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 528 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEI-TSN21aiBMF-lD-w:-NEM7rCd4pzVcYgrPY23:b-ux247h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c63889fee5fb625cbc326eb1a1c4afcd6a30d58/pkg/sql/logictest/testdata/logic_test/delete#L528)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

There's no partial index here, and no need for the check constraint.
</blockquote></details>

Yup. I changed it to a partial index and modified the test for it
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 754 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NE6U1ys7LnAmGApE1iU:-NEM8BUt11eThi-u1nzE:b-ki2tdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bfc308fa28efd1adae5da19f062eea6032502a7/pkg/sql/opt/optbuilder/testdata/delete#L754)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

CHECK constraints aren't checked during deletes, so you can remove the `CHECK`, add the parital index directly into this CREATE TABLE, and remove the test directly below this one. I'd update the table name to match too.
</blockquote></details>

Done. Removed the check constraint test below and added a partial index test using table name `pindex`
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 800 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEHuemp61mu2IGgOal7:-NEM8fWFDJg3EOzCUom7:bvfte1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb79777c8e9b7d3c670fb6bfbb4e4c8ce5ff9bc/pkg/sql/opt/optbuilder/testdata/delete#L800)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

(I think) It should. We have a similar logictest that also uses the target table in the ORDER BY that passes, so this is confusing.

After some digging, I figured out that this only happens if we're ordering on the non-primary key column of the target table while having a USING. Existing functionality does allow to do an ORDER BY with a non-primary key column in `DELETE` statements without `USING` clauses.

Similarly, if we check `UPDATE ... FROM` doing an ORDER BY with a column of a table that is not a primary key, this works so this test should pass. 


</blockquote></details>

Resolved offline. While this should ideally succeed this failure happens when we do ORDER BY on non-primary key columns in a USING in tables when primary keys are present . This is related to this issue that's also present in `UPDATE ... FROM`: #89817

**Review by mgartner — APPROVED** [review]
Great work! :lgtm: just left one test suggestion.

> Reviewed 12 of 12 files at r12, 9 of 10 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-:-NEbYS1L8klADdAF4kI0:b-8hokux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @faizaanmadhani, @michae2, and @rytaft)

___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 527 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/88974#-NEbY2qjCbhRjfRK9uEz:-NEbY2qjCbhRjfRK9uF-:b9b2dvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/62634ff47ef247056e2b7b5e044957eefb47ce3a/pkg/sql/logictest/testdata/logic_test/delete#L527)):*
> ```
> 3.00
> 4.00
> 8.00
> ```

nit: add a test for `SELECT a FROM pindex@pindex_a_idx WHERE a > 3` to verify that scanning the partial index yields the same results as the full table scan here.

**Comment by faizaanmadhani** [comment]
TFTR!!!! 🎉 

bors r+

**Pull request merged**
