### PR TITLE
kvserver,storepool: misc rebalance logging improvements

### LINKED ISSUE #102812: kvserver: include rebalance objective in store rebalancer logging
**Is your feature request related to a problem? Please describe.**
We enabled dual rebalancing objectives in https://github.com/cockroachdb/cockroach/issues/90582, where the store rebalancer will either look at QPS or CPU. The current objective can be found by checking the cluster settings and checking the cockroach.log if the value set by the cluster setting is unsupported:

https://github.com/cockroachdb/cockroach/blob/918923738a73c39986c163465edb70e9af2c49b8/pkg/kv/kvserver/rebalance_objective.go#L251

Or by inspecting which load dimension's max threshold is equal to the mean e.g. below shows `cpu` set:

```
[T1,n5,s9,store-rebalancer] 736  local load ‹(queries-per-second=1261.1 cpu-per-second=161ms)› is below max threshold ‹(queries-per-second=1515.4 cpu-per-second=234ms)› mean=‹(queries-per-second=1515.4 cpu-per-second=184ms)›; no rebalancing needed
```

**Describe the solution you'd like**
Log the current objective, as seen by the store rebalancer in the ambient ctx or somewhere otherwise visible.

Jira issue: CRDB-27665

### PR DESCRIPTION
**Pull request by kvoli**
The store list string returned the mean leases, ranges and
queries-per-second float values without limiting the number of decimal
places. This led to log lines with needlessly long decimals:

`avg-ranges=40.66666666666667... avg-leases=10.166666666666666...`

This PR updates the store list string formatting to 2 decimal
places for float values.

Previously, the easiest method of determining the current rebalance
objective from logs was to view the cluster setting and check for
logging indicating a mixed version cluster - this was cumbersome.

This PR annotates the ctx in the store rebalancer loop with an
additional tag: `obj`. The `obj` tag indicates the current rebalance
objective, either `cpu` or `qps` currently.

resolves: https://github.com/cockroachdb/cockroach/issues/102812

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/allocator/storepool/store_pool.go` line 1087 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102825#-NUwAPNr8tGYAUKqOPsx:-NUwAPNr8tGYAUKqOPsy:b5idext) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da1ceac8682c2b2b08a8957d93d526076edc100/pkg/kv/kvserver/allocator/storepool/store_pool.go#L1087)):*
> ```Go
> }
> 
> func (sl StoreList) String() string {
> ```

Could I suggest this gets converted to a new SafeFormat method; then String re-implemented from there.

see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability#API-Basics

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102825#-:-NV-eiLu4jIwhCZfthi-:b-80sls6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @kvoli)

___
*[`pkg/kv/kvserver/allocator/storepool/store_pool.go` line 1087 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102825#-NUwAPNr8tGYAUKqOPsx:-NV-eTTYEVreWpoF0kck:bjjal82) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da1ceac8682c2b2b08a8957d93d526076edc100/pkg/kv/kvserver/allocator/storepool/store_pool.go#L1087)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Could I suggest this gets converted to a new SafeFormat method; then String re-implemented from there.

see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability#API-Basics
</blockquote></details>

Ack - I've opened https://github.com/cockroachdb/cockroach/issues/102948 for this issue. No logging here implements the SafeFormat method - it would be better do this in one go so we don't miss anything.

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Pull request merged**
