### PR TITLE
sql: enable the use of EXPLAIN as a data source.

### PR DESCRIPTION
**Pull request by knz**
This patch introduces a new syntax which enables SQL queries on the
output of EXPLAIN. For example, the plan depth can be computed like
this:

```sql
SELECT MAX(level) FROM [EXPLAIN SELECT * FROM kv ORDER BY v]
```

This will be used to test/verify optimizations.

Incidentally, the addition of this feature enables clients to emulate
the output of the `INDENT` option fully in SQL, removing the need for
a special case in the EXPLAIN code:

```sql
SELECT repeat(' ', level*3)
       || CASE field
          WHEN '' THEN '-> ' || type
	  ELSE         '   ' || field || ': ' || description
	  END
       AS indent,
       columns,
       ordering
  FROM [EXPLAIN(VERBOSE) SELECT * FROM kv ORDER BY v];
+-------------------------------+---------+-----------+
|            indent             | columns | ordering  |
+-------------------------------+---------+-----------+
| -> select                     | (k, v)  | +v        |
| ‌   -> sort                    | (k, v)  | +v        |
| ‌      order: +v               |         |           |
| ‌      -> render/filter        | (k, v)  | +k,unique |
| ‌         render 0: t.kv.k     |         |           |
| ‌         render 1: t.kv.v     |         |           |
| ‌         -> scan              | (k, v)  | +k,unique |
| ‌            table: kv@primary |         |           |
| ‌            spans: ALL        |         |           |
+-------------------------------+---------+-----------+
(9 rows)
```

The INDENT code may thus be removed by a subsequent commit, pending
the addition of a suitable shortcut in the CLI shell.

(Will be used to test the work around #10633)

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12637)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__pQ8ni_NfFjzyPRXn:-K__pQ8ni_NfFjzyPRXo:b-pouldt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/data_source.go#L295)):*
> ```Go
> }
> 
> var explainTableName = parser.TableName{TableName: parser.Name("explain")}
> ```

hmm what's up with this name? Does it mean that the outer query can say `explain.indent`, for example? Do we need this name?

---

*[pkg/sql/parser/explain.go, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__oj-6qryeMPon-9fz:-K__oj-6qryeMPon-9g-:b624r5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/explain.go#L25)):*
> ```Go
> 	Options   []string
> 	Statement Statement
> 	Enclosed  bool
> ```

please comment

---

*[pkg/sql/parser/select.go, line 219 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__p7PjasC0oYxvOalK:-K__p7PjasC0oYxvOalL:bvxvpxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/select.go#L219)):*
> ```Go
> func (*JoinTableExpr) tableExpr()    {}
> func (*FuncExpr) tableExpr()         {}
> func (*Explain) tableExpr()          {}
> ```

prolly worth explaining here how Explain is a `tableExpr`.

---

*[pkg/sql/parser/sql.y, line 2910 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__owprMGZj8eXFqwST:-K__owprMGZj8eXFqwSU:bpmh2nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/sql.y#L2910)):*
> ```Yacc
>     $$.val = &AliasedTableExpr{Expr: $2.tblExpr(), Ordinality: $4.bool(), As: $5.aliasClause() }
>   }
> | '[' EXPLAIN  explainable_stmt ']' opt_ordinality opt_alias_clause
> ```

do we need the `[ ... ]` ? This syntax is not used elsewhere, is it? Can it at least be regular parens?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-:-K__paiB-5Yy5vTTaeqh:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__pQ8ni_NfFjzyPRXn:-K_aWIivSxtXGzFnozC9:bkt5f0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/data_source.go#L295)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

hmm what's up with this name? Does it mean that the outer query can say `explain.indent`, for example? Do we need this name?
</blockquote></details>

Yeah no not really. I agree if the user really wants a name they can use `AS`. I dropped it.

---

*[pkg/sql/parser/explain.go, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__oj-6qryeMPon-9fz:-K_aWiHqrS0kwvpd-nlK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/explain.go#L25)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment
</blockquote></details>

Done.

---

*[pkg/sql/parser/select.go, line 219 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__p7PjasC0oYxvOalK:-K_aWxwJh6Fs7i3-kNCa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/select.go#L219)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

prolly worth explaining here how Explain is a `tableExpr`.
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 2910 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__owprMGZj8eXFqwST:-K_aWyfA7bpwowtvyRBC:b-wjaexz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/sql.y#L2910)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do we need the `[ ... ]` ? This syntax is not used elsewhere, is it? Can it at least be regular parens?
</blockquote></details>


Two reasons: 1) it doesn't work otherwise 2) it carries useful semantic information.

1) No it can't because then the grammar is ambiguous.

There are two problems, one easier to explain than the other.
The easy one, when explain options are specified: when you write `(EXPLAIN (verbose) ...`, at the point the parser encounters the 2nd parenthesis it doesn't know whether to shift on the EXPLAIN rule or reduce on a function call expression (if e.g. a function named "explain" existed).

The more difficult one is that without explain options the rule becomes ambiguous because the statement keywords are not special and the grammar rule then overlaps with the table alias syntax with an optional WITH clause. If you want details just try it out and check the detailed yacc log.

Long story short, "open parenthesis followed by EXPLAIN followed by either open parenthesis or non-special keyword" will fail no matter what in a non-fixable way with a LALR(1) parser generator.

2) I think it is useful to denote visually that EXPLAIN is special for another reason: the statement that appears after EXPLAIN *is not executed* as a regular data source. This differs from all other uses of statement-looking things inside a FROM clause (namely SELECT and set-generating functions for now). We could thus view these square brackets as a denotation to "escape" a statement. Even if the user doesn't know about this EXPLAIN syntax, by seeing this they are informed "this is special and is definitely not standard".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637)*

**Comment by knz** [comment]
TFYR btw

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 2910 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__owprMGZj8eXFqwST:-K_adHicAOfye4yn3EDZ:b-l9rrvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/sql.y#L2910)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>


Two reasons: 1) it doesn't work otherwise 2) it carries useful semantic information.

1) No it can't because then the grammar is ambiguous.

There are two problems, one easier to explain than the other.
The easy one, when explain options are specified: when you write `(EXPLAIN (verbose) ...`, at the point the parser encounters the 2nd parenthesis it doesn't know whether to shift on the EXPLAIN rule or reduce on a function call expression (if e.g. a function named "explain" existed).

The more difficult one is that without explain options the rule becomes ambiguous because the statement keywords are not special and the grammar rule then overlaps with the table alias syntax with an optional WITH clause. If you want details just try it out and check the detailed yacc log.

Long story short, "open parenthesis followed by EXPLAIN followed by either open parenthesis or non-special keyword" will fail no matter what in a non-fixable way with a LALR(1) parser generator.

2) I think it is useful to denote visually that EXPLAIN is special for another reason: the statement that appears after EXPLAIN *is not executed* as a regular data source. This differs from all other uses of statement-looking things inside a FROM clause (namely SELECT and set-generating functions for now). We could thus view these square brackets as a denotation to "escape" a statement. Even if the user doesn't know about this EXPLAIN syntax, by seeing this they are informed "this is special and is definitely not standard".


</blockquote></details>

ack. Maybe put a link to this explanation in the grammar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-:-K_adN7Ml_EoHFXeDrnD:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/parser/sql.y, line 2910 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637#-K__owprMGZj8eXFqwST:-K_ajxGSYiSSlM0WlP0_:b-8x1l1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6b04708b676407ae4107f06dc56634b929d5a0/pkg/sql/parser/sql.y#L2910)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ack. Maybe put a link to this explanation in the grammar.
</blockquote></details>

Good idea; done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12637)*

**Pull request merged**
