### PR TITLE
sql: split eventTxnFinish to avoid payload allocation

### PR DESCRIPTION
**Pull request by RaduBerinde**
The eventTxnFinish FSM event has a payload that contains a flag that
indicates commit or abort. This payload is allocated on the heap.

This change splits this event into two separate events, so that the
payload is no longer necessary. The explicit handling of the two
events also makes the possible transitions more clear (e.g. we don't
have to handle the "committed" event in stateAborted).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I'm not sure all the state transitions are possible, let me know if I can remove any (in particular I wasn't sure about CommitWait->txnFinishAborted)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56155)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/conn_executor_exec.go, line 1179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-ML9LDkC3KiTv1Kcm1pM:-ML9LDkC3KiTv1Kcm1pN:bh3xikw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c53c7eae656f358d84385167a54f9dc5970b0/pkg/sql/conn_executor_exec.go#L1179)):*
> ```Go
> 		// get a COMMIT in state Aborted.
> 		res.ResetStmtType((*tree.CommitTransaction)(nil))
> 		return eventTxnFinishAborted{}, nil
> ```

I don't like the use of `eventTxnFinishAborted{}` here. I guess technically before this patch `eventTxnFinishPayload{commit: false}` did not necessarily mean an abort.
The code here used to be `eventTxnFinishPayload{commit: false}` and at some point I've made it `commit: true`. I wish I had left a comment explaining why... The PR doing that didn't touch `txnStateTransitionsApplyWrapper()` - which is the thing that consumes the the `txnEvents` which are produced by the FSM in reaction to the events fed into it. So I wonder why I did it... I don't think it matters since the extra things that `txnStateTransitionsApplyWrapper()` does for `txnCommit` instead of `txnRollback` I think don't apply when we're in `stateCommitWait` - because we've already done `resetExtraTxnState()` when we've entered `stateCommitWait`
https://github.com/cockroachdb/cockroach/blob/3639ec53c03c9606f187577d684712c6e0bc9427/pkg/sql/conn_fsm.go#L332
(meaning, we've already produced a `eventTxnFinishPayload{commit: true}` prior).

So long story short, I'd use `eventTxnFinishCommitted` here, and leave a comment saying that it's a duplicate of the one that we've produced before - and as such it is a no-op.
___
*[pkg/sql/conn_fsm.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-ML9IUcc1fWsuJSNgXFj:-ML9IUcc1fWsuJSNgXFk:bqgc3ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c53c7eae656f358d84385167a54f9dc5970b0/pkg/sql/conn_fsm.go#L251)):*
> ```Go
> 		},
> 		eventTxnFinishAborted{}: {
> 			Description: "ROLLBACK, or after a statement running as an implicit txn",
> ```

nit: "ROLLBACK, or after a statement running as an implicit txn fails"
___
*[pkg/sql/conn_fsm.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-ML9ON1cCek8d7_A8S0G:-ML9ON1dCgLkboVbMtUS:b-zzssm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c53c7eae656f358d84385167a54f9dc5970b0/pkg/sql/conn_fsm.go#L412)):*
> ```Go
> 			},
> 		},
> 		eventTxnFinishAborted{}: {
> ```

given how the patch was written, the `eventTxnFinishCommitted` was never triggered here, right?
But as I was saying, I think we should only keep that one, and get rid of handling `eventTxnFinishAborted{}` here.
___
*[pkg/sql/conn_fsm.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-ML9Ij6DCOCOYg4M9PJF:-ML9Ij6DCOCOYg4M9PJG:b-thzct7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c53c7eae656f358d84385167a54f9dc5970b0/pkg/sql/conn_fsm.go#L467)):*
> ```Go
> // finishTxn finishes the transaction. It also calls setAdvanceInfo().
> // The argument should be txnCommit or txnRollback.
> func (ts *txnState) finishTxn(ev txnEvent) error {
> ```

care to assert or make the two events implement some interface?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-:-ML9WBfeEeFaRF2RgP6W:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor_exec.go, line 1179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-ML9LDkC3KiTv1Kcm1pM:-ML9UL1Q6MtYZu0bLwjZ:b-95kdzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c53c7eae656f358d84385167a54f9dc5970b0/pkg/sql/conn_executor_exec.go#L1179)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't like the use of `eventTxnFinishAborted{}` here. I guess technically before this patch `eventTxnFinishPayload{commit: false}` did not necessarily mean an abort.
The code here used to be `eventTxnFinishPayload{commit: false}` and at some point I've made it `commit: true`. I wish I had left a comment explaining why... The PR doing that didn't touch `txnStateTransitionsApplyWrapper()` - which is the thing that consumes the the `txnEvents` which are produced by the FSM in reaction to the events fed into it. So I wonder why I did it... I don't think it matters since the extra things that `txnStateTransitionsApplyWrapper()` does for `txnCommit` instead of `txnRollback` I think don't apply when we're in `stateCommitWait` - because we've already done `resetExtraTxnState()` when we've entered `stateCommitWait`
https://github.com/cockroachdb/cockroach/blob/3639ec53c03c9606f187577d684712c6e0bc9427/pkg/sql/conn_fsm.go#L332
(meaning, we've already produced a `eventTxnFinishPayload{commit: true}` prior).

So long story short, I'd use `eventTxnFinishCommitted` here, and leave a comment saying that it's a duplicate of the one that we've produced before - and as such it is a no-op.

</blockquote></details>

As we discussed offline, I changed to `eventTxnFinishCommitted` and changed the handling of that even in the CommitWait state to pass `noEvent`.
___
*[pkg/sql/conn_fsm.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-ML9ON1cCek8d7_A8S0G:-ML9U-KN6g5hUiScjKrt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c53c7eae656f358d84385167a54f9dc5970b0/pkg/sql/conn_fsm.go#L412)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

given how the patch was written, the `eventTxnFinishCommitted` was never triggered here, right?
But as I was saying, I think we should only keep that one, and get rid of handling `eventTxnFinishAborted{}` here.
</blockquote></details>

Done.
___
*[pkg/sql/conn_fsm.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-ML9Ij6DCOCOYg4M9PJF:-ML9W8QI0XjYe0Qu6g48:bjk9uar) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c53c7eae656f358d84385167a54f9dc5970b0/pkg/sql/conn_fsm.go#L467)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

care to assert or make the two events implement some interface?
</blockquote></details>

I removed the restriction now that we're also passing `noEvent`

**Review by andreimatei — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-:-MLA8htO1ZSr9ZlRenKj:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/conn_fsm.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-MLA8m4ID0gbkJHpmste:-MLA8m4ID0gbkJHpmstf:b-ao1w6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/849b3cafa3e91a3c41c9da9d40f85bdf18f36023/pkg/sql/conn_fsm.go#L410)):*
> ```Go
> 			Next:        stateNoTxn{},
> 			Action: func(args fsm.Args) error {
> 				return args.Extended.(*txnState).finishTxn(noEvent)
> ```

pls add a comment about how a `txnCommit` event has been previously generated when we entered `stateCommitWait`

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56155)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_fsm.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56155#-MLA8m4ID0gbkJHpmste:-MLAlJvj3U4tj9vqNgMR:b-qqx0w8) ([raw file](https://github.com/cockroachdb/cockroach/blob/849b3cafa3e91a3c41c9da9d40f85bdf18f36023/pkg/sql/conn_fsm.go#L410)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls add a comment about how a `txnCommit` event has been previously generated when we entered `stateCommitWait`
</blockquote></details>

Done. TFTR!

**Pull request merged**
