### PR TITLE
colfetcher: minor cleanup and improvement

### PR DESCRIPTION
**Pull request by yuzefovich**
**colfetcher: fix slices' reuse and fix comments**

This commit fixes the reuse of some slices that we kept the references
to but forgot to set properly when overwriting the table information.
Additionally, in order to make it easier to see whether all slices are
correctly set, this commit reorders the assignment order to match the
order in which the fields are defined.

This commit additionally clarifies things in several places that `cols`
refers to all columns of the table (that's what `colDescriptors`
argument to the cFetcher describes). It also removes some of the
duplicated code when creating a vectorized index join (a method was
refactored to be reused but was never used in the second place).

Release note: None

**colfetcher: simplify the population of the table args**

Previously, when initializing the cFetcher we were doing some work
twice: we would populate a set of columns in the table first to get the
types and the column index map only to discard it right away and
populate similar info again by calling `row.FetcherTableArgs.InitCols`.
This commit removes this inefficiency.

It also removes the duplicated slices of types and column descriptors
and refactors some fields of the cFetcher into a separate struct that
is pooled. Note that I extracted the table args struct that was
previously shared between the row fetcher and the cfetcher into
a separate struct because the follow-up work will be changing the
meaning of the fields in that struct.

Release note: None

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71356)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

___
*[pkg/sql/colfetcher/cfetcher.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71356#-Mm_hnju6-FRN1MPzB9a:-Mm_hnju6-FRN1MPzB9b:bjqpex5) ([raw file](https://github.com/cockroachdb/cockroach/blob/98978a5efd731625b3429d49fd3b3f0e65877ca4/pkg/sql/colfetcher/cfetcher.go#L274)):*
> ```Go
> 	// This is only false if there are no needed columns, the table has no
> 	// interleave children, and the tracing is not enabled.
> 	mustDecodeIndexKey bool
> ```

Why were some fields moved into cFetcherArgs, but some of them (mainly, `mustDecodeIndexKey`, `mvccDecodeStrategy`) were not?
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 212 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71356#-Mm_gtzuDwZKcMO2hHp1:-Mm_gtzuDwZKcMO2hHp2:b-5xa1dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/98978a5efd731625b3429d49fd3b3f0e65877ca4/pkg/sql/colfetcher/colbatch_scan.go#L212)):*
> ```Go
> 	invertedColumn := tabledesc.FindInvertedColumn(table, spec.InvertedColumn)
> 	tableArgs, err := populateTableArgs(
> 		ctx, flowCtx, evalCtx, table, table.ActiveIndexes()[spec.IndexIdx],
> ```

Should we check that `spec.IndexIdx` is within bounds of `table.ActiveIndexes()`?

**Review by cucaroach — COMMENTED** [review]
:LGTM: but I have mixed feelings about the pooling stuff and whether the gains justify the increased complexity.   

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71356#-:-MmbyKfX5vo8ZiX2xLun:b8xpa8l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
I believe our thinking about pooling is that it is reasonable to do it when on the hot path. In this case the code is on the hot path, so added complexity is justified IMO.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71356#-:-MmcrvzHEMK-989yqhN-:bu7g2hr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @mgartner, and @rharding6373)

___
*[pkg/sql/colfetcher/cfetcher.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71356#-Mm_hnju6-FRN1MPzB9a:-Mmcpel6CHPUR6jqgYlD:butmjen) ([raw file](https://github.com/cockroachdb/cockroach/blob/98978a5efd731625b3429d49fd3b3f0e65877ca4/pkg/sql/colfetcher/cfetcher.go#L274)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why were some fields moved into cFetcherArgs, but some of them (mainly, `mustDecodeIndexKey`, `mvccDecodeStrategy`) were not?
</blockquote></details>

My thinking when choosing which fields to move into `cFetcherArgs` was as follows: if a particular field comes directly from the closer, then we'll move it into the new struct (e.g. `reverse` is given to us by the caller and the value of that field will never be modified); however, if we need to perform some calculation to get the value for the field, I left it in `cFetcher` (e.g. `mustDecodeIndexKey` depends on which columns actually need to be fetcher and whether there are interleaved tables, this determination is done in `cFetcher.Init`, and the caller cannot set it before `cFetcher.Init` is called).
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 212 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71356#-Mm_gtzuDwZKcMO2hHp1:-MmcrFS34GYIefZ0Grrk:b3wbzxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/98978a5efd731625b3429d49fd3b3f0e65877ca4/pkg/sql/colfetcher/colbatch_scan.go#L212)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should we check that `spec.IndexIdx` is within bounds of `table.ActiveIndexes()`?
</blockquote></details>

Hm, we don't have too because the vectorized flow setup is wrapped with `colexecerror.CatchVectorizedRuntimeError` panic catcher, so even if we get an index out of bounds panic, it'll be converted into an error. I decided to remove the check in the index join code path for symmetry since I think these checks were copy-pasted from the row-by-row engine where we don't have the panic-catcher protection.

IMO it's ok to not have these checks here since having `spec.IndexIdx` that is out of bounds of `table.ActiveIndexes` is an assertion error and should never occur.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71356#-:-MmctqLq8IgeV5RGPsaw:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @mgartner)

**Pull request merged**
