### PR TITLE
sql: persist multiregion data to database descriptor

### PR DESCRIPTION
**Pull request by otan**
sql: display survival goal and regions in SHOW DATABASES

Populating crdb_internal.databases is a pre-cursor to SHOW REGIONS FROM
DATABASE <x>, so here we are.

Release note (sql change): SHOW DATABASES and crdb_internal.databases
now displays all regions as well as survival goals for a given database.

sql: persist CREATE DATABASE ... REGIONS / SURVIVE options

These are now persisted in a RegionConfig field on the database
descriptor. If we decide ENUM as the source of truth, we can denormalize
these at a later stage.

Release note: None

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Nice work here!  Just a couple of questions included below.  

Extremely minor nit about the PR text - The order in which you talk about these commits in the PR seem backwards.  I'd think we'd want to talk about persisting the information before we talk about showing it.

> Reviewed 6 of 6 files at r1, 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-:-MMXR9zP-99I9AbCuoYo:b4d5eep)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @otan)

___
*[pkg/sql/crdb_internal.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaFWPO-_eR4u3xnfO_:-MMaFWPO-_eR4u3xnfOa:b133f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/76ec712d5b3c7f31e90c36aa895e41b6bff58354/pkg/sql/crdb_internal.go#L238)):*
> ```Go
> 				switch db.RegionConfig.SurvivalGoal {
> 				case descpb.SurvivalGoal_ZONE_FAILURE:
> 					survivalGoal = "survive zone failure"
> ```

Seems wordy.  Can we not just go with "zone" and "region"? 
___
*[pkg/sql/crdb_internal.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaFh0k-TysjBpJhJiV:-MMaFh0k-TysjBpJhJiW:bv112a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/76ec712d5b3c7f31e90c36aa895e41b6bff58354/pkg/sql/crdb_internal.go#L239)):*
> ```Go
> 				case descpb.SurvivalGoal_ZONE_FAILURE:
> 					survivalGoal = "survive zone failure"
> 				case descpb.SurvivalGoal_REGION_FAILURE:
> ```

Nit: I'd think that more people would be interested in the regions (as opposed to the survival goal).  Can we put regions first and survival at the end?
___
*[pkg/sql/descriptor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaDg2_4clkRiSC-TPY:-MMaDg2a0jG0nrt-YMJm:bew1plg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/descriptor.go#L106)):*
> ```Go
> 				return nil, false, err
> 			}
> ```

Out of curiosity, why the removal of the comment here?
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMa417_95s68cpKqGCg:-MMa417_95s68cpKqGCh:b-hxn7he) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/catalog/dbdesc/database_desc.go#L55)):*
> ```Go
> // NewInitialOptionDatabaseRegionConfig is an option allowing an optional
> // regional configuration to be set on the database descriptor.
> func NewInitialOptionDatabaseRegionConfig(
> ```

While I can understand the motivation for doing things this way, and it's quite a clever way of solving this problem, it seems a bit gross to me for a couple of reasons:

1) NewInitialOptionDatabaseRegionConfig is just a really long name
2) It makes the code more difficult to understand to have to trace down what each of these NewInitial functions are doing.
3) We're adding many lines of code to save one assignment in NewInitialWithPrivileges

Seeing as how it's just privileges and regions now, I'd think it would be easier to have all of it done in a single function and not build this options infrastructure just yet.  If we had more than 3 of these, I'd probably change my mind, but I don't know that we have another one on the horizon.
___
*[pkg/sql/catalog/descpb/structured.proto, line 1064 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaCSw88l3FW6RVTtGB:-MMaCSw88l3FW6RVTtGC:bfofxxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/catalog/descpb/structured.proto#L1064)):*
> ```protobuf
> message DatabaseRegionConfig {
>   option (gogoproto.equal) = true;
> ```

Do we need the primary region here?  Or is that coming in a subsequent PR?
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMXVno201TUTye7_jaJ:-MMXVno201TUTye7_jaK:br9j0p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/logictest/testdata/logic_test/multiregion#L12)):*
> ```
> 
> statement ok
> CREATE DATABASE region_test_db REGION "test1" SURVIVE ZONE FAILURE
> ```

I didn't realize that we are currently supporting both `REGION` and `REGIONS`.  Will this show up in the help and documentation?  If so, I think we might want to nix `REGION`.

**Review by nvb — COMMENTED** [review]
Nice! This all looks really good.

> Reviewed 6 of 6 files at r1, 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-:-MMbnra8625i2A0XNl_4:b-pmakjc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @otan)

___
*[pkg/sql/crdb_internal.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaFh0k-TysjBpJhJiV:-MMbnMWw3TBG8Kwk4ce3:bwaswix) ([raw file](https://github.com/cockroachdb/cockroach/blob/76ec712d5b3c7f31e90c36aa895e41b6bff58354/pkg/sql/crdb_internal.go#L239)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: I'd think that more people would be interested in the regions (as opposed to the survival goal).  Can we put regions first and survival at the end?
</blockquote></details>

+1. I'm also wondering whether we should make `survival_goal` nullable and populate its value as NULL for databases with no active regions.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56880)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/sql/crdb_internal.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaFWPO-_eR4u3xnfO_:-MMlav38ELPXQ75aVVmI:bh3cmr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/76ec712d5b3c7f31e90c36aa895e41b6bff58354/pkg/sql/crdb_internal.go#L238)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Seems wordy.  Can we not just go with "zone" and "region"? 
</blockquote></details>

Done. I think it's a little less clear under "survival goal" but not fussed too much. Easy to change later.
___
*[pkg/sql/descriptor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaDg2_4clkRiSC-TPY:-MMlbMjF5_rR4qRi8Sha:b4hrrko) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/descriptor.go#L106)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Out of curiosity, why the removal of the comment here?
</blockquote></details>

This was an outdated comment; used a shiny hash map to resolve this.
(i was originally lazy and thought n would be small and avoided it, but /shrug)
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMa417_95s68cpKqGCg:-MMlbXTX5C5OQZtCr21W:b-fyt8nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/catalog/dbdesc/database_desc.go#L55)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

While I can understand the motivation for doing things this way, and it's quite a clever way of solving this problem, it seems a bit gross to me for a couple of reasons:

1) NewInitialOptionDatabaseRegionConfig is just a really long name
2) It makes the code more difficult to understand to have to trace down what each of these NewInitial functions are doing.
3) We're adding many lines of code to save one assignment in NewInitialWithPrivileges

Seeing as how it's just privileges and regions now, I'd think it would be easier to have all of it done in a single function and not build this options infrastructure just yet.  If we had more than 3 of these, I'd probably change my mind, but I don't know that we have another one on the horizon.
</blockquote></details>

I mainly did this because dbdesc.NewInitial is in quite a few places, and regions i feel is an optional argument.
FWIW, options are in https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+coding+guidelines.
___
*[pkg/sql/catalog/descpb/structured.proto, line 1064 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMaCSw88l3FW6RVTtGB:-MMlc5ls-lsBXhfw2EQ7:b-meeajv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/catalog/descpb/structured.proto#L1064)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Do we need the primary region here?  Or is that coming in a subsequent PR?
</blockquote></details>

Subsequent PR. This PR was written before the primary region stuff. Primary region logic requires a bit more work than I'm willing to put in for this PR, for now...
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMXVno201TUTye7_jaJ:-MMlbxqo28AIJ4NI1lh1:bpxd1bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/logictest/testdata/logic_test/multiregion#L12)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I didn't realize that we are currently supporting both `REGION` and `REGIONS`.  Will this show up in the help and documentation?  If so, I think we might want to nix `REGION`.
</blockquote></details>

I can nix it in a subsequent PR. I can also hide it in a subsequent PR. Premium bike shed opportunity!
But yes we can support both.

**Comment by otan** [comment]
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMa417_95s68cpKqGCg:-MMlmy93BUSVgEVP8H47:bhz5x3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/catalog/dbdesc/database_desc.go#L55)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I mainly did this because dbdesc.NewInitial is in quite a few places, and regions i feel is an optional argument.
FWIW, options are in https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+coding+guidelines.
</blockquote></details>

(did it anyway)

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 2 of 28 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56880)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, @nvanbenschoten, and @otan)

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMa417_95s68cpKqGCg:-MMpOfP871ccLQ48l8Zw:bfuybi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/catalog/dbdesc/database_desc.go#L55)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(did it anyway)
</blockquote></details>

Very interesting.  I'm still very new to Go, so that options pattern still seems very foreign to me (I guess, to be fair, you could do something like that in C++ too, but I've never seen it done like that before).  Regardless, if it's in the coding standard, we should probably change it back.  Wouldn't this also apply to the privileges parameter too?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 12 of 28 files at r3, 16 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-:-MMplrzY4GatSyr-SfzS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @otan)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMplQqRCv74o7-19wKu:-MMplQqRCv74o7-19wKv:b-v3jetc) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ea74f06fb8782d4154cfbcff2b363a509014ce/pkg/sql/logictest/testdata/logic_test/multiregion#L24)):*
> ```
> multi_region_test_db  root   {test1,test2,test3}  region
> postgres              root   {}                   NULL
> region_test_db        root   {test1}              zone
> ```

nit: Consider adding a multi-region db with zone survivability, just to assert that the two concerns aren't directly linked.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56880)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMa417_95s68cpKqGCg:-MMqX9Yj4e2IUW2_bzwQ:b-w67p58) ([raw file](https://github.com/cockroachdb/cockroach/blob/5294dbd8e4a51ebacf6b39f444abab0c284814bd/pkg/sql/catalog/dbdesc/database_desc.go#L55)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Very interesting.  I'm still very new to Go, so that options pattern still seems very foreign to me (I guess, to be fair, you could do something like that in C++ too, but I've never seen it done like that before).  Regardless, if it's in the coding standard, we should probably change it back.  Wouldn't this also apply to the privileges parameter too?
</blockquote></details>

Undone.

In theory we could, I'm not too fussed either way. Seems like it's worth being explicit for privilege, but not a fan of how it can be either a security.SQLUsername || descpb.PrivilegeDescriptor object.
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-MMplQqRCv74o7-19wKu:-MMqXZQ28pLsLbk22VTw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ea74f06fb8782d4154cfbcff2b363a509014ce/pkg/sql/logictest/testdata/logic_test/multiregion#L24)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Consider adding a multi-region db with zone survivability, just to assert that the two concerns aren't directly linked.
</blockquote></details>

Done.

**Review by ajstorm — COMMENTED** [review]
Sorry for a bit of back-and-forth.

:lgtm:  now

> Reviewed 1 of 17 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56880#-:-MMr032oBtoP8RqMeWpg:b-d6leyz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @dt, and @nvanbenschoten)

**Comment by otan** [comment]
thanks!

bors r+

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
