### PR TITLE
release-23.2: go.mod: bump Pebble to 93aaf52c3bec

### PR DESCRIPTION
**Pull request by sumeerbhola**
93aaf52c3be db: add compaction callbacks for unexpected SingleDelete behavior
ba91febb8d4 db: compactionIter.nextInStripe skips RANGEDEL covered keys in the same stripe
f065d7a4d05 db: fix SINGLEDEL, MERGE + DEL interaction

Informs #115881
Informs #114421

Release note: None

Release justification: additional invariant checking to help uncover https://github.com/cockroachdb/cockroach/issues/114421.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
lgtm

**Comment by jbowens** [comment]
I think we'll also need to backport to the `release-23.2.0-rc` branch

**Comment by sumeerbhola** [comment]
> I think we'll also need to backport to the release-23.2.0-rc branch

So not just a GA blocker?

**Comment by jbowens** [comment]
> So not just a GA blocker?

I might be misunderstanding the process, but I thought whatever release will eventually be 23.2.0 GA will come from the release-23.2.0-rc branch, and at this point anything merged to `release-23.2` won't be released until 23.2.1.

**Comment by nicktrav** [comment]
EM LGTM ✅

**Comment by sumeerbhola** [comment]
Created https://github.com/cockroachdb/cockroach/pull/116465

**Comment by sumeerbhola** [comment]
TFTRs!

**Pull request merged**
