### PR TITLE
sql: implement SHOW GRANTS ON TYPE

### LINKED ISSUE #53569: sql: support `SHOW GRANTS` on types
**Describe the problem**

I expect to be able to `SHOW GRANTS` on type descriptors.

**To Reproduce**

```sql
SET experimental_enable_enums = true;
CREATE TYPE typ AS ENUM ('hi');
SHOW GRANTS ON TYPE typ;
```

I get:
```
root@127.0.0.1:52942/movr> show grants on type typ
invalid syntax: statement ignored: at or near "typ": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
show grants on type typ
```

**Expected behavior**
To show the grants on the type.

**Environment:**

```
Build Tag:        v20.2.0-alpha.3-650-g3fd6e3b5d3
Build Time:       2020/08/27 18:32:55
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19.5.0)
Go Version:       go1.14.4
C Compiler:       4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)
Build Commit ID:  3fd6e3b5d3610ee4ed34ab0eca2df932aa6ca8f1
Build Type:       development
```

### PR DESCRIPTION
**Pull request by otan**
Resolves: #53569 

**sql: implement SHOW GRANTS ON TYPE**

Release note (sql change): Implement the `SHOW GRANTS ON TYPE` command,
which shows grants for a specific type.

**sql: add information_schema.type_privileges**

This is a custom table as the PostgreSQL data_type_privileges table
contains different information and has different semantics. This is
needed for SHOW GRANTS delegate to work as appropriate.

Release note (sql change): Add a custom
information_schema.type_privileges table that displays type privileges
for each supported type.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Code change looks good to me. I don't see any problems with us implementing `type_priveleges`, especially because `table_priveleges` and `schema_priveleges` (which are used by SHOW GRANTS) disambiguate on the basis of object and grantee (which is in line with the table you're adding). I'll defer the final +1 on that to @solongordon though. 

> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-:-MHRj5ce2P-XFJNAPPtg:b-1c64nq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/logictest/testdata/logic_test/grant_type, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHRgTtQ8MBWi4sziwGJ:-MHRgTtQ8MBWi4sziwGK:bcpm0d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2358417bbb0717319ad0ae3c9525b4396b186dcf/pkg/sql/logictest/testdata/logic_test/grant_type#L40)):*
> ```
> 
> statement error type "non_existent" does not exist
> SHOW GRANTS ON TYPE non_existent
> ```

nit: Maybe add a test where the type name is unqualified in the `SHOW GRANTS` statement too
___
*[pkg/sql/parser/parse_test.go, line 622 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHRitPdB3ANPqjGlcSC:-MHRitPdB3ANPqjGlcSD:bzddgbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2358417bbb0717319ad0ae3c9525b4396b186dcf/pkg/sql/parser/parse_test.go#L622)):*
> ```Go
> 		{`SHOW GRANTS ON SCHEMA foo, bar`},
> 		{`SHOW GRANTS ON TYPE typ1`},
> 		{`SHOW GRANTS ON TYPE typ1, schema2.typ2`},
> ```

nit: maybe add a FQN including the database here as well?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54485)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/grant_type, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHRgTtQ8MBWi4sziwGJ:-MHSEbi64LIP9JMGDTJ4:b1pmudl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2358417bbb0717319ad0ae3c9525b4396b186dcf/pkg/sql/logictest/testdata/logic_test/grant_type#L40)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Maybe add a test where the type name is unqualified in the `SHOW GRANTS` statement too
</blockquote></details>

Hmm, that will error because it's not a table. Changing that is a bigger change since it involves colname changes for a stability period.

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/grant_type, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHRgTtQ8MBWi4sziwGJ:-MHSOI5S9dbdxcZQpMAg:b-qg7v4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2358417bbb0717319ad0ae3c9525b4396b186dcf/pkg/sql/logictest/testdata/logic_test/grant_type#L40)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Hmm, that will error because it's not a table. Changing that is a bigger change since it involves colname changes for a stability period.
</blockquote></details>

ah nvm, it works ok.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54485)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/grant_type, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHRgTtQ8MBWi4sziwGJ:-MHSOnccD2uS_k4PLPTJ:b-53t9bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2358417bbb0717319ad0ae3c9525b4396b186dcf/pkg/sql/logictest/testdata/logic_test/grant_type#L40)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ah nvm, it works ok.
</blockquote></details>

Haha you made me build your branch again to make sure I wasn't tripping :joy:

**Review by solongordon — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 2 of 7 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54485)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @solongordon)

___
*[pkg/sql/information_schema.go, line 1037 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHXcBIP0rbPEx2npf7r:-MHXcBIP0rbPEx2npf7s:b80hza2) ([raw file](https://github.com/cockroachdb/cockroach/blob/040d6c36978c1ee491af20cdf0d2c47784340064/pkg/sql/information_schema.go#L1037)):*
> ```Go
> }
> 
> // Custom; PostgreSQL has data_type_privileges, which only shows one row per type,
> ```

If this is a custom table I wonder if it would be better to put it in `crdb_internal` rather than `information_schema`. Given that `information_schema` follows a standard, I'd don't think we should be adding non-standard tables there. What do you think?

**Comment by otan** [comment]
___
*[pkg/sql/information_schema.go, line 1037 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHXcBIP0rbPEx2npf7r:-MHXeMy15jYYn0nMqRcq:b-ofsx8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/040d6c36978c1ee491af20cdf0d2c47784340064/pkg/sql/information_schema.go#L1037)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

If this is a custom table I wonder if it would be better to put it in `crdb_internal` rather than `information_schema`. Given that `information_schema` follows a standard, I'd don't think we should be adding non-standard tables there. What do you think?
</blockquote></details>

The schema privileges table was already in here which is the precedent I was following.

**Comment by otan** [comment]
___
*[pkg/sql/information_schema.go, line 1037 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHXcBIP0rbPEx2npf7r:-MHXeX63DD-ckOhq8TZF:b-9kv4z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/040d6c36978c1ee491af20cdf0d2c47784340064/pkg/sql/information_schema.go#L1037)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

The schema privileges table was already in here which is the precedent I was following. 
</blockquote></details>

(that one is not standard either)

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54485)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/information_schema.go, line 1037 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54485#-MHXcBIP0rbPEx2npf7r:-MHXkJWBCgLtYzzaj_iw:b-dpt43c) ([raw file](https://github.com/cockroachdb/cockroach/blob/040d6c36978c1ee491af20cdf0d2c47784340064/pkg/sql/information_schema.go#L1037)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(that one is not standard either) 
</blockquote></details>

Okay, I suppose if MySQL can add non-standard information_schema tables then so can we.

**Comment by otan** [comment]
bors r=solongordon

Tftr!

**Pull request merged**
