### PR TITLE
lint: run GCAssert on recently created colexec packages

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64109)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64109#-MYvjDvM4wjusrYTh_eu:-MYvjDvM4wjusrYTh_ev:b-4izxje) ([raw file](https://github.com/cockroachdb/cockroach/blob/4825561313b20c44d6ad39aad68802d7fda90b24/pkg/col/colserde/arrowbatchconverter.go#L347)):*
> ```Go
> 			}
> 			offsets := bytesArr.ValueOffsets()
> 			prevOffset := offsets[0]
> ```

This code seems like it might benefit from templating, but I'm not sure whether we want to introduce it here yet.

**Comment by yuzefovich** [comment]
The microbenchmarks actually showed minor regression with introduction of BCE (on the order 1%), so I removed that change and only kept the linter cleanup.

**Comment by jordanlewis** [comment]
LGTM, though regressions on microbenchmarks after BCE makes no sense to me and could be indicative of something going wrong...

**Comment by yuzefovich** [comment]
Yeah, I don't what that was about. I was on the fence about introducing BCE given that the bounds checks should be very minor in comparison to actual deserialization, but saw a minor regression, so there is no benefit at all in adding that not pretty code to get BCE.

TFTR!

bors r+

**Pull request merged**
