### PR TITLE
sql: fix bug with type name conflict, allow resolving any object

### LINKED ISSUE #72820: sql: code to check whether a sequence exists is bad
**Describe the problem**

The code to check whether a sequence exists uses descriptor resolution APIs which indicate a name is not in use when it's in use by a type. 

https://github.com/cockroachdb/cockroach/blob/3e4a4407c8f0f176a300ca9f4e97d82c59c07470/pkg/sql/serial.go#L94-L97

**To Reproduce**

```sql
set serial_normalization = 'sql_sequence';
create type t_t_seq AS enum ('a');
create table t (t SERIAL PRIMARY KEY);
```
Leads to this inscrutible error:
```
ERROR: unexpected value: raw_bytes:"\304\244\321\003\001v" timestamp:<wall_time:1637082444028995000 > 
```
**Expected behavior**
We call the sequence `t_t_seq1`

**Additional context**
The deeper problem here is that we lack primitives to ask whether an object (postgres would say `relation`) exists with a given name without specifying what type of object we want. This problem lies here:

https://github.com/cockroachdb/cockroach/blob/3e4a4407c8f0f176a300ca9f4e97d82c59c07470/pkg/sql/sem/tree/name_resolution.go#L253-L262

We probably need some sort of `AnyObject` here. That's all fine and good, but it gets a tad tricky here when we want to construct a name for the purposes of errors.
https://github.com/cockroachdb/cockroach/blob/3e4a4407c8f0f176a300ca9f4e97d82c59c07470/pkg/sql/sem/tree/name_resolution.go#L264-L267

At a deeper level, I don't really understand what value we get out of having different types for `TableName` and `TypeName`. 

Jira issue: CRDB-11305

Epic CRDB-35306

### LINKED ISSUE #116795: workload/schemachange: enable `COMMENT ON`
As of https://github.com/cockroachdb/cockroach/pull/115360, `COMMENT ON` is support in the RSW but disabled by default due to a known bug: https://github.com/cockroachdb/cockroach/issues/72820

This is a tracking issue for enabling `COMMENT ON` after or in tandem with fixing the https://github.com/cockroachdb/cockroach/issues/72820.

Jira issue: CRDB-34779

Epic CRDB-19168

### LINKED ISSUE #118753: pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/13842656?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/13842656?buildTab=artifacts#/) on release-23.2 @ [690c68fb6a9d2c6b978aae6d21865d2908709afe](https://github.com/cockroachdb/cockroach/commits/690c68fb6a9d2c6b978aae6d21865d2908709afe):

```
1, 29, protected_ts_records, 32
1, 29, rangelog, 13
1, 29, region_liveness, 9
1, 29, replication_constraint_stats, 25
1, 29, replication_critical_localities, 26
1, 29, replication_stats, 27
1, 29, reports_meta, 28
1, 29, role_id_seq, 48
1, 29, role_members, 23
1, 29, role_options, 33
1, 29, scheduled_jobs, 37
1, 29, settings, 6
1, 29, span_configurations, 47
1, 29, span_stats_buckets, 55
1, 29, span_stats_samples, 56
1, 29, span_stats_tenant_boundaries, 57
1, 29, span_stats_unique_keys, 54
1, 29, sql_instances, 46
1, 29, sqlliveness, 39
1, 29, statement_activity, 60
1, 29, statement_bundle_chunks, 34
1, 29, statement_diagnostics, 36
1, 29, statement_diagnostics_requests, 35
1, 29, statement_execution_insights, 65
1, 29, statement_statistics, 42
1, 29, table_statistics, 20
1, 29, task_payloads, 58
1, 29, tenant_id_seq, 62
1, 29, tenant_settings, 50
1, 29, tenant_tasks, 59
1, 29, tenant_usage, 45
1, 29, tenants, 8
1, 29, transaction_activity, 61
1, 29, transaction_execution_insights, 64
1, 29, transaction_statistics, 43
1, 29, ui, 14
1, 29, users, 4
1, 29, web_sessions, 19
1, 29, zones, 5
100, 0, public, 101
102, 0, public, 103
104, 0, public, 105
104, 0, schema68, 122
104, 105, _enum21, 111
104, 105, enum21, 110
104, 105, table63, 121
    schema_change_external_test.go:82: backup in /artifacts/tmp/_tmp/fcba020ca7cb44bf8385bd0e13bcbe2d/logTestWorkload915465100
    panic.go:523: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/fcba020ca7cb44bf8385bd0e13bcbe2d/logTestWorkload915465100
--- FAIL: TestWorkload (9.30s)
```

Parameters:
 - <code>TAGS=bazel,gss</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #117782 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [C-test-failure O-robot P-3 T-sql-foundations branch-release-23.2.0-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35887

### PR DESCRIPTION
**Pull request by rafiss**
Prior to this change there was a bug when a type name conflicted with a sequence name (#72820). This resolves that problem by adding logic to resolve any sort of object with a given name.

It also removes a bad method from sql/resolver.go

replaces #72824
fixes #72820
fixes https://github.com/cockroachdb/cockroach/issues/118753
fixes https://github.com/cockroachdb/cockroach/issues/116795

Release note (bug fix): Fixed a bug which caused an inscrutable error when a sequence name allocated by `SERIAL` conflicted with an existing type name.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118861)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @srosenberg)

___
*[`pkg/sql/serial.go` line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118861#-Nq3Wkkk6bItiQtfAKq7:-Nq3Wkkl3XQuGZkx5JBW:b-b0yaf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/447d33c6a149ad909969b077d04aca731824f086/pkg/sql/serial.go#L96)):*
> ```Go
> 		RequireMutable:    false,
> 		IncludeOffline:    true,
> 		DesiredObjectKind: tree.AnyObject,
> ```

We need a similar change to the declarative CREATE SEQUENCE. It attempts to only resolve a table when it needs to check for any conflict.

i.e.:
 create type t_t_seq AS enum ('a');
 create sequence t_t_seq;

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118861)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, and @srosenberg)

___
*[`pkg/sql/serial.go` line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118861#-Nq3Wkkk6bItiQtfAKq7:-Nq4Y5y57wYb40JRez9M:b1qzvc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/447d33c6a149ad909969b077d04aca731824f086/pkg/sql/serial.go#L96)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We need a similar change to the declarative CREATE SEQUENCE. It attempts to only resolve a table when it needs to check for any conflict.

i.e.:
 create type t_t_seq AS enum ('a');
 create sequence t_t_seq;
</blockquote></details>

nice catch. fixed

**Review by fqazi — APPROVED** [review]
Great work, and thanks for doing this :lgtm:

> Reviewed 2 of 3 files at r3, 2 of 2 files at r5, 1 of 1 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118861#-:-Nq4YZWjBUnJvcsUgl2p:b-zf9jdf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
