### PR TITLE
importccl: re-enable IMPORT tests

### PR DESCRIPTION
**Pull request by dt**
switching this to a test-cluster appears to have made it too slow under race.
This switches it back to a single node to get it re-enabled for now.

Release note: none.

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
we also could skip this under race. if i have to choose, i'd rather have non-race coverage of multi-node import than race coverage of single-node import

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34996#-:-LYluutA6fCXLA2zYsIm:bgetg2b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

**Comment by dt** [comment]
The other tests in the package are basically all multi-node so we mostly have multi-node coverage. This particular test is targeted at the handling of specific input -- like a strange date string format in mysql or null handling option in csv or the decompression option, etc -- and less about the overall flow so I'm not _as_ concerned that this test be multi-node.

I tried making it multinode since currently it happens to be where I added coverage for the experimental ingest, but IMO while that is off by default, it's less important than the existing t

**Comment by dt** [comment]
(whoops, somehow palmed the close-and-comment button mid-sentence)

**Review by danhhz — APPROVED** [review]
okay. LGTM

**Review by nvb — APPROVED** [review]
Thanks!

**Comment by dt** [comment]
heh. so the targeted stressrace runs on tests modified in the PR is now timing out on `TestImportData` .. even though this commit is literally just checking the file out to how it was on master 2 days ago. This test might have just gradually gotten too slow and we finally hit the breaking point.

**Pull request merged**
