### PR TITLE
cliccl: add cli `load show data` command to display backup table data

### PR DESCRIPTION
**Pull request by Elliebababa**
Previously, `cockraoch load` is used for loading backup manifests,
with backup inspection featrues to show backup metadata, show
backups in collection etc.

This PR extends it with `load show data` subcommand to display
backup table data.
By running `cockroach load show data <table> <backup_url>`, users
are able to inspect key-values of a table in backup. This is a
start point for exporting data from backup to other format data.

Release note (cli change): We extend `load show` with
`load show data` subcommand to display backup table data.
By running `cockroach load show data <table> <backup_url>`, users
are able to inspect key-values of a table in backup. This is a
start point for exporting data from backup to other format data.

```
$ ./cockroach load show data defaultdb.public.customer "nodelocal://0/demo_customer"
/Table/57/1/0/0 @Fri Mar 19 19:19:37 2021 -> /TUPLE/2:2:Int/123
/Table/57/1/1/0 @Fri Mar 19 19:19:43 2021 -> /TUPLE/2:2:Int/223
/Table/57/1/2/0 @Fri Mar 19 19:19:50 2021 -> /TUPLE/2:2:Int/333
```

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWPf9S_4tYY9eWUvZWO:-MWPf9S_4tYY9eWUvZWP:bl6v5aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdb18ba14837254e8f63ceb628dd0c0f75955cf/pkg/ccl/backupccl/restore_planning.go#L1234)):*
> ```Go
> }
> 
> // ErrOnMissingRange returns error message of span not covered by [start, end)
> ```

nit: `returns _an_ error message _that a span is _ not covered by [start, end).`
___
*[pkg/ccl/cliccl/load.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWPggjNCGeuhyiP1Yct:-MWPggjNCGeuhyiP1Ycu:bkrjw09) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdb18ba14837254e8f63ceb628dd0c0f75955cf/pkg/ccl/cliccl/load.go#L162)):*
> ```Go
> 	path := args[0]
> 	ctx := context.Background()
> 	desc, err := getManifestFromURI(ctx, path)
> ```

I think something like `manifest` or `backupManifest` is a better name for the return value here rather than `desc`.
___
*[pkg/ccl/cliccl/load.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWPfM0U5l6TivAYEvmD:-MWPfM0U5l6TivAYEvmE:bf9u22s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdb18ba14837254e8f63ceb628dd0c0f75955cf/pkg/ccl/cliccl/load.go#L164)):*
> ```Go
> 	desc, err := getManifestFromURI(ctx, path)
> 	if err != nil {
> 		return errors.Wrapf(err, "run load show summary")
> ```

When we wrap errors, we usually want to wrap them with information about what we operation we were trying to do when we encountered this error to provide a more informative error message, indicating what the program was trying to do.

In this case we'd either want to wrap this error with something like `fetching backup manifest`, or wrap the error returned from `runLoadShowSummary` with something like `showing backup summary`.

The same applies for errors that are wrapped with `load show data` below, as well as the errors wrapped in `showKV`.
___
*[pkg/ccl/cliccl/load_test.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWPezLr6R1WM3psZK7B:-MWPezLr6R1WM3psZK7C:by9knb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdb18ba14837254e8f63ceb628dd0c0f75955cf/pkg/ccl/cliccl/load_test.go#L211)):*
> ```Go
> 	sqlDB.Exec(t, `CREATE SCHEMA testDB.testschema`)
> 	sqlDB.Exec(t, `CREATE TABLE fooTable (a INT PRIMARY KEY)`)
> 	sqlDB.Exec(t, `CREATE TABLE testDB.testschema.fooTable (a INT PRIMARY KEY)`)
> ```

Let's add some test cases that have a value in the KV.

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/cliccl/load.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWPggjNCGeuhyiP1Yct:-MWQh_6m2bEJlH4HdRhx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdb18ba14837254e8f63ceb628dd0c0f75955cf/pkg/ccl/cliccl/load.go#L162)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think something like `manifest` or `backupManifest` is a better name for the return value here rather than `desc`.
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWPfM0U5l6TivAYEvmD:-MWRJVruCZOzxzpDs-Ai:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdb18ba14837254e8f63ceb628dd0c0f75955cf/pkg/ccl/cliccl/load.go#L164)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

When we wrap errors, we usually want to wrap them with information about what we operation we were trying to do when we encountered this error to provide a more informative error message, indicating what the program was trying to do.

In this case we'd either want to wrap this error with something like `fetching backup manifest`, or wrap the error returned from `runLoadShowSummary` with something like `showing backup summary`.

The same applies for errors that are wrapped with `load show data` below, as well as the errors wrapped in `showKV`.
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load_test.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWPezLr6R1WM3psZK7B:-MWRKXoJDUeAjts8J_zE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdb18ba14837254e8f63ceb628dd0c0f75955cf/pkg/ccl/cliccl/load_test.go#L211)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Let's add some test cases that have a value in the KV.
</blockquote></details>

Done.

**Comment by pbardea** [comment]
Whoops, sorry this fell off my radar. Will take a look.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa)

___
*[pkg/ccl/backupccl/restore_job.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfFUQg3C0lsxQpvKk7:-MWfFUQg3C0lsxQpvKk8:bloes83) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/backupccl/restore_job.go#L486)):*
> ```Go
> 
> 	tbID := resolver.ObjsByName[resolver.DbsByName[descName[0]]][descName[1]][descName[2]]
> 	tbDesc, err := catalog.AsTableDescriptor(resolver.DescByID[tbID])
> ```

Is the second return result of `resolver.LookupObject` the same as `resolver.DescByID`? Can we use that instead?
___
*[pkg/ccl/backupccl/restore_job.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfEaz-5eySoTbFNUjx:-MWfEaz-5eySoTbFNUjy:b-xjsnkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/backupccl/restore_job.go#L491)):*
> ```Go
> 	}
> 
> 	backupCodec := keys.SystemSQLCodec
> ```

Can we use `keys.TODOSQLCodec`here? I think it would need to be updated when doing this on backups from inside tenants (not something we want to tackle for now)
___
*[pkg/ccl/backupccl/restore_job.go, line 498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfEp5b3o62mB7vaRCp:-MWfEp5b3o62mB7vaRCq:biqwgdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/backupccl/restore_job.go#L498)):*
> ```Go
> 		backupManifests,
> 		/*backupLocalityInfo*/ nil,
> 		roachpb.Key{},
> ```

Can we add a comment explaining what this argument is for?
___
*[pkg/ccl/cliccl/load_test.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfE0HC9rSdZ9zH_0Qx:-MWfE0HC9rSdZ9zH_0Qy:bbhaum9) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/cliccl/load_test.go#L212)):*
> ```Go
> 	sqlDB.Exec(t, `CREATE TABLE fooTable (a INT PRIMARY KEY)`)
> 	sqlDB.Exec(t, `INSERT INTO fooTable VALUES (123)`)
> 	sqlDB.Exec(t, `CREATE TABLE testDB.testschema.fooTable (a INT PRIMARY KEY)`)
> ```

Hmm, I mean that we should add another column to this table that is not part of the primary key so that the value portion of the KV that we're printing out is non-empty. Right now it's always empty so it always prints out and empty `/TUPLE/`.

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfFUQg3C0lsxQpvKk7:-MWjQi8H1RWyROYVI4jk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/backupccl/restore_job.go#L486)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Is the second return result of `resolver.LookupObject` the same as `resolver.DescByID`? Can we use that instead?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfEaz-5eySoTbFNUjx:-MWjQj7QCuYPMg8pFabL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/backupccl/restore_job.go#L491)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we use `keys.TODOSQLCodec`here? I think it would need to be updated when doing this on backups from inside tenants (not something we want to tackle for now)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfEp5b3o62mB7vaRCp:-MWjRZ7-0-WEQVnDcSUW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/backupccl/restore_job.go#L498)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we add a comment explaining what this argument is for?
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load_test.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62223#-MWfE0HC9rSdZ9zH_0Qx:-MWjQq119piICj4zuqsI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33b7cb1f99553d7344a1125fce3a60cd67bf93b8/pkg/ccl/cliccl/load_test.go#L212)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Hmm, I mean that we should add another column to this table that is not part of the primary key so that the value portion of the KV that we're printing out is non-empty. Right now it's always empty so it always prints out and empty `/TUPLE/`.
</blockquote></details>

Done.

**Comment by Elliebababa** [comment]
squash into #62662

**Pull request closed without merging**
