### PR TITLE
ui: add full table/index scan count chart in SQL Metrics page

### LINKED ISSUE #64217: Add time series counter for full table and full secondary index scans
**Is your feature request related to a problem? Please describe.**
Full table scans commonly cause problems with clusters including outage events. 

**Describe the solution you'd like**
We need to be able to alert for full table based on time series data.

**Describe alternatives you've considered**
Manually searching for full table scans in code which is time consuming and prone to error

gz#8135

### PR DESCRIPTION
**Pull request by Azhng**
Resolves #64217

Release note (ui change): introducing full table/index scan time series
 chart in SQL Metrics page.

### CODE REVIEW

**Review by matthewtodd — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

**Review by matthewtodd — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66972#-:-MdN0Pz40uIP3e3_GcGx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by kevin-v-ngo** [comment]
Thanks for picking this up Archer! We'll be more specific next time on the chart position. Can we have this chart be under the SQL contention chart is today?

image

**Comment by Azhng** [comment]
Rebased after the #66969 and move the chart to be under the statement contention chart. 

Screen Shot 2021-07-05 at 17 02 20

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66972)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @matthewtodd)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx, line 144 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66972#-Me5S9fc0eob5t6iqyfd:-Me5S9fc0eob5t6iqyfe:b8mudgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff7e2b6c777599646e3e94757382b185e42508d/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L144)):*
> ```XML
> 
>     <LineGraph
>       title="Full Table/Index Scans"
> ```

From the issue I got the impression it was one metric for full scan and another for secondary index, you created one with both names, but that source is a count on just full scan (`cr.node.sql.full.scan.count`). Do they mean the same thing?

**Comment by Azhng** [comment]
A full table scan is also an index scan except it's scanning the primary index. So yes they mean the same thing.

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66972#-:-Me5l0BhCRS3WSk1F_Wn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @matthewtodd)

**Pull request merged**
