### PR TITLE
util/intsets: use new intsets.Sparse implementation for util.FastIntSet

### PR DESCRIPTION
**Pull request by mgartner**
#### util: move FastIntSet to new pkg/util/intsets

Release note: None

#### intsets: rename FastIntSet to Fast

Release note: None

#### intsets: move bitmap into a separate file

Release note: None

#### intsets: add Sparse and use it in Fast

This commit replaces usages of the Sparse type in
golang.org/x/tools/container/intsets with a new `intsets.Sparse` type.
The new type is inspired by the `x/tools` type, but differs in several
ways:

  1. The new `Sparse` type provides a smaller API than the `x/tools`
     `Sparse` type, only containing the methods required by
     `intsets.Fast`.
  2. The new `Sparse` type is implemented as a singly-linked list of
     blocks rather than a circular, doubly-linked list.
  3. The new `Sparse` type reuses the `bitmap` type used in
     `intsets.Fast`. As a result, each block can store up to 128
     integers instead of 256.

This simpler implementation yields a performance boost in query
optimization of some types of queries.

Release note: None

#### intsets: do not shift values in Fast.large

Previously, `intsets.Fast` shifted values by 128 when storing them in
`Fast.large` to minimize allocations within `Fast.large` (see the
deleted comments in the diff). Now that `intsets.Sparse`'s uses
blocks with 128-bit bitmaps instead of 256-bit bitmaps, this shift no
longer provides any benefit, so it has been removed.

Release note: None

Epic: None

### CODE REVIEW

**Comment by mgartner** [comment]
Optimizer microbenchmarks show some promising improvements: https://gist.github.com/mgartner/bafce7fa99cf96644304bceb23303919

I'm planning on running more end-to-end benchmarks to ensure this doesn't cause any significant regressions.

**Comment by smg260** [comment]
👍  Minor impact on test-eng code

**Review by yuzefovich — APPROVED** [review]
Nice work! :lgtm:

> Reviewed 172 of 172 files at r1, 121 of 121 files at r2, 3 of 3 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-:-NFQwvRkEPQJp0Z1kLiD:b-8ewgme)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @herkolategan, @HonoreDB, @mgartner, @msbutler, and @smg260)

___
*[`pkg/util/intsets/sparse.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQvyHH7M9LXn_kLGQI:-NFQvyHH7M9LXn_kLGQJ:b92chg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L29)):*
> ```Go
> // Max method allows us to use a singly-linked list here instead of a
> // circular, doubly-linked list.
> type Sparse struct {
> ```

I wonder whether it would be worth it to add an explicit unit test for this new struct. In particular, it seems that writing a randomized test that compares the new implementation against `intsets.Sparse` would be pretty low effort and would give us more confidence.
___
*[`pkg/util/intsets/sparse.go` line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQqH9EDUPyobLvN2gg:-NFQqH9FEkaoeU_AjyxE:b9i66hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L51)):*
> ```Go
> 
> // offset returns the block offset for the given integer.
> // Note: Bitwise AND NOT only works here because smallCutoff is a power of two.
> ```

nit: should we add an explicit assertion for this? I.e. something like
```
func init() {
  if (smallCutoff & (smallCutoff - 1)) != 0 {
    panic("boom")
  }
}
```

___
*[`pkg/util/intsets/sparse.go` line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQr9IJ0mxqVq8EUARB:-NFQr9IJ0mxqVq8EUARC:b4hmo51) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L95)):*
> ```Go
> 			return nil
> 		}
> 		s.root.offset = b.next.offset
> ```

nit: can we do `s.root = *b.next`?
___
*[`pkg/util/intsets/sparse.go` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQrsRL2x3E4H4d-3Ho:-NFQrsRL2x3E4H4d-3Hp:b-tje6b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L129)):*
> ```Go
> func (s *Sparse) Remove(i int) {
> 	o := offset(i)
> 	b := bit(i)
> ```

nit: not sure whether it is worth it, but we could lazily compute value of `b`. In case when a block that would contain `i` is not present in the set, we'd avoid computing the bit altogether. Ditto for `Contains` and `LowerBound`.
___
*[`pkg/util/intsets/sparse.go` line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQucZO9bvix76TzMKu:-NFQucZO9bvix76TzMKv:b-w0s5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L267)):*
> ```Go
> 		}
> 	}
> 	if sb == &s.root {
> ```

The split of the logic between a loop and outside seems tricky - could you add some more commentary here? Like what `sb` and `last` are expected to point at, etc.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90009)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @herkolategan, @HonoreDB, @msbutler, @smg260, and @yuzefovich)

___
*[`pkg/util/intsets/sparse.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQvyHH7M9LXn_kLGQI:-NFUN5UaEYdjNLvkxGgV:b-qd7wh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L29)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I wonder whether it would be worth it to add an explicit unit test for this new struct. In particular, it seems that writing a randomized test that compares the new implementation against `intsets.Sparse` would be pretty low effort and would give us more confidence.
</blockquote></details>

Good idea. I'll work on adding those.
___
*[`pkg/util/intsets/sparse.go` line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQqH9EDUPyobLvN2gg:-NFUN27zDBooSn17KXkh:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L51)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we add an explicit assertion for this? I.e. something like
```
func init() {
  if (smallCutoff & (smallCutoff - 1)) != 0 {
    panic("boom")
  }
}
```

</blockquote></details>

Good idea. Done.
___
*[`pkg/util/intsets/sparse.go` line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQr9IJ0mxqVq8EUARB:-NFUBnSu8nax8VElAJ_l:bsq9x32) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L95)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: can we do `s.root = *b.next`?
</blockquote></details>

We can, but it compiles to basically the same instructions:

```diff
         MOVQ    24(CX), DX
-        MOVQ    8(DX), BX
-        MOVQ    16(DX), DX
+        MOVQ    8(CX), BX
+        MOVQ    16(CX), SI
+        MOVQ    (CX), CX
+        MOVQ    CX, (AX)
         MOVQ    BX, 8(AX)
-        MOVQ    DX, 16(AX)
-        MOVQ    24(CX), CX
-        MOVQ    24(CX), CX
+        MOVQ    SI, 16(AX)
         PCDATA  $0, $-2
         CMPL    runtime.writeBarrier(SB), $0
-        JNE     command-line-arguments_Sparse_removeBlock_pc126
-        MOVQ    CX, 24(AX)
-        JMP     command-line-arguments_Sparse_removeBlock_pc135
-command-line-arguments_Sparse_removeBlock_pc126:
+        JNE     command-line-arguments_Sparse_removeBlock_pc118
+        MOVQ    DX, 24(AX)
+        JMP     command-line-arguments_Sparse_removeBlock_pc127
+command-line-arguments_Sparse_removeBlock_pc118:
         LEAQ    24(AX), DI
-        CALL    runtime.gcWriteBarrierCX(SB)
-command-line-arguments_Sparse_removeBlock_pc135:
+        CALL    runtime.gcWriteBarrierDX(SB)
+command-line-arguments_Sparse_removeBlock_pc127:
```

But if you think it's more clear and concise, I can make the change.
___
*[`pkg/util/intsets/sparse.go` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQrsRL2x3E4H4d-3Ho:-NFUFu0CCnKroAuw5XEP:b4fi8a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L129)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: not sure whether it is worth it, but we could lazily compute value of `b`. In case when a block that would contain `i` is not present in the set, we'd avoid computing the bit altogether. Ditto for `Contains` and `LowerBound`.
</blockquote></details>

This doesn't seem to change the compiled assembly at all, so I'll leave as-is.
___
*[`pkg/util/intsets/sparse.go` line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQucZO9bvix76TzMKu:-NFUM58i8NYwmSHdE994:by0712t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L267)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The split of the logic between a loop and outside seems tricky - could you add some more commentary here? Like what `sb` and `last` are expected to point at, etc.
</blockquote></details>

This was the trickiest part to get correct. I've left a note - let me know if it helps.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 134 of 134 files at r6, 121 of 121 files at r7, 3 of 3 files at r8, 6 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90009)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @herkolategan, @HonoreDB, @mgartner, @msbutler, and @smg260)

___
*[`pkg/util/intsets/sparse.go` line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQr9IJ0mxqVq8EUARB:-NFUd4w_BGixqq3d7Brr:b8xuid1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L95)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We can, but it compiles to basically the same instructions:

```diff
         MOVQ    24(CX), DX
-        MOVQ    8(DX), BX
-        MOVQ    16(DX), DX
+        MOVQ    8(CX), BX
+        MOVQ    16(CX), SI
+        MOVQ    (CX), CX
+        MOVQ    CX, (AX)
         MOVQ    BX, 8(AX)
-        MOVQ    DX, 16(AX)
-        MOVQ    24(CX), CX
-        MOVQ    24(CX), CX
+        MOVQ    SI, 16(AX)
         PCDATA  $0, $-2
         CMPL    runtime.writeBarrier(SB), $0
-        JNE     command-line-arguments_Sparse_removeBlock_pc126
-        MOVQ    CX, 24(AX)
-        JMP     command-line-arguments_Sparse_removeBlock_pc135
-command-line-arguments_Sparse_removeBlock_pc126:
+        JNE     command-line-arguments_Sparse_removeBlock_pc118
+        MOVQ    DX, 24(AX)
+        JMP     command-line-arguments_Sparse_removeBlock_pc127
+command-line-arguments_Sparse_removeBlock_pc118:
         LEAQ    24(AX), DI
-        CALL    runtime.gcWriteBarrierCX(SB)
-command-line-arguments_Sparse_removeBlock_pc135:
+        CALL    runtime.gcWriteBarrierDX(SB)
+command-line-arguments_Sparse_removeBlock_pc127:
```

But if you think it's more clear and concise, I can make the change.
</blockquote></details>

Thanks for checking, for me it's a minor stylistic preference, but please feel free to ignore this nit.
___
*[`pkg/util/intsets/sparse.go` line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQucZO9bvix76TzMKu:-NFUe5NB1Pl9FDDDNyq0:bsdgezk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L267)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This was the trickiest part to get correct. I've left a note - let me know if it helps.
</blockquote></details>

Yes, now it's clear, thanks!

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for pulling it into separate commits! I'm excited to see what sort of additional gains we can see by using arena allocation  for `intsets.Sparse`

> Reviewed 44 of 172 files at r1, 134 of 134 files at r6, 121 of 121 files at r7, 3 of 3 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-:-NFV3yyE15w6H3_jx4dT:byfh5ca)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @HonoreDB, @mgartner, @msbutler, @smg260, and @yuzefovich)

___
*[`pkg/util/intsets/sparse.go` line 58 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFUy_KsCdPk-b6O2fcM:-NFUy_KsCdPk-b6O2fcN:b-30tl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b56c176ba411e04c20503e5491df83586835b0/pkg/util/intsets/sparse.go#L58)):*
> ```Go
> // offset returns the block offset for the given integer.
> // Note: Bitwise AND NOT only works here because smallCutoff is a power of two.
> func offset(i int) int {
> ```

[nit] Should we add gcassert:inline to some of these methods?

**Comment by DrewKimball** [comment]
@mgartner do you have any plans to bring this one across the finish line? I'm happy to help if it means getting those sweet perf improvements.

**Review by mgartner — COMMENTED** [review]
@drewkimball I've just rebased this and I think the last remaining thing is writing a bunch of randomized tests for sparse. Let me see if I can make some progress on that today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-:-NJRdkHN7877_lvOxmey:b-x866a4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @herkolategan, @HonoreDB, @msbutler, @smg260, and @yuzefovich)

___
*[`pkg/util/intsets/sparse.go` line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQucZO9bvix76TzMKu:-NJRdUUfA63SW69tzMKB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L267)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yes, now it's clear, thanks!
</blockquote></details>

Done.
___
*[`pkg/util/intsets/sparse.go` line 58 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFUy_KsCdPk-b6O2fcM:-NJRdVDhAuMCSYV9Urow:b-wao5wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b56c176ba411e04c20503e5491df83586835b0/pkg/util/intsets/sparse.go#L58)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Should we add gcassert:inline to some of these methods?
</blockquote></details>

I've added them, but I don't think the TestGCAssert linter is running under bazel, so they won't do anything until that is fixed. See https://github.com/cockroachdb/cockroach/issues/65485.

**Review by mgartner — COMMENTED** [review]
I've added tests and fixed a bug that they uncovered in UnionWith. I think the last thing to do it run the optimizer micro-benchmarks again and make sure that we still see the same improvement after the minor change that fixed the bug.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-:-NJS9hEs-wU80vFXsmg8:b-n5mdpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @herkolategan, @HonoreDB, @msbutler, @smg260, and @yuzefovich)

___
*[`pkg/util/intsets/sparse.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NFQvyHH7M9LXn_kLGQI:-NJS9GfR5bN1hSwqF7iB:b-wp13ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/e81723d74e234deab445e49fd5f9f47cb324fbfa/pkg/util/intsets/sparse.go#L29)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good idea. I'll work on adding those.
</blockquote></details>

I've added randomized tests for `intsets.Sparse` using an oracle with the same API but backed by a map. It's a good thing I did it too - it revealed a bug in `Sparse.UnionWith` that was hidden by `intsets.Fast`.

**Review by DrewKimball — APPROVED** [review]
The test looks great! :lgtm:

> Reviewed 25 of 152 files at r11, 121 of 124 files at r12, 1 of 3 files at r13, 7 of 9 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-:-NJSX6rU-qiEONddt54U:b-rdi1la)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @HonoreDB, @mgartner, @msbutler, @smg260, and @yuzefovich)

___
*[`pkg/util/intsets/sparse_test.go` line 29 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NJSWlVw4hTS7dLtaPnK:-NJSWlVw4hTS7dLtaPnL:bkbpyu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89e7ca88ae63b02fe84f33ad84bca6a75feb195/pkg/util/intsets/sparse_test.go#L29)):*
> ```Go
> 
> func TestSparse(t *testing.T) {
> 	for _, minVal := range []int{-100_000, -smallCutoff * 10, -smallCutoff, 0, smallCutoff, smallCutoff * 10} {
> ```

What's with the underscore in `-100_000`?

**Comment by mgartner** [comment]
*[`pkg/util/intsets/sparse_test.go` line 29 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/90009#-NJSWlVw4hTS7dLtaPnK:-NJf1P9-00MKwKYvRRaB:b-8uz0bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89e7ca88ae63b02fe84f33ad84bca6a75feb195/pkg/util/intsets/sparse_test.go#L29)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What's with the underscore in `-100_000`?
</blockquote></details>

It has no semantic meaning, it's just a way to make it easier to read long numbers - just like the comma in "100,000". You can put them wherever you want, e.g., `1000 == 1_0_0_0` => `true`. I've seen it used in other languages, and I think this feature was added in Go 1.13, here's the proposal: https://github.com/golang/go/issues/28493

**Comment by mgartner** [comment]
Unfortunately, the [new benchmark results](https://gist.github.com/mgartner/0d279f1f2630ffa736fab43cafab8f9c) are less promising than the [original ones](https://gist.github.com/mgartner/bafce7fa99cf96644304bceb23303919). For example, we were seeing a -24% latency delta in `Phases/many-columns-and-indexes-c/Prepared/ExecBuild-24`, and now we see only -8%. All the `SlowQueries` benchmarks originally had reduced latency, and now only `SlowQueries/slow-query-1-24` does. I've lost some confidence that this is justified to merge, what do you think @DrewKimball. One justification that this opens the door to attempt to pool some of these block allocations, or create a version with a custom allocator.

I'm not sure what explains the difference in results. It could be the addition of `if rhs.Empty() { return; }` to `Sparse.UnionWith` that fixes the bug found by the Sparse tests, our recent upgrade to Go 1.19, or something else.

**Comment by DrewKimball** [comment]
I think this is still worth merging for the increased optimization opportunities, as you say. I think any minor regressions will be overshadowed by potential to block-allocate - that's going to be a huge win.

**Pull request merged**
