### PR TITLE
client: default admin client to localhost

### LINKED ISSUE #4826: cockroach quit with defaults doesn't work
When you start a node with `./cockroach start`, accepting all defaults (secure, store=cockroach-data, certs=certs, host=localhost, port=26257), it should be possible to stop the node with `./cockroach quit`. Currently, that's not working:

**Start the node:**

```
$ ./cockroach start &
[1] 10039
JESSEs-MacBook-Pro:cockroach jesseseldess$ build:     alpha.v1-490-gd545bc3 @ 2016/02/29 19:03:03 (go1.6)
admin:     https://JESSEs-MacBook-Pro.local:26257
sql:       postgresql://root@JESSEs-MacBook-Pro.local:26257?sslcert=%2FUsers%2Fjesseseldess%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcerts%2Froot.client.crt&sslkey=%2FUsers%2Fjesseseldess%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcerts%2Froot.client.key&sslmode=verify-full&sslrootcert=%2FUsers%2Fjesseseldess%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcerts%2Fca.crt
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

**Try to stop the node:**

```
$ ./cockroach quit
Error: shutdown node error: client/admin.go:161: GET request failed: https://:26257/_admin/v1/quit, err: Get https://:26257/_admin/v1/quit: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
Failed running "quit"
E160303 13:27:31.340659 server.go:2159  http: TLS handshake error from 127.0.0.1:58355: EOF
```

### PR DESCRIPTION
**Pull request by tamird**
Fixes an issue where we attempt to make an outbound HTTPS request
without specifying a hostname, and certificate verification cannot
proceed.

Fixes #4826.

cc @jseldess

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4827)

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

**Comment by mberhault** [comment]
LGTM. might be worth making the localhost the default `--host` value.

**Comment by tamird** [comment]
I intentionally didn't do that because that would prevent us from listening
on all interfaces.

**Comment by jseldess** [comment]
Updated in docs with https://github.com/cockroachdb/docs/pull/88

**Pull request merged**
