### PR TITLE
release-20.2: assorted pgwire and cli/sql backports

### PR DESCRIPTION
**Pull request by knz**
Release justification: bug fixes in CLI-only functionality.

Backport:
  * 1/1 commits from "sql: fix displaying second zone offsets" (#55071)
  * 1/1 commits from "cli: handle utf in show tables" (#56630)
  * 1/1 commits from "pgwire: lazily populate second timezone offset" (#57265)
  * 4/4 commits from "sql/pgwire: fix encoding of int4 and bpchar in tuples " (#61013)
  * 1/1 commits from "cli/sql: properly format different times and floats" (#62310)
  * 1/1 commits from "sql/pgwire: fix encoding of decimals with trailing 0s" (#64022)
  * 2/2 commits from "pgwire: only show TZ minutes offset if non-zero" (#65063)
  * 1/1 commits from "cli/sql: properly format common array types" (#66079)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by knz** [comment]
I think I'm missing one PR on account of a pgwire/pgtest test case failing (one that pertains to `timestamp`)

**Comment by knz** [comment]
any idea what PR that could be?

**Comment by otan** [comment]
maybe b450c44a430f53b3144d2ba49891f7dc5149a4ed ?

**Comment by knz** [comment]
the failure is from `encodings.json`

**Comment by rafiss** [comment]
it appears that the failing test is now:
```
--- FAIL: TestUtfName (0.40s)
    test_log_scope.go:158: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestUtfName939491298
    test_log_scope.go:63: use -show-logs to present logs inline
    sql_util_test.go:259: expected output:
          schema_name | table_name | type  | owner | estimated_row_count | locality
        --------------+------------+-------+-------+---------------------+-----------
          public      | żółw       | table | root  |                NULL | NULL
        (1 row)
        
        got:
          schema_name | table_name | type  | owner | estimated_row_count
        --------------+------------+-------+-------+----------------------
          public      | żółw       | table | root  |                   0
        (1 row)
```

i guess because https://github.com/cockroachdb/cockroach/pull/57653 is not in 20.2. looks like the test can be fixed to not expect the `locality` column

**Comment by knz** [comment]
ok I'll iterate on this tomorrow or Friday

**Comment by knz** [comment]
Fixed; RFAL

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/pgwire/types.go, line 71 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66533#-MfJ1XfQ8eK_VG2Da0Ix:-MfJ1XfQ8eK_VG2Da0Iy:b-884nod) ([raw file](https://github.com/cockroachdb/cockroach/blob/909fc0ee7c7aa8b92ed920fecc7a90f567350367/pkg/sql/pgwire/types.go#L71)):*
> ```Go
> // It is ignored (and can be nil) for types which do not need padding.
> func (b *writeBuffer) writeTextDatum(
> 	ctx context.Context, d tree.Datum, conv sessiondata.DataConversionConfig, t *types.T,
> ```

just a theory, but it's possible the issue here is that `conv.Location` is not set correctly for the EncodingTest

this wouldn't affect later branches because they contain ab19e5c4738228fbd9789f52cc59f1d4bbacb5bc

**Comment by knz** [comment]
wasn't able to make this work.

**Pull request closed without merging**
