### PR TITLE
*: enable declarative schema changer

### PR DESCRIPTION
**Pull request by postamar**
This change enables the declarative schema changer by default. This PR originated as #76610 by @fqazi which I rebased following the merging of #76776. Only mild alterations were needed, these commits can therefore be considered as having been reviewed.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
> Reviewed 11 of 23 files at r1, 56 of 56 files at r14, 2 of 2 files at r15, 6 of 6 files at r16, 1 of 1 files at r17, 10 of 10 files at r18, 2 of 2 files at r19, 1 of 1 files at r20, 8 of 8 files at r21, 11 of 11 files at r22, 5 of 5 files at r23, 17 of 17 files at r24, 1 of 1 files at r25, 1 of 1 files at r26, 11 of 11 files at r27, 38 of 38 files at r28, 3 of 3 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76944)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

**Comment by postamar** [comment]
Thanks for the review! I bumped the TESTIMEOUT variable in the Makefile to 60 minutes, evidently 50 minutes instead of the original 45 doesn't cut it either. We can worry about this later.

bors r+

**Comment by postamar** [comment]
I added a commit which removes the `local-declarative-schema` logic test config, it's entirely useless now. Perhaps this will help merge this. We've had a flake and then a timeout, while the branch CI actually passed this time.

**Comment by postamar** [comment]
Hmm the more I look into it, the more those bors failures seem like unrelated flakes. I feel like a baby trying to ram a square peg through a round hole and not understanding why it's not going throught, but...

bors r+

**Comment by postamar** [comment]
Oh, what a relief. It's done.

**Pull request merged**
