### PR TITLE
release-20.1: backupccl: cluster restore import and restore jobs as canceled

### PR DESCRIPTION
**Pull request by pbardea**
First commit is a backport of https://github.com/cockroachdb/cockroach/pull/60458.

IMPORT and RESTORE may write non-transactionally, so their writes cannot
be trusted to be included in every backup. As such, they should be
restored in a reverting state to attempt to undo any of their untrusted
writes.

Release note (bug fix): IMPORT and RESTORE jobs are now restored as
reverting so that they cleanup after themselves. Previously, some of the
writes of the jobs while they were running may have been missed by
backup.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63773)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 1358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQdibO49ntImPsPq1o:-MYQdibO49ntImPsPq1p:bvjavew) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/ccl/backupccl/restore_job.go#L1358)):*
> ```Go
> 		}
> 
> 		if err := db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> ```

in 21.1 you've got a strong claim that no other instance is concurrently running. In 20.1 it's relatively best-effort. It's not likely but it is very possible. It would not hurt to re-read the details in this txn. 
___
*[pkg/ccl/backupccl/restore_job.go, line 1459 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQfkTpAlj-vQfDKDDU:-MYQfkTpAlj-vQfDKDDV:b-2rv2sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6158bdae3f0104a5d7c6d136ef0c8dbdc4629090/pkg/ccl/backupccl/restore_job.go#L1459)):*
> ```Go
> 				}
> 
> 				var updateStatusQuery strings.Builder
> ```

nit: I'd pull out the query string construction into a helper function or closure. 
___
*[pkg/ccl/backupccl/restore_job.go, line 1470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQfVhAEjYsm5U0Ph1p:-MYQfVhAEjYsm5U0Ph1q:bvy1g2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6158bdae3f0104a5d7c6d136ef0c8dbdc4629090/pkg/ccl/backupccl/restore_job.go#L1470)):*
> ```Go
> 				fmt.Fprint(&updateStatusQuery, ")")
> 
> 				fmt.Println(updateStatusQuery.String())
> ```

detritus?
___
*[pkg/ccl/backupccl/restore_test.go, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQe8dS86F3RsMMdySQ:-MYQe8dS86F3RsMMdySR:bweihd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/ccl/backupccl/restore_test.go#L13)):*
> ```Go
> import (
> 	"context"
> 	fmt "fmt"
> ```

:thinking: 
___
*[pkg/jobs/jobspb/jobs.proto, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQbYX6EGHJzMQ7DnAt:-MYQbYX6EGHJzMQ7DnAu:bopcnhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/jobs/jobspb/jobs.proto#L99)):*
> ```protobuf
>   // SystemTablesRestored keeps track of dynamic states that need to happen only
>   // once during the lifetime of a job. Note, that this state may be shared
>   // between job versions, so updates to this map must be considered carefully.
> ```

what do you mean "job versions"? 

Also, why is this in details and not progress? I imagine that it's because that ship has sailed but :(
___
*[pkg/jobs/jobspb/jobs.proto, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQbI-x8hFMfheRBetb:-MYQbI-y5wyGFxJn1Vt3:b-ljnitf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/jobs/jobspb/jobs.proto#L102)):*
> ```protobuf
>   // It maps system table names to whether or not they have already been
>   // restored.
>   map<string, bool> system_tables_restored = 17;
> ```

This has been backported to every branch after this with the same definition, right?

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63773)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/ccl/backupccl/restore_job.go, line 1358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQdibO49ntImPsPq1o:-MYR3UhiEoITCAy3XMzN:b-2o9d26) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/ccl/backupccl/restore_job.go#L1358)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

in 21.1 you've got a strong claim that no other instance is concurrently running. In 20.1 it's relatively best-effort. It's not likely but it is very possible. It would not hurt to re-read the details in this txn. 
</blockquote></details>

Moved the reading of the details to be contained within the txn.
___
*[pkg/ccl/backupccl/restore_job.go, line 1459 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQfkTpAlj-vQfDKDDU:-MYR3Y-76ZixGc3l5cyF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6158bdae3f0104a5d7c6d136ef0c8dbdc4629090/pkg/ccl/backupccl/restore_job.go#L1459)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I'd pull out the query string construction into a helper function or closure. 
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 1470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQfVhAEjYsm5U0Ph1p:-MYR3Yf22UdlbGBTMm8s:bn1lgv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6158bdae3f0104a5d7c6d136ef0c8dbdc4629090/pkg/ccl/backupccl/restore_job.go#L1470)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

detritus?
</blockquote></details>

Yep, thanks for catching. Removed.
___
*[pkg/ccl/backupccl/restore_test.go, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQe8dS86F3RsMMdySQ:-MYR3dWJ0dYrei4h2MSW:bqry65k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/ccl/backupccl/restore_test.go#L13)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:thinking: 
</blockquote></details>

Something seems to be automatically adding these. Perhaps it's something up with my VSCode setup. Looks like we have quite a few violations throughout the codebase.

Perhaps there's a way to lint against these redundant import aliases.
___
*[pkg/jobs/jobspb/jobs.proto, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQbYX6EGHJzMQ7DnAt:-MYR3sXUDi7i-MUJfR0w:b-r6psie) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/jobs/jobspb/jobs.proto#L99)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what do you mean "job versions"? 

Also, why is this in details and not progress? I imagine that it's because that ship has sailed but :(
</blockquote></details>

I think I originally meant "job implementation versions", changed to "cluster versions" for more clarity.

Ya, it is unfortunate. We already have a few of these state-tracking progress metrics in details and didn't break the momentum here. Will try to keep in mind moving forward though.
___
*[pkg/jobs/jobspb/jobs.proto, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-MYQbI-x8hFMfheRBetb:-MYR4BJO7QlfmlcJdTjq:b-qkccwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec882032156591dbb1627c231c5bea04d5dcbd0/pkg/jobs/jobspb/jobs.proto#L102)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This has been backported to every branch after this with the same definition, right?
</blockquote></details>

Yep:
20.2 - https://github.com/cockroachdb/cockroach/blob/0f4525df9397fba0d89c32cf4d8efdc869417c01/pkg/jobs/jobspb/jobs.proto#L169
21.1 - https://github.com/cockroachdb/cockroach/blob/0e1e28eb323913aa5527ad2a41f4e87e7afb3664/pkg/jobs/jobspb/jobs.proto#L192

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63773#-:-MYe4fyG0KKvkQhP1AUc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

**Comment by pbardea** [comment]
Thanks for the review!

**Pull request merged**
