### PR TITLE
roachtest: add retry loop to follower read test

### LINKED ISSUE #35030: roachtest: follower-reads/nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/8e9a1e310e3e8e37f091b7ca8bd204084ad9e2e5

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=follower-reads/nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1142461&tab=buildLog

```
The test failed on master:
	follower_reads.go:218,test.go:1212: fewer than 2 follower reads occurred: saw [0 0 0] before and [0 0 0] after

```

### PR DESCRIPTION
**Pull request by ajwerner**
In the follower read test we write some data, wait out the follower read period
and then attempt to read that data from each replica and expect to observe that
at least 2/3 will report having issued a follower read. There are several
conditions which might prevent a replica from serving a follower read.
The most pernicious is likely that new closed timestamp updates overwrite old
ones and contain new MLAI value. Even if there was some previous MLAI and
closed timestamp that a store was aware of that might have made a read safe
the new update will prevent all follower reads until the replica catches up to
this new MLAI. To make the test more robust we add a retry loop. Given that the
failures without the loop have thus far been rare and that the cluster is idle
it seems unlikely that the test will continuously fail to observe a follower
read unless something else is broken.

I ran the test successfully twice with this change before submitting this PR.

Fixes #35030.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Even if there was some previous MLAI and
> closed timestamp that a store was aware of that might have made a read safe
> the new update will prevent all follower reads until the replica catches up to
> this new MLAI.

Ugh, I was hoping something like this wouldn't be a problem in practice. But I'm confused, doesn't the closed timestamp `Provider` keep a history of closed timestamps that it looks through when determining the safety of a follower read? How did you determine that this was the situation that caused the test to fail?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35120#-:-LZFt2jE9IS0oc6G0ibD:bhbf6jl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by ajwerner** [comment]
> How did you determine that this was the situation that caused the test to fail?
You're about to be unsatisfied with my answer but I do have a better answer now. I first mostly just guessed. I did download the debug zip and started going through it. Now that you asked though, I went through it again. From the logs we can see that we do the writing around `08:32:24`, it's hard to tell exactly where the writing concludes but that's when it starts. After we write we wait 48 seconds (`30 * (1 + 3*.2)`) Which puts us at `~08:33:12`. The test grabs a debug zip at `08:33:15`. The interesting observation is that there is a lease transfer that occurs at exactly `1550392390953793906` = `08:33:10.95379` (pulled from the range info in the debug zip), so likely what happened is that the existing closed timestamp entries didn't apply because of the lease transfer and no new update had been sent yet. 

I'll update the comment to explain that it was due to lease transfer as opposed to lagging follower. 

> doesn't the closed timestamp `Provider` keep a history of closed timestamps that it looks through when determining the safety of a follower read?

It seems like we just keep a single timestamp and MLAI map which keeps maximum values. See https://github.com/cockroachdb/cockroach/blob/00670e04e90aece1d122b63e1910b7f6f629c98b/pkg/storage/closedts/storage/storage_mem.go#L167

**Comment by ajwerner** [comment]
> It seems like we just keep a single timestamp and MLAI map which keeps maximum values. See
This is wrong. We keep some buckets. Lease transfers are still a hazard. Offline we discussed a need to maintain a lease history to prevent reversions in ability to serve at a timestamp.

**Comment by nvanbenschoten** [comment]
@tbg we've talked about the issue with lease transfers and closed timestamps before. When a lease changes hands we have an initial period where we don't have a closed timestamp entry for that lease yet and can't serve follower reads on any follower. We don't currently keep a history of leases, so we can't even look back through our `closedts.Storage` to determine whether previous leases have closed out a given timestamp. But do we actually need this?

I wonder if we can treat the application of a new lease as an indication of what equates to a closed timestamp. When a new lease takes over, it won't be able to propose any commands below its `Start` timestamp. Isn't this guarantee strong enough to allow any follower who has applied the new lease to serve reads beneath this timestamp immediately?

**Comment by tbg** [comment]
That's a good observation. Sounds right to me. Looks like the "active closed timestamp" is always `max(store-wide CT, lease start ts)` (I'm assuming that there's no way the start ts can change over a sequence number through extensions or the like).

I think we back-date the start timestamp when the lease first comes online (changing hands), but that also shouldn't be a problem.

**Comment by ajwerner** [comment]
Abandoned in favor of https://github.com/cockroachdb/cockroach/pull/35130

**Pull request closed without merging**
