### PR TITLE
ui: inital nav changes

### PR DESCRIPTION
**Pull request by maxlang**
Subset of Q4 UI refresh changes
- Changes the look of the top and side nav
- Adds a select component that interacts with the URL
- Removes the subnav from the nodes list page
- The graphgroup and nodegraphs components now choose what to
display based on the URL query string.

A dependency was added on react-select and react-router was
updated to version 3.

screen shot 2016-11-10 at 12 51 39 pm
screen shot 2016-11-10 at 12 51 31 pm

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10611)

### CODE REVIEW

**Comment by maxlang** [comment]
I think maybe I should move the show/hide logic out of graphgroup and into nodegraphs.

**Comment by mrtracy** [comment]
I don't at all understand why you've connected both GraphGroup and Selector to the router state; is there some technical reason?  It seems that it would be much better for the ClusterOverview page can be connected to the router and provide those two bits of information to the underlying components as properties.

---

Review status: 0 of 25 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/ui/app/app.tsx, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFJUExHACaRFNVg0xX:-KWFJUEyTriXPMT2VyVf:b-cfhluz) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/app.tsx#L75)):*
> ```XML
>         <Route path="cluster" component={ Nodes }> {/* /cluster */}
>           <IndexRedirect to="dashboard" />
>           <Route path="dashboard" component={NodeGraphs} > {/* /cluster/dashboard */}
> ```

I'm not sure these comments are helping, the Route table is already supremely readable IMO.

---

*[pkg/ui/app/components/graphGroup.tsx, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFxBQt1vtpgRzGx-zV:-KWFxBQt1vtpgRzGx-zW:brstsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/components/graphGroup.tsx#L31)):*
> ```XML
>   static contextTypes = {
>     router: React.PropTypes.object.isRequired,
>   };
> ```

I am not sure why you went this way; why not put this logic in the render() method of the cluster page?   I think this is not a good place for this logic, this was a very simple component and now it is not.

---

*[pkg/ui/app/components/graphGroup.tsx, line 79 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFxxuhtQviOFcJvl9w:-KWFxxuhtQviOFcJvl9x:b-8kul0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/components/graphGroup.tsx#L79)):*
> ```XML
> }
> 
> export default connect()(GraphGroup);
> ```

Why does this need to be connected?

---

*[pkg/ui/app/components/selector.tsx, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFyGhDiZZohaY7F48V:-KWFyGhDiZZohaY7F48W:bjzcxj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/components/selector.tsx#L75)):*
> ```XML
> }
> 
> // We need to connect to populate the router details.
> ```

I don't think connect is necessary for router details.  The router is provided through a react-router context, connect is a _redux_ concept. They are not related.

---

*[pkg/ui/app/containers/nodes.tsx, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFzwYuxXEgx_vHOtUJ:-KWFzwYuxXEgx_vHOtUK:balw0wr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/containers/nodes.tsx#L41)):*
> ```XML
>   }
> 
>   componenetWillMount() {
> ```

typo, this won't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-:-KWG-WnmG-vtEl8BGP7b:b-e3l3yv)*

**Comment by maxlang** [comment]
I connected `Selector` to the router state because I felt they were basically navigation components. I wanted them to act like links in that selecting an option would navigate to a specific page.

I agree that other components shouldn't interact with the route directly so I've removed that logic and made the `Selector` component use callbacks to communicate with its parent component.

---

Review status: 0 of 26 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/ui/app/app.tsx, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFJUExHACaRFNVg0xX:-KWPCBhFqFVzaee4VA32:b-ujmsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/app.tsx#L75)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I'm not sure these comments are helping, the Route table is already supremely readable IMO.
</details>
Yeah was just helping me keep track. Removed.

---

*[pkg/ui/app/components/graphGroup.tsx, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFxBQt1vtpgRzGx-zV:-KWPCLmZlMAxKx2mKHZl:b-mq1zbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/components/graphGroup.tsx#L31)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I am not sure why you went this way; why not put this logic in the render() method of the cluster page?   I think this is not a good place for this logic, this was a very simple component and now it is not.
</details>
I had second thoughts after I got it working. Mostly reverted and moved that logic out.

---

*[pkg/ui/app/components/graphGroup.tsx, line 79 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFxxuhtQviOFcJvl9w:-KWPCgYVyGHQJ3mPvkdp:bvt2qjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/components/graphGroup.tsx#L79)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Why does this need to be connected?
</details>
Weird I thought I read some sourcecode somewhere that showed this was how the router info was injected. Looks like it's unnecessary.

---

*[pkg/ui/app/components/selector.tsx, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFyGhDiZZohaY7F48V:-KWPH0lXDT5GXhQj5Hkc:b-c54xq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/components/selector.tsx#L75)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I don't think connect is necessary for router details.  The router is provided through a react-router context, connect is a _redux_ concept. They are not related.
</details>
You're right. I thought `react-redux-router` did some magic but I clearly misremembered.

---

*[pkg/ui/app/containers/nodes.tsx, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-KWFzwYuxXEgx_vHOtUJ:-KWPHaM9PY_kubuQ8muK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33088edfffc01c9d21580f0ab862c51292309694/pkg/ui/app/containers/nodes.tsx#L41)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> typo, this won't work.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-:-KWPHC1RzdWS4REWJQhw:becp3by)*

**Comment by mrtracy** [comment]
LGTM

---

Review status: 0 of 26 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10611#-:-KWTtBYsrWQo5G5woBxH:bb6ywmx)*

**Pull request merged**
