### PR TITLE
sql: eliminate tableVersionState reference to leaseState 

### PR DESCRIPTION
**Pull request by vivekmenezes**

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I'm making another update to this PR

**Comment by vivekmenezes** [comment]
ready for review

**Comment by andreimatei** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/sql/lease.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf1Mzw4WVaWuQjr2Wv:-Knf1Mzw4WVaWuQjr2Ww:b-a0tnnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L59)):*
> ```Go
> )
> 
> type leaseState struct {
> ```

consider adding a comment here linking the expiration of this lease to the expiration field of the parent `tableVersionState`.

Even better, I think I would have kept the `expiration` field here as a `DTimestamp`, and have another expiration field in the `tableVersionState` which would only be initialized when the tvs does not correspond to a lease (and have some accessor methods on top of the two fields for clients who don't care about lease vs non-lease).

---

*[pkg/sql/lease.go, line 78 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-KnepuWxTYJYXCPwVbMv:-KnepuWxTYJYXCPwVbMw:b-t4p9tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L78)):*
> ```Go
> 	// The expiration time for the table version. There are three cases to
> 	// consider here.
> 	// 1. The latest version v "known" to the node: This table descriptor version
> ```

Since there's no `v` field in this struct, I found this comment a bit confusing. It's not clear if this field is to be interpreted differently based on something, or if you're explaining how its value was derived. Perhaps clarify that it's the latter. And also consider adding more words around the "expiration time for the table version", tieing it to transaction timestamps.

---

*[pkg/sql/lease.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf0OaTJCqn-darp_6w:-Knf0OaTJCqn-darp_6x:b-87tvzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L150)):*
> ```Go
> }
> 
> func leaseExpiration(expiration hlc.Timestamp) parser.DTimestamp {
> ```

This method deserves a comment.

---

*[pkg/sql/lease.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf0SPLRKg0u1lXuL2r:-Knf0SPLRKg0u1lXuL2s:b-5cnrpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L150)):*
> ```Go
> }
> 
> func leaseExpiration(expiration hlc.Timestamp) parser.DTimestamp {
> ```

In case we keep the code as written, as opposed to taking the suggestion above about the different expiration fields), I think it'd be a better API if this were a method on the `tableVersionState` and it'd assert that the tvs corresponds to a lease.

---

*[pkg/sql/lease.go, line 61 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf40x9Es9Od09FPYS3:-Knf40x9Es9Od09FPYS4:b-n7bgzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L61)):*
> ```Go
> // tableVersionState holds the state for a table version. This includes
> // the lease information for a table version.
> // TODO(vivek): A node only needs to manage lease information on what it
> ```

has this TODO been satisfied?

---

*[pkg/sql/lease.go, line 84 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf59iUd5R0LrXJoj1p:-Knf59iUd5R0LrXJoj1q:b-holg5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L84)):*
> ```Go
> 	mu       syncutil.Mutex
> 	refcount int
> 	// Set if this table version is leased. The table name cache is only
> ```

s/Set if this table version is leased/Set if the node has a lease on this descriptor

and explain that the lease can be released, and then the `tableVersionState` can continue to exist with this set to false.

And also consider explaining that this field exists because `expiration` needs to be updated when `lease` goes from true to false, rather than the "table name cache" reference. And also see the next point :)

---

*[pkg/sql/lease.go, line 85 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf6RoxZ_5ZR72WHTyA:-Knf6RoxZ_5ZR72WHTyB:b-pab9wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L85)):*
> ```Go
> 	refcount int
> 	// Set if this table version is leased. The table name cache is only
> 	// allowed to hand out tables that are leased.
> ```

I question this "table name cache can only hand out...". I think that need not be the case,  if we'd update the expiration time of the `tableVersionState` when we set `leased` to `false`. And that's also kinda the point of these changes, right - untangling descriptors and leases.

---

*[pkg/sql/lease.go, line 519 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf39nbrIX8gia_QdHV:-Knf39nbrIX8gia_QdHW:b-d3uwdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L519)):*
> ```Go
> 	// Protects both active and acquiring.
> 	mu syncutil.Mutex
> 	// The active leases for the table: sorted by their version and expiration
> ```

is this comment still accurate?

---

*[pkg/sql/lease.go, line 661 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf5fHJIWx_UW6d6FmJ:-Knf5fHJIWx_UW6d6FmK:b8u0qur) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L661)):*
> ```Go
> 	table.refcount += s.refcount
> 	s.refcount = 0
> 	s.leased = false
> ```

shouldn't we also update `s`'s expiration time here?

---

*[pkg/sql/lease.go, line 679 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf5tEfuoFUBDqH8RY5:-Knf5tEfuoFUBDqH8RY6:b-gmn0nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L679)):*
> ```Go
> 			defer table.mu.Unlock()
> 			if table.refcount == 0 {
> 				table.leased = false
> ```

ditto: should we update the expiration time? I see that we're removing the tvs from the `tableState`, but still. I think it'd be a good idea to wrap `leased = false` in a method on the tvs that also updates the expiration time, to make sure that the two fields are not divorced from one another.

---

*[pkg/sql/lease.go, line 772 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf6G-TfulZwyMtM-2t:-Knf6G-Uid0zWLFNgVaF:bvf070w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L772)):*
> ```Go
> 		}
> 		if s.refcount == 0 && removeOnceDereferenced {
> 			s.leased = false
> ```

ditto about expiration time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/lease.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf1Mzw4WVaWuQjr2Wv:-Knjf8rnoS_e_1MJC9DX:bsy3vgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L59)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider adding a comment here linking the expiration of this lease to the expiration field of the parent `tableVersionState`.

Even better, I think I would have kept the `expiration` field here as a `DTimestamp`, and have another expiration field in the `tableVersionState` which would only be initialized when the tvs does not correspond to a lease (and have some accessor methods on top of the two fields for clients who don't care about lease vs non-lease).
</blockquote></details>

I've completed eliminated this struct in this PR! See the other commit

---

*[pkg/sql/lease.go, line 78 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-KnepuWxTYJYXCPwVbMv:-KnjrWpcg0a6r07ggjty:b-eg9hf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L78)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Since there's no `v` field in this struct, I found this comment a bit confusing. It's not clear if this field is to be interpreted differently based on something, or if you're explaining how its value was derived. Perhaps clarify that it's the latter. And also consider adding more words around the "expiration time for the table version", tieing it to transaction timestamps.
</blockquote></details>

I've rewritten this comment and the one below. Hope it makes sense now.

---

*[pkg/sql/lease.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf0SPLRKg0u1lXuL2r:-KnjunPzwBs4pk8X14xG:b-ura8il) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L150)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

In case we keep the code as written, as opposed to taking the suggestion above about the different expiration fields), I think it'd be a better API if this were a method on the `tableVersionState` and it'd assert that the tvs corresponds to a lease.
</blockquote></details>

Done. But unfortunately ```leased``` is already set to false before we call release() so we cannot panic on an invariant here.

---

*[pkg/sql/lease.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf0OaTJCqn-darp_6w:-Knjwhf5qwFTn4v_ALBU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L150)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This method deserves a comment.
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 61 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf40x9Es9Od09FPYS3:-KnjfPf2sibFlnb8FyHD:ba93fbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L61)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

has this TODO been satisfied?
</blockquote></details>

Not yet. All our table versions still have leases.

---

*[pkg/sql/lease.go, line 84 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf59iUd5R0LrXJoj1p:-KnjrdhyqwDKpHYv8HmZ:bdd22uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L84)):*
> Set if the node has a lease on this descriptor
rewritten this comment

---

*[pkg/sql/lease.go, line 85 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf6RoxZ_5ZR72WHTyA:-Knjg3iVDRVkoq7tfJ2x:b42fc50) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L85)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I question this "table name cache can only hand out...". I think that need not be the case,  if we'd update the expiration time of the `tableVersionState` when we set `leased` to `false`. And that's also kinda the point of these changes, right - untangling descriptors and leases.
</blockquote></details>

updated this comment. It also doesn't talk about the table name cache.

---

*[pkg/sql/lease.go, line 519 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf39nbrIX8gia_QdHV:-KnjvpKi7fY2XWrPvMrt:b-6pbmx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L519)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this comment still accurate?
</blockquote></details>

Reworded to remove the reference to expiration.

---

*[pkg/sql/lease.go, line 661 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf5fHJIWx_UW6d6FmJ:-KnjvwdFK2VWNlTA5ysd:b-o3v6cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L661)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

shouldn't we also update `s`'s expiration time here?
</blockquote></details>

No it is removed from the list. We do not plan to leave older versions in there unless they are needed. I'm going to send you another PR with that later.

---

*[pkg/sql/lease.go, line 679 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf5tEfuoFUBDqH8RY5:-KnjwCu6bBGke50TmyEl:btas7x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L679)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ditto: should we update the expiration time? I see that we're removing the tvs from the `tableState`, but still. I think it'd be a good idea to wrap `leased = false` in a method on the tvs that also updates the expiration time, to make sure that the two fields are not divorced from one another.
</blockquote></details>

the expiration time is immutable for now. I'm working on another PR which maintains that property but now I'm not sure if it's worth it. to be seen later.

---

*[pkg/sql/lease.go, line 772 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf6G-TfulZwyMtM-2t:-KnjweH71sV1m8BPQZsv:bjkz1a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L772)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ditto about expiration time
</blockquote></details>

ok, for later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/lease.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf0SPLRKg0u1lXuL2r:-Knkm4Dz7u3EfoU0-v9t:brqq7wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L150)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Done. But unfortunately ```leased``` is already set to false before we call release() so we cannot panic on an invariant here.
</blockquote></details>

hmm in that case, I take my suggestion back :)
Calling `leaseExpiration` on a tvs that doesn't correspond to a lease seems funky.

I think I would have preferred if we kept some structure around corresponding to leases (the `leaseState`). And that guy could have an expiration time of the correct type, divorced from the expiration of a `tvs`.

---

*[pkg/sql/lease.go, line 661 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf5fHJIWx_UW6d6FmJ:-KnknHt5sKJvqGkVwuYF:b-xqtkbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L661)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

No it is removed from the list. We do not plan to leave older versions in there unless they are needed. I'm going to send you another PR with that later.
</blockquote></details>

I see that now they're being removed, but I wonder if doing some sort of cleanup would be a good idea anyway. Or perhaps this point would become moot if interfaces were such that `tvs` with `failed == false` is immediately taken out of the structure. Which I think would mean that there's no point in the `leased` field.

As far as I'm concerned, this big change sequence of changes would better be done in one commit, otherwise the review is less meaningful.

---

*[pkg/sql/lease_test.go, line 675 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knkp9D_FgYrGkKrJlz3:-Knkp9D_FgYrGkKrJlz4:bq0v1zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/560cf92529cfa768816250db5326682b526077fd/pkg/sql/lease_test.go#L675)):*
> ```Go
> }
> 
> // TestTxnObeysLeaseExpiration tests that a transaction is aborted when it
> ```

So what replaces this test?
I think we want to test that a serializable transaction acquires new leases when it's retried, and that a snapshot txn does not commit past its deadline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-:-Knkq42vAS0iRhE1u4T3:bnfp4nl)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/lease.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf0SPLRKg0u1lXuL2r:-Knld4kzBXmfe4W3CyUL:b9rh1ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0b9baf9c9f2e6314ce5247323372f5c3220d326/pkg/sql/lease.go#L150)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

hmm in that case, I take my suggestion back :)
Calling `leaseExpiration` on a tvs that doesn't correspond to a lease seems funky.

I think I would have preferred if we kept some structure around corresponding to leases (the `leaseState`). And that guy could have an expiration time of the correct type, divorced from the expiration of a `tvs`.
</blockquote></details>

I'm going to leave it as is for now. Right now all the tvs have a lease associated with them.

---

*[pkg/sql/lease.go, line 661 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knf5fHJIWx_UW6d6FmJ:-KnlaqR6lJQlghEustV1:b85r0zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90b060941ee0d51b1af7430adcf0a844d1ecea7/pkg/sql/lease.go#L661)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see that now they're being removed, but I wonder if doing some sort of cleanup would be a good idea anyway. Or perhaps this point would become moot if interfaces were such that `tvs` with `failed == false` is immediately taken out of the structure. Which I think would mean that there's no point in the `leased` field.

As far as I'm concerned, this big change sequence of changes would better be done in one commit, otherwise the review is less meaningful.
</blockquote></details>

I'm actually not sure where all this is heading. I make some progress and then I realize it needs to be refactored more and send you PRs. I think we now have a better base from which to make further changes.

At the moment the worst part about the design is the tableNameCache. It's not a nice thing hanging on by the side.

---

*[pkg/sql/lease_test.go, line 675 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707#-Knkp9D_FgYrGkKrJlz3:-Knl_Xla8JxIR5XeAz4e:bqfbsgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/560cf92529cfa768816250db5326682b526077fd/pkg/sql/lease_test.go#L675)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So what replaces this test?
I think we want to test that a serializable transaction acquires new leases when it's retried, and that a snapshot txn does not commit past its deadline.
</blockquote></details>

Well this test was not really testing anything. I agree we need more tests here. I'm leaving #6050 open for now for this work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16707)*

**Pull request merged**
