### PR TITLE
ui: Improve UX when jobs page times out

### LINKED ISSUE #66607: ui: Jobs page in DB Console throws an error
**Describe the problem**

Reported by @chudro 

A user reported seeing an error when attempting to load the Jobs page within the DB Console. Specifically, a `Promise timed out after 30000 ms` error

**To Reproduce**

Currently seen in a 21.1.2 cluster

Image 2021-06-17 at 2 50 15 PM

Jira issue: CRDB-8145

### PR DESCRIPTION
**Pull request by jocrl**
Partially fixes #66607 and #71343.

This commit:
- Increases the Jobs page API timeout from 30 seconds to 1 minute.
- Adds an informational message after 2 seconds of loading indicating that
  loading might take a while, and that filtering can help.
- Improves the timeout error message, and suggests that filtering can help.
- Adds a more informative console.error, that will log to DataDog after the Jobs
  page is added to CC Console.
- Moves stories to the parent `JobsTable` component and adds stories for loading
  and error states.

Unrelated to the Jobs page, this commit also:
- Adds a previously intended but missing 2 second delay to the information
  message in the Transactions table, to make it similar to that of the
  Statements table.
- Fixes broken cluster-ui storybook.

Release note (ui): Previously, when the Jobs page timed out, it would have the
message "Promise timed out after 30000 ms". Now, it has a more helpful error
message, and an information message that appears after 2 seconds of loading and
indicates that the loading might take a while.

Before:
image

After:
First 2 seconds
image

2s - 1min
image

After 1 min timeout
image

### CODE REVIEW

**Comment by jocrl** [comment]
Hi @stbof, @maryliag, @kevin-v-ngo, and @Annebirzin 

So I'm working on improving the user experience when users hit a timeout the jobs page (to help with issues https://github.com/cockroachdb/cockroach/issues/66607 and https://github.com/cockroachdb/cockroach/issues/71343). I'm putting up this draft PR cos I'd like to get some product feedback, specifically round text and wording.

I'm
1) Increasing the time out from 30 seconds -> 1 minute (currently trying to get this working, the param that I thought would control things doesn't seem to work).

2) Adding an info message that appears after the page has been loading for 10 seconds, letting the user know that this might take a while. My rationale with the delay is that this time out seems uncommon, and that if the table returns in <30 seconds there's no need to show users a message that they might have trouble quickly reading. My draft text is:
	> If the Jobs table contains a large amount of data, this page might take a while to load.

	I also took the liberty of adding this 30 second delay to the message for the statement and transactions table, with the same rationale that if it returns quickly it might feel like you get a split second to read disappearing text.

3) Modifying the error message for when the page times out. My draft text is
	> Time out while attempting to retrieve the Jobs table. As an alternative, try filtering the table.

I'd appreciate thoughts in general on these choices, but wanted to specifically ask:

a) Any feedback on the long loading message text?
For reference, [this is](https://github.com/cockroachdb/cockroach/pull/77008/files#diff-b7e775c116135547929b4e0aa104a33aa09a26137d076187cbbc7e1504f1acb0R596) the statements page info text for long loading times.

b) Any feedback on the timeout error message text? These additional things below are a few things we _could_ tell the user, but I'm thinking we should just leave this to our knowledge and I'll add them to our runbook for known issues.
- What SQL query used to query the jobs table, and about collecting a statement bundle for that query to troubleshoot a potentially long query
- To potentially check node latency
- File an issue with us, and tag @sql-obs? I'm adding a console.error, but I believe on DB Console we won't get notified via DataDog.

Also not sure if we should omit trying filtering from the error message text.

**Review by maryliag — COMMENTED** [review]
1. Sounds good
2. The delay on the message sounds good. I added a note about the statement/transaction page, because they already had a delay, so you might want to remove that and just use the new component
3. I would let Anne/Kevin/Stephanie take on this one
a) it does sounds good to me
b) Does the filtering occurs on the backend or frontend?  I don't think you need to tell the user any of those extra info there. If they hit this issue, they can reached out and we can do more investigation. And you're correct, we don't send info for things only on db console. On the good side, we will be moving the jobs table to cluster-ui and cc console, so then we can add more logging when that happens

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-:-N0m30erATKM4ZHnazzh:b7u7wrj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-N0m2e0Y4bhX-_N4GwpP:-N0m2e0Y4bhX-_N4GwpQ:b-7ma3w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/57e9c0b04f62313d1ac5de92694d085ffdc3c4b2/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L627)):*
> ```XML
>       timeWaitingResponse > 2 &&
>       isNil(getValidErrorsList(this.props.statementsError)) && (
>         <Delayed>
> ```

2 lines above there is a `timeWaitingResponse > 2`, that is already adding the delay before showing this message. If you're using this new component, you can remove that extra check

**Comment by stbof** [comment]
I should have paid more attention but this message - If the selected time period contains a large amount of data, this page might take a few minutes to load. - on the Statements page seems totally wrong to me. Who could stand to (bother with) waiting a few minutes for a page load? This seems like a product implementation problem. The product should be able to figure out that the customer is asking for too much data and tell them right away that they should scope down the request.

As far as the Jobs table is concerned, certainly returning an internal message like "Promise timed out" is awful UI. 

I have the same comment though about trying to tell folks to sit tight and wait for the Jobs table to load.  Can't we give helpful information sooner. Something to the effect of:

Unable to retrieve the Jobs table. To reduce the amount of data, try filtering the table.

**Comment by jocrl** [comment]
Thanks everyone,

@maryliag,
> Does the filtering occurs on the backend or frontend?

The filtering for top 50 (or sorting by most recent if "All" is selected) is done on the back end, as part of the SQL query.

@stbof,
> Unable to retrieve the Jobs table. To reduce the amount of data, try filtering the table.

Got it, thanks!

> Anyway, isn't the solution in scenarios like this to paginate?

Yes, and no. The limitation is that when we want things to be sorted (as is the case in the stmt/txn/job tables), unless we store indices on the things we want to sort by, we still need to look at all the things we potentially want to sort by in order  to determine the top. The jobs table already limits to showing the top 50. There's also added complexity (at least, still not 100% clear to me personally) about the `crdb_internal` vs `system` tables, and I know there's more going on with the stmt/txn ones.

That said, the jobs table is by default limited to the 50 most recent jobs (with further front end filtering), unlike the stmt/txn tables which have more sorting options. So maybe we can make use of that.

**Review by maryliag — COMMENTED** [review]
> The filtering for top 50 (or sorting by most recent if "All" is selected) is done on the back end, as part of the SQL query.
sorry, I should have been more clear, I was asking if the other filters (status and type) are done in front or back, because if those are front I don't want to give the wrong impression that adding those filters will make it faster, meaning adding a filter might not help so we should avoid giving that suggestion

> on the Statements page seems totally wrong to me. Who could stand to (bother with) waiting a few minutes for a page load? 
That is the point of that message. By default the period selected shouldn't have a large amount of data, but the user might select a larger period with a lot of data because they decided they _want_ to see all of that and in this case we want to tell them "yes, you can see this large amount of data, but hang on a little because we need to calculate a lot of data to show you, so sit tight and we got you" :smile: 

> isn't the solution in scenarios like this to paginate?
As Josephine pointed out, the pagination on this case is not simple or straight forward. It's an area of improvement that we're aware, but will take time to be addressed and we're giving the users options in the meantime

> There's also added complexity about the crdb_internal vs system tables
the system tables are real tables and the crdb_internal are actually views on top of them, where we do some extra aggregations, try to add filters and so on, and we use the crdb internal on those pages and the time is taking is because of those extra aggregations we need to do (which is also why creating pagination is not so simple)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-:-N0pqbDG47FkNIfiusSj:b77p1vv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @maryliag)

**Comment by stbof** [comment]
> > The filtering for top 50 (or sorting by most recent if "All" is selected) is done on the back end, as part of the SQL query.
> > sorry, I should have been more clear, I was asking if the other filters (status and type) are done in front or back, because if those are front I don't want to give the wrong impression that adding those filters will make it faster, meaning adding a filter might not help so we should avoid giving that suggestion
> 
> > on the Statements page seems totally wrong to me. Who could stand to (bother with) waiting a few minutes for a page load?
> > That is the point of that message. By default the period selected shouldn't have a large amount of data, but the user might select a larger period with a lot of data because they decided they _want_ to see all of that and in this case we want to tell them "yes, you can see this large amount of data, but hang on a little because we need to calculate a lot of data to show you, so sit tight and we got you" 😄
> 
> > isn't the solution in scenarios like this to paginate?
> > As Josephine pointed out, the pagination on this case is not simple or straight forward. It's an area of improvement that we're aware, but will take time to be addressed and we're giving the users options in the meantime
> 
> > There's also added complexity about the crdb_internal vs system tables
> > the system tables are real tables and the crdb_internal are actually views on top of them, where we do some extra aggregations, try to add filters and so on, and we use the crdb internal on those pages and the time is taking is because of those extra aggregations we need to do (which is also why creating pagination is not so simple)
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-:-N0pqbDG47FkNIfiusSj:b77p1vv)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @maryliag)

Thank you for the explanation about the challenges in paginating.

I still wonder if folks will be willing to wait for _a few minutes_ for anything.  Also, just giving a message that they might have to wait for an indeterminate number of minutes is only giving the user the option to bail out of waiting. If it's only the time period that's causing that long wait time, maybe the Statements message could be updated to indicate that, so the user does have the option to shorten the time period to reduce the wait.

**Comment by Annebirzin** [comment]
Just catching up here. A couple of thoughts on the blue loading state:
- we might want to show the blue message earlier that 30 seconds. I want to say we show it after 5 seconds on the statements page? (We should be consistent across both)
- Maybe we can include similar messaging on the blue loading state that we have on the red timeout state that says '...To reduce the amount of data, try filtering the table.'

**Comment by jocrl** [comment]
Thanks everyone!

> if the other filters (status and type) are done in front or back

@maryliag, Status and type are done in the back :)

> we might want to show the blue message earlier that 30 seconds. I want to say we show it after 5 seconds on the statements page? (We should be consistent across both)

@Annebirzin, sounds good. To clarify, are you thinking 5 seconds for all three of the statements, transactions, and jobs pages?

>Maybe we can include similar messaging on the blue loading state that we have on the red timeout state that says '...To reduce the amount of data, try filtering the table.'

@Annebirzin, sounds good, will do this for the jobs table.

**Comment by maryliag** [comment]
if we want to be consistent, the statements and transactions page are waiting 2 seconds

**Comment by jocrl** [comment]
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-N14SApF-haHaVN3KdEf:-N14SApF-haHaVN3KdEg:bnm57lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae702bc16e4a8dc927231aef45fd73533a666154/pkg/ui/workspaces/db-console/src/util/api.ts#L464)):*
> ```XML
>   const url = `${API_PREFIX}/jobs?status=${req.status}&type=${req.type}&limit=${req.limit}`;
>   return timeoutFetch(serverpb.JobsResponse, url, null, timeout).then(
>     (response: JobsResponseMessage) => response,
> ```

I initially tried a catch block here, but couldn't figure out how to appease typescript (see screenshot for the error). So this line is kind of weird with the redundant resolve function, but it appeases typescript 🤔

**Comment by jocrl** [comment]
Made the timeout for all three (Statements, Transactions, and Jobs) 2 seconds, and undrafting.

**Review by maryliag — COMMENTED** [review]
looking good, just a few questions from me :) 

> Reviewed 3 of 8 files at r1, 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-:-N15ib5T1znHhetQatlM:b-x4g1a4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @maryliag)

___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-N15hUv-9WrI504FWvj-:-N15hUv-9WrI504FWvj0:b-nterrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae702bc16e4a8dc927231aef45fd73533a666154/pkg/ui/workspaces/db-console/src/util/api.ts#L185)):*
> ```XML
>     super(message);
> 
>     // Maintains proper stack trace for where our error was thrown (only available on V8)
> ```

comment a little confusing, V8 of what?
___
*[`pkg/ui/workspaces/db-console/src/views/jobs/jobTable.fixture.ts` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-N15iN38-5pBqlXgBnnn:-N15iN38-5pBqlXgBnno:bmuuh2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdd96b38f5b67c655a5697b6bf493b2c59041c1/pkg/ui/workspaces/db-console/src/views/jobs/jobTable.fixture.ts#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

why was this removed?

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-N0m2e0Y4bhX-_N4GwpP:-N161ns33BYxjx8jiG2v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57e9c0b04f62313d1ac5de92694d085ffdc3c4b2/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L627)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

2 lines above there is a `timeWaitingResponse > 2`, that is already adding the delay before showing this message. If you're using this new component, you can remove that extra check
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-N15hUv-9WrI504FWvj-:-N161mJM7mbyLa1Vlfjt:brjzvnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae702bc16e4a8dc927231aef45fd73533a666154/pkg/ui/workspaces/db-console/src/util/api.ts#L185)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

comment a little confusing, V8 of what?
</blockquote></details>

Right, does this help?



_Code quote:_
```XML
// Maintains proper stack trace for where our error was thrown
```
___
*[`pkg/ui/workspaces/db-console/src/views/jobs/jobTable.fixture.ts` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-N15iN38-5pBqlXgBnnn:-N160YDn1TKtCTkai5n2:bm2rpaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdd96b38f5b67c655a5697b6bf493b2c59041c1/pkg/ui/workspaces/db-console/src/views/jobs/jobTable.fixture.ts#L1)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why was this removed?
</blockquote></details>

By mistake 🙃. Fixed, thanks! This is a new file where a lot was copied over from the deleted one.

**Comment by jocrl** [comment]
Took out the stacktrace capture to satisfy the linter; PTAL 🙏

For future reference, see [this thread](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1651589882897039?thread_ts=1651589757.556669&cid=CJ0H8Q97C).

**Comment by jocrl** [comment]
@maryliag, I assuming I need approval that I've addressed your questions?

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80743#-:-N1EX0zDAWY1nFYaDYOa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by jocrl** [comment]
Thanks for everyone's input!

bors r+

**Pull request merged**
