### PR TITLE
roachtest: fix multitenant-upgrade expected error

### LINKED ISSUE #94748: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8192493?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8192493?buildTab=artifacts#/multitenant-upgrade) on master @ [d1233022fc2f67a3901c0be08ec71abb13b1e8fe](https://github.com/cockroachdb/cockroach/commits/d1233022fc2f67a3901c0be08ec71abb13b1e8fe):

```
test artifacts and logs in: /artifacts/multitenant-upgrade/run_1
(sql_runner.go:154).ExpectErr: expected error 'pq: preventing tenant upgrade from running as the host cluster has not yet been upgraded: host cluster version = 22.2, tenant cluster version = 22.2', got: pq: preventing tenant upgrade from running as the storage cluster has not yet been upgraded: storage cluster version = 22.2, tenant cluster version = 22.2
(cluster.go:1933).Run: cluster.RunE: context canceled
(cluster.go:1933).Run: cluster.RunE: context canceled
(cluster.go:1933).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23118

### PR DESCRIPTION
**Pull request by healthy-pod**
In #94669, we changed usages of `host cluster` to
`storage cluster` because `host cluster` is specific to `CC Serverless`.

This change updates the expected
error in `multitenant-upgrade` and some other usages of `host cluster`.

Epic: none
Release note: None

Closes #94748

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
:lgtm: 

Thanks for getting to this one so quickly!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94947#-:-NLNBHDl5mTPsK3aojT2:b9lphbt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

**Comment by healthy-pod** [comment]
TFTR!

bors r=ajstorm

**Comment by healthy-pod** [comment]
bors r=ajstorm single on

**Comment by healthy-pod** [comment]
bors single on

**Comment by healthy-pod** [comment]
bors r+
bors single on

**Pull request merged**
