### PR TITLE
backupccl: add gzip compression for Manifest and PartitionDescriptor

### LINKED ISSUE #48252: backupccl: gzip BACKUP MANIFEST file
The backup manifest is the file the contains all of the metadata of a backup. It holds information such as which tables are backed up and various information about the backup. 

There are a host of reasons that it would be beneficial for the backup manifest to be smaller. For example, in incremental backups we download all of the manifests of all previous backups.

(And while we're here it would be nice to finish off https://github.com/cockroachdb/cockroach/pull/44866 by renaming the file itself.)

### PR DESCRIPTION
**Pull request by Anzoteh96**
Backup manifests are metadata stored during a backup process, and are frequently downloaded. This PR compresses data from manifest files (and partition descriptor files) into gzip format to save space and reduce the amount of data needed to be downloaded.

Data are compressed using the `NewWriter` object in `compress/gzip`. The type of data buffer content is checked using `http.DetectContentType` before being unzipped by `NewReader` object in `compress/gzip`, as necessary.

Fixes #48252. 
Release note: None

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
This is looking good! Added some comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-:-M7mpKbp-BZPt0PWL1N8:bqkq734)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mpWuw4LGmLRnsZade:-M7mpWuw4LGmLRnsZadf:bb2cv77) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/backup_test.go#L420)):*
> ```Go
> 					fileType := http.DetectContentType(backupPartitionBytes)
> 					if fileType != zipType {
> 						t.Errorf("Expect partition descriptor files to be compressed but the format is" + fileType)
> ```

super-minor-nit: we usually don't capitalize failure messages
___
*[pkg/ccl/backupccl/manifest_handling.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7macMR0wH08dCJw4iE:-M7macMR0wH08dCJw4iF:b-9prgmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L52)):*
> ```Go
> 	BackupFormatDescriptorTrackingVersion uint32 = 1
> 	// zipType is the format of a GZipped compressed file.
> 	zipType = "application/x-gzip"
> ```

I think we can probably export this constant (capitalize this first letter), so that we can re-use it in the tests (`backupccl.ZipType`), rather than re-defining it.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mi-6qBaY2Urv7b4_7:-M7mi-6qBaY2Urv7b4_8:b-i10mfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L199)):*
> ```Go
> 		if err != nil {
> 			return BackupPartitionDescriptor{}, err
> 		}
> ```

We probably want to `defer r.Close()` here after we know we've opened a reader to ensure it gets closed. We also use the reader and writer a couple of times, so I would not be opposed to moving them out to helper functions in this file. Additionally, if we add the helper function, we could wrap any error that it returns (e.g. `errors.Wrap(err, "decompressing backup manifest")`).
___
*[pkg/ccl/backupccl/manifest_handling.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mZLXoDB7gB7pCdE_U:-M7mZLXoDB7gB7pCdE_V:bwlwf0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L239)):*
> ```Go
> 	}
> 	// This part of the code applies GZip compression to BackupManifest.
> 	b := bytes.NewBuffer([]byte{})
> ```

I think I mostly likely mixed up the order when we were chatting about this - sorry about that - but I think we actually want to compress the data before encryption. Since encryption turns the manifest into high-entropy data, it'll likely compress much better if it is compressed prior to encryption.

nit: giving this a bit of a more descriptive name may also be nice. Maybe something like `gzipBuf`.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7miqf6BxsA_Gp8o_cL:-M7miqf6BxsA_Gp8o_cM:bn7x1fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L241)):*
> ```Go
> 	b := bytes.NewBuffer([]byte{})
> 	gz := gzip.NewWriter(b)
> 	gz.Write(descBuf)
> ```

I believe both the calls to `Write` and `Close` could return errors - we should check for those.

**Review by Anzoteh96 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mpWuw4LGmLRnsZade:-M7nW9zw54AvWchK9eSs:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/backup_test.go#L420)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

super-minor-nit: we usually don't capitalize failure messages
</blockquote></details>

Done. 
___
*[pkg/ccl/backupccl/manifest_handling.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7macMR0wH08dCJw4iE:-M7nWCQuEyb2Ak0iR3Sn:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L52)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think we can probably export this constant (capitalize this first letter), so that we can re-use it in the tests (`backupccl.ZipType`), rather than re-defining it.
</blockquote></details>

Done. 
___
*[pkg/ccl/backupccl/manifest_handling.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mi-6qBaY2Urv7b4_7:-M7nWE4K-BmH4vEV26kq:bu2ajyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L199)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

We probably want to `defer r.Close()` here after we know we've opened a reader to ensure it gets closed. We also use the reader and writer a couple of times, so I would not be opposed to moving them out to helper functions in this file. Additionally, if we add the helper function, we could wrap any error that it returns (e.g. `errors.Wrap(err, "decompressing backup manifest")`).
</blockquote></details>

I moved these into the helper functions (`compressFile` and `DecompressAndCheckFile`), the latter was exported as there were two tests that directly read backupManifest from file, and therefore has to be decompressed. The `DecompressAndCheckFile` function has the `defer r.Close()` statement in it. 

I also wrapped the error in the individual functions `readBackupManifest` and `readBackupPartitionDescriptor` since technically the messages have to be different ("decompressing backup manifest" vs "decompressing backup partition descriptor"). 
___
*[pkg/ccl/backupccl/manifest_handling.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mZLXoDB7gB7pCdE_U:-M7nXOBV1qW_n34m8AXN:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L239)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think I mostly likely mixed up the order when we were chatting about this - sorry about that - but I think we actually want to compress the data before encryption. Since encryption turns the manifest into high-entropy data, it'll likely compress much better if it is compressed prior to encryption.

nit: giving this a bit of a more descriptive name may also be nice. Maybe something like `gzipBuf`.
</blockquote></details>

Done. 
___
*[pkg/ccl/backupccl/manifest_handling.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7miqf6BxsA_Gp8o_cL:-M7nXPX-9rsWw0oJ0I_x:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/manifest_handling.go#L241)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I believe both the calls to `Write` and `Close` could return errors - we should check for those.
</blockquote></details>

Done.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mpWuw4LGmLRnsZade:-M7sak4968CccEiPCKbg:b-ndy3rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/backup_test.go#L420)):*
> ```
> 					if fileType != backupccl.ZipType {
> 						t.Errorf("expect partition descriptor files to be compressed but the format is" + fileType)
> ```
require.Equal(t, fileTYpe, backupccl.ZipType)
___
*[pkg/ccl/backupccl/backup_test.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7sadMk9Oc8goQE1a-c:-M7sadMk9Oc8goQE1a-d:b906ss2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/backup_test.go#L299)):*
> ```
> 		if fileType != backupccl.ZipType {
> 			t.Errorf("expect manifest files to be compressed but the format is" + fileType)
> 		}
> ```
require.Equal(t, backup.ZipType, fileType)
___
*[pkg/ccl/backupccl/backup_test.go, line 1129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7se7YY0wcWQTCClwl3:-M7se7YY0wcWQTCClwl4:b-rnxd9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/backup_test.go#L1129)):*
> ```Go
> 		if err != nil {
> 			t.Fatal(err)
> 		}
> ```

require.NoError(t, err)
___
*[pkg/ccl/backupccl/backup_test.go, line 2592 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7se9v540UPKnf8ZXGz:-M7se9v540UPKnf8ZXH-:b-rnxd9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/backup_test.go#L2592)):*
> ```Go
> 		if err != nil {
> 			t.Fatalf("%+v", err)
> 		}
> ```

require.NoError(t, err)
___
*[pkg/ccl/backupccl/manifest_handling.go, line 132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7seGS4-TETID_6jm6M:-M7sb8UDAs2RLPboU-RG:b-7og924) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/manifest_handling.go#L132)):*
> ```Go
> // DecompressAndCheckFile checks if a file is in gzip format, and decompresses
> // it if this is the case.
> func DecompressAndCheckFile(descBytes []byte) ([]byte, error) {
> ```

isn't the name a bit backward? We check first, then decompress?

Perhaps a better name might be DecompressFileIfNeeded(...)?
Or MaybeDecompressFile?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 173 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7sbRvwAjvdoghDZ1Xl:-M7sbRvwAjvdoghDZ1Xm:bgu6d1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/manifest_handling.go#L173)):*
> ```Go
> 	}
> 	// This decompresses any backup manifest in gzip format.
> 	descBytes, err = DecompressAndCheckFile(descBytes)
> ```


I think the code might be cleaner if you moved the content type check right here:

if http.DetectContent(descBytes) == ZipFile {
  descBytes, err = DecompressData(...)
  if err != nil {
    ...
  }
}

This kind of change would a) make function (and name of the function) clearer -- it will only do one thing (decompression) 
b ) it makes this code cleaner as well and more in line with how we handle encryption above
(we don't have CheckAndDecryptFile for example).

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @pbardea)

___
*[pkg/storage/enginepb/mvcc3.pb.go, line 4212 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7secHO1D4L__38wwUl:-M7secHP9AyUCu5Rs5KL:bsx5pte) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/storage/enginepb/mvcc3.pb.go#L4212)):*
> ```Go
> func init() {
> 	proto.RegisterFile("storage/enginepb/mvcc3.proto", fileDescriptor_mvcc3_9bc532bf92053320)
> }
> ```

do you know why these files are part of this PR?
But not the actual proto files?

**Review by pbardea — COMMENTED** [review]
As mentioned, we usually squash all those changes into 1 commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-:-M7tICoX34WhTEqFJwZC:b-6yu1x3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7seGS4-TETID_6jm6M:-M7t1GLx7RNKh0p3evh2:b-qgkmd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/manifest_handling.go#L132)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

isn't the name a bit backward? We check first, then decompress?

Perhaps a better name might be DecompressFileIfNeeded(...)?
Or MaybeDecompressFile?

</blockquote></details>

+1 on making this a decompress method and moving the check to the callsite.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 284 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7tGr-u7mUcgFN8KYWe:-M7tGr-u7mUcgFN8KYWf:b-f6tb1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e520156b54b5f77c869a899192ce55d839353e6/pkg/ccl/backupccl/manifest_handling.go#L284)):*
> ```Go
> 		return err
> 	}
> 	// This applies gzip compression to BackupPartitionDescriptor.
> ```

I don't think that this comment is needed now that we've factored it out into a helper method. (Same in the other place that this comment appears.)
___
*[pkg/storage/enginepb/mvcc3.pb.go, line 4212 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7secHO1D4L__38wwUl:-M7t1aSe4t2MKIvRnBRJ:b-t7qh6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/storage/enginepb/mvcc3.pb.go#L4212)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do you know why these files are part of this PR?
But not the actual proto files?
</blockquote></details>

We tracked these down and I think they were added due to some auto formatter being run.

**Review by pbardea — COMMENTED** [review]
This is looking pretty good to me - nearly there! I just had a couple more small comments and it looks like CI is failing on a small linter error. Also be sure to squash these commits into 1 after addressing the changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-:-M8GBC4B2Y-aAMbn8uJv:b-4h5oll)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 116 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8G8A-U4tfrxkzY6T2N:-M8G8A-U4tfrxkzY6T2O:b-3oc1p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/89943b3fe39960f5b62608692b1812efd29e5ec8/pkg/ccl/backupccl/manifest_handling.go#L116)):*
> ```Go
> // into gzip format.
> func compressFile(descBuf []byte) ([]byte, error) {
> 	// Decompresses the file when BackupManifest is compressed by GZip.
> ```

I'm a bit confused by this comment - isn't this method compressing the file?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 127 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8G8Ink8RO9WJZeZoQ3:-M8G8Ink8RO9WJZeZoQ4:b-wl2ixg) ([raw file](https://github.com/cockroachdb/cockroach/blob/89943b3fe39960f5b62608692b1812efd29e5ec8/pkg/ccl/backupccl/manifest_handling.go#L127)):*
> ```Go
> 	}
> 	compressedDescBuf := gzipBuf.Bytes()
> 	return compressedDescBuf, nil
> ```

we can just do `return gzipBuf.Bytes(), nil`

**Review by Anzoteh96 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7mpWuw4LGmLRnsZade:-M8GDoMh082DGlehP0uR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c4e7dc006726aa9c3e30a3a0bdef15831348a41/pkg/ccl/backupccl/backup_test.go#L420)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 					if fileType != backupccl.ZipType {
> 						t.Errorf("expect partition descriptor files to be compressed but the format is" + fileType)
> ```
require.Equal(t, fileTYpe, backupccl.ZipType)
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup_test.go, line 1129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7se7YY0wcWQTCClwl3:-M8GDxRQ7-n-BqeLLrBD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/backup_test.go#L1129)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

require.NoError(t, err)
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup_test.go, line 2592 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7se9v540UPKnf8ZXGz:-M8GDz-Y3uZSyfSJcrp8:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/backup_test.go#L2592)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

require.NoError(t, err)
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/manifest_handling.go, line 132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7seGS4-TETID_6jm6M:-M8GE6JVE6z_DD5lP7k7:b6utbum) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/manifest_handling.go#L132)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

+1 on making this a decompress method and moving the check to the callsite.
</blockquote></details>

It's now changed to `DecompressFile`: a check is done by the caller of the function that the file is in gzip format before calling it. (Should we add an assert statement in the `DecompressFile` function to make sure that the input is a gzip file?)
___
*[pkg/ccl/backupccl/manifest_handling.go, line 173 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7sbRvwAjvdoghDZ1Xl:-M8GF3t_8nfchFoNswkX:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/manifest_handling.go#L173)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>


I think the code might be cleaner if you moved the content type check right here:

if http.DetectContent(descBytes) == ZipFile {
  descBytes, err = DecompressData(...)
  if err != nil {
    ...
  }
}

This kind of change would a) make function (and name of the function) clearer -- it will only do one thing (decompression) 
b ) it makes this code cleaner as well and more in line with how we handle encryption above
(we don't have CheckAndDecryptFile for example).
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/manifest_handling.go, line 284 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7tGr-u7mUcgFN8KYWe:-M8GEbOE5jF2v55JeqLj:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e520156b54b5f77c869a899192ce55d839353e6/pkg/ccl/backupccl/manifest_handling.go#L284)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I don't think that this comment is needed now that we've factored it out into a helper method. (Same in the other place that this comment appears.)
</blockquote></details>

Done

**Review by Anzoteh96 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M7sadMk9Oc8goQE1a-c:-M8GR3Zm4bSwf9_zeFZw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5544f8a7d4c711428b3fa8297e19e6498e5b288b/pkg/ccl/backupccl/backup_test.go#L299)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 		if fileType != backupccl.ZipType {
> 			t.Errorf("expect manifest files to be compressed but the format is" + fileType)
> 		}
> ```
require.Equal(t, backup.ZipType, fileType)
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/manifest_handling.go, line 116 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8G8A-U4tfrxkzY6T2N:-M8GRGlq3CQyJckUVANu:b-vyqju) ([raw file](https://github.com/cockroachdb/cockroach/blob/89943b3fe39960f5b62608692b1812efd29e5ec8/pkg/ccl/backupccl/manifest_handling.go#L116)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I'm a bit confused by this comment - isn't this method compressing the file?
</blockquote></details>

Comments removed (careless mistake oops 🙊)
___
*[pkg/ccl/backupccl/manifest_handling.go, line 127 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8G8Ink8RO9WJZeZoQ3:-M8GRFlH1VBo64_Bt_4y:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/89943b3fe39960f5b62608692b1812efd29e5ec8/pkg/ccl/backupccl/manifest_handling.go#L127)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

we can just do `return gzipBuf.Bytes(), nil`
</blockquote></details>

Done

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 114 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8HX3Tz0nl1VEoM5Tsh:-M8HX3Tz0nl1VEoM5Tsi:brhyjeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/31690a21f82b04f509e5b3c85844bfb56315e950/pkg/ccl/backupccl/manifest_handling.go#L114)):*
> ```Go
> 
> // compressFile compresses a file (could be in form of file streams)
> // into gzip format.
> ```

should this method be called compressData?
Also, comment is a bit confusing:
compressData compresses provided buf and returns compressed bytes.

(Something like that)
___
*[pkg/ccl/backupccl/manifest_handling.go, line 129 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8HXI9f7Ny-01NVpVTY:-M8HXI9f7Ny-01NVpVTZ:bfv140i) ([raw file](https://github.com/cockroachdb/cockroach/blob/31690a21f82b04f509e5b3c85844bfb56315e950/pkg/ccl/backupccl/manifest_handling.go#L129)):*
> ```Go
> // DecompressFile assumes that a file is in GZip format,
> // and decompresses it.
> func DecompressFile(descBytes []byte) ([]byte, error) {
> ```

should this be called DecompressData?

**Review by Anzoteh96 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 114 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8HX3Tz0nl1VEoM5Tsh:-M8Hqzbi3FtY4-BOPHAe:b-8mnlw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/31690a21f82b04f509e5b3c85844bfb56315e950/pkg/ccl/backupccl/manifest_handling.go#L114)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should this method be called compressData?
Also, comment is a bit confusing:
compressData compresses provided buf and returns compressed bytes.

(Something like that)
</blockquote></details>

Good point, just changed them. 
___
*[pkg/ccl/backupccl/manifest_handling.go, line 129 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/49326#-M8HXI9f7Ny-01NVpVTY:-M8Hr3PsDjsegClHB7Q3:b-d6ibbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/31690a21f82b04f509e5b3c85844bfb56315e950/pkg/ccl/backupccl/manifest_handling.go#L129)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should this be called DecompressData?
</blockquote></details>

Just changed them

**Comment by pbardea** [comment]
One comment on the updated commit message, we should probably replace "files" with "data" in "the amount of files needed to be downloaded".

**Comment by Anzoteh96** [comment]
> One comment on the updated commit message, we should probably replace "files" with "data" in "the amount of files needed to be downloaded".

Done, thanks for pointing out!

**Comment by Anzoteh96** [comment]
TFTR! 
bors r+

**Pull request merged**
