### PR TITLE
sql: use distsql for local distinct

### PR DESCRIPTION
**Pull request by rjnn**
Use the distsql distinct processor for processing local sql queries. This is a work-in-progress to demonstrate and begin a discussion around the shims used.

This PR is rebased on top of #25860, so only evaluate the last commit. The main interfaces on which I'd like discussion are RowSourceToPlanNode and PlanNodeToRowSource. The rest of this PR is exporting changes (2nd commit), some planning plumbing, and code removal in local distinct.

### CODE REVIEW

**Comment by petermattis** [comment]
I've only had time to skim this so far. Replacing localsql distinct with distsql distinct wasn’t as involved as I expected. It’s worthwhile to see if there is any performance diff from the change (i.e. due to the glue code).

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LDI1ybhDB3j-gLDBwTX:b-wnflvu)*

**Comment by arjunravinarayan** [comment]
Yup, this was fairly quick work, until I got to tuples!

There will be performance penalty due to the useless `EncDatum` wrapper which will churn through additional allocations, but I'll run some actual benchmarks to give you actual numbers.

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LDI2G_h796vJDtRic_f:bp5wkb6)*

**Comment by RaduBerinde** [comment]
I like the approach, looks pretty straightforward.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 2196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgLZzQ7zVdLYssInrd:-LDgLZzQ7zVdLYssInre:btj83o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/distsql_physical_planner.go#L2196)):*
> ```Go
> }
> 
> func CreateDistinctSpec(n *distinctNode, cols []int) *distsqlrun.DistinctSpec {
> ```

unexport

---

*[pkg/sql/plan_node_to_row_source.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgLjBL53bOzlTVWRTC:-LDgLjBL53bOzlTVWRTD:bhla29q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L11)):*
> ```Go
> )
> 
> type planNodeToRowSource struct {
> ```

What is this to be used for?

---

*[pkg/sql/row_source_to_plan_node.go, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgJnGzAJaqLCzOMO-k:-LDgJnGzAJaqLCzOMO-l:bufucq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L18)):*
> ```Go
> // be constructed with Create(), after which it is a PlanNode and can be treated
> // as such.
> type RowSourceToPlanNode struct {
> ```

Does this need to be exported?

---

*[pkg/sql/row_source_to_plan_node.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgKzJa5vqDUsJNT5lI:-LDgKzJa5vqDUsJNT5lJ:b-6nx6aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L50)):*
> ```Go
> 	}
> 
> 	if len(r.row) == 0 {
> ```

The check should be for `r.row == nil`. Processors can in principle output empty rows.

---

*[pkg/sql/row_source_to_plan_node.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgKrnjDp0ZIE7jfK2Z:-LDgKrnjDp0ZIE7jfK2_:b8p80ds) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L51)):*
> ```Go
> 
> 	if len(r.row) == 0 {
> 		r.source.ConsumerClosed()
> ```

I think ConsumerClosed is to be called only once (at least according to its comment), it will get called again in Close

---

*[pkg/sql/row_source_to_plan_node.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgL9lE8m8RJO0igEHp:-LDgL9lE8m8RJO0igEHq:b-uu2jn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L59)):*
> ```Go
> 
> func (r *RowSourceToPlanNode) Values() tree.Datums {
> 	datums := make(tree.Datums, len(r.row))
> ```

This can be pre-allocated once (most planNodes do this)

---

*[pkg/util/fast_int_set.go, line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgJ-rE7b34W9dsh4AQ:-LDgJ-rE7b34W9dsh4AR:b-zan5f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/util/fast_int_set.go#L196)):*
> ```Go
> 	}
> 	if s.large != nil {
> 		panic("dont do this")
> ```

This panic is not acceptable. We sometimes run tests with the "small set" cutoff set to a very small value to check there are no problems when falling back to large. The code below should work fine in the large mode.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LDgLKsj0vDvB8kl-WrE:bicezc9)*

**Comment by asubiotto** [comment]
Nice work. Have you got a rough plan for the long term merge of the two execution engines? I'm still kind of cloudy on the details but wondering if this work has made the path clearer for you.

---

Review status: 0 of 19 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distinct.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlVw-HCSsYnUszDvAd:-LDlVw-HCSsYnUszDvAe:bq1bgzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/distinct.go#L217)):*
> ```Go
> 
> 	post := &distsqlrun.PostProcessSpec{} // TODO? I think an empty PostProcessSpec is fine.
> 	var output distsqlrun.RowReceiver     // TODO
> ```

Comment explaining that `output` will not be used because distinct will be run as a `RowSource`

---

*[pkg/sql/plan_node_to_row_source.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlTt92BVti6jqag9b9:-LDlTt92BVti6jqag9bA:b1hazv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L58)):*
> ```Go
> 	}
> 	if !valid {
> 		p.valid = false
> ```

Where is `p.valid` used?

---

*[pkg/sql/plan_node_to_row_source.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIhUkH4Tfp6nBjYnP8:-LDIhUkI-bRrnnyDcboY:b8dzd2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L66)):*
> ```Go
> }
> 
> func (p *planNodeToRowSource) ConsumerDone() {}
> ```

I think this currently violates the `RowSource` contract because you would still be returning rows after `ConsumerDone` is called. A call to this should also result in a `planNode.Close` at some point. This usually happens after sending any trailing metadata, but in this case it should be immediate.

---

*[pkg/sql/plan_node_to_row_source.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIftOnBHPiAaMf_sxL:-LDIftOnBHPiAaMf_sxM:brs6k5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L72)):*
> ```Go
> }
> 
> func (p *planNodeToRowSource) DatumsToEncDatumRow(values tree.Datums) sqlbase.EncDatumRow {
> ```

This might be a nice utility function to have in `sqlbase` (I think similar logic is used in the `memRowContainer`)

---

*[pkg/sql/row_source_to_plan_node.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIm2qBERb0Z577vaxP:-LDIm2qBERb0Z577vaxQ:bg7dvej) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L27)):*
> ```Go
> }
> 
> func CreateRowSourceToPlanNode(s distsqlrun.RowSource) RowSourceToPlanNode {
> ```

`s/CreateRowSourceToPlanNode/MakeRowSourceToPlanNode` and ditto in `PlanNodeToRowSource`

---

*[pkg/sql/row_source_to_plan_node.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlS_JgCcBeVoforsA5:-LDlS_Jh39BY7XQHDrCG:b-sczhx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L35)):*
> ```Go
> func (r *RowSourceToPlanNode) Next(params runParams) (bool, error) {
> 	if r.source == nil {
> 		return false, errors.Errorf("no valid rowsource initialized")
> ```

I think it's fine to assume that `r.source != nil` in `Next`, I believe we do this for processors too

---

*[pkg/sql/distsqlrun/base.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlTYndDqgNKV8q58H6:-LDlTYndDqgNKV8q58H7:b61iomb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/distsqlrun/base.go#L155)):*
> ```Go
> type RowSourcedProcessor interface {
> 	RowSource
> 	Run(_ context.Context, wg *sync.WaitGroup)
> ```

Any reason not to embed the Processor interface as well?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LDl_OyK8jIO_K17aVc2:b2eufqq)*

**Comment by arjunravinarayan** [comment]
@asubiotto I updated #23901 with an extended plan.

---

Review status: 0 of 26 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distinct.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlVw-HCSsYnUszDvAd:-LEBDqa21owEWxtuN76l:b-l15b2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/distinct.go#L217)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Comment explaining that `output` will not be used because distinct will be run as a `RowSource`
</blockquote></details>

Great point, thank you. Done.

---

*[pkg/sql/distsql_physical_planner.go, line 2196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgLZzQ7zVdLYssInrd:-LEB5rSi77LZCpw8Le4e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/distsql_physical_planner.go#L2196)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

unexport
</blockquote></details>

Done.

---

*[pkg/sql/plan_node_to_row_source.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgLjBL53bOzlTVWRTC:-LEBHE4u4-FNALN2pKgY:bq03lhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What is this to be used for?
</blockquote></details>

Eventually when we have multiple planNodes that are rowSourced, we'd want to fuse their execution pipeline and then unfuse them at the end. Right now we don't, so this is not used code. I can leave it out of this PR if you prefer.

---

*[pkg/sql/plan_node_to_row_source.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlTt92BVti6jqag9b9:-LEBLB-R-R2LYFMc6n3p:b-2cdl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Where is `p.valid` used?
</blockquote></details>

Huh, I was never using it. You're right, since the underlying RowSources track it internally, there's no need for us to redo that work. Removed.

---

*[pkg/sql/plan_node_to_row_source.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIhUkH4Tfp6nBjYnP8:-LEBMx20DYK4KRldm-Ea:b-ok9wvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L66)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this currently violates the `RowSource` contract because you would still be returning rows after `ConsumerDone` is called. A call to this should also result in a `planNode.Close` at some point. This usually happens after sending any trailing metadata, but in this case it should be immediate.
</blockquote></details>

Added a comment that the caller should close after calling this. 

---

*[pkg/sql/plan_node_to_row_source.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIftOnBHPiAaMf_sxL:-LEBETM9Dujn-mLoP3bm:b9zipqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This might be a nice utility function to have in `sqlbase` (I think similar logic is used in the `memRowContainer`)
</blockquote></details>

Done. Moved to `sqlbase/encoded_datum.go`. Feel free to use it!

---

*[pkg/sql/row_source_to_plan_node.go, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgJnGzAJaqLCzOMO-k:-LEBG4Gg146vjORPV5W8:beund6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L18)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Does this need to be exported?
</blockquote></details>

No. Unexported.

---

*[pkg/sql/row_source_to_plan_node.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIm2qBERb0Z577vaxP:-LEBGHLo50ZK9qvSWz9M:bc24lf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L27)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/CreateRowSourceToPlanNode/MakeRowSourceToPlanNode` and ditto in `PlanNodeToRowSource`
</blockquote></details>

Done, and also unexported.

---

*[pkg/sql/row_source_to_plan_node.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlS_JgCcBeVoforsA5:-LEBGaAGCbRaaN18uC4E:byxthsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L35)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it's fine to assume that `r.source != nil` in `Next`, I believe we do this for processors too
</blockquote></details>

Done. Removed. Thanks.

---

*[pkg/sql/row_source_to_plan_node.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgKzJa5vqDUsJNT5lI:-LEBGerb1b5Ru8QS7HaK:b-6k1ref) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L50)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The check should be for `r.row == nil`. Processors can in principle output empty rows.
</blockquote></details>

Good point. Thank you.

---

*[pkg/sql/row_source_to_plan_node.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgKrnjDp0ZIE7jfK2Z:-LEBGjaD4ZG33VshhP1L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think ConsumerClosed is to be called only once (at least according to its comment), it will get called again in Close
</blockquote></details>

Done.

---

*[pkg/sql/row_source_to_plan_node.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgL9lE8m8RJO0igEHp:-LEBgP9q436TGm0lisER:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/row_source_to_plan_node.go#L59)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This can be pre-allocated once (most planNodes do this)
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/base.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlTYndDqgNKV8q58H6:-LEBGnAb3GFNryUFb3WJ:byg9p45) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/distsqlrun/base.go#L155)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Any reason not to embed the Processor interface as well?
</blockquote></details>

You can't embed both `RowSource` and `Processor`, as you get an "error: duplicate method OutputTypes". The intention here is to have a union interface that satisfies both interfaces, but this is the only way I could get it to not complain. Is there a better way to achieve this?

---

*[pkg/util/fast_int_set.go, line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgJ-rE7b34W9dsh4AQ:-LEBAu3mDce2LTRicMVv:b3rkr32) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/util/fast_int_set.go#L196)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This panic is not acceptable. We sometimes run tests with the "small set" cutoff set to a very small value to check there are no problems when falling back to large. The code below should work fine in the large mode.
</blockquote></details>

I ended up removing the whole function, it was just for rapid prototyping, and thus the code quality.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LEB4dii-pln7GAULLC-:b-wfkjsc)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 10 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/plan_node_to_row_source.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgLjBL53bOzlTVWRTC:-LEGqk-sDoP8knpEiY6J:b-sd6lud) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L11)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Eventually when we have multiple planNodes that are rowSourced, we'd want to fuse their execution pipeline and then unfuse them at the end. Right now we don't, so this is not used code. I can leave it out of this PR if you prefer.
</blockquote></details>

Not sure I understand. Why would we need a row-source - to - planNode shim to fuse them? Anyway, I'd leave it out of this PR since it's just a distraction for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873)*

**Comment by jordanlewis** [comment]
:thumbsup: this looks good!

---

Review status: 0 of 8 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/sql/plan_node_to_row_source.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDgLjBL53bOzlTVWRTC:-LEen2qvAt_HL99mCM6H:binqwor) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not sure I understand. Why would we need a row-source - to - planNode shim to fuse them? Anyway, I'd leave it out of this PR since it's just a distraction for now.
</blockquote></details>

We do need both directions of conversion, at least at first. If there are 3 planNodes in a row, A->B->C, and B is implemented as a wrapper around a Processor, you need a rowSourceToPlanNode wrapper to wrap the processor so that A can consume from B as a planNode, and you need a planNodeToRowSource wrapper to wrap the planNode C so that B's inner processor can consume from C as a RowSource.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LEBjXqB4VlHcaOmHQgM:b-o5eauv)*

**Comment by arjunravinarayan** [comment]
:lgtm: but you know... Mine doesn't count.

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LEjIEh_6sclK6iPhVPm:b-l0wfhe)*

**Comment by asubiotto** [comment]
:lgtm: just some nits. The fact that `ConsumerClosed` and `ConsumerDone` are noops in `planNodeToRowSource` confuses me a bit so it might be worth writing a more extensive comment but otherwise looks good.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/distinct.go, line 211 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LEjJX3k5Mmq8EYrrQs2:-LEjJX3k5Mmq8EYrrQs3:bd1648t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6db89152d3e4005173cf866ad377a0f9597cc15b/pkg/sql/distinct.go#L211)):*
> ```Go
> 
> 	post := &distsqlrun.PostProcessSpec{} // post is not used as we only use the processor for the core distinct logic.
> 	var output distsqlrun.RowReceiver     // output is never used as distinct is only run as a RowSource.
> ```

nit: I personally find it easier to read comments when they are on the line above, but feel free to ignore

---

*[pkg/sql/plan_node_to_row_source.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIhUkH4Tfp6nBjYnP8:-LEjJnwu53zcHhIxz6-e:b-zdh14a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L66)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Added a comment that the caller should close after calling this. 
</blockquote></details>

I'm kind of confused. I think we need to implement `RowSource` contracts in this wrapper, this includes making `ConsumerClosed` actually close the `planNode` and have `ConsumerDone` behave how we expect it to, because the caller (in this case a distsql processor) doesn't know about the underlying `RowSource` implementation and expects

---

*[pkg/sql/row_source_to_plan_node.go, line 81 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LEjNeyb3jmaACyD9Q9X:-LEjNeyb3jmaACyD9Q9Y:buq4632) ([raw file](https://github.com/cockroachdb/cockroach/blob/6db89152d3e4005173cf866ad377a0f9597cc15b/pkg/sql/row_source_to_plan_node.go#L81)):*
> ```Go
> 
> func (r *rowSourceToPlanNode) Close(ctx context.Context) {
> 	if r.source != nil {
> ```

nit: We can assume `r.source` is `!= nil` here as well

---

*[pkg/sql/row_source_to_plan_node.go, line 86 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LEjNoOU0RXyAI0zq-uW:-LEjNoOU0RXyAI0zq-uX:b-o4b2gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6db89152d3e4005173cf866ad377a0f9597cc15b/pkg/sql/row_source_to_plan_node.go#L86)):*
> ```Go
> }
> 
> var _ planNode = &rowSourceToPlanNode{}
> ```

nit: I would put this right below the struct definition

---

*[pkg/sql/distsqlrun/base.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDlTYndDqgNKV8q58H6:-LEjNyIiCcO-38ucSj6L:b-n1ufhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/distsqlrun/base.go#L155)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

You can't embed both `RowSource` and `Processor`, as you get an "error: duplicate method OutputTypes". The intention here is to have a union interface that satisfies both interfaces, but this is the only way I could get it to not complain. Is there a better way to achieve this?
</blockquote></details>

This is fine

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LEjPWBLAXhV9r3aXpo-:b-h7r174)*

**Comment by asubiotto** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/plan_node_to_row_source.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-LDIhUkH4Tfp6nBjYnP8:-LEjQWzh6LfddU1VYGYS:btg6obu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a366faf3f1eee2f2c5e0a6192fe6f24b71ac1f79/pkg/sql/plan_node_to_row_source.go#L66)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm kind of confused. I think we need to implement `RowSource` contracts in this wrapper, this includes making `ConsumerClosed` actually close the `planNode` and have `ConsumerDone` behave how we expect it to, because the caller (in this case a distsql processor) doesn't know about the underlying `RowSource` implementation and expects
</blockquote></details>

^ disregard this unfinished comment, I thought I had deleted it. I'm still confused but it seems that implementing this logic even with removing the `planNode.Close` call in `distinct` results in some `Close` issues. A comment more extensively explaining this interaction would satisfy me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873)*

**Comment by jordanlewis** [comment]
I fixed the flow so that they're no longer no-ops. It makes more sense now. PTAL.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LEkBIZN4fRITuSS4WTQ:bk9rhwy)*

**Comment by asubiotto** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25873#-:-LEkLqw2-KnT3-nwprtL:bnfp4nl)*

**Pull request merged**
