### PR TITLE
obsservice: migrate gRPC ingest to follow new architecture 

### PR DESCRIPTION
**Pull request by abarganier**
**Reviewer note: review this PR commit-wise.**

----

In the original design of the obsservice, exported events were
intended to be written directly to storage. The idea was that
exported events would experience minimal transformation once
ingested, meaning that work done to "package" events properly
was left up to the exporting client (CRDB). The obsservice
would then store the ingested invents into a target storage.
This concept of target storage has been removed for now as
part of this patch.

In the new architecture, exported events are more "raw", and
we expect the obsservice to heavily transform & aggregate the
data externally, where the aggregated results are flushed
to storage instead.

This patch takes the pre-existing gRPC events ingester, and
modifies it to meet the new architecture.

The events ingester will now be provided with a consumer with
which it can feed ingested events into the broader pipeline.
It is no longer the responsibility of the ingester to write
ingested events to storage.

For now, we use a simple STDOUT consumer that writes all
ingested events to STDOUT, but in the future, this will
be a more legitimate component - part of a chain that
eventually buffers ingested events for aggregation.

Release note: none

Epic: CRDB-28526

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 17 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/obsservice/README.md` line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYZj9V_-BJ30VhRO8rf:-NYZj9V_-BJ30VhRO8rg:b-axvyjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b1319d6b01aace4f70956720301ed52fe11c00/pkg/obsservice/README.md#L53)):*
> ```Markdown
>       insecure: true
> ```
> - `--http-addr` is the address on which the DB Console is served. NB: This feature 
> ```

*may be removed*
___
*[`pkg/obsservice/obslib/ingest/grpc_ingest_test.go` line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYZjd3U8ulckUp5aJ73:-NYZjd3V-5JJ5s4kDga4:b-4370je) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b1319d6b01aace4f70956720301ed52fe11c00/pkg/obsservice/obslib/ingest/grpc_ingest_test.go#L89)):*
> ```Go
> 							// Flush every message.
> 							FlushTriggerByteSize: 1,
> 							TestConsumer:         testConsumer,
> ```

I thought you wanted to simplify this to call the aPI handler directly instead of a test knob?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/obsservice/README.md` line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYZj9V_-BJ30VhRO8rf:-NYZsUm16Y5ednZ2ecJx:b-8rfntc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b1319d6b01aace4f70956720301ed52fe11c00/pkg/obsservice/README.md#L53)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

*may be removed*
</blockquote></details>

Ack - I wasn't sure if there was still some utility in keeping this around... I'll give the removal its own PR to keep it separate. 
___
*[`pkg/obsservice/obslib/ingest/grpc_ingest_test.go` line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYZjd3U8ulckUp5aJ73:-NYZrwwo0CtnRBSVmNQf:brmp0pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b1319d6b01aace4f70956720301ed52fe11c00/pkg/obsservice/obslib/ingest/grpc_ingest_test.go#L89)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I thought you wanted to simplify this to call the aPI handler directly instead of a test knob?
</blockquote></details>

Yes, I forgot to add that! To clarify, I think we should keep this integration test *and* add a separate test that calls into the API handler directly. I ended up forgetting to add that 2nd test.

I'll do so now! Thanks for the reminder :sweat_smile:

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback, RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-:-NYtRzpw9CS49i3p8Zb6:bfnuh3l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/obsservice/README.md` line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYZj9V_-BJ30VhRO8rf:-NYtRipt-3K53BUUR__Q:b-8jp0no) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b1319d6b01aace4f70956720301ed52fe11c00/pkg/obsservice/README.md#L53)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Ack - I wasn't sure if there was still some utility in keeping this around... I'll give the removal its own PR to keep it separate. 
</blockquote></details>

Sorry, I misunderstood your comment originally.

Fixed the wording. 
___
*[`pkg/obsservice/obslib/ingest/grpc_ingest_test.go` line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYZjd3U8ulckUp5aJ73:-NYtRmYw46THhfx0xawQ:b1nocvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b1319d6b01aace4f70956720301ed52fe11c00/pkg/obsservice/obslib/ingest/grpc_ingest_test.go#L89)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Yes, I forgot to add that! To clarify, I think we should keep this integration test *and* add a separate test that calls into the API handler directly. I ended up forgetting to add that 2nd test.

I'll do so now! Thanks for the reminder :sweat_smile: 
</blockquote></details>

Added a separate datadriven test just for the GRPC ingester, and changed the filename of the integration test accordingly.

**Review by knz — APPROVED** [review]
> Reviewed 3 of 5 files at r6, 2 of 3 files at r7, 21 of 21 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/obsservice/cmd/obsservice/main.go` line 49 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYxMa4T5lFrP6VNnMeR:-NYxMa4T5lFrP6VNnMeS:b9hsqqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0f2db90ecf736650fa06ea64dfd0105060bf460/pkg/obsservice/cmd/obsservice/main.go#L49)):*
> ```Go
> var termSignal os.Signal = unix.SIGTERM
> 
> // TODO(abarganier): migrate DB migrations over to target storage for aggregated outputs
> ```

I'm not keen on commenting out a Go declaration in a PR.
Either keep the thing (and silence the unused linter) or remove it (we can fetch it back from git history).

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/obsservice/cmd/obsservice/main.go` line 49 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/105316#-NYxMa4T5lFrP6VNnMeR:-NYxcWCX9TqzLTaJQQFv:b-y2zdw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0f2db90ecf736650fa06ea64dfd0105060bf460/pkg/obsservice/cmd/obsservice/main.go#L49)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'm not keen on commenting out a Go declaration in a PR.
Either keep the thing (and silence the unused linter) or remove it (we can fetch it back from git history).
</blockquote></details>

Sounds good, I'll clean this up before merging :+1:

**Comment by abarganier** [comment]
TFYR!

bors r=knz

**Pull request merged**
