### PR TITLE
release-21.1: sql: add max_row_size guardrails

### PR DESCRIPTION
**Pull request by michae2**
Backport 2/3 commits from #67953.
Backport 3/3 commits from #69457.

/cc @cockroachdb/release

---

**sql: add sql.mutations.max_row_size.log guardrail (large row logging)**

Addresses: #67400

Add sql.mutations.max_row_size.log, a new cluster setting which
controls large row logging. Rows larger than this size will have their
primary keys logged to the SQL_PERF or SQL_INTERNAL_PERF channels
whenever the SQL layer puts them into the KV layer.

This logging takes place in rowHelper, which is used by both
row.Inserter and row.Updater. Most of the work is plumbing
settings.Values and SessionData into rowHelper, and adding a new
structured event type.

Release note (ops change): A new cluster setting,
sql.mutations.max_row_size.log, was added, which controls large row
logging. Whenever a row larger than this size is written (or a single
column family if multiple column families are in use) a LargeRow event
is logged to the SQL_PERF channel (or a LargeRowInternal event is logged
to SQL_INTERNAL_PERF if the row was added by an internal query). This
could occur for INSERT, UPSERT, UPDATE, CREATE TABLE AS, CREATE INDEX,
ALTER TABLE, ALTER INDEX, IMPORT, or RESTORE statements. SELECT, DELETE,
TRUNCATE, and DROP are not affected by this setting.

Release justification: Low risk, high benefit change to existing
functionality. This adds logging whenever a large row is written to the
database. Default is 0 in 21.1 (meaning disabled).

**sql: add sql.mutations.max_row_size.err guardrail (large row errors)**

Addresses: #67400

Add sql.mutations.max_row_size.err, a new cluster setting similar to
sql.mutations.max_row_size.log, which limits the size of rows written to
the database. Statements trying to write a row larger than this will
fail with an error. (Internal queries will not fail with an error, but
will log a LargeRowInternal event to the SQL_INTERNAL_PERF channel.)

We're reusing eventpb.CommonLargeRowDetails as the error type, out of
convenience.

Release note (ops change): A new cluster setting,
sql.mutations.max_row_size.err, was added, which limits the size of rows
written to the database (or individual column families, if multiple
column families are in use). Statements trying to write a row larger
than this will fail with a code 54000 (program_limit_exceeded) error.
(Internal queries writing a row larger than this will not fail, but will
log a LargeRowInternal event to the SQL_INTERNAL_PERF channel.) This
limit is enforced for INSERT, UPSERT, and UPDATE statements. CREATE
TABLE AS, CREATE INDEX, ALTER TABLE, ALTER INDEX, IMPORT, and RESTORE
will not fail with an error, but will log LargeRowInternal events to the
SQL_INTERNAL_PERF channel. SELECT, DELETE, TRUNCATE, and DROP are not
affected by this limit. **Note that existing rows violating the limit
*cannot* be updated, unless the update shrinks the size of the row
below the limit, but *can* be selected, deleted, altered, backed-up, and
restored.** For this reason we recommend using the accompanying setting
sql.mutations.max_row_size.log in conjunction with
SELECT pg_column_size() queries to detect and fix any existing large
rows before lowering sql.mutations.max_row_size.err.

Release justification: Low risk, high benefit change to existing
functionality. This causes statements adding large rows to fail with an
error. Default is 0 in 21.1 (meaning disabled).

**sql: rename max_row_size guardrails to match transaction row limits**

Addresses: https://github.com/cockroachdb/cockroach/issues/67400

Rename sql.mutations.max_row_size.{log|err} to
sql.guardrails.max_row_size_{log|err} for consistency with
transaction_rows_{read|written}_{log|err} and upcoming metrics.

Release justification: Low-risk update to new functionality.

Release note (ops change): New variables
sql.mutations.max_row_size.{log|err} were renamed to
sql.guardrails.max_row_size_{log|err} for consistency with other
variables and metrics.

**sql/row: remove dependency on sql/execinfra**

The next commit needs to make sql/row a dependency of sql/execinfra, so
remove two small references to sql/execinfra.

(I will squash this into the next commit before merging.)

Release justification: Low-risk update to new functionality.

Release note: None

**sql, import: plumb row.Metrics from ExecutorConfig to row.Helper**

Addresses: https://github.com/cockroachdb/cockroach/issues/67400

Add metrics for sql/row and pass them down from ExecutorConfig and
FlowCtx all the way to row.Helper. Like sql.Metrics, there are two
copies, one for user queries and one for internal queries. (I wanted to
make these part of sql.Metrics, but there are several users of sql/row
that do not operate under a sql.Server or connExecutor so we are forced
to add row.Metrics to the ExecutorConfig and FlowCtx instead.)

I ran into difficulty passing these through import, as FlowCtx itself
is not plumbed through.

There are only two metrics at first, corresponding to
violations of sql.guardrails.max_row_size_{log|err}.

Release justification: Low-risk update to new functionality.

Release note (ops): Added four new metrics,
sql.guardrails.max_row_size_{log|err}.count{.internal} which are
incremented whenever a large row violates the corresponding
sql.guardrails.max_row_size_{log|err} limit.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I think we should include #69457 into this backport right away too.

> Reviewed 31 of 31 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-:-Mj9wYut0CMe5CUg9kpb:b-hfvk8r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @michae2, and @rytaft)

___
*[pkg/sql/row/inserter.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-Mj9xCRRAhOPq8nTjtP7:-Mj9xCRRAhOPq8nTjtP8:b-xs2nhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/910f3ffd9b9de388595150c40b62c0c1399fa3ee/pkg/sql/row/inserter.go#L64)):*
> ```Go
> 	ri := Inserter{
> 		Helper: newRowHelper(codec, tableDesc, writableIndexDescs, sv, internal),
> ```

nit: seems like an extra new line.
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-Mj9xio79v2BY3vT84qP:-Mj9xio79v2BY3vT84qQ:b-1pfgdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe407c132d0e134dd592ec75bffe7170c39ebdeb/pkg/util/log/eventpb/sql_audit_events.proto#L111)):*
> ```protobuf
>   uint32 family_id = 3 [(gogoproto.customname) = "FamilyID", (gogoproto.jsontag) = ",omitempty"];
>   string primary_key = 4 [(gogoproto.jsontag) = ",omitempty"];
>   bool violates_max_row_size_err = 5 [(gogoproto.jsontag) = ",omitempty"];
> ```

Based on Raphael's comments, we might wanna not introduce this field.

**Comment by rytaft** [comment]
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-Mj9xio79v2BY3vT84qP:-MjA5drAEYY9ZMVBcfPG:b-kw21r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe407c132d0e134dd592ec75bffe7170c39ebdeb/pkg/util/log/eventpb/sql_audit_events.proto#L111)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Based on Raphael's comments, we might wanna not introduce this field.
</blockquote></details>

Instead of removing it from the backport, though, why don't we just backport the PR that fixes it along with this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @michae2, and @rytaft)

___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-Mj9xio79v2BY3vT84qP:-MjA6SNIAoS2NMmcuHlt:b-8v3nsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe407c132d0e134dd592ec75bffe7170c39ebdeb/pkg/util/log/eventpb/sql_audit_events.proto#L111)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Instead of removing it from the backport, though, why don't we just backport the PR that fixes it along with this?
</blockquote></details>

I agree. We currently don't have the PR that fixes it on master yet.

**Review by michae2 — COMMENTED** [review]
- Changed defaults to 0 for both variables, making them disabled in 21.1.
- Removed small KV changes.
- Included 3/3 commits from #69457 as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-:-MjC4t4L6Jxpmar7Jw-f:bmrw02q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @rytaft, and @yuzefovich)

___
*[pkg/sql/row/inserter.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-Mj9xCRRAhOPq8nTjtP7:-MjC4vav0Grq08fOjHc_:b-qr4ibd) ([raw file](https://github.com/cockroachdb/cockroach/blob/910f3ffd9b9de388595150c40b62c0c1399fa3ee/pkg/sql/row/inserter.go#L64)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: seems like an extra new line.
</blockquote></details>

It was in the original PR, too. (Allowed me to avoid wrapping :smiling_imp:)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 23 of 34 files at r8, 6 of 11 files at r9, 4 of 5 files at r10, 1 of 2 files at r11, 23 of 23 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-:-MjUrc2t93P2ZFgM8Nu_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @michae2, @rytaft, and @yuzefovich)

___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-Mj9xio79v2BY3vT84qP:-MjUqfGH3VW0dg2SUaWK:bp5c458) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe407c132d0e134dd592ec75bffe7170c39ebdeb/pkg/util/log/eventpb/sql_audit_events.proto#L111)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I agree. We currently don't have the PR that fixes it on master yet.
</blockquote></details>

The PR to remove this has just been borsed, so we'll just backport it.
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 115 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-MjUquI25Ohh4GEILfo-:-MjUquI25Ohh4GEILfo0:b-z023hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/eba5eff7151a7a6607e2f433987fea539be60f8d/pkg/util/log/eventpb/sql_audit_events.proto#L115)):*
> ```protobuf
> 
> // LargeRow is recorded when a statement tries to write a row larger than
> // cluster setting `sql.mutations.max_row_size.log` to the database. Multiple
> ```

nit: I think the setting has been renamed.
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 147 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-MjUqx7W6ZUYwVoNhD_s:-MjUqx7W6ZUYwVoNhD_t:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/eba5eff7151a7a6607e2f433987fea539be60f8d/pkg/util/log/eventpb/sql_audit_events.proto#L147)):*
> ```protobuf
> 
> // LargeRowInternal is recorded when an internal query tries to write a row
> // larger than cluster settings `sql.mutations.max_row_size.log` or
> ```

ditto

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69946)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @michae2, @rytaft, and @yuzefovich)

___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 115 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69946#-MjUquI25Ohh4GEILfo-:-MjV0_JtBP7acSSq-RTa:bjjliui) ([raw file](https://github.com/cockroachdb/cockroach/blob/eba5eff7151a7a6607e2f433987fea539be60f8d/pkg/util/log/eventpb/sql_audit_events.proto#L115)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think the setting has been renamed.
</blockquote></details>

Good catch! I just fixed this in https://github.com/cockroachdb/cockroach/pull/70102 so it will be backported with that PR.

**Pull request merged**
