### PR TITLE
storage: Minor fallout to #5432

### PR DESCRIPTION
**Pull request by tbg**
cc @bdarnell

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5537)

### CODE REVIEW

**Comment by tamird** [comment]
can you give a bit more detail in that last commit message? :lgtm: otherwise

---

Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_test.go, line 2076 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe03lgFdtCRqtD-gI9:-KDe03lgFdtCRqtD-gIA:-2060158628) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8efe7b306478a8d6573246dd76c971ddad617a/storage/replica_test.go#L2076)):*
s/send 1/send incs[0]/

kinda prefer if `sum` was calculated but whatever

---

*[storage/replica_test.go, line 2110 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe0GewdllpVs_Afz_y:-KDe0GewdllpVs_Afz_z:960733676) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8efe7b306478a8d6573246dd76c971ddad617a/storage/replica_test.go#L2110)):*
a little overboard with the scoping? the `for` is already a scope

---

*[storage/store.go, line 1718 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe-fG9StHnIwNFTuqn:-KDe-fG9StHnIwNFTuqo:-350281663) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c63851d1a94fcc7a1972eb77ec89aa4318882c8/storage/store.go#L1718)):*
nit: you should scope this to the `if` block below. that would have prevented the confusion where it was being updated even when `.ID` was nil

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-:-KDe0UXxHNW5fOShH5gi:1504248988)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_test.go, line 2111 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe3d5fOPcm68wiCcL1:-KDe3d5gWoSakENwwagG:440603268) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8efe7b306478a8d6573246dd76c971ddad617a/storage/replica_test.go#L2111)):*
Set an endpoint on the slice so it sends exactly two even if more cases are added to `incs`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-:-KDe3sXdG2OHpSVOHJd-:676834233)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_test.go, line 2076 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe03lgFdtCRqtD-gI9:-KDe3-ntrcQWFZ_PKXft:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8efe7b306478a8d6573246dd76c971ddad617a/storage/replica_test.go#L2076)):*
Done.

---

*[storage/replica_test.go, line 2110 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe0GewdllpVs_Afz_y:-KDe31ygPH6U5yEDFa47:-1959888883) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8efe7b306478a8d6573246dd76c971ddad617a/storage/replica_test.go#L2110)):*
Yeah. There was something else here once. Removed.

---

*[storage/replica_test.go, line 2111 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe3d5fOPcm68wiCcL1:-KDeA1Qx93nBrnE8RzFN:1663929204) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8efe7b306478a8d6573246dd76c971ddad617a/storage/replica_test.go#L2111)):*
But if it did send more and the sum were updated accordingly, all would be well?

---

*[storage/store.go, line 1718 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-KDe-fG9StHnIwNFTuqn:-KDe9xaSeqtL0P9gTCiO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c63851d1a94fcc7a1972eb77ec89aa4318882c8/storage/store.go#L1718)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4, 1 of 1 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5537#-:-KDeFi1uj8uQ0OWFSCX1:1417088721)*

**Pull request merged**
