### PR TITLE
scripts: add a winworker script to create Windows VMs on GCE

### PR DESCRIPTION
**Pull request by benesch**
It's quite useful to be able to quickly spin up a Windows VM to test our
Windows binaries.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
@tschottdorf can I toss this one your way?

**Comment by tschottdorf** [comment]
As in, can I fix up if necessary and merge this? Yup! Let me try this out.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25314#-:-LCGTJmRDef_xIrkiLJd:b-g8g77q)*

**Comment by benesch** [comment]
Oh, sure, if you’d be so kind! It’s not like this is at all time sensitive
so happy to keep on as the shepard; just realized I hadn’t actually asked
anyone to review.

**Comment by tschottdorf** [comment]
bors r+

I added a comment that removes `ssh` and tells people to use MS remote desktop.

**Pull request merged**
