### PR TITLE
sql: test DROP of UNIQUE column fails

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6458)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6458#-:-KGoTXDbKTREwTie4nFv:1417088721)*

**Comment by bdarnell** [comment]
Is this the behavior we want? In postgres, dropping a column automatically drops any indexes and constraints involving the column (but not foreign keys - for those you need the `RESTRICT` keyword).

**Comment by dt** [comment]
I think I like requiring the index(s) be explicitly dropped first -- I'd be wary of automatically dropping any indexes, at least any that include more than just the dropped column, since that could cause unexpected performance changes.

**Comment by bdarnell** [comment]
Yeah, dropping indexes that contain the dropped column along with others seems sketchy; it makes sense to require those to be explicitly dropped. 

I think it may still be worthwhile to automatically drop indexes that contain *only* the dropped column (or, if we want to get clever, any index that starts with the dropped column). Single-column indexes are often created with syntax that looks like a modifier to the column instead of a separate object, and their names are assigned by the system (and you need to know that name to drop the index).

**Comment by vivekmenezes** [comment]
created an issue
https://github.com/cockroachdb/cockroach/issues/6463

**Pull request merged**
