### PR TITLE
sqlsmith: Add JOIN to TLP testing

### PR DESCRIPTION
**Pull request by nehageorge**
Previously, GenerateTLP only supported basic TLP with a WHERE clause.
This was inadequate because the scope of TLP-based testing is much
larger, allowing for further testing using other filters.
To address this, this commit adds support for "LEFT JOIN"-based TLP.

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
Very nice!!!

Is it possible for TLP to test `INNER JOIN`s as well, or only `LEFT JOIN`s? If it is possible, you can add that in a future PR.

By convention we format commit titles as `pkg: ...` where `pkg` is the package or set of packages updated in the commit. I don't think you'll need a `Release justification` now that the 21.2 branch has been cut, so I think you can remove that from the commit and PR description. There's more details about writing commit messages here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-:-Mj_PfXK94zDNvadJNJx:b-p4lne0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge)

___
*[pkg/internal/sqlsmith/tlp.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_P8nR-v6wOfdxWcq8:-Mj_P8nR-v6wOfdxWcq9:b-ocymf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L55)):*
> ```Go
> //
> // If the resulting counts of the two queries are not equal, there is a logical
> // bug.
> ```

Can you update this comment now that JOINs are supported - there's a few places that should be reworded I think. Consider moving the example for the WHERE TLP query to `generateWhereTLP` and making the comment for `GenerateTLP` a little more high-level.
___
*[pkg/internal/sqlsmith/tlp.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_PVpW0QHcUhDmBC1_:-Mj_PVpW0QHcUhDmBC1a:b745jxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L70)):*
> ```Go
> }
> 
> func (s *Smither) GenerateWhereTLP() (unpartitioned, partitioned string) {
> ```

nit: `generateWhereTLP`
___
*[pkg/internal/sqlsmith/tlp.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_Nx0r5EwcZij0br72:-Mj_Nx0r5EwcZij0br73:blwtj0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L98)):*
> ```Go
> }
> 
> func (s *Smither) GenerateJoinTLP() (unpartitioned, partitioned string) {
> ```

nit: this function doesn't need to be exported, so you can name it `generateJoinTLP` instead

Also, a function comment here is a good place to explain how JOIN TLP logic works. Consider adding an example of the form of the returned queries and explaining why they should produce the same results.
___
*[pkg/internal/sqlsmith/tlp.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_OnI6DC0iZAaFb4FH:-Mj_OnI6DC0iZAaFb4FI:bgl5daz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L118)):*
> ```Go
> 	cols := cols1
> 	for _, col := range cols2 {
> 		cols.extend(col)
> ```

looks like `colRefs.extend` is a [variadic function](https://gobyexample.com/variadic-functions), so you can simplify this to `cols := cols1.extend(cols2...)`

**Review by nehageorge — COMMENTED** [review]
Thanks for the link! In the CockroachDB Join Oracle it seems to be just left join. Could be possible though if it's done in other DBs... maybe worth looking into.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-:-Mj_zOY_4mc_XE4h8a01:b-gj8a70)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/internal/sqlsmith/tlp.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_P8nR-v6wOfdxWcq8:-Mj_ycV5EBZnjSDgyguu:by965ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L55)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you update this comment now that JOINs are supported - there's a few places that should be reworded I think. Consider moving the example for the WHERE TLP query to `generateWhereTLP` and making the comment for `GenerateTLP` a little more high-level.
</blockquote></details>

Yep, will do
___
*[pkg/internal/sqlsmith/tlp.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_PVpW0QHcUhDmBC1_:-Mj_yufK83yyQ-vAQrGI:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L70)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `generateWhereTLP`
</blockquote></details>

Sounds good
___
*[pkg/internal/sqlsmith/tlp.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_Nx0r5EwcZij0br72:-Mj_z2sB5Nwe8zmVX-J7:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L98)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: this function doesn't need to be exported, so you can name it `generateJoinTLP` instead

Also, a function comment here is a good place to explain how JOIN TLP logic works. Consider adding an example of the form of the returned queries and explaining why they should produce the same results.
</blockquote></details>

Sounds good
___
*[pkg/internal/sqlsmith/tlp.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mj_OnI6DC0iZAaFb4FH:-Mj_zBen8qTWNiKY-0Lx:b-hyeyx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8376cb45332b53dc4aaa606ce76783b4a4f4a09/pkg/internal/sqlsmith/tlp.go#L118)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

looks like `colRefs.extend` is a [variadic function](https://gobyexample.com/variadic-functions), so you can simplify this to `cols := cols1.extend(cols2...)`
</blockquote></details>

Ooh cool thanks, ah I was missing the "..." syntax when I was trying to use it like that.

**Review by mgartner — COMMENTED** [review]
Cool. We can explore other joins in the future. This is already a big improvement in the surface area being tested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-:-MjdwUbG3UFE7j8ddTN6:b-nz9gg8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/internal/sqlsmith/tlp.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mjdt7qb6w6oNcxTqKXp:-Mjdt7qb6w6oNcxTqKXq:b-x4gbzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L53)):*
> ```Go
> }
> 
> // generateWhereTLP returns two SQL queries as strings that can be used by the GenerateTLP function.
> ```

nit: wrap comments at 80 characters.

I use the `Wrap To Column` GoLand plugin to make this less manual:


___
*[pkg/internal/sqlsmith/tlp.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mjdvy_334gLWYtHK69T:-Mjdvy_334gLWYtHK69U:bft9e2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L127)):*
> ```Go
> // and then all rows concatenated with NULL values for the second and third parts
> // (JOIN ON FALSE). Recall our TLP logical guarantee that a given predicate p
> // satisfies either (p), NOT (p), or (p) is NULL. It follows that for any row
> ```

nit: "a given predicate p satisfies either (p), NOT (p), or (p) IS NULL" is a bit confusing. Maybe something like: "Recall out TLP logical guarantee that a given predicate p always evaluates to either true, false, or NULL."
___
*[pkg/internal/sqlsmith/tlp.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-MjdwLxb6o1Glr4qjMXO:-MjdwLxb6o1Glr4qjMXP:bnwyljv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L146)):*
> ```Go
> 	table1.Format(f)
> 	table2.Format(f)
> 	tableName1 := f.CloseAndGetString()
> ```

I think you need to close and get the string for table1 before writing table2 to `f`.
___
*[pkg/internal/sqlsmith/tlp.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mjdv5cQ9jLMGQvEQ7k0:-Mjdv5cQ9jLMGQvEQ7k1:b-n1xj4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L154)):*
> ```Go
> 	unpartitioned = fmt.Sprintf("SELECT count(*) FROM (%s UNION ALL %s UNION ALL %s)", leftJoinTrue, leftJoinFalse, leftJoinFalse)
> 
> 	pred := makeBoolExpr(s, cols1)
> ```

Can the predicate only include columns from the left side of the join? It would be nice to test cases where the predicates refer to columns on both sides. By referring to columns only on one side I think we will only perform cross-joins. Testing more useful join algorithms like merge-joins and lookup-joins would be good.

```
defaultdb> create table t1 (k int primary key);
CREATE TABLE

defaultdb> create table t2 (k int primary key);
CREATE TABLE

defaultdb> explain select * from t1 left join t2 on t1.k > 0;
            info
-----------------------------
  distribution: full
  vectorized: true

  • cross join (left outer)
  │ pred: k > 0
  │
  ├── • scan
  │     missing stats
  │     table: t1@primary
  │     spans: FULL SCAN
  │
  └── • scan
        missing stats
        table: t2@primary
        spans: FULL SCAN
(15 rows)

defaultdb> explain select * from t1 left join t2 on t1.k = t2.k;
            info
-----------------------------
  distribution: full
  vectorized: true

  • merge join (left outer)
  │ equality: (k) = (k)
  │ left cols are key
  │ right cols are key
  │
  ├── • scan
  │     missing stats
  │     table: t1@primary
  │     spans: FULL SCAN
  │
  └── • scan
        missing stats
        table: t2@primary
        spans: FULL SCAN
(17 rows)
```

**Review by rytaft — COMMENTED** [review]
Nice! 

nit: It would be good to update the PR message to include the info from your commit message. We also format the titles of PR messages the same way as commit messages, with `pkg: ...`. You can update the title and PR message directly from GitHub.

Is there a way to test that this is working? I know it's hard to test randomized tests, but maybe we could add a way to mock the random generation piece? Probably not necessary for this PR, but would be good to think about for the future.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-:-Mje4OOJ64abmW2JkgxF:bn4b2n4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge)

**Review by nehageorge — COMMENTED** [review]
Done. And this is an interesting point. I wonder how far we would go for the mocking as there are several random generation components - we have the tables and the boolean predicate expression. But yes I think definitely best done in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-:-MjeZG-26SZjs1Ba49A1:b-w5pz41)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/internal/sqlsmith/tlp.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mjdt7qb6w6oNcxTqKXp:-MjeaF4QEj_L75h-L0-Q:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L53)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: wrap comments at 80 characters.

I use the `Wrap To Column` GoLand plugin to make this less manual:




</blockquote></details>

Done
___
*[pkg/internal/sqlsmith/tlp.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mjdvy_334gLWYtHK69T:-MjeaHBM3Hw3E2hXZQAv:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L127)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "a given predicate p satisfies either (p), NOT (p), or (p) IS NULL" is a bit confusing. Maybe something like: "Recall out TLP logical guarantee that a given predicate p always evaluates to either true, false, or NULL."
</blockquote></details>

Done
___
*[pkg/internal/sqlsmith/tlp.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-MjdwLxb6o1Glr4qjMXO:-MjeaIFDCnIVHMl2D66u:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L146)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think you need to close and get the string for table1 before writing table2 to `f`.
</blockquote></details>

Done
___
*[pkg/internal/sqlsmith/tlp.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-Mjdv5cQ9jLMGQvEQ7k0:-MjeaK3r8S6b-5QyJXo6:b-naovl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5542d513e883f5f8b6a9445ff44751d31d34/pkg/internal/sqlsmith/tlp.go#L154)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can the predicate only include columns from the left side of the join? It would be nice to test cases where the predicates refer to columns on both sides. By referring to columns only on one side I think we will only perform cross-joins. Testing more useful join algorithms like merge-joins and lookup-joins would be good.

```
defaultdb> create table t1 (k int primary key);
CREATE TABLE

defaultdb> create table t2 (k int primary key);
CREATE TABLE

defaultdb> explain select * from t1 left join t2 on t1.k > 0;
            info
-----------------------------
  distribution: full
  vectorized: true

  • cross join (left outer)
  │ pred: k > 0
  │
  ├── • scan
  │     missing stats
  │     table: t1@primary
  │     spans: FULL SCAN
  │
  └── • scan
        missing stats
        table: t2@primary
        spans: FULL SCAN
(15 rows)

defaultdb> explain select * from t1 left join t2 on t1.k = t2.k;
            info
-----------------------------
  distribution: full
  vectorized: true

  • merge join (left outer)
  │ equality: (k) = (k)
  │ left cols are key
  │ right cols are key
  │
  ├── • scan
  │     missing stats
  │     table: t1@primary
  │     spans: FULL SCAN
  │
  └── • scan
        missing stats
        table: t2@primary
        spans: FULL SCAN
(17 rows)
```
</blockquote></details>

Documenting our chat here for transparency. It seems that only left table columns can be included if the JOIN partitioning is set up in the same way Manuel Rigger did in https://github.com/sqlancer/sqlancer/blob/master/src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPJoinOracle.java. However, to confirm and clarify, we will be emailing him. Since this isn't blocking, additional changes can be done in a future PR.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-:-MjfHkIr8Z5DMT6Tpnfh:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/internal/sqlsmith/tlp.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-MjfGoY47A_L38KqiQyF:-MjfGoY54DP1G6E_5xdW:b-uyxc6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90751f26af90ebdf11f945f914a247c6b97b82c/pkg/internal/sqlsmith/tlp.go#L94)):*
> ```Go
> 		tableName, predicate)
> 	part3 := fmt.Sprintf("SELECT * FROM %s WHERE (%s) IS NULL",
> 		tableName, predicate)
> ```

nit: only comments need to be wrapped at 80 characters. Code should be wrapped at 100 characters (not a problem to wrap it before, but just FYI). 

Also, it's more idiomatic in our codebase to wrap code like this (with the parentheses on separate lines):
```
	part3 := fmt.Sprintf(
		"SELECT * FROM %s WHERE (%s) IS NULL",
		tableName, predicate,
	)
```

**Review by mgartner — APPROVED** [review]
Great job! :lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70208#-:-Mjk728jDDfWkl75A-Lo:b-jxntrk)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nehageorge)

**Pull request merged**
