### PR TITLE
storage: tick the logical clock for quiescent ranges

### LINKED ISSUE #9372: storage: quiescence leads to more elections
I'm able to reproduce the additional elections when quiescing is turned on in a local test environment. Within a single scheduler worker iteration we do the following:

```
			// Process the range ID.
			if state&stateRaftTick != 0 {
				// processRaftTick returns true if the range should perform ready
				// processing. Do not reorder this below the call to processRaftReady.
				if s.processor.processTick(id) {
					state |= stateRaftReady
				}
			}
			if state&stateRaftRequest != 0 {
				s.processor.processRequestQueue(id)
			}
			if state&stateRaftReady != 0 {
				s.processor.processReady(id)
			}
```

My untested hypothesis of what is happening:
1. Follower ticks a replica.
2. Follower processes a "quiesce" message from the leader.
3. Followers performs raft ready processing (due to the earlier tick) which unquiesces the replica.

At this point, the leader is "quiesced" but the follower is not. The follower will tick and then perform an election. What I'm not quite clear on is that exact timing for why this causes a disruption of request processing.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #9372.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9424)

### CODE REVIEW

**Comment by petermattis** [comment]
Cherry-picked from `develop`.

**Comment by petermattis** [comment]
Cc @cockroachdb/stability

**Comment by petermattis** [comment]
Anyone around to rubber stamp this?

**Review by rjnn — APPROVED** [review]
LGTM.

**Comment by tschottdorf** [comment]
LGTM

**Pull request merged**
