### PR TITLE
opt: some cleanup in CTE code

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit cleans up the optbuilder code related to CTEs and improves
its documentation.

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-:-MXI_lDA5SsZreUudhMP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/with.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-MXIWr4y8uVgchUGamaO:-MXIWr4y8uVgchUGamaP:bgqpasw) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c1d490ce5ae524343b5f1e793fa16c400dfe6b/pkg/sql/opt/optbuilder/with.go#L38)):*
> ```Go
> // addCTEToWithFrame adds a CTE to the current frame.
> func (b *Builder) addCTEToWithFrame(cte cteSource) {
> 	b.cteStack[len(b.cteStack)-1] = append(b.cteStack[len(b.cteStack)-1], cte)
> ```

nit: maybe more readable if you set `len(b.cteStack)-1` to a variable, up to you
___
*[pkg/sql/opt/optbuilder/with.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-MXIX3H4BymX5tb2QkQh:-MXIX3H4BymX5tb2QkQi:bactpjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c1d490ce5ae524343b5f1e793fa16c400dfe6b/pkg/sql/opt/optbuilder/with.go#L45)):*
> ```Go
> func (b *Builder) popWithFrame(s *scope) {
> 	ctes := b.cteStack[len(b.cteStack)-1]
> 	b.cteStack = b.cteStack[:len(b.cteStack)-1]
> ```

nit: ditto, variable for `len(b.cteStack)-1`?
___
*[pkg/sql/opt/optbuilder/with.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-MXI_gtj-ZyvtTN_5AYU:-MXI_gtj-ZyvtTN_5AYV:b67vyq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c1d490ce5ae524343b5f1e793fa16c400dfe6b/pkg/sql/opt/optbuilder/with.go#L51)):*
> ```Go
> 
> // addWiths adds With expressions on top of an expression.
> func (b *Builder) addWiths(expr memo.RelExpr, ctes []cteSource) memo.RelExpr {
> ```

nit: should this be named `buildWiths`?
___
*[pkg/sql/opt/optbuilder/with.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-MXIZUJ21AiRvz-XuaXU:-MXIZUJ21AiRvz-XuaXV:b-61oens) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c1d490ce5ae524343b5f1e793fa16c400dfe6b/pkg/sql/opt/optbuilder/with.go#L57)):*
> ```Go
> 
> 	// Since later CTEs can refer to earlier ones, we want to add these in
> 	// reverse order.
> ```

This comment confuses me. If later CTEs can refer to earlier ones, shouldn't the later ones wrap the earlier ones, not the other way around? The order of CTEs in the stack should be the same as the order of with.CTEList, as far as I can tell. So is with.CTEList actually reversed?
___
*[pkg/sql/opt/optbuilder/with.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-MXIZxbSB51fAfSRFRzU:-MXIZxbSB51fAfSRFRzV:bv0l5eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c1d490ce5ae524343b5f1e793fa16c400dfe6b/pkg/sql/opt/optbuilder/with.go#L88)):*
> ```Go
> 
> // buildCTEs constructs expressions for the CTEs defined by a WITH clause adds
> // them to the CTE stack.
> ```

nit: did you mean "... **and** adds them to the CTE stack"?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/with.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-MXIZUJ21AiRvz-XuaXU:-MXImG1Y5IlicAVdWqz8:b-g4d1dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c1d490ce5ae524343b5f1e793fa16c400dfe6b/pkg/sql/opt/optbuilder/with.go#L57)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This comment confuses me. If later CTEs can refer to earlier ones, shouldn't the later ones wrap the earlier ones, not the other way around? The order of CTEs in the stack should be the same as the order of with.CTEList, as far as I can tell. So is with.CTEList actually reversed?
</blockquote></details>

An inner CTE B which refers to an outer CTE A must be under the With operator for A (same nesting as in the query).  You can only refer to a CTE if you are somewhere inside the right branch of its WithOp.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-:-MXO2-q033Adr0fimpRm:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

**Comment by RaduBerinde** [comment]
I have added a second commit which goes further:

#### opt: refactor cteStack

This commit refactors the "with stack". We replace a pair of push/pop
methods with a single method which takes an inner build function.
This makes the code a bit cleaner and allows us to remove the
cteStack, saving an allocation.

An unnecessary boundary around the initial part of a recursive CTE is
removed. We only need one around the recursive part, because of
recursive references in CTEs. This is actually a hack, and will be
addressed in a future change.

Release note: None

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-:-MXYU7-b9ZGQUHHKh8zz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/optbuilder/with.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63008#-MXIZUJ21AiRvz-XuaXU:-MXYRVwB4JrzxkNGJo0C:b-a7jug4) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c1d490ce5ae524343b5f1e793fa16c400dfe6b/pkg/sql/opt/optbuilder/with.go#L57)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

An inner CTE B which refers to an outer CTE A must be under the With operator for A (same nesting as in the query).  You can only refer to a CTE if you are somewhere inside the right branch of its WithOp.
</blockquote></details>

I see. Thanks for the explanation!

**Pull request merged**
