### PR TITLE
sql: sanitize the handling of limits and desired orderings.

### PR DESCRIPTION
**Pull request by knz**
This patchset simplifies the planNode interface and removes the confusing/hard-to-understand `top` field from `renderNode`. It also enables sub-queries to use the surrounding EXISTS clause or their usage in a scalar context as a row limit hint.

cc @vivekmenezes for the change to the backfill code.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13118)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
A general question - since we now pass down some form of a limit through `expandPlan`, would it make sense to move all limit propagation in `expandPlan` (instead of the `setLimitHint` stuff)?

---

Review status: 0 of 42 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/check.go, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGcb8WWHtzlns4sc4V:-KbGcb8WWHtzlns4sc4W:b8ahha1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/check.go#L146)):*
> ```Go
> 		return err
> 	}
> 	rows.SetLimitHint(1, true)
> ```

Why is this better than the old code? I think it's nicer to let the limit node do its thing instead of doing it ourselves here..

---

*[pkg/sql/expand_plan.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGWzxKOhj593372PfE:-KbGWzxKOhj593372PfF:b-ctldna) ([raw file](https://github.com/cockroachdb/cockroach/blob/08f900b441c2ce7e577270d903327758659e4f8c/pkg/sql/expand_plan.go#L40)):*
> ```Go
> // a given level to the levels under it (upstream).
> type planExpander struct {
> 	p               *planner
> ```

`p.p` is confusing, I would name this `planner`

---

*[pkg/sql/expand_plan.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGVhLfYtHjzhnYSMZh:-KbGVhLfYtHjzhnYSMZi:b3esxz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/08f900b441c2ce7e577270d903327758659e4f8c/pkg/sql/expand_plan.go#L54)):*
> ```Go
> 
> // expand is the algorithm that supports expandPlan().
> func (p planExpander) expand(plan planNode) (planNode, error) {
> ```

wouldn't it be easier to just pass an extra "params expandParams" argument? It would be much clearer what `params = expandParams{}` or `p.expandPlan(expandParams{}, ..)` does compared to `p = makePlanExpander(p.p)`

If not, I would at least replace the `p = makePlanExpander(p.p)` calls with something like `p.clear()`

---

*[pkg/sql/limit_hint.go, line 45 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbG_9JdlnGjA25VN0Yy:-KbG_9JdlnGjA25VN0Yz:bdpwdlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a56fbeeb8ecbbe7a91862462a9f80f084bee1655/pkg/sql/limit_hint.go#L45)):*
> ```Go
> // soft limit propagated up by nodes downstream. We may want to
> // improve this API to pass both the soft and hard limit.
> func setLimitHint(plan planNode, numRows int64, soft bool) {
> ```

"hint" is not a great name because the hard limits are a guarantee, not just a hint. Perhaps this is a good time to rename it, I'd say `propagateLimit` instead of `setLimitHint`

Also, to be more general we probably want to pass a `softLimit` and a `hardLimit` (with `softLimit >= hardLimit`) instead of just one of them. Doesn't need to be in this PR though.

---

*[pkg/sql/optimize.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGXX2phNA1BTM5g-Rc:-KbGXX2phNA1BTM5g-Rd:b-wqe11n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L73)):*
> ```Go
> func (i *subqueryInitializer) subqueryNode(sq *subquery) error {
> 	if sq.plan != nil && !sq.expanded {
> 		neededRows := int64(math.MaxInt64)
> ```

`int64()` not needed

---

*[pkg/sql/optimize.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGkufv6Sh__qsagcOX:-KbGkufv6Sh__qsagcOY:b-33qvw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L87)):*
> ```Go
> 
> 		var err error
> 		sq.plan, err = i.p.optimizePlan(sq.plan, neededCols, neededRows)
> ```

Could we add a limitNode to the plan instead of hacking `optimizePlan`?

Note that if/when we make the subquery run through distsql, the limit information won't be there anymore, except as whatever `setLimitHint` left behind (which is not much outside of scan nodes). Without a limitNode there won't be anything making processors stop from sending rows, regardless if we only end up using one row.

---

*[pkg/sql/testdata/insert, line 499 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGbnsgju3BfpPF3Zow:-KbGbnsgju3BfpPF3Zox:bl87ntm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a56fbeeb8ecbbe7a91862462a9f80f084bee1655/pkg/sql/testdata/insert#L499)):*
> ```
> 2  scan
> 2                 table     select_t@primary
> 2				  limit		1
> ```

tabs
`autocmd BufNewFile,BufRead */sql/testdata/* set expandtab`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-:-KbGc2EC6fMVzovfrtPP:b-wl5cq3)*

**Comment by knz** [comment]
Regarding your first question: no we can't do that yet, because we need to wait until Start() for all sub-query values to be replaced -- the LIMIT/OFFSET clauses may contain sub-queries.

---

Review status: 0 of 42 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/check.go, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGcb8WWHtzlns4sc4V:-KbJEKpcpTYoPRJZzKzN:bp5zxhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/check.go#L146)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is this better than the old code? I think it's nicer to let the limit node do its thing instead of doing it ourselves here..
</blockquote></details>

Ok, I reverted that change.

---

*[pkg/sql/expand_plan.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGWzxKOhj593372PfE:-KbJEOIz9GO0mWKlhte4:b-9plnwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/08f900b441c2ce7e577270d903327758659e4f8c/pkg/sql/expand_plan.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`p.p` is confusing, I would name this `planner`
</blockquote></details>

I changed the other `p` instead.

---

*[pkg/sql/expand_plan.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGVhLfYtHjzhnYSMZh:-KbJ8ensE0RBOZCzI7MY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08f900b441c2ce7e577270d903327758659e4f8c/pkg/sql/expand_plan.go#L54)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

wouldn't it be easier to just pass an extra "params expandParams" argument? It would be much clearer what `params = expandParams{}` or `p.expandPlan(expandParams{}, ..)` does compared to `p = makePlanExpander(p.p)`

If not, I would at least replace the `p = makePlanExpander(p.p)` calls with something like `p.clear()`
</blockquote></details>

Done.

---

*[pkg/sql/limit_hint.go, line 45 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbG_9JdlnGjA25VN0Yy:-KbJIE2pwcxzMjTSJcgd:b-m386bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a56fbeeb8ecbbe7a91862462a9f80f084bee1655/pkg/sql/limit_hint.go#L45)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

"hint" is not a great name because the hard limits are a guarantee, not just a hint. Perhaps this is a good time to rename it, I'd say `propagateLimit` instead of `setLimitHint`

Also, to be more general we probably want to pass a `softLimit` and a `hardLimit` (with `softLimit >= hardLimit`) instead of just one of them. Doesn't need to be in this PR though.
</blockquote></details>

I'll use `applyLimit`, because I want to keep `propagateLimit` for a later transform similar to `propagateFilter`.

The other change should wait for a later PR indeed.

---

*[pkg/sql/optimize.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGXX2phNA1BTM5g-Rc:-KbJ8qvah0PDfedz-lNA:bmomci3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`int64()` not needed
</blockquote></details>

Actually it is -- otherwise I get a compile error.
That's because `MaxInt64` is an untyped const, not an `int64` var. (Did I mention I hated Go today yet?)

---

*[pkg/sql/optimize.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGkufv6Sh__qsagcOX:-KbJES4cGrRx8eZ6ux8a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L87)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Could we add a limitNode to the plan instead of hacking `optimizePlan`?

Note that if/when we make the subquery run through distsql, the limit information won't be there anymore, except as whatever `setLimitHint` left behind (which is not much outside of scan nodes). Without a limitNode there won't be anything making processors stop from sending rows, regardless if we only end up using one row.
</blockquote></details>

Done.

---

*[pkg/sql/testdata/insert, line 499 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGbnsgju3BfpPF3Zow:-KbJH8_MiRGWUO5O16ep:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a56fbeeb8ecbbe7a91862462a9f80f084bee1655/pkg/sql/testdata/insert#L499)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

tabs
`autocmd BufNewFile,BufRead */sql/testdata/* set expandtab`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-:-KbJ68OA86VtCPRHwnuj:b-itk28n)*

**Comment by RaduBerinde** [comment]
Oh, right! Subqueries in LIMIT/OFFSET are so annoying!

:lgtm_strong:  Thanks for making all the changes!

---

Review status: 0 of 37 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/optimize.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGXX2phNA1BTM5g-Rc:-KbKdgUxlliRO7l3m9gE:b-ezh3y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L73)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Actually it is -- otherwise I get a compile error.
That's because `MaxInt64` is an untyped const, not an `int64` var. (Did I mention I hated Go today yet?)
</blockquote></details>

Oh, I see, because we're doing `:=` so it needs to know the type (we can definitely assign to an existing int64 var without cast).

---

*[pkg/sql/optimize.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGkufv6Sh__qsagcOX:-KbKfdF8XBnZyO45gQay:b-5bu0sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L87)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!
What about `execModeOneRow`? We could add a `LIMIT 2` in that case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-:-KbKe0FiN2L9vlk--AU8:bavvjgk)*

**Comment by knz** [comment]
Review status: 0 of 37 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/optimize.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGkufv6Sh__qsagcOX:-KbKiZIYgM50sGDL81eX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L87)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Nice!
What about `execModeOneRow`? We could add a `LIMIT 2` in that case
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118)*

**Comment by RaduBerinde** [comment]
Reviewed 7 of 42 files at r4, 4 of 4 files at r5, 35 of 35 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/optimize.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbGkufv6Sh__qsagcOX:-KbKkESX_JTodimS3eu4:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af903a920c86111fc9d8b53d4967cc04939e8fd/pkg/sql/optimize.go#L87)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118)*

**Comment by knz** [comment]
TFYR!

**Comment by RaduBerinde** [comment]
*[pkg/sql/backfill.go, line 686 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118#-KbzHrmnMr5i7vS5YIXf:-KbzHrmnMr5i7vS5YIXg:bfi2j6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/81e8f13b70b7e95092b53f65dadda78cc847891c/pkg/sql/backfill.go#L686)):*
> ```Go
> 		}
> 
> 		if err := planner.startPlanWithLimit(rows, chunkSize); err != nil {
> ```

Sorry, I just happened to see this now - I think we should add a `LIMIT` node here as well (like we did in the other cases) and remove `startPlanWithLimit`, because distsql won't apply the limit properly (if/when we use distsql).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13118)*

**Pull request merged**
