### PR TITLE
roachtest: tpcc/large-schema-benchmark: add support for multi-region

### LINKED ISSUE #123758: roachtest: extend large schema benchmark into multi-region
Our initial benchmark for large numbers of schema objects will be limited a single region, but as a next phase we should extend it to multi-region. As a part of this work we should:

- [ ] Configure the databases for multi-region out of the box
- [ ] Determine access patterns for workers and worker placement, so that tertiary databases will be region local
- [ ] Optimize workers so that they are localized to minimize variability due to connection latencies from client to server
- [ ] Confirm the performance metrics are stable in this configuration

Epic: [CRDB-37483](https://cockroachlabs.atlassian.net/browse/CRDB-37483)

Jira issue: CRDB-38530

Epic CRDB-37483

### PR DESCRIPTION
**Pull request by fqazi**
This PR extends the tpcc/large-schema-benchmark workload to implement support for multi-region, so that we can get a better understanding of performance with larger schemas in a multi-region cluster. To support this, this patch does the following

1. Update the multi-db TPCC workload to use explicit transactions and reset search_paths so that we can more optimally configure large schemas
2. Update the cockroach workload insert / import commands to use explicit transactions for CREATE TABLE statements, and explicitly select the database, since otherwise multi-region CREATEs can be slow / fail.
3. Fix a bug that prevent proper histogram generation within the large schema benchmark for roachperf.
4. Update  tpcc/large-schema-benchmark to add support for multi-region

Fixes: #123758

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126835)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/large_schema_benchmark.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126835#-O1WzWVP3t4pu_SHJzgR:-O1WzWVQ4KdiRQ9da4Gp:bigzv8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d3c3153b3f1a1ccf5cf8189b5a46645d3ca53c/pkg/cmd/roachtest/tests/large_schema_benchmark.go#L54)):*
> ```Go
> 	if isMultiRegion {
> 		regions = "us-east1,us-west1,us-central1"
> 		testTimeout = 24 * time.Hour
> ```

I'm curious why the test timeout needs to be increased by 5 hours for multi-region. Was there a case where this is needed?
___
*[`pkg/workload/workloadsql/dataload.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126835#-O1WxesiDKimosi1fOb6:-O1WxesiDKimosi1fOb7:b-oogfis) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd9b6d90d77e0b270eb55c8ed54e059233204c00/pkg/workload/workloadsql/dataload.go#L85)):*
> ```Go
> 						return err
> 					}
> 					currentDatabase = string(table.ObjectPrefix.CatalogName)
> ```

nit: could we use `table.ObjectPrefix.Catalog()` to avoid the cast?



_Suggestion:_
```Go
					currentDatabase != table.ObjectPrefix.Catalog() {
					_, err := tx.ExecContext(ctx, "USE $1", table.ObjectPrefix.Catalog())
					if err != nil {
						return err
					}
					currentDatabase = table.ObjectPrefix.Catalog()
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126835)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @spilchen, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/large_schema_benchmark.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126835#-O1WzWVP3t4pu_SHJzgR:-O1oRX2zAWMoMXsxJQGl:b-tgvbdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d3c3153b3f1a1ccf5cf8189b5a46645d3ca53c/pkg/cmd/roachtest/tests/large_schema_benchmark.go#L54)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I'm curious why the test timeout needs to be increased by 5 hours for multi-region. Was there a case where this is needed?
</blockquote></details>

Yes, sadly just the data load for 10k tables is close to 24 hours in multi-region just because of the latencies involved.  It imports close to 800 gigabytes of data across that many table, which can get bogged down because of the latencies.
___
*[`pkg/workload/workloadsql/dataload.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126835#-O1WxesiDKimosi1fOb6:-O1oRGp1CbytPK2JG3_9:bg3fp7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd9b6d90d77e0b270eb55c8ed54e059233204c00/pkg/workload/workloadsql/dataload.go#L85)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: could we use `table.ObjectPrefix.Catalog()` to avoid the cast?
</blockquote></details>

Done.

Good point!

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r5, 4 of 4 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126835#-:-O1qHoha-Fb8ExHL9a_r:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Pull request merged**
