### PR TITLE
workload: reintroduce old `prepare` behavior

### LINKED ISSUE #69316: workload: large number of DEALLOCATE statements after pgx upgrade
After the pgx upgrade in #68608 various workloads seem to be running huge numbers of (hundreds to thousands) DEALLOCATE statements. These are commands that delete a prepared statement.

The behavior change started after August 17, which was when the upgrade PR was merged. The new pgx behavior is to use a `stmtcache`, which is an LRU cache that automatically prepares any statement executed by pgx. When an entry is evicted from the LRU cache, the statement is deallocated. See https://github.com/jackc/pgconn/blob/53f5fed36c570f0b5c98d6ec2415658c7b9bd11c/stmtcache/lru.go#L118 

Previously, the workload would explicitly prepare the statements it needs to use (and these would never get deallocated), but that behavior was removed because pgx no longer allows you to prepare a statement at the connection pool level. See commit https://github.com/cockroachdb/cockroach/pull/68608/commits/f446498d487783ffbec2b1dec084d85ac65c7647

Perhaps we need to do something else to make sure the workload SQL statements don't get deallocated.

This issue might be causing the failures of https://github.com/cockroachdb/cockroach/issues/69086 but that investigation is happening separately, in parallel.

### PR DESCRIPTION
**Pull request by rafiss**
This reverts commit f446498d487783ffbec2b1dec084d85ac65c7647,
and makes the 'prepare' setting work more closely to how it used to.

This is needed because we are seeing that the schemachange workload is
deallocating huge amounts of automatically prepared statements. By
explicitly preparing statements again, they should no longer be
deallocated.

This also disables the automatic prepared statement cache in pgx entirely,
which was enabled in https://github.com/jackc/pgx/commit/0c3e59b07a882e25a896f1b0e75a84461cc889cf

Release justification: test-only change
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
I ran `schemachange/index/tpcc/w=1000` with this change and still see hundreds/thousands of DEALLOCATE statements.

**Comment by rafiss** [comment]
Ah I see, jackc/pgx@0c3e59b is new in pgx4 and enables this automatic prepared statement caching. I made a 2nd commit in this PR which turns that off and it has gotten rid of all the DEALLOCATE statements.

**Review by ajwerner — APPROVED** [review]
:lgtm: though I wonder how important the first commit is. What would happen if we only merged the second commit?

> Reviewed 12 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69313#-:-MhxyzuX71fyhsNsgNb4:b-5jpjhr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rafiss** [comment]
I agree, the 2nd commit is what prevents the thousands of DEALLOCATE statements.

I think the 1st commit is still good since we shouldn't change the client behavior unintentionally. If we didn't merge the first commit, what would happen is that every query would be run using Parse/Bind/Execute every time, using an anonymous prepared statement. I feel that if we want that behavior it's better to opt-in explicitly by using the `noprepare` workload setting.

**Pull request merged**
