### PR TITLE
opt/xform: make merge join have smaller table on the right side

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: ignore last noop processor on gateway when moving single flow**

When figuring out whether a physical plan consists of flows on multiple
nodes, we want to ignore the noop processor that might be planned on the
gateway for a sole purpose of propagating the results back to the client
(in another words, when we have a flow on the gateway consisting only of
a noop processor). Previously, we forgot to do that.

Release note: None

**opt/xform: make merge join have smaller table on the right side**

A PR that is currently in-flight will change the implementation of the
vectorized merge joiner so that it processes the left input always in
a streaming fashion whereas the right input might be buffered
(partially) in some cases. To account for this difference this commit
changes the cost model by introducing a small factor to the right row
count which ensures that the smaller right side is preferred to the
symmetric join.

This commit also handles the case of partial joins in a similar manner
to how we handle the hash join.

Fixes: #71790.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
What modification of memo.MergeJoinExpr are you referring to?

**Comment by yuzefovich** [comment]
This one: https://github.com/cockroachdb/cockroach/blob/90c4cf2f030740654ee5273ccab020ec15181596/pkg/sql/opt/exec/execbuilder/relational.go#L1179-L1181

**Review by cucaroach — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 11 of 11 files at r3, 11 of 11 files at r4, 1 of 1 files at r5, 13 of 13 files at r6, 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by rytaft — COMMENTED** [review]
nit: xfrom -> xform in the commit/PR message title

The stats quality test changes LGTM

> Reviewed 2 of 2 files at r1, 11 of 11 files at r3, 11 of 11 files at r4, 1 of 1 files at r5, 13 of 13 files at r6, 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-:-MmryWJhAC0lYYCd1r1S:b-5xoc4c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[-- commits, line 23 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mms0EX1CoGvXm0krhne):*
nit: a similar -> a similar fashion?
___
*[pkg/sql/opt/xform/coster.go, line 860 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mms-gya9j-CDhfIPQnN:-Mms-gyb7qA1QEDBl8sz:b-trk035) ([raw file](https://github.com/cockroachdb/cockroach/blob/289f9c753e66b5145a62167da76ed533d87915be/pkg/sql/opt/xform/coster.go#L860)):*
> ```Go
> 	// ensures that a join with the smaller right side is preferred to the
> 	// symmetric join.
> 	cost := memo.Cost(leftRowCount+1.25*rightRowCount) * cpuCostFactor
> ```

Have you compared the impact on plans if you also multiply `leftRowCount` by 0.75? (We might want to consider doing this if there are any cases where a different join type is now preferred over merge join, but I didn't see many of those...)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 860 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mms-gya9j-CDhfIPQnN:-MmsMjgu5ZGdlA5pawSn:b-3ff4nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/289f9c753e66b5145a62167da76ed533d87915be/pkg/sql/opt/xform/coster.go#L860)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Have you compared the impact on plans if you also multiply `leftRowCount` by 0.75? (We might want to consider doing this if there are any cases where a different join type is now preferred over merge join, but I didn't see many of those...) 
</blockquote></details>

I don't think I saw any merge joins change into non-merge joins. Is you reasoning such that we'd like to keep the cost of merge joins roughly unchanged? Would we be happy with `0.75 x 1.25` multiples? Maybe `0.9 x 1.1` would be better?

**Review by rytaft — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[-- commits, line 24 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-MmsWutN3t8IglGJkskq):*
nit: to how we handle
___
*[pkg/sql/opt/xform/coster.go, line 860 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mms-gya9j-CDhfIPQnN:-MmsX-YmDbZJtzdrXF8I:b-iu7zgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/289f9c753e66b5145a62167da76ed533d87915be/pkg/sql/opt/xform/coster.go#L860)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I don't think I saw any merge joins change into non-merge joins. Is you reasoning such that we'd like to keep the cost of merge joins roughly unchanged? Would we be happy with `0.75 x 1.25` multiples? Maybe `0.9 x 1.1` would be better?
</blockquote></details>

I think I saw at least one non-trivial plan change. But I agree that there weren't many.

Either way, I do think it is worth trying to be sure that we're not increasing the total cost of merge joins with this change. If anything, we should decrease it since your execution change makes them more efficient, not less. But anyway, either 0.75 x 1.25 or 0.9 x 1.1 seems like it would probably do the right thing -- you might just need to give it a try and see which plans change.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 860 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mms-gya9j-CDhfIPQnN:-Mms_bVT8GXwwEIeHTwM:b959lnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/289f9c753e66b5145a62167da76ed533d87915be/pkg/sql/opt/xform/coster.go#L860)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think I saw at least one non-trivial plan change. But I agree that there weren't many.

Either way, I do think it is worth trying to be sure that we're not increasing the total cost of merge joins with this change. If anything, we should decrease it since your execution change makes them more efficient, not less. But anyway, either 0.75 x 1.25 or 0.9 x 1.1 seems like it would probably do the right thing -- you might just need to give it a try and see which plans change.
</blockquote></details>

I think I'll do `0.9 x 1.1` and will regenerate the test files.

I looked over the PR and still don't see any plans that actually changed - do you mind pointing me to it?

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/opt/xform/coster.go, line 860 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mms-gya9j-CDhfIPQnN:-MmsbOw7Bszk7J_GegRM:baheek6) ([raw file](https://github.com/cockroachdb/cockroach/blob/289f9c753e66b5145a62167da76ed533d87915be/pkg/sql/opt/xform/coster.go#L860)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think I'll do `0.9 x 1.1` and will regenerate the test files.

I looked over the PR and still don't see any plans that actually changed - do you mind pointing me to it?
</blockquote></details>

I added a comment -- only found one.
___
*[pkg/sql/opt/xform/coster.go, line 857 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-MmsbzG_-C9zT0Sb_yR-:-MmsbzGa8BZUyDhr4ptj:b-9isf0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29aa7078aae949783e1de3089b484bc67d4b3bb/pkg/sql/opt/xform/coster.go#L857)):*
> ```Go
> 	// The vectorized merge join in some cases buffers rows from the right side
> 	// whereas the left side is processed in a streaming fashion. To account for
> 	// this difference, we add small factors to both row counts which ensures
> ```

super nit: you're not really "adding" a factor to both row counts now... maybe use "multiply" instead?
___
*[pkg/sql/opt/xform/testdata/external/pgjdbc, line 203 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mmsb26U35GpU_6e4qWy:-Mmsb26V9pd4Nq9u0MHH:be7wj2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eefa0d60784c7700e8ea3fa20b48247f5d2a10/pkg/sql/opt/xform/testdata/external/pgjdbc#L203)):*
> ```
>       │    │    │    │    │    │    │    ├── columns: n.oid:2!null n.nspname:3!null c.oid:7!null c.relname:8!null c.relnamespace:9!null c.relkind:24!null attrelid:44!null attname:45 atttypid:46 attlen:48 attnum:49!null atttypmod:52 a.attnotnull:56 attisdropped:60!null
>       │    │    │    │    │    │    │    ├── fd: ()-->(3,60), (2)==(9), (9)==(2), (7)==(44), (44)==(7)
>       │    │    │    │    │    │    │    ├── inner-join (merge)
> ```

This is the plan that seems to have changed to eliminate merge join in favor of hash

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/pgjdbc, line 203 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-Mmsb26U35GpU_6e4qWy:-Mmsi7QI2ZtHYeLwiBtn:bp3e77h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eefa0d60784c7700e8ea3fa20b48247f5d2a10/pkg/sql/opt/xform/testdata/external/pgjdbc#L203)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is the plan that seems to have changed to eliminate merge join in favor of hash
</blockquote></details>

Oh indeed, thanks. This is a merge join again now.

**Review by rytaft — APPROVED** [review]
nit: further down in the PR message you still have "opt/xfrom"

Otherwise, :lgtm:

> Reviewed 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-:-Mmt0e3_3qoFl29u7gGh:b-jvk9sw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by yuzefovich — COMMENTED** [review]
> nit: further down in the PR message you still have "opt/xfrom"

Fixed.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71849#-:-MmtBSWDCxGuB3sSiFkh:btienrx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
