### PR TITLE
builtins: implement ST_S2Covering with optional params

### PR DESCRIPTION
**Pull request by otan**
Also refactored var parsing to paramparse to avoid the builtins <-> sql
circular dependency.

Release note (sql change): implement ST_S2Covering with optional index
parameters.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

it would be good to get someone else from sql to look at the refactoring.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54357#-:-MHGXg3v5XbyZulwxZje:b-kl4fvd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
@arulajmani mind taking a squiz?

**Review by arulajmani — APPROVED** [review]
Refactor LGTM 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54357#-:-MHI622L3G1Fe0RQ4Zzq:bbu59ir)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
tftrs!

bors r=arulajmani,sumeerbhola

**Comment by otan** [comment]
bors r-

woops

**Comment by otan** [comment]
bors r=arulajmani,sumeerbhola

**Pull request merged**
