### PR TITLE
bazel: upgrade `skylib`

### PR DESCRIPTION
**Pull request by rickystewart**
Epic: none

Release note: None

### CODE REVIEW

**Review by sjbarag — APPROVED** [review]
So fast — thanks!!

**Comment by sjbarag** [comment]
Any thoughts on backporting this to 22.2 (and maybe even 22.1)?

**Comment by rickystewart** [comment]
> Any thoughts on backporting this to 22.2 (and maybe even 22.1)?

Shouldn't be a problem, but I don't know how much of the JS changes you're going to be able to backport to these old branches.

**Comment by sjbarag** [comment]
> > Any thoughts on backporting this to 22.2 (and maybe even 22.1)?
> 
> Shouldn't be a problem, but I don't know how much of the JS changes you're going to be able to backport to these old branches.

Hopefully most of them :)

**Comment by rickystewart** [comment]
> Hopefully most of them :)

Is this just trying to make the dev experience consistent across `master` and the release branches?

**Comment by rickystewart** [comment]
bors r=sjbarag

**Comment by sjbarag** [comment]
> > Hopefully most of them :)
> 
> Is this just trying to make the dev experience consistent across `master` and the release branches?

Yep! Though we tend to not add or modify dependencies for past releases, so perhaps it's not a huge issue.  Oh well, that's a conversation for another PR!

**Pull request merged**
