### PR TITLE
Implement Pow using transformation to Exp

### PR DESCRIPTION
**Pull request by seiflotfy**
Reuse existing Exp and Log function to calculate x^y
as  x^y = e^(yln(x)).
- [x] implement pow function
- [x] dec unit tests
- [x] add benchmarks

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5972)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/decimal/decimal.go, line 429 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF4QFpMgXGN4F2kRimS:-KF4QFpMgXGN4F2kRimT:1612917577) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1d61becee22c6b9915edd89222a9edcee64f6c6/util/decimal/decimal.go#L429)):*
It's not surprising we need more precision in something that we use for an **exponent**.

Let's see. Say we compute the Log with a scale of `k`. That means that the result we get is `ln x +/- 10^-k`.
This leads to an error of `y * 10^-k` in the exponent.
That leads to a **multiplicative** error of `e^(y*10^-k)` in the result.
For small values of `u`, `e^u` can be approximated by `1 + u`, so for large `k` that error is around `1 + y*10^-k`. So the additive error will be `x^y * y * 10^-k`, and we want this to be less than `10^-s`. This approximately means that `k` has to be `s` + the number of digits before the decimal point in `x^y`. Which rougly is `s + <the number of digits before decimal point in x>*y`

You can check out the `newLoop` implementation which also counts the number of digits in a number (grep for `digitsToBitsRatio`). Maybe we can implement a common function to help with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by seiflotfy** [comment]
@RaduBerinde what do you think?

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/decimal/decimal.go, line 430 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5W_PWLNgeLRpbkJ9c:-KF5W_PWLNgeLRpbkJ9d:-569293409) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L430)):*
you can paste all the steps in the reasoning so it makes sense to anyone trying to understand this later

---

*[util/decimal/decimal.go, line 432 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5VhmG6nPU4OyLOhpR:-KF5VhmH519PcYtMjvup:-1832991711) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L432)):*
where is the `+` coming from? we should be multiplying with the ratio. Also`int32(digitsToBitsRatio)` is 0..

BTW it would be better if this would be a function that both this code and `newLoop` use (e.g. `x.NumDigits()`)

---

*[util/decimal/decimal.go, line 433 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5WJTs3OPhXZ79Lnmw:-KF5WJTtwLqu2x9TbMzR:-1952984162) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L433)):*
We need to multiply with `y` not `y.Scale()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 432 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5VhmG6nPU4OyLOhpR:-KF5dF6vpgWtUusj-tz-:-1402056282) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L432)):*
Can it be done in another PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/decimal/decimal.go, line 432 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5VhmG6nPU4OyLOhpR:-KF5dnWVzfF6FLGamI_t:1565890184) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L432)):*
Sure (assuming you mean just the second part)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by seiflotfy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 433 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5WJTs3OPhXZ79Lnmw:-KF5ifu4I-zP-nLQ0wAF:562802545) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L433)):*
So I am dealing with the following

```
yu, _ := new(inf.Dec).Round(y, 0, inf.RoundDown).Unscaled()

bits := int64(x.UnscaledBig().BitLen() + int(digitsToBitsRatio)) // digitsToBitsRatio = 3
es := s + inf.Scale(int32(bits*yu))
```

es (new scale in one of my test cases x = "4.042131231" and y = "86.9627324951673"}} ends up being 3044
That seems waaaaaaaaaaaaay to big. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 433 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5WJTs3OPhXZ79Lnmw:-KF5lMASKsg58HoHNmVi:-319857440) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L433)):*
You are still adding `digitsToBitsRatio` which does not make sense. We want to convert between bits (base 2 digits) and (base 10) digits. We need to multiply the number of bits by `Log10(2)` to get the number of digits. So given that `digitsToBitsRatio is 1 / Log10(2)`, we need to divide by it.

After you do that, you have found the number of digits in x, but that includes the ones after the decimal point. So we need to subtract `x.Scale()` from the result (though make sure to check for underflow).

I am also not sure if the calculation of `yu` is ok, we are assuming that `new(inf.Dec).Round(y, 0, inf.RoundDown)` has scale 0 which I'm not sure is necessarily the case. Easy to verify if you print `y` and `yu` though.

For the example you quoted, we would need a scale of a bit above 70 to get results accurate to a scale of 16. The following calculation shows that`10^-70` error in that value results in a `10^-16` error in the final answer. Hit "more digits" here: https://www.wolframalpha.com/input/?i=4.042131231%5E86.9627324951673+-+e%5E((ln(4.042131231)+%2B+10%5E-70)+*+86.9627324951673)


If you don't get something close to that, please print out the values of `y`, `yu`, `BitLen()`, `x.Scale()` and post them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by seiflotfy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 433 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5WJTs3OPhXZ79Lnmw:-KF6Lrg3XC-td6jD5KJG:787197518) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L433)):*
So you are saying
```
digitsToBitsRatio = 1 / Log10(2)   // This is a constant?
```

which makes number of digits 
```
numBits = x.UnscaledBig().BitLen() * digitsToBitsRatio // Is that right?
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 433 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5WJTs3OPhXZ79Lnmw:-KF6NTHYn0CVjmsiJO5E:83769572) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L433)):*
Should be `numDigits = x.UnscaledBig().BitLen() / digitsToBitsRatio`. There's obviously more bits than digits no? E.g. 500 has 9 bits but 3 digits.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 448 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFBPM3jVtefiPA9Mham:-KFBPM3jVtefiPA9Mhan:-519322923) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4e072bbdb13ca102087fc343d8caaafd4e082f/util/decimal/decimal.go#L448)):*
We don't need to do "Dec" arithmetic on the number of bits, we can just use float.
`numDigits = int(float64(x.UnscaledBig().BitLen()) / digitsToBitsRatio))`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 448 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFBPM3jVtefiPA9Mham:-KFBQLa78abeiBAAdHK8:122667628) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4e072bbdb13ca102087fc343d8caaafd4e082f/util/decimal/decimal.go#L448)):*
or
```
numDigits = float64(x.UnscaledBig().BitLen()) / digitsToBitsRatio))
...
es := s + int32(yu * numDigits)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
The update looks good! I looked over the rest of the change and I have a few more comments.

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[util/decimal/decimal.go, line 427 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFid5auOXuLWI5-WSL:-KFFid5auOXuLWI5-WSM:-1535496212) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L427)):*
We should only do this if `neg` is true.

This doesn't work for large `x` (which is possible for small `y`). You should use `UnscaledBig()` and then `Rem()` or `Bit()`.

Finally, if `neg` is true and the power is not an integer, then we should have a predictable behavior (panic or return nil). This behavior should be specified in the function comment as well.

---

*[util/decimal/decimal.go, line 446 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFhwY3EDWC-7bP3ELM:-KFFhwY4UiBo4Tj-srLg:1318467663) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L446)):*
[nit] if you're not reusing the constant that's already defined somewhere, just do `* math.Log10(2)`

---

*[util/decimal/decimal.go, line 449 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFiCiQD73zKOgxRyH2:-KFFiCiQD73zKOgxRyH3:-2125273986) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L449)):*
calculating

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-:-KFFiJYOb0QLsIuze9tP:270012773)*

**Comment by seiflotfy** [comment]
@RaduBerinde is it good now?

**Comment by seiflotfy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[util/decimal/decimal.go, line 429 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF4QFpMgXGN4F2kRimS:-KFPGO4iEjENbZs-rC54:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1d61becee22c6b9915edd89222a9edcee64f6c6/util/decimal/decimal.go#L429)):*
Done.

---

*[util/decimal/decimal.go, line 430 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KF5W_PWLNgeLRpbkJ9c:-KFPGONf3RlGxv3oB37j:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/473695e8447d347a2c9d483271e8c8599b42937e/util/decimal/decimal.go#L430)):*
Done.

---

*[util/decimal/decimal.go, line 448 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFBPM3jVtefiPA9Mham:-KFPGP87Lw71Geprv3aC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4e072bbdb13ca102087fc343d8caaafd4e082f/util/decimal/decimal.go#L448)):*
Done.

---

*[util/decimal/decimal.go, line 427 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFid5auOXuLWI5-WSL:-KFPGQC5jgLaj8Uecf0S:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L427)):*
Done.

---

*[util/decimal/decimal.go, line 446 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFhwY3EDWC-7bP3ELM:-KFPGOwPp9-qvIgtpXZs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L446)):*
Done.

---

*[util/decimal/decimal.go, line 449 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFiCiQD73zKOgxRyH2:-KFPGOdCCyhaYwa3AGxi:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L449)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 427 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFid5auOXuLWI5-WSL:-KFPnXvnkCkOsPq-xqzl:-362826341) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L427)):*
The "large x" problem I mentioned still exists, you just moved it to line 464. If you are relying on the fact that `Int64()` will preserve the `%2` even if the number doesn't fit, please add a comment explaining that.

In any case, please add some tests with large x (larger than int64 can represent), both negative and positive, raised to a small power (e.g. 2 and 3). 

---

*[util/decimal/decimal.go, line 416 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFPmZA6IL8_fs__fe9R:-KFPmZA7ZGpj8hKAZwx4:-1653134259) ([raw file](https://github.com/cockroachdb/cockroach/blob/e421a2fd6ba1f13f4c903b6759ad3dbc238df48d/util/decimal/decimal.go#L416)):*
The comment you added is not accurate.

---

*[util/decimal/decimal.go, line 450 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFPmhEoL__GsQV92nN6:-KFPmhEoL__GsQV92nN7:1825637831) ([raw file](https://github.com/cockroachdb/cockroach/blob/e421a2fd6ba1f13f4c903b6759ad3dbc238df48d/util/decimal/decimal.go#L450)):*
the `int64()` isn't useful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 427 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFid5auOXuLWI5-WSL:-KFPvyeU5UsHbJgtT83k:-43179484) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L427)):*
I just tested with 9223372036854775807123 ^ 2 and it works.
You want me to replace the  new(inf.Dec).Round(x, 0, inf.RoundDown).Unscaled().Bit(0) 1 as a condition?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by seiflotfy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 450 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFPmhEoL__GsQV92nN6:-KFPt2LHPpiKsxFh-J6D:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e421a2fd6ba1f13f4c903b6759ad3dbc238df48d/util/decimal/decimal.go#L450)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/decimal.go, line 427 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFFid5auOXuLWI5-WSL:-KFQ0YhHmP1zFFuY1cWG:1388660184) ([raw file](https://github.com/cockroachdb/cockroach/blob/3211c4ad0dd5a5ac53096fd050fe86c6ffd2c531/util/decimal/decimal.go#L427)):*
Sure, that would be more clear!

---

*[util/decimal/decimal_test.go, line 452 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFQ0gr5i7qYGgnYTaK2:-KFQ0gr6h8zKD7DdsqCd:674477416) ([raw file](https://github.com/cockroachdb/cockroach/blob/938aa43bf61d8b1e760d83f366d2d885821d6668/util/decimal/decimal_test.go#L452)):*
can you also add the same test with negative base, and then the same pairs of tests with exponent "3" (just to verify the sign logic is correct)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by seiflotfy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/decimal/decimal.go, line 416 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFPmZA6IL8_fs__fe9R:-KFQ3ZaVVSEBanFciJ5a:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e421a2fd6ba1f13f4c903b6759ad3dbc238df48d/util/decimal/decimal.go#L416)):*
Done.

---

*[util/decimal/decimal_test.go, line 452 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-KFQ0gr5i7qYGgnYTaK2:-KFQ3YwG5Hf5wN8gW3SI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/938aa43bf61d8b1e760d83f366d2d885821d6668/util/decimal/decimal_test.go#L452)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972)*

**Comment by RaduBerinde** [comment]
Awesome! :lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5972#-:-KFQ5NizY9XK1dqs7fmG:-1097164489)*

**Pull request merged**
