### PR TITLE
ttljob: adjust logs; reset progress when resuming; add time-based limiter for progress updates

### PR DESCRIPTION
**Pull request by rafiss**
### ttljob: adjust fractionCompleted logs

This makes the logs added in 3cbe0b4b3f1 slightly more useful by adjusting the variable names, and showing the running count of number of spans processed.

### ttljob: reset progress when resuming job

The job starts from the beginning when it is paused/resumed, so we need
to update the fraction completed back to 0.

### ttljob: add time-based limiting for updating progress

There was a risk of a thundering herd of processors all updating progress in rapid
succession (which may happen if they all process spans that don't have any
rows to delete). This patch adds a check so that the progress is only
updated at most once every 60 seconds (with some added jitter).

informs: https://github.com/cockroachdb/cockroach/issues/86884
Release note: None

### CODE REVIEW

**Review by Dedej-Bergin — APPROVED** [review]
Nice
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135192#-:-OBfqLen9Ri2V0dMvIC1:bb70w76)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
Thanks for adding the rate limit!

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
