### PR TITLE
opt: separate pass-through columns in projections

### PR DESCRIPTION
**Pull request by RaduBerinde**
Previously, a project that just removes columns required VariableOps
to represent the projections. This change separates synthesized
columns from pass-through columns; these are now separate fields in
the ProjectionsOp private. We can now match "simple" projects using
`(Project * (Projections [])`.

Some optbuilder changes were required to only create groups for
columns when needed. Some exec improvements were necessary too: if we
have a simple projection on top of a renderNode, we now rearrange the
columns instead of creating a new node (this improvement is related to
this change because we can no longer control the projection order of
the passthrough columns).

The display of expressions is improved to omit projections with no
synthesized columns (as well as empty aggregations).

We also add expression check code that verifies we don't
pass through columns as VariableOps (this was very useful while
working on this change).

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:, with some small comments.

This looks like it was a lot of tedious work. Thanks for making the change. It will make `Project` easier to work with in the future.

A meta comment: it would have been good to put the `ExprView` change to omit projections in output in a separate commit, as it introduced so much "noise" that it's hard to see what else may have erroneously changed.

---

Review status: 0 of 86 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt_exec_engine.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL5XNuEdTukAGguj2t:-LCL5XNuEdTukAGguj2u:b-x82zwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt_exec_engine.go#L187)):*
> ```Go
> 	if r, ok := n.(*renderNode); ok {
> 		// If the top node is already a renderNode, just rearrange the columns.
> 		// TODO(radu): perhaps don't do this if cols have duplicates? (in case that
> ```

What about side-effecting expressions? We have to be careful not to compute the same column twice in those cases. I think we can't do this optimization if there are dups...

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL76b22XEzcivFqFQU:-LCL76b22XEzcivFqFQV:b-5kaww4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/logical_props_builder.go#L554)):*
> ```Go
> 
> 	// For a ProjectionsOp, the passthrough cols are also outer cols.
> 	if ev.Operator() == opt.ProjectionsOp {
> ```

NIT: Maybe move this up into the default case of the switch, since it's only applicable there.

---

*[pkg/sql/opt/memo/private_defs.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL7ThcAEah5dIhRNVb:-LCL7ThcAEah5dIhRNVc:bkejugm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/private_defs.go#L49)):*
> ```Go
> 	// the ProjectionsOp.
> 	SynthesizedCols opt.ColList
> 	// PassthroughCols are columns that are projected unchanged.
> ```

NIT: In all of my code files, I keep a blank space before comments that don't start a block.

---

*[pkg/sql/opt/memo/private_defs.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL7m7M8DVNtT3sLgOr:-LCL7m7M8DVNtT3sLgOs:bpch67h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/private_defs.go#L49)):*
> ```Go
> 	// the ProjectionsOp.
> 	SynthesizedCols opt.ColList
> 	// PassthroughCols are columns that are projected unchanged.
> ```

In comment, mention that pass-through column must come from input; it's not allowed to be an outer column reference. Outer column refs must be wrapped in `Variable` and included in the `SynthesizedCols` list.

Can you also add that comment to the `Project` operator definition in `scalar.opt`, since it's so important (we currently have bugs around this)?

---

*[pkg/sql/opt/memo/statistics_builder.go, line 640 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL8vxlEnWXSQI8bGjE:-LCL8vxlEnWXSQI8bGjF:bc01j2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/statistics_builder.go#L640)):*
> ```Go
> 	// higher scope (in the case of a correlated subquery), or they
> 	// may be synthesized by the projection operation.
> 	inputCols := sb.ev.Child(0).Logical().Relational.OutputCols
> ```

NIT: Maybe we should rename this to match the new terminology:
  `reqOtherCols` => `reqSynthCols`

---

*[pkg/sql/opt/norm/prune_cols.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLF2QX-WECsdYfEpDf:-LCLF2QX-WECsdYfEpDg:bfohh4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/norm/prune_cols.go#L102)):*
> ```Go
> 
> 	case opt.AggregationsOp:
> 		groups, cols := filterColList(
> ```

`filterColList` cleaned this code up nicely. Good idea.

---

*[pkg/sql/opt/ops/scalar.opt, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLGTiE5poy60B-74nP:-LCLGTiE5poy60B-74nQ:b-vk19rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/ops/scalar.opt#L126)):*
> ```
> # The private Defs field contains the list of column indexes returned by each
> # expression, and a list of pass-through columns. Elems cannot contain a simple
> # VariableOp - these would be pass-through columns.
> ```

NIT: It's OK to have VariableOp if the column's ID is being remapped, such as in the case of an outer column ref.

---

*[pkg/sql/opt/optbuilder/project.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLHluH9UfBGmO5ekDL:-LCLHluH9UfBGmO5ekDM:b-crolx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/optbuilder/project.go#L142)):*
> ```Go
> 
> // passthroughColumn adds (to the output scope) a column that is available in
> // the input scope.
> ```

NIT: Maybe mention here that `group` is set to 0 for passthrough cols.

---

*[pkg/sql/opt/optbuilder/scalar.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLI0RT1N0t9xXBLqgs:-LCLI0RT1N0t9xXBLqgt:b-sc0ddm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/optbuilder/scalar.go#L205)):*
> ```Go
> 
> 	case *tree.FuncExpr:
> 		group, col := b.buildFunction(t, "", inScope)
> ```

NIT: can you add a comment giving an example of when group=0 is returned?

---

*[pkg/sql/opt/optbuilder/scope.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLIEgjDlkV5ZKAfCIh:-LCLIEgjDlkV5ZKAfCIi:b-6y20w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/optbuilder/scope.go#L96)):*
> ```Go
> 	s.cols = append(s.cols, *col)
> 	newCol := &s.cols[len(s.cols)-1]
> 	// We want to reset the group, as this becomes a pass-through column in the
> ```

Doesn't `append` already set all newly appended memory to 0? Using the word `reset` makes it sound like it might be something other than 0 to begin with. Isn't this just `set` rather than `reset`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-:-LCLJ2Gh15b_74ssF_KB:bb0i6b2)*

**Comment by RaduBerinde** [comment]
TFTR!

Good idea - I added a "prequel" commit that does the similar formatting change. The diff in the second commit is indeed more manageable - I actually noticed a bug in an inlining rule (fixed in hasDuplicateRefs).

---

Review status: 0 of 86 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/opt_exec_engine.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL5XNuEdTukAGguj2t:-LCLpUM-93s59RTQxlu2:b-lnbqod) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt_exec_engine.go#L187)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What about side-effecting expressions? We have to be careful not to compute the same column twice in those cases. I think we can't do this optimization if there are dups...
</blockquote></details>

Added a check for duplicate cols.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL76b22XEzcivFqFQU:-LCLpq6x0ExI0Pg1XlLc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/logical_props_builder.go#L554)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Maybe move this up into the default case of the switch, since it's only applicable there.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_defs.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL7ThcAEah5dIhRNVb:-LCLpu6t7yVIfINPL1Dr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/private_defs.go#L49)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: In all of my code files, I keep a blank space before comments that don't start a block.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_defs.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL7m7M8DVNtT3sLgOr:-LCLvU9a3NgYj0EYZP_G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/private_defs.go#L49)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In comment, mention that pass-through column must come from input; it's not allowed to be an outer column reference. Outer column refs must be wrapped in `Variable` and included in the `SynthesizedCols` list.

Can you also add that comment to the `Project` operator definition in `scalar.opt`, since it's so important (we currently have bugs around this)?
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 640 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCL8vxlEnWXSQI8bGjE:-LCLvODx6dT6Yqqw8Pvz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/memo/statistics_builder.go#L640)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Maybe we should rename this to match the new terminology:
  `reqOtherCols` => `reqSynthCols`
</blockquote></details>

Done.

---

*[pkg/sql/opt/ops/scalar.opt, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLGTiE5poy60B-74nP:-LCLuvVU3oFoWN-UdmtK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/ops/scalar.opt#L126)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: It's OK to have VariableOp if the column's ID is being remapped, such as in the case of an outer column ref.
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/project.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLHluH9UfBGmO5ekDL:-LCLrFILBQrKk7Mj3KbX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/optbuilder/project.go#L142)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Maybe mention here that `group` is set to 0 for passthrough cols.
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/scalar.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLI0RT1N0t9xXBLqgs:-LCLsqR637CsBvPf82Io:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/optbuilder/scalar.go#L205)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: can you add a comment giving an example of when group=0 is returned?
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/scope.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCLIEgjDlkV5ZKAfCIh:-LCLssI5Ar_DPcyLg0xq:b-trgolz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff4a0d78881a63c5e3333f5cf3fa36c49205afb6/pkg/sql/opt/optbuilder/scope.go#L96)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Doesn't `append` already set all newly appended memory to 0? Using the word `reset` makes it sound like it might be something other than 0 to begin with. Isn't this just `set` rather than `reset`?
</blockquote></details>

We append the contents of `*col`, with whatever `col.group` it has set.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-:-LCLvxg5Df9fLB3afPgE:b-wff27o)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 86 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-:-LCUxFQo7dVgJILQaaHG:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm_strong: nice changes!

---

Reviewed 32 of 86 files at r1, 54 of 54 files at r2, 53 of 53 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/opt_exec_engine.go, line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCVGVm7ALtDtOG7cnyb:-LCVGVm7ALtDtOG7cnyc:b-vfgo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b571864410f74bbc74b2f7dbc30c219ea4c12e/pkg/sql/opt_exec_engine.go#L188)):*
> ```Go
> 	// If the top node is already a renderNode, just rearrange the columns.  But
> 	// check for duplicates - we don't want to duplicate a rendering expressions
> 	// (in case it is expensive to compute or has side-effects).
> ```

It would be helpful to explain here why the code below this block handles duplicates correctly.

---

*[pkg/sql/opt/memo/testdata/memo, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCVVNwLEmwv71W1N_gJ:-LCVVNwLEmwv71W1N_gK:b5nv07n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f231227c6dddd54e05f5a277edda5290dee56cf/pkg/sql/opt/memo/testdata/memo#L140)):*
> ```
>  │         ├── best: (limit G4="[ordering: +2]" G5 +2)
>  │         └── cost: 2026.65
>  ├── G3: (projections G16 G14 G6)
> ```

How hard would it be to include these columns? Seems like it's better to include them if possible...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-:-LCVfwE6-3r_dBgLn7XH:bt8zwum)*

**Comment by RaduBerinde** [comment]
TFTRs! I rebased and fixed up some conflicts with Andy's recent PR.

---

Review status: 8 of 88 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt_exec_engine.go, line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCVGVm7ALtDtOG7cnyb:-LCWBR9n8UFeNAnpAuFu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b571864410f74bbc74b2f7dbc30c219ea4c12e/pkg/sql/opt_exec_engine.go#L188)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It would be helpful to explain here why the code below this block handles duplicates correctly.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/testdata/memo, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-LCVVNwLEmwv71W1N_gJ:-LCWFQRPD_MguHn77N_S:b-g5w2rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f231227c6dddd54e05f5a277edda5290dee56cf/pkg/sql/opt/memo/testdata/memo#L140)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

How hard would it be to include these columns? Seems like it's better to include them if possible...
</blockquote></details>

Included them by name. Had to add a flag to `formatPrivate`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-:-LCWlWoj3m4luKF_fVEj:b-txa0uq)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 25 of 79 files at r4, 55 of 55 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25446#-:-LCYnn_o3k5la7c2tidX:bnfp4nl)*

**Pull request merged**
