### PR TITLE
opt: Allow cyclical normalization rules

### PR DESCRIPTION
**Pull request by andy-kimball**
We have existing patterns that remove unneeded columns from Select, Limit
and Offset operator inputs by creating a Project wrapper that eliminates
those columns. However, we'd also like to push the Select, Limit, and
Offset operators into Project, since the lower we can push them in the
expression tree, the better. Having rules that accomplish both of these
goals results in a dependency cycle. Before this PR, that would result in
an infinite rule application loop as Select pushed into Project, Project
pushed into Select, and so on.

This PR adds support for a new DetectCycle tag. Optgen will generate a
bit of extra code for rules that have this tag. When an expression matches
the rule, its fingerprint is added into a new ruleCycles map. If the
replacement pattern recursively invokes the same rule, then the new code
will see that the fingerprint is already in the map, and will skip the
rule, thus breaking the cycle.

The PR also adds new rules which use this new feature:
  - PushSelectIntoProject
  - PushLimitIntoProject
  - PushOffsetIntoProject

This sets us up to be able to add more rules that attempt to push the
Limit/Offset operators as far down the tree as possible.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Cool stuff! :lgtm: 

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 100 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rBVhM7qUfOT_3DiHV:-L8rBVhM7qUfOT_3DiHW:buawykc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/memo/constraint_builder.go#L100)):*
> ```Go
> 	switch ev.Operator() {
> 	case opt.AndOp, opt.FiltersOp:
> 		if ev.ChildCount() > 0 {
> ```

[nit] I would add a comment explaining that we might have 0 children if this is not a fully normalized expression (e.g. when using `optsteps`).

---

*[pkg/sql/opt/memo/memo.go, line 179 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rBwsB8h27MqwtqkWg:-L8rBwsB8h27MqwtqkWh:b521fjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/memo/memo.go#L179)):*
> ```Go
> func (m *Memo) AddAltFingerprint(alt Fingerprint, group GroupID) {
> 	_, ok := m.exprMap[alt]
> 	if !ok {
> ```

How does it work when the fingerprint was already mapped to a different group? What do we want GroupByFingerprint to return in that case?

---

*[pkg/sql/opt/norm/factory.go, line 557 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rF7-GEaaznbK7KFyM:-L8rF7-GEaaznbK7KFyN:b-h60gpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/norm/factory.go#L557)):*
> ```Go
> }
> 
> // limitNoCycle is similar to projectNoCycle, except that it constructs a Limit
> ```

offsetNoCycle, constructs an Offset operator

---

*[pkg/sql/opt/norm/rules/limit.opt, line 38 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rCmDT0-GImZu6_5nq:-L8rCmDT0-GImZu6_5nr:b-z3z9jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/norm/rules/limit.opt#L38)):*
> ```
> (Offset
>     (Project $input:* $projections:*)
>     $limit:*
> ```

[nit] $offset

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-:-L8rFx-K3ZuRuz50-gPf:b-gmed4d)*

**Comment by andy-kimball** [comment]
Review status: 0 of 18 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 100 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rBVhM7qUfOT_3DiHV:-L8reU3U76dDSsJcTTHg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/memo/constraint_builder.go#L100)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would add a comment explaining that we might have 0 children if this is not a fully normalized expression (e.g. when using `optsteps`).
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/memo.go, line 179 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rBwsB8h27MqwtqkWg:-L8reVL19P8Jhegzxnlm:b-30n1q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/memo/memo.go#L179)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How does it work when the fingerprint was already mapped to a different group? What do we want GroupByFingerprint to return in that case?
</blockquote></details>

The trouble I ran into was that with cycles + optsteps, there are cases where the assert is incorrect. The same fingerprint can end up pointing to two different groups because one is pointing to the normalized group and the other is pointing to a denormalized group that couldn't be normalized because optsteps stopped it.

I thought about this more, and I can make a different change that preserves the assert. For rules with the DetectCycle tag, I can generate an extra check to see whether a recursive invocation has already mapped the fingerprint to a group, and if so I skip calling AddAltFingerprint.

---

*[pkg/sql/opt/norm/factory.go, line 557 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rF7-GEaaznbK7KFyM:-L8s0Xy3CTfd8uKEryY7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/norm/factory.go#L557)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

offsetNoCycle, constructs an Offset operator
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/limit.opt, line 38 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rCmDT0-GImZu6_5nq:-L8s0dGB3C3fgPaNwUCR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/norm/rules/limit.opt#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] $offset
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 11 of 18 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/factory.go, line 78 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8sY38v2nnhzYiuE1U2:-L8sY38v2nnhzYiuE1U3:bhjdkho) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/factory.go#L78)):*
> ```Go
> 	// same fingerprint, then the rule sees that the fingerprint is already in the
> 	// map, and will skip application of the rule.
> 	ruleCycles map[memo.Fingerprint]bool
> ```

[nit] is the bool always true? If so, you could just store an empty struct...

---

*[pkg/sql/opt/norm/factory.go, line 361 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8sXJaX2zT4nHV22WO_:-L8sXJaX2zT4nHV22WOa:b-ntef1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/factory.go#L361)):*
> ```Go
> // hasSubsetCols returns true if the left group's output columns are a subset of
> // the right group's output columns.
> func (f *Factory) hasSubsetCols(left, right memo.GroupID) bool {
> ```

[nit] maybe "colsSubsetOf" would be a slightly clearer name? I don't feel strongly though...

---

*[pkg/sql/opt/norm/rules/project.opt, line 65 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8s_6Tx2lD92MsZ-PC4:-L8s_6Tx2lD92MsZ-PC5:b-1bfjae) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/rules/project.opt#L65)):*
> ```
> # This rule triggers a cycle with the PushSelectIntoProject rule. By tagging
> # this rule (instead of the other) with the DetectCycle tag, the cycle is broken
> # by choosing the (Project (Select)) order rather than the (Select (Project))
> ```

This is a bit confusing because the other rule has an outer Select, and this rule has an outer Project.....

---

*[pkg/sql/opt/norm/testdata/test, line 1 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8seQZZAlhZPTwJnMrZ:-L8seQZZAlhZPTwJnMr_:b-1r4g6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/testdata/test#L1)):*
> ```
> exec-ddl
> ```

What is the purpose of this file?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-:-L8shQGmEtdNvQ7BiZuk:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/memo.go, line 179 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8rBwsB8h27MqwtqkWg:-L8sl0a4Af6AJso5VBus:bdddnqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bff9f349678e97f94c30503d91ae5679b677d1d/pkg/sql/opt/memo/memo.go#L179)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The trouble I ran into was that with cycles + optsteps, there are cases where the assert is incorrect. The same fingerprint can end up pointing to two different groups because one is pointing to the normalized group and the other is pointing to a denormalized group that couldn't be normalized because optsteps stopped it.

I thought about this more, and I can make a different change that preserves the assert. For rules with the DetectCycle tag, I can generate an extra check to see whether a recursive invocation has already mapped the fingerprint to a group, and if so I skip calling AddAltFingerprint.
</blockquote></details>

Nice solution! LGTM

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/factory.go, line 78 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8sY38v2nnhzYiuE1U2:-L8smxdu0cvchDmchn01:biyzzhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/factory.go#L78)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] is the bool always true? If so, you could just store an empty struct...
</blockquote></details>

Yes, it's always true, but I like being able to test whether an is present like this: `if _f.ruleCycles[...] {`, so I deliberately used `bool`.

---

*[pkg/sql/opt/norm/factory.go, line 361 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8sXJaX2zT4nHV22WO_:-L8snfoQCeNZaxJMf83i:bq5fj10) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/factory.go#L361)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] maybe "colsSubsetOf" would be a slightly clearer name? I don't feel strongly though...
</blockquote></details>

`hasSubsetCols` isn't the perfect name, but I do like the symmetry with `hasSameCols`.

---

*[pkg/sql/opt/norm/rules/project.opt, line 65 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8s_6Tx2lD92MsZ-PC4:-L8soQ1Y1rhkPL7-2XL4:b-zijxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/rules/project.opt#L65)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a bit confusing because the other rule has an outer Select, and this rule has an outer Project.....
</blockquote></details>

I'll reword the comment a bit:
```
# This rule triggers a cycle with the PushSelectIntoProject rule. Because this
# rule has the DetectCycle tag, it is skipped once a cycle is detected. This
# gives the PushSelectIntoProject rule one last chance to push Select below
# Project, and therefore causes the normal form to be (Project (Select)) rather
# than (Select (Project)) when the choice is ambiguous. This and other rules
# will try to push Project down as far as possible, but if it gets stopped along
# the way, it will be ordered above Select.
```

---

*[pkg/sql/opt/norm/testdata/test, line 1 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8seQZZAlhZPTwJnMrZ:-L8stxwKC3FvHuqh6xjq:b-8jwkqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/testdata/test#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What is the purpose of this file?
</blockquote></details>

Oh, i meant to delete this. I use a dummy "test" file when I want to zero in on one test case during debugging.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356)*

**Comment by rytaft** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/factory.go, line 78 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8sY38v2nnhzYiuE1U2:-L8tEYHl6TY89iKed4n5:b-4fpask) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/factory.go#L78)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yes, it's always true, but I like being able to test whether an is present like this: `if _f.ruleCycles[...] {`, so I deliberately used `bool`.
</blockquote></details>

Just a drive-by, but as far as I know using the empty struct lets the map avoid storing the values which translates to lower memory usage. Not sure if this is relevant here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356)*

**Comment by andy-kimball** [comment]
*[pkg/sql/opt/norm/factory.go, line 78 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356#-L8sY38v2nnhzYiuE1U2:-L8tGwWt9fSqbW4Rds6p:b-mj2hm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e1c4267c9b4046c1c15455d673473ad217e5d5c/pkg/sql/opt/norm/factory.go#L78)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Just a drive-by, but as far as I know using the empty struct lets the map avoid storing the values which translates to lower memory usage. Not sure if this is relevant here.
</blockquote></details>

Good to know. In this case, it won't matter, since this map will be tiny, often only containing 1 or 2 entries.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24356)*

**Pull request merged**
