### PR TITLE
sql: support SQL parse dollar-quoted strings with digit

### LINKED ISSUE #54676: SQL parse fails on dollar-quoted strings with digits in their delimiters
**Describe the problem**

This is only an issue for delimiters with digits.

Minimal repro:
```
SELECT $foo1$foo$foo1$;
ERROR:  at or near "$": syntax error
DETAIL:  source SQL:
SELECT $foo1$foo$foo1$;
       ^
HINT:  try \h SELECT
```

**Expected behavior**
This should return the string `foo`.

### PR DESCRIPTION
**Pull request by adzimzf**
Support SQL parse dollar-quoted strings with digit

Fixes #54676.

Release note (sql change): support SQL parse dollar-quoted strings with digit.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
Thanks for the contribution! One minor improvement and then it should be good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55958#-:-MKaASSn8t3Y-NFOSg-Z:b-3oq9y5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adzimzf and @solongordon)

___
*[pkg/sql/parser/scan.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55958#-MKaADKqC3xQUTaAdSYA:-MKaADKqC3xQUTaAdSYB:bsxh99c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e341f4ba46494f1738feacf2633156d6d820ad/pkg/sql/parser/scan.go#L946)):*
> ```Go
> 		default:
> 			// If we haven't found a start tag yet, check whether the current characters is a valid for a tag.
> 			if !foundStartTag && !lex.IsIdentStart(ch) && !(ch >= '0' && ch <= '9') {
> ```

As @yasoobh pointed out you can use `IsDigit` here instead. Or perhaps even better would be to just replace `IsIdentStart` with `IsIdentMiddle`.

**Comment by adzimzf** [comment]
Hi @solongordon I have an update

**Comment by yasoobh** [comment]
Hi. I think there is a minor problem with using IsIdentMiddle as it allows for '$' as well, while it is not allowed according to PostgreSQL doc. It won't break anything though, as whenever we have a '$' char, code execution will not come to default case.

https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

> The tag, if any, of a dollar-quoted string follows the same rules as an unquoted identifier, except that it cannot contain a dollar sign. Tags are case sensitive, so $tag$String content$tag$ is correct, but $TAG$String content$tag$ is not.

**Comment by adzimzf** [comment]
> Hi. I think there is a minor problem with using IsIdentMiddle as it allows for '$' as well, while it is not allowed according to PostgreSQL doc. It won't break anything though, as whenever we have a '$' char, code execution will not come to default case.
> 
> https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING
> 
> > The tag, if any, of a dollar-quoted string follows the same rules as an unquoted identifier, except that it cannot contain a dollar sign. Tags are case sensitive, so $tag$String content$tag$ is correct, but $TAG$String content$tag$ is not.

okay, do u prefer using `IsIdentStart(ch) || IsDigit(ch) ` so the `$` is excluded?

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55958#-:-MKjYuDOADtVhCE-t2R8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adzimzf and @solongordon)

**Comment by solongordon** [comment]
Thanks for the contribution!

bors r+

**Pull request merged**
