### PR TITLE
roachpb: Convert proto slices of pointers to slices of values

### PR DESCRIPTION
**Pull request by nvb**
This PR converts a few slices of pointers to slices of values to avoid
unnecessary allocations when populating the slices. This is accomplished
by making repeated proto fields non-nullable.

Fields changed:
- `RaftSnapshotData.KV`
- `InternalTimeSeriesData.Samples`

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5026)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[roachpb/internal.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5026#-KCRoo3ITrP8lyWoTegE:-KCRoo3ITrP8lyWoTegF:1830147516) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c7dac348d3e8ad416f494c87394e72af778473/roachpb/internal.go#L38)):*
Should that be `Max != nil`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5026#-:-KCRowAgonxL-RORnwm9:1417088721)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5026#-:-KCRz4iEVHP67Wf1uTJn:676834233)*

**Comment by tamird** [comment]
LGTM although "roachpb:" in the commit message isn't totally right.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5026#-:-KCS0k7e4zqHNFTUuotw:210192660)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/internal.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5026#-KCRoo3ITrP8lyWoTegE:-KCRplLFfDIZwz8eBIVk:2017371671) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c7dac348d3e8ad416f494c87394e72af778473/roachpb/internal.go#L38)):*
Looks like it. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5026)*

**Pull request merged**
