### PR TITLE
storage: crash a node if the ingestion fails in an unexpected way

### LINKED ISSUE #24971: storage: useless code in pkg/storage/replica_proposal.go
In pkg/storage/replica_proposal.go, there is the following code:
```go
if _, err := os.Stat(path); err == nil {
  // If the fs supports it, make a hard-link for rocks to ingest. We cannot
  // pass it the path in the sideload store as it deletes the passed path on
  // success.
  if linkErr := os.Link(path, ingestPath); linkErr == nil {
    ingestErr := eng.IngestExternalFiles(ctx, []string{ingestPath}, noModify)
    if ingestErr == nil {
      // Adding without modification succeeded, no copy necessary.
      log.Eventf(ctx, "ingested SSTable at index %d, term %d: %s", index, term, ingestPath)
      return false
    }
    if rmErr := os.Remove(ingestPath); rmErr != nil {
      log.Fatalf(ctx, "failed to move ingest sst: %v", rmErr)
    }
    const seqNoMsg = "Global seqno is required, but disabled"
    if err, ok := err.(*engine.RocksDBError); ok && !strings.Contains(err.Error(), seqNoMsg) {
      log.Fatalf(ctx, "while ingesting %s: %s", ingestPath, err)
    }
  }
}
```
If ` err == nil` is `true`, `err, ok := err.(*engine.RocksDBError)` always set `ok` to `false`. So I think that the code starting from `const seqNoMsg = "Global seqno is required, but disabled"` should be deleted.

### PR DESCRIPTION
**Pull request by yaojingguo**
Fixes #24971

Release note: None

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM, thanks again @yaojingguo. For future changes, it'd be nice if the commit message referred to the high-level behavior change (in this case about crashing when `AddSSTable` fails in an unexpected way), rather than just saying a variable was renamed.

cc @tschottdorf @dt - think this should be cherry-picked to 2.0? Without the fix we won't crash if the ingest fails in an unexpected way.

**Comment by yaojingguo** [comment]
@a-robinson Thanks for the review. I have updated the commit message. Please have another look.

**Comment by dt** [comment]
Nice catch, thanks @yaojingguo!

@a-robinson yep, we should cherrypick it, though maybe let it bake on master for a bit first?

**Pull request merged**
