### PR TITLE
opt: process FKs in test catalog

### PR DESCRIPTION
**Pull request by RaduBerinde**
The test catalog currently ignores foreign keys. This is a problem
because FKs sometimes result in automatic indexes being created, so
our tests can be missing indexes that would exist in a real setting
(e.g. see TPC-H).

This change adds code to resolve FKs and add indexes as necessary.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29415#-:-LLCkjI36TR7Z0Wxqsno:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29415#-LLChoyK558_B4GFp-0Y:-LLChoyK558_B4GFp-0Z:b-rqhwuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5856194d1d857a876ee04c671fcd329214c2b89d/pkg/sql/opt/testutils/testcat/create_table.go#L152)):*
> ```Go
> 	}
> 
> 	// Foreign key require indexes in both tables:
> ```

[nit] key -> keys
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29415#-LLCi88sCEVDUwrPiuGn:-LLCi88sCEVDUwrPiuGo:b4qdcb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5856194d1d857a876ee04c671fcd329214c2b89d/pkg/sql/opt/testutils/testcat/create_table.go#L162)):*
> ```Go
> 	//     target table requires looking up whether there would be orphan values
> 	//     left in the source table. This index needs not be unique; in fact, if an
> 	//     existing index as the relevant columns as a prefix, that is good enough.
> ```

[nit] needs not be unique -> need not be unique
[nit] if an existing index as -> if an existing index has

**Comment by justinj** [comment]
LGTM mod Rebecca's comments

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29415#-:-LLFsruO7Oalm3-MS10n:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29415#-LLChoyK558_B4GFp-0Y:-LLFsTPX8PX8xm9YHllU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5856194d1d857a876ee04c671fcd329214c2b89d/pkg/sql/opt/testutils/testcat/create_table.go#L152)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] key -> keys
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29415#-LLCi88sCEVDUwrPiuGn:-LLFsY_08jwec27qgw2B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5856194d1d857a876ee04c671fcd329214c2b89d/pkg/sql/opt/testutils/testcat/create_table.go#L162)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] needs not be unique -> need not be unique
[nit] if an existing index as -> if an existing index has
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
Made a fix to the auto index name, it is now consistent with what we see in practice.

**Pull request merged**
