### PR TITLE
sql: pool distsql receivers

### PR DESCRIPTION
**Pull request by jordanlewis**
```
name                           old time/op    new time/op    delta
FlowSetup/distribute=false-24    15.6µs ± 1%    15.4µs ± 1%  -1.06%
(p=0.002 n=8+10)

name                           old alloc/op   new alloc/op   delta
FlowSetup/distribute=false-24    27.4kB ± 0%    26.8kB ± 0%  -2.49%
(p=0.000 n=10+10)

name                           old allocs/op  new allocs/op  delta
FlowSetup/distribute=false-24       250 ± 0%       248 ± 0%  -0.44%
(p=0.001 n=10+10)
```

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30881#-:-LNvolvK440Of6ZwBNUa:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
this probably needs a backport

**Comment by jordanlewis** [comment]
All of these pooling PRs are intentionally not getting backported. I'm nervous about them introducing bugs so late in the cycle.

**Pull request merged**
