### PR TITLE
raft: document/test invariants in unstable

### PR DESCRIPTION
**Pull request by pav-kv**
This PR documents and tests invariants in the `unstable` log structure. Most importantly, the clean-up straightens up the order of handling `snapshot` and `entries` when both are present.

When `unstable` contains both the `snapshot`, and the `entries`, entries start at `snapshot.index + 1`. Both are sent to storage as one `MsgStorageAppend`. When a `MsgStorageAppendResp` arrives, we should acknowledge the snapshot first. If we, instead, acknowledge entries first, it briefly introduces a gap between the `snapshot` and `entries`, and then it's hard to reason about what this means. Fortunately, the code was calling both `stableSnapTo` and `stableTo`, so the invariant was de facto maintained (but non-atomically).

Epic: none
Release note: none

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126250#-:-O0MKnzZBAOcRqvaVHbC:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/log_unstable.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126250#-O0MKNkqAmhxYHoQCW06:-O0MKNkrBgUH1l_tZNa6:b-kltzow) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79626b7c21e151e7165a6c7a9119941602e3daf/pkg/raft/log_unstable.go#L170)):*
> ```Go
> 		return
> 	}
> 	if u.snapshot != nil && u.snapshotInProgress {
> ```

Is this just `if u.snapshotInProgress {`? `u.snapshotInProgress => u.snapshot != nil`, which is another invariant we could mention above and enforce.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126250)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/log_unstable.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126250#-O0MKNkqAmhxYHoQCW06:-O0O2E-0EKGMd1J-tKJ8:b-n2vfas) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79626b7c21e151e7165a6c7a9119941602e3daf/pkg/raft/log_unstable.go#L170)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this just `if u.snapshotInProgress {`? `u.snapshotInProgress => u.snapshot != nil`, which is another invariant we could mention above and enforce.
</blockquote></details>

Yes. Will make the notes. Just wanted to make it safe against a nil panic on `*u.snapshot`.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126250)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/log_unstable.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126250#-O0MKNkqAmhxYHoQCW06:-O0O77pT7nUW-eQfslMR:b1zdf6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79626b7c21e151e7165a6c7a9119941602e3daf/pkg/raft/log_unstable.go#L170)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Yes. Will make the notes. Just wanted to make it safe against a nil panic on `*u.snapshot`.
</blockquote></details>

Actually, this should be just `if u.snapshot != nil` (whether it progress or not). Done.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126250)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/log_unstable.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126250#-O0MKNkqAmhxYHoQCW06:-O0OEUfJ0z6Pt3qpUFnd:bxw1qvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79626b7c21e151e7165a6c7a9119941602e3daf/pkg/raft/log_unstable.go#L170)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Actually, this should be just `if u.snapshot != nil` (whether it progress or not). Done.
</blockquote></details>

`snapshotInProgress => snapshot != nil` is the same invariant as `snapshot == nil => !snapshotInProgress`. But there is no harm in mentioning both writings. Done.

**Comment by pav-kv** [comment]
bors r=nvanbenschoten

**Pull request merged**
