### PR TITLE
util/interval: generate type-safe specializations of interval B-tree

### PR DESCRIPTION
**Pull request by nvb**
See #43740.

This PR pulls the existing immutable interval B-Tree structure out of the
spanlatch package and into a utility library.

In order to avoid a loss of both type safety and performance, it opts for
code generation by using https://github.com/mmatczuk/go_generics. The new
util library exposes a script that is meant to be invoked by go generate
to create specializations of the ordered tree structure for individual
use cases. This ensures that each use can achieve the performance of being
hand-written without needing to continue the pattern of copying the btree
code and manually modifying it each time we want to use it.

cc. @petermattis @sumeerbhola I'm curious to get your thoughts on this experiment.
I'm hoping this also unblocks @sumeerbhola on #43740.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
This is fairly neat. Not very intrusive and the generated code is perfectly readable. I have no objections to this approach if you can define the generic type appropriately for the lock table use case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-:-LyFpAvU9nISrzmkcagt:bra2hgg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/interval/generic/internal/contract.go, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyFnqfY-492A0BjwMfC:-LyFnqfY-492A0BjwMfD:b-ewluza) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/contract.go#L14)):*
> ```Go
> 
> // T is a Template type. The methods in the interface make up its contract.
> type T = interface {
> ```

What is this about? I didn't see mention of it in the go_generics readme. That documentation is admittedly sparse.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/interval/generic/internal/contract.go, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyFnqfY-492A0BjwMfC:-LyFtWjSAl021unyBW-0:b-n8xlnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/contract.go#L14)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What is this about? I didn't see mention of it in the go_generics readme. That documentation is admittedly sparse. 
</blockquote></details>

Oh, I see that this is just the type being replaced. What through me is the `type T =`. I see other examples of `go_generics` which use `type T interface`. Are both styles supported?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/util/interval/generic/internal/contract.go, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyFnqfY-492A0BjwMfC:-LyGIUxq5LjUGO1xpHzh:b-jkovmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/contract.go#L14)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Oh, I see that this is just the type being replaced. What through me is the `type T =`. I see other examples of `go_generics` which use `type T interface`. Are both styles supported?
</blockquote></details>

Yes, the `type T` is replaced. I'm not sure what the difference between the type alias and the type definition is. https://github.com/scylladb/go-set uses the former and https://github.com/mmatczuk/go_generics uses the latter in its tests. Based on the code in the generator itself, it doesn't look like there's a difference in how they're handled - either way, they're [removed from the resulting AST]( https://github.com/mmatczuk/go_generics/blob/0aaa050f9bab8160cf684130d0afa69ff582cbe6/cmd/go_generics/remove.go#L84).

The interface serves two purposes: to specify a contract for the parameterized type and allow the templated go files to compile.

**Review by sumeerbhola — APPROVED** [review]
Looks great. Thanks.

> Reviewed 14 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-:-LyULjz24G_bnPlz99oq:bcg1puf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/util/interval/generic/doc.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyU9mNr0BXvLRmne4Xg:-LyU9mNr0BXvLRmne4Xh:b11kyhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/doc.go#L27)):*
> ```Go
>   3. Include a go generate declaration that invokes the gen.sh script with the
>      type name as the first argument and the package name as the second argument.
>   4. Invoke go gnerate.
> ```

nit: generate
___
*[pkg/util/interval/generic/internal/contract.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyULK5b3crYghw3ZoIw:-LyULK5b3crYghw3ZoIx:b8k1ne1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/contract.go#L21)):*
> ```Go
> 	SetID(uint64)
> 	SetKey([]byte)
> 	SetEndKey([]byte)
> ```

why does the btree implementation need the `Set*` methods? And I don't see the code in `example_interval_btree.go` calling the `Set*` methods.

Ah, I now see it is needed by the test. Can you add a comment here?
___
*[pkg/util/interval/generic/internal/interval_btree.tmpl.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyUIgL9AXOFHYBpmoix:-LyUIgL9AXOFHYBpmoiy:bxwn5wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/interval_btree.tmpl.go#L166)):*
> ```Go
> }
> 
> // incRef acquires a reference to the node.
> ```

I have a hard time understanding the ref counting happening in this file and reasoning about its correctness.
A snapshot of the tree only increments the ref count on the root node. And the snapshot happens before insertion of the latches. So presumably the root has a refcount of at least 2 (if the baseline is a refcount of 1). Then the insertion needs a mutable root node which must mean a copy is made of the root, and this copy increments the refs of its children, but not a recursive increment. But `mut()` also does a recursive decrement -- why (when were these recursive refs acquired)? I am assuming that `mut()` acquiring refs on its children is what ensures that whatever path the insert takes will see a node that does not have a ref count of 1 and so have to make a copy, while the paths not taken don't need a recursive refcount increment -- so a refcount of > 1 at a node also protects its subtree.

Could you add a high-level comment somewhere in this file?

**Review by nvb — COMMENTED** [review]
Thanks for taking a look. I still need to make a few tweaks here to get it passing all lint checks. I'll ping the PR when that's done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-:-Ly_o4GZ8TGxkDm55MJN:b-p5hk3f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

___
*[pkg/util/interval/generic/doc.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyU9mNr0BXvLRmne4Xg:-Ly_fFCEC95lpBj9qknL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/doc.go#L27)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: generate
</blockquote></details>

Done.
___
*[pkg/util/interval/generic/internal/contract.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyULK5b3crYghw3ZoIw:-Ly_fTqTAc67E6JKDZMd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/contract.go#L21)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why does the btree implementation need the `Set*` methods? And I don't see the code in `example_interval_btree.go` calling the `Set*` methods.

Ah, I now see it is needed by the test. Can you add a comment here?
</blockquote></details>

Done.
___
*[pkg/util/interval/generic/internal/interval_btree.tmpl.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyUIgL9AXOFHYBpmoix:-Ly_l60XAB7pK2wMxXgF:b-iy5hjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/interval_btree.tmpl.go#L166)):*
Your understanding sounds almost exactly correct. The one thing that it sounds like you're still unsure about is why `mut()` does a recursive decrement on the cloned node's refcount. On the path that you're referencing, `mut()` is performing a clone so that it can write. Because `mut()` is cloning a node, it can release it's reference to the old node. _If_ this is the final reference to the old node, which is only possible if we're racing with another call to `decRef` (I added a comment), then that should recursively release references on the children it points to and be recycled.

> Could you add a high-level comment somewhere in this file?

I added the following comment to `btree.Clone`:

```
Incrementing the reference count on the root node is sufficient to ensure that
no node in the cloned tree can be mutated by an actor holding a reference to the
original tree and vice versa. This property is upheld because the root node in
the receiver btree and the returned btree will both necessarily have a reference
count of at least 2 when this method returns. All tree mutations recursively
acquire mutable node references (see mut) as they traverse down the tree. The
act of acquiring a mutable node reference performs a clone if a node's reference
count is greater than one. Cloning a node (see clone) increases the reference
count on each of its children, ensuring that they have a reference count of at
least 2. This, in turn, ensures that any of the child nodes that are modified
will also be copied-on-write, recursively ensuring the immutability property
over the entire tree.```
```

**Review by sumeerbhola — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/util/interval/generic/internal/interval_btree.tmpl.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LyUIgL9AXOFHYBpmoix:-LydmA5z7cDCy5jdPsTU:b9lten3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc6446206cdde4e2988d7ef0d32e3d43a0da3765/pkg/util/interval/generic/internal/interval_btree.tmpl.go#L166)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Your understanding sounds almost exactly correct. The one thing that it sounds like you're still unsure about is why `mut()` does a recursive decrement on the cloned node's refcount. On the path that you're referencing, `mut()` is performing a clone so that it can write. Because `mut()` is cloning a node, it can release it's reference to the old node. _If_ this is the final reference to the old node, which is only possible if we're racing with another call to `decRef` (I added a comment), then that should recursively release references on the children it points to and be recycled.

> Could you add a high-level comment somewhere in this file?

I added the following comment to `btree.Clone`:

```
Incrementing the reference count on the root node is sufficient to ensure that
no node in the cloned tree can be mutated by an actor holding a reference to the
original tree and vice versa. This property is upheld because the root node in
the receiver btree and the returned btree will both necessarily have a reference
count of at least 2 when this method returns. All tree mutations recursively
acquire mutable node references (see mut) as they traverse down the tree. The
act of acquiring a mutable node reference performs a clone if a node's reference
count is greater than one. Cloning a node (see clone) increases the reference
count on each of its children, ensuring that they have a reference count of at
least 2. This, in turn, ensures that any of the child nodes that are modified
will also be copied-on-write, recursively ensuring the immutability property
over the entire tree.```
</blockquote></details>

This comment is helpful. I was still a bit lost, so I reread the code.

The key thing that I missed earlier (a code comment would help) is that a ref represents how many parents a node has. The one special case is the root ref is how many btree structs point to it. Having one parent does not mean the node can be mutated since that parent may be part of two trees.
- when mutating, when see a node N with more than one parent, eagerly clone it. This propagates information of what is shared (that is known higher up in the tree), recursively downwards by ensuring anything along the mutation path (worst case log N) below this parent is also cloned.
  - This cloning ensures the children of N have multiple parents -- the parents are the cloned node N' and any earlier parent nodes (which include N). Any of these children that will need to be modified will also need to be cloned.
- Clone decrements the ref count of N. If the ref count of N is becoming 0 it will be deleted and no longer a parent of its children, so by the definition of what a ref count means it should decrement the ref count of its children.


<!-- Sent from Reviewable.io -->

**Review by danhhz — COMMENTED** [review]
I like the `//go:generate ../../util/interval/generic/gen.sh` lines, that's a nice way to do this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-:-LzEBAo23aPSbKHAfeBJ:b-mup7to)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/util/interval/generic/gen.sh, line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LzEAtbd5YI1ge25Loru:-LzEAtbe4aErjpvcbQRV:b-6q1dny) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c6b73b8afd9ada97d079b20c569c4c09c9b7502/pkg/util/interval/generic/gen.sh#L10)):*
> ```Shell
> fi
> 
> which go_generics > /dev/null || (echo "Could not find go_generics, to install run: \"go get -u github.com/mmatczuk/go_generics/cmd/go_generics\""; exit 1)
> ```

shouldn't the makefile install them into `./bin` and then this use the ones from there? otherwise we have hermetic build issues, no?

**Review by nvb — COMMENTED** [review]
I spent a little too long trying to figure out why _some_ comments were being stripped from the generated files. First I thought they were being stripped somewhere in [`go_generics`](https://github.com/mmatczuk/go_generics/tree/master/cmd/go_generics). I then realized they were being stripped earlier, in [`go_merge`](https://github.com/mmatczuk/go_generics/tree/master/cmd/go_merge) when we merged the `contract.go` file with the template files. `go_merge` passes `ast.FilterUnassociatedComments` to the stdlib's `ast.MergePackageFiles` [here](https://github.com/mmatczuk/go_generics/blob/0aaa050f9bab8160cf684130d0afa69ff582cbe6/cmd/go_merge/merge.go#L75). Removing that didn't do the trick though, because comments were then positioned incorrectly after the file merge, completely mangling the code. It turns out that `ast.MergePackageFiles` doesn't make any attempt to reposition comments as it merges other AST nodes. I gave fixing this a shot for a little too long before eventually finding out that this is a "major design flaw" in how Go handles the relation between free-floating comments and AST nodes: https://github.com/golang/go/issues/20744. In fact, according to Rob Griesemer, this is the single biggest issue when manipulating the AST.

So long story short, we're dropping the dependency on `go_merge` and doing the simpler thing of a small grep and then a file concatenation. That works and avoids the issues around missing comments. With that, all of the lint warnings are resolved and this is ready to go in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-:-Lzo2G5Z2lV8xzdcmBU8:b-xzdudm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @petermattis, and @sumeerbhola)

___
*[pkg/util/interval/generic/gen.sh, line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LzEAtbd5YI1ge25Loru:-LzmndwGAGqTFCH3Vv0f:bbgdjz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c6b73b8afd9ada97d079b20c569c4c09c9b7502/pkg/util/interval/generic/gen.sh#L10)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

shouldn't the makefile install them into `./bin` and then this use the ones from there? otherwise we have hermetic build issues, no?
</blockquote></details>

Yes, the `Makefile` change ensures that these are installed into `./bin`, this language was just off. Fixed (by removing).

**Review by petermattis — APPROVED** [review]
:lgtm: modulo a small comment on the the `*_tmpl.go` files. I want to find a reason to use `go_generics` myself now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-:-Lzqewq4-aCfD4kKVefQ:bn36sql)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/util/interval/generic/internal/unused.go, line 15 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LzqeaMqDF4FN5YieyIT:-LzqeaMqDF4FN5YieyIU:b-9uvr7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ed93ccd7affd50b3cf126c56143606f05e76f/pkg/util/interval/generic/internal/unused.go#L15)):*
> ```Go
> // Silence unused warnings. The linter doesn't notice that these are test
> // functions because their file is not named *_test.go. We don't want it
> // to be because then it would be run by `go test`.
> ```

Show the `*_tmpl.go` files contain a build tag preventing them from being built by default? Not sure if that would work. Alternately, doesn't Go ignore files that start with `_`?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz, @petermattis, and @sumeerbhola)

___
*[pkg/util/interval/generic/internal/unused.go, line 15 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43850#-LzqeaMqDF4FN5YieyIT:-LzrbxHlDGiC2rTx2PFG:boamc3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ed93ccd7affd50b3cf126c56143606f05e76f/pkg/util/interval/generic/internal/unused.go#L15)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Show the `*_tmpl.go` files contain a build tag preventing them from being built by default? Not sure if that would work. Alternately, doesn't Go ignore files that start with `_`?
</blockquote></details>

That's a good question. Changing the files to start with `_` didn't appease the linter without this file. Neither did adding a `// +build ignore` build tag.

However, switching the test file from `interval_btree_test_tmpl.go` to `interval_btree_tmpl_test.go` allowed it to get picked up as a test by the linter, so we could then get rid of this file. That then required the use of a `// +build ignore` build tag, which I added and now strip out in `gen.sh`.

That seems like a nicer solution to me. Thanks for the suggestion.

**Comment by nvanbenschoten** [comment]
CI is trying to pick up and stress this new `pkg/util/interval/generic/internal` package, which isn't going to work now that it has no buildable go files. This should be a one-time issue due to our strategy of stressing new packages, so I'm going to go ahead and merge. Thanks for the reviews!

bors r=petermattis

**Comment by nvanbenschoten** [comment]
^ Everything passed except `go bench`, which failed due to `No space left on device`.

**Comment by nvanbenschoten** [comment]
We're no longer avoiding the compilation of `contract.go` so there's at least one `.go` buildable go source file in `pkg/util/interval/generic/internal` and we are now manually avoiding the unused warning on `T`. This all appears to be working now.

bors r=petermattis

**Pull request merged**
