### PR TITLE
sql: directly specify columns in TableReader

### PR DESCRIPTION
**Pull request by RaduBerinde**
~Note: the first commit is #74922.~

The internal columns of the TableReader (as well as the row fetcher)
are all the columns of the table, with only a subset of values
actually produced. This design decision has been carried over way past
the point where it makes sense (I admit, it's questionable whether it
ever made sense). For one, "all the columns" is ambiguous (does it
contain non-public columns? does it include system columns?) leading
to various flags and inherent fragility. Second, it relies on the
execution engine to figure out (based on the PostProcessSpec) which
columns are actually needed, which the optimizer already figures out
for us now.

This commit changes the TableReader spec and the interface of
row.Fetcher to always produce a given specific set of column IDs. The
diagram for table readers now specifies the columns by name.

The JoinReader, InvertedJoiner, ZigzagJoiner are not changed in this
commit (but they should be cleaned up as well).

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I'm very happy to see this happening, great work!

> Reviewed 72 of 74 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-:-MtkX99iByQjiLc01cM0:b-cn08z7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @stevendanna)

___
*[-- commits, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkPMHW8khI1um_24sP):*
nit: it might be worth to call out this change with columns by name in a release note.
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkO_mJ9v8w2u-BNr53:-MtkO_mJ9v8w2u-BNr54:bv71nmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/colfetcher/colbatch_scan.go#L210)):*
> ```Go
> 	// Make sure that render expressions are deserialized right away so that we
> 	// don't have to re-parse them multiple times.
> 	if post.RenderExprs != nil {
> ```

Did you add this because it was in `populateTableArgsLegacy`? I think we should not include this here - over there, we need the render expressions to be deserialized because we might remap the indexed vars, but IIUC this PR doesn't have to do that.
___
*[pkg/sql/execinfra/version.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkP7j69s1FY23-hZT5:-MtkP7j69s1FY23-hZT6:bswbu3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/execinfra/version.go#L42)):*
> ```Go
> // ATTENTION: When updating these fields, add a brief description of what
> // changed to the version history below.
> const Version execinfrapb.DistSQLVersion = 55
> ```

These also need to be bumped (we forgot to do it for version 56).
___
*[pkg/sql/execinfrapb/flow_diagram.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkTJIe9XnM4UgTbfJS:-MtkTJIe9XnM4UgTbfJT:b-6kd0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/execinfrapb/flow_diagram.go#L155)):*
> ```Go
> 		col, err := tbl.FindColumnWithID(colID)
> 		if i > 0 {
> 			b.WriteByte(',')
> ```

If we need to scan many columns, then the box will become pretty wide. Thoughts on writing one column per line? Or maybe have a limit of, say of up to 100 characters per line?
___
*[pkg/sql/row/fetcher.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkQLeF-T_jCipMgiv2:-MtkQLeF-T_jCipMgiv3:bk48tj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/row/fetcher.go#L294)):*
> ```Go
> 	var err error
> 
> 	// Scan through the entire columns map to see which columns are
> ```

nit: the comment needs an update.
___
*[pkg/sql/row/fetcher.go, line 1112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkR7Lv2EmAfj2JV54u:-MtkR7Lv2EmAfj2JV54v:b-ecygtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/row/fetcher.go#L1112)):*
> ```Go
> // NextRowInto calls NextRow and copies the results into the given EncDatumRow
> // slice according to the given column map.
> // mapping.
> ```

nit: leftover.
___
*[pkg/sql/row/fetcher.go, line 1167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkRc80BBTEn0qPHzYE:-MtkRc80BBTEn0qPHzYF:b5ibwfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/row/fetcher.go#L1167)):*
> ```Go
> // mapping.
> //
> // Values for columns that are not in the map are ignored. cDatums in
> ```

nit: `s/cDatums/Datums`/.
___
*[pkg/sql/row/fetcher.go, line 1193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkRwZD08PF1I5OfJVR:-MtkRwZD08PF1I5OfJVS:b636oww) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/row/fetcher.go#L1193)):*
> ```Go
> 			continue
> 		}
> 		if err := encDatum.EnsureDecoded(col.GetType(), rf.alloc); err != nil {
> ```

Does `col.GetType()` return the correct type for the inverted column? It might be worth making sure that `inverted_.*` logic tests run through the row-by-row engine correctly (maybe they already do).
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 730 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkU4Z38aVJqoQ6cG4G:-MtkU4Z4482FIbFe5ynU:b-xlnf3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L730)):*
> ```
>  ORDER BY message LIKE 'fetched:%' DESC, ordinality ASC
> ----
> fetched: /xyz/zyx/3.0/2/1 -> <undecoded>
> ```

This seems suspicious - we're scanning `INDEX zyx (z, y, x)`, and only need the value of `x`, so I think the previous output was correct.
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans, line 338 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkV9rP4KFbYTuUpL1B:-MtkV9rP4KFbYTuUpL1C:b-muzyf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans#L338)):*
> ```
> distribution: <hidden>
> vectorized: <hidden>
> rows read from KV: 1 (8 B)
> ```

These changes to stats also seem suspicious.
___
*[pkg/sql/opt/exec/execbuilder/testdata/schema_change_in_txn_nonmetamorphic, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkVSvm3UbtFdOawhGs:-MtkVSvm3UbtFdOawhGt:b-6slqof) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/schema_change_in_txn_nonmetamorphic#L34)):*
> ```
> CPut /Table/56/1/101/1/1 -> /TUPLE/4:4:Decimal/0.00/2:6:Decimal/1101.2
> 
> query T
> ```

nit: this seems like an unrelated addition of a test.
___
*[pkg/sql/opt/exec/execbuilder/testdata/vectorize_local, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkVhJQAu8lbTYaVYaE:-MtkVhJQAu8lbTYaVYaF:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/vectorize_local#L72)):*
> ```
> distribution: <hidden>
> vectorized: <hidden>
> rows read from KV: 2 (16 B)
> ```

ditto

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-:-MtnDaDVB2x_d14jKgn-:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[pkg/sql/colfetcher/colbatch_scan.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkO_mJ9v8w2u-BNr53:-MtnCbFaDY4IPeJsubHZ:b-tm0elr) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/colfetcher/colbatch_scan.go#L210)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Did you add this because it was in `populateTableArgsLegacy`? I think we should not include this here - over there, we need the render expressions to be deserialized because we might remap the indexed vars, but IIUC this PR doesn't have to do that.
</blockquote></details>

Yup, removed.
___
*[pkg/sql/execinfra/version.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkP7j69s1FY23-hZT5:-MtmzRagChqsM2LeeSYx:b-fn8mpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/execinfra/version.go#L42)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

These also need to be bumped (we forgot to do it for version 56).
</blockquote></details>

:facepalm: 
___
*[pkg/sql/execinfrapb/flow_diagram.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkTJIe9XnM4UgTbfJS:-MtnC_rDEvw_V0eltRN8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/execinfrapb/flow_diagram.go#L155)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

If we need to scan many columns, then the box will become pretty wide. Thoughts on writing one column per line? Or maybe have a limit of, say of up to 100 characters per line?
</blockquote></details>

Done.
___
*[pkg/sql/row/fetcher.go, line 1193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkRwZD08PF1I5OfJVR:-Mtmzf2wCRfWPgTUVOeh:bbiye4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/row/fetcher.go#L1193)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Does `col.GetType()` return the correct type for the inverted column? It might be worth making sure that `inverted_.*` logic tests run through the row-by-row engine correctly (maybe they already do).
</blockquote></details>

Yeah, we're passing in the full column descriptors and the callers do the inverted column type replacement before setting up the fetcher.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 730 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkU4Z38aVJqoQ6cG4G:-Mtn-qkM5MXCgqNMfikb:bl9z49f) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L730)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This seems suspicious - we're scanning `INDEX zyx (z, y, x)`, and only need the value of `x`, so I think the previous output was correct.
</blockquote></details>

In the optimizer, if a scan is constrained it must return the columns it is constrained on. This is why the plan above has the scan returning `x,y,z` and then it projects away column `x`. We could fix that in the optimizer if it's a problem - filed https://github.com/cockroachdb/cockroach/issues/75153.
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans, line 338 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkV9rP4KFbYTuUpL1B:-Mtn14jX2j7-aDrixxFh:bg63u10) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans#L338)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

These changes to stats also seem suspicious.
</blockquote></details>

Great catch, I didn't notice that! I did not override the new method in the rowFetcherStatCollector. I now unembedded the row.Fetcher so that we have to implement all methods explicitly.
___
*[pkg/sql/opt/exec/execbuilder/testdata/vectorize_local, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkVhJQAu8lbTYaVYaE:-Mtn5aBd1P_xbDWP66GH:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/vectorize_local#L72)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 74 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-:-MtnHdaVE8Y5qWZfLaPH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @stevendanna)

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 730 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtkU4Z38aVJqoQ6cG4G:-MtnH15JCcIXxEMi03MM:b-kufkx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/425f9be5c0c10e37d202d8f128eb91f75007a251/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L730)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In the optimizer, if a scan is constrained it must return the columns it is constrained on. This is why the plan above has the scan returning `x,y,z` and then it projects away column `x`. We could fix that in the optimizer if it's a problem - filed https://github.com/cockroachdb/cockroach/issues/75153.
</blockquote></details>

I see, thanks.
___
*[pkg/sql/execinfrapb/flow_diagram_external_test.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtnHBFc1Ycl7vJgisqa:-MtnHBFc1Ycl7vJgisqb:b-yekcy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3f650fd24171e9e44804621e63808c811d5a00/pkg/sql/execinfrapb/flow_diagram_external_test.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

nit: `s/2018/2022/`.
___
*[pkg/sql/execinfrapb/flow_diagram_external_test.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtnHHyWA216bY6RjiFv:-MtnHHyWA216bY6RjiFw:b-rzfm6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3f650fd24171e9e44804621e63808c811d5a00/pkg/sql/execinfrapb/flow_diagram_external_test.go#L48)):*
> ```Go
> 		  this_is_a_very_long_name_15 INT,
> 		  this_is_a_very_long_name_16 INT,
> 			x INT,
> ```

super nit: the indentation is different.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75114)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @yuzefovich)

___
*[pkg/sql/execinfrapb/flow_diagram_external_test.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75114#-MtnHHyWA216bY6RjiFv:-Mto-ic-24QW64Kyuu3H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3f650fd24171e9e44804621e63808c811d5a00/pkg/sql/execinfrapb/flow_diagram_external_test.go#L48)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: the indentation is different.
</blockquote></details>

Done.

**Pull request merged**
