### PR TITLE
roachprod: support multiple local clusters

### LINKED ISSUE #71945: roachprod: support multiple local clusters
This issue tracks adding support for multiple local clusters to roachprod. This is necessary for multi-tenant support.

### PR DESCRIPTION
**Pull request by RaduBerinde**
Many of these commits are cleanup and reorganization. The functional changes are:
- we no longer use ~/.roachprod/hosts; instead we use json files in ~/.roachprod/clusters
- we can now have multiple local clusters, with names like local-foo
- roachprod invocations using different GCE projects no longer step on each-other's toes 

When this PR merges, roachprod will lose track of any existing local cluster; it will need to be cleaned up and recreated.

#### roachprod: minor cleanup for cloud.Cloud

This change fills in some missing comments from `cloud.Cloud` and
improves the interface a bit. Some of the related roachprod code is
cleaned up as well.

Release note: None

#### roachprod: clean up local cluster metadata

The logic around how the local cluster metadata is loaded and saved is
very convoluted. The local provider is using `install.Clusters` and is
writing directly to the `.hosts/local` file.

This commit disentangles this logic: it is now up to the main program
to call `local.AddCluster()` to inject local cluster information. The
main program also provides the implementation for a new
`local.VMStorage` interface, allowing the code for saving the hosts
file to live where it belongs.

Release note: None

#### roachprod: clean up local cluster deletion

This change moves the code to destroy the local cluster to the local
provider. The hosts file is deleted through LocalVMStorage.

Release note: None

#### roachprod: rework clusters cache

This commit changes roachprod from using `hosts`-style files in
`~/.roachprod/hosts` for caching clusters to using json files in
`~/.roachprod/clusters`.

Like before, each cluster has its own file. The main advantage is
that we can now store the entire cluster metadata instead of
manufacturing it based on one-off parsing.

WARNING: after this change, the information in `~/.roachprod/hosts`
will no longer be used. If a local cluster exists, the new `roachprod`
version will not know about it. It is recommended to destroy any local
cluster before using the new version. A local cluster can also be
cleaned up manually using:
```
killall -9 cockroach
rm -rf ~/.roachprod/local
```

Release note: None

#### roachprod: use cloud.Cluster in SyncedCluster

This change stores Cluster metadata directly in SyncedCluster, instead
of making copies of various fields.

#### roachprod: store ports in vm.VM

This change adds `SQLPort` and `AdminUIPort` fields to `vm.VM`. This
allows us to remove the special hardcoded values for the local
cluster.

Having these fields stored in the clusters cache will allow having
multiple local clusters, each with their own set of ports.

Release note: None

#### roachprod: support multiple local clusters

This change adds support for multiple local clusters. Local cluster
names must be either "local" or of the form "local-foo".

When the cluster is named "local", the node directories stay in the
same place, e.g. `~/local/1`. If the cluster is named "local-foo",
node directories are like `~/local/foo-1`.

For local clusters we include the cluster name in the ROACHPROD
variable; this is necessary to distinguish between processes of
different local clusters. The relevant code is cleaned up to
centralize the logic related to the ROACHPROD variable.

Fixes #71945.

Release note: None

meh

#### roachprod: list VMs in parallel

This commit speeds up the slowest step of roachprod: listing VMs from
all providers. We now list the VMs in parallel across all providers
instead of doing it serially.

Release note: None

#### roachprod: fix behavior when mixing GCE projects

Currently roachprod has very poor behavior when used with different
projects on the same host. For example:
```
shell1: GCE_PROJECT=andrei-jepsen roachstress.sh ... // this will run ~forever
sometime later in shell2: roachprod sync (on the default project)
```

The sync on the default project removes the cached information for the
cluster on `andrei-jepsen`, which causes `roachprod` commands against
that cluster (from within the `roachstress.sh` script) to fail.

We fix this by ignoring any cached clusters that reference a project
that the provider was not configured for - both when loading clusters
into memory and when deleting stale cluster files during `sync`.

As part of the change, we also improve the output of `list` to remove
the colon after the cluster name and to include the GCE project:

```
$ roachprod list --gce-project cockroach-ephemeral,andrei-jepsen
Syncing...
Refreshing DNS entries...
glenn-anarest                  [aws]                      9  (142h41m39s)
glenn-drive                    [aws]                      1  (141h41m39s)
jane-1635868819-01-n1cpu4      [gce:cockroach-ephemeral]  1  (10h41m39s)
lin-ana                        [aws]                      9  (178h41m39s)
local-foo                      [local]                    4  (-)
radu-foo                       [gce:andrei-jepsen]        4  (12h41m39s)
radu-test                      [gce:cockroach-ephemeral]  4  (12h41m39s)
```

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 3 of 3 files at r3, 5 of 5 files at r4, 5 of 5 files at r5, 8 of 8 files at r6, 14 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis, @RaduBerinde, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvr5Kd9D0D972CZ9GI:-Mmvr5Kd9D0D972CZ9GJ:b-dug5kw) (no related file):*
The ability to have multiple local clusters seems very useful, thanks!  I like the cleanups and think that a one-time manual cleanup of local clusters isn't too high a cost.

I left some nit-pick comments, but feel free to ignore them.

I'd like to give it a spin locally before approving.

---
___
*[pkg/cmd/roachprod/clusters_cache.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MmviBom4b8hZqzXZfz9:-MmviBom4b8hZqzXZfzA:b-4uyt3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L56)):*
> ```Go
> 
> 	filename := clusterFilename(c.Name)
> 	return os.WriteFile(filename, []byte(b.String()), 0666)
> ```

[nit] `bytes.Buffer` has a `Bytes()` method you can use instead `[]bytes(b.String())`

Any reason we need `0666` vs `0660` here? 
___
*[pkg/cmd/roachprod/clusters_cache.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvexc41RiN-NOZffgS:-Mmvexc41RiN-NOZffgT:b-twi3yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L71)):*
> ```Go
> 	if err := dec.Decode(c); err != nil {
> 		return nil, err
> 	}
> ```

[nit] since you are already reading in the entire file, you could do (warning, code written in comment box):

```golang
 	data, err := os.ReadFile(filename)
 	if err != nil {
 		return nil, err
 	}
 	c := &cloud.Cluster{}
 	if err := json.Unmarshal(data, c); err != nil {
 		return nil, err
 	}
```
___
*[pkg/cmd/roachprod/clusters_cache.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmviq1_9G8djrLWRt8M:-Mmviq1_9G8djrLWRt8N:b-ryp55m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L101)):*
> ```Go
> 		if len(c.VMs) == 0 {
> 			return errors.Errorf("found no VMs in %s", clusterFilename(name))
> 		}
> ```

[nit] Maybe move this up above the initialisation of `sc`
___
*[pkg/cmd/roachprod/clusters_cache.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MmvjTW-12dYjmuMgc2Q:-MmvjTW-12dYjmuMgc2R:bcverr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L128)):*
> ```Go
> 	// lock acquired by syncAll, but other processes may be reading the host
> 	// files concurrently so we need to write the files atomically by writing to
> 	// a temporary file and renaming.
> ```

I'm not seeing where we do this atomic rename.  Seems like it would make sense for `saveCluster` to just always use an atomic writing strategy.
___
*[pkg/cmd/roachprod/clusters_cache.go, line 164 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvkcgn5NQ6MWVTZclr:-Mmvkcgn5NQ6MWVTZcls:bqwvge3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L164)):*
> ```Go
> 	var result []string
> 	cd := os.ExpandEnv(config.ClustersDir)
> 	files, err := ioutil.ReadDir(cd)
> ```

[nit] You can probably get away with `os.ReadDir` here. It almost surely doesn't matter here, but for larger directories it saves on some lstat calls.  If you do convert it, I believe `file.Mode().IsRegular()` below would need to change to `file.Type().IsRegular()`.
___
*[pkg/cmd/roachprod/config/config.go, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvmmw55awb7oBPom1Y:-Mmvmmw55awb7oBPom1Z:bhxmh2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/791b58324e422fd53a955ad1eda36f08ad40fc92/pkg/cmd/roachprod/config/config.go#L78)):*
> ```Go
> 		return true
> 	}
> 	return len(clusterName) >= 2 && strings.HasPrefix(clusterName, "-")
> ```

[nit] Code is fine as-is, but perhaps something like this would be slightly clearer:

```golang
	if clusterName == Local {
		return true
	}
	if !strings.HasPrefix(clusterName, LocalPrefix) {
 		return false
	}
	clusterName = strings.TrimPrefix(clusterName, LocalPrefix)
	return clusterName != ""
```
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 246 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MmvpytbA-FesZb9QOog:-MmvpytbA-FesZb9QOoh:b-w1bkyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/791b58324e422fd53a955ad1eda36f08ad40fc92/pkg/cmd/roachprod/install/cluster_synced.go#L246)):*
> ```Go
> 			}
> 			for _, dir := range dirs {
> 				cmd += fmt.Sprintf(`rm -fr %s/%s`, c.localVMDir(c.Nodes[i]), dir)
> ```

I'm a scaredy cat so I would maybe add a comment to the VMDir function to remind us that its output is used in `rm -rf` statements so it should be careful to not return "" or "/".
___
*[pkg/cmd/roachprod/install/download.go, line 79 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvuqc3AupgrBl4t-8z:-Mmvuqc4-RactD4XLDZ8:bgguhgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/791b58324e422fd53a955ad1eda36f08ad40fc92/pkg/cmd/roachprod/install/download.go#L79)):*
> ```Go
> 	// the download node to the other nodes.
> 	if c.IsLocal() && !filepath.IsAbs(dest) {
> 		// Eg ~/local/1/./bar.txt or ~/local/local-foo/1/./bar.txt
> ```

Is this comment correct? I think the second example should be `~/local/foo-1/./bar.txt` or have I misread?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis, @RaduBerinde, @stevendanna, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvr5Kd9D0D972CZ9GI:-MmxkYXdAom6nA3Q7f2F:b-ji4ohz) (no related file):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

TFTR! I appreciate you giving it a spin! Hold off on it, I found a problem - we are no longer wiping the local cluster before destroying, will update when it's fixed.
</blockquote></details>

Ok, I fixed that issue (in the "clean up local cluster deletion" commit).

---
___
*[pkg/cmd/roachprod/clusters_cache.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MmviBom4b8hZqzXZfz9:-Mmxc0Pe9AOsFcUHC9vj:b-7sbaze) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L56)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] `bytes.Buffer` has a `Bytes()` method you can use instead `[]bytes(b.String())`

Any reason we need `0666` vs `0660` here? 
</blockquote></details>

Just went with what the old code did, changed to 0660 now.
___
*[pkg/cmd/roachprod/clusters_cache.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmviq1_9G8djrLWRt8M:-MmxcQT28D3z9Gj1zL3a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L101)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] Maybe move this up above the initialisation of `sc`
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/clusters_cache.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MmvjTW-12dYjmuMgc2Q:-MmxcQxPCxqry5K9cn-j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L128)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I'm not seeing where we do this atomic rename.  Seems like it would make sense for `saveCluster` to just always use an atomic writing strategy.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/clusters_cache.go, line 164 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvkcgn5NQ6MWVTZclr:-MmxcbTH3R-rZ_1EfX9G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L164)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] You can probably get away with `os.ReadDir` here. It almost surely doesn't matter here, but for larger directories it saves on some lstat calls.  If you do convert it, I believe `file.Mode().IsRegular()` below would need to change to `file.Type().IsRegular()`.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/config/config.go, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvmmw55awb7oBPom1Y:-Mmxe8no0HAL2xUuj4rs:b-y6jf3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/791b58324e422fd53a955ad1eda36f08ad40fc92/pkg/cmd/roachprod/config/config.go#L78)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] Code is fine as-is, but perhaps something like this would be slightly clearer:

```golang
	if clusterName == Local {
		return true
	}
	if !strings.HasPrefix(clusterName, LocalPrefix) {
 		return false
	}
	clusterName = strings.TrimPrefix(clusterName, LocalPrefix)
	return clusterName != ""
```

</blockquote></details>

That code is not quite right (it's not dealing with the dash). I switched to a regex and added a test.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 246 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MmvpytbA-FesZb9QOog:-MmxeUoy1UpXPVAFZ8-G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/791b58324e422fd53a955ad1eda36f08ad40fc92/pkg/cmd/roachprod/install/cluster_synced.go#L246)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I'm a scaredy cat so I would maybe add a comment to the VMDir function to remind us that its output is used in `rm -rf` statements so it should be careful to not return "" or "/".
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/install/download.go, line 79 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvuqc3AupgrBl4t-8z:-Mmxec8FEVT4aoZACQqu:b810z21) ([raw file](https://github.com/cockroachdb/cockroach/blob/791b58324e422fd53a955ad1eda36f08ad40fc92/pkg/cmd/roachprod/install/download.go#L79)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Is this comment correct? I think the second example should be `~/local/foo-1/./bar.txt` or have I misread?
</blockquote></details>

Yeah, it was stale, I removed it altogether (not very helpful, and not sure what the `.` in there was about).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis, @stevendanna, and @tbg)

___
*[pkg/cmd/roachprod/clusters_cache.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvexc41RiN-NOZffgS:-MmxuQTu8kCVo3weapEY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1300df6c32549fec3fb27e6821da7d5f5a77460/pkg/cmd/roachprod/clusters_cache.go#L71)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] since you are already reading in the entire file, you could do (warning, code written in comment box):

```golang
 	data, err := os.ReadFile(filename)
 	if err != nil {
 		return nil, err
 	}
 	c := &cloud.Cluster{}
 	if err := json.Unmarshal(data, c); err != nil {
 		return nil, err
 	}
```
</blockquote></details>

Done.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis, @stevendanna, and @tbg)

___
*[pkg/cmd/roachprod/config/config.go, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mmvmmw55awb7oBPom1Y:-Mmz-Ru_AnN_cE_gFnbs:b-xtudp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/791b58324e422fd53a955ad1eda36f08ad40fc92/pkg/cmd/roachprod/config/config.go#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

That code is not quite right (it's not dealing with the dash). I switched to a regex and added a test.
</blockquote></details>

Ah, dropped the line where I defined LocalPrefix which would have dealt with the dash, sorry for the confusion.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis, @RaduBerinde, @stevendanna, and @tbg)

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 204 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mn2g7J18Ju5Rlgj0mAb:-Mn3aM1n7qYIuGCk0uPA:b-ayd96i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f43585b052e20aa9aebaccadbf4732e6c185597/pkg/cmd/roachprod/install/cluster_synced.go#L204)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Random question but what do these parens around the value do?
</blockquote></details>

Inside `//` it's a regexp so the parens are a group in the pattern. It doesn't seem that think we're making any use of that fact. I support removing it to avoid confusion.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @petermattis, @RaduBerinde, @stevendanna, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mn4m6Zl8WAEuItL1Eow:-Mn4m6Zl8WAEuItL1Eox:bleipwu) (no related file):*
I tried this out locally and things seem to be working well.

> I'm slightly worried about the impact of changing the ROACHPROD= convention - if you have a running (non-local) cluster, after you update roachprod, the stop command will no longer work. I could probably make it so that only local clusters use the new convention, but it would make things even more messy.

:thinking: I wonder how many running, non-teamcity roachprod clusters there are.  At the time of this writing there were 12 in the GCE projects I checked, but there are many GCE projects.  

If we kept the old stop implementation around and provided it under a `legacy-stop` utility command so that those with old clusters have a tool to use until they can recreate their cluster (or cycle through `legacy-stop` and `start` on their nodes), would that be enough to allow us to handle the transition period without too much disruption?  We could remove legacy-stop once we've given those with long-running clusters some time.

> I could probably make it so that only local clusters use the new convention, but it would make things even more messy.

It might not be _too_ messy code-wise. A method on SyncedCluster could construct the right value for ROACHPROD based on the cluster type and I don't _think_ other functions would need to know about the difference.  That said, if we can help manage the disruption enough, it seems like we should err on the side of not having another minor detail to keep in mind.

---
___
*[pkg/cmd/roachprod/clusters_cache.go, line 63 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mn4ZE2LE8XNG2K4aVhX:-Mn4ZE2ME5o9riJTE5BH:b1dpg8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4e516e805e3b51d55106f24f8f258a856113ac/pkg/cmd/roachprod/clusters_cache.go#L63)):*
> ```Go
> 		return err
> 	}
> 	return os.Rename(tmpFilename, filename)
> ```

We can fix in a follow-up if you'd like, but a couple of other things we might want to consider

- Sync the temporary file before the rename to ensure no one can end up seeing a zero-byte file; and,
- Attempt to clean up the temporary file in the case of WriteFile or Rename failing.

I suppose we could also use `ioutil.TempFile` to create the temporary file, but the higher level file lock we take before writing into this directory makes it unnecessary.

**Comment by RaduBerinde** [comment]
Ahh, what a mess.. This has a ton of conflicts with https://github.com/cockroachdb/cockroach/pull/71660... I wish someone had pointed that PR out to me beforehand. What would be the correct way to sync up with anyone else working on or with knowledge of roachprod? CC @healthy-pod @rail

**Comment by RaduBerinde** [comment]
Allrighty, I managed to merge all the changes. I fixed the multiple GCE project issue and made some more improvements. Most commits changed quite a bit, it would be great to take another look over all of them (sorry, I know it's a lot!).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @healthy-pod, @rail, and @stevendanna)

___
*[pkg/cmd/roachprod/clusters_cache.go, line 63 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mn4ZE2LE8XNG2K4aVhX:-Mnb8vuhDppEmbpSkHRY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4e516e805e3b51d55106f24f8f258a856113ac/pkg/cmd/roachprod/clusters_cache.go#L63)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

We can fix in a follow-up if you'd like, but a couple of other things we might want to consider

- Sync the temporary file before the rename to ensure no one can end up seeing a zero-byte file; and,
- Attempt to clean up the temporary file in the case of WriteFile or Rename failing.

I suppose we could also use `ioutil.TempFile` to create the temporary file, but the higher level file lock we take before writing into this directory makes it unnecessary.
</blockquote></details>

Done.

**Review by rail — APPROVED** [review]
:lgtm:

Love it! The code is much easier to navigate and read now. 

Sorry for the previous merge conflicts :/

> Reviewed 47 of 52 files at r13, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-:-Mncm6QsEdYmtY0EgiDo:b-87924)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @healthy-pod, and @stevendanna)

___
*[pkg/roachprod/install/cockroach.go, line 60 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MncjilD-kmqBP2WL5_e:-MncjilD-kmqBP2WL5_f:brxzefo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3433c3ed5b839ab05c18e9a105e4e2054986f5/pkg/roachprod/install/cockroach.go#L60)):*
> ```Go
> 	}
> 
> 	path := filepath.Join(c.localVMDir(node), config.Binary)
> ```

So much easier to read :+1: 
___
*[pkg/roachprod/config/config_test.go, line 15 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-Mncimnr-fnIla6v95pr:-Mncimnr-fnIla6v95ps:bk4dac4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3433c3ed5b839ab05c18e9a105e4e2054986f5/pkg/roachprod/config/config_test.go#L15)):*
> ```Go
> import "testing"
> 
> func TestIsLocalClusterName(t *testing.T) {
> ```

Yay tests!
___
*[pkg/roachprod/install/cluster_synced_test.go, line 19 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-MncjYeEDWjCV-6231fb:-MncjYeEDWjCV-6231fc:b3mp7f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3433c3ed5b839ab05c18e9a105e4e2054986f5/pkg/roachprod/install/cluster_synced_test.go#L19)):*
> ```Go
> 
> // TestRoachprodEnv tests the roachprodEnvRegex and roachprodEnvValue methods.
> func TestRoachprodEnv(t *testing.T) {
> ```

yay, moar tests!

**Review by stevendanna — APPROVED** [review]

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71970#-:-MnfbiZd8MQD9UZ2hMF3:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @healthy-pod, and @stevendanna)

**Pull request merged**
