### PR TITLE
server: avoid generating 2MB of stack traces during `go test -v`

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thanks! 💯

**Comment by tschottdorf** [comment]
cc @andreimatei I think you filed an issue about this that I now don't seem to find.

**Comment by andreimatei** [comment]
I remember my complain was about some change to some testing infrastructure that you were doing at the time, Tobi, that had as an effect that when it fired, it'd make it really hard to see which test was the one encountering the problem. But I can't remember what it was...

**Comment by benesch** [comment]
Ok, merging! TFTR

**Pull request merged**
