### PR TITLE
obsservice: add asynchronous MemoryQueue consumer framework

### PR DESCRIPTION
**Pull request by abarganier**
This is the final bit of the core obsservice prototype framework
necessary to create an end-to-end event processing pipeline.

Previous work has been done to enable the obsservice process to
ingest, route, validate, transform, and enqueue events that
are received. The last step after that is to asynchronously
process those enqueued events.

This patch does so by creating a MemQueueProcessor.

The MemQueueProcessor is given a MemoryQueue to read off of, and
an EventProcessor to feed the dequeued events to. This is all done
asynchronously in a separate goroutine, as to not tie up the server
threads used by the gRPC server used to ingest data. 

The processor given to the MemQueueProcessor can be a ProcessorGroup,
which groups together common functionality in used to process events (e.g.
validation, further processing such as writing to storage, etc). 

The MemQueueProcessor is hooked up to a stopper, which will drain
the encapsulated MemoryQueue before exiting. This is done with a
generous timeout.

Lastly, a couple small QoL/cleanup items are included in this PR, which were
relevant to the primary work that was being done. 

Release note: none

Epic: CRDB-28191

**Reviewer note: This PR is intended to be reviewed commit-wise, which should make things much easier to digest/understand.**

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/obsservice/cmd/obsservice/main.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgKQDv-ZlRG_Q9yS-_:-NhgKQDv-ZlRG_Q9yS-a:b-v1wyuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef53a7e6c61805542f55360a9a2fa04277771614/pkg/obsservice/cmd/obsservice/main.go#L113)):*
> ```Go
> 			return err
> 		}
> 		fmt.Printf("Listening for OTLP connections on %s.\n", otlpAddr)
> ```

did you mean to log this?
___
*[`pkg/obsservice/obslib/process/processor.go` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgJE427wTW9yXa8byU:-NhgJE427wTW9yXa8byV:bouk1o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/59cde06ad8f004b2d3cbf5f896f0c0b8316f7d31/pkg/obsservice/obslib/process/processor.go#L49)):*
> ```Go
> type ProcessorGroup[T any] struct {
> 	alias      string
> 	ownerTeam  obslib.OwnerTeam
> ```

is this used to identify the owner of the event, so when failed tests are created can be assigned to the right team? Or is this not about CRL teams?
___
*[`pkg/obsservice/obslib/queue/mem_queue.go` line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgKZPB1joiY67qawIy:-NhgKZPB1joiY67qawIz:b-nwwht8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a030aa835291308d4456f56c51aeb1c2a1bd06f/pkg/obsservice/obslib/queue/mem_queue.go#L90)):*
> ```Go
> 
> // Dequeue removes and returns the oldest element from this
> // MemoryQueue. If this MemoryQueue is empty, nil is returned.
> ```

comments need to be update to reflect what the bool returned means
___
*[`pkg/obsservice/obslib/process/mem_queue_processor_test.go` line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgLXD_4xdBFQmoFoo0:-NhgLXD_4xdBFQmoFoo1:b-4pqkb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4846b9d3a05c021b105bcb7119b1c021c19628d9/pkg/obsservice/obslib/process/mem_queue_processor_test.go#L52)):*
> ```Go
> 		processor := &TestWaitGroupCountProcessor{}
> 		// We want the processor to stall until after quiesce. This allows us to verify that the queue is drained,
> 		// even after the
> ```

nit: missing end of sentence

**Review by abarganier — COMMENTED** [review]
TFTR! RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-:-NhhE6oz5DZTCxrDHXuo:b-qoyhu5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/obsservice/cmd/obsservice/main.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgKQDv-ZlRG_Q9yS-_:-NhhDSHGCM9MY3HWRy4O:bn9kyya) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef53a7e6c61805542f55360a9a2fa04277771614/pkg/obsservice/cmd/obsservice/main.go#L113)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

did you mean to log this?
</blockquote></details>

Thanks for pointing this out! The use of `fmt` is a relic of old times, it should definitely be a log call instead.

Switched to an Infof call.
___
*[`pkg/obsservice/obslib/process/processor.go` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgJE427wTW9yXa8byU:-NhhDpFX0ilfZmQ0n3TP:b3luc57) ([raw file](https://github.com/cockroachdb/cockroach/blob/59cde06ad8f004b2d3cbf5f896f0c0b8316f7d31/pkg/obsservice/obslib/process/processor.go#L49)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is this used to identify the owner of the event, so when failed tests are created can be assigned to the right team? Or is this not about CRL teams?
</blockquote></details>

Yup, you've got it right! The idea is that eventually, teams own the individual data processing pipelines, while we own the platform. If things go haywire with a specific event pipeline, this helps us know which team we need to contact. 
___
*[`pkg/obsservice/obslib/queue/mem_queue.go` line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgKZPB1joiY67qawIy:-NhhE3tbCgYcrhZyIGkx:bwqc7e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a030aa835291308d4456f56c51aeb1c2a1bd06f/pkg/obsservice/obslib/queue/mem_queue.go#L90)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

comments need to be update to reflect what the bool returned means
</blockquote></details>

Oops - fixed. Thanks.
___
*[`pkg/obsservice/obslib/process/mem_queue_processor_test.go` line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-NhgLXD_4xdBFQmoFoo0:-NhhE5hX1PKN0qxdJuht:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4846b9d3a05c021b105bcb7119b1c021c19628d9/pkg/obsservice/obslib/process/mem_queue_processor_test.go#L52)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: missing end of sentence
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r8, 1 of 1 files at r10, 2 of 2 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113098#-:-Ni540RBEe0W2Tq7MV9Z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by abarganier** [comment]
TFTR! 

bors r=maryliag

**Pull request merged**
