### PR TITLE
colexec: extract builder and colfetcher packages

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit does two no-op package restructurings:

1. extract a colexec/builder package from colexec which contains
   NewColOperator
2. extract a colfetcher package from colexec which contains cfetcher and
   colbatch_scan

The purpose of this is to begin to slim down the `colexec` package,
which is currently enormous and has many dependencies. I would like to
start moving to a place where `colexec` doesn't have to import the
world, especially for tests.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Unfortunately, this doesn't manage to slim down the size of the `colexec` test binary when compiled, because many `colexec` tests use `NewColOperator`. (to get around this circular important, I injected `NewColOperator` into a `TestNewColOperator` in the `colexec_test` package)

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 55 of 55 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50452)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/op_creation.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50452#-MARiIas1Un49ou4LmLg:-MARiIas1Un49ou4LmLh:b-3hjasi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3da3627516ee92888274abef3efc272d20a05e/pkg/sql/colexec/op_creation.go#L25)):*
> ```Go
> )
> 
> // NewColOperator is a test helper that's always aliased to builder.NewColOperator.
> ```

nit: `s/NewColOperator/TestNewColOperator/`.
___
*[pkg/sql/colexec/builder/execplan.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50452#-MARjmKhAQUqJZlOTDXp:-MARjmKhAQUqJZlOTDXq:bqjkofm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3da3627516ee92888274abef3efc272d20a05e/pkg/sql/colexec/builder/execplan.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package builder
> ```

I think `builder` might be too generic, maybe `colbuilder`?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50452)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/builder/execplan.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50452#-MARjmKhAQUqJZlOTDXp:-MASbl140XsXiwo6VE4l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3da3627516ee92888274abef3efc272d20a05e/pkg/sql/colexec/builder/execplan.go#L11)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think `builder` might be too generic, maybe `colbuilder`?
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm: once you make CI happy.

nit: in the commit message (and PR description) `s/builder/colbuilder/`.

> Reviewed 28 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50452#-:-MAT7uTH9N02zKSCawOu:b-moa8oo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/hashtable.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50452#-MAT7_m-4W42bHieGOUc:-MAT7_m-4W42bHieGOUd:b4m2b9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba6b49d387660b0307a713e56584e9104c63f7f/pkg/sql/colexec/hashtable.go#L26)):*
> ```Go
> 
> // TODO(yuzefovich): support rehashing instead of large fixed bucket size.
> // HashTableNumBuckets is the default number of buckets in the colexec hashtable.
> ```

nit: the two comment lines should probably be switched.
___
*[pkg/sql/colexec/op_creation.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50452#-MAT7hbLASM58iZOK7or:-MAT7hbLASM58iZOK7os:b-so5v9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba6b49d387660b0307a713e56584e9104c63f7f/pkg/sql/colexec/op_creation.go#L25)):*
> ```Go
> )
> 
> // TetNewColOperator is a test helper that's always aliased to builder.NewColOperator.
> ```

nit: `s/Tet/Test/`

**Comment by jordanlewis** [comment]
I have no clue why, but a logic test is failing like this:

```
I200623 02:36:41.920357 83 sql/logictest/logic.go:1147  SELECT c_id, bill
FROM c AS c2
WHERE EXISTS
(
    SELECT *
    FROM (SELECT c_id, coalesce(ship, bill) AS state FROM o WHERE c_id=c2.c_id) AS o
    WHERE state=bill
);
E200623 02:36:41.920883 961 sql/conn_executor.go:780  [n1,client=127.0.0.1:57871,hostssl,user=root] a SQL panic has occurred while executing the following statement:
SELECT c_id, bill FROM c AS c2 WHERE EXISTS (SELECT * FROM (SELECT c_id, COALESCE(ship, bill) AS state FROM o WHERE c_id = c2.c_id) AS o WHERE state = bill)
E200623 02:36:41.920916 961 util/log/log.go:50  [n1,client=127.0.0.1:57871,hostssl,user=root] a panic has occurred!
panic: external-hash-joiner-unlimited: no bytes to release, current 0, free 10240 [recovered]
	panic: external-hash-joiner-unlimited: no bytes to release, current 0, free 10240

goroutine 961 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc001b24000, 0x860adc0, 0xc0010f2240, 0x7a3d8c0, 0xc001994f60)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:797 +0x359
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc001b24000, 0x860adc0, 0xc0010f2240)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:488 +0x61
panic(0x7a3d8c0, 0xc001994f60)
	/usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x860ae80, 0xc001fa9290, 0xc000483500, 0x7d92391, 0x2c, 0xc002045670, 0x3, 0x3)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:335 +0x212
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc0019aaa00, 0x860ae80, 0xc001fa9290, 0x2800)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:645 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc0019949e0, 0x860ae80, 0xc001fa9290)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:523 +0x63
github.com/cockroachdb/cockroach/pkg/sql/colflow.SupportsVectorized.func1(0xc001966f20, 0x860ae80, 0xc001fa9290)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1229 +0xc7
github.com/cockroachdb/cockroach/pkg/sql/colflow.SupportsVectorized(0x860ae80, 0xc001fa9290, 0xc001220d20, 0xc0001b1300, 0x5, 0x10, 0x1, 0x85e9b40, 0xc00196c380, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1240 +0x719
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).setupFlows(0xc0008c62c0, 0x860ae80, 0xc001fa9290, 0xc001b244c0, 0xc001966c60, 0xc001c3c0c0, 0xc00196c380, 0xc001b244c0, 0x1, 0xc001f0cab0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:168 +0x428
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0008c62c0, 0xc001220b60, 0xc001f0cab0, 0xc000fe7e00, 0xc00196c380, 0xc001b244c0, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:385 +0x523
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc0008c62c0, 0x860ae80, 0xc001fa9290, 0xc001b244c0, 0xc001220b60, 0xc001f0cab0, 0x860cb40, 0xc001f0d290, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1018 +0x1de
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001b24000, 0x860ae80, 0xc001fa9290, 0xc001b243d0, 0x3, 0xebbc2d8, 0xc0003d3c80, 0xc002046701, 0xc0007d91f8, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:904 +0x3f6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001b24000, 0x860ae80, 0xc001fa9290, 0xc001b243d0, 0xebbc2d8, 0xc0003d3c80, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:801 +0x6fb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001b24000, 0x860ae80, 0xc001fa9290, 0x862b2c0, 0xc00198c280, 0xc00113ce9d, 0xa6, 0x0, 0x2, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:488 +0xb23
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001b24000, 0x860ae80, 0xc001fa9290, 0x862b2c0, 0xc00198c280, 0xc00113ce9d, 0xa6, 0x0, 0x2, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99 +0x4f6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001b24000, 0x860adc0, 0xc001cda240, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1356 +0x1ba5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001b24000, 0x860adc0, 0xc0010f2240, 0xc000c6e340, 0x5400, 0x15000, 0xc000c6e3d8, 0xc0002c4270, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1285 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000b16000, 0x860adc0, 0xc0010f2240, 0xc001b24000, 0x5400, 0x15000, 0xc000c6e3d8, 0xc0002c4270, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:490 +0x104
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc000b1f9ed, 0xc0012cd9a0, 0x860adc0, 0xc0010f2240, 0xc0002c4270, 0xc000b16000, 0xc0003d3600, 0x8634880, 0xc000e8a240, 0xc000882ae0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:595 +0x317
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:523 +0x17e
make: *** [testbaselogic] Error 2
```

Any ideas? How could this refactor have changed memory accounting in `SupportsVectorized`?

**Comment by jordanlewis** [comment]
Oh, I think I see the issue.

**Comment by jordanlewis** [comment]
The issue was that `NewColOperator` needs to return the current state of the result struct even in the error case, whereas my patch was returning an empty result struct. Refactored the `opResult` wrapper struct to keep a pointer to the returned result struct, so we always return the right thing now.

**Comment by yuzefovich** [comment]
One of the build failures:
```
------- Stdout: -------
=== RUN   TestLogic/local/vectorize_overloads
=== PAUSE TestLogic/local/vectorize_overloads
=== CONT  TestLogic/local/vectorize_overloads
rewrote:
CREATE TABLE t (d DATE, t TIMESTAMP, FAMILY (t), FAMILY (d));


--- progress: testdata/logic_test/cascade: 120 statements/queries
        --- FAIL: TestLogic/local/vectorize_overloads (1.81s)
            logic.go:2051: 
                 
                testdata/logic_test/vectorize_overloads:300: EXPLAIN (VEC) SELECT _int << 1 FROM many_types
                expected:
                    │
                    └ Node 1
                      └ *colexec.projLShiftInt64Int64ConstOp
                        └ *colexec.colBatchScan
                    
                but found (query options: "") :
                    │
                    └ Node 1
                      └ *colexec.projLShiftInt64Int64ConstOp
                        └ *colfetcher.colBatchScan
                    
            logic.go:2629: 
                testdata/logic_test/vectorize_overloads:308: error while processing
            logic.go:2629: testdata/logic_test/vectorize_overloads:308: too many errors encountered, skipping the rest of the input
```

bors r-

**Comment by jordanlewis** [comment]
Wait, I already got rid of those. It passed CI.

**Comment by jordanlewis** [comment]
image

**Comment by yuzefovich** [comment]
I don't know what's up with that, LShift binary operator was merged yesterday, maybe a rebase gone wrong?

**Comment by jordanlewis** [comment]
Ah, it must mean we were saved from merge skew! 🎉 Thanks bors

**Comment by jordanlewis** [comment]
Well, sorry for corrupting that giant batch :(

**Comment by yuzefovich** [comment]
I think you're not the only one. There are some issues with a geo PR as well.

**Comment by yuzefovich** [comment]
There will be another merge skew with one my PRs:
```
------- Stdout: -------
=== RUN   TestLogic/5node/experimental_distsql_planning_5node
=== PAUSE TestLogic/5node/experimental_distsql_planning_5node
=== CONT  TestLogic/5node/experimental_distsql_planning_5node
        --- FAIL: TestLogic/5node/experimental_distsql_planning_5node (2.64s)
            logic.go:2051: 
                 
                testdata/logic_test/experimental_distsql_planning_5node:115: EXPLAIN (VEC) SELECT k::REGCLASS FROM kv
                expected:
                    │
                    ├ Node 1
                    │ └ *colexec.castOp
                    │   └ *colexec.ParallelUnorderedSynchronizer
                    │     ├ *colexec.colBatchScan
                    │     ├ *colrpc.Inbox
                    │     ├ *colrpc.Inbox
                    │     ├ *colrpc.Inbox
                    │     └ *colrpc.Inbox
                    ├ Node 2
                    │ └ *colrpc.Outbox
                    │   └ *colexec.colBatchScan
                    ├ Node 3
                    │ └ *colrpc.Outbox
                    │   └ *colexec.colBatchScan
                    ├ Node 4
                    │ └ *colrpc.Outbox
                    │   └ *colexec.colBatchScan
                    └ Node 5
                      └ *colrpc.Outbox
                        └ *colexec.colBatchScan
                    
                but found (query options: "") :
                    │
                    ├ Node 1
                    │ └ *colexec.castOp
                    │   └ *colexec.ParallelUnorderedSynchronizer
                    │     ├ *colfetcher.colBatchScan
                    │     ├ *colrpc.Inbox
                    │     ├ *colrpc.Inbox
                    │     ├ *colrpc.Inbox
                    │     └ *colrpc.Inbox
                    ├ Node 2
                    │ └ *colrpc.Outbox
                    │   └ *colfetcher.colBatchScan
                    ├ Node 3
                    │ └ *colrpc.Outbox
                    │   └ *colfetcher.colBatchScan
                    ├ Node 4
                    │ └ *colrpc.Outbox
                    │   └ *colfetcher.colBatchScan
                    └ Node 5
                      └ *colrpc.Outbox
                        └ *colfetcher.colBatchScan
                    
            logic.go:2629: 
                testdata/logic_test/experimental_distsql_planning_5node:140: error while processing
            logic.go:2629: testdata/logic_test/experimental_distsql_planning_5node:140: too many errors encountered, skipping the rest of the input
```
I'd appreciate if you could hold off on this one (I have a lot of WIP based on my PR).

**Comment by jordanlewis** [comment]
No problem, I'll hold off.

**Pull request merged**
