### PR TITLE
sql: purge index mutations that refer purged column mutations

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6789)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I'd like to add another two tests to this change and fix a bug. Coming up

**Comment by vivekmenezes** [comment]
Added a new commit and a note at the top.

**Comment by andreimatei** [comment]
Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[sql/descriptor_mutation_test.go, line 538 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KI8ojIqKe0VL7SReEFA:-KI8ojIqKe0VL7SReEFB:1569780479) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/descriptor_mutation_test.go#L538)):*
> ```Go
> 
> 	// read table descriptor
> 	nameKey := sqlbase.MakeNameMetadataKey(keys.MaxReservedDescID+1, "test")
> ```

there's a `getTableDesc` somewhere that you can use

---

*[sql/descriptor_mutation_test.go, line 607 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYdeKnuIhdO0nJ3G3l:-KIYdeKnuIhdO0nJ3G3m:1767391271) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/descriptor_mutation_test.go#L607)):*
> ```Go
> 
> 		// Make column "i" a mutation.
> 		mTest.writeColumnMutation("i", sqlbase.DescriptorMutation{
> ```

how come you add the mutations three times?

---

*[sql/descriptor_mutation_test.go, line 661 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYdl5eMonrngKYokHI:-KIYdl5eMonrngKYokHJ:1840174502) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/descriptor_mutation_test.go#L661)):*
> ```Go
> 		// excluding row "a" since it's deleted.
> 		numVals := mTest.checkQueryResponse(starQuery, [][]string{{"c", "x", "NULL"}})
> 		// Check that there is an extra hidden KV values for row "a" which is the
> ```

I'm confused... Why does this extra value exist? Who wrote it? Shouldn't adding the `a` row ignore the index?
And the comment doesn't clear the confusion, at least for me :)

---

*[sql/descriptor_mutation_test.go, line 892 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYnkhlSVB1LkZPj3gO:-KIYnkhmo2SIRhyRFaX_:-816083075) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/descriptor_mutation_test.go#L892)):*
> ```Go
> }
> 
> func TestTableMutationQueue(t *testing.T) {
> ```

mind adding a comment about what this test tests?

---

*[sql/descriptor_mutation_test.go, line 951 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYo1Xt5Nf7AgGqQwzu:-KIYo1Xt5Nf7AgGqQwzv:-1423315300) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/descriptor_mutation_test.go#L951)):*
> ```Go
> 
> 	// read table descriptor
> 	nameKey := sqlbase.MakeNameMetadataKey(keys.MaxReservedDescID+1, "test")
> ```

there's a `getTableDescFromID` you can use

---

*[sql/rowwriter.go, line 281 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYWuhWMfDAmfrq6cII:-KIYWuhWMfDAmfrq6cIJ:332724676) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/rowwriter.go#L281)):*
> ```Go
> 	}
> 
> 	var deleteOnlyIndex map[int]struct{}
> ```

mind adding a comment here like "there might also be indexes in the process of being added that are part of a Mutation"

---

*[sql/schema_changer.go, line 336 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYmQNFNhLYp-K87P87:-KIYmQNFNhLYp-K87P88:1449258632) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/schema_changer.go#L336)):*
> ```Go
> // of the table.
> func (sc *SchemaChanger) RunStateMachineBeforeBackfill() error {
> 	for modified := true; modified; {
> ```

Mind adding a comment to the loop? I'm not sure why it's needed :) A `schemaChanger` still corresponds to a single `mutationID`, right?

---

*[sql/schema_changer.go, line 370 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYlbjlFqo9BM25_kdq:-KIYlbjmoA92JUqdv1YH:-2130254537) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/schema_changer.go#L370)):*
> ```Go
> 					switch mutation.State {
> 					case sqlbase.DescriptorMutation_ABSENT:
> 						panic(fmt.Sprintf("ABSENT mutation %v being dropped in %v", mutation, desc))
> ```

nit: I think`%+v` is way generally way more readable than `%v`

---

*[sql/sqlbase/structured.go, line 684 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYg1EauJ8ppGKuIzI7:-KIYg1EauJ8ppGKuIzI8:287828406) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/sqlbase/structured.go#L684)):*
> ```Go
> 	}
> 
> 	// Insert after last entry with the same mutation ID.
> ```

mind expending this comment to explain what the deal is? Why not just append? Is it because we want to possibly batch future schema changes with the column add (so order them before the index add)? But then isn't it possible that other changes will get the same `mutationID` as the index add? Is that OK?
I guess I generally find the fact that `NextMutationID` is not touched here to be unintuitive.

Feel free do ignore:
How about we make `addMutation` accumulate the mutations outside of the `TableDescriptor` (for example in a buffer living on the `txnState`, so maybe we extract this method out of TableDescriptor). And then we make `FinalizeMutation(s)` do the mutationID assignment (after a "topological sort") and modifying and writing the descriptor, plus what `notifySchemaChange` does now (enqueue a schema change on the session). Then you wouldn't have to call `notifySchemaChange` in a loop.

---

*[sql/sqlbase/structured.go, line 695 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYf2UNLriaelWnuuf9:-KIYf2UOB4u5ErP5-whG:809401418) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/sqlbase/structured.go#L695)):*
> ```Go
> }
> 
> // FinalizeMutation returns the id that has been used by mutations appended
> ```

comment needs updating for the multiple ids that can be returned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 13 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[sql/descriptor_mutation_test.go, line 538 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KI8ojIqKe0VL7SReEFA:-KJaGHgvqoKCu9RsPUM8:-1891177661) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/descriptor_mutation_test.go#L538)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> there's a `getTableDesc` somewhere that you can use
</details>
Done is a separate PR

---

*[sql/descriptor_mutation_test.go, line 607 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYdeKnuIhdO0nJ3G3l:-KJaGqXRkrcsM5GYZ3Hc:-801409617) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/descriptor_mutation_test.go#L607)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> how come you add the mutations three times?
</details>
We need to keep adding a mutation, running an operation with the mutation, and then making the mutation active so that SELECT can use the active column/index to view the effect of the operation on the data. Added a comment.

---

*[sql/descriptor_mutation_test.go, line 661 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYdl5eMonrngKYokHI:-KJaKHNEz0HeMNErNoBE:504163474) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/descriptor_mutation_test.go#L661)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I'm confused... Why does this extra value exist? Who wrote it? Shouldn't adding the `a` row ignore the index?
> And the comment doesn't clear the confusion, at least for me :)
</details>
Updated the comment. I hope it make sense.

---

*[sql/descriptor_mutation_test.go, line 892 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYnkhlSVB1LkZPj3gO:-KJaKSSJdLe9wN4rCCiA:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/descriptor_mutation_test.go#L892)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> mind adding a comment about what this test tests?
</details>
Done

---

*[sql/descriptor_mutation_test.go, line 951 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYo1Xt5Nf7AgGqQwzu:-KJBnyewQnoQFuZNSH3O:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/descriptor_mutation_test.go#L951)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> there's a `getTableDescFromID` you can use
</details>
Done

---

*[sql/rowwriter.go, line 281 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYWuhWMfDAmfrq6cII:-KJaMEv5Jzej7N7ElGBw:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8738703efc6969c557e0a883ab545c0fb3fdf1/sql/rowwriter.go#L281)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> mind adding a comment here like "there might also be indexes in the process of being added that are part of a Mutation"
</details>
Done

---

*[sql/schema_changer.go, line 336 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYmQNFNhLYp-K87P87:-KJaN_uCLcQHIy9j5Xec:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/schema_changer.go#L336)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Mind adding a comment to the loop? I'm not sure why it's needed :) A `schemaChanger` still corresponds to a single `mutationID`, right?
</details>
Done

---

*[sql/schema_changer.go, line 370 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYlbjlFqo9BM25_kdq:-KJaOIPwlDVUTZnL__Q4:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/schema_changer.go#L370)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> nit: I think`%+v` is way generally way more readable than `%v`
</details>
done

---

*[sql/sqlbase/structured.go, line 684 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYg1EauJ8ppGKuIzI7:-KJaPxT3U7FMQ81jJ3Es:139820506) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/sqlbase/structured.go#L684)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> mind expending this comment to explain what the deal is? Why not just append? Is it because we want to possibly batch future schema changes with the column add (so order them before the index add)? But then isn't it possible that other changes will get the same `mutationID` as the index add? Is that OK?
> I guess I generally find the fact that `NextMutationID` is not touched here to be unintuitive.
> 
> Feel free do ignore:
> How about we make `addMutation` accumulate the mutations outside of the `TableDescriptor` (for example in a buffer living on the `txnState`, so maybe we extract this method out of TableDescriptor). And then we make `FinalizeMutation(s)` do the mutationID assignment (after a "topological sort") and modifying and writing the descriptor, plus what `notifySchemaChange` does now (enqueue a schema change on the session). Then you wouldn't have to call `notifySchemaChange` in a loop.
> 
</details>
I've added a comment that explains the need to sort here. I'll try out your suggestion in another PR. I agree that this is a bit hard to understand but at least it is tested.

---

*[sql/sqlbase/structured.go, line 695 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KIYf2UNLriaelWnuuf9:-KJaSF0XPKb0h94Sc9w3:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2b5c3f8f0e9aad8834718a9fcc897e97ae2d92/sql/sqlbase/structured.go#L695)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> comment needs updating for the multiple ids that can be returned.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789)*

**Comment by vivekmenezes** [comment]
Sorry for not getting back to this earlier. It's ready for another viewing. Thanks

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Added a new commit and a note at the top.
</details>


---

Review status: 0 of 13 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-:-KJaUoScm2sTvhwko-xr:-691252318)*

**Comment by vivekmenezes** [comment]
I'm going to put this PR on ice while I try another approach  thanks to https://github.com/cockroachdb/cockroach/pull/7019

**Comment by vivekmenezes** [comment]
Once #7075 is merged I can see what I need to salvage in terms of tests from this PR.

**Comment by vivekmenezes** [comment]
This PR is now a lot simpler and is actually attacking a different problem. PTAL, thanks

**Comment by andreimatei** [comment]
Should I just look at r7?

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> This PR is now a lot simpler and is actually attacking a different problem. PTAL, thanks
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-:-KJl6E5NAP6Jedv90v5c:-1645955759)*

**Comment by vivekmenezes** [comment]
I think you need to take a fresh look at it. It's completely different. It used to be 3 commits, it's now 1 and the functionality  to fix the original problem has been removed. It now fixes a different problem for which we don't have an open issue.

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Should I just look at r7?
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-:-KJl6k4X9Soio-BVNLA1:233312405)*

**Comment by andreimatei** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/schema_changer.go, line 462 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpoIeG6WzqPSXRNdcZ:-KJpoIeHAqaRZygOuT8H:927592585) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L462)):*
> ```Go
> // reverseMutations reverses the direction of all the mutations with the
> // mutationID. This is called after hitting an irrecoverable error while
> // applying a schema change. If a column being added is reversed and dropped
> ```

the style of this new comment is weird - it's unclear if the caller is supposed to do anything. Also, it's not that any indexes are dropped, it's that a mutation for adding an index is discarded, right?
Maybe also make it clearer that mutations that this `SchemaChanger` is not responsible for are otherwise not touched. But on second thought... Shouldn't we just cancel all the upcoming mutations? If something went wrong with one change, I probably don't want the next ones any more...

---

*[sql/schema_changer.go, line 474 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpsHFEq1-WWekXT1oU:-KJpsHFEq1-WWekXT1oV:-1847762690) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L474)):*
> ```Go
> 
> 	reverseMutationLoop:
> 		for _, mutation := range desc.Mutations {
> ```

I found this function a bit hard to read, much indenting, gotos and all. How about we leave it as it was, plus the `cols` array, and then we add a separate function that looks for indexes using these cols and returns the mutation IDs to be discarded?

---

*[sql/schema_changer.go, line 479 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJporbNzhLbZuy6DzSO:-KJporbNzhLbZuy6DzSP:-256358083) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L479)):*
> ```Go
> 					mutation.Direction == sqlbase.DescriptorMutation_ADD {
> 					if mutation.State != sqlbase.DescriptorMutation_DELETE_ONLY {
> 						panic(fmt.Sprintf("mutation in bad state: %+v", mutation))
> ```

mind expanding this panic message, to also serve as a comment? We can't reverse is the mutation went past `DELETE_ONLY`?

---

*[sql/schema_changer.go, line 507 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpt9NOgNPolvGE99Z0:-KJpt9NPuOXwq1njxc8d:-2101363547) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L507)):*
> ```Go
> 		}
> 		// Reset table descriptor mutations.
> 		desc.Mutations = newMutations
> ```

don't you need to also find the `SchemaChanger`s for the index mutations and do something to them so they don't run? Or maybe change their code to short-circuit early if their mutationID doesn't exist any more?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/schema_changer.go, line 462 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpoIeG6WzqPSXRNdcZ:-KJqtWuMJX8a-GC_UAUV:-1147897812) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L462)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> the style of this new comment is weird - it's unclear if the caller is supposed to do anything. Also, it's not that any indexes are dropped, it's that a mutation for adding an index is discarded, right?
> Maybe also make it clearer that mutations that this `SchemaChanger` is not responsible for are otherwise not touched. But on second thought... Shouldn't we just cancel all the upcoming mutations? If something went wrong with one change, I probably don't want the next ones any more...
</details>
Well I'm not sure about that. Right now a schema change gets reversed only because of a column NOT NULL violation of an index UNIQUE violation. Under both these circumstances it would be okay to continue along with the other schema changes. In general making progress on stuff that is known to be valid seems okay. 

---

*[sql/schema_changer.go, line 474 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpsHFEq1-WWekXT1oU:-KJqu6VANuzYZakXqE7t:792431819) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L474)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I found this function a bit hard to read, much indenting, gotos and all. How about we leave it as it was, plus the `cols` array, and then we add a separate function that looks for indexes using these cols and returns the mutation IDs to be discarded?
</details>
I've split it into two methods for easy of readability. Made a lot of sense. Thanks!

---

*[sql/schema_changer.go, line 479 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJporbNzhLbZuy6DzSO:-KJquHz9MTUcjVlZmn4i:261614648) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L479)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> mind expanding this panic message, to also serve as a comment? We can't reverse is the mutation went past `DELETE_ONLY`?
</details>
I've added a comment above the panic to act as documentation.

---

*[sql/schema_changer.go, line 507 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpt9NOgNPolvGE99Z0:-KJquRAmRA2wHAcDsamo:-2118167445) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L507)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> don't you need to also find the `SchemaChanger`s for the index mutations and do something to them so they don't run? Or maybe change their code to short-circuit early if their mutationID doesn't exist any more?
</details>
No the schema changers can only run on mutations that are in the front of the queue. It is safe for a mutation to not exist in the front. I'll follow up this PR with another PR that tests that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789)*

**Comment by andreimatei** [comment]
LGTM

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I think you need to take a fresh look at it. It's completely different. It used to be 3 commits, it's now 1 and the functionality  to fix the original problem has been removed. It now fixes a different problem for which we don't have an open issue.
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/schema_changer.go, line 462 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpoIeG6WzqPSXRNdcZ:-KK9g0quioFkI5jWZ6bc:-908071729) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L462)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Well I'm not sure about that. Right now a schema change gets reversed only because of a column NOT NULL violation of an index UNIQUE violation. Under both these circumstances it would be okay to continue along with the other schema changes. In general making progress on stuff that is known to be valid seems okay. 
</details>
I think it's pretty questionable what should happen if you've enqueued multiple schema changes and one fails. Do the next ones still make sense?
In any case, consider changing the style of the comment: s/should also be dropped/will also be dropped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-:-KK9fpma789yRr3n4sM6:676834233)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/schema_changer.go, line 462 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789#-KJpoIeG6WzqPSXRNdcZ:-KK9inJZuz3Yf79Fr2Ta:-1015417709) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a53b13187365429c4094d8fd4b38d09d6490381/sql/schema_changer.go#L462)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I think it's pretty questionable what should happen if you've enqueued multiple schema changes and one fails. Do the next ones still make sense?
> In any case, consider changing the style of the comment: s/should also be dropped/will also be dropped.
</details>
Makes sense. Changed to: will also be dropped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6789)*

**Pull request merged**
