### PR TITLE
sql: split the code for UPSERT from the INSERT code

### LINKED ISSUE #23672: sql: missing check on the unicity of SET LHS operands in ON CONFLICT DO UPDATE
```sql
INSERT INTO ... ON CONFLICT ... DO UPDATE SET x = 1, x = 1
```

Succeeds, mistakenly, whereas `UPDATE ... SET x = 1, x = 1` properly fails saying the name `x` cannot be assigned twice.

Found while working on #23373.

### LINKED ISSUE #23674: sql: panic in UPSERT/INSERT due to missing check on aggregation functions
```
panic while executing 1 statements: 
INSERT INTO _(_) VALUES (_) ON CONFLICT (_) DO UPDATE SET _ = (sum(_) OVER ())::INT; caused by runtime error: invalid memory address or nil pointer dereference
```

The problem is that the check for aggregation/windowing function is not performed as it should for the RHS expressions of UPDATE SET.

### PR DESCRIPTION
**Pull request by knz**
Commits split away from #23373 (fixing #23156 and related bugs) to ease reviewing.

Fixes #23672.
Fixes #23674.

### CODE REVIEW

**Comment by knz** [comment]
(note that this code gets further improved / commented / explained in sub-commits of #23373; this PR here merely ensures the diff is minimized)

**Comment by jordanlewis** [comment]
:lgtm: on the merits.

Although it seems weird that you've lifted part of the duplicate pk limitation and not all of it. How will we explain that nicely to users?

Perhaps you should pull out that functionality change into a follow on PR. That will make a potential cherrypick of this easier.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23657#-:-L7B4aknyBV2uvLt9vay:b-vqt8uh)*

**Comment by knz** [comment]
I have removed the partial fix to #23660 from the 2nd commit.

**Comment by knz** [comment]
TFYR

**Pull request merged**
