### PR TITLE
sql: pre-split hash sharded indexes ranges before DELETE_AND_WRITE_ONLY

### LINKED ISSUE #74558: sql: pre-split hash sharded indexes on shard boundaries before `DELETE_AND_WRITE_ONLY`
**Is your feature request related to a problem? Please describe.**

We're creating a hash sharded index because we know that the write volume will be sequential. As we've see in https://github.com/cockroachdb/cockroach/issues/62672#issuecomment-842506818 and elsewhere, throughput can crater when we make these new indexes writable because all of the load lands on a single range. Ideally we'd pre-split the new index before turning on traffic.

It's a somewhat tricky problem to figure out, in the general case, where to pre-split these new indexes. Fortunately, for hash sharded indexes, we get to make an assumption that underneath each shard, the data is uniformly distributed. That means we can safely split at each shard boundary and know that it's a smart place to put a split.

**Describe the solution you'd like**

Before making a hash sharded index `DELETE_AND_WRITE_ONLY`, split it with an expiring split point at each shard boundary.

**Describe alternatives you've considered**
There was tons of discussion of the broader problem in this [internal thread](https://cockroachlabs.slack.com/archives/CARM0PTK4/p1641503398002900).

**Additional context**

We should also split other secondary indexes at the same time, but the heuristic on how many split and where to put them is less obvious. We'll track that separately. 

This change should be backportable.

Epic: CRDB-7363

gz#10941

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #74558

Pre-split ranges on shard boundaries before SchemaChanger move
new hash sharded indexes from DELETE_ONLY to DELETE_AND_WRITE_ONLY
state.

Release note (bug fix): None

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
need to rebase after pr #74835 is merged

**Comment by chengxiong-ruan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74923#-MtoVHxA6XQ8bfewVK8O:-MtoVHxB6NcjeE03Ug2M:bv5goh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1723f7a573cb5d67d835a7ab0dd6ab372dc065ee/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L910)):*
> ```
> );
> 
> skipif config 3node-tenant
> ```

querying `crdb_internal.ranges` is not supported in multi-tenant mode

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74923#-:-MuBQyV7CyhVlcaGbomv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schema_changer_test.go, line 7591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74923#-MuBQgmgDLLmhYM7MPOP:-MuBQgmgDLLmhYM7MPOQ:b-1qjmdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1723f7a573cb5d67d835a7ab0dd6ab372dc065ee/pkg/sql/schema_changer_test.go#L7591)):*
> ```Go
> 
> 	tdb.Exec(t, `
> SET experimental_enable_hash_sharded_indexes = on;
> ```

this reminds me, we should create an issue to track deprecating this session variable and removing the gates.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74923)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schema_changer_test.go, line 7591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74923#-MuBQgmgDLLmhYM7MPOP:-MuBq6qL2zV_-sY-o8bQ:bgd2ypk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1723f7a573cb5d67d835a7ab0dd6ab372dc065ee/pkg/sql/schema_changer_test.go#L7591)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this reminds me, we should create an issue to track deprecating this session variable and removing the gates. 
</blockquote></details>

ha, that is true. created #75442

**Comment by chengxiong-ruan** [comment]
thanks for the review and adding backporting label :)
bors r+

**Pull request merged**
