### PR TITLE
sql: block initial multi-region if zone configs have multi-region fields set

### PR DESCRIPTION
**Pull request by otan**
Refs: #63071

See individual commits for details.

Note I have not done overwriting. This is not going to be planned for 21.1 unless we deem it a GA-blocker.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
I think someone more knowledgable should have a look at the `set_zone_config.go` and `zone.go` changes.  @aayushshah15 could you have a look?  Other than that, :lgtm: (minus the nits below)

> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-:-MXdeGp0DmKb5EaxkyLh:bmz7gn8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-MXdav7-7fXlvWl8a7ql:-MXdav7-7fXlvWl8a7qm:b-64vaee) ([raw file](https://github.com/cockroachdb/cockroach/blob/e317fd127098e9f3533c12b3331e7e3f5ba40fca/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L17)):*
> ```
> USE bad_db;
> SET override_multi_region_zone_config = true;
> ALTER DATABASE bad_db CONFIGURE ZONE DISCARD;
> ```

Nit: Don't we have this case covered down below?  Can we just add the validation call down there?
___
*[pkg/sql/region_util.go, line 722 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-MXdfszP9VdqLW9ZV1Wk:-MXdfszP9VdqLW9ZV1Wl:b-sxxw6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0bdb0889d410e6c09516bad3e069c70a55f3e3c/pkg/sql/region_util.go#L722)):*
> ```Go
> }
> 
> // forEachMutableTableInDatabase calls the given function on every table
> ```

Nit: With this change, does this function belong in `region_util.go`?

**Review by aayushshah15 — APPROVED** [review]
:lgtm:  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-:-MXjW6k28pmWpFK93wKO:b593w5t)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @otan)

___
*[pkg/sql/region_util.go, line 1165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-MXjUBOJ356uuujDjDyS:-MXjUBOJ356uuujDjDyT:b1unskq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f216bf28ecd0b3fb60030abb0f38166cfaf2c08e/pkg/sql/region_util.go#L1165)):*
> ```Go
> 	desc catalog.TableDescriptor,
> ) (zonepb.ZoneConfig, error) {
> 	return *zonepb.NewZoneConfig(), nil
> ```

nit: Consider adding a comment here and in `getExpectedDatabaseZoneConfig` above that references the fact that we only care about the fields listed in `MultiRegionZoneConfigFields` and that we expect all of those to be empty in the `SetInitialRegion` case.
___
*[pkg/sql/region_util.go, line 1460 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-MXjPY0m-cWKncUM4_jn:-MXjPY0m-cWKncUM4_jo:b-dl7f9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f216bf28ecd0b3fb60030abb0f38166cfaf2c08e/pkg/sql/region_util.go#L1460)):*
> ```Go
> // the multi-region fields of the table's zone configuration
> // matches what is expected for the given table.
> func (p *planner) validateZoneConfigForMultiRegionTable(
> ```

`ctx` and `dbDesc` don't seem to be used by `validateZoneConfigForMultiRegionTable`. Do we have them here to conform to some sort of interface? If not, maybe we could get rid of them?
___
*[pkg/sql/set_zone_config.go, line 1008 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-MXjVu8dBL9KVJv-VvQd:-MXjVu8dBL9KVJv-VvQe:b-txz3uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e317fd127098e9f3533c12b3331e7e3f5ba40fca/pkg/sql/set_zone_config.go#L1008)):*
> ```Go
> }
> 
> // getZoneConfigRaw looks up the zone config with the given IDs.
> ```

`s/getZoneConfigRaw/getZoneConfigRawBatch`

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63129)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @ajstorm)

___
*[pkg/sql/region_util.go, line 1460 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-MXjPY0m-cWKncUM4_jn:-MXjc-qh0cw6qfFSUMhk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f216bf28ecd0b3fb60030abb0f38166cfaf2c08e/pkg/sql/region_util.go#L1460)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`ctx` and `dbDesc` don't seem to be used by `validateZoneConfigForMultiRegionTable`. Do we have them here to conform to some sort of interface? If not, maybe we could get rid of them?
</blockquote></details>

Done.
___
*[pkg/sql/set_zone_config.go, line 1008 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63129#-MXjVu8dBL9KVJv-VvQd:-MXja3pTBJflsc6N6b2N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e317fd127098e9f3533c12b3331e7e3f5ba40fca/pkg/sql/set_zone_config.go#L1008)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`s/getZoneConfigRaw/getZoneConfigRawBatch`
</blockquote></details>

Done.

**Comment by otan** [comment]
bors r=ajstorm,aayushshah15

**Pull request merged**
