### PR TITLE
sql: add support for row-level AFTER triggers

### LINKED ISSUE #126361: sql: add support for row-level AFTER triggers
This issue tracks adding support for row-level AFTER triggers, which execute for each mutated row in an INSERT, UPDATE, UPSERT, or DELETE after the mutation occurs, as well as any checks and cascades. Example:
```
CREATE TRIGGER t AFTER UPDATE ON table_1 FOR EACH ROW EXECUTE FUNCTION f();
```

Jira issue: CRDB-37296

Jira issue: CRDB-39861

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: refactor cascade planning in the optimizer

This commit makes some mechanical changes to how cascades are planned
so that it will be easier to add trigger planning later.
* The `CascadeBuilder` (now `PostQueryBuilder`) now handles mapping from
  columns in the original memo to the post-query memo. This simplifies
  handling for different kinds of post-queries that keep different sets
  of columns.
* The `build-cascades` opt test directive is now `build-post-queries`.
* Various names and comments are modified to refer to "post-queries"
  instead of just "cascades".

Informs #126361

Release note: None

#### opt: add row-level AFTER triggers to the optimizer

This commit adds the necessary structs and plumbing so that row-level
AFTER triggers can be planned in the optimizer. The opt-tester also now
supports printing row-level AFTER triggers in the query plan when the
`build-post-queries` directive is used. Note that the logic to actually
build the triggers will be in a later commit.

Informs #126361

Release note: None

#### sql: plumb row-level AFTER triggers through execution

This commit plumbs row-level AFTER triggers alongside cascades from
the optimizer to `PlanAndRunCascadesAndChecks`. A follow-up commit
will add the logic to execute the triggers within that function.

Informs #126361

Release note: None

#### opt: build plans for row-level AFTER triggers

This commit adds the logic to build row-level AFTER triggers for a
mutation into trigger-function invocations that can be run after the
mutation finishes. This includes an implementation of
`memo.PostQueryBuilder`, to mirror those used to build cascades.

Informs #126361

Release note: None

#### sql: execute row-level AFTER triggers

This commit adds support to the execution engine for row-level AFTER
triggers. AFTER triggers run after checks and cascades, and may queue
more cascades, checks, or triggers to run. Cascades can also queue
additional post-queries.

Fixes #126361

Release note (sql change): It is now possible to execute row-level
AFTER triggers in response to mutations on a table. Row-level AFTER
triggers fire after checks and cascades for the query have completed.

### CODE REVIEW

**Comment by DrewKimball** [comment]
This PR is split up into 5 commits, where the first 3 are mostly mechanical - refactoring existing code and plumbing triggers from optimization to execution. The 4th commit adds the logic to build the plan for AFTER triggers, and the 5th adds support for executing them.

**Review by mgartner — APPROVED** [review]
:lgtm: Great work! I have mostly minor comments.

Some testing ideas:
* A test that shows that AFTER triggers observe the effects of BEFORE triggers would be good to have. I don't think there are any here.
* What happens when an AFTER trigger modifies a row? Does it error, or are the change lost?

> Reviewed 13 of 13 files at r1, 9 of 9 files at r2, 35 of 35 files at r6, 23 of 23 files at r7, 7 of 7 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-:-O9tmOJM2OlE-eyXqEYy:b-c4anc)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/distsql_physical_planner.go` line 986 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tJNWs3SH1Mgvlmwxw:-O9tJNWs3SH1Mgvlmwxx:boxkfwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb7f608b58a1ae1c7a55c355ede46cad751a6d3/pkg/sql/distsql_physical_planner.go#L986)):*
> ```Go
> // SaveFlowsFunc is the signature for a function used to examine the physical
> // plan for a query. Implementations may not be concurrency-safe.
> type SaveFlowsFunc func(map[base.SQLInstanceID]*execinfrapb.FlowSpec, execopnode.OpChains, []execinfra.LocalProcessor, bool) error
> ```

nit: the `vectorized` name for the `bool` was helpful documentation, I think it's worth keeping.
___
*[`pkg/sql/distsql_running.go` line 2103 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9teFUXBWtkCg7Vw7gT:-O9teFUXBWtkCg7Vw7gU:bi19dxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/sql/distsql_running.go#L2103)):*
> ```Go
> // Returns false if an error was encountered and sets that error in the provided
> // receiver.
> func (dsp *DistSQLPlanner) PlanAndRunCascadesAndChecks(
> ```

nit: Rename to include Triggers or PostQuery (feel free to do this in a future PR - there's probably lots of renaming to be done over time).
___
*[`pkg/sql/opt/exec/execbuilder/cascades.go` line 22 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tJxl09vSOIZ0qRD1z:-O9tJxl11X1RKlv48sVj:bw100dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb7f608b58a1ae1c7a55c355ede46cad751a6d3/pkg/sql/opt/exec/execbuilder/cascades.go#L22)):*
> ```Go
> )
> 
> // cascadeTriggerBuilder is a helper that fills in exec.PostQuery metadata; it
> ```

nit: should we name this postQueryBuilder instead? Also, should we rename the file?
___
*[`pkg/sql/opt/memo/expr.go` line 1357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tGEu-1EgOGcnaAz1B:-O9tGEu-1EgOGcnaAz1C:ba0l5sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a1698dde8b65b904e43f4936b7a82b258b246e/pkg/sql/opt/memo/expr.go#L1357)):*
> ```Go
> 
> 	// WithID identifies the buffer for the mutation input in the original
> 	// expression tree. 0 if the cascade does not require input.
> ```

nit: this is never 0 for after triggers, correct?
___
*[`pkg/sql/opt/memo/interner.go` line 540 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tGS0s1zMg-eFdoUyc:-O9tGS0s1zMg-eFdoUyd:bd937hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a1698dde8b65b904e43f4936b7a82b258b246e/pkg/sql/opt/memo/interner.go#L540)):*
> ```Go
> }
> 
> func (h *hasher) HashAfterTriggers(val *AfterTriggers) {
> ```

nit: add unit tests for this in `interner_test.go`
___
*[`pkg/sql/opt/memo/interner.go` line 1026 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tGfGN1bs6v8avLein:-O9tGfGN1bs6v8avLeio:bd937hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a1698dde8b65b904e43f4936b7a82b258b246e/pkg/sql/opt/memo/interner.go#L1026)):*
> ```Go
> }
> 
> func (h *hasher) IsAfterTriggersEqual(l, r *AfterTriggers) bool {
> ```

nit: add unit tests for this in `interner_test.go`
___
*[`pkg/sql/opt/optbuilder/insert.go` line 755 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tZL771dGLo3zqUurU:-O9tZL771dGLo3zqUurV:be2wofw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/insert.go#L755)):*
> ```Go
> 	mb.buildFKChecksForInsert()
> 
> 	mb.buildRowLevelAfterTriggers(opt.InsertOp)
> ```

Does the build order of after triggers in relation to FK checks affect the behavior?
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 301 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9taK_rDmz8fpRAGayd:-O9taK_rDmz8fpRAGaye:b-hu8qsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/trigger.go#L301)):*
> ```Go
> 		return triggers[i].Name() < triggers[j].Name()
> 	}
> 	sort.Slice(triggers, less)
> ```

Didn't `getRowLevelTriggers` already sort the triggers?
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 365 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tatzm-Xwbf-I3x6pe:-O9tatzm-Xwbf-I3x6pf:b-qobxc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/trigger.go#L365)):*
> ```Go
> // getEventsToMatchForMutation returns the set of trigger events that should be
> // matched for the given mutation operator.
> func (mb *mutationBuilder) getEventsToMatchForMutation(
> ```

Can this be used for BEFORE trigger too, or just AFTER triggers?
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 783 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9t_1bvD-pgDnx6KBol:-O9t_1bvD-pgDnx6KBom:b-7ca3qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/trigger.go#L783)):*
> ```Go
> 		}
> 	}
> 	if neededTriggers.Len() == 0 {
> ```

nit: use `.Empty()` instead - it's more efficient than `Len` when the set is not empty.
___
*[`pkg/sql/sem/tree/create_trigger.go` line 163 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tcIOf24m7TeNIGCTP:-O9tcIOf24m7TeNIGCTQ:b-xyuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/sem/tree/create_trigger.go#L163)):*
> ```Go
> 
> // Contains returns true if the set contains the given TriggerEventType value.
> func (s *TriggerEventTypeSet) Contains(t TriggerEventType) bool {
> ```

Did you change this type because of the GoLand warning that the type has methods on both value and pointer receivers? We don't follow that guidance, and IMO it's not good advice in general. I think a value receiver makes more sense here.
___
*[`pkg/ccl/backupccl/testdata/backup-restore/triggers` line 258 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tfkkoD82msjfzlKVF:-O9tfkkoD82msjfzlKVG:bibclhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/backupccl/testdata/backup-restore/triggers#L258)):*
> ```
> SELECT nextval('sc1.sq1'::REGCLASS)
> ----
> 10
> ```

Are these changes from a separate PR?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2043 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tgB5T34gpYX9ncmPV:-O9tgB5T34gpYX9ncmPW:biq6q14) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2043)):*
> ```
> 
> # ==============================================================================
> # Test row-level AFTER triggers with a WHERE clause.
> ```

nit: "WHERE" => "WHEN"
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tgPm38nonT94p-aVv:-O9tgPm38nonT94p-aVw:b-3xa9l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2128)):*
> ```
> CREATE FUNCTION g() RETURNS TRIGGER LANGUAGE PLpgSQL AS $$
>   BEGIN
>     RAISE NOTICE '% % ON %: % -> %', TG_WHEN, TG_OP, TG_TABLE_NAME, OLD, NEW;
> ```

These built-in variables like `TG_TABLE_NAME` come in handy for testing!
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2474 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tlaMZDuyoaIOyurea:-O9tlaMZDuyoaIOyureb:b-oramyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2474)):*
> ```
> CREATE TRIGGER bar AFTER INSERT OR UPDATE ON xy FOR EACH ROW EXECUTE FUNCTION g();
> 
> # Fist, all BEFORE triggers are executed. Then, the mutation is executed.
> ```

nit: "Fist" => "First"

**Review by mw5h — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 9 of 9 files at r2, 35 of 35 files at r6, 23 of 23 files at r7, 7 of 7 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-:-O9vOZMv04BTrwWotm1X:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/util.go` line 802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9vEdUUBg2azrn9QiHI:-O9vEdUUBg2azrn9QiHJ:b8z6270) ([raw file](https://github.com/cockroachdb/cockroach/blob/5492e1b5b2ad9197d065423764824e3d3fa2db37/pkg/sql/opt/optbuilder/util.go#L802)):*
> ```Go
> 
> // remapColumns remaps the given column according to the given ColMap.
> func remapColumns(cols opt.ColList, m opt.ColMap) opt.ColList {
> ```

ColList has a method called CopyAndMaybeRemapColumns() that only differs in what to do on a map miss. If feels like these could be either combined, parameterized with a functor, or at least colocated.

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

> A test that shows that AFTER triggers observe the effects of BEFORE triggers would be good to have. I don't think there are any here.

Good idea, Done.

> What happens when an AFTER trigger modifies a row? Does it error, or are the change lost?

The return value for an AFTER trigger is ignored, basically. Some of the existing tests actually do this out of convenience, so that BEFORE and AFTER triggers can use the same trigger function. I'll add a test specifically to address this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-:-O9ujxEX2-8Mrf2F3cwD:b-ww9lfq)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @mw5h)

___
*[`pkg/sql/distsql_physical_planner.go` line 986 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tJNWs3SH1Mgvlmwxw:-O9vTZ_g7jOw5CZTHvVV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb7f608b58a1ae1c7a55c355ede46cad751a6d3/pkg/sql/distsql_physical_planner.go#L986)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: the `vectorized` name for the `bool` was helpful documentation, I think it's worth keeping.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_running.go` line 2103 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9teFUXBWtkCg7Vw7gT:-O9uOKAaCteZuCcV3BFf:bnox7xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/sql/distsql_running.go#L2103)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Rename to include Triggers or PostQuery (feel free to do this in a future PR - there's probably lots of renaming to be done over time).
</blockquote></details>

Yeah there's probably other cases, but I'll rename this one in the third commit.
___
*[`pkg/sql/opt/exec/execbuilder/cascades.go` line 22 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tJxl09vSOIZ0qRD1z:-O9uP1NZ8QXTRKcmcDRt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb7f608b58a1ae1c7a55c355ede46cad751a6d3/pkg/sql/opt/exec/execbuilder/cascades.go#L22)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: should we name this postQueryBuilder instead? Also, should we rename the file?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/memo/expr.go` line 1357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tGEu-1EgOGcnaAz1B:-O9uP_8A6eSf6Mja3suc:b-tgyrgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a1698dde8b65b904e43f4936b7a82b258b246e/pkg/sql/opt/memo/expr.go#L1357)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: this is never 0 for after triggers, correct?
</blockquote></details>

Good point, fixed the comment.
___
*[`pkg/sql/opt/memo/interner.go` line 540 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tGS0s1zMg-eFdoUyc:-O9uRTRi-ZAueiK3P0mV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a1698dde8b65b904e43f4936b7a82b258b246e/pkg/sql/opt/memo/interner.go#L540)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add unit tests for this in `interner_test.go`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/memo/interner.go` line 1026 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tGfGN1bs6v8avLein:-O9uRWqs59d76TS5ZUEN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a1698dde8b65b904e43f4936b7a82b258b246e/pkg/sql/opt/memo/interner.go#L1026)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add unit tests for this in `interner_test.go`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/insert.go` line 755 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tZL771dGLo3zqUurU:-O9uRaJ15Uo2b5JFt2kG:b-jx95uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/insert.go#L755)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does the build order of after triggers in relation to FK checks affect the behavior?
</blockquote></details>

No, checks and cascades are executed before AFTER triggers either way. I think it makes things more clear if we build in that same order, though.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 301 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9taK_rDmz8fpRAGayd:-O9uSN47Dz_ssoQ0xQUh:b-ekaoj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/trigger.go#L301)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Didn't `getRowLevelTriggers` already sort the triggers?
</blockquote></details>

Good catch, removed it.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 365 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tatzm-Xwbf-I3x6pe:-O9uSh6K9ygSP3ubbUYy:b-tneus7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/trigger.go#L365)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can this be used for BEFORE trigger too, or just AFTER triggers?
</blockquote></details>

This is for AFTER triggers specifically. BEFORE triggers have to be built at specific locations in the query plan - in particular, INSERT and UPDATE triggers are invoked at different times for UPSERT operations. So we can't do this simple mapping from mutation -> applicable triggers for BEFORE triggers.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 783 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9t_1bvD-pgDnx6KBol:-O9uX-1FArH3qo447xmy:b-896fiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/opt/optbuilder/trigger.go#L783)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: use `.Empty()` instead - it's more efficient than `Len` when the set is not empty.
</blockquote></details>

Done,
___
*[`pkg/sql/opt/optbuilder/util.go` line 802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9vEdUUBg2azrn9QiHI:-O9vVWEd1hCoLtwxDJgU:b-kbalap) ([raw file](https://github.com/cockroachdb/cockroach/blob/5492e1b5b2ad9197d065423764824e3d3fa2db37/pkg/sql/opt/optbuilder/util.go#L802)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

ColList has a method called CopyAndMaybeRemapColumns() that only differs in what to do on a map miss. If feels like these could be either combined, parameterized with a functor, or at least colocated.
</blockquote></details>

I've combined the two in a `remapColumnsImpl` function exposed via `CopyAndMaybeRemapColumns` and `RemapColumns`.
___
*[`pkg/sql/sem/tree/create_trigger.go` line 163 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tcIOf24m7TeNIGCTP:-O9uXJ4b7jGrfs4RkcAE:bstgzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c335c94fe0456a7c060265ba7d75753a13e344b/pkg/sql/sem/tree/create_trigger.go#L163)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Did you change this type because of the GoLand warning that the type has methods on both value and pointer receivers? We don't follow that guidance, and IMO it's not good advice in general. I think a value receiver makes more sense here.
</blockquote></details>

Yeah that was why. I changed it to use the value receiver for `Contains`.
___
*[`pkg/ccl/backupccl/testdata/backup-restore/triggers` line 258 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tfkkoD82msjfzlKVF:-O9uXUb24svrmC4vuabw:bi2nceq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/backupccl/testdata/backup-restore/triggers#L258)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Are these changes from a separate PR?
</blockquote></details>

No - it's just that the trigger is actually being fired now.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2043 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tgB5T34gpYX9ncmPV:-O9uXbrh6ltgr5r9v2IA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2043)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "WHERE" => "WHEN"
</blockquote></details>

Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tgPm38nonT94p-aVv:-O9uXdI4CPa0Op67AEj2:b-ya9six) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2128)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

These built-in variables like `TG_TABLE_NAME` come in handy for testing!
</blockquote></details>

Yeah, it's pretty nice!
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2474 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/133143#-O9tlaMZDuyoaIOyurea:-O9uXihCC0NR6_1qUF98:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3d57442c84643a4133ea766a99f2d1646d8e3c/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2474)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "Fist" => "First"
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Pull request merged**
