### PR TITLE
distsqlrun: add NoopProcessor benchmark

### PR DESCRIPTION
**Pull request by jordanlewis**
It's nice to be able to see how fast the DistSQL processor interface itself is.

```
name             time/op
Noop/cols=1-8     3.23ms ± 2%
Noop/cols=2-8     4.56ms ± 2%
Noop/cols=4-8     6.53ms ± 5%
Noop/cols=16-8    23.4ms ± 2%
Noop/cols=256-8    407ms ± 6%

name             speed
Noop/cols=1-8    162MB/s ± 2%
Noop/cols=2-8    230MB/s ± 2%
Noop/cols=4-8    321MB/s ± 5%
Noop/cols=16-8   359MB/s ± 2%
Noop/cols=256-8  331MB/s ± 5%
```

### CODE REVIEW

**Comment by asubiotto** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/distsqlrun/noop_test.go, line 31 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477#-L9GmZhL-Vgd0ARxjPQj:-L9GmZhL-Vgd0ARxjPQk:bm1p8lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/15476e35f534f99c0a32bb9da722fd5116604248/pkg/sql/distsqlrun/noop_test.go#L31)):*
> ```Go
> 
> 	ctx := context.Background()
> 	st := cluster.MakeTestingClusterSettings()
> ```

I think you can just embed this in `&FlowCtx{...`

---

*[pkg/sql/distsqlrun/noop_test.go, line 52 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477#-L9Gmpm1ELiUSfLfZhl-:-L9Gmpm1ELiUSfLfZhl0:b-lh53ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/15476e35f534f99c0a32bb9da722fd5116604248/pkg/sql/distsqlrun/noop_test.go#L52)):*
> ```Go
> 			b.ResetTimer()
> 			for i := 0; i < b.N; i++ {
> 				d, err := newNoopProcessor(flowCtx, input, post, &RowDisposer{})
> ```

Probably good to be consistent here and extract the `RowDisposer` to where `post` is allocated.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477)*

**Comment by asubiotto** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/noop_test.go, line 31 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477#-L9GmZhL-Vgd0ARxjPQj:-L9Gn9gg-6BaTq5LlNBi:b-nzreev) ([raw file](https://github.com/cockroachdb/cockroach/blob/15476e35f534f99c0a32bb9da722fd5116604248/pkg/sql/distsqlrun/noop_test.go#L31)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you can just embed this in `&FlowCtx{...`
</blockquote></details>

Nevermind, didn't see the use in `evalCtx := ...`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477)*

**Comment by petermattis** [comment]
Can you include the benchmark results (using `benchstat`)? Inquiring minds want to know and are too lazy to run the benchmark themselves.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477#-:-L9GnSMUExEPSRyxOMd7:bch55ku)*

**Comment by jordanlewis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/noop_test.go, line 52 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477#-L9Gmpm1ELiUSfLfZhl-:-L9H6nb78rl7DtNlOc2t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/15476e35f534f99c0a32bb9da722fd5116604248/pkg/sql/distsqlrun/noop_test.go#L52)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Probably good to be consistent here and extract the `RowDisposer` to where `post` is allocated.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477)*

**Comment by asubiotto** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24477#-:-L9H7ROV2IswPeTUTz-g:bnfp4nl)*

**Pull request merged**
