### PR TITLE
docs: move the contribution guide to the external wiki

### PR DESCRIPTION
**Pull request by knz**
Discussed with @jordanlewis: there was previously "split brain"
between the repo and the wiki about many aspects of code
contributions.

We have decided that the wiki becomes authoritative and this PR
moves the last pieces still in the repo to the wiki, leaving
links behind.

Release note (general change): materials on How to Contribute to
CockroachDB are now moved to the public wiki at wiki.crdb.io.

### CODE REVIEW

**Comment by kenliu** [comment]
SGTM. let's make sure that any references to this doc from our internal onboarding docs point to the wiki as well (if not done already).

**Review by kenliu — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41542)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by knz** [comment]
tfyr!

bors r+

**Pull request merged**
