### PR TITLE
ui: use relative URI paths and send cookies in fetch requests

### LINKED ISSUE #13981: ui: support operating behind reverse proxy
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I would like to run CockroachDB's Admin UI behind a reverse proxy at a base URI of `/cockroach`. In a perfect world I would like to have all paths in the response be relative. In the spirit of pragmatism I'd gladly settle for some way to configure a global `/cockroach` prefix.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

Blocker. No workaround.

3. Provide any additional detail on your proposed use case for this feature.

According to https://tools.ietf.org/html/rfc7320#section-2.3

> For example, an application ought not specify a fixed URI path "/myapp", since this usurps the host's control of that space.

### PR DESCRIPTION
**Pull request by tamird**
This allows the Admin UI to be served from behind an authenticating
reverse proxy.

Fixes #13981.
Closes #14017.

cc @gpaul

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14039)

### CODE REVIEW

**Comment by benesch** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/app/redux/uiData.spec.ts, line 334 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14039#-Kep5S6XOSCsAP-UGRfY:-Kep5S6XOSCsAP-UGRfZ:b-dm6ed9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3d5cef54be32cb24a54e468f0593ea95c117b5d/pkg/ui/app/redux/uiData.spec.ts#L334)):*
> ```XML
>     it("correctly saves UIData", function() {
>       fetchMock.mock({
>         matcher: api.API_PREFIX + `/uidata`,
> ```

You use concatenation here but string interpolation `${var}` below. Particularly weird because you're using template literal quotes. Standardize on string interpolation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14039)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/app/redux/uiData.spec.ts, line 334 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14039#-Kep5S6XOSCsAP-UGRfY:-Kep7Dy_wE7V33wnuiaW:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3d5cef54be32cb24a54e468f0593ea95c117b5d/pkg/ui/app/redux/uiData.spec.ts#L334)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You use concatenation here but string interpolation `${var}` below. Particularly weird because you're using template literal quotes. Standardize on string interpolation?
</blockquote></details>

Good call, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14039)*

**Comment by maxlang** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14039#-:-Kep8AIGPUsM7IvDY7bt:bnfp4nl)*

**Comment by benesch** [comment]
Is it worth adding/easily possible to add a test for this?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14039#-:-Kep7sI4yJKyOWZtTofj:b20b3p5)*

**Comment by tamird** [comment]
Probably worth it, but it ain't gonna be easy (unless you have some ideas).

**Comment by mrtracy** [comment]
The only way I can think of to test this scenario fully would be to actually set up a reverse-proxy situation in an acceptance test, but then you have to make sure that the Admin UI renders correctly; we don't have ANY test that does that end-to-end.

**Comment by mrtracy** [comment]
LGTM

**Comment by gpaul** [comment]
Thanks for this :+1:

**Pull request merged**
