### PR TITLE
ui: improve tooltip UX with text updates

### LINKED ISSUE #79018: Update tool tip text for Rows Read on the Statements overview page
We should clarify the tool tip on the Statements overview page. This column represents the average (mean) rows read per execution of the statement fingerprint including the standard deviation. 

Jira issue: CRDB-14501

### LINKED ISSUE #81248: Fix tooltips in Transactions and Statements pages to refer to date range instead of time interval
Tooltips in many of the columns are referring to a time interval and link to a location (https://www.cockroachlabs.com/docs/stable/ui-statements-page.html#time-interval) and  that no longer exists.

Screen Shot 2022-05-13 at 1 19 36 PM

That link should say date range and go to https://www.cockroachlabs.com/docs/stable/ui-statements-page.html#date-range instead.

The tooltips on the Transactions page should go to https://www.cockroachlabs.com/docs/stable/ui-transactions-page.html#date-range. They are currently pointing to the Statements page.

Jira issue: CRDB-15270

### LINKED ISSUE #81374: Update "Retries" column tool tip on the Statements and Transactions tabs
We should update the "Retries" column tool tip on the Statements and Transactions page to clearly state this counts internal/automatic retries.

Jira issue: CRDB-15214

### LINKED ISSUE #83256: Update the tool tip for the Statement Time column on the statement overview page
The current tool tip states the following,

"Average planning and execution time of statements with this fingerprint within the last hour or specified time interval. The gray bar indicates the mean latency. The blue bar indicates one standard deviation from the mean."

We should clearly call out that Statement Time does not include the time it takes to stream results back to the client. 

**"Average planning and execution time of statements with this fingerprint within the specified time interval. The gray bar indicates the mean latency. The blue bar indicates one standard deviation from the mean. This time does not include the time it takes to stream results back to the client."**

With this issue, we should also update the docs which can go into detail on how the time to stream back results to the client (network communication) is not included in the Statement Time; however, _if_ the buffer fills up and the statement execution blocks on the client consuming the results, the time will implicitly be included. We should also link to the buffer details as well.

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://github.com/cockroachdb/cockroach/issues/81374.
Fixes https://github.com/cockroachdb/cockroach/issues/83256.
Fixes https://github.com/cockroachdb/cockroach/issues/81248.
Fixes https://github.com/cockroachdb/cockroach/issues/79018.

Note the following:

- The updates resolving https://github.com/cockroachdb/cockroach/issues/79018 effectively revert the tooltip text for Rows Read to the original wording (which [was updated for accuracy](https://github.com/cockroachdb/cockroach/commit/e379e9d215bf5eaf9abd2c871867dd4a68afb953#diff-492398441e971e355a687a4ce333a9766e2195287d0227682444d5dc0eb7ee1a)). I assume this is okay. @kevin-v-ngo
- The updates resolving https://github.com/cockroachdb/cockroach/issues/81248 do not in fact refer to the time intervals as date ranges, as this language is misleading (a 1h interval is an interval and not a date range). Instead, this update just removes the anchor and the link to the non-existent Interval Range section of https://www.cockroachlabs.com/docs/stable/ui-statements-page.html. We may want to consider updating the docs to call the "time picker" data type a time interval and not a date range. This appears to have been the case in previous releases (https://www.cockroachlabs.com/docs/v21.1/ui-statements-page#time-interval). @stbof 

Release note (ui change): Updated tooltips on the Statements and
Transactions pages in the DB Console for improved UX.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
Smaller nit on your commit message, otherwise :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83420#-:-N5aBH3z6VoUUFIBb73X:b7iv95e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83420#-N5aB6q18Tlp5BT7cVIp):*
nit: your commit message should also have the "Fixes..."

your release note should state there were updates on tooltips

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83420)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83420#-N5aB6q18Tlp5BT7cVIp):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: your commit message should also have the "Fixes..."

your release note should state there were updates on tooltips
</blockquote></details>

Fixed!

**Comment by stbof** [comment]
I'm reverting _date range_ to _time interval_ throughout in the docs.  If we no longer want to use _date range_, shouldn't this UX label be updated as well
Screen Shot 2022-07-13 at 9 10 47 AM
.

**Pull request merged**
