### PR TITLE
storage: Refactor pagination for the Get command into the MVCC layer

### PR DESCRIPTION
**Pull request by KaiSun314**
Informs: https://github.com/cockroachdb/cockroach/issues/77228

Refactor key and byte pagination for the Get command into the MVCC layer Previously, pagination was done in pkg/kv/kvserver/batcheval/cmd_get.go, but to ensure consistency in where pagination logic is located across all commands, we move the pagination logic for the Get command to the MVCC layer where the pagination logic for most other commands is. This also enables better parameter testing in the storage package since we can leverage e.g. data-driven tests like TestMVCCHistories.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
cc @nicktrav

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/storage/mvcc.go` line 1027 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLNcRls-wnhCD3Lwowi:-NLNcRls-wnhCD3Lwowj:b-rkfqpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff430b958d61474681edd06521fa045c6398696/pkg/storage/mvcc.go#L1027)):*
> ```Go
> 		//
> 		// This mirrors the logic in MVCCScan, though the logic in MVCCScan is
> 		// slightly lower in the stack.
> ```

stale comment "This mirrors ..."

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 1027 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLNcRls-wnhCD3Lwowi:-NLQuI3yD6bcx5XQRF5G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff430b958d61474681edd06521fa045c6398696/pkg/storage/mvcc.go#L1027)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

stale comment "This mirrors ..."
</blockquote></details>

Done.

**Comment by sumeerbhola** [comment]
The storage changes are fine with me, but added @nvanbenschoten to give final approval.

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314 and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLRb9798D2GE1ZSludA:-NLRb9798D2GE1ZSludB:b-iz6h9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7daa997a54348b0afd8cd0960c157afade5622/pkg/storage/mvcc.go#L917)):*
> ```Go
> 	// TargetBytes limit.
> 	AllowEmpty bool
> 	// Reply is a pointer to the Get response object.
> ```

This feels like a layering violation. MVCC is not currently aware of `roachpb.Response` types. I don't think we want it to be.

Instead of pushing a pointer to the response to be modified into `MVCCGet`, we could return the information we need to populate this response, like we do with `MVCCScan`. Then we keep the decision of how to use this information (e.g. to populate a `*roachpb.GetResponse`) up in `kv/kv/server/batcheval`.

That might mean creating a `MVCCGetResult` struct, which feels like a nice change.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLRb9798D2GE1ZSludA:-NLS5GQp1LkTA_X9i5l1:bgs8rdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7daa997a54348b0afd8cd0960c157afade5622/pkg/storage/mvcc.go#L917)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This feels like a layering violation. MVCC is not currently aware of `roachpb.Response` types. I don't think we want it to be.

Instead of pushing a pointer to the response to be modified into `MVCCGet`, we could return the information we need to populate this response, like we do with `MVCCScan`. Then we keep the decision of how to use this information (e.g. to populate a `*roachpb.GetResponse`) up in `kv/kv/server/batcheval`.

That might mean creating a `MVCCGetResult` struct, which feels like a nice change.
</blockquote></details>

True agreed, I have migrated to returning a `MVCCGetResult` struct containing the fields to populate the Get response

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314 and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLRb9798D2GE1ZSludA:-NLS9QWR6vC3FeYIlF8y:b5bhc52) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7daa997a54348b0afd8cd0960c157afade5622/pkg/storage/mvcc.go#L917)):*
<details><summary><i>Previously, KaiSun314 (Kai Sun) wrote…</i></summary><blockquote>

True agreed, I have migrated to returning a `MVCCGetResult` struct containing the fields to populate the Get response
</blockquote></details>

Should we include the `*roachpb.Value` and `*roachpb.Intent` in the `MVCCGetResult` as well? That's what we do in `MVCCScanResult`.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLRb9798D2GE1ZSludA:-NLTF7Fy2KvpyYnMMHv1:bh2c2af) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb7daa997a54348b0afd8cd0960c157afade5622/pkg/storage/mvcc.go#L917)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we include the `*roachpb.Value` and `*roachpb.Intent` in the `MVCCGetResult` as well? That's what we do in `MVCCScanResult`.
</blockquote></details>

Yep that sounds great, added `Value *roachpb.Value` and `Intent *roachpb.Intent` to `MVCCGetresult`

**Review by nvb — COMMENTED** [review]
> Reviewed 19 of 23 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314 and @sumeerbhola)

___
*[`-- commits` line 9 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLTiL-NAVi2KGQ3QCF1):*
Did you mean for these to be two different commits?
___
*[`pkg/kv/kvserver/replica.go` line 1808 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLTiroaAi1t9xiWMIc0:-NLTiroaAi1t9xiWMIc1:bbhvu0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b7bf08a6289484b595d0777459161e0f90b1d5f/pkg/kv/kvserver/replica.go#L1808)):*
> ```Go
> 	desc := r.descRLocked()
> 	descKey := keys.RangeDescriptorKey(desc.StartKey)
> 	res, err := storage.MVCCGet(ctx, r.Engine(), descKey, hlc.MaxTimestamp,
> ```

`intentRes`
___
*[`pkg/kv/kvserver/replica.go` line 1815 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLTizfk8G6q1isK-nE_:-NLTizfk8G6q1isK-nEa:b-y8cmoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b7bf08a6289484b595d0777459161e0f90b1d5f/pkg/kv/kvserver/replica.go#L1815)):*
> ```Go
> 		return false, nil
> 	}
> 	getRes, err := storage.MVCCGetAsTxn(
> ```

`valRes`
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 538 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLTi_c200ao7TDjp30b:-NLTi_c200ao7TDjp30c:bl75805) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84236f521191cee32b587ddeb5bd0d83f7e6e52/pkg/kv/kvserver/replica_rangefeed.go#L538)):*
> ```Go
> 		// Read the previous value from the prev Reader. Unlike the new value
> 		// (see handleLogicalOpLogRaftMuLocked), this one may be missing.
> 		prevVal, _, _, err := storage.MVCCGet(
> ```

In cases where the variable names before carried some context to help readers understand the code, we should try to incorporate that into the new name. For instance, it would be clearer if this was `prevValRes`. I left comments about this in a few other places.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`-- commits` line 9 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLTiL-NAVi2KGQ3QCF1):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean for these to be two different commits?
</blockquote></details>

Oh yep I wanted to split into two commits to make it easier to read and review. One commit refactors `MVCCGetResult` into the return values and one commit pushes pagination for `Get` into MVCC.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 538 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-NLTi_c200ao7TDjp30b:-NLYbkfs4jgP0HM5U8k2:b-ivqbq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84236f521191cee32b587ddeb5bd0d83f7e6e52/pkg/kv/kvserver/replica_rangefeed.go#L538)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

In cases where the variable names before carried some context to help readers understand the code, we should try to incorporate that into the new name. For instance, it would be clearer if this was `prevValRes`. I left comments about this in a few other places.
</blockquote></details>

Done, incorporated previous variable names into the new name

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 11 of 15 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94698#-:-NLb-d6l8stsRcQokfaG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by KaiSun314** [comment]
Thank you so much for the review Nathan and Sumeer!

**Pull request merged**
