### PR TITLE
sql: plumb locking durability into Get/Scan/ReverseScan requests

### LINKED ISSUE #100194: sql: acquire replicated locks on explicit SELECT FOR UPDATE
Once we implement replicated key-level locks (https://github.com/cockroachdb/cockroach/issues/100193), we should then switch explicit SELECT FOR {SHARE/UPDATE} over to acquire locks with a Replicated durability.

Implicit uses of SELECT FOR UPDATE as part of mutation statements can continue to acquire cheaper, best-effort unreplicated locks.

Jira issue: CRDB-26582

Epic CRDB-25322

### PR DESCRIPTION
**Pull request by michae2**
**execinfrapb: remove IndexSkipTableReaderSpec**

The `indexSkipTableReader` was deleted in #51178 but the distsql spec has stuck around for a few versions. I think we can delete the spec now, too. If someone wants to dust off #39668 they can bring it back.

Release note: None

**sql: plumb locking durability into Get/Scan/ReverseScan requests**

Building on top of #110201, plumb locking durability from the optimizer to creation of Get/Scan/ReverseScan requests in txnKVFetcher and txnKVStreamer.

Also add a version gate for usage of guaranteed-durable locking.

Fixes: #100194

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
First commit is https://github.com/cockroachdb/cockroach/pull/110879 and can be ignored. Let's see whether CI says this is ready.

**Review by yuzefovich — COMMENTED** [review]
Seems good to me, I only have a few nits.

> Reviewed 25 of 25 files at r3, 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-:-NfMRTN_AIu4qgHmpJ7h:b-9mqqx4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @michae2)

___
*[`pkg/sql/insert_fast_path.go` line 193 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMPNSu7XJLhdZ82wBh:-NfMPNSu7XJLhdZ82wBi:b-sszzuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/insert_fast_path.go#L193)):*
> ```Go
> 		}
> 		lockStrength := row.GetKeyLockingStrength(descpb.ToScanLockingStrength(c.Locking.Strength))
> 		lockDurability := row.GetKeyLockingDurability(descpb.ToScanLockingDurability(c.Locking.Durability))
> ```

nit: for consistency perhaps move it after `lockWaitPolicy`?
___
*[`pkg/sql/row/locking.go` line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMQmAl9EPftaqzwinv:-NfMQmAl9EPftaqzwinw:b-hox69d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/row/locking.go#L65)):*
> ```Go
> }
> 
> // GetWaitPolicy returns the configured lock wait policy to use for key-value
> ```

nit: needs an update.
___
*[`pkg/sql/logictest/testdata/logic_test/fk_read_committed` line 3 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMQsta-_AHjAJhKhoZ:-NfMQstbDxqnPodsHrzZ:bsu43m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/logictest/testdata/logic_test/fk_read_committed#L3)):*
> ```
> # LogicTest: !local-mixed-22.2-23.1
> 
> # statement ok
> ```

Was it intentional to comment this out?
___
*[`pkg/sql/logictest/testdata/logic_test/read_committed` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMRKF76N1o9MBnHYEr:-NfMRKF76N1o9MBnHYEs:b-b9c0r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/logictest/testdata/logic_test/read_committed#L37)):*
> ```
> COMMIT
> 
> # Use SELECT FOR UPDATE under read committed isolation.
> ```

Can we / do we have some EXPLAIN tests that show that SFU is being used?

**Review by arulajmani — APPROVED** [review]
:lgtm: 

I only have a few nits about the ordering of these fields. Other than that, it's great to see all this wired up! 

> Reviewed 14 of 14 files at r1, 25 of 25 files at r3, 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-:-NfOFk_b2WxQUy8qGYRR:b-jj6azq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/execinfrapb/processors_sql.proto` line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfOEbG_Ekg6tDb1cVA_:-NfOEbG_Ekg6tDb1cVAa:b-397385) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/execinfrapb/processors_sql.proto#L125)):*
> ```proto
> 
>   // Indicates the row-level locking durability to be used by the scan.
>   optional sqlbase.ScanLockingDurability locking_durability = 23 [(gogoproto.nullable) = false];
> ```

nit: Should we move this right below `locking_strength`, given these two fields are related?

Same for below.
___
*[`pkg/sql/row/fetcher.go` line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfOEokX38dOuTNk7xcZ:-NfOEokX38dOuTNk7xc_:b-p7rxm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/row/fetcher.go#L302)):*
> ```Go
> 	// locks held by other active transactions.
> 	LockWaitPolicy descpb.ScanLockingWaitPolicy
> 	// LockDurability represents the row-level locking durability to use.
> ```

nit: Similar to my comments on the proto definition, should we pull this right below `LockStrength` as well?
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfOF2PL4lv4RYrAGRtL:-NfOF2PL4lv4RYrAGRtM:b-a9i9dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/row/kv_batch_fetcher.go#L184)):*
> ```Go
> 	lockWaitPolicy lock.WaitPolicy
> 	// lockDurability represents the locking durability to use.
> 	lockDurability lock.Durability
> ```

nit: here as well.

**Review by nvb — APPROVED** [review]
:lgtm:

Now that https://github.com/cockroachdb/cockroach/pull/111349 is merged and the durable locking requests are hooking into the storage-level APIs, this PR should be the last thing blocking true replicated lock usage, either in RC transactions or even in SSI transactions with the `enable_durable_locking_for_serializable` session variable. Very exciting!

> Reviewed 25 of 25 files at r2, 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-:-NfOW-NLBM3dY82YG68-:beg0uzh)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-:-NfPHdsf1R60MwuqhmaZ:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @nvanbenschoten, and @yuzefovich)

___
*[`pkg/sql/insert_fast_path.go` line 193 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMPNSu7XJLhdZ82wBh:-NfPGMX90zyXUtWGW7hZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/insert_fast_path.go#L193)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: for consistency perhaps move it after `lockWaitPolicy`?
</blockquote></details>

Done.
___
*[`pkg/sql/execinfrapb/processors_sql.proto` line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfOEbG_Ekg6tDb1cVA_:-NfPGO8YDhWOO-6qqaZs:b-ari7l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/execinfrapb/processors_sql.proto#L125)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Should we move this right below `locking_strength`, given these two fields are related?

Same for below.
</blockquote></details>

It's totally arbitrary, but based on the ordering in [opt.Locking](https://github.com/cockroachdb/cockroach/blob/2111b61b2d7c789bc03b1e9392062df80c779075/pkg/sql/opt/locking.go#L18) I've been mostly putting the three in [strength, wait policy, durability] order (or [strength, durability] order when it's just those two).
___
*[`pkg/sql/row/locking.go` line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMQmAl9EPftaqzwinv:-NfPHGzU44Gz8SbkMtXz:bohy0gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/row/locking.go#L65)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: needs an update.
</blockquote></details>

Gah, thanks. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/fk_read_committed` line 3 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMQsta-_AHjAJhKhoZ:-NfPHKAi4oVmw-E1u5uL:b-cota09) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/logictest/testdata/logic_test/fk_read_committed#L3)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Was it intentional to comment this out?
</blockquote></details>

No, thanks. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/read_committed` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-NfMRKF76N1o9MBnHYEr:-NfPHNbD5zN6-E_sgeV7:bk82zjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07db68a824bdc56cd1690087138724606c7cb33/pkg/sql/logictest/testdata/logic_test/read_committed#L37)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Can we / do we have some EXPLAIN tests that show that SFU is being used?
</blockquote></details>

Oh, yes. We already had some `EXPLAIN (OPT)` tests but I've added `EXPLAIN (VERBOSE)` variations (which didn't work before!).

**Review by yuzefovich — APPROVED** [review]
The failure looks concerning, but the changes :lgtm:

> Reviewed 38 of 38 files at r5, 41 of 41 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110945#-:-NfRYUvT6uTLAwUAR6k1:b-99zrwd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2)

**Comment by nvanbenschoten** [comment]
@michae2 the CI failure indicates that we are issuing a Get or Scan request with a `KeyLockingStrength` of `None` and a `KeyLockingDurability` of `Replicated`. This should be illegal, though KV should probably be handling it better instead of panicking.

**Comment by michae2** [comment]
> @michae2 the CI failure indicates that we are issuing a Get or Scan request with a `KeyLockingStrength` of `None` and a `KeyLockingDurability` of `Replicated`. This should be illegal, though KV should probably be handling it better instead of panicking.

I see, it's simply the current implementation of `GetKeyLockingStrength`, which @arulajmani fixes in https://github.com/cockroachdb/cockroach/pull/109638. This PR will need to wait.

**Comment by michae2** [comment]
Failure is an unrelated flake, so I'll go ahead. TFTRs!

bors r=arulajmani,nvanbenschoten,yuzefovich

**Pull request merged**
