### PR TITLE
localmetrics: add local Grafana timeseries tooling

### PR DESCRIPTION
**Pull request by tbg**
Add a docker-compose setup that starts a local Grafana backed by a local
Postgres along with a helper that can import timeseries data into the
Postgres instance which the Grafana instance is configured to display.

Consult scripts/localmetrics/README.md for a quickstart.

This isn't a valuable debug tool just yet, but with a bit of elbow
grease, I believe that it will become an invaluable tool to avoid
the many back-and-forth round-trips we have these days with customers
to exchange screenshots of the Admin UI.

To make it truly useful, we need

1. [timeseries in debug.zip](#50432)
2. auto-generate dashboards from `./pkg/ts/catalog`.

Both are totally doable, and even without 2) there's already some
utility as it's easy to make ad-hoc panels in Grafana thanks to the
built-in query builder.

Finally, here's a screenshot of the one panel included here right now,
the rate of DistSender batches, taken from `sample.csv`.

image

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

This is neat!

`sample.csv` is pretty large. Is it it worth including?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50702#-:-MAlhXDp3orOcejYqntT:b7e8v6h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lunevalex and @petermattis)

**Comment by tbg** [comment]
> sample.csv is pretty large. Is it it worth including?

Don't think it would've mattered, but I moved it to a gist instead, so it's gone now.

TFTR

bors r=petermattis

**Comment by tbg** [comment]
bors r=petermattis

Lint

**Comment by tbg** [comment]
lint fails with:

> [Ensure generated code is up-to-date] pkg/sql/colexec/overloads_test_utils.eg.go:11:2: can’t find import: “github.com/cockroachdb/cockroach/pkg/server/telemetry”

Probably @jordanlewis knows what to make of that, but it doesn't seem to be this PR's fault.

**Comment by tbg** [comment]
bors r=petermattis

master is probably fixed now.

**Comment by tbg** [comment]
bors r=petermattis
lint

**Pull request merged**
