### PR TITLE
storage: do not allow sync intent resolution for RangeLookup requests

### LINKED ISSUE #17760: storage: SCATTER hangs during RangeLookup
I'm periodically seeing an `ALTER TABLE ... SCATTER` hang indefinitely. I finally got around to debugging this and the blockage is during a `RangeLookup` call:

```
2017/08/19 01:45:17.902373 | 318.164174 | /cockroach.roachpb.Internal/Batch
           01:45:17.902375 |    .     2 | ... txnID:30da25bb-71c1-461f-9ff3-87a8f18696e9
           01:45:17.902375 |    .     1 | ... txnid:ffb6d7fe-ac2b-4e55-ae1b-22b180db122a
           01:45:17.902379 |    .     4 | ... [n1] 1 RngLookup
           01:45:17.902385 |    .     6 | ... [n1,s1] executing 1 requests
           01:45:17.902390 |    .     5 | ... [n1,s1,r1/1:/{Min-System/}] read-only path
           01:45:17.902395 |    .     5 | ... [n1,s1,r1/1:/{Min-System/}] command queue
           01:45:17.902398 |    .     3 | ... [n1,s1,r1/1:/{Min-System/}] operation accepts inconsistent results
           01:45:17.902401 |    .     3 | ... [n1,s1,r1/1:/{Min-System/}] waiting for read lock
           01:45:17.902407 |    .     7 | ... [n1,s1,r1/1:/{Min-System/}] RangeLookup
           01:45:17.902549 |    .   142 | ... [n1,s1,r1/1:/{Min-System/}] submitting 1 intents to asynchronous processing
```

I see another request is blocked processing the `AdminScatter`. The request log doesn't give all the detail, but it appears a rebalance operation is in progress:

```
01:45:17.853592 | .   292 | ... [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1] r11374: sending batch 1 EndTxn to (n1,s1):1
01:45:17.853606 | .    15 | ... [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1] sending request to local server
01:45:17.856349 | .  2742 | ... [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1] reply error [txn: 30da25bb], EndTransaction [/Local/Range/"\xbb\x89\xfdl\x1bk\x1c\x92\xb8\x05u"/RangeDescriptor,/Min): r11374 was not found
01:45:17.856352 | .     4 | ... [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1] evicting range descriptor on send error and backoff for re-lookup
01:45:17.857875 | .  1522 | ... [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1] evicting cached range descriptor
01:45:17.902318 | . 44443 | ... [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1,range-lookup] r1: sending batch 1 RngLookup to (n1,s1):1
01:45:17.902339 | .    21 | ... [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1,range-lookup] sending request to local server
01:46:17.902644 | 60.000305 | ... kv/dist_sender.go:1156 [s1,r11374/1:/Table/51/1/77{89937…-90749…},n1,range-lookup] have been waiting 1m0s sending RPC to r1 for batch: RangeLookup [/Meta2/Table/51/1/7789937750932194677,/Min)
```

The logs on `n1` show the most recent activity for `r11374`:

```
I170819 01:45:17.308519 342080 storage/replica_command.go:3637  [n1,s1,r11374/1:/Table/51/1/77{89937…-90749…}] change replicas (REMOVE_REPLICA (n5,s5):4): read existing descriptor r11374:/Table/51/1/77{89937750932194677-90749866333379934} [(n1,s1):1, (n6,s6):2, (n3,s3):3, (n5,s5):4, next=5]
```

Going to poke around and try to find out why the `RangeLookup` operation hung. Processing intents asynchronously shouldn't block.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #17760

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17766#-:-KrwdjdxzmHuua86UNur:bnfp4nl)*

**Comment by petermattis** [comment]
Added a test which fails before this change and succeeds after. The test verifies that range lookup ops do not perform synchronous intent resolution, but does not fully reproduce the deadlock as tying this up with the `RangeDescriptorCache` proved too difficult.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 611 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17766#-Ks9PU8n6YI1_LLbB7CA:-Ks9PU8n6YI1_LLbB7CB:bfrj9nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/64a4be13e2a98c7486296db3ab69e291e3f5e6f1/pkg/storage/store.go#L611)):*
> ```Go
> 	// IntentResolverTaskLimit is the maximum number of asynchronous tasks that
> 	// may be started by the intent resolver. -1 indicates no asynchronous tasks
> 	// are allowed.
> ```

Mention that zero gets the default value (which is not zero)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17766#-:-Ks9PqYCVAr_tZgn7ezd:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 611 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17766#-Ks9PU8n6YI1_LLbB7CA:-Ks9Q7sr0kID1hzYwKSL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64a4be13e2a98c7486296db3ab69e291e3f5e6f1/pkg/storage/store.go#L611)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Mention that zero gets the default value (which is not zero)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17766)*

**Pull request merged**
