### PR TITLE
sql/parser: Various OID-related fixes

### PR DESCRIPTION
**Pull request by nvb**
This change contains 4 OID-related improvements to our `parser` package.
1. OID casts from INTs should never fail. Instead, they should simply result in an OID without a name when the lookup is not successful.
2. Previously our `*DOid` type always returned `TypeOid` from its `ResolvedType` method. We now return the proper type in cases where it is representing an OID variant. This means that introspection into these values' types (`EXPLAIN (TYPES)`, `pg_typeof`, etc.) now works correctly.
3. The `<string>::oid` cast is now implemented correctly.
4. `regnamespace` was added to the pg_type table.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14260)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: 1 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 2175 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-Kfd8yZwfmZ86wfc_qdb:-Kfd8yZwfmZ86wfc_qdc:b1ra8ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/99762e0fea8ff001d1297e615a6c42edab5709b5/pkg/sql/parser/eval.go#L2175)):*
> ```Go
> 			default:
> 				oid, err := queryOid(ctx, typ, v)
> 				if err != nil {
> ```

this seems heavy handed, given that queryOid has more than one error condition. Perhaps a deeper refactoring is necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260)*

**Comment by jordanlewis** [comment]
:lgtm: with a few questions

---

Reviewed 4 of 4 files at r1, 9 of 9 files at r2, 2 of 2 files at r3.
Review status: 10 of 12 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 2043 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-KfgKIPQvddxqhnJfK2E:-KfgKIPRyVuyp0aFcsml:blp5cl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/572379991f8c3af2510cbf77975e6afd734395c9/pkg/sql/parser/datum.go#L2043)):*
> ```Go
> // NewDOid is a helper routine to create a *DOid initialized from a DInt.
> func NewDOid(d DInt) *DOid {
> 	oid := DOid{DInt: d, kind: oidColTypeOid, name: ""}
> ```

Hmm is there a reason you assign this first?  also can you just delegate to `MakeDOid`?

---

*[pkg/sql/parser/eval.go, line 2175 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-Kfd8yZwfmZ86wfc_qdb:-KfgIbMeMIQTiQaSF7iu:b-ctk92f) ([raw file](https://github.com/cockroachdb/cockroach/blob/99762e0fea8ff001d1297e615a6c42edab5709b5/pkg/sql/parser/eval.go#L2175)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this seems heavy handed, given that queryOid has more than one error condition. Perhaps a deeper refactoring is necessary.
</blockquote></details>

It's true that there's more than one error condition, but I'm okay with this. If this fails due to something besides a multiple results error or empty results error, it's likely that the query that issued this command will fail as well, so I don't think we need to worry too much about getting this perfect.

---

*[pkg/sql/parser/eval.go, line 2209 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-KfgLqBHNhgkFDGZWydt:-KfgLqBHNhgkFDGZWydu:bxnq53u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58ac75e4f1336521d851d901d2d038e6101a751/pkg/sql/parser/eval.go#L2209)):*
> ```Go
> 					return nil, err
> 				}
> 				return &DOid{kind: typ, DInt: *i}, nil
> ```

Nice catch, thanks

---

*[pkg/sql/parser/type.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-KfgKx96t3m99T0AHPmd:-KfgKx96t3m99T0AHPme:b-j4eq3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/572379991f8c3af2510cbf77975e6afd734395c9/pkg/sql/parser/type.go#L122)):*
> ```Go
> 	TypeRegProcedure = tOid{oid.T_regprocedure}
> 	// TypeRegType is the type of an regtype OID variant. Can be compared with ==.
> 	TypeRegType = tOid{oid.T_regtype}
> ```

Nice, yeah I avoided this at first because I didn't want to pollute the Type namespace but it seems necessary to get the oid output types to be correct like you're fixing here.

---

*[pkg/sql/testdata/pgoidtype, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-KfgLNz1p9T_ICtqSepZ:-KfgLNz1p9T_ICtqSep_:b66vjhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/572379991f8c3af2510cbf77975e6afd734395c9/pkg/sql/testdata/pgoidtype#L30)):*
> ```
> ----
> regproc  regprocedure  regtype
> ```

Can you also check that `pg_typeof` returns the right thing for string->oid casts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-:-KfgLx_9sycNv5n9rANT:bqzqo63)*

**Comment by nvanbenschoten** [comment]
TFTRs!

---

Review status: 1 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/datum.go, line 2043 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-KfgKIPQvddxqhnJfK2E:-KfjEQK68ZiRwzNZds-d:b-ltfvog) ([raw file](https://github.com/cockroachdb/cockroach/blob/572379991f8c3af2510cbf77975e6afd734395c9/pkg/sql/parser/datum.go#L2043)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm is there a reason you assign this first?  also can you just delegate to `MakeDOid`?
</blockquote></details>

Ah nice catch! That's what I meant to do.

---

*[pkg/sql/parser/type.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-KfgKx96t3m99T0AHPmd:-KfjFfK7hAiO-VPn8PUJ:b-klt37k) ([raw file](https://github.com/cockroachdb/cockroach/blob/572379991f8c3af2510cbf77975e6afd734395c9/pkg/sql/parser/type.go#L122)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nice, yeah I avoided this at first because I didn't want to pollute the Type namespace but it seems necessary to get the oid output types to be correct like you're fixing here.
</blockquote></details>

Yeah, it's not quite as bad as adding a completely new type because of how we implement `tOid.Equivalent` and `tOid.FamilyEqual`. Nice job on the OID stuff again.

---

*[pkg/sql/testdata/pgoidtype, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-KfgLNz1p9T_ICtqSepZ:-KfjEa7XJcukI2g1jwbq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/572379991f8c3af2510cbf77975e6afd734395c9/pkg/sql/testdata/pgoidtype#L30)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you also check that `pg_typeof` returns the right thing for string->oid casts?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260#-:-KfjFbFB_6i6K-T603xa:bz5mair)*

**Comment by jordanlewis** [comment]
Reviewed 10 of 10 files at r4, 9 of 9 files at r5, 2 of 2 files at r6, 3 of 3 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14260)*

**Pull request merged**
