### PR TITLE
gc: use ClearRange storage ops to remove multiple consecutive mvcc garbage keys

### PR DESCRIPTION
**Pull request by aliher1911**
This PR changes GC to use Clear Range functionality when multiple consecutive garbage keys are found.
It is split in multiple commits:
- data types for GC request
- storage operation to do clear range GC with safety checks
- change replica data iter to use visitor identical to replica engine data iterator
- changes to GC
- additional GC metricas to expose clear range successes and abandoned attempts
- changes to cmd_gc to invoke new storage function when gc clear range is received

---

gc: add delete range parameters to gc request

This commit adds range_deletion_keys parameters to GC request.
range_deletion_keys is used by GC queue to remove chunks of
consecutive keys where no new data was written above the GC
threshold and storage can optimize deletions with range
tombstones.
To support new types of keys, GCer interface is also updated
to pass provided keys down to request.

---

storage: add gc operation that uses clear range

GC relies on point and range key deletion operations
when removing data. This is not good in cases where full
range is deleted e.g. schema change.
This pr adds a gc operation that uses pebble range tombstones
to remove data.

---

rditer: helper to visit multiple replica key spans

IterateMVCCReplicaKeySpans helper to complement IterateplicaKeySpans

---

gc: GC use delete_range_keys for consecutive ranges of keys

When deleting large chunks of keys usually produced by range tombstones
GC will use point deletion for all versions found within replica key
range.
That kind of operations would generate unnecessary load on the storage
because each individual version must be deleted independently.
This patch adds an ability for GC to find ranges of consecutive keys
which are not interleaved with any newer data and create
delete_range_key GC requests to remove them.

---

gc: add metrics for clear range requests in GC

This commit adds two metrics for clear range functionality in GC:

queue.gc.info.numclearrangerequests is incremented every time GC sends
a ClearRange request to a replica

queue.gc.info.numclearrangeabandoned is incremented every time GC decides
against sending already collected range key request because there's not
enough contiguous keys to remove and rewinds back to send a points delete
request.

---

batcheval: handle ClearRange request fields in GC requests

Handle ClearRange GC request fields to use ClearRange storage
functions for ranges of keys that contain no visible data instead
of removing each key individually.
This PR only enables processing of request field, while actual GC
and storage functionality is added in previous PRs.

### CODE REVIEW

**Comment by aliher1911** [comment]
I tried a different approach to GC where each request has basically MVCCKey for start and end which makes GC code much simpler in terms of rewinds, but the actual ClearRange code in storage is hairy because of stats. If I can make MVCC stats work in it then we can switch to it.

**Review by erikgrinaker — COMMENTED** [review]
I need to go over the new GC batcher more carefully, but flushing the comments I have for everything else.

I notice that we always do a complete scan across the range for stats purposes. Can we do a fast path when clearing an entire Raft range where we do a TBI scan for conflicts and then simply zero out the MVCC stats?

This needs to verify that a TBI scan is actually significantly faster as far back as 25 hours, when most data will have moved pretty far down the LSM, but I think we should still see significant speedups because of the block property filters.

@jbowens What's your sense here? If we have a contiguous key span with garbage that's >25 hours old in L6, and we don't expect to see any newer values <25 hours for that key span, I expect block property filters will still help a lot?

**Comment by erikgrinaker** [comment]
>I tried a different approach to GC where each request has basically MVCCKey for start and end which makes GC code much simpler in terms of rewinds, but the actual ClearRange code in storage is hairy because of stats. If I can make MVCC stats work in it then we can switch to it.

Would this then also address #61455, i.e. allow removing long version runs of a single key? How would that interact with MVCC range keys, which only exist between `roachpb.Key` bounds?

I'm already a bit nervous with the amount of changes we're making here, so I don't think we should try to do too much this late in the game. We only have another three days left to get this in. But if you do decide to go down this path then let me know, and I'll hold off on reviewing the batcher until it lands.

**Review by jbowens — COMMENTED** [review]
> @jbowens What's your sense here? If we have a contiguous key span with garbage that's >25 hours old in L6, and we don't expect to see any newer values <25 hours for that key span, I expect block property filters will still help a lot?

In this scenario, is the question whether to use an iterator with `RangeKeyMasking` enabled versus an unconditional TBI to check for keys more recent than 25 hours within the span?

Range-key masking (with block property filters support) should be on par with an unconditional TBI, just slightly slower because range-key masking performs an extra key comparison per skipped block and may need to load an extra block here and there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85714#-:-N93PoPg1-Q3w6nROC1n:b-ri7u9s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

**Review by erikgrinaker — COMMENTED** [review]
Good point, range key masking offers an alternative. However, I believe there are also cases here where we'll be looking at point garbage that's not covered by a range key.

My question is specifically how performant we can expect block property filters to be when L6 satisfies the time range (i.e. some time into the past) as opposed to the typical case where we're scanning near the current time and can omit the lower levels entirely. But I suppose we can just run a benchmark and find out as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85714#-:-N93RMtNAd0g1Ms_WMuO:b-9am593)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

**Comment by aliher1911** [comment]
@jbowens is this usage https://github.com/cockroachdb/cockroach/pull/86000 in line with what you are proposing? I think alternative would be just scanning for full range tombstone coverage and then checking with TBI threshold of lowest found highest range tombstone across the range.

**Pull request closed without merging**
