### PR TITLE
acceptance: various fixes and cleanups

### PR DESCRIPTION
**Pull request by cuongdo**
- Rename acceptance/allocator_terraform to acceptance/terraform, because
  all tests using a (*Terrafarm).Farmer should be using that Terraform
  config, not just allocator tests.
- Misc doc updates.
- Move from separate load generation machines to colocating load
  generators with `cockroach` instances, just like the prod clusters.
- Add flags for continuousLoadtest for easy test config through TeamCity.
- Make max std dev check for allocator tests actually work.

Because a these changes touch an overlapping set of files and I want to
get Tobi's eyes on this soon, this is one commit.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8265)

### CODE REVIEW

**Comment by tamird** [comment]
Can you address my comments from https://github.com/cockroachdb/cockroach/pull/8225#issuecomment-236933451 in this PR?

---

Reviewed 2 of 18 files at r1, 2 of 2 files at r2.
Review status: 4 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8265#-:-KOBrqJMV_sgO8OvbDGD:292718267)*

**Comment by cuongdo** [comment]
Rebased (to hopefully fix CI issues) and addressed @tamird's comments from #8225

---

Review status: 3 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8265#-:-KODEeYrm4nCcL-eOhlX:725450267)*

**Comment by tamird** [comment]
My comments LG.

---

Reviewed 1 of 1 files at r3.
Review status: 4 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8265#-:-KODFBhwyE7P7Zypc96L:681584662)*

**Comment by tschottdorf** [comment]
- The hint about `tf.keep-cluster=failed` might as well suggest using
`=always`.
- couldn't the stdDev thing fail spuriously if the first node is rebooted
or not up at the beginning?
- same for "couldn't find any range events" - this makes assumptions about
the actual tests which may not hold in the future (think dump-restore etc).

Probably ok but I thought those checks were lenient for a reason.

- Why do we have to restart the load generators? Don't they tolerate errors?
- Stale comment on `Add()`, `Resize()`
- Double space in `TestBuildBabyCluster resizes...`
- Can we perhaps merge `terrafarm` and `terraform`? Just a thought.

- The semantics for starting nodes and writers are somewhat shady now.
Looking at the code, I see writers being started explicitly, always. But
`cockroach` binaries are apparently run automatically when setting up a
node. That means when I am running a 3node cluster, won't it automatically
turn into a 5node cluster when I call `Resize(5)`? That's really not clear.
How would I run 100 writers against a 3node cluster?

LGTM otherwise.
-- 

-- Tobias

**Comment by bdarnell** [comment]
LGTM

---

Review status: 4 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[acceptance/allocator_test.go, line 40 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8265#-KOGOHibc3dJ-pssFCEa:-KOGOHibc3dJ-pssFCEb:1696944693) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49d4bb671f62f6842880f7ab04906cd463dfd21/acceptance/allocator_test.go#L40)):*
> ```Go
> //
> // Things to note:
> // - Your SSH key (-key-name) for Google Cloud Platform must be in
> ```

Replace this with "You must use an ssh key without a passphrase. It is recommended to create a new key for this purpose named `google_compute_engine` so the `gcloud` tools can use it too. Create the key with `ssh-keygen -f ~/.ssh/google_compute_engine`"

---

*[acceptance/allocator_test.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8265#-KOGOazKIytaPOC-Y6-k:-KOGOazKIytaPOC-Y6-l:-2041325597) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49d4bb671f62f6842880f7ab04906cd463dfd21/acceptance/allocator_test.go#L60)):*
> ```Go
> //
> // Troubleshooting:
> // - If you get strange Terraform errors, try upgrading your Terraform install.
> ```

Mention that 0.6.16 is the recommended minimum (or whatever version you have if it's older). FWIW I know that 0.6.8 did not work. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8265#-:-KOGQ0RJFTBFXNqU6sb5:676834233)*

**Comment by cuongdo** [comment]
Addressed @tschottdorf's comments. Responses follow:

- Changed the hint to `=always`
- I've removed the immediate call to `allocatorStats()` and have bumped the stats interval to 20 seconds for extra cushion. I agree that calling that method in the first few seconds of a server's lifetime is iffy.
- Regarding the range events issue, we'll cross that bridge when we get there. I'm not convinced that dump/restore can be any faster than copying bytes within the same (generally speaking) network.
- I'm not sure what you mean by restarting the load generators.
- Fixed the stale comment on `Add()` and `Resize()`
- Fixed the double space in `TestBuildBabyCluster`
- I'm open to merging `terraform` and `terrafarm`, but I don't see a large benefit either.
- Yes, a 3-node cluster will turn into a 5-node cluster when you call `Resize`. I believe that's expected. The number of started writers won't grow automatically and is up to the test to define. For now, you can't run more writers than nodes, but at this point, you probably shouldn't. Also, if you wanted to run that many writers, you’d probably want to revamp the way we launch load generators. Even previously, we were limited to one instance of each load generator per machine. Since the load generator process uses very little CPU directly, we would likely want to run many instances of a load generator on a single GCE instance to avoid extravagant overuse of GCE resources.

---

Review status: 1 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8265#-:-KOFzTLYYgMHHTxiXbUh:-876512957)*

**Pull request merged**
