### PR TITLE
colexec: add support for percent_rank and cume_dist window functions

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add window peer grouper**

This commit adds an operator that populates a boolean column to signify
whether the corresponding tuple is the start of a new peer group. Peers
are such tuples that belong to the same partition and are equal on the
ordering columns. Some window functions must return the same output for
all peers in the peer group. Currently this operator is not used.

Release note: None

**colexec: minor refactor of rank and denseRank operators**

Previously, rank and denseRank operators contained the logic to figure
out the boundaries of the peer groups, but now that we have a window
peer grouper, it is no longer necessary which simplified the code a
little bit.

Release note: None

**colexec: add support for PERCENT_RANK window function**

This commit adds the support for PERCENT_RANK window function. This
function differs from two other rank variances in that it needs to know
the number of tuples in the partition. If there is no PARTITION BY
clause, then we have no other choice but to buffer the input fully. If
PARTITION BY clause is present, we need to buffer all tuples that belong
to each partition before we can populate the output. However, for
simplicity, the current implementation of the operator with PARTITION BY
clause also fully buffers the whole input before emitting any output.

This commit also adds a couple of "vec-on" configs to 'window' logic
test. This will increase the test coverage of window functions supported
by the vectorized engine.

Addresses: #37035.

Release note: None

**colexec: add support for cume_dist window function**

This commit adds support for CUME_DIST window function. This function is
quite similar to PERCENT_RANK, so it reuses the same template.
"percent_rank" things have been renamed to "relative_rank" things.

This commit also enables running of `row_number`, `rank`, and
`dense_rank` with `vectorize=auto`. The reason is that these window
functions are streaming and internally they might a sorter which can
fallback to disk if necessary.

Addresses: #37035.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Added support for `cume_dist` window function, it seemed easy enough.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Mostly nits.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-:-M1REWOBD3s3ed-D5DZ-:biyt5mx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/rank_tmpl.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RB8mQ8yzTSUFhOiWh:-M1RB8mQ8yzTSUFhOiWi:b-b6r2e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/colexec/rank_tmpl.go#L52)):*
> ```Go
> 	if len(orderingCols) == 0 {
> 		if windowFn == execinfrapb.WindowerSpec_PERCENT_RANK {
> 			return NewConstOp(allocator, input, coltypes.Float64, float64(0), outputColIdx)
> ```

Out of curiosity, could you explain why we return a const op that returns a zero float?
___
*[pkg/sql/colexec/window_functions_util.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1QsPAK40RTU4hqpKwQ:-M1QsPAK40RTU4hqpKwR:b-98jy38) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2dba2b3962597599c5b816013bdeb57cc274eb6/pkg/sql/colexec/window_functions_util.go#L17)):*
> ```Go
> const columnOmitted = -1
> 
> var windowFnNeedsPeersInfo map[execinfrapb.WindowerSpec_WindowFunc]bool
> ```

Could we add a comment to this? I personally have very little knowledge of window functions so some explanations are usually helpful.
___
*[pkg/sql/colexec/window_functions_util.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDqod-sav8gRgHsaX:-M1RDqod-sav8gRgHsaY:bmq3wdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ec7307c4bcbe9d89a5abac9e91ea3b55cc682a/pkg/sql/colexec/window_functions_util.go#L24)):*
> ```Go
> 	// WindowFnOutputType is a mapping from a window function to its output type.
> 	// Only window functions supported by the vectorized engine are present.
> 	WindowFnOutputType map[execinfrapb.WindowerSpec_WindowFunc]*types.T
> ```

What if instead of doing this you created a function called `GetWindowFnInfo()` that returns both the peer info an output type according to a switch statement? I think it would be easier to read. Maybe this should be shared across col and rowexec?
___
*[pkg/sql/colexec/window_peer_grouper_tmpl.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1Qv7CqAtAfoYWSYG92:-M1Qv7CqAtAfoYWSYG93:b-ktr4x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2dba2b3962597599c5b816013bdeb57cc274eb6/pkg/sql/colexec/window_peer_grouper_tmpl.go#L33)):*
> ```Go
> // outputColIdx'th column (which is appended if needed) for every tuple that is
> // the first within its peer group. Peers are tuples that belong to the same
> // partition and are equal on the ordering columns. If ordCols is empty, than
> ```

nit `s/than/then`. I would also rename `ordCols` to `orderingCols` since `ord` makes me think of `ordinal` rather than `ordering`.
___
*[pkg/sql/colexec/window_peer_grouper_tmpl.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1QvEdV86bm4yhsBuZu:-M1QvEdV86bm4yhsBuZv:b-x6ij12) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2dba2b3962597599c5b816013bdeb57cc274eb6/pkg/sql/colexec/window_peer_grouper_tmpl.go#L34)):*
> ```Go
> // the first within its peer group. Peers are tuples that belong to the same
> // partition and are equal on the ordering columns. If ordCols is empty, than
> // all tuples within the partition are peers.
> ```

Window functions are confusing.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 846 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RCR4S-z6HFIcNQkb1:-M1RCR4S-z6HFIcNQkb2:b-hkrs7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/distsql/columnar_operators_test.go#L846)):*
> ```Go
> }
> 
> func TestWindowFunctionsAgainstProcessor(t *testing.T) {
> ```

You probably already did this but I want to make sure we stress this test for a bit before merging.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 879 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDJiW7LGGgiy-VQil:-M1RDJiW7LGGgiy-VQim:b-uw7ftw) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/distsql/columnar_operators_test.go#L879)):*
> ```Go
> 						continue
> 					}
> 					inputTypes := typs[:nCols:nCols]
> ```

Why the extra `nCols`?
___
*[pkg/sql/logictest/testdata/logic_test/window, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDWEw-wZgav8EBCKM:-M1RDWEw-wZgav8EBCKN:bkca7ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/logictest/testdata/logic_test/window#L1)):*
> ```
> # LogicTest: local local-vec fakedist fakedist-metadata fakedist-vec 5node-local 5node-dist 5node-dist-metadata 5node-dist-disk
> ```

Super cool!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/rank_tmpl.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RB8mQ8yzTSUFhOiWh:-M1RKlq9DpVuVyF6Trjm:bh084p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/colexec/rank_tmpl.go#L52)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Out of curiosity, could you explain why we return a const op that returns a zero float?
</blockquote></details>

When there are no columns in `ORDER BY` clause of window functions, then all rows are considered "peers". Percent rank is calculated as `(rank - 1) / (total rows - 1)`, and in such scenario all rows' `rank = 0`, so `percentRank` will also be `0` for all rows.

```
yuzefovich=# create table temp (a int);
CREATE TABLE
yuzefovich=# insert into temp values (0), (1), (2);
INSERT 0 3
yuzefovich=# select a, percent_rank() over () from temp;
 a | percent_rank 
---+--------------
 0 |            0
 1 |            0
 2 |            0
(3 rows)
```
___
*[pkg/sql/colexec/window_functions_util.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1QsPAK40RTU4hqpKwQ:-M1RR7MdCJUlky6BOQvW:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2dba2b3962597599c5b816013bdeb57cc274eb6/pkg/sql/colexec/window_functions_util.go#L17)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could we add a comment to this? I personally have very little knowledge of window functions so some explanations are usually helpful.
</blockquote></details>

Added a comment.
___
*[pkg/sql/colexec/window_functions_util.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDqod-sav8gRgHsaX:-M1RRB5w9ng48a2vlsI9:baqr3uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ec7307c4bcbe9d89a5abac9e91ea3b55cc682a/pkg/sql/colexec/window_functions_util.go#L24)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What if instead of doing this you created a function called `GetWindowFnInfo()` that returns both the peer info an output type according to a switch statement? I think it would be easier to read. Maybe this should be shared across col and rowexec?
</blockquote></details>

We actually already have such function, I moved it from `rowexec` into`execinfrapb` package. Done.
___
*[pkg/sql/colexec/window_peer_grouper_tmpl.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1Qv7CqAtAfoYWSYG92:-M1RLvqB0CgYENVYiYyn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2dba2b3962597599c5b816013bdeb57cc274eb6/pkg/sql/colexec/window_peer_grouper_tmpl.go#L33)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit `s/than/then`. I would also rename `ordCols` to `orderingCols` since `ord` makes me think of `ordinal` rather than `ordering`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/window_peer_grouper_tmpl.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1QvEdV86bm4yhsBuZu:-M1RLwhp4ON10ORGscYU:b4zutyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2dba2b3962597599c5b816013bdeb57cc274eb6/pkg/sql/colexec/window_peer_grouper_tmpl.go#L34)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Window functions are confusing.
</blockquote></details>

Indeed :)
___
*[pkg/sql/distsql/columnar_operators_test.go, line 846 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RCR4S-z6HFIcNQkb1:-M1RRL5006LET7kHWGjR:ba4li91) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/distsql/columnar_operators_test.go#L846)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You probably already did this but I want to make sure we stress this test for a bit before merging.
</blockquote></details>

Yeah, I did 100 runs. Initially, this test confirmed the bug I realized I had in my original implementation of `percentRank` when we have more than a single batch of data. (That's why I bumped the number of rows here.)
___
*[pkg/sql/distsql/columnar_operators_test.go, line 879 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDJiW7LGGgiy-VQil:-M1RRdop17Ftwb5oPkWf:b-2kgw32) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/distsql/columnar_operators_test.go#L879)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why the extra `nCols`?
</blockquote></details>

This is a very subtle issue that I spent a few minutes trying to debug. Here is what happens:
- at the top of the test we instantiate `typs` up to `maxCols`
- then, depending on the test spec, we might actually have less columns, so we slice it up, i.e. `inputTypes := typs[:nCols]`
- later, we're appending to `inputTypes` the return type of the window function, and here is the catch - if we don't specify the capacity of `inputTypes`, then no new array is allocated and we, instead, overwrite one of the `typs` with `returnType`, but we assume that `typs` are immutable.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDWEw-wZgav8EBCKM:-M1RSGcGCYlcWlxhvpfc:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/55fb536b4d20a74b0bb790c7db69b70003a06c85/pkg/sql/logictest/testdata/logic_test/window#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Super cool!
</blockquote></details>

Ack.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r5, 2 of 2 files at r6, 13 of 13 files at r7, 10 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/window_functions_util.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDqod-sav8gRgHsaX:-M1Ra_lL3qM6JnFSQ7pl:bw30cq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ec7307c4bcbe9d89a5abac9e91ea3b55cc682a/pkg/sql/colexec/window_functions_util.go#L24)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We actually already have such function, I moved it from `rowexec` into`execinfrapb` package. Done.
</blockquote></details>

Maybe we still want to do something like this for the peer info?
___
*[pkg/sql/colexec/window_functions_util.go, line 28 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1Raxqj7yIh77Jyu5C0:-M1RaxqkA_yZnUBElSCA:b-6lq56e) ([raw file](https://github.com/cockroachdb/cockroach/blob/edd730f2e42ae83993beae6d03ef356758dc5e6a/pkg/sql/colexec/window_functions_util.go#L28)):*
> ```Go
> 	// SupportedWindowFns contains all window functions supported by the
> 	// vectorized engine.
> 	SupportedWindowFns = []execinfrapb.WindowerSpec_WindowFunc{
> ```

I would make this a map[wfn]struct{}

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/window_functions_util.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDqod-sav8gRgHsaX:-M1RiKsw7dLHV0YYku78:bnspqva) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ec7307c4bcbe9d89a5abac9e91ea3b55cc682a/pkg/sql/colexec/window_functions_util.go#L24)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe we still want to do something like this for the peer info?
</blockquote></details>

`rowexec.Windower` doesn't care about this info (it has a separate `PeerGroupIndicesHelper` utility struct). In `colexec` we have slightly different model: we plan different operators on "top" each other, so we need to know this info during planning, in `rowexec` that info is "assessed" dynamically.

I also think (but not sure) that `row_number` might be the only window function that doesn't pay attention to "peers". If so, maybe we'll remove this `map` later.
___
*[pkg/sql/colexec/window_functions_util.go, line 28 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1Raxqj7yIh77Jyu5C0:-M1RiJpg9FAumVg5Rsv2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edd730f2e42ae83993beae6d03ef356758dc5e6a/pkg/sql/colexec/window_functions_util.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would make this a map[wfn]struct{}
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-:-M1RkxYUADoy8v04g2ye:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/window_functions_util.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDqod-sav8gRgHsaX:-M1Rkqey6igNaTVflJLr:b-i3l4uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ec7307c4bcbe9d89a5abac9e91ea3b55cc682a/pkg/sql/colexec/window_functions_util.go#L24)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`rowexec.Windower` doesn't care about this info (it has a separate `PeerGroupIndicesHelper` utility struct). In `colexec` we have slightly different model: we plan different operators on "top" each other, so we need to know this info during planning, in `rowexec` that info is "assessed" dynamically.

I also think (but not sure) that `row_number` might be the only window function that doesn't pay attention to "peers". If so, maybe we'll remove this `map` later.
</blockquote></details>

I guess I meant just a private function used by `colexec` instead of a map. But up to you.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42137)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/window_functions_util.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42137#-M1RDqod-sav8gRgHsaX:-M1RnSUyAvqlplWHF4JD:b9lrzfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/46ec7307c4bcbe9d89a5abac9e91ea3b55cc682a/pkg/sql/colexec/window_functions_util.go#L24)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I guess I meant just a private function used by `colexec` instead of a map. But up to you.
</blockquote></details>

Oh, I see, I guess a function does look better. Done.

**Comment by yuzefovich** [comment]
I amended the last commit to plan three streaming window functions with `auto` setting as well. If the build is green, I'll go ahead and merge it.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
