### PR TITLE
util: simplify CreateTestAddr

### PR DESCRIPTION
**Pull request by petermattis**
No need to pass in the network to CreateTestAddr when it is always
"tcp".

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5178)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: though I think we can get rid of this function altogether - no point in resolving 127.0.0.1.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5178#-:-KCcOdU3625t_z7BHkTm:879407127)*

**Comment by petermattis** [comment]
Well, we need a `net.Addr`. Add `util.TestAddr` as a replacement for `util.CreateTestAddr()`.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5178#-:-KCcSujC-miz6PfXd2iy:-1302364464)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/unresolved_addr.go, line 24 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5178#-KCcTkXjPy-fF2Qv1Cxf:-KCcTkXk_CtOPKwHd6NE:-641889334) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5f1228c7711aece5d84080218c309ff84bace/util/unresolved_addr.go#L24)):*
"unused" is odd

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5178#-:-KCcTs__afMBTTK0gmjY:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[util/unresolved_addr.go, line 24 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5178#-KCcTkXjPy-fF2Qv1Cxf:-KCfRx3YwZQhmfTkjt61:-639520407) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5f1228c7711aece5d84080218c309ff84bace/util/unresolved_addr.go#L24)):*
Oops, merged before addressing this comment. See https://github.com/cockroachdb/cockroach/pull/5193.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5178)*

**Pull request merged**
