### PR TITLE
sql: Split aggregate logic test so that it can be reused

### PR DESCRIPTION
**Pull request by andy-kimball**
This commit splits the aggregate logic test into multiple parts:

  logic_test/aggregate
    This part excludes EXPLAIN and SHOW TRACE queries, since their output
    only applies to the heuristic planner. These queries often fail with the
    cost-based optimizer, which often uses a different execution plan. With
    the EXPLAIN and SHOW TRACE queries removed, this test can now be
    successfully run using the cost-based optimizer ("opt" config).

  planner_test/aggregate
    This part includes all the EXPLAIN and SHOW TRACE queries that were
    removed from the original logic_test. The expected output is the same
    as it originally was; namely the plans that the heuristic planner
    derives.

  opt/exec/execbuilder
    This part is analogous to the planner_test part, except that the EXPLAIN
    and SHOW TRACE queries run with the cost-based optimizer. Most of these
    tests had already been copied to the `opt` packages, so this commit just
    copies a few additional tests that never made it over, as well as delete
    redundant tests that are already part of the logic_test suite.

There are still 150+ other tests to split. This commit serves as the template
for how that will be done. Once the larger team is happy with the methodology,
we'll begin the work of migrating the other tests.

With this change, while we do lose the convenience of having execution output
paired with EXPLAIN/TRACE output, we gain the ability to run the same set of
logic tests against a wider variety of configurations. By doing so, we stick
more closely to the spirit of the original SQLite sqllogictest methodology.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
The change LGTM  Let's see if folks have any high-level objections or suggestions.

**Comment by knz** [comment]
Thanks Andy!

LGTM on principle. Two nits:

- The change to the logic tests and the change to the opt code are orthogonal, I think they should be split in two separate commits.

- We have a new syntax (thanks to Bram) to identify sub-tests in logic tests, perhaps this could be leveraged usefully here too.

**Comment by andy-kimball** [comment]
Yeah, I thought about splitting into two commits. What I'm trying to do is show the complete end-to-end design:

1. Pure logic tests go in `logic_test`
2. Heuristic planner tests go in `planner_test`
3. Cost-based optimizer tests go in `opt`

I wanted to show what that looks like for a complete set of tests (i.e. aggregate tests), in a single PR. And since there's no overlap between files, it seemed fine to do that in single commit, since this is all one conceptual and connected change.

However, for future work along these lines, I'll split into separate commits.

Re: the sub-tests, how would they impact this work?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25792#-:-LD7RadAEJ9_Z4ktrUlQ:b77grjk)*

**Comment by andy-kimball** [comment]
@knz, @radu clarified that you were talking about the `opt` code changes. I went ahead and split those out into their own commit. I had to tweak a few error messages to match 2.0 so that logic tests would give same results with optimizer.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25792#-:-LD7VNQY8otaKOf21AL5:btpjrz3)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25792#-:-LD8s1mm9tz653hhJHqc:bnfp4nl)*

**Comment by jordanlewis** [comment]
:lgtm: I think this is a good approach.

---

Reviewed 5 of 5 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25792#-:-LD92ZSq6vPoFi5e6OOA:brcxdxm)*

**Pull request merged**
