### PR TITLE
sql: add SpanPartitionState to understand partitioning behavior

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, there was no obseravbility into why our resolver
picked a particular instance for a given span. This made
debugging features such as backups/restores with execution
locality harder as we do not know why all replicas were
picked on a given node instead of being distributed to another
node. This will also benefit distributed SQL queries where
its important to understand what replicas are being picked.

This change adds a `SpanPartitionState` that covers all the
"interesting" decisions made by the resolver. This state can
be attributed to each span partition. Currently, this is logged
if vmodule>=2 or if verbose tracing is enabled. In the future
we may integrate it with the jobs profile infrastructure to
be dumped to disk on demand.

Informs: #113044
Release note: None

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
hm I'm not convinced I'm printing the correct span, I think this is always just printing the entire span that is being partitioned. I think we might have to be smarter about what the EndKey for the current span we are processing is.

**Review by rharding6373 — COMMENTED** [review]
Left some comments. It looks really good, appreciate what you're doing to improve distsql debugability.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-:-NhYWaZs8T_37twkvRwG:b4sgucp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[`pkg/sql/distsql_physical_planner.go` line 1122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYPTxU9CZpwGhFj9h3:-NhYPTxU9CZpwGhFj9h4:bg2oxp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1122)):*
> ```Go
> 	switch r {
> 	case SpanPartitionReason_UNSPECIFIED:
> 		return ""
> ```

I think the string for this should be "unspecified" instead of empty.
___
*[`pkg/sql/distsql_physical_planner.go` line 1353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYMP0V18UEysTff_Vo:-NhYMP0V18UEysTff_Vp:b4ac109) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1353)):*
> ```Go
> 		if log.ExpensiveLogEnabled(ctx, 2) {
> 			log.VEventf(ctx, 2, "partition span: %s, instance ID: %d, reason: %s",
> 				span.String(), sqlInstanceID, reason.String())
> ```

nit: shouldn't need the `.String()`
___
*[`pkg/sql/distsql_physical_planner.go` line 1353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYNFLb6ej_LZ_mIyb0:-NhYNFLb6ej_LZ_mIyb1:b-o3pewr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1353)):*
> ```Go
> 		if log.ExpensiveLogEnabled(ctx, 2) {
> 			log.VEventf(ctx, 2, "partition span: %s, instance ID: %d, reason: %s",
> 				span.String(), sqlInstanceID, reason.String())
> ```

Instead of `span`, this should be something like
`roachpb.Span{
				Key:    lastKey.AsRawKey(),
				EndKey: endKey.AsRawKey(),
			}
`
like below.
___
*[`pkg/sql/distsql_physical_planner.go` line 1503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYYq5D85CugkUwpWWK:-NhYYq5D85CugkUwpWWL:b-bhw4vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1503)):*
> ```Go
> 	healthyNodes := make(map[base.SQLInstanceID]struct{}, len(allHealthy))
> 	for _, n := range allHealthy {
> 		healthyNodes[n.InstanceID] = struct{}{}
> ```

It might improve observability to log all the healthy nodes here. What do you think?
___
*[`pkg/sql/distsql_physical_planner.go` line 1591 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYZhVl5aETOU4YE2Sz:-NhYZhVl5aETOU4YE2T-:b-89mujo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1591)):*
> ```Go
> 		gatewayIsEligible = true
> 	}
> ```

It may also improve observability to log the instances (these will be the healthy, eligible ones) here.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112938)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/distsql_physical_planner.go` line 1122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYPTxU9CZpwGhFj9h3:-Nhb-vo8Co6QEO3rb6RQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1122)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think the string for this should be "unspecified" instead of empty.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_physical_planner.go` line 1353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYNFLb6ej_LZ_mIyb0:-Nhb2XFm0ihHge1CW7MR:b-jy4sc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1353)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Instead of `span`, this should be something like
`roachpb.Span{
				Key:    lastKey.AsRawKey(),
				EndKey: endKey.AsRawKey(),
			}
`
like below.
</blockquote></details>

yeah i realized this when i started writing a test. I moved this log line to a fewer lines below where we have a handle to `endKey`
___
*[`pkg/sql/distsql_physical_planner.go` line 1503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYYq5D85CugkUwpWWK:-Nhb2ejREWFpyQF3krsh:b71kqt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1503)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It might improve observability to log all the healthy nodes here. What do you think?
</blockquote></details>

I agree, added it in
___
*[`pkg/sql/distsql_physical_planner.go` line 1591 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYZhVl5aETOU4YE2Sz:-Nhb2T_F74OHhNqwlU-B:bpleix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1591)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It may also improve observability to log the instances (these will be the healthy, eligible ones) here.
</blockquote></details>

agreed, added it in

**Comment by adityamaru** [comment]
I added a test as well that I'd appreciate a review on!

**Review by rharding6373 — APPROVED** [review]
:lgtm: I think the tests can be combined since they're basically the same except one adds tracing. Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-:-NhcACSA1ibrgnlL498L:b-1hzr95)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[`pkg/sql/distsql_physical_planner.go` line 1353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhYNFLb6ej_LZ_mIyb0:-NhbgEll7ElhItfo4noL:bd9hdu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c96fd683e5b6c7292269e44a12a0c6ab8628712/pkg/sql/distsql_physical_planner.go#L1353)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

yeah i realized this when i started writing a test. I moved this log line to a fewer lines below where we have a handle to `endKey`
</blockquote></details>

Looks fine. Thanks.
___
*[`pkg/sql/distsql_physical_planner.go` line 1382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhbgPUOEHlkF6Bup2eu:-NhbgPUOEHlkF6Bup2ev:bxtbqeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner.go#L1382)):*
> ```Go
> 
> 		if log.ExpensiveLogEnabled(ctx, 2) {
> 			partitionedSpan := roachpb.Span{Key: lastKey.AsRawKey(), EndKey: endKey.AsRawKey()}
> ```

nit: lift `partitionedSpan` out and reuse it on line 1391 instead of making the span twice.
___
*[`pkg/sql/distsql_physical_planner.go` line 1510 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhbyuiLByNtlKU96ogq:-Nhbh-u69MNwnOAtEEG8:boeuazs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner.go#L1510)):*
> ```Go
> 
> 	if log.ExpensiveLogEnabled(ctx, 2) {
> 		log.VEventf(ctx, 2, "healthy SQL instances for KV node hosted instance: %v", allHealthy)
> ```

nit: let's make these log messages for healthy sql instances the same. How about: "healthy SQL instances available for distributed planning:"?
___
*[`pkg/sql/distsql_physical_planner.go` line 1623 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-Nhc2omXCBdMoQNLivod:-Nhc2omXCBdMoQNLivoe:bcq54bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner.go#L1623)):*
> ```Go
> 			if mixedProcessMode {
> 				if ok, _ := nodeDesc.Locality.Matches(locFilter); ok {
> 					return mixedProcessSameNodeResolver(nodeID)
> ```

We noticed in the test that the test is being run in system tenant but use `partitionSpans` if there's a locality filter. As a result of this distsql thinks it's in this "mixed process" mode and in the tests you see logs coming from this call to the `mixedProcessSameNodeResolver`. This is somewhat confusing, since we get a mix of `closest-locality-match` and `target-healthy` reasons (see the second test after "// Test some locality-filtered planning too." in the test).

I don't think this is a problem, just a little confusing. I'll suggest a comment to add to the tests about the mixed process mode.
___
*[`pkg/sql/distsql_physical_planner_test.go` line 1523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhbiJh11cndw0GXCAjP:-NhbiJh11cndw0GXCAjQ:b-4xqb7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner_test.go#L1523)):*
> ```Go
> }
> 
> // TestPartitionSpansPartitionState is almost identical to TestPartitionSpans
> ```

Why not add the `partitionStates` field to `TestPartitionSpans` and just add to that test?
___
*[`pkg/sql/distsql_physical_planner_test.go` line 1653 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-Nhc9Qkg-tJTBP1IisFV:-Nhc9Qkg-tJTBP1IisFW:buxfum2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner_test.go#L1653)):*
> ```Go
> 		},
> 
> 		// Test some locality-filtered planning too.
> ```

Could you add the following comment to help clarify the logs?

```
// Since this test is run on a system tenant but there is a locality filter, the spans are resolved in a mixed process mode. As a result, the partition states include a mix of locality and target reasons, which is expected.
```

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112938)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

___
*[`pkg/sql/distsql_physical_planner.go` line 1623 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-Nhc2omXCBdMoQNLivod:-NhcdZ4015dWt6_fb-H4:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner.go#L1623)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

We noticed in the test that the test is being run in system tenant but use `partitionSpans` if there's a locality filter. As a result of this distsql thinks it's in this "mixed process" mode and in the tests you see logs coming from this call to the `mixedProcessSameNodeResolver`. This is somewhat confusing, since we get a mix of `closest-locality-match` and `target-healthy` reasons (see the second test after "// Test some locality-filtered planning too." in the test).

I don't think this is a problem, just a little confusing. I'll suggest a comment to add to the tests about the mixed process mode.
</blockquote></details>

done!
___
*[`pkg/sql/distsql_physical_planner_test.go` line 1523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-NhbiJh11cndw0GXCAjP:-NhcjUgT8F8XPyXPG0CN:byc5lr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner_test.go#L1523)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why not add the `partitionStates` field to `TestPartitionSpans` and just add to that test?
</blockquote></details>

yeah i thought I was going to trim down that test a lot more but it ended up being valuable to test as is. I collapsed it into a single test.
___
*[`pkg/sql/distsql_physical_planner_test.go` line 1653 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112938#-Nhc9Qkg-tJTBP1IisFV:-NhcdXfl3h6xLi6IJC3g:b-t9490a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89701ff27340ca5f063d3bc8f1a0932e1702247/pkg/sql/distsql_physical_planner_test.go#L1653)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add the following comment to help clarify the logs?

```
// Since this test is run on a system tenant but there is a locality filter, the spans are resolved in a mixed process mode. As a result, the partition states include a mix of locality and target reasons, which is expected.
```
</blockquote></details>

added!

**Comment by adityamaru** [comment]
blathers backport 23.2

**Comment by adityamaru** [comment]
blathers backport 23.1

**Comment by mgartner** [comment]
@adityamaru FYI the 23.1 backport failed.

**Pull request merged**
