### PR TITLE
sql: add support for ANALYZE <tablename>

### LINKED ISSUE #49214: sql, stats: support ANALYZE
For compatibility with Postgres, we should consider adding support for `ANALYZE`. This would basically be syntactic sugar for a call to `CREATE STATISTICS` on all the tables in the database. (We could also support the syntax `VACUUM ANALYZE`, although the `VACUUM` part would be basically a no-op).

This came up because the geospatial team wants to fully support as much of the PostGIS tutorial as possible, and `VACUUM ANALYZE` comes up frequently.

cc @awoods187, @otan

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds support for `ANALYZE <tablename>` by adding the
statement as syntactic sugar for the equivalent command
`CREATE STATISTICS "" FROM <tablename>`. This improves compatibility
with Postgres, and is needed to run the PostGIS tutorial as written.

Note that this commit does not add support for `ANALYZE` without a
table name. We can add support for that and other variants later if
needed, but it is not necessary for the PostGIS tutorial.

Fixes #49214

Release note (sql change): Added support for `ANALYZE <tablename>`,
which causes the database to collect statistics on the given table for
use by the optimizer. The functionality of this command is equivalent
to the existing command `CREATE STATISTICS "" FROM <tablename>`, but
it increases compatibility with Postgres by using the same syntax that
Postgres uses.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @RaduBerinde, and @rytaft)

___
*[pkg/sql/sem/tree/analyze.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49816#-M8rRhcv-405nOlPq86s:-M8rRhcv-405nOlPq86t:b1vy8pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/871d1b347ab7444b4ccd7378999868300b3ef89e/pkg/sql/sem/tree/analyze.go#L20)):*
> ```Go
> // Format implements the NodeFormatter interface.
> func (node *Analyze) Format(ctx *FmtCtx) {
> 	ctx.WriteString("ANALYZE ")
> ```

I think we're missing the corresponding code in `pretty.go`. We should add some parsing tests with the new statement to parse_test.go, I think that would have exposed this.

**Comment by rytaft** [comment]
___
*[pkg/sql/sem/tree/analyze.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49816#-M8rRhcv-405nOlPq86s:-M8u0-xrDXiwD9x4a2Bj:b3lzd6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/871d1b347ab7444b4ccd7378999868300b3ef89e/pkg/sql/sem/tree/analyze.go#L20)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we're missing the corresponding code in `pretty.go`. We should add some parsing tests with the new statement to parse_test.go, I think that would have exposed this.
</blockquote></details>

Doesn't seem like I need to add anything to `pretty.go` (`CREATE STATISTICS` doesn't have anything there either...) but good call about adding to `parse_test.go`. Added tests there and `help_test.go`

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49816#-:-M8vBhh-6gKm-zMsCUU3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/sql/sem/tree/analyze.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49816#-M8rRhcv-405nOlPq86s:-M8vBTLU2MuEK9FIYIaH:b-wf7l7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/871d1b347ab7444b4ccd7378999868300b3ef89e/pkg/sql/sem/tree/analyze.go#L20)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Doesn't seem like I need to add anything to `pretty.go` (`CREATE STATISTICS` doesn't have anything there either...) but good call about adding to `parse_test.go`. Added tests there and `help_test.go`
</blockquote></details>

Ah, I guess there is a "default" that works for simple statements, good to know!

**Review by otan — APPROVED** [review]

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49816#-:-M8vUgwO1y4ASp_K0Hkz:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
