### PR TITLE
ui: Sessions page reintegration

### PR DESCRIPTION
**Pull request by vladlos**
update cluster-ui to latest version, minor updates to sessions,
sessions details and statements details pages to provide new
props needed by cluster-ui components.

Release note (ui): none

### CODE REVIEW

**Comment by elkmaster** [comment]
corresponding yarn vendors pr https://github.com/cockroachdb/yarn-vendored/pull/57

**Review by dhartunian — APPROVED** [review]
:lgtm: I retriggered teamcity build. let me know if it continues to fail.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59539#-:-MUB3ev22hzfsyamIqYf:b-28iir7)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
