### PR TITLE
kvserver/rangefeed: remove lockedRangefeedStream

### PR DESCRIPTION
**Pull request by wenyihu6**
**kvserver: wrap kvpb.RangeFeedEventSink in Stream**

Previously, we declared the same interface signature twice: once in
kvpb.RangeFeedEventSink and again in rangefeed.Stream. This patch embeds
kvpb.RangeFeedEventSink inside rangefeed.Stream, making rangefeed.Stream a
superset of kvpb.RangeFeedEventSink. This approach makes sense, as each
rangefeed server stream should be a rangefeed event sink, capable of making
thread-safe rangefeed event sends.

Epic: none
Release note: none

---

**kvserver/rangefeed: remove lockedRangefeedStream**

Previously, we created separate locked rangefeed streams for each individual
rangefeed stream to ensure Send can be called concurrently as the underlying
grpc stream is not thread safe. However, since the introduction of the mux
rangefeed support, we already have a dedicated lock for the underlying mux
stream, making the Send method on each rangefeed stream thread safe already.
This patch removes the redundant locks from each individual rangefeed stream.

Epic: none
Release note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
I’m not the performance implication of such changes. The original way has a more fine grained mutex wrapped under every setRangeIDEventSink, but they would need to access the same underlying muxstream lock anyways. I did a small benchmarks for comparison, and it seems that having one mutex is better (less contentions and also faster). I'm not sure how accurate the benchmark is tho since I'm getting different results with code refactoring. 

```
Benchmark
Benchmark/fine_grained_mutexes
Benchmark/fine_grained_mutexes-12         	 1465849	       863.0 ns/op
Benchmark/only_one_mutex
Benchmark/only_one_mutex-12               	 1804202	       644.2 ns/op
PASS
```

```
type SharedCounter struct {
	mu    sync.Mutex
	count int
}

func (s *SharedCounter) Increment() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.count++
}

type Counter struct {
	shared *SharedCounter
	mu     sync.Mutex
}

func NewCounter(shared *SharedCounter) *Counter {
	return &Counter{
		shared: shared,
	}
}

func (c *Counter) Increment() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.shared.Increment()
}

type OneCounter struct {
	shared *SharedCounter
}

func NewOne(shared *SharedCounter) *OneCounter {
	return &OneCounter{
		shared: shared,
	}
}

func (c *OneCounter) Increment() {
	c.shared.Increment()
}

func BenchmarkSeparateMutexes(b *testing.B) {
	sharedCounter := &SharedCounter{}
	counter1 := NewCounter(sharedCounter)
	counter2 := NewCounter(sharedCounter)

	b.ResetTimer()
	var wg sync.WaitGroup
	for i := 0; i < b.N; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			counter1.Increment()
		}()
	}

	for i := 0; i < b.N; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			counter2.Increment()
		}()
	}

	wg.Wait()
	b.StopTimer()
}

func BenchmarkOneMutexes(b *testing.B) {
	sharedCounter := &SharedCounter{}
	counter1 := NewOne(sharedCounter)
	counter2 := NewOne(sharedCounter)

	b.ResetTimer()
	var wg sync.WaitGroup
	for i := 0; i < b.N; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			counter1.Increment()
		}()
	}

	for i := 0; i < b.N; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			counter2.Increment()
		}()
	}

	wg.Wait()
	b.StopTimer()
}

func Benchmark(b *testing.B) {
	b.ReportAllocs()
	b.Run("fine grained mutexes", func(b *testing.B) {
		BenchmarkSeparateMutexes(b)
	})

	b.Run("only one mutex", func(b *testing.B) {
		BenchmarkOneMutexes(b)
	})
}
```

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inhHZ8FaJPBVVKXZ-):*
This assumption feels brittle. What do you think about adding an "annotation method" to `RangeFeedEventSink` called `SendIsThreadSafe` so that implementors need to actively opt-in to implementing the contract?
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inHU7CiKwZpQLJ8LH:-O0inHU7CiKwZpQLJ8LI:b-eapv5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9992a5dafb4a2079567b7b0e94e60eae8c49822/pkg/kv/kvserver/replica_rangefeed.go#L326)):*
> ```Go
> 	var done future.ErrorFuture
> 	p := r.registerWithRangefeedRaftMuLocked(
> 		ctx, rSpan, args.Timestamp, catchUpIter, args.WithDiff, args.WithFiltering, stream, &done,
> ```

Do you understand why we have `kvpb.RangeFeedEventSink` and `rangefeed.Stream`? Should we replace `rangefeed.Stream` with `kvpb.RangeFeedEventSink`?

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nvanbenschoten)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inhHZ8FaJPBVVKXZ-):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This assumption feels brittle. What do you think about adding an "annotation method" to `RangeFeedEventSink` called `SendIsThreadSafe` so that implementors need to actively opt-in to implementing the contract?
</blockquote></details>

I like the idea! Made the changes accordingly. Lmkif you had something else in mind.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inHU7CiKwZpQLJ8LH:-O0jWytXD4-hSXWYN_YR:bd0jrz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9992a5dafb4a2079567b7b0e94e60eae8c49822/pkg/kv/kvserver/replica_rangefeed.go#L326)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you understand why we have `kvpb.RangeFeedEventSink` and `rangefeed.Stream`? Should we replace `rangefeed.Stream` with `kvpb.RangeFeedEventSink`?
</blockquote></details>

I agree that the current implementation feels redundant. In the future PR, as we add more methods to the rangefeed.Stream interface, such as [Disconnect and RegisterRangefeedCleanup](https://github.com/cockroachdb/cockroach/blob/8ceb31e92e532373cb88866d3edb30b2a8b187b5/pkg/kv/kvserver/rangefeed/registry.go#L31-L49), their purposes start diverging. The kvpb.RangeFeedEventSink is a node level concept, and we have other RPC context [tests](https://github.com/cockroachdb/cockroach/blob/294e45d7ee6060c83a8d44e38d75162911205d4d/pkg/rpc/context_test.go#L280-L293) that implement it directly for testing. It doesn’t need to implement functions like Disconnect. On the other hand, rangefeed.Stream is more specific to the rangefeed level and include functions like Disconnect. Wdyt?

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inhHZ8FaJPBVVKXZ-):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I like the idea! Made the changes accordingly. Lmkif you had something else in mind.
</blockquote></details>

I'd actually advise we get rid of the `bool` return value, as that makes the property look optional. The role of the method is to indicate that `Send` **must** be thread-safe in every implementation of `RangeFeedEventSink`. Implementors aren't allowed to return false.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inHU7CiKwZpQLJ8LH:-O0kgKU389vmRfXr3pVm:bcu9d7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9992a5dafb4a2079567b7b0e94e60eae8c49822/pkg/kv/kvserver/replica_rangefeed.go#L326)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I agree that the current implementation feels redundant. In the future PR, as we add more methods to the rangefeed.Stream interface, such as [Disconnect and RegisterRangefeedCleanup](https://github.com/cockroachdb/cockroach/blob/8ceb31e92e532373cb88866d3edb30b2a8b187b5/pkg/kv/kvserver/rangefeed/registry.go#L31-L49), their purposes start diverging. The kvpb.RangeFeedEventSink is a node level concept, and we have other RPC context [tests](https://github.com/cockroachdb/cockroach/blob/294e45d7ee6060c83a8d44e38d75162911205d4d/pkg/rpc/context_test.go#L280-L293) that implement it directly for testing. It doesn’t need to implement functions like Disconnect. On the other hand, rangefeed.Stream is more specific to the rangefeed level and include functions like Disconnect. Wdyt?
</blockquote></details>

That makes sense to me, thanks for explaining. Maybe we should have the `rangefeed.Stream` interface embed the `kvpb.RangeFeedEventSink` interface so that it's a clear superset.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inhHZ8FaJPBVVKXZ-):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd actually advise we get rid of the `bool` return value, as that makes the property look optional. The role of the method is to indicate that `Send` **must** be thread-safe in every implementation of `RangeFeedEventSink`. Implementors aren't allowed to return false.
</blockquote></details>

I see what you mean. It's a bit tricky here since we actually do have a few test streams that have thread unsafe Send method. For example, https://github.com/cockroachdb/cockroach/blob/c8476d10b7509d766f7a411f89f827968cab3484/pkg/kv/kvserver/rangefeed/bench_test.go#L206 and https://github.com/cockroachdb/cockroach/blob/c8476d10b7509d766f7a411f89f827968cab3484/pkg/rpc/context_test.go#L291-L293. And they need to conform to the `RangeFeedEventSink` interface. Do you see a clean way to handle this? I could think of 
- define another kvpb.TestStream struct that implements the `SendIsThreadSafe()` interface. Other test streams will embed the *kvpb.TestStream struct to opt in. 
- change each test stream to become thread safe 
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inHU7CiKwZpQLJ8LH:-O0l4-dD9zMbnKuqSnqr:bve5768) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9992a5dafb4a2079567b7b0e94e60eae8c49822/pkg/kv/kvserver/replica_rangefeed.go#L326)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That makes sense to me, thanks for explaining. Maybe we should have the `rangefeed.Stream` interface embed the `kvpb.RangeFeedEventSink` interface so that it's a clear superset.
</blockquote></details>

Aha, great idea. I will make the changes in the future pr above.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0inhHZ8FaJPBVVKXZ-):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I see what you mean. It's a bit tricky here since we actually do have a few test streams that have thread unsafe Send method. For example, https://github.com/cockroachdb/cockroach/blob/c8476d10b7509d766f7a411f89f827968cab3484/pkg/kv/kvserver/rangefeed/bench_test.go#L206 and https://github.com/cockroachdb/cockroach/blob/c8476d10b7509d766f7a411f89f827968cab3484/pkg/rpc/context_test.go#L295. And they need to conform to the `RangeFeedEventSink` interface. Do you see a clean way to handle this? I could think of 
- define another kvpb.TestStream struct that implements the `SendIsThreadSafe()` interface. Other test streams will embed the *kvpb.TestStream struct to opt in. 
- change each test stream to become thread safe
</blockquote></details>

I went with the first proposed idea above. Lmk if you have a better idea in mind.

**Review by nvb — COMMENTED** [review]
> Reviewed 12 of 12 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvpb/api.go` line 2519 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0lWwez3S6PdM_gGmL7:-O0lWwez3S6PdM_gGmL8:bbdhma5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26043d15b3b9e6986c3635118974cf8a1815e21/pkg/kv/kvpb/api.go#L2519)):*
> ```Go
> }
> 
> // Every stream used in prod code implementing the RangeFeedEventSink interface
> ```

This type doesn't feel like it belongs in the top-level `kvpb` package. Arguably, `RangeFeedEventSink` doesn't even belong here, but it's more reasonable.

I'd suggest that we don't introduce this at all. Just because a stream is used in a test, doesn't necessarily mean it doesn't need to be thread-safe. Instead, we should define a `SendIsThreadSafe` method on all `RangeFeedEventSink` structs. That gives us a place to talk about thread safety. Either we then make these implementations thread-safe or we just comment about how the test has organized for the sink to not need thread safety (so in a way, the test is providing the thread safety).
___
*[`pkg/kv/kvpb/api.go` line 2531 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0lYd990lFsPvsbRZ7J:-O0lYd990lFsPvsbRZ7K:b7p0lb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26043d15b3b9e6986c3635118974cf8a1815e21/pkg/kv/kvpb/api.go#L2531)):*
> ```Go
> 	// Context returns the context for this stream.
> 	Context() context.Context
> 	// Send blocks until it sends m, the stream is done, or the stream breaks.
> ```

nit: The parameter is not named here. We should either name it `m`, or replace "sends m" with "sends the RangeFeedEvent".
___
*[`pkg/kv/kvpb/api.go` line 2535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0lWkDC91Tl9TOAj4Oe:-O0lWkDC91Tl9TOAj4Of:bezjnzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26043d15b3b9e6986c3635118974cf8a1815e21/pkg/kv/kvpb/api.go#L2535)):*
> ```Go
> 	Send(*RangeFeedEvent) error
> 	// SendIsThreadSafe is a no-op declaration method. It is a contract that the
> 	// struct has a thread safe Send method.
> ```

nit: s/struct/interface/

nit: s/thread safe/thread-safe/

**Comment by wenyihu6** [comment]
Hm, I just saw this comment on `Send`, and what I'm doing in this pr feels unsafe now 
https://github.com/cockroachdb/cockroach/blob/fc3a17306d53c698397a0e05ec9139f790ada007/pkg/kv/kvserver/rangefeed/registry.go#L36

I think we are no longer providing the guarantee, as we might be accessing the rangeID and streamID fields from different goroutines without mutex protection:
https://github.com/cockroachdb/cockroach/blob/b3237dbf7b2963fc18fd5fc5f394bc87c0db03d3/pkg/server/node.go#L1852-L1859

It seems safe now since Send on the same stream is always called from the same `runOutputLoop` goroutine:
https://github.com/cockroachdb/cockroach/blob/b3237dbf7b2963fc18fd5fc5f394bc87c0db03d3/pkg/kv/kvserver/rangefeed/registry.go#L361 and https://github.com/cockroachdb/cockroach/blob/fc3a17306d53c698397a0e05ec9139f790ada007/pkg/kv/kvserver/rangefeed/registry.go#L408. But it still feels risky and we might change this in the future. Should we change the lock protection to be under `setRangeIDEventSink` and use RWMutex to protect only reads?

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvpb/api.go` line 2519 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0lWwez3S6PdM_gGmL7:-O0noRkwBFFvbIxKk4vh:brxrf2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26043d15b3b9e6986c3635118974cf8a1815e21/pkg/kv/kvpb/api.go#L2519)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This type doesn't feel like it belongs in the top-level `kvpb` package. Arguably, `RangeFeedEventSink` doesn't even belong here, but it's more reasonable.

I'd suggest that we don't introduce this at all. Just because a stream is used in a test, doesn't necessarily mean it doesn't need to be thread-safe. Instead, we should define a `SendIsThreadSafe` method on all `RangeFeedEventSink` structs. That gives us a place to talk about thread safety. Either we then make these implementations thread-safe or we just comment about how the test has organized for the sink to not need thread safety (so in a way, the test is providing the thread safety).
</blockquote></details>

I see. This is much cleaner. Done. 
___
*[`pkg/kv/kvpb/api.go` line 2531 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0lYd990lFsPvsbRZ7J:-O0noWZKC9T25DEdBXug:bmilqin) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26043d15b3b9e6986c3635118974cf8a1815e21/pkg/kv/kvpb/api.go#L2531)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: The parameter is not named here. We should either name it `m`, or replace "sends m" with "sends the RangeFeedEvent".
</blockquote></details>

Ahh oops. Changed it `sends the RangeFeedEvent`. 
___
*[`pkg/kv/kvpb/api.go` line 2535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-O0lWkDC91Tl9TOAj4Oe:-O0nobC09WDkuqbMjlZv:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26043d15b3b9e6986c3635118974cf8a1815e21/pkg/kv/kvpb/api.go#L2535)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: s/struct/interface/

nit: s/thread safe/thread-safe/
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126486#-:-O0nwM976I0eUQmCUgl_:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

**Comment by wenyihu6** [comment]
Thanks for the thorough review!

bors r=nvanbenschoten

**Pull request merged**
