### PR TITLE
sql: drain instead of hard shutdown in DistSQLReceiver.Push

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: drain instead of hard shutdown in DistSQLReceiver.Push**

Previously, when the DistSQLReceiver encountered an error or received
enough rows to satisfy its consumer, it would transition to
`ConsumerClosed` status. I believe this is an incorrect behavior, and in
almost all cases we actually must transition to draining (we already had
several TODOs to do that), the only exception is if we're canceled
(indicated by an error on the context).

My reasoning is that there are certain types of metadata (like
LeafTxnFinalState) that must be received by the gateway to achieve the
correctness, yet that metadata is only collected in the draining state,
so if we go from `NeedMoreRows` to `ConsumerClosed`, we don't get
a chance to collect that meta.

As a concrete example, consider the way we implemented portals with
limits - some SELECT query reads some rows, once the portal limit is
satisfied, an error is returned from `AddRow`, this will currently cause
us to perform a hard shutdown of the flow, and we end up not collecting
spans to refresh. I believe it is a no bueno, and it is confirmed by
a unit test (that we don't drain the required metadata).

This commit fixes this problem by transitioning to draining in all cases
except when the context has an error.

Release note: None

**sql: do not check commErr redundantly in several places**

Previously, several clients of DistSQLReceiver were redundantly checking
`commErr`. The only client that needs to distinguish between the
communication and query execution errors is the main path of
`connExecutor.execWithDistSQLEngine`, and now it is the only one to do
so. Additionally, improve some comments.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:thumbsup:  but let's please add a test.

I'm trying to remember how this all works... I'm surprised that `DistSQLReceiver.ProducerDone` is [a no-op](https://github.com/cockroachdb/cockroach/blob/fb4ce00f4633cbf0417f671d7c0eb8b1d47e5d15/pkg/sql/distsql_running.go#L767). How does a query finish execution? Is it all [coordinated](https://github.com/cockroachdb/cockroach/blob/56ff1a8caf5b94b8fc9f886b5bba83dee1d34eb3/pkg/sql/flowinfra/flow.go#L382) by a "head processor"?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-:-MXIy1fb2bYIpKoBNQpn:b2fo815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXIwOI634dAMiFhTUyh:-MXIwOI634dAMiFhTUyi:baau9na) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc94ea8f943b7f32db1ac50beb702a7b5f96b68/pkg/sql/distsql_running.go#L597)):*
> ```Go
> }
> 
> // checkError checks whether the resultWriter has an error set and updates the
> ```

The dependency seems backwards to me. I see that this new method is not unlike what we had before, but I think it's becoming harder to defend now that you're adding draining to the `DistSQLReceiver`. I don't think `DistSQLReceiver` should ask `resultWriter` about whether it has an error or not. The `resultWriter` doesn't just get errors out of thin air; it's either the `DistSQLReceiver` that pushes errors into it or the `resultWriter` synchronously producing an error when `AddRow` is called. So I'd find everything a lot easier to follow if the `DistSQLReceiver` would just track its own state, and not ask the receiver anything. As is, iI'm unclear about the relationship between `r.status` and what this returns. No?

**Comment by michae2** [comment]
> How does a query finish execution? Is it all [coordinated](https://github.com/cockroachdb/cockroach/blob/56ff1a8caf5b94b8fc9f886b5bba83dee1d34eb3/pkg/sql/flowinfra/flow.go#L382) by a "head processor"?

Unrelated to this PR, but I have been wondering this, too! Maybe something for our session next week?

**Review by yuzefovich — COMMENTED** [review]
> but let's please add a test.

I've pondered about it for a while but couldn't come up with the way to test this. The example that I mentioned in the commit message requires the usages of the PGWire portals feature, so it is very "high level", yet we want to check that certain kind of metadata was emitted on the very low level. The only example of tests of portals with limits in our codebase I know of is data-driven `TestPGTest`, but that won't cut it. I imagine we need to insert some kind of knob into the `ExecutorConfig` so that the `DistSQLReceiver` accumulated all of the metadata (we could use `MetadataCallbackWriter` for this), but I'm not sure how to connect the dots. Do you have some ideas of how we can test this?

> I'm trying to remember how this all works... I'm surprised that `DistSQLReceiver.ProducerDone` is a no-op. How does a query finish execution? Is it all coordinated by a "head processor"?

Essentially yes. In every flow (either row-based or vectorized), we have that `headProc` which runs in the same goroutine as `DistSQLReceiver` is being pushed into. The main loop of running that head processor is https://github.com/cockroachdb/cockroach/blob/df928e46361aa5a0213e5d89ed602dfd6177c385/pkg/sql/execinfra/base.go#L169-L191 where `src` is the processor and `dst` is the `DistSQLReceiver`. The flow can be shutdown for two reasons: either `dst` tells us so by returning `DrainRequested` or `ConsumerClosed` status or `src` returns `nil, nil` for `row, meta` indicating that it has been exhausted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-:-MXJOKcJEu3a0f_Y8Asv:bf2sa5l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/distsql_running.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXIwOI634dAMiFhTUyh:-MXJNeVi5v9B8TXn8UKM:b-kowq3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc94ea8f943b7f32db1ac50beb702a7b5f96b68/pkg/sql/distsql_running.go#L597)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The dependency seems backwards to me. I see that this new method is not unlike what we had before, but I think it's becoming harder to defend now that you're adding draining to the `DistSQLReceiver`. I don't think `DistSQLReceiver` should ask `resultWriter` about whether it has an error or not. The `resultWriter` doesn't just get errors out of thin air; it's either the `DistSQLReceiver` that pushes errors into it or the `resultWriter` synchronously producing an error when `AddRow` is called. So I'd find everything a lot easier to follow if the `DistSQLReceiver` would just track its own state, and not ask the receiver anything. As is, iI'm unclear about the relationship between `r.status` and what this returns. No?
</blockquote></details>

Hm, there are some calls to `DistSQLReceiver.SetError` that can also set the error on `resultWriter` and these calls can occur outside of `Push`. I started going down the route of tracking `execErr` in the `DistSQLReceiver`, but it ended up being essentially the duplicate logic of what we have in `resultWriter`, so I backtracked. Instead, I refactored the code so that `DistSQLReceiver.SetError` is the only place that sets the error, and that method is now responsible for updating the status of the `DistSQLReceiver`. I think it should be cleaner this way, let me know what you think.

**Comment by yuzefovich** [comment]
Note that the first commit is a part of separate PR (a bug uncovered by this PR :) ).

**Comment by yuzefovich** [comment]
Rebased on top of master which now contains the changefeed fix.

**Comment by yuzefovich** [comment]
@andreimatei PTAL. I added a test (which fails on master) that exercises the scenario mentioned in the commit message. After all, it wasn't too bad.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-:-MXbamPS2Thb1-SSFAZA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXIwOI634dAMiFhTUyh:-MXbake92qNMradASPLQ:b-vs1pr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc94ea8f943b7f32db1ac50beb702a7b5f96b68/pkg/sql/distsql_running.go#L597)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, there are some calls to `DistSQLReceiver.SetError` that can also set the error on `resultWriter` and these calls can occur outside of `Push`. I started going down the route of tracking `execErr` in the `DistSQLReceiver`, but it ended up being essentially the duplicate logic of what we have in `resultWriter`, so I backtracked. Instead, I refactored the code so that `DistSQLReceiver.SetError` is the only place that sets the error, and that method is now responsible for updating the status of the `DistSQLReceiver`. I think it should be cleaner this way, let me know what you think.
</blockquote></details>

Looks good.
___
*[pkg/sql/distsql_running_test.go, line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbYuac2XSesAwV8DxZ:-MXbYuadC6WFIrjdfMs0:b-h8pxn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/distsql_running_test.go#L339)):*
> ```Go
> }
> 
> // TestDistSQLReceiverDrainsMeta verifies that the DistSQLReceiver drains the
> ```

I think this test is great. But could you also add a small unit test with just the `DistSQLReceiver` - just pushing an error into it and asserting its draining state?
___
*[pkg/sql/exec_util.go, line 978 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbXcuh1xb3NVzYIgMv:-MXbXcuh1xb3NVzYIgMw:b-830p9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/exec_util.go#L978)):*
> ```Go
> 	// DistSQLReceiverPushCallback, if set, will be called every time
> 	// DistSQLReceiver.Push is called, with the same arguments. It must be
> 	// concurrency-safe.
> ```

Does it need to be "concurrency-safe" indeed? (btw, I think the usual term is thread-safe).
Isn't `DistSSQLReceiver.Push()` only called by one processor, and it's also blocking? Which isn't to say that in your test you don't need a lock around `accumulatedMeta` - you do, but not because of races due to a re-entrant callback.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXIwOI634dAMiFhTUyh:-MXbh6hW-jgCfA8Z9b0f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc94ea8f943b7f32db1ac50beb702a7b5f96b68/pkg/sql/distsql_running.go#L597)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Looks good.
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 978 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbXcuh1xb3NVzYIgMv:-MXbgmj27aTGdq6L5Rk2:b3fznet) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/exec_util.go#L978)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Does it need to be "concurrency-safe" indeed? (btw, I think the usual term is thread-safe).
Isn't `DistSSQLReceiver.Push()` only called by one processor, and it's also blocking? Which isn't to say that in your test you don't need a lock around `accumulatedMeta` - you do, but not because of races due to a re-entrant callback.
</blockquote></details>

I think you're right. I added thread-safety only because the unit test was failing under stressrace, but I don't understand why - can you expand on why the lock around `accumulatedMeta` is needed?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 978 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbXcuh1xb3NVzYIgMv:-MXbkok3CV-Mdiz0ZoBn:b-1aivpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/exec_util.go#L978)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think you're right. I added thread-safety only because the unit test was failing under stressrace, but I don't understand why - can you expand on why the lock around `accumulatedMeta` is needed?
</blockquote></details>

Oh, I guess the reason is simple - we can have multiple queries running concurrently, and each of them will have a separate `DistSQLReceiver`, but all will share the same pushCallback function.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 978 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbXcuh1xb3NVzYIgMv:-MXblg8L9t82gWNNBtrt:b-flfo8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/exec_util.go#L978)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Oh, I guess the reason is simple - we can have multiple queries running concurrently, and each of them will have a separate `DistSQLReceiver`, but all will share the same pushCallback function.
</blockquote></details>

Hm, but isn't it the definition of thread-safety?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 978 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbXcuh1xb3NVzYIgMv:-MXbpmmP-tUElxcUpreE:b-yb4r8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/exec_util.go#L978)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, but isn't it the definition of thread-safety?
</blockquote></details>

Oh, I see, of course. But then I have to say - I think we can do better here :P. Like, how does this this callback even work for your test if all results for all queries in the system go through it? That seems like a recipe for major confusion. How about making the callback into a factory that gets called once per query, takes the query being run, and returns either a channel or another callback which, if not nil, gets stored by the respective `DistSQLReceiver` and then used for every row / metadata message? This way a test can declare exactly which query's results it's interested in capturing?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63032)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/sql/distsql_running_test.go, line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbYuac2XSesAwV8DxZ:-MXby68x7KfZXvy3ZnuM:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/distsql_running_test.go#L339)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this test is great. But could you also add a small unit test with just the `DistSQLReceiver` - just pushing an error into it and asserting its draining state?
</blockquote></details>

Good point, done.
___
*[pkg/sql/exec_util.go, line 978 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63032#-MXbXcuh1xb3NVzYIgMv:-MXc0EUoCR5Ql_VGiiYf:bpxrq3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2674db01a496f13ce7c87684756f58d65d336d62/pkg/sql/exec_util.go#L978)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Oh, I see, of course. But then I have to say - I think we can do better here :P. Like, how does this this callback even work for your test if all results for all queries in the system go through it? That seems like a recipe for major confusion. How about making the callback into a factory that gets called once per query, takes the query being run, and returns either a channel or another callback which, if not nil, gets stored by the respective `DistSQLReceiver` and then used for every row / metadata message? This way a test can declare exactly which query's results it's interested in capturing?
</blockquote></details>

Good point, refactored. The test originally was working as expected because it was relying on an implicit assumption that all internal queries will be executed locally via the root txn, so no `LeafTxnFinalMeta` would be emitted during the test run, but I agree that it would be a source of confusion.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
