### PR TITLE
tests: run acceptance tests with the top level source dir as cwd.

### LINKED ISSUE #9496: tests: acceptance tests don't use a consistent working directory
Compare:
- `make acceptance` locally calls `acceptance/run.sh` which ends up invoking `go test -tags acceptance ./acceptance -run ...`; when invoked this way, `go test` changes to the acceptance sub-dir before launching the tests and **the cwd is the acceptance/ sub-dir**.

- CircleCI and TC first compile the acceptance test binary with `go test -c`, then executes it from the top level with `./acceptance.test ...`; when invoked this way **the cwd is the top-level source dir**.

Now the reason why this matters is that some tests also read files somewhere in the source directory, using relative paths. (At least that's how I found this problem - #9087). 

Since the CCI/TC runs appear to be fine otherwise, I would recommend changing the `acceptance/run.sh` script to do the same as CCI/TC.

cc @tamird @bdarnell thoughts?

### PR DESCRIPTION
**Pull request by knz**
Fixes #9496.

Note that like Ben I do not mind either way. If we find that changing the cwd in TC is the way to go, I'm fine with closing (not merging) this PR.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9498)

### CODE REVIEW

**Comment by jordanlewis** [comment]
LGTM - this makes sense to me as a strategy. I think it's good to assume that the tests are getting run from the top-level source directory.

**Comment by bdarnell** [comment]
I don't think it makes sense to make acceptance tests different from our regular tests in terms of where they are run. I'd rather continue to use `go test` in `acceptance/run.sh` and add `cd acceptance` to the other scripts that run the test binary manually.

**Comment by knz** [comment]
ok PTAL. I'll change the TC config too.

**Comment by knz** [comment]
Merging this as we are not using CircleCI any more anyways.

**Pull request merged**
