### PR TITLE
cli+sql/parser: implement interactive help for SQL syntax and built-in functions

### PR DESCRIPTION
**Pull request by knz**
This is a Friday project in response to some of our users who were asking for better help about which SQL syntax is accepted by CockroachDB.

Summary of new features:

- a new client-side command `\h` can retrieve help about SQL statements.
- a new client-side command `\hf` can retrieve help about built-in functions.
-  if the user makes a syntax error, the syntax error is extended with a suggestion to use \h or \hf to obtain more details about syntax alternatives.
- the CLI shell detects when the user enter `?` followed by Enter and asks for the help immediately (instead of starting a multi-line statement, as is usual when no semicolon is present)
- if the user enters `?` and then presses TAB, the help text is displayed too but the current line remains in the editor. This allows to check the syntax of the current line without invalidating the current state of the prompt (this is useful e.g. when the user is unsure about something in the middle of a transaction)

Also this patch retires HELP as a SQL command since `\hf` is not serving this purpose.

**Note:** this patch is *not* implementing *auto-completion*: the TAB key only displays the help text if the user has explicitly entered a question mark first, but does *not* propose a list of identifiers / table names / function names that are valid in that context.

Bonus: under the hood the mechanism is not CLI-specific and can be reused in other clients (and perhaps a web interface), see below.

For example:

```
kena@jepsen-master ~/cockroach % ./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257/> create ?
```
(user presses Enter here)
```
Suggestion:
Command:     CREATE
Syntax:
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS, CREATE USER, CREATE VIEW

root@:26257/>
```

User continues input:

```
root@:26257/> create database ? _
```
(user presses TAB here)

```
root@:26257/> create database ?
Suggestion:
Command:     CREATE DATABASE
Description: create a new database
Category:    schema manipulation
Syntax:
CREATE DATABASE [IF NOT EXISTS] <name>

See also: https://www.cockroachlabs.com/docs/create-database.html

create database ? _
```
(user continues input)

```
root@:26257/t> select id, count( ? _
```
(user presses TAB here)
```
root@:26257/> select id, count(?
Suggestion:
Function:    count
Category:    built-in functions
Calculates the number of selected elements.

Signature                     Category
count(arg: anyelement) -> int [ANYELEMENT]

See also: https://www.cockroachlabs.com/docs/functions-and-operators.html

select id, count(?
```

**How it works (in a nutshell):** when the parser encounters `" ?"` it replaces the normal error message by a context-dependent help text.

This implies in particular that any client can add `?` to a SQL query and get the same help text back from the server as an error message. 

cc @jseldess @sploiselle @mjibson @dt

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13540)

### CODE REVIEW

**Comment by petermattis** [comment]
This is neat, but also not what I expected from tab-completion. I was expecting something similar to tab-completion in a shell or in my editor. If I type `select database = <tab>` I expected a list of databases. If I type `select database = sys<tab>` I'd like it to complete to the `system` database (assuming that was the only one with the prefix `sys`).

**Comment by jseldess** [comment]
I would love the type of tab-completion that @petermattis mentions, but this is great in terms of understanding acceptable syntax! 

I'm a little concerned about including docs urls, though; it's very likely that our url structure will change in the coming months, and though we can put redirects in place as well as update the cockroach code, it might be overkill to have them in there. @knz, @sploiselle, what's your opinion? Does the benefit of including direct links outweigh the eventual maintenance?

**Comment by jseldess** [comment]
@knz, it looks like this works only with complete keywords (e.g., `create`, `create user`). Partial keywords sometimes result in syntax errors and other times in high-level suggestions:

```
root@:26257/test> create us
syntax error at or near "us"
create us ??
       ^

create us
```

and sometime result in high-level suggestions:

```
root@:26257/test> show col
Suggestion:
Data manipulation: SELECT, INSERT, UPDATE, UPSERT, DELETE,
                   TABLE, VALUES
Transactions:      BEGIN, COMMIT, ROLLBACK, SAVEPOINT*
Data definition:   CREATE, DROP, TRUNCATE, ALTER
Privileges:        GRANT, REVOKE
Other:             SHOW, SET, EXPLAIN

More: https://www.cockroachlabs.com/docs/sql-statements.html
```

I prefer the latter (high-level suggestions). Is there a reason not to do that all the time?

**Comment by knz** [comment]
@petermattis yes, there was a note about that in one of the commit messages, but I had forgotten to mention it in the PR description. I modified the PR description to highlight this. From a technical perspective auto-completion may be a much larger undertaking because I rather sure our parser/scanner do not expose the right interfaces and we'd need to modify go-yacc to achieve this.

@jseldess entering "TAB" with a partial keyword amounts to expecting auto-completion. This PR most conspicuously does not support auto-completion. 

I will look at whether it is possible to erase the last (invalid, because incomplete) keyword to trigger the help text without syntax error.

**Comment by petermattis** [comment]
> From a technical perspective auto-completion may be a much larger undertaking because I rather sure our parser/scanner do not expose the right interfaces and we'd need to modify go-yacc to achieve this.

I agree that auto-completion is much harder technically. I'm interested in what other people think of the ergonomics of this. I recall there is a postgres cli that does fancy auto-completion (not psql). Perhaps it is worth investigating how it achieves that.

**Comment by petermattis** [comment]
https://github.com/dbcli/pgcli

**Comment by dt** [comment]
I generally agree with @petermattis -- my expectation would be for TAB to complete names and identifiers with valid values (i.e. by querying the list of tables, columns, etc).

I realize this implies that completions involve a round trip to a remote host rather than a pure local computation. That said, when I was first looking at adding builtin function help to the CLI, we discussed rendering client side vs querying the server and thought maybe going to the server was better anyway, so you'd be sure the version for which you're getting help matches what actually runs if you execute it. Our choice of a stable, standard wire protocol means older clients should often continue to work with newer servers, so mismatch there isn't unreasonable to expect.

**Comment by dt** [comment]
Whoops, I also meant to say this is really, really cool stuff, and I'd love to see this kind of help info land in the client one way or another, and don't want my nits on implementation choices to take away from that at all.

**Comment by knz** [comment]
@dt thanks for the feedback. Yes our CLI is already talking to the server anyway (for example to display the current database and txn state in the prompt) so there is no real conceptual/principled objection to do so for auto-completion.

My issue with auto-completion is a technical one however: you need support from the LALR parser generator (specifically, it needs to expose the table of "next possible tokens from the current state" and go-yacc does not do this currently, unlike e.g. bison).

Meanwhile, I also think there is wisdom in not freezing initiative just because the intermediate stage is not as good as the desired end result.

**Comment by mjibson** [comment]
I like the function help docs here, especially the removal of HTML from them. We'll have to change the docs generator, but that's easy.

**Comment by sploiselle** [comment]
Quick note that we should have all of the URLs tested in CI to make sure they don't 404; if they do 404, open an issue to update the link and ping the tech writers to update in the CRDB source.

**Comment by knz** [comment]
@sploiselle Good idea. I'll look into this.

@petermattis `pgcli` uses its own non-LALR parser implemented in Python (from https://pypi.python.org/pypi/sqlparse). There's also a lot of logic to fuzzy-match the input with expert rules of the form "if the entry ends with this token then suggest that". We'd need all of this to be nearly as good. I suggest if auto-completion and a nice interface are a thing that we try invest some efforts to make `pgcli` work directly with CockroachDB. It "only" uses the pg_catalog virtual tables to inspect the pg database and provide the completion services.

**Comment by jordanlewis** [comment]
Last time I looked into `pgcli`, it used a bunch of correlated subqueries during initialization, which precludes compatibility.

**Comment by petermattis** [comment]
> Last time I looked into pgcli, it used a bunch of correlated subqueries during initialization, which precludes compatibility.

Well, you'll get that fixed soon, right?

**Comment by knz** [comment]
"soon" ahaha :)

But yes we got the best men on it! :trollface:

**Comment by petermattis** [comment]
> Meanwhile, I also think there is wisdom in not freezing initiative just because the intermediate stage is not as good as the desired end result.

True, though there is a cost here due to the increase in surface area of the product. Will there be bugs to fix? Will there be increased feature requests (on top of this feature) that we have to manage?

> My issue with auto-completion is a technical one however: you need support from the LALR parser generator (specifically, it needs to expose the table of "next possible tokens from the current state") and go-yacc does not do this currently, unlike e.g. bison.

go-yacc must have this internally, right? Sounds like something we could possibly expose.

**Comment by mjibson** [comment]
We also have a yacc parser at https://github.com/cockroachdb/cockroach/tree/master/pkg/internal/rsg/yacc that could be extended for this purpose.

**Comment by knz** [comment]
Ok I'll investigate next Friday

**Comment by sploiselle** [comment]
Really cool work, @knz! I'd be interested to see @kuanluo 's perspective on this design and also would love to have UX research done on it because the shell is such an integral part of the software's surface, esp. in the adoption phase.

**Comment by kuanluo** [comment]
I love this idea. :) 

@jseldess and I had just a conversation yesterday also on making better use of our CLI interface for product adoption. I'm all in for better hints, whether it's tabs for completion or better call-outs for graphs to watch in the admin ui. 

CLI is so crucial to adoption at the moment, and we should make it as easy/hand-holding as possible.

**Comment by petermattis** [comment]
> CLI is so crucial to adoption at the moment, and we should make it as easy/hand-holding as possible.

I agree with this statement, but we're also trying to march toward 1.0 and this work isn't on the roadmap. I'm more than happy to see work progress on it during Fridays (that is what they are there for).

**Comment by knz** [comment]
PTAL, in particular look at the new PR description at the top which describes my new shot at this feature.

Biggest change since the first attempt: the contextual help is only invoked **if the user has entered a question mark explicitly** in their SQL shell. If they press "tab" without an explicit question mark, the explanatory message "`tab completion not supported; append '?' and press tab for contextual help`" is printed instead.

Lotsa new features next to this.

**Comment by knz** [comment]
Also with tests now

**Comment by petermattis** [comment]
Excited to see this PR resurrected. The new mechanism of `?<tab>` is better than `<tab>` by itself.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-:-KlP8kmnMk7mO_jfwcuv:bl3dh86)*

**Comment by justinj** [comment]
After trying this, I like it a lot! It seems to break my CLI history, though? If I press enter on a `?` command and then press up, I don't immediately get the `?` command I just entered (which seems like a common use case, if I want help in the middle of writing a query).

---

Review status: 0 of 19 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/help.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUegTFYu7v2f6rOskf:-KlUegTGIEENrns177As:bnu9s2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L38)):*
> ```Go
> }
> 
> // Error implements the fmt.String interface.
> ```

Should this be `String implements...`?

---

*[pkg/sql/parser/help.go, line 71 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUfFnfeiQihx6ag012:-KlUfFnfeiQihx6ag013:b-957keh) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L71)):*
> ```Go
> // helpWith is to be used in parser actions to mark the parser "in
> // error", with the error set to a contextual help message about the
> // current statement.
> ```

As someone not very familiar with the parser/yacc it might be nice to have a note about what returning `1` here signifies, though I guess it's not super important.

---

*[pkg/sql/parser/help.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUfp0YclSW8Y0TbURO:-KlUfp0YclSW8Y0TbURP:brco8ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L98)):*
> ```Go
> 	w := tabwriter.NewWriter(&buf, 0, 0, 1, ' ', 0)
> 	lastInfo := ""
> 	for i, ovl := range d.Definition {
> ```

I know we're all about terse names but `ovl` -> overload took me a minute and I only realized because I'm somewhat familiar with the builtin structure

---

*[pkg/sql/parser/help.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUg_70KNamQ513NkWe:-KlUg_70KNamQ513NkWf:bvz4hcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L146)):*
> ```Go
> // via a (subsequent) \h client-side command.
> var HelpMessages = func(h map[string]HelpMessageBody) map[string]HelpMessageBody {
> 	appendSeeAlso := func(x, pre string) string {
> ```

```go
if pre != "" {
  return x + "\n  " + pre
}
return x
```
feels a little simpler to me, but it might not be Go-y (is there a Go equivalent of "pythonic"?)
and since the name of this function is so specific, maybe the parameter names could be a bit more specific as well? (specifically I'm not sure what `pre` is supposed to refer to)

---

*[pkg/sql/parser/help.go, line 153 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUlIyVcsqoblLVPE7w:-KlUlIyVcsqoblLVPE7x:b-418t23) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L153)):*
> ```Go
> 		return x + suffix
> 	}
> 	srcMsg := h["<source>"]
> ```

This gets appended to itself if you do `SELECT * FROM ?`, is that ok? Also maybe we could put them either at the beginning or end of the map (or pull their contents out as constants) since they're "special"? There doesn't seem to be a way to directly access `<selectclause>`, unless I'm missing something, so maybe that one doesn't have to be in the map at all?

---

*[pkg/sql/parser/help.go, line 181 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUiMUPUk4dzAEtpQpB:-KlUiMUPUk4dzAEtpQpC:b-h78lax) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L181)):*
> ```Go
> 
> Commands:
>   ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
> ```

[aside] maybe I'm stockholm-syndromed from postgres's docs, but I quite like this format, i think it might be good to have them on the docs pages as well (alongside the graphical ones). Did you write all these just for this PR or is there another source for them somewhere?

---

*[pkg/sql/parser/help_test.go, line 284 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUqLuUIl6W3moiBiFH:-KlUqLuUIl6W3moiBiFI:bnwkpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help_test.go#L284)):*
> ```Go
> 		}
> 		t.Run(f, func(t *testing.T) {
> 			_, err := Parse("select " + f + "(?")
> ```

This use case is sooo good! We have to make sure people know about this one!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-:-KlUc3XIw3UXBiR_9wxJ:bgbpfec)*

**Comment by knz** [comment]
Review status: 0 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/parser/help.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUegTFYu7v2f6rOskf:-KldYWttwdktPiV-tWYP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L38)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Should this be `String implements...`?
</blockquote></details>

Done.

---

*[pkg/sql/parser/help.go, line 71 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUfFnfeiQihx6ag012:-KldYlZcG0j728gANJ_Z:byq9z58) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L71)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

As someone not very familiar with the parser/yacc it might be nice to have a note about what returning `1` here signifies, though I guess it's not super important.
</blockquote></details>

Added a comment to clarify.

---

*[pkg/sql/parser/help.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUfp0YclSW8Y0TbURO:-KldZ4y9LbFpjihDZw8u:b9xcamp) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L98)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I know we're all about terse names but `ovl` -> overload took me a minute and I only realized because I'm somewhat familiar with the builtin structure
</blockquote></details>

Done. Also added a comment to clarify.

---

*[pkg/sql/parser/help.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUg_70KNamQ513NkWe:-KldZObq-183ZNxVIQ1U:b-tkd8c7) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L146)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

```go
if pre != "" {
  return x + "\n  " + pre
}
return x
```
feels a little simpler to me, but it might not be Go-y (is there a Go equivalent of "pythonic"?)
and since the name of this function is so specific, maybe the parameter names could be a bit more specific as well? (specifically I'm not sure what `pre` is supposed to refer to)
</blockquote></details>

Done. Good suggestions.

---

*[pkg/sql/parser/help.go, line 153 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUlIyVcsqoblLVPE7w:-Kld_Zd8nTh30PbHvgKe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L153)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This gets appended to itself if you do `SELECT * FROM ?`, is that ok? Also maybe we could put them either at the beginning or end of the map (or pull their contents out as constants) since they're "special"? There doesn't seem to be a way to directly access `<selectclause>`, unless I'm missing something, so maybe that one doesn't have to be in the map at all?
</blockquote></details>

Done.

---

*[pkg/sql/parser/help.go, line 181 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUiMUPUk4dzAEtpQpB:-KldXx2-5xygBltMjNFN:blyhhm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L181)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

[aside] maybe I'm stockholm-syndromed from postgres's docs, but I quite like this format, i think it might be good to have them on the docs pages as well (alongside the graphical ones). Did you write all these just for this PR or is there another source for them somewhere?
</blockquote></details>

I wrote them myself. To my knowledge there is no tool nor known algorithm to do this automatically from a yacc grammar. I like them too!

---

*[pkg/sql/parser/help_test.go, line 284 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUqLuUIl6W3moiBiFH:-KldY34p1hBVsNgRNPOk:bo6apac) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help_test.go#L284)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This use case is sooo good! We have to make sure people know about this one!
</blockquote></details>

Indeed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540)*

**Comment by jordanlewis** [comment]
This is very awesome!

I have one usability suggestion. It is very jarring to see the prompt get removed after I tab-complete the`?` - it leaves me confused to the state of my shell.

It seems that after you tab-complete a `?` you are left back in a normal prompt mode - if that's the case I'd strongly prefer the `root@26257/>` prompt to still be printed at the start of the line after the help text.

---

Review status: 0 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/parser/help.go, line 181 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUiMUPUk4dzAEtpQpB:-KleALMhy5-TD3sl4o5C:br1rjx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L181)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I wrote them myself. To my knowledge there is no tool nor known algorithm to do this automatically from a yacc grammar. I like them too!
</blockquote></details>

This is all very good writing! I am afraid it will rot though... hmm

---

*[pkg/sql/parser/sql.y, line 429 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KleCuKinio_V6FAwBrW:-KleCuKjISEjHy89f-yp:b-mo3en0) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a42c746b55a9b6d81c97d70807a1887a12babd/pkg/sql/parser/sql.y#L429)):*
> ```Yacc
> %type <Statement> show_tables_stmt
> %type <Statement> show_testing_stmt
> %type <Statement> show_transaction_stmt
> ```

I'm confused why all of this refactoring was necessary - help me understand?

---

*[pkg/sql/parser/sql.y, line 971 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KleD115nzhOO8r7T6Ff:-KleD115nzhOO8r7T6Fg:bhvbh2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a42c746b55a9b6d81c97d70807a1887a12babd/pkg/sql/parser/sql.y#L971)):*
> ```Yacc
>   ALTER TABLE qualified_name SCATTER
>   {
>     /* SKIP DOC */
> ```

What are these SKIP DOCs for?

---

*[pkg/sql/parser/sql.y, line 1235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KleD8y39Ek0HHKUF4Bl:-KleD8y39Ek0HHKUF4Bm:b5v4saa) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a42c746b55a9b6d81c97d70807a1887a12babd/pkg/sql/parser/sql.y#L1235)):*
> ```Yacc
> | create_database_stmt HELPTOKEN %prec UMINUS { return helpWith(sqllex, "CREATE DATABASE") }
> | create_index_stmt              %prec VALUES
> | create_index_stmt HELPTOKEN    %prec UMINUS { return helpWith(sqllex, "CREATE INDEX") }
> ```

Is UMINUS just the closest precedence rule to what we need?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-:-Kle9hcrXjnrYVCrv-xG:b8vpz7l)*

**Comment by mjibson** [comment]
Assuming there's a consensus that this is a good solution, do you plan on breaking up this PR into smaller PRs? The diff is too large to correctly review.

**Comment by mjibson** [comment]
I really like that this is built into the parser instead of a client-side-only extension. Being able to get, say, live help context during typing in a webpage would be awesome.

**Comment by knz** [comment]
@mjibson I thought you could review commit by commit in reviewable? I have been careful to ensure that each commit is touching just one bit of functionality.

@jordan: I added the missing prompt.

---

Review status: 0 of 19 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/help.go, line 181 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KlUiMUPUk4dzAEtpQpB:-KleErscnaNywr_yB-5a:bxos4f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/192c97b820de6857ce7dced1f61826b85741142c/pkg/sql/parser/help.go#L181)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is all very good writing! I am afraid it will rot though... hmm
</blockquote></details>

This is simply a matter of ensuring people who touch the grammar are taught to look at this file too.

---

*[pkg/sql/parser/sql.y, line 429 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KleCuKinio_V6FAwBrW:-KleF2cGHXyQkJcqt9EZ:bopiuum) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a42c746b55a9b6d81c97d70807a1887a12babd/pkg/sql/parser/sql.y#L429)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm confused why all of this refactoring was necessary - help me understand?
</blockquote></details>

You want a different help text to show up for e.g. `SHOW COLUMNS` vs `SHOW TABLES`.
Like I did, you could start by trying with a single rule like this:
```
show : 
  SHOW TABLES error { return help }
| SHOW TABLES FROM ...
| SHOW COLUMNS error { return help }
| SHOW COLUMNS
```

Now if you do this and enter `SHOW COLUMNS ?` you get the help, all fine and dandy.
However, if you enter `SHOW COLUMNS FROM blah ?`, where the prefix "SHOW COLUMNS FROM blah" **is a valid statement**, the parser will *reduce* the non-terminal (and generate a Show AST node), and arrive back into the top-level "statement list" non-terminal. Any information that was distinguishing  "SHOW COLUMNS"  from "SHOW TABLES" has been lost when the eventual "?" is encountered.

In order to work around this you need to write thus:

```
show:
  show_tables
| show_tables HELPTOKEN { return help }
| show_columns
| show_columns HELPTOKEN {return help }
```

---

*[pkg/sql/parser/sql.y, line 971 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KleD115nzhOO8r7T6Ff:-KleG35CVPjw4bHLVTQp:bls2qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a42c746b55a9b6d81c97d70807a1887a12babd/pkg/sql/parser/sql.y#L971)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What are these SKIP DOCs for?
</blockquote></details>

Some of Matt's magic, to ensure the corresponding syntax rules are not emitted in the railroad diagrams in the docs.

---

*[pkg/sql/parser/sql.y, line 1235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KleD8y39Ek0HHKUF4Bl:-KleG7yaBvHEO2THPiBc:b-4sq23s) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a42c746b55a9b6d81c97d70807a1887a12babd/pkg/sql/parser/sql.y#L1235)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is UMINUS just the closest precedence rule to what we need?
</blockquote></details>

It does not matter which precedence is used, as long as the one with HELPTOKEN is higher than the other one, to force the parser to prefer to shift (consume HELPTOKEN) over reduce.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-:-KleGNGmnX93BwBoolQD:biiz6g1)*

**Comment by knz** [comment]
All right, this is rebased and again gtg. I'll schedule a sit-down so we can plow this through.

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r3, 7 of 7 files at r4, 2 of 2 files at r5, 1 of 1 files at r7, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/sql.y, line 2407 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KstDAskftVWCxdi4HMR:-KstDAskftVWCxdi4HMS:bjt73vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/90840ef6031507deb4f8f7af107951c12830fd4f/pkg/sql/parser/sql.y#L2407)):*
> ```Yacc
> 
> help_stmt:
>   HELP unrestricted_name
> ```

I suppose no one cares we're getting rid of this token,right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-:-KstDkhXJkA8RENwQ8Kq:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 26 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/parser/sql.y, line 2407 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540#-KstDAskftVWCxdi4HMR:-KsuTv1mCBsb4OsGiR4n:b-ykm882) ([raw file](https://github.com/cockroachdb/cockroach/blob/90840ef6031507deb4f8f7af107951c12830fd4f/pkg/sql/parser/sql.y#L2407)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I suppose no one cares we're getting rid of this token,right?
</blockquote></details>

Yes; there was a TODO in the code to replace it by something more flexible; together the new `\hf` and previously introduced  `crdb_internal.builtin_functions` serve this purpose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13540)*

**Comment by knz** [comment]
And there was much rejoicing.

Thanks for the reviews and feedback, everyone!

**Pull request merged**
