### PR TITLE
SQL: show the hight latency SQL exceed a specified time

### LINKED ISSUE #14832: SQL: show the hight latency SQL exceed a specified time
**FEATURE REQUEST**

We want to show the high latency SQL exceed a specified time, So we could do some optimization for these hight latency SQL.

And we want the high latency SQL could log out in a independent log file not in the table `node_statement_statistics`, So we didn't should worry about the hight latency SQL could be refreshed out.

### PR DESCRIPTION
**Pull request by a6802739**
fixes #14832.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/app_stats.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836#-KhWINkHD5dbPy0o0pKb:-KhWINkHD5dbPy0o0pKc:b-hxx9z7) ([raw file](https://github.com/cockroachdb/cockroach/blob/93f5fa8224d7cef354f61f34818e6b4b3db23d04/pkg/sql/app_stats.go#L59)):*
> ```Go
> // exceed，so we can store this sql into the table node_statement_statistics.
> var SQLSpecifiedTime = envutil.EnvOrDefaultFloat(
> 	"COCKROACH_SQL_Specified_TIME", 0.1,
> ```

1) Please use the name `COCKROACH_SQL_STATS_SVCLAT_THRESHOLD` instead.
2) Make the default 0. I understand that you need this set to 100ms, but for us the feature needs to be enabled for all latencies. You can set the variable explicitly for your nodes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836)*

**Comment by a6802739** [comment]
@knz , thanks for your review.

**Comment by knz** [comment]
Thank you so much! I think this change is all right, but then perhaps the documentation could be improved a little. Please accept my apologies for not highlighting this in my first review.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/app_stats.go, line 58 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836#-KhXDrifazB6iWP3lSs8:-KhXDrig9OL2FMFG9VXq:b4rwu6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb7c2c254465c316ed7bef59b9fe2ab8f0a95786/pkg/sql/app_stats.go#L58)):*
> ```Go
> // SQLThreshold specify the time that when the sql's consume time
> // exceed，so we can store this sql into the table node_statement_statistics.
> var SQLThreshold = envutil.EnvOrDefaultFloat(
> ```

OK on second read I think we need to improve this comment a little. :smile_cat: 

"SQLThreshold specifies the minimum amount of time consumed by a SQL statement
before it is collected for statistics reporting."

Also I think the name "SQLThreshold" is not precise enough; perhaps "SQLStatiCollectionLatencyThreshold" would be clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836#-:-KhXEKo0dJyH3N4Cgt2F:b-cwzsvf)*

**Comment by a6802739** [comment]
@knz , Thanks a lot. And Thanks for your guidance.

**Comment by knz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/app_stats.go, line 58 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836#-KhXIgXvVX4mrsmCossE:-KhXIgXwhbwUswNGp2n_:bd5kg15) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e99114a9758940abbadfea2d28ae4e4e69f3096/pkg/sql/app_stats.go#L58)):*
> ```Go
> // SQLStatiCollectionLatencyThreshold specifies the minimum amount of time
> // consumed by a SQL statement before it is collected for statistics reporting.
> var SQLStatiCollectionLatencyThreshold = envutil.EnvOrDefaultFloat(
> ```

Sorry I made a mistake that should have been "SQLStatsCollectionLatencyThreshold". I am jetlagged from a recent trip and making many mistakes!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836)*

**Comment by a6802739** [comment]
@knz , done. :)

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/app_stats.go, line 56 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836#-KhXLtqKk_5Y7RmhfVBG:-KhXLtqKk_5Y7RmhfVBH:bw50uhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc7cbef1c2beec2932cbfe990c413ae8ea99e261/pkg/sql/app_stats.go#L56)):*
> ```Go
> )
> 
> // SQLStatiCollectionLatencyThreshold specifies the minimum amount of time
> ```

Yes but the comment still needs to be updated :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14836#-:-KhXLvr-GktgcvJ6_SKQ:bnfp4nl)*

**Comment by a6802739** [comment]
@knz , done :).

**Comment by knz** [comment]
Yes, this works, thanks.

**Pull request merged**
