### PR TITLE
optbuilder: safer partial index predicate normalization

### PR DESCRIPTION
**Pull request by mgartner**
#### optbuilder: eliminate redundant building of partial index predicates

This commit removes unnecessarily building partial index predicates for
each index of a table when determining arbiter indexes for an UPSERT or
INSERT ON CONFLICT statement. The partial index predicates already have
been built and added to the table metadata, so we retrieve predicates
rather than rebuilding them.

Release note: None

#### optbuilder: normalize partial index predicates with a FakeRel

Previously we normalized a partial index predicate for table metadata by
wrapping a scope's expression in a Select with the predicate as a
filter. Prior to the addition of virtual computed columns, the scope's
expression was always a Scan. With virtual columns, the expression could
be a Project. This led to issues because normalization rules could
reorder the Select and Project, making it hard to extract the normalized
filters. The previous solution of manually changing the scope's
expression from a Project to its input Scan was hacky.

Now we construct a FakeRel with the same logical properties as the
scope's expression to be used as the Select's input. This provides
consistent behavior that does not rely on the type of expression in the
scope.

Release note: None

#### optbuilder: make partial index normalization safer

We normalize a partial index predicate in table metadata by constructing
a Select with the predicate as a filter. Previously we were not explicit
about what types of expressions should result from the construction of
the Select. This led to a hard-to-detect correctness bug for INSERT ON
CONFLICT statements which was fixed in #59816.

Now we explicity require the resulting expression to be one of three
types. If the type is not one of the three, we panic, which is
preferrable to a correctness bug.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

[nit] in the commit/PR message: "from a Project to its input select" -> shouldn't this be "from a Project to its input scan"?

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59879#-:-MT5mXYa5bHlXGApY5IA:bmerml3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/partial_index.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59879#-MT5n0SYEyy7Yvi-4cAM:-MT5n0SYEyy7Yvi-4cAN:b4q632c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee372521cca86358712e5583b1dee55549176ea/pkg/sql/opt/optbuilder/partial_index.go#L186)):*
> ```Go
> 		// If the expression has been normalized to a Values expression, then
> 		// the filters were normalized to false and the Select and FakeRel were
> 		// eliminated. So, return a false filter.
> ```

is it worth adding an assertion here that cardinality is zero?

**Review by RaduBerinde — APPROVED** [review]
:lgtm: This is much cleaner and safer!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59879#-:-MT6fz876yt4xXmJGmg5:b-qo1lcx)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
Fixed the commit/PR message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59879#-:-MT7JjfMBQ2XJ4yc2nm1:bhg5awd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/optbuilder/partial_index.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59879#-MT5n0SYEyy7Yvi-4cAM:-MT7JLrZ1b92Dola4M74:b-eb7ch9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee372521cca86358712e5583b1dee55549176ea/pkg/sql/opt/optbuilder/partial_index.go#L186)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is it worth adding an assertion here that cardinality is zero?
</blockquote></details>

Good idea. In theory it should always be zero, but if it's not it's better to panic than potentially cause correctness bugs.

**Pull request merged**
