### PR TITLE
sql: add the 'every' aggregate function

### LINKED ISSUE #45842: sql: add support for the EVERY boolean aggregate function
Repro:
```
root@:26257/defaultdb> SELECT every(true);
ERROR: unknown function: every()
```
EXPECTED: Should work, since EVERY works in PG.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #45842.

Release justification: low risk update to functionality
Release note (sql change): This PR adds the `every` aggregate function.

### CODE REVIEW

**Comment by rohany** [comment]
Not sure if there is an easier way of just translating the every function into `bool_and` -- maybe something in the optimizer can make this easier?

**Comment by andy-kimball** [comment]
As far as I understand, this function is exactly equivalent to `bool_and`, so it should definitely be an optimizer thing. I hadn't realized that before.

**Comment by rohany** [comment]
Sounds good -- editing the distsql infra seemed wrong. I'll still have to make a scalar for it though, right?

**Comment by andy-kimball** [comment]
No need for a scalar. We'll just create the `BitAnd` scalar operator directly.

**Comment by rohany** [comment]
Alright done. Two things though:
* I want to include the distsqlversion bump because of some other aggregates that have been added that need a bump.
* I'm leaning on keeping the `every` entry in the aggregate funcs map so that a docs entry gets generated for it -- not sure if there is an easy way around that

**Comment by andy-kimball** [comment]
___
*[pkg/sql/rowexec/version_history.txt, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46059#-M2H3AXw8pbcQ7GPG4t7:-M2H3AXw8pbcQ7GPG4t8:bwgm4qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9108d5af472e6f7d6cb2efb30614a70566a1751c/pkg/sql/rowexec/version_history.txt#L109)):*
> ```
>     - Change how DArray datums are hashed for distinct and aggregation operations.
> - Version: 28 (MinAcceptedVersion: 28)
>     - Some new aggregate functions have been added (BIT_AND, BIT_OR, CORR)
> ```

Haven't `BIT_AND` and `BIT_OR` been around for a while?

**Review by andy-kimball — COMMENTED** [review]
That's fine to keep it in the map.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46059#-:-M2H3I2q-6cDnbfScWMa:b1k89i3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @rohany, and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46059)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @rohany)

___
*[pkg/sql/rowexec/version_history.txt, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46059#-M2H3AXw8pbcQ7GPG4t7:-M2JMm9oBwCPiNOjtyTd:b-cq3h7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9108d5af472e6f7d6cb2efb30614a70566a1751c/pkg/sql/rowexec/version_history.txt#L109)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Haven't `BIT_AND` and `BIT_OR` been around for a while?
</blockquote></details>

For a few months, yes.

I don't think bumping up the version here is strictly required, yet it is beneficial. I believe without the bump the following can occur in a mixed version cluster:
- the gateway node has the newest version that supports `BIT_AND`, so when the query with this function is issued against the gateway, it thinks everything is great, so it sends out the flow specifications containing this function to remote nodes 
- the remote nodes, however, are running an older version which doesn't have the support for `BIT_AND`, so they will return an error to the gateway because they don't recognize the constant that corresponds to `BIT_AND`, and the whole query will fail.

The important point is that we do not change the order of aggregate functions (i.e. the respective constants remain unchanged), so there is no change of some "internal" error or a crash due to aggregates mismatch. (If my understanding is incorrect, please let me know :) )
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46059#-M2JORuFEpcPdFHQYXvq:-M2JORuFEpcPdFHQYXvr:b1bz7hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9108d5af472e6f7d6cb2efb30614a70566a1751c/pkg/sql/sem/builtins/aggregate_builtins.go#L148)):*
> ```Go
> 	),
> 
> 	"every": makeBuiltin(aggProps(),
> ```

nit: these functions are sorted lexicographically.

**Comment by rohany** [comment]
Sorry, I misread the dates on the commit that added bit_and and bit_or.

> I don't think bumping up the version here is strictly required, yet it is beneficial. I believe without the bump the following can occur in a mixed version cluster:

Yeah, this is what I'm thinking as well.

**Review by yuzefovich — APPROVED** [review]
:lgtm: but I believe we need an approval from a tech lead or from Andy K since we're in stability period.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46059#-:-M2JyPEk-DoO4A9QP9UF:bakjq5v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rohany)

**Comment by rohany** [comment]
cc @andy-kimball for approval

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46059#-:-M2YwBxSBRRUEzf6nIwz:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @rohany)

**Pull request merged**
