### PR TITLE
roachtest: integrating roachprod library into roachtest

### PR DESCRIPTION
**Pull request by healthy-pod**
This patch replaces the use of roachprod binary in roachtest
by roachprod library.

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
Haven't had a chance to review this yet, but perhaps we should run this branch through one of the nightly pipelines before merging. That might uncover problems that are hard to find during review given the many idiosyncrasies of the roachtest and roachprod code.

**Comment by tbg** [comment]
Yep, that's a good idea, and I would add that the timing of such a run is important to avoid spurious failures. Should check when the regular nightly runs end and to kick off this build around that time (it can probably be scheduled).
Probably good doing a review pass first though.

**Review by tbg — APPROVED** [review]
I tried to review this but it's just too much. I think we need to call it LGTM once we've gone through a one-off run and looked into the resulting failures, and did a sanity check to make sure the artifacts look ok.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-:-MqTvTQx-gGdclPKykuj:b52bxam)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod and @rail)

___
*[pkg/cmd/roachtest/cluster.go, line 1782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-MqTKN8uE5VGI0RsFS-h:-MqTKGZS6VdoH9XYwVVA:bzdn3dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab923f3ead830e6c6dc3412182ffe1202c28d35/pkg/cmd/roachtest/cluster.go#L1782)):*
> ```Go
> }
> 
> // worker is only passed by start (not passed with wipe/stop)
> ```

looks like a WIP comment
___
*[pkg/cmd/roachtest/cluster.go, line 1790 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-MqTKOiu5jWsRMJdkDCB:-MqTKOiu5jWsRMJdkDCC:bzdn3dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab923f3ead830e6c6dc3412182ffe1202c28d35/pkg/cmd/roachtest/cluster.go#L1790)):*
> ```Go
> 		}
> 		if _, ok := o.(option.WorkerAction); ok {
> 			// only used with stop/wipe
> ```

looks like a WIP comment
___
*[pkg/cmd/roachtest/cluster.go, line 1791 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-MqTKPC5EUloilXpnVN3:-MqTKPC5EUloilXpnVN4:bpqowv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab923f3ead830e6c6dc3412182ffe1202c28d35/pkg/cmd/roachtest/cluster.go#L1791)):*
> ```Go
> 		if _, ok := o.(option.WorkerAction); ok {
> 			// only used with stop/wipe
> 			// TODO(ahmad/healthy_pod): follow a similar pattern to "start" and avoid using this option.
> ```

Follow-up, right? (I'd rather get this in with no more changes than necessary)
___
*[pkg/cmd/roachtest/cluster.go, line 1807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-MqTKWER1yTP7-KSQSjo:-MqTKWER1yTP7-KSQSjp:b-1zet8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab923f3ead830e6c6dc3412182ffe1202c28d35/pkg/cmd/roachtest/cluster.go#L1807)):*
> ```Go
> }
> 
> // worker is only passed by start (not passed (passed as false) with wipe/stop)
> ```

Ditto WIP comment (real comments are `<method> does this and that and takes these args`), or you can do

```
func (c *clusterImpl) clearStatusForClusterOpt(
  worker bool, // should be set to true if xyz
  opts ...option.Option,
) {
```

(if crlfmt lets you)
___
*[pkg/cmd/roachtest/cluster.go, line 1999 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-MqTL-ah73o6XhLW8Fsm:-MqTL-ah73o6XhLW8Fsn:bre202w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab923f3ead830e6c6dc3412182ffe1202c28d35/pkg/cmd/roachtest/cluster.go#L1999)):*
> ```Go
> }
> 
> // RunWithDetailsSingleNode is just like RunWithDetails but used when 1) operating
> ```

Seems weird since you can pass multiple nodes here. Perhaps add a check that `nodes` is a single node (`len(results) == 1`).
___
*[pkg/cmd/roachtest/cluster.go, line 2003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-MqTL8mMBtoUXu_n8LSb:-MqTL8mN4qFONLR1Zzq6:b-y4o6r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab923f3ead830e6c6dc3412182ffe1202c28d35/pkg/cmd/roachtest/cluster.go#L2003)):*
> ```Go
> // you treat an error from the command. This makes error checking easier / friendlier
> // and helps us avoid code replication.
> func (c *clusterImpl) RunWithDetailsSingleNode(
> ```

haven't gotten there yet, but is this leaking into the cluster interface? Slightly unfortunate but I would still want to get this PR merged before playing code golf.

**Review by rail — APPROVED** [review]
Totally agree with @tbg - looks good, let's run a couple of nightlies to verify it.

> Reviewed 118 of 118 files at r2, 113 of 113 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73607#-:-MqooyDo0THliOvID4GA:beg16rt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

**Comment by healthy-pod** [comment]
I tried to run a [gce nightly](https://teamcity.cockroachdb.com/viewLog.html?buildId=3912396&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly) but it didn't run all tests. Any thoughts why?

**Comment by tbg** [comment]
Still looking, but I'm noticing that the [build output](https://teamcity.cockroachdb.com/viewLog.html?buildId=3912396&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildLog&branch_Cockroach_Nightlies=%3Cdefault%3E#_state=) has tons of output that looks like it came from tests calling `c.Run`, `c.Start`, etc. Is it possible that due to the librarification, output that was previously gathered in a variable (and mostly discarded) now goes to stdout by default? We should make sure this isn't happening to avoid polluting the build log as happens in this run.

**Comment by tbg** [comment]
The [runner logs](https://teamcity.cockroachdb.com/viewLog.html?buildId=3912396&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=artifacts&branch_Cockroach_Nightlies=%3Cdefault%3E#%2F_runner-logs) end rather unexpectedly:

```
01:07:20 test_runner.go:1072: [w1] Selected test: tpccbench/nodes=3/cpu=16 run: 1.
01:07:20 test_runner.go:1081: [w1] Using existing cluster: teamcity-3912396-1639525333-27-n4cpu16. Wiping
01:07:22 test_runner.go:504: [w1] starting test: tpccbench/nodes=3/cpu=16:1
```

I would try running that test in isolation. Maybe there's a call to `os.Exit` somewhere that we're hitting without recording the output? The (roachtest) end of the build output is

```
[01:07:39] :	 [Step 2/3] To see these additional updates run: apt list --upgradable
[01:07:39] :	 [Step 2/3] 
[01:07:39] :	 [Step 2/3] 
[01:07:39] :	 [Step 2/3] *** System restart required ***
[01:07:39] :	 [Step 2/3] 
[01:07:39] :	 [Step 2/3] cockroach is running; see: systemctl status cockroach
[01:07:39] :	 [Step 2/3] 
[01:07:39]i:	 [Step 2/3] Docker event: {"status":"die","id":"a0e89a7adf76744530cc7a69d0cc9de4e5c633abce7318913b0130ed4498f68f","from":"cockroachdb/builder:20211118-190337","Type":"container","Action":"die","Actor":{"ID":"a0e89a7adf76744530cc7a69d0cc9de4e5c633abce7318913b0130ed4498f68f","Attributes":{"exitCode":"0","image":"cockroachdb/builder:20211118-190337","jetbrains.teamcity.buildId":"3912396","name":"jolly_gates"}},"scope":"local","time":1639530459,"timeNano":1639530459609614228}
[01:07:41]i:	 [Step 2/3] Docker event: {"status":"destroy","id":"a0e89a7adf76744530cc7a69d0cc9de4e5c633abce7318913b0130ed4498f68f","from":"cockroachdb/builder:20211118-190337","Type":"container","Action":"destroy","Actor":{"ID":"a0e89a7adf76744530cc7a69d0cc9de4e5c633abce7318913b0130ed4498f68f","Attributes":{"image":"cockroachdb/builder:20211118-190337","jetbrains.teamcity.buildId":"3912396","name":"jolly_gates"}},"scope":"local","time":1639530461,"timeNano":1639530461816868072}
[01:07:41] :	 [Step 2/3] Process exited with code 0
```

so it does seem that "something" just decided to exit zero.

**Comment by healthy-pod** [comment]
Update: I tried to run that test in isolation and it passed without issues. I tried running [another gce nightly](https://teamcity.cockroachdb.com/viewLog.html?buildId=3921031&buildTypeId=Cockroach_Nightlies_WorkloadNightly) and it exited in the same way. I am trying to understand what's happening.

**Comment by tbg** [comment]
Oof, that sucks. No idea. I don't think we ever saw this behavior in the nightlies. I'm not seeing any zero exit codes in `roach{test,prod}` (I checked all non-literals in this list):

```
tobias@td:~/go/src/github.com/cockroachdb/cockroach$ rg -F os.Exit pkg/cmd/roachprod
pkg/cmd/roachprod/main.go
77:			os.Exit(roachprodError.ExitCode())
953:		os.Exit(1)
958:		os.Exit(1)
968:		os.Exit(1)
tobias@td:~/go/src/github.com/cockroachdb/cockroach$ rg -F os.Exit pkg/cmd/roachtest
pkg/cmd/roachtest/test_registry.go
73:		os.Exit(1)
77:		os.Exit(1)

pkg/cmd/roachtest/cluster.go
227:		os.Exit(1)
235:		os.Exit(1)
457:	os.Exit(1)

pkg/cmd/roachtest/main.go
318:		os.Exit(1)
323:		os.Exit(1)
333:		os.Exit(code)
452:// If a 2nd signal is received, it calls os.Exit(2).
479:			os.Exit(2)
482:			os.Exit(2)

pkg/cmd/roachtest/tests/gorm_helpers.go
46:		os.Exit(1)
131:		os.Exit(1)
136:		os.Exit(1)
142:			os.Exit(1)
```

Does this reproduce when you invoke `roachtest` from your own machine?

**Comment by tbg** [comment]
As a nuclear option, you could `defer runtime.PrintStack()` in `func main` of `roachtest`. You could also spawn a goroutine that dumps the stack every minute or so.

It's worth considering if the stdout/stderr problem I mentioned could perhaps cause some other issues, for example if we're blowing up an in-mem buffer somewhere, perhaps we are getting killed by out of memory and the exit code somehow isn't making it out. Just blind guesses at this point but I think cleaning up the output some can't hurt as right now I have no idea if I might be missing something important.

**Comment by healthy-pod** [comment]
Not sure if my question makes sense but is there a thing like a limit on the number of ssh processes forked from a **single process** (i.e. our main Go program)?

**Comment by healthy-pod** [comment]
[This](https://github.com/cockroachdb/cockroach/pull/74086) was the issue! 😄 😄  Ran [another gce nightly](https://teamcity.cockroachdb.com/viewLog.html?buildId=3954408&buildTypeId=Cockroach_Nightlies_WorkloadNightly) and other than a few simple fixes it seems fine (290 passed / 18 failed).

**Comment by tbg** [comment]
Haha, fun bug. But how does this explain the problem? Why does starting an interactive ssh session lead to roachtest shutting down with exit status zero?

**Comment by healthy-pod** [comment]
I am not totally sure about that but I imagine while teamcity is trying to capture the output of roachtest (which is happening all the time), this happens and we start an interactive SSH session (actually that's how the logs end) and teamcity then stops the build (because maybe it knows the process it's monitoring shouldn't enter an interactive SSH session and that it will be there forever). The nightly is running with `--parallelism=16` and the status of the last 16 tests in the build is _"Interrupted by TeamCity on build stop"_

Now that I have typed all of this I remembered I basically divided those 16 tests into two groups and ran them locally in an attempt to reproduce the issue and root-cause it without teamcity, and it was reproduced so it can't be teamcity.

**Comment by healthy-pod** [comment]
Eureka, Eureka! To start an interactive SSH session, `roachprod` calls `syscall.Exec` which invokes the `execve(2)` system call. This system call (quoted from [man7](https://man7.org/linux/man-pages/man2/execve.2.html)) ""causes the program that is currently being run by the calling process to be replaced with a new program, with newly initialized stack, heap, and (initialized and uninitialized) data segments.""

On another note, `syscall` package is now deprecated according to https://pkg.go.dev/syscall and we should use `golang.org/x/sys` instead. Opened an [issue](https://github.com/cockroachdb/cockroach/issues/74098) to track it.

**Comment by srosenberg** [comment]
> Eureka, Eureka! To start an interactive SSH session, roachprod calls syscall.Exec which invokes the execve(2) system call.

Nice find! Do we know which roachtests (and other roachprod dependencies) rely on replacing `roachprod` with `ssh` (i.e., `len(cmdArray) == 0`)? Obviously, we can't have a library do `syscall.Exec` :)

**Comment by healthy-pod** [comment]
Tests in roachtest do not use (and shouldn't use?) **interactive** ssh sessions, so I am assuming if a test in roachtest attempts to call Run (or a variant of Run) with 0 args we should return an error such as "No command passed". The only other tool that depends on roachprod library is the roachprod binary. There are also some other tools (or should I call them scripts?) that I didn't get to work with but seem to use the roachprod binary such as roachprod-stress.

**Comment by healthy-pod** [comment]
@tbg I am waiting to merge #74086 before I merge this. Do I have your approval to do so? [Here's](https://teamcity.cockroachdb.com/viewLog.html?buildId=3962369&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly) the last nightly I ran.

**Comment by tbg** [comment]
LGTM, this will make sure we won't get bored over the holidays :-)

**Comment by healthy-pod** [comment]
@rickystewart say the word and there is light, every start and end hangs on your voice :)

**Comment by rickystewart** [comment]
bors r=rail,tbg

**Pull request merged**
