### PR TITLE
opt: add per-row costs to all filters

### PR DESCRIPTION
**Pull request by madelynnblue**
Previously only the geo lookup join accounted for per-row filter costs,
thus over costing it relative to other joins and select.

### CODE REVIEW

**Comment by mjibson** [comment]
Plan changes:

execbuilder/fk (FK index change)
memo/stats/inverted-join (cross -> lookup)
xform/coster/zone (lookup index)
xform/external/tpcc* (lookup index)

**Review by rytaft — COMMENTED** [review]
Those plan changes look good to me.

> Reviewed 2 of 2 files at r1, 32 of 32 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-:-MBtr0xeECX5aLtM3dy_:bnnhre7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/xform/coster.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-MBtpu93-QbCQtpQnNI2:-MBtpu948Tuc3VbjqrWl:bc1swh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/675ef01f2879fa8e9f8fdfe93e9065c66214a368/pkg/sql/opt/xform/coster.go#L327)):*
> ```Go
> 	inputRowCount := sel.Input.Relational().Stats.RowCount
> 	filterSetup, filterPerRow := c.computeFiltersCost(sel.Filters, util.FastIntMap{})
> 	cost := memo.Cost(inputRowCount) * (cpuCostFactor + filterPerRow)
> ```

Maybe the `cpuCostFactor` should also be included in the per-row cost inside `computeFiltersCost`? Then you could just multiply by `filterPerRow` here.
___
*[pkg/sql/opt/xform/coster.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-MBtqVEj5yuy3UM-RmYi:-MBtqVEj5yuy3UM-RmYj:beey4uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/675ef01f2879fa8e9f8fdfe93e9065c66214a368/pkg/sql/opt/xform/coster.go#L495)):*
> ```Go
> 	numLookupCols := join.Cols.Difference(join.Input.Relational().OutputCols).Len()
> 	perRowCost := lookupJoinRetrieveRowCost + filterPerRow
> 	c.rowScanCost(join.Table, join.Index, numLookupCols)
> ```

looks like the `+` got dropped here, so now `rowScanCost` isn't doing anything.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: modulo Becca's comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-:-MC8DcY4BKzraIXytZfh:bxqmfgp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-MBtqVEj5yuy3UM-RmYi:-MC8CnIQ2OMm2vBuuxUi:bjam93j) ([raw file](https://github.com/cockroachdb/cockroach/blob/675ef01f2879fa8e9f8fdfe93e9065c66214a368/pkg/sql/opt/xform/coster.go#L495)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

looks like the `+` got dropped here, so now `rowScanCost` isn't doing anything.
</blockquote></details>

I think this might explain the otherwise surprising changes to the fk and tpcc tests.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51231)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-MBtpu93-QbCQtpQnNI2:-MC8EAuw0s3cNIeCSx9w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/675ef01f2879fa8e9f8fdfe93e9065c66214a368/pkg/sql/opt/xform/coster.go#L327)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Maybe the `cpuCostFactor` should also be included in the per-row cost inside `computeFiltersCost`? Then you could just multiply by `filterPerRow` here.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-MBtqVEj5yuy3UM-RmYi:-MC8G1cT0qd5GhIMfmZC:b-4m0uvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/675ef01f2879fa8e9f8fdfe93e9065c66214a368/pkg/sql/opt/xform/coster.go#L495)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think this might explain the otherwise surprising changes to the fk and tpcc tests.
</blockquote></details>

Ohh yes! Fixing this removed all plan changes except for memo/stats/inverted-join and left only a bunch of cost changes.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 32 files at r3, 28 of 28 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51231#-:-MC8S1T0BNoR28DM1bmf:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
