### PR TITLE
sql: display locality in SHOW TABLES

### PR DESCRIPTION
**Pull request by otan**
Also reduced the number of joins required on the comments table whilst
I was cleaning around it.

Release note (sql change): crdb_internal.tables and SHOW TABLES now
shows locality data on the tables.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Clever join reduction!

Just one comment on handling NULLs in the locality column.  

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57653#-:-MO28YfT3j_ND21WMbLw:bnfas8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/crdb_internal.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57653#-MO1q_VNAZrG5jKMtDKb:-MO1q_VOAKQPy-QW2Xia:bn2i3xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc06f8441c4a853ca52c7d21b3c38415f06609a/pkg/sql/crdb_internal.go#L333)):*
> ```Go
> 				}
> 				locality := tree.DNull
> 				if c := table.TableDesc().LocalityConfig; c != nil {
> ```

I think there's a problem here with us showing NULL if the LocalityConfig is nil.  All tables with no specified locality will end up showing NULL but these tables have an implicit locality provided that the database is multi-region (they're REGIONAL BY TABLE IN PRIMARY REGION).  Can we put in REGIONAL BY TABLE IN PRIMARY REGION if there is no LocalityConfig and the database is a multi-region database?

I'm a bit torn on whether or not to do it here, or in SHOW TABLES, but I'm leaning towards doing it here so that it can be leveraged in all cases where crdb_internal is queried.

**Comment by otan** [comment]
___
*[pkg/sql/crdb_internal.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57653#-MO1q_VNAZrG5jKMtDKb:-MO2yowW8hocMUwebZyN:b8d4h1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc06f8441c4a853ca52c7d21b3c38415f06609a/pkg/sql/crdb_internal.go#L333)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I think there's a problem here with us showing NULL if the LocalityConfig is nil.  All tables with no specified locality will end up showing NULL but these tables have an implicit locality provided that the database is multi-region (they're REGIONAL BY TABLE IN PRIMARY REGION).  Can we put in REGIONAL BY TABLE IN PRIMARY REGION if there is no LocalityConfig and the database is a multi-region database?

I'm a bit torn on whether or not to do it here, or in SHOW TABLES, but I'm leaning towards doing it here so that it can be leveraged in all cases where crdb_internal is queried.
</blockquote></details>

It would be global, no?

**Comment by otan** [comment]
___
*[pkg/sql/crdb_internal.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57653#-MO1q_VNAZrG5jKMtDKb:-MO2zpyk1cBa0wcEyhXB:b-src1r4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc06f8441c4a853ca52c7d21b3c38415f06609a/pkg/sql/crdb_internal.go#L333)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

It would be global, no?
</blockquote></details>

This should be an error if we always set the table to this value on first region add.

If we're choosing the still have NULL route if not implicitly set, I think we should still different here somehow that it is implicit. Any ideas?

**Comment by otan** [comment]
___
*[pkg/sql/crdb_internal.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57653#-MO1q_VNAZrG5jKMtDKb:-MO4ACKq99O9uq98utaB:bl5fyug) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc06f8441c4a853ca52c7d21b3c38415f06609a/pkg/sql/crdb_internal.go#L333)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

This should be an error if we always set the table to this value on first region add.

If we're choosing the still have NULL route if not implicitly set, I think we should still different here somehow that it is implicit. Any ideas?
</blockquote></details>

As discussed offline, we're happy migrating all tables to be a separate locality when adding the first region since it should be a straightforward transaction across all table descriptors. I've added a TODO on create_table.go to set this by default.

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57653#-:-MO4Kh2F3rbhSDzv2BeK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/crdb_internal.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57653#-MO1q_VNAZrG5jKMtDKb:-MO4KOGsBvcbV67ethK-:b-8e9lhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc06f8441c4a853ca52c7d21b3c38415f06609a/pkg/sql/crdb_internal.go#L333)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

As discussed offline, we're happy migrating all tables to be a separate locality when adding the first region since it should be a straightforward transaction across all table descriptors. I've added a TODO on create_table.go to set this by default.
</blockquote></details>

Let's push this in for now and circle back on the right thing to do at the table level.  I'm still not 100% sold on a separate locality, but that debate is not worth holding this PR up.

**Comment by otan** [comment]
sg! thanks!

bors r=ajstorm

**Pull request merged**
