### PR TITLE
cli/zip: makes it possible to include/exclude specific nodes

### LINKED ISSUE #42953: cli: allow the ability to specify which nodes (by number) are added to the debug zip
`cockroach debug zip` should have a parameter that accepts a selection of node numbers, similar to how roachprod works right now, and only construct the debug.zip from those. 

e.g.:

```bash
./cockroach debug zip --nodes=1,5,8
./cockroach debug zip --nodes=1-5,8-10,12
./cockroach debug zip --nodes=9
```

I'm not sure if this should be on the cli team, so please triage appropriately.

### PR DESCRIPTION
**Pull request by knz**
Fixes #42953 

Release note (cli change): `cockroach debug zip` now supports two
command-line parameters `--nodes` and `--exclude-nodes`. When
specified, they control which nodes are inspected when gathering the
data. This makes it possible to focus on a group of nodes of interest
in a large cluster, or to exclude nodes that `debug zip` would have
trouble reaching otherwise. Both flags accept a list of individual
node IDs or ranges of node IDs, e.g. `--nodes=1,10,13-15`.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-:-M657OjkELVkij-z-4GV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/zip.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M657Bc5-nb5ZAunnilw:-M657Bc5-nb5ZAunnilx:b-9rscif) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip.go#L381)):*
> ```Go
> 
> 			if !zipCtx.nodes.isIncluded(nodeID) {
> 				fmt.Fprintf(stderr, "skipping excluded node %d\n", nodeID)
> ```

Can you also put a file `%d.skipped` in the zip so that we can get an idea of the full node list from looking at it?
___
*[pkg/cli/zip.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M656Mpe2rtMWMJtzdYN:-M656Mpe2rtMWMJtzdYO:b100b0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip.go#L773)):*
> ```Go
> 
> func (r *rangeSelection) Type() string {
> 	return "a-b,c,d-e,..."
> ```

Is this right? What does the interface this is implementing ask for?
___
*[pkg/cli/zip_test.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M656imr5MCX_-RYbyFJ:-M656imsBPDlyrqxjYVP:bdi5qru) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip_test.go#L318)):*
> ```Go
> 		})
> 
> 	// Now do it again and exclude the decommissioned node explicitly.
> ```

It's not decommissioned yet.

**Review by knz — COMMENTED** [review]
TFYR!

bors r=tbg

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-:-M65Fb6m7FJirOO0L95M:bx6iuh9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/cli/zip.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M657Bc5-nb5ZAunnilw:-M65EjCXDVbDS28Ike9J:bdzzslo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip.go#L381)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you also put a file `%d.skipped` in the zip so that we can get an idea of the full node list from looking at it?
</blockquote></details>

FWIW the full node lists is also included in nodes.json.

But I don't mind adding it. Done.
___
*[pkg/cli/zip.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M656Mpe2rtMWMJtzdYN:-M65EWZA1w5daUhEaRW9:bn6nmxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip.go#L773)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this right? What does the interface this is implementing ask for?
</blockquote></details>

Yes this is what shows up in `--help` as an exemplar value:

```
      --exclude-nodes a-b,c,d-e,...
                                                                                    List of nodes to exclude. Can be specified as a comma-delimited list of
                                                                                    node IDs or ranges of node IDs, for example: 5,10-20,23. The default is
                                                                                    to not exclude any node.
```
___
*[pkg/cli/zip_test.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M656imr5MCX_-RYbyFJ:-M65Ehag7tPRpxYM4eSu:b-k2rwtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip_test.go#L318)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's not decommissioned yet.
</blockquote></details>

Good catch. Fixed.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48150)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @tbg)

___
*[pkg/cli/zip.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M656Mpe2rtMWMJtzdYN:-M65KA4g6duAi3xlpi_i:b-whqvw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip.go#L773)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes this is what shows up in `--help` as an exemplar value:

```
      --exclude-nodes a-b,c,d-e,...
                                                                                    List of nodes to exclude. Can be specified as a comma-delimited list of
                                                                                    node IDs or ranges of node IDs, for example: 5,10-20,23. The default is
                                                                                    to not exclude any node.
```
</blockquote></details>

I know it shows up there, but I'm curious/worried that it has other functions where this value isn't adequate. Look at this for example:

https://github.com/cockroachdb/vendored/blob/3b83b9bc60ebe6125772386316cd827ca6437223/github.com/spf13/pflag/flag.go#L361-L380

Clearly it thinks of `Type()` as more of an enum. I don't know what it's used for though.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48150)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @tbg)

___
*[pkg/cli/zip.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M656Mpe2rtMWMJtzdYN:-M65L3-t96IR62HFsSKW:b-4jtehl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip.go#L773)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I know it shows up there, but I'm curious/worried that it has other functions where this value isn't adequate. Look at this for example:

https://github.com/cockroachdb/vendored/blob/3b83b9bc60ebe6125772386316cd827ca6437223/github.com/spf13/pflag/flag.go#L361-L380

Clearly it thinks of `Type()` as more of an enum. I don't know what it's used for though.
</blockquote></details>

Ah, that method is called from various `GetUint8` style methods. I guess it's fine then, it's just never going to retrieve your var ever, but I don't know why it would want that. I don't even know why one would want these methods.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48150)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/cli/zip.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48150#-M656Mpe2rtMWMJtzdYN:-M65MXk81aXnYrU_brsS:b-whyaon) ([raw file](https://github.com/cockroachdb/cockroach/blob/9882ee32c74f754f94a82765bb4b537380370a9b/pkg/cli/zip.go#L773)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ah, that method is called from various `GetUint8` style methods. I guess it's fine then, it's just never going to retrieve your var ever, but I don't know why it would want that. I don't even know why one would want these methods.
</blockquote></details>

I'm doing here what we already do for `--url` and other flags, where this never was considered beyond what `--help` does.

**Pull request merged**
