### PR TITLE
roachtest: add new roachtest to run pg_regress against crdb

### LINKED ISSUE #95768: roachtest: implement a pg_regress runner roachtest
[pg_regress](https://github.com/postgres/postgres/tree/master/src/test/regress) is Postgres's equivalent of our logic test suite. It contains thousands of test cases for Postgres behavior.

Porting all of pg_regress to logictest is more or less a non-starter due to the toil required to encode the expected output for all of the test cases.

However, pg_regress outputs a diff between the expected and actual output at the end of its run. We should use this diff as the source of truth for the roachtest: the roachtest will run the pg_regress tests against CockroachDB and compare the produced diff to the expected diff, failing if the diffs differ.

Jira issue: CRDB-23724

Epic CRDB-25369

### PR DESCRIPTION
**Pull request by rharding6373**
Postgres has a large regression test suite [0,1], analogous to CRDB's logic test suite, with years of contributions. The test runs a set of SQL files against a postgres installation, and diffs the results against expected output from postgres.

In this PR we add a roachtest that runs the pg_regress test suite against CRDB instead of postgres. The test produces the same diffs against the expected postgres output. Since we expect some differences with postgres (e.g., error messages, internal implementation, unsupported features), we additionally diff the test diffs against an expected diff from a previous run of the pg_regress suite against CRDB.

The test fails is the final diff produces any output. If the diff fails due to expected behavior change, the user can copy the test artifact `regression.diffs` to `roachtest/testdata/regression.diffs` for it to be used as the expected output in future runs.

[0] Documentation: https://www.postgresql.org/docs/current/regress.html
[1] Test suite source: https://github.com/postgres/postgres/tree/master/src/test/regress

Epic: CRDB-25369
Fixes: #95768

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Nice! Are there particular reviewers you'd like for this change? It seems like one of SQL Queries engineers would be good, also perhaps Rafi?

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work! Is there a checklist somewhere of test diffs to review?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-:-NkqzEPpCKjE18lNcY-q:b-plext)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, @renatolabs, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nkqy6DH0CF8BikzMSKk:-Nkqy6DI8fsvzM2Eh0Ok:b-p91msi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L142)):*
> ```Go
> 	dataTbls := [...]string{"onek", "tenk1"}
> 	for _, tbl := range dataTbls {
> 		err = c.RunE(ctx, node, fmt.Sprintf(`cat %s/data/%s.data | psql %s -c "COPY %s FROM STDIN"`, pgregressDir, tbl, url, tbl))
> ```

IIRC, COPY FROM <file> actually can be used with `psql`, just not with the builtin CRDB shell. I think this is fine, though.

**Review by rharding6373 — COMMENTED** [review]
Here's the list of diffs that I've reviewed so far here: https://docs.google.com/spreadsheets/d/1f52itpzKOHRCMG0zkiawHke_ZqEYZYbnKHYtlzzf3ws/edit?usp=sharing

I haven't gone through all of them yet, but I think that completing that is orthogonal to merging this PR, so I'm doing both in parallel (unless there are objections to that approach).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-:-NkrJqn0392nAXpBA6xE:b-aia82j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @renatolabs)

**Review by rafiss — APPROVED** [review]
i just had some small nits. nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-:-Nl11pac8SZAUqvN0gPW:bejp4y9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nl0yfrc5Jw5TuSmsaS3:-Nl0yfrc5Jw5TuSmsaS4:bybd0fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L39)):*
> ```Go
> 	node := c.Node(1)
> 	t.Status("setting up cockroach")
> 	c.Put(ctx, t.Cockroach(), "./cockroach", c.All())
> ```

nit: we don't need this `Put` now that https://github.com/cockroachdb/cockroach/pull/113301 has merged
___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nl1-o-F9K6LugQKTn2v:-Nl1-o-F9K6LugQKTn2w:b-la0p6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L381)):*
> ```Go
> 		"cd %s && "+
> 		"make && "+
> 		"./pg_regress --bindir=/usr/bin --host=localhost --port=26257 --user=root "+
> ```

nit: it would be nice to run this as a non-root user, since root is treated specially in many parts of our code (notably by skipping every privilege check)

for ORM tests, we use the following: https://github.com/cockroachdb/cockroach/blob/009c53d8e652bcaceff58ed27d666b8df3d0f45c/pkg/cmd/roachtest/tests/pgjdbc.go#L61-L63
___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nl11c025wPf7vx17Grt:-Nl11c025wPf7vx17Gru:bdzwsd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L520)):*
> ```Go
> -					 "ALTER DATABASE \"%s\" SET lc_numeric TO '"'"'C'"'"';"
> -					 "ALTER DATABASE \"%s\" SET lc_time TO '"'"'C'"'"';"
> -					 "ALTER DATABASE \"%s\" SET bytea_output TO '"'"'hex'"'"';"
> ```

do you know why setting the `bytea_output` setting doesn't work?

**Review by rharding6373 — COMMENTED** [review]
TFTRs! I commented out a few more tests that have proven to be non-deterministic and opened https://github.com/cockroachdb/cockroach/issues/115903 to track adding them back in. Before attempting to merge I will need to run the pg_regress test on a binary built at master. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-:-NlB8pRvAlCxbG375IT8:bbw5mv3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @herkolategan, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nl0yfrc5Jw5TuSmsaS3:-NlAUrKT0f6ziVKOp8mp:b-5kbax0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L39)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: we don't need this `Put` now that https://github.com/cockroachdb/cockroach/pull/113301 has merged
</blockquote></details>

Thanks for the pointer!
___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nkqy6DH0CF8BikzMSKk:-NlAUtaP2C3TREDBrM4a:blp4zbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L142)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

IIRC, COPY FROM <file> actually can be used with `psql`, just not with the builtin CRDB shell. I think this is fine, though.
</blockquote></details>

Thanks, I'll leave as is.
___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nl1-o-F9K6LugQKTn2v:-NlAV0D5AOUawbXpdU8h:bkqvjir) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L381)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it would be nice to run this as a non-root user, since root is treated specially in many parts of our code (notably by skipping every privilege check)

for ORM tests, we use the following: https://github.com/cockroachdb/cockroach/blob/009c53d8e652bcaceff58ed27d666b8df3d0f45c/pkg/cmd/roachtest/tests/pgjdbc.go#L61-L63
</blockquote></details>

Done, thanks for the pointer.
___
*[`pkg/cmd/roachtest/tests/pg_regress.go` line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-Nl11c025wPf7vx17Grt:-NlAV1pk2e0xo6KZF5Nv:b6dvjwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc0e9a8ef428c463405916a8ecbf0a946a8ee94/pkg/cmd/roachtest/tests/pg_regress.go#L520)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know why setting the `bytea_output` setting doesn't work?
</blockquote></details>

CRDB uses hex mode by default, so this line is a no-op. I'm going to leave it out for now, since it simplifies the diff.

**Comment by rharding6373** [comment]
Reviving this pg_regress roachtest PR. The number of non-deterministic tests I had to skip became a significant fraction of all the tests, so I made a few fixes to CRDB (outside of this PR) and added a number of targeted diffs to fix all of the non-deterministic cases I identified. The diffs are generated from running on a CRDB master build from over the weekend, and passed 5 times in a row. PTAL when you have a chance. Thank you!

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work!

> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115187#-:-NosHkLa87cD2EXKjHdZ:bolbkdq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @renatolabs)

**Comment by rharding6373** [comment]
TFTR!

bors r+

**Comment by rickystewart** [comment]
bors r-

Please rebase and fix the build failures.

**Pull request merged**
