### PR TITLE
rocksdb: correctly handle FS that does not support hard links

### LINKED ISSUE #38789: storage: "Failed to link" error creating index on windows
On windows, creating an index on a non-empty table may fail with the following stack trace:

```
# Server version: CockroachDB CCL v19.1.1 (x86_64-w64-mingw32, built 2019/05/15 20:36:28, go1.11.6) (same version as client)
```

```
F190611 16:44:16.118820 183 storage/replica_proposal.go:508  [n1,s1,r23/1:/{Table/53/1/4…-Max}] while ingesting F:\cdb\cockroach-data\auxiliary\sideloading\r0XXXX\r23\i7476.t6.ingested: IO error: Failed to link: F:\cdb\cockroach-data\auxiliary\sideloading\r0XXXX\r23\i7476.t6.ingested to: F:\cdb\cockroach-data/000080.sst: Incorrect function.
goroutine 183 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc00046e100, 0xc00046e1e0, 0x54d7900, 0x1b)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xdb
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5740ec0, 0xc000000004, 0x54d790b, 0x1b, 0x1fc, 0xc000838120, 0x11d)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x961
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3c33680, 0xc0058b47e0, 0x4, 0x2, 0x34dbd4b, 0x16, 0xc0055e4988, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2df
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3c33680, 0xc0058b47e0, 0x1, 0xc000000004, 0x34dbd4b, 0x16, 0xc0055e4988, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x93
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3c33680, 0xc0058b47e0, 0x34dbd4b, 0x16, 0xc0055e4988, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x85
github.com/cockroachdb/cockroach/pkg/storage.addSSTablePreApply(0x3c33680, 0xc0058b47e0, 0xc00058b300, 0x3c7fc20, 0xc000465200, 0x3c56160, 0xc0009fb480, 0x6, 0x1d34, 0xc006050000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:508 +0x412
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc000d76500, 0x3c33680, 0xc0058b47e0, 0xc000340cd0, 0x8, 0x6, 0x1d34, 0x100000001, 0x1, 0x1, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:1868 +0x1495
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc000d76500, 0x3c33680, 0xc0058b47e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:816 +0x13e6
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x3c33680, 0xc0058b47e0, 0xc000d76500, 0x3c33680)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3632 +0x127
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc0008cc000, 0x3c33680, 0xc0058b47e0, 0xc00081b500, 0xc0055e5ed0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3279 +0x13c
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc0008cc000, 0x3c33680, 0xc0009f8000, 0x17)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3620 +0x222
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc00064e000, 0x3c33680, 0xc0009f8000)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:225 +0x221
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x3c33680, 0xc0009f8000)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc000258040, 0xc00078a360, 0xc00008bfb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe8
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xaf
```

We need to make sure that cockroach and/or rocksdb is falling back to copying on platforms where links are not supported.

### PR DESCRIPTION
**Pull request by darinpp**
Ingesting a file from a file system that doesn't
support hard links or from a network location, returns
an error that wasn't handled correctly and the result was
IO error instead of Not Supported status.

Fixes cockroachdb/cockroach#38789

Release justification: Category 2: Bug fixes and low-risk updates to new functionality.

Release note (bug fix): Fixes an issue with creating table indexes
when the server is running on Windows and the store is on a FS
that does not support hard links (ex FAT32 or network share)

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
LGTM, though our docs on how to do RocksDB changes are out of date. Please open a PR on `cockroachdb/rocksdb` with a target branch of `crl-release-6.2.1`. We'll review the RocksDB change there, then get to rubber stamp this PR.

PS You'll need a `Release justification` stanza as well.

**Comment by ajkr** [comment]
@petermattis I talked to @darinpp and we couldn't think of a problem with following the procedure in the out-of-date README.md. My guess is the drawback is we can't comment on individual lines of code, but in cases where the change is small and we don't need to do that, can following either procedure be ok?

**Comment by petermattis** [comment]
> @petermattis I talked to @darinpp and we couldn't think of a problem with following the procedure in the out-of-date README.md. My guess is the drawback is we can't comment on individual lines of code, but in cases where the change is small and we don't need to do that, can following either procedure be ok?

Well, the big thing is that we want is for `crl-release-6.2.1` to be in sync with the submodule pointer. AFAICT right now it is out of sync. I'm fine with omitting the PR step on `cockroachdb/rocksdb`, but please push to the `crl-release-6.2.1` branch.

**Review by ajkr — APPROVED** [review]
Right that is step 7, after we LGTM here. OK then, I'll accept.

**Review by ajkr — APPROVED** [review]
LGTM again, the commit matches head of crl-release-6.2.1 now.

**Comment by kenliu** [comment]
thx for your help with this @darinpp

**Pull request merged**
