### PR TITLE
roachtest: fix schemachange/mixed/tpcc for 19.1

### PR DESCRIPTION
**Pull request by thoszhang**
`schemachange/mixed/tpcc` uses `CREATE TABLE AS` in 19.2. This PR will have the
test correctly create a similar table in 19.1 without using `CREATE TABLE AS`.

See https://github.com/cockroachdb/cockroach/issues/40935#issuecomment-534180196.

Release justification: Fixes a test.

Release note: None

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41079)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @pbardea)

___
*[pkg/cmd/roachtest/schemachange.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41079#-LpdPfcxEuTGn1INSZn7:-LpdPfcxEuTGn1INSZn8:b-pthmoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a96aaf7dc2a2a708da56177526c556b2e798a7/pkg/cmd/roachtest/schemachange.go#L428)):*
> ```Go
> 						if err := runAndLogStmts(ctx, t, c, "mixed-schema-changes-19.1", []string{
> 							`CREATE TABLE tpcc.orderpks (o_w_id, o_d_id, o_id, PRIMARY KEY(o_w_id, o_d_id, o_id));`,
> 							`INSERT INTO tpcc.orderpks SELECT o_w_id, o_d_id, o_id FROM tpcc.order LIMIT 1000;`,
> ```

What's the purpose of this `LIMIT 1000`?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41079)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/cmd/roachtest/schemachange.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41079#-LpdPfcxEuTGn1INSZn7:-LpdQM5LCF7loHxqk6fz:bpo4r6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a96aaf7dc2a2a708da56177526c556b2e798a7/pkg/cmd/roachtest/schemachange.go#L428)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

What's the purpose of this `LIMIT 1000`?
</blockquote></details>

It's just to limit the number of rows to insert so we don't try to read and insert all 30 million rows of `tpcc.order` in this transaction, since I figured that the tables don't have to be identical in 19.1 and 19.2. 1000 might be too conservative, though. Now that I think about it, the best option is probably to just use all the rows to get a similarly-sized table, but use AOST to reduce contention, so I changed it.

**Review by pbardea — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41079#-:-LpdTsNMASkd240qI8YS:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by lucy-zhang** [comment]
TFTR

bors r+

**Pull request merged**
