### PR TITLE
workload: various fixes

### PR DESCRIPTION
**Pull request by danhhz**
See commits for details

### CODE REVIEW

**Comment by benesch** [comment]
> workload,workloadccl: stop using the *Context methods in sql/database
> 
> It does not play well with CockroachDB at all.

Can you expand on this?

> The label is still `ops/sec`; that's much harder to fix, but I'm banking on this being a net usability win until that can happen.

Eek. That's guaranteed to bite someone. Can you print out a warning or something at least?

:lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/workload/main.go, line 37 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23547#-L719rwdTVgJ8MCxEWHr:-L719rwennjkeUwIfdTq:b-mx2zek) ([raw file](https://github.com/cockroachdb/cockroach/blob/50fcd2d9c7c94d1c3e8a4ce1304fa6504e910c58/pkg/cmd/workload/main.go#L37)):*
> ```Go
> }
> 
> func wrap(f func(cmd *cobra.Command, args []string) error) func(cmd *cobra.Command, args []string) {
> ```

I think I'd prefer if this were called `handleErrs` or something. `wrap` is rather nondescript. Don't feel strongly though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23547#-:-L719gOSJ9muV-11PXd4:b-gwjsi8)*

**Comment by danhhz** [comment]
> Eek. That's guaranteed to bite someone. Can you print out a warning or something at least?

There is really no convenient place. Do you think it's bad enough that I should just omit this entirely? Also curious for @jordanlewis's thoughts on this

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/workload/tpcc/worker.go, line 143 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/23547#-L71NWQnO1V-ZZ_hXOc2:-L71NWQoeV7W5_NJ9Xsw:bud0ics) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b2236589a44c74ac0974235c1346a638d3ffb8/pkg/workload/tpcc/worker.go#L143)):*
> ```Go
> 		// tpmC is defined as per minute, but the histograms operate per second,
> 		// so hack it.
> 		w.hists.Get(`tpmC`).RecordCount(elapsed, 60)
> ```

The main requirement is that we have a tpmC number at the very end of the test. For that, we can just multiply the average new orders per second by 60 and output - no need to record something different.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23547)*

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
