### PR TITLE
opt: make lookup join more expensive

### PR DESCRIPTION
**Pull request by justinj**
This change adds a constant factor to the cost of fetching a row for a
lookup join scan. This constant was picked somewhat arbitrarily and can
be made more principled going forward.

This change was motivated by this query:

```
SELECT count(*) FROM lineitem JOIN supplier ON l_suppkey = s_suppkey
```

This query runs an approximately 1:600 join, supplier having around
10,000 rows and lineitem having around 6,000,000 (there's an FK relationship
so technically we could replace this join with a scan).

Previously a lookup-join was chosen. After this change, a merge-join is
chosen, which is roughly 2x as fast.

Run locally, the times for each join strategy are (recall `INNER HASH
JOIN` and `INNER LOOKUP JOIN` are not commutative):

```
SELECT count(*) FROM lineitem INNER HASH JOIN supplier ON l_suppkey = s_suppkey

  => 4.67s
  => cost: 6,446,371

SELECT count(*) FROM supplier INNER HASH JOIN lineitem ON l_suppkey = s_suppkey

  => 4.48s
  => cost: 6,476,327

SELECT count(*) FROM lineitem INNER MERGE JOIN supplier ON l_suppkey = s_suppkey

  => 3.68s
  => cost: 6,431,793

SELECT count(*) FROM lineitem INNER LOOKUP JOIN supplier ON l_suppkey = s_suppkey

  => 10.16s
  => old cost: 36,765,282
  => new cost: 42,746,162

SELECT count(*) FROM supplier INNER LOOKUP JOIN lineitem ON l_suppkey = s_suppkey

  => 6.53s
  => old cost:  6,330,224
  => new cost: 12,311,104
```

This was validated experimentally by running the following three
parameterized queries via exprgen:

Merge Join
----------

```
(MergeJoin
  (Scan
	[
	  (Table "lineitem")
	  (Cols "l_suppkey")
	  (Index "lineitem@l_sk")
	  (HardLimit $lineitem_rows)
	]
  )
  (Scan
	[
	  (Table "supplier")
	  (Cols "s_suppkey")
	  (HardLimit $supplier_rows)
	]
  )
  [ ]
  [
	(JoinType "inner-join")
	(LeftEq "+l_suppkey")
	(RightEq "+s_suppkey")
	(LeftOrdering "+l_suppkey")
	(RightOrdering "+s_suppkey")
  ]
)
```

Hash Join
---------

```
(InnerJoin
  (Scan
    [
      (Table "supplier")
      (Cols "s_suppkey")
      (Index "supplier@s_nk")
      (HardLimit $supplier_rows)
    ]
  )
  (Scan
    [
      (Table "lineitem")
      (Cols "l_suppkey")
      (Index "lineitem@l_sk")
      (HardLimit $lineitem_rows)
    ]
  )
  [
    (Eq (Var "l_suppkey") (Var "s_suppkey"))
  ]
  [ ]
)
```

Lookup Join
-----------

```
(MakeLookupJoin
  (Scan
    [
      (Table "supplier")
      (Index "supplier@s_nk")
      (Cols "s_suppkey")
      (HardLimit $supplier_rows)
    ]
  )
  [
    (JoinType "inner-join")
    (Table "lineitem")
    (Index "lineitem@l_sk")
    (KeyCols "s_suppkey")
    (Cols "l_suppkey")
  ]
  [ ]
)
```

Varying the input sizes, the original plot of estimated cost to actual cost looked like this:
image

After making this change, the plot looks like this:
image

(Green = Lookup, Purple = Hash, Red = Merge).

The change is somewhat unprincipled, but experimentally holds up in at least the case of this query, and doesn't appear to have any overtly bad effects on tests that I can see, besides one sort-merge join that bears further investigation (the query, TPCH Q2, is ever so slightly slower after this change, ~2.05s -> ~2.15s from my testing).

Release note (sql change): the cost-based optimizer will now pick
lookup-joins less frequently.

### CODE REVIEW

**Comment by knz** [comment]
Which process did you use to pick the constant? (Even if manual - would be good to know)

**Comment by justinj** [comment]
I just tweaked it until the lines more or less matched up :) lots of room for improvement here, for sure.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Very nice work. The plots are very useful, it is so easy to see visually what is going on. In time it would be cool to have infrastructure so that anyone can run this whenever some costing change is made.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-:-L_hz6mdEYHJVz5dlYGg:b-ksaz3v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/xform/coster.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-L_hywsA11k4nN6jSM0R:-L_hywsA11k4nN6jSM0S:b-ht9qtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6b53b303f0ed84d55419b208491bc4ba1a96ab/pkg/sql/opt/xform/coster.go#L106)):*
> ```Go
> 
> 	// TODO(justin): make this more sophisticated.
> 	// constRowCost is the cost to retrieve a single row during a lookup join.
> ```

[nit] add a reference to this PR so the reader can come and see the plots
___
*[pkg/sql/opt/xform/coster.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-L_hxTwhEx8Yp9-peSYa:-L_hxTwhEx8Yp9-peSYb:b-s3urer) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6b53b303f0ed84d55419b208491bc4ba1a96ab/pkg/sql/opt/xform/coster.go#L107)):*
> ```Go
> 	// TODO(justin): make this more sophisticated.
> 	// constRowCost is the cost to retrieve a single row during a lookup join.
> 	constRowCost = 1
> ```

[nit] I'd consolidate this with the other per row constant, eg `lookupJoinPerRowCost = 2 * seqIOCostFactor` and `perRowCost := lookupJoinPerRowCost + rowScanCost()`
___
*[pkg/sql/opt/xform/testdata/external/tpch, line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-L_hy7T48mj9rg2nrsfT:-L_hy7T48mj9rg2nrsfU:b4z46r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6b53b303f0ed84d55419b208491bc4ba1a96ab/pkg/sql/opt/xform/testdata/external/tpch#L627)):*
> ```
>       │         │    │    │    │    │    ├── fd: (34)-->(37)
>       │         │    │    │    │    │    └── ordering: +37
>       │         │    │    │    │    ├── sort
> ```

Sorting just the smaller side for a merge join is a legitimate choice (and this is the side that was input to lookup join so it must be significantly smaller). I wouldn't worry about this, given that the two plans are so close in execution time. It may just be due to merge sort being costed a tad too cheaply (the red dots are consistently below the lookup join line in the plots).

**Review by justinj — COMMENTED** [review]
Definitely agreed! Going to try to figure out what better tooling looks like here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-:-L_iHyeI5YRh5kPh53br:b-2le3r1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/opt/xform/coster.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-L_hywsA11k4nN6jSM0R:-L_iHRkx9sGatwlJKYIG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6b53b303f0ed84d55419b208491bc4ba1a96ab/pkg/sql/opt/xform/coster.go#L106)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a reference to this PR so the reader can come and see the plots
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-L_hxTwhEx8Yp9-peSYa:-L_iHSLn4rRn8836vQOt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6b53b303f0ed84d55419b208491bc4ba1a96ab/pkg/sql/opt/xform/coster.go#L107)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd consolidate this with the other per row constant, eg `lookupJoinPerRowCost = 2 * seqIOCostFactor` and `perRowCost := lookupJoinPerRowCost + rowScanCost()`
</blockquote></details>

Done.

**Review by andy-kimball — APPROVED** [review]
Thanks for figuring this out and finding a good compromise for this release. Longer term, the whole cost model needs a rework, but this should give us more time to do that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35561#-:-L_iibO84ged6Q9Nsm89:b-9fxxrl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by justinj** [comment]
For completeness, this change doesn't change the plans for any of the private queries.

**Pull request merged**
