### PR TITLE
sql/backfill: Implement retry mechanism during index backfill

### LINKED ISSUE #130939: sql: index backfill fails to complete with default settings
After creating a cluster and attempting to add an index, the index can get stuck continually failing due to memory settings. The only way to make progress is to manually change the `bulkio.index_backfill.batch_size` setting, however that should not be required and is not clear from the UI. 

Create a 12 node cluster:
```
roachprod create -n12 $CLUSTER 
roachprod put $CLUSTER artifacts/cockroach
roachprod start --store-count 2 $CLUSTER
roachprod ssh $CLUSTER:1 "./cockroach workload init kv {pgurl:1}"
roachprod ssh $CLUSTER:1 "./cockroach workload run kv  --duration=600s --max-block-bytes=10000 --min-block-bytes=10000 --concurrency=100 {pgurl:1-12}"
```
Attempt to create an index on the cluster
```
CREATE INDEX i ON kv.kv (k, v)
```
Note that this will never complete and instead get stuck on step 2. 

To unstick it, set the backfill batch size (this can be run either before the index creation or while it is stuck).
``` 
SET CLUSTER SETTING bulkio.index_backfill.batch_size = 5000;
```
The index creation will now complete successfully.

Jira issue: CRDB-42302

Epic CRDB-37796

### LINKED ISSUE #132048: roachtest: perturbation/full/backfill failed
roachtest.perturbation/full/backfill [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17193088?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17193088?buildTab=artifacts#/perturbation/full/backfill) on master @ [dcce4cafa234525fc859d32745c11ed87890dc7b](https://github.com/cockroachdb/cockroach/commits/dcce4cafa234525fc859d32745c11ed87890dc7b):

```
(test_runner.go:1308).runTest: test timed out (3h0m0s)
test artifacts and logs in: /artifacts/perturbation/full/backfill/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=2</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17193088/perturbation-full-backfill/1728219011252/1728230086542)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/full/backfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42805

Epic CRDB-37796

### PR DESCRIPTION
**Pull request by spilchen**
During an index backfill, if the bulko.index_backfill.batch_size setting is not appropriately configured for a table's size or definition, it may consume all available memory before writing the new index entries. This change introduces a retry mechanism to handle out-of-memory scenarios.

Upon encountering memory issues, the batch size is halved on each retry, coupled with an exponential backoff. This backoff period allows the consumer of the index entries to free up memory. The retry mechanism reuses the same bound memory account, making it critical to accurately track memory usage, even during failed attempts. This ensures proper accounting and frees memory consumed during the failed operation.

Epic: CRDB-37796
Closes #130939
Closes #132048
Release note (bug fix): The schema changer's backfill process now includes a retry mechanism that reduces the batch size when memory issues occur. This improves the likelihood of operation success without requiring manual adjustment of the bulko.index_backfill.batch_size parameter.

### CODE REVIEW

**Review by fqazi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @nameisbhaskar, @spilchen, and @srosenberg)

___
*[`pkg/sql/rowexec/indexbackfiller.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OBz_O7A8ESwdxX_IgW8:-OBz_O7A8ESwdxX_IgW9:b-ivhz7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e5197269e1d918c50098148d6149560df5b69a/pkg/sql/rowexec/indexbackfiller.go#L442)):*
> ```Go
> 			// attempt. We will allocate new memory on the next iteration.
> 			if memUsedBuildingBatch > 0 {
> 				entries = nil
> ```

Should we assert entries are nil?
___
*[`pkg/sql/rowexec/indexbackfiller.go` line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OBzXNbb3ghQGTYvNWP_:-OBzXNbb3ghQGTYvNWPa:b5zkax2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e5197269e1d918c50098148d6149560df5b69a/pkg/sql/rowexec/indexbackfiller.go#L472)):*
> ```Go
> }
> 
> type batchRetry struct {
> ```

Nit: Would it be better to call his indexBatchRetry since its in the rowexec namespace.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, @nameisbhaskar, and @srosenberg)

___
*[`pkg/sql/rowexec/indexbackfiller.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OBz_O7A8ESwdxX_IgW8:-OC-7rtr3eRHLFzXNoFp:br1dqwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e5197269e1d918c50098148d6149560df5b69a/pkg/sql/rowexec/indexbackfiller.go#L442)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Should we assert entries are nil?
</blockquote></details>

Technically, in case of errors, the `entries` slice might still be non-nil. Since this handles the cleanup of any allocated memory in the bound account, I thought it made sense to clear out the `entries` slice here as well. If you'd prefer, I can update `BuildIndexEntriesChunk` to always return a nil `entries` slice when an error occurs.
___
*[`pkg/sql/rowexec/indexbackfiller.go` line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OBzXNbb3ghQGTYvNWP_:-OC-8nVdETGV8865lGvr:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e5197269e1d918c50098148d6149560df5b69a/pkg/sql/rowexec/indexbackfiller.go#L472)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Would it be better to call his indexBatchRetry since its in the rowexec namespace.
</blockquote></details>

Done

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, @nameisbhaskar, @spilchen, and @srosenberg)

___
*[`pkg/sql/backfill/backfill.go` line 808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC-hLRx4V4gmYsPJK0q:-OC-hLRx4V4gmYsPJK0r:b-pm2gkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/67aff66c0c917de2f82365415e946b7603a17cd0/pkg/sql/backfill/backfill.go#L808)):*
> ```Go
> 	chunkSize int64,
> 	traceKV bool,
> ) (entries []rowenc.IndexEntry, resumeKey roachpb.Key, memUsedPerChunk int64, err error) {
> ```

nit: for error return parameters, I find it more clear to name the parameter `retErr`, so it's distinguished from any of the error variables that are declared in the function.
___
*[`pkg/sql/backfill/backfill.go` line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC-hVKs5yiLOoCUvpdG:-OC-hVKt36J3ytaRoevZ:b-w5uf80) ([raw file](https://github.com/cockroachdb/cockroach/blob/67aff66c0c917de2f82365415e946b7603a17cd0/pkg/sql/backfill/backfill.go#L819)):*
> ```Go
> 		err = errors.Wrap(err,
> 			"failed to initialize empty buffer to store the index entries of all rows in the chunk")
> 		return
> ```

nit: i think we should avoid naked returns, especially for larger functions like this. it makes it easy for us to start returning the wrong thing if certain lines or blocks of code are moved.

i was surprised our own coding guidelines don't have this, but it is in the Tour of Go, which we recommend: https://go.dev/tour/basics/7

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @nameisbhaskar, @spilchen, and @srosenberg)

___
*[`pkg/sql/rowexec/indexbackfiller.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OBz_O7A8ESwdxX_IgW8:-OC07w_xARd9Cpm9EECb:b-o0j4lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e5197269e1d918c50098148d6149560df5b69a/pkg/sql/rowexec/indexbackfiller.go#L442)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Technically, in case of errors, the `entries` slice might still be non-nil. Since this handles the cleanup of any allocated memory in the bound account, I thought it made sense to clear out the `entries` slice here as well. If you'd prefer, I can update `BuildIndexEntriesChunk` to always return a nil `entries` slice when an error occurs.
</blockquote></details>

That makes sense, I'm guessing the bound account is incremented last

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, @nameisbhaskar, @rafiss, and @srosenberg)

___
*[`pkg/sql/backfill/backfill.go` line 808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC-hLRx4V4gmYsPJK0q:-OC0ASlyBoWQotpcUNNM:b3aaxrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/67aff66c0c917de2f82365415e946b7603a17cd0/pkg/sql/backfill/backfill.go#L808)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: for error return parameters, I find it more clear to name the parameter `retErr`, so it's distinguished from any of the error variables that are declared in the function.
</blockquote></details>

I backed this part out when I removed the naked returns. So, it's back to what it was before.
___
*[`pkg/sql/backfill/backfill.go` line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC-hVKs5yiLOoCUvpdG:-OC0A5293L2Xb25xsUsI:b3pmzbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/67aff66c0c917de2f82365415e946b7603a17cd0/pkg/sql/backfill/backfill.go#L819)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think we should avoid naked returns, especially for larger functions like this. it makes it easy for us to start returning the wrong thing if certain lines or blocks of code are moved.

i was surprised our own coding guidelines don't have this, but it is in the Tour of Go, which we recommend: https://go.dev/tour/basics/7
</blockquote></details>

Great advice! I removed the naked returns and reinstated much of the existing error handling. For every instance where `BuildIndexEntriesChunk` returns an error, I ensured that the memory usage in the bound account is also returned. This allows us to properly track and free the allocated memory during retries.
___
*[`pkg/sql/rowexec/indexbackfiller.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OBz_O7A8ESwdxX_IgW8:-OC09hMW3j1_SxhYmFbD:b-y2pdby) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e5197269e1d918c50098148d6149560df5b69a/pkg/sql/rowexec/indexbackfiller.go#L442)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

That makes sense, I'm guessing the bound account is incremented last
</blockquote></details>

The counter is incremented as index entries are being built. However, if we encounter an out-of-memory error while building some of the entries, we need to ensure the bound account is freed for the memory allocated during the failed attempt.

I ended up reworking the code, and it made sense to include the assert as part of the changes. This should address your original concern.

**Review by fqazi — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-:-OC0AxRs1ppt_nDJrPe9:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @nameisbhaskar, @rafiss, and @srosenberg)

**Review by rafiss — CHANGES_REQUESTED** [review]
the retry logic here is very cleanly implemented; nice job! my comments are mostly for minor adjustments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-:-OC1rUhPAk1kMBHz0sDj:b56x9au)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, @nameisbhaskar, @spilchen, and @srosenberg)

___
*[`pkg/sql/rowexec/indexbackfiller.go` line 476 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC1qtiOBGlxxXHzjIBy:-OC1qtiP1RlGXzyImWVL:bbbqg4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59827d93102baf7d322f8bb21374cc27504ca6b/pkg/sql/rowexec/indexbackfiller.go#L476)):*
> ```Go
> 
> type indexBatchRetry struct {
> 	nextChunkSize       *int64
> ```

nit: why did this need to be a pointer? it seemed to me that we could keep it a value
___
*[`pkg/sql/rowexec/indexbackfiller.go` line 477 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC1pyTF4TAFsoLowQbY:-OC1pyTG05uzJZjLJ14f:bnn4nc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59827d93102baf7d322f8bb21374cc27504ca6b/pkg/sql/rowexec/indexbackfiller.go#L477)):*
> ```Go
> type indexBatchRetry struct {
> 	nextChunkSize       *int64
> 	builder             func(ctx context.Context, txn isql.Txn) error
> ```

super nit: a name like `buildIndexChunk` might make the purpose of this function more clear.
___
*[`pkg/sql/rowexec/indexbackfiller.go` line 493 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC1pWFl7iat-OQ3QFSi:-OC1pWFl7iat-OQ3QFSj:b-ovfgpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59827d93102baf7d322f8bb21374cc27504ca6b/pkg/sql/rowexec/indexbackfiller.go#L493)):*
> ```Go
> 				// Callback to clear out any state acquired in the last attempt
> 				if resetErr := b.resetForNextAttempt(ctx); resetErr != nil {
> 					return errors.CombineErrors(resetErr, err)
> ```

nit: maybe this should be `CombineErrors(err, resetErr)`, since the reset error is secondary to that other error.
___
*[`pkg/sql/rowexec/indexbackfiller.go` line 498 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC1r7mk0dCsKGafHFci:-OC1r7mk0dCsKGafHFcj:b9kcz3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59827d93102baf7d322f8bb21374cc27504ca6b/pkg/sql/rowexec/indexbackfiller.go#L498)):*
> ```Go
> 				if !r.Next() {
> 					// If we have exhausted all retries, fail with the out of memory error.
> 					return err
> ```

nit: should we return a wrapped error, like perhaps:
```
errors.Wrapf(err, "failed after %d retries", ...)
````
___
*[`pkg/sql/rowexec/indexbackfiller.go` line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-OC1llCzDrNy6dOhW_R4:-OC1llCzDrNy6dOhW_R5:bnqje2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59827d93102baf7d322f8bb21374cc27504ca6b/pkg/sql/rowexec/indexbackfiller.go#L503)):*
> ```Go
> 				log.Infof(ctx,
> 					"out of memory while building index entries; retrying with batch size %d. Silencing error: %s",
> 					redact.SafeInt(*b.nextChunkSize), redact.SafeString(err.Error()))
> ```

The `nextChunkSize` is an int, which is automatically considered safe for non-redaction, so `SafeInt` is not needed.

For the error, we can't assume that `err.Error()` is non-sensitive. it's possible that it is a wrapped error, whose error text could contain application data. For that reason, each error object is responsible for implementing `errors.SafeFormatter` in order to teach the formatter how to redact and unredact as it should. To format it here, we'd use `log.Infof("...%v", ..., err)`.

The page here has a overview of these concepts in a lot greater detail, and is a good reference. Happy to discuss this more synchronously if you think it would help; or perhaps we could review this in a team tech discussion? https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability

**Review by rafiss — APPROVED** [review]
lgtm! nice improvement for sure

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135563#-:-OC59qyOEzP7eVWPm302:b-e12isf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @fqazi, @nameisbhaskar, @spilchen, and @srosenberg)

**Comment by spilchen** [comment]
TFTR!

bors r+

**Comment by spilchen** [comment]
bors retry

**Pull request merged**
