### PR TITLE
opt: clarify implicator test comment

### PR DESCRIPTION
**Pull request by mgartner**
Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This was motivated by the feedback here: https://github.com/cockroachdb/cockroach/pull/123408#pullrequestreview-2036564043

**Review by rytaft — APPROVED** [review]
:lgtm: thank you!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123600#-:-Nx-GD-LBU6sm0E95iAY:bro3093)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123600#-:-NxCDh3dAgEAHV_Kou__:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Pull request merged**
