### PR TITLE
kv: fix flake in TestApplier

### LINKED ISSUE #52611: kv/kvnemesis: TestApplier failed
[(kv/kvnemesis).TestApplier failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2169047&tab=buildLog) on [master@b7cf171ae2d77f3adababe7f42b2cfefc795a2ba](https://github.com/cockroachdb/cockroach/commits/b7cf171ae2d77f3adababe7f42b2cfefc795a2ba):

```
=== RUN   TestApplier
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestApplier565554319
--- FAIL: TestApplier (0.21s)
    test_log_scope.go:154: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestApplier565554319
    test_log_scope.go:63: use -show-logs to present logs inline
    applier_test.go:134: 
        	Error Trace:	applier_test.go:51
        	            				applier_test.go:134
        	Error:      	Not equal: 
        	            	expected: "db1.AdminSplit(ctx, \"foo\") // aborted during DistSender.Send: context canceled"
        	            	actual  : "db1.AdminSplit(ctx, \"foo\") // aborted in distSender: context canceled"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-db1.AdminSplit(ctx, "foo") // aborted during DistSender.Send: context canceled
        	            	+db1.AdminSplit(ctx, "foo") // aborted in distSender: context canceled
        	Test:       	TestApplier

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestApplier PKG=./pkg/kv/kvnemesis TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestApplier.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by nvb**
Fixes #52611.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52711)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52711#-MEYo0_uAkJGrRzy-J4F:-MEYo0_uAkJGrRzy-J4G:b-udqlc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149b55b72501bc1ff5cce889dff263ab953eb9d/pkg/kv/kvclient/kvcoord/dist_sender.go#L1580)):*
> ```Go
> 	case <-ctx.Done():
> 		// Happens when the client request is canceled.
> 		return errors.Wrap(ctx.Err(), "aborted during DistSender.Send")
> ```

this function is not called only from DistSender.Send. Is it hard to relax the test instead?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52711)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52711#-MEYo0_uAkJGrRzy-J4F:-MEd1CNC1Xv2AT1rscjV:b-qsvnoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149b55b72501bc1ff5cce889dff263ab953eb9d/pkg/kv/kvclient/kvcoord/dist_sender.go#L1580)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this function is not called only from DistSender.Send. Is it hard to relax the test instead?
</blockquote></details>

Done. PTAL.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52711#-:-MEi4JNL8nriOkoTycES:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
