### PR TITLE
opt: merge joins

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: adjust the cost of hash-join

Add a factor to account for the overhead of the hashtable. The
intention is to make merge-joins more appealing.

Also add the cost of emitting the number of rows we estimated.

Release note: None

#### opt: merge joins

This change introduces merge joins.

An exploration rule converts any Join to a set of MergeJoin
expressions, based on the interesting orderings property. Each
MergeJoin has a definite ordering on the equality columns and
requires that ordering from both children.

The main TODO is around multiple joins: the merge join should be able
"advertise" its output ordering (`canProvide`).

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Exciting to see this work!

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdLya4BeASmG_NBS5l:-LFdLya4BeASmG_NBS5m:bs7wmwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/exec/execbuilder/relational_builder.go#L372)):*
> ```Go
> 
> // initJoinBuild builds the inputs to the join as well as the ON expression.
> func (b *Builder) initJoinBuild(
> ```

When I get this many params to a helper function, I usually switch to a helper struct. I could imagine something like:
```
type joinBuilder struct {
  ...
}

func (jb *joinBuilder) buildHashJoin(ev memo.ExprView) (execPlan, error)

func (jb *joinBuilder) buildMergeJoin(ev memo.ExprView) (execPlan, error)

var jb joinBuilder
plan, err := jb.buildHashJoin(ev)
```

That said, that's just my own preference, and I'm fine with it as-is.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 412 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdN2wx8kBBYJYR3OmX:-LFdN2wx8kBBYJYR3OmY:b-g4uwv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/exec/execbuilder/relational_builder.go#L412)):*
> ```Go
> }
> 
> func joinOpToJoinType(op opt.Operator) sqlbase.JoinType {
> ```

Can `JoinApply` come through here? Make sure that we report a nice error to users when `Apply` hits the execbuilder due to failure to decorrelate.

---

*[pkg/sql/opt/norm/testdata/props/prune_cols, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdKCQy7VquN4m-kYQj:-LFdKCQy7VquN4m-kYQk:bwbjudo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/norm/testdata/props/prune_cols#L213)):*
> ```
>       ├── prune: (2)
>       ├── interesting orderings: (+1)
>       ├── merge-join
> ```

Should we be remapping this for display, maybe like this:

`semi-join (merge)`
`inner-join (merge)`
etc.

I do find that I pay a lot of attention to the join type, and feel it's more important than the particular algorithm we're using. I could imagine mapping the existing joins into:

`semi-join (hash)`
`inner-join (hash)`

---

*[pkg/sql/opt/xform/custom_funcs.go, line 386 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdQbfB7xsL1RQv26fJ:-LFdQbfB7xsL1RQv26fK:b-38fkix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/xform/custom_funcs.go#L386)):*
> ```Go
> 	}
> 
> 	for _, o := range leftOrders {
> ```

Should we just go ahead and add a simple `CommuteJoin` exploration rule at this point? If not, we'll just have to remember to change this logic so that we don't do this twice.

---

*[pkg/sql/opt/xform/custom_funcs.go, line 411 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdPnG_2mCS9cPJbU9k:-LFdPnG_2mCS9cPJbU9l:b-cng0sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/xform/custom_funcs.go#L411)):*
> ```Go
> 		}
> 		// Don't allow any column to show up twice.
> 		// TODO(radu): need to figure out the right thing to do in cases
> ```

Ideally, we'd normalize simple equality expressions like this, with lower `ColumnID` on left-hand-side. Then we'd have a rule that removes duplicate conjuncts from filters.

---

*[pkg/sql/opt/xform/rules/join.opt, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFZgrxL28ZTK-CnT6tp:-LFZgrxL28ZTK-CnT6tq:b-3k2rfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/xform/rules/join.opt#L5)):*
> ```
> # =============================================================================
> 
> [CreateMergeJoins, Explore]
> ```

NIT: Use `GenerateMergeJoins` for consistency.

---

*[pkg/sql/opt/xform/testdata/rules/join, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdTTF9AfcvHHEUqmBe:-LFdTTF9AfcvHHEUqmBf:b-bvczj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/xform/testdata/rules/join#L61)):*
> ```
> # CreateMergeJoins
> # --------------------------------------------------
> ```

Looking at your merge join generation logic, I think you're missing test cases, such as:

- Multiple different merge joins considered (i.e. multiple in same memo group)
- Different data types in equivalency (shouldn't pick the condition up)
- Equality predicates that don't involve columns in both sides, like `xyz.x = xyz.y`
- Duplicate predicates, reversed predicates: `a=x AND a=x AND x=a`
- Interesting order pulled from right side rather than left

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-:-LFdV9gr7Oh7g0p37sSP:bu5820c)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 412 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdN2wx8kBBYJYR3OmX:-LFqdz-b-EuUOj-kJgyo:b-bpwqri) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/exec/execbuilder/relational_builder.go#L412)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can `JoinApply` come through here? Make sure that we report a nice error to users when `Apply` hits the execbuilder due to failure to decorrelate.
</blockquote></details>

No, this is under an `IsJoinNonApply`. I added a special message for Apply (used to be "unsupported operator").

---

*[pkg/sql/opt/norm/testdata/props/prune_cols, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdKCQy7VquN4m-kYQj:-LFqhy1q-UAZ9dfvzWlS:b-3rrhft) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/norm/testdata/props/prune_cols#L213)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should we be remapping this for display, maybe like this:

`semi-join (merge)`
`inner-join (merge)`
etc.

I do find that I pay a lot of attention to the join type, and feel it's more important than the particular algorithm we're using. I could imagine mapping the existing joins into:

`semi-join (hash)`
`inner-join (hash)`
</blockquote></details>

Done. I left the non-merge ones as they are.

---

*[pkg/sql/opt/xform/custom_funcs.go, line 386 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdQbfB7xsL1RQv26fJ:-LFqiL_9-d4AHfrc6dEA:bsfob9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/xform/custom_funcs.go#L386)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should we just go ahead and add a simple `CommuteJoin` exploration rule at this point? If not, we'll just have to remember to change this logic so that we don't do this twice.
</blockquote></details>

I added a TODO for now. I think adding `CommuteJoin` has some non-trivial ramifications I'd rather not chase right now.

---

*[pkg/sql/opt/xform/custom_funcs.go, line 411 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdPnG_2mCS9cPJbU9k:-LFqjPTQ1apFZIUDQHq-:b-jb8k10) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/xform/custom_funcs.go#L411)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ideally, we'd normalize simple equality expressions like this, with lower `ColumnID` on left-hand-side. Then we'd have a rule that removes duplicate conjuncts from filters.
</blockquote></details>

That's a good idea, but this is more than duplicate conjuncts, the two conjuncts in the example below are different.

---

*[pkg/sql/opt/xform/testdata/rules/join, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFdTTF9AfcvHHEUqmBe:-LFrd_FV5Rbxje8wS07F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e47abefb57a35c5cb781068ec724e024d44c9af5/pkg/sql/opt/xform/testdata/rules/join#L61)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Looking at your merge join generation logic, I think you're missing test cases, such as:

- Multiple different merge joins considered (i.e. multiple in same memo group)
- Different data types in equivalency (shouldn't pick the condition up)
- Equality predicates that don't involve columns in both sides, like `xyz.x = xyz.y`
- Duplicate predicates, reversed predicates: `a=x AND a=x AND x=a`
- Interesting order pulled from right side rather than left
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26904)*

**Comment by rytaft** [comment]
Very nice!

---

Reviewed 5 of 5 files at r1, 17 of 17 files at r2, 19 of 19 files at r4, 13 of 13 files at r5.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt_exec_factory.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrN_2TAXehaGBXQD2L:-LFrN_2U4TxBgKTG94g2:b-mv6jh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt_exec_factory.go#L264)):*
> ```Go
> 	n := len(leftOrdering)
> 	if n == 0 || len(rightOrdering) != n {
> 		return nil, errors.Errorf("invalid orderings")
> ```

Maybe give a bit more detail in the error message - something like, "orderings from the left and right side must be the same length and must be greater than 0"

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrPHcc207alSwqkSK9:-LFrPHcdEC9EvmcLhk8M:bn3prmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/exec/execbuilder/relational_builder.go#L130)):*
> ```Go
> 	default:
> 		if ev.IsJoinNonApply() {
> 			ep, err = b.buildHashJoin(ev, joinOpToJoinType(ev.Operator()))
> ```

why not make this symmetric with `buildMergeJoin` and call `joinOpToJoinType` inside the function?

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrPpT13ku3T1l1iihe:-LFrPpT13ku3T1l1iihf:b-4f485c) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/exec/execbuilder/relational_builder.go#L331)):*
> ```Go
> 	}
> 	ep := execPlan{outputCols: outputCols}
> 	ep.root, err = b.factory.ConstructJoin(joinType, left.root, right.root, onExpr)
> ```

Can you rename this factory method to `ConstructHashJoin`?

---

*[pkg/sql/opt/memo/expr_view.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrR6nJB9W5zWC8D9EC:-LFrR6nJB9W5zWC8D9ED:b-68rb7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/memo/expr_view.go#L409)):*
> ```Go
> 	if ev.op == opt.MergeOnOp {
> 		tp = tp.Childf("%v", ev.op)
> 		def := ev.Private().(*MergeOnDef)
> ```

This stuff seems like it should go in `formatScalarPrivate` -- then you don't need a special case here

---

*[pkg/sql/opt/ops/relational.opt, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrTm8J8OKEohCF1OyK:-LFrTm8KBHRgHqawFtJM:b-ujl118) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/ops/relational.opt#L126)):*
> ```
> 
> # MergeJoin represents a join that is executed using merge-join.
> # On is a MergeOn scalar which contains the ON condition and
> ```

On -> MergeOn

---

*[pkg/sql/opt/ops/scalar.opt, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrTg-Z0whptKVfnGMN:-LFrTg-Z0whptKVfnGMO:b3j8ho9) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/ops/scalar.opt#L623)):*
> ```
> [Scalar]
> define MergeOn {
>     Filter Expr
> ```

Should this be `On` to match the other joins?

---

*[pkg/sql/opt/xform/coster.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrM1im3Gkt9-qSXKN3:-LFrM1im3Gkt9-qSXKN4:b-8cf0ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b9d0f0aa10ca4458fcf138f48d818aa428687ab/pkg/sql/opt/xform/coster.go#L171)):*
> ```Go
> 
> 	// Add the CPU cost of emitting the rows.
> 	// TODO(radu): ideally we would have an estimate of how many rows we actually
> ```

Can you give an example of how the cost would be different if we take the ON condition into account?

---

*[pkg/sql/opt/xform/coster.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrXXDk1R6dD8nom_t_:-LFrXXDk1R6dD8nom_ta:b5mr9du) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/xform/coster.go#L169)):*
> ```Go
> 	cost := memo.Cost(leftRowCount+rightRowCount) * cpuCostFactor
> 
> 	// Add an extra cost for creating the hash table and doing lookups.
> ```

Should this use the Random I/O factor somehow?

---

*[pkg/sql/opt/xform/custom_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFreA1O7TISgfuIKjlE:-LFreA1O7TISgfuIKjlF:b-vt7qhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/xform/custom_funcs.go#L398)):*
> ```Go
> // harvestEqualityColumns returns a list of pairs of columns (one from the left
> // side, one from the right side) which are constrained to be equal.
> func harvestEqualityColumns(
> ```

Seems like you can simplify this a lot once my PR merges by using the FDs from the properties of `on`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-:-LFrh8X1DtW4WUHMToBm:b-j7qk9t)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt_exec_factory.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrN_2TAXehaGBXQD2L:-LFri51J-vbvDrSdcbWN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt_exec_factory.go#L264)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe give a bit more detail in the error message - something like, "orderings from the left and right side must be the same length and must be greater than 0"
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrPHcc207alSwqkSK9:-LFriSW92jPGVGgQlF4v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/exec/execbuilder/relational_builder.go#L130)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why not make this symmetric with `buildMergeJoin` and call `joinOpToJoinType` inside the function?
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrPpT13ku3T1l1iihe:-LFriT4t9mHHtv1DNduw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/exec/execbuilder/relational_builder.go#L331)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you rename this factory method to `ConstructHashJoin`?
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/expr_view.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrR6nJB9W5zWC8D9EC:-LFrsi9J39RItxqwV-P2:b-97xn6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/memo/expr_view.go#L409)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This stuff seems like it should go in `formatScalarPrivate` -- then you don't need a special case here
</blockquote></details>

That only works if we want to put everything on the same line with the operator

---

*[pkg/sql/opt/ops/relational.opt, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrTm8J8OKEohCF1OyK:-LFrtAbG2QDwplJ4i7no:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/ops/relational.opt#L126)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

On -> MergeOn
</blockquote></details>

Done.

---

*[pkg/sql/opt/ops/scalar.opt, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrTg-Z0whptKVfnGMN:-LFrtAvXAocC9Qo-RR9E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/ops/scalar.opt#L623)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this be `On` to match the other joins?
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/coster.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrM1im3Gkt9-qSXKN3:-LFrteAX4ZNkZhqiAm3U:b7ncsze) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b9d0f0aa10ca4458fcf138f48d818aa428687ab/pkg/sql/opt/xform/coster.go#L171)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you give an example of how the cost would be different if we take the ON condition into account?
</blockquote></details>

`SELECT * FROM a,b WHERE a.y > b.y`

Maybe from the histograms we could estimate the number of rows for which the condition holds, and in some cases it might not be very big. But we would still apply the filter N*M times.

---

*[pkg/sql/opt/xform/coster.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrXXDk1R6dD8nom_t_:-LFrtJRzDVpU6ZlMoIbV:bctiymr) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/xform/coster.go#L169)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this use the Random I/O factor somehow?
</blockquote></details>

For now we're assuming it fits in memory (both here and for sorting). I played around with adding IO costs a bit, it will need to be part of a bigger change to make everything work together.

---

*[pkg/sql/opt/xform/custom_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFreA1O7TISgfuIKjlE:-LFrvNd-EDaNqvDAlzTX:b-xahgel) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/xform/custom_funcs.go#L398)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like you can simplify this a lot once my PR merges by using the FDs from the properties of `on`
</blockquote></details>

Yeah, that will be nice. Probably in another PR though

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26904)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 5 of 18 files at r6, 13 of 13 files at r7.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/expr_view.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrR6nJB9W5zWC8D9EC:-LFryWDZBrrFurOsBamw:bpf3ieo) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/memo/expr_view.go#L409)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

That only works if we want to put everything on the same line with the operator
</blockquote></details>

Ah ok - makes sense

---

*[pkg/sql/opt/xform/coster.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrM1im3Gkt9-qSXKN3:-LFryz0-ClC3zNu_5xaJ:b-ujsvxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b9d0f0aa10ca4458fcf138f48d818aa428687ab/pkg/sql/opt/xform/coster.go#L171)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`SELECT * FROM a,b WHERE a.y > b.y`

Maybe from the histograms we could estimate the number of rows for which the condition holds, and in some cases it might not be very big. But we would still apply the filter N*M times.
</blockquote></details>

Oh I see - thanks

---

*[pkg/sql/opt/xform/coster.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFrXXDk1R6dD8nom_t_:-LFrykiS05Zk8LCJYuiH:b1ubcge) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/xform/coster.go#L169)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

For now we're assuming it fits in memory (both here and for sorting). I played around with adding IO costs a bit, it will need to be part of a bigger change to make everything work together.
</blockquote></details>

Makes sense

---

*[pkg/sql/opt/xform/custom_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-LFreA1O7TISgfuIKjlE:-LFrzBxdBAnTBfIOYXf0:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/236f821aaa7aca12415661bfd32374883cd03a41/pkg/sql/opt/xform/custom_funcs.go#L398)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, that will be nice. Probably in another PR though
</blockquote></details>

Sounds good

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-:-LFrzahY6_aqXhH6ohPu:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26904#-:-LFsRjxu3MoKY9ZyTI9k:bnfp4nl)*

**Pull request merged**
