### PR TITLE
backupccl: move writing of encryption info to BACKUP job from planning

### LINKED ISSUE #51038: Audit External IO access during backup planning
Recent changes made it possible to run BACKUP under transaction.
This has the unfortunate side effect: we write external file (s.a. encryption file) during backup
planning.  If the transaction is rolled back, the file stays around.

This is unfortunate and probably wrong.
In general, we should avoid doing IO in planning phase, particularly write IO.

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, if we had to generate and write the encryption-info for a
BACKUP, alongside the manifest and data, we would do this in the
planning phase.  With support added for DETACHED BACKUP, there is a push
to make the planning phase not have any side effects, as these will not
be undone if the DETACHED BACKUP txn is rolled back.

This change moves the logic of writing the encryption-info file to the
BACKUP job resume hook.  The generation of the encryption information
continues to take place in the planning phase, so as to avoid writing
plaintext passphrases to the jobs proto.

Fixes: #51038

Release note: None

Release justification: low risk, high benefit changes to existing functionality

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @pbardea)

___
*[pkg/ccl/backupccl/backup_job.go, line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaMYqU4T96-UlEeWUM:-MFaMYqU4T96-UlEeWUN:b-ef7prp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/backup_job.go#L424)):*
> ```Go
> 
> 	if details.EncryptionInfo != nil {
> 		if err := writeEncryptionOptionsIfNotExists(ctx, details.EncryptionInfo,
> ```

nit: should we rename this to `writeEncryptionInfoIfNotExists` to be more consistent with our `EncryptionInfo`vs `EncryptionOptions` distinction?
___
*[pkg/ccl/backupccl/backup_planning.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaLq2E3Mc-xZsw6sy1:-MFaLq2FBMGc9YY0DE-6:b-wkpnxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/backup_planning.go#L873)):*
> ```Go
> 			BackupManifest:   descBytes,
> 			Encryption:       encryption,
> 			EncryptionInfo:   encryptionInfo,
> ```

Now that we're passing both here, the names `Encryption` and `EncryptionInfo` are a bit confusing. Maybe it's worth renaming `Encryption` to `EncryptionOptions` (I'm thinking both the field in `BackupDetails` as well as the variable in planning) to make it more explicit that that field is referencing the options specified in the backup stmt vs the information that we persist to the backup file.
___
*[pkg/ccl/backupccl/backup_planning.go, line 993 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaKfiD4kAMNL-nAF2i:-MFaKfiD4kAMNL-nAF2j:b-j2htki) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/backup_planning.go#L993)):*
> ```Go
> 	var encryptionOptions *jobspb.BackupEncryptionOptions
> 	var encryptionInfo *jobspb.EncryptionInfo
> 	exportStore, err := makeCloudStorage(ctx, defaultURI, p.User())
> ```

Do we need to pass in `makeCloudStorage` +`defaultURI` and create an `exportStore` anymore?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaFpSMDQBUN5WVk2m8:-MFaFpSMDQBUN5WVk2m9:b-n7em8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/manifest_handling.go#L71)):*
> ```Go
> 	// BackupEncryptionInfoFile is the file name used to store the serialized
> 	// EncryptionInfo proto while the backup is in progress.
> 	BackupEncryptionInfoFile = "ENCRYPTION-INFO"
> ```

just noticed in passing: I don't think that we need to export these consts. We don't have to clean this up in this change though.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaH0gH33gyCXiLtOnj:-MFaH0gH33gyCXiLtOnk:b-f8x3ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/manifest_handling.go#L897)):*
> ```Go
> 	ctx context.Context, opts *jobspb.EncryptionInfo, dest cloud.ExternalStorage,
> ) error {
> 	r, err := dest.ReadFile(ctx, BackupEncryptionInfoFile)
> ```

Do we have a test that tests us doing an incremental backup with different encryption options? I couldn't find anything after a quick search -- if not it might be worth adding one to at least document the expected behaviour here.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_planning.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaLq2E3Mc-xZsw6sy1:-MFberBf2QqfCdj4fQp_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/backup_planning.go#L873)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Now that we're passing both here, the names `Encryption` and `EncryptionInfo` are a bit confusing. Maybe it's worth renaming `Encryption` to `EncryptionOptions` (I'm thinking both the field in `BackupDetails` as well as the variable in planning) to make it more explicit that that field is referencing the options specified in the backup stmt vs the information that we persist to the backup file.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_planning.go, line 993 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaKfiD4kAMNL-nAF2i:-MFbfC0j609z-WNTcVMM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/backup_planning.go#L993)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do we need to pass in `makeCloudStorage` +`defaultURI` and create an `exportStore` anymore?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaFpSMDQBUN5WVk2m8:-MFbgGLkCgKdAys68UY6:b-cgnccp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/manifest_handling.go#L71)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

just noticed in passing: I don't think that we need to export these consts. We don't have to clean this up in this change though.
</blockquote></details>

unexported all of them.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaH0gH33gyCXiLtOnj:-MFbq2w5CjgFL5SSuIw3:b-u96r49) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/manifest_handling.go#L897)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do we have a test that tests us doing an incremental backup with different encryption options? I couldn't find anything after a quick search -- if not it might be worth adding one to at least document the expected behaviour here.
</blockquote></details>

Not a 100% sure what you mean here. An incremental BACKUP would not come into this method because the invocation is surrounded by `if (encryptionInfo != nil)`. In the case of an incremental during planning, the encryptionOptions are resolved from the base BACKUP and so there would never be a call to `makeNewEncryptionOptions` which implies `encryptionInfo == nil`.

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @pbardea)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaFpSMDQBUN5WVk2m8:-MFeur0QERqXmfOLTK9O:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/manifest_handling.go#L71)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

unexported all of them.
</blockquote></details>

Thanks!
___
*[pkg/ccl/backupccl/manifest_handling.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53418#-MFaH0gH33gyCXiLtOnj:-MFesiJp-zbrwm3eQuA5:bv71740) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de32d8c355a570d1684cac27a5cf18c792e7d45/pkg/ccl/backupccl/manifest_handling.go#L897)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Not a 100% sure what you mean here. An incremental BACKUP would not come into this method because the invocation is surrounded by `if (encryptionInfo != nil)`. In the case of an incremental during planning, the encryptionOptions are resolved from the base BACKUP and so there would never be a call to `makeNewEncryptionOptions` which implies `encryptionInfo == nil`.
</blockquote></details>

Gotcha - I was thinking how we handle cases where incrementals are encrypted but the base is not, but in that case we just fail to find the previous encryption info. Thanks for the explanation!

**Comment by adityamaru** [comment]
TFTRs!

bors r+

**Comment by otan** [comment]
bors r=adityamaru

**Pull request merged**
