### PR TITLE
rpc: compute clock offsets in real time

### PR DESCRIPTION
**Pull request by tamird**
I'm a little scared about this, since it makes things more trigger-happy. @knz want to put it through the ringer?

@nvanbenschoten for the review.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5512)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:, but not a very thorough review. Looks a lot cleaner now though - curious when it'll start killing the first nodes!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[rpc/clock_offset.go, line 144 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_QPHu2U1E8qK2D3XX:-KD_QPHvmrzr5ZH0ge0_:359587134) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/clock_offset.go#L144)):*
Could you sprinkle some comments here?

---

*[rpc/clock_offset.go, line 151 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_QSSoym7J5OFuhwjT:-KD_QSSoym7J5OFuhwjU:809332262) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/clock_offset.go#L151)):*
You sure you don't want to lock-defer which would avoid the `V(2)` below racing?

---

*[rpc/clock_offset.go, line 120 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_RbcGCnZ2fOEgONle:-KD_RbcGCnZ2fOEgONlf:940522115) ([raw file](https://github.com/cockroachdb/cockroach/blob/439e2cfe01b09864b11fb433f1730919b04db562/rpc/clock_offset.go#L120)):*
In a prefect world, would you keep some sliding window somehow? Afaict you only keep one measurement per node, so you have a TTL time window over which you collect the min, then you throw everything away and start again.

---

*[rpc/clock_offset.go, line 174 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_S2xT5y67wKxZSgJC:-KD_S2xT5y67wKxZSgJD:2074351519) ([raw file](https://github.com/cockroachdb/cockroach/blob/439e2cfe01b09864b11fb433f1730919b04db562/rpc/clock_offset.go#L174)):*
Do you really want to do this? Couldn't `findOffsetInterval` return an error which implies that the offsetInterval hasn't been set?

---

*[rpc/context.go, line 26 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_OyeBfAr7B4wqIjLk:-KD_OyeC2jSZcSLusGW6:-671895598) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L26)):*
Add a comment.

---

*[rpc/context.go, line 192 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_PAjlQ2YSNynCg3HI:-KD_PAjlQ2YSNynCg3HJ:1218091075) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L192)):*
if `MaxOffset() == 0`, it seems that you'd want to disable checking clock offsets, doesn't this do the opposite?

Ah, fixed in later commit.

---

*[rpc/context.go, line 203 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_PwBOymj3mLr3JPBO:-KD_PwBOymj3mLr3JPBP:871580217) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L203)):*
mildly science dog on how exactly his is used, but that's pretty much the old code and vetted for, right?

---

*[rpc/context_test.go, line 107 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_QzDingolPZyj4Z2q:-KD_QzDjHePpfiaVOm8F:-1912198245) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/context_test.go#L107)):*
s/to not exist/to have been cleared/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-:-KD_SmOkH1Q4Bm9nLlWc:-1897492513)*

**Comment by knz** [comment]
I am currently running skew tests with this, it is indeed much more agressive. Let me finish those before we merge this.

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[rpc/clock_offset.go, line 151 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_QSSoym7J5OFuhwjT:-KD_UYrYuxbUqR3NpP4Y:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/clock_offset.go#L151)):*
+1

---

*[rpc/context.go, line 26 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_OyeBfAr7B4wqIjLk:-KD_TKi__wBUq2UdFVJb:1411141533) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L26)):*
+1, and please include how the value was chosen

---

*[rpc/context.go, line 201 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_T3qJThrj-RAAn7jk:-KD_T3qKe03i8UettahZ:1423450914) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L201)):*
Interesting that we can assume the ping duration is fully symmetric. That seems to me like a best case assumption.

---

*[rpc/context_test.go, line 184 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_VmcYYxGdvyilGCkD:-KD_VmcYYxGdvyilGCkE:1217812663) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/context_test.go#L184)):*
Why not defer?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-:-KD_YgxhGaUfTC0nddlR:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[rpc/clock_offset.go, line 144 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_QPHu2U1E8qK2D3XX:-KD_ZrjeosJHPEZoZBnZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/clock_offset.go#L144)):*
Done.

---

*[rpc/clock_offset.go, line 151 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_QSSoym7J5OFuhwjT:-KD_UqyO7HjWeWbKjeHC:367612625) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/clock_offset.go#L151)):*
oh, that's why this was deferred. fixed.

---

*[rpc/clock_offset.go, line 120 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_RbcGCnZ2fOEgONle:-KD_XpVnGqx_H3pDkBf8:-714003978) ([raw file](https://github.com/cockroachdb/cockroach/blob/439e2cfe01b09864b11fb433f1730919b04db562/rpc/clock_offset.go#L120)):*
There may be some value in holding onto multiple samples, but for now I lack the statistical tools to do anything with additional data.

> you have a TTL time window over which you collect the min, then you throw everything away and start again.

The intention is not to collect the min offset, only the min uncertainty (meaning the measurement which completed in the least amount of time on the local clock). We also don't throw _everything_ away after the TTL - the TTL is per measurement.

Does it look like that's not what is being done?

---

*[rpc/clock_offset.go, line 174 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_S2xT5y67wKxZSgJC:-KD__4oyebttAaSis1AS:-2010162036) ([raw file](https://github.com/cockroachdb/cockroach/blob/439e2cfe01b09864b11fb433f1730919b04db562/rpc/clock_offset.go#L174)):*
Good point. I'm going to leave this as-is because that's what the old code did, but @cuongdo should follow up.

---

*[rpc/context.go, line 26 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_OyeBfAr7B4wqIjLk:-KD_YZc4ixurtsSL7AVV:412784848) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L26)):*
Done.

This value was produced from my nether regions. Open to suggestions.

---

*[rpc/context.go, line 192 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_PAjlQ2YSNynCg3HI:-KD_Ykr8NacwTK0tAYjV:-1846022479) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L192)):*
Yeah, in this commit that is done in the RemoteClockMonitor which noops when MaxOffset() == 0.

---

*[rpc/context.go, line 201 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_T3qJThrj-RAAn7jk:-KD__CFKBhF913RXR-l_:267073949) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L201)):*
Assumption is my middle name. But seriously we could set uncertainty to pingDuration on either side; I'm not sure it's worth it, and not looking to change this logic in this PR. Does that seem reasonable?

---

*[rpc/context.go, line 203 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_PwBOymj3mLr3JPBO:-KD_YghhduAZbuU8sB-b:932309112) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L203)):*
Yeah, this is exactly the old code, just using time.Time and time.Duration instead of ints everywhere.

---

*[rpc/context_test.go, line 107 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_QzDingolPZyj4Z2q:-KD_Xes6mvJLBSmJrsNL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/context_test.go#L107)):*
Done.

---

*[rpc/context_test.go, line 184 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_VmcYYxGdvyilGCkD:-KD__d6snyWOlxOoNOCX:-891880456) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa9cf110d68923891d32de9c665141b24c6799c/rpc/context_test.go#L184)):*
just 'cause already have all the locals I need.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Comment by knz** [comment]
I'd advise against merging this for now. It is just *too* trigger-happy.
I am running the bank transfer over a 5-node cluster just after running `ntpdate` on each node, yet at least 1-2 nodes fail with `clock offset could not be determined: unable to determine the true cluster time from remote clock endpoints`. See example log here:
http://52.91.194.28/cgi-bin/display.py?path=cockroachdb-bank%3Ablank%2F20160323T223945.000Z&merge-logs=1

**Comment by knz** [comment]
More failures:
http://52.91.194.28/cgi-bin/display.py?path=cockroachdb-bank%3Ablank%2F20160323T224433.000Z&merge-logs=1
http://52.91.194.28/cgi-bin/display.py?path=cockroachdb-bank%3Ablank%2F20160323T224611.000Z&merge-logs=1
http://52.91.194.28/cgi-bin/display.py?path=cockroachdb-bank%3Ablank%2F20160323T224748.000Z&merge-logs=1
http://52.91.194.28/cgi-bin/display.py?path=cockroachdb-bank%3Ablank%2F20160323T224919.000Z&merge-logs=1

**Comment by tamird** [comment]
Can you add some detail about the test you're running?

**Comment by knz** [comment]
So the bank test is more or less what we have in acceptance right now. Parameters:

- 5 nodes
- 30 clients (6 per node)
- about 25 requests per second average globally (~5/s per node)
- nodes running on AWS cluster
- each AWS server synchronized prior to running the test using `ntpdate` (but not NTP-synchronized during the test)
- the SQL transactions performed by each client does a mix of reads and writes.

What we see in the results is servers committing suicide sometime after the test start, usually at least 5 seconds after the test begins.

**Comment by tamird** [comment]
Oh wow, so this is even without messing with the clocks. Interesting.

**Comment by nvanbenschoten** [comment]
Reviewed 6 of 6 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, 2 of 2 files at r10, 3 of 3 files at r11, 6 of 6 files at r12.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[rpc/context.go, line 201 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KD_T3qJThrj-RAAn7jk:-KDaVMDFL4b8KkEHWdYM:355482558) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d251aea26260873ab95b648ec4c7e05744c7e9/rpc/context.go#L201)):*
Yeah I wasn't intending for you to change anything, I was just curious.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Comment by knz** [comment]
You need another round of testing for this?

**Comment by tamird** [comment]
Not yet.

**Comment by knz** [comment]
With the latest code I see less premature failures, but now there are storms of the following message in the logs:

```
server/node.go:664	[node=3] unable to log node_restart event for node 3: .../storage/store.go:1539: rejecting command with timestamp in the future: 1459204448071879493 (29.897832727s ahead)
```

**Comment by tamird** [comment]
And you don't see that with master? Seems unrelated to this

**Comment by knz** [comment]
Ok so it seems that this latest code is somewhat less effective at detecting clock skews. In a couple of tests servers happily accept requests with skews of more than a few minutes without terminating. I cannot see whether this leads to db corruption. 

Also the log spam with the message given in the previous comment is a serious issue. It seems to be emitted in a tight loop, I get thousands of entries as a result.

**Comment by knz** [comment]
This is with your branch tamird/cockroach offset-monitor-continuously

**Comment by knz** [comment]
In master I will see:
- "rejecting command with timestamp in the future" on the client with no excessive logging on the server; 
- sometimes, a server suicide
- occasionally, a db consistency error

the symptoms with your branch are different:
- much less occurrences of  "rejecting command with ts in the future" on the client
- more db suicides
- the aforementioned log storm

**Comment by tamird** [comment]
Oh, I see what the log storm is about

Whenever a node is restarted, it attempts to record a `sql.EventLogNodeJoin` event into the eventlog table; if this fails, an error is logged (this is the `[node=3] unable to log node_restart event for node 3` message you keep seeing).

Here's what I suspect the sequence of events is:
1. cluster starts, clocks are healthy
2. clock manipulation starts
3. node k notices its clock is skewed, dies
4. node k restarts
5. node k attempts to record `sql.EventLogNodeJoin` but fails because its clock is skewed (timestamp in the future) and logs an error
6. goto 3

The result: log storm. WDYT?

**Comment by knz** [comment]
Sounds reasonable, but that's not what's happening in those specific tests: I don't restart nodes after they die.

**Comment by knz** [comment]
SGTM

**Comment by knz** [comment]
Woudln't it be useful/smart to abort the join if the clocks are found not to be in sync?

**Comment by tamird** [comment]
Yes, maybe, but that is certainly outside the scope of this PR.

It's really a systematic problem that extends well beyond just these "join events".

I'll add a backoff on those events though, so we don't get a log storm.

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[rpc/clock_offset.go, line 73 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE80-63ogSW4myg9ji_:-KE80-64JxYICQ9s_qGi:-1969959275) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/clock_offset.go#L73)):*
There is nothing returned from this method, error or otherwise.

---

*[rpc/clock_offset.go, line 196 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE82E8OAiXnLUSOAJmy:-KE82E8OAiXnLUSOAJmz:1721841622) ([raw file](https://github.com/cockroachdb/cockroach/blob/b88b6e4a302a3bcdb507d70614ae05dd1fc19ff2/rpc/clock_offset.go#L196)):*
You're no longer updating these metrics. 

---

*[rpc/clock_offset_test.go, line 110 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE8423WVobT-Z5PGQhx:-KE8423WVobT-Z5PGQhy:48126194) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/clock_offset_test.go#L110)):*
`s/offests/offsets/g`

---

*[rpc/context.go, line 174 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE8343lVcgmkQzQ5ED6:-KE8343lVcgmkQzQ5ED7:-373107095) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/context.go#L174)):*
Curious why you're switching from `int64` nanos to `time.Time`. The latter isn't giving you anything for the time ranges we're dealing with.

---

*[server/node.go, line 652 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE83YqHJqeBcgM38EVP:-KE83YqHJqeBcgM38EVQ:2146984561) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/server/node.go#L652)):*
This is unrelated to this PR, correct? Can you pull it out into a separate PR?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[rpc/clock_offset.go, line 73 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE80-63ogSW4myg9ji_:-KE84tADH0AzS9OhpXAL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/clock_offset.go#L73)):*
Done.

---

*[rpc/clock_offset.go, line 196 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE82E8OAiXnLUSOAJmy:-KE84twsX5aUxMBq8BIX:687746062) ([raw file](https://github.com/cockroachdb/cockroach/blob/b88b6e4a302a3bcdb507d70614ae05dd1fc19ff2/rpc/clock_offset.go#L196)):*
Yeah,  I discussed this with @cuongdo: these metrics don't really make sense anymore, so he's going to rework them in a follow-up.

---

*[rpc/clock_offset_test.go, line 110 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE8423WVobT-Z5PGQhx:-KE856hHabo8aYRtR22J:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/clock_offset_test.go#L110)):*
Done.

---

*[rpc/context.go, line 174 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE8343lVcgmkQzQ5ED6:-KE858qKOzq2AsMvx9YF:-829008511) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/context.go#L174)):*
most of those conversions were just done for convenience and type safety.

---

*[server/node.go, line 652 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE83YqHJqeBcgM38EVP:-KE85Dfi9NZ2o0E4kgRX:2019323937) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/server/node.go#L652)):*
Sure, I can. It was done here because @knz noticed the issue while testing this PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Comment by petermattis** [comment]
So the upshot of this PR is that we'll check the cluster time offset on every heartbeat instead of checking it once every `10*heartbeatInterval`? If yes, :lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[rpc/clock_offset.go, line 117 \[r37\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE87vmSZNhGaK2J58rm:-KE87vmSZNhGaK2J58rn:-1056796403) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a15b0766146f886a4b3317f77f4faffc0b7411/rpc/clock_offset.go#L117)):*
Can you add a comment explaining the calculation you're performing and why we're moving away from Marzullo's algorithm?

---

*[rpc/context.go, line 174 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE8343lVcgmkQzQ5ED6:-KE86B2PDO34eBQXo87_:1028105776) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/context.go#L174)):*
`receiveTime - sendTime` is more obvious to me than `receiveTime.Sub(sendTime)`, but perhaps that is just me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-:-KE86c5y63Cumjo6n_Yq:1769612234)*

**Comment by tamird** [comment]
Yep.

---

Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[rpc/clock_offset.go, line 117 \[r37\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE87vmSZNhGaK2J58rm:-KE8C1PT1f-6N0EcWNFF:74062592) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a15b0766146f886a4b3317f77f4faffc0b7411/rpc/clock_offset.go#L117)):*
Done in the function comment. Doesn't address Marzullo's specifically, but I don't think that's necessary.

---

*[rpc/context.go, line 174 \[r36\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE8343lVcgmkQzQ5ED6:-KE89bCAOqi12LceXmen:2127289079) ([raw file](https://github.com/cockroachdb/cockroach/blob/421d92bccbc9341b908cbd317a945a3c8bad38d8/rpc/context.go#L174)):*
I prefer the latter because there's no mixing up durations and times.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-:-KE89OtXvOiRlwiWjQgu:677251183)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[rpc/clock_offset.go, line 117 \[r37\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE87vmSZNhGaK2J58rm:-KE8DmVHZjeDeL2dYbnO:-1616503436) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a15b0766146f886a4b3317f77f4faffc0b7411/rpc/clock_offset.go#L117)):*
Perhaps add a parenthetical for what it means for an offset to be healthy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[rpc/clock_offset.go, line 117 \[r37\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE87vmSZNhGaK2J58rm:-KE8ETLbGNItvQ-MH8sI:714571862) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a15b0766146f886a4b3317f77f4faffc0b7411/rpc/clock_offset.go#L117)):*
> is healthy (as defined by RemoteOffset.isHealthy)

not enough? the implementation of RemoteOffset.isHealthy is pretty succinct and clear thanks to the V(1) log in it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[rpc/clock_offset.go, line 117 \[r37\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE87vmSZNhGaK2J58rm:-KE8RhCCk3WP2qIXpnMF:690167539) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a15b0766146f886a4b3317f77f4faffc0b7411/rpc/clock_offset.go#L117)):*
Well, that parenthetical didn't add much. I was hoping for a bit about how the remote clock offset has uncertainty associated with it. It's all clear in your mind right now, but you'll want a refresher when you look at this in a few months.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[rpc/clock_offset.go, line 117 \[r37\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512#-KE87vmSZNhGaK2J58rm:-KE8SBpK0bz8H3XKoJu0:-535371914) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4a15b0766146f886a4b3317f77f4faffc0b7411/rpc/clock_offset.go#L117)):*
I didn't want to duplicate that information here (hence the callout to RemoteOffset.isHealthy which is defined in this same file).

I added some comments about uncertainty in that function.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5512)*

**Pull request merged**
