### PR TITLE
sql: Add system.jobs table and migration to add it to existing DBs

### PR DESCRIPTION
**Pull request by a-robinson**
Ignore the first three commits - they're already under review in #11658. This is the first use of the infrastructure introduced in that PR for safely running backward-compatible migrations at node startup.

@vivekmenezes @paperstreet @bdarnell 

Commit message:

Unfortunately, this required playing around a bit with the table
creation code to get the permissions and ID right on the new table.
This feels a little dangerous, so let me know what you think. I
effectively ripped it straight out of #7073.

The alternative was to add the table directly to kv, bypassing the SQL
layer, but that seems dangerous to do anytime other than initial
bootstrapping and won't work great for future changes like adding a
new column or index to a system table.

In other news, the amount of tests that have hard-coded results
dependent on the system tables makes adding a new table a bit of a
chore, but I suppose that adding a system table isn't a very common
operation.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11722)

### CODE REVIEW

**Comment by a-robinson** [comment]
Also, the schema is a bit of a strawman sketched out with @paperstreet, who also talked with @dt. We figured we'd leave the `lease` field out until we have code that uses it, but that same reasoning actually applies to this commit in general -- it'd be fine to leave this of master out until we have code that uses it. It's main purpose for me was to put the migration code through its paces a bit.

**Comment by vivekmenezes** [comment]
Alex, It's probably better to leave this code out of master for now.

Do you think we can fix
https://github.com/cockroachdb/cockroach/issues/5887 using
the new mechanism. It might mean adding in some code that reads the
descriptor and rewrites it with the new function unique_rowid. I don't
think we have to go through the elaborate scheme described in the bug.

**Comment by a-robinson** [comment]
Yes, I believe we could fix #5887. I do think we may want to take the approach mentioned in the issue, though, given that switching from `experimental_unique_bytes` to `unique_rowid` means switching the column type from `BYTES` to `INT`.

And not merging this SGTM. I'm always wary of adding things that aren't being used yet. That's why I tried this out to utilize the migration code, but the unique_rowid change can work for that as well.

**Comment by a-robinson** [comment]
Closing in favor of#12228 as the first migration to use the new infrastructure. Something along these lines can be resurrected when needed.

**Pull request closed without merging**
