### PR TITLE
multitenant: add version gate to alter tenant capabilities

### LINKED ISSUE #97756: multitenant: add version gate to set and enforce capabilities
TODO

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #97756

Tenant capabilities should not be modifiable in mixed 22.2/23.1 version clusters to prevent inconsistent behavior between nodes that obey capabilities (23.1) and ignore them (22.2).

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Thanks for the quick fix! 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-:-NPK02DA91tFeOlN2idI:b-d7punr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @rafiss)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-NPK08xZ9KVFIRBvfnxF):*
Should this version gate cover tenant capabilities as a whole, and not just altering them? For example, do we want to version gate checks in the `Authorizer` as well? 
___
*[`pkg/sql/tenant_test.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-NPK0Vmx6Hex1ERbFKGa:-NPK0Vmx6Hex1ERbFKGb:b-i4t716) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fc934b8ca5c5f3a095eb7b371b2c1f39bf1ba6/pkg/sql/tenant_test.go#L137)):*
> ```Go
> }
> 
> func TestAlterTenantCapabilityMixedVersion22_2_23_1(t *testing.T) {
> ```

Are we able to make this a logic test instead?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97764)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @knz, and @rafiss)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-NPK08xZ9KVFIRBvfnxF):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this version gate cover tenant capabilities as a whole, and not just altering them? For example, do we want to version gate checks in the `Authorizer` as well? 
</blockquote></details>

The work to customize capability defaults has not been done yet, but I think we want to have at least `can_admin_split` and `can_admin_scatter` on by default so the authorizer should not be skipped.

When I work on that I will test that the 23.1 default matches the 22.2 behavior.
___
*[`pkg/sql/tenant_test.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-NPK0Vmx6Hex1ERbFKGa:-NPKAi2Q8bo77ffPmFy3:b-rssybt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fc934b8ca5c5f3a095eb7b371b2c1f39bf1ba6/pkg/sql/tenant_test.go#L137)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Are we able to make this a logic test instead? 
</blockquote></details>

There is no logic test config for mixing `22.2` with `23.1` and using the system tenant.

I don't think it's worth adding unless we end up with a bunch of these tests since it is only temporary.

Maybe the multi-version testing work will make this easier in the future.

**Review by knz — COMMENTED** [review]
Don't you think we should also use this version get to _check_ the capabilities during kv authorization?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97764)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-NPK08xZ9KVFIRBvfnxF):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

The work to customize capability defaults has not been done yet, but I think we want to have at least `can_admin_split` and `can_admin_scatter` on by default so the authorizer should not be skipped.

When I work on that I will test that the 23.1 default matches the 22.2 behavior.
</blockquote></details>

This is in line with @knz's comment below. We should version gate the entire subsystem, by using this cluster version to gate checks in the `Authorizer` as well.

**Review by ecwall — COMMENTED** [review]
Doing that will require that we add back all of the `UnsupportedWithMultiTenancy` errors to SQL and combine them with new `!version.IsActive` checks. There will be additional cleanup work in the next release to remove the `UnsupportedWithMultiTenancy` errors.

We will also have to add an additional test case for each capability for the old version of the cluster to trigger the `UnsupportedWithMultiTenancy` error.

I think we can avoid doing this by ensuring
1) Capabilities cannot be set until the new version is finalized (this PR).
2) The default capability values match the behavior of the previous version, which I think needs to happen anyways to simplify the cluster upgrade.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-:-NPO91PDEpUWvMLmOPT0:b-l4kwpm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @knz, and @rafiss)

**Comment by knz** [comment]
ok that works for me

**Review by arulajmani — APPROVED** [review]
@ecwall, like we talked about offline earlier today, we do need version gate checks for the tenant capability subsystem. For example, the rangefeed in the `Watcher` won't work because the `TenantInfo` column doesn't exist until the migration runs. However, let's not keep this PR open for that -- I'll file a separate issue. 

> Reviewed 1 of 1 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-:-NPT3WfL3H_wJTE3hz-d:bsprpiw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/tenant_test.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97764#-NPK0Vmx6Hex1ERbFKGa:-NPT4z6L7MVAHLcdGT2q:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fc934b8ca5c5f3a095eb7b371b2c1f39bf1ba6/pkg/sql/tenant_test.go#L137)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

There is no logic test config for mixing `22.2` with `23.1` and using the system tenant.

I don't think it's worth adding unless we end up with a bunch of these tests since it is only temporary.

Maybe the multi-version testing work will make this easier in the future.
</blockquote></details>

Ack.

**Comment by ecwall** [comment]
bors r=arulajmani

**Pull request merged**
