### PR TITLE
sql: fix and enhance the parse-print-parse roundtrip of INTERVAL.

### LINKED ISSUE #14484: cli: SQL shell history rewriting mangles INTERVAL
Repro:
1. Launch SQL shell
2. Run `SELECT DATE '1998-12-01' - INTERVAL '95' DAY;`
3. Hit up to recall the `SELECT` and run it again. You'll get the error `pq: unsupported binary operator: <date> - <string>`.

Expected: #3 should return 0 rows

SQL shell transcript:
```sql
root@:26257/tpch> SELECT DATE '1998-12-01' - INTERVAL '95' DAY;
+--------------------------------+
| DATE '1998-12-01' - '0m95d0ns' |
+--------------------------------+
| 1998-08-28 00:00:00+00:00      |
+--------------------------------+
(1 row)
--- I hit "up" then "enter" here
root@:26257/tpch> SELECT DATE '1998-12-01' - '0m95d0ns';
pq: unsupported binary operator: <date> - <string>
```

### LINKED ISSUE #14499: sql: INTERVAL datums larger than a day don't pretty-print to parsable values
e.g. `INTERVAL '95' DAY`

found with #14484

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, durations larger than a month would be printed
using the unit "m", which is ambiguous with "minutes".  This caused
problems in particular with distSQL which expects that the
representation of all datums can be parsed back to a datum.  This
patch fixes the issue by using "mon" instead for months.

Also the postgres syntax parser ("1 minute 30 seconds") is extended to
support decimal numbers ("1.5 minute") which in turn enables the code
to use a single path to parse both Go and postgres duration syntax.

It is also extended to recognize the extended pg syntax "HH:MM:SS" in combination with units,
e.g. "1 day 3:12" is "1 day, 3 hours and 12 minutes".

Fixes #14499.
Fixes #14484.

@jordanlewis can you please advise what is the parse test `SET TIME ZONE INTERVAL '-7h0m5s' HOUR TO MINUTE` (`sql/parser/parse_test.go`) doing, and what it's really testing. With my modified code now it pretty-prints back to `-6h59m0s`, I do not know whether this is a problem and what it means.

NB:  this is a preliminary PR to check whether the overall direction is OK. there are some test cases still missing from this PR, I'll polish this to completion once I get your advice.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14534)

### CODE REVIEW

**Comment by knz** [comment]
cc @RaduBerinde

**Comment by jordanlewis** [comment]
Thanks for tackling this! The code is quite tricky. I did not carefully review all cases in the parser. I agree that you need more tests, but I think this is a good starting point.

That test was supposed to check that the `HOUR TO MINUTE` properly indicates that the interval should be truncated to minute precision. Postgres also thinks that the result of that should be -6h59m0s. I absolutely do not understand why that is the case, but I suppose you did something right if you're getting that result as well.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/interval.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-KgePB6SQONS32cWQLGk:-KgePB6SQONS32cWQLGl:bggkutn) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f10b9fbab7e7ffdb0ab7c4c34634095a8b052c/pkg/sql/parser/interval.go#L35)):*
> ```Go
> }
> 
> // Consumes the next decimal number.
> ```

Start comment with consumeNum to follow go style.

---

*[pkg/util/duration/duration.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-KgeQVwT15ID2Bb3x62s:-KgeQVwT15ID2Bb3x62t:b-qb82hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f10b9fbab7e7ffdb0ab7c4c34634095a8b052c/pkg/util/duration/duration.go#L84)):*
> ```Go
> // String returns a string representation of a Duration.
> func (d Duration) String() string {
> 	var buf bytes.Buffer
> ```

Why not go all the way and print out the years as well?

```
jordan=# select '1-2'::interval;
   interval
---------------
 1 year 2 mons
(1 row)

jordan=# select '1- 3:'::interval;
    interval
-----------------
 1 year 03:00:00
(1 row)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-:-KgeOrzXWNZejeAarJQh:b-h1vvew)*

**Comment by RaduBerinde** [comment]
It's like that because the `-` does not apply to all the fields. `-7h0m5s` is actually -7h + 5s:
```
postgres=# select interval '-7h0m5s';
select interval '-7h0m5s';
 interval  
-----------
 -06:59:55
```

So when we discard the seconds we are left with `-06:59`

Note that PG (and I guess CRDB) differs from the SQL standard wrt the sign behavior. See https://www.postgresql.org/docs/9.1/static/datatype-datetime.html (grep for "According to the SQL standard").

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-:-KgeerbWLHhK1LskVM2b:b-kthjaa)*

**Comment by knz** [comment]
Thanks for your comments. I'll iterate on the PR and let you know when I'm further down the road.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/duration/duration.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-KgeQVwT15ID2Bb3x62s:-Kgfl8uyd2mDpAjVEr87:b-8h1hte) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f10b9fbab7e7ffdb0ab7c4c34634095a8b052c/pkg/util/duration/duration.go#L84)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why not go all the way and print out the years as well?

```
jordan=# select '1-2'::interval;
   interval
---------------
 1 year 2 mons
(1 row)

jordan=# select '1- 3:'::interval;
    interval
-----------------
 1 year 03:00:00
(1 row)
```
</blockquote></details>

That's because we don't have a separate field for years -- we only use separate fields when there is no constant factor between a unit and the next (e.g. there are always 12 months in a year, but a varying number of days in a month)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-:-KgflMNUa5nfpkCzksb7:bazec3e)*

**Comment by knz** [comment]
I have fixed most of the remaining issues and added the missing tests. PTAL

---

Review status: 2 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/interval.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-KgePB6SQONS32cWQLGk:-KgoUgPg8Qj8s1rCb1RE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f10b9fbab7e7ffdb0ab7c4c34634095a8b052c/pkg/sql/parser/interval.go#L35)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Start comment with consumeNum to follow go style.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-:-KgoUvZLkIYMkUisJtdT:bpkmqgn)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: 2 of 19 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/interval.go, line 506 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-Kh3ShT2bcUp3Gxs4OUD:-Kh3ShT2bcUp3Gxs4OUE:bfddz34) ([raw file](https://github.com/cockroachdb/cockroach/blob/df26e90b9c56c5c7b12d8bc360e031d7712b03d7/pkg/sql/parser/interval.go#L506)):*
> ```Go
> }
> 
> // addFract increases the duration given as first argument by the unit
> ```

addFrac*

---

*[pkg/util/duration/duration.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-KgeQVwT15ID2Bb3x62s:-KggEOcYqMh1rTysmCUO:b-894zku) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f10b9fbab7e7ffdb0ab7c4c34634095a8b052c/pkg/util/duration/duration.go#L84)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That's because we don't have a separate field for years -- we only use separate fields when there is no constant factor between a unit and the next (e.g. there are always 12 months in a year, but a varying number of days in a month)
</blockquote></details>

That's fine, but the display format doesn't have to be constrained to the same restrictions that we have internally, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-:-Kh3TIw3P5o7ngw_-P77:bnfp4nl)*

**Comment by jordanlewis** [comment]
Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534)*

**Comment by knz** [comment]
TFYR :)

---

Reviewed 1 of 17 files at r2.
Review status: 8 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/parser/interval.go, line 506 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-Kh3ShT2bcUp3Gxs4OUD:-KhMas9MM2x1rMYAkX7L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df26e90b9c56c5c7b12d8bc360e031d7712b03d7/pkg/sql/parser/interval.go#L506)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

addFrac*
</blockquote></details>

Done.

---

*[pkg/util/duration/duration.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-KgeQVwT15ID2Bb3x62s:-KhMavEoYcVFdwwUuA5U:ba12awe) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f10b9fbab7e7ffdb0ab7c4c34634095a8b052c/pkg/util/duration/duration.go#L84)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

That's fine, but the display format doesn't have to be constrained to the same restrictions that we have internally, right?
</blockquote></details>

Sure, ok, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14534#-:-KhMdY0eS_WqBsg3Z5aW:bog7ikf)*

**Pull request merged**
