### PR TITLE
cli: extend `gen settings-list`

### LINKED ISSUE #80097: cli: Update auto-generated Cluster Settings doc to specify suitable environments per setting
Some cluster settings are intended for a specific deployment environment (Serverless, Dedicated, Self-Hosted) or a combination of environments. We should be clear about this on our auto-generated [cluster settings doc](https://www.cockroachlabs.com/docs/stable/cluster-settings.html).

Related [PR](https://github.com/cockroachdb/cockroach/pull/79892).
Related [Slack thread](https://cockroachlabs.slack.com/archives/C02HWA24541/p1649884815325129). 

Jira issue: CRDB-15849

### PR DESCRIPTION
**Pull request by knz**
Fixes #80097

We want to have a way to print all settings with their class and
visibility for internal investigations.

This is also useful for public-facing documentation, where we want to
split settings according to what users can expect from SET CLUSTER
SETTINGS.

The generated files are as follows:

- `settings-for-tenant.txt`: a TSV file containing settings that
  tenants can access (i.e. excluding `system-only` settings which
  cannot be set/accessed by tenants).

  NEW: a new `class` column, containing either:

  - `tenant-rw`: the tenant can use both SHOW and SET
  - `tenant-ro`: the tenant can use only SHOW

- `settings.html`: complete list of settings.

  NEW: the same `class` column as above. This column
  also contain  `system-only` setting in this file.

  Also, a new `visibility` column, which separates
  public vs reserved settings.

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @knz! I need help understanding a few things:

- In the generated `settings.html`, all settings have `public` visibility. If we're only exposing public settings in the docs, which I think is good, we should probably just remove the `Visibility` column from the table.
- I don't quite understand the meaning of the values in the `Class` column of the table. Ideally, I'd like our docs to make it clear whether a setting is usable (r and w) for each environment, Serverless, Dedicated, Self-Hosted. Do these values give me that information?
- How are you imagining `settings-for-tenants.txt` getting used in our docs? Right now, the generated settings docs are included on this page: https://www.cockroachlabs.com/docs/stable/cluster-settings.html

**Comment by knz** [comment]
> we should probably just remove the Visibility column from the table.

done.

> I'd like our docs to make it clear whether a setting is usable and meaningful for each environment, Serverless, Dedicated, Self-Hosted. Do these values give me that information?

yes

- Only the settings in `settings-for-tenants.txt`, i.e. those in settings.html that do *not* have class == `system-only`, can be used in serverless.
- all the others are usable in serverless, dedicated and self-hosted
- starting in v23.1 (or around that time), `system-only` settings will also become unavailable to dedicated users.

**Comment by knz** [comment]
> How are you imagining settings-for-tenants.txt getting used in our docs? 

I have no idea -- the existence of this generated file was a discovery to me and I assume the person who added it knows what it's used for.

**Comment by jseldess** [comment]
Thanks for the clarification, @knz. Here's a proposal that I think might make the generated doc more intuitive to end-users:

- In the generated file, change `Class` to `Supported Deployments`, maybe as a link to https://www.cockroachlabs.com/docs/stable/choose-a-deployment-option.html.
- For the `Supported Deployment` values:
    - change `tenant-rw` to `Serverless/Dedicated/Self-Hosted`
    - change `tenant-ro` to `Serverless/Dedicated/Self-Hosted (read-only)`
    - change `system-only` to `Dedicated/Self-Hosted`

Thoughts?

**Comment by knz** [comment]
Works for me. Done.

RFAL

**Comment by knz** [comment]
@nickvigilante can you help me close the loop on this?

**Comment by nickvigilante** [comment]
@knz Sure. @andf-crl is also reviewing.

**Review by andf-crl — APPROVED** [review]
LGTM, but noting some out-of-scope observations for future efforts:
- Descriptions that include `<` or `>` characters fail to render when included in our docs (example: `trace.zipkin.collector`, can be seen [live](https://www.cockroachlabs.com/docs/stable/cluster-settings.html))
- Descriptions that include backticks similarly fail to render (example: `server.oidc_authentication.redirect_url`, can be seen [live](https://www.cockroachlabs.com/docs/stable/cluster-settings.html))
- Presently, DOCS doesn't know what to do with `settings-for-tenants.txt` but I'll investigate (Guess: `settings-for-tenants.html` is a subset of `settings.html` list, and, with new column to indicate `class` now being added to `settings.html` (thanks!), there is likely no need to ever display `settings-for-tenants.html` itself in our docs.)

Thanks for this!!

**Review by nickvigilante — APPROVED** [review]
LGTM! Do the merge conflicts have any impact on this? And will it cause problems when backporting these changes?

**Comment by knz** [comment]
bors r=andf-crl,nickvigilante

**Comment by knz** [comment]
bors r=andf-crl,nickvigilante

**Pull request merged**
