### PR TITLE
sql,server: exposes TxnIDResolution rpc endpoint

### PR DESCRIPTION
**Pull request by Azhng**
This commit introduces the new TxnIDResolution RPC endpoint. This RPC
endpoint utilizes the new txnidcache.Reader interface to perform
transaction ID resolution.

Partially addresses #74487

Release note: None

### CODE REVIEW

**Comment by Azhng** [comment]
Rebased to pick up a lot of changes that can cause potential merge conflict. Still, only the last commit is relevant.

**Review by matthewtodd — APPROVED** [review]
Reviewed in person, some nits but otherwise :lgtm: 

> Reviewed 2 of 18 files at r12, 2 of 16 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-:-Mw2Cu3oB6axz-Vnn-SJ:b-y3iac1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/server/status.go, line 384 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw266Bh8XFqyijy665R:-Mw266Bh8XFqyijy665S:blmbfdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L384)):*
> ```Go
> 	resp := &serverpb.TxnIDResolutionResponse{
> 		ResolvedTxnIDs: make([]contentionpb.ResolvedTxnID, 0, len(req.TxnIDs)),
> 	}
> ```

nit: I was surprised to see this allocation followed by a reassignment below. I think that's because I don't deeply understand go memory management. Maybe add a comment saying why?
___
*[pkg/server/status.go, line 389 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw26yPq84tu_SMDSp5G:-Mw26yPq84tu_SMDSp5H:b-b5g9nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L389)):*
> ```Go
> 	// attempt fails, we flush the txnID cache and try again.
> 	unresolvedTxnIDs, resp.ResolvedTxnIDs =
> 		resolveTxnIDHelper(txnIDCache, unresolvedTxnIDs, resp.ResolvedTxnIDs)
> ```

nit: the name "helper" doesn't help me understand what's happening here. (Words like manager and coordinator have a similar smell.)
___
*[pkg/server/status.go, line 392 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw27OqyAzW6pVIjskdL:-Mw27OqyAzW6pVIjskdM:b-oizbbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L392)):*
> ```Go
> 
> 	if len(unresolvedTxnIDs) > 0 {
> 		txnIDCache.Flush()
> ```

nit: maybe say why flushing might help? Edit: there are things floating up above the proper cache in some incoming data structure, not yet accessible for reading.

So is there a name other than Flush that evokes that concept? Drain write buffers?
___
*[pkg/server/status.go, line 392 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw27eDZ8qGXbVQq9q0C:-Mw27eDZ8qGXbVQq9q0D:b6dtl4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L392)):*
> ```Go
> 
> 	if len(unresolvedTxnIDs) > 0 {
> 		txnIDCache.Flush()
> ```

nit: @azhng says flushing is async anyway. So does the second loop below accomplish anything?
___
*[pkg/server/status.go, line 3085 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw28ccm1y6C7tqWDvCB:-Mw28ccm1y6C7tqWDvCC:b-1gbf7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L3085)):*
> ```Go
> 	ctx context.Context, req *serverpb.TxnIDResolutionRequest,
> ) (*serverpb.TxnIDResolutionResponse, error) {
> 	ctx = s.AnnotateCtx(propagateGatewayMetadata(ctx))
> ```

nit: double-check we've got all the security boilerplate here. (Sorry I forget all that's required.)
___
*[pkg/server/tenant_status.go, line 1049 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw28nV02t788s12hU7Z:-Mw28nV02t788s12hU7_:blzgq11) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/tenant_status.go#L1049)):*
> ```Go
> 	ctx context.Context, req *serverpb.TxnIDResolutionRequest,
> ) (*serverpb.TxnIDResolutionResponse, error) {
> 	ctx = t.AnnotateCtx(propagateGatewayMetadata(ctx))
> ```

nit: ditto re: security.
___
*[pkg/server/serverpb/status.proto, line 1496 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw24HO_7IJnUgF8rp2z:-Mw24HOa5m5eczSFw2Nb:b88h3wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/serverpb/status.proto#L1496)):*
> ```protobuf
>   // coordinator_id is either the NodeID or SQLInstanceID depending on whether
>   // the transaction is executed on a system tenant or a regular tenant.
>   string coordinator_id = 1 [(gogoproto.customname) = "CoordinatorID"];
> ```

nit: Is `coordinator` a common name for this? Does it make sense to use it at this layer? (Maybe check what we do in other status endpoints?)
___
*[pkg/sql/contentionpb/contention.proto, line 141 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw24tba2bN1PsJ_gvzU:-Mw24tba2bN1PsJ_gvzV:b-9rbp6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/sql/contentionpb/contention.proto#L141)):*
> ```protobuf
>   ];
> 
>   // This field is allowed to be null. This means the given transaction ID
> ```

nit: Oops, not allowed to be null.
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 907 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2AcaMEWY6qeStN_n5:-Mw2AcaMEWY6qeStN_n6:b-y4v7od) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L907)):*
> ```Go
> SELECT id
> FROM crdb_internal.node_transactions
> WHERE application_name = 'test1'`)
> ```

nit: Sometimes I pass example SQL like this through sqlfum.pt and then indent it in the test.
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 911 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2B5zT6LExZLnw831A:-Mw2B5zT6LExZLnw831B:b-sn4otd) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L911)):*
> ```Go
> 			"expected only one active txn, but there are %d active txns found", len(result))
> 		txnID := uuid.FromStringOrNil(result[0][0])
> 		require.False(t, uuid.Nil.Equal(txnID),
> ```

nit: is `uuid.Nil` the same as `uuid.UUID{}`? Would it make sense to use it in the above `.Valid()` method? IDK.
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 924 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2BhCfBucB9EwJjUTQ:-Mw2BhCfBucB9EwJjUTR:b1l1m5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L924)):*
> ```Go
> 				return errors.New("txnID not found")
> 			}
> 			require.True(t, resp.ResolvedTxnIDs[0].TxnID.Equal(txnID))
> ```

nit: Can this be `require.Equal`? (Otherwise you get an unhelpful failure message.) (Maybe stringify the uuids and compare them that way if necessary?)
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 924 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2CAkxE37B23xqeDVK:-Mw2CAkxE37B23xqeDVL:b-tdi2ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L924)):*
> ```Go
> 				return errors.New("txnID not found")
> 			}
> 			require.True(t, resp.ResolvedTxnIDs[0].TxnID.Equal(txnID))
> ```

nit: maybe say that the main thing we're testing is that `coordinatorNodeID` is the one that knows about this `txnID`?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @matthewtodd)

___
*[pkg/server/status.go, line 384 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw266Bh8XFqyijy665R:-Mw2mmY8BVWGATscB0zE:bmvkzop) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L384)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: I was surprised to see this allocation followed by a reassignment below. I think that's because I don't deeply understand go memory management. Maybe add a comment saying why?
</blockquote></details>

Done. Removed assign-after-allocate since the RPC handler no longer retries.

It probably doesn't quite matter here in this case, but my intuition here was to avoid returning a memory object allocated locally within a helper function. 

So when allocating an object in a function in Go, there are two cases:
1. if the object is created on the heap, then returning this object from the function is fine.
2. if the object is small enough to create on the stack, then returning a pointer to this object from this function will cause this object to escape to heap, which incurs unnecessary heap allocation. Though I guess this problem goes away if compiler is smart enough to inline the function :thinking:
___
*[pkg/server/status.go, line 389 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw26yPq84tu_SMDSp5G:-Mw2mODT6g-YZDdxgP5R:b-hqvnrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L389)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: the name "helper" doesn't help me understand what's happening here. (Words like manager and coordinator have a similar smell.)
</blockquote></details>

Done. Removed. 
___
*[pkg/server/status.go, line 392 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw27OqyAzW6pVIjskdL:-Mw2f2Wh5mRhibRtv9R4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L392)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: maybe say why flushing might help? Edit: there are things floating up above the proper cache in some incoming data structure, not yet accessible for reading.

So is there a name other than Flush that evokes that concept? Drain write buffers?
</blockquote></details>

Done.
___
*[pkg/server/status.go, line 392 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw27eDZ8qGXbVQq9q0C:-Mw2hpJYEL3vk_qgWdoz:b-cyu6pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L392)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: @azhng says flushing is async anyway. So does the second loop below accomplish anything?
</blockquote></details>

Good point. Defer the retry logic completely to the client. 
___
*[pkg/server/status.go, line 3085 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw28ccm1y6C7tqWDvCB:-Mw2obwKDpQSPN3-h35e:bhn84h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L3085)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: double-check we've got all the security boilerplate here. (Sorry I forget all that's required.)
</blockquote></details>

Seems like we have everything here. 
___
*[pkg/server/serverpb/status.proto, line 1496 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw24HO_7IJnUgF8rp2z:-Mw2ooFcEOG9t3YjAM6j:b-iegpn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/serverpb/status.proto#L1496)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Is `coordinator` a common name for this? Does it make sense to use it at this layer? (Maybe check what we do in other status endpoints?)
</blockquote></details>

I think it is ok to use the term `coordinator` at this layer. Few reasons:
1. `coordinator` is a pretty common concept exists throughout all stacks within cockroach
2. The endpoint exists so that the RPC request can be routed to the coordinator node that executed the transaction. So explicitly calling it `coordinator` here make that purpose clear. 
___
*[pkg/sql/contentionpb/contention.proto, line 141 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw24tba2bN1PsJ_gvzU:-Mw2iIYzD1myGzJ-cNvy:b-2ao8ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/sql/contentionpb/contention.proto#L141)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Oops, not allowed to be null.
</blockquote></details>

Done. Updated.
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 907 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2AcaMEWY6qeStN_n5:-Mw2ifgJ9kxDy_hBt9gk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L907)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Sometimes I pass example SQL like this through sqlfum.pt and then indent it in the test.
</blockquote></details>

Done.
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 911 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2B5zT6LExZLnw831A:-Mw2irgc4fyUfFs8I6Re:b-r1g0g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L911)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: is `uuid.Nil` the same as `uuid.UUID{}`? Would it make sense to use it in the above `.Valid()` method? IDK.
</blockquote></details>

Done. Good point, `uuid.Nil` is equal to `uuid.UUID{}`. Updated `.Valid()` to use the `uuid.Nil`
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 924 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2BhCfBucB9EwJjUTQ:-Mw2jOzU89gdgaPSIZ-A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L924)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Can this be `require.Equal`? (Otherwise you get an unhelpful failure message.) (Maybe stringify the uuids and compare them that way if necessary?)
</blockquote></details>

Done.
___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 924 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw2CAkxE37B23xqeDVK:-Mw2m5y15HLnZbg73s5o:bqmdzmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L924)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: maybe say that the main thing we're testing is that `coordinatorNodeID` is the one that knows about this `txnID`?
</blockquote></details>

Done. Added the testing error message explaining what we are looking for here.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @matthewtodd)

___
*[pkg/server/status.go, line 384 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75177#-Mw266Bh8XFqyijy665R:-Mw35QAa63WYh5vzZKSU:bxzqytg) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a2ae9ef42e9ba14fe73ec3d8ae48d561efd105/pkg/server/status.go#L384)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done. Removed assign-after-allocate since the RPC handler no longer retries.

It probably doesn't quite matter here in this case, but my intuition here was to avoid returning a memory object allocated locally within a helper function. 

So when allocating an object in a function in Go, there are two cases:
1. if the object is created on the heap, then returning this object from the function is fine.
2. if the object is small enough to create on the stack, then returning a pointer to this object from this function will cause this object to escape to heap, which incurs unnecessary heap allocation. Though I guess this problem goes away if compiler is smart enough to inline the function :thinking:
</blockquote></details>

I see, that's helpful as I build my own intuition. Thank you!

**Comment by Azhng** [comment]
TFTR!

bors r+

**Pull request merged**
