### PR TITLE
storage: handle under-full stores in rebalancer

### PR DESCRIPTION
**Pull request by cuongdo**
Note: this will _not_ be merged until we've resolved the current 3->5 rebalancer test failure.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9415)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/balancer.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-KRjiM_rN2Fh6xYST2qT:-KRjiM_rN2Fh6xYST2qU:bo7slhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c66840cf73b7de4f562b9af6fa26b59a2b9e480/storage/balancer.go#L155)):*
> ```Go
> 	// Are there any stores with a range count below mean*(1-rebalanceThreshold)?
> 	underfullThreshold := int32(math.Floor(sl.candidateCount.mean * (1 - rebalanceThreshold)))
> 	underfullStore := false
> ```

Slightly more idiomatic is to do `var underfullStore bool`.

---

*[storage/balancer.go, line 174 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-KRjiT9YEffAD-dH-TLC:-KRjiT9YEffAD-dH-TLD:b-pu9ryi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c66840cf73b7de4f562b9af6fa26b59a2b9e480/storage/balancer.go#L174)):*
> ```Go
> 	shouldRebalance := store.Capacity.FractionUsed() >= maxFractionUsedThreshold ||
> 		store.Capacity.RangeCount > target ||
> 		(float64(store.Capacity.RangeCount) > sl.candidateCount.mean && underfullStore)
> ```

Placing this in a single expression is a bit unwieldy. Perhaps we can break this up into separate functions:

```
shouldRebalance :=
  rcb.isOverfullCapacity() ||
  rcb.isOverfullRangeCount() ||
  rcb.isUnderfullRangeCount()
```

Ok, my naming on the last one could use some work, but you get the idea. Perhaps not for this PR, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-:-KRjj5PsZBj66j9kSZO-:bnfp4nl)*

**Comment by tamird** [comment]
in first commit: "disable quiescence" seems to be a lie

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/balancer.go, line 174 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-KRjiT9YEffAD-dH-TLC:-KRjnyTSVxC-mC6JPSPE:bb5camg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c66840cf73b7de4f562b9af6fa26b59a2b9e480/storage/balancer.go#L174)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Placing this in a single expression is a bit unwieldy. Perhaps we can break this up into separate functions:
> 
> ```
> shouldRebalance :=
>   rcb.isOverfullCapacity() ||
>   rcb.isOverfullRangeCount() ||
>   rcb.isUnderfullRangeCount()
> ```
> 
> Ok, my naming on the last one could use some work, but you get the idea. Perhaps not for this PR, though.
</details>
+1, though I don't think functions are necessary - a few local variables would greatly improve readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-:-KRjnahVVw4KFA7QaXqT:byz63sq)*

**Comment by cuongdo** [comment]
fixed commit message

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/balancer.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-KRjiM_rN2Fh6xYST2qT:-KRn-DWEdN7dqfgEaPUh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c66840cf73b7de4f562b9af6fa26b59a2b9e480/storage/balancer.go#L155)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Slightly more idiomatic is to do `var underfullStore bool`.
</details>
Done.

---

*[storage/balancer.go, line 174 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-KRjiT9YEffAD-dH-TLC:-KRn8HffO6BuHbxLBzZT:bmpcbtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c66840cf73b7de4f562b9af6fa26b59a2b9e480/storage/balancer.go#L174)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1, though I don't think functions are necessary - a few local variables would greatly improve readability.
</details>
Good suggestion. I've added local variables, and it looks cleaner to my eyes. I did agonize a bit over the variable names; that was the hardest part. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-:-KRn8GQ-MBxOZA2xIo6p:b-g2g3e9)*

**Comment by petermattis** [comment]
:lgtm: I think this is worth merging this PR even with the 3->5 rebalance testing broken. That brokenness appears to be independent of the allocator heuristics. 

---

Reviewed 2 of 2 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/balancer.go, line 175 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-KRn9_FhK8Fw8ve9dObx:-KRn9_FhK8Fw8ve9dOby:bn1jt2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a10ed9cf46214ba67ef32a243a787a6e2ede1f/storage/balancer.go#L175)):*
> ```Go
> 	}
> 	rebalanceToUnderfullStore :=
> 		(float64(store.Capacity.RangeCount) > sl.candidateCount.mean && underfullTargetExists)
> ```

You could avoid calculating `underfullTargetExists` with a little code refactor:

```
var rebalanceToUnderfullStore bool
if float64(store.Capacity.RangeCount) > sl.candidateCount.mean {
	underfullThreshold := int32(math.Floor(sl.candidateCount.mean * (1 - rebalanceThreshold)))
	for _, desc := range sl.stores {
		if desc.Capacity.RangeCount < underfullThreshold {
			rebalanceToUnderfullStore = true
			break
		}
	}
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9415#-:-KRnA0rfhbEJCiEg-kkY:b-ibg6a4)*

**Pull request merged**
