### PR TITLE
roachprod: more ssh{,d} logging

### PR DESCRIPTION
**Pull request by tbg**
Stash the verbose debug logs in a file for each remote ssh session, and
surface it with the error should one occur. Crank up the server verbosity.

For the latest in many past incidents where this would've been useful, see:

https://github.com/cockroachdb/cockroach/issues/36720#issuecomment-491527390

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-LelE_UfEGPZyZnFhsp3:-LelE_Ug2rcnjwhyEUUu:bxs54ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/28079309e470c5a278101fbe31e9bc3a64b92616/pkg/cmd/roachprod/install/cluster_synced.go#L147)):*
> ```Go
> 		return newLocalSession(), nil
> 	}
> 	host := c.host(i)
> ```

nit: why?
___
*[pkg/cmd/roachprod/install/session.go, line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-LelF6s05u_CYUqJHV57:-LelF6s05u_CYUqJHV58:bqe7xpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b5d27c0304951c2d73ebe8ed48662b68154db9/pkg/cmd/roachprod/install/session.go#L53)):*
> ```Go
> 
> func newRemoteSession(user, host string) (*remoteSession, error) {
> 	logfile := filepath.Join(os.TempDir(), fmt.Sprintf("ssh_%s_%s", host, time.Now().Format(time.RFC3339)))
> ```

My only concern is that we never clear this. If there's a long-running test or user of roachprod that ends up creating these sessions in a loop then we'll potentially fill up `/tmp` with these files which can have unintended consequences. Can we delete the log files after we read them? Maybe also in `Close()`?
___
*[pkg/cmd/roachprod/install/session.go, line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-LelGBwK7MUnFkzZp0wf:-LelGBwK7MUnFkzZp0wg:brws19h) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b5d27c0304951c2d73ebe8ed48662b68154db9/pkg/cmd/roachprod/install/session.go#L53)):*
> ```
> time.Now
> ```
timeutil.Now
___
*[pkg/cmd/roachprod/install/session.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-LelFdji4BFzqWN-ic7k:-LelFdji4BFzqWN-ic7l:beo3jj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b5d27c0304951c2d73ebe8ed48662b68154db9/pkg/cmd/roachprod/install/session.go#L80)):*
> ```Go
> 		err = errors.Wrapf(err, "ssh verbose log:\n%s\n%s", s.Cmd.Args, debug)
> 	}
> 	return err
> ```

Can we delete the log file here so it doesn't leak?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/cmd/roachprod/install/session.go, line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-LelGBwK7MUnFkzZp0wf:-LemM6AvACgGT_EFM7hV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b5d27c0304951c2d73ebe8ed48662b68154db9/pkg/cmd/roachprod/install/session.go#L53)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> time.Now
> ```
timeutil.Now
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/install/session.go, line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-LelF6s05u_CYUqJHV57:-LemM6PBBAxMHGPllCeF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b5d27c0304951c2d73ebe8ed48662b68154db9/pkg/cmd/roachprod/install/session.go#L53)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My only concern is that we never clear this. If there's a long-running test or user of roachprod that ends up creating these sessions in a loop then we'll potentially fill up `/tmp` with these files which can have unintended consequences. Can we delete the log files after we read them? Maybe also in `Close()`?
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/install/session.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-LelFdji4BFzqWN-ic7k:-LemM6uZE0PXjQLn2xq3:b-w8rshe) ([raw file](https://github.com/cockroachdb/cockroach/blob/60b5d27c0304951c2d73ebe8ed48662b68154db9/pkg/cmd/roachprod/install/session.go#L80)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we delete the log file here so it doesn't leak?
</blockquote></details>

Done. (in `Close()`)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-:-LemN8rT1k5O0wm68f1_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by tbg — COMMENTED** [review]
bors r=ajwerner

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37483#-:-LemS7ws5GXgTf-74xCi:bclwjo8)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
