### PR TITLE
distsql: add stats collection to hashJoiner

### PR DESCRIPTION
**Pull request by asubiotto**
Release note: None

Simple screenshot:
screen shot 2018-06-04 at 11 03 10 am

You can also see the filtering on the above screenshot. 

More complicated screenshot:
screen shot 2018-06-04 at 11 08 48 am

Weird thing above is that we somehow decided to store the left side although I thought the default if no short stream is found is to store the right side. I'll look into this. The memory used is accurate, but it's kind of weird that the disk usage was also 64MB, I want to verify this.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:metal: 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-LEAXyi33-KOk7MzJs-D:-LEAXyi33-KOk7MzJs-E:b-swgwm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/589e4f7bcc7d38cb5b34722695262801b549207e/pkg/sql/distsqlrun/hashjoiner.go#L176)):*
> ```Go
> 
> 	pushTrailingMeta := func(ctx context.Context) {
> 		// TODO(asubiotto): Once hashJoiner implements RowSource, set
> ```

Rather than have h.outputStatsToTrace check whether the upstreams are stat collectors, can't we just make a different pushTrailingMeta func up front depending on whether or not we're tracing?

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-LEAXTo4Dt4VW4vuN6r8:-LEAXTo4Dt4VW4vuN6r9:b-63yki6) ([raw file](https://github.com/cockroachdb/cockroach/blob/589e4f7bcc7d38cb5b34722695262801b549207e/pkg/sql/distsqlrun/hashjoiner.go#L199)):*
> ```Go
> 	// If the trace is recording, instrument the hashJoiner to collect stats.
> 	if sp := opentracing.SpanFromContext(ctx); sp != nil && tracing.IsRecording(sp) {
> 		h.leftSource = NewInputStatCollector(h.leftSource)
> ```

Hmm. Shouldn't/couldn't this be done in flow setup?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-:-LEAY6Pq0emXxYyAAWLa:biz8bg8)*

**Comment by asubiotto** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-LEAXyi33-KOk7MzJs-D:-LEB-XN-2Ulhzpp53OTP:b-shjvnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/589e4f7bcc7d38cb5b34722695262801b549207e/pkg/sql/distsqlrun/hashjoiner.go#L176)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Rather than have h.outputStatsToTrace check whether the upstreams are stat collectors, can't we just make a different pushTrailingMeta func up front depending on whether or not we're tracing?
</blockquote></details>

In general, I want to keep the check in `h.outputStatsToTrace` for safety instead of providing a definition of when the method can and cannot be called. I maybe should rename it to `outputStatsToTraceMaybe`. With regards to implementing a different `pushTrailingMeta` func depending on our state, it's definitely a valid point but I see no benefit. We should probably have `pushTrailingMeta` be a method on the `hashJoiner` anyway since the functionality is used at the end of `probePhase` on a clean exit. This ugliness will go away when we switch over the `hashJoiner` to be a `RowSource` (it will just be able to use `finishTrace`).

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-LEAXTo4Dt4VW4vuN6r8:-LEB2KGw5JwH4U5zA9p0:bqxres5) ([raw file](https://github.com/cockroachdb/cockroach/blob/589e4f7bcc7d38cb5b34722695262801b549207e/pkg/sql/distsqlrun/hashjoiner.go#L199)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm. Shouldn't/couldn't this be done in flow setup?
</blockquote></details>

It could be, but some processors cannot take advantage of this functionality because they create their own inputs they still want to collect stats from (e.g. `TableReader` or `JoinReader`). If we did do this, we'd have two ways to instrument processors to collect stats which could lead to some confusion. I prefer to keep it this way.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26359)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-LEAXyi33-KOk7MzJs-D:-LEB3RS39_fi3SZV_CsQ:bfchlge) ([raw file](https://github.com/cockroachdb/cockroach/blob/589e4f7bcc7d38cb5b34722695262801b549207e/pkg/sql/distsqlrun/hashjoiner.go#L176)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

In general, I want to keep the check in `h.outputStatsToTrace` for safety instead of providing a definition of when the method can and cannot be called. I maybe should rename it to `outputStatsToTraceMaybe`. With regards to implementing a different `pushTrailingMeta` func depending on our state, it's definitely a valid point but I see no benefit. We should probably have `pushTrailingMeta` be a method on the `hashJoiner` anyway since the functionality is used at the end of `probePhase` on a clean exit. This ugliness will go away when we switch over the `hashJoiner` to be a `RowSource` (it will just be able to use `finishTrace`).
</blockquote></details>

OK, seems fair enough.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-LEAXTo4Dt4VW4vuN6r8:-LEB617v7_gNgUli7DuO:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/589e4f7bcc7d38cb5b34722695262801b549207e/pkg/sql/distsqlrun/hashjoiner.go#L199)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It could be, but some processors cannot take advantage of this functionality because they create their own inputs they still want to collect stats from (e.g. `TableReader` or `JoinReader`). If we did do this, we'd have two ways to instrument processors to collect stats which could lead to some confusion. I prefer to keep it this way.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-:-LEB69BT8XHA_Peo8iMV:bnfp4nl)*

**Comment by RaduBerinde** [comment]
This is really cool!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26359#-:-LEB7TDX8gZmtviYQaP5:b-8capno)*

**Comment by asubiotto** [comment]
Thanks!

bors r+

Will submit a follow-up PR for the `outputStatsToTrace` and `pushTrailingMeta` changes

**Pull request merged**
