### PR TITLE
roachtest: add disk-full roachtest

### LINKED ISSUE #25173: storage: tocommit(%d) is out of range [lastIndex(%d)]. Was the raft log corrupted, truncated, or lost?
https://sentry.io/cockroach-labs/cockroachdb/issues/415952086/

```
*log.safeError: stopper.go:175: string
  File "github.com/cockroachdb/cockroach/pkg/storage/raft.go", line 106, in Panicf
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3335, in func1
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 607, in withRaftGroupLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 624, in withRaftGroup
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3330, in stepRaftGroup
...
(14 additional frame(s) were not displayed)

stopper.go:175: string
```

### LINKED ISSUE #32631: storage/engine: investigate data loss with FlushWAL
https://github.com/cockroachdb/cockroach/pull/32605 reverted usage of FlushWAL (we're back to using the slightly slower SyncWAL) due to a privately reported test that experienced data corruption when a disk is filled up and then some space is freed. We need to replicate this scenario with a roachtest and then track down the source of the data loss. The symptoms of the data loss are Raft log corruption:

`panic: tocommit(1286) is out of range [lastIndex(1277)]. Was the raft log corrupted, truncated, or lost? [recovered]`

### PR DESCRIPTION
**Pull request by petermattis**
RocksDB was missing some error checks on the code paths involved in `FlushWAL`. The result was that writes that failed when the disk is full were erroneously being considered success. 

Fixes #32631
Fixes #25173

Release note (performance improvement): Re-enable usage of RocksDB FlushWAL which is a minor performance improvement for synchronous RocksDB write operations.

### CODE REVIEW

**Comment by petermattis** [comment]
The test now reliably reproduces the Raft log corruption. Time to figure out what is going on with FlushWAL.

**Comment by petermattis** [comment]
This is ready for a look. Note that I'm claiming this fixes #25173 as the occurrences we've seen there all seem to be after we started using `FlushWAL`.

**Comment by petermattis** [comment]
Hold off on the review. I'm running the test in a loop and just hit another crash. Really hoping this is user error.

**Comment by petermattis** [comment]
After updating the RocksDB cherry-picks this looks good to go (for realz this time). I'm still running the `disk-full` roachtest in a loop, but it has now passed 12 times in a row while previously it would fail about 1 of 3 runs.

**Comment by petermattis** [comment]
> I'm still running the disk-full roachtest in a loop.

Still running in a loop, though now I'm up over 50 successful runs. I'm very confident that the swallowing of the error in `DB::FlushWAL` was the problem.

**Review by bdarnell — APPROVED** [review]

**Comment by petermattis** [comment]
bors r=bdarnell

**Review by tbg — APPROVED** [review]
LGTM

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32674#-:-LSaBqam4A6Tsbmx6sr0:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/disk_full.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32674#-LSaBitFCRg0xcDajlUJ:-LSaBitG89XEXf55yTbD:b-fg7agi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd71838afded2238587e7a9383d048b5593d4a86/pkg/cmd/roachtest/disk_full.go#L61)):*
> ```Go
> 				// command to exit with an error. The "|| true" is used to ignore that
> 				// error.
> 				c.Run(ctx, c.Node(n), "./cockroach debug ballast {store-dir}/ballast --size=100% || true")
> ```

nit: this seems a little dirty, can't you do something like `./cockroach debug ballast --size=-10mb`? Though I guess that can also fail with an error.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32674)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/disk_full.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32674#-LSaBitFCRg0xcDajlUJ:-LSaNcDc1HY6mGT7wFg_:b6ob6f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd71838afded2238587e7a9383d048b5593d4a86/pkg/cmd/roachtest/disk_full.go#L61)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: this seems a little dirty, can't you do something like `./cockroach debug ballast --size=-10mb`? Though I guess that can also fail with an error.
</blockquote></details>

I originally used `--size=99%`, but frequently saw the ballast command failing due to running out of disk space. The `|| true` is dirty, but foolproof.

**Pull request merged**
