### PR TITLE
bazel: use nogo to run analysis during builds

### LINKED ISSUE #65517: bazel: `TestLint/TestRoachVet` broken when run in Bazel
Error output looks like this:

```
        /usr/bin/ld: $WORK/b1125/_x002.o: in function `_cgo_4e1d0d71c6d3_Cfunc_el_line':
        /tmp/go-build/cgo-gcc-prolog:249: undefined reference to `el_line'
        /usr/bin/ld: $WORK/b1125/_x002.o: in function `_cgo_4e1d0d71c6d3_Cfunc_el_wline':
        /tmp/go-build/cgo-gcc-prolog:279: undefined reference to `el_wline'
        /usr/bin/ld: $WORK/b1125/_x002.o: in function `_cgo_4e1d0d71c6d3_Cfunc_el_reset':
        /tmp/go-build/cgo-gcc-prolog:264: undefined reference to `el_reset'
        /usr/bin/ld: $WORK/b1125/_x002.o: in function `_cgo_4e1d0d71c6d3_Cfunc_history_end':
        /tmp/go-build/cgo-gcc-prolog:514: undefined reference to `history_end'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `cont_handler':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:406: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:409: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `_el_bracketed_paste':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:109: undefined reference to `el_wgetc'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:116: undefined reference to `el_winsertstr'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:118: undefined reference to `el_get'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `winch_handler':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:386: undefined reference to `el_resize'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `readwrite_history':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:289: undefined reference to `history'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_get_clientdata':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:48: undefined reference to `el_get'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `_el_rl_complete':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:360: undefined reference to `fn_complete'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_rebind_ctrls':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:160: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:163: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:166: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:169: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:173: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o:/cockroach/vendor/github.com/knz/go-libedit/unix/c_editline.c:176: more undefined references to `el_set' follow
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_init':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:199: undefined reference to `el_init'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:218: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:219: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:223: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:228: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:229: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o:/cockroach/vendor/github.com/knz/go-libedit/unix/c_editline.c:230: more undefined references to `el_set' follow
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_init':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:256: undefined reference to `el_source'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:249: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:252: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:213: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_setup_history':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:269: undefined reference to `history_init'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:274: undefined reference to `history'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:275: undefined reference to `history'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:277: undefined reference to `history'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:277: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_gets':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:423: undefined reference to `el_get'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:447: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:448: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:449: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:450: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:451: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o:/cockroach/vendor/github.com/knz/go-libedit/unix/c_editline.c:452: more undefined references to `el_set' follow
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_gets':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:453: undefined reference to `el_reset'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:469: undefined reference to `el_gets'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:492: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:493: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:494: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:495: undefined reference to `el_set'
        /usr/bin/ld: vendor/github.com/knz/go-libedit/unix/c_editline.c:496: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o:/cockroach/vendor/github.com/knz/go-libedit/unix/c_editline.c:497: more undefined references to `el_set' follow
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_gets':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:467: undefined reference to `el_wgets'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `cont_handler':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:411: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `winch_handler':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:394: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_set_clientdata':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:58: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_rebind_ctrls':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:179: undefined reference to `el_set'
        /usr/bin/ld: $WORK/b1125/_x005.o: in function `go_libedit_close':
        vendor/github.com/knz/go-libedit/unix/c_editline.c:505: undefined reference to `el_end'
        collect2: error: ld returned 1 exit status
        sql-gen.y:90: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10302: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10306: cannot use tree.UnarySqrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10310: cannot use tree.UnaryCbrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10679: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:90: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10302: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10306: cannot use tree.UnarySqrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10310: cannot use tree.UnaryCbrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10679: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:90: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10302: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10306: cannot use tree.UnarySqrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10310: cannot use tree.UnaryCbrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10679: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:90: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10302: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10306: cannot use tree.UnarySqrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10310: cannot use tree.UnaryCbrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10679: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:90: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10302: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10306: cannot use tree.UnarySqrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10310: cannot use tree.UnaryCbrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10679: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:90: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10302: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10306: cannot use tree.UnarySqrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10310: cannot use tree.UnaryCbrt (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
        sql-gen.y:10679: cannot use tree.UnaryComplement (type tree.UnaryOperatorSymbol) as type tree.UnaryOperator in field value
```

Epic CRDB-8306

### PR DESCRIPTION
**Pull request by rickystewart**
We run all the checks that `go vet` and `roachvet` run *during* the
build using [`nogo`](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst).
This means we don't have to run `roachvet` during lints.

Moving forward we can also use `nogo` for `staticcheck` and other
complicated checks, giving us a path forward to solve #68496 and #68498.

Closes #65517.

Release note: None

### CODE REVIEW

**Review by rail — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73070)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[BUILD.bazel, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73070#-MpHohWl0r712VQaUkPv:-MpHohWl0r712VQaUkPw:b-qwloq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f136653847893c3f3d1e0354fabe889ac89eec5/BUILD.bazel#L224)):*
> ```Starlark
>         # TODO(ricky): we do want to run the shadow check, we just want to exclude
>         # shadows of the variable "err". Presumably we can hack around this. #73069
>         # "@org_golang_x_tools//go/analysis/passes/shadow:go_default_library",
> ```

Why do we disable this check? Looks like it's used as is in `roachvet`.
___
*[build/bazelutil/nogo_config.json, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73070#-MpHNfET0GKc-vr8acVp:-MpHNfET0GKc-vr8acVq:by9cypt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f136653847893c3f3d1e0354fabe889ac89eec5/build/bazelutil/nogo_config.json#L114)):*
> ```JSON
>     },
>     "testinggoroutine": {
> 	"only_files": {
> ```

nit: mix of tabs and spaces.
___
*[build/bazelutil/nogo_config.json, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73070#-MpHNlvE2zsuuOv741KG:-MpHNlvE2zsuuOv741KH:by9cypt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f136653847893c3f3d1e0354fabe889ac89eec5/build/bazelutil/nogo_config.json#L117)):*
> ```JSON
>             "github.com/cockroachdb/cockroach/.*$": "first-party code"
>         },
> 	"exclude_files": {
> ```

nit: mix of tabs and spaces.
___
*[pkg/sql/logictest/logic.go, line 2564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73070#-MpHq1E96qttuN1m5fmR:-MpHq1E96qttuN1m5fmS:blkn9dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bbcc172a0217fade67458bc6bf24bf96c6ba714/pkg/sql/logictest/logic.go#L2564)):*
> ```Go
> 		errString := pgerror.FullError(err)
> 		newErr := errors.Errorf("%s: %s\nexpected:\n%s\n\ngot:\n%s", pos, sql, expectErr, errString)
> 		if err != nil && strings.Contains(errString, expectErr) {
> ```

Good catch, there is already a `if err == nil` check a few lines above., this one is redundant.
___
*[pkg/sql/logictest/logic.go, line 2575 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73070#-MpHqQZCAEXB8Fj5mHs8:-MpHqQZCAEXB8Fj5mHs9:b-1z74x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bbcc172a0217fade67458bc6bf24bf96c6ba714/pkg/sql/logictest/logic.go#L2575)):*
> ```Go
> 			t.t().Logf("Error regexp: %s\n", r)
> 		}
> 		return (err == nil) == (expectErr == ""), newErr
> ```

Hmmmm. `err` is always not `nil` here (because there is an early return otherwise above).
Therefore `err == nil` is always `false`. 
`false == (expectErr == "")` -> `expectErr != ""` I think?

**Comment by rickystewart** [comment]
> Why do we disable this check? Looks like it's used as is in `roachvet`.

Yeah, we can't enable it because it triggers a lot of spurious errors. We shadow the name `err` in many places. `roachvet` does report these as errors, but those errors get [filtered out](https://github.com/cockroachdb/cockroach/blob/0331536f74eb8a2bf5b2ce20466c9786e37c1ac9/pkg/testutils/lint/lint_test.go#L2137) so they don't get reported as lint errors. #73069 is the tracking issue for this -- we just need to add our own `Analyzer` that does exactly what `shadow` does but filters out `err` shadows.

> Hmmmm. `err` is always not `nil` here (because there is an early return otherwise above).
> Therefore `err == nil` is always `false`.
> `false == (expectErr == "")` -> `expectErr != ""` I think?

Good catch :) Fixed.

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73070#-:-MpI-q5mAjymaE6mSdK5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
