### PR TITLE
sql/sqlbase: add RandCreateTables to make FK-aware tables

### PR DESCRIPTION
**Pull request by madelynnblue**
RandCreateTables creates a specified number of random tables. Foreign key
references are sometimes created on random columns between various tables.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42205)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @mjibson)

___
*[pkg/sql/sqlbase/testutils.go, line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42205#-Lt1IJL86GjOAAUrJZCx:-Lt1IJL86GjOAAUrJZCy:blmbghy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02540672f0ffc520e87fb8325ee83319cb7b81c/pkg/sql/sqlbase/testutils.go#L715)):*
> ```Go
> 
> // RandCreateTables creates random table definitions. They may contain foreign
> // key references to each other.
> ```

Do we need a setting controlling the fkiness? I guess not for now, but seems like not all situations would want foreign keys between tables due to the insert problem you mentioned?
___
*[pkg/sql/sqlbase/testutils.go, line 770 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42205#-Lt2uYbK1z1lniaheIiW:-Lt2uYbK1z1lniaheIiX:bya05mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02540672f0ffc520e87fb8325ee83319cb7b81c/pkg/sql/sqlbase/testutils.go#L770)):*
> ```Go
> 		// Pick some randomly short prefix. I'm sure there's a closed
> 		// form solution to this with a single call to rng.Intn but I'm
> 		// not sure what to search for.
> ```

Could you just take rng.Intn(n cols) or is that not the desired result?
___
*[pkg/sql/sqlbase/testutils.go, line 783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42205#-Lt2wATw21ooLOaKb6Ri:-Lt2wATw21ooLOaKb6Rj:bemc1hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02540672f0ffc520e87fb8325ee83319cb7b81c/pkg/sql/sqlbase/testutils.go#L783)):*
> ```Go
> 			// TODO(mjibson): Circular references are not
> 			// prevented, but it would be nice to detect and
> 			// prevent them.
> ```

I think circular FK references are an okay thing to generate. They don't work in CRDB today but they will once optimizer-driven foreign keys are enabled.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42205)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/sqlbase/testutils.go, line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42205#-Lt1IJL86GjOAAUrJZCx:-Lt3AySh1zdqoZvh2D7L:bch7y3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02540672f0ffc520e87fb8325ee83319cb7b81c/pkg/sql/sqlbase/testutils.go#L715)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do we need a setting controlling the fkiness? I guess not for now, but seems like not all situations would want foreign keys between tables due to the insert problem you mentioned?
</blockquote></details>

Yes. This is soon going to go into the new mutations package which will make it configurable. I think it's fine to not worry about it in this PR.
___
*[pkg/sql/sqlbase/testutils.go, line 770 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42205#-Lt2uYbK1z1lniaheIiW:-Lt3BHha4kBA-7JMgL4y:b-1ldny0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02540672f0ffc520e87fb8325ee83319cb7b81c/pkg/sql/sqlbase/testutils.go#L770)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Could you just take rng.Intn(n cols) or is that not the desired result?
</blockquote></details>

This for loop weights increasingly toward low numbers. 1 has 50% change, 2 25%, 3 12.5%, etc. Using .Intn lets all lengths have equal probability. With a high number of columns it becomes increasingly difficult to to find a table that has all of the same types. So I think this method actually achieves FKs more of the time, but still sometimes produces long ones. I use this kind of random falloff all over sqlsmith and it's been working pretty good so far.
___
*[pkg/sql/sqlbase/testutils.go, line 783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42205#-Lt2wATw21ooLOaKb6Ri:-Lt3Bn9m35-aI2LLg4TH:bk2gac7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02540672f0ffc520e87fb8325ee83319cb7b81c/pkg/sql/sqlbase/testutils.go#L783)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think circular FK references are an okay thing to generate. They don't work in CRDB today but they will once optimizer-driven foreign keys are enabled.
</blockquote></details>

If you have a circular FK then you can't insert data into that table unless it already has like a seed row. Self references and circular references can make it impossible to have a valid INSERT since there's no way to have a row that satisfies the FK. Although we don't yet prevent circular, preventing self references is just a way to try to prevent a bit of that problem.

**Pull request merged**
