### PR TITLE
kv: use AmbientContext in dist_sender

### PR DESCRIPTION
**Pull request by RaduBerinde**
@tamird @andreimatei @tschottdorf commit 2 will make you happy.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10269)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: :tada:

---

Reviewed 6 of 6 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/kv/dist_sender.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6fy4WOkDU9qZBEFKY:-KV6fy4WOkDU9qZBEFKZ:bjo3h6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ddb0f17b08a18dee8b1b7dc31c163907217667/pkg/kv/dist_sender.go#L143)):*
> ```Go
> // defaults will be used.
> func NewDistSender(cfg *DistSenderConfig, g *gossip.Gossip) *DistSender {
> 	if cfg == nil {
> ```

NYC but yuck :(

---

*[pkg/kv/dist_sender.go, line 170 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6g4XWjgaKi-WBAHHQ:-KV6g4XWjgaKi-WBAHHR:b-mv1doj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ddb0f17b08a18dee8b1b7dc31c163907217667/pkg/kv/dist_sender.go#L170)):*
> ```Go
> 		rdb = ds
> 	}
> 	ds.rangeCache = newRangeDescriptorCache(ds.AnnotateCtx(context.Background()), rdb, int(rcSize))
> ```

this should be TODO, right? I'm imagining that it's going to be replace with an ambient.

---

*[pkg/kv/dist_sender.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6gA6DpdAPWr7M7LvC:-KV6gA6DpdAPWr7M7LvD:b-hyx4kx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ddb0f17b08a18dee8b1b7dc31c163907217667/pkg/kv/dist_sender.go#L213)):*
> ```Go
> 					} else {
> 						log.Infof(ctx,
> 							"gossiped first range descriptor: %+v", desc.Replicas)
> ```

I think you can put this on one line now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-:-KV6gxOUNzDeMSHZili-:bck4n45)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/kv/dist_sender.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6fy4WOkDU9qZBEFKY:-KV6hjeeG9EP6DLhPJ5R:b-p1cny1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ddb0f17b08a18dee8b1b7dc31c163907217667/pkg/kv/dist_sender.go#L143)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> NYC but yuck :(
</details>
Removed. Fixed the one caller that passed nil.

---

*[pkg/kv/dist_sender.go, line 170 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6g4XWjgaKi-WBAHHQ:-KV6htI5-BfFj1WEauVi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ddb0f17b08a18dee8b1b7dc31c163907217667/pkg/kv/dist_sender.go#L170)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this should be TODO, right? I'm imagining that it's going to be replace with an ambient.
</details>
Done.

---

*[pkg/kv/dist_sender.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6gA6DpdAPWr7M7LvC:-KV6i0Rc6AJN7PohUQa0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ddb0f17b08a18dee8b1b7dc31c163907217667/pkg/kv/dist_sender.go#L213)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I think you can put this on one line now
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269)*

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r3, 6 of 6 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/kv/dist_sender.go, line 142 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6kiiMHLmeCbJjJS_X:-KV6kiiMHLmeCbJjJS_Y:br5tu2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8796be7a0fba79f02872d335f713c732b6819d29/pkg/kv/dist_sender.go#L142)):*
> ```Go
> // DistSenderContext or the fields within is optional. For omitted values, sane
> // defaults will be used.
> func NewDistSender(cfg *DistSenderConfig, g *gossip.Gossip) *DistSender {
> ```

*optional*: make this a value since nobody's passing nil and it's not mutated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269)*

**Comment by RaduBerinde** [comment]
Review status: 8 of 17 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/dist_sender.go, line 142 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-KV6kiiMHLmeCbJjJS_X:-KV6qX93a2uwrdIf1c4I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8796be7a0fba79f02872d335f713c732b6819d29/pkg/kv/dist_sender.go#L142)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> *optional*: make this a value since nobody's passing nil and it's not mutated.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269)*

**Comment by andreimatei** [comment]
Nice!

---

Review status: 8 of 17 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10269#-:-KV77AZ1p-zIVTTBE75N:b-83sjoh)*

**Comment by RaduBerinde** [comment]
Part of #9807.

**Pull request merged**
