### PR TITLE
opt: calculate filter cost more accurately when spatial functions involved

### LINKED ISSUE #59718: opt: cost of filters is incorrect when expensive function is not top-level operator
Consider the following example:
```
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;

CREATE TABLE tab (
	id INT PRIMARY KEY,
	b BOOL,
	geog GEOGRAPHY
);

ALTER TABLE tab INJECT STATISTICS '[
    {
        "columns": [
            "id"
        ],
        "created_at": "2021-01-01 00:00:00",
        "distinct_count": 500000,
        "name": "__auto__",
        "row_count": 500000
    }
]';

EXPLAIN (OPT, VERBOSE) SELECT id FROM tab
WHERE st_dwithin(geog, st_makepoint(1.0, 1.0)::geography, 200);
                                                                         info
-------------------------------------------------------------------------------------------------------------------------------------------------------
  project
   ├── columns: id:1
   ├── immutable
   ├── stats: [rows=55000]
   ├── cost: 1055554.05
   ├── key: (1)
   ├── prune: (1)
   └── select
        ├── columns: id:1 geog:3
        ├── immutable
        ├── stats: [rows=55000, distinct(3)=50000, null(3)=0]
        ├── cost: 1055004.04
        ├── key: (1)
        ├── fd: (1)-->(3)
        ├── scan tab
        │    ├── columns: id:1 geog:3
        │    ├── stats: [rows=500000, distinct(1)=500000, null(1)=0, distinct(3)=50000, null(3)=5000]
        │    ├── cost: 550004.02
        │    ├── key: (1)
        │    ├── fd: (1)-->(3)
        │    └── prune: (1,3)
        └── filters
             └── st_dwithin(geog:3, '0101000020E6100000000000000000F03F000000000000F03F', 200.0) [outer=(3), immutable, constraints=(/3: (/NULL - ])]
(23 rows)

EXPLAIN (OPT, VERBOSE) SELECT id FROM tab
WHERE st_dwithin(geog, st_makepoint(1.0, 1.0)::geography, 200) = b;
                                                                             info
---------------------------------------------------------------------------------------------------------------------------------------------------------------
  project
   ├── columns: id:1
   ├── immutable
   ├── stats: [rows=165000]
   ├── cost: 566654.05
   ├── key: (1)
   ├── prune: (1)
   └── select
        ├── columns: id:1 b:2 geog:3
        ├── immutable
        ├── stats: [rows=165000, distinct(2)=3, null(2)=0]
        ├── cost: 565004.04
        ├── key: (1)
        ├── fd: (1)-->(2,3)
        ├── scan tab
        │    ├── columns: id:1 b:2 geog:3
        │    ├── stats: [rows=500000, distinct(1)=500000, null(1)=0, distinct(2)=3, null(2)=5000]
        │    ├── cost: 560004.02
        │    ├── key: (1)
        │    ├── fd: (1)-->(2,3)
        │    └── prune: (1-3)
        └── filters
             └── b:2 = st_dwithin(geog:3, '0101000020E6100000000000000000F03F000000000000F03F', 200.0) [outer=(2,3), immutable, constraints=(/2: (/NULL - ])]
(23 rows)
```
Notice that the second query is significantly less expensive than the first (about 2x difference). This is because the optimizer thinks that `st_dwithin(...)` is a much more expensive filter than `st_dwithin(...) = b`. However, they should really be treated exactly the same. The problem is that the optimizer doesn't recurse into the filter expression to find expensive functions. We should update the coster to perform this recursion. 

Jira issue: CRDB-3246

### PR DESCRIPTION
**Pull request by linaqiu22**
Fixes #59718

Release note (performance improvement): the optimizer's cost model is now more
aware of the cost of executing expensive functions (such as spatial functions)
in filter conditions. This may lead to improved query plans.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice work! Just a couple of comments below.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-:-N31OfdoAoYGqPdPxtzC:b-ugo8yt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @linaqiu22)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N31H9gK0SYV4RayE7ZV):*
nit: there is a small user facing change here, since this could cause some query plans to change. I'd say something like:
```
Release note (performance improvement): the optimizer's cost model is now more
aware of the cost of executing expensive functions (such as spatial functions)
in filter conditions. This may lead to improved query plans.
```
___
*[`pkg/sql/opt/xform/coster.go` line 1089 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N31Ih0b73K7FtNXvY5_:-N31Ih0b73K7FtNXvY5a:b-8qo0h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e8d9f5cbb6199cc1a35f1a4b23bfe79c73e147/pkg/sql/opt/xform/coster.go#L1089)):*
> ```Go
> // computeFunctionExprCost calculates per-row cost of spatial functions. It
> // recursively checks if children are also spatial functions.
> func (c *coster) computeFunctionExprCost(
> ```

I think this should be more general than just `computeFunctionExprCost`. I would call it `computeExprCost` and include the switch statement from `computeFiltersCost` below.
Something like:
```
func (c *coster) computeExprCost(expr opt.Expr) memo.Cost {
	var perRowCost memo.Cost
	switch expr.Op() {
	case opt.EqOp:
		...
	case opt.FunctionOp:
		...
	}

	for i := 0; i < expr.ChildCount(); i++ {
		perRowCost += c.computeExprCost(expr.Child(i))
	}
	return perRowCost
}
```
This will ensure that we recurse into all expressions, not just equality and function expressions. You can check if it's working by adding a test case like `SELECT * FROM g WHERE st_area(geog) < a`
___
*[`pkg/sql/opt/xform/testdata/coster/spatial-filters` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N31OWap4-GtxAJewpW4:-N31OWap4-GtxAJewpW5:b10ca2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e8d9f5cbb6199cc1a35f1a4b23bfe79c73e147/pkg/sql/opt/xform/testdata/coster/spatial-filters#L1)):*
> ```
> exec-ddl
> ```

Nice tests!
___
*[`pkg/sql/opt/xform/testdata/coster/spatial-filters` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N31MnryB_WknPs8S3wU:-N31MnryB_WknPs8S3wV:b-lozorc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e8d9f5cbb6199cc1a35f1a4b23bfe79c73e147/pkg/sql/opt/xform/testdata/coster/spatial-filters#L156)):*
> ```
> opt
> SELECT id FROM g
> WHERE st_distance(geog, st_makepoint(a, 1.0)::geography) < 200;
> ```

Both this test and the one above will trigger a normalization rule that converts `st_distance(...) < 200` to a different function (specifically `st_dwithinexclusive`, which you can see in the plan below). If you want to check that we recurse into both sides of the `<` operator, you might want to use a different function like `st_area` or `st_linecrossingdirection`.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @linaqiu22)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N31H9gK0SYV4RayE7ZV):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: there is a small user facing change here, since this could cause some query plans to change. I'd say something like:
```
Release note (performance improvement): the optimizer's cost model is now more
aware of the cost of executing expensive functions (such as spatial functions)
in filter conditions. This may lead to improved query plans.
```
</blockquote></details>

FYI, in the future you can just write "Done" after addressing a comment in Reviewable, and it will be resolved automatically.
___
*[`pkg/sql/opt/xform/coster.go` line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3Biawx35Li1XPu0oHE:-N3Biawx35Li1XPu0oHF:bod7aev) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa649edc42a0f05aa2fa53890865db959ccbf277/pkg/sql/opt/xform/coster.go#L1136)):*
> ```Go
> 		for i := 0; i < f.Condition.ChildCount(); i++ {
> 			perRowCost += c.computeExprCost(f.Condition.Child(i))
> 		}
> ```

To avoid adding all this logic twice, I would eliminate the `opt.FunctionOp` case, and just call `perRowCost += c.computeExprCost(f.Condition)`. You can also move these comments into the `computeExprCost` function.



_Code quote:_
```Go
		case opt.FunctionOp:
			// We are ok with the zero value here for functions not in the map.
			function := f.Condition.(*memo.FunctionExpr)
			perRowCost += fnCost[function.Name]
		}
		// recurse into the children of the current expression
		for i := 0; i < f.Condition.ChildCount(); i++ {
			perRowCost += c.computeExprCost(f.Condition.Child(i))
		}
```

**Review by linaqiu22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/xform/coster.go` line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3Biawx35Li1XPu0oHE:-N3KYXgc2b5kbwm1me7Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa649edc42a0f05aa2fa53890865db959ccbf277/pkg/sql/opt/xform/coster.go#L1136)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

To avoid adding all this logic twice, I would eliminate the `opt.FunctionOp` case, and just call `perRowCost += c.computeExprCost(f.Condition)`. You can also move these comments into the `computeExprCost` function.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/testdata/coster/spatial-filters` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N31OWap4-GtxAJewpW4:-N3KYa3FE1CGHE1ucvr1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e8d9f5cbb6199cc1a35f1a4b23bfe79c73e147/pkg/sql/opt/xform/testdata/coster/spatial-filters#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Nice tests!
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
Awesome -- code :lgtm_strong: 

You have some test failures, though. You'll need to rewrite the test files using `./dev test pkg/sql/opt/memo --rewrite` and `./dev test pkg/sql/opt/xform --rewrite`. Looks like you also have a lint error:
```
------- Stdout: -------
=== RUN   TestLint/TestCrlfmt
=== PAUSE TestLint/TestCrlfmt
=== CONT  TestLint/TestCrlfmt
=== CONT  TestLint/TestCrlfmt
    lint_test.go:1370:
        diff -u old/sql/opt/xform/coster.go new/sql/opt/xform/coster.go
        --- old/sql/opt/xform/coster.go  2022-05-30 15:42:25.243120211 +0000
        +++ new/sql/opt/xform/coster.go  2022-05-30 15:42:25.243120211 +0000
        @@ -1086,9 +1086,7 @@
         // computeExprCost calculates per-row cost of the expression.
         // It finds every embedded spatial function and add its cost.
        -func (c *coster) computeExprCost(
        -  expr opt.Expr,
        -) memo.Cost {
        +func (c *coster) computeExprCost(expr opt.Expr) memo.Cost {
           perRowCost := memo.Cost(0)
           if expr.Op() == opt.FunctionOp {
             // We are ok with the zero value here for functions not in the map.
    lint_test.go:1385: run the following to fix your formatting:
        bin/crlfmt "-fast" "-ignore" "\\.(pb(\\.gw)?)|(\\.[eo]g)\\.go|/testdata/|^sql/parser/sql\\.go$|_generated(_test)?\\.go$" "-tab" "2" "-w" "/go/src/github.com/cockroachdb/cockroach/pkg"
        Don't forget to add amend the result to the correct commits.
    --- FAIL: TestLint/TestCrlfmt (6.37s)
```

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-:-N3R9wmG0DpeWQs1esWi:b-e3l5zc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @linaqiu22)

**Review by mgartner — APPROVED** [review]
Nice! :lgtm: 

FYI, you can add `Fixes #59718` to the PR description (and/or commit message) which will automatically close the issue once the PR is merged. It also provides helpful bi-directional links between the PR and the issue.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-:-N3UrvXQELbcab9AFmaP:bad71ms)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @linaqiu22)

___
*[`pkg/sql/opt/xform/coster.go` line 1116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3Uqyh0BEc2Jyd4UbyE:-N3Uqyh0BEc2Jyd4UbyF:b-61xqi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f63af21120cd8cf21a67bccda11e6b054ef46b/pkg/sql/opt/xform/coster.go#L1116)):*
> ```Go
> 	for i := range filters {
> 		f := &filters[i]
> 		if f.Condition.Op() == opt.EqOp {
> ```

nit: I think you could move this `if` block into `computeExprCost` like Becca previously suggested.

**Review by rytaft — APPROVED** [review]
:lgtm: 

If the `acceptance` failure doesn't go away, you might need to rebase from `master`

> Reviewed 4 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-:-N3VlO1jEQawmcZYw_c8:bsv2cen)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @linaqiu22)

___
*[`-- commits` line 4 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3WyY3d06IZGgtkruqq):*
You'll need to also add this to the PR message in order for GitHub to auto-close the issue.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 4152 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3WyqvK9-lHStr722Xw:-N3WyqvK9-lHStr722Xx:b-quzx9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e08e3a94e353807460d41298fda38407c7f87db/pkg/sql/opt/xform/testdata/rules/select#L4152)):*
> ```
>            └── st_overlaps('0102000000020000000000000000000000000000000000000000000000000000000000000000000040', geom:3) [outer=(3), immutable, constraints=(/3: (/NULL - ])]
> 
> # Cannot use either index in this case.
> ```

nit: update comment: "We can use both indexes because of the SplitDisjunction rule"

**Review by linaqiu22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 4 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3WyY3d06IZGgtkruqq):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You'll need to also add this to the PR message in order for GitHub to auto-close the issue.
</blockquote></details>

Added.
___
*[`pkg/sql/opt/xform/coster.go` line 1116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3Uqyh0BEc2Jyd4UbyE:-N3X0aP-53OvwWuUAR99:b6rz8l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f63af21120cd8cf21a67bccda11e6b054ef46b/pkg/sql/opt/xform/coster.go#L1116)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It would make it slightly harder to avoid adding the `setupCost`, so I'm guessing that's why she left it...
</blockquote></details>

Yes, moving the EqOp checking to `computeExprCost` will change the `setupCost`, or require repeated checking on `if eqMap.Get(int(leftVar.Col)) == int(rightVar.Col)`

**Review by rytaft — APPROVED** [review]
:lgtm: Please feel free to merge with "bors r+". Nice work!!

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-:-N3acik_DBM398XuvP6p:b-7hroa1)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @linaqiu22)

**Comment by mgartner** [comment]
*[`pkg/sql/opt/xform/coster.go` line 1116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3Uqyh0BEc2Jyd4UbyE:-N3dpxab3AAVOw6GRPbb:b-2bnmi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f63af21120cd8cf21a67bccda11e6b054ef46b/pkg/sql/opt/xform/coster.go#L1116)):*
<details><summary><i>Previously, linaqiu22 wrote…</i></summary><blockquote>

Yes, moving the EqOp checking to `computeExprCost` will change the setupCost, or require repeated checking on `if eqMap.Get(int(leftVar.Col)) == int(rightVar.Col)`
</blockquote></details>

I see. Thanks for the explanation.

I do have questions about this setupCost and eqMap that are unrelated to your PR (so please go ahead and merge), maybe @rytaft has answers: Why is computeHashJoinCost the only function that supplies a non-empty `eqMap` (and therefore the only case where this equality special case is used)? Is it because this is the only join where equality columns are described in the ON filters and not separately?

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 7 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @linaqiu22)

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81924)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @linaqiu22)

___
*[`pkg/sql/opt/xform/coster.go` line 1116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81924#-N3Uqyh0BEc2Jyd4UbyE:-N3dsDbrBdxXk337J92j:b-wcfwk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f63af21120cd8cf21a67bccda11e6b054ef46b/pkg/sql/opt/xform/coster.go#L1116)):*
> Is it because this is the only join where equality columns are described in the ON filters and not separately?

Yep! The equality conditions are already removed from merge and lookup joins

**Pull request merged**
