### PR TITLE
build: parallelize check-style if GNU Parallel is available.

### PR DESCRIPTION
**Pull request by jordanlewis**
Use GNU parallel if it exists, otherwise revert to sequential. This will probably affect dev machines more than build machines since they likely have more cores than the build machines, but it's nice having this script finish a little faster so it's reasonable to put in a local git hook.

Also, add test timings to the output.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8424)

### CODE REVIEW

**Comment by petermattis** [comment]
I achieved a similar affect by rewriting check-style.sh in Go. See https://github.com/cockroachdb/cockroach/compare/master...petermattis:pmattis/check-style?expand=1 (though that branch is very out of date).

**Comment by jordanlewis** [comment]
Cool - for now I've changed this to just use a for-loop unless GNU Parallel is available, which doesn't interleave output.

**Comment by tamird** [comment]
What's the impact on runtime?

**Comment by tamird** [comment]
btw, if someone out there has implemented `parallel` in Go, we can add it to our glockfile :)

**Comment by jordanlewis** [comment]
before: `./build/check-style.sh  198.64s user 32.74s system 244% cpu 1:34.70 total`
after: `./build/check-style.sh  187.46s user 33.18s system 376% cpu 58.611 total`

The lion's share of the time is still the safe sql test, clocking in at 53 seconds.

**Comment by jordanlewis** [comment]
Amended this to output style script timings as well.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
