### PR TITLE
cli: ignore snappy error on failure

### PR DESCRIPTION
**Pull request by otan**
Refs: #42634 

Snappy seems to sometimes not be installed when running CI tests. I
would prefer the CI tests run by default, and report new errors if
found. As such, I am proposing we handle the snappy error as a pass, and
if this continues revisit it again.

Maybe we can get rid of snappy if we get rid of grpc anyway...

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
(emergency PR, ick!)

**Comment by petermattis** [comment]
> Snappy seems to sometimes not be installed when running CI tests

AFAIK, snappy is always installed. There is no way to build without snappy. So the cause of the snappy not available error you're seeing is very likely due to something else. Or my understanding of our build is significantly broken.

**Comment by otan** [comment]
Yeah I had this lying around for a while so wanted to put it up and delete it locally :)

I havent the faintest on the snappy issue :/ I can't repro it locally. My guess is a weird flag or build issue...

**Comment by petermattis** [comment]
> I havent the faintest on the snappy issue :/ I can't repro it locally. My guess is a weird flag or build issue...

Can you add logging and then run the test a whole bunch of times on teamcity? That's a pretty awful debug-cycle, but it is a path forward.

**Comment by knz** [comment]
FWIW I am able to repro this reliably on linux by simply running the `expect` command manually a couple of times. FYI I use the following command:

```
killall -9 cockroach cockroachlogs; rm -rf logs; expect -d -f pkg/cli/interactive_tests/test_....tcl ./cockroach
```

This is amenable to use in combination with history recall.

**Comment by otan** [comment]
> this reliably on linux
wonder if that's my problem -- i run this in a tight loop and i can't get it to work

**Pull request closed without merging**
