### PR TITLE
clusterversion: bump MinSupported to 23.2

### PR DESCRIPTION
**Pull request by RaduBerinde**
Epic: REL-696

#### clusterversion: bump MinSupported to 23.2

Release note: None

#### sql: update logictests

Remove `local-mixed-23.1` and `cockroach-go-testserver-23.1` configs
and update files accordingly.

Release note: None

#### dbdesc: tolerate 23.1-20 version

In 23.2 the system database bootstrap version is 23.1-32 which is the
last upgrade version before 23.2. However, this last upgrade does not
bump the version so a cluster that was upgraded to 23.2 will end up
with system database schema version 23.1-20.

Either way, the schema version is smaller than the minimum supported
cluster version of 23.2. This change adds a map that hardcodes the
schema version corresponding to the 23.2 cluster version when we check
if the version is acceptable.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 98 of 98 files at r3, 6 of 6 files at r4, 11 of 11 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121775#-:-Nuy04xP0-pSwAOV0LAD:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @celiala, @jbowens, @msbutler, @rafiss, and @rail)

**Review by msbutler — APPROVED** [review]
DR tests look good

**Review by celiala — APPROVED** [review]
bump of MinSupported to V23_2 LGTM.
Didn't read through individual tests cleaned up - but at a high-level skim, the test cleanup makes sense to me.
Had one question (inline) about the hard-coded systemDatabaseSchemaVersions

> Reviewed 1 of 1 files at r2, 13 of 123 files at r7, 91 of 103 files at r8, 5 of 11 files at r9, 11 of 16 files at r10, 7 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121775#-:-Nv-VItA5b6eHIogJQ_-:b-y6slwf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @RaduBerinde, @rafiss, and @rail)

___
*[`pkg/sql/catalog/dbdesc/database_desc.go` line 283 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/121775#-Nv-Udvt76lCBA84tunL:-Nv-Udvt76lCBA84tunM:b-ci0lq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5615569b4cb72d1c334b71c77addf6e1f5fa2c4c/pkg/sql/catalog/dbdesc/database_desc.go#L283)):*
> This change adds a map that hardcodes the  
schema version corresponding to the 23.2 cluster version when we check  
if the version is acceptable.

will we be able to remove this hardcoded version at some point? or this has to remain forever?

(if the latter, maybe a note as to when this can be removed?)

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121775#-:-Nv265Iz04tr6csquYDM:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @celiala, @jbowens, @rafiss, and @rail)

___
*[`pkg/sql/catalog/dbdesc/database_desc.go` line 283 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/121775#-Nv-Udvt76lCBA84tunL:-Nv250rS3H8qWJa571tu:b-6faoc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5615569b4cb72d1c334b71c77addf6e1f5fa2c4c/pkg/sql/catalog/dbdesc/database_desc.go#L283)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

> This change adds a map that hardcodes the  
schema version corresponding to the 23.2 cluster version when we check  
if the version is acceptable.

will we be able to remove this hardcoded version at some point? or this has to remain forever?

(if the latter, maybe a note as to when this can be removed?)
</blockquote></details>

We only need it to be set for `clusterversion.MinSupported`. Ideally we would somehow make sure the schema version matches the final release version and we'd remove this (I made a suggestion along these lines in #121914). Added a comment.

**Review by rail — APPROVED** [review]
> Reviewed 98 of 98 files at r13, 6 of 6 files at r14, 11 of 11 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121775)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @celiala, @jbowens, @RaduBerinde, and @rafiss)

___
*[`pkg/upgrade/upgrades/permanent_mvcc_statistics_migration_test.go` line 34 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/121775#-Nv29PSP1x2KmhKENfid:-Nv29PSP1x2KmhKENfie:b-4x6ptx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cf16c5cc5fee2406dac14679b1dbc1a43a71a1/pkg/upgrade/upgrades/permanent_mvcc_statistics_migration_test.go#L34)):*
> ```Go
> 		ctx   = context.Background()
> 		tc    = testcluster.StartTestCluster(t, 1, base.TestClusterArgs{})
> 		sqlDB = tc.ServerConn(0)
> ```

Do you need to `defer sqlDB.Close()` it? The previous version closed `db` which pointed to the same resource.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121775)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @celiala, @jbowens, @rafiss, and @rail)

___
*[`pkg/upgrade/upgrades/permanent_mvcc_statistics_migration_test.go` line 34 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/121775#-Nv29PSP1x2KmhKENfid:-Nv2_af43Mw-3ED1c8GX:bxpgffx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cf16c5cc5fee2406dac14679b1dbc1a43a71a1/pkg/upgrade/upgrades/permanent_mvcc_statistics_migration_test.go#L34)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Do you need to `defer sqlDB.Close()` it? The previous version closed `db` which pointed to the same resource.
</blockquote></details>

Done, and also updated another test which I used as a guide.

**Pull request merged**
