### PR TITLE
sql: version gating CREATE FUNCTION

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
This commit adds a version gate for `CREATE FUNCTION` statement.

Release note: None.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85744#-:-N92c_UQ68wNr3wBM9c3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Comment by chengxiong-ruan** [comment]
conflicting with myself looks like :(
bors r-

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
