### PR TITLE
sql: miscellaneous fixes to the `CONVERT TO SCHEMA` command

### LINKED ISSUE #53563: Disallow converting database to schema for the current database
If a user uses `ALTER DATABASE... CONVERT TO SCHEMA WITH PARENT...` for the database they are currently connected to, CockroachDB allows it which causes a bad UX after the database is deleted
```
root@127.0.0.1:63916/rafi> ALTER DATABASE rafi CONVERT TO SCHEMA WITH PARENT my_app;
TODO (rohany): Implement

Time: 124.378ms

warning: error retrieving the database name: pq: database "rafi" does not exist

root@127.0.0.1:63916/?> show databases;
  database_name
-----------------
  bill
  defaultdb
  movr
  my_app
  postgres
  system
  vy
(7 rows)

Time: 2.71ms

warning: error retrieving the database name: pq: database "adam" does not exist
root@127.0.0.1:63916/?> show search_path;
ERROR: database "adam" does not exist
SQLSTATE: 3D000
warning: error retrieving the database name: pq: database "adam" does not exist
```

**Desired behavior**
Instead, we should disallow this command for the current database and error out

### PR DESCRIPTION
**Pull request by rohany**
Fixes #53563.

Release justification: low risk updates to new functionality
Release note (sql change): Disallow the `CONVERT TO SCHEMA` command on
the current database.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53564#-:-MG4U1010Fl_mRyXJ266:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by otan** [comment]
bors r-

merge conflict

**Pull request merged**
