### PR TITLE
Output the admin and sql URLs and log dir on startup.

### LINKED ISSUE #4337: cli: improve initial `cockroach start` output
`cockroach start` should output a handful of terse lines when it starts (as compared to the log messages it currently produces, see #4336). The info we should be providing is:

* The logging directory.
* The store directories.
* The admin UI URL.
* The postgres URL.

Something along the lines of:

```
~ cockroach start
admin:    http://localhost:26257
postgres: postgresql://localhost:15432
logdir:   /var/tmp/foo/bar
stores:   ./cockroach-data
```

### PR DESCRIPTION
**Pull request by petermattis**
Now when starting cockroach:

  ~ cockroach start --dev --host=localhost
 ...
 admin: http://localhost:26257
 sql:   postgres://localhost:15432
 logs:  /var/folders/qc/fpqpgdqd167c70dtc6840xxh0000gn/T/

Fixes #4337.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4448)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM

**Comment by mberhault** [comment]
can you list the stores as well? useful, especially when combined with #4453
the flag value should be sufficient, I don't think it needs to dig into the list of stores itself.

**Comment by petermattis** [comment]
@mberhault Added a `stores:` line. I think we may want to provide a bit more detail than the raw flag, but for now this is sufficient.

**Comment by mberhault** [comment]
agreed, it would be nice to have a little summary: path, type (in-mem or other), capacity, etc... but it can definitely wait.

**Comment by mberhault** [comment]
Just checking: your PR message shows "logs: /var/.../some-random-looking-thing", but you're using `os.TempDir()` in `initFlags1

**Comment by petermattis** [comment]
That's the temp directory on OSX:

```
~ echo $TMPDIR
/var/folders/qc/fpqpgdqd167c70dtc6840xxh0000gn/T/
```

**Comment by mberhault** [comment]
wow. really? that's just odd. It looked like you had been using
`ioutil.TempDir`, then changed it.
Nevermind then.

**Comment by spencerkimball** [comment]
*[server/context.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4448#-KAp2-xPHWzLnZfnVh9S:-KAp2-xQQciF7WsU-Nu6:-1571516656) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7050c95db5faca7226b94939132290d9a771f46/server/context.go#L268)):*
One thing I've noticed about these URLs is that they're damn difficult to use unless your client is running in the same directory as your server due to relative paths to the certs directory. Perhaps you should use `filepath.Abs()` when adding to `options`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4448)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/context.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4448#-KAp2-xPHWzLnZfnVh9S:-KAp2g28IGA2VsWjyCiU:-2143798260) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7050c95db5faca7226b94939132290d9a771f46/server/context.go#L268)):*
That's a good point. It'll make the URLs more gnarly, though. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4448)*

**Comment by jseldess** [comment]
Covered in docs for [`cockroach start`](https://www.cockroachlabs.com/docs/start-a-node.html#standard-output) as well as on [Start a Local Cluster](https://www.cockroachlabs.com/docs/start-a-local-cluster.html).

**Pull request merged**
