### PR TITLE
cli: add new tags in tsdump datadog upload

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously, we supported limited set of tsdump datadog flags which would represent as tags. This was inadequate to filter datadog dashboard to find appropriate tsdump upload. This change introduce new tags which would help us in identifying right set of uploaded tsdump for analysis.
Below are the newly introduced flags/tags:
- cluster-id
- zendesk-ticket
- org-name
- user-name
- upload_timestamp (auto populated)

Epic: none
Release note: None
Part of: CRDB-44870

### CODE REVIEW

**Review by arjunmahishi — COMMENTED** [review]
I would suggest going with a generic `--tags` flag that takes a list of arbitrary `key:values`. I know this can lead to inconsistent tags. But I am guessing the usage pattern of this will be through runbooks that have command that are copy-pasted. So, that partly solves the inconsistent tags. 

I think the ddagent also has this kind of pattern for tags.

Debug zip upload uses this pattern: https://github.com/cockroachdb/cockroach/blob/a86b1274ef81e493f4cbdabe8b20d8977ab099f6/pkg/cli/debug.go#L1582-L1584 

There is also a utility function to handle dedup, conflict with auto-generated tags, etc: https://github.com/cockroachdb/cockroach/blob/a86b1274ef81e493f4cbdabe8b20d8977ab099f6/pkg/cli/zip_upload.go#L775-L777 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136290#-:-OCqcaPp7M9D5DZI5sy-:b2vfevx)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by aa-joshi — COMMENTED** [review]
@arjunmahishi The tag creation has serious implications in cost of sending metrics in datadog. You can check the calculation [here](https://docs.datadoghq.com/account_management/billing/custom_metrics/?tab=countrate). Hence, we want to have as much as control in tag creation. And TSE has confirmed that these tags are more than enough for our usecase.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136290#-:-OCqmbgX2fYPunxrmeRj:b-x1amvd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by arjunmahishi — APPROVED** [review]
Ohh got it :thumbsup: 
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136290#-:-OCqxFrM4RFLEx-ush3S:by4s1bh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by aa-joshi** [comment]
TFTR!

bors r+

**Pull request merged**
