### PR TITLE
kvstreamer: fix the usage of the range iterator

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, after `Seek`ing the range iterator to the next key in the batch of requests in the streamer we forgot to check the validity of the iterator. In particular, this could lead to a crash of the process if `Seek` encountered an error for whatever reason. In practice, I've only observed this when running TPCH with high concurrency when GOMEMLIMIT is set.

The bug was introduced in an innocently-looking refactor in 041b1045018fb7993c842f1c80542d7abac9c52d.

Epic: None

Release note (bug fix): CockroachDB could previously crash in rare circumstances when evaluating lookup and index joins. The bug is present since 22.2.0 release. Temporary workaround without upgrading to the release with this fix is changing the value of undocumented cluster setting `sql.distsql.use_streamer.enabled` to `false`.

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
:lgtm: Is there a way we can enforce the error check?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94031#-:-NJmpRZ2Csx36RSc6ycx:b-guygr9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by yuzefovich — COMMENTED** [review]
We could change `RangeIterator` interface so that `Seek` would explicitly return an error instead of invalidating the iterator. However, that would change pretty-nice looking interface where it can be used with the `for` loop. I looked over how other callers do it, and the streamer is the only one that had an issue and was deviating from the iterator pattern around the `for` loop, so I just pushed a minor update to bring it more in line with others. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94031#-:-NJmvonZ4NzD7X0QmpVP:b-7qftuj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Review by DrewKimball — APPROVED** [review]
:lgtm: Looks good!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94031#-:-NJq1fdG-YvNNyrFCvIu:b276ill)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94031#-NJq1ZFj3rUT_gVXs_x_:-NJq1ZFj3rUT_gVXs_xa:bbr9uca) ([raw file](https://github.com/cockroachdb/cockroach/blob/90f6b0f9f580b2b383a19049795cd0d4a33b0748/pkg/kv/kvclient/kvstreamer/streamer.go#L635)):*
> ```Go
> 			// This was the last range. Breaking here rather than Seek'ing the
> 			// iterator to RKeyMax (and, thus, invalidating it) allows us to
> 			// avoid adding a confusingly-looking message into the trace.
> ```

[nit] `confusingly-looking` -> `confusing`

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94031#-:-NJq2hBc2Q5uQAVq3v1m:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94031#-NJq1ZFj3rUT_gVXs_x_:-NJq2gal4qmyKCYufAL_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90f6b0f9f580b2b383a19049795cd0d4a33b0748/pkg/kv/kvclient/kvstreamer/streamer.go#L635)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `confusingly-looking` -> `confusing`
</blockquote></details>

Done.

**Pull request merged**
