### PR TITLE
opt: updated logic to combine histograms and multi-column stats

### LINKED ISSUE #67966: opt: improve combination of multi-column stats and histograms
As shown by #67573, combining the selectivity estimates of histograms and multi-column stats can lead to incorrect row estimates. The simple formula of multiplying the selectivities from both methods and then "unapplying" the selectivity calculated from single-column distinct counts does not work well when columns are highly correlated and the selected values are popular in the histogram. We should investigate alternative approaches to combining these different estimates into a single, high-quality estimate.

Epic CRDB-10034

Jira issue: CRDB-8803

### PR DESCRIPTION
**Pull request by rytaft**
This commit changes the logic to combine stats estimates from histograms
and multi-column stats. Instead of multiplying the selectivities from
both methods and then "unapplying" the selectivity calculated from
single-column distinct counts, the new logic uses the multi-column stats
to determine the amount of correlation between columns, and then uses the
correlation to adjust the estimate from the histograms.

Specifically, we first find the correlation between the constrained columns,
as indicated by multi-column stats. It is a number between 0 and 1, where 0
means the columns are completely independent, and 1 means the columns are
completely correlated. Next, we calculate the upper and lower bound for the
selectivity from the histograms. Finally, the correlation is used to
calculate the returned selectivity value. If correlation is 0, the returned
value is the lower bound. If correlation is 1, the returned value is the
upper bound. Otherwise, it is somewhere in between.

Fixes https://github.com/cockroachdb/cockroach/issues/67966

Release note (performance improvement): Improved the optimizer's
cardinality estimates for predicates involving many constrained columns.
This may result in better index selection for these queries.

Release justification: low risk, high benefit changes to existing
functionality

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
This is RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-:-Mxc582w5bQ3InTuRfQv:b-n27ya0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
Very cool! :lgtm: 

> Reviewed 1 of 67 files at r1, 2 of 20 files at r2, 75 of 75 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-:-MxefND75CxlSrt3cPxA:b1n0kfb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3661 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxeaZZBDJQH_kQo377P:-MxeaZZBDJQH_kQo377Q:bwpjiv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2f2e28adeebdc9b76f456e0df31df75f62f95/pkg/sql/opt/memo/statistics_builder.go#L3661)):*
> ```Go
> // [1] Ilyas, Ihab F., et al. "CORDS: automatic discovery of correlations and
> //     soft functional dependencies." SIGMOD 2004.
> //
> ```

nit: describe the second return value
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3848 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxeaIbt1hre9yWwrj7Y:-MxeaIbt1hre9yWwrj7Z:bwpjiv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2f2e28adeebdc9b76f456e0df31df75f62f95/pkg/sql/opt/memo/statistics_builder.go#L3848)):*
> ```Go
> // and after the filter was applied. It assumes independence between columns,
> // so it uses equation (1) from selectivityFromMultiColDistinctCounts. See the
> // comment above that function for details.
> ```

nit: describe the second return value

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-:-Mxh9lmGE5c2kfKBlcVp:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3661 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxeaZZBDJQH_kQo377P:-Mxh9cqK9jsH84tEcxxu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2f2e28adeebdc9b76f456e0df31df75f62f95/pkg/sql/opt/memo/statistics_builder.go#L3661)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: describe the second return value
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3848 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxeaIbt1hre9yWwrj7Y:-Mxh9f711H_ZUDdITvCx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2f2e28adeebdc9b76f456e0df31df75f62f95/pkg/sql/opt/memo/statistics_builder.go#L3848)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: describe the second return value
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: Looks like you'll need to `-rewrite` the test `TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row_query_behavior`.

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-:-Mxj0LzYBWJkK9sMxsFh:bkjhftw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-:-MxlEacR9KijpELN__Yh:b-voiyyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

**Review by msirek — COMMENTED** [review]
Nice improvement!  I have some comments here.  I was going to keep reviewing this tomorrow, but I see it's already merged!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-:-MxjSdkc632Y4MQXFGEP:bswkb24)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3731 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxjzgcW2xN_o5_GMTiZ:-MxjzgcW2xN_o5_GMTi_:bech9l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f1222bd68c374ddf1081a7c63e52588f6942e8/pkg/sql/opt/memo/statistics_builder.go#L3731)):*
> ```Go
> 	inputColStat, inputStats := sb.colStatFromInput(multiColSet, e)
> 	if inputColStat.DistinctCount+epsilon >= inputStats.RowCount {
> 		return singleColSelectivity, minLocalSel
> ```

This is such a hard cutoff between using multicolumn stats and not using them, it may lead to some bad estimates.  Is there a way to make the transition more gradual, or a blending of the results, like done with the correlation?  Or maybe you meant subtract`epsilon` instead of add it, to detect when we have a bad `DistinctCount`? For example, without this check the following test case gives a very accurate estimate, but with the check the row count is underestimated:
```
CREATE TABLE t (i int, j int, k int, l int);
INSERT INTO t SELECT g,g,g,g FROM generate_series(1, 100000) g(g)
ANALYZE t;
CREATE STATISTICS ij_stats ON i,j FROM t;
CREATE STATISTICS kl_stats ON k,l FROM t;
explain (verbose)
select * from t where i between 1 and 10000 and j between 1 and 10000 and k between 1 and 10000 and l between 1 and 10000;
```
Without the check:  `estimated row count: 8,993`
With the check:  `estimated row count: 10`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3753 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxjamD07UT_V9CiZ6DD:-MxjamD07UT_V9CiZ6DE:bjjy257) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f1222bd68c374ddf1081a7c63e52588f6942e8/pkg/sql/opt/memo/statistics_builder.go#L3753)):*
> ```Go
> 
> 	// multiColSelectivity must be at least as large as singleColSelectivity.
> 	multiColSelectivity = props.MaxSelectivity(multiColSelectivity, singleColSelectivity)
> ```

Could you please add a comment explaining this point?  Instead, I would expect the multicolumn selectivity to never exceed the single-column selectivity since including more columns could only ever increase the number of distinct values.  But this code is setting `singleColSelectivity` as a lower bound instead of an upper bound.  However, I tried changing this to MinSelectivity() and got some bad estimates.  Is `multiColSelectivity` more like a selectivity upper bound?



_Code quote:_
```Go
multiColSelectivity must be at least as large as singleColSelectivity.
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3792 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-Mxjd1Z3E_Lnutl5Rr3M:-Mxjd1Z3E_Lnutl5Rr3N:bo8m7ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f1222bd68c374ddf1081a7c63e52588f6942e8/pkg/sql/opt/memo/statistics_builder.go#L3792)):*
> ```Go
> 			)
> 			selLowDistinctCountCols.Multiply(selOtherCols)
> 			multiColSelectivity = props.MinSelectivity(multiColSelectivity, selLowDistinctCountCols)
> ```

This code deserves a comment. It's taking a subset of the multicolumn stats columns and multiplying their selectivity with that of the remaining columns. But if the distinct count on each  `lowDistinctCountCol` is <= 1, shouldn't their combined selectivity always be 1?  Do we really need to look up `selLowDistinctCountCols`'s selectivity?  Can we just use `selOtherCols`'s selectivity as a cap on selectivity directly?

**Review by rytaft — COMMENTED** [review]
I've opened #77655 to address the remaining comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-:-Mxr6uq40J_biyAqwUlV:b-iz9kc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3731 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxjzgcW2xN_o5_GMTiZ:-Mxqwp3Q7PZaDsjWrp5N:b-cvk406) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f1222bd68c374ddf1081a7c63e52588f6942e8/pkg/sql/opt/memo/statistics_builder.go#L3731)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

This is such a hard cutoff between using multicolumn stats and not using them, it may lead to some bad estimates.  Is there a way to make the transition more gradual, or a blending of the results, like done with the correlation?  Or maybe you meant subtract`epsilon` instead of add it, to detect when we have a bad `DistinctCount`? For example, without this check the following test case gives a very accurate estimate, but with the check the row count is underestimated:
```
CREATE TABLE t (i int, j int, k int, l int);
INSERT INTO t SELECT g,g,g,g FROM generate_series(1, 100000) g(g)
ANALYZE t;
CREATE STATISTICS ij_stats ON i,j FROM t;
CREATE STATISTICS kl_stats ON k,l FROM t;
explain (verbose)
select * from t where i between 1 and 10000 and j between 1 and 10000 and k between 1 and 10000 and l between 1 and 10000;
```
Without the check:  `estimated row count: 8,993`
With the check:  `estimated row count: 10`
</blockquote></details>

I made the transition more gradual.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3753 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-MxjamD07UT_V9CiZ6DD:-Mxqwtr8-x_qOXWNhxsX:be6n88t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f1222bd68c374ddf1081a7c63e52588f6942e8/pkg/sql/opt/memo/statistics_builder.go#L3753)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Could you please add a comment explaining this point?  Instead, I would expect the multicolumn selectivity to never exceed the single-column selectivity since including more columns could only ever increase the number of distinct values.  But this code is setting `singleColSelectivity` as a lower bound instead of an upper bound.  However, I tried changing this to MinSelectivity() and got some bad estimates.  Is `multiColSelectivity` more like a selectivity upper bound?
</blockquote></details>

Added a comment -- singleColSelectivity is eq (1), so it's a lower bound
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3792 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76786#-Mxjd1Z3E_Lnutl5Rr3M:-Mxqx2-B8NySPoeeDCmE:b-rci62y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f1222bd68c374ddf1081a7c63e52588f6942e8/pkg/sql/opt/memo/statistics_builder.go#L3792)):*
>  if the distinct count on each lowDistinctCountCol is <= 1, shouldn't their combined selectivity always be 1?

No, since their input distinct count is greater than 1. We already eliminated columns that didn't contribute to the selectivity above.

Added a comment -- hopefully it's clearer now?

**Pull request merged**
