### PR TITLE
roachtest/costfuzz: create failure.log file on demand

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes it so that `failure.log` files are created lazily on demand in `costfuzz` and `unoptimized_query_oracle` roachtests. It seems nicer this way since for successful runs previously we'd see empty failure log files which were a bit confusing.

Epic: None

Release note: None

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
Nice fix!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108739#-:-Nbqfvo54kAG-BfU_1uz:b-k6moza)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108739#-Nbqfmuv05_hfcXxwO_v:-Nbqfmuv05_hfcXxwO_w:b-wdn20v) ([raw file](https://github.com/cockroachdb/cockroach/blob/781c8babbdb06e50cbe8eb441a4424be437fa153/pkg/cmd/roachtest/tests/query_comparison_util.go#L168)):*
> ```Go
> 		}
> 	}()
> 	defer failureLog.Close()
> ```

Should this line be removed because now `failureLog` might be nil and the deferred function is doing the closing?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108739#-Nbqfmuv05_hfcXxwO_v:-NbqpNnYEV1O9B8MQnDU:b-x9u7fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/781c8babbdb06e50cbe8eb441a4424be437fa153/pkg/cmd/roachtest/tests/query_comparison_util.go#L168)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should this line be removed because now `failureLog` might be nil and the deferred function is doing the closing?
</blockquote></details>

Oops, nice catch, thanks.

**Review by msirek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108739#-:-NbtxcdJEHb0g29iFQaR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
