### PR TITLE
sql/schemachanger: fix logic in decomp for index/partition zone configs

### LINKED ISSUE #134452: schemachanger: undropped backrefs for zone-configured table
For the following scenario (s/o @fqazi for the repro):
```
statement ok
CREATE TABLE db1.t1_with_index_zone(x INT, j INT REFERENCES db1.t1_with_index_zone(x), PRIMARY KEY(x)) LOCALITY REGIONAL BY ROW

statement ok
ALTER PARTITION "ap-southeast-2" OF INDEX db1.t1_with_index_zone@t1_with_index_zone_pkey CONFIGURE ZONE USING gc.ttlseconds = 32000;

statement ok
ALTER PARTITION "ca-central-1" OF INDEX db1.t1_with_index_zone@t1_with_index_zone_pkey CONFIGURE ZONE USING gc.ttlseconds = 34000;

statement ok
ALTER PARTITION "us-east-1" OF INDEX db1.t1_with_index_zone@t1_with_index_zone_pkey CONFIGURE ZONE USING gc.ttlseconds = 38000;

DROP TABLE db1.t1_with_index_zone CASCADE;
```

The `DROP TABLE` command panics in the DSC with an undropped backref message

For master/24.3, this is because we create too many elements for our subzone(s) than necessary during decomposition. For each subzone, we mis-decompose it into an index and partition zone config element; when it should be one or the other

Jira issue: CRDB-44084

### PR DESCRIPTION
**Pull request by annrpom**
We create too many elements for our subzone(s) than necessary during decomposition. For each subzone, we mis-decompose it into an index and partition zone config element; when it should be one or the other. This can lead to a panic during dropping a table with subzone configs -- as we will detect undropped backrefs.

Epic: none
Fixes: #134452

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
I didn't put a release note on this because I wasn't sure if I should (for 24.3, the user would have to force `SetZoneConfig` in the dsc to get here), but pls correct me on this

**Review by rafiss — APPROVED** [review]
nice fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134454#-:-OB2Ro8a3PvIjb1n5O-B:bhpddey)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/cleanup_zone` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134454#-OB2RcFM3iizKgm1DqQt:-OB2RcFM3iizKgm1DqQu:b-ufj6vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36863181e4e8489631d801ffcb2be656860d69b/pkg/ccl/logictestccl/testdata/logic_test/cleanup_zone#L1)):*
> ```
> # LogicTest: multiregion-9node-3region-3azs multiregion-9node-3region-3azs-tenant multiregion-9node-3region-3azs-no-los
> ```

super nit: purely for the sake of keeping the diff smaller, could we put this test in `pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs` instead?

**Review by annrpom — COMMENTED** [review]
do u notice my new avatar

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134454#-:-OB2_YYgB3EiSx_OXJ4C:b-ked80w)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/cleanup_zone` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134454#-OB2RcFM3iizKgm1DqQt:-OB2_abZ1BvvKYJxxOs5:bymg1vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36863181e4e8489631d801ffcb2be656860d69b/pkg/ccl/logictestccl/testdata/logic_test/cleanup_zone#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: purely for the sake of keeping the diff smaller, could we put this test in `pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs` instead?
</blockquote></details>

good point -- done!

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r+

**Pull request merged**
