### PR TITLE
storage: delay manual splits that would result in more snapshots

### PR DESCRIPTION
**Pull request by tbg**
This is unpolished, but I had used an earlier version of this with what at the
time looked like success. At this point I suspect that this is the best way to
suppress Raft snapshot growth in IMPORT/RESTORE.

(Definitely needs tests).

----

When a Range has followers that aren't replicating properly, splitting
that range results in a right-hand side with followers in a similar
state. Certain workloads (restore/import/presplit) can run large numbers
of splits against a given range, and this can result in a large number
of Raft snapshots that backs up the Raft snapshot queue.

Ideally we'd never have any ranges that require a snapshot, but over
the last weeks it has become clear that this is very difficult to
achieve since the knowledge required to decide whether a snapshot
can efficiently be prevented is distributed across multiple nodes
that don't share the necessary information.

This is a bit of a nuclear option to prevent the likely last big
culprit in large numbers of Raft snapshots in #31409.

With this change, we should expect to see Raft snapshots regularly when
a split/scatter phase of an import/restore is active, but never large
volumes at once.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_command.go, line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSFpfwh3C-WYrKo56Ag:-LSFpfwiEkb9XSSxnZEQ:b-b9xeug) ([raw file](https://github.com/cockroachdb/cockroach/blob/21da18d3f216e6408a08b5f5817b524f51283b7e/pkg/storage/replica_command.go#L282)):*
> ```Go
> 	}
> 	if tPostWait == (time.Time{}) {
> 		tPostWait = timeutil.Now()
> ```

I'm not understanding what is motivating this handling of `tPostWait`. I think you want a boolean indicating whether you ever had a `time.After` call, and if yes then output the `delayed split` for message. As it is, it appears you'll always output that message. 
___
*[pkg/storage/replica_command.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSFoUPmADn8ovLjTUPX:-LSFoUPnCNYPB2eD4hPl:bxvk88y) ([raw file](https://github.com/cockroachdb/cockroach/blob/21da18d3f216e6408a08b5f5817b524f51283b7e/pkg/storage/replica_command.go#L393)):*
> ```Go
> 
> 	log.Infof(ctx, "initiating a split of this range at key %s [r%d]%s",
> 		extra, splitKey, rightDesc.RangeID)
> ```

Is the argument reordering intentional? Seems like that messes with the log message strangely.

**Review by tbg — COMMENTED** [review]
The small fry missing from this change aside, assuming this addresses the problem, is this what we want? Does any alternative approach come to mind? I concede defeat on avoiding Raft snapshots. The `RaftPostSplitSuppressSnapshotTicks` mechanism makes snapshots much worse when it delays without the split trigger showing up, and yet it seems impossible to do much better. I tried (unpushed WIP) to move that detection to the receiver (i.e. the Raft leader of the uninitialized RHS) and this works very well unless the Raft leader of the RHS isn't colocated with that of the LHS. This is mostly true today (though not in the test that I added for this mechanism, which is now unfixably flaky) and I imagine that in the future we won't want splits to pin the RHS and LHS leaseholder together as is done today. (And even if that were somehow circumvented, the problem is still that a single Raft snapshot for whatever reason is multiplied by whatever number of splits hit the range in that state, unless there's a mechanism such as this one).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSG0FYt2hVV5GMsvq9X:b-cjaadj)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_command.go, line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSFpfwh3C-WYrKo56Ag:-LSG-06U06Rk4DaRtUf3:b-gv62eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/21da18d3f216e6408a08b5f5817b524f51283b7e/pkg/storage/replica_command.go#L282)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not understanding what is motivating this handling of `tPostWait`. I think you want a boolean indicating whether you ever had a `time.After` call, and if yes then output the `delayed split` for message. As it is, it appears you'll always output that message. 
</blockquote></details>

I think this works as intended. Note that we initialize `tPostWait := tPreWait` and zero it out only when we're actually waiting (i.e. when `ticks > 0`, though that should really be `ticks = 1`). I agree that a bool is saner though, done.
___
*[pkg/storage/replica_command.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSFoUPmADn8ovLjTUPX:-LSG-6w29wKmBmjTRoqX:b-psf06d) ([raw file](https://github.com/cockroachdb/cockroach/blob/21da18d3f216e6408a08b5f5817b524f51283b7e/pkg/storage/replica_command.go#L393)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the argument reordering intentional? Seems like that messes with the log message strangely.
</blockquote></details>

No, and I just fixed this because the output looked really confusing.

**Review by petermattis — COMMENTED** [review]
The other mitigation we might try is to speed up Raft snapshots when they are very small. For restore / import, the Raft snapshots should be mostly empty. For a range with real data that requires a snapshot, splitting will double the number of snapshots, but each snapshot should be half the size. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSGC5si9Dn3dN8cPUut:b8qpo5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_command.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGCjEBDS2fGRMH4Foc:-LSGCjEBDS2fGRMH4Fod:bglxqay) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L290)):*
> ```Go
> 	}
> 
> 	if elapsed := timeutil.Since(tPreWait); waited {
> ```

Nit: this should probably be `if waited { extra += fmt.Sprintf("...", timeutil.Since(tPreWait)) }`

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSGD4LX1is30tPdSPsi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/replica_command.go, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGHCiLEBZo6-U4819F:-LSGHCiLEBZo6-U4819G:b-m0lluy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L235)):*
> ```Go
> 	// up. If we run out of time, we'll resume the split no matter what.
> 	_ = r.maybeDropMsgAppResp
> 	maxDelaySplitToAvoidSnapshotTicks := 5 + r.store.cfg.RaftPostSplitSuppressSnapshotTicks
> ```

I'm not sure this is long enough to wait. If the Raft snapshot queue is backed up it can take minutes to clear.  So this just seems like it will wait for a bit, then add more work to the queue.

**Review by bdarnell — APPROVED** [review]
I don't love this but if it can put an end to the saga of raft snapshots I'm for it.

One more idea is whether we can tune the order in which splits happen. Would reversing the order of splits make us less likely to hit pathological cases? Or if both ascending and descending are problematic, maybe a pattern like binary search to avoid hitting the same ranges repeatedly?

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSH1P8zDDVYnlpy_v9R:b-767jmb)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/replica_command.go, line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGzS133w0V98eqStN_:-LSGzS133w0V98eqStNa:b-ft8wxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L234)):*
> ```Go
> 	// plus a bit of padding to give a snapshot a chance to catch the follower
> 	// up. If we run out of time, we'll resume the split no matter what.
> 	_ = r.maybeDropMsgAppResp
> ```

Is this just to provide a grep/guru target or did you mean to call this method? (if it's just a guru target say so in the comment)

**Comment by bdarnell** [comment]
> The longest split I've seen delayed is 34.5s, though that comes with the benefit of no Raft snapshot backlog. Is that still palatable?

As long as that worst-case only happens either during large restore/imports or during network distress, I think it's bearable.

**Comment by tbg** [comment]
I second what @petermattis said, it's still not 100% clear what's going on. I think we might actually be seeing priority inversion at work here because preemptive snapshots routinely take 15+ seconds. Putting logging like in this PR in place has been helpful. I'd like to confirm this (or a similar theory) before merging this, and while we're there, the Raft snapshot queue (which very likely is the bottleneck here) needs to get better introspection.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_command.go, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGHCiLEBZo6-U4819F:-LSGgNQd2GQk4wkdfcnF:b-rpiiam) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L235)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure this is long enough to wait. If the Raft snapshot queue is backed up it can take minutes to clear.  So this just seems like it will wait for a bit, then add more work to the queue.
</blockquote></details>

In my experimentation with this change, bumping this value significantly produces a benefit. In particular, without this change I see a number of messages about delaying a split for 5s only to let it through despite it possibly causing a Raft snapshot. If a bump the value I see splits delayed for longer (17.2s in one example), but no spike in Raft snapshots.
___
*[pkg/storage/replica_command.go, line 296 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSLArV6AreADvA_osvX:-LSLArV6AreADvA_osvY:b-pbjd6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b0f789913090364718a99548688c64f2ba3547e/pkg/storage/replica_command.go#L296)):*
> ```Go
> 				return false, nil
> 			})
> 			r.raftMu.Unlock()
> ```

Don't you want to do this before the `select`?

**Review by tbg — COMMENTED** [review]
No code updates in this round of comments. More tomorrow.

Using the backoff only for certain AdminSplit (those issued by backup/restore) is something we can possibly backport so I'm planning to make that change (after asserting that it fixes all the problems and making sure that long backoffs are traced back to a root cause via a log message).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSLiElN7pPSbZTQ-ZBE:b-yqtdl0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_command.go, line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGzS133w0V98eqStN_:-LSLh_iy7gV_Avevj_Fz:b-2h0tpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L234)):*
> ```
> see the _ assignment below)
> ```

What should I change this to? (This helps navigate and also prevents naming rot)

```
_ = ... // guru assignment
```

?
___
*[pkg/storage/replica_command.go, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGHCiLEBZo6-U4819F:-LSLhkTq0XQVrNDtF27R:btgxiq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L235)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

In my experimentation with this change, bumping this value significantly produces a benefit. In particular, without this change I see a number of messages about delaying a split for 5s only to let it through despite it possibly causing a Raft snapshot. If a bump the value I see splits delayed for longer (17.2s in one example), but no spike in Raft snapshots.
</blockquote></details>

I've seen the same. I think ~15s is sort of a magic number because that's how long the average snapshot will be blocked. A preemptive snapshot is usually ~30mb in this workload and they're rate limited to 2mb/s and can block a Raft snapshot to the same target. So a Raft snapshot will often have to wait ~15s.
___
*[pkg/storage/replica_command.go, line 296 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSLArV6AreADvA_osvX:-LSLib2p8ZgliSRdlrI2:bh90wl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b0f789913090364718a99548688c64f2ba3547e/pkg/storage/replica_command.go#L296)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Don't you want to do this before the `select`? 
</blockquote></details>

Good point, will do.

**Review by tbg — COMMENTED** [review]
(I'm also going to experiment with splitting the receiver-side snapshot semaphore into two, so that we always allow one Raft snapshot to be in flight, even if there's already a preemptive one).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSLkCgZ9RJG395UgYoi:b-zavz1g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by tbg** [comment]
For the record (I think I only mentioned this privately so far): testing this PR has discovered what I think is a Raft bug, where a follower isn't tracked as replicating after it has applied a snapshot that is up-to-date with the leader's index. This is mostly inconsequential, but would trip up the wait logic. I'll link to the upstream PR once it's out (and I still think I found a bug).

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_command.go, line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGzS133w0V98eqStN_:-LSPKlPS4Hoa2koXUjTE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L234)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> ```
> see the _ assignment below)
> ```

What should I change this to? (This helps navigate and also prevents naming rot)

```
_ = ... // guru assignment
```

?
</blockquote></details>

Done.
___
*[pkg/storage/replica_command.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSGCjEBDS2fGRMH4Foc:-LSPMR37610VU60ra_JC:b-gk5vqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46399cfcebdde151e0a05f6deb7de701a5abb3/pkg/storage/replica_command.go#L290)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: this should probably be `if waited { extra += fmt.Sprintf("...", timeutil.Since(tPreWait)) }`
</blockquote></details>

Done, I think.
___
*[pkg/storage/replica_command.go, line 296 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSLArV6AreADvA_osvX:-LSPKuT--8nsf4h1QMS_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b0f789913090364718a99548688c64f2ba3547e/pkg/storage/replica_command.go#L296)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Good point, will do.
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
This PR needs lots of cleanup love, but I think the basic mechanism now works. I've run the first few minutes of restore2TB repeatedly and while I always see snapshots and sometimes see the backoff mechanism "give up" (14s in my current testing branch), the reason is always because a follower still needs a snapshot. I definitely saw the Raft bug pop up in almost every run until I had tuned all the Raft proposal knobs required (need to wake the leader), and it's been reliably gone since. I think we're getting somewhere here!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSPeq647b3-pjUg3UyA:b-i60fsy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by petermattis — COMMENTED** [review]
Progress! Let me know when you want me to give this another thorough look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSPgcNJ0QzA49CR1u-P:b-bevxui)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_command.go, line 305 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSPgpZ-EsfGflYnv5ZT:-LSPgpZ-EsfGflYnv5ZU:b-41a1wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0733b4a441b3e6e037b08938a4a0f71eed9f94b8/pkg/storage/replica_command.go#L305)):*
> ```Go
> 
> 			if pr.State != raft.ProgressStateReplicate {
> 				extra += fmt.Sprintf("; replica r%d/%d not caught up: %+v", r.RangeID, replicaID, &pr)
> ```

Adding on to `extra` every tick loop seems excessive. I think you want to do something where you construct a `newExtra` string for the progress, and then after the loop if `!done` you set `extra = newExtra`.

**Review by tbg — COMMENTED** [review]
@petermattis ready for another look. You're going to want to do a single pass across all revisions, there's been a lot of churn - sorry about that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSUZily146SzWwjNnrE:b-igln5u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_command.go, line 305 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSPgpZ-EsfGflYnv5ZT:-LSUZ4ay27hRCl9hn5XF:btvn988) ([raw file](https://github.com/cockroachdb/cockroach/blob/0733b4a441b3e6e037b08938a4a0f71eed9f94b8/pkg/storage/replica_command.go#L305)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Adding on to `extra` every tick loop seems excessive. I think you want to do something where you construct a `newExtra` string for the progress, and then after the loop if `!done` you set `extra = newExtra`.
</blockquote></details>

`extra` is reset at the beginning of the loop. Does that address your concern? We're not piling up across loops.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_command.go, line 305 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSPgpZ-EsfGflYnv5ZT:-LSU_PO203sLFNElI2XD:b-cj0puj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0733b4a441b3e6e037b08938a4a0f71eed9f94b8/pkg/storage/replica_command.go#L305)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`extra` is reset at the beginning of the loop. Does that address your concern? We're not piling up across loops.
</blockquote></details>

Yes, that addresses my concern. Must have missed when you added that.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LSZuPGR0NCLH9PP97pl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/split_delay_helper.go, line 50 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZsPPs7YA62vesVitj:-LSZsPPs7YA62vesVitk:b-t1e9cn) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper.go#L50)):*
> ```Go
> 
> func (sdh *splitDelayHelper) ProposeEmptyCommand(ctx context.Context) {
> 	r := (*Replica)(sdh)
> ```

Given that you're casting back to a `*Replica` here, what is the benefit of the `splitDelayHelper` type? Why not place these methods directly on `*Replica`? I suppose it keeps the method set of `Replica` a bit cleaner. 
___
*[pkg/storage/split_delay_helper_test.go, line 59 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZuIR876d-oajUyJwg:-LSZuIR876d-oajUyJwh:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper_test.go#L59)):*
> ```Go
> var _ splitDelayHelperI = (*testSplitDelayHelper)(nil)
> 
> func TestSplitDelayToAvoidSnapshot(t *testing.T) {
> ```

Nice test!
___
*[pkg/storage/split_delay_helper_test.go, line 65 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZu4b5AHxzQ01lmEh-:-LSZu4b5AHxzQ01lmEh0:bnxjrdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper_test.go#L65)):*
> ```Go
> 
> 	t.Run("disabled", func(t *testing.T) {
> 		// Should immediately bail out if it detects that it's not run on a follower.
> ```

`s/it's not run/it is run/g`?
___
*[pkg/storage/split_delay_helper_test.go, line 77 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZu80w9-UGeuAKP-c1:-LSZu80w9-UGeuAKP-c2:bnxjrdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper_test.go#L77)):*
> ```Go
> 
> 	t.Run("follower", func(t *testing.T) {
> 		// Should immediately bail out if it detects that it's not run on a follower.
> ```

`s/it's not run/it is run/g`?

**Review by tbg — COMMENTED** [review]
TFTR! :crossed_fingers: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-:-LS_4a7k54OcnG12CkBg:b-19fik6)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/replica_command.go, line 305 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSPgpZ-EsfGflYnv5ZT:-LS_3w1o1cR2phx31nKF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0733b4a441b3e6e037b08938a4a0f71eed9f94b8/pkg/storage/replica_command.go#L305)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, that addresses my concern. Must have missed when you added that.
</blockquote></details>

Done.
___
*[pkg/storage/split_delay_helper.go, line 50 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZsPPs7YA62vesVitj:-LS_4HI10Q9P2NAAJKvH:b9psexe) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper.go#L50)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Given that you're casting back to a `*Replica` here, what is the benefit of the `splitDelayHelper` type? Why not place these methods directly on `*Replica`? I suppose it keeps the method set of `Replica` a bit cleaner. 
</blockquote></details>

Yeah, encapsulation was what I was after. `*Replica` is already a giant grab bag of stuff that's really only interesting in a fairly narrow context. I would've pulled this out into a separate package but then I would've had to add random accessors to `*Replica` again. I think in some fairytale refactored world that would be the result, though.
___
*[pkg/storage/split_delay_helper_test.go, line 59 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZuIR876d-oajUyJwg:-LS_4ZV16G62R3N9fvNo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper_test.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

Done.
___
*[pkg/storage/split_delay_helper_test.go, line 65 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZu4b5AHxzQ01lmEh-:-LS_4_7RDxchNAmugh-W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper_test.go#L65)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/it's not run/it is run/g`?
</blockquote></details>

Done.
___
*[pkg/storage/split_delay_helper_test.go, line 77 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/32594#-LSZu80w9-UGeuAKP-c1:-LS_4_UG1dQowIcLZHEq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f7f0b7f8905e44f860d2570bf50a4f72d48f71/pkg/storage/split_delay_helper_test.go#L77)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/it's not run/it is run/g`?
</blockquote></details>

Done.

**Comment by tbg** [comment]
bors r=petermattis

**Comment by tbg** [comment]
@knz I'm not sure what's going on here, but TC thinks the test above simply "didn't print anything" for 1h. I'm fairly sure the storage package failed (my change is pretty invasive there), but it has an 8min timeout and was run with `-v` so that it shouldn't have buffered. Do you have any idea whether your recent line buffering change can have to do with that (I'm thinking no).

Going to re-run for now since TC is green -- maybe I caught a bad agent?

bors r=petermattis

**Pull request merged**
