### PR TITLE
upgrade: add system rbr upgrade and versions

### PR DESCRIPTION
**Pull request by jeffswenson**
This commit contains the version and upgrade tasks needed to migrate the
system.sql_instances, system.lease, and system.sqlliveness tables to an
index format compatible with regional by row tables.

Follow on work is needed to add version checks to code interacting with
the tables. The migrations will be enabled for each table as the version
checks are implemented. The draft PR #97406 contains version checks for
each of the tables and was manually tested with this change to ensure
the upgrade process works as expected.

Part of #98111

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
This seems nice. There are some minor TODOs you can revisit before we merge this, but I'm cool with this sequencing and looking forward to stamping this. 

> Reviewed 1 of 1 files at r1, 5 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98186#-:-NQ24esU5eSAYdMXbS1s:b2couoj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson)

___
*[`pkg/upgrade/upgrades/system_rbr_indexes.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98186#-NQ23Eej0MIttuvVjyn0:-NQ23Eej0MIttuvVjyn1:b-9vv5uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb24833480fee0a6aced74ca3b1eceda5c9d7f67/pkg/upgrade/upgrades/system_rbr_indexes.go#L35)):*
> ```Go
> // system.sql_instance, and system.lease tables to have a primary index that is
> // binary compatible with a regional by row table. The migration is guarded by
> // four feature flags. The feature flags step the crdb servers through a
> ```

nit: version gates as opposed to feature flags
___
*[`pkg/upgrade/upgrades/system_rbr_indexes.go` line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98186#-NQ25eFH0DwMbU32u5u0:-NQ25eFKC7RINjPH7qis:bkw6cqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb24833480fee0a6aced74ca3b1eceda5c9d7f67/pkg/upgrade/upgrades/system_rbr_indexes.go#L254)):*
> ```Go
> 	oldIndex := migration.keyMapper.OldPrefix()
> 	return deps.DB.KV().Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 		_, err := txn.DelRange(ctx, oldIndex, oldIndex.PrefixEnd(), false /*return keys*/)
> ```

Nobody should be writing to the index at this point, right?
___
*[`pkg/upgrade/upgrades/system_rbr_indexes_test.go` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98186#-NQ25LVY0oL78uCe9Ku5:-NQ25LVZ0-cCVwq7RFEW:b-bcwpem) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb24833480fee0a6aced74ca3b1eceda5c9d7f67/pkg/upgrade/upgrades/system_rbr_indexes_test.go#L105)):*
> ```Go
> 	// Delete old index is expected to remove all kvs from the previous index
> 	// and leave the new index untouched.
> 	// everything in the old index.
> ```

nit: detritus

**Review by jeffswenson — COMMENTED** [review]
I see I missed a few TODOs in the test. I resolved the TODOs that can be handled in this PR. I'll remove remaining TODOs in future PRs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98186#-:-NQ5wHH0900fw3zXetmY:bcg59f1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/upgrade/upgrades/system_rbr_indexes.go` line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98186#-NQ25eFH0DwMbU32u5u0:-NQ5vqS55rK9T2whZk3Q:b-c4itez) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb24833480fee0a6aced74ca3b1eceda5c9d7f67/pkg/upgrade/upgrades/system_rbr_indexes.go#L254)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Nobody should be writing to the index at this point, right?
</blockquote></details>

Correct. This is attached to the clean up version gate which will only run once all servers reach the V23_1_SystemRbrSingleWrite version gate. So servers will only be reading and writing to the new index.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98186#-:-NQ7Ra-C8a2lPtWwgf_o:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
