### PR TITLE
opt: execute Values (no columns), add execbuilder testcases for scalars

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: change Values.ColSet to ColList

Change the column set in Values to a column list.

#### opt: execution for Values with no columns

Build execution for Values when there are no columns. This is useful
for expressions like `SELECT 1`.

Release notes: None

#### opt: add execbuilder testcases for scalars

Adding scalar test cases from the old opt tests.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-L5ATEnHB7M-456w8w6A:-L5ATEnHB7M-456w8w6B:b-idovws) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f70557bd62cc31ff535ae3f299b56284c3222f3/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1)):*
> ```
> # This file tests that we build scalar expressions correctly. We do this by
> ```

Great to see these. Looking through the scalar builder, I think you're missing cases that would exercise some code paths:

NOT, OR, TRUE, FALSE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-:-L5ATqy9EbdcHrZxvf3Q:bnfp4nl)*

**Comment by rytaft** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor_opt_interface.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-L5AW5FYNQwdOqYzgkMI:-L5AW5FYNQwdOqYzgkMJ:b-2c59vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f70557bd62cc31ff535ae3f299b56284c3222f3/pkg/sql/executor_opt_interface.go#L65)):*
> ```Go
> 	values := ee.planner.newContainerValuesNode(sqlbase.ResultColumns{}, len(rows))
> 	for range rows {
> 		if _, err := values.rows.AddRow(context.TODO(), tree.Datums{}); err != nil {
> ```

Why is this adding empty rows? Or am I totally confused...?

---

*[pkg/sql/opt/ops/relational.opt, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-L5ATIn91uhDZ9Ea-Kge:-L5ATIn91uhDZ9Ea-Kgf:b-n1si53) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f70557bd62cc31ff535ae3f299b56284c3222f3/pkg/sql/opt/ops/relational.opt#L38)):*
> ```
> #
> # The Rows field contains a list of Tuples, one for each row. Each tuple has
> # the same length (same with that of Cols).
> ```

If cols is empty, does each Row have 0 length?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor_opt_interface.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-L5AW5FYNQwdOqYzgkMI:-L5AXC0zvCtO65PCX10G:b-lg266f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f70557bd62cc31ff535ae3f299b56284c3222f3/pkg/sql/executor_opt_interface.go#L65)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is this adding empty rows? Or am I totally confused...?
</blockquote></details>

Yeah it only handles 0 columns for now (we only build those kind of ValuesOps).

---

*[pkg/sql/opt/ops/relational.opt, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-L5ATIn91uhDZ9Ea-Kge:-L5AXK2xebmjxetYmxjb:b-phv1nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f70557bd62cc31ff535ae3f299b56284c3222f3/pkg/sql/opt/ops/relational.opt#L38)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

If cols is empty, does each Row have 0 length?
</blockquote></details>

Yes, each is an empty tuple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601)*

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor_opt_interface.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-L5AW5FYNQwdOqYzgkMI:-L5AYR9liynby6XBTx0K:b9uk187) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f70557bd62cc31ff535ae3f299b56284c3222f3/pkg/sql/executor_opt_interface.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah it only handles 0 columns for now (we only build those kind of ValuesOps).
</blockquote></details>

Ah ok I get it now - thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-:-L5AYV7dkXSukNTz_kbq:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 12 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601#-L5ATEnHB7M-456w8w6A:-L5Ab0TduHvIkA6AcpTJ:blfcut8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f70557bd62cc31ff535ae3f299b56284c3222f3/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Great to see these. Looking through the scalar builder, I think you're missing cases that would exercise some code paths:

NOT, OR, TRUE, FALSE
</blockquote></details>

Good list! Added, and fixed some bugs that were uncovered. Also enabled normalization rules (we were running with OptimizeNone).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601)*

**Comment by rytaft** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22601)*

**Pull request merged**
