### PR TITLE
release-20.2: server: add diagnostics support for tenants

### PR DESCRIPTION
**Pull request by andy-kimball**
Backport 2/2 commits from #58399.

/cc @cockroachdb/release

---

Previously, SQL-only tenants did not report feature usage to the registration
server. This commit adds that support via the creation of a new diagnostics
package that encapsulates the usage report code in updates.go.

However, since this commit needs to be backported to 20.2, the new code is
*only* used with tenants, and is side-by-side with the existing code, which
will continue to operate as before. A follow-on commit (that will not be
backported) will fully replace the old implementation with the new.

Release note (sql change): Multi-tenant clusters will now send anonymous usage
information to the central CRDB registration server.

### CODE REVIEW

**Comment by tbg** [comment]
Clean backport, right?

An extra commit (roachtest) seems to have snuck in; if you wanted to backport that implicitly a) probably better in a separate PR (though I'm ok with it now that it's already here) and b) just mention in the commit msg that it's intentional.

It looks like you caught an import cycle somewhere, so some manual fixup seems to be necessary.

**Comment by andy-kimball** [comment]
Yes, I had to do a bunch of small changes due to various re-factorings that have happened in the 21.1 codebase.

I didn't intend to add that 3rd commit - it seems that was `backport` that did it, I think b/c there was a race condition with a separate PR being only partially merged right at the moment I ran the backport tool. I got rid of that.

**Review by andy-kimball — COMMENTED** [review]
Also, there was one substantive change I made in `PeriodicallyReportDiagnostics`. For this backport, I always run `ReportDiagnostics` rather than testing the `diagnostics.reporting.interval` cluster setting first. You can see the comment in that function explaining why.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58517#-:-MQSjjCwC-Sa8wncpOIF:b-24j9h9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @tbg)

**Review by tbg — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58517)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Pull request merged**
