### PR TITLE
leaktest: print non-closed stoppers

### LINKED ISSUE #51363: kv/kvclient/kvcoord: TestTxnCoordSenderCondenseLockSpans failed
[(kv/kvclient/kvcoord).TestTxnCoordSenderCondenseLockSpans failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2084916&tab=buildLog) on [master@12b58af06d9104bc585bc0773bbe29d68ff2d826](https://github.com/cockroachdb/cockroach/commits/12b58af06d9104bc585bc0773bbe29d68ff2d826):

```
=== RUN   TestTxnCoordSenderCondenseLockSpans
    TestTxnCoordSenderCondenseLockSpans: test_log_scope.go:77: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestTxnCoordSenderCondenseLockSpans297602311
    TestTxnCoordSenderCondenseLockSpans: test_log_scope.go:58: use -show-logs to present logs inline


ERROR: exit status 2

31 runs completed, 1 failures, over 19m39s
context canceled

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=2

```
make stressrace TESTS=TestTxnCoordSenderCondenseLockSpans PKG=./pkg/kv/kvclient/kvcoord TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestTxnCoordSenderCondenseLockSpans.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
In https://github.com/cockroachdb/cockroach/issues/51363 we saw
use-after-close of an engine, which I tracked down to `LocalTestCluster`
using more than one stopper (only one of which was actually stopped).

This is likely a larger class of problem, so I added a facility to
ensure that no stoppers are currently active, which is invoked from
leaktest. However, due to the large amount of work that is necessary
to sanitize the whole testing codebase, this is for now only advisory
(i.e. logs, does not error). Nevertheless, this will be useful in tests
in which a use-after-stop actually causes problems.

For the LocalTestCluster, I made sure that the warning is no longer
printed, which mainly entailed not handing a different stopper to the kv
DB than that used for the main server. This explains the failures we
have been seeing, which always involved a KV client request.

Closes #51363.

Release note: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51413#-:-MCObGUNCqaF83ghHnQS:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/testutils/localtestcluster/local_test_cluster.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51413#-MCOaTKDAPqouL_4uLUv:-MCOaTKDAPqouL_4uLUw:b-44zqp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f019f089e3ee2ca52bc64c33b81d9802dd26e/pkg/testutils/localtestcluster/local_test_cluster.go#L115)):*
> ```Go
> 
> 	ltc.tester = t
> 	if ltc.Stopper == nil {
> ```

can `ltc.Stopper` be non-nil? Does someone assign it manually? I don't see anyone doing it. How about passing it in to this `Start()`?
___
*[pkg/util/stop/stopper.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51413#-MCO_hp47aqTBRDXipAL:-MCO_hp47aqTBRDXipAM:b-husw1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f019f089e3ee2ca52bc64c33b81d9802dd26e/pkg/util/stop/stopper.go#L66)):*
> ```Go
> type stopperWithStack struct {
> 	s     *Stopper
> 	stack []byte
> ```

comment this pls or give it a more suggestive name. Can it be a string?

**Comment by tbg** [comment]
PTAL @andreimatei 

I did not add the task yet since I am running out of time (back only on Tuesday). Feel free to add the task separately in another PR. However I think this PR alone will also already help since we're not going to have one-off stoppers active longer than the test servers' any more.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51413#-:-MCSna5W2qqlzXKTqPRO:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51413#-:-MCmcrpb3bAvC4CBqMj5:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51413#-:-MCnF7FO4_BvpF_W0Wbz:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Pull request merged**
