### PR TITLE
tracing: move off opentracing interfaces

### PR DESCRIPTION
**Pull request by tbg**
We were previously shoehorning our tracing subsystem into the
opentracing framework. This resulted in lots of bending over
backwards to no real gain.

Move off the interfaces so that we can more easily refactor
the code for always-on tracing as well as make it more digestible.

This commit is mostly mechanical. A bunch of code around the
RPC interceptors was cribbed from the `otgrpc` package.

Cleanups are delegated to additional commits.

TestFollowerReadsWithStaleDescriptor, skipped temporarily in #55937,
passes again due to the rearrangement in `startSpanGeneric` (we
were setting the spanID too late, which led to tags being dropped).

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@andreimatei no need to review, but I sense that you will like this

**Review by knz — APPROVED** [review]
:lgtm: that's clear thanks

> Reviewed 3 of 3 files at r1, 66 of 66 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56012#-:-MKeAcwuDIsZezh1NECG:b-a13d2e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by irfansharif — APPROVED** [review]
:lgtm: 

https://github.com/cockroachdb/cockroach/pull/56004 should make things clearer in CI but reminder to run `bazel run //:gazelle` (or `make bazel-generate`) after the each commit (rename + new file). We should probably add git commit hooks or something here to do this automatically. Sorry!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56012#-:-MKeZjtg3vdmrXi_Fj4C:bdeylei)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/util/tracing/tracer.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56012#-MKedB1_B8Bj0BSqJ-mM:-MKedB1_B8Bj0BSqJ-mN:b-8khssd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e9be364d6e28f16e5be5ac4dce7f7f1ecde64e7/pkg/util/tracing/tracer.go#L657)):*
> ```Go
> type activeSpanKey struct{}
> 
> func SpanFromContext(ctx context.Context) *Span {
> ```

I think we'll want comments here over this exported method (and below) to avoid linter failures.

**Comment by tbg** [comment]
Nice to see those and happily obliging:

```
  lint_test.go:1504: 
            pkg/util/tracing/span.go:970:16: func (*Span).BaggageItem is unused (U1001)
        lint_test.go:1504: 
            pkg/util/tracing/span.go:980:20: func (*crdbSpan).BaggageItem is unused (U1001)
        lint_test.go:1504: 
            pkg/util/tracing/span.go:992:16: func (*Span).LogEvent is unused (U1001)
        lint_test.go:1504: 
            pkg/util/tracing/span.go:1000:16: func (*Span).LogEventWithPayload is unused (U1001)
        lint_test.go:1504: 
            pkg/util/tracing/span.go:1008:16: func (*Span).Log is unused (U1001)
```

**Comment by tbg** [comment]
bors r=knz,irfansharif

**Pull request merged**
