### PR TITLE
ci: bazelize nightly pebble ycsb, write-throughput benchmarks

### PR DESCRIPTION
**Pull request by rickystewart**
We still have to take care of the metamorphic nightly.

Part of #67335.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Ran these successful test nightlies:

* https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PebbleNightlyYcsbTesting/4098665
* https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PebbleNightlyWriteThroughputTesting/4098683

When this PR is merged I'll update the actual nightly build configurations accordingly:

* remove the "run step within Docker container" parameter (the script now calls into `run_bazel` directly which will use its own Docker container)
* Update the scripts for the YCSB and Write Throughput build configurations to point to their new locations, `build/teamcity/cockroach/nightlies/pebble_nightly_ycsb.sh` and `build/teamcity/cockroach/nightlies/pebble_nightly_write_throughput.sh` respectively.

This will be a breaking change but since we only have to run the nightlies on the latest `master` it should be a seamless transition.

**Review by nicktrav — APPROVED** [review]
:lgtm: Thank you!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74693#-:-MtEBvRH5VCp1L2oFpJT:b-ae66e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
Thank you Nick!

bors r=nicktrav

**Comment by rickystewart** [comment]
I've updated the build configurations for these two nightlies.

**Pull request merged**
