### PR TITLE
sql: Support ALTER DEFAULT PRIVILEGES FOR ALL ROLES

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change): Add support for alter default privileges for all roles

The syntax supported is
ALTER DEFAULT PRIVILEGES FOR ALL ROLES grant_default_privs_stmt/revoke_default_privs_stmt
Only admins are able to execute this.

This allows support for adding default privileges for objects that are created
by ANY role as opposed to having to specify a creator role which the default privileges
will apply to when creating an object.

Example:
ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT SELECT ON TABLES TO foo;

Regardless of whichever user now creates a table in the current database,
foo will have select.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice, this is looking good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-:-MfnxJzv-voDG7ToST_5:b-q3vcm4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RichardJCai)

___
*[pkg/sql/alter_default_privileges.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-MfnvoVhB61sZcU4Q76_:-MfnvoVhB61sZcU4Q76a:blaxsrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3512d2898fd8342af8636fbdfbbd35763ddf495f/pkg/sql/alter_default_privileges.go#L71)):*
> ```Go
> 	if !n.n.ForAllRoles && len(n.n.Roles) == 0 {
> 		targetRoles = append(targetRoles, params.p.User())
> 	} else {
> ```

is this `else` branch still correct now? should it be this instead?

```
if n.n.ForAllRoles {
  ...
} else if len(n.n.Roles) == 0 {
  ...
} else {
 ...
}
```
___
*[pkg/sql/alter_default_privileges.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-Mfnw1rRBAP0U6BWyg--:-Mfnw1rRBAP0U6BWyg-0:b71otta) ([raw file](https://github.com/cockroachdb/cockroach/blob/3512d2898fd8342af8636fbdfbbd35763ddf495f/pkg/sql/alter_default_privileges.go#L108)):*
> ```Go
> 
> 	if n.n.ForAllRoles {
> 		hasAdminRole, err := params.p.HasAdminRole(params.ctx)
> ```

nit: use `p.RequireAdminRole` instead, it creates the error for you
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-MfnwvfDAqXY6P6jtyFB:-MfnwvfDAqXY6P6jtyFC:b-rvw15v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3512d2898fd8342af8636fbdfbbd35763ddf495f/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles#L95)):*
> ```
> test           public       t6          testuser2  ALL
> 
> # Revoking from the current role should not affect the default privileges
> ```

nit: instead of "current role" should it say "target roles" or something?
___
*[pkg/sql/logictest/testdata/logic_test/bytes, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-Mfnx7OzE5PwRyaGrFGN:-Mfnx7OzE5PwRyaGrFGO:b-nmwe36) ([raw file](https://github.com/cockroachdb/cockroach/blob/3512d2898fd8342af8636fbdfbbd35763ddf495f/pkg/sql/logictest/testdata/logic_test/bytes#L156)):*
> ```
> EXECUTE r1('abc')
> ----
> \022^\012\011defaultdb\0202\032\035\012\011\012\005admin\020\002\012\010\012\004root\020\002\022\004root\030\002"\000(\001@\000J\000Z(\022\010\010\001\022\004\022\000\030\000\022\010\010\002\022\004\022\000\030\000\022\010\010\003\022\004\022\000\030\000\022\010\010\004\022\004\022\000\030\000
> ```

do you know what's up with this change?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68076)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/alter_default_privileges.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-MfnvoVhB61sZcU4Q76_:-MfoJIshETyWDGQ2do7r:bfydin5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3512d2898fd8342af8636fbdfbbd35763ddf495f/pkg/sql/alter_default_privileges.go#L71)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this `else` branch still correct now? should it be this instead?

```
if n.n.ForAllRoles {
  ...
} else if len(n.n.Roles) == 0 {
  ...
} else {
 ...
}
```
</blockquote></details>

Yeah we don't have to check `len(n.n.Roles) == 0` since it's handled above when creating targetRoles

```
	var targetRoles []security.SQLUsername
	if !n.n.ForAllRoles && len(n.n.Roles) == 0 {
		targetRoles = append(targetRoles, params.p.User())
	} else {
		for _, role := range n.n.Roles {
			user, err := security.MakeSQLUsernameFromUserInput(string(role), security.UsernameValidation)
			if err != nil {
				return err
			}
			targetRoles = append(targetRoles, user)
		}
	}
```

The current user is already added in
___
*[pkg/sql/logictest/testdata/logic_test/bytes, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-Mfnx7OzE5PwRyaGrFGN:-MfoJg_v9I7bXc2RfT5m:b-6ozz8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3512d2898fd8342af8636fbdfbbd35763ddf495f/pkg/sql/logictest/testdata/logic_test/bytes#L156)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know what's up with this change?
</blockquote></details>

It's because we add a field to the descriptor.
```
subtest Regression_4312

statement ok
PREPARE r1(bytes) AS SELECT descriptor::STRING FROM system.descriptor WHERE descriptor != $1 ORDER BY descriptor DESC LIMIT 1

query T
EXECUTE r1('abc')
----
\022^\012\011defaultdb\0202\032\035\012\011\012\005admin\020\002\012\010\012\004root\020\002\022\004root\030\002"\000(\001@\000J\000Z(\022\010\010\001\022\004\022\000\030\000\022\010\010\002\022\004\022\000\030\000\022\010\010\003\022\004\022\000\030\000\022\010\010\004\022\004\022\000\030\000
```

**Review by rafiss — APPROVED** [review]
lgtm!

> Reviewed 10 of 12 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68076#-:-Mg6cGCA1f20ctLJyKW7:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

**Comment by RichardJCai** [comment]
Thanks!
bors r=rafiss

**Pull request merged**
