### PR TITLE
Return immediately when a local key is found in truncate()

### PR DESCRIPTION
**Pull request by kkaneda**
I'm not sure this is a right fix (and whether this scenario can happen in practice), but `truncate()` currently truncates a local key to a non-local key when the key is outside of [from, to), but within the descriptor.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/2885)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Good catch - the use of `desc` is wrong. It should always truncate to the intersection between `[from, to)` and the descriptor's key range. That the descriptor is even used there is incorrect. Could you fix it up? Possibly we don't even want to pass the descriptor in. You could have a `type window struct { from, to RKey }` with an attached method `intersect(*roachpb.RangeDescriptor`) window` which would replace `from, to` and the caller passes `window.intersect(curDesc)` instead. Does it make sense?

**Comment by kkaneda** [comment]
Ah, I see. Sure, will fix!

**Comment by kkaneda** [comment]
Sent #2916 for refactoring. Will work on the actual fix after that.

**Comment by tschottdorf** [comment]
Kenji, I'm closing this one. Let me know if that was premature.

**Comment by kkaneda** [comment]
Ah, yes. Sounds good! Will reopen once it's ready.

**Pull request closed without merging**
