### PR TITLE
sql: remove a redundant allocation when planning table readers

### PR DESCRIPTION
**Pull request by yuzefovich**
In 594ed7b we refactored the logic of
populating a map from ordinals to column IDs slightly and introduced
a redundant allocation when no system columns are requested. Namely, if
`returnMutations` variable is true (which it often is), then we include
all columns into the mapping, including the system columns. However,
because system columns have very large IDs, this would force an
allocation in `util.FastIntMap`. This commit removes that allocation in
case when the system columns are not requested.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24       231µs ± 3%     228µs ± 4%     ~     (p=0.274 n=8+10)
FlowSetup/vectorize=true/distribute=false-24      250µs ±20%     215µs ± 3%  -13.95%  (p=0.000 n=10+9)
FlowSetup/vectorize=false/distribute=true-24      225µs ±13%     216µs ± 5%     ~     (p=0.912 n=10+10)
FlowSetup/vectorize=false/distribute=false-24     205µs ± 8%     207µs ± 3%     ~     (p=0.579 n=10+10)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      34.4kB ± 1%    33.2kB ± 2%   -3.50%  (p=0.000 n=9+9)
FlowSetup/vectorize=true/distribute=false-24     32.5kB ± 0%    31.3kB ± 1%   -3.74%  (p=0.000 n=8+8)
FlowSetup/vectorize=false/distribute=true-24     40.1kB ± 4%    38.3kB ± 0%   -4.61%  (p=0.000 n=10+8)
FlowSetup/vectorize=false/distribute=false-24    37.7kB ± 0%    36.5kB ± 0%   -3.13%  (p=0.000 n=8+9)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         270 ± 0%       268 ± 0%   -0.74%  (p=0.000 n=8+8)
FlowSetup/vectorize=true/distribute=false-24        256 ± 0%       254 ± 0%   -0.78%  (p=0.000 n=8+8)
FlowSetup/vectorize=false/distribute=true-24        261 ± 0%       259 ± 0%   -0.73%  (p=0.000 n=8+9)
FlowSetup/vectorize=false/distribute=false-24       247 ± 0%       245 ± 0%   -0.81%  (p=0.000 n=8+8)
```
This was a regression that is present on all 21.1.x and 21.2.x releases, and it seems as a very low risk to fix that I'm thinking that we might wanna backport to both of those branches. Thoughts?

**Review by postamar — APPROVED** [review]
LGTM. I wonder how you came up with this, but it's rather neat.

I strongly recommend you don't bother backporting this. Even if the likelihood of trouble is very low, the potential trouble here is precious engineering time wasted. It's never worth it. Hence the backport policy, I'd guess.

**Review by yuzefovich — COMMENTED** [review]
Makes sense, let's not backport this. I noticed the mysterious allocations in `util.FastIntMap` when looking at the profile of `BenchmarkFlowSetup` (which reads from a table with two columns), so I looked closer and found this inefficiency.

I've just refactored the change slightly given that #72676 has been merged recently. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72673#-:-MoKelqJ5sKsQCQusTee:b-1qbkym)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Actually, nvm. I like my original change better.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72673#-:-MoKjppz7j_qj0HsXUQr:b-eyx3u6)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
