### PR TITLE
roachpb: MergeSpans doesn't use an out parameter

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8315)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: Good cleanup.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315#-:-KOH_2Up9BO4ZSqKQwNK:2143294174)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/merge_spans.go, line 44 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315#-KOH_a9OWEcR6UJk6EBi:-KOH_a9OWEcR6UJk6EBj:539592119) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d3a19574045ace416406d966db0148dfc1a7e3/roachpb/merge_spans.go#L44)):*
> ```Go
> // MergeSpans sorts the incoming spans and merges overlapping spans. Returns
> // true iff all of the spans are distinct.
> func MergeSpans(spans []Span) ([]Span, bool) {
> ```

Mention in the comment that it modifies the input `[]Span` in place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/merge_spans.go, line 44 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315#-KOH_a9OWEcR6UJk6EBi:-KOH_lvO2vc_a0xyzFY-:1186400070) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d3a19574045ace416406d966db0148dfc1a7e3/roachpb/merge_spans.go#L44)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Mention in the comment that it modifies the input `[]Span` in place.
</details>
I'll do it in the next PR #8313 unless tests fail here, if that's OK with you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/merge_spans.go, line 44 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315#-KOH_a9OWEcR6UJk6EBi:-KOHaOvSu6VgygTkvmIl:677087930) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d3a19574045ace416406d966db0148dfc1a7e3/roachpb/merge_spans.go#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'll do it in the next PR #8313 unless tests fail here, if that's OK with you.
</details>
Sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315)*

**Comment by tamird** [comment]
Actually, the comment already says it sorts the argument, which implies in-place modification.

**Comment by RaduBerinde** [comment]
It's not 100% clear, it could sort them into a new slice, can't hurt mentioning it explicitly (it was a bit more suggestive before since we were passing a pointer).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315#-:-KOHhKENIVPNF9gteH4a:308024818)*

**Comment by bdarnell** [comment]
Yeah, taking a pointer implies in-place modification. Returning a slice implies that the input slice is left alone. If we return a slice but also trash the input slice, this needs to be called out explicitly. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8315#-:-KOIQVW6yhmMpGWkZWNw:2103570370)*

**Comment by tamird** [comment]
Done in #8313.

**Pull request merged**
