### PR TITLE
sql: add ALTER FUNCTION support

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
There're 4 commits matters:
(1) alter function options
(2) alter function rename
(3) alter function owner
(4) alter function set schema

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85942)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/alter_function.go` line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9IaKH-AxpFkRz-D_Ww:-N9IaKH-AxpFkRz-D_Wx:b-u4h7ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0382ae034b51a239d9792ce85c0ba3b726d45b2/pkg/sql/alter_function.go#L128)):*
> ```Go
> 	}
> 
> 	return params.p.writeSchemaDescChange(params.ctx, scDesc, "Alter Function Name")
> ```

nit: can you make this lowercase and do the same for `Create Function`? 
___
*[`pkg/sql/resolver.go` line 1181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9Ib4jC99Pbqd6vAkC5:-N9Ib4jC99Pbqd6vAkC6:b-t73zdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/809ee7f636562df04402948f185fe121ec743d9f/pkg/sql/resolver.go#L1181)):*
> ```Go
> }
> 
> func getFuncNameFromFuncDescriptor(
> ```

nit: `getFunctionNameFromFunctionDescriptor`?
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9Ib-RJD2Fy74-SfnuW:-N9Ib-RJD2Fy74-SfnuX:b-qnb2re) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0382ae034b51a239d9792ce85c0ba3b726d45b2/pkg/sql/catalog/funcdesc/func_desc.go#L456)):*
> ```Go
> 
> // ToFuncObj converts the descriptor to a tree.FuncObj.
> func (desc *immutable) ToFuncObj() tree.FuncObj {
> ```

nit: I'm realizing I don't like `FuncObj` type name. 
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 1236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9I_oEREaznO8Rt0IAc:-N9I_oEREaznO8Rt0IAd:bi3v82x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0382ae034b51a239d9792ce85c0ba3b726d45b2/pkg/sql/logictest/testdata/logic_test/udf#L1236)):*
> ```
> 
> statement ok
> ALTER FUNCTION f_test_alter_name RENAME to f_test_alter_name_new
> ```

nit: you capitalized everything but this `to` and one below, not that it matters
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9IbDR86PklEok0dn3r:-N9IbDR86PklEok0dn3s:b-ln9x24) ([raw file](https://github.com/cockroachdb/cockroach/blob/809ee7f636562df04402948f185fe121ec743d9f/pkg/sql/logictest/testdata/logic_test/udf#L1299)):*
> ```
> 
> statement ok
> ALTER FUNCTION f_test_alter_owner OWNER TO u_test_owner;
> ```

What does `DROP OWNED BY` do in this case? Also, `REASSIGN OWNED BY`?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85942)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/alter_function.go` line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9IaKH-AxpFkRz-D_Ww:-N9IgVzl9HAMvqfRUC5K:byda4cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0382ae034b51a239d9792ce85c0ba3b726d45b2/pkg/sql/alter_function.go#L128)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: can you make this lowercase and do the same for `Create Function`? 
</blockquote></details>

sounds good. fix, I'll do the same for `create function` in the other pr for `replace function`.
___
*[`pkg/sql/resolver.go` line 1181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9Ib4jC99Pbqd6vAkC5:-N9Ig3LS6ubrCWEPqZZw:b-tzt3k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/809ee7f636562df04402948f185fe121ec743d9f/pkg/sql/resolver.go#L1181)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: `getFunctionNameFromFunctionDescriptor`?
</blockquote></details>

good suggestion, I forgot where I got the habit of using short names :(
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9Ib-RJD2Fy74-SfnuW:-N9Ie_2rEsY-izXNTzdD:bvbec09) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0382ae034b51a239d9792ce85c0ba3b726d45b2/pkg/sql/catalog/funcdesc/func_desc.go#L456)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I'm realizing I don't like `FuncObj` type name. 
</blockquote></details>

heh... sorry that you don't like it, how about `FunctionSignature`? (I'd like to do it in a separate PR though, need to touch the parser and affecting other prs)
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 1236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9I_oEREaznO8Rt0IAc:-N9IgCLV9yLJgMhRW5hr:b-kl8g3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0382ae034b51a239d9792ce85c0ba3b726d45b2/pkg/sql/logictest/testdata/logic_test/udf#L1236)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: you capitalized everything but this `to` and one below, not that it matters
</blockquote></details>

good catch.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9IbDR86PklEok0dn3r:-N9IerfQ8cUrTQc4m3oT:b4izbo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/809ee7f636562df04402948f185fe121ec743d9f/pkg/sql/logictest/testdata/logic_test/udf#L1299)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What does `DROP OWNED BY` do in this case? Also, `REASSIGN OWNED BY`?
</blockquote></details>

Sadly `DROP OWNED BY` would fall back to the legacy schema changer and it's unimplemented >_> I think I need to support drop function in declarative some time soon.
And TIL we have `REASSIGN OWNED BY`, I need to fix that, luckily it's not too bad adding that. Fixed and added a test for that. Thanks for the good catch.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-:-N9Im7Ym0xR65XFZnhS0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9Ib-RJD2Fy74-SfnuW:-N9Im3jT6S6uuzcTCjXY:b-606tuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0382ae034b51a239d9792ce85c0ba3b726d45b2/pkg/sql/catalog/funcdesc/func_desc.go#L456)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

heh... sorry that you don't like it, how about `FunctionSignature`? (I'd like to do it in a separate PR though, need to touch the parser and affecting other prs)
</blockquote></details>

Yeah, definitely fine fore later. 
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85942#-N9IbDR86PklEok0dn3r:-N9IlqNZ-KvFsYxB3SZC:b-3fcxqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/809ee7f636562df04402948f185fe121ec743d9f/pkg/sql/logictest/testdata/logic_test/udf#L1299)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Sadly `DROP OWNED BY` would fall back to the legacy schema changer and it's unimplemented >_> I think I need to support drop function in declarative some time soon.
And TIL we have `REASSIGN OWNED BY`, I need to fix that, luckily it's not too bad adding that. Fixed and added a test for that. Thanks for the good catch.
</blockquote></details>

:thumbsup: I'm cool with an unimplemented error as long as it's reasonably clear.

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
