### PR TITLE
sql: fix validation for multi-region enums and create array type alias

### PR DESCRIPTION
**Pull request by arulajmani**

### CODE REVIEW

**Review by otan — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57194)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @otan, and @pbardea)

___
*[pkg/sql/create_database.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57194#-MNKVe0i5rRBO3sFqmX-:-MNKVe0i5rRBO3sFqmX0:b-m6ehaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e0f7cb5beabeac8ef46b1e22f5270e99cafbf9/pkg/sql/create_database.go#L130)):*
> ```Go
> func (*createDatabaseNode) Values() tree.Datums          { return tree.Datums{} }
> func (*createDatabaseNode) Close(context.Context)        {}
> func (n *createDatabaseNode) ReadingOwnWrites()          {}
> ```

nit: remove `n *`
add comment about why this is required (i.e. CREATE ENUM)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57194)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @otan, and @pbardea)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57194#-MNKd-2a2QWUzJuNnf76:-MNKd-2b2GMIVm1vVMa5:bty2qqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d39be0da74fce0622d770f1c2fba46e237852f/pkg/sql/logictest/testdata/logic_test/multiregion#L29)):*
> ```
> 56        29              region  57
> 59        29              region  60
> ```

can you also add a `SHOW ENUMS` test in here?

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57194)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @otan, and @pbardea)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57194#-MNO9-Wu-UV2OAOgQpA5:-MNO9-Wu-UV2OAOgQpA6:b-yd5aya) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e0f7cb5beabeac8ef46b1e22f5270e99cafbf9/pkg/sql/catalog/typedesc/type_desc.go#L448)):*
> ```Go
> 	// Validate the parentID.
> 	reqs = append(reqs, desc.ParentID)
> 	checks = append(checks, func(got catalog.Descriptor) error {
> ```

Did we also want to validate that the regions in the database descriptor match the values in the enum?  And that the primary region matches?

**Review by arulajmani — COMMENTED** [review]
Addressed comments + added another commit to enhance our multi-region validation. RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57194#-:-MNPza_m6Caqwfo0fXkk:bqo2nza)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @pbardea)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57194#-MNO9-Wu-UV2OAOgQpA5:-MNPzOi_0tFPaI7gCutP:bh5k9l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e0f7cb5beabeac8ef46b1e22f5270e99cafbf9/pkg/sql/catalog/typedesc/type_desc.go#L448)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Did we also want to validate that the regions in the database descriptor match the values in the enum?  And that the primary region matches?
</blockquote></details>

We currently don't store the primary region on the type descriptor -- working on that as a followup, but I've added some more multi-region validation for everything else in a new commit. 
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57194#-MNKd-2a2QWUzJuNnf76:-MNOyiKcAssvOSdrPSE8:b-a13ee9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d39be0da74fce0622d770f1c2fba46e237852f/pkg/sql/logictest/testdata/logic_test/multiregion#L29)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you also add a `SHOW ENUMS` test in here?
</blockquote></details>

It's in the other PR (#57197)

**Review by ajstorm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57194)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @pbardea)

**Comment by arulajmani** [comment]
TFTRs! 

bors r=otan,ajstorm

**Pull request merged**
