### PR TITLE
kv/multitenant: skip TestExplainMVCCSteps, TestTransientClusterMultitenant, TestDockerCLI/test_sql_mem_monitor

### PR DESCRIPTION
**Pull request by msbutler**
Informs #94862 #94881 https://github.com/cockroachdb/cockroach/issues/94887

Release Note: none

Epic: none

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]

**Comment by msbutler** [comment]
bors r=erikgrinaker

**Comment by msbutler** [comment]
also skipping the flakey TestDockerCLI/test_sql_mem_monitor, tracked in https://github.com/cockroachdb/cockroach/issues/94887

**Comment by msbutler** [comment]
bors r=erikgrinaker

**Pull request merged**
