### PR TITLE
storage: reduce memory allocations in intentInterleavingIter

### PR DESCRIPTION
**Pull request by sumeerbhola**
The memory allocations for computing the bounds for the
EngineIterator were 33% of the memory allocations in
batcheval.Scan in a joinReader benchmark (the rest, as
expected, is in pebbleResults for storing the result
of the scan). These allocations were 6% of the cpu in
MVCCScanToBytes in the same benchmark.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62984#-:-MXDZ7pm9QEdLJpEQl0g:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm: this optimization is being pulled out from https://github.com/cockroachdb/cockroach/pull/61401, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62984#-:-MXDeZKz2buc1azHC3OP:b7bxl9k)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by sumeerbhola — COMMENTED** [review]
> this optimization is being pulled out from #61401, right?

correct

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62984#-:-MXE67X436uP5uU1JpGO:bclw52t)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62984#-:-MXE6A8cCbUlvBQmm0pB:b-814g8k)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal)

**Pull request merged**
