### PR TITLE
sql/parser: split parser.DTuple into parser.DTuple and parser.Datums

### LINKED ISSUE #12295: sql: IN is broken for computed tuples
What did I do:
```
root@:26257> select 'foo' in (x, null) from (select 'foo' as x);
+--------------------+
| 'foo' IN (x, NULL) |
+--------------------+
| false              |
+--------------------+
```

This fails because of the smartness introduced in aa5dd437a8f3643bf5764f3b5a026bdd504c10f5: this "in comparison" implementation with tuples on the right assumes the tuples are sorted; however tuple sorting only occurs during expression normalization, assuming that all the tuple elements are known already. If there is a column reference in there, the sort doesn't do what it should, and the `sort.Search` doesn't find what it should either.

(Compare with `SELECT 'foo' IN (NULL, x)` which does work)

### LINKED ISSUE #12302: sql: IN does not return NULL in situations where PG would
From https://www.postgresql.org/docs/9.0/static/functions-subquery.html#AEN16806
> Note that if the left-hand expression yields null, or if there are no equal right-hand values and at least one right-hand row yields null, the result of the IN construct will be null, not false. This is in accordance with SQL's normal rules for Boolean combinations of null values.

In Cockroach:
```
root@:26257> SELECT 1 IN (2, NULL);
+----------------+
| 1 IN (2, NULL) |
+----------------+
| false          |
+----------------+
```

In PG:
```
nathan=# SELECT 1 IN (2, NULL);
 ?column?
----------

```

This rule is identical to logic added in #12102, so I'll fix it once that change goes through.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #12295.
Fixes #12302.

This change begins by creating a new type (temporarily) called `parser.DTupleDatum`
that replaces `parser.DTuple` as the `Datum` implementation for a tuple
of `Datum` values. `parser.DTuple` remains a slice of `Datum` values but
no longer implements the interface itself. Meanwhile `parser.DTupleDatum`
is introduced as a struct holding onto a `parser.DTuple` that does
implement the interface.

The reason for this distinction is so that we can later add extra state
to `parser.DTupleDatum` that is specific to the `Datum` type but would
be extraneous for a simple list of Datums (`parser.DTuple`) to worry about.
For instance, these additional fields will include normalization state.
Because most uses of `parser.DTuple` were actually only interested in a
"datum container", the proliferation of `parser.DTupleDatum` is fairly
contained.

Next, it performs the following renaming using `gorename`:
- `parser.DTuple -> parser.Datums`
- `parser.DTupleDatum -> parser.DTuple`

Once this refactoring is completed, the change resolved the two referenced
issues by adding extra state to `parser.DTuple`, which is now a struct. The
two issues fixed are:
- unnormalized Tuples are now evaluated correctly by IN
- tuples with NULL values are now evaluated correctly by IN

@petermattis might also be interested in this change.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13444)

### CODE REVIEW

**Comment by knz** [comment]
1st commit lgtm with nit

---

Reviewed 13 of 13 files at r1.
Review status: 0 of 64 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 1634 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOmglajG5oEhA2ag51:-KcOmglajG5oEhA2ag52:badpevd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fbd27cce2e43a9bc8a926f685293019ae110e70/pkg/sql/parser/datum.go#L1634)):*
> ```Go
> }
> 
> func (d *DTupleDatum) Len() int           { return d.D.Len() }
> ```

Why does DTupleDatum need to implement this interface? I thought only DTuple had to (for sorting)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcOnHLuZcAWJpvg1KHV:bt9j505)*

**Comment by knz** [comment]
2nd commit lgtm

---

Reviewed 58 of 58 files at r2.
Review status: 52 of 64 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcOocdR36E3wb0JF691:bvezcio)*

**Comment by knz** [comment]
3rd commit lgtm

---

Reviewed 13 of 13 files at r3.
Review status: 58 of 64 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcOpHwSAFEOws5eNn6H:bmwjwt9)*

**Comment by knz** [comment]
4th commit can be smarter about subqueries right away. Will need a test though.

---

Reviewed 5 of 5 files at r4.
Review status: 60 of 64 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/subquery.go, line 112 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOpmZtWmYb9pICdeRu:-KcOpmZtWmYb9pICdeRv:blxhhfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3704bb7ad609ce64b244044af54cf1020db2407/pkg/sql/subquery.go#L112)):*
> ```Go
> 
> 	// TODO(nvanbenschoten/knz) If we know that a DTuple created here has been
> 	// sorted in ascending order, we can set its Sorted flag using DTuple.SetSorted.
> ```

But we know this I think, via `s.plan.Ordering()`. Can you check please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcOqVZpAIbyt-s1-bcg:bmjl4w0)*

**Comment by knz** [comment]
5th commit OK but probably would need an extra comment.

---

Reviewed 3 of 3 files at r5.
Review status: 62 of 64 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 1673 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOqr6q4g2ciQd51h14:-KcOqr6rkrONwhz79o0B:b-91s5me) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89191526d74c37dc1a6de32a4f9b53c286864e9/pkg/sql/parser/datum.go#L1673)):*
> ```Go
> 	n := 0
> 	for i := 0; i < len(d.D); i++ {
> 		if d.D[i] == DNull {
> ```

Maybe that's an old bug that was lurking here, but why do we remove NULL's here? Is that because this function is only used for IN and IN never "finds" NULLs? If so, that needs a comment (and perhaps a cursory check throughout the source that makeUnique is indeed only used for that purpose.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcOrIEL8yz2M0E09N5j:b1ebl8a)*

**Comment by knz** [comment]
6th commit lgtm

Great work overall. I am impressed.

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcOrSEPxrMj9zlRqFVs:bwlh9qg)*

**Comment by nvanbenschoten** [comment]
Thanks for the review!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/subquery.go, line 112 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOpmZtWmYb9pICdeRu:-KcQgAR-4s2wNEb_gyqi:bljbekz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3704bb7ad609ce64b244044af54cf1020db2407/pkg/sql/subquery.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

But we know this I think, via `s.plan.Ordering()`. Can you check please.
</blockquote></details>

I have a  version with this working in some regards, but it's not a fully-working implementation. The issue is that `s.plan.Ordering()` gives us information about the columns that need to be sorted using selected indexes. Instead, what we want is information about which columns we know will be sorted in the output of the plan node, and in which directions we know they will be sorted in. 

The distinction is subtle but important for cases like `SELECT 1 ORDER BY 1`. Here we know that the first column can be considered sorted in both an ascending and descending order. However, even with the `ORDER BY` clause, we will notice in `sort.go` that no sorting is needed and `s.plan.Ordering()` will be empty. Another example is `SELECT pk, secondary FROM t ORDER BY 1, 2`. Because we know the pk will be unique, it looks like we remove the second `ordering` from `s.plan.Ordering()`. What we really need is some kind of `plan.OrderingProperties()` method targetted at consumers of the planNode.

---

*[pkg/sql/parser/datum.go, line 1634 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOmglajG5oEhA2ag51:-KcPgPixLUb8DgnHwqD0:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fbd27cce2e43a9bc8a926f685293019ae110e70/pkg/sql/parser/datum.go#L1634)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why does DTupleDatum need to implement this interface? I thought only DTuple had to (for sorting)
</blockquote></details>

Good point. Done.

---

*[pkg/sql/parser/datum.go, line 1673 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOqr6q4g2ciQd51h14:-KcQqV_VTZ0RByxAGTXf:bpiamm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89191526d74c37dc1a6de32a4f9b53c286864e9/pkg/sql/parser/datum.go#L1673)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe that's an old bug that was lurking here, but why do we remove NULL's here? Is that because this function is only used for IN and IN never "finds" NULLs? If so, that needs a comment (and perhaps a cursory check throughout the source that makeUnique is indeed only used for that purpose.)
</blockquote></details>

Yeah, it looks like that was introduced in https://github.com/cockroachdb/cockroach/commit/1fc898a846b50064411f30eb05b7bec87edffa02. After thinking about it more and after understanding why this was done in the first place, I don't think it's needed. I ripped out the `NullRemoved` flag and just allow the single NULL to be sorted to the front of the tuple. This makes handling it easier in a few places. PTAL @ commit 5.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcPgdYW4niHcBrj2lan:b-9qdoz3)*

**Comment by knz** [comment]
:lgtm_strong: with a request for filing an issue

---

Reviewed 51 of 58 files at r8, 8 of 13 files at r9, 2 of 5 files at r10, 5 of 6 files at r11, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/subquery.go, line 112 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOpmZtWmYb9pICdeRu:-KcRUhtYBUhF115YoAEb:bp84sbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3704bb7ad609ce64b244044af54cf1020db2407/pkg/sql/subquery.go#L112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I have a  version with this working in some regards, but it's not a fully-working implementation. The issue is that `s.plan.Ordering()` gives us information about the columns that need to be sorted using selected indexes. Instead, what we want is information about which columns we know will be sorted in the output of the plan node, and in which directions we know they will be sorted in. 

The distinction is subtle but important for cases like `SELECT 1 ORDER BY 1`. Here we know that the first column can be considered sorted in both an ascending and descending order. However, even with the `ORDER BY` clause, we will notice in `sort.go` that no sorting is needed and `s.plan.Ordering()` will be empty. Another example is `SELECT pk, secondary FROM t ORDER BY 1, 2`. Because we know the pk will be unique, it looks like we remove the second `ordering` from `s.plan.Ordering()`. What we really need is some kind of `plan.OrderingProperties()` method targetted at consumers of the planNode.
</blockquote></details>

Ok, so the version you have works when the ordering information is available, right? Then I suggest that you do that, and file an issue (assigned to me) to request that the ordering information be preserved even during optimizations instead of deleted. That would be fair and would not break all the things. Radu was actually asking for the same yesterday for distsql, so the request is legit.

---

*[pkg/sql/parser/datum.go, line 1673 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOqr6q4g2ciQd51h14:-KcRVIHgnFRwUShRzXvW:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89191526d74c37dc1a6de32a4f9b53c286864e9/pkg/sql/parser/datum.go#L1673)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, it looks like that was introduced in https://github.com/cockroachdb/cockroach/commit/1fc898a846b50064411f30eb05b7bec87edffa02. After thinking about it more and after understanding why this was done in the first place, I don't think it's needed. I ripped out the `NullRemoved` flag and just allow the single NULL to be sorted to the front of the tuple. This makes handling it easier in a few places. PTAL @ commit 5.
</blockquote></details>

ack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-:-KcRVK-6_WZWST0MscyA:bwabftr)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 66 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/subquery.go, line 112 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444#-KcOpmZtWmYb9pICdeRu:-KcRqiHdw8dHjw-qoq3K:b-ivk9g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3704bb7ad609ce64b244044af54cf1020db2407/pkg/sql/subquery.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok, so the version you have works when the ordering information is available, right? Then I suggest that you do that, and file an issue (assigned to me) to request that the ordering information be preserved even during optimizations instead of deleted. That would be fair and would not break all the things. Radu was actually asking for the same yesterday for distsql, so the request is legit.
</blockquote></details>

Done. Filed #13476.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13444)*

**Pull request merged**
