### PR TITLE
cluster: remove legacy version upgrade tests for auto upgrade merge

### PR DESCRIPTION
**Pull request by ghost**
Legacy tests such as `TestClusterVersionUpgrade1_0To2_0`,
`TestDockerReadWriteBidirectionalReferenceVersion`, and
`TestDockerReadWriteForwardReferenceVersion` no longer applies.

Therefore, we remove and they will be replaced with new roachtests
when the auto upgrade PR #24987 merges.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
I'm fine (happy, actually) removing the docker reference tests, these haven't caught anything in a long time and I've wanted to kill them for a while (#18960).

What is the rationale for removing the unit tests? Yes, the same functionality is exercised by roachtest, but there's value in having a basic sanity check that the upgrade mechanism works (and one that can be stress tested). My suggestion here is to remove all the stuff about Raft tombstones and to populate the `versions` slice automatically (assuming that the binary version is `3.3-6`, it would upgrade from `3.3` to `4.0`). That way, the test won't rot in the future and can be used to test specific migrations that are currently being introduced.

If the auto-upgrade mechanism somehow makes this test unfeasible, we should massage it slightly so that it becomes feasible. I'd be curious to see if there are any problems. (The test should definitely still run quickly, we don't want longer waiting periods here).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/server/version_cluster_test.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25184#-LBVcCYd9NM4Z9D5x05Z:-LBVcCYf2UPSf1AnHtRt:b-db7rq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b7b164b13f1ab7c94083196aaec2a66dffca5a3/pkg/server/version_cluster_test.go#L146)):*
> ```Go
> 	}
> 
> 	// We will put down fake legacy tombstones (#12154) to jog
> ```

I love how you can just delete migration-related tests when the migration isn't "current" any more.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25184#-:-LBVcQofB_7GUFrhCNeV:bn55b87)*

**Comment by bdarnell** [comment]
I agree with @tschottdorf that removing the acceptance test is fine but it would be nice to keep the unit test.

When this is gone, we can also remove the old binaries from the docker image: 

https://github.com/cockroachdb/postgres-test/blob/b1347c055696856624c1a62aeffd0fd3b066695a/Dockerfile#L99-L107

**Comment by windchan7** [comment]
@tschottdorf , want to LGTM this test removal?

**Review by tbg — APPROVED** [review]
LGTM 🔥

**Pull request merged**
