### PR TITLE
migrations: Clean up main_test file

### LINKED ISSUE #14655: teamcity: failed tests on master: check/TestStyle, check/TestStyle/TestErrCheck, check/TestStyle/TestReturnCheck, check/TestStyle/TestMetacheck, acceptance/TestDockerMigration_7429
The following tests appear to have failed:

[#209032](https://teamcity.cockroachdb.com/viewLog.html?buildId=209032):

```
--- FAIL: check/TestStyle (22.920s)
null
--- FAIL: check/TestStyle/TestErrCheck (7.050s)
style_test.go:570: err=exit status 2, stderr=/go/src/github.com/cockroachdb/cockroach/pkg/migrations/main_test.go:28:2: SetReadFileFn not declared by package security
	error: failed to check packages: could not type check: couldn't load packages due to errors: github.com/cockroachdb/cockroach/pkg/migrations_test
--- FAIL: check/TestStyle/TestReturnCheck (8.820s)
style_test.go:594: err=exit status 1, stderr=/go/src/github.com/cockroachdb/cockroach/pkg/migrations/main_test.go:28:2: SetReadFileFn not declared by package security
--- FAIL: check/TestStyle/TestMetacheck (7.050s)
style_test.go:773: err=exit status 1, stderr=/go/src/github.com/cockroachdb/cockroach/pkg/migrations/main_test.go:28:2: SetReadFileFn not declared by package security
	2017/04/06 05:15:51 couldn't load packages due to errors: github.com/cockroachdb/cockroach/pkg/migrations_test
--- FAIL: acceptance/TestDockerMigration_7429 (7.140s)
reference_test.go:41: non-zero exit code: 1
------- Stdout: -------
test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerMigration_7429130250647  (use -show-logs to present inline)
test logs left over in: &{/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerMigration_7429130250647 false}

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by a-robinson**
Maybe this messiness influenced the weird failure in #14655?

Fixes #14655

### CODE REVIEW

**Comment by mberhault** [comment]
definitely LGTM for the security assets part since it wouldn't even build.
Not sure about the other part though.

**Comment by a-robinson** [comment]
The idea is to more closely match the main_test.go file to rpc/main_test.go (another package that the server package depends on) and put main_test.go into the same package as migration_test.go. I think this is how it should have been in the first place.

**Comment by mberhault** [comment]
ok. LGTM on this bit too.

**Comment by mberhault** [comment]
I'm not sure what's going on with the check failures though.

**Comment by tamird** [comment]
This builder looks borked. Did someone run a build with an ancient builder image?

**Comment by a-robinson** [comment]
How do we reset it?

**Pull request merged**
