### PR TITLE
storage: move consistency checksum notification into replicaChecksum

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5348)

### CODE REVIEW

**Comment by tamird** [comment]
looks like code golf, so :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1338 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4ZxGqOncPW5EOXo0C:-KD4ZxGqOncPW5EOXo0D:-1257917959) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1338)):*
perhaps there are some pertinent details that you could include in this panic?

---

*[storage/replica_command.go, line 1423 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_THeKewXvTznVtaF:-KD4_THeKewXvTznVtaG:-1257917959) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1423)):*
perhaps there are some pertinent details that you could include in this panic?

---

*[storage/replica_command.go, line 1524 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_WRM-yWmW1VO9v58:-KD4_WRM-yWmW1VO9v59:-192448389) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1524)):*
unusual error handling (here and above) needs comments.

---

*[storage/replica_test.go, line 4180 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_adfH12zM_hoOnSV:-KD4_adfH12zM_hoOnSW:-877249943) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_test.go#L4180)):*
log the error if it's not nil?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-:-KD4_eJvBKwgQU6PEs-t:829218527)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 156 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4wTdbCA0epf5NyIk7:-KD4wTdbCA0epf5NyIk8:1843744845) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica.go#L156)):*
I think you can remove `ok` now; you can just to a select on the notify channel to determine whether it's been set.

---

*[storage/replica_command.go, line 1338 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4ZxGqOncPW5EOXo0C:-KD4va1D7vKVdmM_IaSS:1019261585) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1338)):*
Does this really merit a panic? Why not pass the error back to the caller?

---

*[storage/replica_command.go, line 1385 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4wAIAN3Gy9m6Ium2j:-KD4wAIByvcimsbEdDPp:-298759997) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1385)):*
No other errors are possible, so why not return `(replicaChecksum, ok bool)` instead of an error and synthesizing a fake return value?

---

*[storage/replica_command.go, line 1386 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4xc6tn-l9TMQ-16fy:-KD4xc6tn-l9TMQ-16fz:-927224846) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1386)):*
You can't distinguish between a GC'd value and one that never existed; I would be less specific in the error message to avoid giving false confidence that this checksum has in fact been GC'd. "checksum %v not found; possibly GC'd"

---

*[storage/replica_command.go, line 1399 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4vxgpFCj5JYBqaBAD:-KD4vxgpFCj5JYBqaBAE:-1999548179) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1399)):*
If the map contained pointers instead of values, you wouldn't have to re-lookup the value here and you could simplify by getting rid of the inner function. 

---

*[storage/replica_command.go, line 1423 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_THeKewXvTznVtaF:-KD4xQz1MmfDFVtZSd-D:1706781841) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1423)):*
And again, is the panic really necessary? It seems better to log an error here and continue. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 156 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4wTdbCA0epf5NyIk7:-KD6V7Zbg4QEV17R1e2V:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica.go#L156)):*
done

---

*[storage/replica_command.go, line 1338 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4ZxGqOncPW5EOXo0C:-KD4dYrQ-J4yaColdbJO:1598467979) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1338)):*
I just return an error now.

---

*[storage/replica_command.go, line 1385 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4wAIAN3Gy9m6Ium2j:-KD6VRYTZknRhuSLpmby:-867764920) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1385)):*
sounds good. Done

---

*[storage/replica_command.go, line 1386 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4xc6tn-l9TMQ-16fy:-KD6YqD4JU7JXQTO4lgc:-221887839) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1386)):*
This code has been deleted

---

*[storage/replica_command.go, line 1399 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4vxgpFCj5JYBqaBAD:-KD6Yv9_BFzfuyR9JHwD:-1067497332) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1399)):*
This entire function has dramatically changed and this comment is no longer relevant.

---

*[storage/replica_command.go, line 1423 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_THeKewXvTznVtaF:-KD4eH4BtA5CLRutmh3l:-1524790146) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1423)):*
@bdarnell it actually cannot happen.

@tamird Not really. I could print the id, but then we would need to add more log messages to fix the problem.

---

*[storage/replica_command.go, line 1524 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_WRM-yWmW1VO9v58:-KD4gdE3HynOsmfJNOvg:-760387177) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1524)):*
Added a comment at the top of the method.

---

*[storage/replica_test.go, line 4180 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_adfH12zM_hoOnSV:-KD4gysWtoSp4K6JkBZd:1751375599) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_test.go#L4180)):*
Not relevant

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[storage/replica.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79JIMHz_0M9tWFxKo:-KD79JIMHz_0M9tWFxKp:-1924399274) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica.go#L148)):*
did you mean to remove this?

---

*[storage/replica_command.go, line 1423 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_THeKewXvTznVtaF:-KD7AiOkQ7vkHnahczOP:-2130750890) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1423)):*
This still doesn't sit well with me. If this panic actually happened we'll be stuck scratching our heads.

---

*[storage/replica_command.go, line 1335 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79W97ZBGj1OKBi1_I:-KD79W97ZBGj1OKBi1_J:-860846884) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1335)):*
weird comment. isn't it the case here that there is no checksum to verify?

---

*[storage/replica_command.go, line 1376 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79zuyEgcfOX-SiHmv:-KD79zuyEgcfOX-SiHmw:-160390861) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1376)):*
this comment and the call to Now() should be below the early return here

---

*[storage/replica_command.go, line 1389 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD7A93OBvVs_uaMcIFE:-KD7A93OBvVs_uaMcIFF:1692137523) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1389)):*
nit: weird place to use a defer, you can directly call unlock one line lower

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348)*

**Comment by vivekmenezes** [comment]
Thanks for the review. Ready for another look.

---

Review status: 2 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[storage/replica.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79JIMHz_0M9tWFxKo:-KD907By7FcEt21D4XEa:156909515) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica.go#L148)):*
In making the change Ben uncovered that we didn't need it any more. Gone!

---

*[storage/replica_command.go, line 1423 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_THeKewXvTznVtaF:-KD90Lt0JXXJ_Q7ucHSY:-1341722296) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1423)):*
I think we need a policy here around such panics that merely act as documentation. I could easily just add the comment without the panic but the panic validates the comment. if the panic were to ever go off we would need to add more log messages in a few places to better understand why the invariant was false.

---

*[storage/replica_command.go, line 1335 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79W97ZBGj1OKBi1_I:-KD94LzEPgoAF1KJZbi3:-306732824) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1335)):*
Reworded comments and sprayed a few more.

---

*[storage/replica_command.go, line 1376 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79zuyEgcfOX-SiHmv:-KD91_DLZfv5Id-XGdV9:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1376)):*
done

---

*[storage/replica_command.go, line 1389 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD7A93OBvVs_uaMcIFE:-KD913tGvoZm1nQZDJa2:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1389)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-:-KD95R0uUVZjOLCob6S9:1331559900)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[storage/replica.go, line 147 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD96Bsaz9hzFmxkArHy:-KD96Bsaz9hzFmxkArHz:-1985587460) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e18d8e9b863c68a16f655f3f9a4c3043ede615/storage/replica.go#L147)):*
this comment still refers to `ok`.

---

*[storage/replica_command.go, line 1335 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79W97ZBGj1OKBi1_I:-KD96i1ww8VcwLAdgENL:1007931089) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1335)):*
this comment looks unchanged

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348)*

**Comment by vivekmenezes** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[storage/replica.go, line 147 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD96Bsaz9hzFmxkArHy:-KD99kkgLPrq5YSLcUlv:-467915377) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e18d8e9b863c68a16f655f3f9a4c3043ede615/storage/replica.go#L147)):*
fixed

---

*[storage/replica_command.go, line 1335 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD79W97ZBGj1OKBi1_I:-KD99wTMtQxg4BTVuKTb:-1153601425) ([raw file](https://github.com/cockroachdb/cockroach/blob/445d0f331bd8866705efd00db5a3ed7f3763c1d4/storage/replica_command.go#L1335)):*
Sorry, I reworded the comments around VerifyChecksum() thinking your comment was referring to them. I've taken this comment out because the return error message is self-explanatory

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348)*

**Comment by vivekmenezes** [comment]
@bdarnell any more comments?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-:-KD9ZwfRhzrouZTXOm7Q:720525743)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica_command.go, line 1399 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4vxgpFCj5JYBqaBAD:-KDAnzq_C86Q0p4vGOXS:-1109078980) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1399)):*
You'd still avoid the second lock/lookup/unlock cycle if the map contained pointers. Doesn't matter too much, though.

---

*[storage/replica_command.go, line 1423 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_THeKewXvTznVtaF:-KDAoDUQd6fsMTjyjqjf:-1688707211) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1423)):*
If you removed the "ok" check, there would still be a panic with an unclear message ("close of nil channel", I think). Adding an explicit panic like this is a three-way tradeoff between the cost of adding the check, the likelihood of a panic, and the value added by the specific panic message instead of just letting a panic happen naturally (or the risk that the default behavior would silently do the wrong thing without panicking).

I think that in this case, logging an error and continuing seems better than panicking. If we are to panic, then "no checksum" is a little better than "close of nil channel" with a stack trace that points here, but not by much. 

I'm not sure what we could add to this panic message that would make it useful, so I'm OK with leaving it as-is, although I'd prefer to downgrade to an error. The value of the panic is mainly in making things explicit instead of relying on a later error based on the implementation detail of closing a nil channel.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-:-KDAq8Oe2ZdjJO4GK595:676834233)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica_command.go, line 1399 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4vxgpFCj5JYBqaBAD:-KDEqiIEEGnH_q-u9fqU:-1969326615) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1399)):*
I'm leaving it as is.

---

*[storage/replica_command.go, line 1423 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348#-KD4_THeKewXvTznVtaF:-KDErGRXQ825yFD9e-ql:1139282594) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fd2a8ad4eeef81ae3a2da2e536d694c14ab6748/storage/replica_command.go#L1423)):*
Downgraded to an error. I remember folks at Google had this special panic which would  panic in debug mode (tests) and log error in production, which is really what we want here and elsewhere. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5348)*

**Pull request merged**
