### PR TITLE
distsql: Replace Datums in RowFetcher with EncDatums

### PR DESCRIPTION
**Pull request by rjnn**
This is a work in progress, out for preliminary feedback to ensure I'm not 
doing something extremely flawed. 

RowFetcher should return EncDatums. Downstream users who expect a
Datum should extract it from the EncDatum using EncDatumToDTuple.

Other minor changes:
1) Rename EncDatum.Decode to EncDatum.EnsureDecoded.

2) Change SetDatum/SetEncoded/SetFromBuffer from methods that 
mutate structs to functions that return values 

3) (WIP) Merge the functionality of DatumToEncDatum with
SetDatum. Almost done, with the exception of RowFetcher.ProcessKV,
which requires converting RowFetcher.keyVals to []EncDatum.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10550)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @paperstreet 

Thanks for tackling this. This part looks good so far; the main part that's TBD is to add versions of `DecodeKeyVals`, `UnmarshalColumnValue`, `DecodeTableValue` that use `CreateEncDatumFromBuffer` and return `EncDatum`s without creating any `Datum`s internally.

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4ZY_F1a0nDIEev3v-:-KW4ZY_F1a0nDIEev3v0:bu0qeni) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/encoded_datum.go#L67)):*
> ```Go
> // make sure the slice is not modified for the lifetime of the EncDatum.
> // SetEncoded wipes the underlying Datum.
> func CreateEncDatumFromEncoded(typ ColumnType_Kind, enc DatumEncoding, val []byte) EncDatum {
> ```

Thanks for changing these over, this makes more sense. Consider removing the Create, `EncDatumFromXXX` should be clear enough.

Also, in the future try doing cleanup/renamings like this in a separate commit, makes things easier to review and track.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 107 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4augsW655yORqPTI4:-KW4augsW655yORqPTI5:biimxb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/encoded_datum.go#L107)):*
> ```Go
> 
> // SetDatum initializes the EncDatum with the given Datum.
> func (ed *EncDatum) SetDatum(typ ColumnType_Kind, d parser.Datum) {
> ```

This should also be changed to `CreateEncDatumFromDatum` like the others

---

*[pkg/sql/sqlbase/encoded_datum.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4Z9nQt-3L-ZYVkZnv:-KW4Z9nRMMfxvpfTwMpS:bnlnuak) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/encoded_datum.go#L280)):*
> ```Go
> 
> // EncDatumRowToDTuple converts a given EncDatumRow to a DTuple.
> func EncDatumRowToDTuple(tuple parser.DTuple, row EncDatumRow) error {
> ```

This function should be passed a `*DatumAlloc`, and the RowFetcher should have a DatumAlloc member that we use all the time. The point is to amortize the allocations over multiple rows

---

*[pkg/sql/sqlbase/rowfetcher.go, line 510 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4aiQluhJy3b0jzisp:-KW4aiQluhJy3b0jzisq:b-y8p6vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/rowfetcher.go#L510)):*
> ```Go
> 		return nil, nil
> 	}
> 	tuple := make(parser.DTuple, len(encRow))
> ```

this row should be allocated once and reused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KW4ZlUeDyv_y2gohBS8:b-d5qsu)*

**Comment by arjunravinarayan** [comment]
PTAL @raduberinde and @paperstreet. 

@paperstreet just need your input for the last bit that needs to be done: Changing over `ProcessValueSingle` to no longer use `UnmarshalColumnValue`, which is subtle and tricksy and eluding me. 

@raduberinde I've changed `ProcessValueTuple`, `DecodeKeyVals`, `ProcessKV` to not create intermediate `Datum`s. What remains to be done is `ProcessValueSingle`, and removing `valNeededForCol` from `RowFetcher`. I think the latter is best done in a separate PR (I've marked it as a TODO in the code), but the former should be doable with a little help from @paperstreet.

---

Review status: 0 of 26 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4ZY_F1a0nDIEev3v-:-KW9DySubgRzb6W2vOBE:baiu8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/encoded_datum.go#L67)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Thanks for changing these over, this makes more sense. Consider removing the Create, `EncDatumFromXXX` should be clear enough.
> 
> Also, in the future try doing cleanup/renamings like this in a separate commit, makes things easier to review and track.
</details>
Removed the `Create` prefixes.

I have also rebased the commit into two separate commits. Apologies for this, in retrospect I'm in a bit of a rebase hell and should have done these as separate PRs.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 107 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4augsW655yORqPTI4:-KW9DVRCaI2LBK5RmlnE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/encoded_datum.go#L107)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This should also be changed to `CreateEncDatumFromDatum` like the others
</details>
Done.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4Z9nQt-3L-ZYVkZnv:-KWFB6BEY64Ku08tc8WG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/encoded_datum.go#L280)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This function should be passed a `*DatumAlloc`, and the RowFetcher should have a DatumAlloc member that we use all the time. The point is to amortize the allocations over multiple rows
</details>
Done.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 510 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KW4aiQluhJy3b0jzisp:-KWFB7GKyGZKqzQQ-z7-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab34e72b647e591403c8e1a08632299cf0bc5080/pkg/sql/sqlbase/rowfetcher.go#L510)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> this row should be allocated once and reused
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXTtd-yI4xL_EIg77lA:bei5k38)*

**Comment by RaduBerinde** [comment]
Great!!

Can you run `BenchmarkScan*` before and after? There might be a small regression since the traditional path is now doing a bit more than before but hopefully it will be small.

On the difference between `UnmarshalColumnValue` and `DecodeTableValue`: The format of a `roachpb.Value` (see [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/data.proto#L75)) includes a 1 byte tag indicating the type of the value. `UnmarshalColumnValue` knows how to decode a single SQL value based on this tag. Later, when column families were added, a special `TUPLE` tag was introduced and in that case the KV value actually encodes multiple SQL values; `DecodeTableValue` knows how to decode a SQL value inside this more complex format.
But the underlying format might be the same (1 byte tag + value), in which case we should be able to use `DecodeTableValue` in both cases; @paperstreet should know.

---

Review status: 0 of 26 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 314 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXfSQqul37g-d35BR4V:-KXfSQqul37g-d35BR4W:b-niiy36) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L314)):*
> ```Go
> }
> 
> func directionToDatumEncoding(direction encoding.Direction) DatumEncoding {
> ```

[nit] This concept doesn't make sense in general, the name should include KeyEncoding. Although I would just do this in-place (it's only used once..)

---

*[pkg/sql/sqlbase/rowfetcher.go, line 417 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXfTKX61_S33FfMxOE2:-KXfTKX61_S33FfMxOE3:b-faej42) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/rowfetcher.go#L417)):*
> ```Go
> 		idx, ok := rf.colIdxMap[colID]
> 		// TODO(arjun): Now that rowFetcher generates EncDatums instead of Datums,
> 		// we no longer need valNeededForCol. Remove it entirely from RowFetcher.
> ```

Well, we still need it since we provide `NextRowDecoded()` which needs to know what not to decode.

Also, we could use it to optimize things further (e.g. stop processing the rest of the value(s) when we decoded everything we needed; or avoid receiving any unneeded values in the first place) so I think we should keep it.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 418 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXfTppbXX7ZCJmteZpL:-KXfTppbXX7ZCJmteZpM:bnmgkk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/rowfetcher.go#L418)):*
> ```Go
> 		// TODO(arjun): Now that rowFetcher generates EncDatums instead of Datums,
> 		// we no longer need valNeededForCol. Remove it entirely from RowFetcher.
> 		// Doing so requires fixing some logic tests that rely on it.
> ```

I can't think of what logic test would be able to tell the difference of whether RowFetcher internally uses `valNeededForCol` or not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXfUHUtyOZhfpk8huQi:b-aexwff)*

**Comment by arjunravinarayan** [comment]
So `BenchmarkScan` is losing about 5-10% performance, which isn't great, so I'd like to inspect that and streamline it a little more carefully. Will report back with detailed numbers (attempting to produce the detailed numbers unearthed #11665). @paperstreet and I took a look at the `UnmarshalColumnValue` code today, and we have a hypothesis for how to switch it over to `DecodeTableValue` (they have different formats for the tags right now). I'll report back when I attempt that, and get a more detailed report on where the performance regression is right now, and whether we can reduce it. Thank you for the review!

---

Review status: 0 of 26 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXiQ4u5tsgjzCsiZQLB:b-lniipe)*

**Comment by RaduBerinde** [comment]
I see.. I was hoping it was less than that. Though `BenchmarkScan` uses just an int column and `EncDatum` is not very good for small fixed-sized values, #8792 tracks coming up with a better way to pass around small datums.

---

Review status: 0 of 26 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXkIgzUpf609yA5Lrvl:b-g5ff23)*

**Comment by irfansharif** [comment]
Review status: 0 of 26 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[pkg/sql/scan.go, line 194 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXl0za31gNIqLhDTEAn:-KXl0za31gNIqLhDTEAo:b-glm8ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/scan.go#L194)):*
> ```Go
> 	var da sqlbase.DatumAlloc
> 	err = sqlbase.EncDatumRowToDTuple(tuple, encRow, &da)
> 	if err != nil {
> ```

/nit `if err := sqlbase.EncDatumRowToDTuple(tuple, encRow, &da); err != nil { ... }` to not reuse `err`/reduce scope. 

---

*[pkg/sql/sqlbase/encoded_datum.go, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXl49WHBMv-gsPBl6al:-KXl49WHBMv-gsPBl6am:b-jhu6c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddaeb83e6872e2fbd42690b280c2449a2cf8c29f/pkg/sql/sqlbase/encoded_datum.go#L76)):*
> ```Go
> 	ed.encoded = val
> 	ed.Datum = nil
> 	return ed
> ```

we can do 
```
return EncDatum{
    Type: typ,
    encoding: enc,
    encoded: val,
    Datum: nil,
}
```

---

*[pkg/sql/sqlbase/encoded_datum.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlC1-Mk4fPmRm9yCJ3:-KXlC1-Mk4fPmRm9yCJ4:b-6gk51r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L67)):*
> ```Go
> // make sure the slice is not modified for the lifetime of the EncDatum.
> // SetEncoded wipes the underlying Datum.
> func EncDatumFromEncoded(typ ColumnType_Kind, enc DatumEncoding, val []byte) EncDatum {
> ```

`GoRename: val to encoded`

---

*[pkg/sql/sqlbase/encoded_datum.go, line 85 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlCU37J8dSYk-ERl0w:-KXlCU37J8dSYk-ERl0x:bgirkig) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L85)):*
> ```Go
> func EncDatumFromBuffer(
> 	typ ColumnType_Kind, enc DatumEncoding, buf []byte,
> ) (EncDatum, []byte, error) {
> ```

I think we should keep `remaining` as a named return type, makes it clearer.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 93 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlClug0WBPVlaulosD:-KXlClug0WBPVlaulosE:bursepz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L93)):*
> ```Go
> 		}
> 		ed := EncDatumFromEncoded(typ, enc, buf[:encLen])
> 		return ed, buf[encLen:], nil
> ```

if using named return types we can just  use `ed` there and `return EncDatumFromEncoded(typ, enc, buf[:encLen]), buf[encLen:], nil`.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 252 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlDnYoGpAIRp_vuFvs:-KXlDnYpUE6tNutYjZDH:b-oxkdsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L252)):*
> ```Go
> 
> // DTupleToEncDatumRow converts a parser.DTuple to an EncDatumRow.
> func DTupleToEncDatumRow(row EncDatumRow, tuple parser.DTuple) error {
> ```

right so as mentioned in #10411, this and the subsequent call to `DatumToEncDatumWithInferredType` will fail with datums of type `TypeNull`. This is currently only being used in `aggregators.go` iirc so I was going to change this out to a signature that would actually take in a `[]ColumnType_Kind` as well, removing the need for inference. We can leave this for now and I'll follow up with a PR after this is in or just a PR to your branch, whatever you prefer.

---

*[pkg/sql/sqlbase/encoded_datum_test.go, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXl5_bxVRX91tKlaQ4R:-KXl5_bxVRX91tKlaQ4S:btfr03c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddaeb83e6872e2fbd42690b280c2449a2cf8c29f/pkg/sql/sqlbase/encoded_datum_test.go#L38)):*
> ```Go
> 	}
> 
> 	x = EncDatumFromDatum(ColumnType_INT, parser.NewDInt(5))
> ```

/nit let's not re-use `x`? we seem to defining `y`, `z` separately as well down below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550)*

**Comment by irfansharif** [comment]
also could you rebase on the latest master to pick up the new `distsql_physical_planner.go` (and discard `dist_sql_node.go`)? picking this up for aggregation planning which builds on that.

**Comment by arjunravinarayan** [comment]
TFTRs! Working on your helpful comments after fixing the column family thing.
Also rebased. Performance benchmarking shows 0%-3% time increase. Working on doing some `count` benchmarks too, which should show time decrease.
```
name                                   old time/op  new time/op  delta
Scan1_Cockroach-24                      318µs ± 2%   321µs ± 4%    ~     (p=0.529 n=10+10)
Scan1Multinode_Cockroach-24             326µs ± 2%   333µs ± 5%  +2.15%  (p=0.015 n=10+10)
Scan10_Cockroach-24                     357µs ± 1%   357µs ± 3%    ~     (p=0.497 n=9+10)
Scan10Multinode_Cockroach-24            359µs ± 2%   352µs ± 4%    ~     (p=0.075 n=10+10)
Scan100_Cockroach-24                    624µs ± 2%   621µs ± 2%    ~     (p=0.143 n=10+10)
Scan100Multinode_Cockroach-24           616µs ± 2%   606µs ± 2%  -1.65%  (p=0.000 n=9+10)
Scan1000_Cockroach-24                  2.52ms ± 2%  2.51ms ± 1%    ~     (p=0.315 n=10+7)
Scan1000Multinode_Cockroach-24         2.49ms ± 0%  2.51ms ± 1%    ~     (p=0.113 n=10+9)
Scan10000_Cockroach-24                 22.0ms ± 2%  22.3ms ± 2%  +1.34%  (p=0.010 n=10+9)
Scan10000Multinode_Cockroach-24        21.6ms ± 1%  22.4ms ± 3%  +3.45%  (p=0.000 n=8+10)
Scan1000Limit1_Cockroach-24             326µs ± 2%   333µs ± 1%  +2.22%  (p=0.001 n=10+9)
Scan1000Limit1Multinode_Cockroach-24    327µs ± 2%   331µs ± 2%  +1.22%  (p=0.043 n=10+10)
Scan1000Limit10_Cockroach-24            357µs ± 2%   356µs ± 2%    ~     (p=0.684 n=10+10)
Scan1000Limit10Multinode_Cockroach-24   363µs ± 3%   357µs ± 3%    ~     (p=0.089 n=10+10)
Scan1000Limit100_Cockroach-24           618µs ± 1%   625µs ± 3%    ~     (p=0.190 n=9+5)
```

---

Review status: 0 of 26 files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/sql/scan.go, line 194 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXl0za31gNIqLhDTEAn:-KXlRQIti_Te4eyxkIkC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/scan.go#L194)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

/nit `if err := sqlbase.EncDatumRowToDTuple(tuple, encRow, &da); err != nil { ... }` to not reuse `err`/reduce scope. 
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXl49WHBMv-gsPBl6al:-KXlRlXNN-8DUjieUEAj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddaeb83e6872e2fbd42690b280c2449a2cf8c29f/pkg/sql/sqlbase/encoded_datum.go#L76)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

we can do 
```
return EncDatum{
    Type: typ,
    encoding: enc,
    encoded: val,
    Datum: nil,
}
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXlR7vLs0X5BXTsk-rp:b8y5y1n)*

**Comment by RaduBerinde** [comment]
Great! The benchmark differences are within noise, I wouldn't worry about it. In particular, there is no reason why multinode or not should make a difference w.r.t this change.

---

Review status: 0 of 26 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXm1qiR_rvnFlWJolc6:b-s8vwpi)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 26 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlC1-Mk4fPmRm9yCJ3:-KXrD2xEvc9DYh7qJVfB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L67)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

`GoRename: val to encoded`
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 85 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlCU37J8dSYk-ERl0w:-KXrDTTsYZftxx9FHAPu:b-77iywv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L85)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I think we should keep `remaining` as a named return type, makes it clearer.
</blockquote></details>

I think its pretty clear because of the top level comment. And since we'd have to assign the values anyway, I don't see the value.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 93 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlClug0WBPVlaulosD:-KXrHIupeDywyKTfLKPe:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L93)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

if using named return types we can just  use `ed` there and `return EncDatumFromEncoded(typ, enc, buf[:encLen]), buf[encLen:], nil`.
</blockquote></details>

See above.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 252 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXlDnYoGpAIRp_vuFvs:-KXrF7Si8JQ8KKVacxrU:b-oz41m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L252)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

right so as mentioned in #10411, this and the subsequent call to `DatumToEncDatumWithInferredType` will fail with datums of type `TypeNull`. This is currently only being used in `aggregators.go` iirc so I was going to change this out to a signature that would actually take in a `[]ColumnType_Kind` as well, removing the need for inference. We can leave this for now and I'll follow up with a PR after this is in or just a PR to your branch, whatever you prefer.
</blockquote></details>

I'm removing the function, and moving the code to `aggregators.go`. You can remove it in a follow up PR. Thank you!

---

*[pkg/sql/sqlbase/encoded_datum.go, line 314 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXfSQqul37g-d35BR4V:-KXrGAqEkzZjJgDu7KWi:b-bmzonk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/encoded_datum.go#L314)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This concept doesn't make sense in general, the name should include KeyEncoding. Although I would just do this in-place (it's only used once..)
</blockquote></details>

Moved in place.

---

*[pkg/sql/sqlbase/encoded_datum_test.go, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXl5_bxVRX91tKlaQ4R:-KXrGyVxDNVH7DN_-9rw:b-cy4gmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddaeb83e6872e2fbd42690b280c2449a2cf8c29f/pkg/sql/sqlbase/encoded_datum_test.go#L38)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

/nit let's not re-use `x`? we seem to defining `y`, `z` separately as well down below.
</blockquote></details>

Done. Changed earlier occurrences of `x` to `v`, since we rely on `x` downstream for some comparisons.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 417 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXfTKX61_S33FfMxOE2:-KXrHEfrPlIowbe_Afd_:b-x5dbr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/rowfetcher.go#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Well, we still need it since we provide `NextRowDecoded()` which needs to know what not to decode.

Also, we could use it to optimize things further (e.g. stop processing the rest of the value(s) when we decoded everything we needed; or avoid receiving any unneeded values in the first place) so I think we should keep it.
</blockquote></details>

OK, removed the TODO.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 418 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXfTppbXX7ZCJmteZpL:-KXrCuESAHwuMRYCV-LL:b-v6s1o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8717add28055da3027cdd086449ce6bae58032d3/pkg/sql/sqlbase/rowfetcher.go#L418)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I can't think of what logic test would be able to tell the difference of whether RowFetcher internally uses `valNeededForCol` or not?
</blockquote></details>

Removed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550)*

**Comment by RaduBerinde** [comment]
:lgtm_strong: Thanks!

---

Review status: 0 of 26 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 361 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXrPOpGuamNheLXZ1xQ:-KXrPOpGuamNheLXZ1xR:bpa3gri) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fefbcb5122fa374bbf782af8cbfd9ea96777ae0/pkg/sql/sqlbase/rowfetcher.go#L361)):*
> ```Go
> 		}
> 		kind := rf.cols[idx].Type.Kind
> 		value, err := UnmarshalColumnValue(&rf.alloc, kind, kv.Value)
> ```

Can you mention here or in a function comment for processValueSingle that this code path is deprecated and only exists for backward compatibility with versions that didn't have families (even if we have a single-value family!).

---

*[pkg/sql/sqlbase/table.go, line 688 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXrP0W4yff0U5v8VOyR:-KXrP0W4yff0U5v8VOyS:b-y7vsqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fefbcb5122fa374bbf782af8cbfd9ea96777ae0/pkg/sql/sqlbase/table.go#L688)):*
> ```Go
> 	}
> 	for j := range vals {
> 		direction := encoding.Ascending
> ```

[nit] could just do
```
encoding := DatumEncoding_ASCENDING_KEY
if directions != nil && directions[j] == encoding.Descending {
  encoding = DatumEncoding_DESCENDING_KEY
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXrPixuPTd0hzyaJDxy:bfdlkw5)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 361 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXrPOpGuamNheLXZ1xQ:-KXvgzmexGXyMMGiPUJ2:b-5qa47z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fefbcb5122fa374bbf782af8cbfd9ea96777ae0/pkg/sql/sqlbase/rowfetcher.go#L361)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you mention here or in a function comment for processValueSingle that this code path is deprecated and only exists for backward compatibility with versions that didn't have families (even if we have a single-value family!).
</blockquote></details>

I'm not sure any more that its deprecated (I know I said so earlier, so my apologies) but I have added a comment saying this can potentially be optimized out.

---

*[pkg/sql/sqlbase/table.go, line 688 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXrP0W4yff0U5v8VOyR:-KXvguCBcpXEouD4fkN3:b-ttn3ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fefbcb5122fa374bbf782af8cbfd9ea96777ae0/pkg/sql/sqlbase/table.go#L688)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could just do
```
encoding := DatumEncoding_ASCENDING_KEY
if directions != nil && directions[j] == encoding.Descending {
  encoding = DatumEncoding_DESCENDING_KEY
}
```
</blockquote></details>

Done, except using `enc` to not shadow package name `encoding`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550)*

**Comment by RaduBerinde** [comment]
LGTM

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-:-KXvwanlX3qsP94Nf-3l:bb6ywmx)*

**Comment by paperstreet** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 361 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550#-KXrPOpGuamNheLXZ1xQ:-KXvwxTNckFgiXipqx4f:b-fxksfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fefbcb5122fa374bbf782af8cbfd9ea96777ae0/pkg/sql/sqlbase/rowfetcher.go#L361)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'm not sure any more that its deprecated (I know I said so earlier, so my apologies) but I have added a comment saying this can potentially be optimized out.
</blockquote></details>

It's also used as a "performance optimization" if a family has only ever had one column in it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10550)*

**Pull request merged**
