### PR TITLE
colexec: add unit tests for bufferOp and caseOp

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: minor tweaks to bufferOp and caseOp**

This commit cleans up a few things:
- removes an unused batchLen field
- reuses rewind() within advance()
- removes the duplicate call to rewind() in caseOp.Next()
- slices up to origLen when restoring the original selection vector.

Release justification: Category 1: Non-production code changes.

**colexec: add unit tests for bufferOp**

Addresses: #40634.

Release justification: Category 1: Non-production code changes.

**colexec: add some unit tests for caseOp**

This commit adds some unit tests for case operator.

Addresses: #40634.

Release justification: Category 1: Non-production code changes.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Friendly ping.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41054#-:-LrAS2MCBq7u4bQa3bIK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems stuck.

bors r-

**Comment by yuzefovich** [comment]
Seems like a flake.

bors r+

**Pull request merged**
