### PR TITLE
opt: add GenerateUnionSelects exploration rule for disjunction

### LINKED ISSUE #2142: sql: better query planning for OR expressions
Consider a query like `SELECT * FROM foo WHERE a > 1 OR b > 2`. Even if there are appropriate indexes to satisfy both `a > 1` and `b > 2`, the current query planner will perform a full table or index scan because it can't use both conditions at once. Instead, the query planner should check to see if 2 separate index scans can be used and their results merged using a "union" operation.

This is essentially a generalization of #2140.

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add GenerateUnionSelects exploration rule for disjunction

This commit adds a new exploration rule that can produce better query
plans for disjunctions (e.g. a = 1 OR b = 2). The rule transforms some
Select + Scan expressions with a disjunction filter into a Union of two
Select expressions, each with one side of the disjuction as a filter.
This can result in faster query plans in cases where two indexes cover
each side of the disjunction.

This rule only applies for Scan expressions that contain a strict key.

Fixes #2142

Release note (performance improvement): The query optimizer now produces
faster query plans for some disjunctions (OR expressions) by utilizing
multiple indexes.

#### sql: allow UNION with hidden and non-hidden columns

This commit removes an assertion that required corresponding columns on
each side of a UNION to be both hidden or non-hidden.

Prior to this change, the following statements would yield the error:
"UNION types cannot be matched".

  CREATE TABLE ab (a INT, b INT);
  SELECT a, b, rowid FROM ab UNION VALUES (1, 2, 3);

With this commit, the above statements are executed without error.

Release note (bug fix): Fixed an incorrect error the ocurred when
executing UNION statements with hidden and non-hidden columns.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/rules/select.opt, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-M4HMOJs4LXItHYgFf8x:-M4HMOJt86bFc0jgeNdU:b8gt1io) ([raw file](https://github.com/cockroachdb/cockroach/blob/807bf1e6b71a1688907d85c0537947ddd426bf9b/pkg/sql/opt/xform/rules/select.opt#L75)):*
> ```
>         ...
>         $item:(FiltersItem (Or $left:* $right:*)) &
>             ^(ColsAreEqual (ExprOuterCols $left) (ExprOuterCols $right))
> ```

Did we decide whether or not it's also worth checking whether an index exists with a prefix contained by the outer cols of each side? I don't remember how that discussion ended.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/xform/rules/select.opt, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-M4HMOJs4LXItHYgFf8x:-M4KVBCs4Fjp7UXcA1qq:b-ofbhxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/807bf1e6b71a1688907d85c0537947ddd426bf9b/pkg/sql/opt/xform/rules/select.opt#L75)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did we decide whether or not it's also worth checking whether an index exists with a prefix contained by the outer cols of each side? I don't remember how that discussion ended.
</blockquote></details>

Yes, everyone agreed it was the right thing to do. Andy suggested adding it in a follow-up PR to keep the diffs more manageable.

**Review by rytaft — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-:-M4KXaVWAm3AtF3tGNBU:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/rules/select.opt, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-M4HMOJs4LXItHYgFf8x:-M4KXXcsEzj5phjDIx6W:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/807bf1e6b71a1688907d85c0537947ddd426bf9b/pkg/sql/opt/xform/rules/select.opt#L75)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes, everyone agreed it was the right thing to do. Andy suggested adding it in a follow-up PR to keep the diffs more manageable.
</blockquote></details>

Sounds good.

**Comment by rytaft** [comment]
Looks like you have a bunch of failures in the logic tests due to "validate foreign key constraint: UNION types cannot be matched"

**Review by RaduBerinde — APPROVED** [review]
Nice work! :lgtm: 

That error is odd. It comes from an internally generated query for VALIDATE CONSTRAINT (which basically searches for "bad" rows): https://github.com/cockroachdb/cockroach/blob/9ccd76506eaca466b252cf002b7d8d2505258cc0/pkg/sql/check.go#L123

The error is coming from here: https://github.com/cockroachdb/cockroach/blob/9ccd76506eaca466b252cf002b7d8d2505258cc0/pkg/sql/union.go#L118
I don't know why we would have mismatched hidden columns, but I'm also not sure this code should care about them at all. It might be a relic from the heuristic planner.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-:-M4MPBisBXEK3T3lBY1n:b-hmdpi6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by RaduBerinde** [comment]
Looked into it some more and I believe one side is inheriting Hidden from the table column descriptor (for `rowid`) and the other side is a union. It shouldn't matter - it's safe to remove that code that checks that the `Hidden` values match.

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-M4Mbjg18-q5R0NhoSSQ:-M4Mbjg18-q5R0NhoSSR:b5aentw) ([raw file](https://github.com/cockroachdb/cockroach/blob/807bf1e6b71a1688907d85c0537947ddd426bf9b/pkg/sql/opt/xform/custom_funcs.go#L2293)):*
> ```Go
> 	}
> 
> 	return &memo.ScanPrivate{
> ```

We need to copy Flags and Locking here too. Here's an example where we're not respecting the index hint, maybe add a similar test somewhere (probably in `opt/exec/execbuilder/testdata/select_index_flags`):
```
root@127.0.0.1:44751/defaultdb> explain select * from t@primary where k=1 or a=1;
    tree    |    field    | description
------------+-------------+--------------
            | distributed | false
            | vectorized  | false
  union     |             |
   ├── scan |             |
   │        | table       | t@t_a_idx
   │        | spans       | /1-/2
   └── scan |             |
            | table       | t@primary
            | spans       | /1-/1/#
```

**Review by RaduBerinde — APPROVED** [review]
Btw here's a very simple example which causes that error, I would fix it in a separate commit and add this test:
```
root@127.0.0.1:44751/defaultdb> create table ab (a int, b int);
CREATE TABLE

Time: 3.036493ms

root@127.0.0.1:44751/defaultdb> select a, b, rowid from ab union values (1,2,3);
ERROR: UNION types cannot be matched
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-:-M4Me3s47AwFhQlVH1va:bmpkpp6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-M4Mbjg18-q5R0NhoSSQ:-M4QSvo54Pj_rBgKxjto:bh79u73) ([raw file](https://github.com/cockroachdb/cockroach/blob/807bf1e6b71a1688907d85c0537947ddd426bf9b/pkg/sql/opt/xform/custom_funcs.go#L2293)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We need to copy Flags and Locking here too. Here's an example where we're not respecting the index hint, maybe add a similar test somewhere (probably in `opt/exec/execbuilder/testdata/select_index_flags`):
```
root@127.0.0.1:44751/defaultdb> explain select * from t@primary where k=1 or a=1;
    tree    |    field    | description
------------+-------------+--------------
            | distributed | false
            | vectorized  | false
  union     |             |
   ├── scan |             |
   │        | table       | t@t_a_idx
   │        | spans       | /1-/2
   └── scan |             |
            | table       | t@primary
            | spans       | /1-/1/#
```
</blockquote></details>

Done. I'm not sure the test really belongs there though, since it's specific to GenerateUnionSelects. Should I instead make it an opt test in `xform/testdata/rules/select` since the union should not be the in the final execution plan when forcing a single index?

**Review by mgartner — COMMENTED** [review]
> Btw here's a very simple example which causes that error, I would fix it in a separate commit and add this test:

Where is a good place to put this test?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-:-M4QZFiHDM710ccaiKuX:b-vmxfmu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-M4Mbjg18-q5R0NhoSSQ:-M4Qiwbx53p6nF03xAiN:bhgv59o) ([raw file](https://github.com/cockroachdb/cockroach/blob/807bf1e6b71a1688907d85c0537947ddd426bf9b/pkg/sql/opt/xform/custom_funcs.go#L2293)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Done. I'm not sure the test really belongs there though, since it's specific to GenerateUnionSelects. Should I instead make it an opt test in `xform/testdata/rules/select` since the union should not be the in the final execution plan when forcing a single index?
</blockquote></details>

Hm yeah, you're right. It should be another testcase for the rule, with a comment saying that we verify that the index flags are preserved on both sides.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47094#-:-M4Vgh7o9mFG8ja3zwfE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

**Pull request merged**
