### PR TITLE
roachprod: add GCE DNS Provider

### PR DESCRIPTION
**Pull request by herkolategan**
Previously on PR https://github.com/cockroachdb/cockroach/pull/106497 an interface for DNS record management to extend
provider capabilities was introduced, as well as a local cluster only
implementation of that interface, to support port management of tenants in the
form of services.

This change adds a Google Cloud DNS implementation for the GCE Provider
utilising the same interface as mentioned above, to enable cloud clusters to
also utilise port management for tenants. It uses the commands available on the
`gcloud dns cli` to perform DNS operations required to register cockroach
services. All operational commands run through `gcloud` except for
`LookupSRVRecords` which relies on the standard `net` package.

`roachprod` operations are likely to invoke the lookup call frequently thus
using the standard net lookup yields better performance than going through the
`cli`. There is a small delay between management operations completing and the
records becoming available through standard lookup methods. A wait function is
provided to ensure all the records are available through a standard net lookup
after a create operation.

This implementation opted for the non-transactional gcloud dns cli. The
transaction operations are not allowed to overlap even if managing separate
records. A transaction will result in a "preconditions not met" error if any
other transaction completed on the same zone while this one is still in flight.
Due to the fact that `roachprod` can be used from various places concurrently
it's best to avoid this.

Epic: [CRDB-18499](https://cockroachlabs.atlassian.net/browse/CRDB-18499)
Release note: None

### CODE REVIEW

**Review by herkolategan — COMMENTED** [review]
TC Run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11488734

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-:-Nch35Jk4QIOGY-G33tV:b-kctzhe)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by herkolategan** [comment]
Converting to a draft again as I'm making some updates in light of the discovered flake.

**Review by herkolategan — COMMENTED** [review]
Additional TC Run to ensure there are no flakes regarding waiting for DNS records to become available:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11573644

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-:-NdGJiB9CyCSw4SQnEES:b-sfhcdn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @smg260)

**Review by renatolabs — APPROVED** [review]
:lgtm:

Mostly minor comments, nice work!

I see that we're only enabling the DNS provider on Google cloud. Are we planning to implement something similar for other clouds?

> Reviewed 2 of 3 files at r1, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-:-Ndky8xE0FPVfBUl5Gbs:bb6fadk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @smg260)

___
*[`pkg/roachprod/vm/gce/dns.go` line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgJeGz8vJboeFd9Npt:-NdgJeH-0IQX_ITEUP7t:b-jr8z9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L82)):*
> ```Go
> 
> 		// Add the new record data.
> 		// TODO(Herko): Warn if the same record has been added twice
> ```

Is "twice" referring to duplicates in the list of `records` passed as argument, or the records passed as argument relative to `existingRecords`?
___
*[`pkg/roachprod/vm/gce/dns.go` line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgMN3uD19RPgkj5TBd:-NdgMN3uD19RPgkj5TBe:ber01o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L107)):*
> ```Go
> 	// are required for starting servers. The waiting period should usually be
> 	// short (less than 30 seconds), but we set it to 2 minutes to be safe.
> 	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
> ```

Minor, but maybe we should consider changing this interface to take a context, as this should ideally be preemptable if, for example, the test failed concurrently
___
*[`pkg/roachprod/vm/gce/dns.go` line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgMqAi8XrHO7-uQBcj:-NdgMqAi8XrHO7-uQBck:b-k6xzjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L107)):*
> ```Go
> 	// are required for starting servers. The waiting period should usually be
> 	// short (less than 30 seconds), but we set it to 2 minutes to be safe.
> 	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
> ```

Nit: `2 * time.Minute`?
___
*[`pkg/roachprod/vm/gce/dns.go` line 165 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdkvWGr6z3GexJQt7BI:-NdkvWGr6z3GexJQt7BJ:blgoq8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L165)):*
> ```Go
> 		// the errors ambiguous and not useful. The errors are not exported, so we
> 		// have to check the error message.
> 		if dnsError.Err != "server misbehaving" && dnsError.Err != "no such host" && !dnsError.IsNotFound {
> ```

When is `IsNotFound` true? How is it different from `no such host`?

Also curious if the wait loop would work without `IsNotFound`.
___
*[`pkg/roachprod/vm/gce/dns.go` line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgN8NS4FbVGxo-f-mI:-NdgN8NS4FbVGxo-f-mJ:bfb9qll) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L223)):*
> ```Go
> // DNS server through a standard net tools lookup. A context with a timeout
> // should be passed in.
> func (n dnsProvider) waitForRecordsAvailable(ctx context.Context, records ...vm.DNSRecord) error {
> ```

Nit: in terms of API design, I'd prefer if this function took a max wait duration as parameter instead of documenting that the caller should set up the context appropriately. Or maybe we don't even need the duration parameter and this function could just define a sensible timeout since we only have one caller at the moment.
___
*[`pkg/roachprod/vm/gce/dns.go` line 224 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-Ndkgirv4Xz8ZF1kZh9l:-Ndkgirv4Xz8ZF1kZh9m:b6sk0s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L224)):*
> ```Go
> // should be passed in.
> func (n dnsProvider) waitForRecordsAvailable(ctx context.Context, records ...vm.DNSRecord) error {
> 	notAvailable := make(map[string]struct{})
> ```

Is there a reason we're not using a struct as a map key in this data structure? Sounds easier to understand/maintain than the custom string encoding.
___
*[`pkg/roachprod/vm/gce/dns.go` line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-Ndkh2eZB41qfszwNmcV:-Ndkh2eZB41qfszwNmcW:b-ed6n0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L233)):*
> ```Go
> 	}
> 	var lastErr error
> 	for ctx.Err() == nil {
> ```

We could use the `retry` package here, and then we don't need to keep track of a `lastErr`.

**Review by renatolabs — COMMENTED** [review]
How's your experience been using `gcloud` to manage DNS records?

Not sure how reliable this will be; I'm thinking that if we start seeing failures, it would be nice to mark any errors coming from these DNS related functions as flakes and group them the same way we do for cluster creation failures.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-:-Ndkyhrr0G-jg3aL2o7N:bpb0n25)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @smg260)

**Review by herkolategan — COMMENTED** [review]
TFTR!
> Not sure how reliable this will be;

I haven't seen any flakes yet except for the initial bug, and when I had the timeout (to wait for records) on less than 10 seconds. But I agree, if it does become a source of flakes we can make the change to mark it.

> I see that we're only enabling the DNS provider on Google cloud.

I plan on enabling Google Cloud DNS as the DNS provider for the other providers. That should be sufficient and I don't see an immediate need to support any other DNS Service Providers. But I do want to enable Google DNS as the DNS Provider for the other providers as well, just not maybe in this PR until we've had a few good runs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-:-NdpJ_njAdwjjtTeqNqP:bhucpgi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @smg260)

___
*[`pkg/roachprod/vm/gce/dns.go` line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgJeGz8vJboeFd9Npt:-NdngNhk85lwbr10Oo7Q:b-h2mtf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L82)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is "twice" referring to duplicates in the list of `records` passed as argument, or the records passed as argument relative to `existingRecords`?
</blockquote></details>

In a sense I think it ends up covering both. Since you can't add SRV records to an existing name "group", the way to amend it is to query the existing records and append to it. But you could potentially be trying to add an existing entry with the amend. This prevents that as it would cause an error.
___
*[`pkg/roachprod/vm/gce/dns.go` line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgMN3uD19RPgkj5TBd:-Ndngjn33oZa-X0xxtnp:b7t98p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L107)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Minor, but maybe we should consider changing this interface to take a context, as this should ideally be preemptable if, for example, the test failed concurrently
</blockquote></details>

Good idea, I'll rework the interface.
___
*[`pkg/roachprod/vm/gce/dns.go` line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgMqAi8XrHO7-uQBcj:-NdngoIfB3NNOX5yqjnU:b-ty2fzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L107)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: `2 * time.Minute`?
</blockquote></details>

Haha yep, good catch, was fiddling with the time on this one for a bit. 2 minutes still feel long, but I've seen failures between 5 - 10 seconds.
___
*[`pkg/roachprod/vm/gce/dns.go` line 165 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdkvWGr6z3GexJQt7BI:-Ndnh17g91Q2MB-abQwY:b-wopr31) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L165)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

When is `IsNotFound` true? How is it different from `no such host`?

Also curious if the wait loop would work without `IsNotFound`.
</blockquote></details>

`IsNotFound` stems from the same place as "no such host", but this is my distrust of the dns implementation to cover for worst case. It would probably work without `IsNotFound`, we could update it and fix it later if it flakes.
___
*[`pkg/roachprod/vm/gce/dns.go` line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-NdgN8NS4FbVGxo-f-mI:-NdnhiGb-h04rFP0jVD7:b9xpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L223)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: in terms of API design, I'd prefer if this function took a max wait duration as parameter instead of documenting that the caller should set up the context appropriately. Or maybe we don't even need the duration parameter and this function could just define a sensible timeout since we only have one caller at the moment.
</blockquote></details>

Fair enough, a default would suffice, I'll move the timeout logic to the function itself.
___
*[`pkg/roachprod/vm/gce/dns.go` line 224 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-Ndkgirv4Xz8ZF1kZh9l:-Ndni1i_ASdhszwWTmv-:b-xllm0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L224)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is there a reason we're not using a struct as a map key in this data structure? Sounds easier to understand/maintain than the custom string encoding.
</blockquote></details>

True, should be cleaner. Updated.
___
*[`pkg/roachprod/vm/gce/dns.go` line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107415#-Ndkh2eZB41qfszwNmcV:-Ndni7eu1m9b9wpiAG0U:b-ehw21j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3721d0f0a593517a2f372ac2c29c50586d5611/pkg/roachprod/vm/gce/dns.go#L233)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

We could use the `retry` package here, and then we don't need to keep track of a `lastErr`.
</blockquote></details>

Good point, I'll update.

**Review by renatolabs — APPROVED** [review]
Thanks for adding the context to the resolver API!

**Comment by herkolategan** [comment]
TFTR!
bors r=renatolabs

**Pull request merged**
