### PR TITLE
kv/concurrency: expose lock table counters, introduce timeseries metrics

### PR DESCRIPTION
**Pull request by nvb**
Replaces https://github.com/cockroachdb/cockroach/pull/66343.

This change exposes access to a collection of counters that describe the state of a lockTable, including information on locks and on lock wait-queues. Some of these counters are plumbed up through debug endpoints, providing access to this information in the DB console and through debug.zips.

It then introduces following four timeseries metrics:
- `kv.concurrency.locks`
- `kv.concurrency.locks_with_wait_queues`
- `kv.concurrency.lock_wait_queue_waiters`
- `kv.concurrency.max_lock_wait_queue_waiters_for_lock`

These are computed as aggregations over all of the ranges on a given store using the new lock table counters. They are collected periodically - every 10s.

The process of collecting these metrics is made efficient enough that I do not have major concerns about calling this once every 10s per range (from `computePeriodicMetrics`). The vast majority of ranges in large clusters will have empty lock tables, so this will only add about 50ns per replica in `updateReplicationGauges`. Even on a node with 100k ranges, this will only take about 5ms.

```
name                            time/op
LockTableMetrics/locks=0-16     43.0ns ± 4%
LockTableMetrics/locks=1-16     76.1ns ± 3%
LockTableMetrics/locks=16-16     389ns ± 3%
LockTableMetrics/locks=256-16   5.58µs ± 5%
LockTableMetrics/locks=4096-16  89.6µs ± 4%

name                            alloc/op
LockTableMetrics/locks=0-16      0.00B
LockTableMetrics/locks=1-16      0.00B
LockTableMetrics/locks=16-16     0.00B
LockTableMetrics/locks=256-16    0.00B
LockTableMetrics/locks=4096-16   0.00B

name                            allocs/op
LockTableMetrics/locks=0-16       0.00
LockTableMetrics/locks=1-16       0.00
LockTableMetrics/locks=16-16      0.00
LockTableMetrics/locks=256-16     0.00
LockTableMetrics/locks=4096-16    0.00
```

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
@nvanbenschoten should we expose these metrics in a dashboard? Are these metrics something a customer could look at and take action, or mostly for CRDB use? Happy to make a ticket for our team to pick up.

(we have a separate discussion ongoing w/ Tobias about how we can automate the dashboard gen for DB Console + Grafana via `chart_catalog.go` potentially but nothing is in place yet.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-:-Me5pnvVAPnF9PpppLwL:bq0wkjt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @sumeerbhola)

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-:-Me6IOtYCMhJerimefE3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me6AwgiBvKblkaBi1l4:-Me6AwgiBvKblkaBi1l5:bhfg1zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0fd136a538b22cbf9bfff03b2885b7783711aa/pkg/kv/kvserver/concurrency/concurrency_control.go#L302)):*
> ```Go
> 	// LockTableDebug returns a debug string representing the state of the
> 	// lockTable.
> 	LockTableDebug() string
> ```

You sure you wanna take this away (and the corresponding field in the range state proto)?
In fact, instead of taking it away, how about including timing info in it so we can tell how long locks have been held for?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 348 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me6Cj0wB0kYteV6yNif:-Me6Cj0wB0kYteV6yNig:btrjae0) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/concurrency/lock_table.go#L348)):*
> ```Go
> 	// is comparable in system throughput, one can eliminate the above anomalies.
> 	//
> 	// TODO(nvanbenschoten): should we be Reset-ing these btree snapshots when we
> ```

i don't know what we're talking about here, but are we afraid of a bug or just a perf (or memory?) optimization? If it's the latter, I'd hint to it in the TODO, otherwise it sounds scary.
___
*[pkg/kv/kvserver/concurrency/metrics.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me6FZxq55zwErsOWCDN:-Me6FZxq55zwErsOWCDO:b-g34h3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/concurrency/metrics.go#L23)):*
> ```Go
> // LockTableMetrics holds information about the state of a lockTable.
> type LockTableMetrics struct {
> 	Locks                 int64
> ```

I think pretty much all the fields here would benefit from comments :)
___
*[pkg/kv/kvserver/intentresolver/metrics.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me68FXY9E6XgCxF4vAa:-Me68FXY9E6XgCxF4vAb:bnfmk3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c32aefd6942cfad65c4f7b49c193367d7614fbe/pkg/kv/kvserver/intentresolver/metrics.go#L23)):*
> ```Go
> 		Unit:        metric.Unit_COUNT,
> 	}
> 	metaFinalizedTxnCleanupFailed = metric.Metadata{
> ```

while you're here, mind putting a comment on this one with some words about what it means?
___
*[pkg/kv/kvserver/spanlatch/manager.go, line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me69W-a2kHKoEiF_py1:-Me69W-a2kHKoEiF_py2:bokh28x) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/spanlatch/manager.go#L562)):*
> ```Go
> 
> // Metrics holds information about the state of a Manager.
> type Metrics struct {
> ```

I've clicked around a bit and generally failed to find info about the distinction between global and local latches. I think a comment somewhere spelling out why there's separate (perhaps something about MVCC access?)  would be good.
___
*[pkg/server/serverpb/status.proto, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me68dtQ-nAEa2YKW4AX:-Me68dtRCT6NriBb9rEE:bwztgk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/server/serverpb/status.proto#L226)):*
> ```protobuf
>   int64 write_latches = 17;
>   int64 locks = 18;
>   int64 locks_with_wait_queues = 19;
> ```

I think the last 3 would benefit from comments

**Comment by andreimatei** [comment]
Consider adding longest-held lock/latch info.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Consider adding longest-held lock/latch info.

+1. Fine to do some of this in followup PRs since it will be require data-structure changes.

One thing to fully flesh out would be how we expect these to be used:
Someone looks at the cluster graphs which show the max value of these metrics across all nodes. When that is high, ungroups the metrics to find the node with the max. Goes to the node, and finds (how? clicking on each range in the db console wouldn't be feasible) the range responsible for the max (or the top-k ranges). Then looks at the top-k keys in the range with the longest queues or oldest waiters (how?).

> Reviewed 12 of 12 files at r1, 25 of 25 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-:-MeAWH7L-voy3oq86n3N:b4fjabb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_metrics.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-MeAEwvP4xA7efttLWT4:-MeAEwvQAz4MsMdWsP-S:bx7lx6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/replica_metrics.go#L145)):*
> ```Go
> 	}
> 
> 	m.ReadLatches = latchMetrics.LocalReadCount + latchMetrics.GlobalReadCount
> ```

Was the distinction between local and global key latches, that we no longer have with this change. ever useful in troubleshooting?

Also, can we simplify this a bit by add ing`LatchMetrics` and `LockMetrics` as fields in `ReplicaMetrics` instead of flattening the structs.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 348 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me6Cj0wB0kYteV6yNif:-MeAIMdLDPrwaWaW9FjS:b-st800h) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/concurrency/lock_table.go#L348)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

i don't know what we're talking about here, but are we afraid of a bug or just a perf (or memory?) optimization? If it's the latter, I'd hint to it in the TODO, otherwise it sounds scary.
</blockquote></details>

Memory optimization, but a pretty important one. Looks like we are not decrementing the refs in the btree except when we take another snapshot for the same guard. Which means more allocations for the copy-on-write approach.
___
*[pkg/kv/kvserver/concurrency/metrics.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me6FZxq55zwErsOWCDN:-MeASTp28vhIvcXw1l8H:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/concurrency/metrics.go#L23)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think pretty much all the fields here would benefit from comments :)
</blockquote></details>

+1
___
*[pkg/kv/kvserver/intentresolver/metrics.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me68FXY9E6XgCxF4vAa:-MeACZW4-7f0N1uJ87ZB:b-8dn81c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c32aefd6942cfad65c4f7b49c193367d7614fbe/pkg/kv/kvserver/intentresolver/metrics.go#L23)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

while you're here, mind putting a comment on this one with some words about what it means?
</blockquote></details>

Also it is hard to for me to understand the difference between these 2 metrics given the current comments, so anything that helps with that would be good. And the units would be helpful -- I think this one is in number of txns, while the next one is in number of requests (single intent or intent range). And IIUC we'll count in both places when a txn is cleaning up its intents, while the next one also includes intent resolution done by others.
___
*[pkg/kv/kvserver/kvserverpb/state.proto, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-MeATlmF05quWnHfVATe:-MeATlmF05quWnHfVATf:b-ovgho7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0fd136a538b22cbf9bfff03b2885b7783711aa/pkg/kv/kvserver/kvserverpb/state.proto#L166)):*
> ```protobuf
>   // lock_table contains a textual representation of the contents of the lock
>   // table.
>   string lock_table = 17;
> ```

was this string showing up in the db console?

A summary, such as the top-5 keys with the longest queues, and longest wait durations would be useful.
___
*[pkg/kv/kvserver/spanlatch/manager.go, line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me69W-a2kHKoEiF_py1:-MeAUMtb76pRgBAkhTyY:b-jqlf3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/spanlatch/manager.go#L562)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I've clicked around a bit and generally failed to find info about the distinction between global and local latches. I think a comment somewhere spelling out why there's separate (perhaps something about MVCC access?)  would be good.
</blockquote></details>

I don't understand this either, since we are not making this distinction for the lock table metrics. Was it originally a concern about latching for some particular range local keys, like range descriptor keys?

**Review by nvb — COMMENTED** [review]
> @nvanbenschoten should we expose these metrics in a dashboard? Are these metrics something a customer could look at and take action, or mostly for CRDB use? Happy to make a ticket for our team to pick up.

Good question. I think we could expose these metrics in a dashboard, but I'd want to defer to your team on the exact organization of them because these are all "contention" related and I know you have been thinking a lot about contention observability lately.

> +1. Fine to do some of this in followup PRs since it will be require data-structure changes.

:thumbsup: I opened https://github.com/cockroachdb/cockroach/issues/67619 to track this.

> One thing to fully flesh out would be how we expect these to be used:
Someone looks at the cluster graphs which show the max value of these metrics across all nodes. When that is high, ungroups the metrics to find the node with the max. Goes to the node, and finds (how? clicking on each range in the db console wouldn't be feasible) the range responsible for the max (or the top-k ranges). Then looks at the top-k keys in the range with the longest queues or oldest waiters (how?).

Agreed, this is an important story that we should be able to tell. There has been discussion in the past about contention visualization and hotspot visualization, along the lines of https://cloud.google.com/bigtable/docs/keyvis-overview and https://docs.pingcap.com/tidb/stable/troubleshoot-hot-spot-issues. I don't know where those projects currently stand. cc. @thtruo.

With these new metrics, I think the process for a CRL engineer will be:
1. Observe high `kv.concurrency.max_lock_wait_queue_waiters_for_lock` metric.
2. Drill down to find which node it's on using a custom chart.
3. Look at the hot ranges page to find what range it's likely on, with the assumption that the hottest range is also the most contended. This isn't great because of the assumption it's making.
4. Look at that range's status page `/_status/range/[range_id]` and find `topKLocksByWaitQueueWaiters`

Or, from a debug.zip, the process can be automated as:
```
➜ jq --slurp 'map(.top_k_locks_by_wait_queue_waiters) | flatten | max_by(.waiters)' nodes/*/ranges/*.json
{
  "pretty_key": "/Table/57/1/1/0",
  "key": "vYmJiA==",
  "held": true,
  "waiters": 18,
  "waiting_writers": 16
}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-:-Mea7YyJ7SRkeizUp9lh:b-t8bm4r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_metrics.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-MeAEwvP4xA7efttLWT4:-Mea9Iiz5tnDD1j7yeNm:bg1rilm) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/replica_metrics.go#L145)):*
> Was the distinction between local and global key latches, that we no longer have with this change. ever useful in troubleshooting?

No, not once. I removed the distinction.

> Also, can we simplify this a bit by add ingLatchMetrics and LockMetrics as fields in ReplicaMetrics instead of flattening the structs.

Done.
___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me6AwgiBvKblkaBi1l4:-MeaA4wyAvRZsmbbU3zI:bebktfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0fd136a538b22cbf9bfff03b2885b7783711aa/pkg/kv/kvserver/concurrency/concurrency_control.go#L302)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

You sure you wanna take this away (and the corresponding field in the range state proto)?
In fact, instead of taking it away, how about including timing info in it so we can tell how long locks have been held for?
</blockquote></details>

I don't think we've ever found this useful and I'm also concerned with running this in production due to the efficiency of `(*lockTable).String`. It was added on a whim in 7c84afc because we didn't have anything better. I've added a top-k summary of locks based on wait-queue length to the range debug page that I think will be more useful.
___
*[pkg/kv/kvserver/concurrency/metrics.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me6FZxq55zwErsOWCDN:-MeaSXhU7AAcSGrQKCmo:b-f7ifel) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/concurrency/metrics.go#L23)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done. I also reworked a bit of this to support a top-k ordering of locks by wait-queue length and also eventually by duration (#67619).
___
*[pkg/kv/kvserver/intentresolver/metrics.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me68FXY9E6XgCxF4vAa:-Meb-wfg2fXcqXPnQLWf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c32aefd6942cfad65c4f7b49c193367d7614fbe/pkg/kv/kvserver/intentresolver/metrics.go#L23)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Also it is hard to for me to understand the difference between these 2 metrics given the current comments, so anything that helps with that would be good. And the units would be helpful -- I think this one is in number of txns, while the next one is in number of requests (single intent or intent range). And IIUC we'll count in both places when a txn is cleaning up its intents, while the next one also includes intent resolution done by others.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/kvserverpb/state.proto, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-MeATlmF05quWnHfVATe:-MeaBiR-EzR1r8ezoBue:b-o3yr2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0fd136a538b22cbf9bfff03b2885b7783711aa/pkg/kv/kvserver/kvserverpb/state.proto#L166)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

was this string showing up in the db console?

A summary, such as the top-5 keys with the longest queues, and longest wait durations would be useful.
</blockquote></details>

Not in the db console, but it was possible to get to from a debug.zip, though I don't think we ever did. But I had concerns about printing the full debug string here, which can be very expensive and also disruptive. 

What we're adding in this PR will be accessible through the db console's debug pages and through debug.zips. I added a top-k listing of locks, sorted by wait-queue length, and then included more information about each lock, including the key (pretty and raw), whether it is held or not, and the breakdown of its queues. Once we add timing information (#67619), that can be added here as well.
___
*[pkg/kv/kvserver/spanlatch/manager.go, line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-Me69W-a2kHKoEiF_py1:-MeaD8Zv5tHtRgp_cJ8L:bbr3741) ([raw file](https://github.com/cockroachdb/cockroach/blob/252266a09b8ca09066dfffcbece2af2b9b7ac612/pkg/kv/kvserver/spanlatch/manager.go#L562)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand this either, since we are not making this distinction for the lock table metrics. Was it originally a concern about latching for some particular range local keys, like range descriptor keys? 
</blockquote></details>

I collapsed these, as it didn't look like we ever cared about this distinction.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 30 files at r4, 1 of 29 files at r7, 25 of 25 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-:-Meh-Jfm-ukoaVGJfJzq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/kvserverpb/state.proto, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67350#-MeATlmF05quWnHfVATe:-Megzo8q80K4SYPXEu7t:b9xi8k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0fd136a538b22cbf9bfff03b2885b7783711aa/pkg/kv/kvserver/kvserverpb/state.proto#L166)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Not in the db console, but it was possible to get to from a debug.zip, though I don't think we ever did. But I had concerns about printing the full debug string here, which can be very expensive and also disruptive. 

What we're adding in this PR will be accessible through the db console's debug pages and through debug.zips. I added a top-k listing of locks, sorted by wait-queue length, and then included more information about each lock, including the key (pretty and raw), whether it is held or not, and the breakdown of its queues. Once we add timing information (#67619), that can be added here as well.
</blockquote></details>

excellent

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r=sumeerbhola,andreimateidhartunian

**Pull request merged**
