### PR TITLE
roachtest: make upgrade timeouts configurable

### PR DESCRIPTION
**Pull request by renatolabs**
This commit makes the timeout applied when waiting for a cluster
upgrade configurable. Previously, a fixed 10 minute timeout would
apply regardless of the test.

A new option is added to `mixedversion` tests to specify custom
upgrade timeouts; this is especially useful in tests that operate on
larger volumes of data and upgrades that may include expensive
migrations.

Informs: #107414

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
As a sanity check, `acceptance/version-upgrade` and `backup-restore/mixed-version` (two tests that use `mixedversion`) passed: <https://teamcity.cockroachdb.com/viewLog.html?buildId=11052594&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv>.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107529)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 279 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107529#-NaIWGRJ6MNiAbMNeFyk:-NaIWGRJ6MNiAbMNeFyl:bn1ngv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a27bf09fe5c244c26370f15668ee0aa7d1b6201/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L279)):*
> ```Go
> 		})
> 		if err != nil {
> 			return fmt.Errorf(
> ```

Should we maybe wrap the original `err` here just in case it is something unexpected?

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107529)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 279 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107529#-NaIWGRJ6MNiAbMNeFyk:-NaIhDOn-vLgVXo81JLi:bo8006c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a27bf09fe5c244c26370f15668ee0aa7d1b6201/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L279)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Should we maybe wrap the original `err` here just in case it is something unexpected?
</blockquote></details>

Good point! Updated.

**Review by herkolategan — APPROVED** [review]
:lgtm:
Just the one small typo nit in one of the comments.

> Reviewed 2 of 5 files at r1, 1 of 5 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107529#-:-NaIwtLX7mXeTQOFiRGU:bjh1029)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go` line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107529#-NaIwbVk9lWoDXaL73XS:-NaIwbVk9lWoDXaL73XT:bodxrvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f2492f1adc53c782f42ebf72fafa45f1056022f/pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go#L263)):*
> ```Go
> 
> // Test_upgradeTimeout tests the behaviour of upgrade timeouts in
> // mixedversion tests. If not custom value is passed, the default
> ```

Nit: No

**Comment by renatolabs** [comment]
TFTR!

bors r=herkolategan

**Pull request merged**
