### PR TITLE
kvserver: assorted closedts improvements and bug fixes

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
The last commit is quite nice!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-:-MY6QIWI2Ypo3Q4Tto_G:bs1ms6v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica.go, line 265 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6HYzQ-1w-xL0Um2ec:-MY6HYzQ-1w-xL0Um2ed:biy6dry) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica.go#L265)):*
> ```Go
> 	tenantLimiter tenantrate.Limiter
> 
> 	sideTransportClosedTimestamp sideTransportClosedTimestamp
> ```

Give this field a comment. Similar to the one we used to have on `sideTransportClosedTimestamp` which discussed the relationship between this closed timestamp and the one in `state.RaftClosedTimestamp`.
___
*[pkg/kv/kvserver/replica_closedts.go, line 175 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6LYXo5acmPfZm_QHe:-MY6LYXo5acmPfZm_QHf:b9ca86a) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L175)):*
> ```Go
> }
> 
> // sideTransportClosedTimestamp encapsulates state related to the closed
> ```

nit: this name isn't saying as much as I think it could. I was expecting something like `sideTransportHandle` or something that made it clear that this is a per-range reference to the sideTransport, along with a bit of memory. Do you have ideas for how we could improve this?
___
*[pkg/kv/kvserver/replica_closedts.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6J3xp25ltxIgxTzez:-MY6J3xp25ltxIgxTzf-:bt5gc1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L191)):*
> ```Go
> // independent of the source.
> type sideTransportClosedTimestamp struct {
> 	rngID    roachpb.RangeID
> ```

nit: this is named `rangeID` everywhere else I look, so let's just keep that consistent.
___
*[pkg/kv/kvserver/replica_closedts.go, line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6JUkHExJM3ECGq-Le:-MY6JUkHExJM3ECGq-Lf:b-3joysp) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L197)):*
> ```Go
> 		// closed is the cached info about the closed timestamp that was
> 		// communicated by the side transport. The replica can use it if it has
> 		// applied all the commands with indexes <= lai.
> ```

nit: let's say "applied commands up to lai". "all the commands" is a little ambiguous, because we reject some commands below raft and occasionally skip LAIs.
___
*[pkg/kv/kvserver/replica_closedts.go, line 198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6JhyyC_TMBZhT45Cg:-MY6JhyyC_TMBZhT45Ch:b-wv5akp) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L198)):*
> ```Go
> 		// communicated by the side transport. The replica can use it if it has
> 		// applied all the commands with indexes <= lai.
> 		closed hlc.Timestamp
> ```

nit: either `ts` or `closedTimestamp`.
___
*[pkg/kv/kvserver/replica_closedts.go, line 203 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6KADv1aOXMIfdWFxR:-MY6KADv1aOXMIfdWFxS:bcqw2sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L203)):*
> ```Go
> }
> 
> // receiver abstracts *sidetransport.Receiver.
> ```

`receiver` is a pretty ambigious name to leak into the `pkg/kv/kvserver` namespace. Can we make it more specific?
___
*[pkg/kv/kvserver/replica_closedts.go, line 223 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6KyNt6T8GOPKCjelx:-MY6KyNt6T8GOPKCjely:b2513ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L223)):*
> ```Go
> 		r.mu.lai = lai
> 	}
> 	r.mu.Unlock()
> ```

nit: defer this.
___
*[pkg/kv/kvserver/replica_closedts.go, line 226 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6P9rXBeZtb3E3ANoY:-MY6P9rXBeZtb3E3ANoZ:b-haza59) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L226)):*
> ```Go
> }
> 
> // get returns the closed timestamp that the side transport knows for the range.
> ```

Is it safe to call this without holding the replica read lock? I think so, but let's call it out explicitly. Specifically, if we allow that, we'll need to think of cases where `appliedLAI` regresses across calls to the function.
___
*[pkg/kv/kvserver/replica_closedts.go, line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6NUPz9TveQQz2zrD1:-MY6NUQ-Ck6GMOjzHl5o:b-4knf6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L267)):*
> ```Go
> 		// closed timestamp.
> 		r.mu.Lock()
> 		if r.mu.closed.Less(closed) {
> ```

nit: `if r.mu.closed.Forward(closed) { r.mu.lai = receiverLAI }` for a bit more symmetry?

Actually, is this just `r.forward(ctx, closed, receiverLAI)`? That would be nice.
___
*[pkg/kv/kvserver/replica_follower_read.go, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6P09X-VWethWym9yA:-MY6P09X-VWethWym9yB:b-vxipo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_follower_read.go#L156)):*
> ```Go
> 	r.mu.RLock()
> 	defer r.mu.RUnlock()
> 	res, ok := r.maxClosedRLocked(ctx, hlc.Timestamp{} /* sufficient */)
> ```

`return r.maxClosedRLocked...`
___
*[pkg/kv/kvserver/replica_init.go, line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6PrGiAOfIoFkpYw_x:-MY6PrGiAOfIoFkpYw_y:b-ypk1bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_init.go#L220)):*
> ```Go
> 	r.assertStateRaftMuLockedReplicaMuRLocked(ctx, r.store.Engine())
> 
> 	r.sideTransportClosedTimestamp.receiver = r.store.cfg.ClosedTimestampReceiver
> ```

Let's create an `init` method to replace this in case we want to add more fields.
___
*[pkg/kv/kvserver/replica_send.go, line 469 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6Q8032j2Rd8_AyyTa:-MY6Q804BjgeXvsGq_Yc:btx67u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_send.go#L469)):*
> ```Go
> 	// closed timestamp before consulting the lease.
> 
> 	var update replicaUpdate
> ```

Do we still need this?
___
*[pkg/kv/kvserver/replica_send.go, line 476 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6QDdJBJ_mgT8ezOYz:-MY6QDdJBJ_mgT8ezOZ-:bu8bk6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_send.go#L476)):*
> ```Go
> 	var ok bool
> 	ok = r.canServeFollowerReadRLocked(ctx, ba, pErr.GoError())
> 	if ok {
> ```

`if r.canServeFollowerReadRLocked(ctx, ba, pErr.GoError()) {
___
*[pkg/kv/kvserver/replica_tscache.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6F7KkAvu4QU5_69Ev:-MY6F7KkAvu4QU5_69Ew:bjr8u8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b56f884db1343dc19aa5ad87c74604e86ce3ee7/pkg/kv/kvserver/replica_tscache.go#L292)):*
> ```Go
> 	ctx context.Context, ba *roachpb.BatchRequest, minReadTS hlc.Timestamp,
> ) bool {
> 	if !ba.IsIntentWrite() {
> ```

Is this short-circuiting worth it? `BatchRequest.IsIntentWrite` still loops over each request, so it's identical to what we have below, isn't it? So aren't we just creating more work for batches that are intent writes?
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6H98lBS-snI3eUn_I:-MY6H98m86JQ7oOKtfBC:b-70mwxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bd104b67843e47c480660dbcedfe50adf7f15b/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L130)):*
> ```Go
> 	}
> 	if nodeID != 0 {
> 		// Remove the connection from the map, awaiting a new open to be opened by
> ```

"a new open"

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica.go, line 265 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6HYzQ-1w-xL0Um2ec:-MYHNH8VBTyFYBXJEUXE:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica.go#L265)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this field a comment. Similar to the one we used to have on `sideTransportClosedTimestamp` which discussed the relationship between this closed timestamp and the one in `state.RaftClosedTimestamp`.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts.go, line 175 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6LYXo5acmPfZm_QHe:-MYHNZ0aBHxb76sUo0hr:b1eb4aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L175)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this name isn't saying as much as I think it could. I was expecting something like `sideTransportHandle` or something that made it clear that this is a per-range reference to the sideTransport, along with a bit of memory. Do you have ideas for how we could improve this?
</blockquote></details>

made it `sideTransportAccess`
___
*[pkg/kv/kvserver/replica_closedts.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6J3xp25ltxIgxTzez:-MYHNkJUCDaU4VteHbCC:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this is named `rangeID` everywhere else I look, so let's just keep that consistent.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts.go, line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6JUkHExJM3ECGq-Le:-MYHNsI6CbFfAIK2Xyga:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L197)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: let's say "applied commands up to lai". "all the commands" is a little ambiguous, because we reject some commands below raft and occasionally skip LAIs.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts.go, line 198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6JhyyC_TMBZhT45Cg:-MYHO-HS2QwAFHYyKCqn:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L198)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: either `ts` or `closedTimestamp`.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts.go, line 203 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6KADv1aOXMIfdWFxR:-MYHOF0pBQYOZzNKYPcZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L203)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`receiver` is a pretty ambigious name to leak into the `pkg/kv/kvserver` namespace. Can we make it more specific?
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts.go, line 223 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6KyNt6T8GOPKCjelx:-MYHOJdr9BrxG96PQflG:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L223)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: defer this.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts.go, line 226 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6P9rXBeZtb3E3ANoY:-MYHOYXE4bPOAUvTJI8w:b-ko2eda) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L226)):*
> Is it safe to call this without holding the replica read lock? I think so, but let's call it out explicitly.

done

> Specifically, if we allow that, we'll need to think of cases where appliedLAI regresses across calls to the function.

How do you mean? How would appliedLAI regress? :S
___
*[pkg/kv/kvserver/replica_closedts.go, line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6NUPz9TveQQz2zrD1:-MYHPb2F8thSt0H86OFZ:b13abkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L267)):*
> That would be nice.

Done
___
*[pkg/kv/kvserver/replica_follower_read.go, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6P09X-VWethWym9yA:-MYHPiLP-prYYBvzPYhh:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_follower_read.go#L156)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`return r.maxClosedRLocked...`
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_init.go, line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6PrGiAOfIoFkpYw_x:-MYHQ71Z8m-_9Df3Jc1w:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_init.go#L220)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's create an `init` method to replace this in case we want to add more fields.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_send.go, line 469 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6Q8032j2Rd8_AyyTa:-MYHQSdsD-UxGmAYxY_Z:b-u3i7m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_send.go#L469)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we still need this?
</blockquote></details>

removed, thanks
___
*[pkg/kv/kvserver/replica_send.go, line 476 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6QDdJBJ_mgT8ezOYz:-MYHQXe3-KIPQ0ATgcys:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_send.go#L476)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`if r.canServeFollowerReadRLocked(ctx, ba, pErr.GoError()) {
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_tscache.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6F7KkAvu4QU5_69Ev:-MYHMb9SD5rYRk2TELNP:b9s5cpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b56f884db1343dc19aa5ad87c74604e86ce3ee7/pkg/kv/kvserver/replica_tscache.go#L292)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this short-circuiting worth it? `BatchRequest.IsIntentWrite` still loops over each request, so it's identical to what we have below, isn't it? So aren't we just creating more work for batches that are intent writes?
</blockquote></details>

ok, dropped this commit
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6H98lBS-snI3eUn_I:-MYHMvVM7ogHN-Catvv8:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bd104b67843e47c480660dbcedfe50adf7f15b/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"a new open"
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 3 files at r7, 1 of 2 files at r8, 8 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-:-MYIeC1TAOfvK1IziS1u:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_closedts.go, line 226 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6P9rXBeZtb3E3ANoY:-MYIc_UT5l83lndBIXoF:bc4t6vu) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L226)):*
> How would appliedLAI regress? :S

What I meant was that if we don't require the replica.mu to be held then two concurrent callers could provide different `appliedLAI`s, and if the caller with the larger LAI is faster, then from the perspective of this method, the `appliedLAI` will regress. I think that's fine, because it's the `receiverLAI` that we push through `sideTransportAccess.Forward`, but it's something to be aware of.
___
*[pkg/kv/kvserver/replica_closedts.go, line 204 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MYIcPiZ6SO4xt_mkTji:-MYIcPiZ6SO4xt_mkTjj:b-qudx33) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f778c54123af93fbc73533303abc70ff03bbfd7/pkg/kv/kvserver/replica_closedts.go#L204)):*
> ```Go
> }
> 
> // sidetransportReceiver abstracts *sidetransport.Receiver.
> ```

nit: either `sideTransport` for both of these types, or `sidetransport`.
___
*[pkg/kv/kvserver/replica_closedts_internal_test.go, line 100 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MYIdPZu5uwd_vE2RPMV:-MYIdPZu5uwd_vE2RPMW:bbx2o61) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f778c54123af93fbc73533303abc70ff03bbfd7/pkg/kv/kvserver/replica_closedts_internal_test.go#L100)):*
> ```Go
> 			// We expect no usable closed timestamp to be returned. And also we expect
> 			// the local state to not be updated because the LAI from the receiver has
> 			// not bee applied by the replica.
> ```

"been"

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63357)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_closedts.go, line 226 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MY6P9rXBeZtb3E3ANoY:-MYNDgFbBEi_uoBkcO9_:b-fzuac0) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d9b423a522b0c58dd7ca8d60f16c75111d2664/pkg/kv/kvserver/replica_closedts.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> How would appliedLAI regress? :S

What I meant was that if we don't require the replica.mu to be held then two concurrent callers could provide different `appliedLAI`s, and if the caller with the larger LAI is faster, then from the perspective of this method, the `appliedLAI` will regress. I think that's fine, because it's the `receiverLAI` that we push through `sideTransportAccess.Forward`, but it's something to be aware of.
</blockquote></details>

I see. I've added a note explaining this race and saying that the caller with a smaller LAI might get back an empty result.
___
*[pkg/kv/kvserver/replica_closedts.go, line 204 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MYIcPiZ6SO4xt_mkTji:-MYNCmck4uDmuYoTSzWM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f778c54123af93fbc73533303abc70ff03bbfd7/pkg/kv/kvserver/replica_closedts.go#L204)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: either `sideTransport` for both of these types, or `sidetransport`.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts_internal_test.go, line 100 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-MYIdPZu5uwd_vE2RPMV:-MYNDnjD2fKjhwlY8tMs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f778c54123af93fbc73533303abc70ff03bbfd7/pkg/kv/kvserver/replica_closedts_internal_test.go#L100)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"been"
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-:-MYfyoi2A_ImkiBk01Q4:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r11, 1 of 1 files at r12, 9 of 9 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63357#-:-MYg2kxM5M_1RvLlf_Cr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
