### PR TITLE
tree,optbuilder: store annotations for each UDF body statement

### LINKED ISSUE #104242: roachtest: sqlsmith: index out of range in schema changer with CREATE FUNCTION
roachtest.sqlsmith/setup=rand-tables/setting=no-mutations [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10356406?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10356406?buildTab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations) on master @ [bf25b7bf93a6b8e57557813957da263389796bb4](https://github.com/cockroachdb/cockroach/commits/bf25b7bf93a6b8e57557813957da263389796bb4):

```
test artifacts and logs in: /artifacts/sqlsmith/setup=rand-tables/setting=no-mutations/run_1
(sqlsmith.go:248).func3: error: pq: internal error: building declarative schema change targets for CREATE FUNCTION: runtime error: index out of range [1] with length 1
stmt:
CREATE FUNCTION "fun""c159"(IN p0 FLOAT8, IN p1 NAME)
	RETURNS RECORD
	NOT LEAKPROOF
	LANGUAGE SQL
	AS $funcbody$SELECT NULL AS col10641, 0.02274592984327417:::FLOAT8 AS col10642 FROM defaultdb.public."table\\U000A6F2A2"@"table\\U000A6F2A2_co}l2_1_%vcol2😊_4_col2_0_col2_2_co%ql2 _3_key" AS tab4292 WHERE NULL::rand_typ_0 IN () LIMIT 95:::INT8;
SELECT (true,) AS col10643 FROM defaultdb.public.table4@"table4_expr_col4_0_col4\\u00D8_*4_col4_1_c ol/4_2_key" AS " t\\U000BEE29ab4293", defaultdb.public."t	able3"@[0] AS t😶ab😨4294 WHERE NULL ORDER BY " t\\U000BEE29ab4293".col4_0 DESC NULLS FIRST, t😶ab😨4294.col3😋_0 NULLS FIRST, t😶ab😨4294.col3_13 DESC LIMIT 91:::INT8$funcbody$;
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28424

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/104242

This also fixes a related issue where user-defined types that was references in UDF bodies would not be shown in the CREATE FUNCTION statement. This problem was being masked by the main issue that is getting fixed.

Release note (bug fix): Previously, referencing a user-defined type in the body of a user-defined function would result in an error at the time of creating the function. This is now fixed.

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
Thanks for working on this! It looks like there's a panic in `TestParseDatadriven` - maybe should be fixed by passing the `FmtAnnotations` option to the calls to `AsStringWithFlags` in `VerifyStatementPrettyRoundtrip`? Maybe we should also consider changing the behavior for `UnresolvedObjectName.Format` to avoid annotation lookup if the `annotations` slice is nil.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105465#-:-NYfdk7g9oPA1T18bcyw:bajpy5h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @msirek, and @rafiss)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105465#-NYfcnYt4Nw1fM1rG5OH:-NYfcnYt4Nw1fM1rG5OI:bqdgy14) ([raw file](https://github.com/cockroachdb/cockroach/blob/80dc23d3ca32a8203b982afb1ffa4cdabbfc27d9/pkg/sql/opt/optbuilder/create_function.go#L172)):*
> ```Go
> 		// the volatility.
> 		b.factory.FoldingControl().TemporarilyDisallowStableFolds(func() {
> 			stmtScope = b.buildStmt(stmts[i].AST, nil /* desiredTypes */, bodyScope)
> ```

I don't know if it actually has any effect right now, but should we set `b.semaCtx.Annotations` and `b.evalCtx.Annotations` here before building the statement / resolving objects within it?

**Review by rafiss — COMMENTED** [review]
> maybe should be fixed by passing the FmtAnnotations option to the calls to AsStringWithFlags in VerifyStatementPrettyRoundtrip? Maybe we should also consider changing the behavior for UnresolvedObjectName.Format to avoid annotation lookup if the annotations slice is nil.

I figured out that we actually don't need the separate Annotations slice for `RoutineBody` -- all those statements are parsed during the main SQL parsing, so the annotations slice properly reflects any unresolved names in the `RoutineBody` already.

we only need the extra annotations slice for the parsing of the `FunctionBodyStr` that happens in the optbuilder.

i don't think it's correct to add a nil check for this case

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105465#-:-NYsAI4H8EO_lrLcZg_N:brin0jx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @DrewKimball, and @msirek)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105465#-NYfcnYt4Nw1fM1rG5OH:-NYs9t34-XwE97pG7ljG:bgxdrpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/80dc23d3ca32a8203b982afb1ffa4cdabbfc27d9/pkg/sql/opt/optbuilder/create_function.go#L172)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I don't know if it actually has any effect right now, but should we set `b.semaCtx.Annotations` and `b.evalCtx.Annotations` here before building the statement / resolving objects within it?
</blockquote></details>

that's a great idea

**Review by DrewKimball — APPROVED** [review]
Nice work! :lgtm:

>I figured out that we actually don't need the separate Annotations slice for `RoutineBody` -- all those statements are parsed during the main SQL parsing, so the annotations slice properly reflects any unresolved names in the `RoutineBody` already.

Oh, nice catch.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105465#-:-NYt4sjr2pEh4hSVUZVL:b-bztugk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @msirek, and @rafiss)

___
*[`pkg/sql/opt/optbuilder/testdata/create_function` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105465#-NYt6IbK4eMZD5tq-1sD:-NYt6IbK4eMZD5tq-1sE:b-pohcfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/22dabb08e76decbe2fc1c091431e05ebfba5e73f/pkg/sql/opt/optbuilder/testdata/create_function#L57)):*
>x'40':::@100001

Is this formatting expected?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105465)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @100001, @chengxiong-ruan, @DrewKimball, and @msirek)

___
*[`pkg/sql/opt/optbuilder/testdata/create_function` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105465#-NYt6IbK4eMZD5tq-1sD:-NYtFQaC6u_9ph9zQ_lE:bg9gk1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/22dabb08e76decbe2fc1c091431e05ebfba5e73f/pkg/sql/opt/optbuilder/testdata/create_function#L57)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

>x'40':::@100001

Is this formatting expected?
</blockquote></details>

yeah this is the serialized format of the statement. it's needed so that references to user-defined type names+values are stable

**Comment by rafiss** [comment]
tftr!

bors r=DrewKimball

**Comment by rafiss** [comment]
I made a followup to this: https://github.com/cockroachdb/cockroach/pull/105581

**Comment by rafiss** [comment]
Removed 22.2 backport label, since this works there. (since `tree.CreateFunction` doesn't have a `BodyStatements` field where the statements get reparsed by the optimizer.)

**Pull request merged**
