### PR TITLE
release-21.1: colexec: handle panics in Init gracefully by the materializer

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/2 commits from #62126.

/cc @cockroachdb/release

---

**colexec: handle panics in Init gracefully by the materializer**

The materializer wraps the call to `Init` on its input with
a panic-catcher. Previously, if an error is encountered, the
materializer would transition into draining state which would later
drain all of the metadata sources given to it in the constructor.
However, because of a panic in `Init`, those sources might have not been
properly initialized, so draining them might be an unsafe operation.
Instead, we want the materializer to return the error it caught and shut
down the flow. We can achieve this by tweaking the drain helper a bit so
that it drains the inputs only if no error was encountered by the
materializer.

Fixes: #61588.
Fixes: #62061.

Release note: None (no stable release with the bug that could lead to
crashes because of this issue)

### CODE REVIEW

**Comment by asubiotto** [comment]
What's the thinking behind backporting the first commit? It's more of a cleanup than a bugfix to me (might be missing something) so would prefer to just backport the second commit for safety.

**Comment by yuzefovich** [comment]
I added the first commit because I saw failed assertions (with `util.CrdbTestBuild`) when debugging #61588 manually. If for `sqlsmith` roachtest we were using binaries built with `TAGS=crdb_test`, then without the first commit, the test would be failing, but since we don't use the tag, it won't. I think I'm ok with backporting only the second commit.

**Comment by yuzefovich** [comment]
PTAL.

**Review by asubiotto — APPROVED** [review]
LGTM, thanks! I asked because I think we've gotten to the stage where we're trying to reduce the number of backports to those strictly necessary.

**Pull request merged**
