### PR TITLE
backupccl: write dropped version of schema to speed up lease eviction

### LINKED ISSUE #89079: backupccl,sql: lease on schema deleted by restore's OnFailOrCancel not purged from lease manager
**Describe the problem**

In restore's `OnFailOrCancel`, we drop all of the descriptors that we created during the restore.  These descriptors may have already been made public and thus may be leased.

When we drop schemas, we delete the descriptor and namespace keys and then notify the descriptor collection.  But, notably, we never write a version of the descriptor in a Dropped state:

https://github.com/cockroachdb/cockroach/blob/857c7e0a7725d76bacd9777cbffaed1b90904d12/pkg/ccl/backupccl/restore_job.go#L2457-L2466

The lease manager maintains a rangefeed on the lease table. This rangefeed drives the eviction of leases in the event of a descriptor change.  However, the event processing depends on the rangefeed event having a value.  The rangefeed event for a descriptor that is simply deleted will not have a value and the lease manager will do nothing with the event:

https://github.com/cockroachdb/cockroach/blob/857c7e0a7725d76bacd9777cbffaed1b90904d12/pkg/sql/catalog/lease/lease.go#L1133-L1135

As a result, `OnFailOrCancel` may need to wait for the full lease duration even in cases when the lease could have been easily evicted.

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, in restore's OnFailOrCancel, we dropped schemas by directly deleting them from the namespace and descriptor tables and then notifying the descriptor collection.

While this works, it can result in having to wait longer than necessary for leases on the dropped schemas to expire.

The schema's may be leased because they may have come online if the restore fails after the descriptors have been made public.

When descriptors are deleted, the transaction that commits the delete needs to wait until there are no leased versions of that descriptor.

The lease manager maintains a rangefeed on the descriptor table. This rangefeed drives the eviction of leases in the event of a descriptor change. However, the event processing depends on the rangefeed event having a value. The rangefeed event for a descriptor that is simply deleted will not have a value and the lease manager will do nothing with the event.

As a result, OnFailOrCancel might have to wait for the entire lease duration in the face of a leased schema descriptor.

It looks to me from the code that this could also be affecting other descriptors that we delete in OnFailOrCancel, but here I've only addressed schema.

Fixes #89079

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
I wonder if instead of this we should be handling deletion events from the rangefeed.  We could parse the descriptor ID out of the key and use that to purge leases.

**Comment by ajwerner** [comment]
Yes, descriptors should move to dropped before being deleted.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89083)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @stevendanna)

___
*[`pkg/ccl/backupccl/restore_job.go` line 2468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89083#-NDEnoCu8FG3gKBjNQtO:-NDEnoCu8FG3gKBjNQtP:b-mwcqr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ca24fd2a8324916b49c7a58d488b9bff3522e3/pkg/ccl/backupccl/restore_job.go#L2468)):*
> ```Go
> 		// Delete schema entries in descriptor and namespace system tables.
> 		b.Del(catalogkeys.EncodeNameKey(codec, mutSchema))
> 		b.Del(catalogkeys.MakeDescMetadataKey(codec, mutSchema.GetID()))
> ```

If you delete the descriptor in the same transaction which sets it dropped, you're not doing anything. The fact of its being dropped lives on the descriptor which is stored in the descriptor table. If you want to mark the descriptor dropped, you have to do that in one transaction and delete the descriptor in a subsequent transaction. That dance may incur some legitimate complexity. 



_Code quote:_
```Go
		b.Del(catalogkeys.EncodeNameKey(codec, mutSchema))
		b.Del(catalogkeys.MakeDescMetadataKey(codec, mutSchema.GetID()))
		descsCol.NotifyOfDeletedDescriptor(mutSchema.GetID())
```

**Comment by stevendanna** [comment]
> If you delete the descriptor in the same transaction which sets it dropped, you're not doing anything. The fact of its being dropped lives on the descriptor which is stored in the descriptor table. If you want to mark the descriptor dropped, you have to do that in one transaction and delete the descriptor in a subsequent transaction. That dance may incur some legitimate complexity.

Eek. Sorry about this, the branch I pulled this out of had removed the delete completely, which solves the "wait for leases" issue but then leaves the descriptor stranded so then I added the delete back right before pushing without thinking.

I'll look at how complicated it gets to have two transactions.

**Pull request closed without merging**
