### PR TITLE
opt: add FD equivalency for semi-passthrough projection columns

### LINKED ISSUE #43360: opt: incorrect index chosen with constant-folded ORDER BY expression
**Describe the problem**
The user has two similar queries, one query completes in about 2.3s,  user was able to reduce this to 1s appears that the wrong index is being chosen, the other query if quick takes milliseconds. 

Here are both queries: 

This does NOT choose the correct INDEX,
AND IS very slow even WHEN the correct INDEX IS hinted:

```
SELECT id,
CURSOR
FROM
  (SELECT id AS id,
          created AS
   CURSOR
   FROM nodes
   WHERE ((created < '2019-12-11T22:30:17Z')
          OR ((created = '2019-12-11T22:30:17Z')
              AND (id < '')))
     AND organization = '62bcde19-d467-44b6-b693-c76e42a24421'
   ORDER BY CASE
                WHEN FALSE THEN created
            END ASC, CASE
                         WHEN NOT FALSE THEN created
                     END DESC LIMIT 21)
ORDER BY
CURSOR DESC;
```

 This chooses the correct INDEX
AND IS fast:

```
SELECT id,
CURSOR
FROM
  (SELECT id AS id,
          created AS
   CURSOR
   FROM nodes
   WHERE ((created < '2019-12-11T22:30:17Z')
          OR ((created = '2019-12-11T22:30:17Z')
              AND (id < '')))
     AND organization = '62bcde19-d467-44b6-b693-c76e42a24421'
   ORDER BY CASE
                WHEN FALSE THEN 'created ASC'
                ELSE 'created DESC'
            END LIMIT 21)
ORDER BY
CURSOR DESC;
```
Please describe the issue you observed, and any steps we can take to reproduce it:

You can find all the statistics and explains [here](https://docs.google.com/document/d/1O9cix4iOvMXKGhV4phB1KRFA7BKew1G2PW6FmBf9CFc/edit?usp=sharing)

**Expected behavior**

The users application UI uses this query to list all variety of info, so built into it is the ability to page forwards or backwards through the various tables, which accounts for the complexity of the case statement. It's used every time someone logs on, and at unpredictable intervals thereafter. It is critical for the application.  At the moment they have a workaround, however it would be nice to know why the original query was taking so long. 

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2

**Additional context**
Critical query for the users application.

### PR DESCRIPTION
**Pull request by RaduBerinde**
In certain cases, we have synthesized projections that are simple
variable expressions (I hereby name these semi-passthrough). This can
happen for example if a non-trivial expression gets constant folded to
a single variable (perhaps after placeholder replacement). The
optimizer can also construct these to assign different ColumnIDs.

This change adds the equivalency between the semi-passthrough column
and the one it refers to, and also uses it to mark columns as
non-null. This improves the plan when we are ordering on such a
semi-passthrough column (as long as both columns are
projected). There will be a follow-up fix that makes the
`CanProvideOrdering` logic better to handle this case even when the
original column is not projected.

Fixes #43360.

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm:, but maybe add a props test case

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43465#-:-LwiiCti762B249NexdM:b-pik5nw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43465#-Lwii37wAXcUK4gNcm0F:-Lwii37wAXcUK4gNcm0G:b5iosuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/03aa4e115067cd137ae95e89a9bf886adab28881/pkg/sql/opt/memo/logical_props_builder.go#L272)):*
> ```Go
> 			}
> 		}
> 		// Also add any column that is a direct reference to a non-null column.  The
> ```

I'd add a test for this new case into `memo/testdata/logprops/project`.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43465#-:-Lwj9Qy005wvZz_p5qYX:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43465#-Lwii37wAXcUK4gNcm0F:-Lwj9SQP0LQP2Gn0CigH:b8efpkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/03aa4e115067cd137ae95e89a9bf886adab28881/pkg/sql/opt/memo/logical_props_builder.go#L272)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd add a test for this new case into `memo/testdata/logprops/project`.
</blockquote></details>

Done. Added a test for the null column and one for the FD.

**Comment by RaduBerinde** [comment]
Hm, I don't think I pushed that last update

bors r-

**Comment by RaduBerinde** [comment]
Release note (performance improvement): the optimizer generates better execution plans in some cases where there is an ORDER BY expression that simplifies to a simple variable reference.

**Pull request merged**
