### PR TITLE
bazel: build http docs w bazel

### LINKED ISSUE #65814: bazel: add build targets for HTTP API documentation, start building in CI
Build [HTTP API documentation](https://github.com/cockroachdb/cockroach/tree/master/docs/generated/http) with Bazel.

These are generated with `docgen http`.

blocks #65070

Epic CRDB-8306

### PR DESCRIPTION
**Pull request by rickystewart**
We generate this in a different way than the `Makefile` does -- we take
all the proto descriptor sets (that we need to generate anyway as part
of the build) and pass them in to `protoc` rather than passing a bunch
of include paths, which wouldn't work terribly well in the sandbox.

Also teach CI and `dev` to start building these docs.

I deleted a stray comment in `pkg/server/serverpb/admin.proto` that was
causing a diff in the generated file. I also had to patch
`@com_github_pseudomuto_protoc_gen_doc` to quash a compiler error (I
just deleted a dependency that isn't actually necessary).

Closes #65814.

Release note: None

### CODE REVIEW

**Review by rail — CHANGES_REQUESTED** [review]
In overall it looks great. Just a few nits.

> Reviewed 7 of 8 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68834#-:-MhG1GrV-348i7DO1JPW:bn45sw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/cmd/docgen/http.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68834#-MhG-iv72KN_HvFNZpxX:-MhG-iv89iaIJkwOQb7b:byehmeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/02660a0583c7c216367be9e8f10be3c115831792/pkg/cmd/docgen/http.go#L88)):*
> ```Go
> 	}()
> 	var args []string
> 	if len(protocPath) == 0 {
> ```

This check made me think twice. :) Can you use `if protocPath == ""` instead to highlight we are comparing a string and not a slice (`len()` made me think it's a slice).
___
*[pkg/cmd/docgen/http.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68834#-MhG0gLF8pWoTyAaoAIM:-MhG0gLF8pWoTyAaoAIN:bkg3h6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/02660a0583c7c216367be9e8f10be3c115831792/pkg/cmd/docgen/http.go#L95)):*
> ```Go
> 		fmt.Sprintf("--doc_opt=%s,http.json", jsonTmpl),
> 		fmt.Sprintf("--plugin=protoc-gen-doc=%s", genDocPath))
> 	args = append(args, strings.Fields(protocFlags)...)
> ```

It'd be safer to use something like https://pkg.go.dev/github.com/google/shlex, but probably not a big deal now.
___
*[pkg/cmd/docgen/http.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68834#-MhG02oN6excysZwGxFW:-MhG02oO-CJu8BdwHs7g:bqeg1b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/02660a0583c7c216367be9e8f10be3c115831792/pkg/cmd/docgen/http.go#L98)):*
> ```Go
> 	// Generate the JSON file.
> 	executable := protocPath
> 	if len(protocPath) == 0 {
> ```

And same here, can you `if protocPath == ""` instead?

**Review by rickystewart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[pkg/cmd/docgen/http.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68834#-MhG-iv72KN_HvFNZpxX:-MhG2VQx09jX97kXKjBV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02660a0583c7c216367be9e8f10be3c115831792/pkg/cmd/docgen/http.go#L88)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

This check made me think twice. :) Can you use `if protocPath == ""` instead to highlight we are comparing a string and not a slice (`len()` made me think it's a slice).
</blockquote></details>

Done.
___
*[pkg/cmd/docgen/http.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68834#-MhG02oN6excysZwGxFW:-MhG2WOxAxROOPqdx8x3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02660a0583c7c216367be9e8f10be3c115831792/pkg/cmd/docgen/http.go#L98)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

And same here, can you `if protocPath == ""` instead?
</blockquote></details>

Done.

**Review by rail — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
