### PR TITLE
opt: add cost for executing geo functions in filters

### LINKED ISSUE #48214: opt: update coster to account for cost of executing geospatial functions
As described in the [Geospatial RFC](https://github.com/cockroachdb/cockroach/pull/47762), we will need to update the cost model of the optimizer to account for the fact that geospatial functions such as `ST_Covers` are expensive to execute. Currently, the cost model assumes that execution of scalar functions is basically free. We will need to change that assumption for geospatial functions.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #48214

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7JIzX245iLW9it5CTN:-M7JIzX245iLW9it5CTO:bkmmomy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b00bd5b680c699680937aabc421e651baf0f0ee/pkg/sql/opt/xform/coster.go#L318)):*
> ```Go
> 	// The filter has to be evaluated on each input row.
> 	inputRowCount := sel.Input.Relational().Stats.RowCount
> 	cost := memo.Cost(inputRowCount) * cpuCostFactor
> ```

Should this also call computeFiltersCost? Maybe we should move this `cpuCostFactor * rowCount` cost inside that function.
___
*[pkg/sql/opt/xform/coster.go, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7JJO_k3YjiA1ryeidG:-M7JJO_k3YjiA1ryeidH:bm0w4t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b00bd5b680c699680937aabc421e651baf0f0ee/pkg/sql/opt/xform/coster.go#L471)):*
> ```Go
> 	cost += memo.Cost(rowsProcessed) * perRowCost
> 
> 	cost += c.computeFiltersCost(join.On, util.FastIntMap{}, lookupCount)
> ```

this should be `rowsProcessed` not `lookupCount`
___
*[pkg/sql/opt/xform/coster.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7JI2uz1DhvWYEqS_LI:-M7JI2v-AbfOsyzO2flW:b-jot8pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b00bd5b680c699680937aabc421e651baf0f0ee/pkg/sql/opt/xform/coster.go#L520)):*
> ```Go
> 				// some float functions, so this is a somewhat
> 				// data-backed guess.
> 				const geoFnCost = cpuCostFactor * 10
> ```

[nit] move the 10 as a constant at the top of the file, we try to put them all there

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7JIzX245iLW9it5CTN:-M7JJwXY35g2JBSCYlXn:b9sbgn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b00bd5b680c699680937aabc421e651baf0f0ee/pkg/sql/opt/xform/coster.go#L318)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this also call computeFiltersCost? Maybe we should move this `cpuCostFactor * rowCount` cost inside that function.
</blockquote></details>

just added a second commit for this

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7JJO_k3YjiA1ryeidG:-M7JNDnI-wg7oAh5h805:b-9xqt9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b00bd5b680c699680937aabc421e651baf0f0ee/pkg/sql/opt/xform/coster.go#L471)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this should be `rowsProcessed` not `lookupCount`
</blockquote></details>

Ok. I assume this should be changed for computeHashJoinCost too, which is using leftRowCount+rightRowCount, instead of rowsProcessed? Help me understand the intuition here. I did it like this because I thought the function would have to be executed on each incoming row from either side? But I guess that doesn't make much sense because the geo functions have two arguments, so probably one from each side. row count vs rows processed apparently is still unclear to me.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7JI2uz1DhvWYEqS_LI:-M7Jg7Ni9oT_dLsqwd2R:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b00bd5b680c699680937aabc421e651baf0f0ee/pkg/sql/opt/xform/coster.go#L520)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] move the 10 as a constant at the top of the file, we try to put them all there
</blockquote></details>

done

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7JJO_k3YjiA1ryeidG:-M7Jk95c2cfp5YgumziI:bkz149w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b00bd5b680c699680937aabc421e651baf0f0ee/pkg/sql/opt/xform/coster.go#L471)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Ok. I assume this should be changed for computeHashJoinCost too, which is using leftRowCount+rightRowCount, instead of rowsProcessed? Help me understand the intuition here. I did it like this because I thought the function would have to be executed on each incoming row from either side? But I guess that doesn't make much sense because the geo functions have two arguments, so probably one from each side. row count vs rows processed apparently is still unclear to me.
</blockquote></details>

Yeah, rowsProcessed estimates exactly what we need - how many rows we evaluate the ON condition on (a row here being a concatenation of a left row and a right row). The output row count is the same with the number of rows that pass the ON condition (for inner join).

In the worst case (a cross join), we may need to evaluate the ON condition on `leftRowCount * rightRowCount` rows.

An example where this really matters: imagine we have a join on `a=x AND b=y` and we have a hash join that hashes both columns and a lookup join but on an index only on `a`. The second one would generate a lot of rows that match on `a`, on which we'd have to check `b=y`. In this example, rowsProcessed would be equal to the row count for the hash case, but it would be much higher for the lookup case.
___
*[pkg/sql/opt/xform/coster.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7Jld5N5lvgL1gOeXbH:-M7Jld5N5lvgL1gOeXbI:b-nndjnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9386fa3f273fd19c1ee2dde82cab8bd5d22849/pkg/sql/opt/xform/coster.go#L323)):*
> ```Go
> 	// The filter has to be evaluated on each input row.
> 	inputRowCount := sel.Input.Relational().Stats.RowCount
> 	cost := memo.Cost(inputRowCount) * cpuCostFactor
> ```

I think we can remove this now, since `computeFiltersCost` already adds a cpuCostFactor for each one (and also for consistency with the joins where we rely only on `computeFiltersCost`).

**Comment by mjibson** [comment]
Added a new commit that adds limit hints and rows processed.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7Jld5N5lvgL1gOeXbH:-M7Jm7wnCB7du85Cl5uf:bzcxopi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9386fa3f273fd19c1ee2dde82cab8bd5d22849/pkg/sql/opt/xform/coster.go#L323)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we can remove this now, since `computeFiltersCost` already adds a cpuCostFactor for each one (and also for consistency with the joins where we rely only on `computeFiltersCost`).
</blockquote></details>

computeFiltersCost currently only adds per row costs for expensive geo functions. It only adds a single cpuCostFactor per filter condition, not per row. I think this needs to stay for now.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-:-M7L6icVB5l6JJb4uZhv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7L5MZJ9stMMOOSs73K:-M7L5MZKCNfvdB242UCP:b-xg0du) ([raw file](https://github.com/cockroachdb/cockroach/blob/311c5a9206e389e3a815423fa9b22bc6a0352956/pkg/sql/opt/xform/coster.go#L137)):*
> ```Go
> 	hugeCost memo.Cost = 1e100
> 
> 	// Some benchmarks showed that these geo functions were atleast 10
> ```

[nit] remove "these" (or replace with "some")
[nit] at least
___
*[pkg/sql/opt/xform/coster.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7Jld5N5lvgL1gOeXbH:-M7L5geaAlQlW0DlHsgt:b-kufkxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9386fa3f273fd19c1ee2dde82cab8bd5d22849/pkg/sql/opt/xform/coster.go#L323)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

computeFiltersCost currently only adds per row costs for expensive geo functions. It only adds a single cpuCostFactor per filter condition, not per row. I think this needs to stay for now.
</blockquote></details>

I see, thanks!
___
*[pkg/sql/opt/xform/coster.go, line 508 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7L6amX3PsjZ5hTLBQ5:-M7L6amX3PsjZ5hTLBQ6:b9x90ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L508)):*
> ```Go
> 	if required.LimitHint != 0 && lookupCount > 0 {
> 		outputRows := join.Relational().Stats.RowCount
> 		unlimitedLookupCount := lookupCount
> ```

Ha, you used the updated logic even before I merged my PR, nice!

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 541 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7LQrMU9Foe1bms703o:-M7LQrMU9Foe1bms703p:bbx5u3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L541)):*
> ```Go
> 
> func (c *coster) computeFiltersCost(
> 	filters memo.FiltersExpr, eqMap util.FastIntMap, rowCount float64,
> ```

Can we just add the filters cost into the `perRowCost` instead? I think it's awkward and surprising to have some of the filter operators take into account `rowCount` and some not. I bet making the existing `EqOp` cost be per-row instead of a one-time cost wouldn't change any plans, but would allow this API to be cleaner.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 19 of 19 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mjibson)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2360 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7bnSGV4HVWhcCMe06Q:-M7bnSGV4HVWhcCMe06R:bc1z1mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/memo/statistics_builder.go#L2360)):*
> ```Go
> 		withoutOn := e.Memo().MemoizeLookupJoin(t.Input, nil /* on */, lookupJoinPrivate)
> 		return withoutOn.Relational().Stats.RowCount
> 	case *GeoLookupJoinExpr:
> ```

[nit] add a line above this case to be consistent with the formatting in the rest of this switch
___
*[pkg/sql/opt/xform/coster.go, line 494 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7boN3vDZ8ALMYhgT9Y:-M7boN3vDZ8ALMYhgT9Z:b-28jpln) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L494)):*
> ```Go
> 	//   ab JOIN xy ON a=x AND a=10 AND x=10
> 	// which can become a lookup join with left-over condition x=10 which doesn't
> 	// actually filter anything.
> ```

Is there a way to make this comment more specific to geo lookup join? Maybe you could simplify the test case with NYC neighborhoods?
___
*[pkg/sql/opt/xform/coster.go, line 500 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7boHAm-nFbc2inAaZr:-M7boHAm-nFbc2inAaZs:b-w6xm2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L500)):*
> ```Go
> 		// to be optimized twice, the coster should never be used after
> 		// logPropsBuilder.clear() is called.
> 		panic(errors.AssertionFailedf("could not get rows processed for lookup join"))
> ```

[nit] geo lookup join
___
*[pkg/sql/opt/xform/coster.go, line 541 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7LQrMU9Foe1bms703o:-M7bq-QaCzy2WIfZFsNl:bpf34fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L541)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can we just add the filters cost into the `perRowCost` instead? I think it's awkward and surprising to have some of the filter operators take into account `rowCount` and some not. I bet making the existing `EqOp` cost be per-row instead of a one-time cost wouldn't change any plans, but would allow this API to be cleaner.
</blockquote></details>

The problem is when the estimated row count is very tiny, we need a way to prefer certain plans over others, which is why we have the "setup cost". 

But I agree it's kind of awkward that this function now takes a row count, but it's only applied for the case of geo functions.  I think it would be good to keep this function independent of the row count, but maybe always multiply the result by `rowCount+1` instead of just `rowCount`. Does that change any plans?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2360 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7bnSGV4HVWhcCMe06Q:-M7d1dLGEJ65qnVkGvFX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/memo/statistics_builder.go#L2360)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] add a line above this case to be consistent with the formatting in the rest of this switch
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 494 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7boN3vDZ8ALMYhgT9Y:-M7dh09LD0ZsMgCSv3zx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L494)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is there a way to make this comment more specific to geo lookup join? Maybe you could simplify the test case with NYC neighborhoods?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 500 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7boHAm-nFbc2inAaZr:-M7cowE84-UDunK29Jg0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L500)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] geo lookup join
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 541 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7LQrMU9Foe1bms703o:-M7d1-dg1dJtjWag4Cw9:b-ffua12) ([raw file](https://github.com/cockroachdb/cockroach/blob/47e5d74bbaec73497bac31f83e9e1e969e5ce711/pkg/sql/opt/xform/coster.go#L541)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The problem is when the estimated row count is very tiny, we need a way to prefer certain plans over others, which is why we have the "setup cost". 

But I agree it's kind of awkward that this function now takes a row count, but it's only applied for the case of geo functions.  I think it would be good to keep this function independent of the row count, but maybe always multiply the result by `rowCount+1` instead of just `rowCount`. Does that change any plans?
</blockquote></details>

I've removed the row count argument and changed all callers of computeFiltersCost to multiply its output by their row count. This does indeed increase many costs (as we would expect since now we are assuming the base cost applies to all rows instead of just a one time setup), but didn't result in any changed plans in the tests.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 23 files at r6, 18 of 20 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49074)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @mjibson)

___
*[pkg/sql/opt/xform/coster.go, line 323 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7doPma3LMNM0H7goob:-M7doPmbBCHA4uipxH6B:b6xhd03) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/coster.go#L323)):*
> ```Go
> 	// The filter has to be evaluated on each input row.
> 	inputRowCount := sel.Input.Relational().Stats.RowCount
> 	cost := memo.Cost(inputRowCount) * cpuCostFactor
> ```

You can probably get rid of this cost now, since it's subsumed by computeFiltersCost
___
*[pkg/sql/opt/xform/coster.go, line 369 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7docY19RNJr-QS6T_v:-M7docY19RNJr-QS6T_w:b1xu5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/coster.go#L369)):*
> ```Go
> 		rowsProcessed = join.Relational().Stats.RowCount
> 	}
> 	cost += memo.Cost(rowsProcessed) * cpuCostFactor
> ```

can get rid of this
___
*[pkg/sql/opt/xform/coster.go, line 389 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7dsW3dDpWe_iiNAfbN:-M7dsW3dDpWe_iiNAfbO:bn5rlq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/coster.go#L389)):*
> ```Go
> 		eqMap.Set(right, left)
> 	}
> 	cost += c.computeFiltersCost(*on, eqMap) * memo.Cost(rowsProcessed)
> ```

for all of these joins, I think you want to multiply by `1+rowsProcessed` to account for the "setup cost" we had before
___
*[pkg/sql/opt/xform/coster.go, line 408 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7doigc8PENTTdHu8sb:-M7doigc8PENTTdHu8sc:b1xu5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/coster.go#L408)):*
> ```Go
> 		panic(errors.AssertionFailedf("could not get rows processed for merge join"))
> 	}
> 	cost += memo.Cost(rowsProcessed) * cpuCostFactor
> ```

can get rid of this
___
*[pkg/sql/opt/xform/coster.go, line 481 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7dolCp9VjxfIE_SeYm:-M7dolCp9VjxfIE_SeYn:b37s1hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/coster.go#L481)):*
> ```Go
> 		c.rowScanCost(join.Table, join.Index, numLookupCols)
> 
> 	cost += memo.Cost(rowsProcessed) * perRowCost
> ```

can get rid of this, if you add the result of `computeFiltersCost` to the `perRowCost`
___
*[pkg/sql/opt/xform/coster.go, line 496 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7doqTg2RWkqll-9hqu:-M7doqTg2RWkqll-9hqv:b3x14a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/coster.go#L496)):*
> ```Go
> 	// left-over conditions that are not selective.
> 	// A contrived example, where gid is a SERIAL PK:
> 	//   nyc_census_blocks c JOIN nyc_neighborhoods n ON ST_Intersects(c.geom, n.geom) AND c.gid = 10
> ```

[nit] wrap to 80 chars
___
*[pkg/sql/opt/xform/coster.go, line 498 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7dp-dh7G3oP4CHTM4z:-M7dp-diCP2e7srKTi64:b-3f6l7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/coster.go#L498)):*
> ```Go
> 	//   nyc_census_blocks c JOIN nyc_neighborhoods n ON ST_Intersects(c.geom, n.geom) AND c.gid = 10
> 	// which can become a lookup join with left-over condition c.gid = 10 which doesn't
> 	// actually filter anything.
> ```

The statement "which doesn't actually filter anything" isn't correct for this example (`c.gid = 10` does in fact filter the output). But the example is still valid since we would need to evaluate the filter condition on every row processed by the `GeoLookupJoin`, and we need to account for this in the cost. 

On a somewhat unrelated note, `c.gid = 10` is such a selective filter that we'd probably never choose a `GeoLookupJoin` over a constrained primary index scan in this case. I'd suggest changing the filter in the example to something like `c.gid < n.gid` (still totally contrived, but at least more likely to result in a `GeoLookupJoin` with an `ON` condition).
___
*[pkg/sql/opt/xform/testdata/coster/join, line 539 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49074#-M7dsCaa1jTFUeaEhSq-:-M7dsCaa1jTFUeaEhSq0:b8m9y9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2b14c988be36958cc9dc5f92036bef9f3733bf/pkg/sql/opt/xform/testdata/coster/join#L539)):*
> ```
>  └── inner-join (lookup abcde@idx_abd)
>       ├── columns: w:1!null x:2!null y:3!null z:4!null i:5!null j:6!null k:7!null l:8!null m:9!null n:10!null a:12!null b:13!null c:14!null
>       ├── key columns: [1 2] = [12 13]
> ```

we lost one of the equality columns here -- I think this is the reason we needed the setup cost

**Comment by mjibson** [comment]
Closing due to too many unrelated changes happening at once. Getting all the geo stuff in and will do the other joins and select in another PR.

**Pull request closed without merging**
