### PR TITLE
vendor: add cloud storage libs

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11791)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[glide.yaml, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0ddXOx_EhDv8PwRrq:-KY0ddXOx_EhDv8PwRrr:b-i05jqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L166)):*
> ```YAML
> - package: github.com/pborman/uuid
> - package: github.com/agtorre/gocolorize
> - package: github.com/rlmcpherson/s3gof3r
> ```

since these are now imported by cockroach, is it necessary to include them here?

---

*[glide.yaml, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dpVeQvv4PrMmRHnd:-KY0dpVeQvv4PrMmRHne:bq6e05r) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L168)):*
> ```YAML
> - package: github.com/rlmcpherson/s3gof3r
> - package: google.golang.org/api
>   version: 3ef9447cad8d725923ca024dab57786299cf745a
> ```

why this pin?

---

*[pkg/sql/backup_stub.go, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dsgM3HcZnypIkMPg:-KY0dsgM3HcZnypIkMPh:baul6z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/pkg/sql/backup_stub.go#L26)):*
> ```Go
> // code that uses new external libraries. Unfortunately, since we're using a
> // submodule for `vendor`, we can't simply rebase the addition of those deps,
> // and rather than handle frequent and expensive to resolve conflicts over the
> ```

frequent and expensive what?

---

*[pkg/sql/backup_stub.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dvfh33_-UQiZzZ9M:-KY0dvfh33_-UQiZzZ9N:b-k98jzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/pkg/sql/backup_stub.go#L27)):*
> ```Go
> // submodule for `vendor`, we can't simply rebase the addition of those deps,
> // and rather than handle frequent and expensive to resolve conflicts over the
> // submodule ref, we're adding the new tdeps to master's vendor now, even while
> ```

tdeps?

---

*[pkg/sql/backup_stub.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dy1RQXmWbubg2UQZ:-KY0dy1RQXmWbubg2UQ_:bf66i95) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/pkg/sql/backup_stub.go#L28)):*
> ```Go
> // and rather than handle frequent and expensive to resolve conflicts over the
> // submodule ref, we're adding the new tdeps to master's vendor now, even while
> // their usage is still on the branch. These dummy imports to ensure they are
> ```

these dummy imports what?

please give this whole paragraph an additional once-over.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791)*

**Comment by dt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[glide.yaml, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0ddXOx_EhDv8PwRrq:-KY0fu7PcWFzbzFkzZXH:b-i5vf47) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L166)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

since these are now imported by cockroach, is it necessary to include them here?
</blockquote></details>

:eyeroll

---

*[glide.yaml, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dpVeQvv4PrMmRHnd:-KY0fwXHYzhvey5p85vW:bu2z0el) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L168)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why this pin?
</blockquote></details>

i'll give you one guess... nvm, docker of course.

---

*[pkg/sql/backup_stub.go, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dsgM3HcZnypIkMPg:-KY0g6gCcHjPhq9XxB64:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/pkg/sql/backup_stub.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

frequent and expensive what?
</blockquote></details>

Done.

---

*[pkg/sql/backup_stub.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dvfh33_-UQiZzZ9M:-KY0g7F9pCAM-qMJJ665:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/pkg/sql/backup_stub.go#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

tdeps?
</blockquote></details>

Done.

---

*[pkg/sql/backup_stub.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dy1RQXmWbubg2UQZ:-KY0g7jbZDqkiG5iLIZg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/pkg/sql/backup_stub.go#L28)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

these dummy imports what?

please give this whole paragraph an additional once-over.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[glide.yaml, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0ddXOx_EhDv8PwRrq:-KY0jJOET0htVhb-Z9lG:b-hw71zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L166)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

:eyeroll
</blockquote></details>

I don't get it - why include them if it's not necessary? This increases the cognitive overhead of looking at this file, which is already insanely high.

---

*[glide.yaml, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dpVeQvv4PrMmRHnd:-KY0jBn1TAj2kdk3Hf7C:bnygmzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L168)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

i'll give you one guess... nvm, docker of course.
</blockquote></details>

Hm? I don't get it. Can you call it out in the commit message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791)*

**Comment by paperstreet** [comment]
LGTM

science dog-ing the glide stuff but I assume you know what you're doing

**Comment by dt** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[glide.yaml, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0ddXOx_EhDv8PwRrq:-KY0lApbBSjGlcSfpY6u:b-vo6twh) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L166)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't get it - why include them if it's not necessary? This increases the cognitive overhead of looking at this file, which is already insanely high.
</blockquote></details>

how is this dep different than the other 103 deps in here?

---

*[glide.yaml, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0dpVeQvv4PrMmRHnd:-KY0ldVQ71Re930aQ6Lf:b-6abbfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L168)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Hm? I don't get it. Can you call it out in the commit message?
</blockquote></details>

docker pulls in cloud.google and google.golang (along with 50 other things), so unless we pin it, we get docker's version, which doesn't work for us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[glide.yaml, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0ddXOx_EhDv8PwRrq:-KY0oQeFN3qUsBy5QjhZ:b-xwmhi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L166)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

how is this dep different than the other 103 deps in here?
</blockquote></details>

Well, it isn't, and I'd like to prune the others, but you're just making more work for me by adding this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[glide.yaml, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791#-KY0ddXOx_EhDv8PwRrq:-KY0onS82WHSp_5DuvEI:b50d316) ([raw file](https://github.com/cockroachdb/cockroach/blob/de7eca2380dd7ff96529d54ff6b24a9caf052641/glide.yaml#L166)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Well, it isn't, and I'd like to prune the others, but you're just making more work for me by adding this.
</blockquote></details>

eh,  I value staying consistent with the current state -- all direct and manually deps are enumerated in glide.yaml -- and the marginal cost of this one line to any future change of the other 100+ is negligible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11791)*

**Comment by tamird** [comment]
OK, fine.

**Pull request merged**
