### PR TITLE
server: add API endpoint for scheduled jobs

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds an endpoint for scheduled jobs
to the admin server. The endpoint can be used to
fetch details about schedules in the cluster.

The new endpoint `/_admin/v1/schedules` supports three
parameters:

`limit`: to limit the number of schedules in the response

`type`: to specify the type of schedules in the response
- scheduled-backup-executor
- scheduled-sql-stats-compaction-executor

`status`: to specify the status of schdules in the response
- running
- paused

This is a building block to supporting a schedules page on
the debug console.

Release note (api change): Adds an endpoint `/_admin/v1/schedules`
to get information about schedules in the cluster.

### CODE REVIEW

**Comment by adityamaru** [comment]
@miretskiy I'm open to suggestions on what we should expose via this endpoint. I'm thinking that when you click into a schedule we should show the full create schedule statement via `SHOW CREATE SCHEDULE`? I haven't added that yet to the endpoint.

**Review by miretskiy — COMMENTED** [review]
Not sure; I mean, show schedule itself produces useful information -- like status.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70680#-:-MkNCSb31RJSH2QBY-t2:b27jhaz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

**Comment by adityamaru** [comment]
Yeah, I think for the main page where we show all schedules `SHOW SCHEDULES` is fine. When we click in, in the black box I guess we should show the statement like jobs does 🤷 

Screen Shot 2021-09-24 at 10 33 19 AM

**Comment by adityamaru** [comment]
@dhartunian adding you as a reviewer as part of the http-api-prs, please let me know if there is someone else I should go to instead!

**Review by dhartunian — COMMENTED** [review]
@adityamaru is the implementation here speculative w/r/t what the UI will look like or is there a mock or API that this is built against?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70680#-:-MlRwjulEYHgWY2fIbZ0:bz3sttg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

**Pull request closed without merging**
