### PR TITLE
kvserver: QueryResolvedTimestamp should look for intents in LockTable

### LINKED ISSUE #69717: kv: only scan separated intents span for QueryResolvedTimestamp requests
Related to #67562 and #67554.
This optimization was originally outlined in the [bounded staleness RFC](https://github.com/cockroachdb/cockroach/blob/ffbbf819d415aa6f654050cebd6db11c48e23ac6/docs/RFCS/20210519_bounded_staleness_reads.md#queryresolvedtimestamp-efficiency).

Today, a `QueryResolvedTimestamp` request performs a scan over the MVCC keyspace to retrieve the intents in its target key span.

https://github.com/cockroachdb/cockroach/blob/ffbbf819d415aa6f654050cebd6db11c48e23ac6/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L92-L105

With intents now separated out into a separate keyspace, we should be able to perform a more efficient scan over the lock table keyspace to retrieve the active intents on the `QueryResolvedTimestamp`'s target key span. This avoids the need to merge the lock table iterator with an MVCC iterator. As a result, we turn an O(num_keys_in_span) operation into an O(num_locks_in_span) operation.

This is a reasonably hard blocker for stage 2 of bounded staleness reads.

### PR DESCRIPTION
**Pull request by shralex**
Previously, a request called “QueryResolvedTimestamp” that is used to determine the “resolved timestamp” of a key range on a given replica cost O(num_keys_in_span), because it needed to find all intents in the span and intents were interleaved with key-value versions. A multi-release project to separate out intents from MVCC data is now far enough along that we can make this request more efficient by scanning only the lock-table keyspace, reducing its cost to O(num_locks_in_span).

Release note: None

Release justification: This is going into 22.1 where the migration to separated intents is complete

Fixes: #69717

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @shralex)

___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mkm9LN3BsKoE_VrjbO3:-Mkm9LN3BsKoE_VrjbO4:bg3fbl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L57)):*
> ```Go
> 	// because QueryResolvedTimestamp requests are often run without acquiring
> 	// latches (see roachpb.INCONSISTENT) and often also on follower replicas,
> 	// so latches won't help them to synchronize with writes.
> ```

unrelated to this PR, I'm worried by this comment @nvanbenschoten 
- We have discussed that we would like a `Reader` that returns true for `ConsistentIterators` to contain a version of the engine from when the `Reader` was created. I think that would not be acceptable in this latchless situation where we want to see the engine state after the closed timestamp has been retrieved. Is my understanding correct?
- Even with the current lazy creation of the first cloneable iterator, we could have multiple requests in a batch, and a request in the batch that preceded this `QueryResolvedTimestampRequest` could have created that iterator that we will subsequently clone. So the iterator we create in `createMinIntentTimestamp` could reflect the engine state prior to this closed timestamp. Is there something preventing this?
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmBI7T1bjScHBe1Df8:-MkmBI7T1bjScHBe1Df9:bws46dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L111)):*
> ```Go
> 	// version for each key. We're only looking for MVCCMetadata versions, which
> 	// will always be the first version of a key if it exists, so its fine that
> 	// we skip over all other versions of keys.
> ```

This comment is stale.
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmC9xZAu7T4R0z_jcC:-MkmC9xZAu7T4R0z_jcD:bibrjyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L136)):*
> ```Go
> 
> 		// If this is an intent, account for it.
> 		if meta.Txn != nil {
> ```

the case of `meta.Txn == nil` should now be an error.
We have two uses of `MVCCMetadata` that used to both be written to timestamp 0:
- interleaved intents, which are now moved to the lock table. They always have a non-nil txn.
- inline meta, for storing timeseries (these are not MVCC). These are still at timestamp 0 (not in the lock table), and have a nil txn.
___
*[pkg/storage/in_mem.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmDy8kCJ5c5IzpRkU0:-MkmDy8kCJ5c5IzpRkU1:b54hwcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L47)):*
> ```Go
> // NewDefaultInMemForTesting allocates and returns a new, opened in-memory engine with
> // the default configuration. The caller must call the engine's Close method
> // when the engine is no longer needed.
> ```

Can you add to the comment here that this randomizes whether separated intents are written.
___
*[pkg/storage/in_mem.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmE3WN1ZbqdUHEX4TV:-MkmE3WN1ZbqdUHEX4TW:bye675y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L58)):*
> ```Go
> // NewDefaultInMemForStickyEngineTesting is just like NewDefaultInMemForTesting but uses
> // ForStickyEngineTesting to always separate intents from MVCC data, instead of randomizing this setting.
> func NewDefaultInMemForStickyEngineTesting(opts ...ConfigOption) Engine {
> ```

Let's call this something like `NewInMemForTesting(enableSeparatedIntents bool, opts ...ConfigOption)` and not use the term sticky-engine here since this is not specifically to do with sticky engines, and neither is the test that calls it.
In hindsight, I should not have introduced `ForStickyEngineTesting` given that we already have `func SetSeparatedIntents(disable bool) ConfigOption`. So the implementation here should avoid using `ForStickyEngineTesting`.

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mkm9LN3BsKoE_VrjbO3:-MkmQjL64jPQdvTpcWJi:b-t53lto) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

unrelated to this PR, I'm worried by this comment @nvanbenschoten 
- We have discussed that we would like a `Reader` that returns true for `ConsistentIterators` to contain a version of the engine from when the `Reader` was created. I think that would not be acceptable in this latchless situation where we want to see the engine state after the closed timestamp has been retrieved. Is my understanding correct?
- Even with the current lazy creation of the first cloneable iterator, we could have multiple requests in a batch, and a request in the batch that preceded this `QueryResolvedTimestampRequest` could have created that iterator that we will subsequently clone. So the iterator we create in `createMinIntentTimestamp` could reflect the engine state prior to this closed timestamp. Is there something preventing this?

</blockquote></details>

I'll wait for @nvanbenschoten 's input for this.
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmBI7T1bjScHBe1Df8:-MkmNX-I7BFk2jXQ8LjN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L111)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This comment is stale.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmC9xZAu7T4R0z_jcC:-MkmNUo74QIHsD8JB1wx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L136)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the case of `meta.Txn == nil` should now be an error.
We have two uses of `MVCCMetadata` that used to both be written to timestamp 0:
- interleaved intents, which are now moved to the lock table. They always have a non-nil txn.
- inline meta, for storing timeseries (these are not MVCC). These are still at timestamp 0 (not in the lock table), and have a nil txn.

</blockquote></details>

Done.
___
*[pkg/storage/in_mem.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmDy8kCJ5c5IzpRkU0:-MkmNk4NCCtSopTl7vkh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L47)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add to the comment here that this randomizes whether separated intents are written.
</blockquote></details>

Done.
___
*[pkg/storage/in_mem.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmE3WN1ZbqdUHEX4TV:-MkmQfQf9XuPytIu55oa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L58)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Let's call this something like `NewInMemForTesting(enableSeparatedIntents bool, opts ...ConfigOption)` and not use the term sticky-engine here since this is not specifically to do with sticky engines, and neither is the test that calls it.
In hindsight, I should not have introduced `ForStickyEngineTesting` given that we already have `func SetSeparatedIntents(disable bool) ConfigOption`. So the implementation here should avoid using `ForStickyEngineTesting`.
</blockquote></details>

Done.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
looks good. Couple of minor things.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-:-MkmoAgx-4gUh-3_OF3r:b-unhyob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @shralex, and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmnAAEBw5St8iKJvdM:-MkmnAAEBw5St8iKJvdN:bb3lk4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/88322e4297e4b9b93c67c470f1e10988754ea850/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go#L50)):*
> ```Go
> 	}
> 
> 	// Setup:
> ```

can you add a comment here that with separated intents the actual key layout in the store is not what is listed below.

And if you are feeling up to it, you could add a test which manually writes a `MVCCMetadata` that is missing the Txn field to a lock table key, to test the error path you added. The key can be constructed by first constructing a `LockTableKey` then calling `ToEngineKey` and then putting by doing `db.PutEngineKey`.
___
*[pkg/storage/in_mem.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmmKf71X41NNZrcS8T:-MkmmKf71X41NNZrcS8U:bke26ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/88322e4297e4b9b93c67c470f1e10988754ea850/pkg/storage/in_mem.go#L57)):*
> ```Go
> 
> // NewInMemForTesting is just like NewDefaultInMemForTesting but allows to deterministically define whether it
> // separates intents from MVCC data.
> ```

We wrap comments to 80 columns and code to 100 columns, iirc. This comment line looks longer than that.
In case you are using goland, there is a goland plugin to do the comment wrapping, mentioned in our internal wiki here https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks#GolandTipsandTricks-SettingupWrapToColumn

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmnAAEBw5St8iKJvdM:-MkruioV4BREO7VpsElx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88322e4297e4b9b93c67c470f1e10988754ea850/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment here that with separated intents the actual key layout in the store is not what is listed below.

And if you are feeling up to it, you could add a test which manually writes a `MVCCMetadata` that is missing the Txn field to a lock table key, to test the error path you added. The key can be constructed by first constructing a `LockTableKey` then calling `ToEngineKey` and then putting by doing `db.PutEngineKey`.
</blockquote></details>

Done.
___
*[pkg/storage/in_mem.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmmKf71X41NNZrcS8T:-MkrufsO3M6Wv-0dKg-M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88322e4297e4b9b93c67c470f1e10988754ea850/pkg/storage/in_mem.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We wrap comments to 80 columns and code to 100 columns, iirc. This comment line looks longer than that.
In case you are using goland, there is a goland plugin to do the comment wrapping, mentioned in our internal wiki here https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks#GolandTipsandTricks-SettingupWrapToColumn

</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-:-MksLlej00BqaeRI8vPv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

**Review by nvb — COMMENTED** [review]
Nice job on this.

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-:-Mku64Wx7BuGmutuCWzK:br5d1kg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @shralex and @sumeerbhola)

___
*[-- commits, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MktoWpV2phVFJQrP_Xc):*
Before merging this PR, we'll want to squash these three commits down into one. See https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews.
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mkm9LN3BsKoE_VrjbO3:-MktyABdBxEVtdZl26Hc:bgvnn2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L57)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

I'll wait for @nvanbenschoten 's input for this.
</blockquote></details>

This is a very good catch. You are correct that this is improperly relying on the Reader's LSM snapshot being lazily captured at the time of the iterator creation. This will be completely broken when we [begin capturing Reader snapshots eagerly](https://github.com/cockroachdb/cockroach/issues/55461) and is broken today in cases where we have multiple `QueryResolvedTimestampRequest`s in the same batch.

What's even more interesting is that this isn't actually causing issues today, for a very subtle reason. We do issue multiple `QueryResolvedTimestampRequest` in the same batch to the same range [here](https://github.com/cockroachdb/cockroach/blob/5f53feb1ce7070453e9ce52d99013934718cc9d7/pkg/kv/kvserver/store_send.go#L411), so we should hit the second problem. This means that for all but the first request in the batch, we could observe a closed timestamp that was carried in a later log entry than the last entry applied to the observed version of the state machine in `computeMinIntentTimestamp`. However, because of the way that these `QueryResolvedTimestamp` responses are combined, we happen to avoid any problems. Each response carries `min(closed_ts, min_intent_ts)`, and we combine the responses by taking the min of all responses (`min(min(closed_ts_1, min_intent_ts_1), min(closed_ts_2, min_intent_ts_2), ...)`). So because the closed timestamp increases monotonically, we effectively ignore all closed timestamps except the first one and we end up with the correct resolved timestamp.

But regardless, we should fix this. My thinking about how to do that in a way that composes with https://github.com/cockroachdb/cockroach/issues/55461 is a little hazy. We've discussed the need to snapshot additional replica state for read-only operations that may evaluate after dropping latches. We could capture the pre-snapshot closed timestamp in this bundle to ensure that it is properly sequenced with the engine snapshot. But the closed timestamp isn't negligibly cheap to grab, so we probably wouldn't want to grab it if none of the requests needed it.

Since this isn't causing issues, I'm tempted to say that we should try to solve this as part of https://github.com/cockroachdb/cockroach/issues/55461, but if you have thoughts, I'd be happy to dive deeper into this now. I opened https://github.com/cockroachdb/cockroach/issues/70974 to continue the discussion.
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mktqlxe7kZbLY9M5-ms:-Mktqlxe7kZbLY9M5-mt:b-miv19q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81a6fdc3d679a2b6b56311baa73933f0ec38e7/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L124)):*
> ```Go
> 		lockedKey, err := keys.DecodeLockTableSingleKey(engineKey.Key)
> 		if err != nil {
> 			continue
> ```

@sumeerbhola can you think of any valid reasons to hit this branch? Should we be wrapping and returning this error instead?
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 131 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MktqDUID5uZxiYTaas5:-MktqDUID5uZxiYTaas6:bh0kjv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81a6fdc3d679a2b6b56311baa73933f0ec38e7/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L131)):*
> ```Go
> 		}
> 		if meta.Txn == nil {
> 			return hlc.Timestamp{}, nil, errors.Errorf("nil transaction in LockTable. Key: %v, mvcc meta: %v",
> ```

`s/Errorf/AssertionFailedf/`
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go, line 216 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MktrJBP6eROHZynWVB0:-MktrJBP6eROHZynWVB1:b2dn1qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81a6fdc3d679a2b6b56311baa73933f0ec38e7/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go#L216)):*
> ```Go
> }
> 
> func TestSeparatedIntentErrors(t *testing.T) {
> ```

nit: rename this to `TestQueryResolvedTimestampErrors` or something like that. This test is part of the `pkg/kv/kvserver/batcheval` package, so it should be sufficiently qualified.
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go, line 257 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mktrl-JBUeH9j73BuYE:-Mktrl-JBUeH9j73BuYF:b-p4qydv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81a6fdc3d679a2b6b56311baa73933f0ec38e7/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go#L257)):*
> ```Go
> 		_, err := QueryResolvedTimestamp(ctx, db, cArgs, &resp)
> 		require.Error(t, err)
> 		require.Regexp(t, regexp.MustCompile(`unmarshaling mvcc meta`), err.Error())
> ```

I don't think you need the `QueryResolvedTimestamp`. You should be able to pass a string directly.
___
*[pkg/storage/in_mem.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmDy8kCJ5c5IzpRkU0:-MktsO557-p6MWpD5Q_c:b-9p3h2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L47)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Wrap to 80 cols here as well.
___
*[pkg/storage/in_mem.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmE3WN1ZbqdUHEX4TV:-MktsL_I9t6Mhip2UEL6:b2q6ckf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L58)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do we need this function? Couldn't a caller that wants a deterministically defined value for `DisableSeparatedIntents` pass an `SetSeparatedIntents` option to `NewDefaultInMemForTesting`, which will overwrite whatever value is set by `ForTesting`?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @shralex, and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mkm9LN3BsKoE_VrjbO3:-MkwUaeP1Mj-33JyNIRk:b-13iuko) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is a very good catch. You are correct that this is improperly relying on the Reader's LSM snapshot being lazily captured at the time of the iterator creation. This will be completely broken when we [begin capturing Reader snapshots eagerly](https://github.com/cockroachdb/cockroach/issues/55461) and is broken today in cases where we have multiple `QueryResolvedTimestampRequest`s in the same batch.

What's even more interesting is that this isn't actually causing issues today, for a very subtle reason. We do issue multiple `QueryResolvedTimestampRequest` in the same batch to the same range [here](https://github.com/cockroachdb/cockroach/blob/5f53feb1ce7070453e9ce52d99013934718cc9d7/pkg/kv/kvserver/store_send.go#L411), so we should hit the second problem. This means that for all but the first request in the batch, we could observe a closed timestamp that was carried in a later log entry than the last entry applied to the observed version of the state machine in `computeMinIntentTimestamp`. However, because of the way that these `QueryResolvedTimestamp` responses are combined, we happen to avoid any problems. Each response carries `min(closed_ts, min_intent_ts)`, and we combine the responses by taking the min of all responses (`min(min(closed_ts_1, min_intent_ts_1), min(closed_ts_2, min_intent_ts_2), ...)`). So because the closed timestamp increases monotonically, we effectively ignore all closed timestamps except the first one and we end up with the correct resolved timestamp.

But regardless, we should fix this. My thinking about how to do that in a way that composes with https://github.com/cockroachdb/cockroach/issues/55461 is a little hazy. We've discussed the need to snapshot additional replica state for read-only operations that may evaluate after dropping latches. We could capture the pre-snapshot closed timestamp in this bundle to ensure that it is properly sequenced with the engine snapshot. But the closed timestamp isn't negligibly cheap to grab, so we probably wouldn't want to grab it if none of the requests needed it.

Since this isn't causing issues, I'm tempted to say that we should try to solve this as part of https://github.com/cockroachdb/cockroach/issues/55461, but if you have thoughts, I'd be happy to dive deeper into this now. I opened https://github.com/cockroachdb/cockroach/issues/70974 to continue the discussion.
</blockquote></details>

Deferring sounds fine.
Can we add a code comment here referring to that issue, since our current correctness is fragile.
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mktqlxe7kZbLY9M5-ms:-MkwUVbo4ujwpx4MCPXy:b-d0ykxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81a6fdc3d679a2b6b56311baa73933f0ec38e7/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@sumeerbhola can you think of any valid reasons to hit this branch? Should we be wrapping and returning this error instead?
</blockquote></details>

I missed this. There is no valid reason, and we should return the error.

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @shralex, and @sumeerbhola)

___
*[-- commits, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MktoWpV2phVFJQrP_Xc):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Before merging this PR, we'll want to squash these three commits down into one. See https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews.
</blockquote></details>

ack
___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go, line 257 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mktrl-JBUeH9j73BuYE:-MkwjQQSDSyN7kc-N3qP:bh1shdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81a6fdc3d679a2b6b56311baa73933f0ec38e7/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go#L257)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think you need the `QueryResolvedTimestamp`. You should be able to pass a string directly.
</blockquote></details>

I think you meant MustCompile ? fixed
___
*[pkg/storage/in_mem.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmDy8kCJ5c5IzpRkU0:-MkwiXS36X8EMPrNNZzo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Wrap to 80 cols here as well.
</blockquote></details>

Done.
___
*[pkg/storage/in_mem.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmE3WN1ZbqdUHEX4TV:-Mkwijb41HCuNOqI6xu5:bhy0gfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L58)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this function? Couldn't a caller that wants a deterministically defined value for `DisableSeparatedIntents` pass an `SetSeparatedIntents` option to `NewDefaultInMemForTesting`, which will overwrite whatever value is set by `ForTesting`?
</blockquote></details>

My understanding is that the randomization will go away, and this would be easier to use. Let me know if you feel strongly about it and I'll remove.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-:-Mkx12-37COFQCqDrjxb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-Mkm9LN3BsKoE_VrjbO3:-Mkx0CHT2TnDogCHvrxx:b-wdkysv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Deferring sounds fine.
Can we add a code comment here referring to that issue, since our current correctness is fragile.
</blockquote></details>

@shralex do you mind adding the following to this comment:
```go
//
// NOTE: This interaction is complicated by multi-request batches, where
// the iterator snapshot is captured during this evaluation of the first
// request, but this does not currently lead to incorrectness. See
// https://github.com/cockroachdb/cockroach/issues/70974.
```
___
*[pkg/storage/in_mem.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70852#-MkmE3WN1ZbqdUHEX4TV:-Mkx0xPg-cWOezrLiCQa:bd634ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc41d56d2b4dacf4691c024c2bb959a0471aa79/pkg/storage/in_mem.go#L58)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

My understanding is that the randomization will go away, and this would be easier to use. Let me know if you feel strongly about it and I'll remove.
</blockquote></details>

I don't feel strongly, so I'll defer to you and Sumeer.

**Comment by andreimatei** [comment]
This broke all the `QueryResolvedTimestamp` tests in `race` mode, with errors like `cannot read undeclared span /Local/Lock/Intent"b"`.
Eg. #71047 and linked tests.

I'm not sure about the details, but I think that the `QueryResulvedTimestamp` request needs to declare that it'll read some lock-table keys here:
https://github.com/cockroachdb/cockroach/blob/dc0efa872b5f184a1b43f517e3df05712a89d824/pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp.go#L39
I'm surprised that `DefaultDesclareKeys` doesn't declare anything about the lock table for all the other requests, but I don't know what I'm talking about.

**Pull request merged**
