### PR TITLE
logtestutils: generalize structured logging spy

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit generalizes the structured logging spy previously being used for datadriven telemetry tests so that it can repurposed for other structured logging channels.

Epic: none

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Nice job identifying a need here. I ended up needing something similar the other day in a PR, so I'm sure others will benefit from this work. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-:-NyMn3KT7JHDmrpK0qNN:b-b7kz49)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong, @nkodali, and @xinhaoz)

___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMjjohC4xrIWUr7T69:-NyMjjohC4xrIWUr7T6A:b-fw64ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L106)):*
> ```Go
> }
> 
> type StructuredLogSpy[T any] struct {
> ```

nit: docstring for the exported type explaining it's use/function.



_Code quote:_
```Go
type StructuredLogSpy[T any] struct {
```
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMiolOBBpUooNJwKE1:-NyMiolP1YoWS8YEuKMl:b-sdi6bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L110)):*
> ```Go
> 
> 	// map of channels to pointer
> 	channels map[logpb.Channel]interface{}
> ```

nit: can this just be `map[logpb.Channel]struct{}{}`? 



_Code quote:_
```Go
map[logpb.Channel]interface{}
```
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMjZvQ9J-WV5iG0nNi:-NyMjZvQ9J-WV5iG0nNj:blwnkay) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L133)):*
> ```Go
> 	format func(entry logpb.Entry) (T, error),
> 	filters ...func(entry logpb.Entry, formattedEntry T) bool,
> ) *StructuredLogSpy[T] {
> ```

nit: comments/docs explaining how things like `format`, `filters`, etc. work



_Code quote:_
```Go
func NewStructuredLogSpy[T any](
	testState *testing.T,
	channels []logpb.Channel,
	eventTypes []string,
	format func(entry logpb.Entry) (T, error),
	filters ...func(entry logpb.Entry, formattedEntry T) bool,
) *StructuredLogSpy[T] {
```
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMkUCm7qHSLUbw0n6l:-NyMkUCm7qHSLUbw0n6m:brvvhpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L164)):*
> ```Go
> 	defer s.mu.Unlock()
> 	s.mu.filters = nil
> }
> ```

Do we have examples of tests needing to modify filters post-construction? If a test needs different filters, should we just create a new `StructuredLogSpy`? 



_Code quote:_
```Go
func (s *StructuredLogSpy[T]) AddFilters(f ...func(entry logpb.Entry, formattedEntry T) bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.mu.filters = append(s.mu.filters, f...)
}

func (s *StructuredLogSpy[T]) ClearFilters() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.mu.filters = nil
}
```
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMlspcDoNONYigqn8Z:-NyMlspd3KGpusl26Bf5:b-gcwycw) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L193)):*
> ```Go
> 	if n > len(s.mu.logs[ch]) {
> 		n = len(s.mu.logs[ch])
> 	}
> ```

Here and in other functions, should we add some existence checks for the various `s.mu.logs[ch]` map accesses? 



_Code quote:_
```Go
	if n > len(s.mu.logs[ch]) {
		n = len(s.mu.logs[ch])
	}
```

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124301)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @kyle-a-wong, @nkodali, and @xinhaoz)

___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMnQT35U-KYNvZ_N9D:-NyMnQT35U-KYNvZ_N9E:b-ywquez) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L130)):*
> ```Go
> 	testState *testing.T,
> 	channels []logpb.Channel,
> 	eventTypes []string,
> ```

I don't see usage with multiple channels/events. Is it necessary to support? Same with format + filters, can we get away with a single `filter` function that combines formatting? Not sure the interface really needs both since in the simplest case someone might just want to manipulate the entry directly.
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMjZvQ9J-WV5iG0nNi:-NyMnPBsAKOJM8bdOi1T:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L133)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: comments/docs explaining how things like `format`, `filters`, etc. work
</blockquote></details>

+1
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMkUCm7qHSLUbw0n6l:-NyMo5QKBnagPSstgykb:b50019m) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L164)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Do we have examples of tests needing to modify filters post-construction? If a test needs different filters, should we just create a new `StructuredLogSpy`?
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/124371/commits/298f0dd20d3ef0c7b6cc03935aca28730ceab3f2#diff-2b876a20003068a4ddca879d6c283764b01434281d2015c00037d5e084012436R117-R119

**Review by kyle-a-wong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124301)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @nkodali, and @xinhaoz)

___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMo4Jw3T7tdKtMqBDj:-NyMo4Jw3T7tdKtMqBDk:b-7epq1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L208)):*
> ```Go
> }
> 
> func (s *StructuredLogSpy[T]) Intercept(entry []byte) {
> ```

Is there a reason why the funcs above have doc strings but this one and the ones below don't?
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMozA8C65gdOH4BVLe:-NyMozA8C65gdOH4BVLf:bhzxk8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L227)):*
> ```Go
> 			}
> 			return false
> 		}()
> ```

What is the purpose of this being an IFFE?



_Code quote:_
```Go
		found := func() bool {
			for _, re := range s.eventTypeRe {
				if re.MatchString(logEntry.Message) {
					return true
				}
			}
			return false
		}()
```

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124301)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @kyle-a-wong, @nkodali, and @xinhaoz)

___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMjjohC4xrIWUr7T69:-NyMsb8rDQyMeITvdgVC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L106)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: docstring for the exported type explaining it's use/function.
</blockquote></details>

Done.
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMiolOBBpUooNJwKE1:-NyMsj-q98qEoJzn3VPH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L110)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can this just be `map[logpb.Channel]struct{}{}`?
</blockquote></details>

Done.
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMnQT35U-KYNvZ_N9D:-NyN0rljD7q7lkuM93q3:bgvbxgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L130)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I don't see usage with multiple channels/events. Is it necessary to support? Same with format + filters, can we get away with a single `filter` function that combines formatting? Not sure the interface really needs both since in the simplest case someone might just want to manipulate the entry directly.
</blockquote></details>

I don't see any harm with extending it to multiple channels. One motivation for this many-to-one case: I was hoping to use this for some datadriven testing for sql exec / perf channels similar to what we have for telemetry and it would be nice to have one log spy for all of them, since they'd all use the same string format function. Appending a channel name to the log spy in that case will save us from having to create and manage separate log spies for all of them.

Similarly for the format / filter functions, I've found some utility in separating those two ops for reuse. Esp if we might have different tests being setup with their own log spies for the same events, it's nice not having to write the same format function multiple times, but allow those spies to have different filtering behaviours. LMK though and I can convert it to a single channel / function if desired.
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMjZvQ9J-WV5iG0nNi:-NyMssYb7VbcRYaJSbA7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L133)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMkUCm7qHSLUbw0n6l:-NyN31WU8cLboBYaXFAI:bjvitoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L164)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/pull/124371/commits/298f0dd20d3ef0c7b6cc03935aca28730ceab3f2#diff-2b876a20003068a4ddca879d6c283764b01434281d2015c00037d5e084012436R117-R119
</blockquote></details>

Yes, we do always have the option of creating a separate log spy. I find these functions just add some shortcuts so that we don't always need to. 
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMlspcDoNONYigqn8Z:-NyMzZZ17E8kQ8bAQ2dw:b-ob2e0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L193)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Here and in other functions, should we add some existence checks for the various `s.mu.logs[ch]` map accesses?
</blockquote></details>

Working with a nil slice is actually pretty ergonomic in golang. The bottom will just append no entries if we get a nil entry.
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMo4Jw3T7tdKtMqBDj:-NyN3CxC5muk8lla8kEk:bqmjwcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L208)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

Is there a reason why the funcs above have doc strings but this one and the ones below don't?
</blockquote></details>

Added!
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMozA8C65gdOH4BVLe:-NyN0AOE0daaGc_xQEzC:b-i1pa74) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L227)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

What is the purpose of this being an IFFE?
</blockquote></details>

Was just trying to avoid having to do a loop with a break to accomplish `array.some`. Can convert it to that or something else if you have suggestions to make it more readable.

**Review by kyle-a-wong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124301)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @nkodali, and @xinhaoz)

___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMo4Jw3T7tdKtMqBDj:-NyQWp-7DfiUvgNswQg4:bb7k0qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L208)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Added!
</blockquote></details>

lgtm
___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMozA8C65gdOH4BVLe:-NyQWvmO0ACzNU6AM7nm:b-95zq81) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L227)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Was just trying to avoid having to do a loop with a break to accomplish `array.some`. Can convert it to that or something else if you have suggestions to make it more readable.
</blockquote></details>

Ahhh, thanks for the info. I don't have a particular opinion or suggestion about what is most readable.  I was mostly just wondering if this was an idiosyncrasy of golang or just an implementation decision.

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-:-NyQfa6KDjJVHetdp32L:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @nkodali, and @xinhaoz)

___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMkUCm7qHSLUbw0n6l:-NyQfOpz1tt-RitDS-m5:b-t4tvpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L164)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Yes, we do always have the option of creating a separate log spy. I find these functions just add some shortcuts so that we don't always need to.
</blockquote></details>

Ack, thanks for the example usage.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-:-NyOD-dH1HaxQS8iB3d1:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @nkodali and @xinhaoz)

___
*[`pkg/util/log/logtestutils/structured_log_spy.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124301#-NyMnQT35U-KYNvZ_N9D:-NyOCUWl8OlhhqRB92Gd:b8z5gf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ca692b21916510f6cb45603b54fc4b8f502be3/pkg/util/log/logtestutils/structured_log_spy.go#L130)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I don't see any harm with extending it to multiple channels. One motivation for this many-to-one case: I was hoping to use this for some datadriven testing for sql exec / perf channels similar to what we have for telemetry and it would be nice to have one log spy for all of them, since they'd all use the same string format function. Appending a channel name to the log spy in that case will save us from having to create and manage separate log spies for all of them.

Similarly for the format / filter functions, I've found some utility in separating those two ops for reuse. Esp if we might have different tests being setup with their own log spies for the same events, it's nice not having to write the same format function multiple times, but allow those spies to have different filtering behaviours. LMK though and I can convert it to a single channel / function if desired.
</blockquote></details>

:thumbsup: thanks for the note

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
