### PR TITLE
ui: add PGCode to admin api errors

### LINKED ISSUE #98596: admin api: Add PGCode to generic message
The current error message returned on the SQL Activity pages is:
`bundle.js:1793 Error Loading statements: RequestError: An internal server error has occurred. Please check your CockroachDB logs for more details`

It would be ideal to return the PGCode to easily troubleshoot why the underlying query failed. It would avoid the pain of needing to get the db logs and attempt to correlate them with the ui console logs. 

Jira issue: CRDB-25351

### PR DESCRIPTION
**Pull request by j82w**
Adding the PGCode makes it easy to identify
the underlying issue of why the request failed.

old error:
```
RequestError: An internal server error has occurred.
Please check your CockroachDB logs for more details.
```

new error
```
RequestError: An internal server error has occurred. 
Please check your CockroachDB logs for more details. Error Code: 53200
```

Screenshot 2023-03-14 at 2 51 57 PM

Epic: none
Closes: #98596

Release note: none

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98601)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @j82w)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98601#-NQWGMOw4vB-3PHtCb1E):*
Yay!! 
Just wondering if we should use `PGCode` or just `Error Code`
thoughts @kevin-v-ngo ?

**Comment by kevin-v-ngo** [comment]
> > Reviewed 1 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98601)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @j82w)
> 
> _[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98601#-NQWGMOw4vB-3PHtCb1E):_ Yay!! Just wondering if we should use `PGCode` or just `Error Code` thoughts @kevin-v-ngo ?

Although the majority are PG error codes, we do have a subset of CRDB specific errors. So not opposed to just Error Code.

**Comment by j82w** [comment]
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98601#-NQWGMOw4vB-3PHtCb1E):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Yay!! 
Just wondering if we should use `PGCode` or just `Error Code`
thoughts @kevin-v-ngo ?
</blockquote></details>

I'm good either way. I went ahead and switched it to Error Code.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98601#-:-NQX1Ggo6U2AXD9JtVwh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @kevin-v-ngo)

**Comment by maryliag** [comment]
can you also backport this to 22.2 and 22.1?

**Review by dhartunian — APPROVED** [review]
:lgtm: nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98601#-:-NQaqERLCtSU2LPZ_PuW:b-7yytuz)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @kevin-v-ngo)

**Pull request merged**
