### PR TITLE
roachtest: admission/follower-overload test improvements

### PR DESCRIPTION
**Pull request by aadityasondhi**
[roachtest: fix zone config syntax in ac follower overload test](https://github.com/cockroachdb/cockroach/pull/117988/commits/c80491e9e86bd37c7ce52a5f991f204d94e2020a) 

Informs https://github.com/cockroachdb/cockroach/issues/82508.

Release note: None

---

[roachtest: add bandwidth overload test in admission/follower-overload](https://github.com/cockroachdb/cockroach/pull/117988/commits/d0dc296e1d23345d3b387e735652fd2317066102) 

This aims to simulate read bandwidth induced overload by running a large
kv0 workload on a 3 node cluster, while all the leases are owned by n1 and
n2.

Informs https://github.com/cockroachdb/cockroach/issues/82508.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117988)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @DarrylWong, and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/admission_control_follower_overload.go` line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117988#-NonPnblE7k6pp9AWHjz:-NonPnblE7k6pp9AWHk-:b-50988h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4592a545aa4879fdedbd6dfae25739999c4bc62/pkg/cmd/roachtest/tests/admission_control_follower_overload.go#L173)):*
> ```Go
> 		t, `SELECT target FROM [ SHOW ZONE CONFIGURATIONS ]`,
> 	) {
> 		q := `ALTER ` + row[0] + ` CONFIGURE ZONE USING lease_preferences = '[[-node3]]', constraints = '[-node3]'`
> ```

isn't this also removing the replicas from node3? The test comment above says that it wants follower replicas on node3.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117988)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @sumeerbhola)

___
*[`pkg/cmd/roachtest/tests/admission_control_follower_overload.go` line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117988#-NonPnblE7k6pp9AWHjz:-NorMnt21yHZj0rsTtwK:bb8wwfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4592a545aa4879fdedbd6dfae25739999c4bc62/pkg/cmd/roachtest/tests/admission_control_follower_overload.go#L173)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

isn't this also removing the replicas from node3? The test comment above says that it wants follower replicas on node3.
</blockquote></details>

Ah I missed that. Fixed.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117988)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @DarrylWong, and @herkolategan)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117988#-NpQjqRC07IwJEeP3qjF):*
nit: bandwidth


should this say "simulate read bandwidth ..."
___
*[`pkg/cmd/roachtest/tests/admission_control_follower_overload.go` line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117988#-NpQk0R6DRUrZtTFd7Np:-NpQk0R6DRUrZtTFd7Nq:b-mtuhjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7bdcaa39d52909aff7453412258d240ffe3554d/pkg/cmd/roachtest/tests/admission_control_follower_overload.go#L109)):*
> ```Go
> 	// increased kv0 writes to isolate for bandwidth induced overload.
> 	//
> 	//NB: As of Jan 2024, this test is specific to AWS only.
> ```

nit: // NB: ...
___
*[`pkg/cmd/roachtest/tests/admission_control_follower_overload.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117988#-NpQkGAvEJeFF6cW7Ezw:-NpQkGAvEJeFF6cW7Ezx:b-1189ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7bdcaa39d52909aff7453412258d240ffe3554d/pkg/cmd/roachtest/tests/admission_control_follower_overload.go#L127)):*
> ```Go
> 	kvN12ExtraArgs   string
> 	kv0N12           bool                            // run kv0 on n1 and n2
> 	kv0N12BlockBytes string                          // block bytes for kv0 on n1 and n2
> ```

can you add to the code comment that it is optional and what the default value is.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117988)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @sumeerbhola)

___
*[`pkg/cmd/roachtest/tests/admission_control_follower_overload.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117988#-NpQkGAvEJeFF6cW7Ezw:-NpuT0gQ75nIWJZJ9dsI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7bdcaa39d52909aff7453412258d240ffe3554d/pkg/cmd/roachtest/tests/admission_control_follower_overload.go#L127)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add to the code comment that it is optional and what the default value is.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117988#-:-Npyz0rmB2IoP4T8_jay:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

**Comment by aadityasondhi** [comment]
bors r=sumeerbhola

**Pull request merged**
