### PR TITLE
sql: always encode STORING columns in value

### PR DESCRIPTION
**Pull request by eisenstatdavid**
The new encoding for STORING columns is to store them in the same
value-encoded tuple that composite columns use. Keeping STORING columns
out of KV keys is good for performance; see #14601 for a discussion of
the design space.

This format change is backward compatible: old index descriptors with
STORING columns will continue to use the old format. To switch, create a
new index and drop the old one.

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm:

Is there a plan to deprecate and remove the old STORING encodings, or are we going to keep it around forever?

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sqlbase/structured.go, line 217 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhO3emCUAu5Fj0EY2AI:-KhO3emCUAu5Fj0EY2AJ:b3pch6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/structured.go#L217)):*
> ```Go
> 
> // ContainsColumnID returns true if the index descriptor contains the specified
> // column ID either in its explicit column IDs or the extra column IDs.
> ```

Need to update this comment to also list store column IDs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-:-KhO6Qz4yUJzHdMZGv70:b-upnff5)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/alter_table.go, line 261 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOe8p-5eFYjvLBmKss:-KhOe8p-5eFYjvLBmKst:b-7cnq2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/alter_table.go#L261)):*
> ```Go
> 					}
> 					// The loop above this comment is for the old STORING encoding. The
> 					// loop below is for the new encoding.
> ```

nit: provide a bit more context: "new encoding (where the STORING columns are always in the value part of a KV)"

---

*[pkg/sql/information_schema.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOfOl8pp5ZzHTZYI3b:-KhOfOl8pp5ZzHTZYI3c:b-8ee5wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/information_schema.go#L332)):*
> ```Go
> 				// index.StoreColumnNames are implicit columns in the index.
> 				var implicitCols map[string]struct{}
> 				if len(index.ExtraColumnIDs)+len(index.StoreColumnIDs) > len(index.StoreColumnNames) {
> ```

This check is confusing. I see why it works (StoreColumnIDs is either empty in the old encoding, or has the same length with StoreColumnNames in the new encoding) but it's pretty subtle. Needs a comment, perhaps also break it up into two different conditions depending if we are using the old encoding.

---

*[pkg/sql/sqlbase/structured.go, line 601 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOgpkYjtbYR_CmXEN5:-KhOgpkYjtbYR_CmXEN6:b-5znafp) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/structured.go#L601)):*
> ```Go
> 
> 		if index != &desc.PrimaryIndex {
> 			indexUsesOldStoringEncoding := len(index.ExtraColumnIDs) > 0 &&
> ```

This might be useful as a method on `IndexDescriptor`.

---

*[pkg/sql/sqlbase/structured.proto, line 187 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOfBPoECV4mG3NxHQ2:-KhOfBPoECV4mG3NxHQ3:b-kpc31p) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/structured.proto#L187)):*
> ```protobuf
> //   column_ids:          1, 2   // k1, k2
> //
> // Index k1v (k1, v) STORING (w):
> ```

This needs updating. Perhaps illustrate both the old and the new case.

---

*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhOhNrF9A7mMrBt2JSt:bwelpu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
> ```
> EXPLAIN (DEBUG) SELECT * FROM t@b_idx
> ----
> 0  /t/b_idx/2/1/c/d  /3/4  ROW
> ```

where are these "/c/d" coming from and why? they're not really part of the key are they?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/sqlbase/rowwriter.go, line 538 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhPjTpVeIbE_U80ezjo:-KhPjTpVeIbE_U80ezjp:b-6qb6tn) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/rowwriter.go#L538)):*
> ```Go
> 				if err := maybeAddCol(colID); err != nil {
> 					return RowUpdater{}, err
> 				}
> ```

Its a good time to add a new function to structured.go and use it for the two cases above.

```
func (desc *IndexDescriptor) RunOverAllColumns(fn  func(id ColumnID) error)) error {
                     for _, colID := range index.ColumnIDs {
				if err := fn(colID); err != nil {
					return err
				}
			}
			// The extra columns are needed to fix #14601.
			for _, colID := range index.ExtraColumnIDs {
				if err := fn(colID); err != nil {
					return err
				}
			}
			for _, colID := range index.StoreColumnIDs {
				if err := fn(colID); err != nil {
					return err
				}
                       }
        return nil
}

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by eisenstatdavid** [comment]
Vivek suggested that we ask six months (say) from now who has old indexes with STORING where they can't just add a new index with the same schema and drop the old one, then drop support for the old encoding if we don't get pushback. Not a lot of code would disappear though, since the encoder/decoder are very table driven.

---

Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/alter_table.go, line 261 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOe8p-5eFYjvLBmKss:-KhT9Co3i4FYPPDVD0VJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/alter_table.go#L261)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

nit: provide a bit more context: "new encoding (where the STORING columns are always in the value part of a KV)"
</blockquote></details>

Done.

---

*[pkg/sql/information_schema.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOfOl8pp5ZzHTZYI3b:-KhTBAjyNqEwlOooTrMz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/information_schema.go#L332)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This check is confusing. I see why it works (StoreColumnIDs is either empty in the old encoding, or has the same length with StoreColumnNames in the new encoding) but it's pretty subtle. Needs a comment, perhaps also break it up into two different conditions depending if we are using the old encoding.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/rowwriter.go, line 538 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhPjTpVeIbE_U80ezjo:-KhT8CUhxkT7KXUT86Tb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/rowwriter.go#L538)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Its a good time to add a new function to structured.go and use it for the two cases above.

```
func (desc *IndexDescriptor) RunOverAllColumns(fn  func(id ColumnID) error)) error {
                     for _, colID := range index.ColumnIDs {
				if err := fn(colID); err != nil {
					return err
				}
			}
			// The extra columns are needed to fix #14601.
			for _, colID := range index.ExtraColumnIDs {
				if err := fn(colID); err != nil {
					return err
				}
			}
			for _, colID := range index.StoreColumnIDs {
				if err := fn(colID); err != nil {
					return err
				}
                       }
        return nil
}

```
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.go, line 217 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhO3emCUAu5Fj0EY2AI:-KhT8cEQp4F0QFRASIxc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/structured.go#L217)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Need to update this comment to also list store column IDs.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.go, line 601 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOgpkYjtbYR_CmXEN5:-KhTA_y8SnfiWM-aPC1C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/structured.go#L601)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This might be useful as a method on `IndexDescriptor`.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.proto, line 187 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOfBPoECV4mG3NxHQ2:-KhTL5q4FrsJcFC6elsi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/sqlbase/structured.proto#L187)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This needs updating. Perhaps illustrate both the old and the new case.
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhTLDUxYmO27XtWWPw4:b-vzvbek) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

where are these "/c/d" coming from and why? they're not really part of the key are they?
</blockquote></details>

The decoder code paths for STORING are now the same as the composite decoder, where the value really is present in the key. Marking this comment blocking while I think about what I can do about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-:-KhTL_CdbrQqpDi71wfc:b4dxe52)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhTam8x4zJ_1vKgbRt4:b-taena6) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

The decoder code paths for STORING are now the same as the composite decoder, where the value really is present in the key. Marking this comment blocking while I think about what I can do about this.
</blockquote></details>

Actually, it seems that this is the intended behavior. The extra `/c/d` (`/b` below) are identifying the columns that appeared in the value.
```
root@:26257/> create table d.t (a int primary key, b int);
CREATE TABLE
root@:26257/> insert into d.t values (0,0),(1,1),(-1,1),(2,4);
INSERT 4
root@:26257/> explain (debug) select * from d.t;
+--------+-----------------+-------+-------------+
| RowIdx |       Key       | Value | Disposition |
+--------+-----------------+-------+-------------+
|      0 | /t/primary/-1/b | /1    | ROW         |
|      1 | /t/primary/0/b  | /0    | ROW         |
|      2 | /t/primary/1/b  | /1    | ROW         |
|      3 | /t/primary/2/b  | /4    | ROW         |
+--------+-----------------+-------+-------------+
(4 rows)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhTdGAXYtp5xYmCVEsX:bledh86) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Actually, it seems that this is the intended behavior. The extra `/c/d` (`/b` below) are identifying the columns that appeared in the value.
```
root@:26257/> create table d.t (a int primary key, b int);
CREATE TABLE
root@:26257/> insert into d.t values (0,0),(1,1),(-1,1),(2,4);
INSERT 4
root@:26257/> explain (debug) select * from d.t;
+--------+-----------------+-------+-------------+
| RowIdx |       Key       | Value | Disposition |
+--------+-----------------+-------+-------------+
|      0 | /t/primary/-1/b | /1    | ROW         |
|      1 | /t/primary/0/b  | /0    | ROW         |
|      2 | /t/primary/1/b  | /1    | ROW         |
|      3 | /t/primary/2/b  | /4    | ROW         |
+--------+-----------------+-------+-------------+
(4 rows)
```
</blockquote></details>

But that is coming from the fact that the primary index stores multiple KVs per row, so the keys have to be `/t/primary/pk/column` or `/t/primary/pk/column-family`.  A secondary index has one key per row so there wouldn't need to be anything like that in the key.

I'm still not understanding if this is just showing up as an artifact of the implementation, or if the index keys actually have column identifiers for `c` and `d` in them (which would be odd).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhThsANSJmSBWNq1sjN:b-1c4wbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But that is coming from the fact that the primary index stores multiple KVs per row, so the keys have to be `/t/primary/pk/column` or `/t/primary/pk/column-family`.  A secondary index has one key per row so there wouldn't need to be anything like that in the key.

I'm still not understanding if this is just showing up as an artifact of the implementation, or if the index keys actually have column identifiers for `c` and `d` in them (which would be odd).
</blockquote></details>

Here are two explain debug selects on primary indexes. My understanding is that the debug output has exactly one row per KV decoded, with `/columnname` designations appended to the key indicating exactly which values appear in the KV.
```
root@:26257/> create database d;
CREATE DATABASE
root@:26257/> create table d.t (a int primary key, b int, c int, family (a, b, c));
CREATE TABLE
root@:26257/> insert into d.t values (1,2,3),(4,5,6),(7,8,9);
INSERT 3
root@:26257/> explain (debug) select * from d.t;
+--------+------------------+-------+-------------+
| RowIdx |       Key        | Value | Disposition |
+--------+------------------+-------+-------------+
|      0 | /t/primary/1/b/c | /2/3  | ROW         |
|      1 | /t/primary/4/b/c | /5/6  | ROW         |
|      2 | /t/primary/7/b/c | /8/9  | ROW         |
+--------+------------------+-------+-------------+
(3 rows)
root@:26257/> drop table d.t;
DROP TABLE
root@:26257/> create table d.t (a int primary key, b int, c int, family (a), family (b), family (c));
CREATE TABLE
root@:26257/> insert into d.t values (1,2,3),(4,5,6),(7,8,9);
INSERT 3
root@:26257/> explain (debug) select * from d.t;
+--------+----------------+-------+-------------+
| RowIdx |      Key       | Value | Disposition |
+--------+----------------+-------+-------------+
|      0 | /t/primary/1   | NULL  | PARTIAL     |
|      0 | /t/primary/1/b |     2 | PARTIAL     |
|      0 | /t/primary/1/c |     3 | ROW         |
|      1 | /t/primary/4   | NULL  | PARTIAL     |
|      1 | /t/primary/4/b |     5 | PARTIAL     |
|      1 | /t/primary/4/c |     6 | ROW         |
|      2 | /t/primary/7   | NULL  | PARTIAL     |
|      2 | /t/primary/7/b |     8 | PARTIAL     |
|      2 | /t/primary/7/c |     9 | ROW         |
+--------+----------------+-------+-------------+
(9 rows)
root@:26257/>
``` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhTjFnzbVwjTU4LV_YR:b10x593) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Here are two explain debug selects on primary indexes. My understanding is that the debug output has exactly one row per KV decoded, with `/columnname` designations appended to the key indicating exactly which values appear in the KV.
```
root@:26257/> create database d;
CREATE DATABASE
root@:26257/> create table d.t (a int primary key, b int, c int, family (a, b, c));
CREATE TABLE
root@:26257/> insert into d.t values (1,2,3),(4,5,6),(7,8,9);
INSERT 3
root@:26257/> explain (debug) select * from d.t;
+--------+------------------+-------+-------------+
| RowIdx |       Key        | Value | Disposition |
+--------+------------------+-------+-------------+
|      0 | /t/primary/1/b/c | /2/3  | ROW         |
|      1 | /t/primary/4/b/c | /5/6  | ROW         |
|      2 | /t/primary/7/b/c | /8/9  | ROW         |
+--------+------------------+-------+-------------+
(3 rows)
root@:26257/> drop table d.t;
DROP TABLE
root@:26257/> create table d.t (a int primary key, b int, c int, family (a), family (b), family (c));
CREATE TABLE
root@:26257/> insert into d.t values (1,2,3),(4,5,6),(7,8,9);
INSERT 3
root@:26257/> explain (debug) select * from d.t;
+--------+----------------+-------+-------------+
| RowIdx |      Key       | Value | Disposition |
+--------+----------------+-------+-------------+
|      0 | /t/primary/1   | NULL  | PARTIAL     |
|      0 | /t/primary/1/b |     2 | PARTIAL     |
|      0 | /t/primary/1/c |     3 | ROW         |
|      1 | /t/primary/4   | NULL  | PARTIAL     |
|      1 | /t/primary/4/b |     5 | PARTIAL     |
|      1 | /t/primary/4/c |     6 | ROW         |
|      2 | /t/primary/7   | NULL  | PARTIAL     |
|      2 | /t/primary/7/b |     8 | PARTIAL     |
|      2 | /t/primary/7/c |     9 | ROW         |
+--------+----------------+-------+-------------+
(9 rows)
root@:26257/>
``` 
</blockquote></details>

Better example:
```
root@:26257/> create table d.t (a int primary key, b int, c int, family (a, b, c));
CREATE TABLE
root@:26257/> insert into d.t values (0,null,null),(1,2,null),(3,4,5);
INSERT 3
root@:26257/> explain (debug) select * from d.t;
+--------+------------------+-------+-------------+
| RowIdx |       Key        | Value | Disposition |
+--------+------------------+-------+-------------+
|      0 | /t/primary/0     | NULL  | ROW         |
|      1 | /t/primary/1/b   | /2    | ROW         |
|      2 | /t/primary/3/b/c | /4/5  | ROW         |
+--------+------------------+-------+-------------+
(3 rows)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhTmeFtlpL_RDcwpKZ0:b-rqcnvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Better example:
```
root@:26257/> create table d.t (a int primary key, b int, c int, family (a, b, c));
CREATE TABLE
root@:26257/> insert into d.t values (0,null,null),(1,2,null),(3,4,5);
INSERT 3
root@:26257/> explain (debug) select * from d.t;
+--------+------------------+-------+-------------+
| RowIdx |       Key        | Value | Disposition |
+--------+------------------+-------+-------------+
|      0 | /t/primary/0     | NULL  | ROW         |
|      1 | /t/primary/1/b   | /2    | ROW         |
|      2 | /t/primary/3/b/c | /4/5  | ROW         |
+--------+------------------+-------+-------------+
(3 rows)
```
</blockquote></details>

In your first example, `/t/primary/1`, `/t/primary/1/b`, and `/t/primary/1/c` ARE actual keys. The `b`, `c` are part of the keys, as expected for primary indexes. They are not appended as debug-info designations (that wouldn't even make sense, we can't have multiple KVs with the same `/t/primary/1` key). 

In a secondary index, this is not the case:
```
root@:26257/test> CREATE TABLE t (k INT PRIMARY KEY, v INT, UNIQUE INDEX v(v));
root@:26257/test> INSERT INTO t VALUES (1,10), (2,20), (3, 30);
root@:26257/test> EXPLAIN (DEBUG) SELECT * FROM t@v;
+--------+---------+-------+-------------+
| RowIdx |   Key   | Value | Disposition |
+--------+---------+-------+-------------+
|      0 | /t/v/10 | /1    | ROW         |
|      1 | /t/v/20 | /2    | ROW         |
|      2 | /t/v/30 | /3    | ROW         |
+--------+---------+-------+-------------+
```
No `/k` here..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/storing, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-KhOhNrF9A7mMrBt2JSs:-KhTr1r_JzbVSXwyUhYJ:b-qrj2wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/04096ac1fe063323dce4ed9e700ca2191ad0a90e/pkg/sql/testdata/logic_test/storing#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In your first example, `/t/primary/1`, `/t/primary/1/b`, and `/t/primary/1/c` ARE actual keys. The `b`, `c` are part of the keys, as expected for primary indexes. They are not appended as debug-info designations (that wouldn't even make sense, we can't have multiple KVs with the same `/t/primary/1` key). 

In a secondary index, this is not the case:
```
root@:26257/test> CREATE TABLE t (k INT PRIMARY KEY, v INT, UNIQUE INDEX v(v));
root@:26257/test> INSERT INTO t VALUES (1,10), (2,20), (3, 30);
root@:26257/test> EXPLAIN (DEBUG) SELECT * FROM t@v;
+--------+---------+-------+-------------+
| RowIdx |   Key   | Value | Disposition |
+--------+---------+-------+-------------+
|      0 | /t/v/10 | /1    | ROW         |
|      1 | /t/v/20 | /2    | ROW         |
|      2 | /t/v/30 | /3    | ROW         |
+--------+---------+-------+-------------+
```
No `/k` here..
</blockquote></details>

Talked offline, indeed the decoding path appends the column designations.

Updates LGTM, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758)*

**Comment by RaduBerinde** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-:-KhTt-nHnA1N6l2gnFYd:bnfp4nl)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14758#-:-KhV-y1GYWVC1zkZPAUN:bnfp4nl)*

**Pull request merged**
