### PR TITLE
storage: better tracing, faster MVCCGarbageCollect

### PR DESCRIPTION
**Pull request by tbg**
I'll run the benchmarks for MVCCGarbageCollect once they have merged and
will update the commit message.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/cli/debug.go, line 518 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5X31KS1Zp3weijPA:-Kl-5X32ZEMBY8vvgqdD:b5dsmo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a0c6e41c2a6b87b7417556e375a4220ccb13ef/pkg/cli/debug.go#L518)):*
> ```Go
> 	defer stopper.Stop(stopperContext(stopper))
> 
> 	if n := len(args); n != 1 || n != 2 {
> ```

can you combine this with the next `if` below into a `switch len(args)`? seems like that duplication was the cause of this mistake to begin with.

---

*[pkg/storage/replica.go, line 2547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5te1-QDgJrQwZN9F:-Kl-5te1-QDgJrQwZN9G:bceaj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2547)):*
> ```Go
> 	r.mu.Lock()
> 	defer r.mu.Unlock()
> 	log.Event(proposal.ctx, "acquired {raft,replica}mu")
> ```

don't want to separate these?

---

*[pkg/storage/replica.go, line 2606 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5zZRe1f6nPo03bq1:-Kl-5zZRe1f6nPo03bq2:bvoe0g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2606)):*
> ```Go
> 
> func defaultSubmitProposalLocked(r *Replica, p *ProposalData) error {
> 	log.Eventf(p.ctx, "proposing at MaxLeaseIndex=%d (~%d requests in-flight)",
> ```

is `p.ctx` already annotated?

---

*[pkg/storage/replica.go, line 2607 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-60ulf-5Rm55ePk_d:-Kl-60ulf-5Rm55ePk_e:bpodfyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2607)):*
> ```Go
> func defaultSubmitProposalLocked(r *Replica, p *ProposalData) error {
> 	log.Eventf(p.ctx, "proposing at MaxLeaseIndex=%d (~%d requests in-flight)",
> 		p.command.MaxLeaseIndex, len(r.mu.proposals)-1)
> ```

how come -1? is it to avoid counting this command proposal itself?

---

*[pkg/storage/engine/mvcc.go, line 2124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5n5yDpoOZ1l-oiOO:-Kl-5n5yDpoOZ1l-oiOP:b-gavo4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/da3d983f2c2733ae580fbf8afc7768be6bffa251/pkg/storage/engine/mvcc.go#L2124)):*
> ```Go
> 		defer func() {
> 			log.Eventf(ctx, "done with GC evaluation for %d keys at %.2f keys/sec",
> 				len(keys), float64(len(keys))*1E9/float64(timeutil.Now().Sub(begin)))
> ```

`timeutil.Since(begin)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-:-Kl-6ALPXTaamfAOLTn3:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 2606 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-83HddvSg8KFcGA0N:-Kl-83HddvSg8KFcGA0O:b-hirjbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2606)):*
> ```Go
> 
> func defaultSubmitProposalLocked(r *Replica, p *ProposalData) error {
> 	log.Eventf(p.ctx, "proposing at MaxLeaseIndex=%d (~%d requests in-flight)",
> ```

`log.Eventf` isn't free. Might want to protect this with `if log.HasSpanOrEvent(p.ctx)`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-:-Kl-8HzIpSOeJXEgAMEg:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 2117 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-8Z6GsO4wSMsRURvB:-Kl-8Z6H9Zfb6mDg__Up:b-f5xhp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/engine/mvcc.go#L2117)):*
> ```Go
> 	// We're allowed to use a prefix iterator because we always Seek() the
> 	// iterator when handling a new user key.
> 	iter := engine.NewIterator(true)
> ```

Btw, I'd be interested in knowing what effect this has on the `MVCCGarbageCollect` benchmark. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/cli/debug.go, line 518 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5X31KS1Zp3weijPA:-Kl-Iko8eRiecFvDg1bi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a0c6e41c2a6b87b7417556e375a4220ccb13ef/pkg/cli/debug.go#L518)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you combine this with the next `if` below into a `switch len(args)`? seems like that duplication was the cause of this mistake to begin with.
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 2547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5te1-QDgJrQwZN9F:-Kl-JYtHe_-C19SH8qGT:bfbn77z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2547)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

don't want to separate these?
</blockquote></details>

No, I think this is sufficient - if there's a problem, I think we'll figure out which one's slow, and trace points aren't free (though I admit I'm not sure about their precise cost).

---

*[pkg/storage/replica.go, line 2606 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5zZRe1f6nPo03bq1:-Kl-IpekwIooBwUY_5XI:b-ix5r12) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2606)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is `p.ctx` already annotated?
</blockquote></details>

yes, this is right before going into Raft.

---

*[pkg/storage/replica.go, line 2606 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-83HddvSg8KFcGA0N:-Kl-JDjwxkaYHAeYvRXu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2606)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`log.Eventf` isn't free. Might want to protect this with `if log.HasSpanOrEvent(p.ctx)`. 
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 2607 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-60ulf-5Rm55ePk_d:-Kl-JELofy0bl7uwjK7Z:b-4ghlx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2607)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come -1? is it to avoid counting this command proposal itself?
</blockquote></details>

Yes. Added comment.

---

*[pkg/storage/engine/mvcc.go, line 2124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5n5yDpoOZ1l-oiOO:-Kl-JWVZI1jzit14Cd9_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da3d983f2c2733ae580fbf8afc7768be6bffa251/pkg/storage/engine/mvcc.go#L2124)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`timeutil.Since(begin)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/storage/engine/mvcc.go, line 2117 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-8Z6GsO4wSMsRURvB:-Kl-K1EJJ7HDpkmTvlEa:bukjagt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/engine/mvcc.go#L2117)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Btw, I'd be interested in knowing what effect this has on the `MVCCGarbageCollect` benchmark. 
</blockquote></details>

I'll let you know once I get the PR with that benchmark past CI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 2547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-Kl-5te1-QDgJrQwZN9F:-Kl-Kbnnh9FXDWNsilNR:b2nhk3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ee70f00b1aa67769b388bf28a0aeb8e6e801b/pkg/storage/replica.go#L2547)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

No, I think this is sufficient - if there's a problem, I think we'll figure out which one's slow, and trace points aren't free (though I admit I'm not sure about their precise cost).
</blockquote></details>

Mk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129)*

**Comment by tschottdorf** [comment]
Benchmarks added to second commit's message.

**Comment by bdarnell** [comment]
LGTM, but I'm not sure about putting this in 1.0.2. 

---

Reviewed 1 of 3 files at r4, 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16129#-:-Kl0PRAJY1U2E4dUbxLj:b-qa8wyv)*

**Comment by tschottdorf** [comment]
I've removed the label, if someone else wants it there, they should go ahead and speak up.

**Pull request merged**
