### PR TITLE
cli: Fix demo command's nodeName argument index while returning error

### PR DESCRIPTION
**Pull request by tharun208**
Release justification: fixes for high-priority or high-severity bugs
in existing functionality.

The demo command has a wrong nodeName index args while returning an error
which is leading to panic.
To address this, this patch contains the correct args index for nodeName.

Release note (bug fix): Fix demo commands nodeName error argument index handling.

Signed-off-by: Tharun <rajendrantharun@live.com>

### CODE REVIEW

**Review by knz — APPROVED** [review]
Thanks this look good, but please fix the commit message to remove the stray release justification/note at the bottom. Then we can merge this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61246#-:-MUh5mxz0kM7DgvmAcf7:b-oat0aw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tharun208** [comment]
@knz, I am adding a test for this. will remove the stray release justification/note with this.

**Review by knz — APPROVED** [review]
Nice, thank you!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61246#-:-MUhzME6DI4tmc4YUbb1:bf3vg7i)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
let's merge this

bors r+

**Pull request merged**
