### PR TITLE
sql: add json_array_length

### PR DESCRIPTION
**Pull request by heyihong**
Related to #20120.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Hello @heyihong ! Thank you for your contribution.

I notice that the "Release note" text is incorrect. Indeed, you are adding a built-in function. Therefore there is a user-facing change and this should be documented in the release note. Could you extend the commit message accordingly? Thanks!

**Comment by justinj** [comment]
Looks great after fixing knz's release note comment!

**Comment by heyihong** [comment]
Done. Please take another look.

**Comment by justinj** [comment]
👍

**Pull request merged**
