### PR TITLE
Trim the grammar.

### PR DESCRIPTION
**Pull request by petermattis**
I should have broken the initial commit into smaller changes. Mea culpa. I might have gone overboard in some of this trimming. Definitely flag anything that looks suspicious.

### CODE REVIEW

**Comment by tamird** [comment]
OK, LGTM.

**Comment by jusongchen** [comment]
CREATE TABLE ... AS <query> is a very useful feature. Without this feature,an end user cannot easily store a query result as a intermediate table. This feature is very useful when it comes to ad-hoc data analysis and it is widely supported by most RDBMS vendors.

**Comment by petermattis** [comment]
@jusongchen Thanks for the feedback. Supporting all of the SQL functionality of other RDBMS vendors isn't going to be feasible in the short term so we have to prioritize. And this functionality seemed good to cut. That said, it wouldn't be particularly difficult to implement if you have any interesting in helping out.

**Comment by petermattis** [comment]
@tamird No other comments on the grammar trimming? I was sure I must have overreached somewhere.

**Comment by tamird** [comment]
I'm not terribly concerned - missing things can always be resurrected.

**Pull request merged**
