### PR TITLE
kvconnectorccl: allow secondary tenants to prefetch range lookups

### LINKED ISSUE #91433: kv,server: enable some degree of range descriptor pre-fetching in secondary tenants
**Is your feature request related to a problem? Please describe.**
Currently we do not pre-fetch any additional range descriptors. See https://github.com/cockroachdb/cockroach/blob/44884454824c5892cacaa83cbfd4bb75edc4c258/pkg/ccl/kvccl/kvtenantccl/connector.go#L397-L400

**Describe the solution you'd like**
We should add some logic to filter range descriptors returned based on the tenant and then use the same pre-fetching logic we use in regular KV.

Epic: CRDB-18596

Jira issue: CRDB-21259

### PR DESCRIPTION
**Pull request by ajwerner**
This patch permits the tenant connector to request more than 0 ranges to be prefetched. In order to enable this, we add logic in the implementation of the RangeLookup RPC to filter any results which are not intended for this tenant.

Fixes #91433

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@nvanbenschoten are you willing to be the victim here?

**Comment by ajwerner** [comment]
@knz maybe you'd be interested in reviewing this?

**Review by knz — APPROVED** [review]
:lgtm: this is very good and helps much.

Could we trick this code to paper over  #92072 by tweaking the reported EndKey when it's outside of the tenant's keyspace?

 cc @ecwall you might find this interesting.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92265#-:-NHUgazdCAwp5dv0XagA:b2h5wmt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by ajwerner** [comment]
TFTR!

> Could we trick this code to paper over https://github.com/cockroachdb/cockroach/issues/92072 by tweaking the reported EndKey when it's outside of the tenant's keyspace?

I'll leave that for a later change. I do think it's reasonable. 

bors r+

**Pull request merged**
