### PR TITLE
release-21.1: server: add HSTS support via cluster setting

### LINKED ISSUE #77224: server: support HSTS header for HTTP connections on secure clusters
**Is your feature request related to a problem? Please describe.**
When a cluster is running in secure mode, an operator should be able to enable HSTS headers on requests to ensure that browsers only connect to the DB Console using HSTS.

**Describe the solution you'd like**
This feature should be off by default (to allow for operator-driven configuration of certs and DNS before enforcing things) and be enabled via a cluster setting named something like `security.hsts.enabled`. Once this is true, HTTP requests to nodes in the cluster will be automatically upgraded to HTTPS by valid user agents.

From casually thinking this through I don't think the addition of this will break any user agents that *don't* look at this header since they'll just still use the HTTP -> HTTPS redirect. However, enabling this with an invalid HTTPS configuration could result in an unreachable DB Console from a web browser so we should take care to document properly.

**Additional context**
* HSTS Explanation https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
* HTTP redirects are strictly less secure than HSTS because the initial HTTP request could be MITMed to redirect somewhere unsafe. With HSTS *all* requests in the browser after the initial one will use HTTPS and no redirect is necessary.

Jira issue: CRDB-13487

### PR DESCRIPTION
**Pull request by dhartunian**
Backport 1/1 commits from #77244.

/cc @cockroachdb/release

---

This commit adds a boolean cluster setting:
`server.hsts.enabled`
which, when enabled attaches standard HSTS headers to http requests
originating from CRDB nodes. The headers looke like this:
`Strict-Transport-Security: max-age=31536000`

When this header is present, most web browsers will automatically
upgrade all HTTP connections to HTTPS and *remember* that setting until
the expiry of 1 year defined in the header.

*Important*: Careless enabling of this feature can result in broken
access to the DB Console in the browser. If we instruct the browser to
always use HTTPS without having a valid TLS configuration, the browser
will no longer fallback to HTTP until the HSTS setting is manually
cleared.

Resolves #77224

Release justification: low-risk update; opt-in security enhancement

Release note (security update, ops change, ui change): users can enable
HSTS headers to be set on all HTTP requests which force browsers to
upgrade to HTTPS without a redirect. This is controlled by setting the
`server.hsts.enabled` cluster setting to true which is false by default.

### CODE REVIEW

**Comment by knz** [comment]
Wait are we backporting new features to 21.1 now? It's going out of support in a couple of months...

**Comment by dhartunian** [comment]
@knz in this case the customer that requested the feature is on 21.1 and asked for it to be backported. Since we're within the support window and the backport is straightforward I went ahead with it.

**Review by knz — APPROVED** [review]
thanks for explaining. I'm assuming this was approved by PM? @abhinavg6

**Comment by dhartunian** [comment]
I did not check with @abhinavg6 but will reach out separately. Thanks for the reminder.

**Pull request merged**
