### PR TITLE
internal/sqlsmith: add some more statements

### LINKED ISSUE #122541: sqlsmith: check that some DROPs are generated
Make sure that DROP FUNCTION, DROP TYPE, and DROP SEQUENCE are generated by sqlsmith.

Jira issue: CRDB-37951

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds DROP TYPE, DROP FUNCTION, CREATE SEQUENCE and DROP SEQUENCE statements. Additionally, it includes a possible scalar expression to use a sequence via `nextval` or `currval` builtins.

Fixes: #122541

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Ignore the first commit here - it's in #122713.

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you!

> Reviewed 1 of 1 files at r2, 8 of 8 files at r5, 8 of 8 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122671#-:-NwIyu5D7Lc0Y6toimEU:b-ae66e1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/cmd/smith/main.go` line 169 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122671#-Nw6W_jU8aSYYlDxm5bZ:-Nw6W_jU8aSYYlDxm5b_:bdm0tpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b63d4db07eb4eb25fc3a5afd70be614d737eee06/pkg/cmd/smith/main.go#L169)):*
> ```Go
> 			fmt.Print("\n", stmt, ";\n")
> 			if db != nil && *execStmts {
> 				_, _ = db.Exec(stmt)
> ```

Nice idea!
___
*[`pkg/internal/sqlsmith/alter.go` line 441 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122671#-NwIy4nL6JsERSVwu3Iy:-NwIy4nL6JsERSVwu3Iz:b-rwlhsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/102916b29e18b498024b91f2d64a6c08561c440e/pkg/internal/sqlsmith/alter.go#L441)):*
> ```Go
> 		Names:        typNames,
> 		IfExists:     s.d6() < 3,
> 		DropBehavior: tree.DropDefault,
> ```

Should this be `DropCascade` or `DropRestrict` some of the time?
___
*[`pkg/internal/sqlsmith/relational.go` line 936 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122671#-NwIyIjWA39-6RhJKcO3:-NwIyIjWA39-6RhJKcO4:bnsf14l) ([raw file](https://github.com/cockroachdb/cockroach/blob/102916b29e18b498024b91f2d64a6c08561c440e/pkg/internal/sqlsmith/relational.go#L936)):*
> ```Go
> 					Procedure:    false,
> 					Routines:     tree.RoutineObjs{routineObj},
> 					DropBehavior: tree.DropDefault,
> ```

same question here

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122671#-:-NwLX7eV0_BI0PGC-PkN:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/internal/sqlsmith/alter.go` line 441 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122671#-NwIy4nL6JsERSVwu3Iy:-NwLUnkAExVPU4tFV9IK:b-j1sfv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/102916b29e18b498024b91f2d64a6c08561c440e/pkg/internal/sqlsmith/alter.go#L441)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this be `DropCascade` or `DropRestrict` some of the time?
</blockquote></details>

Good point, done (although CASCADE is not supported for types and functions right now).
___
*[`pkg/internal/sqlsmith/relational.go` line 936 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122671#-NwIyIjWA39-6RhJKcO3:-NwLWedp77hUDb7C0M9O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/102916b29e18b498024b91f2d64a6c08561c440e/pkg/internal/sqlsmith/relational.go#L936)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

same question here
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Needed to rebase.

bors r+

**Pull request merged**
