### PR TITLE
Set default values for CIRCLE_NODE_{INDEX,TOTAL} if otherwise unset.

### LINKED ISSUE #3913: CIRCLE_NODE_TOTAL: unbound variable when running ./build/circle-deps.sh
I am in master branch with commit [ae2807b](https://github.com/cockroachdb/cockroach/commit/ae2807bd25ba36278f153860bb629b5e8a9496b0). Run the following commands:

```
make clean
./build/circle-local.sh
```

I got the following error:

```
real	0m0.104s
user	0m0.089s
sys	0m0.036s
+ exit 0
+ gopath0=/home/jing/code/go
+ is_shard 2
./build/circle-deps.sh: line 6: CIRCLE_NODE_TOTAL: unbound variable
++ notify
++ is_shard 1
./build/circle-deps.sh: line 6: CIRCLE_NODE_TOTAL: unbound variable
```

The full output:

```
+ '[' '' = docker ']'
+ shard1_done=/home/jing/shard1
+ shard2_done=/home/jing/shard2
+ trap notify EXIT
+ builder_dir=/home/jing/builder
+ mkdir -p /home/jing/builder
+ du -sh /home/jing/builder
4.0K	/home/jing/builder
+ ls -lah /home/jing/builder
total 8.0K
drwxrwxr-x  2 jing jing 4.0K  1月 18 22:54 .
drwxr-xr-x 79 jing jing 4.0K  1月 18 23:22 ..
+ tag=20151210-134003
+ docker images
+ grep -q 20151210-134003
+ HOME=
+ go get -u github.com/robfig/glock
+ grep -v '^cmd' GLOCKFILE
+ glock sync -n
github.com/VividCortex/ewma                        c34099b489e4	[OK]
github.com/agtorre/gocolorize                      f42b554bf7f0	[OK]
github.com/biogo/store                             3b4c041f52c2	[OK]
github.com/cockroachdb/c-lz4                       c40aaae2fc50	[OK]
github.com/cockroachdb/c-protobuf                  4feb192131ea	[OK]
github.com/cockroachdb/c-rocksdb                   b7fb7bddcb55	[OK]
github.com/cockroachdb/c-snappy                    5c6d0932e0ad	[OK]
github.com/cockroachdb/yacc                        443154b1852a	[OK]
github.com/codahale/hdrhistogram                   954f16e8b9ef	[OK]
github.com/coreos/etcd                             22dd738228b6	[OK]
github.com/docker/go-units                         0bbddae09c5a	[OK]
github.com/elazarl/go-bindata-assetfs              57eb5e1fc594	[OK]
github.com/go-sql-driver/mysql                     6fd058ce0d6b	[OK]
github.com/gogo/protobuf                           c57e439bad57	[OK]
github.com/golang/lint                             32a87160691b	[OK]
github.com/google/btree                            cc6329d4279e	[OK]
github.com/gordonklaus/ineffassign                 507e48671a07	[OK]
github.com/jteeuwen/go-bindata                     a0ff2567cfb7	[OK]
github.com/julienschmidt/httprouter                21439ef4d70b	[OK]
github.com/kisielk/errcheck                        1cd10f9f7824	[OK]
github.com/kisielk/gotool                          58a7a198f2ec	[OK]
github.com/kr/pretty                               e6ac2fc51e89	[OK]
github.com/kr/text                                 bb797dc4fb83	[OK]
github.com/lib/pq                                  8ad2b298cadd	[OK]
github.com/mattn/go-runewidth                      e882a96ec18d	[OK]
github.com/mibk/dupl                               47b66d6a523f	[OK]
github.com/montanaflynn/stats                      2c10aa99e7ec	[OK]
github.com/olekukonko/tablewriter                  cca8bbc07984	[OK]
github.com/opennota/check                          2647c7f78677	[OK]
github.com/peterh/liner                            d5e5aeeb67ca	[OK]
github.com/rcrowley/go-metrics                     51425a2415d2	[OK]
github.com/robfig/glock                            cb3c3ec56de9	[OK]
github.com/samalba/dockerclient                    548a5825c123	[OK]
github.com/spf13/cobra                             9c9300901990	[OK]
github.com/spf13/pflag                             7f60f83a2c81	[OK]
github.com/tebeka/go2xunit                         fff0d031ea2b	[OK]
github.com/termie/go-shutil                        bcacb06fecae	[OK]
golang.org/x/crypto                                3760e0168503	[OK]
golang.org/x/net                                   c92cdcb05f66	[OK]
golang.org/x/text                                  cf4986612c83	[OK]
golang.org/x/tools                                 ae18226edd6d	[OK]
gopkg.in/yaml.v1                                   9f9df34309c0	[OK]
++ dirname ./build/circle-deps.sh
+ ./build/builder.sh ./build/circle-deps.sh docker
+ '[' docker = docker ']'
+ is_shard 2
+ test 0 -eq 0
+ for i in bower_components node_modules typings
+ '[' -e ui/bower_components ']'
+ for i in bower_components node_modules typings
+ '[' -e ui/node_modules ']'
+ for i in bower_components node_modules typings
+ '[' -e ui/typings ']'
+ make -C ui npm.installed
make: Entering directory '/go/src/github.com/cockroachdb/cockroach/ui'
make: 'npm.installed' is up to date.
make: Leaving directory '/go/src/github.com/cockroachdb/cockroach/ui'

real	0m0.010s
user	0m0.004s
sys	0m0.006s
+ make -C ui npm.installed
make: Entering directory '/go/src/github.com/cockroachdb/cockroach/ui'
make: 'npm.installed' is up to date.
make: Leaving directory '/go/src/github.com/cockroachdb/cockroach/ui'
+ make -C ui bower.installed
make: Entering directory '/go/src/github.com/cockroachdb/cockroach/ui'
make: 'bower.installed' is up to date.
make: Leaving directory '/go/src/github.com/cockroachdb/cockroach/ui'

real	0m0.013s
user	0m0.000s
sys	0m0.013s
+ make -C ui bower.installed
make: Entering directory '/go/src/github.com/cockroachdb/cockroach/ui'
make: 'bower.installed' is up to date.
make: Leaving directory '/go/src/github.com/cockroachdb/cockroach/ui'
+ make -C ui tsd.installed
make: Entering directory '/go/src/github.com/cockroachdb/cockroach/ui'
make: 'tsd.installed' is up to date.
make: Leaving directory '/go/src/github.com/cockroachdb/cockroach/ui'

real	0m0.013s
user	0m0.000s
sys	0m0.012s
+ make -C ui tsd.installed
make: Entering directory '/go/src/github.com/cockroachdb/cockroach/ui'
make: 'tsd.installed' is up to date.
make: Leaving directory '/go/src/github.com/cockroachdb/cockroach/ui'
+ find /uicache/typings -type d
+ xargs chmod 0755
++ grep '^cmd' GLOCKFILE
++ grep -v glock
++ awk '{print $2}'
+ cmds='github.com/cockroachdb/c-protobuf/cmd/protoc
github.com/cockroachdb/cockroach/cmd/protoc-gen-gogoroach
github.com/cockroachdb/yacc
github.com/golang/lint/golint
github.com/gordonklaus/ineffassign
github.com/jteeuwen/go-bindata/go-bindata
github.com/kisielk/errcheck
github.com/mibk/dupl
github.com/opennota/check/cmd/varcheck
github.com/tebeka/go2xunit
golang.org/x/tools/cmd/goimports
golang.org/x/tools/cmd/stress
golang.org/x/tools/cmd/stringer'
+ go install -v github.com/cockroachdb/c-protobuf/cmd/protoc github.com/cockroachdb/cockroach/cmd/protoc-gen-gogoroach github.com/cockroachdb/yacc github.com/golang/lint/golint github.com/gordonklaus/ineffassign github.com/jteeuwen/go-bindata/go-bindata github.com/kisielk/errcheck github.com/mibk/dupl github.com/opennota/check/cmd/varcheck github.com/tebeka/go2xunit golang.org/x/tools/cmd/goimports golang.org/x/tools/cmd/stress golang.org/x/tools/cmd/stringer
github.com/cockroachdb/c-protobuf
github.com/cockroachdb/c-protobuf/libprotoc
github.com/gogo/protobuf/proto
golang.org/x/tools/go/exact
golang.org/x/tools/go/types
github.com/gogo/protobuf/protoc-gen-gogo/descriptor
github.com/gogo/protobuf/gogoproto
github.com/gogo/protobuf/vanity
github.com/gogo/protobuf/protoc-gen-gogo/plugin
github.com/gogo/protobuf/protoc-gen-gogo/generator
golang.org/x/tools/go/gcimporter
github.com/golang/lint
github.com/golang/lint/golint
github.com/gogo/protobuf/plugin/defaultcheck
github.com/gogo/protobuf/plugin/testgen
github.com/gogo/protobuf/plugin/embedcheck
github.com/gogo/protobuf/plugin/description
github.com/gogo/protobuf/plugin/enumstringer
github.com/gogo/protobuf/plugin/equal
github.com/gogo/protobuf/plugin/face
github.com/gogo/protobuf/plugin/gostring
github.com/gogo/protobuf/plugin/grpc
github.com/gogo/protobuf/plugin/marshalto
github.com/gogo/protobuf/plugin/oneofcheck
github.com/gogo/protobuf/plugin/populate
github.com/gogo/protobuf/plugin/size
github.com/gogo/protobuf/plugin/stringer
github.com/gogo/protobuf/plugin/union
github.com/gogo/protobuf/plugin/unmarshal
github.com/jteeuwen/go-bindata
github.com/jteeuwen/go-bindata/go-bindata
github.com/gogo/protobuf/vanity/command
github.com/cockroachdb/cockroach/cmd/protoc-gen-gogoroach
golang.org/x/tools/go/ast/astutil
golang.org/x/tools/go/buildutil
golang.org/x/tools/go/loader
github.com/kisielk/errcheck/internal/errcheck
github.com/kisielk/gotool
github.com/kisielk/errcheck
github.com/mibk/dupl/suffixtree
github.com/mibk/dupl/syntax
github.com/mibk/dupl/syntax/golang
github.com/mibk/dupl/job
github.com/mibk/dupl/output
github.com/mibk/dupl/remote
github.com/mibk/dupl
github.com/opennota/check/cmd/varcheck
golang.org/x/tools/imports
golang.org/x/tools/cmd/goimports
github.com/cockroachdb/c-protobuf/cmd/protoc

real	2m20.165s
user	4m25.518s
sys	0m17.366s
+ is_shard 1
+ test 0 -eq 0
+ go test -race -v -i ./...
github.com/cockroachdb/cockroach/roachpb
github.com/cockroachdb/cockroach/util/log
github.com/cockroachdb/cockroach/util/hlc
github.com/cockroachdb/cockroach/util/tracer
github.com/cockroachdb/cockroach/keys
github.com/cockroachdb/cockroach/gossip/resolver
github.com/cockroachdb/cockroach/util/cache
github.com/cockroachdb/cockroach/rpc
github.com/cockroachdb/cockroach/sql/parser
github.com/cockroachdb/cockroach/config
github.com/cockroachdb/cockroach/storage/engine
github.com/cockroachdb/cockroach/client
github.com/cockroachdb/cockroach/gossip
github.com/cockroachdb/cockroach/ts
github.com/cockroachdb/cockroach/gossip/simulation
github.com/cockroachdb/cockroach/testutils/gossiputil
github.com/cockroachdb/cockroach/sql
github.com/cockroachdb/cockroach/storage
github.com/cockroachdb/cockroach/sql/pgwire
github.com/cockroachdb/cockroach/kv
github.com/cockroachdb/cockroach/server/status
github.com/cockroachdb/cockroach/server
github.com/cockroachdb/cockroach/cli
github.com/cockroachdb/cockroach/testutils/sqlutils

real	0m12.884s
user	0m27.191s
sys	0m1.614s
+ go install -v github.com/tebeka/go2xunit

real	0m0.044s
user	0m0.040s
sys	0m0.008s
+ is_shard 0
+ test 0 -eq 0
+ make install GOFLAGS=-v
go install -tags '' -v -ldflags '-X "github.com/cockroachdb/cockroach/util.buildTag=v0.1-alpha-463-gae2807b" -X "github.com/cockroachdb/cockroach/util.buildTime=2016/01/18 15:25:32" -X "github.com/cockroachdb/cockroach/util.buildDeps=github.com/VividCortex/ewma:c34099b489e4ac33ca8d8c5f9d29d6eeaf69f2ed github.com/biogo/store:3b4c041f52c224ee4a44f5c8b150d003a40643a0 github.com/cockroachdb/c-lz4:c40aaae2fc50293eb8750b34632bc3efe813e23f github.com/cockroachdb/c-protobuf:4feb192131ea08dfbd7253a00868ad69cbb61b81 github.com/cockroachdb/c-rocksdb:b7fb7bddcb55be35eacdf67e9e2c931083ce02c4 github.com/cockroachdb/c-snappy:5c6d0932e0adaffce4bfca7bdf2ac37f79952ccf github.com/cockroachdb/cockroach:ae2807bd25ba36278f153860bb629b5e8a9496b0 github.com/codahale/hdrhistogram:954f16e8b9ef0e5d5189456aa4c1202758e04f17 github.com/coreos/etcd:22dd738228b60c5d55ce7a0f8fc0499ae9911910 github.com/elazarl/go-bindata-assetfs:57eb5e1fc594ad4b0b1dbea7b286d299e0cb43c2 github.com/gogo/protobuf:c57e439bad574c2e0877ff18d514badcfced004d github.com/google/btree:cc6329d4279e3f025a53a83c397d2339b5705c45 github.com/julienschmidt/httprouter:21439ef4d70ba4f3e2a5ed9249e7b03af4019b40 github.com/lib/pq:8ad2b298cadd691a77015666a5372eae5dbfac8f github.com/mattn/go-runewidth:e882a96ec18dd43fa283187b66af74497c9101c0 github.com/montanaflynn/stats:2c10aa99e7ec8c4607d4427ec7a1a60fcdfce85f github.com/olekukonko/tablewriter:cca8bbc0798408af109aaaa239cbd2634846b340 github.com/peterh/liner:d5e5aeeb67ca5aeeddeb0b6c3af05421ff63a0b6 github.com/rcrowley/go-metrics:51425a2415d21afadfd55cd93432c0bc69e9598d github.com/spf13/cobra:9c9300901990faada0c5fb3b5730f452585c7c2b github.com/spf13/pflag:7f60f83a2c81bc3c3c0d5297f61ddfa68da9d3b7 golang.org/x/crypto:3760e016850398b85094c4c99e955b8c3dea5711 golang.org/x/net:c92cdcb05f66ce5b61460e23498d2dc5fcf69aaf golang.org/x/text:cf4986612c83df6c55578ba198316d1684a9a287 gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b0f696e1de"'
github.com/cockroachdb/cockroach/util/retry
github.com/cockroachdb/cockroach/util/uuid
github.com/cockroachdb/c-lz4
github.com/cockroachdb/cockroach/util/caller
github.com/cockroachdb/c-snappy
github.com/cockroachdb/cockroach/rpc/codec/wire
github.com/cockroachdb/cockroach/util/stop
github.com/cockroachdb/cockroach/util
github.com/cockroachdb/cockroach/util/log/logflags
github.com/cockroachdb/cockroach/sql/privilege
github.com/cockroachdb/cockroach/util/metric
github.com/cockroachdb/cockroach/ui
github.com/cockroachdb/cockroach/security
github.com/cockroachdb/cockroach/base
github.com/cockroachdb/cockroach/util/encoding
github.com/cockroachdb/cockroach/roachpb
github.com/cockroachdb/cockroach/testutils
github.com/cockroachdb/cockroach/util/randutil
github.com/cockroachdb/cockroach/rpc/codec
github.com/cockroachdb/c-rocksdb
github.com/cockroachdb/cockroach/util/log
github.com/cockroachdb/cockroach/util/hlc
github.com/cockroachdb/cockroach/util/tracer
github.com/cockroachdb/cockroach/keys
github.com/cockroachdb/cockroach/gossip/resolver
github.com/cockroachdb/cockroach/rpc
github.com/cockroachdb/cockroach/sql/driver
github.com/cockroachdb/cockroach/config
github.com/cockroachdb/cockroach/util/cache
github.com/cockroachdb/cockroach/client
github.com/cockroachdb/cockroach/gossip
github.com/cockroachdb/cockroach/sql/parser
github.com/cockroachdb/cockroach/ts
github.com/cockroachdb/cockroach/sql
github.com/cockroachdb/cockroach/sql/pgwire
github.com/cockroachdb/cockroach/storage/engine/rocksdb
github.com/cockroachdb/cockroach/storage/engine
github.com/cockroachdb/cockroach/storage
github.com/cockroachdb/cockroach/kv
github.com/cockroachdb/cockroach/server/status
github.com/cockroachdb/cockroach/server
github.com/cockroachdb/cockroach/cli
github.com/cockroachdb/cockroach

real	4m43.898s
user	4m51.908s
sys	0m19.818s
+ go test -v -i ./...
github.com/cockroachdb/cockroach/gossip/simulation
github.com/cockroachdb/cockroach/testutils/gossiputil
github.com/cockroachdb/cockroach/security/securitytest
github.com/cockroachdb/cockroach/rpc/codec/message
github.com/cockroachdb/cockroach/testutils/sqlutils
github.com/cockroachdb/cockroach/util/leaktest

real	0m1.121s
user	0m2.073s
sys	0m0.357s
+ go test -v -c -tags acceptance ./acceptance

real	0m2.841s
user	0m4.032s
sys	0m0.356s
+ go build ./gossip/simulation/...

real	0m0.104s
user	0m0.089s
sys	0m0.036s
+ exit 0
+ gopath0=/home/jing/code/go
+ is_shard 2
./build/circle-deps.sh: line 6: CIRCLE_NODE_TOTAL: unbound variable
++ notify
++ is_shard 1
./build/circle-deps.sh: line 6: CIRCLE_NODE_TOTAL: unbound variable
```

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #3913.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3915)

### CODE REVIEW

**Comment by tamird** [comment]
Weren't these already being defaulted somewhere? LGTM otherwise.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3915#-:-K8OdhdMytk6ZYVW0-Wg:1814305475)*

**Comment by petermattis** [comment]
They are defaulted in `build/builder.sh`. But these scripts (`build/{builder,circle-deps,circle-test}.sh`) can all be called directly and all need to default these variables.

**Comment by tamird** [comment]
Agreed, but I think with these changes we can remove the now duplicated defaults in `build/builder.sh`.

**Comment by petermattis** [comment]
Why can we remove the defaults in `build/builder.sh`? I sometimes call that script directly during development.

**Comment by tamird** [comment]
I must be missing something. My understanding is that `build/builder.sh`
only defaults these so that they are defined in `circle-{deps,test}`. Now
that those scripts handle the defaults internally, what value do the
defaults in `build/builder.sh` provide?

**Comment by petermattis** [comment]
If you don't default the values in `build/builder.sh` you'll get an error when running that script. We can default the values to the empty string in `build/builder.sh`, but you're talking about removing 2 characters from that script rather than defaulting the values to `0` and `1` respectively.

**Pull request merged**
