### PR TITLE
Added myself to AUTHORS file.

### PR DESCRIPTION
**Pull request by aaron-crl**

### CODE REVIEW

**Review by vladdy — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42921)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by aaron-crl** [comment]
bors r=vladdy

**Comment by aaron-crl** [comment]
bors retry

**Pull request merged**
