### PR TITLE
kvserver: return more range information after a split

### LINKED ISSUE #51096: roachtest: kv50/rangelookups/split/nodes=8 failed
[(roachtest).kv50/rangelookups/split/nodes=8 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2068260&tab=buildLog) on [master@9304ecd70e9f3ba4cb16b5443a10b4e17d7baee0](https://github.com/cockroachdb/cockroach/commits/9304ecd70e9f3ba4cb16b5443a10b4e17d7baee0):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/kv50/rangelookups/split/nodes=8/run_1
	test_runner.go:804: test timed out (10h0m0s)

```

<details><summary>More</summary><p>

Artifacts: [/kv50/rangelookups/split/nodes=8](https://teamcity.cockroachdb.com/viewLog.html?buildId=2068260&tab=artifacts#/kv50/rangelookups/split/nodes=8)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Akv50%2Frangelookups%2Fsplit%2Fnodes%3D8.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by andreimatei**
This patches makes responses to clients with stale information contain
information about both sides of a split if it looks like there's been a
recent split and the client has pre-split info.
Before this patch, a replica would only return information about its own
descriptor and lease to a stale client. If a client had pre-split info
and it addressed the LHS of the post-split, it would thus get back the
LHS desc. It'd proceed to remove the pre-split desc from its cache
and add the LHS. If it then tries to access the RHS, it'd have to do a
range lookup. This patch makes it so that the post-split LHS returns
both LHS and RHS info if the LHS and RHS are of the same generation
(which is an indication that they resulted from a split). The RHS, if
addressed, similarly returns both LHS and RHS info, although this
currently probably doesn't matter as much since a client with pre-split
info would never address the RHS (it'd address the LHS and get back a
RangeKeyMismatchError).

This patch reduces the number of range lookups done while splits are
happening, as detected by the kv50/rangelookups/split test. That test
started failing after the recent changes to return range info when a
server detects a stale client. Before those changes, there were fewer
range lookups than currently because, in the scenario presented above,
the pre-split descriptor would persist in the client's cache even after
addressing the post-split LHS. When trying to address the RHS, the
client would get a RangeKeyMismatchError (which the test doesn't count).
After those changes, these mismatch errors were turned into range
lookups (which the test does count). Probably a wash, but the test
doesn't see it that way. With this patch, both the mismatches and
lookups and their sum looks better than ever.

Fixes #51096

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice change! Glad the test failure was just an accounting inconsistency and nothing more serious.

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-:-MDp1jR3CEB09gCHPOyv:b-q3ux0f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_send.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp0eP43Gzq0qGYi86v:-MDp0eP43Gzq0qGYi86w:bz4vroq) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/replica_send.go#L133)):*
> ```Go
> 	ctx context.Context, ba *roachpb.BatchRequest, br *roachpb.BatchResponse,
> ) {
> 	if ba.ReturnRangeInfo {
> ```

To confirm, we don't want to do anything in this branch?
___
*[pkg/kv/kvserver/replica_send.go, line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp0ljb56rhZ_wHPqC9:-MDp0ljb56rhZ_wHPqCA:b7yv05m) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/replica_send.go#L186)):*
> ```Go
> 		if rr.Desc().Generation != desc.Generation {
> 			// The next range does not look like it came from a split that produced
> 			// both r and this next range.
> ```

Could you talk a little about the cases where this check has false negatives. For instance, if the RHS of the split has split again.
___
*[pkg/kv/kvserver/replica_send.go, line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp0wuJBBa6RO-znwu8:-MDp0wuJBBa6RO-znwu9:b-d2gzqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/replica_send.go#L191)):*
> ```Go
> 
> 		var nextDesc roachpb.RangeDescriptor
> 		var nextLease roachpb.Lease
> ```

nit: `var rangeInfo roachpb.RangeInfo` would avoid these intermediate variables.
___
*[pkg/kv/kvserver/store.go, line 2009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp1O9v3wkel0njypL6:-MDp1O9v3wkel0njypL7:b-bc7rd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/store.go#L2009)):*
> ```Go
> 			})
> 	} else {
> 		// Note that we can't use DescendRange() because it treats the lower end as exclusive.
> ```

and the high end as inclusive?
___
*[pkg/kv/kvserver/store_test.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDoxr_O-cyiamsfWRWt:-MDoxr_O-cyiamsfWRWu:b-f88cvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c386a55e9d90411031b565ddd21a8f5394c232/pkg/kv/kvserver/store_test.go#L871)):*
> ```Go
> 			name:  "within range",
> 			start: ranges[6].Key.Next(),
> 			end:   ranges[6].Key.Next(),
> ```

Isn't this an empty range? That probably works fine, but technically is invalid. Maybe `Next` this again?
___
*[pkg/kv/kvserver/store_test.go, line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDoy2hh6DkGSj6hj2q8:-MDoy2hh6DkGSj6hj2q9:b51rqi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c386a55e9d90411031b565ddd21a8f5394c232/pkg/kv/kvserver/store_test.go#L877)):*
> ```Go
> 	for _, tc := range tests {
> 		t.Run(tc.name, func(t *testing.T) {
> 			visited := make([]roachpb.RSpan, 0)
> ```

nit: `var visited []roachpb.RSpan` is the "correct" way to do this. I'll never forget that one because it came up on my Go readability review.
___
*[pkg/kv/kvserver/store_test.go, line 893 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDozFGL3_TaNaLTsNgS:-MDozFGL3_TaNaLTsNgT:btmmr4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/store_test.go#L893)):*
> ```Go
> 			// Reverse the expected values.
> 			exp := make([]roachpb.RSpan, len(tc.exp))
> 			copy(exp, tc.exp)
> ```

nit: if you already need to copy, probably easier and cleaner to do the copy and reverse in one pass:
```
for i, sp := range tc.exp {
    exp[len(exp)-i-1] = sp
}
```
___
*[pkg/server/testserver.go, line 1253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp-EIG8Joc8hRRMibe:-MDp-EIG8Joc8hRRMibf:bmwhxo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/server/testserver.go#L1253)):*
> ```Go
> // Calling this multiple times is undefined (but see TestCluster.ScratchRange()
> // which is idempotent).
> func (ts *TestServer) ScratchRange() (roachpb.Key, error) {
> ```

Should this take a `t testing.TB` like `TestCluster.ScratchRange`?
___
*[pkg/testutils/serverutils/test_server_shim.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp1WNiE4i0hCrLxHXR:-MDp1WNiE4i0hCrLxHXS:bxgpy5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/testutils/serverutils/test_server_shim.go#L208)):*
> ```Go
> 	StartTenant(params base.TestTenantArgs) (pgAddr string, _ error)
> 
> 	ScratchRange() (roachpb.Key, error)
> ```

Let's give this a comment.
___
*[pkg/testutils/testcluster/testcluster.go, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp-QjR9GQabENoElk0:-MDp-QjR9GQabENoElk1:bllujx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/testutils/testcluster/testcluster.go#L688)):*
> ```Go
> // is lazily split off on the first call to ScratchRange.
> func (tc *TestCluster) ScratchRange(t testing.TB) roachpb.Key {
> 	scratchKey := keys.TableDataMax
> ```

This seems potentially buggy. We define `scratchKey` in two places. We should only do so in one.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52202)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_send.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp0eP43Gzq0qGYi86v:-MDv5_MR3KwwpVVt80In:bc01468) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/replica_send.go#L133)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To confirm, we don't want to do anything in this branch?
</blockquote></details>

I'd rather not touch it. `ReturnRangeInfo` never had very clear semantics about what the client expects, but returning more data for it can only hurt.
___
*[pkg/kv/kvserver/replica_send.go, line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp0ljb56rhZ_wHPqC9:-MDv6h5pAP9EmbxOGQqL:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/replica_send.go#L186)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you talk a little about the cases where this check has false negatives. For instance, if the RHS of the split has split again.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_send.go, line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp0wuJBBa6RO-znwu8:-MDv7-IHC6lIWygusNXB:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/replica_send.go#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `var rangeInfo roachpb.RangeInfo` would avoid these intermediate variables.
</blockquote></details>

done
___
*[pkg/kv/kvserver/store.go, line 2009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp1O9v3wkel0njypL6:-MDv7INK-oxS3P50ny3L:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/store.go#L2009)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

and the high end as inclusive?
</blockquote></details>

done
___
*[pkg/kv/kvserver/store_test.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDoxr_O-cyiamsfWRWt:-MDv9eSl7iQQ_RQsIycA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c386a55e9d90411031b565ddd21a8f5394c232/pkg/kv/kvserver/store_test.go#L871)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Isn't this an empty range? That probably works fine, but technically is invalid. Maybe `Next` this again?
</blockquote></details>

done
___
*[pkg/kv/kvserver/store_test.go, line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDoy2hh6DkGSj6hj2q8:-MDvAQjKEgKwVhbVgMUU:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c386a55e9d90411031b565ddd21a8f5394c232/pkg/kv/kvserver/store_test.go#L877)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `var visited []roachpb.RSpan` is the "correct" way to do this. I'll never forget that one because it came up on my Go readability review.
</blockquote></details>

done
___
*[pkg/kv/kvserver/store_test.go, line 893 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDozFGL3_TaNaLTsNgS:-MDv7mV9A3__zyrVOClP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/store_test.go#L893)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: if you already need to copy, probably easier and cleaner to do the copy and reverse in one pass:
```
for i, sp := range tc.exp {
    exp[len(exp)-i-1] = sp
}
```
</blockquote></details>

done
___
*[pkg/server/testserver.go, line 1253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp-EIG8Joc8hRRMibe:-MDv7rMn8L7syl5dOV8s:bm4hch2) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/server/testserver.go#L1253)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this take a `t testing.TB` like `TestCluster.ScratchRange`?
</blockquote></details>

`TestServer` methods generally return errors, so I've kept it like that.
___
*[pkg/testutils/serverutils/test_server_shim.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp1WNiE4i0hCrLxHXR:-MDv86fs7iR6GfkUPSg1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/testutils/serverutils/test_server_shim.go#L208)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's give this a comment.
</blockquote></details>

done
___
*[pkg/testutils/testcluster/testcluster.go, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp-QjR9GQabENoElk0:-MDv9LEdDc86Lvf6e-zx:b-2x4j6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/testutils/testcluster/testcluster.go#L688)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems potentially buggy. We define `scratchKey` in two places. We should only do so in one.
</blockquote></details>

see now

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-:-ME0KlnB9EMoGKnc8YZQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_send.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp0eP43Gzq0qGYi86v:-ME0K7iV72YGmwYGq1RE:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/kv/kvserver/replica_send.go#L133)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd rather not touch it. `ReturnRangeInfo` never had very clear semantics about what the client expects, but returning more data for it can only hurt.
</blockquote></details>

Ack.
___
*[pkg/testutils/testcluster/testcluster.go, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp-QjR9GQabENoElk0:-ME0K_gN1D9LKOjuAdTC:b4mpuiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/testutils/testcluster/testcluster.go#L688)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

see now
</blockquote></details>

Should we be setting this `scratchRangeKey` field somewhere? Am I missing that?

**Review by andreimatei — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-:-ME3LMrTDtHNu7QOS3po:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/testutils/testcluster/testcluster.go, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-MDp-QjR9GQabENoElk0:-ME3KMOW9t-ZsWbwUq67:bnlp3lh) ([raw file](https://github.com/cockroachdb/cockroach/blob/79564db568fcd8317f55fd4b237b3ba0a7a4b763/pkg/testutils/testcluster/testcluster.go#L688)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we be setting this `scratchRangeKey` field somewhere? Am I missing that?
</blockquote></details>

yes :) done

**Review by andreimatei — COMMENTED** [review]
had to prepend a small commit; PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-:-MEyYAIWD0hQeOQqzeti:b-ps1p40)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52202#-:-MF1lH2FBHN2HXv-4eo0:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Pull request merged**
