### PR TITLE
storage: remove MVCCIterator.Key method

### PR DESCRIPTION
**Pull request by jbowens**
The MVCCIterator interface previously exposed two methods for accessing the current iterator postion as a MVCC key—UnsafeKey and Key. Key() was equivalent to UnsafeKey().Clone().

This commit removes the Key() variant, pushing the onus of key copying onto the caller. This reduces the interface surface area, avoids accidental key copying (some of which is addressed within this commit), and does not impose any unreasonable burden on callers.

Epic: None
Informs #82589.
Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
LGTM, only skimmed the non-test changes.

**Review by stevendanna — APPROVED** [review]

**Review by sumeerbhola — APPROVED** [review]
Happy to see this change.

All the changes here look fine, but just curious whether all tests are still using `unsafeMVCCIterator` (or some equivalent) that will mangle the unsafe key?

:lgtm: 

> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98542#-:-NQWNdhKAAWgEt97fNiF:bl3qzvw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rhu713)

**Review by jbowens — COMMENTED** [review]
> All the changes here look fine, but just curious whether all tests are still using unsafeMVCCIterator (or some equivalent) that will mangle the unsafe key?

Yeah, it now happens through the `storage/pebbleiter.Iterator` type which performs the mangling right above the `*pebble.Iterator`. It may also be worthwhile to perform analogous mangling directly above the top iterator returned from the storage package.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98542#-:-NQWYnQf3zcbSDJgxFAj:bh8ow84)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rhu713)

**Comment by jbowens** [comment]
Failed in UI tests:

```
[15:54:28][Step 3/4] The build Tests::UI Test #47064 {buildId=9064827} has been running for more than 25 minutes. Terminating... 
[15:54:28][Step 3/4] Execution timeout
[15:54:28][Step 3/4] Stopping build on agent. Reason: build execution timeout
[15:54:28][Step 3/4] Dumping threads before termination:
[15:54:28][Step 3/4] PID: 4770, PPID: 1298, Command line: bash /home/agent/temp/agentTmp/custom_script10664969836098975994
[15:54:28][Step 3/4] No thread dump is available: Cannot detect running java processes: jps tool not found
[15:54:28][Step 3/4] 
[15:54:28][Step 3/4] PID: 4771, PPID: 4770, Command line: bash ./build/teamcity/cockroach/ci/tests/ui_test.sh
[15:54:28][Step 3/4] No thread dump is available: Cannot detect running java processes: jps tool not found
[15:54:28][Step 3/4] 
[15:54:28][Step 3/4] PID: 4785, PPID: 4771, Command line: docker run -i --rm --init -u 1003:1004 --workdir=/go/src/github.com/cockroachdb/cockroach --volume /home/agent/system/git:/home/agent/system/git:ro --volume /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts:/artifacts --volume /home/agent/work/.go/src/github.com/cockroachdb/cockroach:/go/src/github.com/cockroachdb/cockroach --volume /home/agent/.bzlhome:/home/roach cockroachdb/bazel:20230303-060247 build/teamcity/cockroach/ci/tests/ui_test_impl.sh
[15:54:28][Step 3/4] No thread dump is available: Cannot detect running java processes: jps tool not found
[15:54:28][Step 3/4] 
[15:54:28][Run UI tests] Terminated
[15:54:28][Run UI tests] Process exited with code 143
```

bors r+

**Pull request merged**
