### PR TITLE
sql: copy scanNode.spans for local flows of distributed plans

### LINKED ISSUE #110712: roachtest: incorrect result of retried-as-local query
roachtest.c2c/shutdown/dest/coordinator [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11786676?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11786676?buildTab=artifacts#/c2c/shutdown/dest/coordinator) on master @ [556be3437fdba9f3d86126b3896ee68b9903b79e](https://github.com/cockroachdb/cockroach/commits/556be3437fdba9f3d86126b3896ee68b9903b79e):

```
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:683
	            				github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:674
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:916
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1449
	            				main/pkg/cmd/roachtest/monitor.go:119
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				src/runtime/asm_amd64.s:1598
	Error:      	Received unexpected error:
	            	sql: no rows in result set
	Test:       	c2c/shutdown/dest/coordinator
(require.go:1360).NoError: FailNow called
(cluster_to_cluster.go:1488).func1: shutdown execution failed: monitor failure: context canceled while waiting for job to finish: context canceled
test artifacts and logs in: /artifacts/c2c/shutdown/dest/coordinator/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-11786676/c2c-shutdown-dest-coordinator/1694773443070/1694774294187)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/shutdown/dest/coordinator.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31572

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes it so that we perform a copy of `scanNode.spans` slice
when putting it into `TableReaderSpec` for local flows of distributed
plans. This prevents corruption of the logical plans (namely,
modification of `scanNode.spans`) that later could lead to incorrect
results in case the distributed query results in an error and is then
retried-as-local.

This corruption could occur because the following memory aliasing chain
is possible:
- `tableReaderPlanningInfo.spans` is set to `scanNode.spans` in
`DistSQLPlanner.createTableReaders`
- `SpanPartition.Spans` is set to `tableReaderPlanningInfo.spans`
directly in some cases in `DistSQLPlanner.planTableReaders`
- `TableReaderSpec.Spans` is set to `SpanPartition.Spans`
- `colBatchScanBase.SpansWithCopy.Spans` is set to
`TableReaderSpec.Spans`
- those spans are then passed as an argument to `cFetcher.StartScan`
which is then passed to `KVFetcher.SetupNextFetcher` and then to
`txnKVFetcher.SetupNextFetch`.

The contract of `SetupNextFetch` is such that the fetcher takes
ownership of the spans slice and can modify it as it pleases (it reuses
the slice for resume spans that are encountered during the fetch; this
has been the case for about two years and was done as a performance
optimization that we don't want to lose). (Note that the keys themselves
aren't mutated (which KV layer wouldn't approve of) - only
`[]roachpb.Span` slice can be changed.)

However, this modification of the spans can propagate all the way up to
the logical plan in some cases which (as of introducing the
retry-as-local mechanism) can lead to real problems. This commit
detects the scenario when this corruption would matter and allocates a
fresh slice for `TableReaderSpec.Spans`. In particular, this is done when
- the plan might be distributed (if it's local, the corruption will
still occur, but we don't care about that)
- the `SpanPartition` is assigned to the local node (for remote nodes
the spec will be serialized, thus, aliasing is not possible).

Note that we might copy the slice in more cases than strictly necessary,
but we choose to be a bit conservative here since this allocation
shouldn't matter that much for distributed queries in the grand scheme
of things.

(The bug is only present on master, so there is no release note.)

Fixes: #110712.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111686)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/distsql_physical_planner.go` line 1907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111686#-NfrkAaJ33KcZ-MZ9mln:-NfrkAaJ33KcZ-MZ9mlo:b-k3tbo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0545c616f9ddd5cf25ae66fd43111e89acb266/pkg/sql/distsql_physical_planner.go#L1907)):*
> ```Go
> 		//      doesn't matter if the remote node modifies them - it'll have its
> 		//      own copy).
> 		if !planCtx.isLocal && sp.SQLInstanceID == dsp.gatewaySQLInstanceID {
> ```

Currently, I introduced the copy only when strictly needed, but the conditionals here seem a bit complex (dealing with unsafe pointers), so I'm wondering whether we'd be ok with performing a copy in more cases. Perhaps this pointer business is unnecessary? We have a distributed query after all, and generally speaking we don't have many `roachpb.Span`s to scan (i.e. it's not the lookup / index join codepath).

It does seem nice to keep the two conditionals from above, but it also means that in the local plan case we will continue having possible logical plan corruption (but it doesn't propagate further into the memo, etc).

**Comment by yuzefovich** [comment]
Also, for context, I initially prototyped a different approach in #111628 that would adjust `KVBatchFetcher.SetupNextFetch` interface to indicate whether the spans modification is allowed or not (it wouldn't be allowed in the regular scan case, but it'd be ok for lookup and index joins), but that approach is more involved and has complications with the memory accounting, so I like this more-targeted PR more.

**Review by michae2 — APPROVED** [review]
:lgtm: This is a work of art.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111686#-:-NftKRrz4HFB6ajO-tfR:bvyg8iv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/distsql_physical_planner.go` line 1907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111686#-NfrkAaJ33KcZ-MZ9mln:-NftMhtjAVHHIup9f8ne:b-usl6vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0545c616f9ddd5cf25ae66fd43111e89acb266/pkg/sql/distsql_physical_planner.go#L1907)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Currently, I introduced the copy only when strictly needed, but the conditionals here seem a bit complex (dealing with unsafe pointers), so I'm wondering whether we'd be ok with performing a copy in more cases. Perhaps this pointer business is unnecessary? We have a distributed query after all, and generally speaking we don't have many `roachpb.Span`s to scan (i.e. it's not the lookup / index join codepath).

It does seem nice to keep the two conditionals from above, but it also means that in the local plan case we will continue having possible logical plan corruption (but it doesn't propagate further into the memo, etc).
</blockquote></details>

I love that you went to the trouble of copying only when strictly needed, but personally in this case I would lean toward always copying to avoid leaving a trap for someone in the future trying to use the plan after executing. Leaving out the unsafe pointer comparison is a good compromise, at least then someone trying to figure this out will always be able to reproduce it with local execution.

I do wish Go had `const`.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111686#-:-NfvVoJk9AuUccIRTG5G:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/distsql_physical_planner.go` line 1907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111686#-NfrkAaJ33KcZ-MZ9mln:-NfvUeT56-FhbSUQL-j6:b-x3rm2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0545c616f9ddd5cf25ae66fd43111e89acb266/pkg/sql/distsql_physical_planner.go#L1907)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I love that you went to the trouble of copying only when strictly needed, but personally in this case I would lean toward always copying to avoid leaving a trap for someone in the future trying to use the plan after executing. Leaving out the unsafe pointer comparison is a good compromise, at least then someone trying to figure this out will always be able to reproduce it with local execution.

I do wish Go had `const`.
</blockquote></details>

I checked the impact of the unconditional copying here, and it did show up in microbenchmarks:
```
name                     old time/op    new time/op    delta
ColBatchScan/rows=16-24     124µs ± 3%     126µs ± 4%  +2.07%  (p=0.028 n=9+10)

name                     old speed      new speed      delta
ColBatchScan/rows=16-24  2.07MB/s ± 2%  2.03MB/s ± 4%  -1.97%  (p=0.023 n=9+10)

name                     old alloc/op   new alloc/op   delta
ColBatchScan/rows=16-24    10.1kB ±25%    10.2kB ±27%    ~     (p=0.631 n=10+10)

name                     old allocs/op  new allocs/op  delta
ColBatchScan/rows=16-24       133 ±18%       135 ±17%    ~     (p=0.658 n=9+9)
```
so I removed the pointer business but chose to keep checks for query possibly being distributed and span partition being assigned to the gateway.

**Pull request merged**
