### PR TITLE
sql: stub ALTER TABLE ... SET LOCALITY/AFFINITY related commands

### PR DESCRIPTION
**Pull request by otan**
Following the doc on proposed ideas and fleshed them all out. They
default to displaying REGIONAL AFFINITY for now.

Release note (sql change): Implemented ALTER TABLE ... SET
LOCALITY/REGIONAL AFFINITY commands that allow users to configure
multiregion properties of given tables. These may change later.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55827#-MKGcjLO16UbC7q5090J:-MKGcjLO16UbC7q5090K:b-386w5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/da80e8bf3aa8bf126417e9f1b645c251a9720e00/pkg/sql/logictest/testdata/logic_test/multiregion#L22)):*
> ```
> 
> statement error implementation pending
> ALTER TABLE a SET REGIONAL AFFINITY TO NONE
> ```

Minor - Why only one test here?  You thinking we'll fully populate when the syntax is hardened?

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55827#-MKGcjLO16UbC7q5090J:-MKGjnMg7Rzc666N3AzO:b7vnhlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/da80e8bf3aa8bf126417e9f1b645c251a9720e00/pkg/sql/logictest/testdata/logic_test/multiregion#L22)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Minor - Why only one test here?  You thinking we'll fully populate when the syntax is hardened?
</blockquote></details>

Yep, that and when we actually have something to unit test. This just checks this links end to end at the moment!

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
