### PR TITLE
distsql: fix metadata propagation in sorter

### LINKED ISSUE #22927: test failure: panic while executing SQL Logic Test nightly
Found in: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&buildTypeId=Cockroach_SqlLogicTests&buildId=530925&_focus=8377

```
--- progress: /go/src/github.com/cockroachdb/sqllogictest/test/index/orderby_nosort/100/slt_good_5.test: 731 statements/queries
E180222 07:41:00.836330 6215 sql/conn_executor.go:496  [n1,client=127.0.0.1:60288,user=root] a SQL panic has occurred while executing "SELECT pk, col0 FROM tab1 WHERE (((col0 > 86) AND (col3 <= 2)) OR ((col0 > 0) AND (col1 > 86.38))) ORDER BY 2 DESC, 1": flow: unexpected 10240 leftover bytes
E180222 07:41:00.836534 6215 util/log/crash_reporting.go:181  [n1,client=127.0.0.1:60288,user=root] a panic has occurred!
E180222 07:41:00.837821 6215 util/log/crash_reporting.go:445  [n1,client=127.0.0.1:60288,user=root] Reported as error 11532ed0c9604c1e9f21a0d3970866c8
panic: flow: unexpected 10240 leftover bytes [recovered]
	panic: panic while executing 1 statements: SELECT _, _ FROM _ WHERE (((_ > _) AND (_ <= _)) OR ((_ > _) AND (_ > _))) ORDER BY _ DESC, _; caused by flow: unexpected 10240 leftover bytes

goroutine 6215 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc422c1b000, 0x219b6c0, 0xc42468ee40, 0x1c30d80, 0xc434384fe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:510 +0x365
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc422c1b000, 0x219b6c0, 0xc42468ee40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:471 +0x61
panic(0x1c30d80, 0xc434384fe0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
```

### LINKED ISSUE #23001: sql: DistSQL failing nightly logic tests
https://teamcity.cockroachdb.com/viewLog.html?tab=buildChangesDiv&buildId=532473&buildTypeId=Cockroach_SqlLogicTests

Lots of failures, like:

```
logic.go:2112: 
	/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby/10/slt_good_2.test:9194: SELECT pk, col0 FROM tab1 WHERE (col0 >= 728) AND col1 < 561.85 ORDER BY 2 DESC,1
	expected:
	    3
	    4
	    840
	    890
	    
	but found (query options: "valuesort" -> ignore the following ordering of rows) :
	
logic.go:2144: 
	/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby/10/slt_good_2.test:9202: error while processing
logic.go:2145: /go/src/github.com/cockroachdb/sqllogictest/test/index/orderby/10/slt_good_2.test:9202: too many errors encountered, skipping the rest of the input
```

This seems pretty messed up. There's also a few scattered panics from 10240 leftover bytes kind of things.

It's easy to reproduce locally. Run `make testlogic` and cancel once the tests start to build the `logictest.test` binary, then `cd pkg/sql/logictest`, and run:

```
./logictest.test -test.run "Test(CCL)?Logic/distsql/14.test" -bigtest -show-sql -test.v -config distsql
E180223 14:40:44.937062 163452 sql/logictest/logic.go:2139  /Users/jordan/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby_nosort/10/slt_good_14.test:2681: too many errors encountered, skipping the rest of the input
--- total: 10032 tests, 0 failures
test logs left over in: /var/folders/wv/sn0dwhv94gz4mss7jhypx2f00000gn/T/logTestLogic267709055
--- FAIL: TestLogic (24.66s)
        test_log_scope.go:81: test logs captured to: /var/folders/wv/sn0dwhv94gz4mss7jhypx2f00000gn/T/logTestLogic267709055
        test_log_scope.go:62: use -show-logs to present logs inline
    --- FAIL: TestLogic/distsql (24.65s)
        --- PASS: TestLogic/distsql/slt_good_14.test (20.12s)
        --- FAIL: TestLogic/distsql/slt_good_14.test#01 (1.70s)
                logic.go:2112:
                        /Users/jordan/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby/10/slt_good_14.test:1134: SELECT pk, col0 FROM tab1 WHERE ((col0 > 494)) AND col3 < 718 ORDER BY 2 DESC,1
                        expected:
                            0
                            5
                            505
                            644
                            8
                            9
                            946
                            982

                        but found (query options: "valuesort" -> ignore the following ordering of rows) :

                logic.go:2144:
                        /Users/jordan/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby/10/slt_good_14.test:1146: error while processing
                logic.go:2145: /Users/jordan/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby/10/slt_good_14.test:1146: too many errors encountered, skipping the rest of the input
        --- FAIL: TestLogic/distsql/slt_good_14.test#02 (2.82s)
                logic.go:2112:
                        /Users/jordan/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby_nosort/10/slt_good_14.test:2675: SELECT pk, col0 FROM tab1 WHERE col1 = 27.90 AND col1 > 45.24 AND col0 <= 58 AND col0 < 25 AND col1 >= 13.21 OR (col0 = 32) OR (((col3 >= 18)) OR (col1 IN (72.63,82.51,16.30,42.3,29.25,31.91)) AND col0 >= 57 OR col4 > 4.80) AND col0 <= 20 ORDER BY 2 DESC,1
                        expected:
                            4
                            0

                        but found (query options: "nosort") :

                logic.go:2144:
                        /Users/jordan/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby_nosort/10/slt_good_14.test:2681: error while processing
                logic.go:2145: /Users/jordan/go/src/github.com/cockroachdb/sqllogictest/test/index/orderby_nosort/10/slt_good_14.test:2681: too many errors encountered, skipping the rest of the input
FAIL
```

These are definitely correctness issues as we don't fail these in local SQL.

### PR DESCRIPTION
**Pull request by rjnn**
Fixes #23001 and fixes #22927.

I am running the entire logic test locally to verify that there are no failures or panics. I will wait for it to complete before merging. I have verified that the individual failures reported in the above issues are indeed fixed by this patch.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23322#-:-L6cTFS4CrFMiOI6OyZo:bnfp4nl)*

**Comment by jordanlewis** [comment]
LGTM, but what was the bug? It's generally good practice to briefly explain what actually got fixed in a patch like this. Also, I'm curious!

**Comment by arjunravinarayan** [comment]
Metadata was not being properly propagated in `sortChunksProcessor`. `sortChunksProcessor.fill()` would terminate filling upon receiving the first metadata row, which would result in incorrect results. Fill was changed to append metadata to the metadata buffer in the processor, like the other `sorter` processors.

This lack of proper metadata propagation would also result in the processor not being properly terminated at the end of the test.

**Comment by arjunravinarayan** [comment]
The SQL bigtest shows no appetite for stopping anytime soon so I'll merge this now. We've fixed the identified bugs. The nightlies will catch anything that was missed.

**Comment by jordanlewis** [comment]
Sorry for not catching this during the review, but this needs a regression test in our logic test suite.

**Pull request merged**
