### PR TITLE
testutils: automate maintenance of predecessor release information

### PR DESCRIPTION
**Pull request by renatolabs**
Up to this point, we have manually maintained a `predecessor_version.json`
file that maps each release series to the latest published
release of the predecessor series. This information is then used
by tests in mixed-version and upgrade contexts.

With the end goal of testing upgrades that do not use the latest
published version, this commit enriches the release information file
to also include which releases have been _withdrawn_. With that
information, the test harness can choose any patch release of the
predecessor release series excluding withdrawn releases, which could
lead to undesired flakes and noise.

In summary, the following changes are made:

* replacement of `predecessor_version.json` file for
`cockroach_releases.yaml`. The new file includes which releases have
been withdrawn.
* automation of the process of keeping `cockroach_releases.yaml`
up to date. The docs team already maintains all this information in a
structured format [1], so we leverage that here.
* Predecessor logic is moved from `pkg/util` to `pkg/testutils`, where
it makes more sense, since that code is only used in tests.
* Introduction of `RandomPredecessor` and `RandomPredecessorHistory`,
which make use of the new data file to pick a random non-withdrawn
predecessor instead of the latest one.

The first commit in this PR introduces these changes, while the second and
third make use of the new functionality in the `tpcc/mixed-headroom` roachtests
and the `mixedversion` framework, respectively.

[1] https://github.com/cockroachdb/docs/blob/main/src/current/_data/releases.yml

Epic: CRDB-19321

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Ready for review now. I have mixed-versions roachtests running in https://teamcity.cockroachdb.com/viewLog.html?buildId=10619835&tab=queuedBuildOverviewTab.

**Comment by renatolabs** [comment]
`schemachange/mixed-version` failed in the build above 👆:

```"message": "***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: at or near \"not\": syntax error: unimplemented: this syntax (SQLSTATE 0A000)"```

Not sure if this is a schemachange issue or `randgen` generating an invalid statement. @fqazi FYI.

Either way, doesn't seem related to the changes introduced here.

**Review by srosenberg — COMMENTED** [review]
> Reviewed 22 of 44 files at r1, 12 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105231)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/release/update_releases.go` line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105231#-NZkoxz605xbcH_mLwbr:-NZkoxz7EQfTfZK0iA63:bklwzo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/93da43a6b3a7de2cb3381c90bef614342837a227/pkg/cmd/release/update_releases.go#L31)):*
> ```Go
> 
> var updateReleasesTestFileCmd = &cobra.Command{
> 	Use:   "update-releases-file",
> ```

This is intended to be run manually, right?
___
*[`pkg/cmd/release/update_releases.go` line 200 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105231#-NZkqRGE0qTfDNJeyi7u:-NZkqRGE0qTfDNJeyi7v:bbvt9wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/93da43a6b3a7de2cb3381c90bef614342837a227/pkg/cmd/release/update_releases.go#L200)):*
> ```Go
> 		if d.Predecessor == "" {
> 			if noPredecessors != "" {
> 				return fmt.Errorf("two release series without known predecessors: %q and %q", name, noPredecessors)
> ```

Is "release series" the right terminology? It's just unfamiliar to me.

**Review by srosenberg — APPROVED** [review]
Nice work! I am especially excited about the application of `RandomPredecessor` :)

:lgtm:

> Reviewed 3 of 44 files at r1, 1 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105231#-:-NZliZXm8nGRbcke5idB:b94ib7m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/testutils/release/releases.go` line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105231#-NZlhyCU6Bf_iSV97Egs:-NZlhyCU6Bf_iSV97Egt:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/93da43a6b3a7de2cb3381c90bef614342837a227/pkg/testutils/release/releases.go#L95)):*
> ```Go
> // instead of returning a list of the latest patch releases, it will
> // return a random non-withdrawn patch release for each release series.
> func RandomPredecessorHistory(rng *rand.Rand, v *version.Version, k int) ([]string, error) {
> ```

Nice!

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105231)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/release/update_releases.go` line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105231#-NZkoxz605xbcH_mLwbr:-N_56PXW4ubKk30W8m5T:b-onkjb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/93da43a6b3a7de2cb3381c90bef614342837a227/pkg/cmd/release/update_releases.go#L31)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

This is intended to be run manually, right?
</blockquote></details>

For now, yes. There's some ongoing work to automate this and run these commands automatically on a TC build, but we're not there yet.
___
*[`pkg/cmd/release/update_releases.go` line 200 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105231#-NZkqRGE0qTfDNJeyi7u:-N_56YUxDirDoBz1vpkk:b-chr1bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/93da43a6b3a7de2cb3381c90bef614342837a227/pkg/cmd/release/update_releases.go#L200)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Is "release series" the right terminology? It's just unfamiliar to me.
</blockquote></details>

To the best of my knowledge, this is the terminology used by the release team.

**Comment by renatolabs** [comment]
bors r=srosenberg

TFTR!

**Pull request merged**
