### PR TITLE
backupccl: separate EncryptionOptions proto used by job and KV request

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, we used a single `FileEncryptionOptions` proto through the
BACKUP/RESTORE planning, processors and KV requests. This was fine when
we only supported `passphrase` encryption. With support being added for
KMS encryption, value was seen in separating the proto used to resolve
and store information in the planning phase, and that used by the KV
layer requests.  While the former will be responsible for resolving the
kind of encryption and populating the relevant information, the KV
request should remain oblivious to this and simply use the key it is
provided.

This change adds a `BackupEncryptionOptions` proto which is wire
compatible with the `FileEncryptionOptions`. The BACKUP/RESTORE planning
and job stages will use this new proto. Prior to setting up the BACKUP/
RESTORE processor specs we switch to using the `FileEncryptionOptions`
as all the relevant information is available by then.

Release note: None

### CODE REVIEW

**Review by dt — APPROVED** [review]
I'm a strong :thumbsup: on this appraoch, but want to make sure Yevgeniy is on board too.

> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52145#-:-MDVhZqn21wtC5efeq3R:bbbvgf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/roachpb/api.proto, line 1384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52145#-MDVga4VA8qWqLTxC5vk:-MDVga4VA8qWqLTxC5vl:b-kmram1) ([raw file](https://github.com/cockroachdb/cockroach/blob/774792cab21e2ef82d41df9015dc7f57be8e25e6/pkg/roachpb/api.proto#L1384)):*
> ```protobuf
> // planning stage, and by the BACKUP/RESTORE job to encrypt or decrypt BACKUP
> // data and manifest files.
> message BackupEncryptionOptions {
> ```

I don't think this needs to be in roachpb does it? or would backupcc -> jobspb be a problem?

**Review by miretskiy — APPROVED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52145)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52145)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/roachpb/api.proto, line 1384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52145#-MDVga4VA8qWqLTxC5vk:-MDVqRtTCsRjEQKqjAeA:bpn3z29) ([raw file](https://github.com/cockroachdb/cockroach/blob/774792cab21e2ef82d41df9015dc7f57be8e25e6/pkg/roachpb/api.proto#L1384)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think this needs to be in roachpb does it? or would backupcc -> jobspb be a problem?
</blockquote></details>

wasn't a problem, done.

**Review by dt — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52145#-:-MDVqpmh7N5a2EnozUp2:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by adityamaru** [comment]
TFTRs!

bors r+

**Pull request merged**
