### PR TITLE
sql: don't show sql.go in reviewable diffs

### PR DESCRIPTION
**Pull request by RaduBerinde**
Reviewable won't show autogenerated files in diffs, and one way it figures that
out is to look for a `GENERATED FILE DO NOT EDIT` comment (see
https://github.com/Reviewable/Reviewable/wiki/FAQ#how-do-i-tell-reviewable-that-a-file-is-generated-and-should-not-be-reviewed).

Adding it to sql.go.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6771)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql.go, line 0 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-KI3pWmEmVOeX1Ve_Vvk:-KI3pWmEmVOeX1Ve_Vvl:1662033242) ([raw file](https://github.com/cockroachdb/cockroach/blob/79c5dbd1467f97be63cae93054cee2317adc8021/sql/parser/sql.go#L0)):*
Test passed. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771)*

**Comment by dt** [comment]
:lgtm:

might also make sense to mark it binary in gitattributes, which prevents attempting to merge edits to it (which should never be done).

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> #### sql: don&#39;t show sql\.go in reviewable diffs
> 
> Reviewable won't show autogenerated files in diffs, and one way it figures that
> 
> out is to look for a `GENERATED FILE DO NOT EDIT` comment (see
> 
> https://github.com/Reviewable/Reviewable/wiki/FAQ#how-do-i-tell-reviewable-that-a-file-is-generated-and-should-not-be-reviewed).
> 
> 
> 
> Adding it to sql.go.
> 
> 
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-:-KI3q1QepW9NrVnKl0sE:-2019973086)*

**Comment by bdarnell** [comment]
Unfortunately it looks like github and reviewable don't agree on this point. The previous comment `// Code generated by go yacc.` was recognized by github; it doesn't recognize the new shouty comment.

**Comment by petermattis** [comment]
I'd file a bug with reviewable. I'm pretty sure other code generated tools use the `Code generated by` prefix. For example, `stringer`.

**Comment by dt** [comment]
Here's how github does it:
https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L256

<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'd file a bug with reviewable. I'm pretty sure other code generated tools use the `Code generated by` prefix. For example, `stringer`. 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-:-KI3qwh8xJyhFEkWaVxc:1711935498)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/sql_union.sh, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-KI3r63O1GdYmSyW25Cv:-KI3r63O1GdYmSyW25Cw:-1020176333) ([raw file](https://github.com/cockroachdb/cockroach/blob/79c5dbd1467f97be63cae93054cee2317adc8021/sql/parser/sql_union.sh#L51)):*
> ```Shell
> 
>     # Add a comment to the top of the autogenerated sql.go file.
>     echo -e '// GENERATED FILE DO NOT EDIT\n// Generated by go yacc.' | \
> ```

if you made this all one line, I think github would agree, since their code just does `include?`:
`lines[0].include?("Code generated by")`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771)*

**Comment by RaduBerinde** [comment]
I left the original comment and put the new one underneath. It doesn't sound like reviewable cares on which line it is.

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Here's how github does it:
> https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L256
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-:-KI3qS7qVMzfXIH5xgUh:1621443551)*

**Comment by RaduBerinde** [comment]
@dt looks like it's already marked binary in .gitattributes.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I left the original comment and put the new one underneath. It doesn't sound like reviewable cares on which line it is.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-:-KI3rw9Yk3NHoPxl9iaa:-309766132)*

**Comment by tamird** [comment]
Awesome! How do you feel about adding a similar treatment to embedded.go? That file routinely ruins my life.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> @dt looks like it's already marked binary in .gitattributes.
</details>


---

Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-:-KI3veMm8pqQgpN_n1eH:-1543296372)*

**Comment by RaduBerinde** [comment]
@tamird It should be as easy as the diff below but I can't build it locally.. (it seems to want darwin not linux).. Can you try it?

```
--- a/ui/Makefile
+++ b/ui/Makefile
@@ -135,12 +135,16 @@ $(GOBINDATA_TARGET): $(GOBINDATA_DEPS) bower.installed release/$(INDEX)
 	$(GO_BINDATA) -nometadata -pkg ui -o $@ $(GOBINDATA_DEPS) $(INDEX) $(GOBINDATA_SOURCES)
 	gofmt -s -w $@
 	goimports -w $@
+	# Add comment recognized by reviewable.
+	echo '// GENERATED FILE DO NOT EDIT' >> $@
 
 $(GOBINDATA_DEBUG_TARGET): $(GOBINDATA_DEBUG_DEPS) bower.installed debug/$(INDEX)
 	rm -f $(INDEX)
 	cp debug/$(INDEX) $(INDEX)
 	chmod a-w $(INDEX)
 	$(GO_BINDATA) -nometadata -pkg ui -o $@ -debug $(GOBINDATA_DEBUG_DEPS) $(INDEX) $(GOBINDATA_DEBUG_SOURCES)
+	# Add comment recognized by reviewable.
+	echo '// GENERATED FILE DO NOT EDIT' >> $@
```

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Awesome! How do you feel about adding a similar treatment to embedded.go? That file routinely ruins my life.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6771#-:-KI4-M_957RSOew1K8jU:480396732)*

**Comment by RaduBerinde** [comment]
Ok to merge? We can deal with embedded.go in a separate PR

**Comment by tamird** [comment]
sgtm

**Pull request merged**
