### PR TITLE
[DNM] partitionccl: modifity TestRepartitioning in a way that repros #40213

### PR DESCRIPTION
**Pull request by ajwerner**
I changed the partitioning tests to involve more nodes and very rapidly started hitting `setting non-zero HardState.Commit on uninitialized replica` issues. At first I thought it must have been my code not deleting the hard state but I added more logic to read the HardState from the replica immediately after I thought it had been deleted and it was gone. I also added logic to print the batch which should delete it and there was a range deletion for that range. 

@ajkr maybe you'll find this helpful. It reproduces in ~10 minutes under stress on a gceworker.

### CODE REVIEW

**Comment by petermattis** [comment]
Thanks, @ajwerner. I'm taking a look at this and seeing if this repro is helpful.

**Comment by petermattis** [comment]
Running `roachprod-stress` I saw:

```
F190918 13:42:21.625960 8273 storage/replica_raft.go:841  [n7,s7,r119/7:/Table/78/1/{4-5}] unable to acquire merge lock: non-deterministic failure: unable to acquire merge lock: RHS of merge r119:/Table/78/{1/4-2} [(n8,s8):5, (n5,s5):2, (n2,s2):4, next=6, gen=110] <- r120:/Table/78/{1/5-2} [(n2,s2):6, (n5,s5):7, (n8,s8):8, next=9, gen=109] not present on store; found r120:/{Table/78/1/5-Max} [(n7,s7):1, (n5,s5):2, (n3,s3):3, next=4, gen=93] in place of the RHS
```

Is that expected? Should I be running this PR on top of your replica lifetime PR?

**Comment by ajwerner** [comment]
> Is that expected?

It's not unexpected.

> Should I be running this PR on top of your replica lifetime PR?

You can though I saw it on master. I'll put up a branch that has both.

**Comment by petermattis** [comment]
Just saw `F190918 13:50:06.386673 621469 storage/replica_raft.go:1511  [n5,s5,r79/4:/Table/68/1/5{-/6}] snapshot widens existing replica, but no replica exists for subsumed key /Table/68/1/5/6` which I think is also fixed by your PR.

**Comment by ajwerner** [comment]
See https://github.com/ajwerner/cockroach/tree/ajwerner/repro-40213


To make roachprod stress work with the second commit I needed to add the following to roachprod stress so it didn't use all of the root partition:

```
diff --git a/pkg/cmd/roachprod-stress/main.go b/pkg/cmd/roachprod-stress/main.go
index 4520e82d39..093ffa5aaa 100644
--- a/pkg/cmd/roachprod-stress/main.go
+++ b/pkg/cmd/roachprod-stress/main.go
@@ -95,6 +95,11 @@ func run() error {
                return fmt.Errorf("%v\n%s", err, out)
        }
        nodes := strings.Count(string(out), "\n") - 1
+       const tmpDir = "/mnt/data1/tmp"
+       cmd = exec.Command("roachprod", "run", cluster, "--", "mkdir", "-p", tmpDir)
+       if err := cmd.Run(); err != nil {
+               return fmt.Errorf("failed to make TMPDIR at %s: %v", tmpDir, err)
+       }
 
        const stressBin = "bin.docker_amd64/stress"
        cmd = exec.Command("roachprod", "put", cluster, stressBin)
@@ -204,7 +209,7 @@ func run() error {
                        var stderr bytes.Buffer
                        cmd := exec.Command("roachprod",
                                "ssh", fmt.Sprintf("%s:%d", cluster, i), "--",
-                               fmt.Sprintf("GOTRACEBACK=all ./stress %s", strings.Join(os.Args[2:], " ")))
+                               fmt.Sprintf("TMPDIR="+tmpDir+" GOTRACEBACK=all ./stress %s", strings.Join(os.Args[2:], " ")))
                        cmd.Stdout = stdoutW
                        cmd.Stderr = &stderr
                        if err := cmd.Run(); err != nil {
```

Repro'd in 3 minutes:

```
F190918 14:24:33.188511 12267 storage/store.go:4258  [n9,s9] found non-zero HardState.Commit on uninitialized replica [n9,s9,r3/?:{-}]. HS={Term:9 Vote:0 Commit:523 XXX_unrecognized:[]} /Local/RangeID/3/u/RaftHardState
```

[out.1568816384.txt](https://github.com/cockroachdb/cockroach/files/3626907/out.1568816384.txt)

**Comment by ajwerner** [comment]
I've confirmed that this updated PR also hits the expected bug on master without my patch (at least sometimes, though it's the only failure I've seen so far).


[out.1568817498.txt](https://github.com/cockroachdb/cockroach/files/3627008/out.1568817498.txt)
[PartitioningTest856284366.zip](https://github.com/cockroachdb/cockroach/files/3627045/PartitioningTest856284366.zip)

[out.1568817895.txt](https://github.com/cockroachdb/cockroach/files/3627056/out.1568817895.txt)

**Comment by irfansharif** [comment]
I believe this can now be closed given #40899 fixed #40213.

**Comment by ajwerner** [comment]
Indeed.

**Pull request closed without merging**
