### PR TITLE
build: build cross toolchains

### LINKED ISSUE #65351: build: pull build of cross toolchains into a separate step outside of the builder image
Currently we build all the cross-compilers as we build all the image. This has [been observed to be a bottleneck](https://github.com/cockroachdb/cockroach/blob/master/build/builder/Dockerfile#L6). Instead, I'll make the toolchain build a preliminary step that publishes the cross-toolchains to our GCP bucket, and then update the builder image so that it just downloads the built toolchains. This will simultaneously make it MUCH quicker to build the builder image, and then also give us something to build the Bazel toolchain off of (Bazel can download the toolchain from GCP at build time).

### PR DESCRIPTION
**Pull request by rickystewart**
The overwhelming majority of the time spent in building the builder
image comes from the cross toolchains. Here we separate out the
toolchain build into a separate step and package them as `.tar.gz`'s
that we simply download and install during the Docker image build.
This also opens up the opportunity to use the same toolchains in the
Bazel build, although consuming these toolchain artifacts from the Bazel
build is a follow-up project.

Closes #65351.

Release note: None

### CODE REVIEW

**Review by rail — COMMENTED** [review]
TOTALLY LOVE IT! I have a few things to discuss.

> Reviewed 10 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65406#-:-MaZ3Bm-C6kFRHI1XUgx:b96b1b0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/builder/Dockerfile, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65406#-MaZ2SSCBYtQJPC9W-Vo:-MaZ2SSCBYtQJPC9W-Vp:b-4csmrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb8d302f6d2bdb1e2d4b4ddf0f0854816f5f184/build/builder/Dockerfile#L21)):*
> ```Dockerfile
> # rsync - sed build
> # texinfo - sed build
> RUN apt-get update \
> ```

Maybe it's time to move all `RUN`s into a shell script? It'd be easier to read it with all the `&&`s and it will create a single docker layer. What do you think?
___
*[build/toolchains/toolchainbuild/perform-build.sh, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65406#-MaZ2tPV0FKxiIVp4yOW:-MaZ2tPV0FKxiIVp4yOX:b32xys3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb8d302f6d2bdb1e2d4b4ddf0f0854816f5f184/build/toolchains/toolchainbuild/perform-build.sh#L38)):*
> ```Shell
> 
> mkdir crosstool-ng \
>  && curl -fsSL http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.xz | tar --strip-components=1 -C crosstool-ng -xJ \
> ```

Shall we check the sha?
___
*[build/toolchains/toolchainbuild/perform-build.sh, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65406#-MaZ2DSF3HJSAduBNc3Z:-MaZ2DSF3HJSAduBNc3_:b-2t4vps) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb8d302f6d2bdb1e2d4b4ddf0f0854816f5f184/build/toolchains/toolchainbuild/perform-build.sh#L74)):*
> ```Shell
> #
> mkdir ncurses \
>  && curl -fsSL http://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz | tar --strip-components=1 -C ncurses -xz \
> ```

Shall we verify the sha?

**Review by rickystewart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65406)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[build/builder/Dockerfile, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65406#-MaZ2SSCBYtQJPC9W-Vo:-MaZBpqU2ayOkC2DIRKe:b-npsfhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb8d302f6d2bdb1e2d4b4ddf0f0854816f5f184/build/builder/Dockerfile#L21)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Maybe it's time to move all `RUN`s into a shell script? It'd be easier to read it with all the `&&`s and it will create a single docker layer. What do you think?
</blockquote></details>

I'll leave that for a follow-up. Now that I've deleted so much from this file, it's actually a lot more manageable. :) So maybe it won't be a huge deal going forward.

**Review by rail — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65406#-:-MaZGxHs5MJDIxoFuDUS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
