### PR TITLE
rpc: re-work connection maintenance

### PR DESCRIPTION
**Pull request by tbg**
This commit simplifies the `rpc` package.

The main aim is to make the code and the logging it produces somewhat
clearer and to pave the way for an ultimate merging of `nodedialer` with
`rpc` as well as adoption of the `util/circuit` package (async-based
circuit breaker).

`rpc.Context` hadn't aged well. Back in the day, it was a connection
pool that held on to connections even when they failed. The heartbeat
loop would run forever and its latest outcome would reflect the health
of the connection. We relied on gRPC to reconnect the transport as
necessary.

At some point we realized that leaving the connection management to
gRPC could cause correctness issues. For example, if a node is de-
commissioned and brought up again, gRPC might reconnect to it but
now we have a connection that claims to be for node X but is actually
for node Y. Similarly, we want to be able to vet that the remote
node's cluster version is compatible with ours before letting any
messages cross the connection.

To achieve this, we added `onlyOnceDialer` - a dialer that fails
all but the first attempt to actually connect, and in particular
from that point on connections were never long lived once they
hit a failure state.

Still, the code and testing around the heartbeat loop continued
to nurture this illusion. I found that quite unappealing as it
was sure to throw off whoever would ultimately work on this code.

So, while my original impetus was to produce better log messages
from `rpc.Context` when there were connection issues, I took
the opportunity to simplify the architecture of the code to
reflect what it actually does.

In doing so, a few heartbeat-related metrics were removed, as they made
limited sense in a world where failing connections get torn down (i.e.
our world).

Connection state logging is now a lot nicer. Previously, one would very
frequently see the onlyOnceDialer's error "cannot reuse client
connection" which, if one is not familar with the concept of the
onlyOnceDialer is completely opaque, and for those few in the know is an
unhelpful error - you wanted the error that occurred during dialing.

I paid special attention to the "failfast" behavior. If connections
don't stay in the pool when they are unhealthy, what prevents us from
dialing down nodes in a tight loop? I realized that we got lucky with
our use of onlyOnceDialer because it would always prompt gRPC to do
one retry, and at a 1s backoff. So, the connection would stay in the
pool for at least a second, meaning that this was the maximum frequency
at which we'd try to connect to a down node.

My cleanups to onlyOnceDialer in pursuit of better logging elimitated
this (desirable) property. Instead we now skip the log messages should
they become too frequent. I claim that this is acceptable for now since
the vast majority of callers go through a `node.Diaelr`, which has a
circuit breaker (letting callers through at most once per second).

We previously configured gRPC with a 20s dial timeout. That means that
if a remote is unreachable, we'd spend 20s just trying to dial it,
possibly tying up callers that could be trying a reachable node in the
meantime. That seemed wildly too large; I am reducing it to 5s here
which is still generous (but there's a TLS handshake in here so better
not make it too tight).

We previously tried to re-use connections that were keyed with a NodeID
for dial attempts that didn't provide a NodeID. This caused some issues
over the years and was now removed; the extra RPC connections are
unlikely to cause any issues.

The internal connection map is now a plain map with an RWMutex. This is
just easier and gets the job done. The code has simplified as a result
and it's clearer that it's correct (which it repeatedly was not in the
past).

I implemented redactability for gRPC's `status.Status`-style errors,
so they format nicer and at least we get to see the error code (the
error message is already flattened when gRPC hands us the error,
sadly).

There are various other improvements to errors and formatting. The
following are excerpts from the health channel when shutting down
another node in a local cluster:

Connection is first established:

> [n3,rnode=1,raddr=‹127.0.0.1:26257›,class=system,rpc] 3  connection is now ready

n1 goes down, i.e. existing connection is interrupted (this error comes
from `onlyOnceDialer`):

> [n3,rnode=1,raddr=‹127.0.0.1:26257›,class=system,rpc] 35  closing
connection after: ‹rpc error: code = Unavailable desc = connection
error: desc = "transport: Error while dialing connection interrupted
(did the remote node shut down or are there networking issues?)"›

Reconnection attempts; these logs are spaced 1-2s apart:

> [n3,rnode=1,raddr=‹127.0.0.1:26257›,class=system,rpc] 37  unable to
connect (is the peer up and reachable?): initial connection heartbeat
failed: ‹rpc error: code = Unavailable desc = connection error: desc =
"transport: Error while dialing dial tcp 127.0.0.1:26257: connect:
connection refused"›

n3 is back up:

> [n3,rnode=1,raddr=‹127.0.0.1:26257›,class=system,rpc] 49  connection is now ready

There are other connection errors in the logs that stem from operations
checking for a healthy connection, failing to get through circuit
breakers, etc., such as these:

> [n3,intExec=‹claim-jobs›,range-lookup=/Table/15/4/‹NULL›] 33  unable
to connect to n1: failed to check for ready connection to n1 at
‹127.0.0.1:26257›: ‹connection not ready: TRANSIENT_FAILURE›

Epic: none

Release note (general change): Previously, CockroachDB employed a 20s
connection timeout for cluster-internal connections between nodes.  This
has been reduced to 5s to potentially reduce the impact of network
issues.

Release note (general change): Previously, CockroachDB (mostly) shared a
TCP connection for the KV and Gossip subsystems. They now use their own
connection each, so the total number of outgoing and incoming TCP
connections at each node in the cluster will increase by 30 to 50
percent.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
First commit LGTM.
2nd commit - I reviewed all I could but not in the right frame of mind to ascertain correctness of the "main" thing. I'd need to look at it further next week. Also will welcome Erik's opinion of course.

> Reviewed 1 of 1 files at r1, 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-:-NDFG-sKA3HpgB6KQbMI:bt6axo9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[`pkg/rpc/context.go` line 1804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFD4Lu11IpikM98D_h:-NDFD4Lu11IpikM98D_i:bseqycx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b58861f098987881eae9108ef8fa038fd0d1005/pkg/rpc/context.go#L1804)):*
> ```Go
> 	target string, remoteNodeID roachpb.NodeID, class ConnectionClass,
> ) *Connection {
> 	ctx := rpcCtx.makeDialCtx(target, remoteNodeID, class)
> ```

Why did you move this? I put it there for the log.Fatal's benefit.
___
*[`pkg/util/grpcutil/grpc_err_redaction.go` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFE3jzArmtR-fktXdd:-NDFE3jzArmtR-fktXde:btks2zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/util/grpcutil/grpc_err_redaction.go#L28)):*
> ```Go
> 
> func grpcSpecialCasePrintFn(err error, p errbase.Printer, isLeaf bool) (handled bool, next error) {
> 	if errors.GetTypeKey(err) != grpcErrTypeKey {
> ```

nit: I think the following is just as correct and will get you less overhead:

```go
var refErr = status.Error(codes.Unavailable, "")
...
if errors.HasType(err, refErr)
```

Alternatively, you could just drop this check entirely and trust `status.FromError` - it only returns true in the 2nd return value if the status object could be recovered with the right type.
___
*[`pkg/util/netutil/net.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFF0kL5d94RrgB_ezg:-NDFF0kL5d94RrgB_ezh:b-rld57f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/util/netutil/net.go#L212)):*
> ```Go
> // SafeFormatError implements errors.SafeFormatter.
> func (e *InitialHeartbeatFailedError) SafeFormatError(p errors.Printer) (next error) {
> 	p.Printf("initial connection heartbeat failed")
> ```

nit: `p.SafeString`, less overhead.
___
*[`pkg/rpc/context_test.go` line 821 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFF8J25BpMYK_VFo9A:-NDFF8J25BpMYK_VFo9B:bq41taj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/context_test.go#L821)):*
> ```Go
> func TestHeartbeatHealth(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	// TODO why does this hide log.HEALTH even when -show-logs is active?
> ```

It was Andrei's request: #69765 / #70052.

You can define a custom log config for use with `log.Scope` if you want.

**Review by erikgrinaker — APPROVED** [review]
LGTM, but haven't been around these parts for a while so don't have all the intricacies paged in.

The reduced connection timeout deserves a release note.

**Review by tbg — COMMENTED** [review]
> The reduced connection timeout deserves a release note.

Good idea, done.

> Dismissed @knz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-:-NE0gy52ETyfsESZYe8y:bfuf34g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @knz, and @yuzefovich)

___
*[`pkg/rpc/addjoin.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDDYp8sRCjAwJ0yj7zV-r2-38:-NE0dVy38bIBIqjog7H4:bmie0k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/addjoin.go#L38)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Let's add a constant with an explanation.
</blockquote></details>

I think that could be misleading, since this value doesn't matter (the relevant use is in another file). The choice here doesn't matter because it's add-join and any reasonable value will do, and 1s is reasonable enough. In our main RPC use, we don't ever redial inside of gRPC and have succeeded in getting everything to fail-fast, so we can set any value there and the results are the same. I expanded commentary there instead.
___
*[`pkg/rpc/context.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDCWp9qfdAqCBPiA0aF-r2-353:-NE0dwQ43zQj_h1fw_ey:b-g8temd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/context.go#L353)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

So why don't we?
</blockquote></details>

I just didn't pull further. I'm seeing now that the error crosses RPC boundaries:

https://github.com/cockroachdb/cockroach/blob/fc1fa24f38a0b4f1e60bd079f231de37a2e842bd/pkg/sql/distsql_physical_planner.go#L997

so might be a bad idea esp in serverless where host cluster and tenant can have different versions. On the plus side, this is the only caller. And I did a little digging, I'm not sure why we want to special-case this error there anyway; unless ConnHealth returns nil, we should probably avoid the node. Yes, when we just dial the node for the first time, it'll take a bit longer until we actually start using it, but that's fine! Better than every now and then using a node that has been down for a while.

@yuzefovich would you confirm that this makes sense (updating the above linked snippet to remove `&& err != rpc.ErrNotHeartbeated`)?
___
*[`pkg/rpc/context.go` line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDCWp9qfdAqCBPiA0aF-r2-568:-NE0ev5rEq-MS9gi0k7r:b-o9d51z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/context.go#L568)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Why is it OK to discard the cancel function here?
</blockquote></details>

The lifetime of the object is the lifetime of the stopper, so the only thing that will ever call cancel is the stopper. And it will!
A cancel function must be called at least once, but we know it will in this case.
___
*[`pkg/rpc/context.go` line 1804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFD4Lu11IpikM98D_h:-NE0fJdtEX9Lv7S_qMrO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b58861f098987881eae9108ef8fa038fd0d1005/pkg/rpc/context.go#L1804)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why did you move this? I put it there for the log.Fatal's benefit.
</blockquote></details>

Done.
___
*[`pkg/rpc/context.go` line 1828 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDCWp9qfdAqCBPiA0aF-r2-1828:-NE0fPMx76DUbtgjYhuo:bba18tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/context.go#L1828)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Why do we add `ctx` here when we don't use it and none of the other dial methods take one?
</blockquote></details>

There was some back and forth with ctx plumbing and this is detritus, removed.
___
*[`pkg/rpc/metrics.go` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDCWp9qfdAqCBPiA0aH-r2-15:-NE0fW_WA1yv1Fes-2qK:b-dgnxcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/metrics.go#L15)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

While we're here: connections
</blockquote></details>

Just removed the whole thing, I don't think this comment was particularly helpful and it was half out of date now.
___
*[`pkg/util/netutil/net.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFF0kL5d94RrgB_ezg:-NE0g1euBp_1jQp5xBNJ:bnj6zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/util/netutil/net.go#L212)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `p.SafeString`, less overhead.
</blockquote></details>

Does not exist on `errors.Printer`.
___
*[`pkg/rpc/down_node_test.go` line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDDYp8sRCjAwJ0yj7zY-r2-64:-NE0gEYBBfR2yOtIT_Ds:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/down_node_test.go#L64)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Should we assert something about responsiveness in the `refused=false` case?
</blockquote></details>

Done.

**Comment by tbg** [comment]
Comments addressed, PTAL.

Note that I rebased and am reverting https://github.com/cockroachdb/cockroach/pull/89539 since it no longer applies to the updated code. I also went ahead and removed the connKey sharing altogether. The PR message has been updated.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`pkg/rpc/context.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDCWp9qfdAqCBPiA0aF-r2-353:-NE0ppX78rN4LNtbzloQ:bf4mhtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/rpc/context.go#L353)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I just didn't pull further. I'm seeing now that the error crosses RPC boundaries:

https://github.com/cockroachdb/cockroach/blob/fc1fa24f38a0b4f1e60bd079f231de37a2e842bd/pkg/sql/distsql_physical_planner.go#L997

so might be a bad idea esp in serverless where host cluster and tenant can have different versions. On the plus side, this is the only caller. And I did a little digging, I'm not sure why we want to special-case this error there anyway; unless ConnHealth returns nil, we should probably avoid the node. Yes, when we just dial the node for the first time, it'll take a bit longer until we actually start using it, but that's fine! Better than every now and then using a node that has been down for a while.

@yuzefovich would you confirm that this makes sense (updating the above linked snippet to remove `&& err != rpc.ErrNotHeartbeated`)?
</blockquote></details>

Hm, it sounds sane to me. However, I've never really touched this code, so I don't have a good intuition for it. I do see that this error check was introduced in #15368 over five years ago, and it's always a bit scary to change such code. In that PR, there is some discussion about `TestDistSQLDeadHosts` being slow, I wonder whether the change you're proposing somehow would affect that? Maybe looking at that test would provide some more context? (I'm on PTO for a couple of weeks, so this is just a cursory look.)

**Review by erikgrinaker — APPROVED** [review]
Appreciate the cleanup!

> Reviewed 25 of 25 files at r3, 20 of 25 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-:-NE1DqoUCrU9MrLN7vB8:b-c9z1kh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 25 files at r4, 8 of 9 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/rpc/context.go` line 1804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFD4Lu11IpikM98D_h:-NE5zZc3DAAm2ZIDLiR-:b-2qh3n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b58861f098987881eae9108ef8fa038fd0d1005/pkg/rpc/context.go#L1804)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still confused - what's the obstacle to having `ctx := rpcCtx.makeDialCtx(target, remoteNodeID, class)` here and passing it as argument to `grpcDialNodeInternal`? Is it solely because you want to avoid creating a context.Context if `rpcCtx.m.Get` returns a valid connection?
___
*[`pkg/rpc/context.go` line 1871 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NE6-4mz-VqcTfm6D4zi:-NE6-4mz-VqcTfm6D4zj:b-v0dui9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0750d8dffa5043a29b8be44ca553b6d5901d9bb/pkg/rpc/context.go#L1871)):*
> ```Go
> 	// callers that may pass a zero NodeID could coalesce onto the connection
> 	// with the "real" NodeID. This caused issues over the years[^1][^2] and
> 	// was never necessary anyway, so we don't do it anymore.
> ```

Does this mean we get 1 extra connection for those callers that use node ID 0?
If so, perhaps worth mentioning in the release note. This will double the number of node-node connections when the cluster goes from non-initialized to initialized at the point `cockroach init` is run.
___
*[`pkg/rpc/context.go` line 1943 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NE6-S553_HqwJtKrK7L:-NE6-S567H-Xh-PGeDgb:bayseug) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0750d8dffa5043a29b8be44ca553b6d5901d9bb/pkg/rpc/context.go#L1943)):*
> ```Go
> 		conn.err.Store(errDialRejected)
> 		close(conn.initialHeartbeatDone)
> 		_ = rpcCtx.m.Remove(k, conn) // ignoring error since it's just on shutdown anyway
> ```

nit: period at end of comment.

Also I'm not sure I agree  - we're moving to a world where these things get instantiated and teared down dynamically (#84700) so we want clean shutdowns in every case.
___
*[`pkg/util/netutil/net.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFF0kL5d94RrgB_ezg:-NE60I3x7Hl9Q1Cdvq3k:b-m2jqkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0612ea93faae848305a335b14a3077453a46d245/pkg/util/netutil/net.go#L212)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Does not exist on `errors.Printer`.
</blockquote></details>

oh sorry I misread. that's cool.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/rpc/context.go` line 1871 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NE6-4mz-VqcTfm6D4zi:-NE60XX6-lOR8QsqzgXu:bqfts2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0750d8dffa5043a29b8be44ca553b6d5901d9bb/pkg/rpc/context.go#L1871)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Does this mean we get 1 extra connection for those callers that use node ID 0?
If so, perhaps worth mentioning in the release note. This will double the number of node-node connections when the cluster goes from non-initialized to initialized at the point `cockroach init` is run.
</blockquote></details>

Also, gossip uses UnvalidatedDial (so with Node ID = 0). So it's not just in the non-init case we're doubling the connections. It's all the time.

(Technically, we'd be going to 2 conns per node-node pair, from system/normal classes, to 3: system/normal/gossip-other.)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/rpc/context.go` line 1871 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NE6-4mz-VqcTfm6D4zi:-NE60tJR6ctwsSDHC8vc:bwefzst) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0750d8dffa5043a29b8be44ca553b6d5901d9bb/pkg/rpc/context.go#L1871)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Also, gossip uses UnvalidatedDial (so with Node ID = 0). So it's not just in the non-init case we're doubling the connections. It's all the time.

(Technically, we'd be going to 2 conns per node-node pair, from system/normal classes, to 3: system/normal/gossip-other.) 
</blockquote></details>

That incidentally brings me to a related question: does it matter whether the gossip connection uses the same TCP connection as the other RPCs? Is there something that gossip _decides_ wrt connectivity that could be wrong / disruptive if the gossip connection succeeds, but the other RPC connection(s) fail?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88625)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @knz, and @yuzefovich)

___
*[`pkg/rpc/context.go` line 1804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NDFD4Lu11IpikM98D_h:-NE7O6FPD7LAtb3hhgpP:baaofw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b58861f098987881eae9108ef8fa038fd0d1005/pkg/rpc/context.go#L1804)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'm still confused - what's the obstacle to having `ctx := rpcCtx.makeDialCtx(target, remoteNodeID, class)` here and passing it as argument to `grpcDialNodeInternal`? Is it solely because you want to avoid creating a context.Context if `rpcCtx.m.Get` returns a valid connection?
</blockquote></details>

The dialing API is currently such that you have methods like `GRPCDialNode` that give you a `*Connection` and are *non-blocking*, so they can never use the cancellation property of the `Context` (that happens when you call `.Connect`). I think it's a little clearer to pass the context only once, or you end up with (essentially) `rpcCtx.GRPCDialNode(ctx).Connect(ctx)`.
___
*[`pkg/rpc/context.go` line 1871 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NE6-4mz-VqcTfm6D4zi:-NE7OptZCnl8tBYH_ftg:b4ahxq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0750d8dffa5043a29b8be44ca553b6d5901d9bb/pkg/rpc/context.go#L1871)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

That incidentally brings me to a related question: does it matter whether the gossip connection uses the same TCP connection as the other RPCs? Is there something that gossip _decides_ wrt connectivity that could be wrong / disruptive if the gossip connection succeeds, but the other RPC connection(s) fail?
</blockquote></details>

Good point, will mention in the release note. It shouldn't matter to Gossip who it's sharing the connection with. If anything, having its own connection might be helpful sometimes. (And of course in async weird network partitions as always all bets are off).
___
*[`pkg/rpc/context.go` line 1943 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88625#-NE6-S553_HqwJtKrK7L:-NE7PTni8KKTueFR3nPO:b149zr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0750d8dffa5043a29b8be44ca553b6d5901d9bb/pkg/rpc/context.go#L1943)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: period at end of comment.

Also I'm not sure I agree  - we're moving to a world where these things get instantiated and teared down dynamically (#84700) so we want clean shutdowns in every case.
</blockquote></details>

The shutdown here is clean, the error makes assertions. But I might as well check the error here too.

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by erikgrinaker** [comment]
Linter failure:

```
=== RUN   TestLint/TestRoachVet
    lint_test.go:91:
        pkg/rpc/context_test.go:928:11: github.com/cockroachdb/errors.Errorf format %d reads arg #1, but call has 0 args
        pkg/rpc/context_test.go:951:11: github.com/cockroachdb/errors.Errorf format %d reads arg #1, but call has 0 args
    --- FAIL: TestLint/TestRoachVet (142.81s)
```

**Comment by tbg** [comment]
bors r=erikgrinaker

**Pull request merged**
