### PR TITLE
storage: ensure atomic Renames using encryptedFS

### PR DESCRIPTION
**Pull request by jbowens**
Release justification: fixes high-severity bug in existing functionality
Release note (bug fix): Fixes a rare bug where an encryption-at-rest
store may fail to open if an ill-timed crash occurs.

### CODE REVIEW

**Review by itsbilal — COMMENTED** [review]
Looks great! Any ideas on how you'd be able to unit test this? Maybe with an `encryptedFS` around a `vfs.FS` that injects errors on one rename?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69555#-:-MiMZ0sw9Wn80tCd0G2C:boy3oev)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[pkg/storage/pebble_file_registry.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69555#-MiMYVrnAN7gFqLNYezt:-MiMYVrnAN7gFqLNYezu:bjmrv7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd9fcd167230966e5c8c6ed20466214b6639416/pkg/storage/pebble_file_registry.go#L149)):*
> ```Go
> 	// log was a rename, it's possible the corresponding filesystem
> 	// rename operation didn't finish. Do it now.
> 	// TODO(jackson): This is temporary fix; The filesystem operations
> ```

nit: "This is a temporary fix;" or "This fix is temporary;"

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/storage/pebble_file_registry.go, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69555#-MiMpAtN0ocvDTiPUkPm:-MiMpAtN0ocvDTiPUkPn:b3ojary) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bd2f004e290b3e462864cacffeecb2a937b042a/pkg/storage/pebble_file_registry.go#L390)):*
> ```Go
> // MaybeLinkEntry copies the entry under src to dst, if src exists. If
> // src does not exist, MaybeLinkEntry removes any entry under the path
> // dst.
> ```

So `vfs.FS.Link` is like `ln -f`? Don't we have an atomicity problem here too in that this call to `SetOp` is happening after the underlying file system has already done the link?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/storage/pebble_file_registry.go, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69555#-MiMpAtN0ocvDTiPUkPm:-MiNV64B1yIAyFmX9YOT:b8uvsty) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bd2f004e290b3e462864cacffeecb2a937b042a/pkg/storage/pebble_file_registry.go#L390)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So `vfs.FS.Link` is like `ln -f`? Don't we have an atomicity problem here too in that this call to `SetOp` is happening after the underlying file system has already done the link?
</blockquote></details>

Yeah, it's not atomic. AFAIK, we never rely on Link's atomicity when the destination exists, but if we go down this road of providing Rename atomicity I do think we should make Link atomic too.

**Comment by jbowens** [comment]
Closing this out in favor of updating the various dependencies on atomic renames to use new schemes for atomicity.

**Pull request closed without merging**
