### PR TITLE
ui: fix app = empty string filter on stmts page

### LINKED ISSUE #107748: ui: stmts page filter broken for appName = empty string
The filter does not work when selecting the  empty string app name filter (unset).

https://www.loom.com/share/e626301e4ceb44e0b4c44c716d6eaea2?sid=bdcd77fb-5014-4a89-80d6-03f88ea947cf

Jira issue: CRDB-30183

### PR DESCRIPTION
**Pull request by xinhaoz**
The filter on app name = empty string was not working on
the stmts page. This was due to the fact that we use (unset)
as the option in the filter to represent selecting the empty
string app name. However when filtering statements, the empty
string app name on the stmt was not changed accordingly.
this commit fixes this and also adds testing for the unset case.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/107748

Release note (bug fix): Filter on stmts page works for
app name = empty string (represented as 'unset').

https://www.loom.com/share/2fee4f0fb7b04208803e0dac1d9694ab?sid=5cabecf9-1c2a-406b-89a8-b378ed07d329

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
is this also happening on the transactions page?

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107750#-:-NaO4Yvb6mnv9_E5ylwZ:b3gu025)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
Nope, all good there!

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107750#-:-NaOA-Rq3feh6kH3BdWC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
TFTR!
Test failures unrelated - looks like a known issue as well.
bors r+

**Comment by xinhaoz** [comment]
blathers backport 23.1

**Pull request merged**
