### PR TITLE
release-23.1: deps: update golang.org/x/tools

### PR DESCRIPTION
**Pull request by rickystewart**
Backport 1/1 commits from #106256.

/cc @cockroachdb/release

---

The patch updates golang.org/x/term from v0.6.0 to v0.7.0. The update is in part motivated by spurious nogo compilation errors tracked in cockroachdb#99988.

Informs: cockroachdb#99988

Release note: None
Epic: none
Release justification: fix spurious `nogo` errors in build

### CODE REVIEW

**Comment by msbutler** [comment]
qq: is it necessary to re-`./dev gen bazel --mirror` on your 23.1 branch, even if it is a clean backport (which it seems to be)?

**Comment by rickystewart** [comment]
> qq: is it necessary to re-./dev gen bazel --mirror on your 23.1 branch, even if it is a clean backport (which it seems to be)?

Unfortunately this was not really a clean backport (as there was a conflict) but it was quite close.

To answer the question, *generally* no. For example in this case only the backport (once the conflicts were resolved) was actually necessary. Out of an abundance of caution I re-ran `dev gen bazel` on the branch before submitting the PR but it had no effect.

Note that failing to `dev gen bazel` when you would have to will cause your PR to fail CI, so you can always just backport if you're okay with potentially wasting a little time and having to do an extra CI run in the case that `dev gen bazel` was necessary.

For (clean) backports, the extra `--mirror` argument is almost never required even if you do need `dev gen bazel`. (`--mirror` causes new vendored dependencies to be uploaded to GCS, but for a clean backport, the dependencies are already there in GCS.)

**Comment by msbutler** [comment]
> Note that failing to dev gen bazel when you would have to will cause your PR to fail CI

good to know!

**Review by msbutler — APPROVED** [review]

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
TFTRs!

**Pull request merged**
