### PR TITLE
sql: drain pipelineQueue on Session.Finish

### PR DESCRIPTION
**Pull request by nvb**
We now make sure to drain the `pipelineQueue` on `Session.Finish`. This is
to assure that we don't look like we've leaked memory.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14411)

### CODE REVIEW

**Comment by benesch** [comment]
Hey @nvanbenschoten, are you sure you want my review of this? I have to admit I'm not familiar with your pipelining code, and at first glance I'm not sure I understand why ignoring the error from `Wait()` is safe given that it also sets the error to `nil`.

**Comment by nvanbenschoten** [comment]
Hey @benesch, no worries! I figured since you've been cleaning up the `Session` lifecycle this should go to you, but I think you're right that this is more of a pipelining issue. Adding @andreimatei as a reviewer.

To answer your question though, the reason we're just ignoring the error is because it would only ever be non-nil on an abandoned `Session`, in which case we don't care about what the error is. I added a sentence to the comment to address this.

**Comment by nvanbenschoten** [comment]
Ping.

**Comment by andreimatei** [comment]
LGTM I guess but I'm pretty confused. Is `Finish` supposed to be called while queries are still in flight (if so, please add a comment to the method)? If so, how come waiting for the `pipelineQueue` (which I think just has pipelined statements in it) is enough and we don't need to wait for the current non-pipelined statement too (if any)?
And also, should this `Session.Finish()` cancel the context under which the queries run (like draining does)? Or do we actually want to block for the statements to finish? (and if we want to block for some reason, should draining also block?)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14411#-:-KhT4g7eJUWmNUp3WPxi:b-6mo8ra)*

**Comment by nvanbenschoten** [comment]
`Finish` won't be called while a query is being processed synchronously because it's called by the `v3Conn.serve` goroutine which blocks on regular queries, but it could be called when asynchronous queries are operating in the background in the case of parallelized statements. This is why we need to drain the queue.

I'm not 100% sure about the second point, but I don't think we can cancel the `context`, because we still want to send a ROLLBACK during a possible txn cleanup. It would be nice to cancel the context as a way to encourage long-running parallelized queries to abort and avoid blocking the queue while draining, but I don't think this issue is unique to this situation. @asubiotto do you know if we actively try to abort ongoing queries when a client abandons them? 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14411#-:-KhVthOi2ChrbhXTdWt0:be149pi)*

**Comment by asubiotto** [comment]
@nvanbenschoten In the case of a client giving up on a long running query and issuing a `CancelRequest` message, we do not yet, but I think that @mjibson is in the process of adding this (the context does get cancelled while draining though).
FWIW I don't think it's a good idea to cancel the `context` in `session.Finish`, since `session.Finish` is triggered by either finishing the query or the query being cancelled (never called asynchronously, and I don't think it ever should be) so it wouldn't do anything.
Note that draining also blocks waiting for cancelled queries to return.

**Comment by mjibson** [comment]
I'm not going to add the CancelRequest stuff because it's too close to the feature cutoff, but I think I'll finish it up in the 1.1 window.

**Comment by andreimatei** [comment]
> Finish won't be called while a query is being processed synchronously because it's called by the v3Conn.serve goroutine which blocks on regular queries, but it could be called when asynchronous queries are operating in the background in the case of parallelized statements. This is why we need to drain the queue.

Ack. A comment explaining this on the method would be helpful.

> I don't think we can cancel the context, because we still want to send a ROLLBACK during a possible txn cleanup. 

You're talking about the `updateStateAndCleanupOnErr` call below? What does that have to do with a context cancellation? Would it not still work? We may want to not cancel the context that's passed to the TxnCoordSender and control heartbeating - as that one will do a rollback when it's cancelled and I guess we don't want the rollback to race with the pipelined statements. We may need to have derived contexts for the pipelined statements, to cancel them independent of the txn.

> It would be nice to cancel the context as a way to encourage long-running parallelized queries to abort and avoid blocking the queue while draining, but I don't think this issue is unique to this situation.

So it sounds like, once we support cancellation, we'll need to read from the client conn at the same time as we process queries, and maybe Finish() will be called concurrently with non-pipelined statements, but for now it isn't. I'm not sure what you were trying to suggest by "the issue being unique to this situation".

> FWIW I don't think it's a good idea to cancel the context in session.Finish, since session.Finish is triggered by either finishing the query or the query being cancelled (never called asynchronously, and I don't think it ever should be) so it wouldn't do anything.

But it is called async wrt to pipelined statements, as Nathan said. So why not cancel (some) context? 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14411#-:-KhY_HnlMe74WeUTZ6bt:b-43dejk)*

**Comment by nvanbenschoten** [comment]
> A comment explaining this on the method would be helpful.

Done. Added a little more to the other comment as well.

> So it sounds like, once we support cancellation, we'll need to read from the client conn at the same time as we process queries, and maybe Finish() will be called concurrently with non-pipelined statements, but for now it isn't. I'm not sure what you were trying to suggest by "the issue being unique to this situation".

Yes, that is what I was trying to convey. @mjibson's work on CancelRequest will encompass this, and will certainly include actually teaching the `sql` layer to watch for context cancellations. The best we can do right now is cancel the `Session`'s context and wait for the `client` layer to complain.

My point here was that clients abandoning long-running statements (the only time when `pipelineQueue.Wait` would be anything more than a no-op) is not unique to pipelined statements. Once the infrastructure is in place to properly cancel statements (probably with a derived context), we'll need to hook that into pipelined statements as well, but I don't want to hack something in here specific for pipelined statements when it should be more general. Added a TODO.

> So why not cancel (some) context

We actually do, that's what the call to `s.cancel()` at the bottom of this function does.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14411#-:-KhZjyE12YkO723mDGpB:bdf3828)*

**Comment by andreimatei** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14411#-:-KhhKD9bk5-D4cEON8gi:bb6ywmx)*

**Pull request merged**
