### PR TITLE
storage: improve the error for aborted txns after lease transfer

### PR DESCRIPTION
**Pull request by andreimatei**
Lease transfers wipe the timestamp cache, and so a txn that straddles a
lease transfer will not be allowed to create its txn record. This commit
introduces a specific reason for the TransactionAbortedError
highlighting that there's a new lease.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: other than the question about timestamp comparisons. This is long overdue. Thanks.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43580#-:-Lx8HS296uUN1AeSazKU:b-2dw64x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @danhhz)

___
*[pkg/storage/replica_tscache.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43580#-Lx8GQHQ7qNunIz77jTd:-Lx8GQHQ7qNunIz77jTe:b-vovkc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bab7e498243fba05d650ebd4968aee53ec1fee/pkg/storage/replica_tscache.go#L486)):*
> ```Go
> 			// Recognize the case where a lease started recently. Lease transfers bump
> 			// the ts cache low water mark.
> 			if txnMinTS.Less(lease.Start) {
> ```

Shouldn't we be comparing `wTS` to `least.Start`? Something like `wTS == lease.Start`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43580)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/storage/replica_tscache.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43580#-Lx8GQHQ7qNunIz77jTd:-Lx8JdA_7Z3nRFhqXAsc:b-eppsha) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bab7e498243fba05d650ebd4968aee53ec1fee/pkg/storage/replica_tscache.go#L486)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Shouldn't we be comparing `wTS` to `least.Start`? Something like `wTS == lease.Start`?
</blockquote></details>

Yeah, I guess that's better than what I had. Done.
I went back and forth when I wrote it originally because, if the lease is new, but `wTS != lease.Start`, it might well be the case that the lease transfer would have prevented the transaction even if the ts cache wouldn't have been overwritten again and so arguably the `NEW_LEASE_PREVENTS_TXN` still makes sense. But it's not necessarily the case - the lease might be new, but the old leaseholder might have been the same node, in which case we don't wipe the ts cache.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43580#-:-Lx8NkgmC4ZnlmxyKKvO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43580#-:-LxDRCgE3Y6pBiokvuwG:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43580#-:-Lxb5DqP1wiMu97X19ih:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @nvanbenschoten)

**Pull request merged**
