### PR TITLE
colexec: close disk resources in tests

### LINKED ISSUE #106119: sql: flakes caused by leaked goroutine `diskHealthCheckingFile` in tests
Found e.g. in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/10777271?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
    explain_test.go:559: Leaked goroutine: goroutine 45013 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
          github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:172 +0xdc
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
          github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:167 +0x5d
```

The routine needs either to shut down cleanly, or be declared as a possible leak in package `leaktest`.

This typically happens when an engine isn't closed during test tear-down. The following tests have been identified (via #106195):

- [ ] `pkg/sql/colexec.TestExternalDistinct`
- [ ] `pkg/sql/colexec.TestSpillingBuffer`
- [ ] `pkg/sql/colcontainer/colcontainer_test.TestPartitionedDiskQueueSimulatedExternal`

Jira issue: CRDB-29411

### PR DESCRIPTION
**Pull request by michae2**
Fixes: #106119

**colcontainer: close PDQ during TestPartitionedDiskQueueSimulatedExternal**

Close the `PartitionedDiskQueue` at the end of `TestPartitionedDiskQueueSimulatedExternal/HashJoin`.

Release note: None

---

**colexecutils: close SpillingBuffer during TestSpillingBuffer**

Release note: None

---

**colexec: make some operators implement colexecop.Closer interface**

This commit makes the following adjustments that fix "leaked files" in
the disk-spilling tests:
- `orderedDistinct` now implements `colexecop.Closer` (needed for
`TestExternalDistinct`)
- `orderedAggregator` and `distinctChainOps` now implement
`colexecop.Closer` (needed for `TestExternalHashAggregator`)
- `TestCrossJoiner` is adjusted to explicitly close all closers when
non-empty ON expression is used (in this case we have selection and
projection operators on top of the cross joiner which currently don't
implement the `Closer` interface).

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106459)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106459#-NZmZ0X57CsOqpsDsTTH):*
I'm not sure about this. We have this best-effort notion that closing the head operator should trigger closing operators in the whole tree, and I'd rather investigate which operators don't do that. I'm a bit concerned that this commit could be hiding some problems. Even though at the `vectorizedFlow` level we track most closers separately, it'd still be nice to improve our best-effort closing of everything by closing the head. Thoughts?

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106459)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106459#-NZmZ0X57CsOqpsDsTTH):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm not sure about this. We have this best-effort notion that closing the head operator should trigger closing operators in the whole tree, and I'd rather investigate which operators don't do that. I'm a bit concerned that this commit could be hiding some problems. Even though at the `vectorizedFlow` level we track most closers separately, it'd still be nice to improve our best-effort closing of everything by closing the head. Thoughts?
</blockquote></details>

SGTM. I will try to figure out exactly which operators are not being closed.

**Comment by yuzefovich** [comment]
@cockroachdb/storage friends please ignore this PR (I temporarily cherry-picked #106195 to see what CI says).

@michae2 hope you don't mind that I looked into this. I investigated several failures in `colexec` package, and I think I fixed them all in the last commit. Thus, I don't think we need the third commit that always closes the closers in the test harness (my thinking is that we should think through each test case separately, to see whether any "close-propagation" is missing).

**Review by michae2 — COMMENTED** [review]
Thanks for picking this up! I'm sorry I let it fester. Last commit :lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106459#-:-Ndqrot7DQuriSFo6X2H:bu8orzv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
No worries! The only exposed failure was in `kvserver` package (filed #110293), so we should be good.

bors r=yuzefovich,michae2

**Review by yuzefovich — APPROVED** [review]
> Reviewed 33 of 34 files at r4, 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106459)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Review by yuzefovich — COMMENTED** [review]
bors r=yuzefovich,michae2

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106459#-:-NdrArUj70Lp1sb-4h5t:byt5z6p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Comment by yuzefovich** [comment]
blathers backport 23.1

**Comment by mgartner** [comment]
Should we also backport this to 23.2 to fixed https://github.com/cockroachdb/cockroach/issues/112868?

**Pull request merged**
