### PR TITLE
sql: support ALTER INDEX … VISIBILITY ...

### PR DESCRIPTION
**Pull request by wenyihu6**
This commit adds support to `ALTER INDEX ... VISIBILITY ...`. `Visibility` is
currently not supported with `CREATE INDEX` or `CREATE TABLE`. Users would need
to create the index as it is fully not visible or fully visible first. And they
can change the index visibility to any float [0.0, 1.0] using `ALTER INDEX ... VISIBILITY ...`.
Invisibility specifies the invisibility of an index to the
optimizer and can be any float64 between [0.0, 1.0]. An index with invisibility
0.0 means that the index is visible. An index with invisibility 1.0 means that
the index is fully not visible. By default, an index should be visible or
invisibility 0.0. An index with invisibility 1.0 is ignored by the optimizer
unless it is used for constraint check or is explicitly selected with index
hinting. An index with invisibility between (0.0, 1.0) would be made fully not
visible to a corresponding fraction of the queries. By convention, we will
refer any indexes with invisibility == 0.0 as visible, any indexes with
invisibility == 1.0 as fully not visible, and any indexes with index visibility
in-between as partially not visible.

Informs https://github.com/cockroachdb/cockroach/issues/82363

Release note (sql change): `ALTER INDEX ... VISIBILITY ...` is now supported.
It can change an index visibility to any visibility within [0.0, 1.0].
Visibility 0.0 means the index is not visible to the optimizer, while
visibility 1.0 means the index is fully visible. A value in the range
(0.0, 1.0) means the index will be visibile to the corresponding fraction of
queries.

### CODE REVIEW

**Comment by wenyihu6** [comment]
The first commit comes from https://github.com/cockroachdb/cockroach/pull/87259.

**Review by rytaft — COMMENTED** [review]
I'm reviving this PR too. I've made a few tweaks to @wenyihu6's original commit, but not many! The first commit is #101334.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87301#-:-NSxMWSZ7-R7OypeGU0-:b-fli6in)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87301#-:-NTG0lzSBg9JeQmp6YJb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @wenyihu6)

___
*[`pkg/sql/parser/sql.y` line 2398 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87301#-NTFbMub0BCkNSeNy3GL:-NTFbMub0BCkNSeNy3GM:b-lbhj9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a844c6af7b85681fe0af732a617c7543927013/pkg/sql/parser/sql.y#L2398)):*
> ```Yacc
>         return 1
>       }
>     invisibilityConst := 1.0 - visibilityConst
> ```

nit: I still don't understand why we don't store this internally as `visibility` instead of `invisibility`. It seems like the `1.0 - [some visibility-related var]` calculations are unnecessary. I don't feel super strongly about consistently naming everything as `visibility` or `visible`, though, as I'm sure there's a reason why we use `invisibility`.

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87301#-:-NTG6raP9WDBaaPHO2Wk:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/parser/sql.y` line 2398 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87301#-NTFbMub0BCkNSeNy3GL:-NTG6Lt-Cf3Zg3Xo4Vg5:b2e56fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a844c6af7b85681fe0af732a617c7543927013/pkg/sql/parser/sql.y#L2398)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: I still don't understand why we don't store this internally as `visibility` instead of `invisibility`. It seems like the `1.0 - [some visibility-related var]` calculations are unnecessary. I don't feel super strongly about consistently naming everything as `visibility` or `visible`, though, as I'm sure there's a reason why we use `invisibility`.
</blockquote></details>

Same comment as the other PR -- the user-facing feature is described as "visibility" (since that's more intuitive), but in the codebase we use "invisibility" for the most part since we want the default to be that all indexes are visible, and therefore have invisibility=0. I think it's easier to have the default match the go default, but let me know if you think it's too confusing.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87301)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/parser/sql.y` line 2398 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87301#-NTFbMub0BCkNSeNy3GL:-NTJWXkvAH_KX-bWn9q2:bmcjrvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a844c6af7b85681fe0af732a617c7543927013/pkg/sql/parser/sql.y#L2398)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Same comment as the other PR -- the user-facing feature is described as "visibility" (since that's more intuitive), but in the codebase we use "invisibility" for the most part since we want the default to be that all indexes are visible, and therefore have invisibility=0. I think it's easier to have the default match the go default, but let me know if you think it's too confusing.
</blockquote></details>

Ok, let's keep as is.

**Pull request merged**
