### PR TITLE
sql: make session tracing better

### PR DESCRIPTION
**Pull request by knz**
- introduce a new session tracing flag "kv" which enables KV tracing.
  (tracing of K/V operations for scans, inserts, deletes etc.)  The
  motivation for this is to make session tracing and thus SHOW TRACE
  FOR as useful as EXPLAIN(DEBUG), so that the latter can later be
  removed.

- report the current tracing options/mode in the output of `SHOW
  "trace"`.

- make `SHOW TRACE` an alias to `SHOW "trace"` (UX improvement).

- fix a context plumbing bug so that TRUNCATE logs to the right
  context/span.

Needed for #15948.
Relates to #16562.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice! :lgtm:

---

Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 532 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-KmmJxehkH2jscy7xUme:-KmmJxehkH2jscy7xUmf:b9hqho7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/sqlbase/rowfetcher.go#L532)):*
> ```Go
> 	// current values.
> 	for {
> 		prettyKey, prettyVal, err := rf.processKV(ctx, rf.kv, traceKV)
> ```

When EXPLAIN(DEBUG) goes away, I think it will make sense to let `processKV` do the `VEventf` directly as necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-:-KmmKDRu7EKjCU2IKggM:be8rotp)*

**Comment by RaduBerinde** [comment]
Just a thought but we may want to propagate `kv` flag the same way we propagate `snowball`, through a baggage item on the span. Functions that need it can get the span from the ctx and check the baggage (though we don't want to do that for every row). I know that will make things easier for distsql, as we won't have to plumb a flag through.

**Comment by andreimatei** [comment]
Please see suggestion about changing the `tableWriter` and `RowFetcher` interfaces.

And I agree with Radu that a "baggage" item on the span would be a better way to do this, because it'd also work with DistSQL - it'd propagate over RPCs.

---

Review status: 0 of 23 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/session.go, line 1094 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-KmmzXGeBy41h6--6Xup:-KmmzXGeBy41h6--6Xuq:b6qo8rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/session.go#L1094)):*
> ```Go
> 	// transactions are being recorded.
> 	enabled bool
> 	// kvTracingEnabled is set at times when KV tracing is active.
> ```

in lack of a better place, please hang more comments about what "KV tracing" is here

---

*[pkg/sql/tablewriter.go, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-Kmmzg6hPTnBJvPNKWGb:-Kmmzg6iG2z6yRnPFuyf:b-pikqbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/tablewriter.go#L64)):*
> ```Go
> 	// The passed Datums is not used after `row` returns. The returned Datums is
> 	// suitable for use with returningHelper.
> 	row(context.Context, parser.Datums, bool) (parser.Datums, error)
> ```

well that bool needs to have a  name, and a link to some explanation. Also, because this is such a popular interface, consider switching the bool to an enum.

I wonder if a better interface would be a `SetKVTrace(on/off)`, set when the `planNode` is created based on the state of the session at that time.

---

*[pkg/sql/distsqlrun/tablereader.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-Kmn-etvoedkJD5HLzlI:-Kmn-etvoedkJD5HLzlJ:b-7cqodi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/distsqlrun/tablereader.go#L203)):*
> ```Go
> 	for {
> 		// TODO(radu,andrei,knz): set the traceKV flag when requested by the session.
> 		fetcherRow, err := tr.fetcher.NextRow(ctx, false /* traceKV */)
> ```

what's stopping you from setting it now?

---

*[pkg/sql/sqlbase/rowfetcher.go, line 520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-Kmn0-KCiB3uDi0KAxAb:-Kmn0-KCiB3uDi0KAxAc:byidf5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/sqlbase/rowfetcher.go#L520)):*
> ```Go
> // EncDatumRow should not be modified and is only valid until the next call.
> // When there are no more rows, the EncDatumRow is nil.
> func (rf *RowFetcher) NextRow(ctx context.Context, traceKV bool) (EncDatumRow, error) {
> ```

similarly as the other interface, consider making `traceKV` an instance member

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-:-Kmn-TKWgUT9Zyz1Im1w:bmvq90l)*

**Comment by knz** [comment]
Review status: 0 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/session.go, line 1094 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-KmmzXGeBy41h6--6Xup:-Kmn1WR9piGhQNF9nsV8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/session.go#L1094)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

in lack of a better place, please hang more comments about what "KV tracing" is here
</blockquote></details>

Done.

---

*[pkg/sql/tablewriter.go, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-Kmmzg6hPTnBJvPNKWGb:-Kmn1nKAfPgLU9BwlXKf:b-c5uvyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/tablewriter.go#L64)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well that bool needs to have a  name, and a link to some explanation. Also, because this is such a popular interface, consider switching the bool to an enum.

I wonder if a better interface would be a `SetKVTrace(on/off)`, set when the `planNode` is created based on the state of the session at that time.
</blockquote></details>

I gave a name. We can switch from bool to enum later when the flag has more values and is more complicated than "tracing on/off".

Regarding the 2nd part this doesn't make sense, the planNode is created before you know whether to trace or not (with `show trace for`).

---

*[pkg/sql/distsqlrun/tablereader.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-Kmn-etvoedkJD5HLzlI:-Kmn24tr9EsQgl2vUEbB:bgey301) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/distsqlrun/tablereader.go#L203)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's stopping you from setting it now?
</blockquote></details>

The flag is not propagated from the gateway node onto the processing node. This can be done in a follow-up PR.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-Kmn0-KCiB3uDi0KAxAb:-Kmn2AqJTDv569MGIKxg:bf3row5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/sqlbase/rowfetcher.go#L520)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

similarly as the other interface, consider making `traceKV` an instance member
</blockquote></details>

Nope, for the same reason.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 532 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567#-KmmJxehkH2jscy7xUme:-Kmn2Ddtsu_HZtjOxSCd:b-mstqq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7dfefc0e2d081f359cd5ebb41da2c9206195ec3/pkg/sql/sqlbase/rowfetcher.go#L532)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

When EXPLAIN(DEBUG) goes away, I think it will make sense to let `processKV` do the `VEventf` directly as necessary.
</blockquote></details>

yes, I have the follow-up patch ready already :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16567)*

**Comment by knz** [comment]
Merging now. I'm much more anxious to get explain(debug) out soon than to get snowball+kv tracing to work with distsql first. Let's do that in a separate PR.

**Comment by danhhz** [comment]
sorry for the drive-by here, but it seems to me that all the `traceKV` parameters added here should be hung off the context as a Value (assuming I'm understanding correctly that they're only used to control tracing)

**Comment by knz** [comment]
> sorry for the drive-by here, but it seems to me that all the |traceKV|
> parameters added here should be hung off the context as a Value

Don't be sorry!
Andrei suggested the same, but I ran into a hurdle: the Context data
structure is not very good at accessing its Values efficiently; it is a
linked list and to determine the truth value of a flag introduced this
way would require a couple steps indirection at every access.

Since we need to test this inside a rather inner loop where performance
is crucial, I figured that the boolean argument was much more efficient
(measurably so in perf benchmarks).

I would be open to using a context value if we had a good way to cache
the value across calls to (e.g.) NextRow. Do you have suggestions?

-- 
Raphael 'kena' Poss

**Comment by danhhz** [comment]
Aha! That makes sense. Everything I can think of to cache it is worse than what you ended up with. Thanks for the response!

It might be nice to have your answer here as a comment so someone doesn't come in later and helpfully "clean up" the code (thus slowing it down). The tableWriter interface might be a nice place to put such a note

**Comment by andreimatei** [comment]
It seems to me that the `traceKV` stuff should be configuration params on some planNodes, and I didn't quite understand why that was not feasible. I was going to call you on the robo when you can.

**Comment by knz** [comment]
> @andreimatei It seems to me that the |traceKV| stuff should be configuration params
> on some planNodes, and I didn't quite understand why that was not feasible.

1) this is a separate discussion: regardless of whether the flag is
passed via planNodes or via the session (what I ended up doing), there
must be an interface to pass the flag to tableWriter. For that latter
aspect the discussion with Dan applies, and I filed  #16603 to add the
missing comment.

2) I used a flag on the session object instead of planNode, because
  2.a) by the time the SHOW TRACE FOR plan node is started, its child
planNode tree is already constructed, so it's too late to (efficiently)
set a boolean everywhere it's needed
  2.b) the value is conceptually shared by all planNodes, so it would be
silly to have different variables in separate planNodes to store the
same information
  2.c) soon enough we'll do plan caching in PREPARE, and the same
logical plan can be reused in tracing and non-tracing EXECUTE
  2.d) this way we can enable/disable KV tracing at different "stages"
of the execution of a plan to capture only a partial trace

-- 
Raphael 'kena' Poss

**Pull request merged**
