### PR TITLE
encoding: propagate column direction info to pretty print

### LINKED ISSUE #20203: DESC indexes invert signage of spans in EXPLAIN
Given a `DESC` index `b`
```
CREATE TABLE bar (
  b INT,
  INDEX b(b DESC)
)
```

```
EXPLAIN SELECT * FROM bar WHERE b = -5
```
shows a misleading table scan on the span `/4 - /5` (instead of `/-5 - /-4`)
```
+-------+------+-------+-------------+
| Level | Type | Field | Description |
+-------+------+-------+-------------+
|     0 | scan |       |             |
|     0 |      | table | bar@b       |
|     0 |      | spans | /4-/5       |
+-------+------+-------+-------------+
```

The reverse is also true
```
EXPLAIN SELECT * FROM bar WHERE b = 5
```
outputs a scan on `/-6 - /-5` (instead of `/5 - /6`)
```
+-------+------+-------+-------------+
| Level | Type | Field | Description |
+-------+------+-------+-------------+
|     0 | scan |       |             |
|     0 |      | table | bar@b       |
|     0 |      | spans | /-6-/-5     |
+-------+------+-------+-------------+
```

Fortunately, the query returns the correct results so this is a matter of UX.

### PR DESCRIPTION
**Pull request by richardwu**
Fixes #20203

I've also made the distinction between `!NULL` for `NotNullAsc` and `#` for `NotNullDesc`.

~~There is however one slight issue where the interleaved sentinel can show up as `!NULL`, as in the case where we do a~~
```
SHOW TESTING_RANGES ON TABLE parent
```
This is because `SHOW TESTING_RANGES` only know about the index descriptor of parent and thus only the parent's columns and their directions. ~~It is unable to propagate column direction information for any interleaved children.~~ Since we default `NotNullDesc` to `#` in the absence of directions, we will always render actual `!NULL` and interleaved sentinels correctly.

See the [docstring above `prettyPrintFirstValue` for the entire explanation](https://github.com/cockroachdb/cockroach/pull/20318/files#diff-a60b7d03be0af825f482474399146703R1073).

cc: @danhhz

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice, thanks for this! LGTM

You have some `TestMakeSpans` tests to update :)

**Comment by nvanbenschoten** [comment]
Nice! I'd be interested to hear from @danhhz about the complication you described above though.

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/keys/printer.go, line 459 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7vrnL8vVXkB9Zt-Lb:-L-7vrnL8vVXkB9Zt-Lc:bhru813) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L459)):*
> ```Go
> 
> // prettyPrintInternal parse key with prefix in keyDict.
> // For table keys, the column directions corresponding to each value may be
> ```

Each value _that_ may be passed in? Seems like this is missing a word.

---

*[pkg/keys/printer.go, line 557 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7w1CsYA2Q7_lSC5r-:-L-7w1CsYA2Q7_lSC5r0:b-5g2tj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L557)):*
> ```Go
> // /Max                                              "\xff\xff"
> func PrettyPrint(key roachpb.Key) string {
> 	return prettyPrintInternal(nil, key, true)
> ```

Nit: it might be a bit clearer what the difference between `PrettyPrint` and `PrettyPrintWithDirs` is if this is changed to:
```
return `PrettyPrintWithDirs(nil, key)`
```

---

*[pkg/keys/printer.go, line 562 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7wHFKbGFrD0JAqEEL:-L-7wHFKbGFrD0JAqEEM:b-h7h391) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L562)):*
> ```Go
> // PrettyPrintWithDirs is the column direction-aware version of PrettyPrint.
> func PrettyPrintWithDirs(colDirs []encoding.Direction, key roachpb.Key) string {
> 	return prettyPrintInternal(colDirs, key, true)
> ```

`s/,true)/,true /* quoteRawKeys */)/`

---

*[pkg/keys/printer.go, line 685 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7wUzRjRLQpUaU5OQM:-L-7wUzRjRLQpUaU5OQN:b-6e5ofo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L685)):*
> ```Go
> 		maxChars = 8
> 	}
> 	prettyStart := prettyPrintInternal(nil, start, false)
> ```

Again, let's try to follow the [style guide](https://github.com/cockroachdb/cockroach/blob/master/STYLE.md#inline-comments-for-arguments-to-function-calls) here.

---

*[pkg/roachpb/data.go, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7wlQrZyWB9Gu4wUby:-L-7wlQrZyWB9Gu4wUbz:bdj7u51) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/roachpb/data.go#L64)):*
> ```Go
> 	// PrettyPrintKeyWithDirs is the column direction-aware version of
> 	// PrettyPrintKey.
> 	// It is also implemented in the keys package.
> ```

I'd replace `It is also implemented in the keys package` with the same `It's implemented in package git.com/cockroachdb/cockroach/keys to avoid package circle import` line we have elsewhere.

---

*[pkg/roachpb/data.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7xLL7AsEsls_BugML:-L-7xLL7AsEsls_BugMM:boryn1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/roachpb/data.go#L65)):*
> ```Go
> 	// PrettyPrintKey.
> 	// It is also implemented in the keys package.
> 	PrettyPrintKeyWithDirs func(colDirs []encoding.Direction, key Key) string
> ```

Is there a reason to create this function instead of just adding `colDirs` to `PrettyPrintKey` directly? Are there cases where we still haven't threaded the `colDirs` information?

---

*[pkg/roachpb/data.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7xhk3YMOG9c_5yCEq:-L-7xhk3YMOG9c_5yCEr:b-aqth3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/roachpb/data.go#L189)):*
> ```Go
> // String returns a string-formatted version of the key.
> func (k Key) String() string {
> 	if PrettyPrintKey != nil {
> ```

Also would probably be cleaner to call `StringWithDirs(nil)`.

---

*[pkg/util/encoding/encoding.go, line 1080 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7yjaeIBcmsXt25XNz:-L-7yjaeIBcmsXt25XO-:b8b04se) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1080)):*
> ```Go
> 			return b, "#", nil
> 		}
> 		return b, "!NULL", nil
> ```

Should these be different?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-:-L-7zE6xgZQBRcLXYFgC:b-itmcel)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/util/encoding/encoding.go, line 1048 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-80lw7TNageD0z7GZj:-L-80lw7TNageD0z7GZk:bgflsu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1048)):*
> ```Go
> 	for len(b) > 0 {
> 		// Defaults to ascending.
> 		var valDir Direction
> ```

`valDir := Ascending` would be more clear

---

*[pkg/util/encoding/encoding.go, line 1077 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-80tedIcY-TgeJ0OOp:-L-80tedIcY-TgeJ0OOq:b-xx0w7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1077)):*
> ```Go
> 	case NotNull:
> 		b, _ = DecodeIfNotNull(b)
> 		if dir == Descending {
> ```

I'm a little confused about this check, I'd expect it to be the other way around. If we run out of `dirs` above, we pass `Ascending`, but if `dirs` has directions for the parent columns only, as soon as they are done, that's where we might see an interleave sentinel, no? Conversely, if we have a descending index, an `encodedNotNullDesc` should be `!NULL`, not `#`

We probably want to special case for when `b[0] = encodedNotNullDesc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318)*

**Comment by richardwu** [comment]
So after some fiddling around and discussion with @danhhz, I've managed to make this work well for all cases (see the rationale comment below).

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/keys/printer.go, line 459 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7vrnL8vVXkB9Zt-Lb:-L-98ZJd6FtayxUtGV3m:bqh91kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L459)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Each value _that_ may be passed in? Seems like this is missing a word.
</blockquote></details>

Reworded this for clarity.

---

*[pkg/keys/printer.go, line 557 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7w1CsYA2Q7_lSC5r-:-L-99WqgnEo80x2hD8eC:bb9klg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L557)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nit: it might be a bit clearer what the difference between `PrettyPrint` and `PrettyPrintWithDirs` is if this is changed to:
```
return `PrettyPrintWithDirs(nil, key)`
```
</blockquote></details>

I've taken your suggestion to just add a `colDirs` parameter to this function.

---

*[pkg/keys/printer.go, line 562 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7wHFKbGFrD0JAqEEL:-L-9Ab47GP-Coq1T08ef:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L562)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/,true)/,true /* quoteRawKeys */)/`
</blockquote></details>

Done.

---

*[pkg/keys/printer.go, line 685 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7wUzRjRLQpUaU5OQM:-L-9AYS1YFvuVLUGQJaB:b-ubb87t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/keys/printer.go#L685)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Again, let's try to follow the [style guide](https://github.com/cockroachdb/cockroach/blob/master/STYLE.md#inline-comments-for-arguments-to-function-calls) here.
</blockquote></details>

Good catch, thanks!

---

*[pkg/roachpb/data.go, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7wlQrZyWB9Gu4wUby:-L-9Az7tgZnhXQHn4ZrZ:bw2qb1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/roachpb/data.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd replace `It is also implemented in the keys package` with the same `It's implemented in package git.com/cockroachdb/cockroach/keys to avoid package circle import` line we have elsewhere.
</blockquote></details>

Removed this method as suggested below.

---

*[pkg/roachpb/data.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7xLL7AsEsls_BugML:-L-9B0JFMF1etfYIAecf:bezw10y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/roachpb/data.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason to create this function instead of just adding `colDirs` to `PrettyPrintKey` directly? Are there cases where we still haven't threaded the `colDirs` information?
</blockquote></details>

Very true, I've removed this and added it to the base `PrettyPrintKey/PrettyPrint` functions.

---

*[pkg/roachpb/data.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7xhk3YMOG9c_5yCEq:-L-9CIoS0Q7Y3ehjAuL2:b-s2rc7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/roachpb/data.go#L189)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Also would probably be cleaner to call `StringWithDirs(nil)`.
</blockquote></details>

Good point, thanks!

---

*[pkg/util/encoding/encoding.go, line 1048 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-80lw7TNageD0z7GZj:-L-9DlWxHDdoV0Hz6KAg:b-2ltbrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1048)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`valDir := Ascending` would be more clear
</blockquote></details>

After some offline discussion with @dan, we've come to the conclusion that we can use a "default" direction if value directions are not provided when pretty-printing.

Effectively, `Ascending` will be the default direction for all values except for `NotNull`. If `Ascending` or `Descending` directions are **explicitly** provided (i.e. for table keys), then `!NULL` will be used.

If no direction is provided (in the case of `SHOW TESTING_RANGE ON TABLE parent`) for a `NotNull` value, `#` will be used. We prove that `#` will only be used for interleaved sentinels:
- For non-table keys, we never use `NotNull`
- For table keys, we always explicitly pass in `Ascending` and `Descending` for column values, including `NotNull`s. The only case we do not pass in `NotNull`s is during a `SHOW TESTING_RANGE ON TABLE parent` and there exists an interleaved split key. Note that interleaved keys cannot have `NotNull` values except for the interleaved sentinel.

Defaulting to `Ascending` for all other value types is fine since all non-table keys use encode values with `Ascending`. 

The only case where we "default" for table keys is for interleaved split keys in `SHOW TESTING_RANGE ON TABLE parent`: since interleaved prefixes are defined on the primary key  (and primary key values are always encoded `Ascending`), this will always print out the correct key even if we don't have access to the child index's columns. `

We could have created a separate enum `encoding.PrettyPrintDirection` with `Default`, `Ascending` and `Descending`, but it looks like there is already an un-used `0` value for `encoding.Direction` which we can use for pretty-printing.

---

*[pkg/util/encoding/encoding.go, line 1077 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-80tedIcY-TgeJ0OOp:-L-9Hj2RqCcX8vKGFYmC:bmjdldd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1077)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm a little confused about this check, I'd expect it to be the other way around. If we run out of `dirs` above, we pass `Ascending`, but if `dirs` has directions for the parent columns only, as soon as they are done, that's where we might see an interleave sentinel, no? Conversely, if we have a descending index, an `encodedNotNullDesc` should be `!NULL`, not `#`

We probably want to special case for when `b[0] = encodedNotNullDesc`
</blockquote></details>

You're right, thanks for the insight! I've added the rationale for the updated patch (see above).

---

*[pkg/util/encoding/encoding.go, line 1080 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-7yjaeIBcmsXt25XNz:-L-9Hwkq_3razGEDnq6T:b-a88tej) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1080)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should these be different?
</blockquote></details>

It was discussed at some point that we want to disambiguate actual `NotNull`s (as `!NULL`) from the interleaved sentinel ( as `#`) for pretty-printing. See the rationale comment I've added above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-:-L-9I904iAR4NGVoODey:b-g7e0o4)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 9 of 19 files at r1, 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/keys/printer.go, line 687 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-CMm8OPdQYdwv_KIDN:-L-CMm8OPdQYdwv_KIDO:bn4e40a) ([raw file](https://github.com/cockroachdb/cockroach/blob/831b72692e422fd5d55cd9924355815d6fd3efaf/pkg/keys/printer.go#L687)):*
> ```Go
> 		maxChars = 8
> 	}
> 	prettyStart := prettyPrintInternal(nil /* valDirs */, start, false /*quoteRawKeys */)
> ```

[nit] space before quoteRawKeys (and below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-:-L-CNbuSicYveIcEOln4:bnfp4nl)*

**Comment by danhhz** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/util/encoding/encoding.go, line 1048 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-80lw7TNageD0z7GZj:-L-CR06h8n58yf1vkVMu:b6zv3bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1048)):*
<details><summary><i>Previously, richardwu (Richard Wu) wrote…</i></summary><blockquote>

After some offline discussion with @dan, we've come to the conclusion that we can use a "default" direction if value directions are not provided when pretty-printing.

Effectively, `Ascending` will be the default direction for all values except for `NotNull`. If `Ascending` or `Descending` directions are **explicitly** provided (i.e. for table keys), then `!NULL` will be used.

If no direction is provided (in the case of `SHOW TESTING_RANGE ON TABLE parent`) for a `NotNull` value, `#` will be used. We prove that `#` will only be used for interleaved sentinels:
- For non-table keys, we never use `NotNull`
- For table keys, we always explicitly pass in `Ascending` and `Descending` for column values, including `NotNull`s. The only case we do not pass in `NotNull`s is during a `SHOW TESTING_RANGE ON TABLE parent` and there exists an interleaved split key. Note that interleaved keys cannot have `NotNull` values except for the interleaved sentinel.

Defaulting to `Ascending` for all other value types is fine since all non-table keys use encode values with `Ascending`. 

The only case where we "default" for table keys is for interleaved split keys in `SHOW TESTING_RANGE ON TABLE parent`: since interleaved prefixes are defined on the primary key  (and primary key values are always encoded `Ascending`), this will always print out the correct key even if we don't have access to the child index's columns. `

We could have created a separate enum `encoding.PrettyPrintDirection` with `Default`, `Ascending` and `Descending`, but it looks like there is already an un-used `0` value for `encoding.Direction` which we can use for pretty-printing.
</blockquote></details>

Can you include this comment in the code, plz? : - )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318)*

**Comment by richardwu** [comment]
Review status: 23 of 25 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/keys/printer.go, line 687 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-CMm8OPdQYdwv_KIDN:-L-C_8AklSsDnsYDGt1I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/831b72692e422fd5d55cd9924355815d6fd3efaf/pkg/keys/printer.go#L687)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] space before quoteRawKeys (and below)
</blockquote></details>

Done.

---

*[pkg/util/encoding/encoding.go, line 1048 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318#-L-80lw7TNageD0z7GZj:-L-CZy_aIteumdkb9MbU:bxvec61) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75659a72bf23e47b6fe083786cb05d890c4d84a/pkg/util/encoding/encoding.go#L1048)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Can you include this comment in the code, plz? : - )
</blockquote></details>

Of course, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20318)*

**Pull request merged**
