### PR TITLE
opt: add OptionalColList type

### PR DESCRIPTION
**Pull request by RaduBerinde**
I am open to better suggestions for the name.

#### opt: change ColSetToList() func to a ToList() method

Release note: None

#### opt: add OptionalColList type

For mutations, we use ColLists that map 1-to-1 to table columns, and
where some of the entries in the list can be 0. This is really meant
to represent a mapping of columns and it is an abuse of the ColList
type (which is supposed to be a simple list of columns).

We add a separate OptionalColList type which has the desired
semantics. This helps clarify things a bit (in particular it is now
obvious which of the lists are "real" lists and which are "mappings").
It will also allow a different ToSet() method which makes sense for
this structure (i.e. doesn't put 0 in the set).

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

Will you be adding `ToSet` in a future PR? Is there a use case for it right now?

> Reviewed 6 of 6 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58110#-:-MP50l2F8J1njUOP2NP5:b9vv0t2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/column_meta.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58110#-MP4z1EA7hvfllEx7D-Q:-MP4z1EA7hvfllEx7D-R:bnp0l0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a2aab84bfc72603b9138d58c387a687b7a5839/pkg/sql/opt/column_meta.go#L101)):*
> ```Go
> func (cl OptionalColList) Find(col ColumnID) (idx int, ok bool) {
> 	for i := range cl {
> 		if col != 0 && cl[i] == col {
> ```

[nit] you could move a `col == 0` check to the top of the function since you'll always return `false` in that case.

**Review by RaduBerinde — COMMENTED** [review]
TFTR! I have an upcoming usecase for `ToSet`, I will add it then.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58110#-:-MP5NSMe1uvTDEdy6Oo6:bcuyrib)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @rytaft)

___
*[pkg/sql/opt/column_meta.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58110#-MP4z1EA7hvfllEx7D-Q:-MP5NsiN961qKBHJ5b8V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a2aab84bfc72603b9138d58c387a687b7a5839/pkg/sql/opt/column_meta.go#L101)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] you could move a `col == 0` check to the top of the function since you'll always return `false` in that case.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58110#-:-MP5RL3D8iRP4DRXRjXp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

**Review by mgartner — APPROVED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58110#-:-MP73QnS0B5D-ts0v8ZH:b-83sjoh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

**Pull request merged**
