### PR TITLE
opt: initial support for optimizer + distsql combo

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### distsql: support optimizer-style scanNodes in distsql planner

In the heuristic planner, scanNodes always have all the columns of the
table, even if we're scanning a subset. With the optimizer, this is no
longer the case: only the scanned columns are present.

This change fixes up the distsql planner to support this case. The
tablereader filter and projection refer to columns by table column
ordinal, so we need to remap scanNode column ordinals to table
ordinals.

Release note: None

#### distsql: support semi/anti join in distsql planner

Release note: None

#### distsql: support zero-column values

Add support for zero column values processors. This most commonly
shows up in simple cases like `SELECT 1` where we need a one row data
source with no columns.

We add a NumRows field to ValuesCoreSpec, with the caveat that it's
only guaranteed to be set if we have zero columns (for backward
compatibility - existing code paths never plan zero-column values
processor).

Release note: None

#### opt: initial support for optimizer + distsql combo

This change adds the following:

 - support for running DistSQL queries through the TestEngine

 - execbuilder now runs every query in both local and DistSQL mode,
   unless a `nodist` flag is set. Not letting the DistSQL planner
   automatically decide if it can distribute a plan is intentional: we
   want it to be clear from the tests what can and what can't run as
   DistSQL; and we want to make sure that what we think should run
   actually gets executed.

 - Adding nodist as appropriate in the execbuilder tests. The most
   common is for EXPLAIN queries, but there are a few things DistSQL
   doesn't support: subqueries, tuples, ordinality.

Note that even with DistSQL, we still run in a single node mode, which
does not exercise all aspects of distributed planning. In a future PR,
we will tweak the configuration to have multiple nodes, and possibly
use the fake span resolver.

Release note: None

CC @andreimatei or @arjunravinarayan for looking over the first three commits which plug some holes in the distsql planner.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
@justinj I know this would conflict with your lookup join PR so I plan to wait for your PR to go in first. It might require a bit of fixing in the distsql planner to get everything working.

**Comment by andy-kimball** [comment]
Looks like most of the meat of this PR is in the DistSQL code, so I'll leave that for someone else to review. The opt code changes look fine to me.

---

Review status: 0 of 28 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LBhGL1z5gwvtUa58sPI:-LBhGL206rzs7dxNdBvh:b4oaymj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5498040c2e02e458d5ec094ab2af3316861243fc/pkg/sql/opt/exec/execbuilder/builder_test.go#L181)):*
> ```Go
> }
> 
> func execute(
> ```

NIT: This isn't a big deal given this is test code, but when I have 7 args to a function call, I always look at refactoring to use a helper struct. In this case, I'd create an `execTester` struct that wraps `optTester` and stores most of these fields as parameters (though maybe I'd handle errors in the caller so that `t` and `d` didn't have to be passed). I'd also consider making `useDistSQL` a control knob on the tester, like `Flags` is on `OptTester`. I'd make it a control knob on `OptTester` as well rather than passing it in, and default it to whatever the most sensible default is.

That kind of design makes for nicely reusable components, like the ability to use `OptTester` to implement `OptSteps`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-:-LBhIKsj8NgZMI-UVO47:b-cre285)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LBhGL1z5gwvtUa58sPI:-LBhaWgeBC5hiPOMq2R4:b-w4scqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5498040c2e02e458d5ec094ab2af3316861243fc/pkg/sql/opt/exec/execbuilder/builder_test.go#L181)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: This isn't a big deal given this is test code, but when I have 7 args to a function call, I always look at refactoring to use a helper struct. In this case, I'd create an `execTester` struct that wraps `optTester` and stores most of these fields as parameters (though maybe I'd handle errors in the caller so that `t` and `d` didn't have to be passed). I'd also consider making `useDistSQL` a control knob on the tester, like `Flags` is on `OptTester`. I'd make it a control knob on `OptTester` as well rather than passing it in, and default it to whatever the most sensible default is.

That kind of design makes for nicely reusable components, like the ability to use `OptTester` to implement `OptSteps`.
</blockquote></details>

Done, good suggestion. I kept `useDistSQL` as an argument, I think it's important to be explicit about that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25318)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql_physical_planner.go, line 837 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV1mT125QgIoNJyZO_:-LCV1mT20n31-pTiPF2s:bohiyh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L837)):*
> ```Go
> // this case we have to create a map from scanNode column ordinal to table
> // column ordinal (which is what the TableReader uses).
> func getScanNodeToTableReaderMap(n *scanNode) []int {
> ```

maybe `getScanNodeToTableOrdinal()` map

---

*[pkg/sql/distsql_physical_planner.go, line 857 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV2Q2E6Tvzdm6natjv:-LCV2Q2E6Tvzdm6natjw:b-pv699f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L857)):*
> ```Go
> // getOutputColumnsFromScanNode returns the indices of the columns that are
> // returned by a scanNode.
> func getOutputColumnsFromScanNode(n *scanNode, scanNodeToTableReaderMap []int) []uint32 {
> ```

A comment about `scanNodeToTableReaderMap` would be nice. Maybe just rename to to `remap`

---

*[pkg/sql/distsql_physical_planner.go, line 1015 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV3OHj1xtHu9RtzSfl:-LCV3OHj1xtHu9RtzSfm:b-rwdo6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L1015)):*
> ```Go
> 	}
> 
> 	planToStreamColMap := identityMapInPlace(make([]int, len(n.cols)))
> ```

how come this changed?

---

*[pkg/sql/distsql_physical_planner.go, line 1027 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV3gopDvhOaZ8UHErr:-LCV3gopDvhOaZ8UHErs:bmz5627) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L1027)):*
> ```Go
> 	}
> 
> 	types := make([]sqlbase.ColumnType, len(n.desc.Columns))
> ```

how come we're building `types` to contain info about all the columns, and not just the needed ones?

---

*[pkg/sql/distsqlrun/processors.proto, line 157 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV58au38Id-A4hMKlc:-LCV58au38Id-A4hMKld:bytssft) ([raw file](https://github.com/cockroachdb/cockroach/blob/1df1d3614319330e49e0a98980f49afd11c936ee/pkg/sql/distsqlrun/processors.proto#L157)):*
> ```protobuf
>   repeated DatumInfo columns = 1 [(gogoproto.nullable) = false];
> 
>   // The number of rows is especially useful when we have zero columns.
> ```

Please add a comment to `columns` saying that it can be empty and what that means - `raw_bytes` needs to be empty?

---

*[pkg/sql/distsqlrun/values.go, line 32 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV5JcLDf1phPnHRayt:-LCV5JcLDf1phPnHRayu:b4we3z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1df1d3614319330e49e0a98980f49afd11c936ee/pkg/sql/distsqlrun/values.go#L32)):*
> ```Go
> 	data    [][]byte
> 	// numRows is only guaranteed to be set if there are zero columns (because of
> 	// backward compatibility).
> ```

and if it is set and columns is also set, then what does it mean?

---

*[pkg/sql/distsqlrun/version_history.txt, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV5blX0AjCU1fzCupV:-LCV5blX0AjCU1fzCupW:b-9bo9pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1df1d3614319330e49e0a98980f49afd11c936ee/pkg/sql/distsqlrun/version_history.txt#L58)):*
> ```
>       will not recognize.
> - Version: 13 (MinAcceptedVersion: 6)
>     - Add NumRows to ValuesSpec (used for zero-column case). The implemnetation
> ```

nit: implemnetation

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-:-LCV85OR3jwm--ec1q0h:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR

---

Review status: 0 of 28 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 837 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV1mT125QgIoNJyZO_:-LCV9V-90yqG9PXa-uMZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L837)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe `getScanNodeToTableOrdinal()` map
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 857 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV2Q2E6Tvzdm6natjv:-LCV9n8X4nz87mGhyu_c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L857)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

A comment about `scanNodeToTableReaderMap` would be nice. Maybe just rename to to `remap`
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 1015 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV3OHj1xtHu9RtzSfl:-LCV9vFeDtWDKgC52l_M:b-14sgol) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L1015)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come this changed?
</blockquote></details>

There's no difference (`cols` and `resultColumns` always have the same columns), just thought using `cols` makes more sense (since we're also using it below)

---

*[pkg/sql/distsql_physical_planner.go, line 1027 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV3gopDvhOaZ8UHErr:-LCVAI9F1TPBoh8THwRD:bdf8dxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3becec6e993c2efa0e031b75c0746d8d8e73432a/pkg/sql/distsql_physical_planner.go#L1027)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come we're building `types` to contain info about all the columns, and not just the needed ones?
</blockquote></details>

`AddProjection` takes care of that. Admittedly it may be a bit wasteful, but it's convenient to set up the node as if there is no projection and then use `AddProjection`.

---

*[pkg/sql/distsqlrun/processors.proto, line 157 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV58au38Id-A4hMKlc:-LCVBVSPAutEvuhnxd-F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1df1d3614319330e49e0a98980f49afd11c936ee/pkg/sql/distsqlrun/processors.proto#L157)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please add a comment to `columns` saying that it can be empty and what that means - `raw_bytes` needs to be empty?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/values.go, line 32 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV5JcLDf1phPnHRayt:-LCVBjXg-T7EUz6d4o1u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1df1d3614319330e49e0a98980f49afd11c936ee/pkg/sql/distsqlrun/values.go#L32)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

and if it is set and columns is also set, then what does it mean?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/version_history.txt, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-LCV5blX0AjCU1fzCupV:-LCVBuIvCVvWsBz4hr7t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1df1d3614319330e49e0a98980f49afd11c936ee/pkg/sql/distsqlrun/version_history.txt#L58)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: implemnetation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25318#-:-LCVArQh17OPNwcx2_co:bb73zsl)*

**Pull request merged**
