### PR TITLE
rowenc: don't panic during EncDatum creation

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, EncDatum creation could panic in exceptional conditions.
Now, we return errors instead.

Release note (sql change): don't panic on some rare error cases in datum
decode.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Err, this is not ready for review yet. I have missed a bunch of updates.

**Review by RaduBerinde — COMMENTED** [review]
Are you worried about this making things slower at all?

An alternative that covers the issue observed (but less general) would be to catch panics in planNodeToRowSource.Start and Next, no?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57572#-:-MNihgxV7Kf2HWeXDoKg:buftjmo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by jordanlewis** [comment]
I'll run some benchmarks. Are you concerned? We have many worse problems than copying an extra word in some places, and this is more incentive to try to say goodbye to row exec. :)

**Review by RaduBerinde — COMMENTED** [review]
Mildly concerned, only because we will backport this (I assume)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57572#-:-MNikXgG09VW_utxzeep:b-gtqasn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by jordanlewis** [comment]
```
name                old time/op    new time/op    delta
DatumToEncDatum-12    11.5ns ± 1%    12.6ns ± 2%  +9.12%  (p=0.000 n=8+10)

name                old alloc/op   new alloc/op   delta
DatumToEncDatum-12     0.00B          0.00B         ~     (all equal)

name                old allocs/op  new allocs/op  delta
DatumToEncDatum-12      0.00           0.00         ~     (all equal)
```

**Comment by RaduBerinde** [comment]
Oops.. forgot about this.. LGTM

**Pull request closed without merging**
