### PR TITLE
opt: remove opt-generated files

### PR DESCRIPTION
**Pull request by RaduBerinde**
Remove the `og.go` files from the optimizer and add make rules to
generate them on demand. This will make working on the `.opt` files
easier, and prevent merge skew in the generated files.

Release note: None

My makefile-fu is very weak, @benesch please take a look. It seems that we are building the files every time, not sure why.. (it's very fast though)

### CODE REVIEW

**Comment by rytaft** [comment]
This definitely makes life easier for us, but won't it slow down the build for everyone else?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22957#-:-L5zFj2PT3nLyp6ZpuQa:b-ok2hly)*

**Comment by RaduBerinde** [comment]
Generating the files is instant. Building optgen is not, but I think it would only happen once (and if optgen itself is modified, which would be rare).

**Comment by rytaft** [comment]
Cool! :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22957#-:-L5zItiJ9K_OVeRw7KgF:b-dp13x5)*

**Comment by benesch** [comment]
Looking good, @RaduBerinde! The specific reason that your optgen commands are rerunning every time is because they're depending on a phony target, build-optgen, which is always considered out of date. Fixing this is not trivial. Would you mind holding off on this for a bit? I have a solution in the works!

**Comment by RaduBerinde** [comment]
Thanks! Absolutely, no rush whatsoever.

**Comment by RaduBerinde** [comment]
> they're depending on a phony target, build-optgen, which is always considered out of date

Then I wonder how come `optgen` itself isn't getting built every time?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22957#-:-L63yX0QEBArFw71bB0W:b-s7wase)*

**Comment by RaduBerinde** [comment]
@benesch any update? If it's too much trouble, I can close this PR, at least for now

**Comment by benesch** [comment]
Whoops, thanks for the ping! You inspired me to get my act together: https://github.com/cockroachdb/cockroach/pull/24104/commits/7736214d9eeeb4b508d62966fff33e1be32b1a00.

**Comment by RaduBerinde** [comment]
Closing in favor of #24104.

**Pull request closed without merging**
