### PR TITLE
kvserver: lazily translate Spans to LockUpdates instead of pre-alloca…

### LINKED ISSUE #77219: kv: avoid `*Transaction -> []LockUpdate` translation in `IntentResolver.ResolveIntents`
In https://github.com/cockroachdb/cockroach/issues/76282, we saw OOMs during a highly concurrent data ingestion workload. The OOMs were permitted in part because CRDB did not push back on the client fast enough, allowing too much async work to build up in the IntentResolver.

To avoid some memory amplification along the intent resolution path, we could rework the contract of `IntentResolver.ResolveIntents` to avoid the eager `*Transaction -> []LockUpdate` translation.

Instead of calling `LocksAsLockUpdates` [here](https://github.com/cockroachdb/cockroach/blob/8eb279af465b85badd8e3ddb175f60b922f6992d/pkg/kv/kvserver/intentresolver/intent_resolver.go#L771), which allocates memory proportionally to the number of intent spans in a txn, we should have `ResolveIntents` accept an interface which lazily transforms each `LockSpan` in a `Transaction` to a `LockUpdate` in [this loop](https://github.com/cockroachdb/cockroach/blob/8eb279af465b85badd8e3ddb175f60b922f6992d/pkg/kv/kvserver/intentresolver/intent_resolver.go#L866).

Jira issue: CRDB-13478

### PR DESCRIPTION
**Pull request by shralex**
…ting

Previously, we called LocksAsLockUpdates before calling ResolveIntents, which
pre-allocated memory for all LockUpdates. In this PR we change the interface
of ResolveIntents to avoid this memory allocation and perform the translation
of Span to LockUpdate lazily, as we iterate over them in ResolveIntents.

Release justification: stability change that may help avoid OOM.
Release note: None

Resolves: https://github.com/cockroachdb/cockroach/issues/77219
Jira issue: https://cockroachlabs.atlassian.net/browse/CRDB-13478

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @shralex)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAdyko808qs8I_6SQ-r:-NAdyko808qs8I_6SQ-s:b-rxy7d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/replica_rangefeed.go#L126)):*
> ```Go
> 	ctx context.Context, intents []roachpb.LockUpdate,
> ) error {
> 	return tp.ir.ResolveIntents(ctx, intents, nil,
> ```

nit: `nil /* txn */`
___
*[`pkg/kv/kvserver/concurrency/lock_table_waiter.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAdyyrJ6qMxX8y47rMQ:-NAdyyrJ6qMxX8y47rMR:b-6efydc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L131)):*
> ```Go
> 
> 	// ResolveIntents synchronously resolves the provided batch of intents.
> 	ResolveIntents(context.Context, interface{}, *roachpb.Transaction, intentresolver.ResolveOptions) *Error
> ```

Instead of an empty interface, could we use `[]IntentInfo` here instead?
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe1Gy4EhPptKNdprRG:-NAe1Gy4EhPptKNdprRH:b-rxy7d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/intentresolver/intent_resolver.go#L543)):*
> ```Go
> 		// Thus, we must poison.
> 		opts := ResolveOptions{Poison: true}
> 		if pErr := ir.ResolveIntents(ctx, resolveIntents, nil, opts); pErr != nil {
> ```

nit: `nil /* txn */`
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe1Wbe27Vrtdh4MjHM:-NAe1Wbe27Vrtdh4MjHN:bchk5aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/intentresolver/intent_resolver.go#L877)):*
> ```Go
> 
> 	respChan := make(chan requestbatcher.Response, intents.Len())
> 	for i := 0; i < intents.Len(); i++ {
> ```

nit: `for i, intent := range intents` could also work here. 
___
*[`pkg/roachpb/data.go` line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe0UEs2PIA1gkl5Pv7:-NAe0UEs2PIA1gkl5Pv8:bbemr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/roachpb/data.go#L1273)):*
> ```Go
> }
> 
> // IntentInfo allows for eager or lazy translation of lock spans to lock updates
> ```

nit: here, and below, periods at the end of the comment. 
___
*[`pkg/roachpb/data.go` line 1275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe-qrNDrfKrwqcpKDU:-NAe-qrNDrfKrwqcpKDV:b-q8q3bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/roachpb/data.go#L1275)):*
> ```Go
> // IntentInfo allows for eager or lazy translation of lock spans to lock updates
> type IntentInfo interface {
> 	Intent(t *Transaction) LockUpdate
> ```

Should we call this `GetLockUpdate` or something similar? I say because we seem to have a separate proto message called `Intent`, and calling this method `Intent` and having it return a `LockUpdate` might be a bit confusing. 

Do you think it's worth renaming the interface as well?
___
*[`pkg/roachpb/data.go` line 1283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe0YowBNMhzUATeP_F:-NAe0YowBNMhzUATeP_G:bahuz2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/roachpb/data.go#L1283)):*
> ```Go
> }
> 
> // Intent trivially returns self when Intent() is called on a LockUpdate
> ```

nit: Could you also add a comment of the form "Intent implements the IntentInfo interface" as well, here and above? Though not always, we generally add these on functions that are part of an interface implementation.

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAdyko808qs8I_6SQ-r:-NAeJTF6BN-5DwtHoWrE:b-b7dp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/replica_rangefeed.go#L126)):*
>  /* txn */
Done
___
*[`pkg/kv/kvserver/concurrency/lock_table_waiter.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAdyyrJ6qMxX8y47rMQ:-NAeMDGt1fODdJYo5EqJ:b-j0y6mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L131)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of an empty interface, could we use `[]IntentInfo` here instead?
</blockquote></details>

UFAIU, no. https://stackoverflow.com/questions/12753805/type-converting-slices-of-interfaces/12754757#12754757
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe1Gy4EhPptKNdprRG:-NAeJfV-54xyrD8n4cgO:b-sl7hsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/intentresolver/intent_resolver.go#L543)):*
> /* txn */
Done
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe1Wbe27Vrtdh4MjHM:-NAeLEjQ3F-uU6-SwzY5:b-dwawtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/intentresolver/intent_resolver.go#L877)):*
> for i, intent := range intents
intents has the type of reflection.Value, so this unfortunately doesn't work.
___
*[`pkg/roachpb/data.go` line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe0UEs2PIA1gkl5Pv7:-NAeJlf96UG6WnQaHbkM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/roachpb/data.go#L1273)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: here, and below, periods at the end of the comment. 
</blockquote></details>

Done
___
*[`pkg/roachpb/data.go` line 1275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe-qrNDrfKrwqcpKDU:-NAeKPQW8SsGADt-bRIq:bk59ql2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/roachpb/data.go#L1275)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we call this `GetLockUpdate` or something similar? I say because we seem to have a separate proto message called `Intent`, and calling this method `Intent` and having it return a `LockUpdate` might be a bit confusing. 

Do you think it's worth renaming the interface as well?
</blockquote></details>

Done, renamed both
___
*[`pkg/roachpb/data.go` line 1283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAe0YowBNMhzUATeP_F:-NAeKy4B06yFHac9rE3D:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/roachpb/data.go#L1283)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Could you also add a comment of the form "Intent implements the IntentInfo interface" as well, here and above? Though not always, we generally add these on functions that are part of an interface implementation. 
</blockquote></details>

Done

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @nvanbenschoten, and @shralex)

___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 879 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAet80z7cDK0Zd1wBnE:-NAet80z7cDK0Zd1wBnF:bak3ifx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66ecedac2a8121401d0a51933719504c5082ed/pkg/kv/kvserver/intentresolver/intent_resolver.go#L879)):*
> ```Go
> 	for i := 0; i < intents.Len(); i++ {
> 		in := intents.Index(i)
> 		intent := in.MethodByName("GetLockUpdate").Call([]reflect.Value{reflect.ValueOf(txn)})[0].
> ```

We should avoid using reflection in production code paths. It's slow and it lacks type safety. One way to make this type-safe and accomplish our goal is to create a structure like the following to parameterize the iterator itself.
```go
type lockUpdates interface {
	Len() int
	Index(i int) roachpb.LockUpdate
}

type txnLockUpdates roachpb.Transaction

func (t *txnLockUpdates) Len() int {
	return len(t.LockSpans)
}

func (t *txnLockUpdates) Index(i int) roachpb.LockUpdate {
	return roachpb.MakeLockUpdate((*roachpb.Transaction)(t), t.LockSpans[i])
}

type sliceLockUpdates []roachpb.LockUpdate

func (s *sliceLockUpdates) Len() int {
	return len(*s)
}

func (s *sliceLockUpdates) Index(i int) roachpb.LockUpdate {
	return (*s)[i]
}

func (ir *IntentResolver) cleanupFinishedTxnIntents(...) {
	...
	ir.ResolveIntents(ctx, (*txnLockUpdates)(txn), opts)
	...
}

func (ir *IntentResolver) ResolveIntents(
	ctx context.Context, intents []roachpb.LockUpdate, opts ResolveOptions,
) (pErr *roachpb.Error) {
	return ir.resolveIntents(ctx, (*sliceLockUpdates)(&intents), opts)
}

func (ir *IntentResolver) resolveIntents(
	ctx context.Context, intents lockUpdates, opts ResolveOptions,
) (pErr *roachpb.Error) {
	...
}
```

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @nvanbenschoten, and @shralex)

___
*[`pkg/kv/kvserver/concurrency/lock_table_waiter.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAdyyrJ6qMxX8y47rMQ:-NAf7khj8_j8a9lt68fV:b-l0u5vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L131)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

UFAIU, no. https://stackoverflow.com/questions/12753805/type-converting-slices-of-interfaces/12754757#12754757
</blockquote></details>

The motivation behind this was to get rid of the `reflect` stuff we have below. Nathan's approach seems cleaner though as we don't need to thread in the transaction if we structured things as he said -- let's do that instead!

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table_waiter.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAdyyrJ6qMxX8y47rMQ:-NAgfp56EMmQ0luq0VTv:b2nha9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c757ffa46cc50184bae23c672a72ee6efd37f4e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L131)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The motivation behind this was to get rid of the `reflect` stuff we have below. Nathan's approach seems cleaner though as we don't need to thread in the transaction if we structured things as he said -- let's do that instead! 
</blockquote></details>

ACK
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 879 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAet80z7cDK0Zd1wBnE:-NAgfrJv61s3O0ZmkMX3:bm02cs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66ecedac2a8121401d0a51933719504c5082ed/pkg/kv/kvserver/intentresolver/intent_resolver.go#L879)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should avoid using reflection in production code paths. It's slow and it lacks type safety. One way to make this type-safe and accomplish our goal is to create a structure like the following to parameterize the iterator itself.
```go
type lockUpdates interface {
	Len() int
	Index(i int) roachpb.LockUpdate
}

type txnLockUpdates roachpb.Transaction

func (t *txnLockUpdates) Len() int {
	return len(t.LockSpans)
}

func (t *txnLockUpdates) Index(i int) roachpb.LockUpdate {
	return roachpb.MakeLockUpdate((*roachpb.Transaction)(t), t.LockSpans[i])
}

type sliceLockUpdates []roachpb.LockUpdate

func (s *sliceLockUpdates) Len() int {
	return len(*s)
}

func (s *sliceLockUpdates) Index(i int) roachpb.LockUpdate {
	return (*s)[i]
}

func (ir *IntentResolver) cleanupFinishedTxnIntents(...) {
	...
	ir.ResolveIntents(ctx, (*txnLockUpdates)(txn), opts)
	...
}

func (ir *IntentResolver) ResolveIntents(
	ctx context.Context, intents []roachpb.LockUpdate, opts ResolveOptions,
) (pErr *roachpb.Error) {
	return ir.resolveIntents(ctx, (*sliceLockUpdates)(&intents), opts)
}

func (ir *IntentResolver) resolveIntents(
	ctx context.Context, intents lockUpdates, opts ResolveOptions,
) (pErr *roachpb.Error) {
	...
}
```
</blockquote></details>

Thanks a lot, this is awesome. I changed the code, wasn't sure about the test. In intent_resolver_tests we seem to use RPCs, and I verified that this new code is exercised but I haven't changed it yet. Let me know if you think we need to add anything.

**Review by nvb — APPROVED** [review]
:lgtm: nice! I think this is safe enough to merge now, given the improved type safety.

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-:-NAkZFHJ5d_Zlcy5PiEg:b-2a4w06)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @shralex)

___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 879 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86988#-NAet80z7cDK0Zd1wBnE:-NAkZ7Rn4bxnpgohwLYF:b-megova) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66ecedac2a8121401d0a51933719504c5082ed/pkg/kv/kvserver/intentresolver/intent_resolver.go#L879)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Thanks a lot, this is awesome. I changed the code, wasn't sure about the test. In intent_resolver_tests we seem to use RPCs, and I verified that this new code is exercised but I haven't changed it yet. Let me know if you think we need to add anything.
</blockquote></details>

There's plenty of testing that exercises these different code paths, so I think if it passes CI, we have good confidence that it works.

**Review by arulajmani — APPROVED** [review]

**Pull request merged**
