### PR TITLE
rfc: enable Datestyle/IntervalStyle by Default

### PR DESCRIPTION
**Pull request by e-mbrown**
This is a proposal for enabling Datestyle and Intervalstyle
by default.

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
Nice!

I think this would be a lot more readable to people who have no context on the issue if you had a couple of examples of it broken. See comments below.

You probably also want to add a few extra new lines to separate paragraphs out. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-:-MtpLqpU5CRjKcSS0Cqd:b4vsgmn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLn6L-sEHjc_qzlGv:-MtpLn6L-sEHjc_qzlGw:byrsxbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L3)):*
> ```Markdown
> - Feature Name: DateStyle/IntervalStyle Enabled by Default
> - Status: in-progress
> - Start Date: 2021-11-
> ```

nit: enter a day :)
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpKlnaD0lKlVkLqEou:-MtpKlnaD0lKlVkLqEov:b7guw36) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L5)):*
> ```Markdown
> - Start Date: 2021-11-
> - Authors: Ebony Brown
> - RFC PR: []()
> ```

you can fill these two in :)
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpKnzJCdCIRnseALeJ:-MtpKnzJCdCIRnseALeK:byioacd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L10)):*
> ```Markdown
> # Summary
> 
> This document describes the process of enabling the Datestyle/Intervalstyle options by default.
> ```

nit: `IntervalStyle` / `DateStyle` capitalisation
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpKrWNAS8SA-5kJspx:-MtpKrWNAS8SA-5kJspy:bazjtpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L11)):*
> ```Markdown
> 
> This document describes the process of enabling the Datestyle/Intervalstyle options by default.
> In its current states, date to string and interval to string casts aren't restricted when the Datestyle/Intervalstyle session 
> ```

nit: In it's current state,
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpKv_e53M_9kTeYeit:-MtpKv_e53M_9kTeYeiu:bivsy3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L12)):*
> ```Markdown
> This document describes the process of enabling the Datestyle/Intervalstyle options by default.
> In its current states, date to string and interval to string casts aren't restricted when the Datestyle/Intervalstyle session 
> variables are false. This allows for inconsistencies in formatting when the session variables are true.  This will be 
> ```

It may be worth detailing an example of why it's broken.
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLa8N9HBNkmS8O7QV:-MtpLa8N9HBNkmS8O7QW:bwd7tis) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L19)):*
> ```Markdown
> 
> 
> In 21.2 an experimental feature was added to CockroachDB which allowed Datestyle and Intervalstyle to take on multiple values.
> ```

nit: v21.2, may be worth hyperlinking the PR
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpL6D4EzBqGAE3zWWG:-MtpL6D4EzBqGAE3zWWH:bjie4f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L31)):*
> ```Markdown
> ## Migration
> 
> We’d start a long-running migration that queries for all descriptors in system descriptors. We will iterate through the
> ```

nit: "In v22.1, we will start a long-running migration that queries for all TableDescriptors on the cluster`
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLGdA99vnBxpzIQO2:-MtpLGdA99vnBxpzIQO3:bkk2sdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L34)):*
> ```Markdown
> descriptors looking at each column. For every computed column found, we will check the computed expression volatility. If we find 
> an expression that isn't immutable, we can assume it's the violating cast and rewrite the expression. We will walk through 
> the expression, and using a visitor type assert the cast expressions into function expressions. Doing this will allow us to 
> ```

Are we doing this for DEFAULT and partial index expressions as well?
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLYIb389Fk7mDHYax:-MtpLYIb389Fk7mDHYay:b-2a6wix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L42)):*
> ```Markdown
> # Alternative Considered
> 
> We also considered a simpler approach which involved keeping the session variables for one more release. If version 22.1 
> ```

nit: replace "version 22.1" with "v21.1"
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLfDRCd-hyysYh07r:-MtpLfDRCd-hyysYh07s:b-r4swh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L47)):*
> ```Markdown
> error that specifies that the violating cast are no longer supported. The customers could use the virtual table to determine 
> what needs to be changed in order for the migration to be finalized.  
> For CC, the SRE team would have to be notified as 
> ```

nit: extra new line before this line

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @rafiss)

___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpKlnaD0lKlVkLqEou:-MuCHuld7jXywDs65Mw9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L5)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

you can fill these two in :)
</blockquote></details>

Done.
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpKv_e53M_9kTeYeit:-MuCHxzL9jiJCBhQs4Jl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L12)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

It may be worth detailing an example of why it's broken.
</blockquote></details>

Done.

**Comment by e-mbrown** [comment]
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLa8N9HBNkmS8O7QV:-MuCJ36ECh4XbBoONwou:b-asu7y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L19)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: v21.2, may be worth hyperlinking the PR
</blockquote></details>

Would #67000 be the correct Pr to link?

**Review by otan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @rafiss)

___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLa8N9HBNkmS8O7QV:-MuFK6bJD6vJzP51H2d_:b-wztxf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L19)):*
<details><summary><i>Previously, e-mbrown wrote…</i></summary><blockquote>

Would #67000 be the correct Pr to link? 
</blockquote></details>

yep for IntervalStyle
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MuFK3es08rRYz0MpeXl:-MuFK3es08rRYz0MpeXm:bf06i0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f951f661cd824d08e0fedfff1398c58e48713782/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L43)):*
> ```Markdown
> 
> This will be 
> corrected by removing the session variables as well as rewriting all instances of the violating cast in computed columns.
> ```

nit: collapse with line above

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLGdA99vnBxpzIQO2:-MuFWRkp6eriWvdSXPQC:b-fj286x) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L34)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Are we doing this for DEFAULT and partial index expressions as well?
</blockquote></details>

didn't seem like this got addressed yet
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MuFWUz17f2qemK7565i:-MuFWUz17f2qemK7565j:bp5t0q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f951f661cd824d08e0fedfff1398c58e48713782/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L65)):*
> ```Markdown
> an expression that isn't immutable, we can assume it's the violating cast and rewrite the expression. We will walk through 
> the expression, and using a visitor type assert the cast expressions into function expressions. Doing this will allow us to 
> use the builtin "parse_interval" and "to_char_with_style", created during the original Date/IntervalStyle implementation.
> ```

you want to use backticks instead of " here because otherwise it shows up as italics

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MtpLGdA99vnBxpzIQO2:-MuprZ6C-dxJ8-oGMLH4:b-73mqk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db36e6ac72966c956914cef4289d166bf2c21fa/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L34)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

didn't seem like this got addressed yet
</blockquote></details>


We are going to rewrite partial index expressions but not DEFAULT expressions.
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MuFWUz17f2qemK7565i:-MuprOgJ9uSXR227AOOR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f951f661cd824d08e0fedfff1398c58e48713782/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L65)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

you want to use backticks instead of " here because otherwise it shows up as italics
</blockquote></details>

Done.

**Review by otan — COMMENTED** [review]
cool one more thing to do - we should format this to 80 characters max like all the RFCs are (unless you need it for table formatting / URL linking).

You can use https://plugins.jetbrains.com/plugin/7234-wrap-to-column/ to automagically do this for you, if you're using Goland!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-:-Musx05Z3TM77GxikbKd:b8b1y6t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @rafiss)

___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-Muswc69Ce-MYER1RQWc:-Muswc69Ce-MYER1RQWd:bq2z8fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9244395bb5d1cdb7c320aa3a17cfd1b1f23839a3/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L14)):*
> ```Markdown
> variables are false. This allows for inconsistencies in formatting when the session variables are true.
> 
> Example:
> ```

let's replace this with "This is an example of how having IntervalStyle set can lead to a corrupt computed index."
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-Muswi6A9rfAKVMZsS_r:-Muswi6B7EOV5VdYeulR:b-785w2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9244395bb5d1cdb7c320aa3a17cfd1b1f23839a3/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L43)):*
> ```Markdown
> 
> This will be corrected by removing the session variables as well as rewriting all instances of the violating cast 
> in computed columns.
> ```

computed columns, index expressions and partial indexes
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 68 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MuswqBm106dn276DWMh:-MuswqBm106dn276DWMi:bm08lnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9244395bb5d1cdb7c320aa3a17cfd1b1f23839a3/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L68)):*
> ```Markdown
> would be accounted when iterating through computed however partial indexes would not. To account for partial indexes, all
> partial indexes will be iterated over after the computed columns. The rewriting will use the builtin `parse_interval` and 
> `to_char_with_style`, created during the original Date/IntervalStyle implementation.Other date to string cast seem to be blocked, 
> ```

nit: extra space required

**Review by otan — APPROVED** [review]
looks good!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-:-Mv0KLhVBJYDWLZF7jLx:bbo24j7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 68 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-MuswqBm106dn276DWMh:-Mv0KC9NCQhWFQ4ofweV:bryon45) ([raw file](https://github.com/cockroachdb/cockroach/blob/9244395bb5d1cdb7c320aa3a17cfd1b1f23839a3/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L68)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: extra space required
</blockquote></details>

Lets make a new paragraph after "The rewriting will use"
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-Mv0K99T2oSDPYoolEdB:-Mv0K99T2oSDPYoolEdC:bsey4g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff19d1d83ded2d1fb5f19a21ff8812b01ed8812/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L74)):*
> ```Markdown
> assume it's the violating cast and rewrite the expression. We will walk through
> the expression, and using a visitor type assert the cast expressions into
> function expressions. We found that the formatting issue could also affect
> ```

let's make a new paragraph after "We found that"
___
*[docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75084#-Mv0KGKA59aQrTY8bWdr:-Mv0KGKA59aQrTY8bWds:b-3rwwqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff19d1d83ded2d1fb5f19a21ff8812b01ed8812/docs/RFCS/20211220_DateStyle_IntervalStyle_Default.md#L79)):*
> ```Markdown
> account for partial indexes, all partial indexes will be iterated over after the
> computed columns. The rewriting will use the builtin `parse_interval` and
> `to_char_with_style`, created during the original Date/IntervalStyle
> ```

nit: extra comma here.

**Pull request merged**
