### PR TITLE
Adding myself to authors

### PR DESCRIPTION
**Pull request by madelineliao**

### CODE REVIEW

**Review by bobvawter — APPROVED** [review]
LGTM. Welcome to the team!

**Comment by otan** [comment]
welcome @madelineliao!

just a heads up that we ideally don't push branches to cockroachdb/cockroach, but a fork instead. see "where to push" in https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR!

**Pull request merged**
