### PR TITLE
sql: implement JSON operations on still-encoded data

### PR DESCRIPTION
**Pull request by justinj**
Apologies for the size of this! Reviewing the commits in order should provide a mostly coherent view of the changes in more digestible chunks.

This PR could probably do with some more polish, but I've been staring at it for so long that I think it will be more productive to get some external eyes on it.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Good work so far.

I'm missing a clear sense for which operations are the ones that need optimization. It seems like this PR is going for the low-hanging lazy decoding fruit - which is fine, but I think the tradeoffs here are getting murky.

The main comment I have for this approach is that it's missing any sort of caching. Normally when you have a lazy decoded object, you cache the parts that you decode as you decode them, so that you never need to redo the decoding work later.

However, this caching obviously adds memory overhead. In order to make a good decision about what kind of laziness we want to implement, we need to think about the list of operations we're trying to support, ordered by how important it is that they go fast.

That being said, my intuition is that it's probably nearly always better to cache the decoded values aggressively. That's because all of these objects are statement scoped anyway. For example, in `Compare` and `shallowDecode`, we end up creating a brand new (decoded) json object that contains (encoded) subvalues - all of this stuff has to get allocated on the heap. We end up throwing it away after `Compare`, but those allocations still happened. I think it would be better in almost every case to memoize the work we did to decode the keys by storing the decoded versions on the original `encodedJson` object.

Does that make sense?

---

Reviewed 11 of 11 files at r1, 7 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/builtins/generator_builtins.go, line 422 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyl_9-ghDueIAnIYiY:-Kzyl_9-ghDueIAnIYiZ:b-2zptk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/sql/sem/builtins/generator_builtins.go#L422)):*
> ```Go
> 	// TODO(justin): with the introduction of encoded data, this is now very
> 	// slow.  Need to figure out the right abstraction to make this fast.
> 	// We should probably expose some kind of array iterator.
> ```

If you made Start() just decode the entire value it would be fast. Seems like a reasonable tradeoff no?

---

*[pkg/util/json/contains.go, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyRPHk7BW0GfeUhUy0:-KzyRPHk7BW0GfeUhUy1:bmhfbb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a10cd147a46b08be70cf96b7dca14b28df01b755/pkg/util/json/contains.go#L161)):*
> ```Go
> 			}
> 			var c int
> 			c, err = j.scalars[i].JSON.Compare(o.JSON)
> ```

fyi: you could use := and not declare the c. but this really doesn't matter

---

*[pkg/util/json/encoded.go, line 18 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyjuK_7YEah1cegH3-:-KzyjuK_7YEah1cegH30:b-udowh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L18)):*
> ```Go
> 	// arrays and objects, value contains the container header, but it never
> 	// contains a scalar container header.
> 	value []byte
> ```

When you described this feature I was envisioning that you'd have a pointer to a JSON to cache the results of decode. Otherwise, you'll probably end up decoding more than once a lot of the time. Is there a reason you didn't include that? 

---

*[pkg/util/json/encoded.go, line 53 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzygrqHAnNAz9k05O_2:-KzygrqIM7Fy4PCl-4SW:b-lklv0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L53)):*
> ```Go
> 		return v, 0, err
> 	}
> 	switch containerHeader & containerHeaderTypeMask {
> ```

maybe capture this value since you're using it again below

---

*[pkg/util/json/encoded.go, line 59 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyfg4eEIYdyEDNH-n3:-Kzyfg4fFYzydFzNmtDU:bj2a25) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L59)):*
> ```Go
> 		return v, ObjectJSONType, nil
> 	case scalarContainerTag:
> 		jEntry, err := getUint32At(v, 4)
> ```

4 is a magic number. i think we want a containerHeaderTypeLen.

---

*[pkg/util/json/encoded.go, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyfkY1JEqjb1Wu8WlY:-KzyfkY1JEqjb1Wu8WlZ:bt1oftj) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L65)):*
> ```Go
> 		switch jEntry & jEntryTypeMask {
> 		case nullTag:
> 			return v[8:], NullJSONType, nil
> ```

8 is also a magic number. containerHeaderTypeLen + jEntryTypeLen?

---

*[pkg/util/json/encoded.go, line 79 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyhErYMl8bGg_nJCqc:-KzyhErYMl8bGg_nJCqd:b-4os519) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L79)):*
> ```Go
> }
> 
> func newEncoded(jentry uint32, v []byte) (JSON, error) {
> ```

nit: jEntry is used elsewhere

---

*[pkg/util/json/encoded.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyhKBZqiR7T7fU2bBG:-KzyhKBZqiR7T7fU2bBH:b-ufamgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L99)):*
> ```Go
> 			return nil, err
> 		}
> 		switch containerHeader & containerHeaderTypeMask {
> ```

capture this

---

*[pkg/util/json/encoded.go, line 169 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyfUP1fk-XOp6usq5d:-KzyfUP1fk-XOp6usq5e:bjisajd) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L169)):*
> ```Go
> 	switch j.typ {
> 	case StringJSONType:
> 		return "string"
> ```

i sense a DRY opportunity - don't we already have this enum somewhere?

---

*[pkg/util/json/encoded.go, line 220 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyf92WOLTcpqnCoqwh:-Kzyf92WOLTcpqnCoqwi:bbr9n3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L220)):*
> ```Go
> 	decoded, err := j.decode()
> 	if err != nil {
> 		buf.WriteString(`<corrupt JSON data: `)
> ```

could use fmt.Fprintf(&buf, ...) if you wanted

---

*[pkg/util/json/encoded.go, line 227 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyl6Vlxybr2QDHKNkZ:-Kzyl6Vlxybr2QDHKNk_:bl6eroe) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L227)):*
> ```Go
> 	}
> }
> ```

All of these methods should say  e.g.`RemoveIndex implements the JSON interface.`

---

*[pkg/util/json/encoded.go, line 306 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzykpBckyJv2RPrMiX8:-KzykpBckyJv2RPrMiX9:b7t1y3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L306)):*
> ```Go
> }
> 
> // maybeDecode implements the JSON interface.
> ```

Doesn't seem like JSON owns this method?

---

*[pkg/util/json/encoded.go, line 148 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzynwRk7BUYkQBR4S8g:-KzynwRk7BUYkQBR4S8h:b-gh35a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L148)):*
> ```Go
> }
> 
> func (e *encodedArrayIterator) nextEncoded() (ok bool, nextJEntry uint32, next []byte, err error) {
> ```

i think usually the `ok` should come at the end, not the beginning. maybe right before error. Also perhaps you should name it `hasNext`or something? I guess it's really `hasCurrent` so maybe ok is fine.

---

*[pkg/util/json/encoded.go, line 153 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzym663z34WgtjnabiG:-Kzym663z34WgtjnabiH:b-yuw4dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L153)):*
> ```Go
> 	}
> 
> 	nextJEntry, err = getUint32At(e.data, 4+e.idx*4)
> ```

Please remove these magic numbers

---

*[pkg/util/json/encoded.go, line 172 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzymBf2BtK-LzYvrKZJ:-KzymBf2BtK-LzYvrKZK:bczujrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L172)):*
> ```Go
> 
> 	return encodedArrayIterator{
> 		curDataIdx: 4 + j.containerLen*4,
> ```

Please remove these magick numbers

---

*[pkg/util/json/encoded.go, line 192 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzzCklhsAHPeerdqtxp:-KzzCklhsAHPeerdqtxq:b-7mvy2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L192)):*
> ```Go
> 	}
> 
> 	nextKeyJEntry, err := getUint32At(e.data, 4+e.idx*4)
> ```

magic

---

*[pkg/util/json/encoded.go, line 199 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzzClzFGjUvpX-Xw1tM:-KzzClzFGjUvpX-Xw1tN:b-7mvy2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L199)):*
> ```Go
> 	nextKeyData := e.data[e.curKeyIdx : e.curKeyIdx+nextKeyLen]
> 
> 	nextValueJEntry, err := getUint32At(e.data, 4+(e.idx+e.len)*4)
> ```

magic

---

*[pkg/util/json/encoded.go, line 219 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzymKQB8PF272yrctit:-KzymKQB8PF272yrctiu:bazf1v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L219)):*
> ```Go
> 	}
> 
> 	curKeyIdx := 4 + j.containerLen*4*2
> ```

such magick

---

*[pkg/util/json/encoded.go, line 224 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzz2JXTq0cOOcLO1REj:-Kzz2JXTq0cOOcLO1REk:bb9jlh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L224)):*
> ```Go
> 	// We have to seek to the start of the value data.
> 	for i := 0; i < j.containerLen; i++ {
> 		jEntry, err := getUint32At(j.value, 4+i*4)
> ```

slay the magic

---

*[pkg/util/json/encoded.go, line 265 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzymOKf0yJpBEZkrFxC:-KzymOKf0yJpBEZkrFxD:b4oe3r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L265)):*
> ```Go
> }
> 
> // TODO(justin): this is quite slow as it requires a linear scan - implement the length/offset distinction in
> ```

nit: comment line length is too large

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-:-Kzz2NCQe2SnlOxsYGNO:bo9ui6n)*

**Comment by justinj** [comment]
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/builtins/generator_builtins.go, line 422 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyl_9-ghDueIAnIYiY:-L-7N8y5DLIFkFRk1K2k:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/sql/sem/builtins/generator_builtins.go#L422)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

If you made Start() just decode the entire value it would be fast. Seems like a reasonable tradeoff no?
</blockquote></details>

:+1:

---

*[pkg/util/json/contains.go, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyRPHk7BW0GfeUhUy0:-L-7OaHZuz5PrAxApbiY:b-4n0gmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a10cd147a46b08be70cf96b7dca14b28df01b755/pkg/util/json/contains.go#L161)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

fyi: you could use := and not declare the c. but this really doesn't matter
</blockquote></details>

Naw we need to be able to use the `err` from the enclosing scope :(

---

*[pkg/util/json/encoded.go, line 18 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyjuK_7YEah1cegH3-:-L-7Okj2NdIx_OQ3K11d:b-6czsx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L18)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

When you described this feature I was envisioning that you'd have a pointer to a JSON to cache the results of decode. Otherwise, you'll probably end up decoding more than once a lot of the time. Is there a reason you didn't include that? 
</blockquote></details>

Done as discussed on Slack!

---

*[pkg/util/json/encoded.go, line 53 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzygrqHAnNAz9k05O_2:-L-7Pn0Ip7No1S3jXtpd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L53)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

maybe capture this value since you're using it again below
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 59 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyfg4eEIYdyEDNH-n3:-L-7Q4sNMMNj4PJ2fHOa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

4 is a magic number. i think we want a containerHeaderTypeLen.
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyfkY1JEqjb1Wu8WlY:-L-7QPENnGDA1dB3kA1I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L65)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

8 is also a magic number. containerHeaderTypeLen + jEntryTypeLen?
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 79 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyhErYMl8bGg_nJCqc:-L-CSQQA-bYV-cqiiIrR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L79)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: jEntry is used elsewhere
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyhKBZqiR7T7fU2bBG:-L-7QYrjbi8TQfnWy_Y_:bg1k777) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L99)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

capture this
</blockquote></details>

It's not actually reused - the other one extracts the length.

---

*[pkg/util/json/encoded.go, line 169 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzyfUP1fk-XOp6usq5d:-L-CVk2jzPPefJZElqzx:b-y9jrxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L169)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

i sense a DRY opportunity - don't we already have this enum somewhere?
</blockquote></details>

A merged PR that I have now rebased has obviated the need for this.

---

*[pkg/util/json/encoded.go, line 220 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyf92WOLTcpqnCoqwh:-L-CY5Jc5n9yIFNxVTAI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L220)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

could use fmt.Fprintf(&buf, ...) if you wanted
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 227 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzyl6Vlxybr2QDHKNkZ:-L-CY4zhY_cPIAOIrNBf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L227)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

All of these methods should say  e.g.`RemoveIndex implements the JSON interface.`
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 306 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzykpBckyJv2RPrMiX8:-L-CYEdrZpgbfb4RhVfM:blzczl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b4da96abb11cd8723526133836f5196853c2d5/pkg/util/json/encoded.go#L306)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Doesn't seem like JSON owns this method?
</blockquote></details>

It's in the JSON interface, I just added a comment for it.

---

*[pkg/util/json/encoded.go, line 148 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzynwRk7BUYkQBR4S8g:-L-CTO94TJZm3u8cic39:btfhexe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L148)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

i think usually the `ok` should come at the end, not the beginning. maybe right before error. Also perhaps you should name it `hasNext`or something? I guess it's really `hasCurrent` so maybe ok is fine.
</blockquote></details>

Done. I don't love `hasCurrent` for the verbosity, I considered `more`? But `ok` seems pretty idiomatic? Would you rather we had to check beforehand whether to call `nextEncoded`? I wish there was a more standard pattern for iterators in Go :(

---

*[pkg/util/json/encoded.go, line 153 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzym663z34WgtjnabiG:-L-CSfzF8Zty_cVxoQc_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L153)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Please remove these magic numbers
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 172 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzymBf2BtK-LzYvrKZJ:-L-CSgTDDVrxWli6W9LC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L172)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Please remove these magick numbers
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 192 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzzCklhsAHPeerdqtxp:-L-CSgslkFVPvWBF6ueg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L192)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

magic
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 199 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzzClzFGjUvpX-Xw1tM:-L-CShBGfxVP--H5owJM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L199)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

magic
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 219 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzymKQB8PF272yrctit:-L-CShhvUQZIQv-OpeV-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L219)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

such magick
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 224 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-Kzz2JXTq0cOOcLO1REj:-L-CSifXS-W-WYoMvTfe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L224)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

slay the magic
</blockquote></details>

Done.

---

*[pkg/util/json/encoded.go, line 265 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-KzymOKf0yJpBEZkrFxC:-L-CU8a0MZcUVGRq9_dC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94f13b661df6b6a4b0fe1503f947575fa2beee0/pkg/util/json/encoded.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: comment line length is too large
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r4, 2 of 7 files at r5, 6 of 6 files at r6, 1 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-:-L-DJxRdFBHzhiySY8F6:bnfp4nl)*

**Comment by justinj** [comment]
Some of the other functions could definitely be optimized, for example, by directly using the object/array iterators rather than decoding first. I think for this PR (and for contains especially) that's out of scope - there will be a decent amount of benchmarking required there in order to ensure that that's actually an improvement.

---

Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/util/json/contains.go, line 149 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-L-DK-SmgpBeeaEyLq_1:-L-DX9ETgw-cgp7Z5LHz:bcny3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d7aeabdc6c563840226f3dc5ff02c4ad8fd9e4/pkg/util/json/contains.go#L149)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

nit: maybe use containable? Containsable sounds a bit weird to me.
</blockquote></details>

This isn't really the right place for this since that's from an older PR, but I think `containsable` is better, since it's in service of implementing `contains`, not `contain`, like, it's `containsable` in that you can execute `contains` on it, even if that's not a real word? Does that seem reasonable?

---

*[pkg/util/json/contains.go, line 217 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-L-DJgC4thPIo7Puc4Ep:-L-DXQO1htbVJ_NK3NzV:b-esllql) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d7aeabdc6c563840226f3dc5ff02c4ad8fd9e4/pkg/util/json/contains.go#L217)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I think it would make sense to sort them and do a comparison especially if the arrays are large.
</blockquote></details>

This was discussed in the contains PR, but this doesn't work, since array containment is set containment (which is made more complex by arrays containing objects) if you have concerns about this or ideas for how to make it faster though please open an issue! There are quite a few subtleties to the semantics of contains as implemented by Postgres.

---

*[pkg/util/json/encoded.go, line 322 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-L-DRIjnNCAGXEv-XTB3:-L-DXv5cBCwokZiQMbuy:b-wyitag) ([raw file](https://github.com/cockroachdb/cockroach/blob/8507b860124714df4bcb36258c5a4d13b07b7b72/pkg/util/json/encoded.go#L322)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Key deletion within a JSON object? Do you mean for something like an upsert?
</blockquote></details>

the `-` operator as implemented by `RemoveKey` and `RemoveIndex`.

---

*[pkg/util/json/json.go, line 171 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-L-DQHu-uz_0_CLaNxFa:-L-DgqMH4Fm7Zx8clXHP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8507b860124714df4bcb36258c5a4d13b07b7b72/pkg/util/json/json.go#L171)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

The block looks copied/pasted 4 times, it would be good to make it a function. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-:-L-DWwzd_ZaZkcGC5vsF:b-h5l2cj)*

**Comment by m-schneider** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217#-:-L-E5bQl4M5-2es2iFek:bg7igkv)*

**Comment by knz** [comment]
Reviewed 2 of 11 files at r1, 10 of 10 files at r4, 7 of 7 files at r5, 3 of 6 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20217)*

**Pull request merged**
