### PR TITLE
metric: add prev, next values in counter update panic

### PR DESCRIPTION
**Pull request by aadityasondhi**
This should help investigate potential bugs in metrics.

Informs #126470.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126583)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, and @nkodali)

___
*[`pkg/util/metric/metric.go` line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126583#-O0q__oyEzr8c7453DMa:-O0q__oyEzr8c7453DMb:b-m3j30f) ([raw file](https://github.com/cockroachdb/cockroach/blob/da054febfb9d4ed64aba12e196ded006265b506b/pkg/util/metric/metric.go#L756)):*
> ```Go
> func (c *Counter) Update(val int64) {
> 	if buildutil.CrdbTestBuild && val < c.count.Load() {
> 		panic(fmt.Sprintf("Counters should not decrease, prev: %d, new: %d.", c.count.Load(), val))
> ```

We should store the result of Load since it can change by the time we print.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126583)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @nkodali)

___
*[`pkg/util/metric/metric.go` line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126583#-O0q__oyEzr8c7453DMa:-O0srZnlECyoNCIWAXwf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da054febfb9d4ed64aba12e196ded006265b506b/pkg/util/metric/metric.go#L756)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should store the result of Load since it can change by the time we print.
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]

**Comment by RaduBerinde** [comment]
*[`pkg/util/metric/metric.go` line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126583#-O0q__oyEzr8c7453DMa:-O0t13cU6U1PBcR87pos:b-k2h8zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da054febfb9d4ed64aba12e196ded006265b506b/pkg/util/metric/metric.go#L756)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We shouldn't Load it unnecessarily either..

```go
if buildutil.CrdbTestBuild {
  if prev := c.count.Load(); val < prev { ... }
}
```

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126583)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @nkodali)

___
*[`pkg/util/metric/metric.go` line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126583#-O0q__oyEzr8c7453DMa:-O1I-d1A6fAkjI-XKs1w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da054febfb9d4ed64aba12e196ded006265b506b/pkg/util/metric/metric.go#L756)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We shouldn't Load it unnecessarily either..

```go
if buildutil.CrdbTestBuild {
  if prev := c.count.Load(); val < prev { ... }
}
```
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126583#-:-O1Ki5sX7AMi7rVdkp0G:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @nkodali)

**Review by aadityasondhi — COMMENTED** [review]
bors r=raduberinde

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126583#-:-O1N22zt9Wjedr_5DhaZ:b-y49i4j)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @nkodali)

**Pull request merged**
