### PR TITLE
storage: unify storage/fs.FS and pebble/vfs.FS

### PR DESCRIPTION
**Pull request by jbowens**
The storage/fs.FS had largely the same interface as vfs.FS. The storage/fs.FS interface was intended as a temporary stepping stone to using pebble's vfs.FS interface throughout Cockroach for all filesystem access. This commit unifies the two.

Epic: None
Release note: None

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
:lgtm: for sql queries changes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98776#-:-NQgcOpw4xw99yQImObr:b-ozhmr3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @RaduBerinde, and @tbg)

**Review by tbg — APPROVED** [review]
Thank you!
I'll defer to you on whether to merge this _after_ the branch cut. There doesn't seem to be a pressing reason to merge it before, and there might be a flake or two due to the changed sorting behavior in `List`.

**Review by jbowens — COMMENTED** [review]
TFTRs!

Yeah, I'll sit on this until the branch cut.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98776#-:-NQjqqkt5JrxTOeZZZHl:b-aezk02)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

**Comment by dt** [comment]
counter-arg: backports will be easier for the next year+ of supporting 23.1 if we merge before branch cut.

Can always revert if there's a flake.

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Pull request merged**
