### PR TITLE
opt: implement the rest of window functions

### PR DESCRIPTION
**Pull request by justinj**
With this series of commits, there are no unimplemented window function features, and all of the window function logic tests pass. The DISTINCT change is somewhat unrelated, but decided to clump it here because it justifies completely removing the big `if` I had for unimplemented features :)

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Exciting to have full support!!

r1 LGTM

some comments about r2. The "chaining" approach looks good to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-:-Lg8Yv0j3fZ5NEa3VMy5:bff3fx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/memo/interner.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-Lg8XKHUC9BTv8vRkDMk:-Lg8XKHV4MKRHSKj7U37:b-q58mgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6e7618a3edbe4203c5aab306e656fcbfe6d406/pkg/sql/opt/memo/interner.go#L486)):*
> ```Go
> }
> 
> func (h *hasher) HashWindowFrame(val *tree.WindowFrame) {
> ```

We are not hashing the OffsetExprs. I realize we don't care about those fields, but this is kind of unexpected. You might intern something and get something back that has different values in those fields. At the very least that could be very confusing during debugging (if you print out a WindowFrame).

We should at a minimum document it here (and IsWindowFrameEqual), though I believe in common usage one doesn't usually get this deep into the memo code. I think the right thing is to have our own version of WindowFrame that only has the WindowFrameMode and the start/end WindowFrameBoundTypes.

**Review by rytaft — APPROVED** [review]
[nit] do we need a release note for the first commit now that the functionality of using DISTINCT has changed?

Overall, :lgtm:. Chaining the start and end offsets feels a bit weird, but I don't really have a better solution. I think some additional comments would help to explain the chaining and why it's better than the alternative.

Nice work finishing this off!!

> Reviewed 3 of 3 files at r1, 12 of 12 files at r2, 12 of 12 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-:-Lg9RlPa54GZnuQrqe_J:b4ph5s4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1354 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-Lg9TPtI-b8ltTp6NWDs:-Lg9TPtI-b8ltTp6NWDt:b-ovh6ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6e7618a3edbe4203c5aab306e656fcbfe6d406/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1354)):*
> ```Go
> // extractFromOffset extracts the start bound expression of a window function
> // that uses the OFFSET windowing mode for its start bound.
> func (b *Builder) extractFromOffset(e opt.ScalarExpr) (opt.ScalarExpr, bool) {
> ```

[nit] maybe name this return param `ok` so it's clear what the boolean means (here and below)
___
*[pkg/sql/opt/optbuilder/scope.go, line 1030 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAhP01A5p_qIMyWlGp:-LgAhP01A5p_qIMyWlGq:b-fvau07) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1030)):*
> ```Go
> 	switch {
> 	case def.RefName != "":
> 		// SELECT rank() OVER (w) FROM t WINDOW w as (...)
> ```

[nit] as -> AS
___
*[pkg/sql/opt/optbuilder/scope.go, line 1038 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAjwTA42Sct6cJiZYX:-LgAhZR03-8J8GJUrcu6:b-jvyl1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1038)):*
> ```Go
> 		return &result
> 	case def.Name != "":
> 		// SELECT rank() OVER w FROM t WINDOW w as (...)
> ```

ditto

Also it's kind of hard to see the difference between this and the one above -- maybe call it out explicitly?
___
*[pkg/sql/opt/optbuilder/testdata/window, line 1375 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-Lg9rD-G77gDISD5Bk6b:-Lg9rD-G77gDISD5Bk6c:b-sp8yyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/487a4efeb79a845da8e25dc3f02295d2db13c948/pkg/sql/opt/optbuilder/testdata/window#L1375)):*
> ```
> 
> build
> SELECT count(*) FILTER (WHERE true) OVER (), count(*) FILTER (WHERE false) OVER () FROM kv
> ```

how about a test where you reuse the same filter

**Review by justinj — COMMENTED** [review]
Added some extra comments about the chaining. I'm not sold on it, and also it's a little messier than the aggregate version since we don't always have an argument to chain off of, so we have to chain on top of the function. That said I also think it's better than any alternative I can think of (short of us adding full-on ML-style variant types or something to optgen).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-:-LgT21EhDUyflNH9Acks:b-y96uit)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1354 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-Lg9TPtI-b8ltTp6NWDs:-LgSrA9NCGKqmQ4u29NC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6e7618a3edbe4203c5aab306e656fcbfe6d406/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1354)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] maybe name this return param `ok` so it's clear what the boolean means (here and below)
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/interner.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-Lg8XKHUC9BTv8vRkDMk:-LgSrB0E1NXU8Q9sC451:bj5kuey) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6e7618a3edbe4203c5aab306e656fcbfe6d406/pkg/sql/opt/memo/interner.go#L486)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are not hashing the OffsetExprs. I realize we don't care about those fields, but this is kind of unexpected. You might intern something and get something back that has different values in those fields. At the very least that could be very confusing during debugging (if you print out a WindowFrame).

We should at a minimum document it here (and IsWindowFrameEqual), though I believe in common usage one doesn't usually get this deep into the memo code. I think the right thing is to have our own version of WindowFrame that only has the WindowFrameMode and the start/end WindowFrameBoundTypes.
</blockquote></details>

Done. I made a new type. It made lots of stuff much simpler so I think it was definitely the right choice.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1030 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAhP01A5p_qIMyWlGp:-LgSrZIu9_Qwufsr2QLl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1030)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] as -> AS
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1038 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAjwTA42Sct6cJiZYX:-LgSrZqHDK5MW82LLNgy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1038)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto

Also it's kind of hard to see the difference between this and the one above -- maybe call it out explicitly?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/window, line 1375 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-Lg9rD-G77gDISD5Bk6b:-LgSx3fB08IRJEkYXPQB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/487a4efeb79a845da8e25dc3f02295d2db13c948/pkg/sql/opt/optbuilder/testdata/window#L1375)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

how about a test where you reuse the same filter
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 7 of 15 files at r6, 9 of 12 files at r7, 7 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-:-LgTiq3x4iYIRUov8pEY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1366 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgTgm8e1FqJTEK6w6IB:-LgTgm8e1FqJTEK6w6IC:b-9hk15e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3696cbba8703466b5b517e0f622da2a7b36504e4/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1366)):*
> ```Go
> // extractToOffset extracts the end bound expression of a window function
> // that uses the OFFSET windowing mode for its end bound.
> func (b *Builder) extractToOffset(e opt.ScalarExpr) (_ opt.ScalarExpr, _ bool) {
> ```

[nit] _ bool -> ok bool
___
*[pkg/sql/opt/ops/scalar.opt, line 935 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgThvBD1lWLId1bZFwo:-LgThvBD1lWLId1bZFwp:bdhukex) ([raw file](https://github.com/cockroachdb/cockroach/blob/3696cbba8703466b5b517e0f622da2a7b36504e4/pkg/sql/opt/ops/scalar.opt#L935)):*
> ```
>     # operators containing those expressions, similar to AggDistinct and
>     # AggFilter.
>     # This is a little clunky sometimes because it means that any time you want
> ```

[nit] add a line above this if it's supposed to be a new paragraph
___
*[pkg/sql/opt/optbuilder/scope.go, line 1030 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAhP01A5p_qIMyWlGp:-LgTiBMLBGhYLiaLFtlA:bqqal3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1030)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you changed it in `pkg/sql/window.go` but not here
___
*[pkg/sql/opt/optbuilder/scope.go, line 1038 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAjwTA42Sct6cJiZYX:-LgTiISEEGdBPE6xzyJ8:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1038)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same as above

**Review by justinj — COMMENTED** [review]
cc @RaduBerinde did you have any more comments on this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-:-LgcmIdy6jE9wWRJPEdw:bxw1nln)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1366 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgTgm8e1FqJTEK6w6IB:-LgclfjE-dFt6dFdse59:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3696cbba8703466b5b517e0f622da2a7b36504e4/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1366)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] _ bool -> ok bool
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 935 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgThvBD1lWLId1bZFwo:-LgclfBbDupjIS0Occ1D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3696cbba8703466b5b517e0f622da2a7b36504e4/pkg/sql/opt/ops/scalar.opt#L935)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] add a line above this if it's supposed to be a new paragraph
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1030 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAhP01A5p_qIMyWlGp:-Lgclsn11Pjl_5Ojrr18:bc5a45h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1030)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Looks like you changed it in `pkg/sql/window.go` but not here
</blockquote></details>

Oops! Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1038 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37912#-LgAjwTA42Sct6cJiZYX:-LgcltxlC5UHTjcwivnz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd31484845a74a46a53019a927e16396e2b49c30/pkg/sql/opt/optbuilder/scope.go#L1038)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 7 of 15 files at r10, 9 of 12 files at r11, 7 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37912)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by justinj** [comment]
I'm eager to merge this since there are 4 commits. We can address any follow-up comments afterward.

bors r+

**Comment by RaduBerinde** [comment]
Sorry for the delay, LGTM!

**Pull request merged**
