### PR TITLE
colexec: add partially ordered distinct

### LINKED ISSUE #43562: colexec: implement distinct on partially ordered columns
With #42522 being merged (hopefully) soon, we should implement specialized distinct operator on partially ordered columns. Unordered distinct doesn't take into account whether we have partially ordered input and buffers it up fully, but specialized operator could divide the stream of tuples from the input in several "chunks." The chunks will contain all tuples that are equal on already ordered columns, allowing us to buffer less tuples at a time.

I think this operator could be implemented as a combination of `chunker` (used in sort chunks) and `unorderedDistinct`.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix null handling in sort chunks**

Previously, `tuplesDiffer` function (which checks whether a value in one
colvec differs from a value in another colvec) didn't pay attention to
NULLs which is wrong. This could cause sortChunksOp to incorrectly find
the boundaries of the chunks. Now this is fixed, as well as
`tuples_differ` has been renamed to `values_differ` as it describes it
better. The likelihood of such occurrence is very low, and out tests
never caught this (I believe eventually it would have since we now
randomize coldata.BatchSize) due to fixed number of rows with which we
had only a single input batch.

Release note: None (no release note since this bug could only be hit
with vectorize=experimental_on up until few days ago).

**colexec: add partially ordered distinct**
This commit adds a specialized distinct operator for the case when we
have partial ordering on the distinct columns. It uses newly added
chunkerOperator (which is an adapter from chunker spooler to Operator,
it returns all tuples that belong to the same "chunk" - i.e. those
equal on the already ordered columns - followed by zero-length batches
until it is reset) and unorderedDistinct on the tuples from the same
"chunk" (with its distinct columns being the subset of the original
distinct columns that is not included in the ordered columns). Both of
these operators are reset when a chunk is processed.

Unfortunately, the benchmarks have shown that this partially ordered
distinct operator is better than pure unordered distinct only when the
fraction of distinct tuples coming from the input is on the order of
0.01. When that fraction is exceeded, then the performance degrades
significantly because we spend most of the times resetting the hash
table used by unordered distinct. Therefore, currently this newly
introduced operator is not planned.

I still think that it is beneficial to merge this commit because,
hopefully, in the future we will estimate this fraction at runtime and
will be able to plan it if it'd be worth it.

Fixes: #43562.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks:
```
BenchmarkDistinct/Unordered/newTupleProbability=0.001/rows=4096/cols=2/ordCols=0-16         	    2432	    456268 ns/op	 143.63 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.001/rows=4096/cols=2/ordCols=1-16  	    4602	    266471 ns/op	 245.94 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.001/rows=4096/cols=2/ordCols=2-16           	   40654	     29439 ns/op	2226.18 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.001/rows=4096/cols=4/ordCols=0-16         	    1622	    695298 ns/op	 188.51 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.001/rows=4096/cols=4/ordCols=2-16  	    2948	    403556 ns/op	 324.79 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.001/rows=4096/cols=4/ordCols=4-16           	   22278	     53477 ns/op	2451.01 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.001/rows=65536/cols=2/ordCols=0-16        	     234	   5048565 ns/op	 207.70 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.001/rows=65536/cols=2/ordCols=1-16 	     316	   3728160 ns/op	 281.26 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.001/rows=65536/cols=2/ordCols=2-16          	    3103	    393596 ns/op	2664.09 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.001/rows=65536/cols=4/ordCols=0-16        	     100	  10048637 ns/op	 208.70 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.001/rows=65536/cols=4/ordCols=2-16 	     212	   5562934 ns/op	 376.99 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.001/rows=65536/cols=4/ordCols=4-16          	    1614	    738541 ns/op	2839.59 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.010/rows=4096/cols=2/ordCols=0-16         	    3264	    338177 ns/op	 193.79 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.010/rows=4096/cols=2/ordCols=1-16  	    4406	    277117 ns/op	 236.49 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.010/rows=4096/cols=2/ordCols=2-16           	   40519	     29507 ns/op	2221.02 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.010/rows=4096/cols=4/ordCols=0-16         	    2373	    488374 ns/op	 268.38 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.010/rows=4096/cols=4/ordCols=2-16  	    2564	    457780 ns/op	 286.32 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.010/rows=4096/cols=4/ordCols=4-16           	   22576	     53733 ns/op	2439.30 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.010/rows=65536/cols=2/ordCols=0-16        	     266	   4421739 ns/op	 237.14 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.010/rows=65536/cols=2/ordCols=1-16 	     294	   4029216 ns/op	 260.24 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.010/rows=65536/cols=2/ordCols=2-16          	    3018	    396986 ns/op	2641.34 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.010/rows=65536/cols=4/ordCols=0-16        	     170	   6966064 ns/op	 301.05 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.010/rows=65536/cols=4/ordCols=2-16 	     192	   6207943 ns/op	 337.82 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.010/rows=65536/cols=4/ordCols=4-16          	    1623	    742469 ns/op	2824.56 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.100/rows=4096/cols=2/ordCols=0-16         	    3684	    325607 ns/op	 201.27 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.100/rows=4096/cols=2/ordCols=1-16  	    1633	    695183 ns/op	  94.27 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.100/rows=4096/cols=2/ordCols=2-16           	   40867	     29655 ns/op	2209.97 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.100/rows=4096/cols=4/ordCols=0-16         	    2455	    468970 ns/op	 279.49 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.100/rows=4096/cols=4/ordCols=2-16  	    1076	   1103141 ns/op	 118.82 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.100/rows=4096/cols=4/ordCols=4-16           	   22288	     53326 ns/op	2457.95 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.100/rows=65536/cols=2/ordCols=0-16        	     259	   4599660 ns/op	 227.97 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.100/rows=65536/cols=2/ordCols=1-16 	     100	  11687784 ns/op	  89.72 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.100/rows=65536/cols=2/ordCols=2-16          	    2989	    398086 ns/op	2634.04 MB/s
BenchmarkDistinct/Unordered/newTupleProbability=0.100/rows=65536/cols=4/ordCols=0-16        	     163	   7320267 ns/op	 286.49 MB/s
BenchmarkDistinct/PartiallyOrdered/newTupleProbability=0.100/rows=65536/cols=4/ordCols=2-16 	      67	  17863443 ns/op	 117.40 MB/s
BenchmarkDistinct/Ordered/newTupleProbability=0.100/rows=65536/cols=4/ordCols=4-16          	    1572	    737735 ns/op	2842.69 MB/s
```

**Review by asubiotto — APPROVED** [review]
The approach :lgtm: Do you expect @azhng 's work to reduce the unordered distinct should make this partially ordered distinct much better in comparison?

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-:-M1Cf69-03TR9AZ_-_T2:b-pmlx1g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @yuzefovich)

___
*[pkg/sql/colexec/distinct_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1CgzEe4gIq6Di96Zsc:-M1CgzEe4gIq6Di96Zsd:bdc0v07) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7e7da3e3914aba02cf67b05af91e37a623651d/pkg/sql/colexec/distinct_test.go#L133)):*
> ```Go
> 				})
> 			}
> 			t.Run("ordered", func(t *testing.T) {
> ```

Does this mean we only run two tests with the ordered distinct now? If I understand correctly, why not just assume that all test cases are ordered on distinct columns and run all of the distincts on the input?
___
*[pkg/sql/colexec/partially_ordered_distinct.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1ChpFqA-5AWkhrCTSA:-M1ChpFr8LULDZ6aoYd8:b-210x3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7e7da3e3914aba02cf67b05af91e37a623651d/pkg/sql/colexec/partially_ordered_distinct.go#L36)):*
> ```Go
> ) (Operator, error) {
> 	if len(orderedCols) == 0 || len(orderedCols) == len(distinctCols) {
> 		execerror.VectorizedInternalPanic(fmt.Sprintf(
> ```

I still don't 100% understand why we want to panic in these cases instead of returning an error.

**Review by yuzefovich — COMMENTED** [review]
That's my hope - that we will be able to plan this `partiallyOrderedDistinct` always when we have partial ordering.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-:-M1CpQVu6MGufBpZ6Kox:b-p89npa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colexec/distinct_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1CgzEe4gIq6Di96Zsc:-M1Cnbwy0ElN-W4z9OXu:b-lle6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7e7da3e3914aba02cf67b05af91e37a623651d/pkg/sql/colexec/distinct_test.go#L133)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this mean we only run two tests with the ordered distinct now? If I understand correctly, why not just assume that all test cases are ordered on distinct columns and run all of the distincts on the input?
</blockquote></details>

There is `TestDistinctAgainstProcessor` test which in my mind is a lot more powerful than these unit tests. Then, the three unit tests were already present, and one of them actually had a bug in it - the input tuples are not ordered on distinct columns, so it is not valid to expect `orderedDistinct` to work in such scenario. It just so happened that it worked for the ordered distinct, but it doesn't for partially ordered. I think it is still beneficial to have a test in which the input is not ordered as a unit test of `unordered_distinct`.
___
*[pkg/sql/colexec/partially_ordered_distinct.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1ChpFqA-5AWkhrCTSA:-M1CoqiY-mQg2JqqATQk:bwl3tn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7e7da3e3914aba02cf67b05af91e37a623651d/pkg/sql/colexec/partially_ordered_distinct.go#L36)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I still don't 100% understand why we want to panic in these cases instead of returning an error.
</blockquote></details>

Changed to failing the assertion. I believe that is an unexpected situation if we're trying to create a partially ordered distinct when either the input is not ordered (unordered distinct should be planned) or fully ordered (ordered distinct should be). Such scenario indicates that something in the planning code is messed up, and I'd like to see it right away to be exposed in tests. If we simply return an error, it is possible that the error will be consumed and we will fall back to row-by-row engine which will hide the problem in the vectorized planning.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44886)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @yuzefovich)

___
*[pkg/sql/colexec/partially_ordered_distinct.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1ChpFqA-5AWkhrCTSA:-M1H2UwB1n94K9TlN0Tq:b-xr5xqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7e7da3e3914aba02cf67b05af91e37a623651d/pkg/sql/colexec/partially_ordered_distinct.go#L36)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Changed to failing the assertion. I believe that is an unexpected situation if we're trying to create a partially ordered distinct when either the input is not ordered (unordered distinct should be planned) or fully ordered (ordered distinct should be). Such scenario indicates that something in the planning code is messed up, and I'd like to see it right away to be exposed in tests. If we simply return an error, it is possible that the error will be consumed and we will fall back to row-by-row engine which will hide the problem in the vectorized planning.
</blockquote></details>

That makes sense, but don't we catch panics and return an error anyway?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44886)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colexec/partially_ordered_distinct.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1ChpFqA-5AWkhrCTSA:-M1LnUdgAiXBn_hl-qL3:b-13wqw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7e7da3e3914aba02cf67b05af91e37a623651d/pkg/sql/colexec/partially_ordered_distinct.go#L36)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That makes sense, but don't we catch panics and return an error anyway?
</blockquote></details>

Yes, we do. I guess I hope that when we return the error, it'll be more "screaming" or something lol. I think that maybe having `AssertionFailed` in the code also indicates to the reader of the code that this is truly unexpected situation.

**Comment by yuzefovich** [comment]
Hm, this PR has been consistently failing the CI build (I believe due to a timeout). I bumped the timeout from 20 minutes to 30 minutes, and the build is green. Are we ok with this bump? cc @jordanlewis

**Comment by jordanlewis** [comment]
Yes, that's fine.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by nvanbenschoten** [comment]
The bors batch just hit [the following error](https://teamcity.cockroachdb.com/viewLog.html?buildId=1780022&buildTypeId=Cockroach_UnitTests&fromExperimentalUI=true), which looks closely related to this change:
```
=== RUN   TestLogic/fakedist/cascade/UpdateSetDefault_Unique
rewrote:
CREATE TABLE a (id STRING PRIMARY KEY);
CREATE TABLE b (id STRING PRIMARY KEY, a_id STRING UNIQUE DEFAULT 'default' REFERENCES a ON UPDATE SET DEFAULT, FAMILY (a_id, id));


SIGQUIT: quit
PC=0x25dfe4b m=0 sigcode=0

goroutine 3305337 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*chunker).prepareNextChunks(0xc026716f00, 0x4276ec0, 0xc02b450740, 0x7f14c53eefff)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort_chunks.go:378 +0x5b fp=0xc00c2f5850 sp=0xc00c2f57a8 pc=0x25dfe4b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*chunker).spool(0xc026716f00, 0x4276ec0, 0xc02b450740)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort_chunks.go:427 +0x3f fp=0xc00c2f5880 sp=0xc00c2f5850 pc=0x25e071f
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*sortOp).Next(0xc05486fc80, 0x4276ec0, 0xc02b450740, 0x20, 0x18)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:268 +0x337 fp=0xc00c2f5968 sp=0xc00c2f5880 pc=0x25de2d7
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*sortChunksOp).Next(0xc02b450ac0, 0x4276ec0, 0xc02b450740, 0x68ff5a, 0xc0000b2380)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort_chunks.go:93 +0x6e fp=0xc00c2f59b0 sp=0xc00c2f5968 pc=0x25df52e
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:211 +0x4e fp=0xc00c2f59f0 sp=0xc00c2f59b0 pc=0x25f888e
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror.CatchVectorizedRuntimeError(0xc00c2f5aa0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:91 +0x5f fp=0xc00c2f5a40 sp=0xc00c2f59f0 pc=0x1e2b3cf
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next(0xc04f4e4e70, 0x4276ec0, 0xc02b450740, 0x5, 0x400)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:209 +0xa2 fp=0xc00c2f5ad8 sp=0xc00c2f5a40 pc=0x1ee9ca2
github.com/cockroachdb/cockroach/pkg/sql/colexec.invariantsChecker.Next(0x4279d40, 0xc04f4e4e70, 0x3, 0x4276ec0, 0xc02b450740, 0x42da7a0, 0xc02b451180)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:45 +0x63 fp=0xc00c2f5b80 sp=0xc00c2f5ad8 pc=0x1f4dd43
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next(0xc0549ec5a0, 0x4276ec0, 0xc02b450740, 0x0, 0x7f14b93c9c98)
	<autogenerated>:1 +0x62 fp=0xc00c2f5bc8 sp=0xc00c2f5b80 pc=0x2687b42
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*deselectorOp).Next(0xc019e7a3c0, 0x4276ec0, 0xc02b450740, 0x68ff5a, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/deselector.go:51 +0x73 fp=0xc00c2f5c60 sp=0xc00c2f5bc8 pc=0x1ee9393
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).sendBatches.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:220 +0x5f fp=0xc00c2f5ca0 sp=0xc00c2f5c60 pc=0x27da4af
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror.CatchVectorizedRuntimeError(0xc00c2f5da0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:91 +0x5f fp=0xc00c2f5cf0 sp=0xc00c2f5ca0 pc=0x1e2b3cf
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).sendBatches(0xc043834870, 0x4276f80, 0xc02f090f90, 0x7f14aef81b58, 0xc02cda0d80, 0xc02cda0bc0, 0xc043834870, 0xc044ec99e0, 0x66bd95)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:227 +0xbb fp=0xc00c2f5dd0 sp=0xc00c2f5cf0 pc=0x27d962b
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).runWithStream(0xc043834870, 0x4276f80, 0xc02f090f90, 0x7f14aef81b58, 0xc02cda0d80, 0xc02cda0bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:307 +0x104 fp=0xc00c2f5e48 sp=0xc00c2f5dd0 pc=0x27da0a4
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).Run(0xc043834870, 0x4276ec0, 0xc02b450740, 0x4201320, 0xc02f096c80, 0x69b0163800000001, 0xfd6019ae134396a3, 0x21f4280b, 0x3, 0xc02cda0bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:167 +0x586 fp=0xc00c2f5f18 sp=0xc00c2f5e48 pc=0x27d9276
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRemoteOutputStream.func1(0x4276ec0, 0xc02b450740, 0xc02cda0bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:529 +0x9a fp=0xc00c2f5f90 sp=0xc00c2f5f18 pc=0x27e392a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(0xc0549ec700, 0x4276ec0, 0xc02b450740, 0xc02cda0bc0, 0xc0552b2670)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1073 +0x44 fp=0xc00c2f5fb8 sp=0xc00c2f5f90 pc=0x27e3ce4
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00c2f5fc0 sp=0xc00c2f5fb8 pc=0x6c11a1
created by github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1072 +0x6f
```
I'd recommend canceling the bors invocation if you think this could be related.

**Comment by yuzefovich** [comment]
bors r-

Hm, I thought it was a timeout, but it seems like there is a deadlock :/

**Comment by nvanbenschoten** [comment]
> Hm, I thought it was a timeout, but it seems like there is a deadlock :/

Was that the reason for the second commit? Is it still needed?

**Comment by yuzefovich** [comment]
> Was that the reason for the second commit? Is it still needed?

Yeah, I saw a build fail a couple of times and on quick glance it seemed like a test timeout, so I bumped the timeout limit, and the build was green. I guess this deadlock is random, and it just so happened that on two builds that I had with bumped timeout the deadlock didn't occur.

I'll investigate this issue later.

**Comment by yuzefovich** [comment]
I believe I found the problem with my refactor of `chunkerSpooler` so it could get stuck in an infinite loop in `prepareNextChunks` call (which is confirmed by the stack trace). Pushed the fix and rerunning CI to confirm.

**Comment by yuzefovich** [comment]
I found a bug with null handling in `chunker`, so I added the fix to that as a preliminary commit in this PR. Please take another look.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44886)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 357 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1aCUKR8UBDlUZMrQqS:-M1aCUKR8UBDlUZMrQqT:bnry84) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36c8363865cf6bd70b7b0deea6dd7d3ef3e563b/pkg/sql/distsql/columnar_operators_test.go#L357)):*
> ```Go
> 	rng := rand.New(rand.NewSource(int64(seed)))
> 	nRuns := 5
> 	nRows := 5 / 4 * coldata.BatchSize()
> ```

Do you mean `(4*coldata.BatchSize)/nRuns`? This will be 0 most of the time I think

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44886)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 357 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-M1aCUKR8UBDlUZMrQqS:-M1aPofX9z5SAS8GicJq:b-oy8jhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36c8363865cf6bd70b7b0deea6dd7d3ef3e563b/pkg/sql/distsql/columnar_operators_test.go#L357)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do you mean `(4*coldata.BatchSize)/nRuns`? This will be 0 most of the time I think
</blockquote></details>

No, I meant five fourths of the batch size (so that we always have at least two batches). I think it would have always evaluated to `coldata.BatchSize()`, so I changed the order of operands.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 13 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44886#-:-M1ajlr1Cv9Fd8WdVTNk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
