### PR TITLE
cli,ts: allow (hacky) visualization of timeseries dumps

### PR DESCRIPTION
**Pull request by tbg**
One of our observability achilles heels has always been that time series
are not included in `debug.zip`. But let's aim lower, they're also not
included in roachtest artifacts. This PR tries to address at least the
latter, and opens up a potential interim solution for the former.

We actually have had the ability to export time series from a cluster
for quite some time, and have recently improved it in #57481. However,
the real problem is visualizing the data. We have something that allows
you to [explore] a dump, but it's unusable until we also do #54178,
which isn't going to happen anytime soon.

For better or worse, in the short term, the most attractive way to get
the data visualized is to dump raw KV pairs into a local cockroachdb
instance and open the DB console.

That's what this commit achieves. Here's a "demo":

```
./cockroach debug tsdump --format raw --insecure \
    --host $(roachprod ip --external tobias-ui: 1) > ts.gob
```

```
COCKROACH_DEBUG_TS_IMPORT_FILE=ts.gob ./cockroach start-single-node --insecure
```

Open the UI and browse:

image

We anticipate trying this out in `roachtest`. It's unclear if it will
ever be included in `debug.zip`, but it seems worthwhile given that
our real solution - the observability server - is a ways out.

There are gotchas.

- the code behind COCKROACH_DEBUG_TS_IMPORT_FILE has to make all kinds of
assumptions about which node each store belongs to and in practice this
means that unless each node has exactly one store, and the IDs match,
the operation will either fail or produce an incorrect mapping,
silently.  What's worse, if this conflicts with the actual running node,
the running node's opinion will win (so things might look at at first,
then flip around, not sure).
- some metrics are missing, see #64373. I think everything except the latency
metrics are there, such as `sql.txn.latency-*`.
- to get the console to even realize these metrics are there, we have to
write fake NodeStatuses. Definitely don't use this on any cluster you
care about.

Given those, the only situation in which I will personally use this is
that of a vanilla roachtest, where NodeIDs and StoreIDs line up nicely.

[explore]: https://github.com/cockroachdb/cockroach/blob/master/scripts/localmetrics/README.md

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Very elegant, very straightforward. I like it!

A few nits and this will be good to go.

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64329#-:-MZOF3hS32hoUrNoKnWR:b-5jsmbt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cli/demo.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64329#-MZOEpeW5PnEEs4UuFDh:-MZOEpeX6dJMZ-6HZpIG:b-zc7wam) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ac14b1c948bd21a67a260eeecb173414574c3a/pkg/cli/demo.go#L52)):*
> ```Go
> `,
> 	Example: `  cockroach demo`,
> 	Args:    cobra.RangeArgs(0, 1),
> ```

Can you change this to accept a flag instead. We already have `demo` sub-commands (one per workload) and this interferes with that.
___
*[pkg/cli/demo.go, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64329#-MZOEzixAgp3Lsmz6Bcc:-MZOEzixAgp3Lsmz6Bcd:bikdt65) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ac14b1c948bd21a67a260eeecb173414574c3a/pkg/cli/demo.go#L302)):*
> ```Go
> 
> 	if tsImport != "" {
> 		f, err := os.Open(tsImport)
> ```

please extract this in a separate function

**Comment by knz** [comment]
Is it possible to have the import done using an RPC instead of direct access to the server object? This way we could also do it for a running server.

**Comment by tbg** [comment]
I re-worked this a bit and in doing so highlighted why this isn't as elegant as it may first seem. The issue is that from the data we get, we can't figure out which storeIDs and nodeIDs belong together. The NodeStatus is how the UI figures out how to aggregate the timeseries corresponding to storeIDs (or so I assume, it seems to work now that I'm writing fake NodeStatuses). What I have here works and it gets the job done, but only under very specific circumstances. There are also some metrics that are missing, see #64373.

I think this is about as good as it gets as a first step, and provides some lessons for the observability server / a more general decoupling of the console from the DB, the biggest one being that the store -> node mappings need to be remembered alongside the actual time series.

> Is it possible to have the import done using an RPC instead of direct access to the server object? This way we could also do it for a running server.

Anything is possible (but no such RPC exists), but if you look at the current code, I think you might agree that it's going to be more work than I will be able to provide here. Given the caveats, I think we are far from using this in a production setting, and so I would even caution against wanting to do this against any running server.

**Review by knz — COMMENTED** [review]
I see what you've done here.

Does this mean what everything will go haywire if we start a cluster with multiple nodes with the env var set?

If so, we'll want an interlock to prevent `cockroach nodes` being started with a value for `--nodes` greater than 1 if the env var is set.

> Reviewed 2 of 3 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64329#-:-M_0aOhF51UsfayjJgd_:b4ni4d0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
> Does this mean what everything will go haywire if we start a cluster with multiple nodes with the env var set?

It should be fairly hard to hold it wrong, at least with the latest set of small updates:

1. env var is only ever used in `start-single-node`
2. it errors out when trying to import into an existing cluster
3. or when you try to pass more than one store

So really the only way to use this is `COCKROACH_DEBUG_TS_IMPORT_FILE=x ./cockroach start-single-node` when the store doesn't yet exist.

**Review by knz — APPROVED** [review]
Ok the code change looks LGTM.

Any way we could have a test that checks that _some_ data is being imported? (no need to make it thorough)
I would just like something that asserts the functionality is not accidentally removed.

> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64329#-:-M_5Yerd0EoRwdT9vdIs:b-mtmvmi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
👍🏽 Added a test, PTAL

**Review by knz — APPROVED** [review]
Test LGTM but I think CI is trying to tell you something

> Reviewed 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64329#-:-M_6DqJ78vfVlZrK7cLM:b-yrzckn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/ts/util.go, line 12 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/64329#-M_6DhNbCZKCeezZacq_:-M_6DhNbCZKCeezZacqa:b-lvsfrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b5b49cf4ae0b61946d478400d8190b7074930a6/pkg/ts/util.go#L12)):*
> ```Go
> // DumpRawTo is a helper that gob-encodes all messages received from the
> // source stream to the given WriteCloser.
> func DumpRawTo(src tspb.TimeSeries_DumpRawClient, out io.WriteCloser) error {
> ```

this can be an `io.Writer` since you're not using Close

**Comment by tbg** [comment]
bors r=knz
TFTR!

**Pull request merged**
