### PR TITLE
test_certs: generate test certs for tenant 2

### PR DESCRIPTION
**Pull request by adityamaru**
In soon to be c2c tests we will be creating the destination tenant by name instead of ID and allow the CRDB to assign us the first available tenant ID. This ID in the absence of other tenants is 2, and so it is helpful to have the certs of tenant 2 embedded so that we can run queries against the tenant post cutover.

This change adds tenant 2 to the embedded test certs.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Alternative: allow name-scoped client certs. @stevendanna can explain.

**Comment by stevendanna** [comment]
@adityamaru and I talked. We definitely will want to take on named-scoped client certs in the nearish term.  Our thinking is that we move forward with this so that the team doing CREATE TENANT work can continue. I'll likely pick up named-scoped client certs later this month.

**Comment by adityamaru** [comment]
If we're cool with this as a stop-gap can I get a stamp please 😃 CI failure is https://github.com/cockroachdb/cockroach/issues/91919

**Review by knz — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=knz

**Pull request merged**
