### PR TITLE
sql: don't panic when rolling back from state RestartWait

### LINKED ISSUE #5744: sql: panic on rollbackSQLTransaction with non-open txn
I got the following crash when killing a load generator app.

```
panic: rollbackSQLTransaction called on non-open txn: &{db:{sender:0xc8202dc160 userPriority:1 txnRetryOptions:{InitialBackoff:50000000 MaxBackoff:5000000000 Multiplier:2 MaxRetries:0 RandomizationFactor:0 Closer:<nil>}} wrapped:0xc820378e40 Proto:"sql/executor.go:380 sql txn" id=42e8c764 key=/Table/51/1/1/2/1 rw=true pri=0.00170982 iso=SERIALIZABLE stat=PENDING epo=1 ts=1459375813.964082583,1 orig=1459375813.964082583,1 max=1459375814.207097056,0 wto=false UserPriority:NORMAL Context:context.Background.WithCancel CollectedSpans:[] systemConfigTrigger:false retrying:false finalized:false}

goroutine 6503 [running]:
panic(0x4edbfa0, 0xc8206edf10)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql.rollbackSQLTransaction(0xc8207fc828, 0xc8207fc878, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:813 +0x1cf
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInAbortedTxn(0xc8202241c0, 0x7acf2c0, 0x5dd3b78, 0xc8207fc828, 0xc8207fc878, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:603 +0x166
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8202241c0, 0xc8206edc40, 0x1, 0x1, 0xc8207fc878, 0xc8207fc828, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:558 +0xbbb
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8202241c0, 0xc8207fc878, 0x3, 0xc8207fc828, 0xc8207497a0, 0xc8206edc40, 0x1, 0x1, 0xc820a093a0, 0xc820a093b8, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:488 +0x147
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc8202dc160, 0xc8207497a0, 0xc8208b9c80)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:401 +0x325
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc8202dc160, 0x55d0000, 0x0, 0x0, 0xc820a094f8, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/client/txn.go:531 +0x410
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8202241c0, 0x7a059d0, 0xc820644340, 0xc8207fc800, 0xc8207be137, 0x8, 0x0, 0x0, 0x0, 0x7a50d00)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:405 +0x892
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8202241c0, 0x7a059d0, 0xc820644340, 0xc8207fc800, 0xc8207be137, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:295 +0xe2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc8202f4600, 0x7a059d0, 0xc820644340, 0xc8207be137, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:604 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc8202f4600, 0x7a059d0, 0xc820644340, 0xc8202f4628, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:314 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc8202f4600, 0x0, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:270 +0x10d3
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8202c7e58, 0x7a083d8, 0xc820241810, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:159 +0x929
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x7a083d8, 0xc820241810)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/server/server.go:300 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820140600, 0x7a083d8, 0xc820241810, 0xc820200020)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #5744

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5802)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/executor.go, line 813 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRcKZl2hhZ1Iqs0-Z:-KEHRcKZl2hhZ1Iqs0-_:-1121685380) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/executor.go#L813)):*
does this really need to be +v? We should define a useful String method if the existing one is not useful.

---

*[sql/txn_restart_test.go, line 664 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRUo3cofcwcXSxC3F:-KEHRUo3cofcwcXSxC3G:735089416) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L664)):*
prefer `:=`

---

*[sql/txn_restart_test.go, line 665 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRTTOslMinmqHyFYQ:-KEHRTTOslMinmqHyFYR:-435464181) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L665)):*
weird line break

---

*[sql/txn_restart_test.go, line 668 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRWRSeut5EVfbXKfu:-KEHRWRSeut5EVfbXKfv:-1264023629) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L668)):*
inline below and prefer `:=`

---

*[sql/txn_restart_test.go, line 676 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRY8xX5JyI9E6trd0:-KEHRY8yr8V7X3AMnWY1:677416866) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L676)):*
`:=`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-:-KEHRaYlcVHwS0Q2F6gv:1417088721)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/executor.go, line 813 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRcKZl2hhZ1Iqs0-Z:-KEHmrtS3E5G3lekpqip:1027903287) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/executor.go#L813)):*
Done. The proto has a String().

---

*[sql/txn_restart_test.go, line 664 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRUo3cofcwcXSxC3F:-KEHoI9xkSpP0vVPYtmd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L664)):*
Done.

---

*[sql/txn_restart_test.go, line 665 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRTTOslMinmqHyFYQ:-KEHoITZkq3engWazn5g:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L665)):*
Done.

---

*[sql/txn_restart_test.go, line 668 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRWRSeut5EVfbXKfu:-KEHoIi8cT7EegGM4XqE:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L668)):*
done

---

*[sql/txn_restart_test.go, line 676 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRY8xX5JyI9E6trd0:-KEHoKHrjqpaIdzHvgz4:-1513455635) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L676)):*
done, but I'm not sure I prefer it like this. When you're forced to put `err` in the function scope (like we are in this function because of the begin call), having other `err`s in sub-scopes can lead to bugs if you confuse the two.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/txn_restart_test.go, line 676 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-KEHRY8xX5JyI9E6trd0:-KEHpukYfhOfgxYRJ3mq:899794036) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c523eec9eff3f0b9b661175e012aad9eb6bad9/sql/txn_restart_test.go#L676)):*
yes, but the overwriting style is more likely to lead to bugs in my experience.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802)*

**Comment by nvanbenschoten** [comment]
:lgtm: Glad you were able to reproduce this in a test.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5802#-:-KEHse23dbmpGQAhPxqA:1432821021)*

**Pull request merged**
