### PR TITLE
kvserver: log a trace for slow splits

### LINKED ISSUE #81152: kvserver: add cluster settings to log traces for slow lease transfers and splits
**Is your feature request related to a problem? Please describe.**

In an internal escalation (https://github.com/cockroachlabs/support/issues/1533) we attributed high tail latencies to KV-internal requests like lease transfers and splits taking a while. This presented as the following:

```
‹     0.974ms      0.024ms                    event:kv/kvserver/spanlatch/manager.go:517 [n250,s576,r625905/2:/Table/62/16/1498341{40…-63…}] waiting to acquire read latch /Table/62/16/14983414721{8-9}@1651156512.523480877,0, held by write latch /M{in-ax}@0,0›
‹   447.326ms    446.352ms                    event:kv/kvserver/concurrency/concurrency_manager.go:300 [n250,s576,r625905/2:/Table/62/16/1498341{40…-63…}] scanning lock table for conflicting locks›
```

Here we're latched behind the lease transfer request that declares a [non-MVCC latch over the entire keyspace](https://github.com/cockroachdb/cockroach/blob/044cc4493fd8e316015985a0790a74ee00d5167d/pkg/kv/kvserver/batcheval/cmd_lease_transfer.go#L55), i.e. `/M{in-ax}@0,0`. It's difficult however to go from this to an understanding of why the lease transfer request itself was taking that long? Was it waiting for inflight reads to complete? Was it something else?

The same is true for split requests (also declares a non-MVCC write latch over the RHS):

```
‹     1.121ms      0.030ms event:kv/kvserver/spanlatch/manager.go:517 [n220,s459,r625867/1:/Table/60/1{0/2022-…-1/2022-…}] waiting to acquire write latch /Table/60/10/2022-04-28T14:30:03.790531Z/17049428001/0@1651156203.790535407,0, held by write latch /Table/60/1{0/2022-04-28T08:04:21.873826Z/9576597821-1/2022-03-15T03:13:16.248485Z/85629368671}@0,0›
‹  1297.601ms   1296.480ms event:kv/kvserver/concurrency/concurrency_manager.go:300 [n220,s459,r625867/1:/Table/60/10/2022-04-28T0…] scanning lock table for conflicting locks›
‹  1298.162ms      0.561ms event:kv/kvserver/replica_send.go:120 [n220,s459,r625867/1:/Table/60/10/2022-04-28T0…] replica.Send got error: key range /Table/60/10/2022-04-28T14:30:03.790531Z/17049428001/0-/Table/60/10/2022-04-28T14:30:03.790531Z/17049428001/0/NULL outside of bounds of range /Table/60/10/2022-04-28T03:03:48.097657Z/19000424899-/Table/60/10/2022-04-28T08:04:21.873826Z/9576597821; suggested ranges: [desc: r625867:/Table/60/10/2022-04-28T0{3:03:48.097657Z/19000424899-8:04:21.873826Z/9576597821} [(n220,s459):1, (n254,s595):2, (n243,s551):3, (n232,s506):4, (n246,s562):5, next=6, gen=106966, sticky=1651115328.121799069,0], lease: repl=(n220,s459):1 seq=1980 start=1650759449.968454111,0 epo=3 pro=1650759449.967785279,0, closed_timestamp_policy: LAG_BY_CLUSTER_SETTING]›
```

Is the split waiting for long-running inflight reads to finish? Is stats evaluation taking a while?

**Describe the solution you'd like**

We have `sql.trace.{stmt,txn}.enable_threshold` to log instances where individual statements take longer than some threshold we're trying to filter out. We could do something similar here for internal requests (I'm specifically interested in lease transfers and splits). 

**Additional Context**

Arguably `sql.trace.{stmt,txn}.enable_threshold` aren't great given they apply to all statements/txns (we don't have something like https://github.com/cockroachdb/cockroach/issues/70614 to target specific tables/indexes, or a specific stmt fingerprint). Setting thresholds for splits/lease transfers in the same way doesn't seem that bad though given they're down in KV and (should) apply uniformly across ranges and finish in a timely manner (if they don't, say for slow stats computations, that's something we'd want to capture threshold).

+cc @cockroachdb/kv-notifications.

Jira issue: CRDB-15123

### PR DESCRIPTION
**Pull request by miraradeva**
This change enables logging a trace of a split request if it exceeds a certain duration. The duration is controlled by a new cluster setting: `kv.split.slow_split_tracing_threshold`, which defaults to 2s.

Fixes: #81152

Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
> What should the default value for the tracing threshold duration be? I have it at 2s now. Should it be a property of the range that's being split, similarly to the [replicate queue's threshold](https://github.com/cockroachdb/cockroach/blob/dd75019add6102bffdac4f0a6de9103e35e19a92/pkg/kv/kvserver/replicate_queue.go#L545).

2s sounds reasonable. Re-using something similar to the replicate queue would be a bit rough to define an expected rate based off the range size given different hardware/conditions. In comparison, the rate for the replicate queue is mostly bounded by the configured snapshot rate.

> Do we want to refactor processOneChangeWithTracing as a function of the base queue? E.g. as a wrapper around process. That way any specific queue that wants tracing for slow operations can just set its own tracing threshold. I didn't do this right away because the different queues implement process differently: some have retries built into process, and others don't. I'm assuming we don't want a trace across multiple retries, but happy to discuss.

I didn't take a look at other queues but if this is doable without too much added effort, then that sounds good. We wouldn't want to trace across multiple retries, since a trace on the last retry would be sufficient.

**Comment by miraradeva** [comment]
> We wouldn't want to trace across multiple retries, since a trace on the last retry would be sufficient.

I looked at the various queues again. I think if we want to add optional tracing for slow queue processing in the base queue, we'd wrap the timing and tracing logic around [this call](https://github.com/cockroachdb/cockroach/blob/48454ff280ad8f6e85a4246aa259738771709cc0/pkg/kv/kvserver/queue.go#L984) to `process(...)`. I think that makes sense since the timeout logic is there as well. Almost all queues implement the processing logic as a single attempt, except the replicate queue, which [retries](https://github.com/cockroachdb/cockroach/blob/dd75019add6102bffdac4f0a6de9103e35e19a92/pkg/kv/kvserver/replicate_queue.go#L649) *within* the `process(...)` function. So I see two options:

1. Do the above refactor, as long as we're ok with tracing the `process` in replicate queue with all its retries. 
2. Do this kind of change one queue at a time as needed. I can try to refactor a helper function to do the actual tracing to avoid code duplication.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120943#-:-Ntvl7JB33hsgMFU6XYl:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvserver/client_split_test.go` line 1070 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120943#-Ntvl1Fm4MRMwtWrgpzw:-Ntvl1Fm4MRMwtWrgpzx:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69bfdfed75f63a93c8dbc7d53af34707a35c667/pkg/kv/kvserver/client_split_test.go#L1070)):*
> ```Go
> // TestStoreRangeSplitWithTracing tests that the split queue logs traces for
> // slow splits.
> func TestStoreRangeSplitWithTracing(t *testing.T) {
> ```

Nice test!
___
*[`pkg/kv/kvserver/client_split_test.go` line 1074 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120943#-Ntvkpvt2dIfphjkihgs:-Ntvkpvu0jPJbq4-puGV:b1cg21c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69bfdfed75f63a93c8dbc7d53af34707a35c667/pkg/kv/kvserver/client_split_test.go#L1074)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 	l := log.ScopeWithoutShowLogs(t)
> 	_ = log.SetVModule("split_queue=2")
> ```

nit:  change this to `split_queue=1` to match the expensive log check exactly in`processAttemptWithTracing`.

**Comment by miraradeva** [comment]
bors r=kvoli

**Pull request merged**
