### PR TITLE
colexec: do not generate some dead code

### PR DESCRIPTION
**Pull request by yuzefovich**
6 comparison operators that are handled by `proj_const_ops_tmpl.go` are
normalized so that the constant is always on the right side. This
renders the code for these comparison operators useless for the case
when the constant is on the left, so we omit generating it.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First two commits are in a separate PR that has been approved, please ignore them.

**Comment by yuzefovich** [comment]
In order to confirm that I don't fool myself by falling back to the old engine for the case when the constant is on the left, but the comparison expression is not normalized, I added a panic in `execplan` that was not caught by the vectorized catcher (meaning it would have crashed the server), and the build was [successful](https://teamcity.cockroachdb.com/viewLog.html?buildId=2039338&tab=queuedBuildOverviewTab) (apart from the linter failure). So I'm quite confident that this code is, indeed, a dead code that can be safely removed.

**Comment by yuzefovich** [comment]
cc @RaduBerinde to sanity check my assumption that we don't need the code for `EQ, NE, LT, LE, GT, GE` comparison operators with the constant on the left because such expressions are always normalized.

**Comment by RaduBerinde** [comment]
Yes, we have rules (CommuteVarInequality, CommuteConstInequality) that ensure any variable is on the left and any constant is on the right.

**Comment by jordanlewis** [comment]
Can we add some `AssertionError` that fires if we fail this assumption, and a test for this case on the exec side, so we can at least notice if we start to fail this invariant?

**Review by yuzefovich — COMMENTED** [review]
> Can we add some `AssertionError` that fires if we fail this assumption

I've thought about it, and it is very tricky to do. If we are to add the assertion in `execplan.go`, we need to make sure that the error is not caught by `SupportsVectorized` check (because then we simply fallback to the row-based flow) and that we also don't wrap a table reader into the vectorized flow. This will require either basically teaching the `colbuilder` about this particular assertion or propagating the error (via `colexecerror` panic-catch mechanism) in such a way that it doesn't get caught by the catcher (this requires introducing an exception in `colexecerror/error.go` when we're string-matching the origin of the error). Both options are bad IMO.

Another consideration is that we might want to add this assertion before the physical planning, so like after optbuilder and probably execbuilder but before the physical planning, but we don't have a facility to do so at the moment, and I don't think it's worth adding it for this use case.

I'm curious to hear your thoughts, maybe I'm missing something.

> a test for this case on the exec side, so we can at least notice if we start to fail this invariant

This also doesn't seem trivial - we can come up with our own `execinfrapb.Expression` that has the constant on the left and use `colbuilder` to plan the vectorized flow for it, but that would be wrong because the optbuilder wouldn't run. I think the best test for this is already existing logic test in `vectorize_overloads`:
```
# Check that the comparison expressions with the constant on the left are
# handled as well (such expressions are normalized so that the constant ends up
# on the right side).
query T
EXPLAIN (VEC) SELECT B'11' <> _varbit FROM many_types
----
│
└ Node 1
  └ *colexec.projNEDatumDatumConstOp
    └ *colfetcher.colBatchScan
```
We have a constant on the left, and we're making sure that the expression is normalized so that the constant is placed on the right. This tests only `NE` operator though.

All that said, I think it is acceptable to simply trust the optimizer to perform the normalization - in my opinion, this is one of the cases where an implicit agreement between the planning and the execution is warranted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50650#-:-MAhA_uXBEk-7m9LSr5x:b-aij9nb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Another consideration is that we might want to add this assertion before the physical planning, so like after optbuilder and probably execbuilder but before the physical planning, but we don't have a facility to do so at the moment, and I don't it's worth adding it.

This is my preferred option because these invariants should apply to rowexec as well as colexec. I think this is definitely worth adding. We've asked about two optimizer invariants that I can remember in the past couple of weeks (this and if tuples are sorted for a `SELECT IN` binary search). I'm not sure this justifies a new traversal of the plan though, so maybe it's something we should add to the spec factory.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50650#-:-MB3Sbap1f1i0PtSmi6_:b-rhhicg)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by jordanlewis — APPROVED** [review]

**Review by yuzefovich — COMMENTED** [review]
Added a TODO.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50650#-:-MB4ltqUCGyQAgvNZxaX:b1c2ibt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
