### PR TITLE
opt: add UDFs to test catalog

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add UDFs to test catalog

This comment adds basic support for UDFs in the test catalog. The
`exec-ddl` directive can now translate a `CREATE FUNCTION` statement
into a `tree.FunctionDefinition` that is saved in the test
catalog. The test catalog implements `tree.FunctionReferenceResolver`
and is set as the `SemaContext.FunctionResolver` so that it can resolve
references to UDFs in subsequent statements.

Release note: None

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Looks pretty good, just some questions from me.

> Reviewed 7 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-:-N72rEWx5wEnKkBUXSZv:bj2we2d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @msirek)

___
*[`pkg/sql/opt/testutils/testcat/function.go` line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N72q-R87zqcQxcBukOk:-N72q-R87zqcQxcBukOl:bd521jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b0ddbc7f5b7f8896d1d9f136b3e29fd0c95451a/pkg/sql/opt/testutils/testcat/function.go#L149)):*
> ```Go
> // formatFunction nicely formats a function definition creating in the opt test
> // catalog using a treeprinter for debugging and testing.
> func formatFunction(fn *tree.FunctionDefinition) string {
> ```

Is the real output of `SHOW CREATE FUNCTION` also going to use treeprinter like this? I find it a little confusing that `SHOW CREATE FUNCTION` would return something that can't be copy-pasted to create the same function. But maybe this output format is specific to opttest?

Maybe opttest could use a different statement, like `EXPLAIN CREATE FUNCTION`, or a new command like `show-create-function` or something.
___
*[`pkg/sql/sem/tree/overload.go` line 276 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N72kVnb3IAs17_U8iur:-N72kVnb3IAs17_U8ius:b7orp7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b0ddbc7f5b7f8896d1d9f136b3e29fd0c95451a/pkg/sql/sem/tree/overload.go#L276)):*
> ```Go
> 	// SetAt sets the name and type of the argument at the given index in the
> 	// TypeList.
> 	// SetAt(i int, name string, t *types.T)
> ```

Why is this commented out?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84506)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @michae2, and @msirek)

___
*[`pkg/sql/opt/testutils/testcat/function.go` line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N72q-R87zqcQxcBukOk:-N73-ZaAElH7J674ytoM:b2wh2cy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b0ddbc7f5b7f8896d1d9f136b3e29fd0c95451a/pkg/sql/opt/testutils/testcat/function.go#L149)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is the real output of `SHOW CREATE FUNCTION` also going to use treeprinter like this? I find it a little confusing that `SHOW CREATE FUNCTION` would return something that can't be copy-pasted to create the same function. But maybe this output format is specific to opttest?

Maybe opttest could use a different statement, like `EXPLAIN CREATE FUNCTION`, or a new command like `show-create-function` or something.
</blockquote></details>

The tree-printer output will only be used for the few tests I've added to ensure that functions can be created correctly in the test catalog, and for future debugging of optimizer tests. This code path won't be used for the _real_ output of SHOW CREATE FUNCTION.

I used a tree-printer to follow the pattern for other test-catalog introspection commands, like SHOW CREATE: https://github.com/cockroachdb/cockroach/blob/ec8e63caed508a40d92a3a9d750f4ce022f908b1/pkg/sql/opt/testutils/testcat/testdata/table#L32-L49
___
*[`pkg/sql/sem/tree/overload.go` line 276 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N72kVnb3IAs17_U8iur:-N73-Pw--pjYH2PzhM5x:b1a6gmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b0ddbc7f5b7f8896d1d9f136b3e29fd0c95451a/pkg/sql/sem/tree/overload.go#L276)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Why is this commented out?
</blockquote></details>

Silly mistake. Fixed.

**Review by michae2 — APPROVED** [review]
:lgtm: Looks like it needs a `./dev gen bazel`

> Reviewed 1 of 9 files at r3, 1 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-:-N7I73d18wxJ4zJa5uih:bmmvrbl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @msirek)

___
*[`pkg/sql/opt/testutils/testcat/function.go` line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N72q-R87zqcQxcBukOk:-N7I4bsw-loyqD8tvZqJ:b-6ahin5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b0ddbc7f5b7f8896d1d9f136b3e29fd0c95451a/pkg/sql/opt/testutils/testcat/function.go#L149)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The tree-printer output will only be used for the few tests I've added to ensure that functions can be created correctly in the test catalog, and for future debugging of optimizer tests. This code path won't be used for the _real_ output of SHOW CREATE FUNCTION.

I used a tree-printer to follow the pattern for other test-catalog introspection commands, like SHOW CREATE: https://github.com/cockroachdb/cockroach/blob/ec8e63caed508a40d92a3a9d750f4ce022f908b1/pkg/sql/opt/testutils/testcat/testdata/table#L32-L49
</blockquote></details>

Ah, I didn't know that we also do this for SHOW CREATE in the test catalog. Ok, I take it back. Thanks for the explanation!
___
*[`pkg/sql/opt/testutils/testcat/testdata/udf` line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I5fSP9sGkN0JA2b0b:-N7I5fSP9sGkN0JA2b0c:b8dbhmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1139d050df9c78c580f3bf2dd5cdc5e85279d06b/pkg/sql/opt/testutils/testcat/testdata/udf#L24)):*
> ```
> ----
> FUNCTION b(i: int, s: string) -> int [volatile]
>  └──   SELECT *
> ```

micro-nit: This doesn't matter in the slightest, but I'm curious where the extra two spaces come from in this case.

**Review by msirek — APPROVED** [review]
:lgtm: I just had a couple questions about possible missing parameters.

> Reviewed 20 of 22 files at r1, 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-:-N7I7qJc4bRYTP5g-I49:b-v3htq9)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @msirek)

___
*[`pkg/sql/opt/optbuilder/scope.go` line 1499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I6la4B3KZImc0osX1:-N7I6la54d3UevJf0FhQ:b-cj9ens) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb1e27db5e917d5ce9d6be5ca67766b0b35ff95/pkg/sql/opt/optbuilder/scope.go#L1499)):*
> ```Go
> 				e.Exprs = tree.Exprs{tree.DBoolTrue}
> 
> 				newDef, err := e.Func.Resolve(s.builder.semaCtx.SearchPath, nil /* resolver */)
> ```

Should this be using `semaCtx.FunctionResolver` as the resolver?
___
*[`pkg/sql/opt/optbuilder/scope.go` line 1525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I6rOA3c3TfwqSWS2K:-N7I6rOA3c3TfwqSWS2L:bxuw5d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb1e27db5e917d5ce9d6be5ca67766b0b35ff95/pkg/sql/opt/optbuilder/scope.go#L1525)):*
> ```Go
> 				panic(err)
> 			}
> 			newDef, err := e.Func.Resolve(s.builder.semaCtx.SearchPath, nil /* resolver */)
> ```

Same comment.  Use `semaCtx.FunctionResolver`?
___
*[`pkg/sql/sem/asof/as_of.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I7Dfz8JWNGczyXZv5:-N7I7Dfz8JWNGczyXZv6:bxvl3as) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb1e27db5e917d5ce9d6be5ca67766b0b35ff95/pkg/sql/sem/asof/as_of.go#L66)):*
> ```Go
> 		return funcTypeInvalid
> 	}
> 	def, err := fe.Func.Resolve(searchPath, nil /* resolver */)
> ```

Add a resolver?  Or a TODO comment?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84506)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @michae2, and @msirek)

___
*[`pkg/sql/opt/testutils/testcat/testdata/udf` line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I5fSP9sGkN0JA2b0b:-N7InZuSDtzem1C7SmMg:bzakd7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/1139d050df9c78c580f3bf2dd5cdc5e85279d06b/pkg/sql/opt/testutils/testcat/testdata/udf#L24)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

micro-nit: This doesn't matter in the slightest, but I'm curious where the extra two spaces come from in this case.
</blockquote></details>

They come from the indentation in the `CREATE FUNCTION` above. The `$$` are [dollar quotes](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING), so the value inside them is just a string, with the newlines and indentation preserved. We'll parse and analyze this string when `CREATE FUNCTION` is run to validate it a bit, but I'm not yet sure if we'll pretty print the string from the parsed AST or not. And even if we do that in the _real_ implementation of `CREATE FUNCTION`, we'll probably only do it if absolutely necessary in the test catalog implementation. I was frustrated by these unsightly spaces, but I can't think of an easy way to get rid of them.
___
*[`pkg/sql/opt/optbuilder/scope.go` line 1499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I6la4B3KZImc0osX1:-N7IpCVMEwHTToxJcTbz:b-c13gd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb1e27db5e917d5ce9d6be5ca67766b0b35ff95/pkg/sql/opt/optbuilder/scope.go#L1499)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should this be using `semaCtx.FunctionResolver` as the resolver?
</blockquote></details>

Thanks for pointing this out. These are edge cases we'll need to handle in the even that a user defines a `count` function that shadows the built-in `count` function. I've add TODOs.
___
*[`pkg/sql/opt/optbuilder/scope.go` line 1525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I6rOA3c3TfwqSWS2K:-N7Ipda7AJfWPHTtI57e:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb1e27db5e917d5ce9d6be5ca67766b0b35ff95/pkg/sql/opt/optbuilder/scope.go#L1525)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Same comment.  Use `semaCtx.FunctionResolver`?
</blockquote></details>

Added a comment.
___
*[`pkg/sql/sem/asof/as_of.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84506#-N7I7Dfz8JWNGczyXZv5:-N7IqQCd7t9ox5vXyOnD:b-hbof5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb1e27db5e917d5ce9d6be5ca67766b0b35ff95/pkg/sql/sem/asof/as_of.go#L66)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Add a resolver?  Or a TODO comment?
</blockquote></details>

Added a comment explaining why we don't need a resolver here.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
