### PR TITLE
distsql: add ProjectSet processor and planning

### PR DESCRIPTION
**Pull request by solongordon**
I added a new ProjectSet processor type, which is the distsql
implementation of projectSetNode. It applies a set of expressions to its
input, some of which may be set-returning functions, and emits the
zipped results. This is mostly a port of knz's existing local
implementation and there is a fair amount of code redundancy, which we
should be able to remove in the near term by merging the
implementations.

I also added planning logic to distsql_physical_planner.go. For now I
chose the simple approach of only planning ProjectSet processors on the
gateway node. My hypothesis is that for the vast majority of queries,
ProjectSet will be a late stage which produces more rows than its
source, so it doesn't make sense to distribute it and stream the
results. We may want to adjust this in the future if we find queries
where this isn't the case.

Release note (sql change): Support set-returning functions in
distributed SQL execution.

### CODE REVIEW

**Comment by solongordon** [comment]
This is ready for a look, though I would still like to add unit tests and expand the logic tests.

**Comment by RaduBerinde** [comment]
Distsql plumbing and planning part LGTM, with one comment.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsql_physical_planner.go, line 2334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LF2qXiK2zxEWfK2vb01:-LF2qXiK2zxEWfK2vb02:b-3y0wws) ([raw file](https://github.com/cockroachdb/cockroach/blob/444560a97d51994f21b770603e271eb262989b35/pkg/sql/distsql_physical_planner.go#L2334)):*
> ```Go
> 	}
> 
> 	plan.SetMergeOrdering(dsp.convertOrdering(planPhysicalProps(n), plan.planToStreamColMap))
> ```

The plan should already have whatever ordering was in the input node. We shouldn't need to do this here. We would need to do it at the end if we didn't have a single stage (we can still do it for completeness).

I would also move the planToStreamColMap update after AddSingleGroupStage

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-:-LF2rrsH4Eyjv88o50rN:b-83x1bb)*

**Comment by knz** [comment]
Seems good but chances are your tests won't pass until you also fix #26627.

---

Reviewed 12 of 12 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-:-LF2t5gY7NJl3i0s9Hrh:bdfotmq)*

**Comment by solongordon** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsql_physical_planner.go, line 2334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LF2qXiK2zxEWfK2vb01:-LF30TFTCEtdISofoj-1:bctsbbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/444560a97d51994f21b770603e271eb262989b35/pkg/sql/distsql_physical_planner.go#L2334)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The plan should already have whatever ordering was in the input node. We shouldn't need to do this here. We would need to do it at the end if we didn't have a single stage (we can still do it for completeness).

I would also move the planToStreamColMap update after AddSingleGroupStage
</blockquote></details>

Oh interesting, thanks. It seemed necessary at the time but that must have been before https://github.com/cockroachdb/cockroach/pull/26703 was merged.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26739)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/distsqlrun/project_set.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFIejZW1XkWSsgIU3sM:-LFIejZW1XkWSsgIU3sN:b-3yh9ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/distsqlrun/project_set.go#L41)):*
> ```Go
> 
> 	// funcs contains a valid pointer to a SRF FuncExpr for every entry
> 	// in `exprs` that is actually a SRF function application.
> ```

What is/where does `exprs` live?

---

*[pkg/sql/distsqlrun/project_set.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFIfvEy3FBeGb4vNpho:-LFIfvEy3FBeGb4vNphp:b-ljcu3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/distsqlrun/project_set.go#L142)):*
> ```Go
> 	// Initialize a round of SRF generators or scalar values.
> 	for i := range ps.exprHelpers {
> 		if fn := ps.funcs[i]; fn != nil {
> ```

Is it common that not every `exprHelper` will be an SRF? I think I'd prefer to see an approach that stores the indexes of the `exprHelpers` that actually are SRFs, to avoid iterating over `exprHelpers` every time. We know the indexes of the SRFs ahead of time - might as well store those directly, during processor initialization, rather than re-find them for every row in the input.

Welll... actually I guess since you have to false-ify all of ps.done anyway it might not matter too much.

---

*[pkg/sql/distsqlrun/project_set.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFIjs0r5YG2LhGCTQQk:-LFIjs0r5YG2LhGCTQQl:b-plfbi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/distsqlrun/project_set.go#L247)):*
> ```Go
> 
> 			// Keep the values for later.
> 			copy(ps.rowBuffer, row)
> ```

I don't think you need this copy. You only need to copy the EncDatumRow from an input processor if your processor needs to hold on to the row for longer than the duration of a single call to input.Next, which (I don't think) is the case here. In other words, you should be able to just set ps.rowBuffer=row here.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_srfs, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFImjgs40clQX7M7YGk:-LFImjgs40clQX7M7YGl:bhgn8er) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/logictest/testdata/logic_test/distsql_srfs#L20)):*
> ```
> # Correlated SRF
> query II
> SELECT a, generate_series(a, a + 1) FROM data ORDER BY 1, 2
> ```

I *think* this distributed testing should be happening automatically if you add the `fakedist` configurations to a test of this scenario, without having to do the split + relocate by hand.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-:-LFInS9v2D7Rwx2UvJmY:bnfp4nl)*

**Comment by solongordon** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/project_set.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFIejZW1XkWSsgIU3sM:-LFNjvKa27Ufwox-CwCY:bbir2fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/distsqlrun/project_set.go#L41)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What is/where does `exprs` live?
</blockquote></details>

Should be `exprHelpers`. Done.

---

*[pkg/sql/distsqlrun/project_set.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFIfvEy3FBeGb4vNpho:-LFNlfWu1DO96CL-62zG:b-ohawge) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/distsqlrun/project_set.go#L142)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is it common that not every `exprHelper` will be an SRF? I think I'd prefer to see an approach that stores the indexes of the `exprHelpers` that actually are SRFs, to avoid iterating over `exprHelpers` every time. We know the indexes of the SRFs ahead of time - might as well store those directly, during processor initialization, rather than re-find them for every row in the input.

Welll... actually I guess since you have to false-ify all of ps.done anyway it might not matter too much.
</blockquote></details>

Yeah, I'm not sure storing the SRF indexes would be any more efficient. The `exprHelper`s which are not SRFs don't get touched here anyhow.

---

*[pkg/sql/distsqlrun/project_set.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFIjs0r5YG2LhGCTQQk:-LFOEZjSBof2zKy3GPPz:b-gy2yug) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/distsqlrun/project_set.go#L247)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think you need this copy. You only need to copy the EncDatumRow from an input processor if your processor needs to hold on to the row for longer than the duration of a single call to input.Next, which (I don't think) is the case here. In other words, you should be able to just set ps.rowBuffer=row here.
</blockquote></details>

It seems like I still need the copy because `rowBuffer` is longer than `row` to accommodate the generated values. Unless there is a slice trick I'm missing.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_srfs, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFImjgs40clQX7M7YGk:-LFOEpiMAQtFEVAihBmi:b-z4qkzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/logictest/testdata/logic_test/distsql_srfs#L20)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I *think* this distributed testing should be happening automatically if you add the `fakedist` configurations to a test of this scenario, without having to do the split + relocate by hand.
</blockquote></details>

Oh sweet, was not aware of this functionality.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26739)*

**Comment by jordanlewis** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/distsqlrun/project_set.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26739#-LFIjs0r5YG2LhGCTQQk:-LFOJDb1Bp2IphrrXNza:bky0lu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/06443e8af83b1c76401e8a13fe328c8ec30c07cb/pkg/sql/distsqlrun/project_set.go#L247)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

It seems like I still need the copy because `rowBuffer` is longer than `row` to accommodate the generated values. Unless there is a slice trick I'm missing.
</blockquote></details>

Oh I see. I missed that. Carry on.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26739)*

**Pull request merged**
