### PR TITLE
sql: fix privileges reported for non-user-defined schemas

### LINKED ISSUE #68917: sql: remove check for CREATE privilege on database substituting for USAGE privilege on schema
This will be no longer valid once `CREATE` is completely deprecated as a database privilege in 22.1

https://github.com/cockroachdb/cockroach/blob/fbdc57c54181754619f0b767ca617273fa7fdc99/pkg/sql/information_schema.go#L1019-L1040

Epic CRDB-8948

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/68917

They no longer inherit privileges from the parent database.

Release note (sql change): The privileges reported in
information_schema.schema_privileges for non-user-defined schemas no
longer are inferred from the privileges on the parent database. Instead,
virtual schemas (like pg_catalog and information_schema) always report the USAGE
privilege for the public role. The pg_temp schema always reports USAGE
and CREATE privileges for the public role.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Does this need a version gate and/or logic for the mixed version state prior to the migration?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-:-MuSuUxO8WaqRkRLxWoK:b-wzkmeu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

**Comment by rafiss** [comment]
this doesn't really need a gate -- if a new binary runs this code in a mixed version cluster, it will just call `GetPrivileges` on the synthetic descriptors (the public, virtual, and temporary structs) and will get the USAGE privilege without ever going to disk. I could add a `local-mixed-21.2-22.1` logic test for this though

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/catalog/schemadesc/temporary_schema_desc.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-MuWlfiU5aF63K-G-oko:-MuWlfiU5aF63K-G-okp:by85ak5) ([raw file](https://github.com/cockroachdb/cockroach/blob/727d50cf4892f906bb67121029f568a4424acf96/pkg/sql/catalog/schemadesc/temporary_schema_desc.go#L49)):*
> ```Go
> func (p temporary) GetParentID() descpb.ID { return p.parentID }
> func (p temporary) GetPrivileges() *descpb.PrivilegeDescriptor {
> 	return descpb.NewPublicUsagePrivilegeDescriptor()
> ```

Can we add a logic test for this case?
___
*[pkg/sql/logictest/testdata/logic_test/grant_table, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-MuWlE926nNwazzFMdtr:-MuWlE926nNwazzFMdts:b4iwsb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5c8326d4acf773dce97a1f4eff735b566a2522/pkg/sql/logictest/testdata/logic_test/grant_table#L30)):*
> ```
> test           NULL                NULL                                   root     ALL
> test           crdb_internal       NULL                                   admin    ALL
> test           crdb_internal       NULL                                   root     ALL
> ```

The privileges that `root` and `admin` no longer have are `GRANT` and `CREATE` which both seem fine to remove for our internal virtual schemas.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/catalog/schemadesc/temporary_schema_desc.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-MuWlfiU5aF63K-G-oko:-MuXskhU4VCNpv1TqRRq:b-gltolr) ([raw file](https://github.com/cockroachdb/cockroach/blob/727d50cf4892f906bb67121029f568a4424acf96/pkg/sql/catalog/schemadesc/temporary_schema_desc.go#L49)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Can we add a logic test for this case?
</blockquote></details>

interesting, seems like in postgres, everyone actually gets CREATE on pg_temp
```
WITH "names"("name") AS (
   SELECT n.nspname AS "name"
     FROM pg_catalog.pg_namespace n
 ) SELECT "name",
   pg_catalog.has_schema_privilege('newrole', "name", 'CREATE') AS "create",
   pg_catalog.has_schema_privilege('newrole', "name", 'USAGE') AS "usage"
     FROM "names";

+--------------------+----------+---------+
| name               | create   | usage   |
|--------------------+----------+---------|
| pg_toast           | False    | False   |
| pg_catalog         | False    | True    |
| public             | True     | True    |
| information_schema | False    | True    |
| pg_temp_3          | True     | True    |
| pg_toast_temp_3    | False    | False   |
+--------------------+----------+---------+
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/grant_table, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-MuWlE926nNwazzFMdtr:-MuY3iYa3kfBZ-uNqwb-:bey0xam) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5c8326d4acf773dce97a1f4eff735b566a2522/pkg/sql/logictest/testdata/logic_test/grant_table#L30)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

The privileges that `root` and `admin` no longer have are `GRANT` and `CREATE` which both seem fine to remove for our internal virtual schemas.
</blockquote></details>

yeah, hm well if we want to, we could modify `NewPublicSelectPrivilegeDescriptor` and the related functions to use `NewBasePrivilegeDescriptor` and give ALL to superusers. doesn't seem important, but maybe it's better to be consistent?

**Review by rafiss — COMMENTED** [review]
added another commit to consolidate logic for public schema privileges.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-:-MuY9OXq5DXXxMDsX0kq:b-dvumfe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @shermanCRL)

**Comment by rafiss** [comment]
@RichardJCai this is ready for another look

**Review by RichardJCai — APPROVED** [review]
nice, lgtm.

> Reviewed 3 of 6 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-:-MuqNn-9DL68w3yX1sVd:b-w69zto)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[-- commits, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-MuqN6Am1vXAAyQnxcHa):*
nit: no longer / are no longer

**Review by rafiss — COMMENTED** [review]
tftr!

bors r=RichardJCai

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-:-MuqSRScDzwHnF2w8OQT:b-23iapl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[-- commits, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75628#-MuqN6Am1vXAAyQnxcHa):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: no longer / are no longer
</blockquote></details>

i think the grammar works: i have "privileges no longer are inferred from..." right now

**Pull request merged**
