### PR TITLE
raft: move Config onto the raft struct 

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details.

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 7 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127312)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25cFMY6QxvW4p3gq3J:-O25cFMY6QxvW4p3gq3K:b-n5v5aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8146e2143ce7ce773ff69a4416972221b713c8be/pkg/raft/raft.go#L432)):*
> ```Go
> 	lastID := r.raftLog.lastEntryID()
> 
> 	r.trk = tracker.MakeProgressTracker(&r.config, c.MaxInflightMsgs, c.MaxInflightBytes)
> ```

It would be nice to not need to construct a `ProgressTracker` until after `confchange.Restore`. Ideally, I think this would live in `switchToConfig`. I think we can get there with a few changes to `confchange.Changer` — see my comment below.
___
*[`pkg/raft/confchange/confchange.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25bHWD0gf6KBbCndsk:-O25bHWD0gf6KBbCndsl:b-aub7yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8146e2143ce7ce773ff69a4416972221b713c8be/pkg/raft/confchange/confchange.go#L35)):*
> ```Go
> // configuration.
> type Changer struct {
> 	Tracker   tracker.ProgressTracker
> ```

It's not great that `Changer` holds a `Config` and a `ProgressTracker`, which in turn holds a pointer to a different `Config`. Did you look into replacing the full `ProgressTracker` with a more limited `ProgressMap`?

That seems to work for everything except the one use of `MaxInflight` and `MaxInflightBytes`. Do those even belong in `ProgressTracker`? If we lift those off of `ProgressTracker` and onto `raft` and then passing them directly on `Changer`, could we then clean this up?
___
*[`pkg/raft/confchange/confchange.go` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25bAJQDmMYawmdX2-N:-O25bAJQDmMYawmdX2-O:b-t0e8h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8146e2143ce7ce773ff69a4416972221b713c8be/pkg/raft/confchange/confchange.go#L36)):*
> ```Go
> type Changer struct {
> 	Tracker   tracker.ProgressTracker
> 	Config    quorum.Config
> ```

nit: move Config above Tracker here and wherever we construct a Changer to better reflect the one-way dependency between them.
___
*[`pkg/raft/quorum/config.go` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25Ydqg80MmSfLHBCvA:-O25YdqhBMUP5IWs8czQ:bjod1sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/54564215c87690d342db2a5784cae45b716ddfa1/pkg/raft/quorum/config.go#L20)):*
> ```Go
> )
> 
> // Config reflects the configuration tracked in a ProgressTracker.
> ```

It feels like this comment should be updated to talk more about how to `Config` relates to a quorum, rather than referencing the `ProgressTracker` (which is now in a separate package).

**Review by arulajmani — COMMENTED** [review]
RFAL. Sorry for going a bit overboard with the refactors here. There's more to come, with pulling out vote tracking, but I'll do those in a separate PR. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-:-O27J5IrE8yrIgHUjm4W:b-5dt430)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25cFMY6QxvW4p3gq3J:-O27J-8aCALKE5xGmqAl:b-ndh15o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8146e2143ce7ce773ff69a4416972221b713c8be/pkg/raft/raft.go#L432)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It would be nice to not need to construct a `ProgressTracker` until after `confchange.Restore`. Ideally, I think this would live in `switchToConfig`. I think we can get there with a few changes to `confchange.Changer` — see my comment below.
</blockquote></details>

Done in commit 4, which then prompted commit 5.
___
*[`pkg/raft/confchange/confchange.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25bHWD0gf6KBbCndsk:-O2726k-9rkwG4zyNJK4:b-zfzba0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8146e2143ce7ce773ff69a4416972221b713c8be/pkg/raft/confchange/confchange.go#L35)):*
> It's not great that `Changer` holds a `Config` and a `ProgressTracker`, which in turn holds a pointer to a different `Config`.

Heavy +1. I hadn't looked into this before, but I quite like your suggestion. It's in commit 3.
___
*[`pkg/raft/quorum/config.go` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25Ydqg80MmSfLHBCvA:-O25qRQQ1_hapyKXFSAZ:bp7cbq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/54564215c87690d342db2a5784cae45b716ddfa1/pkg/raft/quorum/config.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It feels like this comment should be updated to talk more about how to `Config` relates to a quorum, rather than referencing the `ProgressTracker` (which is now in a separate package).
</blockquote></details>

Sorry, this was copy pasted. Fixed.

**Review by nvb — APPROVED** [review]
:lgtm: beyond some nits and a question of whether we want the 5th commit.

> Reviewed 14 of 14 files at r3, 13 of 13 files at r4, 11 of 11 files at r5, 9 of 9 files at r6, 4 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-:-O2AuDjw2eIEyRe1prCO:bwdbeet)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 62 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2AtxhK-YnesQcAenGe):*
The map can still be modified by a caller of this method, so I'm lukewarm on this final commit. It doesn't feel like it's getting us much beyond some code churn and breaking an established pattern of exported fields.
___
*[`pkg/raft/raft.go` line 331 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2As9NJ3BProVZ9tovl:-O2As9NJ3BProVZ9tovm:b-7i15bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/24532ae790c382b47b04d7f1fb9a4fae0bdb6831/pkg/raft/raft.go#L331)):*
> ```Go
> 	trk    tracker.ProgressTracker
> 
> 	maxInflight      int
> ```

nit: let's move this down here and in the constructor to next to the rest of the configurations (like `heartbeatTimeout` and `preVote`).
___
*[`pkg/raft/raft.go` line 1911 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2Ass769rw4HGvZhLE9:-O2Ass769rw4HGvZhLEA:b-le7hur) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0c486c712f261d52308c377d16554c76af4215/pkg/raft/raft.go#L1911)):*
> ```Go
> 
> 	// Reset the configuration and add the (potentially updated) peers in anew.
> 	r.config = quorum.MakeEmptyConfig()
> ```

Instead of assigning to `r.config` here and then again in `switchToConfig`, should we just pass `Config: quorum.MakeEmptyConfig()` and assign once in `switchToConfig`?

Same question up above in `newRaft`.
___
*[`pkg/raft/quorum/config.go` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25Ydqg80MmSfLHBCvA:-O2ArjsRDVHj78MAf29U:bawcq95) ([raw file](https://github.com/cockroachdb/cockroach/blob/54564215c87690d342db2a5784cae45b716ddfa1/pkg/raft/quorum/config.go#L20)):*
> make decisions

Maybe switch to something a bit more specific. Like "make quorum decisions".
___
*[`pkg/raft/tracker/progress.go` line 361 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2AtVWGBWn6XoBIqS9q:-O2AtVWGBWn6XoBIqS9r:b-70malm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0c486c712f261d52308c377d16554c76af4215/pkg/raft/tracker/progress.go#L361)):*
> ```Go
> // MakeEmptyProgressMap constructs and returns an empty ProgressMap.
> func MakeEmptyProgressMap() ProgressMap {
> 	return map[pb.PeerID]*Progress{}
> ```

nit: `return make(ProgressMap)`
___
*[`pkg/raft/tracker/tracker.go` line 43 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2Atj3d3dKIY18TG_2i:-O2Atj3d3dKIY18TG_2j:bjuqj3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0c486c712f261d52308c377d16554c76af4215/pkg/raft/tracker/tracker.go#L43)):*
> ```Go
> 	p := ProgressTracker{
> 		Config:   config,
> 		Votes:    map[pb.PeerID]bool{},
> ```

small nit: move this one line down, to match the order in the struct definition.

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-:-O2Bcd9f3rVcrYXc_3YY:b-l0r5kv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`-- commits` line 62 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2AtxhK-YnesQcAenGe):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The map can still be modified by a caller of this method, so I'm lukewarm on this final commit. It doesn't feel like it's getting us much beyond some code churn and breaking an established pattern of exported fields.
</blockquote></details>

We spoke about this offline -- we're soon gonna have all fields in these trackers be unexported, so we want to move in a direction where `progressMap` is private as well. We agreed that giving the caller the ability to modify this map isn't great; we've got a plan to fix that, but I'll pull that out into its own PR. For now, I'm merging the first 4 commits.
___
*[`pkg/raft/raft.go` line 331 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2As9NJ3BProVZ9tovl:-O2BadtT0gGjGeZB8u-M:boxxiya) ([raw file](https://github.com/cockroachdb/cockroach/blob/24532ae790c382b47b04d7f1fb9a4fae0bdb6831/pkg/raft/raft.go#L331)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: let's move this down here and in the constructor to next to the rest of the configurations (like `heartbeatTimeout` and `preVote`).
</blockquote></details>

Move it above `checkQuorum` to match the position in `Config`.
___
*[`pkg/raft/raft.go` line 1911 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O2Ass769rw4HGvZhLE9:-O2BcADJEtoTgXAq_mh4:b5c2xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0c486c712f261d52308c377d16554c76af4215/pkg/raft/raft.go#L1911)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of assigning to `r.config` here and then again in `switchToConfig`, should we just pass `Config: quorum.MakeEmptyConfig()` and assign once in `switchToConfig`?

Same question up above in `newRaft`.
</blockquote></details>

Done in both places.
___
*[`pkg/raft/quorum/config.go` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-O25Ydqg80MmSfLHBCvA:-O2B_znRDSv7Ye1Io1cF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54564215c87690d342db2a5784cae45b716ddfa1/pkg/raft/quorum/config.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> make decisions

Maybe switch to something a bit more specific. Like "make quorum decisions".
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 19 files at r8, 3 of 13 files at r9, 3 of 11 files at r10, 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127312#-:-O2BfZxLAKKZpcR1cFxi:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
bors retry

**Pull request merged**
