### PR TITLE
changefeedccl: disable non-enterprise feeds in TestChangefeedTimelyRe…

### LINKED ISSUE #134113: ccl/changefeedccl: TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart failed
ccl/changefeedccl.TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/17555849?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/17555849?buildTab=artifacts#/) on master @ [6c92b92b20bd46e71a9c3deacad6fe1223d5a2e2](https://github.com/cockroachdb/cockroach/commits/6c92b92b20bd46e71a9c3deacad6fe1223d5a2e2):

```
*   | 	GOROOT/src/runtime/iface.go:434
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart
*   | 	pkg/ccl/changefeedccl/changefeed_test.go:6565
*   | testing.tRunner
*   | 	GOROOT/src/testing/testing.go:1689
*   | runtime.goexit
*   | 	src/runtime/asm_arm64.s:1222
* Wraps: (2) interface conversion: *changefeedccl.sinklessFeed is not cdctest.EnterpriseTestFeed: missing method Details
* Error types: (1) *withstack.withStack (2) *runtime.TypeAssertionError
*
    stopper.go:226: -- test log scope end --

ERROR: a panic has occurred!
Details cannot be printed yet because we are still unwinding.
Hopefully the test harness prints the panic below, otherwise check the test logs.

test logs left over in: /artifacts/tmp/_tmp/f236cfce7e32f4b492de4b4f1cd80c96/logTestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart3899893785
    stopper.go:226: panic: interface conversion: *changefeedccl.sinklessFeed is not cdctest.EnterpriseTestFeed: missing method Details
--- FAIL: TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart (131.25s)
panic: interface conversion: *changefeedccl.sinklessFeed is not cdctest.EnterpriseTestFeed: missing method Details [recovered]
	panic: interface conversion: *changefeedccl.sinklessFeed is not cdctest.EnterpriseTestFeed: missing method Details [recovered]
	panic: interface conversion: *changefeedccl.sinklessFeed is not cdctest.EnterpriseTestFeed: missing method Details [recovered]
	panic: interface conversion: *changefeedccl.sinklessFeed is not cdctest.EnterpriseTestFeed: missing method Details [recovered]
	panic: interface conversion: *changefeedccl.sinklessFeed is not cdctest.EnterpriseTestFeed: missing method Details

goroutine 122320 [running]:
testing.tRunner.func1.2({0x5de88a0, 0x401af19680})
	GOROOT/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1634 +0x33c
panic({0x5de88a0?, 0x401af19680?})
	GOROOT/src/runtime/panic.go:770 +0x124
github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func2()
	pkg/util/leaktest/leaktest.go:132 +0x370
panic({0x5de88a0?, 0x401af19680?})
	GOROOT/src/runtime/panic.go:770 +0x124
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0x401e85c6c8?, {0x81d1748, 0xc786cc0})
	pkg/util/stop/stopper.go:226 +0x68
panic({0x5de88a0?, 0x401af19680?})
	GOROOT/src/runtime/panic.go:770 +0x124
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0x400bcc4ea0, {0x81d1748, 0xc786cc0})
	pkg/util/stop/stopper.go:535 +0x154
panic({0x5de88a0?, 0x401af19680?})
	GOROOT/src/runtime/panic.go:770 +0x124
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart(0x400601aea0)
	pkg/ccl/changefeedccl/changefeed_test.go:6565 +0xaf0
testing.tRunner(0x400601aea0, 0x6d49820)
	GOROOT/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
	GOROOT/src/testing/testing.go:1742 +0x318
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-43918

### LINKED ISSUE #134148: ccl/changefeedccl: TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart failed
ccl/changefeedccl.TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart [failed](https://tanzanite.cluster.engflow.com/invocations/default/f87e9f1d-363e-45c5-90e9-ec0afc2d1ec2?testReportRun=1&testReportShard=3&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.3 @ [29d723d5f5e6ed2075feb728e9632fb3516e4fc2](https://github.com/cockroachdb/cockroach/commits/29d723d5f5e6ed2075feb728e9632fb3516e4fc2):

```
=== RUN   TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart1094501607
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:6520: error executing 'ALTER TABLE d.foo SPLIT AT (SELECT * FROM generate_series(1, 1000));': pq: replica unavailable: (n1,s1):1 unable to serve request to r397:/{Table/106/1/368-Max} [(n1,s1):1, (n3,s3):2, (n2,s2):3, next=4, gen=372, sticky=9223372036.854775807,2147483647]: closed timestamp: 1730548075.445353187,0 (2024-11-02 11:47:55); raft status: {"id":"1","term":19,"vote":"1","commit":10,"lead":"0","leadEpoch":"0","raftState":"StateCandidate","applied":10,"progress":{},"leadtransferee":"0"}: have been waiting 61.00s for slow proposal RequestLease [/Table/106/1/368]
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart1094501607
--- FAIL: TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart (2564.85s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=3</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #134113 ccl/changefeedccl: TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart failed [A-cdc C-test-failure O-robot T-cdc branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedTimelyResolvedTimestampUpdatePostRollingRestart.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-43937

### PR DESCRIPTION
**Pull request by rharding6373**
…solvedTimestampUpdatePostRollingRestart

Fixes a test panic and prevents the test from running under race, deadlock, or stress test conditions.

Epic: None
Fixes: #134148
Fixes: #134113

Release note: None

### CODE REVIEW

**Review by wenyihu6 — APPROVED** [review]

**Comment by wenyihu6** [comment]
Do you want to change Fixes to Informs instead since the test is also failing due to other reasons - https://github.com/cockroachdb/cockroach/issues/134148#issuecomment-2454732920?

**Comment by rharding6373** [comment]
I added a skip for the conditions under which we hit the other error. Want to take another look?

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134157#-:-OAscBC96mwet64WTmba:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890 and @rharding6373)

___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 6477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134157#-OAsbz2W5rK8tkCgMnVI:-OAsbz2W5rK8tkCgMnVJ:b-6q0tpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8340011f3b18ea254e4b6df478047f4cb6a335a/pkg/ccl/changefeedccl/changefeed_test.go#L6477)):*
> ```Go
> 	// This test requires many range splits, which can be slow under certain test
> 	// conditions. Skip potentially slow tests.
> 	skip.UnderDuress(t)
> ```

nit: consider just skipping under deadlock and race, as duress also skips the test under stress as well.

**Review by wenyihu6 — APPROVED** [review]

**Comment by rharding6373** [comment]
TFTRs!

bors r+

**Pull request merged**
