### PR TITLE
opt: support EXPLAIN BUNDLE as a prepared statement

### LINKED ISSUE #46020: sql: explain bundle doesn't work with dbeaver
```SQL
explain bundle select * from drop_index_test;
```
image

Here is the error:
```
SQL Error [0A000]: ERROR: unimplemented: unsupported statement: *tree.ExplainBundle
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/34848
```
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [0A000]: ERROR: unimplemented: unsupported statement: *tree.ExplainBundle
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/34848
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:488)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:425)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:417)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:775)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2914)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3423)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: unimplemented: unsupported statement: *tree.ExplainBundle
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/34848
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```
Explain analyze does work for example:
image

Version: V20.1.0-BETA.2-764-G73F4AAC551
Dbeaver: Version 7.0.0.202003021717

To repro:
Use dbeaver with cockroach demo.
Then use the SQL editor to execute explain bundle.

### PR DESCRIPTION
**Pull request by RaduBerinde**
Some clients / drivers might issue EXPLAIN BUNDLE with the parse/bind/exec
protocol (e.g. DBeaver).

This change also fixes an error message in the optimizer - it was left over from
when we would fall back on HP; now this condition is an internal error.

Fixes #46020.

Release note (bug fix): EXPLAIN BUNDLE now works when the client driver prepares
the statement (as is the case with DBeaver).

Release justification: Bug fixes and low-risk updates to new functionality.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
Opt stuff :lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46111#-:-M2YcsTK-EM3IIPSa6bl:b9mbr92)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

**Comment by RaduBerinde** [comment]
bumpity bump for a review for the sql side

**Comment by andreimatei** [comment]
LGTM

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
