### PR TITLE
colexec: make aggregators more dynamic

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: clean up AggregateFunc interface**

This commit updates the comments to reflect the current code around
aggregation as well as cleans up the ordered aggregator according to the
new contract.

Additionally, this commit removes `Reset` method from `AggregateFunc`
which is only used by the benchmarks in order to make those more
realistic (when executing a query, we don't have an aggregator that we
can reset, and we always create a new one) and to be more in line with
the row-execution benchmarks.

Release note: None

**colexec: make aggregators more dynamic and refactor ordered aggregator**

This commit refactors both aggregators to be more dynamic. This required
adding another method `SetOutput` to `AggregateFunc` interface to notify
the aggregate functions that the new vector should be used for their
output.

The changes to the hash aggregator are minor since hash aggregate
functions don't need the output vectors until `Flush` is called since
they process tuples only from a single group and don't write anything
during `Compute` method. One minor change was made to the allocator to
allow for getting the footprint of `nil` vectors.

The ordered aggregator required slightly more invasive changes, but the
general algorithm remained intact. With introduction of the dynamic
`scratch.Batch` we need to be careful to make sure that the aggregate
functions will not overflow past the capacity of the batch. We also now
instantiate the `unsafeBatch` lazily (of fixed `coldata.BatchSize()` in
size). I decided to refactor the ordered aggregator to be more like
a state machine, and the notable change is that now in case when the
results "overflow", we copy over the second part of the scratch batch
before returning the output (previously, we would do so on the next
iteration) - I think it is easier to follow the code this way. Also, we
add a minor optimization when zeroing out `groupCol` - we need to do it
only for `batchLength` number of values.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks are [here](https://gist.github.com/yuzefovich/858c67e3ad79018e1c1e6dcfa8df9835).

Note that in case of the hash aggregation we're still are starting out with 1024 buckets in the hash table, and I'll be tuning that number in the follow-up PR.

**Review by asubiotto — CHANGES_REQUESTED** [review]
The point of the `Reset` method is to make benchmarks less noisy by removing the setup overhead from the benchmarks. I thought that was a good thing, no?

> Reviewed 30 of 30 files at r1, 31 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56879#-:-MMUyQRi-w5McU8VSlvp:b4ewcfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56879#-MMV9Zu7ETdVcCJ0efND:-MMV9Zu8CBJ5cS6m6A51:bj1egg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d79851a5b89c98bca17691c060ac11e01e39c8a/pkg/sql/colexec/hash_aggregator.go#L289)):*
> ```Go
> func (op *hashAggregator) setupScratchSlices(numBuffered int) {
> 	if len(op.scratch.eqChains) < numBuffered {
> 		op.scratch.eqChains = make([][]int, numBuffered)
> ```

I guess there's not much use to checking the capacity and slicing since `numBuffered` should practically always grow. What do you think?
___
*[pkg/sql/colexec/ordered_aggregator.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56879#-MMV9tM1BUcR3pJwdZqm:-MMV9tM29RVa6p_5PsYv:b-f88mei) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d79851a5b89c98bca17691c060ac11e01e39c8a/pkg/sql/colexec/ordered_aggregator.go#L83)):*
> ```Go
> 
> 	state struct {
> 		current, next orderedAggregatorState
> ```

Why two states? We've always handled this via a local variable I think

**Review by yuzefovich — COMMENTED** [review]
I find that having that `Reset` method inflates the numbers, and the question comes down to what do we like to measure: if we're interested in the throughput of an operator once it is instantiated, then `Reset` is useful; if we're interested in the throughput of an operator in a query setting, then I believe including the setup overhead is more realistic. I didn't find that there is a lot of noise with the removal if that's a concern.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56879#-:-MMWIfGuByrkZ0HxpnUx:bxltdqp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/hash_aggregator.go, line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56879#-MMV9Zu7ETdVcCJ0efND:-MMWJPRjEVJ7Zw9HF9yc:bmwkkew) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d79851a5b89c98bca17691c060ac11e01e39c8a/pkg/sql/colexec/hash_aggregator.go#L289)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I guess there's not much use to checking the capacity and slicing since `numBuffered` should practically always grow. What do you think?
</blockquote></details>

`numBuffered` is limited by `maxBuffered` field which is capped at `4 * coldata.BatchSize()`, so if have an input with 4k tuples, then we'll instantiate the slices with `maxBuffered` capacity and all consequent calls to this method will be noops, but if the input has less than 4k, then we instantiate the slices only with the required capacity (equal to the number of tuples in the input in this case).
___
*[pkg/sql/colexec/ordered_aggregator.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56879#-MMV9tM1BUcR3pJwdZqm:-MMWLqWG1ldGHDENiIKN:blv44iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d79851a5b89c98bca17691c060ac11e01e39c8a/pkg/sql/colexec/ordered_aggregator.go#L83)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why two states? We've always handled this via a local variable I think
</blockquote></details>

I think the only precedent when we need to "enqueue" two states that we have is the cfetcher, and it has a queue of states. Here we need to specify the follow-up state to the outputting state, so I thought I'd have these two states. I agree that it might be confusing, refactored.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 31 of 31 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56879#-:-MM_7q2j0j9FfNJmcOZ1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
