### PR TITLE
multiregionccl: implement trace analysis for REGIONAL BY ROW tables

### PR DESCRIPTION
**Pull request by pawalt**
Previously, we could only perform trace analysis to test if a single
query was performed locally and via a stale read. In REGIONAL BY ROW
queries, we run locality-optimized search, leading to multiple queries.
This PR adds trace analysis with knowledge of these semantics.

Release note: None

This functionality has been tested with `make stress` on a gceworker for 40 minutes with no failures.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhEYY-g9x7Y7wlwjkuW:-MhEYY-h5N3MYMUI47RA:b44oenr) ([raw file](https://github.com/cockroachdb/cockroach/blob/669e5680c3ad1db901fcabbd8af418fe2e91d631/pkg/ccl/multiregionccl/datadriven_test.go#L60)):*
> ```Go
> // server.
> //
> // "trace-sql idx=server_number [trace-analysis=simple]":
> ```

s/simple/trace_analysis_type/?
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5X25EWhRVXenqwjI:-MhP5X25EWhRVXenqwjJ:b6qcl77) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L72)):*
> ```Go
> //     locally.
> //   rbr:
> //     - attempted local search: prints true iff the locality-optimized search
> ```

let's call this "local region" search
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5_jIAYx3NPNCKQZx:-MhP5_jIAYx3NPNCKQZy:b9fkhpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L75)):*
> ```Go
> //     was executed on local data (as opposed to reaching out to the
> //     leaseholder)
> //     - served locality-optimized search via follower read: prints true iff the
> ```

let's call this "served local region search via follower read"
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5dUe4ChIBS7iFZ5o:-MhP5dUe4ChIBS7iFZ5p:b-wwk7kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L78)):*
> ```Go
> //     first search was local and served by a follower read. This is omitted
> //     completely if the first search was not local.
> //     - found in locality-optimized search: prints true iff there was only one
> ```

Let's call this "found in local region"
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5iWq1DRoHo3KQhlX:-MhP5iWq1DRoHo3KQhlY:b-m8y5w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L80)):*
> ```Go
> //     - found in locality-optimized search: prints true iff there was only one
> //     search executed.
> //     - served remote read via follower read: prints true iff the second read
> ```

Let's call this "served remote region read via follower read"
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP9QbJ-aSktLizIvhd:-MhP9QbJ-aSktLizIvhe:b9sajv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L542)):*
> ```Go
> // - if a remote read comes after the local read, the data was remote.
> // Semantics of the output are described in the command description at the top.
> func analyzeRegionalByRowQuery(rec tracing.Recording) (string, error) {
> ```

Have you given thought to how the trace analysis would change if there are more complex traces? I think this works for simple reads from regional by row tables, but what if we want to extend this to more complex queries, such as foreign key checks?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP4fRXDRDpbiadB1H2:-MhP4fRXDRDpbiadB1H3:bq2a4p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/testdata/regional_by_row#L37)):*
> ```
> # 1. Reads from leaseholder for row only look locally.
> # 2. Reads from voters look remotely but only to leaseholder.
> # 3. Reads from other leaseholders look locally first and then remotely.
> ```

other partition's leaseholders

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhEYY-g9x7Y7wlwjkuW:-MhPinzZ6wP6LjoH5dIR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/669e5680c3ad1db901fcabbd8af418fe2e91d631/pkg/ccl/multiregionccl/datadriven_test.go#L60)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/simple/trace_analysis_type/?
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5X25EWhRVXenqwjI:-MhPmUO67eHXxM97Hama:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L72)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

let's call this "local region" search
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5_jIAYx3NPNCKQZx:-MhPmUjV7eje1XgZgtsR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L75)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

let's call this "served local region search via follower read"
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5iWq1DRoHo3KQhlX:-MhPmV8O4ctNMAlXeZUB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L80)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's call this "served remote region read via follower read"
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP9QbJ-aSktLizIvhd:-MhPiqP4-hdxHsQ2jy58:blagnwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L542)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Have you given thought to how the trace analysis would change if there are more complex traces? I think this works for simple reads from regional by row tables, but what if we want to extend this to more complex queries, such as foreign key checks?
</blockquote></details>

I've put a bit of thought into it, but I'm not familiar enough with foreign key traces to say anything definitive. In any case, I don't think we'd want to modify this trace analysis. I think instead we should write new functions for the different types of analysis we want to perform. For example, a foreign key lookup will create extra lookups that we would want to reject in the context of a simple trace.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP4fRXDRDpbiadB1H2:-MhPjUzt09lPKyTD4MDG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/testdata/regional_by_row#L37)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

other partition's leaseholders
</blockquote></details>

Done.

**Review by arulajmani — COMMENTED** [review]
Sorry for coming back to this after so long. This is very close, I mostly have minor comments around wanting a little more words around tests. Should be ready to merge soon. 

How do you feel about splitting this single `regional_by_row` file into multiple files? You could put every "sketch" into its own file with an appropriate name. You only have to copy paste the initial cluster setup, but I don't think it's that bad considering it'll make this whole thing easier to read. Wdyt? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-:-MhsNyhgDD47P6DkQOKf:b5b1ee9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhsLxIGC1DHgm8GvC0y:-MhsLxIGC1DHgm8GvC0z:b-cglh73) ([raw file](https://github.com/cockroachdb/cockroach/blob/1034833a0d8967010ed44209c6ef1de27a81e65b/pkg/ccl/multiregionccl/testdata/regional_by_row#L86)):*
> ```
> # It's now follower read time. We'll attempt to perform follower reads to
> # us-central-1 and validate the following behavior:
> # 1. Leaseholder can serve follower reads
> ```

nit: I like how you've sketched this out here, but it might be useful to comment the particular scenario in line as well? What do you think? I found myself scrolling up and figuring out which index is what region and validating against this sketch a few times.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhsNAZaDMu18RDYuuie:-MhsNAZaDMu18RDYuuif:bpef4dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1034833a0d8967010ed44209c6ef1de27a81e65b/pkg/ccl/multiregionccl/testdata/regional_by_row#L104)):*
> ```
> ----
> served local region search on current node: true
> served local region search via follower read: false
> ```

I think we do this a few times, but I think it's worth calling out once that because the current node is the leaseholder it serves this historical read "normally" instead of a follower read (as a voter/non-voter would). 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhsMIiz66rMfYKDvJBw:-MhsMIiz66rMfYKDvJBx:b-kjey4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1034833a0d8967010ed44209c6ef1de27a81e65b/pkg/ccl/multiregionccl/testdata/regional_by_row#L149)):*
> ```
> # We expect:
> # - Old leaseholder (0) can no longer serve local reads
> # - Leaseholder (6) can immediately serve local lookups
> ```

I wouldn't call it "immediate" considering you have to do the whole "wait-for-zone_config-changes" bit 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhsMS8t3_GcLoOTLbdD:-MhsMS8uAgza7k6TmUYx:b-x5polp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1034833a0d8967010ed44209c6ef1de27a81e65b/pkg/ccl/multiregionccl/testdata/regional_by_row#L159)):*
> ```
> 
> # When (1, 1) is relocated to us-west-1, node 0 may no longer be the leaseholder
> # due to range collapsing. We wait here to ensure our leaseholders are where we
> ```

range collapsing?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhP5dUe4ChIBS7iFZ5o:-MhyPX_ODbMrkc8ub7FT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10ac78d338fb91358ac6c1c38c150fc6ae0b053/pkg/ccl/multiregionccl/datadriven_test.go#L78)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's call this "found in local region"
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhsNAZaDMu18RDYuuie:-MhyROV61iEt6WWQD-Rp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1034833a0d8967010ed44209c6ef1de27a81e65b/pkg/ccl/multiregionccl/testdata/regional_by_row#L104)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think we do this a few times, but I think it's worth calling out once that because the current node is the leaseholder it serves this historical read "normally" instead of a follower read (as a voter/non-voter would). 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhsMIiz66rMfYKDvJBw:-MhyRSQB08INFHKbyJeV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1034833a0d8967010ed44209c6ef1de27a81e65b/pkg/ccl/multiregionccl/testdata/regional_by_row#L149)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I wouldn't call it "immediate" considering you have to do the whole "wait-for-zone_config-changes" bit 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-MhsMS8t3_GcLoOTLbdD:-MhyPbx80PrwRBN9zXkd:b-rhpxx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1034833a0d8967010ed44209c6ef1de27a81e65b/pkg/ccl/multiregionccl/testdata/regional_by_row#L159)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

range collapsing? 
</blockquote></details>

Whoops I meant merging

**Review by arulajmani — APPROVED** [review]
Couple file name change suggestions, but otherwise :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-:-Mhyaner0UXgUpHyHA60:b-4scx12)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/testdata/regional_by_row_relocating, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-Mhy_rETE6jAKS5f_IuQ:-Mhy_rETE6jAKS5f_IuR:bcl3dwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/9252cfbe8e704b9ceece24944dcff94dc0db7d0a/pkg/ccl/multiregionccl/testdata/regional_by_row_relocating#L1)):*
> ```
> new-cluster localities=us-east-1,us-east-1,us-east-1,us-central-1,us-central-1,us-central-1,us-west-1,us-west-1,us-west-1,eu-central-1,eu-west-1
> ```

nit: rename this file `regional_by_row_relocate_row`? 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_row_simple, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-Mhy_dalCyecwMaFKaJk:-Mhy_dalCyecwMaFKaJl:b-y15wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9252cfbe8e704b9ceece24944dcff94dc0db7d0a/pkg/ccl/multiregionccl/testdata/regional_by_row_simple#L1)):*
> ```
> new-cluster localities=us-east-1,us-east-1,us-east-1,us-central-1,us-central-1,us-central-1,us-west-1,us-west-1,us-west-1,eu-central-1,eu-west-1
> ```

Let's rename this file `regional_by_row_present_time_reads` as a parallel to `regional_by_row_follower_reads`?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68968)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/multiregionccl/testdata/regional_by_row_simple, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68968#-Mhy_dalCyecwMaFKaJk:-Mhyc9EHC9R_fYoD6QPu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9252cfbe8e704b9ceece24944dcff94dc0db7d0a/pkg/ccl/multiregionccl/testdata/regional_by_row_simple#L1)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's rename this file `regional_by_row_present_time_reads` as a parallel to `regional_by_row_follower_reads`? 
</blockquote></details>

Done.

**Pull request closed without merging**
