### PR TITLE
storage: construct and return lock acquisitions from mvccPutInternal

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, callers that ended up in mvccPutInternal would construct lock acquisitions a few layers above where the lock was actually acquired (intent was written). We now construct a lock acquisition in mvccPutInternal and return it up the stack instead. It's plumbed all the way up, from mvccPutInternal and friends, to the various cmd_*.go files. For now, we don't actually make use of the returned lock acquisition -- we'll do so in a subsequent patch that resolves the linked issue.

Constructing a lock acquisition closer to where intents are written allows us to do so only in cases where no intents are written. This ensures the write timestamp on the transaction writing the intent is the same as the timestamp at which the intent was written. Notably, this excludes replays, where these two values could diverge.

Informs #112409

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 59 of 59 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RaduBerinde)

___
*[`pkg/storage/mvcc.go` line 1144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0uMOP8OatTmiLcYD2:-Ni0uMOP8OatTmiLcYD3:b4grwwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L1144)):*
> ```Go
> 	acq, err := MVCCBlindPut(ctx, rw, key, hlc.Timestamp{}, value, MVCCWriteOptions{Stats: ms})
> 	if !acq.Empty() {
> 		log.Fatalf(ctx, "inline write should not be within a transaction; lock acquisition found: %v", acq)
> ```

Does this cause the acquisition struct to escape to the heap?
___
*[`pkg/storage/mvcc.go` line 2608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0x7BmCVVzRQC65G_y:-Ni0x7BmCVVzRQC65G_z:bienbdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L2608)):*
> ```Go
> 			return false, roachpb.LockAcquisition{}, err
> 		}
> 		lockAcquisition = roachpb.MakeLockAcquisition(opts.Txn, metaKey.Key, lock.Replicated, lock.Intent)
> ```

Can we use `newMeta.Txn` instead of `opts.Txn` here? `opts.Txn` is the input to this function, but it's not entirely obvious that we haven't modified it before putting it into the intent. In fact, I think there is a case above ("If we bumped") where we do perform such a modification, and this doesn't get reflected in `opts.Txn`.

That may require us to change `MakeLockAcquisition` to accept a `TxnMeta` instead of `Transaction`, which feels like a reasonable change.
___
*[`pkg/storage/mvcc.go` line 3547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0y_lZ9pqcQq_7zrh5:-Ni0y_lZ9pqcQq_7zrh6:b7kd74c) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L3547)):*
> ```Go
> 	var keys []roachpb.Key
> 	var acqs []roachpb.LockAcquisition
> 	j := 0
> ```

Instead of maintaining `j`, can we just initialize `acqs` with a zero-length but sufficient capacity and then `append`? That also avoids the need to trim at the end.
___
*[`pkg/storage/mvcc.go` line 3614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0yzIZDcYyLQ04HCyn:-Ni0yzIZDcYyLQ04HCyo:b2wh69q) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L3614)):*
> ```Go
> 	rangeTombstoneThreshold int64,
> 	maxLockConflicts int64,
> ) (*roachpb.Span, []roachpb.LockAcquisition, error) {
> ```

These are always non-transactional writes, so will they ever return lock acquisitions?
___
*[`pkg/storage/mvcc_history_test.go` line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0z5nb0QDmrgErz1b7:-Ni0z5nb0QDmrgErz1b8:b-g0i2mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc_history_test.go#L1263)):*
> ```Go
> 			MaxLockConflicts:               e.getMaxLockConflicts(),
> 		}
> 		if _, err := storage.MVCCConditionalPut(e.ctx, rw, key, ts, val, expVal, behavior, opts); err != nil {
> ```

Should we assert on this output?

**Review by arulajmani — COMMENTED** [review]
TFTR; RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-:-Ni1E43c5KRy_-diE3os:bszxgi3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/storage/mvcc.go` line 1144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0uMOP8OatTmiLcYD2:-Ni12i-23Zm-ghZgYerJ:b-259wed) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L1144)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this cause the acquisition struct to escape to the heap?
</blockquote></details>

It does; I'll remove it from the log message.
___
*[`pkg/storage/mvcc.go` line 2608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0x7BmCVVzRQC65G_y:-Ni19X_34QaiTxz-jSZ7:b-naxgki) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L2608)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use `newMeta.Txn` instead of `opts.Txn` here? `opts.Txn` is the input to this function, but it's not entirely obvious that we haven't modified it before putting it into the intent. In fact, I think there is a case above ("If we bumped") where we do perform such a modification, and this doesn't get reflected in `opts.Txn`.

That may require us to change `MakeLockAcquisition` to accept a `TxnMeta` instead of `Transaction`, which feels like a reasonable change.
</blockquote></details>

Good catch. I ran with and without this change after adding assertions in `TestMVCCHistories`, and `put_new_epoch_lower_timestamp` and `put_out_of_order` failed without the change.
___
*[`pkg/storage/mvcc.go` line 3547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0y_lZ9pqcQq_7zrh5:-Ni14cX2DEafvld_x5XI:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L3547)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of maintaining `j`, can we just initialize `acqs` with a zero-length but sufficient capacity and then `append`? That also avoids the need to trim at the end.
</blockquote></details>

Done. 
___
*[`pkg/storage/mvcc.go` line 3614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0yzIZDcYyLQ04HCyn:-Ni14e-e591qDazH4KCm:bo9z6bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc.go#L3614)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

These are always non-transactional writes, so will they ever return lock acquisitions?
</blockquote></details>

Good catch. Reverted and added an assertion.
___
*[`pkg/storage/mvcc_history_test.go` line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni0z5nb0QDmrgErz1b7:-Ni1Dy0OE8hsSjOzynRj:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32b02c1d324e6e98239818cc3fc9a5eb1d572/pkg/storage/mvcc_history_test.go#L1263)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we assert on this output?
</blockquote></details>

Done.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/storage/testdata/mvcc_histories/put_without_txn` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni1FBj5-tXw-EB6utcM:-Ni1FBj5-tXw-EB6utcN:b7m0j25) ([raw file](https://github.com/cockroachdb/cockroach/blob/93bf4c3e432b9ee6f69a8c9f5a1d5f7524373019/pkg/storage/testdata/mvcc_histories/put_without_txn#L9)):*
> ```
> ----
> >> put v=v ts=0,1 k=k
> put: lock acquisition = {/Min id=00000000 key=/Min iso=Serializable pri=0.00000000 epo=0 ts=0,0 min=0,0 seq=0 Unreplicated None []}
> ```

I'm gonna skip printing these if the lock acquisition is empty.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/storage/testdata/mvcc_histories/put_without_txn` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni1FBj5-tXw-EB6utcM:-Ni1Hn287xO3RgAxq4v0:b-2y5vlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/93bf4c3e432b9ee6f69a8c9f5a1d5f7524373019/pkg/storage/testdata/mvcc_histories/put_without_txn#L9)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm gonna skip printing these if the lock acquisition is empty.
</blockquote></details>

Decided to print "empty" instead. That way, `write_with_sequence` tests our replay scenario more explicitly. Happy to do things differently if this feels unnecessarily verbose.

**Review by nvb — APPROVED** [review]
> Reviewed 26 of 100 files at r2, 74 of 74 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RaduBerinde)

___
*[`pkg/storage/testdata/mvcc_histories/put_without_txn` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni1FBj5-tXw-EB6utcM:-Ni29iWa2rMiXf7gkdEX:b-t09rap) ([raw file](https://github.com/cockroachdb/cockroach/blob/93bf4c3e432b9ee6f69a8c9f5a1d5f7524373019/pkg/storage/testdata/mvcc_histories/put_without_txn#L9)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Decided to print "empty" instead. That way, `write_with_sequence` tests our replay scenario more explicitly. Happy to do things differently if this feels unnecessarily verbose.
</blockquote></details>

In most cases, it seems fine, but there are a few files where it does get pretty noisy with dozens of `put: lock acquisition = empty`. I'd be supportive of skipping printing in these cases. That would mirror what we do for other optional outputs like resume spans.

**Review by arulajmani — COMMENTED** [review]
Thanks! 

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-:-Ni52XrgEygZdDSFoE5_:bui1ko0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/storage/testdata/mvcc_histories/put_without_txn` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113295#-Ni1FBj5-tXw-EB6utcM:-Ni52WsB0f8lpyRq4-r3:bjby8ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/93bf4c3e432b9ee6f69a8c9f5a1d5f7524373019/pkg/storage/testdata/mvcc_histories/put_without_txn#L9)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

In most cases, it seems fine, but there are a few files where it does get pretty noisy with dozens of `put: lock acquisition = empty`. I'd be supportive of skipping printing in these cases. That would mirror what we do for other optional outputs like resume spans.
</blockquote></details>

Makes sense, switched to only printing these when the lock acquisition is non-empty.

**Comment by arulajmani** [comment]
bors r=nvanbenschoten

**Comment by arulajmani** [comment]
blathers backport 23.2

**Pull request merged**
