### PR TITLE
stats: fix and unskip flaky test TestCreateStatsProgress

### LINKED ISSUE #52782: opt: TestCreateStatsProgress flaky
@yuzefovich saw a failure of this test on 19.2.

There is also a record of a failure on master here: https://github.com/cockroachdb/cockroach/issues/43564#issuecomment-670988572

### PR DESCRIPTION
**Pull request by rytaft**
Release justification: non-production code changes

This commit fixes the flaky test `TestCreateStatsProgress` and unskips
it. `TestCreateStatsProgress` was flaky because of the recent changes to
the stats cache, which removed the guarantee that fresh stats would be
available in the cache immediately after stats creation. This commit
fixes the issue by explicitly invalidating the stats cache before the
part of `TestCreateStatsProgress` that expects certain stats to be present.

Fixes #52782

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53681#-:-MG4MKuE4ieNS8DfQ_WS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/stats/create_stats_job_test.go, line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53681#-MG4Lw0G0jghNxfVioZt:-MG4Lw0G0jghNxfVioZu:b-sat27m) ([raw file](https://github.com/cockroachdb/cockroach/blob/581d46fb4eadbe2477c627fd31dd3b60e343eaae/pkg/sql/stats/create_stats_job_test.go#L610)):*
> ```Go
> 
> 	// Invalidate the stats cache so that we can be sure to get the latest stats.
> 	tableID := descpb.ID(53)
> ```

[nit] would be nice to get the table ID programatically (`SELECT id FROM system.namespace WHERE name = 't'`)

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53681#-:-MG4PE126HfXps9UtN5L:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/stats/create_stats_job_test.go, line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53681#-MG4Lw0G0jghNxfVioZt:-MG4O41v2tzwSH6OsxGK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/581d46fb4eadbe2477c627fd31dd3b60e343eaae/pkg/sql/stats/create_stats_job_test.go#L610)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would be nice to get the table ID programatically (`SELECT id FROM system.namespace WHERE name = 't'`)
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53681#-:-MG4PNN11DqgeVy_QWVY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
