### PR TITLE
opt: add support for IFERROR/ISERROR

### PR DESCRIPTION
**Pull request by justinj**
This commit introduces the IFERROR/ISERROR scalar operators. See #25304
for more background on these operators.

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ops/scalar.opt, line 595 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNqqGr4iW2Al64iajJ:-LTNqqGsAq3Ky0MVVXZZ:b-fc6ebk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L595)):*
> ```
> }
> 
> # IfErr is roughly a runtime try-catch operator. It has different semantics
> ```

Nice comment!
___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNpwQV6CfxhToF4tkc:-LTNpwQV6CfxhToF4tkd:b-o2piow) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/optbuilder/testdata/scalar#L1142)):*
> ```
>  │    ├── const: 1 [type=int]
>  │    └── const: 0 [type=int]
>  └── const: '22012' [type=string]
> ```

How do we know this is the error code and not the else statement? Maybe the formatter should print labels?
___
*[pkg/sql/sem/tree/testdata/eval/conditional, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNqTyYD4O_31SLwGGK:-LTNqTyYD4O_31SLwGGL:bczlmvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/sem/tree/testdata/eval/conditional#L39)):*
> ```
> 
> eval
> (ISERROR((1/0)::STRING, '22012'), IFERROR((1/0)::STRING, '22012'))
> ```

How does this work if there is a hash collision? (According to your comment in `scalar.opt`)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ops/scalar.opt, line 603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTOKfyY3I1GnkBSwuK2:-LTOKfyY3I1GnkBSwuK3:b6is0gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L603)):*
> ```
> # 1. If an error is *not* caught while evaluating Cond:
> #   a. If OrElse is set, IfErr evaluates to the value of Cond.
> #   b. If OrElse is not set, IfErr evaluates to false.
> ```

This is quite the semantic difference.. I think having separate operators would make more sense, and they'd be easier to  understand. (and it would resolve the optional hack).
___
*[pkg/sql/opt/ops/scalar.opt, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTOJl1JD6bFwbvSPt6Z:-LTOJl1JD6bFwbvSPt6_:bnfpdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L614)):*
> ```
> # handling for hoisting is needed.
> #
> # TODO(justin): The implementation here is a hack: ErrCode and OrElse are
> ```

Isn't `ErrCode` of `NULL` equivalent to not having a code? We could make it be non-optional and build it to NULL as necessary.

**Review by andy-kimball — COMMENTED** [review]
It looks like you're missing a change to `deriveHasHoistableSubquery`. We should not allow subqueries to be hoisted out of these new operators (also need tests for this).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-:-LTOaTkjD6k7WkwG4VPT:bi0vwd4)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by justinj — COMMENTED** [review]
Ah, you're right, I had somehow convinced myself that regular handling of side-effects was sufficient. Fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-:-LTP0rhpA5Tz3gjsVAwf:b-w8muqo)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ops/scalar.opt, line 603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTOKfyY3I1GnkBSwuK2:-LTP0GM67aVgo-6wE582:bp1nzua) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L603)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is quite the semantic difference.. I think having separate operators would make more sense, and they'd be easier to  understand. (and it would resolve the optional hack).
</blockquote></details>

I'm torn, I do agree the semantics are quite different, but I think having multiple of these might be more trouble than it's worth (especially since there's a single AST node for them). It also wouldn't resolve the optional hack, since `ErrCode` is optional for both expressions (and like I mentioned below, it's not sufficient to use `NULL` in place of not set).

I'm happy to change it if you feel strongly, at the moment I feel a little happier with the weirdness of this (pretty obscure) operator hidden away inside of a single operator rather than spread out across two.
___
*[pkg/sql/opt/ops/scalar.opt, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTOJl1JD6bFwbvSPt6Z:-LTOTyCv9K3y0wISYYNe:bvhzwk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L614)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Isn't `ErrCode` of `NULL` equivalent to not having a code? We could make it be non-optional and build it to NULL as necessary.
</blockquote></details>

Unfortunately not:
```
root@127.0.0.1:53560/defaultdb> select iserror(1/0);
  iserror
+---------+
   true
(1 row)

root@127.0.0.1:53560/defaultdb> select iserror(1/0, null);
pq: division by zero
```
___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNpwQV6CfxhToF4tkc:-LTOU6TF-sQQzyHuVOQk:b-nv4vaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/optbuilder/testdata/scalar#L1142)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

How do we know this is the error code and not the else statement? Maybe the formatter should print labels?
</blockquote></details>

It's non-ambiguous because of the type of the expression (I tried to find an ambiguous case and couldn't), though you're right it's a bit annoying to read. I changed it to be clearer, though I think the result is a little gross.
___
*[pkg/sql/sem/tree/testdata/eval/conditional, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNqTyYD4O_31SLwGGK:-LTP-kddCSe6KUCo5YG_:br1jcye) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/sem/tree/testdata/eval/conditional#L39)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

How does this work if there is a hash collision? (According to your comment in `scalar.opt`)
</blockquote></details>

The interner handles hash collisions safely - I guess I just mentioned it to like...build up intuition in the reader? I'm not sure, there isn't really anything actionable based on that fact (though this test *was* written to verify the interner handles those collisions safely).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ops/scalar.opt, line 603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTOKfyY3I1GnkBSwuK2:-LTPA6AK4bGQbNrs6P4a:b-a5zhvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L603)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I'm torn, I do agree the semantics are quite different, but I think having multiple of these might be more trouble than it's worth (especially since there's a single AST node for them). It also wouldn't resolve the optional hack, since `ErrCode` is optional for both expressions (and like I mentioned below, it's not sufficient to use `NULL` in place of not set).

I'm happy to change it if you feel strongly, at the moment I feel a little happier with the weirdness of this (pretty obscure) operator hidden away inside of a single operator rather than spread out across two.
</blockquote></details>

Fine with me either way. I'd just make the description easier to read:

```
If OrElse is not set, IfErr evaluates to true or false indicating if an error was caught.

If OrElse is set, IfErr evaluates to Cond if no error was caught and to OrElse if an error was caught.
```
___
*[pkg/sql/opt/ops/scalar.opt, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTOJl1JD6bFwbvSPt6Z:-LTP9l3g3W_fPj6jDLeV:b-q454ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L614)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Unfortunately not:
```
root@127.0.0.1:53560/defaultdb> select iserror(1/0);
  iserror
+---------+
   true
(1 row)

root@127.0.0.1:53560/defaultdb> select iserror(1/0, null);
pq: division by zero
```
</blockquote></details>

Oh, I see, I don't remember why I thought NULL would work. If this was a bigger/more important feature, I'd say we could add a special `AnyError` scalar operator just for this. But as you point out, this is a pretty obscure thing so maybe it's best to keep it as contained as possible.
___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNpwQV6CfxhToF4tkc:-LTPAr5yBSwMRtF3hM3r:be11nal) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/optbuilder/testdata/scalar#L1142)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

It's non-ambiguous because of the type of the expression (I tried to find an ambiguous case and couldn't), though you're right it's a bit annoying to read. I changed it to be clearer, though I think the result is a little gross.
</blockquote></details>

Instead of adding `else (none)` or `err-code (none)`, I would add an `else / err-code` node for the cases where there is one. So here we would have `if-err -> err-code -> const:..`

**Review by rytaft — DISMISSED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNpwQV6CfxhToF4tkc:-LTPDU2X55roQKLTC_ND:bnvhxjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/optbuilder/testdata/scalar#L1142)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Instead of adding `else (none)` or `err-code (none)`, I would add an `else / err-code` node for the cases where there is one. So here we would have `if-err -> err-code -> const:..`
</blockquote></details>

+1 to what Radu said
___
*[pkg/sql/sem/tree/testdata/eval/conditional, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNqTyYD4O_31SLwGGK:-LTPDajZ2sdbeKGOfBEP:b-4k1dof) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/sem/tree/testdata/eval/conditional#L39)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

The interner handles hash collisions safely - I guess I just mentioned it to like...build up intuition in the reader? I'm not sure, there isn't really anything actionable based on that fact (though this test *was* written to verify the interner handles those collisions safely).
</blockquote></details>

Ah ok -- I think it would help if you update that comment to make it clear that there is no problem even in case of collision.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/sem/tree/testdata/eval/conditional, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNqTyYD4O_31SLwGGK:-LTPkTHl29CUvTCdxkFs:b-h5d2x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/sem/tree/testdata/eval/conditional#L39)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ah ok -- I think it would help if you update that comment to make it clear that there is no problem even in case of collision.
</blockquote></details>

I think that comment adds confusion more than anything. The hashing is mostly an internal detail of the memo, I don't think it should be mentioned in `.opt` files (plus we could easily fix up this case if we cared to).

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ops/scalar.opt, line 603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTOKfyY3I1GnkBSwuK2:-LTSvI7lE634LCVuMj99:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/ops/scalar.opt#L603)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Fine with me either way. I'd just make the description easier to read:

```
If OrElse is not set, IfErr evaluates to true or false indicating if an error was caught.

If OrElse is set, IfErr evaluates to Cond if no error was caught and to OrElse if an error was caught.
```
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNpwQV6CfxhToF4tkc:-LTSvMY_8_8jhdgYuZGl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/opt/optbuilder/testdata/scalar#L1142)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

+1 to what Radu said
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/testdata/eval/conditional, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-LTNqTyYD4O_31SLwGGK:-LTSvNN83dNziJGKGeMW:b8oj2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f656e84cec368496f3a9509740326129766af11/pkg/sql/sem/tree/testdata/eval/conditional#L39)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think that comment adds confusion more than anything. The hashing is mostly an internal detail of the memo, I don't think it should be mentioned in `.opt` files (plus we could easily fix up this case if we cared to).
</blockquote></details>

Done, removed the comment.

**Review by rytaft — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32957#-:-LTSyD7dBPwt7I9tRTCI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by justinj** [comment]
TFTRs!

bors r+

**Pull request merged**
