### PR TITLE
workload/tpch: augment Q15 with streamID for concurrency

### LINKED ISSUE #79870: roachtest: tpch_concurrency failed
roachtest.tpch_concurrency [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4867638&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4867638&tab=artifacts#/tpch_concurrency) on master @ [9b80166bc5f3d3d1212c44a9e1ac219d458af9e0](https://github.com/cockroachdb/cockroach/commits/9b80166bc5f3d3d1212c44a9e1ac219d458af9e0):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/tpch_concurrency/run_1
	test_runner.go:1006,test_runner.go:905: test timed out (18h0m0s)
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpch_concurrency.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-15885

### PR DESCRIPTION
**Pull request by yuzefovich**
According to the TPC-H spec, Q15 can be augmented with the streamID
identifier so that Q15 could run with concurrency, so this commit
implements that. This ability is now used by the `tpch_concurrency`
roachtest in order to remove the number of retries that were occurring
when trying to create and drop the view named `revenue0`.

Fixes: #79870.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82330)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/workload/tpch/queries.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82330#-N3XX55O2-fM5N_uLuHv:-N3XX55O2-fM5N_uLuHw:b-vmpsvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/598b8de5c4b9808296225519c9f660634cb66197/pkg/workload/tpch/queries.go#L52)):*
> ```Go
> 
> 	// NumQueries specifies the number of queries in TPC-H benchmark.
> 	NumQueries = len(queriesByNumber)
> ```

I think we can make this change more minimal with the following:
```go
func makeQueriesForStream(streamID int) map[int]string {
     return Queries{
		1:  query1,
		2:  query2,
		3:  query3,
		4:  query4,
		5:  query5,
		6:  query6,
		7:  query7,
		8:  query8,
		9:  query9,
		10: query10,
		11: query11,
		12: query12,
		13: query13,
		14: query14,
		15: fmt.Sprintf(query15template, streamID),
		16: query16,
		17: query17,
		18: query18,
		19: query19,
		20: query20,
		21: query21,
		22: query22,
     }
}

// QueriesByNumber is a mapping from the number of a TPC-H query to the actual
// query for stream 0.
var QueriesByNumber = makeQueriesForStreamID(0)
```

Then for the worker:

```go
type worker struct {
	config   *tpch
	hists    *histogram.Histograms
	db       *gosql.DB
	ops      int
	queries map[int]string
}
//...
		worker := &worker{
			config:   w,
			hists:    reg.GetHandle(),
			db:       db,
			queries: makeQueriesForStreamID(i),
		}

//... 
query := fmt.Sprintf("%s %s", prefix, w.queries[queryNum])
``
```




_Code quote:_
```Go
	// Note that Q15 is a "format-string template" expecting a single
	// non-negative integer argument (i.e. it should be used as
	// fmt.Sprintf(query15, <id>) where <id> is an integer).
	queriesByNumber = map[int]string{
		1:  query1,
		2:  query2,
		3:  query3,
		4:  query4,
		5:  query5,
		6:  query6,
		7:  query7,
		8:  query8,
		9:  query9,
		10: query10,
		11: query11,
		12: query12,
		13: query13,
		14: query14,
		15: query15,
		16: query16,
		17: query17,
		18: query18,
		19: query19,
		20: query20,
		21: query21,
		22: query22,
	}

	// NumQueries specifies the number of queries in TPC-H benchmark.
	NumQueries = len(queriesByNumber)
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82330)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @michae2)

___
*[`pkg/workload/tpch/queries.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82330#-N3XX55O2-fM5N_uLuHv:-N3XsKtM5yqje6BXw_lF:be7jc42) ([raw file](https://github.com/cockroachdb/cockroach/blob/598b8de5c4b9808296225519c9f660634cb66197/pkg/workload/tpch/queries.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think we can make this change more minimal with the following:
```go
func makeQueriesForStream(streamID int) map[int]string {
     return Queries{
		1:  query1,
		2:  query2,
		3:  query3,
		4:  query4,
		5:  query5,
		6:  query6,
		7:  query7,
		8:  query8,
		9:  query9,
		10: query10,
		11: query11,
		12: query12,
		13: query13,
		14: query14,
		15: fmt.Sprintf(query15template, streamID),
		16: query16,
		17: query17,
		18: query18,
		19: query19,
		20: query20,
		21: query21,
		22: query22,
     }
}

// QueriesByNumber is a mapping from the number of a TPC-H query to the actual
// query for stream 0.
var QueriesByNumber = makeQueriesForStreamID(0)
```

Then for the worker:

```go
type worker struct {
	config   *tpch
	hists    *histogram.Histograms
	db       *gosql.DB
	ops      int
	queries map[int]string
}
//...
		worker := &worker{
			config:   w,
			hists:    reg.GetHandle(),
			db:       db,
			queries: makeQueriesForStreamID(i),
		}

//... 
query := fmt.Sprintf("%s %s", prefix, w.queries[queryNum])
``
```

</blockquote></details>

Indeed, very elegant, thanks!

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82330#-:-N3_KKbW3b_hUh7a1Pnu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
