### PR TITLE
sql: remove the Executor reference from Session

### PR DESCRIPTION
**Pull request by a6802739**
@knz , please see #10096, and let me know if I done it right. thanks a lot.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10100)

### CODE REVIEW

**Comment by knz** [comment]
The goal of #10096 was to remove the executor field from Session entirely. This PR is not doing that :)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-:-KUVci8YIbA0U4etj_7S:b-utkpk9)*

**Comment by knz** [comment]
Thanks for this!

@nvanbenschoten what do you think? Does this seem reasonable?

**Comment by a6802739** [comment]
@knz , thanks for your review.

**Comment by nvanbenschoten** [comment]
Yeah this seems like a good idea to me. Thanks @songhao!

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUbihMiEmA-z4Qp14zg:-KUbihMiEmA-z4Qp14zh:b-pkeyda) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L178)):*
> ```Go
> // Finish releases resources held by the Session.
> func (s *Session) Finish(e *Executor) {
> 	// Cleanup leases. We might have unreleased leases if we're finishing the
> ```

Where is this new logic coming from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-:-KUbizl0z2hGUiUt4V3C:bo8qgjv)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUbihMiEmA-z4Qp14zg:-KUbl_GEhx_C-cMIgV6n:b-mh5hyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Where is this new logic coming from?
</details>
It looks like a borked rebase. @songhao please check in the latest master commit how the `Finish` method is implemented and use that instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by a6802739** [comment]
@knz,I update my latest master branch,  I found In `pkg/sql/session.go`, it's just like
```
// Finish releases resources held by the Session.
func (s *Session) Finish() {
	// If we're inside a txn, roll it back.
	if s.TxnState.State.kvTxnIsOpen() {
		s.TxnState.updateStateAndCleanupOnErr(
			errors.Errorf("session closing"), s.executor)
	}
```
so, I have to pass the parameter `*Executor` to replace `s.executor` in `s.TxnState.updateStateAndCleanupOnErr(
			errors.Errorf("session closing"), s.executor)`.

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUbihMiEmA-z4Qp14zg:-KUmWiBpepl-BThr50ML:be7nnno) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L178)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> It looks like a borked rebase. @songhao please check in the latest master commit how the `Finish` method is implemented and use that instead.
</details>
@songhao once more please look at the full diff on your side, for example with `git diff master` from here. Look at what is happening, you have introduced a call to `.releaseLeases()` and `FinishEventLog` at the beginning of the `Finish()` method, whereas these two calls already exist  10 lines lower in the code! This is duplicate code now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by a6802739** [comment]
@knz , yeah, it's my mistake, I have change it now.

Appreciate it very much.

**Comment by knz** [comment]
:lgtm: now.

@andreimatei can you also have a look please and see if this makes sense to you too.

---

Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-:-KUr4EA9g842KhE1WEgG:bbfcxl2)*

**Comment by andreimatei** [comment]
:lgtm:

Thanks for cleaning this up

---

Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/planner.go, line 339 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUrMJL1SWsv75a_uJMX:-KUrMJL2FzALL44ulPBm:b-8al6x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0c09fc33e448340909049e9ff1db9d48a6022/pkg/sql/planner.go#L339)):*
> ```Go
> }
> 
> func (p *planner) virtualSchemas() *virtualSchemaHolder {
> ```

nit: remove this accessor, now that it's doing even less than before

We don't tend to have such simple accessors in the code, particularly if they're not "more exported" than the field they're providing access to. In particular, clients of `planner` already access `p.session` directly for a bunch of stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-:-KUrMzh3-ApkvYlKlk34:bkat5oz)*

**Comment by tamird** [comment]
Reviewed 2 of 6 files at r1, 3 of 4 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by tamird** [comment]
@a6802739 merge whenever you're ready (I've made you a collaborator). Thanks for your contributions!

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUbihMiEmA-z4Qp14zg:-KUrvpTloArRQTVtbH9F:b-1wxcdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L178)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> @songhao once more please look at the full diff on your side, for example with `git diff master` from here. Look at what is happening, you have introduced a call to `.releaseLeases()` and `FinishEventLog` at the beginning of the `Finish()` method, whereas these two calls already exist  10 lines lower in the code! This is duplicate code now.
</details>
this was fixed, cool. @a6802739 please mark such discussions with the "done" button in Reviewable, or otherwise write a reply, so people know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by a6802739** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUbihMiEmA-z4Qp14zg:-KUtkI1pC83rBCZ7a3je:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L178)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> this was fixed, cool. @a6802739 please mark such discussions with the "done" button in Reviewable, or otherwise write a reply, so people know.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by a6802739** [comment]
Done

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-:-KUtlP7G56TRCfgloFhC:bb6un1j)*

**Comment by a6802739** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUbihMiEmA-z4Qp14zg:-KUtlYUm_wnB42NNNfAG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L178)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by a6802739** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUbihMiEmA-z4Qp14zg:-KUtm5APB_5a4tHu0d12:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L178)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> Done.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by a6802739** [comment]
*[pkg/sql/session.go, line 181 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100#-KUtmTwFddlV3rziItCG:-KUtmTwFddlV3rziItCH:bb6p4lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f3840303db5f77033559b57a0e842b25ed38d2/pkg/sql/session.go#L181)):*
>  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10100)*

**Comment by a6802739** [comment]
@tamird, thanks a lot. But I still don't know how to merge this PR.

**Comment by knz** [comment]
You do not see the big green button? See this screenshot:
schermafdruk_2016-10-25_09-31-01

**Comment by a6802739** [comment]
@knz  No, I Cann't see it.

96270c089f76db3942042c171dff7911

**Comment by knz** [comment]
Ok sorry for the inconvenience, there is some permission issue.
I'll let @tamird investigate the permission, but in the meantime I am merging this for you.

Again many thanks for your help!

**Comment by tamird** [comment]
@a6802739 I've invited you to the organization, but your invite is still pending. Perhaps check your email.

**Pull request merged**
