### PR TITLE
roachprod: add ability to specify SSD count

### PR DESCRIPTION
**Pull request by pbardea**
This adds a flag to roachprod to specify the number of SSDs. This is
based off of #40801, but with a log message to notify the user upon
changing of the flag if it sees an n2 machine type, if not enough SSDs
were provided.

Release note: None

### CODE REVIEW

**Review by bobvawter — COMMENTED** [review]
If this is GCE-specific, it should go into

https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachprod/vm/gce/gcloud.go#L247

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42444#-:-Lt_UT--D2G0ytLUwrDY:byaxh38)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @nvanbenschoten)

**Review by pbardea — COMMENTED** [review]
Thanks for taking a look! I moved the gcloud specific flags to the appropriate file. Also added a check that we're only auto-updating the flag when a machine of the correct size is requested. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42444#-:-Ltf99T8Dmi4ZQYQHzXN:b-94swhj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by bobvawter — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42444)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by pbardea** [comment]
TFTR! bors r+

**Pull request merged**
