### PR TITLE
CRDB-31650 : Add Spot instance support to roachtest 

### PR DESCRIPTION
**Pull request by BabuSrithar**
Fixes CRDB-31650 

Add UseSpot instance option.

### CODE REVIEW

**Review by DarrylWong — APPROVED** [review]
Changes LGTM assuming there will be a eventual followup PR to add AWS spot instance support?

**Review by RaduBerinde — APPROVED** [review]
:lgtm: with some comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113741#-:-Niet2jR8tD-RzC3xIrN:b-wkd30r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @BabuSrithar, @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/spec/option.go` line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113741#-NieseEJ1Nt0gdlmkj1F:-NieseEJ1Nt0gdlmkj1G:b-rsuwsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b493b312b532f79339d6d58984ba777a1318dbcd/pkg/cmd/roachtest/spec/option.go#L188)):*
> ```Go
> }
> 
> // UseSpot creates a spot instance or equivalent of a cloud provider.
> ```

Mention that this is best effort, depending on cloud.

Would be useful to include more information here  about what a spot instance is and when it should or should not be used.
___
*[`pkg/cmd/roachtest/spec/option.go` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113741#-Niesq-O-WnjFtYu78Se:-Niesq-O-WnjFtYu78Sf:b5k8gc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b493b312b532f79339d6d58984ba777a1318dbcd/pkg/cmd/roachtest/spec/option.go#L189)):*
> ```Go
> 
> // UseSpot creates a spot instance or equivalent of a cloud provider.
> func UseSpot() Option {
> ```

[nit] `UseSpotInstances`

**Comment by BabuSrithar** [comment]
@DarrylWong , AWS, we will add in the future, the next follow-up PR is to detect VM preemptions in GCP.

**Comment by BabuSrithar** [comment]
*[`pkg/cmd/roachtest/spec/option.go` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113741#-Niesq-O-WnjFtYu78Se:-NimlUtN5fMfKlmRlEK1:b-p8ukv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b493b312b532f79339d6d58984ba777a1318dbcd/pkg/cmd/roachtest/spec/option.go#L189)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `UseSpotInstances`
</blockquote></details>

Refactored. Thanks!

**Comment by BabuSrithar** [comment]
*[`pkg/cmd/roachtest/spec/option.go` line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113741#-NieseEJ1Nt0gdlmkj1F:-NimlZYWENJSV01Qp9ku:b66h52q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b493b312b532f79339d6d58984ba777a1318dbcd/pkg/cmd/roachtest/spec/option.go#L188)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Mention that this is best effort, depending on cloud.

Would be useful to include more information here  about what a spot instance is and when it should or should not be used.
</blockquote></details>

Added additional commands.

**Comment by BabuSrithar** [comment]
*[`pkg/cmd/roachtest/spec/option.go` line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113741#-NieseEJ1Nt0gdlmkj1F:-Nimle452Mk4stW2PUWA:b9xv1tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b493b312b532f79339d6d58984ba777a1318dbcd/pkg/cmd/roachtest/spec/option.go#L188)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

Added additional commands.
</blockquote></details>

* comments

**Review by RaduBerinde — APPROVED** [review]
:lgtm: thanks!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113741#-:-Nioj2V54I9DjQIoezLn:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

**Pull request merged**
