### PR TITLE
opt: Eliminate unnecessary Max1Row operators

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR has two parts:

1. Rename logical and physical factory to builder (cleanup)
2. Add Cardinality logical property, in order to eliminate unnecessary Max1Row operators

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm: very nice!

---

Reviewed 8 of 11 files at r1, 36 of 40 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/cardinality_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyDkIM-EobnmV5ED53:-LAyDkIM-EobnmV5ED54:b-ki687v) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf856565dba0b7a038a13549713e9bcdfec084f1/pkg/sql/opt/memo/cardinality_test.go#L36)):*
> ```Go
> 	test(Cardinality{Min: 1, Max: 10}.Filter(0), "[0 - 10]")
> 	test(Cardinality{Min: 5, Max: 10}.Filter(1), "[1 - 10]")
> 	test(Cardinality{Min: 1, Max: 10}.Filter(20), "[1 - 10]")
> ```

What about a filter value between min and max:

 ```
 test(Cardinality{Min: 1, Max: 10}.Filter(5), "[1 - 10]")
 ```

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 431 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyGO5wDR0eO4qdXrVJ:-LAyGO5wDR0eO4qdXrVK:bny3ogj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf856565dba0b7a038a13549713e9bcdfec084f1/pkg/sql/opt/memo/logical_props_builder.go#L431)):*
> ```Go
> 	*props.Relational = *inputProps
> 
> 	// Max1Row ensures that the zero or one row is returned by input.
> ```

the zero -> zero

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-:-LAyZq_Z409tVgNfwIKM:bhnhlex)*

**Comment by RaduBerinde** [comment]
:lgtm: modulo a couple of comments.

---

Review status: 4 of 44 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/cardinality.go, line 33 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyrV3d0Kz07fwfQDY4:-LAyrV3d0Kz07fwfQDY5:bk74885) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/cardinality.go#L33)):*
> ```Go
> 
> // Cardinality is the number of rows that can be returned by a relational
> // expression. Both Min and Max are inclusive bounds. If Max = math.MaxUint32,
> ```

Maybe mention that these values are determined from the relational properties, and not from statistics (so they are never incorrect.

---

*[pkg/sql/opt/memo/cardinality.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAypiOD3QqBVXf8VN1Y:-LAypiOD3QqBVXf8VN1Z:by7cs3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/cardinality.go#L43)):*
> ```Go
> // Filter ratchets the min bound downwards in order to ensure that it's no
> // larger than the given min value.
> func (c Cardinality) Filter(min uint32) Cardinality {
> ```

[nit] I don't think `Filter` is a good name, the relation is fairly weak. Maybe `AsLowAs`?

---

*[pkg/sql/opt/xform/explorer.go, line 365 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyu1MvBw7MJdN3WSWa:-LAyu1MvBw7MJdN3WSWb:b-9og2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/xform/explorer.go#L365)):*
> ```Go
> 	scanOpDef := e.mem.LookupPrivate(def).(*memo.ScanOpDef)
> 	if scanOpDef.HardLimit != 0 {
> 		// Can't push limit into scan if scan is already limited.
> ```

Can't we push it if it's smaller?

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAx3sr21gLc0xYFLaId:-LAys0LAEAixC4xs6-HW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4869fba04606a990443e48c1c322f52494997ff9/pkg/sql/opt/memo/logical_props_builder.go#L523)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

FullJoin appears in both, since it acts like LeftJoin and RightJoin.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 115 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyuT4sAXgutf8XQDFq:-LAyuT4t-CwyoR8Coqz5:bqerc8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/logical_props_builder.go#L115)):*
> ```Go
> 		props.Relational.Cardinality = Cardinality{Max: uint32(def.HardLimit)}
> 	}
> ```

Maybe as a TODO - we could limit the cardinality to <=1 if the index is unique and the scan is fully constrained (i.e. ExactPrefix(constraint) = # of columns in index). And it's not constrained to any NULL values

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 293 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyqwoX0dqHpKwn-Ooo:-LAyqwoX0dqHpKwn-Oop:b-ehwqgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/logical_props_builder.go#L293)):*
> ```Go
> 		props.Relational.Cardinality = OneCardinality
> 	} else {
> 		// GroupBy acts like a filter, never returning more rows than input has.
> ```

[nit] the input

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 409 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyrmxQ2HHlDwdlMeL0:-LAyrmxQ2HHlDwdlMeL1:b-ex7qo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/logical_props_builder.go#L409)):*
> ```Go
> 	}
> 
> 	// Offset decreases number of rows that are passed through from input.
> ```

[nit] the number, from the input

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 511 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAys4pm7L8OksLR4G3G:-LAys4pm7L8OksLR4G3H:b-mjsqh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/logical_props_builder.go#L511)):*
> ```Go
> 	case opt.SemiJoinOp, opt.AntiJoinOp, opt.SemiJoinApplyOp, opt.AntiJoinApplyOp:
> 		// Semi/Anti cardinality never exceeds left input cardinality.
> 		card = left.Product(right.AtMost(1))
> ```

Why use Product at all? Isn't it just `left`?

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 530 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAysMuJDbZTzq10Ja0t:-LAysMuJDbZTzq10Ja0u:b-wlq4fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/logical_props_builder.go#L530)):*
> ```Go
> 	// Apply filter to cardinality.
> 	if ev.Child(2).Operator() == opt.TrueOp {
> 		return card
> ```

This should be zero for anti joins

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 549 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyszi85QKqtrd48EP3:-LAyszi85QKqtrd48EP4:bc296uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/logical_props_builder.go#L549)):*
> ```Go
> 	case opt.ExceptOp, opt.ExceptAllOp:
> 		// Use left Max cardinality.
> 		card = Cardinality{Min: 0, Max: left.Max}
> ```

Min could be left.Min - right.Max (when positive)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-:-LAyv1YwElF7I1I8YQll:b-o82hyh)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 4 of 44 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/xform/explorer.go, line 365 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyu1MvBw7MJdN3WSWa:-LAzg0Nm-iVSMgr6MTya:b-qgg2vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/xform/explorer.go#L365)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yes, but limiting a limit should have already been taking care of during normalization. This is a check to make sure we don't try to push if normalization hasn't occurred (e.g. optsteps).
</blockquote></details>

Ah, I see. Might be worth mentioning in a comment.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 530 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAysMuJDbZTzq10Ja0t:-LAzeT3yE6_eWRgOX9de:b-x3rzq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/memo/logical_props_builder.go#L530)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think it's correct as-is. `True` should be a no-op in all cases. For example, the query  `SELECT * FROM a ANTI JOIN (SELECT * FROM b WHERE False) ON True` would return all rows in `a`.

Anyway, I've made some changes to the anti/semi join logic to make it simpler (if a bit less precise).
</blockquote></details>

It's correct only when the right side has 0 rows. If the right side has at least 1 row, the result of the anti-join is always empty (because all rows "match"). The new code looks good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-:-LAzgU8C3yZokMylwI0F:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 4 of 44 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/xform/explorer.go, line 365 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25065#-LAyu1MvBw7MJdN3WSWa:-LAzmczkB0c9MusOd-Ib:b-88z3z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8adda9980be28ac5f1e8031f88449e2300c73c9a/pkg/sql/opt/xform/explorer.go#L365)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, I see. Might be worth mentioning in a comment.
</blockquote></details>

OK, I can make add a comment in a different PR, since I'm green on this one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25065)*

**Pull request merged**
