### PR TITLE
release-24.2: clusterversion: mint 24.2

### PR DESCRIPTION
**Pull request by celiala**
Set the final 24.2 cluster version.

Epic: None
Release note: None
Release justification: necessary versioning step for every release.

### CODE REVIEW

**Comment by celiala** [comment]
Error is

```
    migration_test.go:417: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/server/migration_test.go:417
        	Error:      	Not equal: 
        	            	expected: roachpb.Version{Major:24, Minor:1, Patch:0, Internal:10}
        	            	actual  : roachpb.Version{Major:24, Minor:2, Patch:0, Internal:0}
        	Test:       	TestUpgradeHappensAfterMigrations
        	Messages:   	after upgrade, expected system database version (24.2) to be equal to systemschema.SystemDatabaseSchemaBootstrapVersion (24.1-upgrading-to-24.2-step-010)

```

Seeing this note https://github.com/cockroachdb/cockroach/blob/release-24.2/pkg/server/migration_test.go#L383-L391
```
		// NB: When MinSupported is changed to 24_2, this check can change to
		// an equality check. This is because 24.2 is the first release where
		// https://github.com/cockroachdb/cockroach/issues/121914 has been
		// resolved.
		require.False(
			t, clusterversion.MinSupported.Version().Less(*systemDBVersion),
			"before upgrade, expected system database version (%v) to be less than or equal to clusterversion.MinSupported (%v)",
			*systemDBVersion, clusterversion.MinSupported.Version(),
		)

```

**Comment by celiala** [comment]
```
=== RUN   TestInitialValuesToString/testdata
    bootstrap_test.go:81: Unexpected hash value 6789d4b255fcb7948efde7caa155afdc272dfb26b30da29422f51b872dab9315 for system.
        If you're seeing this error message, this means that the bootstrapped system
        schema has changed. Assuming that this is expected:
        - If this occurred during development on the main branch, rewrite the expected
          test output and the hash value and move on.
        - If this occurred during development of a patch for a release branch, make
          very sure that the underlying change really is expected and is backward-
          compatible and is absolutely necessary. If that's the case, then there are
          hardcoded literals in the main development branch as well as any subsequent
          release branches that need to be updated also.
    --- FAIL: TestInitialValuesToString/testdata (0.00s)
```

**Comment by celiala** [comment]
running:
- dev test pkg/sql/catalog/systemschema_test --rewrite -f TestValidateSystemSchemaAfterBootStrap
- dev test pkg/sql/logictest/tests/local --rewrite -f TestLogic_crdb_internal_catalog
to fix these failing tests

**Review by kvoli — APPROVED** [review]

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127817#-:-O3F9AkF3gAq4Lxnc_Gv:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rail)

**Pull request merged**
