### PR TITLE
release: use bazel to build release binaries

### LINKED ISSUE #67147: ci: make bazel publish bleeding edge
Epic CRDB-8306

Jira issue: CRDB-8390

### LINKED ISSUE #67161: ci: duplicate `Internal / Release / Process / Make and Publish Build` CI job for Bazel
Epic CRDB-8351

Jira issue: CRDB-8404

### LINKED ISSUE #67279: bazel: correctly stamp `build.channel`, `log.crashReportEnv`
#67278 took care of #66853, but that still leaves a couple variables:

```
# TODO(ricky): Also provide a way to stamp the following variables:
# - github.com/cockroachdb/cockroach/pkg/build.channel
# - github.com/cockroachdb/cockroach/pkg/util/log.crashReportEnv
```

Epic CRDB-8351

Jira issue: CRDB-8467

### LINKED ISSUE #67322: build: update pkg/cmd/publish-provisional-artifacts to support building using bazel
Epic CRDB-8306

Jira issue: CRDB-8484

### PR DESCRIPTION
**Pull request by rickystewart**
This is a pretty large swath of related changes that update the release
pipeline to use Bazel for builds.

1. Update `.bazelrc` to add a new `*base` config for each cross-config.
   The existing cross configs will continue to work as before. Each
   `*base` config has the same contents as the corresponding cross
   config EXCEPT the `--workspace_status_command` argument is missing.
2. Stamping. `build/bazelutil/stamp.sh` now takes up to 3 more
   arguments in addition to the target triple: `build-channel`,
   `build-tag`, and `build-type`. These are documented in the script and
   have appropriate defaults for development builds if not specified.
3. Refactor `pkg/release`; the new API is more high-level rather than
   allowing injecting arbitrary `gotags`, etc. In the future it won't
   be impossible to add this functionality back in if we want it.
4. Prepare to fork the `Make and Publish Build` build configuration in
   TC by moving its script into `build/teamcity` and update the script
   to use Bazel.
5. Update `bazci` to make sure it reads the Windows `geos` libraries
   from the appropriate location in `bazel-bin`.
6. Update `publish-artifacts` and `publish-provisional-artifacts` to use
   the new `pkg/release` API.

Closes https://github.com/cockroachdb/cockroach/issues/67147.
Closes https://github.com/cockroachdb/cockroach/issues/67161.
Closes https://github.com/cockroachdb/cockroach/issues/67279.
Closes https://github.com/cockroachdb/cockroach/issues/67322.

Release note (general change): Use Bazel to build release binaries
Release justification: update release process

### CODE REVIEW

**Review by rail — APPROVED** [review]
It looks sane to me. Would be great to have @jlinder's opinion too.
Sorry for the delay.

> Reviewed 5 of 5 files at r1, 7 of 19 files at r2, 7 of 20 files at r4, 14 of 19 files at r5, 20 of 20 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76897#-:-MxFJGvH2V4FgukKTCgE:b8xhu3o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/release/release.go, line 637 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76897#-MxFIL3GDgsw0ixgYqaS:-MxFIL3GDgsw0ixgYqaT:b-fj2gpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6913f891699677cf3c5cc7b755110160dc5ab7/pkg/release/release.go#L637)):*
> ```Go
> }
> 
> func closeFileOrPanic(f *os.File) {
> ```

Or `func closeFileOrPanic(f io.Closer)`.  Pedantic mode off. :)



_Code quote:_
```Go
func closeFileOrPanic(f *os.File) {
```

**Review by jlinder — APPROVED** [review]
This is great! 🚢

**Comment by rickystewart** [comment]
I pushed an additional update to move the `Publish Cockroach Release` script from `build/release/teamcity-publish-release.sh` to `build/teamcity/internal/release/process/publish-cockroach-release.sh`.

**Comment by rickystewart** [comment]
TFTR! yolo 

bors r=rail,jlinder

**Pull request merged**
