### PR TITLE
sql: run check constraint mutations and validation by schema changer

### PR DESCRIPTION
**Pull request by eriktrinh**
This change moves check constraint adds and drops through the schema
changer when the transaction commits, moving the constraint through the
same intermediate states as when index/columns are added or dropped. The
only small differences are:
 - Constraint adds can start in write-only and immediately start being
   enforced if all used columns are in write-only or public.
 - Constraint drops can move immediately from public to absent if they
   have not yet been validated.

Therefore, the check constraint is no longer immediately public when it
is added, but allows data validation of the constraint to be performed
when the constraint is added (and is now the default behaviour).
Constraints can now also be added on columns in the process of being
added.

This change also ensures that there are no data anomalies in either
versions of the schema when dropping a validated check constraint, as
previously the transition moved the constraint from public -> absent.
Writes on the new version were not being checked even though nodes on an
older version expect all rows to conform to the constraint.

Release note (sql change): Check constraint adds by default will
validate table data with the added constraint asynchronously after the
transaction commits.

### CODE REVIEW

**Review by dt — APPROVED** [review]
Great Stuff! A couple really minor nits. The schema_changer.go stuff is in code with which I have a little less familiarity but overall approach looks great (though as commented below, I still get confused about how txn semantics work with schema changes that "fail").

> Reviewed 19 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-:-LSrV1qu0ma-8Rxx-bRj:b-h9mm74)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrTFLv27RRwNT7ROQh:-LSrTFLv27RRwNT7ROQi:b-fxuv55) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/backfill.go#L47)):*
> ```Go
> 	// checkConstraintBackfillChunkSize is the maximum number of rows
> 	// processed per chunk during check constraint validation.
> 	checkConstraintBackfillChunkSize = 800
> ```

How did we pick this number?
___
*[pkg/sql/backfill/backfill.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrUXoM48eyG_X0BUoR:-LSrUXoM48eyG_X0BUoS:baekbqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/backfill/backfill.go#L111)):*
> ```Go
> 	); err != nil {
> 		return err
> 	} else {
> ```

this really should be allowed -- minimizing the scope in which `typed` has to be bound is nice and clean -- but sadly the linter doesn't like it since first block ends in return. dumb linter.
___
*[pkg/sql/backfill/backfill.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrP-ao441EDI_Hbkpg:-LSrP-ao441EDI_Hbkph:b6eqcwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/backfill/backfill.go#L183)):*
> ```Go
> 			}
> 			if val == tree.DBoolFalse {
> 				return roachpb.Key{}, errors.Errorf("validation of CHECK %q failed on row: %s",
> ```

I think there's a proper pgerror code we should be returning -- though I don't know if returning it _here_ will make it back to the client.
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrORzRCx8w5DrsLjAL:-LSrORzRCx8w5DrsLjAM:b8ww1fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L611)):*
> ```
> 
> statement ok
> ALTER TABLE forlater ADD CONSTRAINT e_0 CHECK (e > 0)
> ```

Is it sort of weird that you get a success reply here, but if you then ran `SELECT ... WHERE e < 0` in the txn, you could observe a violation?
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 613 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrS0vi7STenPTPfbIj:-LSrS0vi7STenPTPfbIk:b3lun4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L613)):*
> ```
> ALTER TABLE forlater ADD CONSTRAINT e_0 CHECK (e > 0)
> 
> statement error pq: validation of CHECK "e > 0" failed on row: k='c', v='d', d=NULL, e=0
> ```

So you get an error from commit but the txn _does_ commit, right? just the CHECK doesn't get added? I realize some of our other schema changes have similar behavior, but it really seems like a strange violation of the all-or-nothing aspect of committing a txn. Maybe I just need to get over that expectation though.

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrTFLv27RRwNT7ROQh:-LSv_EPK2JC8JkKeKumZ:b-6hhe4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/backfill.go#L47)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

How did we pick this number?
</blockquote></details>

I chose a number larger than any of the other backfill chunk sizes because check backfills don't actually write any data. Testing and benchmarking could be done to tune this.
___
*[pkg/sql/backfill/backfill.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrP-ao441EDI_Hbkpg:-LSvUTZQCyN4-_gbb1cu:bje3eoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/backfill/backfill.go#L183)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think there's a proper pgerror code we should be returning -- though I don't know if returning it _here_ will make it back to the client.
</blockquote></details>

You're right, there exists 23514 aka `check_validation` data exception. However error codes from the schema changer get replaced with a `statement_completion_unknown` code.
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrORzRCx8w5DrsLjAL:-LSvZPAP0PDsFMjb8POs:b-t76h48) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L611)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Is it sort of weird that you get a success reply here, but if you then ran `SELECT ... WHERE e < 0` in the txn, you could observe a violation?
</blockquote></details>

Yea this is kinda weird, a similar result is observed with unique constraints as well.
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 613 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSrS0vi7STenPTPfbIj:-LSvZtkXB8uzvYIvn99Y:b-29lx8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23f712c6080ad21d2830e67fb675837d1d2c664/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L613)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

So you get an error from commit but the txn _does_ commit, right? just the CHECK doesn't get added? I realize some of our other schema changes have similar behavior, but it really seems like a strange violation of the all-or-nothing aspect of committing a txn. Maybe I just need to get over that expectation though.
</blockquote></details>

Right, the txn which added the mutation does commit. The violation is strange but it's communicated to the user through the error code and name.

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.proto, line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LSvaXkF9ua_05QNjNpU:-LSvaXkF9ua_05QNjNpV:b-m6ipvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/91eb4a8b052d5cd98d51253c4a4d12181b59a2f3/pkg/sql/sqlbase/structured.proto#L480)):*
> ```protobuf
> }
> 
> message CheckConstraint {
> ```

Not sure if pulling out this message type is safe or not.

**Comment by eriktrinh** [comment]
Gave this PR another pass: updating the commit message, adding tests, adding a `validating` state, and also dropping check constraints through the schema changer if the constraint has been validated. PTAL.

**Review by thoszhang — COMMENTED** [review]
Made some very minor changes:

* rebased and resolved conflicts
* added 2 tests to the end of `schema_change_in_txn`
* put issues in commit message

@dt @vivekmenezes this is ready for one last look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-:-LVnnbbeAIiU73f4mQUE:b-58fyc3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
Nice work on pushing the new update.

I noticed that `func (p *planner) validateCheckExpr` uses a sql query to check the constraint. Is there a reason why we don't do this here as opposed to spinning off a backfiller?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-:-LVoPqOsAtBvIpx-vzry:b-wnm5nf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.go, line 2261 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LVoPJZkB6np7mPuhIyw:-LVoPJZkB6np7mPuhIyx:bi0rhan) ([raw file](https://github.com/cockroachdb/cockroach/blob/296e932d95bf856479587f3d13fc25044303604b/pkg/sql/sqlbase/structured.go#L2261)):*
> ```Go
> // AddCheckAddMutation adds an add check constraint mutation to desc.Mutations.
> // If moveInitialState is specified, the initial state of the mutation is
> // DELETE_AND_WRITE_ONLY.
> ```

Is there a strong reason why this is needed? It's better to not have to break from convention
___
*[pkg/sql/sqlbase/structured.proto, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LVoJfTh1WQebEpujdDU:-LVoJfTh1WQebEpujdDV:b-hklfox) ([raw file](https://github.com/cockroachdb/cockroach/blob/296e932d95bf856479587f3d13fc25044303604b/pkg/sql/sqlbase/structured.proto#L196)):*
> ```protobuf
>   Validated = 0;
>   Unvalidated = 1;
>   Validating = 2;
> ```

I wonder if this is needed? Is a constraint in the mutations list always validating?

**Review by thoszhang — COMMENTED** [review]
Per offline discussion, we'll keep using the backfiller because of the progress tracker and ability to resume.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-:-LVp4VzI5Ywpxl8tmPd2:bsxxftv)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.go, line 2261 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LVoPJZkB6np7mPuhIyw:-LVomeUk8Z7rR5KvDQN4:bkbs0sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/296e932d95bf856479587f3d13fc25044303604b/pkg/sql/sqlbase/structured.go#L2261)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Is there a strong reason why this is needed? It's better to not have to break from convention
</blockquote></details>

No, I don't think it's necessary. I'll change it to match the other cases for consistency.

What do you think of the other optimization, to immediately move to the absent state on a DROP CONSTRAINT if the constraint isn't validated?
___
*[pkg/sql/sqlbase/structured.proto, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LVoJfTh1WQebEpujdDU:-LVp3ahjDemzxoZbgCnF:bnhwuoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/296e932d95bf856479587f3d13fc25044303604b/pkg/sql/sqlbase/structured.proto#L196)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I wonder if this is needed? Is a constraint in the mutations list always validating?
</blockquote></details>

It's not needed for this change. I talked with @dt about it - the point of adding this state is that when we add support for `NOT VALID`, we would add unvalidated constraints via the schema changer, and they would be present in the mutations list in the unvalidated state (so whether a constraint is unvalidated vs. validating determines whether the validation backfill step runs).

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.go, line 2261 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LVoPJZkB6np7mPuhIyw:-LVtISrC6OqWPb5osFPe:bb78iaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/296e932d95bf856479587f3d13fc25044303604b/pkg/sql/sqlbase/structured.go#L2261)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

No, I don't think it's necessary. I'll change it to match the other cases for consistency.

What do you think of the other optimization, to immediately move to the absent state on a DROP CONSTRAINT if the constraint isn't validated?
</blockquote></details>

I suppose the drop case is okay since it doesn't go through the state machine

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.go, line 2261 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LVoPJZkB6np7mPuhIyw:-LVtV7VX03_CBXeQY3Ie:b-rlruy) ([raw file](https://github.com/cockroachdb/cockroach/blob/296e932d95bf856479587f3d13fc25044303604b/pkg/sql/sqlbase/structured.go#L2261)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I suppose the drop case is okay since it doesn't go through the state machine
</blockquote></details>

Updated `AddCheckMutation` to match the implementation for indexes and columns.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.go, line 2261 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32504#-LVoPJZkB6np7mPuhIyw:-LVtqss4D8EEfDbjZDZP:bt9p6mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/296e932d95bf856479587f3d13fc25044303604b/pkg/sql/sqlbase/structured.go#L2261)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Updated `AddCheckMutation` to match the implementation for indexes and columns.
</blockquote></details>

Also removed a test in `schema_changer_test.go` that was testing this special case.

**Pull request merged**
