### PR TITLE
cli: add cockroach debug job-trace

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds a new cli command - `cockroach debug job-trace`
that can be used to grab information from inflight trace spans
associated with the execution of a particular job.
The command takes a `jobID` and file destination where the
information will be dumped. It also requires a `--url` of the
node from which to pull the inflight spans.

In the future we will have a means of pulling inflight spans from
the cluster, but at the moment this command must be run against every
node to get a complete picture of job execution.

Informs: #64992

Release note (cli change): Adds a `cockroach debug job-trace` command
that takes 2 arguments: <jobID> and file destination, along with a
`--url` pointing to the node on which to execute this command.
The command pulls information about inflight trace spans associated
with the job and dumps it to the file destination.

### CODE REVIEW

**Comment by adityamaru** [comment]
The first two commits are from #65322.

**Comment by jordanlewis** [comment]
Excellent.

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/cli/debug_job_trace.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLU0OBHWLtkMFBOwg:-M_uLU0OBHWLtkMFBOwh:bedfqpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L34)):*
> ```Go
> 	Args:  cobra.MinimumNArgs(2),
> 	RunE: MaybeDecorateGRPCError(
> 		func(command *cobra.Command, args []string) error {
> ```

nit: please move this function to a named function below.
___
*[pkg/cli/debug_job_trace.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLeo04nKEEHrk1bEg:-M_uLeo04nKEEHrk1bEh:befnwjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L65)):*
> ```Go
> 	}
> 
> 	jobID, err := strconv.Atoi(jobIDStr)
> ```

This check is parameter validation, and should be done upfront in the command before starting to open connections etc.
___
*[pkg/cli/debug_job_trace.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLmZb8WwbfxTioRDM:-M_uLmZb8WwbfxTioRDN:bd9xjk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L71)):*
> ```Go
> 
> 	var jobQuery = fmt.Sprintf(`SELECT trace_id FROM crdb_internal.jobs WHERE job_id='%d'`, jobID)
> 	rows, err := sqlConn.Query(jobQuery, nil)
> ```

please pass the query inside `sqlConn.Query` and use a placeholder to pass jobID.
___
*[pkg/cli/debug_job_trace.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uM4NV4DRBfR0jrPO8:-M_uM4NV4DRBfR0jrPO9:b-jacnvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L72)):*
> ```Go
> 	var jobQuery = fmt.Sprintf(`SELECT trace_id FROM crdb_internal.jobs WHERE job_id='%d'`, jobID)
> 	rows, err := sqlConn.Query(jobQuery, nil)
> 	if err != nil {
> ```

I think you need to call `rows.Close()`.
Please extract the retrieval of the traceID into a separate function, and ensure `rows.Close()` is called within that function.
___
*[pkg/cli/debug_job_trace.go, line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLt6p3btfjlnhUeVB:-M_uLt6p3btfjlnhUeVC:b6c0rwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L103)):*
> ```Go
> 
> 	var resRows [][]string
> 	spanRows, err := sqlConn.Query(query, nil)
> ```

ditto calling `spanRows.Close()`.
___
*[pkg/cli/debug_job_trace.go, line 108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uMVSfBoXYiLnFvXR_:-M_uMVSfBoXYiLnFvXRa:baruiox) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L108)):*
> ```Go
> 	}
> 
> 	populateRow := func(vals []driver.Value) ([]string, error) {
> ```

I don't understand why you need this code -- what was wrong with calling `runQueryAndFormatResults()`?
___
*[pkg/sql/crdb_internal.go, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLEli3kQFXMaVXUcY:-M_uLEli3kQFXMaVXUcZ:b223tsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/92f17eb22ca9de0cb680430c9ae8ec917a0e3ba1/pkg/sql/crdb_internal.go#L623)):*
> ```Go
> 	error              		STRING,
> 	coordinator_id     		INT,
>   trace_id              INT
> ```

nit: spacing is off

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @pbardea)

___
*[pkg/cli/debug_job_trace.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLU0OBHWLtkMFBOwg:-Ma2onypCFZ71XLwcR7L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L34)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: please move this function to a named function below.
</blockquote></details>

Done.
___
*[pkg/cli/debug_job_trace.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLeo04nKEEHrk1bEg:-Ma2p6My4phaATPFjAau:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L65)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This check is parameter validation, and should be done upfront in the command before starting to open connections etc.
</blockquote></details>

Done.
___
*[pkg/cli/debug_job_trace.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLmZb8WwbfxTioRDM:-Ma2puCNDpClaJJoVHEx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L71)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please pass the query inside `sqlConn.Query` and use a placeholder to pass jobID.
</blockquote></details>

Done.
___
*[pkg/cli/debug_job_trace.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uM4NV4DRBfR0jrPO8:-Ma2puSQ62Al8R9SjnIK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L72)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you need to call `rows.Close()`.
Please extract the retrieval of the traceID into a separate function, and ensure `rows.Close()` is called within that function.
</blockquote></details>

Done.
___
*[pkg/cli/debug_job_trace.go, line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLt6p3btfjlnhUeVB:-Ma32rSUDcdNsu_mx-Es:b3lgk6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L103)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto calling `spanRows.Close()`.
</blockquote></details>

Deleted this code since it is no longer required.
___
*[pkg/cli/debug_job_trace.go, line 108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uMVSfBoXYiLnFvXR_:-Ma32dghE64SK5zWHk3D:b3gqf1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L108)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand why you need this code -- what was wrong with calling `runQueryAndFormatResults()`?
</blockquote></details>

doh, that's exactly what I want. Thanks for always pointing me to the right place :slightly_smiling_face:

**Comment by adityamaru** [comment]
Rebased on #65322 that was merged, and also cherry-picked #65454. The last commit is the pertinent one!

**Review by knz — COMMENTED** [review]
The code looks good overall, but I'm missing the test code. Can you point me to it?

> Reviewed 5 of 11 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-:-Ma3VKZ8CbjZlvIQKbhe:b-ul1hbp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/cli/debug_job_trace.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uM4NV4DRBfR0jrPO8:-Ma3UyeV665qcwTXAChV:bg60iqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0e53cab27d3c6785e137bcbde7879aff9245ff/pkg/cli/debug_job_trace.go#L72)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nice :100: 
___
*[pkg/cli/debug_job_trace.go, line 35 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-Ma3UWZr7Vh6X5zVoRq8:-Ma3UWZr7Vh6X5zVoRq9:b-dpqa95) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1b11e6fe42bb83d74e82226e5ab4bfa50ccc2bc/pkg/cli/debug_job_trace.go#L35)):*
> ```Go
> 
> func runDebugJobTrace(_ *cobra.Command, args []string) error {
> 	jobID, err := strconv.Atoi(args[0])
> ```

Maybe `strconv.ParseInt` here and pass it as int64 below. This avoids a cast.
___
*[pkg/sql/crdb_internal.go, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLEli3kQFXMaVXUcY:-Ma3VEbe8EKvO_IPXME3:b-6biwku) ([raw file](https://github.com/cockroachdb/cockroach/blob/92f17eb22ca9de0cb680430c9ae8ec917a0e3ba1/pkg/sql/crdb_internal.go#L623)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: spacing is off
</blockquote></details>

still off

**Review by pbardea — COMMENTED** [review]
+1 to tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-:-MaAl_b88nEoOLfan0MC:bj672q9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/cli/debug_job_trace.go, line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-MaAlU3x-2A_jyw8A73T:-MaAkwqWESrAMKAyka9s:b-yl8130) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1b11e6fe42bb83d74e82226e5ab4bfa50ccc2bc/pkg/cli/debug_job_trace.go#L104)):*
> ```Go
> 	}
> 
> 	var inflightSpanQuery = `WITH spans AS(
> ```

nit: formatting of the query looks a bit of

**Comment by knz** [comment]
you need to use `--format` to choose a specific output format and make your output the same in every case

(The default value of `--format` is different depending on how you invoke the command)

**Comment by knz** [comment]
> Do you all have any other ideas?

We have other tests (e.g. for `node status`) that expect specific outputs based on regular rexpressions.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @pbardea)

___
*[pkg/cli/debug_job_trace.go, line 35 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-Ma3UWZr7Vh6X5zVoRq8:-MaEJKwB0UHA70JOFkIW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1b11e6fe42bb83d74e82226e5ab4bfa50ccc2bc/pkg/cli/debug_job_trace.go#L35)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe `strconv.ParseInt` here and pass it as int64 below. This avoids a cast.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-M_uLEli3kQFXMaVXUcY:-Mabvx9z4r21EvlTlBLb:b-3dueg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/92f17eb22ca9de0cb680430c9ae8ec917a0e3ba1/pkg/sql/crdb_internal.go#L623)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

still off
</blockquote></details>

fixed the trace_id prefix indent. the col type indentation appears fine in my editor, but not in reviewable.

**Review by knz — APPROVED** [review]
Code structure/style LGTM, but I'll let your team chime in on correctness.

> Reviewed 2 of 3 files at r6, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-:-Mac5T4P3gSTBff16kOT:bdg82b8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @knz)

___
*[pkg/sql/crdb_internal.go, line 621 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-Mac5M474SKVg7FW1dKO:-Mac5M474SKVg7FW1dKP:bge90rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26af701f711eef98809950080d0a7e8c25883a6/pkg/sql/crdb_internal.go#L621)):*
> ```Go
> 	fraction_completed 		FLOAT,
> 	high_water_timestamp	DECIMAL,
> 	error              		STRING,
> ```

While you're at it, perhaps you could put that STRING and the INT just below it on the same column as the rest.

**Comment by adityamaru** [comment]
> While you're at it, perhaps you could put that STRING and the INT just below it on the same column as the rest.

These only appear shifted in reviewable for some reason. Github and in my IDE the spacing is identical for all the columns.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @pbardea)

___
*[pkg/sql/crdb_internal.go, line 621 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-Mac5M474SKVg7FW1dKO:-MadiBcoDDgbguS-nG9O:bp5c9vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26af701f711eef98809950080d0a7e8c25883a6/pkg/sql/crdb_internal.go#L621)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

While you're at it, perhaps you could put that STRING and the INT just below it on the same column as the rest.
</blockquote></details>

I'm realizing what the issue is: this vtable definition uses tabs, not spaces, in its schema.
*all the other vtables uses spaces* - this one is the exception.

So the improvement would be to convert this to use spaces like everything else: two spaces at the beginning, then spaces to align the columns.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @pbardea)

___
*[pkg/sql/crdb_internal.go, line 621 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65324#-Mac5M474SKVg7FW1dKO:-MadpJlo4VoaKVSrZ6CH:bwfn4pc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26af701f711eef98809950080d0a7e8c25883a6/pkg/sql/crdb_internal.go#L621)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm realizing what the issue is: this vtable definition uses tabs, not spaces, in its schema.
*all the other vtables uses spaces* - this one is the exception.

So the improvement would be to convert this to use spaces like everything else: two spaces at the beginning, then spaces to align the columns.
</blockquote></details>

nice! all done :slightly_smiling_face:

**Comment by knz** [comment]
my previous review stands

> Code structure/style LGTM, but I'll let your team chime in on correctness.

**Review by pbardea — APPROVED** [review]
LGTM

**Comment by adityamaru** [comment]
Had to fix up a few things to get the test passing:
- debug job-trace no longer creates a "job-trace" directory, but just creates whatever path is passed in as the CLI argument. 
- test cleans up directory after itself.
- we would occasionally see a "contention event" in the trace for a job. We are only really interested in the header and the trace we injected, so the test only checks for those now.

**Comment by adityamaru** [comment]
Seeing an `Execution timeout` in CI. Not sure what is causing this yet.

**Comment by adityamaru** [comment]
Going ahead and merging this. The bazel failure is unrelated and seems to have been occurring on most builds since ~3-4 days ago - `pkg/sql/sql_test_/sql_test`

TFTR!
bors r=pbardea,knz

**Pull request merged**
