### PR TITLE
cli/sql: support `\s`

### LINKED ISSUE #97575: cli/sql: add command to display history
Requested by @smcvey 

It would be useful to have a client-side commadn that prints out the history entries, akin to `\s` in `psql`.

Jira issue: CRDB-24766

### PR DESCRIPTION
**Pull request by lyang24**
Fixes: #97575

### CODE REVIEW

**Comment by Xiang-Gu** [comment]
Thanks for contributing to CRDB! Please add tests before someone took a closer look at it.

**Comment by lyang24** [comment]
> Thanks for contributing to CRDB! Please add tests before someone took a closer look at it.

Hi, thanks for the feedback. I added `pkg/cli/interactive_tests/test_print_command_history.tcl` to acceptance test. I spend sometime to look at the testing infrastructure since this command is for interactive shell only  and most of the test execute with `sql -e {statements}` which uses another editor with no history. I am having trouble to find the right testing infrastructure? @knz could you please let me know if there are more places i could test this?

**Comment by knz** [comment]
I will look when I am back at the computer later this week.

**Review by knz — APPROVED** [review]
Hello, I have reviewed this and it looks good. The test was to be added to `test_history.tcl`; I have updated your PR accordingly.

Thanks for your change.

**Pull request merged**
