### PR TITLE
ttl: improve row-level TTL performance using DistSQL

### LINKED ISSUE #76914: ttl: improve row-level TTL performance using DistSQL
the TTL job should be distributed using DistSQL / a DistSQL flow job (mentioned by @miretskiy).
   * It does not shard out deletes to be local to each region yet either (i'd say ideally the leaseholders of the range should perform the delete)
  

Further improvements related to a secondary index are mentioned here:
* https://github.com/cockroachdb/cockroach/issues/82140

Jira issue: CRDB-13392
Epic CRDB-14592

### PR DESCRIPTION
**Pull request by ecwall**
fixes https://github.com/cockroachdb/cockroach/issues/76914

Release note (performance improvement): The row-level TTL job has been modified
to distribute work using DistSQL. This usually results in the leaseholder nodes
managing deleting of the spans they own.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice work! I have some nits as well as a suggestion - it'd be good to check that the physical planning of DistSQL processors is as expected. You could do so in a "execbuilder" test - e.g. take a look at `pkg/sql/opt/exec/execbuilder/distsql_join` for inspiration (or any other `distsql_*` file in that folder).

> Reviewed 5 of 11 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-:-N85PrtG44CguhePfSJk:b-cwcbvg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @otan, and @rafiss)

___
*[`pkg/sql/distsql_running.go` line 752 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85MN3S8W3aR1HQ9yJw:-N85MN3S8W3aR1HQ9yJx:b-hjz3uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/distsql_running.go#L752)):*
> ```Go
> }
> 
> // NewErrorOnlyMetadataCallbackWriter creates a new MetadataCallbackWriter that supports receiving an error.
> ```

Given the name of the function, I'd expect that this would take the callback that should be called whenever a metadata is received.

nit: wrap at 80 characters.
___
*[`pkg/sql/distsql_running.go` line 755 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85M_TGDfE37qecEvim:-N85M_TGDfE37qecEvin:b-hpkxag) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/distsql_running.go#L755)):*
> ```Go
> func NewErrorOnlyMetadataCallbackWriter() *MetadataCallbackWriter {
> 	return NewMetadataCallbackWriter(
> 		NewRowResultWriter(nil),
> ```

nit: using `errOnlyResultWriter` here seems cleaner.
___
*[`pkg/sql/exec_util.go` line 1524 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85L_bU8k4VIaDqQtby:-N85L_bU8k4VIaDqQtbz:b-5hykfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/exec_util.go#L1524)):*
> ```Go
> 	// ReturnStatsError causes stats errors to be returned instead of logged as warnings.
> 	ReturnStatsError bool
> 	// ChangeTableDescriptorVersionDuringDelete flag to change the table descriptor
> ```

nit: a verb seems to be missing in the comment.
___
*[`pkg/sql/execinfrapb/flow_diagram.go` line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85MoaY3xDeignnFcNQ:-N85MoaY3xDeignnFcNR:b-5aw8lk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/execinfrapb/flow_diagram.go#L585)):*
> ```Go
> // summary implements the diagramCellType interface.
> func (s *TTLSpec) summary() (string, []string) {
> 	return "TTL", []string{}
> ```

nit: this determines what is shown on DistSQL diagrams - do we not want to include some details? Up to you.
___
*[`pkg/sql/execinfrapb/processors_ttl.proto` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85LgkP1W-rcLUPawms:-N85LgkP1W-rcLUPawmt:b6qfo8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/execinfrapb/processors_ttl.proto#L1)):*
> ```protobuf
> // Copyright 2019 The Cockroach Authors.
> ```

nit: `s/2019/2022/`.
___
*[`pkg/sql/execinfrapb/processors_ttl.proto` line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85LnxBCJngl82nbQRH:-N85LnxBCJngl82nbQRI:ba19aps) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/execinfrapb/processors_ttl.proto#L27)):*
> ```protobuf
> import "jobs/jobspb/jobs.proto";
> 
> message TTLSpec {
> ```

nit: it'd be good to add some comments to the fields in this proto.
___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85O5EtBsbiD6h9icE0:-N85O5EtBsbiD6h9icE1:b9n9k6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob.go#L251)):*
> ```Go
> 
> 		physicalPlan := planCtx.NewPhysicalPlan()
> 		// All of the progress information is sent through the metadata stream, so we
> ```

Do we want to expose that progress information somehow?

Update: I see that each processor updates the job progress, it'd probably be worth to mention that in the comment here.
___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85OFwa0_mLEGYOScc-:-N85OFwa0_mLEGYOScc0:b5wpvbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob_processor.go#L50)):*
> ```Go
> 
> func (t *ttlProcessor) Start(ctx context.Context) {
> 	ctx = t.StartInternal(ctx, "t")
> ```

nit: probably `s/"t"/"ttl"/` or something like that.
___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 271 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85P63h3jJeI-CW_3NY:-N85P63h3jJeI-CW_3NZ:b-asa26u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob_processor.go#L271)):*
> ```Go
> 	cutoff := details.Cutoff
> 	selectBuilder := makeSelectQueryBuilder(
> 		details.TableID,
> ```

nit: use `tableID`.
___
*[`pkg/sql/ttl/ttljob/ttljob_query_builder.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85PJZ2-a61QaSqqt3H:-N85PJZ2-a61QaSqqt3I:bi4p7nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L74)):*
> ```Go
> 	cachedArgs := make([]interface{}, 0, 1+len(pkColumns)*2)
> 	cachedArgs = append(cachedArgs, cutoff)
> 	endPK := rangeToProcess.endPK
> ```

nit: it'd be good to be consistent - either define `startPK` as well or don't define `endPK`.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84728)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 752 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85MN3S8W3aR1HQ9yJw:-N8Nwv2R4XprGoKOJPCy:b-p6xfi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/distsql_running.go#L752)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Given the name of the function, I'd expect that this would take the callback that should be called whenever a metadata is received.

nit: wrap at 80 characters.


</blockquote></details>

I renamed it to `NewMetadataOnlyMetadataCallbackWriter` since it should never receive row results.

Wrapped line at 80 chars.



_Code quote:_
```Go
NewErrorOnlyMetadataCallbackWriter
```
___
*[`pkg/sql/execinfrapb/flow_diagram.go` line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85MoaY3xDeignnFcNQ:-N8OxwrpAhGaqwmXlBam:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/execinfrapb/flow_diagram.go#L585)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this determines what is shown on DistSQL diagrams - do we not want to include some details? Up to you.
</blockquote></details>

Added.
___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85O5EtBsbiD6h9icE0:-N8OuTNY7bDtBCI8ZKu1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob.go#L251)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do we want to expose that progress information somehow?

Update: I see that each processor updates the job progress, it'd probably be worth to mention that in the comment here.
</blockquote></details>

Done.



_Code quote:_
```Go
physicalPlan.AddNoInputStage(
```
___
*[`pkg/sql/ttl/ttljob/ttljob_query_builder.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85PJZ2-a61QaSqqt3H:-N8Oujsa9xw1MNFEYmqr:b-h3ynjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L74)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it'd be good to be consistent - either define `startPK` as well or don't define `endPK`.
</blockquote></details>

`endPK` is used multiple times so I defined a variable for it, but I can define one for `startPK` too for consistency even though it is only used once.



_Code quote:_
```Go
endPK := rangeToProcess.endPK
```

**Review by rafiss — CHANGES_REQUESTED** [review]
this look good! just small nits. i focused my review only on the ttljob parts, so anything changing the distsql framework should get signoff from yahor/sql-queries

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-:-N8V2w7v3sTXjN4gikFc:b-5vd2dm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @otan, and @yuzefovich)

___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 447 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N8V2-rFEJQf0YsP38Rh:-N8V2-rFEJQf0YsP38Ri:bufwr7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8d7c86306389930a5e69ecb94d7c1870368242/pkg/sql/ttl/ttljob/ttljob_processor.go#L447)):*
> ```Go
> 		processorID,
> 		output,
> 		nil, /* memMonitor */
> ```

should the job do memory monitoring? if not, it would be useful for a comment to explain why
___
*[`pkg/sql/ttl/ttljob/ttljob_test.go` line 558 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N8V2ibz87p0z07vECHp:-N8V2ibz87p0z07vECHq:b-mavnrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8d7c86306389930a5e69ecb94d7c1870368242/pkg/sql/ttl/ttljob/ttljob_test.go#L558)):*
> ```Go
> 					AOSTDuration:                  &zeroDuration,
> 					ReturnStatsError:              true,
> 					RequireMultipleSpanPartitions: numNodes > 0,
> ```

based on the `if numNodes == 0` condition above, won't this always be true?

**Review by yuzefovich — APPROVED** [review]
:lgtm: modulo Rafi's comments.

> Reviewed 5 of 10 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-:-N8VbH8PEYomwBpCVyGR:bnob22b)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall and @otan)

___
*[`pkg/sql/execinfrapb/flow_diagram.go` line 587 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N8VYajIBt69aOlKWyDx:-N8VYajJ6e619bPyb5LG:b-73tr53) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8d7c86306389930a5e69ecb94d7c1870368242/pkg/sql/execinfrapb/flow_diagram.go#L587)):*
> ```Go
> 	details := s.RowLevelTTLDetails
> 	spans := s.Spans
> 	spanStrings := make([]string, len(spans))
> ```

This is currently ignored and not included into the summary - is this intentional? Also if you do include it, then it might makes sense to print out only a single span - take a look at `TableReaderSpec.summary` for an example (if we print out hundreds of spans, then the diagram will be unreadable).
___
*[`pkg/sql/execinfrapb/processors_ttl.proto` line 29 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N8VZ-8V3qDeuf0o3qAf:-N8VZ-8W3oLr_A1xpF3Z:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8d7c86306389930a5e69ecb94d7c1870368242/pkg/sql/execinfrapb/processors_ttl.proto#L29)):*
> ```protobuf
> message TTLSpec {
> 
>   // JobID of the job that ran the ttlProcessor
> ```

nit: missing period.
___
*[`pkg/sql/ttl/ttljob/ttljob_query_builder.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85PJZ2-a61QaSqqt3H:-N8VZkL81DkiWz0rGypV:bpuggxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L74)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

`endPK` is used multiple times so I defined a variable for it, but I can define one for `startPK` too for consistency even though it is only used once.
</blockquote></details>

Oh, I didn't see the multiple uses - up to you then.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84728)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @yuzefovich)

___
*[`pkg/sql/execinfrapb/flow_diagram.go` line 587 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N8VYajIBt69aOlKWyDx:-N8W8C9d9QFqWTaHVZ1I:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8d7c86306389930a5e69ecb94d7c1870368242/pkg/sql/execinfrapb/flow_diagram.go#L587)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This is currently ignored and not included into the summary - is this intentional? Also if you do include it, then it might makes sense to print out only a single span - take a look at `TableReaderSpec.summary` for an example (if we print out hundreds of spans, then the diagram will be unreadable).
</blockquote></details>

Removed
___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 447 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N8V2-rFEJQf0YsP38Rh:-N8W9-UN937Xo-hWaEMT:b8nxcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8d7c86306389930a5e69ecb94d7c1870368242/pkg/sql/ttl/ttljob/ttljob_processor.go#L447)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should the job do memory monitoring? if not, it would be useful for a comment to explain why
</blockquote></details>

I'm not sure if it should or not. I copied it from `newBulkRowWriterProcessor` where it was `nil`.
___
*[`pkg/sql/ttl/ttljob/ttljob_test.go` line 558 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N8V2ibz87p0z07vECHp:-N8W9bRB-v6z_rpGdCl7:b-60432i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8d7c86306389930a5e69ecb94d7c1870368242/pkg/sql/ttl/ttljob/ttljob_test.go#L558)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

based on the `if numNodes == 0` condition above, won't this always be true?
</blockquote></details>

changed to tc.numNodes

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84728)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @yuzefovich)

___
*[`pkg/sql/ttl/ttljob/ttljob_query_builder.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-N85PJZ2-a61QaSqqt3H:-N8W9f_aDNi0rM0WFlpO:b-28fwmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d5f3bf39c9f02c015191cd19e916569e3d71460/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L74)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Oh, I didn't see the multiple uses - up to you then.
</blockquote></details>

I'll leave it in then.

**Review by rafiss — APPROVED** [review]
lgtm!

bors r+

> Reviewed 4 of 11 files at r2, 1 of 10 files at r3, 3 of 10 files at r4, 1 of 5 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84728#-:-N8ysRRR7uq-dnzYGEfu:bh8jbcz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan, @rafiss, and @yuzefovich)

**Pull request merged**
