### PR TITLE
kv: pool rangeCacheKey objects

### PR DESCRIPTION
**Pull request by nvb**
This commit introduces a `sync.Pool` for `rangeCacheKey` objects. This
is used to avoid heap allocations when querying and updating the `RangeCache`.

```
name                      old time/op    new time/op    delta
KV/Scan/Native/rows=1-10    14.8µs ± 2%    14.9µs ± 4%    ~     (p=0.356 n=9+10)
KV/Scan/SQL/rows=1-10       92.1µs ± 4%    94.3µs ± 5%    ~     (p=0.113 n=9+10)

name                      old alloc/op   new alloc/op   delta
KV/Scan/Native/rows=1-10    6.87kB ± 0%    6.85kB ± 0%  -0.35%  (p=0.000 n=10+10)
KV/Scan/SQL/rows=1-10       20.0kB ± 0%    20.0kB ± 0%  -0.25%  (p=0.012 n=10+10)

name                      old allocs/op  new allocs/op  delta
KV/Scan/Native/rows=1-10      52.0 ± 0%      51.0 ± 0%  -1.92%  (p=0.000 n=10+10)
KV/Scan/SQL/rows=1-10          244 ± 0%       242 ± 0%  -0.78%  (p=0.000 n=10+10)
```
----

This is part of a collection of assorted micro-optimizations:
- #74336
- #74337
- #74338
- #74339
- #74340
- #74341
- #74342
- #74343
- #74344
- #74345
- #74346
- #74347
- #74348

Combined, these changes have the following effect on end-to-end SQL query performance:
```
name                      old time/op    new time/op    delta
KV/Scan/SQL/rows=1-10       94.4µs ±10%    92.3µs ±11%   -2.20%  (p=0.000 n=93+93)
KV/Scan/SQL/rows=10-10       102µs ±10%      99µs ±10%   -2.16%  (p=0.000 n=94+94)
KV/Update/SQL/rows=10-10     378µs ±15%     370µs ±11%   -2.04%  (p=0.003 n=95+91)
KV/Insert/SQL/rows=1-10      133µs ±14%     132µs ±12%     ~     (p=0.738 n=95+93)
KV/Insert/SQL/rows=10-10     197µs ±14%     196µs ±13%     ~     (p=0.902 n=95+94)
KV/Update/SQL/rows=1-10      186µs ±14%     185µs ±14%     ~     (p=0.351 n=94+93)
KV/Delete/SQL/rows=1-10      132µs ±13%     132µs ±14%     ~     (p=0.473 n=94+94)
KV/Delete/SQL/rows=10-10     254µs ±16%     250µs ±16%     ~     (p=0.086 n=100+99)

name                      old alloc/op   new alloc/op   delta
KV/Scan/SQL/rows=1-10       20.1kB ± 0%    19.1kB ± 1%   -4.91%  (p=0.000 n=96+96)
KV/Scan/SQL/rows=10-10      21.7kB ± 0%    20.7kB ± 1%   -4.61%  (p=0.000 n=96+97)
KV/Delete/SQL/rows=10-10    64.0kB ± 3%    63.7kB ± 3%   -0.55%  (p=0.000 n=100+100)
KV/Update/SQL/rows=1-10     45.8kB ± 1%    45.5kB ± 1%   -0.55%  (p=0.000 n=97+98)
KV/Update/SQL/rows=10-10     105kB ± 1%     105kB ± 1%   -0.10%  (p=0.008 n=97+98)
KV/Delete/SQL/rows=1-10     40.8kB ± 0%    40.7kB ± 0%   -0.08%  (p=0.001 n=95+96)
KV/Insert/SQL/rows=1-10     37.4kB ± 1%    37.4kB ± 0%     ~     (p=0.698 n=97+96)
KV/Insert/SQL/rows=10-10    76.4kB ± 1%    76.4kB ± 0%     ~     (p=0.822 n=99+98)

name                      old allocs/op  new allocs/op  delta
KV/Scan/SQL/rows=1-10          245 ± 0%       217 ± 0%  -11.43%  (p=0.000 n=95+92)
KV/Scan/SQL/rows=10-10         280 ± 0%       252 ± 0%  -10.11%  (p=0.000 n=75+97)
KV/Delete/SQL/rows=10-10       478 ± 0%       459 ± 0%   -4.04%  (p=0.000 n=94+97)
KV/Delete/SQL/rows=1-10        297 ± 1%       287 ± 1%   -3.34%  (p=0.000 n=97+97)
KV/Update/SQL/rows=1-10        459 ± 0%       444 ± 0%   -3.27%  (p=0.000 n=97+97)
KV/Insert/SQL/rows=1-10        291 ± 0%       286 ± 0%   -1.72%  (p=0.000 n=82+86)
KV/Update/SQL/rows=10-10       763 ± 1%       750 ± 1%   -1.68%  (p=0.000 n=96+98)
KV/Insert/SQL/rows=10-10       489 ± 0%       484 ± 0%   -1.03%  (p=0.000 n=98+98)
```

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-Msf0VAp7PaGLZKR4avd:-Msf0VAqCb0DTA_Ogl_g:b-6jvip7) ([raw file](https://github.com/cockroachdb/cockroach/blob/165cbc40b59876ae2f9a2712ef3da622b3babd6c/pkg/kv/kvclient/rangecache/range_cache.go#L51)):*
> ```Go
> }
> 
> func newRangeCacheKey(key roachpb.RKey) *rangeCacheKey {
> ```

can you put some words about why these keys generally escape? Does it have to do with `OrderedCache` taking `interface{}` ? Any chance generics are gonna save us?
___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-Msf0pHF3DFPNBm7o1RI:-Msf0pHF3DFPNBm7o1RJ:b3xa9t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/165cbc40b59876ae2f9a2712ef3da622b3babd6c/pkg/kv/kvclient/rangecache/range_cache.go#L53)):*
> ```Go
> func newRangeCacheKey(key roachpb.RKey) *rangeCacheKey {
> 	k := rangeCacheKeyPool.Get().(*rangeCacheKey)
> 	*k = rangeCacheKey(key)
> ```

Does this cause `key` to escape in cases where `key` would not escape otherwise?
Even if in practice `key` is already on the heap, I'd consider making a copy of it and reusing the backing array for `k` (i.e. don't assign it to `nil` in `release()`).
___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-Msf-nyKD5RMf2m_nN-N:-Msf-nyKD5RMf2m_nN-O:b-klxhxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/165cbc40b59876ae2f9a2712ef3da622b3babd6c/pkg/kv/kvclient/rangecache/range_cache.go#L58)):*
> ```Go
> 
> func (k *rangeCacheKey) release() {
> 	*k = nil
> ```

what do you think of writing this as `*k = rangeCacheKey{}`? The `nil` is a bit ambiguous to me, because it's not apparent that this is a slice.

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-:-N8yTx3eDJNg0F0ZxrKL:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-Msf0VAp7PaGLZKR4avd:-N8yO2wp201TUumAlIoH:b-8mw6uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/165cbc40b59876ae2f9a2712ef3da622b3babd6c/pkg/kv/kvclient/rangecache/range_cache.go#L51)):*
Done.

> Any chance generics are gonna save us?

In the future, I hope :crossed_fingers: 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-Msf0pHF3DFPNBm7o1RI:-N8yOiiU3mTQsFIjEB6Q:b-82nyl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/165cbc40b59876ae2f9a2712ef3da622b3babd6c/pkg/kv/kvclient/rangecache/range_cache.go#L53)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Does this cause `key` to escape in cases where `key` would not escape otherwise?
Even if in practice `key` is already on the heap, I'd consider making a copy of it and reusing the backing array for `k` (i.e. don't assign it to `nil` in `release()`).
</blockquote></details>

I took a look. There are no cases where the backing array of `key` was on the stack and now gets pushed onto the heap.

I don't think we want to perform a deep copy of the key. `roachpb.Key`'s are already required to be immutable and this would be an extra cost that would be proportional to the size of the keys.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-Msf-nyKD5RMf2m_nN-N:-N8yPdT6EhdX97JjJZQM:bdkvcsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/165cbc40b59876ae2f9a2712ef3da622b3babd6c/pkg/kv/kvclient/rangecache/range_cache.go#L58)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what do you think of writing this as `*k = rangeCacheKey{}`? The `nil` is a bit ambiguous to me, because it's not apparent that this is a slice. 
</blockquote></details>

Good idea, this is clearer. Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74337#-:-N97YT3aAh8veZtvxmE-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=arulajmani

**Pull request merged**
