### PR TITLE
go.mod: bump Pebble to 3d9c6101a3a1

### PR DESCRIPTION
**Pull request by jbowens**
```
3d9c6101 db: allow switching directions using NextPrefix
df2a3f09 db: factor out iterator repositioning to first/last key
1a5e2335 db: require validity check before calling HasPointAndRange, RangeKeyChanged
6cd8bb04 sstable: implement NextPrefix for the sstable iterators
811a8c0e replay: implement Stringer on workload collector's Cleaner
eb5e1039 replay: add workload pacing
36a9cc67 replay: stub out workload replay logic
```

Epic: None
Release note: None

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94712)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`DEPS.bzl` line 9013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94712#-NKyFHp-8HCiJUYLPoAM:-NKyFHp-8HCiJUYLPoAN:btsgf39) ([raw file](https://github.com/cockroachdb/cockroach/blob/3767006f15b8c3110cce9b0184d6dca58ca5fabb/DEPS.bzl#L9013)):*
> ```Starlark
>         ],
>     )
>     go_repository(
> ```

This happened to me recently too. Try `./dev generate` first, which should get rid of this dep. More context [here](https://github.com/cockroachdb/cockroach/pull/94096#issuecomment-1362096878).

**Review by rickystewart — APPROVED** [review]

**Comment by rickystewart** [comment]
> Try ./dev generate first, which should get rid of this dep. More context https://github.com/cockroachdb/cockroach/pull/94096#issuecomment-1362096878.

Seems like this is something that could be added to that "bump pebble" script, right?

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94712#-:-NKyQCinCrU6QLZNhB2q:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by jbowens** [comment]
This bump is blocked on cockroachdb/pebble#2217

**Comment by jbowens** [comment]
Closing in favor of #94762.

**Pull request closed without merging**
