### PR TITLE
opt: clean up TableMeta copying

### PR DESCRIPTION
**Pull request by RaduBerinde**
The way we copy TableMetas is very sketchy: we do an implicit shallow
copy and then try to fix up the fields that can't be copied like that.
This is error prone and led to some recent issues.

This commit cleans this up: we now have a single `TableMeta.copyFrom`
function which explicitly copies the fields.

We also remove an unnecessary allocation for `userDefinedTypes` in the
common case where no UDTs are involved.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @rohany - I couldn't add you as a reviewer for some reason.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67079#-:-MdT0e8z6HmJm8-SHX0e:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by rohany** [comment]
lgtm :D

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67079#-:-MdTY5td142a2S5oWp9n:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67079#-:-MdTutm-AWlr1G2Wese-:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
