### PR TITLE
release-22.2: add pprof lables and log tags to jobs

### PR DESCRIPTION
**Pull request by lidorcarmel**
Backport of #91167 and #91630 (and then #92696 because of a flaky test).

Release justification: better observability - we will be able to see the resource usage of jobs on remote nodes (in pprof), and also we can get the log tags for traces running on behalf of remote jobs.

Note that there were a few conflicts when creating this backport, the main was that 22.2 is using `ScheduleFlow()` instead of `RunFlow()` used on master. It should be fine because both run the same cleanup code.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by lidorcarmel** [comment]
bummer, the new test fails under race or stress, I don't know why, yet.

**Comment by lidorcarmel** [comment]
fix in #92696.
I'll merge to master and then add it to this pr.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by lidorcarmel** [comment]
TFTR!!!

**Pull request merged**
