### PR TITLE
opt: propagate set operation output types to input columns

### LINKED ISSUE #34524: sql: error decoding bytes: couldn't decode type unknown
```
root@127.0.0.1:62165/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 5.724ms

root@127.0.0.1:62165/defaultdb> (select null from a) except (values((select 1 from a limit 1)), (1));
pq: error decoding 2 bytes: couldn't decode type unknown
```

### PR DESCRIPTION
**Pull request by rytaft**
This commit updates the `optbuilder` logic for set operations in which
the types of the input columns do not match the types of the output
columns. This can happen if a column on one side has type Unknown,
but the corresponding column on the other side has a known type such
as Int. The known type must be propagated to the side with the unknown
type to prevent errors in the execution engine related to decoding
types.

If there are any column types on either side that don't match the output,
then the `optbuilder` propagates the output types of the set operation down
to the input columns by wrapping the side with mismatched types in a
Project operation. The Project operation passes through columns that
already have the correct type, and creates cast expressions for those
that don't.

Fixes #34524

Release note (bug fix): Fixed an error that happened when executing
some set operations containing only nulls in one of the input columns.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
I didn't really follow the original discussion around the problems this causes for execution, but the opt changes :lgtm:. If there was a problem in execution that this fixes I think there should probably be a couple execution tests included in this change.

I also think that if there are some more general rules that this is satisfying then that should maybe be included in the comment above the definition of the set op private (e.g., "due to an execution limitation, both inputs to the set op must have matching types").

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-:-L_8K3VNDYLm4J_Qj-xF:b-gwilty)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/logprops/set, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_8VVPD9c6gRRP-Abn_:-L_8VVPD9c6gRRP-Abna:b-53sqeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/553736417c67535b44e84a07dd03d4ee0cf1072c/pkg/sql/opt/memo/testdata/logprops/set#L48)):*
> ```
> ----
> intersect
>  ├── columns: x:6(int!null) y:7(int) x:8(int!null)
> ```

It's not really clear to me why all the column ids in this file changed, it doesn't seem to me like they had to (but maybe they did)?

**Review by rytaft — COMMENTED** [review]
Thanks! Added an execution regression test and added the comment you suggested above `SetPrivate`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-:-L_Apo4F75mt_peqH-an:b1lakfs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/memo/testdata/logprops/set, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_8VVPD9c6gRRP-Abn_:-L_ATcMLBqqCMxEZfwBd:bmlapu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/553736417c67535b44e84a07dd03d4ee0cf1072c/pkg/sql/opt/memo/testdata/logprops/set#L48)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

It's not really clear to me why all the column ids in this file changed, it doesn't seem to me like they had to (but maybe they did)?
</blockquote></details>

Before this change we were only synthesizing new columns for `UNION`. But now it's clear that we need to synthesize new columns for all set operations if the input types don't match. If they do match (as in this example), we could get away with not synthesizing output columns for `EXCEPT` and `INTERSECT`, but it seemed like there was little benefit to adding the extra logic in the `optbuilder`...

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-:-L_F0zmnC-SvPJ55Zshz:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @RaduBerinde)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/rules/set.opt, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_FIP-d5yjr_qIRpp12:-L_FIP-d5yjr_qIRpp13:b-k0acvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c094d8f68c7f965e999196eb62d63aeeb8f9b7e/pkg/sql/opt/norm/rules/set.opt#L47)):*
> ```
> # The Project operation passes through columns that already have the correct
> # type, and creates cast expressions for those that don't.
> [PropagateSetTypesLeft, Normalize]
> ```

Isn't there a better way to create a reusable pattern here? This seems very specific to Set operations and not reusable for other operators which we may want to support in future.

I was expecting something like:
```
(Set
  $left:*
  $right:*
  $private:* & ^(ColTypesMatch (OutputCols $left) (SetOutputCols $private))
)
=>
((OpName)
  (RemapUnknownColTypes $left (SetOutputCols $private))
  $right
  $private
)
```
I probably don't have all the details right, but that's the gist of what I was thinking.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/rules/set.opt, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_FIP-d5yjr_qIRpp12:-L_FJy8F2fMzfczEz-CC:bt2zkwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c094d8f68c7f965e999196eb62d63aeeb8f9b7e/pkg/sql/opt/norm/rules/set.opt#L47)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't there a better way to create a reusable pattern here? This seems very specific to Set operations and not reusable for other operators which we may want to support in future.

I was expecting something like:
```
(Set
  $left:*
  $right:*
  $private:* & ^(ColTypesMatch (OutputCols $left) (SetOutputCols $private))
)
=>
((OpName)
  (RemapUnknownColTypes $left (SetOutputCols $private))
  $right
  $private
)
```
I probably don't have all the details right, but that's the gist of what I was thinking.
</blockquote></details>

I've thought more about this, and see why my idea above won't work well. The order of columns is important, and the `private` has to be remapped to new col ids, and probably other problems as well. I'm seeing what a major pain it is to do this as a normalization rule. I'm also thinking about the `Values` case, which will have similar pain, but will share virtually none of this code.

I wonder if we should simply prohibit "mixed type" scenarios altogether, in both the `Values` and `Set` operators. Maybe `optbuilder` should be inserting the casts where necessary when some of the input values are `Unknown` and some are not? It might be quite a bit easier to do there.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/set.opt, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_FIP-d5yjr_qIRpp12:-L_iezio0v8i0GaeYU8W:b4vy0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c094d8f68c7f965e999196eb62d63aeeb8f9b7e/pkg/sql/opt/norm/rules/set.opt#L47)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I've thought more about this, and see why my idea above won't work well. The order of columns is important, and the `private` has to be remapped to new col ids, and probably other problems as well. I'm seeing what a major pain it is to do this as a normalization rule. I'm also thinking about the `Values` case, which will have similar pain, but will share virtually none of this code.

I wonder if we should simply prohibit "mixed type" scenarios altogether, in both the `Values` and `Set` operators. Maybe `optbuilder` should be inserting the casts where necessary when some of the input values are `Unknown` and some are not? It might be quite a bit easier to do there.
</blockquote></details>

Done. I think you're right that it's better to put this logic in `optbuilder`.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 609 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_igueq7UuTnsSTnA2h:-L_igueq7UuTnsSTnA2i:bk3iu5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd68d8e85d22beb9f4e58e507735c0019be48e0/pkg/sql/opt/ops/relational.opt#L609)):*
> ```
> #   Out:   [5, 6]  <-- synthesized output columns
> #
> # Due to an execution limitation, both inputs to the set op must have matching
> ```

I'd say, `To make normalization rules and execution simpler, both inputs to the set op must have matching types.` I think this restriction will just make our lives easier overall, since mixed type inputs have also caused us a number of bugs (like in `CASE`).
___
*[pkg/sql/opt/optbuilder/union.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_ihYkk2gwlBBeLhmgA:-L_ihYkk2gwlBBeLhmgB:bvsggg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd68d8e85d22beb9f4e58e507735c0019be48e0/pkg/sql/opt/optbuilder/union.go#L91)):*
> ```Go
> 			typ = l.typ
> 			if r.typ == types.Unknown {
> 				propagateTypesRight = true
> ```

Isn't it possible to have cases where some column need to propagate left and other columns propagate right?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/ops/relational.opt, line 609 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_igueq7UuTnsSTnA2h:-L_ijE2r6uroMK8NLxSl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd68d8e85d22beb9f4e58e507735c0019be48e0/pkg/sql/opt/ops/relational.opt#L609)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd say, `To make normalization rules and execution simpler, both inputs to the set op must have matching types.` I think this restriction will just make our lives easier overall, since mixed type inputs have also caused us a number of bugs (like in `CASE`).
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/union.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_ihYkk2gwlBBeLhmgA:-L_ijF9_3hQPnX-AcXuY:bykel4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd68d8e85d22beb9f4e58e507735c0019be48e0/pkg/sql/opt/optbuilder/union.go#L91)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't it possible to have cases where some column need to propagate left and other columns propagate right?
</blockquote></details>

Yes -- this block is executed for each column, so it's possible that both `propagateTypesRight` and `propagateTypesLeft` are true at the end of the `for` loop. There's a test case for this in `optbuilder/testdata/union`

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-:-L_mVYG03W67m7KLkjSV:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/logprops/set, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_8VVPD9c6gRRP-Abn_:-L_mR8Qs2nrLlO_AQ9SZ:b-j2k41p) ([raw file](https://github.com/cockroachdb/cockroach/blob/553736417c67535b44e84a07dd03d4ee0cf1072c/pkg/sql/opt/memo/testdata/logprops/set#L48)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Before this change we were only synthesizing new columns for `UNION`. But now it's clear that we need to synthesize new columns for all set operations if the input types don't match. If they do match (as in this example), we could get away with not synthesizing output columns for `EXCEPT` and `INTERSECT`, but it seemed like there was little benefit to adding the extra logic in the `optbuilder`...
</blockquote></details>

In general, we want to avoid creating extra column ids, since once we get over 64 we start allocating extra objects for `FastIntSet`. If there's a relatively easy way to not allocate new ids, I generally do it.
___
*[pkg/sql/opt/optbuilder/union.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_ihYkk2gwlBBeLhmgA:-L_mUf0mEMSU5BozVVDm:b-7vo826) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd68d8e85d22beb9f4e58e507735c0019be48e0/pkg/sql/opt/optbuilder/union.go#L91)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Yes -- this block is executed for each column, so it's possible that both `propagateTypesRight` and `propagateTypesLeft` are true at the end of the `for` loop. There's a test case for this in `optbuilder/testdata/union`
</blockquote></details>

Ah, I see.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/logprops/set, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-L_8VVPD9c6gRRP-Abn_:-L_msXYv9Byo3z817oMe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/553736417c67535b44e84a07dd03d4ee0cf1072c/pkg/sql/opt/memo/testdata/logprops/set#L48)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In general, we want to avoid creating extra column ids, since once we get over 64 we start allocating extra objects for `FastIntSet`. If there's a relatively easy way to not allocate new ids, I generally do it.
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35321#-:-L_n2gYU-uZCZTK7uEVz:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

**Pull request merged**
