### PR TITLE
storage: optimize runs of put/cput commands if writing to virgin keyspace

### PR DESCRIPTION
**Pull request by spencerkimball**
…yspace

If more than 10 contiguous put or cput commands, the keyspace is searched
using a full order iterator to determine whether it's clear, in which case
the "blind" versions of MVCCPut and MVCCConditionalPut are used to more
efficiently write values without requiring a prefix iterator to search for
an existing value on each put.

Stable sorting was discontinued as it showed a performance hit on the
benchmarks, even for randomly ordered insertions.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6414)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Please post the benchmark results.
Haven't reviewed closely yet, but having the boolean on the proto looks semantically unsound (not saying I have a better idea, but the decision should be made much later and never be sent over the wire).

Also, nits: limit commit header to 50 chars, prefix with `storage:`

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1833 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmT7uk41jZMS2qlYD_:-KGmT7uk41jZMS2qlYDa:1239930745) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1833)):*
Faster to use `iter.Less()` rather than extracting the key and comparing.

---

*[storage/replica.go, line 1834 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTaXqlm-CMai6kSsy:-KGmTaXr3KBNVM9iKup4:-51901741) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1834)):*
Rather than extracting `iterKey` here, I think you should compare against the `iter` in the loop below. 

---

*[storage/replica.go, line 1895 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTxVOLZcGS2qdzj4C:-KGmTxVOLZcGS2qdzj4D:-1012621694) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1895)):*
The requests might not be put requests, which makes this comparison a little strange.

---

*[storage/replica.go, line 1896 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTuSALuUfJ3F_epON:-KGmTuSALuUfJ3F_epOO:-169069232) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1896)):*
I was imagining that you would do this work in the `range ba.Requests` loop. Something like:

```
var lastBlindIndex int
for index, union := range ba.Requests {
  blind := index < lastBlandIndex
  if !blind {
    lastBlindIndex = optimizePuts(batch, ba.Requests, index)
  }
  ...
}
```

The above is only half-baked, but the idea is to look at the current run of puts to see if they are virgin and compute that contiguous "blind" span. This would remove the need for the `{Put,ConditionalPut}Request.Blind` field as you would be able to pass a `blind` parameter to `executeCmd`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414)*

**Comment by spencerkimball** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1833 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmT7uk41jZMS2qlYD_:-KGn3SdeorQW3uPmVJjL:476727601) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1833)):*
Unfortunately unless we add `iter.LessThanEqual()`,  I'm out of luck. This really doesn't need to be faster, which is why I didn't choose to implement more iterator API calls.

---

*[storage/replica.go, line 1834 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTaXqlm-CMai6kSsy:-KGn3im_pFLjFJXj39tv:1865234009) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1834)):*
Would need `iter.Greater` in the loop below.

---

*[storage/replica.go, line 1895 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTxVOLZcGS2qdzj4C:-KGn43x10Pp8KCFmTPrP:-1858485310) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1895)):*
Yeah, I could drop this, but was just a way to avoid calling the method and stepping through in the common case, when there's no way you'll ever get a run of `optimizePutThreshold` Put or CPut requests. 

---

*[storage/replica.go, line 1896 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTuSALuUfJ3F_epON:-KGn4KVcfPPkeKx2kVDZ:1578922663) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1896)):*
A `blind` parameter to `executeCmd` seems more clumsy than the current `{Put,ConditionalPut}Request.Blind` field since `executeCmd` applies to every type of command. Having `blind` specified in this context is very confusing as it is meaningless for ~90% of the commands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414)*

**Comment by petermattis** [comment]
Ditto what @tschottdorf said about benchmarks. Or I can generate them if you'd like.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1834 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTaXqlm-CMai6kSsy:-KGo1aEom_i3a0mTwmfp:861843532) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1834)):*
If you had `iter.Greater`, you wouldn't need `iter.LessThanEqual` as you could use `!iter.Greater()`.

---

*[storage/replica.go, line 1896 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTuSALuUfJ3F_epON:-KGo1nIru0CeAosV5O_m:406213476) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1896)):*
A `blind` parameter is clumsier in one regard, but adding the `Blind` field to `{Put,ConditionalPut}Request` leaks that field to every user of those requests. For paranoia, you should be checking that incoming RPCs do not have the `Blind` field set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-:-KGo2Cjn62VdSLxIac9C:1572833872)*

**Comment by spencerkimball** [comment]
```
name                    old time/op  new time/op  delta
KVInsert1_Native-4       439µs ± 3%   444µs ± 3%     ~      (p=0.083 n=9+10)
KVInsert1_SQL-4          346µs ± 3%   346µs ± 1%     ~      (p=1.000 n=10+8)
KVInsert10_Native-4      640µs ± 2%   605µs ± 1%   -5.49%  (p=0.000 n=10+10)
KVInsert10_SQL-4         784µs ±11%   683µs ± 6%  -12.82%   (p=0.000 n=10+9)
KVInsert100_Native-4    2.37ms ± 5%  1.97ms ± 2%  -16.69%  (p=0.000 n=10+10)
KVInsert100_SQL-4       4.84ms ±16%  3.80ms ± 5%  -21.57%   (p=0.000 n=10+9)
KVInsert1000_Native-4   20.7ms ± 5%  18.1ms ± 8%  -12.46%   (p=0.000 n=9+10)
KVInsert1000_SQL-4      44.9ms ± 4%  38.1ms ± 5%  -15.13%  (p=0.000 n=10+10)
KVInsert10000_Native-4   262ms ± 9%   225ms ± 6%  -14.20%   (p=0.000 n=10+8)
KVInsert10000_SQL-4      629ms ±10%   585ms ±11%   -6.96%  (p=0.029 n=10+10)
```

**Comment by nvanbenschoten** [comment]
:lgtm: Nice! It would probably be worth trying to tune the `optimizePutThreshold` based on a semi-realisitc workload.

---

Reviewed 6 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1847 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGrsgJ7_Ob3Fwu3SSqC:-KGrsgJ7_Ob3Fwu3SSqD:1973185005) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e897909191da385eabe01c7c4e810dd60e32b8/storage/replica.go#L1847)):*
Can we just return here if not and avoid the looping and checking below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-:-KGruqTbyBRCBHnVuO2b:-2023959514)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1896 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGmTuSALuUfJ3F_epON:-KGsOYcEOUvnBQpgQguX:810359950) ([raw file](https://github.com/cockroachdb/cockroach/blob/456c78c7d640fd82ced605e869956bfa6ddf11ee/storage/replica.go#L1896)):*
Thinking about this again, it may be useful for higher-levels to specify that put/cput is "blind" (for example, when restoring a table). We'd want to avoid using the iterator in `optimizePuts`, but that is straightforward. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-:-KGsOp3sp-tV0FLMping:1417088721)*

**Comment by tschottdorf** [comment]
Sorry about being late to the party. Got one comment about mixing range-local and range-global keys, LGTM otherwise.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1868 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGugex_051dP0H6Shr7:-KGugexa7GHZsbVdAFB-:798224470) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e897909191da385eabe01c7c4e810dd60e32b8/storage/replica.go#L1868)):*
I think this will be somewhat sketchy with range-local addressing. What if you have a batch that mixes range-local and range-global keys? Your minKey will be `\x00...` and your maxKey `someUserKey`. I think that doesn't kill anything concretely here  but it decidedly means that the replica is scanning around way outside of its jurisdiction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-:-KGuhos_txbO816qCtFc:2013336117)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1868 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGugex_051dP0H6Shr7:-KGvjBK5u0eRVLQn5bX5:1072947615) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e897909191da385eabe01c7c4e810dd60e32b8/storage/replica.go#L1868)):*
Probably worth a comment in the code, but I don't think mixing range-local and range-global keys would cause a problem. Yes, we'd be scanning outside of the range's jurisdiction, but we're not doing anything with the key that is found, simply determining if any key exists within a span. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414)*

**Comment by bdarnell** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1868 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414#-KGugex_051dP0H6Shr7:-KHP8LbrBDBuq9RVA24W:-1699191217) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e897909191da385eabe01c7c4e810dd60e32b8/storage/replica.go#L1868)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Probably worth a comment in the code, but I don't think mixing range-local and range-global keys would cause a problem. Yes, we'd be scanning outside of the range's jurisdiction, but we're not doing anything with the key that is found, simply determining if any key exists within a span. </details>
I don't think it would be a correctness problem, but it could undermine this optimization if a key outside the range could prevent it from being applied. Probably wouldn't matter much, though, since no user transactions should touch range-local keys; those are just for non-performance-critical actions like splits and replica changes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6414)*

**Pull request merged**
