### PR TITLE
util/timeutil: new time-mocking utilities

### PR DESCRIPTION
**Pull request by tamird**
Also adds a lint to ensure `time.Now()` isn't used anywhere.

Note that this is a parial mock that doesn't mess with `time.After` or
`time.Sleep`.

cc @knz

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5019)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by petermattis** [comment]
Review status: 0 of 41 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[util/timeutil/time.go, line 21 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRrPAw3-OdLX1xUzHC:-KCRrPAw3-OdLX1xUzHD:1663022675) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time.go#L21)):*
Not sure I'm understanding the usage of the term "mockable" here. `Now()` is a fixed function which can't be changed. `now()` can be changed, but only between 2 implementations which isn't exactly mockable. I think this is fine, I'm just complaining about the comment.

---

*[util/timeutil/time.go, line 25 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRr5uMM21XhlZI7u4P:-KCRr5uMM21XhlZI7u4Q:1303678921) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time.go#L25)):*
You could have `Now` defined in the `time_{fake,real}.go`. I'm not seeing the purpose of defining it here.

---

*[util/timeutil/time_fake.go, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRqmOAqA1-kb0IM0EZ:-KCRqmOAqA1-kb0IM0E_:-263836601) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake.go#L17)):*
What's the rationale for using a build tag to protect this? Are you worried about someone setting the `CLOCKOFFSET` env variable in a production setting?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 41 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Makefile, line 176 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRuz1auRYErL7RyD5r:-KCRuz1auRYErL7RyD5s:-2019033097) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/Makefile#L176)):*
The first `util.Now()` should be `time.Now`, and the second should be `timeutil.Now`

---

*[util/timeutil/time_fake_test.go, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRw9gZ7bSCrJ4tX7V4:-KCRw9gZ7bSCrJ4tX7V5:176969713) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake_test.go#L17)):*
This test will almost never get run. If we want to test this then I'd move the necessary pieces out from behind the build tag and only have the binding to the "now" name be controlled by the tag. (but because it's not compiled in by default I'm not too concerned about testing). 

---

*[util/timeutil/time_fake_test.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRwJ9kJBw7GS62Jk8Q:-KCRwJ9kJBw7GS62Jk8R:-1036878051) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake_test.go#L28)):*
Why `[...]` instead of `[]`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-:-KCRxOxksBGathjN46-X:676834233)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 41 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[util/timeutil/time_fake.go, line 44 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCS-tuO-MyA-MYF16Ak:-KCS-tuO-MyA-MYF16Al:872330801) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake.go#L44)):*
Add() does some math even when offset == 0; it's probably better to test for offset == 0 here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by tamird** [comment]
Review status: 0 of 40 files reviewed at latest revision, 7 unresolved discussions.

---

*[Makefile, line 176 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRuz1auRYErL7RyD5r:-KCS1K9hrbH11aci2nIb:-1190566206) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/Makefile#L176)):*
ah, yes. overzealous `sed`. Done.

---

*[util/timeutil/time.go, line 21 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRrPAw3-OdLX1xUzHC:-KCS0tBKkgmbcHb4Z5ed:-1604456691) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time.go#L21)):*
Reworded.

---

*[util/timeutil/time.go, line 25 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRr5uMM21XhlZI7u4P:-KCS0qmLPSXy6LP0n7Ws:324650994) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time.go#L25)):*
Only reason was to have a singular place to put the doc comment. Anyway, this is rearranged now.

---

*[util/timeutil/time_fake.go, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRqmOAqA1-kb0IM0EZ:-KCS0yPVx1jXxPJi2fGP:-1675554353) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake.go#L17)):*
Yep. @tschottdorf insisted on this.

---

*[util/timeutil/time_fake.go, line 44 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCS-tuO-MyA-MYF16Ak:-KCS2Xqa_1gWGITOVkAt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake.go#L44)):*
Done.

---

*[util/timeutil/time_fake_test.go, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRw9gZ7bSCrJ4tX7V4:-KCS1AXlG1rC7ewhxybS:2048708067) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake_test.go#L17)):*
Yeah, this test was really for my own sanity checking. Reshuffled.

---

*[util/timeutil/time_fake_test.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRwJ9kJBw7GS62Jk8Q:-KCS1GEvW0mCxMMD1O33:753179097) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake_test.go#L28)):*
no particular reason. style guide?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by petermattis** [comment]
Review status: 0 of 40 files reviewed at latest revision, 5 unresolved discussions.

---

*[util/timeutil/time_fake.go, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRqmOAqA1-kb0IM0EZ:-KCS4j16CgyMF7aFJVGz:-450115792) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake.go#L17)):*
@tschottdorf What is the concern? Especially with the new structure the build tag simply adds irritation for manually testing with a clock offset.

---

*[util/timeutil/time_fake_test.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRwJ9kJBw7GS62Jk8Q:-KCS4wuJ27okn_tPmgAD:-1641084093) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake_test.go#L28)):*
One creates an array, the other a slice. I think we should prefer the slice unless an array is actually necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by tamird** [comment]
Review status: 0 of 40 files reviewed at latest revision, 5 unresolved discussions.

---

*[util/timeutil/time_fake_test.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRwJ9kJBw7GS62Jk8Q:-KCS5LSrFBbvj043GyOP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake_test.go#L28)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by bdarnell** [comment]
New arrangement LGTM

---

Review status: 0 of 40 files reviewed at latest revision, 5 unresolved discussions.

---

*[util/timeutil/time_fake_test.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRwJ9kJBw7GS62Jk8Q:-KCS4j_lK19f9ArYcUTr:-765246042) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake_test.go#L28)):*
Doesn't really matter, just curious. Slices are so much more common than arrays for this kind of thing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-:-KCS5PyMgf9CLjIxPt1A:-1624603729)*

**Comment by vivekmenezes** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 40 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1, 41 of 41 files at r2, 41 of 41 files at r3, 40 of 40 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[Makefile, line 177 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCSWEkZEg8K0e12IYOm:-KCSWEkZEg8K0e12IYOn:1072092961) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/Makefile#L177)):*
I can still call it though:

```go
f := time.Now
f()
```

---

*[util/timeutil/time.go, line 51 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCSWo7ZWrsMYNpm9NCZ:-KCSWo7ZWrsMYNpm9NC_:-746245248) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7862078c1839b516f46f751bb2fc4cb707c25c/util/timeutil/time.go#L51)):*
still :-1: on this, but if y'all are for it, then I guess that's what it's going to be. At least the name should be `COCKROACH_DEBUG_CLOCKOFFSET` though.

---

*[util/timeutil/time_fake.go, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRqmOAqA1-kb0IM0EZ:-KCSUtsmWbNwDE7mEFFe:1044590541) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake.go#L17)):*
Yeah, I'm very careful about magic undocumented flags. If it's in the production binary, it should have a more straightforward way to trigger it, i.e. through a flag hidden behind `-X`. Remember when we had the COCKROACH_DEV env variable? On more than one occasion that's caused some of us to operate under wrong assumptions. Don't want that happening outside of dev.
Agreed though that a build tag is unwieldy. I'd prefer the flag which gives a decent place for documentation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by tschottdorf** [comment]
for symmetry with

```
Flags converted to env variables:
--metrics-frequency -> COCKROACH_METRICS_FREQUENCY
--scan-interval -> COCKROACH_SCAN_INTERVAL
--scan-max-idle-time -> COCKROACH_SCAN_MAX_IDLE_TIME
--time-until-store-dead -> COCKROACH_TIME_UNTIL_STORE_DEAD
--max-offset -> COCKROACH_MAX_OFFSET
--linearlizable -> COCKROACH_LINEARIZABLE
```

this should probably be COCKROACH_SIMULATED_OFFSET.

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[Makefile, line 177 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCSWEkZEg8K0e12IYOm:-KCSZzni_GYreilz0cmw:-1874755069) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/Makefile#L177)):*
Hard to be bulletproof - if you import `time` with an alias then it's game over, and we need to implement these lints over the AST.

---

*[util/timeutil/time.go, line 51 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCSWo7ZWrsMYNpm9NCZ:-KCS_9BHrzEuI48tgcTv:133213462) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7862078c1839b516f46f751bb2fc4cb707c25c/util/timeutil/time.go#L51)):*
OK, I'll rework this into a flag.

---

*[util/timeutil/time_fake.go, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCRqmOAqA1-kb0IM0EZ:-KCS_SlxhFvlgDg9U85w:1050996261) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/util/timeutil/time_fake.go#L17)):*
Will change to a flag.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Makefile, line 177 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCSWEkZEg8K0e12IYOm:-KCSnQ8SelKNtCcTWC52:-2082131489) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/Makefile#L177)):*
well - we could just lint against importing time under an alias. But yeah, can't get too crazy. I was mostly worried because something like
`c := hlc.NewClock(time.Now)` seems like a valid API for some things.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019)*

**Comment by tamird** [comment]
OK, went with COCKROACH_SIMULATED_OFFSET and kept the build tag because people using this in production gives me sufficient pause to disallow it.

---

Review status: 0 of 41 files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 177 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-KCSWEkZEg8K0e12IYOm:-KCSpna5iOA_C5bytblZ:-297793496) ([raw file](https://github.com/cockroachdb/cockroach/blob/d210b4aa6c492fbb23d6bffdc8ffcdc739719209/Makefile#L177)):*
Updated, and this actually caught something (you wrote)!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-:-KCSprF1LgG1OuoFiyrl:-2140587929)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 41 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-:-KCT6NhEclJAmI6fKhfP:676834233)*

**Comment by tschottdorf** [comment]
:lgtm:, bring 'er in!

---

Reviewed 1 of 42 files at r9, 39 of 39 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5019#-:-KCTiGlHgW1wlICUFS_-:1214396445)*

**Pull request merged**
