### PR TITLE
sqlmigrations: copy entries into new system.namespace in 20.1

### PR DESCRIPTION
**Pull request by arulajmani**
In 20.1, CRDB started using a new system.namespace table that had an
additional primary key column, `ParentSchemaID`. Previously, all
namespace entries created before 20.1 could only be accessed through
the old table. This patch migrates them over to the new
`system.namespace` table.

In the migration:
- All databases (`parentID` = 0) are migrated over as is, with the
`parentSchemaID` set to 0.
- For every database, we add an entry for the `public` schema, which
has the ID 29.
- All tables (`parentID` != 0) are migrated over as is, with the
`parentSchemaID` set to 29.

Release note: none

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
General approach looks good. I left some clarifying questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-:-LwFhroQ2M9XBES4GONC:b-74hjlr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sqlmigrations/migrations.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFh-iQBeZv-jwNn6yT:-LwFh-iRCM2eVvCPCMlm:br813uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L274)):*
> ```Go
> 		newDescriptorIDs:    staticIDs(keys.ProtectedTimestampsRecordsTableID),
> 	},
> 	{
> ```

Does this want an `// Introduced in v20.1` comment?
___
*[pkg/sqlmigrations/migrations.go, line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFhMd9Au7onDF5hv3I:-LwFhMd9Au7onDF5hv3J:b-k0x2qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L275)):*
> ```Go
> 	},
> 	{
> 		name:                "create schema supporting system.namespace table",
> ```

This name is confusing to me. Doesn't the migration just insert a row for `system.namespace` into the new `system.namespace` table, or am I misunderstanding?
___
*[pkg/sqlmigrations/migrations.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFfrk8DUl6MiA3jF7T:-LwFfrk8DUl6MiA3jF7U:bzi75rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L278)):*
> ```Go
> 		workFn:              createSchemaSupportingSystemNamespaceTable,
> 		includedInBootstrap: cluster.VersionByKey(cluster.VersionNamespaceTableWithSchemas),
> 		newDescriptorIDs:    staticIDs(keys.NamespaceTableID),
> ```

I'm not sure what the effect of this field is, but is `NamespaceTableID` really a new descriptor ID? Doesn't it already exist when this migration is run?
___
*[pkg/sqlmigrations/migrations.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFdngz9k0UEqvRIxhJ:-LwFdnh-EtWzYO4r7U0d:b-6glc66) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L285)):*
> ```Go
> 		workFn:              migrateSystemNamespace,
> 		includedInBootstrap: cluster.VersionByKey(cluster.VersionNamespaceTableWithSchemas),
> 	},
> ```

Is there an advantage to making these two separate migrations vs one?
___
*[pkg/sqlmigrations/migrations.go, line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFe4553nOKkKr4cfi_:-LwFe4553nOKkKr4cfia:b-d4dhy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L668)):*
> ```Go
> 		b := txn.NewBatch()
> 		// The 19.2 namespace table contains an entry for "namespace" which maps to
> 		// the deprecated namespace tables ID. Even though the cluster version at
> ```

What is the effect of adding this entry? Does it affect the results of `select * from system.namespace` and whether they reflect the old or new table?

This is outside the scope of this PR, but thinking about this makes me realize that there are probably a few places where the code queries `system.namespace` which could behave strangely in a mixed 19.2/20.1 cluster. It would be good to grep through the codebase for examples of this. For example:
https://github.com/cockroachdb/cockroach/blob/ac49d1323b105ce52b2b0980384f12c2f584ef92/pkg/server/admin.go#L2180
___
*[pkg/sqlmigrations/migrations.go, line 698 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwF_4f471BdRBAAHMym:-LwF_4f471BdRBAAHMyn:b-jr1diz) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L698)):*
> ```Go
> INSERT INTO [%d AS namespace]("parentID", "parentSchemaID", name, id)
> (SELECT "parentID", %d, name, id FROM [%d AS namespace_deprecated] WHERE "parentID" = %d) 
> ON CONFLICT("parentID", "parentSchemaID", name) DO NOTHING`,
> ```

Minor: You can just write `ON CONFLICT DO NOTHING`.
___
*[pkg/sqlmigrations/migrations.go, line 717 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFaUJfAUCsrs6_yTU4:-LwFaUJfAUCsrs6_yTU5:bipn7wv) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L717)):*
> ```Go
> 		sqlbase.NamespaceTable.ID, keys.PublicSchemaID, sqlbase.DeprecatedNamespaceTable.ID, keys.RootNamespaceID,
> 	)
> 	_, err := r.sqlExecutor.ExecWithUser(
> ```

Do you think there would be any value in running all three statements in the same transaction? Would there be advantages to this migration being all-or-nothing or does it not matter?

**Review by arulajmani — COMMENTED** [review]
Addressed all comments. Open question on if the migration needs to be a create + copy over in one step, or two separate steps (as is right now). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-:-LwGR44e3QazuJOR-VJW:b-n06fvj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sqlmigrations/migrations.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFh-iQBeZv-jwNn6yT:-LwGIaZh4Gslnq_oFGvF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L274)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Does this want an `// Introduced in v20.1` comment?
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFhMd9Au7onDF5hv3I:-LwGIcgW4FWNLYfVIKD9:b-7zjc6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L275)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This name is confusing to me. Doesn't the migration just insert a row for `system.namespace` into the new `system.namespace` table, or am I misunderstanding?
</blockquote></details>

It writes the new `NamespaceTable` descriptor, and adds a name -> id mapping for the table descriptor. (essentially creating the new namespace table). Only caveat is that the name -> id mapping is added to the new `system.namespace` table, not the old one. 
___
*[pkg/sqlmigrations/migrations.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFfrk8DUl6MiA3jF7T:-LwGJ23y8brjbwPJ0cwY:bbid1i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L278)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'm not sure what the effect of this field is, but is `NamespaceTableID` really a new descriptor ID? Doesn't it already exist when this migration is run?
</blockquote></details>

`NamespaceTableID` used to be 2, but in 20.1 this changed to 30. Now, `DeprecatedNamespaceTableID` is 2. So (the new) `NamespaceTableID` does not exist when the migration is run. 
___
*[pkg/sqlmigrations/migrations.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFdngz9k0UEqvRIxhJ:-LwGQRDzD5Qz812QrTW-:b-jfecet) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L285)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is there an advantage to making these two separate migrations vs one?
</blockquote></details>

Not really, I just organized it to do create and then copy over in two steps. I can switch it to a single migration if that is preferable. 
___
*[pkg/sqlmigrations/migrations.go, line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFe4553nOKkKr4cfi_:-LwGMyWECu6USzncwz9p:b-oner11) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L668)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

What is the effect of adding this entry? Does it affect the results of `select * from system.namespace` and whether they reflect the old or new table?

This is outside the scope of this PR, but thinking about this makes me realize that there are probably a few places where the code queries `system.namespace` which could behave strangely in a mixed 19.2/20.1 cluster. It would be good to grep through the codebase for examples of this. For example:
https://github.com/cockroachdb/cockroach/blob/ac49d1323b105ce52b2b0980384f12c2f584ef92/pkg/server/admin.go#L2180
</blockquote></details>

In a 19.2/20.1 cluster, `system.namespace` will always refer to the `system.namespace_deprecated`. For system tables, we never actually query the KV layer to read from the system.namespace table -- because all system table descriptors are hard coded, we resolve them in code. 
So, querying system.namespace is analogous to querying the old namespace table in mixed version(19.2/20.1) clusters, and the new system.namespace table in 20.1 clusters.

Adding this entry in the new system.namespace table just ensures that when migrating over the deprecated table into the new one, we don't insert a (1, 29, namespace) -> 2 entry in the new table -- it continues to be (1, 29, namespace) -> 30. 
___
*[pkg/sqlmigrations/migrations.go, line 717 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFaUJfAUCsrs6_yTU4:-LwGMPumAKyRp34AlpJo:b-uaehra) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L717)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Do you think there would be any value in running all three statements in the same transaction? Would there be advantages to this migration being all-or-nothing or does it not matter?
</blockquote></details>

I don't think

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43203)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sqlmigrations/migrations.go, line 717 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFaUJfAUCsrs6_yTU4:-LwHDRJUDWPbuIoVzIxK:bmy0m86) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L717)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think 
</blockquote></details>

Oops left this comment unfinished. 

I don't think it matters if we do the migration all or nothing. I'm slightly in favor of this approach because it makes the intermediate queries readable.

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43203)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sqlmigrations/migrations.go, line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFhMd9Au7onDF5hv3I:-LwJPHzTAMLvozbCBvWw:b-v7dy7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L275)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It writes the new `NamespaceTable` descriptor, and adds a name -> id mapping for the table descriptor. (essentially creating the new namespace table). Only caveat is that the name -> id mapping is added to the new `system.namespace` table, not the old one. 
</blockquote></details>

Ah I missed that the descriptor was getting written. It might be clearer to just call it something like "write new system.namespace descriptor".
___
*[pkg/sqlmigrations/migrations.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFfrk8DUl6MiA3jF7T:-LwJPk4v2EQAblcI1NwG:b8xdn96) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L278)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

`NamespaceTableID` used to be 2, but in 20.1 this changed to 30. Now, `DeprecatedNamespaceTableID` is 2. So (the new) `NamespaceTableID` does not exist when the migration is run. 
</blockquote></details>

Makes sense. I got confused because we were already writing to the new namespace table even though it didn't have a descriptor.
___
*[pkg/sqlmigrations/migrations.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFdngz9k0UEqvRIxhJ:-LwJRfwk9gxslvwrOpcc:b7q2c6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L285)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Not really, I just organized it to do create and then copy over in two steps. I can switch it to a single migration if that is preferable. 
</blockquote></details>

My instinct is that it would be best to do the entire migration in a single transaction if possible. That way you don't have to worry about system.namespace being in a half-baked state if the migration fails partway through.

I guess the downside to this would be that `SELECT ... FROM system.namespace` queries could fail until the migration is complete?
___
*[pkg/sqlmigrations/migrations.go, line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFe4553nOKkKr4cfi_:-LwJTWsY9YqM5lsZK-7x:bjm2fzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L668)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

In a 19.2/20.1 cluster, `system.namespace` will always refer to the `system.namespace_deprecated`. For system tables, we never actually query the KV layer to read from the system.namespace table -- because all system table descriptors are hard coded, we resolve them in code. 
So, querying system.namespace is analogous to querying the old namespace table in mixed version(19.2/20.1) clusters, and the new system.namespace table in 20.1 clusters.

Adding this entry in the new system.namespace table just ensures that when migrating over the deprecated table into the new one, we don't insert a (1, 29, namespace) -> 2 entry in the new table -- it continues to be (1, 29, namespace) -> 30. 
</blockquote></details>

OK. I still think there is likely some weirdness with any code that queries `system.namespace`, since there could be old entries that won't get migrated until 20.2. But we can deal with that in a separate PR.
___
*[pkg/sqlmigrations/migrations.go, line 717 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFaUJfAUCsrs6_yTU4:-LwJTuyk0hN7xFvoTuHu:bqh3hpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L717)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Oops left this comment unfinished. 

I don't think it matters if we do the migration all or nothing. I'm slightly in favor of this approach because it makes the intermediate queries readable. 
</blockquote></details>

What is the advantage of intermediate queries being readable?

**Review by arulajmani — COMMENTED** [review]
TFTR! Discussed all the other the points offline

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-:-LwJe-NIEqvsFyljhqDd:bcu4dk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sqlmigrations/migrations.go, line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFhMd9Au7onDF5hv3I:-LwJ_tOK50kQ2dvrnGdL:b-qu2bvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L275)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Ah I missed that the descriptor was getting written. It might be clearer to just call it something like "write new system.namespace descriptor".
</blockquote></details>

Changed to `createNewSystemNamespaceDescriptor`

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43203)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sqlmigrations/migrations.go, line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFhMd9Au7onDF5hv3I:-LwJgl3k4TMqPaY0E3A4:bbzm9m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L275)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Changed to `createNewSystemNamespaceDescriptor` 
</blockquote></details>

Want to change the `name` as well?
___
*[pkg/sqlmigrations/migrations.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFdngz9k0UEqvRIxhJ:-LwJgpwA30b8ba6dOIx1:bre3bjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L285)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

My instinct is that it would be best to do the entire migration in a single transaction if possible. That way you don't have to worry about system.namespace being in a half-baked state if the migration fails partway through.

I guess the downside to this would be that `SELECT ... FROM system.namespace` queries could fail until the migration is complete?
</blockquote></details>

As discussed offline, it's not straightforward to use a single transaction, and since the cluster version won't get bumped until the migration completes, the new namespace table will not be queried while it is in a half-baked state. (Though it will be used for name resolution.)
___
*[pkg/sqlmigrations/migrations.go, line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-LwFe4553nOKkKr4cfi_:-LwJhHYNBVBFle4ZiM2_:b-wwrgt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/696c62bb7d2e314e2f48d34d498871fb46bbbc96/pkg/sqlmigrations/migrations.go#L668)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

OK. I still think there is likely some weirdness with any code that queries `system.namespace`, since there could be old entries that won't get migrated until 20.2. But we can deal with that in a separate PR.
</blockquote></details>

Opened #43243 to investigate the weirdness I was talking about.

**Review by arulajmani — COMMENTED** [review]
Fixed the nit, merging now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43203#-:-LwK0CHi72zTzMp3crl1:benfvf4)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
