### PR TITLE
Revert "kv, storage: HeartbeatTxnReq skips checking the abort span"

### PR DESCRIPTION
**Pull request by andreimatei**
This reverts commit 39f695010a26724a5beef7bfae39b3eb8b9c7095.
That commit reads:
"
Before this patch, the behavior of the heartbeat request was
inconsistent when it found an aborted txn record:
It either returned a successful response, with an aborted txn proto in
it (as suggested by the docs) or it would return TransactionAbortedError
if the abort span had been populated. No more; stick to the former.
This also fixes the problem that we were not handling the first case
correctly in the TxnCoordSender - we were not stopping the hb loop.
"

It would appear that it introduced a leak of heartbeat goroutines,
reproducible with TPCC against a local node. Reverting while I
investigate.

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @benesch

**Comment by tschottdorf** [comment]
LGTM (in case this is a clean revert, only skimmed the diff)

**Review by andreimatei — COMMENTED** [review]
It is a clean revert. I've had to now add a revert for a followup test cleanup commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27959#-:-LIMO5-i06Fvt96iqXDn:b85gaqu)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27959#-:-LIMkF-TDSkI-bQrcond:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
