### PR TITLE
changefeedccl: support DELETEs

### PR DESCRIPTION
**Pull request by danhhz**
@jordanlewis This is almost entirely RowFetcher changes; mind taking a look? I also need to figure out how we're going to do the continuous table leasing that changefeeds will need, which is much larger surgery. Happy to step back and discuss the approach if you're not feeling it.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: mod terminology / removing the scare quotes.

Normally I'd also complain about adding non-hotpath stuff to the hot path, but row fetcher is a bit of a beast to extend. Ideally, we could provide a separate implementation that only changefeeds use. However, the manipulations added seem very low cost, so I think it's okay.

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-LD-JaRHEwd6DDKGWUYl:-LD-JaRHEwd6DDKGWUYm:b-9h295x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5ab4df1a09eb82e2a5894aa98e8b0d974dbe9e/pkg/sql/sqlbase/rowfetcher.go#L92)):*
I found this comment hard to understand - I thought the verb and object were "are iterated", but it's really a description. I also think you should get rid of "sideband" - you keep putting in quotes as if it's something weird! That would scare me when trying to modify or understand this later.

What about:

> The following fields are updated on every call to NextRow. They contain MVCC metadata for each row. They're not important to ordinary consumers of RowFetcher that only concern themselves with actual SQL row data.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-LD-KUxgEcWAeILma6T0:-LD-KUxgEcWAeILma6T1:bcdziwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5ab4df1a09eb82e2a5894aa98e8b0d974dbe9e/pkg/sql/sqlbase/rowfetcher.go#L102)):*
> ```Go
> 	// meaningful when kv deletion tombstones are returned by the kvFetcher,
> 	// which the one used by `StartScan` (the common case) doesnt. Notably,
> 	// changefeeds use this by providing raw kvs with tombstones unfiltered via
> ```

seems package boundary violating to talk about changefeeds here, but I guess it's just a comment.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-LD-Kd1I0AleSDiobAe8:-LD-Kd1I0AleSDiobAe9:b-qy1rde) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5ab4df1a09eb82e2a5894aa98e8b0d974dbe9e/pkg/sql/sqlbase/rowfetcher.go#L666)):*
> ```Go
> 		rf.valueColsFound = 0
> 
> 		// Reset the "sideband" data.
> ```

How about: `// Reset the MVCC metadata for the next row.` or something.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-:-LD-L0pm4sIiZ-A6LxH_:b9qnx3v)*

**Comment by danhhz** [comment]
TFTR! Removed all scarequotes and uses of the word sideband

As much as I don't want to be the one to pick this off, there may be a small RowFetcher refactor coming up for changefeeds. They have all sorts of crazy requirements that the normal code doesn't (multiple versions of the same row, multiple versions of each table descriptor). I have no idea yet whether changefeeds should be using a modified RowFetcher or something else that shares some underlying components or what.

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-LD-JaRHEwd6DDKGWUYl:-LD26i8L82S_aIQaeQzF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5ab4df1a09eb82e2a5894aa98e8b0d974dbe9e/pkg/sql/sqlbase/rowfetcher.go#L92)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I found this comment hard to understand - I thought the verb and object were "are iterated", but it's really a description. I also think you should get rid of "sideband" - you keep putting in quotes as if it's something weird! That would scare me when trying to modify or understand this later.

What about:

> The following fields are updated on every call to NextRow. They contain MVCC metadata for each row. They're not important to ordinary consumers of RowFetcher that only concern themselves with actual SQL row data.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-LD-KUxgEcWAeILma6T0:-LD24P1j08h9fzk3-nqw:bkfzfro) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5ab4df1a09eb82e2a5894aa98e8b0d974dbe9e/pkg/sql/sqlbase/rowfetcher.go#L102)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

seems package boundary violating to talk about changefeeds here, but I guess it's just a comment.
</blockquote></details>

IMO it's always fine (and a good idea) to call out the motivation for something non-obvious in a low level package like this but YMMV

---

*[pkg/sql/sqlbase/rowfetcher.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-LD-Kd1I0AleSDiobAe8:-LD24m0Q3x4tjjBpzCTV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5ab4df1a09eb82e2a5894aa98e8b0d974dbe9e/pkg/sql/sqlbase/rowfetcher.go#L666)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

How about: `// Reset the MVCC metadata for the next row.` or something.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25727#-:-LD28STl6OXyroY5-yJY:b-l46fwb)*

**Comment by danhhz** [comment]
bors r=jordanlewis

**Comment by jordanlewis** [comment]
Reviewed 5 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25727)*

**Pull request merged**
