### PR TITLE
opt: make the placeholder fast-path into an optgen rule

### PR DESCRIPTION
**Pull request by DrewKimball**
This is a refactor of the placeholder fast path to use optgen fast-path
rules instead of go code. This does not change the behavior of the
placeholder fast path, but opens the way for other fast-path rules to
be implemented.

This patch adds a new type of rule, tagged with `FastPath`. Fast path
rules attempt to match the root of the expression tree. If the match is
successful, the new expression returned by the rule will be used as the
new root. The physical properties of the expresssion tree will be set,
and the memo will be considered fully optimized.

It is possible for fast-path rules to use `(Root)` as the replace pattern.
This indicates that the rule will not make any changes to the matched
expression, and that it will be considered optimized as-is.

Informs https://github.com/cockroachdb/cockroach/issues/77128

Release note: None

### CODE REVIEW

**Review by cucaroach — COMMENTED** [review]
> Reviewed 1 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104760)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYN-ZWlAHzaDrvfMqhc):*
Nice work!   So like the optimization process stops and we move on? Seems like a useful thing but also seems like a bit of a footgun. Might be nice to talk about some examples that motivated this work and some possible future avenues. What makes it fast? Is it the short-circuiting of exploration or avoiding the reconstruction of the memo? What changes if any do we see in the opt benchmarks?

**Review by cucaroach — APPROVED** [review]
:lgtm:   

I don't fully grok whats going on with the property stuff and I'm a bit nervous about increased usage of memo's across multiple sessions and there being races, I know we've had issues there in the past. Maybe some kv roachtest testing with race enabled would be in order?

> Reviewed 28 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-:-NYN8R9r3rdZOJcjQWKh:b-25awx3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/fastpath/testdata/scan` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYN7dMVAUwUHFeQhGaV:-NYN7dMVAUwUHFeQhGaW:b58bwpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/fastpath/testdata/scan#L31)):*
> ```
> 
> fast-path
> SELECT * FROM kv WHERE k = $1
> ```

Since we now use this code in non-placeholder situations should we add some fast-path tests w/o placeholders to make sure that's working as expected too?

**Review by mgartner — CHANGES_REQUESTED** [review]
Very cool!

This would be a good opportunity to add detailed commentary on how the entire fast-path process works (fast_path.go might be a good place for this). E.g., when are the fast-path rules applied, what happens then they match and alter the expression, and what happens when a cache fast-path memo is reused and how do the placeholders get filled in.

> Reviewed 8 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-:-NYYNO-D8ETotANsGDC8:b-q0nljv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @DrewKimball)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYG_5g-zSTVoad3HEd):*
nit: explain when this matching happens and that the fast-path expression is cached and reused
___
*[`pkg/sql/opt/fastpath/fast_path.og.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYMUKD8d4sBrAh7Di4:-NYYMUKD8d4sBrAh7Di5:b-7c4f0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/fastpath/fast_path.og.go#L1)):*
> ```Go
> // Code generated by optgen; DO NOT EDIT.
> ```

We should exclude this file by adding it to `pkg/sql/opt/fastpath/.gitignore`. There might be some bazel magic we have to do to get it to generate correctly in the same way we generate factory.og.go - not sure if you've already come across that.
___
*[`pkg/sql/opt/xform/optimizer.go` line 1188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYHxy-6rxV5MXTCubG:-NYYHxy-6rxV5MXTCubH:b4v1prv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/xform/optimizer.go#L1188)):*
> there is a single canonical expression tree

This is a bit confusing when you see that the generated fast path code is adding new expressions to existing groups. The memo then has more than one expressions tree. It's not clear to me how the new expression is picked as the "best" expression when the memo is detached.
___
*[`pkg/sql/opt/xform/optimizer.go` line 1210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYFa7a2SUYgYsYF6Hn:-NYYFa7a2SUYgYsYF6Ho:b-19seec) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/xform/optimizer.go#L1210)):*
> ```Go
> 		// since there's only one possible tree.
> 		// TODO(mgartner): Think about whether we need to short-circuit in the
> 		// presence or absence of UDFs.
> ```

I'll have to think more about this, but we should have some tests. Or we should return false if there is a `UDF` to prevent the fast-path entirely for now until we confirm it's safe.
___
*[`pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYFyJB4z2S9gtmgnC2:-NYYFyJB4z2S9gtmgnC3:b7dax46) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath#L14)):*
> ```
> 	Constraint Constraint
> 	HardLimit  ScanLimit
> 	Flags      ScanFlags
> ```

nit: Use spaces instead of tabs here for consistency.
___
*[`pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYKTPU3QrmXPD3HAHd:-NYYHFkJDgCyv2v4T9lr:b4rib64) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath#L102)):*
> ```
> 					}
> 
> 					_interned := _fp.mem.AddScanToGroup(_expr, _root)
> ```

Is it necessary to add the new expression to a memo group?

**Review by DrewKimball — COMMENTED** [review]
>I don't fully grok whats going on with the property stuff and I'm a bit nervous about increased usage of memo's across multiple sessions and there being races, I know we've had issues there in the past. Maybe some kv roachtest testing with race enabled would be in order?

I think with the change I just made to only match in the presence of placeholders, we should no longer apply the fast path in more cases than before with this PR. Worth mentioning that the fast path only applies during initial creation of the memo - any concurrency only happens after this step, and concurrent accesses to the memo never modify it (at least not without copying it first). More concurrency testing does sound like a good idea, though.

>This would be a good opportunity to add detailed commentary on how the entire fast-path process works (fast\_path.go might be a good place for this). E.g., when are the fast-path rules applied, what happens then they match and alter the expression, and what happens when a cache fast-path memo is reused and how do the placeholders get filled in.

Great point, will do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-:-NYuwFEMD_CSJE1DpvXP:b3vogvd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @mgartner)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYG_5g-zSTVoad3HEd):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: explain when this matching happens and that the fast-path expression is cached and reused
</blockquote></details>

Done.
___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYN-ZWlAHzaDrvfMqhc):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Nice work!   So like the optimization process stops and we move on? Seems like a useful thing but also seems like a bit of a footgun. Might be nice to talk about some examples that motivated this work and some possible future avenues. What makes it fast? Is it the short-circuiting of exploration or avoiding the reconstruction of the memo? What changes if any do we see in the opt benchmarks?
</blockquote></details>

I believe #63807 saw some ~10% improvement on a read-heavy benchmark, with more context in #57223. I've added some more context/detail to the commit message.
___
*[`pkg/sql/opt/fastpath/fast_path.og.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYMUKD8d4sBrAh7Di4:-NYuuToMBKm48sm36P__:bq12ham) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/fastpath/fast_path.og.go#L1)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We should exclude this file by adding it to `pkg/sql/opt/fastpath/.gitignore`. There might be some bazel magic we have to do to get it to generate correctly in the same way we generate factory.og.go - not sure if you've already come across that.
</blockquote></details>

Done. I don't see any magic to generate the gitignore, so I just added it manually.
___
*[`pkg/sql/opt/xform/optimizer.go` line 1188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYHxy-6rxV5MXTCubG:-NYw0Fu94V7idsg3PxJV:b-ab7qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/xform/optimizer.go#L1188)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> there is a single canonical expression tree

This is a bit confusing when you see that the generated fast path code is adding new expressions to existing groups. The memo then has more than one expressions tree. It's not clear to me how the new expression is picked as the "best" expression when the memo is detached.
</blockquote></details>

`setProps` doesn't have to worry about "best" expressions, since it just traverses the tree that's given to it. I've removed the reference to `setLowestCostTree` since I think it just adds confusion. I'll rework the comment as well; let me know what you think.

I also realized that `setProps` can panic, so I've moved the panic-catching to `TryFastPath` above from `fastpath.TryOptimizerFastPath`.
___
*[`pkg/sql/opt/xform/optimizer.go` line 1210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYFa7a2SUYgYsYF6Hn:-NYw19rwCFxwZ48mixE2:b-g5tj84) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/xform/optimizer.go#L1210)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'll have to think more about this, but we should have some tests. Or we should return false if there is a `UDF` to prevent the fast-path entirely for now until we confirm it's safe.
</blockquote></details>

It seems fine to prevent it for now, so I'll just do that.
___
*[`pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYFyJB4z2S9gtmgnC2:-NYuvKPQ84qyxUtt7icT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath#L14)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Use spaces instead of tabs here for consistency.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYYKTPU3QrmXPD3HAHd:-NYuvoQRD_YFyx3rT6SD:b-pmu27) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/optgen/cmd/optgen/testdata/fastpath#L102)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is it necessary to add the new expression to a memo group?
</blockquote></details>

It's necessary because the group contains the properties. While `Memoize...` could do the same, we'd have to implement `buildPlaceholderScanProps` and maybe others as well.
___
*[`pkg/sql/opt/fastpath/testdata/scan` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104760#-NYN7dMVAUwUHFeQhGaV:-NYuuvRIEyq6qRVWo5_b:b-3unxuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9e35c67d80b1a986a4c5abac071e95125d82ba4/pkg/sql/opt/fastpath/testdata/scan#L31)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Since we now use this code in non-placeholder situations should we add some fast-path tests w/o placeholders to make sure that's working as expected too?
</blockquote></details>

Good point. I've modified the rules to only match the case when there are placeholders, since I think it's best not to change behavior from the existing fast path logic for now.

**Comment by DrewKimball** [comment]
@mgartner friendly ping if you have time over the next week or so - sounds like Mark might want to build on top of this.

**Comment by michae2** [comment]
After talking to @DrewKimball we're going to save this for 24.1.

**Comment by mgartner** [comment]
I believe [generic query plans](https://github.com/cockroachdb/cockroach/pull/117284) will make the placeholder fast path and this PR obsolete.

**Pull request closed without merging**
