### PR TITLE
exec: don't template asc vs desc in mj

### PR DESCRIPTION
**Pull request by jordanlewis**
Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40595#-LoMiFDcEt8_0pX2-MD4:-LoMiFDcEt8_0pX2-MD5:bd2pdnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c372574af14fed68aa151be00b256e6a2d5f2b7/pkg/sql/exec/mergejoiner_tmpl.go#L274)):*
> ```Go
> 					_ASSIGN_LT("incrementLeft", "lVal", "rVal")
> 					// Switch the direction of increment if we're sorted descendingly.
> 					incrementLeft = incrementLeft == (o.left.directions[eqColIdx] == distsqlpb.Ordering_Column_ASC)
> ```

I'm curious to see what the performance hit is. I feel like it shouldn't be too bad, and this change is justified. I'll pull from your branch and run the benchmarks.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40595#-LoMhzhN7wuZr7r6ItCj:-LoMhzhN7wuZr7r6ItCk:b-7329go) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c372574af14fed68aa151be00b256e6a2d5f2b7/pkg/sql/exec/mergejoiner_tmpl.go#L588)):*
> ```Go
> 		if lVec.MaybeHasNulls() {
> 			if rVec.MaybeHasNulls() {
> 				_PROBE_SWITCH(_JOIN_TYPE, _FILTER_INFO, _SEL_ARG, true, true, false)
> ```

We also should update the corresponding template in `mergejoiner_gen` (as well as remove `_ASC_DIRECTION` replacement).

**Review by yuzefovich — APPROVED** [review]
:lgtm: This cuts off another 7mb or so, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40595#-:-LoMkaeiBTJgaoVahmLn:b1f0k2x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40595#-LoMiFDcEt8_0pX2-MD4:-LoMkPGi4w0lpSBrRmvJ:b-cb316j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c372574af14fed68aa151be00b256e6a2d5f2b7/pkg/sql/exec/mergejoiner_tmpl.go#L274)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm curious to see what the performance hit is. I feel like it shouldn't be too bad, and this change is justified. I'll pull from your branch and run the benchmarks.
</blockquote></details>

On a quick run, there is like 3-5% performance hit which - considering how fast the merge joiner is relative to other stuff - is very minor.

**Comment by jordanlewis** [comment]
TFTR! Fixed the template.

bors r+

**Pull request merged**
