### PR TITLE
prereqs: handle CWDs with symlinks

### PR DESCRIPTION
**Pull request by benesch**
See commits for details.

### CODE REVIEW

**Comment by knz** [comment]
Any way to have the Makefile `cd` to the absdir before running anything? It would also fix `make build` and the -X handling

**Comment by benesch** [comment]
...I guess we could unset $PWD? I'm just realizing what a colossal hack CD'ing into a symlink is.

**Comment by knz** [comment]
I don't understand what you mean
Right now I have a script which I use as prefix to any command I run:

```
#!/bin/sh
cd $(cd $(dirname "$0") && /bin/pwd)
exec "$@"
```

would be nice if `make` would do that for me

**Comment by benesch** [comment]
I mean that you can't actually CD into a symlink. `chdir(2)` will always resolve the symlink for you. Your shell hacks around this by setting the PWD env var to the logical path, with symlinks, while actually `chdir`ing into the physical path. So when Make executes its physical CWD is correct, but it's passing along a PWD value that some programs, including the Go runtime, use to infer a logical CWD that includes the symlink. This isn't easily solved. For example, `PWD := $(CURDIR)` doesn't actually modify the PWD env var for commands executed with `$(shell)`, it seems.

**Comment by knz** [comment]
Oh now I understand why unsetting $PWD would work (at least, I'd expect it to work based on your explanation).

> For example, PWD := $(CURDIR) doesn't actually modify the PWD env var for commands executed with $(shell), it seems.

Have you determined why it doesnt? This surprises me.

**Comment by knz** [comment]
Oh perhaps $(CURDIR) is based off $PWD in the first place. What about `PWD := $(shell /bin/pwd)`

**Comment by benesch** [comment]
I believe that Make's `export` and `unexport` directives only refer to the environment that recipes execute in, not the environment of `$(shell ...)` commands. I'm just shooting in the dark here, though.

It's possible that none of the commands we invoke via `$(shell)` actually care about the PWD, but I'm nervous about having the PWD differ between the two contexts. That's a bug waiting to happen.

**Comment by knz** [comment]
I think `$(shell ...)` uses `$(SHELL)`? Then maybe `SHELL := /usr/bin/env PWD=$(CURDIR) bash`

**Review by knz — APPROVED** [review]

**Comment by benesch** [comment]
bors=knz

**Comment by knz** [comment]
@benesch "bors=knz" doesn't do anything :smiley_cat: 

bors r+

**Pull request merged**
