### PR TITLE
sql: switch internal executor to iterator pattern

### PR DESCRIPTION
**Pull request by jordanlewis**
Note: this is still very much WIP

This commit removes the non-streaming way of using the internal
executor, replacing it with a simple iterator style interface.

Release note (sql change): internal queries are streamed instead of
buffered, potentially using less memory.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49148)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/internal.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49148#-M7ar-gW06QIdKpsMkSd:-M7ar-gW06QIdKpsMkSe:bomcdz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83b67da9b850a69c600db536926a42b39a2db68/pkg/sql/internal.go#L420)):*
> ```Go
> 	stmt string,
> 	qargs ...interface{},
> ) (r *rowsIterator, retErr error) {
> ```

I think your life will be simpler if you were to also return a `cleanup func()` and have all the callers defer a call to that. Otherwise there is no clear place where you can guarantee the intex finishes execution.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 40 files at r1, 2 of 42 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49148)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/internal.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49148#-M7ar-gW06QIdKpsMkSd:-MEMPk_380CvwfEl8Vqg:b-f72q74) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83b67da9b850a69c600db536926a42b39a2db68/pkg/sql/internal.go#L420)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think your life will be simpler if you were to also return a `cleanup func()` and have all the callers defer a call to that. Otherwise there is no clear place where you can guarantee the intex finishes execution.
</blockquote></details>

unless you intended the iterator's Close() function to play that role. Still, the RAII semantics should be clarified as comments above the functions.

**Comment by knz** [comment]
We definitely want to resume this work -- I'd suggest to place it as a high-priority item for the 21.1 cycle.

**Comment by jordanlewis** [comment]
This has been redone better by @yuzefovich 🙇 thank you!

**Pull request closed without merging**
