### PR TITLE
kvfollowerreadsccl: deflake TestFollowerReadsWithStaleDescriptor

### LINKED ISSUE #125898: ccl/kvccl/kvfollowerreadsccl: TestFollowerReadsWithStaleDescriptor failed
ccl/kvccl/kvfollowerreadsccl.TestFollowerReadsWithStaleDescriptor [failed](https://tanzanite.cluster.engflow.com/invocations/default/d6131356-c521-4ad1-a458-6674f2f5ecbb?testReportRun=3&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL2t2Y2NsL2t2Zm9sbG93ZXJyZWFkc2NjbDprdmZvbGxvd2VycmVhZHNjY2xfdGVzdA==) on release-24.1 @ [c4641acfdb8533ccf951535f408ec61df8437b62](https://github.com/cockroachdb/cockroach/commits/c4641acfdb8533ccf951535f408ec61df8437b62):

```
=== RUN   TestFollowerReadsWithStaleDescriptor
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestFollowerReadsWithStaleDescriptor691115469
    test_log_scope.go:81: use -show-logs to present logs inline

pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go:891: (TestFollowerReadsWithStaleDescriptor)
	NOTICE: .DistSenderI() called via implicit interface ApplicationLayerInterface;
HINT: consider using .ApplicationLayer().DistSenderI() instead.
TIP: consider replacing the test server initialization from:
    ts, ... := serverutils.StartServer(t, ...)
    defer ts.Stopper().Stop(...)
to:
    srv, ... := serverutils.StartServer(t, ...)
    defer srv.Stopper().Stop(...)
    ts := srv.ApplicationLayer()

See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization
    followerreads_test.go:895: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go:895
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestFollowerReadsWithStaleDescriptor
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestFollowerReadsWithStaleDescriptor691115469
--- FAIL: TestFollowerReadsWithStaleDescriptor (91.21s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFollowerReadsWithStaleDescriptor.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39653

### PR DESCRIPTION
**Pull request by arulajmani**
This test wants to tightly control where leases are placed to make assertions about follower reads. Most of this is achieved by running the cluster in replication mode manual, which disables the lease queue. However, we're still susceptible to load based rebalancing transferring leases unexpectedly, which could cause the test to fail. Disable the store rebalancer.

While here, we also do the same for
TestSecondaryTenantFollowerReadsRouting which could also run into this.

Closes #125898

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

**Comment by rickystewart** [comment]
Not sure what happened here, but it looks like you need to rebase and use `kvserver.LBRebalancingMode` instead of `int64`.

**Comment by rickystewart** [comment]
Fairly certain the merge skew came from #125700.

**Comment by arulajmani** [comment]
Thanks @rickystewart. 

bors r+

**Pull request merged**
