### PR TITLE
sql: don't assume session zone in non-zone timestamps

### PR DESCRIPTION
**Pull request by dt**
`TIMESTAMP WITH TIME ZONE` should assume the session zone (and does) and get rendered
in the session zone when sent, which means a string like `2016-02-03 23:50` should
round-trip no matter what the zone.

However non-`WITH TIME ZONE` timestamp strings are rendered exactly as they are on disk
with a zero offset, not with the session zone (since they have no zone). Thus, to maintain
the property of round-tripping a parsed string with no offset specified, since it will
returned with a zero offset, it must also be parsed and stored assuming a zero offset (rather
than the session offset as assumed above).

In both cases, an _explicit_ offset in the parsed string is always used if present.
Obiously if it is different than the one that would have been assumed by parsing --
UTC for non-`WITH TIME ZONE` strings, the session offset for `WITH TIME ZONE` -- then
the string will not round-trip verbatim, but in both cases that makes sense as an
explicit offset changed the meaning of that string.

Unfortunately Go is very strict when parsing abbreviated zone names -- with
the exception of 'UTC' and 'GMT', it only supports abbreviations that are
defined in the local in which it is parsing. Worse, it doesn't return any
sort of error for unresolved zones, but rather simply pretends they have a
zero offset. This means changing the session zone such that an abbreviation
like 'CET' stops being resolved _silently_ changes the offsets of parsed
strings with 'CET' offsets to zero.

We attempt to detect when this has happened and return an error instead.

Postgres does its own parsing and just maintains a list of zone abbreviations
that are always recognized, regardless of the session location. If this check
ends up catching too many users, we may need to do the same.

Also fixes a few casts and functions that only handled `Timestamp` types to also handle
`TimestampTZ`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9444)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/parser/datum.go, line 868 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzRlTtAJUDQcSmRfff:-KRzRlTtAJUDQcSmRffg:b-7x8pn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/parser/datum.go#L868)):*
> ```Go
> // ParseDTimestamp parses and returns the *DTimestamp Datum value represented by
> // the provided string in the provided location, or an error if parsing is unsuccessful.
> func ParseDTimestamp(s string, loc *time.Location, precision time.Duration) (*DTimestamp, error) {
> ```

`loc` should be removed from the signature here if it's not used, otherwise it will confuse users of it who will assume it does something.

---

*[sql/testdata/datetime, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzUw36aDi4Q146vKFF:-KRzUw36aDi4Q146vKFG:bf230oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/testdata/datetime#L75)):*
> ```
> 123  2015-08-30 03:34:45.34567 +0000 +0000  2015-08-29 22:34:45.34567 -0500 -0500  2015-08-30 00:00:00 +0000 +0000  34h0m2s
> 234  2015-08-25 06:45:45.53453 +0000 +0000  2015-08-25 01:45:45.53453 -0500 -0500  2015-08-25 00:00:00 +0000 +0000  2h45m2.234s
> 345  2015-08-29 23:10:09.98763 +0000 +0000  2015-08-29 23:10:09.98763 -0500 -0500  2015-08-28 00:00:00 +0000 +0000  234h45m2.234s
> ```

Does the date behavior here match postgres? That is, the date is parsed with the session TZ? Seems odd but all this stuff is odd.

---

*[sql/testdata/datetime, line 419 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzVVR7qxHt7O0LGSIr:-KRzVVR7qxHt7O0LGSIs:b2d49g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/testdata/datetime#L419)):*
> ```
> 
> query T
> SELECT '2015-08-25 05:45:45.53453 CET'::timestamptz WHERE false
> ```

why WHERE FALSE? To make sure it doesn't error on "CET"?

---

*[sql/testdata/datetime, line 558 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzWLx2w6xGlgTDoRz0:-KRzWLx3QI9b9b8qv58K:b2nif2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/testdata/datetime#L558)):*
> ```
> SELECT b, b::date, c, c::date FROM u WHERE a = 123
> ----
> 2015-08-30 03:34:45.34567 +0000 +0000  2015-08-29 00:00:00 +0000 +0000  2015-08-29 22:34:45.34567 -0500 -0500  2015-08-29 00:00:00 +0000 +0000
> ```

wat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444)*

**Comment by tamird** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/datum.go, line 869 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzqT1UjSBz4AWwtF7V:-KRzqT1UjSBz4AWwtF7W:b-pj45po) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/parser/datum.go#L869)):*
> ```Go
> // the provided string in the provided location, or an error if parsing is unsuccessful.
> func ParseDTimestamp(s string, loc *time.Location, precision time.Duration) (*DTimestamp, error) {
> 	// `ParseInLocation` uses the location provided both for resolving an explicit
> ```

this comment and the use of `time.UTC` should be in the caller, I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444)*

**Comment by dt** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/datum.go, line 868 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzRlTtAJUDQcSmRfff:-KScFeXU5R3ICFrXGzvj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/parser/datum.go#L868)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> `loc` should be removed from the signature here if it's not used, otherwise it will confuse users of it who will assume it does something.
</details>
Done.

---

*[sql/parser/datum.go, line 869 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzqT1UjSBz4AWwtF7V:-KScFwsnGHF9WNucUbgY:b1awayo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/parser/datum.go#L869)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this comment and the use of `time.UTC` should be in the caller, I think?
</details>
Actually removing `loc` from the signature all together as suggested above (since non-TZ timestamps don't care about it).

---

*[sql/testdata/datetime, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzUw36aDi4Q146vKFF:-KScPu4Z1c9snsVeChLV:b-9y6yfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/testdata/datetime#L75)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Does the date behavior here match postgres? That is, the date is parsed with the session TZ? Seems odd but all this stuff is odd.
</details>
Done (talked offline, and we're going to match pg's behavior: use session loc for casting `WITH TIME ZONE` timestamps only).

---

*[sql/testdata/datetime, line 419 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzVVR7qxHt7O0LGSIr:-KScG8Ztt2jiVPO4rnqJ:b7ixnus) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/testdata/datetime#L419)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> why WHERE FALSE? To make sure it doesn't error on "CET"?
</details>
yes, but I don't want a row to come back that changes depending whether tests are run in DST or not.

---

*[sql/testdata/datetime, line 558 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-KRzWLx2w6xGlgTDoRz0:-KScPsp7F4oN9vFJnfvN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95efd1e9d1a3a080bd74a99bb7f6b4b6ebc25de/sql/testdata/datetime#L558)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> wat
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 2 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9444#-:-KSeQ4bP-4Gdke5ICiKG:bnfp4nl)*

**Pull request merged**
