### PR TITLE
sql: remove type annotations from computed cols in information_schema

### LINKED ISSUE #50499: sql: information_schema.columns.generation_expression should round-trip
Postgres:
```
rafiss@127:postgres> create table computed_column_table (id int primary key, computed int generated always as (id + 42) stored);
CREATE TABLE

rafiss@127:postgres> SELECT column_name, data_type,  generation_expression FROM information_schema.columns WHERE ((table_schema = 'public') AND (table_name = 'computed_column_ta
 ble'));
+---------------+-------------+-------------------------+
| column_name   | data_type   | generation_expression   |
|---------------+-------------+-------------------------|
| id            | integer     | <null>                  |
| computed      | integer     | (id + 42)               |
+---------------+-------------+-------------------------+
```

CockroachDB:
```
root@:26257/defaultdb> create table computed_column_table (id int primary key, computed int as (id + 42) stored);
CREATE TABLE

root@:26257/defaultdb> SELECT column_name, data_type,  generation_expression FROM information_schema.columns WHERE ((table_schema = 'public') AND (table_name = 'computed_column_table'));
  column_name | data_type | generation_expression
--------------+-----------+------------------------
  id          | bigint    |
  computed    | bigint    | id + 42:::INT8
```

Note that CockroachDB includes the `:::INT8` type hint in the result for `generation_expression`. This causes issues for some ORMs (e.g. SQLAlchemy) that rely on this column for reflection and introspection, to make sure a computed column was created successfully.

Solution: `generation_expression` should not include type hints.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50499.

No release note since this was introduced this release.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Some tests are going to fail, so I'll update those once CI runs. I definitely ran sqlalchemy tests when running this serializable representations PR and didn't run into any problems...

**Comment by rafiss** [comment]
> I definitely ran sqlalchemy tests when running this serializable representations PR and didn't run into any problems...

Right now the computed column tests are disabled in the `sqlalchemy-cockroachdb` adapter. I just noticed this because I tried enabling them.

**Comment by rohany** [comment]
PTAL, updated to pass the tests.

**Review by rafiss — APPROVED** [review]
lgtm. thank you!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50502#-:-MAWxxZm2aRF4g-UQQEO:bwh2gg3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rohany** [comment]
bors r=rafiss

**Pull request merged**
