### PR TITLE
docs: update range lease acquisition description

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13179)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
What's missing here is a description of how raft agrees on one of two replicas owning the lease when two replicas issue a raft command to own the lease simultaneously

**Comment by bdarnell** [comment]
This change LGTM but this section needs an update for epoch leases. Your question is answered differently depending on the type of lease. 

For expiration-based leases, the lease is granted if its start time is greater than the expiration time of any (successful) lease request appearing earlier in the raft log. So when two replicas race to grab the lease, raft assigns each request a position in the log, and the one that appears in the earlier position wins (the second will be ignored because its start time is less than the just-granted lease's expiration).

For epoch leases, the requestor includes a copy of the lease that it believes to be valid at the time it requests the lease. If that lease is still valid when the lease request is processed, it is granted. If not (because another lease has been granted in the meantime), it is ignored. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13179#-:-KbT3UxnCWx-1lPVI_Cp:b2zc8y1)*

**Comment by vivekmenezes** [comment]
I've updated the section to talk about epoch based leases, with a note referencing expiration leases only for system ranges. PTAL

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13179#-:-KbWgMxQ0fuZ89AIF_N1:b5k7y1c)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13179#-:-KbahZ9qY2-iE5AK4jAw:bnfp4nl)*

**Pull request merged**
