### PR TITLE
server, ui: move problem range page from `/debug` to `/reports`

### PR DESCRIPTION
**Pull request by BramGruneir**
This adds a new gRPC service (also attached to the status server) but the endpoint is now _report. Since calls to report tend to be longer running than normal status queries, I felt this was an appropriate separation.

Also, move the first report in the ui to be under /report instead of /debug.

### CODE REVIEW

**Comment by BramGruneir** [comment]
I was also considering pulling the reports server out of the status server to be stand alone.  This would allow everything report related to exist in a single directory /server/report, including the protobuf, which would be in the new report namespace.  

Thoughts?

**Comment by BramGruneir** [comment]
So I tried pulling a report server out of the server directory, but it won't work due to needing to call back into status server.  However I did move it into it's own file, having it as part of the status server just seemed strange.

**Comment by mrtracy** [comment]
I'll let you make the call on this, but I don't think there's a point to adding another server object.  I think there's a very strong argument to be made that the "status" and "admin" servers should not even be separate; they were not separated due to any consideration, but rather due to a coincidence of development.

Both of these services, and the new one created in this PR, serve HTTP requests to the admin UI and have no current *or planned* difference in the access or initialization.

**Comment by BramGruneir** [comment]
I think there is a strong argument for combining or at least restructuring status and admin.  

That being said, what I want to do here is to demarcate this new endpoint in it's own proto file with it's own grpc service.  Since report queries will take significantly longer than status queries (as most call numerous status queries) and I wanted to reflect that.

Now this could easily be part of a single status server (see the first version of this that I posted), but doing so seemed to break how our server is structured as long as admin is its own entity.  I can try my hand a restructuring the whole thing, but I wouldn't want to do so until we've audited all the status and admin endpoints first, removing redundant ones, combining overlaps and renaming where appropriate.

So for now, I think this is clearer but I'd be down with cleaning this all up.

**Comment by mrtracy** [comment]
I wasn't suggesting that you merge "status" and "admin", I was suggesting that further separating "report" is exacerbating a problem rather than making anything clearer.  My central question is: to whom are you making it clear that a "_report" endpoint might take a long time to return?

If it's external users, then documentation is required along with the URL difference; the construction of objects in server code will provide no information to these users.

If it needs to be made clear to server-side developers somehow, then you must add some sort of explanation in a comment. There is currently no difference in initialization, no difference in access, and no difference in comments between these three services; to a backend developer, there is no apparent difference between a "report" and something returned from "status", or something returned from "admin"; all three services have calls that aggregate information from multiple queries.

**Comment by BramGruneir** [comment]
As to whom, to us, the developers.  We don't advertise or document these endpoints yet and until we do, we can change them anytime we want.

I was thinking about changing how long timeouts took in them, but so far in our small test clusters, this hasn't been an issue.  I'd like to see how long a 64 node cluster takes, especially if it spans across regions or clouds.

But I see your point, so what do you suggest in this case?  I'd like to keep the _report address, and I like it having it's own proto, which will match the devision on admin ui side.

I can:
1) keep it as is
2) move the report service into the status service struct
3) remove the report service entirely and just extend the status service (but maintain the _report endpoint)
4) do 3 and remove the _report endpoint as well, just add new status endpoints
5) anything else you can think of?

**Comment by BramGruneir** [comment]
Ok, after offline discussion, I'm going to go with option 4, and just remove the report service entirely and merge the endpoint back into status.  So this PR is going to be just a moving around of the page in the ui.

**Comment by BramGruneir** [comment]
Ok, this should be ready to go.  PTAL

**Comment by mrtracy** [comment]
LGTM

**Pull request merged**
