### PR TITLE
sql: set constraint name in pg error for FK violations

### LINKED ISSUE #36494: Add constraint name to foreign key/check constraint errors
**Is your feature request related to a problem? Please describe.**

I'm running into an issue where [Ecto](https://github.com/elixir-ecto/ecto) isn't able to nicely handle cockroach's constraint errors (`foreign_key_violation`, `unique_violation`, `exclusion_violation` and `check_violation` ) because cockroach's constraint errors do not include a `constraint_name` error field as part of the error response. This behavior was added in postgres 9.3 under a feature titled ["Provide clients with constraint violation details as separate fields"](https://www.postgresql.org/docs/9.3/release-9-3.html#AEN119393).

**Describe the solution you'd like**

It would be great if cockroach could add the failing constraint name to these errors, so they can be used by higher level application code. The field id should be `n` as described in [53.8. Error and Notice Message Fields](https://www.postgresql.org/docs/current/protocol-error-fields.html) of the postgres docs. This field is also know as `PG_DIAG_CONSTRAINT_NAME` in the [`PQresultErrorField` docs](https://www.postgresql.org/docs/9.3/libpq-exec.html#LIBPQ-PQRESULTERRORFIELD).

It would also be nice if the error message text could match that of postgres, but I understand if there's reasons that it's been changed.

**Additional context**
Here are the differences between the postgres and cockroach foreign key error responses, as parsed by [postgrex](https://github.com/elixir-ecto/postgrex).

```elixir
# Postgres error fields (as parsed by postgrex)
%Postgrex.Error{
  connection_id: 70007,
  message: nil,
  postgres: %{
    code: :foreign_key_violation,
    constraint: "users_account_id_fkey",
    detail: "Key (account_id)=(q) is not present in table \"accounts\".",
    file: "ri_triggers.c",
    line: "2776",
    message: "insert or update on table \"users\" violates foreign key constraint \"users_account_id_fkey\"",
    pg_code: "23503",
    routine: "ri_ReportViolation",
    schema: "public",
    severity: "ERROR",
    table: "users",
    unknown: "ERROR"
  },
  query: nil
}

# Cockroach error fields (as parsed by postgresx)
%Postgrex.Error{
  connection_id: nil,
  message: nil,
  postgres: %{
    code: :foreign_key_violation,
    file: "sql/sqlbase/fk.go",
    line: "359",
    message: "foreign key violation: value ['k'] not found in accounts@primary [id] (txn=8c87c634-cf34-4e69-8bf3-ea6758e65a82)",
    pg_code: "23503",
    routine: "runCheck",
    severity: "ERROR"
  },
  query: nil
}
```

Here are the differences in the error messages between cockroach and postgres:
* Postgres: `insert or update on table "users" violates foreign key constraint "users_account_id_fkey"`
* Cockroach: `foreign key violation: value ['k'] not found in accounts@primary [id] (txn=8c87c634-cf34-4e69-8bf3-ea6758e65a82)`

Issue tracking ecto compatibility: #33441

Psycopg2 issue where they were working to support additional `PG_DIAG_*_NAME` fields like `PG_DIAG_CONSTRAINT_NAME`: https://github.com/psycopg/psycopg2/issues/149

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds infrastructure to set the "constraint name" field of
errors on pgwire and uses it to populate the constraint name for
foreign key violation errors.

Fixes #36494.

Release note (sql change): foreign key violation errors now fill in
the "constraint name" error message field.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/pgwire/pgerror/constraint_name.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MH4MahK65OvBHRdBJiW:-MH4MahL43D41TKYL4hd:bjt0qo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b9bc5b6b9e07fae918ab9bdfbc5a8a8ec59798/pkg/sql/pgwire/pgerror/constraint_name.go#L52)):*
> ```Go
> func (w *withConstraintName) Unwrap() error { return w.cause }
> func (w *withConstraintName) SafeDetails() []string {
> 	// The constraint name is considered PII.
> ```

I'm not sure about this, are schema elements considered PII or "safe"?
___
*[pkg/sql/pgwire/pgerror/constraint_name.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MH4MeEe3OtgmXyXPJMB:-MH4MeEe3OtgmXyXPJMC:b3rdbca) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b9bc5b6b9e07fae918ab9bdfbc5a8a8ec59798/pkg/sql/pgwire/pgerror/constraint_name.go#L75)):*
> ```Go
> 	var constraint string
> 	if len(details) > 0 {
> 		constraint = details[0]
> ```

A little unsure about this, where do `details` come from normally? Do I need a custom encoder if I can't return it through SafeDetails? (how can I test this?)

**Comment by RaduBerinde** [comment]
Friendly ping (I intend to try to backport this to 20.2)

**Review by knz — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/pgwire/pgerror/constraint_name.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MH4MahK65OvBHRdBJiW:-MHKt-Ib2tp53UEwzFWG:b-9q6rlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b9bc5b6b9e07fae918ab9bdfbc5a8a8ec59798/pkg/sql/pgwire/pgerror/constraint_name.go#L52)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not sure about this, are schema elements considered PII or "safe"?
</blockquote></details>

not safe
___
*[pkg/sql/pgwire/pgerror/constraint_name.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MH4MeEe3OtgmXyXPJMB:-MHKtGZFEUG6_tIbBQ58:b-oo5zmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b9bc5b6b9e07fae918ab9bdfbc5a8a8ec59798/pkg/sql/pgwire/pgerror/constraint_name.go#L75)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

A little unsure about this, where do `details` come from normally? Do I need a custom encoder if I can't return it through SafeDetails? (how can I test this?)
</blockquote></details>

There's an `errorspb.StringPayload` you can use. Look how `hintdetail.withDetail` is implemented.

(how to test: Encode then Decode and see the payload is still there)
___
*[pkg/sql/pgwire/testdata/pgtest/errors, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MHKtacdBPg8tBcmXas0:-MHKtace5TnIRIVyD2oC:b-gdunlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742c0290307ead34d72e77a79ed4de18ac1e9fa/pkg/sql/pgwire/testdata/pgtest/errors#L43)):*
> ```
> ReadyForQuery
> ----
> {"Type":"ErrorResponse","Code":"23503","ConstraintName":"fk_p_ref_parent"}
> ```

Can you 
1) add a test with a constraint name containing special characters, so it'd need quoting in SQL
2) verify (e.g. using this pgtest) what postgres does with it in the error payload: is it quoted?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/pgwire/pgerror/constraint_name.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MH4MeEe3OtgmXyXPJMB:-MHN31HI3vJJ92flA2nu:b-dtkds3) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b9bc5b6b9e07fae918ab9bdfbc5a8a8ec59798/pkg/sql/pgwire/pgerror/constraint_name.go#L75)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

There's an `errorspb.StringPayload` you can use. Look how `hintdetail.withDetail` is implemented.

(how to test: Encode then Decode and see the payload is still there)
</blockquote></details>

Done, thanks!
___
*[pkg/sql/pgwire/testdata/pgtest/errors, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MHKtacdBPg8tBcmXas0:-MHN5wGU7KtEDGGj9AK0:b-upgmad) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742c0290307ead34d72e77a79ed4de18ac1e9fa/pkg/sql/pgwire/testdata/pgtest/errors#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you 
1) add a test with a constraint name containing special characters, so it'd need quoting in SQL
2) verify (e.g. using this pgtest) what postgres does with it in the error payload: is it quoted?
</blockquote></details>

Added a test (using a space, did you have other special characters in mind?)

Why would it be quoted on the wire? I can't figure out how to run pgtest against a local postgres and I couldn't find any instructions.

**Review by knz — APPROVED** [review]
:lgtm:

(maybe you can do the pg test by hand too. `\errverbose` in psql will reveal the details of the last error object)

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-:-MHNakYo9HK_fhTndRos:brx5dqx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/pgwire/testdata/pgtest/errors, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MHKtacdBPg8tBcmXas0:-MHNaSY_70ikD5DExTVK:b-no7l7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742c0290307ead34d72e77a79ed4de18ac1e9fa/pkg/sql/pgwire/testdata/pgtest/errors#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Added a test (using a space, did you have other special characters in mind?)

Why would it be quoted on the wire? I can't figure out how to run pgtest against a local postgres and I couldn't find any instructions.
</blockquote></details>

`make test ... TESTFLAGS='-addr localhost:5432'`

optionally `-user`

you'll need a testdb with permission for the `-user`

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54313)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/pgwire/testdata/pgtest/errors, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-MHKtacdBPg8tBcmXas0:-MHNfe421NggBFQebkU2:bhapd44) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742c0290307ead34d72e77a79ed4de18ac1e9fa/pkg/sql/pgwire/testdata/pgtest/errors#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`make test ... TESTFLAGS='-addr localhost:5432'`

optionally `-user`

you'll need a testdb with permission for the `-user`
</blockquote></details>

I did try that, I get `unexpected: &pgproto3.AuthenticationMD5Password{..` (even after clearing out the password for the user)

**Review by RaduBerinde — COMMENTED** [review]
Oh, thanks, I'll do that!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-:-MHNfjxK4HyMl5lfPtRQ:b-9agzc8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by RaduBerinde — COMMENTED** [review]
Output of `\errverbose`:
```
ERROR:  23503: insert or update on table "child" violates foreign key constraint "foo bar"
DETAIL:  Key (p)=(1) is not present in table "parent".
SCHEMA NAME:  public
TABLE NAME:  child
CONSTRAINT NAME:  foo bar
LOCATION:  ri_ReportViolation, ri_triggers.c:3266
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54313#-:-MHNg2zXEpLa6t-wCQOk:b3d115k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
nb I approved already, so the rest was up to you

**Pull request merged**
