### PR TITLE
scripts/release-notes.py: derive author aliases from AUTHORS

### PR DESCRIPTION
**Pull request by knz**
Previously, the release-notes script contained an explicit list of
contributors to the repo with their name aliases, to disambiguate
entries in the git log while constructing the release notes report.

The explicit list was problematic in numerous ways, foremost because
it was often out of date and incomplete, and also because it couldn't
distinguish different folk with the same name but different addresses.

Luckily, Git has a standard solution for this problem, called a
"mailmap" file. The format of this file is standardized and documented
in the man page git-check-mailmap(1). To simplify, this file format
has one line per _person_, and each line can contain multiple
name/mail combinations for that person.

Meanwhile, the CockroachDB repository also maintains a file `AUTHORS`
at the top of the source tree. This also contains a list of
contributors with names and e-mails, although for far this file was
not maintained to conform exactly to Git's mailmap format.

This commit bridges the two things as follows:

- it updates the `AUTHORS` file to conform to the mailmap format.
  This removes duplicate entries, and spells out Git commit/author
  aliases alongside the primary name of a person.
- it simplifies the release-notes script to use AUTHORS
  as its input database.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
cc @jseldess

**Comment by knz** [comment]
@chrisseto if you could review the code change that would be swell.

**Review by chrisseto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42339)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[scripts/release-notes.py, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRXOOI9QyC8JBekYUD:-LtRXOOI9QyC8JBekYUE:b-ymdmee) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L51)):*
> ```Python
> mmare = re.compile('(?P<alias>[^<]*)<(?P<addr>[^>]*)>')
> crdb_folk = set()
> class P:
> ```

A bit more descriptive name would be nice here, maybe `Person`?
___
*[scripts/release-notes.py, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRXc_O6TrnX3ai1jtl:-LtRXc_O6TrnX3ai1jtm:b-l1ml4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L68)):*
> ```Python
> def define_person(name, addr):
>         p = P(name, addr)
>         canon = (name, addr)
> ```

You could use the person object as the key if you [override __hash__ and __eq__](https://stackoverflow.com/questions/4901815/object-of-custom-type-as-dictionary-key)
___
*[scripts/release-notes.py, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtR_IWq5Ftmm2B3YCOX:-LtR_IWq5Ftmm2B3YCOY:bdd7lgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L70)):*
> ```Python
>         canon = (name, addr)
>         if canon in mmap_bycanon:
>             print('warning: duplicate person %r, ignoring', canon)
> ```

Should the be going to stderr? `file=sys.stderr`

Python's print function doesn't do any built in formatting. Instead call str.format
```python
print('warning: duplicate person %r, ignoring'.format(canon))
```
___
*[scripts/release-notes.py, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtR_muRA0nmkvXvu3Y8:-LtR_muRA0nmkvXvu3Y9:bothrc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L71)):*
> ```Python
>         if canon in mmap_bycanon:
>             print('warning: duplicate person %r, ignoring', canon)
>             return None
> ```

This case doesn't appear likely to happen but it looks like the `None` could trickle through `lookup_person` and cause some weird errors?

Would it be better to throw an exception here and request that AUTHORS be checked for validity?
___
*[scripts/release-notes.py, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRYJka-E9kHiD5dGss:-LtRYJkb4tvM-73io_-t:b70hcxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L73)):*

> ```
>         byaddr = mmap_byaddr.get(addr, [])
>         byaddr.append(p)
>         mmap_byaddr[addr] = byaddr
> ```

`mmap_byaddr.setdefault(addr, []).append(p)` is functionally equivalent and a bit more readable IMO
___
*[scripts/release-notes.py, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRaHSD7DnYojKofV7s:-LtRaHSD7DnYojKofV7t:b-sqki4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L81)):*
> ```Python
>         return p
> 
> if not os.path.exists('AUTHORS'):
> ```

AUTHORS could be targeted directly by making use of python's [__file__](https://stackoverflow.com/questions/9271464/what-does-the-file-variable-mean-do) variable
___
*[scripts/release-notes.py, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRbCiGBr417x2Ybewk:-LtRbCiGBr417x2Ybewl:b5nm76s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L83)):*
> ```Python
> if not os.path.exists('AUTHORS'):
>     print('warning: AUTHORS missing in current directory.', file=sys.stderr)
>     print('Maybe use "cd" to navigate to the working tree root.', file=sys.stderr)
> ```

Should the script exit in this case?
___
*[scripts/release-notes.py, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRafKL9_OTQxJsTQad:-LtRafKL9_OTQxJsTQae:bakdfdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L95)):*
> ```Python
>             if p is None:
>                 continue
>             p.crdb = '@cockroachlabs.com' in line
> ```

Remove this line, it is already handled in `P`'s constructor 
___
*[scripts/release-notes.py, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRWgB06qKZEIuAr0JH:-LtRWgB06qKZEIuAr0JI:b-x7fnec) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L97)):*
> ```Python
>             p.crdb = '@cockroachlabs.com' in line
>             if p.crdb:
>                 crdb_folk.add(p)
> ```

Looks like `crdb_folk.add(p)` gets called twice.
Once here and once in the P constructor.

Technically it doesn't matter as crdb_folk is a set but this could be confusing for the next author.
I think the `crdb_folk.add(self)` in `P.__init__` should be removed as it is less "side effect-y"
___
*[scripts/release-notes.py, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRbWOM3nXk4YHxMKZr:-LtRbWOM3nXk4YHxMKZs:btl452x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L99)):*
> ```Python
>                 crdb_folk.add(p)
>             aliases = m.group('aliases')
>             aliases = mmare.findall(aliases)
> ```

`aliases = m.group(m.group('aliases'))` might be a bit more explicit.
___
*[scripts/release-notes.py, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRbmrP-DzCk1hlFkgv:-LtRbmrP-DzCk1hlFkgw:bpi0uio) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L102)):*
> ```Python
>             for alias, addr in aliases:
>                 name = alias.strip()
>                 byaddr = mmap_byaddr.get(addr, [])
> ```

Can this block instead delegate to `define_person`?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42339)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @jordanlewis)

___
*[scripts/release-notes.py, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRXOOI9QyC8JBekYUD:-LtUX3K17yQZdAvscz52:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L51)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

A bit more descriptive name would be nice here, maybe `Person`?
</blockquote></details>

Done.
___
*[scripts/release-notes.py, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRXc_O6TrnX3ai1jtl:-LtUkFGV4u3hh3EooNkP:bxv3igs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L68)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

You could use the person object as the key if you [override __hash__ and __eq__](https://stackoverflow.com/questions/4901815/object-of-custom-type-as-dictionary-key)
</blockquote></details>

Well except that I want to be using this dict when I don't have a person object yet.
___
*[scripts/release-notes.py, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtR_IWq5Ftmm2B3YCOX:-LtUfQL-CxqamqokBI8J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L70)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Should the be going to stderr? `file=sys.stderr`

Python's print function doesn't do any built in formatting. Instead call str.format
```python
print('warning: duplicate person %r, ignoring'.format(canon))
```
</blockquote></details>

Done.
___
*[scripts/release-notes.py, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtR_muRA0nmkvXvu3Y8:-LtUfX9W3Et0fBiWekDL:b86hl89) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L71)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

This case doesn't appear likely to happen but it looks like the `None` could trickle through `lookup_person` and cause some weird errors?

Would it be better to throw an exception here and request that AUTHORS be checked for validity?
</blockquote></details>

Good catch. It's ok to return the existing entry. Done.
___
*[scripts/release-notes.py, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRYJka-E9kHiD5dGss:-LtUf_QdDq8PiP2i1iGz:bk55nfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L73)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>


> ```
>         byaddr = mmap_byaddr.get(addr, [])
>         byaddr.append(p)
>         mmap_byaddr[addr] = byaddr
> ```

`mmap_byaddr.setdefault(addr, []).append(p)` is functionally equivalent and a bit more readable IMO
</blockquote></details>

Nice TIL. Done.
___
*[scripts/release-notes.py, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRaHSD7DnYojKofV7s:-LtUfi4C0KyW5hkrKofb:be0n3cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L81)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

AUTHORS could be targeted directly by making use of python's [__file__](https://stackoverflow.com/questions/9271464/what-does-the-file-variable-mean-do) variable
</blockquote></details>

This was intentional. Added a comment to clarify.
___
*[scripts/release-notes.py, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRbCiGBr417x2Ybewk:-LtUfsqaCiWYgTBceVCn:bpxaoo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L83)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Should the script exit in this case?
</blockquote></details>

Nah it's valid to proceed without aliases.
___
*[scripts/release-notes.py, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRafKL9_OTQxJsTQad:-LtUg19PA_DAmGNxnt0W:b-tmb3if) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L95)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Remove this line, it is already handled in `P`'s constructor 
</blockquote></details>

Not quite: the constructor did not catch the crdb address in an alias.

But I have re-organized the code to simplify.
___
*[scripts/release-notes.py, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRWgB06qKZEIuAr0JH:-LtUk6Ya-kDvxdISV1OE:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L97)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Looks like `crdb_folk.add(p)` gets called twice.
Once here and once in the P constructor.

Technically it doesn't matter as crdb_folk is a set but this could be confusing for the next author.
I think the `crdb_folk.add(self)` in `P.__init__` should be removed as it is less "side effect-y"


</blockquote></details>

Good idea. Done.
___
*[scripts/release-notes.py, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRbWOM3nXk4YHxMKZr:-LtUkCN1CSeQQQQlLAi3:b-oh3ezv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L99)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

`aliases = m.group(m.group('aliases'))` might be a bit more explicit.
</blockquote></details>

I don't understand?
___
*[scripts/release-notes.py, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42339#-LtRbmrP-DzCk1hlFkgv:-LtUkDrE79-gO3pgC7dh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a242b72b443cb414739de17861cab67dd7c6444e/scripts/release-notes.py#L102)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Can this block instead delegate to `define_person`?
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYRs!

bors r+

**Pull request merged**
