### PR TITLE
sql: correct return type for timestamptz - interval

### PR DESCRIPTION
**Pull request by madelynnblue**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6540)

### CODE REVIEW

**Comment by tamird** [comment]
test plz

**Comment by nvanbenschoten** [comment]
LGTM

**Comment by mjibson** [comment]
Test added.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6540#-:-KH1oIcZL-ZKXQXvPqmP:-372168649)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6540#-:-KH1oU9ka1zxOn30dDyv:1417088721)*

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6540)*

**Pull request merged**
