### PR TITLE
opt: exploration rule for streaming aggregations

### LINKED ISSUE #30000: opt: use GroupBy input ordering
Ran into this debugging another issue. We use an `orderedAggregator` when there is an ordering on the input columns to output each group when we're done with it to avoid using memory. This works fine with the optimizer off but when the optimizer is turned on we seem to plan a `hashAggregator` because we don't get the information that there is an ordering on the input columns.

```
root@:26257/defaultdb> SHOW create table accounts;
  table_name |                   create_statement
+------------+------------------------------------------------------+
  accounts   | CREATE TABLE accounts (
             |     custid INT8 NOT NULL,
             |     CONSTRAINT pk_accounts PRIMARY KEY (custid ASC),
             |     FAMILY "primary" (custid)
             | )
(1 row)

Time: 7.928417ms

root@:26257/defaultdb> SET optimizer=off;
SET

Time: 448.428µs

root@:26257/defaultdb> EXPLAIN SELECT custid, count(1) FROM accounts group by custid;
       tree      |    field    |     description
+----------------+-------------+----------------------+
  group          |             |
   │             | aggregate 0 | custid
   │             | aggregate 1 | count(1)
   │             | group by    | @1
   │             | ordered     | @1
   └── render    |             |
        └── scan |             |
                 | table       | accounts@pk_accounts
                 | spans       | ALL
(9 rows)

Time: 1.226927ms

root@:26257/defaultdb> SET optimizer=on;
SET

Time: 486.415µs

root@:26257/defaultdb> EXPLAIN SELECT custid, count(1) FROM accounts group by custid;
       tree      |    field    |     description
+----------------+-------------+----------------------+
  group          |             |
   │             | aggregate 0 | custid
   │             | aggregate 1 | count(column2)
   │             | group by    | @2
   └── render    |             |
        └── scan |             |
                 | table       | accounts@pk_accounts
                 | spans       | ALL
(8 rows)

Time: 1.567282ms
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change implements an exploration rule that creates versions of a
GroupBy or DistinctOn operator based on interesting orderings.

In addition, we enact a workaround for #31882 - a problem caused by
using optional non-constant columns in orderings: we no longer set the
grouping columns as optional. These two changes are related in that
this workaround would reduce even further the cases where we do a
streaming aggregation; the exploration rule compensates for this in
most cases.

Fixes #30000.
Informs #31882.

Release note (bug fix): Fixed a bug that can cause incorrect results
or an "incorrectly ordered stream" error with queries that use GROUP
BY or DISTINCT ON. Improved performance of some aggregations (by
utilizing streaming aggregation in more cases).

I plan to backport this on 2.1, so the more eyes on it the better (and let me know if you have ideas for more testcases).

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Gentle ping :)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 1129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQGGPx38nifV-QP2lia:-LQGGPx4EZc4R-wKNgl6:b-4d64b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/norm/testdata/rules/decorrelate#L1129)):*
> ```
>  ├── columns: k:1(int!null) i:2(int) f:3(float) s:4(string) j:5(jsonb)
>  ├── grouping columns: k:1(int!null)
>  ├── internal-ordering: +1 opt(2)
> ```

Is it really better to do an extra sort in order to do a streaming group-by?
___
*[pkg/sql/opt/ops/relational.opt, line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQGGyVy6D3_CG84mynQ:-LQGGyVy6D3_CG84mynR:b-xyobmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/ops/relational.opt#L374)):*
> ```
> 
> 	# Ordering specifies the order required of the input. This order can intermix
>   # grouping and non-grouping columns, serving a dual-purpose:
> ```

NIT: Use tabs instead of spaces for these new lines.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 1129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQGGPx38nifV-QP2lia:-LQH-XNeC-jewQB9MPxh:bn9vjml) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/norm/testdata/rules/decorrelate#L1129)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Is it really better to do an extra sort in order to do a streaming group-by?
</blockquote></details>

Doesn't seem right.. The rowcount is probably very small (under 1) and for those the per-row sort cost is much less than the aggregation cost. I'll see if I can find a way to tweak it without disrupting things.

**Review by rytaft — APPROVED** [review]
:lgtm: Lots of subtle/tricky issues here, but as far as I can tell you're handling them - nicely done.

> Reviewed 2 of 2 files at r1, 32 of 32 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-:-LQHNwVjB-1FPEx_S-md:b-bcnd8j)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 1071 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQHJSzM6bne0Ml-bdAy:-LQHJSzM6bne0Ml-bdAz:b-13s0u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/xform/testdata/physprops/ordering#L1071)):*
> ```
> SELECT DISTINCT ON (a) a, c FROM abc ORDER BY a, c DESC, b
> ----
> sort
> ```

This one seems suboptimal

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 1071 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQHJSzM6bne0Ml-bdAy:-LQInZOnA1gTVTutbDjD:b7yyz1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/xform/testdata/physprops/ordering#L1071)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This one seems suboptimal
</blockquote></details>

This is a consequence of the workaround (in this case the new exploration rule doesn't help because we still need sorting of the input).

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 1071 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQHJSzM6bne0Ml-bdAy:-LQJR3_A-sajQbRw-NxU:bptyld5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/xform/testdata/physprops/ordering#L1071)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a consequence of the workaround (in this case the new exploration rule doesn't help because we still need sorting of the input).
</blockquote></details>

I think I understand... so making this case choose internal ordering `+1, -3, +2` will be saved for a future PR?

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 1071 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQHJSzM6bne0Ml-bdAy:-LQJTyv54Kec4kwjK7h6:bgk3t1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/xform/testdata/physprops/ordering#L1071)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think I understand... so making this case choose internal ordering `+1, -3, +2` will be saved for a future PR? 
</blockquote></details>

Sorry, never mind. I just read through #31882. So this will be the fix for 2.1.x, but not the long-term solution.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 1129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQGGPx38nifV-QP2lia:-LQKWHVX3RRkO8WyQxD_:bv7ke92) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8034b0e0b17fe6b92d10218b0daa618aadb5fde/pkg/sql/opt/norm/testdata/rules/decorrelate#L1129)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Doesn't seem right.. The rowcount is probably very small (under 1) and for those the per-row sort cost is much less than the aggregation cost. I'll see if I can find a way to tweak it without disrupting things.
</blockquote></details>

PTAL at the coster changes. I changed the groupby costing to add some extra cost for non-streaming, and I tweaked the cost for sort a bit.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 36 of 36 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-:-LQL0W2C-ac9cNNWXTyC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/coster.go, line 185 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQOxhqQBz5CHaInuQGR:-LQOxhqQBz5CHaInuQGS:b1flzsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c40c7d920c6760e931c535484efeebc98a5914/pkg/sql/opt/xform/coster.go#L185)):*
> ```Go
> 	cost := memo.Cost(rowCount) * cpuCostFactor
> 	factor := memo.Cost(1)
> 	if rowCount > 1 {
> ```

Maybe add a comment explaining the formula. It appears that the problem with the previous formula is that it failed to produce different relative costs when rowCount < 1.
___
*[pkg/sql/opt/xform/coster.go, line 344 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQOyKJwB2EC86j3_CIh:-LQOyKJwB2EC86j3_CIi:b69n33o) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c40c7d920c6760e931c535484efeebc98a5914/pkg/sql/opt/xform/coster.go#L344)):*
> ```Go
> 	// input.
> 	hashCost := memo.Cost(inputRowCount) * cpuCostFactor
> 	if !private.GroupingCols.SubsetOf(private.Ordering.Optional) {
> ```

This test condition (`private.GroupingCols.SubsetOf(private.Ordering.Optional)`) should be a nicely-named and commented method on the private, because it's hard to understand what it's doing.
___
*[pkg/sql/opt/xform/coster.go, line 348 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQOzNqf1xT8Yvhmy2cS:-LQOzNqf1xT8Yvhmy2cT:btp7z1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c40c7d920c6760e931c535484efeebc98a5914/pkg/sql/opt/xform/coster.go#L348)):*
> ```Go
> 		for i := range private.Ordering.Columns {
> 			unorderedCols.DifferenceWith(private.Ordering.Columns[i].Group)
> 		}
> ```

Same goes with this calculation of "unorderedCols" - it should be a helper method, because it's related to the mechanics of the grouping operator, and not really to costing.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/coster.go, line 185 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQOxhqQBz5CHaInuQGR:-LQPPCcLB-FuwylcjEnm:b697m0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c40c7d920c6760e931c535484efeebc98a5914/pkg/sql/opt/xform/coster.go#L185)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Maybe add a comment explaining the formula. It appears that the problem with the previous formula is that it failed to produce different relative costs when rowCount < 1.
</blockquote></details>

Done.  I also removed `memo.Cost(rowCount) * cpuCostFactor` which was accidentally left over.
___
*[pkg/sql/opt/xform/coster.go, line 344 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQOyKJwB2EC86j3_CIh:-LQPPNCE-RnxlRZ9riO4:b-4jz1o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c40c7d920c6760e931c535484efeebc98a5914/pkg/sql/opt/xform/coster.go#L344)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This test condition (`private.GroupingCols.SubsetOf(private.Ordering.Optional)`) should be a nicely-named and commented method on the private, because it's hard to understand what it's doing.
</blockquote></details>

I added a `StreamingAggCols` method which is now used both by the coster and the execbuilder. What I was doing here wasn't enough because I wasn't looking at the required ordering. We are now looking at both and that results in better plans in some cases (sort before instead of after grouping).
___
*[pkg/sql/opt/xform/coster.go, line 348 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-LQOzNqf1xT8Yvhmy2cS:-LQPPS2M2rODa3VKgGSh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c40c7d920c6760e931c535484efeebc98a5914/pkg/sql/opt/xform/coster.go#L348)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Same goes with this calculation of "unorderedCols" - it should be a helper method, because it's related to the mechanics of the grouping operator, and not really to costing.
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-:-LQjN7Ot0qyO4PkVvJ15:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by andy-kimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31976#-:-LQjNCTl6VeVdDFh4VHh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
