### PR TITLE
sql/pgwire: support for decoding JSON[] OID by aliasing to JSONB[] OID

### LINKED ISSUE #90839: sql/pgwire: need support for decoding `JSON[]` OID by aliasing to `JSONB[]` OID [unknown oid type: 199]
**Describe the problem**

Since the fix in https://github.com/cockroachdb/cockroach/issues/88355 , CockroachDB recognises oid `114` as `JSON`, and internally aliases it to `JSONB` (with the oid `3802`).

Would it be possible to make the same fix with JSON arrays? Ideally it would treat oid `199` (`JSON[]`) as oid `3807` (`JSONB[]`)?

If we send the same queries with `3807` instead everything works.

**Expected behavior**
Ideally, `JSON[]` input with oid 199 would be accepted in the wire format and treated as `JSONB[]` internally.

**Additional context**
Discovered whilst implementing subscriptions for Hasura Graphql Engine

Expected `oid` values found in here: https://github.com/postgres/postgres/blob/5543677ec90a15c73dab5ed4f0902b3b920f0b87/src/include/catalog/pg_type.dat#L443

Jira issue: CRDB-20967
Epic CRDB-11916

### PR DESCRIPTION
**Pull request by ZhouXing19**
Previously, with the parameter type oid (199) for JSON[], the pgwire parse message
will fail to be executed with a `unknown oid type: 199`. We now aliasing it
to the one for `JSONB[]`.

This PR also includes a test revealing https://github.com/cockroachdb/cockroach/issues/95434.

This commit follows the changes in https://github.com/cockroachdb/cockroach/pull/88379.

fixes #90839

Release note (sql change): The pgwire protocol implementation can
now accept arguments of the JSON[] type (oid=199). Previously, it could
only accept JSONB[] (oid=3804). Internally, JSON[] and JSONB[] values are
still identical, so this change only affects how the values are received
over the wire protocol.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`-- commits` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL3-A-2D5a04tC5hL5g):*
could you make this a bit more clear for a user to understand? "Fixed the formatting of JSON values inside of a SQL array so they don't have improper quoting."
___
*[`pkg/sql/pgwire/pgwirebase/encoding.go` line 547 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL324ftDpQL2N28UYu5:-NL324ftDpQL2N28UYu6:bvl1w5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a208ef6d8bca74234f2f661bea4acdb06378a84e/pkg/sql/pgwire/pgwirebase/encoding.go#L547)):*
> ```Go
> 			return &tree.DTSVector{TSVector: ret}, nil
> 		}
> 		if typ.Family() == types.ArrayFamily {
> ```

hm, what was wrong with this case for json arrays?
___
*[`pkg/sql/pgwire/pgwirebase/encoding.go` line 859 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL32Jp0CWH7qR9Alhsy:-NL32Jp0CWH7qR9Alhsz:b-spvgf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a208ef6d8bca74234f2f661bea4acdb06378a84e/pkg/sql/pgwire/pgwirebase/encoding.go#L859)):*
> ```Go
> 		default:
> 			if typ.Family() == types.ArrayFamily {
> 				return decodeBinaryArray(ctx, evalCtx, typ.ArrayContents(), b, code)
> ```

we should make sure this works correctly for `oid.T__json`. i think we need to make sure `typ.ArrayContents()` returns an OID of 114 and not 3802, so that the `case oid.T_json` is used above.
___
*[`pkg/sql/types/types.go` line 655 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL33Jvj5lmok8zHCUxa:-NL33Jvj5lmok8zHCUxb:b-f5hmdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a208ef6d8bca74234f2f661bea4acdb06378a84e/pkg/sql/types/types.go#L655)):*
> ```Go
> 	// JSONArray is the type of an array value having JSON-typed elements.
> 	JSONArray = &T{InternalType: InternalType{
> 		Family: ArrayFamily, ArrayContents: Jsonb, Oid: oid.T__jsonb, Locale: &emptyLocale}}
> ```

i'm wondering if we need to have two types here, like
```
	// JSONBArray is the type of an array value having JSONB-typed elements.
	JSONBArray = &T{InternalType: InternalType{
		Family: ArrayFamily, ArrayContents: Jsonb, Oid: oid.T__jsonb, Locale: &emptyLocale}}

	// JSONArray is the type of an array value having JSON-typed elements.
	JSONArray = &T{InternalType: InternalType{
		Family: ArrayFamily, ArrayContents: Json, Oid: oid.T__json, Locale: &emptyLocale}}
```

(all the current usages should use JSONBArray, but the new ones you are adding should use JSONArray)

see my comment on DecodeDatum
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL30AKg-T1n6IlO-eXJ:-NL30AKg-T1n6IlO-eXK:b-yd3yvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/71bb69953e99b8a4769b6e414a352ad8ebaf8132/pkg/sql/logictest/testdata/logic_test/json#L212)):*
> ```
> SELECT array_agg(bar ORDER BY pk) FROM foo
> ----
> {"'{\"a\": \"b\"}'","'[1, 2, 3]'","\"hello\"",1.000,true,false,NULL,"'{\"x\": [1, 2, 3]}'","'{\"x\": {\"y\": \"z\"}}'"}
> ```

nice, thanks for fixing this too!
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL3-Wz5-AX9POAZpUte:-NL3-Wz5-AX9POAZpUtf:b-5uwcx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedce90eb2666e9d3cf99cdedbb0f9efe4fe22d6/pkg/sql/pgwire/testdata/pgtest/json_array#L1)):*
> ```
> send
> ```

this should be `send crdb_only` or else make sure to add a `until noncrdb_only` below this.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL317n17NiErWQcTL-l:-NL317n17NiErWQcTL-m:b-yrf51w) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedce90eb2666e9d3cf99cdedbb0f9efe4fe22d6/pkg/sql/pgwire/testdata/pgtest/json_array#L48)):*
> ```
> Parse {"Query": "SELECT $1::JSON[]", "ParameterOIDs": [199]}
> Describe {"ObjectType": "S"}
> Bind {"ParameterFormatCodes": [0], "Parameters": [{"text":"{\"{\\\"a\\\":{}}\"}"}]}
> ```

we should have some tests where `ParameterFormatCodes` is `[1]` so that the binary input format is tested

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL3-A-2D5a04tC5hL5g):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you make this a bit more clear for a user to understand? "Fixed the formatting of JSON values inside of a SQL array so they don't have improper quoting."
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/pgwirebase/encoding.go` line 547 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL324ftDpQL2N28UYu5:-NL4jq4o5Z4kKnKDmr-m:bt5c1cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a208ef6d8bca74234f2f661bea4acdb06378a84e/pkg/sql/pgwire/pgwirebase/encoding.go#L547)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, what was wrong with this case for json arrays?
</blockquote></details>

It's because if the given string is of the wrong form of an array or json element (e.g. `""`), this part won't return an error, and the server will still send a `BindComplete` message to the client, as the actual parsing for an array happens after this. 
This is inconsistent with PG -- we should not give `BindComplete` in this case. 

The newly added `case oid.T__json, oid.T__jsonb`part ensures the string can be parsed to an array of json. If not, we returns an error right away.
___
*[`pkg/sql/pgwire/pgwirebase/encoding.go` line 859 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL32Jp0CWH7qR9Alhsy:-NL7P0sn2De5pl_Ka_Qu:b9soeei) ([raw file](https://github.com/cockroachdb/cockroach/blob/a208ef6d8bca74234f2f661bea4acdb06378a84e/pkg/sql/pgwire/pgwirebase/encoding.go#L859)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should make sure this works correctly for `oid.T__json`. i think we need to make sure `typ.ArrayContents()` returns an OID of 114 and not 3802, so that the `case oid.T_json` is used above.
</blockquote></details>

Yeah I've checked with the debugger that `typ.ArrayContents()` returns with `oid T_json`.
___
*[`pkg/sql/types/types.go` line 655 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL33Jvj5lmok8zHCUxa:-NL7PCD_E_Qs7fLFA7Q5:bdtxzlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a208ef6d8bca74234f2f661bea4acdb06378a84e/pkg/sql/types/types.go#L655)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm wondering if we need to have two types here, like
```
	// JSONBArray is the type of an array value having JSONB-typed elements.
	JSONBArray = &T{InternalType: InternalType{
		Family: ArrayFamily, ArrayContents: Jsonb, Oid: oid.T__jsonb, Locale: &emptyLocale}}

	// JSONArray is the type of an array value having JSON-typed elements.
	JSONArray = &T{InternalType: InternalType{
		Family: ArrayFamily, ArrayContents: Json, Oid: oid.T__json, Locale: &emptyLocale}}
```

(all the current usages should use JSONBArray, but the new ones you are adding should use JSONArray)

see my comment on DecodeDatum
</blockquote></details>

Nice catch, thanks! Done.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL3-Wz5-AX9POAZpUte:-NL7PJms1VXFMjkPsCaM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedce90eb2666e9d3cf99cdedbb0f9efe4fe22d6/pkg/sql/pgwire/testdata/pgtest/json_array#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should be `send crdb_only` or else make sure to add a `until noncrdb_only` below this.
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NL317n17NiErWQcTL-l:-NL7PMwF9_C9E0aI8NHY:b-yevuc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedce90eb2666e9d3cf99cdedbb0f9efe4fe22d6/pkg/sql/pgwire/testdata/pgtest/json_array#L48)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should have some tests where `ParameterFormatCodes` is `[1]` so that the binary input format is tested
</blockquote></details>

Done, see below

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/pgwire/conn.go` line 974 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRwPXu299WIoNbHtJj:-NLRwPXu299WIoNbHtJk:bndvust) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/conn.go#L974)):*
> ```Go
> 				continue
> 			}
> 			// This special case for json, json[] and jsonb[] is here so we can
> ```

nit: there is no special case for `jsonb[]` here
___
*[`pkg/sql/types/oid.go` line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRtNQ_5idt07RaT_eT:-NLRtNQ_5idt07RaT_eU:b-1xlysi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/types/oid.go#L82)):*
> ```Go
> 	// oid.T_json:      Json,
> 	oid.T_jsonb:        Jsonb,
> 	oid.T__jsonb:       JSONBArray,
> ```

hm, this shouldn't be needed. note that there is no other Array type in this map
___
*[`pkg/sql/types/types.go` line 658 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRvoW67WwPmbdABvCT:-NLRvoW67WwPmbdABvCU:bezd7pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/types/types.go#L658)):*
> ```Go
> 
> 	// JSONArray is the type of an array value having JSON-typed elements.
> 	JSONArray = &T{InternalType: InternalType{
> ```

maybe we should name this new `JSONArray` type something like `JSONArrayForDecodingOnly`, so that people know not to use it in other places. (and explain in the comment)
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRx0tI10ZC2LJBE9xr:-NLRx0tI10ZC2LJBE9xs:bwspe3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L57)):*
> ```
> ----
> {"Type":"BindComplete"}
> {"Type":"DataRow","Values":[{"binary":"000000000000000000000eda"}]}
> ```

i ran this test against postgres with `./dev test pkg/sql/pgwire -f=TestPGTest/json_array --test-args='-addr localhost:5432 -user rafiss -rewrite'` and there was a diff, so there's more adjusting needed. on postgres, this results in `000000000000000000000072`, i think because PG outputs ` json[]` while CRDB ouputs a `jsonb[]`
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRxGmv5kG48x39dVJ6:-NLRxGmv5kG48x39dVJ7:b-mwnvy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L71)):*
> ```
> ----
> {"Type":"BindComplete"}
> {"Type":"DataRow","Values":[{"binary":"000000010000000000000eda00000001000000010000000a017b2261223a207b7d7d"}]}
> ```

on postgres, this results in `0000000100000000000000720000000100000001000000087b2261223a7b7d7d`. this is also because PG outputs ` json[]` while CRDB ouputs a `jsonb[]`
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRxcBu1zi3VrdTKwhv:-NLRxcBu1zi3VrdTKwhw:b-lcuf3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L86)):*
> ```
> ----
> {"Type":"BindComplete"}
> {"Type":"DataRow","Values":[{"text":"{\"{\\\"a\\\": {}}\"}"}]}
> ```

on PG this results in `{"Type":"DataRow","Values":[{"text":"{\"{\\\"a\\\":{}}\"}"}]}` (no space after the `:`)
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRuqGsCwHTFuo7IjQq:-NLRuqGsCwHTFuo7IjQr:b4ni8eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L125)):*
> ```
> # Test with input in binary.
> send
> Parse {"Query": "SELECT $1::JSON[]", "ParameterOIDs":[199]}
> ```

we still should add another test where ParameterFormatCode=1, and ParameterOID=199, _and_ where the data is successfully decoded. let's test these too:
- `000000000000000000000072` - empty array in `json[]` format
- 0000000100000000000000720000000100000001000000087b2261223a7b7d7d - {\"{\\\"a\\\":{}}\"}"}
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRuO2c7AZGxrPywrLX:-NLRuO2c7AZGxrPywrLY:b-s1gs3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L126)):*
> ```
> send
> Parse {"Query": "SELECT $1::JSON[]", "ParameterOIDs":[199]}
> Bind {"ParameterFormatCodes": [1], "Parameters": [{"binary":"000000000000000000000eda"}]}
> ```

can you add a comment explaining what text value `000000000000000000000eda` represents? my understanding is that it is an empty array in `jsonb[]` format
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRy9eSBeUKszeoJgSP:-NLRy9eSBeUKszeoJgSQ:b-g5y5k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L136)):*
> ```
> ----
> {"Type":"ParseComplete"}
> {"Type":"ErrorResponse","Code":"08P01"}
> ```

on PG this returns error code `42804` (data type mismatch)

to fix this test, add a `until mapError=(42804, 08P01)` and a commend explaining that PG returns `42804` (data type mismatch) while CRDB returns `08P01` (protocol violation), but both are acceptable

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/pgwire/conn.go` line 974 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRwPXu299WIoNbHtJj:-NM4nLP763T16XsIjovg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/conn.go#L974)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: there is no special case for `jsonb[]` here
</blockquote></details>

Done.
___
*[`pkg/sql/types/oid.go` line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRtNQ_5idt07RaT_eT:-NM4nMsI1LpfryvbhR1H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/types/oid.go#L82)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, this shouldn't be needed. note that there is no other Array type in this map
</blockquote></details>

Done.
___
*[`pkg/sql/types/types.go` line 658 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRvoW67WwPmbdABvCT:-NM4nOSk4bURbKghz5OQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/types/types.go#L658)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe we should name this new `JSONArray` type something like `JSONArrayForDecodingOnly`, so that people know not to use it in other places. (and explain in the comment)
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRx0tI10ZC2LJBE9xr:-NM4nSWzCAb6E0qOSkrM:byvyyi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L57)):*
> i think because PG outputs json[] while CRDB ouputs a jsonb[]

Yeah exactly. It's because cockroach parses `JSON[]` as `JSONB[]`. This happens to `JSON` as well. I added tests for both pg and crdb with comments.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRxGmv5kG48x39dVJ6:-NM4nqJSBJ36wJZmQree:b-qxomoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L71)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

on postgres, this results in `0000000100000000000000720000000100000001000000087b2261223a7b7d7d`. this is also because PG outputs ` json[]` while CRDB ouputs a `jsonb[]`
</blockquote></details>

Split the test for pg and crdb. Also pg's binary record the number of spaces between the key and value in the json text input, but cockroach doesn't. See the tests added in the third commit.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRxcBu1zi3VrdTKwhv:-NM4pdVzAlIVQrzNAreP:b-deaqqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L86)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

on PG this results in `{"Type":"DataRow","Values":[{"text":"{\"{\\\"a\\\":{}}\"}"}]}` (no space after the `:`)
</blockquote></details>

This turns out to be a bug for json as well. Filed [here](https://github.com/cockroachdb/cockroach/issues/95434), also added tests in the 3rd commit.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRuqGsCwHTFuo7IjQq:-NM4porQBulqDAhyw2V1:bvcojn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L125)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we still should add another test where ParameterFormatCode=1, and ParameterOID=199, _and_ where the data is successfully decoded. let's test these too:
- `000000000000000000000072` - empty array in `json[]` format
- 0000000100000000000000720000000100000001000000087b2261223a7b7d7d - {\"{\\\"a\\\":{}}\"}"}
</blockquote></details>

Done. Note that I added the `json[]` binary for `{"{\"a\": {}}"}"}` (with a space between the kv) so it differs from the value you had above.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRuO2c7AZGxrPywrLX:-NM4q-uG7gi8EbZDPzX0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L126)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add a comment explaining what text value `000000000000000000000eda` represents? my understanding is that it is an empty array in `jsonb[]` format
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/testdata/pgtest/json_array` line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-NLRy9eSBeUKszeoJgSP:-NM4q14t8K_YoliNEFnu:bd78h4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c603ca8c4bcb0fb8e2b1bec1d09d65e9379f840/pkg/sql/pgwire/testdata/pgtest/json_array#L136)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

on PG this returns error code `42804` (data type mismatch)

to fix this test, add a `until mapError=(42804, 08P01)` and a commend explaining that PG returns `42804` (data type mismatch) while CRDB returns `08P01` (protocol violation), but both are acceptable
</blockquote></details>

Ah TIL. Thanks, done.

**Review by rafiss — APPROVED** [review]
nice tests, this lgtm!

> Reviewed 2 of 3 files at r1, 7 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94705#-:-NM5OYxXAevkrnoqcsAM:b-p9j03i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

**Comment by ZhouXing19** [comment]
TFTR!
bors r+

**Pull request merged**
