### PR TITLE
bazel: upgrade to 6.2.1

### PR DESCRIPTION
**Pull request by rickystewart**
Epic: CRDB-8308
Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
First commit here is from #105212, also I'll run `dev gen bazel --mirror` when https://github.com/knz/go-libedit/pull/26 is merged.

**Comment by knz** [comment]
you good

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rail** [comment]
Looks like make and publish [failed](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_Process_MakeAndPublishBuildArtifactsV221/10633666?buildTab=log&focusLine=2886&logView=flowAware&linesState=2541.2553.2615) tonight.
```
02:06:43     INFO: Build options --//build/toolchains:cross_flag, --//build/toolchains:force_build_cdeps_flag, --compilation_mode, and 2 more have changed, discarding analysis cache.

02:06:43     Analyzing: 3 targets (3 packages loaded, 0 targets configured)

02:06:43     ERROR: /go/src/github.com/cockroachdb/cockroach/c-deps/BUILD.bazel:204:11: Illegal ambiguous match on configurable attribute "actual" in //c-deps:libgeos:

02:06:43     //build/toolchains:force_build_cdeps

02:06:43     @io_bazel_rules_go//go/platform:linux_amd64

02:06:43     Multiple matches are not allowed unless one is unambiguously more specialized or they resolve to the same value. See https://bazel.build/reference/be/functions#select

02:06:43     ERROR: Analysis of target '//c-deps:libgeos' failed; build aborted:

02:06:43     INFO: Elapsed time: 0.556s

02:06:43     INFO: 0 processes.

02:06:43     FAILED: Build did NOT complete successfully (3 packages loaded, 311 targets configured)

02:06:43     2023/06/22 06:06:43 main.go:254: failed to run [bazel build //pkg/cmd/cockroach //pkg/cmd/cockroach-sql //c-deps:libgeos --workspace_status_command=./build/bazelutil/stamp.sh x86_64-pc-linux-gnu official-binary release v23.1.0-alpha.7-3371-g71228e57723 -c opt --config=ci --config=force_build_cdeps --config=crosslinuxbase]: : exit status 1
```

**Pull request merged**
