### PR TITLE
sql: Fix bug in zone constraint validation for attributes.

### LINKED ISSUE #39800: sql: validation of constraints referencing attributes is broken
```
root@:26257/defaultdb> alter table t configure zone using constraints='["+x1","+x2"]';
pq: incompatible zone constraints: "+x1" and "+x2"
```

There's nothing incompatible about those constraints. Based on some superficial debugging, I believe the problem is that we parse those constraints badly - we parse them as having an empty "key" and a populated "value". And then some validation code sees that there's two "conflicting" constraints using the same empty key.
Presumably this code was only tested with constraints referencing localities, not,

I find it very surprising that we'd want to populate the constraints' values and not their keys. Assuming this was always the case, I wonder if constraints referencing attributes work at all.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #39800.

Release note: None

### CODE REVIEW

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rohany, and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39822#-LnCsQnc0HDSMcJKOBaS:-LnCsQnc0HDSMcJKOBaT:bpwseui) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebe63473047772de7b52e994ee2e8854ebb67cf/pkg/sql/set_zone_config.go#L535)):*
> ```Go
> 			// Don't perform any validation for pairs with an empty key.
> 			// These attributes are not real key value pairs, and instead
> 			// are node attributes, such as +ssd.
> ```

Would it still make sense to check for conflicting attributes, like `+ssd,-ssd`?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39822#-LnCsQnc0HDSMcJKOBaS:-LnDlHAx2c5CqB4f-T_o:b-41pepv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ebe63473047772de7b52e994ee2e8854ebb67cf/pkg/sql/set_zone_config.go#L535)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Would it still make sense to check for conflicting attributes, like `+ssd,-ssd`?
</blockquote></details>

you're right. PTAL

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rohany, and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39822#-LnSYtug4SCp12R2JSsv:-LnSYtug4SCp12R2JSsw:bxljspv) ([raw file](https://github.com/cockroachdb/cockroach/blob/875804247c0d50dee2c25d721270ff8d57c15e71/pkg/sql/set_zone_config.go#L537)):*
> ```Go
> 				// are attributes, due to the keys being the same for attributes.
> 				if curr.Key == "" && other.Key == "" {
> 					if curr.Value == other.Value {
> ```

Nit: You can combine these into a single `if`. Also maybe we should also check that `curr.Type != other.Type`?  `["+ssd", "+ssd"]` is redundant but not really incompatible.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39822#-LnSYtug4SCp12R2JSsv:-LnTHP7W5Vd16uz0ln6j:bz15vqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/875804247c0d50dee2c25d721270ff8d57c15e71/pkg/sql/set_zone_config.go#L537)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: You can combine these into a single `if`. Also maybe we should also check that `curr.Type != other.Type`?  `["+ssd", "+ssd"]` is redundant but not really incompatible.
</blockquote></details>

I had that originally, but we don't want that -- if the values are not equal (and the keys are both empty), then we fall into the other case and perform an incorrect validation sequence on the attributes. I can update the comment if that isn't clear.

I think we want to keep that +ssd and +ssd is invalid -- to me it looks like its a user error, and they should be notified (for example forgot to copy the correct node attributes in or something).

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rohany, and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39822#-LnSYtug4SCp12R2JSsv:-LnU62pZAtbwc0SmPZNc:b-xihiuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/875804247c0d50dee2c25d721270ff8d57c15e71/pkg/sql/set_zone_config.go#L537)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I had that originally, but we don't want that -- if the values are not equal (and the keys are both empty), then we fall into the other case and perform an incorrect validation sequence on the attributes. I can update the comment if that isn't clear.

I think we want to keep that +ssd and +ssd is invalid -- to me it looks like its a user error, and they should be notified (for example forgot to copy the correct node attributes in or something). 
</blockquote></details>

Ah right, ok works for me.

**Comment by rohany** [comment]
bors r=solongordon

**Pull request merged**
