### PR TITLE
storage: allocator will actively move replicas due to zone configs

### PR DESCRIPTION
**Pull request by BramGruneir**
This change allows the allocator to determine when there are replicas on nodes or stores that violate a constraint. This can happen when a zone config is changed after the replicas are already present.

Replaces #13288

I've done a large number of tests on indigo and it performed admirably.  I'll add some of those results in a bit.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14106)

### CODE REVIEW

**Comment by a-robinson** [comment]
When you tested this on indigo, was it with or without load-based leaseholder rebalancing?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/storage/allocator_test.go, line 2025 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CVbgzNGVo-wWomdy:-Kf7CVbgzNGVo-wWomdz:b-ucd52s) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2025)):*
> constraint: config.Constraint{Key: "datacenter", Value: "us", Type: config.Constraint_POSITIVE},
> 			expected:   &stores[3].StoreID

This is what we were discussing in the meeting, right? Whether a positive constraint should move all replicas there or just ensure there's at least one there?

---

*[pkg/storage/allocator_test.go, line 2029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CuUIBVNQk8ohMYhw:-Kf7CuUIBVNQk8ohMYhx:b5v3pbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2029)):*
> constraint: config.Constraint{Key: "datacenter", Value: "eur", Type: config.Constraint_REQUIRED},
> 			expected:   &stores[4].StoreID,

What would happen to this case if we made the rabalance to 4 and then called the function again (i.e. if two replicas were in EUR, one in US, but there wasn't another EUR node to rebalance to)?

---

*[pkg/storage/client_raft_test.go, line 1134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7Dgsevpcmj-O3GkuE:-Kf7Dgsevpcmj-O3GkuF:b-qlipyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/client_raft_test.go#L1134)):*
> ```Go
> 	const extraStores = 3
> 
> 	ctx := context.Background()
> ```

For what it's worth, the changes in this file probably belonged in a separate commit and/or PR, but thanks for cleaning it up :)

---

*[pkg/storage/rule_solver.go, line 322 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7Iv-FznCtbw8iOyzH:-Kf7Iv-FznCtbw8iOyzI:b-5m7maz) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L322)):*
> ```Go
> // most qualified. The second list is of all potential stores that could be
> // used as rebalancing receivers, ordered from best to worst.
> func rebalanceCandidates(
> ```

Is there a unit test that covers this and/or shouldRebalance?

---

*[pkg/storage/rule_solver.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7GUuAeo6MDmMYMzV0:-Kf7GUuAeo6MDmMYMzV1:b-w5jjmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L341)):*
> ```Go
> 	var constraintsOkStoreDescriptors []roachpb.StoreDescriptor
> 	constraintsOkByStoreID := make(map[roachpb.StoreID]bool)
> 	preferredMatchedByStoreID := make(map[roachpb.StoreID]int)
> ```

What's meant by `preferredMatched`? What's a "Matched"? There's probably a clearer name for this.

---

*[pkg/storage/rule_solver.go, line 354 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7Gndi6lPnv4mIcpL8:-Kf7Gndjg2_vMVAq1zb4:b64ilvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L354)):*
> ```Go
> 			if exists && preferredMatched < preferredExistingWorst {
> 				preferredExistingWorst = preferredMatched
> 			} else if !exists && preferredMatched > preferredCandidateBest {
> ```

Are `preferredMatched` values always greater than 0? If not, then `preferredCandidateBest` should start at math.MinInt64, rather than 0 (and probably should anyway, just to be safe about potential future changes)

---

*[pkg/storage/rule_solver.go, line 366 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HXpwUn_ICklwedPa:-Kf7HXpwUn_ICklwedPb:b-td47a) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L366)):*
> ```Go
> 
> 	if preferredCandidateBest > preferredExistingWorst {
> 		rebalanceConstraintsCheck = true
> ```

Does the existence of a more preferred store really qualify as a constraints check issue? If nothing else, the variable names here would lead me to believe that it's just a preference, not a constraints requirement

---

*[pkg/storage/rule_solver.go, line 368 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HF7MH8Um_UAS6u4n:-Kf7HF7MH8Um_UAS6u4o:b-453v0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L368)):*
> ```Go
> 		rebalanceConstraintsCheck = true
> 		if log.V(2) {
> 			log.Infof(ctx, "try to rebalance to improve preferred score from %d to %d",
> ```

nit, but should this be s/try/trying? Commands like "try to ..." read funny in the logs

---

*[pkg/storage/rule_solver.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HmdLL0gH9jQpF03X:-Kf7HmdLL0gH9jQpF03Y:b-n5cr96) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L377)):*
> ```Go
> 	var shouldRebalanceCheck bool
> 	if !rebalanceConstraintsCheck {
> 		for _, s := range sl.stores {
> ```

It's not an immediate concern, but how do you expect this method to scale with the number of stores in the cluster? We're iterating over all of them and doing some computations up to three different times, for all leaseholder replicas on each node.

---

*[pkg/storage/store_pool.go, line 456 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf710-rmrjQmvdVAqzn:-Kf710-rmrjQmvdVAqzo:b8j2y65) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/store_pool.go#L456)):*
> ```Go
> // from the subset of passed in store IDs.
> func (sp *StorePool) getStoreListFromIDs(
> 	storeIDs roachpb.StoreIDSlice, rangeID roachpb.RangeID,
> ```

The `rangeID` parameter to these methods never ceases to confuse me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-:-Kf71QSaToJ2LIyDrZUG:b-p70dfk)*

**Comment by BramGruneir** [comment]
Without load-based leaseholder rebalancing.  I can start some runs with it enabled as well, but I don't think it's going to show a major shift.  Consider that the loads run on it are photos and blockwriter.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/storage/allocator_test.go, line 2025 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CVbgzNGVo-wWomdy:-Kf7KZqr88EG6vn5mqVB:ba5me2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2025)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> constraint: config.Constraint{Key: "datacenter", Value: "us", Type: config.Constraint_POSITIVE},
> 			expected:   &stores[3].StoreID

This is what we were discussing in the meeting, right? Whether a positive constraint should move all replicas there or just ensure there's at least one there?
</blockquote></details>

Yes.  Right now, it will try to move as many as it can.  And this competes with diversity.  

---

*[pkg/storage/allocator_test.go, line 2029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CuUIBVNQk8ohMYhw:-Kf7KcfUXvf4pKOrVNRX:b-fc09kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2029)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> constraint: config.Constraint{Key: "datacenter", Value: "eur", Type: config.Constraint_REQUIRED},
> 			expected:   &stores[4].StoreID,

What would happen to this case if we made the rabalance to 4 and then called the function again (i.e. if two replicas were in EUR, one in US, but there wasn't another EUR node to rebalance to)?
</blockquote></details>

If there is no suitable rebalance candidate, there will be no action.  We don't remove a rebalance a replica if there is no suitable place for it to go.  See the final 3 tests, trying to move thing to `datacenter other` We should consider adding a "violating constraints" list to our forthcoming ranges in bad states page.

---

*[pkg/storage/client_raft_test.go, line 1134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7Dgsevpcmj-O3GkuE:-Kf7KhyQ8iKPedDmsUnO:b7myf54) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/client_raft_test.go#L1134)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

For what it's worth, the changes in this file probably belonged in a separate commit and/or PR, but thanks for cleaning it up :)
</blockquote></details>

The reason for the changes here were due to this test failing and debugging it.  I figured the actual change was more or less harmless.

---

*[pkg/storage/rule_solver.go, line 322 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7Iv-FznCtbw8iOyzH:-Kf7UgMnK8VG2jT0qlT4:bahms9) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L322)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Is there a unit test that covers this and/or shouldRebalance?
</blockquote></details>

A number already do actually.

---

*[pkg/storage/rule_solver.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7GUuAeo6MDmMYMzV0:-Kf7V9pZiWGLEF3wk8wO:b-80u18m) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L341)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

What's meant by `preferredMatched`? What's a "Matched"? There's probably a clearer name for this.
</blockquote></details>

Renamed to just `preferredByStoreID`.  There are for preferred constraints.  

---

*[pkg/storage/rule_solver.go, line 354 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7Gndi6lPnv4mIcpL8:-Kf7UoOdbPeGuJxBK956:b-m0qz39) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L354)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Are `preferredMatched` values always greater than 0? If not, then `preferredCandidateBest` should start at math.MinInt64, rather than 0 (and probably should anyway, just to be safe about potential future changes)
</blockquote></details>

yes they are, but that's a good idea regardless.

Done.

---

*[pkg/storage/rule_solver.go, line 366 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HXpwUn_ICklwedPa:-Kf7VnFMymlZe3qGoO-d:b-cu17ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L366)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Does the existence of a more preferred store really qualify as a constraints check issue? If nothing else, the variable names here would lead me to believe that it's just a preference, not a constraints requirement
</blockquote></details>

Yeah, having a preferred store is not a requirement but should more or less guarantee that at least one replica is on a preferred store.  Without this, when you change the zone config to include a preference, nothing will happen.

But there might be the need for a bit more logic here.  I'm going to consider adding a bit more logic to ensure that if a preferred constraint is already filled, we can ignore it.  That should remove all the thrashing.

---

*[pkg/storage/rule_solver.go, line 368 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HF7MH8Um_UAS6u4n:-Kf7WOD_AWstNyyaZRyz:bvnrpcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L368)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

nit, but should this be s/try/trying? Commands like "try to ..." read funny in the logs
</blockquote></details>

updated

---

*[pkg/storage/rule_solver.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HmdLL0gH9jQpF03X:-Kf7WVBJZ1lYm1PKTPMN:b-yc0xoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L377)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It's not an immediate concern, but how do you expect this method to scale with the number of stores in the cluster? We're iterating over all of them and doing some computations up to three different times, for all leaseholder replicas on each node.
</blockquote></details>

If in the 100 to 1000 range, I think we're ok.  When we start pushing 10000, we can revisit it.  But the bigger issue would be having a cache in the store pool instead of locking, which will slow down everything that uses the store pool.

---

*[pkg/storage/store_pool.go, line 456 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf710-rmrjQmvdVAqzn:-Kf7VESsH2LVUc_WVrHq:b-kmpqa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/store_pool.go#L456)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The `rangeID` parameter to these methods never ceases to confuse me
</blockquote></details>

yeah, I added the comment on it in `getStoreList`, but there must be a better way to do this.  Just not going to address it in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-:-Kf7KI6wLbg27JM9A0zB:b-vnvzw2)*

**Comment by petermattis** [comment]
I need to take another look at this when my eyes are fresher.

---

Review status: 4 of 5 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator_test.go, line 2025 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CVbgzNGVo-wWomdy:-Kf7b2MJw3wNMM7By2eA:bbvns19) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2025)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Yes.  Right now, it will try to move as many as it can.  And this competes with diversity.  
</blockquote></details>

Why does this compete with diversity? Shouldn't one win (either the positive constraint or diversity)? Competing implies they have the same priority, but I don't think we want a level playing field here.

Btw, before fixing this I think we should figure out what the desired semantics of a positive constraint are.

---

*[pkg/storage/rule_solver.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7GUuAeo6MDmMYMzV0:-Kf7h5tz2QZdLCLBPSQ4:b-byaqo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L341)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Renamed to just `preferredByStoreID`.  There are for preferred constraints.  
</blockquote></details>

I think this would be clearer as a single map from storeID to constraint info:

```
type constraintInfo struct {
  ok bool
  matched int
}
storeInfo := make(map[roachpb.StoreID]constraintInfo)
```

FYI, you can define a type within a method (you just can't define any methods on that type).

---

*[pkg/storage/rule_solver.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HmdLL0gH9jQpF03X:-Kf7i3PJdTIp0q4-jGot:b-8b2xc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L377)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

If in the 100 to 1000 range, I think we're ok.  When we start pushing 10000, we can revisit it.  But the bigger issue would be having a cache in the store pool instead of locking, which will slow down everything that uses the store pool.
</blockquote></details>

I bet this per-store computation will show up in profiles before we hit 1000 stores. 

---

*[pkg/storage/rule_solver.go, line 353 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7gZMk4lLq2zDcFNuN:-Kf7gZMk4lLq2zDcFNuO:b-2amm72) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7f72422904103d743347abb45be5a765defc06/pkg/storage/rule_solver.go#L353)):*
> ```Go
> 			constraintsOkStoreDescriptors = append(constraintsOkStoreDescriptors, s)
> 			if exists && preferredMatched < preferredExistingWorst {
> 				preferredExistingWorst = preferredMatched
> ```

I've always found code like this more readable if the assignment and the comparison have the variables on the same side. Above, you're comparing `a < b` and then assigning `b = a`. I think this is more readable as:

```
if exists && preferredExistingWorse > preferredMatched {
  preferredExistingWorse = preferredMatched
}
```

Ditto for the comparison below. Feel free to ignore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-:-Kf7iVcAIhKCQm_thIil:bhs7z2w)*

**Comment by a-robinson** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator_test.go, line 2025 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CVbgzNGVo-wWomdy:-Kf7iAF1tby6ktHDRUNr:bylfa94) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2025)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Yes.  Right now, it will try to move as many as it can.  And this competes with diversity.  
</blockquote></details>

And is that the behavior that's agreed upon as what we want?

---

*[pkg/storage/allocator_test.go, line 2029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CuUIBVNQk8ohMYhw:-Kf7iHKHXNVgxI1NIM1p:b-1lmpj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2029)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

If there is no suitable rebalance candidate, there will be no action.  We don't remove a rebalance a replica if there is no suitable place for it to go.  See the final 3 tests, trying to move thing to `datacenter other` We should consider adding a "violating constraints" list to our forthcoming ranges in bad states page.
</blockquote></details>

Yeah, that seems wise. Mind opening an issue or adding it to an existing one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106)*

**Comment by BramGruneir** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator_test.go, line 2025 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CVbgzNGVo-wWomdy:-Kf7zh7osG1Pw_7xm9tf:b-5v3dmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2025)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

And is that the behavior that's agreed upon as what we want?
</blockquote></details>

After further reflection, I think we should redefine a positive constraint as a preference for at least one replica following that constraint.  This will require more work, since we won't be able to blindly pick a store with more positive constraint matches, but instead we will have to find the candidates that increase the number of matches (and when removing, the opposite, which one takes the least away).

Right now, a single positive constraint is equal to a full diversity score (i.e. top level locality difference).  But if you had two, say `region=eastus` and `ssd`, then any store with both would always win.  And worse, if you had ssds in every region except for eastus, than it's possible to be in just eastus or just ssd, which isn't really fulfilling the constraint.

So for the interim, we if penalize the convergence score by 0.01, than we should be able to emulate at least making sure that the preference is respected over diversity.

---

*[pkg/storage/allocator_test.go, line 2029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7CuUIBVNQk8ohMYhw:-Kf8-kqYn1nx8EAyR09Z:b-17erfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/allocator_test.go#L2029)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Yeah, that seems wise. Mind opening an issue or adding it to an existing one?
</blockquote></details>

I'll add it.  #14113

---

*[pkg/storage/rule_solver.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7GUuAeo6MDmMYMzV0:-Kf82kRLXgDhMTl2aTCX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L341)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this would be clearer as a single map from storeID to constraint info:

```
type constraintInfo struct {
  ok bool
  matched int
}
storeInfo := make(map[roachpb.StoreID]constraintInfo)
```

FYI, you can define a type within a method (you just can't define any methods on that type).
</blockquote></details>

Done.

---

*[pkg/storage/rule_solver.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7HmdLL0gH9jQpF03X:-Kf830y5SnUKyqFxYpJF:blujv7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/17770a87559d37a7413a83b02b8da7b06d7c5721/pkg/storage/rule_solver.go#L377)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I bet this per-store computation will show up in profiles before we hit 1000 stores. 
</blockquote></details>

When we are dealing with 1000 store issues, I'll be very happy to refactor this.

---

*[pkg/storage/rule_solver.go, line 353 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-Kf7gZMk4lLq2zDcFNuN:-Kf8308pRWm0kQfmcN-b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7f72422904103d743347abb45be5a765defc06/pkg/storage/rule_solver.go#L353)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I've always found code like this more readable if the assignment and the comparison have the variables on the same side. Above, you're comparing `a < b` and then assigning `b = a`. I think this is more readable as:

```
if exists && preferredExistingWorse > preferredMatched {
  preferredExistingWorse = preferredMatched
}
```

Ditto for the comparison below. Feel free to ignore.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106)*

**Comment by a-robinson** [comment]
:lgtm: but wait for @petermattis's full review.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-:-Kf8CKY16IWlCnO7SA7S:bucwv4r)*

**Comment by BramGruneir** [comment]
Here are some of my test results.  I'm working on some that include preferred instead of just required and negative.

All tests were run with both photos and blockwriter loads running.

From: no constraints
To: datablocks +region=westus 
image

From: datablocks +region=westus
To: datablocks +region=eastus
image

From: datablocks +region=eastus 
To: datablocks -region=eastus
image

From: datablocks -region=eastus
To: no constraints
image

From: no constraints 
To: datablocks +region=centralus, .default = +region=westus, photos = +region=eastus
image

From: datablocks +region=centralus, .default = +region=westus, photos = +region=eastus
To: datablocks -region=centralus, .default = -region=westus, photos = -region=eastus 
image

From: To: datablocks -region=centralus, .default = -region=westus, photos = -region=eastus 
To: .default = -region=westus
image

**Comment by BramGruneir** [comment]
I've pushed a new version in which I've removed all logic around positive constraints.  Once #14163 is closed, I'll follow up with actively rebalancing based on a change in positive constraints.

**Comment by BramGruneir** [comment]
Based on all my testing, this looks like it's ready to go, and if would could get it in this week's beta would be great.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14106#-:-KfMUp4-vv3NdyyyFFO4:bnfp4nl)*

**Pull request merged**
