### PR TITLE
storageccl: move import and export request limits to Store

### PR DESCRIPTION
**Pull request by dt**
These limits should be per-store, and thus embedded in the Store itself, rather than per-node, and can be hooked up to cluster settings to allow on-the-fly tuning.
A little extra plumbing is required to get them into the batcheval.EvalCtx that's available in these commands, but that's just part of being per-store rather than singletons.

Release note (enterprise change): add configurable limits on number of bulk io requests each store will process.

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Comment by danhhz** [comment]
:lgtm:

I think this is worth merging, but the semantics of these limiters are becoming increasingly unclear, especially the Import one. What bottleneck are they limiting? If it's disk usage (which is what I'd guess by making them per-store), then we should be limiting AddSSTable, not Import (plus we already have the `kv.bulk_io_write.max_rate` which does the same thing in a better way). If it's network, then the limiting should be per-nic or something (certainly not per-store). If it's rekeying, it should likely be some function of number of cpus. Can you file a 2.1 issue plz?

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23517#-L70HfwBE4dTdNCuow_a:-L70HfwCGACIaOoGEWLe:b-ndqs8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5749cc8d489df48946b81eb7383619d575c01890/pkg/storage/store.go#L140)):*
> ```Go
> 
> // ExportRequestsLimit is the number of Export requests that can run at once.
> // Each extracts data from RocksDB to a temp file and then uploads it to cloud
> ```

not your change, but this comment has rotted. we no longer use temp files for this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23517#-:-L70HqhNyL4RNItxCK_y:bhyvzh)*

**Comment by dt** [comment]
I like the write_rate limit better for limiting disk IO as well (especially with the only-counting-2mb thing fixed), but supposing it works as intended, and you have a slow disk, I still think we want to limit letting requests in as well -- otherwise you could end up unbounded requests fetching and rekeying their SSTs but then before blocking on the rate-limited AddSSTables, tying up potentially with gigs of re-keyed SSTs sitting in memory in the mean time. I think we still want both limits so we have reasonable back-pressure at each step, but the import requests limit might now want to be a bit high, say, 3 or something, that backs out to a reasonable amount of buffered SSTs, rather than targeting some write-rate, as that's no longer its job.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23517#-:-L70W_smliDmZIlpfNAu:b-3xusar)*

**Comment by danhhz** [comment]
Sure agreed. I guess change my point to the more general "this has become wonky over time and we should revisit"

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23517#-:-L70c72fh5mHCZ-3EXaK:bm3kfw1)*

**Comment by dt** [comment]
yeah, and an explainer doc of what they do and how they interact would be good too. (also, wow, I murdered those sentences didn't i)

**Comment by dt** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23517#-L70HfwBE4dTdNCuow_a:-L70hLdLv3vI_hOc6mG2:b-s8zfk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5749cc8d489df48946b81eb7383619d575c01890/pkg/storage/store.go#L140)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

not your change, but this comment has rotted. we no longer use temp files for this
</blockquote></details>

Done -- eliminated the stale specifics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23517)*

**Comment by dt** [comment]
@danhhz I think we can piggyback on cockroachdb/docs#2533 for documenting these and how they interact?

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23517#-:-L70iHwJvX__DTbmkHfW:bjvmp73)*

**Comment by dt** [comment]
@danhhz we've also got https://github.com/cockroachdb/cockroach/issues/22733 for thinking about how to improve rate limiting behaviors and I think we can capture some of this there too.

**Comment by danhhz** [comment]
> we've also got #22733 for thinking about how to improve rate limiting behaviors and I think we can capture some of this there too.

Okay, cool. I'm happy to piggy-back on that issue. Let's make the scope of it a bit more general to capture that we should revisit all this. I just want to make sure that someone thinks about this in the 2.1 cycle.

**Comment by dt** [comment]
Yep I commented here as I was commenting / updating that one.

**Comment by dt** [comment]
discussing with @danhhz it seems like we might want to cherrypick to 2.0, since this gives us runtime knobs we can offer in troubleshooting situations

**Pull request merged**
