### PR TITLE
[wip] kvserver: plumb in node liveness into the allocator

### PR DESCRIPTION
**Pull request by irfansharif**
Do it instead of a bunch of intermediate state and types we were using
before. 

Release note: None

---

The first commit is from the first commit of #69972, and will be folded away.
Also, need to actually update the tests here.

### CODE REVIEW

**Comment by tbg** [comment]
Alex WDYT? To me this looks sensible but I haven't reviewed in-depth.

**Comment by lunevalex** [comment]
I think I groked the proposal now, yes it makes sense to get rid of the intermediate data structure all together and just drive everything from liveness. I would have to review in more detail to make sure it's actually covering everything correctly. That function on store_pool.go is quite dense. In terms of backporting, I think this change introduces no more risk than the original change of introducing the new intermediate data structures explored in #69972.

**Comment by lunevalex** [comment]
ping?

**Comment by irfansharif** [comment]
I doubt I'll be able to get to this soon, and I'm sorry for having dragged my feet here and stalling #69972. I still think it's the right approach longer-term, but the test changes here were pretty exhausting to work through + get right. I'll abandon it for now, perhaps after #70552 these allocator tests are much easier to write+maintain.

**Pull request closed without merging**
