### PR TITLE
admin: tenant support jobs endpoints

### LINKED ISSUE #84621: tenant: support jobs endpoints on tenant HTTP server
In order to support the jobs page on both the DB Console and Cloud consoles, adding support on the sql tenant will add multi-tenant support for the API.

nb: I've created this mostly to track completion of #84620 

Jira issue: CRDB-17766

Epic: CC-6266

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, the Job() and Jobs() endpoints were not implemented on the
tenant admin server as there was not a need and we had split the
implementation into a tenant-only server.

Now that we want to ship the jobs page into CC Console and support it
for multi-tenant, the endpoints for the UI should work as expected.

This PR edits the `jobHelper` and `jobsHelper` helpers to be functions
instead of methods in `adminServer` which allows the implementation to
be shared between the two servers.

Fixes #84621.

Release note: None

Release justification: low risk, high benefit addition to multi-tenant

### CODE REVIEW

**Review by knz — APPROVED** [review]
:100: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-:-N7LRgoTCa62MVVN-otj:bmi8ppe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

**Review by matthewtodd — APPROVED** [review]

**Review by ericharmeling — CHANGES_REQUESTED** [review]
A couple nits related to CI testing and local testing.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-:-N7NOu6h4KE1hpUvCDTw:b-wuifmo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/tenant_admin.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-N7NOf_b5fNueYFqA41K:-N7NOf_b5fNueYFqA41L:b-u0rke8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2235d74a1197e68f876d2e17050c19c2f09d9ea3/pkg/server/tenant_admin.go#L162)):*
> ```Go
> 	}
> 
> 	j, err := jobsHelper(
> ```

See below for context on this suggestion.



_Suggestion:_
```Go
	}

	t.sqlServer.cfg.TestingKnobs = base.TestingKnobs{}

	j, err := jobsHelper(
```
___
*[`pkg/server/tenant_admin.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-N7NFaVtCnwwT17eT4Nd:-N7NFaVtCnwwT17eT4Ne:b-priy4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2235d74a1197e68f876d2e17050c19c2f09d9ea3/pkg/server/tenant_admin.go#L167)):*
> ```Go
> 		userName,
> 		t.sqlServer,
> 		t.sqlServer.cfg,
> ```

When I test the jobs endpoint locally (using `./cockroach demo --multitenant=true`), the cluster crashes with the following error:

```* ERROR: a panic has occurred!
* interface conversion: base.ModuleTestingKnobs is nil, not *jobs.TestingKnobs
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:1038
*   | runtime.panicdottypeE
*   | 	GOROOT/src/runtime/iface.go:261
*   | runtime.panicdottypeI
*   | 	GOROOT/src/runtime/iface.go:271
*   | github.com/cockroachdb/cockroach/pkg/server.jobsHelper.func2
*   | 	github.com/cockroachdb/cockroach/pkg/server/admin.go:2124
*   | github.com/cockroachdb/cockroach/pkg/server.jobsHelper
*   | 	github.com/cockroachdb/cockroach/pkg/server/admin.go:2129
*   | github.com/cockroachdb/cockroach/pkg/server.(*tenantAdminServer).Jobs
*   | 	github.com/cockroachdb/cockroach/pkg/server/tenant_admin.go:162
* ...
```

Locally, I just set the problematic field to the zero value for `base.TestingKnobs`, and it resolved this issue. IDK if this is the best approach, but it worked for me. :grin: 

(Aside: I assume this was a problem because `jobsHelper` normally expects a pointer to `server.cfg.BaseConfig`, and not `sqlServer.cfg` and that field wasn't getting initialized properly?)
___
*[`pkg/server/tenant_admin.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-N7N7xL07KXsHeTuAPw4:-N7N7xL07KXsHeTuAPw5:b-9shw0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2235d74a1197e68f876d2e17050c19c2f09d9ea3/pkg/server/tenant_admin.go#L182)):*
nit: linter is complaining

>pkg/server/tenant_admin.go:176:1: receiver name s should be consistent with previous receiver name t for tenantAdminServer



_Suggestion:_
```Go
func (t *tenantAdminServer) Job(
	ctx context.Context, request *serverpb.JobRequest,
) (_ *serverpb.JobResponse, retErr error) {
	ctx = t.AnnotateCtx(ctx)

	userName, err := userFromContext(ctx)
	if err != nil {
		return nil, serverError(ctx, err)
	}
	r, err := jobHelper(ctx, request, userName, t.sqlServer)
	if err != nil {
		return nil, serverError(ctx, err)
	}
	return r, nil
}
```

**Review by dhartunian — COMMENTED** [review]
@ericharmeling PTAL, I added a separate commit that does some light refactoring of tests so they can be shared between packages.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-:-N9Iz_Na5Bh44Qzx7tfg:bokymtj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @ericharmeling, and @knz)

___
*[`pkg/server/tenant_admin.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-N7NFaVtCnwwT17eT4Nd:-N9IzVh1DE0hDcISJeDG:b-w3rpqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2235d74a1197e68f876d2e17050c19c2f09d9ea3/pkg/server/tenant_admin.go#L167)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

When I test the jobs endpoint locally (using `./cockroach demo --multitenant=true`), the cluster crashes with the following error:

```* ERROR: a panic has occurred!
* interface conversion: base.ModuleTestingKnobs is nil, not *jobs.TestingKnobs
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:1038
*   | runtime.panicdottypeE
*   | 	GOROOT/src/runtime/iface.go:261
*   | runtime.panicdottypeI
*   | 	GOROOT/src/runtime/iface.go:271
*   | github.com/cockroachdb/cockroach/pkg/server.jobsHelper.func2
*   | 	github.com/cockroachdb/cockroach/pkg/server/admin.go:2124
*   | github.com/cockroachdb/cockroach/pkg/server.jobsHelper
*   | 	github.com/cockroachdb/cockroach/pkg/server/admin.go:2129
*   | github.com/cockroachdb/cockroach/pkg/server.(*tenantAdminServer).Jobs
*   | 	github.com/cockroachdb/cockroach/pkg/server/tenant_admin.go:162
* ...
```

Locally, I just set the problematic field to the zero value for `base.TestingKnobs`, and it resolved this issue. IDK if this is the best approach, but it worked for me. :grin: 

(Aside: I assume this was a problem because `jobsHelper` normally expects a pointer to `server.cfg.BaseConfig`, and not `sqlServer.cfg` and that field wasn't getting initialized properly?)
</blockquote></details>

what I just pushed up works without further tweaking of the config variables.
___
*[`pkg/server/tenant_admin.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-N7N7xL07KXsHeTuAPw4:-N8OYmq98mwT81nX76pq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2235d74a1197e68f876d2e17050c19c2f09d9ea3/pkg/server/tenant_admin.go#L182)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: linter is complaining

>pkg/server/tenant_admin.go:176:1: receiver name s should be consistent with previous receiver name t for tenantAdminServer
</blockquote></details>

Done.

**Review by ericharmeling — APPROVED** [review]
Nice! Apologies for the delay. There are still some linting errors, but otherwise LGTM. Thank you!

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84620#-:-NA4lVz4A-o6KCTeYMvm:b-oc23kc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by dhartunian** [comment]
TFTRs!

bors r=matthewtodd,knz,ericharmeling

**Pull request merged**
