### PR TITLE
scpb: remove Direction type

### PR DESCRIPTION
**Pull request by postamar**
This commit removes the Direction enum type definition from the scpb
package and replaces the direction field in the Target message with
a target_status field of type Status. DROP is therefore mapped to ABSENT
and ADD to PUBLIC.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This is a prelude to getting rid of Target entirely but I found it worthwhile on its own.

**Comment by postamar** [comment]
I pushed another commit which improves opgen somewhat. 

```
    opgen: tighten spec definitions
    
    A recent commit redefined targets as having a target status instead of
    a direction. Another recent commit rewrote the planner in a way which
    allows it to handle no-op edges more gracefully.
    
    This commit follows up on these by changing the semantics of
    the opgen spec definitions: "equiv" calls no longer copy existing
    op-edges with different sources, instead they define no-op edges. This
    should make for more natural state transitions and correspondingly
    reduce the likelihood of bugs in the dependency rules definitions.
    
    This also paves the way for state transitions which don't follow a clear
    ADD / DROP pattern.
    
    Release note: None
```

**Review by fqazi — APPROVED** [review]
> Reviewed 61 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-Ms5cgy-8Ga3Z8qy4Bmx:-Ms5cgy-8Ga3Z8qy4Bmy:bx4oasr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L46)):*
> ```Go
> 
> func enqueueIfNotExists(b BuildCtx, targetStatus scpb.Status, elem scpb.Element) {
> 	if !b.HasTarget(targetStatus, elem) {
> ```

There is always a potential danger of people throwing this method in situations where a duplicate should not exist accidentally. The explicit checks were added because we had a few incorrect cases hiding stuff in the past.

I'm okay with reintroducing this method again, but we have to be more careful where its used.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 61 of 61 files at r1, 40 of 40 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-:-MsU-tg62EftQo8LZ-06:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsTxey26MqhjDQvanAX:-MsTxey26MqhjDQvanAY:b-mye44p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/scbuild/builder_state.go#L26)):*
> ```Go
> 	status, targetStatus scpb.Status, elem scpb.Element, meta scpb.TargetMetadata,
> ) {
> 	for _, node := range b.output {
> ```

drive-by: can this use `b.HasTarget`? If not, the logic in `enqueueIfNotExists` feels bogus, and I'd prefer to have only one place to have to optimize that to be sublinear. 



_Code quote:_
```Go
	for _, node := range b.output {
		if screl.EqualElements(node.Element(), elem) {
			panic(errors.AssertionFailedf("element already present in builder state: %s", elem))
		}
	}
```
___
*[pkg/sql/schemachanger/scplan/opgen/opgen_schema.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsU-D2qAhgSZpZA4T6w:-MsU-D2qAhgSZpZA4T6x:bpqdaju) ([raw file](https://github.com/cockroachdb/cockroach/blob/db42e5bce5cf12b6d056b8f7b700ba4eccdd3fa0/pkg/sql/schemachanger/scplan/opgen/opgen_schema.go#L48)):*
> ```Go
> 			to(scpb.Status_ABSENT,
> 				// TODO(ajwerner): The minPhase here feels like it should be PostCommit.
> 				// Also, this definitely is not revertible. Leaving to make this commit
> ```

the TODO feels weird now



_Code quote:_
```Go
				// TODO(ajwerner): The minPhase here feels like it should be PostCommit.
				// Also, this definitely is not revertible. Leaving to make this commit
				// a port.
```
___
*[pkg/sql/schemachanger/scplan/opgen/target.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsU-l2W66AS3jeoZtkC:-MsU-l2W66AS3jeoZtkD:b8grdkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/db42e5bce5cf12b6d056b8f7b700ba4eccdd3fa0/pkg/sql/schemachanger/scplan/opgen/target.go#L78)):*
> ```Go
> 		isTo:          map[scpb.Status]bool{},
> 		isFrom:        map[scpb.Status]bool{},
> 	}
> ```

uber-nit: make a constructor function? 



_Code quote:_
```Go
	tbs := transitionBuildState{
		from:          spec.from,
		isRevertible:  true,
		isEquivMapped: map[scpb.Status]bool{spec.from: true},
		isTo:          map[scpb.Status]bool{},
		isFrom:        map[scpb.Status]bool{},
	}
```
___
*[pkg/sql/schemachanger/screl/format.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsTywTh7_0zRuvcAbmh:-MsTywTh7_0zRuvcAbmi:b-5sm2ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/screl/format.go#L41)):*
> ```Go
> 	w.SafeString(", ")
> 	w.SafeString(redact.SafeString(e.Target.TargetStatus.String()))
> 	w.SafeString("; ")
> ```

Instead of this semicolon, can we make this instead another pair of `[]` around the element and its `TargetStatus`? I would love if we could find a way to retain the yaml nature of all of this. We should add testing to enforce that it's yaml given the work to have made it yaml. That or we come up with something totally bespoke. The 99% yaml kills me. 
___
*[pkg/sql/schemachanger/scbuild/testdata/alter_table, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsTyFqO4qbvyecB8Ucg:-MsTyFqO4qbvyecB8Uch:b-1at2bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/scbuild/testdata/alter_table#L9)):*
> ```
> ----
> - ABSENT IndexName:{DescID: 54, IndexID: 1, Name: foo_pkey}
>   state: PUBLIC
> ```

while we're here, thoughts on changing this to be `-> ABSENT` as a suffix? Also, can we `s/state/status/` below? 



_Code quote:_
```
- ABSENT IndexName:{DescID: 54, IndexID: 1, Name: foo_pkey}
  state: PUBLIC
```

**Review by postamar — COMMENTED** [review]
Thanks for the reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-:-MsaUsaQCwF_T6-TBOBy:b-hlc8bm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsTxey26MqhjDQvanAX:-MsaVg_75FAfjVcmI1Tb:b-dg8g5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/scbuild/builder_state.go#L26)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

drive-by: can this use `b.HasTarget`? If not, the logic in `enqueueIfNotExists` feels bogus, and I'd prefer to have only one place to have to optimize that to be sublinear. 
</blockquote></details>

I'll revisit this and things like this in my upcoming builder work.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-Ms5cgy-8Ga3Z8qy4Bmx:-MsaVme26Cq8G_c5oEwt:b-4gojtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L46)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

There is always a potential danger of people throwing this method in situations where a duplicate should not exist accidentally. The explicit checks were added because we had a few incorrect cases hiding stuff in the past.

I'm okay with reintroducing this method again, but we have to be more careful where its used.
</blockquote></details>

You're right. I promise to address this in my upcoming builder PR, which will distinguish between "legal" and "illegal" element-already-exists cases more gracefully.
___
*[pkg/sql/schemachanger/scplan/opgen/opgen_schema.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsU-D2qAhgSZpZA4T6w:-MsaWlOFEt1L6USBnnz4:b-xiywyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/db42e5bce5cf12b6d056b8f7b700ba4eccdd3fa0/pkg/sql/schemachanger/scplan/opgen/opgen_schema.go#L48)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

the TODO feels weird now
</blockquote></details>

I've removed this and other TODOs in opgen, I don't feel they're relevant.
___
*[pkg/sql/schemachanger/scplan/opgen/target.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsU-l2W66AS3jeoZtkC:-MsaWv5V7nxQvrSt2Tfg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db42e5bce5cf12b6d056b8f7b700ba4eccdd3fa0/pkg/sql/schemachanger/scplan/opgen/target.go#L78)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

uber-nit: make a constructor function? 
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/screl/format.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsTywTh7_0zRuvcAbmh:-MsaWwHj37dy5REMOct4:b-bp18yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/screl/format.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Instead of this semicolon, can we make this instead another pair of `[]` around the element and its `TargetStatus`? I would love if we could find a way to retain the yaml nature of all of this. We should add testing to enforce that it's yaml given the work to have made it yaml. That or we come up with something totally bespoke. The 99% yaml kills me. 
</blockquote></details>

Done. I'll keep thinking about the YAML thing.
___
*[pkg/sql/schemachanger/scbuild/testdata/alter_table, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74227#-MsTyFqO4qbvyecB8Ucg:-MsaX2bV4cJSVvwJYAAF:b-zerobz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8e0bfdd83773c699a4f9c4b14caa3896ef72042/pkg/sql/schemachanger/scbuild/testdata/alter_table#L9)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

while we're here, thoughts on changing this to be `-> ABSENT` as a suffix? Also, can we `s/state/status/` below? 
</blockquote></details>

I looked into this. I settled on just printing out the node's string representation instead.

**Comment by postamar** [comment]
Unrelated flake.

**Comment by postamar** [comment]
bors r+

Perhaps this time it will work!

**Pull request merged**
