### PR TITLE
sql: adjust recently added logging events for txn row count guardrails

### LINKED ISSUE #69477: sql: the structured events produced by  `handleTxnRowsGuardrails` are defective and not ready for use by external users
## Problem description

Found while reviewing #67934. The field names `Limit`, `ViolatesTxnRowsLimitErr` and `IsRead` in the user-facing JSON events for telemetry are quite poor and should all be changed before we release this.

Also the description for `ViolatesTxnRowsLimitErr` is very confusing and not human-friendly.

I have tried to read the code to understand it and find better words. I failed.

I was relatively disappointed to see that the code inside function `handleTxnRowsGuardrails` is mixing and matching incoherent concepts—or, rather, the concepts may be coherent but the English words chosen to describe them are incomprehensible for an external reader, which will make this difficult to maintain. Additionally, I find the control flow  _much_ too complex for what this code is trying to achieve, which makes this double difficult to understand/maintain.

## Suggested resolution

I think there are two different actions that need to be taken:

1. we need to remove the current public fields from the structured events. Right now the explanation for them is too complicated and the fields will thus be unfit for consumption, so they might as well not exist. We can replace them in another PR later.

2. we should clarify the code in `handleTxnRowsGuardrails` with adequate explanatory comments, and perhaps a different choice of words for the various variables. Once this is clarified, I predict we will discover better words for the telemetry events.

I'm available to help for point two.

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: adjust txn rows written/read guardrails a bit**

Release note (ops change): the meaning of the recently introduced
`transaction_rows_written_err` and `transaction_rows_read_err` (as well
as the corresponding `_log` variables) have been adjusted a bit to
indicate the largest number of rows that is still allowed. In other
words, originally reaching the limit would result in an error, and now
only exceeding the limit would.

Release justification: low-risk adjustment to new functionality.

**sql: adjust recently added logging events for txn row count guardrails**

This commit refactors the recently introduced
`CommonTxnRowsLimitDetails` protobuf struct to make it more
user-friendly (since it is used for logging and errors). Namely, the
following changes are made:
- `Limit` is changed to `NumRows` making it easier to understand
- `ViolatesTxnRowsLimitErr` is removed since it is confusing
- `IsRead` is removed too since it is redundant (the types of logged
events contain the necessary "kind" information and this commit
extends the logic of errors to contain the "kind" info too) and is
confusing.

Additionally, we will no longer log twice if `_err` guardrail is reached
after `_log` was reached previously.

Fixes: #69477.

Release note: None (no release since this was introduced)

Release justification: an update to the new functionality.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @michae2)

___
*[pkg/sql/conn_executor_exec.go, line 1168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-Mj6d8eQ1PDZbB9Yy78q:-Mj6d8eQ1PDZbB9Yy78r:b-mrcuw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae562cb117a9372f436cb001e118a8b2910a9b04/pkg/sql/conn_executor_exec.go#L1168)):*
> ```Go
> 
> // handleTxnRowsGuardrails handles either "written" or "read" rows guardrails.
> func (ex *connExecutor) handleTxnRowsGuardrails(
> ```

I've stared at this method for quite some time, but I don't see how to make it less complex without duplicating logic (i.e. extracting separate methods for "external" vs "internal" executors, etc), so I'm looking forward to suggestions on how to improve here. Any comments that I could think of seemed quite obvious to me (maybe because I stared for too long).
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-Mj6chgBCTZ7MjnGMrHP:-Mj6chgBCTZ7MjnGMrHQ:be0llqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae562cb117a9372f436cb001e118a8b2910a9b04/pkg/util/log/eventpb/sql_audit_events.proto#L133)):*
> ```protobuf
>   // LimitValue indicates the value of the transaction row count limit that was
>   // reached.
>   int64 limit_value = 3 [(gogoproto.jsontag) = ",omitempty"];
> ```

I removed two of the fields Raphael mentioned in the issue, but I think it is worth keeping the "limit" field, so I renamed it, but I'm open to suggestions on the naming and/or comments.

**Review by michae2 — COMMENTED** [review]
I agree that `IsRead` was redundant with the event types, but I think I might have actually done the opposite :laughing: (that is, I would have unified the read/written event types into a single type, and kept a boolean field indicating whether this was rows read or written). That would simplify `handleTxnRowsGuardrails` a bit and also simplify any readers of the structured events. (But that's pretty subjective, I think what you've done here is also fine. Maybe @knz has a stronger opinion?)

Another idea for simplifying `handleTxnRowsGuardrails`: replace `LimitValue` with `NumRows` which then wouldn't require all the `logLimit =` and might be easier for a customer to understand.

@knz If you took issue with these structured events, then I wonder what you think of `CommonLargeRowDetails` used by `LargeRow` and `LargeRowInternal`? :thinking: Maybe we should also get rid of `ViolatesMaxRowSizeErr` in those events?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-:-Mj6oIduBotbZHnXeMKz:b-bv4z94)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-Mj6wRDi2vQv9wtDJDYT:-Mj6wRDi2vQv9wtDJDYU:ba7nn7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae562cb117a9372f436cb001e118a8b2910a9b04/pkg/sql/conn_executor_exec.go#L1205)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> 		if shouldErr {
> 			// But this time we also reached the error limit, so we want to log
> 			// an event again (it will have ViolatesTxnRowsLimitErr set to
> 			// true). Note that we couldn't have reached the error limit when we
> 			// logged the event the previous time because that would have
> 			// aborted the execution of the transaction.
> 			shouldLog = true
> 			logLimit = errLimit
> 		} else {
> ```
</details>


We could consider deleting this logic and moving the rest of this `alreadyLogged` check up above the `executorTypeInternal` check. I don't really think we have to log if `shouldErr` is true. And don't we already have a way to log all query errors?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the suggestions. I changed `LimitValue` to `NumRows`, but I prefer to keep the distinction between different error types so that the errors were more useful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-:-MjAEqk-9PsGr0Or9JQs:b8mmt02)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @michae2)

___
*[pkg/sql/conn_executor_exec.go, line 1168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-Mj6d8eQ1PDZbB9Yy78q:-MjAF8LxAns5XxzpsY7b:bam9qtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae562cb117a9372f436cb001e118a8b2910a9b04/pkg/sql/conn_executor_exec.go#L1168)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I've stared at this method for quite some time, but I don't see how to make it less complex without duplicating logic (i.e. extracting separate methods for "external" vs "internal" executors, etc), so I'm looking forward to suggestions on how to improve here. Any comments that I could think of seemed quite obvious to me (maybe because I stared for too long).
</blockquote></details>

Ok, I think the logic here is now pretty simple.
___
*[pkg/sql/conn_executor_exec.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-Mj6wRDi2vQv9wtDJDYT:-MjAFDtr1YAxtAED4it4:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae562cb117a9372f436cb001e118a8b2910a9b04/pkg/sql/conn_executor_exec.go#L1205)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 		if shouldErr {
> 			// But this time we also reached the error limit, so we want to log
> 			// an event again (it will have ViolatesTxnRowsLimitErr set to
> 			// true). Note that we couldn't have reached the error limit when we
> 			// logged the event the previous time because that would have
> 			// aborted the execution of the transaction.
> 			shouldLog = true
> 			logLimit = errLimit
> 		} else {
> ```

We could consider deleting this logic and moving the rest of this `alreadyLogged` check up above the `executorTypeInternal` check. I don't really think we have to log if `shouldErr` is true. And don't we already have a way to log all query errors?
</blockquote></details>

Thanks, done.

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-:-MjAl8941lSJncQqAbTV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[pkg/util/log/eventpb/sql_audit_events.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjAjZq94mdliEq7Vsya:-MjAjZq94mdliEq7Vsyb:b-5wko5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e1340e53e2b5984cf99ad415018e7c0817f4cc/pkg/util/log/eventpb/sql_audit_events.go#L63)):*
> ```Go
> func (d *CommonTxnRowsLimitDetails) Error(kind string) string {
> 	return fmt.Sprintf(
> 		"txn reached the number of rows %s (%d): TxnID %v SessionID %v",
> ```

nit: Now that we're using `NumRows` instead of `LimitValue` we should change this message to something more like `"txn %s %s rows, which is above the limit: TxnID %v SessionID %v"`.
___
*[pkg/util/log/eventpb/sql_audit_events.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjAkBMZ9rzvQF5EiUk-:-MjAkBMZ9rzvQF5EiUk0:b589p5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e1340e53e2b5984cf99ad415018e7c0817f4cc/pkg/util/log/eventpb/sql_audit_events.go#L79)):*
> ```Go
> 	if p.Detail() {
> 		p.Printf(
> 			"txn reached the number of rows %s (%d): TxnID %v SessionID %v",
> ```

Same nit here (message should be changed now that we're using `NumRows` instead of `LimitValue`).
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjAkWkm7jJD4k0NaLA6:-MjAkWkm7jJD4k0NaLA7:blsmknn) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e1340e53e2b5984cf99ad415018e7c0817f4cc/pkg/util/log/eventpb/sql_audit_events.proto#L131)):*
> ```protobuf
>   // SessionID is the ID of the session that initiated the transaction.
>   string session_id = 2 [(gogoproto.customname) = "SessionID", (gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];
>   // NumRows is the number of rows written/read (depending on the context) by
> ```

nit: Instead of "context" could we say "event type"?

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 1102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjArQ8T-aro3ZcMq7Xt:-MjArQ8T-aro3ZcMq7Xu:b67kpr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e1340e53e2b5984cf99ad415018e7c0817f4cc/pkg/sql/conn_executor_exec.go#L1102)):*
> ```Go
> }
> 
> const writtenKind = "written"
> ```

nit: Is this used anywhere? I would be fine with using string literals directly in both `SafeFormatError` methods. Also if you take my message-changing suggestion then you should also change this to "wrote" :slightly_smiling_face:

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @michae2)

___
*[pkg/sql/conn_executor_exec.go, line 1102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjArQ8T-aro3ZcMq7Xt:-MjAzyZu2f5ySHidW6-t:byjkbe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e1340e53e2b5984cf99ad415018e7c0817f4cc/pkg/sql/conn_executor_exec.go#L1102)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Is this used anywhere? I would be fine with using string literals directly in both `SafeFormatError` methods. Also if you take my message-changing suggestion then you should also change this to "wrote" :slightly_smiling_face:
</blockquote></details>

Inlined the literals but kept "written" by rephrasing your suggestion.
___
*[pkg/util/log/eventpb/sql_audit_events.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjAjZq94mdliEq7Vsya:-MjB-4ZZ-2gDOwSY5MTh:bo3hy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/33e1340e53e2b5984cf99ad415018e7c0817f4cc/pkg/util/log/eventpb/sql_audit_events.go#L63)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Now that we're using `NumRows` instead of `LimitValue` we should change this message to something more like `"txn %s %s rows, which is above the limit: TxnID %v SessionID %v"`.
</blockquote></details>

Good point, done. I added another commit to adjust the meaning of the rows written/read guardrails to be more intuitive (which allow for being precise while using your suggestion).

**Review by michae2 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-:-MjBa7wMBawcK0iwzkG3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by yuzefovich** [comment]
I think the concerns raised by Raphael have been addressed, so I'm merging this.

TFTR!

bors r+

**Review by knz — COMMENTED** [review]
LGTM on the logging event, but I just noticed something
- incorrect/superfluous use of `p.Detail` in a `SafeFormat` method
- naming for the cluster settings

> Reviewed 11 of 11 files at r3, 8 of 8 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-:-MjE8_mh12tCIVR3jIAn:b-jujj4a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 1110 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE8EyT6tlQy2QZWVwm:-MjE8EyT6tlQy2QZWVwn:bsenmdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3460a19f184bf7611e0194124c6b859c179208b8/pkg/sql/conn_executor_exec.go#L1110)):*
> ```Go
> // implements.
> func (e *txnRowsWrittenLimitErr) Error() string {
> 	return e.CommonTxnRowsLimitDetails.Error("written")
> ```

`return errors.Sprintf("%v", e)`
___
*[pkg/sql/exec_util.go, line 602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE7-4q882Mad6D-3jx:-MjE7-4r-_U-yT31jShg:b3csqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/sql/exec_util.go#L602)):*
> ```Go
> 
> var txnRowsWrittenLog = settings.RegisterIntSetting(
> 	"sql.defaults.transaction_rows_written_log",
> ```

`sql.defaults.transaction_max_rows.writes.logging_threshold`
___
*[pkg/sql/exec_util.go, line 611 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE762u1UzwNzEU6S5j:-MjE762u1UzwNzEU6S5k:b-jjmzae) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/sql/exec_util.go#L611)):*
> ```Go
> 
> var txnRowsWrittenErr = settings.RegisterIntSetting(
> 	"sql.defaults.transaction_rows_written_err",
> ```

`sql.defaults.transaction_max_rows.writes.force_abort_threshold`
___
*[pkg/sql/exec_util.go, line 620 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE7JYS97DZlwSuL_Zx:-MjE7JYS97DZlwSuL_Zy:b-6f71wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/sql/exec_util.go#L620)):*
> ```Go
> 
> var txnRowsReadLog = settings.RegisterIntSetting(
> 	"sql.defaults.transaction_rows_read_log",
> ```

`sql.defaults.transaction_max_rows.reads.logging_threshold`
___
*[pkg/sql/exec_util.go, line 629 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE7NikCVLTnG0_bjQp:-MjE7NikCVLTnG0_bjQq:b-nnl2f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/sql/exec_util.go#L629)):*
> ```Go
> 
> var txnRowsReadErr = settings.RegisterIntSetting(
> 	"sql.defaults.transaction_rows_read_err",
> ```

`sql.defaults.transaction_max_rows.reads.force_abort_threshold`
___
*[pkg/util/log/eventpb/sql_audit_events.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE7UKHCMP4lqijvW-u:-MjE7UKHCMP4lqijvW-v:b-ichk4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/util/log/eventpb/sql_audit_events.go#L73)):*
> ```Go
> // Error is part of the error interface, which CommonTxnRowsLimitDetails
> // implements.
> func (d *CommonTxnRowsLimitDetails) Error() string {
> ```

simpler: `return fmt.Sprintf("%v", d)`
which will automatically cascade to `Format` and `SafeFormatError` below.
___
*[pkg/util/log/eventpb/sql_audit_events.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE7vE-AjdJyd0_Pf1V:-MjE7vE-AjdJyd0_Pf1W:b-bo1n3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/util/log/eventpb/sql_audit_events.go#L95)):*
> ```Go
> // CommonTxnRowsLimitDetails implements.
> func (d *CommonTxnRowsLimitDetails) SafeFormatError(p errors.Printer) (next error) {
> 	if p.Detail() {
> ```

I'd remove `if p.Detail()` since the details are meant to be included in the base case.
___
*[pkg/util/log/eventpb/sql_audit_events.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE8-yF50B0pozxibGk:-MjE8-yF50B0pozxibGl:b-qqz1s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/util/log/eventpb/sql_audit_events.go#L98)):*
> ```Go
> 		p.Printf(
> 			"txn exceeded the number of rows %s (%d): TxnID %v SessionID %v",
> 			d.kind(), d.Limit, redact.SafeString(d.TxnID), redact.SafeString(d.SessionID),
> ```

I'm pretty sure you do not need `redact.SafeString` here? I thought the transaction and session IDs are already safe types?

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69945)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE7-4q882Mad6D-3jx:-MjFZZHk4fcpazIbFqJ1:b8w44us) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/sql/exec_util.go#L602)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`sql.defaults.transaction_max_rows.writes.logging_threshold`
</blockquote></details>

This would make the corresponding session setting `transaction_max_rows.writes.logging_threshold` which would be the first session setting with periods in its name.

Some background: the names originally came from [this document](https://docs.google.com/document/d/1fWQ-c8YT_JJiupOze55xZ3nyrz2wGTtJ7TJKRqh0tnQ/edit#heading=h.9rr55wu16wqk) and were then discussed [here](https://github.com/cockroachdb/cockroach/pull/69202#issuecomment-904278949) and [here](https://github.com/cockroachdb/cockroach/pull/69202#pullrequestreview-737707029) and [here](https://github.com/cockroachdb/cockroach/pull/69202#pullrequestreview-737789942). We decided to keep these names to avoid adding session settings with periods.

These cluster settings were not named in isolation, they match:
- the corresponding session settings (e.g. `transaction_rows_written_log`)
- the corresponding metrics (e.g. `sql.guardrails.transaction_rows_written_log.count`)
- the large row cluster settings (e.g. `sql.guardrails.max_row_size_log`) which were [renamed](https://github.com/cockroachdb/cockroach/pull/69457) to match these names
- the large row metrics (e.g. `sql.guardrails.max_row_size_log.count`)

We've already had sign-offs from @vy-ton and @rytaft on the existing names, and the customer who requested the feature has already seen them. And I've already started [backporting](https://github.com/cockroachdb/cockroach/pull/69946) the large row guardrails. I'm reluctant for us to do additional bikeshedding at this point.
___
*[pkg/util/log/eventpb/sql_audit_events.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69945#-MjE8-yF50B0pozxibGk:-MjFvPKCD3TKThD3AMeL:b-1nawk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f68a17f935cbe1daf77a764f341adf01983ed2/pkg/util/log/eventpb/sql_audit_events.go#L98)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm pretty sure you do not need `redact.SafeString` here? I thought the transaction and session IDs are already safe types?
</blockquote></details>

`TxnID` and `SessionID` are plain old strings in `CommonTxnRowsLimitDetails`.

**Comment by knz** [comment]
ok thanks for explaining

**Comment by knz** [comment]
I'm still interested in a followup to the `p.Detail` call though

**Comment by michae2** [comment]
> I'm still interested in a followup to the `p.Detail` call though

I'm creating a PR to remove `CommonLargeRowDetails.ViolatesMaxRowSizeErr`, I will take a look at it in that PR, since `CommonLargeRowDetails.SafeFormatError` likely has the same issues.

**Pull request merged**
