### PR TITLE
sql: implement SHOW PROCEDURES

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/parser: add tests for SHOW FUNCTIONS

Release note: None

#### sql/parser: parse SHOW PROCEDURES statements

This commit updates the parser so that it can parse `SHOW PROCEDURES`
statements.

Release note: None

#### sql/sem/tree: rename ShowFunctions to ShowRoutines

Release note: None

#### sql: fix pg_proc.prokind column for procedures

This commit corrects the `pg_proc.prokind` column so that it has the
value `"p"` for rows representing procedures.

Release note: None

#### sql: implement SHOW PROCEDURES

This commit adds execution support for the `SHOW PROCEDURES` statement.

Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first 5 commits are from #111808.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 10 of 10 files at r1, 7 of 7 files at r2, 12 of 12 files at r3, 31 of 31 files at r4, 41 of 41 files at r5, 1 of 1 files at r6, 11 of 11 files at r7, 5 of 5 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111944#-:-Ng5sBdX2uezOdXJFlIe:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @rharding6373)

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111944#-:-Ng6WYWC-TOjOLRLU_bv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @jayshrivastava, and @rhu713)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
