### PR TITLE
server: secure init service cert rotation

### PR DESCRIPTION
**Pull request by aaron-crl**
Part of #60632 .

Release justification: low risk, feature completion for #60632.

Added certificate rotation functionality and some test cases. Fixed several bugs related to path checks that rotation depends on.

Adjustments to automatic certificate generation lifespan and key sizes to bring them in alignment with existing defaults.

### CODE REVIEW

**Comment by aaron-crl** [comment]
It's worth noting this only adds a function for rotation. It does not plumb it to a scheduler yet.

**Review by knz — COMMENTED** [review]
Mostly good to go, a few nits.

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-:-MUdauu92wH24twzGWZs:byl28ck)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @itsbilal)

___
*[pkg/security/auto_tls_init.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUd_-Aj9TlBMcp3ajPk:-MUd_-Ak19bF-gCW2UJ-:bclobwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dba7763902b0b4bac201647a66cf6ba16e10cb77/pkg/security/auto_tls_init.go#L43)):*
> ```Go
> 	max.Exp(big.NewInt(2), big.NewInt(130), nil).Sub(max, big.NewInt(1))
> 
> 	// Serials is set using rand.Int which yields a value between [0, max)
> ```

nit (in 1st commit): serials "are" not "is"
it's corrected in the last commit but each commit should be self sufficient.
___
*[pkg/server/auto_tls_init.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUd_J-G4fnzx-n9trJM:-MUd_J-G4fnzx-n9trJN:b-i40ait) ([raw file](https://github.com/cockroachdb/cockroach/blob/dba7763902b0b4bac201647a66cf6ba16e10cb77/pkg/server/auto_tls_init.go#L477)):*
> ```Go
> ) error {
> 	// TODO(aaron-crl): Possibly add a warning to the log that a CA was not
> 	// found
> ```

nit: period at end.
___
*[pkg/server/auto_tls_init_test.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUda0TvA83l6nx16AaS:-MUda0TvA83l6nx16AaT:b9pk2uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L112)):*
> ```Go
> 	cmp(
> 		cb1.InterNode.CACertificate,
> 		cb2.InterNode.CACertificate, "InterNodeCA cert")
> ```

here and below, prefer to use the constants that are now declared in global scope.
___
*[pkg/server/auto_tls_init_test.go, line 221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUda8I3EojoQqjbw8Xc:-MUda8I3EojoQqjbw8Xd:b-i40aj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L221)):*
> ```Go
> // TestNodeCertRotation tests that the rotation function will overwrite the
> // expected certificates and fail if they are not there.
> // TODO(aaron-crl): correct this
> ```

nit: period at end 
___
*[pkg/server/auto_tls_init_test.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdaCHV7INKYF4zwNXf:-MUdaCHV7INKYF4zwNXg:bxy1jb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L222)):*
> ```Go
> // expected certificates and fail if they are not there.
> // TODO(aaron-crl): correct this
> func TestRotationOnUnintializedNode(t *testing.T) {
> ```

here and all new tests below:
```
defer leaktest.AfterTest(t)()
```

on the first line
___
*[pkg/server/auto_tls_init_test.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdaJHc-1jatMeJiINX:-MUdaJHc-1jatMeJiINY:bf5n9qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L238)):*
> ```Go
> 	dir, err := os.Open(cfg.SSLCertsDir)
> 	if err != nil {
> 		t.Fatalf("failed to open cfg.SSLCertsDir: %q", cfg.SSLCertsDir)
> ```

report the error in the message
___
*[pkg/server/auto_tls_init_test.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdaGKHE1xrbCMmtAC0:-MUdaGKHE1xrbCMmtAC1:b-p65uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L239)):*
> ```Go
> 	if err != nil {
> 		t.Fatalf("failed to open cfg.SSLCertsDir: %q", cfg.SSLCertsDir)
> 	}
> ```

`defer dir.Close()` here and remove the call below.

**Review by aaron-crl — COMMENTED** [review]
Cleaned up nits - I think. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-:-MUdnTfe0VYIDut_yQ7B:bwhcgjn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @knz)

___
*[pkg/security/auto_tls_init.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUd_-Aj9TlBMcp3ajPk:-MUdmcWX-nPb5SGTis9K:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/dba7763902b0b4bac201647a66cf6ba16e10cb77/pkg/security/auto_tls_init.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit (in 1st commit): serials "are" not "is"
it's corrected in the last commit but each commit should be self sufficient.
</blockquote></details>

Thanks, done.
___
*[pkg/server/auto_tls_init.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUd_J-G4fnzx-n9trJM:-MUdmk-m65OwYch6oYsn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dba7763902b0b4bac201647a66cf6ba16e10cb77/pkg/server/auto_tls_init.go#L477)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: period at end.
</blockquote></details>

Done.
___
*[pkg/server/auto_tls_init_test.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUda0TvA83l6nx16AaS:-MUdmnFPDaAn_8RWXa_Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here and below, prefer to use the constants that are now declared in global scope.
</blockquote></details>

Done.
___
*[pkg/server/auto_tls_init_test.go, line 221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUda8I3EojoQqjbw8Xc:-MUdnPaH1xmO5-QzXZDS:bn9az7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L221)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: period at end 
</blockquote></details>

This was a spurious TODO.
___
*[pkg/server/auto_tls_init_test.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdaCHV7INKYF4zwNXf:-MUdnNYX4ZP-7vEu_IfD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L222)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here and all new tests below:
```
defer leaktest.AfterTest(t)()
```

on the first line
</blockquote></details>

Done.
___
*[pkg/server/auto_tls_init_test.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdaJHc-1jatMeJiINX:-MUdnKMp5UbBhYlcx_Yq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L238)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

report the error in the message
</blockquote></details>

Done.
___
*[pkg/server/auto_tls_init_test.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdaGKHE1xrbCMmtAC0:-MUdnMfEC2uSAVRa8Zck:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbe63447e161a6341467db82c49d62ec154938b/pkg/server/auto_tls_init_test.go#L239)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`defer dir.Close()` here and remove the call below.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: if CI passes

> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-:-MUdoCFK7JXO2JWtRj66:b470e91)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl and @itsbilal)

___
*[pkg/server/auto_tls_init_test.go, line 240 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdo7HL3fRyTjsYjmx1:-MUdo7HM3Uk2LunneEit:b-q5x3gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eb78406ec257f5d87ba9daa2990300665f35b7a/pkg/server/auto_tls_init_test.go#L240)):*
> ```Go
> 	if err != nil {
> 		t.Fatalf(
> 			"failed to open cfg.SSLCertsDir: %q with err: %q",
> ```

nit: it's customary to report errors with `%v` not `%q`

**Review by aaron-crl — COMMENTED** [review]
Fixed a few linter gripes. Waiting for CI.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-:-MUe--PK5Wmz3J-GdXwo:b7aeswk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @knz)

___
*[pkg/server/auto_tls_init_test.go, line 240 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61233#-MUdo7HL3fRyTjsYjmx1:-MUdzxPw0M4sIU3jaH-X:b-x52gbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eb78406ec257f5d87ba9daa2990300665f35b7a/pkg/server/auto_tls_init_test.go#L240)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: it's customary to report errors with `%v` not `%q`
</blockquote></details>

Thanks, fixed.

**Pull request merged**
