### PR TITLE
#5801 gossip: code rot in resolvers, remove references to http-lb and unix

### PR DESCRIPTION
**Pull request by a-s8h**
For #5801

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5956)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: Thanks for tackling this.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[gossip/resolver/resolver.go, line 44 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEsQB-XgU-jUtEzCVRf:-KEsQB-XgU-jUtEzCVRg:498596981) ([raw file](https://github.com/cockroachdb/cockroach/blob/f697fe61c30de30630aa5c77ec6f86e22d41c118/gossip/resolver/resolver.go#L44)):*
This line should be deleted as well (it went with the `http-lb` comment).

---

*[gossip/resolver/resolver.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEsQEFzi2dCBPnBT2EN:-KEsQEFzi2dCBPnBT2EO:1662488377) ([raw file](https://github.com/cockroachdb/cockroach/blob/f697fe61c30de30630aa5c77ec6f86e22d41c118/gossip/resolver/resolver.go#L45)):*
I think we only use the `tcp=` prefix in tests. Probably worth removing it as well.

---

*[gossip/resolver/socket.go, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEsPiqmqa8laSBFGko7:-KEsPiqmqa8laSBFGko8:1863827877) ([raw file](https://github.com/cockroachdb/cockroach/blob/f697fe61c30de30630aa5c77ec6f86e22d41c118/gossip/resolver/socket.go#L47)):*
Do you mind removing the `exhausted` field? It is no longer used. I simply missed removing it in an earlier change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-:-KEsQbTxDNjnSzB_KmLs:870070330)*

**Comment by tamird** [comment]
:lgtm: but i think there's more we can remove here.

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[gossip/resolver/resolver.go, line 44 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEshkVWPRLJtQt4cAQ1:-KEshkVXVvPAbZtjP7-F:577756429) ([raw file](https://github.com/cockroachdb/cockroach/blob/cacc891d9edc9139ac3152f2e0140a3ce527e79b/gossip/resolver/resolver.go#L44)):*
all this `spec` logic is ripe for removal, too. i believe we never pass anything other than addresses in practice.

---

*[gossip/resolver/resolver.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEshv4Gnjn3FPi9bdwF:-KEshv4Gnjn3FPi9bdwG:-1948147239) ([raw file](https://github.com/cockroachdb/cockroach/blob/cacc891d9edc9139ac3152f2e0140a3ce527e79b/gossip/resolver/resolver.go#L64)):*
`validTypes` now has just one member which is also the default and never specified explicitly. ripe for removal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-:-KEsiHMlo95dJRPS3kPD:-830306308)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956)*

**Comment by Yogendrovich** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gossip/resolver/resolver.go, line 44 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEsQB-XgU-jUtEzCVRf:-KF3wu_7Iy7od1vFm3I5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f697fe61c30de30630aa5c77ec6f86e22d41c118/gossip/resolver/resolver.go#L44)):*
Done.

---

*[gossip/resolver/resolver.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEsQEFzi2dCBPnBT2EN:-KF3wtKNX7t_1IY03FZz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f697fe61c30de30630aa5c77ec6f86e22d41c118/gossip/resolver/resolver.go#L45)):*
Done.

---

*[gossip/resolver/socket.go, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956#-KEsPiqmqa8laSBFGko7:-KF3we2VYHzkMhGgMFjL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f697fe61c30de30630aa5c77ec6f86e22d41c118/gossip/resolver/socket.go#L47)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5956)*

**Comment by petermattis** [comment]
Thanks @Yogendrovich.

**Pull request merged**
