### PR TITLE
Revert "Revert "util/log: more misc cleanups""

### LINKED ISSUE #57161: cli: TestZipSpecialNames failed
[(cli).TestZipSpecialNames failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2475364&tab=buildLog) on [master@fe5da5c2df069dc7f820f5c3e2f3e03f1cb7b661](https://github.com/cockroachdb/cockroach/commits/fe5da5c2df069dc7f820f5c3e2f3e03f1cb7b661):

```
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706 +0x124
  github.com/cockroachdb/cockroach/pkg/server.(*Node).recordJoinEvent.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:790 +0x4f4
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:222 +0x1de

Goroutine 373 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1345 +0x3b3
  github.com/cockroachdb/cockroach/pkg/cli_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/pkg/cli/main_test.go:34 +0xaf
  main.main()
      _testmain.go:217 +0x271

Goroutine 845 (finished) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xc4
  github.com/cockroachdb/cockroach/pkg/server.(*Node).recordJoinEvent()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:784 +0x1c4
  github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1735 +0x4edc
  github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1622 +0x43a5
  github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1048 +0x50
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:410 +0x92
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:318 +0xc5
  github.com/cockroachdb/cockroach/pkg/cli.newCLITest()
      /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli_test.go:152 +0x437
  github.com/cockroachdb/cockroach/pkg/cli.TestZipSpecialNames()
      /go/src/github.com/cockroachdb/cockroach/pkg/cli/zip_test.go:145 +0x1e4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
==================
CREATE TABLE
[debug --host=127.0.0.1:40163 --insecure=false --certs-dir=/go/src/github.com/cockroachdb/cockroach/artifacts/cli-test866458830 zip --cpu-profile-duration=0 /dev/null]
W201126 06:26:50.045421 195280 sql/sqlliveness/slinstance/slinstance.go:181 ⋮ [n1] exiting heartbeat loop
W201126 06:26:50.046501 195281 jobs/registry.go:687 ⋮ canceling all adopted jobs due to stopper quiescing
    testing.go:1038: race detected during execution of test
--- FAIL: TestZipSpecialNames (21.74s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestZipSpecialNames PKG=./pkg/cli TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestZipSpecialNames.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #57162: sql/pgwire: TestConnResultsBufferSize failed
[(sql/pgwire).TestConnResultsBufferSize failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2475894&tab=buildLog) on [master@fe5da5c2df069dc7f820f5c3e2f3e03f1cb7b661](https://github.com/cockroachdb/cockroach/commits/fe5da5c2df069dc7f820f5c3e2f3e03f1cb7b661):

```
  github.com/cockroachdb/cockroach/pkg/sql.cleanupAndFinishOnError()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_fsm.go:472 +0x127
  github.com/cockroachdb/cockroach/pkg/util/fsm.Transitions.apply()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:106 +0x203
  github.com/cockroachdb/cockroach/pkg/util/fsm.(*Machine).ApplyWithPayload()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:135 +0x2db
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2215 +0xd2
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1591 +0xe64
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1372 +0x40c
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:481 +0x139
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626 +0x3a4

Goroutine 177 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1345 +0x3b3
  github.com/cockroachdb/cockroach/pkg/sql/pgwire_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/main_test.go:33 +0xdb
  main.main()
      _testmain.go:171 +0x271

Goroutine 242 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:554 +0x1f7
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:280 +0x8e4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:154 +0x30a
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:589 +0xa84
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1964 +0x1a4
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:148 +0x11d
==================
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestConnResultsBufferSize324537989
    testing.go:1038: race detected during execution of test
--- FAIL: TestConnResultsBufferSize (0.73s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestConnResultsBufferSize PKG=./pkg/sql/pgwire TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestConnResultsBufferSize.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by knz**
Reverts  #57178. 

This re-instates #57000, as it did not "introduce a race in crdb"
The description in #57178 was incorrect - instead #57161 / #57162 merely outlined a bug in some tests, which remains to be fixed.

This PR also includes a temporary workaround for said test bug.

Fixes #57162. 
Fixes #57161 (presumably - although the symptoms there don't align).

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 59 of 59 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57222#-:-MNOlO-61HWKYdobSw83:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @irfansharif)

**Review by irfansharif — APPROVED** [review]
Woops, sorry about the misattribution, just friday evening laziness. LGTM (though I think we want to re-order these commits for git bisectability).

**Comment by knz** [comment]
The two commits cannot be inverted - the 2nd commit works around the bug in the test within the context set up by the 1st commit.

**Comment by knz** [comment]
TFYR

bors r=irfansharif

**Pull request merged**
