### PR TITLE
stats: enable histogram collection by default

### PR DESCRIPTION
**Pull request by rytaft**
This commit enables collection of histograms by default, as well as
their use by the optimizer, by changing the default value of the
cluster setting `sql.stats.histogram_collection.enabled` to true.
To disable collection and use of histograms, users can set the cluster
setting `sql.stats.histogram_collection.enabled` to false.

Testing has shown that the performance impact of histograms on both
TPC-C and KV workloads is negligible.

Release note (sql change): enabled collection of histograms by default
during automatic statistics collection.

### CODE REVIEW

**Comment by awoods187** [comment]
Exciting stuff! Is that both KV0 and KV95?

**Comment by rytaft** [comment]
Thanks! Just KV95 -- I can also test KV0 if you think it would be helpful, but I don't expect the results to be different.

**Comment by awoods187** [comment]
I don't think its needed was just wondering

**Comment by RaduBerinde** [comment]
Very cool, awesome work getting here! LGTM

**Review by andy-kimball — COMMENTED** [review]
Yes, nice milestone. Thanks for doing the due diligence to minimize the perf risk of turning these on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39743#-:-LmfcWyYBERD7WAsxTHL:b374tdt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Comment by rytaft** [comment]
Thanks!

bors r+

**Pull request merged**
