### PR TITLE
storage/concurrency: benchmark for lockTable

### PR DESCRIPTION
**Pull request by sumeerbhola**
Most of the allocations in lockTable are due to the temporary
*lockState created for btree lookup. And the total bytes allocated
is roughly equal to the bytes allocated by
spanlatch.allocGuardAndLatches in the contended benchmarks.
The cpu is mostly in runtime.mcall, in pthread_cond_wait and
pthread_cond_signal.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: this looks really good. Do you mind posting the results to the PR and in the commit message? Ideally, you'd run with `-benchmem` and then pass the output to `benchstat`.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-:-M-q29FBBe5SLA7eKCiq:b-q52jtx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/concurrency/lock_table_test.go, line 998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-M-q0YSKDo225tY41lyL:-M-q0YSKDo225tY41lyM:bpw3hsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9db223917246c032f1f5ffb10e4d284db412f26/pkg/storage/concurrency/lock_table_test.go#L998)):*
> ```
> &item.Txn.TxnMeta
> ```

This will allocate if we don't pass `benchWorkItem` in as a pointer to this function.

To do this, switch:
```
go doBenchWork(items[i], env, requestDoneCh)
```

with
```
go doBenchWork(&items[i], env, requestDoneCh)
```
___
*[pkg/storage/concurrency/lock_table_test.go, line 1003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-M-q0rEe9BHqe5YE3vOd:-M-q0rEe9BHqe5YE3vOe:bnx7p2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9db223917246c032f1f5ffb10e4d284db412f26/pkg/storage/concurrency/lock_table_test.go#L1003)):*
> ```Go
> 		}
> 	}
> 	env.lm.Release(lg)
> ```

Was there a reason you're acquiring latches regardless of whether there are any locks to acquire or not?

**Review by sumeerbhola — COMMENTED** [review]
> Do you mind posting the results to the PR and in the commit message? Ideally, you'd run with -benchmem and then pass the output to benchstat.

Done. There isn't any before number to compare with using `benchstat`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-:-M-qC19VE6IWbnihwrnY:bvtj8ke)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/concurrency/lock_table_test.go, line 998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-M-q0YSKDo225tY41lyL:-M-q9z9mBzXJoMlEk3SD:bqromw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9db223917246c032f1f5ffb10e4d284db412f26/pkg/storage/concurrency/lock_table_test.go#L998)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> &item.Txn.TxnMeta
> ```

This will allocate if we don't pass `benchWorkItem` in as a pointer to this function.

To do this, switch:
```
go doBenchWork(items[i], env, requestDoneCh)
```

with
```
go doBenchWork(&items[i], env, requestDoneCh)
```
</blockquote></details>

Done.
How do I get escape analysis output for the test itself? When I do `go build -gcflags "-m -m"` it does not produce anything for `lock_table_test.go`.
___
*[pkg/storage/concurrency/lock_table_test.go, line 1003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-M-q0rEe9BHqe5YE3vOd:-M-qAbwz5H0rvRfWmB3D:b7e94k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9db223917246c032f1f5ffb10e4d284db412f26/pkg/storage/concurrency/lock_table_test.go#L1003)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was there a reason you're acquiring latches regardless of whether there are any locks to acquire or not?
</blockquote></details>

Oversight. Fixed.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44964)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/concurrency/lock_table_test.go, line 1112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-M-qTAwB9-5cffuROE3o:-M-qTAwB9-5cffuROE3p:bk806fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/046fa890eb42560c9ac3060043f774a4dfa7072f/pkg/storage/concurrency/lock_table_test.go#L1112)):*
> ```Go
> // RunParallel() -- it doesn't seem possible to get parallelism between these
> // two values when using B.RunParallel() since B.SetParallelism() accepts an
> // integer multiplier to GOMAXPROCS.
> ```

btw, do we have an existing test framework to do better than this?
I was first going to vary the concurrency in smaller increments and have a shared variable incremented by the goroutine for each group and when one of them detects the total count has been reached it would signal (via closing a shared channel) to all the other groups. It was more code so I did the simpler thing here.

**Review by nvb — COMMENTED** [review]
:lgtm:

> There isn't any before number to compare with using benchstat.

That's fine, it is still useful with only a single point of comparison because it aggregates across trials.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-:-M-qTIv1A5xR_Y3M69eh:b-p7zmbk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/concurrency/lock_table_test.go, line 998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-M-q0YSKDo225tY41lyL:-M-qTj2Z-YjBQLp09HLj:bq1syon) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9db223917246c032f1f5ffb10e4d284db412f26/pkg/storage/concurrency/lock_table_test.go#L998)):*
> How do I get escape analysis output for the test itself? When I do go build -gcflags "-m -m" it does not produce anything for lock_table_test.go.

`go test -gcflags "-m -m"` should give you what you want, but I've never used that so I might be mistaken.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44964)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/concurrency/lock_table_test.go, line 1112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44964#-M-qTAwB9-5cffuROE3o:-M-qUv7U9rbjCh048YRa:b-kf735f) ([raw file](https://github.com/cockroachdb/cockroach/blob/046fa890eb42560c9ac3060043f774a4dfa7072f/pkg/storage/concurrency/lock_table_test.go#L1112)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

btw, do we have an existing test framework to do better than this?
I was first going to vary the concurrency in smaller increments and have a shared variable incremented by the goroutine for each group and when one of them detects the total count has been reached it would signal (via closing a shared channel) to all the other groups. It was more code so I did the simpler thing here.
</blockquote></details>

I'm not aware of any test framework for doing this. We generally don't use `B.RunParallel`, in part because of the integer limitation you pointed out here. Instead, we usually just do our own thing with `WaitGroup`s and a manual division of work between each goroutine.

**Pull request merged**
