### PR TITLE
sql: add storage iteration stats to fingerprint stats tables

### LINKED ISSUE #77580: sql: surface pebble internal iterator stats for scans
#77512 exposed Pebble's internal scan stats for iterators. The stats are sent back via tracing.

These stats can be surfaced in:
* `EXPLAIN ANALYZE` 
* `execution_statistics` field in the statement statistics

Jira issue: CRDB-13663

### PR DESCRIPTION
**Pull request by ericharmeling**
Related to https://github.com/cockroachdb/cockroach/issues/72048.
Fixes https://github.com/cockroachdb/cockroach/issues/77580.

This PR adds storage iteration stats from tracing to internal
`{statement,transaction}_statistics` tables.

Release note (sql change): The internal `statement_statistics` and
`transaction_statistics` tables now include sampled execution statistics
on storage iteration.

### CODE REVIEW

**Comment by ericharmeling** [comment]
Re: https://github.com/cockroachdb/cockroach/issues/71351, here are some `tpcch_concurrency` benchmark results on https://github.com/cockroachdb/cockroach/pull/96016/commits/80de3dbf521b56c1a4953cba2700a3dd00ef7ab7 (with the default sample rate `0.01`):

```
79, 82, 99, 94, 78
```

Comparing this with the [nightly `tpcch_concurrency` on master `roachperf`](https://roachperf.crdb.dev/?filter=&view=tpch_concurrency&tab=gce) that's been hovering around 80 [60,100] since 10/2022, I don't see a lot of evidence to suggest that adding additional fields to exec stats is having much of an added impact on memory usage *beyond the regression already reported in https://github.com/cockroachdb/cockroach/issues/71351 due to exec stats collection*.

As a result, I think we might want to move forward with the first approach laid out in [72048](https://github.com/cockroachdb/cockroach/issues/72048#issuecomment-1400618652) (or something similar):

> 1. Add all iterator stats sampled from tracing to exec stats (i.e., resolve https://github.com/cockroachdb/cockroach/issues/77580).
> 1. Add status endpoint functions to process relevant iterator stats (i.e., PointCount/PointsCoveredByRangeTombstones) for exposure to the statement_statistics and transaction_statistics tables.
> 1. Add new column(s) to SQL Activity page for relevant storage stats.

**Review by maryliag — COMMENTED** [review]
Although the level of detail is great, it would probably be too overwhelming for users and hard to understand. The end goal is to show % of live data, so you don't need to be too granular to what the MVCC is. Create just one value and add all the ones from your list 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-:-NN3cVXx6Ezi4Tfn5VvY:bmrrmlk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @yuzefovich)

**Comment by yuzefovich** [comment]
Re: benchmarking of `tpch_concurrency`: the fact that this PR doesn't change the numbers is expected - adding already-collected information into new fields in the protos is cheap. I believe the main impact of #64503 was in the collection phase, i.e. where we call `recordIteratorStats` in `storage` package where we allocate `roachpb.ScanStats` object on every call (and we can have thousands or more calls per query).

I see that this PR is marked as draft, so I haven't reviewed it. Please ping me when it is RFAL.

I also agree with Marylia that this level of detail might be too much (I'd guess even most CRDB engineers wouldn't be able to meaningfully utilize the newly-added fields). Perhaps it's worth collaborating with someone from the storage team to come up with a handful of useful statistics there. I think recently a large comment about these details was merged somewhere in the codebase.

**Review by ericharmeling — COMMENTED** [review]
Thanks for the feedback!

I briefly chatted with @sumeerbhola, and then with @kevin-v-ngo, and @maryliag, and it looks like the best path forward is to expose all of the storage iteration stats in the internal execution statistics tables where advanced users/L2s can find them, and then provide documentation on how to interpret the stats. In a future PR, [we can pare down the stats or derive some other statistic in the status server](https://github.com/cockroachdb/cockroach/issues/72048#issuecomment-1400618652), for exposure to the Console.

I've updated this PR to add the stats to the `crdb_internal.node_{transaction,statement}_statistics` tables, and then surface them in the `crdb_internal.{transaction,statement}_statistics` and `system.{transaction,statement}_statistics` tables under `statistics->'execution_statistics'->'mvcc_iterator_stats'`. I've also added some high-level comments that point to internal storage docs.

The PR should now resolve #77580, but not #72048. After this PR is merged, we'll need to properly document the meaning of these stats in the most common cases in our user-facing docs. 

>  I believe the main impact of #64503 was in the collection phase, i.e. where we call recordIteratorStats in storage package where we allocate roachpb.ScanStats object on every call (and we can have thousands or more calls per query).

@yuzefovich Thank you for clarifying that for me :grin: . With that context, the benchmark results make more sense. Given that the stats are already collected, this PR should help surface them more easily, at little cost. I think these changes are RFAL at this point.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-:-NN7Djv_DjNRUAuUasjo:b-kchuo4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo, @sumeerbhola, and @yuzefovich)

**Review by maryliag — COMMENTED** [review]
> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @kevin-v-ngo, @sumeerbhola, and @yuzefovich)

___
*[`pkg/sql/appstatspb/app_stats.proto` line 342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmhdP_3BYGv5TOv6BO:-NNmhdP_3BYGv5TOv6BP:be9gbyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/appstatspb/app_stats.proto#L342)):*
> ```protobuf
> 
>   // Internal storage iteration statistics.
>   optional MvccIteratorStats mvcc_iterator_stats = 8 [(gogoproto.nullable) = false];
> ```

nit: MVCCIteratorStats, you can also add that as the custom name for this parameter
___
*[`pkg/sql/appstatspb/app_stats.proto` line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmhmBhD8R0Caglbjtj:-NNmhmBhD8R0Caglbjtk:bjiwm26) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/appstatspb/app_stats.proto#L367)):*
> ```protobuf
> 
> // Internal storage iteration statistics.
> message MvccIteratorStats {
> ```

nit: MVCCIteratorStats
___
*[`pkg/sql/appstatspb/app_stats.proto` line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmhuy7E6U1Ocyr_dkC:-NNmhuy7E6U1Ocyr_dkD:bws4omi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/appstatspb/app_stats.proto#L369)):*
> ```protobuf
> message MvccIteratorStats {
> 
>   // StepCount collects the number of times the iterator moved forward or backward over the
> ```

these comments are great!
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkhJX83SlXD3S_Vnq:-NNmkhJX83SlXD3S_Vnr:b-gtm63v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L141)):*
> ```Go
>          },
>          "mvcc_iterator_stats": {
> 					 "stepCount": {
> ```

nit: spacing seem off here, a lot of space compared to the line above
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkn-S6gxfPZRTybHB:-NNmkn-S6gxfPZRTybHC:b51l13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L325)):*
> ```Go
>          },
>          "mvcc_iterator_stats": {
> 					 "stepCount": {
> ```

nit: same as above
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkpEL3I99PV8Qf218:-NNmkpEL3I99PV8Qf219:b51l13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L495)):*
> ```Go
>     },
>     "mvcc_iterator_stats": {
> 			"stepCount": {
> ```

nit: same as above

**Comment by kevin-v-ngo** [comment]
> then provide documentation on how to interpret the stats. In a future PR, exposure to the Console.

How would L2/on-call interpret the stats today and do we already have internal documentation/runbooks? Last thing we want is to have the stats unusable by advanced users so just want to confirm we're not missing any stats.

And do we have a general idea of how we'd expose to the console yet? Happy to chat offline

**Review by ericharmeling — COMMENTED** [review]
> How would L2/on-call interpret the stats today and do we already have internal documentation/runbooks? 

There are internal docs (code comments, really) in the storage package and in the pebble codebase. The comments I put on the protos for these stats point to those files. I do agree that we'll want to make some kind of runbook/internal wiki that will make this info a lot more accessible. We can base the user-facing docs on those.

>  Last thing we want is to have the stats unusable by advanced users so just want to confirm we're not missing any stats.

We are surfacing all stats that are being collected at the storage level, so I don't think we're missing any stats, but the docs are crucial to making these stats usable.

> And do we have a general idea of how we'd expose to the console yet? Happy to chat offline

Off the top of my head, I think we can get the range stats for the database/table the stmt/txn is querying, and then report the % live data in that range, using the same query from [the database details endpoint](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/admin.go#L1034). We could compare this with the key + value bytes read by the scan, or just report it separate from the iterator stats. We should chat about this offline though and get some design input too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-:-NNqykNp5XJaj3UO4fzA:bqtvilx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo, @maryliag, @sumeerbhola, and @yuzefovich)

___
*[`pkg/sql/appstatspb/app_stats.proto` line 342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmhdP_3BYGv5TOv6BO:-NNqqg06CjmldNOgMCOP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/appstatspb/app_stats.proto#L342)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: MVCCIteratorStats, you can also add that as the custom name for this parameter
</blockquote></details>

Done.
___
*[`pkg/sql/appstatspb/app_stats.proto` line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmhmBhD8R0Caglbjtj:-NNqqhv56aroept2-tPg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/appstatspb/app_stats.proto#L367)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: MVCCIteratorStats
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkhJX83SlXD3S_Vnq:-NNqwjW57dRcSXzlvqCP:b-h5l7ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L141)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: spacing seem off here, a lot of space compared to the line above
</blockquote></details>

It looks like this comment is on an older revision. I believe this is fixed now.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkn-S6gxfPZRTybHB:-NNqwrcA-tBPua4GEA9k:b-ya81ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L325)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: same as above
</blockquote></details>

Same as above
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkpEL3I99PV8Qf218:-NNqwq1IAO4HuFrBbtxV:b-ya81ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L495)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: same as above
</blockquote></details>

Same as above

**Review by maryliag — COMMENTED** [review]
just a few nits from me

> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-:-NNr5YNyDID9J2n1JCoS:b-emi92a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @kevin-v-ngo, @sumeerbhola, and @yuzefovich)

___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4OoMCwfOAJ3QXfbS:-NNr4OoN-9lpx8T3kAbG:b-yd6b54) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29e24fd8a927ab2890180489cf649a50cb7e24e/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L204)):*
> ```Go
> //	        "maxDiskUsage":    { "$ref": "#/definitions/numeric_stats" },
> //	        "cpuSQLNanos":     { "$ref": "#/definitions/numeric_stats" },
> //	        "mvcc_iterator_stats": { "$ref": "#/definitions/MVCCIteratorStats" }
> ```

nit: is this suppose to be camelCase?
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4RhG7fvQor8ObVt-:-NNr4RhG7fvQor8ObVt0:b-yd6b54) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29e24fd8a927ab2890180489cf649a50cb7e24e/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L215)):*
> ```Go
> //	        "maxDiskUsage",
> //	        "cpuSQLNanos",
> //	        "mvcc_iterator_stats"
> ```

nit: is this suppose to be camelCase?
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4VV42xo-bskrAQu-:-NNr4VV42xo-bskrAQu0:b-ialw80) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29e24fd8a927ab2890180489cf649a50cb7e24e/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L371)):*
> ```Go
> //	        "maxDiskUsage":    { "$ref": "#/definitions/numeric_stats" },
> //	        "cpuSQLNanos":     { "$ref": "#/definitions/numeric_stats" },
> //	        "mvcc_iterator_stats": { "$ref": "#/definitions/MVCCIteratorStats" }
> ```

nit: same 
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 381 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4XAz-nmLOeQRKn8b:-NNr4XAz-nmLOeQRKn8c:bxs2f0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29e24fd8a927ab2890180489cf649a50cb7e24e/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L381)):*
> ```Go
> //	        "maxDiskUsage",
> //	        "cpuSQLNanos",
> //	        "mvcc_iterator_stats"
> ```

nit: same
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4Z5aCz1p92dB8Lb8:-NNr4Z5aCz1p92dB8Lb9:b-yd6b54) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29e24fd8a927ab2890180489cf649a50cb7e24e/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L367)):*
> ```Go
> 		{"maxDiskUsage", (*numericStats)(&e.MaxDiskUsage)},
> 		{"cpuSQLNanos", (*numericStats)(&e.CPUSQLNanos)},
> 		{"mvcc_iterator_stats", (*iteratorStats)(&e.MVCCIteratorStats)},
> ```

nit: is this suppose to be camelCase?
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkhJX83SlXD3S_Vnq:-NNr5-NB-xF1Fp6bH3Mn:b-lxt038) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L141)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

It looks like this comment is on an older revision. I believe this is fixed now.
</blockquote></details>

hm, I still see it (both on github and reviewable). Compare the `stepCount` and the `mean` from the one above, they're suppose to be on the same spacing 


___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkn-S6gxfPZRTybHB:-NNr5J476AjJ9VT9xGr3:b-usupdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L325)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

same as above +1 :sweat_smile: 
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkpEL3I99PV8Qf218:-NNr5OkvE6gZk0OtCkts:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L495)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

+1

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo, @maryliag, @sumeerbhola, and @yuzefovich)

___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4OoMCwfOAJ3QXfbS:-NNrPN7DELrvtxHfRCVv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ace9a9258b57cfa57cb81df77d0ee261b02895fa/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L204)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: is this suppose to be camelCase?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4RhG7fvQor8ObVt-:-NNrPO6d6ec0AYz3mjmE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ace9a9258b57cfa57cb81df77d0ee261b02895fa/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L215)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: is this suppose to be camelCase?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNr4Z5aCz1p92dB8Lb8:-NNrJiYY9MgA7f1p8kPQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ace9a9258b57cfa57cb81df77d0ee261b02895fa/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L367)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: is this suppose to be camelCase?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNmkhJX83SlXD3S_Vnq:-NNrMmJjDMTPyceHKHrg:b-pvwyia) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cd0af5bc4ab7837acbee3e4a7b02a1bc5671ac5/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L141)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

hm, I still see it (both on github and reviewable). Compare the `stepCount` and the `mean` from the one above, they're suppose to be on the same spacing 



</blockquote></details>

You're right! It should be fixed now.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-:-NNrS2cw5dfEveIDF5SF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kevin-v-ngo, @sumeerbhola, and @yuzefovich)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96016)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @kevin-v-ngo, @maryliag, and @yuzefovich)

___
*[`pkg/sql/appstatspb/app_stats.proto` line 370 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96016#-NNrpa6gEsQ4FRo4xHAO:-NNrpa6gEsQ4FRo4xHAP:b-bsferx) ([raw file](https://github.com/cockroachdb/cockroach/blob/68b725ab09fa5abf825cc83c7eb158539f5bf346/pkg/sql/appstatspb/app_stats.proto#L370)):*
> ```protobuf
> }
> 
> // Internal storage iteration statistics.
> ```

I made a quick pass here and it looks good

**Comment by ericharmeling** [comment]
TFTRs! Tests are passing and I'll take the feedback as two approvals. I'm going to go ahead and bors.

**Pull request merged**
