### PR TITLE
kv: do not overwrite Transaction fields not present in TransactionRecord

### LINKED ISSUE #121589: changefeedccl: transaction restarts do not respect session-based filtering
In performance testing using TPCC, it was observed that transaction retries were correlated with changefeed events escaping session-based filtering. Replacing the `txn.OmitInRangefeeds` line in the snippet below with `true` seems to resolve this issue, leading to suspicions that transactions that need to retry due to a `TransactionAbortedError` are somehow dropping the `OmitInRangefeeds` flag:
https://github.com/cockroachdb/cockroach/blob/e53cc10829fa7740de7b40bfed5e5496e8bc4e26/pkg/kv/kvpb/data.go#L63-L75

Further investigation is needed to determine the root cause.

Jira issue: CRDB-37355

Epic CRDB-34240

### PR DESCRIPTION
**Pull request by miraradeva**
A field in the Transaction proto, that is not present in TransactionRecord, can be accidentally overwritten by Transaction.Update(...). OmitInRangefeeds and AdmissionPriority are two such fields. This patch addresses the issue by allowing the update to go through only if the fields we previously unset.

Fixes: https://github.com/cockroachdb/cockroach/issues/121589

Release note: None

### CODE REVIEW

**Review by andyyang890 — APPROVED** [review]
Thanks! :lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121850#-:-NujWTeL7QVjkNvQPi-_:b-ftzx47)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/txn_test.go` line 1397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121850#-NujW47n5aCVUfrmD26L:-NujW47n5aCVUfrmD26M:b-ejg9l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f1d8a00aacc7d355e82324581462ddbae08d046/pkg/kv/kvclient/kvcoord/txn_test.go#L1397)):*
> ```Go
> // accidentally overwritten by Update().
> // OmitInRangefeeds and AdmissionPriority are two such fields.
> func TestTxnUpdateFromTxnRecordOverwritesField(t *testing.T) {
> ```

nit: maybe rename to `...DoesNotOverwriteFields`

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121850)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/roachpb/data.go` line 1375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121850#-NujcqWwDm_SRC7Gxj__:-NujcqWwDm_SRC7Gxj_a:b-yw5dd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f1d8a00aacc7d355e82324581462ddbae08d046/pkg/roachpb/data.go#L1375)):*
> ```Go
> 	t.UpgradePriority(o.Priority)
> 
> 	// The following fields are not present in TransactionRecord, so we need to be
> ```

Can we add a unit test for this behavior? Something like the following:
```go
// TestTransactionUpdateFromRecord ... TODO ...
func TestTransactionUpdateFromRecord(t *testing.T) {
	txn := nonZeroTxn
	txnRecord := txn.AsRecord()
	txnFromRecord := txnRecord.AsTransaction()
	txn.Update(&txnFromRecord)
	require.Equal(t, nonZeroTxn, txn)
}
```

This currently fails with:
```go
Diff:
--- Expected
+++ Actual
@@ -72,4 +72,4 @@
    },
- AdmissionPriority: (int32) 1,
- OmitInRangefeeds: (bool) true
+ AdmissionPriority: (int32) 0,
+ OmitInRangefeeds: (bool) false
    }
```
___
*[`pkg/roachpb/data.go` line 1383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121850#-Nuje0ml-u0tO1h59Hpa:-Nuje0ml-u0tO1h59Hpb:b-1ov339) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f1d8a00aacc7d355e82324581462ddbae08d046/pkg/roachpb/data.go#L1383)):*
> ```Go
> 
> 	// AdmissionPriority doesn't change after the transaction is created, so we
> 	// don't ever expect to change it from a non-zero value to 0.
> ```

Do we need to test of `t` in both of these conditions? Is the following sufficient? 
```go
if o.AdmissionPriority != 0 {
    t.AdmissionPriority = o.AdmissionPriority
}
if o.OmitInRangefeeds {
    t.OmitInRangefeeds = o.OmitInRangefeeds
}
```

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121850#-:-Nv7nMYB3prTdb-SJFHP:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @miraradeva)

___
*[`pkg/kv/kvclient/kvcoord/txn_test.go` line 1393 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/121850#-Nv7mvVn84OZ04zLZTql:-Nv7mvVn84OZ04zLZTqm:b-ahuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/60035a121fea8f86aa0454f366c7cfbb359c05b8/pkg/kv/kvclient/kvcoord/txn_test.go#L1393)):*
> ```Go
> }
> 
> // TestTxnUpdateFromTxnRecordOverwritesField tests that any field in
> ```

nit: comment needs an update now that the test is renamed.
___
*[`pkg/roachpb/data_test.go` line 811 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/121850#-Nv7n5XKDYvKCAXmOJeT:-Nv7n5XKDYvKCAXmOJeU:bt5pdsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/60035a121fea8f86aa0454f366c7cfbb359c05b8/pkg/roachpb/data_test.go#L811)):*
> from a Transaction proto, to a TransactionRecord proto, and back to a Transaction proto

This isn't quite what the test is verifying. It's testing that updating a Transaction proto using a TransactionRecord does not overwrite non-zero field. Worth clarifying.

**Comment by miraradeva** [comment]
bors r=nvanbenschoten,andyyang890

**Pull request merged**
