### PR TITLE
geos: fix compile error with -Wsign-conversion

### PR DESCRIPTION
**Pull request by otan**
Not sure why this wasn't caught in #53647.

Release justification: bug fixes and low-risk updates to new
functionality

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
cc @petermattis do you know why this wasn't caught in CI, but was in https://teamcity.cockroachdb.com/viewLog.html?buildId=2235367&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Testrace?

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53702#-:-MG5B3ZsA5MF1QEcCEW8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=sumeerbhola

**Review by petermattis — COMMENTED** [review]
> cc @petermattis do you know why this wasn't caught in CI, but was in https://teamcity.cockroachdb.com/viewLog.html?buildId=2235367&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Testrace?

I don't know. Maybe some artifact reuse thingy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53702#-:-MG5DJnD4XNNLl5o-bFk:b-lx6od3)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
> Maybe some artifact reuse thingy.

ick.

**Pull request merged**
