### PR TITLE
kvserver,rac2: initialize RaftNode early

### PR DESCRIPTION
**Pull request by pav-kv**
This PR moves the `RaftNode` interface initialization to the point when `raft.RawNode` is created. This will be needed for correct initialization of `LogTracker` from the initial raft state.

The `RaftNode` interface is moved to `replica_rac2` integration package, to reduce cluttering of `kvserver`.

Part of #129508

### CODE REVIEW

**Comment by pav-kv** [comment]
@sumeerbhola This is ready for review.

Since the `RawNode` creation and setting the replica descriptor are scattered in code/time (notably, during range splits), we better need to initialize the `RaftNode` early to be sure that stable index tracking state is inited with the `RawNode` and misses no updates.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
This looks fine but I am curious whether this was necessary. We currently initialized `RaftNode` on the first call to `OnDescChangedLocked` since that happens when the replica is initialized. Before that, there should be no processing of `MsgStorageAppends`, whether as a leader or a replica. 

Initialization or state changes via calling into `Processor` are more prone to integration bugs where someone forgets to call something if another such place is added in kvserver that performs a state transition, which is why I've been trying to minimize them. They are currently limited to `OnDestroyRaftMuLocked/OnDescChangedLocked` and for the v1=>v2 transition `SetEnabledWhenLeaderRaftMuLocked`. A pull from `Processor` has some risk if it is called too early, but it isn't subject to such integration wiring bugs.

For this change, I suppose we can assume that kvserver code is stable enough that new places won't be added where `r.mu.internalRaftGroup` is set.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-:-O5K4Sx671tLfCsEozdO:br39jxe)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O5K7Az29q1_1NxEASRh:-O5K7Az29q1_1NxEASRi:bpjp4ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4381a1bc7c2a90acf5b23e6c76f5a6d1908021/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L484)):*
> ```Go
> func (p *processorImpl) InitRaftLocked(rn RaftNode) {
> 	p.raftMu.raftNode = rn
> 	// TODO(pav-kv): initialize the stable log mark tracking from RawNode state.
> ```

I am curious what this TODO is about.
The `admittedTracker` stable log mark doesn't need to be initialized here. It can wait until the callback from a `MsgAppResp` or in a `HandleRaftReadyRaftMuLocked`.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O5K7vFv2mql05bkPvPs:-O5K7vFv2mql05bkPvPt:bxhi9cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4381a1bc7c2a90acf5b23e6c76f5a6d1908021/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L557)):*
> ```Go
> 		panic(errors.AssertionFailedf("tenantId was changed from %s to %s",
> 			p.raftMu.tenantID, tenantID))
> 	}
> ```

can you add an assertion that `raftNode` is already initialized.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go` line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O5K96P31w0rANvqYiaI:-O5K96P489a5ZK-M5sOp:b-5v7kcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4381a1bc7c2a90acf5b23e6c76f5a6d1908021/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go#L305)):*
> ```Go
> 			p.opts.NodeID, p.opts.StoreID, p.opts.RangeID, p.opts.ReplicaID, tenantID,
> 			enabledLevelString(p.mu.enabledWhenLeader))
> 		p.InitRaftLocked(r.raftNode)
> ```

there are existing test cases that call handleRaftReady before initializing `RawNode` and ensure that the `processorImpl` is correctly doing nothing instead of causing a null pointer exception. Those will no longer get exercised by eagerly calling `InitRaftLocked`. Can you make this an explicit command, or roll this into the first "on-desc-locked".

**Review by pav-kv — COMMENTED** [review]
Agree, this might be unnecessary. It would be good to confirm that "uninitialized replica" (one with `RawNode` but no descriptor) won't write to storage, and if that's the case we're good. Putting this on hold for now. Needed this to initialize `LogTracker` from the other PR, but it's ok to do it next to `RaftNodeLocked()` call too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-:-O5OkOyk4qo_Z0f4fwnl:bbo1lcn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

**Review by pav-kv — COMMENTED** [review]
This PR now seems necessary, per context in #130171. Yeah, we can assume that the code initializing `RawNode` is fairly stable. Today, there is only one place where `RawNode` is created, and I don't expect it to get out hand.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-:-O67pJjh3W8_D-pY6p94:b-v42i1o)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O5K7Az29q1_1NxEASRh:-O67oetV4T4R-5JakD_k:b-4vz2a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4381a1bc7c2a90acf5b23e6c76f5a6d1908021/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L484)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am curious what this TODO is about.
The `admittedTracker` stable log mark doesn't need to be initialized here. It can wait until the callback from a `MsgAppResp` or in a `HandleRaftReadyRaftMuLocked`.
</blockquote></details>

This will be the place for `logTracker.init` call. Motivation is explained in https://github.com/cockroachdb/cockroach/pull/130171#issuecomment-2332425356: for correct stable index tracking we don't want `LogTracker` initialization racing with `RawNode.Ready()` handling.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O5K7vFv2mql05bkPvPs:-O67p8woChfeJz9V-t_P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4381a1bc7c2a90acf5b23e6c76f5a6d1908021/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L557)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add an assertion that `raftNode` is already initialized.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go` line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O5K96P31w0rANvqYiaI:-O67sK0G1q6IMp0DntNY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4381a1bc7c2a90acf5b23e6c76f5a6d1908021/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go#L305)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there are existing test cases that call handleRaftReady before initializing `RawNode` and ensure that the `processorImpl` is correctly doing nothing instead of causing a null pointer exception. Those will no longer get exercised by eagerly calling `InitRaftLocked`. Can you make this an explicit command, or roll this into the first "on-desc-locked".
</blockquote></details>

Done.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129727)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go` line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O682Ws1BDm14Ua-ZSpR:-O682Ws1BDm14Ua-ZSpS:bqsmjog) ([raw file](https://github.com/cockroachdb/cockroach/blob/44155ccf682b471487c73f72db453c9ca274041b/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go#L323)):*
> ```Go
> 				return builderStr()
> 
> 			case "init-raft":
> ```

Could also move this to `set-raft-state`, and init raft node if it's nil.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 8 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-:-O68Np7x6Z_El87XX8ST:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O68MjTe-Jhtw4UjE3st:-O68MjTe-Jhtw4UjE3su:b-lly8qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/44155ccf682b471487c73f72db453c9ca274041b/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L301)):*
> ```Go
> type Processor interface {
> 	// InitRaftLocked is called when RaftNode is initialized for the Replica.
> 	// NB: can be called twice before the Replica is fully initialized.
> ```

And these two `RawNode`s (uninitialized replica, and later when initialized) are consistent with each other?

Just curious -- why did we need to recreate the `RawNode`? Is it because we don't have `RaftAppliedIndex` until the `Replica` is initialized -- I would have thought snapshot application (which Raft knows about) would have fixed that part of its state.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go` line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O682Ws1BDm14Ua-ZSpR:-O68M42d7bA8XFlYkDiR:b-produ5) ([raw file](https://github.com/cockroachdb/cockroach/blob/44155ccf682b471487c73f72db453c9ca274041b/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor_test.go#L323)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Could also move this to `set-raft-state`, and init raft node if it's nil.
</blockquote></details>

this is fine

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129727)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129727#-O68MjTe-Jhtw4UjE3st:-O68dt0y8JKIwI3f_S6L:bcn8lp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44155ccf682b471487c73f72db453c9ca274041b/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L301)):*
I think this has to do with the fact that uninitialized replica needs to be able to participate in elections, before it gets the initial snapshot/`RaftAppliedIndex` and initialized.

> And these two `RawNode`s (uninitialized replica, and later when initialized) are consistent with each other?

I think they are, at least `RawNode` always assumes that it starts from a durable/consistent state. Arguably it would be better to init `RawNode` exactly once, and move it forward to the new state when the replica is fully inited - should consider doing that in the future. The last related PR is #104657.

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Pull request merged**
