### PR TITLE
sql: add MODIFYSQLCLUSTERSETTING system privilege

### LINKED ISSUE #96172: MODIFYCLUSTERSETTING does not work as expected 22.2+
**Describe the problem**

When providing the system privilege MODIFYCLUSTERSETTING in 22.1, this setting provided access to alter sql.defaults.* cluster settings.

From 22.2 MODIFYCLUSTERSETTING allows access to all cluster settings.

**To Reproduce**

```
root@localhost:26257/defaultdb> alter role test3001 with modifyclustersetting;
ALTER ROLE

 ./cockroach sql --certs-dir=certs --user test3001


test3001@localhost:26257/defaultdb> SET CLUSTER SETTING diagnostics.reporting.enabled = false;
SET CLUSTER SETTING

````

**Expected behavior**

The user "test3001" shouldn't be able to set cluster settings outside of sql.defaults.

Seen in previous versions: 

```
root@localhost:26257/defaultdb> alter role test3001 with modifyclustersetting;
ALTER ROLE

 ./cockroach sql --certs-dir=certs --user test3001

test3001@:26257/defaultdb> SET CLUSTER SETTING diagnostics.reporting.enabled = false;
warning: cannot save command-line history: write_history: illegal byte sequence
ERROR: only users with the admin role are allowed to set cluster setting 'diagnostics.reporting.enabled'
SQLSTATE: 42501
```

**Additional context**
This violates the principle of least privilege. Once upgraded to 22.2, there will be users that have access to all cluster settings and therefore able to alter security settings such as the hba.conf. 

Ultimately meaning, that in this state we have to revoke access to MODIFYCLUSTERSETTING and users will no longer be able to edit sql.defaults without adjusting roles..

 [ALTER ROLE ALL SET {sessionvar} = {val}](https://www.cockroachlabs.com/docs/v22.2/alter-role#set-default-session-variable-values-for-all-users)

Jira issue: CRDB-23981

### PR DESCRIPTION
**Pull request by Santamaura**
This patch creates a new system privilege called
MODIFYSQLCLUSTERSETTING. It allows user who have
been granted this system privilege the ability to
view all cluster settings but only change cluster
settings which have the  prefix 'sql.defaults'.
This allows for the same edit functionality that
MODIFYCLUSTERSETTINGS had before 22.2.

Fixes: #96172

Release note (sql change): add MODIFYSQLCLUSTERSETTING system privilege. This privilege allows users the ability to view all cluster settings but only modify setting with the 'sql.defaults' prefix in order to re-introduce the modify functionality seen with MODIFYCLUSTERSETTING before 22.2.

e.g. a user with MODIFYSQLCLUSTERSETTING
Screenshot 2023-02-22 at 3 41 51 PM

### CODE REVIEW

**Comment by Santamaura** [comment]
Note: I think we should be clear in the subsequent docs that `MODIFYSQLCLUSTERSETTING` only allows users to modify cluster settings with the `sql.defaults` prefix and in that sense it behaves similar to `MODIFYCLUSTERSETTING` before 22.2.

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good. i had a few code organization suggestions

and one bigger suggestion: since we recommend the `ALTER ROLE .. SET` syntax, i think we should modify the code in https://github.com/cockroachdb/cockroach/blob/46b1afac031677e71ef6ba87d8686cc8c90600dd/pkg/sql/alter_role.go#L293 so that it works if you have MODIFYCLUSTERSETTING or MODIFYSQLCLUSTERSETTING

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-:-NPNXl7SCoULqW5zc0RO:b-q5dtun)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/sql/set_cluster_setting.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPNWrh2A-IJQcc8kAHH:-NPNWrh2A-IJQcc8kAHI:b-93phz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e866db687eddd9dcab7384c0192816cf306d40/pkg/sql/set_cluster_setting.go#L73)):*
> ```Go
> 	hasView := false
> 	if err := p.CheckPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING); err == nil {
> 		hasModify = true
> ```

nit: it would be more clear to also set `hasSqlModify = true` here.

actually, for readability i'd recommend rewriting this so that you minimize the amount of elses and avoid checking the error code:

```
	hasModify := false
	hasSqlModify := false
	hasView := false
	if ok, err := p.HasPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING, p.User()); err != nil {
		return err
	} else if ok {
		hasModify = true
		hasSqlModify = true
		hasView = true
	}
	if !hasSqlModify {
		if ok, err := p.HasPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYSQLCLUSTERSETTING, p.User()); err != nil {
			return err
		} else if ok {
			hasSqlModify = true
			hasView = true
		}
	}
	if !hasView {
		if ok, err := p.HasPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.VIEWCLUSTERSETTING, p.User()); err != nil {
			return err
		} else if ok {
			hasView = true
		}
	}
```
___
*[`pkg/sql/set_cluster_setting.go` line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPNXLs3CUgEfsbsBckW:-NPNXLs3CUgEfsbsBckX:b-hhhbh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e866db687eddd9dcab7384c0192816cf306d40/pkg/sql/set_cluster_setting.go#L98)):*
> ```Go
> 		}
> 		hasModify = hasModify || ok
> 		hasView = hasView || ok
> ```

nit: also set `hasModifySql = hasModifySql || ok`
___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPNeAtv3zfJmFMq4LIR:-NPNeAtv3zfJmFMq4LIS:b-6mnobh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e866db687eddd9dcab7384c0192816cf306d40/pkg/sql/delegate/show_all_cluster_settings.go#L30)):*
> ```Go
> 	hasSqlModify := false
> 	hasView := false
> 	if err := d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING); err == nil {
> ```

similar to above, i think this would be more readable without so many else-ifs:
```
	hasModify := false
	hasSqlModify := false
	hasView := false
	if err := d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING); err == nil {
		hasModify = true
		hasSqlModify = true
		hasView = true
	} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
		return nil, err
	}
	if !hasSqlModify {
		if err := d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYSQLCLUSTERSETTING); err == nil {
			hasSqlModify = true
			hasView = true
		} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
			return nil, err
		}
	}
	if !hasView {
		if err := d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.VIEWCLUSTERSETTING); err == nil {
			hasView = true
		} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
			return nil, err
		}
	}
```

(i'd prefer if the catalog interface also had the `HasPrivilege` version of the function, but it doesn't right now. i can add that later)

**Review by Santamaura — COMMENTED** [review]
> so that it works if you have MODIFYCLUSTERSETTING or MODIFYSQLCLUSTERSETTING

Added

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-:-NPOmd21BA1TQ75y4t2k:bu1kyry)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @rafiss, and @zachlite)

___
*[`pkg/sql/set_cluster_setting.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPNWrh2A-IJQcc8kAHH:-NPOnBtcAM8mmA_dteQ2:bzfetym) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e866db687eddd9dcab7384c0192816cf306d40/pkg/sql/set_cluster_setting.go#L73)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it would be more clear to also set `hasSqlModify = true` here.

actually, for readability i'd recommend rewriting this so that you minimize the amount of elses and avoid checking the error code:

```
	hasModify := false
	hasSqlModify := false
	hasView := false
	if ok, err := p.HasPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING, p.User()); err != nil {
		return err
	} else if ok {
		hasModify = true
		hasSqlModify = true
		hasView = true
	}
	if !hasSqlModify {
		if ok, err := p.HasPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYSQLCLUSTERSETTING, p.User()); err != nil {
			return err
		} else if ok {
			hasSqlModify = true
			hasView = true
		}
	}
	if !hasView {
		if ok, err := p.HasPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.VIEWCLUSTERSETTING, p.User()); err != nil {
			return err
		} else if ok {
			hasView = true
		}
	}
```

</blockquote></details>

Thanks for the org suggestion, done
___
*[`pkg/sql/set_cluster_setting.go` line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPNXLs3CUgEfsbsBckW:-NPOnFWS3InPDaDggPYm:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e866db687eddd9dcab7384c0192816cf306d40/pkg/sql/set_cluster_setting.go#L98)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: also set `hasModifySql = hasModifySql || ok`
</blockquote></details>

Done
___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPNeAtv3zfJmFMq4LIR:-NPOnHD81JOf1HPz1SD_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e866db687eddd9dcab7384c0192816cf306d40/pkg/sql/delegate/show_all_cluster_settings.go#L30)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar to above, i think this would be more readable without so many else-ifs:
```
	hasModify := false
	hasSqlModify := false
	hasView := false
	if err := d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING); err == nil {
		hasModify = true
		hasSqlModify = true
		hasView = true
	} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
		return nil, err
	}
	if !hasSqlModify {
		if err := d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYSQLCLUSTERSETTING); err == nil {
			hasSqlModify = true
			hasView = true
		} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
			return nil, err
		}
	}
	if !hasView {
		if err := d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.VIEWCLUSTERSETTING); err == nil {
			hasView = true
		} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
			return nil, err
		}
	}
```

(i'd prefer if the catalog interface also had the `HasPrivilege` version of the function, but it doesn't right now. i can add that later)
</blockquote></details>

Done

**Comment by thtruo** [comment]
@Santamaura can we also backport this to 22.2?

**Comment by rafiss** [comment]
@thtruo @Santamaura: i don't think this is actually safe to backport. see this line https://github.com/cockroachdb/cockroach/blob/a3db6798bdfcc462c509f7c655caebe355c37f37/pkg/sql/privilege/privilege.go#L292

if someone grants MODIFYSQLCLUSTERSETTING on a node running `v22.2.new`, and then tries to modify a cluster setting on a node running `v22.2.old`, they will see an error like `not a valid privilege: "MODIFYSQLCLUSTERSETTING"`

we can discuss more offline

**Review by rafiss — CHANGES_REQUESTED** [review]
one more thing we should do: can you update the `retiredSettings` map in pkg/settings/registry.go so that it has the name of the setting that we are going to be adding to v22.2 for https://github.com/cockroachdb/cockroach/issues/98155. otherwise, there would be issues when upgrading to v23.1, which will not have that cluster setting.

this lgtm after that change!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-:-NPxS6ea13ksh8_nC0hZ:bfet638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_role_set` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPxRnz4-fwm5IZxjT5T:-NPxRnz4-fwm5IZxjT5U:b-sxi5q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b99f9da4a7c8eb90b60c94483954ade764b00f/pkg/sql/logictest/testdata/logic_test/alter_role_set#L156)):*
> ```
> # Verify that testuser can't edit their own defaults.
> statement error pq: ALTER ROLE ... SET requires MODIFYCLUSTERSETTING, MODIFYSQLCLUSTERSETTING or CREATEROLE
> ALTER ROLE testuser RESET application_name
> ```

nice, thanks for the tests!

**Review by Santamaura — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-:-NQ25vyi39RSEIK1bjch:bb6un1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @rafiss, and @zachlite)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_role_set` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97521#-NPxRnz4-fwm5IZxjT5T:-NQ25z4t1jR-c0fScwi0:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b99f9da4a7c8eb90b60c94483954ade764b00f/pkg/sql/logictest/testdata/logic_test/alter_role_set#L156)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice, thanks for the tests!
</blockquote></details>

:thumbsup:

**Review by rafiss — APPROVED** [review]
this lgtm, but to make the test pass, you need to add the new keyword to `bare_label_keywords`: https://github.com/cockroachdb/cockroach/blob/ac7961d7a99237d066daa61912b27943ab757efc/pkg/sql/parser/sql.y#L16595

**Comment by Santamaura** [comment]
TFTR

bors r+

**Pull request merged**
