### PR TITLE
kvserver: move raft log size update

### PR DESCRIPTION
**Pull request by pav-kv**
Part of #136109

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136467)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/replica_raftlog_writes.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136467#-OD6nvsBDlyGwiiQPYbY:-OD6nvsBDlyGwiiQPYbZ:b2ni8l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d2e4663c6f92118065962a048c2840d1c588c16/pkg/kv/kvserver/replica_raftlog_writes.go#L79)):*
> ```Go
> // knowledge about this size. Returns the computed log size.
> //
> // Replica.{raftMu,mu} most not be held.
> ```

nit



_Suggestion:_
```Go
// Replica.{raftMu,mu} must not be held.
```

**Review by pav-kv — COMMENTED** [review]
Added another commit which makes the log size computation a method of `LogStore`. This allows using the right engines from `LogStore`, instead of `TODOEngine()`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136467#-:-OD6sEXm8UU5HFm10HS3:b-zgephb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvserver/replica_raftlog_writes.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136467#-OD6nvsBDlyGwiiQPYbY:-OD6sCLbDC_hpDag5s2R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d2e4663c6f92118065962a048c2840d1c588c16/pkg/kv/kvserver/replica_raftlog_writes.go#L79)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.

**Comment by pav-kv** [comment]
bors r=tbg

**Comment by pav-kv** [comment]
bors r=tbg

**Pull request merged**
