### PR TITLE
multitenant: support crdb_internal.list_sql_keys_in_range() for secondary tenants

### LINKED ISSUE #92072: kv: consider splitting at tenant's end key range boundary
See slack thread for context: https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1667393625502529

Today, each tenant's end key (in the range list) is the first key of the next tenant (i.e. the last key of tenant 10 is /tenant/30, if only tenants 10 and 30 are defined). For the the last tenant its end key is `/Max`.

We'd like all this to be `/Tenant/<id>/<endprefix>`. 

This causes a few concerns around things like zone configs from the previous tenant temporarily leaking into a newly created tenant. This should be straightforward to address, so we should.

cc @knz @cockroachdb/multi-tenant 

Jira issue: CRDB-21562

Epic CRDB-23344

### LINKED ISSUE #95006: sql,kv: the builtin `list_sql_keys_in_range` emits requests outside of the tenant keyspace
**Describe the problem**

The builtin function `crdb_internal.list_sql_keys_in_range()` currently errors out in secondary tenans
```
ERROR: RangeIterator failed to seek to /Meta2/"\x00": rpc error: code = Unauthenticated desc = requested key /Meta2/"\x00" not fully contained in tenant keyspace /Tenant/1{2-3}
```

**Expected behavior**

- for ranges that contain the requesting tenant's data, the builtin should work and return results without errors.
- for ranges that don't contain the requesting tenant's data, we should have a check:
  - if the tenant is the system tenant, allow the request to go through
  - otherwise return a clear error

Jira issue: CRDB-23269

Epic CRDB-23344

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #95006

The crdb_internal.list_sql_keys_in_range builtin now uses the RangeDescIterator
and scopes the range span by the tenant span to prevent these errors:
```
ERROR: RangeIterator failed to seek to /Meta2/"\x00": rpc error: code = Unauthenticated desc = requested key /Meta2/"\x00" not fully contained in tenant keyspace /Tenant/1{2-3}
```
    
----

Fixes #92072

The last range of the last tenant's end key is `/Max` which is outside of the
tenant's key space.

This is fixed by adding a split at the end of the tenant's key space when the
tenant is created. For example, when tenant 10 is created, a split is added at
/tenant/11.

Release note: None

### CODE REVIEW

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @knz, @rafiss, and @yuzefovich)

___
*[`pkg/sql/region_util.go` line 2426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXJ0u1-75H0xapWXgf:-NLXJ0u1-75H0xapWXgg:b-ys4hiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/19550a27841bc356be575d4a534785db67ed65ad/pkg/sql/region_util.go#L2426)):*
> ```Go
> 	execCfg := p.execCfg
> 	tenantSpan := execCfg.Codec.TenantSpan()
> 	rangeDescIterator, err := execCfg.RangeDescIteratorFactory.NewIterator(ctx, tenantSpan)
> ```

This fixes the error caused by trying to access `Meta2`, but the `RangeDescriptor` can have an `EndKey` of `var KeyMax = []byte{0xff, 0xff}` which causes a similar error because `{0xff, 0xff}` is not inside the tenant keyspace.

Does it make sense to make sure that the `RangeDescriptor` returned by `RangeDescIteratorFactory` has keys within the specified `tenantSpan`? Or should the result be intersected like `tenantSpan.Intersect(rangeSpan)` whenever it is used?

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-:-NLXafRNC-9x22LghRrA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, and @rafiss)

___
*[`pkg/sql/region_util.go` line 2426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXJ0u1-75H0xapWXgf:-NLXaBZe8epSMYAmaPCA:b-9iq8vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/98443a84201dfdd8f0dad4177b956d6b1fc18286/pkg/sql/region_util.go#L2426)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

This fixes the error caused by trying to access `Meta2`, but the `RangeDescriptor` can have an `EndKey` of `var KeyMax = []byte{0xff, 0xff}` which causes a similar error because `{0xff, 0xff}` is not inside the tenant keyspace.

Does it make sense to make sure that the `RangeDescriptor` returned by `RangeDescIteratorFactory` has keys within the specified `tenantSpan`? Or should the result be intersected like `tenantSpan.Intersect(rangeSpan)` whenever it is used?
</blockquote></details>

I'm not sure. I'm OK leaving that problem open for now (with a test case that demonstrates the problem) and then address this comprehensively when we look at the group of issues around range boundaries.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 2145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXaPgTAYGQHU1YDYv9:-NLXaPgTAYGQHU1YDYvA:bqkh2zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/98443a84201dfdd8f0dad4177b956d6b1fc18286/pkg/sql/sem/builtins/generator_builtins.go#L2145)):*
> ```Go
> func newSpanKeyIterator(evalCtx *eval.Context, span roachpb.Span) *spanKeyIterator {
> 	return &spanKeyIterator{
> ```

nit: remove this empty line.

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/eval/deps.go` line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXfGDKDjU8YKB0_SWN:-NLXfGDKDjU8YKB0_SWO:by08ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/98443a84201dfdd8f0dad4177b956d6b1fc18286/pkg/sql/sem/eval/deps.go#L362)):*
> ```Go
> 
> 	// GetTenantRangeRSpanByID gets the Span of the range (specified by RangeID)
> 	// and scopes it to the tenant.
> ```

Something about this feels a bit off -- specifically, the "scope it to the tenant" part. Suddenly, what is a span that corresponds to a range in the system is no longer that, which makes me question what we are using it for. Why do we need this?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/eval/deps.go` line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXfGDKDjU8YKB0_SWN:-NLXftANEU9z0WE9wf25:bdsgpnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/98443a84201dfdd8f0dad4177b956d6b1fc18286/pkg/sql/sem/eval/deps.go#L362)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Something about this feels a bit off -- specifically, the "scope it to the tenant" part. Suddenly, what is a span that corresponds to a range in the system is no longer that, which makes me question what we are using it for. Why do we need this? 
</blockquote></details>

Can we do this at the caller instead of adding this wart to the interface?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[`pkg/sql/sem/eval/deps.go` line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXfGDKDjU8YKB0_SWN:-NLXl_Gf7OptOe-DcmlL:b-ntqypa) ([raw file](https://github.com/cockroachdb/cockroach/blob/98443a84201dfdd8f0dad4177b956d6b1fc18286/pkg/sql/sem/eval/deps.go#L362)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we do this at the caller instead of adding this wart to the interface? 
</blockquote></details>

Moving it up into the call site is even worse because every caller will need to know that range's span needs an intersection done on it before it can be used.

Maybe it's worth it to make a `TenantRangeDescriptor` model with only info that the tenant should see?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @knz, and @rafiss)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 2145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXaPgTAYGQHU1YDYv9:-NLXnD9m45RE9P7I-iGP:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/98443a84201dfdd8f0dad4177b956d6b1fc18286/pkg/sql/sem/builtins/generator_builtins.go#L2145)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: remove this empty line.
</blockquote></details>

Fixed.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/sem/eval/deps.go` line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NLXfGDKDjU8YKB0_SWN:-NLYkh4UD3PYDBFZ6G-l:b-kcmhpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/98443a84201dfdd8f0dad4177b956d6b1fc18286/pkg/sql/sem/eval/deps.go#L362)):*
I'm not sure what you mean by every call site -- isn't there just one? 

That being said, that's kind of my point, callers *should* perform this intersection, explicitly, if there's a legitimate reason to do so. The real issue here is that ranges may span across tenant boundaries, and hiding the magic required to deal with this wart behind an interface gives it unwarranted credibility. 

Could we change this to `GetRangeDescriptor` instead?

> Maybe it's worth it to make a TenantRangeDescriptor model with only info that the tenant should see?

Instead of introducing a new concept, we should fix https://github.com/cockroachdb/cockroach/issues/92072 instead.

**Review by arulajmani — APPROVED** [review]
Thanks for fixing #92072 while you were here! Let's add some words about it, and how we fixed it, in the commit message (or, better yet, let's pull it out into its own commit). 

> Reviewed 3 of 10 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-:-NM4MNiL81gyhH8yHjAY:byctf0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ecwall, @knz, and @rafiss)

**Review by knz — APPROVED** [review]
Agreed for a better description in the commit message of what is changing here. Currently the commit message is incomplete: it does not explain what is being done to the tenant range boundaries in tenant creation and span configs.

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-:-NM5CvWx05jnbmliQQOd:b-aw3z6m)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/tenant_creation.go` line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95100#-NM5CQe32w8Y4e203stu:-NM5CQe32w8Y4e203stv:bzdzvnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b4bb0c47e1535d234cbe3c0373b7ffd2b53262/pkg/sql/tenant_creation.go#L315)):*
> ```Go
> 		return roachpb.TenantID{}, err
> 	}
> 	tenantPrefixEnd := tenantPrefix.PrefixEnd()
> ```

Thanks for this. Can you add a comment that explains why this is important.

**Comment by ecwall** [comment]
bors r=knz,arulajmani

**Pull request merged**
