### PR TITLE
sql: SHOW GRANTS includes inherited roles

### LINKED ISSUE #97299: sql: SHOW GRANTS inherited by virtue of role membership
`SHOW GRANTS` currently only lists explicitly granted privileges. This FR is to extend the list to privileges inherited by role membership. Example below:

Starting point:

```sql
create database d1;
create role r1;
create user u1;
grant r1 to u1;
use d1;
create table t1 (id int);
grant all on table t1 to r1;
show grants on t1 for r1;
--   database_name | schema_name | table_name | grantee | privilege_type | is_grantable
-- ----------------+-------------+------------+---------+----------------+---------------
--   d1            | public      | t1         | r1      | ALL            |      f
-- (1 row)
```

Currently, it shows no grants for u1:

```sql
show grants on t1 for u1;
-- SHOW GRANTS 0
```

Envisioned - see last column so you have that extra info

```sql
show grants on t1 for u1;
--   database_name | schema_name | table_name | grantee | privilege_type | is_grantable   | from_role
-- ----------------+-------------+------------+---------+----------------+----------------------------
--   d1            | public      | t1         | r1      | ALL            |      f         |    r1
-- (1 row)
```

[Slack](https://cockroachlabs.slack.com/archives/CHVV403F0/p1676651603690829)

Jira issue: CRDB-24622

gz#16111

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by postamar**
Previously, SHOW GRANTS would only list explicitly-granted privileges.
  This commit changes its output to include privileges inherited by role
  membership.
  
  Consider for example:
  
      CREATE DATABASE d1;
      CREATE ROLE r1;
      CREATE USER u1;
      GRANT r1 TO u1;
      SET database = d1;
      CREATE TABLE t1 (id INT8);
      GRANT ALL ON TABLE t1 TO r1;
  
  We want `SHOW GRANTS ON TABLE t1 FOR u1` to list the ALL privilege that
  u1 inherits from r1.
  
  For this purpose this commit also adds a new `kv_inherited_role_members`
  virtual table in `crdb_internal` which is essentially a recursive
  self-join of `system.role_members` run by the node user.
  
  This commit also changes the output of `SHOW GRANTS ON ROLE` to list
  both explicit and implicit grantees: the former are the direct result of
  a `GRANT ... TO ...` statement, the latter comprise also all the roles
  which inherit the privileges following further role membership
  relationships. For this purpose it also uses the new virtual table and
  therefore the current user no longer requires SELECT privileges on the
  `system.role_members` table.
  
  Fixes #97299.
  
  Release note (sql change): SHOW GRANTS now lists not just privileges
  explicitly granted to each role, but also roles which inherit from
  those. SHOW GRANTS ON ROLE statements no longer require any privileges
  and also lists implicit grantees.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good! i think we should add tests for each one of: `SHOW GRANTS ON [TABLE|SCHEMA|DATABASE|TYPE|FUNCTION]` that demonstrate that they show the inherited privileges too

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-:-NXB3vY19ptaeIpl9gNb:b-8dorhc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/crdb_internal.go` line 8059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXB1Cmo7tzo955ocQrs:-NXB1Cmo7tzo955ocQrt:b3hipgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70acfdbf8676dac2a0b07172e60af9580883749/pkg/sql/crdb_internal.go#L8059)):*
> ```Go
> 		// This is defined as a table instead of a more straightforward view
> 		// because we want the query to run under the node user.
> 		const query = `
> ```

have you tried testing how this performs? i've crafted a query like this before and i think it had some bad issues

i'm thinking it would be better if we used the existing role-membership cache. because of how commonly we need to look up memberships, the way the cache works is that it actually loads everything in eagerly. so if we just iterate through each user using the `forEachRole` helper, and then call `planner.MemberOfWithAdminOption` for each one, it might actually perform better
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog` line 1639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXB3a3l9UD67-fFmWO0:-NXB3a3l9UD67-fFmWO1:b-6wu6pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70acfdbf8676dac2a0b07172e60af9580883749/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1639)):*
> ```
> ----
> classid     objid       objsubid  refclassid  refobjid    refobjsubid  deptype
> 4294967102  111         0         4294967105  110         14           a
> ```

what made all the OIDs change? is it from adding `CrdbInternalInheritedRoleMembersTableID`? (that's fine if so, though it's unpleasant)

**Review by postamar — COMMENTED** [review]
Good point, I completely forgot to do this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-:-NXC5WQG9JIAZ5OzmQJT:b225k5c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 8059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXB1Cmo7tzo955ocQrs:-NXBJxppE8qU3U-MOlwm:b-rstvjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70acfdbf8676dac2a0b07172e60af9580883749/pkg/sql/crdb_internal.go#L8059)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

have you tried testing how this performs? i've crafted a query like this before and i think it had some bad issues

i'm thinking it would be better if we used the existing role-membership cache. because of how commonly we need to look up memberships, the way the cache works is that it actually loads everything in eagerly. so if we just iterate through each user using the `forEachRole` helper, and then call `planner.MemberOfWithAdminOption` for each one, it might actually perform better
</blockquote></details>

Agreed, this seems better in every way.
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog` line 1639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXB3a3l9UD67-fFmWO0:-NXBHnwEAcKJd0zK0QJ5:b-6ldl4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70acfdbf8676dac2a0b07172e60af9580883749/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1639)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what made all the OIDs change? is it from adding `CrdbInternalInheritedRoleMembersTableID`? (that's fine if so, though it's unpleasant)
</blockquote></details>

Yes indeed.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104119)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/crdb_internal.go` line 8057 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXGQz6L1CUxl1gG8L2X:-NXGQz6L1CUxl1gG8L2Y:b-fokyj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed81fbf5a8732ff4191aed2b3430ffca256f5f7/pkg/sql/crdb_internal.go#L8057)):*
> ```Go
> );`,
> 	populate: func(ctx context.Context, p *planner, _ catalog.DatabaseDescriptor, addRow func(...tree.Datum) error) (retErr error) {
> 		explicit := make(map[username.SQLUsername]map[username.SQLUsername]bool)
> ```

could you add a comment for why we need `explicit` (or perhaps a different name would make it more clear)
___
*[`pkg/sql/crdb_internal.go` line 8058 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXGHY8j8Z8tnXmwvgyY:-NXGHY8j8Z8tnXmwvgyZ:b-dvtoif) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed81fbf5a8732ff4191aed2b3430ffca256f5f7/pkg/sql/crdb_internal.go#L8058)):*
> ```Go
> 	populate: func(ctx context.Context, p *planner, _ catalog.DatabaseDescriptor, addRow func(...tree.Datum) error) (retErr error) {
> 		explicit := make(map[username.SQLUsername]map[username.SQLUsername]bool)
> 		if err := forEachRoleMembership(ctx, p.InternalSQLTxn(), func(role, member username.SQLUsername, isAdmin bool) error {
> ```

this seems to work, but it won't use the cache. that could be fine, but if it's easy to do without changing any existing logic, i would still vote for using forEachRole and then calling MemberOfWithAdminOption for each one.
___
*[`pkg/sql/delegate/show_role_grants.go` line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXGSvFO8XSaNA7DUtXN:-NXGSvFO8XSaNA7DUtXO:b5rlrbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed81fbf5a8732ff4191aed2b3430ffca256f5f7/pkg/sql/delegate/show_role_grants.go#L70)):*
> ```Go
> 
> 	query := fmt.Sprintf(`
> WITH
> ```

could you add some commentary to explain in english why we need both `u` and `explicit`?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104119)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/crdb_internal.go` line 8058 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-NXGHY8j8Z8tnXmwvgyY:-NXGTLry1v8RECfXvnrr:b6nxefy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed81fbf5a8732ff4191aed2b3430ffca256f5f7/pkg/sql/crdb_internal.go#L8058)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this seems to work, but it won't use the cache. that could be fine, but if it's easy to do without changing any existing logic, i would still vote for using forEachRole and then calling MemberOfWithAdminOption for each one.
</blockquote></details>

nvm, ignore this comment. i see now that we do use the cache below, and this is just for getting the explicit memberships.

**Comment by postamar** [comment]
Ready for another look!

**Comment by postamar** [comment]
Thanks for taking another look, I've added some commentary. Please do let me know if it needs to be reworded again, I've been focused on this issue for long enough that I've lost perspective somewhat.

**Review by rafiss — APPROVED** [review]
the new commentary is extremely helpful. thanks! 

we will need to backport this, since the field teams need it, so i'm adding some labels

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-:-NXGz80t7vPIjM270v3P:bt0mrhw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

**Comment by postamar** [comment]
Thanks!

> This is safe since vtables are always populated by just one node. 

My worry was more that because SHOW GRANTS ON ROLE delegates to a nested query which might be processed in a distributed fashion, the node that would populate the vtable might be a different node and therefore potentially unpatched.

bors r+

**Comment by rafiss** [comment]
hmm i suppose that's a fair concern. let's at least do some diligence: this should now be quite easy to test using the `cockroach-go-testserver-upgrade-to-master` logictest config, so can i request that you add one of those?

bors r-

**Comment by postamar** [comment]
We would have to have the SHOW GRANTS performed on a node with the new binary, which is easy enough, but how do we ensure that the query gets distributed in such a way that the vtable scan takes place on an old binary? Or do we just hope that the test never flaking means that the implementation is safe?

**Comment by rafiss** [comment]
> Or do we just hope that the test never flaking means that the implementation is safe?

yes i think in this case we can just use the flakiness as a signal.

although one thing i would say is that since the behavior is backwards-compatible, i believe it's OK that in a mixed version state, you might see the old behavior. i just want to ensure there's no error/crash.

> Also, once we backport this patch to 23.1, such a test cannot fail, because it will pull the latest maintenance version of 23.1.

hm that's a good point. well, the test will still exist in the 23.1 branch though, which would run in a 22.2/23.1 mixed state

**Comment by postamar** [comment]
I haven't gotten anywhere with disabling distsql (thanks anyway @mgartner ) so I'll just add the test and call it a day.

**Review by rafiss — APPROVED** [review]
thanks for the extra testing!

> Reviewed 15 of 19 files at r1, 5 of 7 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104119#-:-NXM_1DI8MyIGXmaEybk:bypyz09)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

**Pull request merged**
