### PR TITLE
storage: retry ambiguous errors on node liveness heartbeats

### PR DESCRIPTION
**Pull request by spencerkimball**
Addresses #15341

### CODE REVIEW

**Comment by tamird** [comment]
Test?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/node_liveness.go, line 251 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifR84afNMDs5ypa78w:-KifR84afNMDs5ypa78x:b8odeg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ffff6f749043cfd956537b684c9b1b6d58a047/pkg/storage/node_liveness.go#L251)):*
> ```Go
> 						// Retry skipped heartbeats and amibugous result errors immediately.
> 						if err == errSkippedHeartbeat {
> 							log.Infof(ctx, "skipped node liveness heartbeat; retrying")
> ```

nit: can you use `err` in this message?

---

*[pkg/storage/node_liveness.go, line 254 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifRA_iQkMgLfS8FCYM:-KifRA_iQkMgLfS8FCYN:bmstarc) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ffff6f749043cfd956537b684c9b1b6d58a047/pkg/storage/node_liveness.go#L254)):*
> ```Go
> 							continue
> 						} else if _, ok := err.(*roachpb.AmbiguousResultError); ok {
> 							log.Infof(ctx, "ambiguous node liveness heartbeat (%v); retrying", err)
> ```

This will print:
`"ambiguous node liveness heartbeat (result is ambiguous (...)); retrying"`
perhaps we can do better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-:-KifR26jmuptqjgh8abg:b-80jztk)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/node_liveness.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifS61gevWBommB1iki:-KifS61gevWBommB1ikj:b-bkvoxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ffff6f749043cfd956537b684c9b1b6d58a047/pkg/storage/node_liveness.go#L249)):*
> ```Go
> 					}
> 					if err := nl.heartbeatInternal(ctx, liveness, incrementEpoch); err != nil {
> 						// Retry skipped heartbeats and amibugous result errors immediately.
> ```

s/amibugous/ambiguous

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-:-KifTZZk9LZ3QPRZM86g:bnfp4nl)*

**Comment by spencerkimball** [comment]
OK, had to rearrange the loop for ambiguous result errors to catch them in a place that's simpler to unittest and also notices the need to retry on manual heartbeats, such as those sent when acquiring a range lease.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/node_liveness.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifS61gevWBommB1iki:-KifTRq5-98lq_KMfTN9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ffff6f749043cfd956537b684c9b1b6d58a047/pkg/storage/node_liveness.go#L249)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/amibugous/ambiguous
</blockquote></details>

Done.

---

*[pkg/storage/node_liveness.go, line 251 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifR84afNMDs5ypa78w:-KifTS5GPWZIFaRFEAa_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ffff6f749043cfd956537b684c9b1b6d58a047/pkg/storage/node_liveness.go#L251)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: can you use `err` in this message?
</blockquote></details>

Done.

---

*[pkg/storage/node_liveness.go, line 254 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifRA_iQkMgLfS8FCYM:-KifUB43i_NJa5zUNqY-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ffff6f749043cfd956537b684c9b1b6d58a047/pkg/storage/node_liveness.go#L254)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This will print:
`"ambiguous node liveness heartbeat (result is ambiguous (...)); retrying"`
perhaps we can do better?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-:-KifT13gLBzRDv4zNjUA:b6bly5f)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/node_liveness.go, line 350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifXt8vj5U0Bhi6GUvq:-KifXt8vj5U0Bhi6GUvr:b-96t5jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93d955765ea9f65ff0d85e01eaae922f086215e/pkg/storage/node_liveness.go#L350)):*
> ```Go
> 	for {
> 		err := hbFn()
> 		// Retry ambiguous result errors immediately.
> ```

would help to elaborate here that doing this in the caller would result in backoff.

---

*[pkg/storage/node_liveness.go, line 352 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifXaSg8yockccMrHkt:-KifXaSg8yockccMrHku:b7todlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93d955765ea9f65ff0d85e01eaae922f086215e/pkg/storage/node_liveness.go#L352)):*
> ```Go
> 		// Retry ambiguous result errors immediately.
> 		if _, ok := err.(*roachpb.AmbiguousResultError); ok {
> 			log.Infof(ctx, "heartbeat experienced %v; retrying", err)
> ```

%s for consistency

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-:-KifY49JCJLuOyA-q08l:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/node_liveness_test.go, line 688 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifYbEdU_ZI8yhqURZX:-KifYbEdU_ZI8yhqURZY:b62cqu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93d955765ea9f65ff0d85e01eaae922f086215e/pkg/storage/node_liveness_test.go#L688)):*
> ```Go
> 	if err := nl.Heartbeat(context.Background(), l); err != nil {
> 		t.Fatal(err)
> 	}
> ```

It's probably worth checking that `etCount` actually got incremented, just to make sure the test machinery is working

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-:-KifYgq83oomtWhkt1qL:bnfp4nl)*

**Comment by a-robinson** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/node_liveness.go, line 350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifXt8vj5U0Bhi6GUvq:-KifdDSjt7TmX2SZwHtQ:bc6cs0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93d955765ea9f65ff0d85e01eaae922f086215e/pkg/storage/node_liveness.go#L350)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

would help to elaborate here that doing this in the caller would result in backoff.
</blockquote></details>

Not sure that makes sense. There is a comment here that we're retrying immediately for these errors as opposed to backing off.

---

*[pkg/storage/node_liveness.go, line 352 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifXaSg8yockccMrHkt:-KifdJPxfY1DO_cK9Vr_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93d955765ea9f65ff0d85e01eaae922f086215e/pkg/storage/node_liveness.go#L352)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

%s for consistency
</blockquote></details>

Done.

---

*[pkg/storage/node_liveness_test.go, line 688 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362#-KifYbEdU_ZI8yhqURZX:-KifdJs6WMSteV5irL1r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93d955765ea9f65ff0d85e01eaae922f086215e/pkg/storage/node_liveness_test.go#L688)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It's probably worth checking that `etCount` actually got incremented, just to make sure the test machinery is working
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15362)*

**Pull request merged**
