### PR TITLE
cmd/roachtest: add lib/pq roachtest

### PR DESCRIPTION
**Pull request by asubiotto**
Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I tried using `go-junit-report` tool for go-pg, and it mostly works with our XML parsing
```
Tests run against gopg v9.0.0-beta.15
30 Total Tests Run
24 tests passed
6 tests failed
0 tests skipped
0 tests ignored
0 tests passed unexpectedly
6 tests failed unexpectedly
0 tests expected failed but skipped
39 tests expected failed but not run
For a full summary look at the gopg artifacts 

21:59:47 orm_helpers.go:109: ------------------------
21:59:47 orm_helpers.go:129: 

Here is new gopg blacklist that can be used to update the test:

var gopgBlackList19_2 = blacklist{
  "v9.ExampleDB_Model_postgresArrayStructTag": "unknown",
  "v9.TestBigColumn": "unknown",
  "v9.TestConversion": "unknown",
  "v9.TestGinkgo": "unknown",
  "v9.TestGocheck": "unknown",
  "v9.TestUnixSocket": "unknown",
}
```
The issue is that `TestGinkgo` is like the main test that contains 134 of others that I mentioned before, and with this tool it is treated as a single test which is not very useful. I think I will actually use my initial approach and this tool to populate the report.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-:-LqmZ8Hq5gye9y3PEDsL:b-r9kkut)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/libpq.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-LqmZVAq3Pg0B2lXCOp8:-LqmZVAq3Pg0B2lXCOp9:bmpsrf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L28)):*
> ```Go
> 		node := c.Node(1)
> 		t.Status("setting up cockroach")
> 		c.Put(ctx, cockroach, "./cockroach", c.All())
> ```

Do you know how to stage a particular version of cockroach? It seems that whenever we run the roachtest manually, the local `cockroach-linux...` will be staged.
___
*[pkg/cmd/roachtest/libpq.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lqma5PR5MhOwq6j07JJ:-Lqma5PR5MhOwq6j07JK:bj1bzgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L39)):*
> ```Go
> 		c.l.Printf("Latest lib/pq release is %s.", latestTag)
> 		if err := repeatRunE(
> 			ctx, c, node, "add recent go version repository", "sudo add-apt-repository -y ppa:longsleep/golang-backports",
> ```

Are we ok with using the latest go version? Maybe in order to reduce the flakiness, we should use the same version that is used for building the cockroach?
___
*[pkg/cmd/roachtest/libpq.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lqmaq4N1dHdQBPXK4XB:-Lqmaq4N1dHdQBPXK4XC:bseay2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L96)):*
> ```Go
> 			ctx,
> 			node,
> 			fmt.Sprintf("cd %s && PGPORT=26257 PGUSER=root PGSSLMODE=disable go test -v 2>&1 | %s/bin/go-junit-report > %s/report.xml", libPQPath, goPath, resultsPath),
> ```

Are these environment variables specific to lib/pq?

**Review by asubiotto — COMMENTED** [review]
Good point, that's unfortunate.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-:-Lqqe9h_EqV7B5PYE-p-:bgqzr28)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/libpq.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-LqmZVAq3Pg0B2lXCOp8:-LqqdLjJ4qHpZSOmg7Wu:b1vxy2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L28)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do you know how to stage a particular version of cockroach? It seems that whenever we run the roachtest manually, the local `cockroach-linux...` will be staged.
</blockquote></details>

You would specify the binary name with `--cockroach=` when running the roachtest. I think most (if not all) roachtests don't choose the version to run under, but they do get this information with `fetchCockroachVersion` and adjust their behavior accordingly.
___
*[pkg/cmd/roachtest/libpq.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lqma5PR5MhOwq6j07JJ:-LqqcnUoApHmSumgnJ_z:b-ntrbfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L39)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Are we ok with using the latest go version? Maybe in order to reduce the flakiness, we should use the same version that is used for building the cockroach?
</blockquote></details>

I don't see why not, this is only the go version used to run the lib/pq tests.
___
*[pkg/cmd/roachtest/libpq.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lqmaq4N1dHdQBPXK4XB:-LqqcxID-1Ol4Mxk3ywX:bx7qzg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L96)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Are these environment variables specific to lib/pq?
</blockquote></details>

Yes, they are used by the tests.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/cmd/roachtest/libpq.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-LqqwVRT5sqinh543l1y:-LqqwVRT5sqinh543l1z:b-2xbgin) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L30)):*
> ```Go
> 		c.Put(ctx, cockroach, "./cockroach", c.All())
> 		c.Start(ctx, t, c.All())
> ```

it could be useful to put this here (i'm assuming these tests also create/alter/drop tables very frequently, like how hibernate does)

```
		version, err := fetchCockroachVersion(ctx, c, node[0])
		if err != nil {
			t.Fatal(err)
		}

		if err := alterZoneConfigAndClusterSettings(ctx, version, c, node[0]); err != nil {
			t.Fatal(err)
		}
```

**Review by asubiotto — COMMENTED** [review]
This is now RFAL, all relevant failures have been classified. Nearly all failures have associated issue numbers. It doesn't make sense to create issues for some failures, but they are commented with their failure reason.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-:-Lr9ppHR52Ngtdg9TEJ1:b-eunukd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/cmd/roachtest/libpq.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-LqqwVRT5sqinh543l1y:-Lr9poDSCPxXfLf9Pxxm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L30)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it could be useful to put this here (i'm assuming these tests also create/alter/drop tables very frequently, like how hibernate does)

```
		version, err := fetchCockroachVersion(ctx, c, node[0])
		if err != nil {
			t.Fatal(err)
		}

		if err := alterZoneConfigAndClusterSettings(ctx, version, c, node[0]); err != nil {
			t.Fatal(err)
		}
```
</blockquote></details>

Done.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/cmd/roachtest/libpq.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lr9tczz7nXlwkc_OhSJ:-Lr9tczz7nXlwkc_OhSK:b-1izedj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08c0fd936481ee452ee1de01ac081c13d4ca149/pkg/cmd/roachtest/libpq.go#L97)):*
> ```Go
> 		}
> 
> 		_ = c.RunE(ctx, node, fmt.Sprintf("mkdir -p %s", resultsDir))
> ```

do you need to also delete the old result dir ?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

___
*[pkg/cmd/roachtest/libpq.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lr9tczz7nXlwkc_OhSJ:-LrAMtDQ7pVFdOdjBCO3:b-x11opq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08c0fd936481ee452ee1de01ac081c13d4ca149/pkg/cmd/roachtest/libpq.go#L97)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

do you need to also delete the old result dir ?
</blockquote></details>

Don't think it's necessary, we just need to assert that it exists. If it does, we would overwrite the report.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, @rohany, and @yuzefovich)

___
*[pkg/cmd/roachtest/libpq.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lqma5PR5MhOwq6j07JJ:-LrAgsZ-0FionCDz19Ci:b-kn731o) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L39)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't see why not, this is only the go version used to run the lib/pq tests.
</blockquote></details>

Ok, I think we should unify this then like you mentioned previously. Let's merge your PR first and then I'll extract a function and reuse it for gopg.
___
*[pkg/cmd/roachtest/libpq.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lqmaq4N1dHdQBPXK4XB:-LrAhJ4tB8q1ArvaHUnC:bzepp9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L96)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yes, they are used by the tests.
</blockquote></details>

I believe you can now remove `grep -v ...` part since the parsing of XML has been enhanced.
___
*[pkg/cmd/roachtest/libpq_blacklist.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-LrAhdYc53LOt9u_xhGq:-LrAhdYd8bqDZqOW_OpD:b-l5i8h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08c0fd936481ee452ee1de01ac081c13d4ca149/pkg/cmd/roachtest/libpq_blacklist.go#L25)):*
> ```Go
> 	// TODO(asubiotto): The upstream fix has been submitted so this can be removed
> 	// from blacklists once we test with a newer version of lib/pq.
> 	"pq.TestCloseBadConn":                "unknown",
> ```

I think we should extract all "unknown" ones into the ignore list. This way if a new blacklist is automatically populated, we can just paste it over the existing one without losing the comments.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

___
*[pkg/cmd/roachtest/libpq.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-Lqmaq4N1dHdQBPXK4XB:-LrFaCPIBmvOniZTOgNk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/331cae60bd2fd566938ff5dfccdf06bff6677627/pkg/cmd/roachtest/libpq.go#L96)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I believe you can now remove `grep -v ...` part since the parsing of XML has been enhanced.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/libpq_blacklist.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-LrAhdYc53LOt9u_xhGq:-LrFaD2J8z3K5TYitCya:b-avfod) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08c0fd936481ee452ee1de01ac081c13d4ca149/pkg/cmd/roachtest/libpq_blacklist.go#L25)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we should extract all "unknown" ones into the ignore list. This way if a new blacklist is automatically populated, we can just paste it over the existing one without losing the comments.
</blockquote></details>

Done. `ignoreList`s don't seem to be easily supported by the java summarization code so just left a TODO.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

The only thing is that as was discussed, some of the "unknowns" might deserve an issue.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41478#-:-LrG-MSgDG_u_H6wIeiL:b-1v74mx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

**Comment by asubiotto** [comment]
Done, there are no more `unknown`s.

TFTR

bors r=yuzefovich

**Comment by asubiotto** [comment]
Canceled for some reason, retrying

bors r=yuzefovich

**Comment by jordanlewis** [comment]
Agent was out of disk space again.

bors r+

**Pull request merged**
