### PR TITLE
sql: Add `TIMESTAMP WITH TIME ZONE` type that includes offset

### LINKED ISSUE #5863: sql: support `TIMESTAMP WITH(OUT) TIME ZONE`
## The spec says:

>          6) If the data type of CR is TIME or TIMESTAMP, then the implicit
>             time zone of the data is the current default time zone for the
>             SQL-session.
> 
>          7) If the data type of CR is TIME WITH TIME ZONE or TIMESTAMP WITH
>             TIME ZONE, then the time zone of the data is the time zone rep-
>             resented in the value of CR.

## When inserting a timestamp / parsing a value:
`WITHOUT ZONE` (or no modifier) does not consider the session offset.
Open Question: should it even accept a ts that has an explicit offset? If so, what should it do? (postgres does, and silently ignores it(!))

 `WITH ZONE` should use supplied offset if present to calculate UTC time and insert UTC, and should otherwise use the session offset to calculate UTC and insert that.

## When returning a timestamp:
`WITHOUT ZONE` (or no modifier) should *not* include an offset (we currently do). The session offset isn't considered and no shift is required.
`WITH ZONE` *should* include an offset when returned, and it should ideally be the session offset, thus the timestamp should be shifted as needed, since the stored time is UTC.

### LINKED ISSUE #5953: sql: error parsing string as timestamp through Postgres JDBC driver
ERROR: param $3: could not parse string "2016-04-07 23:00:02.965000 +00:00:00" as timestamp

### PR DESCRIPTION
**Pull request by dt**
A `TIMESTAMP WITH TIME ZONE` should be rendered with an offset and when sent
using pgwire should use the `timestamptz` OID, while a plain `TIMESTAMP` should
have no offset included and be sent with the `timestamp` OID.

This is important because some clients (eg Java) follow the spec to the letter
and fail to parse offsets in plain `timestamp` values.

Closes #6138.

This is an alternative to the approach in #6138: This introduces a new, separate, disparate type  (generally called `timestamptz` internally) for timestamps that include offsets when rendered, and can be cast to/from the plain `timestamp` type where needed. Both types still map to the same `columnType.Kind` though.

For now, a cast from string to either type has the same behavior (eg a present offset will be used to calculate UTC) but in the future we may choose to error on an offset in a non-tz string.

Unlike #6138, this PR does not include changing the rendering to send timestamps _in the session offset_ -- that's an easy follow-on change once the machinery for choosing if they should include an offset at all is in place.

Closes #5863.
Closes #5953.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6165)

### CODE REVIEW

**Comment by dt** [comment]
Recap of why I'm suggesting an alternative approach to #6138:

Separate types allow for picking between separate operator and function signatures, meaning the information about how to render the values flows naturally though the type system, which is where the single type approach got a little messy.

Specifically, a `resultColumn` needs to send the client the OID indicating which form it contains and then all values for that column must be rendered matching that. This gets tricky since that `resultColumn`'s type comes from typing an expression like `timestampCol + interval` and that operator has a static return type regardless of flags in the value actually passed at execution (e.g. those could come from a case or something).

**Comment by petermattis** [comment]
I'm leaning towards this approach. It does seem cleaner to explicit model a difference in the types so that the zone information is properly propagated through. 

---

Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/parser/datum.go, line 748 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9zbuOO05K50FZtDZ:-KFo9zbuOO05K50FZtD_:-795976593) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/datum.go#L748)):*
I think this should be spelled `DTimestampTZ` because `Time` and `Zone` are separate words.

---

*[sql/parser/datum.go, line 759 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9ULA3a3LA4ZEutMC:-KFo9ULB_oaC-hGKXzYx:-1987012748) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/datum.go#L759)):*
I wonder if this should also return true for `(*DTimestamp)`. Take a look at how this function (and `Compare`) are used by `analyzeExpr`. 

---

*[sql/parser/eval.go, line 199 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFoAAptcv0bch7kG0mI:-KFoAAptcv0bch7kG0mJ:396817034) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/eval.go#L199)):*
Don't you need to add entries to `CmpOps` as well?

---

*[sql/parser/eval.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFoALTT-qx4F8Rcn0oi:-KFoALTT-qx4F8Rcn0oj:1898325951) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/eval.go#L260)):*
Should we allow subtraction between `TIMESTAMP` and `TIMESTAMPTZ`?

---

*[sql/parser/eval.go, line 1150 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFoAfquVQEAuiG3UfdT:-KFoAfquVQEAuiG3UfdU:-1280709487) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/eval.go#L1150)):*
Ah, this is an advantage of having a separate type for `TIMESTAMPTZ`. 

---

*[sql/parser/types.go, line 117 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9sEuDNr9e7VlaZNI:-KFo9sEvP8_F1WkYRKDc:-603568854) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/types.go#L117)):*
Is a separate type needed here? The previous `withZone` approach seemed fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-:-KFoAzs9LYCILYfzoIxr:-701654088)*

**Comment by tamird** [comment]
Reviewed 17 of 17 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/structured.proto, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo-fbnJWb0xb8Sm4od:-KFo-fbo12iUfnwKIbo0:-492989054) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7dbedbb10356080eea4a245809d19c1f43d4d6/sql/structured.proto#L46)):*
`// TIMESTAMP.` above this line. also, why not have a new `Kind` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165)*

**Comment by dt** [comment]
Review status: 3 of 19 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/structured.proto, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo-fbnJWb0xb8Sm4od:-KFoGHZR1TQ7LaYrsRxa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7dbedbb10356080eea4a245809d19c1f43d4d6/sql/structured.proto#L46)):*
Done.

---

*[sql/parser/datum.go, line 748 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9zbuOO05K50FZtDZ:-KFoIk8rU9pjbgH_hAiV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/datum.go#L748)):*
Done.

---

*[sql/parser/datum.go, line 759 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9ULA3a3LA4ZEutMC:-KFoIe0n6BSpgWl-KHu8:1685500454) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/datum.go#L759)):*
My initial thinking is we start with no implicit mixing of types, then, if we find requiring explicit casts is too burdensome, we add support later.

---

*[sql/parser/eval.go, line 199 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFoAAptcv0bch7kG0mI:-KFoIVeI-QJWHLn5btIP:-1635890994) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/eval.go#L199)):*
Done (and added tests).

---

*[sql/parser/eval.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFoALTT-qx4F8Rcn0oi:-KFoBtugaSb7I3iCoH0m:-614548421) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/eval.go#L260)):*
ditto above about starting with explicit casts.

---

*[sql/parser/types.go, line 117 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9sEuDNr9e7VlaZNI:-KFoBVAmbViNvcgRKGrO:1137605440) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/types.go#L117)):*
My thinking was  separate type means I can let the compiler make sure I catch all the places I should be handling each case, rather than hoping I remember to always check `withZone`, but I don't feel that strongly about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-:-KFoM2Tl6n2rEcMANnqY:1417088721)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/datum.go, line 759 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9ULA3a3LA4ZEutMC:-KFoLP9oLbgiTjyrEfI7:747346906) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/datum.go#L759)):*
This affects index selection which is somewhat less obvious than regular operations on values. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-:-KFoMwHaj049Cgm2pYiB:1417088721)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/datum.go, line 759 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9ULA3a3LA4ZEutMC:-KFohk3_DPnJFrsjn6Ug:-629476285) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/datum.go#L759)):*
Seem like where its checking mixed type comparisons wouldn't even be reachable as it stands, since we don't have those comparison ops?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/datum.go, line 759 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165#-KFo9ULA3a3LA4ZEutMC:-KFojRDh_4j32Uzp1gOn:-465075601) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a48d4071c26661620256bbf1154effc483a0ed1/sql/parser/datum.go#L759)):*
Oh, good point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6165)*

**Pull request merged**
