### PR TITLE
Added new generator function for querying sstables.

### PR DESCRIPTION
**Pull request by raggar**
Currently, SSTable-level statistics are difficult to obtain and require
work from the customer and support teams to find appropriate files to
pull from the filesystem to send to us. As a result, the new SRF added
in this pull-request returns SSTable-level statistics that overlap a
provided key span for a certain node and store id.

image

RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/query_sst_metrics.md

Informs: #102604
Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-:-NYTkSar7Vr6kwWCF5Av:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RahulAggarwal1016)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYThw_J8MpEIBrvH3pq:-NYThw_J8MpEIBrvH3pr:bnqidl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3130)):*
> ```Go
> )
> 
> type tableMetricsIterator struct {
> ```

[nit] worth a comment here
// tableMetricsIterator implements tree.ValueGenerator; it returns a set of SSTable metrics (one per row).
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTi-F68YCwvjfn25Sm:-NYTi-F68YCwvjfn25Sn:bnqo42h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3140)):*
> ```Go
> 	end     []byte
> }
> ```

[nit] add a type assertion `var _ tree.ValueGenerator = (*tableMetricsIterator)(nil)`
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTjGRCCDnUwBS4VC4q:-NYTjGRCCDnUwBS4VC4r:b-wx8kfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3149)):*
> ```Go
> // Start implements the tree.ValueGenerator interface.
> func (tmi *tableMetricsIterator) Start(ctx context.Context, _ *kv.Txn) error {
> 	var err error = nil
> ```

`= nil` not necessary
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTjYoR7ej8gNxeJG8C:-NYTjYoR7ej8gNxeJG8D:bt3jp17) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3151)):*
> ```Go
> 	var err error = nil
> 	tmi.metrics, err = tmi.evalCtx.GetTableMetrics(ctx, tmi.nodeID, tmi.storeID, tmi.start, tmi.end)
> 	return err
> ```

It would be nice to sort the output by node, then store, then level, then filenum
___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTjfhy1JwoqfXoGl9d:-NYTjfhy1JwoqfXoGl9e:bbxwv9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins_test.go#L63)):*
> ```Go
> 	defer s.Stopper().Stop(ctx)
> 
> 	_, err := db.Query(` select * from crdb_internal.sstable_metrics('1', '1', 'a', 'd')`)
> ```

We will need better tests.. In particular, we need to test the case where the 'target' node is not the same node.
I would start a test cluster with 3 nodes (node 1 will have store 1, node 2 will have store 2 etc), then create some tables and write some data, do `WaitForFullReplication`, then
try various queries and verify that we get at least one entry, and verify as many fields as we can.

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTjfhy1JwoqfXoGl9d:-NYTq3DVBLYApa_4YSbN:b6nh8uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins_test.go#L63)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We will need better tests.. In particular, we need to test the case where the 'target' node is not the same node.
I would start a test cluster with 3 nodes (node 1 will have store 1, node 2 will have store 2 etc), then create some tables and write some data, do `WaitForFullReplication`, then
try various queries and verify that we get at least one entry, and verify as many fields as we can.
</blockquote></details>

yeah im currently working on the testing part

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTi-F68YCwvjfn25Sm:-NYUN62s-V1mRg9WI-Zw:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3140)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a type assertion `var _ tree.ValueGenerator = (*tableMetricsIterator)(nil)`
</blockquote></details>

done

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYThw_J8MpEIBrvH3pq:-NYUN75F4IP6DPpBARgf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] worth a comment here
// tableMetricsIterator implements tree.ValueGenerator; it returns a set of SSTable metrics (one per row).
</blockquote></details>

done

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTjGRCCDnUwBS4VC4q:-NYUN7vH0627GZ3OdrkC:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3149)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`= nil` not necessary
</blockquote></details>

fixed

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RahulAggarwal1016)

___
*[`pkg/storage/enginepb/rocksdb.proto` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYUVfI-E9hgS6SaFgba:-NYUVfI-E9hgS6SaFgbb:bknp00l) ([raw file](https://github.com/cockroachdb/cockroach/blob/147374f4743945f73efc3c0f74caaca6896cccfe/pkg/storage/enginepb/rocksdb.proto#L23)):*
> ```proto
>   // table_id is the sstable's file number
>   uint64 table_id = 2 [(gogoproto.customname) = "TableID"];
>   // table_info is represents SSTableInfo.Properties
> ```

[nit] `table_info` contains sstable properties, encoded as JSON. Maybe rename to `table_info_json / TableInfoJSON`

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/storage/enginepb/rocksdb.proto` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYUVfI-E9hgS6SaFgba:-NYUqqBO6DFSdYdPQoD8:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/147374f4743945f73efc3c0f74caaca6896cccfe/pkg/storage/enginepb/rocksdb.proto#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `table_info` contains sstable properties, encoded as JSON. Maybe rename to `table_info_json / TableInfoJSON`
</blockquote></details>

fixed

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RahulAggarwal1016)

___
*[`pkg/storage/pebble.go` line 1992 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtEzdk8MGcmjEBSndV:-NYtEzdk8MGcmjEBSndW:b-9nlcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/storage/pebble.go#L1992)):*
> ```Go
> // GetTableMetrics implements the Engine interface.
> func (p *Pebble) GetTableMetrics(start, end roachpb.Key) ([]enginepb.SSTableMetricsInfo, error) {
> 	tableInfo, err := p.db.SSTables()
> ```

We're missing the option to filter by key
___
*[`pkg/storage/enginepb/rocksdb.proto` line 23 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtF2Vr17kUVnDyjFZ7:-NYtF2Vr17kUVnDyjFZ8:b12unvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/storage/enginepb/rocksdb.proto#L23)):*
> ```proto
>   // table_id is the sstable's file number
>   uint64 table_id = 2 [(gogoproto.customname) = "TableID"];
>   // table_info is represents SSTableInfo.Properties
> ```

[nit] Comment still not updated, I suggest: "table_info_json contains sstable properties, encoded as JSON."
___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 62 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtFRok9yAkaHweRuky:-NYtFRok9yAkaHweRukz:b1zk7f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/sql/sem/builtins/generator_builtins_test.go#L62)):*
> ```Go
> }
> 
> func TestGetSSTableMetrics(t *testing.T) {
> ```

make sure you run the new test under stress to verify it's not flaky
___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 99 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtFNMA8EjrT8bP-W4N:-NYtFNMB5udTqWF-yLep:bl89rxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/sql/sem/builtins/generator_builtins_test.go#L99)):*
> ```Go
> 		var metrics []byte
> 
> 		require.NoError(t, rows.Scan(&nodeID, &storeID, &level, &fileNum, &metrics))
> ```

Maybe verify `nodeID` and `storeID`

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/storage/pebble.go` line 1992 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtEzdk8MGcmjEBSndV:-NYtKFF2DFJwlAqqgGZv:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/storage/pebble.go#L1992)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We're missing the option to filter by key
</blockquote></details>

fixed

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/storage/enginepb/rocksdb.proto` line 23 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtF2Vr17kUVnDyjFZ7:-NYtKGPSBZIZWeC06Gjd:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/storage/enginepb/rocksdb.proto#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Comment still not updated, I suggest: "table_info_json contains sstable properties, encoded as JSON."
</blockquote></details>

fixed

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 62 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtFRok9yAkaHweRuky:-NYtKHVoAQ2ddCaushh_:b-8xcdvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/sql/sem/builtins/generator_builtins_test.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

make sure you run the new test under stress to verify it's not flaky
</blockquote></details>

yup, checked!

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 99 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYtFNMA8EjrT8bP-W4N:-NYtKJyG4fHwP0i_tqT9:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c059bd7a32aa5c19e7fa0c0c16fe377fae27720d/pkg/sql/sem/builtins/generator_builtins_test.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe verify `nodeID` and `storeID`
</blockquote></details>

done

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NYTjYoR7ej8gNxeJG8C:-NYtKqZM6_McbjDqa47K:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dd3e554db885586f57890ae083bb1ab2ff0ee77/pkg/sql/sem/builtins/generator_builtins.go#L3151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It would be nice to sort the output by node, then store, then level, then filenum
</blockquote></details>

done

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-:-NZCkYnICaiLKkCoHj6h:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens, @mgartner, and @RahulAggarwal1016)

___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 104 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NZCkWfkB8KlIbgewBVy:-NZCkWfkB8KlIbgewBVz:b-e5915b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f030127d04f36fdb2c456dd9b07e15177edf44c/pkg/sql/sem/builtins/generator_builtins_test.go#L104)):*
> ```Go
> 	}
> 
> 	for idx, id := range tc.NodeIDs() {
> ```

Very nice test, well done!
___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 126 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NZCkJbf90yaE0kqhy0N:-NZCkJbf90yaE0kqhy0O:b-xfmszt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f030127d04f36fdb2c456dd9b07e15177edf44c/pkg/sql/sem/builtins/generator_builtins_test.go#L126)):*
> ```Go
> 
> 		rows := sqlDB.Query(t, fmt.Sprintf(`
> 	 SELECT * FROM crdb_internal.sstable_metrics(
> ```

[supernit] inconsistent indentation

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 104 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NZCkWfkB8KlIbgewBVy:-NZCoI72-v0DDfevCS2Y:bd5l6mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f030127d04f36fdb2c456dd9b07e15177edf44c/pkg/sql/sem/builtins/generator_builtins_test.go#L104)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Very nice test, well done!
</blockquote></details>

thanks!

**Review by raggar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104739)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/sem/builtins/generator_builtins_test.go` line 126 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104739#-NZCkJbf90yaE0kqhy0N:-NZCoJ_aEDjWlVqSk-oO:b-qssebz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f030127d04f36fdb2c456dd9b07e15177edf44c/pkg/sql/sem/builtins/generator_builtins_test.go#L126)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[supernit] inconsistent indentation
</blockquote></details>

fixed

**Pull request merged**
