### PR TITLE
kvserver: don't reset local keys in tscache on r1 lease move

### PR DESCRIPTION
**Pull request by andreimatei**
applyReadSummaryToTimestampCache had a bug in how it dealt with r1's
descriptor: it bumped the timestamp cache over the whole keyspace that
the descriptor declared ([\x00,\x02)). That's bad, because it includes
the \x01... keys. That's the "local" keyspace, which doesn't belong to
any range in particular (so, r1's descriptor is arguably lying). Bumping
the timestamp cache over the local keyspace had the consequence (maybe
among others) that the txn tombstone keys were included, leading to
transactions being aborted when they came to create their txn record
because the bumped timestamp cache was saying that there might have been
a tombstone in there.

Release note: A bug causing transactions to be spuriously aborted in
rare circumstances has been fixed.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_tscache.go, line 608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MaifqlB-xL4Ffe0f3bc:-MaifqlB-xL4Ffe0f3bd:b-adwlus) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e827952ee4fbeeb9acb55c879959d794a70d09f/pkg/kv/kvserver/replica_tscache.go#L608)):*
> ```Go
> 		s.Local.LowWater,
> 	)
> 	//tc.SetLowWater(
> ```

Remove this commented-out call. 
___
*[pkg/roachpb/metadata.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MaifCXg3bv-zJ0xUPmz:-MaifCXg3bv-zJ0xUPn-:b-y2tpm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e827952ee4fbeeb9acb55c879959d794a70d09f/pkg/roachpb/metadata.go#L203)):*
> ```Go
> 
> // KeySpan returns the keys covered by this range. Local keys are not included.
> func (r *RangeDescriptor) KeySpan() RSpan {
> ```

This method seems like a good idea (or maybe just one for the StartKey?). Should we start to mandate its use instead of direct access to StartKey?

Both callers of this method immediately call AsRawKey on its results. Should we build that in to the method itself? (I think probably not)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_tscache.go, line 608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MaifqlB-xL4Ffe0f3bc:-MajLF1g-kYD_tbt50S-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e827952ee4fbeeb9acb55c879959d794a70d09f/pkg/kv/kvserver/replica_tscache.go#L608)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove this commented-out call. 
</blockquote></details>

done
___
*[pkg/roachpb/metadata.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MaifCXg3bv-zJ0xUPmz:-MajLJrY3OGHy_va4R-z:bgcwv6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e827952ee4fbeeb9acb55c879959d794a70d09f/pkg/roachpb/metadata.go#L203)):*
> This method seems like a good idea (or maybe just one for the StartKey?). Should we start to mandate its use instead of direct access to StartKey?

I didn't feel like boiling the ocean. What I think we should do is what I think you've also suggested - change r1's descriptor to start from `\x02`. But I don't wanna start pulling on that at the moment.

> Both callers of this method immediately call AsRawKey on its results. Should we build that in to the method itself? (I think probably not)

I think not... If anything, those callers should be changed to deal in `RKeys`, but I don't know if that's worth it.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-:-Mak17FTANTEn8f5_2ZG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/kv/kvserver/replica_tscache.go, line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-Mak0L-r4QlHRvAqj4Pn:-Mak0L-s2vHP8UjR493t:bgeiw7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3355b8e23e8a572e9571f3f3012c69862e5db61f/pkg/kv/kvserver/replica_tscache.go#L609)):*
> ```Go
> 		uuid.Nil, /* txnID */
> 	)
> 	userKeys := desc.KeySpan()
> ```

Should we be using this to generate the span above as well?
```
tc.Add(
		keys.MakeRangeKeyPrefix(userKey.Key),
		keys.MakeRangeKeyPrefix(userKey.EndKey),
		s.Local.LowWater,
		uuid.Nil, /* txnID */
)
```
___
*[pkg/roachpb/metadata.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MaifCXg3bv-zJ0xUPmz:-Mak0k6mD8aVyX2_xm6G:b8fh2sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e827952ee4fbeeb9acb55c879959d794a70d09f/pkg/roachpb/metadata.go#L203)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> This method seems like a good idea (or maybe just one for the StartKey?). Should we start to mandate its use instead of direct access to StartKey?

I didn't feel like boiling the ocean. What I think we should do is what I think you've also suggested - change r1's descriptor to start from `\x02`. But I don't wanna start pulling on that at the moment.

> Both callers of this method immediately call AsRawKey on its results. Should we build that in to the method itself? (I think probably not)

I think not... If anything, those callers should be changed to deal in `RKeys`, but I don't know if that's worth it.
</blockquote></details>

Did you consider adding this logic to `RSpan` instead of creating another method?

**Review by andreimatei — COMMENTED** [review]
I've changed `collectReadSummaryFromTimestampCache` too. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-:-MbmpNy55lISj1PIgFcj:b-45qc9d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_tscache.go, line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-Mak0L-r4QlHRvAqj4Pn:-MbhgUZ01bW2A-wQ3V8w:b-qp1fb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3355b8e23e8a572e9571f3f3012c69862e5db61f/pkg/kv/kvserver/replica_tscache.go#L609)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we be using this to generate the span above as well?
```
tc.Add(
		keys.MakeRangeKeyPrefix(userKey.Key),
		keys.MakeRangeKeyPrefix(userKey.EndKey),
		s.Local.LowWater,
		uuid.Nil, /* txnID */
)
```
</blockquote></details>

I've considered that, but I got cold feet. Doing this change would mean declaring that the start of the range-local keyspace of r1 would change from `/Local/Range/Min` to  `/Local/Range/Meta1/""` (i.e `\x01\x00 -> \x01\x02`.
I don't know what the consequences of that would be. As far as the bug being fixed by this patch is concerned, this change is not necessary. The `\x01\x00 -> \x01\x02` local key space does not belong to anyone other that r1, so it would be technically correct for r1 to use it. And perhaps it does use it; there are places in the code where we do `keys.MakeRangeKeyPrefix(st.LeftDesc.StartKey)` (e.g. [here](https://github.com/cockroachdb/cockroach/blob/d0ebb7f1952b3da714bc4fa801c013cfdce52300/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L119)).

Thoughts?
___
*[pkg/roachpb/metadata.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MaifCXg3bv-zJ0xUPmz:-MbhhQEw24O2igqueNOZ:bup41ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e827952ee4fbeeb9acb55c879959d794a70d09f/pkg/roachpb/metadata.go#L203)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you consider adding this logic to `RSpan` instead of creating another method?
</blockquote></details>

I'm scared, because that function is used `ContainsKey` and such. I'm afraid of breaking some iteration over the key space. But I've added a TODO...

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-:-MbrPzJ29XMcVbZNi8Lz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/kv/kvserver/replica_tscache.go, line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-Mak0L-r4QlHRvAqj4Pn:-MbrPekr8Fs119NIFAHC:b-ei05h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3355b8e23e8a572e9571f3f3012c69862e5db61f/pkg/kv/kvserver/replica_tscache.go#L609)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I've considered that, but I got cold feet. Doing this change would mean declaring that the start of the range-local keyspace of r1 would change from `/Local/Range/Min` to  `/Local/Range/Meta1/""` (i.e `\x01\x00 -> \x01\x02`.
I don't know what the consequences of that would be. As far as the bug being fixed by this patch is concerned, this change is not necessary. The `\x01\x00 -> \x01\x02` local key space does not belong to anyone other that r1, so it would be technically correct for r1 to use it. And perhaps it does use it; there are places in the code where we do `keys.MakeRangeKeyPrefix(st.LeftDesc.StartKey)` (e.g. [here](https://github.com/cockroachdb/cockroach/blob/d0ebb7f1952b3da714bc4fa801c013cfdce52300/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L119)).

Thoughts?

</blockquote></details>

This sounds reasonable to me. I also don't know what the consequences of that would be, and it doesn't sound like there's a reason to make the change.
___
*[pkg/roachpb/metadata.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MbrPwh-Ax-eLQa7OO7S:-MbrPwh0ALOGsg0HETl5:brxpmjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/94022fd088b2728f1d2e1a14660bdbc3207799c2/pkg/roachpb/metadata.go#L205)):*
> ```Go
> //
> // TODO(andrei): Consider if this logic should be lifted to
> // RangeDEscriptor.RSpan(). Or better yet, see if we can changes things such
> ```

`RangeDescriptor`

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-:-McA9qtXEHN70ETkcaHn:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @nvanbenschoten, and @tbg)

___
*[pkg/roachpb/metadata.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65741#-MbrPwh-Ax-eLQa7OO7S:-Mbrv5Uo49xv6E9pBlgJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/94022fd088b2728f1d2e1a14660bdbc3207799c2/pkg/roachpb/metadata.go#L205)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`RangeDescriptor`
</blockquote></details>

done

**Pull request merged**
