### PR TITLE
sql: rationalize some output events from the connection state machine

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @knz

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45515)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_fsm.go, line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-M1BuG-5BeBP7hurGeQW:-M1BuG-5BeBP7hurGeQX:b-lz9ix5) ([raw file](https://github.com/cockroachdb/cockroach/blob/483c170bdfbe771b6a4df77abcc8541b63f5d0de/pkg/sql/conn_fsm.go#L506)):*
> ```Go
> })
> 
> // cleanupAndFinish rolls back the KV txn and finishes the SQL txn.
> ```

Four suggestions to make this easier to read:
1. could you move this down right below `finishTxn` because these are the two code paths that can produce this `txnRollback` event?
2. could you rename this to `cleanupAndFinishOnError`?
3. could you make this a method on `*txnState` to parallel `noTxnToOpen` and `finishTxn`?
4. could you pull out the actions that do the same thing except they don't `ts.finishSQLTxn()` into a similar helper method?
___
*[pkg/sql/txn_state.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-M1BsLkE50z_q2CM4pcx:-M1BsLkF5dQVIuactQOG:b-jrjqa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6595c628953b492aacad42517852441e47138e48/pkg/sql/txn_state.go#L381)):*
> ```Go
> 	// txnRestart means that the transaction is expecting a retry. The iteration
> 	// of the txn just finished will not commit.
> 	// This event is produced both when entering the RetryWait state and sometimes
> ```

We seem to like these comments around here, so consider updating it instead of deleting it.
___
*[pkg/sql/txn_state.go, line 373 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-M1BsomyCxnAE3Rczn4M:-M1Bsomz1FOVjwBfdPAh:b-4uvt39) ([raw file](https://github.com/cockroachdb/cockroach/blob/483c170bdfbe771b6a4df77abcc8541b63f5d0de/pkg/sql/txn_state.go#L373)):*
> ```Go
> 	// when leaving it.
> 	txnCommit
> 	// txnRollback means that the transaction has rolled back.
> ```

Could you include a bit more here? How far has the transaction rolled back? To a savepoint? All the way? Either?

Do you want to include something about when the event is produced?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45515)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/conn_fsm.go, line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-M1BuG-5BeBP7hurGeQW:-M1C2zUm5SEkUN-bAm1w:bndlsct) ([raw file](https://github.com/cockroachdb/cockroach/blob/483c170bdfbe771b6a4df77abcc8541b63f5d0de/pkg/sql/conn_fsm.go#L506)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Four suggestions to make this easier to read:
1. could you move this down right below `finishTxn` because these are the two code paths that can produce this `txnRollback` event?
2. could you rename this to `cleanupAndFinishOnError`?
3. could you make this a method on `*txnState` to parallel `noTxnToOpen` and `finishTxn`?
4. could you pull out the actions that do the same thing except they don't `ts.finishSQLTxn()` into a similar helper method?
</blockquote></details>

1. done
2. done
3. I went the other way and made `noTxnToOpen` a free-standing function. And see 4)
4. done - also as a free-standing function that can be referenced directly in the state machine transitions, without having to write an inline function. 
___
*[pkg/sql/txn_state.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-M1BsLkE50z_q2CM4pcx:-M1C7DhJ3e2SgdpCSpyc:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6595c628953b492aacad42517852441e47138e48/pkg/sql/txn_state.go#L381)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We seem to like these comments around here, so consider updating it instead of deleting it.
</blockquote></details>

done
___
*[pkg/sql/txn_state.go, line 373 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-M1BsomyCxnAE3Rczn4M:-M1C6Dno3Jv_dWjzWjOu:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/483c170bdfbe771b6a4df77abcc8541b63f5d0de/pkg/sql/txn_state.go#L373)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you include a bit more here? How far has the transaction rolled back? To a savepoint? All the way? Either?

Do you want to include something about when the event is produced?
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, 2 of 2 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-:-M1CiPd43XUlm-7VVA5U:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45515#-:-M1RYZ_UDOXgPK9mWO29:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
