### PR TITLE
sql: Track view dependencies to support RESTRICT and CASCADE

### PR DESCRIPTION
**Pull request by a-robinson**
This handles view dependencies when dropping tables, views, and forced indexes.

This does not yet restrict the dropping of columns that are depended on or the renaming of anything that's depended on. I'll finish off those bits next if the general approach for tracking the dependencies looks reasonable so far. It also definitely needs some tests, which I'll be working on while waiting for review.

The data_source.go modifications for tracking when a view depends on another view likely aren't the best way to do it -- alternative suggestions welcome.
#2971

cc @dt @paperstreet

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9724)

### CODE REVIEW

**Comment by a-robinson** [comment]
Looking into the test timeout - these changes have drastically slowed down some operations.

**Comment by dt** [comment]
want to add some test cases to the `drop_table` logic tests?

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPFRifQM0yY_i2Pctv:-KTPFRigAlZW-7z58TEJ:bguw8bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/create.go#L295)):*
> ```Go
> 	privs := n.dbDesc.GetPrivileges()
> 
> 	affected := make(map[sqlbase.ID]*sqlbase.TableDescriptor)
> ```

nit: could put a comment here about why we don't need to create the view non-public and then wait to publish it until the updates to the referenced tables have propagated the way we do with normal tables.

---

*[sql/drop.go, line 375 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPHclZW63JMTC1u_lV:-KTPHclZW63JMTC1u_lW:b-nht05o) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/drop.go#L375)):*
> ```Go
> 		// then `cascade` was specified.
> 		for _, ref := range droppedDesc.DependedOnBy {
> 			if err := p.canRemoveDependentView(droppedDesc, ref, n.DropBehavior); err != nil {
> ```

I think you want to also check if you're dropping it as well (by constructing the set that is being dropped first) in which case you don't need cascade -- i think DropTabe does this?

---

*[sql/drop.go, line 540 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPI5CPfIGnSC6khWa8:-KTPI5CQRecnRia8mCn7:bq6l5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/drop.go#L540)):*
> ```Go
> }
> 
> func (p *planner) canRemoveDependentView(
> ```

does this need a privilege check?

---

*[sql/drop.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPLo4oKXRH589HSpX-:-KTPLo4oKXRH589HSpX0:b7ofu9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/drop.go#L665)):*
> ```Go
> // on it if `cascade` is enabled). It returns a list of view names that were
> // dropped due to `cascade` behavior.
> func (p *planner) dropTableImpl(tableDesc *sqlbase.TableDescriptor) ([]string, error) {
> ```

we should verify DropDatabase is doing the right RESTRICT checks too -- maybe add some test cases to those logic tests as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KTPGZI5Yh4zqzUGU98L:bn8hrgi)*

**Comment by a-robinson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPFRifQM0yY_i2Pctv:-KTVAJ8hiiFd-bKdpav_:b-i8tk8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/create.go#L295)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> nit: could put a comment here about why we don't need to create the view non-public and then wait to publish it until the updates to the referenced tables have propagated the way we do with normal tables.
</details>
Hm, I'm not actually sure that we don't need to, I sort of glossed over that (oops). Should we first create them as non-public until the tables have been updated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724)*

**Comment by a-robinson** [comment]
cc @mjibson to look at https://github.com/cockroachdb/cockroach/commit/ed73da0836d6716001d374c0e4437e423e0c9940, which repurposes the planner.AsOf field.

Still looking into the privilege check you mentioned, cascades with weird dependency hierarchies, and adding more tests, but responding to comments now since there's been a fair bit added.

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPFRifQM0yY_i2Pctv:-KToJMGJ6LIS81GJVH3F:b-obgvr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/create.go#L295)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Hm, I'm not actually sure that we don't need to, I sort of glossed over that (oops). Should we first create them as non-public until the tables have been updated?
</details>
I've switched to waiting on the dependencies, but let me know if you think it's better without the waiting.

---

*[sql/drop.go, line 375 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPHclZW63JMTC1u_lV:-KToJUvsNmNNEXjAm3YK:bsy0k3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/drop.go#L375)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I think you want to also check if you're dropping it as well (by constructing the set that is being dropped first) in which case you don't need cascade -- i think DropTabe does this?
</details>
I've added logic to accumulate the set of cascaded tables and let them be cascaded rather than deleting them from the top level and cascading.

---

*[sql/drop.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPLo4oKXRH589HSpX-:-KToJjvnie03fd-MtPtc:b-nvmr15) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/drop.go#L665)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> we should verify DropDatabase is doing the right RESTRICT checks too -- maybe add some test cases to those logic tests as well?
</details>
It actually looks like DropDatabase doesn't distinguish between RESTRICT and CASCADE. Does that mean we should only support RESTRICT? Because I've effectively implemented CASCADE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KToKOU6BQXm7t_auZFr:bwd3mm3)*

**Comment by a-robinson** [comment]
Rebased onto master to get teamcity working. All tests are passing locally after the fixes to not use cached table descriptors and to avoid double deletes when dropping a database.

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KToMjAAbbji_FCnp_TF:b-vydj1w)*

**Comment by a-robinson** [comment]
PTAL. I've added a bunch of logic tests to drop_database and to a new drop_view suite, and fixed a couple bugs found in the process.

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/drop.go, line 540 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPI5CPfIGnSC6khWa8:-KTtVP9LYRnj5xKdBqAx:b-9vonn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/drop.go#L540)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> does this need a privilege check?
</details>
Yes it did, and to recursively check the privileges of dependent views. Thanks!

---

*[sql/drop.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPLo4oKXRH589HSpX-:-KTtVVTMnKVEINGUSZyw:b-dy98tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/drop.go#L665)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> It actually looks like DropDatabase doesn't distinguish between RESTRICT and CASCADE. Does that mean we should only support RESTRICT? Because I've effectively implemented CASCADE.
</details>
Moving the discussion to https://github.com/cockroachdb/cockroach/issues/3943, where there's already been some discussion. For now, dropping databases is implicitly CASCADE with no option to RESTRICT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KTtVnB8jM8uk_HC52rV:bennehg)*

**Comment by dt** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r6.
Review status: 1 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 921 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTuZVe_Nbarp90kTk84:-KTuZVe_Nbarp90kTk85:b-kz8ylj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d73e30a68270cf0635e12307d136ac0d1bdbe81/sql/create.go#L921)):*
> ```Go
> 	n.resolveViewDependencies(&desc, affected)
> 
> 	// Since this view is referencing another table/view, it must be created in
> ```

as discussed offline, I don't think this is needed since schema change ops already read from KV and use a txn, so I think we get transactional semantics on this without needing to use the extra states (they're needed for FKs since those have to worry about normal reads/writes, which _do_ hit the desc cache, being unaware of a check, but views don't care about that, only desc modification).

---

*[sql/testdata/drop_view, line 36 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTuc8rxos-KOTz6wtWa:-KTuc8ryyxFnU0Hqxnt4:b-yycopz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d73e30a68270cf0635e12307d136ac0d1bdbe81/sql/testdata/drop_view#L36)):*
> ```
> 
> statement error view "diamond" depends on view "d"
> DROP VIEW d
> ```

I'd also add a `drop view a, b RESTRICT` example where  just `drop view a` would fail (due to a dep from b and no cascade), but explicitly adding `b` to the same drop (order independent though) works in lieu of cascade.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KTuckmNemAEXqSTLt1C:bnfp4nl)*

**Comment by a-robinson** [comment]
Sorry, but PTAL since supporting the test case you brought up required adding some more code.

---

Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTPFRifQM0yY_i2Pctv:-KTufb8etnIVSfTPfJyz:b-h56bc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/87db50a05c86c10981f3d6308df89d30c42b3eb8/sql/create.go#L295)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> I've switched to waiting on the dependencies, but let me know if you think it's better without the waiting.
</details>
Undone, as mentioned in the comment below.

---

*[sql/create.go, line 921 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTuZVe_Nbarp90kTk84:-KTuffDWviCt24ltcOoy:b9izszt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d73e30a68270cf0635e12307d136ac0d1bdbe81/sql/create.go#L921)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> as discussed offline, I don't think this is needed since schema change ops already read from KV and use a txn, so I think we get transactional semantics on this without needing to use the extra states (they're needed for FKs since those have to worry about normal reads/writes, which _do_ hit the desc cache, being unaware of a check, but views don't care about that, only desc modification).
</details>
Yup, done.

---

*[sql/testdata/drop_view, line 36 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-KTuc8rxos-KOTz6wtWa:-KTuhYBRwVK5hOHQJ0Ma:bnz1g1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d73e30a68270cf0635e12307d136ac0d1bdbe81/sql/testdata/drop_view#L36)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I'd also add a `drop view a, b RESTRICT` example where  just `drop view a` would fail (due to a dep from b and no cascade), but explicitly adding `b` to the same drop (order independent though) works in lieu of cascade.
</details>
Nice edge case. I've updated the code to handle it, although I wish it didn't complicate the code quite so much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KTyQVzHG3KKpGQE1jZY:by80r05)*

**Comment by dt** [comment]
:lgtm:

fwiw, drop table builds a set (map) of things to drop first rather than searching a slice, but at the sizes we can expect, I don't think it matters.

---

Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KTyVjQ4jROUdjPcRo3_:b-bpbqbs)*

**Comment by a-robinson** [comment]
Yeah, I figured avoiding the extra allocation was more valuable than avoiding the N^2 searching given that we're searching a list of manually specified tables. 

Thanks for the review!

---

Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9724#-:-KTyaCu1goilgXxN4OzB:b-yxuezk)*

**Comment by a-robinson** [comment]
Rebased onto the pkg/ change. There weren't any complications other than having to `git mv` the new drop_view test.

**Review by dt — APPROVED** [review]

**Pull request merged**
