### PR TITLE
jobs, sql, ui: Create `AutoCreateStats` job type

### LINKED ISSUE #34377: jobs: garbage collect old CreateStats jobs
Once PR #34279 merges, enabling the cluster setting `sql.stats.experimental_automatic_collection.enabled` has the potential to create **many** CreateStats jobs. This has a couple of implications:

1. The `system.jobs` table may grow very large over time, possibly affecting the performance of new jobs. This can be addressed by simply deleting all jobs (or all `CreateStats` jobs) over a certain age.

2. The Jobs view on the AdminUI may become cluttered. This is somewhat mitigated by the fact that there is a "TYPE" dropdown, but if a user wants to see their own manual runs of `CREATE STATISTICS`, they are likely to be drowned out by all the automated runs. The question is: should the Jobs view even show the automated `CreateStats` jobs? Or perhaps there should be two types: `AutoCreateStats` and `CreateStats`?

Any thoughts from members of the AdminUI team or people who are familiar with the jobs infrastructure would be appreciated!

cc @danhhz, @couchand, @piyush-singh

### PR DESCRIPTION
**Pull request by celiala**
With #34279, enabling the cluster setting
`sql.stats.experimental_automatic_collection.enabled` has the potential
to create many CreateStats jobs, which can cause the Jobs view on the
AdminUI to become cluttered.

This commit creates a new `AutoCreateStats` job type for these auto-created
CreateStats jobs, so that users are able to still see their own manual runs
of CREATE STATISTICS, via the pre-existing `CreateStats` type.

cc @danhhz, @piyush-singh, @rolandcrosby 

jobs-auto-create-stats

Release note (admin ui change): AutoCreateStats type added to
Jobs page to filter automatic statistics jobs.

Fixes #34377.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
Nice, thanks!

**Comment by awoods187** [comment]
this is awesome!

**Comment by rolandcrosby** [comment]
This is great! Do currently-running auto-stats jobs still show up in the default view or have they all been moved to this subview?

**Comment by celiala** [comment]
Yep! In the default view (All types, All statuses), you'll still see currently-running auto-stats jobs.

**Comment by celiala** [comment]
TFTR!

bors r+

**Comment by rytaft** [comment]
:lgtm: thanks!

**Comment by vilterp** [comment]
Nice :) Maybe someday auto-stats jobs should be filtered out by default (i.e. you should see everything but them). Not sure what the UI would be tho. Maybe instead of a simple selector dropdown for job type, it's a checkbox dropdown, where by default everything but "auto stats job" is checked? 🤔 

Anyway, this is a good step forward 👍

**Comment by piyush-singh** [comment]
Agreed with Pete, eventually we should filter out the automated create stats jobs on the default view since the sheer number of them makes it hard to find much without filtering.

**Pull request merged**
