### PR TITLE
obsservice: export StatementInsightsStatistics

### PR DESCRIPTION
**Pull request by maryliag**
_commit 1:_

**obsservice: add stmt insights proto and conversion**

Add proto definition for Statement Insights to be
used on Obs Service.
Creates function to copy a `insights.Insight` to the new
`obspb.StatementInsightsStatistics` format.

For this version, there are some parameters not being set,
such as contention. Those will be populated on a following
iteration.

Epic: none

Release note: None

----

_commit 2:_

**obsservice: export StatementInsightsStatistics**

This patch hooks into the Flush functionality used
by PersistedSQLStats, in preparation for Insights
to be sent to external o11y systems.
A following PR will do the actual export during the flush.

Lastly, it's acknowledged that the transformation
required here is likely going to be heavy on
allocations. During the prototyping phase however,
we leave the optimization and/or restructuring of
the exported type for the future. For now, we use
a sync.Pool in an effort to reduce allocations/GC.

Release note: none

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
:tada: :tada: :tada: Looking good!

Just a couple tiny nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-:-NiBEHJj8XrApAigNHzP:broghaj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/obsservice/obspb/obsservice.proto` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-NiBAAJy96RYfeTvevof:-NiBAAJy96RYfeTvevog:b-iv1mmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d95bbdc08f66a89d9ddf0096a35e1ab6243866/pkg/obsservice/obspb/obsservice.proto#L85)):*
> ```proto
> 
> enum Status {
>   Completed = 0;
> ```

nit: for these (Status/Problem/Cause), should we prefix the type name with something like "Insight" (e.g. InsightStatus), so that it's more obvious which event type they pertain to? Just thinking about what this file might look like a year in the future :slightly_smiling_face: 
___
*[`pkg/sql/sqlstats/insights/registry.go` line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-NiBAWWpEqHFrem8AQO_:-NiBAWWpEqHFrem8AQOa:bwkjbby) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d95bbdc08f66a89d9ddf0096a35e1ab6243866/pkg/sql/sqlstats/insights/registry.go#L200)):*
> ```Go
> 
> func (s *Statement) CopyTo(
> 	ctx context.Context, t *Transaction, session Session, other *obspb.StatementInsightsStatistics,
> ```

nit: can `session` be a pointer?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

___
*[`pkg/obsservice/obspb/obsservice.proto` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-NiBAAJy96RYfeTvevof:-NiBHeJt5MsmnVfKUvYw:bzcz8uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d95bbdc08f66a89d9ddf0096a35e1ab6243866/pkg/obsservice/obspb/obsservice.proto#L85)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: for these (Status/Problem/Cause), should we prefix the type name with something like "Insight" (e.g. InsightStatus), so that it's more obvious which event type they pertain to? Just thinking about what this file might look like a year in the future :slightly_smiling_face:
</blockquote></details>

I decided to move them to inside the Statements Insights definition, so it's clear it's part of it, and when using it it would need to add the prefix anyway
___
*[`pkg/sql/sqlstats/insights/registry.go` line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-NiBAWWpEqHFrem8AQO_:-NiBHsYrALc_e2dbJv6q:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d95bbdc08f66a89d9ddf0096a35e1ab6243866/pkg/sql/sqlstats/insights/registry.go#L200)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can `session` be a pointer?
</blockquote></details>

Done

**Review by abarganier — APPROVED** [review]
:lgtm: - thanks @maryliag!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-:-Ni_vp1I1QJKKtKQB-Ce:b-g8q3c8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/obsservice/obspb/obsservice.proto` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-NiBAAJy96RYfeTvevof:-Ni_vlRe7tqcseIM32vT:btnlxa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d95bbdc08f66a89d9ddf0096a35e1ab6243866/pkg/obsservice/obspb/obsservice.proto#L85)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I decided to move them to inside the Statements Insights definition, so it's clear it's part of it, and when using it it would need to add the prefix anyway
</blockquote></details>

Cool, thanks! LGTM
___
*[`pkg/sql/sqlstats/insights/registry.go` line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113498#-NiBAWWpEqHFrem8AQO_:-Ni_vnnjDX8INmyFXIeZ:b-hay2ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d95bbdc08f66a89d9ddf0096a35e1ab6243866/pkg/sql/sqlstats/insights/registry.go#L200)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks!

**Comment by maryliag** [comment]
TFTR!

bors r+

**Pull request merged**
