### PR TITLE
sql: use 0 for gateway node in statistics table to reduce row count

### LINKED ISSUE #107787: sql: Reduce SQL statement statistics rows
The SQL Activity pages already use a query to do a group by to remove any node specific information. So storing the gateway node in the system table causes the table to grow by the number of nodes. Then the SQL Activity query has to merge all the data down to a single row. Then the clean up job has to delete all of the rows. 

The solution is to change the default value of the `sql.metrics.statement_details.gateway_node.enabled` to false. This cluster setting was already added initially to help customers with large workloads because there were to many rows being generated.  By switching this to false by default all customer will be able to take advantage of. This is still a cluster setting so if customer still want a per node statistics they can change the cluster setting.

Related to: https://github.com/cockroachdb/cockroach/issues/99220

Jira issue: CRDB-30196

### PR DESCRIPTION
**Pull request by j82w**
The SQL Activity pages already use a query to do a group by to remove any node specific information. So storing the gateway node in the system table causes the table to grow by the number of nodes. Then the SQL Activity query has to merge all the data down to a single row. Then the clean up job has to delete all of the rows.

This PR changes the default value of the
`sql.metrics.statement_details.gateway_node.enabled` to false. This cluster setting was already added initially to help customers with large workloads because there were to many rows being generated. By switching this to false by default all customer will be able to take advantage of the reduce row generation. This is still a cluster setting so if customer still want a per node statistics they can change the cluster setting.

Closes: #107787

Release note (sql change): Change the cluster setting `sql.metrics.statement_details.gateway_node.enabled` to default to false. This will reduce the number of rows generated in SQL Statistics.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107788)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/server/drain_test.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107788#-NavZR1x4jrDvDLCyAd8:-NavZR1x4jrDvDLCyAd9:b-g7nwk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23c5abdce9f2e0330fa5df9bde00576af080e87/pkg/server/drain_test.go#L15)):*
> ```Go
> import (
> 	"context"
> 	"github.com/cockroachdb/cockroach/pkg/sql/sqlstats"
> ```

location of this import will give you a lint error

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107788)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/server/drain_test.go` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107788#-Nbv2PVsA5tErQeAJHox:-Nbv2PVt3emOHF8Aiy5y:b-c94ll9) ([raw file](https://github.com/cockroachdb/cockroach/blob/499f25404ed844c6c2160a3f2e29ec167a061e04/pkg/server/drain_test.go#L169)):*
> ```Go
> 	} else {
> 		// Check that the stats were flushed into the statement stats system table.
> 		// Verify that the number of statistics for node 1 are non-zero.
> ```

If you want to test that node 1 was flushed you can use `where node_id = 0 AND statistics ->
                        -> 'statistics' ->> 'nodes' = '[1]'`

(keep he node_id = 0 to confirm that the flag is doing that is should)

**Comment by j82w** [comment]
*[`pkg/server/drain_test.go` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107788#-Nbv2PVsA5tErQeAJHox:-Ne53BByDf_oCfQ6D4oP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499f25404ed844c6c2160a3f2e29ec167a061e04/pkg/server/drain_test.go#L169)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

If you want to test that node 1 was flushed you can use `where node_id = 0 AND statistics ->
                        -> 'statistics' ->> 'nodes' = '[1]'`

(keep he node_id = 0 to confirm that the flag is doing that is should)
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107788#-:-NeIzlqZ9DjsQfNbhuvv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

**Pull request merged**
