### PR TITLE
asim: enable event series generation

### PR DESCRIPTION
**Pull request by wenyihu6**
**asim: enable event series generation**

This patch enables interesting event series to be generated and scheduled as
part of the simulation.

The following command is now supported:
"rand_events" [type=<string>{cycle_via_hardcoded_survival_goals}]
 [duration_to_assert_on_event=<time.Duration>]
 e.g. rand_events type=cycle_via_hardcoded_survival_goals duration=5m
 - rand_events: generates interesting event series to be scheduled in the
 simulation.
 - type: type of event series to be scheduled.
 - duration_to_assert_on_event: delay to add the assertion events post
   mutation events for mutation-assertion event series.

----

**asim: better output for executed events**

Previously, the randomized testing framework only reports number of scheduled
mutation and assertion events, offering no insights on their execution or the
results of the assertion events. This patch adds more output info to include
executed mutation events, conducted assertion checks, assertion results, and
their execution timing.

New verbosity flags for eval is now supported to print these info.
```
"eval" [verbose=events]
```

Part of: https://github.com/cockroachdb/cockroach/issues/106192
Release Note: none

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
Looks good, lets discuss how we want to handle the CI timeout offline.

> Reviewed 15 of 25 files at r1, 9 of 9 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-:-Nd5cyqHAdFkeZZDfSxt:b-93sseq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-Nd1zK3eCy7M_nW_oo8H):*
nit: the wording of this line seems off.
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-Nd5bpWPDxzLNJzuNqaT:-Nd5bpWPDxzLNJzuNqaU:bh4uuqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c72341611fd6feb3cc48d7caa99fde8284b091/pkg/kv/kvserver/asim/event/mutation_event.go#L64)):*
> ```Go
> 
> func (se SetSpanConfigEvent) String() string {
> 	return fmt.Sprintf("set span config event with span=%s, config=%s", se.Span.String(), se.Config.String())
> ```

Is the `.String()` call necessary on these? My understanding was that these were inferred by the format function if they exist.
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-Nd5bzfF558WiUYKseQh:-Nd5bzfF558WiUYKseQi:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c72341611fd6feb3cc48d7caa99fde8284b091/pkg/kv/kvserver/asim/event/mutation_event.go#L99)):*
> ```Go
> 
> func (sne SetNodeLivenessEvent) String() string {
> 	return fmt.Sprintf("set node liveness event with nodeID=%d, liveness_status=%s", sne.NodeId, sne.LivenessStatus.String())
> ```

Same as above.
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-Nd5c01t17YpBRoCR6oo:-Nd5c01t17YpBRoCR6op:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c72341611fd6feb3cc48d7caa99fde8284b091/pkg/kv/kvserver/asim/event/mutation_event.go#L110)):*
> ```Go
> 
> func (sce SetCapacityOverrideEvent) String() string {
> 	return fmt.Sprintf("set capacity override event with storeID=%d, capacity_override=%s", sce.StoreID, sce.CapacityOverride.String())
> ```

Same as above.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-Nd5bpWPDxzLNJzuNqaT:-Nd7EW_01jHvuw7fL2ik:b-b29ipo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c72341611fd6feb3cc48d7caa99fde8284b091/pkg/kv/kvserver/asim/event/mutation_event.go#L64)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Is the `.String()` call necessary on these? My understanding was that these were inferred by the format function if they exist.
</blockquote></details>

opps forgot about it

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-Nd5bzfF558WiUYKseQh:-Nd7EZ2c2GadayCGnwRx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c72341611fd6feb3cc48d7caa99fde8284b091/pkg/kv/kvserver/asim/event/mutation_event.go#L99)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-Nd5c01t17YpBRoCR6oo:-Nd7E_0Z320egwiZmI79:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c72341611fd6feb3cc48d7caa99fde8284b091/pkg/kv/kvserver/asim/event/mutation_event.go#L110)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by kvoli — APPROVED** [review]
:lgtm: Discussed offline, we will resolve the timing out tests before merging.

> Reviewed 29 of 29 files at r4, 12 of 28 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-:-Nd785QA7lImMTEEGu5S:b8867cp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/testdata/rand/events` line 4 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109602#-NdAreuiA15PM2vA4KOg:-NdAreuiA15PM2vA4KOh:b-x7t1fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/186b57cbee062672efbfe57fdef187ad371f3965/pkg/kv/kvserver/asim/tests/testdata/rand/events#L4)):*
> ```
> ----
> 
> change_static_option ranges=1
> ```

I forgot to shorten the duration when changing the number of ranges generated to 1. After making this change, the time it took to stabilize decreased significantly. The test only takes 2.5 seconds now. I have another PR to remove some of the log events that were time-consuming. But this is no longer blocking this PR. Happy to close this other PR if we prefer to keep the log events for tracing.

**Comment by wenyihu6** [comment]
TFTR! 

bors r=kvoli

**Pull request merged**
