### PR TITLE
tablemetadatacache: collect data & write to system.table_metadata

### LINKED ISSUE #128993: sql: implement data collection for UpdateCachedTableMetadata
This issue deals with implementing the portion of the UpdateCachedTableMetadata that collects table metadata for the whole cluster (user and system tables, exlcuding virtual).

Required metadata for each table:
* 	db (parent) id
* db (parent) name
* table id
* table name
* replication bytes
* range count
* replica count
* index count
* column count
* live bytes
* total bytes
* unique store ids
* percentage of live data

Next:
* https://github.com/cockroachdb/cockroach/issues/130040
* https://github.com/cockroachdb/cockroach/issues/130249

Epic CRDB-37558

Jira issue: CRDB-41320

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit adds the execution logic to the UPDATE TABLE
METADATA job to populate the system.table_metadata
table. The update process is managed by the new
`tableMetadataUpdater` struct.

Job execution summary:
1. Rows in `system.table_metadata` are pruned if the table_id
no longer exists in `system.namespace`.
2. tableMetadataIterator collects table metadata in batches by
paginating `system.namespace` (current batch size of 20).
3. For each row from system.namespace, we decode the descriptor
from system.namespace.
3. One RPC is issued per batch to collect the batch's table span
stats.
4. Each batch is prepped and upserted into system.table_metadata.

Fixes: https://github.com/cockroachdb/cockroach/issues/128993
Epic: [CRDB-37558](https://cockroachlabs.atlassian.net/browse/CRDB-37558)
Release note: None

### CODE REVIEW

**Comment by xinhaoz** [comment]
Going to release this for review for sooner feedback. I might add more testing via datadriven test to audit the table rows more fully.

**Comment by xinhaoz** [comment]
Replaced unit testing with datadriven tests.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130041)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dt, @kyle-a-wong, and @xinhaoz)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6MuPzt-4B2TMFpsOUy):*
what happens if a new system table is added while this job is running? (for instance if the cluster is upgraded) will we miss one or more rows because of pagination logic?
___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6Mx6_N9AKBmx6WlS2A:-O6Mx6_N9AKBmx6WlS2B:b-szdkdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bcdefe296c9961c861dd78ad12ac32563893232/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L120)):*
> ```Go
>                 LEFT JOIN system.descriptor d ON n.id = d.id
>                 WHERE (n."parentID", n."parentSchemaID", n.name) > ($1, $2, $3)
>                 LIMIT $4),
> ```

don't you need the `ORDER BY` here if you're applying the `LIMIT`?
___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6Mv0oZAOcsiDLkRuSw:-O6Mv0oZAOcsiDLkRuSx:b-jhb8cy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bcdefe296c9961c861dd78ad12ac32563893232/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L148)):*
> ```Go
> 		// If there are no more results we've reached the end of the namespace table
> 		// and are done.
> 		ok, err := it.Next(ctx)
> ```

the use if `it` and `ti` makes this method harder to read. can you adjust the naming a bit?
___
*[`pkg/sql/tablemetadatacache/testdata/update_table_metadata` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6MvnFE3E-CiwcTxq9i:-O6MvnFE3E-CiwcTxq9j:b-fbwrbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bcdefe296c9961c861dd78ad12ac32563893232/pkg/sql/tablemetadatacache/testdata/update_table_metadata#L113)):*
> ```
> SELECT count(*) FROM system.table_metadata WHERE table_name = 'mytable'
> ----
> 0
> ```

beautiful tests! :clap:

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130041)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, @dt, and @kyle-a-wong)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6MuPzt-4B2TMFpsOUy):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

what happens if a new system table is added while this job is running? (for instance if the cluster is upgraded) will we miss one or more rows because of pagination logic?
</blockquote></details>

Yeah we'll miss a table if it's added during the iter execution and we're past that point in the namespace table. I don't think it's a big deal since we'll just get it in the next update - we likewise wouldn't see any added tables in between update runs. WDYT?
___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6Mx6_N9AKBmx6WlS2A:-O6XkAB-2S0Lzn-zjth4:b8rabeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bcdefe296c9961c861dd78ad12ac32563893232/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L120)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

don't you need the `ORDER BY` here if you're applying the `LIMIT`?
</blockquote></details>

I guess it worked since this is the pk on the namespace table - added order by to be more cautious here.
___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6Mv0oZAOcsiDLkRuSw:-O6Xk_Zn8X2R2ZdNU8OK:bbp1vtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bcdefe296c9961c861dd78ad12ac32563893232/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L148)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

the use if `it` and `ti` makes this method harder to read. can you adjust the naming a bit?
</blockquote></details>

Good point, renamed receiver for clarity.
___
*[`pkg/sql/tablemetadatacache/testdata/update_table_metadata` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6MvnFE3E-CiwcTxq9i:-O6XlLcBEKNoyY29WSQd:bjsfwhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bcdefe296c9961c861dd78ad12ac32563893232/pkg/sql/tablemetadatacache/testdata/update_table_metadata#L113)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

beautiful tests! :clap:
</blockquote></details>

Love me some datadriven tests :raised_hands:

**Review by kyle-a-wong — APPROVED** [review]
:lgtm:. Have a question about the use of a left join, but its not blocking

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-:-O6bV3cpDuvkB7BT7suJ:b-2p1z1b)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, @dt, and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6bTyHC8q3Z3-hTta4j:-O6bTyHC8q3Z3-hTta4k:b-7m43at) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9c0b19dde956855dcb0e560a194a7333d0bd67/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L118)):*
> ```Go
>                        crdb_internal.table_span(n.id) as span
>                 FROM system.namespace n
>                 LEFT JOIN system.descriptor d ON n.id = d.id
> ```

not blocking: Why do we need a left join here?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130041)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, @dt, and @kyle-a-wong)

___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130041#-O6bTyHC8q3Z3-hTta4j:-O6bXV-E1fu3EVEg-ZPt:b-wns1cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9c0b19dde956855dcb0e560a194a7333d0bd67/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L118)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

not blocking: Why do we need a left join here?
</blockquote></details>

Not totally necesssary to do a left join - we can swap to a regular JOIN - done.

**Comment by xinhaoz** [comment]
@dhartunian just checking in on if you have any final words, otherwise going to merge once CI passes!

**Pull request merged**
