### PR TITLE
roachtest: minor fixes in rebalance/by-load test

### PR DESCRIPTION
**Pull request by kvoli**
`%` was not escaped, causing it to be substituted with values which
were meant to go later.

e.g., from:

```
node 0 has core count normalized CPU utilization ts datapoint not in [0%!,(float64=1.4920845083839689)100{[{{%!](string=cr.node.sys.cpu.combined.percent-normalized) %!]
...
```

To

```
node idx 0 has core count normalized CPU utilization ts datapoint not in [0%,100%]
...
```

---

The `rebalance/by-load/*` roachtests compare the CPU of nodes and assert
that the distribution of node cpu is bounded +- 20%. The previous metric:

```
sys.cpu.combined.percent_normalized
```

Would occasionally over-report the CPU, as greater than 100% (>1.0),
which is impossible. Use the host CPU instead, which will look at the
machines CPU utilization, rather than any cockroach processes.

```
sys.cpu.host.combined.percent_normalized
```

Part of: #133004
Part of: #133054
Part of: #132019
Part of: #133223
Part of: #132633
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
I believe the second commit should generally fix all the issues I've seen, however I'm not certain and don't wish to run all the variations/release-branches -- so not closing on this PR to prevent churn. If these don't fail again after the backports land, I'll close the issues.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133681#-:-OAOMu6YAhi-nZy6AABS:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by kvoli** [comment]
TYFTR!

bors r=arulajmani

**Comment by kvoli** [comment]
https://github.com/cockroachdb/cockroach/pull/135947 will need to merge before backporting to 24.2

**Pull request merged**
