### PR TITLE
roachtest: add goroutine leak checker

### PR DESCRIPTION
**Pull request by tbg**
Previously in [^1], we dumped all stacks upon test run completion. Now, we install a leak checker (same one used by unit tests). The leak checker is deferred until after the entire test run. Detected leaks are appended to the test runner's log.

Also, the Ctrl-C signal handler will dump stacks to the log, not stderr.

[^1]: https://github.com/cockroachdb/cockroach/pull/104901

Epic: none

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/util/leaktest/leaktest.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105873#-NZTQDwh6gCeU_jDNwlS:-NZTQDwh6gCeU_jDNwlT:b-orvm9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eeafa30285b7b5473c11dc0f69d690f7f6964d9/pkg/util/leaktest/leaktest.go#L132)):*
> ```Go
> 			// that innocent test.
> 			atomic.StoreUint32(&leakDetectorDisabled, 1)
> 			t.Errorf("panic: %s", r)
> ```

This seems to change the semantics

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)

___
*[`pkg/util/leaktest/leaktest.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105873#-NZTQDwh6gCeU_jDNwlS:-NZZz92-32KvjKNd3aFg:b8ra2ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eeafa30285b7b5473c11dc0f69d690f7f6964d9/pkg/util/leaktest/leaktest.go#L132)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

This seems to change the semantics
</blockquote></details>

True, but not in a meaningful way, since we re-panic on the next line. For historical context, this code originally translated panics into test failures (i.e. called `t.Fatalf` here). This was then essentially, but not quite, reverted in https://github.com/cockroachdb/cockroach/pull/92627, leaving us with this code.

**Comment by tbg** [comment]
bors r=srosenberg
TFTR!

**Comment by renatolabs** [comment]
blathers backport 23.1

**Pull request merged**
