### PR TITLE
Revert "ui: use browserHistory rather than hashHistory"

### PR DESCRIPTION
**Pull request by tamird**
This reverts #7803 because that broke reloading pages in the UI.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7814)

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

This makes me sad.  Is there no work around?

---

Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7814#-:-KM_Qbi8iW3ch4NUNKkn:329789260)*

**Comment by tamird** [comment]
Things get broken in dev mode when SystemJS starts asking for relative
paths. I'm open to suggestions.

**Comment by maxlang** [comment]
LGTM

This is breaking my development environment.

Happy to discuss workarounds.

**Comment by tamird** [comment]
@maxlang can you merge this for me? I have to step out.

**Pull request merged**
