### PR TITLE
.github: update CODEOWNERS

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[.github/CODEOWNERS, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17383#-KqYCHenY_-iEOfwy9C5:-KqYCHeoGX1KWkLrn3-B:bcesw82) ([raw file](https://github.com/cockroachdb/cockroach/blob/f163fb8f2556ef488c4b916d03634c41dcd5b545/.github/CODEOWNERS#L19)):*
> ```
> /pkg/cli/              @cockroachdb/sql-ui
> 
> /pkg/sql/              @cockroachdb/sql-rest
> ```

It looks like `sql-rest` are people who are explicitly opting into the firehose?  Just ensuring this is the desired behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17383#-:-KqYCVd62cbtVub0xnsr:bnfp4nl)*

**Comment by knz** [comment]
No they only opt into things not matched by the other patterns. Which reminds me that I just missed testlogic, probably the worst offender :)

**Comment by benesch** [comment]
Much better. Thanks @knz! LGTM too.

**Comment by arjunravinarayan** [comment]
@knz In that case I'm :dog: :dog: :dog:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17383#-:-KqYDAxZGTfQ-zOZbfAT:b-epa2l3)*

**Comment by jordanlewis** [comment]
Triple dog down as well. Although this still seems to not work some of the time - neither of my recent PRs have had auto assigned reviewers.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[.github/CODEOWNERS, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17383#-KqYFUCIo0YnV-YD2SGG:-KqYFUCJjnHgYKf3g_X1:b-p48ue5) ([raw file](https://github.com/cockroachdb/cockroach/blob/971e095c4185ff057a96ad7f6e4dcbe9977b2589/.github/CODEOWNERS#L46)):*
> ```
> # We purposefully sink testlogic into a non-existent team
> # to disable notifications otherwise caught by the @sql-rest team.
> /pkg/sql/testlogic/    @cockroachdb/nonexistent
> ```

Non-obvious why we don't want notifications for testlogic - maybe say in the comment that "typically, testlogic changes are part of a bigger change that will trigger notifications to the correct sub-team"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17383#-:-KqYFsIPi6nQJz747r4z:bnfp4nl)*

**Comment by knz** [comment]
Good idea, done.

**Comment by benesch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[.github/CODEOWNERS, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17383#-KqYFUCIo0YnV-YD2SGG:-KqYHApoVIgvrQr0ZV26:b-kejvak) ([raw file](https://github.com/cockroachdb/cockroach/blob/971e095c4185ff057a96ad7f6e4dcbe9977b2589/.github/CODEOWNERS#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Non-obvious why we don't want notifications for testlogic - maybe say in the comment that "typically, testlogic changes are part of a bigger change that will trigger notifications to the correct sub-team"
</blockquote></details>

Does leaving the team blank not work? I.e.:

```
/pkg/sql/testlogic
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17383)*

**Comment by knz** [comment]
@benesch I don't know, does it? I couldn't find any docs

**Comment by benesch** [comment]
Yeah, neither could I. This file is very shoddily documented.

**Comment by knz** [comment]
I sent a request to GH support. For the time being we can try this approach.

**Comment by RaduBerinde** [comment]
LGTM

**Pull request merged**
