### PR TITLE
build: install glide in checkdeps

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12090)

### CODE REVIEW

**Comment by dt** [comment]
I'm inclined to `build/builder.sh` the script itself rather than each line, since the script is building up internal state (e.g. installed glide version, modified `vendor`, etc)

**Comment by tamird** [comment]
If you `build/builder.sh` the script itself, then we should have two scripts. It should be possible to run these guys locally and get a TC-equivalent result.

**Comment by dt** [comment]
Done.

**Comment by tamird** [comment]
LGTM assuming you've verified this works.

**Comment by dt** [comment]
I verified the parts individually (that checkdeps works, and and that tc-checkdeps call checkdepsin docker). Unfortunately docker on mac seems to choke on IO load of rebuilding a full `vendor` so it times out as often as it doesn't, but it should be fine on TC/linux, or when run not-in-docker.

**Pull request merged**
