### PR TITLE
opt: Map output mutation columns to new column IDs

### PR DESCRIPTION
**Pull request by andy-kimball**
Currently, the Insert and Update operators pass through input columns
when there is a RETURNING clause. That works, but has downsides:

  1. It won't work well for Upsert, since Upsert chooses each output
     value from either one of two input columns.
  2. It makes formatted output harder to understand.

This commit maps mutation operator output to the target table column
IDs. For example:

  update xyz
   ├── columns: x:1(string!null) y:2(int!null) z:3(float)
   ├── fetch columns: x:4(string) y:5(int) z:6(float)
   ├── update-mapping:
   │    └──  column7:7 => x:1

Previously, "columns" would have been pass through ids from the fetch
columns and update-mappings.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: 

I agree the old output was sketchy. E.g the following case was a mess `INSERT INTO abcde (a, b) SELECT b, a FROM abcde RETURNING a, b`, and it's much nicer now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33145#-:-LTdWU4qBRaYSj7Mp89L:by7a52s)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/expr.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33145#-LTdV6VT7jXw4SVSV3ew:-LTdV6VT7jXw4SVSV3ex:b2kb4u2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7641c2120b122be8b118eead0e8650aff7e794/pkg/sql/opt/memo/expr.go#L282)):*
> ```Go
> }
> 
> // MapToInputID maps from the ID of a target table column to the ID of the
> ```

[nit] maybe we want a more general `MapToInputIDs` that give us both IDs (with the second being 0 if N/A). The props code would look like:
```go
a, b := MapToInputIDs()
if inputProps.NotNullCols.Contains(a) && (b == 0 || inputProps.NotNullCols.Contains(b)) {
  rel.NotNullCols.Add()
}
```

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33145)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/expr.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33145#-LTdV6VT7jXw4SVSV3ew:-LTizNjHET40CVPkqXnR:b2g2cng) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7641c2120b122be8b118eead0e8650aff7e794/pkg/sql/opt/memo/expr.go#L282)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe we want a more general `MapToInputIDs` that give us both IDs (with the second being 0 if N/A). The props code would look like:
```go
a, b := MapToInputIDs()
if inputProps.NotNullCols.Contains(a) && (b == 0 || inputProps.NotNullCols.Contains(b)) {
  rel.NotNullCols.Add()
}
```
</blockquote></details>

I'd thought about doing this, but backed off. But with your comment, I went ahead and did it.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33145#-:-LTj1qR14eW4TpIEVDbh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
