### PR TITLE
build: add TC build configuration for running roachtests with profiling

### PR DESCRIPTION
**Pull request by rickystewart**
Epic: CRDB-41952
Part of: CRDB-44692
Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
The TC build configuration: https://teamcity.cockroachdb.com/admin/editBuildParams.html?id=buildType:Cockroach_Nightlies_RoachtestGceForceProfile

**Review by jlinder — COMMENTED** [review]
One thing:

- the commit message needs a `Release note: none` line.

**Comment by rickystewart** [comment]
Sorry, I have only been working here for years.

**Comment by jlinder** [comment]
LoL. Happens to the best of us.

**Review by jlinder — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=jlinder

**Pull request merged**
