### PR TITLE
sql/schemachanger: adopt screl for operation generation

### PR DESCRIPTION
**Pull request by ajwerner**
Extends https://github.com/cockroachdb/cockroach/pull/70905 with 2 more commits to adopt the rules and attributes system for operation generation.

### CODE REVIEW

**Review by postamar — APPROVED** [review]
See https://github.com/cockroachdb/cockroach/pull/70405#pullrequestreview-775373706

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 51 files at r1, 12 of 18 files at r3, 6 of 6 files at r5, 15 of 18 files at r6, 26 of 26 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70957)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scplan/opgen/opgen_default_expression.go, line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70957#-MlpB5wjBzhjIiE4oMoq:-MlpB5wjBzhjIiE4oMor:b-u6bcv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e333b4df95830891ad7cd8341b72eece4b7a160c/pkg/sql/schemachanger/scplan/opgen/opgen_default_expression.go#L25)):*
> ```Go
> 		to(scpb.Status_ABSENT,
> 			minPhase(scop.PreCommitPhase),
> 			emit(func(this *scpb.DefaultExpression) scop.Op {
> ```

Can't we emit an array of op's anymore? Or am I misinterpreting this

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70957)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/schemachanger/scplan/opgen/opgen_default_expression.go, line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70957#-MlpB5wjBzhjIiE4oMoq:-MlwvHHoCvR1IHkixtqi:blojjut) ([raw file](https://github.com/cockroachdb/cockroach/blob/e333b4df95830891ad7cd8341b72eece4b7a160c/pkg/sql/schemachanger/scplan/opgen/opgen_default_expression.go#L25)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Can't we emit an array of op's anymore? Or am I misinterpreting this
</blockquote></details>

I recall now why I wanted to make them separate. It was a half-baked idea that I clearly did not follow up on. The idea was that I could make the function that emits the ops have the actual op type as the return type and then statically we could know the types of ops we emit at each step. 

If you feel that the slice is better, we can do that in follow up as it's a small change.

**Review by fqazi — APPROVED** [review]

**Comment by fqazi** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70957)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)
> 
> _[pkg/sql/schemachanger/scplan/opgen/opgen_default_expression.go, line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70957#-MlpB5wjBzhjIiE4oMoq:-MlwvHHoCvR1IHkixtqi:blojjut) ([raw file](https://github.com/cockroachdb/cockroach/blob/e333b4df95830891ad7cd8341b72eece4b7a160c/pkg/sql/schemachanger/scplan/opgen/opgen_default_expression.go#L25)):_
> 
> Previously, fqazi (Faizan Qazi) wrote…
> I recall now why I wanted to make them separate. It was a half-baked idea that I clearly did not follow up on. The idea was that I could make the function that emits the ops have the actual op type as the return type and then statically we could know the types of ops we emit at each step.
> 
> If you feel that the slice is better, we can do that in follow up as it's a small change.

We can poke at it as a follow-up, that makes sense.

**Pull request closed without merging**
