### PR TITLE
release-20.1: *: Upgrade gogoproto

### PR DESCRIPTION
**Pull request by bdarnell**
Backport 1/1 commit from #58716. 

cc @cockroachdb/release

### CODE REVIEW

**Review by knz — APPROVED** [review]
I was initially surprised to see so many files changed in the vendor tree, but they are all generated .pb.go. So LGTM

**Comment by aaron-crl** [comment]
> I was initially surprised to see so many files changed in the vendor tree, but they are all generated .pb.go. So LGTM

same :LGTM:

**Comment by knz** [comment]
this is green so merging

**Comment by bdarnell** [comment]
Oops, thought I had already done that.

**Pull request merged**
