### PR TITLE
kv: add LockTimeout option to BatchRequest

### PR DESCRIPTION
**Pull request by nvb**
Informs #67513.

This commit introduces a new `lock_timeout` field on the BatchRequest Header struct.

lock_timeout specifies the maximum amount of time that the batch request will wait while attempting to acquire a lock on a key or while blocking on an existing lock in order to perform a non-locking read on a key. The time limit applies separately to each lock acquisition attempt. If the timeout elapses when waiting for a lock, a WriteIntentError will be returned.

Unlike in some other systems like PostgreSQL, where non-locking reads do not wait on conflicting locks, in CockroachDB, non-locking reads do wait for conflicting locks to be released. Because of this, the lock_timeout configuration applies to non-locking reads in read-write and read-only transactions as well.

Only the (default) Block wait policy will allow a request to wait on conflicting locks, so the timeout only makes sense in conjunction with the Block wait policy. The Error wait policy will throw an error immediately if a conflicting lock held by an active transaction is encountered, so this timeout can never be hit with an Error wait policy.

A value of zero disables the timeout.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
I haven't read the tests yet. Looks good, with just some small questions.

> Reviewed 2 of 2 files at r1, 10 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-:-MgBR5ss-SdnLhOFtLPP:bmz2tno)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBOvLS5UCqFEmW3ffh:-MgBOvLS5UCqFEmW3ffi:b-4fyqog) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f2d63c18203e251fccdb135dc6c03ece330095/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L299)):*
> ```Go
> 						ctx, req.LockTimeout,
> 						func(ctx context.Context) *Error { return w.pushLockTxn(ctx, req, state) },
> 						func(ctx context.Context) *Error { return w.pushLockTxnAfterTimeout(ctx, req, state) },
> ```

If it timed out while doing the push, I don't understand the reason for doing another push with error wait. The probability of success would be low. Is there extra information we need, like the latest state of the pushee?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBOPIo9ub6DWAWDbxm:-MgBOPIo9ub6DWAWDbxn:bnsf14l) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f2d63c18203e251fccdb135dc6c03ece330095/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L456)):*
> ```Go
> 		return doWithTimeoutAndFallback(
> 			ctx, req.LockTimeout,
> 			func(ctx context.Context) *Error { return w.pushLockTxn(ctx, req, state) },
> ```

same question here
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 777 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBN2ph5HNdPY-mT0yI:-MgBN2ph5HNdPY-mT0yJ:b9u3f3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f2d63c18203e251fccdb135dc6c03ece330095/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L777)):*
> ```Go
> 		// NOTE: we look at timeoutCtx.Err() and not err to avoid the
> 		// potential for bugs if context cancellation is not propagated
> 		// correctly on some error paths.
> ```

So you are worried about err being nil, or err not correctly specifying that it was due to the deadline being exceeded?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter_test.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBIDIs06wvwHio4SBR:-MgBIDIs06wvwHio4SBS:bjwjhou) ([raw file](https://github.com/cockroachdb/cockroach/blob/335901254c8ac8686e93656651beb4c5eb6bf474/pkg/kv/kvserver/concurrency/lock_table_waiter_test.go#L477)):*
> ```Go
> 	testutils.RunTrueAndFalse(t, "lockHeld", func(t *testing.T, lockHeld bool) {
> 		testutils.RunTrueAndFalse(t, "pusheeActive", func(t *testing.T, pusheeActive bool) {
> 			if !lockHeld && !pusheeActive {
> ```

can you add a comment like
// !lockHeld means a lock reservation, so is only possible when pusheeActive is true.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @stevendanna, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBOvLS5UCqFEmW3ffh:-MgH2uur6HxWW7HFmsZ2:bn4g9lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f2d63c18203e251fccdb135dc6c03ece330095/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L299)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If it timed out while doing the push, I don't understand the reason for doing another push with error wait. The probability of success would be low. Is there extra information we need, like the latest state of the pushee?
</blockquote></details>

The idea is that on a timeout, we don't know whether the PUSH_TIMESTAMP/PUSH_ABORT actually got to the point of proving that the pushee was active and began waiting in its `txnwait.Queue`. The push may have timed out before this point. But just like with `WaitPolicy_Error`, we don't want to throw an error on abandoned locks. So on timeout, we issue a PUSH_TOUCH request (like we do for `WaitPolicy_Error`) that is not subject to the `lock_timeout` to check with certainty whether the conflict is active or not, but without blocking if it happens to be active.

If you buy all this, I'll add some more commentary to spell this out in the code.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 777 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBN2ph5HNdPY-mT0yI:-MgH4BoG0lulTzQLZDKB:b-bvr006) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f2d63c18203e251fccdb135dc6c03ece330095/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L777)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So you are worried about err being nil, or err not correctly specifying that it was due to the deadline being exceeded?
</blockquote></details>

The latter. As it turns out, this is also what `contextutil.RunWithTimeout` does, presumable for the same reason.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter_test.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBIDIs06wvwHio4SBR:-MgH9-cS7h3-JjZ47etK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/335901254c8ac8686e93656651beb4c5eb6bf474/pkg/kv/kvserver/concurrency/lock_table_waiter_test.go#L477)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment like
// !lockHeld means a lock reservation, so is only possible when pusheeActive is true.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
sorry about the delay
:lgtm: 

> Reviewed 18 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-:-Mgg4G7mCFU6LCgoyGEK:bza7qlf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @stevendanna, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager_test.go, line 162 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-Mgg-Lj57mdWrUO0Doy3:-Mgg-Lj57mdWrUO0Doy4:b-pnkbns) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0380c89eed6f22c72918a188139c670f400efa1/pkg/kv/kvserver/concurrency/concurrency_manager_test.go#L162)):*
> ```Go
> 					// without a delay by the lockTableWaiter, ensuring that the lock
> 					// timeout logic deterministically fires.
> 					// See (*lockTableWaiterImpl).timeUntilDeadline.
> ```

Does this mean we are not testing the `doWithTimeoutAndFallback` code?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBOvLS5UCqFEmW3ffh:-Mgfwsxu8IpWJevYFxr-:b-67dsx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f2d63c18203e251fccdb135dc6c03ece330095/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L299)):*
> actually got to the point of proving that the pushee was active and began waiting in its txnwait.Queue

And it may not because of slowness elsewhere like network or cpu overload?

> If you buy all this, I'll add some more commentary to spell this out in the code.

sounds good
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter_test.go, line 701 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-Mgg1mrO3IUAnUyNfKc_:-Mgg1mrO3IUAnUyNfKca:b-183l97) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0380c89eed6f22c72918a188139c670f400efa1/pkg/kv/kvserver/concurrency/lock_table_waiter_test.go#L701)):*
> ```Go
> 					h roachpb.Header,
> 					pushType roachpb.PushTxnType,
> 				) (*roachpb.Transaction, *Error) {
> ```

never mind my earlier question about testing of the fallback path.

**Review by nvb — COMMENTED** [review]
> sorry about the delay

Not a problem at all, you were away for a few weeks and this was a big PR. Thanks for getting through all of it!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-:-Mgh7fAu0uOfTzzux4Dv:bbyoy2m)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @stevendanna, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68026#-MgBOvLS5UCqFEmW3ffh:-Mgh5_tfB9WOpfAbNbvw:bkamw9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f2d63c18203e251fccdb135dc6c03ece330095/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L299)):*
> And it may not because of slowness elsewhere like network or cpu overload?

Exactly. I added some commentary along these lines.

**Pull request merged**
