### PR TITLE
filetable: fix NPE when an empty file is downloaded from userfile

### LINKED ISSUE #62605: userfile: interface cast exception if the file has a metadata entry but no payload
`./cockroach userfile get` will fail with an interface cast exception if the file has a metadata entry but no payload.

```
SELECT f.file_id, sum_int(length(p.payload))
		FROM %s f LEFT OUTER JOIN %s p ON p.file_id = f.file_id
		WHERE f.filename = $1 GROUP BY f.file_id
```

the second column for this query will return NULL. We should probably use the file_size field in the metadata entry instead, or special case when seeing a nil.

### PR DESCRIPTION
**Pull request by adityamaru**
Fixes: #62605

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY4rjG3BI2RF1BycnIy:-MY4rjG3BI2RF1BycnIz:b-9i97ex) (no related file):*
Looks reasonable to me.  It might be nice to write a few words in the commit message about why we aren't using the `size` field in the metadata table.

---
___
*[pkg/cli/userfiletable_test.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY4k0GW36mFfvr1IIkj:-MY4k0GW36mFfvr1IIkk:b-eaoxge) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2afb0675bd196f0d2d0d12f8e636cd2259d3a0a/pkg/cli/userfiletable_test.go#L175)):*
> ```Go
> 		})
> 
> 		t.Run("get", func(t *testing.T) {
> ```

`tc.name+"_get"` might make for clearer output
___
*[pkg/cli/userfiletable_test.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY4ha5F6qJXPnD1oFgw:-MY4ha5GBhhn24QuIHzr:b3e6dpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2afb0675bd196f0d2d0d12f8e636cd2259d3a0a/pkg/cli/userfiletable_test.go#L181)):*
> ```Go
> 			cliOutput, err := c.RunWithCaptureArgs(cmd)
> 			require.NoError(t, err)
> 			if strings.Contains(cliOutput, "ERROR: no files matched requested path or path pattern") {
> ```

Would it be worth it to be less strict here? Given the line below, I imagine anything starting with `ERROR` would be unexpected.

It's a little unfortunate that RunWithCaptureArgs swallows the error produced by what I hope would be the non-zero exit of the command.

**Review by pbardea — APPROVED** [review]

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY53AJK7HeAl0hIYi_U:-MY53AJK7HeAl0hIYi_V:bl1o0qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2afb0675bd196f0d2d0d12f8e636cd2259d3a0a/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L701)):*
> ```Go
> 		fileID = vals[0].([]byte)
> 		if vals[1] != nil {
> 			sz = vals[1].(int64)
> ```

perhaps we should use tree.MustBeX methods instead of direct cases?

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

___
*[pkg/cli/userfiletable_test.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY4k0GW36mFfvr1IIkj:-MY6NHqcCDo1uArULI1I:b-8h77vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2afb0675bd196f0d2d0d12f8e636cd2259d3a0a/pkg/cli/userfiletable_test.go#L175)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

`tc.name+"_get"` might make for clearer output
</blockquote></details>

As a bonus, it looks like these other test cases would be good candidates for subtests of the `tc.name` one above, which would help avoid the awkward tc.name+subTestName formulation for all of these subtests.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY4rjG3BI2RF1BycnIy:-MY9vA254LvPMbgxWWmY:bjpr03) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Looks reasonable to me.  It might be nice to write a few words in the commit message about why we aren't using the `size` field in the metadata table.
</blockquote></details>

I wanted to minimize the diff so that we can consider a backport for this, but apart from that I don't really see a reason we can't consult the file size we write in the metadata row. I guess there is an argument that this is the most accurate source of truth, but if the former were to go out of sync we probably have another bug.

---
___
*[pkg/cli/userfiletable_test.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY4k0GW36mFfvr1IIkj:-MY9qhp56tiUIpboJZK_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2afb0675bd196f0d2d0d12f8e636cd2259d3a0a/pkg/cli/userfiletable_test.go#L175)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

As a bonus, it looks like these other test cases would be good candidates for subtests of the `tc.name` one above, which would help avoid the awkward tc.name+subTestName formulation for all of these subtests.
</blockquote></details>

Done.
___
*[pkg/cli/userfiletable_test.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY4ha5F6qJXPnD1oFgw:-MY9qiF0BFjqyPD9TJ0v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2afb0675bd196f0d2d0d12f8e636cd2259d3a0a/pkg/cli/userfiletable_test.go#L181)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Would it be worth it to be less strict here? Given the line below, I imagine anything starting with `ERROR` would be unexpected.

It's a little unfortunate that RunWithCaptureArgs swallows the error produced by what I hope would be the non-zero exit of the command.
</blockquote></details>

Done.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63467#-MY53AJK7HeAl0hIYi_U:-MY9s9el19Gk2WgNNQH0:bl0vnri) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2afb0675bd196f0d2d0d12f8e636cd2259d3a0a/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L701)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

perhaps we should use tree.MustBeX methods instead of direct cases?
</blockquote></details>

The internal executor above can use these methods because the results of the iterator are Datums, but for a SQLConnExecutor the results are `driver.Value` which I believe can't be converted to datums easily.

**Review by stevendanna — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

**Comment by adityamaru** [comment]
TFTR!
bors r=stevendanna

**Comment by rafiss** [comment]
@adityamaru friendly ping on this: does this still need to be backported?

**Pull request merged**
