### PR TITLE
coldata: remove pkg/sql/exec/execgen dep

### PR DESCRIPTION
**Pull request by danhhz**
Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
lol, cool. thanks.

**Review by yuzefovich — APPROVED** [review]
That was easy, thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39475#-:-LlnULJpB75BplWS2gmL:brm8q9j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by danhhz** [comment]
bors r=jordanlewis,yuzefovich

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39475#-Llnj8Tn4IvrRM3uCrYB:-Llnj8Tn4IvrRM3uCrYC:b-83c2yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66530ef50d1431c5add9b7c669668f0ca53bd55/pkg/sql/exec/coldata/vec_tmpl.go#L26)):*
> ```Go
> 
> 	"github.com/cockroachdb/apd"
> 	"github.com/cockroachdb/cockroach/pkg/sql/exec/execgen"
> ```

It appears to not have worked.

I think we should keep this import line in-place but surround it with `//{{/*` before and `// */}}` after.

**Review by danhhz — COMMENTED** [review]
bors r=jordanlewis,yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39475#-:-Llnly8Q2jakkwzDeWLD:b-gmedaw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39475#-Llnj8Tn4IvrRM3uCrYB:-Llnm0WT-kldJjZz8QU1:bjtm9te) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66530ef50d1431c5add9b7c669668f0ca53bd55/pkg/sql/exec/coldata/vec_tmpl.go#L26)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It appears to not have worked.

I think we should keep this import line in-place but surround it with `//{{/*` before and `// */}}` after.
</blockquote></details>

works for me

**Pull request merged**
