### PR TITLE
workload: use IMPORT then BACKUP in 'fixtures make'

### PR DESCRIPTION
**Pull request by dt**
Previously we used the 'transform' option on IMPORT.

However that option will soon go away as IMPORT is increasingly focused on ingestion.
Making fixtures should hopefully be rare enough that we can do a little extra work here
rather than maintain the special 'transform' mode.

Release note: none.

### CODE REVIEW

**Review by bobvawter — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37343#-:-LeH3Zin2d_OT-ygnWPi:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

**Review by danhhz — APPROVED** [review]
The `fixtures make` command didn't used to modify your cluster (besides creating jobs). I'd add a very short bit to the cli cmd description that it works by ingesting and backing up the data.

:lgtm: mod 2 comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37343#-:-LeHdghA8NvWSAtqT0bX:brqxpkx)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/workloadccl/fixture.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37343#-LeHdRESEwmqGlJStZ9D:-LeHdRET7LOOFjZOtgff:bkcc02h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c024660c3c16aa08acada5c62ef938abc32f7619/pkg/ccl/workloadccl/fixture.go#L264)):*
> ```Go
> 	}
> 
> 	if _, err := ImportFixture(ctx, sqlDB, gen, dbName, false, 1, false, ""); err != nil {
> ```

our style is to have `/* */` comments on all these false, 1, false, "" params

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37343)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @bobvawter)

___
*[pkg/ccl/workloadccl/fixture.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37343#-LeHdRESEwmqGlJStZ9D:-LeHlUYOBB5YH_XsouXL:b-2el2n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c024660c3c16aa08acada5c62ef938abc32f7619/pkg/ccl/workloadccl/fixture.go#L264)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

our style is to have `/* */` comments on all these false, 1, false, "" params
</blockquote></details>

Done.

I made them named consts.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37343)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @bobvawter)

___
*[pkg/ccl/workloadccl/fixture.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37343#-LeHdRESEwmqGlJStZ9D:-LeHr8u83QnP0RFHKeje:b-8uztlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c024660c3c16aa08acada5c62ef938abc32f7619/pkg/ccl/workloadccl/fixture.go#L264)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.

I made them named consts.
</blockquote></details>

Even better

**Pull request merged**
