### PR TITLE
*: add a context argument to storagepb.ReplicaRequestFilter

### PR DESCRIPTION
**Pull request by knz**
Suggested by @tbg 
This will unblock progress on #44342.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45133#-:-M09B0fe5br2TntaTjj1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/sql/user_test.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45133#-M09Ar3Y8L_I2JDaeYyE:-M09Ar3Y8L_I2JDaeYyF:b1ok9hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b643e977106365e5fa0994d0bdd6091ba5fdde55/pkg/sql/user_test.go#L126)):*
> ```Go
> 
> 	// Configure the login timeout to just 1s.
> 	if _, err := db.Exec(`SET CLUSTER SETTING server.user_login.timeout = '1s'`); err != nil {
> ```

How do you feel about making this shorter than 1s?  I imagine this will roughly control the duration of the test.

**Comment by knz** [comment]
> How do you feel about making this shorter than 1s? I imagine this will roughly control the duration of the test.

I'm a bit wary of slowness under testrace. What about lowering the timeout and excluding the test from testrace runs?

**Review by ajwerner — COMMENTED** [review]
sgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45133#-:-M09CtbLEJbjz5-Th3an:bb7ohn6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by knz** [comment]
Done.
TFYR!

bors r=ajwerner

**Pull request merged**
