### PR TITLE
sql: fix invalid constraints being generated for secondary regions

### LINKED ISSUE #88559: multiregionccl: Secondary Region zone configs are invalid
**Describe the problem**

When Primary and Secondary regions are set - creating multiple table in a database with survival goal of REGION - some tables created in this database have a lease holder in US_WEST-1 region which is not primary.  This is not expected behavior.
**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster with three regions (US_EAST-1, US_EAST-2, US_WEST-1 with three servers in each region - zones A/B/C)
```
CREATE DATABASE alex PRIMARY REGION "US_EAST-1" REGIONS "US_EAST-1","US_EAST-2","US_WEST-1"  SURVIVE REGION FAILURE SECONDARY REGION "US_EAST-2";
show regions;                                                                                                                            
   region   |  zones  | database_names | primary_region_of | secondary_region_of
------------+---------+----------------+-------------------+----------------------
  US_EAST-1 | {A,B,C} | {alex}         | {alex}            | {}
  US_EAST-2 | {A,B,C} | {alex}         | {}                | {alex}
  US_WEST-1 | {A,B,C} | {alex}         | {}                | {}
(3 rows)
Time: 48ms total (execution 48ms / network 0ms)
show zone configuration from database alex;                                                                                              
     target     |                                     raw_config_sql
----------------+------------------------------------------------------------------------------------------
  DATABASE alex | ALTER DATABASE alex CONFIGURE ZONE USING
                |     range_min_bytes = 134217728,
                |     range_max_bytes = 536870912,
                |     gc.ttlseconds = 90000,
                |     num_replicas = 5,
                |     num_voters = 5,
                |     constraints = '{+region=US_EAST-1: 1, +region=US_EAST-2: 1, +region=US_WEST-1: 1}',
                |     voter_constraints = e'{\'+region=US_EAST-1,+region=US_EAST-2\': 2}',
                |     lease_preferences = '[[+region=US_EAST-1, +region=US_EAST-2]]'
(1 row)
show tables;
  schema_name | table_name | type  | owner | estimated_row_count |              locality
--------------+------------+-------+-------+---------------------+--------------------------------------
  public      | users1     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users2     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users3     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users4     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users5     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users6     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users7     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users8     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
  public      | users9     | table | root  |                   0 | REGIONAL BY TABLE IN PRIMARY REGION
(9 rows)
root@localhost:26260/alex> show ranges from table users9;
  start_key | end_key | range_id |       range_size_mb        | lease_holder |  lease_holder_locality  |  replicas   |                                                         replica_localities
------------+---------+----------+----------------------------+--------------+-------------------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------
  NULL      | NULL    |       90 | 0.000042000000000000000000 |            9 | region=US_WEST-1,zone=B | {1,5,7,8,9} | {"region=US_EAST-1,zone=A","region=US_EAST-1,zone=B","region=US_EAST-2,zone=B","region=US_EAST-2,zone=A","region=US_WEST-1,zone=B"}
(1 row)
Time: 36ms total (execution 36ms / network 0ms) (edited) 
```

**Expected behavior**
All tables for database alex should have leaseholder in US_EAST-1 as long as this region is up.

**Environment:**
 - CockroachDB v22.2-alpha-03
 - Server OS: Ubuntu
 - Client app cockroach sql

**Additional context**
did this test on a single box using multiple ports

Jira issue: CRDB-19954

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/88559

See individual commits to make it easier to review.

This also enhances validation in two ways:
- Make sure there are no repeat keys in lease preference constraints.
- Call validattion functions when using high level multiregion
  primitives, not just when setting zone configs explicitly.

Release note (bug fix): The zone configs generated
for a database with a secondary region were invalid.
The voter_constraints and the lease preferences called
for voters and leaseholders to exist in both the
primary and secondary region which is impossible.
This bug was present since v22.2.0-alpha.1.

### CODE REVIEW

**Review by aayushshah15 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89956)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[`pkg/sql/region_util.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89956#-NENWhVe3tEijgvQezLL:-NENWhVe3tEijgvQezLM:b-g00hlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed143fb161e4baaf360b315bb2f1cb51a24189e2/pkg/sql/region_util.go#L449)):*
> ```Go
> 		if regionConfig.HasSecondaryRegion() && regionConfig.SecondaryRegion() != region {
> 			ret = append(ret, zonepb.ConstraintsConjunction{
> 				NumReplicas: maxFailuresBeforeUnavailability(numVoters),
> ```

This is pinning 2 replicas to the secondary region, I don't think that's what we want. I think we only want to pin 2 replicas to the primary region and 1 to the secondary region. 


The following section from the MR functional spec (https://docs.google.com/document/d/1j4XxQtLJIYIsxmj6m3DkMlUsC1XyVHXN_d32YWSKydM/edit#heading=h.l8n11rpefd8e) talks about how the total `num_replicas` value is determined based on the assumption that every region other than the primary region is expected to have exactly 1 replica.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89956)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @arulajmani)

___
*[`pkg/sql/region_util.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89956#-NENWhVe3tEijgvQezLL:-NENZHtz2X2VRHqcc-2m:b-lwjr42) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed143fb161e4baaf360b315bb2f1cb51a24189e2/pkg/sql/region_util.go#L449)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This is pinning 2 replicas to the secondary region, I don't think that's what we want. I think we only want to pin 2 replicas to the primary region and 1 to the secondary region. 


The following section from the MR functional spec (https://docs.google.com/document/d/1j4XxQtLJIYIsxmj6m3DkMlUsC1XyVHXN_d32YWSKydM/edit#heading=h.l8n11rpefd8e) talks about how the total `num_replicas` value is determined based on the assumption that every region other than the primary region is expected to have exactly 1 replica.  


</blockquote></details>

i'm catching up a bit on the secondary region design, but my understanding is that this change is part of the secondary region proposal: https://docs.google.com/document/d/1uE2BXHK6Iet7GUuISDHw1pbOP7v-H4AixD5kZGZLYEo/edit#

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89956)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[`pkg/sql/region_util.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89956#-NENbLuF5FCxQgoqID2o:-NENbLuF5FCxQgoqID2p:b28ub19) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed143fb161e4baaf360b315bb2f1cb51a24189e2/pkg/sql/region_util.go#L330)):*
> ```Go
> 	case descpb.SurvivalGoal_REGION_FAILURE:
> 		// The primary and secondary region each have two voters.
> 		// maxFailuresBeforeUnavailability(numVotersForZoneSurvival) = 2.
> ```

Should this be `s/numVotersForZoneSurvival/numVotersForRegionSurvival`?
___
*[`pkg/sql/region_util.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89956#-NENbYgf5RuOJRh92aAz:-NENbYgf5RuOJRh92aB-:bjf7w4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed143fb161e4baaf360b315bb2f1cb51a24189e2/pkg/sql/region_util.go#L341)):*
> ```Go
> 
> 		numVoters = numVotersForRegionSurvival
> 		// We place the maximum concurrent replicas that can fail before a range
> ```

This comment block deserves an update.
___
*[`pkg/sql/region_util.go` line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89956#-NENboWs3OEZiFLdlnTB:-NENboWs3OEZiFLdlnTC:b-xyoxa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed143fb161e4baaf360b315bb2f1cb51a24189e2/pkg/sql/region_util.go#L344)):*
> ```Go
> 		// outage in the home region, and ensure that there's at least one replica
> 		// in all other regions.
> 		numReplicas = numRegionsWithTwoVoters*maxFailuresBeforeUnavailability(numVotersForRegionSurvival) + (numRegions - numRegionsWithTwoVoters)
> ```

This computation is kind of confusing for me the way it's written at the moment. Do you think it would be cleaner to write this as follows:

```
// 2 replicas in the primary region, 1 replica in every other region.
numReplicas = maxFailuresBeforeUnavailability(numVotersForRegionSurvival) + (int32(numRegions) - 1)
if regionConfig.HasSecondaryRegion() {
  numReplicas += 1  // If there is a secondary region, it gets an additional replica.
}
```
The above seems a lot easier to quickly reason about, imo. 
___
*[`pkg/sql/region_util.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89956#-NENWhVe3tEijgvQezLL:-NENfPk3BO_ZG5A_W6wQ:b5uhnl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed143fb161e4baaf360b315bb2f1cb51a24189e2/pkg/sql/region_util.go#L449)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm catching up a bit on the secondary region design, but my understanding is that this change is part of the secondary region proposal: https://docs.google.com/document/d/1uE2BXHK6Iet7GUuISDHw1pbOP7v-H4AixD5kZGZLYEo/edit#
</blockquote></details>

Thanks for linking that document, I see that the `num_replicas` computation inside `getNumVotersAndNumReplicas` was indeed updated to take this into consideration.

**Comment by rafiss** [comment]
@aayushshah15 this is ready for another review

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

@rafiss any interest in filing an issue to perhaps add secondary regions and/or super regions to the multi-region TPCC roachtests? Should be a small work item and get us a bunch of extra coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89956#-:-NEgDLlW764eXFMjhRqq:b-v755hk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

**Comment by rafiss** [comment]
tftr! yes for sure - i have been working on adding a datadriven test in pkg/ccl/multiregionccl/testdata/secondary_region but have been finding it a challenge to make it deterministic. I did confirm that the failover works manually with roachprod. I will track adding the tests in this issue: https://github.com/cockroachdb/cockroach/issues/90169

bors r=aayushshah15

**Pull request merged**
