### PR TITLE
cli: increase limit for debug's open file descriptors

### PR DESCRIPTION
**Pull request by a6802739**
@BramGruneir, please have a look to see if I've done it right.
#7886

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7981)

### CODE REVIEW

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cli/debug.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7981#-KNXUL0HrJTFQ6hwp6fj:-KNXUL0HrJTFQ6hwp6fk:-522691031) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef1b3c822fd197a5a0ee6a54c31eea29707d0fc/cli/debug.go#L88)):*
> ```Go
> }
> 
> func setMaxOpenFiles() (int, error) {
> ```

Is there a way to not have to repeat most of this?  The other function does almost the same thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7981)*

**Comment by a6802739** [comment]
@BramGruneir, yes it does. maybe I should add a wrap with `server/context.go`

**Comment by BramGruneir** [comment]
Sure. Or even pull out the meat of both functions and drop it in util or something.  As long as we don't repeat the code I think we're good.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7981#-:-KNXnPZlzsAjNp0h-rXo:1925311639)*

**Comment by a6802739** [comment]
@BramGruneir, got it. thanks a lot. : )

**Comment by a6802739** [comment]
@BramGruneir , could you help me review it?

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7981#-:-KOL5whykinXknH6t59c:1417088721)*

**Comment by knz** [comment]
@BramGruneir this looks good, unless you object I'll go ahead and merge it.

**Comment by BramGruneir** [comment]
Go for it.  LGTM

**Comment by knz** [comment]
Thanks @a6802739 again for your help!

**Pull request merged**
