### PR TITLE
libroach: further decomposition of db.cc

### PR DESCRIPTION
**Pull request by petermattis**
Split the various engine implementations out of `db.cc`. Move the merge
operator routines into `merge.cc`. Move the `MVCC*` routines into
`mvcc.cc`. Move the custom RocksDB comparator to `comparator.cc`.

This is all code movement: no functional changes.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
I think this gets us to a reasonable place.

**Comment by petermattis** [comment]
Added a few others as reviewers who might have opinions about the organization of code in `libroach`.

**Comment by petermattis** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[c-deps/libroach/ccl/db.cc, line 18 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TN21a11yripH8F71D:-L3TN21a11yripH8F71E:b151j2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f213b2e1d727af3a1cbdcc80a5bac50537e2ec0/c-deps/libroach/ccl/db.cc#L18)):*
> ```cpp
> #include <rocksdb/write_batch.h>
> #include "../batch.h"
> #include "../comparator.h"
> ```

@benesch Do you know how to avoid these relative includes? Seems like there should be some cmake configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636)*

**Comment by mberhault** [comment]
I'm overall happy with this kind of re-org, just really not while https://github.com/cockroachdb/cockroach/pull/21580 is pending, this will be a nasty merge.

---

Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[c-deps/libroach/ccl/db.cc, line 18 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TN21a11yripH8F71D:-L3TNyYHy8fk4MfN-EQU:b1v5kjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f213b2e1d727af3a1cbdcc80a5bac50537e2ec0/c-deps/libroach/ccl/db.cc#L18)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@benesch Do you know how to avoid these relative includes? Seems like there should be some cmake configuration.
</blockquote></details>

Things used in common by `./` and `ccl/` should ideally be in sub-directories that are added to the include list. Easy enough for things like `../fmt.h`, not so much for the ones listed here. The dirty way would be to include `./` as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-:-L3TOLUQzFznjo2TYs24:b-679mnt)*

**Comment by petermattis** [comment]
> I'm overall happy with this kind of re-org, just really not while #21580 is pending, this will be a nasty merge.

I'll hold off on merging until #21580 goes in. 

---

Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-:-L3TPwuZPGpADBZfRUlz:bleaqjs)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 24 of 24 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/batch.cc, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TP3IR4PAbc8YnExz1:-L3TP3IR4PAbc8YnExz2:b-44oipx) ([raw file](https://github.com/cockroachdb/cockroach/blob/124136e363ff227151a0ca3250be26dd5e6d71b3/c-deps/libroach/batch.cc#L33)):*
> ```cpp
> // pointing to "key" if no updates existing for that key in the batch.
> //
> // Note that RocksDB WriteBatches append updates
> ```

nit: weird flow

---

*[c-deps/libroach/mvcc.cc, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TQoboL358J7NyZ7Rx:-L3TQoboL358J7NyZ7Ry:bii8739) ([raw file](https://github.com/cockroachdb/cockroach/blob/124136e363ff227151a0ca3250be26dd5e6d71b3/c-deps/libroach/mvcc.cc#L80)):*
> ```cpp
>   std::string prev_key;
>   bool first = false;
>   // NB: making this uninitialized triggers compiler warnings
> ```

This is random, but you didn't have any opinions on this, did you? This would be the first time any compiler was wrong about any warning issued to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-:-L3TRWzw5v8-rZF-xuuE:bnfp4nl)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/ccl/db.cc, line 18 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TN21a11yripH8F71D:-L3TSDJvZUAzzHij707F:b-bm0jdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f213b2e1d727af3a1cbdcc80a5bac50537e2ec0/c-deps/libroach/ccl/db.cc#L18)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Things used in common by `./` and `ccl/` should ideally be in sub-directories that are added to the include list. Easy enough for things like `../fmt.h`, not so much for the ones listed here. The dirty way would be to include `./` as well.
</blockquote></details>

After checking, `rocksdb` does include its own `PROJECT_SOURCE_DIR` so that their includes look like `util/blahblah.h`. This seems reasonable to do for us as well. Moving things into separate subdirs can be done at a later date.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636)*

**Comment by bdarnell** [comment]
:lgtm: 

I think this may have gone a little too far towards lots of small files, but i don't have an alternative arrangement to offer. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-:-L3TVEUBoOq0lQGvIcLv:b-xl64bc)*

**Comment by petermattis** [comment]
Review status: 23 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[c-deps/libroach/batch.cc, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TP3IR4PAbc8YnExz1:-L3TWDg0NmNyZsVuZcxb:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/124136e363ff227151a0ca3250be26dd5e6d71b3/c-deps/libroach/batch.cc#L33)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

nit: weird flow
</blockquote></details>

Fixed.

---

*[c-deps/libroach/mvcc.cc, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TQoboL358J7NyZ7Rx:-L3TVjy-7M6glorrAVcG:b-5eq8lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/124136e363ff227151a0ca3250be26dd5e6d71b3/c-deps/libroach/mvcc.cc#L80)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This is random, but you didn't have any opinions on this, did you? This would be the first time any compiler was wrong about any warning issued to me.
</blockquote></details>

Seems reasonable to me that the compiler can't figure out that `accrue_gc_age_nanos` is being initialized before use. The compiler is doing some data flow analysis and you're running into the limits. This is fairly typical for C++ compiler warnings in my experience. We don't see this in Go because all variables are default 0 initialized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636)*

**Comment by benesch** [comment]
Reviewed 23 of 24 files at r1, 3 of 3 files at r3, 1 of 2 files at r4.
Review status: 25 of 26 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[c-deps/libroach/options.h, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TY-24lBhKGJG4GvI3:-L3TY-24lBhKGJG4GvI4:b-43o21q) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ab3be8c747b81e6df1334f6b3c250b1a961f0d/c-deps/libroach/options.h#L29)):*
> ```objc
> // local variables:
> // mode: c++
> // end:
> ```

Stray editor-specific config.

---

*[c-deps/libroach/ccl/db.cc, line 18 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TN21a11yripH8F71D:-L3TYgvt5MBY3lueVv9i:b-2vr5oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f213b2e1d727af3a1cbdcc80a5bac50537e2ec0/c-deps/libroach/ccl/db.cc#L18)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

After checking, `rocksdb` does include its own `PROJECT_SOURCE_DIR` so that their includes look like `util/blahblah.h`. This seems reasonable to do for us as well. Moving things into separate subdirs can be done at a later date.
</blockquote></details>

I'd hesitate to use RocksDB's build system as an example of what to do in general, but agreed, sticking `PRIVATE .` into libroachccl's `target_include_directories` seems reasonable.

(The relative imports don't bother me though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636)*

**Comment by petermattis** [comment]
Per in-person discussion with @mberhault, I'm going to merge this and will help with any conflicts that arise with his PR.

**Comment by petermattis** [comment]
Review status: 15 of 30 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/options.h, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636#-L3TY-24lBhKGJG4GvI3:-L3Z3sYitu03_D2eKmwW:b4elz6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ab3be8c747b81e6df1334f6b3c250b1a961f0d/c-deps/libroach/options.h#L29)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Stray editor-specific config.
</blockquote></details>

Ack. I've removed all of these. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21636)*

**Pull request merged**
