### PR TITLE
server: add proxy protocol support

### LINKED ISSUE #130706: Support Proxy Protocol Headers in CRDB
[Proxy protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) is a way to preserve the original client IP address when transferring data across a proxy which rewrites the original source IP address.

One such proxy is AWS Network Load Balancers which have Client IP preservation disabled. Client IP preservation must be disabled on Network Load Balancers which have Cross-Zone Load Balancing enabled, or load balancer targets (e.g. CockroachDB nodes) will experience TCP socket collisions.

We wish to add a startup flag `--accept-proxy-protocol-headers` which, when enabled, will allow CRDB network listeners to parse proxy protocol headers and use the client IP information therein instead of the source IP of the incoming packets.

Related Jira issue: [CC-26729](https://cockroachlabs.atlassian.net/browse/CC-26729)

Jira issue: CRDB-42185

### PR DESCRIPTION
**Pull request by DuskEagle**
This commit adds an `--accept-proxy-protocol-headers` flag to CockroachDB startup commands. When set, it allows CockroachDB to parse proxy protocol headers and use the client IP information therein.

Resolves #130706

Release note: None

### CODE REVIEW

**Review by cthumuluru-crdb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130707)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DuskEagle and @stevendanna)

___
*[`pkg/server/listen_and_update_addrs_test.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130707#-O7510vi8oK9B3r7jOoZ:-O7510vi8oK9B3r7jOo_:b-e6316f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e46fed710a56f4a3e8316e8df9460acb9b70106/pkg/server/listen_and_update_addrs_test.go#L23)):*
> ```Go
> )
> 
> func TestListenAndUpdateAddrs(t *testing.T) {
> ```

Is it possible to write an end to end mock test (dial a conn, pass header followed by data)?

**Comment by DuskEagle** [comment]
> Is it possible to write an end to end mock test (dial a conn, pass header followed by data)?

Done! PTAL

**Review by cthumuluru-crdb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130707)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DuskEagle and @stevendanna)

___
*[`pkg/cli/flags.go` line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130707#-O7YAXXI2rqquvdYLuCA:-O7YAXXI2rqquvdYLuCB:bxsebor) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda4f3ed5587942c83353e638cfc1707f5d61ab6/pkg/cli/flags.go#L453)):*
> ```Go
> 		cliflagcfg.VarFlag(f, addr.NewAddrSetter(&serverHTTPAdvertiseAddr, &serverHTTPAdvertisePort), cliflags.HTTPAdvertiseAddr)
> 
> 		cliflagcfg.BoolFlag(f, &serverCfg.AcceptProxyProtocolHeaders, cliflags.AcceptProxyProtocolHeaders)
> ```

Covers all the surfaces we want (`start`, `start-single-node` and `mt start-sql`). 
___
*[`pkg/server/tenant.go` line 593 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130707#-O7YCGwl7aVlhiw6cRjZ:-O7YCGwl7aVlhiw6cRj_:b-k4gbkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda4f3ed5587942c83353e638cfc1707f5d61ab6/pkg/server/tenant.go#L593)):*
> ```Go
> 	}
> 
> 	pgL, loopbackPgL, rpcLoopbackDialFn, startRPCServer, err := startListenRPCAndSQL(ctx, workersCtx, *s.sqlServer.cfg, s.stopper, s.grpc, lf, enableSQLListener, s.cfg.AcceptProxyProtocolHeaders)
> ```

We could optionally use functional options here and couple of other places. (https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Functional-Options).

**Pull request merged**
