### PR TITLE
colexec: assert BCE in some sets

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
What do you think about something like this? Confusingly, `TestGCAssert` linter now fails with many inlining issues, not sure what's up with that.

**Comment by yuzefovich** [comment]
Huh, I removed some empty lines and now the linter passes. This stuff is so weird.

**Comment by jordanlewis** [comment]
It's probably a bug in gcassert. Can you make a reproduction case and file to `https://github.com/jordanlewis/gcassert` if you can remember what went wrong?

**Comment by jordanlewis** [comment]
Overall, I don't really like this idea. We should remove `execgen.SET` and replace it with a method, since the method should be trivially inlineable. I don't know why we didn't do that - maybe the BCE doesn't work as well in those cases?

**Comment by yuzefovich** [comment]
closing in favor of #57854

**Pull request closed without merging**
