### PR TITLE
upgrade: automatically bump the system DB version

### LINKED ISSUE #121914: sql: add a test that verifies that the system database schema version is correct after upgrade
In the 23.2 release cycle, #104714 added a system table but the [upgrade](https://github.com/cockroachdb/cockroach/blob/e929e8b9472e525d44bfe691b6c6d46d343edcd0/pkg/upgrade/upgrades/v23_2_system_exec_insights.go#L23) does not bump the system database schema version. The PR does change the bootstrap version, so depending on whether we created a cluster on 23.2 or upgraded a cluster from 23.1, we end up with a different schema version.

To prevent this in the future, we should have a test that upgrades a cluster from the previous version and then asserts that the system database schema version is the same as the bootstrap version.

Somewhat related - it's a bit unfortunate that the schema version is an upgrade version (e.g 23.1-32) which will later require special code to determine if this version is acceptable given a minimum supported cluster version of 23.2. It would be ideal if the final schema version matches the latest cluster version. Perhaps the final upgrade step could always be a "finalize schema version" where we bump the version to the bootstrap version.

Jira issue: CRDB-37616

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by rafiss**
Rather than making authors of an upgrade remember that they should bump
the version of the system DB schema, now it will be bumped automatically
after any upgrade step that has a migration or if upgrading to the final
cluster version for a release. Two tests are added:

- TestSystemDatabaseSchemaBootstrapVersionBumped makes sure the
  SystemDatabaseSchemaBootstrapVersion is incremented whenever
  clusterversion.Latest changes AND if that version has an upgrade
  migration or is the final version in a release.
- TestUpgradeHappensAfterMigrations is augmented to check that after all
  upgrades run, the actual system database schema version is equal to
  the SystemDatabaseSchemaBootstrapVersion.

Taken together, these tests ensure that the system database bootstrap
version is manually incremented in the code when it should be, and that
the automatic upgrade process correctly increments the version.

This change results in more work, since it means that the version will
be bumped when it is not strictly necessary to do so. But since it
makes it harder to forget a manual step, it seems worth doing.

fixes https://github.com/cockroachdb/cockroach/issues/121914
Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: @dt should take a look too in case we're missing something.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-:-NwM0VJU4J747ePP7872:bflq64a)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @fqazi, and @rafiss)

___
*[`pkg/upgrade/upgrademanager/manager.go` line 530 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwM0EKZ8328tC1t1_O5:-NwM0EK_8nW5_jRrf33m:bm1qftu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/upgrade/upgrademanager/manager.go#L530)):*
> ```Go
> 		}
> 
> 		// Bump the version of the system database schema.
> ```

Should we do this above the interlock above? (that's what happened before, for the upgrades that did bump it)

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwNbWcdDDMX0ka_Xp-l:-NwNbWcdDDMX0ka_Xp-m:beu50kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/sql/catalog/systemschema/system.go#L1212)):*
> ```Go
> func MakeSystemDatabaseDesc() catalog.DatabaseDescriptor {
> 	priv := privilege.List{privilege.CONNECT}
> 	latestVersion := clusterversion.Latest.Version()
> ```

If I recall correctly, I was thinking of doing something similar when I first added this field but someone (maybe it was @dt?) raised an objection over the fact that this would mean we'd need to regenerate the bootstrap testdata for every new version gate regardless of whether it changed the system schema. Is anyone still concerned by this?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @fqazi, and @rafiss)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwNbWcdDDMX0ka_Xp-l:-NwO0XOf0CWLUFY-vA0z:b-i33r74) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/sql/catalog/systemschema/system.go#L1212)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

If I recall correctly, I was thinking of doing something similar when I first added this field but someone (maybe it was @dt?) raised an objection over the fact that this would mean we'd need to regenerate the bootstrap testdata for every new version gate regardless of whether it changed the system schema. Is anyone still concerned by this?
</blockquote></details>

I think it was this comment https://github.com/cockroachdb/cockroach/pull/111404#discussion_r1343040618.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @fqazi, and @RaduBerinde)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwNbWcdDDMX0ka_Xp-l:-NwePKQy-NKxfe-B_hpd:b-ui5zgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/sql/catalog/systemschema/system.go#L1212)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I think it was this comment https://github.com/cockroachdb/cockroach/pull/111404#discussion_r1343040618.
</blockquote></details>

i did a test locally and added a new clusterversion, and i did not need to regenerate the bootstrap data. i may not understand why though -- is it because the bootstrap data just has the _contents_ of the system database, but not the system database descriptor itself? 
___
*[`pkg/upgrade/upgrademanager/manager.go` line 530 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwM0EKZ8328tC1t1_O5:-NwePJinEh6wQKuZD6rN:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/upgrade/upgrademanager/manager.go#L530)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should we do this above the interlock above? (that's what happened before, for the upgrades that did bump it)
</blockquote></details>

sgtm

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @fqazi)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwNbWcdDDMX0ka_Xp-l:-NweSPNj3JfCR7Zghsk3:bmq2bhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/sql/catalog/systemschema/system.go#L1212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i did a test locally and added a new clusterversion, and i did not need to regenerate the bootstrap data. i may not understand why though -- is it because the bootstrap data just has the _contents_ of the system database, but not the system database descriptor itself?
</blockquote></details>

The bootstrap data has all the KVs on a freshly bootstrapped cluster, it should include this version somewhere no? Otherwise how do we know what version we're reading..

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @RaduBerinde, and @rafiss)

___
*[`pkg/upgrade/upgrademanager/manager.go` line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NweXH5W0edPAq8ipCbP:-NweXH5W0edPAq8ipCbQ:bw83sg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/upgrade/upgrademanager/manager.go#L579)):*
> ```Go
> 		}
> 		systemDBDesc.SystemDatabaseSchemaVersion = &cs.Version
> 		return txn.Descriptors().WriteDesc(ctx, false /* kvTrace */, systemDBDesc, txn.KV())
> ```

Just a general question should we worry about long running transactions potentially holding up the upgrade? We need to bump the system database descriptor version, so leases need to expire on the system database. Not sure if we want to make that operation high priority.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @fqazi, and @RaduBerinde)

___
*[`pkg/upgrade/upgrademanager/manager.go` line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NweXH5W0edPAq8ipCbP:-NweZu4ODVKRmuIIIDRo:b-rf8h8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/upgrade/upgrademanager/manager.go#L579)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Just a general question should we worry about long running transactions potentially holding up the upgrade? We need to bump the system database descriptor version, so leases need to expire on the system database. Not sure if we want to make that operation high priority.
</blockquote></details>

that's a fair point. that question would also apply to all the upgrades themselves ([example](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/upgrade/upgrades/v24_1_system_database.go#L31)) that modify the system DB right?

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @RaduBerinde, and @rafiss)

___
*[`pkg/upgrade/upgrademanager/manager.go` line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NweXH5W0edPAq8ipCbP:-Nwe__H-EbIenRGNGDD-:b-fl5bx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/upgrade/upgrademanager/manager.go#L579)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

that's a fair point. that question would also apply to all the upgrades themselves ([example](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/upgrade/upgrades/v24_1_system_database.go#L31)) that modify the system DB right?
</blockquote></details>

Yeah ,those have the same problem too

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwNbWcdDDMX0ka_Xp-l:-Nwe_slABxUfchbWQmcL:bcatecu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/sql/catalog/systemschema/system.go#L1212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The bootstrap data has all the KVs on a freshly bootstrapped cluster, it should include this version somewhere no? Otherwise how do we know what version we're reading..
</blockquote></details>

yeah, i would expect that reasoning to hold too. still trying to figure out why `TestInitialValuesToString` is not affected

i also realized that some of the (yet-to-be-seen) churn can be reduced with:
```
		// Run the actual upgrade, if any.
		mig, exists := m.GetUpgrade(clusterVersion)
		if exists {
			if err := m.runMigration(ctx, mig, user, clusterVersion, !m.knobs.DontUseJobs); err != nil {
				return err
			}
		}

		// Bump the version of the system database schema.
		if exists || (clusterVersion.Equal(clusterversion.Latest.Version()) && clusterVersion.IsFinal()) {
			if err := bumpSystemDatabaseSchemaVersion(ctx, cv, m.deps.DB); err != nil {
				return err
			}
		}
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwNbWcdDDMX0ka_Xp-l:-NwedU0d4_s94fncfNy-:b5xday9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/sql/catalog/systemschema/system.go#L1212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yeah, i would expect that reasoning to hold too. still trying to figure out why `TestInitialValuesToString` is not affected

i also realized that some of the (yet-to-be-seen) churn can be reduced with:
```
		// Run the actual upgrade, if any.
		mig, exists := m.GetUpgrade(clusterVersion)
		if exists {
			if err := m.runMigration(ctx, mig, user, clusterVersion, !m.knobs.DontUseJobs); err != nil {
				return err
			}
		}

		// Bump the version of the system database schema.
		if exists || (clusterVersion.Equal(clusterversion.Latest.Version()) && clusterVersion.IsFinal()) {
			if err := bumpSystemDatabaseSchemaVersion(ctx, cv, m.deps.DB); err != nil {
				return err
			}
		}
```
</blockquote></details>

i think there was a PEBKAC earlier; `TestInitialValuesToString` does churn when i try this now.

and i also realized that my `if exists || (clusterVersion.Equal(clusterversion.Latest.Version()) && clusterVersion.IsFinal())` comment is irrelevant to this part of the code, since here we are talking about bootstrapping, not upgrading.

so what do folks think now: should i avoid the churn, and make this PR _only_ include the test proposed in https://github.com/cockroachdb/cockroach/issues/121914 (and avoid modifying `MakeSystemDatabaseDesc()`)?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @fqazi, and @RaduBerinde)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-NwNbWcdDDMX0ka_Xp-l:-Nwfhifg4L1q6QTkBl_e:b2q80n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c32e4a48b199bc06f5d52ef7e047a092dd364a/pkg/sql/catalog/systemschema/system.go#L1212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think there was a PEBKAC earlier; `TestInitialValuesToString` does churn when i try this now.

and i also realized that my `if exists || (clusterVersion.Equal(clusterversion.Latest.Version()) && clusterVersion.IsFinal())` comment is irrelevant to this part of the code, since here we are talking about bootstrapping, not upgrading.

so what do folks think now: should i avoid the churn, and make this PR _only_ include the test proposed in https://github.com/cockroachdb/cockroach/issues/121914 (and avoid modifying `MakeSystemDatabaseDesc()`)?
</blockquote></details>

i gave that option a shot. PTAL at the latest revision.

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123084#-:-NwfitQ7BGYUvMdHz0u8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890, @dt, @RaduBerinde, and @rafiss)

**Review by rafiss — COMMENTED** [review]
bors r+

**Pull request merged**
