### PR TITLE
coldata: optimize copying nulls in a common case

### PR DESCRIPTION
**Pull request by yuzefovich**
Whenever we're copying `coldata.Vec`s, we need to copy the nulls
vectors as well. Often, we would be copying the nulls vectors in such
a manner that the shifts within nulls bitmaps would be the same. Such
observation allows us to optimize the copying behavior (previously, we
would be checking and setting every null value one at a time), but now
we will do a more efficient copy for the largest central part of the
range to copy and handle the "head" and the "tail" of the range
separately. This gives us a nice speedup (e.g. on a quick projection
operator benchmark I see 2x improvement in the throughput).

Release justification: low risk, high benefit change.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Benchmarks ([here](https://gist.github.com/yuzefovich/aa71678a7d1b434f4848e3fb2df4167f) and [here](https://gist.github.com/yuzefovich/99cb0a16631f2fd7a1d69c1d22e1a7fc)):
```
name                                             old speed      new speed       delta
Copy/bytes/CopySimple/NullProbability=0.0-24     25.5GB/s ± 3%   25.3GB/s ± 1%       ~     (p=0.579 n=10+10)
Copy/bytes/CopyWithSel/NullProbability=0.0-24     528MB/s ± 0%    527MB/s ± 0%       ~     (p=0.050 n=9+9)
Copy/bytes/CopySimple/NullProbability=0.2-24     3.01GB/s ± 2%  20.84GB/s ± 1%   +592.85%  (p=0.000 n=10+9)
Copy/bytes/CopyWithSel/NullProbability=0.2-24     448MB/s ± 0%    460MB/s ± 2%     +2.81%  (p=0.000 n=10+10)
Copy/decimal/CopySimple/NullProbability=0.0-24    728MB/s ± 1%    706MB/s ± 2%     -3.07%  (p=0.000 n=10+9)
Copy/decimal/CopyWithSel/NullProbability=0.0-24   456MB/s ± 1%    442MB/s ± 2%     -2.98%  (p=0.000 n=10+10)
Copy/decimal/CopySimple/NullProbability=0.2-24    606MB/s ± 3%    693MB/s ± 3%    +14.43%  (p=0.000 n=9+10)
Copy/decimal/CopyWithSel/NullProbability=0.2-24   470MB/s ± 1%    462MB/s ± 3%     -1.73%  (p=0.043 n=10+10)
Copy/int/CopySimple/NullProbability=0.0-24       60.2GB/s ± 0%   57.2GB/s ± 3%     -5.02%  (p=0.000 n=10+9)
Copy/int/CopyWithSel/NullProbability=0.0-24      4.18GB/s ± 1%   3.92GB/s ± 1%     -6.30%  (p=0.000 n=10+10)
Copy/int/CopySimple/NullProbability=0.2-24       3.43GB/s ± 1%  39.75GB/s ± 0%  +1059.21%  (p=0.000 n=9+9)
Copy/int/CopyWithSel/NullProbability=0.2-24      2.17GB/s ± 1%   2.27GB/s ± 1%     +4.24%  (p=0.000 n=9+9)
```
```
Append/bytes/AppendSimple/NullProbability=0.0-16     40.9GB/s ± 3%   40.4GB/s ± 4%       ~     (p=0.315 n=9+10)
Append/bytes/AppendWithSel/NullProbability=0.0-16     790MB/s ± 2%    784MB/s ± 5%       ~     (p=0.888 n=8+9)
Append/bytes/AppendSimple/NullProbability=0.2-16     3.74GB/s ± 5%  32.80GB/s ± 7%   +777.02%  (p=0.000 n=9+10)
Append/bytes/AppendWithSel/NullProbability=0.2-16     689MB/s ± 1%    655MB/s ± 8%     -4.94%  (p=0.000 n=9+10)
Append/decimal/AppendSimple/NullProbability=0.0-16   1.10GB/s ± 2%   1.12GB/s ± 2%     +2.43%  (p=0.001 n=8+10)
Append/decimal/AppendWithSel/NullProbability=0.0-16   313MB/s ± 8%    331MB/s ± 4%     +5.71%  (p=0.003 n=10+10)
Append/decimal/AppendSimple/NullProbability=0.2-16    846MB/s ± 6%   1098MB/s ± 4%    +29.81%  (p=0.000 n=10+10)
Append/decimal/AppendWithSel/NullProbability=0.2-16   316MB/s ± 2%    312MB/s ± 1%     -1.18%  (p=0.016 n=10+10)
Append/int/AppendSimple/NullProbability=0.0-16       68.8GB/s ± 5%   73.1GB/s ± 4%     +6.34%  (p=0.001 n=10+10)
Append/int/AppendWithSel/NullProbability=0.0-16      7.88GB/s ± 2%   8.10GB/s ± 3%     +2.82%  (p=0.000 n=10+9)
Append/int/AppendSimple/NullProbability=0.2-16       3.80GB/s ±10%  48.45GB/s ± 6%  +1176.70%  (p=0.000 n=10+10)
Append/int/AppendWithSel/NullProbability=0.2-16      3.17GB/s ± 4%   2.60GB/s ± 1%    -17.86%  (p=0.000 n=10+7)
```
Note that I ran `BenchmarkAppend` on my laptop with the following modification:
```
diff --git a/pkg/col/coldata/vec_test.go b/pkg/col/coldata/vec_test.go
index 42a1d5a9dc..204a17ec22 100644
--- a/pkg/col/coldata/vec_test.go
+++ b/pkg/col/coldata/vec_test.go
@@ -438,7 +438,9 @@ func BenchmarkAppend(b *testing.B) {
                                        bc.args.DestIdx = 0
                                        for i := 0; i < b.N; i++ {
                                                dest.Append(bc.args)
-                                               bc.args.DestIdx += coldata.BatchSize()
+                                               if typ.Identical(types.Bytes) {
+                                                       dest.Bytes().Reset()
+                                               }
                                        }
                                })
                        }
```
(for some reason when running with `./scripts/bench` it was crashing - seemed like we were overflowing `int32` offset in case of `coldata.Bytes`).

**Comment by yuzefovich** [comment]
This also shows a nice improvement in micro-benchmarks of the operators [here](https://gist.github.com/yuzefovich/695781234607454824814ddd1b953259).

**Review by asubiotto — COMMENTED** [review]
This is a nice speedup but I'm again not convinced this should go in during stability period. Let's discuss further during standup.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53585#-:-MG39k3IB_UExRQPx1Zi:bq3a18p)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Discussed it during the standup, and we all agreed that it can go in now. I'll wait for LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53585#-:-MG4MYud9hZ_w5APPOsg:b-3ekord)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53585#-:-MG4NFtm89DQGlOMLwu0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
