### PR TITLE
sql, jobs: ban running un-migrated 19.2-style schema change jobs

### PR DESCRIPTION
**Pull request by thoszhang**
When upgrading from 19.2 to 20.1, we need to ban 19.2-style schema
change jobs from being run or updated on 20.1 nodes, because we need to
avoid having 20.1 nodes interfere with the job state for schema changes
running on any remaining 19.2 nodes, and because the 20.1 schema change
job resumer doesn't know how to resume 19.2-style schema change jobs.

This PR introduces a `FormatVersion` field to the schema change job
details and populates it with a higher version for all 20.1-style schema
change job records. Schema change jobs with a lower version are banned
from being adopted, canceled, or paused.

A future change will introduce the migration on 19.2-style jobs that
will allow them to be run in 20.1 after the upgrade finalization.

Addresses part 1 of #46152.

Release justification: This is a necessary part of the schema change
updates for beta 3.
Release note (sql change): As part of ensuring consistency for schema
changes throughout the upgrade process to 20.1, schema changes initiated
in 19.2 now cannot be adopted, paused, or resumed from 20.1 nodes until
an internal migration is run.

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, @pbardea, and @spaskob)

___
*[pkg/jobs/jobs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2i3VbkBJ-9xsrP-5pi:-M2i3VbkBJ-9xsrP-5pj:b-v78wpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L398)):*
> ```Go
> 		// which should be supported in theory. But disallowing cancellation means
> 		// there's one fewer scenario we have to think about.
> 		if schemaChangeDetails, ok := md.Payload.UnwrapDetails().(jobspb.SchemaChangeDetails); ok &&
> ```

I was considering if there was a way to move this bit over to the job so that there isn't schema changer logic inside the general jobs handling code. I'm not yet convinced one way or another about that idea though.

I think that it may be useful to move the schema changer logic to a single helper method though (something like `shouldDisable` or `canRun`).
___
*[pkg/jobs/jobs.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2i1zWw1AYiJgTd1HWu:-M2i1zWw1AYiJgTd1HWv:bjrjwsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L446)):*
> ```Go
> 			return errors.Newf(
> 				"schema change job was created in earlier version, and cannot be " +
> 					"paused in this version until an internal migration is complete")
> ```

Should this error message also say that the internal migration cannot complete until the cluster upgrade is finalized.

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @spaskob)

___
*[pkg/jobs/jobs.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2hkIfA-QWh7uhI_XKx:-M2hkIfA-QWh7uhI_XKy:b-cl06wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L393)):*
> ```Go
> 		// before they undergo a migration to make them properly runnable in 20.1 and
> 		// later versions.
> 		// TODO (lucy): Is this actually necessary? If we allow jobs to be canceled
> ```

IMO this case is fine from point of view of jobs, leaving it up to you decide if we want to keep it. I agree it's one less thing to worry about; on the flip side when cancelling a schema change may be useful during migration?
___
*[pkg/jobs/jobs.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2hkfSW5hpqb2ciCp_b:-M2hkfSW5hpqb2ciCp_c:b-z3d0uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L442)):*
> ```Go
> 		// forcing 19.2 nodes to deal with a schema change job in a state that wasn't
> 		// possible in 19.2.
> 		if schemaChangeDetails, ok := md.Payload.UnwrapDetails().(jobspb.SchemaChangeDetails); ok &&
> ```

nit: share the code with the above snippet in function? The boolean condition is used also in `registry.go`.

**Review by ajwerner — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-:-M2iCLlhBOimfKbGRqvv:b593w57)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @spaskob)

___
*[pkg/jobs/jobs_test.go, line 2180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2hkQqyAEQqDUb91C2q:-M2hkQqyAEQqDUb91C2r:b-1ih02b) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs_test.go#L2180)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer jobs.ResetConstructors()()
> 	defer func(oldInterval time.Duration) {
> ```

nit: helper for this
___
*[pkg/jobs/registry.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2e8xeUEDJ-K50T5IMr:-M2e8xeUEDJ-K50T5IMs:bbjppdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/722c97428def4210a2fb6a9e771c0273ea69fd03/pkg/jobs/registry.go#L1018)):*
> ```Go
> 
> 		// In version 20.1, the registry must not adopt 19.2-style schema change
> 		// jobs until they've undergone a migration.
> ```

Shall we add a `TODO` to remove this in 20.2? 
___
*[pkg/jobs/jobspb/jobs.proto, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2e2ule3JtYiifMX2Bi:-M2e2ulf3LC6mwCONRio:bgy3ldx) ([raw file](https://github.com/cockroachdb/cockroach/blob/722c97428def4210a2fb6a9e771c0273ea69fd03/pkg/jobs/jobspb/jobs.proto#L240)):*
> ```protobuf
>   uint32 table_id = 5 [(gogoproto.customname) = "TableID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sqlbase.ID"];
>   uint32 mutation_id = 6 [(gogoproto.customname) = "MutationID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sqlbase.MutationID"];
>   uint32 format_version = 7 [(gogoproto.casttype) = "SchemaChangeDetailsFormatVersion"];
> ```

nit: comment explaining this? I know other fields don't have it but it can't hurt.

**Review by pbardea — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-:-M2iEeVZ9Ufi_G2hD92w:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46214)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @pbardea, and @spaskob)

___
*[pkg/jobs/jobs.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2hkIfA-QWh7uhI_XKx:-M2iUB3w6gQi1oUdAiG0:bun1xcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L393)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

IMO this case is fine from point of view of jobs, leaving it up to you decide if we want to keep it. I agree it's one less thing to worry about; on the flip side when cancelling a schema change may be useful during migration?
</blockquote></details>

Yeah, ultimately I'm not convinced there's an advantage to being able to cancel a job that's hanging around and not adoptable (with the result that after it becomes adoptable, we start running `OnFailOrCancel`), so I'll just take this approach. I'm removing this TODO and adding a comment about it.
___
*[pkg/jobs/jobs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2i3VbkBJ-9xsrP-5pi:-M2i_KVUE8NTD8LDihn7:b-td9aw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L398)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I was considering if there was a way to move this bit over to the job so that there isn't schema changer logic inside the general jobs handling code. I'm not yet convinced one way or another about that idea though.

I think that it may be useful to move the schema changer logic to a single helper method though (something like `shouldDisable` or `canRun`).
</blockquote></details>

I think the problem with putting the logic in the job resumer is that we can't prevent state changes (e.g., cancellation) from happening in the first place. (The most we could do is just keep returning retry errors or sleeping or something _after_ we've already adopted this job that isn't supposed to be run, which is not ideal.) I did move the format version gate logic out into a separate function.
___
*[pkg/jobs/jobs.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2hkfSW5hpqb2ciCp_b:-M2i_JlvBMYiisKc_SFn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L442)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

nit: share the code with the above snippet in function? The boolean condition is used also in `registry.go`.
</blockquote></details>

Done.
___
*[pkg/jobs/jobs.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2i1zWw1AYiJgTd1HWu:-M2iUsZ8-8bHAaot6QAu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs.go#L446)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Should this error message also say that the internal migration cannot complete until the cluster upgrade is finalized.
</blockquote></details>

Done.
___
*[pkg/jobs/jobs_test.go, line 2180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2hkQqyAEQqDUb91C2q:-M2iVPEF7Ru_UDHGHacA:b-44oyb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/43c7523d06c0fd8aa900f25eca4a1f0377ea85ee/pkg/jobs/jobs_test.go#L2180)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: helper for this
</blockquote></details>

I'm going to leave that for a later change, because we don't have a pre-existing helper in this package AFAIK, and the job tests are doing all sorts of things with the adopt interval so I'm reluctant to add one right now.
___
*[pkg/jobs/registry.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2e8xeUEDJ-K50T5IMr:-M2iWX8817OTOIVP_1Ti:b-pnkj6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/722c97428def4210a2fb6a9e771c0273ea69fd03/pkg/jobs/registry.go#L1018)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Shall we add a `TODO` to remove this in 20.2? 
</blockquote></details>

Done (here and elsewhere).
___
*[pkg/jobs/jobspb/jobs.proto, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46214#-M2e2ule3JtYiifMX2Bi:-M2iYPCE7uEWKR7JyjY6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/722c97428def4210a2fb6a9e771c0273ea69fd03/pkg/jobs/jobspb/jobs.proto#L240)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: comment explaining this? I know other fields don't have it but it can't hurt.
</blockquote></details>

Done.

**Comment by lucy-zhang** [comment]
TFTRs

bors r+

**Comment by danhhz** [comment]
Subscribe

**Pull request merged**
