### PR TITLE
 backupccl: support 'execution locality' option in scheduled backups

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: CRDB-9547.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
LGTM.

During review I noted that we technically aren't type-checking `SET WITH` options in ALTER.  You will get an error from the "dry run" backup, so you'll get an error eventually. Just not as early as we may like and not from PREPARE.  I'll file this separately.

**Comment by stevendanna** [comment]
If you fancied, we have some data drive tests in `pkg/ccl/backupccl/testdata/backup-restore/alter-schedule/backup-options`

**Comment by dt** [comment]
> If you fancied, we have some data drive tests in pkg/ccl/backupccl/testdata/backup-restore/alter-schedule/backup-options

Added.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
