### PR TITLE
opt: add single col constraints and add constants to fds

### PR DESCRIPTION
**Pull request by justinj**
These are grouped together because adding the constants makes testing the second commit much simpler.

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 35 of 35 files at r1, 3 of 3 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-LFt1G4Q4ADwppRHI6Z4:-LFt1G4Q4ADwppRHI6Z5:b87eovx) ([raw file](https://github.com/cockroachdb/cockroach/blob/24076cc3f93550c80284a031aadc3c50fea2091a/pkg/sql/opt/memo/logical_props_builder.go#L190)):*
> ```Go
> 	relational.FuncDeps.ProjectCols(relational.OutputCols)
> 	if filterProps.Constraints != nil {
> 		relational.FuncDeps.AddConstants(filterProps.Constraints.ExtractConstCols(b.evalCtx))
> ```

This will be redundant with the change in #26937 - just FYI for whichever one of us merges second and needs to rebase.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFwRzJHB7wkuPmu1QTs:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-LFwUgoN2rSCSvEGVuoH:-LFwUgoN2rSCSvEGVuoI:b-z05p5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/24076cc3f93550c80284a031aadc3c50fea2091a/pkg/sql/opt/memo/testdata/logprops/constraints#L681)):*
> ```
>  ├── cost: 0.00216326531
>  ├── key: (1)
>  ├── fd: ()-->(2,3), (1)-->(2,3)
> ```

`()-->(2,3)` looks wrong (`u` is not constant). Maybe a  problem with ExtractConstCols?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962)*

**Comment by justinj** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-LFt1G4Q4ADwppRHI6Z4:-LFwW0tW-PHT4NVZTqDW:b5kvtm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/24076cc3f93550c80284a031aadc3c50fea2091a/pkg/sql/opt/memo/logical_props_builder.go#L190)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This will be redundant with the change in #26937 - just FYI for whichever one of us merges second and needs to rebase.
</blockquote></details>

Thanks for the heads up - also #26975 perhaps

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-LFwUgoN2rSCSvEGVuoH:-LFwVu0wCF6zJwxCpux_:b-wwxu3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/24076cc3f93550c80284a031aadc3c50fea2091a/pkg/sql/opt/memo/testdata/logprops/constraints#L681)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`()-->(2,3)` looks wrong (`u` is not constant). Maybe a  problem with ExtractConstCols?
</blockquote></details>

It was a problem with the `TupleIn` constraint builder, it's fixed in the second commit of this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-LFwUgoN2rSCSvEGVuoH:-LFwZHsp32lj75WNrlsC:bu58byq) ([raw file](https://github.com/cockroachdb/cockroach/blob/24076cc3f93550c80284a031aadc3c50fea2091a/pkg/sql/opt/memo/testdata/logprops/constraints#L681)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

It was a problem with the `TupleIn` constraint builder, it's fixed in the second commit of this PR.
</blockquote></details>

Ah, cool, I missed that note in the commit msg.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFwZYrO9E5k3Ofjee9r:bnfp4nl)*

**Comment by andy-kimball** [comment]
Doesn't this change mean we'd have *both* the multi-column constraint as well as the single-column constraints?

---

Review status: :shipit: complete! 2 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFwbG4TD09u5BgZHnVC:bg0fzo7)*

**Comment by justinj** [comment]
Yes, but the ConstraintSet code should do the intersection intelligently, and this means we have both tight constraints and easy-to-decipher constant columns.

---

Review status: :shipit: complete! 2 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFwc7Dm3io0ofnw3xjB:b3atdfz)*

**Comment by andy-kimball** [comment]
Could you now update `Set.ExtractConstCols` to skip over multi-column constraints?

Also, I assume that existing code had bug in case where there were multiple constraints with different values for same column:

`/a/b: [/1/3 - /1/3]`
`/a/c: [/2/4 - /2/4]`

I'd add test case(s) for that case, to make sure we now handle it properly.

---

Review status: :shipit: complete! 2 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFx0WqC4zEHKrZQDpnA:bfi1ut1)*

**Comment by justinj** [comment]
I think we should still look at multi-column constraints, perhaps @RaduBerinde can confirm if this is the intended behaviour, but my thoughts were that `ConstraintSet`'s `Intersect` method should handle adding `/3: ...` to an existing `/3/2: ...` constraint, and so we might have constant columns only implied by a multi-column constraint regardless.

---

Review status: :shipit: complete! 2 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFx2stpC7cqyszob8yH:b-bk2uz0)*

**Comment by RaduBerinde** [comment]
I don't think the constraint intersection currently does that, it will keep both `/3` and `/3/2` as separate constraints.
Also, I think we have other cases where we have just a multi-column constraint (eg tuple inequality).

BTW we should have a testcase that shows the constraints we generate for IN (perhaps on a table with no indexes, so they're not hidden by a constrained scan).

---

Review status: :shipit: complete! 2 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFx4_zh666IA_uO5s0J:b-2u2gpw)*

**Comment by andy-kimball** [comment]
I guess what bothers me here is that we're not normalizing in the `constraint` code, but are instead adding a bunch of redundant constraints in the builder code and then expecting `constraint.Set` to deal with them. It seems inelegant and inefficient. I'd much prefer to be normalizing in `constraint.Set` according to whatever rules we decide upon. If we want to maintain redundant constraints (and there are good reasons to do so), then we should enforce that in `constraint.Set`. That way, every caller that uses `Intersect`/`Union` will get the right behavior, rather than being expected to add the right constraint combos themselves. I could imagine rules like:

1. Multi-column constraints will always have exact prefixes factored out (according to `ExactPrefix` method):
```
/y/m/d: [/2018/10/2 - /2018/11/2]
=>
/y: [/2018 - /2018]
/m/d: [/10/2 - /11/2]

/y/m/d: [/2018/10/2 - /2018/10/5] [/2018/10/15 - /2018/10/20]
=>
/y: [/2018 - /2018]
/m: [/10 - /10]
/d: [/2 - /5] [/15 - /20]

```
2. Every column appearing in a multi-column constraint will also have a single-column constraint, assuming its single-col version is not unconstrained:
```
/y/m/d: [/2018/10/2 - /2018/11/2]
=>
/y: [/2018 - /2018]
/m/d: [/10/2 - /11/2]
/m: [/10 - /11]

/y/m/d: [/2018/10/2 - /2018/10/5] [/2020/10/12 - /2020/10/15]
=>
/y/m/d: [/2018/10/2 - /2018/10/5] [/2020/10/12 - /2020/10/15]
/y: [/2018 - /2018] [/2020 - /2020]
/m: [/10 - /10]
/d: [/2 - /5] [/12 - /15]
```

I think we should go ahead with this PR, but I wanted to record my reservations, in the hopes that we can tighten this up in the future.

---

Review status: :shipit: complete! 2 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LFx6LWj8j1cMzFhu6l_:bw0nv1s)*

**Comment by justinj** [comment]
Yeah, put that way I agree that this approach is spreading out the knowledge of how constraints are stored/used too wide. I have reservations about both of the proposals though:

Proposal 1 won't won't catch cases like
```
/1/2: [/10/50 - /10/50] [/20/50 - /20/50]
```
since there's no exact prefix, but we would like to be able to infer that 2 is constant.

Proposal 2 would catch this, but it seems to me that it would be inflating the size of the constraints in a lot of cases where there isn't much benefit, given that we only really care about getting the extra columns when it allows us to infer constant columns (which I guess the current approach is doing too). Maybe this is ok, since in the especially common case of one single-column constraint we'd still only have a single constraint, but I wonder if there's a way that we can avoid this.

Maybe there isn't much lost by sacrificing the tight constraints here, especially given that (I think) the index constraint code will still be able to get a tight scan? I feel like this still has the same concern of the builder code having to understand how those constraints are used later, though.

All in all I think I will merge this for the time being so we can get these TPCC queries working properly, and we can think about/discuss how we'd like to move forward with it.

**Comment by RaduBerinde** [comment]
The two rules were not separate proposals, they would be used together. They seem pretty nice to me; yeah we are adding more constraints but we can use them more efficiently (instead of trying to "harvest" what we need from more complicated constraints). At the very least they are a great starting point for the discussion, maybe we should open an issue to record this discussion.

**Comment by justinj** [comment]
Removed the first commit since it's redundant with #26975, and made some small changes, would you mind taking another quick look @RaduBerinde?

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/memo/constraint_builder.go, line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-LG18X4QBWrpLXvbPVRQ:-LG18X4QBWrpLXvbPVRR:biugolw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d21347e57fefa0c10ae1df394f984caf2d62dbd/pkg/sql/opt/memo/constraint_builder.go#L259)):*
> ```Go
> 
> 		key := constraint.MakeCompositeKey(vals...)
> 		var sp constraint.Span
> ```

[nit] we usually put the declaration outside the loop just in case it escapes (it shouldn't in this case but who knows). Probably fine to leave it here, just an FYI

---

*[pkg/sql/opt/memo/constraint_builder.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-LG18lVKExyJ1NqYpcWU:-LG18lVKExyJ1NqYpcWV:b-vh82sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d21347e57fefa0c10ae1df394f984caf2d62dbd/pkg/sql/opt/memo/constraint_builder.go#L277)):*
> ```Go
> 		// multi-column constraint we added above.
> 		if i == 0 {
> 			continue
> ```

[nit] `for i := 1; i < len(colIdxsInLHS); i++`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26962#-:-LG19iw3AH8eykt243Ys:bnfp4nl)*

**Comment by justinj** [comment]
TFTRs!

bors r+

**Comment by justinj** [comment]
ci passed but bors failed, going to try again

bors r+

**Pull request merged**
