### PR TITLE
kv/kvserver: Remove buffering from SSTSnapshotStorageFile

### PR DESCRIPTION
**Pull request by itsbilal**
When investigating a durability violation around ingested sstables
that disappeared after a power outage, we realized that
SSTSnapshotStorageFile does not flush its buffer before doing
a Sync(). When used with a pebble SSTWriter, we expect Sync()
to ensure all bytes written to that file are synced to disk,
which is not what was happening here for the last couple bytes
written to the buffer.

This change removes buffering from SSTSnapshotStorageFile
as pebble's SST writer already does its own buffering. This
makes Sync() do what it is expected to do.

Release note (bug fix): Fix a bug where a badly timed power outage
or system crash could result in an error upon process restart.

### CODE REVIEW

**Comment by itsbilal** [comment]
Tagged @nvanbenschoten for review as this is KV owned code, but really anyone from KV can review this as well.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5O4U-DUs9efktRYCZ:-MB5O4U-DUs9efktRYC_:b-tl3vwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L206)):*
> ```Go
> 		return nil
> 	}
> 	if len(f.buffer) > 0 {
> ```

This could be a call to `f.Flush()`.
___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5O-uXAxY_YP24cDew:-MB5O-uXAxY_YP24cDex:br1mrln) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L223)):*
> ```Go
> // buffer is empty. Implements flusher for pebble's SSTWriter.
> func (f *SSTSnapshotStorageFile) Flush() error {
> 	if err := f.openFile(); err != nil {
> ```

Technically not needed because `len(f.buffer) == 0` if the file has not been opened.
___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5MI3Q5BgkfEleOeb1:b-rlu0xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
> ```Go
> 		return err
> 	}
> 	if len(f.buffer) > 0 {
> ```

Do we need the buffer at all? `sstable.NewWriter` wraps the file it is passed in a `bufio.Writer`. And the other user of `SSTSnapshotStorageFile` writes files in their entirety.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5OHrW0YNm4WDYDDSW:bxjrtzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do we need the buffer at all? `sstable.NewWriter` wraps the file it is passed in a `bufio.Writer`. And the other user of `SSTSnapshotStorageFile` writes files in their entirety.
</blockquote></details>

I was wondering the same thing. It looks like we use this for fine-grained control over size of chunks that are synced (hooked up to `kv.snapshot_sst.sync_size`). The whole thing seems convoluted to me, though. I'd much rather use the `bufio.Writer` in `sstable.Writer` and trying to remove `f.buffer` entirely.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5PNm85mLd0Z6JvRHh:b-i741q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was wondering the same thing. It looks like we use this for fine-grained control over size of chunks that are synced (hooked up to `kv.snapshot_sst.sync_size`). The whole thing seems convoluted to me, though. I'd much rather use the `bufio.Writer` in `sstable.Writer` and trying to remove `f.buffer` entirely.
</blockquote></details>

`sstable.Writer` only makes a `bufio.Writer` if the passed in file doesn't have a `Flush()` method. This file has it now, so it effectively gives us control into the buffering semantics from here (and that cluster setting). I'm fine with getting rid of it entirely if you all think that's more preferable, but this is at least better than the status quo where we double-buffer.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5O4U-DUs9efktRYCZ:-MB5QJvH0KgRz9Cxrovt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L206)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This could be a call to `f.Flush()`.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5O-uXAxY_YP24cDew:-MB5QKDbBzLF8xr0tGUn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L223)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Technically not needed because `len(f.buffer) == 0` if the file has not been opened.
</blockquote></details>

Done.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5PjEh0W2SQ_JE09MJ:b-bnv6dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

`sstable.Writer` only makes a `bufio.Writer` if the passed in file doesn't have a `Flush()` method. This file has it now, so it effectively gives us control into the buffering semantics from here (and that cluster setting). I'm fine with getting rid of it entirely if you all think that's more preferable, but this is at least better than the status quo where we double-buffer.
</blockquote></details>

Agreed that it's better than the status quo. I think this code got itself in trouble by trying to couple writing to a file and syncing that file. We should be able to preserve `kv.snapshot_sst.sync_size` while removing the `f.buffer` once we break that coupling.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5QfZf0ENtHibB5DU4:b2q5j4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Agreed that it's better than the status quo. I think this code got itself in trouble by trying to couple writing to a file and syncing that file. We should be able to preserve `kv.snapshot_sst.sync_size` while removing the `f.buffer` once we break that coupling.
</blockquote></details>

@itsbilal I can do that if you don't want to. Although it might be easier just to keep the changes all in this PR because it shouldn't be a lot.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5QYAw9LvjLfpRkUPS:bz2fw86) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@itsbilal I can do that if you don't want to. Although it might be easier just to keep the changes all in this PR because it shouldn't be a lot.
</blockquote></details>

I think it is fine to just use the `sstable.Writer's``bufio.Writer`. Also, we should really be using `CreateWithSync` rather than having this bespoke syncing code. Unfortunately, `CreateWithSync` doesn't look like it does the write thing on RocksDB.

@nvanbenschoten I think the default value for `"kv.snapshot_sst.sync_size"` is too high. In my testing, `512 KB` is a better value. A sync every `2 MB` introduces writes that cause latency spikes for other concurrent operations.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5YS6p0BQdZCuyYnA4:bphe5cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think it is fine to just use the `sstable.Writer's``bufio.Writer`. Also, we should really be using `CreateWithSync` rather than having this bespoke syncing code. Unfortunately, `CreateWithSync` doesn't look like it does the write thing on RocksDB.

@nvanbenschoten I think the default value for `"kv.snapshot_sst.sync_size"` is too high. In my testing, `512 KB` is a better value. A sync every `2 MB` introduces writes that cause latency spikes for other concurrent operations.
</blockquote></details>

@nvanbenschoten I'm a bit unclear on the solution you're thinking of, where you'd do the uncoupling while also preserving that setting. Are you thinking of just keeping counts of bytes written, getting rid of the buffer, and calling `Sync` after x bytes where x = that setting? If so, yes I can implement that here no problem. Should be a pretty non-invasive change, which would help when we backport this.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5f5ae-UuEUQsfWjF-:b-psn2nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
> CreateWithSync doesn't look like it does the write thing on RocksDB.

Typo or pun :thinking: 

> @nvanbenschoten I think the default value for "kv.snapshot_sst.sync_size" is too high. In my testing, 512 KB is a better value. A sync every 2 MB introduces writes that cause latency spikes for other concurrent operations.

This was copied over from `kv.bulk_sst.sync_size`. Should we change that as well?

> Are you thinking of just keeping counts of bytes written, getting rid of the buffer, and calling Sync after x bytes where x = that setting?

Yes, that's exactly what I was thinking. Thanks for taking it!

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5gl2x0srzbGQ-WWnD:b-852odn) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
> Typo or pun 🤔

Typo, but I wish I had been that clever.

> This was copied over from kv.bulk_sst.sync_size. Should we change that as well?

Yes. Probably shouldn't backport such changes to 20.1, though. So let's do them in a separate PR.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5ihNq1WXQqQ_0W5Ni:b-xvk57j) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
> So let's do them in a separate PR.

Agreed. We can track that in https://github.com/cockroachdb/cockroach/pull/50838.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5MI3Q5BgkfEleOeb0:-MB5oFhcAM14YQHeOwKk:b-8hbhjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70494ffe84eb66ea1bef9de00a0f1e01da2bb195/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> So let's do them in a separate PR.

Agreed. We can track that in https://github.com/cockroachdb/cockroach/pull/50838.
</blockquote></details>

I've made the syncing change and the buffer removal - PTAL!

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-:-MB5thStEHFIgnK9g9JE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5td9b-ijgS6o5bQQN:-MB5td9b-ijgS6o5bQQO:bblamun) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f8a57295b9df8aa603140b21771d39003030bd/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L119)):*
> ```Go
> 		return err
> 	}
> 	if err := f.Sync(); err != nil {
> ```

Is this needed? Doesn't `Close` already imply a `Sync`?

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5td9b-ijgS6o5bQQN:-MB5vCvPCHBaGzVP90ml:b4t7k2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f8a57295b9df8aa603140b21771d39003030bd/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this needed? Doesn't `Close` already imply a `Sync`?
</blockquote></details>

It doesn't - which is partly why this bug crept in to begin with. We were doing a `Write` and then a `Close` as part of `SSTSnapshotStorageFile.Close`, without a sync in between.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-:-MB5xF6k8-Ea0epYjkQB:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5wbCxDpAmJbBdLZfF:-MB5wbCxDpAmJbBdLZfG:b-mainih) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f8a57295b9df8aa603140b21771d39003030bd/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L183)):*
> ```Go
> 	}
> 	var err error
> 	if f.syncSize > 0 {
> ```

Can you file a bug to push this logic down into `rocksdbWritableFile`? We should really be using `storage/FS.CreateWithSync` (which uses the `sync_file_range` system call on Pebble).

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5td9b-ijgS6o5bQQN:-MB5xkIWB9IECrH_sC3m:b-esitca) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f8a57295b9df8aa603140b21771d39003030bd/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L119)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It doesn't - which is partly why this bug crept in to begin with. We were doing a `Write` and then a `Close` as part of `SSTSnapshotStorageFile.Close`, without a sync in between.
</blockquote></details>

Ah, I see. I keep getting confused with who calls who in this `sstable.Writer` + `SSTSnapshotStorageFile` contraption. In this case, there is no `sstable.Writer`.

**Review by itsbilal — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-:-MB60wcB4OoVn6jldxyP:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5wbCxDpAmJbBdLZfF:-MB611k_2T0qWUVrJUwJ:b-dy79vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f8a57295b9df8aa603140b21771d39003030bd/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L183)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you file a bug to push this logic down into `rocksdbWritableFile`? We should really be using `storage/FS.CreateWithSync` (which uses the `sync_file_range` system call on Pebble).
</blockquote></details>

Done: #50844 . Wondering what else would be important to mention there.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50831)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/kv/kvserver/replica_sst_snapshot_storage.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50831#-MB5wbCxDpAmJbBdLZfF:-MB6Dw_v8H1MR1ggYEDu:b-tm1dvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f8a57295b9df8aa603140b21771d39003030bd/pkg/kv/kvserver/replica_sst_snapshot_storage.go#L183)):*
> Wondering what else would be important to mention there.

LGTM

**Pull request merged**
