### PR TITLE
acceptance: Added acceptance test for npgsql

### PR DESCRIPTION
**Pull request by BramGruneir**
This test is a mimic of the java test and it requires an update to the postgres-test docker image. See https://github.com/cockroachdb/postgres-test/pull/24.

~~DO~~ ~~NOT~~ ~~MERGE~~ until after https://github.com/cockroachdb/postgres-test/pull/24 has been merged and the docker images has been tagged and updated.

### CODE REVIEW

**Comment by BramGruneir** [comment]
This should be all good to merge now.

**Comment by couchand** [comment]
:lgtm: I breezed through the C#, didn't really look at the Go, didn't try executing it.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/csharp_test.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19181#-KwC87316PAHBlVgauTt:-KwC87316PAHBlVgauTu:bfeyzfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c99c6dd7830f9b92d78f6f8f21cfc5d4906fdb9/pkg/acceptance/csharp_test.go#L145)):*
> ```Go
>         {
>             // Call the simple method to create the required database and table and insert some data.
>             Simple(connString);
> ```

This always happens twice (after line 67), is one of them in error?

---

*[pkg/acceptance/csharp_test.go, line 207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19181#-KwC8nWOqvQ0qpILZVIL:-KwC8nWOqvQ0qpILZVIM:b-xtjl3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c99c6dd7830f9b92d78f6f8f21cfc5d4906fdb9/pkg/acceptance/csharp_test.go#L207)):*
> ```Go
>                     if (rows != -1)
>                     {
>                         throw new DataException(String.Format("DROP DATABASE reports {0} rows changed, expecting -1", rows));
> ```

Many of these errors are `s/reports/test/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19181#-:-KwCAX_rQppJKjYV8Cb3:b-o02slt)*

**Comment by BramGruneir** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/csharp_test.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19181#-KwC87316PAHBlVgauTt:-KwCDwcO1K3A_5X3FbjW:bqrmnzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c99c6dd7830f9b92d78f6f8f21cfc5d4906fdb9/pkg/acceptance/csharp_test.go#L145)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

This always happens twice (after line 67), is one of them in error?
</blockquote></details>

No need for it, removed.

---

*[pkg/acceptance/csharp_test.go, line 207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19181#-KwC8nWOqvQ0qpILZVIL:-KwCEBrkg8Ijb2tHB3RW:bwrqdhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c99c6dd7830f9b92d78f6f8f21cfc5d4906fdb9/pkg/acceptance/csharp_test.go#L207)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Many of these errors are `s/reports/test/`
</blockquote></details>

This seems correct to me.  The return value is a report on the number of changed rows.  And this matches the Java test.  I'm going to leave it unchanged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19181)*

**Comment by BramGruneir** [comment]
TFTR!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19181#-:-KwCEpsnq9zGBEDrI4uE:b-814g8k)*

**Pull request merged**
