### PR TITLE
txn: make SetSystemConfigTrigger less surprising

### PR DESCRIPTION
**Pull request by vivekmenezes**
return an error from SetSystemConfigTrigger when it
notices that it is being set on a transaction that has
already written.

@bdarnell you already reviewed this change as part of #14368

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14446)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/internal/client/txn.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14446#-KgQ1FACW8jQm6evvthr:-KgQ1FACW8jQm6evvths:b-oz47yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0510155fc01190dcd209f5e44339fe4a678d0c1c/pkg/internal/client/txn.go#L203)):*
> ```Go
> 	txn.mu.Lock()
> 	if txn.mu.Proto.Writing || txn.mu.writingTxnRecord {
> 		txn.mu.Unlock()
> ```

looks like a classic use case for a `defer`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14446)*

**Comment by vivekmenezes** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/internal/client/txn.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14446#-KgQ1FACW8jQm6evvthr:-KgQ3ypAvlkr6lgd7ivc:b-4st41b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0510155fc01190dcd209f5e44339fe4a678d0c1c/pkg/internal/client/txn.go#L203)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like a classic use case for a `defer`?
</blockquote></details>

Yeah, no performance constraints here. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14446)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14446)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14446#-:-KgQBW6rPyplbIROMQEo:bnfp4nl)*

**Pull request merged**
