### PR TITLE
sql: support SHOW SUPER REGIONS FROM DATABASE

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change): Add support for SHOW SUPER REGIONS FROM DATABASE.
Example:

SHOW SUPER REGIONS FROM DATABASE mr2
----
mr2  ca-central-sr  {ca-central-1}
mr2  test           {ap-southeast-2,us-east-1}

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78985)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @RichardJCai)

___
*[pkg/sql/crdb_internal.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78985#-MzMf45BDBwh-TdmuT6Q:-MzMf45BDBwh-TdmuT6R:bq8q35f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f546d6f486f0148fe4a580a1ba65a1c3a56e42b/pkg/sql/crdb_internal.go#L363)):*
> ```Go
> 					return err
> 				}
> 				typeDesc, err := p.Descriptors().GetMutableTypeVersionByID(ctx, p.txn, typeID)
> ```

Would an immutable do here? I forget what our philosophy around these internal tables is -- would you mind confirming we do indeed want a transactional view of the descriptor instead of a leased one?
___
*[pkg/sql/crdb_internal.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78985#-MzMgF4G0OSPn3_xN42g:-MzMgF4G0OSPn3_xN42h:b-vlylyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f546d6f486f0148fe4a580a1ba65a1c3a56e42b/pkg/sql/crdb_internal.go#L375)):*
> ```Go
> 
> 					if err := addRow(
> 						tree.NewDInt(tree.DInt(db.GetID())),          // id
> ```

Do we need this? Shouldn't the database name be unique by itself?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78985)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/sql/crdb_internal.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78985#-MzMf45BDBwh-TdmuT6Q:-MzS1BK-19UB2Bh_NH8w:bt7zoc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f546d6f486f0148fe4a580a1ba65a1c3a56e42b/pkg/sql/crdb_internal.go#L363)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Would an immutable do here? I forget what our philosophy around these internal tables is -- would you mind confirming we do indeed want a transactional view of the descriptor instead of a leased one?
</blockquote></details>

Done, yeah immutable is better.
___
*[pkg/sql/crdb_internal.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78985#-MzMgF4G0OSPn3_xN42g:-MzS1CzPEIrtREx6ZTc6:b88mblh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f546d6f486f0148fe4a580a1ba65a1c3a56e42b/pkg/sql/crdb_internal.go#L375)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need this? Shouldn't the database name be unique by itself?
</blockquote></details>

It is but it can't hurt to include. `crdb_internal.databases` has it as well.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

Looks fine, I think there's a few more test cases that need updating. Lemme know if they end up being anything more than the usual "adding a new crdb_internal table so there's churn" and I can have another look. Otherwise, feel free to merge on green.

> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78985#-:-MzW7ORs5eOryy1gRIK-:b-y1rrtm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @RichardJCai)

___
*[pkg/sql/crdb_internal.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78985#-MzMgF4G0OSPn3_xN42g:-MzW6aCa059O3_Ij7eEc:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f546d6f486f0148fe4a580a1ba65a1c3a56e42b/pkg/sql/crdb_internal.go#L375)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

It is but it can't hurt to include. `crdb_internal.databases` has it as well.
</blockquote></details>

Ack.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 3017 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78985#-MzW78yl3BKz89057QUc:-MzW78yl3BKz89057QUd:bf9ijx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/746bca9252a8a1e07e4a9537cf4f7ee3e423cbec/pkg/sql/logictest/testdata/logic_test/pg_catalog#L3017)):*
> ```
> 4294967222  character_sets                         NULL      NULL        false       0            -1
> 4294967223  attributes                             NULL      NULL        false       0            -1
> 4294967224  applicable_roles                       NULL      NULL        false       0            -1
> ```

The churn on this diff :sweat_smile:

**Comment by RichardJCai** [comment]
Thanks!

No other tests other than churn

>The churn on this diff 😅

Yeah the churn diff on adding an internal table is kind of ridiculous

**Comment by RichardJCai** [comment]
bors r=arulajmani

**Pull request merged**
