### PR TITLE
sql: improve interval parsing to better match postgres

### PR DESCRIPTION
**Pull request by madelynnblue**
Needed for upcoming COPY support, which produces this format.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8603)

### CODE REVIEW

**Comment by mjibson** [comment]
Maybe the int/float unit stuff is bad and even though it's postgres-compatible we don't want it? The COPY stuff only outputs ints (AFAICT), so we could reasonably exclude the float stuff. We'd have to be real careful, though, to not support floats differently than postgres, as that could potentially lead to some existing applications to send stuff that's wrong.

Docs may need updating to document support for this format. We will have to note that the weirdness in the int/float unit stuff is there to be compatible with Postgres.

**Comment by RaduBerinde** [comment]
Hi Matt,

According to [this table](https://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES), this format also supports `Y-M D` before `H:M:S`, do we want to support that too?

It looks like there is some difference between SQL and PG when there are negative signs (specifically whether a leading negative sign applies to the entire interval or just the first value - see the third paragraph above that table). I think we are being SQL compatible here and PG by default treats each field as independently signed.. We should probably tolerate negative signs everywhere like PG does (eg `-1:10` and `-1:-10` should both be -70 minutes).

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/eval_test.go, line 523 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-KPOdgVu-L3iFY00my16:-KPOdgVu-L3iFY00my17:buuoi8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/73a4caf487de4ed613566dd1c9badff66077d840/sql/parser/eval_test.go#L523)):*
> ```Go
> 		{`'1:2.3'::interval`, `1m2.3s`},
> 		{`'1:2:3'::interval`, `1h2m3s`},
> 		{`'1234:56:54'::interval`, `1234h56m54s`},
> ```

should add tests with negative intervals

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-:-KPOZnlbGrBUnlKh1vn-:buh3lfd)*

**Comment by mjibson** [comment]
That table is describing ISO8601 support, which we already support and is different than this format: https://github.com/cockroachdb/cockroach/blob/cb60b102970e75faf33dcbd1c21dbf1d6cfe8bed/sql/parser/interval.go#L112

The negative interval stuff is already tracked in #7916, but is about a different syntax (Go-style durations). But I agree that it makes sense to add it here now, will do.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-:-KPOhWhGNFqFTID5dEEq:b-hx64pb)*

**Comment by RaduBerinde** [comment]
Only the last two entries in the table are about ISO8601. The first (`1-2`) and the second (`3 4:05:06`) rows are talking about the "SQL standard format" which looks like this format you are adding.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-:-KPOjx9hk_aDXi9J9uaX:bps6ix6)*

**Comment by mjibson** [comment]
Oh I missed that. Will add, thanks.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-:-KPOzW6np8mAgrrxg0C5:bp3o09l)*

**Comment by mjibson** [comment]
Upon review of that syntax, I would like to just open an issue to support the Y-M-D format at a later time. The purpose of this PR is to make COPY work, and COPY just uses very large hour fields instead of the YMD stuff. Supporting those and the negative durations will possibly involve a larger change to our underlying duration type, and I'd like to punt on that for now.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/eval_test.go, line 523 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-KPOdgVu-L3iFY00my16:-KPPD5RO_cMwu0MN4M8w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73a4caf487de4ed613566dd1c9badff66077d840/sql/parser/eval_test.go#L523)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> should add tests with negative intervals
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-:-KPP8jfFVExUGAo6LHFV:b8k80dp)*

**Comment by RaduBerinde** [comment]
Sure, sounds good.

:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8603#-:-KPPGKJNgRPMn5KSKBdW:b-942qfl)*

**Comment by jseldess** [comment]
Waiting to document until @mjibson makes a few additional changes to how we treat floats.

**Pull request merged**
