### PR TITLE
colexec: add support for UUID type

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add support for UUID type**

This commit adds support for UUID type simply by treating it as
[]byte. This is probably inefficient but requires very little
changes to the code, so maybe it'll be ok to backport for 19.2
release.

**colexec: add an integration test for all supported types**

This commit adds an end-to-end integration test for all supported by
the vectorized engine SQL types. It verifies that passing Datums
through conversion to coldata.Batch, then from batch to Arrow format,
then serializing and deserializing, back from Arrow format to batch,
and materializing the batch outputs the same Datums.

**colexec: check that CFetcher can read all supported types**

This commit adds a simple logic test that creates a table
with all supported by the vectorized engine SQL types, inserts
a row full of NULL values and a row with non-NULL values, and
reads it back. The test uncovered an issue that Oid type was
not decoded by CFetcher (it was reported as "unsupported").

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I thought about implementing `UUID` using `[16]byte`, but that would require more "full" introduction of a new type. Treating it as `[]byte` (I believe) gives us full support out of the box.

**Comment by jordanlewis** [comment]
Cool. But, I don't see any tests that verify the functionality is as we expect. I'd like to see tests that make sure we can read UUIDs from disk, compare them properly, output them.

I think a backport is possible into 19.2.1, potentially.

Are there any concerns with changing the serialization representation? Would that make it hard to upgrade? Think carefully about this as it would be bad if we painted ourselves into a corner.

**Comment by rohany** [comment]
Serialization could be a worry here -- older clusters would send over batches with an older UUID format during distributed queries

**Review by yuzefovich — COMMENTED** [review]
I added an end-to-end test as Alfonso suggested. I believe it addresses the concerns that Jordan expressed as `read UUIDs from disk, compare them properly, output them`, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-LrPekkbBcj6MGzcTCC1:b2zgqy8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rohany)

**Review by jordanlewis — COMMENTED** [review]
Nice! The end to end test is good. But we still need coverage in cfetcher. Can you add an equivalent "all supported types" logic test that inserts an "every-supported-type" row into a table and selects from it? Maybe having an all-NULL row would be good too.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-LroQCX2-Bpyv2wPLjIx:b535ymb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rohany)

**Review by jordanlewis — COMMENTED** [review]
The code LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-LroQRs4Ea591i_ZLUtZ:b-aywcud)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rohany)

**Comment by yuzefovich** [comment]
Great idea, Jordan! I added such test and it uncovered an issue with Oid type. I added a third commit with the test and a fix, PTAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice. Maybe we should add tests that evaluate some expressions with UUIDs (e.g. comparison)? Maybe in the eval tests?

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-LruNAoc3N1tISsWzKfl:bgyavqd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @yuzefovich)

___
*[pkg/sql/colexec/types_integration_test.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruK1il3PHQRdRK83w0:-LruK1il3PHQRdRK83w1:bpjdqx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L32)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/leaktest"
> 	"github.com/cockroachdb/cockroach/pkg/util/randutil"
> 	"github.com/stretchr/testify/require"
> ```

Probably want to separate cockroach and third-party imports.
___
*[pkg/sql/colexec/types_integration_test.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruK81t91IxDyO8k2cm:-LruK81t91IxDyO8k2cn:bvxud7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L35)):*
> ```Go
> )
> 
> // TestSupportedSQLTypesIntegration tests that all supported by the vectorized
> ```

nit: `s/that all supported by the vectorized ... types/ that all types supported by...`
___
*[pkg/sql/colexec/types_integration_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruKrUM6s4lU3bhO92x:-LruKrUM6s4lU3bhO92y:bqkyrls) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L36)):*
> ```Go
> 
> // TestSupportedSQLTypesIntegration tests that all supported by the vectorized
> // engine SQL types can be safely "round-tripped through colserde package." It
> ```

I would probably remove "round-tripped through the colserde package" since it's not clear what that means and modify the rest of the comment to a more physical explanation, e.g. "creates a bunch of rows (including nulls), converts them into column batches, serializes then deserializes these batches, and finally converts the deserialized batches back to rows which are compared to the original rows"
___
*[pkg/sql/colexec/typeconv/typeconv.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruJ9Pr9H43j2GQA1ZY:-LruJ9Ps7f5SWj0t-vGi:b-6gl8t7) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e2c9e96d1dbf9f5f98621a3c663c730e137c05/pkg/sql/colexec/typeconv/typeconv.go#L210)):*
> ```Go
> 			}
> 			// TODO(yuzefovich): this maybe should be GetBytesMut().
> 			return d.UUID.GetBytes(), nil
> ```

You could maybe try running a profile to see, it seems like it probably should be `GetBytesMut`.
___
*[pkg/sql/colexec/typeconv/typeconv.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMXRD6kqB5fUgdf_D:-LruMXRD6kqB5fUgdf_E:b1xlu2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/typeconv/typeconv.go#L27)):*
> ```Go
> // AllSupportedSQLTypes is a slice of all SQL types that the vectorized engine
> // currently supports. It should be kept in sync with FromColumnType().
> var AllSupportedSQLTypes = []types.T{
> ```

Should we put this into `coltypes` instead?
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMf_ZAEXoNX_s1Ciz:-LruMf_ZAEXoNX_s1Cj-:b-mjk1c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f9f8189250e66532847fb5d0f7ea28669664c63/pkg/sql/logictest/testdata/logic_test/vectorize_types#L1)):*
> ```
> # Check that all supported by the vectorized engine types can be read correctly.
> ```

nit: `s/Check... engine types/Check that all types supported by ...`
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMz4Z-sswBQyQy0CI:-LruMz4Z-sswBQyQy0CJ:b-3y8xsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f9f8189250e66532847fb5d0f7ea28669664c63/pkg/sql/logictest/testdata/logic_test/vectorize_types#L12)):*
> ```
>     _int     INT8,
>     _oid     OID,
>     _float   FLOAT8,
> ```

`FLOAT4` as well.

**Review by yuzefovich — COMMENTED** [review]
I added a few things into an eval test, but I'm not sure how useful it is. We already have `logictest/uuid` which itself has some comparisons and sorts, so I feel like it might be redundant.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-LruthysAff4R9nFVPrY:b-9hflai)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @rohany)

___
*[pkg/sql/colexec/types_integration_test.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruK1il3PHQRdRK83w0:-LrudVxXEoR-FV07Atnm:b-9hdawg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L32)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Probably want to separate cockroach and third-party imports.
</blockquote></details>

That's what Goland insists on :man_shrugging: 
___
*[pkg/sql/colexec/types_integration_test.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruK81t91IxDyO8k2cm:-Lrudgna3UCXyHxbZusR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L35)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/that all supported by the vectorized ... types/ that all types supported by...`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/types_integration_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruKrUM6s4lU3bhO92x:-LruefT5-Fj9cjlTR6Y3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L36)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would probably remove "round-tripped through the colserde package" since it's not clear what that means and modify the rest of the comment to a more physical explanation, e.g. "creates a bunch of rows (including nulls), converts them into column batches, serializes then deserializes these batches, and finally converts the deserialized batches back to rows which are compared to the original rows"
</blockquote></details>

Done.
___
*[pkg/sql/colexec/typeconv/typeconv.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruJ9Pr9H43j2GQA1ZY:-Lrur0qd-9NXMusfNIfN:b2hswaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e2c9e96d1dbf9f5f98621a3c663c730e137c05/pkg/sql/colexec/typeconv/typeconv.go#L210)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You could maybe try running a profile to see, it seems like it probably should be `GetBytesMut`.
</blockquote></details>

I think you're right. I ran a simple benchmark and saw 0.5MB allocations with `GetBytes` and no allocations with `GetBytesMut`. Done.
___
*[pkg/sql/colexec/typeconv/typeconv.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMXRD6kqB5fUgdf_D:-LrufJUuELRDZDTusxmf:b-1h05ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/typeconv/typeconv.go#L27)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we put this into `coltypes` instead?
</blockquote></details>

Hm, I feel like it should be here, in `typeconv` package since this is where the mapping from SQL types to coltypes happens. I don't feel strongly about it though.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMf_ZAEXoNX_s1Ciz:-Lrufg9j7GgrqxvnSCMo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f9f8189250e66532847fb5d0f7ea28669664c63/pkg/sql/logictest/testdata/logic_test/vectorize_types#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/Check... engine types/Check that all types supported by ...`
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMz4Z-sswBQyQy0CI:-LrufjNLDet8Xm-4BDXE:b-2tn57v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f9f8189250e66532847fb5d0f7ea28669664c63/pkg/sql/logictest/testdata/logic_test/vectorize_types#L12)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`FLOAT4` as well.
</blockquote></details>

Actually I removed support for `FLOAT4` several weeks ago since it wasn't used internally.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Oh `logictest/uuid` is perfect. That runs with `experimental_on`, right?

> Reviewed 5 of 5 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-LrylJXM22tqNxDGP7-h:b-87b3bt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @yuzefovich)

___
*[pkg/sql/colexec/types_integration_test.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruK1il3PHQRdRK83w0:-LryjjD-0yL-3iWDq4fS:blgzu0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L32)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

That's what Goland insists on :man_shrugging: 
</blockquote></details>

I think you can separate them manually with a blank line and the imports file watcher should keep that separation and reorder the separate import blocks appropriately.
___
*[pkg/sql/colexec/typeconv/typeconv.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMXRD6kqB5fUgdf_D:-Lryjzl3CwkveEcaGF8W:bqa2y1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/typeconv/typeconv.go#L27)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I feel like it should be here, in `typeconv` package since this is where the mapping from SQL types to coltypes happens. I don't feel strongly about it though.
</blockquote></details>

But I think it's specific to the vectorized execution engine and seems to only be used there, right?
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMz4Z-sswBQyQy0CI:-LrykQRF4LRM6fT4mMS0:b-1faoep) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f9f8189250e66532847fb5d0f7ea28669664c63/pkg/sql/logictest/testdata/logic_test/vectorize_types#L12)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Actually I removed support for `FLOAT4` several weeks ago since it wasn't used internally.
</blockquote></details>

It's still supported but with a `float64` internally though, right?
```
root@127.0.0.1:53258/defaultdb> CREATE TABLE a (x FLOAT4);
CREATE TABLE

Time: 3.263ms

root@127.0.0.1:53258/defaultdb> INSERT INTO a VALUES (1.2);
INSERT 1

Time: 3.828ms

root@127.0.0.1:53258/defaultdb> SET vectorize=experimental_always;
SET

Time: 405µs

warning: error retrieving the database name: pq: unable to vectorize execution plan: unsupported processor core "localPlanNode:<RowSourceIdx:0 NumInputs:0 Name:\"virtual table\" > "
root@127.0.0.1:53258/?> SELECT x*0.2 FROM a;
  ?column?
+----------+
      0.24
(1 row)

Time: 8.395ms
```
sha: 33fdfa3b7b4abe56189f1deac0990b74dd547185

**Review by yuzefovich — COMMENTED** [review]
No, it will not run with `experimental_on`, but the tests will run through both the vectorized and the row-by-row engines. The default configs have `vectorize` as `auto` and `off` and we override the vectorize row count threshold, so all streaming queries will go through the vectorized. And, in this case, both engines will be tested, so I removed the eval test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-LrymDJ-ExTJyyvEzy_9:b-2qaraz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @rohany)

___
*[pkg/sql/colexec/types_integration_test.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruK1il3PHQRdRK83w0:-LryncWi7qhTcgJD5LpG:b24d3v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/types_integration_test.go#L32)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you can separate them manually with a blank line and the imports file watcher should keep that separation and reorder the separate import blocks appropriately.
</blockquote></details>

It didn't work :/
___
*[pkg/sql/colexec/typeconv/typeconv.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMXRD6kqB5fUgdf_D:-LryoQyhDN3wN0yVwFiN:b76li4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9d2510ae64bc8f188c57e5d21366aa13df5a668/pkg/sql/colexec/typeconv/typeconv.go#L27)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

But I think it's specific to the vectorized execution engine and seems to only be used there, right?
</blockquote></details>

Ok, I see your point, but I also don't think that `coltypes` is the right place for it then - I don't think `pkg/col/coltypes` should have a dependency on `pkg/sql/types`. And since these supported types are only relevant to the vectorized engine, I moved them into `colexec` package.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-LruMz4Z-sswBQyQy0CI:-LryqZPREh8ygk-vfME8:b-ax6hly) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f9f8189250e66532847fb5d0f7ea28669664c63/pkg/sql/logictest/testdata/logic_test/vectorize_types#L12)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's still supported but with a `float64` internally though, right?
```
root@127.0.0.1:53258/defaultdb> CREATE TABLE a (x FLOAT4);
CREATE TABLE

Time: 3.263ms

root@127.0.0.1:53258/defaultdb> INSERT INTO a VALUES (1.2);
INSERT 1

Time: 3.828ms

root@127.0.0.1:53258/defaultdb> SET vectorize=experimental_always;
SET

Time: 405µs

warning: error retrieving the database name: pq: unable to vectorize execution plan: unsupported processor core "localPlanNode:<RowSourceIdx:0 NumInputs:0 Name:\"virtual table\" > "
root@127.0.0.1:53258/?> SELECT x*0.2 FROM a;
  ?column?
+----------+
      0.24
(1 row)

Time: 8.395ms
```
sha: 33fdfa3b7b4abe56189f1deac0990b74dd547185
</blockquote></details>

Ok, I added `FLOAT4`.

**Review by asubiotto — APPROVED** [review]
:lgtm: We should backport this but wait until 19.2 is released cc @jordanlewis, @awoods187

> Reviewed 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41658#-:-Lrz-v0r1kGqSBxdX7pi:b-fuo91g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @rohany)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
