### PR TITLE
sqlsmith: GROUP BY

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
plong @justinj

**Comment by jordanlewis** [comment]
Justin's on vacation til next week, FYI.

**Comment by mjibson** [comment]
Oh! No rush then.

**Review by justinj — COMMENTED** [review]
:lgtm_strong: nice!

I wish there was a way to easily demonstrate what the queries look like after a change like this, but I guess it's hard because 1. they're so big and 2. they're randomly generated so making them test cases would be weird.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36443#-:-LbxDDnm7aQE0G9qeum6:b4xpal0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 386 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36443#-LbxBjkZ7kmyfppXig_j:-LbxBjk_4FFHBVZL8r9r:bdtk5xi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd11074a571892d9b14dd22205fbc08bd8dac0a/pkg/internal/sqlsmith/relational.go#L386)):*
> ```Go
> 		selectListRefs = groupByRefs
> 		orderByRefs = groupByRefs
> 		ctx = groupByCtx
> ```

We could also use this context sometimes without any explicit grouping columns (see `select sum(x) from a`).
___
*[pkg/internal/sqlsmith/scope.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36443#-LbxB-FGAxVA0RUxDiay:-LbxB-FHEudcsNa1X_qt:buwp86x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd11074a571892d9b14dd22205fbc08bd8dac0a/pkg/internal/sqlsmith/scope.go#L68)):*
> ```Go
> }
> 
> // Context holds information about the current SQL context.
> ```

A little more detail would be good here, I think, something like "...about what kinds of expressions are legal at a particular place in a query"?

**Pull request merged**
