### PR TITLE
tree: fix decimal strings for 0 with exponents < -6

### PR DESCRIPTION
**Pull request by otan**
Release note (bug fix): Fix a bug where 0 with exponents < -6 would display
as `0E(exponent)` instead of printing all 0s, e.g. `0E-7` should be `0.0000000`.

Informs https://github.com/cockroachdb/cockroach/issues/102217

### CODE REVIEW

**Comment by otan** [comment]
i'm fine with it if you are ;)

**Comment by otan** [comment]
(but we'll want to merge https://github.com/cockroachdb/apd/pull/128 first)

**Review by rafiss — CHANGES_REQUESTED** [review]
does this fix #102217 or are there more cases to deal with?

i'm surprised the `::decimal` cases in pkg/cmd/generate-binary/main.go weren't affected. could we add a a test there that shows the fix in action?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-:-NVVjVwY7ow73WVfHALB:bsdibqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-NVVjoSo17tYinEO5pdo:-NVVjoSo17tYinEO5pdp:b-2uqojj) ([raw file](https://github.com/cockroachdb/cockroach/blob/87c279fc4224c081915bee8f36ea5792d948bb11/pkg/sql/logictest/testdata/logic_test/decimal#L480)):*
> ```
> 0          -1         -0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0     -0
> 0          4.2        0E+1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0.0   0
> 0          Infinity   0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000   0     0
> ```

i tried this query on postgres and got this result for this row:
```
         0 |  Infinity |                       0 |    0 |         0
```


<!-- Sent from Reviewable.io -->

**Review by otan — COMMENTED** [review]
> does this fix [#102217](https://github.com/cockroachdb/cockroach/issues/102217) or are there more cases to deal with?

this fixes the display issue, yeah

> i'm surprised the `::decimal` cases in pkg/cmd/generate-binary/main.go weren't affected. could we add a a test there that shows the fix in action?

yep

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-:-NVWGXTC24PuHafH7-af:bla12fl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-NVVjoSo17tYinEO5pdo:-NVWGFZD6A6g6XTTyW5A:b-pdiht7) ([raw file](https://github.com/cockroachdb/cockroach/blob/87c279fc4224c081915bee8f36ea5792d948bb11/pkg/sql/logictest/testdata/logic_test/decimal#L480)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i tried this query on postgres and got this result for this row:
```
         0 |  Infinity |                       0 |    0 |         0
```
</blockquote></details>

this is a bug in our implementation more than anything, and is unrelated to this PR.

pg:
```
otan=# select 0::decimal / 'infinity'::decimal;
 ?column?
----------
        0
(1 row)
```

crdb, before this pr:
```
root@:26257/defaultdb> select 0::decimal / 'infinity'::decimal;
  ?column?
------------
  0E-2019
(1 row)
```

i'm guessing our use of `HighPrecisionContext` to divide `Infinity` is incorrect (it's also incorrect for all the other cases). Seems outside the scope of what I need out of this PR though.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-NVVjoSo17tYinEO5pdo:-NVkOBfO-EsTk1yavbY2:b-pv4c4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/87c279fc4224c081915bee8f36ea5792d948bb11/pkg/sql/logictest/testdata/logic_test/decimal#L480)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this is a bug in our implementation more than anything, and is unrelated to this PR.

pg:
```
otan=# select 0::decimal / 'infinity'::decimal;
 ?column?
----------
        0
(1 row)
```

crdb, before this pr:
```
root@:26257/defaultdb> select 0::decimal / 'infinity'::decimal;
  ?column?
------------
  0E-2019
(1 row)
```

i'm guessing our use of `HighPrecisionContext` to divide `Infinity` is incorrect (it's also incorrect for all the other cases). Seems outside the scope of what I need out of this PR though.
</blockquote></details>

hm ok - but do you have a sense of what is needed in `apd` to make `0.00000...0` display as `0`? would be nice to address later

**Comment by otan** [comment]
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-NVVjoSo17tYinEO5pdo:-NVkhqDVAHe6Nk1dmHJS:b7gclbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/87c279fc4224c081915bee8f36ea5792d948bb11/pkg/sql/logictest/testdata/logic_test/decimal#L480)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm ok - but do you have a sense of what is needed in `apd` to make `0.00000...0` display as `0`? would be nice to address later
</blockquote></details>

it's not `apd` we need to change. it's all the execution stuff that makes `0 / infinity` not use `HighScalePrecision` to divide.

**Comment by otan** [comment]
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-NVVjoSo17tYinEO5pdo:-NVki01lBZeNOQheC0qR:bmvbelm) ([raw file](https://github.com/cockroachdb/cockroach/blob/87c279fc4224c081915bee8f36ea5792d948bb11/pkg/sql/logictest/testdata/logic_test/decimal#L480)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it's not `apd` we need to change. it's all the execution stuff that makes `0 / infinity` not use `HighScalePrecision` to divide.
</blockquote></details>

(we need to change the builtin or whatever that does this)

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
filed https://github.com/cockroachdb/cockroach/pull/102299

**Comment by otan** [comment]
*[`pkg/sql/logictest/testdata/logic_test/decimal` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102299#-NVVjoSo17tYinEO5pdo:-NVki01lBZeNOQheC0qR:b-a2cbod) ([raw file](https://github.com/cockroachdb/cockroach/blob/87c279fc4224c081915bee8f36ea5792d948bb11/pkg/sql/logictest/testdata/logic_test/decimal#L480)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it's not `apd` we need to change. it's all the execution stuff that makes `0 / infinity` not use `HighScalePrecision` to divide.
</blockquote></details>

actually it may be `Divide` in apd, stuff like `0::decimal / 5` performs correctly.

**Pull request merged**
