### PR TITLE
sqlccl: avoid using PlanHookState inside of backup

### PR DESCRIPTION
**Pull request by benesch**
sqlccl.backup will soon be called by jobs.Registry when resuming a job
whose coordinator has died. It currently requires a PlanHookState, but
creating a PlanHookState requires an Executor, which is quite difficult
to plumb.

This commit splits the function into two, where the newly-split chunk,
makeBackupDescriptor, has a hard dependency on PlanHookState but only
needs to be called when creating a new backup and not when resuming an
existing one. The two remaining usages of PlanHookState in the backup
function are removed by passing pointers to client.DB and gossip.Gossip
directly.

### CODE REVIEW

**Comment by benesch** [comment]
Actually, I have a slightly better version of this coming tomorrow. Ignore for now.

**Comment by benesch** [comment]
Ok, RFAL. I went on a side quest to ensure all `BackupDescriptor.Spans` had a corresponding entry in `BackupDescriptor.Descriptors`, which required a side-side quest, #17222. It also seems like we have a requirement that interleaved tables appear after their parents in the descriptor list, and I think it's just luck that `descriptorsMatchingTargets` has been returning tables in the right order so far. See the awkward `sort.Sort` I added.

**Comment by dt** [comment]
LGTM, though, we're going to plumb need more things down to storageccl soon too for inter-node blob sharing (rpcCtx, gossip, maybe stores?). We might want to keep some sort of bundle, but just make it something easier to get outside SQL-land?

**Comment by benesch** [comment]
Per @danhhz's verbal advice, split the test into #17235.

@dt, mind if we cross that bridge when we come to it? Agreed that `backup` is at its argument limit, but we're coming up on this feature freeze real fast.

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 359 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-KpzZ0wT1AXJcYBjBq_7:-KpzZ0wU9dFPNReb0rVo:b-dniigm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d735618f30aa4c85c2c3d5fff28194e7e48c7bbc/pkg/ccl/sqlccl/backup.go#L359)):*
> ```Go
> 			descsByID[sqlDesc.GetID()] = sqlDesc
> 		}
> 		sqlDescs = make([]sqlbase.Descriptor, len(descsByID))
> ```

optional: could save the alloc with `sqlDescs = sqlDescs[:0]`

---

*[pkg/ccl/sqlccl/backup.go, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-KpzZE4JFHFEmgeOMqwQ:-KpzZE4JFHFEmgeOMqwR:bp0u9v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d735618f30aa4c85c2c3d5fff28194e7e48c7bbc/pkg/ccl/sqlccl/backup.go#L367)):*
> ```Go
> 	// Ensure interleaved tables appear after their parent. Since parents must be
> 	// created before their children, simply sorting by ID accomplishes this.
> 	// TODO(benesch): figure out if there's a cleaner way to do this.
> ```

this is fine by me. feel free to remove to TODO

---

*[pkg/ccl/sqlccl/backup.go, line 414 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-Kpzr0XRMDeKR7C1tI9J:-Kpzr0XRMDeKR7C1tI9K:b-uckunv) ([raw file](https://github.com/cockroachdb/cockroach/blob/103ec5a2c7076bfe112af8562efefa05e5023042/pkg/ccl/sqlccl/backup.go#L414)):*
> ```Go
> 	}{}
> 
> 	checkpointMu := struct {
> ```

lets move checkpointed into mu (and don't hold it below during the execution of writeBackupDescriptor, just grab it afterward to update checkpointed)

---

*[pkg/ccl/sqlccl/backup_test.go, line 379 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-KpzZk5Y96nPMXOQ7JUo:-KpzZk5Y96nPMXOQ7JUp:bv0w2yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d735618f30aa4c85c2c3d5fff28194e7e48c7bbc/pkg/ccl/sqlccl/backup_test.go#L379)):*
> ```Go
> 		for _, db := range []string{"system_explicit", "system_implicit"} {
> 			a := sqlDB.QueryStr(fmt.Sprintf("SHOW EXPERIMENTAL_FINGERPRINTS FROM TABLE %s.%s", db, table))
> 			if e := expectedFingerprints[table]; !reflect.DeepEqual(e, a) {
> ```

sqlDB.CheckQueryResults does this for you

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-:-Kpzrp3dhCHwnEQ66fpc:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 359 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-KpzZ0wT1AXJcYBjBq_7:-Kpzzxt2D4A2SdSvDEDU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d735618f30aa4c85c2c3d5fff28194e7e48c7bbc/pkg/ccl/sqlccl/backup.go#L359)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

optional: could save the alloc with `sqlDescs = sqlDescs[:0]`
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-KpzZE4JFHFEmgeOMqwQ:-KpzzyMEEClJBJf3Ikjk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d735618f30aa4c85c2c3d5fff28194e7e48c7bbc/pkg/ccl/sqlccl/backup.go#L367)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this is fine by me. feel free to remove to TODO
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 414 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-Kpzr0XRMDeKR7C1tI9J:-Kq--trJA6TW9hLaa7G7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/103ec5a2c7076bfe112af8562efefa05e5023042/pkg/ccl/sqlccl/backup.go#L414)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

lets move checkpointed into mu (and don't hold it below during the execution of writeBackupDescriptor, just grab it afterward to update checkpointed)
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup_test.go, line 379 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205#-KpzZk5Y96nPMXOQ7JUo:-Kq--uSr6dvGDJaGTfX-:b-c0k1gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d735618f30aa4c85c2c3d5fff28194e7e48c7bbc/pkg/ccl/sqlccl/backup_test.go#L379)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

sqlDB.CheckQueryResults does this for you
</blockquote></details>

(No longer in this PR.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17205)*

**Comment by benesch** [comment]
Merging because this makes my life much easier for an upcoming PR and your changes were straightforward, but please do let me know if you have any post-merge feedback!

**Pull request merged**
