### PR TITLE
util/version: fix version.AtLeast()

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35916#-:-LaHzRj2Cl1R0o4Ayc1T:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35916#-:-LaqAjVd88CMJ3p-D0KU:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
Flake was #35833

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35916#-:-LaqIsW00P5YIDYCJ_G_:b-pi96gf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
