### PR TITLE
sql: add ability to not rewrite old primary key during primary key change

### LINKED ISSUE #43788: add support for alter primary key to denote that the old primary key doesn't need to be rewritten
Sometimes, when using `alter primary key`, it is clear to the user that they don't need their old primary key to be left around, so there should be a way to have it not be rebuilt.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #43788.

Release note (sql change):
This PR introduces the syntax

```
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (x, y) DROP OLD KEY
```
to signify that the old primary key does not need to be rewritten
during the primary key change process.

### CODE REVIEW

**Comment by rohany** [comment]
Taking suggestions on what the syntax should look like!

**Comment by rohany** [comment]
Friendly ping

**Comment by solongordon** [comment]
`DROP OLD KEY` doesn't feel great to me but I'm having trouble coming up with a good alternative. 

Maybe @knz has ideas? The background here is that when a user runs ALTER PRIMARY KEY, by default we "preserve" the old primary key by adding a secondary index on the same columns. This prevents unexpected performance regressions. We'd now like to provide the option for the user to skip that step, since it takes extra time and might not be necessary.

We should also keep thinking about how we can support the Postgres syntax for changing the primary key, that is:
```
ALTER TABLE <table_name> DROP CONSTRAINT <table_name>_pkey;
ALTER TABLE <table_name> ADD PRIMARY KEY (id);
```
We can't really "drop" the primary key when the first statement is run (at least without unnecessarily rewriting the entire table). But maybe we could just set a flag on the primary IndexDescriptor which indicates that it's ok not to rewrite the primary index if an `ADD PRIMARY KEY` or `ALTER PRIMARY KEY` statement is run.

**Comment by knz** [comment]
> We should also keep thinking about how we can support the Postgres syntax for changing the primary key

That is my first thought as well. Let's think this through, in order:

1. CockroachDB already supports giving names to indexes. In fact, IIRC all indexes must have names.
2. IIRC, in pg index name = constraint name when an index is used to support a constraint.
3. The notion of "PRIMARY KEY" in pg is a constraint. It's dropped using DROP CONSTRAINT.
4. ergo, `ALTER TABLE ADD CONSTRAINT new_pk PRIMARY KEY (a,b), DROP CONSTRAINT old_pk`

(remember `ALTER TABLE` accepts a list of one or more commands separated by commas)

You'll need to double-check that we don't hardcode the identifier "`primary`" in tests, etc to designate the PK, but I'd be surprised if we do.

**Comment by knz** [comment]
I'd accept this syntax as-is for compatibility with pg, then add a *planning* level semantic check that ADD CONSTRAINT PK is only listed once in the list of table commands (can't add multiple PKs).

**Comment by solongordon** [comment]
I like that. Though I do wonder if we'll still need to support `DROP CONSTRAINT` and `ADD CONSTRAINT` in separate statements for ORM compatibility.

**Comment by knz** [comment]
I think direct ORM compatibility would be impossible even with my proposal. The pg way to change the PK is to first drop the existing constraint then add a new one. I can hardly see how to achieve this here.

Unless...

Unless dropping the PK implies creating a temporary implicit rowid PK? Until the next explicit new PK. But again unsure how this would work. 
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by rohany** [comment]
> Unless dropping the PK implies creating a temporary implicit rowid PK? Until the next explicit new PK. But again unsure how this would work.

This would be pretty expensive -- we'd basically have to undergo the whole primary key change process twice, rewriting every single index twice.

**Comment by knz** [comment]
> This would be pretty expensive -- we'd basically have to undergo the whole primary key change process twice, rewriting every single index twice.

If the two operations are done in the same BEGIN...COMMIT block, we could merge the two operations before COMMIT processes the schema change.

If they are done in separate (single-stmt txns), then arguably the expense is what the application wants: there could be concurrent accesses in-between the two statements.

**Comment by rohany** [comment]
Do you know how we can inspect all of the statements coming into the planner? My whole view of the system is executing one statement at a time, so I'm unsure how to detect the above.

**Comment by knz** [comment]
That's not the right way to think about it.

The truth of the matter is that each DDL statement is executed first, and as a side effect of its execution it accumulates a "schema change object" that defers "all there needs to happen" to the end of the txn (at COMMIT time).

The idea to "merge" the operations is to let the DDL statements execute as usual, then *optimize* (merge, de-duplicate etc) the schema change objects that have been accumulated during COMMIT.

**Comment by rohany** [comment]
@knz we've been a bit stuck on this. The case of `DROP PRIMARY KEY ... ADD PRIMARY KEY` in the same txn is pretty easy, but the case when just `DROP PRIMARY KEY` occurs in a txn is trickier. The problem is that it isn't really clear how to clean up this extra state at the end of the txn without introducing some sort of out of place special casing.

We've considered the following, but I'm not really happy any of them:
* put some sort of flag on the index/table descriptor that denotes that the PK is dropped, and remember in the `extraTxnState` to clean it up later.
* represent this operation as a mutation and clean it up in the schema changer, but this has the side effect of creating a job to track the operation, which could lead users into thinking that a primary key drop has succeeded.
* try to represent the state of dropping the primary key as some field that doesn't actually need a clean up. For example, storing the version of the table descriptor when the field is written. In this case, if the version of the read table descriptor is ahead of the version that the drop primary key bit was written, then we know the drop primary key wasn't written in this txn. My issue with this approach is that it feels like over-engineering for this small problem.

**Comment by knz** [comment]
What about rejecting the COMMIT with an error if the PK is dropped without adding a new one.

**Comment by rohany** [comment]
going to close this in favor of another PR.

**Pull request closed without merging**
