### PR TITLE
Log events when renaming Databases and Tables

### PR DESCRIPTION
**Pull request by jrote1**
Related to #13492

### CODE REVIEW

**Comment by dhartunian** [comment]
Hi @jrote1 thanks for pushing up this change! I'm going to try and figure out who is best to own this on our end.

@jordanlewis can you help me out here? I'm happy to pick this up on Observability but it looked like you were already looking at the parent issue, I'm not sure who the owner is of the "Events" feature.

**Review by jordanlewis — COMMENTED** [review]
Looks great! Just a couple comments. Thanks for taking this on.

> Reviewed 5 of 5 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55269#-:-MJ2a8d57KzYGELlsDaA:b-fgjr9z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jrote1)

___
*[pkg/sql/event_log.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55269#-MJ2_X382JupLC0k0v1b:-MJ2_X382JupLC0k0v1c:b-nbmjum) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b24cd5f3b946b3dc8b720e5e0ab5370010dffd7/pkg/sql/event_log.go#L32)):*
> ```Go
> 	// EventLogDropDatabase is recorded when a database is dropped.
> 	EventLogDropDatabase EventLogType = "drop_database"
> 	// EventLogDropDatabase is recorded when a database is renamed.
> ```

nit: this change really belongs in the previous commit. If you want you can just squash the two commits together.
___
*[pkg/sql/rename_table.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55269#-MJ2_bJB0y5e0EdsrGyn:-MJ2_bJB0y5e0EdsrGyo:b-f7lds1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eef1d8585ca61c92102c2ae7c7c563812dcc8e81/pkg/sql/rename_table.go#L212)):*
> ```Go
> 	}
> 
> 	// Log Rename Database event. This is an auditable log event and is recorded
> ```

Comment out of date
___
*[pkg/sql/logictest/testdata/logic_test/event_log, line 354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55269#-MJ2_GMJ153-6p0udIMW:-MJ2_GMJ153-6p0udIMX:b-ustx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b24cd5f3b946b3dc8b720e5e0ab5370010dffd7/pkg/sql/logictest/testdata/logic_test/event_log#L354)):*
> ```
> ##################
> 
> # verify event is there, and cascading table drops are logged.
> ```

I'm not sure if this "cascading table drops are logged" part of the sentence makes sense (mis-copypaste?).

Ah I see you got rid of it in the second commit. I think you should squash these commits together

**Comment by jrote1** [comment]
@jordanlewis I squashed the commits and fixed the incorrect comment

**Review by jordanlewis — APPROVED** [review]
Thanks!

bors r+

**Pull request merged**
