### PR TITLE
roachtest: add mixed isolation level variant of TPC-C

### LINKED ISSUE #118272: roachtest: add mixed isolation level variant of TPC-C
We currently have variants of TPC-C that run at Serializable, Read Committed, and ([soon](https://github.com/cockroachdb/cockroach/pull/118271)) Snapshot isolation.

We should add another variant called `tpcc-nowait/isolation-level=mixed/nodes=3/w=1`, which runs some transactions at each isolation level.

The best way to implement this is probably to extend `workload tpcc`'s (`pkg/workload/tpcc/tpcc.go`) `--isolation-level` flag to accept a `mixed` value. This would round robin through the three possible isolation levels, setting a different `default_transaction_isolation` on each SQL conn (around `SetDefaultIsolationLevel`). 

Jira issue: CRDB-35655

### PR DESCRIPTION
**Pull request by nvb**
Closes #118272.

This commit adds the following roachtest:
```
tpcc-nowait/isolation-level=mixed/nodes=3/w=1
```

This roachtest runs TPC-C with some transactions at every supported isolation level (including aliases, for added test coverage).

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118852#-:-Nq-XKqGBt9TW-W1v1SI:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @renatolabs, and @srosenberg)

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118852#-:-Nq-_5Tf4phIi5QdBZ8T:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Comment by nvanbenschoten** [comment]
This test passes with the expected distribution of transaction isolation levels:
```sql
root@localhost:29000/defaultdb> select count(*), isolation_level from crdb_internal.cluster_transactions group by isolation_level;
  count | isolation_level
--------+------------------
     46 | SERIALIZABLE
     88 | SNAPSHOT
     88 | READ COMMITTED
```

Here is the performance summary of the 5 transactions for each isolation level:
```
# read uncommitted (promoted to read committed)
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2743            4.6    175.7    159.4    335.5    436.2    604.0  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27417           45.7     95.6     88.1    209.7    302.0    570.4  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2743            4.6     62.5     52.4    176.2    285.2    419.4  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27436           45.7    967.8    973.1   1208.0   1275.1   1744.8  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2742            4.6     69.7     58.7    176.2    260.0    385.9  stockLevel


# read committed
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2747            4.6    177.5    167.8    335.5    419.4    637.5  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27411           45.7     95.4     88.1    209.7    302.0    570.4  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2751            4.6     63.6     52.4    176.2    268.4    520.1  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27431           45.7    967.8    973.1   1208.0   1275.1   1811.9  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2739            4.6     71.1     60.8    184.5    268.4    520.1  stockLevel


# repeatable read (promoted to snapshot)
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2747            4.6    177.5    167.8    335.5    419.4    637.5  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27411           45.7     95.4     88.1    209.7    302.0    570.4  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2751            4.6     63.6     52.4    176.2    268.4    520.1  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27431           45.7    967.8    973.1   1208.0   1275.1   1811.9  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2739            4.6     71.1     60.8    184.5    268.4    520.1  stockLevel


# snapshot
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2747            4.6    177.5    167.8    335.5    419.4    637.5  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27411           45.7     95.4     88.1    209.7    302.0    570.4  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2751            4.6     63.6     52.4    176.2    268.4    520.1  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27431           45.7    967.8    973.1   1208.0   1275.1   1811.9  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2739            4.6     71.1     60.8    184.5    268.4    520.1  stockLevel


# serializable
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2750            4.6    154.5    134.2    318.8    436.2    704.6  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27446           45.7     93.0     83.9    209.7    302.0    671.1  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2749            4.6     63.4     52.4    184.5    260.0    402.7  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          27450           45.7    971.6    973.1   1208.0   1275.1   2684.4  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2745            4.6     71.7     60.8    176.2    243.3    419.4  stockLevel
```

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Pull request merged**
