### PR TITLE
jobs: add log tags on contexts for Resume and OnFailOrCancel hooks

### PR DESCRIPTION
**Pull request by thoszhang**
This PR adds a log tag with the job ID (`job=...`) to the contexts
passed to `Resume()` and `OnFailOrCancel()`, so that logs emitted from
those job hooks can be associated with the job.

We should probably expand the scope of using these log tags to other
parts of the job registry to avoid the overhead of manually including
job IDs in log messages. This is meant to be a starting point and have a
limited, well-defined scope.

Release note (general change): Logs emitted from jobs are now tagged
with the job ID to improve visibility and aid debugging.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
@spaskob I'm proposing this as an alternative to including `job: %d` to logs in the schema change job resumer that interact with the job. Eventually we may want to replace all the `job: %d` prefixes with this (or some other means of tagging the logs).

One slight downside is that now there are multiple formats surrounding job IDs in logs, but in practice we should grep for just the job ID itself.

**Review by dt — APPROVED** [review]

**Review by spaskob — APPROVED** [review]
Thank you, this is awesome!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45728#-:-M1bSaQVDeifEXooTQ1q:bm1vfsa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

**Comment by lucy-zhang** [comment]
bors flake

bors r+

**Comment by lucy-zhang** [comment]
It was the CLA assistant...

bors r+

**Pull request merged**
