### PR TITLE
opt: fix benchmark

### LINKED ISSUE #135716: opt: BenchmarkEndToEnd fails in `bench` CI run
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_Bench/17829837?buildTab=overview&expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true
```
[00:37:21] :			 [Bench //pkg/sql/opt/bench:bench_test] --- FAIL: BenchmarkEndToEnd
[00:37:21] :			 [Bench //pkg/sql/opt/bench:bench_test]     test_log_scope.go:165: test logs captured to: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/execroot/com_github_cockroachdb_cockroach/_tmp/4d025bdb26128dab9f5a867b6346d1b0/logBenchmarkEndToEnd76308205
[00:37:21] :			 [Bench //pkg/sql/opt/bench:bench_test]     test_log_scope.go:76: use -show-logs to present logs inline
[00:37:21] :			 [Bench //pkg/sql/opt/bench:bench_test]     bench_test.go:1167: -- test log scope end --
```

Jira issue: CRDB-44684

### PR DESCRIPTION
**Pull request by mgartner**
This commit fixes a benchmark that was failing due to the code path in
`BenchmarkEndToEnd` not being able to parse JSON values wrapped in
single quotes. The single quotes are necessary for the non-end-to-end
benchmarks, so `BenchmarkEndToEnd` trims them.

Fixes: #135716.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135708#-:-OC4U7OeEPxDqFx6-oWY:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work figuring that out!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135708#-:-OC4a8fJ8zmw3yrc9MZR:b-6xlleg)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/bench/bench_test.go` line 522 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135708#-OC4_wFP9wZqj7Ah-u8w:-OC4_wFP9wZqj7Ah-u8x:bksq8s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cb1cb252bd4789d08fcbb9492cb706db983989/pkg/sql/opt/bench/bench_test.go#L522)):*
> ```Go
> 		name:    "json-insert",
> 		query:   `INSERT INTO json_table(k, i, j) VALUES (1, 10, '{"a": "foo", "b": "bar", "c": [2, 3, "baz", true, false, null]}')`,
> 		args:    []interface{}{},
> ```

We could potentially add the placeholders back in this case as well now that we know how to make JSON work properly.

**Comment by tbg** [comment]
Wanna merge this? Just spent another five minutes figuring out that my red PR CI was due to this :-)

**Review by mgartner — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135708#-:-OCJhEATCVYxiFaK0LWx:b-tlx7ko)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/bench/bench_test.go` line 522 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135708#-OC4_wFP9wZqj7Ah-u8w:-OCJhBDO-0uth_DsGxCY:bod37xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cb1cb252bd4789d08fcbb9492cb706db983989/pkg/sql/opt/bench/bench_test.go#L522)):*
> We could potentially add the placeholders back in this case as well now that we know how to make JSON work properly.

will do in a separate PR

**Pull request merged**
