### PR TITLE
schemachanger: remove redundant screl schema option

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Release justification: non-functional changes
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
LGTM

While you're here, do you want to add commentary around the line where we duplicate the. The reason is because the rel schema needs to know a type for each attribute. It supports interface types, but if you don't tell it the attribute holds that interface, it'll bind the attribute to the type which implements the interface you first tell it about.

**Comment by chengxiong-ruan** [comment]
Thanks, I added a comment for that.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77633#-:-MxuW3w71dPt43HSz7Wu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
