### PR TITLE
ui: fix metrics scaling for date periods without high sampling resolution

### PR DESCRIPTION
**Pull request by koorosh**
Before, metrics charts and date range selector allowed to select arbitrary
ranges to load time series. It had predefined sampling duration per date
range size (small date ranges had higher sampling resolution).
But cluster doesn't store all metrics time series and periodically cleans
it up. Two cluster settings (`timeseries.storage.resolution_10s.ttl` and
`timeseries.storage.resolution_30m.ttl`) control the logic when time series
with 10s resolution data are removed and then 30min resolution data is
deleted as well. It might cause cases when user requests time series with
higher resolution for older data that has been already deleted.

To prevent such cases, current change adds validation logic that justifies
scaling for requested data depending on cluster's settings and selected
date range.

This change doesn't display any messages for users, but provides mechanism
to get justification reason for changed time scaling.

Release note (ui change): fix issue on Metrics page when graphs don't show
data for date ranges older than 10 days

Example of displaying and hiding messages when user changes date range

https://user-images.githubusercontent.com/3106437/140776401-a675009b-b4e4-4fa4-b9f6-26bf4ecd9b35.mov

### CODE REVIEW

**Comment by koorosh** [comment]
cc @Annebirzin , screen recording is added to show how info messages are shown when date range is changed.

**Comment by Annebirzin** [comment]
Thanks @koorosh, LGTM

cc @thtruo @taroface for any feedback

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @Santamaura)

___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72431#-Mo-UxtxDxXnMXS0K4_O:-Mo-UxtxDxXnMXS0K4_P:b-v24hvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/86078291723aa4994d8fde69bb772e39ebd20d12/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx#L385)):*
> ```
>                   The 'timeseries.storage.resolution_30m.ttl' cluster setting
>                   determines how long data is stored at 30-minute resolution. 
> ```

I realized this tooltip is not clear enough, sorry! Can we add a line after the above sentence:

"Data is no longer stored after this time period."

Otherwise LGTM :)

**Comment by thtruo** [comment]
+1 to Ryan's copy suggestion. Once that's incorporated, the new flow LGTM!

**Review by Santamaura — APPROVED** [review]
:lgtm: couple minor typo nits

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72431#-:-Mo-gxcjCEHnVMBtcHoK:b-lrg1s6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @nathanstilwell)

___
*[pkg/ui/workspaces/db-console/src/redux/timewindow.ts, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72431#-Mo-L0GeD-2bMlc1HY00:-Mo-L0GeD-2bMlc1HY01:b-gbm1qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/86078291723aa4994d8fde69bb772e39ebd20d12/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L251)):*
> ```XML
>  * [resolution30mStorageTTL]           [resolution10sStorageTTL]        [now]
>  *
>  * - time series older that resolution30mStorageTTL duration is subject for deletion
> ```

nit: typo "that" -> "than"
___
*[pkg/ui/workspaces/db-console/src/redux/timewindow.ts, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72431#-Mo-LBJc84GRZp9zQJjM:-Mo-LBJc84GRZp9zQJjN:bimn6qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/86078291723aa4994d8fde69bb772e39ebd20d12/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L252)):*
> ```XML
>  *
>  * - time series older that resolution30mStorageTTL duration is subject for deletion
>  * - time series before resolution30mStorageTTL and older that resolution10sStorageTTL is stored with
> ```

nit: same typo as above

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72431)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nathanstilwell and @taroface)

___
*[pkg/ui/workspaces/db-console/src/redux/timewindow.ts, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72431#-Mo-L0GeD-2bMlc1HY00:-Mo2tqw25RpzMaefE4K2:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/86078291723aa4994d8fde69bb772e39ebd20d12/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L251)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

nit: typo "that" -> "than"
</blockquote></details>

Done
___
*[pkg/ui/workspaces/db-console/src/redux/timewindow.ts, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72431#-Mo-LBJc84GRZp9zQJjM:-Mo2tss_Am5V40zANoPM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/86078291723aa4994d8fde69bb772e39ebd20d12/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L252)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

nit: same typo as above
</blockquote></details>

Done
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72431#-Mo-UxtxDxXnMXS0K4_O:-Mo2tuGB-EYB5q4xfkEk:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/86078291723aa4994d8fde69bb772e39ebd20d12/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx#L385)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
>                   The 'timeseries.storage.resolution_30m.ttl' cluster setting
>                   determines how long data is stored at 30-minute resolution. 
> ```

I realized this tooltip is not clear enough, sorry! Can we add a line after the above sentence:

"Data is no longer stored after this time period."
</blockquote></details>

Done

**Comment by koorosh** [comment]
@thtruo , should it be backported in `21.2` version as well?

**Comment by thtruo** [comment]
@koorosh yes we should backport to `21.2` too

**Comment by thtruo** [comment]
A customer is still seeing this issue occur https://github.com/cockroachdb/cockroach/issues/72874 for v21.2
Looks like the backport to v21.2 did not succeed originally. Can you confirm the latest status @koorosh ?

**Pull request merged**
