### PR TITLE
*: remove various stored contexts

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12345)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM, nice!

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12345#-:-KYyGzjEgkHHl9a6HKMN:b-6ynlgp)*

**Comment by tamird** [comment]
Interestingly the second commit leads to some test failures, so removed it for now.

**Comment by petermattis** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/stop/stopper.go, line 257 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12345#-KYySVOt9y_OpyDDOPnK:-KYySVOt9y_OpyDDOPnL:b-mirxfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5213be68170142732e9f91e720d4c270eaab232d/pkg/util/stop/stopper.go#L257)):*
> ```Go
> 	}
> 
> 	ctx = s.WithCancel(ctx)
> ```

What happens to a cancellable context if the cancel isn't invoked? Seems like `Stopper.mu.cancels` will leak memory. Curious what necessitated this portion of the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12345)*

**Comment by tamird** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/stop/stopper.go, line 257 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12345#-KYySVOt9y_OpyDDOPnK:-KYytCHPIjQZRxNeRU6s:b-jhjm5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5213be68170142732e9f91e720d4c270eaab232d/pkg/util/stop/stopper.go#L257)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What happens to a cancellable context if the cancel isn't invoked? Seems like `Stopper.mu.cancels` will leak memory. Curious what necessitated this portion of the change.
</blockquote></details>

Good point, though this part of the change has already been backed out (but reviewable is confused)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12345)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/stop/stopper.go, line 257 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12345#-KYySVOt9y_OpyDDOPnK:-KYytn_Y-9NBUrXyPZFI:b-4yw2e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5213be68170142732e9f91e720d4c270eaab232d/pkg/util/stop/stopper.go#L257)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Good point, though this part of the change has already been backed out (but reviewable is confused)
</blockquote></details>

Huh? Bad reviewable. Bad. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12345#-:-KYytsZVXj9ydhtpAnV9:bnfp4nl)*

**Pull request merged**
