### PR TITLE
docs: update cockroachdb banner in readme

### PR DESCRIPTION
**Pull request by jordanlewis**
Release note: None

### CODE REVIEW

**Comment by nathanstilwell** [comment]
___
*[docs/media/cockroach_db.png, line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63333#-MXn1J5n68fKMOJGQ1dV:-MXn1J5n68fKMOJGQ1dW:bi8lch) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb5d4443f8d13a61ec5d78d6b3889bbd54c3949/docs/media/cockroach_db.png#L0)):*
Can we make this a PNG with a white background instead? For those of us using _dark mode_, this image is hard to read.

**Comment by nathanstilwell** [comment]
___
*[docs/media/cockroach_db.png, line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63333#-MXn1J5n68fKMOJGQ1dV:-MXn2f8z6WJ3VGZkzAtl:b-pijp45) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb5d4443f8d13a61ec5d78d6b3889bbd54c3949/docs/media/cockroach_db.png#L)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

Can we make this a PNG with a white background instead? For those of us using _dark mode_, this image is hard to read.
</blockquote></details>

[Here's one](https://assets.nathanstilwell.com/extra/cockroach_db_white_bg.png), in case you need it.

**Review by nathanstilwell — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63333)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by jordanlewis** [comment]
Done, thx!

**Pull request merged**
