### PR TITLE
storage,sql: add latest counts to crdb_internal.scan_storage_internal…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…_keys

The latest counts were added to Pebble in
https://github.com/cockroachdb/pebble/pull/3030. This PR is the plumbing to expose these in crdb_internal.scan_storage_internal_keys.

Epic: none

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-Ni_WWw5470qvDyglXUh:-Ni_WWw5470qvDyglXUi:b5ua8ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/281101c1a67535a22e6b89cd1e2ae1e73fee870e/pkg/sql/sem/builtins/fixed_oids.go#L2441)):*
> ```Go
> 	2468: `crdb_internal.request_statement_bundle(stmtFingerprint: string, planGist: string, antiPlanGist: bool, samplingProbability: float, minExecutionLatency: interval, expiresAfter: interval) -> bool`,
> 	2469: `crdb_internal.is_system_table_key(raw_key: bytes) -> bool`,
> 	2470: `crdb_internal.scan_storage_internal_keys(node_id: int, store_id: int, start_key: bytes, end_key: bytes) -> tuple{int AS level, int AS node_id, int AS store_id, int AS snapshot_pinned_keys, int AS snapshot_pinned_keys_bytes, int AS point_key_delete_is_latest_count, int AS point_key_delete_count, int AS point_key_set_is_latest_count, int AS point_key_set_count, int AS range_delete_count, int AS range_key_set_count, int AS range_key_delete_count}`,
> ```

Am I allowed to change the signature in this manner?
This was recently added for v23.2 in https://github.com/cockroachdb/cockroach/commit/08dbd7e12d57dc8fd4972db4a8841d07547ce53c

Does the answer depend on whether this change is backported to v23.2?

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-:-NiaUF3W7koHch4rn2Vc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-Ni_WWw5470qvDyglXUh:-NiaTUSpANsenWN9OEHq:bu1sy13) ([raw file](https://github.com/cockroachdb/cockroach/blob/281101c1a67535a22e6b89cd1e2ae1e73fee870e/pkg/sql/sem/builtins/fixed_oids.go#L2441)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Am I allowed to change the signature in this manner?
This was recently added for v23.2 in https://github.com/cockroachdb/cockroach/commit/08dbd7e12d57dc8fd4972db4a8841d07547ce53c

Does the answer depend on whether this change is backported to v23.2?
</blockquote></details>

I think it's okay because we say that `crdb_internal` should be considered unstable. I guess ideally we'd return rows instead of tuples, and it'd be a little more future proof.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113877)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @yuzefovich)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-Ni_WWw5470qvDyglXUh:-NiatpEn1dBwIdHV8yC4:bm3aft2) ([raw file](https://github.com/cockroachdb/cockroach/blob/281101c1a67535a22e6b89cd1e2ae1e73fee870e/pkg/sql/sem/builtins/fixed_oids.go#L2441)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think it's okay because we say that `crdb_internal` should be considered unstable. I guess ideally we'd return rows instead of tuples, and it'd be a little more future proof.
</blockquote></details>

I wonder what will happen in a mixed-version cluster if we didn't backport to v23.2, and the query execution was distributed. Would the code in generator_builtins.go execute on the gateway node and so proto compatibility would take care of the missing or extra fields?

@yuzefovich

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113877)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-Ni_WWw5470qvDyglXUh:-NibYgGJ53zFq5U8wTp5:b-gppws9) ([raw file](https://github.com/cockroachdb/cockroach/blob/281101c1a67535a22e6b89cd1e2ae1e73fee870e/pkg/sql/sem/builtins/fixed_oids.go#L2441)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I wonder what will happen in a mixed-version cluster if we didn't backport to v23.2, and the query execution was distributed. Would the code in generator_builtins.go execute on the gateway node and so proto compatibility would take care of the missing or extra fields?

@yuzefovich
</blockquote></details>

I think we could have problems if the query happens to be distributed, and the builtin gets evaluated on each node (if it's evaluated only on the gateway, then we'd be ok), and I bet we could come up with such a plan. The problem would be in the "tuple schema" of data produced by the builtin - we assume that a single stage of SQL processors always produces rows of the same "type schema", but this builtin would produce rows with a single tuple but with different "tuple contents" on different versions.

Thus, we should backport this change :)
___
*[`pkg/storage/pebble.go` line 2222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-NibZcoQ8T2mSPwFPaav:-NibZ_Px1m-MD1KRSJ9m:b3z1een) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0d438e0dc20544446cf6d34f7fe1a35719c9d0/pkg/storage/pebble.go#L2222)):*
> ```Go
> 	}
> 	var m enginepb.StorageInternalKeysMetrics
> 	setMetricsFromStats(-1, &stats.Accumulated, &m)
> ```

nit: add `/* level */.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113877)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @yuzefovich)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-Ni_WWw5470qvDyglXUh:-NieD3SB1kpKVajOiwqC:btuzlr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/281101c1a67535a22e6b89cd1e2ae1e73fee870e/pkg/sql/sem/builtins/fixed_oids.go#L2441)):*
> I think we could have problems if the query happens to be distributed

Is it correct to assume that it would result in an error and would not crash a node?

> Thus, we should backport this change :)

Done :)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-:-NieFy8A3LnXeo2QoPjI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`pkg/sql/sem/builtins/fixed_oids.go` line 2441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113877#-Ni_WWw5470qvDyglXUh:-NieFd089hrIVrFiGc2t:bqw05ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/281101c1a67535a22e6b89cd1e2ae1e73fee870e/pkg/sql/sem/builtins/fixed_oids.go#L2441)):*
> Is it correct to assume that it would result in an error and would not crash a node?

Probably it'll be an error (at least in the vectorized engine), but this is "undefined behavior" territory, so I'd not assume this.

**Comment by sumeerbhola** [comment]
bors r=yuzefovich,jbowens

**Pull request merged**
