### PR TITLE
physicalplan: add support for multi-stage execution of regr_avgx, regr_avgy, regr_intercept, regr_r2, and regr_slope aggregate functions.

### PR DESCRIPTION
**Pull request by mneverov**
physicalplan: add support for multi-stage execution of regr_avgx, regr_avgy,
regr_intercept, regr_r2, and regr_slope aggregate functions.

See #58347.

Release note (performance improvement): regr_avgx, regr_avgy, regr_intercept,
regr_r2, and regr_slope aggregate functions are now evaluated more efficiently
in a distributed setting

### CODE REVIEW

**Review by mneverov — COMMENTED** [review]
@yuzefovich can you help me out with the changes in `zone`?
When I run `testlogic` with `rewrite` flag it modifies the `zone` test file, and the `ccl` tests are failing with the changes. I can adjust `zone` test expectations to make tests pass but the next rewrite will override the file.
There are no changes on master branch when I run `testlogic` with `rewrite`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76007#-:-MvTGcrFBuKBI9UmQ_yS:bffew1j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Hm, when I rewrite with your commit reverted (on 7c4e234357923082f7ae90f5a8ab527707c60493), I do see changes in `zone` file too. Clearly, your change is not to blame. My guess is that we have an issue with `-rewrite` flag when `retry` option is specified for the queries, so I'd just revert the changes in `zone` file in your PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76007#-:-MvUJSS18wgJSDm7t00r:b-5xg9nb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by mneverov — COMMENTED** [review]
thanks, reverted the changes in `zone` file.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76007#-:-MvUlds02y9ZMn-RcXDv:b-tox3xi)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — APPROVED** [review]
Nice, thanks! :lgtm:

bors r=yuzefovich

> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76007#-:-MvUvHiqEe46AIwc6ZKh:b-wk33qd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov)

**Pull request merged**
