### PR TITLE
kv: Replace custom logic with singleflight.Group in rangeDescriptorCache

### PR DESCRIPTION
**Pull request by nvb**
To avoid sending a storm of `RangeLookupRequests` for the same
`RangeDescriptor`, we have attempted to coalesce identical
RangeDescriptorCache lookups onto single DB lookup since 7027b38. To
facilitate this, we introduced some custom logic around mapping requests
onto identical in-flight requests. It turns out that the package
`golang.org/x/sync/singleflight` is meant for exactly this use case.

This change replaces our custom logic with the use of a
`singleflight.Group`. This allows us to delete a good chunk of code.

As a welcomed validation, the library looks extremely similar to our
previous implementation. The only downside to this change is that it
forces each range lookup request to occur on a new goroutine, instead of
on the goroutine of the requests "leader". This allows for symmetry
between all requesters because the first to issue a request no longer
has a different code path, which makes the code easier to read. Still,
we should consider if the cleanup is worth the cost of a new goroutine
per in-flight request.

In addition, this PR contains a small bug fix that has evaded fixing for too
long! This change is to no longer insert `RangeDescriptor` intents into 
`rangeDescriptorCache` immediately, which previously overwrote the
non-intent `RangeDescriptor`.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14217)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

looks like an improvement to me.

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 143 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORIWqcwJLlGMFx6_z:-KfORIWqcwJLlGMFx6a-:brq6eig) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L143)):*
> ```Go
> 		}
> 	}
> 	return string(key) + ":" + strconv.FormatBool(useReverseScan)
> ```

fmt.Sprintf is cheaper, I think?

---

*[pkg/kv/range_cache.go, line 293 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORtDKWYwZeZdfNkhE:-KfORtDKWYwZeZdfNkhF:b-ashjkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L293)):*
> ```Go
> 		}
> 
> 		var lookupRes lookupResult
> ```

nit: could avoid renaming this (it was previously called `res`)

---

*[pkg/kv/range_cache.go, line 340 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfOS3z73kVuEPDoMK4P:-KfOS3z73kVuEPDoMK4Q:b-u84k67) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L340)):*
> ```Go
> 	})
> 
> 	// We must use DoChan above so that we cal always unlock this mutex. This must
> ```

s/cal/can/

---

*[pkg/kv/range_cache.go, line 341 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfOT3QVgmOXvFCHwLyw:-KfOT3QVgmOXvFCHwLyx:b1rbnee) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L341)):*
> ```Go
> 
> 	// We must use DoChan above so that we cal always unlock this mutex. This must
> 	// be done *after* the request has been added to the lookupRequests group, or
> ```

This is interesting. Naively, I would expect that we could go further and replace the entire cache with an `inflight.Group`, using `Do` instead of `DoChan`, but I guess that's not so because of the eviction token dance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-:-KfOTrf1zaBdRkOb-_Bh:b-1hfbr2)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 341 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfOT3QVgmOXvFCHwLyw:-KfOVa8w9Qvfs4dHOugv:bkc85y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This is interesting. Naively, I would expect that we could go further and replace the entire cache with an `inflight.Group`, using `Do` instead of `DoChan`, but I guess that's not so because of the eviction token dance?
</blockquote></details>

Ah, nevermind; the structure deletes requests from its internal map as soon as they complete.

Interestingly, the range cache is also a good candidate for https://godoc.org/golang.org/x/sync/syncmap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 341 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfOT3QVgmOXvFCHwLyw:-KfOWR5J4ythaaQjRgnW:bn4zdi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, nevermind; the structure deletes requests from its internal map as soon as they complete.

Interestingly, the range cache is also a good candidate for https://godoc.org/golang.org/x/sync/syncmap.
</blockquote></details>

Ah, might've spoken too soon - there's synchronization here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217)*

**Comment by nvanbenschoten** [comment]
TFTR

---

Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kv/range_cache.go, line 143 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORIWqcwJLlGMFx6_z:-KfOZZyjZMCd2PPiW68v:bps1jwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L143)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

fmt.Sprintf is cheaper, I think?
</blockquote></details>

For small concatenations, it's surprisingly the opposite: https://groups.google.com/forum/#!topic/golang-nuts/uIhmp50Agtw. I'm seeing about an order of magnitude difference in my own testing (with a byte slice and bool)

---

*[pkg/kv/range_cache.go, line 293 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORtDKWYwZeZdfNkhE:-KfOa7QN8LWQrdWoHJFS:b-651n25) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L293)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: could avoid renaming this (it was previously called `res`)
</blockquote></details>

I'm calling the result channel `resC` and the result `res`, so I don't want them to be confused.

---

*[pkg/kv/range_cache.go, line 340 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfOS3z73kVuEPDoMK4P:-KfOaLvs-g1qc3ztEQsP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L340)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/cal/can/
</blockquote></details>

Done.

---

*[pkg/kv/range_cache.go, line 341 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfOT3QVgmOXvFCHwLyw:-KfOaUqtSsMBKFCAonB3:b-434dy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, might've spoken too soon - there's synchronization here.
</blockquote></details>

Yeah, the cache is also backed by an ordered red-black tree to permit range lookups, so neither alternative would suit our needs here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-:-KfOajxd9OZ9mbRw-z6B:bb73zsl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 143 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORIWqcwJLlGMFx6_z:-KfOeK7qQ69N-OTkKkG9:bg4toka) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L143)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

For small concatenations, it's surprisingly the opposite: https://groups.google.com/forum/#!topic/golang-nuts/uIhmp50Agtw. I'm seeing about an order of magnitude difference in my own testing (with a byte slice and bool)
</blockquote></details>

Neat, TIL.

---

*[pkg/kv/range_cache.go, line 293 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORtDKWYwZeZdfNkhE:-KfOeNlIjvzfSmh1pKxH:bz8l296) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L293)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm calling the result channel `resC` and the result `res`, so I don't want them to be confused.
</blockquote></details>

`res` is in a different scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 293 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORtDKWYwZeZdfNkhE:-KfOeZJXwOf3pWmOGhub:b-kyesx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L293)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`res` is in a different scope.
</blockquote></details>

Eh, I guess I don't feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/kv/range_cache.go, line 293 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217#-KfORtDKWYwZeZdfNkhE:-KfOmDd1-boj8kLO1rcc:b-d6digu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ba3e19ade4aef48ed715ed013cd66c455a94340/pkg/kv/range_cache.go#L293)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Eh, I guess I don't feel strongly.
</blockquote></details>

We also have a `lookupRes` is the other scope though, so I'd hate to mix up how we name different types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14217)*

**Pull request merged**
