### PR TITLE
cmd/github-post: refactor issue posting into a library

### PR DESCRIPTION
**Pull request by petermattis**
See #24894

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Hmm, this is primarily code movement, but reviewable isn't showing it as such. Let me try to structure the commits show that the actual diff shows up better. I probably won't get to this until tomorrow.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25596#-:-LCeytRz2UcdcIfwzOsf:b-btxvea)*

**Comment by tschottdorf** [comment]
I can take another look when you've rejiggered this, but as long as you've tested it end-to-end and there aren't any substantial changes in semantics here, LGTM.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/cmd/internal/issues/issues.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25596#-LChSw4_6j3z1HgD3Jjk:-LChSw4a1-gGGWJ2fbG9:b-jyg956) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d927ef6feb97b9a94f6b8fe3d68665a6586368d/pkg/cmd/internal/issues/issues.go#L58)):*
> ```Go
> const githubIssueBodyMaximumLength = 1<<16 - 1
> 
> func trimIssueRequestBody(message string, usedCharacters int) string {
> ```

Explain what `message` is with an example (I tried unsuccessfully to find out).

---

*[pkg/cmd/internal/issues/issues.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25596#-LChTxZx-b8w9s2evaW1:-LChTxZx-b8w9s2evaW2:bq4qc81) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d927ef6feb97b9a94f6b8fe3d68665a6586368d/pkg/cmd/internal/issues/issues.go#L62)):*
> ```Go
> 
> 	if m := stacktraceRE.FindStringIndex(message); m != nil {
> 		// We want the top stack traces plus a few lines before.
> ```

This doesn't have to be in this PR, but some of these messages can get quite long (see for example https://github.com/cockroachdb/cockroach/issues/25573).

It might be nice to use the

```
<details>
 <summary>Summary Goes Here</summary>
collapsed content
</details>
```

construct whenever a good summary is known. That would reduce the time spent scrolling vigorously while looking at test flakes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25596#-:-LChUvqT81jE-BGIjMtr:b6aone)*

**Comment by petermattis** [comment]
There are no semantic changes here, just reorganization of code. `github-post` now only cares about parsing `go test` output and `issues.Post` is what creates a github issue or adds a comment to an existing issue. This logic was previously all bundled together in `github-post`. 

The one tiny change is that the body of the issue message now says `Failed test` instead of `Stress build found a failed test`. 

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cmd/internal/issues/issues.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25596#-LChSw4_6j3z1HgD3Jjk:-LCiPL1y1LDjlQsLbX7c:b-zig5ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d927ef6feb97b9a94f6b8fe3d68665a6586368d/pkg/cmd/internal/issues/issues.go#L58)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Explain what `message` is with an example (I tried unsuccessfully to find out).
</blockquote></details>

Not my code. Comment added with my understanding. 

---

*[pkg/cmd/internal/issues/issues.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25596#-LChTxZx-b8w9s2evaW1:-LCiPZ8Y2Zq6wudri-sE:b-3yfz6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d927ef6feb97b9a94f6b8fe3d68665a6586368d/pkg/cmd/internal/issues/issues.go#L62)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This doesn't have to be in this PR, but some of these messages can get quite long (see for example https://github.com/cockroachdb/cockroach/issues/25573).

It might be nice to use the

```
<details>
 <summary>Summary Goes Here</summary>
collapsed content
</details>
```

construct whenever a good summary is known. That would reduce the time spent scrolling vigorously while looking at test flakes.
</blockquote></details>

Agreed this would be nice. Do you know how to achieve this? I've added a TODO.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25596#-:-LCiQGLd8jnF76V8mpBm:b-v46gjr)*

**Comment by petermattis** [comment]
bors r=tschottdorf

**Comment by tschottdorf** [comment]
🎆 🍾 I owe you one @petermattis

**Pull request merged**
