### PR TITLE
multitenant: add AdminUnsplitRequest capability

### LINKED ISSUE #97716: multitenant: add AdminUnsplitRequest capability
1) Add a new `tenantcapabilitiespb.CanAdminUnsplit` capability.
2) Check capability in `Authorizer.HasCapabilityForBatch`.
3) Remove `ExecutorConfig.RequireSystemTenant` call from `execFactory.ConstructAlterTableUnsplit`, `execFactory.ConstructAlterTableUnsplitAll`.

Jira issue: CRDB-24858

Epic CRDB-23344

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #97716

1) Add a new `tenantcapabilitiespb.CanAdminUnsplit` capability.
2) Check capability in `Authorizer.HasCapabilityForBatch`.
3) Remove `ExecutorConfig.RequireSystemTenant` call from
   `execFactory.ConstructAlterTableUnsplit`,
   `execFactory.ConstructAlterTableUnsplitAll`.

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
As we're adding new capabilities, we should continue to add tests for them in the tenantcapabilities package. For this one, I think all you need is to add more tests to the `Authorizer's` datadriven tests. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97717#-:-NPIdb2t0mYXngNdvUbu:bdlgrhq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mgartner, and @rafiss)

**Review by ecwall — COMMENTED** [review]
To make adding those tests easier, can I replace the request method aliases (`split`, `scan`, `cput`) with the actual method names (`AdminSplit`, `Scan`, `ConditionalPut`)?

This will prevent new cases from needing to be added to this switch for each method:
```
switch z {
  case "split":
    ba.Add(&kvpb.AdminSplitRequest{})
  case "scan":
    ba.Add(&kvpb.ScanRequest{})
  case "cput":
    ba.Add(&kvpb.ConditionalPutRequest{})
  default:
    t.Fatalf("unsupported request type: %s", z)
}
```

I would like to minimize the overhead of using DSLs everywhere for what could be go tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97717#-:-NQ5uj8qCqKz-1JkC3Ce:b-r77cpx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mgartner, and @rafiss)

**Review by knz — APPROVED** [review]
nice.

> Reviewed 18 of 18 files at r3, 1 of 1 files at r4, 8 of 8 files at r5, 25 of 25 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97717#-:-NQ7S4Ql8MK2RNi7rs1i:b-7m74ok)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

**Comment by ecwall** [comment]
bors r=knz

**Pull request merged**
