### PR TITLE
keys,storage: add lock table key space, EngineKey, and LockTableKey

### PR DESCRIPTION
**Pull request by sumeerbhola**
This includes an EngineIterator interface that currently has no
implementation.

The next PR will rename Iterator to MVCCIterator.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
The `storage` parts look good. Love the thorough commenting. I didn't pay much attention to the new keys as I'm not super familiar with the design constraints for the separated lock table. I'll leave reviewing that to @nvanbenschoten.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-:-MKKPN0oDdfUYyHjXPkQ:bhziih7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOrS475FvmrztQQMn:-MKKOrS475FvmrztQQMo:bhzzqd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine.go#L156)):*
> ```Go
> 	// SeekGE advances the iterator to the first key in the engine which
> 	// is >= the provided key.
> 	SeekGE(key EngineKey)
> ```

There is value in symmetry with the existing `Iterator` API, but there is also an opportunity to adjust the API for higher performance. Having this method return `(EngineKey, []byte)` would avoid subsequent calls to `{Key,UnsafeKey}` or `{Value,UnsafeValue}`. Ditto for the other positioning methods (`SeekLT`, `Next`, and `Prev`). I don't particularly mind this API being different, especially if we have a TODO to eventually adjust the `Iterator` API as well.
___
*[pkg/storage/engine_key.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKN84A2zExC2zcr6cb:-MKKN84A2zExC2zcr6cc:bhvf5yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L38)):*
> ```Go
> type EngineKey struct {
> 	Key     roachpb.Key
> 	Version []byte
> ```

Do `Key` and `Version` always share the same underlying memory? If yes, should we consider storing `Version` as an unexported length and provide a `Version() []byte` accessor that dynamically constructs it? The advantage of this approach is shrinking the `EngineKey` struct from 48 bytes to 32 bytes. That might be a perf win, or this might be a pessimization if we're frequently accessing `Version`.
___
*[pkg/storage/engine_key.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOVgm6STlZdDfaz48:-MKKOVgm6STlZdDfaz49:bjtrqug) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L159)):*
> ```Go
> }
> 
> // DecodeEngineKey decodes the given bytes as an EngineKey.
> ```

Should we be noting when these new functions correspond to existing functions? This one is essentially `enginepb.SplitMVCCKey`. Is the intention to deprecate `enginepb.SplitMVCCKey`?
___
*[pkg/storage/engine_key.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKNto75biQazaIjzA4:-MKKNto75biQazaIjzA5:b-ybtjlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L206)):*
> ```Go
> 
> // ToEngineKey converts a lock table key to an EngineKey.
> func (lk LockTableKey) ToEngineKey() EngineKey {
> ```

This performs an allocation. We'll need to be cautious about using this function in performance sensitive code. I wonder if it needs to exist at all.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-:-MKLLIUyDZBe0CiMpWQZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/keys/constants.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKLHprP5keet1ztBtU4:-MKLHprP5keet1ztBtU5:bgh2vhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/keys/constants.go#L172)):*
> ```Go
> 	// Different lock strengths may use different value types. The exclusive
> 	// lock strength uses MVCCMetadata as the value type, since it does
> 	// double duty as a reference to a provisional MVCC value.
> ```

Could you add a TODO to reference the other value type here once it's introduced?
___
*[pkg/keys/doc.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKLI4ZU7LiJl2Mvx-kN:-MKLI4ZU7LiJl2Mvx-kO:b-g7xuba) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/keys/doc.go#L171)):*
> ```Go
> 	// 		`localRangeIDUnreplicatedInfix`.
> 	// 	  - Range local keys all share `LocalRangePrefix`.
> 	//    - Range lock (which are also local keys) all share
> ```

I think this looks off in reviewable because the previous lines use a tab.
___
*[pkg/keys/keys_test.go, line 730 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKLJZpm-3SJju7gYyS1:-MKLJZpm-3SJju7gYyS2:bfqrefl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/keys/keys_test.go#L730)):*
> ```Go
> func TestLockTableKeyEncodeDecode(t *testing.T) {
> 	expectedPrefix := append([]byte(nil), LocalRangeLockTablePrefix...)
> 	expectedPrefix = append(expectedPrefix, LockTableSingleKeyInfix...)
> ```

Is this used?

**Comment by nvanbenschoten** [comment]
Oh, one thing I meant to mention is that we're doing a lot of work to support bloom filter access for lockTable lookups of point reads. Unfortunately, SQL doesn't actually use point reads in almost any case today. This is being worked on in https://github.com/cockroachdb/cockroach/issues/46758, so I still think the focus here is appropriate, but it's something to keep in mind.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> Unfortunately, SQL doesn't actually use point reads in almost any case today. This is being worked on in #46758, so I still think the focus here is appropriate, but it's something to keep in mind.

Ack. I'd looked at https://reviewable.io/reviews/cockroachdb/cockroach/52511 when I was trying to optimize geospatial queries, so hopefully it happens in the near future.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-:-MKLt3ftAyAv-2qt--vH:b-epa32f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/keys/constants.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKLHprP5keet1ztBtU4:-MKLgb7E-gVujRxJgNp8:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/keys/constants.go#L172)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a TODO to reference the other value type here once it's introduced?
</blockquote></details>

Done
___
*[pkg/keys/doc.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKLI4ZU7LiJl2Mvx-kN:-MKLhIGg2kCXLfMmbfTq:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/keys/doc.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think this looks off in reviewable because the previous lines use a tab.
</blockquote></details>

Fixed.
___
*[pkg/keys/keys_test.go, line 730 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKLJZpm-3SJju7gYyS1:-MKLhKNHD17ig4IhVvWI:bwivqlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/keys/keys_test.go#L730)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

Oversight (which lint caught). It is now used.
___
*[pkg/storage/engine.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOrS475FvmrztQQMn:-MKLhwRXD2r3GFf05xDA:b-7szj9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine.go#L156)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

There is value in symmetry with the existing `Iterator` API, but there is also an opportunity to adjust the API for higher performance. Having this method return `(EngineKey, []byte)` would avoid subsequent calls to `{Key,UnsafeKey}` or `{Value,UnsafeValue}`. Ditto for the other positioning methods (`SeekLT`, `Next`, and `Prev`). I don't particularly mind this API being different, especially if we have a TODO to eventually adjust the `Iterator` API as well.
</blockquote></details>

I'm assuming this would mean returning an unsafe key/value. Decoding is not zero-cost, and even getting the unsafe value means calling `pebble.Iterator.Value` (unlike `InternalIterator`, `pebble.Iterator` returns a bool from these positioning methods). Maybe the caller doesn't care about the key and value and just whether the iterator is still valid, or just wants the key. Making the right choice here seems tricky, so I've left this as-is. Let me know if you have a strong opinion.
___
*[pkg/storage/engine_key.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKN84A2zExC2zcr6cb:-MKLmDbL6YX76xEgjvCJ:bwgnbp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L38)):*
> Do Key and Version always share the same underlying memory?

Not sure, yet. I suspect not, because the `Key` could from a different source like a `roachpb.Key` of an MVCC value (though not for the LockTableKey case, since there one performs an additional encoding using `LockTableSingleKey`). How about I leave this for later?

> If yes, should we consider storing Version as an unexported length and provide a Version() []byte accessor that dynamically constructs it? The advantage of this approach is shrinking the EngineKey struct from 48 bytes to 32 bytes. That might be a perf win, or this might be a pessimization if we're frequently accessing Version.

My one previous experience with shrinking from 48 to 40 bytes in golang did not seem to help https://github.com/cockroachdb/cockroach/pull/53446#issuecomment-687378975 but that could be a less frequently copied object. Do you have a good way of deciding when it would help, based on looking at profiles?
___
*[pkg/storage/engine_key.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOVgm6STlZdDfaz48:-MKLnhenEupSoZNSr2FK:b-nr8epr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L159)):*
> Should we be noting when these new functions correspond to existing functions? This one is essentially enginepb.SplitMVCCKey.
 > Is the intention to deprecate enginepb.SplitMVCCKey?

The intention here was to have a "clean" decoding interface for `EngineKey`. I am not sure about replacing `SplitMVCCKey` -- the callers usually discards the second slice, and perhaps that is faster. I don't have a good sense of golang performance -- do you think avoiding that slice assignment is significant? Meanwhile, I've added a TODO.
___
*[pkg/storage/engine_key.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKNto75biQazaIjzA4:-MKLn-OA00jdzHoPPGw7:b-h6jx38) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L206)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This performs an allocation. We'll need to be cautious about using this function in performance sensitive code. I wonder if it needs to exist at all.
</blockquote></details>

Good point. Most of the functions here are place-holders that will get adjusted when adding real code that uses them. This may not need to exist if Puts/Clears to the lock table are an internal implementation detail of adding an intent or clearing an intent, since we currently only have exclusive locks/intents. But eventually we will have other lock strengths too. I've added a TODO for the future to avoid the allocation.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55878)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/engine.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKM1kUH6CVGT-cJNn49:-MKM1kUH6CVGT-cJNn4A:bdz0z5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine.go#L151)):*
> ```Go
> 	UnsafeValue() []byte
> 	// Key returns the current key.
> 	Key() MVCCKey
> ```

`s/MVCCKey/EngineKey/g`
___
*[pkg/storage/engine.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOrS475FvmrztQQMn:-MKM1lqQ5hXEspXLXG0b:bl1zomx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine.go#L156)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm assuming this would mean returning an unsafe key/value. Decoding is not zero-cost, and even getting the unsafe value means calling `pebble.Iterator.Value` (unlike `InternalIterator`, `pebble.Iterator` returns a bool from these positioning methods). Maybe the caller doesn't care about the key and value and just whether the iterator is still valid, or just wants the key. Making the right choice here seems tricky, so I've left this as-is. Let me know if you have a strong opinion.
</blockquote></details>

Won't the caller always be calling `Key()` or `UnsafeKey()` after a positioning call? When would we make a positioning call and not perform such a check? At the very least, I think we could return `(bool, error)` and get rid of `Valid()`.
___
*[pkg/storage/engine_key.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKN84A2zExC2zcr6cb:-MKM2TI41ZTI6coAjpBS:b-bn72cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Do Key and Version always share the same underlying memory?

Not sure, yet. I suspect not, because the `Key` could from a different source like a `roachpb.Key` of an MVCC value (though not for the LockTableKey case, since there one performs an additional encoding using `LockTableSingleKey`). How about I leave this for later?

> If yes, should we consider storing Version as an unexported length and provide a Version() []byte accessor that dynamically constructs it? The advantage of this approach is shrinking the EngineKey struct from 48 bytes to 32 bytes. That might be a perf win, or this might be a pessimization if we're frequently accessing Version.

My one previous experience with shrinking from 48 to 40 bytes in golang did not seem to help https://github.com/cockroachdb/cockroach/pull/53446#issuecomment-687378975 but that could be a less frequently copied object. Do you have a good way of deciding when it would help, based on looking at profiles?
</blockquote></details>

Yes, it is fine to leave this to later.
___
*[pkg/storage/engine_key.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOVgm6STlZdDfaz48:-MKM25LwCyZ0br_oO_9i:bviwb02) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L159)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Should we be noting when these new functions correspond to existing functions? This one is essentially enginepb.SplitMVCCKey.
 > Is the intention to deprecate enginepb.SplitMVCCKey?

The intention here was to have a "clean" decoding interface for `EngineKey`. I am not sure about replacing `SplitMVCCKey` -- the callers usually discards the second slice, and perhaps that is faster. I don't have a good sense of golang performance -- do you think avoiding that slice assignment is significant? Meanwhile, I've added a TODO.

</blockquote></details>

Ack on not replacing `SplitMVCCKey` right now. But I do think this comment should mention the other function: `This function is similar to "enginepb.SplitMVCCKey"` or something like that.

**Review by nvb — APPROVED** [review]
The `pkg/keys` part :lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-:-MKMBRtr5-FYOsph0RyW:bi3t2gm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55878)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKM1kUH6CVGT-cJNn49:-MKMkcRq0oj_NVUgZab9:bxb7hf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine.go#L151)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/MVCCKey/EngineKey/g`
</blockquote></details>

oops. Done.
___
*[pkg/storage/engine.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOrS475FvmrztQQMn:-MKMkhv405uEwyojCjg1:b-cfyib6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine.go#L156)):*
> Won't the caller always be calling Key() or UnsafeKey() after a positioning call? When would we make a positioning call and not perform such a check?

I don't know of any. But there are cases that don't look at value, like https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/mvcc.go#L2800

> At the very least, I think we could return (bool, error) and get rid of Valid().

Good point. Done.
If we had to choose between returning `error` in-band or returning the (key, value), I would lean towards the former (unlike Pebble's `InternalIterator` which requires calling the `Error()` function), since I've been bitten too many times by code that forgot to handle an error and returned an incorrect/incomplete result as truth. 
___
*[pkg/storage/engine_key.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-MKKOVgm6STlZdDfaz48:-MKMpDm_90Bvw9Eagixt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf4c140b85ae4286dd74cdf9b0089ca357ae0b/pkg/storage/engine_key.go#L159)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack on not replacing `SplitMVCCKey` right now. But I do think this comment should mention the other function: `This function is similar to "enginepb.SplitMVCCKey"` or something like that.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55878#-:-MKMtnbhB7oGUp3ZM-__:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @sumeerbhola)

**Pull request merged**
