### PR TITLE
storage: make TestRaftRemoveRace race harder

### PR DESCRIPTION
**Pull request by tamird**
This change trivially reproduces #9017 under stress, and it would be good to figure out why.

Note that changing this test to use only 2 stores causes it to never fail; this suggests that the 3rd store (neither the initiator the ChangeReplicas nor its target) is involved in producing this failure, perhaps via unexpected raft messages to the ChangeReplicas target.

Assigning to @petermattis because he's most familiar with this code, though @bdarnell, @jordanlewis, and @arjunravinarayan might also have some ideas.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10637)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:  Can we mark the test as skipped and merge? This definitely needs to be investigated, especially the panic.

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 2009 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10637#-KWKUHPKIQK0jUmzhQrQ:-KWKUHPKIQK0jUmzhQrR:b-dd04ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5b102f31e3c1a56ec1a3ed3d95c2f66e32b9022/pkg/storage/client_raft_test.go#L2009)):*
> ```Go
> 			storeIndexes = append(storeIndexes, i)
> 		}
> 		mtc.replicateRange(rangeID, storeIndexes...)
> ```

This is what the code was doing before and the previous setup is common practice. I'm not sure why you felt this should change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10637#-:-KWKUaqRDxkUHIGRFpyx:b-8znm5b)*

**Comment by tamird** [comment]
There's probably no rush to merge this - the panic actually occurs more readily without this patch, since the other failure cases are prevented (see https://github.com/cockroachdb/cockroach/issues/9037#issuecomment-260018217).

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 2009 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10637#-KWKUHPKIQK0jUmzhQrQ:-KWKVy87bBoKVlCau_yk:bi7lks) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5b102f31e3c1a56ec1a3ed3d95c2f66e32b9022/pkg/storage/client_raft_test.go#L2009)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This is what the code was doing before and the previous setup is common practice. I'm not sure why you felt this should change.
</details>
I was playing with the number of nodes used in the test to see if it would change the outcome. I'm still contemplating running this test in a few configurations via sub-tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10637#-:-KWKo83tLiR7Nt3wTyC1:b-vw349e)*

**Comment by bdarnell** [comment]
> Note that changing this test to use only 2 stores causes it to never fail; this suggests that the 3rd store (neither the initiator the ChangeReplicas nor its target) is involved in producing this failure, perhaps via unexpected raft messages to the ChangeReplicas target.

An alternate theory is that with two stores, the replication changes are more synchronized: the second store's participation in the quorum is required. With three stores, the two stores that are left alone form a quorum and commit the replication changes as fast as they can, leaving the third store to find out about the changes in racier ways. 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10637#-:-KWRLYBUyh28Ltsb88Bd:bhz163z)*

**Comment by tamird** [comment]
Rebased this - some new failures are now exposed, though perhaps those are expected?

@petermattis triage ping

**Pull request closed without merging**
