### PR TITLE
opt: Improve performance of IndexJoin planning

### PR DESCRIPTION
**Pull request by andy-kimball**
Previously, we were generating an IndexJoin+Scan expression for every
secondary index on a table. However, unless the Scan is constrained or
limited, the IndexJoin has almost no chance of being the best plan. And
yet we were paying a sizeable perf penalty for generating the IndexJoins
and then not using them.

The change is to generate IndexJoins "one level up", only when a Scan is
wrapped in a Select or Limit. At this point, they become viable plans that
have a reasonable chance of being selected.

There are significant planning-time improvements from this change. Here are
single CPU numbers showing the effects on optbuild + normalization + exploration
times:
```
  name                      old time/op  new time/op  delta
  Phases/kv-read/Explore    30.1µs ± 2%  27.7µs ± 3%   -8.12%  (p=0.008 n=5+5)
  Phases/planning1/Explore  15.4µs ± 1%  10.6µs ± 1%  -30.90%  (p=0.008 n=5+5)
  Phases/planning2/Explore  56.8µs ± 2%  31.7µs ± 3%  -44.13%  (p=0.008 n=5+5)
  Phases/planning3/Explore  54.2µs ± 3%  36.7µs ± 3%  -32.21%  (p=0.008 n=5+5)
  Phases/planning4/Explore  67.8µs ± 1%  44.4µs ± 3%  -34.45%  (p=0.008 n=5+5)
  Phases/planning5/Explore  54.0µs ± 3%  35.5µs ± 1%  -34.37%  (p=0.008 n=5+5)
  Phases/planning6/Explore   218µs ± 1%    64µs ± 2%  -70.41%  (p=0.008 n=5+5)
```

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28870)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS0fQo2ZHCkT_kt2qR:-LKS0fQpAzpYTbwDuk_X:bcbya6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/exec/execbuilder/testdata/select_index#L137)):*
> ```
> 
> statement ok
> SET tracing = on,kv,results; SELECT * FROM t WHERE c = 22; SET tracing = off
> ```

Does this test also need a TODO for fixup?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS1RJ6115T6_GAa4fJ:-LKS1RJ76M_CtMFJSH4U:b-ssbev1) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L52)):*
> ```Go
> // IsFullPrimaryScan is true if scanning all rows in the primary index of the
> // Scan operator's table. This means that the Scan operator cannot be
> // constrained or limited, or operate over a secondary index.
> ```

This comment is a bit confusing, since the purpose of this function is to determine if a scan *can* be limited/constrained.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS2SyS5rfO2XyIc0Q4:-LKS2SyS5rfO2XyIc0Q5:b-fng9ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L76)):*
> ```Go
> 
> 	var sb indexScanBuilder
> 	sb.init(c, scanOpDef.Table)
> ```

Seems like we only need this scan builder if the index is forced and the index is not covering. 
___
*[pkg/sql/opt/xform/custom_funcs.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS2gOZ4h_wbgXWn8s4:-LKS2gOZ4h_wbgXWn8s5:bziajd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L99)):*
> ```Go
> 		// Otherwise, if the index must be forced, then construct an IndexJoin
> 		// operator that provides the columns missing from the index.
> 		if !scanOpDef.Flags.ForceIndex {
> ```

Shouldn't we also check whether the forced index is `iter.index`?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS5PoN4ciyu1u_Q9HV:-LKS5PoO9go208McQX_Q:bcxscu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L346)):*
> ```Go
> 	// Make copy of constraint so that idxconstraint instance is not referenced.
> 	copy := *ic.Constraint()
> 	if copy.IsUnconstrained() {
> ```

Can you do this check before making a copy?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS74iIDeQYDh9Yw2JE:-LKS74iIDeQYDh9Yw2JF:b-t14fxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L479)):*
> ```Go
> 
> 		// If the alternate index does not conform to the ordering, then skip it.
> 		ok, reverse := newDef.CanProvideOrdering(c.e.mem.Metadata(), required)
> ```

Can you add a comment to explain the `reverse` return value?
___
*[pkg/sql/opt/xform/index_scan_builder.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS9RHY2jnG1tWMkDux:-LKS9RHY2jnG1tWMkDuy:b-mh3713) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/index_scan_builder.go#L26)):*
> ```Go
> 
> // indexScanBuilder composes a constrained, limited scan over a table index.
> // Any filters are created as close the scan as possible, and index joins can
> ```

[nit] close to

**Review by rytaft — COMMENTED** [review]
Published a bit too early. Nice performance improvements!!

It seems like there are several tests that changed for the worse... I guess you've had discussions with @RaduBerinde about how to fix these?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-:-LKSCgNMAUKbKMsJWtkz:by8rvq8)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
Very nice!

Yeah, I am working on a change for lookup joins that will work similarly (start from a canonical scan and go through the indexes).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-:-LKSR57V9jQ8RZMh90Su:bwf2m2q)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/custom_funcs.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS1RJ6115T6_GAa4fJ:-LKSM40r5XyGM3ensjz9:b-pl9qcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L52)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment is a bit confusing, since the purpose of this function is to determine if a scan *can* be limited/constrained.
</blockquote></details>

I used this comment in my tree, maybe this is more clear?
```
// IsCanonicalScan returns true if the given ScanOpDef is an original unaltered
// primary index Scan operator (i.e. unconstrained and not limited).
```
___
*[pkg/sql/opt/xform/custom_funcs.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSO73E-CHG_D9Nr4hp:-LKSO73E-CHG_D9Nr4hq:b-w2onan) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L98)):*
> ```Go
> 
> 		// Otherwise, if the index must be forced, then construct an IndexJoin
> 		// operator that provides the columns missing from the index.
> ```

mention that in this case, scanIndexIter guarantees that this is the index we are looking at.
___
*[pkg/sql/opt/xform/index_scan_builder.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSP3_Z331B9yfxKUee:-LKSP3_Z331B9yfxKUef:b-y97lul) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/index_scan_builder.go#L90)):*
> ```Go
> // Select expression that wraps the current result expression, and the remainder
> // filter is returned.
> func (b *indexScanBuilder) addSelectAfterSplit(filter memo.GroupID, cols opt.ColSet) memo.GroupID {
> ```

[nit] name the return value, e.g. `remainingFilter`. Mention it is 0 if there's no remainder.
___
*[pkg/sql/opt/xform/index_scan_builder.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSPpzC7YVu16oFvdiN:-LKSPpzC7YVu16oFvdiO:bsirnf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/index_scan_builder.go#L130)):*
> ```Go
> // and returns it.
> func (b *indexScanBuilder) constructInput() memo.GroupID {
> 	switch b.result.Operator() {
> ```

I'm not crazy about this magic (converting an Expr to a group), given that ultimately there aren't many different cases here. Consider making the other functions only store information (e.g. the scandef, the filter) instead of creating expressions, and have a `finalize` method that actually does all the construction. That function will have a few cases inside but each one will be much easier to follow (it would be all in one place, and it would be similar to other exploration custom functions).
___
*[pkg/sql/opt/xform/rules/limit.opt, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSMZcx49HdwgHQDnMw:-LKSMZcx49HdwgHQDnMx:bygwgd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/rules/limit.opt#L19)):*
> ```
> )
> =>
> (LimitScans $def $limit $ordering)
> ```

[nit] maybe `GenerateLimitedScans` since we aren't starting with more than 1 scan.
___
*[pkg/sql/opt/xform/rules/select.opt, line 12 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSNdj-3iQtmQ1NVXvR:-LKSNdj-3iQtmQ1NVXvS:b-7nvlnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/rules/select.opt#L12)):*
> ```
> # the output columns, an IndexJoin is introduced to supply them. See the comment
> # for the ConstrainScans custom method for more details and examples.
> [ConstrainScans, Explore]
> ```

[nit] GenerateConstrainedScans

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/xform/custom_funcs.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS1RJ6115T6_GAa4fJ:-LKSaBCw3SqjIrmmTL0R:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L52)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I used this comment in my tree, maybe this is more clear?
```
// IsCanonicalScan returns true if the given ScanOpDef is an original unaltered
// primary index Scan operator (i.e. unconstrained and not limited).
```
</blockquote></details>

sgtm

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28870)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS0fQo2ZHCkT_kt2qR:-LKXy0Al7D-3Q0igV77b:b-3a4jax) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/exec/execbuilder/testdata/select_index#L137)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Does this test also need a TODO for fixup?
</blockquote></details>

No, Radu and I decided that this is fine as-is. It's an edge case that's not too important.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS1RJ6115T6_GAa4fJ:-LKXyMS720YBq5uTolNF:b-b4uw93) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L52)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

OK, I switched to `IsCanonicalScan` with that comment.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS2SyS5rfO2XyIc0Q4:-LKXyR9a5jLFi6GktXBm:b-15wpus) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L76)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like we only need this scan builder if the index is forced and the index is not covering. 
</blockquote></details>

I moved it down to where it's needed.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSO73E-CHG_D9Nr4hp:-LKY--9s89QTMRAuVJIC:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L98)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

mention that in this case, scanIndexIter guarantees that this is the index we are looking at.
</blockquote></details>

Added a comment.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS2gOZ4h_wbgXWn8s4:-LKXzjS09uBe8tUI8TxN:b-5ksnkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L99)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Shouldn't we also check whether the forced index is `iter.index`?
</blockquote></details>

If there's a forced index, the iterator only returns that one index. i added a comment.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS5PoN4ciyu1u_Q9HV:-LKY-fn07I4aDbJL8r7f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L346)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you do this check before making a copy?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS74iIDeQYDh9Yw2JE:-LKY-xCd9EQYI6rUe_gY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/custom_funcs.go#L479)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a comment to explain the `reverse` return value?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/index_scan_builder.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKS9RHY2jnG1tWMkDux:-LKY02To6wUpiXSzXlQm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/index_scan_builder.go#L26)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] close to
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/index_scan_builder.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSPpzC7YVu16oFvdiN:-LKYATUV5QM9ku-Ckyfc:b-t8ksyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/index_scan_builder.go#L130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not crazy about this magic (converting an Expr to a group), given that ultimately there aren't many different cases here. Consider making the other functions only store information (e.g. the scandef, the filter) instead of creating expressions, and have a `finalize` method that actually does all the construction. That function will have a few cases inside but each one will be much easier to follow (it would be all in one place, and it would be similar to other exploration custom functions).
</blockquote></details>

OK, I reworked as you suggested. See if it makes it clearer.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 29 files at r4, 5 of 7 files at r5, 23 of 23 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28870)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-:-LKZQcDKAK5InNmVcXu7:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/xform/index_scan_builder.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28870#-LKSPpzC7YVu16oFvdiN:-LKbu1l2Aokah2uLNZmh:b-qbxl94) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af103fde78e323b0b465de605c173f12d3fda/pkg/sql/opt/xform/index_scan_builder.go#L130)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

OK, I reworked as you suggested. See if it makes it clearer.
</blockquote></details>

Looks great, thanks!

**Pull request merged**
