### PR TITLE
encoding: correct large decimal decoding

### LINKED ISSUE #16081: Container crash when inserting a too-large value into a DECIMAL column
If you send a very large BigDecimal into an unbounded DECIMAL column, you will crash Cockroach.

If you bound the BigDecimal (e.g. DECIMAL(10,2)) it works fine and correctly rejects the too-large value. If you just make a column of type DECIMAL, the container crashes. The docs imply that precision and scale are optional, but don't list a default value.

When I made this happen by accident, I saw a stacktrace referring to a slice issue. I wanted to paste it here but when I run my test case, the container simply crashes with no stack trace. Still, I can give you my test code

Here are the logs I do have (version and such)

*
* WARNING: running in insecure mode, this is strongly discouraged. See --insecure.
*
CockroachDB node starting at 2017-05-23 13:53:26.517384398 +0000 UTC
build:      CCL v1.0 @ 2017/05/10 13:19:57 (go1.8.1)
admin:      http://advda-roach.docker:8080
sql:        postgresql://root@advda-roach.docker:26257?sslmode=disable
logs:       /cockroach/cockroach-data/logs
store[0]:   path=/cockroach/cockroach-data
status:     initialized new cluster
clusterID:  381f7b33-46a6-4fac-b995-8c2b8d99aa80
nodeID:     1

I've attached a Spock test case that causes the crash.

[bigDecimalTestCase.txt](https://github.com/cockroachdb/cockroach/files/1022383/bigDecimalTestCase.txt)

### PR DESCRIPTION
**Pull request by madelynnblue**
The nonsorting decimal value encode method uses binary.PutUvarint
to encode the length encoded. The decode path was using
DecodeNonsortingUvarint, which is different but happened to be correct
for values < 0x80 (which is most decimals, luckily). Add a correct
decode function and use it correctly in the decode and peek functions.

Fixes #16081

### CODE REVIEW

**Comment by mjibson** [comment]
Ping @danhhz

**Comment by mjibson** [comment]
Sorry, forgot you were out. No rush.

**Comment by danhhz** [comment]
We already have `{Encode,Decode}NonsortingVarint` which wraps `binary.PutVarint`. The naming of the decode method you introduce here should match.`NonsortingUvarint` is already taken by the custom thing we have that puts MSB first. I don't really love this but one option could be `NonsortingMSB` and `NonsortingLSB`?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/encoding/encoding.go, line 188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16152#-KlZ3GFhXYj8lriKIciS:-KlZ3GFhXYj8lriKIciT:b-y104l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6142d003ae050c92f919d68b9a729642dc19f892/pkg/util/encoding/encoding.go#L188)):*
> ```Go
> const (
> 	maxVarintSize        = 9
> 	maxBinaryUvarintSize = 10
> ```

This comes from binary. MaxVarintLen64 right? We should use that constant here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16152#-:-KlZ37ksDDzsjt4u4voc:b-4ydfvc)*

**Comment by mjibson** [comment]
I guess I disagree. I think the current name is really clear in what it does, and using MSB in the name will be less clear.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/encoding/encoding.go, line 188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16152#-KlZ3GFhXYj8lriKIciS:-KlZmBUjHMkA3Y_SySdU:bhfnr8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6142d003ae050c92f919d68b9a729642dc19f892/pkg/util/encoding/encoding.go#L188)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This comes from binary. MaxVarintLen64 right? We should use that constant here
</blockquote></details>

I didn't even know that was a thing. I found it experimentally. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16152#-:-KlZlkcn3Kx3RK4mCgYE:b3du31g)*

**Comment by danhhz** [comment]
I'm open to other names than my MSB/LSB strawman, but I object strongly to the current naming. As of this PR we would have `DecodeNonsortingVarint` and `DecodeBinaryUvarint` which use `binary.{U,}Varint` as well as `DecodeNonsortingUVarint`, which really seems like it's related to `DecodeNonsortingVarint` but is actually the odd one.

**Comment by mjibson** [comment]
Renamed as per discussion.

**Comment by danhhz** [comment]
LGTM

**Pull request merged**
