### PR TITLE
stability: prevent GC from preventing all new transactions

### LINKED ISSUE #9522: storage: Txn GC check uses wrong txn
The [recently-added check](https://github.com/cockroachdb/cockroach/blob/85e34b40104f75f341451d4dca09f3d5037dd729/storage/replica_command.go#L454-L466) to ensure that we don't recreate a transaction that is old enough to be GC'd uses the wrong transaction (`txn` is used to read the existing txn record from disk, and here it is definitely empty because we handled existing txns in the preceding switch statement. Because it is empty, its timestamps are zero, always less than the GC cutoff. It should be looking at the request transaction, or the copy cloned into reply.Txn instead). 

This means that after a transaction GC has occurred, no more transactions can be executed on this range. This is the cause of the current lack of progress with the `photos` app, and suggests a significant gap in our test coverage. 

@cockroachdb/stability

### PR DESCRIPTION
**Pull request by tbg**
Fixes #9522.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9524)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by tschottdorf** [comment]
In the interest of deploying this soon, I'm going to merge this, but please let me know if further refactors/precautions/tests are in order before #9522 can be considered satisfactorily addressed.

**Comment by bdarnell** [comment]
LGTM. I can't think of any other specific tests to add here, but it just makes me nervous that the slow-path GC is so infrequent that we didn't run into this until we both deployed this to production and used a particular workload.

**Comment by tschottdorf** [comment]
Mentioned that in #9522.

**Pull request merged**
