### PR TITLE
opt: Fix output column names

### PR DESCRIPTION
**Pull request by rytaft**
This PR is broken into two commits for ease of review: the first contains the
updates to the go code, and the second contains all the updated test cases.

This PR fixes the output column names for projections with no alias
that are not bare table columns. Previously, any synthesized column was
given a name such as column1, column2, etc. Now the name matches the name
given by the existing CockroachDB planner, which is more evocative of
what the column contains.

For example: aggregate columns such as `MAX(x)` are given the name of
the aggregate builtin (e.g., "max"). Other scalar expressions are given
the name of the full expression. For example, `x + y` is given the name
"x + y".

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

When we display column names in test output, should we add quotes when the labels have spaces, or perhaps remove any spaces? E.g. `columns: (xy.x + 1) = (length('foo') + xy.y):6(bool) uv.rowid * xy.x:7(int)`

I wonder if my recent change to shorten column names can screw things up, e.g. `a + xy.x` -> `x`. We probably want to check that the prefix we are removing only has characters that can appear in table names.

**Comment by rytaft** [comment]
Made those changes. PTAL.

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25614#-:-LCjpbWd5Rprq_9G7iBf:biolf1f)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 62 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25614#-:-LCk0NrI4LtBh6juwVaP:bnfp4nl)*

**Comment by rytaft** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25614#-:-LCk9AdLA_I2Qfqmu0rL:b-ydi9ay)*

**Comment by rytaft** [comment]
bors r-

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25614#-:-LCk9Dum7qFid_9xcuCz:b-ydi9aw)*

**Pull request merged**
