### PR TITLE
kvnemesis: add backoff to retry loop on txn aborts

### PR DESCRIPTION
**Pull request by nvb**
This commit adds an exponential backoff to the transaction retry loop
when it detects that a transaction has been aborted. This was observed
to prevent thrashing under heavy read-write contention on `global_read`
ranges, which are added to kvnemesis in #63747. These ranges have an
added propensity to cause thrashing because every write to these ranges
gets bumped to a higher timestamp, so it is currently imperative that a
transaction be able to refresh its reads after writing to a global_read
range. If other transactions continue to invalidate a read-write
transaction's reads, it may never complete and will repeatedly abort
conflicting txns after detecting deadlocks. This commit prevents this
from stalling kvnemesis indefinitely.

I see two ways that we can improve this situation in the future.
1. The first option is that we could introduce some form of pessimistic
   read-locking for long running read-write transactions, so that they can
   eventually prevent other transactions from invalidating their reads as
   they proceed to write to a global_reads range and get their write
   timestamp bumped. This ensures that when the long-running transaction
   returns to refresh (if it even needs to, depending on the durability of
   the read locks) its reads, the refresh will have a high likelihood of
   succeeding. This is discussed in #52768.
2. The second option is to allow a transaction to re-write its existing
   intents in new epochs without being bumped by the closed timestamp. If a
   transaction only got bumped by the closed timestamp when writing new
   intents, then after a transaction was forced to retry, it would have a
   high likelihood of succeeding on its second epoch as long as it didn't
   write to a new set of keys. This is discussed in #63796.

### CODE REVIEW

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvnemesis/applier.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63799#-MYbvYoj4pgf2C8nuMVQ:-MYbvYoj4pgf2C8nuMVR:b9pdinc) ([raw file](https://github.com/cockroachdb/cockroach/blob/15187bb670fdf04a14323e2285b9a1ccac95f6a4/pkg/kv/kvnemesis/applier.go#L98)):*
> ```Go
> 		var savedTxn *kv.Txn
> 		txnErr := db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 			if savedTxn != nil && savedTxn.TestingCloneTxn().Epoch == 0 {
> ```

I think I'm missing something basic here, but I don't follow why we're checking the `Epoch` of the previous attempt. IIUC the way this is written, we would only backoff if the _previous attempt was not a retry_ right?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvnemesis/applier.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63799#-MYbvYoj4pgf2C8nuMVQ:-MYuZmlY1gmM9H8sXMxt:bsikezc) ([raw file](https://github.com/cockroachdb/cockroach/blob/15187bb670fdf04a14323e2285b9a1ccac95f6a4/pkg/kv/kvnemesis/applier.go#L98)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I think I'm missing something basic here, but I don't follow why we're checking the `Epoch` of the previous attempt. IIUC the way this is written, we would only backoff if the _previous attempt was not a retry_ right?
</blockquote></details>

Good catch! You're not missing anything. This was supposed to check the Epoch of the _new txn_. I made the change and confirmed that it still solves the starvation.

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63799#-:-MYxQ2CyBE6NVOH0wR-0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Pull request merged**
