### PR TITLE
roachpb: disable roachpb.Value checksum computation

### LINKED ISSUE #21435: roachpb: investigate disabling roachpb.Value checksum computation
#21395 disabled verification of the `roachpb.Value` checksums, providing a 15-20% speed boost to large MVCC scans. Checksums are still computed when values are written, they are just not verified. The justification for removing the verification is that TLS and RocksDB checksums already provide adequate coverage. RocksDB checksums have caught disk corruption in the wild. The `roachpb.Value` checksums never have.

Computation of the checksums was left in because disabling them may be problematic. We'd need to verify that checksums are never computed below Raft or perform a migration. But before doing any of that work, we should verify that disabling the checksum provides a speed boost. Workloads to investigate are simple KV operations are bulk insert operations.

@nvanbenschoten for triage.

Jira issue: CRDB-5886

### PR DESCRIPTION
**Pull request by nvb**
Fixes #21435.

This change disables roachpb.Value checksum computation, leaving
the checksum field blank on roachpb.Values.

See https://github.com/cockroachdb/cockroach/issues/21435#issuecomment-358389164
for details on the measured performance improvement from this change.

Release note (performance improvement): Unnecessary value
checksums are no longer computed, speeding up database writes.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/roachpb/data.go, line 248 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4mS83i4fh9e5uUgtXl:-L4mS83i4fh9e5uUgtXm:b-smwaey) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/roachpb/data.go#L248)):*
> ```Go
> // still doesn't allow the compiler to optimize out calls to InitChecksum
> // completely when it is disabled.
> const shouldInitChecksum = false
> ```

So you're using this by just changing the constant and rebuilding? I think we can probably remove it before this PR is merged. 

---

*[pkg/roachpb/data.go, line 265 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4mSuIcTz1pH6h4zKln:-L4mSuIcTz1pH6h4zKlo:b-kohp0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/roachpb/data.go#L265)):*
> ```Go
> // TODO(peter): This method should return an error if the Value is corrupted
> // (e.g. the RawBytes field is > 0 but smaller than the header size).
> func (v *Value) InitChecksum(key []byte) {
> ```

Add a TODO to remove this method in 2.1. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-:-L4mSz7mPlX6yvhcuBEx:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

I notice that we're still calling `Value.Verify` in a number of places. For example, `mvccGetInternal` which is used by `MVCCPut`. Also, `{Get,Scan,ReverseScan}Response.Verify`. Do you want to remove those?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-:-L4n2PzFnMkvCcBR2cpm:b-6hyrsv)*

**Comment by nvanbenschoten** [comment]
A bit of my confusion here is because I'm not sure what our long-term plans are for `roachpb.Value` checksums. Do we want to get rid of `Value.InitChecksum` and `Value.Verify` entirely or just disable them for the time being while leaving the option to easily re-enable them? If the plan is to get rid of them then I can chop more out in this PR.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-:-L4qPjOIhDck1tzjbYgJ:bm8cm0k)*

**Comment by bdarnell** [comment]
I think we want to just get rid of it. It doesn't make sense for SQL, and when/if we ever have a KV API where it might make sense it would probably take a very different form.

**Comment by nvanbenschoten** [comment]
Ok, then, in that case, the only reason to keep `InitChecksum` is for the below raft protos test. I'll rework this a bit and rip out `Value.Verify`.

**Comment by nvanbenschoten** [comment]
I removed `Value.Verify` and all derivative code in a second commit. However, this was called in `mvccGetInternal`, which is used beneath Raft by functions like `MVCCPut`. A checksum verification error beneath Raft would be pretty strange. It would result in a `log.Fatal` because we can't allow updates to the replicated state machine to fail, but it's not clear whether this would be a replicated failure or an unreplicated corruption-related failure.

Still, I replaced these calls with `value.InitChecksum` so that we could use the BelowRaftProtos infrastructure to track down callers. I never saw it fire. I followed these beneath Raft calls up to `StateLoader.SetAppliedIndexBlind` and `StateLoader.SetMVCCStats`, both of which perform blind puts which never hit the `mvccGetInternal` code path. This should mean that making this change beneath Raft is safe, but we might want to keep the `value.InitChecksum` interceptor calls in-place as a lasting assertion.

cc. @danhhz this resulted in some changes to `storageccl/engineccl` that you might be interested in, especially after our conversation yesterday.

---

Review status: 1 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/roachpb/data.go, line 248 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4mS83i4fh9e5uUgtXl:-L4t03HqqOzLgDV2VI2V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/roachpb/data.go#L248)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

So you're using this by just changing the constant and rebuilding? I think we can probably remove it before this PR is merged. 
</blockquote></details>

Done.

---

*[pkg/roachpb/data.go, line 265 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4mSuIcTz1pH6h4zKln:-L4t03-B9JukE6_X-vLg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/roachpb/data.go#L265)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add a TODO to remove this method in 2.1. 
</blockquote></details>

Done.

---

*[pkg/storage/stateloader/stateloader.go, line 361 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4tHduH_AUgCGqFcC3F:-L4tHduH_AUgCGqFcC3G:b-pr02mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/storage/stateloader/stateloader.go#L361)):*
> ```Go
> 	// because it is replicated, so we must always initialize the checksum.
> 	value.MustInitChecksum(key)
> 	return engine.MVCCPut(ctx, eng, nil /* ms */, key, hlc.Timestamp{}, value, nil /* txn */)
> ```

This was already performing a blind put, but I switched to using `engine.MVCCBlindPut` to make it more explicit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-:-L4t8YYoKJ_-As2rdP9z:b-xfo0z)*

**Comment by danhhz** [comment]
ccl stuff lgtm

---

Review status: 1 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/engineccl/rocksdb.go, line 44 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4ukgELOdMhJimbKlWC:-L4ukgEMSW_2C3vV0cL1:b3pgb0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d304f8b31b5b0678a46d36a7b751cf50fedb1/pkg/ccl/storageccl/engineccl/rocksdb.go#L44)):*
> ```Go
> 	// sure the all ones in this BatchRepr validate.
> 	//
> 	// TODO(dan): After a number of hours of trying, I was unable to get a
> ```

whoohoo!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-:-L4ukmoQ6RGIyz08m4IU:bpfat2x)*

**Comment by bdarnell** [comment]
Reviewed 1 of 4 files at r2, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/data.go, line 248 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4mS83i4fh9e5uUgtXl:-L4wQ7-p2s29GBQrEMW0:b-jzxekw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/roachpb/data.go#L248)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

On second thought, while it doesn't make sense to keep the constant around, don't we still need some sort of conditional checksum use here to support mixed-version clusters and downgradability? We can stop verifying checksums immediately but must continue to set them until the cluster version is set to 2.0.

---

*[pkg/storage/stateloader/stateloader.go, line 361 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4tHduH_AUgCGqFcC3F:-L4wPlk5xmLxV6j3CBk8:bi865zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/storage/stateloader/stateloader.go#L361)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This was already performing a blind put, but I switched to using `engine.MVCCBlindPut` to make it more explicit.
</blockquote></details>

The "blind put" distinction is meaningless for inline (timestamp zero) values, and we don't normally use it, so I'd prefer to keep using MVCCPut instead. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487)*

**Comment by nvanbenschoten** [comment]
Review status: 1 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/roachpb/data.go, line 248 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4mS83i4fh9e5uUgtXl:-L4wRtDgFctUIL-b9kpG:bv1dcj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/roachpb/data.go#L248)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

On second thought, while it doesn't make sense to keep the constant around, don't we still need some sort of conditional checksum use here to support mixed-version clusters and downgradability? We can stop verifying checksums immediately but must continue to set them until the cluster version is set to 2.0.
</blockquote></details>

Checksums have always been optional on `roachpb.Values` and checksum verification has always [been a no-op](https://github.com/cockroachdb/cockroach/blob/5a131ba4633dda804cc3f241264cec0891c64ed9/pkg/roachpb/data.go#L268) if the checksum for a value is not set.

---

*[pkg/storage/stateloader/stateloader.go, line 361 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4tHduH_AUgCGqFcC3F:-L4wSXZRuIzm4cGg2oeR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/storage/stateloader/stateloader.go#L361)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The "blind put" distinction is meaningless for inline (timestamp zero) values, and we don't normally use it, so I'd prefer to keep using MVCCPut instead. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487)*

**Comment by bdarnell** [comment]
Review status: 1 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/roachpb/data.go, line 248 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487#-L4mS83i4fh9e5uUgtXl:-L4wT4RtH1d2Neax29Ln:b2pu9ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7840410fbb8bb0309834fee545223ba4681286/pkg/roachpb/data.go#L248)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Checksums have always been optional on `roachpb.Values` and checksum verification has always [been a no-op](https://github.com/cockroachdb/cockroach/blob/5a131ba4633dda804cc3f241264cec0891c64ed9/pkg/roachpb/data.go#L268) if the checksum for a value is not set.
</blockquote></details>

Ack. LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22487)*

**Pull request merged**
