### PR TITLE
asim: make simulator deterministic

### PR DESCRIPTION
**Pull request by kvoli**
This pr introduces several patches that move the allocator simulator towards being deterministic. This is asserted on in the final commit which asserts on e2e determinism.

Part of #83990

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 8 of 8 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-:-NIp70qw-BEuF1qi6bw5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks and @kvoli)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp4jdYDFXkRoxX70GV):*
`s/Previoulsy/Previously/`
___
*[`pkg/kv/kvserver/asim/state/helpers.go` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp4t7JA2DJsWmWWsWC:-NIp4t7JA2DJsWmWWsWD:bde0gym) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29c2f79ca330598a1a258c4794ae15c17424baf/pkg/kv/kvserver/asim/state/helpers.go#L32)):*
> ```Go
> // NewShuffler returns a function which will shuffle elements determinstically
> // but without order.
> func NewShuffler(seed int64) func(n int, swap func(i, j int)) {
> ```

Feel free to ignore, but defining a `Shuffler` interface would give you a little more flexibility if you ever wanted to swap out implementations. It would also give readers something to jump to to understand the shuffle interface, instead of seeing an opaque function signature hanging off `Simulator`.

Something like:
```go
type Shuffler interface {
    // Shuffle pseudo-randomizes the order of elements. n is the number of elements. 
    // Shuffle panics if n < 0. swap swaps the elements with indexes i and j.
    Shuffle(n int, swap func(i, j int))
}

func NewShuffler(seed int64) Shuffler {
    return rand.New(rand.NewSource(seed))
}
```
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 938 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp3O8L7-x7AU-GaNlR:-NIp3O8L7-x7AU-GaNlS:bp9krcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fadb29ed66cf98533271132d761a402e80a294b/pkg/kv/kvserver/asim/state/impl.go#L938)):*
> ```Go
> // Replicas returns all replicas which exist for this range.
> func (r *rng) Replicas() []Replica {
> 	replicas := replicaList{}
> ```

This isn't production code, so it doesn't matter here, but for the sake of completeness, I'll mention that it's typically idiomatic to preallocate a slice with exactly the desired capacity when copying from a map to a slice. That avoids re-sizing and wasted space.
___
*[`pkg/kv/kvserver/asim/state/state_test.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp3Hr16EQhGvcW_5Op:-NIp3Hr16EQhGvcW_5Oq:bsxbopp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fadb29ed66cf98533271132d761a402e80a294b/pkg/kv/kvserver/asim/state/state_test.go#L374)):*
> ```Go
> 	s := NewState(config.DefaultSimulationSettings())
> 	assertListsOrdered(s)
> 	// Test a even distribution with 100 stores, 10k ranges and 1m keyspace.
> ```

nit: "an even"

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-:-NIpSfMr5XeB1l0h_Xun:b-80sls6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks, @benbardin, and @nvanbenschoten)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp4jdYDFXkRoxX70GV):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/Previoulsy/Previously/`
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/state/helpers.go` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp4t7JA2DJsWmWWsWC:-NIpPPMS2uNPKDY-oJOz:b9ssgec) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29c2f79ca330598a1a258c4794ae15c17424baf/pkg/kv/kvserver/asim/state/helpers.go#L32)):*
> type Shuffler interface {
>     // Shuffle pseudo-randomizes the order of elements. n is the number of elements. 
>     // Shuffle panics if n < 0. swap swaps the elements with indexes i and j.
>     Shuffle(n int, swap func(i, j int))
> }
> 
> func NewShuffler(seed int64) Shuffler {
>     return rand.New(rand.NewSource(seed))
> }
I agree but I think a stronger abstraction is required here. Similar to an ECS like composition. I'm fine having this band aid in the meantime.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 938 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp3O8L7-x7AU-GaNlR:-NIpSKwO1h7okOUGMj_O:b-jko55p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fadb29ed66cf98533271132d761a402e80a294b/pkg/kv/kvserver/asim/state/impl.go#L938)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This isn't production code, so it doesn't matter here, but for the sake of completeness, I'll mention that it's typically idiomatic to preallocate a slice with exactly the desired capacity when copying from a map to a slice. That avoids re-sizing and wasted space.
</blockquote></details>

Good idea. Updated to prealloc.
___
*[`pkg/kv/kvserver/asim/state/state_test.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp3Hr16EQhGvcW_5Op:-NIpSb3u8wCTGbSfAer2:bvnrpcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fadb29ed66cf98533271132d761a402e80a294b/pkg/kv/kvserver/asim/state/state_test.go#L374)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: "an even"
</blockquote></details>

updated

**Review by nvb — APPROVED** [review]
:lgtm: mod the one comment.

> Reviewed 2 of 4 files at r9, 7 of 8 files at r10, 3 of 3 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-:-NIyAXk326vnMQG6etWB:b22dvwl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks and @benbardin)

___
*[`pkg/kv/kvserver/asim/state/impl.go` line 938 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93014#-NIp3O8L7-x7AU-GaNlR:-NIyA_Lf1a5rYsmDJyyw:b-6sf6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fadb29ed66cf98533271132d761a402e80a294b/pkg/kv/kvserver/asim/state/impl.go#L938)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Good idea. Updated to prealloc.
</blockquote></details>

You don't need the `i` variable to do this. You can pre-alloc the capacity with a zero-length and then append.
```go
	replicas := make(replicaList, 0, len(r.replicas))
	for _, replica := range r.replicas {
		replicas = append(replicas, replica)
	}
```

**Comment by kvoli** [comment]
bors r=nvanbenschoten

**Comment by kvoli** [comment]
bors r=nvanbenschoten

**Pull request merged**
