### PR TITLE
rttanalysis: add rttanalysisccl.TestBenchmarkExpectations

### PR DESCRIPTION
**Pull request by postamar**
Previously, we had no convenient way to adjust the roundtrip benchmark
expectations in the CCL package. This commit adds a new test for this
purpose and in so doing exports a bunch of test utilities in
rttanalysis.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69020)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/ccl/benchccl/rttanalysisccl/validate_benchmark_data_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69020#-MhGg1OQ-6MeZbmC8SnO:-MhGg1ORDMoJuKh8Hf1B:b-sneccl) ([raw file](https://github.com/cockroachdb/cockroach/blob/546d5d37aebc9898f8aea3e4df422663580202f3/pkg/ccl/benchccl/rttanalysisccl/validate_benchmark_data_test.go#L37)):*
> ```Go
> 		return
> 	}
> ```

It feels like this whole function could get factored out and reused, at which point, it’s not clear to me that you really need to export all the stuff that you’re exporting.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69020)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/benchccl/rttanalysisccl/validate_benchmark_data_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69020#-MhGg1OQ-6MeZbmC8SnO:-MhIVIwpB2Ga2fGATn9S:b4t54ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/546d5d37aebc9898f8aea3e4df422663580202f3/pkg/ccl/benchccl/rttanalysisccl/validate_benchmark_data_test.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It feels like this whole function could get factored out and reused, at which point, it’s not clear to me that you really need to export all the stuff that you’re exporting. 
</blockquote></details>

I tried to do that originally and it didn't work. I'll go back to the drawing board if you want.

**Comment by postamar** [comment]
Not sure what was up, I got it to work as it should right now. Ready for another look.

**Review by otan — APPROVED** [review]

**Comment by postamar** [comment]
bors r+

CI failed due to flaky test, here's hoping that bors will be lucky.

**Pull request merged**
