### PR TITLE
roachtest: disable more expiration lease metamorphism

### LINKED ISSUE #103340: roachtest: systemschema/validate-after-version-upgrade failed
roachtest.systemschema/validate-after-version-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/systemschema/validate-after-version-upgrade) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/systemschema/validate-after-version-upgrade/run_1
(versionupgrade.go:292).func1: failed to set cluster settings: ~ 
		if ! test -e /mnt/data1/cockroach/settings-initialized ; then
			COCKROACH_CONNECT_TIMEOUT=1200 ./v22.2.9/cockroach sql --url 'postgres://root@localhost:26257?sslmode=disable' -e "SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';
SET CLUSTER SETTING enterprise.license = 'crl-0-EID/+KQHGAEiI0NvY2tyb2FjaCBMYWJzIC0gUHJvZHVjdGlvbiBUZXN0aW5n';
SET CLUSTER SETTING kv.expiration_leases_only.enabled = 'true';
" && touch /mnt/data1/cockroach/settings-initialized
		fi
SET CLUSTER SETTING
SET CLUSTER SETTING
ERROR: unknown cluster setting 'kv.expiration_leases_only.enabled'
Failed running "sql": COMMAND_PROBLEM: ssh verbose log retained in ssh_182846.960833017_n1_set-cluster-settings.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*systemschema/validate-after-version-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27953

### LINKED ISSUE #103347: roachtest: tpcc/mixed-headroom/n5cpu16 failed
roachtest.tpcc/mixed-headroom/n5cpu16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/tpcc/mixed-headroom/n5cpu16) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/tpcc/mixed-headroom/n5cpu16/run_1
(versionupgrade.go:280).func1: failed to set cluster settings: ~ 
		if ! test -e /mnt/data1/cockroach/settings-initialized ; then
			COCKROACH_CONNECT_TIMEOUT=1200 ./v22.2.9/cockroach sql --url 'postgres://root@localhost:26257?sslmode=disable' -e "SET CLUSTER SETTING enterprise.license = 'crl-0-EID/+KQHGAEiI0NvY2tyb2FjaCBMYWJzIC0gUHJvZHVjdGlvbiBUZXN0aW5n';
SET CLUSTER SETTING kv.expiration_leases_only.enabled = 'false';
SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';
" && touch /mnt/data1/cockroach/settings-initialized
		fi
SET CLUSTER SETTING
ERROR: unknown cluster setting 'kv.expiration_leases_only.enabled'
Failed running "sql": COMMAND_PROBLEM: ssh verbose log retained in ssh_193407.421940642_n1_set-cluster-settings.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/mixed-headroom/n5cpu16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27957

### PR DESCRIPTION
**Pull request by erikgrinaker**
Resolves #103347.
Resolves #103340.
Touches #98799.
Touches #99087.

Epic: none
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks!

**Comment by erikgrinaker** [comment]
Will let this sit for a couple of hours and see if there are any further failures.

**Comment by renatolabs** [comment]
Two more: #98799 and #103347.

**Pull request merged**
