### PR TITLE
sql: consolidate join type enums

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: move distsqlrun.JoinType to sqlbase

We have at three places where we define a join type enum, and the list
is growing. Moving `distsqlrun.JoinType` to `sqlbase`, with the
intention that it will be used everywhere.

Release note: None

#### sql: remove sql.joinType

Remove joinType and use the new sqlbase.JoinType.

Release note: None

#### sql: remove distsqlrun.joinType

Replace with the new sqlbase.JoinType.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
@abhimadan - I modified the comments for intersect_all and except_all, PTAL

**Comment by abhimadan** [comment]
Modified comments to intersect_all and except_all LGTM. Thanks!

**Comment by pbardea** [comment]
:lgtm:

---

Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 69 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5QZrINpMy6CmarvFZS:-L5QZrINpMy6CmarvFZT:b4tshpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/95ee8e9e210f1cbaf9a9ab1a0fac27dd20171825/pkg/sql/data_source.go#L69)):*
> ```Go
> 			return planDataSource{}, err
> 		}
> 		return p.makeJoin(ctx, sqlbase.InnerJoin, left, right, nil)
> ```

This change, although doesn't change the functionality may be confusing given the comment above (line before `getSources`), may warrant a brief explanation.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5QUn_LkyMfTz_d4BVK:-L5QUn_LkyMfTz_d4BVL:bou14m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b1bc2bcc2afccd195ee555d54bcabbf7621c43b/pkg/sql/distsqlrun/flow_diagram.go#L146)):*
> ```Go
> 			buf.WriteRune(c)
> 		}
> 	}
> ```

Minor: I think this can be done in one line: `buf.WriteString(strings.Replace(joinType.String(), "_", " ", -1))`, but the one liner also makes a copy of the string then adds it to the buffer which is a bit redundant.
Ref: https://golang.org/pkg/strings/#Replace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-:-L5QaCfr-xkPnNwox7cX:bnfp4nl)*

**Comment by pbardea** [comment]
Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 69 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5QZrINpMy6CmarvFZS:-L5QaSXV1_zbf6b9p6b5:b-mktrad) ([raw file](https://github.com/cockroachdb/cockroach/blob/95ee8e9e210f1cbaf9a9ab1a0fac27dd20171825/pkg/sql/data_source.go#L69)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

This change, although doesn't change the functionality may be confusing given the comment above (line before `getSources`), may warrant a brief explanation.
</blockquote></details>

(I mean because the comment above mentions a cross join explicitly and it wasn't equivalence to a cross join was not immediately clear)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/data_source.go, line 69 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5QZrINpMy6CmarvFZS:-L5RbKyVQ3uiN-T0YC5F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/95ee8e9e210f1cbaf9a9ab1a0fac27dd20171825/pkg/sql/data_source.go#L69)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

(I mean because the comment above mentions a cross join explicitly and it wasn't equivalence to a cross join was not immediately clear)
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5QUn_LkyMfTz_d4BVK:-L5Rc09ZpQidcH36UbrN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b1bc2bcc2afccd195ee555d54bcabbf7621c43b/pkg/sql/distsqlrun/flow_diagram.go#L146)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Minor: I think this can be done in one line: `buf.WriteString(strings.Replace(joinType.String(), "_", " ", -1))`, but the one liner also makes a copy of the string then adds it to the buffer which is a bit redundant.
Ref: https://golang.org/pkg/strings/#Replace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 7 of 14 files at r1, 3 of 3 files at r2, 11 of 11 files at r3, 5 of 5 files at r4, 3 of 19 files at r5, 11 of 11 files at r6, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/data_source.go, line 69 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5Rng55IxgnFavhU2wR:-L5Rng55IxgnFavhU2wS:bqabnls) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/data_source.go#L69)):*
> ```Go
> 			return planDataSource{}, err
> 		}
> 		// A cross join is an inner join without an condition.
> ```

an condition -> a condition

---

*[pkg/sql/render.go, line 582 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5RoGUaiHp-MQe_Plks:-L5RoGUaiHp-MQe_Plkt:b-itqdep) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/render.go#L582)):*
> ```Go
> 
> 	if !isUnarySource(r.source) {
> 		// The FROM clause specifies something. Replace with a cross-join.
> ```

Add a similar comment as in the other file that inner join = cross join

---

*[pkg/sql/sqlbase/join_type.proto, line 28 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5Rp7ACJjuunYy-xoWg:-L5Rp7AD5KqmY--4HLyZ:bg88wzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L28)):*
> ```protobuf
> 
>   // A left semi join returns the rows from the left side that have at least a
>   // match (as per equality columns and ON condition).
> ```

it might be a bit clearer to say:

"... rows from the left side that match at least one row from the right side (as per equality columns and ON condition"

---

*[pkg/sql/sqlbase/join_type.proto, line 32 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5RpVrwPtivbT2jZQKG:-L5RpVrwPtivbT2jZQKH:b-6zdp5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L32)):*
> ```protobuf
> 
>   // A left anti join is an "inverted" semi join: it returns the rows from the
>   // left side that don't have a match (as per equality columns and ON
> ```

"... rows from the left side that don't match any columns on the right side (as per...."

---

*[pkg/sql/sqlbase/join_type.proto, line 69 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5Rq-nRb6KlRMZhsZeq:-L5Rq-nRb6KlRMZhsZer:b-6etg13) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L69)):*
> ```protobuf
>   //       1       1        1
>   //       1       2        2
>   //       2       2        2
> ```

shouldn't all the 2s and 3s be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-:-L5RqXP8lb6207aAHnh9:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 9 of 27 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/data_source.go, line 69 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22759#-L5Rng55IxgnFavhU2wR:-L5Rus8A-VODbPZW6ezx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/data_source.go#L69)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

an condition -> a condition
</blockquote></details>

Done.

---

*[pkg/sql/render.go, line 582 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22759#-L5RoGUaiHp-MQe_Plks:-L5Rv63y1Lyu2ND0fViP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/render.go#L582)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Add a similar comment as in the other file that inner join = cross join
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/join_type.proto, line 28 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22759#-L5Rp7ACJjuunYy-xoWg:-L5RvVdE2DS5Vyfz25He:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L28)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

it might be a bit clearer to say:

"... rows from the left side that match at least one row from the right side (as per equality columns and ON condition"
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/join_type.proto, line 32 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22759#-L5RpVrwPtivbT2jZQKG:-L5RvV9PAOnxr7FLNz9d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L32)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

"... rows from the left side that don't match any columns on the right side (as per...."
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/join_type.proto, line 69 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22759#-L5Rq-nRb6KlRMZhsZeq:-L5Rw3as0bml9qxZBY53:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L69)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't all the 2s and 3s be removed?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22759)*

**Comment by rytaft** [comment]
Reviewed 2 of 18 files at r8, 11 of 11 files at r9, 5 of 5 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sqlbase/join_type.proto, line 28 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5Rp7ACJjuunYy-xoWg:-L5Rz45RLyzJhSpnYSDN:bbthxr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L28)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Put the ")" back in - sorry didn't mean to remove it in my comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sqlbase/join_type.proto, line 28 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759#-L5Rp7ACJjuunYy-xoWg:-L5S1RNkWfGOJaWaVcqF:b4j9bb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f13c5f8ae049424bd3606d02e429fa9e1dea46/pkg/sql/sqlbase/join_type.proto#L28)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Put the ")" back in - sorry didn't mean to remove it in my comment
</blockquote></details>

Done. Sigh, I'll have to wait for CI again..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22759)*

**Pull request merged**
