### PR TITLE
builtins: use ST_Union as aggregate

### LINKED ISSUE #51248: geo/geomfn: implement ST_Union({geometry})
Implement `ST_Union` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Union.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Implemented by GEOS - this one is the aggregate form.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-07-09T21:54:34Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Add the ST_Union aggregate, removing the two-argument version
temporarily as we cannot currently have an aggregate and non-aggregate
at the same time. This is ok since we haven't released yet, and from
reading it seems more likely people will use the aggregate version.

Resolves #51248

Release note (sql change): Implement the ST_Union builtin as an
aggregate. The previous alpha-available ST_Union for two arguments is
deprecated.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-:-MFDYyg_6b3qCZtBR5XO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/operator.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-MFDYZBw4szhBN_zMKAS:-MFDYZBx0Q3cI--V4qk1:b9hj76h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48518a5b6c9473aa9d50125e6f3c5a33fb97f65/pkg/sql/opt/operator.go#L406)):*
> ```Go
> 	case ArrayAggOp, AvgOp, ConcatAggOp, CorrOp, JsonAggOp, JsonbAggOp,
> 		JsonObjectAggOp, JsonbObjectAggOp, PercentileContOp, PercentileDiscOp,
> 		SqrDiffOp, StdDevOp, StringAggOp, VarianceOp, StdDevPopOp, STUnionOp, VarPopOp:
> ```

Unless I'm misunderstanding the function, seems like it *can* merge.
___
*[pkg/sql/opt/operator.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-MFDYKoS02UG-rTcmCJU:-MFDYKoS02UG-rTcmCJV:b-e4bovq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48518a5b6c9473aa9d50125e6f3c5a33fb97f65/pkg/sql/opt/operator.go#L425)):*
> ```Go
> 		SumOp, SqrDiffOp, VarianceOp, StdDevOp, XorAggOp, JsonAggOp, JsonbAggOp,
> 		StringAggOp, PercentileDiscOp, PercentileContOp, StdDevPopOp, STMakeLineOp,
> 		STUnionOp, VarPopOp, JsonObjectAggOp, JsonbObjectAggOp:
> ```

Unless I'm misunderstanding the function, seems like it *does* ignore duplicates.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53127)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/opt/operator.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-MFDYZBw4szhBN_zMKAS:-MFEd3L1Dd6gP7i7rv7p:b-g0durc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48518a5b6c9473aa9d50125e6f3c5a33fb97f65/pkg/sql/opt/operator.go#L406)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Unless I'm misunderstanding the function, seems like it *can* merge.
</blockquote></details>

hmm, i think iwas paranoid about order of ops. will do!
___
*[pkg/sql/opt/operator.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-MFDYKoS02UG-rTcmCJU:-MFEdb9M4TlJrxAAUcYP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48518a5b6c9473aa9d50125e6f3c5a33fb97f65/pkg/sql/opt/operator.go#L425)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Unless I'm misunderstanding the function, seems like it *does* ignore duplicates.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 13 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-:-MFFnwNW5bvMv31eJKaD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-MFFnIQaDGCuZjCaBW7-:-MFFnIQb56bZ3bWc9yd0:be9qenm) ([raw file](https://github.com/cockroachdb/cockroach/blob/647540a0cf984a8d45181698013909482e325898/pkg/sql/sem/builtins/aggregate_builtins.go#L701)):*
> ```Go
> 	}
> 	var err error
> 	agg.ewkb, err = geos.Union(agg.ewkb, geomArg.EWKB())
> ```

We are allocating a slice for the result each time we call `geos.Union`, in `cStringToSafeGoBytes`. We could change `geos.Union` to accept the existing slice. A TODO is fine.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53127)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @otan)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53127#-MFG6UYV5XNgzHCLTySB:-MFG6UYW7IhaDj2QhLMk:bh3s6cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/647540a0cf984a8d45181698013909482e325898/pkg/sql/distsql/columnar_operators_test.go#L187)):*
> ```Go
> 								aggFnInputTypes[j] = sqlbase.RandType(rng)
> 							}
> 							// There is a special case for these functions when at
> ```

[nit] these -> some?

**Pull request merged**
