### PR TITLE
roachtest: fix transfer-leases

### LINKED ISSUE #91801: roachtest: transfer-leases/drain-other-node failed
roachtest.transfer-leases/drain-other-node [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7478551?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7478551?buildTab=artifacts#/transfer-leases/drain-other-node) on release-22.2.0 @ [234c9295cc02150f919cfa96b09ee2fa07b68ace](https://github.com/cockroachdb/cockroach/commits/234c9295cc02150f919cfa96b09ee2fa07b68ace):

```
test artifacts and logs in: /artifacts/transfer-leases/drain-other-node/run_1
	quit.go:72,quit.go:324,soon.go:69,retry.go:208,soon.go:75,soon.go:48,quit.go:228,quit.go:95,quit.go:154,context.go:91,quit.go:153,quit.go:95,quit.go:54,quit.go:361,test_runner.go:930: (1) ranges with no lease outside of node 3: []string{"37"}
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*transfer-leases/drain-other-node.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21437

### PR DESCRIPTION
**Pull request by tbg**
`checkNoLeases` verifies that once a node is drained, for each range
there is one replica of the other nodes that sees the lease on one of
the non-drained stores. The reason it asks justs for *one* replica to
have the lease as opposed to all of them is because some followers may
be behind.

However, even just the assumption that there is one can be violated.
The drain succeeds once the draining node has locally seen the lease
transfer succeed. It is likely the raft leader at this point, so it
will be the first one to see this event. Other nodes will only see
it after one additional round-trip (when they learn that the log
index has committed, and then go and apply it).

So going and looking for a replica that sees the new lease immediately
after the drain succeeds may fail.

Work around this by sleeping for one second before checking, which ought
to be enough, and is also a small enough delay to make sure that if
leases are actually not getting transferred, the check will continue to
fail (non-cooperative lease failover is on the order of multiple
seconds).

This commit also improves a debugging file which was previously
clobbered over the multiple iterations of the surrounding loop.

It also makes it clearer that we're pulling the range data from
each node in turn (we were previously hitting otherNodeID but asking
it to proxy to the node. Now we're hitting each node directly without
relying on the internal redirect, which is less confusing).

See: https://github.com/cockroachdb/cockroach/issues/91801#issuecomment-1323331606

Fixes #91801.

Epic: none
Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Ran the test locally to check that I didn't obviously mess up. Still works.

**Review by erikgrinaker — APPROVED** [review]

**Comment by tbg** [comment]
I confused myself again. The endpoint we're hitting doesn't matter because we're hitting `_status/ranges/${i}`, where ${i} is the `nodeID`. So no matter which node we hit, the result will come from node i, and the change here is redundant.

**Review by erikgrinaker — APPROVED** [review]
Not pretty, but gets the job done I suppose. No condition we can wait for instead?

**Comment by tbg** [comment]
Not a good time to rewrite this test, and couldn't think of anything better, so don't think so.

bors r=erikgrinaker

**Comment by aliher1911** [comment]
blathers backport 22.2

**Pull request merged**
