### PR TITLE
ccl/sqlproxyccl: add basic Balancer component for load balancing

### PR DESCRIPTION
**Pull request by jaylim-crl**
#### ccl/sqlproxyccl: rename LookupTenantAddrs to TryLookupTenantAddrs 

This commit is purely mechanical, and renames LookupTenantAddrs in the
directory cache to TryLookupTenantAddrs. This is done so that we could
rename EnsureTenantAddr to LookupTenantAddr, which is more explicit.

Release note: None
  
#### ccl/sqlproxyccl: rename EnsureTenantAddr to LookupTenantAddr 

This commit renames EnsureTenantAddr within the tenant directory cache to
LookupTenantAddr. At the same time, we moved the logic for ChoosePodAddr out
of tenantEntry into the directory cache. This will prepare us for moving the
balancing logic out of the directory cache into the balancer.

Release note: None
  
#### ccl/sqlproxyccl: TryLookupTenantAddrs now return []*tenant.Pod 

Previously, TryLookupTenantAddrs returned addresses. This commit is purely
mechanical, and updates that to return a slice of *tenant.Pod instead. We do
this so that it will be consistent with LookupTenantPod later on. A side effect
of this is that the method has been renamed to TryLookupTenantPods.

Release note: None
  
#### ccl/sqlproxyccl: add basic Balancer component for load balancing 

Previously, all the load balancing logic is within the directory cache, which
makes it difficult to implement the connection rebalancing feature. This commit
extracts all of those logic out of the directory cache into a new Balancer
component, which will be responsible for load balancing moving forward. For
that to work, the directory cache now will only return pods in two forms:
- LookupTenantPods
- TryLookupTenantPods

The "try" variant will return an error if the cluster hasn't been fetched into
the directory's cache yet, and will never attempt to resume the tenant if there
are no available pods. LookupTenantPods will block until there is at least one
available SQL pod.

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/tenant/directory_cache.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-Mytxbov1hyPUlJyTYI8:-Mytxbow8O8Ow1wd6NGX:b-whtrf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6171fa2bb5bacb6daefc66e856c27e63da81766/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L202)):*
> ```Go
> 		}
> 	}
> 	pods := make([]*Pod, len(tenantPods))
> ```

The directory entry code takes pains to always "copy-on-write" and never overwrite any pods in the slice (see e.g. `tenantEntry.AddPod`). We should be able to simply return the slice here, with no need to copy. Is there code somewhere that makes you think we can't do that? We should add a comment to the `tenantEntry.pods` fields to make this more clear.
___
*[pkg/ccl/sqlproxyccl/tenant/directory_cache.go, line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-MytyRnp9dpNVSJE8aW1:-MytyRnp9dpNVSJE8aW2:b-d854wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6171fa2bb5bacb6daefc66e856c27e63da81766/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L237)):*
> ```Go
> 	pods := make([]*Pod, len(tenantPods))
> 	for i, pod := range tenantPods {
> 		// Make a copy of the tenant pod to avoid modifications by callers.
> ```

A copy is not needed here either.

**Review by jaylim-crl — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-:-Mytzj40E15XlCmVmqhZ:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jaylim-crl, and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/tenant/directory_cache.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-Mytxbov1hyPUlJyTYI8:-MytyxO8EVFMHwAn5bqO:b-fqlkou) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6171fa2bb5bacb6daefc66e856c27e63da81766/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L202)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The directory entry code takes pains to always "copy-on-write" and never overwrite any pods in the slice (see e.g. `tenantEntry.AddPod`). We should be able to simply return the slice here, with no need to copy. Is there code somewhere that makes you think we can't do that? We should add a comment to the `tenantEntry.pods` fields to make this more clear.
</blockquote></details>

This is to avoid callers from mutating the data. I'm aware that we always do copy-on-write, but that's only when we add/remove pods. `entry.GetPods()` does not return a copy. This means that if we have two calls to LookupTenantPods, they'll both return the same slice. That's fine if callers don't mutate the pod entries, which is true for what we have today, but may not hold in the future. Alternatively, we could return the same slice as-is, but add a huge note that callers should not modify the pod entries themselves.

**Review by jaylim-crl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/tenant/directory_cache.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-Mytxbov1hyPUlJyTYI8:-MytzwCYEUiEhQr3XVxj:bqq9jeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6171fa2bb5bacb6daefc66e856c27e63da81766/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L202)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

This is to avoid callers from mutating the data. I'm aware that we always do copy-on-write, but that's only when we add/remove pods. `entry.GetPods()` does not return a copy. This means that if we have two calls to LookupTenantPods, they'll both return the same slice. That's fine if callers don't mutate the pod entries, which is true for what we have today, but may not hold in the future. Alternatively, we could return the same slice as-is, but add a huge note that callers should not modify the pod entries themselves.
</blockquote></details>

Done. I removed this, and went ahead with adding a comment.
___
*[pkg/ccl/sqlproxyccl/tenant/directory_cache.go, line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-MytyRnp9dpNVSJE8aW1:-Myu30RZ8N18q8AvyPnB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6171fa2bb5bacb6daefc66e856c27e63da81766/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L237)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

A copy is not needed here either.
</blockquote></details>

Done.

**Comment by andy-kimball** [comment]
___
*[pkg/ccl/sqlproxyccl/tenant/directory_cache.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-Mytxbov1hyPUlJyTYI8:-MywKOa370DmCjkwmLeK:b-h6dv1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6171fa2bb5bacb6daefc66e856c27e63da81766/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L202)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Done. I removed this, and went ahead with adding a comment.
</blockquote></details>

OK. FYI, it's fine and usual to just document the fact that callers should not modify what a method returns. In fact, it'd be very strange in a case like this for callers to think they can safely modify the pods that are returned. Immutability is usually the best design for thread-safe code, when it's possible.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78396#-:-MywLRWtCNiH7jzRJRar:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @JeffSwenson)

**Review by jeffswenson — APPROVED** [review]
LGTM

**Comment by jaylim-crl** [comment]
TFTR!

bors r=andy-kimball,JeffSwenson

**Pull request merged**
