### PR TITLE
vendor: Bump pebble to 6a4d448f0427bda9b583a33d033182fa5f34a132

### LINKED ISSUE #46366: storage/metamorphic: TestRocksPebbleRestarts failed
[(storage/metamorphic).TestRocksPebbleRestarts failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1820999&tab=buildLog) on [master@744bf8589528c9da8f717049446c0661d27b9c3c](https://github.com/cockroachdb/cockroach/commits/744bf8589528c9da8f717049446c0661d27b9c3c):

Fatal error:
```
panic: assignment to entry in nil map

```

Stack:
```
goroutine 4867 [running]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*tableCacheShard).findNode(0xc000566820, 0xc000512800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:305 +0x58a
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*tableCacheShard).newIters(0xc000566820, 0xc000512800, 0x0, 0xc000156478, 0x18, 0x18, 0xc000337ae0, 0x3, 0x0, 0xc000072a80)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:163 +0x4d
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*tableCache).newIters(0xc000565298, 0xc000512800, 0x0, 0xc000156478, 0xc0007ed408, 0x66dae8, 0x20, 0x1761b20, 0x1a25111, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:58 +0x78
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*compaction).newInputIter(0xc000156400, 0xc000276040, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:726 +0x904
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).runCompaction(0xc000565200, 0x2d, 0xc000156400, 0x1a457a0, 0x2653860, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1230 +0x411
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).compact1(0xc000565200, 0xc000156400, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1143 +0x42b
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).compact.func1(0x1a69c60, 0xc000185470)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1094 +0xbe
runtime/pprof.Do(0x1a69c60, 0xc000185470, 0xc0000d6100, 0x1, 0x1, 0xc000745f98)
	/usr/local/go/src/runtime/pprof/runtime.go:37 +0xf8
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).compact(0xc000565200, 0xc000156400, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1091 +0xa2
created by github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).maybeScheduleCompaction
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:1085 +0x3c2

```

<details><summary>Log preceding fatal error</summary><p>

```
I200320 13:56:00.913593 4796 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 27] MANIFEST deleted 000074
I200320 13:56:00.926818 4859 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 31] MANIFEST created 000080
I200320 13:56:00.926917 4859 vendor/github.com/cockroachdb/pebble/compaction.go:996  [JOB 31] flushed to L0 [000079] (1.2 K)
I200320 13:56:00.927215 4859 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 31] MANIFEST deleted 000077
I200320 13:56:00.933353 4679 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 29] MANIFEST created 000081
I200320 13:56:00.933501 4679 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 29] MANIFEST deleted 000080
I200320 13:56:00.933593 4679 vendor/github.com/cockroachdb/pebble/ingest.go:604  [JOB 29] ingested L0:000076 (1.2 K)
I200320 13:56:00.934339 4860 vendor/github.com/cockroachdb/pebble/compaction.go:1130  [JOB 32] compacting L0 [000079 000076] (2.4 K) + L6 [000075] (5.9 K)
I200320 13:56:00.934548 4860 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 32] compacting: sstable created 000082
I200320 13:56:00.943611 4679 vendor/github.com/cockroachdb/pebble/db.go:1306  [JOB 33] WAL created 000084 (recycled 000066)
I200320 13:56:00.944236 4870 vendor/github.com/cockroachdb/pebble/compaction.go:946  [JOB 35] flushing to L0
I200320 13:56:00.944755 4860 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 32] MANIFEST created 000083
I200320 13:56:00.944822 4860 vendor/github.com/cockroachdb/pebble/compaction.go:1168  [JOB 32] compacted L0 [000079 000076] (2.4 K) + L6 [000075] (5.9 K) -> L6 [000082] (5.8 K), in 0.0s, output rate 1.3 M/s
I200320 13:56:00.952713 4870 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 35] flushing: sstable created 000085
I200320 13:56:00.952743 4871 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 34] sstable deleted 000065
I200320 13:56:00.952873 4871 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 34] sstable deleted 000069
I200320 13:56:00.952947 4860 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 32] MANIFEST deleted 000081
I200320 13:56:00.954794 4863 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 36] sstable deleted 000075
I200320 13:56:00.954906 4863 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 36] sstable deleted 000076
I200320 13:56:00.954968 4863 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 36] sstable deleted 000079
I200320 13:56:00.963423 4870 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 35] MANIFEST created 000086
I200320 13:56:00.963486 4870 vendor/github.com/cockroachdb/pebble/compaction.go:996  [JOB 35] flushed to L0 [000085] (1.5 K)
I200320 13:56:00.964344 4870 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 35] MANIFEST deleted 000083
I200320 13:56:00.972620 4679 vendor/github.com/cockroachdb/pebble/db.go:1306  [JOB 37] WAL created 000087 (recycled 000072)
I200320 13:56:00.972785 4750 vendor/github.com/cockroachdb/pebble/compaction.go:946  [JOB 38] flushing to L0
I200320 13:56:00.975178 4750 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 38] flushing: sstable created 000088
I200320 13:56:00.979725 4679 vendor/github.com/cockroachdb/pebble/db.go:1306  [JOB 39] WAL created 000089 (recycled 000078)
I200320 13:56:00.986906 4750 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 38] MANIFEST created 000090
I200320 13:56:00.986973 4750 vendor/github.com/cockroachdb/pebble/compaction.go:996  [JOB 38] flushed to L0 [000088] (1.4 K)
I200320 13:56:00.987072 4750 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 38] MANIFEST deleted 000086
I200320 13:56:00.987192 4753 vendor/github.com/cockroachdb/pebble/compaction.go:1130  [JOB 40] compacting L0 [000085 000088] (2.9 K) + L6 [000082] (5.8 K)
I200320 13:56:00.987562 4753 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 40] compacting: sstable created 000091
I200320 13:56:00.988164 4752 vendor/github.com/cockroachdb/pebble/compaction.go:946  [JOB 41] flushing to L0
I200320 13:56:00.988274 4752 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 41] flushing: sstable created 000092
I200320 13:56:00.996777 4752 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 41] MANIFEST created 000093
I200320 13:56:00.996857 4752 vendor/github.com/cockroachdb/pebble/compaction.go:996  [JOB 41] flushed to L0 [000092] (1.2 K)
I200320 13:56:00.997475 4752 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 41] MANIFEST deleted 000090
I200320 13:56:00.998066 4679 vendor/github.com/cockroachdb/pebble/db.go:1306  [JOB 42] WAL created 000094 (recycled 000084)
I200320 13:56:00.998222 4756 vendor/github.com/cockroachdb/pebble/compaction.go:946  [JOB 43] flushing to L0
I200320 13:56:00.998346 4756 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 43] flushing: sstable created 000096
I200320 13:56:01.012599 4753 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 40] MANIFEST created 000095
I200320 13:56:01.012698 4753 vendor/github.com/cockroachdb/pebble/compaction.go:1168  [JOB 40] compacted L0 [000085 000088] (2.9 K) + L6 [000082] (5.8 K) -> L6 [000091] (6.2 K), in 0.0s, output rate 1.4 M/s
I200320 13:56:01.012827 4753 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 40] MANIFEST deleted 000093
I200320 13:56:01.013490 4800 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 44] sstable deleted 000082
I200320 13:56:01.013708 4800 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 44] sstable deleted 000085
I200320 13:56:01.013822 4800 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 44] sstable deleted 000088
I200320 13:56:01.029574 4756 vendor/github.com/cockroachdb/pebble/version_set.go:421  [JOB 43] MANIFEST created 000097
I200320 13:56:01.029656 4756 vendor/github.com/cockroachdb/pebble/compaction.go:996  [JOB 43] flushed to L0 [000096] (1.5 K)
I200320 13:56:01.029773 4756 vendor/github.com/cockroachdb/pebble/compaction.go:1851  [JOB 43] MANIFEST deleted 000095
I200320 13:56:01.036107 4867 vendor/github.com/cockroachdb/pebble/compaction.go:1130  [JOB 45] compacting L0 [000092 000096] (2.7 K) + L6 [000091] (6.2 K)

```

</p></details>

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestRocksPebbleRestarts PKG=./pkg/storage/metamorphic TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRocksPebbleRestarts.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by itsbilal**
Changes:
 - compaction: Check closed flag after logLock returns
 - db: fix comment grammar
 - fix doc for Skiplist.NewIter

Fixes #46366.

Release justification: Bug fixes in pebble.
Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by itsbilal** [comment]
TFTR!

bors r+

**Comment by itsbilal** [comment]
Logictest timeout.

bors r+

**Comment by itsbilal** [comment]
🤔

bors r+

**Comment by itsbilal** [comment]
It didn't retry

bors r+

**Pull request merged**
