### PR TITLE
telemetry: add feature-usage counters and registry

### PR DESCRIPTION
**Pull request by dt**
This is a prototype feature usage counter and registry, to allow easy
any given feature or code path to easily record that it was hit without
additional work required in the rest of the telemetry pipeline.

The registry is global for now, to avoid significant plumbing and mess
until we validate this is useful. Singletons often complicate testing
but this registry's contents should not affect behavior, so some of
those drawbacks are less applicable than in other sitations.

If this pattern does prove useful, future work may need to find a more
compact means of storing and transmitting bundled counts than their
verbose string names -- perhaps moving the most common keys to fields of
a pre-defined proto. Additionally, a lock-free map may provide superior
performance compared to the lock-protected map.

Release note: none.

### CODE REVIEW

**Comment by knz** [comment]
woo nice to have a proto already! I'll have a look shortly when I am done fixing my computer.

An early remark: as I have mentioned to you earlier I am not fan of neither a map (the cumulative lookup complexity is non-negligible) and a global lock (contention). I could be convinced otherwise by a microbenchmark that, says, has 100 goroutines concurrently increasing 50 feature-counters.

**Comment by dt** [comment]
@knz so I want to validate that this is a useful feature / pattern before we invest in more complicated performance optimizations. That said, I did include an accessor that only holds the lock long enough to return the `*int`, on which the caller can then do all the atomic increments it wants without contention -- e.g. you could have just a one-time locked map access at init, then no contention after that. We could also look at a lock-free hashmap implementation, but again, I want to wait until we actually see a need before going too far down the optimization path.

**Comment by dt** [comment]
@knz does that seem like it mitigates some of your concerns (letting latency-sensitive callers hold on to a *int and inc it directly)?

**Review by knz — DISMISSED** [review]
Base code LGTM.

Remaining concern is about the reporting protobuf.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27103#-:-LH3bdGA9SxNgYT0Oind:b-513ilo)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/diagnosticspb/diagnostics.proto, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27103#-LH3bNDY5U4qAKMLiAtL:-LH3bNDZ-DQMQESX849C:b-fc7rec) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3f0d702192dca2d1f3c71c287b40f09e1ceff40/pkg/server/diagnosticspb/diagnostics.proto#L34)):*
> ```protobuf
>   map<string, int64> error_counts = 7;
>   map<int64, config.ZoneConfig> zone_configs = 8 [(gogoproto.nullable) = false];
>   map<string, int32> feature_usage = 9 [(gogoproto.nullable) = false];
> ```

As discussed before this map can get insanely large. I might recommend sending a map of array index to name just once, then an array of counters (where each array position is named after the initial map) in each event after that.

**Comment by dt** [comment]
I think we can optimize the map encoding _if/when it gets large_ rather than right away.

I'm not excited about just sending arrays of ints since tracking which offsets mean what to which clients could get complicated -- yes, a given client could send its mapping at startup, but then we need to keep track of who has sent what. If/when the map becomes giant, then something like that might become worth the extra complexity/risk but it seems like premature overkill to do it now?

In the medium term, as the map grows, I think we could add a proto with statically defined fields for the most common counters (i.e. those that usually appear in the majority of reports). When clients send reports, they'd set those fields in that proto rather than add those keys to the map. Proto is a pretty compact encoding for handing around lots and lots of fields, rather than rolling our own with the associated cost and risk.

**Comment by knz** [comment]
> Proto is a pretty compact encoding for handing around lots and lots of fields, rather than rolling our own with the associated cost and risk.

D'oh! I had forgotten about that, and another part of the discussion we had three weeks ago.

Given that we should (and will!) restrict counter names to be string literals throughout the source base, we can generate a protobuf spec with all the counters, and a function that collects them all and populates the protobuf (i.e. something like

```go
func populate(p *pb.Thing) {
   counters.RLock()
   // autogenerated code follows  
   p.Field1 = *counters["field1"].m
   p.Field2 = *counters["field2"].m
   p.Field3 = *counters["field3"].m
   p.Field4 = *counters["field4"].m
   p.Field5 = *counters["field5"].m
   ...
   counters.RUnlock()
}
```

) this would get us a superfast and super-compact collection event.

**Comment by dt** [comment]
@knz are there any changes/optimizations you think we need to make *now*, or do you think we can wait to do these once it grows?

**Comment by knz** [comment]
yes these can wait!

**Comment by knz** [comment]
LGTM

**Pull request merged**
