### PR TITLE
exec: Fix test case TestTraceFieldDecomposition.

### PR DESCRIPTION
**Pull request by rohany**
Fix test case TestTraceFieldDecomposition, addressed in #38935

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

What is the expected and the actual output before this change (if you happen to have it somewhere)?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39027#-:-LkPtvBcADmma270FRaO:bsgvaj1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by rohany** [comment]
The test fails here because the automatic string conversion of the core union has a whitespace at the end of it, which is one thing that the test is checking for -- this makes sure that this isn't the case.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39027)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39027#-LkPvMCI3SU_-wKaWfbl:-LkPvMCI3SU_-wKaWfbm:b-yfba7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6441e8bf88b73834b3905d77e9b00db315380d5a/pkg/sql/distsqlrun/column_exec_setup.go#L500)):*
> ```Go
> 
> 	default:
> 		return nil, nil, memUsage, errors.Newf("unsupported processor core %s", strings.TrimSpace(core.String()))
> ```

Hm, why doesn't the equivalent line in `processors.go` need a call to `TrimSpace`?
https://github.com/cockroachdb/cockroach/blob/e2e2c67afd8547f98a7c9225cc440458384cb3e3/pkg/sql/distsqlrun/processors.go#L1199
Does the difference come from using `errors.Newf` in one place and `errors.Errorf` in the other? Not really a big deal but we might as well make the code match.

**Pull request merged**
