### PR TITLE
bulkio: Move target resolution code into backupbase package.

### PR DESCRIPTION
**Pull request by miretskiy**
A code movement refactoring which moves methods accessible
from outside of backupccl (currently ResolveTargetsToDescriptors) into
a separate backupbase package. Because of various dependencies,
most supporting functions, including system schema backup/restore
information are also moved into backupbase.

This is a pure code movement to avoid dependency cycles between
backupccl and changefeedccl. Now, all cross package dependencies
live in backupbase and changefeedbase respectively.

Release Notes: None

### CODE REVIEW

**Review by pbardea — APPROVED** [review]
:lgtm: with a couple of minor comments/question

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-:-MSeILrlCoODCickiPNs:b5q3mzn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/backup_destination.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MSeGqUH1BGwr9em3R54:-MSeGqUI89ZcXYp78OeB:b-gsnxvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57fd860a5ea4de38cfc35b04a44efb0a2698743/pkg/ccl/backupccl/backup_destination.go#L169)):*
> ```Go
> 		i := i
> 		g.GoCtx(func(ctx context.Context) error {
> 			// TODO(lucy): We may want to upgrade the table Descs to the newer
> ```

Looks like this and a few other `descs` got caught in a refactor and changed to `Descs`.
___
*[pkg/ccl/backupccl/targets_test.go, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MSeHQXpE3uEZeXyy0SK:-MSeHQXpE3uEZeXyy0SL:b-5lg2xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57fd860a5ea4de38cfc35b04a44efb0a2698743/pkg/ccl/backupccl/targets_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package backupccl
> ```

Does it make sense to move this over to `backupbase`?

**Review by pbardea — COMMENTED** [review]
I also think that we still need ccl init?

> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-:-MSeIsA1A6ZR4DrLSXI5:b-ik77w3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

**Review by pbardea — COMMENTED** [review]
I did a quick pass through looking for those pesky Desc changes. Looks like there's a couple of more strays.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-:-MShY_JS1VTen6q05mVm:b-izdywe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/restore_planning.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShY2SC9PAU_mQ291to:-MShY2SC9PAU_mQ291tp:bg1r8lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/restore_planning.go#L421)):*
> ```Go
> 					}
> 					// Write a schema descriptor rewrite so that we can remap all
> 					// temporary table Descs which were under the original session
> ```

(another desc -> Descs)
___
*[pkg/ccl/backupccl/restore_planning.go, line 1542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShY7ht5ww-o9R6iwb4:-MShY7ht5ww-o9R6iwb5:bg1r8lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/restore_planning.go#L1542)):*
> ```Go
> 
> 	// Ensure that no user table descriptors exist for a full cluster restore.
> 	txn := p.ExecCfg().DB.NewTxn(ctx, "count-user-Descs")
> ```

(another desc -> Descs)
___
*[pkg/ccl/backupccl/targets.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShYGVg-90BLBQ4YNGT:-MShYGVg-90BLBQ4YNGU:bg1r8lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/targets.go#L32)):*
> ```Go
> 
> // getRelevantDescChanges finds the changes between start and end time to the
> // SQL descriptors matching `Descs` or `expandedDBs`, ordered by time. A
> ```

(another desc -> Descs)
___
*[pkg/ccl/backupccl/targets.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShYG-7-5aSNYeiks8L:-MShYG-7-5aSNYeiks8M:bg1r8lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/targets.go#L34)):*
> ```Go
> // SQL descriptors matching `Descs` or `expandedDBs`, ordered by time. A
> // descriptor revision matches if it is an earlier revision of a descriptor in
> // Descs (same ID) or has parentID in `expanded`. Deleted descriptors are
> ```

(another desc -> Descs)
___
*[pkg/ccl/backupccl/targets.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShYEpP8sb_lyzRhEup:-MShYEpP8sb_lyzRhEuq:bg1r8lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/targets.go#L54)):*
> ```Go
> 
> 	// If no descriptors changed, we can just stop now and have RESTORE use the
> 	// normal list of Descs (i.e. as of endTime).
> ```

(another desc -> Descs)

**Review by miretskiy — COMMENTED** [review]
Yup.  Was removed by accident.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-:-MSefWs334tYL7OIvIM1:b-rxpatw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_destination.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MSeGqUH1BGwr9em3R54:-MSefq832dfwAuoCdKiC:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57fd860a5ea4de38cfc35b04a44efb0a2698743/pkg/ccl/backupccl/backup_destination.go#L169)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Looks like this and a few other `descs` got caught in a refactor and changed to `Descs`.
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/restore_planning.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShY2SC9PAU_mQ291to:-MShnj-Y1ocYyEJ8-HMF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/restore_planning.go#L421)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

(another desc -> Descs)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_planning.go, line 1542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShY7ht5ww-o9R6iwb4:-MShnjLx2gGttm2e-eAD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/restore_planning.go#L1542)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

(another desc -> Descs)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShYGVg-90BLBQ4YNGT:-MShnsuS8byzUka3i1ae:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/targets.go#L32)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

(another desc -> Descs)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShYG-7-5aSNYeiks8L:-MShntBP5tXpoSX4y8f7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/targets.go#L34)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

(another desc -> Descs)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MShYEpP8sb_lyzRhEup:-MShnx8X4XSErkrdauRL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f9e3e88bd2e52faa351c5cefb455adb16d34/pkg/ccl/backupccl/targets.go#L54)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

(another desc -> Descs)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets_test.go, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59787#-MSeHQXpE3uEZeXyy0SK:-MSefiGS4oJSyx4MRh3i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57fd860a5ea4de38cfc35b04a44efb0a2698743/pkg/ccl/backupccl/targets_test.go#L9)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Does it make sense to move this over to `backupbase`?
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]

**Pull request merged**
