### PR TITLE
batcheval: Work around time-bound iterator bug in RefreshRange

### LINKED ISSUE #31823: production: qps stalls on adriatic
I deployed a new v2.1 release candidate a couple hours ago, and adriatic has had some qps stalls since (it also had some before the push, on yesterday's release candidate, too though):

<img width="930" alt="screen shot 2018-10-24 at 2 16 39 pm" src="https://user-images.githubusercontent.com/7085343/47455481-8ff48380-d797-11e8-9d1f-fa3fbf5b1e7d.png">

I was able to grab the queries that are stuck this time around. They don't change across multiple `SHOW QUERIES` calls:

```sql
root@:26257/defaultdb> select * from [show queries] order by start limit 10;
              query_id             | node_id | user_name |              start               |                                                                                                                    query                                                                                                                     | client_address  | application_name | distributed |   phase
+----------------------------------+---------+-----------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+-------------+-----------+
  1560a13726f6cf9a0000000000000006 |       6 | root      | 2018-10-24 19:12:10.809581+00:00 | UPDATE "order" SET o_carrier_id = 6 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((2, 227105), (3, 227939), (5, 227362), (8, 227767), (9, 227020), (1, 228429), (4, 226625), (6, 227548), (7, 227412), (10, 228144))) RETURNING o_d_id, o_c_id  | 127.0.0.1:57286 |                  |    false    | executing
  1560a137446e3dbc0000000000000006 |       6 | root      | 2018-10-24 19:12:11.301989+00:00 | UPDATE "order" SET o_carrier_id = 4 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((7, 227412), (8, 227767), (10, 228144), (1, 228429), (3, 227939), (4, 226625), (6, 227548), (2, 227105), (5, 227362), (9, 227020))) RETURNING o_d_id, o_c_id  | 127.0.0.1:57268 |                  |    false    | executing
  1560a137d084fc280000000000000004 |       4 | root      | 2018-10-24 19:12:13.654228+00:00 | SELECT count(*) FROM (SELECT DISTINCT s_i_id FROM order_line JOIN stock ON (s_i_id = ol_i_id) AND (s_w_id = ol_w_id) WHERE (((ol_w_id = 9) AND (ol_d_id = 7)) AND (ol_o_id BETWEEN (227432 - 20) AND (227432 - 1))) AND (s_quantity < 16))   | 127.0.0.1:56480 |                  |    true     | executing
  1560a137f99ce9840000000000000005 |       5 | root      | 2018-10-24 19:12:14.343641+00:00 | UPDATE "order" SET o_carrier_id = 7 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((8, 227768), (9, 227021), (1, 228430), (3, 227940), (5, 227363), (6, 227549), (7, 227413), (10, 228145), (2, 227106), (4, 226626))) RETURNING o_d_id, o_c_id  | 127.0.0.1:34926 |                  |    false    | executing
  1560a137feac302e0000000000000004 |       4 | root      | 2018-10-24 19:12:14.428539+00:00 | UPDATE "order" SET o_carrier_id = 3 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((3, 227940), (4, 226626), (5, 227363), (10, 228145), (1, 228430), (2, 227106), (6, 227549), (7, 227413), (8, 227768), (9, 227021))) RETURNING o_d_id, o_c_id  | 127.0.0.1:56486 |                  |    false    | executing
  1560a138c42aca6a0000000000000003 |       3 | root      | 2018-10-24 19:12:17.741935+00:00 | SELECT count(*) FROM (SELECT DISTINCT s_i_id FROM order_line JOIN stock ON (s_i_id = ol_i_id) AND (s_w_id = ol_w_id) WHERE (((ol_w_id = 9) AND (ol_d_id = 5)) AND (ol_o_id BETWEEN (227380 - 20) AND (227380 - 1))) AND (s_quantity < 14))   | 127.0.0.1:35326 |                  |    true     | executing
  1560a13f74022c600000000000000006 |       6 | root      | 2018-10-24 19:12:46.461861+00:00 | UPDATE "order" SET o_carrier_id = 10 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((2, 227115), (3, 227949), (5, 227372), (7, 227422), (8, 227777), (9, 227030), (10, 228154), (1, 228439), (4, 226635), (6, 227558))) RETURNING o_d_id, o_c_id | 127.0.0.1:57284 |                  |    false    | executing
  1560a13fb978cf620000000000000006 |       6 | root      | 2018-10-24 19:12:47.627277+00:00 | UPDATE "order" SET o_carrier_id = 10 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((6, 227559), (8, 227778), (9, 227031), (10, 228155), (1, 228440), (2, 227116), (3, 227950), (4, 226636), (5, 227373), (7, 227423))) RETURNING o_d_id, o_c_id | 127.0.0.1:57288 |                  |    false    | executing
  1560a1405ca733470000000000000004 |       4 | root      | 2018-10-24 19:12:50.365056+00:00 | UPDATE "order" SET o_carrier_id = 5 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((3, 227950), (4, 226636), (5, 227373), (7, 227423), (9, 227031), (10, 228155), (1, 228440), (2, 227116), (6, 227559), (8, 227778))) RETURNING o_d_id, o_c_id  | 127.0.0.1:56482 |                  |    false    | executing
  1560a1437024a1180000000000000001 |       1 | root      | 2018-10-24 19:13:03.576917+00:00 | UPDATE "order" SET o_carrier_id = 10 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((1, 228443), (4, 226639), (5, 227376), (6, 227562), (9, 227034), (2, 227119), (3, 227953), (7, 227426), (8, 227781), (10, 228158))) RETURNING o_d_id, o_c_id | 127.0.0.1:33552 |                  |    false    | executing
(10 rows)

Time: 8.425971ms

root@:26257/defaultdb> select * from [show queries] order by start limit 25;
              query_id             | node_id | user_name |              start               |                                                                                                                                                                                                                                                                                                  query                                                                                                                                                                                                                                                                                                  | client_address  | application_name | distributed |   phase
+----------------------------------+---------+-----------+----------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+-------------+-----------+
  1560a13726f6cf9a0000000000000006 |       6 | root      | 2018-10-24 19:12:10.809581+00:00 | UPDATE "order" SET o_carrier_id = 6 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((2, 227105), (3, 227939), (5, 227362), (8, 227767), (9, 227020), (1, 228429), (4, 226625), (6, 227548), (7, 227412), (10, 228144))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:57286 |                  |    false    | executing
  1560a137446e3dbc0000000000000006 |       6 | root      | 2018-10-24 19:12:11.301989+00:00 | UPDATE "order" SET o_carrier_id = 4 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((7, 227412), (8, 227767), (10, 228144), (1, 228429), (3, 227939), (4, 226625), (6, 227548), (2, 227105), (5, 227362), (9, 227020))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:57268 |                  |    false    | executing
  1560a137d084fc280000000000000004 |       4 | root      | 2018-10-24 19:12:13.654228+00:00 | SELECT count(*) FROM (SELECT DISTINCT s_i_id FROM order_line JOIN stock ON (s_i_id = ol_i_id) AND (s_w_id = ol_w_id) WHERE (((ol_w_id = 9) AND (ol_d_id = 7)) AND (ol_o_id BETWEEN (227432 - 20) AND (227432 - 1))) AND (s_quantity < 16))                                                                                                                                                                                                                                                                                                                                                              | 127.0.0.1:56480 |                  |    true     | executing
  1560a137f99ce9840000000000000005 |       5 | root      | 2018-10-24 19:12:14.343641+00:00 | UPDATE "order" SET o_carrier_id = 7 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((8, 227768), (9, 227021), (1, 228430), (3, 227940), (5, 227363), (6, 227549), (7, 227413), (10, 228145), (2, 227106), (4, 226626))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:34926 |                  |    false    | executing
  1560a137feac302e0000000000000004 |       4 | root      | 2018-10-24 19:12:14.428539+00:00 | UPDATE "order" SET o_carrier_id = 3 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((3, 227940), (4, 226626), (5, 227363), (10, 228145), (1, 228430), (2, 227106), (6, 227549), (7, 227413), (8, 227768), (9, 227021))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:56486 |                  |    false    | executing
  1560a138c42aca6a0000000000000003 |       3 | root      | 2018-10-24 19:12:17.741935+00:00 | SELECT count(*) FROM (SELECT DISTINCT s_i_id FROM order_line JOIN stock ON (s_i_id = ol_i_id) AND (s_w_id = ol_w_id) WHERE (((ol_w_id = 9) AND (ol_d_id = 5)) AND (ol_o_id BETWEEN (227380 - 20) AND (227380 - 1))) AND (s_quantity < 14))                                                                                                                                                                                                                                                                                                                                                              | 127.0.0.1:35326 |                  |    true     | executing
  1560a13f74022c600000000000000006 |       6 | root      | 2018-10-24 19:12:46.461861+00:00 | UPDATE "order" SET o_carrier_id = 10 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((2, 227115), (3, 227949), (5, 227372), (7, 227422), (8, 227777), (9, 227030), (10, 228154), (1, 228439), (4, 226635), (6, 227558))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                            | 127.0.0.1:57284 |                  |    false    | executing
  1560a13fb978cf620000000000000006 |       6 | root      | 2018-10-24 19:12:47.627277+00:00 | UPDATE "order" SET o_carrier_id = 10 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((6, 227559), (8, 227778), (9, 227031), (10, 228155), (1, 228440), (2, 227116), (3, 227950), (4, 226636), (5, 227373), (7, 227423))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                            | 127.0.0.1:57288 |                  |    false    | executing
  1560a1405ca733470000000000000004 |       4 | root      | 2018-10-24 19:12:50.365056+00:00 | UPDATE "order" SET o_carrier_id = 5 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((3, 227950), (4, 226636), (5, 227373), (7, 227423), (9, 227031), (10, 228155), (1, 228440), (2, 227116), (6, 227559), (8, 227778))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:56482 |                  |    false    | executing
  1560a1437024a1180000000000000001 |       1 | root      | 2018-10-24 19:13:03.576917+00:00 | UPDATE "order" SET o_carrier_id = 10 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((1, 228443), (4, 226639), (5, 227376), (6, 227562), (9, 227034), (2, 227119), (3, 227953), (7, 227426), (8, 227781), (10, 228158))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                            | 127.0.0.1:33552 |                  |    false    | executing
  1560a143d9da68480000000000000003 |       3 | root      | 2018-10-24 19:13:05.350421+00:00 | UPDATE "order" SET o_carrier_id = 8 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((3, 227954), (4, 226640), (5, 227377), (10, 228159), (1, 228444), (2, 227120), (6, 227563), (7, 227427), (8, 227782), (9, 227035))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:35344 |                  |    false    | executing
  1560a144845952500000000000000004 |       4 | root      | 2018-10-24 19:13:08.210875+00:00 | UPDATE "order" SET o_carrier_id = 7 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((1, 228444), (3, 227954), (5, 227377), (6, 227563), (8, 227782), (9, 227035), (2, 227120), (4, 226640), (7, 227427), (10, 228159))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:56474 |                  |    false    | executing
  1560a1468ddd2cf00000000000000006 |       6 | root      | 2018-10-24 19:13:16.960368+00:00 | UPDATE "order" SET o_carrier_id = 7 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((6, 227565), (8, 227784), (9, 227037), (1, 228446), (5, 227379), (4, 226642), (7, 227429), (10, 228161), (2, 227122), (3, 227956))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:57294 |                  |    false    | executing
  1560a146958370b50000000000000006 |       6 | root      | 2018-10-24 19:13:17.088795+00:00 | UPDATE "order" SET o_carrier_id = 10 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((3, 227956), (4, 226642), (6, 227565), (9, 227037), (10, 228161), (1, 228446), (2, 227122), (5, 227379), (7, 227429), (8, 227784))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                            | 127.0.0.1:57280 |                  |    false    | executing
  1560a146c6193c7e0000000000000002 |       2 | root      | 2018-10-24 19:13:17.90368+00:00  | UPDATE customer SET (c_balance, c_ytd_payment, c_payment_cnt, c_data) = (c_balance - 370.680000, c_ytd_payment + 370.680000, c_payment_cnt + 1, CASE c_credit WHEN 'BC' THEN left((((((c_id::STRING || c_d_id::STRING) || c_w_id::STRING) || 10::STRING) || 2::STRING) || 370.680000::STRING) || c_data, 500) ELSE c_data END) WHERE ((c_w_id = 9) AND (c_d_id = 1)) AND (c_id = 2400) RETURNING c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, c_zip, c_phone, c_since, c_credit, c_credit_lim, c_discount, c_balance, CASE c_credit WHEN 'BC' THEN left(c_data, 200) ELSE '' END | 127.0.0.1:56588 |                  |    false    | executing
  1560a146cd5774f00000000000000003 |       3 | root      | 2018-10-24 19:13:18.02542+00:00  | UPDATE "order" SET o_carrier_id = 7 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((6, 227565), (7, 227429), (8, 227784), (9, 227037), (10, 228161), (2, 227122), (3, 227956), (5, 227379), (1, 228446), (4, 226642))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:35352 |                  |    false    | executing
  1560a146d84fa2de0000000000000001 |       1 | root      | 2018-10-24 19:13:18.209458+00:00 | SELECT w_tax FROM warehouse WHERE w_id = 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 127.0.0.1:33550 |                  |    false    | executing
  1560a146db875da70000000000000002 |       2 | root      | 2018-10-24 19:13:18.263428+00:00 | UPDATE warehouse SET w_ytd = w_ytd + 1308.050000 WHERE w_id = 2 RETURNING w_name, w_street_1, w_street_2, w_city, w_state, w_zip                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 127.0.0.1:56596 |                  |    false    | executing
  1560a146de14faff0000000000000003 |       3 | root      | 2018-10-24 19:13:18.306123+00:00 | UPDATE warehouse SET w_ytd = w_ytd + 3573.310000 WHERE w_id = 2 RETURNING w_name, w_street_1, w_street_2, w_city, w_state, w_zip                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 127.0.0.1:35342 |                  |    false    | executing
  1560a146e4192aec0000000000000006 |       6 | root      | 2018-10-24 19:13:18.407267+00:00 | SELECT w_tax FROM warehouse WHERE w_id = 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 127.0.0.1:57290 |                  |    false    | executing
  1560a146fc7d137a0000000000000006 |       6 | root      | 2018-10-24 19:13:18.79744+00:00  | SELECT w_tax FROM warehouse WHERE w_id = 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 127.0.0.1:57298 |                  |    false    | executing
  1560a147021c0d8a0000000000000004 |       4 | root      | 2018-10-24 19:13:18.910703+00:00 | UPDATE "order" SET o_carrier_id = 4 WHERE (o_w_id = 9) AND ((o_d_id, o_id) IN ((5, 227380), (7, 227430), (2, 227123), (3, 227957), (4, 226643), (9, 227038), (10, 228162), (1, 228447), (6, 227566), (8, 227785))) RETURNING o_d_id, o_c_id                                                                                                                                                                                                                                                                                                                                                             | 127.0.0.1:56456 |                  |    false    | executing
  1560a1470a249c140000000000000005 |       5 | root      | 2018-10-24 19:13:19.04557+00:00  | SELECT w_tax FROM warehouse WHERE w_id = 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 127.0.0.1:34916 |                  |    false    | executing
  1560a1470cae87240000000000000001 |       1 | root      | 2018-10-24 19:13:19.08817+00:00  | SELECT w_tax FROM warehouse WHERE w_id = 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 127.0.0.1:33526 |                  |    false    | executing
  1560a1470fcaaa8a0000000000000005 |       5 | root      | 2018-10-24 19:13:19.140293+00:00 | SELECT d_next_o_id FROM district WHERE (d_w_id = 2) AND (d_id = 6)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 127.0.0.1:34904 |                  |    false    | executing
(25 rows)

Time: 21.42194ms
```

There are only two "problem ranges", and they're both just non-active leases from a node's previous liveness epoch; nothing too suspicious.

I'm continuing to investigate.

### PR DESCRIPTION
**Pull request by bdarnell**
Updates #28358
Fixes #31823

Release note (bug fix): Fix long stalls that can occur in contended
transactions.

### CODE REVIEW

**Comment by petermattis** [comment]
I'm fine with this hack if it works, though we need to develop a test which demonstrates this fixes the problem. [`TestMVCCIncrementalIteratorIntentStraddlesSStables`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/storageccl/engineccl/mvcc_test.go#L344) shows how to set up a test with a particular table structure. A targeted test which set up the correct structure and then called `RefreshRange` seems feasible (i.e. no store, server, cluster, etc).

**Review by benesch — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32211)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_refresh_range.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32211#-LR89-KCDCQZLMT2Xz7B:-LR89-KCDCQZLMT2Xz7C:b-ajp60n) ([raw file](https://github.com/cockroachdb/cockroach/blob/971a12bde7079ec8fb9564b185f927b0ab150fc7/pkg/storage/batcheval/cmd_refresh_range.go#L112)):*
> ```Go
> 				continue
> 			}
> 		} else { // Range intent
> ```

These are coming from disk, so I'm not seeing how they could ever be range intents. But I'm also entirely unfamiliar with where we do use range intents.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32211)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_refresh_range.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32211#-LR89-KCDCQZLMT2Xz7B:-LR8IyMmCl2VMRtGksIm:b1m0v6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/971a12bde7079ec8fb9564b185f927b0ab150fc7/pkg/storage/batcheval/cmd_refresh_range.go#L112)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

These are coming from disk, so I'm not seeing how they could ever be range intents. But I'm also entirely unfamiliar with where we do use range intents.
</blockquote></details>

Right. Fixed.

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32211#-:-LR8Q5YU7i982yppxzNk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by bdarnell** [comment]
bors r=benesch

**Pull request merged**
