### PR TITLE
sql: separate pausable portal code paths in `execStmtInOpenState`

### LINKED ISSUE #135908: sql: reduce allocs in execStmtInOpenState [~5% allocs]
Under sysbench oltp_read_only this shows up very prominently, as one of the top hitters in `peek`:

```
Type: alloc_objects
Time: 2024-11-21 13:25:41 CET
Duration: 30.17s, Total samples = 158593784 
Showing nodes accounting for 158593784, 100% of 158593784 total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                           2031648   100% |   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1 pkg/sql/conn_executor_exec.go:141
   2031648  1.28%  9.75%    2031648  1.28%                | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState pkg/sql/conn_executor_exec.go:275
----------------------------------------------------------+-------------
```

image

I'm not actually sure which one is right (does this function allocate 2031648 times or 5072675 times which is 2.5x of the former?) but it's clear that it allocates all over the place. Summing up the "Total:" lines in the listing[^sum] gives 5807416 which is yet another number, but it's close to the latter. So, we think this is around 2.5*1.28% or around 5%! Much of that seems avoidable at first glance and someone should spend some quality time with this code.

[^sum]: `$ grep 'Total' src.txt | awk '{ print $2 }' | grep -E '[0-9]+' | perl -lne '$x += $_; END { print $x; }'
5807416`

Even its three return parameters leak to the heap (because they are named and get passed to all kinds of functions inside of execStmtInOpenState). You can see this [here](https://gist.github.com/tbg/eef959086c67d27c755ea12d8c33d6d3#file-source-txt-L13) alongside all the other allocations.

I was so confused by this that I used `scripts/goescape` which also told me that the `ctx` arg gets moved to the heap:

```
./conn_executor_exec.go:276:2: moved to heap: ctx
./conn_executor_exec.go:282:4: moved to heap: retEv
./conn_executor_exec.go:282:21: moved to heap: retPayload
./conn_executor_exec.go:282:50: moved to heap: retErr
```

presumably because `ctx` is leaked into the `portal` [here](https://github.com/cockroachdb/cockroach/blob/6a7b1e20e70c0ba8e6bb7a42d52512d9437cd75b/pkg/sql/conn_executor_exec.go#L348-L351).

Epic: CRDB-42584

Jira issue: CRDB-44787

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: add `(*connExecutor).execStmtInOpenStateWithPausablePortal`

The `execStmtInOpenStateWithPausablePortal` method has been added to
`connExecutor`. It is currently an exact copy of `execStmtInOpenState`.
Future commits will simplify both methods.

Release note: None

#### sql: remove `isPausablePortal` anonymous function in `execStmtInOpenStateWithPortal`

Release note: None

#### sql: remove pausable-portal-specific code paths in `execStmtInOpenState`

Release note: None

#### sql: remove `processCleanupFunc` in `execStmtInOpenState`

Fixes #135908

Release note: None

#### sql: remove `portal` parameter from `execStmtInOpenState`

Release note: None

#### sql: remove `localVars` struct in `execStmtInOpenState`

Refactoring in previous commits has prevented all the `localVars`
variables from escaping to the heap, except for `cancelQuery`. So the
struct is no longer needed. Removing it reduces the size of heap
allocations, since the entire struct was heap allocated previously.

Release note: None

#### sql: refactor errors in `execStmtInOpenState`

Release note: None

#### sql: add metamorphic test variable to force pausable portal logic

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This PR is a prototype showing the benefits of removing pausable-portal-specific logic in the `execStmtInOpenState`. The pausable-portal specific code in `execStmtInOpenState` adds quite a bit of overhead, especially in heap allocations. Since pausable portals are not used in the common case—`multiple_active_portals_enabled` is disabled by default—ideally we would not have to pay the price of that overhead.

This PR essentially splits `execStmtInOpenState` into two functions: one that doesn't deal with pausable portals at all, and one that does. I measured a fairly respectable performance improvement from this change (the benchmarks below are simple read-only queries of empty tables that highlight execution overhead). As an added benefit, the function that doesn't have pausable portal logic is now a bit simpler for a human to reason about.

```
name                                     old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple        192µs ± 3%     184µs ± 2%  -3.75%  (p=0.000 n=20+20)
EndToEnd/kv-read/vectorize=on/Prepared      133µs ± 4%     127µs ± 4%  -4.15%  (p=0.000 n=20+20)
EndToEnd/kv-read/vectorize=off/Simple       211µs ± 1%     205µs ± 1%  -2.96%  (p=0.000 n=16+16)
EndToEnd/kv-read/vectorize=off/Prepared     134µs ± 6%     130µs ± 7%  -2.94%  (p=0.010 n=20+20)

name                                     old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Simple       32.1kB ± 8%    31.4kB ± 9%  -2.14%  (p=0.009 n=20+20)
EndToEnd/kv-read/vectorize=on/Prepared     20.2kB ± 0%    19.5kB ± 0%  -3.17%  (p=0.000 n=16+17)
EndToEnd/kv-read/vectorize=off/Simple      32.5kB ± 0%    31.9kB ± 0%  -2.00%  (p=0.000 n=18+18)
EndToEnd/kv-read/vectorize=off/Prepared    21.4kB ± 0%    21.1kB ± 9%  -1.58%  (p=0.001 n=16+18)

name                                     old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple          295 ± 3%       283 ± 4%  -4.03%  (p=0.000 n=17+17)
EndToEnd/kv-read/vectorize=on/Prepared        207 ± 0%       195 ± 0%  -5.78%  (p=0.000 n=17+17)
EndToEnd/kv-read/vectorize=off/Simple         286 ± 0%       274 ± 0%  -4.20%  (p=0.000 n=17+16)
EndToEnd/kv-read/vectorize=off/Prepared       199 ± 0%       187 ± 0%  -6.21%  (p=0.000 n=13+17)
```

My understanding of pausable portals is limited, and there is an open question of whether or not this change is valid (cc'ing @ZhouXing19 who might have some answers). My first question is: can the `execStmtInOpenState` function be invoked more than once for a single statement when executed with pausable portals? If so, I'm not sure this will behave correctly in edge cases where a pausable portal is started and paused, `multiple_active_portals_enabled` is disabled, and execution of the portal continues.

**Comment by DrewKimball** [comment]
>My understanding of pausable portals is limited, and there is an open question of whether or not this change is valid (cc'ing @ZhouXing19 who might have some answers). My first question is: can the execStmtInOpenState function be invoked more than once for a single statement when executed with pausable portals? If so, I'm not sure this will behave correctly in edge cases where a pausable portal is started and paused, multiple_active_portals_enabled is disabled, and execution of the portal continues.

The one case I can think of where a statement can be executed across multiple `execStmtInOpenState` calls is a stored procedure with `COMMIT` or `ROLLBACK`.

**Comment by yuzefovich** [comment]
Let me provide some context. Pausable portals machinery supports the extended PGWire protocol where an execution of a single prepared portal can be paused (by sending `Execute` command with `Limit` set), with all the query resources being kept alive, followed by a transition to executing different stmts / portals, and at some point in the future we can come back to "resume" the paused portal execution by sending another `Execute` command. Every `Execute` command results in `execStmtInOpenState` call.

> If so, I'm not sure this will behave correctly in edge cases where a pausable portal is started and paused, multiple_active_portals_enabled is disabled, and execution of the portal continues.

Do I understand correctly that you're concerned about value of `multiple_active_portals_enabled` going from `true` to `false` between different `Execute` commands? If so, I don't think it's a problem - we only examine this value once, when we create the prepared portal (i.e. when evaluating the `Prepare` pgwire command), and from that point on the portal will always either be pausable or not. (There is a minor caveat that we might "revoke portal pausability" after performing the logical planning if we see that the stmt is disallowed. This will happen on the first call to `execStmtInOpenState`.)

**Comment by ZhouXing19** [comment]
I agree with Yahor's points and wanted to add some additional details.

> My first question is: can the execStmtInOpenState function be invoked more than once for a single statement when executed with pausable portals?

Yes, it can. For example, consider the select_from_individual_resources test from pgtest/multiple_active_portals:

```
Parse {"Name": "q1", "Query": "SELECT * FROM generate_series(1,20)"}
Parse {"Name": "q2", "Query": "SELECT * FROM generate_series(1,20)"}
Bind {"DestinationPortal": "p1", "PreparedStatement": "q1"}
Bind {"DestinationPortal": "p2", "PreparedStatement": "q2"}
Execute {"Portal": "p1", "MaxRows": 1}
Execute {"Portal": "p2", "MaxRows": 1}
Execute {"Portal": "p1", "MaxRows": 1}
Execute {"Portal": "p2", "MaxRows": 1}
```

In this scenario, for each execution of either `p1` or `p2`, `connExecutor.execPortal()` will be called, which eventually invokes `execStmtInOpenState()`.

The key distinction here is that when a portal is executed for the first time, it gets registered in `ex.extraTxnState.prepStmtsNamespace.portals`, along with the associated `portalInfo`. This `portalInfo` is essential for resuming execution of that specific portal, particularly through `planner.resumeFlowForPausablePortal()`.

An important aspect of portalInfo is the cleanupFuncStack. This stack contains functions meant to be executed in a specific order when the portal is closed. For a deeper explanation of this part, you can refer to [this section of the code](https://github.com/cockroachdb/cockroach/blob/ba77a89b6e3e7c0be0f2845948c5284091625043/pkg/sql/prepared_stmt.go#L373-L405).

I believe it makes sense to have a dedicated code path for pausable portals. The primary reason for the `if portal.isPausable()` checks in `execStmtInOpenState` is that the lifecycle of a pausable portal differs significantly from that of a regular statement execution. Specifically:

- For a regular statement, its lifecycle is confined to a single invocation of execStmtInOpenState().
- For a pausable portal, the lifecycle needs to account for:
    - Parts executed only during the initial run.
    - Parts repeated for each execution.
    - Cleanup tasks executed only when the portal is closed.
Given that the original design of `execStmtInOpenState` doesn't align well with this lifecycle, having a dedicated set of execution functions for pausable portals would likely result in a cleaner and more maintainable implementation.

**Comment by yuzefovich** [comment]
The main reason for why we didn't implement a separate code path for pausable portals right away is the code duplication, i.e. we were worried about two `execStmtInOpenState` variants drifting apart. It did result in a very difficult to read code though, and there is a performance cost for all queries that don't use the pausable portal execution model. I guess I'd be ok with this change - it'll also provide a way to refactor the pausable portal variant of `execStmtInOpenState` to better match the model that pausable portals need, as Jane outlined above.

**Comment by mgartner** [comment]
>Do I understand correctly that you're concerned about value of multiple_active_portals_enabled going from true to false between different Execute commands?

Yes, sort of. My main concern is this scenario:

1. A `execStmtInOpenStateWithPausablePortal` is called and a pausable portal is created.
2. Later on, the portal is no longer pausable (e.g., pausability has been revoked for one reason or another), yet the portal execution is resumed with `execStmtInOpenState`.

Is the logic in `execStmtInOpenStateWithPausablePortal` (or the current version of `execStmtInOpenState` on `master`) that must execute for a portal that was once pausable but is no longer pausable. If so, then this approach won't work.

**Comment by michae2** [comment]
> I believe it makes sense to have a dedicated code path for pausable portals. The primary reason for the `if portal.isPausable()` checks in `execStmtInOpenState` is that the lifecycle of a pausable portal differs significantly from that of a regular statement execution.

> The main reason for why we didn't implement a separate code path for pausable portals right away is the code duplication, i.e. we were worried about two execStmtInOpenState variants drifting apart. It did result in a very difficult to read code though

@ZhouXing19 and @yuzefovich, something I have wondered: instead of storing state in `portalPauseInfo`, would it have worked to keep all of that state local and instead run `execStmtInOpenState` in a goroutine that then waits on a channel whenever it needs to pause?

**Comment by yuzefovich** [comment]
> Yes, sort of. My main concern is this scenario:
> 1. `execStmtInOpenStateWithPausablePortal` is called and a pausable portal is created.
> 2. Later on, the portal is no longer pausable (e.g., pausability has been revoked for one reason or another), so the portal execution is resumed with `execStmtInOpenState`.

I don't think this sequence of events is possible. The prepared portal is created when we evaluate `Bind` pgwire command, and this is when we decide whether the portal will be pausable or not. When we evaluate the first `Execute` pgwire command, then if we created a pausable portal, we will always go into `execStmtInOpenStateWithPausablePortal`. There are two possible scenarios here:
- the stmt is supported for pausable portals machinery, so it'll only be executed via the pausable portals model. We never will revoke the pausability, so we will keep on calling `execStmtInOpenStateWithPausablePortal`.
- the stmt is _not_ supported for pausable portals machinery, so we revoke the portal pausability. Notably the revocation occurs _before_ we invoke the execution engine, so we execute the portal via non-pausable model. (Well, to be precise, we can execute it via "limited pausable portal" model where we can pause the portal execution but without switching to another stmt. In this case `limitedCommandResult.moreResultsNeeded` hijacks the connExecutor state machine, so we only have a single `execStmtInOpenStateWithPausablePortal` invocation total even for multiple `Execute{Limit}` pgwire commands, before the portal is destroyed.) With non-pausable model we won't call `execStmtInOpenState` variants for the same portal again.

> something I have wondered: instead of storing state in `portalPauseInfo`, would it have worked to keep all of that state local and instead run `execStmtInOpenState` in a goroutine that then waits on a channel whenever it needs to pause?

Hm, it's an interesting idea, and it might be cleaner to implement. I imagine that in `limitedCommandResult.AddRow` if we have a pausable portal and we reached the current limit, we would block on the channel waiting for the connExecutor to tell us whether we need to resume execution (with a new limit or without it) or we should exit because the portal is being closed. The only caveat I see is that we currently create a separate `CommandResult` for each pgwire Execute command, but I think for this idea to work we would need to keep using the same `limitedCommandResult` object that we created on the first run. Let me prototype it to see how it would look.

**Comment by mgartner** [comment]
>I don't think this sequence of events is possible.

Cool! Thanks for the thorough explanation and all the additional context @yuzefovich and @ZhouXing19!

> The main reason for why we didn't implement a separate code path for pausable portals right away is the code duplication, i.e. we were worried about two execStmtInOpenState variants drifting apart. It did result in a very difficult to read code though, and there is a performance cost for all queries that don't use the pausable portal execution model. I guess I'd be ok with this change - it'll also provide a way to refactor the pausable portal variant of execStmtInOpenState to better match the model that pausable portals need, as Jane outlined above.

If we proceed with something like this, @RaduBerinde recommended "falling back to the general function with a random probability in CrdbTestBuild to make sure the paths don't diverge." I think that's a good idea, at least as long as the pausable portal code path is capable of handling the non-pausable portal cases as well.

**Comment by mgartner** [comment]
Some single-node sysbench benchmark results:

```
name                                        old time/op    new time/op    delta
Sysbench/SQL/1node_local/oltp_read_write-8    4.65ms ± 0%    4.63ms ± 0%  -0.31%  (p=0.008 n=5+5)

name                                        old alloc/op   new alloc/op   delta
Sysbench/SQL/1node_local/oltp_read_write-8    1.28MB ± 0%    1.27MB ± 0%  -1.25%  (p=0.008 n=5+5)

name                                        old allocs/op  new allocs/op  delta
Sysbench/SQL/1node_local/oltp_read_write-8     7.39k ± 0%     7.14k ± 0%  -3.31%  (p=0.008 n=5+5)
```

**Review by yuzefovich — COMMENTED** [review]
>> something I have wondered: instead of storing state in `portalPauseInfo`, would it have worked to keep all of that state local and instead run `execStmtInOpenState` in a goroutine that then waits on a channel whenever it needs to pause?

> Let me prototype it to see how it would look.

I prototyped it in #136940, and I think it's a direction worth pursuing: the code becomes cleaner, and we probably will be able to lift restrictions on the types of stmts that can be executed via the pausable portals model. The main complication with that approach is that we need to think through how to handle objects that are bound to the connExecutor to allow for concurrent access. For example, `connExecutor.planner` state needs to be copied ("forked") for the pausable portal (perhaps we'll also need to "reconcile" the forked planner used by the pausable portal with the main one, when the portal is closed). So there definitely some questions to work out, but it seems promising overall.

In the meantime, I think we should proceed with the current change. I also like Radu's idea of switching the codepath we take in the test builds.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-:-ODglfWC0PQqXZpiN9px:b271spi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @ZhouXing19)

___
*[`pkg/sql/conn_executor_exec.go` line 360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODgox6JDPxqJidGfZIq:-ODgox6K50dhzI0I2j9S:b-n7vjzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/658a64a7c0208694685addfc50d614e61d227929/pkg/sql/conn_executor_exec.go#L360)):*
> ```Go
> 	ex.addActiveQuery(parserStmt, pinfo, queryID, vars.cancelQuery)
> 	defer func() {
> 		// We need to check the latest errors rather than the ones evaluated
> ```

nit: this comment doesn't seem helpful anymore, so I'd consider removing it altogether.
___
*[`pkg/sql/conn_executor_exec.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODgnmqn-w8COJgSWE_8:-ODgnmqn-w8COJgSWE_9:b-q1q8cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c5449572df7feb8900fe6905a1e06cb2b2ca31e/pkg/sql/conn_executor_exec.go#L146)):*
> ```Go
> 			})
> 		} else {
> 			err = ex.execWithProfiling(ctx, ast, preparedStmt, func(ctx context.Context) error {
> ```

`preparedStmt` will now be unset for non-pausable portals.

Update: this is fixed in the fifth commit. We should fix it in the first.
___
*[`pkg/sql/conn_executor_exec.go` line 709 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODgpdCD-fLevyyOcjex:-ODgpdCD-fLevyyOcjey:b-ske0ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb532fe34d5f41ab68ad35fe8dfbc6105adfdb0b/pkg/sql/conn_executor_exec.go#L709)):*
> ```Go
> 
> 		processCleanupFunc("set query error", func() {
> 			cancelQueryCtx := ctx
> ```

nit: we can remove some more redundant code here by using `ctx` instead of `cancelQueryCtx`, `res` instead of `resToPushErr`. Additionally, we should switch `ErrAllowReleased()` call in favor of `Err()` (the former is only needed for pausable portals).

**Comment by mgartner** [comment]
> In the meantime, I think we should proceed with the current change. I also like Radu's idea of switching the codepath we take in the test builds.

Thanks for prototyping that solution. I'll address your comments and add a random flip between the two codepaths in test builds.

---

Some more benchmark results:

```
name                                   old time/op    new time/op    delta
Sysbench/SQL/3node/oltp_read_write-16    6.33ms ± 1%    6.25ms ± 1%  -1.30%  (p=0.000 n=10+10)

name                                   old alloc/op   new alloc/op   delta
Sysbench/SQL/3node/oltp_read_write-16    2.45MB ± 7%    2.44MB ± 7%    ~     (p=0.315 n=10+10)

name                                   old allocs/op  new allocs/op  delta
Sysbench/SQL/3node/oltp_read_write-16     17.3k ± 6%     16.9k ± 2%  -2.34%  (p=0.015 n=10+10)
```

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136861)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @yuzefovich, and @ZhouXing19)

___
*[`pkg/sql/conn_executor_exec.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODgnmqn-w8COJgSWE_8:-ODhcr3P-aDgSbjq3z4n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd11d6604f9c8f1d885718bf9c92b421e2230953/pkg/sql/conn_executor_exec.go#L146)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`preparedStmt` will now be unset for non-pausable portals.

Update: this is fixed in the fifth commit. We should fix it in the first.
</blockquote></details>

Done.
___
*[`pkg/sql/conn_executor_exec.go` line 709 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODgpdCD-fLevyyOcjex:-ODhenUr-lOwK_1UgYnK:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e6e772f3fcf3c9afecdcc5107301ba067704e6/pkg/sql/conn_executor_exec.go#L709)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we can remove some more redundant code here by using `ctx` instead of `cancelQueryCtx`, `res` instead of `resToPushErr`. Additionally, we should switch `ErrAllowReleased()` call in favor of `Err()` (the former is only needed for pausable portals).
</blockquote></details>

Good catch. Done.
___
*[`pkg/sql/conn_executor_exec.go` line 360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODgox6JDPxqJidGfZIq:-ODhdCdy3mm3PKycxa39:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b67706f41f86bbeb4ad56573da20e26bada4ac99/pkg/sql/conn_executor_exec.go#L360)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this comment doesn't seem helpful anymore, so I'd consider removing it altogether.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
With the added randomization of which path is used I think we now must remove commits 2 and 3. Otherwise, :lgtm:

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-:-ODhp10f3Yyu7zu6LBG9:b-dydd15)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @ZhouXing19)

___
*[`pkg/sql/conn_executor_exec.go` line 155 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODhoxIPBC3Q6cBfGF9v:-ODhoxIPBC3Q6cBfGF9w:b-f8vbou) ([raw file](https://github.com/cockroachdb/cockroach/blob/db66acce34feb5b8823978aa3ef97de2e344236f/pkg/sql/conn_executor_exec.go#L155)):*
> ```Go
> 		}
> 		if usePausableCodePath {
> 			preparedStmt = portal.Stmt
> ```

nit: we no longer need this line.

**Review by mgartner — COMMENTED** [review]
>With the added randomization of which path is used I think we now must remove commits 2 and 3.

I've removed the assertion in the 2nd commit, but kept the other minor changes (and reworded the commit message to match). The 3rd commit should be fine—the `execStmtInOpenState` function is never used with a pausable portal—unless I'm missing something.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-:-ODqTAfa-ZN9fdw0Z1Se:b62is34)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @yuzefovich, and @ZhouXing19)

___
*[`pkg/sql/conn_executor_exec.go` line 155 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/136861#-ODhoxIPBC3Q6cBfGF9v:-ODqSyd41J-J_YikLsbq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db66acce34feb5b8823978aa3ef97de2e344236f/pkg/sql/conn_executor_exec.go#L155)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we no longer need this line.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136861)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @ZhouXing19)

**Comment by yuzefovich** [comment]
Oh, actually, now the second commit hard-codes the assumption that `portal` is non-nil in `execStmtInOpenStateWithPortal`, but then with the last commit we might choose to use that function even for non-portals. What am I missing?

**Comment by mgartner** [comment]
Since https://github.com/cockroachdb/cockroach/commit/5838c5c1ee27cd195aeedd0cc513830cf2be423d#diff-7c5a26942e53c921a48fb4a83f4482df389c106e396179c1ef70eda12bd2a72fR330, `(*PreparedPortal).isPausable` can handle the case where the receiver is `nil`. So this is the same as the current version of `execStmtInOpenState` on master.

**Comment by mgartner** [comment]
In a full sysbench test I measured a 1% increase in throughput:

Before:
```
22759 qps = (22749 + 22814 + 22714) / 3
```

After:
```
23003 qps = (22980 + 22931 + 23099) / 3
```

bors r+

**Pull request merged**
