### PR TITLE
sql: rename "ident" aggregation to "any_not_null"

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change revamps the use of ident aggregation:

 - the aggregation is renamed to `any_not_null` and is now a built-in
   that can be used in SQL.

 - the semantics are cleaned up: the aggregation now returns any
   non-null value (or null if no such value). These semantics are
   compatible with how we are using ident today, and are also what the
   optimizer needs for some transforms.

Release note: None

CC @andy-kimball

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/group.go, line 578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_QT9z47kF6z11UNhP:-LC_QT9z47kF6z11UNhQ:b-45xo4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/group.go#L578)):*
> ```Go
> // any_not_null aggregation for a grouping column. The grouping column
> // index is also returned.
> func (n *groupNode) aggIsGroupingColumn(aggIdx int) (colIdx int, ok bool) {
> ```

[nit] I don't love this name but I don't really have a better suggestion. Would be good to somehow include the `any_not_null` aspect of it...

---

*[pkg/sql/distsqlrun/processors.proto, line 421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_PR756eO8Islzq3g_:-LC_PR756eO8Islzq3ga:btwcl5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/575b73a20a2b48cf040cc2f0bbb9b60a3e94022d/pkg/sql/distsqlrun/processors.proto#L421)):*
> ```protobuf
>   enum Func {
>     // The identity function is set to be the default zero-value function,
>     // returning the last value added.
> ```

Did you mean to remove this comment?

---

*[pkg/sql/sem/builtins/aggregate_builtins.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Qpo17duSN8-MhS3e:-LC_Qpo17duSN8-MhS3f:b-oxgu7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L249)):*
> ```Go
> 			tree.IdentityReturnType(0),
> 			newAnyNotNullAggregate,
> 			"Returns an arbitrary not-NULL value.",
> ```

Maybe say:
"Returns an arbitrary not-NULL value, or NULL if none exists."

---

*[pkg/sql/sem/builtins/aggregate_builtins.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_R59Q1_U4fhvjNdVE:-LC_R59Q1_U4fhvjNdVF:b-j2sv26) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L339)):*
> ```Go
> // themselves).
> //
> // The NULL behavior is important in a few different contexts:
> ```

Can you be more specific about the NULL behavior? Is it the fact that it skips over NULL values?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-:-LC_RIPlEPCuaY25IuFD:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/generated/sql/aggregates.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_U0gRAhjrwV2hiVja:-LC_U0gRAhjrwV2hiVjb:bjv3qyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/docs/generated/sql/aggregates.md#L4)):*
> ```Markdown
> <thead><tr><th>Function &rarr; Returns</th><th>Description</th></tr></thead>
> <tbody>
> <tr><td><code>any_not_null(arg1: anyelement) &rarr; anyelement</code></td><td><span class="funcdesc"><p>Returns an arbitrary not-NULL value.</p>
> ```

This should be a private function. See my comment in `aggregate_builtins.go`.

---

*[pkg/sql/sem/builtins/aggregate_builtins.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Tn2yAkZAAdCH06Vm:-LC_Tn2yAkZAAdCH06Vn:b-7yhod9) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L245)):*
> ```Go
> 
> 	"any_not_null": {
> 		makeAggBuiltinWithReturnType(
> ```

I think we want to set the private field to true for this aggregate, since it should be internal-only. See `makePrivateAggBuiltin`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Tn2yAkZAAdCH06Vm:-LC_Xs0o90aJLHM3N6tv:b9zkww9) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L245)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think we want to set the private field to true for this aggregate, since it should be internal-only. See `makePrivateAggBuiltin`.
</blockquote></details>

Is there a strong reason it should be private? I don't see a problem with allowing it in SQL statements. The other ones that are private cause crashes when used in statements.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534)*

**Comment by knz** [comment]
:lgtm: modulo a couple nits

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[docs/generated/sql/aggregates.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_U0gRAhjrwV2hiVja:-LC_bQK488rLXsK8-xWg:b-hy49oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/docs/generated/sql/aggregates.md#L4)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This should be a private function. See my comment in `aggregate_builtins.go`.
</blockquote></details>

Also perhaps `crdb_internal.any_not_null()`? not strongly opinionated on this, but there's precedent.

---

*[pkg/sql/group.go, line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_bcSv7HI4EOOh4tHu:-LC_bcSv7HI4EOOh4tHv:b-i2nmyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/group.go#L579)):*
> ```Go
> // index is also returned.
> func (n *groupNode) aggIsGroupingColumn(aggIdx int) (colIdx int, ok bool) {
> 	if holder := n.funcs[aggIdx]; holder.funcName == "any_not_null" {
> ```

Make a constant for the sting in the builtin package and use the constant in both places.

---

*[pkg/sql/opt_exec_engine.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_bhpS8GglbOnfZZsK:-LC_bhpS8GglbOnfZZsL:b64bjlr) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/opt_exec_engine.go#L356)):*
> ```Go
> 		// TODO(radu): only generate the grouping columns we actually need.
> 		f := n.newAggregateFuncHolder(
> 			"any_not_null",
> ```

ditto constant

---

*[pkg/sql/opt/memo/typing_test.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_bs__Bwjd4Pmjs5_x:-LC_bs__Bwjd4Pmjs5_y:b64bjlr) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/opt/memo/typing_test.go#L148)):*
> ```Go
> func TestTypingAggregateAssumptions(t *testing.T) {
> 	for name, overloads := range builtins.Aggregates {
> 		if name == "any_not_null" {
> ```

ditto constant

---

*[pkg/sql/sem/builtins/aggregate_builtins.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Tn2yAkZAAdCH06Vm:-LC_bwYD2Znozb2rH9ds:b-lzbnt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L245)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

To clarify, I'm not necessarily against it. But we don't want to just slip in new top-level SQL syntax in a PR. This would need to be cleared through the PM's, the doc team, etc. Everyone needs to be informed and on-board before we introduce new SQL syntax.
</blockquote></details>

yeah I'd say either `crdb_internal` or "experimental" in the name.

---

*[pkg/sql/sem/builtins/aggregate_builtins.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Qpo17duSN8-MhS3e:-LC_bzjLEJHyBvlAslcA:b-miqvmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L249)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe say:
"Returns an arbitrary not-NULL value, or NULL if none exists."

</blockquote></details>

Also add a remark in the doc that this is an experimental feature for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-:-LC_c5N13OB_JXwBflnA:bykfzog)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Tn2yAkZAAdCH06Vm:-LC_kk_3Bk7s1iw5Q_b2:b-638i54) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L245)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah I'd say either `crdb_internal` or "experimental" in the name.
</blockquote></details>

Honestly, I'd rather remove it than have `crdb_internal.any_not_null` or `experimental_any_not_null` in explains and distsql plans..

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Tn2yAkZAAdCH06Vm:-LC_ky2s4kO-25FJSDJR:brag75z) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L245)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Honestly, I'd rather remove it than have `crdb_internal.any_not_null` or `experimental_any_not_null` in explains and distsql plans..
</blockquote></details>

(by "remove", I meant make it private)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534)*

**Comment by knz** [comment]
LGTM but I'm a bit sorry to see the builtin become private :) 
Oh well.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/builtins/aggregate_builtins.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-LC_Tn2yAkZAAdCH06Vm:-LCcMcxr50Iqgk3JfWf0:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/aec3a5f52c9ce16e45416f7a16765afa5d282c2c/pkg/sql/sem/builtins/aggregate_builtins.go#L245)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Made it private.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534#-:-LCcMk8T-J2URfjz12u_:b-vzr9vu)*

**Comment by rytaft** [comment]
Reviewed 6 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25534)*

**Pull request merged**
