### PR TITLE
build: remove codacy.yml

### PR DESCRIPTION
**Pull request by justinj**

### CODE REVIEW

**Comment by benesch** [comment]
:fire:

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19384#-:-KwqDQi406HVbg555tIw:b-5eepet)*

**Review by a-robinson — APPROVED** [review]

**Comment by jordanlewis** [comment]
🐴 💥 🔫

**Review by jordanlewis — APPROVED** [review]
🐴 💥 🔫

**Pull request merged**
