### PR TITLE
keys: Add an infixed specifier tag to split per-range raft and non-raft keys

### LINKED ISSUE #4447: storage: Raft keys need to be moved out of the system-local kv-pairs for stats computations
Raft logs and the Raft HardState are not consistent across replicas, so we can't include these kv-pairs in the `SysBytes` and `SysCount` `MVCCStats` struct. Including these keys in statistics computations results in these structs being inconsistent between replicas, because they are not the same on each replica, and incorrect on all replicas most of the time anyway, because the stats aren't currently updated when the raft kv state changes.

### PR DESCRIPTION
**Pull request by nvb**
Closes #4447.

This approach uses a tag that is appended to the Range ID prefix to
construct per-range metadata keys. By appending this tag after the Range
ID, as opposed to before it, we assure that the raft keys and the
non-raft keys for a given range sort contiguously, meaning that
they can be scanned and deleted together using a single MVCC command by
omitting any specifier, but can also be manipulated separately when
necessary by appending the appropriate specifier to any MVCC command key
ranges.

This change is a precursor to separating Raft statistics from the rest
of the range-local value statistics in the `MVCCStats` struct. This separation
is critical both because it will give a greater level of granularity to
statistic introspection, and because it will prevent the inconsistent,
non-raft replicated raft metadata values (the `RaftLog` and `RaftHardState`)
from undermining the integrity of the rest of the stats for range-local data
(such as the `SequenceCache` and the `LastVerificationTimestamp`).

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4510)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[keys/constants.go, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAv6PN2ljwM1Vl1gFOK:-KAv6PN2ljwM1Vl1gFOL:-1901959302) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/constants.go#L97)):*
The `scanned and deleted together or separately` phrase doesn't make sense to me. In this context, I think `scanned and deleted separately` is sufficient. 

---

*[storage/replica_data_iter.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAvZ9-si9AcvpJp1A84:-KAvZ9-si9AcvpJp1A85:-1598590147) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/storage/replica_data_iter.go#L43)):*
This is clever, though the meaning of the second parameter to `makeReplicaKeyRanges` isn't obvious at the call site. Perhaps add a comment `/* statsOnly */` after the `{true,false}` parameter when this method is called.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-:-KAvZX6lFX0DYbTz9ocL:676834233)*

**Comment by tschottdorf** [comment]
LGTM. In the unlikely event of this merging after my open sequence cache PR, make sure to rebase.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[keys/keys.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAveqvxa2iI7j87TATJ:-KAveqvxa2iI7j87TATK:-1340338438) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/keys.go#L90)):*
I wonder whether `Meta` is the right name for this stuff, but I'm at a loss for a better name right now. `Local`? `Unreplicated`?

Similarly, `Raft` for the replicated keys sounds confusing to my ears since it sounds like that would probably hold Raft state, which is not replicated.

Maybe `Local` vs `Replicated` is a good compromise?

---

*[keys/printer.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAvfk-Vv0C8IcMUVbZH:-KAvfk-Vv0C8IcMUVbZI:-1914712617) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/printer.go#L148)):*
Maybe we want to print this somehow.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-:-KAvg5kFYiptdydcJdv4:961151869)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_data_iter.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAvZ9-si9AcvpJp1A84:-KAvpaxlqIs5xowYoxMR:-1596914422) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/storage/replica_data_iter.go#L43)):*
Seems clearer to have two separate functions. Most of the code can be shared by passing `metaFunc` to a helper.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510)*

**Comment by nvanbenschoten** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[keys/constants.go, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAv6PN2ljwM1Vl1gFOK:-KAvwboJrdNXCxySIAvv:758084059) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/constants.go#L97)):*
Would `"manipulated either together or individually in a single scan"` make more sense? My whole point was that by having this specifier after the replicaID, the two system-local metadata groups could be scanned or deleted together when needed (because they're contiguous instead of interleaved with other ranges), but could also be worked with separately.

---

*[keys/keys.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAveqvxa2iI7j87TATJ:-KAvzYyvtHYFDPRz1Mt2:1244447122) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/keys.go#L90)):*
I agree that the name `Meta` is overloaded and not exactly the right word here, but I haven't been able to figure out something that works better yet.

Also, I may be misinterpreting what you're saying, but I just want to make sure its clear that this approach is currently splitting **all** Raft keys (including fully replicated ones) from the rest of the metadata (`SequenceCache`, `LastVerificationTimestamp`, `MVCCStats`). Later, this will allow for a natural progression to adding replicated Raft stats into the `MVCCStats` as a separate key from the system-local data, as Ben suggested. For now though, it will simply remove all Raft data from the system-local stats, eliminating the replicated vs. unreplicated issue as a temporary holdover.

---

*[keys/printer.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAvfk-Vv0C8IcMUVbZH:-KB50oSYoYxT1xCVWS9h:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/printer.go#L148)):*
Done.

---

*[storage/replica_data_iter.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAvZ9-si9AcvpJp1A84:-KAvyeomMXpjvrU_vmC1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/storage/replica_data_iter.go#L43)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510)*

**Comment by bdarnell** [comment]
Review status: 5 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[keys/keys.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAveqvxa2iI7j87TATJ:-KB50Ioo7ZzBJP9_97E5:-1072909120) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/keys.go#L90)):*
Much of the raft state *is* replicated, though. For the consistency checker, we want to include all the raft state except log and hardstate. If the consistency checker and MVCCStats can't agree on a definition of what's included and what's not, then I'd rather not encode either one of them as an "infix" in the key names.

I'd go with the names `Unreplicated` (`Local` is already used differently in this context) and `Replicated` if that's the way the boundary ends up drawn (with raft log and hardstate being the only unreplicated keys).

---

*[storage/replica_data_iter.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAvZ9-si9AcvpJp1A84:-KB52rSE9RXnuiybk3Lk:-1286925942) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/storage/replica_data_iter.go#L43)):*
The function should also have a comment explaining what `statsOnly` means.

---

*[storage/sequence_cache.go, line 231 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KB531yh4499uYKsPand:-KB531yh4499uYKsPane:-522191001) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/storage/sequence_cache.go#L231)):*
I'd like to move key-parsing code like this into the `keys` package.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510)*

**Comment by petermattis** [comment]
Review status: 5 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[keys/constants.go, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAv6PN2ljwM1Vl1gFOK:-KB5bUWpnoQtvQM5FbtL:1780716317) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/constants.go#L97)):*
Yeah, that wording is better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510)*

**Comment by tschottdorf** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[keys/keys.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAveqvxa2iI7j87TATJ:-KB5iUC0QUXgBH9huhkI:-1082027984) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/keys.go#L90)):*
The the definition of what's in `Replicated` is everything that has the same state across all replicas as they execute a given Raft command. Consequently, parts of Raft which play along with that (so presumably everything but log and hardstate, though I don't remember what's left) should be `Replicated`. That should be the same the consistency checker looks at.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510)*

**Comment by nvanbenschoten** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[keys/constants.go, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAv6PN2ljwM1Vl1gFOK:-KB66Oz9ZQSAU4R2oiSk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/constants.go#L97)):*
Done.

---

*[keys/keys.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAveqvxa2iI7j87TATJ:-KB6DgcQI4v3ALteSE7S:-1518688771) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/keys/keys.go#L90)):*
Got it, I figured there were two possible ways to approach this so I'd push out a PR to get the conversation going. Like you both mentioned, splitting the system-local keys between `Unreplicated` and `Replicated` fixes the stats issue and helps out the consistency checker, so I agree that it is the right way to go from here. I just made the switch to that approach, so PTAL.

---

*[storage/replica_data_iter.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KAvZ9-si9AcvpJp1A84:-KB6AF0ppYEEq-QFsqcc:-1801455456) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/storage/replica_data_iter.go#L43)):*
This was changed to two wrapper functions around a helper, as Tamir suggested. Hopefully the intention of each is clearer that way.

---

*[storage/sequence_cache.go, line 231 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KB531yh4499uYKsPand:-KB6Cj8QUsgaBcT2uAgU:-910066345) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eb1e1bb954402565b5dd332daa4473a2096afd/storage/sequence_cache.go#L231)):*
Agreed, but the cleanup should probably be in a different PR. See #4547

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/replica_data_iter.go, line 50 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KB9GLPPwLUABzHJ6zxW:-KB9GLPPwLUABzHJ6zxX:-255828310) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5386904600a218e246f1ac983bb4389164138c2/storage/replica_data_iter.go#L50)):*
s/ReplicaStats/Replicated/

In a separate PR we might want to expose this distinction via `newReplicaDataIterator`: some of the logic in `Replica.Snapshot` and `Replica.ApplySnapshot` could be removed if we never saw the unreplicated state to begin with. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-:-KB9H1xWUVf3NSHGGR8H:676834233)*

**Comment by nvanbenschoten** [comment]
I just moved `RaftLastIndexKey` from the replicated group to the unreplicated group, because it is used with the Raft log. PTAL.

---

Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/replica_data_iter.go, line 50 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-KB9GLPPwLUABzHJ6zxW:-KB9SC1HJzG1P3Rkx-ho:-30835038) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5386904600a218e246f1ac983bb4389164138c2/storage/replica_data_iter.go#L50)):*
Done. And made an issue for the cleanup #4572.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4510#-:-KB9bOo277dbX4QJUEH8:-893594644)*

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
