### PR TITLE
sql: reuse aggregation pre-renders

### PR DESCRIPTION
**Pull request by RaduBerinde**
In cases where multiple aggregation functions were taking the same argument, we
were rendering the same value multiple times. We now reuse renders.

Plus: some cleanup and a fix in separate commits.

### CODE REVIEW

**Comment by knz** [comment]
Good idea and good execution. I'm curious about what the failing test is highlighting.

---

Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1114 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-KjMyEyyUX7kHPm2BsFi:-KjMyEyyUX7kHPm2BsFj:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/557dd33af427c7773cc83a435bb1df04fe706dc3/pkg/sql/distsql_physical_planner.go#L1114)):*
> ```Go
> 	}
> 
> 	fmt.Printf("MEH funcs %v\n", n.funcs)
> ```

?

---

*[pkg/sql/distsqlplan/expression.go, line 63 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-KjMvZJd1hFTODZWEIkW:-KjMvZJd1hFTODZWEIkX:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/557dd33af427c7773cc83a435bb1df04fe706dc3/pkg/sql/distsqlplan/expression.go#L63)):*
> ```Go
> 		return distsqlrun.Expression{}
> 	}
> 	fmt.Printf("MAKE EXPR %s\n", expr)
> ```

?

---

*[pkg/sql/distsqlplan/expression.go, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-KjMv_kZjNw71J_zhXYt:-KjMv_kZjNw71J_zhXYu:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/557dd33af427c7773cc83a435bb1df04fe706dc3/pkg/sql/distsqlplan/expression.go#L74)):*
> ```Go
> 			func(buf *bytes.Buffer, _ parser.FmtFlags, _ parser.IndexedVarContainer, idx int) {
> 				if idx >= len(indexVarMap) {
> 					fmt.Printf("IDX %d  MAP: %v\n", idx, indexVarMap)
> ```

?

---

*[pkg/sql/parser/format.go, line 71 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-KjMuvrHtQ0zjcOYvqLi:-KjMuvrIpjNU694YKAhf:b1id0nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/931cd2630ac5b1cd20003d4dd81348ba0f9dd7ac/pkg/sql/parser/format.go#L71)):*
> ```Go
> // FmtSymbolicVars is like FmtParsable except it instructs the pretty-printer to
> // print indexedVars using symbolic notation (to disambiguate columns).
> var FmtSymbolicVars FmtFlags = &fmtFlags{symbolicVars: true, disambiguateDatumTypes: true}
> ```

Add the explanation from the commit message in this comment, to justify why disambiguateDatumTypes is set to true.
Also the commit message is wrong, with `bareString:false` (the default) strings will be enclosed in quotes, while numbers will be without quotes.
Do you mean perhaps that a *decimal* is printed the same as an *int* and yet they are different? (Same for bool vs string) I'd buy that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-:-KjMy9-Zy1SCpX3QavEc:b-sbyowk)*

**Comment by RaduBerinde** [comment]
Hm, [during formatting](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/format.go#L161) we are using `DatumTypeToColumnType` to come up with the cast string, but this doesn't support all types. Normally we wouldn't use it for a bool Datum because it's not an `AmbiguousFormat`, but we do use it if we have a placeholder. It seems like not supporting bools in this function is a mistake which I can fix, but there are other types (like arrays) it doesn't support, and a placeholder could have those types (?)

**Comment by knz** [comment]
Not yet I think. @jordanlewis ?

**Comment by RaduBerinde** [comment]
Review status: 4 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 1114 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-KjMyEyyUX7kHPm2BsFi:-KjNi5wPkzRSfXYlx8O2:b-rh72q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/557dd33af427c7773cc83a435bb1df04fe706dc3/pkg/sql/distsql_physical_planner.go#L1114)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

?
</blockquote></details>

Oops, sorry, forgot to clean these up. Fixed.

---

*[pkg/sql/parser/format.go, line 71 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-KjMuvrHtQ0zjcOYvqLi:-KjNiANHIKGRJklOSmQS:boag3xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/931cd2630ac5b1cd20003d4dd81348ba0f9dd7ac/pkg/sql/parser/format.go#L71)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add the explanation from the commit message in this comment, to justify why disambiguateDatumTypes is set to true.
Also the commit message is wrong, with `bareString:false` (the default) strings will be enclosed in quotes, while numbers will be without quotes.
Do you mean perhaps that a *decimal* is printed the same as an *int* and yet they are different? (Same for bool vs string) I'd buy that.
</blockquote></details>

Yeah, that's what I meant. I got a panic along the lines of "expected DDecimal but got DInt". Fixed, and renamed to `FmtCheckEquivalence`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710)*

**Comment by jordanlewis** [comment]
Yes this is a problem I've been encountering in my patch for caching parsed
prepared statements as well. We don't currently encounter this problem for
placeholders with eg array types because the placeholders are replaced
before distsql needs to serialize anything.

I don't think it's a problem to include the rest of the missing types here,
as long as we verify that unsupported column types like arrays are still
properly rejected during eg table creation.

**Comment by cuongdo** [comment]
There is already a test for creating tables with ARRAY columns here:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/testdata/logic_test/table#L426

---

Review status: 4 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-:-KjNoW0wobN3vVAuh5cX:b-ryizne)*

**Comment by knz** [comment]
Reviewed 2 of 9 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/format.go, line 71 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-KjMuvrHtQ0zjcOYvqLi:-KjNqWoSqZxb_igh2hkp:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/931cd2630ac5b1cd20003d4dd81348ba0f9dd7ac/pkg/sql/parser/format.go#L71)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, that's what I meant. I got a panic along the lines of "expected DDecimal but got DInt". Fixed, and renamed to `FmtCheckEquivalence`.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710)*

**Comment by knz** [comment]
LGTM modulo the check suggested by Jordan.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-:-KjNrkWObBzIva6jXE1H:b9q7c4o)*

**Comment by RaduBerinde** [comment]
I made the Bool fix (which was definitely a mistake, we can have bool columns). I filed #15714 to follow up on the ColumnType issue.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15710#-:-KjNpmNP7Qf95OMdYZD_:bx03iip)*

**Comment by RaduBerinde** [comment]
Ok to merge? (I'm not sure which check you referred to above)

**Review by knz — APPROVED** [review]
Cuong answered. Indeed good to merge.

**Comment by RaduBerinde** [comment]
dank je

**Pull request merged**
