### PR TITLE
kv: support migration between lease types

### LINKED ISSUE #125241: kv: support migration between lease types
Part of https://github.com/cockroachdb/cockroach/issues/123847.

It should be possible and safe to switch back and forth between epoch-based leases and leader leases.

Jira issue: CRDB-39332

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by nvb**
Fixes #125241.

This commit adds support for switching between epoch-based leases and leader leases dynamically, based on the current values of the following two cluster settings:
* `kv.raft.leader_fortification.fraction_enabled` (public)
* `kv.leases.leader_leases.enabled` (private)

When either of these settings is changed, the lease queue will start switching the types of leases that no longer match their range's desired lease type. These changes will be spread across a scanner cycle, so we shouldn't see serious disruption to the cluster.

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
:lgtm: modulo one minor comment

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-:-O7VfbLC1u1_T-8XxI3-:bryl8fz)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-O7VboVZENJMAjonn1bl:-O7VboVZENJMAjonn1bm:bvpxhmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1eb376c89ccbf73946f07d5d7e9c6acca8c704/pkg/kv/kvserver/replica_range_lease.go#L358)):*
> ```Go
> 		// previous lease during evaluation, under latches. It then forwards the
> 		// start time of the next lease. See cmd_lease_transfer.go.
> 		_ = out.PrevLeaseManipulation.RevokeAndForwardNextStart
> ```

I may be missing something, but do we need this `RevokeAndForwardNextStart` boolean? IIUC, we're not really using it, as cmd_lease_transfer.go was doing this unconditionally anyway. Is it just for symmetry with the lease extension case?
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 374 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-O7Vckcx9Ts-UH15aGms:-O7Vckcx9Ts-UH15aGmt:b-2t7nb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1eb376c89ccbf73946f07d5d7e9c6acca8c704/pkg/kv/kvserver/replica_range_lease.go#L374)):*
> ```Go
> 		}
> 		if out.PrevLeaseManipulation.RevokeAndForwardNextStart {
> 			panic("RevokeAndForwardNextStart unexpectedly set for acquisition")
> ```

nit: acquisition/extension?
___
*[`pkg/kv/kvserver/batcheval/cmd_lease_request.go` line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-O7Va_1j-TygGCu1uVFy:-O7Va_1j-TygGCu1uVFz:b-5iqlli) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1eb376c89ccbf73946f07d5d7e9c6acca8c704/pkg/kv/kvserver/batcheval/cmd_lease_request.go#L89)):*
> ```Go
> 		minExp := cArgs.EvalCtx.Clock().Now().Add(int64(cArgs.EvalCtx.GetRangeLeaseDuration()), 0)
> 		if newLease.Type() == roachpb.LeaseExpiration {
> 			newLease.Expiration.Forward(minExp)
> ```

nit: might be worth reminding the reader that `MinExpiration` isn't supported for expiration based leases.
___
*[`pkg/kv/kvserver/lease_queue_test.go` line 313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-O7VdmnA4Zy5QOwvPG7i:-O7VdmnA4Zy5QOwvPG7j:bumq74s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1eb376c89ccbf73946f07d5d7e9c6acca8c704/pkg/kv/kvserver/lease_queue_test.go#L313)):*
> ```Go
> 
> 	waitForLeasesToSwitch := func(name string, someEpoch, someLeader bool) {
> 		require.Eventually(t, func() bool {
> ```

TIL: `require.Eventually`

**Review by nvb — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-:-O7eTgGvB4U7hAFqXRkO:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @jbowens)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-O7VboVZENJMAjonn1bl:-O7eSCEs6aAlyKPg4FrK:b-gea621) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1eb376c89ccbf73946f07d5d7e9c6acca8c704/pkg/kv/kvserver/replica_range_lease.go#L358)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I may be missing something, but do we need this `RevokeAndForwardNextStart` boolean? IIUC, we're not really using it, as cmd_lease_transfer.go was doing this unconditionally anyway. Is it just for symmetry with the lease extension case?
</blockquote></details>

You're correct. It's not actually needed because `cmd_lease_transfer.go` is doing this unconditionally. This is essentially just for documentation and so we can push the assumption about how `TransferLeaseRequest` works up a level to where we're actually interacting with the request type.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 374 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-O7Vckcx9Ts-UH15aGms:-O7eSa7F7uHpIhhJ3MKj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1eb376c89ccbf73946f07d5d7e9c6acca8c704/pkg/kv/kvserver/replica_range_lease.go#L374)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: acquisition/extension?
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/batcheval/cmd_lease_request.go` line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-O7Va_1j-TygGCu1uVFy:-O7eSr-I-8xWTzryrGaI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1eb376c89ccbf73946f07d5d7e9c6acca8c704/pkg/kv/kvserver/batcheval/cmd_lease_request.go#L89)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: might be worth reminding the reader that `MinExpiration` isn't supported for expiration based leases.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
>> I may be missing something, but do we need this RevokeAndForwardNextStart boolean? IIUC, we're not really using it, as cmd_lease_transfer.go was doing this unconditionally anyway. Is it just for symmetry with the lease extension case?

> You're correct. It's not actually needed because cmd_lease_transfer.go is doing this unconditionally. This is essentially just for documentation and so we can push the assumption about how TransferLeaseRequest works up a level to where we're actually interacting with the request type.

I switched this to an assertion.

@arulajmani this should be ready for one more look.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r4, 5 of 5 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130700#-:-O7fMHtz2psCBMw8FOAJ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Pull request merged**
