### PR TITLE
kv: rename ReplicaType LEARNER to LEARNER_EPHEMERAL

### PR DESCRIPTION
**Pull request by aayushshah15**
As we work towards adding support for persistent learner replicas, we'd
like to decouple it from the ephemeral learner state. Conceptually,
learners in their current state are an _internal_ intermediate state
used for atomic replication changes, whereas persistent learners are
meant to be a user-visible state explicitly chosen to be placed in
specific localities.

There are also some practical reasons that motivated this change:
1. The replicate queue, when it discovers a learner replica, infers that
it must be a relic of a failed `ChangeReplicas` run, and clears it up.
2. The raft snapshot queue doesn't send it snapshots since these
learners are supposed to receive it directly from the `ChangeReplicas`
txn.
3. We disallow range merges when we detect that either of the concerned
ranges have a learner replica, as in our current state, this is likely
because there is an ongoing atomic configuration change.

In all of these scenarios it seems safer & more efficient to be able
to differentiate between persistent & ephemeral learners based on the
ReplicaType (as opposed to some other solution like a `isPersistent` bit
on the replica descriptor)

This PR performs this change with a combination of Goland-rename and
then grepping for string literals and comments that talk about learners.
Note that the `SnapshotRequest_LEARNER` type has not been changed in
this PR.

Touches #51943.

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
I've leaned towards being pedantic around the changes in the comments & string literals, only letting them stay unchanged if either the statement applies to _both_ types of learners or if it's entirely obvious from the surrounding context.

**Review by andreimatei — COMMENTED** [review]
LGTM

Let's get @tbg's opinion too. An alternative to this would be to leave ephemeral/long-lived learners undifferentiated in the proto, but generally access them through a wrapper that has access to the zone configuration and can make up its mind on the fly on what type of learner a replica should be considered to be. I like this PR better though; it probably results in clearer state machines.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52048#-:-MDu2zdbE-Gbxz3meZb4:b-e7syw7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by tbg — APPROVED** [review]
No concerns here, I like this rename no matter what, even if in the future we somehow ended up deciding that we wanted to keep only one learner type we could rename it back, but I doubt it will come to that.

**Comment by aayushshah15** [comment]
Since persistent learners are not going to make 20.2, I'll hold off on merging this until the release branch is cut.

**Comment by aayushshah15** [comment]
This PR is now a part of #53715, so I'm closing this.

**Pull request closed without merging**
