### PR TITLE
workload/movr: better fake data generation

### PR DESCRIPTION
**Pull request by danhhz**
This includes a partial port of the faker python library to the
workload/faker package.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
@tbg feels like the faker stuff could use some tests, any opinions on what would be most useful? I think I'd mostly like to verify the lazy initialization (the movr workload is built into the cockroach binary and I want to avoid the allocs at startup if you're not using the workload), but not entirely sure how to do that

**Review by tbg — APPROVED** [review]
:lgtm:

For testing, it'd be good to get some very basic coverage (i.e. just set up a deterministic rng and call each gen 3 times, verifying the outcome). No good idea about testing the absence of allocs. I'd just avoid any global vars in that package and put some comments in the right place (`dict.go`?) mentioning why things are set up without globals. That is, if there isn't a good reason to have that singleton-init'ed global that I'm unaware of.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-:-Lhev88l3J1RDA2qBW-1:b6is9fo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/workload/faker/address.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-LheshN-4zR7fM15dSyg:-LheshN-4zR7fM15dSyh:b2cut2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/address.go#L35)):*
> ```Go
> 
> func (f *addressFaker) buildingNumber(rng *rand.Rand) string {
> 	return strconv.Itoa(randInt(rng, 1000, 99999))
> ```

Interesting that you don't dip below 1k.
___
*[pkg/workload/faker/faker.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-Lhet3Js1tYLBI5MCh43:-Lhet3Js1tYLBI5MCh44:b-m2b6hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/faker.go#L27)):*
> ```Go
> var faker Faker
> 
> // GetFaker lazily initializes a singleton Faker and returns it.
> ```

Is it worth making it a singleton? It does hold on to a bunch of data but not very much. Are we calling this a lot? I sort of figured we'd only need one of them during workload (per node), but maybe I'm missing a bunch of context.
___
*[pkg/workload/faker/lorem.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-Lheu7q41t_yjXLOC3Xr:-Lheu7q41t_yjXLOC3Xs:b-lsdize) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/lorem.go#L59)):*
> ```Go
> 
> func firstToUpper(s string) string {
> 	isFirst := true
> ```

I didn't see you actually use any unicode testdata, but I suppose that's the "correct" way of upper-casing the first letter of a `string`.
___
*[pkg/workload/faker/lorem.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-LheqTi7AE2elG7Q1-UZ:-LheqTi8Dmmu9OxkGJ8u:bsc12pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/lorem.go#L77)):*
> ```Go
> 	f := loremFaker{}
> 	f.words = makeWeightedEntries(
> 		`a`, 1.0,
> ```

Mind pulling those dicts out into a separate file. For example `dict.cc` which contains a handful of methods such as

```go
func words() *weightedEntries {
   return makeWeightedEntries(/* ... */)
}
```
___
*[pkg/workload/faker/name.go, line 530 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-Lhes01f9tUiwbSQ9z5V:-Lhes01f9tUiwbSQ9z5W:b-zay49r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/name.go#L530)):*
> ```Go
> 		`Dalton`, 0.000615113,
> 		`Damon`, 0.00034308,
> 		`Dan`, 0.000388496,
> ```

Who would've thought

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38203)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/workload/faker/address.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-LheshN-4zR7fM15dSyg:-LhfeclLBK7w2FCl1gyf:brzedcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/address.go#L35)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Interesting that you don't dip below 1k.
</blockquote></details>

Just porting the faker logic
___
*[pkg/workload/faker/faker.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-Lhet3Js1tYLBI5MCh43:-Lhfenkh3jquAeWNaEPH:b-eegk7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/faker.go#L27)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is it worth making it a singleton? It does hold on to a bunch of data but not very much. Are we calling this a lot? I sort of figured we'd only need one of them during workload (per node), but maybe I'm missing a bunch of context.
</blockquote></details>

Good call, it's really not that much data
___
*[pkg/workload/faker/lorem.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-Lheu7q41t_yjXLOC3Xr:-LhfnBmu6P9zCFj6O6pb:b-hck6ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/lorem.go#L59)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I didn't see you actually use any unicode testdata, but I suppose that's the "correct" way of upper-casing the first letter of a `string`.
</blockquote></details>

Added tests
___
*[pkg/workload/faker/lorem.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-LheqTi7AE2elG7Q1-UZ:-Lhfifm91WS44MQWXMIJ:bqbi8a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/lorem.go#L77)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mind pulling those dicts out into a separate file. For example `dict.cc` which contains a handful of methods such as

```go
func words() *weightedEntries {
   return makeWeightedEntries(/* ... */)
}
```
</blockquote></details>

Done except I didn't port it to c++ : - p
___
*[pkg/workload/faker/name.go, line 530 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38203#-Lhes01f9tUiwbSQ9z5V:-LhfmiNp7sOzJUnLbGEf:b-1g9y70) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc7aa07d54fa0ac53535bd80e97a06d1888df97/pkg/workload/faker/name.go#L530)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Who would've thought
</blockquote></details>

my last name is in there too. looks like if you generate O(10 million) users you'd expect to get me at some point :grimacing:

**Comment by danhhz** [comment]
bors r=tbg

**Pull request merged**
