### PR TITLE
kvserver: add `SmallEngineBlocks` testing knob and metamorphic params

### LINKED ISSUE #86648: storage: metamorphic tests with small Pebble blocks
In #86256, we add a metamorphic parameter for `TestMVCCHistories` that causes Pebble to write very small blocks and flush after each write, in order to provoke TBI bugs.

We should extend this to other tests too -- maybe even enable it metamorphically for the default Pebble test engine.

Jira issue: CRDB-18853

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by erikgrinaker**
@cockroachdb/repl-prs to do the main review, tagging other teams for visibility/review of metamorphic test params.

Resolves #86648.

---

**kvserver: add `SmallEngineBlocks` testing knob**

This patch adds a store testing knob `SmallEngineBlocks` which
configures Pebble with a block size of 1 byte. This will store every key
in a separate block, which can provoke bugs in time-bound iterators.

Release note: None
  
**sql/logictest: add metamorphic test param for small engine blocks**

Uses a Pebble block size of 1 byte, to provoke bugs in time-bound
iterators.

Release note: None
  
**kvserver/rangefeed: add metamorphic test param for small engine blocks**

Uses a Pebble block size of 1 byte, to provoke bugs in time-bound
iterators.

Release note: None
  
**kvserver/gc: add metamorphic test param for small engine blocks**

Uses a Pebble block size of 1 byte, to provoke bugs in time-bound
iterators.

Release note: None

  
**backupccl: add metamorphic test param for small engine blocks**

Uses a Pebble block size of 1 byte, to provoke bugs in time-bound
iterators.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, @msbutler, and @yuzefovich)

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-NDC0whB1TNeAc571Ui3):*
Any reason they're not metamorphic? I assume a block size of one can also *hide* bugs, though I'll admit that that's somewhat less likely.
___
*[`pkg/server/config.go` line 705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-NDC0VU83eJUffBSGOt1:-NDC0VU83eJUffBSGOt2:bwvo7dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1001937d178c060d4538ba1582a63d46febf6a6e/pkg/server/config.go#L705)):*
> ```Go
> 				cfg.SoftSlotGranter,
> 			}
> 			if storeKnobs.SmallEngineBlocks {
> ```

I'm surprised the in-mem path and this one are so different in how options are configured.
Ah, seeing below that BlockSize() is something you added that does the same thing.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @msbutler, @tbg, and @yuzefovich)

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-NDC0whB1TNeAc571Ui3):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Any reason they're not metamorphic? I assume a block size of one can also *hide* bugs, though I'll admit that that's somewhat less likely.
</blockquote></details>

May as well, done.
___
*[`pkg/server/config.go` line 705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-NDC0VU83eJUffBSGOt1:-NDCl4q_5wU36ifWOMSG:b-5s4nqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1001937d178c060d4538ba1582a63d46febf6a6e/pkg/server/config.go#L705)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm surprised the in-mem path and this one are so different in how options are configured.
Ah, seeing below that BlockSize() is something you added that does the same thing.
</blockquote></details>

Yeah, I suspect the main engine initialization code path got pulled out of `storage.Open` to have direct access to the Pebble config. Could probably be cleaned up, but not doing that now.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, @msbutler, and @tbg)

___
*[`pkg/sql/logictest/logic.go` line 556 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-NDE6bvHC2UdFRUwP-H0:-NDE6bvHC2UdFRUwP-H1:bwcymlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e59112d60b9657600fc9c4641763536282018f/pkg/sql/logictest/logic.go#L556)):*
> ```Go
> 	// smallEngineBlocks configures Pebble with a block size of 1 byte, to provoke
> 	// bugs in time-bound iterators.
> 	smallEngineBlocks = util.ConstantWithMetamorphicTestBool("logictest-small-engine-blocks", false)
> ```

Will this make tests run noticeably slower? Specifically I'm thinking about SQLLite test corpus which usually inserts on the order of few thousands of rows into the table.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @msbutler, @tbg, and @yuzefovich)

___
*[`pkg/sql/logictest/logic.go` line 556 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-NDE6bvHC2UdFRUwP-H0:-NDE75id8h6RXm-RkD8-:bie2bch) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e59112d60b9657600fc9c4641763536282018f/pkg/sql/logictest/logic.go#L556)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Will this make tests run noticeably slower? Specifically I'm thinking about SQLLite test corpus which usually inserts on the order of few thousands of rows into the table.
</blockquote></details>

Yes, it will make tests somewhat slower. For the `fakedist` suite, I believe it was slowed down by something like 20-30%.

**Review by msbutler — APPROVED** [review]
bulk changes look fine!

**Review by yuzefovich — APPROVED** [review]
Logic test change LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-:-NDE82cfAgZ3cXe9fWTx:bk5refl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[`pkg/sql/logictest/logic.go` line 556 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/89026#-NDE6bvHC2UdFRUwP-H0:-NDE7nBm7MUtK12I32od:b98c2n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e59112d60b9657600fc9c4641763536282018f/pkg/sql/logictest/logic.go#L556)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yes, it will make tests somewhat slower. For the `fakedist` suite, I believe it was slowed down by something like 20-30%.
</blockquote></details>

I see. We'll probably need to increase the timeout for that test corpus (currently it's not a problem since we don't set `crdb_test` build flag for nightlies there, but I do want to bring it back).

**Comment by erikgrinaker** [comment]
All CI failures are known flakes. TFTRs!

bors r+

**Pull request merged**
