### PR TITLE
sqlbase: add round-trippable export and parsing for arrays and collated strings

### LINKED ISSUE #33429: importccl: EXPORT/IMPORT does not roundtrip arrays properly
```sql
> export into csv 'nodelocal:///foo.csv' from select array['a','b','c'];
  filename | rows | bytes
+----------+------+-------+
  n1.0.csv |    1 |    15
(1 row)


> import table zc(x text[]) csv data ('nodelocal:///foo.csv');
pq: "nodelocal:///foo.csv": row 1: parse "x" as STRING[]: array must be enclosed in { and }:
```

### LINKED ISSUE #44414: `tree.FmtExport` does not wrap strings with quotes
Found during investigation in #44322. 

`tree.DNull` and "NULL" serialize to the same string because `tree.FmtExport` does not wrap strings with quotes.

`ARRAY['hel, lo']` serializes to "ARRAY[hel,lo]", causing a future parse error.

### PR DESCRIPTION
**Pull request by rohany**
Work for #44322.
Fixes #33429.
Fixes #44414.
Closes #44669.

This PR adds support for ARRAY's and collated strings to be dumped with the
`tree.FmtExport` flag, which dumps datums in a string format that can be
round-tripped with `sqlbase.ParseDatumStringAs`.

This PR additionally performs some code cleanup and renaming
around various parsing functions within the `tree` package.
In particular, this PR removes the function `tree.ParseStringAs` which
was confusingly used sometimes instead of `sqlbase.ParseDatumStringAs`
due to it's handling of raw bytes. Instead, we introduce a new function
`sqlbase.ParseDatumStringAsWithRawBytes` to be more explicit about when
to use one parsing function over the other.

Release note (bug fix): This PR fixes bugs around `cockroach dump` and
`IMPORT`/`EXPORT` where columns of arrays or collated strings would
not be able to be roundtripped from cockroach to the dump and back to cockroach.

### CODE REVIEW

**Comment by rohany** [comment]
I had to move `ParseDatumStringAs` out of `tree` to avoid an import cycle with `parser`.

Since our sql parser already does this work of parsing arrays, I used that instead of trying to adjust the existing array parser, which was meant for strictly casting strings to arrays (in pg compat style).

**Comment by awoods187** [comment]
Thanks for putting this together @rohany. If possible, it would be great to get this reviewed and merged soon so that we can de-risk the cdc to upsert work needed for several customers.

**Review by knz — COMMENTED** [review]
I somewhat trust the code change to do what it says on the label. I would feel more comfortable with a more thorough test suite (The one included here is very "lightweight") but I also want to admit I don't have concrete recommendations. Ideally, someone (or multiple folk) from the Bulk I/O team could make recommendations about testing best practices.

 

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-:-M-BNLiYARDw_q50h-JC:b-xqo2mu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rohany)

___
*[pkg/sql/sem/tree/parse_string.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BNBZt0WkQxjBoqxxu:-M-BNBZt0WkQxjBoqxxv:b-p8wgus) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sem/tree/parse_string.go#L22)):*
> ```Go
> // TODO (rohany): why do the various import functions depend on this
> //  and not ParseDatumStringAs? What is the "power" of not parsing
> //  the input string as bytes but just keeping it as raw bytes?
> ```

This is a good question. I think this question should get an answer as part of the review process. Ideally MattJ would answer but he's on leave. Maybe ask @dt who is most likely to remember/know about this.
___
*[pkg/sql/sem/tree/parse_string.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMfGkAqM-C7jG_G4p:-M-BMfGmDQzXKy0g9kJq:b8mule6) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sem/tree/parse_string.go#L50)):*
> ```Go
> //  because there are some things outside of this package in tree (like tree_test)
> //  that need the functionality of this (basically the old ParseDatumStringAs).
> //  However, I don't think the name is great.
> ```

Can you place more words in the comment to explain what this function assumes from its input parameters and what guarantees it provides on its output?

Based on that understanding we can work on a better name.
___
*[pkg/sql/sqlbase/roundtrip_format_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMz7E2qjK4eBmrVHh:-M-BMz7E2qjK4eBmrVHi:b4aazxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sqlbase/roundtrip_format_test.go#L91)):*
> ```Go
> // TestParseDatumStringAs tests that datums are roundtrippable between
> // printing with FmtExport and ParseDatumStringAs.
> func TestParseDatumStringAs(t *testing.T) {
> ```

So this test is about `ParseDatumStringAs`. Where are the equivalent tests for the new function?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rohany)

___
*[pkg/sql/sem/tree/parse_string.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMfGkAqM-C7jG_G4p:-M-BOU8L2WDtbpYP5JNj:bi85at0) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sem/tree/parse_string.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you place more words in the comment to explain what this function assumes from its input parameters and what guarantees it provides on its output?

Based on that understanding we can work on a better name.
</blockquote></details>

Ack, i removed the original comment for some reason.

```
// parseStringAs parses s as type t for simple types. Arrays and collated
// strings are not handled. nil, nil is returned if t is not a supported type.
```

It differs from `ParseStringAs` in that it calls the bytes parsing method when `types.Bytes` is requested while `ParseStringAs` doesn't.
___
*[pkg/sql/sqlbase/roundtrip_format_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMz7E2qjK4eBmrVHh:-M-BO2LBBNOaODd_2bAx:b-azm4ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sqlbase/roundtrip_format_test.go#L91)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So this test is about `ParseDatumStringAs`. Where are the equivalent tests for the new function?
</blockquote></details>

What do you mean? `ParseDatumStringAs` and it's test already existed, I just moved it from `tree/parse_string_test.go` into here and added a case for arrays. There is a randomized test for it above in this same file.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rohany)

___
*[pkg/sql/sqlbase/roundtrip_format_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMz7E2qjK4eBmrVHh:-M-BP-0l9IoNbDNUlUI2:bb6dx37) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sqlbase/roundtrip_format_test.go#L91)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

What do you mean? `ParseDatumStringAs` and it's test already existed, I just moved it from `tree/parse_string_test.go` into here and added a case for arrays. There is a randomized test for it above in this same file.
</blockquote></details>

*its

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rohany)

___
*[pkg/sql/sem/tree/parse_string.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMfGkAqM-C7jG_G4p:-M-BQACe6C4U_E3FK-VJ:b6k8uvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sem/tree/parse_string.go#L50)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Ack, i removed the original comment for some reason.

```
// parseStringAs parses s as type t for simple types. Arrays and collated
// strings are not handled. nil, nil is returned if t is not a supported type.
```

It differs from `ParseStringAs` in that it calls the bytes parsing method when `types.Bytes` is requested while `ParseStringAs` doesn't.
</blockquote></details>

`ParseAndRequireString`? I think we already have `XAndRequireY` in other places?
___
*[pkg/sql/sqlbase/roundtrip_format_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMz7E2qjK4eBmrVHh:-M-BPwXJ9UD9d5W2JLsl:bn196x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sqlbase/roundtrip_format_test.go#L91)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

*its
</blockquote></details>

thanks for pointing it out.

For curiosity where is ParseStringMustBe() tested?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rohany)

___
*[pkg/sql/sem/tree/parse_string.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMfGkAqM-C7jG_G4p:-M-BQUJ091VFpfIFvzKA:b-5thqby) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sem/tree/parse_string.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`ParseAndRequireString`? I think we already have `XAndRequireY` in other places?
</blockquote></details>

That makes sense to me.
___
*[pkg/sql/sqlbase/roundtrip_format_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMz7E2qjK4eBmrVHh:-M-BQW5zBdeHtM7t4s6r:b-pbuw3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sqlbase/roundtrip_format_test.go#L91)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

thanks for pointing it out.

For curiosity where is ParseStringMustBe() tested?
</blockquote></details>

It was unexported before, and is used in `ParseStringAs`. `ParseStringAs` was used in a few places and tested there. However, I don't think it had any unit tests. The answer to the above question (about why using `ParseStringAs` rather than `ParseDatumStringAs`) might answer why that is the case.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rohany)

___
*[pkg/sql/sqlbase/roundtrip_format_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BMz7E2qjK4eBmrVHh:-M-BRXOB0f3xgYW7Msy9:b-ej5q3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sqlbase/roundtrip_format_test.go#L91)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

It was unexported before, and is used in `ParseStringAs`. `ParseStringAs` was used in a few places and tested there. However, I don't think it had any unit tests. The answer to the above question (about why using `ParseStringAs` rather than `ParseDatumStringAs`) might answer why that is the case.
</blockquote></details>

Ok that makes sense. I'll be ok wrapping up this review once we have more insight about why this function wasn't used. Please approach your favorite TLs to get the information you need.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @knz)

___
*[pkg/sql/sem/tree/parse_string.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-BNBZt0WkQxjBoqxxu:-M-CJdRm-GMAzPkej3Ku:b-uwy1pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/99469eb79d224bf1801e52ac003b7f4a7c9d0d7d/pkg/sql/sem/tree/parse_string.go#L22)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is a good question. I think this question should get an answer as part of the review process. Ideally MattJ would answer but he's on leave. Maybe ask @dt who is most likely to remember/know about this.
</blockquote></details>

Hm, I think it might be a mistake? I see `csv` uses ParseDatumStringAs so I can't imagine the others actually intended to use something different. I'll try switching all the calls in importccl to be ParseDatumStringAs and see if anything fails.

**Comment by dt** [comment]
I tried changing them and some of our mysql import tests failed with `bytea encoded value ends with incomplete escape sequence`. It looks like mysql dumps bytes in some relatively raw string that does not escape in a way our ParseBytes function, which ParseDatumStringAs calls, expected. It might be that we need to be using something (in vitess probably) do parse those, but in any case I don't expect to always be able to use _our roundtrip_ functions against so foreign data source like mysql.

**Comment by knz** [comment]
Can you explain why we use the same parsing code for pg and mysql data?
Do you think there's a chance our pg parsing code has ever been tweaked to become less strict to accommodate mysql input?

(if so that would be a problem that needs fixing)

I think the proximate way forward is to split the code paths, make a special case for mysql that needs it then fix /homogenize the pg case. 
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by dt** [comment]
We don't exactly use the same parsing code for mysql and pr -- there's a lot of mysql-specific lexing and some parsing but in some places, we do indeed reuse our (pg) parsing functions to get to actual cockroach datums.

**Comment by rohany** [comment]
This is RFAL (now that tests have passed)

**Review by knz — COMMENTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rohany)

___
*[pkg/sql/sem/tree/parse_string.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-GSxVA1jHMorlGEHr4:-M-GSxVA1jHMorlGEHr5:b-xhhqei) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ca040f5627b9d3ab69cdac360c2810bc58816fb/pkg/sql/sem/tree/parse_string.go#L21)):*
> ```Go
> // unchanged. Otherwise s is parsed with the given type's Parse func. This function is
> // used when the input string might be unescaped raw bytes, so we don't want to run
> // a bytes parsing routine on that input.
> ```

Maybe you can refer to the other function in this comment and also explain in this comment the difference between the two.
___
*[pkg/sql/sem/tree/parse_string.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-GSefz3KAC0hjGxhxQ:-M-GSeg-4N_OLhvKmF6g:b8mowx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ca040f5627b9d3ab69cdac360c2810bc58816fb/pkg/sql/sem/tree/parse_string.go#L29)):*
> ```Go
> 		d = NewDBytes(DBytes(s))
> 	case types.CollatedStringFamily:
> 		d, err = NewDCollatedString(s, t.Locale(), &evalCtx.CollationEnv)
> ```

Collated strings can also contain escape sequences. Is this not supported?
___
*[pkg/sql/sqlbase/roundtrip_format.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-GSCG_-1yy0lXKiRwN:-M-GSCGa2kbNUL4DRMKb:byvaobk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ca040f5627b9d3ab69cdac360c2810bc58816fb/pkg/sql/sqlbase/roundtrip_format.go#L26)):*
> ```Go
> 		return parseArray(evalCtx, t, s)
> 	case types.CollatedStringFamily:
> 		return tree.NewDCollatedString(s, t.Locale(), &evalCtx.CollationEnv)
> ```

huh are you sure about this one. That doesn't seem right. See my previous comment.

Also where are the tests for this.

**Review by rohany — COMMENTED** [review]
Updated, RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-:-M-GtpKNBScAcrkWLFKi:b-rq6ivc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rohany)

___
*[pkg/sql/sem/tree/parse_string.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-GSxVA1jHMorlGEHr4:-M-Gtef9Cjy8CCE3MTMT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ca040f5627b9d3ab69cdac360c2810bc58816fb/pkg/sql/sem/tree/parse_string.go#L21)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe you can refer to the other function in this comment and also explain in this comment the difference between the two.
</blockquote></details>

Done
___
*[pkg/sql/sem/tree/parse_string.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-M-GSefz3KAC0hjGxhxQ:-M-Gtfdr-E34_zk_nkkF:b2xpdu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ca040f5627b9d3ab69cdac360c2810bc58816fb/pkg/sql/sem/tree/parse_string.go#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Collated strings can also contain escape sequences. Is this not supported?
</blockquote></details>

Good eye -- this was existing code, but it was incorrect (especially for roundtripping). Updated and added to the randomized tester.

**Review by knz — COMMENTED** [review]
Code LGTM, but this PR is missing a couple of release notes. The bug fix should include a description of the symptoms a user would encounter prior to your fix.

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44464#-:-M-JzAdmABQ49QhhJJoF:b-khu2ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rohany)

**Comment by rohany** [comment]
Thanks for the careful review! Updated.

**Comment by rohany** [comment]
bors r=knz

**Pull request merged**
