### PR TITLE
sql: fix error-on-COMMIT sometimes leaving the txn open

### LINKED ISSUE #7198: sql: close transaction on COMMIT/ROLLBACK irrespective of error
It seems that when (not using our SAVEPOINT restarts and) COMMIT fails, we are waiting for an explicit rollback before allowing the next transaction, which is in contrast to Postgres.

```
Aman Goel @amangoeliitb_twitter: Another problem
We are trying to run 2 concurrent transactions
They look like this -
Transaction 1:
READ A
WRITE B
Transaction 2:
READ B
WRITE A
One of the transaction fails.
But then when another transaction is started in the client where the transaction fails, it gives the following error:
pq: current transaction is aborted, commands ignored until end of transaction block
We tested it on postgres and it doesn't happen in postgres (we are using transaction isolation level as serializable in postgres)
Here are the commands that we are running: https://gist.github.com/amangoeliitb/6cca9f37fe94582b7db4f2192a080d75

Any help would be appreciated
On postgres, a failed commit automatically calls a rollback and we don't have to explicitly rollback the transaction
On cockroachdb, if a commit fails, an explicit rollback has to be sent

Andrei Matei @andreimatei 18:09
hey can anyone else try go generate ./… at head pretty please?

Tamir Duberstein @tamird 18:10
it will likely fail at head - try it at cockroachdb/cockroach#7196 if it does

Tobias Schottdorf @tschottdorf 18:10
yeah, does fail at head
@amangoeliitb_twitter so essentially you’re saying with Postgres you can do BEGIN; COMMIT[fail] and then immediately do another BEGIN, and that that isn’t true with CockroachDB, correct?

Aman Goel @amangoeliitb_twitter 18:12
Yes
exactly

Tobias Schottdorf @tschottdorf 18:16
I just tried BEGIN; intentional_garbage; BEGIN; and it does begin a new transaction, but emits a warning (Postgres)
Might be different when the actual COMMIT fails, but at least in that situation it seems ok to disallow the BEGIN

Garvit Juniwal @garvitjuniwal 18:17
@tschottdorf I think it does not warn on COMMIT failure

Tobias Schottdorf @tschottdorf 18:17
yes, I’m looking at that now. Seems more reasonable to accept it in that case.

Garvit Juniwal @garvitjuniwal 18:17
COMMIT/ROLLBACK close the transaction irrespective of whether they generate an error
 
```

### PR DESCRIPTION
**Pull request by andreimatei**
fixes #7198

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7282)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm: but I recommend another pair of eyes on this too.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/txn_restart_test.go, line 766 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPMw0VPJw49jPS1aW8:-KKPMw0VPJw49jPS1aW9:-424744809) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L766)):*
> ```Go
> 		"boulanger": 1,
> 	}
> 	defer cmdFilters.AppendFilter(
> ```

Why is this deferred?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-:-KKPN1FUnk6ALDHv63jb:464717200)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/txn_restart_test.go, line 616 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPO5rcTd372VgglmI9:-KKPO5rcTd372VgglmIA:678148092) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L616)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	// We need to do everything on one connection.
> ```

why?

---

*[sql/txn_restart_test.go, line 657 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPOPtCgADy51OCAJdp:-KKPOPtDBa5wykK_yeFK:742325543) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L657)):*
> ```Go
> 		}
> 		if _, err := sqlDB.Exec("COMMIT;"); !testutils.IsError(err, "pq: restart transaction") {
> 			t.Fatal("expected commit to fail")
> ```

`t.Fatalf("unexpected error: %v", err)`

---

*[sql/txn_restart_test.go, line 766 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPMw0VPJw49jPS1aW8:-KKPNo_AzK03JDQsl7YH:-1340352906) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L766)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Why is this deferred?
</details>
note the extra `()` on the end; this was not previously cleaning up after itself.

---

*[sql/txn_restart_test.go, line 815 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPNvDAymZ2LQUrr64P:-KKPNvDAymZ2LQUrr64Q:-1913807809) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L815)):*
> ```Go
> 	defer cleanupFilter()
> 
> 	// We need to do everything on one connection.
> ```

Cool story; why?

---

*[sql/testdata/serializable_eager_restart, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPNydxdgySL5ro0NcK:-KKPNydxdgySL5ro0NcL:-2026086125) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5d4fbe18b0f3ec70e5d85a406b5c83cc6ee6e4/sql/testdata/serializable_eager_restart#L39)):*
> ```
> 
> statement ok
> ROLLBACK
> ```

replace this with something else (e.g. `SELECT 1`) so we can see that the connection is live

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-:-KKPOY_sh5NCtjGtaoer:1417088721)*

**Comment by andreimatei** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/txn_restart_test.go, line 616 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPO5rcTd372VgglmI9:-KKQ8wPenh1ljmIT1ENR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L616)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why?
</details>
Done.

---

*[sql/txn_restart_test.go, line 657 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPOPtCgADy51OCAJdp:-KKQ9IcuEAQNjXmZEpzY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L657)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `t.Fatalf("unexpected error: %v", err)`
</details>
Done.

---

*[sql/txn_restart_test.go, line 815 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPNvDAymZ2LQUrr64P:-KKQ9K6QwozRcKsKh14q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d3e81ba30436e489d426f13a32db7fd05cc864/sql/txn_restart_test.go#L815)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Cool story; why?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-:-KKQI1qvUgI-JOYFsWYg:1417088721)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/testdata/serializable_eager_restart, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282#-KKPNydxdgySL5ro0NcK:-KKQIMvAv4qE7n1s5tNX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5d4fbe18b0f3ec70e5d85a406b5c83cc6ee6e4/sql/testdata/serializable_eager_restart#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> replace this with something else (e.g. `SELECT 1`) so we can see that the connection is live
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7282)*

**Pull request merged**
