### PR TITLE
ccl/jwtauthccl: add user mapping to JWT auth

### PR DESCRIPTION
**Pull request by kpatron-cockroachlabs**
Previously, JWT auth wasn't optimized for third party token issuers. In order to better support customers running in public clouds, we decided we needed to better support this.

To accomplish this there are 3 changes that are being made:
* restrict JWT auth so it can't be used to login with root
* allow multiple audiences for a cluster (since customers may not be able to control the audiences field for third party issued tokens)
* allow customers to map the subjects of tokens to valid SQL users (since customers may not be able to control the subject field for third party issued tokens)

The third part of this is the most involved.
An example of why this is needed. If you wanted to use a JWT issued for a GCP service account, you previously couldn't because the subject is a user id like 113794436627259432046. Since that is not a valid sql username, we need to do some kind of mapping.

We decided to reuse the existing identity map for this purpose. When a user logs in with a JWT, the cluster checks if there is a ident map with the map name equal to the issuer field of the token. If there is, it uses the map to translate the subject to a user.

As an example, we can set the identity_map.configuration to:
```
https://accounts.google.com    113794436627259432046    kyle
https://accounts.google.com    /^([9-0]*)$              g_\1
email_example                  /^([^@]+)@.*$            email_\1
```
Then I can log in to the kyle or g_113794436627259432046 user
using the following invocations (113794436627259432046  is the
user id for kpatron-testing@kpatron-sandbox.iam.gserviceaccount.com):
```
psql "port=26257 host=localhost user=kyle
password=`gcloud auth print-identity-token
--impersonate-service-account=
"kpatron-testing@kpatron-sandbox.iam.gserviceaccount.com"
--audiences="test_cluster"` options=--crdb:jwt_auth_enabled=true"
```
```
psql "port=26257 host=localhost user=g_113794436627259432046
password=`gcloud auth print-identity-token
--impersonate-service-account=
"kpatron-testing@kpatron-sandbox.iam.gserviceaccount.com"
--audiences="test_cluster"` options=--crdb:jwt_auth_enabled=true"
```

Release note (enterprise change): User mapping, and support for multiple audiences has been added to JWT auth in order to better integrate with third party JWT issuers.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs and @rafiss)

___
*[`-- commits` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-ND-mhc-8F7N90iBt-nr):*
I think the example would be more compelling if it wasn't implicitly suggesting that the operator would ned to modify the identity map manually every time they add or remove a user from their org :)

Maybe something like this:
```
https://accounts.google.com  ^([0-9]*)$     sql_\1
```

i.e. prepend the `sql_` prefix to the number-only UID to generate a SQL name, regardless of user.
___
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-ND-nnmj7uuEUW8TYjY5:-ND-nnmj7uuEUW8TYjY6:b-1bos03) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9f94304b5632f35b76467338050bfd272aa209/pkg/ccl/testccl/authccl/testdata/jwt#L138)):*
> ```
> ok defaultdb
> 
> subtest end
> ```

can we also include some full auth test with an identity map?

**Review by kpatron-cockroachlabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`-- commits` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-ND-mhc-8F7N90iBt-nr):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I think the example would be more compelling if it wasn't implicitly suggesting that the operator would ned to modify the identity map manually every time they add or remove a user from their org :)

Maybe something like this:
```
https://accounts.google.com  ^([0-9]*)$     sql_\1
```

i.e. prepend the `sql_` prefix to the number-only UID to generate a SQL name, regardless of user.

</blockquote></details>

Good point. I added two examples, one like the one you suggested as that's relevant to GCP and then one that demonstrates how this could be used if the subject field on your tokens is an email address.
___
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-ND-nnmj7uuEUW8TYjY5:-ND3m3qb8QpN4bF7ASag:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9f94304b5632f35b76467338050bfd272aa209/pkg/ccl/testccl/authccl/testdata/jwt#L138)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

can we also include some full auth test with an identity map?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
i just had a minor comment, which i'm fine leaving up to you

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-:-ND4-HYK-A5ToQjmpFYg:b-126js3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @kpatron-cockroachlabs, and @rafiss)

___
*[`pkg/sql/pgwire/identmap/ident_map.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-ND3z8K79tyLS84s3WCa:-ND3z8K79tyLS84s3WCb:b-cn641y) ([raw file](https://github.com/cockroachdb/cockroach/blob/08063d079157aaf12d2d1145f306bca2c68e0fe9/pkg/sql/pgwire/identmap/ident_map.go#L132)):*
> ```Go
> 
> // HasMap returns true if there are entries for the given map name.
> func (c *Conf) HasMap(mapName string) bool {
> ```

is this necessary? we can avoid an extra map lookup if the existing `Map` function is changed to return a `present bool` value. or just do the `nil` check when it's called (after doing the `err` check). there's only one usage of this function.

that approach also seems more inline with the golang map access conventions

**Review by kpatron-cockroachlabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/pgwire/identmap/ident_map.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-ND3z8K79tyLS84s3WCa:-ND4OSThE0xetSe2Dctc:b-p51jgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/08063d079157aaf12d2d1145f306bca2c68e0fe9/pkg/sql/pgwire/identmap/ident_map.go#L132)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this necessary? we can avoid an extra map lookup if the existing `Map` function is changed to return a `present bool` value. or just do the `nil` check when it's called (after doing the `err` check). there's only one usage of this function.

that approach also seems more inline with the golang map access conventions
</blockquote></details>

Good point. I will add it as an boolean to the return type.

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 7 files at r2, 4 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

**Review by knz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88858#-:-ND8hvNi7o8CIqzSQjE_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @rafiss)

**Pull request merged**
