### PR TITLE
kv/kvserver: fix TestStoreMetrics by stopping automatic compactions

### LINKED ISSUE #90631: kvserver: TestStoreMetrics is flakey
**Describe the problem**

It's failed 3 in the last 20. https://teamcity.cockroachdb.com/test/-743047615087228185?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&branch=%3Cdefault%3E&expandTestHistoryChartSection=true

Here's a failure: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/7125033?showRootCauses=false&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

`client_metrics_test.go:168: gauge rocksdb.table-readers-mem-estimate = 0 < min 50`

### PR DESCRIPTION
**Pull request by coolcom200**
Previously the `TestStoreMetrics` test was running into an issue where
an automatic compaction would cause entries in the
`pebble.Metrics.TableCache` to be evicted before the test was able to
validate the data. In order to resolve this an additional testing knob
was added to allow for `storage.ConfigOptions` to be provided.

Release note: None
Closes: #90631 
Epic: CRDB-20293

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Thanks for tracking this down!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91166#-:-NFyfnEi037D4QvXRJj_:b-4evfnn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @coolcom200)

___
*[`pkg/kv/kvserver/testing_knobs.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91166#-NFyfMAp688kF5bcPQr7:-NFyfMAp688kF5bcPQr8:b-m58ygc) ([raw file](https://github.com/cockroachdb/cockroach/blob/feb54bdd95bcb7d1c921868938472bb4a162a5e8/pkg/kv/kvserver/testing_knobs.go#L126)):*
> ```Go
> 	LeaseTransferBlockedOnExtensionEvent func(nextLeader roachpb.ReplicaDescriptor)
> 	// DisableAutomaticCompactions disable automatic compactions
> 	DisableAutomaticCompactions bool
> ```

How about we make this a `ConfigOptions []storage.ConfigOption` so we can propagate arbitrary `storage.ConfigOption`s without expanding this testing knob struct.

**Review by jbowens — APPROVED** [review]
:lgtm:

Nice!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91166#-:-NG2Yo1p0iZu_qpZGrCV:bli1pub)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @coolcom200)

**Comment by coolcom200** [comment]
TFTR! bors r=jbowens

**Comment by coolcom200** [comment]
bors r=jbowens

**Pull request merged**
