### PR TITLE
roachtest: adjust tpch_concurrency a bit

### LINKED ISSUE #104238: roachtest: tpch_concurrency failed
roachtest.tpch_concurrency [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10338231?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10338231?buildTab=artifacts#/tpch_concurrency) on master @ [e2b704df25b012baf7d5fbe26e034f520a70f25c](https://github.com/cockroachdb/cockroach/commits/e2b704df25b012baf7d5fbe26e034f520a70f25c):

```
test artifacts and logs in: /artifacts/tpch_concurrency/run_1
(test_runner.go:1027).runTest: test timed out (18h0m0s)
(cluster.go:1995).Start: ~ ./cockroach.sh
cockroach service already active
To get more information: systemctl status cockroach: COMMAND_PROBLEM: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpch_concurrency.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28423

### PR DESCRIPTION
**Pull request by yuzefovich**
Since we enabled GOMEMLIMIT by default in 23.1, `tpch_concurrency` roachtest has become less of a benchmark of stability and more a sanity check. In particular, we now usually can sustain the maximum concurrency in the binary search range (centered around 1000). This commit codifies that change of the test to make it run at 1000 concurrency 3 times and fail the test if 2 or 3 iterations result in a node crash. This should make it unlikely for the test to timeout while providing a good sanity check on the stability. Also, this commit disables the backups.

Fixes: #104238.

Release note: None

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/tpch_concurrency.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104281#-NWyjwr17b7IpfRvUpLv:-NWyhUsi11fH-qt1KywV:b-l65qgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3722dad82f681b866bd063b812af1c2d8ee3a4b9/pkg/cmd/roachtest/tests/tpch_concurrency.go#L107)):*
> ```Go
> 				}
> 				if queryNum == 21 {
> 					if rand.Float64() < 0.5 {
> ```

It's difficult for me to reason about what effect this will have on the precision and accuracy of the benchmark. If Q21 is sometimes the sensitive query, couldn't the mixture of skipping and not skipping it throw off the binary search? Why not always skip it?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/cmd/roachtest/tests/tpch_concurrency.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104281#-NWyjwr17b7IpfRvUpLv:-NWyvApSCi-ryQckj34S:b-tlx6wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3722dad82f681b866bd063b812af1c2d8ee3a4b9/pkg/cmd/roachtest/tests/tpch_concurrency.go#L107)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It's difficult for me to reason about what effect this will have on the precision and accuracy of the benchmark. If Q21 is sometimes the sensitive query, couldn't the mixture of skipping and not skipping it throw off the binary search? Why not always skip it?
</blockquote></details>

Since we enabled GOMEMLIMIT by default this roachtest became less of a benchmark - it now _usually_ hits the highest end of the search range https://roachperf.crdb.dev/?filter=&view=tpch_concurrency&tab=gce. I think of it now more as a sanity check that we haven't regressed on stability sufficiently (the test will fail if all six iterations fail). Skipping Q21 all the time could make us more blind to stability on that query - with the current PR and skipping it in 50% cases we could at least examine the logs (like imagine that Q21 always OOMs the cluster, the test doesn't fail, but we could manually look at the log (if curious) to see that Q21 is the crasher; anecdotally IIRC Q21 is one of the heaviest queries, so I'd prefer to keep it in).

**Review by michae2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/tpch_concurrency.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104281#-NWyjwr17b7IpfRvUpLv:-NXBomtb-YxINhbRtwkN:bv3wg8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3722dad82f681b866bd063b812af1c2d8ee3a4b9/pkg/cmd/roachtest/tests/tpch_concurrency.go#L107)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Since we enabled GOMEMLIMIT by default this roachtest became less of a benchmark - it now _usually_ hits the highest end of the search range https://roachperf.crdb.dev/?filter=&view=tpch_concurrency&tab=gce. I think of it now more as a sanity check that we haven't regressed on stability sufficiently (the test will fail if all six iterations fail). Skipping Q21 all the time could make us more blind to stability on that query - with the current PR and skipping it in 50% cases we could at least examine the logs (like imagine that Q21 always OOMs the cluster, the test doesn't fail, but we could manually look at the log (if curious) to see that Q21 is the crasher; anecdotally IIRC Q21 is one of the heaviest queries, so I'd prefer to keep it in). 
</blockquote></details>

I see. If we're now using this as less of a benchmark and more of a regression test, would it make sense to get rid of the binary search and run once at concurrency=1000? That would also help it finish before the timeout, right?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/cmd/roachtest/tests/tpch_concurrency.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104281#-NWyjwr17b7IpfRvUpLv:-NXCTTw5Bgux7h9udAZW:b82mb2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3722dad82f681b866bd063b812af1c2d8ee3a4b9/pkg/cmd/roachtest/tests/tpch_concurrency.go#L107)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I see. If we're now using this as less of a benchmark and more of a regression test, would it make sense to get rid of the binary search and run once at concurrency=1000? That would also help it finish before the timeout, right?
</blockquote></details>

Yeah, that's a good point, I like this suggestion, done.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104281#-:-NXCasarCy1GcQozdWCI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
