### PR TITLE
core: fix and add test for per locality hosts

### LINKED ISSUE #29591: core: --locality-advertise-addr flag isn't hooked up
The contents of the `--locality-advertise-addr` flag never actually get plumbed into the server/gossip code, meaning that the feature almost certainly doesn't work.

The `localityAddress` arg to `Node.start` is unused:
https://github.com/cockroachdb/cockroach/blob/44a5f0685eed55ef76a437e1cc196ebe9e33c757/pkg/server/node.go#L396

The `NodeDescriptor.LocalityAddress` field never actually gets set anywhere in our code:
https://sourcegraph.com/github.com/cockroachdb/cockroach@master/-/blob/pkg/roachpb/metadata.pb.go#L166:2=&tab=references

That should be fixed and the feature tested end-to-end.

### PR DESCRIPTION
**Pull request by m-schneider**
Connected the existing code and added an acceptance roachtest.

Closes #29591.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/gossip.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMhLAi2C-tgikyd8Y5M:-LMhLAi2C-tgikyd8Y5N:b8yczrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L407)):*
> ```Go
> }
> 
> func runCheckLocalityIpAddress(ctx context.Context, t *test, c *cluster) {
> ```

A roachtest is kind of a heavy way to test this; it could also be an acceptance test or I think a CLI/tcl test.

**Review by a-robinson — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmjvrI8fW5TdETtBT6:-LMmjvrI8fW5TdETtBT7:bmio5qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cli/flags.go#L525)):*
> ```Go
> 	serverCfg.HTTPAddr = net.JoinHostPort(serverHTTPAddr, serverHTTPPort)
> 	for i, addr := range localityAdvertiseHosts {
> 		localityAdvertiseHosts[i].Address.AddressField = net.JoinHostPort(addr.Address.AddressField, serverAdvertisePort)
> ```

For consistency with all of @knz's recent changes to the CLI flags, `--locality-advertise-addr` should be made to support the port being included in the provided addresses. We've pretty strongly adopted the stance that `addr` means "host with an optional port" and that `addr` flags are preferred over the less-flexible `host` flags.
___
*[pkg/cli/flags.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmku5JBQd2f-Qt4XdD:-LMmku5JBQd2f-Qt4XdE:b-oyakfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cli/flags.go#L527)):*
> ```Go
> 		localityAdvertiseHosts[i].Address.AddressField = net.JoinHostPort(addr.Address.AddressField, serverAdvertisePort)
> 	}
> 	serverCfg.LocalityIPAddresses = localityAdvertiseHosts
> ```

Not a big deal, but why `LocalityIPAddresses` instead of just `LocalityAddresses` given that it's perfectly valid for these to be domain names rather than IPs?
___
*[pkg/cmd/roachtest/gossip.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmlBdjBAgLJOWJaWle:-LMmlBdjBAgLJOWJaWlf:b-u6tmb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L410)):*
> ```Go
> 	c.Put(ctx, cockroach, "./cockroach")
> 
> 	externalIp := c.ExternalIP(ctx, c.Range(1, c.nodes))
> ```

nit, but `externalIp` should be `externalIP` (in the function name too)

https://github.com/golang/go/wiki/CodeReviewComments#initialisms

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmjvrI8fW5TdETtBT6:-LNBv-Ua4Hk8oGYwGTds:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cli/flags.go#L525)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

For consistency with all of @knz's recent changes to the CLI flags, `--locality-advertise-addr` should be made to support the port being included in the provided addresses. We've pretty strongly adopted the stance that `addr` means "host with an optional port" and that `addr` flags are preferred over the less-flexible `host` flags.
</blockquote></details>

Done!
___
*[pkg/cli/flags.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmku5JBQd2f-Qt4XdD:-LNBnht197fn-joFrxIt:b6ljlsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cli/flags.go#L527)):*
> LocalityIPAddresses
Makes Sense
___
*[pkg/cmd/roachtest/gossip.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMhLAi2C-tgikyd8Y5M:-LNBmlcZ6PRqqHQDuYtK:btuuw4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L407)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

A roachtest is kind of a heavy way to test this; it could also be an acceptance test or I think a CLI/tcl test. 
</blockquote></details>

Can you test remote vs local IPs in one of those or is it just localhost vs 127.0.0.1?
___
*[pkg/cmd/roachtest/gossip.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmlBdjBAgLJOWJaWle:-LNBnVSS5g5hvVPcyRKf:b-b01451) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L410)):*
> externalIp
Fixed.

**Review by a-robinson — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmjvrI8fW5TdETtBT6:-LNCT61q0MtA2w-wySJi:b3ior2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cli/flags.go#L525)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Done!
</blockquote></details>

Nice, thanks! Would you mind also updating one of the examples in the flag help text in cli/cliflags/flags.go to include a port?
___
*[pkg/cmd/roachtest/gossip.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMhLAi2C-tgikyd8Y5M:-LNCZ3D7BkYma1J8oFWp:btxucdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L407)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Can you test remote vs local IPs in one of those or is it just localhost vs 127.0.0.1?
</blockquote></details>

You could use IPs and container names as two different address types in a docker acceptance test. I'm not aware of any precedent for multi-node tests in the cli unit or interactive tests, but really if all the test is doing is checking `crdb_internal.gossip_nodes`, a single node is probably good enough.
___
*[pkg/cmd/roachtest/gossip.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmlBdjBAgLJOWJaWle:-LNCR03-A00EpxeHvziV:b7z2ro8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L410)):*
> ```
> runCheckLocalityIpAddress
> ```
Doesn't look like the function name changed? s/runCheckLocalityIpAddress/runCheckLocalityIPAddress

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/gossip.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMhLAi2C-tgikyd8Y5M:-LNR1QbS57zlSgoDnB5P:bqs81jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L407)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You could use IPs and container names as two different address types in a docker acceptance test. I'm not aware of any precedent for multi-node tests in the cli unit or interactive tests, but really if all the test is doing is checking `crdb_internal.gossip_nodes`, a single node is probably good enough.
</blockquote></details>

The `acceptance` roachtests are fairly lightweight as they share a cluster. The primary overhead is the initial cluster creation which is amortized. 
___
*[pkg/cmd/roachtest/gossip.go, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNR2XT85aJe_QBiVwun:-LNR2XT85aJe_QBiVwuo:b-qyrj6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b1df81bf2796a29b698eec013af340737d25a3/pkg/cmd/roachtest/gossip.go#L418)):*
> ```Go
> 		extAddr := externalIP[i-1]
> 
> 		c.Start(ctx, c.Node(i), startArgs("--racks=1", fmt.Sprintf("--args=--locality-advertise-addr=rack=0@%s", extAddr)))
> ```

What is the `--racks=1` being used for?
___
*[pkg/cmd/roachtest/gossip.go, line 426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNR1qBj2FUBgH--f_xd:-LNR1qBj2FUBgH--f_xe:b4lk87u) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b1df81bf2796a29b698eec013af340737d25a3/pkg/cmd/roachtest/gossip.go#L426)):*
> ```Go
> 	rows, err := db.Query(
> 		`SELECT node_id, connect_address FROM crdb_internal.gossip_nodes`,
> 	)
> ```

I believe `crdb_internal.gossip_nodes` can differ from node-to-node. I wonder if this should be run against every node. That is, wrap this in a `for i := 1; i <= c.nodes; i++ {` loop.
___
*[pkg/sql/crdb_internal.go, line 1739 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNRR17zB84kAGcRgn08:-LNRR17zB84kAGcRgn09:b91lgs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b1df81bf2796a29b698eec013af340737d25a3/pkg/sql/crdb_internal.go#L1739)):*
> ```Go
>   network         	STRING NOT NULL,
>   address         	STRING NOT NULL,
>   connect_address   STRING NOT NULL,
> ```

I wonder if this should be named `advertise_address`? Or perhaps we should be replacing the existing `address` column.

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmjvrI8fW5TdETtBT6:-LNl1x00Dfe8Qn5p6tjw:bu7dejo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cli/flags.go#L525)):*
>  cli/cliflags/flags.go
Done!
___
*[pkg/cmd/roachtest/gossip.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMhLAi2C-tgikyd8Y5M:-LNl20yb8ZYUezGNxLm4:blpiytw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L407)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `acceptance` roachtests are fairly lightweight as they share a cluster. The primary overhead is the initial cluster creation which is amortized. 
</blockquote></details>

Got it so there's no need for special logic for 1 node?
___
*[pkg/cmd/roachtest/gossip.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMmlBdjBAgLJOWJaWle:-LNl2t_LCKIOdLJdROlD:bfa4eme) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L410)):*
> runCheckLocalityIpAddress
Done
___
*[pkg/cmd/roachtest/gossip.go, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNR2XT85aJe_QBiVwun:-LNl34X_1dhfqT2b0JDs:b87x10i) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b1df81bf2796a29b698eec013af340737d25a3/pkg/cmd/roachtest/gossip.go#L418)):*
> for i := 1; i <= c.nodes; i++
It was the most straight forward way to add a locality without knowing which regions everything is running in.
___
*[pkg/cmd/roachtest/gossip.go, line 426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNR1qBj2FUBgH--f_xd:-LNl47da-2Z46k02v3tA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b1df81bf2796a29b698eec013af340737d25a3/pkg/cmd/roachtest/gossip.go#L426)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe `crdb_internal.gossip_nodes` can differ from node-to-node. I wonder if this should be run against every node. That is, wrap this in a `for i := 1; i <= c.nodes; i++ {` loop.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1739 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNRR17zB84kAGcRgn08:-LNl4GieAUrUVOQyzAml:b-sdgxuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b1df81bf2796a29b698eec013af340737d25a3/pkg/sql/crdb_internal.go#L1739)):*
> advertise_address
I kept the existing one, just in case we ever needed for debugging, advertise_address is a better name than connect_address.

**Review by a-robinson — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-:-LNlHvXCBxCidjkY2agi:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/gossip.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LMhLAi2C-tgikyd8Y5M:-LNlGtcnAhqFeEehRmhK:b-nb93xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e8f20be2711f1c02c6407e0682fec1e6308e1c/pkg/cmd/roachtest/gossip.go#L407)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Got it so there's no need for special logic for 1 node?
</blockquote></details>

I'm happy with the test as-is. It certainly would have caught the bug fixed by this PR and will catch a future regression.
___
*[pkg/cmd/roachtest/gossip.go, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNR2XT85aJe_QBiVwun:-LNlH4O1DnfZy_WtS4K6:bvee5e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b1df81bf2796a29b698eec013af340737d25a3/pkg/cmd/roachtest/gossip.go#L418)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

> for i := 1; i <= c.nodes; i++
It was the most straight forward way to add a locality without knowing which regions everything is running in.
</blockquote></details>

Ack. I missed the `rack=00x` part of the locality-advertise-addr flag.
___
*[pkg/cmd/roachtest/gossip.go, line 444 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNlHlcwACNrl3AfDzPQ:-LNlHlcwACNrl3AfDzPR:bef0ulm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac8380d7fe374c0fa94627a7bacee0875a034db/pkg/cmd/roachtest/gossip.go#L444)):*
> ```Go
> 				}
> 			} else if c.ExternalAddr(ctx, c.Node(nodeID))[0] != advertiseAddress {
> 				t.Fatal(fmt.Sprintf("Connection address is %s but expected %s", advertiseAddress, c.ExternalAddr(ctx, c.Node(nodeID))[0]))
> ```

`t.Fatalf` is a simpler way of saying `t.Fatal(fmt.Sprintf())`.

Nit: you have a variety of lines that are much longer than 100 columns which makes the diff more challenging to review in reviewable.
___
*[pkg/cmd/roachtest/gossip.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNlHGjm7-YIOO_Qk_6a:-LNlHGjm7-YIOO_Qk_6b:b-h7stmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac8380d7fe374c0fa94627a7bacee0875a034db/pkg/cmd/roachtest/gossip.go#L446)):*
> ```Go
> 				t.Fatal(fmt.Sprintf("Connection address is %s but expected %s", advertiseAddress, c.ExternalAddr(ctx, c.Node(nodeID))[0]))
> 			}
> 		}
> ```

The test will incorrectly succeed if the query returns no rows (i.e. `rows.Next()` returns `false` on the first iteration).

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/gossip.go, line 444 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNlHlcwACNrl3AfDzPQ:-LNlKcGh8bQNk0XmCGrK:b28afxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac8380d7fe374c0fa94627a7bacee0875a034db/pkg/cmd/roachtest/gossip.go#L444)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`t.Fatalf` is a simpler way of saying `t.Fatal(fmt.Sprintf())`.

Nit: you have a variety of lines that are much longer than 100 columns which makes the diff more challenging to review in reviewable.
</blockquote></details>

Cleaned up.
___
*[pkg/cmd/roachtest/gossip.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNlHGjm7-YIOO_Qk_6a:-LNlKe1kE-AmTFtRhYm_:b-bfm97u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac8380d7fe374c0fa94627a7bacee0875a034db/pkg/cmd/roachtest/gossip.go#L446)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The test will incorrectly succeed if the query returns no rows (i.e. `rows.Next()` returns `false` on the first iteration).
</blockquote></details>

Added a counter.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30359)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/gossip.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30359#-LNlHGjm7-YIOO_Qk_6a:-LNpeQbdEIWOvLrCtFdP:b-1uiw4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac8380d7fe374c0fa94627a7bacee0875a034db/pkg/cmd/roachtest/gossip.go#L446)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Added a counter.
</blockquote></details>

I think this should be inside the for-loop. And don't you want the number of rows to be equal to the number of nodes?

**Pull request merged**
