### PR TITLE
sql: implement REGIONAL BY ROW AS

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Implement REGIONAL BY ROW AS ..., which
allows a column of type crdb_internal_region to be used as a column for
REGIONAL BY ROW multi-region properties.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSmMnBEZ57gYN0i-_F:-MRSmMnBEZ57gYN0i-_G:b-jowqve) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L25)):*
> ```
> LOCALITY REGIONAL BY ROW
> 
> statement error cannot implicitly create REGIONAL BY ROW column as column crdb_region already exists
> ```

Nit: Does it make more sense to word this from the user's perspective?  "cannot specify crdb_region column in REGIONAL BY ROW table as one is implicitly created by the system"?
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSmh1-2d-ODgzIXYZW:-MRSmh1-2d-ODgzIXYZX:b-snikkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L178)):*
> ```
> ap-southeast-2  23  24  25
> 
> statement error  cannot use column INT8 which has type crdb_region_col in REGIONAL BY ROW AS
> ```

Did you get the order of these %q's wrong? :-P
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSmyRW-dRMfgEJhbOf:-MRSmyRW-dRMfgEJhbOg:b-rp72a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L194)):*
> ```
>   a int,
>   b int,
>   crdb_region_col crdb_internal_region,
> ```

This is very cool.  Do we get computed regional columns for free now?  If so, can we test them here?
___
*[pkg/sql/create_table.go, line 1411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSncYF5ag2fjx880ms:-MRSncYF5ag2fjx880mt:b3552d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/sql/create_table.go#L1411)):*
> ```Go
> 							pgcode.InvalidTableDefinition,
> 							"cannot use column %s which has type %s in REGIONAL BY ROW AS",
> 							t.SQLString(),
> ```

Ahh, the culprit!
___
*[pkg/sql/create_table.go, line 1420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSo3M887RL7sHH_G2n:-MRSo3M887RL7sHH_G2o:bq2xt6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/sql/create_table.go#L1420)):*
> ```Go
> 							err = errors.WithDetailf(
> 								err,
> 								"REGIONAL BY ROW AS must reference a column of type %s.",
> ```

Can you please add a testcase for this case?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSmh1-2d-ODgzIXYZW:-MRSreDK-0ZcmbiCenBz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L178)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Did you get the order of these %q's wrong? :-P
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSmyRW-dRMfgEJhbOf:-MRSrwpV6gEFt7nDPMF6:b7v01fy) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L194)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

This is very cool.  Do we get computed regional columns for free now?  If so, can we test them here?
</blockquote></details>

Huh guess so. Added tests.
___
*[pkg/sql/create_table.go, line 1411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSncYF5ag2fjx880ms:-MRSrifp7JX5pvWRCjXx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/sql/create_table.go#L1411)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Ahh, the culprit!
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSo3M887RL7sHH_G2n:-MRSrtc-4EBbQhyDtaL1:bm4i0p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/sql/create_table.go#L1420)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can you please add a testcase for this case?
</blockquote></details>

already tested, but added this to the regex

**Review by ajstorm — APPROVED** [review]
Awesome!  :lgtm: 

Left import changes for @dt.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-:-MRT-PpkDDMD0Uu5zgpJ:b-ct1xqz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSmyRW-dRMfgEJhbOf:-MRSzcONEK3OQGtx3Fk7:bnae4hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L194)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Huh guess so. Added tests.
</blockquote></details>

:tada:  What a wonderful surprise!

I'm sure the team would be very excited to hear about this (specifically Nathan, Andrei and Becca).  I'll let you break the good news.

**Comment by otan** [comment]
bors r=ajstorm

surprise feature best feature

**Comment by rytaft** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59121#-MRSmyRW-dRMfgEJhbOf:-MRUn-MBBTJnFF7mXENv:b44uc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6688567a6802499095383edb60e9929af8e893/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L194)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

:tada:  What a wonderful surprise!

I'm sure the team would be very excited to hear about this (specifically Nathan, Andrei and Becca).  I'll let you break the good news.
</blockquote></details>

🎉

**Pull request merged**
