### PR TITLE
kvserver: deflake TestPromoteNonVoterInAddVoter

### LINKED ISSUE #101519: kv/kvserver: TestPromoteNonVoterInAddVoter failed
kv/kvserver.TestPromoteNonVoterInAddVoter [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9606449?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9606449?buildTab=artifacts#/) on master @ [8e6cdbd8b3d12ba5d65db101a3abfeb2cb1bf470](https://github.com/cockroachdb/cockroach/commits/8e6cdbd8b3d12ba5d65db101a3abfeb2cb1bf470):

```
=== RUN   TestPromoteNonVoterInAddVoter
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/d486233d291fa43f53db749aea077e75/logTestPromoteNonVoterInAddVoter3018638515
    test_log_scope.go:79: use -show-logs to present logs inline
    replicate_queue_test.go:2349: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/replicate_queue_test.go:2349
        	Error:      	Expected to promote non-voter, instead added voter
        	Test:       	TestPromoteNonVoterInAddVoter
        	Messages:   	Added voter store ID: 6
        	            	Add voter events: [{r63:/{Table/104-Max} [(n3,s3):1, (n2,s2):2, (n1,s1):7, (n6,s6):8NON_VOTER, (n4,s4):9, next=10, gen=32] <nil> <nil> (n4,s4):9 <nil> range under-replicated {"Target":"s4, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:62"}} {r63:/{Table/104-Max} [(n3,s3):1, (n2,s2):2, (n1,s1):7, (n6,s6):8, (n4,s4):9, next=10, gen=33] <nil> <nil> (n6,s6):8 <nil> range under-replicated {"Target":"s6, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:62"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):2, (n1,s1):7, (n6,s6):11LEARNER, next=12, gen=44] <nil> <nil> (n6,s6):11LEARNER <nil> range under-replicated {"Target":"s6, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:61"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):2, (n1,s1):7, (n6,s6):11, next=12, gen=45] <nil> <nil> (n6,s6):11 <nil> range under-replicated {"Target":"s6, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:61"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):2, (n1,s1):7, (n6,s6):11, (n4,s4):12LEARNER, next=13, gen=46] <nil> <nil> (n4,s4):12LEARNER <nil> range under-replicated {"Target":"s4, necessary:true, diversity:0.88, converges:0, balance:0, rangeCount:61"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):2, (n1,s1):7, (n6,s6):11, (n4,s4):12, next=13, gen=47] <nil> <nil> (n4,s4):12 <nil> range under-replicated {"Target":"s4, necessary:true, diversity:0.88, converges:0, balance:0, rangeCount:61"}}]
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d486233d291fa43f53db749aea077e75/logTestPromoteNonVoterInAddVoter3018638515
--- FAIL: TestPromoteNonVoterInAddVoter (30.90s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPromoteNonVoterInAddVoter.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26986

### PR DESCRIPTION
**Pull request by kvoli**
It is possible for span config updates to arrive at different times
between stores. `TestPromoteNonVoterInAddVoter` was flaking when the
incoming leaseholder would act upon a stale span config, before
receiving the updated one which the outgoing leaseholder used.

This resulted in the test failing as more than just the two expected
promotion events appeared in the range log, as the incoming leaseholder
removed voters, then subsequently added them back upon receiving the
up to date span configuration. 

#103086 tracks this issue.

This PR checks on the prefix of the range log add voter events, to
avoid failing the test when this untimely behavior occurs.

Stressed overnight, removing the skip under stress flag:

```
dev test pkg/kv/kvserver -f TestPromoteNonVoterInAddVoter -v --stress --stress-args="-p 4"
...
27158 runs so far, 0 failures, over 12h56m55s
```

This PR also adds additional (v=6) logging of the range descriptor and span config,
as these come in handy when debugging failures such as this.

Fixes: https://github.com/cockroachdb/cockroach/issues/101519

Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm: This is pretty subtle and complex. I am surprised that the zone config takes so long to transfer, but I suppose it makes sense since there are only metadata changes happening (no snapshot transfers). I wonder if we should write in the lease record which zone config we based our decision on, so that we avoid this, but I agree this isn't a big enough problem to really try and address short term.

**Comment by kvoli** [comment]
TYFTR - I updated the vmodule from 5 to 6 as it is a big hammer.

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Comment by kvoli** [comment]
bor r-

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Comment by kvoli** [comment]
blathers backport 23.1

**Pull request merged**
