### PR TITLE
roachpb: Transaction.LastHeartbeat is non-nullable

### PR DESCRIPTION
**Pull request by tamird**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5753)

### CODE REVIEW

**Comment by tschottdorf** [comment]
I think you should disallow `BeginTransaction` with `LastHeartbeat.Equal(roachpb.ZeroTimestamp)`.

**Comment by tschottdorf** [comment]
Or make BeginTransaction set `LastHeartbeat=OrigTimestamp` (but only on the request that creates the txn entry, not on restarts).

**Comment by tschottdorf** [comment]
Pushed a commit which fixes the test failure (feel free to squash).

**Comment by tamird** [comment]
Thanks! squash and add a transitional method. PTAL

**Comment by tschottdorf** [comment]
:lgtm: except for discussing that transitional thing's lifetime.

---

Reviewed 6 of 10 files at r1, 1 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[roachpb/data.go, line 856 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-KEBHMvrBRkX4-BgJxC3:-KEBHMvsVL1HNjWquI-D:1175312697) ([raw file](https://github.com/cockroachdb/cockroach/blob/874cd68f48c0b65ee05a9b8d78eb35ae3547d5ab/roachpb/data.go#L856)):*
Good thinking. Can we slate this for removal though? I realize we probably don't have a process for it, but we'll need one anyway so this might be the time to think about it. Essentially we need to decide how big of a version spread we allow in clusters. No limit is convenient for the user, but very inconvenient for us. A tight limit is great for us, but means that users can only upgrade the binary in small steps (depending on how bad not sticking to the limit is). Thoughts?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-:-KEBI6PHQuwvVT48bskF:2110749225)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/data.go, line 856 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-KEBHMvrBRkX4-BgJxC3:-KEBf3vVARxNOlJ5VZYZ:1790200108) ([raw file](https://github.com/cockroachdb/cockroach/blob/874cd68f48c0b65ee05a9b8d78eb35ae3547d5ab/roachpb/data.go#L856)):*
This is the price of backward compatibility. I can see us keeping around this method for a while (it is kruft, but not awful). It is also a good example of where the RPC version number could be used. At some point we could require that servers running a new version do not support an older version. It doesn't make sense to add a whole new set of RPC methods for a change like this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 6 of 10 files at r1, 1 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[roachpb/data.go, line 856 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-KEBHMvrBRkX4-BgJxC3:-KEC1g9p2qtYG0g_BVzT:-792708560) ([raw file](https://github.com/cockroachdb/cockroach/blob/874cd68f48c0b65ee05a9b8d78eb35ae3547d5ab/roachpb/data.go#L856)):*
The RPC version number alone isn't enough; Transactions are persisted to disk. (on the other hand, they're not terribly long-lived and since we're not yet guaranteeing zero-downtime restarts we could just abort any transactions that are pending when upgrading to a version that has removed this function).

I think that post-1.0 we should support upgrading from old versions for a long time (at least a year, probably longer. People perform database upgrades very infrequently). In beta we can be a little more flexible but I'd still like to aim for a clean upgrade path from the earliest beta to 1.0. Maybe the next version after 1.0 can drop all the pre-beta upgrade stuff.

---

*[roachpb/data.proto, line 255 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-KEC35wlESd3cxUjnA65:-KEC35wlESd3cxUjnA66:-995222108) ([raw file](https://github.com/cockroachdb/cockroach/blob/874cd68f48c0b65ee05a9b8d78eb35ae3547d5ab/roachpb/data.proto#L255)):*
Should we give this a name like `UnexposedLastHeartbeat` to force everything to go through the getter? (we have another name like this somewhere)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-:-KEC3_8UHgqUfca894yu:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[roachpb/data.go, line 856 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-KEBHMvrBRkX4-BgJxC3:-KEC40TI0Ucar6YaXYQj:-1668818405) ([raw file](https://github.com/cockroachdb/cockroach/blob/874cd68f48c0b65ee05a9b8d78eb35ae3547d5ab/roachpb/data.go#L856)):*
Yeah, I think I may just remove this since we're not guaranteeing zero-downtime upgrades yet.

---

*[roachpb/data.proto, line 255 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753#-KEC35wlESd3cxUjnA65:-KEC4AH-7iPPl1oDQKUB:-952691908) ([raw file](https://github.com/cockroachdb/cockroach/blob/874cd68f48c0b65ee05a9b8d78eb35ae3547d5ab/roachpb/data.proto#L255)):*
I didn't do that because the intention is that this field will not remain "Unexposed". Anyway, I'm going to remove that getter, so this becomes moot.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5753)*

**Comment by tschottdorf** [comment]
Another thing to worry about is that running this version and its predecessor can immediately kill consistency (one node sets LastHeartbeat, the others leave it nil).

We really can't apply Raft commands at all in inhomogeneously versioned clusters unless we have very tight guarantees on them not having changed semantics in any way.

**Comment by tamird** [comment]
Right, but again, we don't have hitless upgrades in beta, so it's cool.

**Comment by bdarnell** [comment]
@tschottdorf Good point. And even a stop-the-world upgrade doesn't guarantee that all nodes are on the same position in their raft logs. I think the previous version with a transitional function was safe, but the new version is not.

**Comment by tschottdorf** [comment]
I think generally we want to make sure that we have all nodes at the same log position when they resume (or do something else that's complicated, but same log position eliminates a lot of surprises)

> Right, but again, we don't have hitless upgrades in beta, so it's cool.

But what does hitless mean? I think it should be able to upgrade an old cluster stop-the-world without having diverging replicas.

**Comment by tamird** [comment]
Yeah, I'll restore this, and note that it should be removed in 1.0.

**Comment by tschottdorf** [comment]
btw, will the zero timestamp marshal to something nontrivial (i.e. anything different from the nullable version?)
That would be another way in which we'd diverge.

**Comment by bdarnell** [comment]
Yes, it will. Good catch. So changing the nullability of a field in a proto that is written by raft commands is not safe without a much more complex migration plan. :(

**Comment by tschottdorf** [comment]
While we're at it, have we spent any reasonable effort into outlining how we’re actually going to keep our clean migration path as we want it? I’d expect every little change from now on to introduce a bundle of things which break compat in ways we don’t even notice. Viewfinder seems to have done a lot of work on this, how about a write-up? And looks like it's time for a concerted effort to get a framework/functionality together that can serve our migration goals for some time.

**Comment by petermattis** [comment]
@tschottdorf Fleshing out the migration story should definitely be a goal for Q2.

**Comment by bdarnell** [comment]
> So changing the nullability of a field in a proto that is written by raft commands is not safe without a much more complex migration plan. :(

Actually, it's worse than that: we can no longer add non-nullable fields safely to anything that gets persisted by a raft command. Any new fields will have to be nullable in order to make the transition safe. 

> Viewfinder seems to have done a lot of work on this, how about a write-up?

A good idea, but we need something more than what viewfinder did because cockroachdb is peer-to-peer. Things were simplified for viewfinder because we could rely on the asymmetry of the client/server system and the fact that we knew for sure when old server versions were gone.

**Comment by tschottdorf** [comment]
This change seems like a good baby case to get a good Raft migration story
into place. It's small, insignificant but does need all the stuff a proper
migration needs.

**Comment by bdarnell** [comment]
Maybe, but this one could also be resolved without a true raft migration story. Raft doesn't require bit-for-bit equivalence, it just requires functional equivalence. Our consistency checker enforces bit-for-bit equivalence because that's the easiest thing to measure, but if we could look into the protobuf encoding we (for keys that are known to hold encoded protos) then we could normalize proto values to discard things like unnecessarily-encoded zero values. It's a bit hacky but it might be better than tying our hands for all future proto changes. (we'll need an RFC for real raft-level migrations too, but I think it's better to view that as independent of this change)

**Comment by tschottdorf** [comment]
I'm not opposed to the encoding change (if that's reasonable to implement,
sounds like a good idea anyway on general principle). If it's not, we don't
need this change for anything, and an unnecessarily nullable field isn't
worth bending over backwards for.

**Review by bdarnell — APPROVED** [review]

**Pull request merged**
