### PR TITLE
pgwire: add detailed error message for index out of bounds in decodeBinaryTuple

### PR DESCRIPTION
**Pull request by ecwall**
refs https://github.com/cockroachdb/cockroach/issues/77796

Release note (bug fix): Added a detailed error message for index out of bounds
when decoding a binary tuple datum. This does not fix the root cause, but
should give more insight into what is happening.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78637)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-MzM8bhG4_wyLY0QeXJt:-MzM8bhG4_wyLY0QeXJu:bmw1btv) ([raw file](https://github.com/cockroachdb/cockroach/blob/230bf57d1e5660f09eebad915239bfd5e2f5a4c9/pkg/sql/pgwire/pgwirebase/encoding.go#L991)):*
> ```Go
> 	}
> 
> 	totalLength := int32(len(b))
> ```

i just realized that some of these values should be uint32 since they deal with slice lengths/indexes. specifically, `totalLength`, `curByte`, and `nextByte`

`elementLength` should still be int32 (as per https://www.npgsql.org/dev/types.html)

making this change should actually fix the original issue completely.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-MzM6Rtn5mQ7HWX5LEPn:-MzM6Rtn5mQ7HWX5LEPo:b-dhn56x) ([raw file](https://github.com/cockroachdb/cockroach/blob/230bf57d1e5660f09eebad915239bfd5e2f5a4c9/pkg/sql/pgwire/pgwirebase/encoding.go#L1003)):*
> ```Go
> 		return pgerror.Newf(
> 			pgcode.Syntax,
> 			"%s curByte=%d nextByte=%d elementLength=%d totalLength=%d curIdx=%d numberOfElements=%d",
> ```

i think it's best to keep the error message not too verbose. ultimately, the only person seeing this message will be the end-user, not us (at least in 99% of cases). so i'd err on the side of not overloading the user with information that looks like internal-only information.

what about just including the following and avoid naming them using the internal variable names

```
tupleIdx=%d bufferLength=%d bufferStartIdx=%d bufferEndIdx=%d
```
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1012 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-MzM6Bv5DDnaqk64UaOF:-MzM6Bv5DDnaqk64UaOG:b-lse6bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/230bf57d1e5660f09eebad915239bfd5e2f5a4c9/pkg/sql/pgwire/pgwirebase/encoding.go#L1012)):*
> ```Go
> 		nextByte = curByte + elementLength
> 		if nextByte < curByte {
> 			return nil, getSyntaxError("decode tuple - integer overflow reading element OID for binary format - ")
> ```

nit: we can remove "decode tuple - " from all of these messages

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78637)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-MzM8bhG4_wyLY0QeXJt:-N-4HbX83HUtBjUopmxm:bclnig2) ([raw file](https://github.com/cockroachdb/cockroach/blob/230bf57d1e5660f09eebad915239bfd5e2f5a4c9/pkg/sql/pgwire/pgwirebase/encoding.go#L991)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i just realized that some of these values should be uint32 since they deal with slice lengths/indexes. specifically, `totalLength`, `curByte`, and `nextByte`

`elementLength` should still be int32 (as per https://www.npgsql.org/dev/types.html)

making this change should actually fix the original issue completely.
</blockquote></details>

The issue is still possible even with uint32 since you can overflow it by having large elements, it just makes maximum buffer size 2x as big.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-MzM6Rtn5mQ7HWX5LEPn:-N-4Hxhq1DJonRy0pApk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/230bf57d1e5660f09eebad915239bfd5e2f5a4c9/pkg/sql/pgwire/pgwirebase/encoding.go#L1003)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think it's best to keep the error message not too verbose. ultimately, the only person seeing this message will be the end-user, not us (at least in 99% of cases). so i'd err on the side of not overloading the user with information that looks like internal-only information.

what about just including the following and avoid naming them using the internal variable names

```
tupleIdx=%d bufferLength=%d bufferStartIdx=%d bufferEndIdx=%d
```
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1012 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-MzM6Bv5DDnaqk64UaOF:-N-4HyY07XKCeZdFT7hx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/230bf57d1e5660f09eebad915239bfd5e2f5a4c9/pkg/sql/pgwire/pgwirebase/encoding.go#L1012)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: we can remove "decode tuple - " from all of these messages
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
i just had a few nits, but feel free to merge after addressing them

i'm OK if we change to use unsigned ints later. just so it's clear, this is what i was proposing:
```
diff --git a/pkg/sql/pgwire/pgwirebase/encoding.go b/pkg/sql/pgwire/pgwirebase/encoding.go
index 6d1c806aef..c87a05434c 100644
--- a/pkg/sql/pgwire/pgwirebase/encoding.go
+++ b/pkg/sql/pgwire/pgwirebase/encoding.go
@@ -994,7 +994,7 @@ const tupleHeaderSize, oidSize, elementSize = 4, 4, 4
 
 func decodeBinaryTuple(evalCtx *tree.EvalContext, b []byte) (tree.Datum, error) {
 
-	bufferLength := int32(len(b))
+	bufferLength := len(b)
 	if bufferLength < tupleHeaderSize {
 		return nil, pgerror.Newf(
 			pgcode.Syntax,
@@ -1002,7 +1002,7 @@ func decodeBinaryTuple(evalCtx *tree.EvalContext, b []byte) (tree.Datum, error)
 			tupleHeaderSize, bufferLength)
 	}
 
-	bufferStartIdx := int32(0)
+	bufferStartIdx := 0
 	bufferEndIdx := bufferStartIdx + tupleHeaderSize
 	numberOfElements := int32(binary.BigEndian.Uint32(b[bufferStartIdx:bufferEndIdx]))
 	if numberOfElements < 0 {
@@ -1034,8 +1034,7 @@ func decodeBinaryTuple(evalCtx *tree.EvalContext, b []byte) (tree.Datum, error)
 
 	for elementIdx < numberOfElements {
 
-		bytesToRead := int32(oidSize)
-		bufferEndIdx = bufferStartIdx + bytesToRead
+		bufferEndIdx = bufferStartIdx + oidSize
 		if bufferEndIdx < bufferStartIdx {
 			return nil, getSyntaxError("integer overflow reading element OID for binary format - ")
 		}
@@ -1051,8 +1050,7 @@ func decodeBinaryTuple(evalCtx *tree.EvalContext, b []byte) (tree.Datum, error)
 		typs[elementIdx] = elementType
 		bufferStartIdx = bufferEndIdx
 
-		bytesToRead = int32(elementSize)
-		bufferEndIdx = bufferStartIdx + bytesToRead
+		bufferEndIdx = bufferStartIdx + elementSize
 		if bufferEndIdx < bufferStartIdx {
 			return nil, getSyntaxError("integer overflow reading element size for binary format - ")
 		}
@@ -1060,12 +1058,12 @@ func decodeBinaryTuple(evalCtx *tree.EvalContext, b []byte) (tree.Datum, error)
 			return nil, getSyntaxError("insufficient bytes reading element size for binary format - ")
 		}
 
-		bytesToRead = int32(binary.BigEndian.Uint32(b[bufferStartIdx:bufferEndIdx]))
+		bytesToRead := int32(binary.BigEndian.Uint32(b[bufferStartIdx:bufferEndIdx]))
 		bufferStartIdx = bufferEndIdx
 		if bytesToRead == -1 {
 			datums[elementIdx] = tree.DNull
 		} else {
-			bufferEndIdx = bufferStartIdx + bytesToRead
+			bufferEndIdx = bufferStartIdx + int(bytesToRead)
 			if bufferEndIdx < bufferStartIdx {
 				return nil, getSyntaxError("integer overflow reading element for binary format - ")
 			}

```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-:-N-UlcmM61TvODJqrDkh:buqf3df)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-MzM8bhG4_wyLY0QeXJt:-MzSc2o9CwYMQxAtQCbh:b-iq10y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/230bf57d1e5660f09eebad915239bfd5e2f5a4c9/pkg/sql/pgwire/pgwirebase/encoding.go#L991)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

The issue is still possible even with uint32 since you can overflow it by having large elements, it just makes maximum buffer size 2x as big.
</blockquote></details>

right, we still need all the checks either way
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1001 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-Ui_iv5hxGytkW0Fr6:-N-Ui_iv5hxGytkW0Fr7:byu7x7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1001)):*
> ```Go
> 		return nil, pgerror.Newf(
> 			pgcode.Syntax,
> 			"tuple requires a %d byte header for binary format - bufferLength=%d",
> ```

we should use a period instead of a hyphen (here and in the messages below)
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1011 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-UiJ5I5yZo60dDObu0:-N-UiJ5L2MedsBXIaWUS:b-vgtogf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1011)):*
> ```Go
> 		return nil, pgerror.Newf(
> 			pgcode.Syntax,
> 			"tuple must have non-negative number of elements - bufferLength=%d numberOfElements=%d",
> ```

don't think we need to show bufferLength here
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1025 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-UgSBxCbXwkrj31emA:-N-UgSBxCbXwkrj31emB:b43ly6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1025)):*
> ```Go
> 		var formattedMessage string
> 		if len(args) > 0 {
> 			formattedMessage = fmt.Sprintf(message, args)
> ```

you should be able to use Sprintf unconditionally, i think?
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1043 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-UioZQ3I6RhpCpygT0:-N-UioZR0J7YNzB3AjmW:b9cq0bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1043)):*
> ```Go
> 		}
> 		if bufferLength < bufferEndIdx {
> 			return nil, getSyntaxError("insufficient bytes reading element OID for binary format - ")
> ```

end with a period instead of hyphen/space

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78637)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1001 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-Ui_iv5hxGytkW0Fr6:-N-YPsDzB1xjKUlBg0YU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1001)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should use a period instead of a hyphen (here and in the messages below)
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1011 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-UiJ5I5yZo60dDObu0:-N-YPZa80w2ksc2q14qJ:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1011)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

don't think we need to show bufferLength here
</blockquote></details>

Removed.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1025 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-UgSBxCbXwkrj31emA:-N-YP_fhCKpfj041Edpy:bp5bdvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1025)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you should be able to use Sprintf unconditionally, i think?
</blockquote></details>

I thought so too, but it is appending `%!(EXTRA []interface {}=[])` to the output.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1043 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-UioZQ3I6RhpCpygT0:-N-YPqeA2W83BggdM0uL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1043)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

end with a period instead of hyphen/space
</blockquote></details>

Done.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78637)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 1025 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78637#-N-UgSBxCbXwkrj31emA:-N-YQ1VK8wZfVVmYuxKs:buqcvpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ea989027b71c7357a8267e0e1ba6e306ab4a94/pkg/sql/pgwire/pgwirebase/encoding.go#L1025)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I thought so too, but it is appending `%!(EXTRA []interface {}=[])` to the output.
</blockquote></details>

Oh weird it looks like changing it to `fmt.Sprintf(message, args...)` fixes it and also removes the weird `[` `]` around the output when `len(args) == 1`

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
