### PR TITLE
sql: add `CACHE` clause to `SHOW CREATE SEQUENCE` when relevant

### PR DESCRIPTION
**Pull request by ajwerner**
In 21.1 we added support for `CACHE` to sequences but we didn't add the logic
to render that clause.

Release note (bug fix): Render `CACHE` clause for sequences which use a cache.

### CODE REVIEW

**Comment by ajwerner** [comment]
@rafiss feel free to redirect the review elsewhere. cc @ericharmeling

**Review by rafiss — APPROVED** [review]
ty! maybe worth testing in TestShowCreateSequence in show_test.go as well

**Comment by ajwerner** [comment]
> ty! maybe worth testing in TestShowCreateSequence in show_test.go as well

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
