### PR TITLE
storage: take an engine checkpoint during failing consistency checks

### PR DESCRIPTION
**Pull request by tbg**
This takes a checkpoint on the nodes with replicas of a failing range,
before the failure leads to nodes shutting down. The checkpoint will, for
the replicas of the affected range, be taken at the same Raft log position.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
A failed consistency check will effectively leak the checkpoint, which I think is fine for now -- customers running into one are always supposed to (and likely to) contact support.

If we're paranoid about someone running out of disk space after not realizing that they have RocksDB checkpoints created after inconsistencies, we need to figure out a better UX but for now I'd say we add an env var that's set by default when using `roachprod`.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[c-deps/libroach/db.cc, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbBMXpDLtWXiHIQmGU:-LcbBMXpDLtWXiHIQmGV:b-f07cda) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/c-deps/libroach/db.cc#L269)):*
> ```cpp
>     return ToDBStatus(status);
>   }
>   status = cp_ptr->CreateCheckpoint(cp_dir, 0 /* log_size_for_flush */);
> ```

consider saying something about what that 0 does, if it's interesting. I think a lot of people (like myself right now) will stop reading here and not dig into `CreateCheckpoint()` to see.
___
*[c-deps/libroach/db.cc, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbBkdH-xHxMxzbMnUY:-LcbBkdH-xHxMxzbMnUZ:b-dp9zmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/c-deps/libroach/db.cc#L274)):*
> ```cpp
>     return ToDBStatus(status);
>   }
>   return kSuccess;
> ```

can't we always `return ToDBStatus(status);` ?
___
*[c-deps/libroach/include/libroach.h, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbAtQO7Bl-j5-n76fs:-LcbAtQO7Bl-j5-n76ft:b-tmumwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/c-deps/libroach/include/libroach.h#L104)):*
> ```objc
> 
> // Creates a RocksDB checkpoint in the specified directory (which must not exist).
> DBStatus DBCreateCheckpoint(DBEngine* db, DBSlice dir);
> ```

pls put some words about what a checkpoint is - something about hardlinks to current SSTs
___
*[pkg/roachpb/api.proto, line 1144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbB53DDW1vyg0z3wny:-LcbB53DDW1vyg0z3wnz:b-xzfjl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/roachpb/api.proto#L1144)):*
> ```protobuf
>   // If set, a checkpoint (i.e. cheap backup) of the engine will be taken. This
>   // is expected to be set only if we already know that there is an
>   // inconsistency and we want to preserve as much state as possible.
> ```

pls say where the checkpoint will live (how to find it)
___
*[pkg/storage/consistency_queue_test.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbDcEY4y7V7oekAe6v:-LcbDcEY4y7V7oekAe6w:bud7heq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/consistency_queue_test.go#L196)):*
> ```Go
> 	defer cache.Release()
> 
> 	for i := 0; i < numStores; i++ {
> ```

say something about not using in-memory engines because we want to take snapshots. But actually, why can't we use in-mem engines (and still take snapshots)?
___
*[pkg/storage/replica_consistency.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbCASy9q1uJ8vvoBTz:-LcbCASy9q1uJ8vvoBU-:b6i3e9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/replica_consistency.go#L92)):*
> ```Go
> 		// queue is asking us to report a diff, so it has run a previous check
> 		// which failed.
> 		Checkpoint: args.WithDiff && args.Mode == roachpb.ChecksumMode_CHECK_VIA_QUEUE,
> ```

this already confusing dance is becoming even more complex. How about just plumbing a `checkpoint` bool through `args`?
___
*[pkg/storage/replica_proposal.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbC_qv7_rdaN5pxkom:-LcbC_qv7_rdaN5pxkon:b-cdiqjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/replica_proposal.go#L173)):*
> ```Go
> 	if cc.Checkpoint {
> 		checkpointBase := filepath.Join(r.store.engine.GetAuxiliaryDir(), "checkpoints")
> 		_ = os.MkdirAll(checkpointBase, 0700)
> ```

nit: `0700 /* owner rwx /*` 
___
*[pkg/storage/replica_proposal.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbCkAlB1c6pzFbft-m:-LcbCkAlB1c6pzFbft-n:b-hdnb7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/replica_proposal.go#L178)):*
> ```Go
> 			log.Warningf(ctx, "unable to create checkpoint %s: %s", checkpointDir, err)
> 		} else {
> 			log.Infof(ctx, "created checkpoing %s", checkpointDir)
> ```

poing poing
___
*[pkg/storage/engine/engine_test.go, line 804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbD-wT-waLQGGiIHp0:-LcbD-wT-waLQGGiIHp1:b-coahvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/engine/engine_test.go#L804)):*
> ```Go
> 	defer cleanup()
> 
> 	// TODO(tbg): use the method below, but only for on-disk stores.
> ```

sorry, what's going on here?
___
*[pkg/storage/engine/engine_test.go, line 821 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbDD3O5JHtJ26wNaPJ:-LcbDD3O5JHtJ26wNaPK:b-wnjulk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/engine/engine_test.go#L821)):*
> ```Go
> 
> 	assert.NoError(t, err)
> 	assert.NoError(t, db.CreateCheckpoint(dir))
> ```

can you open and read the checkpoint you've just created? (as a RocksDB engine)

**Review by andreimatei — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/consistency_queue_test.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbDcEY4y7V7oekAe6v:-LcbEDQm4jjgNkFn1qjF:b3i3sis) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/consistency_queue_test.go#L196)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

say something about not using in-memory engines because we want to take snapshots. But actually, why can't we use in-mem engines (and still take snapshots)?
</blockquote></details>

what does `engine.GetAuxiliaryDir()` return for in-mem engines? 
___
*[pkg/storage/replica_proposal.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbEXTEDtPkPKDaasLp:-LcbEXTEDtPkPKDaasLq:bivgsxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/replica_proposal.go#L172)):*
> ```Go
> 	snap := r.store.engine.NewSnapshot()
> 	if cc.Checkpoint {
> 		checkpointBase := filepath.Join(r.store.engine.GetAuxiliaryDir(), "checkpoints")
> ```

should we protect against in-mem engines here somehow? What's going to happen for those?
___
*[pkg/storage/replica_proposal.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbEU1e5o0x7IrNAiQn:-LcbEU1e5o0x7IrNAiQo:b-g3fjk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/replica_proposal.go#L173)):*
> ```Go
> 	if cc.Checkpoint {
> 		checkpointBase := filepath.Join(r.store.engine.GetAuxiliaryDir(), "checkpoints")
> 		_ = os.MkdirAll(checkpointBase, 0700)
> ```

why MkdirAll and not Mkdir?

**Review by tbg — COMMENTED** [review]
:lgtm:

@petermattis could you give the C++ changes a glance to make sure I'm not doing something silly with memory mgmt?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-:-LcfEvktCkd9v4ahKkX3:b-49rml1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[c-deps/libroach/db.cc, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbBMXpDLtWXiHIQmGU:-Lcf9ljD-rDMrSMlqvBO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/c-deps/libroach/db.cc#L269)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider saying something about what that 0 does, if it's interesting. I think a lot of people (like myself right now) will stop reading here and not dig into `CreateCheckpoint()` to see.
</blockquote></details>

Done.
___
*[c-deps/libroach/db.cc, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbBkdH-xHxMxzbMnUY:-Lcf9y4X5eFYMjqlyN-Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/c-deps/libroach/db.cc#L274)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can't we always `return ToDBStatus(status);` ?
</blockquote></details>

Done.
___
*[c-deps/libroach/include/libroach.h, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbAtQO7Bl-j5-n76fs:-LcfAQBPB1Vk1m84TVIQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/c-deps/libroach/include/libroach.h#L104)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls put some words about what a checkpoint is - something about hardlinks to current SSTs
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbB53DDW1vyg0z3wny:-LcfAhqY-849c47vIccG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/roachpb/api.proto#L1144)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls say where the checkpoint will live (how to find it)
</blockquote></details>

Done.
___
*[pkg/storage/consistency_queue_test.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbDcEY4y7V7oekAe6v:-LcfAthtEeqquuPZW4Iw:b-t67ygz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/consistency_queue_test.go#L196)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what does `engine.GetAuxiliaryDir()` return for in-mem engines? 
</blockquote></details>

RocksDB abstracts away the file system through an `Env`. An in-memory engine just has an in-memory env. So in-memory engines work if and only if you write everything through the RocksDB env, which basically means you have to slap a full POSIX API into the `Engine` interface. We did some of that (had to) for encryption at rest, but it's not enough. This isn't a yak worth shaving.

In-mem engines actually return a temp dir as the auxiliary dir, mostly to make things "mostly work", but that's not behavior that makes a lot of sense or that I want to rely on in this test.
___
*[pkg/storage/replica_consistency.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbCASy9q1uJ8vvoBTz:-LcfCV2y7tMQtNmUAE_a:b-8rhp40) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/replica_consistency.go#L92)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this already confusing dance is becoming even more complex. How about just plumbing a `checkpoint` bool through `args`?
</blockquote></details>

Done. Agreed that this is better.
___
*[pkg/storage/engine/engine_test.go, line 804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbD-wT-waLQGGiIHp0:-LcfCdOF6H3MDmVf4T2M:b2j0p8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/engine/engine_test.go#L804)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sorry, what's going on here?
</blockquote></details>

Removed. The comment was saying "I want to use runWithAllEngines so that pebble automatically gets this test as well, but we need a version of `runWithAllEngines` that uses non-mem engines". Not worth it right now. The method is in the interface, so pebble will have to learn it anyway.
___
*[pkg/storage/engine/engine_test.go, line 821 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-LcbDD3O5JHtJ26wNaPJ:-LcfE_Fn6EHXpQYdqkLA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d44e47f6c24610681d1a563ae1f716c701559a62/pkg/storage/engine/engine_test.go#L821)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you open and read the checkpoint you've just created? (as a RocksDB engine)
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
PS not sure why I LGTM'ed myself. The button looked too inviting, I guess.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-:-LcfF1dq2Xi8NrNSDu3Q:bkijpb8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

**Comment by andreimatei** [comment]
LGTM

**Comment by tbg** [comment]
TFTR!

bors r=andreimatei

**Comment by tbg** [comment]
bors r=andreimatei

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36867#-:-LcgSd0Z3FQlkL2fnOb9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @tbg)

**Pull request merged**
