### PR TITLE
kubernetes: Remove detritus left around in multiregion setup script

### PR DESCRIPTION
**Pull request by a-robinson**
Release note: None

### CODE REVIEW

**Review by jseldess — APPROVED** [review]
LGTM

**Comment by jseldess** [comment]
___
*[cloud/kubernetes/multiregion/setup.py, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28735#-LK43mVF7WdUAgG5SnDv:-LK43mVGBLN-sIxDiUJg:b-nqfovq) ([raw file](https://github.com/cockroachdb/cockroach/blob/efad3ba92f452c15d4e20fff63d332377b892863/cloud/kubernetes/multiregion/setup.py#L163)):*
> ```Python
> sleep(30)
> for zone, context in contexts.items():
>     check_call(['kubectl', 'create', '-f', 'cluster-init-secure.yaml', '--namespace', zone, '--context', context])
> ```

Is `zone` a problem here, too?

**Comment by mberhault** [comment]
LGTM

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28735)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[cloud/kubernetes/multiregion/setup.py, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28735#-LK43mVF7WdUAgG5SnDv:-LK4Rc_EAVg7GpNQghbt:bbd4ckl) ([raw file](https://github.com/cockroachdb/cockroach/blob/efad3ba92f452c15d4e20fff63d332377b892863/cloud/kubernetes/multiregion/setup.py#L163)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Is `zone` a problem here, too?
</blockquote></details>

No, that's intentional. It means we're creating the cluster-init-secure job in the namespace named after the zone the cluster is running in.

**Pull request merged**
