### PR TITLE
storage: fix lease application race condition

### LINKED ISSUE #23574: storage: Incremental MVCC SysBytes incorrect due to lease acquisition race
Discovered as part of #22687

The incrementally-computed MVCC SysBytes kept with each range can become incorrect due to a race with leases.  This occurs when:

+ Two different lease requests are attempted at the same time
+ Both lease requests succeed, but delta stats are calculated as if both leases were replacing the same original lease.  That is, the original lease was A, then B became lease, then C immediately became the lease. Delta stats should be applied for (sizeof(B) - sizeof(A)), then ((sizeof(C) - sizeof(B)).  However, due to the bug, delta stats are applied for (sizeof(B) - sizeof(A)), then (sizeof(C) - *sizeof(A)*).

The disabled test in #22687 (TestStoreMetrics) verifies this by directly comparing the output of "MVCCComputeStats" with the incrementally computed values. If the lease acquisition race occurs and the size of the stored leases are different than the original lease, the SysBytes count can become skewed as a result.

### PR DESCRIPTION
**Pull request by m-schneider**
Before this change a replica could recieve a lease request which was
evaluated against one lease but applied against a different one. For
example if we had three leases A, B, and C with A being the current lease for a
range. If a replica then recieved lease requests B and C evaluated
against A and B was a lease extension for A, both requests would succeed.
The check to apply lease C would only check to see if the sequence
number associated with the previous lease was the same as the current
lease which it would be because B was an extension and extensions don't
increment sequence numbers. However this check should fail because the lease has
been updated after the lease request was evaluated.

We're now adding the previous proposal timestamp to the
ReplicatedEvalResult which gets changed when a lease is extended so that
we can make sure that we're actually applying a least request against
the correct lease.

closes #23574

Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm: 

There's no reason to believe that this race had consequences other than messing up the stats, right?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/storage/replica.go, line 4496 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228#-L8Z4iH02FHwVkMSOqIq:-L8Z4iH02FHwVkMSOqIr:b-gwizk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5842cd5cf58398f3ac82ace59453573edd684b7/pkg/storage/replica.go#L4496)):*
> ```Go
> 			// leases don't increment sequence numbers upon extension. Without this check
> 			// a lease could have been extended and then the new lease request would be applied against an extension
> 			// which is a different lease.
> ```

We usually say that it's still "the same lease" after extensions (and we have the check of Lease.Sequence above to ensure that we're not reaching this point on a completely independent lease). Instead of calling it "a different lease" I'd say that we take care to apply lease extensions strictly sequentially because doing otherwise would allow discrepancies in the MVCC stats. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228#-:-L8Z47hU93fOTowvP5bP:b-c2qcyr)*

**Comment by tschottdorf** [comment]
I think it's a correctness bug, there's a window of time during which B (the extension to A) would be known to its proposer, but C could be known to its proposer. So there could be commands proposed and applied under C while B would be dishing out stale reads. Exceedingly rare since you'd need perfect timing plus a leaseholder-not-leader condition.

Messing up the stats is actually less of an issue, since we don't use `SysBytes` for anything, plus it's now self-correcting via the consistency checker queue.

:lgtm: mod the open comments, thanks for fixing this so quickly!

---

Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_metrics_test.go, line 110 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24228#-L8Z_q368k4BHAe_ue0f:-L8Z_q368k4BHAe_ue0g:b16v7s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/191896e9f82e75d30da83f170060fa2058b75984/pkg/storage/client_metrics_test.go#L110)):*
> ```Go
> 		checkGauge(t, idString, m.ValCount, realStats.ValCount)
> 		checkGauge(t, idString, m.IntentCount, realStats.IntentCount)
> 		// TODO(mrtracy): Re-enable SysBytes check when #23574 is fixed.
> ```

Also remove this line.

---

*[pkg/storage/replica.go, line 4496 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24228#-L8Z4iH02FHwVkMSOqIq:-L8Z_x1KJrRelGIcca45:b-iyfkoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5842cd5cf58398f3ac82ace59453573edd684b7/pkg/storage/replica.go#L4496)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We usually say that it's still "the same lease" after extensions (and we have the check of Lease.Sequence above to ensure that we're not reaching this point on a completely independent lease). Instead of calling it "a different lease" I'd say that we take care to apply lease extensions strictly sequentially because doing otherwise would allow discrepancies in the MVCC stats. 
</blockquote></details>

Wording should focus on the correctness issue, unless I'm mistaken on there being one.

---

*[pkg/storage/batcheval/result/result.go, line 274 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24228#-L8ZaCblsYoWaBhXhTy1:-L8ZaCblsYoWaBhXhTy2:b-k6dhxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/191896e9f82e75d30da83f170060fa2058b75984/pkg/storage/batcheval/result/result.go#L274)):*
> ```Go
> 		p.Replicated.PrevLeaseProposal = q.Replicated.PrevLeaseProposal
> 	} else if q.Replicated.PrevLeaseProposal != nil {
> 		return errors.New("conflicting lease expiration")
> ```

Message needs fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24228#-:-L8ZZi0OAwLR_dB2RhSH:b-bcde8x)*

**Comment by bdarnell** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 4496 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228#-L8Z4iH02FHwVkMSOqIq:-L8c5AZWB8f4w89F1G4s:bs2rlue) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5842cd5cf58398f3ac82ace59453573edd684b7/pkg/storage/replica.go#L4496)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Wording should focus on the correctness issue, unless I'm mistaken on there being one.
</blockquote></details>

Yeah, I was confused about this. I was thinking lease C was an extension instead of a completely independent lease. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228)*

**Comment by m-schneider** [comment]
Review status: 4 of 10 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_metrics_test.go, line 110 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228#-L8Z_q368k4BHAe_ue0f:-L8mn4vdAT4T_M2T6G7J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/191896e9f82e75d30da83f170060fa2058b75984/pkg/storage/client_metrics_test.go#L110)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Also remove this line.
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 4492 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228#-L8cS5RZ6xm_3RTojm8M:-L8mn5or9dJ_Kx-0FFfj:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65d654d67b3af7d017c5c86ab47f2b310e73829/pkg/storage/replica.go#L4492)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Fundamentally, this issue is possible whether we're using `DeprecatedProposerLease` or `ProposerLeaseSequence`. This is because neither would notice the racing lease extension. We can see this in the `raftCmd.DeprecatedProposerLease != nil` case, where we're checking if `r.mu.state.Lease` is equal to or an extension of `DeprecatedProposerLease`. I actually noticed this a little while ago and assumed it was desired behavior :man_facepalming: In some ways, I still think this is desired behavior. It should be possible for a command to be proposed under a lease without being rejected during evaluation because of a lease extension. The one case we need to be careful about is lease requests themselves, which shouldn't be evaluated under lease extensions. It would be nice if this was spelled out more explicitly here.

This actually reminds me a lot of the fix we made in 9a837c0, which is the block above here. I think all of that logic could be removed and replaced by this more restrictive check if we didn't have to worry about mixed-version clusters. Regardless, we can at least move all of this into the `if !leaseMismatch && isLeaseRequest {` block to indicate that the checks are related and that they're only applicable to lease requests.
</blockquote></details>

Added a comment.

---

*[pkg/storage/batcheval/result/result.go, line 274 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228#-L8ZaCblsYoWaBhXhTy1:-L8mn9fKEfkWSwED3L8Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/191896e9f82e75d30da83f170060fa2058b75984/pkg/storage/batcheval/result/result.go#L274)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Message needs fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24228)*

**Pull request merged**
