### PR TITLE
crosscluster/logical: use QoS on writes, scale proc count by CPU

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126859)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @msbutler)

___
*[`pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go` line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126859#-O1JDV7M5F0Ft7LQsc9T:-O1JDV7M5F0Ft7LQsc9U:baznb86) ([raw file](https://github.com/cockroachdb/cockroach/blob/344aa0ae82beb5d56a759a6994f132f0b0249f3d/pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go#L557)):*
> ```Go
> 	workers := len(lrw.bh)
> 	// Don't start lots of workers when out of CPU just to wait for one another.
> 	// Cut a fourth above 70%, a third above 80%, and half above 90%.
> ```

nit: with the current formula we get
- 3/4 above 70%
- 2/4 above 80%
- 1/4 above 90%

is this intentional? If so, we probably should update the comment.

Also, thoughts on having a cluster setting that would somehow control this pacing? For example, we could have a setting that would control the lower bound CPU threshold at which we start reducing workers, and then we'd use a linear formula so that we get 1/4 above 90% (e.g. when the threshold is set to 60%, with every additional 10% of CPU utilization, we'd reduce the workers count by 1/4).
___
*[`pkg/ccl/crosscluster/logical/lww_row_processor.go` line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126859#-O1JCWEzCQpcdZyP9SOn:-O1JCWEzCQpcdZyP9SOo:b-qrb6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c71c7fe04c0f01786ae476d8cc0de565664079d/pkg/ccl/crosscluster/logical/lww_row_processor.go#L242)):*
> ```Go
> 		// via sql.
> 		OriginIDForLogicalDataReplication: 1,
> 		QualityOfService:                  &sessiondatapb.UserLowQoS,
> ```

nit: do you think it's worth having a cluster setting that controls QoS level used here (with low being the default)?

**Comment by dt** [comment]
> we probably should update the comment.

What's wrong with the comment? you want it worded as a fraction of the original number, as opposed to a series of accumulated cuts?

> Cluster setting

I'd rather wait until we see evidence we need the setting, rather than add additional possible configurations we need to reason about / test before we know we need it. I think this is all a stop-gap until replication AC v2 is ready anyway.

**Review by yuzefovich — APPROVED** [review]
> What's wrong with the comment? you want it worded as a fraction of the original number, as opposed to a series of accumulated cuts?

The current wording had me confused. I'd either use a fraction of the original number, or use a wording like "Cut a fourth above 70%, another third above 80%, and another half above 90%."

**Comment by yuzefovich** [comment]
lol, you really dislike reviewable, and here I am always using it :D

**Comment by dt** [comment]
I might just write a bot to poll all of my PRs and nuke the "this change is reviewable" comment off them.

**Review by stevendanna — APPROVED** [review]
Have you observed this as effective on small nodes? It's a bit interesting to me because our default count worker count is 32 per-processor at the moment. So at max CPU this is taking us from 32*8=256 workers to 128 workers which still seems like a _lot_ of workers for some node sizes.

But I know this was a very effective strategy for OR so I'm not sure why it continues to surprise me.

**Comment by dt** [comment]
This had virtually no effect on the QPS hit on the workload when catching up after a 15min pause of the jobs. I don't really want to more aggressively tune down the workers since when we're not slammed the high concurrency for a single flush is useful. I played with a process-wide sem on flushes or flush workers, but I don't think one partition that hangs on an open txn should block other processors on different tables from flushing so I don't really want to do that.

Maybe we merge just the first commit here -- even though it doesn't seem to have much effect -- since at the very least the Low QoS is more correct, and then maybe replication AC v2 in 24.3 changes the equation here?

**Comment by dt** [comment]
I did more experiments today with variations on the CPU-based worker count scaling, including some that went down to a single worker when CPU was >= 90%. The more aggressive reduction in worker count _does_ have an effect: I see the workload's incoming byte traffic drop from around 9MB/s to 3-4MB/s instead of 1.8-2.5MB/s without it. But I also see the duration of the catch up scan increase substantially, incasing the duration of the reduced workload QPS, but almost double. I'm going to drop the dynamic worker-count commit from this PR, so it is only enabling the QoS, and leave it at that for now and revisit this after talking to AC, since it seems like a longer backfill duration that still impacts traffic for that duration isn't a clear win.

**Review by yuzefovich — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
