### PR TITLE
storage: add conflict handling for MVCC range tombstones

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch takes MVCC range tombstones into account for all MVCC write
operations, i.e. for conflict checks and conditional writes.

MVCC stats updates are not covered here, but will be addressed in a
subsequent PR. This also adds more exhaustive tests, especially for the
intent handling in `mvccPutInternal()`.

Touches #70412.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@jbowens I think we should focus our optimization efforts here first. This patch enables conflict checks with MVCC range tombstones on the write path. For `MVCCPut` on a database with no range keys or other existing data, this has a ~6% performance penalty:

```
name                               old time/op    new time/op    delta
MVCCPut_Pebble/valueSize=10-24       9.82µs ± 6%   10.42µs ± 5%  +6.05%  (p=0.001 n=10+10)
MVCCPut_Pebble/valueSize=100-24      11.0µs ± 6%    11.3µs ± 2%  +2.97%  (p=0.013 n=9+10)
MVCCPut_Pebble/valueSize=1000-24     12.7µs ± 2%    13.4µs ± 3%  +5.63%  (p=0.000 n=10+9)
MVCCPut_Pebble/valueSize=10000-24    42.7µs ±15%    40.5µs ±13%    ~     (p=0.143 n=10+10)
```

The conflict checks essentially enable `IterKeyTypePointsAndRanges` and then use `pointSynthesizingIter` to synthesize point tombstones. The latter is not optimized, so there are some gains to be had there, but the majority appears to be due to Pebble -- disabling point synthesis (so we're only changing `IterKeyType`) still shows a ~5% performance penalty:

```
name                            old time/op    new time/op    delta
MVCCPut_Pebble/valueSize=10-24    9.82µs ± 6%   10.28µs ± 6%  +4.69%  (p=0.009 n=10+10)
```

Ideally, we should be able to get this down to ~0 in the null case (no range keys). That would allow us to merge this to `master` and unblock dependant PRs.

**Comment by erikgrinaker** [comment]
I think most of the Pebble overhead here may be due to iterator construction. When I change the benchmark to use a batch, which reuses the Pebble iterator, then the time/op drops by an order of magnitude. In that case, the overhead is mostly due to `pointSynthesizingIter`.

```
name                            old time/op    new time/op   delta
MVCCPut_Pebble/valueSize=10-24     910ns ± 4%   1034ns ± 2%  +13.61%  (p=0.008 n=5+5)
```

When I drop the point synthesis and only enable range keys on the iterator, the performance diff is negligible:

```
name                            old time/op    new time/op    delta
MVCCPut_Pebble/valueSize=10-24     910ns ± 4%     933ns ± 5%   ~     (p=0.095 n=5+5)
```

I've pushed a patch with some WIP `pointSynthesizingIter` optimizations here, I'll see how low we can get it. It's possible that we're better off explicitly handling range keys in `mvccPutInternal`.

In any case, it would be worth having a look at cutting the iterator construction costs too, although this may not be as important since we often reuse iterators on batches.

**Comment by erikgrinaker** [comment]
I eliminated `pointSynthesisIter` on the hottest write paths, only using it when we need to access an old value. This got rid of most of the performance diff. We now only have a minor regression when updating existing keys, and only when using a batch (which reuses the iterator).

I think this is sufficient to merge to `master`, and we can keep pushing on performance separately.

```
name                                                       old time/op    new time/op    delta
MVCCPut_Pebble/batch=false,valueSize=10,versions=1-24        10.1µs ± 7%     9.9µs ± 5%    ~     (p=0.211 n=10+9)
MVCCPut_Pebble/batch=false,valueSize=10,versions=10-24        113µs ± 9%     111µs ± 3%    ~     (p=0.529 n=10+10)
MVCCPut_Pebble/batch=false,valueSize=100,versions=1-24       11.2µs ± 5%    11.0µs ± 5%    ~     (p=0.182 n=9+10)
MVCCPut_Pebble/batch=false,valueSize=100,versions=10-24       124µs ± 4%     124µs ± 3%    ~     (p=0.853 n=10+10)
MVCCPut_Pebble/batch=false,valueSize=1000,versions=1-24      12.7µs ± 5%    12.7µs ± 4%    ~     (p=0.955 n=10+10)
MVCCPut_Pebble/batch=false,valueSize=1000,versions=10-24      155µs ± 2%     150µs ± 3%  -3.22%  (p=0.000 n=9+10)
MVCCPut_Pebble/batch=false,valueSize=10000,versions=1-24     41.2µs ± 6%    41.7µs ± 8%    ~     (p=0.529 n=10+10)
MVCCPut_Pebble/batch=false,valueSize=10000,versions=10-24     449µs ± 6%     451µs ± 9%    ~     (p=0.684 n=10+10)
MVCCPut_Pebble/batch=true,valueSize=10,versions=1-24          952ns ± 7%     969ns ± 4%    ~     (p=0.696 n=10+8)
MVCCPut_Pebble/batch=true,valueSize=10,versions=10-24        15.2µs ± 1%    15.6µs ± 1%  +2.60%  (p=0.000 n=9+10)
MVCCPut_Pebble/batch=true,valueSize=100,versions=1-24        1.09µs ± 2%    1.08µs ± 1%    ~     (p=0.251 n=9+10)
MVCCPut_Pebble/batch=true,valueSize=100,versions=10-24       16.7µs ± 2%    17.1µs ± 3%  +2.81%  (p=0.000 n=10+10)
MVCCPut_Pebble/batch=true,valueSize=1000,versions=1-24       1.92µs ± 2%    1.90µs ± 2%    ~     (p=0.130 n=9+9)
MVCCPut_Pebble/batch=true,valueSize=1000,versions=10-24      29.2µs ± 2%    29.7µs ± 1%  +1.91%  (p=0.001 n=9+10)
MVCCPut_Pebble/batch=true,valueSize=10000,versions=1-24      10.7µs ±14%    10.2µs ±12%    ~     (p=0.190 n=10+10)
MVCCPut_Pebble/batch=true,valueSize=10000,versions=10-24      122µs ± 7%     123µs ± 7%    ~     (p=0.912 n=10+10)
```

**Comment by jbowens** [comment]
Sorry for the delay getting back to you—had a run around with covid this week. A bit of it might be fixed by cockroachdb/pebble#1723. I suspect the rest _is_ in iterator construction, and I'm pretty confident it'll be easy to fix. I'll work on it right now.

**Comment by erikgrinaker** [comment]
> Sorry for the delay getting back to you—had a run around with covid this week. A bit of it might be fixed by [cockroachdb/pebble#1723](https://github.com/cockroachdb/pebble/pull/1723). I suspect the rest _is_ in iterator construction, and I'm pretty confident it'll be easy to fix. I'll work on it right now.

Oh no, hope the covid wasn't too bad.

I think we're good for this PR. The read path is a bit worse, let's continue over on #82045.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81189#-:-N4bwJPvBwb0G-XTcS7d:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @nicktrav, and @sumeerbhola)

**Comment by erikgrinaker** [comment]
TFTR!

bors r=jbowens

**Pull request merged**
