### PR TITLE
exec: implement and plan decimal/float average columnar operator

### PR DESCRIPTION
**Pull request by asubiotto**
First three commits are #32138

When experimental_vectorize = true, if an average is performed on an
ordered decimal column, the columnar decimal average aggregator is now
planned.

```
root@:26257/tpch> SET experimental_vectorize=true;
SET

Time: 705µs

root@:26257/tpch> SELECT AVG(l_quantity) FROM lineitem;
avg
+-----------------------+
 25.507967136654827397
(1 row)

Time: 6.232818s

root@:26257/tpch> SET experimental_vectorize=false;
SET

Time: 673µs

root@:26257/tpch> SELECT AVG(l_quantity) FROM lineitem;
avg
+-----------------------+
 25.507967136654827397
(1 row)

Time: 7.661776s
```

This is not a crazy improvement but keep in mind that it seems that the scan performance dominates here (around 6s when run with EXPLAIN ANALYZE).

Microbenchmarks of the average operator are included in the relevant commit message.

Looking into adding logic tests for general columnar aggregations.

This PR is useful for the queries we care about but there are two nits I'd like to fix in the long term:
1) Can't use AggregatorSpec_FUNC because doing so would create an import cycle. We have been wanting to extract the specs into their separate packages but although I gave it a shot, it was taking longer than I wanted it to.
2) Template the average operator. Something I can potentially do in this PR but this is useful as it is. I just need to figure out what the preferred way of templating arbitrary type to decimal conversion is.

### CODE REVIEW

**Comment by asubiotto** [comment]
Added a commit that adds float support to the average operator. Wondering if I can template it better.

**Review by jordanlewis — COMMENTED** [review]
What's crude about it? I think this looks pretty good. I agree that there's an additional challenge to figure out how to template the cross-type aggregator builtins. I have some ideas about that, and generally how to improve the templating for aggregates. Ideally, we'd figure out a way to knock out lots of aggregate operators at once in a single template. 

I'm happy to brainstorm with you on this soon. I think we should find an equivalent to the aggregate builtin struct in our normal builtin type system. Look at `avgAggregate` for example in `aggregate_builtins` - it's a very elegant structure, with minimal code duplication. Can we figure out a way to channel that simplicity here?

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-:-LRPwBNn8o-BarEb9WW3:b-i6fowi)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator_test.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPsdIf8xkLNrN7f6nS:-LRPsdIf8xkLNrN7f6nT:bmqb4t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3cc6ab7bfbc1cfebb8f7884f9b1a9b1c8dbac8c/pkg/sql/exec/aggregator_test.go#L32)):*
> ```Go
> 	AVG = 1
> 	SUM = 10
> )
> ```

I don't think I need to tell you that this is super unfortunate. I looked at what distsql does, and it's pretty unfortunate too - it uses the AggregatorSpec_Func_value() function that proto gives you to map uppercase aggregate function name to integer...

Maybe it would be better to just use the string names like everybody else does? I'm not sure, but this whole thing feels a bit hacky - not just your code but all of the code that translates aggregation builtins.
___
*[pkg/sql/exec/avg_agg_tmpl.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPurlYE2Ql3GrArTrY:-LRPurlYE2Ql3GrArTrZ:bi64q0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aa90944f30823c9e0057f6fa08cf79a1271291e/pkg/sql/exec/avg_agg_tmpl.go#L45)):*
> ```Go
> // input to the result of the second input / the third input, where the third
> // input is an int64.
> func _ASSIGN_DIV_INT64(_, _, _ string) {
> ```

Nice! This is so cool.
___
*[pkg/sql/exec/avg_agg_tmpl.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPvigxB37O4-kHSQa3:-LRPvigxB37O4-kHSQa4:bv1qcjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aa90944f30823c9e0057f6fa08cf79a1271291e/pkg/sql/exec/avg_agg_tmpl.go#L56)):*
> ```Go
> 	case _TYPES_T:
> 		return &avg_TYPEAgg{}, nil
> 		// {{end}}
> ```

nit: can you put this on the same column as the {{range}} declaration?
___
*[pkg/sql/exec/avg_agg_tmpl.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPvwBV6rfaN9gXd0Us:-LRPvwBV6rfaN9gXd0Ut:b-g4axl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aa90944f30823c9e0057f6fa08cf79a1271291e/pkg/sql/exec/avg_agg_tmpl.go#L123)):*
> ```Go
> 			// TODO(asubiotto): Wonder how best to template this part (and below).
> 			// We'd like to do something similar to AssignFunc, where we have a
> 			// separate method call on DDecimal per type.
> ```

Can't you remove this TODO now?
___
*[pkg/sql/exec/avg_agg.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRNJZ2A7ZyRp4WzYdDS:-LRNJZ2B7lII7qloniDc:b51w8tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae631908723b42401bfd3d24f910f2dd8c2cb2f/pkg/sql/exec/avg_agg.go#L22)):*
> ```Go
> )
> 
> type avgDecimalAgg struct {
> ```

This seems nearly identical to the sum_TYPEAgg struct. The difference is that the `scratch` struct is different. Is there anything we do to reduce the duplication without making things too complex?
___
*[pkg/sql/exec/avg_agg.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPpfwR053GUfycqLWf:-LRPpfwR053GUfycqLWg:bomtqez) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae631908723b42401bfd3d24f910f2dd8c2cb2f/pkg/sql/exec/avg_agg.go#L61)):*
> ```Go
> 
> func (a *avgDecimalAgg) SetOutputIndex(idx int) {
> 	if a.scratch.curIdx != -1 {
> ```

This also seems similar to the other aggregate.
___
*[pkg/sql/exec/avg_agg.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPrNLIDnr91xQ7xsPu:-LRPrNLJ4G6nTawjP6j_:b-59nvu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae631908723b42401bfd3d24f910f2dd8c2cb2f/pkg/sql/exec/avg_agg.go#L81)):*
> ```Go
> 			// TODO(asubiotto): Wonder how best to template this part (and below).
> 			// We'd like to do something similar to AssignFunc, where we have a
> 			// separate method call on DDecimal per type.
> ```

I'm missing what prevents you from using an AssignFunc here, that's specialized on the `/` operator. You're talking about the Quo call, right?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32277)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator_test.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPsdIf8xkLNrN7f6nS:-LSQZQXeDdQpguXev3OM:b-7ccw7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3cc6ab7bfbc1cfebb8f7884f9b1a9b1c8dbac8c/pkg/sql/exec/aggregator_test.go#L32)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think I need to tell you that this is super unfortunate. I looked at what distsql does, and it's pretty unfortunate too - it uses the AggregatorSpec_Func_value() function that proto gives you to map uppercase aggregate function name to integer...

Maybe it would be better to just use the string names like everybody else does? I'm not sure, but this whole thing feels a bit hacky - not just your code but all of the code that translates aggregation builtins.
</blockquote></details>

Agreed. In an ideal world I think the `groupNode` would have a list of `AggregatorSpec_Func`s which is why I'm reluctant to make these strings (so won't unless you have a strong opinion given this), but I think that and this both rely on extracting the spec into a separate package.
___
*[pkg/sql/exec/avg_agg_tmpl.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPvigxB37O4-kHSQa3:-LSQ_9mA0pkqcFxNh1bG:bfwk89m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aa90944f30823c9e0057f6fa08cf79a1271291e/pkg/sql/exec/avg_agg_tmpl.go#L56)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: can you put this on the same column as the {{range}} declaration?
</blockquote></details>

Urgh, this keeps happening. Thanks for catching. Done.
___
*[pkg/sql/exec/avg_agg_tmpl.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPvwBV6rfaN9gXd0Us:-LSQdfdr8DSh2rwi9gKk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aa90944f30823c9e0057f6fa08cf79a1271291e/pkg/sql/exec/avg_agg_tmpl.go#L123)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can't you remove this TODO now?
</blockquote></details>

Done.
___
*[pkg/sql/exec/avg_agg.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRNJZ2A7ZyRp4WzYdDS:-LSQdOYM-OwWd6etnFHj:b-rsvjjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae631908723b42401bfd3d24f910f2dd8c2cb2f/pkg/sql/exec/avg_agg.go#L22)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems nearly identical to the sum_TYPEAgg struct. The difference is that the `scratch` struct is different. Is there anything we do to reduce the duplication without making things too complex?
</blockquote></details>

I don't know. From a first glance, all the methods use the scratch struct in their own, although similar way. This would probably benefit from a brainstorm but I'm not sure it's worth spending much time on this now.
___
*[pkg/sql/exec/avg_agg.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPrNLIDnr91xQ7xsPu:-LSQasY_3EnLSOkqMrsq:bhdccqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae631908723b42401bfd3d24f910f2dd8c2cb2f/pkg/sql/exec/avg_agg.go#L81)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm missing what prevents you from using an AssignFunc here, that's specialized on the `/` operator. You're talking about the Quo call, right?
</blockquote></details>

Yes, this has been done in a later commit for decimal and float, but I think the issue is that I also want to do a conversion to a decimal from the division of arbitrary types (e.g. int). Will remove this TODO.

**Review by jordanlewis — APPROVED** [review]
:lgtm: for now. I think if we were working on this actively I'd have more comments, but let's just merge and fix later.

We'll really want to find a way to dedup the aggregate code soon.

> Reviewed 1 of 3 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-:-LSSmJilCVZp029g_Bgl:b-ulajse)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator_test.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRPsdIf8xkLNrN7f6nS:-LSSfXIl8sSILvPXeDvX:bi8hz7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3cc6ab7bfbc1cfebb8f7884f9b1a9b1c8dbac8c/pkg/sql/exec/aggregator_test.go#L32)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Agreed. In an ideal world I think the `groupNode` would have a list of `AggregatorSpec_Func`s which is why I'm reluctant to make these strings (so won't unless you have a strong opinion given this), but I think that and this both rely on extracting the spec into a separate package.
</blockquote></details>

Sounds good. I think this will come up again soon. I think when it does, we should just bite the bullet and move the aggregator specs to a new package - it should be easy to do that.
___
*[pkg/sql/exec/avg_agg_tmpl.go, line 67 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LSSlxS3EKHdeTFson9Z:-LSSlxS3EKHdeTFson9_:b-jttu9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/148e0eeb9b7721a74fc75a30c0252a965c23d396/pkg/sql/exec/avg_agg_tmpl.go#L67)):*
> ```Go
> 	done bool
> 
> 	groups  []bool
> ```

Seems like we'll be able to at least abstract `done` and `groups` out into a parent struct at some point.

Hnnm, random thought now that I think about it, couldn't we plan `avg` as a scalar combination of a sum and a count? This might be faster by a little though.
___
*[pkg/sql/exec/avg_agg_tmpl.go, line 129 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LSSmDicC4GpagM1imRa:-LSSmDicC4GpagM1imRb:b-adieif) ([raw file](https://github.com/cockroachdb/cockroach/blob/148e0eeb9b7721a74fc75a30c0252a965c23d396/pkg/sql/exec/avg_agg_tmpl.go#L129)):*
> ```Go
> 	col, sel := b.ColVec(int(inputIdxs[0]))._TemplateType(), b.Selection()
> 	if sel != nil {
> 		sel = sel[:inputLen]
> ```

Having been away from this code for a little bit now, the `sel` duplication is starting to bug me. We should fix this soon. 
___
*[pkg/sql/exec/execgen/cmd/execgen/avg_agg_gen.go, line 40 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LSSlmqS7JqPDtv_S_WE:-LSSlmqS7JqPDtv_S_WF:b-l1tu1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/148e0eeb9b7721a74fc75a30c0252a965c23d396/pkg/sql/exec/execgen/cmd/execgen/avg_agg_gen.go#L40)):*
> ```Go
> }
> 
> func (a *avgAggTmplInfo) AssignDivInt64(target, l, r string) string {
> ```

You can avoid unused lint errors on these by just assigning _ to them nearby.
___
*[pkg/sql/exec/avg_agg.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32277#-LRNJZ2A7ZyRp4WzYdDS:-LSSYyTREVPe39DdsuGF:bm0sv5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae631908723b42401bfd3d24f910f2dd8c2cb2f/pkg/sql/exec/avg_agg.go#L22)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't know. From a first glance, all the methods use the scratch struct in their own, although similar way. This would probably benefit from a brainstorm but I'm not sure it's worth spending much time on this now.
</blockquote></details>

Yeah, that's fine.

**Pull request merged**
