### PR TITLE
opt: add transformation rule to convert anti join to left join

### PR DESCRIPTION
**Pull request by rytaft**
Release justification: bug fixes and low-risk updates to new functionality

`ConvertAntiToLeftJoin` converts an anti join to a left join with the same
`ON` condition, wraps the expression in a `Select` to remove rows that matched
the `ON` condition, and then projects out the left side columns.
For example (assuming `x` is a not-null column in `b`):
```
  SELECT * FROM a WHERE NOT EXISTS (
    SELECT * FROM b WHERE ST_Intersects(a.geom, b.geom)
  );
```
is converted to:
```
  SELECT a.* FROM a LEFT JOIN b ON ST_Intersects(a.geom, b.geom)
  WHERE b.x IS NULL;
```
Note that this transformation is not desirable in the general case, but it
is useful if there is a possibility of creating an inverted join (such as in
the above example). For this reason, we only perform this transformation if
it is possible to generate an inverted join.

This transformation allows us to index-accelerate spatial anti joins, which
was not possible before.

Informs #53576

Release note (performance improvement): spatial anti joins can now
be index-accelerated, which can lead to performance improvements in some
cases.

### CODE REVIEW

**Comment by rytaft** [comment]
You can ignore the first commit (it's from #53976)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-:-MGnu_Q_9qJ6pOH0mGN8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2883 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGnsYU44HmCTR2dB3t6:-MGnsGu0Exh_RDOxZYRT:b-4km90p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fcf2be943b588a79cc6f52d8e86f9a77fbe8552/pkg/sql/opt/xform/custom_funcs.go#L2883)):*
> ```Go
> 		return res
> 	}
> 	panic(errors.AssertionFailedf("TryAddKeyToScan failed. Input type: %T", expr))
> ```

[nit] add to the message to make it clear that the expected type is a Scan or a Select with a Scan input.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGnu-bo1gD0BiqxHac9:-MGnu-bo1gD0BiqxHacA:b-dwxxdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fcf2be943b588a79cc6f52d8e86f9a77fbe8552/pkg/sql/opt/xform/testdata/rules/join#L3701)):*
> ```
>            └── n.gid:13 IS NOT DISTINCT FROM CAST(NULL AS INT8) [outer=(13), constraints=(/13: [/NULL - /NULL]; tight), fd=()-->(13)]
> 
> opt expect=(ConvertAntiToLeftJoin,GenerateInvertedJoinsFromSelect)
> ```

[nit] If I understand correctly, this is a test for the case when the right side of the anti-join does not have a strict key, so one is added. And in the above case the key already exists. I think it's nice to leave a comment the explains this for each test so it's clear why the test was written.

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-:-MGorW3v5rNFtDLJBOm-:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2883 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGnsYU44HmCTR2dB3t6:-MGohzYiCPahuWQ8dS6h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fcf2be943b588a79cc6f52d8e86f9a77fbe8552/pkg/sql/opt/xform/custom_funcs.go#L2883)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add to the message to make it clear that the expected type is a Scan or a Select with a Scan input.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGnu-bo1gD0BiqxHac9:-MGojHwa6ynfq7FIfc4N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fcf2be943b588a79cc6f52d8e86f9a77fbe8552/pkg/sql/opt/xform/testdata/rules/join#L3701)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] If I understand correctly, this is a test for the case when the right side of the anti-join does not have a strict key, so one is added. And in the above case the key already exists. I think it's nice to leave a comment the explains this for each test so it's clear why the test was written.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54081)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

**Comment by rytaft** [comment]
@raduberinde do you want to take a look at this or should I go ahead and merge? Want to make sure it's ready for the Monday discussion on possible backports to 20.2.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-:-MGuZeNR3EokPpwyMnBH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2874 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGuZ5eH233RD4PTK890:-MGuZ5eH233RD4PTK891:bapykad) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf55df2b4d506fc056c29ba0437deb189d5e554/pkg/sql/opt/xform/custom_funcs.go#L2874)):*
> ```Go
> // TryAddKeyToScan, which will try to augment the expression with the primary
> // key of the underlying table scan (guaranteed to be not-null). In order for
> // this call to succeed, the input expression must be either a Scan or a Scan
> ```

[nit] must be a non-virtual Scan, optionally wrapped in a Select.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 2876 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGuZS6uE4XW7b6dQ7m2:-MGuZS6uE4XW7b6dQ7m3:b-l1g8xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf55df2b4d506fc056c29ba0437deb189d5e554/pkg/sql/opt/xform/custom_funcs.go#L2876)):*
> ```Go
> // this call to succeed, the input expression must be either a Scan or a Scan
> // wrapped in a Select. Otherwise, EnsureNotNullCol will panic.
> func (c *CustomFuncs) EnsureNotNullCol(expr memo.RelExpr) memo.RelExpr {
> ```

This is similar to `EnsureCanary`.. Feels like projecting a constant value would be cheaper than decoding extra columns no?

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-:-MGxW2VZBGBBbIAvTFME:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2874 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGuZ5eH233RD4PTK890:-MGxVxtU-EZ-E-DPXl_n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf55df2b4d506fc056c29ba0437deb189d5e554/pkg/sql/opt/xform/custom_funcs.go#L2874)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] must be a non-virtual Scan, optionally wrapped in a Select.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 2876 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGuZS6uE4XW7b6dQ7m2:-MGxVgqh84qMGngMpc5S:b-jog8wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf55df2b4d506fc056c29ba0437deb189d5e554/pkg/sql/opt/xform/custom_funcs.go#L2876)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is similar to `EnsureCanary`.. Feels like projecting a constant value would be cheaper than decoding extra columns no?
</blockquote></details>

That's what I thought originally, but then the project expression fails to match on GenerateInvertedJoins or GenerateInvertedJoinsFromSelect. Added a comment.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-:-MGxmwJGCdcu270w1L5w:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2876 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGuZS6uE4XW7b6dQ7m2:-MGxmcpDEaXu1ovxD_58:b4vlai6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf55df2b4d506fc056c29ba0437deb189d5e554/pkg/sql/opt/xform/custom_funcs.go#L2876)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

That's what I thought originally, but then the project expression fails to match on GenerateInvertedJoins or GenerateInvertedJoinsFromSelect. Added a comment.
</blockquote></details>

My only worry is that the name is very general that it will be tempting to use.. Maybe rename to `EnsureNotNullColFromFilteredScan` or something

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-:-MGylJdw1Yt7W02kMKCt:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2876 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54081#-MGuZS6uE4XW7b6dQ7m2:-MGykbKo14DSZlmVBTQN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf55df2b4d506fc056c29ba0437deb189d5e554/pkg/sql/opt/xform/custom_funcs.go#L2876)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

My only worry is that the name is very general that it will be tempting to use.. Maybe rename to `EnsureNotNullColFromFilteredScan` or something
</blockquote></details>

Done.

**Pull request merged**
