### PR TITLE
sql: hint scan batch size by expected row count

### LINKED ISSUE #62198: YCSB/E performance regression on December 4th
the `ycsb/E` benchmarks had a sharp drop of 52% (1580→755) between December 3rd and 5th:

https://roachperf.crdb.dev/?filter=&view=ycsb%2FE%2Fnodes%3D3&tab=gce

### PR DESCRIPTION
**Pull request by jordanlewis**
Might close #62198.

Previously, the "dynamic batch size" strategy for the vectorized
engine's batch allocator worked the same in every situation: batches
would start at size 1, then double on each re-allocation, until they hit
their maximum size of 1024.

Now, to improve performance for scans that return a number of rows
somewhere in between 1 and 1024, we pass in the optimizer's best guess
of the number of rows that the scan will produce all the way down into
the TableReader. That guess is used as the initial size of the batch if
it's less than 1024.

Release note (performance improvement): improve the performance for the
vectorized engine when scanning fewer than 1024 rows at a time.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Very nice find! I just have a few nits as usual :)

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-:-MWBl0IxEaydKMsQ7iF9:bwath0t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWBjteWBykl1Gw08QAl:-MWBjteWBykl1Gw08QAm:bdhgjge) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66b66659217630d36186ba978d82689aa9bf476/pkg/sql/colexec/colbuilder/execplan.go#L741)):*
> ```Go
> 			}
> 			scanOp, err := colfetcher.NewColBatchScan(
> 				ctx, streamingAllocator, flowCtx, evalCtx, core.TableReader, post, estimatedRowCount)
> ```

super nit: it's nicer to put closing parenthesis on the newline.
___
*[pkg/sql/colfetcher/cfetcher.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWBk2yeBFo67Fkff07Z:-MWBk2yeBFo67Fkff07_:bbftjy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66b66659217630d36186ba978d82689aa9bf476/pkg/sql/colfetcher/cfetcher.go#L322)):*
> ```Go
> 	}
> 	rf.machine.batch, reallocated = rf.allocator.ResetMaybeReallocate(
> 		rf.typs, rf.machine.batch, estimatedRowCount, rf.memoryLimit,
> ```

nit: can just use `rf.estimatedRowCount` directly since `ResetMaybeReallocate` will truncate itself.
___
*[pkg/sql/execinfrapb/processors.proto, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWBkubVD878Cd0UczMa:-MWBkubVD878Cd0UczMb:b-n7w6yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66b66659217630d36186ba978d82689aa9bf476/pkg/sql/execinfrapb/processors.proto#L84)):*
> ```protobuf
>   repeated sql.sem.types.T result_types = 7;
> 
>   optional uint64 estimated_row_count = 8 [(gogoproto.nullable) = false];
> ```

nit: I think this deserves at least a quick comment.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 684 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWCAD1sETd5FNPvgoPe:-MWCAD1sETd5FNPvgoPf:bd8xxo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2ce8d632c146d1b24267196880fe75da87227d/pkg/sql/colexec/colbuilder/execplan.go#L684)):*
> ```Go
> 	post := &spec.Post
> 
> 	estimatedRowCount := spec.EstimatedRowCount
> ```

nit: it would probably be nice to either move into the TableReader case or leave a comment here that currently this information is set only for the table readers.
___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans_nonmetamorphic, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWCAi6n2qoHwUORmo1W:-MWCAi6n2qoHwUORmo1X:b63aiq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2ce8d632c146d1b24267196880fe75da87227d/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans_nonmetamorphic#L1)):*
> ```
> # LogicTest: !metamorphic local
> ```

We probably don't need this file, right?
___
*[pkg/sql/tests/vectorized_batch_size_test.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWCB-aq2uu411tTondh:-MWCB-aq2uu411tTondi:b-wy4fqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2ce8d632c146d1b24267196880fe75da87227d/pkg/sql/tests/vectorized_batch_size_test.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package tests
> ```

I'd move it to `colfetcher` package.
___
*[pkg/sql/tests/vectorized_batch_size_test.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWCB7Eg9_2q8qJAvNiG:-MWCB7Eg9_2q8qJAvNiH:b2d0al9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2ce8d632c146d1b24267196880fe75da87227d/pkg/sql/tests/vectorized_batch_size_test.go#L28)):*
> ```Go
> )
> 
> func TestScanBatchSize(t *testing.T) {
> ```

nit: quick comment for the goal of the test would be beneficial.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans_nonmetamorphic, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWCAi6n2qoHwUORmo1W:-MWCDfI8EOhJk_1wBEZG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2ce8d632c146d1b24267196880fe75da87227d/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans_nonmetamorphic#L1)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We probably don't need this file, right?
</blockquote></details>

Done.
___
*[pkg/sql/tests/vectorized_batch_size_test.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-MWCB-aq2uu411tTondh:-MWCDePd-xes-cUOEOeM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2ce8d632c146d1b24267196880fe75da87227d/pkg/sql/tests/vectorized_batch_size_test.go#L11)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'd move it to `colfetcher` package.
</blockquote></details>

Done.

**Comment by erikgrinaker** [comment]
I did some `ycsb/E/nodes=3` GCE runs to try this: 5 runs at 24e76d3990 (without this PR) and 5 runs at 3d7eecc068 (with this PR). Happy to say that the median results were 792 ops/s before, and 1829 ops/s after, which is even higher than the original ~1600ops/s baseline back in November! Great work @jordanlewis!

However, I also did some `kv95/enc=false/nodes=1/cpu=32` GCE runs to see if this might address #62156. Unfortunately, this seems to have regressed from 60589 ops/s without this PR to 56142 ops/s with this PR. The results were fairly noisy, so I did 10 runs each, and it should probably be taken with a grain of salt. I don't think it should block this PR, but if you have any ideas for why this might have caused `kv95` to regress then that'd be worth looking into.

**Comment by jordanlewis** [comment]
Interesting. @erikgrinaker, thank you for working on these benchmark results.

I'm currently baffled why this PR would have made kv95 worse. I would expect that it would have been a no-op. I will look into this as well.

**Comment by jordanlewis** [comment]
I did a couple of brief tests and couldn't reproduce the behavior you saw, but I'm not ruling out the possibility I've missed something just yet.

Also, I wouldn't suspect that this fix could help with the slow regression you're looking at. The behavior for single-key primary key lookup workloads (like the ones in KV) should be exactly the same before and after this patch. 🤔

**Comment by erikgrinaker** [comment]
Yeah, it's weird. I'm fine with putting it down to noise, but I just did another run now and got similar results. The thing that jumps out at me is that it's always slower to ramp up with this change -- have a look at the instantaneous rates below:

Without this PR:

```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
    1.0s        0        29460.3        33190.0      1.1      5.2      8.9     27.3 read
    1.0s        0         1538.0         1732.7      3.8     10.0     13.6     26.2 write
    2.0s        0        33780.4        33484.5      1.0      5.0      8.9     24.1 read
    2.0s        0         1736.3         1734.5      4.5     11.0     15.7     25.2 write
    3.0s        0        32794.3        33254.4      1.0      5.5     10.0     21.0 read
    3.0s        0         1746.0         1738.3      4.5     12.1     17.8     28.3 write
    4.0s        0        35227.5        33747.8      1.0      4.7      9.4     22.0 read
    4.0s        0         1867.9         1770.7      3.8      9.4     14.7     29.4 write
    5.0s        0        34809.9        33960.6      1.0      5.2     10.5     19.9 read
    5.0s        0         1874.7         1791.5      3.8     11.0     14.7     26.2 write
```

With this PR:

```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
    1.0s        0        40747.2        45317.0      0.9      3.5      7.3     15.2 read
    1.0s        0         2148.8         2389.8      3.3      8.9     12.6     17.8 write
    2.0s        0        47194.0        46255.5      0.9      3.1      7.3     16.3 read
    2.0s        0         2516.2         2453.0      3.1      9.4     13.1     18.9 write
    3.0s        0        49113.7        47206.9      0.8      2.9      7.1     18.9 read
    3.0s        0         2600.1         2502.0      3.1      8.9     12.1     19.9 write
    4.0s        0        49923.5        47886.7      0.8      2.9      6.8     16.8 read
    4.0s        0         2656.9         2540.7      3.4      9.4     12.1     21.0 write
    5.0s        0        51812.2        48671.6      0.8      2.4      6.6     17.8 read
    5.0s        0         2646.0         2561.8      2.9     10.0     15.2     21.0 write
```

This pattern holds across all the runs I've done. But I don't have a good explanation for why this change should cause this.

**Comment by jordanlewis** [comment]
@erikgrinaker does the pattern reoccur in your test setup with `read-percent=100`?

**Comment by jordanlewis** [comment]
Could you share the exact invocations you used to do your tests?

**Comment by erikgrinaker** [comment]
Sure:

```
roachtest -u grinaker --cockroach cockroachshort-linux-jordanlewis-post run --count 5 --cpu-quota 320 '^kv95/enc=false/nodes=1/cpu=32$'
```

I'll do a run with a patched `roachtest` using `read-percent=100` soon, running some other benchmarks atm.

**Comment by erikgrinaker** [comment]
Seeing the same with `read-percent=100`, median is 66267 ops/s vs. 61842 ops/s. Slow ramp-up:

Without PR:

```
    1.0s        0        45943.9        52634.9      0.9      3.5      7.6     16.8 read
    2.0s        0        53887.3        53256.5      0.9      3.4      6.8     15.7 read
    3.0s        0        54726.6        53746.9      0.9      3.4      6.8     16.8 read
    4.0s        0        55622.4        54215.3      0.9      3.3      7.1     15.7 read
    5.0s        0        56558.9        54684.7      0.9      3.1      7.1     17.8 read
    6.0s        0        58279.0        55282.8      0.9      2.9      6.6     15.2 read
    7.0s        0        57671.5        55624.7      0.9      3.0      6.6     14.7 read
    8.0s        0        58504.5        55984.0      0.9      2.9      6.6     15.7 read
    9.0s        0        57625.4        56166.6      0.9      3.0      7.1     15.2 read
   10.0s        0        58540.9        56404.1      0.9      2.9      6.8     18.9 read
```

With PR:

```
    1.0s        0        31237.3        35882.4      1.2      5.0      9.4     22.0 read
    2.0s        0        37625.5        36753.0      1.2      4.7      8.4     23.1 read
    3.0s        0        37586.4        37031.0      1.1      5.0      9.4     23.1 read
    4.0s        0        38858.7        37488.1      1.2      4.5      7.9     18.9 read
    5.0s        0        38599.1        37710.2      1.1      4.5      8.9     18.9 read
    6.0s        0        38557.1        37851.5      1.1      4.7      8.4     19.9 read
    7.0s        0        38632.2        37963.4      1.2      4.5      8.9     18.9 read
    8.0s        0        40179.1        38239.8      1.1      4.5      8.9     18.9 read
    9.0s        0        39869.8        38421.0      1.0      4.7      8.9     23.1 read
   10.0s        0        40219.6        38600.9      1.1      4.5      8.9     16.3 read
```

**Comment by erikgrinaker** [comment]
Ok -- I think this is a pretty clear win for YCSB/E, and if it turns out not to be noise we can optimize that separately. Thanks!

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62282#-:-MWPsH1S3zo2PAo3082Y:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
There is a merge skew with #62255 that is in the current batch (looks like you might have noticed it too).

**Comment by yuzefovich** [comment]
I hope you don't mind - I've just rebased and updated `explain_analyze` logic test.

bors r+

**Comment by jordanlewis** [comment]
On the contrary, I very much appreciate it - thanks so much!

**Comment by yuzefovich** [comment]
"vectorized batch count" doesn't show up for some of the logic test configs :/

bors r-

**Comment by yuzefovich** [comment]
I'll pick this up and will move over the finish line. I'll update `explain_analyze` logic test to run only with `vec-on` configs so that it is not flaky anymore.

**Pull request merged**
