### PR TITLE
insights: separate problems and causes

### PR DESCRIPTION
**Pull request by matthewtodd**
This change effectively removes the "unknown" problem that was both
confusing and noisy. We now have 2 separate fields, the high-level
"slow" or "failed" problem, and the possible causes for the slowness.

(We also work through a couple of auxiliary commits encountered
along the way. See their commit messages for more.)

Release justification: bug fixes and low-risk updates to new
functionality

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
Nice changes! :lgtm:  (just nit on release note)

> Reviewed 19 of 21 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87205#-:-NAph30FCFjk8QE8PmXg:b-i8cmg0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87205#-NAph98T8C6sziNH6UZZ):*
you're changing the table format and new values, so it should have a release note, specially so the docs team can see this. Can you also update our doc that Stephanie is using with this changes?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87205)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stbof)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87205#-NAph98T8C6sziNH6UZZ):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you're changing the table format and new values, so it should have a release note, specially so the docs team can see this. Can you also update our doc that Stephanie is using with this changes?
</blockquote></details>

:thumbsup: I'll update the doc for @stbof.

As for the release notes, I think this falls under the [new guidance](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#High-level-rules) to "exclude changes to reserved interfaces," yes? The [API support policy](https://www.cockroachlabs.com/docs/v22.1/api-support-policy) marks all of `crdb_internal` as reserved.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87205)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stbof)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87205#-NAph98T8C6sziNH6UZZ):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

:thumbsup: I'll update the doc for @stbof.

As for the release notes, I think this falls under the [new guidance](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#High-level-rules) to "exclude changes to reserved interfaces," yes? The [API support policy](https://www.cockroachlabs.com/docs/v22.1/api-support-policy) marks all of `crdb_internal` as reserved.
</blockquote></details>

Edit: it marks `crdb_internal` as reserved by default, with specific tables called out as stable for production use. I think we don't want folks to treat `{cluster,node}_execution_insights` as stable for production use yet.

**Pull request merged**
