### PR TITLE
ui: Disk Usage stats for time series data

### LINKED ISSUE #20210: ui/ts: Expose information about timeseries disk/range usage
We currently don't appear to expose the amount of disk used by timeseries data or the number of ranges containing timeseries data, unlike for all SQL tables which have this info shown on the `/#/databases/tables` page. This makes understanding a cluster's disk usage more confusing and less definitive. We can point people to https://www.cockroachlabs.com/docs/stable/operational-faqs.html#why-is-disk-usage-increasing-despite-lack-of-writes and say that timeseries is *probably* why the number of bytes and ranges in their cluster is increasing at an unexpectedly high rate, but can't be totally sure that there isn't also something else contributing.

### PR DESCRIPTION
**Pull request by mrtracy**
Adds disk usage stats for time series data. This data is visible at the
bottom of the Databases tab in its own special section; there does not
appear to be a more obvious place to put it at this time, and it doesn't
appear to be invasive.

Resolves #20210
Work towards #20738 (this does not account for *all* non-table usage).

Release note: Disk usage for time series data is now visible on the
Admin UI Databases page.

screen shot 2018-02-05 at 7 02 47 pm

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

The `Time Series Data` table is formatted differently from the other tables on the `Databases` page. Admittedly, the `# of Columns` and `# of Indices` columns don't make sense, but we could still add them there. I cringe at bring up a UI issue. This can certainly be addressed in a follow-on PR.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/serverpb/admin.proto, line 216 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22398#-L4cs-Se-T01Sz1RALJb:-L4cs-Se-T01Sz1RALJc:bdm5w26) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db68c97e046c0fc60c3b402b9950c053d30e13b/pkg/server/serverpb/admin.proto#L216)):*
> ```protobuf
> // addressed as a database/table pair.
> message TimeSeriesStatsRequest {
> }
> ```

Are you imagining there will be a new request for each type of non-table data? Perhaps there should be a single `NonTableStatsRequest` and the response should contain fields for each type of non-table data we wish to report about. For example, I can see having `meta1`, `meta2` and `timeseries` fields. These seem relatively straightforward to gather in a single requestm but perhaps you had something different in mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22398#-:-L4csHgBBUhrTrEHLvX4:b-kl83cl)*

**Review by vilterp — APPROVED** [review]

**Comment by vilterp** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/serverpb/admin.proto, line 216 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22398#-L4cs-Se-T01Sz1RALJb:-L4cxKo0aryoQrrIVXUW:b-zb6wpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db68c97e046c0fc60c3b402b9950c053d30e13b/pkg/server/serverpb/admin.proto#L216)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are you imagining there will be a new request for each type of non-table data? Perhaps there should be a single `NonTableStatsRequest` and the response should contain fields for each type of non-table data we wish to report about. For example, I can see having `meta1`, `meta2` and `timeseries` fields. These seem relatively straightforward to gather in a single requestm but perhaps you had something different in mind.
</blockquote></details>

:+1: on the single `NonTableStats` message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22398)*

**Comment by couchand** [comment]
:lgtm:

It would be nice if the columns lined up with the tables above, but it's not clear what would go in them...

It's probably a bigger change, so not in this PR, but would it be worth exposing the usage on `/_status/vars`, too?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22398#-:-L4fgsL3198ww2JVAPDT:b8zyf85)*

**Comment by bdarnell** [comment]
> It would be nice if the columns lined up with the tables above, but it's not clear what would go in them...

We could at least add a "name" column containing "time series" and then we'd have the first three columns lining up (if resized to match)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22398#-:-L4gFPSAnEistbsNtBl0:b-2a5xur)*

**Comment by mrtracy** [comment]
I've changed the method on the backend to `nonTableStats`, and as Peter suggested it is now formatted to return data from multiple non-table ranges.  Currently, it still only returns data for the time series system, but it should be very straightforward to augment it with additional ranges.

I have updated the table slightly in the Databases page; however, I don't think there's a good solution to align the columns exactly with the preceding tables, aside from adding empty columns with the titles "# of Indices" and "# of Columns"; the titles would be necessary, as these tables are auto-sized to fit the needs of each column.

screen shot 2018-02-06 at 3 44 21 pm

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22398#-:-L4gwpSTBWozMoQ2aGyX:bnfp4nl)*

**Pull request merged**
