### PR TITLE
util: add tsearch package

### PR DESCRIPTION
**Pull request by jordanlewis**
Updates #41288.

Broken off from #83736

This PR adds a tsearch package which contains text search algorithms
for the tsvector/tsquery full text search capability.

See https://www.postgresql.org/docs/current/datatype-textsearch.html for details.

The package can:

1. parse the tsvector language, which consists of a list of terms surrounded by single quotes, optionally suffixed with a list of positions corresponding to the term's original ordinal position within a document. Each position may optionally come with a "weight", which is a letter A-D (defaulting to D, the lowest weight) that can be used to customize how important a word is in a document.
2. parse the tsquery language, which consists of a simple expression language with terms separating by operators `!`, `&`, `|`, and `<n>` where `n` is a number or `-` which is equivalent to 1. Expressions can be further grouped with parentheses. The first 3 operators are ordinary boolean operators over whether a term exists in a document. The `<n>` operator returns true if the left argument is `n` tokens to the left of the argument on the right in the document expressed by the vector.
3. evaluate a tsquery against a tsvector, which returns a boolean indicating whether the vector satisfied the query.

So far, this package is standalone and not hooked up to SQL at all.

Release note: None
Epic: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Lol, @jordanlewis how come you're a community member? Did they take away your engineering permissions? :D

**Review by rytaft — APPROVED** [review]
:lgtm: Impressive work!

> Reviewed 3 of 5 files at r1, 6 of 6 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-:-NFG5c8C9Nf2ZjkW3PGR:b-73yvk8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @rafiss)

___
*[`pkg/util/tsearch/eval.go` line 89 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG5rW-4Vo676LLm0aR:-NFG5rW-4Vo676LLm0aS:bt8ub7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval.go#L89)):*
> ```Go
> 	positions []tsposition
> 	width     int
> 	invert    bool
> ```

These could use comments
___
*[`pkg/util/tsearch/eval.go` line 97 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG5thG80IwUu22OAnK:-NFG5thG80IwUu22OAnL:bt8ub7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval.go#L97)):*
> ```Go
> 	emitMatches emitMode = 1 << iota
> 	emitLeftUnmatched
> 	emitRightUnmatched
> ```

These could use comments
___
*[`pkg/util/tsearch/lex.go` line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFEhhjm-_80qawOFkp7:-NFEhhjm-_80qawOFkp8:bisgfgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/54aa0781d30473488f07cee70632111b18246bbb/pkg/util/tsearch/lex.go#L80)):*
> ```Go
> // If a word is not single-quote wrapped, the next term will begin if there is
> // whitespace after the word. Whitespace and colons may be entered by escaping
> // them with backslashes. All other uses of backslashes are no-ops.
> ```

When you say "no-op", do you mean the backslash is ignored, or just treated like a normal character? If ignored, can a backslash escape another backslash to treat it as a normal character?
___
*[`pkg/util/tsearch/lex.go` line 288 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFEjMWw-iCz1ep0GGlH:-NFEjMWw-iCz1ep0GGlI:bog9x8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/54aa0781d30473488f07cee70632111b18246bbb/pkg/util/tsearch/lex.go#L288)):*
> ```Go
> 				} else {
> 					p.state = expectingPosDelimiter
> 				}
> ```

nit: add a comment to explain why this doesn't use the same format as the ones above
___
*[`pkg/util/tsearch/tsquery.go` line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFHjhu63MPyW6hsOnE:-NFFHjhv5umI3mJ49q7U:b-i57a02) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cd57fa42ed2ce4646a875ce6e5c63ffd4a4dba/pkg/util/tsearch/tsquery.go#L23)):*
> ```Go
> // tsNode represents a single AST node within the tree of a TSQuery.
> type tsNode struct {
> 	// Only one of term, op, or paren will be set.
> ```

paren doesn't exist
___
*[`pkg/util/tsearch/tsvector.go` line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG30Lx-dB7R9c7l6uw:-NFG30Lx-dB7R9c7l6ux:b-37zrfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/tsvector.go#L46)):*
> ```Go
> 	}
> 	if w&weightD != 0 {
> 		ret.WriteByte('D')
> ```

Should this be printed if it's the default?
___
*[`pkg/util/tsearch/tsvector.go` line 83 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG3SDd9myQl9vu2sml:-NFG3SDd9myQl9vu2smm:b-ntqm6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/tsvector.go#L83)):*
> ```Go
> 		return 1
> 	}
> 	panic(fmt.Sprintf("no precdence for operator %d", o))
> ```

AssertionFailedf?
___
*[`pkg/util/tsearch/tsvector.go` line 197 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG4-sc9EUoDTNWqL7n:-NFG4-sc9EUoDTNWqL7o:b-m8gm0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/tsvector.go#L197)):*
> ```Go
> 		// Make sure to sort and uniq the position list even if there's only 1
> 		// entry.
> 		latsIdx := len(ret) - 1
> ```

nit: latsIdx -> lastIdx
___
*[`pkg/util/tsearch/eval_test.go` line 80 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG0VSIATEN8_wvhPqq:-NFG0VSIATEN8_wvhPqr:bejokwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval_test.go#L80)):*
> ```Go
> 		{`!a <-> !b`, `a:3`, true},
> 
> 		//{`!a <-> !b`, ``, true},
> ```

leftover?
___
*[`pkg/util/tsearch/eval_test.go` line 124 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFxJ792MlyWGdQPcT6:-NFFxJ792MlyWGdQPcT7:b127jr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval_test.go#L124)):*
> ```Go
> 	t.Run("ComparePG", func(t *testing.T) {
> 		skip.IgnoreLint(t, "need to manually enable")
> 		conn, err := pgx.Connect(context.Background(), "postgresql://jordan@localhost:5432")
> ```

Same question I had before -- how would someone else run this?
___
*[`pkg/util/tsearch/tsquery_test.go` line 199 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFg35hE4ZnoiR5Y-RV:-NFFg35i2LrCA65daFQG:b-yhfly3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cd57fa42ed2ce4646a875ce6e5c63ffd4a4dba/pkg/util/tsearch/tsquery_test.go#L199)):*
> ```Go
> 	t.Run("ComparePG", func(t *testing.T) {
> 		skip.IgnoreLint(t, "need to manually enable")
> 		conn, err := pgx.Connect(context.Background(), "postgresql://jordan@localhost:5432")
> ```

How will other people run this? Can you give some instructions on how to run this test?
___
*[`pkg/util/tsearch/tsvector_test.go` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFGp_-3CsHKDm0vc4y:-NFFGp_-3CsHKDm0vc4z:by7noqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/54aa0781d30473488f07cee70632111b18246bbb/pkg/util/tsearch/tsvector_test.go#L39)):*
> ```Go
> 		{`foo:3A`, `'foo':3A`},
> 		{`foo:3D`, `'foo':3`},
> 		{`foo:3D`, `'foo':3`},
> ```

duplicate test case

**Review by jordanlewis — COMMENTED** [review]
Thanks much for the review! Reading the code again I can see that there was not much provided context, so I've gone through and added a lot of explanatory comments that hopefully make it a bit easier to read this code. I've also renamed a few structs to be more canonical (like tsOperator instead of tsoperator).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-:-NFMEu-E3rR9hSsa_gr4:b-v73k7a)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rafiss, and @rytaft)

___
*[`pkg/util/tsearch/eval.go` line 89 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG5rW-4Vo676LLm0aR:-NFLYBQGBdV5x5_W9Mlm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval.go#L89)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These could use comments
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/eval.go` line 97 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG5thG80IwUu22OAnK:-NFM4FQZ6rDLshkb-YAz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval.go#L97)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These could use comments
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/lex.go` line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFEhhjm-_80qawOFkp7:-NFM1jK-DoTB_KcKSVuQ:bcnisth) ([raw file](https://github.com/cockroachdb/cockroach/blob/54aa0781d30473488f07cee70632111b18246bbb/pkg/util/tsearch/lex.go#L80)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

When you say "no-op", do you mean the backslash is ignored, or just treated like a normal character? If ignored, can a backslash escape another backslash to treat it as a normal character?
</blockquote></details>

Confusingly they're just ignored. A doubled backslash is treated as a backslash literal. Clarified the comment (and added the missing test cases for \\ in tsvector and tsquery).

Extra confusingly, Postgres outputs single backslash literals as double backslashes (WTF), this behavior can be confirmed by converted the string to bytes and noticing that there's just a single backslash byte... so I changed the test that runs against Postgres to deal with this. Truly confusing and awful!
___
*[`pkg/util/tsearch/tsquery.go` line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFHjhu63MPyW6hsOnE:-NFLYq9DDmUlgiryCENL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cd57fa42ed2ce4646a875ce6e5c63ffd4a4dba/pkg/util/tsearch/tsquery.go#L23)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

paren doesn't exist
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsvector.go` line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG30Lx-dB7R9c7l6uw:-NFL_FeT1xtwZ0ek1vP5:b-s7df0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/tsvector.go#L46)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should this be printed if it's the default?
</blockquote></details>

It should - the reason we need to do this is that tsWeight is reused for both TSQuery and TSVector. In TSQuery, the default is not present, so D needs to be printed. In TSVector, the default is D, and it doesn't need to be printed - but we just store absence for the weight if D is seen in TSVector.

It's a little confusing but I think easier to keep it like this than introduce 2 separate tsWeight enums. I've added clarifying comments.
___
*[`pkg/util/tsearch/tsvector.go` line 83 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG3SDd9myQl9vu2sml:-NFM0zJA1AeCmwDw2Pol:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/tsvector.go#L83)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

AssertionFailedf?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/eval_test.go` line 80 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFG0VSIATEN8_wvhPqq:-NFM19qV6Qptn-2k6C80:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval_test.go#L80)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

leftover?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsquery_test.go` line 199 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFg35hE4ZnoiR5Y-RV:-NFMFIb06D2XpAn3VQLn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1cd57fa42ed2ce4646a875ce6e5c63ffd4a4dba/pkg/util/tsearch/tsquery_test.go#L199)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

How will other people run this? Can you give some instructions on how to run this test?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsvector_test.go` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFGp_-3CsHKDm0vc4y:-NFM1Gu9Br4G1LzJQhRJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54aa0781d30473488f07cee70632111b18246bbb/pkg/util/tsearch/tsvector_test.go#L39)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

duplicate test case
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85185)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rafiss, and @rytaft)

___
*[`pkg/util/tsearch/eval_test.go` line 124 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFFxJ792MlyWGdQPcT6:-NFMIAS99Smx92aRnTzH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a19197b58e3a07634931d69d15f6508b71f43771/pkg/util/tsearch/eval_test.go#L124)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Same question I had before -- how would someone else run this?
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
Thanks!

> Reviewed 6 of 6 files at r7, 8 of 8 files at r10, 3 of 3 files at r11, 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-:-NFOlWFrBlMmY_dgwEIl:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @rafiss)

___
*[`pkg/util/tsearch/eval.go` line 106 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOjll86ku51rbIFBbH:-NFOjll86ku51rbIFBbI:b-7wiw7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/eval.go#L106)):*
> ```Go
> 	width int
> 	// invert, if true, indicates that this match should be inverted. It's used
> 	// to handle followed by matches within not operators.
> ```

Do you have tests that cover this case? (more generally, have you checked for code coverage?)
___
*[`pkg/util/tsearch/lex.go` line 85 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOgYCE5ylP47d-SDHT:-NFOgYCE5ylP47d-SDHU:bhi69n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/lex.go#L85)):*
> ```Go
> // whitespace after the word. Whitespace and colons may be entered by escaping
> // them with backslashes. All other uses of backslashes are skipped, allowing
> // the following character to be included as a literal.
> ```

might help to explicitly mention that / itself could be the following character
___
*[`pkg/util/tsearch/lex.go` line 99 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOgUAy7XLkB7Yqi0Mx:-NFOgUAy7XLkB7Yqi0My:bccf3kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/lex.go#L99)):*
> ```Go
> //     operator. For example, foo:3AC*
> //
> // See examples in tsvector_test.go and tsquery_test.go.
> ```

might also help to include a reference to the postgres docs (or your comment in tsvector.go which includes that ref)
___
*[`pkg/util/tsearch/tsquery.go` line 24 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOgofK2V40syy5PGaK:-NFOgofK2V40syy5PGaL:b-8265jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsquery.go#L24)):*
> ```Go
> // tsoperator is an enum that represents the different operators within a
> // TSQuery.
> type tsoperator int
> ```

did you want to make this tsOperator?
___
*[`pkg/util/tsearch/tsquery.go` line 42 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOhC3f33k-q6w4vKLD:-NFOhC3f33k-q6w4vKLE:bmd46i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsquery.go#L42)):*
> ```Go
> 	not
> 	// followedby is the <-> operator. It can also be specified with a number like
> 	// <1> or <2> or <3>. It requires that the left operand is next to the right
> ```

nit: next to -> followed by
___
*[`pkg/util/tsearch/tsvector.go` line 20 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOhbgO3uFNQvHUsDDE:-NFOhbgO3uFNQvHUsDDF:bu7ldq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsvector.go#L20)):*
> ```Go
> )
> 
> // This file defines the tsvector data structure, which is used to implement
> ```

nit: TSVector
___
*[`pkg/util/tsearch/tsvector.go` line 28 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOhxzz-HQZCU2EQxBq:-NFOhxzz-HQZCU2EQxBr:b-monc74) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsvector.go#L28)):*
> ```Go
> // list of lexemes in the doc (typically without stop words like common or short
> // words, and typically stemmed using a stemming algorithm like snowball
> // stemming), along with an associated set of positions that those lexemes occur
> ```

nit: maybe add a link to explain snowball stemming (like this one? https://en.wikipedia.org/wiki/Snowball_(programming_language) )
___
*[`pkg/util/tsearch/tsvector.go` line 44 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOihe595SjLIbQ5O4o:-NFOihe595SjLIbQ5O4p:b-bo2oid) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsvector.go#L44)):*
> ```Go
> // - TSVector is a list of tsTerms, ordered by their lexeme.
> 
> // tsWeight is an bitfield that represents the weight of a given term. When
> ```

nit: an -> a

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85185)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rafiss, and @rytaft)

___
*[`pkg/util/tsearch/eval.go` line 106 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOjll86ku51rbIFBbH:-NFROoF3E1GPv_RyUTwB:b-mnnel1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/eval.go#L106)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you have tests that cover this case? (more generally, have you checked for code coverage?)
</blockquote></details>

Good question which prompted me to run code coverage. Almost the whole file was covered, except for the cases where rPositions.width > lPositions.width in the followed by case. Also, we were missing cases where prefix match fails. I've added tests for those cases.
___
*[`pkg/util/tsearch/lex.go` line 85 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOgYCE5ylP47d-SDHT:-NFRPIeTDC5kmh8jx_lw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/lex.go#L85)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

might help to explicitly mention that / itself could be the following character
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/lex.go` line 99 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOgUAy7XLkB7Yqi0Mx:-NFRPTba5pn8rTRO7pDa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/lex.go#L99)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

might also help to include a reference to the postgres docs (or your comment in tsvector.go which includes that ref)
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsquery.go` line 24 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOgofK2V40syy5PGaK:-NFRPbzX2XMtLbgj5Rzc:b-tdnl5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsquery.go#L24)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you want to make this tsOperator?
</blockquote></details>

Whoops, yes. Done.
___
*[`pkg/util/tsearch/tsquery.go` line 42 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOhC3f33k-q6w4vKLD:-NFRPr9Y3iwGMrKe8DsT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsquery.go#L42)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: next to -> followed by
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsvector.go` line 20 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOhbgO3uFNQvHUsDDE:-NFRPriI7UQXNujDPhRd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsvector.go#L20)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: TSVector
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsvector.go` line 28 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOhxzz-HQZCU2EQxBq:-NFRQ-59D7AHTPfpo1A0:b-kmk7xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsvector.go#L28)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: maybe add a link to explain snowball stemming (like this one? https://en.wikipedia.org/wiki/Snowball_(programming_language) )
</blockquote></details>

Good point, thanks! It's this: https://snowballstem.org/
___
*[`pkg/util/tsearch/tsvector.go` line 44 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85185#-NFOihe595SjLIbQ5O4o:-NFRQ2F55kWvNX6nI9Rr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7818be30f641ee12f954d2762415f3c53bdae5e7/pkg/util/tsearch/tsvector.go#L44)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: an -> a
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Pull request merged**
