### PR TITLE
util/log: don't report ERROR events on stderr by default in test config

### PR DESCRIPTION
**Pull request by knz**
All commits but the last from #69954 and prior.
Informs #69765 (point 4).

Requested by @andreimatei: when NOT using `-show-logs` in
tests (i.e. log output goes to files), we used to include a *copy* of
events at severity ERROR or FATAL on stderr.

We found out experimentally that many tests cause ERROR messages to
occur as part of their normal operator (e.g. ungraceful shutdown of
TestServer).
To reduce noise during troubleshooting of failing tests, this commit
narrows the filtering in that case to only include FATAL messages.
The person can still find the ERROR events and other events in the
generated files.

Release justification: non-production code changes

Release note: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69955#-:-Mj9u4TtB-S1o_Pqsaqk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[pkg/util/log/test_log_scope.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69955#-Mj9teg5BHl7dAIFHskj:-Mj9teg5BHl7dAIFHskk:b-63ggmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c8fc65d8de47e4d5fb42ee27a8c40cbeafd742/pkg/util/log/test_log_scope.go#L221)):*
> ```Go
> 		// calls go to the external stderr, in addition to the log file.
> 		//
> 		// We used to include events at severity ERROR as well, however
> ```

Personally, I'd strike this comment. It seems natural to me to not include ERROR messages, just like we don't include anything else.
I'd say that we want FATAL messages though because those don't pertain to a specific test, but rather to the whole package / `go test` invocation because they stop the execution.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69955)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @rauchenstein)

___
*[pkg/util/log/test_log_scope.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69955#-Mj9teg5BHl7dAIFHskj:-MjFa7-06SVGfQCyTEht:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c8fc65d8de47e4d5fb42ee27a8c40cbeafd742/pkg/util/log/test_log_scope.go#L221)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Personally, I'd strike this comment. It seems natural to me to not include ERROR messages, just like we don't include anything else.
I'd say that we want FATAL messages though because those don't pertain to a specific test, but rather to the whole package / `go test` invocation because they stop the execution.
</blockquote></details>

Done.

**Review by rauchenstein — CHANGES_REQUESTED** [review]
> Reviewed 11 of 31 files at r1, 25 of 25 files at r4, 6 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69955)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @knz)

___
*[-- commits, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69955#-Mj_PYZx1mKZrdDM1mAz):*
operation
(otherwise, change LGTM)

**Comment by knz** [comment]
TFYR!

bors r=andreimatei

**Pull request merged**
