### PR TITLE
sql: implement alter sequence/view owner

### LINKED ISSUE #57965: sql: ALTER VIEW/SEQUENCE .. OWNER TO is not implemented
This is implemented in postgres.

Also, postgres allows using `ALTER TABLE ... OWNER TO` to change the ownership of a view or sequence -- it's not restricted to tables. In CockroachDB, this currently produces an error.

### PR DESCRIPTION
**Pull request by RichardJCai**
Resolves #57965

Release note (sql change): Add support for ALTER VIEW/SEQUENCE OWNER TO commands.

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
Some minor comments, but otherwise looks good 

> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-:-MRMOVAO8DBWR1NHb0Q8:b19052q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea, @RichardJCai, and @solongordon)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRLzr0S0ul7nxpA60ug:-MRLzr0S0ul7nxpA60uh:b-5wyrzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/ccl/importccl/read_import_pgdump.go#L543)):*
> ```Go
> 		// the auto stats stuff will pick up the changes and run if needed.
> 	case *tree.AlterTableOwner:
> 		// ignore
> ```

Why'd this move?
___
*[pkg/sql/alter_table_owner.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRMKrIg5Z9dTDIM22GB:-MRMKrIg5Z9dTDIM22GC:bm7v2hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/sql/alter_table_owner.go#L25)):*
> ```Go
> type alterTableOwnerNode struct {
> 	owner     security.SQLUsername
> 	tableDesc *tabledesc.Mutable
> ```

nit: s/tableDesc/desc
___
*[pkg/sql/alter_table_owner.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRML2pG67rgaeRNQGMF:-MRML2pG67rgaeRNQGMG:b-geh81f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/sql/alter_table_owner.go#L40)):*
> ```Go
> 
> 	tn := n.Name.ToTableName()
> 	requiredTableKind := tree.ResolveAnyTableKind
> ```

This deserves a comment indicating that an ALTER TABLE OWNER applies to views and sequences as well, and that's why we're resolving any descriptor as opposed to a table desc explicitly. 
___
*[pkg/sql/alter_table_owner.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRM57-V9W7tgOwp3xig:-MRM57-V9W7tgOwp3xih:bo3cytt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/sql/alter_table_owner.go#L94)):*
> ```Go
> 
> // checkCanAlterTableAndSetNewOwner handles privilege checking and setting new owner.
> // Called in ALTER TABLE and REASSIGN OWNED BY.
> ```

nit: comment over 80 characters. Also, could you remove the "Called in ALTER ..." seems more effort to maintain than its usefulness. 
___
*[pkg/sql/logictest/testdata/logic_test/alter_view_owner, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRMNKNzEbX9eWGdg4hv:-MRMNKNzEbX9eWGdg4hw:bmrscc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/sql/logictest/testdata/logic_test/alter_view_owner#L44)):*
> ```
> 
> # MATERIALIZED keyword must be present to change the owner of materialized views.
> statement error pq: "mvx" is a materialized view
> ```

What if you say `ALTER TABLE  mvx OWNER TO ...`? Does that work with Postgres? Either way, it's worth adding a test for that case

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59049)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @pbardea, and @solongordon)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRLzr0S0ul7nxpA60ug:-MRMX1CLEvgwfOy9-VC4:bsw62sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/ccl/importccl/read_import_pgdump.go#L543)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Why'd this move?
</blockquote></details>

I split this out from being a general AlterTable subcommand to its own statement (so it could also used for VIEWS/SEQUENCES) so it no longer a subcase of *tree.AlterTable.

Not sure if this case ignore is actually needed though.
___
*[pkg/sql/alter_table_owner.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRML2pG67rgaeRNQGMF:-MRMXlqKDfYHSBWToD_v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/sql/alter_table_owner.go#L40)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This deserves a comment indicating that an ALTER TABLE OWNER applies to views and sequences as well, and that's why we're resolving any descriptor as opposed to a table desc explicitly. 
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/alter_view_owner, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRMNKNzEbX9eWGdg4hv:-MRMYGYH2-cpH8AifSuo:b41l882) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/sql/logictest/testdata/logic_test/alter_view_owner#L44)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

What if you say `ALTER TABLE  mvx OWNER TO ...`? Does that work with Postgres? Either way, it's worth adding a test for that case
</blockquote></details>

Good call! That indeed does work with Postgres, adding a case.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-:-MRQFtlF5QroVDiVaUjD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea, @RichardJCai, and @solongordon)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59049#-MRLzr0S0ul7nxpA60ug:-MRQFr9j6rf9kMsyJjv3:b-iwj8fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca27b89e6d29c42f15f2d3616439119eef31dd7b/pkg/ccl/importccl/read_import_pgdump.go#L543)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I split this out from being a general AlterTable subcommand to its own statement (so it could also used for VIEWS/SEQUENCES) so it no longer a subcase of *tree.AlterTable.

Not sure if this case ignore is actually needed though.
</blockquote></details>

Ah makes sense, I was just curious.

**Comment by RichardJCai** [comment]
bors r=arulajmani

**Pull request merged**
