### PR TITLE
kv: combine local and global uncertainty limit into Interval struct

### PR DESCRIPTION
**Pull request by nvb**
This commit combines the server-side "local" and "global" uncertainty limits into an `uncertainty.Interval` struct. It also centralizes the computation of this interval to an `uncertainty.ComputeInterval` function.

As a result, MVCC no longer reaches inside of a `Transaction` object to construct its implied uncertainty interval. Instead, an uncertainty interval is supplied to MVCC directly.

This refactor is made in preparation for a follow-on commit that will address #58459 (giving non-transactional requests uncertainty intervals), which in turn will prepare to simplify HLC handling throughout the system.

The refactor also cleanly addresses a goal I've had to make the local uncertainty limit a `ClockTimestamp`, which helps clarify its role in the system.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 17 of 17 files at r1, 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73244)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvserver/uncertainty/compute.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-MpevxLB4vtv5lTFMHH3:-MpevxLB4vtv5lTFMHH4:bbsvoxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e4ecdc3e666a03ae8dd35cabcab8526bb06a0/pkg/kv/kvserver/uncertainty/compute.go#L56)):*
> ```Go
> //    is guaranteed to be greater than any write which occurred on the
> //    right-hand side.
> // TODO(nvanbenschoten): fix this bug with range merges.
> ```

Is there an issue for this?
___
*[pkg/kv/kvserver/uncertainty/interval.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-Mpey74w6TTuZ8XHka_n:-Mpey74x4G9L-E-ShqZ3:bz8kgn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e4ecdc3e666a03ae8dd35cabcab8526bb06a0/pkg/kv/kvserver/uncertainty/interval.go#L50)):*
> ```Go
> // uncertain to a reader with a ReadTimestamp below the value's and with
> // the specified uncertainty interval.
> func (in Interval) IsUncertain(valueTs hlc.Timestamp) bool {
> ```

So now `Interval{}.IsUncertain(ts)` is always false, meaning we have some special casing for non-txnal requests right now? Might be worth a note.

**Review by sumeerbhola — COMMENTED** [review]
:lgtm: for the storage package changes

> Reviewed 3 of 17 files at r1, 12 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-:-Mpi41raCzKwKMWQExFL:btkz71r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/uncertainty/compute.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-MpevxLB4vtv5lTFMHH3:-Mpi2mjA0NoQTduCy3yB:b-8byaxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e4ecdc3e666a03ae8dd35cabcab8526bb06a0/pkg/kv/kvserver/uncertainty/compute.go#L56)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is there an issue for this?
</blockquote></details>

I don't fully understand this example, given that observed timestamps are for a node. Presumably n1 is not the leaseholder for r2 before the merge, and "acquires" the lease as a side-effect of the merge since it is r1's raft group that is continuing post merge?

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-:-MpiuAtuDwjgQ8w95bLN:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @irfansharif, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/uncertainty/compute.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-MpevxLB4vtv5lTFMHH3:-Mpj6er0EsEYCNyjiZC0:b8l8knf) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e4ecdc3e666a03ae8dd35cabcab8526bb06a0/pkg/kv/kvserver/uncertainty/compute.go#L56)):*
I have a branch that addresses this, but I'm not happy enough with it to commit to a fast follow PR. So +1 on this getting an issue. I opened https://github.com/cockroachdb/cockroach/issues/73292 to track this.

> Presumably n1 is not the leaseholder for r2 before the merge, and "acquires" the lease as a side-effect of the merge since it is r1's raft group that is continuing post merge?

Right, n1 is not the leaseholder for r2.

What you said is one way to view what's broken here. Merging a right-hand neighbor into a LHS range does not force the LHS range to acquire a new lease. So r1's lease can extend from before the merge to beyond it. This breaks the existing logic that forwards the local limit to the lease start time.

Or are you saying that you would expect that the replica of r2 on n1 would acquire the lease before the merge could complete? This is not the case. We don't require collocated leaseholders before a merge can complete. But even if we did, that would not be enough to address this issue. We would still need some way to ignore observed timestamps acquired from n1 before the lease transfer occurred.
___
*[pkg/kv/kvserver/uncertainty/interval.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-Mpey74w6TTuZ8XHka_n:-Mpj5fY2DHzkKJUgWXPE:b-7ws1hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e4ecdc3e666a03ae8dd35cabcab8526bb06a0/pkg/kv/kvserver/uncertainty/interval.go#L50)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

So now `Interval{}.IsUncertain(ts)` is always false, meaning we have some special casing for non-txnal requests right now? Might be worth a note.
</blockquote></details>

I don't quite understand. A follow on PR will be adding uncertainty intervals to non-txnal requests, but for now, no value is uncertain to a non-txnal request. There isn't special casing for this. Well, there is for efficiency purposes (see `pebbleMVCCScanner.checkUncertainty`), but there doesn't need to be.

Any chance you read this as `IsNotUncertain` or `IsCertain` and that's where the confusion is coming from?

Also, I added test cases for this.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73244)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @irfansharif, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/uncertainty/interval.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-Mpey74w6TTuZ8XHka_n:-Mpk2Dzk38OPanjn80_I:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e4ecdc3e666a03ae8dd35cabcab8526bb06a0/pkg/kv/kvserver/uncertainty/interval.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't quite understand. A follow on PR will be adding uncertainty intervals to non-txnal requests, but for now, no value is uncertain to a non-txnal request. There isn't special casing for this. Well, there is for efficiency purposes (see `pebbleMVCCScanner.checkUncertainty`), but there doesn't need to be.

Any chance you read this as `IsNotUncertain` or `IsCertain` and that's where the confusion is coming from?

Also, I added test cases for this.
</blockquote></details>

:thumbsup:

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73244)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/uncertainty/compute.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73244#-MpevxLB4vtv5lTFMHH3:-MplCAAb1GAFFD0XzZtd:bz4xcwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e4ecdc3e666a03ae8dd35cabcab8526bb06a0/pkg/kv/kvserver/uncertainty/compute.go#L56)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I have a branch that addresses this, but I'm not happy enough with it to commit to a fast follow PR. So +1 on this getting an issue. I opened https://github.com/cockroachdb/cockroach/issues/73292 to track this.

> Presumably n1 is not the leaseholder for r2 before the merge, and "acquires" the lease as a side-effect of the merge since it is r1's raft group that is continuing post merge?

Right, n1 is not the leaseholder for r2.

What you said is one way to view what's broken here. Merging a right-hand neighbor into a LHS range does not force the LHS range to acquire a new lease. So r1's lease can extend from before the merge to beyond it. This breaks the existing logic that forwards the local limit to the lease start time.

Or are you saying that you would expect that the replica of r2 on n1 would acquire the lease before the merge could complete? This is not the case. We don't require collocated leaseholders before a merge can complete. But even if we did, that would not be enough to address this issue. We would still need some way to ignore observed timestamps acquired from n1 before the lease transfer occurred.
</blockquote></details>

Thanks for clarifying the details -- this matches what I was guessing.

**Pull request merged**
