### PR TITLE
release-23.1: opt: add GenerateTrigramSimilarityInvertedIndexScans rule

### LINKED ISSUE #112675: sql: trigram-index-accelerated fuzzy string matching slow for long search strings
When using trigram indexes to accelerate string operations, the optimizer usually constructs a plan like:

```
filter
    index join
        inverted filter
            scan trigram index
```

The inverted filter aggregates trigram matches to produce a set of PKs for the index join. In the case of `=` and `LIKE` the aggregation is an AND of all of the searched-for trigrams, that is, in order for a PK to match it must have been found in all of the trigram spans. But in the case of `%` (fuzzy string matching, or similarity matching) the aggregation is an OR of all of the searched-for trigrams, that is, any PK that was found in any of the trigram spans matches. This can lead to very large index joins, which are then immediately filtered out. Here's an example:

```sql
CREATE TABLE s (s STRING, INVERTED INDEX (s gin_trgm_ops));
INSERT INTO s SELECT to_hex(generate_series(0, 65535));

-- In both of these cases the AND inverted filter reduces the 64 matched trigrams to 1 PK.
EXPLAIN ANALYZE SELECT s FROM s WHERE s = 'abcd';
EXPLAIN ANALYZE SELECT s FROM s WHERE s LIKE '%abcd%';

-- With the similarity threshold set to max, only one row should match.
SET pg_trgm.similarity_threshold = 1;

-- But the OR inverted filter only reduces the 4962 matched trigrams to 4638 PKs,
-- even though the final filter will end up producing just a single row.
EXPLAIN ANALYZE SELECT s FROM s WHERE s % 'abcd';
```

This effect gets worse for longer search strings, such that trigram index acceleration for very long search strings is probably slower than a full-table scan. This is discussed a bit in #93830.

But I think there's a way to make the inverted filter step smarter for fuzzy string matching. Instead of a plain OR, the inverted filter could require PKs to appear in at least N trigram spans (where N = 1 is equivalent to OR, and N > 1 is more selective). We can calculate N based on the value of `pg_trgm.similarity_threshold` and the number of trigrams in the search string, L, as simply:

N = pg_trgm.similarity_threshold * L

For the example above, I think this would cause the inverted filter to produce only a single row instead of 4638.

Jira issue: CRDB-32547

### PR DESCRIPTION
**Pull request by mgartner**
Backport 4/5 commits from #121973.

/cc @cockroachdb/release

---

#### sql: add optimizer_use_trigram_similarity_optimization setting

This commit adds a new session setting called
`optimizer_use_trigram_similarity_optimization`. It currently has no
effect, but in future commits it will allow control over a new
optimization for queries with trigram similarity filters.

Release note: None

#### sql: disable inverted scans when similarity optimization is enabled

The `GenerateInvertedIndexScans` rule is now disabled for similarity
filters on trigram indexes when the
`optimizer_use_text_similarity_optimization` session setting is enabled.
In a future commit this setting will enable a new rule that makes
`GenerateInvertedIndexScans` obsolete. There is no reason to trigger
both rules.

Release note: None

#### opt: add GenerateTrigramSimilarityInvertedIndexScans rule

The `GenerateTrigramSimilarityInvertedIndexScans` exploration rule has
been added, which index-accelerates trigram similarity filters. See the
comment above the newly added custom function for more details. In
future commits, this rule will be optimized further.

The tests for this rule break from convention: they are added to a new
file rather than to the `select` test file corresponding to the location
of the rule in `select.opt`. This proposed new method of organization is
motivated by the huge growth of the `select` file over the years. If
there is agreement on this, we can incrementally reorganize all existing
tests to match.

Release note (performance improvement): More efficient query plans are
now generated for queries with text similarity filters, e.g.,
`text_col % 'foobar'`. These plans are generated if the
`optimizer_use_trigram_similarity_optimization` session setting is
enabled. It is disabled by default.

#### opt: reduce scanned trigrams for similarity filters

The `GenerateSimilarityInvertedIndexScans` exploration rule now
generates plans that scan fewer trigrams. See the added code comments
for more details.

Epic: None

Release note: None

---

Release justification: Performance improvements gated behind a
session setting.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
Should have asked this on the other backport PRs, but is the last commit necessary to backport? Otherwise, :lgtm: 

> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 14 of 14 files at r3, 9 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122723#-:-Nw5Y6OMC9g_8uCzFhUf:b-awk8jd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by mgartner** [comment]
No it's not strictly necessary but it was identical code, so it seems low risk. But I can remove it here and revert in the other release branches if you feel strongly about it.

**Comment by mgartner** [comment]
Ya, let's remove it. I'll revert from 23.1.20-rc and 23.2 too.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 14 of 14 files at r3, 9 of 9 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122723#-:-Nw61tEh2BBSd5pQ4De6:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
Removed the last commit and reverted in other release branches where this PR was already backported: #122830 #122831

**Comment by rytaft** [comment]
*[`-- commits` line 54 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122723#-Nw664_u6NaG8sRa9Ify):*
Now it looks like you've included this commit twice

**Comment by mgartner** [comment]
*[`-- commits` line 54 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122723#-Nw664_u6NaG8sRa9Ify):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Now it looks like you've included this commit twice
</blockquote></details>

I think reviewable is confused. Github shows just 4 commits: https://github.com/cockroachdb/cockroach/pull/122723/commits

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122723#-:-Nw6BYFS3Uo2Lg_OIgaU:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 54 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122723#-Nw664_u6NaG8sRa9Ify):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think reviewable is confused. Github shows just 4 commits: https://github.com/cockroachdb/cockroach/pull/122723/commits
</blockquote></details>

Oh ok, great.

**Pull request merged**
