### PR TITLE
importer: fix flaky TestImportIntoCSV

### LINKED ISSUE #100366: sql/importer: TestImportIntoCSV failed
sql/importer.TestImportIntoCSV [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9371042?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9371042?buildTab=artifacts#/) on master @ [a6b9ad50967f49a2fde23b24a0c0cebb87c1c188](https://github.com/cockroachdb/cockroach/commits/a6b9ad50967f49a2fde23b24a0c0cebb87c1c188):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 1574471 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x88
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestImportIntoCSV
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1bb943832b8a00effe98912a1a7e8043/logTestImportIntoCSV1410107140
    test_log_scope.go:79: use -show-logs to present logs inline
=== RUN   TestImportIntoCSV/import-into-auto-bzip
=== RUN   TestImportIntoCSV/import-into-explicit-gzip
=== RUN   TestImportIntoCSV/import-into-explicit-gzip-wildcard
=== RUN   TestImportIntoCSV/import-into-no-database
=== RUN   TestImportIntoCSV/import-into-no-decompress
=== RUN   TestImportIntoCSV/empty-with-files
=== RUN   TestImportIntoCSV/import-into-bad-opt-name
=== RUN   TestImportIntoCSV/import-into-explicit-bzip
=== RUN   TestImportIntoCSV/import-into-no-decompress-gzip#01
=== RUN   TestImportIntoCSV/import-into-no-decompress-wildcard
=== RUN   TestImportIntoCSV/empty-file
=== RUN   TestImportIntoCSV/import-into-implicit-bzip
=== RUN   TestImportIntoCSV/import-into-implicit-gzip
=== RUN   TestImportIntoCSV/import-into-no-table
=== RUN   TestImportIntoCSV/import-no-files-match-wildcard
=== RUN   TestImportIntoCSV/import-into-auto-gzip
=== RUN   TestImportIntoCSV/import-into-auto-bzip-wildcard
=== RUN   TestImportIntoCSV/import-into-auto-decompress
=== RUN   TestImportIntoCSV/import-into-no-decompress-gzip
=== RUN   TestImportIntoCSV/import-into-no-glob-wildcard
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestImportIntoCSV.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26389

### LINKED ISSUE #100477: TestImportIntoCSV/import-into-no-glob-wildcard  flaked on master
See CI flake[ here](https://teamcity.cockroachdb.com/viewLog.html?buildId=9403574&)

Jira issue: CRDB-26456

More details:
```
=== RUN   TestImportIntoCSV/import-into-no-glob-wildcard
    import_stmt_test.go:3121: error executing 'RESUME JOB $1': pq: job 853514721570684929: job with status pause-requested cannot be resumed
=== RUN   TestImportIntoCSV/import-into-unique_rowid
    import_stmt_test.go:3377: error executing 'CREATE TABLE t (a INT, b STRING)': pq: relation "defaultdb.public.t" already exists
=== RUN   TestImportIntoCSV/import-into-checkpoint-leftover
=== RUN   TestImportIntoCSV/import-into-checkpoint-leftover/nonEmptyTable
    import_stmt_test.go:3411: error executing 'CREATE TABLE t (a INT PRIMARY KEY, b STRING)': pq: relation "defaultdb.public.t" already exists
=== RUN   TestImportIntoCSV/import-into-checkpoint-leftover/empty-table
    import_stmt_test.go:3411: error executing 'CREATE TABLE t (a INT PRIMARY KEY, b STRING)': pq: relation "defaultdb.public.t" already exists
...
```

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes an oversight of 117f712552e79d55621f0af9d6fc1acc3b18e8aa that made TestImportIntoCSV flaky. In particular, that commit made it so that if the import fails but is actually paused, the corresponding import job is resumed. This is needed in order to bring the table back online before it can be safely dropped. However, resuming of the job might fail if the job still has the "pause-requested" status, thus, this commit adds a waiting mechanism before the job transitions out of this status. Additionally, that resume can hang (or take a very long time), so this commit switches to canceling the job instead.

Fixes: #100366.
Fixes: #100477.

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100675#-:-NSH9nTj-VXa5ltg_DL4:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Actually, it seems like the test can still get stuck, and although I don't think this commit is making anything worse, I'll spend some more time on de-flaking it.

bors r-

**Comment by yuzefovich** [comment]
I switched from resuming the paused job to canceling it, got an hour on the gceworker with no failures. Will stress the test overnight and will merge tomorrow if no failures / timeouts occur.

**Comment by yuzefovich** [comment]
```
9708 runs so far, 0 failures, over 15h28m35s
```

bors r+

**Pull request merged**
