### PR TITLE
parser: fix GetTypeFromValidSQLSyntax for collated strings

### LINKED ISSUE #77353: Use of COLLATE in a statement bundle stats file causes error during injection
If you generate a statement bundle, and one of the histogram buckets has a reference to a collation, then when injecting those stats later, it fails.

```
           {
                "distinct_range": ...,
                "num_eq": ...,
                "num_range": ...,
                "upper_bound": "e''\\x01....\x00 '' COLLATE en_US_u_ks_level2"
            },
```

Importing:

```
ERROR: internal error: expected a tree.CastExpr, but found *tree.CollateExpr
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:392: GetTypeFromValidSQLSyntax()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/stats/json.go:132: GetHistogram()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:1251: injectTableStats()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:900: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:508: func2()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:119: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:296: visitInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86: visit()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:50: walkPlan()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:511: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:135: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:156: Init()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91: CatchVectorizedRuntimeError()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:273: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:780: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:388: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:528: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1176: PlanAndRun()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1235: execWithDistSQLEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:926: dispatchToExecutionEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:669: execStmtInOpenState()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:125: execStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1548: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1550: execCmd()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1471: run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:495: ServeConn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:628: func1()
/usr/local/go/src/runtime/asm_amd64.s:1374: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.
```

Jira issue: CRDB-13545

Epic CRDB-14510

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, `GetTypeFromValidSQLSyntax` would result in an error when attempting to parse a collated string. This is due to an expression like `1::STRING COLLATE en` being parsed as `CollateExpr(CastExpr)` whereas the function expected just `CastExpr`. This is now fixed by having a special case for the collated strings.

Additionally, this commit adds a couple of testing improvements around the collated strings:
- a representative collated string type is now included into `randgen.SeedTypes` (this actually exposed a minor bug in recently introduced `tree.DatumNext` method)
- a new test is introduced that asserts that for all (with a few exceptions) type families at least one representative type is included into `randgen.SeedTypes`.

Fixes: #77353.

Release note (bug fix): Previously, `ALTER TABLE ... INJECT STATISTICS` command would fail if a column with COLLATED STRING type had histograms to be injected, and this is now fixed. The bug has been present since at least 21.2.

### CODE REVIEW

**Comment by yuzefovich** [comment]
There are some interesting failures, will need to spend more time. Hold off on reviewing for now.

**Comment by yuzefovich** [comment]
RFAL. @rafiss let me know if you think someone else should be reviewing this.

**Comment by yuzefovich** [comment]
Friendly ping @rafiss

**Review by rafiss — APPROVED** [review]
sorry for missing this! this lgtm! i had some optional comments on the release note and a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96695#-:-NOpnvPpDganuMKbd5w0:b-62mczi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96695#-NOpnLWE82uCGiOD62Cb):*
seems like https://github.com/cockroachdb/cockroach/issues/77353 was a user-facing bug report. so i think we could have a release note like "fixed an error that could happen when capturing statement diagnostics for a query that references a COLLATE expression"
___
*[`pkg/sql/parser/parse_test.go` line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96695#-NOpnquTBi-vCxkGiDYL:-NOpnquTBi-vCxkGiDYM:b5x7692) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c8bb34b200509b32d0a3ef6e20c73ecfc4744b/pkg/sql/parser/parse_test.go#L761)):*
> ```Go
> 		// TODO(yuzefovich): ideally, we'd assert that the returned type is
> 		// equal to the original one; however, there are some subtle differences
> 		// at the moment (like the width might only be set on the returned
> ```

can't we still assert that the type OIDs are the same though?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96695#-:-NOqTnX39t-z8wJPjOZZ:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96695#-NOpnLWE82uCGiOD62Cb):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

seems like https://github.com/cockroachdb/cockroach/issues/77353 was a user-facing bug report. so i think we could have a release note like "fixed an error that could happen when capturing statement diagnostics for a query that references a COLLATE expression"
</blockquote></details>

Good point, done.
___
*[`pkg/sql/parser/parse_test.go` line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96695#-NOpnquTBi-vCxkGiDYL:-NOqTfi0BSJ7N1rEa_zD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c8bb34b200509b32d0a3ef6e20c73ecfc4744b/pkg/sql/parser/parse_test.go#L761)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can't we still assert that the type OIDs are the same though?
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Seems that I need to adjust one of recently merged tests.

bors r-

**Comment by yuzefovich** [comment]
It was actually a bug introduced in #97152. The impact of that bug is minor, so I just included the fix into this PR.

bors r+

**Pull request merged**
