### PR TITLE
release-21.1: acceptance: run `python`, `psql` containers as current uid

### PR DESCRIPTION
**Pull request by rickystewart**
Manual cherry-pick from #81460.

`postgres`'s permission checking for certificates has gotten more
rigorous since [this commit](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=a59c79564bdc209a5bc7b02d706f0d7352eb82fa).
This has broken a couple `acceptance` tests which do not pin to any
specific `postgres` version (see #81313, #81437).

Here we attempt to solve the problem "once and for all" by ensuring that
these containers run with a UID that is equal to the one that created
the certificates.

Release note: None
Release justification: Test-only change

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Comment by otan** [comment]
(there is a test failing tho)

**Comment by rickystewart** [comment]
@knz Cherry-picking the fix to `TestComposeGSSPython` isn't really working. With a simple manual cherry-pick I had [this error](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/5246630?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true):

```
python_1     | psql: ERROR:  password authentication failed for user roach
```

I then tried to update `pkg/acceptance/compose/gss/python/Dockerfile` to make it closer to the content we have at `master`, but that didn't do the trick either. Now I get [this error](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/5248097?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true):

```
python_1     | psql: could not read certificate file "/certs/client.root.crt": ee key too small
```

I don't know what the exact root cause of this is but I don't know if `client.root.crt` even exists at this old branch.

Can you advise about what changes we need to make to get the test working on `release-21.1`? Alternatively we can start skipping this test outright at `release-21.1`, I'm not sure what (if any) value it is providing at this point.

**Comment by knz** [comment]
Need to rebase on top of  #81730.

**Comment by rickystewart** [comment]
> I see I can't merge #81730 without this PR, and this one can't merge without the other one. So I think the best way is to integrate the two commits into one PR (presumably this one).

Done, going to make sure it passes CI.

**Pull request merged**
