### PR TITLE
acceptance: maybe deflake acceptance/multi-tenant

### LINKED ISSUE #65335: roachtest: acceptance/multitenant failed
roachtest.acceptance/multitenant [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2988247&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2988247&tab=artifacts#/acceptance/multitenant) on master @ [adb98c20a536c80885b3eddb7119248a6549d29f](https://github.com/cockroachdb/cockroach/commits/adb98c20a536c80885b3eddb7119248a6549d29f):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: artifacts/acceptance/multitenant/run_1
	sql_runner.go:59,multitenant_upgrade.go:431,multitenant.go:47,acceptance.go:98,test_runner.go:784: error executing 'CREATE TABLE foo (id INT PRIMARY KEY, v STRING)': dial tcp 127.0.0.1:36258: connect: connection refused
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh acceptance/multitenant
```
</p>
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*acceptance/multitenant.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by tbg**
Closes #65335.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
This commit failed in CI with exactly the thing I wanted to fix. But I had it pass dozens of times on my local machine and 200 times on roachprod VMs. 🤔

**Comment by tbg** [comment]
oh and it *also* failed on the bors run.

**Review by ajwerner — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachtest/multitenant_upgrade.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65386#-MaZkt0ZAJmClgjvxSeY:-MaZkt0ZAJmClgjvxSeZ:bav7zl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad4aefd23e758c49822b3da9477e10fec06d5c4/pkg/cmd/roachtest/multitenant_upgrade.go#L107)):*
> ```Go
> 	tn.pgURL = u.String()
> 
> 	// The tenant is usually responsible ~right away, but it
> ```

responsive?

**Comment by tbg** [comment]
This seems to fail reliably on CI. I have no idea why.

**Comment by tbg** [comment]
Aha - the tenant wasn't actually flushing the logs on any signal. I fixed that now.

bors r=ajwerner,erikgrinaker

**Pull request merged**
