### PR TITLE
workload/tpcc: forward port everything

### PR DESCRIPTION
**Pull request by jordanlewis**
This is my attempt at forward porting all of the progress except for the checks in loadgen/tpcc to workload.

The commits are roughly named - I'll squash them further after the review, but it's probably easier to keep them like this for the review.

@danhhz 2 main things for you to look at - a new `-ramp` global argument, and a new `PostRun` member of the `Hooks` struct.

Also, keep an eye out for the `-split` arg. I see that there's a workload specific split thing, but I'm not sure if that covers the way `tpcc`'s split works.

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/cmd/workload/run.go, line 249 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D3KiU0c7IBfFbLWUU:-L8D3KiU0c7IBfFbLWUV:b-25m4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/cmd/workload/run.go#L249)):*
> ```Go
> 			workFn := workFn
> 			go workerRun(ctx, errCh, &wg, limiter, workFn)
> 			time.Sleep(sleepTime)
> ```

shouldn't this be before the `workerRun` call?

---

*[pkg/workload/workload.go, line 102 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D6-r34p_FJDzRL1DS:-L8D6-r34p_FJDzRL1DT:b-4hq7c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/workload.go#L102)):*
> ```Go
> 	// PostRun is called after workload run has ended. This is where any post-run
> 	// special printing or validation can be done.
> 	PostRun func() error
> ```

does anything call this?

---

*[pkg/workload/tpcc/ddls.go, line 163 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D3Yy-8ogypqanC6qM:-L8D3Yy-8ogypqanC6qN:b8gervm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/ddls.go#L163)):*
> ```Go
> // NB: Since we always split at the same points (specific warehouse IDs and
> // item IDs), splitting is idempotent.
> func splitTables(db *gosql.DB, warehouses int) {
> ```

I don't see any reason this wouldn't work as part of the existing splits stuff. i'm happy to let this be a followup though in order to land this sooner (otherwise we'll be stepping on each other's toes a bit)

---

*[pkg/workload/tpcc/tpcc.go, line 97 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D1gbh5nUuTSkVN75J:-L8D1gbiDZ7rcsXkx1qr:b21reu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/tpcc.go#L97)):*
> ```Go
> 			`serializable`: {RuntimeOnly: true},
> 			`split`:        {RuntimeOnly: true},
> 			`usePostgres`:  {RuntimeOnly: true},
> ```

nit: this isn't a flag, so doesn't need to be here, though it's not hurting anything

---

*[pkg/workload/tpcc/tpcc.go, line 148 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D4HjU3-W6QvyDl5_n:-L8D4HjU3-W6QvyDl5_o:b-ntv0ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/tpcc.go#L148)):*
> ```Go
> 
> 			if w.partitions != 0 && !w.split {
> 				return errors.Errorf(`--partitions requires --split`)
> ```

not your code, but why?

---

*[pkg/workload/tpcc/tpcc.go, line 305 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D6B6B0H7skejA6TsD:-L8D6B6B0H7skejA6TsE:bwv7e8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/tpcc.go#L305)):*
> ```Go
> 	// Assign each DB connection pool to a partition. This assumes that dbs[i] is
> 	// a machine that holds partition "i % *partitions".
> 	partitionDBs := make([][]*gosql.DB, w.partitions)
> ```

the mapping between warehouses+partitions+conns+workers is confusing to me, so I'm just going to assume this is all correct. a diagram or something would be nice if you feel like it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-:-L8D6aRlCALlOB0RBxY1:bnfp4nl)*

**Comment by danhhz** [comment]
pressed that button too quickly. if anything deserves :lgtm_strong: it's this. thanks jordan!

---

Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-:-L8D737XlYDS4agXLWvj:b-5dq07)*

**Comment by solongordon** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/workload/workload.go, line 102 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D6-r34p_FJDzRL1DS:-L8DDDbfA7ISUGp_GYCb:b-3evmwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/workload.go#L102)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

does anything call this?
</blockquote></details>

Dan beat me to it. Doesn't look like the audit checks are ever run.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142)*

**Comment by jordanlewis** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/cmd/workload/run.go, line 249 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-L8D3KiU0c7IBfFbLWUU:-L8DFczbx0Cags2GDMMh:bafpxni) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/cmd/workload/run.go#L249)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

shouldn't this be before the `workerRun` call?
</blockquote></details>

I don't think so - we want the first `workerRun` to happen instantly. (This sleep is in the outer "work starter" goroutine, not the inner per-worker goroutine!) Maybe I'm misunderstanding, though?

---

*[pkg/workload/workload.go, line 102 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-L8D6-r34p_FJDzRL1DS:-L8DFyWPHl6Eb0UgE2Yq:b-no1wxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/workload.go#L102)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Dan beat me to it. Doesn't look like the audit checks are ever run.
</blockquote></details>

Oops, thanks! :sweat_smile: 

---

*[pkg/workload/tpcc/ddls.go, line 163 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-L8D3Yy-8ogypqanC6qM:-L8DG-tyGYIGEk90Ell5:b-81nlyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/ddls.go#L163)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I don't see any reason this wouldn't work as part of the existing splits stuff. i'm happy to let this be a followup though in order to land this sooner (otherwise we'll be stepping on each other's toes a bit)
</blockquote></details>

SGTM!

---

*[pkg/workload/tpcc/tpcc.go, line 97 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-L8D1gbh5nUuTSkVN75J:-L8DG2SEu77vW5IX12q4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/tpcc.go#L97)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: this isn't a flag, so doesn't need to be here, though it's not hurting anything
</blockquote></details>

Done.

---

*[pkg/workload/tpcc/tpcc.go, line 148 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-L8D4HjU3-W6QvyDl5_n:-L8DMD4FlsN6Jv0k2bAR:b-i644vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/tpcc.go#L148)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

not your code, but why?
</blockquote></details>

I'm not sure... I'll follow up with Peter about this later.

---

*[pkg/workload/tpcc/tpcc.go, line 305 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-L8D6B6B0H7skejA6TsD:-L8DMYCv4DRjFy04JO8Q:b-4n9udj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/workload/tpcc/tpcc.go#L305)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

the mapping between warehouses+partitions+conns+workers is confusing to me, so I'm just going to assume this is all correct. a diagram or something would be nice if you feel like it
</blockquote></details>

Yeah, I don't fully understand it either. Calling @petermattis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142)*

**Comment by solongordon** [comment]
Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/workload/run.go, line 337 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142#-L8DRB_49zIMfhMN1TD2:-L8DRB_49zIMfhMN1TD3:b-aghvv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/826fec0bdbcaabc6e4e317a6faac1c2562cb895b/pkg/cmd/workload/run.go#L337)):*
> ```Go
> 
> 			if h, ok := gen.(workload.Hookser); ok {
> 				if err := h.Hooks().PostRun(); err != nil {
> ```

Needs a nil check on `PostRun` I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24142)*

**Comment by danhhz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/workload/run.go, line 249 at r13](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8D3KiU0c7IBfFbLWUU:-L8DTFh32B7rHen-3XS3:b-3hj1xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebda100f859bb1949d3d2a4d00b5db736fc44e13/pkg/cmd/workload/run.go#L249)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think so - we want the first `workerRun` to happen instantly. (This sleep is in the outer "work starter" goroutine, not the inner per-worker goroutine!) Maybe I'm misunderstanding, though?
</blockquote></details>

aha. carry on

---

*[pkg/cmd/workload/run.go, line 337 at r16](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142#-L8DRB_49zIMfhMN1TD2:-L8DTIfuBanZSyiiBMmN:b2nih0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/826fec0bdbcaabc6e4e317a6faac1c2562cb895b/pkg/cmd/workload/run.go#L337)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Needs a nil check on `PostRun` I think.
</blockquote></details>

yup

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24142)*

**Comment by jordanlewis** [comment]
TFTRs!

**Pull request merged**
