### PR TITLE
sql: don't test error identities using reference equality

### LINKED ISSUE #35854: sql: erroneous switches to test error identity
Currently there are a few highly suspicious places where the code is running `switch err { ...` or `switch err.(type) {` to determine whether an error encountered is one of a predefined set of "interesting" errors for which special behavior must be triggered.

This general patterns is highly problematic because:

- the error may have been wrapped (`errors.Wrapf`) and decorated from the point it was generated to the point it is seen. At the very least a `Cause()` should be put in there
- the error may have been flattened / transformed into a `pgerror.Error` with a different error code.

The proper pattern is thus not `if err == errMyInterestingError` but instead `if IsErrorDerived(err, errMyInterestingError)` with some suitably implemented `IsErrorDerived` predicate (which is not yet implemented).

here is the list of problematic codes:

### `conn_executor.go`

```go
        switch t := err.(type) {
        case *roachpb.TransactionRetryWithProtoRefreshError:
          errTxn := t.Transaction
          if errTxn.ID == curTxnID && errTxn.Epoch == curTxnEpoch {
            // A retryable error for the current transaction
            // incarnation is given the highest priority.
            return 1
          }
          return 2
        case *roachpb.TxnAlreadyEncounteredErrorError:
          // Another parallel stmt got an error that caused this one.
          return 5
        default:
          // Any other error. We sort these behind retryable errors
          // and errors we know to be their symptoms because it is
          // impossible to conclusively determine in all cases whether
          // one of these errors is a symptom of a concurrent retry or
          // not. If the error is a symptom then we want to ignore it.
          // If it is not, we expect to see the same error during a
          // transaction retry.
          return 4
        }
```

- maybe the error was wrapped? Note: wrapped pg errors do not preserve the kv error details.
- is it possible the error got flattened into pg error with code 40001 already by that point? 

### `lease.go`

```go
    switch err {
    case nil, errDidntUpdateDescriptor:
      return sqlbase.NewImmutableTableDescriptor(tableDesc.TableDescriptor), nil
    case errLeaseVersionChanged:
      // will loop around to retry
    default:
      return nil, err
    }
```

- this may have been wrapped
- this may have been flattened into a pg error

### `lease.go` again

```go
    switch err {
    case errRenewLease:
      // Renew lease and retry. This will block until the lease is acquired.
      if _, errLease := acquireNodeLease(ctx, m, tableID); errLease != nil {
        return nil, hlc.Timestamp{}, errLease
      }
      if m.testingKnobs.LeaseStoreTestingKnobs.LeaseAcquireResultBlockEvent != nil {
        m.testingKnobs.LeaseStoreTestingKnobs.LeaseAcquireResultBlockEvent(LeaseAcquireBlock)
      }

    case errReadOlderTableVersion:
      // Read old table versions from the store. This can block while reading
      // old table versions from the store.
      versions, errRead := m.readOlderVersionForTimestamp(ctx, tableID, timestamp)
      if errRead != nil {
        return nil, hlc.Timestamp{}, errRead
      }
      m.insertTableVersions(tableID, versions)

    default:
      return nil, hlc.Timestamp{}, err
    }
```

- this may have been wrapped
- this may have been flattened into a pg error

### `schema_changer_go`

```go
  switch err {
  case
    context.Canceled,
    context.DeadlineExceeded,
    errExistingSchemaChangeLease,
    errExpiredSchemaChangeLease,
    errNotHitGCTTLDeadline,
    errSchemaChangeDuringDrain,
    errSchemaChangeNotFirstInLine:
    return false
  }
  switch err := err.(type) {
  case errTableVersionMismatch:
    return false
  case *pgerror.Error:
    switch err.Code {
    case pgerror.CodeSerializationFailureError, pgerror.CodeConnectionFailureError:
      return false

    case pgerror.CodeInternalError:
      if err.Message == context.DeadlineExceeded.Error() {
        return false
      }

    }
  }
```

- the error may have been wrapped
- the pgerror comparison is wrong. Although I think vivek is fixing that in #35851 already?

### `sequence.go`

```go
      switch err.(type) {
      case *roachpb.IntegerOverflowError:
        return 0, boundsExceededError(descriptor)
      default:
        return 0, err
      }
```

- the error may have been wrapped

### PR DESCRIPTION
**Pull request by knz**
Fixes  #35854.

Prior to this patch, the SQL code was expecting to identify
errors by addess, ie. something like:

```go
// at global scope
var errSomething = errors.New(...)

// somewhere in the code
   if err == errSomething { ... }
```

This approach was flawed in that errors can be wrapped (`errors.Wrap`,
`errors.WithMessage`) or flattened (`pgerror.Wrap`) or sent over the
wire.

To make the code more robust, this patch introduces a new API
`pgerror.WithMarker()` which instantiates errors with a unique
marker. The marker is guaranteed to be preserved through `errors.Wrap`
and `pgerror.Wrap` calls. It can be tested with
`pgerror.IsMarkedError()`.

The patch then updates the various points in the SQL code where errors
were tested in that way, to use the new API.

(In some places some attempt is made to "work around" with a string
comparison on the message instead, but that's arguably even worse for
reasons left as an exercise to the reader. This should also be fixed,
but that fix is out of scope here.)

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@lucy-zhang I am sending this out as a generally beneficial fix. 

I have not yet confirmed the origin of the schema change flake we've been discussing earlier, and thus I don't know whether this PR fixes it. Tomorrow I hope to conduct tests against my hypothesis, and determine whether this PR addresses the problem.

However regardless I think the way the errors were compared was problematic and the present PR generally improves things.

**Comment by knz** [comment]
I also just added a test of the new special case.

**Review by bobvawter — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @lucy-zhang, and @vivekmenezes)

___
*[pkg/sql/pgwire/pgerror/markers.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35920#-LaLOf3BCrIPDKZ8-LtL:-LaLOf3BCrIPDKZ8-LtM:bxmted0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d93fac3f43c28dd6fb9bfe0abd7b9193317eb02e/pkg/sql/pgwire/pgerror/markers.go#L64)):*
> ```Go
> // - instead of including the line number or function name, so that
> //   the marker persists across minor code refactorings; this ensures
> //   comparability across mixed version clusters.
> ```

I don't think this kind of identity is safe.  Renaming a `.go` file or moving a symbol between files in a package is basically a no-op as far as refactorings or cleanups go.  Baking the filename into the marker would create landmines for subsequent developers.

What if there were a function to create markers that required the developer to include a globally-unique string?  This could be enforced by having a static "registry" map to ensure that no duplicate values are present.  A `Marker` is then mixed with an `error` to produce a `MarkedError`.  It's weird to me that the marker objects are themselves errors.

```
var ContextCanceledMarker Marker = MakeMarker(context.Canceled, "pgerror.ContextCanceled")
```

**Comment by knz** [comment]
That was my first implementation. The problem with that, I found, is that people are really bad at inventing names.

Then where would you store this global registry? And prevent changes that rename the error by changing the string?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Review by bobvawter — COMMENTED** [review]
> Then where would you store this global registry? And prevent changes that rename the error by changing the string?

The markers could go in a new, leaf package `pgerror/marker`.

```
package somepkg

var MyMarker = marker.New("somepkg.MyMarker")
```

If I saw the code above, I'd be pretty justified in assuming that the constant string value is meaningful, but I would never consider the enclosing file or package to ever be meaningful.

As to the naming issue, we're in the same boat as telemetry.  We only need names to be distinct within the project and governed by our code-review process.  If the marker API clearly indicates that the string values ought not to be changed, I think we would have fewer problems in practice than by incorporating too much magic into the markers.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35920#-:-LaLZwP_5PWjKCGlMehF:b-2iuvr1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @lucy-zhang, and @vivekmenezes)

**Comment by andreimatei** [comment]
I haven't looked at the code, but I wonder how `pgerror.IsMarkedError()` is different from `errors.Cause(err)` ? Don't they serve the same purpose - to unwrap?

**Comment by vivekmenezes** [comment]
another test failure caused by poor unwrapping of errors:

https://github.com/cockroachdb/cockroach/issues/35734#issuecomment-474820856

**Comment by knz** [comment]
I have discussed this further with @andreimatei  yesterday.

- Bob's remark that we should use unique constant strings is good. I'll implement that.
- however doing this as an additional field inside the pgerror.Error object is misguided. This is because it's desirable to be able to add multiple markers around an error. What we can do is mimic the `errors.Wrap` machinery inside the `pgerror` package for that purpose, ensuring that the wrapper objects are protobuf-encodable.

I will prioritize this work today because it's actually solving a real problem -  #35734.

**Comment by knz** [comment]
Following wise words from Vivek I have decided to not pursue this approach further and instead revert some of my more agressive changes to pgerror.Error throughout the code.
This means that I am putting a band-aid into 19.1 to ensure that  #35854 is not going to be too serious. The band-aid is in #36023.

This ensures that the original error objects are left intact through `pgerror.Wrap` and can still be compared with equality.

The present PR can be left to sleep for the time being.

**Comment by knz** [comment]
I'll be wanting to rebase this on top of #37765.

**Comment by knz** [comment]
Subsumed by #37765.

**Pull request closed without merging**
