### PR TITLE
exec: add Outbox/Inbox for remote communication

### LINKED ISSUE #37052: exec: add outbox/inbox
Write inbox/outbox components.

The outbox component should serialize `coldata.Batch`es and send them through the current `ProducerMessage.Data.RawBytes` to an inbox that deserializes this byte slice back into `coldata.Batch`es to be exposed to the inbox's flow. Current cancellation semantics should be observed.

### PR DESCRIPTION
**Pull request by asubiotto**
This commit adds an Outbox component that pulls coldata.Batches from
an upstream Operator, serializes them, and sends them over a FlowStream
bidirectional RPC to an Inbox, that then exposes these batches to its
vectorized execution flow.

This commit does not include metadata or draining or planning of these
components. These features will be added in following PRs. The goal of
this commit is to simply introduce the components and test a normal
flow of execution (graceful termination) but nothing else.

Release note: None

The other commits are mostly testing-related, with one bugfix.

Closes #37052 

The work that still needs to be done is outlined in #37224 and #37051

### CODE REVIEW

**Comment by asubiotto** [comment]
Assigning @jordanlewis as primary reviewer but cc @yuzefovich @solongordon @mjibson

**Review by yuzefovich — COMMENTED** [review]
This looks great! And it :lgtm: (modulo my limited understanding of the RPC stuff).

> Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 5 of 5 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-:-LeD1EHVBAB-GMEQecfh:booz0v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/random_testutils.go, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCqbVo0h52uVT_3l0V:-LeCqbVo0h52uVT_3l0W:b-jdi3c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/random_testutils.go#L184)):*
> ```Go
> 
> // RandomDataOpArgs are arguments passed in to RandomDataOp. All arguments are
> // optional (refer to the constants above this struct definition for the
> ```

[nit]: missing closing parenthesis.
___
*[pkg/sql/exec/random_testutils.go, line 288 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCrbFt-YYRLxcQlnT7:-LeCrbFt-YYRLxcQlnT8:b-dnsrpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/random_testutils.go#L288)):*
> ```Go
> 	}
> 
> 	b := randomBatchWithSel(o.rng, o.typs, o.batchSize, nullProbability, selProbability)
> ```

~I think using `randomBatchWithSel` will always set the length of the batch to the length of the generated selection vector, so if `o.selection == false`, that will shorten the batch. Is this the desired behavior? I think we should use `randomBatch` in that case.~ I see, actually `selProbability` will be 0 in that case and the length won't be updated. Please add a note explaining this logic.
___
*[pkg/sql/exec/colrpc/colrpc_test.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCtRH_Dfs6zuhz_19X:-LeCtRH_Dfs6zuhz_19Y:bp0jgp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/colrpc_test.go#L71)):*
> ```Go
> }
> 
> // Recv is part of the flowStreamServer interface. Should only be called from
> ```

[nit]: it's slightly odd that only this method has a comment.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCy6Jc7jRBv98-bOde:-LeCy6Jc7jRBv98-bOdf:bx2w7p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox_test.go#L61)):*
> ```Go
> 		cancelFn()
> 		// Next should not block if the context is canceled.
> 		inbox.Next(ctx)
> ```

[nit]: it might be worth checking that a zero length batch is returned.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeD16cS9OIOxQDazS3Y:-LeD16cTC9ll1mVjX4c4:butn4ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox_test.go#L133)):*
> ```Go
> 	}()
> 
> 	require.Panics(t, func() { inbox.Next(context.Background()) })
> ```

[nit]: a comment what this should panic would be useful.
___
*[pkg/sql/exec/colrpc/outbox.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCzYo04e5qC5aGcnqC:-LeCzYo04e5qC5aGcnqD:b-dqvvqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L65)):*
> ```Go
> 	o := &Outbox{
> 		// Add a deselector as selection vectors are not serialized (nor should they
> 		// be). TODO(asubiotto): Do we want a coalescer too?
> ```

I think yes since with a coalescer we should experience less overhead (just my feeling), right? I remember doing the benchmarks and a pair deselector-coalescer was showing like 1-2GBs throughput which I don't think the network will give us.

**Review by jordanlewis — COMMENTED** [review]
First 3 commits LGTM, will look at the main commit tomorrow.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-:-LeFTRr43tzq0T2B3LDH:b1lo2b0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by jordanlewis — COMMENTED** [review]
Sorry about the delay on this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-:-Leli8qs89ZKGO4k9rjw:bewds48)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox.go, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelar3q52wynGClrCvE:-Lelar3q52wynGClrCvF:bdm8cn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L103)):*
> ```Go
> // sets the stream to read from. ctx ownership is retained until the stream
> // arrives (to allow for unblocking the wait for a stream), at which point
> // ownership is transferred to RunWithStream.
> ```

This will be called by the main setup goroutine, right? It would be useful to add that information to the comment.
___
*[pkg/sql/exec/colrpc/inbox.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelcfR78BYtm36QhPuC:-LelcfR78BYtm36QhPuD:b1ob4f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L140)):*
> ```Go
> 	// reader goroutine, as returning from the handler will close the stream.
> 	select {
> 	case err := <-i.errCh:
> ```

This is the normal path, right? This will see `nil` when the channel is closed. I would add a comment here about that.
___
*[pkg/sql/exec/colrpc/inbox.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelcBAp79ZzynuKeqsv:-LelcBAp79ZzynuKeqsw:b-eu2mbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L144)):*
> ```Go
> 	case <-readerCtx.Done():
> 		// The reader canceled the stream.
> 		return fmt.Errorf("%s: readerCtx in Inbox stream handler", readerCtx.Err())
> ```

I would enhance these error messages to include the plain english explanation that you have in the comment, to make it easier to understand what's going on when we see these in the logs.
___
*[pkg/sql/exec/colrpc/inbox.go, line 169 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelct7H-DGT_x2b3XAt:-Lelct7H-DGT_x2b3XAu:b4owszl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L169)):*
> ```Go
> 
> 	// NOTE: It is very important to close i.errCh on termination of execution
> 	// (normally or when panicking), otherwise we might leak RunWithStream.
> ```

I think it would be easier to remove all the calls to `close(i.errCh)` in the body, and put one in the `defer` outside of the `recover` block.
___
*[pkg/sql/exec/colrpc/inbox.go, line 188 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Leldd333S-zqHhd_0nq:-Leld8dkEllmXMMBFH9P:b-xe4ih1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L188)):*
> ```Go
> 	i.scratch.data = i.scratch.data[:0]
> 	if err := i.serializer.Deserialize(&i.scratch.data, m.Data.RawBytes); err != nil {
> 		panic(err)
> ```

Does the panic catching machinery that Yahor added need to be extended to understand panics from `exec/colrpc`?
___
*[pkg/sql/exec/colrpc/outbox.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelds8iCeGVTgn76Hf7:-Lelds8iCeGVTgn76Hf8:byf3phg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L59)):*
> ```Go
> 	s, err := colserde.NewRecordBatchSerializer(typs)
> 	if err != nil {
> 		// TODO(asubiotto): Remove err? The only case in which an error is returned
> ```

I think it's fine to leave error returns in constructors - we do it everywhere else too.
___
*[pkg/sql/exec/colrpc/outbox.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCzYo04e5qC5aGcnqC:-Lele4Jx8Ubqo36sbKeg:b9ths6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L65)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think yes since with a coalescer we should experience less overhead (just my feeling), right? I remember doing the benchmarks and a pair deselector-coalescer was showing like 1-2GBs throughput which I don't think the network will give us.
</blockquote></details>

Yeah, I agree - using both would be good. 
___
*[pkg/sql/exec/colrpc/outbox.go, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelemQ88TpPxS4AuHou:-LelemQ99m7CgLrussX3:b-heda45) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L109)):*
> ```Go
> 	// TODO(asubiotto): Hopefully the context will be annotated with the flowID
> 	// already, but the outbox should annotate this context with a streamID as
> 	// well. How do I do this?
> ```

I think you use `ctx = logtags.WithTags(ctx, logtags.SingleTagBuffer("streamId", streamId))` or something like that.
___
*[pkg/sql/exec/colrpc/outbox.go, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelfMizBzLjmn2AiZ11:-LelfMizBzLjmn2AiZ12:bd1lf0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L129)):*
> ```Go
> 	stream, err := client.FlowStream(ctx)
> 	if err != nil {
> 		log.Errorf(ctx, "Outbox FlowStream error: %s", err)
> ```

Should this really be an error-level log? I would also recommend improving the log message so that it's comprehensible to someone seeing an error in the logs. Maybe a warning level, and something like "Outbox connection failure: remote query will fail" or something. Do we have a query id available? It would be nice to log that too.

And ditto for the other messages in here. I want to make sure that the logs are actionable to administrators.
___
*[pkg/sql/exec/colrpc/outbox.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelgx6UDBGNFpgaoh5l:-Lelgx6UDBGNFpgaoh5m:b-haq1ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L202)):*
> ```Go
> 		o.scratch.msg.Data.RawBytes = o.scratch.buf.Bytes()
> 
> 		if err := stream.Send(o.scratch.msg); err != nil {
> ```

I don't understand the lifetimes of data here. When `stream.Send` returns, are we allowed to modify the buffers in `RawBytes`? I would document this explicitly - I could see this becoming an issue. I think we're safe right now because grpc always(?) copies all of the data in the input messages, but what if that changes?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox.go, line 188 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Leldd333S-zqHhd_0nq:-LemRDh7EzUR2ycTuRHk:bhw89r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L188)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Does the panic catching machinery that Yahor added need to be extended to understand panics from `exec/colrpc`?
</blockquote></details>

I think there is no need for any changes - in `exec/error.go` we're matching based on the prefix, so `pkg/sql/exec/colrpc` will match our desired prefix of `pkg/sql/exec`.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/exec/random_testutils.go, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCqbVo0h52uVT_3l0V:-LemDl-y8L-1kSVnRCTE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/random_testutils.go#L184)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: missing closing parenthesis.
</blockquote></details>

Done.
___
*[pkg/sql/exec/random_testutils.go, line 288 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCrbFt-YYRLxcQlnT7:-LemOjdP71KgGYCyIMKD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/random_testutils.go#L288)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

~I think using `randomBatchWithSel` will always set the length of the batch to the length of the generated selection vector, so if `o.selection == false`, that will shorten the batch. Is this the desired behavior? I think we should use `randomBatch` in that case.~ I see, actually `selProbability` will be 0 in that case and the length won't be updated. Please add a note explaining this logic.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/colrpc_test.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCtRH_Dfs6zuhz_19X:-LemOuBA4xhBt3sZWu-h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/colrpc_test.go#L71)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: it's slightly odd that only this method has a comment.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox.go, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelar3q52wynGClrCvE:-LemPYME-Q34r6pchhOF:b-nzag3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L103)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This will be called by the main setup goroutine, right? It would be useful to add that information to the comment.
</blockquote></details>

No, it will be called by the first call to `Next` (or `DrainMeta` in the following PR) since it is blocking.
___
*[pkg/sql/exec/colrpc/inbox.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelcfR78BYtm36QhPuC:-LemQjFs6MRYZxNilIEV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L140)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is the normal path, right? This will see `nil` when the channel is closed. I would add a comment here about that.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelcBAp79ZzynuKeqsv:-LemRsPS8yj6P_dcbitK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L144)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would enhance these error messages to include the plain english explanation that you have in the comment, to make it easier to understand what's going on when we see these in the logs.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox.go, line 169 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelct7H-DGT_x2b3XAt:-LemRvxX2UeqmiYdDpmU:bg6v483) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L169)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it would be easier to remove all the calls to `close(i.errCh)` in the body, and put one in the `defer` outside of the `recover` block.
</blockquote></details>

But we don't want to close `i.errCh` when we return a batch normally. In the following `DrainMeta` PR, this becomes cleaner since we only need to close on panic in `Next` and unconditionally in `DrainMeta`.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCy6Jc7jRBv98-bOde:-LemSOT20NlggfL8A8Ai:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox_test.go#L61)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: it might be worth checking that a zero length batch is returned.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeD16cS9OIOxQDazS3Y:-LemSoOu0CIVz9sa9Y8a:b-64y3oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox_test.go#L133)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: a comment what this should panic would be useful.
</blockquote></details>

Added a comment, but don't want to be too specific.
___
*[pkg/sql/exec/colrpc/outbox.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelds8iCeGVTgn76Hf7:-LemStsf2uviNhbcIPdy:b-tjz97q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it's fine to leave error returns in constructors - we do it everywhere else too.
</blockquote></details>

Yeah, but it seems like an unnecessary case to return an error for.
___
*[pkg/sql/exec/colrpc/outbox.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCzYo04e5qC5aGcnqC:-LemT7NY5oWUcvqtQC6j:b9ymuiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L65)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah, I agree - using both would be good. 
</blockquote></details>

I'm actually not sure I agree. We wouldn't want to have a downstream reader wait for us to produce a whole batch of values. This is why we currently have a flush timer in the distsql outbox. We wait for 16 values to be buffered up or a small amount of time to elapse before writing to the stream.
___
*[pkg/sql/exec/colrpc/outbox.go, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelemQ88TpPxS4AuHou:-Lemudq983keNyazbJph:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L109)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think you use `ctx = logtags.WithTags(ctx, logtags.SingleTagBuffer("streamId", streamId))` or something like that.
</blockquote></details>

Done. Thanks!
___
*[pkg/sql/exec/colrpc/outbox.go, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelfMizBzLjmn2AiZ11:-Lem_y926P3o5tattD5j:b-b8m18j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L129)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should this really be an error-level log? I would also recommend improving the log message so that it's comprehensible to someone seeing an error in the logs. Maybe a warning level, and something like "Outbox connection failure: remote query will fail" or something. Do we have a query id available? It would be nice to log that too.

And ditto for the other messages in here. I want to make sure that the logs are actionable to administrators.
</blockquote></details>

It's an error that will fail the query, which makes it an error-level log to me, but I might not understand the severity implied by the error-level log. Switched to warning. It would be great to have a query ID available but not sure where to get it (context should be annotated with it though, but I doubt that's the case right now). I changed the log messages but do we want to put the expected effect in it? I'd like to keep the method names in the message to be able to identify where the log message came from. Let me know what you think of the log messages, I'd be happy to change them further for clarity.
___
*[pkg/sql/exec/colrpc/outbox.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelgx6UDBGNFpgaoh5l:-LemhWYWByjavUfHgTNQ:b-u584ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L202)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't understand the lifetimes of data here. When `stream.Send` returns, are we allowed to modify the buffers in `RawBytes`? I would document this explicitly - I could see this becoming an issue. I think we're safe right now because grpc always(?) copies all of the data in the input messages, but what if that changes?
</blockquote></details>

Yeah, `Send` is guaranteed to only return when the data is "sent" (written to the control buffer, not actually sent) or some error occurs. The first thing GRPC does is serialize the message (which does the copy) before even attempting a write, so the caller retains ownership. If that changes, our tests will fail (specifically `TestOutboxInbox`).

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox.go, line 169 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-Lelct7H-DGT_x2b3XAt:-LetTKYC1654o71hb0Zn:bofwq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/inbox.go#L169)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

But we don't want to close `i.errCh` when we return a batch normally. In the following `DrainMeta` PR, this becomes cleaner since we only need to close on panic in `Next` and unconditionally in `DrainMeta`.
</blockquote></details>

Ah, I see. OK.
___
*[pkg/sql/exec/colrpc/outbox.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCzYo04e5qC5aGcnqC:-LetTbtM1jGZ3F55oUYO:bag8dte) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L65)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm actually not sure I agree. We wouldn't want to have a downstream reader wait for us to produce a whole batch of values. This is why we currently have a flush timer in the distsql outbox. We wait for 16 values to be buffered up or a small amount of time to elapse before writing to the stream.
</blockquote></details>

Hmm, good point. I forgot about that. And waiting too much for inputs might lead to deadlocks in some cases, right?
___
*[pkg/sql/exec/colrpc/outbox.go, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LelfMizBzLjmn2AiZ11:-LetToPZ9PkLep-ChNb9:b-md6fzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L129)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's an error that will fail the query, which makes it an error-level log to me, but I might not understand the severity implied by the error-level log. Switched to warning. It would be great to have a query ID available but not sure where to get it (context should be annotated with it though, but I doubt that's the case right now). I changed the log messages but do we want to put the expected effect in it? I'd like to keep the method names in the message to be able to identify where the log message came from. Let me know what you think of the log messages, I'd be happy to change them further for clarity.
</blockquote></details>

Thanks for changing to warning - I think what you did here is good.

**Review by asubiotto — COMMENTED** [review]
bors r=jordanlewis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-:-LevbBDKEr44FuvW1t9Y:bkhbmek)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colrpc/outbox.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCzYo04e5qC5aGcnqC:-LevYaZK9Yka0STYptiu:be8oumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L65)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, good point. I forgot about that. And waiting too much for inputs might lead to deadlocks in some cases, right?
</blockquote></details>

I'm not sure about deadlocks, what cases are you thinking about?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37296)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colrpc/outbox.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37296#-LeCzYo04e5qC5aGcnqC:-Lew-Fm7EWv1iOMDxHOl:bcmlyh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0e43efc4bda048d54fd9ed9b05f7dfc3a09da8/pkg/sql/exec/colrpc/outbox.go#L65)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure about deadlocks, what cases are you thinking about?
</blockquote></details>

I think that you could get a deadlock if you were waiting to assemble full batches before writing to an outbox, if you also didn't have a flush timer, because of the problem with hash joins with full outputs... I could try to construct a more complete example, but I'm pretty sure there 's a potential issue there, right?

**Comment by asubiotto** [comment]
If I'm understanding correctly, I think that in that case (a hash joiner blocked on that side of the input), given that the outbox runs in its own goroutine, will at some point read a zero-length batch independently of the state of its downstream hash joiner which will unblock the flow. I think deadlocking is not an issue with this, but higher execution times is.

**Pull request merged**
