### PR TITLE
sql: improve how tracing of processors is done on the gateway node

### PR DESCRIPTION
**Pull request by yuzefovich**
**tracing: make it possible for EventListeners to "consume" the event**

This commit extends `Notify` signature with a return argument in order
to introduce the notion of "event consumption". Once a listener
"consumes" the event, no other listener for the span nor the ancestor
spans will be notified about the event. This behavior is needed by the
follow-up commit which changes how DistSQL processors examine their
traces to pick out their "own" events from the events of their inputs.

This also resulted in notifications of the span's listeners be done
before the ancestor.

Release note: None

**execinfra: plumb FlowCtx and processorID into ProcessorSpan method**

This commit is mostly a mechanical change to plumb `FlowCtx` object as
well as the processor ID into `ProcessorSpan` method. The main goal of
this work is to be able to know whether the method is called on the
gateway node or not (this will be used by the follow-up commit), but
this change also results in unification of how FlowID and ProcessoID
tags are set on the tracing span.

Release note: None

**execstats: collect some stats via EventListeners**

This commit changes how contention time, scan stats, and consumed RU
information are accumulated by the processors. Previously, we would
analyze the trace recording of the processor to pick out all applicable
events from the trace and aggregate across all of them. This worked well
because currently we always create "detached" spans for all processors
(in other words, a contention event attached to the span of one
processor will not be seen by the parent processor).

However, the following commit will change that for processors on the
gateway. Namely, all processors on the gateway will no longer use the
detached option. As a result, we need to have a different way to
distinguish between events seen by the processor itself versus events
seen by the "child" processor. This commit introduces that way via the
EventListeners. In particular, it defines three types of listeners (for
all kinds of structured events we're interested in), which are then used
by all processors.

Release note: None

**sql: don't propagate spans from local processors as metadata**

This commit changes how we create tracing spans for components of the
flow on the gateway. Previously, we would always create them with the
detached option, and, as a result, we needed to collect the traces and
propagate them as metadata to be imported by the DistSQLReceiver into
the span of the flow on the gateway. However, this is not necessary to
do so on the gateway - we can just let the regular tracing behavior to
happen there.

The main benefit of this change is that we now preserve the hierarchy of
the tracing spans in the gateway flows making them much more
understandable when viewing via the jaeger. Perhaps this is also a minor
performance improvement since the native trace collection is probably
faster than having to import the trace data via the metadata, as was
done previously.

An additional improvement can be made to create the spans with the
detached recording only for the root components of the remote flows.
This is left as a TODO for now.

Epic: None

Release note: None

**tracing: Notify EventListeners while holding the span's mutex**

This commit addresses an oversight that was introduced in https://github.com/cockroachdb/cockroach/commit/6a3c0f9207eda2d136046a367049160f0386cd8b
where we made the notifications of the EventListeners done without
holding the span's mutex. However, the contract of `WithEventListeners`
implies that the callbacks are not called any more after `Finish()`
returns, so that commit introduced a bug that is now fixed in this
commit.

The fix done in this commit is suboptimal though - it introduces an
exported method `SetLazyTagLocked` which is not great. The proper fix
would be to refactor `TracingAggregator` to avoid setting the lazy tag
dynamically, in the event listener callback, but that seems like
a non-trivial change, and I'd like to get this commit backported. To
avoid introducing more callsites of this `SetLazyTagLocked` method it is
marked as "deprecated" and https://github.com/cockroachdb/cockroach/issues/100438 tracks addressing this piece of the
tech debt.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First two commits in separate PRs and should be ignored here.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 4 of 4 files at r3, 40 of 41 files at r4, 15 of 15 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-:-NR0FTTkBwOShHICqnhe:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[`pkg/sql/plan_node_to_row_source.go` line 265 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR0AhEoD8RDx0fMFMiT:-NR0AHk813Wmr6oMRR56:b-limq0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/821f6c618f2b797f134f1f6030da65fca22f7c91/pkg/sql/plan_node_to_row_source.go#L265)):*
> ```Go
> 	// Propagate RUs from IO requests.
> 	// TODO(drewk): we should consider propagating other stats for planNode
> 	// operators.
> ```

Would addressing this TODO now be as simple as passing more listeners to `StartInternal` above?
___
*[`pkg/util/tracing/crdbspan.go` line 974 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR-FR6IBF8s4QUB_bFZ:-NR-FR6IBF8s4QUB_bF_:b-osto9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4107b6b1c3799b134eb41bd8d268a2ba6b724db6/pkg/util/tracing/crdbspan.go#L974)):*
> ```Go
> 		return
> 	}
> 	s.mu.Unlock()
> ```

Why do we unlock before notifying event listeners? Is this so that the listeners can call `SetLazyTag`? (Which appears to acquire the mutex?)
___
*[`pkg/util/tracing/crdbspan.go` line 986 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR-FKb9CmvNksje4Z5F:-NR-EH8D0b4Nm2iBMKgM:b86t7jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4107b6b1c3799b134eb41bd8d268a2ba6b724db6/pkg/util/tracing/crdbspan.go#L986)):*
> ```Go
> 	}
> 
> 	s.mu.Lock()
> ```

If we're re-acquiring the lock, do we need to check `finished` again?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98831)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @michae2)

___
*[`pkg/sql/plan_node_to_row_source.go` line 265 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR0AhEoD8RDx0fMFMiT:-NR0Q6nNAy3m7bGbTnjl:b-1x1jnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/821f6c618f2b797f134f1f6030da65fca22f7c91/pkg/sql/plan_node_to_row_source.go#L265)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Would addressing this TODO now be as simple as passing more listeners to `StartInternal` above?
</blockquote></details>

I don't think so - we currently have two other "types" of stats (contention time and scan stats), but neither seems applicable here. I think we'd first need to define some stats we're interested in, then we'd need to collect them (possibly via listeners like this PR does), and then expose them (either on distsql diagram or EXPLAIN ANALYZE plan output).
___
*[`pkg/util/tracing/crdbspan.go` line 974 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR-FR6IBF8s4QUB_bFZ:-NR0Qk2N94tnoWmj_QqL:b-caoc48) ([raw file](https://github.com/cockroachdb/cockroach/blob/4107b6b1c3799b134eb41bd8d268a2ba6b724db6/pkg/util/tracing/crdbspan.go#L974)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Why do we unlock before notifying event listeners? Is this so that the listeners can call `SetLazyTag`? (Which appears to acquire the mutex?)
</blockquote></details>

My guess is to reduce mutex contention. This behavior (of processing `s.eventListeners` without holding the mutex) was already present before my patch, so I preserved it.
___
*[`pkg/util/tracing/crdbspan.go` line 986 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR-FKb9CmvNksje4Z5F:-NR0U6gb68gp3Jw8o72Z:bj6aw4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4107b6b1c3799b134eb41bd8d268a2ba6b724db6/pkg/util/tracing/crdbspan.go#L986)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If we're re-acquiring the lock, do we need to check `finished` again?
</blockquote></details>

Hm, I'm not sure. This code was added in #81379, and primarily it was fixing the inconsistent locking: namely, the contract is that the parent's lock must be acquired first (when we have two spans with parent-child relationship), and before #81379 we'd incorrectly acquire the lock of the child (`s` in this function) and call `parent.notifyEventListeners` (which would acquire the parent's lock).

I read through the discussion on #81379, and it seems acceptable for both options: we could both check `finished` here again or not check it. I'm leaning towards the latter with the rationale that we have already notified listeners of `s` about this event, so we might as well propagate the notification to parent of `s` too, even if `s.Finish` was called while we were notifying listeners of `s`.

I plan to wait for @andreimatei to take a look too (I think he's out for a week), so let's see what he says about this.

**Comment by yuzefovich** [comment]
@andreimatei could you take a look at this one? I'm hoping to get this in for 23.1.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98831)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/execinfra/processorsbase.go` line 665 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NReHfZYBwKEO5cZ_7Yy:-NReHfZYBwKEO5cZ_7Yz:b-vxjpxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b73acb051b7d4e6c18c30c5ad0359b68189438d/pkg/sql/execinfra/processorsbase.go#L665)):*
> ```Go
> 			}
> 		}
> 		if !pb.FlowCtx.Gateway {
> ```

consider hinting here as to why the gw is special
___
*[`pkg/util/tracing/crdbspan.go` line 974 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR-FR6IBF8s4QUB_bFZ:-NReCPwX7iAbVWhx5C7Z:b-cixj8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4107b6b1c3799b134eb41bd8d268a2ba6b724db6/pkg/util/tracing/crdbspan.go#L974)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

My guess is to reduce mutex contention. This behavior (of processing `s.eventListeners` without holding the mutex) was already present before my patch, so I preserved it.
</blockquote></details>

I think it's pretty dubious that the listeners were called outside of the mutex. The comment on `WithEventListeners` implies that the callbacks are not called any more after `Finish()` returns, which I think are pretty sane semantics. This is how it seems to have been written initially, but then this subtlety was lost in #81379. In fact, for the one user of this API, a call to the event listener concurrent with a call to `Finish()` would trigger a bug, since a use-after-finish would be detected when the event handler calls `SetLazyTag`. 
So I think we should continue holding the mutex, and figure out a solution for the `TracingAggregator` to be able to continue calling `SetLazyTag` (*), or I think better yet by reworking the `TracingAggregator` to not call `SetLazyTag` from the event handler. Instead, I think it'd be better if `TracingAggregator` would attach one single lazy tag at construction time (instead of attaching them dynamically, one lazy tag per "event tag") , and the lazy tag would be in charge of iterating through the `b.mu.aggregatedEvents` map and rendering all the events.

(*) perhaps by introducing an exported `SetLazyTagLocked` that can only be used from these notifications, and passing the span to `Notify`
___
*[`pkg/util/tracing/crdbspan.go` line 986 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR-FKb9CmvNksje4Z5F:-NReGFEk1R2mat0yhbaV:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4107b6b1c3799b134eb41bd8d268a2ba6b724db6/pkg/util/tracing/crdbspan.go#L986)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I'm not sure. This code was added in #81379, and primarily it was fixing the inconsistent locking: namely, the contract is that the parent's lock must be acquired first (when we have two spans with parent-child relationship), and before #81379 we'd incorrectly acquire the lock of the child (`s` in this function) and call `parent.notifyEventListeners` (which would acquire the parent's lock).

I read through the discussion on #81379, and it seems acceptable for both options: we could both check `finished` here again or not check it. I'm leaning towards the latter with the rationale that we have already notified listeners of `s` about this event, so we might as well propagate the notification to parent of `s` too, even if `s.Finish` was called while we were notifying listeners of `s`.

I plan to wait for @andreimatei to take a look too (I think he's out for a week), so let's see what he says about this.
</blockquote></details>

See above.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98831)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @andreimatei, and @michae2)

___
*[`pkg/kv/bulk/bulkpb/ingestion_performance_stats.go` line 275 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NS2w2tj23WqGS8ky2sv:-NS2w2tj23WqGS8ky2sw:b-n3zn1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e27c65fb5a3810a5e2285cf07b45d95d401cca6/pkg/kv/bulk/bulkpb/ingestion_performance_stats.go#L275)):*
> ```Go
> func (t timing) SafeValue()     {}
> 
> var _ bulk.TracingAggregatorEvent = &IngestionPerformanceStats{}
> ```

This line is removed because it has a duplicate at the top of this file.
___
*[`pkg/sql/execinfra/processorsbase.go` line 665 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NReHfZYBwKEO5cZ_7Yy:-NS2vtoj93Kga73G8LTA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b73acb051b7d4e6c18c30c5ad0359b68189438d/pkg/sql/execinfra/processorsbase.go#L665)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider hinting here as to why the gw is special
</blockquote></details>

Done.
___
*[`pkg/util/tracing/crdbspan.go` line 974 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NR-FR6IBF8s4QUB_bFZ:-NS2ufk96B52lofBTWEM:b-wu3sgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4107b6b1c3799b134eb41bd8d268a2ba6b724db6/pkg/util/tracing/crdbspan.go#L974)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it's pretty dubious that the listeners were called outside of the mutex. The comment on `WithEventListeners` implies that the callbacks are not called any more after `Finish()` returns, which I think are pretty sane semantics. This is how it seems to have been written initially, but then this subtlety was lost in #81379. In fact, for the one user of this API, a call to the event listener concurrent with a call to `Finish()` would trigger a bug, since a use-after-finish would be detected when the event handler calls `SetLazyTag`. 
So I think we should continue holding the mutex, and figure out a solution for the `TracingAggregator` to be able to continue calling `SetLazyTag` (*), or I think better yet by reworking the `TracingAggregator` to not call `SetLazyTag` from the event handler. Instead, I think it'd be better if `TracingAggregator` would attach one single lazy tag at construction time (instead of attaching them dynamically, one lazy tag per "event tag") , and the lazy tag would be in charge of iterating through the `b.mu.aggregatedEvents` map and rendering all the events.

(*) perhaps by introducing an exported `SetLazyTagLocked` that can only be used from these notifications, and passing the span to `Notify`
</blockquote></details>

I added another commit that implements the former idea and opened #100438 to track the latter (it doesn't seem exactly trivial and I'm hoping to backport this PR to 23.1).

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-:-NS7uHjjCp0kC0jflK_J:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @michae2, and @yuzefovich)

___
*[`pkg/util/tracing/span.go` line 526 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NS7rAha3QeoJWOswyJy:-NS7rAha3QeoJWOswyJz:bnnonfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7bb0850055764663afd715a301ae77f5ffe3e2/pkg/util/tracing/span.go#L526)):*
> ```Go
> // is being held.
> //
> // Deprecated: this method should not be used because it's introduced only to go
> ```

nit: this is a rather liberal use of the word "deprecated". Perhaps you're using it in the Google style of deprecating something without providing an alternative :P
I would simply say that this method is to be used specifically from callbacks invoked by whomever, which hold the lock.
___
*[`pkg/util/tracing/span.go` line 556 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NS7rpwnBubXrly-O00X:-NS7rpwnBubXrly-O00Y:b5usltf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7bb0850055764663afd715a301ae77f5ffe3e2/pkg/util/tracing/span.go#L556)):*
> ```Go
> 	// Notify will not be called concurrently on the same span.
> 	//
> 	// NB: the span's mutex is locked.
> ```

this comment is a bit unclear. Modify the "Note that this methoud should not run ..." above to not talk about "Structured events", and instead mention that the caller holds the mutex.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-:-NS7y0XD06Uug9wg_Eb4:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @andreimatei, and @michae2)

___
*[`pkg/util/tracing/span.go` line 526 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NS7rAha3QeoJWOswyJy:-NS7wi4D6r-VCTtVIPut:boseg2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7bb0850055764663afd715a301ae77f5ffe3e2/pkg/util/tracing/span.go#L526)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: this is a rather liberal use of the word "deprecated". Perhaps you're using it in the Google style of deprecating something without providing an alternative :P
I would simply say that this method is to be used specifically from callbacks invoked by whomever, which hold the lock.
</blockquote></details>

I do prefer to keep it this way. In particular, a method marked as `Deprecated:` fails the linter, so nogo build will fail (that's why I had to make an exception in a couple of places for the linter), as a result, the likelihood of introducing another caller of this method is much lower (an engineer both sees the method as crossed-out in the IDE as well as a failed build without adding an exception). I believe it's ok to not provide an alternative here given that we're consciously taking on some tech debt that should be addressed at some point. Simply making the comment on the method say that it's only designed to be used in the callbacks seems like a much weaker protection from extending this tech debt.
___
*[`pkg/util/tracing/span.go` line 556 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/98831#-NS7rpwnBubXrly-O00X:-NS7y-2q4gaqRjXfNlQI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7bb0850055764663afd715a301ae77f5ffe3e2/pkg/util/tracing/span.go#L556)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment is a bit unclear. Modify the "Note that this methoud should not run ..." above to not talk about "Structured events", and instead mention that the caller holds the mutex.
</blockquote></details>

Done.

**Pull request merged**
