### PR TITLE
storage/engine: initial integration of encryption-at-rest

### PR DESCRIPTION
**Pull request by sumeerbhola**
functionality for Pebble.

Does not contain the stats, which will be a later PR.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
Is there an existing engine test that exercises encryption that will exercise this integration code or do I need to add some testing for it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-:-LsrpwXXCNNifxsgqhys:ba90h7o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

**Review by petermattis — COMMENTED** [review]
:lgtm: modulo the testing question

> Is there an existing engine test that exercises encryption that will exercise this integration code or do I need to add some testing for it?

I'm not aware of one. @mberhault?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-:-LsvnVC40sBrKboXc0E_:bp357vx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-Lsvnch31wYOwjGFQ5Y9:-Lsvnch31wYOwjGFQ5YA:b-lor863) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L194)):*
> ```Go
> // We cannot change any of the key/iv/nonce and reuse the same file since RocksDB does not
> // like non-empty WAL files with zero readable entries. There is a todo in env_encryption.cc
> // to change this RocksDB behavior.
> ```

We should file an issue about this. Recycling WAL files is a nice performance optimization as it speeds up disk syncs. I don't see a fundamental reason it is at odds with encryption of the files. Heck, encrypting the files actually makes it safer as there is no danger of reading data from the old version of the WAL.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-LsvnsN08z-Rz-fJ9SHT:-LsvnsN08z-Rz-fJ9SHU:bpe2tvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L208)):*
> ```Go
> //
> // See the comment at the top of this file for the structure of this environment.
> func CreateEncryptedEnv(
> ```

Nit: `s/Create/New/g`. The most frequent verb we use to describe construction of an object is `New`. We also use `Make` when the function returns a value and not a pointer.

You'll want to hook this up to `storage/engine.CreateEncryptedEnvFunc` via an `init` function:

```
func init() {
  engine.CreateEncryptedEnvFunc = CreateEncryptedEnv
}
```
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-LsvoKLWAA5goZpiAAP0:-LsvoKLWAA5goZpiAAP1:b-jso6ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L212)):*
> ```Go
> ) (vfs.FS, error){
> 	options := &baseccl.EncryptionOptions{}
> 	if err := protoutil.Unmarshal(optionBytes, options); err != nil {
> ```

Huh, I'm mildly surprised by this. We're passing `optionBytes` as the binary format for `EncryptionOptions`? That sure seems to match up with the C++ code, but I would have thought the text format would be better here. Maybe I'm not understanding where these are getting plumbed from.

Ah, we're using the encoded wire format to avoid referring to CCL code from non-CCL code. This makes sense now, though an explanatory comment might help a future reader of this code.
___
*[pkg/storage/engine/pebble.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-LsvpQeREnHpU2LVRYQT:-LsvpQeSDEf52ArG1846:b5scnua) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/storage/engine/pebble.go#L284)):*
> ```Go
> 			return nil, fmt.Errorf("file registry is needed to support encryption")
> 		}
> 		fs, err := CreateEncryptedEnvFunc(cfg.Opts.FS, fileRegistry, cfg.Dir, cfg.Opts.ReadOnly, cfg.ExtraOptions)
> ```

I think you need to check for whether `CreateEncryptedEnvFunc` is nil which can happen in a pure-OSS binary.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42156)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-Lsvnch31wYOwjGFQ5Y9:-LswsUkg5aGik6diKJAX:bpb5vew) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L194)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We should file an issue about this. Recycling WAL files is a nice performance optimization as it speeds up disk syncs. I don't see a fundamental reason it is at odds with encryption of the files. Heck, encrypting the files actually makes it safer as there is no danger of reading data from the old version of the WAL.
</blockquote></details>

@ajkr Is there an existing issue about https://www.facebook.com/groups/rocksdb.dev/permalink/2405909486174218/ ?
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-LsvnsN08z-Rz-fJ9SHT:-Lswqye53PfnLtKLVrXB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L208)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/Create/New/g`. The most frequent verb we use to describe construction of an object is `New`. We also use `Make` when the function returns a value and not a pointer.

You'll want to hook this up to `storage/engine.CreateEncryptedEnvFunc` via an `init` function:

```
func init() {
  engine.CreateEncryptedEnvFunc = CreateEncryptedEnv
}
```


</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-LsvoKLWAA5goZpiAAP0:-LswrUNe43G1_ztaD62M:btwxvkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L212)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Huh, I'm mildly surprised by this. We're passing `optionBytes` as the binary format for `EncryptionOptions`? That sure seems to match up with the C++ code, but I would have thought the text format would be better here. Maybe I'm not understanding where these are getting plumbed from.

Ah, we're using the encoded wire format to avoid referring to CCL code from non-CCL code. This makes sense now, though an explanatory comment might help a future reader of this code.
</blockquote></details>

I've added comments both here and in `pebble.go`.
___
*[pkg/storage/engine/pebble.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-LsvpQeREnHpU2LVRYQT:-Lswq2Gh33m6hjjttRPw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/storage/engine/pebble.go#L284)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you need to check for whether `CreateEncryptedEnvFunc` is nil which can happen in a pure-OSS binary.
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42156)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr and @itsbilal)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-Lsvnch31wYOwjGFQ5Y9:-LswtbSCB0SxT_6ulmY1:b-6u538h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L194)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

@ajkr Is there an existing issue about https://www.facebook.com/groups/rocksdb.dev/permalink/2405909486174218/ ?
</blockquote></details>

I was suggesting filing an issue against Pebble.

**Review by ajkr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42156)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-Lsvnch31wYOwjGFQ5Y9:-LswshRFDZbTt0FoSCRL:b-ic115d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L194)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I was suggesting filing an issue against Pebble.
</blockquote></details>

There is not. I think we should make a PR on our branch if we want that fixed as I suspect they'll be uninterested in revisiting crash-recovery assumptions at this point.

BTW, I don't know if this was explained anywhere already, but Sumeer pointed out to me the reason for not doing this in Pebble (i.e., allowing WAL file reuse on encrypted files) is to support downgrade compatibility with RocksDB, which cannot read them.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42156)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42156#-Lsvnch31wYOwjGFQ5Y9:-Lsya4Jr267yoI12do6-:b-5kgpuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4c94080963551dc5cdbd66549fd3a1d81019f3/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L194)):*
<details><summary><i>Previously, ajkr (Andrew Kryczka) wrote…</i></summary><blockquote>

There is not. I think we should make a PR on our branch if we want that fixed as I suspect they'll be uninterested in revisiting crash-recovery assumptions at this point.

BTW, I don't know if this was explained anywhere already, but Sumeer pointed out to me the reason for not doing this in Pebble (i.e., allowing WAL file reuse on encrypted files) is to support downgrade compatibility with RocksDB, which cannot read them.
</blockquote></details>

I added this in a comment here.

**Pull request merged**
