### PR TITLE
sql: reduce allocations in physicalplan.MakeExpression

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: reduce allocations in physicalplan.MakeExpression

The `physicalplan.MakeExpression` function allocates two visitor structs
on the heap. These structs cannot be stack allocated because they are
passed to the `tree.Walk` function as arguments that implement the
`tree.Visitor` interface. This prevents Go from allocating the structs
on the stack. These allocations can be a significant portion of all
allocations, especially when query plans have many columns flowing
through their operators. Two visitor structs will be allocated for every
expression rendered.

This commit reduces these allocations by introducing the
`physicalplan.ExprFactory` which reuses allocated visitors for each
expression created by the factory.

Release note: None

#### physicalplan: batch allocate indexed vars

`ExprFactory` now batches allocations of indexed vars, reducing the
total number of allocations. In addition, the
`ExprFactory.IndexedVarsHint` method has been added that allows callers
to provide an estimate for the number of indexed vars that will be
created by all calls to `ExprFactory.Make`. This can further reduce
allocations.

Informs #117546

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Some benchmark results:

```
name                                                 old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-10            51.5µs ± 1%    58.5µs ±21%     ~     (p=0.421 n=5+5)
FlowSetup/vectorize=true/distribute=false-10           49.8µs ± 4%    49.5µs ± 1%     ~     (p=0.841 n=5+5)
FlowSetup/vectorize=false/distribute=true-10           51.7µs ± 3%    49.8µs ± 1%   -3.72%  (p=0.016 n=5+5)
FlowSetup/vectorize=false/distribute=false-10          51.0µs ±13%    50.3µs ±13%     ~     (p=0.690 n=5+5)
FlowRenderSetup/vectorize=true/distribute=true-10      1.65ms ± 3%    1.57ms ± 1%   -4.74%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10     1.46ms ± 1%    1.40ms ± 1%   -4.25%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=false/distribute=true-10     1.50ms ± 1%    1.42ms ± 0%   -5.30%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=false/distribute=false-10    1.31ms ± 0%    1.26ms ± 0%   -3.23%  (p=0.008 n=5+5)

name                                                 old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-10            23.4kB ± 2%    23.5kB ± 3%     ~     (p=0.690 n=5+5)
FlowSetup/vectorize=true/distribute=false-10           21.9kB ± 2%    22.0kB ± 2%     ~     (p=0.381 n=5+5)
FlowSetup/vectorize=false/distribute=true-10           28.4kB ± 2%    28.6kB ± 1%     ~     (p=0.310 n=5+5)
FlowSetup/vectorize=false/distribute=false-10          27.6kB ± 4%    29.7kB ±30%     ~     (p=0.556 n=4+5)
FlowRenderSetup/vectorize=true/distribute=true-10      1.06MB ± 1%    1.03MB ± 1%   -2.49%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      975kB ± 2%     945kB ± 0%   -3.13%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=true-10      842kB ± 0%     816kB ± 0%   -3.01%  (p=0.029 n=4+4)
FlowRenderSetup/vectorize=false/distribute=false-10     765kB ± 0%     740kB ± 0%   -3.29%  (p=0.008 n=5+5)

name                                                 old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-10               238 ± 1%       239 ± 2%     ~     (p=0.730 n=5+5)
FlowSetup/vectorize=true/distribute=false-10              221 ± 2%       221 ± 2%     ~     (p=1.000 n=5+5)
FlowSetup/vectorize=false/distribute=true-10              239 ± 2%       240 ± 1%     ~     (p=1.000 n=5+5)
FlowSetup/vectorize=false/distribute=false-10             239 ±23%       237 ±22%     ~     (p=0.825 n=5+5)
FlowRenderSetup/vectorize=true/distribute=true-10       10.7k ± 3%      9.2k ± 3%  -14.06%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      7.36k ± 2%     5.82k ± 0%  -20.92%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=true-10      8.30k ± 0%     6.80k ± 0%  -18.09%  (p=0.029 n=4+4)
FlowRenderSetup/vectorize=false/distribute=false-10     5.04k ± 0%     3.54k ± 0%  -29.79%  (p=0.008 n=5+5)
```

**Review by yuzefovich — COMMENTED** [review]
Nice! Just one question from me.

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118788#-:-NpvNN_a-eOQ3m6VddL5:b-743h77)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/distsql_physical_planner.go` line 2314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118788#-NpvM6zG1eWxxIXEn2aE:-NpvM6zG1eWxxIXEn2aF:bz1hig0) ([raw file](https://github.com/cockroachdb/cockroach/blob/92336c751718cbe8093189385d192dde5017370d/pkg/sql/distsql_physical_planner.go#L2314)):*
> ```Go
> 		aggregations[i].Arguments = make([]execinfrapb.Expression, len(fholder.arguments))
> 		argumentsColumnTypes[i] = make([]*types.T, len(fholder.arguments))
> 		var ef physicalplan.ExprFactory
> ```

Could we store (i.e. embed) the `ExprFactory` in `PlanningCtx` and reuse it in different methods? There is no concurrency accessing the planning ctx, so I think it should work.

**Comment by mgartner** [comment]
The same benchmark of `master` vs the combination of this PR and #118684: 

```
name                                                 old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-10            51.5µs ± 1%    51.9µs ± 1%     ~     (p=0.222 n=5+5)
FlowSetup/vectorize=true/distribute=false-10           49.8µs ± 4%    49.0µs ± 1%     ~     (p=0.111 n=5+4)
FlowSetup/vectorize=false/distribute=true-10           51.7µs ± 3%    49.0µs ± 1%   -5.22%  (p=0.008 n=5+5)
FlowSetup/vectorize=false/distribute=false-10          51.0µs ±13%    49.8µs ±18%     ~     (p=0.421 n=5+5)
FlowRenderSetup/vectorize=true/distribute=true-10      1.65ms ± 3%    1.55ms ± 0%   -6.28%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10     1.46ms ± 1%    1.38ms ± 0%   -5.12%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=false/distribute=true-10     1.50ms ± 1%    1.37ms ± 0%   -8.59%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=false-10    1.31ms ± 0%    1.24ms ± 2%   -5.42%  (p=0.008 n=5+5)

name                                                 old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-10            23.4kB ± 2%    23.4kB ± 2%     ~     (p=0.841 n=5+5)
FlowSetup/vectorize=true/distribute=false-10           21.9kB ± 2%    22.0kB ± 2%     ~     (p=0.952 n=5+5)
FlowSetup/vectorize=false/distribute=true-10           28.4kB ± 2%    28.2kB ± 2%     ~     (p=0.421 n=5+5)
FlowSetup/vectorize=false/distribute=false-10          27.6kB ± 4%    29.6kB ±29%     ~     (p=0.730 n=4+5)
FlowRenderSetup/vectorize=true/distribute=true-10      1.06MB ± 1%    1.01MB ± 1%   -4.84%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      975kB ± 2%     920kB ± 0%   -5.64%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=true-10      842kB ± 0%     771kB ± 0%   -8.43%  (p=0.029 n=4+4)
FlowRenderSetup/vectorize=false/distribute=false-10     765kB ± 0%     695kB ± 0%   -9.25%  (p=0.016 n=5+4)

name                                                 old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-10               238 ± 1%       239 ± 1%     ~     (p=1.000 n=5+5)
FlowSetup/vectorize=true/distribute=false-10              221 ± 2%       222 ± 1%     ~     (p=0.667 n=5+5)
FlowSetup/vectorize=false/distribute=true-10              239 ± 2%       237 ± 1%     ~     (p=0.222 n=5+5)
FlowSetup/vectorize=false/distribute=false-10             239 ±23%       237 ±21%     ~     (p=0.365 n=5+5)
FlowRenderSetup/vectorize=true/distribute=true-10       10.7k ± 3%      9.2k ± 3%  -14.08%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      7.36k ± 2%     5.82k ± 0%  -20.92%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=true-10      8.30k ± 0%     5.55k ± 0%  -33.10%  (p=0.029 n=4+4)
FlowRenderSetup/vectorize=false/distribute=false-10     5.04k ± 0%     2.29k ± 0%  -54.55%  (p=0.016 n=5+4)
```

**Comment by mgartner** [comment]
*[`pkg/sql/distsql_physical_planner.go` line 2314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118788#-NpvM6zG1eWxxIXEn2aE:-NpvVGT2-vyCIViBPspq:b-vloqk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/92336c751718cbe8093189385d192dde5017370d/pkg/sql/distsql_physical_planner.go#L2314)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Could we store (i.e. embed) the `ExprFactory` in `PlanningCtx` and reuse it in different methods? There is no concurrency accessing the planning ctx, so I think it should work.
</blockquote></details>

Ya we could do that. I'd probably replace `ExprFactory` with some `ExprAlloc` struct that contains the visitors and a slice of indexed vars, and add a method to the `ExprContext` interface that returns an `ExprAlloc`. Then we can go back to using `MakeExpression` everywhere and all the visitors and indexed vars should be shared across all calls.

I might pursue that in a follow-up PR, but maybe not immediately. I'd rather chase bigger gains for now, if that's alright with you. Of course if I see more evidence that shows this would help significantly I'll prioritize it.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118788#-:-NpvZoCsDjedfFfNTXGZ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
