### PR TITLE
storage: remove legacy SST iterator

### PR DESCRIPTION
**Pull request by jbowens**
The legacy sstable iterator is no longer in use. Removing the legacy sstable iterator now also avoids updating it to accommodate the new Pebble internal iterator interface with lazy value fetching.

Epic: None
Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91231#-:-NFz1A5Y8LlsbRAQVn4q:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by jbowens** [comment]
TFTR!

bors r=nicktrav

**Comment by jbowens** [comment]
bors r=nicktrav

?

**Comment by jbowens** [comment]
bors retry

**Comment by jbowens** [comment]
bors retry

**Pull request merged**
