### PR TITLE
kubernetes: Add multiregion channel, add channel to daemonset configs

### PR DESCRIPTION
**Pull request by a-robinson**
Release note: None

Fixes https://github.com/cockroachdb/cockroach/issues/31144

### CODE REVIEW

**Comment by kannanlakshmi** [comment]
LGTM, thanks for getting it in so quickly! So in the reg data, if it calls out `kubernetes multi-region` its obviously multi-region, the default of all others Kubernetes clusters is single region, right?

**Comment by a-robinson** [comment]
`kubernetes-multiregion` will mean a multi-region cluster that was set up using our instructions. Any other cluster set up using our config files will show up as either `kubernetes-insecure` or `kubernetes-secure`, based on whether they use certificates.

Of course, any user can modify any of the provided files or deploy us in their own way such that no information (or garbage information) is sent.

**Comment by kannanlakshmi** [comment]
Makes sense, but hopefully no one is using the multi-region config files to set up a single region cluster. And you can't use any of our other files to set up multi-region anyway. Noted, that no information sent is always a possibility.

**Comment by a-robinson** [comment]
> And you can't use any of our other files to set up multi-region anyway.

Well, not easily at least :)

**Pull request merged**
