### PR TITLE
opt: support array subscripts

### PR DESCRIPTION
**Pull request by justinj**
Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30901)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ops/scalar.opt, line 526 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNuefi88x4-6thkZTR4:-LNuefi88x4-6thkZTR5:b-xedcdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/opt/ops/scalar.opt#L526)):*
> ```
> }
> 
> # ArraySubscript is a subscripting expression of the form <expr>[<index>].
> ```

ArraySubscript -> Indirection
___
*[pkg/sql/opt/ops/scalar.opt, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNuf03C2Gyyq_nWJ2oO:-LNuf03DAEv-YsVKnOVU:bi5cipp) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/opt/ops/scalar.opt#L528)):*
> ```
> # ArraySubscript is a subscripting expression of the form <expr>[<index>].
> # The grammar and Expr type implies support for multiple indirections and
> # slicing but they are not supported.
> ```

[nit] I think it would be clearer to say "Input must be of type Array and Index must be of type Int. Multiple indirections and array slicing are not supported." or something like that. 

But another question is whether we want to make the `Indirection` scalar expression general enough that it can support slicing and multi-dimensional arrays if/when we want to support them. (Does the heuristic planner support them?)
___
*[pkg/sql/sem/tree/expr.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNutd5p8DnHEPphEcIV:-LNutd5p8DnHEPphEcIW:bw710if) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/sem/tree/expr.go#L444)):*
> ```Go
> 	node := &IndirectionExpr{
> 		Expr:        expr,
> 		Indirection: ArraySubscripts{&ArraySubscript{Begin: index}},
> ```

Does the heuristic planner support multi-dimensional arrays and slicing? If so, maybe this function should be more general (so we don't need to change it later).

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30901)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ops/scalar.opt, line 526 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNuefi88x4-6thkZTR4:-LNvCBwjBYYo4QFc4auu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/opt/ops/scalar.opt#L526)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ArraySubscript -> Indirection
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNuf03C2Gyyq_nWJ2oO:-LNvAxynAcdVOOwHEhg0:b-8ghp0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/opt/ops/scalar.opt#L528)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I think it would be clearer to say "Input must be of type Array and Index must be of type Int. Multiple indirections and array slicing are not supported." or something like that. 

But another question is whether we want to make the `Indirection` scalar expression general enough that it can support slicing and multi-dimensional arrays if/when we want to support them. (Does the heuristic planner support them?)
</blockquote></details>

Done.

We definitely could but I don't know if we have any plans to add those features (not that they're that hard, we could probably add them without too much effort), and I don't think we're committing to anything hard by not supporting them here yet.
___
*[pkg/sql/sem/tree/expr.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNutd5p8DnHEPphEcIV:-LNvAeIv1Bf-M6rWUSj1:b-7amebw) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/sem/tree/expr.go#L444)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Does the heuristic planner support multi-dimensional arrays and slicing? If so, maybe this function should be more general (so we don't need to change it later).
</blockquote></details>

The heuristic planner doesn't support them:
```
root@127.0.0.1:63045/defaultdb> set optimizer = 'off';
SET

Time: 647µs

root@127.0.0.1:63045/defaultdb> select (array[1,2,3])[1][2];
pq: unimplemented: multidimensional ARRAY (ARRAY[1, 2, 3])[1][2]
HINT: See: https://github.com/cockroachdb/cockroach/issues/2115
root@127.0.0.1:63045/defaultdb> select (array[1,2,3])[1:2];
pq: unimplemented: ARRAY slicing in (ARRAY[1, 2, 3])[1:2]
HINT: See: https://github.com/cockroachdb/cockroach/issues/2115
```
this is sort of a strange failure mode - I'm not aware of another feature we both parse and have `Expr`s for but don't support.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-:-LNvFmX16lLe_OK44OfH:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/ops/scalar.opt, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNuf03C2Gyyq_nWJ2oO:-LNvFWyRCUPCoHhbzv-3:bsrdy1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/opt/ops/scalar.opt#L528)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Done.

We definitely could but I don't know if we have any plans to add those features (not that they're that hard, we could probably add them without too much effort), and I don't think we're committing to anything hard by not supporting them here yet.
</blockquote></details>

Sounds good. Since the heuristic planner doesn't support them I think we should just leave this as-is.
___
*[pkg/sql/sem/tree/expr.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30901#-LNutd5p8DnHEPphEcIV:-LNvFfddBApRQgTXocYW:b-m4w8mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb065412436bc86d4f3c936d417e73048c4a2a/pkg/sql/sem/tree/expr.go#L444)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

The heuristic planner doesn't support them:
```
root@127.0.0.1:63045/defaultdb> set optimizer = 'off';
SET

Time: 647µs

root@127.0.0.1:63045/defaultdb> select (array[1,2,3])[1][2];
pq: unimplemented: multidimensional ARRAY (ARRAY[1, 2, 3])[1][2]
HINT: See: https://github.com/cockroachdb/cockroach/issues/2115
root@127.0.0.1:63045/defaultdb> select (array[1,2,3])[1:2];
pq: unimplemented: ARRAY slicing in (ARRAY[1, 2, 3])[1:2]
HINT: See: https://github.com/cockroachdb/cockroach/issues/2115
```
this is sort of a strange failure mode - I'm not aware of another feature we both parse and have `Expr`s for but don't support.
</blockquote></details>

Interesting!

**Comment by justinj** [comment]
TFTR!

bors r+

**Review by RaduBerinde — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30901)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by andy-kimball** [comment]
:lgtm:

**Pull request merged**
