### PR TITLE
roachtest: misc clearrange improvements

### PR DESCRIPTION
**Pull request by tbg**
Touches #34897.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Friendly ping.

**Review by petermattis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35050#-:-LZA9jZb-uLvPyF-vG3R:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/cmd/roachtest/clearrange.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35050#-LZAA0GKESkaXwjd8bVl:-LZAA0GKESkaXwjd8bVm:bkifmk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/503adcf1bfaac9b54080f7e0a55c4bb0b3a5d97c/pkg/cmd/roachtest/clearrange.go#L93)):*
> ```Go
> 	// declare itself ready before it's actually 100% ready. See:
> 	// https://github.com/cockroachdb/cockroach/issues/34897#issuecomment-465089057
> 	c.Run(ctx, c.Node(1), `COCKROACH_CONNECT_TIMEOUT=120 ./cockroach sql --insecure -e "DROP DATABASE IF EXISTS tinybank"`)
> ```

Ick. Ok, but ick.

**Comment by tbg** [comment]
TFTR!

bors r=petermattis

Ack on the ick.

**Comment by tbg** [comment]
Hrm, somehow the CLA won't turn green. I force-pushed and also clicked "recheck PRs" on cla-assistant.io. Any other ideas?

**Comment by tbg** [comment]
I even checked that the cla-assistant recheck request goes through (it does after ~49s) but the payload and response are mostly arrays of `null`, so maybe something is broken there?

**Comment by tbg** [comment]
Thanks @bdarnell for redelivering the webhook.

bors r=petermattis

**Pull request merged**
