### PR TITLE
cdc: Add ledger workload option to CDC roachtests

### PR DESCRIPTION
**Pull request by mrtracy**
Adds a new workload option to the CDC tests "ledger", which runs the
ledger workload instead of the TPCC workload.

To accomodate this, significantly refactor the CDC test (already
confined to a single file, not a far-reaching refactor). Notes on this:

+ Breaks down the large test function into several logical components -
a workload, a verifier, a manager for kafka - and encapsulate those in
simple objects with methods. Makes the top-level flow much easier to
read.
+ Move all verification parameters (e.g. maximum allowed latency) to be
explicitly defined for each test, rather than being inferred within the
test from other parameters such as warehouse count.

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
I wish I'd knows you were planning a refactor this big. This conflicts with some changes I have in local PRs, which I'll now have to resolve and keep rebased on top of this while you iterate. Perhaps worse is that this set of tests has been tricky to get right and now is a bad time to have to start debugging any issues introduced by a refactor. It's definitely more clear now, so I guess we merge it, but let's please stop refactoring this file for a while

Go ahead and run these to make sure they still pass and manually verify that everything looks sane

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-:-LP2KcEM1wJBdgDJ8VSb:b-nvr6nr)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cdc.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2IPmw2qojepiWMSPY:-LP2IPmw2qojepiWMSPZ:b5gnr93) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L33)):*
> ```Go
> 
> const (
> 	tpccWorkloadType workloadType = iota
> ```

no iota please. explicitly assigning the ints is basically always clearer

even better is to make workloadType a string and make these "tpcc" and "ledger" so they're useful when printed
___
*[pkg/cmd/roachtest/cdc.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2JVRf7LnM83XfL6lU:-LP2JVRf7LnM83XfL6lV:b-qui9c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L59)):*
> ```Go
> 	c.Start(ctx, t, crdbNodes, startArgs(`--args=--vmodule=changefeed=2,poller=2`))
> 
> 	// Additional arcane test setup, just to make things run more smoothly.
> ```

see below comment. this is arguably already lying
___
*[pkg/cmd/roachtest/cdc.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2J3T17674QuYoK53B:-LP2J3T17674QuYoK53C:by84p6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L70)):*
> ```Go
> 	}()
> 
> 	// Install and start Kafka.
> ```

In general, I find these sorts of narrative comments more harmful than helpful. This isn't adding anything to the below, but at best it has to be maintained in future changes and worse it could rot and become a lie
___
*[pkg/cmd/roachtest/cdc.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2Gj6nB5EE5hc6Z-VD:-LP2Gj6nB5EE5hc6Z-VE:b-iz60s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L215)):*
> ```Go
> 		Name:       "cdc/ledger/nodes=3/init=false",
> 		MinVersion: "2.1.0",
> 		Nodes:      nodes(4, cpu(16)),
> ```

should be cpu(20) right?
___
*[pkg/cmd/roachtest/cdc.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2GtoYEasKj6naty84:-LP2GtoYEasKj6naty85:b8jhzzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L221)):*
> ```Go
> 				workloadType:             ledgerWorkloadType,
> 				workloadDuration:         "30m",
> 				initialScan:              true,
> ```

this disagrees with init=false in the name
___
*[pkg/cmd/roachtest/cdc.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2HGYJ0zS9J11X6_o6:-LP2HGYK7z9ruAqh5Amg:b1ylp93) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L318)):*
> ```Go
> func (lw *ledgerWorkload) run(ctx context.Context, c *cluster, workloadDuration string) {
> 	c.Run(ctx, lw.workloadNodes, fmt.Sprintf(
> 		`./workload run ledger --mix=balance=50,withdrawal=25,deposit=12,reversal=0 {pgurl%s} --workloadDuration=%s`,
> ```

#28642 says withdraw=50,deposit=50, right? it also says 575 txn/s, which we might have to add support for in the workload, if it doesn't support it already

**Review by mrtracy — COMMENTED** [review]
I have already manually verified that the roachtests are still working correctly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-:-LP2f4kyEvIsmRHPBo2k:b-1kpvqf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cdc.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2IPmw2qojepiWMSPY:-LP2dn2cCjkpj-nhC0s4:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L33)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

no iota please. explicitly assigning the ints is basically always clearer

even better is to make workloadType a string and make these "tpcc" and "ledger" so they're useful when printed
</blockquote></details>

done.
___
*[pkg/cmd/roachtest/cdc.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2J3T17674QuYoK53B:-LP2dxP_4U1QBMKxEsDs:b-pz7eh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L70)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

In general, I find these sorts of narrative comments more harmful than helpful. This isn't adding anything to the below, but at best it has to be maintained in future changes and worse it could rot and become a lie
</blockquote></details>

I will remove them.  I will say, for me they serve to break up the code into clear steps.  Without them, visually the code seems to run together and be harder to parse.

I do understand the sentiment about these comments getting out of date.
___
*[pkg/cmd/roachtest/cdc.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2Gj6nB5EE5hc6Z-VD:-LP2eYu0BT4gotR2pZEA:bvn9dqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L215)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

should be cpu(20) right?
</blockquote></details>

Apparently this is not available from GCE?  I got an error, we're going to have to figure out how to get this to the right number.
___
*[pkg/cmd/roachtest/cdc.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2GtoYEasKj6naty84:-LP2eiWh-3aQJQuLcqIP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L221)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this disagrees with init=false in the name
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/cdc.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2HGYJ0zS9J11X6_o6:-LP2ejZzAO1mMqfuLmBB:b-mthv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L318)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

#28642 says withdraw=50,deposit=50, right? it also says 575 txn/s, which we might have to add support for in the workload, if it doesn't support it already
</blockquote></details>

is balance supposed to be 0?

As for 575txn/s, I need to add a new verification step (and possibly workload options) for that to make sure the test is actually hitting that target. I held off on that because this was already a big change.

**Review by danhhz — COMMENTED** [review]
:lgtm:

> I have already manually verified that the roachtests are still working correctly.

Gotcha. The PR description is out of date then.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-:-LP2iHp69awcCwS1b68v:b-54kpsq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cdc.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2J3T17674QuYoK53B:-LP2jNBn0VTahKyfyXVy:b-j5z8xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L70)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

I will remove them.  I will say, for me they serve to break up the code into clear steps.  Without them, visually the code seems to run together and be harder to parse.

I do understand the sentiment about these comments getting out of date.
</blockquote></details>

Yeah, it's always a balance. You've added some of these in other places in recent PRs and I thought they were a net win. These ones I felt went a bit the other way
___
*[pkg/cmd/roachtest/cdc.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2Gj6nB5EE5hc6Z-VD:-LP2iTsd7aKWfy38BWRD:b-8th12h) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L215)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Apparently this is not available from GCE?  I got an error, we're going to have to figure out how to get this to the right number.
</blockquote></details>

ah, makes sense. leave a TODO please
___
*[pkg/cmd/roachtest/cdc.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2HGYJ0zS9J11X6_o6:-LP2ib155CFq3n3fWGYV:b-xc9exi) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L318)):*
> is balance supposed to be 0?

I forwarded you the email that I got those numbers from. Please do double check what I came up with.

> As for 575txn/s, I need to add a new verification step (and possibly workload options) for that to make sure the test is actually hitting that target. I held off on that because this was already a big change.

leave a TODO please

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31537)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cdc.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2Gj6nB5EE5hc6Z-VD:-LP3BcsPDSFK0zz_PqqQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L215)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

ah, makes sense. leave a TODO please
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/cdc.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31537#-LP2HGYJ0zS9J11X6_o6:-LP3Be9JBEcU-xo1F4QH:bu3kt9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/23416e90fdc7cb29988e7289a0d8cb81de6ebd8b/pkg/cmd/roachtest/cdc.go#L318)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

> is balance supposed to be 0?

I forwarded you the email that I got those numbers from. Please do double check what I came up with.

> As for 575txn/s, I need to add a new verification step (and possibly workload options) for that to make sure the test is actually hitting that target. I held off on that because this was already a big change.

leave a TODO please
</blockquote></details>

Done, and I think 0/50/50 is fine for now. We can add additional tests with different parameters if necessary.

**Comment by mrtracy** [comment]
bors r=danhhz

**Comment by mrtracy** [comment]
bors r=danhhz

**Pull request merged**
