### PR TITLE
singleflight: spruce up singleflight 

### LINKED ISSUE #90854: sql/catalog/lease: log lease acquisition in traces
**Describe the problem**

We currently don't have any evidence that lease acquisition is happening in the traces. The problem is that lease acquisition uses a singleflight. 

Jira issue: CRDB-20972

### PR DESCRIPTION
**Pull request by andreimatei**
This patch improves singleflight with a couple of features that were
done manually by most callers. The singleflight now optionally makes a flight's
context not respond to the cancelation of the caller's ctx, the flights
now run in stopper tasks, and stopper quiescence cancels the flights'
contexts. The callers were doing some of these things, but
inconsistently.

Also, the flights now get a tracing span and callers that join an
existing span get log messages demarcating the wait time. We've wanted
this multiple times when debugging, for example in the context of table
descriptor lease acquisitions and range descriptor resolving. To
accomodate for this, the contract of singleflight.DoChan() gets a bit
more complicated: the singleflight captures the tracing spans of all
non-leaders, and these callers have to call a new ReaderClosed() method
on the DoChan() result if they're not going to wait for the flight
result.

Fixes #90854

Release note: None
Epic: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFnQNU50bHBTOG-yZUI:-NFnQNU50bHBTOG-yZUJ:b-b72669) ([raw file](https://github.com/cockroachdb/cockroach/blob/446ffb8c4ba8deb3360512c0bcdcac3f974ba941/pkg/util/syncutil/singleflight/singleflight.go#L87)):*
> ```Go
> }
> 
> // Do executes and returns the results of the given function, making
> ```

One thing that's not clear is what will happen if `ctx` is canceled while the function is running, in particular, while it's running on behalf of another caller. I know you're not changing the behavior, but, by adding a context, I think you're making it more confusing.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFnQNU50bHBTOG-yZUI:-NFncaeL8y8vwmqJV8Cs:bcrxmus) ([raw file](https://github.com/cockroachdb/cockroach/blob/446ffb8c4ba8deb3360512c0bcdcac3f974ba941/pkg/util/syncutil/singleflight/singleflight.go#L87)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

One thing that's not clear is what will happen if `ctx` is canceled while the function is running, in particular, while it's running on behalf of another caller. I know you're not changing the behavior, but, by adding a context, I think you're making it more confusing. 
</blockquote></details>

See now; I've added a note about it.
I would argue that I'm hardly making things worse - virtually every closure passed to these functions was already capturing a ctx. And even if I am making it marginally worse, I think it's worth it for the new logging.
Btw, this function has a single caller; everybody else uses `DoChan`. If you want, we can delete it. We could also have it take `DoOpts`, if you think.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 22 of 23 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 712 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo8srEEECP8cmVz9wJ:-NFo8srEEECP8cmVz9wK:b-ssx1oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/kv/kvserver/replica_rangefeed.go#L712)):*
> ```Go
> 				select {
> 				case m.RangeFeedSlowClosedTimestampNudgeSem <- struct{}{}:
> 				case <-r.store.stopper.ShouldQuiesce():
> ```

Should we use the `ctx` again?
___
*[`pkg/kv/kvserver/protectedts/ptcache/cache.go` line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo9I4SAtKQucI-WZxX:-NFo9I4SAtKQucI-WZxY:bkhuie4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/kv/kvserver/protectedts/ptcache/cache.go#L215)):*
> ```Go
> 			lastReset = timeutil.Now()
> 		case <-c.stopper.ShouldQuiesce():
> 			if doneCh != nil {
> ```

Should we defer this in a closure up above where we declare `var doneCh singleflight.Future`?
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo58hp68xeMYm0v-jp:-NFo58hq8Kxw1HKZ95En:b-qlucsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L49)):*
> ```Go
> }
> 
> type waiter struct {
> ```

Is this struct used? Was it replaced by `futureImpl`?
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo6OSM9-O3aH8X1wGh:-NFo6OSM9-O3aH8X1wGi:bg4hy01) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L143)):*
> ```Go
> // Future represents the result of the DoChan() call.
> type Future interface {
> 	// ReaderClose indicates that the reader is no longer waiting on this Future.
> ```

nit: Why `ReaderClose` instead of just `Close`? Was `Close` ambiguous from the external interface of this package? Would `Abandon` be?
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo757p-cofevIMl5BU:-NFo757p-cofevIMl5BV:bcvu3kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L196)):*
> ```Go
> 	f.mu.Lock()
> 	if f.mu.sp != nil {
> 		f.mu.sp.Recordf("finished waiting on singleflight %s:%s. err: %v", groupName, key, r.Err)
> ```

`Span.Recordf` is different than the call to `log.Eventf` above. Will that be observable? Will we include the filename and line number in this event?
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo7TwS5btqD2ngmfVA:-NFo7TwS5btqD2ngmfVB:b-imwiaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L247)):*
> ```Go
> 		return waiter, false
> 	}
> 	waiter := newFutureImpl(nil /* sp - the leader does not keep track of the span because it doesn't need to log*/)
> ```

nit: `s/log*/log */`
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo7nqb9Moe9E5nthm5:-NFo7nqb9Moe9E5nthm6:bpa4l4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L275)):*
> ```Go
> 		// Copy the log tags and the span.
> 		ctx = logtags.AddTags(context.Background(), logtags.FromContext(ctx))
> 		ctx = tracing.ContextWithSpan(ctx, sp)
> ```

What is the effect of this? Do the trace events make it to the caller's span? What if the caller's context is canceled but the cancelation is not inherited?
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 283 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo866f0yGBzf-acniQ:-NFo866f0yGBzf-acniR:b-hv2730) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L283)):*
> ```Go
> 	}
> 
> 	if opts.Stop != nil {
> ```

nit: two `if opts.Stop != nil` branches in a row. Collapse them?
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo8CZC-5QWFgI2fm-d:-NFo8CZC-5QWFgI2fm-e:b-s8n20m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L298)):*
> ```Go
> 	res := Result{c.val, c.err, c.dups > 0}
> 	for _, waiter := range c.waiters {
> 		waiter.writerClose(res, g.opName, key)
> ```

Did you consider an approach that propagated the tracing events from the leader's span to the followers' so that everyone who waited on the singleflight ended up with it in their trace? Does that run into complications with singleflight operations that started before one of its followers?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 712 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo8srEEECP8cmVz9wJ:-NFo_2kuDwXI-abPUVlP:b-5g9o7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/kv/kvserver/replica_rangefeed.go#L712)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we use the `ctx` again?
</blockquote></details>

yes, done
___
*[`pkg/kv/kvserver/protectedts/ptcache/cache.go` line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo9I4SAtKQucI-WZxX:-NFoaEF23EowUkSLahgq:b-xp3va9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/kv/kvserver/protectedts/ptcache/cache.go#L215)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we defer this in a closure up above where we declare `var doneCh singleflight.Future`?
</blockquote></details>

done; please see now
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo58hp68xeMYm0v-jp:-NFoaNxQ9svpVvpwlaAI:b-1156mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this struct used? Was it replaced by `futureImpl`?
</blockquote></details>

yes, removed, thanks
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo6OSM9-O3aH8X1wGh:-NFoabh3-i1DirDl3_Mb:b-lc22ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L143)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Why `ReaderClose` instead of just `Close`? Was `Close` ambiguous from the external interface of this package? Would `Abandon` be?
</blockquote></details>

This all changed.
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo757p-cofevIMl5BU:-NFobJSi-fDW-E1fNUK3:bayi46w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L196)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`Span.Recordf` is different than the call to `log.Eventf` above. Will that be observable? Will we include the filename and line number in this event?
</blockquote></details>

this all changed
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo7TwS5btqD2ngmfVA:-NFodVjGAM65LP4xooLa:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L247)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `s/log*/log */`
</blockquote></details>

done
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo7nqb9Moe9E5nthm5:-NFoeJLmCMWi_kYKX533:b-i2nein) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L275)):*
> Do the trace events make it to the caller's span?

The events make it to a child span opened at the beginning of this function.

> What if the caller's context is canceled but the cancelation is not inherited?

That's why we're creating a child span - to allow it to outlive the caller's span. Added a note about it.
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 283 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo866f0yGBzf-acniQ:-NFofWMg1fMO8WnDedEe:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L283)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: two `if opts.Stop != nil` branches in a row. Collapse them?
</blockquote></details>

done
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NFo8CZC-5QWFgI2fm-d:-NFofXpGDMr7eGkjJo2O:b-ta4pgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf42b2267150c33a5a1c8f0d0bf63152bb0f5061/pkg/util/syncutil/singleflight/singleflight.go#L298)):*
> Did you consider...

I have. But I can consider it again.
I considered it again, and implemented.

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 27 of 27 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0W9SV1zYyV8uFMXRP:-NH0W9SV1zYyV8uFMXRQ:b-8hfwiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/syncutil/singleflight/singleflight.go#L58)):*
> ```Go
> 	/////////////////////////////////////////////////////////////////////////////
> 	// These fields are read and written with the singleflight mutex held before
> 	// the channel is closed, and are read but not written after the chanel is
> ```

`s/chanel/channel/`
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 208 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0WYW50c-aTJUdUzwr:-NH0WYW50c-aTJUdUzws:b-7ozvc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/syncutil/singleflight/singleflight.go#L208)):*
> ```Go
> // then the recording of the flight will be ingested into ctx even if this
> // caller was not the flight's leader.
> func (f Future) Result(ctx context.Context) Result {
> ```

Consider renaming to use a verb like `WaitForResult` or `ResolveResult`. I did not find it clear at the callers of this method that this was blocking and would return early on context cancellation.
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 227 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0Wj0cB-EfKCydaErU:-NH0Wj0cB-EfKCydaErV:b9obpbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/syncutil/singleflight/singleflight.go#L227)):*
> ```Go
> 				log.Eventf(ctx, "waiting for singleflight interrupted: %v", ctx.Err())
> 			}
> 			return Result{
> ```

Did you consider having `Result` return an error, separate from the result, in cases of context cancellation? Is it useful to callers to distinguish between cases where the signleflight call failed and cases where its own context was canceled and so it did not wait for the future to be resolved?
___
*[`pkg/util/tracing/span.go` line 370 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0VIDq3aqHeFRScXM4:-NH0VIDq3aqHeFRScXM5:bjunpqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/tracing/span.go#L370)):*
> ```Go
> 	}
> 	var rec Trace
> 	if recType != tracingpb.RecordingOff {
> ```

Why do we need this condition here but not above in `GetTraceRecording`?
___
*[`pkg/util/tracing/span_inner.go` line 96 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0VeNZEn7llx99g0qR:-NH0VeNZEn7llx99g0qS:bqx03tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/tracing/span_inner.go#L96)):*
> ```Go
> 	recType tracingpb.RecordingType, finishing bool,
> ) tracingpb.Recording {
> 	if s.isNoop() {
> ```

Should this call `GetTraceRecording()` to avoid redundancy?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0W9SV1zYyV8uFMXRP:-NHWqg0I5aWZvokMW-6I:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/syncutil/singleflight/singleflight.go#L58)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/chanel/channel/`
</blockquote></details>

done
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 208 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0WYW50c-aTJUdUzwr:-NHWr4LR0IfFtsCfQSVd:b3sdujl) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/syncutil/singleflight/singleflight.go#L208)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider renaming to use a verb like `WaitForResult` or `ResolveResult`. I did not find it clear at the callers of this method that this was blocking and would return early on context cancellation.
</blockquote></details>

renamed to `WaitForResult`
___
*[`pkg/util/syncutil/singleflight/singleflight.go` line 227 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0Wj0cB-EfKCydaErU:-NHWryWj4J8ZgfxCvuEh:bpya1fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/syncutil/singleflight/singleflight.go#L227)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you consider having `Result` return an error, separate from the result, in cases of context cancellation? Is it useful to callers to distinguish between cases where the signleflight call failed and cases where its own context was canceled and so it did not wait for the future to be resolved?
</blockquote></details>

That doesn't appear to be useful to any current callers. I can't very clearly imagine one needing to distinguish... But I can do it if you think so.
FWIW, the error message that a leader or follower gets on ctx cancelation says something like "interrupted during singleflight".
___
*[`pkg/util/tracing/span.go` line 370 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0VIDq3aqHeFRScXM4:-NHWrKVzAY0NCPE5vZ2g:b-gc1z4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/tracing/span.go#L370)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we need this condition here but not above in `GetTraceRecording`?
</blockquote></details>

it's not needed here either; removed
___
*[`pkg/util/tracing/span_inner.go` line 96 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NH0VeNZEn7llx99g0qR:-NHWruobDuuJPfm4EnFC:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/305a38c4e1af434e24c19f49b36d9e988549d8b5/pkg/util/tracing/span_inner.go#L96)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this call `GetTraceRecording()` to avoid redundancy?
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

@ajwerner do you want to give this another pass as well?

> Reviewed 2 of 3 files at r9, 28 of 28 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-:-NIDX-co9pMacoqB6LcQ:bd24t0o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[`pkg/sql/catalog/lease/lease.go` line 537 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NIDWRvJ3o9TOzPsG9LD:-NIDWRvJ3o9TOzPsG9LE:b6i8m5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e87d898cdca77c39dc74791b8200392c7e26f6/pkg/sql/catalog/lease/lease.go#L537)):*
> ```Go
> 	if result.Err != nil {
> 		return false, result.Err
> ```

nit: stray line
___
*[`pkg/util/tracing/crdbspan.go` line 251 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NIDWmFi-9MBj7Jys9lK:-NIDWmFi-9MBj7Jys9lL:b-54ozzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e87d898cdca77c39dc74791b8200392c7e26f6/pkg/util/tracing/crdbspan.go#L251)):*
> ```Go
> }
> 
> func (t Trace) String() string {
> ```

`Trace` looks huge. Are you sure we want this defined on a value receiver? We also then call `Flatten`, which has a ptr receiver.

**Review by ajwerner — APPROVED** [review]
:lgtm: thanks for doing it 

> Reviewed 1 of 3 files at r9, 2 of 28 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-:-NIEvznkECCwC9z2jI--:b-f9lv2r)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[`pkg/sql/catalog/lease/lease.go` line 537 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NIDWRvJ3o9TOzPsG9LD:-NIExd6a5BE3dzq1bExW:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e87d898cdca77c39dc74791b8200392c7e26f6/pkg/sql/catalog/lease/lease.go#L537)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: stray line
</blockquote></details>

removed
___
*[`pkg/util/tracing/crdbspan.go` line 251 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-NIDWmFi-9MBj7Jys9lK:-NIEzgIzA9frQtTx2wNO:bvth56w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e87d898cdca77c39dc74791b8200392c7e26f6/pkg/util/tracing/crdbspan.go#L251)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`Trace` looks huge. Are you sure we want this defined on a value receiver? We also then call `Flatten`, which has a ptr receiver.
</blockquote></details>

reverted

**Review by andreimatei — COMMENTED** [review]
@ajwerner check out the last commit, pls

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-:-NInV8-F-IyVsfWxm5ul:b-yfkxeo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @nvanbenschoten)

**Review by ajwerner — APPROVED** [review]
Last commit LGTM

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91038#-:-NJI0PA3-LoLsLh-Dmul:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @nvanbenschoten)

**Pull request merged**
