### PR TITLE
changefeedccl: add a cache to store the columns mappings

### PR DESCRIPTION
**Pull request by ajwerner**
We were building this per-row. That was expensive. We could do something
similar in other encodings, but this seemed easy and motivated.

Release justification: low risk, high benefit changes to existing functionality

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Screen Shot 2022-03-10 at 9 07 02 PM

**Review by stevendanna — APPROVED** [review]

**Review by miretskiy — APPROVED** [review]
Do you have "before" graphs by any chance?

**Comment by ajwerner** [comment]
> Do you have "before" graphs by any chance?

This is the before graph, I don't have an after graph

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by ajwerner** [comment]
unrelated flake

bors r+

**Pull request merged**
