### PR TITLE
colfetcher,execinfra: use soft limit for sizing batches

### PR DESCRIPTION
**Pull request by yuzefovich**
**colfetcher,execinfra: use soft limit for sizing batches**

Previously, we would use the limit hint for sizing batches only if the
estimated row count wasn't available. There is another scenario where
the hint should take precedence - when we have a soft limit: in such
scenario it is beneficial to size the original batch up to that soft
limit. The soft limit is present when it is smaller than the estimated
row count.

Additionally, this commit removes some ad-hoc logic when updating the
limit hint in the execution engine where we artificially increased the
hint so that in the row-by-row engine we blocked the reader in some
cases. That logic doesn't apply to the vectorized engine which is now
the default and only makes the hint imprecise, so it is now removed.

Release note: None

**sql,xform: remove no longer used scanNode.limitHint**

This function hasn't been used for a while now, so this commit removes
it. Accordingly, the 2.0 multiple is removed during the costing of scans
with soft limits.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice! Can you add a test that the limit hint is being used? A simple query like `SELECT * FROM t WHERE x = 1 LIMIT 1` where there is no index on `x` should do the trick.

Also, should we remove this factor from the coster now? Or is that factor of 2 still lurking somewhere? https://github.com/cockroachdb/cockroach/blob/6862953747ea160347013e9bda8dfd197ac0fa1b/pkg/sql/opt/xform/coster.go#L119-L121

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63101#-:-MXY7Kz86IYWI2oK45hN:b-xt6bbv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
I tried the following:
```
CREATE TABLE t (x INT);
INSERT INTO t SELECT generate_series(1, 10000);
ANALYZE t;
EXPLAIN ANALYZE SELECT * FROM t WHERE x = 1 LIMIT 1;
```
and got:
```
  • limit
  │ cluster nodes: n1
  │ actual row count: 1
  │ estimated row count: 1
  │ count: 1
  │
  └── • filter
      │ cluster nodes: n1
      │ actual row count: 1
      │ estimated row count: 1
      │ filter: x = 1
      │
      └── • scan
            cluster nodes: n1
            actual row count: 1,024
            KV rows read: 1,024
            KV bytes read: 64 KiB
            estimated row count: 10,000 (100% of the table; stats collected 1 second ago)
            table: t@primary
            spans: FULL SCAN
```
The limit hint happens to be 10000, so we read one a batch with `coldata.BatchSize` number of rows, and only then return. Is this expected?

> Also, should we remove this factor from the coster now? Or is that factor of 2 still lurking somewhere?

It is currently only used in the testing code, added another commit to remove it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63101#-:-MXYKpQMAY0pVkLlQqLu:bq2k69h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by rytaft — COMMENTED** [review]
> The limit hint happens to be 10000 ... Is this expected?

Yea, that's because the filter x = 1 is very selective, so we assume we'll have to scan a lot of data to find a row that matches. A better test might be to use a less selective filter like x < 5000. That should result in a much smaller limit hint. 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63101#-:-MXYNYHXAzx0DlMww-p9:bmr03c6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Thanks, makes sense, added a unit test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63101#-:-MXZCpel1NEX27Efpocw:bwqrj1g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: thanks!

> Reviewed 12 of 12 files at r5, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63101#-:-MXbjUum9n-Xlqmrysko:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Thoughts about backporting this? It seems to me like a nice optimization that could go in for 21.1.1.

**Comment by yuzefovich** [comment]
And it'd be nice to get the second commit backported too.

**Comment by rytaft** [comment]
Seems relatively low risk, so I'd be in favor of that.

**Pull request merged**
