### PR TITLE
sql: make CANCEL,RESUME,PAUSE,BACKUP,RESTORE,IMPORT valid for PREPARE

### LINKED ISSUE #15772: sql: BACKUP/RESTORE can take placeholders in pgwire but not in SQL
Currently, the BACKUP and RESTORE parser statements can take either names or placeholders for their targets.

However, neither BACKUP nor RESTORE are part of the `preparable_stmt` rule in `sql.y`, which prevents them from being used with a `PREPARE` statement in SQL.

This can be fixed by adding `backup_stmt` to the `preparable_stmt` rule and adding tests.

### PR DESCRIPTION
**Pull request by knz**
Fixes #15772.

Can't test BACKUP/RESTORE/IMPORT in pgwire_test because it's CCL code and not visible to the test framework. However since the CCL code already extensively uses placeholders, I consider the code path being exercised properly already.

### CODE REVIEW

**Comment by danhhz** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 621 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-Ks9VkUgGOGxmbLcwNM1:-Ks9VkUgGOGxmbLcwNM2:bl42d4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/718d9676835959071b0c0269c46d0115e632efaa/pkg/ccl/sqlccl/backup.go#L621)):*
> ```Go
> 	}
> 	fn := func(ctx context.Context, resultsCh chan<- parser.Datums) error {
> 		// We only check whether the feature is enabled during execute so
> ```

I don't think we should make this change, the ccl code shouldn't even PREPARE without a license.

Why do we need this for tests? Could we use something like testingPlanHook in sql/main_test.go?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805)*

**Comment by knz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/sqlccl/backup.go, line 621 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-Ks9VkUgGOGxmbLcwNM1:-Ks9zOb9Jgl3fWRKEP_y:bm4jq0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/718d9676835959071b0c0269c46d0115e632efaa/pkg/ccl/sqlccl/backup.go#L621)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I don't think we should make this change, the ccl code shouldn't even PREPARE without a license.

Why do we need this for tests? Could we use something like testingPlanHook in sql/main_test.go?
</blockquote></details>

All right, you can ignore this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805)*

**Comment by knz** [comment]
Since jordan is away perhaps Justin you could have a look?

**Comment by justinj** [comment]
Could we have a test that `BACKUP`/`RESTORE` don't prepare, as Dan says they shouldn't? I assume "doesn't prepare" is the default but if that's the behaviour we want I guess it should be encoded in the tests as well?

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/prepare, line 282 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-KsQlOLpohf0dWCZkSkm:-KsQlOLpohf0dWCZkSkn:b-um1i32) ([raw file](https://github.com/cockroachdb/cockroach/blob/c47d2a451b55cbc8eef7301ecefd6999e96b5f76/pkg/sql/logictest/testdata/logic_test/prepare#L282)):*
> ```
> ----
> 123
> ```

nit: extra line here

---

*[pkg/sql/parser/sql.y, line 1615 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-KsQkhvAzrKZpFCc7Evo:-KsQkhvAzrKZpFCc7Evp:b-7mw3fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c47d2a451b55cbc8eef7301ecefd6999e96b5f76/pkg/sql/parser/sql.y#L1615)):*
> ```Yacc
> | pause_stmt   // EXTEND WITH HELP: PAUSE JOB
> | restore_stmt // EXTEND WITH HELP: RESTORE
> | resume_stmt  // EXTEND WITH HELP: RESUME JOB
> ```

Remind me how it finds the help for this? And where its canonical source is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-:-KsQlK31lFJFOJsoM0rI:blen8sc)*

**Comment by knz** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 1615 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-KsQkhvAzrKZpFCc7Evo:-KsSZ8q6T6c3boyeGIJg:b-wyxmtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c47d2a451b55cbc8eef7301ecefd6999e96b5f76/pkg/sql/parser/sql.y#L1615)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Remind me how it finds the help for this? And where its canonical source is?
</blockquote></details>

in a comment just above the rules for the resume_stmt non-terminal
(also check out README.md in the same directory)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805)*

**Comment by knz** [comment]
I actually disagree strongly on the idea that license-requiring statements cannot be prepared. But this PR is not the topic for that and such a test would be out of scope anyway.

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/prepare, line 282 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-KsQlOLpohf0dWCZkSkm:-KsdNB59HdqKGtQNiIF0:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c47d2a451b55cbc8eef7301ecefd6999e96b5f76/pkg/sql/logictest/testdata/logic_test/prepare#L282)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: extra line here
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17805#-:-KsdMwKHY1r8XXL6OTGr:b-iterfn)*

**Comment by justinj** [comment]
OK, looks good to me then!

**Comment by knz** [comment]
TFYR!

**Pull request merged**
