### PR TITLE
geoindex: fix bad coverings for geometry by using the bounding box

### PR DESCRIPTION
**Pull request by sumeerbhola**
For the following query on the nyc dataset the false positives
produced by the inverted join decreased from 6061 rows to 3115 rows
(490 rows output by the inverted join were real positives) since
each of the census blocks with a bad covering matched all the
subway stations in the inverted join.
SELECT ... FROM nyc_census_blocks@geom_idx AS census
JOIN nyc_subway_stations AS subways
ON ST_Intersects(subways.geom, census.geom)

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
will read deeper in a second, but do you think we should do this for geography?

**Review by sumeerbhola — COMMENTED** [review]
We will probably need to (in a future PR), and the `covererInterface` should allow for that -- the implementation will need to be different since `covererWithBBoxFallback` is specific to `s2GeometryIndex`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-:-MBqCYWkDDkiRDqM3WN7:b-e4lxal)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

___
*[pkg/geo/geoindex/s2_geometry_index.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-MBqItqO-VTKTaaMayxq:-MBqItqO-VTKTaaMayxr:b-wolrji) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebeccf6de658681831069c524647366ce459f636/pkg/geo/geoindex/s2_geometry_index.go#L96)):*
> ```Go
> 	cu := simpleCovererImpl{rc: rc.s.rc}.covering(regions)
> 	if isBadCovering(cu) {
> 		bbox := geo.BoundingBoxFromGeomTGeometryType(rc.geom)
> ```

does this work for POINT EMPTY / POLYGON EMPTY?
___
*[pkg/geo/geoindex/s2_geometry_index.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-MBqImwZEDP3vZeHsANl:-MBqImwZEDP3vZeHsANm:bpr2snd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebeccf6de658681831069c524647366ce459f636/pkg/geo/geoindex/s2_geometry_index.go#L133)):*
> ```Go
> 	if gt != nil {
> 		r := s.s2RegionsFromPlanarGeomT(gt)
> 		keys = invertedIndexKeys(c, covererWithBBoxFallback{s: s, geom: gt}, r)
> ```

we can just use the BoundingBox from the g.BoundingBox() object here.
___
*[pkg/geo/geoindex/s2_geometry_index.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-MBqIxtj8DFnKclUA4Vy:-MBqIxtj8DFnKclUA4Vz:b-9unw6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebeccf6de658681831069c524647366ce459f636/pkg/geo/geoindex/s2_geometry_index.go#L135)):*
> ```Go
> 		keys = invertedIndexKeys(c, covererWithBBoxFallback{s: s, geom: gt}, r)
> 	}
> 	// keys = s.replaceBadWithBBoxKeys(c, g, keys)
> ```

delete?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/geo/geoindex/s2_geometry_index.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-MBqItqO-VTKTaaMayxq:-MBseTAWDc3VMOScgl0v:b-a73j9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebeccf6de658681831069c524647366ce459f636/pkg/geo/geoindex/s2_geometry_index.go#L96)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

does this work for POINT EMPTY / POLYGON EMPTY?
</blockquote></details>

Good question -- this was broken prior to this PR, so I've fixed it.
The `isBadCovering` predicate will not be true for empty shapes.
___
*[pkg/geo/geoindex/s2_geometry_index.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-MBqImwZEDP3vZeHsANl:-MBsc8tD8yl0LlLGK4IZ:b-n19pnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebeccf6de658681831069c524647366ce459f636/pkg/geo/geoindex/s2_geometry_index.go#L133)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

we can just use the BoundingBox from the g.BoundingBox() object here.
</blockquote></details>

We want the bounding box of the clipped geometry `gt` -- we could further optimize by doing that only when it is clipped but the code path to compute the bounding box should be rare.
___
*[pkg/geo/geoindex/s2_geometry_index.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-MBqIxtj8DFnKclUA4Vy:-MBsc6dUC5k0BI757NmW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebeccf6de658681831069c524647366ce459f636/pkg/geo/geoindex/s2_geometry_index.go#L135)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

delete?
</blockquote></details>

Done.

**Review by otan — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51257#-:-MBt3qbe-gh-rACOi5HT:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

**Pull request merged**
