### PR TITLE
lint: speed up TestLowercaseFunctionNames by ~200x

### PR DESCRIPTION
**Pull request by benesch**
It is much faster to run one grep invocation that checks for misuse of
every builtin at once than it is to run one grep invocation per builtin.
On my laptop, this linter now takes 200ms instead of 43s.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]

**Comment by knz** [comment]
:lgtm: somehow I had tried that the first time and it didn't work (was slower), I don't know what I was doing different...

Also people I don't know what you're doing with your machines but here this takes less than 2 seconds. ZFS perhaps? RAM?

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26758#-:-LF6RPFpBXlSBDAN2dX9:byafbfq)*

**Comment by knz** [comment]
merging early for everyone's benefit

bors r+

**Comment by knz** [comment]
bors r=RaduBerinde,knz,jordanlewis

**Pull request merged**
