### PR TITLE
sql: more Postgres compatibility measures for ActiveRecord

### LINKED ISSUE #12148: sql: current_schema{,s}() builtins should return public, not database name
In postgres, running `current_schema()` or `current_schemas(false)` will return `public` when the current database is a user-created database with default settings. We currently return the database name.

This is breaking ActiveRecord, which expects `current_schemas(false)` to contain a match for the namespace name of a table's `pg_class.relnamespace` column (which we always set to `public` for user-created tables) for the following query:

```
SELECT * FROM pg_class AS c
LEFT JOIN pg_namespace AS n
ON n.oid = c.relnamespace
WHERE ((c.relkind IN ('r', 'v', 'm'))AND (c.relname = 'schema_migrations'))
AND (n.nspname = ANY (current_schemas(false)));
```

### LINKED ISSUE #12153: sql: unwrap inner quotes in OID typecasts
ActiveRecord generates `'"schema_migrations"'::regclass` in one of its initialization queries. Postgres treats this the same as `'schema_migrations'::regclass` - we report that there's no relation named `"schema_migrations"`.

Make OID typecasts unwrap any inner quoting.

### LINKED ISSUE #13436: sql: support pg_extension table
Rails queries this when doing database migrations and dumps. We can just leave it blank.

### LINKED ISSUE #13485: sql: support current_database builtin
ActiveRecord 5.0+ requires `current_database()` to function.

### LINKED ISSUE #13486: sql: support pg_try_advisory_{lock,unlock}(int) builtin
Rails 5.0+ requires the [`pg_try_advisory_lock`](https://www.postgresql.org/docs/9.1/static/functions-admin.html) and `pg_advisory_unlock` builtins. Postgres advisory locks are re-entrant locks that are available for application-defined purposes. For now, let's just stub this functionality out.

### LINKED ISSUE #13498: sql: support pg_catalog.obj_description(oid, string) builtin
This builtin is required by ActiveRecord. It returns a database comment, so we can safely no-op it. We already support the single-argument form.

### PR DESCRIPTION
**Pull request by jordanlewis**
A few more compatibility features for ActiveRecord.

- OID casts unwrap outer quotes from their inputs - `'"table"'::regclass` is equivalent to `'table'::regclass`.
- `pg_type`'s entries for string types are now named the same as in Postgres: `text` and `varchar`.
- `pg_type`'s entry for decimal types are now named the same as in Postgres: `numeric`.
- `pg_namespace` now has one entry per database.
- Add the (empty) `pg_extension` virtual table.
- Add (no-op) implementations of some advisory lock builtins.
- Add the `current_database` builtin.
- Add a new overload to `obj_description`.

Resolves #12153.
Resolves #12148.
Resolves #13436.
Resolves #13486.
Resolves #13485.
Resolves #13498.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13429)

### CODE REVIEW

**Comment by cuongdo** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1406 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJht-PqHGnpJyecrwF:-KcJht-QtIrgV0j2fpwW:bwesdyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/049f0b3ed7c5a65c3706afbbc87906c17e8dc2b3/pkg/sql/parser/builtins.go#L1406)):*
> ```Go
> 				return NewDString(schemaForDb(ctx.Database)), nil
> 			},
> 			Info: "Returns the current database.",
> ```

This description is now outdated

---

*[pkg/sql/parser/builtins.go, line 1436 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJhvjeZ9Gn1iVIjVee:-KcJhvjeZ9Gn1iVIjVef:b-z3k5h1) ([raw file](https://github.com/cockroachdb/cockroach/blob/049f0b3ed7c5a65c3706afbbc87906c17e8dc2b3/pkg/sql/parser/builtins.go#L1436)):*
> ```Go
> 				return schemas, nil
> 			},
> 			Info: "Returns the current database; optionally include implicit schemas (e.g. " +
> ```

This is now outdated

---

*[pkg/sql/testdata/builtin_function, line 1147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJi5PYSWbdyM_mfGGR:-KcJi5PYSWbdyM_mfGGS:btxgorp) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e90e7610c294590c1feb49712a8ed5e573ac38/pkg/sql/testdata/builtin_function#L1147)):*
> ```
> SELECT CURRENT_SCHEMAS(true)
> ----
> {pg_catalog,public}
> ```

These tests aren't part of this commit

---

*[pkg/sql/testdata/pgoidtype, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJg2jUIJHxNrx1wyAb:-KcJg2jUIJHxNrx1wyAc:b-sxhhyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a290948121c997c3adddd1b2e05ddef109dfded/pkg/sql/testdata/pgoidtype#L12)):*
> ```
> 
> query O
> SELECT '"pg_constraint"'::REGCLASS
> ```

could you also test with some whitespace before and after `pg_constraint`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
TFTR!

---

Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/parser/builtins.go, line 1406 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJht-PqHGnpJyecrwF:-KcJpOTnKbicHW0Xrdjg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/049f0b3ed7c5a65c3706afbbc87906c17e8dc2b3/pkg/sql/parser/builtins.go#L1406)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

This description is now outdated
</blockquote></details>

Done.

---

*[pkg/sql/parser/builtins.go, line 1436 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJhvjeZ9Gn1iVIjVee:-KcJrWc_QbcJgoaWbsuI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/049f0b3ed7c5a65c3706afbbc87906c17e8dc2b3/pkg/sql/parser/builtins.go#L1436)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

This is now outdated
</blockquote></details>

Done.

---

*[pkg/sql/testdata/builtin_function, line 1147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJi5PYSWbdyM_mfGGR:-KcJt9TrHa7aSfA7urKe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e90e7610c294590c1feb49712a8ed5e573ac38/pkg/sql/testdata/builtin_function#L1147)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

These tests aren't part of this commit
</blockquote></details>

Done.

---

*[pkg/sql/testdata/pgoidtype, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJg2jUIJHxNrx1wyAb:-KcJw3QNM6O0Dzmo-LFR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a290948121c997c3adddd1b2e05ddef109dfded/pkg/sql/testdata/pgoidtype#L12)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

could you also test with some whitespace before and after `pg_constraint`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-:-KcJpP2Buii5JqrGDLfA:b-814g8k)*

**Comment by nvanbenschoten** [comment]
Review status: 1 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 1410 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJxSaHDbgYi426_VLK:-KcJxSaIjiTqII2orysU:b-ipvff5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a431fae48f6fef96cf52672b2470b6868dc1cd0/pkg/sql/parser/builtins.go#L1410)):*
> ```Go
> 	},
> 
> 	// For now, schemas are the same as databases. So, current_schemas returns the
> ```

This change should coordinate with #13404.

---

*[pkg/sql/testdata/pgoidtype, line 12 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJwyW225U4Bs7vjSN6:-KcJwyW34ipWRo6YzxJl:b-68gxml) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a431fae48f6fef96cf52672b2470b6868dc1cd0/pkg/sql/testdata/pgoidtype#L12)):*
> ```
> 
> query OO
> SELECT '"pg_constraint"'::REGCLASS, '  "pg_constraint" '::REGCLASS
> ```

Should something like `'    pg_constraint    '::REGCLASS` (whitespace but no quotes) work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/testdata/pgoidtype, line 12 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcJwyW225U4Bs7vjSN6:-KcKf-fW7li2d-PRHpy8:b-q26zja) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a431fae48f6fef96cf52672b2470b6868dc1cd0/pkg/sql/testdata/pgoidtype#L12)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should something like `'    pg_constraint    '::REGCLASS` (whitespace but no quotes) work?
</blockquote></details>

Good point. Yes. That works now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 2220 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcMomJPdSsLmqv_K3Nf:-KcMomJPdSsLmqv_K3Ng:b-uut9lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2520cb058fadd4fe443d11db1d35b7f8eafa3fc6/pkg/sql/parser/eval.go#L2220)):*
> ```Go
> 			// Trim whitespace and unwrap outer quotes if necessary.
> 			// This is required to mimic postgres.
> 			s = strings.Trim(s, " ")
> ```

It looks like newlines and tabs should also be stripped for whatever reason. `strings.TrimSpaces` is probably what we're looking for.

---

*[pkg/sql/parser/eval.go, line 2221 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcMo7MPtDl2PfQGAIO6:-KcMo7MPtDl2PfQGAIO7:bt1t28f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2520cb058fadd4fe443d11db1d35b7f8eafa3fc6/pkg/sql/parser/eval.go#L2221)):*
> ```Go
> 			// This is required to mimic postgres.
> 			s = strings.Trim(s, " ")
> 			s = unwrapQuotesRegexp.ReplaceAllString(s, "$1")
> ```

We don't really need a regexp anymore then:

```
if len(s) > 1 && s[0] == `"` && s[len(s)-1] == `"` {
  s = s[1:len(s)-1]
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 2220 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcMomJPdSsLmqv_K3Nf:-KcOATQ5UcpivyVE4ThS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2520cb058fadd4fe443d11db1d35b7f8eafa3fc6/pkg/sql/parser/eval.go#L2220)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It looks like newlines and tabs should also be stripped for whatever reason. `strings.TrimSpaces` is probably what we're looking for.
</blockquote></details>

Done.

---

*[pkg/sql/parser/eval.go, line 2221 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcMo7MPtDl2PfQGAIO6:-KcOATbmG0QTdlbuom_N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2520cb058fadd4fe443d11db1d35b7f8eafa3fc6/pkg/sql/parser/eval.go#L2221)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't really need a regexp anymore then:

```
if len(s) > 1 && s[0] == `"` && s[len(s)-1] == `"` {
  s = s[1:len(s)-1]
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r5, 6 of 6 files at r9, 3 of 3 files at r10, 3 of 3 files at r11, 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 1441 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONfxivI7dkC88aKHA:-KcONfxivI7dkC88aKHB:bvrm4xb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1441)):*
> ```Go
> 			},
> 			Info: "Returns the schema of the current current database; optionally " +
> 				"include implicit schemas (e.g. `pg_catalog`). CockroachDB " +
> ```

includes?

---

*[pkg/sql/parser/builtins.go, line 1664 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONqxi037XoYHaMewM:-KcONqxi037XoYHaMewN:blk1mhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1664)):*
> ```Go
> 
> const (
> 	// InformationSchemaName is the name of the information_schema table.
> ```

s/table/database/ on all three  constants

---

*[pkg/sql/parser/builtins.go, line 1674 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONuEkbbco4fWkUbnU:-KcONuEkbbco4fWkUbnV:bcb5rbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1674)):*
> ```Go
> // schemaForDb maps a DatabaseDescriptor to its corresponding pgNamespace.
> // See the comment above pgNamespace for more details.
> func schemaForDb(db string) string {
> ```

how come not 'DB'?

---

*[pkg/sql/parser/builtins.go, line 1675 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONivcEnxKknPMTn7E:-KcONivcEnxKknPMTn7F:b-nkx9v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1675)):*
> ```Go
> // See the comment above pgNamespace for more details.
> func schemaForDb(db string) string {
> 	if db == InformationSchemaName || db == PgCatalogName || db == SystemName {
> ```

might read better as a switch-case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/builtins.go, line 1441 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONfxivI7dkC88aKHA:-KcPR-mxvBFBjJ6UggU5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1441)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

includes?
</blockquote></details>

Done.

---

*[pkg/sql/parser/builtins.go, line 1664 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONqxi037XoYHaMewM:-KcPR82-7HzmTYeu1XdV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1664)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/table/database/ on all three  constants
</blockquote></details>

Done.

---

*[pkg/sql/parser/builtins.go, line 1674 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONuEkbbco4fWkUbnU:-KcP_Bs6hBg4fOwJ3E0U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1674)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come not 'DB'?
</blockquote></details>

Done.

---

*[pkg/sql/parser/builtins.go, line 1675 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcONivcEnxKknPMTn7E:-KcP_C3Yj4_Cv2x3wG50:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d72cadbe76f7264fd7c8a80bd3aa38e6df5a13/pkg/sql/parser/builtins.go#L1675)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

might read better as a switch-case
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r13, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1676 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcPhcHG_f47A46RJ5tZ:-KcPhcHG_f47A46RJ5t_:b-j9qxd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb4916b4e78a07381c644244b736c137b9b18f9b/pkg/sql/parser/builtins.go#L1676)):*
> ```Go
> func schemaForDB(db string) string {
> 	switch db {
> 	case InformationSchemaName:
> ```

you can make this one single case

```
switch db {
case InformationSchemaName, PgCatalogName, SystemName:
  return db
default:
  return "public"
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
Review status: 3 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/parser/builtins.go, line 1676 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcPhcHG_f47A46RJ5tZ:-KcPiQwLYc0d31qk7LCY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb4916b4e78a07381c644244b736c137b9b18f9b/pkg/sql/parser/builtins.go#L1676)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you can make this one single case

```
switch db {
case InformationSchemaName, PgCatalogName, SystemName:
  return db
default:
  return "public"
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r15, 3 of 3 files at r16.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
Reworked the `current_schema` commit after discussing with @knz about compatibility with his upcoming namespaces change. Now the `current_schema` behavior is left unchanged - but `pg_namespace` now reports a namespace per database instead of a single `public` namespace for all user-created databases.

Also added a few more commits with some new fixes for active record and updated the PR description to match.

**Comment by knz** [comment]
Awesome, thanks. One request about a builtin description, though. Looks otherwise fine to me.

---

Reviewed 1 of 3 files at r16, 1 of 4 files at r18, 3 of 3 files at r21, 1 of 1 files at r22.
Review status: 7 of 8 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1395 at r22](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-Kc_BswRDH80WNPUX-WG:-Kc_BswSxZr9HQQCWcg6:buon2z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/83bd928d60e191e90e658ff1bc02f821b57ea4aa/pkg/sql/parser/builtins.go#L1395)):*
> ```Go
> 	},
> 
> 	"current_database": {
> ```

Side note: The existence of both `current_database` and `current_schema` is bound to introduce confusion. 
All the more reason to do something about #13319.

---

*[pkg/sql/parser/builtins.go, line 1421 at r22](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-Kc_C85uNKm0CVmHWmOi:-Kc_C85v5ojIWNeHouUC:bnbd92v) ([raw file](https://github.com/cockroachdb/cockroach/blob/83bd928d60e191e90e658ff1bc02f821b57ea4aa/pkg/sql/parser/builtins.go#L1421)):*
> ```Go
> 				return NewDString(ctx.Database), nil
> 			},
> 			Info: "Returns the current database.",
> ```

Once `current_database` becomes available, please change the `Info` field of `current_schema` to say "This function is provided for compatibility with PostgreSQL. For a new CockroachDB application, consider using current_database() instead."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-:-Kc_Cdek3MVtz5HwX5aD:brhz6uh)*

**Comment by jordanlewis** [comment]
Review status: 3 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/parser/builtins.go, line 1421 at r22](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-Kc_C85uNKm0CVmHWmOi:-Kc_LZwm2-yAeHrxNBmK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83bd928d60e191e90e658ff1bc02f821b57ea4aa/pkg/sql/parser/builtins.go#L1421)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Once `current_database` becomes available, please change the `Info` field of `current_schema` to say "This function is provided for compatibility with PostgreSQL. For a new CockroachDB application, consider using current_database() instead."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
RFAL - is this good to go?

**Comment by knz** [comment]
It is for me! But I didn't feel I was primary reviewer :-)

Jordan Lewis <notifications@github.com> schreef op 10 februari 2017 17:36:07 CET:
>RFAL - is this good to go?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cockroachdb/cockroach/pull/13429#issuecomment-278993053

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jordanlewis** [comment]
I mainly didn't set you as a primary reviewer because you have been awfully busy - but I'm more than happy to take your LGTM if you're offering 😄

**Comment by bdarnell** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1680 at r30](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcnV8RphsYF6h19DH2z:-KcnV8RqIqR0tRVrYs6Y:bsm612u) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e8bcebb10c562266c2916711c03f4e9c40c76e/pkg/sql/parser/builtins.go#L1680)):*
> ```Go
> 			ReturnType: fixedReturnType(TypeBool),
> 			fn: func(_ *EvalContext, _ Datums) (Datum, error) {
> 				return DBoolTrue, nil
> ```

I'm a little late to this PR, but it seems bad to lie about locking like this. Even if ActiveRecord is (currently) OK with us stubbing out this lock, implementing this function in a silently broken way could cause problems for other frameworks in the future. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by jordanlewis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1680 at r30](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429#-KcnV8RphsYF6h19DH2z:-KcnlwN27XASQRUfrFZ_:bcprti9) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e8bcebb10c562266c2916711c03f4e9c40c76e/pkg/sql/parser/builtins.go#L1680)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm a little late to this PR, but it seems bad to lie about locking like this. Even if ActiveRecord is (currently) OK with us stubbing out this lock, implementing this function in a silently broken way could cause problems for other frameworks in the future. 
</blockquote></details>

Good point.  Opened #13546.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13429)*

**Comment by sandstrom** [comment]
You should mention in your docs somewhere, that there are known limitations with your ActiveRecord compatibility and explain that these things are (mentioning this one).

https://github.com/rails/rails/blob/8de10f9bb6edaf10bde21cea73db3da2aac6f6de/activerecord/lib/active_record/migration.rb#L151

**Comment by brandondrew** [comment]
@jordanlewis 
> TFTR!

[Tokamak Fusion Test Reactor](https://www.google.com/search?hl=en&q=TFTR#ip=1)?

**Comment by jordanlewis** [comment]
It stands for "thanks for the review"

**Pull request merged**
