### PR TITLE
ui: use classnames everywhere

### LINKED ISSUE #20314: ui: use classnames everywhere
There are a lot of places in our codebase that we're conditionally concatenating strings together to make the class of some element.  A handful of them already use `classnames` but most don't.  We should use that everywhere.

### PR DESCRIPTION
**Pull request by couchand**
Rather than conditionally concatenating strings, let's use the
classnames helper package.

Closes #20314.

Release notes: none.

### CODE REVIEW

**Comment by couchand** [comment]
@BramGruneir a lot of the wonkier ones were your work, could you take a look to check if I botched anything?

**Comment by vilterp** [comment]
Thanks for doing this refactor! Makes things a lot easier to read.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/views/cluster/components/visualization/index.tsx, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-4cqmljEuTMzXr4aeH:-L-4cqmljEuTMzXr4aeI:b-497mtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/cluster/components/visualization/index.tsx#L39)):*
> ```XML
>     });
>     const contentClasses = classNames({
>       "visualization__content": true,
> ```

you can use initial positional arguments for ones that are always true:

```
const contentClasses = classNames("visualization__content", {
    "visualization--loading": this.props.loading
})
```

Applies to pretty much each file in the diff :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-:-L-4dSh-dYx6GjLZUHsh:bd23113)*

**Comment by BramGruneir** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-7o2SnbKYbZaQbTU80:-L-7o2SoUuSDa8b7iRnB:b-vl3az6) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L226)):*
> ```XML
>         "range-table__cell": true,
>         "range-table__cell--dormant": dormant,
>         "range-table__cell--different-from-leader-warning": !dormant && differentFromLeader,
> ```

You could just move the dormant check into differentFromLeader, no point is performing all those other calculations if dormant.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 263 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-7oZf-9_I9qvfusB6Z:-L-7oZf-9_I9qvfusB6_:btohc3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L263)):*
> ```XML
>     }
>     const headerClassName = classNames({
>       "range-table__cell range-table__cell--header": true,
> ```

Isn't this two different classes?

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 303 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-7p-wPzIt2eFrGnXh2:-L-7p-wPzIt2eFrGnXh3:bhlpskz) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L303)):*
> ```XML
>       "range-table__cell--dormant": dormant,
>       "range-table__cell--different-from-leader-warning": !dormant && differentFromLeader,
>       "range-table__cell--local-replica": !dormant && replica && replica.store_id === localStoreID,
> ```

Do we need a !differentFromLeader here?  Local and Different should never be true at the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316)*

**Comment by couchand** [comment]
Ok, made all the requested changes, PTAL.

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/views/cluster/components/visualization/index.tsx, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-4cqmljEuTMzXr4aeH:-L-CdwqJHJvfRzPBp-rD:b-kohar4) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/cluster/components/visualization/index.tsx#L39)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

you can use initial positional arguments for ones that are always true:

```
const contentClasses = classNames("visualization__content", {
    "visualization--loading": this.props.loading
})
```

Applies to pretty much each file in the diff :P
</blockquote></details>

Done, everywhere that had exactly one dynamic class.  Where there are several dynamic classes, pulling out the static ones makes it slightly more cumbersome, let me know if you disagree.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-7o2SnbKYbZaQbTU80:-L-CeDwrGlt1Otajbpbp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L226)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

You could just move the dormant check into differentFromLeader, no point is performing all those other calculations if dormant.
</blockquote></details>

Done.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 263 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-7oZf-9_I9qvfusB6Z:-L-CeFX6DL-hifhQc1_8:bb77ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L263)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Isn't this two different classes?
</blockquote></details>

Yep.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 303 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-7p-wPzIt2eFrGnXh2:-L-CeHnaPR4bGqbZ3umP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a837c16eafa898dca252396ee860ce196175b0/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L303)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Do we need a !differentFromLeader here?  Local and Different should never be true at the same time.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-:-L-CeLe914o72ktnbsj8:bygt01q)*

**Comment by vilterp** [comment]
:lgtm: with a couple of nits

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-CgSvYxtoOnB8gQjlA:-L-CgSvYxtoOnB8gQjlB:biz1t2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46189d85bc10fc6cda4bf188fa381b53f726eb/pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx#L76)):*
> ```XML
>     "cluster-summary__metric",
>     "suspect-nodes",
>     {"warning": suspectNodes > 0 },
> ```

nit: space after `{`

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 302 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-CgiyzRxz1VoW1aWai:-L-CgiyzRxz1VoW1aWaj:b-a2jkrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46189d85bc10fc6cda4bf188fa381b53f726eb/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L302)):*
> ```XML
>     const localReplica = !dormant && !differentFromLeader && replica && replica.store_id === localStoreID;
>     const className = classNames({
>       "range-table__cell": true,
> ```

missed this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-:-L-CgrSwBJRgS1B8S42P:b-3qzdeb)*

**Comment by couchand** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-CgSvYxtoOnB8gQjlA:-L-Cjnasuo0iTp_Xnmac:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46189d85bc10fc6cda4bf188fa381b53f726eb/pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx#L76)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

nit: space after `{`
</blockquote></details>

Done.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 302 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-L-CgiyzRxz1VoW1aWai:-L-Cjo_YN-bizZ4JkLh0:bb0t56j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e46189d85bc10fc6cda4bf188fa381b53f726eb/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L302)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

missed this one
</blockquote></details>

See my response to your first comment - I think this looks awkward when there's more than one dynamic class, since it means you can't one-line the object literal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20316#-:-L-ClJmq7eTcOsUPPZsI:bnfp4nl)*

**Pull request merged**
