### PR TITLE
storage/engine: bump write buffer size from 8MB to 64MB

### PR DESCRIPTION
**Pull request by petermattis**
The write_buffer_size controls the size of the RocksDB memtable. A
higher setting means we'll buffer more data before flushing to disk and
thus reduce write amplification at L0 and L1.

Bump level0_file_num_compaction_trigger from 1 to 2. This also reduces
write amplification and the cost of a small amount of read
amplification.

Adjust max_bytes_for_level_base to continue to follow the RocksDB
recommendation that the size of L1 be the same as the estimated size of
L0. We estimate the size of L0 as 2 32MB files. Experimentally, L0 files
appear to be ~40 MB in the workload (ycsb) I tested.

These changes reduced write amplification from 16.2 to 10.1 for a write
only workload (`ycsb --workload F`), improved throughput by 8% and
reduced the amount of data written by compactions from 3.2TB to 2.1TB.

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM. Did you test out other numbers that didn't work quite so well? Writing those down (at least in this PR) would be useful too

**Comment by petermattis** [comment]
I tested setting `level0_file_num_compaction_trigger` to 3 and 4. Both values produced more spiky throughput. I also tested setting `max_bytes_for_level_base` to 96MB, 128MB and 192MB. None of these settings produced a noticeable change in performance or write amplification. I didn't try any other values for `write_buffer_size`.

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/engine/db.cc, line 1579 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16929#-KohQjpc8jsd2VP4N7Es:-KohQjpc8jsd2VP4N7Et:b-pro1pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2a77462c9e075b3d48508aff392aa0ca53d09e8/pkg/storage/engine/db.cc#L1579)):*
> ```cpp
>   // to be somewhat larger than than typical range size so that
>   // deletion of a range worth of keys does not cause write stalls.
>   options.max_write_buffer_number = 4;
> ```

This is now hard-coding a memtable budget of 256MiB (up from 128MiB). This is a non-trivial fraction of a minimum-spec node (with 2GiB of ram and half of that reserved for cache and sql working memory. We'd even like to reduce that minimum to 1GiB - that's what we had in the docs at some early stage but we already experience undiagnosed OOM problems at 1GiB). We should probably make this configurable and/or responsive to the total available memory. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16929)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/engine/db.cc, line 1579 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16929#-KohQjpc8jsd2VP4N7Es:-KohjRsRrKSpeSY58da3:bdulj1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2a77462c9e075b3d48508aff392aa0ca53d09e8/pkg/storage/engine/db.cc#L1579)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is now hard-coding a memtable budget of 256MiB (up from 128MiB). This is a non-trivial fraction of a minimum-spec node (with 2GiB of ram and half of that reserved for cache and sql working memory. We'd even like to reduce that minimum to 1GiB - that's what we had in the docs at some early stage but we already experience undiagnosed OOM problems at 1GiB). We should probably make this configurable and/or responsive to the total available memory. 
</blockquote></details>

RocksDB only allocates the memory for memtables as necessary. So while we have a max of 256MiB that can be used by memtables, we'll usually be using something in the 64-128MiB range. 

I wonder if we should just subtract 256MiB from the configured cache size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16929)*

**Pull request merged**
