### PR TITLE
storage/engine: make pebbleTimeBoundPropCollector extract intent timestamps

### LINKED ISSUE #41900: storage/engine: pebbleTimeBoundPropCollector not extracting intent timestamp
The C++ `TimeBoundTblPropCollector` contains the following code:

```
    if (!last_value_.empty()) {
      // Check to see if an intent was the last key in the SSTable. If
      // it was, we need to extract the timestamp from the intent and
      // update the bounds to include that timestamp.
      cockroach::storage::engine::enginepb::MVCCMetadata meta;
      if (!meta.ParseFromArray(last_value_.data(), last_value_.size())) {
        // We're unable to parse the MVCCMetadata. Fail open by not
        // setting the min/max timestamp properties.
        return rocksdb::Status::OK();
      }
      if (meta.has_txn()) {
        // We have an intent, use the intent's timestamp to update the
        // timestamp bounds.
        std::string ts;
        EncodeTimestamp(ts, meta.timestamp().wall_time(), meta.timestamp().logical());
        UpdateBounds(ts);
      }
    }
```

This logic is missing from `pebbleTimeBoundPropCollector`. I'm also not sure it is correct. It isn't obvious to me why we only do this intent timestamp extraction if the intent is the last key in the sstable. Hmm, it might be because the intent timestamp is also reflected in a versioned value which will immediately follow the intent record. That's subtle and should be called out in a comment more explicitly.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #41900

Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41958#-:-LsJA-L-6pnICC1jnAuj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/testdata/time_bound_props, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41958#-LsJ9s1592pWINBMyysn:-LsJ9s17AiXBtR7l16Vh:b5nv0wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e27c9a7610f2b150795f11b5fb81dcadbc6da25/pkg/storage/engine/testdata/time_bound_props#L28)):*
> ```
> crdb.ts.min: 0000000000000002
> 
> # Note that this case should never happen. We can't have an intent on
> ```

Not sure about the value of testing "should never happen" cases, but I guess it rigidly lays out the implementation which is nice.

**Review by petermattis — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41958#-:-LsJLc0J0h8uWosMJZ8c:bz5m8ji)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/testdata/time_bound_props, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41958#-LsJ9s1592pWINBMyysn:-LsJLTg-8tvqylaVff9T:b-sn2wqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e27c9a7610f2b150795f11b5fb81dcadbc6da25/pkg/storage/engine/testdata/time_bound_props#L28)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Not sure about the value of testing "should never happen" cases, but I guess it rigidly lays out the implementation which is nice.
</blockquote></details>

Yeah, these are just about verifying boundary behavior. I'm not attached to the current behavior, but wanted to make it clear what happens when it occurs.

**Comment by petermattis** [comment]
bors r=itsbilal

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41958)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41958#-LsMg4BMEMuR4BQEDwHE:-LsMg4BMEMuR4BQEDwHF:bv0p52b) ([raw file](https://github.com/cockroachdb/cockroach/blob/280dc16568a31965e4171908c0ef1aaf30a700fc/pkg/storage/engine/pebble.go#L136)):*
> ```Go
> 			return nil
> 		}
> 		if meta.Txn != nil {
> ```

what causes meta.Txn to be nil (there wasn't a comment in mvcc.proto)?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41958)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41958#-LsMg4BMEMuR4BQEDwHE:-LsMitOx2mqhN-aZ3yh3:b-disv9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/280dc16568a31965e4171908c0ef1aaf30a700fc/pkg/storage/engine/pebble.go#L136)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what causes meta.Txn to be nil (there wasn't a comment in mvcc.proto)?
</blockquote></details>

I don't think it can be nil. I meant to ask Nathan and Tobias about this. Thanks for the reminder. Note that this is exactly the logic in the C++ version of this code.

**Pull request merged**
