### PR TITLE
ccl: Fill in chart catalog with missed metrics

### LINKED ISSUE #81359: catalog: is incomplete
**Describe the problem**

The chart catalog is incomplete since it doesn't correctly pick up metrics from the CCL binary.

It also contains metrics that no longer exist.

A WIP PR that updates the `TestChartCatalogMetrics` can be found here: https://github.com/cockroachdb/cockroach/pull/81038

This PR needs to be picked up and the catalog rectified. This will also prevent the divergence going forward.

**To Reproduce**

Check out the PR and run the test.

**Expected behavior**

Catalog is up to date.

**Additional data / screenshots**

**Environment:**
master at time of writing

**Additional context**

This means that `tsdump` fails to pick up a number of timeseries, mostly related to changefeeds.

Jira issue: CRDB-15223

### PR DESCRIPTION
**Pull request by koorosh**
Based on PR: #81038

Resolves: #81359

This change adds missing metrics to the chart catalog.

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Feel free to squash the commits (i.e. take ownership of my commit); there's generally no need to preserve my authorship. I'm happy you picked this up so quickly! Only need to figure out 1schedule_metrics.go`  and then if it passes CI, LGTM.

> Reviewed 2 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81739#-:-N2q4ReL4oLx9AWmibKD:b-k514lg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper and @koorosh)

___
*[`pkg/jobs/schedule_metrics.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81739#-N2q49LM8XVa1k53XqoV:-N2q49LN8m7nC81nODtg:b4vi4w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2004f0276919ed86d407ce8b26514b2ea4a34246/pkg/jobs/schedule_metrics.go#L91)):*
> ```Go
> 		}),
> 
> 		NumTotalStartedSchedules: metric.NewGauge(metric.Metadata{
> ```

Wait, why are we adding metrics? I think the changes in this file should go, we should make sure the chart catalog reflects the truth, not make the truth reflect the chart catalog :-)

**Review by koorosh — COMMENTED** [review]
The only thing, I cannot push directly to your PR #81038 (I'm not in code owners group) so squashed all changes in this PR. Thanks for the feedback!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81739#-:-N2qDFt66dhPdVMslySV:btfpxe7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper and @tbg)

___
*[`pkg/jobs/schedule_metrics.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81739#-N2q49LM8XVa1k53XqoV:-N2qClEKBHDK5Dfk2ET5:b-r9wpm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2004f0276919ed86d407ce8b26514b2ea4a34246/pkg/jobs/schedule_metrics.go#L91)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Wait, why are we adding metrics? I think the changes in this file should go, we should make sure the chart catalog reflects the truth, not make the truth reflect the chart catalog :-)
</blockquote></details>

ah, that was too naive to adjust everything to fit the chart catalog's state :)

**Review by tbg — APPROVED** [review]
:lgtm: 

you could `git commit --amend --reset-author` to have your name on it but I don't know if it's worth your trouble.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81739#-:-N2qIVAa7cuiCgoHg8yB:b-tzq18w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gh-casper and @tbg)

**Pull request merged**
