### PR TITLE
rangefeed: improve assertion when txn refcount becomes negative

### PR DESCRIPTION
**Pull request by nvb**
Informs #34600.

It is critical that `unresolvedIntentQueue` properly handle negative
reference counts to avoid leaking references before a rangefeed has
finished its resolved timestamp initialization scan. However, once this
scan is complete, reference counts on transactions should never drop
below zero. Such an occurrence would indicate that an intent was lost
either during the initial scan or somewhere in the logical ops stream.

Based on the stacktraces in #34600, I believe this is what is happening
because we can see that an `MVCCCommitIntentOp` is triggering the
assertion. This commit will make this more explicit and should hopefully
also fire more because it won't rely on the intent with a negative
refcount being the oldest intent tracked to fire.

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35772#-:-L_yhGsf4w2HpO38V_eO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

**Comment by nvanbenschoten** [comment]
I'm able to hit this assertion immediately! That means I probably shouldn't merge this until the root issue is fixed.

**Comment by danhhz** [comment]
Are you still thinking of merging this with the fix?

**Comment by nvanbenschoten** [comment]
Yes!

bors r+

**Comment by nvanbenschoten** [comment]
Flake due to #34081.

bors r+

**Comment by nvanbenschoten** [comment]
Flaked due to #35484.

bors r+

**Pull request merged**
