### PR TITLE
rpc: avoid disconnecting on heartbeat timeouts for CLI clients

### PR DESCRIPTION
**Pull request by tamird**
This reverts commit 94882ece5ecb562ad889e02ccb32b9d8167794cf.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14123)

### CODE REVIEW

**Comment by bdarnell** [comment]
Put the revert in a separate commit?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/rpc/context.go, line 338 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iGKDPKhO_TTctpLM:-Kf8iGKDPKhO_TTctpLN:b-lje28n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L338)):*
> ```Go
> 		// timeouts) fail eagerly. Any other error is likely to be noticed by
> 		// other RPCs, so it's OK to leave the connection open while grpc
> 		// internally reconnects if necessary.go
> ```

s/go//

---

*[pkg/rpc/context.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iK6DkZ5yqQ2RfR1c:-Kf8iK6DkZ5yqQ2RfR1d:b-xc12la) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L341)):*
> ```Go
> 		//
> 		// NB: This check is skipped when the connection is initiated from a CLI
> 		// client (indicated by the zero maxOffset) since those clients aren't
> ```

The use of `maxOffset` for this is kind of a hack; if we ever do #14093 we might have servers running with a zero maxOffset but they'd still want to disconnect on heartbeat failures. Can we do something more explicit for the CLI commands?

---

*[pkg/rpc/context.go, line 342 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iI6HjT2dY4AdLQvI:-Kf8iI6HjT2dY4AdLQvJ:bbbvkje) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L342)):*
> ```Go
> 		// NB: This check is skipped when the connection is initiated from a CLI
> 		// client (indicated by the zero maxOffset) since those clients aren't
> 		// sensitive to partitionsm, are likely to be invoked while the server is
> ```

s/partitionsm/partitions/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-:-Kf8iDlCXAHx0xmfk-yD:bgphrv2)*

**Comment by tamird** [comment]
Is that better? This just happens to revert, the main purpose is as described in the subject.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/rpc/context.go, line 338 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iGKDPKhO_TTctpLM:-Kf8j2ATBdZNDH1SFt8-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L338)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/go//
</blockquote></details>

Done.

---

*[pkg/rpc/context.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iK6DkZ5yqQ2RfR1c:-Kf8j2roWFYf_zl81bjw:b-er66tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L341)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The use of `maxOffset` for this is kind of a hack; if we ever do #14093 we might have servers running with a zero maxOffset but they'd still want to disconnect on heartbeat failures. Can we do something more explicit for the CLI commands?
</blockquote></details>

Definitely a hack. We could do a naked grpc.Dial for the CLI commands, but that's more surgery; perhaps that can be done when it's necessary?

---

*[pkg/rpc/context.go, line 342 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iI6HjT2dY4AdLQvI:-Kf8j2iouaoXPOPbHVgF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L342)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/partitionsm/partitions/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-:-Kf8jEbjzl7He-_nTHgD:b-sj62ga)*

**Comment by bdarnell** [comment]
:lgtm: 

Is what better? The only change I see (unless reviewable is confusing me) is the typo fixes. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/rpc/context.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iK6DkZ5yqQ2RfR1c:-Kf8kPUktOJ9x2cnrdoO:b-wqzky5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Definitely a hack. We could do a naked grpc.Dial for the CLI commands, but that's more surgery; perhaps that can be done when it's necessary?
</blockquote></details>

Make this a TODO instead of an NB then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-:-Kf8keDFjHahe6FzV4Zs:b-hykd3o)*

**Comment by tamird** [comment]
> Put the revert in a separate commit?

I was replying to this.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/rpc/context.go, line 341 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-Kf8iK6DkZ5yqQ2RfR1c:-Kf8lvwPqz0qkSypQ86H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3da3d029757fdd74ac6b75ab619aafa048b14f3/pkg/rpc/context.go#L341)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Make this a TODO instead of an NB then.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-:-Kf8lauHw68u7JZ7c4ll:bw8l7th)*

**Comment by bdarnell** [comment]
> Is that better?

And I was replying to this. If "that" was referring to the revert instead of a change you had made, then yeah, I think it is - this change leaves a portion of the previous commit in place and it's hard to see what the net change is. (I also wouldn't micro-manage commit history for anyone but you :))

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-:-Kf8n7HSK3zbWwLctEfB:b6k1f4r)*

**Comment by tamird** [comment]
Point taken. I've reworded the commit message to more explicitly call out the net change. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14123#-:-Kf8oDi_r92gZovDKLfP:b-vdowid)*

**Pull request merged**
