### PR TITLE
sql: restrict CHECK to valid boolean exprs

### LINKED ISSUE #6427: sql: CHECK constraints allow non-bool expressions
```
root@:26257> create table t (ts decimal check (cluster_logical_timestamp()));
CREATE TABLE
root@:26257> insert into t values (decimal '1');
pq: cannot convert decimal to bool
```

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #6427

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6452)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/table.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-KGmhCL_cRrmxtHN3RJK:-KGmhCL_cRrmxtHN3RJL:-1385253139) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed18e970ba004547db83f2e5e6959c6905b8837/sql/table.go#L153)):*
Does this fix the `TODO(guanqun)` in `makeColumnDefDescs`? 

Is a `CHECK` expression on a column able to use other columns in the table?

Feels like the above belongs in a helper method, for clarity if nothing else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/table.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-KGmhCL_cRrmxtHN3RJK:-KGmtq_ORzHtBUugBMQu:-1936129580) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed18e970ba004547db83f2e5e6959c6905b8837/sql/table.go#L153)):*
+1 to helper method since we'll presumably want to reuse for ALTER as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/table.go, line 150 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-KGmvxO8ArL0g-F32aI1:-KGmvxO8ArL0g-F32aI2:-1983952610) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed18e970ba004547db83f2e5e6959c6905b8837/sql/table.go#L150)):*
PG gives a better error here: "argument of CHECK must be type boolean, not type integer"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/table.go, line 150 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-KGmvxO8ArL0g-F32aI1:-KGmzpgp8MLucOYt2Yeh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed18e970ba004547db83f2e5e6959c6905b8837/sql/table.go#L150)):*
Done.

---

*[sql/table.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-KGmhCL_cRrmxtHN3RJK:-KGn5yA-pckuvFzdFjm6:651552101) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed18e970ba004547db83f2e5e6959c6905b8837/sql/table.go#L153)):*
The wiki entry on check (https://en.wikipedia.org/wiki/Check_constraint) says that when defined on a column, a check constraint may only refer to that column. Postgres notably doesn't do this, but it also always moves all check constraints to the table level. I've moved the code back to the column-level and added that check, because I think it makes more sense. We can add table-level CHECKs later which can support cross-column stuff.

Since the CHECK stuff is now moved into it's old place, I think it's better to not create a helper function until we need it in two places and know what common logic is needed between the two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/table.go, line 211 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-KGo2OTSxb-BXequepJE:-KGo2OTSxb-BXequepJF:-1877607324) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe6ba75942272a42c50363ac962e463bd85f4482/sql/table.go#L211)):*
Would be nice to link to the wikipedia entry with a URL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-:-KGo2_VFqzu6oPzIh-P2:1417088721)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/table.go, line 211 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452#-KGo2OTSxb-BXequepJE:-KGp5Y5tJBvuTvj5dF_6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe6ba75942272a42c50363ac962e463bd85f4482/sql/table.go#L211)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6452)*

**Pull request merged**
