### PR TITLE
opt: Decorrelate LIMIT 1

### PR DESCRIPTION
**Pull request by andy-kimball**
Add rules to decorrelate queries like this:
  SELECT (SELECT x FROM xy WHERE y=v LIMIT 1) FROM uv

Also add Optgen support for literal numeric values, to make it
easy to match and construct values like "1", "0", etc.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28268#-:-LJEq3Vn5JEf2nwIJCv4:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/groupby.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28268#-LJEpe0i15slIKXTl9W2:-LJEpe0j2MLkou3hUivt:becm999) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a0eedb51aede2097da86d575259333dd435050/pkg/sql/opt/norm/groupby.go#L95)):*
> ```Go
> 	aggOp opt.Operator, cols opt.ColSet, outElems []memo.GroupID, outColList opt.ColList,
> ) {
> 	// Append ConstAgg aggregate functions wrapping each appendCol.
> ```

this comment needs updating I think?
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28268#-LJEcfwc2JFSoWQoc0wi:-LJEcfwc2JFSoWQoc0wj:b-95q7z0) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a0eedb51aede2097da86d575259333dd435050/pkg/sql/opt/norm/rules/decorrelate.opt#L399)):*
> ```
> (InnerJoin | InnerJoinApply | LeftJoin | LeftJoinApply
>     $left:*
>     $right:* &
> ```

this relies on `CommuteJoin` to handle cases where it's `left` that has the `LIMIT 1`, right?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28268)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28268#-LJEcfwc2JFSoWQoc0wi:-LJExphdAl4XSC3Do470:b-n8i79j) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a0eedb51aede2097da86d575259333dd435050/pkg/sql/opt/norm/rules/decorrelate.opt#L399)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

this relies on `CommuteJoin` to handle cases where it's `left` that has the `LIMIT 1`, right?
</blockquote></details>

Hm, CommuteJoin is an exploration rule, I don't think this rule would run (and definitely not any higher-level rules that depend on this rule).

My guess is that we only care about this form because this is the one we'll see during decorrelation

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28268)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/groupby.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28268#-LJEpe0i15slIKXTl9W2:-LJFM1IdBp6LWAO84DO7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a0eedb51aede2097da86d575259333dd435050/pkg/sql/opt/norm/groupby.go#L95)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

this comment needs updating I think?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28268#-LJEcfwc2JFSoWQoc0wi:-LJFM7IRAc4VRbuhNLEG:b-gkec20) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a0eedb51aede2097da86d575259333dd435050/pkg/sql/opt/norm/rules/decorrelate.opt#L399)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, CommuteJoin is an exploration rule, I don't think this rule would run (and definitely not any higher-level rules that depend on this rule).

My guess is that we only care about this form because this is the one we'll see during decorrelation
</blockquote></details>

Yeah, we almost never see decorrelation cases in the left side of a join, so I didn't bother handling it. I added the TODO in the comment to track adding other join types in the future. It can be quite time consuming to add new join types, since we've got to prove that each join type is valid for the transformation. For example, proving that `LeftJoin` is valid for this rule is not trivial (especially with `Apply` and orderings). And proving that one join type is valid does not mean that others are.

**Pull request merged**
