### PR TITLE
sql-telemetry: query_sampling.max_event_frequency public

### LINKED ISSUE #108385: Set public = t for sql.telemetry.query_sampling.max_event_frequency cluster setting
This setting needs to be documented according to [DOC-8029](https://cockroachlabs.atlassian.net/browse/DOC-8029):

```
sql.telemetry.query_sampling.max_event_frequency
```

However it is not publicly documented on [the cluster settings page](https://www.cockroachlabs.com/docs/v23.1/cluster-settings) because it has public = f in crdb_internal.cluster_settings. The cluster settings page is automatically generated with settings where public = t.

Describe the solution you'd like
Please set public = t for the above cluster setting.

### PR DESCRIPTION
**Pull request by emilaleksanteri**
Epic: none
Fixes: #108385

Release note (sql change): make max_event_frequency public for public documentation

### CODE REVIEW

**Review by florence-crl — COMMENTED** [review]
@maryliag please review or ask someone else to review to make sure the code change is correct. thanks!

**Review by maryliag — CHANGES_REQUESTED** [review]
Hi @emilaleksanteri , thank you for your contribution! 

You're missing an update on a generate file, to have the needed doc file updated you need to run `./dev gen`, which will generate something similar to this other PR: https://github.com/cockroachdb/cockroach/pull/106530/files

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-:-Nflu85c9DmeVjrRswSD:bn0hlj8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emilaleksanteri)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-NfltuyaD-CfF1MSK18G):*
We do have a format to commit messages, you need to add `Fixes #108385` to this commit message and also a release note, similar to https://github.com/cockroachdb/cockroach/pull/106530

**Comment by emilaleksanteri** [comment]
> Hi @emilaleksanteri , thank you for your contribution!
> 
> You're missing an update on a generate file, to have the needed doc file updated you need to run `./dev gen`, which will generate something similar to this other PR: https://github.com/cockroachdb/cockroach/pull/106530/files
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-:-Nflu85c9DmeVjrRswSD:bn0hlj8)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emilaleksanteri)
> 
> _[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-NfltuyaD-CfF1MSK18G):_ We do have a format to commit messages, you need to add `Fixes #108385` to this commit message and also a release note, similar to #106530

Oh right, sounds good, thank you!

**Comment by emilaleksanteri** [comment]
> Hi @emilaleksanteri , thank you for your contribution!
> 
> You're missing an update on a generate file, to have the needed doc file updated you need to run `./dev gen`, which will generate something similar to this other PR: https://github.com/cockroachdb/cockroach/pull/106530/files
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-:-Nflu85c9DmeVjrRswSD:bn0hlj8)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emilaleksanteri)
> 
> _[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-NfltuyaD-CfF1MSK18G):_ We do have a format to commit messages, you need to add `Fixes #108385` to this commit message and also a release note, similar to #106530

> Hi @emilaleksanteri , thank you for your contribution!
> 
> You're missing an update on a generate file, to have the needed doc file updated you need to run `./dev gen`, which will generate something similar to this other PR: https://github.com/cockroachdb/cockroach/pull/106530/files
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-:-Nflu85c9DmeVjrRswSD:bn0hlj8)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emilaleksanteri)
> 
> _[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-NfltuyaD-CfF1MSK18G):_ We do have a format to commit messages, you need to add `Fixes #108385` to this commit message and also a release note, similar to #106530
Hi, it looks like there is something wrong with my ./dev gen builder on linux_amd64 

`GoCompilePkg pkg/ccl/gssapiccl/gssapiccl.a [for tool] failed: (Exit 1): builder failed: error executing command (from target //pkg/ccl/gssapiccl:gssapiccl) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src pkg/ccl/gssapiccl/get_user.go -src ... (remaining 53 arguments skipped)`

Do you know if I need to do something with my bazel/bazelisk to make the gen work?

**Comment by rickystewart** [comment]
@emilaleksanteri 

You should be able to reproduce the issue with `bazel build pkg/gen:code`. You get a better error message by adding the flag `--verbose_failures`.

From the beginning of the error message, I'm assuming it's going to be a `resolv_wrapper` link error. Consider using `--config cross` instead of `--config dev` (assuming you have the latter in your `.bazelrc.user`).

If you don't want to do that, installing the `libresolv-wrapper` package is an option. (If you are on Ubuntu 22.04, this is not an option.)

Removing `-lresolv_wrapper` from `pkg/ccl/gssapiccl/BUILD.bazel` is another option.

**Comment by emilaleksanteri** [comment]
@rickystewart woohoo it worked, thank you very much! It was the `.bazelrc.user`

**Review by maryliag — APPROVED** [review]
Awesome! :lgtm: 

I'll go ahead and merge it!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111594#-:-Nfpd3Sm86ESHGoP4MJ5:b-v7ynou)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @emilaleksanteri)

**Comment by emilaleksanteri** [comment]
@maryliag woohoo sounds good!!

**Pull request merged**
