### PR TITLE
sql: add option to alter primary key to an interleaved primary key

### PR DESCRIPTION
**Pull request by rohany**
This PR adds the ability to switch the primary key
of a table to another primary key, while interleaving
the new primary key into another table.

The new syntax looks like
```
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (x, y) INTERLEAVE IN PARENT t2 (x)
```

Release note (sql change): This PR adds the abiilty to alter the primary
key of a table to one that is interleaved in another table.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
Delighted this PR is as small as it is. Let's add a bit more testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44038#-:-Lyf6Jhe--dOdjMj5Z_B:b-1unc82)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44038#-Lyf4py03ZjNjKEELfge:-Lyf4py03ZjNjKEELfgf:b-r8k74o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8806f855db3307597563747b3c77bb3ccb0febcf/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L68)):*
> ```
> ----
> 1 2 3
> 4 5 6
> ```

I wonder if these tests could probe a bit deeper. They would still basically pass if INTERLEAVE IN PARENT were treated as a no-op here. Can you test that these tables have more properties we expect from an interleaved relationship? Maybe like checking the ranges in a trace, or checking that you can't truncate the parent table without CASCADE, stuff like that. Don't worry about going overboard but let's get a bit more coverage.

**Comment by rohany** [comment]
PTAL

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44038#-LyfIH8uC_nTBLizG4w6:-LyfIH8v8bm7OngJjqg4:b-gpe5kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b40a335bc1b5f8398f4f2e34a3598fbc02125f8/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L83)):*
> ```
> 
> statement ok
> DROP TABLE parent CASCADE
> ```

Might as well check that `child` was dropped.

**Comment by rohany** [comment]
Testing this helped uncover #44068

**Comment by rohany** [comment]
I think this is a flake

bors r+

**Pull request merged**
