### PR TITLE
sql/sem/builtins: fix span double finish

### PR DESCRIPTION
**Pull request by andreimatei**
The tracing span was finished twice on the error path, which is illegal.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82532)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82532#-N3zI6iA4MWsDmBYWORi:-N3zI6iA4MWsDmBYWORj:b-6yqmc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d29e5c0713ff6b2deeda7bdbdcc4b5f788698/pkg/sql/sem/builtins/generator_probe_ranges.go#L157)):*
> ```Go
> 		})
> 		if err != nil {
> 			return nil, errors.Wrapf(err, "%s", sp.FinishAndGetConfiguredRecording().String())
> ```

I'm pretty sure `Wrapf` is not the right thing to use here, but I don't know what is. `Wrapf` is supposed to take a relatively small message. Here the trace will probably completely obscure the error.
There's `errors.WithDetail`, but then the detail only gets printed if the error is rendered with `%+v`. I doubt that a SQL client gets a `%+v` rendering.
Perhaps we should implement our own error type to control the rendering.
@knz what's the right thing to do?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82532)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @Santamaura)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82532#-N3zI6iA4MWsDmBYWORi:-N3zJBnEAE-7vFRle3x9:bh2lbe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d29e5c0713ff6b2deeda7bdbdcc4b5f788698/pkg/sql/sem/builtins/generator_probe_ranges.go#L157)):*
> There's errors.WithDetail,  I doubt that a SQL client gets a %+v rendering.

It doesn't get a %+v rendering, but it gets the details! (as a pg DETAILS payload). So maybe the details is the right way to do this. Have you tried?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82532)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @Santamaura)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82532#-N3zI6iA4MWsDmBYWORi:-N3zU4UTElTNxNNK-y1V:b3m9ckx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d29e5c0713ff6b2deeda7bdbdcc4b5f788698/pkg/sql/sem/builtins/generator_probe_ranges.go#L157)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> There's errors.WithDetail,  I doubt that a SQL client gets a %+v rendering.

It doesn't get a %+v rendering, but it gets the details! (as a pg DETAILS payload). So maybe the details is the right way to do this. Have you tried?

</blockquote></details>

yup, neato. Massaged this a bit and now it looks nice:
```
root@localhost:26257/defaultdb> select * from crdb_internal.probe_ranges(INTERVAL '1000ms', 'read') limit 1;
ERROR: error scanning meta ranges: !!! xxx
DETAIL: trace:
     0.000ms      0.000ms    === operation:meta2scan _verbose:1 client:127.0.0.1:40314 node:1 user:root
     0.009ms      0.009ms        === operation:txn coordinator send _verbose:1 client:127.0.0.1:40314 node:1 txnID:fa023bd2-91e3-4a75-94af-a07e537724ef user:root
     0.018ms      0.008ms            === operation:dist sender send _verbose:1 client:127.0.0.1:40314 node:1 txn:fa023bd2 user:root
     0.072ms      0.054ms            event:kv/kvclient/kvcoord/range_iter.go:175 [n1,client=127.0.0.1:40314,user=root,txn=fa023bd2] querying next range at /Meta2/"\x00"
     0.124ms      0.053ms            event:kv/kvclient/kvcoord/dist_sender.go:2032 [n1,client=127.0.0.1:40314,user=root,txn=fa023bd2] r1: sending batch 1 Scan to (n1,s1):1
     0.141ms      0.017ms            event:rpc/nodedialer/nodedialer.go:161 [n1,client=127.0.0.1:40314,user=root,txn=fa023bd2] sending request to local client
     0.147ms      0.005ms                === operation:/cockroach.roachpb.Internal/Batch _verbose:1 node:1 span.kind:server
...
```

This code was also broken - it had a double finish in the error case, which I've now fixed in a prepended commit. PTAL.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82532)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @Santamaura)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82532#-:-N44JdiSEapl9eNOi7L8:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @Santamaura)

**Pull request merged**
