### PR TITLE
kvserver: maybe deflake TestStoreRangeMergeSlowWatcher

### LINKED ISSUE #58750: kv/kvserver: TestStoreRangeMergeSlowWatcher timed out
[(kv/kvserver).TestStoreRangeMergeSlowWatcher failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2574679&tab=buildLog) on [master@63fba7f1ab321088619d04aa9a44e61d018016f6](https://github.com/cockroachdb/cockroach/commits/63fba7f1ab321088619d04aa9a44e61d018016f6):

```
Slow failing tests:
TestStoreRangeMergeSlowWatcher - 960.21s

Slow passing tests:
TestLogic - 626.36s
TestTenantLogic - 435.98s
TestRestoreMidSchemaChange - 86.46s
Example_demo - 83.71s
TestImportIntoCSV - 82.20s
TestScatterRandomizeLeases - 67.50s
TestImportCSVStmt - 66.97s
TestPaginatedBackupTenant - 59.86s
TestRemoveDeadReplicas - 58.21s
TestExecBuild - 56.94s
TestRaceWithBackfill - 55.38s
TestChangefeedSchemaChangeNoBackfill - 55.17s
TestBTreeDeleteInsertCloneEachTime - 52.36s
TestImportData - 48.77s
TestAllRegisteredSetup - 46.20s
TestTelemetry - 45.91s
TestChangefeedNoBackfill - 44.55s
TestFullClusterBackup - 44.34s
TestChangefeedDiff - 42.89s
TestTransientTxnErrors - 41.33s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestStoreRangeMergeSlowWatcher PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestStoreRangeMergeSlowWatcher.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
This test seems to have a rare deadlock in which the cond is already
signaled but the merge watcher isn't already receiving from the cond.
The result is that the test hangs indefinitely, which is a pretty bad
failure mode.

I don't claim to have taken the time to understand the test flake, but
by signaling the cond repeatedly once it is out of the picture, we can
hopefully avoid the flake.

A real fix would likely entail not using a `sync.Cond` (which is prone
to deadlocks) in this test, but refactoring this test is nontrivial.

Closes #58750.

cc @cockroachdb/kv

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/client_merge_test.go, line 3630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-MYtRNzxA4630nztG6WZ:-MYtRNzxA4630nztG6W_:bokvtav) ([raw file](https://github.com/cockroachdb/cockroach/blob/293166cdab07deea34ffb0629052343724a702eb/pkg/kv/kvserver/client_merge_test.go#L3630)):*
> ```Go
> 			}
> 		}
> 	})
> ```

Perhaps use an unbuffered channel here instead? Namely, block by reading from the chan in testingRequestFilter above and then close the channel here where we were previously calling cond.Signal()? 

I suppose this reminds us that there is some yet-to-be diagnosed problem though.

**Review by nvb — COMMENTED** [review]
Thanks for deflaking!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-:-MYu8wBD5Agdwm8Tw9to:bhhz3h5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/kv/kvserver/client_merge_test.go, line 3630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-MYtRNzxA4630nztG6WZ:-MYu89GX6exRAFoAJfB5:bqcql4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/293166cdab07deea34ffb0629052343724a702eb/pkg/kv/kvserver/client_merge_test.go#L3630)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Perhaps use an unbuffered channel here instead? Namely, block by reading from the chan in testingRequestFilter above and then close the channel here where we were previously calling cond.Signal()? 

I suppose this reminds us that there is some yet-to-be diagnosed problem though.
</blockquote></details>

Yeah, this is what I was thinking as well. That would also avoid the need to work around the possibility of the merge transaction restarting up above.

I don't quite understand what the test in trying to demonstrate, but it seems like it's just trying to block the watcher for some period of time, and then let it proceed. I don't think it's important that the watcher only ever pushes once (for whatever reason). Seems like that's coupling this test to the behavior of pushing transactions.

**Review by tbg — COMMENTED** [review]
`Cond` is gone, PTAL.

> Dismissed @stevendanna from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-:-MZSmkYu6x4tVagNlQfW:b-zd3b4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 3630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-MYtRNzxA4630nztG6WZ:-MZSmn7c2WxvZrdJvwIO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293166cdab07deea34ffb0629052343724a702eb/pkg/kv/kvserver/client_merge_test.go#L3630)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, this is what I was thinking as well. That would also avoid the need to work around the possibility of the merge transaction restarting up above.

I don't quite understand what the test in trying to demonstrate, but it seems like it's just trying to block the watcher for some period of time, and then let it proceed. I don't think it's important that the watcher only ever pushes once (for whatever reason). Seems like that's coupling this test to the behavior of pushing transactions.
</blockquote></details>

Done.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64058)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-MZSujbVDfpzA60yDqzL:-MZSujbVDfpzA60yDqzM:b-qd6vlx) (no related file):*
:lgtm: I've left one comment for what looks to be another possible simplification; but feel free to ignore it if I've missed something there.

---
___
*[pkg/kv/kvserver/client_merge_test.go, line 3529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-MZSu4CDBV-QjfOIRMki:-MZSu4CDBV-QjfOIRMkj:brxp4kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6393825ef574a22ad22f005e514f981c06a55c3/pkg/kv/kvserver/client_merge_test.go#L3529)):*
> ```Go
> 				// through so that it allows traffic on the range again. We'll try again
> 				// with the restarted merge transaction.
> 				stopDelayingPush()
> ```

Do we need this loop at all anymore with this new structure?  It was required before because cond.Wait() relocks after returning so subsequent calls also block.  Here the read on delayPushCh will always return nil once it is closed?

**Review by tbg — COMMENTED** [review]
bors r=stevendanna

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-:-MZXqffG6pdMMP0Aa5KC:b-7jq173)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @stevendanna, and @tbg)

___
*[pkg/kv/kvserver/client_merge_test.go, line 3529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64058#-MZSu4CDBV-QjfOIRMki:-MZXpqIfEBp6s5SiuWA6:b-ixdqe9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6393825ef574a22ad22f005e514f981c06a55c3/pkg/kv/kvserver/client_merge_test.go#L3529)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we need this loop at all anymore with this new structure?  It was required before because cond.Wait() relocks after returning so subsequent calls also block.  Here the read on delayPushCh will always return nil once it is closed? 
</blockquote></details>

I'm not sure. If the merge restarts and gets stuck on the delayed pusher, the test will deadlock before reaching the main `stopDelayingPush()` call. I might be wrong here, too.

**Pull request merged**
