### PR TITLE
server: create gauge metric for license expiry tracking

### LINKED ISSUE #71525: metrics: `seconds_until_enterprise_license_expiry` needs accompanying HELP and TYPE lines
Metrics in `/_status/vars` contain a `HELP` and `TYPE` line. However, the metric `seconds_until_enterprise_license_expiry` is missing those lines. We'd like to add those for this metric

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, the license expiry metric was manually appended to the
Prometheus output resulting in some unexpected behavior. First, the
expected Prometheus metadata that accompanies other metrics did not
accompany this metric. Second, the metric was unavailable in the DB
Console for viewing in custom graphs.

This change updates the license expiry metric to use the standard
`Metric` types and API. The metric is updated using a callback attached
to the cluster setting.

Resolves: cockroachdb#71525

Release note (ops change): The license expiry metric is now available in
the DB Console and includes the expected `HELP` and `TYPE` annotations
in the promtheus output on `_status/vars`.

### CODE REVIEW

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @rimadeodhar)

___
*[pkg/base/license.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MmUlnWD3dC_9Yff8yBz:-MmUlnWE353lKtVwgZmD:b-gt3y6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/159c571c23a746822e82ac9a0131e5ca22e25ec2/pkg/base/license.go#L58)):*
> ```Go
> }
> 
> func UpdateTimeToLicenseExpiry(ctx context.Context, sv *cluster.Settings, asOf time.Time) {
> ```

Nit: Will need to add a comment for this exported function.
___
*[pkg/server/server.go, line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MmUkze85qBnJymx0euT:-MmUkze9BgPkrm8BN-2c:b-qa00xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/159c571c23a746822e82ac9a0131e5ca22e25ec2/pkg/server/server.go#L1654)):*
> ```Go
> 
> 	// TODO(davidh): where to place this that makes sense?
> 	s.registry.AddMetric(base.LicenseTTL)
> ```

Seems fine to keep this here.

**Review by dhartunian — COMMENTED** [review]
@rimadeodhar please take another look. I took the much better approach of updating a metric via a callback on the setting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-:-Mna7tExDsT25nBIOq0G:b-twm3uy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[pkg/base/license.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MmUlnWD3dC_9Yff8yBz:-Mmrm7koBhqgFt0PyFnQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/159c571c23a746822e82ac9a0131e5ca22e25ec2/pkg/base/license.go#L58)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: Will need to add a comment for this exported function.
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MmUkze85qBnJymx0euT:-Mna7nZG85kLZXkTPKqs:b-2herev) ([raw file](https://github.com/cockroachdb/cockroach/blob/159c571c23a746822e82ac9a0131e5ca22e25ec2/pkg/server/server.go#L1654)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Seems fine to keep this here.
</blockquote></details>

Moved everything around so this is no longer relevant.

**Review by rimadeodhar — APPROVED** [review]
:lgtm:. Some minor nits but seems ready to go. 

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-:-MnbyAG-7ZYF_3nMcmjq:bj74e5m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[-- commits, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MnbuMdA9Q-cPAjOjqGy):*
Could you also update this on the PR message in GH? Seems like that hasn't gotten updated with this new information.
___
*[pkg/base/license.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-Mnbw3kBDhkDgLvzBc5Q:-Mnbw3kBDhkDgLvzBc5R:btar4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/edbd521ffe1689808f0b43e1867e81d70e5980df/pkg/base/license.go#L49)):*
> ```Go
> // in order to connect the enterprise license setting update to the
> // prometheus metric defined above.
> var RegisterLicenseExpiryCallback = func(st *cluster.Settings, ts timeutil.TimeSource) {}
> ```

Nit: This name seems a bit misleading. It seems to me that this callback actually updates the metric when the enterprise license setting is updated rather than registering anything. Maybe UpdateLicenseExpiryMetricCallback might be a better name?
___
*[pkg/ccl/utilccl/license_check.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MnbvHBS0NQs-E3qYkjD:-MnbvHBTBUQ5_tSD1AnR:b-nno3nz) ([raw file](https://github.com/cockroachdb/cockroach/blob/edbd521ffe1689808f0b43e1867e81d70e5980df/pkg/ccl/utilccl/license_check.go#L130)):*
> ```Go
> }
> 
> func RegisterLicenseExpiryCallback(st *cluster.Settings, ts timeutil.TimeSource) {
> ```

Nit: Not sure I like the idea of including `Callback` in the function name. I think the function should be named as per its functionality (maybe just `UpdateEnterpriseLicenseExpiry`), the fact that it is used as a callback seems orthogonal to what it actually does :shrug:.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rimadeodhar)

___
*[-- commits, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MnbuMdA9Q-cPAjOjqGy):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Could you also update this on the PR message in GH? Seems like that hasn't gotten updated with this new information.
</blockquote></details>

Done.
___
*[pkg/base/license.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-Mnbw3kBDhkDgLvzBc5Q:-MoKv8eE4R2pmdXoD-z6:bjsp346) ([raw file](https://github.com/cockroachdb/cockroach/blob/edbd521ffe1689808f0b43e1867e81d70e5980df/pkg/base/license.go#L49)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: This name seems a bit misleading. It seems to me that this callback actually updates the metric when the enterprise license setting is updated rather than registering anything. Maybe UpdateLicenseExpiryMetricCallback might be a better name?
</blockquote></details>

Changed name to `UpdateMetricOnLicenseChange`
___
*[pkg/ccl/utilccl/license_check.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MnbvHBS0NQs-E3qYkjD:-MoKeIem5ELeAayyyn8Y:b-rflu6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/edbd521ffe1689808f0b43e1867e81d70e5980df/pkg/ccl/utilccl/license_check.go#L130)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: Not sure I like the idea of including `Callback` in the function name. I think the function should be named as per its functionality (maybe just `UpdateEnterpriseLicenseExpiry`), the fact that it is used as a callback seems orthogonal to what it actually does :shrug:. 
</blockquote></details>

Renamed to `UpdateMetricOnLicenseChange` everywhere which seems a bit more straightforward

**Comment by dhartunian** [comment]
@rimadeodhar RFAL

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 2 of 7 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

___
*[pkg/ccl/utilccl/license_check.go, line 136 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MpmqJUd6CEKFEFPNxRu:-MpmqJUd6CEKFEFPNxRv:b3liplo) ([raw file](https://github.com/cockroachdb/cockroach/blob/38c0529e1e3a35453d14a8e8f717cc7f94ef189f/pkg/ccl/utilccl/license_check.go#L136)):*
> ```Go
> // UpdateMetricOnLicenseChange starts a task to periodically update
> // the given metric with the seconds remaining until license expiry.
> func UpdateMetricOnLicenseChange(
> ```

Why do we only need this in the CCL context?

**Review by rimadeodhar — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-:-MpmrF3g8TODeH-FU1Vo:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[pkg/ccl/utilccl/license_check.go, line 136 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-MpmqJUd6CEKFEFPNxRu:-MpqckiX70mARcU0cGS1:bm47lfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/38c0529e1e3a35453d14a8e8f717cc7f94ef189f/pkg/ccl/utilccl/license_check.go#L136)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Why do we only need this in the CCL context?
</blockquote></details>

Only CCL servers contain code that requires enterprise licenses.

**Comment by moogzy** [comment]
Hi there - any word on when this will be resolved?

The missing HELP/TYPE (the latter in particular) is causing our Datadog instance to not poll this metric. As Datadog appears to be relying on the TYPE field to map to it's metric types.

 As a side note - Cockroach documentation says this metric is ready for use.... which is why we started trying to poll it today. It's there in the metric export if you look at the `_status/vars` endpoint but because of this incomplete implementation it means engineer cycles are wasted troubleshooting, wondering why the docs say to poll this metric but it's not working for with their particular monitoring platform.
 
 I've raised this with our account contacts Paul Logan and Carolyn Parrish.
 
Documentation reference: https://www.cockroachlabs.com/docs/stable/licensing-faqs.html#monitoring-for-license-expiry

**Comment by dhartunian** [comment]
> Hi there - any word on when this will be resolved?

@moogzy Hi I'm working on getting this PR merged shortly and it will be in the next minor version of `21.2`, likely `21.2.4`.

**Comment by moogzy** [comment]
> > Hi there - any word on when this will be resolved?
> 
> @moogzy Hi I'm working on getting this PR merged shortly and it will be in the next minor version of `21.2`, likely `21.2.4`.

thanks @dhartunian - Looking forward to it!

**Review by abarganier — APPROVED** [review]
:lgtm:! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71740#-:-MqyqMpmCJvYe9UP9CAj:b593w6o)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rimadeodhar)

**Comment by dhartunian** [comment]
bors r=rimadeodhar,abarganier

**Pull request merged**
