### PR TITLE
sql: rewrite vectorize telemetry test

### LINKED ISSUE #50125: sql/logictest: TestLogic failed
[(sql/logictest).TestLogic failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2007156&tab=buildLog) on [master@296ceb7d2e1cfecc2ca70b06344309883064afd9](https://github.com/cockroachdb/cockroach/commits/296ceb7d2e1cfecc2ca70b06344309883064afd9):

```
=== RUN   TestLogic
--- FAIL: TestLogic (1109.73s)
    test_log_scope.go:77: test logs captured to: /tmp/logTestLogic698617766
    test_log_scope.go:58: use -show-logs to present logs inline
=== RUN   TestLogic/local/vectorize_telemetry
=== PAUSE TestLogic/local/vectorize_telemetry
=== CONT  TestLogic/local/vectorize_telemetry
rewrote:
CREATE TABLE b (id INT8, a_id INT8, FOREIGN KEY (a_id) REFERENCES a (id), FAMILY (id, a_id));


        --- FAIL: TestLogic/local/vectorize_telemetry (1.21s)
            logic.go:1981: 
                 
                testdata/logic_test/vectorize_telemetry:56: SELECT * FROM incremented_feature_names
                expected:
                    sql.exec.vectorized-setting.on
                    sql.exec.vectorized-setting.off
                but found (query options: "rowsort" -> ignore the following ordering of rows) :
                    sql.exec.vectorized-setting.on
                    
=== RUN   TestLogic/local
    --- FAIL: TestLogic/local (0.47s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestLogic PKG=./pkg/sql/logictest TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestLogic.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by asubiotto**
vectorize_telemetry has been rewritten in order to be run using TestTelemetry.

Release note: None (testing change)

cc @RaduBerinde 

Closes #50125

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50877#-:-MBAEDogAFC3u39AFOeD:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50877)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
TFTRs

bors r=RaduBerinde

**Comment by asubiotto** [comment]
Looks like the build failed because one of the dependencies was canceled (`Canceled with comment: Agent gce-agent-20200513-preempt-4 unregistered: Agent has unregistered`). Trying again

bors r=RaduBerinde

**Pull request merged**
