### PR TITLE
util/timeutil: test the concurrent usage of stop watch

### PR DESCRIPTION
**Pull request by yuzefovich**
We recently merged a fix to the stop watch to make it truly safe for the
concurrent usage. That commit was lacking a unit test which this commit
adds. The test exposes the previous bug immediately under race.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61885)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/util/timeutil/stopwatch_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61885#-MVbX65J5ct7bJ0FBuqD:-MVbX65J5ct7bJ0FBuqE:b-don621) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee69421d88d2c04a9a7317c2a61cf5976fe5472a/pkg/util/timeutil/stopwatch_test.go#L75)):*
> ```Go
> // TestStopWatchConcurrentUsage makes sure that the stop watch is safe for
> // concurrent usage.
> func TestStopWatchConcurrentUsage(t *testing.T) {
> ```

defer leaktest?
___
*[pkg/util/timeutil/stopwatch_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61885#-MVbXLkM2OUgdX-vbuZi:-MVbXLkM2OUgdX-vbuZj:b197hex) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee69421d88d2c04a9a7317c2a61cf5976fe5472a/pkg/util/timeutil/stopwatch_test.go#L91)):*
> ```Go
> 	var wg sync.WaitGroup
> 	for i := 0; i < numGoroutines; i++ {
> 		wg.Add(1)
> ```

nit: `wg.Add(numGoroutines)` before the loop

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61885)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/util/timeutil/stopwatch_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61885#-MVbX65J5ct7bJ0FBuqD:-MVbkWfi1NC19qB-CiM-:b-8hvw10) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee69421d88d2c04a9a7317c2a61cf5976fe5472a/pkg/util/timeutil/stopwatch_test.go#L75)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

defer leaktest?
</blockquote></details>

I also tried at first, but it was creating an import cycle with `leaktest`, so I removed it. On the second thought I moved this file into `timeutil_test` package.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61885)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/util/timeutil/stopwatch_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61885#-MVbX65J5ct7bJ0FBuqD:-MVbkWfi1NC19qB-CiM-:b-8hvw10) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee69421d88d2c04a9a7317c2a61cf5976fe5472a/pkg/util/timeutil/stopwatch_test.go#L75)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

defer leaktest?
</blockquote></details>

I also tried at first, but it was creating an import cycle with `leaktest`, so I removed it. On the second thought I moved this file into `timeutil_test` package.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61885#-:-MVpxvVw3p8zingro3JB:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
