### PR TITLE
rpc: validate SourceAddr at init

### PR DESCRIPTION
**Pull request by tamird**
Minor cleanup from the graveyard.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14124)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/rpc/context.go, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14124#-Kf8jaN0ld70o4_rx8hw:-Kf8jaN0ld70o4_rx8hx:b-bd6azd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfd11f1bded286b9dab94816335b7c08a5ba077/pkg/rpc/context.go#L69)):*
> ```Go
> 		sourceIP := net.ParseIP(sourceAddr)
> 		if sourceIP == nil {
> 			panic(fmt.Sprintf("unable to parse %s '%s' as IP address", envKey, sourceAddr))
> ```

We don't panic on failures to parse other environment variables ([example](https://github.com/cockroachdb/cockroach/blob/33a5d379a0b177ddfc7fcb94fc4fc397f247bf7e/pkg/util/envutil/env.go#L245)). This should be consistent with the functions in envutil.go. (I think I'd be OK with making all of the env parsing panic instead of failing with a log message)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14124#-:-Kf8k7aqh48sLq4rY4VW:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/rpc/context.go, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14124#-Kf8jaN0ld70o4_rx8hw:-Kf8l5M17XcC6FMd28mT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfd11f1bded286b9dab94816335b7c08a5ba077/pkg/rpc/context.go#L69)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We don't panic on failures to parse other environment variables ([example](https://github.com/cockroachdb/cockroach/blob/33a5d379a0b177ddfc7fcb94fc4fc397f247bf7e/pkg/util/envutil/env.go#L245)). This should be consistent with the functions in envutil.go. (I think I'd be OK with making all of the env parsing panic instead of failing with a log message)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14124)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14124#-:-Kf8lSevOnIlEpcuQJsl:bnfp4nl)*

**Review by a-robinson — COMMENTED** [review]
LGTM

**Pull request merged**
