### PR TITLE
admission: move WorkPriority into admissionpb.WorkPriority

### PR DESCRIPTION
**Pull request by otan**
This commit moves WorkPriority into a separate, smaller package to
reduce the dependencies on packages that only need the WorkPriority
constants.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
What about calling this `admissionpb`?

**Comment by otan** [comment]
done

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80893#-:-N16uJvu9stuPLMH2qdl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @msirek, and @otan)

___
*[`pkg/util/admission/admissionpb/doc.go` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80893#-N16uPPo1EHllZ3Tz5r5:-N16uPPo1EHllZ3Tz5r6:b-7aufko) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbcf4ac7ee128073563f7193be9f3accdf14546/pkg/util/admission/admissionpb/doc.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> // Package admissionwork contains the base types for the admission package.
> ```

linter says "Package admissionpb ..."

**Comment by otan** [comment]
bors r=ajwerner

**Comment by otan** [comment]
bors did it's job


bors r=ajwerner

**Comment by otan** [comment]
bors r=ajwerner

**Pull request merged**
