### PR TITLE
opt: execute SortOp

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: fix ORDER BY build problem

Fixing a bug when building `ORDER BY` which causes incorrect
projections.

Release note: None

#### opt: support for partialsort in execbuilder tests

Support partial sorting of rows for queries which guarantee a partial,
but not total order.

Release note: None

#### opt: execute SortOp

Support `SortOp` in the `execbuilder`.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675#-L7B3Pe6JsOn33TqWiYT:-L7B3Pe6JsOn33TqWiYU:bxoo6uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30d0e816f439642df9ec9850a4f02b6d4e89b70/pkg/sql/opt/exec/execbuilder/testdata/orderby#L173)):*
> ```
>  └── render          1  render  ·         ·          ("t.b", "t.a")  ·
>       │              1  ·       render 0  b          ·               ·
>       │              1  ·       render 1  a          ·               ·
> ```

Drive-by question: what's with the 2 levels of renders? Is that a temporary artifact, or something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675#-L7B3Pe6JsOn33TqWiYT:-L7B47a0XNW61yPP9WFP:b7bapgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30d0e816f439642df9ec9850a4f02b6d4e89b70/pkg/sql/opt/exec/execbuilder/testdata/orderby#L173)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Drive-by question: what's with the 2 levels of renders? Is that a temporary artifact, or something else?
</blockquote></details>

Yeah, it's temporary, I plan to make the code tweak any existing renderNode instead of adding one on top.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675#-L7B5AjSCRqpv0xhlWxh:-L7B5AjT5x5yCecedfLF:bcmsq7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30d0e816f439642df9ec9850a4f02b6d4e89b70/pkg/sql/opt/exec/execbuilder/relational_builder.go#L75)):*
> ```Go
> // node.
> func (ep *execPlan) getColumnOrdinal(col opt.ColumnIndex) exec.ColumnOrdinal {
> 	idx, ok := ep.outputCols.Get(int(col))
> ```

NIT: I use `ord` rather than `idx` when I'm dealing with ordinals, to make it easier to keep things straight.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675#-:-L7B64mUbtb05uQXOcx6:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675#-L7B5AjSCRqpv0xhlWxh:-L7B7HNDOeNKPyXDvggE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30d0e816f439642df9ec9850a4f02b6d4e89b70/pkg/sql/opt/exec/execbuilder/relational_builder.go#L75)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I use `ord` rather than `idx` when I'm dealing with ordinals, to make it easier to keep things straight.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23675)*

**Comment by RaduBerinde** [comment]
Updated. Added the fix for the optbuilder orderby bug and beefed up the execbuilder/orderby testcases.

**Comment by andy-kimball** [comment]
Looks good.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23675#-:-L7MZJ5F5f5Y8X5MVmSp:b-vs1pr4)*

**Pull request merged**
