### PR TITLE
sql: remove local ordinality

### PR DESCRIPTION
**Pull request by jordanlewis**
Now that it's got a distributed version, we can delete the local
implementation.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42596)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
The order of `planNode`s in `mustWrapNode` and `createPlanForNode` is now off-sync 😢

**Comment by jordanlewis** [comment]
😰 I'll send a PR

**Comment by yuzefovich** [comment]
While you're at it, it seems to me that `exportNode` is not in `mustWrapNode` while `virtualTableNode` is in it but not in `createPlanForNode`. What I'm saying is that the methods are out of sync :/

**Comment by jordanlewis** [comment]
Blah. This thing is terrible.

**Pull request merged**
