### PR TITLE
server, sql: surface session txnCount, recent txn fingerprints, active time

### PR DESCRIPTION
**Pull request by xinhaoz**
Finishing up Gerardo's PR, original review here: https://github.com/cockroachdb/cockroach/pull/80717

--------------------------------------------------
Partially addresses #74257.

Previously, the status server did not provide session details such as
total number of transactions executed, transaction fingerprint
IDs, and total active time. This change adds the aforementioned session
details to the `serverpb.Session` struct.

To track recently executed transaction fingerprint IDs, a FIFO cache
`TxnFingerprintIDCache` is introduced with its corresponding cluster
setting `TxnFingerprintIDBufferCapacity` to control the capacity. The
default capacity is set at 100 fingerprints.

The total number of transactions executed is filled using the existing
`txnCounter` from the `extraTxnState` in `connExecutor`. The total active
time is calculated by introducing a `timeutil.StopWatch` to the connection
executor, which is started and stopped when a transaction is started and
finished respectively.

Release note (api change): the `serverpb.Session` struct now has three
new fields: number of transactions executed, transaction fingerprint
IDs, and total active time.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3bG-Af6ZiwqrHa1DKA:-N3bG-Af6ZiwqrHa1DKB:b-rmizwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/60160c8cf77957142f65f824e6099701704d48d6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L371)):*
> ```
> SELECT * FROM crdb_internal.node_sessions WHERE node_id < 0
> ----
> node_id  session_id  user_name  client_address  application_name  active_queries  last_active_query  num_txns_executed  session_start  oldest_query_start  kv_txn  alloc_bytes  max_alloc_bytes status session_end
> ```

i feel like this might be less disruptive if the new column were added to the end, so the column ordering doesn't change as much. (would affect any users who are doing `select *` queries)

**Review by matthewtodd — APPROVED** [review]
:lgtm: mod a few questions and @rafiss's suggestion.

> Reviewed 6 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-:-N3uI5Sh6vjIUH7x4l1V:b-1sisy0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd, @rafiss, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 2904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uA4tbC3tuGnRjDRNY:-N3uA4tc1WLh4Al0S-_o:bdubvty) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/sql/conn_executor.go#L2904)):*
> ```Go
> 		ex.extraTxnState.txnCounter++
> 
> 		// Session is considred active when executing a transaction.
> ```

nit: typo in "considred"
___
*[`pkg/sql/txn_fingerprint_id_cache.go` line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uEcp46e0MzuMDj-UF:-N3uEcp46e0MzuMDj-UG:b9b783) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/sql/txn_fingerprint_id_cache.go#L77)):*
> ```Go
> }
> 
> // Add adds a TxnFingerprintID to the cache, truncating the cache to the
> ```

nit: looks like this sentence got truncated?
___
*[`pkg/sql/txn_fingerprint_id_cache.go` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uFztg4qSxc7nT9-lU:-N3uFztg4qSxc7nT9-lV:bmvqmx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/sql/txn_fingerprint_id_cache.go#L92)):*
> ```Go
> 
> // GetAllTxnFingerprintIDs returns a slice of all TxnFingerprintIDs in the cache.
> // The cache may be truncated if the capacity was updated to a smaller size.
> ```

nit: I wonder if it would be sufficient to just let adding to the cache handle eviction, WDYT?
___
*[`pkg/util/timeutil/stopwatch.go` line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uGGQsBzpUESQrOuVn:-N3uGGQt48RrPVkTPlqX:b-inzf2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/util/timeutil/stopwatch.go#L90)):*
> ```Go
> 	w.mu.Lock()
> 	defer w.mu.Unlock()
> 	return w.mu.started, w.mu.startedAt
> ```

nit: Would it feel more idiomatic to reverse the order of these return parameters, like the `v, ok` when getting from a map?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82352)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @matthewtodd and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 2904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uA4tbC3tuGnRjDRNY:-N4YCgoJ314YboO8enjh:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/sql/conn_executor.go#L2904)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: typo in "considred"
</blockquote></details>

Fixed.
___
*[`pkg/sql/txn_fingerprint_id_cache.go` line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uEcp46e0MzuMDj-UF:-N4YGdMs3RFaT3hJMft8:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/sql/txn_fingerprint_id_cache.go#L77)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: looks like this sentence got truncated?
</blockquote></details>

Fixed.
___
*[`pkg/sql/txn_fingerprint_id_cache.go` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uFztg4qSxc7nT9-lU:-N4YD43n0_5CKx1vxN8z:b5wd3er) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/sql/txn_fingerprint_id_cache.go#L92)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: I wonder if it would be sufficient to just let adding to the cache handle eviction, WDYT?
</blockquote></details>

Yeah, the rate at which txn fingerprints are added in a real workload might be sufficient for ensuring the cache eventually gets resized appropriately. But in the off chance where none are inserted between a change in capacity and a retrieval of fingerprint ids, are we okay with the number of returned ids being greater than the cache's newly set capacity? I'm also not sure how often sessions become idle for extended periods of time in practice.
___
*[`pkg/util/timeutil/stopwatch.go` line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3uGGQsBzpUESQrOuVn:-N4YEuTo3jSCp6I2Lzfq:b-16pqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dd1f55533203e99e406b3ccf6dac51891377b19/pkg/util/timeutil/stopwatch.go#L90)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Would it feel more idiomatic to reverse the order of these return parameters, like the `v, ok` when getting from a map?
</blockquote></details>

Ah good suggestions! Done. I also changed the name of this function to more accurately reflect what it returns.
___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N3bG-Af6ZiwqrHa1DKA:-N4YGb8gBUm3ZoypaZqU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60160c8cf77957142f65f824e6099701704d48d6/pkg/sql/logictest/testdata/logic_test/crdb_internal#L371)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i feel like this might be less disruptive if the new column were added to the end, so the column ordering doesn't change as much. (would affect any users who are doing `select *` queries)
</blockquote></details>

Done.

**Review by abarganier — APPROVED** [review]
Not much to add on top of what others said aside from a lingering merge conflict artifact. :lgtm: otherwise!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-:-N4cB9SM-CCzACXzgVy2:bcfgub3)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @matthewtodd, @rafiss, and @xinhaoz)

___
*[`docs/generated/settings/settings-for-tenants.txt` line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82352#-N4c9N08CFKv2Tou0FQM:-N4c9N08CFKv2Tou0FQN:b-dsnwhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8beb1b127465c9e849c753ccb7ed352247b26b0d/docs/generated/settings/settings-for-tenants.txt#L276)):*
> ```help
> sql.ttl.default_select_batch_size	integer	500	default amount of rows to select in a single query during a TTL job
> sql.ttl.job.enabled	boolean	true	whether the TTL job is enabled
> <<<<<<< HEAD
> ```

nit: Lingering artifacts from merge conflict?



_Code quote:_
```help
<<<<<<< HEAD
=======
sql.ttl.range_batch_size	integer	100	amount of ranges to fetch at a time for a table during the TTL job
sql.txn_fingerprint_id_cache.capacity	integer	100	the maximum number of txn fingerprint IDs stored
>>>>>>> 4dd1f55533 (server, sql: surface session txnCount, txn fingerprints, active time)
```

**Comment by xinhaoz** [comment]
Thanks everyone for the reviews!
bors r+

**Pull request merged**
