### PR TITLE
WIP: sql: Add Pow to decimal

### PR DESCRIPTION
**Pull request by seiflotfy**
Using the concept of power series to represent e^x where
x = b *ln(a), which implies  a^b = e^(b *ln(a))
This is then used to represent the series

```
    res = 0
    for i in xrange(100):
        res += math.pow(b * math.log(a), i) / math.factorial(i)
    return res
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5827)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[util/decimal/decimal.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcySSQKgSzYtwbS2l:-KERcySSQKgSzYtwbS2m:-2103588709) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L336)):*
would it make sense to have special handling for the case when y is a positive integer? (maybe just use ppow in that case?)

---

*[util/decimal/decimal.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcDMLZC8FUiVGMhDk:-KERcDMLZC8FUiVGMhDl:677525581) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L359)):*
bla?

---

*[util/decimal/decimal.go, line 362 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcTtiAtncpDytFORM:-KERcTtiAtncpDytFORN:-1993516001) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L362)):*
Maybe this can be made into a separate Exp function which could be useful on its own?

---

*[util/decimal/decimal.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERaUMF-QIb9uF-UElE:-KERaUMG7UOYpRbD9TMn:-915712683) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L365)):*
The number of rounds should depend on the amount of precision we want. Check out `newLoop`

---

*[util/decimal/decimal.go, line 367 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERdxH0alCaoYnWEmQt:-KERdxH0alCaoYnWEmQu:-2069671253) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L367)):*
instead of using `ppow` and `fac` every time, why don't we just take the last term (`tmp`), multiply it by `bla` and divide it by `i`?  `x^n/n! = (x^(n-1)/(n-1)!) * x / n`

---

*[util/decimal/decimal.go, line 376 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERbg9z-CrvZ0Grl64C:-KERbgA-mCajTS2Tj-c0:1974726084) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L376)):*
It looks like this internal function is always used with an integer y, why not pass it as an int?

---

*[util/decimal/decimal.go, line 396 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERbxNxnrrqwaOiZqOB:-KERbxNxnrrqwaOiZqOC:-412891305) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L396)):*
we could do this in log2(u) steps instead of u

---

*[util/decimal/decimal.go, line 405 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERbmGJnZmlx_yafEUu:-KERbmGJnZmlx_yafEUv:-24733064) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L405)):*
I would make `x` int here too..

---

*[util/decimal/decimal.go, line 417 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERdETpsCYdpbtUfKmh:-KERdETq9aJFyKH3sRHu:-1166794069) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L417)):*
should start at 2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[util/decimal/decimal.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KES1_jFeLpEgwpR8tvu:-KES1_jFeLpEgwpR8tvv:-1980375916) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L365)):*
This series needs many iterations if `bla` is large - specifically `O(bla)` because `n` has to be bigger by `bla` by a factor to make the terms small. E.g. if we want to compute e^1000, the 1000th term is `1000^1000 / 1000!` which is still huge (about `10^432`).

It would be better if we could write the exponent as a product `xy` where `x` is integer and `y < 1`, use the series to compute `e^y`, then use repeated exponentiation to compute `(e^y)^x` in `log x` steps.

Instead of reinventing the wheel though we should look at what methods for exponentiation other large number libraries use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcDMLZC8FUiVGMhDk:-KESugD9ap0rIP07vfh1:378618349) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L359)):*
bloga (just noticed how wrong bla sounded)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcDMLZC8FUiVGMhDk:-KESugD9ap0rIP07vfh1:378618349) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L359)):*
bloga (just noticed how wrong bla sounded)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 367 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERdxH0alCaoYnWEmQt:-KESv-cXOtwFqdQJX0FB:708609716) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L367)):*
yeah was going for that now in the second iteration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 367 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERdxH0alCaoYnWEmQt:-KESv-cXOtwFqdQJX0FB:708609716) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L367)):*
yeah was going for that now in the second iteration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcySSQKgSzYtwbS2l:-KET-d4Azy4-lrGwzR8E:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L336)):*
+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcySSQKgSzYtwbS2l:-KET-d4Azy4-lrGwzR8E:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L336)):*
+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
If https://github.com/cockroachdb/cockroach/pull/5831 lands I can reuse it partially for this PR I guess

**Comment by nvanbenschoten** [comment]
Hey @seiflotfy, thanks for the contribution! Would you mind adding tests and benchmarks for this new functionality? Check out `decimal_test.go` to get an idea of how most of these have been done so far.

---

Review status: 0 of 2 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[util/decimal/decimal.go, line 334 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KEWdKeOVz69IFYlxnea:-KEWdKePLxiAYlnigh2P:1374881238) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L334)):*
Do you mind using the corresponding parameter names here? It would make things a lot clearer.

---

*[util/decimal/decimal.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KEWhP18k1Je6oZTBenL:-KEWhP18k1Je6oZTBenM:1771794609) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L336)):*
Can we define this "working" scale in a different variable so we dont have to divide it back out at the end?

---

*[util/decimal/decimal.go, line 355 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KEWhqwv1DpTSw5zPb16:-KEWhqwv1DpTSw5zPb17:-1511571192) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L355)):*
Is this correct? `(-2)^2 != -(2^2)`

---

*[util/decimal/decimal.go, line 358 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KEWiTGdjUpACAZOelFc:-KEWiTGdjUpACAZOelFd:175585422) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L358)):*
Could you leave a comment about why you are setting the scale here? I'm a little confused what your intention is.

---

*[util/decimal/decimal.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERcDMLZC8FUiVGMhDk:-KEWiDl78m0DqiI8kyto:747113066) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L359)):*
Is this a term I'm just not familiar with?

---

*[util/decimal/decimal.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERaUMF-QIb9uF-UElE:-KEWcTIjjTmjf76Eacl7:1027586579) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L365)):*
Right, `loop` is helpful in making sure we converge to an arbitrary provided amount of precision.

---

*[util/decimal/decimal.go, line 366 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KEWdy6FvdPRF3WOWwTk:-KEWdy6FvdPRF3WOWwTl:1898880585) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L366)):*
We really need to avoid allocating within this loop. I'd take a look at trying to pull these into temp variables that we can reuse for each iteration, and also double check that we need all of these to begin with. 

To a further extent, we should probably even expose optional temp parameters to `ppow` and `fac` if we're planning on delegating most of the work to them. Bottom line though is that allocating within our convergence loop is going to kill performance.

---

*[util/decimal/decimal.go, line 375 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KEWe_JBbl8zAdm4j3Gp:-KEWe_JBbl8zAdm4j3Gq:1265389071) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L375)):*
s/pow/ppow/

---

*[util/decimal/decimal.go, line 405 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KERbmGJnZmlx_yafEUu:-KEWfUEMfHatRq8zpvVb:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L405)):*
+1

---

*[util/decimal/decimal.go, line 421 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KEWff8j9Yby-du6tJeE:-KEWff8j9Yby-du6tJeF:-162242889) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L421)):*
Why not do this above and use `z` instead of `tmp` as the accumulator in the loop?

We should still use `tmp` variable to avoid allocating the multiplier each time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-:-KEWcpGMesq0e2MJwQwG:-554535550)*

**Comment by seiflotfy** [comment]
*[util/decimal/decimal.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827#-KES1_jFeLpEgwpR8tvu:-KEY2siz1Axn-tthMR78:-603157364) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2e30c6e7cd9651cbe49962e0341f8936a32f00/util/decimal/decimal.go#L365)):*
So this is what we have now i split xy to look as follows ==> if xy = 2.1  ==> y = 0.21  x = 10. so it does work but not sure it is efficient

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5827)*

**Comment by seiflotfy** [comment]
I was thinking of using x^y = e^y(lnx) but that seems to deliver very inaccurate results for higher ys.
Maybe we should fall back to Taylor series?

**Pull request closed without merging**
