### PR TITLE
acceptance: add flyway 6.0.0-beta test

### PR DESCRIPTION
**Pull request by madelynnblue**
Use docker-compose to set up a simple flyway test. This will allow us
to verify that changes to our virtual tables or other operations don't
break their basic functionality.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
The overall structure of the patch is OK, but are you comfortable with so few tests? This suggests me we should have a more diverse combination of types, using DEFAULT expressions, precision on DECIMAL, etc.

**Comment by mjibson** [comment]
I'm completely comfortable with such few tests because before we had nothing. If we find things that are broken we can add them over time. It is not currently a goal that we ensure flyway works completely. That's their job. My intuition is that it's the init and basic migrations that will fail. That is, I'm much less worried about edge cases as I am just basic functionality.

**Comment by knz** [comment]
Ok I agree with making one step forward now on this.
However I do want to point out we want more tests even if the flyway team is helping us. This is because we also want to catch the kind of regression that has hit us last week with TypeORM.

**Comment by mjibson** [comment]
Yes, I also want more tests in general. However I'm currently ok with adding tests retroactively (that is, when a bug is found) since I don't want to come up with all of the kinds of things we want to test for.

**Comment by knz** [comment]
Yes sure, go ahead.

**Pull request merged**
