### PR TITLE
server: separate SQL statistics from being refreshed with telemetry

### PR DESCRIPTION
**Pull request by rohany**
This PR fixes the issue that SQL statement statistics
are refreshed when telemetry is reported.

To do this, this PR introduces a new statistics
pool for statistics to be reported to telemetry.
Whenever the SQL stats are reset, they are first
dumped into the reporting pool. The telemetry
reporter then takes the statistics that have been
aggregated so far and reports them whenever it executes.
This has the effect of telemetry only reporting SQL
stats at the rate of max(sql_refresh_rate, telemetry_report_rate).

Release note (sql change): This PR introduces a new cluster
setting to control the rate at which SQL statement statistics
are refreshed, `diagnostics.sql_stat_reset.interval`. Additionally
it renames the setting `diagnostics.forced_stat_reset.interval` to
`diagnostics.forced_sql_stat_reset_interval`.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Cool I like this approach.

You'll need to write some testing before this can merge though.

Also:

> This has the effect of telemetry only reporting SQL
stats at the rate of max(sql_refresh_rate, telemetry_report_rate).

I don't believe this sentence is consistent with the rest of the text (and with the code). I'd recommend re-phrasing.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-:-M-znRXFERPDJSIcVj54:bxva51g)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rohany** [comment]
Added a test, PTAL!

**Review by knz — COMMENTED** [review]
ok for the test but now the behavior got me a little bit confused.

As I am reading the code now, I am imagining the following behavior: 

- user opens admin UI, fiddles with the "reset" button to calibrate some experiment (they want to clear the stats, then start their app, then look at what happens)
- a few seconds after they start their experiment, the telemetry loop activates and flushes the sql stats
- user doesn't see all the data they wanted in the admin UI and gets confused

Was this intentional? 

Somehow I was working under the impression that the SQL-side reset would be the only place that pushes data to telemetry. The telemetry loop could pick up data from what SQL has pushed away, without ever triggering the SQL push on its own.

Also, separately from the above I strongly suggest a maximum value on the reset interval, for example 24 hours.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-:-M03ABLb5NyPY1eJ494m:bl5nwpx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/roachpb/app_stats.proto, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-M039WRMAQJZcsADBLt5:-M039WRN4YneE8-NsZhJ:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/fde8374f6a5835bf506126980665bbb23bf9e6d1/pkg/roachpb/app_stats.proto#L102)):*
> ```protobuf
> 
> // N.B. When this changes, make sure to update (*NumericStat).AlmostEqual
> // in app_stats.go.
> ```

:100: 
___
*[pkg/server/stats_test.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-M039g273AgAT4Uib36t:-M039g273AgAT4Uib36u:b-4w6iom) ([raw file](https://github.com/cockroachdb/cockroach/blob/fde8374f6a5835bf506126980665bbb23bf9e6d1/pkg/server/stats_test.go#L49)):*
> ```Go
> 	}
> 
> 	// Collect stats from the SQL Server and ensure our queries are present.
> ```

SQL server (no capital needed - "SQL Server" is a different product)

**Comment by rohany** [comment]
> a few seconds after they start their experiment, the telemetry loop activates and flushes the sql stats

Where are you seeing this? The telemetry loop touch the SQL stats at all.

> Also, separately from the above I strongly suggest a maximum value on the reset interval, for example 24 hours.

Theres a max reset interval in here for both the sql stats and reported stats of 2 hours -- i can bump this up though.

**Review by knz — COMMENTED** [review]
> Where are you seeing this? The telemetry loop doesn't touch the SQL stats at all.

Sorry I mis-read the code. It would help to show a test that does the telemetry at a high frequency with a fake server (say, every 20ms) and demonstrate that the app stats in SQL are preserved when this happens.

> Theres a max reset interval in here for both the sql stats and reported stats of 2 hours -- i can bump this up though.

Yes I  think admin UI users will be thankful to have the option to increase up to a day.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-:-M03EqGP06KMw1J4lIfc:b-1exmcq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
| Yes I think admin UI users will be thankful to have the option to increase up to a day.

Do we want this though? Most of the comments around this area seem to be wary of the memory build up of the stats with the 2 hour window.

**Comment by knz** [comment]
The default should remain 1 hour or less.
However if the users has a lot of RAM maybe they want more. Remember this entire effort is to enable users to see more data in the web UI. If they truly want a lot of data, we don't have to block them.

**Comment by rohany** [comment]
Added a test. I think I misunderstood your comment re reset intervals earlier -- I made the maximum value for the reset intervals 24 hours.

**Comment by rohany** [comment]
Friendly ping.

**Review by knz — APPROVED** [review]
LGTM with nits

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-:-M0rrTmBExbSsbqhPGE9:b3nilp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/server/stats_test.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-M0rqzFx-KrghoMDZK3p:-M0rqzFyDe53DPoZYv4T:b9szppi) ([raw file](https://github.com/cockroachdb/cockroach/blob/59daf8d068710494debbbcb28545ecb02c859d42/pkg/server/stats_test.go#L49)):*
> ```Go
> 	// Run a bunch of queries in a loop, and request telemetry in a loop.
> 	// At the end, ensure that SQL statistics are unaffected by telemetry.
> 	var wg sync.WaitGroup
> ```

As much as I love wait groups and goroutines, this test does not need them. You can interleave 4 calls as follows:
1. insert
2. maybe report diagnostics
3. insert
4. maybe report diagnostics

and check that you still have the 2 inserts at the end.
___
*[pkg/settings/duration.go, line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45082#-M0rrGh-0iSEnLKQbX1A:-M0rrGh-0iSEnLKQbX1B:b25fmj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/59daf8d068710494debbbcb28545ecb02c859d42/pkg/settings/duration.go#L120)):*
> ```Go
> // RegisterPublicNonNegativeDurationSettingWithMaximum defines a new setting with
> // type duration, makes it public, and sets a maximum value.
> func RegisterPublicNonNegativeDurationSettingWithMaximum(
> ```

I don't dislike this new helper, but then I would request that you grep for all the other calls to `Register.*DurationSetting` throughout the code and ensure that the other few that also use a maximum also use your new helper.

Or file an issue and tag it "easy" / "good first issue".

**Comment by rohany** [comment]
It doesn't look like there are other duration settings with maximums around.

**Comment by rohany** [comment]
bors r=knz

**Pull request merged**
