### PR TITLE
build: clean old generated files

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds an unconditional search-and-destroy for untracked
execgen files, so that switching between branches that have new
generated code or not won't cause build errors.

Release note: None

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
:lgtm: I suppose we should also backport to the active release branches.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-:-LghK46ODnKviwhWFZ8C:b8cl5ha)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @solongordon)

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38054)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @jordanlewis)

___
*[Makefile, line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-LghPI--0zzKw9h5aCo_:-LghPI--0zzKw9h5aCoa:b8qenr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbd744cd7a2d8bb5464a0265b557e5d169e4379/Makefile#L768)):*
> ```Makefile
> 
> $(info Cleaning old generated files.)
> $(shell find ./pkg/sql/exec -type f -name '*.eg.go' | grep -v -e ${EXECGEN_EXCLUSION_STRING} | xargs rm)
> ```

have you done testing on how long this takes? if it's run on every make invocation even a little slowness could add up. also curious how long it takes in ./build/builder.sh (I can never remember what, but some filesystem operations are crazy slow in docker for mac)
___
*[Makefile, line 1483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-LghPAK_CTzb1b2OMwdR:-LghPAK_CTzb1b2OMwdS:bg2skqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbd744cd7a2d8bb5464a0265b557e5d169e4379/Makefile#L1483)):*
> ```Makefile
> 	git -C $(KRB5_SRC_DIR)     clean -dxf
> 
> .PHONY: clean-generated-go
> ```

should we include opt here or else rename the target to be exec-specific?

**Review by jordanlewis — COMMENTED** [review]
I'll backport.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-:-LghTmvjBpM_RRRAxp4t:bsy1u5l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[Makefile, line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-LghPI--0zzKw9h5aCo_:-LghSwVn0Y48aLkfEvv4:b-1scy5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbd744cd7a2d8bb5464a0265b557e5d169e4379/Makefile#L768)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

have you done testing on how long this takes? if it's run on every make invocation even a little slowness could add up. also curious how long it takes in ./build/builder.sh (I can never remember what, but some filesystem operations are crazy slow in docker for mac)
</blockquote></details>

A no-op `make build` takes about 15 seconds on my machine, so any difference there is in the noise. The fastest `make` command we have is probably `make testbaselogic FILES=nosuchfile` after the cache is warm. That takes 1.10 seconds on average before my change, and 1.15 seconds on average after.

On Docker, I see a similar spread. The filesystem issue was bad before because of the sheer number of files to crawl in stuff like node_modules. pkg/sql/exec has very few files.
___
*[Makefile, line 1483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-LghPAK_CTzb1b2OMwdR:-LghTm57AT5uaFtBsMkx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbd744cd7a2d8bb5464a0265b557e5d169e4379/Makefile#L1483)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

should we include opt here or else rename the target to be exec-specific?
</blockquote></details>

Done.

**Review by danhhz — COMMENTED** [review]
:lgtm-strong: thanks jordan!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-:-LghWT3BC62-A0wYitC-:bl83fs7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[Makefile, line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-LghPI--0zzKw9h5aCo_:-LghWVK0D0P8KXkZxPBc:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbd744cd7a2d8bb5464a0265b557e5d169e4379/Makefile#L768)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

A no-op `make build` takes about 15 seconds on my machine, so any difference there is in the noise. The fastest `make` command we have is probably `make testbaselogic FILES=nosuchfile` after the cache is warm. That takes 1.10 seconds on average before my change, and 1.15 seconds on average after.

On Docker, I see a similar spread. The filesystem issue was bad before because of the sheer number of files to crawl in stuff like node_modules. pkg/sql/exec has very few files.
</blockquote></details>

:thumbsup:

**Review by jordanlewis — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38054#-:-LghlouoEVB0HHQRwmOk:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

**Pull request merged**
