### PR TITLE
plpgsql: allow RETURN with no expression

### LINKED ISSUE #108298: sql: unexpected error creating PLpgSQL UDF with void return type
In Postgres:

```sql
DROP FUNCTION IF EXISTS f;

CREATE FUNCTION f() RETURNS VOID LANGUAGE PLpgSQL AS 'BEGIN RETURN; END';

SELECT f();
--  f
-- ---
-- 
-- (1 row)
```

In CRDB, the `CREATE FUNCTION` errors:

```
ERROR: at or near "return": at or near ")": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SET ROW ()
         ^
--
source SQL:
BEGIN RETURN; END
      ^
HINT: try \h SET SESSION
```

Jira issue: CRDB-30418

### LINKED ISSUE #114849: sql: plpgsql functions should not have a parameter in functions returning void
Repro:
```
create function void_return_expr() returns void as $$                  
  begin                                                                  
     return 5;                                                          
 end;$$ language plpgsql; 
```

This succeeds in CRDB but fails in postgres with the error:
```
ERROR:  RETURN cannot have a parameter in function returning void      
 -LINE 3:     return 5;                                                  
 -                   ^   
```

Additionally, since this succeeds, we can run into the following internal error if we try to call the function.
```
select void_return_expr();
```

Stacktrace:
```
ERROR: internal error: invalid datum type given: INT8, expected VOID
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:195: DatumToEncDatum()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:228: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:128: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:145: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:150: Next()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:198: Run()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:305: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:910: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1957: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:361: func3()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:364: runPlanInsidePlan()
github.com/cockroachdb/cockroach/pkg/sql/routine.go:276: func2()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:1219: func2()
github.com/cockroachdb/cockroach/pkg/sql/routine.go:239: startInternal()
github.com/cockroachdb/cockroach/pkg/sql/routine.go:180: Start()
github.com/cockroachdb/cockroach/pkg/sql/routine.go:92: EvalRoutineExpr()
github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:629: EvalRoutineExpr()
github.com/cockroachdb/cockroach/bazel-out/darwin-fastbuild/bin/pkg/sql/sem/tree/eval_expr_generated.go:351: Eval()
github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:26: Expr()
github.com/cockroachdb/cockroach/pkg/sql/values.go:89: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:520: func2()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:112: func1()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:299: visitInternal()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:79: visit()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:43: walkPlan()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:523: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:175: Start()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183: Init()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94: init()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

Found in pg_regress plpgsql

Jira issue: CRDB-33715

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: add parser support for RETURN with no expression

This commit adds support in the PL/pgSQL parser for RETURN statements
with no expression, like `RETURN;`.

#### plpgsql: allow RETURN with no expression

This commit adds support for `RETURN` statements with no expression.
This applies to routines with OUT-parameters, and those with a VOID
return type. This commit also refactors handling of implicit RETURN
statements for the previously mentioned cases. This ensures that implicit
returns are added in all possible control flow paths, including
exception handlers.

Informs #100405
Fixes #114849
Fixes #108298

Release note (sql change): Added support for `RETURN` statements with
no expression for routines with OUT-parameters and routines with a `VOID`
return type.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Very nice, thanks! :lgtm:

> Reviewed 4 of 4 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-:-NsOhFKY-DXus2zKuN1J:b-8sc7h2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsOgQvA-EazuPE5emVx:-NsOgQvA-EazuPE5emVy:bbbsr33) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741a72bf5c28ea57a698a8d811e6bdf096588/pkg/sql/opt/optbuilder/plpgsql.go#L337)):*
> ```Go
> 	// building the variable declarations, so that expressions that reference
> 	// those variables can be type-checked.
> 	if types.IsRecordType(b.returnType) && !b.hasOutParam() {
> ```

nit: why we skip the type checking if we have an OUT param? Consider adjusting the comment below.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120043)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsOgQvA-EazuPE5emVx:-NsP1XoH0lK0jNMwYuh4:b-3vbxxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741a72bf5c28ea57a698a8d811e6bdf096588/pkg/sql/opt/optbuilder/plpgsql.go#L337)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: why we skip the type checking if we have an OUT param? Consider adjusting the comment below.
</blockquote></details>

OUT params will have already determined the return type at this point. I modified the comment, and also removed the one above since it's redundant.

**Review by mgartner — APPROVED** [review]
:lgtm: Nicely done!

> Reviewed 4 of 4 files at r1, 7 of 7 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-:-NsP9sLE2bX1ppez-2ta:b-msncp4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1851 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsP8_1I2XKb3JhZ_inQ:-NsP8_1I2XKb3JhZ_inR:b9evo2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdabdd9a2b8eb298404ed2eff8fc58b7b50a73f6/pkg/sql/opt/optbuilder/plpgsql.go#L1851)):*
> ```Go
> 	)
> 	returnWithVoidParameterErr = pgerror.New(pgcode.DatatypeMismatch,
> 		"RETURN cannot have a parameter in function returning void",
> ```

nit: `RETURN cannot have an expression` here and above, if you agree 
___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsP7XlJ4Yb0YzsZG9V1:-NsP7XlJ4Yb0YzsZG9V2:b-82ld2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee80147d7f46727d50f862d6df3fbd0dd1a7060/pkg/sql/plpgsql/parser/plpgsql.y#L1058)):*
> ```Yacc
> ;
> 
> stmt_return: RETURN return_expr ';'
> ```

Instead of changing the lexer, would a `RETURN ';'` option work?

**Review by DrewKimball — COMMENTED** [review]
TFYRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-:-NsPcIKaEVI30sLI5639:bz5phge)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1851 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsP8_1I2XKb3JhZ_inQ:-NsPbyq7B1QJucPz_pgJ:bzbxqah) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdabdd9a2b8eb298404ed2eff8fc58b7b50a73f6/pkg/sql/opt/optbuilder/plpgsql.go#L1851)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `RETURN cannot have an expression` here and above, if you agree
</blockquote></details>

Postgres does `parameter` instead of `expression` - do you think we should change that?
___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsP7XlJ4Yb0YzsZG9V1:-NsPc6hc61ZPXsZ5iEEw:b-hmiyol) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee80147d7f46727d50f862d6df3fbd0dd1a7060/pkg/sql/plpgsql/parser/plpgsql.y#L1058)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Instead of changing the lexer, would a `RETURN ';'` option work?
</blockquote></details>

That would make the parser mad, unfortunately. PG does the same thing in `pl_gram.y`, FWIW.

**Review by mgartner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120043)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1851 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsP8_1I2XKb3JhZ_inQ:-NsPodEy6fwQ9lgdxcZI:bfn5s5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdabdd9a2b8eb298404ed2eff8fc58b7b50a73f6/pkg/sql/opt/optbuilder/plpgsql.go#L1851)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Postgres does `parameter` instead of `expression` - do you think we should change that?
</blockquote></details>

Ah ok. Fine to leave as-is then.
___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120043#-NsP7XlJ4Yb0YzsZG9V1:-NsPogmM9jJUG85is8js:bv7ybov) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee80147d7f46727d50f862d6df3fbd0dd1a7060/pkg/sql/plpgsql/parser/plpgsql.y#L1058)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

That would make the parser mad, unfortunately. PG does the same thing in `pl_gram.y`, FWIW.
</blockquote></details>

I figured. Oh well...

**Comment by DrewKimball** [comment]
bors retry

**Pull request merged**
