### PR TITLE
sql: Reject INTERVAL nanoseconds

### PR DESCRIPTION
**Pull request by bobvawter**
This change is a follow-up to #32143 and #34202.  This changes the parser to
reject the "nanoseconds" token when parsing an INTERVAL value.

Fixes: #35872

Release note: None

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Comment by bobvawter** [comment]
bors r+

Looks like a test-rig flake.

**Comment by knz** [comment]
does this want a backport?

**Comment by awoods187** [comment]
Yes--it should be in 19.1

**Comment by bobvawter** [comment]
This was backported to 19.1 in #36001

**Comment by knz** [comment]
Thanks. Somehow backboard did not see it.

(You know about that tool `backport` that automates things, right? :)

**Pull request merged**
