### PR TITLE
sql: cleanup fetchers

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: clean up Fetcher interfaces a bit**

This commit removes a couple of arguments (`traceKV`,
`forceProductionBatchSize`) from `StartScan*` fetcher methods in
favor of passing them on `Init`. Additionally, several fields are
removed from `row.Fetcher` in favor of accessing the args struct
directly.
    
The only meaningful change is that now we correctly propagate `traceKV`
flag in the column backfiller code path when it is set up in
a distributed case.

Release note: None

**sql: clean up the lifecycle of fetchers**

Previously, the lifecycle of different fetcher objects was a mess.
Consider the sequence of fetchers when used by the join reader with the
old non-streamer code path:
`rowexec.joinReader` -> `row.Fetcher` -> `row.KVFetcher` -> `row.txnKVFetcher`.
`row.Fetcher` was initialized once, but then on every call to
`StartScan`, we would create a new `row.txnKVFetcher` and then wrap it
with a new `row.KVFetcher` (during an internal `StartScanFrom` call). In
other words, throughout the lifetime of the join reader, its fetcher
would create a new pair of objects for each input row batch. This setup
is very unintuitive and previously led to some bugs with memory
accounting.

I believe such a setup was created organically, without giving too much
thought to it. Some considerations should be pointed out:
- in some cases, we have some state from the previous fetch that we want
to discard
- in some cases, we provide the `row.Fetcher` with a custom
`KVBatchFetcher` implementation.

This commit refactors all of this stuff to make it much more sane. In
particular, we now only create a single `row.KVFetcher` object that is
powered by a single `row.txnKVFetcher` or `row.txnKVStreamer`
implementation throughout the whole lifetime of `row.Fetcher`. In the
main code path, the callers are now expected to only use `StartScan`
method which correctly discards unnecessary state from the previous
call. This is achieved by adding a new method to `KVBatchFetcher`
interface.

This commit supports the use case with custom `KVBatchFetcher`s too by
asking the caller to explicitly specify a knob during the initialization
of the `row.Fetcher` - in such case, only `StartScanFrom` calls are
allowed. There, we still close the `KVBatchFetcher` from the previous
call (tbh I believe this is not necessary since these custom
`KVBatchFetcher`s don't have anything to clean up, but it's probably
safer to keep the old behavior here).

Furthermore, this commit pushes some arguments from `StartScan` into
`Init` - most notably the txn is now passed only once. However, there
are some use cases (like a column backfill, done in chunks) where the
txn might change throughout the lifetime of the fetcher - we allow
updating it later if needed.

This also allows us to unify the streamer and the non-streamer
code paths - to remove some of the duplicated code as well as push the
usage of the streamer lower in the stack.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This was inspired by Michael's [suggestion](https://github.com/cockroachdb/cockroach/pull/82384#pullrequestreview-1004741418).

**Review by miretskiy — APPROVED** [review]
changefeed changes are 👍

**Review by rharding6373 — DISMISSED** [review]
Nice cleanup!

> Reviewed 20 of 20 files at r1, 29 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-:-N585IVQ4P1uRzYgLwNU:b7oy6or)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @stevendanna, and @yuzefovich)

___
*[`pkg/sql/row/fetcher.go` line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N57Unx7E9j28qRrvJCp:-N57Unx7E9j28qRrvJCq:bkm9rlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f984b37f9ff4bcb5663787626a5386c7c6d323/pkg/sql/row/fetcher.go#L391)):*
> ```Go
> // SetTxn updates the Fetcher to use the provided txn.
> func (rf *Fetcher) SetTxn(txn *kv.Txn) {
> 	rf.setTxnAndSendFn(txn, makeKVBatchFetcherDefaultSendFunc(txn))
> ```

What if there was already a sendFn set? Wouldn't this overwrite it?
___
*[`pkg/sql/row/kv_batch_streamer.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N57W9a1DYludSxAzqjJ:-N57W9a1DYludSxAzqjK:b71uup8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f984b37f9ff4bcb5663787626a5386c7c6d323/pkg/sql/row/kv_batch_streamer.go#L83)):*
> ```Go
> ) error {
> 	if bytesLimit != rowinfra.NoBytesLimit {
> 		return errors.AssertionFailedf("unexpectedly non-zero bytes limit for txnKVStreamer")
> ```

nit: s/unexpectedly/unexpected
___
*[`pkg/sql/row/kv_fetcher.go` line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N56EyHwE4qH8HaCTh_t:-N56EyHxECpe9bQe0uUP:bmahpwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f984b37f9ff4bcb5663787626a5386c7c6d323/pkg/sql/row/kv_fetcher.go#L272)):*
> ```Go
> 
> // SetupNextFetch overrides the same method from the wrapped KVBatchFetcher in
> // order reset this KVFetcher.
> ```

nit: s/in order/in order to

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @rharding6373, and @stevendanna)

___
*[`pkg/sql/row/fetcher.go` line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N57Unx7E9j28qRrvJCp:-N58gWEzDF4RcJPMhGqk:b4vosy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f984b37f9ff4bcb5663787626a5386c7c6d323/pkg/sql/row/fetcher.go#L391)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

What if there was already a sendFn set? Wouldn't this overwrite it?
</blockquote></details>

Yes, this would overwrite it, added some commentary.

This method is exposed to support the column backfill use case where a single `row.Fetcher` object is reused many times throughout the column backfill operation which is broken down into chunks, and each chunk is processed under a new txn. The previous usage pattern of creating new `row.txnKVFetcher`s for each chunk was doing essentially this - creating a new `sendFn` for each chunk.

**Review by michae2 — CHANGES_REQUESTED** [review]
Thank you for doing this. It turned out really, really nice. I was not expecting all the unifications of streamer and non-streamer code!

I have a few nits. Almost done reading, I will finish tonight.

> Reviewed 20 of 20 files at r1, 14 of 29 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-:-N5CrNWbEAaUPQBvlahF:b-uqt2h7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373, @stevendanna, and @yuzefovich)

___
*[`pkg/sql/row/fetcher.go` line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N5C_rd87k-TGJHeiyqm:-N5C_rd87k-TGJHeiyqn:b-eq1u6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/238d479c77f5fa6a7c4dc041532d95b8d943725f/pkg/sql/row/fetcher.go#L227)):*
> ```Go
> 	// WillUseCustomKVFetcher, if true, indicates that the caller will only use
> 	// StartScanFrom() method and will be providing its own KVFetcher.
> 	WillUseCustomKVFetcher bool
> ```

nit: Maybe this is pedantic, but wouldn't `WillUseCustomKVBatchFetcher` be more accurate? And likewise, shouldn't the comment say "its own KVBatchFetcher" instead of "its own KVFetcher"?
___
*[`pkg/sql/row/fetcher.go` line 403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N5Bv_mdAzmq9cvkQX9I:-N5Bv_mdAzmq9cvkQX9J:b-rkryds) ([raw file](https://github.com/cockroachdb/cockroach/blob/238d479c77f5fa6a7c4dc041532d95b8d943725f/pkg/sql/row/fetcher.go#L403)):*
> ```Go
> // setTxnAndSendFn peeks inside of the KVFetcher to update the underlying
> // txnKVFetcher with the new txn and sendFn.
> func (rf *Fetcher) setTxnAndSendFn(txn *kv.Txn, sendFn sendFunc) {
> ```

Could we do this in a `txnKVFetcher` method rather than here? I know it's a pain to plumb another method call down to `KVFetcher` / `KVBatchFetcher` / `txnKVFetcher`, but reaching into the `txnKVFetcher` like this this seems like a layer violation.

Or maybe a compromise would be: we put the changes to `txnKVFetcher` in a `txnKVFetcher` method, but then we peek inside `kvFetcher.KVBatchFetcher.(*txnKVFetcher)` to call the method instead of adding the method to `KVBatchFetcher` and `KVFetcher`? That at least shrinks the surface area of the layer violation slightly. Would that be reasonable?
___
*[`pkg/sql/row/fetcher.go` line 500 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N5Cbjh_0n6YM11VwjqL:-N5Cbjh_0n6YM11VwjqM:b-he1guy) ([raw file](https://github.com/cockroachdb/cockroach/blob/238d479c77f5fa6a7c4dc041532d95b8d943725f/pkg/sql/row/fetcher.go#L500)):*
> ```Go
> ) error {
> 	if rf.args.StreamingKVFetcher != nil {
> 		return errors.AssertionFailedf("StartInconsistentScan is called instead of StartScanFrom")
> ```

nit: Should this say "... instead of StartScan" instead of "... instead of StartScanFrom"?
___
*[`pkg/sql/row/kv_fetcher.go` line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N5CZIKSER756D1_cHy6:-N5CZIKSER756D1_cHy7:b-nrjkbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/238d479c77f5fa6a7c4dc041532d95b8d943725f/pkg/sql/row/kv_fetcher.go#L138)):*
> ```Go
> 	diskBuffer kvstreamer.ResultDiskBuffer,
> ) *KVFetcher {
> 	streamer := kvstreamer.NewStreamer(
> ```

Nice that you can push this lower!

**Review by yuzefovich — COMMENTED** [review]
Indeed, I'm quite happy with this refactor, thanks for the idea!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-:-N5CvL-R3GkmIP2XCEVp:bflmb8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @rharding6373, and @stevendanna)

___
*[`pkg/sql/row/fetcher.go` line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N5C_rd87k-TGJHeiyqm:-N5CvwSX-27wD1s3L52H:bupcdqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/238d479c77f5fa6a7c4dc041532d95b8d943725f/pkg/sql/row/fetcher.go#L227)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Maybe this is pedantic, but wouldn't `WillUseCustomKVBatchFetcher` be more accurate? And likewise, shouldn't the comment say "its own KVBatchFetcher" instead of "its own KVFetcher"?
</blockquote></details>

You're right, fixed. I guess I wanted to make things shorter, but it seems better to be precise here.
___
*[`pkg/sql/row/fetcher.go` line 403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-N5Bv_mdAzmq9cvkQX9I:-N5CxGeoBanwEMLl1tSu:b-6t3oo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/238d479c77f5fa6a7c4dc041532d95b8d943725f/pkg/sql/row/fetcher.go#L403)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Could we do this in a `txnKVFetcher` method rather than here? I know it's a pain to plumb another method call down to `KVFetcher` / `KVBatchFetcher` / `txnKVFetcher`, but reaching into the `txnKVFetcher` like this this seems like a layer violation.

Or maybe a compromise would be: we put the changes to `txnKVFetcher` in a `txnKVFetcher` method, but then we peek inside `kvFetcher.KVBatchFetcher.(*txnKVFetcher)` to call the method instead of adding the method to `KVBatchFetcher` and `KVFetcher`? That at least shrinks the surface area of the layer violation slightly. Would that be reasonable?
</blockquote></details>

I agree that this is rather hacky, and I like your suggestion, done. I also added some assertions to make things more explicit (in the future, we might need to do a similar thing for `txnKVStreamer`, but for now we only need to support the updating of the txn on `txnKVFetcher`).

**Review by michae2 — APPROVED** [review]
:lgtm_strong: :100: :motorcycle:

> Reviewed 29 of 29 files at r4, 29 of 29 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83010#-:-N5DmfDV3n4oDVqadmST:bv5t49r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @stevendanna)

**Comment by yuzefovich** [comment]
I'm assuming that Rachael is on board with this change.

Thanks for the reviews!

bors r+

**Pull request merged**
