### PR TITLE
sql: add tests for check constraints on virtual columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Friendly ping.

**Review by mgartner — COMMENTED** [review]
Sorry! Taking a look ASAP.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-:-MTgCNyK1qD0nqvnAacr:b-a028ls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-:-MTgmr8tEE4CW0f-TlED:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-MTgjX4_BJC7a_S8suiI:-MTgjDUm1_fq__C3jpvO:b-1bl1kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa13f820fb8c2436798b4dcf36246e73370c5636/pkg/sql/logictest/testdata/logic_test/virtual_columns#L496)):*
> ```
> 
> statement ok
> INSERT INTO n VALUES (1, NULL) ON CONFLICT DO NOTHING
> ```

[nit] add tests with no conflict that error like

```
statement error null value in column "v" violates not-null constraint
INSERT INTO n VALUES (3, NULL) ON CONFLICT DO NOTHING
```

And below:

```
statement error null value in column "v" violates not-null constraint
INSERT INTO n VALUES (3, NULL) ON CONFLICT (a) DO UPDATE SET b = 10
```
___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-MTgm5IU669Tnds_IKiZ:-MTgm5IV1zs3fancZOUn:b-n1hurz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa13f820fb8c2436798b4dcf36246e73370c5636/pkg/sql/logictest/testdata/logic_test/virtual_columns#L768)):*
> ```
> 
> statement error failed to satisfy CHECK constraint
> INSERT INTO sc VALUES (20, 20)
> ```

[super nit] seems like some of these tests belong in the Checks subtest, but if it's easier to keep them here that's fine.
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 1367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-MTgmTNmAFN05UDbWIQA:-MTgmTNmAFN05UDbWIQB:b-3k4y18) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa13f820fb8c2436798b4dcf36246e73370c5636/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L1367)):*
> ```
>       estimated row count: 60 (missing stats)
>       table: checks@checks_v_b_idx
>       spans: /0/10-/0/16 /1/10-/1/16 /2/10-/2/16 /3/10-/3/16
> ```

:tada: Cool! I'm glad this _just works_.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-:-MTh0oyS8ntLjP87UVwC:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-MTgm5IU669Tnds_IKiZ:-MTgzKNmANuyMh6cVN4K:bnn0hta) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa13f820fb8c2436798b4dcf36246e73370c5636/pkg/sql/logictest/testdata/logic_test/virtual_columns#L768)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[super nit] seems like some of these tests belong in the Checks subtest, but if it's easier to keep them here that's fine.
</blockquote></details>

This is the SchemaChanges subtest, I think it belongs here because any failure here (without an earlier failure in the vanilla tests) is likely related to the schema change.

**Review by mgartner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60452)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @mgartner, and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60452#-MTgm5IU669Tnds_IKiZ:-MThRGJ2AAUxI7wMAqNC:b4vhr7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa13f820fb8c2436798b4dcf36246e73370c5636/pkg/sql/logictest/testdata/logic_test/virtual_columns#L768)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is the SchemaChanges subtest, I think it belongs here because any failure here (without an earlier failure in the vanilla tests) is likely related to the schema change.
</blockquote></details>

Ahh I missed that. SGTM.

**Pull request merged**
