### PR TITLE
roachtest: stop ignoring activerecord failures

### LINKED ISSUE #108938: roachtest: update to stable activerecord test suite when available
The activerecord nightly tests are unstable. There is work being done upstream ([here](https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+failure)) to make the tests work.

Once that is complete, we should update the nightly roachtest to use the new version.

Jira issue: CRDB-30709

### PR DESCRIPTION
**Pull request by rafiss**
The adapter has been stabilized, so we should enable this test again.

fixes https://github.com/cockroachdb/cockroach/issues/108938
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
testing here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13787422?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Comment by rafiss** [comment]
a second run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13794102?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Review by annrpom — APPROVED** [review]
lgtm

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
