### PR TITLE
protectedts: switch Record UUID to a binary encoding

### PR DESCRIPTION
**Pull request by adityamaru**
This change introduces a `Bytes` type that represents the
binary encoding of a UUID. It also switches the ptpb.Record.ID
field that previously used a UUID backed customtype, to now
be cast to a `Bytes` type.

The need for this change arises
because of the lack of gogoproto support to protoutil.Clone
an Array type. uuid.UUID is backed by an Array, and so we
have safeguards to prevent any CRDB code from cloning a protobuf
that contains a uuid.UUID field.

In the near future, we might start storing ptpb.Record on zone configs,
which are cloned in parts of the codebase. To make this transition
easier, we switch the Array backed UUID to a Slice backed binary
encoding of the UUID. Even if we decide against storing the records
on zcfgs, this seems like a general improvement.

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
@ajwerner is this something like what you had in mind to get around the whole `protoutil.Clone` `UUID` mess? Generally switching the customtype without any migration seems sane given how we write the fields as byte to the system table. My one concern was `Protect` that takes in a `ptpb.Record`, but I have audited the code to convince myself that we should never end up with an older `ptpb.Record` (with UUID) being passed into the 22.1 `Protect` implementation.

**Comment by ajwerner** [comment]
What about something simpler. In particular, what if we did something like:

```go
package uuid

// Bytes represents a byte slice which is intended to be interpreted as a binary
// encoding of a UUID.
type Bytes []byte

// ToUUID constructs a UUID from the bytes. If the data is not valid, a
// zero value will be returned.
func (b Bytes) GetUUID() UUID { return FromBytesOrNil(b) }
```

and then in the proto use a `casttype` instead of a custom type:

```protobuf
 message Record {
 
   // ID uniquely identifies this row.
-  bytes id = 1 [(gogoproto.customtype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.UUID", (gogoproto.nullable) = false, (gogoproto.customname) = "ID"];
+  bytes id = 1 [(gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.Bytes", (gogoproto.customname) = "ID"];
```

It results in a need to add a number of `GetUUID` and `GetBytes()` calls, but it's all superficial.

**Comment by adityamaru** [comment]
> What about something simpler. In particular, what if we did something like:
> 
> ```go
> package uuid
> 
> // Bytes represents a byte slice which is intended to be interpreted as a binary
> // encoding of a UUID.
> type Bytes []byte
> 
> // ToUUID constructs a UUID from the bytes. If the data is not valid, a
> // zero value will be returned.
> func (b Bytes) GetUUID() UUID { return FromBytesOrNil(b) }
> ```
> 
> and then in the proto use a `casttype` instead of a custom type:
> 
> ```proto
>  message Record {
>  
>    // ID uniquely identifies this row.
> -  bytes id = 1 [(gogoproto.customtype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.UUID", (gogoproto.nullable) = false, (gogoproto.customname) = "ID"];
> +  bytes id = 1 [(gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.Bytes", (gogoproto.customname) = "ID"];
> ```
> 
> It results in a need to add a number of `GetUUID` and `GetBytes()` calls, but it's all superficial.

Thanks for this, much simpler and low touch. I've changed the commit to this.

**Review by ajwerner — COMMENTED** [review]
kv/kvserver/replica_protected_timestamp_test.go needs some love

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73634#-:-Mr8l5849umHp246RiXX:b-tehbms)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by adityamaru** [comment]
Failures now seem unrelated to the change:

`TestComposeGSS` on Github CI, and an occurrence of https://github.com/cockroachdb/cockroach/issues/73997 on Bazel.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73634#-:-MrL-tO_2tnBt637e5jp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Pull request merged**
