### PR TITLE
colexecagg: add accounting for current aggregate decimals and cleanup first group handling

### LINKED ISSUE #57374: colexecagg: aggregate functions don't account for curAgg if it is decimal
The title. Also, consider refactoring all of the functions to make accounting for `curAgg` easier.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexecagg: add accounting for current aggregate decimals**

Previously, we weren't accounting for the size of a decimal object that
is the "current aggregate value" (i.e. the intermediate result of
computation), and this is now fixed. Additionally, this commit cleans up
how we perform such accounting for bytes and datum-backed types by
introducing another `execgen.SETVARIABLESIZE` directive that computes
the size of an element from a vector if it is variable.

Fixes: #57374.

Release note: None

**colexecagg: refactor ordered aggregate funcs' handling of first group**

Previously, the contract of `AggregateFunc` was that the first tuple of
the first group (in case of the ordered aggregation) must *not* be
marked with `true` in `groups` column. In order to achieve that, we had
to plan a "one-shot" operator that performed an arbitrary operation (in
our case, setting `groups[0]` to `false`) and then deleted itself from
the tree.

Such approach seems pretty fragile - how can we reset the ordered
aggregator for reuse (needed by the external hash joiner)? So this
commit adjusts the contract that all groups, including the first one,
must have `true` set at the group's start. This required introducing
a boolean flag to `orderedAggregateFuncBase` that tracks whether the next
group marked in `groups` column is the first one or not (we don't need
to advance the aggregation if it is). The performance impact is quite
small given the absolute speeds of ordered aggregation.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Added another commit the benchmarks of which are [here](https://gist.github.com/yuzefovich/3ecd0aab768e7cb86cace9fff1472e59) and [here](https://gist.github.com/yuzefovich/026cdbabbc2ac8a0895bf50aa781c539).

**Review by asubiotto — CHANGES_REQUESTED** [review]
Do you have benchmarks for the second commit? The reason to have the groups behavior is to avoid an extra conditional, but maybe the impact is small.

> Reviewed 32 of 32 files at r1, 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57620#-:-MO5z4ix1s57_GAJs1Im:b-j403o0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/execgen/placeholders.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57620#-MO5yNWQ4jmxsNGpThQ_:-MO5yNWQ4jmxsNGpThQa:bwpmu5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e739d6e36f7487ec699f88a6bebf341776376912/pkg/sql/colexec/execgen/placeholders.go#L86)):*
> ```Go
> 
> // VARIABLESIZE is a template function.
> func VARIABLESIZE(target, value interface{}) interface{} {
> ```

`VARIABLESIZE` seems pretty vague to me because there's no verb. What about `SETMEMSIZE`?

**Review by yuzefovich — COMMENTED** [review]
I posted the benchmarks numbers in the comment [right above](https://github.com/cockroachdb/cockroach/pull/57620#issuecomment-741501523).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57620#-:-MO79J0d06_vPj96dKj0:b-j58iln)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/execgen/placeholders.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57620#-MO5yNWQ4jmxsNGpThQ_:-MO79PgR4sFFn4zp7bVk:ba663g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e739d6e36f7487ec699f88a6bebf341776376912/pkg/sql/colexec/execgen/placeholders.go#L86)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`VARIABLESIZE` seems pretty vague to me because there's no verb. What about `SETMEMSIZE`?
</blockquote></details>

Switched to `SETVARIABLESIZE`.

I think we want the method to do something only for the types with variable size so that for all others the code for memory accounting is compiled away (since it looks something like
```
var oldCurAggSize uintptr
...
var newCurAggSize uintptr
if newCurAggSize != oldCurAggSize {
...
}
```
and those variables aren't changed in the main body). It seems like a nice minor improvement.

**Review by asubiotto — APPROVED** [review]
> right above
Oops, sorry! For some reason didn't see it in reviewable.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57620#-:-MOBIP177AIrFqTQQHS3:b-djby79)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by yuzefovich** [comment]
Np!

TFTR!

bors r+

**Pull request merged**
