### PR TITLE
sql: fix incorrect ordering inside distributed streaming aggregation

### LINKED ISSUE #37211: distsqlplan: incorrectly ordered physical plan generated
A query produced the following physical plan, which has unordered synchronizers above a processor that expects ordered inputs. This is invalid.

[distsql plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJzMVu1q40YU_d-nELeFTZpxrTuSbVlQkOluIUvipJsstHRMqlhjR61XY0YSaFnyMn2EPlcfokhO6s_MlWKzGIKJpDn385wjfYFERXIYfpIp-L8DAgMHGLjAoAMjBnOtxjJNlS4fLw6fRwX4NoM4medZeXvEYKy0BP8LZHE2k-DDbXg_kx9kGEndtoFBJLMwnlUp5jr-FOrPwXiWp5nUKTC4mYdJ6luttoDhmRBFXwpRjO__KP_13mZCFKF3LUQh3e-EKO77QuRS9qWA9rWWk7h4l0RWmEQWWip7kBoY_BzPMql96yTwrB-tSThL5ak1GL61TgLHErltO9J6w23st2y3ZaNl2371d1b9vvF9__b88t3N7eDy-hQYXOWZbwXIAocFHoweGag8W3afZuFUgo-PrP6E3qs4eRqQs3tAaaa0vNNyrnRWTulCqb_yufWnihNLJWU9_1fmsqDLgj4L8MXieJPiBtOpltMwU7rdXS-uHAIv8-pIahk9VTEY_nY3vLq9G368uDgJ8HTrFi9vXQ5-PQmc040Sl1nvP1sPYfqwK-HocdmJ82Iny1B5ohYFrgWrohh67R--11XuvLgb95W7Qb5ZcJ1qbz5eVkU2XMPaDjo1drBrAxDgGVBrwM7h2lqW3G0y5BulM6nb6G1Uwlsvxu-txcf6_oh1_XEPeyytNZ_EQhQTtzpfHh-_fw4WOkIUXqf8iconzr___P2tgOMwUmKUK0bqfn0jJYpbYXXvyI0UD2ikaB-Fk9ZfDjrH4aS7l_B6J916ex_eSYkhPzvp5ru1tpPyBiOpgu4oYqhaat7muEHi3em9tfROfSPnDYy8uRmXFl4eGf-ghSiQD4ufng-HvU4V4pfvhShsTCbH_WVMjHTF0Dtf39CJ4lbEtfltcGyG7hzS0PEoDL3-ctA9DkPfvYTXG_rWV8ThDZ0Y8pOh881X_KsMfUf8DzKdqySVtbzaLuclo6lczDdVuR7La63G1Rf-4vKqwlU3Iplmi6e4uDhPFo_KAlfBaARzM5hvgnEV7KyBsRkY7b3QnhntGLt2zV27xtQdc2YzGPk-aE7MrGPsumvuumtmmWtO3TOiPXNqzwjum8H9fThqBlMcJdAER5HQNSXsLWU3oSmBpnhKwCmi4pa611t3iNbN8qa4ilsqW_dEwhTRLDMkdIaE0HoEfEtpTfhOoCnCU3CK8WahI6F0NOuNYjyhVorxZjjFeG4WOyfEzs2v8S3Gjx6_-S8AAP__MQ35MA==
)
The queries and error:

```
roland@gceworker-roland:~/pm$ cat clustersize.sql
SHOW CREATE TABLE clusters;
SHOW CREATE TABLE store_reports;
SELECT
	cluster, sum(bytes) AS cluster_size
FROM
	(
		SELECT
			cluster, storeid, max(bytes) AS bytes
		FROM
			store_reports JOIN clusters ON cluster = id
		WHERE
			internal = false AND lastseen > '2019-04-01'
		GROUP BY
			cluster, storeid
	)
GROUP BY
	cluster
ORDER BY
	cluster_size DESC;
roland@gceworker-roland:~/pm$ cockroach sql -d registration --insecure < clustersize.sql
  table_name |                                         create_statement
+------------+---------------------------------------------------------------------------------------------------+
  clusters   | CREATE TABLE clusters (
             |     id UUID NOT NULL,
             |     firstseen TIMESTAMP NULL DEFAULT now():::TIMESTAMP,
             |     lastseen TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
             |     pings INT NOT NULL DEFAULT 0:::INT,
             |     insecure BOOL NULL,
             |     maxnodeid INT NULL,
             |     licensetype STRING NULL,
             |     internal BOOL NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     FAMILY "primary" (id, firstseen, lastseen, pings, insecure, maxnodeid, licensetype, internal)
             | )
(1 row)

Time: 28.577681ms

   table_name   |                                                   create_statement
+---------------+----------------------------------------------------------------------------------------------------------------------+
  store_reports | CREATE TABLE store_reports (
                |     cluster UUID NOT NULL,
                |     node INT NOT NULL,
                |     storeid INT NOT NULL,
                |     "timestamp" TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
                |     uptime INT NULL,
                |     bytes INT NULL,
                |     keycount INT NULL,
                |     rangecount INT NULL,
                |     encryptionalgorithm STRING NULL,
                |     CONSTRAINT "primary" PRIMARY KEY (cluster ASC, node ASC, storeid ASC, "timestamp" DESC),
                |     FAMILY "primary" (cluster, node, storeid, "timestamp", uptime, bytes, keycount, rangecount, encryptionalgorithm)
                | )
(1 row)

Time: 18.470403ms

pq: internal error: uncaught error: incorrectly ordered stream ['009a27be-977a-4efd-b905-4f7eb7bce44a' 74105] after ['4e3f7753-5bef-4c43-b5c0-a530ec07a62e' 74422] (ordering: [{0 1}])
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*orderedSynchronizer).advanceRoot
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/input_sync.go:252
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*orderedSynchronizer).Next
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/input_sync.go:291
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*orderedAggregator).accumulateRows
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:533
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*orderedAggregator).Next
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:721
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).fill
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:305
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).Start
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:286
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:800
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:566
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/distsqlpb/data.go:151: in NewError()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/stream_encoder.go:109: in AddMetadata()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:125: in addRow()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:293: in mainLoop()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:413: in run()

HINT: You have encountered an unexpected error inside CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this problem is already tracked. If you cannot find it there,
please report the error with details at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.
```

The EXPLAIN(opt,env):

```
text
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  Version: CockroachDB CCL v19.1.0-rc.3 (x86_64-unknown-linux-gnu, built 2019/04/11 23:27:22, go1.11.6)
  CREATE TABLE store_reports (
      cluster UUID NOT NULL,
      node INT NOT NULL,
      storeid INT NOT NULL,
      "timestamp" TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
      uptime INT NULL,
      bytes INT NULL,
      keycount INT NULL,
      rangecount INT NULL,
      encryptionalgorithm STRING NULL,
      CONSTRAINT "primary" PRIMARY KEY (cluster ASC, node ASC, storeid ASC, "timestamp" DESC),
      FAMILY "primary" (cluster, node, storeid, "timestamp", uptime, bytes, keycount, rangecount, encryptionalgorithm)
  );
  ALTER TABLE registration.public.store_reports INJECT STATISTICS '[
      {
          "columns": [
              "cluster"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 936407,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "node"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 298,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "storeid"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 298,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "timestamp"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 39203169,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "uptime"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 2416492,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "bytes"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 35002993,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "keycount"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 9689249,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "rangecount"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 56723,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 39124661
      },
      {
          "columns": [
              "encryptionalgorithm"
          ],
          "created_at": "2019-04-29 01:38:03.459732+00:00",
          "distinct_count": 4,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 29562096,
          "row_count": 39124661
      }
  ]';
  CREATE TABLE clusters (
      id UUID NOT NULL,
      firstseen TIMESTAMP NULL DEFAULT now():::TIMESTAMP,
      lastseen TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
      pings INT NOT NULL DEFAULT 0:::INT,
      insecure BOOL NULL,
      maxnodeid INT NULL,
      licensetype STRING NULL,
      internal BOOL NULL,
      CONSTRAINT "primary" PRIMARY KEY (id ASC),
      FAMILY "primary" (id, firstseen, lastseen, pings, insecure, maxnodeid, licensetype, internal)
  );
  ALTER TABLE registration.public.clusters INJECT STATISTICS '[
      {
          "columns": [
              "id"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 2924260,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 2926091
      },
      {
          "columns": [
              "firstseen"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 2917259,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 2926091
      },
      {
          "columns": [
              "lastseen"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 2521073,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 2926091
      },
      {
          "columns": [
              "pings"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 6857,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 2926091
      },
      {
          "columns": [
              "insecure"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 2,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 388391,
          "row_count": 2926091
      },
      {
          "columns": [
              "maxnodeid"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 131,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 433074,
          "row_count": 2926091
      },
      {
          "columns": [
              "licensetype"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 6,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 800363,
          "row_count": 2926091
      },
      {
          "columns": [
              "internal"
          ],
          "created_at": "2019-04-29 01:36:28.386611+00:00",
          "distinct_count": 2,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 1097499,
          "row_count": 2926091
      }
  ]';
  EXPLAIN (OPT, ENV) SELECT cluster, sum(bytes) AS cluster_size FROM (SELECT cluster, storeid, max(bytes) AS bytes FROM store_reports JOIN clusters ON cluster = id WHERE (internal = false) AND (lastseen > '2019-04-01') GROUP BY cluster, storeid) GROUP BY cluster ORDER BY cluster_size DESC;
  ----
  sort
   └── group-by
        ├── group-by
        │    ├── inner-join (lookup store_reports)
        │    │    ├── select
        │    │    │    ├── scan clusters
        │    │    │    └── filters
        │    │    │         ├── internal = false
        │    │    │         └── lastseen > '2019-04-01 00:00:00+00:00'
        │    │    └── filters (true)
        │    └── aggregations
        │         └── max
        │              └── variable: bytes
        └── aggregations
             └── sum
                  └── variable: max
(240 rows)
Time: 52.308ms
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
When running a streaming aggregation, `groupNode` had the list of
ordered columns, but not the exact ordering. The exact ordering is
needed when planning a distributed aggregation - this ordering must be
maintained between the local and the final stage. The distsql planner
was trying to deduce the ordering from the input, which is usually
OK but not in all cases: if another column is known to be equal with
a grouping column, that column could be used in the input ordering
instead of the grouping column.

The fix is to store the ordering in `groupNode`. We also display the
ordering in EXPLAIN output, and fix the grouping columns to also use
column names for consistency.

Fixes #37211.

Release note (bug fix): Fixed incorrect results or "incorrectly
ordered stream" error in some cases of queries with aggregations.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-:-LfVngIL2cwGraN7QqXZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_physical_planner.go, line 1653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-LfVBZNiAsrM3coE_re3:-LfVBZNiAsrM3coE_re4:b-2jy5nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dae09cb5e0db241dcea13ec4adcaf275cb20d224/pkg/sql/distsql_physical_planner.go#L1653)):*
> ```Go
> 			}
> 			if !found {
> 				return errors.Errorf("group column ordering contains non-grouping column %d", o.ColIdx)
> ```

should this be an assertionerror?
___
*[pkg/sql/explain_tree_test.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-LfVBtb89S7iixdg6Hf_:-LfVBtb89S7iixdg6Hfa:b-xk2ijn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dae09cb5e0db241dcea13ec4adcaf275cb20d224/pkg/sql/explain_tree_test.go#L130)):*
> ```Go
> 2 .aggregate 0 cid (cid int, sum decimal) weak-key(cid)
> 2 .aggregate 1 sum(value) (cid int, sum decimal) weak-key(cid)
> 2 .group by cid (cid int, sum decimal) weak-key(cid)
> ```

I didn't know we still made explain plans that looked like this...
___
*[pkg/sql/opt/ordering/group_by.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-LfVVaWLDDBEObqEUOR9:-LfVVaWLDDBEObqEUORA:b-1nuuzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/dae09cb5e0db241dcea13ec4adcaf275cb20d224/pkg/sql/opt/ordering/group_by.go#L125)):*
> ```Go
> 			ordering = append(
> 				ordering,
> 				opt.MakeOrderingColumn(opt.ColumnID(col), inputOrdering.Columns[i].Descending),
> ```

Not sure I understand what's going on here. Say we have `a==b` as an equality FD and `ORDER BY a, c`. Does this mean we'll report `a,b,c` as the ordering here?

In what circumstances can someone make use of `b` here? It seems to me that in any situation where a consumer of this ordering just knew the ordering but not about the equality relationship between `a` and `b` they wouldn't be able to make any inferences based on knowledge of `b` and not `a`, is that wrong?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37713)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @justinj)

___
*[pkg/sql/distsql_physical_planner.go, line 1653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-LfVBZNiAsrM3coE_re3:-LfVqGX01sPUr6vMXaQZ:b-8ybonr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dae09cb5e0db241dcea13ec4adcaf275cb20d224/pkg/sql/distsql_physical_planner.go#L1653)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

should this be an assertionerror?
</blockquote></details>

Done (though there are a lot of other instances in this file that I left alone).
___
*[pkg/sql/explain_tree_test.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-LfVBtb89S7iixdg6Hf_:-LfVqM5N2u4r8PclB8E2:b-rutnoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/dae09cb5e0db241dcea13ec4adcaf275cb20d224/pkg/sql/explain_tree_test.go#L130)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I didn't know we still made explain plans that looked like this...
</blockquote></details>

I don't know what this is and I'd love to keep it that way :)
___
*[pkg/sql/opt/ordering/group_by.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-LfVVaWLDDBEObqEUOR9:-LfVr0MgDlAsYcS3-Mse:bpmqfat) ([raw file](https://github.com/cockroachdb/cockroach/blob/dae09cb5e0db241dcea13ec4adcaf275cb20d224/pkg/sql/opt/ordering/group_by.go#L125)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Not sure I understand what's going on here. Say we have `a==b` as an equality FD and `ORDER BY a, c`. Does this mean we'll report `a,b,c` as the ordering here?

In what circumstances can someone make use of `b` here? It seems to me that in any situation where a consumer of this ordering just knew the ordering but not about the equality relationship between `a` and `b` they wouldn't be able to make any inferences based on knowledge of `b` and not `a`, is that wrong?
</blockquote></details>

In your example, if we are grouping on `a,b,c`, yes, we will report the ordering `+a,+b,+c` here. The idea was that the more columns we are streaming on the better. In principle, knowing that we're streaming on all columns could be helpful from the execution side (you always work on one bucket at a time).

In practice, this shouldn't happen as the optimizer has rules to remove redundant grouping columns. So I see no reason why I can't change it to just pick a single grouping column if that makes more sense.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37713)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @justinj)

___
*[pkg/sql/opt/ordering/group_by.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-LfVVaWLDDBEObqEUOR9:-LfWPdjh23U4YKQmHiVL:b-q2i19b) ([raw file](https://github.com/cockroachdb/cockroach/blob/dae09cb5e0db241dcea13ec4adcaf275cb20d224/pkg/sql/opt/ordering/group_by.go#L125)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In your example, if we are grouping on `a,b,c`, yes, we will report the ordering `+a,+b,+c` here. The idea was that the more columns we are streaming on the better. In principle, knowing that we're streaming on all columns could be helpful from the execution side (you always work on one bucket at a time).

In practice, this shouldn't happen as the optimizer has rules to remove redundant grouping columns. So I see no reason why I can't change it to just pick a single grouping column if that makes more sense.
</blockquote></details>

Went ahead and made that change.

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: yay, thanks for dealing with this bug - and the huge win that is saying bye-bye to the @n explain syntax. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37713#-:-LfXfvDJBDYbqlahYqKX:b63vyzp)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @justinj)

**Pull request merged**
