### PR TITLE
kv: ignore missing txn record errors in txn heartbeat loop 

### PR DESCRIPTION
**Pull request by nvb**
Related to #20448.

This change adds a reason enum to`TransactionStatusError`. This
enum includes a variant is returned when an operation looks up a
transaction record that it expects to exist and finds that it does
not. This is possible for `HeartbeatTxnRequests` and `EndTxnRequests`.

The change then detects this error type in the `TxnCoordSender`
heartbeat loop. Unlike for any other error type, this error does
not force the heartbeat loop to shut down. The reason for this is
that the heartbeat loop can be started before a client is certain
that a transaction record has been written. If this is ever the
case, like we saw in the YCSB exploration, then terminating the
heartbeat loop on a `TransactionStatusError` will prematurely
abort the entire transaction.

This is a good 2.0.1 candidate. The code that it touches is a little too
delicate for me to feel comfortable rushing it into 2.0 at the last minute.

Release note (bug fix): Fixed bug where an expected transaction
heartbeat failure aborted the transaction.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

Definitely not for 2.0.0, but we can consider it for 2.0.1 if we get good results with further ycsb testing.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/roachpb/errors.proto, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24134#-L8Add_KDsznKdG1rd9s:-L8Add_Lri2Z24JkaCTX:b-ye89qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a4bfc12eaaa47d5e0227d4f2f629d22a65716d/pkg/roachpb/errors.proto#L179)):*
> ```protobuf
> // A TransactionNotFoundError indicates that a request was sent to a
> // transaction record that does not exist.
> message TransactionNotFoundError {
> ```

A new error type seems riskier to me (in terms of mixed-version issues) than a new enum in TransactionStatusError. Maybe it doesn't matter since we don't catch TransactionStatusError anywhere that I can see, but I think I'd still rather have a `reason` enum and add it to all of the TransactionStatusErrors instead of making a different error type for this case. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24134#-:-L8AeLwOLVuop8NKcYkS:bte3aw6)*

**Comment by tschottdorf** [comment]
:lgtm:, I'll defer to @bdarnell for the specifics.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24134#-:-L8DW7R_C0uBrm2Z1dYN:bmf8s03)*

**Comment by nvanbenschoten** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/roachpb/errors.proto, line 179 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24134#-L8Add_KDsznKdG1rd9s:-L96E_6h5vKZbdGNkR1R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a4bfc12eaaa47d5e0227d4f2f629d22a65716d/pkg/roachpb/errors.proto#L179)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

A new error type seems riskier to me (in terms of mixed-version issues) than a new enum in TransactionStatusError. Maybe it doesn't matter since we don't catch TransactionStatusError anywhere that I can see, but I think I'd still rather have a `reason` enum and add it to all of the TransactionStatusErrors instead of making a different error type for this case. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24134)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24134#-:-L96NXeKDxb6lKfu_tEK:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
bors r=bdarnell

**Pull request merged**
