### PR TITLE
backport-2.0: ui: fix typo in node map onboarding screen

### LINKED ISSUE #25096: ui: typo in node map onboarding screen
image

> Step 3: Refer this configuration guide to configure the Node Map.

Missing 'to'. Should be 
> Refer to [this guide](https://www.cockroachlabs.com/docs/v2.0/enable-node-map.html) to configure the roadmap

### PR DESCRIPTION
**Pull request by vilterp**
Backport of #25112

Fixes #25096

Release note (admin ui change): fix typo in node map onboarding screen

### CODE REVIEW

**Review by couchand — APPROVED** [review]

**Comment by benesch** [comment]
Nice, thanks.

**Comment by benesch** [comment]
Nuked some misbehaving TeamCity agents. Let's try this again!

bors r+

**Comment by benesch** [comment]
Once more:

bors r+

**Pull request merged**
