### PR TITLE
Use http-lb, the tcp-level  load balaner will be retired

### PR DESCRIPTION
**Pull request by mberhault**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3591)

### CODE REVIEW

**Comment by mberhault** [comment]
this makes the AWS terraform deployment work again. This will also be used when switching to https anyway (https load balancers are fairly well supported. tcp ones not so much)

**Comment by tschottdorf** [comment]
Can we figure out what went wrong first?

**Comment by bdarnell** [comment]
LGTM

FYI the ["proxy protocol"](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) is reasonably well supported ([AWS](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html)) and could be used to give us the remote IP/port if we want to continue supporting TCP-level load balancing.

**Comment by tschottdorf** [comment]
LGTM, but please post an explanation of why that fixes things.

**Comment by tschottdorf** [comment]
ok, I'm happy. @spencerkimball posted in the other thread.

**Comment by spencerkimball** [comment]
@mberhault we should remove the `lb=` load balancer type.

**Pull request merged**
