### PR TITLE
storage: deflake TestLeaderAfterSplit

### LINKED ISSUE #9968: TestLeaderAfterSplit panic in RocksDB
https://teamcity.cockroachdb.com/viewLog.html?buildId=31562&buildTypeId=Cockroach_UnitTests

```
SIGABRT: abort
PC=0x7fdd95a4f067 m=5
signal arrived during cgo execution

goroutine 25742 [syscall, locked to thread]:
runtime.cgocall(0x17e4ae0, 0xc422099df0, 0x0)
    /usr/local/go/src/runtime/cgocall.go:131 +0xb9 fp=0xc422099dc0 sp=0xc422099d88
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBClose(0x7fdd8d6d8b60)
    ??:0 +0x63 fp=0xc422099df0 sp=0xc422099dc0
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).Close(0xc4203f4480)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:402 +0x1bf fp=0xc422099e78 sp=0xc422099df0
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc42173a090)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:376 +0x435 fp=0xc422099f30 sp=0xc422099e78
github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContext).Stop.func1(0xc421990000, 0xc421db87e0)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:342 +0x2cb fp=0xc422099fa0 sp=0xc422099f30
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc422099fa8 sp=0xc422099fa0
created by github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContext).Stop
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:345 +0x95
```

### PR DESCRIPTION
**Pull request by petermattis**
When an outgoing snapshot is present, Replica.mu.outSnap holds an open
RocksDB iterator and snapshot. These need to be properly released when
the Store is stopped and before the associated Engine is closed in order
to avoid tickling a RocksDB assertion. Added RaftScheduler.Wait() that
blocks until the Raft scheduler worker goroutines finish. Added a new
goroutine to Store that waits for the scheduler goroutines to exit and
then loops over all of the Replicas and abandons any unsent snapshot.

Fixes #9968

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10033)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/scheduler.go, line 172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10033#-KUIzwD9NOm2JWjS7Eod:-KUIzwD9NOm2JWjS7Eoe:b6lcvne) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba0f271f017f37faf456d7222665ad57426b591e/pkg/storage/scheduler.go#L172)):*
> ```Go
> 
> func (s *raftScheduler) Start(stopper *stop.Stopper) {
> 	stopper.RunWorker(func() {
> ```

can this goroutine be reused for the wait-for-done situation?

hm, maybe not; i guess you don't have access to the store here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10033#-:-KUJ-Bfh4CyxGSYtKtRL:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/scheduler.go, line 172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10033#-KUIzwD9NOm2JWjS7Eod:-KUJ-NgHFMA3_4T2Op-M:beldj9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba0f271f017f37faf456d7222665ad57426b591e/pkg/storage/scheduler.go#L172)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this goroutine be reused for the wait-for-done situation?
> 
> hm, maybe not; i guess you don't have access to the store here.
</details>
Possibly. I thought about that, but it doesn't seem worth it. One extra goroutine per store isn't going to hurt us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10033)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10033#-:-KUJ03DhUyWxgj5pmarK:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/store.go, line 2915 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10033#-KUIyr7gatCOFI6H4-sX-r1-2915:-KUJ0W8hhNBA-50IYgAo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba0f271f017f37faf456d7222665ad57426b591e/pkg/storage/store.go#L2915)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> This should read unsent I think
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10033)*

**Pull request merged**
