### PR TITLE
sql/distsql: push down NOT NULL constraints on equality columns durin…

### LINKED ISSUE #20100: sql/distsql: push down NOT NULL constraints on equality columns during planning
We can push down a `NOT NULL` filter depending on the join type. This can reduce the data that is streamed to the join. For example, if we have:

```sql
SELECT * FROM t1 AS l INNER JOIN t1 AS r ON l.id = r.id
```

If either `l.id` or `r.id` are NULL they will never be in the join result due to `NULL = <any>` is false-y. This applies to joins that are composed of only equalities, in particular:
- All inner joins
- When doing a left or right outer join, we can push the constraint down to the other side of the join (e.g. when doing a `LEFT OUTER JOIN`, we can push it down the right side of the join)

Mentioned from https://github.com/cockroachdb/cockroach/pull/20090 and https://github.com/cockroachdb/cockroach/issues/17135#issuecomment-344744926.

cc: @RaduBerinde 

Jira issue: CRDB-5942

### PR DESCRIPTION
**Pull request by adamyaoqinglin**
fix #20100 

We can push down a NOT NULL filter depending on the join type.
This can reduce the data that is streamed to the join.

All inner joins
When doing a left or right outer join, we can push the constraint down to the other side of the join
(e.g. when doing a LEFT OUTER JOIN, we can push it down the right side of the join)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for working on this!

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expr_filter.go, line 236 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-Cnhr6skl5_ITHcnMb:-L-Cnhr6skl5_ITHcnMc:b-56h7sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce42ad0cece2d4797929a1db76cb59bd328b7b3a/pkg/sql/expr_filter.go#L236)):*
> ```Go
> 	case *tree.ComparisonExpr:
> 		if !weaker {
> 			// In the stronger (inverted) case, we donot add "IS NOT NULL" constraint.
> ```

[nit] don't (or do not). I'd also add a bit more explanation, e.g. point out that `x > 1` implies that `x IS NOT NULL` but `(NOT (x > 1))` does not imply the opposite (in fact, it implies the same).

---

*[pkg/sql/expr_filter.go, line 243 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-CoG4sy3gmBm1RVjGT:-L-CoG4sy3gmBm1RVjGU:b-p56905) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce42ad0cece2d4797929a1db76cb59bd328b7b3a/pkg/sql/expr_filter.go#L243)):*
> ```Go
> 			return tree.MakeDBool(tree.DBool(weaker)), expr
> 		}
> 		leftRes, _ := splitBoolExpr(t.TypedLeft(), conv, weaker)
> ```

This probably does what  we want, but it's pretty hard to understand. It would be more clear if we
 - check if the left side is a `tree.VariableExpr` and that `exprCheckVars()` returns true on it; if yes, return  "<left> is not null"
 - do the same for the right side

---

*[pkg/sql/opt_filters.go, line 648 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-CuZjSVIPlg5NIxkcT:-L-CuZjSVIPlg5NIxkcU:b-g43sp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce42ad0cece2d4797929a1db76cb59bd328b7b3a/pkg/sql/opt_filters.go#L648)):*
> ```Go
> }
> 
> // addEqualNotNullConj loops all the left/rightEqualityIndices to construct
> ```

loops over; to construct not-null constraint expressions.

---

*[pkg/sql/opt_filters.go, line 650 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-CudHIWR7bgjFiBzUo:-L-CudHIWR7bgjFiBzUp:b-9j47ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce42ad0cece2d4797929a1db76cb59bd328b7b3a/pkg/sql/opt_filters.go#L650)):*
> ```Go
> // addEqualNotNullConj loops all the left/rightEqualityIndices to construct
> // sqls which indicates fetching none-null values(columns).
> // For Inner Join, both left and right column should fetch none-null values.
> ```

not-null

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-:-L-CuRdX__U2iiFh87xh:b-4v1jpi)*

**Comment by arjunravinarayan** [comment]
Thank you for working on this, as well! Please address @raduberinde's comments. I have focused instead on the test results, and the distsql plan changes look great, although I have a couple questions on some of the changes.

---

Reviewed 6 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_numtables, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-CzdYRgvPBxaPy-Iq4:-L-CzdYRgvPBxaPy-Iq5:b-xvookb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7de7099c40f9c0893c59f9fd04ac22962c63dbe/pkg/sql/logictest/testdata/logic_test/distsql_numtables#L130)):*
> ```
> 
> query T
> SELECT "URL" FROM [EXPLAIN (DISTSQL) SELECT x, str FROM NumToSquare JOIN NumToStr ON y = xsquared]
> ```

This plan looks incomplete. Why is the filter only applicable to Node 1?

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-D-0HNHfTCs5UQQtvk:-L-D-0HNHfTCs5UQQtvl:bt1w1xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7de7099c40f9c0893c59f9fd04ac22962c63dbe/pkg/sql/logictest/testdata/logic_test/order_by_index#L104)):*
> ```
> 
> query ITTTTT
> EXPLAIN(METADATA) SELECT k FROM kv a NATURAL JOIN kv ORDER BY INDEX kv@foo
> ```

This change is confusing me, although it doesn't seem obviously wrong. @raduberinde can you cross-check?

---

*[pkg/sql/logictest/testdata/logic_test/physical_props, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-D-QwAE-CxrXz_SlHX:-L-D-QwAE-CxrXz_SlHY:b3bxuy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7de7099c40f9c0893c59f9fd04ac22962c63dbe/pkg/sql/logictest/testdata/logic_test/physical_props#L183)):*
> ```
> query ITTTTT colnames
> EXPLAIN (VERBOSE) SELECT * FROM abcd JOIN (SELECT * FROM efg WITH ORDINALITY) ON a=e
> ----
> ```

I don't understand this change either, cc @raduberinde 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-:-L-D-Vh1ooocOGP4-MKJ:b-yu5daa)*

**Comment by RaduBerinde** [comment]
Review status: 6 of 9 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-D-0HNHfTCs5UQQtvk:-L-D3IjwT97pvg5rnYLE:bbc8t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7de7099c40f9c0893c59f9fd04ac22962c63dbe/pkg/sql/logictest/testdata/logic_test/order_by_index#L104)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This change is confusing me, although it doesn't seem obviously wrong. @raduberinde can you cross-check?
</blockquote></details>

Because we pushed down not-null constraints, we now choose the `foo` index instead of the primary (and skip reading any null `v`s).

---

*[pkg/sql/logictest/testdata/logic_test/physical_props, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-D-QwAE-CxrXz_SlHX:-L-D3u9uuh2KgO_QQfG0:b-712i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7de7099c40f9c0893c59f9fd04ac22962c63dbe/pkg/sql/logictest/testdata/logic_test/physical_props#L183)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I don't understand this change either, cc @raduberinde 
</blockquote></details>

This doesn't look right.. we should still have a merge join order.

We're not correctly pushing the filter through the ordinality node, but the ordering should have been preserved anyway.  I would comment out the call to `simplifyOrderings` in expand_plan.go and see what orderings are there before simplifying them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341)*

**Comment by adamyaoqinglin** [comment]
Thanks for reviews.
@RaduBerinde I have changed the code accordingly.
@arjunravinarayan pkg/sql/logictest/testdata/logic_test/distsql_numtables, line 130 at r1 (raw file):
If the not-null constraint in distribute sql should be pushed down, I think it could be another issue.

**Comment by RaduBerinde** [comment]
Review status: 1 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/expr_filter.go, line 243 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-CoG4sy3gmBm1RVjGT:-L-J2uruFYrsdczbKFNE:bksy7jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce42ad0cece2d4797929a1db76cb59bd328b7b3a/pkg/sql/expr_filter.go#L243)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This probably does what  we want, but it's pretty hard to understand. It would be more clear if we
 - check if the left side is a `tree.VariableExpr` and that `exprCheckVars()` returns true on it; if yes, return  "<left> is not null"
 - do the same for the right side

</blockquote></details>

It's still not easy to understand what's going on here; the cases that are relevant will only have one useful`leftRes/rightRes`. I was suggesting something like

```go
if _, ok := t.TypedLeft().(VariableExpr); ok && exprCheckVars(t.TypedLeft(), conv) {
   return tree.NewTypedComparisonExpr(tree.IsNot, exprConvertVars(t.TypedLeft(), conv), tree.DNull)
}
if _, ok := t.TypedRight().(VariableExpr); ok && exprCheckVars(t.TypedRight(), conv) {
   return tree.NewTypedComparisonExpr(tree.IsNot, exprConvertVars(t.TypedRight(), conv), tree.DNull)
}
```
(and we should exit above if `weaker` is false)

---

*[pkg/sql/expr_filter.go, line 165 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341#-L-J4bQGC9mdb1S-KgVv:-L-J4bQGC9mdb1S-KgVw:b-nypypj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e97c45ce1c36ff7f1a6df58c939d04fae36822f5/pkg/sql/expr_filter.go#L165)):*
> ```Go
> 				notNullExpr = tree.NewTypedComparisonExpr(tree.IsNot, newExpr, tree.DNull)
> 			} else {
> 				notNullExpr = tree.NewTypedComparisonExpr(tree.Is, newExpr, tree.DNull)
> ```

I don't think this is correct. I don't think we can do anything for "!weaker".  See the comment below:
```
//  - If weaker is false:
//       E(x) = (RES(x) OR REM(x))
//    This implies RES(x) => E(x), i.e. RES is "stronger"
```

If `x` is `a > b`, we can't have RES(x) be `a IS NULL`, that makes no sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20341)*

**Comment by adamyaoqinglin** [comment]
An explanation:
The advise is:
```c
if _, ok := t.TypedLeft().(VariableExpr); ok && exprCheckVars(t.TypedLeft(), conv) {
   return tree.NewTypedComparisonExpr(tree.IsNot, exprConvertVars(t.TypedLeft(), conv), tree.DNull)
}
if _, ok := t.TypedRight().(VariableExpr); ok && exprCheckVars(t.TypedRight(), conv) {
   return tree.NewTypedComparisonExpr(tree.IsNot, exprConvertVars(t.TypedRight(), conv), tree.DNull)
}
```

However, the test case `pkg/sql/expr_filter_test.go` would get wrong,  since it tested the `return tree.UnresolvedName` in splitFilter convFunc. 
My change is that check the indexed var after the `exprConvertVars`.
```
		if exprCheckVars(t.TypedLeft(), conv) {
 			leftRes := exprConvertVars(t.TypedLeft(), conv)
 			if _, ok := leftRes.(*tree.IndexedVar); ok {
 				return tree.NewTypedComparisonExpr(tree.IsNot, leftRes, tree.DNull), expr
 			}
 		}
 		if exprCheckVars(t.TypedRight(), conv) {
 			rightRes := exprConvertVars(t.TypedRight(), conv)
 			if _, ok := rightRes.(*tree.IndexedVar); ok {
 				return tree.NewTypedComparisonExpr(tree.IsNot, rightRes, tree.DNull), expr
 			}
 		}
```

**Comment by RaduBerinde** [comment]
It should be ok in practice.. But it's not quite clean, checking after the conversion means that we're depending on what the conversion function does. What testcase is failing exactly? I would think we want the rule to apply when we run TestSplitFilter. In fact, we should add testcases there verifying the new case (e.g. {`a > b`, []string{"a"}, `a IS NOT NULL`, ...}).

**Comment by adamyaoqinglin** [comment]
The test case is `pkg/sql/expr_filter_test.go:135`, the expression it returned is unresolved name. The unresolved name can not be used in `tree.NewTypedComparisonExpr `. I also think we should add the test case, but I don't know how to do that.

**Comment by RaduBerinde** [comment]
Oh, interesting. We can create the `tree.NewTypedComparsionExpr` first, and then `exprConvertVars` that entire thing.  So something like:
```
if _, ok := t.TypedLeft().(VariableExpr); ok && exprCheckVars(t.TypedLeft(), conv) {
   newExpr := tree.NewTypedComparisonExpr(tree.IsNot, t.TypedLeft(), tree.DNull)
   return exprConvertVars(newExpr, conv)
}
```

On the other hand, the test converting to an `UnresolvedName` is a hack and can be removed. We could create new `IndexedVar`s in the test instead. See `MakeIndexedVarHelper`,

BTW if this back and forth is too tedious, feel free to leave out the `splitFilter` part from this PR and I can look at it separately.

**Comment by adamyaoqinglin** [comment]
@RaduBerinde 
Yes, we can split it into two parts and this PR only code for equality situation.

BTW, there is no tedious. I am enjoying it, since you are doing the awesome things.

**Comment by RaduBerinde** [comment]
Cool. The equality columns are the important ones in most cases anyway.

**Pull request closed without merging**
