### PR TITLE
all: fix various static checks

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### all: fix static checks (printf with dynamic string)

Fixing instances of: printf-style function with dynamic format string
and no further arguments should use print-style function instead
(SA1006).

Release note: None

#### all: fix static checks (uint >= 0 checks)

Fixing instances of "no value of type uint64 is less than 0 (SA4003)".

Release note: None

#### all: fix static checks (capitalized error messages)

Fixing instances of "error strings should not be capitalized (ST1005)".

Release note: None

#### all: fix static checks (misc checks)

Release note: None

#### tree: move error as last return of SimpleVisitFn

Main reason is to appease some linter checks of an upcoming version.

Release note: None

#### all: fix static checks (dot imports)

Removing some dot imports.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 5 of 6 files at r3, 14 of 14 files at r4, 8 of 8 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37178#-:-LddaVbYBxqkN1owePH1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/conn_fsm.go, line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37178#-Ldda2feEB_osYdjqi8H:-Ldda2feEB_osYdjqi8I:bviovol) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ca9d6f807d01b0062e890b12d5e9088e127498/pkg/sql/conn_fsm.go#L29)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/roachpb"
> 	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
> 	// We dot-import fsm to use common names such as fsm.True/False. State machine
> ```

Comment is stale.
___
*[pkg/sql/types/oid.go, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37178#-LddaHca4WF0Utephssi:-LddaHca4WF0Utephssj:b-tmuyzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/826098540768fcb41e304fd114a981bb147561cf/pkg/sql/types/oid.go#L165)):*
> ```Go
> 
> func init() {
> 	if len(oidToArrayOid) != len(oidToArrayOid) {
> ```

:see_no_evil:

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37178#-:-LddbLMT-IHsvdmrOC6a:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/sql/conn_fsm.go, line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37178#-Ldda2feEB_osYdjqi8H:-LddbKwC4rH7WOPAKFbd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ca9d6f807d01b0062e890b12d5e9088e127498/pkg/sql/conn_fsm.go#L29)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Comment is stale.
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
Hit a timeout

bors r+

**Comment by RaduBerinde** [comment]
Same failure, filed #37191.

bors r+

**Comment by tbg** [comment]
I haven't seen this one. You're sure this isn't introduced in this PR,
rihgt?

**Pull request merged**
