### PR TITLE
gossip: Fix premature DNS resolution on forward address, unskip TestGossipRestart

### PR DESCRIPTION
**Pull request by tbg**
This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5017)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/cluster/localcluster.go, line 245 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-KCR8L6WIFPR4UcJIvKg:-KCR8L6WIFPR4UcJIvKh:929848393) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ec00b19a60fbec88ed136a15e7b4df571bdc12/acceptance/cluster/localcluster.go#L245)):*
Seems more natural to put `cockroachdb_acceptance_` inside of the `fmt.Sprintf`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-:-KCR8n529HLWnZnQYqhh:676834233)*

**Comment by tamird** [comment]
last commit should include "Fixes ...."

LGTM

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[acceptance/cluster/localcluster.go, line 245 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-KCR8pJseMXnkZVT5GD9:-KCR8pJtmprtG29iZMf_:-1858280554) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ec00b19a60fbec88ed136a15e7b4df571bdc12/acceptance/cluster/localcluster.go#L245)):*
this needs a comment (just the commit message would suffice). however, I think that this is just obscuring the issue - perhaps we should try to remove this network before creating it? or else do better about cleaning it up.

---

*[acceptance/cluster/localcluster.go, line 556 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-KCR9aETmW0YvV8kuHe6:-KCR9aEUp6FUh3nDnvMH:1520224367) ([raw file](https://github.com/cockroachdb/cockroach/blob/56682c2964c03ebf5a802c6f6db915d2a1f06ac1/acceptance/cluster/localcluster.go#L556)):*
just wondering - why did this increase?

---

*[gossip/client_test.go, line 440 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-KCR9J1Xiq_lJv7K6acP:-KCR9J1Xiq_lJv7K6acQ:-715764289) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08410cf87201a93bcf2d92dc46da28e41bf6621/gossip/client_test.go#L440)):*
broken record: i don't think `%v` will render this nicely - you may need to separate the errors to get reasonable messages here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-:-KCR9er9HNEQD4DZCUSl:-920994248)*

**Comment by tschottdorf** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[acceptance/cluster/localcluster.go, line 245 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-KCR8pJseMXnkZVT5GD9:-KCRDS5vNOxLCMyiE-AQ:229101867) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ec00b19a60fbec88ed136a15e7b4df571bdc12/acceptance/cluster/localcluster.go#L245)):*
You can't guarantee cleanup, so the other option is finding the existing networks and cleaning up etc - that seems excessive as well. Also, technically we shouldn't be using fixed names for anything in these tests. There's no reason why you shouldn't be able to run multiple acceptance tests at the same time, for instance. Of course that currently fails horribly, but there's no reason to put in more places that cement this.

I'll try to look into the bug again though to see whether it needs to be filed upstream.

---

*[acceptance/cluster/localcluster.go, line 556 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-KCR9aETmW0YvV8kuHe6:-KCRC57OOARqVj0DVAG9:-623380901) ([raw file](https://github.com/cockroachdb/cockroach/blob/56682c2964c03ebf5a802c6f6db915d2a1f06ac1/acceptance/cluster/localcluster.go#L556)):*
this fails occasionally locally, and while I don't think it's because of the timeout (probably just the event never firing), this will make it clearer which one it is. Other than that, just homogenizing with the 15s we use elsewhere (`SucceedsSoon`).

---

*[gossip/client_test.go, line 440 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-KCR9J1Xiq_lJv7K6acP:-KCRCPGlxUjuwX9zJE02:406027112) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08410cf87201a93bcf2d92dc46da28e41bf6621/gossip/client_test.go#L440)):*
now `client_test.go:442: unexpected forward address localhost:2345, expected localhost:2375` will do, I hope.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017)*

**Comment by spencerkimball** [comment]
LGTM

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017)*

**Comment by bdarnell** [comment]
First commit message should say "look up a network", not "look up a name"

LGTM

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5017#-:-KCRssrAeC9qwRVdTqJW:1277420683)*

**Pull request merged**
