### PR TITLE
opt: simplify ScalarBuilder.Build

### PR DESCRIPTION
**Pull request by mgartner**
Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This was a refactor commit from #107767 that I thought I'd try to get merged.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108217#-:-NbG1teU3xPV_GfuWm-W:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108217#-:-NbGYv8b6Qf48ODf8td4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
