### PR TITLE
cli: Enable use of environment variable to override configuration flags

### LINKED ISSUE #2706: cli: environment variables for certs dir and addr and other cli flags
Would it make sense to allow the `cockroach` CLI command to read various environment variables as defaults for the available flags? 

For example, a number of environment variables could be defined that allow various flags to have default values set that are specific to a given server/node.

- `CDB_BASE_DIR`: Base directory for the CockroachDB installation. Could also be used to add CochroachDB to `PATH`.
- `CDB_CERTS_DIR`: Directory that contains SSL certs that falls back to `$CDB_BASE_DIR/certs`.
- `CDB_DATA_DIR`: Directory that contains the RocksDB database files.

Currently, I'm adding `--certs` to many commands when I run `cockroach` outside of the installation directory. For example: `cockroach user set user1 --certs="$CDB_CERTS_DIR"`.

If this sounds like something that would make sense then I'll start on writing the code to implement it.

### PR DESCRIPTION
**Pull request by knz**
The order of configuration is:
1. command line flag, if set,
2. env var, if set and valid,
3. default value

For each flag "x", the env var is COCKROACH_X ("x" upper-cased)

A new CLI command "env" dumps all known environment variables.

**noteworthy**:
- "MetricsFrequency" has been renamed to "MetricsSampleInterval"
  (the accompanying env. var. is COCKROACH_METRICS_SAMPLE_INTERVAL)
- the following environment variables have been renamed:
  - ANNOTATE_TRACES -> COCKROACH_ANNOTATE_TRACES
  - RANDOM_SEED -> COCKROACH_RANDOM_SEED
  - ENABLE_LOCAL_CALLS -> COCKROACH_ENABLE_LOCAL_CALLS

Fixes #2706.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5430)

### CODE REVIEW

**Comment by tschottdorf** [comment]
#2706 was about setting client flags. Are you sure we want to suck in all
sort of configuration variables from the env? If so, I'd like that gated
behind a parameter `--from-env` which forces everything to be specified
through the environment (and I would suggest that we Fatal on start if any
of the environment variables are found nonempty and `--from-env` isn't
set). Maybe everyone else thinks this is fine, but I've had enough trouble
with stuff getting in from the environment (COCKROACH_DEV), and I think
it's worth being a little careful about it.

**Comment by bdarnell** [comment]
I don't think we want to add support for most flags to be specified by the environment. I think it would be nice to have environment-variable equivalents for enough flags for `cockroach sql` to work with no other arguments (host, port, user, certs), but other client flags like `--max-results` should remain command-line only, and I don't think the server should use environment variables at all for any of its documented functionality (the various undocumented hacks we have are OK for now but I'd prefer to migrate those to an "advanced use" subset of the command line, or into the database itself).

**Comment by knz** [comment]
@tschottdorf it's really hard to get the environment variables to be read after the command-line flags unless we want to implement a lot of code duplication. So I'd rather have verbose message in the log file to indicate when a value was picked up from the environment instead of `--from-env`.

@bdarnell @tschottdorf It's not clear to me yet which configuration we want to pick from the environment. Here is the list of what I implemented, please annotate which one(s) you'd prefer to keep out:

```
COCKROACH_INSECURE # server/client

COCKROACH_ANNOTATE_TRACES # server
COCKROACH_ATTRS # server
COCKROACH_CACHE # server
COCKROACH_ENABLE_CHECK_MONOTONIC_TIME # server
COCKROACH_ENABLE_LOCAL_CALLS # server
COCKROACH_JOIN  # server
COCKROACH_RANDOM_SEED  # server
COCKROACH_SERVER_HOST  # server
COCKROACH_SERVER_HTTP_PORT  # server
COCKROACH_SERVER_PORT  # server
COCKROACH_SIMULATED_OFFSET # server

COCKROACH_CA_KEY  # cert gen
COCKROACH_CA_CERT # certs
COCKROACH_CERT  # certs
COCKROACH_KEY  # certs
COCKROACH_KEY_SIZE  # cert gen

COCKROACH_MAX_RESULTS  # kv util

COCKROACH_URL  # CLI admin

COCKROACH_DATABASE # client
COCKROACH_DATABASE_HOST # client
COCKROACH_DATABASE_HTTP_PORT # client
COCKROACH_DATABASE_PORT # client
COCKROACH_PASSWORD  # client 
COCKROACH_USER  # client
```

**Comment by bdarnell** [comment]
I think the following environment variables should be supported for client commands:

```
COCKROACH_INSECURE # server/client
COCKROACH_CA_CERT # certs
COCKROACH_CERT  # certs
COCKROACH_KEY  # certs
COCKROACH_URL  # CLI admin
COCKROACH_DATABASE # client
COCKROACH_HOST # client
COCKROACH_HTTP_PORT # client
COCKROACH_PORT # client
COCKROACH_PASSWORD  # client 
COCKROACH_USER  # client
```

The cert/key flags and the insecure flags should be read from the environment only in client commands, not for the server (and probably not for the cert creation commands, but I'm not sure about that. If we do support env vars for cert creation then CA_KEY should also be included). The host/port flags should not contain the word `DATABASE`.

**Comment by knz** [comment]
Ok so this changeset boils down to the following:

- there are 2 kinds of environment variables: 1) documented, user-facing variables, these are reduced to the set listed by @bdarnell above. These now also appear in the output of `help`. 2) undocumented, developer-oriented variables, these already existed prior to this changeset, including `COCKROACH_MAX_OFFSET`, `COCKROACH_ENABLE_LOCAL_CALLS` and a few others.
- the code now also checks that the same env var is not given two different meanings at different places in the source base.
- `cockroach env` prints out both documented and undocumented variables, because we need both for debugging.

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 2 of 23 files at r2, 11 of 23 files at r4, 11 of 12 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[Makefile, line 182 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDqxIn-V89njlBA76E:-KEDqxIoZajIhaeXeJZf:877652394) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/Makefile#L182)):*
s/envutils/envutil/

---

*[cli/flags.go, line 66 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDtqVHOwGcxWMH2BZ4:-KEDtqVIG18b67bmoh6j:1975256898) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/cli/flags.go#L66)):*
The default is now 25% of physical memory.

---

*[cli/flags.go, line 314 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDuHypKUUorqKsneCv:-KEDuHyqUaxPJnxWXhuO:1509716857) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/cli/flags.go#L314)):*
This transformation should be a function in `envutil`.

---

*[cli/flags.go, line 323 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDu301_6Bd7F5r6Ic8:-KEDu301_6Bd7F5r6Ic9:-731769502) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/cli/flags.go#L323)):*
I would flip the names here: `usage` should not have the env var since that looks like the more common case, and the places that want it should opt in to `usageEnv`. Or we should have `usageEnv` and `usageNoEnv`.

---

*[util/envutil/env.go, line 32 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDrxBhUjrFAeD0PPtU:-KEDrxBhUjrFAeD0PPtV:359079007) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/util/envutil/env.go#L32)):*
The comment should specify that each environment variable may only be accessed from one place, and that access should be made at startup so it can be included in the `cockroach env` report. 

---

*[util/envutil/env.go, line 59 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDsfl8AO5if9pra5PT:-KEDsfl8AO5if9pra5PU:-1843569204) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/util/envutil/env.go#L59)):*
If this report is for end users we probably don't want to include consumer information in it, since that's just implementation details. If it's for us then we can include it but the command should probably be under `cockroach debug env` instead of a top-level command.

---

*[util/humanizeutil/humanize_test.go, line 17 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDrBbmSjS9Met6yLw-:-KEDrBbmSjS9Met6yLw0:1238447279) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/util/humanizeutil/humanize_test.go#L17)):*
This could just be `package humanizeutil` and then you wouldn't need to qualify the names below.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-:-KEDwFbJm5Ffd7CluuNn:676834233)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[Makefile, line 182 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDqxIn-V89njlBA76E:-KEE9ThQXl0sDYkeC3Ji:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/Makefile#L182)):*
Done.

---

*[cli/flags.go, line 66 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDtqVHOwGcxWMH2BZ4:-KEEASpbZYgbHtmf81Sm:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/cli/flags.go#L66)):*
Done.

---

*[cli/flags.go, line 314 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDuHypKUUorqKsneCv:-KEEAkcRGMhZfGruXS_9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/cli/flags.go#L314)):*
Done.

---

*[cli/flags.go, line 323 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDu301_6Bd7F5r6Ic8:-KEEAvcrNgaKy9IcwFdB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/cli/flags.go#L323)):*
Done.

---

*[util/envutil/env.go, line 32 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDrxBhUjrFAeD0PPtU:-KEEBUdiwrC8lwoUl0JQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/util/envutil/env.go#L32)):*
Done.

---

*[util/envutil/env.go, line 59 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDsfl8AO5if9pra5PT:-KEEC0o5OkgBByGCCPZn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/util/envutil/env.go#L59)):*
Done.

---

*[util/humanizeutil/humanize_test.go, line 17 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEDrBbmSjS9Met6yLw-:-KEECCfRuIxDfUNSWry_:-2017995611) ([raw file](https://github.com/cockroachdb/cockroach/blob/359fbb36d5bb77124443cbd1c4856886c9ad0c53/util/humanizeutil/humanize_test.go#L17)):*
No can do because of a circular dependency.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 20 of 23 files at r2, 2 of 23 files at r4, 2 of 20 files at r7.
Review status: 0 of 18 files reviewed at latest revision, 12 unresolved discussions.

---

*[kv/send.go, line 223 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESvU1c_2kPmzybL91:-KEESvU1c_2kPmzybL92:677963634) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/kv/send.go#L223)):*
why init?

---

*[util/envutil/env.go, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEERvTVMCEewWT0uQZQ:-KEERvTVMCEewWT0uQZR:541360779) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L35)):*
you can inline this into the `if` - `f` is not used outside the block

---

*[util/envutil/env.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEES0_WWx3dl9oYHMHe:-KEES0_WWx3dl9oYHMHf:-1509777874) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L56)):*
really a nit: we tend to use bytes.Buffer for stuff like this

---

*[util/envutil/env.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESH4YpHvXaXYzoq8P:-KEESH4YpHvXaXYzoq8Q:-1842981004) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L72)):*
this is repeated quite a bit; you could extract into a shared method that caller runtime.Caller(2).

---

*[util/tracing/annotate.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEER4S0ws4_Qtv0h-5l:-KEER4S14ChNLwfDyJwC:-1014227531) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/tracing/annotate.go#L27)):*
throughout: why does this suddenly need to be in `init`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by tamird** [comment]
Reviewed 5 of 23 files at r2, 21 of 23 files at r3, 23 of 23 files at r4, 12 of 12 files at r5, 20 of 22 files at r6, 20 of 20 files at r7.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[cli/flags.go, line 310 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEEWs-WmF278z_6exBm:-KEEWs-XPHfi2MUbeTMQ:-565536233) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e4aa42dc75dda9ac77c3c5d252b3ac1d0df21c/cli/flags.go#L310)):*
looks like this function just moved - the diff may be smaller if you keep it in its original location. also, the comment has the function name wrong.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by tamird** [comment]
This is great! Just a few comments.

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[cli/flags.go, line 310 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEEWs-WmF278z_6exBm:-KEFUgTP1G9l1oJkg3f1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e4aa42dc75dda9ac77c3c5d252b3ac1d0df21c/cli/flags.go#L310)):*
Done.

---

*[kv/send.go, line 223 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESvU1c_2kPmzybL91:-KEFVSWnWngNlZLY_MIx:989170653) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/kv/send.go#L223)):*
Didn't know you can call a function in a global initializer.

---

*[util/envutil/env.go, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEERvTVMCEewWT0uQZQ:-KEFWeGmLPfaa4x0ukie:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L35)):*
Done.

---

*[util/envutil/env.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEES0_WWx3dl9oYHMHe:-KEFXkw6mEf0D07Ke1s8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L56)):*
Done.

---

*[util/envutil/env.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESH4YpHvXaXYzoq8P:-KEFWIy7qxDAn_cIWsKS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L72)):*
Done.

---

*[util/tracing/annotate.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEER4S0ws4_Qtv0h-5l:-KEFXvB7gfSsWbzflp29:-1631649668) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/tracing/annotate.go#L27)):*
It doesn't.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[util/envutil/env.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESH4YpHvXaXYzoq8P:-KEG1IHozQMbo2FCE1oO:-820327145) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L72)):*
I think you can pull the `GetEnv(name, c)` into the common function too.

---

*[util/envutil/env.go, line 62 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEG13Js7nkqHQpOiUd9:-KEG13JtX8CEfCJdYDa-:-1946682007) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e1c2196dedd04fd280dbcdff0dab958ead4883a/util/envutil/env.go#L62)):*
no need to `new` this - you can just `var b bytes.Buffer`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[util/envutil/env.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESH4YpHvXaXYzoq8P:-KEHfg-3QHs1xbIChGdK:1618712150) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L72)):*
I'm not sure that's desirable; my idea was to export GetEnv as a general replacement for os.Getenv.

---

*[util/envutil/env.go, line 62 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEG13Js7nkqHQpOiUd9:-KEHfbwTFwl1Gdzmm5w3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e1c2196dedd04fd280dbcdff0dab958ead4883a/util/envutil/env.go#L62)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[util/envutil/env.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESH4YpHvXaXYzoq8P:-KEHhBoCvdDxLhGvW9OJ:340396377) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L72)):*
OK. I thought GetEnv wasn't used outside this package, but maybe I was mistaken.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[util/envutil/env.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-KEESH4YpHvXaXYzoq8P:-KEHiYmWgrJ4YVEJ0uY2:1068978189) ([raw file](https://github.com/cockroachdb/cockroach/blob/f86aac720863bed7d9252edd82eb767f15514884/util/envutil/env.go#L72)):*
You're right it's not currently used.
However this patch also adds a linter to advise its use instead of os.Getenv. It would be surprising to users hitting the linter error to not find the API.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430)*

**Comment by knz** [comment]
Changed the linter as suggested by @tamird and un-exported GetEnv.

**Comment by tamird** [comment]
retroactive :lgtm:

---

Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5430#-:-KEI9bctpUCDxrFmlEIb:-542510131)*

**Comment by jseldess** [comment]
Docs here: https://www.cockroachlabs.com/docs/cockroach-commands.html#environment-variables

**Pull request merged**
