### PR TITLE
ui: update login page with docs link, SQL command

### PR DESCRIPTION
**Pull request by vilterp**
- update docs link to point at specific docs for configuring login
- add SQL command to create user
- a couple of copy changes: "console" => "web ui"; "sign in" => "log in"

Before:
image

After:
image

### CODE REVIEW

**Comment by Amruta-Ranade** [comment]
Text suggestion: "New in v2.1: Sign in with your user credentials to access the Web UI for your secure cluster. Use the following command to create a CockroachDB user with password authentication:"

**Review by BramGruneir — CHANGES_REQUESTED** [review]
There was no mention of changing the svgs in the commit message, please add it.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-:-LJtoniLB0v8qQ8Mthq6:b-nmbn2p)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/util/docs.ts, line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtp-uF8bj3akwkeetR:-LJtp-uF8bj3akwkeetS:b-ah6oju) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac3d53f47ba9430ede4fd60572c3125552d3cd3d/pkg/ui/src/util/docs.ts#L10)):*
> ```XML
> }
> 
> export const adminUILogin = docsURL("admin-ui-access-and-navigate.html#secure-the-admin-ui");
> ```

this fix should be back in the earlier commit, please move it.
___
*[pkg/ui/src/views/app/components/layoutSidebar/index.tsx, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtp8zG6gn1iRDnLh0f:-LJtp8zG6gn1iRDnLh0g:b-phu2ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac3d53f47ba9430ede4fd60572c3125552d3cd3d/pkg/ui/src/views/app/components/layoutSidebar/index.tsx#L97)):*
> ```XML
>           { user[0] }
>         </div>
>         <Link to={LOGOUT_PAGE} onClick={handleLogout}>Log Out</Link>
> ```

Please add that you've changed it from `sign in` to `log in` in the description of the 3rd commit. 
___
*[pkg/ui/src/views/login/loginPage.tsx, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtoQqhA0pC289b632j:-LJtoQqi9yVKFwSZjoZH:bcelie0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314c2ae65c3d2d1e358131b590b52eb3b268a97/pkg/ui/src/views/login/loginPage.tsx#L103)):*
> ```XML
>             </p>
>             <div>
> ```

why is this an empty div?  And if it is an empty div, why not <div/>
___
*[pkg/ui/src/views/login/loginPage.tsx, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtoZ5J-M_w-izOChOk:-LJtoZ5J-M_w-izOChOl:b9mkml4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a08d98a0133aeb445cfb630057f481b8560886a/pkg/ui/src/views/login/loginPage.tsx#L113)):*
> ```XML
>           </section>
>           <section className="section login-page__form">
>             <h1 className="heading">Sign in to the Web UI</h1>
> ```

nit: Cluster Control Center

**Review by vilterp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28355)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/util/docs.ts, line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtp-uF8bj3akwkeetR:-LJuiDps47D9bX0CsIpX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac3d53f47ba9430ede4fd60572c3125552d3cd3d/pkg/ui/src/util/docs.ts#L10)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

this fix should be back in the earlier commit, please move it.
</blockquote></details>

Done.
___
*[pkg/ui/src/views/app/components/layoutSidebar/index.tsx, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtp8zG6gn1iRDnLh0f:-LJuiEp65-cbm33HtyTX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac3d53f47ba9430ede4fd60572c3125552d3cd3d/pkg/ui/src/views/app/components/layoutSidebar/index.tsx#L97)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add that you've changed it from `sign in` to `log in` in the description of the 3rd commit. 
</blockquote></details>

Done.
___
*[pkg/ui/src/views/login/loginPage.tsx, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtoQqhA0pC289b632j:-LJuiFgHCN0p0u60LNUw:b-m336l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314c2ae65c3d2d1e358131b590b52eb3b268a97/pkg/ui/src/views/login/loginPage.tsx#L103)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

why is this an empty div?  And if it is an empty div, why not <div/>
</blockquote></details>

Done. Wasn't supposed to be there.
___
*[pkg/ui/src/views/login/loginPage.tsx, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-LJtoZ5J-M_w-izOChOk:-LJuiJ4aBnJosqxSCk7S:b-xvjh1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a08d98a0133aeb445cfb630057f481b8560886a/pkg/ui/src/views/login/loginPage.tsx#L113)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit: Cluster Control Center
</blockquote></details>

I thought it was Cockroach Colony Control Center, haha

**Review by BramGruneir — APPROVED** [review]
:lgtm:

But please mention the addition of the SVGs in the appropriate commit message.

> Reviewed 4 of 5 files at r4, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-:-LJys7EQEdl62rZ6lY8N:b-a2wzr3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by vilterp** [comment]
Done; TFTR.

bors r+

**Review by BramGruneir — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28355#-:-LJyt2EI4N5DwsC6k7lo:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
