### PR TITLE
ui: open TimeScaleDropdown directly to the custom menu when custom is selected

### LINKED ISSUE #78499: Enhance the time range selectors for better usability
We should enhance the usability of the time range selectors we have in the console. Specifically, 

- If you were already rendering a custom range, the time picker should expand back to custom range pick when clicked. Today's behavior forces the user to click through the relative duration shorthands menu first. 
- In the time selector menu, we should also have a link to allow the user to quickly go to the relative duration shorthands list if they were at the custom range select view
- ~Allow text entry in the time selector~ broke out into https://github.com/cockroachdb/cockroach/issues/80655

Jira issue: CRDB-14160

### PR DESCRIPTION
**Pull request by jocrl**
Fixes #78499

This commit modifies the TimeScaleDropdown so that if a custom time is currently
select it opens directly to the custom selection menu, and a "Preset Time
Ranges" navigation link to go to the preset options from the custom menu.

This commit also cleans up the unused DateRange component.

https://user-images.githubusercontent.com/91907326/170353048-a52974dc-fd39-48f6-a228-f17fc974607d.mov

Release note (ui): The time picker now opens directly to the custom time
selection menu when a custom time is already selected. A "Preset Time Ranges"
navigation link has been added to go to the preset options from the custom
menu.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
looks great! 
just a tiny nit, otherwise :lgtm: 

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81855#-:-N3-jt_A40JL6eXAlz4e:b-9qakll)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @1lann and @jocrl)

___
*[`pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.spec.tsx` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81855#-N3-jhs16ksuucUD3rSg:-N3-jhs16ksuucUD3rSh:b-cowji) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798c0a3a7d65d32b8869fea8e527d6ae99e0fa7/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.spec.tsx#L207)):*
> ```XML
>     );
> 
>     // When a preset option is selected, the dropdown should open to other preset options
> ```

small nit: add period to the end of all comments

**Comment by jocrl** [comment]
TFTR!

@Annebirzin, just checking that the spacing for "Preset Time Ranges" looks good?

**Comment by jocrl** [comment]
Added periods to comments.

**Comment by Annebirzin** [comment]
looks good, thanks @jocrl!

**Pull request merged**
