### PR TITLE
storage: combine applied index and stats keys into RangeAppliedState key

### LINKED ISSUE #13392: perf: investigate if our "key" overhead has a performance impact on writes
We have a 3 key overhead when applying a write operation. For any `BatchRequest` that contains a write operation we also write the keys:
* `/Local/RangeID/<id>/r/RaftAppliedIndex`
* `/Local/RangeID/<id>/r/LeaseAppliedIndex`
* `/Local/RangeID/<id>/r/RangeStats`

Since these keys are all written in the same batch using keys derived from the same range ID and they are all read at the same time, it is feasible to combine their state into a single key. An initial hacky experiment to see if this would provide any performance benefit failed (no noticeable benefit), but we should pay attention to the overhead here. The space consideration is minimal, but each key needs a separate entry in the RocksDB MemTable.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #13392.

This change creates a new replicated range-local key called the
RangeAppliedState key. The key holds a combination of the Raft applied
index, the lease applied index, and the MVCC stats. Each of these pieces
of metadata is written on every single Raft application, so combining them
into single RocksDB key reduces the required number of keys touched on
each Raft application down from 3 to 1.

Preliminary benchmarking of this change confirms the expected performance
improvement. When running `./kv --read-percent=0` locally I see a 5-8%
improvement in throughput and 4-6% reduction in avg latency.

----

#### Initial States

For existing clusters, the old keys are supported and will continue to work
as expected.

For freshly bootstrapped ranges, we call into `writeInitialReplicaState` with
the cluster settings. This function internally checks whether
`IsMinSupported(VersionRangeAppliedStateKey)`. If so, it bootstraps the range
using the new RangeAppliedState key. If not, it creates the replica state as
usual without the key.

For new ranges created during a split, the new replica state is created with
`writeInitialReplicaState`. Again, this checks the cluster setting to determine
whether to use the RangeAppliedState or not. Since this is done in the split
trigger above raft instead of below raft, this is safe.

For new replicas added to an existing range, the new replica is bootstrapped
using a snapshot. Snapshots preserve the existing state of the leaseholder's
`UsingAppliedStateKey` flag. Snapshots also preserve the leaseholder's existing
keys, so the new replica will have either a `RangeAppliedState` key or all three
legacy keys, just like the leaseholder who sent it the snapshot. See the snapshot
"transition path" for more details.

#### Transition Paths

For a leaseholder of a range that is not using the new key, it can transition to
begin using it by proposing an "upgrade" flag on a `ReplicatedEvalResult.State`.
In order to transition, it must first ensure that
`IsMinSupported(VersionRangeAppliedStateKey)`. If this is the case then it can
be sure that all nodes in the cluster will be able to handle the key properly.
It then sends the flag through Raft. During command application, the flag is
picked up. If the range has already migrated to using the new flag then it won't
do anything special - this ensures that the flag is idemptotent. If the range
has not already migrated to using the new flag then it will begin a migration.
The migration removes the legacy keys and begins writing the new
`RangeAppliedState` key. As usual, this is deterministic so each follower who
processes the command will do the exact same thing.

For a follower that misses the proposal with the upgrade flag and needs to be
caught up using a Raft snapshots, the `UsingAppliedStateKey` flag will be
propagated through the `ReplicaState` field in the `SnapshotRequest_Header`.
This is used to replace the follower's `ReplicaState` wholesale. In addition,
the snapshot will include either the `RangeAppliedState` or the three legacy
keys, which are the persistent representation of the `UsingAppliedStateKey`
flag and will always agree with it. Because of this, no special handling is
needed. If the leader has migrated to the new key then the snapshot will
reflect that. If it has not migrated to the new key, then the snapshot will
reflect that.

#### Version Safety

It would be a problem if a node that is unaware of the `RangeAppliedState` ever
saw it. This is prevented by `IsMinSupported` checks wherever the key may be
written or migrated to.

----

The change is still a WIP because the changes made to ComputeStatsGo needs
to be ported over to C++.

Release note (performance improvement): Fewer disk writes are required
for each database write, increasing write throughput and reducing
write latency.

### CODE REVIEW

**Comment by bdarnell** [comment]
I'm afraid this still needs a cluster version migration. We must support both upgrades and downgrades until the new cluster version is set. Given that, I think it would be better to maintain consistency across all the replicas instead of all this magic to allow them to diverge without messing up the stats. I think we could do this with a MigrateAppliedState flag in ReplicatedEvalResult which is set by the leaseholder on the first command it proposes after the appropriate version becomes MinSupported. 

---

Reviewed 5 of 13 files at r1, 9 of 16 files at r2, 1 of 1 files at r3, 21 of 21 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/cli/debug.go, line 306 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22317#-L4YR9KqjEMlwAwU6waL:-L4YR9KqjEMlwAwU6waM:b-h799py) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6991c3685e6bff9f2e11acde35583f2cf5c6ed/pkg/cli/debug.go#L306)):*
> ```Go
> 		msg = &roachpb.Lease{}
> 
> 	case bytes.Equal(suffix, keys.LocalRangeStatsLegacySuffix):
> ```

Add a case here for the new applied state key.

---

*[pkg/storage/engine/migration_iter.go, line 72 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22317#-L4YP7VTAV8oTliN2row:-L4YP7VTAV8oTliN2rox:b-mecb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6991c3685e6bff9f2e11acde35583f2cf5c6ed/pkg/storage/engine/migration_iter.go#L72)):*
> ```Go
> 
> // Seek implements the SimpleIterator interface.
> func (mi *MigrationIterator) Seek(key MVCCKey) { mi.it.Seek(key) }
> ```

Don't we need to `resetSynthesizedState`/`maybeSynthesizeKey` here?

---

*[pkg/storage/engine/migration_iter.go, line 165 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22317#-L4YQ4R62ThE_yRWu7UI:-L4YQ4R62ThE_yRWu7UJ:bv5pect) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6991c3685e6bff9f2e11acde35583f2cf5c6ed/pkg/storage/engine/migration_iter.go#L165)):*
> ```Go
> 
> 			// Replicated range-local keys replaced by range applied state key.
> 			// Synthesize using cached range applied state key.
> ```

So we're relying here that the applied state key comes lexically before any of the three keys it replaces and that any uses of this type iterate over at least that much of the keyspace? This seems subtle and fragile. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22317#-:-L4YSTOsogwLQHHRQfe1:b9lguoy)*

**Comment by petermattis** [comment]
> I'm afraid this still needs a cluster version migration.

Ugh, you're probably right. I have a growing worry about the various migrations we're introducing in 2.0 and that we don't have adequate testing of the upgrade and downgrade paths. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22317#-:-L4faNwXbRFajBZ0ihyr:beqpmgc)*

**Comment by nvanbenschoten** [comment]
> I'm afraid this still needs a cluster version migration. We must support both upgrades and downgrades until the new cluster version is set.

Yeah, you're right about this. As I brought up today though, this doesn't necessarily mean we need to maintain consistency across replicas. I see two approaches we could take here:

#### Check MinSupported beneath Raft

Introduce a new cluster version and wrap the changes we made here in `applyRaftCommand` with a check to `IsMinSupported(newVersion)`, which ensures that the cluster will never be downgraded. This would still allow replicas to become inconsistent, so the machinery around `MigrationIter` would need to stay. However, it would allow us to avoid adding any new flags to `ReplicatedEvalResult ` while preventing the issue you brought up about downgrades.

#### Add MigrateAppliedState flag to ReplicatedEvalResult

Add a `usingAppliedStateKey` flag to the `Replica.mu` struct. This flag would be set to true in three different places. First, it would be set `initRaftMuLockedReplicaMuLocked` by performing an MVCCGet on the `ReplicaAppliedState` key and checking if it is present. Second, it would be set in `applySnapshot` by checking whether the snapshot contains the key. Third, it would be set in `applyRaftCommand` when the `MigrateAppliedState` flag you mentioned on `ReplicatedEvalResult` was set. 

This flag would be set on `ReplicatedEvalResult` by a leaseholder whenever `!r.mu.usingAppliedStateKey && IsMinSupported(newVersion)`. This means that it may be set for a few proposals in a row, which avoids concerns about proposals or rejected proposals, but does not require that it be set on proposals after the migration is complete. Beneath raft, we would write to the new `ReplicaAppliedState` key if `r.mu.usingAppliedStateKey` and the old keys if not.

This second proposal avoids most of the complication introduced in this change. It also avoids needing to allow more inconsistency between replicas in the replicated keyspace. For these two reasons, I think it's the approach we should go with (which sadly means throwing out all this code). 

@bdarnell Does the second proposal line up with your expectation? Is it missing anything obvious?

**Comment by nvanbenschoten** [comment]
This PR has been re-written to implement the second proposal described above. In doing so, a lot of the complexity was removed and I'm a lot more satisfied with the result. PTAL (but no rush, this won't be usable until 2.1).

**Comment by nvanbenschoten** [comment]
Review status: 3 of 42 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/cli/debug.go, line 306 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L4YR9KqjEMlwAwU6waL:-L9M2Euc1VNxnHE3wUVv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6991c3685e6bff9f2e11acde35583f2cf5c6ed/pkg/cli/debug.go#L306)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this is still needed.
</blockquote></details>

Done.

---

*[pkg/storage/replica_eval_context_span.go, line 136 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9HGFK-EzQz70v3vLNZ:-L9M4mi4D8VW-dyHdzu_:b-btu1qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/replica_eval_context_span.go#L136)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How does the command queue work with this transition? Shouldn't we require commands to declare the new combined key? 
</blockquote></details>

It doesn't really make a difference because nothing else declares the `RangeStatsLegacyKey`, even when writing to it. 

I added a comment that regardless of the state of the `RangeAppliedStateKey`, all commands should continue to declare the `RangeStatsLegacyKey` when they access the stats.

---

*[pkg/storage/engine/mvcc.go, line 53 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9HJ0M89iTO0mrwbLw9:-L9M6Q_t6_nChy8oT8jT:b-2cv6br) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/engine/mvcc.go#L53)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why don't we need similar accounting for the new key? I see where calls to this method have been removed, but don't see where each of those calls is getting replaced. 
</blockquote></details>

The calls to `AccountForLegacyMVCCStats` were all moved to `writeInitialReplicaState`.

We don't need to account for the new key because we're ignoring it in all stats computations. The reason we do this is because it contains variable length fields. This is an alternative to doing what we did with MVCCStats where we had to use fixed length fields and deal with this `AccountForSelf` mess. 

---

*[pkg/storage/engine/rocksdb.go, line 2010 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9G_2hj2hxcJ8lpTP9m:-L9M7eKf294EzhJluDAE:bwwp21t) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/engine/rocksdb.go#L2010)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Don't forget this. 
</blockquote></details>

I won't. I was just waiting for everything else to check out before addressing it because it requires us to move some extra decoding logic into C++.

---

*[pkg/storage/engine/enginepb/mvcc3.proto, line 95 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9HBjs24ZVKPY44vo4u:-L9M8GriBnDhiqkHrwSu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/engine/enginepb/mvcc3.proto#L95)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"unsigned" isn't quite right here. They're signed, they're just less efficient at negative numbers. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 8 of 16 files at r11, 1 of 1 files at r12, 30 of 30 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_eval_context_span.go, line 136 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9HGFK-EzQz70v3vLNZ:-L9MQ4uS9o_E6C1K8Fxn:b-dc6zr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/replica_eval_context_span.go#L136)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It doesn't really make a difference because nothing else declares the `RangeStatsLegacyKey`, even when writing to it. 

I added a comment that regardless of the state of the `RangeAppliedStateKey`, all commands should continue to declare the `RangeStatsLegacyKey` when they access the stats.
</blockquote></details>

Hmm. If it's written without declaring a write, why do we need to declare a read to access the in-memory stats? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-:-L9MQOaY65KtJpsh5z0p:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 12 of 47 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica_eval_context_span.go, line 136 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9HGFK-EzQz70v3vLNZ:-L9RY6zyB8Dnn3ZHJVH4:b-akd7o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/replica_eval_context_span.go#L136)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Hmm. If it's written without declaring a write, why do we need to declare a read to access the in-memory stats? 
</blockquote></details>

Yeah, I think you're right that we don't need to ever declare the stats key or check for it. This dates back all the way to https://github.com/cockroachdb/cockroach/pull/14524/files#diff-cf18e61e68032d3a2f950f61282f0ee9R714. Did something change since then?

---

*[pkg/storage/engine/rocksdb.go, line 2010 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9G_2hj2hxcJ8lpTP9m:-L9RY_If3ay8G4o2qWy4:bjziw5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/engine/rocksdb.go#L2010)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I won't. I was just waiting for everything else to check out before addressing it because it requires us to move some extra decoding logic into C++.
</blockquote></details>

Done. PTAL (last time, I promise!)

I had to port a few encoding functions to C++, so there's also one new commit.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 33 files at r15, 34 of 34 files at r16.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_eval_context_span.go, line 136 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9HGFK-EzQz70v3vLNZ:-L9ewkQTB5rfUMboyjBr:b-urvbhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/replica_eval_context_span.go#L136)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I think you're right that we don't need to ever declare the stats key or check for it. This dates back all the way to https://github.com/cockroachdb/cockroach/pull/14524/files#diff-cf18e61e68032d3a2f950f61282f0ee9R714. Did something change since then?
</blockquote></details>

I don't think anything's changed; it was unnecessary from the beginning. I was following the example of all the other replica state which is managed as regular keys, but MVCCStats are special. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-:-L9ewtSY9WCV-yl0IX7q:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_eval_context_span.go, line 136 at r9](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317#-L9HGFK-EzQz70v3vLNZ:-L9f1Q8d79zrLKcpcsco:b8sejxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9ff1e6df0e9db7ae5ec5ff4fb7f7b0e147684d/pkg/storage/replica_eval_context_span.go#L136)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think anything's changed; it was unnecessary from the beginning. I was following the example of all the other replica state which is managed as regular keys, but MVCCStats are special. 
</blockquote></details>

I'll send a follow up change to address this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22317)*

**Pull request merged**
