### PR TITLE
sql/parser: Add new SQL grammar for row-level security (RLS)

### LINKED ISSUE #136692: sql: Add RLS SQL Grammar
This issue introduces the following grammar changes for new SQL statements related to row-level security (RLS):
```
DROP POLICY [ IF EXISTS ] name ON table_name [ CASCADE | RESTRICT ]

CREATE POLICY name ON table_name
    [ AS { PERMISSIVE | RESTRICTIVE } ]
    [ FOR { ALL | SELECT | INSERT | UPDATE | DELETE } ]
    [ TO { role_name | PUBLIC | CURRENT_ROLE | CURRENT_USER | SESSION_USER } [, ...] ]
    [ USING ( using_expression ) ]
    [ WITH CHECK ( check_expression ) ]

ALTER POLICY name ON table_name RENAME TO new_name

ALTER POLICY name ON table_name
    [ TO { role_name | PUBLIC | CURRENT_ROLE | CURRENT_USER | SESSION_USER } [, ...] ]
    [ USING ( using_expression ) ]
    [ WITH CHECK ( check_expression ) ]

ALTER TABLE … DISABLE ROW LEVEL SECURITY
ALTER TABLE … ENABLE ROW LEVEL SECURITY
ALTER TABLE … FORCE ROW LEVEL SECURITY
ALTER TABLE … NO FORCE ROW LEVEL SECURITY

CREATE ROLE name [[ WITH ] [BYPASSRLS | NOBYPASSRLS]]
ALTER ROLE role_specification [ WITH ] [BYPASSRLS | NOBYPASSRLS]

SHOW POLICIES FOR <table_name>
```

At this stage, these commands won’t have any functionality implemented. A follow-up issue will add a feature gate, allowing these commands to be used only when a specific session variable is set, as we continue building out the RLS feature set.

Jira issue: CRDB-45200

### PR DESCRIPTION
**Pull request by spilchen**
This change introduces new SQL grammar to support row-level security (RLS). All of the statements, with the exception of SHOW POLICIES match the postgres grammar. The added statements and options are as follows:
```
DROP POLICY [ IF EXISTS ] name ON table_name [ CASCADE | RESTRICT ]

CREATE POLICY name ON table_name 
[ AS { PERMISSIVE | RESTRICTIVE } ]
[ FOR { ALL | SELECT | INSERT | UPDATE | DELETE } ]
[ TO { role_name | PUBLIC | CURRENT_USER | SESSION_USER } [, ...] ]
[ USING ( using_expression ) ]
[ WITH CHECK ( check_expression ) ]

ALTER POLICY name ON table_name RENAME TO new_name

ALTER POLICY name ON table_name 
[ TO { role_name | PUBLIC | CURRENT_USER | SESSION_USER } [, ...] ]
[ USING ( using_expression ) ]
[ WITH CHECK ( check_expression ) ]

ALTER TABLE … DISABLE ROW LEVEL SECURITY
ALTER TABLE … ENABLE ROW LEVEL SECURITY
ALTER TABLE … FORCE ROW LEVEL SECURITY
ALTER TABLE … NO FORCE ROW LEVEL SECURITY

CREATE ROLE name [[ WITH ] [BYPASSRLS | NOBYPASSRLS]]
ALTER ROLE role_specification [ WITH ] [BYPASSRLS | NOBYPASSRLS]

SHOW POLICIES FOR <table_name>
```

Currently, attempting to use any of the new statements or options will return an unimplemented error. Documentation for this grammar is temporarily omitted and will be added closer to the feature's release, expected in version 25.2.

Epic: CRDB-11724
Closes: #136692
Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
looks good! just had small comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-:-OEFD9se6YZJrWD2F9eS:b-n4ya57)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @spilchen)

___
*[`pkg/sql/sem/tree/alter_table.go` line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFC0eo4J67orRh0aOq:-OEFC0eo4J67orRh0aOr:bh6suz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/alter_table.go#L877)):*
> ```Go
> // TableRLSMode represents different modes that the table can be in for
> // row-level security.
> type TableRLSMode int
> ```

nit: let's mark this enum with the `redact.SafeValue` interface
___
*[`pkg/sql/alter_policy.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF5OF20MtwY4hu9MSB:-OEF5OF20MtwY4hu9MSC:b-foyl1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/alter_policy.go#L15)):*
> ```Go
> )
> 
> func (p *planner) AlterPolicy(ctx context.Context, n *tree.AlterPolicy) (planNode, error) {
> ```

nit: i don't think it matters too much since this is just a stub, but since we were planning to only implement this statement in the DSC, should the stub be defined there rather than in this legacy fashion? (similar comment for the other syntax forms below.)
___
*[`pkg/sql/sem/tree/stmt.go` line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFCXa8B54vEcwcXuNG:-OEFCXa8B54vEcwcXuNH:buc3bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/stmt.go#L450)):*
> ```Go
> 
> // StatementReturnType implements the Statement interface.
> func (*AlterPolicy) StatementReturnType() StatementReturnType { return DDL }
> ```

nit: i believe the ALTER, DROP, and CREATE statements should implement the `tree.canModifySchema` interface
___
*[`pkg/sql/sem/tree/stmt.go` line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFCa-793ieKQFUjW4Q:-OEFCa-793ieKQFUjW4R:b-g68ubk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/stmt.go#L458)):*
> ```Go
> func (*AlterPolicy) StatementTag() string { return AlterPolicyTag }
> 
> func (*AlterPolicy) hiddenFromShowQueries() {}
> ```

were these hidden just because the syntax is not public yet? since we block the syntax at planning time, i think it's ok for us not to implement `hiddenFromShowQueries` here, so we avoid forgetting to remove this later.
___
*[`pkg/sql/parser/testdata/create_policy` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFCzuy3La4dBH7F4Je:-OEFCzuy3La4dBH7F4Jf:bz2jg5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/parser/testdata/create_policy#L2)):*
> ```
> parse
> CREATE POLICY p1 ON xy
> ```

nit: it could be worth trying a few mixed case policy names to make sure those are handled. the name would need to be wrapped in double quotes
___
*[`pkg/sql/sem/tree/create_policy.go` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFBxE03LvXdSXR2ySJ:-OEFBxE03LvXdSXR2ySK:bh6suz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/create_policy.go#L12)):*
> ```Go
> // PolicyCommand represents the type of commands a row-level security policy
> // will apply against.
> type PolicyCommand int
> ```

nit: let's mark this enum with the `redact.SafeValue` interface
___
*[`pkg/sql/sem/tree/create_policy.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFC39O9xhGWschsVOg:-OEFC39O9xhGWschsVOh:bh6suz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/create_policy.go#L36)):*
> ```Go
> 
> // PolicyType represents the type of the row-level security policy.
> type PolicyType int
> ```

nit: let's mark this enum with the `redact.SafeValue` interface
___
*[`pkg/sql/sem/tree/create_policy.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFC51r6ViTJ37cXKqL:-OEFC51r6ViTJ37cXKqM:bgncrvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/create_policy.go#L86)):*
> ```Go
> func (node *CreatePolicy) Format(ctx *FmtCtx) {
> 	ctx.WriteString("CREATE POLICY ")
> 	ctx.FormatName(string(node.Policy))
> ```

nit: let's use `ctx.FormatNode`
___
*[`pkg/sql/sem/tree/alter_policy.go` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF683MEohQ4k1lzjUD:-OEF683MEohQ4k1lzjUE:b7mlzcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/alter_policy.go#L14)):*
> ```Go
> 	Policy    Name
> 	Table     TableName
> 	NewPolicy Name
> ```

nit: could the variables be called `PolicyName`. `TableName` and `NewPolicyName` so that it's more clear they are just names when being referenced in other areas of the code? feel free to skip this comment if you find that it adds unnecessary verbosity.
___
*[`pkg/sql/sem/tree/alter_policy.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF6bHA5WFS-prIJAIK:-OEF6bHBB7IHcpza3oW9:bnfgsx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/alter_policy.go#L22)):*
> ```Go
> func (node *AlterPolicy) Format(ctx *FmtCtx) {
> 	ctx.WriteString("ALTER POLICY ")
> 	ctx.FormatName(string(node.Policy))
> ```

the `FormatName` implementation is just:
```
func (ctx *FmtCtx) FormatName(s string) {
	ctx.FormatNode((*Name)(&s))
}
```

so i think these calls should be replaced with `ctx.FormatNode(node.Policy)` (etc) for simplicity.
___
*[`pkg/sql/sem/tree/drop_policy.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFCNEfDRXYcweEA98M:-OEFCNEfDRXYcweEA98N:bgncrvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/drop_policy.go#L24)):*
> ```Go
> 		ctx.WriteString("IF EXISTS ")
> 	}
> 	ctx.FormatName(string(node.Policy))
> ```

nit: let's use `ctx.FormatNode`
___
*[`pkg/sql/parser/sql.y` line 11808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF7D8k24xKmJ5JW2m2:-OEF7D8k24xKmJ5JW2m3:b-xokyfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/parser/sql.y#L11808)):*
> ```Yacc
> | BYPASSRLS
>   {
>     $$.val = tree.KVOption{Key: tree.Name($1), Value: nil}
> ```

one thing that we differ from Postgres on is that we have deprecated role options in favor of "system privileges" (https://www.cockroachlabs.com/docs/stable/security-reference/authorization).

they behave nearly the same, except system privileges can be inherited through role membership, but role options cannot. since this role option is part of the RLS syntax, let's keep it, but let's also add the equivalent system privilege to the `Kind` enum in privilege.go

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137105)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @rafiss)

___
*[`pkg/sql/alter_policy.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF5OF20MtwY4hu9MSB:-OEGtSLZE3f9Zaf01D-Q:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/alter_policy.go#L15)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i don't think it matters too much since this is just a stub, but since we were planning to only implement this statement in the DSC, should the stub be defined there rather than in this legacy fashion? (similar comment for the other syntax forms below.)
</blockquote></details>

Done
___
*[`pkg/sql/parser/sql.y` line 11808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF7D8k24xKmJ5JW2m2:-OEJYk133QIj2g_UuX72:b-gp669a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/parser/sql.y#L11808)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

one thing that we differ from Postgres on is that we have deprecated role options in favor of "system privileges" (https://www.cockroachlabs.com/docs/stable/security-reference/authorization).

they behave nearly the same, except system privileges can be inherited through role membership, but role options cannot. since this role option is part of the RLS syntax, let's keep it, but let's also add the equivalent system privilege to the `Kind` enum in privilege.go
</blockquote></details>

Cool, I wasn't aware of this. I'll update #136910, which is to implement BYPASSRLS, to include system privileges too.
___
*[`pkg/sql/sem/tree/alter_policy.go` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF683MEohQ4k1lzjUD:-OEJ__GX3oa3vcEay98r:b-g1kmwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/alter_policy.go#L14)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could the variables be called `PolicyName`. `TableName` and `NewPolicyName` so that it's more clear they are just names when being referenced in other areas of the code? feel free to skip this comment if you find that it adds unnecessary verbosity.
</blockquote></details>

Makes sense. I'll apply it.
___
*[`pkg/sql/sem/tree/alter_policy.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEF6bHA5WFS-prIJAIK:-OEJaB0N8gQ_aVc-co06:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/alter_policy.go#L22)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the `FormatName` implementation is just:
```
func (ctx *FmtCtx) FormatName(s string) {
	ctx.FormatNode((*Name)(&s))
}
```

so i think these calls should be replaced with `ctx.FormatNode(node.Policy)` (etc) for simplicity.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/stmt.go` line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFCa-793ieKQFUjW4Q:-OEJeWGEEDrPMfzFyf7y:b-v6vsmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/stmt.go#L458)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

were these hidden just because the syntax is not public yet? since we block the syntax at planning time, i think it's ok for us not to implement `hiddenFromShowQueries` here, so we avoid forgetting to remove this later.
</blockquote></details>

It appears that most DDL statements implement this interface. Upon investigating its origin, it seems necessary for any statement that spans jobs, possibly to prevent the statements themselves from being canceled.
___
*[`pkg/sql/parser/testdata/create_policy` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFCzuy3La4dBH7F4Je:-OEJgDtV2TwlD_KkelcQ:bccio2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/parser/testdata/create_policy#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it could be worth trying a few mixed case policy names to make sure those are handled. the name would need to be wrapped in double quotes
</blockquote></details>

Good idea for a test.

**Review by Dedej-Bergin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137105)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong, @rafiss, and @spilchen)

___
*[`pkg/sql/alter_policy.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEKHsms5rMHeiJr2me-:-OEKHsms5rMHeiJr2me0:b-z8ko94) ([raw file](https://github.com/cockroachdb/cockroach/blob/c54c9c6c20fa8be10adad6b71698431895413e16/pkg/sql/alter_policy.go#L16)):*
> ```Go
> )
> 
> func (p *planner) AlterPolicy(ctx context.Context, n *tree.AlterPolicy) (planNode, error) {
> ```

Should we make a pkg/sql/unimplemented.go file and put all these unimplemented statements?  

The sql package is already a bit too crowded and as we continue to add new DSC only statements it might be nice to put them all in one file.

We could put create_policy.go and drop_policy.go and others in there.

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-:-OEKO-322r3SI7s-E7rZ:b-j4xmku)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @kyle-a-wong)

___
*[`pkg/sql/alter_policy.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEKHsms5rMHeiJr2me-:-OEKNK0i7uB_PSlgqTUf:batmc4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c54c9c6c20fa8be10adad6b71698431895413e16/pkg/sql/alter_policy.go#L16)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Should we make a pkg/sql/unimplemented.go file and put all these unimplemented statements?  

The sql package is already a bit too crowded and as we continue to add new DSC only statements it might be nice to put them all in one file.

We could put create_policy.go and drop_policy.go and others in there.
</blockquote></details>

that seems like a good idea. let's do it, though if it would make more sense to do in another PR, feel free to merge and we can make that refactor later.
___
*[`pkg/sql/sem/tree/stmt.go` line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEFCa-793ieKQFUjW4Q:-OEKNrjF0mbVy8Hq2ob8:bogbwwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0deb9d6d92ba16d2283fc1d6082d6fff9df8a8d/pkg/sql/sem/tree/stmt.go#L458)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

It appears that most DDL statements implement this interface. Upon investigating its origin, it seems necessary for any statement that spans jobs, possibly to prevent the statements themselves from being canceled.
</blockquote></details>

i see, thanks for finding that out!

**Review by Dedej-Bergin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137105)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @rafiss)

___
*[`pkg/sql/alter_policy.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEKHsms5rMHeiJr2me-:-OEKOLXJESNgwggUL4NE:bm6b7ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/c54c9c6c20fa8be10adad6b71698431895413e16/pkg/sql/alter_policy.go#L16)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

that seems like a good idea. let's do it, though if it would make more sense to do in another PR, feel free to merge and we can make that refactor later.
</blockquote></details>

Sounds good, I'd be happy to write the code for that! So I'll make this change in one of my future PRs.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137105)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @kyle-a-wong, and @rafiss)

___
*[`pkg/sql/alter_policy.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137105#-OEKHsms5rMHeiJr2me-:-OEKaifs9n0O0DgSL00X:b-585yh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c54c9c6c20fa8be10adad6b71698431895413e16/pkg/sql/alter_policy.go#L16)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

I opened this issue for it https://github.com/cockroachdb/cockroach/issues/137615
</blockquote></details>

Sounds good. Thanks for tackling this Bergin.

**Comment by spilchen** [comment]
TFTR!

bors r+

**Pull request merged**
