### PR TITLE
obsservice: ui handler serves db console assets 

### PR DESCRIPTION
**Pull request by dhartunian**
This change enables the Observabilty Service to serve the DB Console UI
itself. Endpoints that CRDB can handle are proxied (`/_admin/`,
`/_status/`, `/ts/`) but the base URL will return a blank HTML page with
JS assets that load the DB Console.

In order to build with the ui code, the `--config=with_ui` flag must be
passed to bazel.

This commit also adds a shortcut to the `dev` command to build
`obsservice` which includes the `--config=with_ui` flag just as we do by
default in `cockroach` builds.

Release note: None

### CODE REVIEW

**Comment by dhartunian** [comment]
First commit is from #78216

**Review by abarganier — APPROVED** [review]
:lgtm: modulo some tiny nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-:-N5fGkFY3JuQJGZtsF0H:b-8epg57)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @sjbarag)

___
*[`pkg/obsservice/obslib/lib.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5f1CLD6loqeNrfKO5V:-N5f1CLD6loqeNrfKO5W:b-m2wit7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/obsservice/obslib/lib.go#L101)):*
> ```Go
> 
> func (c *noOIDCConfigured) GetOIDCConf() ui.OIDCUIConf {
> 	return ui.OIDCUIConf{
> ```

nit: brief comments on this function



_Code quote:_
```Go
func (c *noOIDCConfigured) GetOIDCConf() ui.OIDCUIConf {
	return ui.OIDCUIConf{
		Enabled: false,
	}
}
```
___
*[`pkg/obsservice/obslib/lib.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5f1RwfBt1QKStGs11q:-N5f1RwfBt1QKStGs11r:b-za0syh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/obsservice/obslib/lib.go#L128)):*
> ```Go
> 
> 		nodeID := &base.NodeIDContainer{}
> 		nodeID.Set(ctx, 123456)
> ```

nit: can we use a constant here instead so we can accompany it with some comments? 



_Code quote:_
```Go
123456
```

**Review by sjbarag — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82741)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @sjbarag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5fdf-zE9MMecPx9twq:-N5fdf-zE9MMecPx9twr:b-2kxcxj) (no related file):*
Good stuff @dhartunian !  Sorry for being slow on the review here :sweat: 

___
___
*[`pkg/cmd/dev/build.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5fdMtp3Jq0HMLC_k3G:-N5fdMtp3Jq0HMLC_k3H:bp1efgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/cmd/dev/build.go#L92)):*
> ```Go
> 	"geos":             geosTarget,
> 	"libgeos":          geosTarget,
> 	"obsservice":       "//pkg/obsservice/cmd/obsservice",
> ```

Do we have a `make` target set up for this as well?  I can't remember if we need to also support `make` builds



_Code quote:_
```Go
		if target.fullName == buildTargetMapping["cockroach"] ||
			target.fullName == buildTargetMapping["cockroach-oss"] ||
```
___
*[`pkg/obsservice/obslib/lib.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5fbqIc8SiuqegHnTjv:-N5fbqIc8SiuqegHnTjw:b-c3z1hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/obsservice/obslib/lib.go#L137)):*
> TODO(davidh): Previously, the `/` handler was the proxy to CRDB. This is now broken because we've started serving the UI from the same endpoint. We should find some way to serve the UI *and* proxy to CRDB at the same time. Unclear how this should work at the moment.

I assume it's the ambiguity of paths (is it a file, an SPA fallback to index.html, or a proxyable path?) that's the issue right?   I wouldn't mind having `/api/**` routes or something to separate UI paths from data-only paths :thinking:

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82741)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @sjbarag)

___
*[`pkg/cmd/dev/build.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5fdMtp3Jq0HMLC_k3G:-N6-ToVc308nzmlZKpCJ:btqlt3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/cmd/dev/build.go#L92)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Do we have a `make` target set up for this as well?  I can't remember if we need to also support `make` builds
</blockquote></details>

We do not have a Makefile target. I'd prefer not to since we will never backport this code but I'll check with #dev-inf.
___
*[`pkg/obsservice/obslib/lib.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5f1CLD6loqeNrfKO5V:-N6-YbTs8ubljX8P0qJx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/obsservice/obslib/lib.go#L101)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: brief comments on this function
</blockquote></details>

Done.
___
*[`pkg/obsservice/obslib/lib.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5f1RwfBt1QKStGs11q:-N6-YritBp2mNr_-Zysn:btvnjys) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/obsservice/obslib/lib.go#L128)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we use a constant here instead so we can accompany it with some comments? 
</blockquote></details>

Done. Ended up just adding logic to be able to omit the NodeID since it makes no sense in this context.
___
*[`pkg/obsservice/obslib/lib.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5fbqIc8SiuqegHnTjv:-N6-ZycN05Of3aF_CGkU:b-e3yzyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/obsservice/obslib/lib.go#L137)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

> TODO(davidh): Previously, the `/` handler was the proxy to CRDB. This is now broken because we've started serving the UI from the same endpoint. We should find some way to serve the UI *and* proxy to CRDB at the same time. Unclear how this should work at the moment.

I assume it's the ambiguity of paths (is it a file, an SPA fallback to index.html, or a proxyable path?) that's the issue right?   I wouldn't mind having `/api/**` routes or something to separate UI paths from data-only paths :thinking: 
</blockquote></details>

This comment is actually out of date as I've added proxying below this. I'll extract the list of CRDB paths for clarity.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, and @sjbarag)

___
*[`pkg/cmd/dev/build.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5fdMtp3Jq0HMLC_k3G:-N6DoptYEAOKnpooStVt:bb7u0xu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/cmd/dev/build.go#L92)):*
> dev-inf

I have confirmation that we do not need to support the Makefile

**Review by sjbarag — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, and @sjbarag)

___
*[`pkg/obsservice/obslib/lib.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82741#-N5fbqIc8SiuqegHnTjv:-N6E1MyW9JxtgBi06XVB:b-2hka24) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e90a98bc60352d79802404d29bb0890cc2683d2/pkg/obsservice/obslib/lib.go#L137)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This comment is actually out of date as I've added proxying below this. I'll extract the list of CRDB paths for clarity.
</blockquote></details>

Perfect, thank you!

**Comment by dhartunian** [comment]
TFTRs!

bors r=sjbarag,abarganier

**Pull request merged**
