### PR TITLE
ui/cluster-ui: add wait time insights to active executions

### LINKED ISSUE #79127: cluster-ui: surface blocked transaction information for active executions
Depends on: https://github.com/cockroachdb/cockroach/pull/77876

Using the new `cluster_locks` virtual table, we can surface information on which tables and indexes an active transaction / query is blocked on for the `ListSessions` API.

Jira issue: CRDB-14587

### LINKED ISSUE #79131: ui: add blocking information for active queries/txns in `WAITING` state
Figma: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=6152%3A136586

On the active transaction details page, update UI to show:
- blocked database, table, schema, index and row
- time spent waiting
- add table for transactions waiting for _currently_viewed_txn_ shown txn
- add table for transactions that _currently_viewed_txn_ is waiting for

On the active stmt details page, update UI to show:
- blocked table and row
- add table for statements that  _currently_viewed_stmt_ is waiting for

Jira issue: CRDB-14590

### PR DESCRIPTION
**Pull request by xinhaoz**
Closes: https://github.com/cockroachdb/cockroach/issues/79127
Closes: https://github.com/cockroachdb/cockroach/issues/79131

This commit introduces a new section, 'Wait Time Insights' to the
active stmts/txns details pages. The section is included if the txn
being viewed is experiencing contention and includes info on the
blocked schema, table, index name, time spent blocking, and the
executions blocking or waiting for the viewed execution.

The section is powered by querying the `crdb_internal.cluster_locks`
table via the SQL api in `/api/v2/`. The table informatioin is
refreshed at an interval of 10s while on active execution pages,
and is requested along with session information (to give info on
active txns/stmts).

Only users having VIEWACTIVITY or higher permissions can view this
feature.

Refactor note: to remove  duplication across shared selector logic
in the active txn components, `activeExecutionsCommon.selectors.ts`
has been created. This file exports  combiner functions for active
txn selectors. The combiner func step contains the bulk of the logic
to transform data from the redux state to component props, thus future
changes to this logic will not need to be duplicated across packages.

Release note (ui change): A new section, 'Wait Time Insights' has
been added to the active statement and transaction details page.
The section is included if the txn being viewed is experiencing
contention and includes info on the blocked schema, table, index
name, time spent blocking, and the txns blocking or waiting for the
viewed txn.  Only users having `VIEWACTIVITY` or higher can view
this feature. The column 'Time Spent Waiting' has been added to
the active executions tables that shows the total amount of time
an execution has been waiting for a lock.

--------------
### Note to reviewers: only the 2nd commit is relevant, see first commit here: https://github.com/cockroachdb/cockroach/pull/85080

https://www.loom.com/share/53d8a74f9c9041a9b967e32dc370a153

### CODE REVIEW

**Comment by xinhaoz** [comment]
@cockroachdb/sql-observability I'd like to do the same refactor shown here for the selector logic for active statements pages and possibly other pages. I notice when we make changes to how we transform data from the redux store to our pages we literally copy paste the code across `db-console` and `cluster-ui` workspaces. This is pretty tedious to maintain but we can avoid the bulk of that if we just export the combiner functions for the selectors, as shown here. LMK your thoughts and I can file issues, maybe smth to do for a flex friday =)

**Comment by xinhaoz** [comment]
The CC changes here are WIP. Couldn't test those changes yet and might just revert and leave them for another commit.

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 33 of 33 files at r3, 23 of 40 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts` line 99 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_I70_90T1kzdSdtfV:-N8_I70aDt-Jse1_HoQG:b-5d9ll3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L99)):*
> ```XML
>             : "Preparing",
>         start: TimestampToMoment(query.start),
>         elapsedTimeMillis: time.diff(TimestampToMoment(query.start), "ms"),
> ```

might be worth just calling elapsedTime and leaving the unit to be generated by the format Duration function, which adds the relevant unit
___
*[`pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts` line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_INQt6aC_nWxvTe3e:-N8_INQt6aC_nWxvTe3f:b-ia41wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L228)):*
> ```XML
>         status: "Executing" as ExecutionStatus,
>         start: TimestampToMoment(activeTxn.start),
>         elapsedTimeMillis: time.diff(TimestampToMoment(activeTxn.start), "ms"),
> ```

same comment as above
___
*[`pkg/ui/workspaces/cluster-ui/src/activeExecutions/types.ts` line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_IldP9iqVy3QxpPrh:-N8_IldP9iqVy3QxpPri:b9hsdqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/activeExecutions/types.ts#L28)):*
> ```XML
> 
> export interface ActiveExecution {
>   statementID?: string; // This may not be present for a tranaction.
> ```

nit: transaction
___
*[`pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_JPn26vzh3wmURNRd:-N8_JPn26vzh3wmURNRe:b-iach2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L34)):*
> ```XML
>   BLOCKED_INDEX: "Blocked Index",
>   BLOCKED_ROW: "Blocked Row",
>   WAIT_TIME: "Time Spenet Waiting",
> ```

nit: spent
___
*[`pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx` line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_JaW11VeGVNKfsxCt:-N8_JaW11VeGVNKfsxCu:b-4stxcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L38)):*
> ```XML
>     `${capitalize(execType)} ID: ${id} waiting on`,
>   WAITING_TXNS_TABLE_TITLE: (id: string, execType: ExecutionType): string =>
>     `${capitalize(execType)} waiting for ID: ${id}`,
> ```

nit: add an `s`, so it looks like statements waiting for...
you don't need the `:` on those 2 messages
___
*[`pkg/ui/workspaces/cluster-ui/src/selectors/activeExecutions.selectors.ts` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_KFBaBZS4J0uXRVsk:-N8_KFBbEb3YT9foWhS1:b-z2jy54) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/selectors/activeExecutions.selectors.ts#L30)):*
> ```XML
> // This file contains selector functions used across active execution
> // pages that are specific to cluster-ui.
> // They should NOT be exported with the cluster-ui package.
> ```

I'm a little confused by this comment, this is used for cluster-ui, but should not be exported to cluster-ui, so how cluster-ui is using these functions?
___
*[`pkg/ui/workspaces/cluster-ui/src/store/clusterLocks/clusterLocks.reducer.ts` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_L6z_472x1M1kpTmt:-N8_L6z_472x1M1kpTmu:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/store/clusterLocks/clusterLocks.reducer.ts#L43)):*
> ```XML
>       state.valid = false;
>     },
>     // Define actions that don't change state
> ```

nit: period
___
*[`pkg/ui/workspaces/cluster-ui/src/store/sessions/sessions.sagas.ts` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_LLLqDelwQSlSdw3A:-N8_LLLqDelwQSlSdw3B:bchf6f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/05e3d5d7837a202624d0fd5fb12d968283a9f00e/pkg/ui/workspaces/cluster-ui/src/store/sessions/sessions.sagas.ts#L46)):*
> ```XML
>     takeLatest(actions.request, requestSessionsSaga),
>     takeLatest(
>       actions.received,
> ```

what was this being used for?
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx` line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_MXwB1s0TTm4TE-PV:-N8_MXwB1s0TTm4TE-PW:bgxaec5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx#L53)):*
> ```XML
> const TXN_EXECUTION_ID_LABEL = "Transaction Execution ID";
> 
> export const GeneralActiveTxnInsightsLabels = {
> ```

this is becoming a wordy name, I don't think the `general` is adding anything here and can be removed
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsView.tsx` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_Mr_eAiwitBnsp8AQ:-N8_Mr_f3NMwEGTr1ja4:burfolx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsView.tsx#L87)):*
> ```XML
>   useEffect(() => {
>     // Refresh  every 10 seconds.
>     // if (!transactions || transactions.length === 0) {
> ```

I think you forgot to put the comment back here
___
*[`pkg/ui/workspaces/db-console/src/redux/apiReducers.ts` line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_MyBIEAmDefHsuZ5e:-N8_MyBIEAmDefHsuZ5f:b2oyplu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L296)):*
> ```XML
>   api.getSessions,
>   "sessions",
>   // The sessions page is a real time view, so need a fairly quick update pace.
> ```

is this comment still valid since you changed to `null`?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts` line 99 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_I70_90T1kzdSdtfV:-N8eaxyV-q2K60-IVMLg:bpgurcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L99)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

might be worth just calling elapsedTime and leaving the unit to be generated by the format Duration function, which adds the relevant unit
</blockquote></details>

The unit displayed will still be generated by the duration function, I actually made this change so that this would happen (was previously just displaying seconds). I just need to approximate the elapsed time here based on the lastUpdated value since it's not actually returned by the server. We can file that as an issue so as to get a more accurate elapsed time.
___
*[`pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts` line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_INQt6aC_nWxvTe3e:-N8ebP8WAIktxMjkQxJq:b-kof1lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L228)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

(responded to other comment)
___
*[`pkg/ui/workspaces/cluster-ui/src/activeExecutions/types.ts` line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_IldP9iqVy3QxpPrh:-N8ebhKe9lP9KW1mHfCN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/activeExecutions/types.ts#L28)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: transaction
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_JPn26vzh3wmURNRd:-N8eblUP-tn7IroUWmEy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L34)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: spent
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx` line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_JaW11VeGVNKfsxCt:-N8ebq8uBffVDgKZVPCf:brfsivw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L38)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: add an `s`, so it looks like statements waiting for...
you don't need the `:` on those 2 messages
</blockquote></details>

Done.
The `:` was part of the figma but I can remove it if it makes more sense!
___
*[`pkg/ui/workspaces/cluster-ui/src/selectors/activeExecutions.selectors.ts` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_KFBaBZS4J0uXRVsk:-N8ec0VN-kOGYOhBxXIh:b-ejx3ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/selectors/activeExecutions.selectors.ts#L30)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm a little confused by this comment, this is used for cluster-ui, but should not be exported to cluster-ui, so how cluster-ui is using these functions?
</blockquote></details>

I noted they shouldn't be exported with the package since they're not to be used in db-console. Since they're local to cluster-ui we don't need to export them since they'll just be used by the  components connecting to redux within the pkg. The file `activeExecutionsCommon.selectors` and the active stmt utils contains the funcs that can be reused across the two pkgs for the selectors and contains all the shared logic in transforming data for the UI pages. This file just uses those functions to create selectors based off the specific state in cluster-ui.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/clusterLocks/clusterLocks.reducer.ts` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_L6z_472x1M1kpTmt:-N8ecmp090gibrYWmV8K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/store/clusterLocks/clusterLocks.reducer.ts#L43)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: period
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/sessions/sessions.sagas.ts` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_LLLqDelwQSlSdw3A:-N8eco4v5LtTIQ6Dl0zU:b-b20bid) ([raw file](https://github.com/cockroachdb/cockroach/blob/05e3d5d7837a202624d0fd5fb12d968283a9f00e/pkg/ui/workspaces/cluster-ui/src/store/sessions/sessions.sagas.ts#L46)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

what was this being used for?
</blockquote></details>

This was used to perform polling previously (invalidation causes refresh). But since we're manually polling now on the page there's no need for this and I thought the added logic here might muck up the polling being done by the pages so I removed it.
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx` line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_MXwB1s0TTm4TE-PV:-N8edMoI9x-QMEksc2mt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx#L53)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this is becoming a wordy name, I don't think the `general` is adding anything here and can be removed
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsView.tsx` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_Mr_eAiwitBnsp8AQ:-N8edenw2jz-ttXpvXTD:bypkfas) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsView.tsx#L87)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think you forgot to put the comment back here
</blockquote></details>

Ah yes, fixed!
___
*[`pkg/ui/workspaces/db-console/src/redux/apiReducers.ts` line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8_MyBIEAmDefHsuZ5e:-N8edhfIEIUKCSa-1ldV:b6e4egp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a47cf01763f465c9c97976eb1cf91d0c6aa7681e/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L296)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is this comment still valid since you changed to `null`?
</blockquote></details>

Updated comment to better reflect how this api is being used.

**Review by maryliag — COMMENTED** [review]
I notice on the loom that on the details page, the values for blocked schema, blocked database and blocked index are empty, only the blocked table is populated, is that expected?

> Reviewed 1 of 37 files at r5, 36 of 36 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-:-N8kkCuhE4CV3SdMHHQS:bduktyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx` line 76 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8xbMNyDX5tdjj0tm2O:-N8xbMNyDX5tdjj0tm2P:bti1doi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2820162ebddb096bd956837560b35b7c49d9e0/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L76)):*
> ```XML
>               <Col className="gutter-row" span={12}>
>                 <SummaryCard className={cx("summary-card")}>
>                   <SummaryCardItem
> ```

if viewactivityredacted won't have that value, better hide this info on that case.
Similar to showing the column itself, otherwise they will see 0/empty and think there is no contention

**Review by xinhaoz — COMMENTED** [review]
@maryliag The DB and schema wasn't being populated in the component at the time I made the loom, that's since been fixed. For all the other values, they are just what is being returned in the query, so the index returned just so happened to be the empty string. Perhaps this is a bug within the virtual table -- I'll ask.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-:-N8xvmFH2AfZfqADsclx:bni3o5j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx` line 76 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8xbMNyDX5tdjj0tm2O:-N8xwRON4op-NzFqSOFu:b-sjg8xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2820162ebddb096bd956837560b35b7c49d9e0/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L76)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if viewactivityredacted won't have that value, better hide this info on that case.
Similar to showing the column itself, otherwise they will see 0/empty and think there is no contention
</blockquote></details>

VIEWACTIVITYREDACTED can show the wait time values and blocked table/schema/db/index, they just won't be able to see which txns are waiting/blocking it. I left it in since I thought it might be useful info -- do you think it's better to just remove everything for REDACTED users?

**Review by maryliag — APPROVED** [review]
Thank you for the explanation! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-:-N8xzuXy5NqJ-afb4k6x:b-waqeoy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx` line 76 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85081#-N8xbMNyDX5tdjj0tm2O:-N8xzCcMCYm4xNGTRc-m:b-34gxhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2820162ebddb096bd956837560b35b7c49d9e0/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L76)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

VIEWACTIVITYREDACTED can show the wait time values and blocked table/schema/db/index, they just won't be able to see which txns are waiting/blocking it. I left it in since I thought it might be useful info -- do you think it's better to just remove everything for REDACTED users?
</blockquote></details>

ah okay, I thought they couldn't see anything. In that case, makes sense to keep it in

**Pull request merged**
