### PR TITLE
sql: Rename SemanticType to Family (patch 16/)

### PR DESCRIPTION
**Pull request by andy-kimball**
Update terminology from SemanticType to Family, per conversation on
PR #36699. The rename follows this pattern:

  INT -> IntFamily
  STRING -> StringFamily
  ...

In addition, update all the places that were using the name of the family
as if it were the name of the type, and update them to use one of the
other type name methods instead. Add a PGName() method to round out the
set of type name methods that we use in various places in the code.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Don't merge this, as it is part of the type system refactor, and exists only to make review easier.

https://github.com/cockroachdb/cockroach/pull/36598

**Review by knz — APPROVED** [review]
> Reviewed 131 of 131 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36957)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/testdata/rules/scalar, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36957#-LcqJc92BNfkaPsRUVV4:-LcqJc949_ml5wx-P-cp:bhnke0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/cac010331df172824ba547e251caa1232b535a1d/pkg/sql/opt/norm/testdata/rules/scalar#L213)):*
> ```
> ----
> values
>  ├── columns: int8:1(int) timestamptz:2(timestamptz) bpchar:3(char) oid:4(oidvector) int2:5(int2vector)
> ```

when I saw this change I was like "wait a PR that renames stuff should not have functional changes" then I saw your changes to `col_name.go`.

HAve you considered changing `col_name.go` and this test file in a separate commit?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 805 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36957#-LcqJuhI44JjnfyJyWFE:-LcqJuhI44JjnfyJyWFF:bvfl253) ([raw file](https://github.com/cockroachdb/cockroach/blob/cac010331df172824ba547e251caa1232b535a1d/pkg/sql/opt/optbuilder/mutation_builder.go#L805)):*
> ```Go
> 	panic(pgerror.NewErrorf(pgerror.CodeDatatypeMismatchError,
> 		"value type %s doesn't match type %s of column %q",
> 		typ.String(), col.DatumType().String(), tree.ErrNameString(colName)))
> ```

you can drop the call to `.String()`, `%s` will take care of it

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36957)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/sql/opt/norm/testdata/rules/scalar, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36957#-LcqJc92BNfkaPsRUVV4:-LcqSXoI1C7uVHUbZvFU:b-dn3fk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cac010331df172824ba547e251caa1232b535a1d/pkg/sql/opt/norm/testdata/rules/scalar#L213)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

when I saw this change I was like "wait a PR that renames stuff should not have functional changes" then I saw your changes to `col_name.go`.

HAve you considered changing `col_name.go` and this test file in a separate commit?
</blockquote></details>

OK, I put those changes in a separate commit as part of this PR.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 805 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36957#-LcqJuhI44JjnfyJyWFE:-LcqS58B3L4n7J-DYiGY:b-oh1mxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cac010331df172824ba547e251caa1232b535a1d/pkg/sql/opt/optbuilder/mutation_builder.go#L805)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can drop the call to `.String()`, `%s` will take care of it
</blockquote></details>

OK, I changed it. I had left it explicit just because of how much work it's caused me to not be able to search for all usages of `T.String`, since GoLand is blind to implicit usages.

**Comment by RaduBerinde** [comment]
LGTM

**Pull request closed without merging**
