### PR TITLE
pgwire: fix the handling of the cancel request

### LINKED ISSUE #47596: pgwire: recognize cancel requests sent before conn upgraded to TLS
This is a regression introduced in 20.1 (the code was fine in 19.2):

- we want to recognize the "cancel request" message even though cancel is not yet supported (cf #41335 #34520) and report it in telemetry
- in 20.1, this is not working (it did in 19.x)
- this is because the cancel request is sent before TLS is set up, and I mistakenly changed the code to only accept it after TLS is set up
- details of protocol flow here: https://www.postgresql.org/docs/12/protocol-flow.html

found by @andreimatei

### PR DESCRIPTION
**Pull request by knz**
Fixes #47596

This fixes a telemetry regression that was introduced in the "great
HBA refactor".

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Friendly ping
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47597#-:-M5Nzj6XDHQgumrXrnVM:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/pgwire/pgwire_test.go, line 1890 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47597#-M5Nz64jAPBVPNGfTPKw:-M5Nz64jAPBVPNGfTPKx:b-hki0kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4106379c60233057d250fbe8ee9b8f8f19a587cb/pkg/sql/pgwire/pgwire_test.go#L1890)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		const versionCancel = 80877102
> ```

mind putting some comment explaining this "version"?

**Comment by knz** [comment]
> mind putting some comment explaining this "version"?

Done.

Thanks!

bors r=andreimatei

**Comment by knz** [comment]
google download link fail

bors r=andreimatei

**Pull request merged**
