### PR TITLE
sql/ccl: add partial inverted index, multi-column inverted index, and partitioned inverted index telemetry

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: rename "partial_index" telemetry test file to "index"

A single telemetry test file is appropriate for testing all
index-related telemetries.

Release note: None

#### sql: add telemetry for partial and multi-column inverted indexes

This commit adds telemetry counters `sql.schema.partial_inverted_index`
and `sql.schema.multi_column_inverted_index`. It also adds telemetry
tests for geography and geometry inverted indexes, which was already
supported.

Informs #63380

Release note: None

#### sql/ccl: add telemetry for partitioned inverted indexes

Informs #63380

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63417#-:-MY5p_x25Q6z1b7lbak5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @otan)

___
*[pkg/sql/create_index.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63417#-MY5nKrY1PmHlOlWwZtw:-MY5nKrZ4K8DjlZ1RIVJ:b2p0a08) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59583c7fc55dba8b64c8a9650187b06bce0220d/pkg/sql/create_index.go#L263)):*
> ```Go
> 	if indexDesc.Type == descpb.IndexDescriptor_INVERTED {
> 		telemetry.Inc(sqltelemetry.InvertedIndexCounter)
> 		if isGeometry {
> ```

Instead of using these bools, you can check `geoindex.IsGeographyConfig(&indexDesc.GeoConfig)` or `geoindex.IsGeometryConfig(&indexDesc.GeoConfig)`

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63417)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/sql/create_index.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63417#-MY5nKrY1PmHlOlWwZtw:-MY6I0PAAyEoOB6Gn_RI:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e59583c7fc55dba8b64c8a9650187b06bce0220d/pkg/sql/create_index.go#L263)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Instead of using these bools, you can check `geoindex.IsGeographyConfig(&indexDesc.GeoConfig)` or `geoindex.IsGeometryConfig(&indexDesc.GeoConfig)` 
</blockquote></details>

Thanks! Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63417#-:-MY6WMfw4kBFJzuvC_uZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
