### PR TITLE
snappy: updated ref, fixed issue for big-endian

### PR DESCRIPTION
**Pull request by adpopescu**
This is to fix a test case failure on s390x architecture.

Previous to this change the test _TestPebbleWritesSameSSTs_ within the storage package fails on s390x.
This was due to a hash table collision within the snappy compression code which only occurs on big-endian systems.
The collision was causing the compression to differ from the equivalent GO compression.

Please see the commit in the submodule for more details.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

Fun bug. Thanks for the fix.

**Comment by jbowens** [comment]
Hey @adpopescu, do you mind opening a PR with this fix against the `crl-release-1.1.7` branch on the cockroachdb/snappy repo?

**Comment by adpopescu** [comment]
Hi @jbowens, PR should be there now.

**Comment by jbowens** [comment]
bors r+

Thanks for the contribution @adpopescu!

**Comment by adpopescu** [comment]
TFTR!

**Pull request merged**
