### PR TITLE
server: convert the nodeStatus latency map's key to an int32

### PR DESCRIPTION
**Pull request by BramGruneir**
The proto was originally a map with an int64 key, which makes dealing with the javascript versions of the protos perticularly strange. Since javascript does not have a long type (that can be used as a key for a POJO hash), protobufjs creates an unprintable hash that needs to be interpreted into a long object using a function.

In this case, nodeIDs are always int32, so this should makes the problem a little better. In the future, we should avoid adding any protobufs that have an int64 as the key if they may be consumed by the frontend.

### CODE REVIEW

**Comment by BramGruneir** [comment]
Just a note, that this still isn't ideal, int32s are represented as strings instead of numbers.  Why they don't do that for longs as well I don't understand.

From: https://www.npmjs.com/package/protobufjs
> Map fields are Object.<string,T> with the key being the string representation of the respective value or an 8 characters long binary hash string for Long-likes.

**Comment by mrtracy** [comment]
LGTM

Javascript converts numeric values to strings when using them as dictionary keys, so this is always the case; it can't be done automatically in the case of Long because it is an object, not a primitive numeric type.

**Comment by BramGruneir** [comment]
Yeah, but why not convert the long to a string.
And it could use a Map type and solve everything.  And it could use Longs as the key then.

**Comment by mrtracy** [comment]
Well, they did it this way, this is what we've got.

**Pull request merged**
