### PR TITLE
ui: update ui-components version to 0.4.2

### PR DESCRIPTION
**Pull request by maryliag**
Updates `cockroachlabs/ui-components` to 0.4.2.

Epic: None

Release note: None

### CODE REVIEW

**Review by xinhaoz — APPROVED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Comment by maryliag** [comment]
unrelated flaky

bors r+

**Comment by maryliag** [comment]
bors retry

**Comment by yuzefovich** [comment]
bors single on

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
