### PR TITLE
dbconsole: fix admission wait sum graphs

### LINKED ISSUE #108466: admission: wait_sum graphs in consoles are broken
These are defined in many places.
```
$ git grep admission.wait_sum
monitoring/splunk-dashboard/overload.xml:rate_sum(admission_wait_sum_kv) as KV_request_rate,
monitoring/splunk-dashboard/overload.xml:rate_sum(admission_wait_sum_kv_stores) as KV_write_request_rate,
monitoring/splunk-dashboard/overload.xml:rate_sum(admission_wait_sum_sql_kv_response) as SQL-KV_response_rate,
monitoring/splunk-dashboard/overload.xml:rate_sum(admission_wait_sum_sql_sql_response) as SQL-SQL_response_rate
pkg/cmd/roachtest/grafana/configs/backup-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_kv_stores[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/backup-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_kv[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/backup-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_kv_response[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/backup-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_sql_response[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/backup-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_leaf_start[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/backup-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_root_start[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/changefeed-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_kv_stores{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/changefeed-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_kv{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/changefeed-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_kv_response{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/changefeed-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_sql_response{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/changefeed-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_leaf_start{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/changefeed-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_root_start{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/changefeed-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_elastic_cpu{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/snapshot-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_kv_stores{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/snapshot-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_kv{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/snapshot-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_kv_response{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/snapshot-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_sql_response{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/snapshot-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_leaf_start{node=~\"$node\"}[$__rate_interval])",
pkg/cmd/roachtest/grafana/configs/snapshot-admission-control-grafana.json:              "expr": "rate(admission_wait_sum_sql_root_start{node=~\"$node\"}[$__rate_interval])",
pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.fixtures.ts:      "admission.wait_sum.kv": 0,
pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.fixtures.ts:      "admission.wait_sum.kv-stores": 0,
pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.fixtures.ts:      "admission.wait_sum.sql-kv-response": 0,
pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.fixtures.ts:      "admission.wait_sum.sql-sql-response": 0,
pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx:              name="cr.node.admission.wait_sum.kv"
pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx:              name="cr.node.admission.wait_sum.kv-stores"
pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx:              name="cr.node.admission.wait_sum.sql-kv-response"
pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx:              name="cr.node.admission.wait_sum.sql-sql-response"
```

But we've changed the underlying metric to be a histogram https://github.com/cockroachdb/cockroach/blob/2c650afca63edc27a39fd8876a13ef4deb15d955/pkg/util/admission/work_queue.go#L1669  which exports the sum as e.g. `admission.wait_durations.kv-stores-sum` 

Jira issue: CRDB-30483

### PR DESCRIPTION
**Pull request by aadityasondhi**
The underlying metric for these graphs changed, but we forgot to change the UI code to match that.

This patch changes `admission.wait_sum` to `admission.wait_durations`.

Fixes: #108466

Release note: None

### CODE REVIEW

**Comment by aadityasondhi** [comment]
Forgot to fix the stuff in the grafana.json. Hold on reviewing this PR.

**Comment by aadityasondhi** [comment]
before: https://github.com/cockroachdb/cockroach/issues/108466#issuecomment-1804202967
after: https://github.com/cockroachdb/cockroach/issues/108466#issuecomment-1804686548

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114184#-:-Nj8LwqL6nsaDyyZtPoI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @RaduBerinde)

**Review by jbowens — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114184#-:-Nj8ZcUM-g7N3YHlVZlE:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @RaduBerinde)

**Review by aadityasondhi — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114184#-:-Nj8ZknWB5Pl1ojJ6C7h:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @RaduBerinde)

**Pull request merged**
