### PR TITLE
jobs: change job_info.info_key to string

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

Hopefully we get this one in now before it is released and harder to change later. I think if we go with bytes, we'll spend the next several years typing convert_to over and over, or forgetting to and then typing it, when debugging.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]

**Review by adityamaru — APPROVED** [review]

**Comment by dt** [comment]
TFTRs!

bors r+

(red CI is green on everything except maybe_stress which is apparently just known to be busted)

**Comment by dt** [comment]
blathers backport 23.1

**Comment by yuzefovich** [comment]
This likely needs a rebase.

bors r-

```
pkg/jobs/jobsprofiler/profiler.go:47:34: cannot use []byte(fmt.Sprintf(infoKey, timeutil.Now().UnixNano())) (value of type []byte) as type string in argument to infoStorage.Write
```

**Comment by dt** [comment]
thanks @yuzefovich!

> This likely needs a rebase.
done.

bors r+

**Comment by dt** [comment]
don't think bors noticed the comment since it didn't queue it.

bors r+

**Comment by knz** [comment]
bors r-

please rebase. there's a merge conflict now.

**Pull request merged**
