### PR TITLE
storage/cloud: split out implementations into own files

### PR DESCRIPTION
**Pull request by dt**
This is change is only moving code, and only what files that code is in -- no behavior or even symbols are changed.
This is just splitting up the big 'external_storage.go' that previously contained both the common interface and
all the implementaitons of it, to only contain the interface and common helpers, with each implementaiton now in its
own file. Tests are similarly split.

Release note: none.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
LG.
Since this is a pure refactoring, feel free to ignore comments re long lines...
Or, take this opportunity to tidy those long lines/comments as you see fit.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-:-LxxBGaN7qEIG4WUTRWW:b4hzj4k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/storage/cloud/azure_storage.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-Lxx8wkr2C3rTFycuNrI:-Lxx8wkr2C3rTFycuNrJ:bo57582) ([raw file](https://github.com/cockroachdb/cockroach/blob/022c0eac3537f744fa31cff9c41abdb7726354d6/pkg/storage/cloud/azure_storage.go#L79)):*
> ```Go
> 		func(ctx context.Context) error {
> 			blob := s.getBlob(basename)
> 			_, err := blob.Upload(ctx, content, azblob.BlobHTTPHeaders{}, azblob.Metadata{}, azblob.BlobAccessConditions{})
> ```

Longish line; perhaps wrap?
___
*[pkg/storage/cloud/azure_storage.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-Lxx9--VDRtsuMR7ntAn:-Lxx9--VDRtsuMR7ntAo:b2cs6o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/022c0eac3537f744fa31cff9c41abdb7726354d6/pkg/storage/cloud/azure_storage.go#L128)):*
> ```Go
> 		func(ctx context.Context) error {
> 			blob := s.getBlob(basename)
> 			_, err := blob.Delete(ctx, azblob.DeleteSnapshotsOptionNone, azblob.BlobAccessConditions{})
> ```

longish line?
___
*[pkg/storage/cloud/http_storage.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-LxxAmMV8h0Rsak5ptXc:-LxxAmMV8h0Rsak5ptXd:bpsc4eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/022c0eac3537f744fa31cff9c41abdb7726354d6/pkg/storage/cloud/http_storage.go#L242)):*
> ```
> was
> ```
Can you drop this  word (a typo)

**Review by miretskiy — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-:-LxxBSV_5Iz1CVr9ZKU1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43757)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

___
*[pkg/storage/cloud/azure_storage.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-Lxx8wkr2C3rTFycuNrI:-LxxDPYFB1RQR4278pHy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/022c0eac3537f744fa31cff9c41abdb7726354d6/pkg/storage/cloud/azure_storage.go#L79)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Longish line; perhaps wrap?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/azure_storage.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-Lxx9--VDRtsuMR7ntAn:-LxxEHbK-snD2rL9yz4y:bp3y0rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/022c0eac3537f744fa31cff9c41abdb7726354d6/pkg/storage/cloud/azure_storage.go#L128)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

longish line?
</blockquote></details>

this one is okay by the rules  (<100) and I'm not sure it'd be more readable wrapped.
___
*[pkg/storage/cloud/http_storage.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43757#-LxxAmMV8h0Rsak5ptXc:-LxxEk3FDWAgCWGUZmxx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/022c0eac3537f744fa31cff9c41abdb7726354d6/pkg/storage/cloud/http_storage.go#L242)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> was
> ```
Can you drop this  word (a typo)
</blockquote></details>

Done.

**Pull request merged**
