### PR TITLE
roachprod: force wait=true for `stop --signal=9`

### LINKED ISSUE #77334: roachtest, roachprod: default to Wait=true in Stop
`Wait` should default to `true`, as that's what ~all callers want:

https://github.com/cockroachdb/cockroach/blob/5af48f0e85f10124161679408024b29623d78f73/pkg/roachprod/roachprod.go#L682-L688

We should also consider negating the field, i.e. `NoWait bool`, and to say that a signal of `0` uses `9` as a default. That way, we don't need a method to instantiate the defaults in the first place, making the zero value useful instead.

Jira issue: CRDB-13532
Epic: CRDB-10428

### PR DESCRIPTION
**Pull request by tbg**
Touches #77334.

Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
Thanks for PR! Minor comments, otherwise it's good to go.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-:-MymwtwK52Y4-LlCQJrt:bmfk3hg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @tbg)

___
*[pkg/roachprod/roachprod.go, line 680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-MymwI1c-d0Unx_E8ibB:-MymwI1c-d0Unx_E8ibC:b7mqgpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5861187ce91caffdffa6babb43b818476fc0c8ce/pkg/roachprod/roachprod.go#L680)):*
> ```Go
> 	// If Wait is set, roachprod waits until the PID disappears (i.e. the
> 	// process has terminated).
> 	Wait bool // forced to true when Sig == 9
> ```

Might be worthwhile to also change roachprod's `DefaultStopOpts.Wait` default to `true`.
___
*[pkg/roachprod/install/cluster_synced.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-Mymwbis6-RVFcUxmPWA:-Mymwbis6-RVFcUxmPWB:b-8d8xlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5861187ce91caffdffa6babb43b818476fc0c8ce/pkg/roachprod/install/cluster_synced.go#L228)):*
> ```Go
> func (c *SyncedCluster) Stop(ctx context.Context, l *logger.Logger, sig int, wait bool) error {
> 	if sig == 9 {
> 		// `kill -9` without wait is never what a caller wants. See #77334.
> ```

While I can't think of a specific use-case which would require `wait=false`, it would improve debugging experience to log in the case that the `wait` value is overridden below.

**Review by tbg — COMMENTED** [review]
TFTR! No changes, but would like you to take a look at my responses before I merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-:-MzEZo_FCg4e5RnMU5yE:b-cnt9xd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @srosenberg)

___
*[pkg/roachprod/roachprod.go, line 680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-MymwI1c-d0Unx_E8ibB:-MzEYFhAEKblXfMDiMiR:b-ibg0d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5861187ce91caffdffa6babb43b818476fc0c8ce/pkg/roachprod/roachprod.go#L680)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Might be worthwhile to also change roachprod's `DefaultStopOpts.Wait` default to `true`.
</blockquote></details>

I intentionally didn't do that, or things like this will rot:

```
	stopOpts := option.DefaultStopOpts()
	stopOpts.RoachprodOpts.Sig = 2
```

`DefaultStopOpts()` has 50 usages. I would like to minimize potential disruption during the stability period (and would like to backport this without sweating). Generally I still like the plan to move from `Wait` -> to `NoWait` but I think that should be done separately from fixing the missing wait in `kill -9` that exists pervasively across the test suite and is ever desirable.
___
*[pkg/roachprod/install/cluster_synced.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-Mymwbis6-RVFcUxmPWA:-MzEZQZiDbjXrCgW0Nhf:b-av9pns) ([raw file](https://github.com/cockroachdb/cockroach/blob/5861187ce91caffdffa6babb43b818476fc0c8ce/pkg/roachprod/install/cluster_synced.go#L228)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

While I can't think of a specific use-case which would require `wait=false`, it would improve debugging experience to log in the case that the `wait` value is overridden below.
</blockquote></details>

It won't be useful to log this. Tests call `c.Stop` all the time and since I am averse to changing the default for the `Wait` flag at this moment (see other comment) it would just get spammed all over the place (into already spammy logs :-) )

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-:-Mymx3E-EbxC9UAtWx1G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @tbg)

___
*[pkg/roachprod/roachprod.go, line 680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-MymwI1c-d0Unx_E8ibB:-MzFlSw091MjF1I02DCt:b-f14lsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5861187ce91caffdffa6babb43b818476fc0c8ce/pkg/roachprod/roachprod.go#L680)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I intentionally didn't do that, or things like this will rot:

```
	stopOpts := option.DefaultStopOpts()
	stopOpts.RoachprodOpts.Sig = 2
```

`DefaultStopOpts()` has 50 usages. I would like to minimize potential disruption during the stability period (and would like to backport this without sweating). Generally I still like the plan to move from `Wait` -> to `NoWait` but I think that should be done separately from fixing the missing wait in `kill -9` that exists pervasively across the test suite and is ever desirable.
</blockquote></details>

Sounds good; would you mind leaving a TODO for a follow-up refactoring.
___
*[pkg/roachprod/install/cluster_synced.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78268#-Mymwbis6-RVFcUxmPWA:-MzFlhdQ7J1cyyCbRcEX:b3nwj74) ([raw file](https://github.com/cockroachdb/cockroach/blob/5861187ce91caffdffa6babb43b818476fc0c8ce/pkg/roachprod/install/cluster_synced.go#L228)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It won't be useful to log this. Tests call `c.Stop` all the time and since I am averse to changing the default for the `Wait` flag at this moment (see other comment) it would just get spammed all over the place (into already spammy logs :-) )
</blockquote></details>

Got it; logs are way too spammy as is :(

**Comment by tbg** [comment]
bors r=srosenberg

Not going to put a TODO in the code but instead leaving https://github.com/cockroachdb/cockroach/issues/77334 open.

**Pull request merged**
