### PR TITLE
server: change conn close error to warning

### LINKED ISSUE #98523: server: `use of closed network connection` when quiescing
During a (likely unrelated to this failure) roachtest, a node is stopped gracefully and restarted with a new binary. In the process of terminating the node, the following panic was observed:

```
@server/server_http.go:227 ⋮ [T1,n1] 280  close tcp ‹[::]:26258›: ‹use of closed network connection›
@server/server_http.go:227 ⋮ [T1,n1] 280 !goroutine 150 [running]:
@server/server_http.go:227 ⋮ [T1,n1] 280 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x1)
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x89
@server/server_http.go:227 ⋮ [T1,n1] 280 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000816420, {{{0xc00b004a20, 0x24}, {0x0, 0x0}, {0x5a5ba7a, 0x1}, {0x5a5ba7a, 0x1}}, 0x174c0a264829ca96, ...})
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/pkg/util/log/clog.go:262 +0x97
@server/server_http.go:227 ⋮ [T1,n1] 280 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x6ee4260, 0xc000e0ef00}, 0x2, 0x4, 0x1, 0x0?, {0x59891a6, 0x2}, {0xc001671f10, 0x1, ...})
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x645
@server/server_http.go:227 ⋮ [T1,n1] 280 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
@server/server_http.go:227 ⋮ [T1,n1] 280 !github.com/cockroachdb/cockroach/pkg/util/log.loggerOps.Fatalf(...)
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:1378
@server/server_http.go:227 ⋮ [T1,n1] 280 !github.com/cockroachdb/cockroach/pkg/server.startHTTPService.func1({0x6ee4260, 0xc000e0ef00})
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/pkg/server/server_http.go:227 +0xbf
@server/server_http.go:227 ⋮ [T1,n1] 280 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
@server/server_http.go:227 ⋮ [T1,n1] 280 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
@server/server_http.go:227 ⋮ [T1,n1] 280 ! github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```

For reference, this happened while running a roachtest that has not been merged to master yet [1], but it's quite likely this crash is unrelated to that. A similar failure has also been observed in a different roachtest [2], although we don't see the same panic logs in that case [2].

Apologies for the lack of artifacts here; I have them but they are too large for a GitHub attachment. I can upload them somewhere as needed.

@cockroachdb/obs-inf-prs @cockroachdb/server 

[1] #96991
[2] #98436

Jira issue: CRDB-25308

### PR DESCRIPTION
**Pull request by dhartunian**
Resolves: #98523
Epic: None
Release note: None

### CODE REVIEW

**Review by abarganier — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98600#-:-NQWVXcJB1u91QhzJUZ6:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — APPROVED** [review]
thanks

**Comment by dhartunian** [comment]
bors r=knz,abarganier

**Comment by dhartunian** [comment]
blathers backport 22.2

**Pull request merged**
