### PR TITLE
opt: incorporate cast volatility

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change incorporates the new cast volatility information into the
VolatilitySet property.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 36 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49779#-:-M8rbap-0V48NP8V_HRh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/sem/tree/casts.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49779#-M8rYn33ChqLMVHS5ah4:-M8rYn33ChqLMVHS5ah5:b-sitiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad3ac8d1720116a6fb3b122f7f32250d946a6c44/pkg/sql/sem/tree/casts.go#L117)):*
> ```Go
> 	{from: types.GeometryFamily, to: types.GeographyFamily, volatility: VolatilityImmutable},
> 
> 	// Casts to GeographyFamily.
> ```

[nit] Should be `GeometryFamily`.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 36 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49779#-:-M8vrezy-pv--mMtZr0e:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
