### PR TITLE
tracing: add registry of unfinished local root Spans

### PR DESCRIPTION
**Pull request by tbg**
A local root span is a Span which was created without the
`WithParentAndAutoCollection` option, meaning that either
it is the root of the trace, or it is a child whose parent
will not include the child in its recording.

A new method `Tracer.VisitSpans` is added which allows
iterating through these Spans.

Touches #55592.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
No objection here, but I'd like to pick up the argument I've served you before, that we want completed spans to also visible through a global registry (i.e. the ability to view trace spans for fast queries, when they may have completed already at the instant when we look into the registry).

My original idea for this was to keep all the trace entries in a cyclic buffer (not the spans), so that memory consumption remains bounded regardless of trace complexity. What do you say to that?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58490#-:-MQMvp0t8UaZ5lYqKBi_:b-fc5p93)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by tbg — COMMENTED** [review]
I am not opposed to that idea in general, but I don't think its time is now - we are not too far off the stability period and want to make sure that we deliver always-on tracing and observability into hanging requests. Until these basic commitments are checked off, we need to be mindful of feature creep. And looking at the remaining plans for the release (in particular CC-serverless), I do not think we will have additional bandwidth here, even in the best case.

Note that anyone wanting to track all requests can point CRDB at Jaeger. This was a bad idea so far due to the giant overhead of verbose tracing, but now you can, in principle (with small code changes) send non-verbose traces to Jaeger. (And similary it is straightforward to offer an OpenTracing backend that simply writes all traces to files, for later import into Jaeger). With this option around the corner, there bar for considering doing something fancier here is very high.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58490#-:-MQN0zW62VN4AT1fg16r:bnh5afw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by irfansharif — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/util/tracing/tracer.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58490#-MQNmBsAAmlyT7_mPI4I:-MQNmBsAAmlyT7_mPI4J:bg1ueuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/634d0faea3a03a9580b5fc36cfcc91df69a22726/pkg/util/tracing/tracer.go#L623)):*
> ```Go
> 		sl = append(sl, sp)
> 	}
> 	t.activeSpans.Unlock()
> ```

curious: Is allocating the slice under a lock really that bad? Wouldn't we end up reallocating again anyway if there was a new active span added while allocating outside the lock?

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=irfansharif

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58490#-:-MQQzo7YE2px6uehXAqJ:btc32ws)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

___
*[pkg/util/tracing/tracer.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58490#-MQNmBsAAmlyT7_mPI4I:-MQQzY1G0jXkqiizfZRX:bz8qt69) ([raw file](https://github.com/cockroachdb/cockroach/blob/634d0faea3a03a9580b5fc36cfcc91df69a22726/pkg/util/tracing/tracer.go#L623)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

curious: Is allocating the slice under a lock really that bad? Wouldn't we end up reallocating again anyway if there was a new active span added while allocating outside the lock?
</blockquote></details>

No, you're right, this is premature optimization, and not of the useful kind. It could help - but could not. I guess in a steady state you're about as likely to see more in the map after than before than not, so it helps in 50% of cases roughly. Either way, since it's not clear that we need to do this anyway, I removed it.

**Pull request merged**
