### PR TITLE
opt: show cross joins in EXPLAIN

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: show cross joins in EXPLAIN

A cross join is a join where we have to consider all possible pairs of
rows from the two inputs. This is internally executed as a degenerate
case of a hash join, where the hash columns are the empty set and thus
everything is in a single bucket. This implementation detail "bleeds"
out into EXPLAIN output, where it looks like a hash join (which is
deceiving; a cross join in a plan should be a big red flag).

This change improves EXPLAIN and EXPLAIN (OPT) output to explicitly
mention cross join. This can help debug issues where (from looking at
the query) we think we have an equality column but we actually don't
(e.g. because they are of different types).

Somewhat related to #43060.

Release note (sql change): the output of EXPLAIN now shows joins where
there are no equality columns as "cross" instead of "hash". This kind
of join can be very expensive and should be avoided.

CC @awoods187

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Updating the change to say "cross join" instead of "quadratic join".

**Review by rytaft — COMMENTED** [review]
Did you consider the name "nested loops" join? Cross join seems like more of a logical term than a specific algorithm.

> Reviewed 51 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43061#-:-LvpSS0-Dt_Ofxa-gkC3:bxmzli0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj)

**Comment by RaduBerinde** [comment]
The problem is that in other databases, "nested loop join" can refer to something along the lines of apply-join, which includes lookup join. In SQL Server, lookup join shows up as a nested loop join.

Another option would be "cartesian product" but "cross join" seemed more user friendly

**Review by rytaft — APPROVED** [review]
Right, ok, cross join seems like a reasonable compromise. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43061#-:-LvvI3LK71US4Y-Mc8Wl:b-1q01ro)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Comment by awoods187** [comment]
SGTM--i like cross join

**Pull request merged**
