### PR TITLE
auth: add region-based callback URLs for OIDC

### LINKED ISSUE #56517: auth: support multi-region configuration for OIDC
Previously, the `redirect_url` parameter used in the OIDC flow was set as a static string by the user. This made supporting multiple OIDC flow origins difficult since a customer could have a complex and changing multi-region configuration with many hosts. In addition, supporting both node-specific logins and load balancer logins was challenging as they had different URLs themselves.

This feature eliminates the need for a `redirect_url` parameter set by the user altogether. By extracting information available in the initial OIDC login request we can construct what is a likely valid callback URL automatically.

The callback URL is composed of 3 elements: scheme, host, and path. Here’s how they will be automatically chosen:

Scheme is always “https”. This is a requirement for OIDC authentication already.

Host is read from the `Host` HTTP header on the initial login request. This will contain the host and port that the request is served for. It is assumed that the callback URL will be at this same host. Any CRDB instance that serves the login route can always serve the callback route as well.

Path is the login path with “oidc/v1/login” replaced by “oidc/v1/callback”. This will capture any path prefix that a load balancer imposes.

For example, if the original login URL is:

https://crdb.region-us-west-2.example.com:8080/node0/oidc/v1/login

The computed `redirect_url` is:

https://crdb.region-us-west-2.example.com:8080/node0/oidc/v1/callback

(If we assume that the `Host` header is “crdb.region-us-west-2.example.com:8080” and the path is “node0/oidc/v1/login”)

*Updated Sequence Diagram*

bPDHJzim4CVV-obEuGKqQBOn8Irg8w1CR1BR41jlaS1rBerLr-viXuvllxETMI70fBr4jkFxtz-_kpkrZXdNRUJatEYTHGD79InkBiuBM4Z1rw0LP5Tw9HJiX6lX-vUBHJPHsY58R5m1bvz-Ggv5pVE7Txdq5olrMLlwC_CouDVb92oJyYKgD8ma35Erti0Q7m_1Ed_Yz1hLb2IORUCcvgKhj8MjqNN7-sjVpnOZuLcZbGEk

### PR DESCRIPTION
**Pull request by dhartunian**
Modifies `server.oidc_authentication.redirect_url` cluster setting to
accept valid JSON strings with a `redirect_urls` field that can support
region-based OIDC auth flows.

In addition to a simple string callback URL, here is an example of
valid JSON that this setting can accept:

```
'{
  "redirect_urls": {
    "us-east-1": "https://localhost:8080/oidc/v1/callback",
    "eu-west-1": "example.com"
  }
}'
```

Prerequisites to using the multi-region callback URLs:
1. `region` locality flag is available and set
2. `server.oidc_authentication.redirect_url` setting is set as valid
JSON containing the `redirect_urls` object with a key that matches the
`region` locality flag value on this node

When prerequisites above are met, the `callback_uri` OAuth param is set
to the region-specific value from the JSON setting upon redirect to the
auth provider.

If you are using region-specific configuration, and do not have the
`region` locality set, or try using OIDC in a region without a
corresponding entry in the JSON, OIDC will fail to run.

If you are using simple string-based configuration of a single redirect
URL, OIDC will always use it regardless of your region locality
configuration.

Be aware that the auth provider will likely need to be updated to know
about all possible redirect URLs it may get triggered with.

Resolves #56517

Release note (security update): Adds ability to set region-specific
callback URLs in the OIDC config. The
`server.oidc_authentication.redirect_url` cluster setting can now accept
JSON as an alternative to the basic URL string setting. If a JSON value
is set, it *must* contain a `redirect_url` key that maps to an object
with key, value pairs where the key is a `region` matching an existing
locality setting, and the value is a callback URL.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Approach LGTM but I'll have a look also after you fix the broken test.

(also don't forget `make bazel-generate`)

I also hope Ben can chime in for a second look.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-:-MNh1K586x5bONsoZBPW:b7i7w8h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @nkodali)

**Review by bdarnell — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @nkodali)

___
*[docs/generated/settings/settings.html, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MNz2HNv6VmftSgE-Y2J:-MNz2HNv6VmftSgE-Y2K:b-ukb1n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/11127056f94ebfc754bb72630a0d026eac3d0931/docs/generated/settings/settings.html#L56)):*
> ```HTML
> <tr><td><code>server.oidc_authentication.principal_regex</code></td><td>string</td><td><code>(.+)</code></td><td>regular expression to apply to extracted principal (see claim_json_key setting) to translate to SQL user (golang regex format, must include 1 grouping to extract) (this feature is experimental)</td></tr>
> <tr><td><code>server.oidc_authentication.provider_url</code></td><td>string</td><td><code></code></td><td>sets OIDC provider URL ({provider_url}/.well-known/openid-configuration must resolve) (this feature is experimental)</td></tr>
> <tr><td><code>server.oidc_authentication.redirect_url</code></td><td>string</td><td><code>https://localhost:8080/oidc/v1/callback</code></td><td>sets OIDC redirect URL via a URL string or a JSON string containing a required `default_url` key and a `redirect_urls` key containing an object that maps from region keys to URL strings (URLs should point to your load balancer and must route to the path /oidc/v1/callback) (this feature is experimental)</td></tr>
> ```

Making the `default_url` required seems wrong. It should never be used - if it is, there's a misconfiguration, since the set of regions should be knowable when the configuration is set. And if it is used, it won't actually work as I understand the problem.

Maintaining a map for each region seems tedious, since the URLs will almost certainly be the same except for a region token inserted somewhere. We've already established a convention for regex-based substitutions for extracting the principal. Could we do something similar here and say that `\1` (or pick some string that doesn't require as much annoying escaping) gets replaced with the region name? Or do we need to support cases where the region name is something different than what's used in DNS?

Stepping back a bit, we always need the redirect URL to be able to see cookies set by the login page. That limits how much customization is possible here - the redirect URL will always be a suffix of the requested `Host` header. This suggests an `ndots`-style customization to specify how *much* of the Host header to use. 

Or maybe we should just use the whole thing? I can't remember if we've discussed this before but I think the main reason against using the Host header as-is is that using a suffix may let you login once for multiple nodes in a cluster. But I'm not sure that use case is worth the complexity. Another reason is that some OIDC/OAuth providers require you to pre-register a redirect URL and will not accept arbitrary urls at login time. But these providers generally limit you to a single redirect URL, so they wouldn't be compatible with the pre-region scheme introduced here anyway. 
___
*[pkg/ccl/oidcccl/settings_test.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MNz4zA18WrP9GS5UVjM:-MNz4zA18WrP9GS5UVjN:b-r5y8vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/11127056f94ebfc754bb72630a0d026eac3d0931/pkg/ccl/oidcccl/settings_test.go#L35)):*
> ```Go
> 			"{\"default_url\":\"example.com\"}", false,
> 			&multiRegionRedirectURLs{nil, "example.com"}},
> 		{"json with default url and extra nonsense",
> ```

"Extra nonsense" should generally be an error (to help catch typos).

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nkodali, and @piyush-singh)

___
*[docs/generated/settings/settings.html, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MNz2HNv6VmftSgE-Y2J:-MO70YPg3m1LHJKSQ63t:bd89sgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/11127056f94ebfc754bb72630a0d026eac3d0931/docs/generated/settings/settings.html#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Making the `default_url` required seems wrong. It should never be used - if it is, there's a misconfiguration, since the set of regions should be knowable when the configuration is set. And if it is used, it won't actually work as I understand the problem.

Maintaining a map for each region seems tedious, since the URLs will almost certainly be the same except for a region token inserted somewhere. We've already established a convention for regex-based substitutions for extracting the principal. Could we do something similar here and say that `\1` (or pick some string that doesn't require as much annoying escaping) gets replaced with the region name? Or do we need to support cases where the region name is something different than what's used in DNS?

Stepping back a bit, we always need the redirect URL to be able to see cookies set by the login page. That limits how much customization is possible here - the redirect URL will always be a suffix of the requested `Host` header. This suggests an `ndots`-style customization to specify how *much* of the Host header to use. 

Or maybe we should just use the whole thing? I can't remember if we've discussed this before but I think the main reason against using the Host header as-is is that using a suffix may let you login once for multiple nodes in a cluster. But I'm not sure that use case is worth the complexity. Another reason is that some OIDC/OAuth providers require you to pre-register a redirect URL and will not accept arbitrary urls at login time. But these providers generally limit you to a single redirect URL, so they wouldn't be compatible with the pre-region scheme introduced here anyway. 
</blockquote></details>

Thanks for the detailed thoughts @bdarnell. I'll talk to @piyush-singh and the customer and see what we can do here.

I like the idea of using the `Host` header. A few quick follow-up ideas I'd be curious about your opinion on:

1. What if we implement the callback URL generation as a search/replace of `/auth` at the end of the `Host` header value with `/callback`? It feels like things could be as simple as that.
2. To further simplify the idea of using the `Host` header, I'm now wondering if we could have a single endpoint act as the auth initiation *and* the callback based on whether it's triggered with query params or not. Then re-using the `Host` header seems more natural. Maybe this is what you were suggesting already.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nkodali, and @piyush-singh)

___
*[docs/generated/settings/settings.html, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MNz2HNv6VmftSgE-Y2J:-MO72L7Q93e26XeSewBq:bh5ma6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/11127056f94ebfc754bb72630a0d026eac3d0931/docs/generated/settings/settings.html#L56)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Thanks for the detailed thoughts @bdarnell. I'll talk to @piyush-singh and the customer and see what we can do here.

I like the idea of using the `Host` header. A few quick follow-up ideas I'd be curious about your opinion on:

1. What if we implement the callback URL generation as a search/replace of `/auth` at the end of the `Host` header value with `/callback`? It feels like things could be as simple as that.
2. To further simplify the idea of using the `Host` header, I'm now wondering if we could have a single endpoint act as the auth initiation *and* the callback based on whether it's triggered with query params or not. Then re-using the `Host` header seems more natural. Maybe this is what you were suggesting already.
</blockquote></details>

Spoke too soon and just remembered that `Host` does not contain the requested path. So my comment above is w/r/t to computing the callback as `Host` + request path, not the `Host` header alone.

I do think setting the cookie on the full `Host` domain makes sense. I'm not sure that supporting a suffix-based strategy here is worth the complexity especially if auto-login is enabled on OIDC and opening up a new host will only cause a small delay.

**Comment by piyush-singh** [comment]
For the implementation in the PR, I agree with Ben's comment:

> Making the default_url required seems wrong. It should never be used - if it is, there's a misconfiguration, since the set of regions should be knowable when the configuration is set. And if it is used, it won't actually work as I understand the problem.

The default_url seems antithetical to the premise of the multi-region redirect URLs. I do wonder about the case where a user adds a new region to a cluster - if they don't update their callback URL config, the login for the DB console will not work. How are errors handled in this case? Will we show an error that indicates that the region they are attempting to connect to is not support in their configs?

Other than that, the PR looks good to me. Will hold off on comments for Ben's suggested approach until David H has a chance to prototype.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nkodali, and @piyush-singh)

___
*[docs/generated/settings/settings.html, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MNz2HNv6VmftSgE-Y2J:-MO7kQjy9yFVrfuJazeL:b-c1yd2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/11127056f94ebfc754bb72630a0d026eac3d0931/docs/generated/settings/settings.html#L56)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Spoke too soon and just remembered that `Host` does not contain the requested path. So my comment above is w/r/t to computing the callback as `Host` + request path, not the `Host` header alone.

I do think setting the cookie on the full `Host` domain makes sense. I'm not sure that supporting a suffix-based strategy here is worth the complexity especially if auto-login is enabled on OIDC and opening up a new host will only cause a small delay.
</blockquote></details>

I was thinking of option 1 (replacing `/auth` with `/callback`), but option 2 works too (and is how [I've implemented OAuth before](https://github.com/tornadoweb/tornado/blob/b120df9b584dc59881b72854a4b8e73b16b25159/tornado/auth.py#L541)). And yes, it's `Host` header plus the request path.

**Comment by dhartunian** [comment]
Closing this in favor of #57758

**Comment by dhartunian** [comment]
Reopening after #57758 raised too many security questions without clearly being a bigger win for our customer.

**Review by bdarnell — COMMENTED** [review]
It looks like there are some comments from the last round that have not been addressed (e.g. that the `default_url` field should not be required). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-:-MRQeDlYE1IBHaXFkUkO:bl3uzl7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nkodali, and @piyush-singh)

**Comment by dhartunian** [comment]
@bdarnell yes, I will have an update to this PR over the next few days.

**Review by dhartunian — COMMENTED** [review]
@piyush-singh @bdarnell I modified the configuration to remove the `default_url` setting. Also added more detailed description of behavior to the commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-:-MRR-MPT6bh0ir4BjIN8:bs5o5vw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, @nkodali, and @piyush-singh)

___
*[pkg/ccl/oidcccl/settings_test.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MNz4zA18WrP9GS5UVjM:-MRR-Eoa0u_0A_cTzGvQ:bz3rkn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/11127056f94ebfc754bb72630a0d026eac3d0931/pkg/ccl/oidcccl/settings_test.go#L35)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"Extra nonsense" should generally be an error (to help catch typos). 
</blockquote></details>

I modified the parsing to be strict and added tests to that effect :)

**Review by bdarnell — APPROVED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @nkodali, and @piyush-singh)

**Review by knz — APPROVED** [review]
:lgtm: with nits. Nice!

> Reviewed 5 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-:-MR_D5Cw3NGzgsMi2zKG:bz74rot)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell, @dhartunian, @nkodali, and @piyush-singh)

___
*[pkg/ccl/oidcccl/settings.go, line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MR_D0wC6t64kp5o4D_6:-MR_D0wC6t64kp5o4D_7:bszxh1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7f5f802287ed572d3b93ae3a1f180a5765271b/pkg/ccl/oidcccl/settings.go#L131)):*
> ```Go
> 		// If we know the string is *not* valid JSON, fall back to assuming basic URL
> 		// string to use the simple redirect URL configuration option
> 		_, err := url.Parse(s)
> ```

nit: `if err := ...; err != nil {`
___
*[pkg/ccl/oidcccl/settings.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MR_D1c086sMfdFBYDAr:-MR_D1c086sMfdFBYDAs:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7f5f802287ed572d3b93ae3a1f180a5765271b/pkg/ccl/oidcccl/settings.go#L140)):*
> ```Go
> 	decoder := json.NewDecoder(bytes.NewReader([]byte(s)))
> 	decoder.DisallowUnknownFields()
> 	err := decoder.Decode(&mrru)
> ```

ditto
___
*[pkg/ccl/oidcccl/settings.go, line 190 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57519#-MR_Ctz52jvY_rebbLED:-MR_Ctz52jvY_rebbLEE:b-fpevnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7f5f802287ed572d3b93ae3a1f180a5765271b/pkg/ccl/oidcccl/settings.go#L190)):*
> ```Go
> 
> // OIDCProviderURL is the location of the OIDC discovery document for the auth
> // provider
> ```

nit: here and below, period at end of sentence.

**Pull request merged**
