### PR TITLE
rpc: plumb contexts

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9175)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 27 of 27 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/client_test.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9175#-KR5SoJBsGk_b9K_Izjj:-KR5SoJBsGk_b9K_Izjk:b-7r9tfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf7d27eb6b60d4c1cc3e3951c03a394f1c748d8/storage/client_test.go#L272)):*
> ```Go
> 	if m.rpcContext == nil {
> 		m.rpcContext = rpc.NewContext(
> 			context.TODO(), &base.Context{Insecure: true}, m.clock, m.transportStopper)
> ```

dubious wrapping here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9175#-:-KR5SwwYmX_HwlWIZfMv:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Added a commit that sets the node tags for tests that use `startGossip`. Sample output [here](https://gist.github.com/RaduBerinde/996f9e5a1263c613c65337eaf35b1506) 

---

Review status: 22 of 30 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/client_test.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9175#-KR5SoJBsGk_b9K_Izjj:-KR5UEOiEXkzTM3fYdl7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf7d27eb6b60d4c1cc3e3951c03a394f1c748d8/storage/client_test.go#L272)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> dubious wrapping here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9175#-:-KR5UF-J2MgGf81aUyfl:bbqgu4z)*

**Comment by tamird** [comment]
Last commit is not what I had in mind. Isn't it possible to do this for all gossip instances by having `SetNodeID` return the new context? I think it'll be easier to discuss in its own PR.

---

Reviewed 7 of 7 files at r3, 4 of 4 files at r4, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9175#-:-KR5iW5Vmt2jrnbHfmzu:bkeqw23)*

**Comment by RaduBerinde** [comment]
Sigh.. I'll open a new PR. By the time we do `SetNodeID`, `g.ctx` is already set so we would have to protect it with a mutex or some other nightmare like that.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9175#-:-KR5t1DvE1W_HD9fgw5G:b-2ybeye)*

**Comment by tamird** [comment]
Not necessarily. I'd move `nodeLogTagVal` from server.Server to gossip.Gossip - that way the synchronization is internal.

**Comment by RaduBerinde** [comment]
Why? What is special about gossip? Your argument could apply to any server component. If we had the same issue with tests that set up multiple distsenders, would you be suggesting moving `nodeLogTagVal` to distsender?

And how would that work? The server needs to pass the context with the log tags to various components. In particular, we need to pass it to RPCContext, which we need to create before gossip.

We can [duplicate the same logic](https://github.com/RaduBerinde/cockroach/commit/e5c3a4285dcd8345ebc726efe19c0f900c0b87cf) but I don't buy moving it.

**Comment by tamird** [comment]
I was thinking gossip was the component that discovered the node ID, but
I'm not sure that's true.

I guess what I'm asking for is for SetNodeID to go away, and have the node
ID only be set through the context to avoid this duplication.

**Comment by RaduBerinde** [comment]
The node ID is set by the server code (`node.initNodeID`)

Gossip is created before we know the node ID, and we need to create gossip early so we can pass it to various components. This is a general difficulty with the server code and the reason we have `nodeLogTagVal` in the first place, as well as various `SetNodeID` methods. I looked at it before but found no reasonable way to refactor it to avoid this.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9175#-:-KR68LAN_vxUVln7_shz:bti1w3o)*

**Pull request merged**
