### PR TITLE
opt/exec: implement Presentation

### PR DESCRIPTION
**Pull request by RaduBerinde**
Handle the Presentation physical property by adding a projection
(which either renames columns or adds a renderNode on top).

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt_exec_engine.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23401#-L6rrL8WDKs2Yiu6VLW9:-L6rrL8WDKs2Yiu6VLWA:by2cqpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e9302f22b2cca7b81e631ae4a3fd67a3292615/pkg/sql/opt_exec_engine.go#L192)):*
> ```Go
> 			inputCols = planMutableColumns(n.(planNode))
> 			for i := range inputCols {
> 				inputCols[i].Name = colNames[i]
> ```

Should you add a check to see if `len(inputCols) == len(colNames)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23401#-:-L6rtV5X6i2zZNEGLXdx:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Oops, merged the wrong PR.

**Comment by andy-kimball** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23401#-:-L6rvk-YCCYsKgCTy22L:bnfp4nl)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt_exec_engine.go, line 192 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23401#-L6rrL8WDKs2Yiu6VLW9:-L6rw30x5uG8TvzFMTuU:bvd15s) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e9302f22b2cca7b81e631ae4a3fd67a3292615/pkg/sql/opt_exec_engine.go#L192)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should you add a check to see if `len(inputCols) == len(colNames)`?
</blockquote></details>

The function assumes that `exprs` and `colNames` have the same length.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23401)*

**Pull request merged**
