### PR TITLE
Remove storage.RangeManager interface

### PR DESCRIPTION
**Pull request by bdarnell**
This interface was only being used in one test and has gotten far too
messy to be a useful abstraction over Store functionality.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/2828)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Hmm. Agreed about it being messy, but I'm worried about the replica digging back into the store even more. In particular, the internals are now exposed to Replica and the barrier to use the Store is even lower. Could we refactor the interface instead?

**Comment by bdarnell** [comment]
The interface wasn't serving as an effective deterrent - we would just add whatever we needed to the interface whenever we'd stumble across something that wasn't there. If we have a plan for paring the interface down to something more coherent then we could keep it, but it seems unlikely that we'd ever have a second implementation of this interface. 

If we do want to enforce more of a boundary between Store and Replica, then instead of defining an interface with one implementation I think we should consider splitting `storage` into separate packages, and making anything that needs to cross the `Store`/`Replica` boundary exported.

**Comment by tschottdorf** [comment]
yeah, splitting it into subpackages sounds like a good idea. Can you file? LGTM

**Comment by bdarnell** [comment]
Maybe you should file it since you're more concerned about this than I am. I'm not convinced that enforcing this split will be worth the work.

**Comment by tschottdorf** [comment]
Looking at it a little more, I still feel that it's better to have a bad separation than no separation. Four of the `RangeManager` methods just access the `StoreContext`, those could easily be refactored into a single `Ctx()`. Then there are accessors for the queues, the feed and some other random things. We can just export them all and avoid awkward naming conflicts. If we moved LocalSender into `./storage` (which I think is where it really belongs, since it operates directly on a Store) we could unexport the whole interface. Sure, it's not pretty, but possibly pulling it apart into different packages isn't the kind of code yoga we're looking to do now.

**Comment by bdarnell** [comment]
What does `LocalSender` have to do with it? There are no references to `RangeManager` outside the storage package, so we could unexport it now. 

Is there anything in the RangeManager interface that you think should be removed so the Replica can't access it? Are there any particular parts of Store that would be exposed by the removal of the interface that seems problematic? It would certainly be possible for Replica to break Store's invariants by poking at its internals, but this doesn't seem like an especially high risk in practice.

**Comment by tschottdorf** [comment]
sorry, `LocalSender` was once the reason why the interface was exported in the first place. That dependency seems to have been resolved since.

I have no concrete concerns other than keeping the code clear and maintainable. `Replica` and `Store` always seemed kind of muddled up and I had the hope that some day they'd interface more clearly.

If I'm alone thinking like this, then I'm probably barking up the wrong tree.

**Comment by bdarnell** [comment]
It's a reasonable concern. I don't think the RangeManager interface is currently helpful, but it's also not hurting anything. (I was only motivated to get rid of it by @vivekmenezes's surprise at the underscores in #2826) I'm fine with either removing the interface or leaving it in.

**Comment by tschottdorf** [comment]
I'd still prefer leaving it in, though I must say those underscores are ugly.

**Comment by spencerkimball** [comment]
Hmm, just read this thread (I know...). We started out originally by passing things down into Range...but the number of items started to increase until we just had a ton of wasted memory per range (with potentially lots of ranges).

I agree with Ben that it'd be better at this point to just eliminate the RangeManager interface. It's just extra cognitive complexity and I'd argue it's doing active harm. It's mixing an expectation of a clean abstraction with access to internals which fundamentally break the abstraction – it's promising safety and not delivering. I think it should be discarded with a long term future refactoring TODO to be considered after the fast-evolving relationship between store and range has had a chance to cool down.

**Comment by bdarnell** [comment]
OK. I had prepared an alternate change (https://github.com/cockroachdb/cockroach/compare/master...bdarnell:unexport-range-manager?expand=1), but I can dust off this change instead.

**Comment by bdarnell** [comment]
This branch is now up-to-date with `master`

**Comment by spencerkimball** [comment]
LGTM

**Pull request merged**
