### PR TITLE
sessiondata: add OriginIDForLogicalDataReplication session variable

### PR DESCRIPTION
**Pull request by msbutler**
sessiondata: add OriginIDForLogicalDataReplication session variable
This patch adds a new OriginIDForLogicalDataReplication session variable which
only the internal executor may set, which all LDR writes pass through.

Informs https://github.com/cockroachdb/cockroach/issues/126253

Release note: none

----

sql: bind LogicalDataReplicationOriginID session var value to tableWriter batch

This patch follows a similar strategy for plumbing OmitFromRangefeeds, except
this patch binds the LogicalDataReplicationOriginID val to the batch header
created by all table writers, rather than the batch txn. This was done because
this value will get plumbed to each written key's MVCCValueHeader, even if a
transaction is not used in the kv layer (e.g. via 1 phase commit).

Note this patch does not plumb this session val to other plan nodes (e.g. the
delete range node), as all LDR replicated writes will pass through the
tableWriter plan node.

Informs https://github.com/cockroachdb/cockroach/issues/126253

Release note: none

### CODE REVIEW

**Comment by msbutler** [comment]
the batch header commit is in a seperate PR: https://github.com/cockroachdb/cockroach/pull/126285

I have an end to end test in a draft pr https://github.com/cockroachdb/cockroach/pull/126404

**Review by yuzefovich — APPROVED** [review]
I have some nits, but :lgtm:

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126394#-:-O0UU-rw2Vhy2FweNHq8:bawohbd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @msbutler, and @rafiss)

___
*[`pkg/sql/tablewriter.go` line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126394#-O0UT4StDhqHeBbgi9kf:-O0UT4StDhqHeBbgi9kg:bneqw12) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a6d18cbcef693a815798bbd53140567910d2d5b/pkg/sql/tablewriter.go#L267)):*
> ```Go
> 	tb.b = tb.txn.NewBatch()
> 	tb.putter.Batch = tb.b
> 	tb.b.Header.LockTimeout = tb.lockTimeout
> ```

nit: I think we should unify how we're handling lock timeout and the origin ID. Currently the value for the former is obtained in `init` (done once) and stored for use later; for the latter we'll obtain the value on each new KV batch. I'd probably lean towards using the existing approach of the lock timeout - this should reduce about of plumbing in this change. (Sorry, I know the latter option was my suggestion.)
___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126394#-O0USaKHBbjz3vDE5hHF:-O0USaKHBbjz3vDE5hHG:bu26jqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8508d0f868d58975ad6221995ca3daa10a135a9/pkg/sql/sessiondatapb/local_only_session_data.proto#L532)):*
> ```proto
>   bool optimizer_use_polymorphic_parameter_fix = 134;
>   // OriginIDForLogicalDataReplication is an identifier for the cluster that
> 	// originally wrote the data that are being written in this session. An
> ```

nit: replace tabs with spaces.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126394)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @rafiss, and @yuzefovich)

___
*[`pkg/sql/tablewriter.go` line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126394#-O0UT4StDhqHeBbgi9kf:-O0Up1B6EGB0gxBBuRy9:brn9z3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a6d18cbcef693a815798bbd53140567910d2d5b/pkg/sql/tablewriter.go#L267)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we should unify how we're handling lock timeout and the origin ID. Currently the value for the former is obtained in `init` (done once) and stored for use later; for the latter we'll obtain the value on each new KV batch. I'd probably lean towards using the existing approach of the lock timeout - this should reduce about of plumbing in this change. (Sorry, I know the latter option was my suggestion.)
</blockquote></details>

ah, no worries! your suggestion is indeed much cleaner.
___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126394#-O0USaKHBbjz3vDE5hHF:-O0UplDC7T-hzecIqDns:bltldrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8508d0f868d58975ad6221995ca3daa10a135a9/pkg/sql/sessiondatapb/local_only_session_data.proto#L532)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: replace tabs with spaces.
</blockquote></details>

done, i should probably configure vscode to do this for me.

**Comment by msbutler** [comment]
unrelated flake https://github.com/cockroachdb/cockroach/issues/126344

**Comment by msbutler** [comment]
TFTR!

bors r=yuzefovich

**Pull request merged**
