### PR TITLE
clusterversion,*: remove VersionContainsEstimatesCounter

### LINKED ISSUE #56401: kvserver: clean up VersionContainsEstimatesCounter migration from 20.1
Part of #47447.

### PR DESCRIPTION
**Pull request by irfansharif**
This, and all surrounding migration code and tests, are now safe to
remove. It mostly served as documentation, which we've moved to the
field itself. Part of #47447. Fixes #56401.

(While here, Let's also tell git that `versionkey_string.go` is a
generated file.)

Release note: None

---

First commit is from #57154.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57155)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/kv/kvserver/replica_proposal.go, line 795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57155#-MN7xwMk9oNF0uzWDaJj:-MN7xwMl-OSxsVpH_yp1:b-1jfgpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae990418231921770267b50e98a83f5724ef8e3/pkg/kv/kvserver/replica_proposal.go#L795)):*
> ```Go
> 		res.Replicated.Delta = ms.ToStatsDelta()
> 
> 		// Encode that this command (and any that follow) uses regular
> ```

Add something like this

// This is the result of a migration. See the field for more details.

**Review by irfansharif — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57155#-:-MNAixYZ8zf2_EPbJErc:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/replica_proposal.go, line 795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57155#-MN7xwMk9oNF0uzWDaJj:-MNAiuro3lRjwnT94RL_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae990418231921770267b50e98a83f5724ef8e3/pkg/kv/kvserver/replica_proposal.go#L795)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Add something like this

// This is the result of a migration. See the field for more details.
</blockquote></details>

Done.

**Pull request merged**
