### PR TITLE
acceptance: use the same docker tag for building and running

### PR DESCRIPTION
**Pull request by petermattis**
Ensure that the docker image tags are the same in build/circle-deps.sh
and their usage in the acceptance tests.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4928)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. That `awk` looks a bit freaky, but I don't immediately have a better solution.

**Comment by petermattis** [comment]
Eh? That awk is perfectly readable. I'm sure I'll be able to understand it a month from now. (Adding a comment).

**Comment by tschottdorf** [comment]
I'm not saying it's unreadable, it's more about awk'ing `.go` code from a bash file to get a version string.

**Comment by petermattis** [comment]
We could store the image tags in a file that both `build/circle-deps.sh` and the acceptance tests read. That seems like more trouble than its worth, though.

**Comment by tschottdorf** [comment]
I agree, at least for now. Looks like you need a rebase here.

**Pull request merged**
