### PR TITLE
sql: add MODIFYCLUSTERSETTING role option

### PR DESCRIPTION
**Pull request by solongordon**
Release justification: low-risk update to new functionality

Release note (sql change): Introduced a new MODIFYCLUSTERSETTING role
option. This grants non-admin roles the ability to modify certain
cluster settings, currently limited to settings with the "sql.defaults"
prefix.

### CODE REVIEW

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53930)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/set_cluster_setting.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGKwQAx7MdE3Islo4--:-MGKwQAx7MdE3Islo4-0:boiijff) ([raw file](https://github.com/cockroachdb/cockroach/blob/88dec540737e286b6acf4259f12432f672c961d5/pkg/sql/set_cluster_setting.go#L50)):*
> ```Go
> // nonAdminsCanModify returns whether non-admin users with MODIFYCLUSTERSETTING
> // privileges can modify the specified setting.
> func nonAdminsCanModify(name string) bool {
> ```

@knz Let me know how offensive you find this. I know it would be preferable to introduce a new field on settings for this, but it seems like that would be kind of clunky and introduce a bunch of code churn.
___
*[pkg/sql/set_cluster_setting.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGKwera1Z6wj_pQvQy-:-MGKwera1Z6wj_pQvQy0:bgp75t7) ([raw file](https://github.com/cockroachdb/cockroach/blob/88dec540737e286b6acf4259f12432f672c961d5/pkg/sql/set_cluster_setting.go#L51)):*
> ```Go
> // privileges can modify the specified setting.
> func nonAdminsCanModify(name string) bool {
> 	return strings.HasPrefix(name, "sql.defaults.")
> ```

I'm happy to add more settings to this allowlist. Not sure who is best to make the call on what should be included.

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53930)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/set_cluster_setting.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGKwQAx7MdE3Islo4--:-MGNBklW4KXlEoLKVDPu:bvn6gwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/88dec540737e286b6acf4259f12432f672c961d5/pkg/sql/set_cluster_setting.go#L50)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

@knz Let me know how offensive you find this. I know it would be preferable to introduce a new field on settings for this, but it seems like that would be kind of clunky and introduce a bunch of code churn.
</blockquote></details>

We can start with this and extend it later, for sure.
___
*[pkg/sql/set_cluster_setting.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGKwera1Z6wj_pQvQy-:-MGNBnUI3Egel2HGedRw:bh68qvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/88dec540737e286b6acf4259f12432f672c961d5/pkg/sql/set_cluster_setting.go#L51)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'm happy to add more settings to this allowlist. Not sure who is best to make the call on what should be included.
</blockquote></details>

The SRE team is best: they know which settings customers have asked to tweak in the past and how they decided whether it was safe or not.
___
*[pkg/sql/set_cluster_setting.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGNAycNCZeCRDEt3e7g:-MGNAycNCZeCRDEt3e7h:b64qo52) ([raw file](https://github.com/cockroachdb/cockroach/blob/88dec540737e286b6acf4259f12432f672c961d5/pkg/sql/set_cluster_setting.go#L78)):*
> ```Go
> 	if !hasAdmin {
> 		if nonAdminsCanModify(name) {
> 			hasModify, err := p.HasRoleOption(ctx, roleoption.MODIFYCLUSTERSETTING)
> ```

For readability, I'd swap this around. 
I'm assuming that `HasRoleOption` returns `true` for the `admin` role in any case:

```go
if !nonAdminsCanModify(name) {
   hasAdmin, err := p.HasAdminRole(ctx)
   if err != nil {
     return nil, err
   }
   if !hasAdmin {
       return ... error ...
  }
} else {
   hasModify, err := p.HasRoleOption(ctx, roleoption.MODIFYCLUSTERSETTING)
   if err != nil {
      return nil, err
   }
   if !hasModify {
       return ... error ...
   }
}
```

(In which case it may be worth flipping the boolean to `adminOnlySetting()` for additional readability on the first condition)

**Comment by solongordon** [comment]
I realized that SHOW CLUSTER SETTING and its variants are also admin-only. It seems like these users should be able to show the settings they have permission to modify. I'll make that change.

**Review by solongordon — COMMENTED** [review]
Addressed comments and added logic so that users can SHOW whatever settings they can modify. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-:-MGOqMqT9BDPFxpP16e1:bsr81ij)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/set_cluster_setting.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGKwera1Z6wj_pQvQy-:-MGOoKYT6Smwbsdjrava:b-id1enl) ([raw file](https://github.com/cockroachdb/cockroach/blob/88dec540737e286b6acf4259f12432f672c961d5/pkg/sql/set_cluster_setting.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The SRE team is best: they know which settings customers have asked to tweak in the past and how they decided whether it was safe or not.
</blockquote></details>

Makes sense. I would vote let's merge this for now and update later based on SRE feedback.
___
*[pkg/sql/set_cluster_setting.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGNAycNCZeCRDEt3e7g:-MGOoXPrEbT9pp04YxPA:b-da26g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/88dec540737e286b6acf4259f12432f672c961d5/pkg/sql/set_cluster_setting.go#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

For readability, I'd swap this around. 
I'm assuming that `HasRoleOption` returns `true` for the `admin` role in any case:

```go
if !nonAdminsCanModify(name) {
   hasAdmin, err := p.HasAdminRole(ctx)
   if err != nil {
     return nil, err
   }
   if !hasAdmin {
       return ... error ...
  }
} else {
   hasModify, err := p.HasRoleOption(ctx, roleoption.MODIFYCLUSTERSETTING)
   if err != nil {
      return nil, err
   }
   if !hasModify {
       return ... error ...
   }
}
```

(In which case it may be worth flipping the boolean to `adminOnlySetting()` for additional readability on the first condition) 
</blockquote></details>

Done. I moved this function to `settings.AdminOnly`.

**Review by knz — COMMENTED** [review]
this looks about right. just one round of polishing and this is good to go

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-:-MGOxKxk5GNAJV44WTK5:b-rw8367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/crdb_internal.go, line 955 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOvoV31CknUM5YvLlD:-MGOvoV31CknUM5YvLlE:b-u7rjd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/crdb_internal.go#L955)):*
> ```Go
> )`,
> 	populate: func(ctx context.Context, p *planner, _ *dbdesc.Immutable, addRow func(...tree.Datum) error) error {
> 		hasAdmin, err := p.HasAdminRole(ctx)
> ```

Maybe this code would be simpler by not forcing an error upfront and simply filtering out anything the current user cannot see (with the option to see an empty result if they don't have enough privilege)

i.e.
```go
hasAdmin, ... := ...
hasModify, ... := ...

for _, k := range settings.Keys() {
    if !hasAdmin &&  (!hasModify || settings.AdminOnly(k))) {
         continue
    }
   ...
```

what do you think? (your call)
___
*[pkg/sql/set_cluster_setting.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOwfoMC9BaPh3I7Zda:-MGOwfoMC9BaPh3I7Zdb:bfiyy2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/set_cluster_setting.go#L68)):*
> ```Go
> 
> 	if settings.AdminOnly(name) {
> 		if err := p.RequireAdminRole(ctx, fmt.Sprintf("set '%s'", name)); err != nil {
> ```

nit: I'd add "cluster setting" in that error message
___
*[pkg/sql/show_cluster_setting.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOwopRAsFoaU5ZHgJD:-MGOwopRAsFoaU5ZHgJE:b-ih3kmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/show_cluster_setting.go#L111)):*
> ```Go
> 	}
> 
> 	if settings.AdminOnly(name) {
> ```

could you factor the check in the function above and this one into a common function (I think only the string in the error is different)
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOx5ms8wNkcdbpzTFd:-MGOx5ms8wNkcdbpzTFe:b-ska66u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/delegate/show_all_cluster_settings.go#L23)):*
> ```Go
> 	stmt *tree.ShowClusterSettingList,
> ) (tree.Statement, error) {
> 	hasModify, err := d.catalog.HasRoleOption(d.ctx, roleoption.MODIFYCLUSTERSETTING)
> ```

I don't think you need this check here since the vtable internally already checks privs?
___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOwx8HBNPRS2nJfQ6n:-MGOwx8HBNPRS2nJfQ6o:bdr0dub) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/logictest/testdata/logic_test/cluster_settings#L117)):*
> ```
> ----
> cloudstorage.gs.default.key    foo
> sql.defaults.default_int_size  4
> ```

nit: newline missing at end of file

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53930)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 955 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOvoV31CknUM5YvLlD:-MGP-M7L0RLfIm7f9fSV:b-jxt86s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/crdb_internal.go#L955)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe this code would be simpler by not forcing an error upfront and simply filtering out anything the current user cannot see (with the option to see an empty result if they don't have enough privilege)

i.e.
```go
hasAdmin, ... := ...
hasModify, ... := ...

for _, k := range settings.Keys() {
    if !hasAdmin &&  (!hasModify || settings.AdminOnly(k))) {
         continue
    }
   ...
```

what do you think? (your call)
</blockquote></details>

Yeah, I agree that would simplify things a bit. On the other hand, I think it's a nicer user experience to get an error explaining why you can't see the data rather than just an empty data set. Because of that, I think I prefer to keep this as-is.
___
*[pkg/sql/set_cluster_setting.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOwfoMC9BaPh3I7Zda:-MGOymH19OhEohE73E4-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/set_cluster_setting.go#L68)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: I'd add "cluster setting" in that error message
</blockquote></details>

Done.
___
*[pkg/sql/show_cluster_setting.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOwopRAsFoaU5ZHgJD:-MGP4NV75n8xQde09NWH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/show_cluster_setting.go#L111)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

could you factor the check in the function above and this one into a common function (I think only the string in the error is different)
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOx5ms8wNkcdbpzTFd:-MGP4ON8DhkFOyPTLfeP:b-83o2he) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/delegate/show_all_cluster_settings.go#L23)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't think you need this check here since the vtable internally already checks privs?
</blockquote></details>

Yeah, though it's a bit nicer UX because the error message says "SHOW CLUSTER SETTINGS" rather than "read crdb_internal.cluster_settings"
___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53930#-MGOwx8HBNPRS2nJfQ6n:-MGOz0xO8XycfDjE5apl:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2232baf0920bc0526f70b4e741d16e1fde7ca2cd/pkg/sql/logictest/testdata/logic_test/cluster_settings#L117)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: newline missing at end of file
</blockquote></details>

Done

**Review by knz — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53930)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @solongordon)

**Pull request merged**
