### PR TITLE
sql: add NotVisible to index descriptor

### PR DESCRIPTION
**Pull request by wenyihu6**
This commit adds a new field `NotVisible` to the struct `IndexDescriptor`. Since
primary indexes cannot be not visible, it also includes another check in
`pkg/sql/catalog/tabledesc/validate.go`. Since the invisible index feature has
not been introduced yet, all indexes created should be visible.

See also: https://github.com/cockroachdb/cockroach/pull/84776

Assists: https://github.com/cockroachdb/cockroach/issues/72576

Release note: none

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

```
message: ThisPR {
  optional bool lgtm = 1 [(gogoproto.nullable) = false];
}

return &ThisPR{lgtm: true}
```

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-:-N7WdFTJ8HEXrjI1CyDP:b-cbvz73)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @postamar)

**Review by mgartner — APPROVED** [review]
:lgtm: Very nicely done! Let's get someone on SQL Schema to stamp this before merging.

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-:-N7X-zW120zPd9XeVt8D:b-xdmgnz)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @postamar and @wenyihu6)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-N7WvSgQ2Wsp0lW9Dqqa):*
nit: [we prefer to use the imperative mood for commit titles](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title), like `sql: add NotVisible to index descriptor`

I _think_ we typically use the present tense in the commit body (e.g. "This PR adds ..." rather than "This PR added ..."), but I don't see that as an official guideline in the doc linked above, so that's up to you if you want to change it.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-N7WwiTFBuVkkAGFGkmF):*
super nit: PR => commit
___
*[`pkg/sql/catalog/catformat/index.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-N7WwtpO0_oJqTsElhJa:-N7WwtpO0_oJqTsElhJb:b-qp1k15) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4610f622385029b9b8d0d7c0be2b8f4ba961240/pkg/sql/catalog/catformat/index.go#L179)):*
> ```Go
> 
> 	if index.NotVisible {
> 		f.WriteString(" NOT VISIBLE")
> ```

Reminder to add tests for this with `SHOW CREATE TABLE` once not visible indexes can be added.
___
*[`pkg/sql/opt/indexrec/hypothetical_index.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-N7Wz4wb7jorvqw9Tfzh:-N7Wz4wb7jorvqw9Tfzi:b-g5wufq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4610f622385029b9b8d0d7c0be2b8f4ba961240/pkg/sql/opt/indexrec/hypothetical_index.go#L52)):*
> ```Go
> 
> 	// notVisible indicates if an index is not visible to the optimizer.
> 	notVisible bool
> ```

I don't think we need this field, we can just always return false in `IsNotVisible` below. I don't see a case where we'd make a recommendation to the user to create an invisible index.

You could add a TODO [here](https://github.com/cockroachdb/cockroach/blob/e1fd17bb00fc49e76fa89f2361afed7893826960/pkg/sql/opt/indexrec/hypothetical_table.go#L63) to handle cases where an invisible index exists that should be made non-visible to improve the query plan.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-N7X-If69Ks8u_hZy1wU:-N7X-If69Ks8u_hZy1wV:b-b7im5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4610f622385029b9b8d0d7c0be2b8f4ba961240/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L46)):*
> ```Go
> 		IsInverted:     n.Inverted,
> 		IsConcurrently: n.Concurrently,
> 		IsNotVisible:   false, // TODO(wenyihu6): populate hidden property after CREATE
> ```

nit: hidden => IsNotVisible

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by wenyihu6** [comment]
*[`pkg/sql/opt/indexrec/hypothetical_index.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-N7Wz4wb7jorvqw9Tfzh:-N7_GIXg-LMNrRfWrfDx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4610f622385029b9b8d0d7c0be2b8f4ba961240/pkg/sql/opt/indexrec/hypothetical_index.go#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think we need this field, we can just always return false in `IsNotVisible` below. I don't see a case where we'd make a recommendation to the user to create an invisible index.

You could add a TODO [here](https://github.com/cockroachdb/cockroach/blob/e1fd17bb00fc49e76fa89f2361afed7893826960/pkg/sql/opt/indexrec/hypothetical_table.go#L63) to handle cases where an invisible index exists that should be made non-visible to improve the query plan.
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84763#-N7X-If69Ks8u_hZy1wU:-N7_GOJIDHpIByS2RD0d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4610f622385029b9b8d0d7c0be2b8f4ba961240/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L46)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: hidden => IsNotVisible
</blockquote></details>

Done.

**Pull request merged**
