### PR TITLE
workload/tpcc: fix --partition-affinity flag

### PR DESCRIPTION
**Pull request by nvb**
This was broken by b4e7796.

The second commit adds a new roachtest that uses the flag and would have caught this regression.

cc. @sploiselle

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39649)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/workload/tpcc/tpcc.go, line 570 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39649#-LmDJtpcEma0WyeaLt2N:-LmDJtpcEma0WyeaLt2O:b-66o3zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce26a553dced258e97937541e96f58728adde5d9/pkg/workload/tpcc/tpcc.go#L570)):*
> ```Go
> 		db := dbs[warehouse%len(dbs)]
> 
> 		ql.WorkerFns = append(ql.WorkerFns, nil)
> ```

This seems like now this can race on accessing the underlying array of `ql.WorkerFns`. I don't think it's a particularly problematic hazard but when the slice re-allocs you might race with a goroutine constructing a new worker below.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39649)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/workload/tpcc/tpcc.go, line 570 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39649#-LmDJtpcEma0WyeaLt2N:-LmG6WkQ-4hlcbPVrdyU:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce26a553dced258e97937541e96f58728adde5d9/pkg/workload/tpcc/tpcc.go#L570)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This seems like now this can race on accessing the underlying array of `ql.WorkerFns`. I don't think it's a particularly problematic hazard but when the slice re-allocs you might race with a goroutine constructing a new worker below. 
</blockquote></details>

Good point. Done.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39649#-:-LmG7A_J8gt924U_xmGm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
bors r=ajwerner

**Pull request merged**
