### PR TITLE
opt: build ANY expressions as regular subqueries within UDFs

### LINKED ISSUE #87291: sql: allow subqueries in UDFs
We should lift the restriction that disallows subqueries within user-defined function bodies.

Epic: CRDB-20370

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: build ANY expressions as regular subqueries within UDFs

To support execution of ANY expressions within UDFs, the optimizer
builds them as subqueries with GroupBy expressions instead. The
transformation simulates the peculiar behavior of ANY expressions. See
`CustomFuncs.ConstructGroupByAny` for more details on this
transformation.

By constructing ANY expressions within UDFs as subqueries, we avoid
adding complexity to the execution engine, which is not currently
capable of evaluating ANY expressions within the context of a UDF.

Fixes #87291

Release note: None

#### opt: fix GenerateIndexScans comment

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
I haven't looked into the specifics yet, but a quick comment based on the PR message - agg filters can prevent decorrelation, so I think we're better off using something like `bool_or(col IS NULL) AND NULL`

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-:-NQRHbY_6qzcETR_76MR:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/builder.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-NQR6WyL7MKXkzDnh45k:-NQR6WyL7MKXkzDnh45l:b6hq6uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9b8cea3f666dcb2df803fcce7c076072e60190/pkg/sql/opt/optbuilder/builder.go#L133)):*
> ```Go
> 	// udfDepth is greater than zero, then the builder is currently building
> 	// expressions within one or more UDFs.
> 	udfDepth int
> ```

It seems like we only need to know if we're inside a UDF, so would a bool be sufficient to follow YAGNI principles?
___
*[`pkg/sql/opt/optbuilder/subquery.go` line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-NQR4t2MB4osGcEiWu5W:-NQR4t2MB4osGcEiWu5X:b-le60tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9b8cea3f666dcb2df803fcce7c076072e60190/pkg/sql/opt/optbuilder/subquery.go#L376)):*
> ```Go
> 
> 	if b.udfDepth > 0 {
> 		// Any expressions are cannot be built by the optimizer within a UDF, so
> ```

nit: Any expressions cannot

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 1 of 1 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-:-NQRSWzX0mJyDrV1NUDC:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by mgartner — COMMENTED** [review]
> I haven't looked into the specifics yet, but a quick comment based on the PR message - agg filters can prevent decorrelation, so I think we're better off using something like bool_or(col IS NULL) AND NULL

Done.

> It seems like we only need to know if we're inside a UDF, so would a bool be sufficient to follow YAGNI principles?

Ok, switched to a boolean for now. We'll have to use an integer once we support UDFs that call other UDFs.

> nit: Any expressions cannot

Fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-:-NQRieOAEcyYQrFuTk6x:b-wv5w4x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
Just found `constructGroupByAny` in `decorrelate_funcs.go` - were you aware of this?

**Comment by mgartner** [comment]
> Just found constructGroupByAny in decorrelate_funcs.go - were you aware of this?

Heh, no. Looks like we reinvented the wheel here. And a worse version - `constructGroupByAny` is thorough in constructing an expression that can be decorrelated and avoid apply-joins. I'll see if I can reuse the logic there.

**Comment by mgartner** [comment]
This was a great find @DrewKimball! It should be easy to reuse the same code as `constructGroupByAny` AND I found a bug in that code which should be an easy fix, #98691. I'm hoping to update the PR shortly.

**Comment by mgartner** [comment]
Ok this is ready for another look. The first commit is from #98700.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice refactoring!

> Reviewed 9 of 9 files at r5, 6 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-:-NQb5v0a4MjMrRFKGySr:b-5ei8sr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/subquery.go` line 377 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-NQb5dJ44I5LWn59TMey:-NQb5dJ44I5LWn59TMez:b-8b3lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f2bdbbed1347d85a65ec89dae79e305f41d6de/pkg/sql/opt/optbuilder/subquery.go#L377)):*
> ```Go
> 	if b.insideUDF {
> 		// Any expressions cannot be built by the optimizer within a UDF, so
> 		// build them as subqueries with GroupBy expressions instead.
> ```

[nit] `GroupBy`->`ScalarGroupBy`

**Review by rharding6373 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98375)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98375)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/subquery.go` line 377 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98375#-NQb5dJ44I5LWn59TMey:-NQegR8qEBWOp_1Tvf7v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f2bdbbed1347d85a65ec89dae79e305f41d6de/pkg/sql/opt/optbuilder/subquery.go#L377)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `GroupBy`->`ScalarGroupBy`
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
