### PR TITLE
roachtest: fix pg_regress diffs

### LINKED ISSUE #118388: roachtest: pg_regress failed
roachtest.pg_regress [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13713791?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13713791?buildTab=artifacts#/pg_regress) on master @ [b59a83a1cd31d8e00f39cf32b1cf99b41b96e28e](https://github.com/cockroachdb/cockroach/commits/b59a83a1cd31d8e00f39cf32b1cf99b41b96e28e):

```
@@ -281130,11 +277786,7 @@
  begin;
  set timezone to 'UTC';
  alter table rewriteme alter column bar type timestamp;
-<<<<<<< HEAD
 @@ -530,7 +761,6 @@
-=======
-@@ -530,7 +760,6 @@
->>>>>>> 566e82d5737 (roachtest: add new roachtest to run pg_regress against crdb)
  alter table rewriteme alter column bar type timestamptz;
  set timezone to 'Europe/London';
  alter table rewriteme alter column bar type timestamp; -- does rewrite
@@ -281142,11 +277794,7 @@
  rollback;
  -- typed tables are rewritten when their type changes.  Don't emit table
  -- name, because firing order is not stable.
-<<<<<<< HEAD
 @@ -541,21 +771,52 @@
-=======
-@@ -541,21 +770,52 @@
->>>>>>> 566e82d5737 (roachtest: add new roachtest to run pg_regress against crdb)
                 pg_event_trigger_table_rewrite_reason();
  END;
  $$;
@@ -281202,11 +277850,7 @@
  CREATE TABLE event_trigger_test (a integer, b text);
  CREATE OR REPLACE FUNCTION start_command()
  RETURNS event_trigger AS $$
-<<<<<<< HEAD
 @@ -563,37 +824,66 @@
-=======
-@@ -563,37 +823,66 @@
->>>>>>> 566e82d5737 (roachtest: add new roachtest to run pg_regress against crdb)
  RAISE NOTICE '% - ddl_command_start', tg_tag;
  END;
  $$ LANGUAGE plpgsql;
@@ -281282,11 +277926,7 @@
  -- Check the object addresses of all the event triggers.
  SELECT
      e.evtname,
-<<<<<<< HEAD
 @@ -604,13 +894,22 @@
-=======
-@@ -604,13 +893,22 @@
->>>>>>> 566e82d5737 (roachtest: add new roachtest to run pg_regress against crdb)
      LATERAL pg_identify_object_as_address('pg_event_trigger'::regclass, e.oid, 0) as b,
      LATERAL pg_get_object_address(b.type, b.object_names, b.object_args) as a
    ORDER BY e.evtname;
If the diff is expected, copy regression.diffs from the test artifacts to pkg/cmd/roachtest/testdata/regression.diffs
test artifacts and logs in: /artifacts/pg_regress/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13713791/pg-regress/1706356978397/1706358147432)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pg_regress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35709

### PR DESCRIPTION
**Pull request by rharding6373**
The pg_regress diffs had some remnant diff markers, which have now been removed.

Epic: none
Fixes: #118388

Release note: none

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118452#-:-NpOVo1584e_T4VRHBLn:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by rharding6373** [comment]
TFTR!

bors r+

**Comment by rharding6373** [comment]
bors r=DrewKimball

**Comment by rharding6373** [comment]
There was some transient failure. Trying again.

bors r+

**Pull request merged**
