### PR TITLE
roachtest: backup2TB writes perf artifacts for roachperf

### PR DESCRIPTION
**Pull request by adityamaru**
The backup2TB roachtest now writes a histogram with the
time taken by the backup to the artifacts directory. This
change will be followed by teaching roachperf to read this
value, parse the backup size and number of nodes from the
test name, and plot the rate of backup per node.

Release note: None

Informs: #49813

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63914)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @nihalpednekar, and @pbardea)

___
*[pkg/cmd/roachtest/backup.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnwW6j4g-_xeKTP9Ss:-MYnwW6j4g-_xeKTP9St:b-8pujft) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L51)):*
> ```Go
> 
> // writeArtifacts writes a histogram with the backupDuration to the artifacts
> // directory. This information is used by roachperf to track backup performance.
> ```

A question I have that might be good to write a few words about: are we writing a histogram snapshot based on a single value here? Why is this preferable to writing the duration out directly?  Is this to make it easier to reuse existing code in roachperf?  
___
*[pkg/cmd/roachtest/backup.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnwMcYANs1vest2mhq:-MYnwMcYANs1vest2mhr:b-dtf7wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L55)):*
> ```Go
> 	reg := histogram.NewRegistry(2 * time.Hour)
> 	reg.GetHandle().Get(histogramName).Record(backupDuration)
> 	backupPerfDir := perfArtifactsDir + "/stats.json"
> ```

naming: this isn't a directory, perhaps `statsFile`?
___
*[pkg/cmd/roachtest/backup.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnxIl4282wyZnl7wVs:-MYnxIl4282wyZnl7wVt:b-2japq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L56)):*
> ```Go
> 	reg.GetHandle().Get(histogramName).Record(backupDuration)
> 	backupPerfDir := perfArtifactsDir + "/stats.json"
> 	_ = os.MkdirAll(filepath.Dir(backupPerfDir), 0755)
> ```

It'll be caught by the os.Create below so it is minor, but any reason to skip the error check here?
___
*[pkg/cmd/roachtest/backup.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnvi3E711_w3ZWNuxw:-MYnvi3F9O_xUVmxSstr:b-oe0yon) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L63)):*
> ```Go
> 	jsonEnc := json.NewEncoder(jsonF)
> 	reg.Tick(func(tick histogram.Tick) {
> 		if jsonEnc != nil {
> ```

No harm in being defensive I suppose, but jsonEnc can't be nil here afaik.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63914)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @nihalpednekar)

___
*[pkg/cmd/roachtest/backup.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYtpa553TwyaYjuodzG:-MYtpa553TwyaYjuodzH:b-w99vmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L62)):*
> ```Go
> 	}
> 	jsonEnc := json.NewEncoder(jsonF)
> 	reg.Tick(func(tick histogram.Tick) {
> ```

While looking through the roachperf PR, I wonder if we can just `tick` at the start of the backup and `tick` again at the end. That way we could use the `totalElapsed` time on the roachperf side?

I may be missing something here though.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63914)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nihalpednekar, @pbardea, and @stevendanna)

___
*[pkg/cmd/roachtest/backup.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnwW6j4g-_xeKTP9Ss:-MYyF4d96gh-VxBcLI5Q:bmx2p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L51)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

A question I have that might be good to write a few words about: are we writing a histogram snapshot based on a single value here? Why is this preferable to writing the duration out directly?  Is this to make it easier to reuse existing code in roachperf?  
</blockquote></details>

I've reworked this a little bit on Paul's suggestion. We can simply rely on the elapsed time between two ticks instead of recording a single value and using that as the duration. Let me know if this makes more sense!
___
*[pkg/cmd/roachtest/backup.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnwMcYANs1vest2mhq:-MYxqO6K3YZMri595zBJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L55)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

naming: this isn't a directory, perhaps `statsFile`?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/backup.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnxIl4282wyZnl7wVs:-MYxqOedAR5MoCXOtASJ:b-9atwa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L56)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

It'll be caught by the os.Create below so it is minor, but any reason to skip the error check here?
</blockquote></details>

No reason, just copy-pasted from somewhere in workload.go, added an error check.
___
*[pkg/cmd/roachtest/backup.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYtpa553TwyaYjuodzG:-MYyEh9CCscme8u4EfjD:b8g80z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L62)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

While looking through the roachperf PR, I wonder if we can just `tick` at the start of the backup and `tick` again at the end. That way we could use the `totalElapsed` time on the roachperf side?

I may be missing something here though.
</blockquote></details>

I think you're right. I believe it is okay to not bother recording any "counts" in the histogram since we have a single operation unlike workloads. I've restructured the code to tick twice, and then I'll make the appropriate changes on the roachperf PR.
___
*[pkg/cmd/roachtest/backup.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63914#-MYnvi3E711_w3ZWNuxw:-MYxqkBa6CCBgiH8efSp:b-f3kcc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdeebbd4b6dd8dda70735ba22152d3628e582b7/pkg/cmd/roachtest/backup.go#L63)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

No harm in being defensive I suppose, but jsonEnc can't be nil here afaik.
</blockquote></details>

another copy pasta, removed the unnecessary nil check.

**Comment by adityamaru** [comment]
The above generates the following, when run locally. Roachperf will use the diff between the "Now" fields:

```
{"Name":"backup/2TB","Hist":{"LowestTrackableValue":100000,"HighestTrackableValue":7200000000000,"SignificantFigures":1,"Counts":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"Elapsed":89612000,"Now":"2021-04-23T10:31:52.38781Z"}
{"Name":"backup/2TB","Hist":{"LowestTrackableValue":100000,"HighestTrackableValue":7200000000000,"SignificantFigures":1,"Counts":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"Elapsed":15472930000,"Now":"2021-04-23T10:32:07.86074Z"}
```

**Review by pbardea — APPROVED** [review]
LGTM

**Comment by adityamaru** [comment]
TFTR!

bors r=pbardea

**Pull request merged**
