### PR TITLE
sql: fix schema change failure test

### PR DESCRIPTION
**Pull request by pbardea**
This schema change test relied on the backfiller not ingesting any of
the keys that violated the unique constraint, rather than on the
ROLLBACK job cleaning up the KVs generated.

Changing `schemachanger.backfiller.buffer_size` and
`schemachanger.backfiller.max_buffer_size` to 1 triggered a failure on
this test. This simulates what happens when a batch that does not
contain a violating key is ingested and flushed in the backfiller.

After this change, the test waits for the rollback job and corresponding
GC job to complete before checking for any garbage.

Release note: None

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/sql/schema_changer_test.go, line 1704 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59321#-MS0ESn14sTIoyEBCjHx:-MS0ESn26wly6arhFxoc:bpmg47u) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ba90ca5e68c5a78d73610e4a0a1ea0fb6eff95/pkg/sql/schema_changer_test.go#L1704)):*
> ```Go
> 
> 	// Check that constraints are cleaned up.
> 	tableDesc := catalogkv.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "t", "test")
> ```

Don't we still need to look up the table descriptor again after the schema change has rolled back?
___
*[pkg/sql/schema_changer_test.go, line 4475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59321#-MS0Emk2DI7rsDK-NOs6:-MS0Emk2DI7rsDK-NOs7:bgdl2y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea85c86fb810feaf3cefd7cb4ee6b915cdec536/pkg/sql/schema_changer_test.go#L4475)):*
> ```Go
> 
> 	if err := tx.Commit(); !testutils.IsError(
> 		err, `unique constraint "v_unique"`,
> ```

Maybe add a comment explaining that the error varies?

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by pbardea** [comment]
TFTR!
bors r+

**Comment by pbardea** [comment]
Rebased to address a merge skew.
bors r+

**Pull request merged**
