### PR TITLE
replica_rac2: add Processor, that integrates RangeController with kvs…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…erver

All dependencies of Processor on kvserver etc. are abstracted out for unit testing.

Informs #128308

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I am still adding testcases to the datadriven test, but this is ready for an initial look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-:-O4CTo0q7Wd5iBV-1MwC:b-pcaz13)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by sumeerbhola — COMMENTED** [review]
Added more test cases. I verified that all non-panic code paths in replica_rac2 have test coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-:-O4GDhCI7Fes9Y7xY43R:be43tqw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 1 of 4 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128927)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GHY7Z2P5H9thM8gAz:-O4GHY7Z2P5H9thM8gB-:b-pai9ko) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L78)):*
> ```Go
> // SafeFormat implements the redact.SafeFormatter interface.
> func (rs ReplicaSet) SafeFormat(w redact.SafePrinter, _ rune) {
> 	var buf [10]roachpb.ReplicaDescriptor
> ```

Any particular reason to pre-size the buf cap to 10 and not 5 or 3?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 198 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GLJGQEF4ECLGtCaKa:-O4GLJGQEF4ECLGtCaKb:bhgsbfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L198)):*
> ```Go
> // this replica is the leader.
> //
> // State transitions are NotEnabledWhenLeader => EnabledWhenLeaderV1Encoding
> ```

nit: below the processor method requires that levels are ratcheted up and the state transition makes that point here. I'd suggest adding an additional comment here along the lines of `i.e. the level may never regress`.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GKnOj7zpaSAfYxnWd:-O4GKnOj7zpaSAfYxnWe:bxs521n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L259)):*
> ```Go
> // RawNode.Step, and HandleRaftReadyRaftMuLocked. We rely on the current
> // external behavior where Store.processRequestQueue (which calls Step using
> // queued messages) will always return true if there wre any messages that
> ```

nit: were



_Code quote:_
```Go
wre
```
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GLyAdCrpy17LnwFnO:-O4GLyAdCrpy17LnwFnP:bht0rug) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L298)):*
> ```Go
> 	// can close, and return tokens. We do this call from
> 	// disconnectReplicationRaftMuLocked. Make sure this is not too late in
> 	// that these flow tokens may be needed by others.
> ```

nit: move locking requirements to separate comment line, just above method declaration. This is currently inconsistent.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 452 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GNLSh1c4ddMMoFtEW:-O4GNLSi517LhY1XIn5k:b-63y9zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L452)):*
> ```Go
> }
> 
> func (p *processorImpl) OnDestroyRaftMuLocked(ctx context.Context) {
> ```

nit: consider duplicating comments from the iface on the impl methods. Feel free to ignore, this may just be a personal preference.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 465 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GNc809q8xj5RZtK2l:-O4GNc809q8xj5RZtK2m:b-9cuu0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L465)):*
> ```Go
> }
> 
> func (p *processorImpl) SetEnabledWhenLeaderRaftMuLocked(level EnabledWhenLeaderLevel) {
> ```

nit: why no raft mu assertion here?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 509 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GOKco0J1Qp16F_0XG:-O4GOKco0J1Qp16F_0XH:bqumdsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L509)):*
> ```Go
> 	p.opts.Replica.RaftMuAssertHeld()
> 	p.opts.Replica.MuAssertHeld()
> 	if p.raftMu.replicas == nil {
> ```

nit: add a comment mentioning this state transition when replicas was previously nil
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 520 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GOofWAsrBBCo49q5p:-O4GOofWAsrBBCo49q5q:b9ci6x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L520)):*
> ```Go
> // the entries provided to RangeController in the next call to
> // HandleRaftEventRaftMuLocked.
> func (p *processorImpl) makeStateConsistentRaftMuLockedProcLocked(
> ```

(note to self) resume here.

**Review by kvoli — COMMENTED** [review]
Overall looks great! I left some questions scattered around.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-:-O4GwV7m1euI4ZLWQS19:b-bk93t3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GgYh0-cHgtT51tmiN:-O4GgYh0-cHgtT51tmiO:b-10slab) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L516)):*
> ```Go
> }
> 
> // nextUnstableIndex is used to initialize the state of the send-queues if
> ```

nit: start comment with `makeConsistent...`.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 700 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GnT2v0PiOdxXiwhNJ:-O4GnT2v0PiOdxXiwhNK:b2342pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L700)):*
> ```Go
> 	// not become stale during this method.
> 	var isLeaderUsingV2Protocol bool
> 	func() {
> ```

nit: consider making this (and possibly other above) closures return the values required, instead of mutating the vars in the parent scope. 
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 736 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GrgPx0__QF3G4nr1W:-O4GrgPx0__QF3G4nr1X:b2pgpwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L736)):*
> ```Go
> 			}()
> 		} else {
> 			raftPri = raftpb.LowPri
> ```

Can't users also run v1 turned on for regular traffic, even if not the default; forcing the pri here to be lowpri could conflict?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4Gw5Lj4wGwqITTTr-V:-O4Gw5Lj4wGwqITTTr-W:bpcnous) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L1)):*
> ```
> # NB: this replica is on n1, s2 and for range r3. The tenant-id is 4 and the
> ```

nit: consider adding an init command that inits and prints the init state, the comment is helpful but seeing a formatted output similar to below may be clearer and more consistent.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4Gt9YWBL2N8xgalu39:-O4Gt9YX7MmvCHL2UVt8:b-ckoef2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L90)):*
> ```
> .....
> AdmitRaftEntries:
>  ACWorkQueue.Admit({TenantID:4 Priority:low-pri CreateTime:2 RequestedCount:107 Ingested:false CallbackState:{StoreID:2 RangeID:3 ReplicaID:5 LeaderTerm:50 Index:25 Priority:LowPri}})
> ```

Why is this 107 and not 100 from:

```
entries=v1/i25/t45/pri0/time2/len100
```



_Code quote:_
```
RequestedCount:107
```
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GtcXC4C0zvOzxqd7u:-O4GtcXC4C0zvOzxqd7v:bb7nx1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L148)):*
> ```
>  RaftNode.LeaderLocked() = 11
>  Replica.LeaseholderMuLocked
>  RaftNode.GetAdmittedLocked) = [24, 25, 25, 25]
> ```

rm )
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GuJtM6pBajUK2pgCZ:-O4GuJtM6pBajUK2pgC_:bx405tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L171)):*
> ```
>  Replica.RaftMuAssertHeld
>  Replica.MuLock
>  RaftNode.NextUnstableIndexLocked() = 25
> ```

Is `UnstableIndex > StableIndex` an artifact of the test or something that would happen on a real cluster?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4Gtb1Z1xY7GVjDukuy:-O4Gtb1Z1xY7GVjDukuz:bb7nx1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L175)):*
> ```
>  RaftNode.LeaderLocked() = 11
>  Replica.LeaseholderMuLocked
>  RaftNode.GetAdmittedLocked) = [24, 25, 25, 25]
> ```

rm )
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GtZfb0YBA6nMi-2Su:-O4GtZfb0YBA6nMi-2Sv:bb7nx1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L196)):*
> ```
>  RaftNode.LeaderLocked() = 11
>  Replica.LeaseholderMuLocked
>  RaftNode.GetAdmittedLocked) = [24, 26, 25, 26]
> ```

rm )
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 328 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GtsJV9VV4IQLwhLeW:-O4GtsJV9VV4IQLwhLeX:b-p28h6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L328)):*
> ```
> Raft: leader: 5 leaseholder: 10 stable: 27 next-unstable: 25 my-term: 52 admitted: [27, 27, 27, 27]
> 
> on-desc-changed  replicas=n11/s11/11,n1/s2/5
> ```

nit: could we use the replica set formatting here instead?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 396 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GvP-z6l326LaUJFdQ:-O4GvP-z6l326LaUJFdR:b-f1z0ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L396)):*
> ```
> 
> # Enqueue piggybacked MsgAppResp.
> enqueue-piggybacked-admitted from=25 to=5
> ```

Why 25? I don't see a replicaID w/ 25

```
(replicaSet=[(n1,s2):5,(n11,s11):11], leaseholder=10, nextRaftIndex=28)
```

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-:-O4HbPtbCaRQCQtoZMaU:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GHY7Z2P5H9thM8gAz:-O4HG1JXEPALFu_9lqQW:bsuyutd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L78)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Any particular reason to pre-size the buf cap to 10 and not 5 or 3?
</blockquote></details>

Changed to 7 :)
Figured an allocation is worse than a slightly bigger stack.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 198 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GLJGQEF4ECLGtCaKa:-O4HGKpx-x0g4KgtWZUa:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L198)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: below the processor method requires that levels are ratcheted up and the state transition makes that point here. I'd suggest adding an additional comment here along the lines of `i.e. the level may never regress`.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GKnOj7zpaSAfYxnWd:-O4HGYe3-2CY_NGJkrXA:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L259)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: were
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GLyAdCrpy17LnwFnO:-O4HGngO782q0XaFcwNq:bh9ou49) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L298)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: move locking requirements to separate comment line, just above method declaration. This is currently inconsistent.
</blockquote></details>

I assumed you meant the missing `// raftMu is held.`. If yes, added.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 452 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GNLSh1c4ddMMoFtEW:-O4HH7Bb2-Y8V5s6xZEL:b7wj7fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L452)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider duplicating comments from the iface on the impl methods. Feel free to ignore, this may just be a personal preference.
</blockquote></details>

Those are long comments, that are likely to be updated. I've added the shorter boilerplate ones, that reference the interface.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 465 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GNc809q8xj5RZtK2l:-O4HIG4zCBf_oLd_O1ly:b-mj3rib) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L465)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: why no raft mu assertion here?
</blockquote></details>

Good catch. Added.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 509 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GOKco0J1Qp16F_0XG:-O4HIZKQAYFC_PYOgavY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L509)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: add a comment mentioning this state transition when replicas was previously nil
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GgYh0-cHgtT51tmiN:-O4HMbqJ8m8FQsNIdiG3:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L516)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: start comment with `makeConsistent...`.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 520 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GOofWAsrBBCo49q5p:-O4HMcgW7NKFn-QQ1mQ6:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L520)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

(note to self) resume here.
</blockquote></details>

Ack
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 700 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GnT2v0PiOdxXiwhNJ:-O4HMlngAEGJt3uCkfB8:bgk5k8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L700)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider making this (and possibly other above) closures return the values required, instead of mutating the vars in the parent scope.
</blockquote></details>

I find trivial closures like these have simpler code when mutating. One just reads them in a linear manner as the rest of the enclosing code and they exist simply to scope the locking. Otherwise the boilerplate of return values gets in the way. There is one closure above that initializes 6 variables.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 736 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GrgPx0__QF3G4nr1W:-O4HNXRC8WNggyF7-NOu:bhj2keo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L736)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Can't users also run v1 turned on for regular traffic, even if not the default; forcing the pri here to be lowpri could conflict?
</blockquote></details>

Correct. But the v1=>v2 transition design makes the assumption that it is an insane setting.
I've added an error log here.

Since we have decoded the `RaftAdmissionMeta` here, one can use the original priority. But the `RangeController` cannot afford to decode the `RaftAdmissionMeta` and will deduct elastic eval and send tokens, so we should be consistent here.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4Gw5Lj4wGwqITTTr-V:-O4HbL3RBgEvL_QjX7d0:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L1)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider adding an init command that inits and prints the init state, the comment is helpful but seeing a formatted output similar to below may be clearer and more consistent.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4Gt9YWBL2N8xgalu39:-O4HPl9eB0624Fpe7_Mj:b-dnrdgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L90)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Why is this 107 and not 100 from:

```
entries=v1/i25/t45/pri0/time2/len100
```
</blockquote></details>

Because I could not get `createEntry` in the test to be precise. I had an existing code comment about it, but it is easy to miss. I've updated the logic there so it should more likely succeed (and it does for this testdata file).
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GtcXC4C0zvOzxqd7u:-O4HS6y2-lFQ8eyg3Prf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L148)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

rm )
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GuJtM6pBajUK2pgCZ:-O4HUU1n0wxwE6wLFHat:bnpy6ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L171)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Is `UnstableIndex > StableIndex` an artifact of the test or something that would happen on a real cluster?
</blockquote></details>

Good catch. It was a test artifact, but it also meant that some calls to `RangeControllerFactory` in this test were not using the right `nextRaftIndex`. Fixed.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4Gtb1Z1xY7GVjDukuy:-O4HUfqq98yp7z0RGsmG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L175)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

rm )
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GtZfb0YBA6nMi-2Su:-O4HUgfOEN3G9SZoHmFt:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L196)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

rm )
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 328 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GtsJV9VV4IQLwhLeW:-O4H_y8r30_7tE38J84a:bn99f4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L328)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: could we use the replica set formatting here instead?
</blockquote></details>

I gave it a try, but it is not a parsing friendly format, since it has multiple commas and simply using `strings.Split` is insufficient. So I've left this unchanged.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 396 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GvP-z6l326LaUJFdQ:-O4HUsWY9lsizOAZl8jJ:b-fh9p03) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L396)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Why 25? I don't see a replicaID w/ 25

```
(replicaSet=[(n1,s2):5,(n11,s11):11], leaseholder=10, nextRaftIndex=28)
```
</blockquote></details>

It is arbitrary. We are not checking consistency in `Processor`. The `RaftNode` implementation can discard it.

**Review by kvoli — APPROVED** [review]
:lgtm: excited to see this land!

> Reviewed 2 of 8 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-:-O4HdojP5LivzCGlr5gW:b45mv1t)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 452 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GNLSh1c4ddMMoFtEW:-O4HclrbEzfAwC9wR9ty:bgc99nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L452)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Those are long comments, that are likely to be updated. I've added the shorter boilerplate ones, that reference the interface.
</blockquote></details>

Ack, sounds reasonable.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 700 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4GnT2v0PiOdxXiwhNJ:-O4HcuDw0WQoJFaxbFC4:b-3wgt6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L700)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I find trivial closures like these have simpler code when mutating. One just reads them in a linear manner as the rest of the enclosing code and they exist simply to scope the locking. Otherwise the boilerplate of return values gets in the way. There is one closure above that initializes 6 variables.
</blockquote></details>

Ack, I meant the smaller # of return value closures. Lets keep it as is, I don't feel strongly about it.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor` line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128927#-O4Gt9YWBL2N8xgalu39:-O4HdIT38XWkxRzAkYnj:b-g9lzkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9ac4470473d2ec3addbd2589390a1047149e3ae/pkg/kv/kvserver/kvflowcontrol/replica_rac2/testdata/processor#L90)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Because I could not get `createEntry` in the test to be precise. I had an existing code comment about it, but it is easy to miss. I've updated the logic there so it should more likely succeed (and it does for this testdata file).
</blockquote></details>

I saw that comment and assumed it was related but thought I'd prod anyway :). Looks good.

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
