### PR TITLE
roachtest: Collect apt-get logs on jepsen failures

### LINKED ISSUE #30876: roachtest: jepsen/3/register/majority-ring failed
SHA: https://github.com/cockroachdb/cockroach/commits/0f5a289d49105cd317a2713b71546d84c25547f6

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=jepsen/3/register/majority-ring PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=937459&tab=buildLog

```
The test failed on master:
	test.go:500,cluster.go:890,jepsen.go:86,jepsen.go:125,jepsen.go:285: /home/agent/work/.go/bin/roachprod run teamcity-937459-jepsen-3:1-6 -- sh -c "sudo apt-get -qqy upgrade -o Dpkg::Options::='--force-confold' > /dev/null 2>&1" returned:
		stderr:
		
		stdout:
		.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
		   1: 
		exit status 100
		   2: 
		exit status 100
		   3: 
		exit status 100
		   4: 
		exit status 100
		   5: 
		exit status 100
		   6: 
		exit status 100
		Error:  exit status 100
		: exit status 1
	test.go:500,cluster.go:890,jepsen.go:74,asm_amd64.s:573,panic.go:377,test.go:501,cluster.go:890,jepsen.go:86,jepsen.go:125,jepsen.go:285: test already failed

```

### PR DESCRIPTION
**Pull request by bdarnell**
Closes #30876

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30899#-:-LNqYnRVBz6pzD6Kylcu:bg7igk9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/jepsen.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30899#-LNqYija4KLGWJoaq871:-LNqYija4KLGWJoaq872:b-n1d1ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0f1181f410b90baa3163bf9c1246fed29923051/pkg/cmd/roachtest/jepsen.go#L81)):*
> ```Go
> 	// probably either remove it or use a new base image with more of
> 	// these preinstalled.
> 	c.Run(ctx, c.All(), "sh", "-c", `"sudo apt-get -y update 2>&1 | sudo tee /var/log/apt-upgrade.log > /dev/null"`)
> ```

What's the point of the `tee` if you're just going to direct stdout to `/dev/null`? I'm probably just misunderstanding something here.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30899)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/jepsen.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30899#-LNqYija4KLGWJoaq871:-LNqZ54FARvPGIEakdzP:b-k5dpjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0f1181f410b90baa3163bf9c1246fed29923051/pkg/cmd/roachtest/jepsen.go#L81)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What's the point of the `tee` if you're just going to direct stdout to `/dev/null`? I'm probably just misunderstanding something here.
</blockquote></details>

Oh, is it the `sudo` that is important?

**Comment by benesch** [comment]
Yeah, you can't sudo a redirection.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30899)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/jepsen.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30899#-LNqYija4KLGWJoaq871:-LNqZHsgDgtlnPr7_f_J:b-9nuhmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0f1181f410b90baa3163bf9c1246fed29923051/pkg/cmd/roachtest/jepsen.go#L81)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Oh, is it the `sudo` that is important? 
</blockquote></details>

Yep, it's a standard trick to send stdout/stderr to a file as root (since we're running in a shell that's not root). We could rearrange things to run the entire shell as root instead of just `apt-get` and `tee`, but I figured I'd probably break quoting if I tried that.

**Pull request merged**
