### PR TITLE
statusccl: speed up unit tests by sharing test helper

### PR DESCRIPTION
**Pull request by Azhng**
# First Commit

Previously, running statusccl tests was very expensive. This was
because for each unit tests, the test helper set up a host cluster
and two tenant clusters. This resulted in total of 9 nodes being
created and destroyed.

This commit addresses this issue by having all unit tests sharing
a single test helper to avoid unnecessary setup and teardowns of
clusters.

Release note: None

---

# Second Commit 

statusccl: speedup unit test by reducing concurrency

Previously, we spin up 1 host cluster and 2 tenant clusters for testing
tenant status server. Each cluster contains 3 nodes and we effectively
spin up 9 nodes for the test. This is very expensive and can cause
errors like "race: limit on 8128 simultaneously alive goroutines is
exceeded, dying" due to the underyling LLVM limitation.

This commit reduces the total number of nodes that are spinned up.
Host cluster and the second tenant cluster size is now reduced to
1 node to reduce the cost of the tests. Additional special
`randomServerIdx` value is introduced to avoid having the test
rely on the hard-coded server index.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-:-MpvKbTH2GyEk8nBA5QL:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lindseyjin)

**Review by matthewtodd — APPROVED** [review]
:lgtm: :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-:-MpvkEmI3MmzFzvVhLvU:by6fmpn)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @lindseyjin)

**Comment by Azhng** [comment]
Seems like we are still running into issues due to high concurrency in `testrace` .

```
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
```

 I really don't want to skip the test under race so I added another commit to reduce the concurrency within the test helper.

PTAL! @RaduBerinde  @matthewtodd

**Comment by Azhng** [comment]
`testrace` on GCE worker now went down from ~600 seconds to 79 seconds.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-:-MpwFeqYADBMk9_Q-Pgq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @lindseyjin)

___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-MpwEr3V8NhnlpOtprc0:-MpwEr3V8NhnlpOtprc1:b-vse7nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a45925edfa8461b6d4892f83a10044d1de73f9ed/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L306)):*
> ```Go
> 			// Clears the SQL Stats at the end of each test via builtin.
> 			defer func() {
> 				testCluster.tenantConn(randomServerIdx).Exec(t, "SELECT crdb_internal.reset_sql_stats()")
> ```

[nit] When reading this code `randomServerIdx` sounds like an actual index that was chosen randomly somewhere above. Maybe rename to `randomServer`.
___
*[pkg/ccl/serverccl/statusccl/tenant_test_utils.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-MpwF5qU2YLRhOjcjV2U:-MpwF5qU2YLRhOjcjV2V:b-lw7za3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a45925edfa8461b6d4892f83a10044d1de73f9ed/pkg/ccl/serverccl/statusccl/tenant_test_utils.go#L112)):*
> ```Go
> 			t,
> 			server,
> 			1, // tenantClusterSize
> ```

We should to clean this up, o?
___
*[pkg/ccl/serverccl/statusccl/tenant_test_utils.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-MpwFQ5200SLOF5yfGWo:-MpwFQ5200SLOF5yfGWp:b-5z8x0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a45925edfa8461b6d4892f83a10044d1de73f9ed/pkg/ccl/serverccl/statusccl/tenant_test_utils.go#L166)):*
> ```Go
> }
> 
> func (c tenantCluster) tenantSQLStats(idx int) *persistedsqlstats.PersistedSQLStats {
> ```

[nit] We have all these methods where it's not clear that you can pass a special value. If it's not too much code to change, maybe make a separate type for the index (and the doc for that type can explain the special value).

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73363)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @lindseyjin and @RaduBerinde)

___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-MpwEr3V8NhnlpOtprc0:-MpwKZFI9bLKXju2p1yD:bn4p3a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a45925edfa8461b6d4892f83a10044d1de73f9ed/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L306)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] When reading this code `randomServerIdx` sounds like an actual index that was chosen randomly somewhere above. Maybe rename to `randomServer`.
</blockquote></details>

Renamed to `randomServer`
___
*[pkg/ccl/serverccl/statusccl/tenant_test_utils.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-MpwF5qU2YLRhOjcjV2U:-MpwK_vy1nv2Dn1BNx57:b-ownwyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a45925edfa8461b6d4892f83a10044d1de73f9ed/pkg/ccl/serverccl/statusccl/tenant_test_utils.go#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should to clean this up, o?
</blockquote></details>

This was meant to be an inline comment for the parameter name, I changed it to use `/* */` comment here instead. 
___
*[pkg/ccl/serverccl/statusccl/tenant_test_utils.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-MpwFQ5200SLOF5yfGWo:-MpwKydR0KeqtS5tT5ns:bcdwqez) ([raw file](https://github.com/cockroachdb/cockroach/blob/a45925edfa8461b6d4892f83a10044d1de73f9ed/pkg/ccl/serverccl/statusccl/tenant_test_utils.go#L166)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We have all these methods where it's not clear that you can pass a special value. If it's not too much code to change, maybe make a separate type for the index (and the doc for that type can explain the special value).
</blockquote></details>

Introduced a new `serverIdx` type.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73363#-:-MpwV-oC75ZC-ZZJ9K4b:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @lindseyjin)

**Comment by Azhng** [comment]
TFTR!

bors r=matthewtodd,RaduBerinde

**Comment by Azhng** [comment]
Hmm failed for unrelated tests :/ 


bors r=matthewtodd,RaduBerinde

**Comment by Azhng** [comment]
blathers backport 21.2

**Pull request merged**
