### PR TITLE
server,pgwire: define connection and session auth logs

### LINKED ISSUE #45028: Anonymized feature tracking for access logging
Please add anonymized usage tracking for our access logging functionality (#41378). This will help the Product team answer questions like “What % of clusters are tracking authentication events?” and improve feature usability and documentation.

Please add events for:
- [ ] conn logging  -> counters `auditing.connection.enabled` (when enabled) / `auditing.connection.disabled` (when not enabled)
- [ ] auth logging : -> counters `auditing.authentication.enabled` (when enabled) / `auditing.authentication.disabled` (when not enabled)

### LINKED ISSUE #45715: sql: implement an audit log for connections and authentication attempts
This is a feature ask by a paying customer.

The need is to provide an opt-in logger for SQL client connections (opening the SQL port), and another opt-in logger for SQL authentications (indicating which user logs in from where using which auth method and whether it is successful/rejected).

Note that this issue is specific to SQL client conns. Audit logging for other types of connections (UI, RPC etc) is covered by the separate issue #45716

### PR DESCRIPTION
**Pull request by knz**
Fixes #45715.
Fixes #45028.

Security feature: log connections and authenticated sessions to a
separate "authentication log".

This is articulated as follows:

- SQL client *connections* are loggable, subject to the
  cluster setting `server.auth_log.sql_connections.enabled`.

  When this type of logging is enabled, the following events are
  logged:

  - connection established;
  - connection terminated.

  Example log:
  ```
  I200219 05:02:18.147679 1036 sql/pgwire/server.go:445  [n1,client] 16 received connection
  I200219 05:02:18.155284 1036 sql/pgwire/server.go:453  [n1,client,local] 21 disconnected; duration: 7.612943ms

  I200219 05:08:43.083907 5235 sql/pgwire/server.go:445  [n1,client=[::1]:34588] 22 received connection
  I200219 05:08:44.171384 5235 sql/pgwire/server.go:453  [n1,client=[::1]:34588,hostssl] 26 disconnected; duration: 1.087489893s
  ```

- SQL client *authenticated sessions*  are loggable,
  subject to the cluster setting `server.auth_log.sql_sessions.enabled`.

  When this type of logging is enabled, the following events are
  logged:

  - authentication method selection;
  - authentication method application;
  - authentication method result;
  - session termination.

  Example auth success log (TLS cert over TCP):
  ```
  I200219 05:08:43.089501 5149 sql/pgwire/auth.go:327  [n1,client=[::1]:34588,hostssl,user=root] 23 connection matches HBA rule:
  # TYPE DATABASE USER ADDRESS METHOD        OPTIONS
  host   all      root all     cert-password
  I200219 05:08:43.091045 5149 sql/pgwire/auth.go:327  [n1,client=[::1]:34588,hostssl,user=root] 24 authentication succeeded
  I200219 05:08:44.169684 5235 sql/pgwire/conn.go:216  [n1,client=[::1]:34588,hostssl,user=root] 25 session terminated; duration: 1.080240961s
  ```

  Example auth fail log (password over unix socket):
  ```
  I200219 05:02:18.148961 1037 sql/pgwire/auth.go:327  [n1,client,local,user=root] 17 connection matches HBA rule:
  # TYPE DATABASE USER ADDRESS METHOD   OPTIONS
  local  all      all          password
  I200219 05:02:18.151644 1037 sql/pgwire/auth.go:327  [n1,client,local,user=root] 18 user has no password defined
  I200219 05:02:18.152863 1037 sql/pgwire/auth.go:327  [n1,client,local,user=root] 19 authentication failed: password authentication failed for user root
  I200219 05:02:18.154168 1036 sql/pgwire/conn.go:216  [n1,client,local,user=root] 20 session terminated; duration: 5.261538ms
  ```

- This new logging output is emitted to a separate log file
  `cockroach-auth.log` in the main log directory, alongside the main
  logs (directory subject to the regular `--log-dir` flag).

Additionally, the logging tags for SQL clients now also includes the
connection type: `local`, `hostssl` (TLS transport) and
`hostnossl` (no TLS). This change is applicable to all the logging
done on behalf of SQL clients on their gateway, not just the new auth
log.

Note: the difference between "connection" and "session" is that
"connection" events include also SQL-based liveness probe attempts,
which do not even try to negotiate a SQL session; as well as attempts
to use the PostgreSQL cancel protocol, which does not establish a SQL
session either (and is also, incidentally, currently not supported).

Deployments that need complete audit logging of client connections
including failed authentication attempts should probably enable both
types of logging.

Finally, as requested by PM, connections and authentication attempts
now cause increases to the following telemetry counters:
```
auditing.connection.enabled - inc on connections when audit enabled
auditing.connection.disabled - inc on connections when audit disabled
auditing.authentication.enabled - inc on auth when audit enabled
auditing.authentication.disabled - inc on auth when audit disabled
```

Release note (security update): CockroachDB now offers an experimental
facility to log client connections and authentication events to a
separate log file. See the commit message of this change for details.

### CODE REVIEW

**Comment by knz** [comment]
@BramGruneir @nstewart can you have a look at this?

I still need to add the auth logging for admin UI sessions (it's not done yet), but I'd like to get some preliminary feedback—preferably from the customer!—about the output format and whether any more/less details are needed. Thanks in advance.

**Comment by knz** [comment]
@tbg this is the PR I'd like some help reviewing. Thanks

**Comment by knz** [comment]
`testrace` is giving me a hard time and I'm not sure what to do about it. I thought my `atomic` call was sufficient?

**Review by tbg — APPROVED** [review]
:lgtm:

I would need more information to be able to help with testrace.

> Reviewed 14 of 14 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-:-M1fEURkDCt5XI2yl35C:b-kektnz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/server/server.go, line 787 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fB-517YNfVMR2MYNy:-M1fB-517YNfVMR2MYNz:b-qu23dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/server/server.go#L787)):*
> ```Go
> 		// crashing the server before it has a chance to write the last
> 		// few log lines to disk.
> 		// TODO(knz): We could worry about disk I/O activity incurred
> ```

Has this potential performance impact been brought up in the particular case that prompted this work? It doesn't seem that this logger would be too chatty in the common case, right?
___
*[pkg/sql/pgwire/auth.go, line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fBQQT3of70WzR3laa:-M1fBQQT3of70WzR3lab:b-4k4291) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/sql/pgwire/auth.go#L346)):*
> ```Go
> }
> 
> var logSessionAuth = settings.RegisterPublicBoolSetting(
> ```

Bottom of the file is an usual place for a cluster setting. Don't we usually put them near the top?
___
*[pkg/sql/pgwire/server.go, line 798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fCZ_AEN-1qKc5GQNz:-M1fCZ_AEN-1qKc5GQO-:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/sql/pgwire/server.go#L798)):*
> ```Go
> }
> 
> var logConnAuth = settings.RegisterPublicBoolSetting(
> ```

Ditto
___
*[pkg/sql/pgwire/hba/hba.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1f9PQg5BYvJacrWkYg:-M1f9PQg5BYvJacrWkYh:b-k7exod) ([raw file](https://github.com/cockroachdb/cockroach/blob/81556aefa69ae0a433df85e7dbf0685d7a013d25/pkg/sql/pgwire/hba/hba.go#L57)):*
> ```Go
> 	// This is used for auditing purposes.
> 	Input string
> 	// Generated is true if the entry was expanded from another.
> ```

I'm not sure what this means, so I wasn't able to confirm that the code behaves as intended. Is it true that `Generated` implies `Input == ""`? Is the converse true? (Then `Generated` could be a method)
___
*[pkg/sql/pgwire/hba/hba.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1f9vom29zKs4vXyAL9:-M1f9vom29zKs4vXyALA:b-mh94em) ([raw file](https://github.com/cockroachdb/cockroach/blob/81556aefa69ae0a433df85e7dbf0685d7a013d25/pkg/sql/pgwire/hba/hba.go#L370)):*
> ```Go
> 			entry.User[0].Value = tree.Name(iu.Value).Normalize()
> 			if userIdx > 0 {
> 				entry.Generated = true
> ```

Ah ok, so we carry the input through all of the generated ones as well.
___
*[pkg/sql/pgwire/hba/testdata/parse, line 630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fAf9y3EjBp5uJoLt1:-M1fAf9y3EjBp5uJoLt2:b-3lcerr) ([raw file](https://github.com/cockroachdb/cockroach/blob/81556aefa69ae0a433df85e7dbf0685d7a013d25/pkg/sql/pgwire/hba/testdata/parse#L630)):*
> ```
>         },
>     },
> }
> ```

Any testing where there are actually comments in the input file (bonus: one with trailing spaces)?
___
*[pkg/sql/pgwire/testdata/auth/conn_log, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fCzhx5_oIf3HGNLfi:-M1fCzhx5_oIf3HGNLfj:b-9nu4rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/sql/pgwire/testdata/auth/conn_log#L46)):*
> ```
> ----
> I: [n1,client=XXX] 4 received connection
> I: [n1,client=XXX,hostssl,user=root] 5 connection matches HBA rule: host  all root all cert-password # CockroachDB mandatory rule
> ```

so this used a cert and no password, right? Is it ok that we can't distinguish it from the password-authed case?
___
*[pkg/testutils/soon.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fEIMn1yQomkj5xDnS:-M1fEIMn1yQomkj5xDnT:beyvmvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/testutils/soon.go#L49)):*
> ```Go
> }
> 
> // SucceedsSoonErrorWithMaxDuration is like SucceedsSoonError but the
> ```

Just my 2c, but there's a reason there's a 45s delay in SucceedsSoon and I would've just used that, especially since your test is blocked on i/o.

**Review by knz — COMMENTED** [review]
> I would need more information to be able to help with testrace.

Never mind, found it. It was trivial.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-:-M1kt6xN4ROE_6Jt3EYy:b-usn99b)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/server/server.go, line 787 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fB-517YNfVMR2MYNy:-M1kndojEf6ExSKzNADd:bkcu1r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/server/server.go#L787)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Has this potential performance impact been brought up in the particular case that prompted this work? It doesn't seem that this logger would be too chatty in the common case, right?
</blockquote></details>

Added a comment to clarify I was thinking about DoS.
___
*[pkg/sql/pgwire/auth.go, line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fBQQT3of70WzR3laa:-M1knuCQ3qK-dYX58EtG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/sql/pgwire/auth.go#L346)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Bottom of the file is an usual place for a cluster setting. Don't we usually put them near the top?
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fCZ_AEN-1qKc5GQNz:-M1knv1TD2KapJvzfH5j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/sql/pgwire/server.go#L798)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/hba/hba.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1f9PQg5BYvJacrWkYg:-M1ko4if7YAm0-Nvxn0p:b-cr06uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/81556aefa69ae0a433df85e7dbf0685d7a013d25/pkg/sql/pgwire/hba/hba.go#L57)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm not sure what this means, so I wasn't able to confirm that the code behaves as intended. Is it true that `Generated` implies `Input == ""`? Is the converse true? (Then `Generated` could be a method)
</blockquote></details>

They are separate fields.
___
*[pkg/sql/pgwire/hba/hba.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1f9vom29zKs4vXyAL9:-M1ko6qP-eN9qBS_loDK:b-3cslek) ([raw file](https://github.com/cockroachdb/cockroach/blob/81556aefa69ae0a433df85e7dbf0685d7a013d25/pkg/sql/pgwire/hba/hba.go#L370)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ah ok, so we carry the input through all of the generated ones as well.
</blockquote></details>

indeed.
___
*[pkg/sql/pgwire/hba/testdata/parse, line 630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fAf9y3EjBp5uJoLt1:-M1ko85C8FsDIKI9RJs9:bpzvnru) ([raw file](https://github.com/cockroachdb/cockroach/blob/81556aefa69ae0a433df85e7dbf0685d7a013d25/pkg/sql/pgwire/hba/testdata/parse#L630)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Any testing where there are actually comments in the input file (bonus: one with trailing spaces)?
</blockquote></details>

Done (in `scan` not parse).
___
*[pkg/sql/pgwire/testdata/auth/conn_log, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fCzhx5_oIf3HGNLfi:-M1kqppi4CiyI1VrTrrE:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/sql/pgwire/testdata/auth/conn_log#L46)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

so this used a cert and no password, right? Is it ok that we can't distinguish it from the password-authed case?
</blockquote></details>

Good idea. Done.
___
*[pkg/testutils/soon.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45193#-M1fEIMn1yQomkj5xDnS:-M1kp1MABQbbjpX33ljJ:b8bd14y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a255502d77e6430f731a05a505dbedb773f84bdb/pkg/testutils/soon.go#L49)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Just my 2c, but there's a reason there's a 45s delay in SucceedsSoon and I would've just used that, especially since your test is blocked on i/o.
</blockquote></details>

Ok no prob, reverted.

**Pull request merged**
