### PR TITLE
release-22.2: pkg/util/metric: optionally reintroduce legacy hdrhistogram model

### PR DESCRIPTION
**Pull request by abarganier**
This patch reeintroduces the old HdrHistogram model to optionally be
enabled in favor of the new Prometheus model, gated behind
an environment variable called `COCKROACH_ENABLE_HDR_HISTOGRAMS`,
allowing users a means to "fall back" to the old model in the
event that the new model does not adequately serve their needs
(think of this as an "insurance policy" to protect against
this from happening again with no real mitigation - ideally,
this environment variable should never have to be used).

It also updates the pre-defined bucket boundaries used by the Prometheus
backed histograms with more buckets. This aims to improve precision,
especially for latency histograms, when calculating quantiles (the low precision
being the core cause of the issue at hand).

Note: some histograms were introduced *after* the new
Prometheus histograms were added to CockroachDB. In this
case, we use the `ForceUsePrometheus` option in the
`HistogramOptions` struct to ignore the value of the env
var, since there never was a time where these specific
histograms used the HdrHistogram model.

Release note (ops change): Histogram metrics can now optionally
use the legacy HdrHistogram model by setting the environment var
`COCKROACH_ENABLE_HDR_HISTOGRAMS=true` on CockroachDB nodes.
**Note that this is not recommended** unless users are having
difficulties with the newer Prometheus-backed histogram model.
Enabling can cause performance issues with timeseries databases
like Prometheus, as processing and storing the increased number
of buckets is taxing on both CPU and storage. Note that the
HdrHistogram model is slated for full deprecation in upcoming
releases.

Fixes: https://github.com/cockroachdb/cockroach/issues/95833

Backport 2/2 commits from #96029.

/cc @cockroachdb/release

Release justification: Fixes for high-priority or high-severity bugs in existing functionality

### CODE REVIEW

**Comment by dhartunian** [comment]
@abarganier looks like you're missing some test files for `AggMetrics`.

**Review by dhartunian — APPROVED** [review]
do we need `release-22.2-` prefix in the PR title?

> Reviewed 34 of 38 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96514#-:-NNNOYP077cIR3RZ_N7a:b-y0xn0i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Comment by abarganier** [comment]
TFTR!

> do we need release-22.2- prefix in the PR title?

I see the PR title as `release-22.2: pkg/util/metric: optionally reintroduce legacy hdrhistogram model` 🤔

**Review by dhartunian — COMMENTED** [review]
Sorry I posted with an old comment that was out of date, whoops.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96514#-:-NNbrk8E7pWkyYZisdH0:b-3gitxq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Comment by abarganier** [comment]
TFTR!

**Pull request merged**
