### PR TITLE
kv: eliminate heap allocations throughout Raft messaging and processing logic

### PR DESCRIPTION
**Pull request by nvb**
This PR contains a few improvements within the Raft messaging and processing code to avoid common heap allocations that stuck out during tests in #56860. This will improve the general efficiency of the Raft pipeline and will specifically reduce the cost of handling large coalesced heartbeats. This will reduce the impact that these heartbeats have on the [scheduler latency](https://github.com/cockroachdb/cockroach/pull/56943) of other active ranges.

### CODE REVIEW

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57007)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/store_raft.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57007#-MMqNmPI1WkJguKQcCvp:-MMqNmPI1WkJguKQcCvq:bxwhhi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a7bd2ded02f6ebc04692906f2921bd0cbe71b9/pkg/kv/kvserver/store_raft.go#L282)):*
> ```Go
> 		ctx context.Context, r *Replica,
> 	) (pErr *roachpb.Error) {
> 		ctx = r.AnnotateCtx(ctx)
> ```

Why aren't we using `raftSchedulerCtx` here?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57007)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/store_raft.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57007#-MMqNmPI1WkJguKQcCvp:-MMqe9SUDtYwL-DEyX06:bd657ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a7bd2ded02f6ebc04692906f2921bd0cbe71b9/pkg/kv/kvserver/store_raft.go#L282)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Why aren't we using `raftSchedulerCtx` here?
</blockquote></details>

`processRaftSnapshotRequest` is not called from the Raft scheduler, it's called from `Store.receiveSnapshot` with the RPC's stream's context.

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57007#-:-MMqfTWfEjeepK1STpAl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/store_raft.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57007#-MMqNmPI1WkJguKQcCvp:-MMqfS9EBbft8yr8FOb5:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a7bd2ded02f6ebc04692906f2921bd0cbe71b9/pkg/kv/kvserver/store_raft.go#L282)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`processRaftSnapshotRequest` is not called from the Raft scheduler, it's called from `Store.receiveSnapshot` with the RPC's stream's context.
</blockquote></details>

:+1:

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
