### PR TITLE
ui: add disk ops per second graph to hardware dashboard

### LINKED ISSUE #28552: ui: iops does not match iostat
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

using Rand to perform 100% upsert, 3 nodes, 

`roachprod run $f -- 'PATH=~/:$PATH; rand --batch 10 test factors'`

- Which version of CockroachDB are you using?

roachprod run $f -- 'wget -qO- https://binaries.cockroachdb.com/cockroach-v2.1.0-alpha.20180730.linux-amd64.tgz | tar  xvz; cp cockroach-v2.1.0-alpha.20180730.linux-amd64/cockroach ./'

- What did you do?

- What did you expect to see?

```
$ iostat -x 5
Linux 4.10.0-35-generic (robert-vungle-0001) 	08/13/2018 	_x86_64_	(4 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          41.02    0.02    3.65    3.63    0.00   51.68

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     6.95    1.21    2.49    38.19   222.45   140.90     0.02    5.66    1.06    7.89   0.52   0.19
sdb               0.00  1289.61    0.05 1272.74     0.89 77700.41   122.10     0.30    0.24    0.17    0.24   0.17  22.24

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          86.25    0.00    6.70    3.32    0.00    3.73

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.20     0.00     1.60    16.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00  1875.40    0.00 1995.20     0.00 114416.80   114.69     1.29    0.64    0.00    0.64   0.21  42.56

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          79.07    0.00    7.16    7.97    0.00    5.80

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     2.00    0.00    4.00     0.00    24.00    12.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00  2447.20    0.00 2679.40     0.00 47460.00    35.43     0.61    0.23    0.00    0.23   0.18  47.76
```
- What did you see instead?

screen shot 2018-08-13 at 7 02 08 pm

- What was the impact?

IOPS on the hardware table is misleading

### PR DESCRIPTION
**Pull request by vilterp**
The middle two graphs are new:
image

Fixes #28552

### CODE REVIEW

**Comment by vilterp** [comment]
Note: this dashboard is getting pretty big; good use case for something like http://html2canvas.hertzen.com/documentation/, or a layout which can show more TS at once (e.g. @josueeee's grid design)

**Comment by robert-s-lee** [comment]
Disk read and write per second look good.  Per our hall way conversation the iops in progress is avg queue size from iostat.  Relabeling to match commonly used vocabulary would lessen the customers questions on how to interpret the metric.

**Comment by vilterp** [comment]
Yeah, would be good to be consistent with `iostat`. I was trying to be faithful to the description in the [`/proc/diskstat` docs](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats), which is where we're getting the metric: "I/Os currently in progress". Need to make sure that that's actually the same as "avg queue size" before relabeling; will probably do that in a separate PR.

**Comment by vilterp** [comment]
@robert-s-lee do you think these read & write time graphs are important, or should I remove them as I add the read and write ops?

image

**Comment by vilterp** [comment]
K, I will leave them in.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28594#-:-LK3VDL_999gtpEVzjGp:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by vilterp** [comment]
TFTR!

bors r+

**Comment by couchand** [comment]
is the IOPS in Progress chart adding value here?


> good use case for something like http://html2canvas.hertzen.com/documentation/

meh.  Print-to-pdf works fine and comes standard in Chrome.

**Comment by BramGruneir** [comment]
>> good use case for something like http://html2canvas.hertzen.com/documentation

> meh. Print-to-pdf works fine and comes standard in Chrome.

But not in FF.

**Pull request merged**
