### PR TITLE
build: add --fail-on-race to go2xunit cmdline

### PR DESCRIPTION
**Pull request by bdarnell**
This gives us better failure output for data races.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4265)

### CODE REVIEW

**Comment by tamird** [comment]
Wow, this was always available? LGTM. Can we remove some of the excerpt shenanigans now?

**Comment by bdarnell** [comment]
Yeah, looks like it's been there since 2014 (but not documented on the readme, only in `--help`). 

We could remove the `excerpt.txt` logic, but we'd need to replace it with something that parsed the XML. (and we currently make an effort to run even without a place to put the XML files).

**Comment by tamird** [comment]
I'm not sure what you mean; doesn't Circle CI parse the XML? How could we have somewhere to put excerpt.txt without having somewhere to put the XML?

Or are you saying that `except.txt` is useful as human-readable text? that hasn't been my experience.

**Comment by bdarnell** [comment]
We use excerpt.txt as the body of our auto-generated github issues. It's not very good, but I think it's better than nothing but a link to the circleci build. This is where we'd need to parse the xml.

**Pull request merged**
