### PR TITLE
testserver: Modify GetHTTPClient to GetUnauthenticatedHTTPClient, GetAdminAuthenticatedHTTPClient to GetAdminHTTPClient

### LINKED ISSUE #76241: testserver: rename GetHTTPClient to GetUnauthenticatedHTTPClient
Suggested by @dhartunian 

the problem to solve is that it's currently just too easy to create a test for a HTTP API without authentication, which does not invite the implementer to care about authn (nor authorization).

We can nudge this in the right direction by renaming the "simple" method to a longer name with a discouragement in the comment; then renaming the admin method to a "simple" name so that it's easier to find.

Jira issue: CRDB-13044

### PR DESCRIPTION
**Pull request by changhanlee**
fixes #76241.
See commit message.

Release justification: Low impact, rename refactoring of testserver methods

### CODE REVIEW

**Review by knz — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77732)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)

**Comment by knz** [comment]
This change is good. Thank you!

**Comment by changhanlee** [comment]
TFYR

**Comment by otan** [comment]
looks like there are conflicts - can you resolve them?

**Comment by changhanlee** [comment]
Yep, will do.

**Comment by changhanlee** [comment]
@otan I fixed the merge conflict but now the TeamCity build fails. I looked through the build output logs multiple times but cannot understand the issue. I'd appreciate help in understanding the problem.

Also, when handling merge conflicts after approval, is it standard to rebase afterwards (as I have done here)?

**Comment by otan** [comment]
i see

```
[05:00:51][Run unit tests] pkg/ccl/serverccl/statusccl/tenant_test_utils.go:173:27: too many arguments in call to c.tenantHTTPClient
[05:00:51][Run unit tests] 	have (*testing.T, serverIdx, bool)
[05:00:51][Run unit tests] 	want (*testing.T, serverIdx)
[05:00:51][Run unit tests] pkg/ccl/serverccl/statusccl/tenant_status_test.go:889:50: too many arguments in call to helper.testCluster().tenantHTTPClient
[05:00:51][Run unit tests] 	have (*testing.T, number, bool)
[05:00:51][Run unit tests] 	want (*testing.T, serverIdx)
[05:00:51][Run unit tests] pkg/ccl/serverccl/statusccl/tenant_status_test.go:1022:50: too many arguments in call to helper.testCluster().tenantHTTPClient
[05:00:51][Run unit tests] 	have (*testing.T, number, bool)
[05:00:51][Run unit tests] 	want (*testing.T, serverIdx)
[05:00:51][Run unit tests] compilepkg: error running subcommand external/go_sdk/pkg/tool/linux_amd64/compile: exit status 2
[05:00:51][Run unit tests] INFO: Elapsed time: 1083.721s, Critical Path: 693.45s
[05:00:51][Run unit tests] INFO: 6711 processes: 733 internal, 5978 processwrapper-sandbox.
```

when clicking Build Log

> Also, when handling merge conflicts after approval, is it standard to rebase afterwards (as I have done here)?

yep!

**Comment by knz** [comment]
thank you for the change again. When the CI is happy with this, we can merge this

**Pull request merged**
