### PR TITLE
raft: pull out a ElectionTracker 

### LINKED ISSUE #125265: raft: refactor ProgressTracker to support leader leases
**Describe the problem**
Part of https://github.com/cockroachdb/cockroach/issues/123847

Today, the `ProgressTracker` holds a raft groups `Config` and is responsible for tracking both votes and progress for the raft group. We want to add a third type of tracking, that of fortification support, to support leader leases (see https://github.com/cockroachdb/cockroach/issues/125264). To achieve this, we want to:

- Pull `Config` a level higher and not have the `ProgressTracker` create/embed it.
- Pass a pointer to the `Config` to the `ProgressTracker`
- Pull out vote tracking into a new struct, say `VoteTracker`

Jira issue: CRDB-39356

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
First 5 commits are from https://github.com/cockroachdb/cockroach/pull/127312.

Previously, the ProgressTracker was responsible for tracking votes and
progress. This patch pulls out a new struct, a VoteTracker, to track
votes instead.

Closes https://github.com/cockroachdb/cockroach/issues/125265

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127526)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/tracker/votetracker.go` line 18 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-O2BZeY-BpLrpAq4jHfN:-O2BZeY-BpLrpAq4jHfO:bcjq5np) ([raw file](https://github.com/cockroachdb/cockroach/blob/655375ead2eb6e40936bb3e579503c6ece7d66e8/pkg/raft/tracker/votetracker.go#L18)):*
> ```Go
> )
> 
> // VoteTracker is used to track votes from the currently active configuration
> ```

The term "vote" can mean different things in Raft. It can mean voting on an election or it can mean voting for a log append. Consider renaming this to `ElectionTracker` so that it is clear that this is only used for leader election.

(the `votes` map within is fine)
___
*[`pkg/raft/tracker/votetracker.go` line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-O2B_7Q726VOjtMaWAjz:-O2B_7Q726VOjtMaWAk-:b-mdhp67) ([raw file](https://github.com/cockroachdb/cockroach/blob/655375ead2eb6e40936bb3e579503c6ece7d66e8/pkg/raft/tracker/votetracker.go#L45)):*
> ```Go
> // election outcome is known.
> func (v *VoteTracker) TallyVotes(
> 	progress ProgressMap,
> ```

See our discussion in Slack about how it would be good to not need this argument.

**Review by arulajmani — COMMENTED** [review]
@nvanbenschoten I pulled out r3 to avoid conflicts with https://github.com/cockroachdb/cockroach/pull/127619. RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-:-O2QdMsRAv_Pa9VvPste:b-4zqy5f)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/tracker/votetracker.go` line 18 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-O2BZeY-BpLrpAq4jHfN:-O2QOMg2B_ZtqXDLK94p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/655375ead2eb6e40936bb3e579503c6ece7d66e8/pkg/raft/tracker/votetracker.go#L18)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The term "vote" can mean different things in Raft. It can mean voting on an election or it can mean voting for a log append. Consider renaming this to `ElectionTracker` so that it is clear that this is only used for leader election.

(the `votes` map within is fine)
</blockquote></details>

Done.
___
*[`pkg/raft/tracker/votetracker.go` line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-O2B_7Q726VOjtMaWAjz:-O2QczAT51rnid-Emd5u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/655375ead2eb6e40936bb3e579503c6ece7d66e8/pkg/raft/tracker/votetracker.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

See our discussion in Slack about how it would be good to not need this argument.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 24 files at r9, 19 of 19 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-:-O2RGao35ijIASDQi4fz:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/tracker/electiontracker.go` line 65 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-O2RGF2L-rd5LGObT6DB:-O2RGF2L-rd5LGObT6DC:b-dutcpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b1db46136b0d1e4f984327a549b1ab625a928f2/pkg/raft/tracker/electiontracker.go#L65)):*
> ```Go
> // ResetVotes prepares for a new round of vote counting via recordVote.
> func (e *ElectionTracker) ResetVotes() {
> 	e.votes = map[pb.PeerID]bool{}
> ```

We can use the new (as of Go 1.21) `clear(e.votes)` here to avoid the re-allocation.

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-:-O2_0oN2AhomehkNQG-I:b-l0r5kv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/tracker/electiontracker.go` line 65 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/127526#-O2RGF2L-rd5LGObT6DB:-O2_0kdt-9m1BkcLdEPF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b1db46136b0d1e4f984327a549b1ab625a928f2/pkg/raft/tracker/electiontracker.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can use the new (as of Go 1.21) `clear(e.votes)` here to avoid the re-allocation.
</blockquote></details>

Done.

**Pull request merged**
