### PR TITLE
opt: support INSERT ON CONFLICT with unique partial indexes

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: add basic tests for unique partial indexes

This commit adds tests for INSERT, UPDATE, and DELETE operations on
tables with unique partial indexes.

Release note: None

#### opt: support INSERT ON CONFLICT DO NOTHING and unique partial indexes

This commit adds support for `INSERT ON CONFLICT DO NOTHING` statements
on tables with unique partial indexes. In order to support the correct
behavior, there are three primary changes to the expression tree built
by `optbuilder`.

  1. Existing rows that are not in the unique partial index cannot
  conflict with insert rows. Therefore, the Scans that search for
  existing, conflicting rows are wrapped in Selects with the partial
  index predicate as a filter.

  2. Insert rows that do not satisfy the partial index predicate cannot
  conflict with existing rows in the unique partial index. Therefore,
  the left outer join ON filter now includes the partial index
  predicate.

  3. Insert rows that do not satisfy the partial index predicate cannot
  conflict with other insert rows in the same `INSERT` and they should
  not be de-duplicated. Therefore, we project a new column that allows
  the UpsertDistinctOn expression to de-duplicate only the rows that
  satisfy the partial index predicate.

Future work includes handling `INSERT ON CONFLICT (column)` and
`INSERT ON CONFLICT DO UPDATE`.

Informs #52603

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Well this came out really nice and clean!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52954#-:-MEzrU82C02gkRV5xN5d:b-h6lswk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/insert.go, line 810 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52954#-MEzr-TS7NEW-vdLrFJs:-MEzr-TT5NyMLzAwXN8S:b21bl8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2786c0b9abfc576e2205f882835890df85994c2/pkg/sql/opt/optbuilder/insert.go#L810)):*
> ```Go
> 		// and NULL otherwise. This column is added to the set of conflictCols.
> 		// The UpsertDistinctOn operator will treat all NULL values as unique,
> 		// preventing those rows from being de-duplicated.
> ```

Very cool use of OR, makes things more self-documenting!

[nit] It would be nice to explicitly mention the projected expression in this example: `(b > 0)  OR NULL` (and maybe show the resulting value for the sample rows in the query)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52954)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/insert.go, line 810 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52954#-MEzr-TS7NEW-vdLrFJs:-MF-JKN89-DHad4e-FPh:b8u7od7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2786c0b9abfc576e2205f882835890df85994c2/pkg/sql/opt/optbuilder/insert.go#L810)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Very cool use of OR, makes things more self-documenting!

[nit] It would be nice to explicitly mention the projected expression in this example: `(b > 0)  OR NULL` (and maybe show the resulting value for the sample rows in the query)
</blockquote></details>

Ya it turned out nice. The OR was @andy-kimball's idea.

I've added the examples to the comment, LMK if that's what you had in mind.

**Comment by mgartner** [comment]
bors r=RaduBerinde

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/insert.go, line 810 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52954#-MEzr-TS7NEW-vdLrFJs:-MF1zUhTAVyxjYLBwMRc:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2786c0b9abfc576e2205f882835890df85994c2/pkg/sql/opt/optbuilder/insert.go#L810)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ya it turned out nice. The OR was @andy-kimball's idea.

I've added the examples to the comment, LMK if that's what you had in mind.
</blockquote></details>

:100:

**Pull request merged**
