### PR TITLE
server: another step toward KV and SQL ID separation

### LINKED ISSUE #84602: server: enforce SQL Instance ID = KV node ID for in-memory tenants [CRDB-14537 followup]
When running in-process, we'd like the SQL servers to have the same SQL instance ID as the KV node ID, so that distsql planning can continue equating the two.

(NB: we might be able to obviate this idea once distsql planning uses localities properly)

Jira issue: CRDB-17759

Epic CRDB-23559

### PR DESCRIPTION
**Pull request by stevendanna**
See individual commits for details. In short, we:

- Now store the KV Node ID and SQL Instance ID in two slots
- Tell shared-process tenant sql servers about their parent server's KV Node ID.

Fixes #84602

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Maybe mark this PR as fixing 84602?

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96645#-:-NNbgxG943ae8Q6lxr7m:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by aadityasondhi — APPROVED** [review]
:lgtm: thanks, this  is helpful

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96645#-:-NNhqbHW159027XlAdh3:b-yhj3ay)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by dt** [comment]
Is this still blocked on anything?

**Comment by stevendanna** [comment]
@dt I merged half of it as part of https://github.com/cockroachdb/cockroach/pull/96857.  I need to rebase this and see what is left.

**Review by knz — APPROVED** [review]
still LGTM

> Reviewed 3 of 4 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96645#-:-NOud7vk4u6jh9ok9y6k:bh5f435)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @stevendanna)

___
*[`pkg/server/server_sql.go` line 546 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/96645#-NOud-cS6zxVUdiJexzJ:-NOud-cS6zxVUdiJexzK:bmjpyad) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d104319be54cd1148c2d6ba7a5e731ac21b3a1c/pkg/server/server_sql.go#L546)):*
> ```Go
> 		codec, cfg.clock, cfg.stopper)
> 
> 	// We can't use the nodeDailer as the podNodeDailer unless we
> ```

nit: nodeDialer, podDialer

**Comment by dt** [comment]
> merged half of it as part of #96857.

Yeah, it's the other half I want 😛

**Comment by dt** [comment]
I'm also happy to pick up the rebase here if that'd be helpful

**Pull request closed without merging**
