### PR TITLE
sql: support COMMENT ON CONSTRAINT

### LINKED ISSUE #65563: Add support for "COMMENT ON CONSTRAINT" from Postgres
Add support for "COMMENT ON CONSTRAINT"

For example:
```
root@:26257/defaultdb> CREATE TABLE t1 ( id int primary key, constraint gtzero check (id > 0) );
CREATE TABLE

Time: 130ms total (execution 130ms / network 0ms)

root@:26257/defaultdb> COMMENT ON CONSTRAINT gtzero 'whoa!!';
invalid syntax: statement ignored: at or near "constraint": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
COMMENT ON CONSTRAINT gtzero 'whoa!!'
           ^

```

This works in Postgres

### PR DESCRIPTION
**Pull request by e-mbrown**
Fixes: #65563

This change adds support for CONSTRAINT comments.

Release note (sql change): This change adds ability to comment
on SQL table constraints using PostgreSQL's COMMENT ON CONSTRAINT syntax.

Added support for a cli shortcut that displays constraint
information similar to PostgreSQL.
The change to SHOW CONSTRAINTS delegate makes it so
that constraint comments are included and the results
are more detailed.

Release note (cli change): Adds shortcut for SHOW CONSTRAINT

Release note (sql change): Adds comment column to results of SHOW CONSTRAINT.
This removes the need to query seperately for constraint comments
in pg_constraints or system.comments

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @e-mbrown, and @rafiss)

___
*[pkg/sql/comment_on_constraint.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibqkRx4bHpNtSqUAgV:-MibqkRy4Eiqr0UT8Fts:b-ovpyea) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint.go#L78)):*
> ```Go
> 	hasher := makeOidHasher()
> 	switch kind := constraint.Kind; kind {
> 	case "PRIMARY KEY":
> ```

I would create constants for these
___
*[pkg/sql/comment_on_constraint.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibrZa3Cq68-r4vYO0l:-MibrZa3Cq68-r4vYO0m:bofypig) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint.go#L108)):*
> ```Go
> 		}
> 	} else {
> 		_, err := params.p.extendedEvalCtx.ExecCfg.InternalExecutor.ExecEx(
> ```

I would add a comment to make it clear that setting a comment to NULL is equivalent to deleting it.
___
*[pkg/sql/comment_on_constraint.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-Mibr1-ECrqvAaUhAvMF:-Mibr1-ECrqvAaUhAvMG:bo1sur2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint.go#L113)):*
> ```Go
> 			params.p.Txn(),
> 			sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> 			"DELETE FROM system.comments WHERE type=$1 AND object_id=$2 AND sub_id=$0",
> ```

Should this be `sub_id=0` and not `sub_id=$0`?
___
*[pkg/sql/comment_on_constraint_test.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibrQuj0IALKyERnwCB:-MibrQuj0IALKyERnwCC:b-3rf34g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint_test.go#L31)):*
> ```Go
> 	}
> 
> 	testCases := []struct {
> ```

Should add a test case for removing the comment
___
*[pkg/sql/comment_on_constraint_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibrFhUEhTQma2WyDYx:-MibrFhUEhTQma2WyDYy:b-6imhuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint_test.go#L36)):*
> ```Go
> 		expect gosql.NullString
> 	}{
> 		//SEPT 1 EOD:MAKING FOREIGN KEY CONSTRAINT AND UNIQUE CONSTRAINT TEST!
> ```

I think you left this comment over

**Comment by e-mbrown** [comment]
___
*[pkg/sql/comment_on_constraint.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibqkRx4bHpNtSqUAgV:-Mibzd0PCjhzqYsGZOEd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint.go#L78)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I would create constants for these
</blockquote></details>

Done.

**Comment by e-mbrown** [comment]
___
*[pkg/sql/comment_on_constraint.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-Mibr1-ECrqvAaUhAvMF:-Mibzsci5szDGZOmjO4b:b-p4e227) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint.go#L113)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Should this be `sub_id=0` and not `sub_id=$0`?
</blockquote></details>

Yup, changed

**Comment by e-mbrown** [comment]
___
*[pkg/sql/comment_on_constraint_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibrFhUEhTQma2WyDYx:-MibzzgPC4qeVN8WFW6-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint_test.go#L36)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think you left this comment over
</blockquote></details>

Done.

**Comment by e-mbrown** [comment]
___
*[pkg/sql/comment_on_constraint.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibrZa3Cq68-r4vYO0l:-Mic1LfY1E8XLNwcUddN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint.go#L108)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I would add a comment to make it clear that setting a comment to NULL is equivalent to deleting it.
</blockquote></details>

Done.

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @RichardJCai)

___
*[pkg/sql/comment_on_constraint_test.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-MibrQuj0IALKyERnwCB:-MicJiV69aiuSC0BSnmi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3ce386ecc1bfb62d7387cb6a63e42964381aac/pkg/sql/comment_on_constraint_test.go#L31)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Should add a test case for removing the comment
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @e-mbrown, and @RichardJCai)

___
*[-- commits, line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-Mk9OQ0W1dsTP9Fq4pa-):*
nit: take a look at the guidelines for release notes: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#How-to-write-release-note-texts

in this case, we'd want to describe how a user would use this feature, so the release note should say that the shortcut is `\dd ...`. also, if the release notes cover everything, then there's no need for the earlier info in the commit message. so this could be:

```
Release note (cli change): Added support for a cli shortcut that displays constraint
information similar to PostgreSQL. The shortcut is `\dd TABLE`.

Release note (sql change): Added a `WITH COMMENT` clause to the `SHOW CONSTRAINT`
statement that causes constraint comments to be displayed,
```

then no need for the rest of the commit message. (well you still need the title, but not the rest.)
___
*[pkg/cli/clisqlshell/sql.go, line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-Mk9PK1A-F9o2vB_rcXa:-Mk9PK1A-F9o2vB_rcXb:b2q9l42) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf8874d325948c18efd95afd0b8d7655ba44baaa/pkg/cli/clisqlshell/sql.go#L79)):*
> ```Go
>   \du               list the users for all databases.
>   \d [TABLE]        show details about columns in the specified table, or alias for '\dt' if no table is specified.
> 	\dd TABLE					show details about constraints on the specified table.
> ```

nit: make the spacing line up. it's important because this is shown directly in help text.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @e-mbrown, and @RichardJCai)

___
*[pkg/cli/clisqlshell/sql.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-Mkgxies3j8hZg1GV6aY:-Mkgxiet31WOCCAVHAHa:b-w6hd9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2968c77aa92addb1f3e00711790532d1908811f4/pkg/cli/clisqlshell/sql.go#L79)):*
> ```Go
>   \du               list the users for all databases.
>   \d [TABLE]        show details about columns in the specified table, or alias for '\dt' if no table is specified.
>   \dd TABLE					show details about constraints on the specified table.
> ```

nit: in between the word `TABLE` and `show`, make sure to use spaces and not tabs

**Review by rafiss — APPROVED** [review]
lgtm! well done

> Reviewed 5 of 19 files at r1, 10 of 14 files at r3, 10 of 11 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69783#-:-MkhoxUT7MRsea6yT8Iw:bd6ul8c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @e-mbrown, and @RichardJCai)

**Comment by e-mbrown** [comment]
bors r=rafiss,RichardJCai

**Pull request merged**
