### PR TITLE
roachtest: make splits/largerange more aggressive

### PR DESCRIPTION
**Pull request by nvb**
This commit addresses a TODO by extending the splits/largerange roachtest to run
on a 6 node cluster. This extension means that the test will begin performing
rebalancing once splits begin, which should stress the behavior of streaming
snapshots. If we were to ever hold one of these snapshots in-memory in its
entirety, the test would have a bad time.

Release justification: testing only

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Here are some pretty cool graphs of this roachtest in action around the point where we let the single 32GB range start splitting and rebalancing:

Screen Shot 2021-02-24 at 12 38 02 AM
Screen Shot 2021-02-24 at 12 38 08 AM

**Review by irfansharif — APPROVED** [review]
That Avg. QPS graph looks surprising, do you know why that happens? Does all the sudden splits processing starve out CPU that aggressively?

**Comment by nvanbenschoten** [comment]
I think the test just cuts all load once the dataset is loaded in and waits for splitting. The test doesn't currently wait for rebalancing to complete, though. I'm going to add that.

**Pull request merged**
