### PR TITLE
cdc: Add Txn/S verification to ledger test

### PR DESCRIPTION
**Pull request by mrtracy**
Adds verification that a certain level of transactions per second is
maintained during the CDC ledger workload roachtest. This is done by
querying time series after the workload has concluded.

The average transactions-per-second level for the entire workload
timeperiod is verified; in addition, the txn/s rate for each individual
one minute period of the test is inspected, and we only allow a certain
percentage of such periods to fall below the target.

Release note: None

### CODE REVIEW

**Comment by mrtracy** [comment]
This is not *quite* ready to merge, but I don't expect any of the code to change other than the per-minute validation criteria; I may have to relax it by dropping the first-and-last minute and the percentage a bit.

**Review by danhhz — COMMENTED** [review]
:lgtm_strong: 

This is SUPER COOL. I'm definitely going to use this to dump a csv of interesting timeseries when one of these roachtests fails

throw out last minute because it's a partial datapoint? makes sense. as for first minute, i think our usual tpcc ramp period is more like 5 minutes, so there's precedent for throwing out more than just the first one if we need to

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32303#-:-LRHoMc82FouLO38SPeo:blmzocz)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by mrtracy** [comment]
This actually passed without any relaxation, but to be on the safe side of flakes, I'm dropping the first two minutes. Result:

```
01:08:23 cdc.go:803: average txns per second: 870.196290
01:08:23 cdc.go:820: spent 0.000000% of time below target of 575.000000 txn/s
```

**Comment by mrtracy** [comment]
bors r=danhhz

**Pull request merged**
