### PR TITLE
opt: make distinct value calculation lazy 

### PR DESCRIPTION
**Pull request by rytaft**
This commit changes the model of statistics calculation so
that column statistis are only calculated when needed to
estimate the row cardinality of the current expression or a
parent expression. Previously, all column statistics were
calculated for every expression in the memo. Now, column
statistics are calculated lazily and only when needed.

This commit also improves the estimation for selectivity of
a filter. The selectivity of the filter is calculated as the
product of the selectivities of the conjuncts in the filter.
For example, the selectivity of `<pred1> AND <pred2>` is
`selectivity(pred1) * selectivity(pred2)`. The selectivity for
each conjunct is calculated in one of three ways:

1. If the predicate can be converted to a tight constraint set,
    we calculate the selectivity directly from the constraint set.

2. If only part of the predicate can be converted to a constraint set
    (i.e., it's not tight), the selectivity is calculated as:
    min(selectivity from constraint set, 1/3).

3. If we can't convert the predicate to a constraint set, the predicate
    is too complex to easily determine the selectivity, so we use 1/3.

### CODE REVIEW

**Comment by rytaft** [comment]
Based on an offline discussion with @andy-kimball, I've added a new commit which renames `memo/Statistics` to `memo/statisticsBuilder` and makes `memo/statisticsBuilder` structs ephemeral. Please take a look - thanks!

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LAtmkrE5YAJQNPDm2EY:b-i9qicd)*

**Comment by RaduBerinde** [comment]
So we are always computing RowCount but we only compute column stats as needed. Pretty cool!

There's something funky going on with the first commit.

It would have been useful to separate the lazy conversion from the selectivity improvements into commits (just mentioning it for the future, not even sure how feasible that would have been in this case).

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/statistics.go, line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAx234b82MfwCojmkiO:-LAx234b82MfwCojmkiP:bcwhk0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/statistics.go#L21)):*
> ```Go
> // for tables and indexes and are exposed to the optimizer via opt.Catalog
> // interfaces. As logical properties are derived bottom-up for each
> // expression, statistics are derived for each relational expression, based
> ```

this needs updating (some mention of the fact that we do it lazily)

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 113 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAx4OveEh0aydpOPd8d:-LAx4OveEh0aydpOPd8e:bwe41jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/memo/logical_props_factory.go#L113)):*
> ```Go
> 
> 	f.sb.init(&props.Relational.Stats, ev, f.evalCtx)
> 	f.sb.initScan(def)
> ```

This pattern looks strange now with the two `init`s. Maybe rename `initXXX` to `buildXXX`?

---

*[pkg/sql/opt/memo/testdata/stats/join, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAnzqsB0USvIDMIdOcP:-LAnzqsB0USvIDMIdOcQ:b-hzlu2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af4ffd05b8501fbd332fca8883842d73e3272e3/pkg/sql/opt/memo/testdata/stats/join#L71)):*
> ```
> inner-join
>  ├── columns: x:1(int!null) y:2(int) s:3(string) d:4(decimal!null) x:5(int) z:6(int!null) rowid:7(int!null)
>  ├── stats: [rows=4000000]
> ```

I wonder if we should have a test flag which causes us to calculate all possible stats. It was useful to be able to see everything it could calculate.

---

*[pkg/sql/opt/memo/statistics.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAoNw27Bdd_iu6CDsJ5:-LAoNw27Bdd_iu6CDsJ6:b8rw0fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af4ffd05b8501fbd332fca8883842d73e3272e3/pkg/sql/opt/memo/statistics.go#L296)):*
> ```Go
> 		if inputStat, ok := inputStats.singleColStat(col); ok {
> 			if inputStat.DistinctCount != 0 {
> 				selectivity *= float64(colStat.DistinctCount) / float64(inputStat.DistinctCount)
> ```

The old code had `distinctCount = min(distinctCount, colStat.DistinctCount)`. I think we should have a check for that condition here too. This is related to the comment for `updateDistinctCountsFromConstraint` (the last paragraph).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LAniWqK3NV9B1-WGchH:b4vmjfo)*

**Comment by rytaft** [comment]
TFTR!

> So we are always computing RowCount but we only compute column stats as needed. Pretty cool!

Yep - thanks!

> There's something funky going on with the first commit.

Yea -- that was the commit from my previous PR, and I must have screwed up the rebase somehow. Do you know if there is an easy way to fix it? That PR is already merged into master... 

> It would have been useful to separate the lazy conversion from the selectivity improvements into commits (just mentioning it for the future, not even sure how feasible that would have been in this case).

Yea, sorry I realize this was probably pretty painful to review :frowning:. I started working on the selectivity stuff and then realized that I needed the column stats on-demand for that to work... I'll try to not do this again!

---

Review status: 0 of 40 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/statistics.go, line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAx234b82MfwCojmkiO:-LAy1K8y0S1RuLQUUaAD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/statistics.go#L21)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this needs updating (some mention of the fact that we do it lazily)
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 113 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAx4OveEh0aydpOPd8d:-LAy1SHc6WnkWd85yOl6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/memo/logical_props_factory.go#L113)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This pattern looks strange now with the two `init`s. Maybe rename `initXXX` to `buildXXX`?
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/testdata/stats/join, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAnzqsB0USvIDMIdOcP:-LAy1sCK6qbNLSpcf-C_:b-7bmvu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af4ffd05b8501fbd332fca8883842d73e3272e3/pkg/sql/opt/memo/testdata/stats/join#L71)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I wonder if we should have a test flag which causes us to calculate all possible stats. It was useful to be able to see everything it could calculate.
</blockquote></details>

So how would that flag work? Every expression should just request all the column stats available from its input in addition to any derived stats?

---

*[pkg/sql/opt/memo/statistics.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAoNw27Bdd_iu6CDsJ5:-LAy1VH03rCLvcbizR-W:b-vvlry1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af4ffd05b8501fbd332fca8883842d73e3272e3/pkg/sql/opt/memo/statistics.go#L296)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The old code had `distinctCount = min(distinctCount, colStat.DistinctCount)`. I think we should have a check for that condition here too. This is related to the comment for `updateDistinctCountsFromConstraint` (the last paragraph).
</blockquote></details>

Good catch! I added a check for `colStat.DistinctCount < inputStat.DistinctCount`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LAy-uhlDOy4qAo79V16:b6a53p3)*

**Comment by andy-kimball** [comment]
Review status: 0 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/metadata.go, line 19 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAxQCBRBgZoRsdHJ9AH:-LAxQCBRBgZoRsdHJ9AI:bl2o7oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/metadata.go#L19)):*
> ```Go
> import (
> 	"fmt"
> ```

NIT: eliminate extra space here.

---

*[pkg/sql/opt/metadata.go, line 218 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAxQVEeADh4WKi1F_dr:-LAxQVEeADh4WKi1F_ds:bni2xfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/metadata.go#L218)):*
> ```Go
> 
> 					if _, ok := mdTab.statistics.ColStats[key]; !ok {
> 						mdTab.statistics.ColStats[key] = &ColumnStatistic{Cols: cols, DistinctCount: stat.DistinctCount()}
> ```

NIT: over 100-char limit here and below, causing wrapping in side-by-side diff.

---

*[pkg/sql/opt/testutils/alter_table.go, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy83Oi9iD-bV8bw7j6:-LAy83Oi9iD-bV8bw7j7:b-3go0g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/testutils/alter_table.go#L20)):*
> ```Go
> 	gojson "encoding/json"
> 	"fmt"
> ```

NIT: extra space

---

*[pkg/sql/opt/memo/statistics_builder.go, line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAxdpne9HiQV6jhhVGt:-LAxdpne9HiQV6jhhVGu:b-kgo7sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/memo/statistics_builder.go#L75)):*
> ```Go
> // as it gets passed up the expression tree. If the statistic cannot be
> // determined from the children, colStat returns ok=false.
> func (sb *statisticsBuilder) colStat(colSet opt.ColSet) (_ *opt.ColumnStatistic, ok bool) {
> ```

I think this (and the other methods) should always succeed. We can always derive stats for a col (or multi-col) stat. Even if we have no stats, we can go with estimates. In future, we can indicate the estimated error in other field(s) on the returned stat struct.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 680 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy41Mz6tmIL4IwegSU:-LAy41Mz6tmIL4IwegSV:bkk96aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2376a7888238afd43bf191ca3cdefac623029d49/pkg/sql/opt/memo/statistics_builder.go#L680)):*
> ```Go
> 			distinctRows = colStat.DistinctCount
> 		} else {
> 			groupingColSet.ForEach(func(i int) {
> ```

This is good example of where not returning errors from the `colStat` methods would be nicer/cleaner. This code would just reduce to `colStat = sb.copyColStat(&inputStatsBuilder, groupingColSet)`, and it'd be up to the underlying code to give back best estimate for those columns, even in case where we don't have stats on exactly those cols. The code lower down will then memoize results so that if the same/similar sets are requested, it can draw from its cache.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 920 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy6L_k6V-u9npn1eKZ:-LAy6L_k6V-u9npn1eK_:b-ec9xl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2376a7888238afd43bf191ca3cdefac623029d49/pkg/sql/opt/memo/statistics_builder.go#L920)):*
> ```Go
> 		hardLimit := *limit.Private().(*tree.DInt)
> 		if hardLimit > 0 {
> 			colStat.DistinctCount = min(uint64(hardLimit), colStat.DistinctCount)
> ```

Perhaps better would be to scale the `DistinctCount`:
```
LimitDistinct = LimitRowCount * (InputDistinct / InputRowCount)
```

---

*[pkg/sql/opt/memo/statistics_builder.go, line 949 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy73876aGHiSbf_8Ag:-LAy73876aGHiSbf_8Ah:b-c1hzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2376a7888238afd43bf191ca3cdefac623029d49/pkg/sql/opt/memo/statistics_builder.go#L949)):*
> ```Go
> 	}
> 
> 	colStat.DistinctCount = min(sb.s.RowCount, colStat.DistinctCount)
> ```

Same as above comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981)*

**Comment by RaduBerinde** [comment]
You should be able to `git rebase --onto origin/master HEAD^^` to get rid of it

---

Review status: 0 of 40 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/memo/testdata/stats/join, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAnzqsB0USvIDMIdOcP:-LAy7Z5Q1Oql-zjTV_3l:b-vxd7ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af4ffd05b8501fbd332fca8883842d73e3272e3/pkg/sql/opt/memo/testdata/stats/join#L71)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

So how would that flag work? Every expression should just request all the column stats available from its input in addition to any derived stats?
</blockquote></details>

Hm, good question. That would work if it's not too difficult/invasive. One semi-decent option is to request all single column stats from the top-level expression. Or maybe the flag could have as value a list of column sets to ask stats for from the top-level expr.

I'm just wondering how we will be able to test a specific stat calculation without having to figure out how to craft an artificial query that results in it being calculated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LAy7BJt-inutXxw96YS:bmbxtvu)*

**Comment by andy-kimball** [comment]
Review status: 0 of 40 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/testdata/stats/join, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAnzqsB0USvIDMIdOcP:-LAy91o97ORQhn6o45_L:b5pzve) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af4ffd05b8501fbd332fca8883842d73e3272e3/pkg/sql/opt/memo/testdata/stats/join#L71)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, good question. That would work if it's not too difficult/invasive. One semi-decent option is to request all single column stats from the top-level expression. Or maybe the flag could have as value a list of column sets to ask stats for from the top-level expr.

I'm just wondering how we will be able to test a specific stat calculation without having to figure out how to craft an artificial query that results in it being calculated.
</blockquote></details>

perhaps the flag could cause these stats to be created at each expr:
1. single-col stats on all output cols
2. col stats (single or multi) on all weak keys for that expr

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981)*

**Comment by rytaft** [comment]
> You should be able to git rebase --onto origin/master HEAD^^ to get rid of it

That worked - thanks! Magic...

I've added a new commit to always return an estimate for the column stats, per @andy-kimball's suggestion below. I think it's definitely an improvement in the flow of the code, and in several cases it produces better overall cardinality estimates. PTAL.

---

Review status: 0 of 42 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/metadata.go, line 19 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAxQCBRBgZoRsdHJ9AH:-LB3HCb41-zvWWtsiXqn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/metadata.go#L19)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: eliminate extra space here.
</blockquote></details>

Done.

---

*[pkg/sql/opt/metadata.go, line 218 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAxQVEeADh4WKi1F_dr:-LB3HEXS-HmyihF1BIfx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/metadata.go#L218)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: over 100-char limit here and below, causing wrapping in side-by-side diff.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/testdata/stats/join, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAnzqsB0USvIDMIdOcP:-LB3Hp5QC7tvx1WpTIoQ:b-xadmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af4ffd05b8501fbd332fca8883842d73e3272e3/pkg/sql/opt/memo/testdata/stats/join#L71)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

perhaps the flag could cause these stats to be created at each expr:
1. single-col stats on all output cols
2. col stats (single or multi) on all weak keys for that expr
</blockquote></details>

After thinking about this and discussing with @andy-kimball offline, I think this should wait for another PR. It's definitely not a trivial change, and we should make sure it's really necessary before devoting the time. I agree it would be useful, but it doesn't seem essential for this PR.

---

*[pkg/sql/opt/testutils/alter_table.go, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy83Oi9iD-bV8bw7j6:-LB3IIgM33gwu6rSLAnX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/testutils/alter_table.go#L20)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: extra space
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAxdpne9HiQV6jhhVGt:-LB3HJKp2i0ABrJ8jbfZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a141a25b7fef79771619b592802328bd102626/pkg/sql/opt/memo/statistics_builder.go#L75)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think this (and the other methods) should always succeed. We can always derive stats for a col (or multi-col) stat. Even if we have no stats, we can go with estimates. In future, we can indicate the estimated error in other field(s) on the returned stat struct.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 680 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy41Mz6tmIL4IwegSU:-LB3HVfY4fSrdkNm8lrZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2376a7888238afd43bf191ca3cdefac623029d49/pkg/sql/opt/memo/statistics_builder.go#L680)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This is good example of where not returning errors from the `colStat` methods would be nicer/cleaner. This code would just reduce to `colStat = sb.copyColStat(&inputStatsBuilder, groupingColSet)`, and it'd be up to the underlying code to give back best estimate for those columns, even in case where we don't have stats on exactly those cols. The code lower down will then memoize results so that if the same/similar sets are requested, it can draw from its cache.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 920 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy6L_k6V-u9npn1eKZ:-LB3HXz-66Zv81OVwpPx:b-w2xp4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2376a7888238afd43bf191ca3cdefac623029d49/pkg/sql/opt/memo/statistics_builder.go#L920)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Perhaps better would be to scale the `DistinctCount`:
```
LimitDistinct = LimitRowCount * (InputDistinct / InputRowCount)
```
</blockquote></details>

Done. I used the selectivity logic that we're already using to scale distinct counts for Select and Scan operators.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 949 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LAy73876aGHiSbf_8Ag:-LB3HmuD0zzC4YQZ32t5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2376a7888238afd43bf191ca3cdefac623029d49/pkg/sql/opt/memo/statistics_builder.go#L949)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Same as above comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LB3H8Jb3SN-aTNOK4VK:bgwl8d6)*

**Comment by andy-kimball** [comment]
Review status: 0 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 116 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB79L3ODXD6TQt8d43t:-LB79L3ODXD6TQt8d43u:b-t8ny1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L116)):*
> ```Go
> func (sb *statisticsBuilder) colStatFromChildren(colSet opt.ColSet) *opt.ColumnStatistic {
> 	switch sb.ev.Operator() {
> 	case opt.UnknownOp:
> ```

How come this isn't a panic?

---

*[pkg/sql/opt/memo/statistics_builder.go, line 640 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB7B8T41VZbVGI6mWkc:-LB7B8T41VZbVGI6mWkd:b-2xe1kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L640)):*
> ```Go
> 		for i, col := range outputCols {
> 			if synthesizedCols.Contains(int(col)) {
> 				inputCols.UnionWith(sb.ev.Child(1).Child(i).Logical().Scalar.OuterCols)
> ```

But what if an outer column comes from a higher scope rather than being an input column? It would seem this code assumes every outer column of a synthesized column must be an input column, which isn't the case when subqueries are involved.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981)*

**Comment by rytaft** [comment]
Review status: 0 of 42 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 116 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB79L3ODXD6TQt8d43t:-LBBO58GCchCDDfybuqZ:b-ypw0eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L116)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come this isn't a panic?
</blockquote></details>

`buildScan` and `colStatScan` don't set the `ev` field in the `inputStatsBuilder`, since there is technically no input to the scan operator. If `colStatFromChildren` is called on the `inputStatsBuilder`, it needs to fall back on the metadata, which is why I call `colStatMetadata` here. But I agree it's a little weird to expect `UnknownOp` -- can you think of a better way to handle this? 

---

*[pkg/sql/opt/memo/statistics_builder.go, line 640 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB7B8T41VZbVGI6mWkc:-LBBPT2b9_hcxhZkoYH4:b2lfos3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L640)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

But what if an outer column comes from a higher scope rather than being an input column? It would seem this code assumes every outer column of a synthesized column must be an input column, which isn't the case when subqueries are involved.
</blockquote></details>

Good point. I updated the logic and added a test case in `memo/testdata/stats/project`. We probably want to handle this differently in the future, so I added a TODO below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 42 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 116 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB79L3ODXD6TQt8d43t:-LBBk97J6WMQ_wjpCSHQ:b-hcfxl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L116)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

`buildScan` and `colStatScan` don't set the `ev` field in the `inputStatsBuilder`, since there is technically no input to the scan operator. If `colStatFromChildren` is called on the `inputStatsBuilder`, it needs to fall back on the metadata, which is why I call `colStatMetadata` here. But I agree it's a little weird to expect `UnknownOp` -- can you think of a better way to handle this? 
</blockquote></details>

I think just add a comment here.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 640 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB7B8T41VZbVGI6mWkc:-LBBkPXI7E8QsIBQVF3b:b-4u4qx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L640)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Good point. I updated the logic and added a test case in `memo/testdata/stats/project`. We probably want to handle this differently in the future, so I added a TODO below.
</blockquote></details>

In future we should compute constant columns for an expression. This includes both columns like `SELECT 1`, but also columns that contain outer references, since those are effectively constant at the lower scope. The stats for constant columns would be distinct=1. 

---

*[pkg/sql/opt/memo/statistics_builder.go, line 627 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LBBmqvd4cjTj53vjQzB:-LBBmqvd4cjTj53vjQzC:bncaagf) ([raw file](https://github.com/cockroachdb/cockroach/blob/93ae4272b9444768634777e27bda6d82c1ba15e3/pkg/sql/opt/memo/statistics_builder.go#L627)):*
> ```Go
> 
> func (sb *statisticsBuilder) colStatProject(colSet opt.ColSet) *opt.ColumnStatistic {
> 	// Columns may be passed through from the input or a higher scope, or they
> ```

This is not quite true. An outer column should never be "passed through". We're currently (incorrectly) doing this in optbuilder, but that's a bug that needs to be fixed. Outer columns should always be aliased to another ColumnID when they're projected. Otherwise, we can end up joining two relations that both contain columns with the same id, which is not good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LBBosbn2b2d0IXFnNET:bnfp4nl)*

**Comment by andy-kimball** [comment]
A ton of good work here. Looks like you're just about over the finish line.

---

Review status: 0 of 42 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LBBovrw3qMy4K2ZcJ7l:bycky0f)*

**Comment by rytaft** [comment]
TFTRs! Updated a few comments.

---

Review status: 0 of 42 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 116 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB79L3ODXD6TQt8d43t:-LBNkEdh4qBZ4vtIwjXU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L116)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think just add a comment here.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 640 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LB7B8T41VZbVGI6mWkc:-LBNjzz6C7mgvuqRB4FB:b-ukdpbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6718572dc3bf085478ec712fcfcc95ef096126e4/pkg/sql/opt/memo/statistics_builder.go#L640)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In future we should compute constant columns for an expression. This includes both columns like `SELECT 1`, but also columns that contain outer references, since those are effectively constant at the lower scope. The stats for constant columns would be distinct=1. 
</blockquote></details>

Ah! In that case I think this code is already doing the right thing. Updated the comment.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 627 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-LBBmqvd4cjTj53vjQzB:-LBNkAkv2NCsjYOgRveX:b-dwiyr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/93ae4272b9444768634777e27bda6d82c1ba15e3/pkg/sql/opt/memo/statistics_builder.go#L627)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This is not quite true. An outer column should never be "passed through". We're currently (incorrectly) doing this in optbuilder, but that's a bug that needs to be fixed. Outer columns should always be aliased to another ColumnID when they're projected. Otherwise, we can end up joining two relations that both contain columns with the same id, which is not good.
</blockquote></details>

Fixed the comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LBNkHtfBsXm-DH7lrX6:ba9mci9)*

**Comment by rytaft** [comment]
bors r+

---

Review status: 0 of 42 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24981#-:-LBNl3REAGu0H28WJOMX:b-ydi9ay)*

**Pull request merged**
