### PR TITLE
sql: newly created databases have public schemas with descriptors

### PR DESCRIPTION
**Pull request by RichardJCai**
There are multiple commits in this PR.

Notably, the first commit changes new databases to be created with public schemas that have descriptors. Resolution logic was added was added to handle special cases for the public schema.

Additionally, ALTER DATABASE CONVERT TO SCHEMA is being disabled on the new version (unable to handle regular schemas) and ALTER TABLE RENAME TO can no longer move tables between schemas. We can revisit adding this back and supporting the cases that were previously supported - they would work if the database only had a public schema for convert to schema and if rename would work if tables were being moved between databases but only in the public schema.

There is a fair amount of bulkio work to be done as well but that makes the PR even larger and there are some special cases to still handle there and figure out.

New public schemas will have descriptors. Schema resolution logic
had to be updated to take into account public schemas are now effectively
the same as UDS.

On cluster version PublicSchemaWithDescriptors and above, newly created
databases will have public schemas with descriptors. We use this
version to determine if the public schema is backed by a descriptor or not.
In the future, we will also use PublicSchemaWithDescriptors to kick off the
public schema migration.

Logic was added to handle schema resolution in the mixed version state.

Release justification: None, waiting for 22.1
Release note: None

Moving a table from one database's public schema to another was
previously possible using ALTER TABLE RENAME due to the public
schema being a special case, now that the public schema is a
regular user defined schema with a descriptor, this is no
longer the case.

Release note (sql change): Previously, ALTER TABLE ... RENAME TO ...
would allow the user to move the table from a database to another
if the table is being moved within one database's public schema
to another. This is now disallowed.

sql: disallow alter database convert to schema on versions with explicit public schemas

Release note (sql change): ALTER DATABASE CONVERT TO SCHEMA is now disabled on
versions 22.1+.

### CODE REVIEW

**Comment by RichardJCai** [comment]
cc @ajwerner @cockroachdb/sql-schema @cockroachdb/sql-experience 

This PR is probably ready for some review cycles, most of the SQL tests should be passing. Open to suggestions for writing more tests here.

Ignore the bulkio (backup/restore/import) stuff for now - still have some details to iron out there but don't want to make this PR even bigger then it already is.

**Comment by postamar** [comment]
I will review this tomorrow, looking forward to it. Thanks for doing this, Richard!

**Review by postamar — DISMISSED** [review]
There's definitely a lot here. This seems like a good first step. As a general comment I'm a bit concerned with the abundance of TODOs here. A lot of these pertain to the usage of `keys.PublicSchemaID` and I wonder if they're necessary. It seems to me that when we'll remove that constant we'll naturally also remove its usages, so the TODO is really only necessary on the constant definition itself.

Full disclosure: I didn't review the tests yet. My brain is fried right now. I will be doing another pass over the whole thing again next week.

> Reviewed 68 of 68 files at r1, 1 of 1 files at r2, 3 of 4 files at r3, 21 of 107 files at r6, 103 of 105 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-:-MjpGWvJ-rjg2PbuPhZl:b65h3q7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @RichardJCai)

___
*[pkg/sql/descriptor.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-Mjp4uQ3AMB7laBXgc2U:-Mjp4uQ3AMB7laBXgc2V:b-b7zzxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/descriptor.go#L68)):*
> ```Go
> // createDatabase implements the DatabaseDescEditor interface.
> func (p *planner) createDatabase(
> 	ctx context.Context, database *tree.CreateDatabase, jobDesc string, version clusterversion.Handle,
> ```

Why are you passing `version` in here when you can already get it with `p.execCfg.Settings.Version`?
___
*[pkg/sql/descriptor.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-Mjp5OtR2jif4AObSqJf:-Mjp5OtR2jif4AObSqJg:bb7izuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/descriptor.go#L190)):*
> ```Go
> 
> 	// Every database must be initialized with the public schema.
> 	key := catalogkeys.MakePublicSchemaNameKey(p.ExecCfg().Codec, dbID)
> ```

Would it be possible to get rid of `catalogkeys.MakePublicSchemaNameKey` and any other function in there that treats the `public` schema in a special way? There aren't many usages anyway. Perhaps not in this PR. Just a comment in passing.
___
*[pkg/sql/drop_schema.go, line 92 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-MjpEU1E8RfTzlgV4bfv:-MjpEU1E8RfTzlgV4bfw:bf8fsop) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfcf52ad1f95819f9afc9300d73eecc06a19680f/pkg/sql/drop_schema.go#L92)):*
> ```Go
> 		if sc.GetName() == tree.PublicSchema {
> 			return nil, pgerror.Newf(pgcode.InvalidSchemaName, "cannot drop schema %q", scName)
> 		}
> ```

Doesn't this case fall under `case catalog.SchemaPublic` below?
___
*[pkg/sql/information_schema.go, line 2098 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-Mjp6Ktv4Kz1SRbQIF8w:-Mjp6Ktv4Kz1SRbQIF8x:b-ftpjn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/information_schema.go#L2098)):*
> ```Go
> 			// public schema will continue to use keys.PublicSchemaID (29).
> 			if id == keys.PublicSchemaID {
> 				schemas = append(schemas, schemadesc.GetPublicSchema())
> ```

Wouldn't we want to get rid of `schemadesc.GetPublicSchema()` altogether? or at least in the meantime limit its usage? It seems like it should be marked as deprecated.
___
*[pkg/sql/reparent_database.go, line 123 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-MjpFbdU2S0YCKu7-DTL:-MjpFbdU2S0YCKu7-DTM:b-rhahvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfcf52ad1f95819f9afc9300d73eecc06a19680f/pkg/sql/reparent_database.go#L123)):*
> ```Go
> 	for i, u := range privs.Users {
> 		// Remove privileges that are valid for databases but not for schemas.
> 		privs.Users[i].Privileges = u.Privileges & schemaPrivs
> ```

It appears you're changing the database's privileges and then cloning those to use as the schema's. Is this intentional? It doesn't seem like it. This is perhaps good motivation to add a `SetPrivileges` method to `catalog.MutableDescriptor`. In fact wouldn't it be better if `GetPrivileges` returned an interface instead of `*descpb.Privileges`? The potential for mistakes is quite high.
___
*[pkg/sql/resolver.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-Mjp7phRA9wgKDfHL5AE:-Mjp7phRA9wgKDfHL5AF:bkv3f8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/resolver.go#L194)):*
> ```Go
> 			if dbDesc.HasPublicSchemaWithDescriptor() {
> 				publicSchemaID := dbDesc.GetSchemaID(tree.PublicSchema)
> 				return true, prefix, typedesc.MakeSimpleAlias(alias, publicSchemaID), nil
> ```

Have you considered putting the public schema ID in the database descriptor's `Schemas` mapping in all cases? In other words, even when it's `29`? This way you can do away with this if-block. This would require changing the implementation of `HasPublicSchemaWithDescriptor` and all other places where you rely on checking the absence of a `"public"` key in this mapping but it feels like you could replace that check with `Schemas["public"].ID == 29` instead, if that makes sense.
___
*[pkg/sql/resolver.go, line 1144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-Mjp99Dy9mUlG-07ojES:-Mjp99Dy9mUlG-07ojET:bly8ejf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/resolver.go#L1144)):*
> ```Go
> 	// Public schema is also a regular UDS but always adding this entry is still
> 	// okay.
> 	schemaNames[keys.PublicSchemaID] = tree.PublicSchema
> ```

This seems dangerous!
___
*[pkg/sql/resolver.go, line 1194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-Mjp70CS6kIM8LFXEGvO:-Mjp70CS6kIM8LFXEGvP:blvs28h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/resolver.go#L1194)):*
> ```Go
> 		fallback:    fallback,
> 		ctx:         ctx,
> 		version:     version,
> ```

Are these used anywhere at all? I can't find any usages. It's also weird to pass `ctx` around as a struct field.
___
*[pkg/sql/catalog/dbdesc/database_desc_builder.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-Mjp9mhIEW979pprOERx:-Mjp9mhIEW979pprOERy:bkdbgxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/catalog/dbdesc/database_desc_builder.go#L152)):*
> ```Go
> 	name string,
> 	owner security.SQLUsername,
> 	publicSchemaID descpb.ID,
> ```

I would much prefer you created a companion to `NewInitial` called `NewInitialWithPublicSchema` which allows you to pass an ID and leave `NewInitial` as it is. All these zero arguments feel like a code smell.
___
*[pkg/sql/catalog/descs/descriptor.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-MjpAAXA-PrLchN2tpxO:-MjpAAXA-PrLchN2tpxP:b-w7sm45) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/catalog/descs/descriptor.go#L163)):*
> ```Go
> 	name string,
> 	avoidCached, mutable bool,
> 	version clusterversion.Handle,
> ```

Similar to another comment: is passing `version` here at all necessary? It appears that it can be obtained from `tc`. 
___
*[pkg/sql/catalog/descs/descriptor.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-MjpAQIg2JRAB9cCfxWr:-MjpAQIg2JRAB9cCfxWs:bx8qclc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de13a79e75c2ba097d22a9868eb7316ba4ceb3b/pkg/sql/catalog/descs/descriptor.go#L289)):*
> ```Go
> 			err = nil
> 		}
> 		if sc != nil {
> ```

Isn't this redundant?
___
*[pkg/sql/testdata/telemetry/error, line 35 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70221#-MjpE-zd6VaUtvEZ-Ezg:-MjpE-zeE2FpnquBt3xy:buro9ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfcf52ad1f95819f9afc9300d73eecc06a19680f/pkg/sql/testdata/telemetry/error#L35)):*
> ```
> GRANT node TO root;
> UPDATE system.descriptor
>   SET descriptor=crdb_internal.json_to_pb('cockroach.sql.sqlbase.Descriptor', '  {"type": {"arrayTypeId": 57, "enumMembers": [{"logicalRepresentation": "hello", "physicalRepresentation": "QA=="}, {"logicalRepresentation": "hi", "physicalRepresentation": "gA=="}], "id": 56, "modificationTime": {}, "parentId": 50, "parentSchemaId": 29, "privileges": {"ownerProto": "root", "users": [{"privileges": 2, "userProto": "admin"}, {"privileges": 512, "userProto": "public"}, {"privileges": 2, "userProto": "root"}], "version": 1}, "version": "1"}}')
> ```

Thanks for doing this. These hex dumps were bad.

**Review by ajwerner — COMMENTED** [review]
Want to fix up your rebase issues? I'll check it out and play with it after you do.

**Review by RichardJCai — COMMENTED** [review]
@ajwerner 
Updated, do you want me to rebase again onto master? I'd rather deal with the conflicts for logic tests / generated files at the end if possible.

**Comment by RichardJCai** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/72000

**Pull request closed without merging**
