### PR TITLE
sql: verify index before declaring it public

### PR DESCRIPTION
**Pull request by vivekmenezes**
A new index verification step is added after an index backfill
to verify that the index is indeed valid. This is good practice,
but also necessary with the introduction of the new bulk index
backfill which doesn't have the capability to detect duplicate
index entries.

related to #12424

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I'll add a test and also verify the performance of this verification step.

**Comment by vivekmenezes** [comment]
```
I190126 04:37:08.859821 51968 sql/backfill.go:542  [n1,client=71.125.15.117:58313,user=root,scExec] index order/order_o_entry_d_o_w_id_o_d_id_o_carrier_id_o_id_key row count = 30211493/30211493, took 2m59.614708966s/1m46.906444836s
```

**Comment by vivekmenezes** [comment]
This is ready for another look. Much much better!

I think we can do a better job of the threading model used for validation so it can be reused elsewhere. Perhaps that should be done later in the context of lucy's change.

@lucy-zhang FYI

**Comment by vivekmenezes** [comment]
@dt this is ready for review. Thanks!

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vivekmenezes)

___
*[pkg/sql/backfill.go, line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34263#-LXa3995-ZA9jeIL2YfB:-LXa3995-ZA9jeIL2YfC:bxxt3gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8fcf688bcb683fb891ee0cbd9caf8ad4c6833f4/pkg/sql/backfill.go#L516)):*
> ```Go
> 
> 			numIndexChecks++
> 			go func() {
> ```

I think we might want a ctx that we can cancel as soon as one of these fails so we don't wait for wasted work. 
Actually, this looks like it might be a good use for ctxgroup?
___
*[pkg/sql/backfill.go, line 598 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34263#-LXa4sGgCfKZyt5UTHzO:-LXa4sGgCfKZyt5UTHzP:be0dybb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8fcf688bcb683fb891ee0cbd9caf8ad4c6833f4/pkg/sql/backfill.go#L598)):*
> ```Go
> 			}
> 			for i := 0; i < numIndexChecks; i++ {
> 				index := <-notify
> ```

I'm a little wary of this. If we get anything wrong above, we're deadlocked here and those are my least favorite to debug. In either case, anything that blocks like this I think is also supposed to keep an eye on the stopper? 

It'd also be nice if we could cancel as soon as we know there's a problem. Combined (along with trying to reason about multiple gorooutines writing to `err`, these are making me think it might be a good candidate for `ctxgroup`. I'm not sure of specifics, but might look something like:
shared vars: `var tableRowCount int` and a `countReady := make(chan struct{})`. 
Use a ctxgroup to 1) kick off the table row counter. When it finishes it sets `tableRowCount` and closes `countReady`
2)  for each index, use ctxgroup to kick off the count func. Inside each , after the count finishes query, select on `<-tableCountReady` as well as `stopper.shouldStop` and the ctx.Done ch. If the table counter has closed the ready ch, it should be safe to read and compare to`tableRowCount`. On mismatch, or another other errors, returning a non-nil error from the func should cause the ctxgroup to cancel everything for us. If the sql exec looks at the context, it should even cancel the in-flight counts. 

It also handles accumulating the err in a lock-protected way for us. 

I dunno, maybe this doesn't make sense, but I'm just a little wary of counting on reading and writing N things to a channel -- that has often bitten me in the past when things start to go wrong, and I have to debug a deadlock before I can even start debugging the actual error.
___
*[pkg/sql/backfill.go, line 600 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34263#-LXa49p-7GRjPMJOYvIZ:-LXa49p-7GRjPMJOYvI_:bkfem44) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8fcf688bcb683fb891ee0cbd9caf8ad4c6833f4/pkg/sql/backfill.go#L600)):*
> ```Go
> 				index := <-notify
> 				if index.err != nil {
> 					err = index.err
> ```

will the race detector be okay with concurrent writes to err?

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/backfill.go, line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34263#-LXa3995-ZA9jeIL2YfB:-LY3L6ac34aGkLsmURQV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8fcf688bcb683fb891ee0cbd9caf8ad4c6833f4/pkg/sql/backfill.go#L516)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we might want a ctx that we can cancel as soon as one of these fails so we don't wait for wasted work. 
Actually, this looks like it might be a good use for ctxgroup?

</blockquote></details>

Done.
___
*[pkg/sql/backfill.go, line 598 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34263#-LXa4sGgCfKZyt5UTHzO:-LY3L87D1YOVwlwRcBWq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8fcf688bcb683fb891ee0cbd9caf8ad4c6833f4/pkg/sql/backfill.go#L598)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm a little wary of this. If we get anything wrong above, we're deadlocked here and those are my least favorite to debug. In either case, anything that blocks like this I think is also supposed to keep an eye on the stopper? 

It'd also be nice if we could cancel as soon as we know there's a problem. Combined (along with trying to reason about multiple gorooutines writing to `err`, these are making me think it might be a good candidate for `ctxgroup`. I'm not sure of specifics, but might look something like:
shared vars: `var tableRowCount int` and a `countReady := make(chan struct{})`. 
Use a ctxgroup to 1) kick off the table row counter. When it finishes it sets `tableRowCount` and closes `countReady`
2)  for each index, use ctxgroup to kick off the count func. Inside each , after the count finishes query, select on `<-tableCountReady` as well as `stopper.shouldStop` and the ctx.Done ch. If the table counter has closed the ready ch, it should be safe to read and compare to`tableRowCount`. On mismatch, or another other errors, returning a non-nil error from the func should cause the ctxgroup to cancel everything for us. If the sql exec looks at the context, it should even cancel the in-flight counts. 

It also handles accumulating the err in a lock-protected way for us. 

I dunno, maybe this doesn't make sense, but I'm just a little wary of counting on reading and writing N things to a channel -- that has often bitten me in the past when things start to go wrong, and I have to debug a deadlock before I can even start debugging the actual error.
</blockquote></details>

Done.
___
*[pkg/sql/backfill.go, line 600 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34263#-LXa49p-7GRjPMJOYvIZ:-LY3LASH29GnEJEVTcOe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8fcf688bcb683fb891ee0cbd9caf8ad4c6833f4/pkg/sql/backfill.go#L600)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

will the race detector be okay with concurrent writes to err?
</blockquote></details>

Done.

**Review by dt — APPROVED** [review]

**Pull request merged**
