### PR TITLE
cli: add basic 'help foo' to describe functions

### PR DESCRIPTION
**Pull request by dt**
Short-hand version, and named arguments in `replace`:

```
root@:26257> \? replace

*** String and Byte Functions ***

replace(s string, from string, to string) -> string

regexp_replace(string, string, string) -> string

regexp_replace(string, string, string, string) -> string

root@:26257>
```

the named arguments will also be good to use in the docs page generator.
a followup will add long-form description text to Builtin as well, which again, will also be useful in the docs generator.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8577)

### CODE REVIEW

**Comment by knz** [comment]
Wow I've wanted this for *so* much time. Thank you so much for tackling this!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 74 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIqsAKgsfahPhL5fD8:-KPIqsALmdrp9rgKEGdy:b-4k2r32) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L74)):*
> ```Go
> 		found := make(map[string][]namedBuiltin)
> 		for f, matches := range parser.Builtins {
> 			if strings.Contains(f, name) {
> ```

I'd recommend using a fuzzy matcher for this (see https://godoc.org/?q=fuzzy ), and the next best thing would be`filepath.Match` for this ( https://golang.org/pkg/path/filepath/#Match ) -- glob syntax is powerful enough to tweak the search when you're not entirely sure of the spelling, yet not as complicated/confusing as regexps for new users. 

---

*[cli/sql.go, line 84 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrjukfyuH3un4MiuA:-KPIrjukfyuH3un4MiuB:bi36fql) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L84)):*
> ```Go
> 			if strings.Contains(f, name) {
> 				for _, match := range matches {
> 					aggs = append(aggs, namedBuiltin{f, match})
> ```

what about `found["Aggregate"] = append(found["Aggregate"], ...)` ?

---

*[cli/sql.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIraZWaKEBwruNSg7o:-KPIraZXkUVYvf2f1bBr:bnnbfcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L95)):*
> ```Go
> 			return
> 		}
> 		// TODO(dt): sort by edit distance?
> ```

A fuzzy matching package would give you this distance.

---

*[cli/sql.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrxPIA7TyqFx-VeQ1:-KPIrxPJnJhkL1QuJJ6L:b-ed7mg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L159)):*
> ```Go
> 				_, hasSet = isEndOfStatement(syntax, stmt)
> 				return status, hasSet
> 			case `\`, `\?`, `help`, `HELP`:
> ```

I'm not entirely sure we want to merge `\?` and `help`. It feels to me like we ought to distinguish a command like `help`  for SQL and `\?` for client-side (shell-specific) commands. psql for example uses separate `\h` and `\?`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-:-KPIqM4txAcb6lG7h11f:b-lf3eay)*

**Comment by tamird** [comment]
That is a nice usage example in the PR description - can you move it to the commit message?

Also, can you write a CLI test?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIr0n92iqCiQv5Jwk2:-KPIr0n92iqCiQv5Jwk3:b377rt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L145)):*
> ```Go
> 		}
> 
> 		if (len(line) > 0 && line[0] == '\\') || (len(line) >= 4 && strings.EqualFold(line[:4], "help")) {
> ```

can this condition just go away? what is this `if` guarding?

---

*[sql/parser/builtins.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrum1m14hqprTa8L9:-KPIrum2lLQGgAFrcgK5:b70f2r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/sql/parser/builtins.go#L69)):*
> ```Go
> type Builtin struct {
> 	Types      typeList
> 	ArgNames   []string
> ```

Not thrilled about the possibility of this drifting (or simply being incorrect) can you add a TODO? we might be able to get creative with how we generate these.

---

*[sql/parser/overload.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIsD2mBELG_mCXZrOA:-KPIsD2mBELG_mCXZrOB:b-c54e4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/sql/parser/overload.go#L43)):*
> ```Go
> 	getAt(i int) Datum
> 
> 	String(names []string) string // human readable signature, using `names`` if provided.
> ```

extra tick

---

*[sql/parser/overload.go, line 89 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIsFmxIj2AEj88p9D5:-KPIsFmxIj2AEj88p9D6:b-hg77) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/sql/parser/overload.go#L89)):*
> ```Go
> 	first := true
> 	for i := range a {
> 		if first {
> ```

why do you need first? it's equivalent to `i == 0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-:-KPIq_Xm0AKPPzjxY-5p:b8prhx7)*

**Comment by dt** [comment]
I'm kinda thinking I actually want to move this server-side and add a `HELP` statement -- in the event the client and server are different versions, the execution of the functions will still be done by the server, so it should handle describing them too to ensure consistency.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/parser/builtins.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrum1m14hqprTa8L9:-KPIsrMOjQVXZ3y5vX64:b6dhddg) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/sql/parser/builtins.go#L69)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Not thrilled about the possibility of this drifting (or simply being incorrect) can you add a TODO? we might be able to get creative with how we generate these.
</details>
AFAIK, there's no way to get parameter names via reflection, since it isn't even a requirement that parameters are named (e.g. if they are unused).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-:-KPIt2VvzF2x8tH4pNA-:beufxko)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/parser/builtins.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrum1m14hqprTa8L9:-KPItt6kMrPYJVM_6Vmj:bx8gdqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/sql/parser/builtins.go#L69)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> AFAIK, there's no way to get parameter names via reflection, since it isn't even a requirement that parameters are named (e.g. if they are unused).
</details>
That's true, but the parameters were passed as a struct...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 84 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrjukfyuH3un4MiuA:-KPIvji5BhH0yyD2Zctd:bfhkjnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L84)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> what about `found["Aggregate"] = append(found["Aggregate"], ...)` ?
</details>
why pay the map lookup cost every time?

---

*[cli/sql.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIraZWaKEBwruNSg7o:-KPIvqb14HGFgnt0Ursx:b-yhnode) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> A fuzzy matching package would give you this distance.
</details>
it's a little harder than that since they are bucket'ed by category, so you'd need to rank the matches, then figure out which category has the highest... avg weight? single highest weight match? this is why I punted this to a TODO.

---

*[cli/sql.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIr0n92iqCiQv5Jwk2:-KPIwI9bS9anYmTBLefA:brcvic5) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L145)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this condition just go away? what is this `if` guarding?
</details>
once we enter the `if` we have to pick a valid cmd or fail, whereas outside the `if`, we process as a query I think.

---

*[sql/parser/builtins.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrum1m14hqprTa8L9:-KPIwdaWkJ9nr-06Fd_0:bp33rxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/sql/parser/builtins.go#L69)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> That's true, but the parameters were passed as a struct...
</details>
the implementation `fn` that is actually executed has (usually) named arguments -- imo these names should match those. AFAIK, there's no way for us to enforce that though (well, custom static analysis, but that seems like overkill). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/parser/builtins.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrum1m14hqprTa8L9:-KPIy0h1H-UrynfQ5X3B:b4em0s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/sql/parser/builtins.go#L69)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> the implementation `fn` that is actually executed has (usually) named arguments -- imo these names should match those. AFAIK, there's no way for us to enforce that though (well, custom static analysis, but that seems like overkill). 
</details>
what I'm saying is that `fn` can take a struct which has named fields, and those *are* retrievable via reflection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 84 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIrjukfyuH3un4MiuA:-KQXR-EgVjAn2QsVDNIn:b-yi3l4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L84)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> why pay the map lookup cost every time?
</details>
because "help" won't be called often enough that the better perf makes a difference, and the code would be more readable that way.

---

*[cli/sql.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIraZWaKEBwruNSg7o:-KQXRBPCdtUJuC0BNnrm:b6apnsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L95)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> it's a little harder than that since they are bucket'ed by category, so you'd need to rank the matches, then figure out which category has the highest... avg weight? single highest weight match? this is why I punted this to a TODO.
</details>
Ok with me.

---

*[cli/sql.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577#-KPIr0n92iqCiQv5Jwk2:-KQXRID4Br8F8UdPMAEQ:b1fo3pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/047f598e9f2a366a289c084234d6322259e33106/cli/sql.go#L145)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> once we enter the `if` we have to pick a valid cmd or fail, whereas outside the `if`, we process as a query I think.
</details>
I'd use `strings.EqualFold(line, "help") || (len(line) > 4 && strings.EqualFold(line[:5], "help "))` to reject "helpblah" properly. Also move the predicate to `isHelpCommand()` for readability.

(your other comment about moving this server-side notwithstanding.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8577)*

**Comment by dt** [comment]
(closing for now -- I think if/when we do this, we should do it server-side)

**Pull request closed without merging**
