### PR TITLE
distsqlrun: lookup join efficiency improvements

### PR DESCRIPTION
**Pull request by jordanlewis**
- distsqlrun: don't save lookup rows twice
- distsqlrun: stream lookup join output
- distsql: remove unused field from lookup join spec

Previously, lookup join buffered its rendered output rows before
emitting any of them, because this used to be a requirement when lookup
join was also responsible for doing a second layer of lookups against an
index. This was no longer necessary.

Now, after the result of a lookup batch is accumulated into memory, rows
are rendered and emitted in a row-at-a-time streaming fashion.

Also, remove the unused extra index filter expression field from the lookup join spec.

### CODE REVIEW

**Comment by jordanlewis** [comment]
PTAL, thanks!

**Review by yuzefovich — COMMENTED** [review]
Very nice, no nits from me :) LGTM.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39043#-:-LkjN_qW1qF2Rfx-sWDA:b81u0m0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Review by solongordon — APPROVED** [review]
Great stuff. It's nice to see the lookup joiner becoming less of a beast.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39043#-:-Lkxogrz7EM64YwWZBH3:bos18i8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/distsqlrun/joinreader.go, line 473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39043#-LkxoIPP7ES15bndh42S:-LkxoIPP7ES15bndh42T:b-de3d4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae28913a4b7c87fd6e66592f3f3f5f758752bfc/pkg/sql/distsqlrun/joinreader.go#L473)):*
> ```Go
> 	*distsqlpb.ProducerMetadata,
> ) {
> 	for {
> ```

Minor: I think this would read better if rather than wrapping the whole thing in a for loop, you just returned `jrEmittingRows, nil, nil` whenever there is no output and let the state machine do its work.

**Review by jordanlewis — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39043#-:-Lky0nGs5RvZu5cU_3BF:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsqlrun/joinreader.go, line 473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39043#-LkxoIPP7ES15bndh42S:-Lky0lx65rdrJL_Jv9ER:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae28913a4b7c87fd6e66592f3f3f5f758752bfc/pkg/sql/distsqlrun/joinreader.go#L473)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Minor: I think this would read better if rather than wrapping the whole thing in a for loop, you just returned `jrEmittingRows, nil, nil` whenever there is no output and let the state machine do its work.
</blockquote></details>

Done.

**Pull request merged**
