### PR TITLE
Added link to the to-do apps repo

### PR DESCRIPTION
**Pull request by Amruta-Ranade**

### CODE REVIEW

**Comment by jordanlewis** [comment]
LGTM! (in general, we usually don't permit merges without a review - we might have to make a policy for documents like this that's different. in the mean time, just review request me! I'll try to be quick about them.)

**Comment by Amruta-Ranade** [comment]
I forgot that bors merges the PR 😳  I thought it would just run the tests and then I'd ask for a review and merge it manually (the way we do for docs). Sorry!

**Comment by jordanlewis** [comment]
No problem! 👍👍

**Pull request merged**
