### PR TITLE
opt: use a layout table for ExprView methods

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add Private call in ExprView benchmark

Release note: None

#### opt: use a layout table for ExprView methods

Replacing the generated `ChildCount`, `ChildGroup`, `privateID`
methods with a layout table: each op has an 8-bit value which contains
the number of children (excluding lists), position of list in state
array (if any), position of private in state array (if any), and
whether the op is an enforcer.

The methods are reimplemented to use the table.

```
name          old time/op    new time/op    delta
ExprView/0-8     502ns ± 2%     340ns ± 2%  -32.31%  (p=0.000 n=10+10)
```

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Note that the benchmark timings aren't comparable to the ones in my previous PR - I added a `Private()` call for each node.

**Comment by andy-kimball** [comment]
:lgtm:
Very interesting results. One thing I'm curious about: does it make any difference whether `lookupExpr` and `lookupNormExpr` return `*memoExpr` vs. `memoExpr`?

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-L6dF-asSF-Y29HVTQUl:-L6dF-asSF-Y29HVTQUm:b2fc2j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b372ebd8312b6ffc5aeefc2c54c918233fc7e105/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L42)):*
> ```Go
> 
> 	g.genLayoutTable()
> 	//g.genPrivateFieldLookup()
> ```

NIT: Should this be removed rather than commented out?

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-L6dEh0y-2n8tktIW1da:-L6dEh0y-2n8tktIW1db:b-cqxt3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b372ebd8312b6ffc5aeefc2c54c918233fc7e105/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L58)):*
> ```Go
> }
> 
> // genLayoutTable generates the layout
> ```

NIT: Need to finish comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-:-L6dGbZs1xPi-d7rQnwr:b-7gddg6)*

**Comment by petermattis** [comment]
Looks a lot like the `opttoy/v3` approach, though I settled on that due to the ergonomics. I never actually benchmarked it.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/xform/expr.go, line 336 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-L6dIPiLJ-FuyNncYmfk:-L6dIPiLJ-FuyNncYmfl:br3jrac) ([raw file](https://github.com/cockroachdb/cockroach/blob/b372ebd8312b6ffc5aeefc2c54c918233fc7e105/pkg/sql/opt/xform/expr.go#L336)):*
> ```Go
> //
> // The table of values (opLayoutTable) is generated by optgen.
> type opLayout uint8
> ```

Was it important to make this 8-bits vs a struct with fields? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-:-L6dImqATIi-ITjzjBMF:b-5ubles)*

**Comment by RaduBerinde** [comment]
It's not an easy thing to try, all the things like `asProjections, asVariable` need to change, along with the generated code that uses them (and currently compares the result to `nil`). I will spend some time on it (though it might wait until next Friday).

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-L6dF-asSF-Y29HVTQUl:-L6dJHZ-2VALEJecVhwn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b372ebd8312b6ffc5aeefc2c54c918233fc7e105/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L42)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Should this be removed rather than commented out?
</blockquote></details>

Done.

---

*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-L6dEh0y-2n8tktIW1da:-L6dJHJBe4aqkSbKU7xH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b372ebd8312b6ffc5aeefc2c54c918233fc7e105/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L58)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Need to finish comment.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/expr.go, line 336 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-L6dIPiLJ-FuyNncYmfk:-L6dJAWU__He3zq77ksP:bcytmcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b372ebd8312b6ffc5aeefc2c54c918233fc7e105/pkg/sql/opt/xform/expr.go#L336)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Was it important to make this 8-bits vs a struct with fields? 
</blockquote></details>

I didn't try a struct. I figured the smaller the better (the table will hopefully stay in a low-level cache).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-:-L6dJNCkeXvcwGsUcnzq:b-ezb405)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/xform/expr.go, line 336 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-L6dIPiLJ-FuyNncYmfk:-L6dL4LmoeSR47Dip90F:bje118j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b372ebd8312b6ffc5aeefc2c54c918233fc7e105/pkg/sql/opt/xform/expr.go#L336)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I didn't try a struct. I figured the smaller the better (the table will hopefully stay in a low-level cache).
</blockquote></details>

My intuition is that smaller is better as well. I was just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330)*

**Comment by andy-kimball** [comment]
A quick and dirty check would be to create a `lookupExpr2` method and use it only from the EV code, just to see if it has any impact on the benchmark.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-:-L6dNK6RvuKtphlaMwxn:bm5r6hb)*

**Comment by RaduBerinde** [comment]
Oh, good point. I just tried that but it's slower (~370ns instead of ~320ns).

**Comment by rytaft** [comment]
:lgtm: good idea!

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23330#-:-L6hKOjYY802MyLJw1vm:bbzbus6)*

**Pull request merged**
