### PR TITLE
cli/interactive_tests: deflake some tests

### LINKED ISSUE #39720: test failure: TestDockerCLI/test_log_config_msg.tcl
Happened to me on CI here:
https://teamcity.cockroachdb.com/viewLog.html?buildId=1442417&buildTypeId=Cockroach_UnitTests

I guess this failure claims that the cluster ID was not printed in the logs... But I'm not sure how to check the get the logs...

```
TestDockerCLI/test_log_config_msg.tcl/runMode=docker

.190816 17:56:10.919356973 EXPECT TEST: BEGIN START SERVER
?column?
1

.190816 17:56:15.028047904 EXPECT TEST: START SERVER DONE

.190816 17:56:15.034128397 EXPECT TEST: BEGIN STOP SERVER
still waiting

.190816 17:56:16.380400178 EXPECT TEST: END STOP SERVER

.190816 17:56:16.386403861 EXPECT TEST: START TEST: Check that the cluster ID is reported at the start of the first log file.
child process exited abnormally
    while executing
"system "grep -qF '\[config\] clusterID:' logs/db/logs/cockroach.log""
    (file "/go/src/github.com/cockroachdb/cockroach/cli/interactive_tests/test_log_config_msg.tcl" line 12)
non-zero exit code: 1
        cli_test.go:88: non-zero exit code: 1
```

### LINKED ISSUE #40746: teamcity: failed test: TestDockerCLI
The following tests appear to have failed on master (acceptance): TestDockerCLI/test_disable_replication.tcl, TestDockerCLI

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestDockerCLI).

[#1485022](https://teamcity.cockroachdb.com/viewLog.html?buildId=1485022):

```
TestDockerCLI
--- FAIL: acceptance/TestDockerCLI (372.920s)

------- Stdout: -------
    test_log_scope.go:77: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerCLI196157948
    test_log_scope.go:58: use -show-logs to present logs inline



TestDockerCLI/test_disable_replication.tcl
--- FAIL: acceptance/TestDockerCLI: TestDockerCLI/test_disable_replication.tcl (15.850s)





```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #40776: teamcity: failed test: TestDockerCLI
The following tests appear to have failed on master (acceptance): TestDockerCLI, TestDockerCLI/test_sql_version_reporting.tcl

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestDockerCLI).

[#1488926](https://teamcity.cockroachdb.com/viewLog.html?buildId=1488926):

```
TestDockerCLI
--- FAIL: acceptance/TestDockerCLI (406.140s)

------- Stdout: -------
    test_log_scope.go:77: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerCLI136240066
    test_log_scope.go:58: use -show-logs to present logs inline



TestDockerCLI/test_sql_version_reporting.tcl
--- FAIL: acceptance/TestDockerCLI: TestDockerCLI/test_sql_version_reporting.tcl (16.040s)





```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #40788: teamcity: failed test: TestDockerCLI
The following tests appear to have failed on master (acceptance): TestDockerCLI/test_log_config_msg.tcl, TestDockerCLI

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestDockerCLI).

[#1489801](https://teamcity.cockroachdb.com/viewLog.html?buildId=1489801):

```
TestDockerCLI
--- FAIL: acceptance/TestDockerCLI (458.700s)

------- Stdout: -------
    test_log_scope.go:77: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerCLI915653011
    test_log_scope.go:58: use -show-logs to present logs inline



TestDockerCLI/test_log_config_msg.tcl
--- FAIL: acceptance/TestDockerCLI: TestDockerCLI/test_log_config_msg.tcl (10.540s)





```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by knz**
Release justification: see individual commits

### cli/interactive_tests: make server shutdown more resilient

Fixes #40776.
Fixes #40788.
Fixes #40746.

This patch intends to resolve test flakiness in the CLI interactive
tests. The flakiness was observed while shutting down servers at the
end of tests. The symptom are:

- the `cockroach quit` command terminates successfully;
- after 5 seconds, the process is still there (its PID is still present);
- immediately when the 5-second loop stops and the script attempts
  to forcefully kill the process, the PID is not there any more;
- the server log file indicates the server has shut down successfully.

This combination of symptoms suggests that the server shutdown takes
approximately 5 seconds. Flakiness occurs because most of the time it
shuts down within 5 seconds, and only occasionally takes more than 5
seconds.

The patch thus bumps the delay for forceful shutdown up to 30
seconds. Since an escape from the loop (server fails to shut down)
incurs a failure of the test, we are expecting this to only occur
rarely.

Separately, the patch also changes the definition of the separate
action `force_stop_server` to immediately kill the process. The 3
callers of this action do not expect a graceful `quit` to succeed
anyway.

### cli/interactive_tests: deflake test_log_config_msg

Fixes #39720.

This test checks that the cluster ID is reported at the start of the
log file(s). Prior to this patch, it would check this by starting a
server, then quitting it immediately, and then looking at the
resulting log file.

This logic was flawed, because it is possible for `cockroach quit` to
instruct a server to shut down before it has completed
its (informational) report in the log file.

This patch resolves this bug by waiting for the expected log output
*before* quitting the server instead of afterwards.

### CODE REVIEW

**Comment by knz** [comment]
Ironically I am encountering this separate flake #39720  in the CI run for this PR.
I'll fix both in one go.

**Comment by knz** [comment]
this will need a backport

**Review by andreimatei — APPROVED** [review]
:lgtm: 

thanks for poking at these

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40821#-:-LozbZ0ICozdh43kPU7c:bhvhnvl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @jordanlewis, and @knz)

___
*[pkg/cli/interactive_tests/common.tcl, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40821#-Lozao-sENaca8Q6Rupc:-Lozao-sENaca8Q6Rupd:b-qemdhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ff765e250221e81c36d430064901bdbea0e0d7/pkg/cli/interactive_tests/common.tcl#L99)):*
> ```Tcl
>     report "BEGIN STOP SERVER"
>     # Trigger a normal shutdown.
> 	# If after 10 seconds the server hasn't shut down, kill the process and trigger an error.
> ```

nit: tab
___
*[pkg/cli/interactive_tests/common.tcl, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40821#-LozbPZI7VbnioqH1oK_:-LozbPZI7VbnioqH1oKa:b-od42ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ff765e250221e81c36d430064901bdbea0e0d7/pkg/cli/interactive_tests/common.tcl#L99)):*
> ```Tcl
>     report "BEGIN STOP SERVER"
>     # Trigger a normal shutdown.
> 	# If after 10 seconds the server hasn't shut down, kill the process and trigger an error.
> ```

s/10/30 right?
___
*[pkg/cli/interactive_tests/common.tcl, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40821#-LozbHCm5wgvesmqBcsf:-LozbHCm5wgvesmqBcsg:b-bltd71) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ff765e250221e81c36d430064901bdbea0e0d7/pkg/cli/interactive_tests/common.tcl#L102)):*
> ```Tcl
>     system "kill -TERM `cat server_pid` 2>/dev/null;
>             for i in `seq 1 30`; do
>               kill -CONT `cat server_pid` 2>/dev/null || exit 0
> ```

would you mind commenting what this `sigcont` does exactly? If we're just interested in whether the server is alive, wouldn't a `pgrep` be better?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40821)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @jordanlewis)

___
*[pkg/cli/interactive_tests/common.tcl, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40821#-Lozao-sENaca8Q6Rupc:-LozctB2BQFZ9bBrzd_C:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ff765e250221e81c36d430064901bdbea0e0d7/pkg/cli/interactive_tests/common.tcl#L99)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: tab
</blockquote></details>

Done
___
*[pkg/cli/interactive_tests/common.tcl, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40821#-LozbPZI7VbnioqH1oK_:-LozcthYDlcQRJgXMjla:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ff765e250221e81c36d430064901bdbea0e0d7/pkg/cli/interactive_tests/common.tcl#L99)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/10/30 right?
</blockquote></details>

Done.
___
*[pkg/cli/interactive_tests/common.tcl, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40821#-LozbHCm5wgvesmqBcsf:-Lozcu5k6IbQjhlN18aR:b-nn1akl) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ff765e250221e81c36d430064901bdbea0e0d7/pkg/cli/interactive_tests/common.tcl#L102)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

would you mind commenting what this `sigcont` does exactly? If we're just interested in whether the server is alive, wouldn't a `pgrep` be better?
</blockquote></details>

Added comment.
`pgrep` doesn't work for this use case.

**Comment by knz** [comment]
bors r=andreimatei

**Comment by jordanlewis** [comment]
This needs a Release justification note in the PR description since it's a multi-commit patch.

**Pull request merged**
