### PR TITLE
turn LeaseRejectedError into NotLeaderError

### PR DESCRIPTION
**Pull request by tbg**
@petermattis for #1149. See if that helps.

### CODE REVIEW

**Comment by petermattis** [comment]
Yes, that appears to fix the problem.

**Comment by petermattis** [comment]
At least, it advanced the ball. Now I'm seeing some sort of infinite loop on the servers:

```
I0527 01:26:08.201165       1 retry.go:95] routing InternalPushTxn rpc failed; retrying immediately
W0527 01:26:08.209271       1 dist_sender.go:590] failed to invoke InternalPushTxn: key range "00032369"-"" outside of bounds of range ""-"00008011"
I0527 01:26:08.209410       1 retry.go:95] routing InternalPushTxn rpc failed; retrying immediately
W0527 01:26:08.233266       1 dist_sender.go:590] failed to invoke InternalPushTxn: key range "00032369"-"" outside of bounds of range ""-"00008011"
I0527 01:26:08.233951       1 retry.go:95] routing InternalPushTxn rpc failed; retrying immediately
W0527 01:26:08.246387       1 dist_sender.go:590] failed to invoke InternalPushTxn: range 5 was not found
```

**Comment by tschottdorf** [comment]
This looks like a request getting routed to the wrong range a couple of times and then being sent to a range that doesn't exist. Since the leader cache should be cleared between retries (`kv/dist_sender.go:596`), I don't see why it would look up the wrong range. Maybe there is a merge/... going on? I'll see if I can reproduce this with your PR.

**Comment by tschottdorf** [comment]
It's a split, I think:

> I0527 14:00:26.470310       1 range_command.go:832] initiating a split of range 2 "00008143"-"\xff\xff" at key "00016276"
> W0527 14:00:28.401088       1 dist_sender.go:590] failed to invoke EndTransaction: key range "00016276"-"" outside of bounds of range "00008143"-"00016276"
I0527 14:00:28.403585       1 retry.go:95] routing EndTransaction rpc failed; retrying immediately
E0527 14:00:28.405403       1 range.go:785] error executing raft command Put: key range "00024415"-"" outside of bounds of range "00008143"-"00016276"
E0527 14:00:28.408522       1 range.go:785] error executing raft command Put: key range "00024416"-"" outside of bounds of range "00008143"-"00016276"
W0527 14:00:28.435283       1 dist_sender.go:590] failed to invoke EndTransaction: key range "00016276"-"" outside of bounds of range "00008143"-"00016276"
I0527 14:00:28.442493       1 retry.go:95] routing EndTransaction rpc failed; retrying immediately
E0527 14:00:28.449569       1 range.go:785] error executing raft command Put: key range "00024417"-"" outside of bounds of range "00008143"-"00016276"

**Comment by petermattis** [comment]
@tschottdorf Can't imagine why a merge would be happening as the test is only writing data, not deleting it.

**Comment by tschottdorf** [comment]
I'm also getting this:

> W0527 14:02:49.140350       1 client.go:283] client roach0.local:8080 unhealthy after 3s
W0527 14:02:49.973187       1 raft_transport.go:190] raft client for node 1 unhealthy
W0527 14:02:50.114537       1 raft_transport.go:190] raft client for node 1 unhealthy
W0527 14:02:50.194825       1 raft_transport.go:190] raft client for node 1 unhealthy

I'm pretty sure I got a hailstorm of stacktraces on a previous run, but I deleted that log. Looks like we're filling something up here.

**Comment by tschottdorf** [comment]
pure speculation about this here:

> W0527 14:10:55.615324       1 dist_sender.go:590] failed to invoke InternalPushTxn: range 4 was not found

Maybe there's a gap in holding locks on the store when updating the local range on a split, so that there's a short moment during which the old range is taken out and reinserted only a moment later.

**Comment by tschottdorf** [comment]
I'm seeing very long restart races regarding leadership - a lot of NotLeaderErrors that don't seem to be going anywhere, blocking basically everything for tens of seconds at a time.

The aforementioned panic also came back: It's just an out of memory error. An analysis of the goroutines in the trace shows this:

``` 
   2 github.com/cockroachdb/cockroach/server.(*rpcTransport).processQueue
   2 github.com/cockroachdb/cockroach/storage.(*Store).ProposeRaftCommand
   3 github.com/cockroachdb/cockroach/rpc.Send
   4 github.com/cockroachdb/cockroach/rpc.(*Client).startHeartbeat
   4 github.com/cockroachdb/cockroach/storage.func·013()
   9 net.(*pollDesc).Wait
  22 github.com/cockroachdb/cockroach/rpc.sendOne
  66 github.com/cockroachdb/cockroach/util/retry.WithBackoff
 284 github.com/cockroachdb/cockroach/multiraft.(*multiraftServer).RaftMessage
1353 sync.(*Mutex).Lock
6350 sync.(*WaitGroup).Wait
```

(`cat acceptance-put-retries-onlypanic.log | grep -A 1 goroutine | grep -v goroutine | sed 's/(0x.*//g' | sort | uniq -c | sort -n`)

The 6350 WaitGroup ones are mostly `InternalPushTxn` calls piling up at `Range.beginCmd()`; the Mutex is there as well.

**Comment by tschottdorf** [comment]
I've gotten it to crash with an out of memory error again, but the goroutine profile looks inconspicous:

```
   3 github.com/cockroachdb/cockroach/rpc.(*Client).startHeartbeat
   3 github.com/cockroachdb/cockroach/storage.func·013()
   3 github.com/cockroachdb/cockroach/util/retry.WithBackoff
   7 sync.(*Mutex).Lock
   8 net.(*pollDesc).Wait
  12 github.com/cockroachdb/cockroach/rpc.Send
  30 sync.(*WaitGroup).Wait
```

So we must be leaking memory or (hopefully not) churning it faster than GC can put up with.

**Comment by tschottdorf** [comment]
It's definitely the range splitting. It causes an intents push/backoff mayhem on the range descriptors. I'll be posting some small fixes for this (which probably won't make everything alright but at least reduce the amount of noise in debugging this).

**Comment by tschottdorf** [comment]
This is ready for an actual look now.

**Comment by petermattis** [comment]
LGTM

**Pull request merged**
