### PR TITLE
asim: add simulation datadriven test framework 

### LINKED ISSUE #90138: asim: add test harness
The asim pkg does not currently have a method to easily instantiate the simulator with a configuration (workload, stores, nodes, initial state) and assert on the results.

The solution is to add a testing harness that can be instantiated easily and is configurable. The harness should to support:

- declaring or using a preset cluster configuration of nodes, stores, initial ranges and their replicas.
- configuring cluster settings such as thresholds and enabling/disabling components
- ability to assert on the state of the simulation (and possibly intermediate state, via invariants).

Jira issue: CRDB-20608

### PR DESCRIPTION
**Pull request by kvoli**
This commit adds the ability to declare datadriven tests that use the
allocation simulator and assert on the recorded history of a simulation.
The test framework may also be used to explore and for understanding on
an adhoc basis by creating a scratch test file.

The supported commands:

```
- "gen_load" [rw_ratio=<float>] [rate=<float>] [access_skew=<bool>]
  [min_block=<int>] [max_block=<int>] [min_key=<int>] [max_key=<int>]
  Initialize the load generator with parameters. On the next call to eval,
  the load generator is called to create the workload used in the
  simulation. The default values are: rw_ratio=0 rate=0 min_block=1
  max_block=1 min_key=1 max_key=10_000 access_skew=false.

- "gen_state" [stores=<int>] [ranges=<int>] [placement_skew=<bool>]
  [repl_factor=<int>] [keyspace=<int>]
  Initialize the state generator parameters. On the next call to eval, the
  state generator is called to create the initial state used in the
  simulation. The default values are: stores=3 ranges=1 repl_factor=3
  placement_skew=false keyspace=10000.

- "assertion" type=<string> stat=<string> ticks=<int> threshold=<float>
  Add an assertion to the list of assertions that run against each
  sample on subsequent calls to eval. When every assertion holds during eval,
  OK is printed, otherwise the reason the assertion(s) failed is printed.
  There are two types of assertions available, type=balance and type=steady.
  Both assertions only look at the last ticks duration of the simulation
  run.

  For type=balance assertions, the max stat (e.g. stat=qps) value of each
  store is taken and divided by the mean store stat value. If the max/mean
  exceeds the threshold provided (e.g. threshold=1.15) during any of the
  last ticks (e.g. ticks=5), then the assertion fails. This assertion
  applies over all stores, at each tick, for the last ticks duration.

  For type=steady assertions, if the max or min stat (e.g. stat=replicas)
  value over the last ticks (e.g. ticks=6) duration is greater than
  threshold (e.g. threshold=0.05) % of the mean, the assertion fails. This
  assertion applies per-store, over ticks duration.

- "setting" [rebalance_mode=<int>] [rebalance_interval=<duration>]
  [rebalance_qps_threshold=<float>] [split_qps_threshold=<float>]
  [rebalance_range_threshold=<float>] [gossip_delay=<duration>]
  Configure the simulation's various settings. The default values are:
  rebalance_mode=2 (leases and replicas) rebalance_interval=1m (1 minute)
  rebalance_qps_threshold=0.1 split_qps_threshold=2500
  rebalance_range_threshold=0.05 gossip_delay=500ms.

- "eval" [duration=<string>] [samples=<int>] [seed=<int>]
  Run samples (e.g. samples=5) number of simulations for duration (e.g.
  duration=10m) time and evaluate every prior declared assertion against
  each sample. The seed (e.g. seed=42) given will be used to create a new
  random number generator that creates the seed used to generate each
  simulation sample. The default values are: duration=30m (30 minutes)
  samples=1 seed=random.

- "plot" stat=<string> [sample=<int>] [height=<int>] [width=<int>]
  Visually renders the stat (e.g. stat=qps) as a series where the x axis
  is the simulated time and the y axis is the stat value. A series is
  rendered per-store, so if there are 10 stores, 10 series will be
  rendered.
```

For example, consider asserting that a 7 store cluster with only 7
ranges will balance QPS (max<=mean*1.15) within 4 minutes and the
balance holds for at least 1 minute:

```
gen_state stores=7 ranges=7 placement_skew=true
----

gen_load rate=7000 rw_ratio=0.95 access_skew=false min_block=128 max_block=256
----

assertion stat=qps type=balance ticks=6 threshold=1.15
----

eval duration=3m samples=2 seed=42
----
OK

plot stat=qps sample=2
----
----

 3583 ┤ ╭╮
 3344 ┤ ││
 3105 ┤ │╰╮
 2866 ┤ │ │
 2627 ┤ │ │
 2389 ┤ │ │
 2150 ┤ │ │
 1911 ┤ │ ╰──────────────────────╮
 1672 ┤ │                        │
 1433 ┤ │    ╭╮╭──╮╭─────────────╮        ╭╮╭───────────────╮
 1194 ┤ │   ╭╯╰╯  ╰╯             │ ╭──────╯╰╯               │
  955 ┤ │   │                    │╮│                        │
  717 ┤ │╭──╭───────────────────────╭──────────────────────────────────────────
  478 ┤ ││ ╭│                      ╭│╯                        │
  239 ┤ ││ ││                      ││                         │
    0 ┼─────────────────────────────╯─────────────────────────╯
                                             qps
----
----
```

Note the simulator currently only supports evaluating the rebalancing
components of allocation.

Resolves: https://github.com/cockroachdb/cockroach/issues/90138

Depends on: #96822

Release note: None

### CODE REVIEW

**Review by AlexTalks — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 17 of 17 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96661)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBg7AO6HXHSomOsTOD:-NOBg7AO6HXHSomOsTOE:b-2kuoe1) ([raw file](https://github.com/cockroachdb/cockroach/blob/589b7387d30eaaf6f63128b41d063f4b97bbdd25/pkg/kv/kvserver/asim/state/config_loader.go#L151)):*
> ```Go
> }
> 
> type RangeInfo struct {
> ```

`RangeState` maybe?

Also are there any other existing structures in `roachpb` you can use that this duplicates?  Lastly, it seems like this should have a span rather than just a start key, no?
___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBk-FEC3hcSomBy055:-NOBk-FEC3hcSomBy056:b-gfkemj) ([raw file](https://github.com/cockroachdb/cockroach/blob/589b7387d30eaaf6f63128b41d063f4b97bbdd25/pkg/kv/kvserver/asim/state/config_loader.go#L192)):*
> ```Go
> }
> 
> // LoadRangesConfig loads the ranges specified in RangesInfo into state. If any
> ```

`s/LoadRangesConfig/LoadRangeInfo`
___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBkNgG53XeOUCr6hMA:-NOBkNgG53XeOUCr6hMB:blbxgq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c43ff0b1be75876b93265d45df669fec6c11f830/pkg/kv/kvserver/asim/state/config_loader.go#L38)):*
> ```Go
> // SingleRegionMultiStoreConfig is a simple cluster config with a single region
> // and 3 zones, all zones have 1 node and 6 stores per node.
> var SingleRegionMultiStoreConfig = ClusterInfo{
> ```

It might not be possible to share directly without changes, but this reminds me significantly of a lot of the store configs we have in `kvserver/*_test.go` and `allocatorimpl/*_test.go`.  Could we somehow enable reuse?
___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBkh3k5YHaavqZ3ani:-NOBkh3lEYbT3EIjPUKg:bqxgb3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c43ff0b1be75876b93265d45df669fec6c11f830/pkg/kv/kvserver/asim/state/config_loader.go#L224)):*
> ```Go
> 
> 		// Use the default span config if not set in the configuration.
> 		if r.Config.NumReplicas == 0 {
> ```

nit: this seems a bit odd, though fine if need be.  Possibly `nil` could be used?
___
*[`pkg/kv/kvserver/asim/state/new_state.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBl597BskQLHPCfmdL:-NOBl597BskQLHPCfmdM:b-v7kbiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c43ff0b1be75876b93265d45df669fec6c11f830/pkg/kv/kvserver/asim/state/new_state.go#L75)):*
> ```Go
> 			numRanges, minKey, maxKey))
> 	}
> 	rangeInterval := int(float64(maxKey-minKey+1) / float64(numRanges))
> ```

nit: This distribution generator makes sense though perhaps could use more comments.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96661)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @kvoli)

___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBg7AO6HXHSomOsTOD:-NOFYY0V-MVo5Ktu5Tg9:b-gpyi0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/589b7387d30eaaf6f63128b41d063f4b97bbdd25/pkg/kv/kvserver/asim/state/config_loader.go#L151)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

`RangeState` maybe?

Also are there any other existing structures in `roachpb` you can use that this duplicates?  Lastly, it seems like this should have a span rather than just a start key, no?
</blockquote></details>

I was tossing up here, since it's not a very compact representation when  using RangeDescriptor but it seems worthwhile just using it anyway, even though a lot of the info isn't usable atm in the simulator (voter/nonvoter/learner). Updated to use RangeDescriptor.

For the endKey, again there's no use for it atm since every range is being created together so the end key is known. It doesn't seem that difficult to add when needed.
___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBk-FEC3hcSomBy055:-NOFWacd1I5LKVbQl5vZ:bvnrpcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/589b7387d30eaaf6f63128b41d063f4b97bbdd25/pkg/kv/kvserver/asim/state/config_loader.go#L192)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

`s/LoadRangesConfig/LoadRangeInfo`
</blockquote></details>

updated
___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBkNgG53XeOUCr6hMA:-NOFX0_vCu6SW8Oi_yrO:b2ug409) ([raw file](https://github.com/cockroachdb/cockroach/blob/c43ff0b1be75876b93265d45df669fec6c11f830/pkg/kv/kvserver/asim/state/config_loader.go#L38)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

It might not be possible to share directly without changes, but this reminds me significantly of a lot of the store configs we have in `kvserver/*_test.go` and `allocatorimpl/*_test.go`.  Could we somehow enable reuse?
</blockquote></details>

There are a lot of store descriptor configs however it doesn't make sense imo to try and copy that format for the simulator representation. Instead adding a translator fn in the future would be best.
___
*[`pkg/kv/kvserver/asim/state/config_loader.go` line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBkh3k5YHaavqZ3ani:-NOFjDLt2iCyZcGoBPI3:bnwhzy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c43ff0b1be75876b93265d45df669fec6c11f830/pkg/kv/kvserver/asim/state/config_loader.go#L224)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: this seems a bit odd, though fine if need be.  Possibly `nil` could be used?
</blockquote></details>

Updated to be `nil`.
___
*[`pkg/kv/kvserver/asim/state/new_state.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-NOBl597BskQLHPCfmdL:-NOFkliRAdlQF1G3iKQx:b-x1e0et) ([raw file](https://github.com/cockroachdb/cockroach/blob/c43ff0b1be75876b93265d45df669fec6c11f830/pkg/kv/kvserver/asim/state/new_state.go#L75)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: This distribution generator makes sense though perhaps could use more comments.
</blockquote></details>

Added some explanations in key parts.

**Review by AlexTalks — APPROVED** [review]
:lgtm:

> Reviewed 30 of 30 files at r5, 18 of 18 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96661#-:-NOHNloO0wDmOR4lX3B4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR

**Comment by kvoli** [comment]
bors r=alextalks

**Comment by kvoli** [comment]
Bors r-

**Comment by kvoli** [comment]
Bors r+

**Pull request merged**
