### PR TITLE
storage: remove the possibility of nil Replica.raftGroup

### LINKED ISSUE #3896: Persistent crash in Raft
I was trying to start the first of the three nodes in a local cluster (the other 2 nodes were down), and I got a panic. It looks like a Replica's mu.raftGroup is somehow nil. Perhaps it's because of the errors that precede the panic?

This is consistently reproducible with my set of 'data' directories, which I've packaged up here:

https://www.dropbox.com/s/qzw3d8eh62ujhqx/bad_data.tgz?dl=0

Below is the Cockroach log output. Let me know if you need any other info.

```
/Users/cdo/gocode/bin/cockroach start --insecure --stores=ssd=data1 --addr=127.0.0.1:26001 --pgaddr=127.0.0.1:15001 --gossip=127.0.0.1:26001,127.0.0.2:26002,127.0.0.3:26003
I0113 09:45:43.061175 31993 cli/start.go:141  build Vers: go1.5.2
I0113 09:45:43.061271 31993 cli/start.go:142  build Tag:  v0.1-alpha-359-g80581b9
I0113 09:45:43.061282 31993 cli/start.go:143  build Time: 2016/01/13 14:45:22
I0113 09:45:43.061290 31993 cli/start.go:144  build Deps: github.com/VividCortex/ewma:c34099b489e4ac33ca8d8c5f9d29d6eeaf69f2ed github.com/biogo/store:3b4c041f52c224ee4a44f5c8b150d003a40643a0 github.com/cockroachdb/c-lz4:c40aaae2fc50293eb8750b34632bc3efe813e23f github.com/cockroachdb/c-protobuf:4feb192131ea08dfbd7253a00868ad69cbb61b81 github.com/cockroachdb/c-rocksdb:b7fb7bddcb55be35eacdf67e9e2c931083ce02c4 github.com/cockroachdb/c-snappy:5c6d0932e0adaffce4bfca7bdf2ac37f79952ccf github.com/cockroachdb/cockroach:80581b9b16187c17d4728669b96fc1feb9ac092c github.com/codahale/hdrhistogram:954f16e8b9ef0e5d5189456aa4c1202758e04f17 github.com/coreos/etcd:b35ab33045197fb31d22212e9e429e6cf72ea3db github.com/elazarl/go-bindata-assetfs:57eb5e1fc594ad4b0b1dbea7b286d299e0cb43c2 github.com/gogo/protobuf:c57e439bad574c2e0877ff18d514badcfced004d github.com/google/btree:cc6329d4279e3f025a53a83c397d2339b5705c45 github.com/julienschmidt/httprouter:21439ef4d70ba4f3e2a5ed9249e7b03af4019b40 github.com/lib/pq:2d785ad24be7a038e2fc35424b993645a0025425 github.com/mattn/go-runewidth:e882a96ec18dd43fa283187b66af74497c9101c0 github.com/montanaflynn/stats:2c10aa99e7ec8c4607d4427ec7a1a60fcdfce85f github.com/olekukonko/tablewriter:48dc4474bcf3e0134e9a64222207b1e020f171e9 github.com/peterh/liner:3f1c20449d1836aa4cbe38731b96f95cdf89634d github.com/rcrowley/go-metrics:7839c01b09d2b1d7068034e5fe6e423f6ac5be22 github.com/spf13/cobra:97f831a4fd01378ad85840fed4f43824bc3dd102 github.com/spf13/pflag:7f60f83a2c81bc3c3c0d5297f61ddfa68da9d3b7 golang.org/x/crypto:d67eb63455fa4d6fca5802332d86f1f204017e00 golang.org/x/net:76365a41624aa608f888301bf60fabecaf928b5a golang.org/x/text:cf4986612c83df6c55578ba198316d1684a9a287 gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b0f696e1de
I0113 09:45:43.061370 31993 server/context.go:186  1 storage engine(s) specified
I0113 09:45:43.061392 31993 cli/start.go:176  starting cockroach node
W0113 09:45:43.061412 31993 server/server.go:102  running in insecure mode, this is strongly discouraged. See --insecure and --certs.
I0113 09:45:43.063136 31993 storage/engine/rocksdb.go:106  opening rocksdb instance at "data1"
I0113 09:45:43.063152 31993 gossip/gossip.go:916  starting client to 127.0.0.2:26002
W0113 09:45:43.063480 31993 rpc/client.go:317  dial tcp 127.0.0.2:26002: getsockopt: connection refused
I0113 09:45:43.093544 31993 server/node.go:293  initialized store store=1:1 ([ssd]=data1): {Capacity:249779191808 Available:220275060736 RangeCount:0}
I0113 09:45:43.093736 31993 server/node.go:220  node ID 1 initialized
I0113 09:45:43.093870 31993 gossip/gossip.go:218  setting node descriptor node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:26001" > attrs:<> 
W0113 09:45:43.094056 31993 storage/replica.go:1576  could not acquire lease for range gossip: range 1 was not found
W0113 09:45:43.094227 31993 storage/replica.go:1576  could not acquire lease for range gossip: range 1 was not found
W0113 09:45:43.094595 31993 storage/store.go:639  error gossiping system config: range 1 was not found
W0113 09:45:43.094613 31993 storage/store.go:620  error gossiping first range data: range 1 was not found
I0113 09:45:43.101676 31993 gossip/gossip.go:267  read 3 gossip host(s) for bootstrapping from persistent storage
I0113 09:45:43.101704 31993 server/node.go:389  connecting to gossip network to verify cluster ID...
I0113 09:45:43.101721 31993 server/node.go:406  node connected via gossip and verified as part of cluster "3ce7a37d-7215-41a2-9411-318829882572"
I0113 09:45:43.101772 31993 server/node.go:258  Started node with [[ssd]=data1] engine(s) and attributes []
I0113 09:45:43.101828 31993 server/server.go:262  starting http server at 127.0.0.1:26001
I0113 09:45:43.101942 31993 sql/pgwire/server.go:76  starting postgres server at 127.0.0.1:15001
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x46f7634]

goroutine 51 [running]:
github.com/coreos/etcd/raft.(*RawNode).Tick(0x0)
	/Users/cdo/gocode/src/github.com/coreos/etcd/raft/rawnode.go:115 +0x14
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/Users/cdo/gocode/src/github.com/cockroachdb/cockroach/storage/store.go:1604 +0x790
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820214a80, 0xc8203717e0)
	/Users/cdo/gocode/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/cdo/gocode/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62
```

### LINKED ISSUE #4101: ChangeReplicas(...) REMOVE replica process fail, because scanner delete it from the queue according shouldQueue
**[Question 1]:**
For example, ChangeReplicas(...)
step 1. range 1 has A,B,C three replica
step 2. add replica D to range 1, then range 1 has A,B,C,D four replica
step 3. delete replica A from range 1, then range 1 has B,C,D three replica, replica A will be added to the replica_gc_queue

But, in step 3, it's a replica gc queue. If there are many elements in queue,
the scanner will scan the replicas in the store, meanwhile there is new leader lease which was took affect with the replica.
The queue.go MaybeAdd -> shouldQueue will return false,0 accroding to the lease expiration 24H and remove the replica from the queue. 
Wait a moment, kill the cockroach, the cockroach will never be started again. 
Beause the replica' local meta is not deleted yet, start command will load it and panic.

Summary, 
ChangeReplicas(...) RemoveReplica operation add replica to the replica_gc_queue directly without shouldQueue.
Scanner will add/remove replica to/from the replica_gc_queue according to the shouldQueue.
The two of them will affect each other.

**[Question 2]:**
The replica_gc_queue is a asynchronous processing. If the queue has not been fully processed, the cockroach is down.
The local meta is not deleted yet. Restart will be fail.

How do you feel? Or other suggestions.

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes #4101
Fixes #3896

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4204)

### CODE REVIEW

**Comment by tschottdorf** [comment]
The failure mode is a removal happening, and the local data not being destroyed. Isn't the only mechanism by which a nil `raftGroup` comes into existence in `NewStore` which in turn creates a new replica with a descriptor that doesn't contain the replica?
Why doesn't that lead to the replica not even being created/added to the Store in the first place? This sounds like what you were getting at in your comment on the test, so when is `raftGroup` intentionally nil?

**Comment by bdarnell** [comment]
OK, I've updated the commit to ensure that `Replica.raftGroup` is never nil instead of adding checks for it. This was a little tricky because there is a second way in which nil raftGroups are created. When Replicas are created in response to raft messages, they have a nil raftGroup and are then (non-atomically) updated with their replica ID. I fixed this by adding a replicaID argument to NewReplica.

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1, 7 of 8 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/client_raft_test.go, line 1460 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26QJyOaX8uFGGVWb8:-KA26QJyOaX8uFGGVWb9:958309040) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/client_raft_test.go#L1460)):*
Since the store is already running, is this a race? I feel like this should happen even before the replica is removed.

---

*[storage/replica.go, line 182 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26vkRVdyiAW5M7CF_:-KA26vkRVdyiAW5M7CFa:717608042) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/replica.go#L182)):*
OT: what's this wrapping at?

---

*[storage/replica.go, line 244 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA299OxdKvRAkXQBks_:-KA299OxdKvRAkXQBksa:1513187761) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/replica.go#L244)):*
`return r.setReplicaIDLocked(replicaID)`?

---

*[storage/replica_test.go, line 252 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA277dcqrNthXyBA8wT:-KA277dcqrNthXyBA8wU:-2653690) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/replica_test.go#L252)):*
is this saying it's weird because it doesn't call Store.start and does assign IDs or because it neither calls Store.Start nor assigns IDs?

---

*[storage/store.go, line 1678 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA28qwvjZSES06U7ZHU:-KA28qwvjZSES06U7ZHV:268033783) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/store.go#L1678)):*
drive-by, but can this be `return r, r.setReplicaID(replicaID)`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204)*

**Comment by bdarnell** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/client_raft_test.go, line 1460 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26QJyOaX8uFGGVWb8:-KA29r0zeYdvTMdFZuDf:-258443395) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/client_raft_test.go#L1460)):*
It's slightly racy in that the queue could have run by now (although it's using atomic operations internally so it's not a race in the race detector sense). It's also not really necessary: the test works just as well whether the GC queue is enabled or not. It's just an extra line of defense to make it unlikely that the replica was created and then removed via another path. 

---

*[storage/replica.go, line 182 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26vkRVdyiAW5M7CF_:-KA2BjzqZRwqMi4gmhbs:610443705) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/replica.go#L182)):*
80 (same as most of the other comments in the file). The "wrap comments at 100" guideline doesn't seem to have taken hold.  

---

*[storage/replica_test.go, line 252 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA277dcqrNthXyBA8wT:-KA2CQ_0_XlMGLZUizrA:-1732510625) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/replica_test.go#L252)):*
The latter.  Changed to "doesn't call Store.Start which would assign IDs"

---

*[storage/store.go, line 1678 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA28qwvjZSES06U7ZHU:-KA2LH11GDM54JTbVVFw:550304645) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/store.go#L1678)):*
Could be, but it would diverge from the usual pattern in which all other results are zero-valued on error.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/client_raft_test.go, line 1460 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26QJyOaX8uFGGVWb8:-KA2QOED5EADuVFuiOQy:-1280137852) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/client_raft_test.go#L1460)):*
That's even worse - that means that this could cause this test to fail to detect the failure condition it's testing for. Why not disable the GC queue at the outset?

---

*[storage/replica.go, line 234 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA2R3gaBhRXc0fZwrEX:-KA2R3gaBhRXc0fZwrEY:516622123) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bbc9190af204b0edd8e69cbf02e9462e588635/storage/replica.go#L234)):*
this could be in an `else if` below, but either way is fine

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/client_raft_test.go, line 1460 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26QJyOaX8uFGGVWb8:-KA2RVq6S_sBrxGmjBVV:-1383624983) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/client_raft_test.go#L1460)):*
Because "the outset" is not accessible; we'd have to do a larger refactoring to be able to call DisableReplicaGCQueue in between NewStore and Start. I don't think it's worth that - it's too hypothetical of a concern. I'd rather just remove this line than make it any less racy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204)*

**Comment by tamird** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/client_raft_test.go, line 1460 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26QJyOaX8uFGGVWb8:-KA2TSToAu3ulKWbYo8Z:-1097383612) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/client_raft_test.go#L1460)):*
Heh, sorry, I didn't notice the `mtc.stores[0].DisableReplicaGCQueue` at the top of this test; this already does what I wanted.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-:-KA2Tson0ovG3I1_LA9L:676834233)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/client_raft_test.go, line 1460 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-KA26QJyOaX8uFGGVWb8:-KA2UKMkTf-4C1djXkRT:1565304257) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d4b75a8223dc94de53a83d6b77c658c488ed86/storage/client_raft_test.go#L1460)):*
Yeah, that's the important one, and that one doesn't race.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204)*

**Comment by tschottdorf** [comment]
Nice, LGTM.

---

Reviewed 4 of 8 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4204#-:-KA2W-XMgO9CDDEMIASg:-308130748)*

**Pull request merged**
