### PR TITLE
workload/histogram: simplify and test prometheus histogram creation

### PR DESCRIPTION
**Pull request by tbg**
- workload/histogram: clean prometheus metric names
- workload/histogram: simplify and test prometheus histogram creation

### CODE REVIEW

**Review by otan — APPROVED** [review]
Good morning!

**Comment by tbg** [comment]
Thank you! Now go have some cereal and good night. If this fails for some reason, mind shepherding it in? You should be able to push to my branch.

bors r=otan

**Comment by otan** [comment]
aye aye capt'n

**Comment by otan** [comment]
We do need that map separate, as otherwise NamedHistogram objects die and we re-try re-creating one with the same name! I've mostly reverted that change.

**Comment by tbg** [comment]
Thanks for cleaning this up! I'm taking another pass to try to understand the way this all works and I'm pretty confused. I get that at a high level what `*Registry` wants to do is to collect a histogram and reset it on each `Tick`. But it only resets `w.mu.current`; we should be able to reliably store the promHistogram on `w` (the `*NamedHistogram`) itself; those don't have an expiration date.

Where did you observe a failure? It'd be good to simplify this yet again, I'll take a stab at that but it looks like you saw something that I didn't.

**Comment by tbg** [comment]
Well I'll see, I extended the unit test and it seems like I do understand how this works, let's see how the PR fares.

**Comment by tbg** [comment]
I think I understand the problem, but it doesn't have to do anything with the code I had written. The problem is this:

```go
func TestRegistrySameMetricFromMultipleHandles(t *testing.T) {
	r := NewRegistry(10*time.Second, "jepsen")
	const name = "foo"
	h1 := r.GetHandle()
	h2 := r.GetHandle()
	h1.Get(name).Record(time.Second)
	h2.Get(name).Record(time.Minute)
	t.Error("x")
}
```

The whole point of `r.GetHandle()` is that you get your local namespace, but since we're sharing the prom registry across handles, we get duplicates.

I thought this `GetHandle()` thing was a bit over-engineered anyway, I'm going to look if we can maybe flatten things down to use just the library and to "prevent" duplicate metrics (they wouldn't panic, just share a histogram).

**Comment by tbg** [comment]
Hmm, we do give each worker a separate handle in some places, for example here:

https://github.com/cockroachdb/cockroach/blob/a9bc350e4327ae9763398cbab79c98471b495fb6/pkg/workload/bank/bank.go#L206-L219

This does lead to multiple histograms under the same name. I do wonder what the point is though. When we actually collect the data, we smush them all together:

https://github.com/cockroachdb/cockroach/blob/50df495cb2c078a1389dde99a0c671caa33bf26f/pkg/workload/histogram/histogram.go#L192-L205

So the only difference is... possible lock contention (sharing an RLock vs not doing so across workers), but it's not externally exposed.

Since it puts us at odds with the prometheus model (to expose `Gatherer` on `*Registry` we'd need to write internal code that merges the histograms across the same name, which... no), I'll try to rip it out.

**Comment by tbg** [comment]
And now having understood all of that myself, I can see that that's exactly what you meant above @otan. :-)

**Pull request merged**
