### PR TITLE
sql: don't hand out leases for deleted tables

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6215)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 14 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[roachpb/errors.go, line 566 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFumuMjLjgglrtjWexE:-KFumuMk0Gs-KglnEgmi:338366493) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/roachpb/errors.go#L566)):*
I understand you wanting to differentiate between this error and the next one. Is there a strong reason to want to do that? Should we call this DescriptorBeingDeletedError? It's a bit more descriptive.

---

*[sql/lease.go, line 298 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFunhjqX7iCODQC6DG2:-KFunhjrauCfTY_yqJK_:1113403689) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L298)):*
want to combine this log message with the one above?

---

*[sql/lease.go, line 489 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvQ5gVvtepjDgSiZHe:-KFvQ5gVvtepjDgSiZHf:-1992598681) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a0fd2025ea4880f476f7c4781d94f2f0020364/sql/lease.go#L489)):*
I now remember why we needed this. I so might happen that a the refcount of an old version is > 0. When a new version comes along, purgeOldVersions will not purge the old version. when we decrement the refcount, it will not get purged immediately but given that there is lots of activity on the table, the acquire will purge the old version. I think the current implementation is not perfect but it is better than what you are proposing.

One thought is to leave the entire logic the way it is but only change Acquire to
either release NonLatest leases (same as now), or all leases in case it sees the delete bit. I think that's all this change entails.

---

*[sql/lease.go, line 521 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvAMptH9kaYAPYl8g3:-KFvAMpu3WtSvPiQ7zQg:-1756681291) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L521)):*
remove the must be locked comment

---

*[sql/lease.go, line 676 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvBAzJxrsLAm5h_q7Z:-KFvBAzJxrsLAm5h_q7_:-315767502) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a0fd2025ea4880f476f7c4781d94f2f0020364/sql/lease.go#L676)):*
this comment should be retained

---

*[sql/lease.go, line 727 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvAf931oES6_fKy0Fo:-KFvAf931oES6_fKy0Fp:-1363372325) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L727)):*
/* comment */ after false 

---

*[sql/lease.go, line 728 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvNcdFt7etMC9cdnF5:-KFvNcdFt7etMC9cdnF6:-896954049) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L728)):*
I think the right thing to do here is to 1. acquire and release a new lease when the table is not marked as deleted.

---

*[sql/lease_test.go, line 394 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvU8wbISih66wYwCiI:-KFvU8wbISih66wYwCiJ:-815917743) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L394)):*
just return an error man!

---

*[sql/lease_test.go, line 397 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvUdoUS4OfRTBMZPlI:-KFvUdoViyhzS_vxpKNF:-677639046) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L397)):*
how about another method for the non transaction case?

---

*[sql/lease_test.go, line 425 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvUR3Ins3VyjwpuAGx:-KFvUR3Ins3VyjwpuAGy:-145751005) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L425)):*
why a transaction? 

---

*[sql/lease_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvV2DoiniCAWuYfnaF:-KFvV2DoiniCAWuYfnaG:1992398352) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L446)):*
is this comment relevant?

---

*[sql/table.go, line 356 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvVXGOXOvnV-YZ7CqE:-KFvVXGOXOvnV-YZ7CqF:-1011692413) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/table.go#L356)):*
Wanna file an issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215)*

**Comment by andreimatei** [comment]
Review status: 0 of 14 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[roachpb/errors.go, line 566 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFumuMjLjgglrtjWexE:-KFzl6AS_-LyhAW1zyk0:125964733) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/roachpb/errors.go#L566)):*
Well the reason why I thought I'd keep them separate is that one of them (`DescriptorDeletedError`) is something thrown by one particular function (one of the `Acquire`s), and the catcher can pretty much rely on the fact that it refers to the table it was trying to acquire.
The other one, `NotFound` can in theory come from anywhere and refer to anything - it could be an error a node got over the network from a lower-level KV  operation it was doing.

But listen all this is bullshit. These shouldn't be `ErrorDetails`, they shouldn't be in this proto at all. And if they wouldn't be in this proto we probably would indeed not need both of them, and even if still do, they'd be declared in different parts of the code, with different scopes. So I've had it with these ErrorDetails for upper layers like sql, and I've gone on a little rampage in the PR below. Let's see what happens there and reconvene.
https://github.com/cockroachdb/cockroach/pull/6251

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215)*

**Comment by andreimatei** [comment]
Review status: 0 of 14 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[sql/lease.go, line 298 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFunhjqX7iCODQC6DG2:-KFzyr-5-WLGZFQ1zhgM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L298)):*
Done.

---

*[sql/lease.go, line 489 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvQ5gVvtepjDgSiZHe:-KG--jqzFSETM_anV5k8:986552904) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a0fd2025ea4880f476f7c4781d94f2f0020364/sql/lease.go#L489)):*
currently it looks like we would be releasing the lease of the old version when its refcount gets to 0 (line 569). There's a TODO in there about maybe allowing for a grace period before that happens, but in any case the lease for an old should be release soon after it's not in use...

---

*[sql/lease.go, line 521 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvAMptH9kaYAPYl8g3:-KG-0QQsFZL_Ns0QQi0S:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L521)):*
Done.

---

*[sql/lease.go, line 676 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvBAzJxrsLAm5h_q7Z:-KG-0uKkEFf5iEhetkKJ:-1489410284) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a0fd2025ea4880f476f7c4781d94f2f0020364/sql/lease.go#L676)):*
there's a function comment at `purgeOldLeases` that says `// If t has no active leases, nothing is done.`

---

*[sql/lease.go, line 727 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvAf931oES6_fKy0Fo:-KG-0Z2J3CGjYR6UvwNI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L727)):*
Done.

---

*[sql/lease.go, line 728 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvNcdFt7etMC9cdnF5:-KG-1NXXnBGxzJYJlZm7:1388399080) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease.go#L728)):*
isn't that what `purgeOldLeases` does?

---

*[sql/lease_test.go, line 394 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvU8wbISih66wYwCiI:-KG-1emWRZMfQy5TKHuz:1113052308) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L394)):*
these function will go away with the next PR when this test will just do a `DROP` instead as manually setting this `deleted` bit.

---

*[sql/lease_test.go, line 397 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvUdoUS4OfRTBMZPlI:-KG-1uAwTCalm-vu5icg:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L397)):*
ditto

---

*[sql/lease_test.go, line 425 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvUR3Ins3VyjwpuAGx:-KG-1wZLuPwNwuCW5WlS:2069718130) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L425)):*
true. But will go away.

---

*[sql/lease_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvV2DoiniCAWuYfnaF:-KG-279vs2BZltg1Zjha:2032769766) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L446)):*
yes, I believe it is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215)*

**Comment by RaduBerinde** [comment]
LGTM, though I don't claim to understand the table lease stuff in detail.

---

Reviewed 2 of 6 files at r1, 11 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[sql/lease.go, line 499 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-gS9yN4hHl1xDrHA8:-KG-gS9zI1Vt0w-wQgrx:-389065535) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L499)):*
releaseLeasesIfNotActive

---

*[sql/lease.go, line 586 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-h7XL07ckWR4qqHcr:-KG-h7XL07ckWR4qqHcs:-1873782367) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L586)):*
`) error {` on separate line

---

*[sql/lease.go, line 588 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-hDgVkz3LMS3whKTz:-KG-hDgVkz3LMS3whKU-:-1277959556) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L588)):*
why a function? just do `t.muLock(); empty := (len(t.active.data) == 0); t.muUnlock()`..

---

*[sql/lease.go, line 601 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-hxI_x2JbxGDRm4HM:-KG-hxI_x2JbxGDRm4HN:2145315725) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L601)):*
move the `if` after, no point making the entire if span so many linesn

---

*[sql/lease.go, line 668 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-isqSHcozgtxU2YSH:-KG-isqSHcozgtxU2YSI:1193033496) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L668)):*
"with the current" shows up twice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-:-KG-jVdIpobhMcZ7DVpg:-748544619)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[sql/lease.go, line 489 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvQ5gVvtepjDgSiZHe:-KGA1gPKl8pV7aE1ydnl:59528685) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a0fd2025ea4880f476f7c4781d94f2f0020364/sql/lease.go#L489)):*
We still have this one issue wherein once the table is marked as deleted, if the older leases have refcount > 0, they will not be released when the refcount is zeor because a new lease is not found  in the code on line 569.

Perhaps what we should do is this:
1. Add a new deleted bit to the struct.
2. When we acquire a new lease on success mark all old leases as deleted.
3. if the table is deleted, mark all old leases as deleted.
4. When the refcount goes to zero only a lease marked as deleted is purged.

---

*[sql/lease.go, line 617 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGA-MEGasnbe0qCiDog:-KGA-MEGasnbe0qCiDoh:31311233) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L617)):*
Let's get rid of releaseNonLatest()

if  _, deleted := pErr.GetDetail().(*roachpb.DescriptorDeletedError); deleted || pErr == nil {
   // release older leases
   t.mu.Lock()
   oldLeases := t.active.data
   if !deleted {
      // keep the latest one.
      oldLeases := t.active.data[len(t.active.data) - 1]
   }
   if err := t.releaseLeasesIfNotActive(oldLeases, store); err != nil {
				log.Warning(err)
	}
   t.mu.Unlock()
} 

---

*[sql/lease_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvV2DoiniCAWuYfnaF:-KGA3fVh7kbS52N5L8cQ:1527584135) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L446)):*
Does the client of this code use Acquire() or acquire()? Just use the one that they would use. Also looking at the test I don't believe there should be an outstanding lease for this table. Perhaps a better mechanism is use minVersion here which you can pick up from the descriptor you read above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[sql/lease.go, line 489 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvQ5gVvtepjDgSiZHe:-KGFBJR2jg4eX65pbrwN:854531262) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a0fd2025ea4880f476f7c4781d94f2f0020364/sql/lease.go#L489)):*
valid, good catch. Instead of what you suggest, I've added a `deleted` bit to the `tableState`, which makes leases be released quicker. Added a test for it too.

---

*[sql/lease.go, line 499 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-gS9yN4hHl1xDrHA8:-KGFNmJiCoyelCUs1Zh5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L499)):*
Done.

---

*[sql/lease.go, line 586 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-h7XL07ckWR4qqHcr:-KGFNornNBSBKbtZAAUQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L586)):*
Done.

---

*[sql/lease.go, line 588 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-hDgVkz3LMS3whKTz:-KGFMp4MaIFncTGr9tAk:553973925) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L588)):*
much of this function is copy-pasta, but this also bothered me. done.

---

*[sql/lease.go, line 601 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-hxI_x2JbxGDRm4HM:-KGFMKLX4Y-LwcL97yfj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L601)):*
Done.

---

*[sql/lease.go, line 617 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGA-MEGasnbe0qCiDog:-KGFM9BnGrNJipdX5Zgh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L617)):*
Done.

---

*[sql/lease.go, line 668 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KG-isqSHcozgtxU2YSH:-KGFMzbLBRnjjftCFjfB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2244dd85594408e2b8b0b49dd97235098b90c9/sql/lease.go#L668)):*
Done.

---

*[sql/lease_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KFvV2DoiniCAWuYfnaF:-KGFN_1kBJGKrf-PPLP0:512241078) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a950ca3c41dd3d2b8559aa7fbcc8f002c28024/sql/lease_test.go#L446)):*
good idea with the minVersion. done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215)*

**Comment by vivekmenezes** [comment]
I think you need to push your changes

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-:-KGFX8A30OsqRpXFc2KF:1043074134)*

**Comment by andreimatei** [comment]
oops sorry

---

Review status: 12 of 18 files reviewed at latest revision, 14 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-:-KGFY3Hg2rwJD6NHxhez:1404670629)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 12 of 18 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[server/testserver.go, line 198 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI04NlQna93Hj80i1q:-KGI04NlQna93Hj80i1r:-741260306) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/server/testserver.go#L198)):*
Is it hard to just capitialize it to LeaseMgr?

---

*[sql/lease.go, line 607 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI2veYlx4xtM_g7_Ps:-KGI2rcfFI43RjSn3JwR:500824566) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease.go#L607)):*
just assign it to  t.active.data so that you don't need to declare it.

---

*[sql/lease.go, line 617 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI3qD1lj9KZOAtq8Op:-KGI3qD1lj9KZOAtq8Oq:1819864257) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease.go#L617)):*
I suppose you could also just return the error

---

*[sql/lease_test.go, line 487 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI5168qDXFdf95Hiph:-KGI5168qDXFdf95Hipi:688720122) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease_test.go#L487)):*
deleted := make(chan bool)

---

*[sql/lease_test.go, line 494 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI5DX3UVZ25lK4ksDp:-KGI5DX3UVZ25lK4ksDq:830758886) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease_test.go#L494)):*
no need to send a value. Just close it

---

*[sql/lease_test.go, line 534 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI5dmTglgxPlcnWn4L:-KGI5dmTglgxPlcnWn4M:-1147760630) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease_test.go#L534)):*
nit: Fatal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-:-KGI7obAukmCtZ1FxCnC:1417088721)*

**Comment by andreimatei** [comment]
Review status: 12 of 18 files reviewed at latest revision, 19 unresolved discussions, some commit checks pending.

---

*[server/testserver.go, line 198 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI04NlQna93Hj80i1q:-KGIEIhDo7jMAtfQNdb6:-242648478) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/server/testserver.go#L198)):*
well there's already a lot of precedent in this class for exposing private fields.
Plus... I like private fields, keeps people from using it :)

---

*[sql/lease.go, line 607 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI2veYlx4xtM_g7_Ps:-KGIE7X_qRDgB0i8Gzbm:596999762) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease.go#L607)):*
I like it better this way, gives better structure to the comments

---

*[sql/lease.go, line 617 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI3qD1lj9KZOAtq8Op:-KGIE5nhS-zf_a4O6DjR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease.go#L617)):*
Done.

---

*[sql/lease_test.go, line 487 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI5168qDXFdf95Hiph:-KGIC0cze3W9psUiPUn9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease_test.go#L487)):*
Done.

---

*[sql/lease_test.go, line 494 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI5DX3UVZ25lK4ksDp:-KGIC19Xx4-Ir_zCDYTC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease_test.go#L494)):*
Done.

---

*[sql/lease_test.go, line 534 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215#-KGI5dmTglgxPlcnWn4L:-KGIBsSesj6AuSyqpnLM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebca3532a451739324abb435e02d0a653a9f68a1/sql/lease_test.go#L534)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6215)*

**Pull request merged**
