### PR TITLE
cli: add --cert-principal-map to `cert list` command

### LINKED ISSUE #48011: cli: `cert list` needs to be provided `--cert-principal-map`
The `cert list` command lists and validates the certs in the `--certs-dir` directory. This validation currently fails if a cert exists there which requires `--cert-principal-map` to be valid.

### PR DESCRIPTION
**Pull request by petermattis**
Remove the use of `base.Config.GetCertificateManager()` from the `cert 
list` implementation as a first step in limiting use of that method, and 
possibly removing it in the future.

Fixes #48011

Release note (cli change): Support `list cert` with certificates which 
require `--cert-principal-map` to pass validation.

### CODE REVIEW

**Comment by petermattis** [comment]
This is an intermediate step towards moving `Config.GetCertificateManager()` to a more server-specific bit of code, and generally providing a cleaner separation between client cert handling and server cert handling. I don't quite have the plan for how that will be achieved as this stuff is all intricately woven together right now.

**Review by knz — APPROVED** [review]
LGTM modulo the default initialization

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48013#-:-M5gF_y14NXSmqC5lBFB:b-3eebwv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @petermattis)

___
*[pkg/cli/context.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48013#-M5gF14oAKAWOB-a8eVD:-M5gF14p--igmp-tM-tb:bxuamjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/300d20a116712ad5e3c9100a8b78d5f3a6c21edc/pkg/cli/context.go#L400)):*
> ```Go
> // Defaults set by InitCLIDefaults() above.
> var certCtx struct {
> 	certPrincipalMap []string
> ```

you should reset this at the top in `initCLIDefaults()`
___
*[pkg/server/server.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48013#-M5gFVdE09x_5S90gCKz:-M5gFVdE09x_5S90gCL-:b-mgbznj) ([raw file](https://github.com/cockroachdb/cockroach/blob/40d5cc1760457a99f11b5a89bccf9077627bcc09/pkg/server/server.go#L206)):*
> ```Go
> 
> 	// Attempt to load TLS configs right away, failures are permanent.
> 	if !cfg.Insecure {
> ```

I think this change makes this PR fix #17194 - WDYT?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48013)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @knz)

___
*[pkg/cli/context.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48013#-M5gF14oAKAWOB-a8eVD:-M5gbMtA8DedXiLVODo9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/300d20a116712ad5e3c9100a8b78d5f3a6c21edc/pkg/cli/context.go#L400)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you should reset this at the top in `initCLIDefaults()`
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48013#-M5gFVdE09x_5S90gCKz:-M5gbQdz78Bxp6ajOE2x:b-ogjc5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/40d5cc1760457a99f11b5a89bccf9077627bcc09/pkg/server/server.go#L206)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this change makes this PR fix #17194 - WDYT?
</blockquote></details>

I'm not seeing why this PR would fix #17194. The code here is intended to be identical to what was previously being done. Note that `InitializeNodeTLSConfigs` already had a `if cfg.Insecure` check. Am I missing something? I'm not actually sure what the problem is in #17194.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48013)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @petermattis)

___
*[pkg/server/server.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48013#-M5gFVdE09x_5S90gCKz:-M5h86UN1TfVPbv7gxVc:b7o6vuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/40d5cc1760457a99f11b5a89bccf9077627bcc09/pkg/server/server.go#L206)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not seeing why this PR would fix #17194. The code here is intended to be identical to what was previously being done. Note that `InitializeNodeTLSConfigs` already had a `if cfg.Insecure` check. Am I missing something? I'm not actually sure what the problem is in #17194.
</blockquote></details>

Yes sorry I misread the call point.

The problem in #17194 is that the node certs should be checked to include the listen addr upon startup, not merely when another node tries to join. But I agree it's unrelated here.

**Comment by petermattis** [comment]
TFTR!

bors r+

**Pull request merged**
