### PR TITLE
clusterversion: remove deprecated internal versions

### PR DESCRIPTION
**Pull request by RaduBerinde**
Remove deprecated 23.2 gates - these features will always be enabled
in any cluster that a 24.2 node is part of.

`TODODelete_V23_1` has a lot of uses and will be removed separately.

Epic: none
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: for the storage changes

> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124013#-:-NxxeEfh4Dep3h0cwUqY:b-r1zanr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @celiala, @rail, and @wenyihu6)

**Review by celiala — APPROVED** [review]
Thank you :lgtm: 

> Reviewed 14 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124013#-:-Nxxh1v22cIy7Oa0hrWO:buxrqzc)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @abarganier, @rail, and @wenyihu6)

**Review by wenyihu6 — COMMENTED** [review]
:lgtm: for the cdc changes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124013#-:-NxxiQrr8P7QlAPshxzo:br451f4)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @abarganier and @rail)

**Review by wenyihu6 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124013#-:-NxxiUIf1zRRvowKOUjb:bnfp4nl)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @abarganier and @rail)

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124013#-:-Nxxn2NsEqgfmvtpyI4x:b-tlx7ko)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @abarganier and @rail)

**Pull request merged**
