### PR TITLE
kvserver/batcheval: fix mvcc stats computaion on split

### LINKED ISSUE #102410: kv/kvnemesis: TestKVNemesisSingleNode failed
kv/kvnemesis.TestKVNemesisSingleNode [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9828507?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9828507?buildTab=artifacts#/) on master @ [5b44c4fd6d97dc3a75e786fed24f47ad8bcf9039](https://github.com/cockroachdb/cockroach/commits/5b44c4fd6d97dc3a75e786fed24f47ad8bcf9039):

```
=== RUN   TestKVNemesisSingleNode
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisSingleNode2646109487
    test_log_scope.go:79: use -show-logs to present logs inline
    kvnemesis_test.go:180: seed: 9116470825307397985
    kvnemesis_test.go:124: kvnemesis logging to /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis85842970
    kvnemesis.go:165: range 113 (/Table/100/"8202395e8dbe1792") RANGE_CONSISTENT_STATS_INCORRECT:
        stats: {ContainsEstimates:0 LastUpdateNanos:1682591416804502043 IntentAge:0 GCBytesAge:86808 LiveBytes:2703 LiveCount:51 KeyBytes:8526 KeyCount:186 ValBytes:5845 ValCount:385 IntentBytes:0 IntentCount:0 SeparatedIntentCount:0 RangeKeyCount:9 RangeKeyBytes:468 RangeValCount:10 RangeValBytes:107 SysBytes:6491 SysCount:37 AbortSpanBytes:1810}
        delta (stats-computed): {ContainsEstimates:0 LastUpdateNanos:1682591416804502043 IntentAge:0 GCBytesAge:0 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 SeparatedIntentCount:0 RangeKeyCount:0 RangeKeyBytes:0 RangeValCount:0 RangeValBytes:0 SysBytes:-6 SysCount:0 AbortSpanBytes:0}
    kvnemesis.go:185: failures(verbose): /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis85842970/failures
        repro steps: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis85842970/repro.go
        rangefeed KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis85842970/kvs-rangefeed.txt
        scan KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis85842970/kvs-scan.txt
    kvnemesis_test.go:207: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:207
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:148
        	Error:      	Should be zero, but was 1
        	Test:       	TestKVNemesisSingleNode
        	Messages:   	kvnemesis detected failures
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisSingleNode2646109487
--- FAIL: TestKVNemesisSingleNode (22.58s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisSingleNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27429

Epic CRDB-27234

### PR DESCRIPTION
**Pull request by aliher1911**
Previouly split trigger was using in-memory copy of mvccstats from replica. This value could diverge from store snapshot used by request in special cases of lease extensions that don't hold latches.
This was causing stats for the replica to diverge. This PR changes base stats to be read from request reader which provides consistent stats value with content of splitted ranges.

Touches: #101721
Fixes: #102410

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> This value could diverge from store snapshot used by request in special cases of lease extensions that don't hold latches.

How does reading from the engine instead of from the in-memory stats avoid a race in this situation? Either way, couldn't the stats source used by the EndTxn(trigger=Split) be concurrently updated by a lease extension on the pre-split range?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-:-NW3YjU63of9EhK-aJ3l:bwxnf4q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by aliher1911 — COMMENTED** [review]
Isn't batch providing us consistent view here when we perform a request? The original failure was giving us old lease value from storage but new mvcc stats from replica itself. Maybe we just move those two events closer together now and shrink the window when we are exposed to inconsistency. The failure is only causing inconsistency between stats and data, but no other visible effects.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-:-NW3c3sV7WyeYc2Pdhb6:bydjy55)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by nvb — COMMENTED** [review]
I see, so this is not attempting to avoid the unsynchronized race between the split trigger and the lease extension, it's just ensuring that the split trigger observes MVCC stats that are consistent with the engine snapshot that it will recompute stats over. The commutativity of stats deltas will resolve any race on the LHS range's lease. That makes sense.

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-:-NW3fePFC_m6FmQV9Q9n:b-1twkrk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-NW3fxLb4SmRoogek95B:-NW3fxLb4SmRoogek95C:b-10rslf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e405aa8c459be6038ad31ab0bd06b900e2330f2/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L1017)):*
> ```Go
> 	// Retrieve MVCC Stats from the current batch instead of using stats from
> 	// execution context. Stats in the context could diverge from storage snapshot
> 	// of current request when lease extensions are applied. We must not write
> ```

We should mention that lease extensions do not acquire latches and so they can race with this splitTrigger.
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 1019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-NW3gwdgCcpPVYssKkiF:-NW3gwdgCcpPVYssKkiG:b-j0tgll) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e405aa8c459be6038ad31ab0bd06b900e2330f2/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L1019)):*
> ```Go
> 	// of current request when lease extensions are applied. We must not write
> 	// absolute stats values for LHS based on this value, always produce a delta
> 	// since underlying stats in storage could change.
> ```

Let's mention why it is ok to write absolute stats values for the RHS based on this value.
___
*[`pkg/kv/kvserver/batcheval/split_stats_helper.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-NW3gOBQE7S8y4oSifSB:-NW3gOBQE7S8y4oSifSC:b-z0aa71) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34c137004f111b915fb346da9a4770264d6c22f/pkg/kv/kvserver/batcheval/split_stats_helper.go#L116)):*
> ```Go
> }
> 
> // splitStatsScanFn scans a post-split keyspace to compute its stats. The
> ```

Why remove this comment?

**Review by aliher1911 — COMMENTED** [review]
Yeah, I don't think synchronizing is important here. RHS will get "old" lease, but then it would be extended after the split by new leaseholder. And we don't overwrite LHS lease so it would be preserved.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-:-NW3k1Ku8Ixh7DU4k73R:bi48ye8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/batcheval/split_stats_helper.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-NW3gOBQE7S8y4oSifSB:-NW3ii5M34QK31sinEHk:b-pghm97) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34c137004f111b915fb346da9a4770264d6c22f/pkg/kv/kvserver/batcheval/split_stats_helper.go#L116)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why remove this comment?
</blockquote></details>

I think this comment is redundant as the function type itself shows its purpose. It isn't specific on how stats are retrieved. What happened in the code, we had two fields of this type each saying they are left and right sides, but the fact that they actually do scan is completely hidden outside of the type. So I changed type name to reflect that it retrieves stats and names of fields to indicate that those are scans.
I was actually thinking of making stats field to be a function to retrieve stats from storage, but in the end made it just retrieve the value in the beginning.
But the rename itself made sense to me as it looked easier to read.
I can revert that if you think it is not true and only keep stats retrieval hunk and relevant comments on justifications.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-:-NW86Q4ZE4E-jJiUNClE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/batcheval/split_stats_helper.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103719#-NW3gOBQE7S8y4oSifSB:-NW85bh1Ap-hDUdpVYr7:b-fig0ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34c137004f111b915fb346da9a4770264d6c22f/pkg/kv/kvserver/batcheval/split_stats_helper.go#L116)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think this comment is redundant as the function type itself shows its purpose. It isn't specific on how stats are retrieved. What happened in the code, we had two fields of this type each saying they are left and right sides, but the fact that they actually do scan is completely hidden outside of the type. So I changed type name to reflect that it retrieves stats and names of fields to indicate that those are scans.
I was actually thinking of making stats field to be a function to retrieve stats from storage, but in the end made it just retrieve the value in the beginning.
But the rename itself made sense to me as it looked easier to read.
I can revert that if you think it is not true and only keep stats retrieval hunk and relevant comments on justifications.
</blockquote></details>

I'd be in favor of a revert, specifically for the comment on and name of this type. You're right that the comment and name don't strictly need to be specific to the `splitStatsHelper` and that this can all be more abstract, but I also don't think they are detracting from clarity. This logic is all so tightly entwined that the more commentary about how the pieces all fit together, the better.

**Comment by aliher1911** [comment]
Thanks for the feedback!

bors r=nvanbenschoten

**Comment by aliher1911** [comment]
bors r=nvanbenschoten

**Comment by erikgrinaker** [comment]
I like this approach. I resolved a similar race during merges in #99017, but did so only by reducing the race window, so it's still technically racey. Would it be possible to apply the same approach there?

**Comment by aliher1911** [comment]
I need to look in more detail if we rely on the absolute value vs delta of written state when doing merge. Superficially we should be able to use the same approach as writes to RHS lease should be thrown away and writes to LHS lease would persist and we can add RHS delta for remaining.

**Pull request merged**
