### PR TITLE
make TODO checkbox'ed

### PR DESCRIPTION
**Pull request by funkygao**

### CODE REVIEW

**Comment by petermattis** [comment]
Can you provide a bit of justification for this change? We usually just remove entries from the TODO list when they are completed. Alternately, we should probably start using github issues for some of these items.

**Comment by funkygao** [comment]
I thought that TODO's can be tracked in history. I thought when a TODO entry was done, just check the checkbox so that we can review all the TODO's in history.
If that's not cockroachdb's TODO purpose, please help to skip this commit.
thanks

**Comment by petermattis** [comment]
The TODO file has historically not been used as you describe. The TODO file is intended as a light-weight place to keep track of issues, but it really shouldn't evolve into being an issue tracker. If we want to keep track of history we should really be using an issue tracker (like github issues).

**Comment by tschottdorf** [comment]
Thanks @funkygao, but it looks like we don't need this at this point.

**Pull request closed without merging**
