### PR TITLE
roachtest: misc fixes

### LINKED ISSUE #36596: roachtest: acceptance/cli/node-status failed
SHA: https://github.com/cockroachdb/cockroach/commits/6da68d7fe2c9a29b85e2ec0c7e545a0d6bdc4c5c

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=acceptance/cli/node-status PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1226521&tab=buildLog

```
The test failed on release-19.1:
	cli.go:79,cli.go:113,acceptance.go:78,test.go:1237: expected [is_available is_live true true true true false false], but found [is_available is_live true true true true false false true true]:
	cluster.go:953,context.go:90,cluster.go:942,asm_amd64.s:522,panic.go:397,test.go:785,test.go:775,cli.go:79,cli.go:113,acceptance.go:78,test.go:1237: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1226521-acceptance --oneshot --ignore-empty-nodes: exit status 1 1: 8592
		2: 7410
		3: dead
		4: 5945
		Error:  3: dead

```

### LINKED ISSUE #36978: roachtest: backup2TB/n10cpu4 failed
SHA: https://github.com/cockroachdb/cockroach/commits/df200cbf3f407dbf349aa601ff9036b4dff88e83

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=backup2TB/n10cpu4 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1252822&tab=buildLog

```
The test failed on release-2.1:
	cluster.go:1329,backup.go:45,test.go:1237: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1252822-backup2tb-n10cpu4:1 -- ./workload fixtures import bank --db=bank --payload-bytes=10240 --ranges=0 --rows=65104166 --seed=1 {pgurl:1} returned:
		stderr:
		
		stdout:
		I190421 06:06:17.726391 1 ccl/workloadccl/cliccl/fixtures.go:325  starting import of 1 tables
		I190421 06:06:17.818378 9 ccl/workloadccl/fixture.go:517  imported bank (0s, 0 rows, 0 index entries, 0 B)
		Error: importing fixture: importing table bank: pq: unsupported storage scheme: "experimental-workload"
		Error:  exit status 1
		: exit status 1

```

### PR DESCRIPTION
**Pull request by tbg**
roachtest: run backup test on 19.1 and upwards only

Fixes #36978.

roachtest: really skip version-upgrade on 2.1 (via hack)

The hack is necessary since subtests silently ignore the MinVersion field.

See #36752.

acceptance: add debugging to acceptance/cli/node-status

Closes #36596.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37032)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @tbg)

___
*[pkg/cmd/roachtest/acceptance.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37032#-Ld9pJ1Q9x-WeTviVjNO:-Ld9pJ1R3usCZU_EYYAu:bfzagzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/156e2fe1b2f493159464a0e42f66f6c8f3bc7e38/pkg/cmd/roachtest/acceptance.go#L34)):*
> ```Go
> 		fn   func(ctx context.Context, t *test, c *cluster)
> 		skip string
> 		// roachtest needs to be taught about MinVersion for subtests.
> ```

Add `TODO(bobvawter)`. I don't think this is particularly difficult to do.
___
*[pkg/cmd/roachtest/backup.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37032#-Ld9pzKT658WSNsek6X2:-Ld9pzKT658WSNsek6X3:b-whbbq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/11ce2737d6fa60dd74fcc3598288063663505ecc/pkg/cmd/roachtest/backup.go#L33)):*
> ```Go
> 		Name:       fmt.Sprintf("backup2TB/%s", backup2TBSpec),
> 		Cluster:    backup2TBSpec,
> 		MinVersion: "v19.1.0",
> ```

I looked in https://github.com/cockroachdb/cockroach/issues/36978, but didn't see a reason this test can only run on `19.1`. What obvious thing am I missing?

**Review by tbg — COMMENTED** [review]
TFTR, I'll follow up on the backup test on 2.1.

bors r=petermattis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37032#-:-LdDXm145iHhI3Hzl0hf:blyelrq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @petermattis)

___
*[pkg/cmd/roachtest/acceptance.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37032#-Ld9pJ1Q9x-WeTviVjNO:-LdDX1nK8nvUshq-4Cby:b-7slvmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/156e2fe1b2f493159464a0e42f66f6c8f3bc7e38/pkg/cmd/roachtest/acceptance.go#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Add `TODO(bobvawter)`. I don't think this is particularly difficult to do.
</blockquote></details>

The issue is assigned to him. I mention there to remove this hack.
___
*[pkg/cmd/roachtest/backup.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37032#-Ld9pzKT658WSNsek6X2:-LdDXNX0EPlapar8Vb_n:b-1wlqi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/11ce2737d6fa60dd74fcc3598288063663505ecc/pkg/cmd/roachtest/backup.go#L33)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I looked in https://github.com/cockroachdb/cockroach/issues/36978, but didn't see a reason this test can only run on `19.1`. What obvious thing am I missing?
</blockquote></details>

pq: unsupported storage scheme: "experimental-workload"

@danhhz I searched Slack for the incantation to use the csv server, but found nothing that I didn't think I'd have to tinker with, mind reminding me of the right thing to do here so that we can keep this test on 2.1?

**Comment by tbg** [comment]
bors r=petermattis

OOM in TestVet

Using https://github.com/cockroachdb/cockroach/issues/37061 to track.

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/37066

bors r=petermattis

**Comment by tbg** [comment]
Sigh... another new one, https://github.com/cockroachdb/cockroach/issues/37073

Will this PR find all the flakes? Let's find out

bors r=petermattis

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37032)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/cmd/roachtest/backup.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37032#-Ld9pzKT658WSNsek6X2:-LdEou0m5g4L6jLrkndp:b-iwslr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/11ce2737d6fa60dd74fcc3598288063663505ecc/pkg/cmd/roachtest/backup.go#L33)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

pq: unsupported storage scheme: "experimental-workload"

@danhhz I searched Slack for the incantation to use the csv server, but found nothing that I didn't think I'd have to tinker with, mind reminding me of the right thing to do here so that we can keep this test on 2.1?
</blockquote></details>

I went to write this up, but it looks like the --csv-server arg was only ever hooked up to `fixtures make` and not to `fixtures import`. :man_facepalming: PR incoming

Once that's merged, this should work:
```
roachprod run cluster -- "./workload csv-server --port=8081 &> logs/workload-csv-server.log < /dev/null &"
roachprod run cluster:1 -- "./workload fixtures import tpcc --csv-server=http://localhost:8081"
```

**Pull request merged**
