### PR TITLE
opt: Create separate norm package for normalization rules

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains two commits. The first moves files to the new norm directory, and the second updates them to create the new package.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

I think `opt/README.md` could use some updating.

**Comment by RaduBerinde** [comment]
[nit] It's a bit confusing that `onRuleMatch` and `OnRuleMatch` are named the same, I'd rename the latter to `SetOnRuleMatch`

**Comment by RaduBerinde** [comment]
AFAICT `xform/testdata/rules/scan` is not being run anywhere. Maybe we should have a single test and automatically make subtests for each subdir in `testdata`

**Comment by andy-kimball** [comment]
I updated `opt/README.cmd`. I also changed name of `OnRuleMatch`. And I consolidated the various optimizer tests into one `TestOptimizer` test.

---

Review status: 11 of 56 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/xform/optimizer.go, line 76 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24312#-L8mG857BcCDjW1JJya9:-L8mIohYDw0MW5WWbG9J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac837e16a5d574f9803ddd0f0bca68ed8ab7a74d/pkg/sql/opt/xform/optimizer.go#L76)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] normalizer -> normalize
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24312#-:-L8mEXY17S0HUzTji_M3:bvqptkf)*

**Comment by rytaft** [comment]
Reviewed 45 of 51 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24312)*

**Comment by RaduBerinde** [comment]
Reviewed 30 of 58 files at r1, 45 of 51 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/opt/xform/optimizer_test.go, line 27 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24312#-L8mNwdp2LY4KGebFlBn:-L8mNwdp2LY4KGebFlBo:b-ph6g6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e486838772fc3af7841d2df79b5916b4997259d7/pkg/sql/opt/xform/optimizer_test.go#L27)):*
> ```Go
> 
> // TestOptimizer files can be run separately like this:
> //   make test PKG=./pkg/sql/opt/xform TESTS="coster/scan"
> ```

[nit] How would these work? AFAICT runDataDrivenTest takes only the last part of the path. Even if it did that, they would have to be `/coster/scan` or `TestOptimizer/coster/scan`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24312)*

**Pull request merged**
