### PR TITLE
sql: Add support for pgwire flush clientMessageType

### LINKED ISSUE #4549: sql/pgwire: responses to commands should be coalesced
Noticed while comparing pg and cockroach network traces, e.g. in https://github.com/cockroachdb/cockroach/issues/4538#issuecomment-186655930 

The responses to a combined command packet are sent as separate/individual packets by cockroach, whereas pg keeps the responses combined. The extra packets mean more network traffic / overhead.

Responses should be coalesced for performance.

### LINKED ISSUE #5739: sql: Support pgwire flush clientMessageType
The [node.js Postgres driver](https://github.com/brianc/node-postgres) expects support for the [flush](https://github.com/brianc/node-postgres/blob/eabbebaea8dc9140547b1c662b7f6999b559e276/lib/connection.js#L286) client message. Adding support for this would enable placeholder support for the driver when talking to CockroachDB.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #5739.
Fixes #4549.

This enables placeholder support for the node.js driver when talking to
CockroachDB.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5740)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire/v3.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8OJhXCIdzAmPwZrUP:-KE8OJhXCIdzAmPwZrUQ:631408740) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b85ca73c138bd64e4dcd951d271eb96991d643/sql/pgwire/v3.go#L243)):*
per http://www.postgresql.org/docs/current/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY:

> A Flush must be sent after any extended-query command except Sync, if the frontend wishes to examine the results of that command before issuing more commands.

so this flush should move up into the `if !c.doingExtendedQueryMessage {` block above, and then flush needs to be not a no-op.

be sure to update the comment on _this_ flush call when you move it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire/v3.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8OJhXCIdzAmPwZrUP:-KE8OzV7g5SnAoG1WfJI:-411471889) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b85ca73c138bd64e4dcd951d271eb96991d643/sql/pgwire/v3.go#L243)):*
If this moves, it might solve #4549. But if none of the languages we've tested with so far issue Flush commands, then we need to be careful we're still flushing often enough even without explicit commands.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire/v3.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8OJhXCIdzAmPwZrUP:-KE8R4LEom3VU6yKdb4d:180934681) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b85ca73c138bd64e4dcd951d271eb96991d643/sql/pgwire/v3.go#L243)):*
if none of the languages we've tested so far issue explicit flushes, and our tests continue to pass, doesn't that mean that we _are_ flushing often enough?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire/v3.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8OJhXCIdzAmPwZrUP:-KE8Rb4RbYNqCpfqkalG:2080016534) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b85ca73c138bd64e4dcd951d271eb96991d643/sql/pgwire/v3.go#L243)):*
We are now; we need to ensure that we continue to do so if this moves.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire/v3.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8OJhXCIdzAmPwZrUP:-KE8Rv9ty2_be3LCHk41:-1742101363) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b85ca73c138bd64e4dcd951d271eb96991d643/sql/pgwire/v3.go#L243)):*
I understand - what I mean is: if this moves and tests continue to pass, we are good to go.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/pgwire/v3.go, line 243 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8OJhXCIdzAmPwZrUP:-KE8VO9IyC9uBNNAl5fr:-2007887632) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b85ca73c138bd64e4dcd951d271eb96991d643/sql/pgwire/v3.go#L243)):*
Yeah it seems like as long as we flush on client connection finish when not given an explicit flush command for extended queries, we should be good, as that's all the spec guarantees. Waiting on the acceptance tests to anecdotally confirm.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire/v3.go, line 240 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8WhSX_rHS98uC1xA8:-KE8WhSYfA_aNtjuTldX:-358419243) ([raw file](https://github.com/cockroachdb/cockroach/blob/67796f0be4c494d262240b98f32c6e44c309f476/sql/pgwire/v3.go#L240)):*
this old comment is irrelevant - ignoring messages only happens in extended query mode.

---

*[sql/pgwire/v3.go, line 241 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8WpLAzkOngYxdtve2:-KE8WpLAzkOngYxdtve3:715410059) ([raw file](https://github.com/cockroachdb/cockroach/blob/67796f0be4c494d262240b98f32c6e44c309f476/sql/pgwire/v3.go#L241)):*
why not reference the postgres docs?

---

*[sql/pgwire/v3.go, line 296 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8WrujL8uUgW8pu39O:-KE8WrujL8uUgW8pu39P:348592676) ([raw file](https://github.com/cockroachdb/cockroach/blob/67796f0be4c494d262240b98f32c6e44c309f476/sql/pgwire/v3.go#L296)):*
this ain't right, is it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by nvanbenschoten** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire/v3.go, line 240 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8WhSX_rHS98uC1xA8:-KE8bWp4dzz8mBtqYPWb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/67796f0be4c494d262240b98f32c6e44c309f476/sql/pgwire/v3.go#L240)):*
Done.

---

*[sql/pgwire/v3.go, line 241 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8WpLAzkOngYxdtve2:-KE8bX5SmjnFrDwdixMQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/67796f0be4c494d262240b98f32c6e44c309f476/sql/pgwire/v3.go#L241)):*
Done.

---

*[sql/pgwire/v3.go, line 296 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-KE8WrujL8uUgW8pu39O:-KE8YDaUTjMCXnL4tpIG:680160658) ([raw file](https://github.com/cockroachdb/cockroach/blob/67796f0be4c494d262240b98f32c6e44c309f476/sql/pgwire/v3.go#L296)):*
For reference: https://github.com/postgres/postgres/blob/master/src/backend/tcop/postgres.c#L431

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740)*

**Comment by tamird** [comment]
:lgtm:

Per @bdarnell's comment, this fixes #4549.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5740#-:-KE8c1FOJrwUjlNT5xJ8:1387970127)*

**Pull request merged**
