### PR TITLE
kvserver: deflake TestMergeQueue

### LINKED ISSUE #63009: kvserver: nil pointer dereference in TestMergeQueue
**Describe the problem**

See this [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=2841409&buildTypeId=Cockroach_UnitTests) run against the 21.1 branch.

```

------- Stdout: -------
=== RUN   TestMergeQueue/sticky-bit
    --- FAIL: TestMergeQueue/sticky-bit (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c1a2e7]

goroutine 196713 [running]:
testing.tRunner.func1.1(0x4182cc0, 0x737a9c0)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc001b04f00)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x4182cc0, 0x737a9c0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SetZoneConfig(0x0, 0xc008ca0fc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica.go:689 +0x47
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMergeQueue.func5(0xc005694700, 0xc0056946f0, 0xc0056946f8, 0x0, 0xc0056946e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:4144 +0xae
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMergeQueue.func6(0xc001b04f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:4155 +0x302
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMergeQueue.func12(0xc001b04f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:4234 +0x8f
testing.tRunner(0xc001b04f00, 0xc00539cf80)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
```

+cc @tbg for routing.

### LINKED ISSUE #64056: kv/kvserver: TestMergeQueue failed
kv/kvserver.TestMergeQueue [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2911036&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2911036&tab=artifacts#/) on master @ [a2b80cb4474f93ac66e59d567c3197dfd482a3be](https://github.com/cockroachdb/cockroach/commits/a2b80cb4474f93ac66e59d567c3197dfd482a3be):

Fatal error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cb64a7]

```
Stack: 

```
goroutine 205411 [running]:
testing.tRunner.func1.1(0x426eac0, 0x756cab0)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc009084f00)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x426eac0, 0x756cab0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SetZoneConfig(0x0, 0xc008d8f380)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica.go:685 +0x47
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMergeQueue.func5(0xc005e486c0, 0xc005e486b0, 0xc005e486b8, 0x0, 0xc005e486a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:4144 +0xae
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMergeQueue.func6(0xc009084f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:4155 +0x302
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMergeQueue.func12(0xc009084f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:4234 +0x8f
testing.tRunner(0xc009084f00, 0xc00b35ea00)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestMergeQueue
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestMergeQueue222352953
    test_log_scope.go:74: use -show-logs to present logs inline
--- FAIL: TestMergeQueue (0.88s)
=== RUN   TestMergeQueue/combined-threshold
    client_merge_test.go:4205: ranges unexpectedly unmerged expected startKey /Table/Max, but got "\xfa\x00\x00"
    --- FAIL: TestMergeQueue/combined-threshold (0.01s)
=== RUN   TestMergeQueue/non-collocated
    client_merge_test.go:4227: replica doesn't exist
    --- FAIL: TestMergeQueue/non-collocated (0.08s)
=== RUN   TestMergeQueue/sticky-bit
    --- FAIL: TestMergeQueue/sticky-bit (0.00s)
```
</p>
</details>
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestMergeQueue PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-json
</p>
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
benesch marked as alumn{us/a}; resolving to nvanbenschoten instead
```
</p>
</details>

/cc @nvanbenschoten
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMergeQueue.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #64866: kvserver: TestMergeQueue fails with "unmerged expected startKey"
Observed in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2960243?

```
=== RUN   TestMergeQueue/both-empty
client_merge_test.go:4196: ranges unexpectedly unmerged expected startKey /Table/Max, but got "\xfa\x00\x00"
--- FAIL: TestMergeQueue/both-empty (0.00s)

=== RUN   TestMergeQueue/lhs-undersize
client_merge_test.go:4205: ranges unexpectedly unmerged expected startKey /Table/Max, but got "\xfa\x00\x00"
--- FAIL: TestMergeQueue/lhs-undersize (0.00s)

```

etc

cc @tbg for triage

### PR DESCRIPTION
**Pull request by aayushshah15**
The test started flaking after ce73bc1. The issue was that there was a race
between when the merge queue was enabled via an `Override()` call and when
these tests assert that a given range actually got merged away. In other words,
these tests were sometime getting to their assertion before the relevant server
learned that the merge queue was enabled.

This patch modifies the test to instead enable the merge queue via SQL and not
through the `Override()` call on the cluster setting.

Resolves #64866
Resolves #64056
Resolves #63009

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
Stressed the test with this patch for a while:
```
30423 runs so far, 0 failures, over 15m40s
```

I don't think I fully understand why doing it via the `Override()` call was racey. I'll try and dig in tomorrow.

**Review by nvb — COMMENTED** [review]
> I don't think I fully understand why doing it via the Override() call was racey. I'll try and dig in tomorrow.

I don't think I understand either. Did you get a chance to dig into this yet? Perhaps it's because there is some asynchrony in `(*TestCluster).Start`'s call to `SET CLUSTER SETTING kv.range_merge.queue_enabled = false`. If cluster settings are propagated via gossip then maybe one of the servers doesn't hear about this update until _after_ the call to `kvserverbase.MergeQueueEnabled.Override(ctx, sv, true)`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65912#-:-MbCKVpf6eep202ss-NK:bhw2wds)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/client_merge_test.go, line 4238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65912#-MbCK0d5BYm9fEWGc8m7:-MbCK0d6EkT3_3GkvNqQ:bfvw1on) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb0e29d1da5d09d1d869c2324d14160c0fbd71f/pkg/kv/kvserver/client_merge_test.go#L4238)):*
> ```Go
> 		tc.TransferRangeLeaseOrFatal(t, *rhs().Desc(), tc.Target(1))
> 		tc.RemoveVotersOrFatal(t, rhs().Desc().StartKey.AsRawKey(), tc.Target(0))
> 		testutils.SucceedsSoon(t, func() error {
> ```

We don't need this? My understanding was that this is needed because the leaseholder of the RHS is 1, so 0 may not apply the ChangeReplicas entry synchronously. But maybe that's not true since we're running a 2 node cluster.

**Review by aayushshah15 — COMMENTED** [review]
>If cluster settings are propagated via gossip then maybe one of the servers doesn't hear about this update until after the call to kvserverbase.MergeQueueEnabled.Override(ctx, sv, true)

That was a :galaxybrain: suspicion. That's indeed what was happening:
```
137:I210602 22:43:16.938797 47 kv/kvserver/client_merge_test.go:4119  [-] 117  DEBUG!!! override kv.range_merge.queue_enable to true
...
140:I210602 22:43:16.939702 197 server/settingsworker.go:48  [n1] 120  DEBUG!!! setting kv.range_merge.queue_enabled to false
```  

Adding a sleep right before this line https://github.com/cockroachdb/cockroach/blob/904807640f6a28aa82c5e63f0b62de2dbf27b3a0/pkg/server/settingsworker.go#L82 makes the test fail every time.
```


> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65912#-:-MbDsvVk4fB17nTxw7LD:bbu17y6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 4238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65912#-MbCK0d5BYm9fEWGc8m7:-MbDa-Se00augKeWDT4i:bc1ufjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb0e29d1da5d09d1d869c2324d14160c0fbd71f/pkg/kv/kvserver/client_merge_test.go#L4238)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't need this? My understanding was that this is needed because the leaseholder of the RHS is 1, so 0 may not apply the ChangeReplicas entry synchronously. But maybe that's not true since we're running a 2 node cluster.
</blockquote></details>

Yeah, I clarified that that's because its a 2 node `TestCluster`.


<!-- Sent from Reviewable.io -->

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65912#-:-MbHh54r58_e3p6KG3RP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by aayushshah15** [comment]
TFTR!

bors r+

**Pull request merged**
