### PR TITLE
server: delete node status entries during decommissioning

### LINKED ISSUE #51304: kv: NodeStatus keys not cleared on decommissioning
We don't currently clear entries from `"status-node-"` keyspace when a node is removed from the cluster. This can cause confusion when performing aggregation over those keys. For instance, when working with `crdb_internal.kv_store_status` and aggregating over `metrics->>'ranges.underreplicated'`.

I don't know the full history or intention of these keys and the metrics they contain, but we should likely either:
1. clear the metrics portion of the keys associated with decommissioned nodes
2. delete the keys associated with decommissioned nodes entirely

cc. @tbg since you might be one of the few people who still knows how this subsystem works and what its intentions are.

### PR DESCRIPTION
**Pull request by erikgrinaker**
Decommissioning a node did not remove its node status entry in the
`status-node-` keyspace. This caused the decommissioned node to remain
visible via e.g. `Status/Nodes` gRPC calls, affecting other systems that
did not check against the node's liveness entry.

This commit deletes a node's status entry when it is being
decommissioned. Unfortunately, since the status entry is inline this
cannot be transactional with the liveness entry, which can cause a stale
status entry to be left behind if the operation should fail or the node
should crash. In these cases, the decommission operation (which is
idempotent) must be run again to remove it.

To avoid a race condition where the decommissioned node's status
recorder loop resurrects the status entry after it has been removed,
this also changes the recorder to only update the status entry if it
already exists. The initial status entry is written during node startup,
and the node will now fail to start if the entry cannot be written.

Release note (bug fix): remove a node's status entry when the node is
decommissioned, to prevent it from appearing in API calls and UIs, and
avoid it affecting node constraints such as localities and attributes
for various operations.

Resolves #51304.

This also adds support for conditional puts of inline values, as a separate commit -- see commit message for details.

### CODE REVIEW

**Comment by tbg** [comment]
Thanks @erikgrinaker and sorry it's taking me so long to look at this. It turns out that there's actually a near-term desire to rely on these status keys internally a bit more. @nvanbenschoten and/or @aayushshah15, could you provide pointers on what's needed there?

> One option here which isn't outlined in the issue might be to have all nodes attempt to clean up the NodeStatusKey when they see the liveness entry change to decommissioned, since this is a cheap and idempotent operation - this would at the very least be eventually consistent (or highly likely to be). The status update loop would also need to check the liveness entry before writing, to avoid recreating it.

That's not a bad idea, though in practice it's still going to be a little crufty (as will anything that requires sync between the update loop and the record). For example, we want a decommission**ing** node to keep writing these updates (as the UI uses them to display node info) and only stop on decommission**ed**, which is a very short moment in time.

For an alternative solution, we could add an RPC endpoint that stops the node status loop (i.e. a `WillBeDecommissionedCallback`). When the target node is live, we invoke it (otherwise we don't). After that point, we delete the entry, and flip the entry to decommissioned. This still leaves, theoretically, a small window in which the node could rejoin the cluster and write an offending key, but it does seem fine, as long as the guarantees required for Nathan and Aayush's work are fine with that remote chance.

**Comment by erikgrinaker** [comment]
No rush! I agree that there aren't really any obvious good ways to solve this. What about having a version for the entry and using OCC along with a tombstone? Other than that, I think I'm leaning towards either check-on-read or a reconciliation loop (possibly piggybacking on some other cleanup loop), since those will always converge on a correct state, eventually.

**Review by nvb — COMMENTED** [review]
Hi @erikgrinaker, this looks like a great start! Thanks for putting it together and sorry my review is coming a little late.

Performing a best-effort removal of the `NodeStatusKey` when decommissioning is the right first step here. I left a comment below about a potential change we could make to allow for manual retries in the presence of node failures or other interruptions. Given the limited set of places that we intend to use `NodeStatusKey`s for https://github.com/cockroachdb/cockroach/issues/51304#issuecomment-720780437, this may actually be sufficient for our use case.

Past that, it sounds like the biggest blocker towards clearer semantics is that there is no coordination with the `MetricsRecorder`, so any work we do to delete the node's status key may be undone due to a race. The most natural way to avoid these kinds of issues would be to replace the blind put in `MetricsRecorder` with a conditional put. If writes to the key from the `startWriteNodeStatus` loop (but not from `initializeAdditionalStores`) were to atomically check that _some_ value already existed for the key, then I think we'd be in the clear. The immediate issue with this is that we don't have an `Inline` flag on `ConditionalPutRequest`. I don't think there's any strong reason for this though, other than that we have never needed one (@tbg does that sound right?). So we could consider:
1. adding inline support to `ConditionalPutRequest`
2. either querying or remembering the previous value for the node's `NodeStatusKey` in `startWriteNodeStatus`
3. conditionally writing to the key and logging a warning on `ConditionFailedErrors`

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-:-MMx7DPQ4LQ9DfcUd9-a:btxzu8j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[pkg/server/server.go, line 2092 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MMx8K3gBP5xtOoS-X7B:-MMx8K3gBP5xtOoS-X7C:blqrd5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9dd70c27e9304fb8451c104551fef71942ba3e7/pkg/server/server.go#L2092)):*
> ```Go
> 			// the status entries if we crash or fail. Note that the status
> 			// entry is an inline value, thus this cannot be transactional.
> 			if targetStatus.Decommissioned() {
> ```

While this can't be transactional, I wonder if we can leverage the fact that decommissioning is idempotent to permit crashes/failures that prevent the NodeStatus key from being deleted to be retried. If we pulled this operation out of the `if statusChanged` block, would that be enough to support this form of manual reconciliation?

**Comment by erikgrinaker** [comment]
>I wonder if we can leverage the fact that decommissioning is idempotent to permit crashes/failures that prevent the NodeStatus key from being deleted to be retried. If we pulled this operation out of the if statusChanged block, would that be enough to support this form of manual reconciliation?

I like this idea. Since there's no great way to ensure this automatically, having some way to manually repair this in the case of failure seems like a reasonable first step -- have updated the PR with this.

> The most natural way to avoid these kinds of issues would be to replace the blind put in `MetricsRecorder` with a conditional put.

Awesome! I was thinking we could use some sort of optimistic concurrency control, but put the idea aside since I didn't think the KV store supported it (given that it also uses MVCC) -- great to learn that this is possible after all, thanks for the tip! I'll go ahead and implement this.

One problem with this approach is that if the original write in `initializeAdditionalStores` fails (which would just be logged and ignored) then the status key will never be written. Maybe we should make this a fatal error?

**Comment by erikgrinaker** [comment]
>>The most natural way to avoid these kinds of issues would be to replace the blind put in MetricsRecorder with a conditional put.
>
>Awesome! I was thinking we could use some sort of optimistic concurrency control, but put the idea aside since I didn't think the KV store supported it (given that it also uses MVCC) -- great to learn that this is possible after all

Hm, I'm actually not sure if `ConditionalPut` can be implemented safely for inline values. Since inline values do not have a timestamp, and Pebble does not appear to support transactions, OCC, or locks, I don't think there's any way to atomically read and write the value. A concurrent writer (e.g. the decommissioner) could therefore modify it in the meanwhile. Or am I missing something?

**Review by nvb — COMMENTED** [review]
> One problem with this approach is that if the original write in initializeAdditionalStores fails (which would just be logged and ignored) then the status key will never be written. Maybe we should return an error for this?

Returning an error there seems reasonable to me. That way, we can guarantee that an initialized store will have a corresponding node status key.

> Hm, I'm actually not sure if ConditionalPut can be implemented safely for inline values. Since inline values do not have a timestamp, and Pebble does not appear to support transactions, OCC, or locks, I don't think there's any way to atomically read and write the value. A concurrent writer (e.g. the decommissioner) could therefore modify it in the meanwhile. Or am I missing something?

Everything you said is true, but what you're missing is that CRDB has a lightweight latching mechanism that provides request-level isolation, even to inline and non-transaction operations. This is enough to synchronize with other inline ConditionalPut operations. To read up on this, see https://github.com/cockroachdb/cockroach/blob/13ce0e8db15efd201af782322669f0542c40b29a/pkg/kv/kvserver/concurrency/concurrency_control.go and https://github.com/cockroachdb/cockroach/blob/13ce0e8db15efd201af782322669f0542c40b29a/pkg/kv/kvserver/spanlatch/doc.go.

To use this, we'll need to configure the inline ConditionalPut to support latching just like we do with the inline Put operation. See https://github.com/cockroachdb/cockroach/blob/13ce0e8db15efd201af782322669f0542c40b29a/pkg/kv/kvserver/batcheval/cmd_put.go#L34-L38.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-:-MNPf3Eg7z7eepMvaDcV:b-5gxl9v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

**Comment by andreimatei** [comment]
Hi Erik!
Drive-by comment: please update the (almost non-existent) comment on the Nodes RPC with this patch to say something about decommissioned nodes - namely spell out that they're not included (or that they can still be included in some edge cases?)
https://github.com/cockroachdb/cockroach/blob/9e4ec7d392e327ba6bb2310d550ea8420ebb0cc6/pkg/server/serverpb/status.proto#L994

**Comment by erikgrinaker** [comment]
Sure thing @andreimatei!

**Comment by erikgrinaker** [comment]
@tbg @nvanbenschoten Thanks for the input, I think this should be ready for review now (barring any CI failures). 

We do a best-effort removal during decommissioning, on failure the operation must be rerun to remove the stale entry. The status recorder loop uses a conditional put to update the value only if it already exists, and we unconditionally write a status entry on node startup with a fatal error on failure.

This may still leave a race condition when decommissioning a node that happens to be starting up (where it's decommissioned between checking the decommissioned status and writing the status entry), but I feel like that's going pretty far into edge case territory. In any case, it can be repaired using the same approach as for crashes, by rerunning the decommission operation.

Let me know what you think.

**Review by nvb — COMMENTED** [review]
This looks great! Very nice job @erikgrinaker. There are just a few nits remaining before we can merge this, nothing serious.

> Reviewed 10 of 10 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-:-MOD66iRBbozUVJu_J4x:bjnwqpq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[pkg/kv/batch.go, line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MOD2HD1AjmgN4IgdqD8:-MOD2HD1AjmgN4IgdqD9:bqw5fkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/94465c43932cb0e06f4bf1e2733f5dac31e8e680/pkg/kv/batch.go#L427)):*
> ```Go
> }
> 
> // CPutInline conditionally sets the value for a key if the existing value is
> ```

nit: drop this below `CPutAllowingIfNotExists` to keep the transaction versions of CPut grouped together. 
___
*[pkg/kv/client_test.go, line 379 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MOD2SnIBMjzPr1BiPW9:-MOD2SnIBMjzPr1BiPWA:bfm9f0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/94465c43932cb0e06f4bf1e2733f5dac31e8e680/pkg/kv/client_test.go#L379)):*
> ```Go
> 	value := []byte("value")
> 
> 	// Should fail on non-existent key with expected value
> ```

nit: in accordance with the [Go style guide](https://golang.org/doc/effective_go.html#commentary), we generally try to use proper punctuation in comments whenever possible.
___
*[pkg/server/decommission_test.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MOD5jLd5naeEN7m6sn9:-MOD5jLe7oytNi0CGPMk:b-j6xjpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec4751fef405daa186c80dd17990b272517dd03/pkg/server/decommission_test.go#L61)):*
> ```Go
> 		ctx, livenesspb.MembershipStatus_DECOMMISSIONED, []roachpb.NodeID{decomNodeID}))
> 
> 	// The node status entries should shortly be cleaned up.
> ```

I might be thinking about this incorrectly, but shouldn't this have been performed synchronously? In other words - why do we need the `SucceedsSoon`?
___
*[pkg/server/node.go, line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MOD4O002cmHJIWTY6KX:-MOD4O0183yy15OmZ9Bd:b-v9x6wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec4751fef405daa186c80dd17990b272517dd03/pkg/server/node.go#L585)):*
> ```Go
> 	// Write a new status summary after all stores have been initialized; this
> 	// helps the UI remain responsive when new nodes are added.
> 	if err := n.writeNodeStatus(ctx, 0 /* alertTTL */, false); err != nil {
> ```

nit: add a `/* mustExist */` comment after the false. See the "Avoid Naked Parameters" section of our extended style guide for the reason why: https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+coding+guidelines.

Same thing down below.
___
*[pkg/server/node.go, line 725 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MOD5AZt47ZmMAqk1VBT:-MOD5AZt47ZmMAqk1VBU:b-27tr98) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec4751fef405daa186c80dd17990b272517dd03/pkg/server/node.go#L725)):*
> ```Go
> 				//
> 				// The status key must already exist, to avoid race conditions
> 				// during node decommissioning.
> ```

Consider expanding this comment a bit to mention that this process may not even be the one performing the decommissioning.

**Comment by erikgrinaker** [comment]
Thanks for the review and suggestions @nvanbenschoten, I've updated the PR with fixes.

**Review by nvb — APPROVED** [review]
Looks great, thanks again! I'll merge this into master.

bors r+

> Reviewed 2 of 12 files at r4, 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-:-MOEoIjL4UUJqmv9AELQ:b-v4zd81)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by erikgrinaker** [comment]
>I might have missed this in the code, but isn't there a migration concern here due to the new option to CPut?

Good catch, I think you're right. What would be the preferred approach? Assuming regular (non-inline) CPuts for inline values return a distinct error type we could handle the error and fall back to a normal put, otherwise I suppose we'd have to rely on the API versioning system somehow. Can look into this tonight.

**Comment by tbg** [comment]
The standard way to do this would be to gate the inline cputs behind a cluster setting (i.e. don't use the new cputs unless the version is active, which guarantees that all nodes in the cluster run a binary containing your commit).

Take a look at this version: https://github.com/cockroachdb/cockroach/blob/867505f94f4dab4067c62172e8ac5c4109413b99/pkg/clusterversion/cockroach_versions.go#L204

and how it is used here:

https://github.com/cockroachdb/cockroach/blob/b2fc523a4f8fc0646f9f413243625af39ba1f123/pkg/sql/create_table.go#L1758

You can introduce a new version `VersionInlineCPut` (`cockroach_versions.go` has a the instructions).

**Comment by erikgrinaker** [comment]
@tbg Added `clusterversion.InlineCPut`. It's only checked in `MetricsRecorder.WriteNodeStatus()`, since the client APIs `DB.CPutInline()` and `Batch.CPutInline()` do not appear to have access to cluster settings -- which I suppose makes sense since they may be used outside of a cluster context. I instead liberally sprinkled comments in the client APIs about checking the feature gate before using it.

**Review by tbg — COMMENTED** [review]
Looks good! You are right, it is difficult to version gate additions to the KV API as no settings are available. Something I've done in the past, just to avoid misuse (people don't necessarily read the comments since it might be obvious to them what the method would do) is this:

```go
type canUseInlineCPut struct{}
func CtxForInlineCPut(ctx context.Context) context.Context {
  // This code and all of its uses can be removed when the version below
  // is removed:
  _ = clusterversion.InlineCPut
  return context.WithValue(ctx, canUseInlineCPut{}, canUseInlineCPut{})
}

func InlineCPut(ctx context.Context, /* ... */) error {
  if ctx.Value(canUseInlineCPut{}) == nil {
    return errors.New("InlineCPut is new in 21.1, you must check the InlineCPut cluster version and use CtxForInlineCPut")
  }
  // ...
}
```

> Reviewed 2 of 10 files at r2, 1 of 12 files at r4, 18 of 18 files at r6, 11 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-:-MOa3cBZ17IXUWcyv5Jn:b-plhivs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/server/status/recorder.go, line 511 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MOa3B9dBswEDcZx88Gy:-MOa3B9dBswEDcZx88Gz:b-g1ubns) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2630058ef55c4635042e344cc7101bc9af4f2bd/pkg/server/status/recorder.go#L511)):*
> ```Go
> 		}
> 		if entry.Value == nil {
> 			return &roachpb.ConditionFailedError{ActualValue: nil}
> ```

This doesn't seem like the right error to return (since we're not in any code path where the caller knows do to anything with a structured KV error). Don't you want something like

```go
return errors.New("this node was decomissioned")
```

**Comment by erikgrinaker** [comment]
> Something I've done in the past, just to avoid misuse

Good idea, thanks. I added this for `DB.CPutInline()`, but `Batch.CPutInline()` doesn't have access to a context so I'd have to go into the batch execution machinery and inspect the requests there, which seemed a bit excessive -- can add this if you'd prefer though.

> This doesn't seem like the right error to return

Yeah, I thought it might be nice to always return the same error kind as the conditional put, but you're right in that we're not going to inspect it here anyway. Used a generic error instead.

**Comment by tbg** [comment]
> Good idea, thanks. I added this for DB.CPutInline(), but Batch.CPutInline() doesn't have access to a context so I'd have to go into the batch execution machinery and inspect the requests there, which seemed a bit excessive -- can add this if you'd prefer though.

Yeah that seems excessive. You are calling that method, right? Otherwise - unexport. If you're calling it, you could still rename it (`UnsafeCPutInline`?) Anyway, I agree that this is going into diminishing returns.

> Yeah, I thought it might be nice to always return the same error kind as the conditional put, but you're right in that we're not going to inspect it here anyway. Used a generic error instead.

`ConditionalPutError` is primarily intended for programmatic consumption (i.e. translate into for example a unique constraint violation error), but this error we were looking at is just going to the logs, so human-readable is the right choice.

**Review by nvb — APPROVED** [review]
> Reviewed 10 of 21 files at r8, 11 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56529)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/server/status/recorder.go, line 511 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-MOa3B9dBswEDcZx88Gy:-MOgKf1d40hnEE1b1V7D:bz6q5ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2630058ef55c4635042e344cc7101bc9af4f2bd/pkg/server/status/recorder.go#L511)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This doesn't seem like the right error to return (since we're not in any code path where the caller knows do to anything with a structured KV error). Don't you want something like

```go
return errors.New("this node was decomissioned")
```

</blockquote></details>

This is a good point. What do you think about catching `ConditionFailedError`s coming from CPutInline and wrapping them with similar context about a concurrent update (if `ActualValue != nil`) and a concurrent decommission (if `ActualValue == nil`).

**Comment by erikgrinaker** [comment]
> You are calling that method, right? Otherwise - unexport.

Done. 👍

> What do you think about catching ConditionFailedErrors coming from CPutInline and wrapping them with similar context about a concurrent update

For sure -- should've done that when I changed the other error, but slipped my mind. Done.

**Review by nvb — APPROVED** [review]
:lgtm: thanks for pushing through the migration concerns.

I'll merge on green.

> Reviewed 5 of 16 files at r10, 11 of 11 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56529#-:-MOh1UAQ8Lu6z47b7I4d:b-wozj4m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by erikgrinaker** [comment]
Bumped this again, realized what you meant with the `ActualValue` check. Thanks!

**Pull request merged**
