### PR TITLE
sql/schemachanger: enable CCL testing, fix a bug

### PR DESCRIPTION
**Pull request by ajwerner**
Before this PR, dropping a multi-region database would fail because
of a bug in the builder. I should probably also give a similar treatment to
builder tests, but not right now.

Before this change, the test failed with:
```
pq: internal error: unexpected kind MULTIREGION_ENUM for type "crdb_internal_region"
```

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
I need to pull this testing functionality out anyway. I don't think this is so so onerous.

**Review by fqazi — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

**Review by fqazi — APPROVED** [review]
Took a quick look, good find. :LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76559#-:-Mvv_UuT114jezt6Pauz:b5uzypd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Pull request merged**
