### PR TITLE
Fix typos in test case TestTxnDBReadSkewAnomaly's comment

### PR DESCRIPTION
**Pull request by yaojingguo**
Fix typos in test case TestTxnDBReadSkewAnomaly's comment

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7264)

### CODE REVIEW

**Comment by tamird** [comment]
lgtm

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[kv/txn_correctness_test.go, line 905 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264#-KKO9sMFk35JzjU6lj_4:-KKO9sMFk35JzjU6lj_5:1980793334) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9e58492f6c9e3b82a2a8ad5fe4175a46e14ebe/kv/txn_correctness_test.go#L905)):*
> ```Go
> //   D(x) - delete key "x"
> //   DR(x-y) - delete range of keys "x"-"y"
> //   W(x,y+z+...]) - writes sum of values y+z+... to x
> ```

I think there is still a stray "]" in here that needs to be removed.

---

*[kv/txn_correctness_test.go, line 914 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264#-KKO9vnRVuKEiEv8QuJ2:-KKO9vnRVuKEiEv8QuJ3:1700997001) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9e58492f6c9e3b82a2a8ad5fe4175a46e14ebe/kv/txn_correctness_test.go#L914)):*
> ```Go
> //   Dn.m(x) - delete key from txn ("m"th retry) of key "x"
> //   DRn.m(x-y) - delete range from txn "n" ("m"th retry) of keys "x"-"y"
> //   Wn.m(x,y+z+...]) - write sum of values y+z+... to x from txn "n" ("m"th retry)
> ```

Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264)*

**Comment by yaojingguo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[kv/txn_correctness_test.go, line 905 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264#-KKO9sMFk35JzjU6lj_4:-KKRMw6lKqK13fQi3i9M:-894265573) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9e58492f6c9e3b82a2a8ad5fe4175a46e14ebe/kv/txn_correctness_test.go#L905)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think there is still a stray "]" in here that needs to be removed.
</details>
"]" is removed in the new commit 6578445. PTAL.
      

---

*[kv/txn_correctness_test.go, line 914 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264#-KKO9vnRVuKEiEv8QuJ2:-KKRN7_jBD1UlleGkxTx:1700997001) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9e58492f6c9e3b82a2a8ad5fe4175a46e14ebe/kv/txn_correctness_test.go#L914)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Ditto.
</details>
Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264)*

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7264#-:-KKSzxQiTbdPLDxHg6gg:1417088721)*

**Comment by knz** [comment]
@yaojingguo many thanks for your contribution!

**Pull request merged**
