### PR TITLE
opt: Eliminate unused columns using the new PruneCols property

### PR DESCRIPTION
**Pull request by andy-kimball**
This is a multi-commit PR that changes the way we prune unused columns. Its goal is to never introduce new Project operators into the tree when pruning unused columns, because they tend to prevent other rules from matching. I'm seeing that happen quite a bit while working on the decorrelation rules, which is what triggered this PR.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm_strong:

Much nicer than the first version!

Thanks for breaking it up into commits, it helped a lot.

---

Reviewed 2 of 18 files at r1, 27 of 37 files at r2, 1 of 8 files at r3, 6 of 9 files at r4, 19 of 27 files at r5, 22 of 28 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/memo/expr_view.go, line 256 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgxLiVA6iqUUYUtHu2:-LBgxLiVA6iqUUYUtHu3:b-mjmkoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/memo/expr_view.go#L256)):*
> ```Go
> 
> 	// ExprFmtHideRulesProps does not show rule-specific properties in the output.
> 	ExprFmtHideRulesProps
> ```

[nit] HideRuleProps rolls off the tongue better

---

*[pkg/sql/opt/testutils/opt_tester.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgxETc1AwGMPS2yqHD:-LBgxETc1AwGMPS2yqHE:b-m2k04h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/testutils/opt_tester.go#L210)):*
> ```Go
> 				"hide-cost":        memo.ExprFmtHideCost,
> 				"hide-constraints": memo.ExprFmtHideConstraints,
> 				"hide-rules":       memo.ExprFmtHideRulesProps,
> ```

[nit] hide-rules is deceiving, maybe hide-ruleprops

---

*[pkg/sql/opt/props/logical.go, line 115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgxaRe7TbM6crEQCm6:-LBgxaRe7TbM6crEQCm7:b5xq2z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/props/logical.go#L115)):*
> ```Go
> 	// in by one of the transformation packages, since deriving rule properties
> 	// is so closely tied with maintenance of the rules that depend upon them.
> 	Rules struct {
> ```

[nit] maybe `Rule`? "Rule props" sounds better to me.

---

*[pkg/sql/opt/props/logical.go, line 131 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgvcpuDQVMQ1E26GbM:-LBgvcpv9p8INh5wEJEp:b-gryiw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/props/logical.go#L131)):*
> ```Go
> 		// are referenced. Drawing from the example above:
> 		//
> 		//   Project PruneCols: [z]
> ```

How can Project have `[z]` if `z` isn't an output column?

---

*[pkg/sql/opt/props/logical.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgvqSlBI7W9brDOk7z:-LBgvqSlBI7W9brDOk8-:b-du97jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/props/logical.go#L140)):*
> ```Go
> 		// operator. If a column is part of PruneCols, then it is guaranteed that
> 		// such an operator exists at the end of the journey.
> 		PruneCols opt.ColSet
> ```

If I was reading this description without any prior knowledge, I would assume that if I thought about it enough, I would know how to derive this property for all relational operators, independent of the rules we have. In reality, this is closer to a heuristic, and we are setting it in a way that works best with our rules. I think this is worth pointing out (either here or perhaps in the Rules comment if this will be a common theme among these properties)

Great description otherwise!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-:-LBh4-N442rsv0INWG5M:b-um54gk)*

**Comment by RaduBerinde** [comment]
Reviewed 10 of 11 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25323)*

**Comment by rytaft** [comment]
I like the idea of using the logical properties to help with determining which columns can be pruned. It seems cleaner than the cyclic rule handling.

But it seems like there are some cases where the previous rules would have produced a better plan. For example, there are some cases where you're now adding a top-level project where previously there was a lower-level project. Based on your commit message, it sounds like there shouldn't be a top-level project in those cases - it sounds like it should be handled by the presentation property. 

---

Reviewed 12 of 18 files at r1, 32 of 37 files at r2, 6 of 8 files at r3, 8 of 9 files at r4, 27 of 27 files at r5, 18 of 28 files at r6, 10 of 11 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/testdata/limit, line 86 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqphTg0nyOf_vffq2o:-LBqphTg0nyOf_vffq2p:b-106jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/exec/execbuilder/testdata/limit#L86)):*
> ```
> render                         ·            ·          (column4)         ·
>  │                             render 0     column4    ·                 ·
>  └── render                    ·            ·          (column4, "t.v")  ·
> ```

it's odd that there are two renders -- do you know why this is happening? 

---

*[pkg/sql/opt/norm/prune_cols.go, line 79 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqsXqPA_EZbFPpY2vK:-LBqsXqPA_EZbFPpY2vL:b-xxn0hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/norm/prune_cols.go#L79)):*
> ```Go
> func (f *Factory) candidatePruneCols(target memo.GroupID) opt.ColSet {
> 	switch f.mem.NormExpr(target).Operator() {
> 	case opt.ProjectionsOp, opt.AggregationsOp:
> ```

These are scalar expressions, right? Do we need this check? (If so, can we guarantee this function is not called on other scalar expressions?)

---

*[pkg/sql/opt/norm/rule_props_builder.go, line 152 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBquh902eEjlbHBh5h4:-LBquh9116l3c6waTpZc:bm16jub) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/norm/rule_props_builder.go#L152)):*
> ```Go
> func (b *rulePropsBuilder) buildSetProps(ev memo.ExprView) {
> 	// Don't allow any columns to be pruned, since that would trigger the
> 	// creation of a wrapper Project around the Max1Row, since there's not yet
> ```

Did you mean Set operator instead of Max1Row?

---

*[pkg/sql/opt/norm/rules/prune_cols.opt, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqm4qN7cO72KVRlIK9:-LBqm4qN7cO72KVRlIKA:bh6i5px) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa174a43076a2c1a07dae92f8106595a0193b1d8/pkg/sql/opt/norm/rules/prune_cols.opt#L23)):*
> ```
> # Scan or Project, and it will be merged into that operator.
> #
> # Pruning unused columns is not desirable if the Project operator "get stuck"
> ```

get stuck -> gets stuck

---

*[pkg/sql/opt/norm/rules/prune_cols.opt, line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBr22rUBthTzj8xx5ra:-LBr22rUBthTzj8xx5rb:bs5lrqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/norm/rules/prune_cols.opt#L69)):*
> ```
> # While the PruneCols property should prevent this rule (which pushes Project
> # below Select) from cycling with the PushSelectIntoProject rule (which pushes
> # Select below Project), the DetectCycle flag is used anyway. This will prevent
> ```

how will we find those bugs if we don't get rid of the flag?

---

*[pkg/sql/opt/xform/testdata/coster/join, line 29 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqzuAq0M8FbH-3aW-B:-LBqzuAq0M8FbH-3aW-C:bmo8xa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d22ffae880e03490fad8b7cb27b2da11a04be6fb/pkg/sql/opt/xform/testdata/coster/join#L29)):*
> ```
>  ├── stats: [rows=100]
>  ├── cost: 2100.00
>  ├── project
> ```

This is a place where it seems better to have the project below the inner join. Am I missing something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-:-LBr-yGH7VaXDrJouQNl:b-4p1dxv)*

**Comment by andy-kimball** [comment]
Yes, the plan is to separate out two different kinds of pruning:

1. Pruning of columns that aren't used anywhere or can be filtered by an existing Project or GroupBy that we have to have anyway. No reason to keep these around. The new `prune_cols` rules get rid of this category.

2. Pruning of columns that were used in the subtree, but which are not needed by higher level expressions. The trouble with pruning these is that it sprinkles extra Project operators into the tree, which impede other rules from firing. So the plan is to use the Presentation property to exclude these from the final physical plan.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/testdata/limit, line 86 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqphTg0nyOf_vffq2o:-LC1LJrfACtCSysicoL1:b-c1x7pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/exec/execbuilder/testdata/limit#L86)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

it's odd that there are two renders -- do you know why this is happening? 
</blockquote></details>

Radu says that he's not detecting that a simplification is possible in this case. Using the presentation property should fix this up.

---

*[pkg/sql/opt/memo/expr_view.go, line 256 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgxLiVA6iqUUYUtHu2:-LBhItYOBBb-kIA7Ypyx:b-44asux) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/memo/expr_view.go#L256)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] HideRuleProps rolls off the tongue better
</blockquote></details>

Done, though who doesn't love a good tongue twister?

---

*[pkg/sql/opt/norm/prune_cols.go, line 79 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqsXqPA_EZbFPpY2vK:-LC1NE4S2_WUx_i3XRfI:b-hy0cs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/norm/prune_cols.go#L79)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

These are scalar expressions, right? Do we need this check? (If so, can we guarantee this function is not called on other scalar expressions?)
</blockquote></details>

`Projections` and `Aggregations` are kind of a cross between scalar and relational, since they both project columns for a relational operator and act a bit like a `Scalar` operator with a `Tuple` type. We could invent a 3rd category for them, but it seems like overkill. Remember that they mainly exist b/c we want to keep our relational operators to only 3 int32 fields (though keeping them separate has turned out to have other benefits as well).

If this function is called for other scalar expressions, we'd immediately fail below when we deref the `Relational` property.

---

*[pkg/sql/opt/norm/rule_props_builder.go, line 152 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBquh902eEjlbHBh5h4:-LC1MBjC8nv0puOCdjWR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/norm/rule_props_builder.go#L152)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Did you mean Set operator instead of Max1Row?
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/prune_cols.opt, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqm4qN7cO72KVRlIK9:-LC1MFPH85mR1ggLSLX9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa174a43076a2c1a07dae92f8106595a0193b1d8/pkg/sql/opt/norm/rules/prune_cols.opt#L23)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

get stuck -> gets stuck
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/prune_cols.opt, line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBr22rUBthTzj8xx5ra:-LC1MHd58yXxqZlLOp89:b-ecuw8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/norm/rules/prune_cols.opt#L69)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

how will we find those bugs if we don't get rid of the flag?
</blockquote></details>

We'll have some `optsteps` output for some complex cases where decorrelation rules are both pushing Select down and pulling it up. We'll be able to make sure it's working as intended. The reason I'm being overly safe here is that infinite loops are *really* undesirable, whereas running a few extra rules we didn't really need to run is quite minor.

---

*[pkg/sql/opt/testutils/opt_tester.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgxETc1AwGMPS2yqHD:-LBhOidK41vGNI8h4SMw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/testutils/opt_tester.go#L210)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] hide-rules is deceiving, maybe hide-ruleprops
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/coster/join, line 29 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqzuAq0M8FbH-3aW-B:-LC1N-ks7F6zJEiQOMEu:b-mf7glz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d22ffae880e03490fad8b7cb27b2da11a04be6fb/pkg/sql/opt/xform/testdata/coster/join#L29)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a place where it seems better to have the project below the inner join. Am I missing something?
</blockquote></details>

The `Presentation` property will be able to handle cases like this.

---

*[pkg/sql/opt/props/logical.go, line 115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgxaRe7TbM6crEQCm6:-LBhJ_IW2raYfJLbj0lH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/props/logical.go#L115)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe `Rule`? "Rule props" sounds better to me.
</blockquote></details>

Done.

---

*[pkg/sql/opt/props/logical.go, line 131 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgvcpuDQVMQ1E26GbM:-LBhLh_fDTiTtkOlzHti:b-mn7rmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/props/logical.go#L131)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How can Project have `[z]` if `z` isn't an output column?
</blockquote></details>

That's an error. I added a `Limit` and corrected the language.

---

*[pkg/sql/opt/props/logical.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgvqSlBI7W9brDOk7z:-LBhOVNo7hp9eI-BcDZl:b6pj2fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/props/logical.go#L140)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If I was reading this description without any prior knowledge, I would assume that if I thought about it enough, I would know how to derive this property for all relational operators, independent of the rules we have. In reality, this is closer to a heuristic, and we are setting it in a way that works best with our rules. I think this is worth pointing out (either here or perhaps in the Rules comment if this will be a common theme among these properties)

Great description otherwise!
</blockquote></details>

OK, I added a bit to the Rule comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-:-LC1KZNe6N5ulxFa4pc5:bq7jcgv)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 79 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/opt/exec/execbuilder/testdata/limit, line 86 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBqphTg0nyOf_vffq2o:-LC1X5sv8mU6fwaW9ta-:b-kiypug) ([raw file](https://github.com/cockroachdb/cockroach/blob/721593ad762151009c5a09b485596c3af5885805/pkg/sql/opt/exec/execbuilder/testdata/limit#L86)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Radu says that he's not detecting that a simplification is possible in this case. Using the presentation property should fix this up.
</blockquote></details>

Yeah I'll look at it if it still happens after we do the presentation thing.

---

*[pkg/sql/opt/props/logical.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25323#-LBgvqSlBI7W9brDOk7z:-LC1XJUe33M1jlXz0VjQ:b-c23jcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b484c563cf2f7fc5957d1a0b5754b395e73a32d2/pkg/sql/opt/props/logical.go#L140)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

OK, I added a bit to the Rule comment.
</blockquote></details>

LG, thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25323)*

**Pull request merged**
