### PR TITLE
changefeedccl: Correctly check for type equivalence.

### PR DESCRIPTION
**Pull request by miretskiy**
Check for type equivalence instead of equality
when computing projections.

Release justification: low impact bug fix
Release note: None

### CODE REVIEW

**Review by HonoreDB — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87388)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @shermanCRL)

___
*[`pkg/ccl/changefeedccl/cdcevent/projection.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87388#-NBDUYdJ9qdOXSTCago1:-NBDUYdJ9qdOXSTCago2:bexhi6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/75d6ab2dfea61d7d185e61fdc6e9408405c00388/pkg/ccl/changefeedccl/cdcevent/projection.go#L73)):*
> ```Go
> 	// A bit of a sanity check -- types must match or d must be  DNULL.
> 	col := p.cols[pos]
> 	if !col.Typ.EquivalentOrNull(d.ResolvedType(), true) {
> ```

Based on feedback I got on a different PR recently, I think the more correct way to do this might be [like this](https://github.com/cockroachdb/cockroach/pull/84107/files#diff-541cee6d4834f09f26743c04071ff3e5cdb94ac0b71fcb081b62004745ccc76fR171-R172): sanity check that that d can be implicitly cast to the column type, and then do so. The consumer should be able to rely on the datum matching the column type exactly, even if the expression is emitting the wrong string type or whatever.

**Comment by miretskiy** [comment]
> I think the more correct way to do this might be [like this](https://github.com/cockroachdb/cockroach/pull/84107/files#diff-541cee6d4834f09f26743c04071ff3e5cdb94ac0b71fcb081b62004745ccc76fR171-R172):

Nice; thanks; Done.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87388)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @shermanCRL)

**Comment by miretskiy** [comment]
Bors r+

**Pull request merged**
