### PR TITLE
jobs: add a Profiler tab to the job details page

### LINKED ISSUE #102735: jobsprofiler: enable collection of cluster wide job-specific CPU profiles
Once a customer has identified that a job is the reason for CPU running hot on a cluster, the next step is to understand what part of the job's execution is CPU intensive. With pprof labels now propagated across distsql and kvserver boundaries we can fetch a cluster-wide CPU profile with only the samples relevant to a particular job's execution. This issue tracks the work to build the infrastructure to collect and merge a cluster wide CPU profile, and subsequently filter the profile based on the job's pprof tags. The collection of such a profile should be triggered from the "job details" page in the DB Console.

Epic: CRDB-8964

Jira issue: CRDB-27623

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds a Profiler tab to the job details page. This change also adds a row that allows collection of a cluster-wide CPU profile for 5 seconds, of all the samples corresponding to the job's execution.

Fixes: #102735

Release note (ui change): job details page now has a profiler tab for more advanced observability into a job's execution. Currently, we support collecting a cluster-wide CPU profile of the job.

### CODE REVIEW

**Comment by adityamaru** [comment]
I still need to test that this works on CC but considering it uses the same linking logic as Advanced Debug, I think it should. I'll report back.

**Review by maryliag — COMMENTED** [review]
> but considering it uses the same linking logic as Advanced Debug, I think it should

keep in mind that Advanced Debug doesn't exist on CC, so the routes might not work there at all

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-:-NWNU4zL0-zA92bQqN8a:b-qivchp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNdLoBBLDOButMoZ2S:-NWNdLoCCOJawf3JoNqh:b6ai50x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L19)):*
> ```XML
> import Long from "long";
> import Helmet from "react-helmet";
> import { RouteComponentProps, useHistory, useLocation } from "react-router-dom";
> ```

I don't see these 2 imports being used anywhere, maybe you forgot to remove from some previous tests?
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNdnPd9hon1IVomMHl:-NWNdnPd9hon1IVomMHm:b-7oyahg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L128)):*
> ```XML
>           <SummaryCard className={cardCx("summary-card")}>
>             <SummaryCardItem
>               label="Cluster-wide CPU Profile (profiles all nodes; MEMORY OVERHEAD)"
> ```

is the intention of this `MEMORY OVERHEAD` to be a warning?
If so, we have some components that make warnings more obvious and you could add a better description.
For example you could add something like this below the SummaryCartItem

```
<InlineAlert intent="warning" title="Creation of a Profile consume additional resources and can potentially negatively impact workload responsiveness." />
```
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNegi2E6uzNrFU2tKC:-NWNegi37nc032PtZaxk:bxxec9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L267)):*
> ```XML
>                     {this.renderOverviewTabContent(hasNextRun, nextRun, job)}
>                   </TabPane>
>                   <TabPane tab={TabKeysEnum.PROFILER} key="profiler">
> ```

if the profiler doesn't work on CC, you can always hide this tab completely on CC. We have a context that you can use, such as
`const isCockroachCloud = useContext(CockroachCloudContext);`  

```
{!isCockroachCloud && (<TabPane>...</TabPane>)}
```

**Comment by adityamaru** [comment]
sorry for the delay here @maryliag I'm going to get to this soon. Other things have bumped this PR from the queue 😓

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNdLoBBLDOButMoZ2S:-NXueD824IUAnV5fuoO7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L19)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I don't see these 2 imports being used anywhere, maybe you forgot to remove from some previous tests?
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNdnPd9hon1IVomMHl:-NXv64Dc30ds7hw9FQka:b-auk94n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L128)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is the intention of this `MEMORY OVERHEAD` to be a warning?
If so, we have some components that make warnings more obvious and you could add a better description.
For example you could add something like this below the SummaryCartItem

```
<InlineAlert intent="warning" title="Creation of a Profile consume additional resources and can potentially negatively impact workload responsiveness." />
```
</blockquote></details>

Nice! Changed to use this now.
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNegi2E6uzNrFU2tKC:-NXunZpbA8MobRbLx9lb:b86nsew) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L267)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if the profiler doesn't work on CC, you can always hide this tab completely on CC. We have a context that you can use, such as
`const isCockroachCloud = useContext(CockroachCloudContext);`  

```
{!isCockroachCloud && (<TabPane>...</TabPane>)}
```
</blockquote></details>

nice, added this check in. I can't seem to add the const at the top level because this is a class component? React shouts at me with:

```
Invalid hook call. Hooks can only be called inside of the body of a function component.
```

**Comment by adityamaru** [comment]
Screenshot 2023-06-14 at 2 10 19 PM

**Review by maryliag — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNegi2E6uzNrFU2tKC:-NXzPR5j0o9UA6SDxNUS:bgosgf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L267)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nice, added this check in. I can't seem to add the const at the top level because this is a class component? React shouts at me with:

```
Invalid hook call. Hooks can only be called inside of the body of a function component.
```
</blockquote></details>

After you made this change, is the page loading as expected? At least for DB Console
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NXzN9Km1haWpT9cCthZ:-NXzN9Km1haWpT9cCth_:b-5nrugo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fec7c0cc2b9e4b03acbaa217a4ffd079c8033bb/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L134)):*
> ```XML
>             <InlineAlert
>               intent="warning"
>               title="This profiles all nodes in the cluster. This operation buffers profiles in memory and should only be run if there is sufficient overhead."
> ```

tagging @florence-crl  to review the warning message
I don't know if the user will know what "sufficient overhead" means and how much is it, so maybe something that matches a few other performance warnings we have:

"This operation buffers profiles in memory for all the nodes in the cluster and can potentially negatively impact workload responsiveness."

**Comment by florence-crl** [comment]
I agree with @maryliag. Please use her recommendation for the warning message:
"This operation buffers profiles in memory for all the nodes in the cluster and can potentially negatively impact workload responsiveness."

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @florence-crl, and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NWNegi2E6uzNrFU2tKC:-NXznDyV-kfPvNt8NF1Q:b-b3nloq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca793e2ccacb0ebd27a1bde032d090273404e854/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L267)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

After you made this change, is the page loading as expected? At least for DB Console
</blockquote></details>

Yup for the DB console its working as expected!
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-NXzN9Km1haWpT9cCthZ:-NXznJ_y30RBDXPtrwwH:b-e8hgap) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fec7c0cc2b9e4b03acbaa217a4ffd079c8033bb/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L134)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

tagging @florence-crl  to review the warning message
I don't know if the user will know what "sufficient overhead" means and how much is it, so maybe something that matches a few other performance warnings we have:

"This operation buffers profiles in memory for all the nodes in the cluster and can potentially negatively impact workload responsiveness."
</blockquote></details>

I don't know whether I'd say it negatively impacts workload responsiveness. I've changed it to say:

"This operation buffers profiles in memory for all the nodes in the cluster and can result in increased memory usage."

@florence-crl is this okay?

**Review by maryliag — APPROVED** [review]
Nice work on this!
:lgtm: 
I will just leave now to @florence-crl the approval on the message itself

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103945#-:-NXztz7u17a5vyq4CGLR:b9vquae)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @florence-crl)

**Comment by florence-crl** [comment]
"This operation buffers profiles in memory for all the nodes in the cluster and can result in increased memory usage."
sounds good to me.

**Comment by adityamaru** [comment]
TFTR!

bors r=maryliag

**Pull request merged**
