### PR TITLE
release-2.0: distsqlrun: fix panic with offsets and topk sort

### LINKED ISSUE #25197: panic: Cannot convert nil datum to EncDatum
Hey,

just recently cockroachdb crashed.

It took a few restarts until it stopped crashing again.

I guess it is related to schema changes, but it doesn't seem to happen always.

```
grep -F '[config]' cockroach-data/logs/cockroach.log
I180501 02:45:45.645510 20686 util/log/clog.go:1001  [config] file created at: 2018/05/01 02:45:45
I180501 02:45:45.645510 20686 util/log/clog.go:1001  [config] running on machine: db-node-1
I180501 02:45:45.645510 20686 util/log/clog.go:1001  [config] binary: CockroachDB CCL v2.0.1 (x86_64-unknown-linux-gnu, built 2018/04/23 18:39:21, go1.10)
I180501 02:45:45.645510 20686 util/log/clog.go:1001  [config] arguments: [cockroach-server/cockroach --cache=25% --max-sql-memory=25% --max-disk-temp-storage=25% --logtostderr=INFO --certs-dir=certs start]
```

```
panic: Cannot convert nil datum to EncDatum

goroutine 86768784 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:137 +0x267
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*memRowContainer).EncRow(0xc43f575900, 0x0, 0xc43c868450, 0xc426759860, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/row_container.go:133 +0x168
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortTopKProcessor).Next(0xc43e10f680, 0xe55f90, 0x2771c80, 0xc45c6ccab0, 0x2791d00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:433 +0x4c7
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x2771bc0, 0xc42f305240, 0x2772a80, 0xc43e10f680, 0x2756f40, 0xc4500438c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:137 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortTopKProcessor).Run(0xc43e10f680, 0xc42d63fb38)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:451 +0x6b
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:470 +0x3a5
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #25197.

Release note (bug fix): fix a panic in the top k sorter that occurred
with offsets.

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25238#-:-LBWX9NL2jBqsnUVU9r_:bnfp4nl)*

**Comment by RaduBerinde** [comment]
:lgtm:

[nit] the release note should be (at least somewhat) understandable by a user. Maybe "Fix a panic caused by certain queries containing OFFSET and ORDER BY"

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25238#-:-LBWY56PEIXWvgcSD7xA:bjvr548)*

**Comment by andreimatei** [comment]
LGTM

please prefix with release-2.0 and make it clear that this is original work on the 2.0 branch and link to the other 2.1 PR.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/logictest/testdata/logic_test/order_by, line 842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25238#-LBWZpwb8Z8rvPCQaASl:-LBWZpwb8Z8rvPCQaASm:b2o6sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b38142140dcfb302913536dd9c8f95d74e0db12/pkg/sql/logictest/testdata/logic_test/order_by#L842)):*
> ```
> ·               limit  1               ·                                                     ·
> 
> # Regression test for #25197
> ```

nit: I generally find these comments annoying when they're not accompanied by an actual description. Say something about an offset (I don't actually know what the bug is).
And stick a subtest while you're at it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25238#-:-LBWZ_FX5FdXiMrMMg0B:b-2kbpln)*

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Comment by jordanlewis** [comment]
Already done in #25240! thx

**Pull request merged**
