### PR TITLE
roachprod: trim down chrony configs

### PR DESCRIPTION
**Pull request by tbg**
- gce: rework chrony config
- aws: update chrony config

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Unfortunately I don't have AWS configured and couldn't make sure my change actually works, does either of you have this set up and is willing to make sure that the VM comes up and that `chronyc sources -v` looks reasonable?

**Comment by stevendanna** [comment]
I can spot-check AWS

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62951#-:-MXBuf4310VYvLRvk8gs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by stevendanna** [comment]
It appears to have started, has a single source that we expect, and is logging:

```
ubuntu@ip-10-12-17-255:~$ chronyc sources -v
210 Number of sources = 1

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current synced, '+' = combined , '-' = not combined,
| /   '?' = unreachable, 'x' = time may be in error, '~' = time too variable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* 169.254.169.123               3   6    37    16  -2346ns[ -136us] +/-  371us
ubuntu@ip-10-12-17-255:~$ sudo systemctl status chrony.service
● chrony.service - LSB: Controls chronyd NTP time daemon
   Loaded: loaded (/etc/init.d/chrony; bad; vendor preset: enabled)
   Active: active (running) since Thu 2021-04-01 10:14:05 UTC; 1min 40s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2707 ExecStop=/etc/init.d/chrony stop (code=exited, status=0/SUCCESS)
  Process: 2715 ExecStart=/etc/init.d/chrony start (code=exited, status=0/SUCCESS)
    Tasks: 1
   Memory: 272.0K
      CPU: 15ms
   CGroup: /system.slice/chrony.service
           └─2723 /usr/sbin/chronyd

Apr 01 10:14:03 ip-10-12-17-255 systemd[1]: Starting LSB: Controls chronyd NTP time daemon...
Apr 01 10:14:03 ip-10-12-17-255 chronyd[2723]: chronyd version 2.1.1 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -DEBUG +ASYNCDNS +IPV6 +SECHASH)
Apr 01 10:14:03 ip-10-12-17-255 chronyd[2723]: Frequency 0.000 +/- 1000000.000 ppm read from /var/lib/chrony/chrony.drift
Apr 01 10:14:05 ip-10-12-17-255 chrony[2715]: chronyd is running and online.
Apr 01 10:14:05 ip-10-12-17-255 systemd[1]: Started LSB: Controls chronyd NTP time daemon.
Apr 01 10:14:07 ip-10-12-17-255 chronyd[2723]: Selected source 169.254.169.123
Apr 01 10:14:07 ip-10-12-17-255 chronyd[2723]: System clock wrong by 0.073883 seconds, adjustment started
Apr 01 10:14:09 ip-10-12-17-255 chronyd[2723]: System clock wrong by -0.016184 seconds, adjustment started
```

**Review by stevendanna — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62951#-:-MXBwNRnDzAbgcPvHlxu:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Thanks!

bors r=stevendanna,erikgrinaker

**Pull request merged**
