### PR TITLE
go.mod: bump github.com/Azure/azure-storage-blob-go to v0.13.0

### PR DESCRIPTION
**Pull request by adityamaru**
Release notes: https://github.com/Azure/azure-storage-blob-go/releases

Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
Sorry for the delay here! This change looks good, but I wonder if it's worthwhile to go all the way to 0.14.0 which fixes a couple of panics given that we don't intend to backport this change (meaning that we have a couple of months to let the release bake?)

**Comment by adityamaru** [comment]
Hehe, they snuck a release under me! I'll bump it to 0.14.0

**Comment by adityamaru** [comment]
TFTR!

bors r=pbardea

**Pull request merged**
