### PR TITLE
ttl: implement TTL scheduled job validation & fixup

### LINKED ISSUE #75428: sql: TTL v1 meta issue
This is a meta issue for the v1 TTL meta issue.

⛔ = blocked
✔️ = in review
♻️ = in progress

# Done
- [x] RFC #75189
- [x] ALTER TABLE ... SET syntax #75262
- [x] ALTER TABLE ... RESET syntax #75429
- [x] Persist metadata #75602
- [x] handle each options
- [x] Placeholder for scheduled job
- [x] (optional) look into protecting scheduled job from being cancelled
- [x] Implement deletion job main logic
- [x] CREATE TABLE ... WITH
- [x] cron management for TTL
- [x] (stretch?) add jitter to scheduled jobs framework - (cancelled) https://cockroachlabs.slack.com/archives/C02DSDS9TM1/p1644461478718559
- [x] DROP TABLE/DATABASE/SCHEMA should also drop the scheduled job. (#76216)
- [x] ALTER TABLE ... SET setting up the automatic column and scheduled job for the first time (#76216)
- [x] ALTER TABLE ... SET modifying TTL expire_after's default expressions (#76216)
- [x] ALTER TABLE ... RESET dropping the TTL automatic column and scheduled job (#76216)
- [x] Break up the TTL job by ranges & add concurrency. (#76487)
- [x] Cancel deletion job if schema change relating to a PK change or TTL parameter change. (#76487)
- [x] Block FKs into a TTL table (#76409)
- [x] implement desired metrics on the TTL table (#76701)
- [x] Implement rate limiting for deletes (#76615)
- [x] backup and restore should re-instate the TTL schedule (in review: #76725)
- [x] range scans are currently unpaginated - we need to paginate them. ( in review: #76726)
- [x] implement feature flag and pause for TTL stops (in review: #76835)
- [x] cleanup: create issues for all post-v1 TODOs and tag in codebase, add unimplemented issue ttl_automatic_expiration, CODEOWNERs, only allow ascending PKs, commit with a release note for TTL (#76918)
- [x] ensure pg_class.reloptions matches SHOW CREATE TABLE (#76918)

## out of scoped
* ttl_expiration_expression (maybe a stretch)
 
# By February 25

- [x] ✔️ Plug in admission priority for DELETE. (#76837)
- [x] ✔️ implement a scan of deleted vs active rows to report as metrics: In addition to the current metrics, we need to write a loop that counts all the expired rows and existing rows in the table. For now, this will be an extra goroutine on the TTL job. This needs to be gated by a table setting and cluster setting. (in review: #76837)

# Stability items
- [x] ✔️ Add telemetry (https://github.com/cockroachdb/cockroach/pull/77108)
- [ ] (happy for someone to take this) add validation builtins (see below); incorporate into `debug doctor`
* Write some builtins which scan the descriptors and validate all tables with TTL have an associated scheduled job & scans row level TTL jobs and ensure they map to a valid table.
* Write some builtins which can create the scheduled jobs you might expect if they don't exist.
- [ ] Re-do performance testing of TTL

## Product Questions

* Figure out how TTL priority configuration should align with `SET ADMISSION PRIORITY` (i.e. using numbers versus enums)
* figure out advice for "child" metrics (since we use `aggmetric` for metrics, child labels are not applied by default... see [slack](https://cockroachlabs.slack.com/archives/D01BCGJH77S/p1645398309969139))
* i'd advocate for calling row-level TTL "preview" / "experimental" for this release. should we?

Epic CRDB-10488

Jira issue: CRDB-12666

### PR DESCRIPTION
**Pull request by otan**
See individual commits for review.

Resolves #75428

Release justification: high pri addition to new functionality

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 3 of 3 files at r2, 3 of 7 files at r3, 1 of 3 files at r4, 3 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @otan, @rafiss, and @stevendanna)

___
*[pkg/sql/check.go, line 590 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MygMoHe2i2Jgi7GSDLI:-MygMoHe2i2Jgi7GSDLJ:bb6y76c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c88bbf3d0b63118da8b24790ea29500d636d6db/pkg/sql/check.go#L590)):*
> ```Go
> 	db, err := p.Descriptors().GetImmutableDatabaseByName(
> 		ctx, p.Txn(), dbName, tree.DatabaseLookupFlags{Required: true},
> 	)
> ```

It seems to me that the entirety of changes in this file, in particular Validate and Repair methods
added to planner, could be made into standalone functions (somewhere under ttl directory).
You only appear to access `p.Descriptors()` and `p.Txn()` from planner.  Why not just pass those as function
arguments?
___
*[pkg/sql/sem/builtins/builtins.go, line 6440 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MygNWu8Aqbqivfnkcct:-MygNWu8Aqbqivfnkccu:b2b72dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c88bbf3d0b63118da8b24790ea29500d636d6db/pkg/sql/sem/builtins/builtins.go#L6440)):*
> ```Go
> 	),
> 
> 	"crdb_internal.repair_ttl_table_scheduled_job": makeBuiltin(
> ```

it would be helpful if you could explain (perhaps in the pr description), under what conditions
do you expect to have invalid schedules?

A schedule could have been made undroppable, for example.  And if you need to delete the schedule
because of alter statement, you don't have to use `drop schedule` statement -- you could just delete
the schedule.

I suppose you might worry about admin directly deleting the schedule.  But that's no different
than admin deleting arbitrary things from system tables -- in general, we don't really protect against that.
And if you're still afraid, then perhaps starting a one-off task to check the sanity (ie.. for each db, validate ttl jobs)  might be sufficient?

Does this worry raise to the level of adding new internal functions?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, @rafiss, and @stevendanna)

___
*[pkg/sql/check.go, line 590 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MygMoHe2i2Jgi7GSDLI:-MyiBggFEf_uwpM3TI9C:b-81trt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c88bbf3d0b63118da8b24790ea29500d636d6db/pkg/sql/check.go#L590)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It seems to me that the entirety of changes in this file, in particular Validate and Repair methods
added to planner, could be made into standalone functions (somewhere under ttl directory).
You only appear to access `p.Descriptors()` and `p.Txn()` from planner.  Why not just pass those as function
arguments?
</blockquote></details>

`EvalContext` does not have access to `Descriptors`. that's all we get in builtins, which is why it's here.



_Code quote:_
```Go
RepairTTLScheduledJobForTable
```
___
*[pkg/sql/sem/builtins/builtins.go, line 6440 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MygNWu8Aqbqivfnkcct:-MyiB1341DhxmGjTuyIQ:b35zuwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c88bbf3d0b63118da8b24790ea29500d636d6db/pkg/sql/sem/builtins/builtins.go#L6440)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

it would be helpful if you could explain (perhaps in the pr description), under what conditions
do you expect to have invalid schedules?

A schedule could have been made undroppable, for example.  And if you need to delete the schedule
because of alter statement, you don't have to use `drop schedule` statement -- you could just delete
the schedule.

I suppose you might worry about admin directly deleting the schedule.  But that's no different
than admin deleting arbitrary things from system tables -- in general, we don't really protect against that.
And if you're still afraid, then perhaps starting a one-off task to check the sanity (ie.. for each db, validate ttl jobs)  might be sufficient?

Does this worry raise to the level of adding new internal functions?
</blockquote></details>


This commit is intended for "repairing" jobs that may have been broken
by a broken schema change interaction.

added

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, @otan, @rafiss, and @stevendanna)

___
*[pkg/sql/check.go, line 590 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MygMoHe2i2Jgi7GSDLI:-MyiEVXs8MtwKTIfXT5O:bp6xd0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c88bbf3d0b63118da8b24790ea29500d636d6db/pkg/sql/check.go#L590)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

`EvalContext` does not have access to `Descriptors`. that's all we get in builtins, which is why it's here.
</blockquote></details>

Couldn't descriptors be added to eval ctx? It's just planner is such a huge interface.
Why add more to it?

**Comment by otan** [comment]
___
*[pkg/sql/check.go, line 590 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MygMoHe2i2Jgi7GSDLI:-MyiFBFX3w6I8_j4gnL2:bu1kaqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c88bbf3d0b63118da8b24790ea29500d636d6db/pkg/sql/check.go#L590)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Couldn't descriptors be added to eval ctx? It's just planner is such a huge interface.
Why add more to it?
</blockquote></details>

i think adding things to EvalContext is just as contentious because it gives more access than it needs to :)
this is how all the other builtins "hack" access to the planner, i'm not inclined to change it for just this PR.

**Comment by miretskiy** [comment]
> i think adding things to EvalContext is just as contentious because it gives more access than it needs to :)
> this is how all the other builtins "hack" access to the planner, i'm not inclined to change it for just this PR.

I don't know... EvalContext already has access to EvalPlanner, that object does things like type resolution... it seems that
it could very well support descriptor resolution.

**Review by stevendanna — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r2, 16 of 16 files at r6, 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77741)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, @otan, @rafiss, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MylWeNk25hGlZuM45mq:-MylWeNl5vWYRN3opwry:boq3gyj) (no related file):*
:lgtm: Left a few non-blocking nitpicks.

---
___
*[pkg/sql/check.go, line 652 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MylUqZWB-JHB4Iv0ZzE:-MylUqZXBlzMirUeoV4j:b9s3gek) ([raw file](https://github.com/cockroachdb/cockroach/blob/662de4eef5350a3a9ab4f1b2bdb372a2bacacf34/pkg/sql/check.go#L652)):*
> ```Go
> 		return pgerror.Newf(
> 			pgcode.Internal,
> 			"scheduled job id %d points to table id %d instead of table id %d",
> ```

[mega nit, don't change it if you don't want to] But the error messages from this function use `scheduled job id`, `schedule id`, and `scheduled job` all to describe the same ID.



_Code quote (from -- commits):_
```
  table points to a valid scheduled job which will action the deletion of
  expired rows.
```
___
*[pkg/sql/ttl/ttlschedule/ttlschedule.go, line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MylWTr0EFS9tLHzqGch:-MylWTr0EFS9tLHzqGci:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb313b940ae18dfc31f82aa8ea962aba0e2287ef/pkg/sql/ttl/ttlschedule/ttlschedule.go#L115)):*
> ```Go
> 		return true, nil
> 	}
> 	// If there is a schedule id mismatch we can drop this table.
> ```





_Suggestion:_
```Go
// If there is a schedule id mismatch we can drop this schedule.
```

**Review by stevendanna — APPROVED** [review]
> Reviewed 3 of 3 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77741)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, @otan, and @rafiss)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77741)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, @otan, @rafiss, and @stevendanna)

___
*[pkg/sql/check.go, line 652 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MylUqZWB-JHB4Iv0ZzE:-Myo2FBD3_oLjTJK_G_W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/662de4eef5350a3a9ab4f1b2bdb372a2bacacf34/pkg/sql/check.go#L652)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[mega nit, don't change it if you don't want to] But the error messages from this function use `scheduled job id`, `schedule id`, and `scheduled job` all to describe the same ID.
</blockquote></details>

Done.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77741)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, @otan, @rafiss, and @stevendanna)

___
*[pkg/sql/ttl/ttlschedule/ttlschedule.go, line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/77741#-MylWTr0EFS9tLHzqGch:-Myo2GXq9fs2KsnuP2Zt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb313b940ae18dfc31f82aa8ea962aba0e2287ef/pkg/sql/ttl/ttlschedule/ttlschedule.go#L115)):*
> ```Go
> 		return true, nil
> 	}
> 	// If there is a schedule id mismatch we can drop this table.
> ```

Done.

**Comment by otan** [comment]
thanks!

bors r+

**Pull request merged**
