### PR TITLE
colexec: simplify .gitignore

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes git ignore all files in `colexec` folder that end with
`.eg.go` which improves the environment setup for the cases when we
change the file names as well as simplifies the maintenance.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
We used to do this previously, FYI: https://github.com/cockroachdb/cockroach/pull/35858

**Comment by yuzefovich** [comment]
I think we have since improved the Makefile, so now we're removing the old generated files when we see that their target has changed. I think `git clean` will also ignore these generated files, so if someone wants to remove only them, they will have to do something like `rm pkg/sql/colexec/*.eg.go` (which I actually have been doing occasionally).

**Comment by jordanlewis** [comment]
Yeah, came here to say this was done on purpose like @irfansharif said (#35858).

I think that this will now manifest as old files being left behind and failing to build, which will probably be just as confusing as the situation right now. I don't think we can assume everyone knows or cares about *.eg.go. It's not a fair solution to say they will have to rm the files themselves...

What happened to deleting the `.eg.go` files automatically when switching branches, didn't we have that at one point?

**Comment by yuzefovich** [comment]
> What happened to deleting the .eg.go files automatically when switching branches, didn't we have that at one point?

Yes, it still happens, and that's why I think this change is acceptable. This way not only nobody should experience any issues with the build but also `.eg.go` files that were renamed/deleted in between branches won't show up in `git status`.

> It's not a fair solution to say they will have to rm the files themselves...

`rm` is not required. I think I mentioned it in a confusing context - sometimes my goal with removal of the files was forcing the execgen to regenerate files without having to clean any other stuff. But the most important use case for me is when I do search for some text or a method usage, and if that shows up in generated files, they clutter the search result, so I often remove all `.eg.go` files. That said, I think we can disregard this for the discussion.

**Comment by jordanlewis** [comment]
Gotcha. LGTM - let's try it.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
