### PR TITLE
sql/types, sql/stats: fix SQLStringFullyQualified for arrays of UDTs

### LINKED ISSUE #137443: sql/stats: histograms of array-of-UDT no longer use fully-qualified type names in json stats output
Starting in v24.2, the output of `SHOW STATISTICS USING JSON` does not fully qualify the type name of **arrays** of UDTs. (Regular UDTs are still fully-qualified.) Here's a repro:

```sql
CREATE TYPE e AS ENUM ('hello', 'howdy', 'hi');
CREATE TABLE ab (a e PRIMARY KEY, b e[]);
INSERT INTO ab VALUES ('hello', '{hello, hi}');
ANALYZE ab;
SELECT stat->'columns', stat->'histo_col_type', stat->'histo_buckets'->0->'upper_bound'
FROM (
  SELECT jsonb_array_elements(statistics) AS stat
  FROM [SHOW STATISTICS USING JSON FOR TABLE ab]
);
```

Before v24.2 this returns:

```
  ?column? |        ?column?        |                            ?column?
-----------+------------------------+------------------------------------------------------------------
  ["a"]    | "defaultdb.public.e"   | "hello"
  ["b"]    | "defaultdb.public.e[]" | "ARRAY['hello':::defaultdb.public.e,'hi':::defaultdb.public.e]"
(2 rows)
```

Starting in v24.2 this returns:

```
  ?column? |       ?column?       |                  ?column?
-----------+----------------------+----------------------------------------------
  ["a"]    | "defaultdb.public.e" | "hello"
  ["b"]    | "public.e[]"         | "ARRAY['hello':::public.e,'hi':::public.e]"
(2 rows)
```

Jira issue: CRDB-45582

### PR DESCRIPTION
**Pull request by michae2**
Starting in v24.2 we added `SQLStringFullyQualified`, but it looks like it didn't work for arrays of user-defined types. This is only used in a few places, including the output of `SHOW STATISTICS USING JSON`.

This commit:
1. fixes `SQLStringFullyQualified` for arrays of UDTs
2. adds the `t.TypeMeta.Name == nil` guard to `SQLString` for composite UDTs
3. sets a formatting flag in `stats.(*JSONStatistic).SetHistogram` so that we get fully-qualified type annotations on histogram upper bounds

No release note because the output of `SHOW STATISTICS USING JSON` isn't documented.

Fixes: #137443

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
(Note that after #125996 I'm not totally convinced that using the fully-qualified names in `SHOW STATISTICS USING JSON` output is still the right thing to do, but it seemed good to at least fix the regression before having that discussion.)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137448#-:-OEFsbon9o7tpiCz0fNT:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @spilchen)

**Comment by michae2** [comment]
TFTR!

bors r=rytaft

**Comment by yuzefovich** [comment]
Looks like `TestLogic_distsql_stats` is flaky on this change.

bors r-

**Comment by michae2** [comment]
> Looks like `TestLogic_distsql_stats` is flaky on this change.
> 
> bors r-

Gah, sorry!

**Comment by michae2** [comment]
Ok, flake should be fixed now. I've opened https://github.com/cockroachdb/cockroach/issues/137713 about the problem with avg_size and column families.

bors r=rytaft

**Comment by michae2** [comment]
Backport to v24.2 depends on https://github.com/cockroachdb/cockroach/pull/127243.

**Pull request merged**
