### PR TITLE
sql: stop dealing with node addresses in DistSQL planning

### PR DESCRIPTION
**Pull request by andreimatei**
And also restrict SpanResolver's interface to returning only
ReplicaDescriptors, not also NodeDescriptors. This is all towards
reducing the physical planning's dependency on gossip - node descriptors
come from gossip.
This patch doesn't yet eliminate the dependency - leaseholder oracles
still use gossip to translate store ids to node ids and to order
replicas, but it's a step in the right direction.

Touches #48432

Release note: None

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49675)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

___
*[pkg/sql/distsql_physical_planner.go, line 526 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8T01_fDb33wetF9S9R:-M8T01_gC8W9bcMD-sB_:b-lb84yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1711352fa5085a7615958fd5492fa6e5026545/pkg/sql/distsql_physical_planner.go#L526)):*
> ```
> // because it's not healthy.
> ```
because it's not compatible?
___
*[pkg/sql/distsql_physical_planner.go, line 536 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8T0NkB-EXcTCnc5s3C:-M8T0NkB-EXcTCnc5s3D:bwd1jrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1711352fa5085a7615958fd5492fa6e5026545/pkg/sql/distsql_physical_planner.go#L536)):*
> ```Go
> 	ExtendedEvalCtx *extendedEvalContext
> 	spanIter        physicalplan.SpanResolverIterator
> 	// Nodes contains info for all NodeIDs that are referenced by any PhysicalPlan
> ```

s/info/status/ ?
___
*[pkg/sql/distsql_physical_planner.go, line 538 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8VkD9W3QtJcQPOdpME:-M8VkD9X9qjZI8qFr7Rn:bjsz3rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1711352fa5085a7615958fd5492fa6e5026545/pkg/sql/distsql_physical_planner.go#L538)):*
> ```Go
> 	// Nodes contains info for all NodeIDs that are referenced by any PhysicalPlan
> 	// we generate with this context.
> 	Nodes map[roachpb.NodeID]NodeStatus
> ```

do you want to rename it to NodeStatuses?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49675)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @miretskiy)

___
*[pkg/sql/distsql_physical_planner.go, line 526 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8T01_fDb33wetF9S9R:-M8W18WF0ojk6IacM3Ud:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1711352fa5085a7615958fd5492fa6e5026545/pkg/sql/distsql_physical_planner.go#L526)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> // because it's not healthy.
> ```
because it's not compatible?
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 536 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8T0NkB-EXcTCnc5s3C:-M8W1BcZ2i0snv_6RK_k:b-wpvw2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1711352fa5085a7615958fd5492fa6e5026545/pkg/sql/distsql_physical_planner.go#L536)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

s/info/status/ ?
</blockquote></details>

well everything is "info" :P
___
*[pkg/sql/distsql_physical_planner.go, line 538 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8VkD9W3QtJcQPOdpME:-M8W1Nq91p-D_l76VkrR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1711352fa5085a7615958fd5492fa6e5026545/pkg/sql/distsql_physical_planner.go#L538)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do you want to rename it to NodeStatuses?
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-:-M8jGMcACymfnz3vHf1h:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @miretskiy)

___
*[pkg/sql/distsql_physical_planner.go, line 858 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8jDDRc7MH8HjCJR58k:-M8jDDRc7MH8HjCJR58l:bkxbzar) ([raw file](https://github.com/cockroachdb/cockroach/blob/f334dc8d02f10e1f4f7cfda9612b4eed22af79a6/pkg/sql/distsql_physical_planner.go#L858)):*
> ```Go
> 
> // nodeVersionIsCompatible decides whether a particular node's DistSQL version
> // is compatible with planVer. It uses gossip to find out the node's version
> ```

Replace the reference to `planVer`  with `dsp.planVersion` or remove.
___
*[pkg/sql/distsql_plan_csv.go, line 121 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8jFX_y82zPQebQN32d:-M8jFX_y82zPQebQN32e:b-p4lcuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd796fcba433ab74f584cbc751a7af62e962c527/pkg/sql/distsql_plan_csv.go#L121)):*
> ```Go
> 	// the nodeID -> nodeAddress map ourselves.
> 	for _, node := range resp.Nodes {
> 		dsp.CheckNodeHealthAndVersion(planCtx, node.Desc.NodeID)
> ```

nit: mention that this call has the side effect of constructing `planCtx.NodeStatuses` and maybe also explicitly ignore the status returned `_ = dsp.CheckNode`

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49675)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @miretskiy)

___
*[pkg/sql/distsql_physical_planner.go, line 858 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8jDDRc7MH8HjCJR58k:-M8kUfEm-AY6Tx0FKH-u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f334dc8d02f10e1f4f7cfda9612b4eed22af79a6/pkg/sql/distsql_physical_planner.go#L858)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Replace the reference to `planVer`  with `dsp.planVersion` or remove.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_plan_csv.go, line 121 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-M8jFX_y82zPQebQN32d:-M8kVJxj4hIGEkATi-qO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd796fcba433ab74f584cbc751a7af62e962c527/pkg/sql/distsql_plan_csv.go#L121)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: mention that this call has the side effect of constructing `planCtx.NodeStatuses` and maybe also explicitly ignore the status returned `_ = dsp.CheckNode`
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49675#-:-M8l0HrQEDqagwFgrdGi:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @miretskiy)

**Pull request merged**
