### PR TITLE
storage: print trace for slow lease requests

### PR DESCRIPTION
**Pull request by tbg**
This experiments with the idea floated in #28282 (the discussion there is
about liveness, but it applies equally to lease requests)

The first three commits are #28519, please don't review them here.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
I'd like to test this (if nothing else, to make sure it doesn't crash the server). But the output should also be helpful.

**Review by andreimatei — COMMENTED** [review]
I'll look at the changes next week if they're still around, but what I can tell you is that my belief is that, if you are tracing (i.e. "recording") a parent span, then the child "FollowsFrom" span is also recording, and will be part of the trace. However, the child span does not need to be finished before the parent, and so you'll only get the log messages that have happened before... something (before the moment where the parent is finished, or before the whole RPC returns a result to the caller, I forgot how things work).
The comment on the lines you linked to seem to suggest that normally the child is expected to finish before the parent, and so I think you're good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28521#-:-LJnjgdA2lIJHZRQPyte:bd2qh0f)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by bdarnell — COMMENTED** [review]
I'm not sure about this - it seems expensive to preemptively trace all lease requests (which scale up with the size of the cluster). Maybe we could do this only with some probability, or only after we have detected slow lease attempts or some other problem (e.g. cancel the first request that hit the 1m "slow" threshold, and start a new one with tracing enabled)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28521#-:-LJoS3c846hD8WYU0trk:b62mgh9)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tschottdorf** [comment]
I don't think making this probabilistic is the right approach (you care about slow requests in particular, the chance of tracing it are slim). I agree with the general concern though. Perhaps we can add a new mechanism that through which ranges can be reported to for a health check. The health check could then try to issue a read, issue a (state-preserving) write, etc. and trace them, reporting the trace on "failure" (FSVO failure). That would also be easier to maintain and to test.

**Pull request closed without merging**
