### PR TITLE
bench/ddl_analysis: de-flake, clean up format, improve usability

### LINKED ISSUE #57771: bench/ddl_analysis: unskip TestBenchmarkExpectation
[(bench/ddl_analysis).TestBenchmarkExpectation failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2509115&tab=buildLog) on [master@c41a2ed503cd31d95bc3ee4365663811772c8bd3](https://github.com/cockroachdb/cockroach/commits/c41a2ed503cd31d95bc3ee4365663811772c8bd3):

```
=== RUN   TestBenchmarkExpectation
    validate_benchmark_data_test.go:100: /go/src/github.com/cockroachdb/cockroach/artifacts/go-build171179183/b997/ddl_analysis.test --test.run=^$ --test.bench=. --test.benchtime=1x
    validate_benchmark_data_test.go:92: expected AlterRole/alter_role_with_3_options to perform KV lookups in [59, 59], got 60
    validate_benchmark_data_test.go:92: expected DropView/drop_2_views to perform KV lookups in [89, 89], got 93
    validate_benchmark_data_test.go:92: expected DropView/drop_3_views to perform KV lookups in [160, 160], got 168
    validate_benchmark_data_test.go:92: expected Grant/grant_all_on_1_table to perform KV lookups in [33, 33], got 41
    validate_benchmark_data_test.go:92: expected Grant/grant_all_on_2_tables to perform KV lookups in [37, 37], got 45
    validate_benchmark_data_test.go:92: expected Grant/grant_all_on_3_tables to perform KV lookups in [41, 41], got 49
    validate_benchmark_data_test.go:92: expected Revoke/revoke_all_on_1_table to perform KV lookups in [33, 33], got 41
    validate_benchmark_data_test.go:92: expected Revoke/revoke_all_on_2_tables to perform KV lookups in [37, 37], got 45
    validate_benchmark_data_test.go:92: expected Revoke/revoke_all_on_3_tables to perform KV lookups in [41, 41], got 49
    validate_benchmark_data_test.go:76: see the --rewrite flag to re-run the benchmarks and adjust the expectations
--- FAIL: TestBenchmarkExpectation (103.82s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestBenchmarkExpectation PKG=./pkg/bench/ddl_analysis TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestBenchmarkExpectation.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by ajwerner**
See individual commits.

Fixes #57771.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
very exciting to have this test back!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61830#-:-MVVAZ8wDkxQm7GX4-dk:bxjmknb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)

___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61830#-MVV9FaF2rUVwkH6SL9m:-MVV9FaF2rUVwkH6SL9n:bevpo2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f78d48ab8ac47500a571c794cd39bbd0bd4cb64/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L104)):*
> ```Go
> 			}
> 
> 			b.ReportMetric(float64(roundTrips)/float64(b.N), "roundtrips")
> ```

i'm not super familiar with custom metrics in benchmarks but it seems like the docs say `If the metric is per-iteration, the caller should divide by b.N` -- so do we need to divide here? it looks like it's outside of the loop

**Review by rafiss — APPROVED** [review]
meant to lgtm, just had a question about tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61830#-:-MVVAhVU7JaFaTMtP54z:bsdwed)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61830)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/bench/ddl_analysis/ddl_analysis_bench.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61830#-MVV9FaF2rUVwkH6SL9m:-MVWXXWq6IFk5IReAwNW:b-fdobuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f78d48ab8ac47500a571c794cd39bbd0bd4cb64/pkg/bench/ddl_analysis/ddl_analysis_bench.go#L104)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm not super familiar with custom metrics in benchmarks but it seems like the docs say `If the metric is per-iteration, the caller should divide by b.N` -- so do we need to divide here? it looks like it's outside of the loop
</blockquote></details>

Note that this variable is accumulated per iteration. The metric is per iteration. We are dividing here in order to fit the API. 

The old code used to only look at the last iteration :grimacing:

**Review by ajwerner — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61830#-:-MVX1q9D7HUKHXCtAQuF:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

**Pull request merged**
