### PR TITLE
sql: support OUT parameters in PLpgSQL UDFs

### LINKED ISSUE #119208: roachtest: pgjdbc failed [expected WrongObjectType error, but got UndefinedFunction]
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13990670?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13990670?buildTab=artifacts#/pgjdbc) on master @ [254dbd247fb8ed352a11439063b29f23a0767f28](https://github.com/cockroachdb/cockroach/commits/254dbd247fb8ed352a11439063b29f23a0767f28):

```
(orm_helpers.go:221).summarizeFailed: 
Tests run on Cockroach v24.1.0-alpha.00000000-dev-254dbd247fb8ed352a11439063b29f23a0767f28
Tests run against pgjdbc REL42.3.3
5785 Total Tests Run
5080 tests passed
705 tests failed
72 tests skipped
185 tests ignored
0 tests passed unexpectedly
2 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: org.postgresql.test.jdbc3.EscapeSyntaxCallModeCallTest.testInvokeFunction - unknown (unexpected)
--- FAIL: org.postgresql.test.jdbc3.EscapeSyntaxCallModeCallIfNoReturnTest.testInvokeFunction - unknown (unexpected)
For a full summary look at the pgjdbc artifacts 
An updated blocklist (pgjdbcBlockList) is available in the artifacts' pgjdbc log
test artifacts and logs in: /artifacts/pgjdbc/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13990670/pgjdbc/1707924175516/1707925718082)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36092

### LINKED ISSUE #119841: roachtest: pg_regress failed
roachtest.pg_regress [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14214555?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14214555?buildTab=artifacts#/pg_regress) on master @ [791969fa98711e681289fa4f61f3d58c8fe44263](https://github.com/cockroachdb/cockroach/commits/791969fa98711e681289fa4f61f3d58c8fe44263):

```
(pg_regress.go:453).runPGRegress: Regression diffs do not match expected output:
--- testdata/regression.diffs
+++ regression.diffs
@@ -226165,18 +226165,18 @@
 +github.com/cockroachdb/cockroach/pkg/sql/routine.go:180: Start()
 +github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:208: nextInputRow()
 +github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:290: Next()
-+github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:128: next()
-+github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:145: nextAdapter()
++github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
++github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
 +github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
-+github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:150: Next()
-+github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:198: Run()
-+github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:723: Run()
-+github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579: Run()
-+github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:305: Run()
++github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126: Next()
++github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250: nextAdapter()
++github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
++github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254: next()
++github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286: Run()
++github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320: Run()
 +github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:911: Run()
 +github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1972: PlanAndRun()
 +github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1687: func3()
-+github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1690: PlanAndRunAll()
 +
 +HINT:  You have encountered an unexpected error.
 +
If the diff is expected, copy regression.diffs from the test artifacts to pkg/cmd/roachtest/testdata/regression.diffs
test artifacts and logs in: /artifacts/pg_regress/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14214555/pg-regress/1709394403037/1709395127050)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pg_regress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36344

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit (mostly) adds the support for INOUT / OUT parameters in PLpgSQL UDFs. OUT parameters are not included into the signature (for overload resolution), but they result in uninitialized variables. Any parameter can be left unnamed but can still be referenced via `$i` notation which is unsupported so far. Unlike for SQL UDFs, in PLpgSQL input and output parameters share the same namespace for duplication check.

Additionally, this commit fixes a few issues:
- for UDFs only input parameters need to be added to the scope of the body
- for procedures, all parameters (including OUT) are used for overload resolution.
- UDF returning VOID with empty body previously would hit an index out of bounds internal error.

Addresses: #100405.
Fixes: #119208.
Epic: CRDB-30611

Fixes: #119841.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First commit should be ignored here - it's from #119608.

**Review by DrewKimball — COMMENTED** [review]
I think it would be good to also add OUT parameters to `pkg/ccl/logictestccl/testdata/logic_test/udf_rewrite` and `pkg/sql/logictest/testdata/logic_test/udf_rewrite`, just to make sure we aren't skipping them during AST rewrites.

> Reviewed 5 of 5 files at r1, 3 of 6 files at r2, 20 of 20 files at r5, 19 of 19 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-:-NrrgLr1EzA-k2tkltOa:bm53g4l)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/create_function.go` line 144 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrqfZfh9CW3CLQNF09y:-NrqfZfh9CW3CLQNF09z:blu2n41) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/sql/create_function.go#L144)):*
> ```Go
> 	signatureTypes := make([]*types.T, 0, len(udfDesc.Params))
> 	for _, param := range udfDesc.Params {
> 		if udfDesc.IsProcedure() || tree.IsInParamClass(funcdesc.ToTreeRoutineParamClass(param.Class)) {
> ```

[nit] Would it be worth adding a helper for these checks?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 343 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrrL_wz7vFYZimCbaT9:-NrrL_wz7vFYZimCbaTA:b-rtybya) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/sql/opt/optbuilder/create_function.go#L343)):*
> ```Go
> 			lastStmt := stmt.AST.Body[len(stmt.AST.Body)-1]
> 			if _, hasReturn := lastStmt.(*ast.Return); hasReturn && len(outParamTypes) > 0 {
> 				panic(returnWithOUTParameterErr)
> ```

We should check this in `plpgsql.go` when building RETURN statements, since otherwise we can only catch when it's the last statement. We're going to have to modify the parser to allow RETURN with no expression (should be pretty simple).
___
*[`pkg/sql/opt/optbuilder/srfs.go` line 212 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-Nrqd_pO3LNKv7M4fFjO:-Nrqd_pO3LNKv7M4fFjP:b-s2054y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4997665a815aa3a5eb7cf0982f15af38d3ea15e3/pkg/sql/opt/optbuilder/srfs.go#L212)):*
> ```Go
> 			// If we have at least two OUT parameters, they specify an implicit
> 			// alias for the RECORD return type.
> 			if numOutParams < 2 {
> ```

If we have one out parameter, shouldn't the error be different? Is this line ever reachable with `numOutParams == 1`?
___
*[`pkg/sql/sem/tree/overload.go` line 271 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-Nrqe9vZ-uooX1n6VrQT:-Nrqe9vZ-uooX1n6VrQU:ba65mdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4997665a815aa3a5eb7cf0982f15af38d3ea15e3/pkg/sql/sem/tree/overload.go#L271)):*
> ```Go
> 	// This is currently either SQL or PL/pgSQL.
> 	Language RoutineLanguage
> 	// RoutineParams contains all parameter information of the routine.
> ```

[nit] Maybe talk about how this is distinguished from the `Types` field, e.g. `Types` is used for matching a routine signature, while `RoutineParams` contains the class, type, and name of each parameter for use in building the routine's body and return type.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 76 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrrND505I2HvNTK05nW:-NrrND505I2HvNTK05nX:b-kinjqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L76)):*
> ```
> 
> statement ok
> CREATE FUNCTION f(INOUT param1 INT, OUT param2 INT) AS $$ BEGIN SELECT 3 INTO param1; END $$ LANGUAGE PLpgSQL;
> ```

Could we have a few cases use assignment `:=` instead of `SELECT INTO`? Could also be good to verify that OUT parameters can be referenced in other statements, like `RAISE`.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the pointers - didn't know about `udf_rewrite` tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-:-Ns6QUX41Gpk4wbPmKKt:b-26brwm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/create_function.go` line 144 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrqfZfh9CW3CLQNF09y:-Ns69sDbEpnnrvW9FASh:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/sql/create_function.go#L144)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Would it be worth adding a helper for these checks?
</blockquote></details>

Good point, done.
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 343 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrrL_wz7vFYZimCbaT9:-Ns6ELF6-RnDUI8W6q6L:b1nqq1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/sql/opt/optbuilder/create_function.go#L343)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We should check this in `plpgsql.go` when building RETURN statements, since otherwise we can only catch when it's the last statement. We're going to have to modify the parser to allow RETURN with no expression (should be pretty simple).
</blockquote></details>

Good point, done.

I did try adjusting the parser to support empty RETURN with this rule:
```
| RETURN ';'
  {
    $$.val = &plpgsqltree.Return{}
  }
```
but it ran into a shift/reduce conflict, so I left a TODO instead.
___
*[`pkg/sql/opt/optbuilder/srfs.go` line 212 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-Nrqd_pO3LNKv7M4fFjO:-Ns683jA9Tp2rCw4K-wZ:b-urxqvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4997665a815aa3a5eb7cf0982f15af38d3ea15e3/pkg/sql/opt/optbuilder/srfs.go#L212)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

If we have one out parameter, shouldn't the error be different? Is this line ever reachable with `numOutParams == 1`?
</blockquote></details>

No, this line is not reachable with one OUT parameter - the function would have `ReturnsRecordType == false`.
___
*[`pkg/sql/sem/tree/overload.go` line 271 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-Nrqe9vZ-uooX1n6VrQT:-Ns68ctgEo1Y9FXt-wFu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4997665a815aa3a5eb7cf0982f15af38d3ea15e3/pkg/sql/sem/tree/overload.go#L271)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Maybe talk about how this is distinguished from the `Types` field, e.g. `Types` is used for matching a routine signature, while `RoutineParams` contains the class, type, and name of each parameter for use in building the routine's body and return type.
</blockquote></details>

Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 76 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrrND505I2HvNTK05nW:-Ns6NGb_B2AZ4X7PPUXo:b-nxemdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L76)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we have a few cases use assignment `:=` instead of `SELECT INTO`? Could also be good to verify that OUT parameters can be referenced in other statements, like `RAISE`.
</blockquote></details>

Good point, added a few cases.

Adding a RAISE stmt actually exposed a problem when the function is used as a data source:
```
        (XX000) internal error: invalid datum type given: RECORD, expected INT8
        encoded_datum.go:195: in DatumToEncDatum()
        DETAIL: stack trace:
        github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:195: DatumToEncDatum()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:333: toEncDatum()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:240: nextGeneratorValues()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:312: Next()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
...
```
I'm not sure why it happens - any ideas? `Builder.finishBuildLastStmt` seems to handle this code when I go into debugger, which adds a projection of two columns from the tuple, yet the project set processor still produces a tuple.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 18 of 18 files at r8, 21 of 21 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-:-Ns78TSfAqgC5PJ1lHhK:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 343 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrrL_wz7vFYZimCbaT9:-Ns76qzU3IHMR4eNpV2R:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/sql/opt/optbuilder/create_function.go#L343)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point, done.

I did try adjusting the parser to support empty RETURN with this rule:
```
| RETURN ';'
  {
    $$.val = &plpgsqltree.Return{}
  }
```
but it ran into a shift/reduce conflict, so I left a TODO instead.
</blockquote></details>

SGTM
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 76 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrrND505I2HvNTK05nW:-Ns76iub7Lb4eELTyKuv:btibuyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L76)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point, added a few cases.

Adding a RAISE stmt actually exposed a problem when the function is used as a data source:
```
        (XX000) internal error: invalid datum type given: RECORD, expected INT8
        encoded_datum.go:195: in DatumToEncDatum()
        DETAIL: stack trace:
        github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:195: DatumToEncDatum()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:333: toEncDatum()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:240: nextGeneratorValues()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:312: Next()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
...
```
I'm not sure why it happens - any ideas? `Builder.finishBuildLastStmt` seems to handle this code when I go into debugger, which adds a projection of two columns from the tuple, yet the project set processor still produces a tuple.
</blockquote></details>

Hm, that feels like something that would be solved by #119616. Can you show the optimizer plan with the `TYPES` option?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119493)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 76 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NrrND505I2HvNTK05nW:-Ns9dj52B1unbt2w7DLJ:b-l8l3gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ef96372d6157f0b5ef2bf21f3898de8bcd039/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L76)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Hm, that feels like something that would be solved by #119616. Can you show the optimizer plan with the `TYPES` option?
</blockquote></details>

```
  • project set
  │ columns: (param1 int, param2 int)
  │ estimated row count: 1
  │ render 0: (f((3)[int]))[tuple{int AS param1, int AS param2}]
  │
  └── • emptyrow
        columns: ()
```
I rebased this PR on top of #119616, and the problem still reproduces.

It's interesting that it seems somewhat non-deterministic. For now, I commented out the couple of cases that trigger this internal error.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Review by mgartner — COMMENTED** [review]
Nice work!

> Reviewed 2 of 6 files at r2, 18 of 18 files at r8, 20 of 21 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-:-NsE4qKM9ulVsxWcL5qy:bdtx8r6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 333 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/119493#-NsE4DpK5XOthJ7OmEA5:-NsE4DpK5XOthJ7OmEA6:b-uo6yha) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b32d40fb95b3985a85938481615c04c5823a7db/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L333)):*
TIL:

> Equal (`=`) can be used instead of PL/SQL-compliant `:=`.

https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-ASSIGNMENT

**Pull request merged**
