### PR TITLE
multitenant: only charge for pgwire egress and update cost model settings

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### tenantrate: revive KV Compute Units

Sharing the same cost model for tenant costing and for KV-side tenant
limiting was a mistake - the latter is meant to estimate CPU usage as
much as possible whereas we want to take arbitrary freedoms with
tenant costing.

This commit revives the `kv.tenant_rate_limiter.*` settings for the
cost model and reverts to using the concept of "KV Compute Units"
inside the rate limiter.

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

#### multitenant: only charge for pgwire egress

This commit changes the tenant cost accounting for pgwire bytes to
only take into account egress; cloud providers don't charge for
ingress. In the future, we can plumb the ingress bytes separately if
needed - as of now we don't plan to charge for ingress.

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

#### tenantcostmodel: update settings

This commit updates settings for the tenant cost model. These values
are derived from the Tenant Pricing Model spreadsheet.

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
___
*[pkg/kv/kvserver/tenantrate/settings.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71094#-MlBsgfJ-OTiiaEc0NaC:-MlBsgfK5LdTqaLQDDtC:bl9kdca) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3fc19c2c85f153ffc1ae7f210f13cd42f7bbec/pkg/kv/kvserver/tenantrate/settings.go#L55)):*
> ```Go
> 		"per-tenant rate limit in Request Units per second if positive, "+
> 			"or Request Units per second per CPU if negative",
> 		-500,
> ```

Not very sure how to go about setting this. Definitely seems like we should increase it, now that writes are 5x more expensive and reads are 2x.

**Comment by RaduBerinde** [comment]
Updated - I added a commit that revives the separate tenantrate limiter settings; cost model changes no longer affect that subsystem.

**Review by andy-kimball — APPROVED** [review]
:lgtm:

Do you foresee any problems if we upgrade from the previous code to this code in our Staging/Production environments?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71094#-:-MlFmQJv7qenxZWenPLj:bupxmev)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/kv/kvserver/tenantrate/settings.go, line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71094#-MlFlmpd-NiqgnwW3ThG:-MlFlmpd-NiqgnwW3ThH:bcn2e2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c92953f8a26a9d397ffe665dc9d438cd8394429/pkg/kv/kvserver/tenantrate/settings.go#L52)):*
> ```Go
> // seconds), so it doesn't need to be adjusted in concert with the rate.
> var (
> 	// kvcuRateLimit was initially set to an absolute value in KV Compute Units/s,
> ```

NIT: Somewhere in here, can you add a comment explaining the difference between the constants used in distributed rate limiting vs. the constants used in KV tenant throttling?

**Review by RaduBerinde — COMMENTED** [review]
TFTR! There should be no problem upgrading.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71094#-:-MlG6rCZAy6JFdyDDtWF:b-caip0r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/tenantrate/settings.go, line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71094#-MlFlmpd-NiqgnwW3ThG:-MlG6p4D8ZXxpQ6pb1mB:b-oq3912) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c92953f8a26a9d397ffe665dc9d438cd8394429/pkg/kv/kvserver/tenantrate/settings.go#L52)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Somewhere in here, can you add a comment explaining the difference between the constants used in distributed rate limiting vs. the constants used in KV tenant throttling?
</blockquote></details>

Done, PTAL

**Pull request merged**
