### PR TITLE
sem/tree: avoid heap allocs during pretty-printing

### PR DESCRIPTION
**Pull request by knz**
Everywhere applicable, change
```go
  for i, xxx := range yyy {
      ctx.FormatNode(&xxx)
  }
```
to:
```go
  for i := range yyy {
      ctx.FormatNode(&yyy[i])
  }
```

Epic: None

### CODE REVIEW

**Comment by postamar** [comment]
I'm naturally OK with this change as it is fairly uncontroversial but I'm curious what its performance impact is, do you know?

**Comment by knz** [comment]
> I'm curious what its performance impact is, do you know?

1 fewer heap allocation per loop iteration every time the statement is pretty-printed, which happens as a side effect of each execution when we use execution tracing.

Note that the *main* reason for this PR is to _set an engineering standard_ (i.e. build habits). The next step here would be a linter.

**Comment by postamar** [comment]
I might have guessed that, however since this is about building habits: I'm not trying to be snarky but a good habit is also to collect quantitative data to support assertions of a performance improvement. In this case fortunately the change is straightforwardly beneficial, so it's probably pointless, and I won't belabour my entirely academic point further.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95245)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @chengxiong-ruan, @e-mbrown, and @knz)

___
*[`pkg/sql/alter_function.go` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95245#-NNbzuL-3nue8FIiegDJ:-NNbzuL-3nue8FIiegDK:b-rlexj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a32376e6a136064d927de0be925ffb62e13db79/pkg/sql/alter_function.go#L141)):*
> ```Go
> 	}
> 
> 	maybeExistingFuncObj := fnDesc.ToFuncObj()
> ```

should `ToFuncObj` be updated to return the pointer? it seems like in both usages of it, we need to immediately convert it to a pointer anyway

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95245)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @chengxiong-ruan, @e-mbrown, and @rafiss)

___
*[`pkg/sql/alter_function.go` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95245#-NNbzuL-3nue8FIiegDJ:-NNc9TJc0x9e2nmPPdOQ:b-jqt3s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a32376e6a136064d927de0be925ffb62e13db79/pkg/sql/alter_function.go#L141)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should `ToFuncObj` be updated to return the pointer? it seems like in both usages of it, we need to immediately convert it to a pointer anyway
</blockquote></details>

That works! Done.

**Review by chengxiong-ruan — APPROVED** [review]

**Review by rafiss — APPROVED** [review]
ty!

**Comment by knz** [comment]
Thanks!

bors r=chengxiong-ruan,rafiss

**Pull request merged**
