### PR TITLE
ui: update browser tab on tab change

### LINKED ISSUE #71991: ui: SQL Activity Page browser tabs are not being updated
When navigating between the SQL Activity tabs, the browser tab name is not being properly updated. See recorded video below:

https://user-images.githubusercontent.com/9267198/138925157-0f8b14fe-c107-4170-bf9b-be25500bb17d.mov

### PR DESCRIPTION
**Pull request by maryliag**
Previously, the browser tab title was not being updated
when a differen tab was selected on SQL Activity tab.
This commits make sure the browser tab is updated.

Fixes #71991

Release note (bug fix): Update browser tab when SQL Activity
tab is changed.

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
Hmm when I first go to the SQL Activity page, it shows the Sessions tab but the browser still says "Cockroach Console". Is that supposed to be the case?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72516#-:-Mo-PEZZDJGG6SIL5UnP:b-nizroq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Review by maryliag — COMMENTED** [review]
Fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72516#-:-Mo-WS5C7n4eho4ocf_O:b-886gsx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin)

**Review by lindseyjin — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Review by lindseyjin — APPROVED** [review]
LGTM! :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72516#-:-Mo-_rC1-db-zrPdBLda:b-h9m0zy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by maryliag** [comment]
blathers backport 21.2

**Pull request merged**
