### PR TITLE
[wip] show number of CPU cores in node list

### PR DESCRIPTION
**Pull request by vilterp**
image

Also, there might be a better way to do this than saving it in NodeSummary every ten seconds (i.e. just on the RPC's codepath). Thoughts, @mrtracy?

TODOs:
- [ ] design work to figure out how / where best to show this (cc @josueeee)

### CODE REVIEW

**Review by bdarnell — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27662)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/status/recorder.go, line 498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27662#-LHenIiK3fdA_e1MFfFv-r2-498:-LHfFv0U8EI75VoFXa9q:bvkgwty) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc5f44c20ed2195f738f51d47d0f39520337c114/pkg/server/status/recorder.go#L498)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

`logical_cores = physical_cores*2` seems to be the rule for Intel (according to https://en.wikipedia.org/wiki/Hyper-threading, and it works on my laptop), but may not be the case for e.g. AMD. Not sure how best to handle this.
</blockquote></details>

If the UI says "cores", we should report the number of cores, not the number of threads. And we need to be careful about doubling things when another layer has already doubled them (trust the libraries we're using to do a better job of handling things like intel vs amd than we can)

However, the `gopsutil` library doesn't look like a reliable source for this information. [On linux](https://github.com/shirou/gopsutil/blob/6ddbb8c5d870fb1d7f25cc0801000897cc0ac943/cpu/cpu_linux.go#L110) as far as I can tell, it gives you threads instead of cores (one `cpuInfo` object per thread, and `cpuInfo.Cores` is always 1). Darwin, on the other hand, returns one `cpuInfo` object per socket, sets `cpuInfo.Cores` correctly, but doesn't report threads at all. There's an [open issue](https://github.com/shirou/gopsutil/issues/551) about it being incorrect on windows too.

**Comment by vilterp** [comment]
Thanks for pointing out these problems Ben. I changed it to use https://golang.org/pkg/runtime/#NumCPU, which returns 8 on my Mac (4 cores * 2 for hyperthreading), which seems to indicate that it's returning what's called "threads", although the Go docs refer to it as "logical CPUs". Like the gopsutil library, it has different implementations for different OSs (https://github.com/golang/go/search?p=2&q=ncpu&unscoped_q=ncpu), but I have more confidence in its reliability, given that it's in the Go stdlib.

As for what to call it, "threads" may be the correct term, but without qualification I think people would probably think it's referring to how many OS threads are running, so I'm inclined to go with "Cores".

**Review by bdarnell — COMMENTED** [review]
> As for what to call it, "threads" may be the correct term, but without qualification I think people would probably think it's referring to how many OS threads are running, so I'm inclined to go with "Cores".

Agreed that "threads" is confusing, but we can't call it "cores" because that has a specific, different meaning in this context. I think "CPUs" may be the best label to use here.

(And I think we do want to report CPUs/threads instead of cores - CPUs are tangible things (units of execution and scheduling), cores are just an implementation detail)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27662#-:-LI2uPLnAq6IMK4Mmn7n:b-8tivf9)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by vilterp** [comment]
Ok, changed it to CPUs. That does evoke a unit of execution & scheduling without getting into the implementation details; seems like the Go authors may have come to the same conclusion by calling the stdlib function `NumCPU`…

@petermattis I know you had asked for this; do you agree on terminology?

**Comment by petermattis** [comment]
> I know you had asked for this; do you agree on terminology?

That's a bikeshed I do not wish to paint. I'll trust the folks on this thread to choose a good color.

**Comment by vilterp** [comment]
Closed in favor of #28189, so we can see a few related new metrics in the node list.

**Pull request closed without merging**
