### PR TITLE
roachtest: deduplicate descriptor validation check

### PR DESCRIPTION
**Pull request by msbutler**
Epic: none

Release note: none

### CODE REVIEW

**Review by renatolabs — APPROVED** [review]
:lgtm:

Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116070#-:-NlOhF3O8zJ_jxVhJTv3:b9benhj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong)

**Comment by msbutler** [comment]
TFTR! 

bors r=renatolabs

**Comment by msbutler** [comment]
bors cancel

**Comment by msbutler** [comment]
blathers backport 23.2

**Pull request merged**
