### PR TITLE
rfcs: new RFC on shared-process deployments for cluster virtualization

### PR DESCRIPTION
**Pull request by knz**
Text of RFC: https://github.com/knz/cockroach/blob/20220720-rfc-in-memory-tenants/docs/RFCS/20220720_shared_process_deployments.md

Some prototype work ongoing here: #84608.
Epic: CRDB-14537

### CODE REVIEW

**Review by ajstorm — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7QkZkL1DHlj3Gd1GYr:-N7QkZkL1DHlj3Gd1GYs:bs0kgx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L13)):*
> ```Markdown
> same CockroachDB process serving the KV layer.
> 
> This change is meant to (eventually) power a multitenant experience in
> ```

Nit: Can we also explicitly tie this to the unified architecture project in this summary?  Internal readers may find an explicit linkage helpful to frame this within a larger body of work.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7QpMg92JgfLldUbXRJ:-N7QpMg92JgfLldUbXRK:b61ewus) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L124)):*
> ```Markdown
> deployment, a maximum of 2 of these in-memory tenants will be
> available to external network clients: one for application workloads
> and one for system operators. This will power the new "multi-tenant
> ```

Nit: Let's be consistent with terminology and call this the "unified architecture".
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7QpYMT6n1pVzkEAP5e:-N7QpYMT6n1pVzkEAP5f:b-x736r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L128)):*
> ```Markdown
> self-hosted deployments. Serving more tenants over the network will be
> restricted via a license check, reserved for exclusive use inside
> Cockroach Cloud.
> ```

Nit: Should we be more explicit here and say that it's only for CC Serverless?
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7QqIqnC7ve5mDSoav9:-N7QqIqnC7ve5mDSoavA:b-4lbrv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L164)):*
> ```Markdown
> Tenant names will be introduced via a new UNIQUE column in `system.tenants`.
> 
> An entry will also be materialized for the system tenant with ID 1 and a
> ```

Nit: Should we restrict this "On newly created clusters..."? Above we talk about how the system tenant will not always be ID 1. 
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7Qsx1Y4rkhfHcEZBss:-N7Qsx1Y4rkhfHcEZBst:bcrn716) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L179)):*
> ```Markdown
> on a value separate from the tenant ID, and that can be changed at run time.
> 
> This will become the new ADMIN/GUEST capability, and will be stored
> ```

Nit: Instead of "ADMIN/GUEST" could we call this something more generic like "tenant privileges" capability?  We may want to expand this beyond two modes in the future.  Also, what about NONADMIN or UNPRIVILEGED as opposed to GUEST.  GUEST may be difficult to interpret for some who are unaware that the alternative is ADMIN.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7Qu8tnBgDCf9AGUFm5:-N7Qu8tnBgDCf9AGUFm6:b-wakf9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L183)):*
> ```Markdown
> 
> To support the restriction on network access, we will also introduce a
> new PRIVATE/EXPORTED capability. Only tenants with cap EXPORTED will
> ```

Nit: Call this "tenant visibility"?  Also, does it make sense to go with HIDDEN/VISIBLE or PRIVATE/VISIBLE instead of EXPORTED?
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7R14fp3AwDdHmZu4kc:-N7R14fp3AwDdHmZu4kd:bo5twh) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L191)):*
> ```Markdown
> privileged operations to any secondary tenant. A candidate use case
> could be granting the capability to view KV-level timeseries to a
> non-ADMIN tenant.
> ```

Do we need any syntax around tenant privileges/visibility?  Will we ever want the ability to change a tenant from privileged to non-privileged (aside from the migration case cited above) or the reverse?  
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7R50yx4Scxa2YUBqaA:-N7R50yx4Scxa2YUBqaB:be4ozpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L210)):*
> ```Markdown
> Also, there will be a reference counter (incremented by internal SQL
> queries and network connection), and the registry would stop a SQL
> server some time after its reference count drops to zero.
> ```

This reference counting sounds interesting (and powerful) but I wonder if it's overkill for a first cut.  Did you ever contemplate an explicit "stop tenant" command to shut down a SQL server?  The benefits to this approach is that there's less to implement in the short term, and the behavior is more predictable.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7RAcRQ1XefzzspDQLH:-N7RAcRQ1XefzzspDQLI:beh4fx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L321)):*
> ```Markdown
> or, alternatively,
> 
> `AS TENANT <tenantname> <string>`  (where the string is a quoted SQL statement), e.g. `AS TENANT app $$SELECT * FROM system.users$$`
> ```

What authorization, if any, would we need to perform when running this statement?  Does the caller need to come from an ADMIN tenant to act on a non-ADMIN tenant?

**Review by ajstorm — COMMENTED** [review]
Very nice to see this!  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-:-N7RD83W9xJS-un2ej-E:b-9wo8i9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @nvanbenschoten, and @rafiss)

**Review by knz — COMMENTED** [review]
I'll only process `nit` comments in batches - leaving them as open comments for now.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-:-N7RHXz3-SFhEBFY9BX5:b26r75g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7Qu8tnBgDCf9AGUFm5:-N7RGtMN6QpzqgbBJfcw:bo8c0oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L183)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Call this "tenant visibility"?  Also, does it make sense to go with HIDDEN/VISIBLE or PRIVATE/VISIBLE instead of EXPORTED?
</blockquote></details>

I have thought _hard_ about using the term "visibility" initially, and I am 70%+ confident it's not the right abstraction. If we really want to be pedantic, I'd go for the full words "WITHOUT_NETWORK" / "WITH_NETWORK".
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7R14fp3AwDdHmZu4kc:-N7RHAuVBhl1_i28Wrlt:b-u8d9j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L191)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we need any syntax around tenant privileges/visibility?  Will we ever want the ability to change a tenant from privileged to non-privileged (aside from the migration case cited above) or the reverse?  
</blockquote></details>

Not in a first iteration. Added words about it.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7R50yx4Scxa2YUBqaA:-N7RHDAk9Rp4xWpNoRtt:b-ix10oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L210)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This reference counting sounds interesting (and powerful) but I wonder if it's overkill for a first cut.  Did you ever contemplate an explicit "stop tenant" command to shut down a SQL server?  The benefits to this approach is that there's less to implement in the short term, and the behavior is more predictable.
</blockquote></details>

the TTL would be configurable. If folk want the servers to linger they can configure the TTL to "forever". It's generally bad design to introduce registry data structures without an invalidation protocol, so I'm not going to do that.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7RAcRQ1XefzzspDQLH:-N7RHPvj9qJ5GSfPXyyV:b-ddgpbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L321)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

What authorization, if any, would we need to perform when running this statement?  Does the caller need to come from an ADMIN tenant to act on a non-ADMIN tenant?
</blockquote></details>

Good Q. Added a sentence about that. Note that David is requesting we do not provision this facility too early. We might cut it from the RFC altogether.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7SA7H_BlPWbyzEnKbJ:-N7SA7H_BlPWbyzEnKbK:bca45y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a09cf18057e067becde5bbc10421e1497184fe2d/docs/RFCS/20220720_in_memory_tenants.md#L129)):*
> ```Markdown
> everywhere" deployment model for Cockroach Cloud Dedicated, and
> self-hosted deployments. Serving more tenants over the network will be
> restricted via a license check, reserved for exclusive use inside
> ```

Why not let everybody use as many tenants as they want (perhaps conditioned on having a license)?
In particular, if the Obs Service is to use tenants for anything, I think they need to be available broadly.

**Review by knz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7SA7H_BlPWbyzEnKbJ:-N7UlZ6i2-9c7OnkU9Mb:bcw7wm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a09cf18057e067becde5bbc10421e1497184fe2d/docs/RFCS/20220720_in_memory_tenants.md#L129)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Why not let everybody use as many tenants as they want (perhaps conditioned on having a license)?
In particular, if the Obs Service is to use tenants for anything, I think they need to be available broadly.
</blockquote></details>

I think you're right. I re-reviewed our licensing change proposal https://docs.google.com/document/d/1UQDSAqaYGE-bfeMQbz4nPz0cveaFSxo2YP0fL0Vqo0k/edit

and I see that indeed there's no mention of locking a specific number of tenants. I'll remove this limit in the next batch of updates.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7SA7H_BlPWbyzEnKbJ:-N7Vj39s98-NXgUQxRCB:b71gov3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a09cf18057e067becde5bbc10421e1497184fe2d/docs/RFCS/20220720_in_memory_tenants.md#L129)):*
> I'll remove this limit in the next batch of updates.

IMO, it's not just about what's possible (and allowed as part of our licensing), it's also about what we're willing (and able) to test.  Unless we're prepared to properly validate scenarios where we run a large number of in-memory tenants through some fairly rigorous testing, I'd think we'd be better off blocking the creation of more than one tenant.

I could totally imagine us revisiting this at some point down the road when (a) we've seen that there's customer demand for this, and (b) we have the means to properly test it.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7SA7H_BlPWbyzEnKbJ:-N7W8cIJAgjJKfogoSnY:br33k9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a09cf18057e067becde5bbc10421e1497184fe2d/docs/RFCS/20220720_in_memory_tenants.md#L129)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

> I'll remove this limit in the next batch of updates.

IMO, it's not just about what's possible (and allowed as part of our licensing), it's also about what we're willing (and able) to test.  Unless we're prepared to properly validate scenarios where we run a large number of in-memory tenants through some fairly rigorous testing, I'd think we'd be better off blocking the creation of more than one tenant.

I could totally imagine us revisiting this at some point down the road when (a) we've seen that there's customer demand for this, and (b) we have the means to properly test it.
</blockquote></details>

Imposing an arbitrary limit because larger values haven't been tested is an unusual thing to do. We can use whatever language we want in our docs, and print messages on the command line, etc, but otherwise let people have fun.

**Comment by knz** [comment]
@lunevalex is going on record elsewhere saying that we should run all dedicated / self-hosted customers using the serverless model, that is, with separate processes for all secondary tenants. This would make this RFC unnecessary and I could simply close this PR altogether.

Thoughts?

**Comment by ajstorm** [comment]
> This would make this RFC unnecessary and I could simply close this PR altogether.

Until we have a plan for something that would replace this, we should both leave this open, and continue working on it.

> Imposing an arbitrary limit because larger values haven't been tested is an unusual thing to do. We can use whatever language we want in our docs, and print messages on the command line, etc, but otherwise let people have fun.

I'm fine with that, so long (a) product is fine with it, and (b) we mark it as being in "preview" mode.

**Review by knz — COMMENTED** [review]
In light of various convos with the tenant streaming and obs inf teams, I've simultaneously reduced the scope of the RFC (we don't need tenant capabilities in *this* RFC) and generalized the mechanisms (so we can use them in standalone SQL pods too, for help in testing tenant-to-tenant replication).

It's time to get the RFC more seriously reviewed. We'd like a prototype of this to make its way to 22.2, or very early in the 23.1 cycle.

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-:-N96MeTB5rzq6wB8fEvA:b-s2m4k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7QkZkL1DHlj3Gd1GYr:-N96Lap7AQF-fh1irovN:bqmexye) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L13)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Can we also explicitly tie this to the unified architecture project in this summary?  Internal readers may find an explicit linkage helpful to frame this within a larger body of work.
</blockquote></details>

We're going to decouple this from unified architecture, and instead focus on tenant-to-tenant repl as the main use case.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7QpMg92JgfLldUbXRJ:-N96LvSzEAzecdudLBsS:b-5jp7rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L124)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Let's be consistent with terminology and call this the "unified architecture".
</blockquote></details>

Removed the sentence.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7Qsx1Y4rkhfHcEZBss:-N96MPr4Bs2YV7ZX2uta:bg1tjj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L179)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Instead of "ADMIN/GUEST" could we call this something more generic like "tenant privileges" capability?  We may want to expand this beyond two modes in the future.  Also, what about NONADMIN or UNPRIVILEGED as opposed to GUEST.  GUEST may be difficult to interpret for some who are unaware that the alternative is ADMIN.
</blockquote></details>

We don't need tenant capabilities for this RFC. I removed this section entirely.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7RAcRQ1XefzzspDQLH:-N96MWNC2YEFIzIFXi6f:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff6038bb9828438396833c01609416dc92db17/docs/RFCS/20220720_in_memory_tenants.md#L321)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Good Q. Added a sentence about that. Note that David is requesting we do not provision this facility too early. We might cut it from the RFC altogether.
</blockquote></details>

Removed.
___
*[`docs/RFCS/20220720_in_memory_tenants.md` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N7SA7H_BlPWbyzEnKbJ:-N96MF1q9PfPs4bKO6c0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a09cf18057e067becde5bbc10421e1497184fe2d/docs/RFCS/20220720_in_memory_tenants.md#L129)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Imposing an arbitrary limit because larger values haven't been tested is an unusual thing to do. We can use whatever language we want in our docs, and print messages on the command line, etc, but otherwise let people have fun.
</blockquote></details>

Done.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_dynamic_tenant_servers.md` line 257 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N97w4h-4vFVRCVHFMdX:-N97w4h-4vFVRCVHFMdY:b-st3eld) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaab297f2149759bb88c94c00afba288d4b9b0c/docs/RFCS/20220720_dynamic_tenant_servers.md#L257)):*
> ```Markdown
> 
> Internally, the HTTP service will route incoming requests to a
> different HTTP request mux depending on the `tenant` cookie, using the
> ```

For `/api/v2/` might be worth also supporting a header-based approach.
___
*[`docs/RFCS/20220720_dynamic_tenant_servers.md` line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N97zoQy8r3gGraBABBd:-N97zoQy8r3gGraBABBe:b-pb7eme) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaab297f2149759bb88c94c00afba288d4b9b0c/docs/RFCS/20220720_dynamic_tenant_servers.md#L265)):*
> ```Markdown
> to set the `tenant` cookie to the specified value (e.g. `/tenant/app`
> sets cookie to `app`, `/tenant/system` sets cookie to `/system`) and
> redirect to the `/` URL.
> ```

Will it be possible to query the list of known tenant names without a session? My assumption is not since that data itself lives in SQL.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @dhartunian, @knz, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_dynamic_tenant_servers.md` line 257 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N97w4h-4vFVRCVHFMdX:-N98aL18BqP85XheM8vm:b-rqhu7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaab297f2149759bb88c94c00afba288d4b9b0c/docs/RFCS/20220720_dynamic_tenant_servers.md#L257)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

For `/api/v2/` might be worth also supporting a header-based approach.
</blockquote></details>

I'll add it.
___
*[`docs/RFCS/20220720_dynamic_tenant_servers.md` line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N97zoQy8r3gGraBABBd:-N98aBCn3VRMldPiGlMG:bliv4t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaab297f2149759bb88c94c00afba288d4b9b0c/docs/RFCS/20220720_dynamic_tenant_servers.md#L265)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Will it be possible to query the list of known tenant names without a session? My assumption is not since that data itself lives in SQL.
</blockquote></details>

This is a good insight!

Yes, we definitely need a new endpoint to query the list of tenant names (if only to build the selector in the front-end).
We do not need a session for that. We can make the endpoint talk to the tenant registry directly.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @dhartunian, @nvanbenschoten, and @rafiss)

___
*[`docs/RFCS/20220720_dynamic_tenant_servers.md` line 257 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N97w4h-4vFVRCVHFMdX:-N9Vp-lfA7GAIdkYsZEx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaab297f2149759bb88c94c00afba288d4b9b0c/docs/RFCS/20220720_dynamic_tenant_servers.md#L257)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'll add it.
</blockquote></details>

Done.
___
*[`docs/RFCS/20220720_dynamic_tenant_servers.md` line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/84700#-N97zoQy8r3gGraBABBd:-N9Vp0xK5xm4CTaQR-Yr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaab297f2149759bb88c94c00afba288d4b9b0c/docs/RFCS/20220720_dynamic_tenant_servers.md#L265)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is a good insight!

Yes, we definitely need a new endpoint to query the list of tenant names (if only to build the selector in the front-end).
We do not need a session for that. We can make the endpoint talk to the tenant registry directly.
</blockquote></details>

Done.

**Review by stevendanna — APPROVED** [review]
I'll admit that I just skimmed it again and didn't do a deep review. Let's commit this for posterities sake as it represents what was implemented.

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Pull request merged**
