### PR TITLE
distsql: refactor flow.StartSync()

### PR DESCRIPTION
**Pull request by andreimatei**
It was burdening the caller with also calling Flow.Wait(), although
that's bizarre for a sync method. No longer.
Also rename some Flow methods.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
LGTM minus the renaming

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-:-LVDm9Gx21S_wkkl5NPW:b-k1hzjz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/flow.go, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-LVDlC992Y-6x47iiW1L:-LVDlC992Y-6x47iiW1M:b6itsel) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9bb43f21b03137c89e26bee9d7d2fb4f207684/pkg/sql/distsqlrun/flow.go#L598)):*
> ```Go
> 	if len(f.processors) > 0 {
> 		// Everything but the last processor was started by startInternal(). We need
> 		// to manuall start the last one.
> ```

`s/manuall/manually`
___
*[pkg/sql/distsqlrun/flow.go, line 612 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-LVDlP8c7FxAUuDRABHg:-LVDlP8c7FxAUuDRABHh:bpk4n14) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9bb43f21b03137c89e26bee9d7d2fb4f207684/pkg/sql/distsqlrun/flow.go#L612)):*
> ```Go
> // the flow's goroutines are done.
> // The caller needs to call f.Cleanup().
> func (f *Flow) Run(ctx context.Context, doneFn func()) error {
> ```

I think this renaming is more confusing than helpful. It's difficult to tell the difference between `Run` and `Start` so I would just keep it as `Start{A}Sync`

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/distsqlrun/flow.go, line 612 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-LVDlP8c7FxAUuDRABHg:-LVDrtfF715_A_qSmscX:b-kijy70) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9bb43f21b03137c89e26bee9d7d2fb4f207684/pkg/sql/distsqlrun/flow.go#L612)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this renaming is more confusing than helpful. It's difficult to tell the difference between `Run` and `Start` so I would just keep it as `Start{A}Sync`
</blockquote></details>

It could also be `MainLoop` which is clear

**Review by andreimatei — COMMENTED** [review]
TFTRs

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-:-LVFcf9c1YuVbWyorOZ_:b-6rbzir)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/flow.go, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-LVDlC992Y-6x47iiW1L:-LVFccsy9b6hBESkLDac:bdzw2k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9bb43f21b03137c89e26bee9d7d2fb4f207684/pkg/sql/distsqlrun/flow.go#L598)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/manuall/manually`
</blockquote></details>

it's gone in the next commit
___
*[pkg/sql/distsqlrun/flow.go, line 612 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-LVDlP8c7FxAUuDRABHg:-LVFaxCC29OxRN6hliBi:bb0ima1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9bb43f21b03137c89e26bee9d7d2fb4f207684/pkg/sql/distsqlrun/flow.go#L612)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It could also be `MainLoop` which is clear
</blockquote></details>

mmm I don't really like `MainLoop`. It's not even particularly clear who's loop we're talking about, this being a Flow and not a Processor.
I think `Run`/`Start` is  right... Definitely better than `StartSync / StartAsync` :P
I've improved their comments and cross-link.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33412#-:-LVFcyRP67FS_KWw85YK:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
