### PR TITLE
mvcc: continue scanning if ReverseScan falls off end of range

### LINKED ISSUE #17825: Sometimes tables seem empty!
Sometimes the following query returns zero rows despite there being 100's of thousands of rows in the table:

    SELECT * FROM bank.accounts ORDER BY id DESC LIMIT 1;

This issue is under discussion on the forum here:
https://forum.cockroachlabs.com/t/sometimes-my-700-000-row-table-seems-empty/900

I will add details to reproduce here in a moment....

Here we go:

Machine: amd64, 2GByte RAM, 128GB SSD.

OS: Debian GNU/Linux 9

Kernel: Linux jhctech2 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

cockroachdb: 

$ cockroach version
Build Tag:    v1.0.4
Build Time:   2017/07/27 17:54:36
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  5b757262d33d814bda1deb2af20161a1f7749df3
Build Type:   release

Node.js: v8.2.1

I start three instances of cockroach on this machine, as per the getting started instructions on the web site:

$ nohup cockroach start --certs-dir=certs --store=node1 --host=localhost --port=26257 --http-port=8080 --http-host=localhost &
$ nohup cockroach start --certs-dir=certs --store=node2 --host=localhost --port=26258 --http-port=8081 --http-host=localhost --join=localhost:26257 &
$ nohup cockroach start --certs-dir=certs --store=node3 --host=localhost --port=26259 --http-port=8082 --http-host=localhost --join=localhost:26257 &

I start filling up the example bank account table, 100 inserts persecond, from node.js using pg and this code:

    const fs = require('fs')

    const config = {
    host: 'localhost',
    port: 26257,
    user: 'root',
    database: 'bank',

    // this object will be passed to the TLSSocket constructor
    ssl: {
        rejectUnauthorized: false,
        ca: fs.readFileSync('/home/rsm/certs/ca.crt').toString(),
        key: fs.readFileSync('/home/rsm/certs/client.root.key').toString(),
        cert: fs.readFileSync('/home/rsm/certs/client.root.crt').toString()
    }
    }

    const { Pool } = require('pg')

    const pool = new Pool(config)

    const query = {
    text: 'INSERT INTO accounts(id, balance) VALUES($1, $2)',
    values: [24, 666]
    }

    setInterval(function () {
    query.values[0]++
    pool.query(query, (err, res) => {
        if (err) {
        console.log(err.stack)
        } else {
        console.log(res.rows)
        }
    })
    }, 10)

    pool.query('SELECT * FROM accounts', (err, res) => {
    if (err) {
        throw err
    }
    console.log('accounts:', res.rows)
    })

Then start querying the table for the last record using the sql shell:

    root@:26257/> SELECT * FROM bank.accounts ORDER BY id DESC LIMIT 1;
    +--------+---------+
    |   id   | balance |
    +--------+---------+
    | 788130 |     666 |
    +--------+---------+
    (1 row)
    root@:26257/> SELECT * FROM bank.accounts ORDER BY id DESC LIMIT 1;
    +----+---------+
    | id | balance |
    +----+---------+
    +----+---------+
    (0 rows)
    root@:26257/> SELECT * FROM bank.accounts ORDER BY id DESC LIMIT 1;
    +--------+---------+
    |   id   | balance |
    +--------+---------+
    | 875072 |     666 |
    +--------+---------+
    (1 row)

NOTE: The EMPTY row returned. This happens one in 20 or thrirty queries.

The following code that makes the same query produces the same error from pg.

    const fs = require('fs')

    const config = {
    host: 'localhost',
    port: 26257,
    user: 'root',
    database: 'bank',

      ssl: {
          rejectUnauthorized: false,
          ca: fs.readFileSync('/home/rsm/certs/ca.crt').toString(),
          key: fs.readFileSync('/home/rsm/certs/client.root.key').toString(),
          cert: fs.readFileSync('/home/rsm/certs/client.root.crt').toString()
      }
    }

    const { Pool } = require('pg')

    const pool = new Pool(config)

    let previousId = 0;

    setInterval(function () {
    pool.query('SELECT * FROM bank.accounts ORDER BY id DESC LIMIT 1;', (err, res) => {
        let id = 0;
        if (err) {
        throw err
        }
        if (res.rows.length < 1) {
        console.log('Error: Empty result');
        } else {
        id = res.rows[0].id
        if (id < previousId) {
            console.log('Error: Low result')
        } else {
            previousId = id
        }
        console.log(res.rows[0].id)
        }
    })
    }, 100)

### PR DESCRIPTION
**Pull request by nvb**
Fixes #17825.

When an `mvccGetInternal` call scans off the end of a key range
while attempting to find a value at a certain timestamp,
`MVCCReverseScan` shouldn't stop scanning backwards. This change
fixes this behavior by ignoring the `iter.Valid` in `MVCCIterate`
until after the iterator has scanned to the previous key.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/mvcc.go, line 1742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFpyhNQIzS_5nWkxJz:-KsFpyhNQIzS_5nWkxK-:bi17c0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc.go#L1742)):*
> ```Go
> 				// The current entry is an inline value. We can reach the previous
> 				// entry using Prev() which is slightly faster than PrevKey().
> 				iter.Prev()
> ```

is it legal to call `iter.Prev()` on an iter that's not valid? Just checking. The "invalid iter" would have to keep enough state about where it is (i.e. "I'm at KeyMin" or "I'm at KeyMax"). We might have to re-seek, or add a comment explaining why it's all good.

ISTM that it would be illegal if `valid == false` but `buf.meta.IsInline() == true`. Something to clarify and perhaps assert.

---

*[pkg/storage/engine/mvcc_test.go, line 2321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFqkIJDLquPwV2m6LX:-KsFqkIJDLquPwV2m6LY:b-kr1owa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc_test.go#L2321)):*
> ```Go
> 	defer engine.Close()
> 
> 	if err := MVCCPut(context.Background(), engine, nil, testKey2, hlc.Timestamp{WallTime: 1}, value2, nil); err != nil {
> ```

Could you add commentary narrating what's going on and what used to go wrong? I know what you're fixing, but it still takes me some energy to see through the random numbers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868)*

**Comment by tschottdorf** [comment]
:lgtm: mod comments.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-:-KsFr14V_jGTJPwUh3_x:b-vvp1bn)*

**Comment by benesch** [comment]
(If you have to go through CI anyway, I think you want "falls off" instead of "fall of" in the commit message.)

**Comment by bdarnell** [comment]
:lgtm: but I'm not sure about the answer to @tschottdorf's question.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-:-KsG-MYgywtsFfFm-t9P:b-8fki2m)*

**Comment by nvanbenschoten** [comment]
TFTRs.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/engine/mvcc.go, line 1742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFpyhNQIzS_5nWkxJz:-KsG-GOld93BqsbYESLT:b-hnfgkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc.go#L1742)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

is it legal to call `iter.Prev()` on an iter that's not valid? Just checking. The "invalid iter" would have to keep enough state about where it is (i.e. "I'm at KeyMin" or "I'm at KeyMax"). We might have to re-seek, or add a comment explaining why it's all good.

ISTM that it would be illegal if `valid == false` but `buf.meta.IsInline() == true`. Something to clarify and perhaps assert.
</blockquote></details>

Yeah, that's a good point. Before calling `iter.Prev()` on the inline case we should still check if the key is valid. If not, we should have the same behavior as before. Done.

---

*[pkg/storage/engine/mvcc_test.go, line 2321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFqkIJDLquPwV2m6LX:-KsFwnR7qcOrplwaOqS3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc_test.go#L2321)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Could you add commentary narrating what's going on and what used to go wrong? I know what you're fixing, but it still takes me some energy to see through the random numbers.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-:-KsG0uzky0Tu6yS53bn4:bz5maj4)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/mvcc.go, line 1742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFpyhNQIzS_5nWkxJz:-KsG0ljb_htxdWXBB_0D:b-vgqc9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc.go#L1742)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, that's a good point. Before calling `iter.Prev()` on the inline case we should still check if the key is valid. If not, we should have the same behavior as before. Done.
</blockquote></details>

I don't think `iter.Prev()` is legal on an iter that's not valid. The RocksDB comments say:

```
  // Moves to the previous entry in the source.  After this call, Valid() is
  // true iff the iterator was not positioned at the first entry in source.
  // REQUIRES: Valid()
  virtual void Prev() = 0;
```

Rather than trying to keep track of where the iterator is pointed, perhaps we should add a dummy "max" key when an engine is created.

PS `Next()` has the same requirement that `iter.Valid()` is true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/mvcc_test.go, line 2321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFqkIJDLquPwV2m6LX:-KsG1Xzw68SfrhxuEley:b-m4klvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc_test.go#L2321)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! :tophat: :dollar:  (<- attempted "hat tip")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/mvcc.go, line 1742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFpyhNQIzS_5nWkxJz:-KsG1Xhmz5mIdf7Tv1yg:baenjfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc.go#L1742)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think `iter.Prev()` is legal on an iter that's not valid. The RocksDB comments say:

```
  // Moves to the previous entry in the source.  After this call, Valid() is
  // true iff the iterator was not positioned at the first entry in source.
  // REQUIRES: Valid()
  virtual void Prev() = 0;
```

Rather than trying to keep track of where the iterator is pointed, perhaps we should add a dummy "max" key when an engine is created.

PS `Next()` has the same requirement that `iter.Valid()` is true.
</blockquote></details>

The newest version of this change will only `Seek()` on an invalid iterator, never `Prev()` or `PrevKey()`. Are there any issues with this approach @petermattis?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/mvcc.go, line 1742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFpyhNQIzS_5nWkxJz:-KsG4e7k4w3M2fbtajBZ:b-4j9idl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc.go#L1742)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The newest version of this change will only `Seek()` on an invalid iterator, never `Prev()` or `PrevKey()`. Are there any issues with this approach @petermattis?
</blockquote></details>

`Seek()` on an invalid iter is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/mvcc.go, line 1742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868#-KsFpyhNQIzS_5nWkxJz:-KsG_fSzGF-2fQzNJ9kK:b-kzrcdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80166a50133dc334ddea083f1883aa600641298/pkg/storage/engine/mvcc.go#L1742)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`Seek()` on an invalid iter is fine.
</blockquote></details>

The newest version looks fine. Nice job on tracking this down. Not at all where I expected the bug to be. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17868)*

**Pull request merged**
