### PR TITLE
backupccl: fix a recently added flaky test

### PR DESCRIPTION
**Pull request by lidorcarmel**
A recently added test (PR #91630) fails in 22.2 in stress or race.

The test is running a backup on a 3 node cluster, and then verifies a remote flow was running with the right pprof labels and log tags. The problem is that if all flows are local we fail, which can happen with a 3 node cluster.

Instead, this fix is changing the test cluster to have 4 nodes which will force at lease one flow to run remotely.

Release note: None

Epic: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I don't understand why increasing the number of nodes in the test from 3 to 4 would make this test non-flaky, like my intuition says it'll just become less flaky. Can you elaborate a bit more please?

Alternatively, we could track whether `SetupFlowCb` was called, and if not, we'd not assert that the log tags are propagated.

**Comment by lidorcarmel** [comment]
sure, the failure was that the:
```
	require.True(t, found)
```
at the end of the test was failing, meaning we never called the `SetupFlowCb` because we only had local flow(s), and we don't update log tags (and pprof labels) for local flows.

so with 4 nodes we have to have at least one remote flow during a backup, and then `found` must be true.

hopefully my understanding of how this works is ok! please ask more questions if this still doesn't make sense to you..

**Comment by lidorcarmel** [comment]
BTW worth mentioning that I don't know why this doesn't fail in master.

**Comment by yuzefovich** [comment]
> so with 4 nodes we have to have at least one remote flow during a backup

I don't understand why this would be always true if for 3 nodes it is sometimes false.

My guess is that the range cache might occasionally be not populated for the table we're backing up when backup is issued. It looks like we're using a bank workload with 10 ranges. If the range cache is empty, then `PartitionSpans` in `distBackupPlanSpecs` will assign all ranges to the local node. I'd add `SELECT count(*) FROM data.bank` after `WaitForFullReplication` in `backupRestoreTestSetupWithParams` (this would populate the DistSender's range cache on the gateway node which should make the backup be distributed).

It's also possible that the ranges from `bank` table aren't scattered across the cluster when the data is imported. However, IIUC we're using concurrency 4, so we should round-robin connections, and every node in the cluster would get some data inserted. Maybe this is where number 4 comes from? Maybe also we ought to shuffle the ranges after the inserts?

**Comment by lidorcarmel** [comment]
>I don't understand why this would be always true if for 3 nodes it is sometimes false.

I was thinking that with 4 nodes (or, more than 3) at least one range would be remote, you're right that it's not guaranteed but the ranges and leases should be spread evenly across those nodes.

thanks for the rest of the comment! interesting about the range cache! though I just tried adding these 5 lines right before calling `backupAndRestore` in that test and it still fails :(

```
	conn := tc.Conns[0]
	sqlDB := sqlutils.MakeSQLRunner(conn)
	var rowCount int64
	sqlDB.QueryRow(t, `SELECT count(*) FROM data.bank`).Scan(&rowCount)
	require.Equal(t, int64(numAccounts), rowCount)
```

thanks again for helping with this!

**Comment by yuzefovich** [comment]
Hm, interesting. I'm not sure what's happening here, so I'll leave it up to you to decide whether it's worth getting to the bottom of it.

I still think that increasing the node count doesn't fix the flake for good, and it would be better to omit `require.True(t, found)` assertion if `SetupFlowCb` wasn't called - this seems like a proper way to de-flake the test.

**Comment by lidorcarmel** [comment]
hi @yuzefovich , I rather not drop the `require.True(t, found)` because something might change to make this test run without testing anything, for example without running the callback, and still succeeding.. not ideal. But you're right it's an option if this will still be flaky with 4 nodes.

PTAL at the comment in the pr code again? looks like we fail because SCATTER may sometimes not scatter leases if the other replicas are not ready yet to be leaseholders. See this for a bit more info: https://github.com/cockroachdb/cockroach/blob/0fbeb5749bd76b2d806fa136f1b659ec96a6a8a0/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1608-L1652

FYI this fails consistently in 22.2 race, and within a few minutes in stress. And I did not see this fails with 4 nodes at all, even in stress/race/stressrace for hours.

**Review by yuzefovich — APPROVED** [review]
Makes sense, thanks! :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92696#-:-NIEpeiNEe7ANmZ22bmB:btbrf5i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by lidorcarmel** [comment]
TFTR Yahor!
bors r+

**Pull request merged**
