### PR TITLE
sql: implement write path for ALTER ROLE ... SET

### PR DESCRIPTION
**Pull request by rafiss**
Touches https://github.com/cockroachdb/cockroach/issues/21151

ALTER ROLE ... SET will now persist the default settings in the
system.database_role_settings table. The behavior matches Postgres in
the following ways:
- RESET does not validate the setting name.
- SET validates both the name and the proposed default value.
- The defaults are stored in a string array, in key=val format.

The privilege checking is slightly different: we diverge from Postgres
by prohibiting users from modifying their own defaults unless they
have CREATEROLE. This is analogous to our restriction that prevents
a user from modifying their own password.

There is no release note since this does not yet affect any
user-behavior. Everything in this commit is write-only

Release note: None

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/alter_role.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe8-LJAz76CH8aXqj3:-Mfe8-LJAz76CH8aXqj4:bscz4v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L53)):*
> ```Go
> 	varName string
> 	sVar    sessionVar
> 	// typedValues == nil means RESET.
> ```

I would prefer using a bool to determine reset, not a fan of the extra logic to check if varName and typedValues are nil

Think it would be clearer if we had a reset bool and shortcircuited with that
___
*[pkg/sql/alter_role.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe8jY78gtOICCJEHso:-Mfe8jY78gtOICCJEHsp:b-kxczi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L307)):*
> ```Go
> 	// Also note that we diverge from Postgres by prohibiting users from
> 	// modifying their own defaults unless they have CREATEROLE. This is analogous
> 	// to our restriction that prevents a user from modifying their own password.
> ```

Maybe we should add an additional check that if the user being modified is a member of the admin role, then we'll want to that the user running alter is also admin
___
*[pkg/sql/alter_role.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe9mHXCTPGSvgQMKVY:-Mfe9mHXCTPGSvgQMKVZ:b-jtnyj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L409)):*
> ```Go
> 		expr = paramparse.UnresolvedNameToStrVal(expr)
> 
> 		var dummyHelper tree.IndexedVarHelper
> ```

I think it's fine to just pass `tree.IndexedVarHelper{}` into analyzeExpr
___
*[pkg/sql/alter_role.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeA3UC8NfYMzmGomio:-MfeA3UC8NfYMzmGomip:bi7j8w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L435)):*
> ```Go
> 	if err != nil {
> 		return err
> 	} else if !needsUpdate {
> ```

nit: I'd prefer to pull the `!needsUpdate` into it's own if statement. 
___
*[pkg/sql/drop_role.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeCAmV3pWJ7ks7WZiJ:-MfeCAmV3pWJ7ks7WZiK:b-og40xu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/drop_role.go#L337)):*
> ```Go
> 
> 		// TODO(rafi): Remove this condition in 21.2.
> 		if params.EvalContext().Settings.Version.IsActive(params.ctx, clusterversion.DatabaseRoleSettings) {
> ```

Is it possible that we're in a mixed version cluster where one node is 21.2 and this table exists but we drop a role on a 21.1 node and it doesn't execute this query hence leaving the row leftover?
___
*[pkg/sql/logictest/testdata/logic_test/alter_role_set, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeCvMo7_X81e1SbVgz:-MfeCvMp5s3bYVeO6YCX:b10ca2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/logictest/testdata/logic_test/alter_role_set#L1)):*
> ```
> statement ok
> ```

Nice tests!
___
*[pkg/sql/roleoption/role_option.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeCfDOC_FeotspSBt0:-MfeCfDP0LTRB8aBdRvy:b3s6xl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/roleoption/role_option.go#L58)):*
> ```Go
> 	MODIFYCLUSTERSETTING
> 	NOMODIFYCLUSTERSETTING
> 	DEFAULTSETTINGS
> ```

Do we have to add this in this PR? It doesn't do anything right now - would rather add where it gets used.

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/drop_role.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeCAmV3pWJ7ks7WZiJ:-MfeFQ801t-zDVOvbir3:bri971u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/drop_role.go#L337)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Is it possible that we're in a mixed version cluster where one node is 21.2 and this table exists but we drop a role on a 21.1 node and it doesn't execute this query hence leaving the row leftover?
</blockquote></details>

Nvm ignore that this the clusterversion won't be active until all nodes are on the same version.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/alter_role.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe8-LJAz76CH8aXqj3:-MffeiyYEOs4wWnfq42F:b-mchzff) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L53)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I would prefer using a bool to determine reset, not a fan of the extra logic to check if varName and typedValues are nil

Think it would be clearer if we had a reset bool and shortcircuited with that
</blockquote></details>

sounds good -- i wasn't sure which would be more clear.
___
*[pkg/sql/alter_role.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe8jY78gtOICCJEHso:-Mffgbq613JUOiWWA8Lx:b-tpkx6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L307)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Maybe we should add an additional check that if the user being modified is a member of the admin role, then we'll want to that the user running alter is also admin
</blockquote></details>

this makes sense. i borrowed the same restriction the the existing `alterRoleNode` has, so i think we should update that one as well.
___
*[pkg/sql/alter_role.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe9mHXCTPGSvgQMKVY:-MffgyV28F__ywqrzAtt:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L409)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think it's fine to just pass `tree.IndexedVarHelper{}` into analyzeExpr
</blockquote></details>

fixed
___
*[pkg/sql/alter_role.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeA3UC8NfYMzmGomio:-Mffh0e00D0vYS6KoLZc:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L435)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: I'd prefer to pull the `!needsUpdate` into it's own if statement. 
</blockquote></details>

fixed
___
*[pkg/sql/roleoption/role_option.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeCfDOC_FeotspSBt0:-MffhKtL6MonnYmyUhWh:b-os465m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/roleoption/role_option.go#L58)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Do we have to add this in this PR? It doesn't do anything right now - would rather add where it gets used.
</blockquote></details>

well it's used in alter_role.go for audit logging purposes, see line 541

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/alter_role.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe8jY78gtOICCJEHso:-Mffo4Ib-yKMFem0zX7X:b-tjaan3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L307)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this makes sense. i borrowed the same restriction the the existing `alterRoleNode` has, so i think we should update that one as well.
</blockquote></details>

i'll change the existing ALTER ROLE in a separate commit if you agree

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/alter_role.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe8-LJAz76CH8aXqj3:-Mffoii71NfeomCQ75BJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L53)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

sounds good -- i wasn't sure which would be more clear.
</blockquote></details>

Done.
___
*[pkg/sql/alter_role.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe9mHXCTPGSvgQMKVY:-MffohQ3D5Gq8DmhYn6k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L409)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

Done.
___
*[pkg/sql/drop_role.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeCAmV3pWJ7ks7WZiJ:-MffodDL7jjMOZnAPXQz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/drop_role.go#L337)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Nvm ignore that this the clusterversion won't be active until all nodes are on the same version.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/alter_role_set, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-MfeCvMo7_X81e1SbVgz:-Mffoa8ED5X4DvbwGic_:b2nidcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/logictest/testdata/logic_test/alter_role_set#L1)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Nice tests!
</blockquote></details>

ty!

**Review by RichardJCai — APPROVED** [review]
LGTM mod nit

> Reviewed 3 of 9 files at r2, 24 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-:-MfhntFh-k3kvzwtEYfY:bkyd1w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/alter_role.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfe8jY78gtOICCJEHso:-MfhmM5m3tDKYj-Wfi6Z:bxuvvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8ff913700fdd712df7897cf4114284fb600f51b/pkg/sql/alter_role.go#L307)):*
> Maybe we should add an additional check that if the user being modified is a member of the admin role, then we'll want to that the user running alter is also admin

SGTM lets do this in a separate PR if we want to follow through
___
*[pkg/sql/alter_role.go, line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfhn2853VFbLVPyNd7b:-Mfhn2853VFbLVPyNd7c:b-ko4892) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8bfbc93ed1facd0f24fc83fa24ea24bc78d4b17/pkg/sql/alter_role.go#L522)):*
> ```Go
> 	var oldSettings *tree.DArray
> 	var newSettings []string
> 	if datums != nil {
> ```

nit: pull this into helper function with high level explanation of what's happening here

code is fairly hard to understand at first read

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/alter_role.go, line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68030#-Mfhn2853VFbLVPyNd7b:-Mfhx03j3JHSrcbtdY23:btfpidi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8bfbc93ed1facd0f24fc83fa24ea24bc78d4b17/pkg/sql/alter_role.go#L522)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: pull this into helper function with high level explanation of what's happening here

code is fairly hard to understand at first read
</blockquote></details>

good call. also commented other helpers.

**Comment by rafiss** [comment]
tftr!

bors r=RichardJCai

**Pull request merged**
