### PR TITLE
tscache: add intervalSkl metrics

### PR DESCRIPTION
**Pull request by nvb**
These metrics will help us track page count and page rotation rate so
that we can monitor that the tscache remains healthy.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Rebased on top of https://github.com/cockroachdb/cockroach/pull/20232.

**Comment by tschottdorf** [comment]
Looks good. I generally wish we'd expose all the metrics that are available somewhere hidden in the ui automatically.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/tscache/metrics.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20309#-L-Djd00THLp7JqPmFgr:-L-Djd00THLp7JqPmFgs:b-fljfq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f9ceca68e49c204e0de6606e0853734ef6b62b/pkg/storage/tscache/metrics.go#L21)):*
> ```Go
> // Metrics holds all metrics relating to a Cache.
> type Metrics struct {
> 	Skl sklImplMetrics
> ```

why export `Skl`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20309#-:-L-DjkiU3qAW29ofeakT:b-y169nh)*

**Comment by nvanbenschoten** [comment]
Thanks for the review.

> I generally wish we'd expose all the metrics that are available somewhere hidden in the ui automatically.

Do you mean in addition to the `/_status/vars` page? As graphs?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/tscache/metrics.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20309#-L-Djd00THLp7JqPmFgr:-L-DkSLw54bnVlc75XGo:b-686czg) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f9ceca68e49c204e0de6606e0853734ef6b62b/pkg/storage/tscache/metrics.go#L21)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

why export `Skl`?
</blockquote></details>

It needs to be exported for the reflection-based `metrics.Struct` magic to work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20309#-:-L-Dkm6qiNepQ6mzVPzM:bmjmivs)*

**Comment by tschottdorf** [comment]
Yeah, as graphs. Just a random wish, though, for the situations in which we're not looking at our own prometheus-backed clusters.

Btw, that was :lgtm: :smile: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20309#-:-L-DlfWeJIMRANpIrH0b:b374xii)*

**Pull request merged**
