### PR TITLE
bench: pre-create connections for InsertDistinct

### LINKED ISSUE #21310: bench: the InsertDistinct benchmark is failing with count=1000
This also suggests there benchmark misses a `DROP TABLE IF EXISTS insert_distinct` to account for previous failures.

```
BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16             --- FAIL: BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16
        bench_test.go:813: dial tcp 127.0.0.1:17629: getsockopt: connection reset by peer
        bench_test.go:755: dial tcp 127.0.0.1:17629: connect: connection reset by peer
BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16             --- FAIL: BenchmarkSQL/Cockroach/InsertDistinct/count=1000
        bench_test.go:767: pq: relation "insert_distinct" already exists
--- FAIL: BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16
        bench_test.go:767: pq: relation "insert_distinct" already exists
BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16             --- FAIL: BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16
        bench_test.go:813: dial tcp 127.0.0.1:17629: connect: connection reset by peer
        bench_test.go:755: dial tcp 127.0.0.1:17629: connect: connection reset by peer
BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16             --- FAIL: BenchmarkSQL/Cockroach/InsertDistinct/count=1000
        bench_test.go:767: pq: relation "insert_distinct" already exists
--- FAIL: BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16
        bench_test.go:767: pq: relation "insert_distinct" already exists
BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16             --- FAIL: BenchmarkSQL/Cockroach/InsertDistinct/count=1000-16
        bench_test.go:813: dial tcp 127.0.0.1:17629: getsockopt: connection reset by peer
        bench_test.go:755: dial tcp 127.0.0.1:17629: connect: connection reset by peer
```

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, a pool of worker goroutines was sharing a connection
pool, and opening db connections concurrently through it.  This is a
problem on OSX and FreeBSD because the server cannot accept the
connections fast enough and so opening some connections fails. This
happens when we attempt to open
1000 connections concurrently because of the default kernel limit of
kern.ipc.somaxconn=128.

Fixes https://github.com/cockroachdb/cockroach/issues/21310

Release note: None
Epic: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
nice

**Review by stevendanna — APPROVED** [review]
This seems reasonable to me and is consistent with what we found in other investigations of this, namely that on macOS the default kernel configuration has a relatively low max listen backlog.  Starting these in sequence should ensure we don't fill up that backlog.

**Comment by knz** [comment]
ci failure is an unrelated flake. #99903

**Comment by andreimatei** [comment]
I've updated the commit msg and comments to refer to `somaxconn`.

TFTR

bors r+

**Pull request merged**
