### PR TITLE
storage: improve raft leadership change detection

### PR DESCRIPTION
**Pull request by petermattis**
Watch for changes to Raft leadership via changes to
RaftStatus.SoftState.Lead. Refresh pending commands when the leadership
changes.

See #8344.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8346)

### CODE REVIEW

**Comment by petermattis** [comment]
I want to get feedback on the approach before attempting to test this. I have manually tested this and it does detect Raft leadership changes that are not currently detected.

**Comment by bdarnell** [comment]
I think that reproposing all pending commands after applying a snapshot will catch every leadership change that this will and more. I think it's more consistent to look at empty entries + snapshots than empty entries + SoftState.

**Comment by petermattis** [comment]
Looks like changes to `SoftState.Lead` occur before snapshot application. Isn't it better to re-propose commands earlier so that they can be sent along to the leader?

**Comment by bdarnell** [comment]
Yeah, `SoftState.Lead` is the earliest indication we can get of a new leader, so reproposing when `SoftState.Lead` changes could improve latency a bit. But it's not 100% reliable and will never tell us anything we won't get through other means.

**Comment by petermattis** [comment]
I've been spelunking the raft code and I'm not seeing how `SoftState.Lead` changes are not 100% reliable. Do you mind justifying that assertion in order to enlighten me?

**Comment by bdarnell** [comment]
Suppose node A is the leader, and then node C gets partitioned away from the others. Leadership passes back and forth between A and B during the partition, but when the partition is healed node A is leader again. When node C is reconnected, it would never see a leader in SoftState.Lead other than A, even though there had been a change of leadership which could have caused its earlier proposals to get dropped. (Granted, in the case of a partition anything C had tried propose would need to be retried whether or not B had ever been the leader).

There's some history in #3154. We changed from detecting leader changes with a combination of SoftState.Lead and HardState.Term to using the empty entries because only the latter worked for the case of conflicting config changes.

**Comment by petermattis** [comment]
Ok, so `SoftState.Lead` isn't a robust mechanism, but I think we should watch it for the latency improvement. Here are some log lines from a recent test run:

```
I160807 09:52:02.530240 cli/start.go:334  CockroachDB beta-20160728-345-g847cca0-dirty (darwin amd64, built 2016/08/07 13:50:43, go1.7rc4)
...
I160807 09:52:02.938311 storage/replica.go:1571  store=1:1 range=1 [/Min-/Table/11): raft leader changed: 0 -> 2
...
I160807 09:52:04.324866 storage/replica.go:1813  store=1:1 range=1 [/Min-/Table/11): pending commands: refurbished 1, reproposing 0 (at 112.93); reasonTicks
...
I160807 09:52:04.740974 storage/replica.go:1813  store=1:1 range=1 [/Min-/Table/11): pending commands: refurbished 1, reproposing 0 (at 156.125); reasonSnapshotApplied
```

The node starts at `09:52:02.53`. 400ms later it sees `SoftState.Lead` change from `0` to `2` for range 1. Another 2 seconds elapse before the snapshot is applied.

**Comment by petermattis** [comment]
Added additional code to refresh commands after a snapshot is applied. PTAL.

**Comment by bdarnell** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica.go, line 1561 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOadZZTf47xXvv6TgBI:-KOadZZTf47xXvv6TgBJ:b-rbb8o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/372cfece24a6b1474702f55109f97d4c92fe81bb/storage/replica.go#L1561)):*
> ```Go
> 	defer r.mu.Unlock()
> 	return r.withRaftGroupLocked(func(raftGroup *raft.RawNode) error {
> 		// RaftStatus.Lead only changes within calls to RawNode.Step(). We watch
> ```

The `Lead` can also change during `Tick` (when the current node is a leader and steps down because it has not gotten a quorum of `MsgHeartbeatResp` in an election timeout). It's better to check this in `handleRaftReady` just like all other information we receive from raft, instead of introducing calls to `raftGroup.Status()`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 1672 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOaonICqAIdLq3LCdnY:-KOaonIDzIfXDh2AFexG:b-ekx9o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/372cfece24a6b1474702f55109f97d4c92fe81bb/storage/replica.go#L1672)):*
> ```Go
> 			// entire batch of entries.
> 			if len(e.Data) == 0 {
> 				if refreshReason == noReason {
> ```

perhaps the reasons enum should be a bit field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 1561 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOadZZTf47xXvv6TgBI:-KOanXlXhGsTaG8Y5Lns:b-x4uc57) ([raw file](https://github.com/cockroachdb/cockroach/blob/372cfece24a6b1474702f55109f97d4c92fe81bb/storage/replica.go#L1561)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The `Lead` can also change during `Tick` (when the current node is a leader and steps down because it has not gotten a quorum of `MsgHeartbeatResp` in an election timeout). It's better to check this in `handleRaftReady` just like all other information we receive from raft, instead of introducing calls to `raftGroup.Status()`. 
</details>
Ok, does this look better? Performing the check in `handleRaftReady` has the challenge that we need to keep track of the previous leader ourselves. Perhaps I'm missing some other way to detect that the leader changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346)*

**Comment by bdarnell** [comment]
:lgtm:

One more thing we'll want to keep an eye on: in the common case we'll get a new leader from SoftState.Lead, and shortly thereafter get the empty entry (before any of the reproposals we may have made after the SoftState change could have had an effect, even though they are still in flight and could be completed soon). This may result in wasteful multiple-proposals, although leadership changes should be rare enough that it may not be worth optimizing. 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-:-KObCDTp-lAnl8bPwSMB:b-dvl4yf)*

**Comment by petermattis** [comment]
Added a TODO comment about the possibility of wasteful re-proposals. Any ideas for how to test this? Or pointers to existing tests to conscript into service?

**Comment by bdarnell** [comment]
We have tests to ensure that things get reproposed when necessary, but we don't have anything that verifies the absence of other reproposals. I think the thing to do would be to make metrics for reproposal events so we can monitor the percentage of proposals that get retried in real-world scenarios. We might also want to add a per-command counter so we can see if the same commands are getting reproposed multiple times.

**Comment by petermattis** [comment]
I was wondering more about a test that verifies we re-propose after a snapshot and after a `SoftState.Lead` change.

Adding metrics around re-proposals sounds like a good idea. I'll file an issue.

**Comment by bdarnell** [comment]
Verifying reproposal specifically after a SoftState.Lead change is going to be tricky because that is redundant compared to the empty entry and snapshot triggers. We have to make the reason for reproposal observable; counters are the best way I can think of to do that.

**Comment by petermattis** [comment]
Ok, so where can I look for inspiration on how to test the snapshot-based re-proposals? I'm not seeing an existing test I can riff off of.

**Comment by bdarnell** [comment]
I'm not sure. After looking, we don't currently have any direct tests of reproposals, although many of our tests fail if you remove reproposals entirely. The snapshot-based reproposals are really a stretch since it's nearly impossible to get into a state where a command needed to be reproposed after a snapshot and would succeed. (also, you'll often hit the tick-based reproposal anyway). Can you turn the scenario from #8344 into a test?

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 1672 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOaonICqAIdLq3LCdnY:-KOf57DbOVkVH9UHePQX:bb9l32m) ([raw file](https://github.com/cockroachdb/cockroach/blob/372cfece24a6b1474702f55109f97d4c92fe81bb/storage/replica.go#L1672)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> perhaps the reasons enum should be a bit field.
</details>
The string-ified reason is only used for debugging. I'm going through the `refreshReason == noReason` dance in order to keep track of the original reason. Another option would be to keep a slice of reasons (the usual case is no refresh so this doesn't need to be particularly fast), but any change here seems like overkill at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346)*

**Comment by petermattis** [comment]
Added a test of this new functionality. This required adding additional testing knobs to disable refreshing pending commands under certain circumstances. PTAL.

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 3 of 4 files at r5.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1672 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOaonICqAIdLq3LCdnY:-KOfr-vzskcqa7EO1Ar3:b-m5br6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/372cfece24a6b1474702f55109f97d4c92fe81bb/storage/replica.go#L1672)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The string-ified reason is only used for debugging. I'm going through the `refreshReason == noReason` dance in order to keep track of the original reason. Another option would be to keep a slice of reasons (the usual case is no refresh so this doesn't need to be particularly fast), but any change here seems like overkill at the moment.
</details>
Sure. Dunno why you'd keep a slice though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 569 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOg0xrwSejFjKC1Ln9W:-KOg0xrxdam0gq_PplmQ:b-dazta6) ([raw file](https://github.com/cockroachdb/cockroach/blob/22ca3e1e611917820015a2735a2424cd0fdbfe93/storage/client_raft_test.go#L569)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	testCases := []storage.StoreTestingKnobs{
> ```

Add some comments: "In this scenario, three different mechanisms detect the need to repropose commands. Test that each one is sufficient individually. We have this redundancy because some mechanisms respond with lower latency than others, but each has some scenarios (not currently tested) in which it is insufficient on its own). In addition, there is a fourth reproposal mechanism (reasonNewLeaderOrConfigChange) which is not relevant to this scenario."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-:-KOg2I0NI2brXQkvm-Ao:bb6ywmx)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 569 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOg0xrwSejFjKC1Ln9W:-KOg54-evmpKGddgwBnB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22ca3e1e611917820015a2735a2424cd0fdbfe93/storage/client_raft_test.go#L569)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Add some comments: "In this scenario, three different mechanisms detect the need to repropose commands. Test that each one is sufficient individually. We have this redundancy because some mechanisms respond with lower latency than others, but each has some scenarios (not currently tested) in which it is insufficient on its own). In addition, there is a fourth reproposal mechanism (reasonNewLeaderOrConfigChange) which is not relevant to this scenario."
</details>
Done.

---

*[storage/replica.go, line 1672 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346#-KOaonICqAIdLq3LCdnY:-KOg55F2GQys-rglTQzn:borwcr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/372cfece24a6b1474702f55109f97d4c92fe81bb/storage/replica.go#L1672)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Sure. Dunno why you'd keep a slice though.
</details>
A slice would show the order in which the reasons were detected, though I suppose that could be discerned from the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8346)*

**Pull request merged**
