### PR TITLE
distsql: add missing MoveToDraining calls

### LINKED ISSUE #29374: panic: Non-nullable column with no value!
Running v2.1.0-beta.20180827 on a 5 nodes cluster. One of the node crash with this panic message.

The column screenview:lastmodified was defined with default value.

lastmodified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()

```
panic: Non-nullable column "screenview:lastmodified" with no value! Index scanned was "primary" with the index key columns (fp) and the values ('a6b301a0-1e78-4263-b351-e1347c99c2fa')

goroutine 160961941 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc42687fc90, 0x2efbe40, 0xc43a67a0c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1276 +0x9d9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc42687fc90, 0x2efbe40, 0xc43a67a0c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1028 +0x183
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*rowFetcherWrapper).Next(0xc430304ca0, 0xc42b1efb30, 0x0, 0x0, 0xc42b1efb30)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:141 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc42687f800, 0x0, 0x0, 0x0, 0xc42b1efb30)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:238 +0x4e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x2efbe40, 0xc446d8aba0, 0x2f06300, 0xc42687f800, 0x2eda000, 0xc432698000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc42687f800, 0x2efbe40, 0xc446d8aba0, 0xc42be2ff38)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:739 +0x98
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:574 +0x1e3
```

### LINKED ISSUE #29978: fatal error: runtime: out of memory
When I was testing this issue https://github.com/cockroachdb/cockroach/issues/29374
Once one of the node crashed by the above panic, the remaining servers keep accepting query and insert statement. However, if I run a query like this a few times
select * from universe.screenview order by date desc
One of the server will go 00m and get killed by the system.
Log for the crashed server attached.
[cockroach.crdb-05.root.2018-09-09T03_01_30Z.025882.log](https://github.com/cockroachdb/cockroach/files/2363948/cockroach.crdb-05.root.2018-09-09T03_01_30Z.025882.log)

### PR DESCRIPTION
**Pull request by solongordon**
I found several places where processors were not checking for error
metadata from their inputs and draining appropriately. The most
egregious of these is in TableReader, which was not calling
MoveToDraining when it encountered an error from the underlying
RowFetcher. This meant that rather than draining it would continue
calling NextRow and generating errors in a tight loop, which caused the
query to hang as well as high CPU and memory usage on the affected node.

Other affected processors are Distinct, SortChunks, and SortTopK.

Fixes #29374
Fixes #29978

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm: glad you found it... definitely adding more weight to the argument that we should be moving the burden of understanding and correctly dealing with metadata to a layer above individual processors.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30096#-:-LM9Jq4-6XrR2Hx2G-m-:b-g4h191)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by asubiotto — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30096)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/sorter.go, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30096#-LM9P9Qr5TEmypBJ_XmT:-LM9P9Qr5TEmypBJ_XmU:b-q006fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/23ce7dcfe7dcc429b907acb44d93aa0f87926a30/pkg/sql/distsqlrun/sorter.go#L557)):*
> ```Go
> 			s.trailingMeta = append(s.trailingMeta, *meta)
> 			if meta.Err != nil {
> 				return false, nil
> ```

MoveToDraining call missing here?
___
*[pkg/sql/distsqlrun/tablereader.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30096#-LM9PHCT8QIn3q3TKKJk:-LM9PHCT8QIn3q3TKKJl:b-h51dg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/23ce7dcfe7dcc429b907acb44d93aa0f87926a30/pkg/sql/distsqlrun/tablereader.go#L247)):*
> ```Go
> 			if meta.Err != nil {
> 				tr.MoveToDraining(nil /* err */)
> 				break
> ```

Does this drop the metadata? If it does that would be hopefully caught by the metadata sender tests.

**Comment by vivekmenezes** [comment]
is there a way to test for this?

**Comment by vivekmenezes** [comment]
Yes, moving duplicate code to one place sounds like a fine plan. Thanks

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30096)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/sorter.go, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30096#-LM9P9Qr5TEmypBJ_XmT:-LMCbKfh5vStPPfmnxCB:bvjf4bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/23ce7dcfe7dcc429b907acb44d93aa0f87926a30/pkg/sql/distsqlrun/sorter.go#L557)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

MoveToDraining call missing here?
</blockquote></details>

It's handled in the caller.
___
*[pkg/sql/distsqlrun/tablereader.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30096#-LM9PHCT8QIn3q3TKKJk:-LMCfSK28mSTx0nHnVOD:b-r2eibb) ([raw file](https://github.com/cockroachdb/cockroach/blob/23ce7dcfe7dcc429b907acb44d93aa0f87926a30/pkg/sql/distsqlrun/tablereader.go#L247)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this drop the metadata? If it does that would be hopefully caught by the metadata sender tests.
</blockquote></details>

D'oh, looks that way. Thanks. (I don't think it would be caught by the tests because it's coming from the `rowFetcherWrapper`.)

**Pull request merged**
