### PR TITLE
storage: stop-gap HardState clobbering on split

### PR DESCRIPTION
**Pull request by tbg**
Before this fix,

```
make stressrace PKG=./storage TESTS=TestStoreRangeDownReplicate \
  STRESSFLAGS='-p 16 -maxfails 1 -stderr'
```

failed in a few hundred iterations (and in <20 with some assertions and
shortcuts added in my WIP which I am going to publish as well).

See #7600.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7672)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Interested in hearing ideas on how to test is. My current best shot is running a lot of splits while having a goroutine spin on the side with faux incoming Raft messages.

**Comment by petermattis** [comment]
I was thinking about testing of this code in general this morning. `Replica` and `Store` are state machines. If we had finer control of `Store.processRaft` we should be able to create scenarios.

In the short term, could you create the RHS range manually (via `Store.getOrCreateReplicaLocked`) before splitting? 

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2260 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UU1ErGvL3fcEhQW6:-KM4UU1ErGvL3fcEhQW7:427205088) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2260)):*
> ```Go
> 
> 	// Write the initial state for the new Raft group of the right-hand side.
> 	// Node that this needs to go into deltaMS (which is the total difference
> ```

`s/Node/Note/g`

---

*[storage/replica_command.go, line 2262 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4Uv1W_xUIrEaHoYCI:-KM4Uv1W_xUIrEaHoYCJ:469282574) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2262)):*
> ```Go
> 	// Node that this needs to go into deltaMS (which is the total difference
> 	// in bytes reported to the store in the end). We compute the RHS' stats
> 	// from it below.
> ```

Move this comment down below the new block of code.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4UedrTalZG-jTIVnb:771891822) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
> ```Go
> 		r.store.mu.Lock()
> 		if uninitRHS := r.store.mu.uninitReplicas[split.NewDesc.RangeID]; uninitRHS != nil {
> 			uninitRHS.mu.Lock()
> ```

I think you also need to grab `s.store.processRaftMu` to ensure that the uninitialized replica is not currently `Replica.handleRaftReady`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-:-KM4V5JgiyJwoim3fZVi:-1234821636)*

**Comment by bdarnell** [comment]
LGTM

TestRangeDescriptorSnapshotRace may be a good example to follow for testing this; I don't have a better idea in the short term than just racing splits versus other messages.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4XWJkI5cUzJIz50RY:1491955057) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think you also need to grab `s.store.processRaftMu` to ensure that the uninitialized replica is not currently `Replica.handleRaftReady`. 
</details>
processRaftMu is already held while splitTrigger is running. 

However, you're right that this isn't sufficient locking. The other replica could be in handleRaftReady and about to write its HardState; no other lock is held at this time. I think in addition to this change we need to set storeReplicaRaftReadyConcurrency to 1 until we can figure out a better locking scheme. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-:-KM4Z8CoDyFsY65_tbXg:1965839715)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4_NLwNuTK31gYHRNK:-479639056) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> processRaftMu is already held while splitTrigger is running. 
> 
> However, you're right that this isn't sufficient locking. The other replica could be in handleRaftReady and about to write its HardState; no other lock is held at this time. I think in addition to this change we need to set storeReplicaRaftReadyConcurrency to 1 until we can figure out a better locking scheme. 
</details>
Ah, good point about `processRaftMu` already being held.

Perhaps we should add `Replica.handleRaftReadyMu` that is grabbed for the duration of `Replica.handleRaftReady`. Yet-another-mutex kind of sucks, but we don't have one which currently covers this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672)*

**Comment by tschottdorf** [comment]
> However, you're right that this isn't sufficient locking. The other replica could be in handleRaftReady and about to write its HardState; no other lock is held at this time. I think in addition to this change we need to set storeReplicaRaftReadyConcurrency to 1 until we can figure out a better locking scheme.

Good point. Sent a PR to disable this (since we wanted to do it anyway).

> Perhaps we should add Replica.handleRaftReadyMu that is grabbed for the duration of Replica.handleRaftReady. Yet-another-mutex kind of sucks, but we don't have one which currently covers this.

Yeah, maybe. Having just disabled the concurrency, I'd like to avoid it (until we actively clean up that concurrency). Always easy to add a mutex and a lot of anxiety about removing one.

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2260 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UU1ErGvL3fcEhQW6:-KM4tHKuxX-GHS-yYo3i:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2260)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/Node/Note/g`
</details>
Done.

---

*[storage/replica_command.go, line 2262 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4Uv1W_xUIrEaHoYCI:-KM4tHkSR_k2UmBNPPHr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2262)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Move this comment down below the new block of code.
</details>
Done.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4tKTvqquXS5o8Ilr0:95717650) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Ah, good point about `processRaftMu` already being held.
> 
> Perhaps we should add `Replica.handleRaftReadyMu` that is grabbed for the duration of `Replica.handleRaftReady`. Yet-another-mutex kind of sucks, but we don't have one which currently covers this.
</details>
Replied to both in main thread.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4vS6D1LDC-kV9R-br:124109390) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Replied to both in main thread.
</details>
I'm trying to walk through how an uninitialized replica could be running concurrently here. Uninitialized replicas are created by `Store.handleRaftMessage` which holds `Store.processRaftMu`. But they aren't processed by `Store.processRaft`. Since we're hold `Store.processRaftMu` how is `uninitRHS` being operated on concurrently?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4wrVt6Ko2NJFSAoM5:1412521167) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm trying to walk through how an uninitialized replica could be running concurrently here. Uninitialized replicas are created by `Store.handleRaftMessage` which holds `Store.processRaftMu`. But they aren't processed by `Store.processRaft`. Since we're hold `Store.processRaftMu` how is `uninitRHS` being operated on concurrently?
</details>
Uninitialized replicas are indeed processed by `Store.processRaft`. Once a `Replica` is created in `handleRaftMessage`, it will become "ready" for the next cycle of `handleRaftReady` in order to persist its new HardState and write its response.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4ydfXqoaKHC4fCPAO:-273686118) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Uninitialized replicas are indeed processed by `Store.processRaft`. Once a `Replica` is created in `handleRaftMessage`, it will become "ready" for the next cycle of `handleRaftReady` in order to persist its new HardState and write its response.
</details>
For the curious: replicas can exist in both the `Store.mu.replicas` and `Store.mu.uninitReplicas` maps simultaneously. Very confusing. 

Now I'm trying to understand what prevents the RHS replica from being initialized at this point. If that's an impossible situation, we should be checking for it.

PS It's confusing to have an `uninitReplicas` map. Can we add an `uninitialized` boolean to `Replica`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM4zjT3PabuSro42Whm:-989930689) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> For the curious: replicas can exist in both the `Store.mu.replicas` and `Store.mu.uninitReplicas` maps simultaneously. Very confusing. 
> 
> Now I'm trying to understand what prevents the RHS replica from being initialized at this point. If that's an impossible situation, we should be checking for it.
> 
> PS It's confusing to have an `uninitReplicas` map. Can we add an `uninitialized` boolean to `Replica`?
</details>
Uninitialized replicas can only become initialized in two ways: the application of a snapshot, and splitTrigger. `Store.canApplySnapshot` prevents the application of snapshots to ranges for which there is a pending split.

Yeah, `uninitReplicas` should probably be replaced with a check of `Replica.IsInitialized` (or the two maps should be disjoint, which I think was the original plan when I created the second map)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM50DBt5U6CWKrUt-jZ:-1291482102) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Uninitialized replicas can only become initialized in two ways: the application of a snapshot, and splitTrigger. `Store.canApplySnapshot` prevents the application of snapshots to ranges for which there is a pending split.
> 
> Yeah, `uninitReplicas` should probably be replaced with a check of `Replica.IsInitialized` (or the two maps should be disjoint, which I think was the original plan when I created the second map)
</details>
Ok. Got it. We should add a check here that there isn't an existing initialized replica for the RHS. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-:-KM50MELsqu4gOadhnoP:1417088721)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672#-KM4UedrTalZG-jTIVna:-KM50Wwn5gydfHwC6NPn:1946008377) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff94876047bea08037e65cad35d5ccca2ac1938/storage/replica_command.go#L2282)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Ok. Got it. We should add a check here that there isn't an existing initialized replica for the RHS. 
</details>
There is, indirectly. If there were an existing initialized replica, store.addReplicaToRangeMap would fail. It would be good to make a more explicit check for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7672)*

**Comment by bdarnell** [comment]
Now that we've limited `handleRaftReady` concurrency, this change should be ready to go. @tschottdorf, if you merge it (even without a test) I'll push it to the beta clusters.

**Comment by tschottdorf** [comment]
SGTM, off we go and them I'm back on working on that test.

**Pull request merged**
