### PR TITLE
Write time series about ranges with active lease and lease errors

### PR DESCRIPTION
**Pull request by bogdanbatog**
Added two new counters on storeMetrics to record lease errors and successes. #869

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5596)

### CODE REVIEW

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5596#-:-KEspcvWbUkUqE4VgQ-P:1417088721)*

**Comment by mrtracy** [comment]
The code is LGTM, but could you please write a test to verify this?  I would recommend writing a short test in `storage/replica_test.go`, right next to `TestReplicaLeaderLease` and `TestReplicaNotLeaderError`. The code is very simple, but tests help put us at ease if we need to refactor.

I apologize again for the turnaround time on this; it appears it got lost during our beta release push. If you have a pull request that's significantly outstanding like this, feel free to bug us in our [gitter channel](https://gitter.im/cockroachdb/cockroach).

**Comment by bogdanbatog** [comment]
Sure, I'll add it. I apologize too for being slow.

**Comment by bogdanbatog** [comment]
@mrtracy I've added the unit test, LMK if other changes are needed

**Comment by mrtracy** [comment]
Yep, this looks good to me, Merging. Thanks for the contribution!

**Pull request merged**
