### PR TITLE
Log & graph process RSS + other stats changes

### LINKED ISSUE #5566: ui: node graph nits
The `Memory Allocated` graph should is really `Go Memory Usage` assuming that the graph is measuring the in use memory and not the number of bytes that were allocated during the time interval.

I think the `Garbage Collection` graph should be renamed `GC Pause Time` as it isn't otherwise clear what this graph is displaying. And the scale would be better in milliseconds.

### LINKED ISSUE #5592: stability: crash on malloc "free list corrupted"
build sha: da0a33b

This may be a side effect of calling malloc_info. I'm running with `--vmodule=linuxstats=2` which ends up running `malloc_info` as part of the memstats dump. Note that the `V(2)` switch does not control just output, it controls whether we run `malloc_info` entirely.

Scenario: clean cluster, 4 nodes + 4 photos apps. After ~1h, node3 died with:
```
runtime: free list of span 0x7fd4e093c7c0:
0xc8209fa020 -> 0xc8209fa030 -> 0xc8209fa040 -> 0xc8209fa050 -> 0xc8209fa060 -> 0xc8209fa080 -> 0xc8209fa090 -> 0xc8209fa0d0 -> 0xc8209fa110 -> 0xc8209fa130 -> 0xc8209fa140 -> 0xc8209fa170 -> 0xc8209fa180 -> 0xc8209fa190 -> 0xc8209fa1a0 -> 0xc8209fa1f0 -> 0xc8209fa200 -> 0xc8209fa220 -> 0xc8209fa230 -> 0xc8209fa250 -> 0xc8209fa290 -> 0xc8209fa2e0 -> 0xc8209fa2f0 -> 0xc8209fa300 -> 0xc8209fa320 -> 0xc8209fa330 -> 0xc8209fa360 -> 0xc8209fa370 -> 0xc8209fa380 -> 0xc8209fa3d0 -> 0xc8209fa410 -> 0xc8209fa420 -> 0xc8209fa430 -> 0xc8209fa440 -> 0xc8209fa450 -> 0xc8209fa460 -> 0xc8209fa470 -> 0xc8209fa480 -> 0xc8209fa490 -> 0xc8209fa4a0 -> 0xc8209fa4c0 -> 0xc8209fa4e0 -> 0xc8209fa4f0 -> 0xc8209fa530 -> 0xc8209fa540 -> 0xc8209fa550 -> 0xc8209fa570 -> 0xc8209fa580 -> 0xc8209fa590 -> 0xc8209fa5a0 -> 0xc8209fa5d0 -> 0xc8209fa5e0 -> 0xc8209fa690 -> 0xc8209fa6b0 -> 0xc8209fa6c0 -> 0xc8209fa720 -> 0xc8209fa730 -> 0xc8209fa750 -> 0xc8209fa760 -> 0xc8209fa7a0 -> 0xc8209fa7b0 -> 0xc8209fa7c0 -> 0xc8209fa7d0 -> 0xc8209fa7e0 -> 0xc8209fa7f0 -> 0xc8209fa800 -> 0xc8209fa810 -> 0xc8209fa820 -> 0xc8209fa830 -> 0xc8209fa840 -> 0xc8209fa870 -> 0xc8209fa8a0 -> 0xc8209fa8b0 -> 0xc8209fa8c0 -> 0xc8209fa8d0 -> 0xc8209fa920 -> 0xc8209fa930 -> 0xc8209fa940 -> 0xc8209fa960 -> 0xc8209fa970 -> 0xc8209fa990 -> 0xc8209fa9a0 -> 0xc8209fa9b0 -> 0xc8209fa9d0 -> 0xc8209fa9f0 -> 0xc8209faa20 -> 0xc8209faa30 -> 0xc8209faa40 -> 0xc8209faa60 -> 0xc8209faa70 -> 0xc8209faa90 -> 0xc8209faad0 -> 0xc8209fab00 -> 0xc8209fab10 -> 0xc8209fab40 -> 0xc8209fab60 -> 0xc8209fab70 -> 0xc8209fab80 -> 0xc8209fab90 -> 0xc8209fabe0 -> 0xc8209fabf0 -> 0xc8209fac20 -> 0xc8209fac30 -> 0xc8209fac40 -> 0xc8209fac50 -> 0xc8209fac60 -> 0xc8209fac70 -> 0xc8209fac80 -> 0xc8209fac90 -> 0xc8209faca0 -> 0xc8209facb0 -> 0xc8209facd0 -> 0xc8209face0 -> 0xc8209facf0 -> 0xc8209fad20 -> 0xc8209fad30 -> 0xc8209fad40 -> 0xc8209fad50 -> 0xc8209fad60 -> 0xc8209fad70 -> 0xc8209fad80 -> 0xc8209fad90 -> 0xc8209fadb0 -> 0xc8209fadc0 -> 0xc8209fadd0 -> 0xc8209fadf0 -> 0xc8209fae20 -> 0xc8209fae30 -> 0xc8209fae40 -> 0xc8209fae50 -> 0xc8209fae60 -> 0xc8209fae70 -> 0xc8209fae80 -> 0xc8209fae90 -> 0xc8209faea0 -> 0xc8209faeb0 -> 0xc8209faec0 -> 0xc8209faed0 -> 0xc8209faee0 -> 0xc8209faef0 -> 0xc8209faf00 -> 0xc8209faf10 -> 0xc8209faf20 -> 0xc8209faf30 -> 0xc8209faf40 -> 0xc8209faf50 -> 0xc8209faf60 -> 0xc8209faf70 -> 0xc8209faf80 -> 0xc8209faf90 -> 0xc8209fafa0 -> 0xc8209fafb0 -> 0xc8209fafc0 -> 0xc8209fafd0 -> 0xc8209fafe0 -> 0xc8209faff0 -> 0xc8209fb000 -> 0xc8209fb010 -> 0xc8209fb020 -> 0xc8209fb030 -> 0xc8209fb040 -> 0xc8209fb050 -> 0xc8209fb060 -> 0xc8209fb070 -> 0xc8209fb080 -> 0xc8209fb0a0 -> 0xc8209fb0c0 -> 0xc8209fb110 -> 0xc8209fb130 -> 0xc8209fb150 -> 0xc8209fb170 -> 0xc8209fb210 -> 0x221b (BAD)
fatal error: free list corrupted

runtime stack:
runtime.throw(0x190a970, 0x13)
        /usr/local/go/src/runtime/panic.go:530 +0x90
runtime.(*mspan).sweep(0x7fd4e093c7c0, 0x64bd00006400, 0x201)
        /usr/local/go/src/runtime/mgcsweep.go:201 +0x852
runtime.sweepone(0x0)
        /usr/local/go/src/runtime/mgcsweep.go:112 +0x23e
runtime.gosweepone.func1()
        /usr/local/go/src/runtime/mgcsweep.go:124 +0x21
runtime.systemstack(0x7fd4d6ffcbf8)
        /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.gosweepone(0x25f35a8)
        /usr/local/go/src/runtime/mgcsweep.go:125 +0x3d
runtime.deductSweepCredit(0x2000, 0x0)
        /usr/local/go/src/runtime/mgcsweep.go:384 +0xc6
runtime.(*mcentral).cacheSpan(0x25f38f0, 0x7fd4e086cdf0)
        /usr/local/go/src/runtime/mcentral.go:36 +0x56
runtime.(*mcache).refill(0x7fd4e097a000, 0x2, 0x25e8f30)
        /usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:610 +0x28
runtime.systemstack(0xc820016000)
        /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1048

goroutine 13 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820436e40 sp=0xc820436e38
runtime.mallocgc(0x8, 0x14b63c0, 0xffffffff00000001, 0xffffffff00000002)
        /usr/local/go/src/runtime/malloc.go:611 +0x365 fp=0xc820436f18 sp=0xc820436e40
runtime.newobject(0x14b63c0, 0x0)
        /usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc820436f40 sp=0xc820436f18
runtime.gcBgMarkWorker(0xc820016000)
        /usr/local/go/src/runtime/mgc.go:1375 +0x95 fp=0xc820436fb8 sp=0xc820436f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820436fc0 sp=0xc820436fb8
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1329 +0x92
```

Full log for that node:

[cockroach.stderr.txt](https://github.com/cockroachdb/cockroach/files/190505/cockroach.stderr.txt)

### PR DESCRIPTION
**Pull request by cuongdo**
This is a hodgepodge of changes:
- Log max RSS to console.
- Record max RSS to time series & graph.
- Change Y scale and graph title for Go garbage collection time.
- Graph RocksDB iterator pinned cache usage and memtable total size.
- Remove calls to mallinfo (useless because of 32-bit limits) and
  malloc_info (corrupted memory when called using inline C).
- Use max RSS instead of Go memory allocated for node table.

Max RSS was verified by comparing console output and graphed values
against top & ps output on OS X and Linux.

Resolves #5566 and fixes #5592

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5628)

### CODE REVIEW

**Comment by cuongdo** [comment]
skitch

Arrows indicate changed parts.

**Comment by petermattis** [comment]
Looks good (the graphs, I didn't look at the code). I wonder if we should rename `Total Memory` to `RSS`. The term `RSS` is fairly common.

Were you going to rename the `Memory Allocated` graph to `Memory Usage`?

**Comment by cuongdo** [comment]
@petermattis: changed



---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628#-:-KDxVQCutuDYmYS4cUBK:1226455802)*

**Comment by petermattis** [comment]
LGTM (visually)

**Comment by maxlang** [comment]
:lgtm: for typescript

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[ui/ts/pages/nodes.ts, line 356 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628#-KDyDjw4PvBNXp43QX-8:-KDyDjw4PvBNXp43QX-9:-734905903) ([raw file](https://github.com/cockroachdb/cockroach/blob/bab1de1183579682061455bf1fd8356b6ec52863/ui/ts/pages/nodes.ts#L356)):*
At some point we should probably add these to MetricNames.

---

*[ui/ts/pages/nodes.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628#-KDyDSn6orFNdNY6JU-Z:-KDyDSn7-cyly3MINbUc:1589738790) ([raw file](https://github.com/cockroachdb/cockroach/blob/bab1de1183579682061455bf1fd8356b6ec52863/ui/ts/pages/nodes.ts#L413)):*
You can just pass in ```Utils.Convert.NanoToMilli``` directly

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628#-:-KDyDsoHnX2UhkM_kdFy:871787)*

**Comment by petermattis** [comment]
LGTM for the Go changes.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628#-:-KDyEfko5dViNSHSbbI6:-1153582986)*

**Comment by cuongdo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ui/ts/pages/nodes.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628#-KDyDSn6orFNdNY6JU-Z:-KDyJBLf1GRNq3QLIEdE:879233797) ([raw file](https://github.com/cockroachdb/cockroach/blob/bab1de1183579682061455bf1fd8356b6ec52863/ui/ts/pages/nodes.ts#L413)):*
trying to pass `NanoToMilli` in directly to `format()` gets me this error:

```
ts/pages/nodes.ts(957,22): error TS2345: Argument of type '(nano: number) => number' is not assignable to parameter of type '(n: number) => string'.
  Type 'number' is not assignable to type 'string'.
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628)*

**Comment by maxlang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[ui/ts/pages/nodes.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628#-KDyDSn6orFNdNY6JU-Z:-KDyMsAX0kB4vxh4YkRL:657965057) ([raw file](https://github.com/cockroachdb/cockroach/blob/bab1de1183579682061455bf1fd8356b6ec52863/ui/ts/pages/nodes.ts#L413)):*
Ah k. Your solution is fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5628)*

**Pull request merged**
