### PR TITLE
sql: change table truncation to create new indexes rather than new ID

### LINKED ISSUE #52170: sql: create new indexes rather than a new table in TRUNCATE
**Is your feature request related to a problem? Please describe.**
Today the implementation of `TRUNCATE` creates a new table with the same structure as an old one. It then drops the old one and renames it to the new one. This has caused a number of problems and bugs. Worse yet, it means that a table ID is not a stable identifier, complicating how we store references to it in other tables. 

**Describe the solution you'd like**

This was probably done because prior to 20.1, we required that every table have a primary index with ID 1. This is no longer the case since we implemented primary key changes. We should just drop all of the existing indexes and create new ones in truncate.

**Describe alternatives you've considered**
None

**Additional context**

This will make challenges related to renaming things which are referenced easier. See https://github.com/cockroachdb/cockroach/issues/10083 and https://github.com/cockroachdb/cockroach/issues/51090. 

One problem here is that the index IDs might get quite high. This could be mitigated with https://github.com/cockroachdb/cockroach/issues/47981.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #52170.

This commit updates the implementation of table truncation to create a
new set of indexes for the table, rather than creating a new table ID
for the table's data.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
cc @ajwerner @lucy-zhang wanted to get some eyes here before cleaning this up heavily and adding some schema changer tests

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/backfill.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEP-CZcAS4117B8eze2:-MEP-CZcAS4117B8eze3:bdssn38) ([raw file](https://github.com/cockroachdb/cockroach/blob/85609a5de52f5c07c572cb1079c01deb86b7ed68/pkg/sql/backfill.go#L646)):*
> ```Go
> 		if err := execCfg.DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 			var err error
> 			table, err = sqlbase.GetTableDescFromID(ctx, txn, execCfg.Codec, tableID)
> ```

can you use catalogkv here?
___
*[pkg/sql/backfill.go, line 665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEP-3eg90uQCTeawZlI:-MEP-3eg90uQCTeawZlJ:b-qe0cfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/85609a5de52f5c07c572cb1079c01deb86b7ed68/pkg/sql/backfill.go#L665)):*
> ```Go
> 			return err
> 		case errors.Is(err, sqlbase.ErrDescriptorNotFound):
> 			log.Infof(ctx, "descriptor %d not found for GCJob index truncation", tableID)
> ```

Don't you want to return here?
___
*[pkg/sql/truncate.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEOzMAvA1O5mXZ919QF:-MEOzMAvA1O5mXZ919QG:b-wiawk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/85609a5de52f5c07c572cb1079c01deb86b7ed68/pkg/sql/truncate.go#L236)):*
> ```
> 	// TODO (rohany): I'm confused about what job API to use -- i want to start the
> 	//  job and not wait for it at all.
> ```
You want `CreateAdoptableJobWithTxn`

----

I feel like we need to make sure in the gcjob that the leases have drained for the current version. Does that happen anywhere?
___
*[pkg/sql/truncate.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEOzkxx88XzEdkjO3Tr:-MEOzkxx88XzEdkjO3Ts:bvgl2dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/85609a5de52f5c07c572cb1079c01deb86b7ed68/pkg/sql/truncate.go#L361)):*
> ```
> 	// TODO (rohany): Do a query here first to see if there are any index comments
> 	//  that need to be updated.
> 	// TODO (rohany): Is there a natural way of doing this so that it is all in
> ```
This seems fine.

**Review by rohany — COMMENTED** [review]
I'll update this tomorrow with a test that ensures that interleaved data gets cleaned up on truncate. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-:-MEPETHV7otRW_CTlwbE:bijgre5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEPEYnI-I7OoTOmmQtD:-MEPEYnI-I7OoTOmmQtE:blcx22x) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ed3b4c76c8c4669365759e3c47ab5b0bfdc048/pkg/ccl/changefeedccl/changefeed_test.go#L1313)):*
> ```Go
> 		sqlDB := sqlutils.MakeSQLRunner(db)
> 
> 		// TODO (rohany): Not sure what we expect from truncations now in changefeedland.
> ```

@ajwerner what's going on here? Right now, we hang on the first call to next after the truncation -- I assume this is because now the table ID is the same and there isn't any data coming into the table. What should happen now?
___
*[pkg/sql/backfill.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEP-CZcAS4117B8eze2:-MEPELtJ6xV8Cb8sUDoa:b-2hp717) ([raw file](https://github.com/cockroachdb/cockroach/blob/85609a5de52f5c07c572cb1079c01deb86b7ed68/pkg/sql/backfill.go#L646)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you use catalogkv here?
</blockquote></details>

yeah, this PR was behind those changes.
___
*[pkg/sql/truncate.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEOzMAvA1O5mXZ919QF:-MEPEO78C4p-62bHk4uO:blw71e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/85609a5de52f5c07c572cb1079c01deb86b7ed68/pkg/sql/truncate.go#L236)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// TODO (rohany): I'm confused about what job API to use -- i want to start the
> 	//  job and not wait for it at all.
> ```
You want `CreateAdoptableJobWithTxn`

----

I feel like we need to make sure in the gcjob that the leases have drained for the current version. Does that happen anywhere?
</blockquote></details>

Done. Added a lease drain stage to the GC Job when indexes are being deleted.

**Review by ajwerner — COMMENTED** [review]
This is great! I had to think for a while about the logic of interleaved secondary indexes but it seems spot on. 

Let's get the changefeed stuff in order and merge it

> Reviewed 2 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-:-MEcaE4eEvSmC-Dte7AZ:b-nrcqf6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEPEYnI-I7OoTOmmQtD:-MEcUpB466-M9evhDLz2:blwudbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ed3b4c76c8c4669365759e3c47ab5b0bfdc048/pkg/ccl/changefeedccl/changefeed_test.go#L1313)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

@ajwerner what's going on here? Right now, we hang on the first call to next after the truncation -- I assume this is because now the table ID is the same and there isn't any data coming into the table. What should happen now?
</blockquote></details>

Yeesh yeah this is a big behavior change. We need to do something here. For now let's work to preserve the behavior that exists, I think ideally what we want is to perform a backfill that issues deletes for every key that used to exist but that can come later. 

In order to preserve the behavior, we want to classify the error appropriately such that this call returns an error:

https://github.com/cockroachdb/cockroach/blob/ab161ab87a814449e683a5af770e6ebabb9f1d22/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L436

We should make https://github.com/cockroachdb/cockroach/blob/ab161ab87a814449e683a5af770e6ebabb9f1d22/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go#L50 detect and return a new truncate event then have shouldFilter return an error indicating that the table has been truncated with a TODO to do something better.
___
*[pkg/sql/truncate.go, line 379 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEcac_n6W3Gsfo97dAw:-MEcac_n6W3Gsfo97dAx:b-ikqloj) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ab706ae1a7b2485a73f61c0fa068f4601e69b5/pkg/sql/truncate.go#L379)):*
> ```Go
> }
> 
> // reassignInterleaveIndexReferences reassigns all index ID's present in
> ```

This is sort of magical and amazing that for primary indexes of interleave children you don't actually need to do anything fancy like change the index ID because you've changed the parent index id. :exploding_head:

**Comment by rohany** [comment]
> This is sort of magical and amazing that for primary indexes of interleave children you don't actually need to do anything fancy like change the index ID because you've changed the parent index id. 🤯

IDK if this is as :brain: as you're imagining -- we traverse the interleaved hierarchy during the truncate and reassign all of the index ID's when processing each table.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @lucy-zhang)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEPEYnI-I7OoTOmmQtD:-MEd0g4C9eV1WDLHM__R:b-q1stup) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ed3b4c76c8c4669365759e3c47ab5b0bfdc048/pkg/ccl/changefeedccl/changefeed_test.go#L1313)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yeesh yeah this is a big behavior change. We need to do something here. For now let's work to preserve the behavior that exists, I think ideally what we want is to perform a backfill that issues deletes for every key that used to exist but that can come later. 

In order to preserve the behavior, we want to classify the error appropriately such that this call returns an error:

https://github.com/cockroachdb/cockroach/blob/ab161ab87a814449e683a5af770e6ebabb9f1d22/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L436

We should make https://github.com/cockroachdb/cockroach/blob/ab161ab87a814449e683a5af770e6ebabb9f1d22/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go#L50 detect and return a new truncate event then have shouldFilter return an error indicating that the table has been truncated with a TODO to do something better.
</blockquote></details>

Done. However, i tried to add some tests for this (to differentiate table truncation from primary key changes) and my test failed with errors out side of this (we can differentiate truncation from pk changes). I added this test:

```

// TestChangefeedPrimaryKeyChange ensures that primary key changes aren't
// interpreted as table truncations by the changefeed table event filters.
func TestChangefeedPrimaryKeyChange(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	testFn := func(t *testing.T, db *gosql.DB, f cdctest.TestFeedFactory) {
		sqlDB := sqlutils.MakeSQLRunner(db)

		// Create a table and add some data.
		sqlDB.Exec(t, `CREATE TABLE t (x INT PRIMARY KEY, y INT NOT NULL)`)
		sqlDB.Exec(t, `INSERT INTO t VALUES (1, 1)`)
		tfeed := feed(t, f, `CREATE CHANGEFEED FOR t`)
		defer closeFeed(t, tfeed)
		assertPayloads(t, tfeed, []string{`t: [1]->{"after": {"x": 1, "y": 1}}`})
		// Now change the primary key.
		sqlDB.Exec(t, `ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (y)`)
		// Insert a new value.
		sqlDB.Exec(t, `INSERT INTO t VALUES (2, 2)`)
		assertPayloads(t, tfeed, []string{`t: [1]->{"after": {"x": 2, "y": 2}}`})
	}

	t.Run(`sinkless`, sinklessTest(testFn))
	t.Run(`enterprise`, enterpriseTest(testFn))
}
```

and it fails with an `decoding unset encdatum` error. I think this can be addressed in future PRs by folks with more change feed knowledge.

**Review by ajwerner — APPROVED** [review]
:lgtm: after a rebase and the nits

> Reviewed 1 of 12 files at r3, 2 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-:-MEddSnT5GvXy3SnQR4I:b-1t3pz8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEPEYnI-I7OoTOmmQtD:-MEdZM1U6EPTWx1uJUiW:bxsuxyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ed3b4c76c8c4669365759e3c47ab5b0bfdc048/pkg/ccl/changefeedccl/changefeed_test.go#L1313)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Done. However, i tried to add some tests for this (to differentiate table truncation from primary key changes) and my test failed with errors out side of this (we can differentiate truncation from pk changes). I added this test:

```

// TestChangefeedPrimaryKeyChange ensures that primary key changes aren't
// interpreted as table truncations by the changefeed table event filters.
func TestChangefeedPrimaryKeyChange(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	testFn := func(t *testing.T, db *gosql.DB, f cdctest.TestFeedFactory) {
		sqlDB := sqlutils.MakeSQLRunner(db)

		// Create a table and add some data.
		sqlDB.Exec(t, `CREATE TABLE t (x INT PRIMARY KEY, y INT NOT NULL)`)
		sqlDB.Exec(t, `INSERT INTO t VALUES (1, 1)`)
		tfeed := feed(t, f, `CREATE CHANGEFEED FOR t`)
		defer closeFeed(t, tfeed)
		assertPayloads(t, tfeed, []string{`t: [1]->{"after": {"x": 1, "y": 1}}`})
		// Now change the primary key.
		sqlDB.Exec(t, `ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (y)`)
		// Insert a new value.
		sqlDB.Exec(t, `INSERT INTO t VALUES (2, 2)`)
		assertPayloads(t, tfeed, []string{`t: [1]->{"after": {"x": 2, "y": 2}}`})
	}

	t.Run(`sinkless`, sinklessTest(testFn))
	t.Run(`enterprise`, enterpriseTest(testFn))
}
```

and it fails with an `decoding unset encdatum` error. I think this can be addressed in future PRs by folks with more change feed knowledge.
</blockquote></details>

I created https://github.com/cockroachdb/cockroach/issues/52796 to track. 
___
*[pkg/sql/backfill.go, line 627 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEdecTy0O37qAoLKPCH:-MEdecTz1-Dv9YVRUyYf:bmj8kp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/00670a2d4bea3157067a8ca7dc0f03500ded2347/pkg/sql/backfill.go#L627)):*
> ```
> // SchemaChanger.truncateIndexes instead because that accesses the most recent
> // version of the table when deleting. In this case, we need to use the version
> // of the table before truncation, which is passed in.
> ```
Is it worth trying to unify some code between the two?
___
*[pkg/sql/backfill.go, line 643 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEddlCWBtezIUoNT6gS:-MEddlCWBtezIUoNT6gT:bodbuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/00670a2d4bea3157067a8ca7dc0f03500ded2347/pkg/sql/backfill.go#L643)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			if log.V(2) {
> 				log.Infof(
> 					ctx, "truncate interleaved index (%d) at row: %d, span: %s", table.ID, rowIdx, resume)
> 			}
> ```
</details>

This is a weird wrapping. Also I think `log.VEventf` is strictly better in this case.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52235)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @lucy-zhang)

___
*[pkg/sql/backfill.go, line 627 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-MEdecTy0O37qAoLKPCH:-MEdg3ktA931gteOmUUs:b-s5ef25) ([raw file](https://github.com/cockroachdb/cockroach/blob/00670a2d4bea3157067a8ca7dc0f03500ded2347/pkg/sql/backfill.go#L627)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // SchemaChanger.truncateIndexes instead because that accesses the most recent
> // version of the table when deleting. In this case, we need to use the version
> // of the table before truncation, which is passed in.
> ```
Is it worth trying to unify some code between the two?
</blockquote></details>

Trust me, I spent a long time trying. Trying to unify them but also allow the schema changer use case to refetch the table at every iteration  led to some weird interfaces.

**Comment by rohany** [comment]
> This is a weird wrapping. Also I think log.VEventf is strictly better in this case.

Switched to a veventf

**Review by ajwerner — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52235#-:-MEdyytzCedpOLSoOT2C:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @lucy-zhang)

**Pull request merged**
