### PR TITLE
deps: upgrade sarama@1.42.1 to version 1.43.1

### PR DESCRIPTION
**Pull request by wenyihu6**
This patch upgrades sarama to v1.43.1 to pick up fix https://github.com/IBM/sarama/pull/2826 related to the kafka
throttling feature we supported in v24.1. It addresses a race condition where
producer could be blocked.

Epic: none

Release note: fixed a race condition in sarama when kafka throttling is
enabled

### CODE REVIEW

**Comment by rharding6373** [comment]
sarama's [changelog](https://github.com/IBM/sarama/blob/main/CHANGELOG.md) isn't up-to-date. I looked at a diff of the changes between 1.42.1 and 1.43.1 and it looks like the changes are minor except for 2 bug fixes (https://github.com/IBM/sarama/compare/v1.42.1...v1.43.1).

LGTM Thanks for tracking this Wenyi!

**Review by rharding6373 — APPROVED** [review]

**Comment by wenyihu6** [comment]
Thanks for checking the diff between the two versions! Do we want to backport this?

**Comment by rharding6373** [comment]
Yes, I think we should backport. Given the few changes in the diff it seems like a lowish risk highish reward situation.

**Comment by wenyihu6** [comment]
TFTR! 

bors r=rharding6373

**Comment by wenyihu6** [comment]
bors retry

**Comment by wenyihu6** [comment]
backport 24.2 24.3

**Comment by wenyihu6** [comment]
blathers backport 24.2 24.3

**Pull request merged**
