### PR TITLE
fix logcrash issue on ppc64le                                                                                                                                                                                                           

### PR DESCRIPTION
**Pull request by ambujkumar3**
Release note: none.

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]

**Comment by andreimatei** [comment]
Thanks! Merging.

bors r+

**Comment by andreimatei** [comment]
@ambujkumar3 I think you need to sign the CLA above.

**Comment by ambujkumar3** [comment]
> @ambujkumar3 I think you need to sign the CLA above.
@andreimatei already signed CLA but till now it's showing as progress, is it any issue or required more input. could you please confirm me.

**Comment by andreimatei** [comment]
merging
bors r+

**Pull request merged**
