### PR TITLE
sql,server: enable tenant status server to work with persisted SQL stats

### LINKED ISSUE #70585: sql: persisted SQL Stats is not returned by tenant RPC endpoints
I think this is surfacing the bigger issue where our test coverage for tenant code is a lot smaller than non-tenant code. Ideally, we only need to write once and run them in both configurations. (perhaps even better, we just have one status server used by both tenant/non-tenant). However, this is not the case today.

### PR DESCRIPTION
**Pull request by Azhng**
Previsouly, tenant status server was not able to work with the new
persisted SQL Stats. This result in SQL Stats RPC not able to return
or reset persisted SQL stats.
This commit addresses this issue to update tenant status server's
implementation to be able to work with persisted SQL Stats.

Resolves #70585 #70529 #68177

Release Justification: Bug fixes and low-risk updates to new functionality

Release note (bug fix): Statement/Transaction Page now is able to
display and reset persisted SQL Stats.

### CODE REVIEW

**Comment by Azhng** [comment]
@dhartunian Do you mind also taking a look since this depends on the pod2pod infra?

**Review by maryliag — COMMENTED** [review]
> Reviewed 9 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @dhartunian)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEg9uxBYcbLIccbwKG:-MkEg9uxBYcbLIccbwKH:bvwk3ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ccl/serverccl/tenant_status_test.go#L258)):*
> ```Go
> 
> 			for _, txn := range statsPostReset.Transactions {
> 				for _, previousTxn := range statsPreReset.Transactions {
> ```

nit: is previous the right word here? Considering this is the check post reset
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEgCDU1rU3T9g2G8va:-MkEgCDU1rU3T9g2G8vb:b51l13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ccl/serverccl/tenant_status_test.go#L265)):*
> ```Go
> 
> 			for _, stmt := range statsPostReset.Statements {
> 				for _, previousStmt := range statsPreReset.Statements {
> ```

nit: same as above
___
*[pkg/server/sql_stats.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEgaLC08nzsK1ShDxp:-MkEgaLC08nzsK1ShDxq:b9jwgyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/server/sql_stats.go#L37)):*
> ```Go
> 	controller := s.sqlServer.pgServer.SQLServer.GetSQLStatsController()
> 
> 	// We short circuit the handler to use the SQL Stats Controller if we are
> ```

nit: not sure if your sentence "we short circuit the handler" is very clear on that this is doing
___
*[pkg/server/tenant_status.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEgvEM1z7bmspcAmNj:-MkEgvEM1z7bmspcAmNk:bqgz5xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/server/tenant_status.go#L214)):*
> ```Go
> 	controller := t.sqlServer.pgServer.SQLServer.GetSQLStatsController()
> 
> 	// We short circuit the handler to use the SQL Stats Controller if we are
> ```

nit: same as previous comment
___
*[pkg/sql/sqlstats/sslocal/sql_stats_controller.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEhDRi8hz2KBhOSuMP:-MkEhDRi8hz2KBhOSuMQ:b-4spbmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/sql/sqlstats/sslocal/sql_stats_controller.go#L40)):*
> ```Go
> func (s *Controller) ResetClusterSQLStats(ctx context.Context) error {
> 	req := &serverpb.ResetSQLStatsRequest{
> 		ResetPersistedStats: false,
> ```

nit: can you add some comment on why this is hard coded to false?
___
*[pkg/ui/workspaces/cluster-ui/src/api/sqlStatsApi.ts, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEhLkQ1hk6yrcZdPut:-MkEhLkQ1hk6yrcZdPuu:b-r8r77k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ui/workspaces/cluster-ui/src/api/sqlStatsApi.ts#L22)):*
> ```XML
>     cockroach.server.serverpb.ResetSQLStatsRequest,
>     new cockroach.server.serverpb.ResetSQLStatsRequest({
>       reset_persisted_stats: true,
> ```

nit: same as previous, add a comment to explain why the hard coded value here
___
*[pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEhR5zE8muZlufmSWD:-MkEhR5zE8muZlufmSWE:bl7a169) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts#L25)):*
> ```XML
> export function* resetSQLStatsSaga() {
>   const resetSQLStatsRequest = new ResetSQLStatsRequest({
>     reset_persisted_stats: true,
> ```

nit: same as others

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEg9uxBYcbLIccbwKG:-MkFj9t7EW9Xx4G43iat:bt1b19p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ccl/serverccl/tenant_status_test.go#L258)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: is previous the right word here? Considering this is the check post reset
</blockquote></details>

Renamed.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEgCDU1rU3T9g2G8va:-MkFjBsTEWRpNJYsI_rI:ba3o3s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ccl/serverccl/tenant_status_test.go#L265)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: same as above
</blockquote></details>

Renamed
___
*[pkg/server/sql_stats.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEgaLC08nzsK1ShDxp:-MkFjDbQAtdXHfCsLgx7:b-qj92pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/server/sql_stats.go#L37)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: not sure if your sentence "we short circuit the handler" is very clear on that this is doing
</blockquote></details>

Reworded.
___
*[pkg/server/tenant_status.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEgvEM1z7bmspcAmNj:-MkFjI7-153kPAx0aN0t:bwg0dnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/server/tenant_status.go#L214)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: same as previous comment
</blockquote></details>

reworded
___
*[pkg/sql/sqlstats/sslocal/sql_stats_controller.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEhDRi8hz2KBhOSuMP:-MkFjJc97s1SaiYBHuIL:b-bizqh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/sql/sqlstats/sslocal/sql_stats_controller.go#L40)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: can you add some comment on why this is hard coded to false?
</blockquote></details>

Added comment.
___
*[pkg/ui/workspaces/cluster-ui/src/api/sqlStatsApi.ts, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEhLkQ1hk6yrcZdPut:-MkFjKrI8hn1tEbq4xLJ:b-bttoee) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ui/workspaces/cluster-ui/src/api/sqlStatsApi.ts#L22)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: same as previous, add a comment to explain why the hard coded value here
</blockquote></details>

Added comment
___
*[pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkEhR5zE8muZlufmSWD:-MkFjM1n9voAlpXgPLN2:b-bttoee) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2678d8ef9f72e3931f4f64e714ef8c13ba6ac1c/pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts#L25)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: same as others
</blockquote></details>

Added comment

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-:-MkHmGXlDPY7MYLE1LT1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — COMMENTED** [review]
:lgtm: other than some nits and commit msg.

Can you expand the commit message a bit? You're modifying the API so it's worth noting that even though it's not strictly user-facing. The PR combines a few functionality tweaks so it's good to call them out.

> Reviewed 6 of 15 files at r1, 3 of 6 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-:-MkJr7RiCeXTs-uCSyED:bhyfq9t)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng)

___
*[-- commits, line 4 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJi1ToDU81s1RFk_U6):*
nit: "Previously"
___
*[-- commits, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJi72OD1FvUUDG3wZE):*
FYI I think you only need Justification prior to the branch cut. Will be necessary in PR for backport. 
___
*[pkg/ccl/serverccl/tenant_test_utils.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJqL57845MX7p7k5fJ:-MkJqL5886W0SZSa8p3R:b-31uu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/09993f4f2ca40f1dac0a5c412e10f86af9f69c4b/pkg/ccl/serverccl/tenant_test_utils.go#L85)):*
> ```Go
> 		hostCluster:          testCluster,
> 		tenantTestCluster:    newTenantCluster(t, server, tenantClusterSize, 10 /* tenantID */),
> 		tenantControlCluster: newTenantCluster(t, server, tenantClusterSize, 11 /* tenantID */),
> ```

consider grabbing the `tenantID` values from `security.EmbeddedTenantIDs()` just so it's clear why we pick 10,11 etc.
___
*[pkg/server/serverpb/status.proto, line 1127 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJiSx45OcH31j07GCR:-MkJiSx5-InSBhBJDYwF:bau8c72) ([raw file](https://github.com/cockroachdb/cockroach/blob/09993f4f2ca40f1dac0a5c412e10f86af9f69c4b/pkg/server/serverpb/status.proto#L1127)):*
> ```protobuf
> message ResetSQLStatsRequest {
>   string node_id = 1 [(gogoproto.customname) = "NodeID"];
>   bool reset_persisted_stats = 2;
> ```

Add docs for this field.
___
*[pkg/sql/sqlstats/sslocal/sql_stats_controller.go, line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJioNO-5KVFxhoINgw:-MkJioNO-5KVFxhoINgx:b21ooby) ([raw file](https://github.com/cockroachdb/cockroach/blob/09993f4f2ca40f1dac0a5c412e10f86af9f69c4b/pkg/sql/sqlstats/sslocal/sql_stats_controller.go#L45)):*
> ```Go
> 		// stats.
> 		ResetPersistedStats: false,
> 	}
> ```

Helpful comment, thanks!

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70586)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian and @maryliag)

___
*[-- commits, line 4 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJi1ToDU81s1RFk_U6):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: "Previously"
</blockquote></details>

Done.
___
*[pkg/ccl/serverccl/tenant_test_utils.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJqL57845MX7p7k5fJ:-MkNx35xC1L8TJiB92_-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09993f4f2ca40f1dac0a5c412e10f86af9f69c4b/pkg/ccl/serverccl/tenant_test_utils.go#L85)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

consider grabbing the `tenantID` values from `security.EmbeddedTenantIDs()` just so it's clear why we pick 10,11 etc.
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.proto, line 1127 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70586#-MkJiSx45OcH31j07GCR:-MkNxHeY2M7LgNOZ7OL9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09993f4f2ca40f1dac0a5c412e10f86af9f69c4b/pkg/server/serverpb/status.proto#L1127)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Add docs for this field.
</blockquote></details>

Done.

**Comment by Azhng** [comment]
TFTR!

bors r=maryliag,dhartunian

**Comment by Azhng** [comment]
Flaked :/ 

bors r=maryliag,dhartunian

**Pull request merged**
