### PR TITLE
roachtest: fix backup2TB by using IMPORT, rip out store dumps

### LINKED ISSUE #34702: roachtest: backup2TB failed
SHA: https://github.com/cockroachdb/cockroach/commits/4e2e450ecf5c3f73c7de46e48696528468803db7

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=backup2TB PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1128035&tab=buildLog

```
The test failed on master:
	test.go:743,backup.go:42: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1128035-backup2tb:1 -- mkdir -p {store-dir} && gsutil -m cp -r gs://cockroach-fixtures/workload/bank/version=1.0.0,payload-bytes=10240,ranges=0,rows=65104166,seed=1/stores=10,bin-version=2.0/1/* {store-dir} returned:
		stderr:
		
		stdout:
		.0 GiB/153.0 GiB]  18% Done 323.6 MiB/s ETA 00:06:32     
Copying gs://cockroach-fixtures/workload/bank/version=1.0.0,payload-bytes=10240,ranges=0,rows=65104166,seed=1/stores=10,bin-version=2.0/1/002294.sst...
		Copying gs://cockroach-fixtures/workload/bank/version=1.0.0,payload-bytes=10240,ranges=0,rows=65104166,seed=1/stores=10,bin-version=2.0/1/002295.sst...
		- [1.2k/5.9k files][ 29.1 GiB/153.0 GiB]  18% Done 324.5 MiB/s ETA 00:06:31     
- [1.2k/5.9k files][ 29.1 GiB/153.0 GiB]  18% Done 324.5 MiB/s ETA 00:06:31     
Copying gs://cockroach-fixtures/workload/bank/version=1.0.0,payload-bytes=10240,ranges=0,rows=65104166,seed=1/stores=10,bin-version=2.0/1/002297.sst...
		- [1.2k/5.9k files][ 29.1 GiB/153.0 GiB]  18% Done 325.4 MiB/s ETA 00:06:30     
- [1.2k/5.9k files][ 29.1 GiB/153.0 GiB]  19% Done 325.1 MiB/s ETA 00:06:30     
- [1.2k/5.9k files][ 29.1 GiB/153.0 GiB]  19% Done 324.7 MiB/s ETA 00:06:31     
- [1.2k/5.9k files][ 29.1 GiB/153.0 GiB]  19% Done 325.3 MiB/s ETA 00:06:30     
Error:  exit status 255
		: exit status 1

```

### PR DESCRIPTION
**Pull request by tbg**
Now that 19.1 is tagged, the store dumps don't work any more. Consequently
the tests haven't run in over two weeks. Before that, it had episodes
during which it didn't run most of the time due to flakes downloading the
store dumps. Hopefully now it'll be more reliable.

Rip out the unused remainders of store dumps as well.

Fixes #34702.

Release note: None

### CODE REVIEW

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @tbg)

___
*[pkg/cmd/roachtest/backup.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-LcWGkoY1ybipkLEnkL4:-LcWGkoY1ybipkLEnkL5:b-wffsi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fe80be3624cb5b2bc1ea2e83920d7ef4e6fd2d6/pkg/cmd/roachtest/backup.go#L39)):*
> ```Go
> 			// bank.bank doesn't exist, probably due to some gossip propagation
> 			// delay.
> 			delay := 5 * time.Second
> ```

Can you change this to poll for the existence of `bank.bank` before launching the `BACKUP` command?  Then a longer timeout, maybe 1 minute, could be used before bailing out.
___
*[pkg/cmd/roachtest/cluster.go, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-LcWFyJb802XEFqqtr3v:-LcWFyJb802XEFqqtr3w:bjtn46f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c27c854e135a3efcda1465e56e3c66a371f4bf4/pkg/cmd/roachtest/cluster.go#L530)):*
> ```Go
> }
> 
> func (s *clusterSpec) String() string {
> ```

Is this change intentional?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @petermattis)

___
*[pkg/cmd/roachtest/backup.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-LcWGkoY1ybipkLEnkL4:-LcWUmyYCWMAFtFv9Dda:bu5n36) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fe80be3624cb5b2bc1ea2e83920d7ef4e6fd2d6/pkg/cmd/roachtest/backup.go#L39)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Can you change this to poll for the existence of `bank.bank` before launching the `BACKUP` command?  Then a longer timeout, maybe 1 minute, could be used before bailing out.
</blockquote></details>



BTW, filed this issue as https://github.com/cockroachdb/cockroach/issues/36841. This is a bug.

I'll make that change, though I think it's largely an idle diversion. If it takes more than 5s, I'm happy to fail the test. And the test takes many hours, so the 5s don't matter.
___
*[pkg/cmd/roachtest/cluster.go, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-LcWFyJb802XEFqqtr3v:-LcWUtYI6fh3RPjcbdyb:b-t2ennv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c27c854e135a3efcda1465e56e3c66a371f4bf4/pkg/cmd/roachtest/cluster.go#L530)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is this change intentional?
</blockquote></details>

Yes, with the pointer receiver you couldn't call this when you had a value. Now that it has a value receiver it works both on a `clusterSpec` and a `*clusterSpec`. For example, the new code in `registerBackup` makes use of this.

**Review by petermattis — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-:-LcWtOmuCXNPfM-mRWdP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter)

___
*[pkg/cmd/roachtest/backup.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-LcWGkoY1ybipkLEnkL4:-LcWtCjl6bdWRYgo_WTT:b-mln7kx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fe80be3624cb5b2bc1ea2e83920d7ef4e6fd2d6/pkg/cmd/roachtest/backup.go#L39)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>



BTW, filed this issue as https://github.com/cockroachdb/cockroach/issues/36841. This is a bug.

I'll make that change, though I think it's largely an idle diversion. If it takes more than 5s, I'm happy to fail the test. And the test takes many hours, so the 5s don't matter.
</blockquote></details>

Nit: `const delay = 5 * time.Second`.

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=petermattis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-:-LcX0QubC5i2z1JLUl3C:b-spmsx3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bobvawter and @petermattis)

___
*[pkg/cmd/roachtest/backup.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36832#-LcWGkoY1ybipkLEnkL4:-LcX0O6Y3dywvK-fhG2W:b99dolt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fe80be3624cb5b2bc1ea2e83920d7ef4e6fd2d6/pkg/cmd/roachtest/backup.go#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `const delay = 5 * time.Second`.
</blockquote></details>

I did it The Bob Way.

**Review by bobvawter — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36832)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
