### PR TITLE
bazel: add a few test suites and label broken tests

### PR DESCRIPTION
**Pull request by rickystewart**
I attempted to manually identify the appropriate "size" of each test,
marking each test that is unconditionally broken in the Bazel sandbox
with the `broken_in_bazel` tag. We can go through the tree and fix each
test marked with that tag later. This made it trivial to add some
convenience unit test suites; for example, you can run all the quicker
tests with `bazel test pkg:small_tests`.

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
This is pretty awesome, TIL. +cc @otan, check this out.

---

Defining a top-level test suite that just excludes broken packages would be a great way to insta-onboard a wide gamut of (signed off) tests onto CI.

---

Looking at `ALL_TESTS`, it's the kind of thing that could out of date really quickly. But I think we have a way out. I found https://github.com/bazelbuild/rules_go/blob/4e4ef6c/tests/integration/popular_repos/popular_repos.py#L278, and I think we ought to do something similar. I'll not gate this PR, but it'd be worth following up on using `bazel query 'kind(go_test,  //pkg/...)'` instead, which programatically gives us what we need. It's worth adding a TODO at least.

---

Here's the timing information for these tests, and I think we could mark a few more as medium (>10s) instead? Ignoring of course that this "benchmark" is running on my Mac while I'm doing other stuff. pkg/storage should definitely not be small. (Also included are are two packages we should mark as broken.)

```
//pkg/blobs:blobs_test                                          (cached) PASSED in 5.3s
//pkg/ccl/baseccl:baseccl_test                                  (cached) PASSED in 2.4s
//pkg/ccl/storageccl/engineccl:engineccl_test                   (cached) PASSED in 2.7s
//pkg/clusterversion:clusterversion_test                        (cached) PASSED in 4.8s
//pkg/cmd/cmpconn:cmpconn_test                                  (cached) PASSED in 6.0s
//pkg/cmd/github-pull-request-make:github-pull-request-make_test (cached) PASSED in 3.5s
//pkg/cmd/internal/issues:issues_test                           (cached) PASSED in 3.4s
//pkg/cmd/publish-provisional-artifacts:publish-provisional-artifacts_test (cached) PASSED in 3.8s
//pkg/cmd/testfilter:testfilter_test                            (cached) PASSED in 2.5s
//pkg/col/coldataext:coldataext_test                            (cached) PASSED in 5.9s
//pkg/col/colserde:colserde_test                                (cached) PASSED in 4.6s
//pkg/geo/geoproj:geoproj_test                                  (cached) PASSED in 1.9s
//pkg/geo/geoprojbase:geoprojbase_test                          (cached) PASSED in 2.8s
//pkg/keys:keys_test                                            (cached) PASSED in 2.1s
//pkg/kv/kvclient/rangecache:rangecache_test                    (cached) PASSED in 4.1s
//pkg/kv/kvserver/apply:apply_test                              (cached) PASSED in 2.6s
//pkg/kv/kvserver/closedts/minprop:minprop_test                 (cached) PASSED in 2.9s
//pkg/kv/kvserver/closedts/provider:provider_test               (cached) PASSED in 4.8s
//pkg/kv/kvserver/closedts/storage:storage_test                 (cached) PASSED in 7.5s
//pkg/kv/kvserver/closedts/tracker:tracker_test                 (cached) PASSED in 3.8s
//pkg/kv/kvserver/closedts/transport:transport_test             (cached) PASSED in 2.2s
//pkg/kv/kvserver/observedts:observedts_test                    (cached) PASSED in 3.7s
//pkg/kv/kvserver/protectedts:protectedts_test                  (cached) PASSED in 3.7s
//pkg/kv/kvserver/rditer:rditer_test                            (cached) PASSED in 2.0s
//pkg/kv/kvserver/tenantrate:tenantrate_test                    (cached) PASSED in 3.4s
//pkg/roachpb:roachpb_test                                      (cached) PASSED in 5.8s
//pkg/rpc/nodedialer:nodedialer_test                            (cached) PASSED in 3.2s
//pkg/server/debug/pprofui:pprofui_test                         (cached) PASSED in 2.1s
//pkg/server/diagnostics/diagnosticspb:diagnosticspb_test       (cached) PASSED in 5.8s
//pkg/server/heapprofiler:heapprofiler_test                     (cached) PASSED in 2.3s
//pkg/server/serverpb:serverpb_test                             (cached) PASSED in 10.0s
//pkg/server/status:status_test                                 (cached) PASSED in 4.2s
//pkg/settings:settings_test                                    (cached) PASSED in 2.4s
//pkg/sql/catalog:catalog_test                                  (cached) PASSED in 5.0s
//pkg/sql/catalog/catalogkeys:catalogkeys_test                  (cached) PASSED in 5.6s
//pkg/sql/catalog/catalogkv:catalogkv_test                      (cached) PASSED in 9.9s
//pkg/sql/catalog/dbdesc:dbdesc_test                            (cached) PASSED in 5.9s
//pkg/sql/catalog/descpb:descpb_test                            (cached) PASSED in 6.6s
//pkg/sql/catalog/schemaexpr:schemaexpr_test                    (cached) PASSED in 3.1s
//pkg/sql/catalog/systemschema:systemschema_test                (cached) PASSED in 5.9s
//pkg/sql/colcontainer:colcontainer_test                        (cached) PASSED in 8.1s
//pkg/sql/colencoding:colencoding_test                          (cached) PASSED in 5.2s
//pkg/sql/colexecbase:colexecbase_test                          (cached) PASSED in 3.9s
//pkg/sql/colflow/colrpc:colrpc_test                            (cached) PASSED in 3.7s
//pkg/sql/contention:contention_test                            (cached) PASSED in 4.8s
//pkg/sql/enum:enum_test                                        (cached) PASSED in 8.9s
//pkg/sql/gcjob/gcjobnotifier:gcjobnotifier_test                (cached) PASSED in 3.0s
//pkg/sql/inverted:inverted_test                                (cached) PASSED in 1.9s
//pkg/sql/lexbase:lexbase_test                                  (cached) PASSED in 1.6s
//pkg/sql/oidext:oidext_test                                    (cached) PASSED in 2.6s
//pkg/sql/opt/exec/explain:explain_test                         (cached) PASSED in 6.6s
//pkg/sql/opt/idxconstraint:idxconstraint_test                  (cached) PASSED in 3.7s
//pkg/sql/opt/optbuilder:optbuilder_test                        (cached) PASSED in 4.9s
//pkg/sql/opt/optgen/cmd/optfmt:optfmt_test                     (cached) PASSED in 2.6s
//pkg/sql/opt/ordering:ordering_test                            (cached) PASSED in 4.5s
//pkg/sql/opt/props:props_test                                  (cached) PASSED in 9.7s
//pkg/sql/opt/props/physical:physical_test                      (cached) PASSED in 3.2s
//pkg/sql/pgwire/hba:hba_test                                   (cached) PASSED in 2.3s
//pkg/sql/privilege:privilege_test                              (cached) PASSED in 2.7s
//pkg/sql/querycache:querycache_test                            (cached) PASSED in 8.4s
//pkg/sql/rowcontainer:rowcontainer_test                        (cached) PASSED in 7.8s
//pkg/sql/rowflow:rowflow_test                                  (cached) PASSED in 7.9s
//pkg/sql/schemachanger/scpb:scpb_test                          (cached) PASSED in 5.0s
//pkg/sql/span:span_test                                        (cached) PASSED in 3.4s
//pkg/storage:storage_test                                      (cached) PASSED in 37.2s
//pkg/testutils/reduce:reduce_test                              (cached) PASSED in 5.4s
//pkg/ts/testmodel:testmodel_test                               (cached) PASSED in 4.9s
//pkg/util:util_test                                            (cached) PASSED in 3.3s
//pkg/util/cgroups:cgroups_test                                 (cached) PASSED in 6.2s
//pkg/util/ctxgroup:ctxgroup_test                               (cached) PASSED in 2.0s
//pkg/util/errorutil/unimplemented:unimplemented_test           (cached) PASSED in 5.0s
//pkg/util/flagutil:flagutil_test                               (cached) PASSED in 5.4s
//pkg/util/fsm:fsm_test                                         (cached) PASSED in 1.9s
//pkg/util/fuzzystrmatch:fuzzystrmatch_test                     (cached) PASSED in 3.8s
//pkg/util/grpcutil:grpcutil_test                               (cached) PASSED in 2.6s
//pkg/util/hlc:hlc_test                                         (cached) PASSED in 2.3s
//pkg/util/interval:interval_test                               (cached) PASSED in 7.7s
//pkg/util/ipaddr:ipaddr_test                                   (cached) PASSED in 2.1s
//pkg/util/limit:limit_test                                     (cached) PASSED in 3.4s
//pkg/util/log/logconfig:logconfig_test                         (cached) PASSED in 2.8s
//pkg/util/log/testshout:testshout_test                         (cached) PASSED in 3.4s
//pkg/util/metric/aggmetric:aggmetric_test                      (cached) PASSED in 2.3s
//pkg/util/mon:mon_test                                         (cached) PASSED in 7.0s
//pkg/util/netutil:netutil_test                                 (cached) PASSED in 2.1s
//pkg/util/protoutil:protoutil_test                             (cached) PASSED in 5.3s
//pkg/util/retry:retry_test                                     (cached) PASSED in 3.6s
//pkg/util/ring:ring_test                                       (cached) PASSED in 35.6s
//pkg/util/sdnotify:sdnotify_test                               (cached) PASSED in 1.9s
//pkg/util/shuffle:shuffle_test                                 (cached) PASSED in 2.6s
//pkg/util/stop:stop_test                                       (cached) PASSED in 3.3s
//pkg/util/syncutil:syncutil_test                               (cached) PASSED in 3.6s
//pkg/util/syncutil/singleflight:singleflight_test              (cached) PASSED in 2.1s
//pkg/util/timetz:timetz_test                                   (cached) PASSED in 1.0s
//pkg/util/unique:unique_test                                   (cached) PASSED in 2.3s
//pkg/util/version:version_test                                 (cached) PASSED in 5.4s
//pkg/workload/faker:faker_test                                 (cached) PASSED in 3.7s
//pkg/workload/tpcc:tpcc_test                                   (cached) PASSED in 2.5s
//pkg/workload/workloadimpl:workloadimpl_test                   (cached) PASSED in 2.2s
//pkg/base:base_test                                                     PASSED in 6.8s
//pkg/bench:bench_test                                                   PASSED in 6.2s
//pkg/bench/ddl_analysis:ddl_analysis_test                               PASSED in 4.6s
//pkg/ccl/backupccl/backupbase:backupbase_test                           PASSED in 6.2s
//pkg/ccl/changefeedccl/cdctest:cdctest_test                             PASSED in 5.1s
//pkg/ccl/changefeedccl/kvfeed:kvfeed_test                               PASSED in 4.9s
//pkg/ccl/changefeedccl/schemafeed:schemafeed_test                       PASSED in 11.2s
//pkg/ccl/cliccl:cliccl_test                                             PASSED in 7.3s
//pkg/ccl/kvccl/kvfollowerreadsccl:kvfollowerreadsccl_test               PASSED in 11.5s
//pkg/ccl/kvccl/kvtenantccl:kvtenantccl_test                             PASSED in 7.4s
//pkg/ccl/oidcccl:oidcccl_test                                           PASSED in 7.2s
//pkg/ccl/partitionccl:partitionccl_test                                 PASSED in 51.9s
//pkg/ccl/serverccl:serverccl_test                                       PASSED in 28.3s
//pkg/ccl/streamingccl/streamclient:streamclient_test                    PASSED in 3.4s
//pkg/ccl/streamingccl/streamingest:streamingest_test                    PASSED in 22.0s
//pkg/ccl/utilccl:utilccl_test                                           PASSED in 2.6s
//pkg/ccl/utilccl/sampledataccl:sampledataccl_test                       PASSED in 5.7s
//pkg/ccl/workloadccl:workloadccl_test                                   PASSED in 7.7s
//pkg/cli/exit:exit_test                                                 PASSED in 3.0s
//pkg/cmd/cockroach-oss:cockroach-oss_test                               PASSED in 10.5s
//pkg/cmd/docgen/extract:extract_test                                    PASSED in 3.1s
//pkg/cmd/roachprod/vm:vm_test                                           PASSED in 5.4s
//pkg/col/coldata:coldata_test                                           PASSED in 8.3s
//pkg/config:config_test                                                 PASSED in 4.9s
//pkg/config/zonepb:zonepb_test                                          PASSED in 6.0s
//pkg/geo/geogen:geogen_test                                             PASSED in 1.7s
//pkg/geo/geographiclib:geographiclib_test                               PASSED in 2.1s
//pkg/geo/geotransform:geotransform_test                                 PASSED in 1.4s
//pkg/geo/wkt:wkt_test                                                   PASSED in 0.6s
//pkg/gossip:gossip_test                                                 PASSED in 6.1s
//pkg/gossip/resolver:resolver_test                                      PASSED in 2.1s
//pkg/internal/client/requestbatcher:requestbatcher_test                 PASSED in 8.7s
//pkg/internal/rsg:rsg_test                                              PASSED in 3.5s
//pkg/internal/sqlsmith:sqlsmith_test                                    PASSED in 10.4s
//pkg/jobs/jobsprotectedts:jobsprotectedts_test                          PASSED in 10.8s
//pkg/kv:kv_test                                                         PASSED in 25.4s
//pkg/kv/bulk:bulk_test                                                  PASSED in 11.3s
//pkg/kv/kvnemesis:kvnemesis_test                                        PASSED in 7.2s
//pkg/kv/kvserver/abortspan:abortspan_test                               PASSED in 5.7s
//pkg/kv/kvserver/batcheval:batcheval_test                               PASSED in 25.8s
//pkg/kv/kvserver/batcheval/result:result_test                           PASSED in 5.1s
//pkg/kv/kvserver/closedts/container:container_test                      PASSED in 2.1s
//pkg/kv/kvserver/gc:gc_test                                             PASSED in 12.2s
//pkg/kv/kvserver/idalloc:idalloc_test                                   PASSED in 9.5s
//pkg/kv/kvserver/intentresolver:intentresolver_test                     PASSED in 8.1s
//pkg/kv/kvserver/liveness:liveness_test                                 PASSED in 19.0s
//pkg/kv/kvserver/protectedts/ptcache:ptcache_test                       PASSED in 11.8s
//pkg/kv/kvserver/protectedts/ptreconcile:ptreconcile_test               PASSED in 9.3s
//pkg/kv/kvserver/protectedts/ptstorage:ptstorage_test                   PASSED in 22.1s
//pkg/kv/kvserver/protectedts/ptverifier:ptverifier_test                 PASSED in 9.4s
//pkg/kv/kvserver/raftentry:raftentry_test                               PASSED in 5.0s
//pkg/kv/kvserver/rangefeed:rangefeed_test                               PASSED in 6.3s
//pkg/kv/kvserver/reports:reports_test                                   PASSED in 24.5s
//pkg/kv/kvserver/spanset:spanset_test                                   PASSED in 2.2s
//pkg/kv/kvserver/split:split_test                                       PASSED in 6.3s
//pkg/kv/kvserver/stateloader:stateloader_test                           PASSED in 7.3s
//pkg/kv/kvserver/tscache:tscache_test                                   PASSED in 21.4s
//pkg/kv/kvserver/txnrecovery:txnrecovery_test                           PASSED in 8.1s
//pkg/kv/kvserver/txnwait:txnwait_test                                   PASSED in 2.1s
//pkg/migration/migrationcluster:migrationcluster_test                   PASSED in 5.9s
//pkg/migration/migrationmanager:migrationmanager_test                   PASSED in 11.5s
//pkg/migration/migrations:migrations_test                               PASSED in 14.1s
//pkg/rpc:rpc_test                                                       PASSED in 6.4s
//pkg/security:security_test                                             PASSED in 12.3s
//pkg/server/debug:debug_test                                            PASSED in 6.1s
//pkg/server/diagnostics:diagnostics_test                                PASSED in 28.0s
//pkg/server/dumpstore:dumpstore_test                                    PASSED in 3.0s
//pkg/server/goroutinedumper:goroutinedumper_test                        PASSED in 5.2s
//pkg/server/telemetry:telemetry_test                                    PASSED in 4.8s
//pkg/sql/catalog/catformat:catformat_test                               PASSED in 6.3s
//pkg/sql/catalog/colinfo:colinfo_test                                   PASSED in 4.6s
//pkg/sql/catalog/descs:descs_test                                       PASSED in 6.0s
//pkg/sql/catalog/hydratedtables:hydratedtables_test                     PASSED in 3.6s
//pkg/sql/catalog/schemadesc:schemadesc_test                             PASSED in 8.3s
//pkg/sql/catalog/tabledesc:tabledesc_test                               PASSED in 9.9s
//pkg/sql/catalog/typedesc:typedesc_test                                 PASSED in 6.0s
//pkg/sql/colexec/colbuilder:colbuilder_test                             PASSED in 9.9s
//pkg/sql/colexec/execgen:execgen_test                                   PASSED in 1.4s
//pkg/sql/colflow:colflow_test                                           PASSED in 12.4s
//pkg/sql/colmem:colmem_test                                             PASSED in 3.3s
//pkg/sql/covering:covering_test                                         PASSED in 2.4s
//pkg/sql/distsql:distsql_test                                           PASSED in 9.1s
//pkg/sql/doctor:doctor_test                                             PASSED in 4.5s
//pkg/sql/execinfra:execinfra_test                                       PASSED in 5.4s
//pkg/sql/execinfrapb:execinfrapb_test                                   PASSED in 5.9s
//pkg/sql/execstats:execstats_test                                       PASSED in 4.0s
//pkg/sql/flowinfra:flowinfra_test                                       PASSED in 27.8s
//pkg/sql/gcjob:gcjob_test                                               PASSED in 3.3s
//pkg/sql/gcjob_test:gcjob_test_test                                     PASSED in 20.1s
//pkg/sql/lex:lex_test                                                   PASSED in 5.4s
//pkg/sql/mutations:mutations_test                                       PASSED in 2.2s
//pkg/sql/opt:opt_test                                                   PASSED in 2.2s
//pkg/sql/opt/bench:bench_test                                           PASSED in 10.7s
//pkg/sql/opt/cat:cat_test                                               PASSED in 3.9s
//pkg/sql/opt/constraint:constraint_test                                 PASSED in 8.0s
//pkg/sql/opt/invertedexpr:invertedexpr_test                             PASSED in 3.7s
//pkg/sql/opt/opbench:opbench_test                                       PASSED in 5.2s
//pkg/sql/opt/optgen/cmd/optgen:optgen_test                              PASSED in 6.5s
//pkg/sql/opt/optgen/exprgen:exprgen_test                                PASSED in 6.6s
//pkg/sql/opt/optgen/lang:lang_test                                      PASSED in 5.5s
//pkg/sql/opt/partialidx:partialidx_test                                 PASSED in 2.4s
//pkg/sql/opt/testutils:testutils_test                                   PASSED in 3.3s
//pkg/sql/opt/testutils/opttester:opttester_test                         PASSED in 3.3s
//pkg/sql/opt/testutils/testcat:testcat_test                             PASSED in 5.2s
//pkg/sql/pgwire/pgerror:pgerror_test                                    PASSED in 3.6s
//pkg/sql/physicalplan:physicalplan_test                                 PASSED in 18.1s
//pkg/sql/physicalplan/replicaoracle:replicaoracle_test                  PASSED in 5.3s
//pkg/sql/protoreflect:protoreflect_test                                 PASSED in 3.5s
//pkg/sql/row:row_test                                                   PASSED in 8.9s
//pkg/sql/rowenc:rowenc_test                                             PASSED in 17.4s
//pkg/sql/rowexec:rowexec_test                                           PASSED in 19.4s
//pkg/sql/schemachange:schemachange_test                                 PASSED in 13.6s
//pkg/sql/schemachanger/scbuild:scbuild_test                             PASSED in 7.2s
//pkg/sql/schemachanger/scexec:scexec_test                               PASSED in 6.8s
//pkg/sql/sessiondata:sessiondata_test                                   PASSED in 9.5s
//pkg/sql/sqlliveness/slinstance:slinstance_test                         PASSED in 3.2s
//pkg/sql/sqlliveness/slstorage:slstorage_test                           PASSED in 6.8s
//pkg/sql/stmtdiagnostics:stmtdiagnostics_test                           PASSED in 11.7s
//pkg/sql/types:types_test                                               PASSED in 6.7s
//pkg/sqlmigrations:sqlmigrations_test                                   PASSED in 7.9s
//pkg/sqlmigrations/leasemanager:leasemanager_test                       PASSED in 6.7s
//pkg/storage/cloudimpl/cloudimpltests:cloudimpltests_test               PASSED in 12.0s
//pkg/storage/cloudimpl/filetable/filetabletest:filetabletest_test       PASSED in 22.2s
//pkg/storage/enginepb:enginepb_test                                     PASSED in 6.1s
//pkg/testutils:testutils_test                                           PASSED in 3.7s
//pkg/testutils/keysutils:keysutils_test                                 PASSED in 5.7s
//pkg/testutils/reduce/reducesql:reducesql_test                          PASSED in 7.6s
//pkg/testutils/sqlutils:sqlutils_test                                   PASSED in 10.2s
//pkg/testutils/testcluster:testcluster_test                             PASSED in 28.3s
//pkg/testutils/zerofields:zerofields_test                               PASSED in 1.9s
//pkg/ts:ts_test                                                         PASSED in 17.2s
//pkg/util/binfetcher:binfetcher_test                                    PASSED in 7.5s
//pkg/util/bitarray:bitarray_test                                        PASSED in 0.7s
//pkg/util/cache:cache_test                                              PASSED in 4.0s
//pkg/util/cloudinfo:cloudinfo_test                                      PASSED in 1.7s
//pkg/util/contextutil:contextutil_test                                  PASSED in 1.3s
//pkg/util/duration:duration_test                                        PASSED in 4.4s
//pkg/util/encoding/csv:csv_test                                         PASSED in 4.3s
//pkg/util/envutil:envutil_test                                          PASSED in 6.9s
//pkg/util/errorutil:errorutil_test                                      PASSED in 6.5s
//pkg/util/humanizeutil:humanizeutil_test                                PASSED in 2.9s
//pkg/util/log/eventpb:eventpb_test                                      PASSED in 1.8s
//pkg/util/log/logcrash:logcrash_test                                    PASSED in 6.1s
//pkg/util/metric:metric_test                                            PASSED in 6.5s
//pkg/util/optional:optional_test                                        PASSED in 1.4s
//pkg/util/pretty:pretty_test                                            PASSED in 1.8s
//pkg/util/quotapool:quotapool_test                                      PASSED in 5.2s
//pkg/util/randutil:randutil_test                                        PASSED in 3.0s
//pkg/util/search:search_test                                            PASSED in 1.9s
//pkg/util/span:span_test                                                PASSED in 1.5s
//pkg/util/stringarena:stringarena_test                                  PASSED in 6.6s
//pkg/util/sysutil:sysutil_test                                          PASSED in 3.4s
//pkg/util/timeofday:timeofday_test                                      PASSED in 5.7s
//pkg/util/timeutil:timeutil_test                                        PASSED in 10.9s
//pkg/util/timeutil/pgdate:pgdate_test                                   PASSED in 7.7s
//pkg/util/tracing:tracing_test                                          PASSED in 4.5s
//pkg/util/treeprinter:treeprinter_test                                  PASSED in 3.2s
//pkg/util/uint128:uint128_test                                          PASSED in 3.4s
//pkg/util/uuid:uuid_test                                                PASSED in 5.8s
//pkg/workload:workload_test                                             PASSED in 9.3s
//pkg/workload/bank:bank_test                                            PASSED in 7.1s
//pkg/workload/cli:cli_test                                              PASSED in 5.3s
//pkg/workload/movr:movr_test                                            PASSED in 2.3s
//pkg/workload/workloadsql:workloadsql_test                              PASSED in 6.5s
//pkg/internal/codeowners:codeowners_test                                FAILED in 2.1s
//pkg/internal/team:team_test                                            FAILED in 0.3s
```

---

I'd also prefer if we could move /pkg/BUILD.bazel into /build instead, alongside STRINGER. I think it's a better home for it. Maybe it's time for us to create a new directory altogether to house all these cross package bazel utilities.

**Comment by otan** [comment]
This is pretty nifty.

From experience, I think small should be < 30s, medium < 2mins, large < 5mins, especially if we're integration test heavy (we are from SQL experience :P) 

Agree that ALL_TESTS will get quite old, and it'd be preferrable if we could use `bazel query` to find these.

**Comment by irfansharif** [comment]
Some more timing info, and another broken test, if that helps us categorize package sizes better (I don't really have any opinions on what the sizes should be, as long as we have a rough heuristic spelled out somewhere).

```
# medium tests
//pkg/ccl/storageccl:storageccl_test                                     PASSED in 272.9s
//pkg/ccl/workloadccl/allccl:allccl_test                                 PASSED in 102.6s
//pkg/jobs:jobs_test                                                     PASSED in 35.6s
//pkg/kv/kvclient/kvcoord:kvcoord_test                                   PASSED in 57.9s
//pkg/kv/kvserver/concurrency:concurrency_test                           PASSED in 172.3s
//pkg/kv/kvserver/spanlatch:spanlatch_test                               PASSED in 126.6s
//pkg/sql/catalog/lease:lease_test                                       PASSED in 18.1s
//pkg/sql/colexec:colexec_test                                           PASSED in 98.4s
//pkg/sql/stats:stats_test                                               PASSED in 24.7s
//pkg/sql/tests:tests_test                                               PASSED in 58.8s
//pkg/util/interval/generic:generic_test                                 PASSED in 127.6s
//pkg/workload/ycsb:ycsb_test                                            PASSED in 82.0s
//pkg/ccl/importccl:importccl_test                                       PASSED in 31.2s
//pkg/kv/kvserver:kvserver_test                                          PASSED in 214.9s
//pkg/server:server_test                                                 FAILED in 2 out of 16 in 300.2s

# large tests
//pkg/ccl/backupccl:backupccl_test                                       PASSED in 260.8s
```

**Review by irfansharif — COMMENTED** [review]
Also, the `go_test` doc doesn't really have this "size" guy listed: https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-test. And we're using tags to filter them? I'm guessing the "size" guy feeds into https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests. Does it also inherit those timeouts by default? (1m, 5m, 15m, 60m for short-enormous.) Is that what we want?

Again, nothing worth holding this PR up over, but I wouldn't mind just using tags manually (though I don't know how what would take precedence if we used the same labels, the "size" or the "tag" - maybe we side step everything and use t-shirt sizes instead), or just making sure we're somehow controlling the test timeouts explicitly at some future point. Worth just adding a comment I think, cause I'm confused about how this works.

**Comment by rickystewart** [comment]
I took another pass through the list using your timing info and tried to categorize the sizes a little more accurately. There are fewer `small` tests and more `medium`/`large` ones now.

> I'd also prefer if we could move /pkg/BUILD.bazel into /build instead, alongside STRINGER.

As we discussed in Slack, I like this because `pkg` is where EVERYTHING lives, so `pkg:small_tests` will run everything you expect it to (i.e., all the small tests in `pkg`).

I'm not opposed to moving this stuff around in the future, maybe we can take some time to deliberate on it before committing to anything new.

> I'll not gate this PR, but it'd be worth following up on using bazel query 'kind(go_test, //pkg/...)' instead, which programatically gives us what we need. 

This is how I enumerated the tests for this PR :) You can't just inject `query` results into a `BUILD` file, which is why the list is hard-coded now, but I was going to take a TODO to follow up on this with a lint. That's pointed out in the `BUILD` file now.

> And we're using tags to filter them?

Yes: ["Note that a test's size is considered a tag for the purpose of filtering."](https://docs.bazel.build/versions/master/be/general.html#test_suite) This is just normal Bazel stuff, I'm not doing anything weird here.

> Does it also inherit those timeouts by default? (1m, 5m, 15m, 60m for short-enormous.)

Yes.

> Is that what we want?

I've attempted to select test sizes such that the timeouts make sense (i.e., you're not going to realistically time out unless you're on a hugely slow machine). We can also configure the timeouts ourselves if that's what we want, but this starting place is as good as anywhere else AFAIC. If we want to move to something else we can take the time to deliberate over it.

**Pull request merged**
