### PR TITLE
util/log: new experimental integration with Fluentd 

### PR DESCRIPTION
**Pull request by knz**
Release note (cli change): It is now possible to redirect logging to
[Fluentd](https://www.fluentd.org)-compatible network collectors. See
the documentation for details. This is an alpha-quality feature.

### CODE REVIEW

**Comment by knz** [comment]
rebased, PTAL

**Review by itsbilal — COMMENTED** [review]
Mostly looks good to me, one comment about JSON serialization.

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57170#-:-MNe4yR14ODjDTfoVL4I:b-p1dpy5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/format_json.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57170#-MNe4CpL4Z64MgMh1bE4:-MNe4CpM4nGL8d0qRCr1:b404l1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a99b80cb02494d4b0c418c4403d7378a85813fbc/pkg/util/log/format_json.go#L88)):*
> ```Go
> }()
> 
> func formatJSON(entry logpb.Entry, stacks []byte, forFluent, compact bool) *buffer {
> ```

This seems like a lot of manual legwork just to serialize an object into json. Was `json.Marshal` on a custom struct not good here?
___
*[pkg/util/log/logconfig/config.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57170#-MNe4rSXDy640SuVamsg:-MNe4rSXDy640SuVamsh:b-4g0c1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a99b80cb02494d4b0c418c4403d7378a85813fbc/pkg/util/log/logconfig/config.go#L207)):*
> ```Go
> 	CommonSinkConfig `yaml:",inline"`
> 
> 	// used during validation.
> ```

Nit: First word should be capitalized.

**Review by knz — COMMENTED** [review]
rebased; now also with unit test. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57170#-:-MSETtUZ7h6XI0XKvDbL:b-kpyx86)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/util/log/logconfig/config.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57170#-MNe4rSXDy640SuVamsg:-MSE6dU3BDnz08HxgkMg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a99b80cb02494d4b0c418c4403d7378a85813fbc/pkg/util/log/logconfig/config.go#L207)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nit: First word should be capitalized.
</blockquote></details>

Done.

**Comment by knz** [comment]
Flaked on  #59644 which is unrelated.

**Comment by knz** [comment]
friendly ping

**Review by itsbilal — APPROVED** [review]
:lgtm: Sorry for the late review!

> Reviewed 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57170#-:-MScX0JyEOwFbyZ1S3ZX:b-3kotvd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
Thank you!

bors r=itsbilal

**Pull request merged**
