### PR TITLE
sql/sem/tree: teach JSON how to pretty print itself

### PR DESCRIPTION
**Pull request by madelynnblue**
For cast and annotate expressions, if the LHS is a string and the RHS
is JSON, pretty print the JSON since we know it's still valid.

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
If this is just the most ridiculous thing then please consider it a joke and I'll just close this PR and maintain it forever on my own.

**Comment by knz** [comment]
I like it! :sparkling_heart: 
LGTM

**Comment by mjibson** [comment]
Current problem: there's a thing that verifies statements don't change as a test that sqlfmt doesn't mess anything up. This change modifies the actual strings which causes that thing to fail the tests (correctly). It's not obvious how to work around this because munging people's strings is inherently a weird thing. Like this PR pretty neatly breaks through it's layer of abstraction into the next one, breaking assumptions.

Possible fixes:

1. Just close this PR.
2. Add a JSON-mode to the PrettyCfg type that enables this behavior, it would be enabled probably only by the sqlfmt website. In order to ensure its correctness (i.e., that it's not incorrectly formatting the JSON) a new test will be added that generates random JSON datums and ensures datum equivalency before and after this pretty printing.

Thoughts?

**Review by knz — COMMENTED** [review]
I'm sorry I don't get it; can you point me to the part of the code which causes in-place modification of the strings?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43392#-:-LxcQLchDb3GCX4UBOtX:b-ibbl9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by mjibson** [comment]
See the tests added in this PR for example. The initial string is on a single line, the formatted string has had newlines and tabs added to it.

**Review by knz — COMMENTED** [review]
Oh I see it now. It's not that it modifies the strings, it's just that the new default pretty-printer configuration does not roundtrip the canonical printout using Format(). But the strings remain equivalent :)

Let's see. First things first, I would be grateful if you could apply the following patch in the code to clarify what is going on:
```diff
--- a/pkg/testutils/sqlutils/pretty.go
+++ b/pkg/testutils/sqlutils/pretty.go
@@ -30,6 +30,40 @@ func VerifyStatementPrettyRoundtrip(t *testing.T, sql string) {
        // Be careful to not simplify otherwise the tests won't round trip.
        cfg.Simplify = false
        for i := range stmts {
+               // Dataflow of the statement through these checks:
+               //
+               //             sql (from test file)
+               //              |
+               //          (parser.Parse)
+               //              v
+               //           origStmt
+               //          /         \
+               //    (cfg.Pretty)    (AsStringWithFlags,FmtParsable)
+               //       v                          |
+               //    prettyStmt                    |
+               //       |                          |
+               // (parser.ParseOne)                |
+               //       v                          |
+               //   parsedPretty                   |
+               //       |                          |
+               // (AsStringWithFlags,FmtSimple)    |
+               //       v                          v
+               //   prettyFormatted          origFormatted
+               //
+               // == Check 1: prettyFormatted == origFormatted
+               // If false:
+               //
+               //       |                          |
+               //       |                   (parser.ParseOne)
+               //       |                          v
+               //       |                    reparsedStmt
+               //       |                          |
+               //       |                 (AsStringWithFlags,FmtParsable)
+               //       v                          v
+               //   prettyFormatted           origFormatted
+               //
+               // == Check 2: prettyFormatted == origFormatted
+               //
                origStmt := stmts[i].AST
                // Be careful to not simplify otherwise the tests won't round trip.
                prettyStmt := cfg.Pretty(origStmt)
```

From there there are two solutions. Either you can make `origFormatted` contain the spaces; or you can make `prettyFormatted` remove the spaces again.

I think it would be a mistake to add the overhead of introducing spaces in `AsStringWithFlags`, which is the common case where no humans are looking at the output (not to talk about the extra memory usage). Therefore the logical choice (to me) is to add a pretty configuration option to do the JSON thing, then either:

1) add the option as default into `DefaultPrettyCfg`, but then remove it in `VerifyStatementPrettyRoundtrip`

or

2) add the option as opt-in (non-default) in `DefaultPrettyCfg`, then modify `cli/sqlmft.go` and sqlfm.pt to add it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43392#-:-LxcSf_V9F4Vrn90yAVH:bbapn5p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by mjibson** [comment]
I think option 2 is the best since this is kind of a weird feature and should be opt in. However it saddens me that we have to disable this in tests, when I want tests for exactly this kind of thing, since it would be easy to accidentally produce bad JSON (like an earlier version of this PR did).

**Comment by knz** [comment]
You could still have it in tests, but with a fallback (if the comparison fails, try again with json formatting disabled).

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43392#-:-LxkbR8U2QunhkmEp5R5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
