### PR TITLE
sql/schemachanger: move column compute expression to separate DSC element

### PR DESCRIPTION
**Pull request by spilchen**
Previously, the column compute expression was part of the ColumnType element, which made it difficult to change the compute expression without affecting the other fields in ColumnType. To address this, especially for the upcoming work on adding a temporary compute expression during column type changes that require a backfill (in #127014), we’re moving the compute expression into its own separate element, similar to how default expressions (ColumnDefaultExpression) and ON UPDATE expressions (ColumnOnUpdateExpression) are handled.

Key points to note about this change:
- Version Gate: The new element must be protected by a version gate. For older versions, we’ll continue using the old compute expression field in ColumnType. There was one instance where the current cluster version wasn’t accessible, so I added a field in ElementCreationMetadata to track if the ColumnType was created in 24.3. This acts as the version gate.
- IsVirtual Attribute: Although logically, the IsVirtual attribute should belong to ColumnComputeExpression, I left it in ColumnType. During the ADD COLUMN process, we set up the column family for the new column only if it’s not virtual. Moving IsVirtual to ColumnComputeExpression would require a dependency rule to ensure the ColumnComputeExpression is applied before ColumnType to set up the column family correctly.
- Dropping a Compute Column: When dropping a computed column, I leave a NULL expression in the column descriptor. If the expression is removed entirely, it triggers validation logic that a virtual column must have a compute expression. We will need to revisit this, especially for the ALTER TABLE .. TYPE use case and future support for ALTER TABLE .. DROP EXPRESSION.

Epic: CRDB-25314
Informs: #127014
Release note: None

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
This looks great, just some minor stuff. We also should update scpb.MigrateDescriptorState to convert elements to the new one, after the version gate is active.

> Reviewed 104 of 104 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-:-O4GJRMR5c_z2FXIXr6b:b-g5nl6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-O4GA-3n73ljIupv154T:-O4GA-3n73ljIupv154U:b48hyaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e5f916fe9f0443544e837b4ba07a85572fb7aa2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L179)):*
> ```Go
> 	if desc.IsComputed() {
> 		expr := b.WrapExpression(tbl.TableID, b.ComputedColumnExpression(tbl, d))
> 		if spec.colType.ElementCreationMetadata.In_24_3OrLater {
> ```

In the builder I think we can just do: b.EvalCtx().Settings.Version.ActiveVersion()
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go` line 856 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-O4GAqto42dy16PIsEVS:-O4GAqto42dy16PIsEVT:bl7zs95) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e5f916fe9f0443544e837b4ba07a85572fb7aa2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L856)):*
> ```Go
> 	scpb.ForEachColumnType(elts, func(current scpb.Status, target scpb.TargetStatus, e *scpb.ColumnType) {
> 		column := mustRetrieveColumnElem(b, e.TableID, e.ColumnID)
> 		computeExpr := retrieveColumnComputeExpression(b, e.TableID, e.ColumnID)
> ```

Nit: Would it be a bit cleaner to always use the new element internally, and convert to the ColumnExpression element

**Comment by annrpom** [comment]
> We also should update scpb.MigrateDescriptorState to convert elements to the new one, after the version gate is active.

@fqazi Should we also have done this for zone configs in the DSC? Is this needed everytime we modify an existing element?

**Review by fqazi — COMMENTED** [review]
@annrpom I think your safe for zone configs because we didn't support any schema changes with them. This is more about making sure we can re-plan for restore or paused state

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-:-O4GQ4An33LeVB7GZ1Sj:bwjy59w)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @spilchen)

**Comment by annrpom** [comment]
> This is more about making sure we can re-plan for restore or paused state

@fqazi ahh ok that makes sense -- ty! (sorry for the PR noise, Matt!)

**Review by spilchen — COMMENTED** [review]
Thanks for taking a look @fqazi. I addressed/replied to your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-:-O4H7nyb5f_n4m97x_x3:boo5gsy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @mgartner)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-O4GA-3n73ljIupv154T:-O4H1vzqDuR-KF3dx2aL:bgljw5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e5f916fe9f0443544e837b4ba07a85572fb7aa2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L179)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

In the builder I think we can just do: b.EvalCtx().Settings.Version.ActiveVersion()
</blockquote></details>

I did try this in an earlier iteration, but I ran into an issue where I couldn't find the current version in one codepath. Specifically, in `pkg/sql/schemachanger/scexec/scmutationexec/column.go`, I need to check the compute expression in `addNewColumnType`. Do you have any suggestions on how to get the current active version there? I wasn’t too keen on using `ElementCreationMetadata`, but it seemed like the only option.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go` line 856 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-O4GAqto42dy16PIsEVS:-O4H3OWq1ZArLlFTEcEd:b-ovwaw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e5f916fe9f0443544e837b4ba07a85572fb7aa2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L856)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Would it be a bit cleaner to always use the new element internally, and convert to the ColumnExpression element
</blockquote></details>

Good idea.

**Review by spilchen — COMMENTED** [review]
@fqazi I addressed the final comment you had about migration. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-:-O4L90oX0iP4DnI5Z_AB:b-nc4m7i)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @mgartner)

**Review by fqazi — APPROVED** [review]
This looks great :lgtm_strong:  

> Reviewed 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-:-O4HG_0123WHTLWmjC8u:bridis)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128892#-O4GA-3n73ljIupv154T:-O4HFrh27v0IXZW2gqh6:b-kxnjbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e5f916fe9f0443544e837b4ba07a85572fb7aa2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L179)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I did try this in an earlier iteration, but I ran into an issue where I couldn't find the current version in one codepath. Specifically, in `pkg/sql/schemachanger/scexec/scmutationexec/column.go`, I need to check the compute expression in `addNewColumnType`. Do you have any suggestions on how to get the current active version there? I wasn’t too keen on using `ElementCreationMetadata`, but it seemed like the only option.
</blockquote></details>


Ah this makes, sense. Lets keep the version checks as-is since we need them on the execution side.

**Pull request merged**
