### PR TITLE
sql: Add information_schema.views

### PR DESCRIPTION
**Pull request by szpony**
Add information_schema.views. 
Pls refer to  #8675

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10288)

### CODE REVIEW

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 434 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVB3-YcMPpnrN706kts:-KVB3-YcMPpnrN706ktt:b-i5uvm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b157607163f9f383a685b749e05e5e185bd71fc2/pkg/sql/information_schema.go#L434)):*
> ```Go
> 					parser.NewDString(db.Name),         // table_schema
> 					parser.NewDString(table.Name),      // table_name
> 					parser.NewDString(table.ViewQuery), // view_definition
> ```

You may want to include a disclaimer/TODO about the view query printed here (as I've done in #10276) about how this won't properly insert column aliases into the query

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288)*

**Comment by yznming** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 434 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVB3-YcMPpnrN706kts:-KVFFdGe7nY6xJW_TXPN:bl00v8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b157607163f9f383a685b749e05e5e185bd71fc2/pkg/sql/information_schema.go#L434)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> You may want to include a disclaimer/TODO about the view query printed here (as I've done in #10276) about how this won't properly insert column aliases into the query
</details>
done. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288)*

**Comment by mtMabo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 434 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVB3-YcMPpnrN706kts:-KVFFdGe7nY6xJW_TXPN:bl00v8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b157607163f9f383a685b749e05e5e185bd71fc2/pkg/sql/information_schema.go#L434)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> You may want to include a disclaimer/TODO about the view query printed here (as I've done in #10276) about how this won't properly insert column aliases into the query
</details>
done. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288)*

**Comment by nvanbenschoten** [comment]
:lgtm: other than the small nits. Thanks @mtMabo!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/information_schema.go, line 434 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVB3-YcMPpnrN706kts:-KVO9x0BYBvgvfVKzUTQ:b-4q2ev2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b157607163f9f383a685b749e05e5e185bd71fc2/pkg/sql/information_schema.go#L434)):*
<details><summary><i>Previously, mtMabo (MaBo) wrote…</i></summary>
> done. Thanks
</details>
`s/TODO/TODO(a-robinson)/` so that this doesnt get lost.

---

*[pkg/sql/testdata/information_schema, line 675 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVOA9Gp3PgppUbPFQsp:-KVOA9Gp3PgppUbPFQsq:b-ok9h7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cc126ba5804b2e9b616362764f670d773575b8c/pkg/sql/testdata/information_schema#L675)):*
> ```
> 
> query TTTTTBBBBB colnames
> SELECT * FROM information_schema.views WHERE TABLE_NAME='v_xyz'; 
> ```

Let's split this into two queries so it's a little more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-:-KVOAHdgNS-jvnPxqUod:b-xy01gk)*

**Comment by mtMabo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/information_schema, line 675 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVOA9Gp3PgppUbPFQsp:-KVOQn1BlRalz-eOHVns:bxpszoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cc126ba5804b2e9b616362764f670d773575b8c/pkg/sql/testdata/information_schema#L675)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Let's split this into two queries so it's a little more readable.
</details>
What do you mean  "split this into two queries so it's a little more readable" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/information_schema, line 675 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVOA9Gp3PgppUbPFQsp:-KVRL274r8qB3Xl3HD6j:b2x1jpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cc126ba5804b2e9b616362764f670d773575b8c/pkg/sql/testdata/information_schema#L675)):*
<details><summary><i>Previously, mtMabo (MaBo) wrote…</i></summary>
> What do you mean  "split this into two queries so it's a little more readable" ?
</details>
Instead of `SELECT *`, select from 5 columns each in two queries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288)*

**Comment by mtMabo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/information_schema.go, line 434 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVB3-YcMPpnrN706kts:-KVUQTi5iexYMV8I4w6D:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b157607163f9f383a685b749e05e5e185bd71fc2/pkg/sql/information_schema.go#L434)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/TODO/TODO(a-robinson)/` so that this doesnt get lost.
</details>
Done. 

---

*[pkg/sql/testdata/information_schema, line 675 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288#-KVOA9Gp3PgppUbPFQsp:-KVUQevX_6aGJzoth99d:bnputky) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cc126ba5804b2e9b616362764f670d773575b8c/pkg/sql/testdata/information_schema#L675)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Instead of `SELECT *`, select from 5 columns each in two queries.
</details>
Done. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10288)*

**Pull request merged**
