### PR TITLE
sql/catalog/dbdesc: repair old descriptors corrupted due to DROPPED SCHEMA name

### LINKED ISSUE #63148: sql: repair corruption due to DROP SCHEMA bug
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/63119 we uncovered a typo bug that then causes corruption when you have schemas of the same name as the database. Fortunately we can repair this type of corruption pretty trivially. We should do this as a read-time repair and then we should write a long-running migration.

### PR DESCRIPTION
**Pull request by sajjadrizvi**
#63119 fixes a bug that corrupts a database descriptor when a child schema was 
dropped, adding an entry in schema-info structure erroneously with database name
instead of schema name . Although the bug was fixed , there can be database backups 
with corrupted descriptors.

This commit adds a post-deserialization function to repair a corrupted descriptor. Moreover,
it adds a test function to ensure that descriptors with such corruption are fixed during
migration.
 
Release note: None
 
Fixes: #63148

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: mod naming and commentary nits

> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68738#-:-Mgzfvwv4wReH2GtQR-P:bsthx31)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nihalpednekar and @sajjadrizvi)

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68738#-MgzgCQ4B7-MnG81So1J:-MgzgCQ4B7-MnG81So1K:b-kg7ajf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b755771b99837371fba95938758cd3811b56adb1/pkg/sql/catalog/dbdesc/database_desc.go#L441)):*
> ```
> // maybeFixDroppedSchemaName fixes the name of a dropped child schema in a
> // database descriptor.
> ```
This first sentence is too vague and might lead somebody to believe it's a very general function. How about: 

```go
// maybeRemoveDroppedSelfEntryFromSchemas removes an entry in the Schemas map corresponding to the
// database itself which was added due to a bug in prior versions when dropping any user-defined schema. 
// The bug inserted an entry for the database rather than the schema being dropped. This function fixes the
// problem by deleting the erroneous entry.
func maybeRemoveDroppedSelfEntryFromSchemas(dbDesc *descpb.DatabaseDescriptor) bool {
```
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68738#-MgzgyBP7tO6TKtFpe75:-MgzgyBP7tO6TKtFpe76:b-dsrrjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b755771b99837371fba95938758cd3811b56adb1/pkg/sql/catalog/dbdesc/database_desc.go#L452)):*
> ```Go
> 	}
> 	if sc, ok := dbDesc.Schemas[dbDesc.Name]; ok {
> 		if sc.Dropped && sc.ID == dbDesc.ID {
> ```

I don't think the `Dropped` check is necessary. The database should never think of itself as a schema inside of itself. 
___
*[pkg/sql/catalog/dbdesc/database_desc_builder.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68738#-Mgzfzml5wVXP2zd0cM4:-Mgzfzmm4NX5N02s4NeF:bwkpkng) ([raw file](https://github.com/cockroachdb/cockroach/blob/b755771b99837371fba95938758cd3811b56adb1/pkg/sql/catalog/dbdesc/database_desc_builder.go#L63)):*
> ```Go
> 	privsChanged := descpb.MaybeFixPrivileges(ddb.maybeModified.ID, ddb.maybeModified.ID,
> 		&ddb.maybeModified.Privileges, privilege.Database)
> 	nameChanged := maybeFixDroppedSchemaName(ddb.maybeModified)
> ```

`nameChanged` is a surprising name for this variable. The name of the descriptor did not change. Can you change it to something more descriptive like `re

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68738)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nihalpednekar and @sajjadrizvi)

___
*[pkg/sql/catalog/dbdesc/database_desc_builder.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68738#-Mgzfzml5wVXP2zd0cM4:-MgzhFBI-6CjLjYiOFNu:b9jqbz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b755771b99837371fba95938758cd3811b56adb1/pkg/sql/catalog/dbdesc/database_desc_builder.go#L63)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`nameChanged` is a surprising name for this variable. The name of the descriptor did not change. Can you change it to something more descriptive like `re
</blockquote></details>

heh didn't finish that. `removedSelfEntryInSchemas`?

**Review by sajjadrizvi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68738)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nihalpednekar)

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68738#-MgzgCQ4B7-MnG81So1J:-Mh-3ri0B23_Ehx70h3T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b755771b99837371fba95938758cd3811b56adb1/pkg/sql/catalog/dbdesc/database_desc.go#L441)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // maybeFixDroppedSchemaName fixes the name of a dropped child schema in a
> // database descriptor.
> ```
This first sentence is too vague and might lead somebody to believe it's a very general function. How about: 

```go
// maybeRemoveDroppedSelfEntryFromSchemas removes an entry in the Schemas map corresponding to the
// database itself which was added due to a bug in prior versions when dropping any user-defined schema. 
// The bug inserted an entry for the database rather than the schema being dropped. This function fixes the
// problem by deleting the erroneous entry.
func maybeRemoveDroppedSelfEntryFromSchemas(dbDesc *descpb.DatabaseDescriptor) bool {
```
</blockquote></details>

Done.

**Comment by sajjadrizvi** [comment]
TFTR!

r=ajwerner

**Comment by sajjadrizvi** [comment]
bors r=ajwerner

**Pull request merged**
