### PR TITLE
backupccl: remove type backreferences on failed restores

### LINKED ISSUE #53338: backupccl: failed restores need to remove backreferences from existing types
When restoring a backup that maps type references to existing types, we need to remove those installed backreferences if the restore fails.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #53338.

Teach `RESTORE` to clean up backreferences from existing types to
restored tables when a `RESTORE` fails.

Release note: None

Release justification: bug fixes and low-risk updates to new
functionality

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53420)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, @pbardea, and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 1657 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53420#-MFaR-K373oIHP0O0M8d:-MFaR-K373oIHP0O0M8e:b-qbgw71) ([raw file](https://github.com/cockroachdb/cockroach/blob/47243f809d9d64d607302ef7db13b4c000114ebb/pkg/ccl/backupccl/backup_test.go#L1657)):*
> ```Go
> }
> 
> func TestRestoreFailCleansUpTypeBackReferences(t *testing.T) {
> ```

Can this test be an added assertion in `TestRestoreFailCleanup`?
___
*[pkg/ccl/backupccl/restore_job.go, line 1368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53420#-MFaQh7-A0pYOCD3Rds-:-MFaQh7-A0pYOCD3Rds0:b-6xktaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/47243f809d9d64d607302ef7db13b4c000114ebb/pkg/ccl/backupccl/restore_job.go#L1368)):*
> ```Go
> 	// We first collect the restored types to be addressable by ID.
> 	restoredTypes := make(map[descpb.ID]*typedesc.Immutable)
> 	existingTypes := make(map[descpb.ID]*typedesc.Mutable)
> ```

This method is ballooning quite a bit... maybe we can move the below logic to a helper that gives us back `existingTypes`? Ideally, we'd just have something like `revertTypeChanges` and similar for all of the reverts we do below, but we don't need that for this change.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53420)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 1657 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53420#-MFaR-K373oIHP0O0M8d:-MFaWB5763QQTw_ZmaEy:bqm7yrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/47243f809d9d64d607302ef7db13b4c000114ebb/pkg/ccl/backupccl/backup_test.go#L1657)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can this test be an added assertion in `TestRestoreFailCleanup`?
</blockquote></details>

I tried but it's a bit awkward due to TestRestoreFailCleanup restoring a whole database vs this needing to restore just a table.
___
*[pkg/ccl/backupccl/restore_job.go, line 1368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53420#-MFaQh7-A0pYOCD3Rds-:-MFaWHVk5fJVRLPqklAC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47243f809d9d64d607302ef7db13b4c000114ebb/pkg/ccl/backupccl/restore_job.go#L1368)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

This method is ballooning quite a bit... maybe we can move the below logic to a helper that gives us back `existingTypes`? Ideally, we'd just have something like `revertTypeChanges` and similar for all of the reverts we do below, but we don't need that for this change.
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53420)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

**Comment by rohany** [comment]
I want @lucy-zhang or @ajwerner to take a look as well before I merge this

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53420)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Pull request merged**
