### PR TITLE
opt: use constraint primitives for idxconstraint

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt/idxconstraint: benchmarks with single long span

Adding two benchmarks that show the scaling when we have many columns,
but just one span.

#### opt: use constraint primitives for idxconstraint

This change reworks the index constraints code to use the new
primitives in `opt/constraint`.

Notable changes:
 - IndexColumnInfo now uses OrderingColumn instead of separate index
   and direction.
 - more efficient Columns.Equals implementation.
 - more efficient initializers for Span, Spans and Constraint. In
   particular, Span.Init no longer checks that the keys are in the
   expected order (this had a not-insignificant cost).
 - during filter simplification, instead of using CutFirstColumn and
   SubsetOf, we now generate the cut spans one at a time and use
   ContainsSpan. This is more efficient (we don't need to copy spans)
   and the necessary primitive is simpler.

Benchmark results:
```
name                                      old time/op    new time/op    delta
IndexConstraints/point-lookup-8              361ns ± 0%     288ns ± 2%   -20.25%  (p=0.000 n=8+10)
IndexConstraints/no-constraints-8            146ns ± 0%     171ns ± 4%   +17.06%  (p=0.000 n=9+10)
IndexConstraints/range-8                    1.67µs ± 1%    1.57µs ± 1%    -5.86%  (p=0.000 n=9+10)
IndexConstraints/range-2d-8                 2.86µs ± 3%    3.04µs ± 1%    +6.48%  (p=0.000 n=10+9)
IndexConstraints/many-columns-8             5.13µs ± 2%    6.05µs ± 2%   +18.04%  (p=0.000 n=9+10)
IndexConstraints/single-jumbo-span-10-8     16.5µs ± 2%    20.1µs ± 0%   +21.24%  (p=0.000 n=10+8)
IndexConstraints/single-jumbo-span-100-8     824µs ± 2%    1102µs ± 1%   +33.79%  (p=0.000 n=9+10)

name                                      old alloc/op   new alloc/op   delta
IndexConstraints/point-lookup-8               224B ± 0%       52B ± 0%   -76.79%  (p=0.000 n=10+10)
IndexConstraints/no-constraints-8             128B ± 0%       52B ± 0%   -59.38%  (p=0.000 n=10+10)
IndexConstraints/range-8                      584B ± 0%       64B ± 0%   -89.04%  (p=0.000 n=10+10)
IndexConstraints/range-2d-8                   912B ± 0%      136B ± 0%   -85.09%  (p=0.000 n=10+10)
IndexConstraints/many-columns-8             1.75kB ± 0%    0.89kB ± 0%   -49.32%  (p=0.000 n=10+10)
IndexConstraints/single-jumbo-span-10-8     4.88kB ± 0%    1.95kB ± 0%   -60.00%  (p=0.000 n=10+10)
IndexConstraints/single-jumbo-span-100-8     201kB ± 0%     171kB ± 0%   -14.79%  (p=0.000 n=10+10)

name                                      old allocs/op  new allocs/op  delta
IndexConstraints/point-lookup-8               4.00 ± 0%      2.00 ± 0%   -50.00%  (p=0.000 n=10+10)
IndexConstraints/no-constraints-8             1.00 ± 0%      2.00 ± 0%  +100.00%  (p=0.000 n=10+10)
IndexConstraints/range-8                      16.0 ± 0%       3.0 ± 0%   -81.25%  (p=0.000 n=10+10)
IndexConstraints/range-2d-8                   24.0 ± 0%       5.0 ± 0%   -79.17%  (p=0.000 n=10+10)
IndexConstraints/many-columns-8               36.0 ± 0%      15.0 ± 0%   -58.33%  (p=0.000 n=10+10)
IndexConstraints/single-jumbo-span-10-8       91.0 ± 0%      21.0 ± 0%   -76.92%  (p=0.000 n=10+10)
IndexConstraints/single-jumbo-span-100-8       901 ± 0%       201 ± 0%   -77.69%  (p=0.000 n=10+10)
```
Release note: None

Many thanks to @andy-kimball for tracking down various performance problems.

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 255 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8XdJ0z9biuS1zhQQl-:-L8XdJ0z9biuS1zhQQl0:b-o0dvx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/idxconstraint/index_constraints.go#L255)):*
> ```Go
> 
> 	case opt.NeOp, opt.IsNotOp:
> 		startKey, startBoundary := c.notNullStartKey(offset)
> ```

A comment here would be good, maybe something like:
```
// Build constraint that doesn't contain the key:
//   if nullable    : [ - key) (key - ]
//   if not nullable: (NULL - key) (key - ]
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-:-L8XfVJN4-zyc19-f1DH:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 255 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8XdJ0z9biuS1zhQQl-:-L8Xh6kaBIBKAoGh1EBf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/idxconstraint/index_constraints.go#L255)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

A comment here would be good, maybe something like:
```
// Build constraint that doesn't contain the key:
//   if nullable    : [ - key) (key - ]
//   if not nullable: (NULL - key) (key - ]
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 20 of 20 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/opt_index_selection.go, line 223 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8Xc5xI1q5kx9tidYL7:-L8Xc5xI1q5kx9tidYL8:b-49rg34) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt_index_selection.go#L223)):*
> ```Go
> 		for i, c := range candidates {
> 			log.Infof(
> 				ctx, "%d: selectIndex(%s): cost=%v spans=%s reverse=%t",
> ```

should this be `constraint=%s`?

---

*[pkg/sql/opt_index_selection.go, line 596 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8XdPHI-vyQTnUxjhr5:-L8XdPHI-vyQTnUxjhr6:b6aan7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt_index_selection.go#L596)):*
> ```Go
> }
> 
> // spanFromConstraintSpan converts an constraint.Span to a
> ```

[nit] an -> a

---

*[pkg/sql/opt/constraint/span.go, line 86 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8Xi62q-3dKq3IJVe9G:-L8Xi62q-3dKq3IJVe9H:b-64qcr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/constraint/span.go#L86)):*
> ```Go
> }
> 
> // EndBoundary returns whether the start key is included or excluded.
> ```

start -> end

---

*[pkg/sql/opt/constraint/spans.go, line 36 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8Xir3z-f6eGIAcMbTm:-L8Xir4-1hCYkzDJwjAb:b2x08ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/constraint/spans.go#L36)):*
> ```Go
> 
> // Alloc allocates enough space to support the given amount of spans without
> // reallocation. Does nothing if the structure already contains spans.
> ```

Doesn't look like that's true - it checks if `s.numSpans > 0`

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 437 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8XnVt1Bmw_8R7Bdlji:-L8XnVt1Bmw_8R7Bdljj:baho6z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/idxconstraint/index_constraints.go#L437)):*
> ```Go
> 	}
> 
> 	// We use makeNotNullSpan to disallow NULLs on the first column.
> ```

update comment

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-:-L8Xrcms1pZv59NRP5_p:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt_index_selection.go, line 223 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8Xc5xI1q5kx9tidYL7:-L8Xz89AAI9VggaY20Da:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt_index_selection.go#L223)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should this be `constraint=%s`?
</blockquote></details>

Done.

---

*[pkg/sql/opt_index_selection.go, line 596 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8XdPHI-vyQTnUxjhr5:-L8XzAMo7zonejrQLTqY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt_index_selection.go#L596)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] an -> a
</blockquote></details>

Done.

---

*[pkg/sql/opt/constraint/span.go, line 86 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8Xi62q-3dKq3IJVe9G:-L8XzEJ8BqhLtH-ifepw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/constraint/span.go#L86)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

start -> end
</blockquote></details>

Done.

---

*[pkg/sql/opt/constraint/spans.go, line 36 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8Xir3z-f6eGIAcMbTm:-L8Xyt9g9ymEhRr1USkO:bjf7f3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/constraint/spans.go#L36)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Doesn't look like that's true - it checks if `s.numSpans > 0`
</blockquote></details>

Good catch!  Fixed, and added a test.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 437 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-L8XnVt1Bmw_8R7Bdlji:-L8XzM-8DMYcKIFrSj5z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9c16a95bb399023b8024454764613ddeafe1eb/pkg/sql/opt/idxconstraint/index_constraints.go#L437)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

update comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192#-:-L8XzNco8hF34AHdTXQt:bz5mair)*

**Comment by rytaft** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24192)*

**Pull request merged**
