### PR TITLE
tracing: introduce a per-span limit for structured events

### PR DESCRIPTION
**Pull request by irfansharif**
Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Can we construct a way to also detect when the ring buffer has been full and cycled? We'll want to know when things have been lost.

Can we also use a ring buffer for the unstructured (log) events too?

**Review by irfansharif — COMMENTED** [review]
Yes to both of those, we'll want to tightly bound how large a verbose span can get and a ring buffer could be one way to do it. I'm hoping to take a stab at the code that renders trace events, but not yet. This could be captured then. For now, we don't have a great way to view structured events anyway (part of what Angela is working on), so I'll wait until we make head way there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60678#-:-MTpvZ58A8lP4hjXt-Vb:b-30w99u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen and @tbg)

**Review by tbg — APPROVED** [review]
Touches https://github.com/cockroachdb/cockroach/issues/59188

I think we should merge this because it's 1000x better than `master` now, but ideally the limiting would be based on a count of bytes, not just a count of items. We are already asking `Structured` to implement `interface{ Size() int }` so this is easy. All you'd have to change here to get this is to do

```
type crdbSpan {
  bytesStructured int64 // atomic
}

func (s *crdbSpan) RecordStructured(item Structured) {
  n := int64(item.Size())
  if atomic.AddInt64(&s.bytesStructured, n) > maxStructuredBytesPerSpan {
    // NB: this would also be a convenient place to mark the span has having
    // filled up once we want that.
    atomic.AddInt64(&s.bytesStructured, -n)
    return
  }
  // do the usual stuff
}
```

and given how easy it is, I would do it - the count-based mechanism will also translate poorly to verbose messages, which can get *huge*.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60678#-:-MU7xyF90GRgwYYs0AEX:bhvnnmu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen and @irfansharif)

___
*[pkg/util/tracing/tracer.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60678#-MU7xpnoEzdI6G6dq88m:-MU7xpnoEzdI6G6dq88n:bww7j9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b39cc391bab7a1d71714477d2f188d3ca4d324/pkg/util/tracing/tracer.go#L402)):*
> ```Go
> 		},
> 	}
> 	helper.crdbSpan.mu.structured.Reserve(maxStructuredEventsPerSpan)
> ```

This will allocate a slice of 50 elements for every Span, which seems inefficient. Why don't we let the ringbuf grow as needed, up to `maxStructuredEventsPerSpan`?

**Review by irfansharif — COMMENTED** [review]
I have another PR brewing doing both those things, probably could do with another round of review, so merging this one as is.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60678#-:-MUGOci35WcKPCs6ik4W:bibj152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen and @irfansharif)

**Pull request merged**
