### PR TITLE
storage: per-store categorized write metrics

### LINKED ISSUE #126431: storage: categorized write metrics are inflated
In a multi-store configuration, the categorized write metrics can report inflated numbers.

For example, the following was pulled from a single node that has four stores:

Screenshot 2024-06-28 at 2 13 09 PM

Note also that the metrics per store are ~identical, which is sus.

Digging into the code, we have a single `DiskWriteStatsCollector` for all engines, and the collector doesn't internally separate based on store.

[More context (internal)](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1719609559087359).

Jira issue: CRDB-39906

### PR DESCRIPTION
**Pull request by aadityasondhi**
Previously, we were using a single node-level `DiskWriteStatsCollector`, which led to inflated metrics in multi-store deployments.

This patch introduces a `WriteStatsManager` that maps physical disk `DeviceID` to a unique `DiskWriteStatsCollector`. By doing this, we are able to attribute categorized disk writes to each store's physical disks, and track other writes such as CRDB logs and sql spills.

Fixes #126431.

Release note: None

### CODE REVIEW

**Comment by aadityasondhi** [comment]
Running on roachprod with 3 nodes and 4 stores each.

Node level metrics: 
image

Store level metrics (n1):
image

**Comment by aadityasondhi** [comment]
Running roachprod with this patch. Setup is a 3 node cluster, each with 4 store.

Cluster level view:
image


Node level view (metrics are per-store) for n1:
image

Total disk writes from Hardware tab:
image

**Comment by aadityasondhi** [comment]
Tested using roachprod on 3 node cluster with 4 stores each.

Cluster level (per-node):
image

Cluster level, filtered on n1 wal writes:
image


Hardware stats for n1:
image

Node level view (per-store):
image

**Review by jbowens — COMMENTED** [review]
Looking great; got a few questions

> Reviewed 15 of 22 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-:-O2z6T7D6vYzDwFxt20h:b-ihaztq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`docs/generated/metrics/metrics.html` line 648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-O2z23XwEGEftaU9YZgI:-O2z23XxDzoBrJRnvk5K:b-1kpq29) ([raw file](https://github.com/cockroachdb/cockroach/blob/60756070016412e61d0ab36880d4a109cb998340/docs/generated/metrics/metrics.html#L648)):*
> ```HTML
> <tr><td>STORAGE</td><td>storage.category-pebble-manifest.bytes-written</td><td>Bytes written to disk</td><td>Bytes</td><td>GAUGE</td><td>BYTES</td><td>AVG</td><td>NONE</td></tr>
> <tr><td>STORAGE</td><td>storage.category-pebble-wal.bytes-written</td><td>Bytes written to disk</td><td>Bytes</td><td>GAUGE</td><td>BYTES</td><td>AVG</td><td>NONE</td></tr>
> <tr><td>STORAGE</td><td>storage.category-unspecified.bytes-written</td><td>Bytes written to disk</td><td>Bytes</td><td>GAUGE</td><td>BYTES</td><td>AVG</td><td>NONE</td></tr>
> ```

Do the categorized timeseries metrics not appear here because they're lazily constructed and not statically known, so `generate` does not know of them? I suppose we could statically define all the possible Cockroach-level category enum variants in the `storage/fs` package. The pebble-defined ones are trickier...
___
*[`pkg/cli/log_flags.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-O2z46P4E95jRIcFl8V8:-O2z46P4E95jRIcFl8V9:bf5kdoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4a7f3488f468030b295e3c66c36bc34a3cee867/pkg/cli/log_flags.go#L201)):*
> ```Go
> 			return err
> 		}
> 	} else if h.Config.FileDefaults.Dir != nil {
> ```

this is a naive Cockroach logs question, but is it possible `h.Config.Sinks.FileGroups` contains `FileSinkConfig`s with dirs outside `h.Config.FileDefaults.Dir`?
___
*[`pkg/kv/kvserver/metrics.go` line 4102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-O2z5XEq9uwqLu1jJvn7:-O2z5XEq9uwqLu1jJvn8:buicpcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4a7f3488f468030b295e3c66c36bc34a3cee867/pkg/kv/kvserver/metrics.go#L4102)):*
> ```Go
> 
> type pebbleCategoryDiskWriteMetrics struct {
> 	BytesWritten *metric.Counter
> ```

:sunglasses: 
___
*[`pkg/storage/disk/stats_collector.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-O2z56wc7_knEj_N43Wr:-O2z56wc7_knEj_N43Ws:b-uqdngj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4a7f3488f468030b295e3c66c36bc34a3cee867/pkg/storage/disk/stats_collector.go#L72)):*
> ```Go
> // TestingStatsManager is used for tests. It maps path to
> // vfs.DiskWriteStatsCollector instead of DeviceID.
> type TestingStatsManager struct {
> ```

wondering if this could be done by mocking `vfs.FS` instead to wrap a `vfs.FS` and override `vfs.Stat` to use mocked device IDs for each path, so we can still exercise `StatsManager`?

**Review by aadityasondhi — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-:-O3-UkBkC2cJPySD-R4v:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`docs/generated/metrics/metrics.html` line 648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-O2z23XwEGEftaU9YZgI:-O3-T7adETgvHM-oVLDC:bu9agky) ([raw file](https://github.com/cockroachdb/cockroach/blob/60756070016412e61d0ab36880d4a109cb998340/docs/generated/metrics/metrics.html#L648)):*
> Do the categorized timeseries metrics not appear here because they're lazily constructed and not statically known

Yes
> I suppose we could statically define all the possible Cockroach-level category enum variants in the `storage/fs` package. The pebble-defined ones are trickier...

I initially decided against that initially since we already do similar lazy loading in other places. AC does something similar with work queue metrics and we do the same thing for the categorized iterator stats. 
___
*[`pkg/cli/log_flags.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-O2z46P4E95jRIcFl8V8:-O3-UMk8-5uVgqBYzd93:b2ymf1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4a7f3488f468030b295e3c66c36bc34a3cee867/pkg/cli/log_flags.go#L201)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

this is a naive Cockroach logs question, but is it possible `h.Config.Sinks.FileGroups` contains `FileSinkConfig`s with dirs outside `h.Config.FileDefaults.Dir`?
</blockquote></details>

Nice catch! I think I was just being lazy, but in theory we could have multiple file sinks all writing to different dirs on different physical disks. I fixed this by making the logging metric per file sink. 
___
*[`pkg/storage/disk/stats_collector.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-O2z56wc7_knEj_N43Wr:-O3-TdPZ1n5ii-s2aubc:b1mykdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4a7f3488f468030b295e3c66c36bc34a3cee867/pkg/storage/disk/stats_collector.go#L72)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

wondering if this could be done by mocking `vfs.FS` instead to wrap a `vfs.FS` and override `vfs.Stat` to use mocked device IDs for each path, so we can still exercise `StatsManager`?
</blockquote></details>

Attempted this, but we actually rely on the os level functions to do the mappings. It is non-trivial to mock it from the VFS layer. I have added a comment here to document that this is only used for specific tests and the others use the other code path that is used in production.

**Comment by aadityasondhi** [comment]
Introduced a dependency cycle with the category enum, fixed it now. PTAL.

**Review by jbowens — APPROVED** [review]
:lgtm:

thanks for tackling this!

> Reviewed 1 of 22 files at r1, 1 of 3 files at r3, 3 of 21 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127266#-:-O38Dy8eDuUvVv4XYpjd:b6vmgx7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Comment by aadityasondhi** [comment]
TFTR! 

bors r=jbowens

**Pull request merged**
