### PR TITLE
sql: pass postgres error codes to the client

### PR DESCRIPTION
**Pull request by andreimatei**
This is going to be useful for the client to be able to distinguish retriable error.

The SQL errors are now coalesced into a single `roachpb.Error` detail, which contains an error code.
I've tried to have SQL not use `pErr` anymore, but it would have taken a while.

notice @tschottdorf

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5364)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r1, 6 of 6 files at r2.
Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[roachpb/errors.go, line 109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5w9TCWZuQ7bw9xW4n:-KD5w9TCWZuQ7bw9xW4o:-863591025) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.go#L109)):*
comments are supposed to start with the method name, but Error() is special and doesn't require a comment. Just remove this.

---

*[roachpb/errors.proto, line 177 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wIpLBgLxm-nC8pRH:-KD5wIpLBgLxm-nC8pRI:2038124964) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.proto#L177)):*
This name is too generic - this error really carries PG error codes, right?

---

*[sql/errors.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wtXCDc1Z7OP2-rAY:-KD5wtXCDc1Z7OP2-rAZ:-546323118) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L113)):*
this comment is a light on important detail (why is it hard to make txn.Exec() not return a pErr?). in its current form it's just FUD, and does more harm than good.

---

*[sql/errors.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5x9jgizjcG-8lSqb6:-KD5x9jgizjcG-8lSqb7:-952141864) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L161)):*
s/it/it in/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by kkaneda** [comment]
Review status: 10 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

*[roachpb/errors.proto, line 174 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6OMjQPDmkMHxjP1nS:-KD6OMjR_HuwRzoXD3us:-121019820) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.proto#L174)):*
Just checking my understanding: We don't move this and DidntUpdateDescriptorError to SQLErrorProto as these won't be passed to clients?

---

*[sql/errors.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wtXCDc1Z7OP2-rAY:-KD6Q3TGLNaSmq17J4sg:713868123) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L113)):*
My experience so was that we have callers of `txn.Exec()` that use `getDetail` to do type check..

---

*[sql/errors.go, line 170 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6QnArD7_-vkjhEKSM:-KD6QnArD7_-vkjhEKSN:625067059) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L170)):*
nitpick: s/`pErr.GoError().Error()`/`pErr.Message()`?

---

*[sql/executor.go, line 793 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6TJiTQ_qsJJPF_Du6:-KD6TJiTQ_qsJJPF_Du7:-1342102784) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acaaef3698a269c6da52af918674a5f5ca9117e/sql/executor.go#L793)):*
I'm not totally sure, but does this make sense to call `convertToSQLError` in `sendPErr`)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by andreimatei** [comment]
Review status: 5 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[roachpb/errors.go, line 109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5w9TCWZuQ7bw9xW4n:-KDAEmTL4NNskyhptRI1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.go#L109)):*
Done.

---

*[roachpb/errors.proto, line 174 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6OMjQPDmkMHxjP1nS:-KDAFdTB0qCIHCd7G3Ll:-1417291154) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.proto#L174)):*
`ExistingSchemaChangeLeaseError` seems to indeed be an internal error that causes us to keep retrying stuff. So, yeah, it shouldn't have an error code, as the client is not gonna see it.

`DindUpdateDescriptorError` seems to also be caught internally and ignored. I'm not really sure what this one means to be honest, but it looks pretty internal to me.
https://github.com/cockroachdb/cockroach/blob/master/sql/lease.go#L284

---

*[roachpb/errors.proto, line 177 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wIpLBgLxm-nC8pRH:-KDAGRwKfeO_z5hjzQmh:2095659576) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.proto#L177)):*
yeah, PG error codes + cockroach specific codes. What name would you suggest? `ErrorWithPGCode`?

---

*[sql/errors.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wtXCDc1Z7OP2-rAY:-KDAHONXpGMq-blxf7kQ:-2094492711) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L113)):*
@tamird ok, added a TODO to `txn.Exec()` instead.

@kkaneda right, but that's not ideal, is it? There's no reason for callers of `txn.Exec()` to get a proto, is there? `txn.Exec()` should return a plain `error`. In fact, there's no reason even for the callback that's passed to `txn.Exec` to return a proto. It should just return an `error` augmented with a `retriable={true,false}` flag.
This way we wouldn't have to play with this `errorDetail` machinery every time we want to introduce new errors in parts of the system that don't need marshaling of errors over the network.

---

*[sql/errors.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5x9jgizjcG-8lSqb6:-KDAHL_0YvQDo6F3zv9V:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L161)):*
Done.

---

*[sql/errors.go, line 170 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6QnArD7_-vkjhEKSM:-KDAIdTnAQz0OrSFOFP1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L170)):*
Done.

---

*[sql/executor.go, line 793 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6TJiTQ_qsJJPF_Du6:-KDAJugReGZL6YWh9y-m:1225642286) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acaaef3698a269c6da52af918674a5f5ca9117e/sql/executor.go#L793)):*
hmm interesting, I haven't considered doing that. You could argue for it. I think I prefer it the way it is, though. The SQL execution layer, above that pgwire code, has to deal with "sql errors" anyway (for example there's that `convertBatchError()` function that recognized uniqueness constraint violations; that code would definitely be inappropriate to be called from pgwire). So given that, I'd rather we do all these error transformation shenanigans in SQL.
And the long game here is to have `convertToSQLError` return this new `sqlError` interface, and propagate these kinds of errors up through the callback and `txn.Exec()`. Once this happens, it'd be more clear that you want to do this conversion operation as early as possible.

What do you think?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 6 files at r2, 5 of 8 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by tamird** [comment]
Reviewed 5 of 8 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 449 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB7kuxwkJBalhqWMTQ:-KDB7kuy2bQfeQXm-7R7:-1725193636) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/client/txn.go#L449)):*
as noted elsewhere, sql needs to know when we hit a cput error

---

*[roachpb/errors.proto, line 177 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wIpLBgLxm-nC8pRH:-KDB6m_0Cn5qWN1Kw5Zv:-1272320892) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.proto#L177)):*
Yeah, that would be better. I don't feel strongly other than avoiding "SQL" as the name.

---

*[sql/errors.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wtXCDc1Z7OP2-rAY:-KDB7D6cF01b74GKgsfi:956858454) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L113)):*
callers of `txn.Exec` sometimes need to deconstruct the structured error, which is why they need the proto (see UniquenessConstraintViolation in sql code).

---

*[sql/errors.go, line 42 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB70fUJS_Nkjfxt_JR:-KDB70fVv40Kcz2NZSc4:-153378749) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L42)):*
space after `//`

---

*[sql/errors.go, line 70 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB75eqVTdTfeqfPr8M:-KDB75eqVTdTfeqfPr8N:962091) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L70)):*
use a pointer receiver - when used as an interface, this thing will be on the heap anyway.

---

*[sql/logic_test.go, line 54 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB85jrzqpMt9RSwAKp:-KDB85jrzqpMt9RSwAKq:-1060448293) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/logic_test.go#L54)):*
shouldn't that be `[[:alnum:]]+`?

someone else should look at this code, it's getting a bit hairy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by kkaneda** [comment]
Reviewed 5 of 6 files at r2, 5 of 8 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[roachpb/errors.proto, line 174 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6OMjQPDmkMHxjP1nS:-KDBj4CntZl69LpS2ZV9:1412990793) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.proto#L174)):*
Thanks! Yes, makes sense.

---

*[roachpb/errors.proto, line 210 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDBnhPsvp9UDJh7m0gx:-KDBnhPttQCPR80ecJha:815250400) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/roachpb/errors.proto#L210)):*
nitpick: if we don't care the backward compatibility, we could change the field id to `20` or change `existing_scheme_change_lease` to use `20` (and then change `sql_error` to use `21`)..

---

*[sql/executor.go, line 793 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6TJiTQ_qsJJPF_Du6:-KDBjT4QbOy_KTaDLKTM:47464143) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acaaef3698a269c6da52af918674a5f5ca9117e/sql/executor.go#L793)):*
Thanks for the explanation! Sounds good to me. Just wondered where else we should call `convertToSQLError`.. For example, `execStmtInOpenTxn` also sets `Result.PErr` and I wonder we might want to call `convertToSQLError` there..

---

*[sql/logic_test.go, line 525 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDBm31DY51015dvA13b:-KDBm31EzmHsolsa_4fC:-1125315240) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/logic_test.go#L525)):*
nitpick: maybe just ```if expectErr == "" && expectErrCode == "" && err != nil```?

---

*[sql/logic_test.go, line 549 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDBmb3K3MyPWmD5llqF:-KDBmb3K3MyPWmD5llqG:-674575139) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/logic_test.go#L549)):*
nitpick: whitespace between `error code` and `%q`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by kkaneda** [comment]
Sorry for the slow review iteration.. The change looks good to me!

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[sql/errors.go, line 30 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDF8fKRJDGJcbd4snCq:-KDF8fKRJDGJcbd4snCr:-840616287) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L30)):*
Include a link to http://www.postgresql.org/docs/9.5/static/errcodes-appendix.html where the upstream codes are defined.

---

*[sql/errors.go, line 46 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDF8nedPOV43pqxcCbr:-KDF8nedPOV43pqxcCbs:1927504532) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L46)):*
I'd prefer CR instead of CK as the abbreviation for CockroachDB extensions.

---

*[sql/errors.go, line 60 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDF9NAJokbpNYHgBHt0:-KDF9NAJokbpNYHgBHt1:-914043042) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L60)):*
This constant is only used once, so I'd just make it a literal in the method where it is used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by andreimatei** [comment]
thanks @kkaneda, wasn't slow at all!

---

Review status: 2 of 14 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 449 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB7kuxwkJBalhqWMTQ:-KDPUqYPgKFA3TRIl4cM:-366338791) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/client/txn.go#L449)):*
replied in the other place

---

*[roachpb/errors.proto, line 177 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wIpLBgLxm-nC8pRH:-KDPRBc7AEfIRqssRexe:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/roachpb/errors.proto#L177)):*
Done.

---

*[roachpb/errors.proto, line 210 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDBnhPsvp9UDJh7m0gx:-KDPROCVjnSiFMD1dX-a:-1334661081) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/roachpb/errors.proto#L210)):*
done. Indeed we don't care since we're not saving these protos anywhere (at least that I know).

---

*[sql/errors.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD5wtXCDc1Z7OP2-rAY:-KDPSMf77m41yJFZbUcF:1194206064) ([raw file](https://github.com/cockroachdb/cockroach/blob/1242606986a17d9e7e2937a2549d14ff09430b59/sql/errors.go#L113)):*
@tamird all the deconstructing of sql errors that SQL does is done inside the closure passed to `txn.Exec`.

---

*[sql/errors.go, line 30 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDF8fKRJDGJcbd4snCq:-KDPRfgXKR16Vnh-h3ZP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L30)):*
Done.

---

*[sql/errors.go, line 42 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB70fUJS_Nkjfxt_JR:-KDPRfQjAFGoI2goh47a:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L42)):*
Done.

---

*[sql/errors.go, line 46 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDF8nedPOV43pqxcCbr:-KDPRZkBIpayAQcao6h0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L46)):*
Done.

---

*[sql/errors.go, line 60 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDF9NAJokbpNYHgBHt0:-KDPRib6rtI3tUu0MEEF:1650120553) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L60)):*
I like all of these constants together. Plus, we might extract them to a common package if we ever have drivers that need to map error codes to messages. For example lib/pq has such a map.

---

*[sql/errors.go, line 70 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB75eqVTdTfeqfPr8M:-KDPSI1u9FgTnoYTAl2r:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/errors.go#L70)):*
Done.

---

*[sql/executor.go, line 793 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KD6TJiTQ_qsJJPF_Du6:-KDPSnBE0CX7jreE61Ir:1635844673) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acaaef3698a269c6da52af918674a5f5ca9117e/sql/executor.go#L793)):*
`execStmtInOpenTxn` is called just above this, so its Result will be processed here.

---

*[sql/logic_test.go, line 54 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB85jrzqpMt9RSwAKp:-KDPUVnpxC0n3gUoJEwz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/logic_test.go#L54)):*
Done.

---

*[sql/logic_test.go, line 525 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDBm31DY51015dvA13b:-KDPUc_0BXN-hJqMAirA:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/logic_test.go#L525)):*
Done.

---

*[sql/logic_test.go, line 549 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDBmb3K3MyPWmD5llqF:-KDPUff4eXZSFt6k6ify:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/sql/logic_test.go#L549)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-:-KDPUi5BrZwiekVTd92x:819715073)*

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 449 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB7kuxwkJBalhqWMTQ:-KDPXhU2nq2TPR1jSL9y:1101362681) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/client/txn.go#L449)):*
Seems like this is the right place to discuss.

> all the deconstructing of sql errors that SQL does is done inside the closure passed to txn.Exec.

Are you sure? Look at callers of `convertBatchError`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by andreimatei** [comment]
Review status: 2 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[client/txn.go, line 449 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364#-KDB7kuxwkJBalhqWMTQ:-KDPgtq5Dj6jwBkoOyCE:504381075) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb65e7b88c69ef3a24fd5d0590cb5e3626b43014/client/txn.go#L449)):*
as discussed, this is called inside a KV txn

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r8, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5364)*

**Pull request merged**
