### PR TITLE
roachtest: avoid cdc/ledger failures caused by splits

### PR DESCRIPTION
**Pull request by stevendanna**
Rangefeed catchup scans are slow. Splits cause catchup scans. Range
growth causes splits.

To avoid continued cdc/ledger failures while we address catchup scan
performance, this change reduces the duration of the test and
increases the max range size to avoid range splits.

Release note: None

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/cmd/roachtest/cdc.go, line 746 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67232#-MdwrBtbDBFEour9J6xy:-MdwrBtbDBFEour9J6xz:b-zhiqth) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fc41c657e083a14e1d8d3af2e2194a77666221/pkg/cmd/roachtest/cdc.go#L746)):*
> ```Go
> 				workloadType: ledgerWorkloadType,
> 				// TODO(ssd): Range splits cause changefeed latencies to balloon
> 				// becuase of catchup-scan performance. Reducing thet test time and
> ```

Technically not a nit because this fails the linter: s/becuase/because and s/thet/the

**Comment by stevendanna** [comment]
bors r=HonoreDB

**Comment by stevendanna** [comment]
bors cancel

**Comment by stevendanna** [comment]
bors r=HonoreDB

**Pull request merged**
