### PR TITLE
acceptance: re-enable bank/zerosum-restart

### PR DESCRIPTION
**Pull request by tbg**
This was forgotten, #30064 is long fixed :fingers_crossed:

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
```
test.go:696,bank.go:375,bank.go:569,acceptance.go:69: pq: while adding target n3,s3: snapshot failed: unable to dial n3: breaker open
```

Looks like this still needs some work.

**Comment by tbg** [comment]
Added the random error to the already random whitelist...

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33549#-:-LVsRPCc-qbyx6dp54TV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33549#-LVsRInr8y_APAQa8Esc:-LVsRIns-uTgb0orzNri:bihk2eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3fe9cc0495cfd405ff978ca3b922b5350917a3/pkg/cmd/roachtest/bank.go#L348)):*
> ```Go
> 
> func isExpectedRelocateError(err error) bool {
> 	return testutils.IsError(err, "(descriptor changed|unable to remove replica .* which is not present|unable to add replica .* which is already present|received invalid ChangeReplicasTrigger .* to remove self|breaker open)")
> ```

I'm actually a bit surprised by `breaker open`.

**Review by nvb — APPROVED** [review]

**Review by tbg — COMMENTED** [review]
TFTRs!
bors r=petermattis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33549#-:-LVvvaG01mUXTqlihpdC:bvd9sdw)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33549#-LVsRInr8y_APAQa8Esc:-LVvvYTDDoIWxR0LMkxa:b-lh53a5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3fe9cc0495cfd405ff978ca3b922b5350917a3/pkg/cmd/roachtest/bank.go#L348)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm actually a bit surprised by `breaker open`.
</blockquote></details>

Agreed, filed https://github.com/cockroachdb/cockroach/issues/33657 to follow up.

**Pull request merged**
