### PR TITLE
Bump RocksDB to 5.0.2.

### PR DESCRIPTION
**Pull request by petermattis**
Use the new RocksDB DeleteRange op. This needs testing on production
clusters before merging.

```
name                  old time/op   new time/op        delta
ClearRange_RocksDB-8    216ms ± 2%           0ms ± 2%       -100.00% (p=0.000 n=10+10)

name                  old speed     new speed          delta
ClearRange_RocksDB-8  310MB/s ± 2%  83215447MB/s ± 2%  +26820751.44% (p=0.000 n=10+10)
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12913)

### CODE REVIEW

**Comment by tamird** [comment]
O.o

is that benchmark real? is rocksdb doing the work asynchronously?

**Comment by petermattis** [comment]
@spencerkimball Can you test this out on `blue`? The wifi connection on the plane isn't reliable enough to do so.

**Comment by tamird** [comment]
and looks like a bunch of API-breaking change adjustments are in the 2nd commit rather than the first.

**Comment by petermattis** [comment]
Yes, the benchmark is real. The `DeleteRange` operation adds a range tombstone which is much faster than adding per-key tombstones. 

There are no breaking API changes. The `AddFile` -> `IngestExternalFile` change is to remove a deprecation warning.

**Comment by spencerkimball** [comment]
Nice. Yes will work on getting this running on blue.

**Review by spencerkimball — APPROVED** [review]

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 9 of 9 files at r2.
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/bench_test.go, line 612 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913#-KaNpH-oO_kBt2oeRUvM:-KaNpH-oO_kBt2oeRUvN:b-csi1wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/03116e54f31af4fead6f550470777e868fed47cf/pkg/storage/engine/bench_test.go#L612)):*
> ```Go
> 			b.Fatal(err)
> 		}
> 		// NB: We don't actually commit the batch here as we don't want to delete
> ```

is this actually reasonable to do? seems like there might be a real cost to the `commit`.

---

*[pkg/storage/engine/bench_test.go, line 614 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913#-KaNlp8S4pTozxCXM09X:-KaNlp8S4pTozxCXM09Y:b-z28t0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/03116e54f31af4fead6f550470777e868fed47cf/pkg/storage/engine/bench_test.go#L614)):*
> when ClearRange was slowly because the benchmark to
> 		// take an exceptionally long time now that ClearRange is very fast.
something went wrong here

---

*[pkg/storage/engine/bench_test.go, line 630 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913#-KaNm0WDNDRdh-0KSVUi:-KaNm0WDNDRdh-0KSVUj:b1s4exd) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f24f8c218083eb96c0e5a103618d8fb5aff42e/pkg/storage/engine/bench_test.go#L630)):*
> ```Go
> 		b.StopTimer()
> 
> 		dupEng.Close()
> ```

don't you still want to close the batch? At least, it does have a Close method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913)*

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/engine/bench_test.go, line 612 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913#-KaNpH-oO_kBt2oeRUvM:-KaNrOgjG5AeuIdRPoS6:b-c3n7cy) ([raw file](https://github.com/cockroachdb/cockroach/blob/03116e54f31af4fead6f550470777e868fed47cf/pkg/storage/engine/bench_test.go#L612)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this actually reasonable to do? seems like there might be a real cost to the `commit`.
</blockquote></details>

Yes, there is a cost to the commit, but it is very small. I made this change exactly because the benchmark never finished if we actually performed the commit due to the need to repopulate the data. I don't see an alternative to the current approach. A non-benchmark test shows the commit cost is very small. 

---

*[pkg/storage/engine/bench_test.go, line 614 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913#-KaNlp8S4pTozxCXM09X:-KaNrSoPU5dkKeYPyJFz:bpy0qvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/03116e54f31af4fead6f550470777e868fed47cf/pkg/storage/engine/bench_test.go#L614)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> when ClearRange was slowly because the benchmark to
> 		// take an exceptionally long time now that ClearRange is very fast.
something went wrong here
</blockquote></details>

Yeah, I think I fat-fingered deletion of part of the comment. Fixed.

---

*[pkg/storage/engine/bench_test.go, line 630 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913#-KaNm0WDNDRdh-0KSVUi:-KaNrh6s6e9eVtc5DIcV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f24f8c218083eb96c0e5a103618d8fb5aff42e/pkg/storage/engine/bench_test.go#L630)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

don't you still want to close the batch? At least, it does have a Close method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913)*

**Comment by tamird** [comment]
Reviewed 11 of 11 files at r3, 9 of 9 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913)*

**Comment by bdarnell** [comment]
LGTM

We'll need a warning when this goes out that it will not be possible to downgrade to an earlier release (because the rocksdb WAL could contain DeleteRange ops that older versions can't handle). 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12913#-:-KaO1RqQko-FTFzqfvK2:b-qio56p)*

**Comment by petermattis** [comment]
I reworked the second commit of this PR so that the usage of `DeleteRange` is conditional on `COCKROACH_ENABLE_FAST_CLEAR_RANGE` (default false). This should allow us to merge this PR and test it more thoroughly on production clusters before flipping the switch for external users.

**Comment by tamird** [comment]
Is this no longer DNM?

**Comment by petermattis** [comment]
I think it is still DNM until we understand the `block checksum mismatch` and `bad entry in block` errors.

**Comment by petermattis** [comment]
I'm planning to merge this PR later today after a I do another sanity check that usage of `DeleteRange` will not be enabled by default.

**Comment by petermattis** [comment]
Ok, this looks good to go. I'm going to merge after lunch.

**Pull request merged**
