### PR TITLE
settings: add ByteSizeSetting

### PR DESCRIPTION
**Pull request by dt**
Suggested in #15237.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/settings/registry.go, line 267 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246#-KiFqzJi-abR0VFG8I8U:-KiFqzJi-abR0VFG8I8V:bxiflsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d149d6777433e7fb7a9ea0dcfb220c7e8c5dd1/pkg/settings/registry.go#L267)):*
> ```Go
> type ByteSizeSetting struct {
> 	IntSetting
> }
> ```

Should you override `ByteSizeSetting.String` to pretty-print the value?

---

*[pkg/sql/set.go, line 184 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246#-KiFqiOvuJwiymPL0cvZ:-KiFqiOvuJwiymPL0cv_:b-fktrd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d149d6777433e7fb7a9ea0dcfb220c7e8c5dd1/pkg/sql/set.go#L184)):*
> ```Go
> 				return settings.EncodeInt(bytes), nil
> 			}
> 			return "", errors.Errorf("cannot use %s %T value for duration setting", d.ResolvedType(), d)
> ```

`s/duration/byte size/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246#-:-KiFrNpPDp70O_bt8Xj1:bnfp4nl)*

**Comment by dt** [comment]
Also added a commit to switch the snapshot settings over. RFAL.

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/registry.go, line 267 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246#-KiFqzJi-abR0VFG8I8U:-KiFuQfMcxKIpC4RGeW9:b-vsgwr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d149d6777433e7fb7a9ea0dcfb220c7e8c5dd1/pkg/settings/registry.go#L267)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I tried that initially,  but changed my mind after seeing it round in the test below to "1.4GiB" -- I think I value exact value over the readability?
</blockquote></details>

Hmm, not sure I agree with that, but I don't feel strongly. Perhaps I'll change my mind once I see this in action.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/registry.go, line 267 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246#-KiFqzJi-abR0VFG8I8U:-KiFzxZEPMjayTPmu69p:b-1szdfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d149d6777433e7fb7a9ea0dcfb220c7e8c5dd1/pkg/settings/registry.go#L267)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Hmm, not sure I agree with that, but I don't feel strongly. Perhaps I'll change my mind once I see this in action.
</blockquote></details>

Okay, added pretty-print `String`, and a test that shows `1500MB` and `1450MB` are both returned as `1.4GiB` in `SHOW CLUSTER SETTING`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246)*

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/registry.go, line 267 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246#-KiFqzJi-abR0VFG8I8U:-KiG0JCx9fl5w8KrfxaA:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d149d6777433e7fb7a9ea0dcfb220c7e8c5dd1/pkg/settings/registry.go#L267)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Okay, added pretty-print `String`, and a test that shows `1500MB` and `1450MB` are both returned as `1.4GiB` in `SHOW CLUSTER SETTING`.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15246)*

**Pull request merged**
