### PR TITLE
roachtest: disable metamorphic expiration leases in some tests

### LINKED ISSUE #103268: roachtest: import/mixed-versions failed
roachtest.import/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/import/mixed-versions) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/import/mixed-versions/run_1
(versionupgrade.go:280).func1: failed to set cluster settings: ~ 
		if ! test -e /mnt/data1/cockroach/settings-initialized ; then
			COCKROACH_CONNECT_TIMEOUT=1200 ./v22.2.9/cockroach sql --url 'postgres://root@localhost:26257?sslmode=disable' -e "SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';
SET CLUSTER SETTING enterprise.license = '<redacted>';
SET CLUSTER SETTING kv.expiration_leases_only.enabled = 'false';
" && touch /mnt/data1/cockroach/settings-initialized
		fi
SET CLUSTER SETTING
SET CLUSTER SETTING
ERROR: unknown cluster setting 'kv.expiration_leases_only.enabled'
Failed running "sql": COMMAND_PROBLEM: ssh verbose log retained in ssh_052837.544389869_n1_set-cluster-settings.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #84150 roachtest: import/mixed-versions failed [C-test-failure O-roachtest O-robot T-disaster-recovery T-server-and-security branch-release-22.1]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27909

### LINKED ISSUE #103271: roachtest: rebalance/by-load/leases/mixed-version failed
roachtest.rebalance/by-load/leases/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/rebalance/by-load/leases/mixed-version) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/rebalance/by-load/leases/mixed-version/run_1
(cluster.go:1943).Start: failed to set cluster settings: ~ 
		if ! test -e /mnt/data1/cockroach/settings-initialized ; then
			COCKROACH_CONNECT_TIMEOUT=1200 ./v22.2.9/cockroach sql --url 'postgres://root@localhost:26257?sslmode=disable' -e "SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';
SET CLUSTER SETTING enterprise.license = '<redacted>';
SET CLUSTER SETTING kv.expiration_leases_only.enabled = 'false';
" && touch /mnt/data1/cockroach/settings-initialized
		fi
SET CLUSTER SETTING
SET CLUSTER SETTING
ERROR: unknown cluster setting 'kv.expiration_leases_only.enabled'
Failed running "sql": COMMAND_PROBLEM: ssh verbose log retained in ssh_053610.904039832_n1_set-cluster-settings.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*rebalance/by-load/leases/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27912

### LINKED ISSUE #103272: roachtest: schemachange/secondary-index-multi-version failed
roachtest.schemachange/secondary-index-multi-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/schemachange/secondary-index-multi-version) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/schemachange/secondary-index-multi-version/run_1
(versionupgrade.go:292).func1: failed to set cluster settings: ~ 
		if ! test -e /mnt/data1/cockroach/settings-initialized ; then
			COCKROACH_CONNECT_TIMEOUT=1200 ./v22.2.9/cockroach sql --url 'postgres://root@localhost:26257?sslmode=disable' -e "SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';
SET CLUSTER SETTING enterprise.license = '<redacted>';
SET CLUSTER SETTING kv.expiration_leases_only.enabled = 'false';
" && touch /mnt/data1/cockroach/settings-initialized
		fi
SET CLUSTER SETTING
SET CLUSTER SETTING
ERROR: unknown cluster setting 'kv.expiration_leases_only.enabled'
Failed running "sql": COMMAND_PROBLEM: ssh verbose log retained in ssh_062602.662634245_n1_set-cluster-settings.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/secondary-index-multi-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27913

### LINKED ISSUE #103275: roachtest: kv/splits/nodes=3/quiesce=true failed
roachtest.kv/splits/nodes=3/quiesce=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/kv/splits/nodes=3/quiesce=true) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/kv/splits/nodes=3/quiesce=true/run_1
(cluster.go:2043).Run: output in run_053242.396662945_n4_workload-run-kv-init: ./workload run kv --init --max-ops=1 --concurrency=192 --splits=300000 {pgurl:1-3} returned: COMMAND_PROBLEM: ssh verbose log retained in ssh_053243.265351197_n4_workload-run-kv-init.log: exit status 1
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/splits/nodes=3/quiesce=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27916

### LINKED ISSUE #103287: roachtest: follower-reads/mixed-version/single-region failed
roachtest.follower-reads/mixed-version/single-region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/follower-reads/mixed-version/single-region) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/follower-reads/mixed-version/single-region/run_1
(cluster.go:1943).Start: failed to set cluster settings: ~ 
		if ! test -e /mnt/data1/cockroach/settings-initialized ; then
			COCKROACH_CONNECT_TIMEOUT=1200 ./v22.2.9/cockroach sql --url 'postgres://root@localhost:26257?sslmode=disable' -e "SET CLUSTER SETTING enterprise.license = 'crl-0-EID/+KQHGAEiI0NvY2tyb2FjaCBMYWJzIC0gUHJvZHVjdGlvbiBUZXN0aW5n';
SET CLUSTER SETTING kv.expiration_leases_only.enabled = 'false';
SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';
" && touch /mnt/data1/cockroach/settings-initialized
		fi
SET CLUSTER SETTING
ERROR: unknown cluster setting 'kv.expiration_leases_only.enabled'
Failed running "sql": COMMAND_PROBLEM: ssh verbose log retained in ssh_123420.098733205_n1_set-cluster-settings.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=2</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*follower-reads/mixed-version/single-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27922

### LINKED ISSUE #103303: roachtest: rebalance/by-load/replicas/mixed-version failed
roachtest.rebalance/by-load/replicas/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10083565?buildTab=artifacts#/rebalance/by-load/replicas/mixed-version) on master @ [a65bca232dfde1862e5aff343e7b1f3a379d6cd6](https://github.com/cockroachdb/cockroach/commits/a65bca232dfde1862e5aff343e7b1f3a379d6cd6):

```
test artifacts and logs in: /artifacts/rebalance/by-load/replicas/mixed-version/run_1
(cluster.go:1943).Start: failed to set cluster settings: ~ 
		if ! test -e /mnt/data1/cockroach/settings-initialized ; then
			COCKROACH_CONNECT_TIMEOUT=1200 ./v22.2.9/cockroach sql --url 'postgres://root@localhost:26257?sslmode=disable' -e "SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';
SET CLUSTER SETTING enterprise.license = 'crl-0-EID/+KQHGAEiI0NvY2tyb2FjaCBMYWJzIC0gUHJvZHVjdGlvbiBUZXN0aW5n';
SET CLUSTER SETTING kv.expiration_leases_only.enabled = 'true';
" && touch /mnt/data1/cockroach/settings-initialized
		fi
SET CLUSTER SETTING
SET CLUSTER SETTING
ERROR: unknown cluster setting 'kv.expiration_leases_only.enabled'
Failed running "sql": COMMAND_PROBLEM: ssh verbose log retained in ssh_150047.533132628_n1_set-cluster-settings.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*rebalance/by-load/replicas/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27933

### PR DESCRIPTION
**Pull request by erikgrinaker**
This caused test failures in:

* `decommission/mixed-versions`
* `follower-reads/mixed-version/single-region`
* `import/mixed-versions`
* `kv/splits/nodes=3/quiesce=true`
* `rebalance/by-load/leases/mixed-version`
* `rebalance/by-load/replicas/mixed-version`
* `schemachange/secondary-index-multi-version`

Follows #103190.
Resolves #103271.
Resolves #103272.
Resolves #103275.
Resolves #103268.
Resolves #103287.
Resolves #103303.
Touches #101620.

Epic: none
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I think we've addressed the failures we know about so far, let's get these in before tonight's run.

**Comment by renatolabs** [comment]
Should we create an issue to revert this commit once master's release series becomes 23.2 (which should be happening soon)?

**Comment by erikgrinaker** [comment]
Yeah, may as well, I'll add an issue.

**Review by renatolabs — APPROVED** [review]

**Comment by erikgrinaker** [comment]
https://github.com/cockroachdb/cockroach/issues/103304

**Comment by rafiss** [comment]
i think this missed https://github.com/cockroachdb/cockroach/issues/103340

**Comment by erikgrinaker** [comment]
#103346

**Pull request merged**
