### PR TITLE
sql: add pprof labels based on the statement type

### PR DESCRIPTION
**Pull request by jordanlewis**
pprof profiles will now be enhanced with the type of the statement that
caused the creation of each stack. statement types are things like
'SELECT', 'INSERT', 'ALTER TABLE', etc.

This example output is produced based on a kv95 workload:

```
(pprof) tags
 stmt: Total 27.7s
       25.4s (91.77%): SELECT
        2.3s ( 8.23%): INSERT
```

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Here's a sample profile created with the new tags:

[pprof.samples.cpu.007.pb.gz](https://github.com/cockroachdb/cockroach/files/2443336/pprof.samples.cpu.007.pb.gz)

**Comment by jordanlewis** [comment]
https://rakyll.org/profiler-labels/ has more details on how the labels work,  btw.

**Comment by tschottdorf** [comment]
Just a drive by question, what's the cost of a label? Are they cheap enough to throw in basically as we please?

**Comment by jordanlewis** [comment]
They seem very cheap, but I don't know about using them more than on the order of once per query. They do a `context.Value` call and call a runtime function that sets a field on a pointer.

**Review by nvb — CHANGES_REQUESTED** [review]
Same question as Tobi. This is really neat, but I'd like to experimentally confirm that the overhead is completely negligible before making the change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30930#-:-LNvPvj8DljkCo39a8ei:b-r95cu5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/conn_executor_exec.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30930#-LNvPml38zfLpbivcJZK:-LNvPml4E5inCvUy71CW:b-70zp67) ([raw file](https://github.com/cockroachdb/cockroach/blob/533025c55ef312890fd54d43e62689dd06abe03c/pkg/sql/conn_executor_exec.go#L26)):*
> ```Go
> 	"github.com/pkg/errors"
> 
> 	pprof "runtime/pprof"
> ```

Weird import.

**Comment by jordanlewis** [comment]
```
Switching to pprof-labels~
+ make bench PKG=./pkg/bench BENCHTIMEOUT=5m 'BENCHES=BenchmarkSelect1/^Cockroach$$' 'TESTFLAGS=-count 10 -benchmem'
Switching to pprof-labels
+ make bench PKG=./pkg/bench BENCHTIMEOUT=5m 'BENCHES=BenchmarkSelect1/^Cockroach$$' 'TESTFLAGS=-count 10 -benchmem'
name                 old time/op    new time/op    delta
Select1/Cockroach-8     126µs ± 1%     140µs ±13%  +10.74%  (p=0.000 n=9+9)

name                 old alloc/op   new alloc/op   delta
Select1/Cockroach-8    18.8kB ± 0%    19.2kB ± 0%   +2.22%  (p=0.000 n=7+9)

name                 old allocs/op  new allocs/op  delta
Select1/Cockroach-8       164 ± 0%       169 ± 0%   +3.05%  (p=0.000 n=10+10)
```

Pretty disappointing. Not sure this is worth it. Though the `Do` call is high level and always allocates something - let me see if I can improve the performance by doing things with lower level calls.

**Comment by jordanlewis** [comment]
Replacing the `Do` call makes this seem ok again.

```
name                 old time/op    new time/op    delta
Select1/Cockroach-8     126µs ± 2%     127µs ± 0%    ~     (p=0.156 n=10+9)

name                 old alloc/op   new alloc/op   delta
Select1/Cockroach-8    18.8kB ± 0%    19.2kB ± 0%  +2.26%  (p=0.000 n=10+10)

name                 old allocs/op  new allocs/op  delta
Select1/Cockroach-8       164 ± 0%       169 ± 0%  +3.05%  (p=0.000 n=10+10)
```

**Comment by nvanbenschoten** [comment]
Can we statically allocate the labels for all statement types to avoid the increase in memory usage?

**Comment by jordanlewis** [comment]
We'll still have to allocate a map in `WithLabels`, since the `labelContextKey` isn't exported for us to muck with, but I think you're right that we can avoid making `LabelSet`s over and over. Good suggestion.

**Comment by nvanbenschoten** [comment]
> Nevermind, there's no way we can reduce allocations here.

Can't we at least avoid the `pprof.Labels` allocation?

**Comment by jordanlewis** [comment]
That doesn't get allocated.

**Comment by nvanbenschoten** [comment]
Really? Aren't there varargs and a slice in `pprof.Labels`?

**Comment by jordanlewis** [comment]
I ran this change through pprof and didn't see any allocations on those lines. Maybe I did something wrong?

**Review by nvb — APPROVED** [review]
Code LGTM, so up to you whether you think the added debuggability from this change is worth the minor increase in allocations.

**Comment by jordanlewis** [comment]
I'm not really sure. I'm going to let this sit a while longer and revisit when I have more headspace for it. Thanks for the reviews so far.

**Comment by tbg** [comment]
Per our discussion yesterday, I think that if you gated this behind a cluster setting and used the anonymized statement string (on top of a tag label) this would be a very useful addition that we could use in the 2.2 cycle to find out whether we'll want to make larger investments here like the ones you're dreaming of (like adding general byte counter profiles etc that help us profile I/O). WDYT?

PS: for the cluster setting, perhaps the right pattern is to make the setting a deadline at which the labels deactivate -- intended usage would be something like `SET CLUSTER SETTING server.pprof.statements = NOW() + INTERVAL '10 minutes';`.

**Pull request closed without merging**
