### PR TITLE
cluster: remove and test against obsolete versions

### PR DESCRIPTION
**Pull request by tbg**
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Very nice! :lgtm: mod a few comments.

We can even remove up to Version19_1 now, right? Did you avoid that thinking that it might interfere with backports?

> Reviewed 36 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-:-LgsQ6491uO0zXWNNVSe:bnmc724)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/server/version_cluster_test.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-LgsMu0u5I354YDaxENS:-LgsMu0u5I354YDaxENT:bsd0plb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e669c0ab3115d9fbf47a08c5b3a6e0c51a06e35a/pkg/server/version_cluster_test.go#L520)):*
> ```Go
> }
> 
> func TestClusterVersionMixedVersionTooOld(t *testing.T) {
> ```

Were these tests only relevant to version 1.0, before we had upgrade logic? I'm surprised to see us removing them.
___
*[pkg/settings/cluster/keyed_versions.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-LgsLhcc2JrIgOSQxoFU:-LgsLhcc2JrIgOSQxoFV:b-90elma) ([raw file](https://github.com/cockroachdb/cockroach/blob/350f9b9c27856402b6d8abe578bd063378a35331/pkg/settings/cluster/keyed_versions.go#L76)):*
> ```Go
> 	}
> 
> 	if n := len(byRelease) - 3; n >= 0 {
> ```

Nice! Add a comment about what this is trying to test though.
___
*[pkg/storage/replica_proposal.go, line 976 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-LgsO_MY2dxRFY63h-tL:-LgsO_MY2dxRFY63h-tM:bi69djc) ([raw file](https://github.com/cockroachdb/cockroach/blob/350f9b9c27856402b6d8abe578bd063378a35331/pkg/storage/replica_proposal.go#L976)):*
> ```Go
> 		r.mu.RUnlock()
> 		if !usingAppliedStateKey {
> 			// The range applied state was introduced in v2.1. It's possible to
> ```

I guess we can close https://github.com/cockroachdb/cockroach/pull/33653 now. cc. @andreimatei 

There is an updated comment and test in that PR that you might want to port over to here.
___
*[pkg/storage/stores.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-LgsO4LgAO4dXm-dZ4bj:-LgsO4Lh7kkStIl0S2Y-:b-3puo74) ([raw file](https://github.com/cockroachdb/cockroach/blob/e669c0ab3115d9fbf47a08c5b3a6e0c51a06e35a/pkg/storage/stores.go#L294)):*
> ```Go
> 	}
> 
> 	// These values should always exist in 1.1-initialized clusters, but may
> ```

Is it worth returning an error if this is true then?

**Review by tbg — COMMENTED** [review]
Yes, I wanted to leave some slack to avoid unnecessarily interfering. I should have added a comment. (Done).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-:-LguRLdJ7HDYbyKPCGPB:b-q6uonj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/server/version_cluster_test.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-LgsMu0u5I354YDaxENS:-LgsSwjR2BZqdzeT8ZMf:b-oqegva) ([raw file](https://github.com/cockroachdb/cockroach/blob/e669c0ab3115d9fbf47a08c5b3a6e0c51a06e35a/pkg/server/version_cluster_test.go#L520)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Were these tests only relevant to version 1.0, before we had upgrade logic? I'm surprised to see us removing them.
</blockquote></details>

You're right, one of them (joining an old node into a cluster) was removed erroneously (it was failing because of the automatic cluster upgrade that basically led to ignoring the min supported version). I fixed it up and reintroduced it. The other case (joining node is too new) can't be tested like this any more because the RPC handshake prevents the new node from accepting connections from old nodes (or establishing to them).
___
*[pkg/storage/replica_proposal.go, line 976 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-LgsO_MY2dxRFY63h-tL:-LguRK5t2hcemVPYslWj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/350f9b9c27856402b6d8abe578bd063378a35331/pkg/storage/replica_proposal.go#L976)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I guess we can close https://github.com/cockroachdb/cockroach/pull/33653 now. cc. @andreimatei 

There is an updated comment and test in that PR that you might want to port over to here.
</blockquote></details>

Done.
___
*[pkg/storage/stores.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38108#-LgsO4LgAO4dXm-dZ4bj:-LgsTrJO2zVtGFmaQgWm:bjrkzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e669c0ab3115d9fbf47a08c5b3a6e0c51a06e35a/pkg/storage/stores.go#L294)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it worth returning an error if this is true then?
</blockquote></details>

I meant to rename to `ReadVersionFromEngineOrZero`, but forgot. Note that the caller handles this gracefully. We could also signal that through an error, though it's a wash which one is better, so I kept the status quo.

**Comment by tbg** [comment]
TFTR!
bors r=nvanbenschoten

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Pull request merged**
