### PR TITLE
roachprod: create admin user and backup schedule for virtual clusters

### PR DESCRIPTION
**Pull request by renatolabs**
This commit updates `roachprod start{-sql}` and unifies the set of
steps performed on the cluster regardless of whether we are starting
the system tenant for the first time or creating a new tenant.

Specifically, tenants will also have an admin user configured and a
default backup schedule is created when `--schedule-backups` is passed.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Ran a couple of builds on this branch:

* [`0.1` run](https://teamcity.cockroachdb.com/viewLog.html?buildId=13878355&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel), to make sure the changes to `Start` didn't break anything obvious.
* [`multitenant` run](https://teamcity.cockroachdb.com/viewLog.html?buildId=13892999&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv), which includes all tests migrated to the new API. If we inspect the logs, we see that we now have default admin users and backup schedules both for the system tenants and for each tenant as well.

**Review by herkolategan — APPROVED** [review]
Nice! Thank for fixing this!

**Comment by renatolabs** [comment]
Rebased to fix conflicts with recent changes.

Worth noting is that I changed the default username/password combination from `roach:system` to `roachprod:cockroachdb`. The new username more directly reflects that this was setup by roachprod, and `system` as a password was a little strange, especially in non-UA contexts. `cockroachdb` is more generic (but open to other suggestions).

I'll run a few test runs on this branch, I'm curious if there were any other assumptions on the previous credentials that we missed.

**Comment by renatolabs** [comment]
Ran a [final run](https://teamcity.cockroachdb.com/viewLog.html?buildId=14013549&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv&branch_Cockroach_Nightlies=118851) on this branch; failures are unrelated and also happen on master.

TFTR!

bors r=herkolategan

**Comment by renatolabs** [comment]
This has been running without problems on master, so I'll attempt to backport it.

blathers backport 23.2 23.1

**Pull request merged**
