### PR TITLE
Added --raft-tick-interval flag to the cockroach start command

### PR DESCRIPTION
**Pull request by d4l3k**
This adds a flag so the raft tick interval is configurable via the command line.

See #6105 

I'm not entirely this is the right approach since it duplicates the `RaftTickInterval` param in `server.Context` and `storage.StoreContext`. However, the alternative would mean the StoreContext would be created earlier creating a much bigger change.

Also, is this something that I should be adding a test for?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6590)

### CODE REVIEW

**Comment by tschottdorf** [comment]
I think this is fine (it happens in the same way for some other flags already), at least for now.

<details><summary><i>Previously, CLAassistant wrote…</i></summary>
> [CLA assistant check](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=6590) <br/>All committers have signed the CLA.</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cli/flags.go, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-KHMUaCWE2vhz3SEd7a8:-KHMUaCWE2vhz3SEd7a9:-977036083) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a98f87f3a47c2c8486d8517dfea54f3e39bd74b/cli/flags.go#L228)):*
> ```Go
> 	cliflags.RaftTickIntervalName: wrapText(`
> RaftTickInterval is the resolution of the Raft timer; other raft timeouts are
> defined in terms of multiples of this value.`),
> ```

Do we really want to expose this as a user-visible flag? I would've expected this to be handled like the other internal knobs in `func (ctx *Context) readEnvironmentVariables()`.

---

*[server/server.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-KHMU7o9MWc2azgXJxN6:-KHMU7o9MWc2azgXJxN7:-1841024009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a98f87f3a47c2c8486d8517dfea54f3e39bd74b/server/server.go#L218)):*
> ```Go
> 			AllowRebalance: true,
> 		},
> 		RaftTickInterval: ctx.RaftTickInterval,
> ```

Group this up with the other values taken from `s.ctx` above (they're all similar internalish knobs).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-:-KHMUptBkMnVF98Tdvek:-653848843)*

**Comment by tamird** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cli/flags.go, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-KHMUaCWE2vhz3SEd7a8:-KHMYkNvOY7-9mdRhKWh:1407762401) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a98f87f3a47c2c8486d8517dfea54f3e39bd74b/cli/flags.go#L228)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Do we really want to expose this as a user-visible flag? I would've expected this to be handled like the other internal knobs in `func (ctx *Context) readEnvironmentVariables()`.</details>
Came here to say this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590)*

**Comment by d4l3k** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cli/flags.go, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-KHMUaCWE2vhz3SEd7a8:-KHMWMR9A6TtZp5p4Qxw:1200946086) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a98f87f3a47c2c8486d8517dfea54f3e39bd74b/cli/flags.go#L228)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Do we really want to expose this as a user-visible flag? I would've expected this to be handled like the other internal knobs in `func (ctx *Context) readEnvironmentVariables()`.</details>
That makes a lot of sense. I didn't realize that was something that already existed.

---

*[server/server.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-KHMU7o9MWc2azgXJxN6:-KHMWdBa_CmHfi06WzLt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a98f87f3a47c2c8486d8517dfea54f3e39bd74b/server/server.go#L218)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Group this up with the other values taken from `s.ctx` above (they're all similar internalish knobs).</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590)*

**Comment by tschottdorf** [comment]
As far as testing goes - if there's anything for the other comparable variables, your new one should get the same coverage (i.e. likely updating an existing test slightly).

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I think this is fine (it happens in the same way for some other flags already), at least for now.</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-:-KHM_KNT7CByXnK9ZekZ:1947824197)*

**Comment by d4l3k** [comment]
I reworked the flag to be an environment variable.

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> As far as testing goes - if there's anything for the other comparable variables, your new one should get the same coverage (i.e. likely updating an existing test slightly).</details>


---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-:-KHMdhXe5AIZwR6Mqhfy:-1868089138)*

**Comment by BramGruneir** [comment]
:lgtm:

<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> I reworked the flag to be an environment variable.</details>


---

Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-:-KHMuYWDZilvYSKhXkmy:1417088721)*

**Comment by tschottdorf** [comment]
:lgtm:!

<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6590#-:-KHN2lMpebT2FemgXMGI:980077424)*

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/286

**Pull request merged**
