### PR TITLE
kvserver,rac2,replica_rac2: add Scheduler.ScheduleControllerEvent

### PR DESCRIPTION
**Pull request by sumeerbhola**
It is implemented using raftScheduler. It will be used for both force-flush and when a send-queue has tokens.

Informs #130433

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
This lacks tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-:-O89ArAh8wZA8CjsR2CE:bfpv8ic)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — COMMENTED** [review]
Approach :lgtm:  -- I'll do another quick pass once the tests are in.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-:-O89L-_u7g1bh44ysfUA:bg4hhx7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O89K3rd4TYJViFk2ZUE):*
nit: for
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O89Kchw8C9VtnoxriXz:-O89Kchx0N3y64NLyzKY:b-mhkwlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e556ece2a2052c1369febf2086d804c11ebf97b/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1088)):*
> ```Go
> 			rc.scheduledMu.Lock()
> 			defer rc.scheduledMu.Unlock()
> 			if len(rc.scheduledMu.replicas) == 0 {
> ```

nit: this probably warrants a comment, is it to schedule an event only when the map is becoming non-empty?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O89KpM25l3iazlEh2eu:-O89KpM25l3iazlEh2ev:b-hd8rjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e556ece2a2052c1369febf2086d804c11ebf97b/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L1078)):*
> ```Go
> 		return
> 	}
> 	if p.leader.rc != nil {
> ```

What did this missing check trip up?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

Tests are ready.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-:-O8D2VgbEaiLUpuKdJgV:b-82eeri)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O89K3rd4TYJViFk2ZUE):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: for
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O89Kchw8C9VtnoxriXz:-O8Cp2yb1fJ17HH5uV7k:bwv9egz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e556ece2a2052c1369febf2086d804c11ebf97b/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1088)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: this probably warrants a comment, is it to schedule an event only when the map is becoming non-empty?
</blockquote></details>

Correct. Added comments.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O89KpM25l3iazlEh2eu:-O8Cpcs3Eg_JMxVKxQGr:bv6gys8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e556ece2a2052c1369febf2086d804c11ebf97b/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L1078)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

What did this missing check trip up?
</blockquote></details>

Just happened to see it and added it as a defensive thing. We do this everywhere else in this file.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-:-O8DLPGz5RhpyHa5KFdc:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 1203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O8DLVd27qj0A1uDbOHi:-O8DLVd27qj0A1uDbOHj:b-gxxke4) ([raw file](https://github.com/cockroachdb/cockroach/blob/467805e829310d8583072defe97f52ed5bcb1035/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L1203)):*
> ```Go
> 				d.ScanArgs(t, "range_id", &rangeID)
> 				testRC := state.ranges[roachpb.RangeID(rangeID)]
> 				testRC.rc.HandleSchedulerEventRaftMuLocked(ctx)
> ```

The err returned here needs to be handled for CI.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131715)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 1203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O8DLVd27qj0A1uDbOHi:-O8DQCuZCcHHN3otChja:b-ngehst) ([raw file](https://github.com/cockroachdb/cockroach/blob/467805e829310d8583072defe97f52ed5bcb1035/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L1203)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The err returned here needs to be handled for CI.
</blockquote></details>

I've removed the error return since it was always nil and even `processorImpl` was ignoring it.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-:-O8DS2fA0uv3UCq5GQG9:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 1203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131715#-O8DLVd27qj0A1uDbOHi:-O8DS1zh6y-ZNdwYAhkr:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/467805e829310d8583072defe97f52ed5bcb1035/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L1203)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I've removed the error return since it was always nil and even `processorImpl` was ignoring it.
</blockquote></details>

sgtm

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
