### PR TITLE
deps: bump cockroachdb/errors

### LINKED ISSUE #49752: *: make errors.New / errors.Wrap assume their string argument is safe for reporting
This is discussed in https://github.com/cockroachdb/cockroach/pull/49660#issuecomment-635879096

- today `errors.New` / `errors.Wrap` assume their string argument is not safe for reporting; and the caller should call `errors.Newf("%v", errors.Safe(...))` to manually mark strings a safe.

- as discussed in the linked thread, we want change the API contract so that the two constructors take safe strings instead. 

The benefits are 1) convenience 2) automatically makes most sentinel errors reportable.

### PR DESCRIPTION
**Pull request by knz**
Two changes here:

First change enhances the clarity of Sentry reports. See https://github.com/cockroachdb/errors/pull/43 for details.

Second change:

This updates to the new major release v1.6.
See release notes here: https://github.com/cockroachdb/errors/releases/tag/v1.6.0

This makes the string argument to New() and Wrap()
reportable to Sentry. This is now safe in CockroachdB
since the introduction of linters that assert
that their argument is a literal string.

**This code is not safe to back-port to previous release
branches unless the corresponding linters are also
back-ported and report the code is clean.**

Fixes #49752

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
LGTM, I haven't looked at cockroachdb/errors#43 however so let me know if I should.

**Comment by knz** [comment]
feel free to. However I am going to ad a 2nd commit to this PR, and I'd like you to review it as well. Will ping you when that occurs.

**Comment by knz** [comment]
@irfansharif RFAL.

**Comment by irfansharif** [comment]
LGTM, will this be closing out #49752?

**Comment by knz** [comment]
>  will this be closing out #49752?

yes

I am expecting two tests to fail in CI. If they don't I'll add the missing tests. If they do, I'll fix them.

**Comment by knz** [comment]
bors r=irfansharif

**Pull request merged**
