### PR TITLE
sql: metadata-mutating operations wait for gossip in tests

### LINKED ISSUE #2699: sql: stale metadata in logic_test
The following test appears to have failed:

[#8075](https://circleci.com/gh/cockroachdb/cockroach/8075):

```
tefce914d  127.0.0.1:0  17:32:49.423069  24.686µs     ·meta descriptor lookup       kv/dist_sender.go:510
tefce914d  127.0.0.1:0  17:32:49.423116  11.248288ms  ·sending RPC                  kv/dist_sender.go:424
tefce914d  127.0.0.1:0  17:32:49.423267  0            ··sending to 127.0.0.1:42792  rpc/send.go:156

I0928 17:32:49.440227 855 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- FAIL: TestLogic (4.33s)
	logic_test.go:393: testdata/database:52: expected "database \"b\" does not exist", but found success
=== RUN   TestPrivilege
--- PASS: TestPrivilege (0.02s)
=== RUN   TestPrivilegeValidate
--- PASS: TestPrivilegeValidate (0.01s)
=== RUN   TestSystemPrivilegeValidate
--- PASS: TestSystemPrivilegeValidate (0.01s)
=== RUN   TestRenameTable
I0928 17:32:49.489689 855 rpc/clock_offset.go:154  monitoring cluster offset
I0928 17:32:49.490004 855 multiraft/multiraft.go:442  node 100000001 starting
--
--- PASS: TestValidateTableDesc (0.00s)
=== RUN   TestColumnTypeSQLString
--- PASS: TestColumnTypeSQLString (0.00s)
=== RUN   TestInitialKeys
--- PASS: TestInitialKeys (0.00s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	11.099s
=== RUN   TestNoLinkForbidden
--- PASS: TestNoLinkForbidden (1.06s)
=== RUN   TestPlaceholders
I0928 17:32:44.969158 863 rpc/clock_offset.go:154  monitoring cluster offset
I0928 17:32:44.975928 863 multiraft/multiraft.go:442  node 100000001 starting
I0928 17:32:44.976829 863 raft/raft.go:406  group 1 100000001 became follower at term 5
I0928 17:32:44.977112 863 raft/raft.go:219  group 1 newRaft 100000001 [peers: [100000001], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0928 17:32:44.977485 863 raft/raft.go:485  group 1 100000001 is starting a new election at term 5
I0928 17:32:44.977669 863 raft/raft.go:419  group 1 100000001 became candidate at term 6
I0928 17:32:44.977836 863 raft/raft.go:468  group 1 100000001 received vote from 100000001 at term 6

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #2699.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3099)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[sql/executor.go, line 332 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2oGP-F7vG9mx7GxaXy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/executor.go#L332)):</sup>
Since this is only for testing, I might set the `MaxBackoff` to 100ms.


---

<sup>**[sql/rename.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2oGrpAPo2pH7czT_Dq)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/rename.go#L88)):</sup>
It's not clear looking at this code that it is only used for testing. Perhaps you should wrap in `if testingWaitForMetadata {`. Not as an optimization, but for clarity.


---

<sup>**[sql/rename.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2oHFVjLHEm6WewKkIb)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/rename.go#L207)):</sup>
Seems like there is a bunch of code duplication between the various `verifyMetadata` closures. Can a `planner.verifyDescriptor(descID, descDesc)` be written?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tamird** [comment]
This got a pretty major update, PTAL!


---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[sql/executor.go, line 332 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2oGP-F7vG9mx7GxaXy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/executor.go#L332)):</sup>
Used a condition variable instead.


---

<sup>**[sql/rename.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2oGrpAPo2pH7czT_Dq)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/rename.go#L88)):</sup>
I renamed the function to `testingVerifyMetadata`, instead.


---

<sup>**[sql/rename.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2oHFVjLHEm6WewKkIb)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/rename.go#L207)):</sup>
I don't think so, or at least I don't think it's worth it. Happy to hear some suggestions though.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tschottdorf** [comment]
Reviewed 6 of 6 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[sql/descriptor.go, line 119 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2re808hNLEgGXjL6O7)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/descriptor.go#L119)):</sup>
I personally think these would be more legible if some of the checks were inversed:

```go
v := systemConfig.GetValue(key)
if v == nil {
  return errStaleMetadata
}
```


---

<sup>**[sql/executor.go, line 110 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rf6VPEtLifbGrUyvN)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L110)):</sup>
what's wrong with the old code?


---

<sup>**[sql/executor.go, line 325 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rfFFT3GnE9QrP1n7c)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L325)):</sup>
s/^w/W/


---

<sup>**[sql/executor.go, line 326 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rg6Rn_N6U5vgNcVuL)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L326)):</sup>
It's a bit weird that we would alter the possible concurrency during tests. What happens without this? It seems that the verification code should be fine either way.


---

<sup>**[sql/table.go, line 241 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rfiCAPsDrs55tkez3)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/table.go#L241)):</sup>
can't a `nil` `systemConfig` just return `nil` for everything?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[sql/descriptor.go, line 119 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2re808hNLEgGXjL6O7)** ([raw file](https://github.com/cockroachdb/cockroach/blob/8c870aa9b9321abb80413bf2ce822e27e09d3693/sql/descriptor.go#L119)):</sup>
Done.


---

<sup>**[sql/executor.go, line 110 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rf6VPEtLifbGrUyvN)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L110)):</sup>
Anecdotal, but in simple functions like this, runtime of the function is dominated by the `defer`.


---

<sup>**[sql/executor.go, line 325 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rfFFT3GnE9QrP1n7c)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L325)):</sup>
Done.


---

<sup>**[sql/executor.go, line 326 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rg6Rn_N6U5vgNcVuL)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L326)):</sup>
Yes, but we get a stronger assurance this way. Take a look at the verification code: it also asserts that a gossip update was indeed required to make the verification pass, which is an important protection against rot.


---

<sup>**[sql/table.go, line 241 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rfiCAPsDrs55tkez3)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/table.go#L241)):</sup>
If we want that behaviour, we're better off using a `SystemConfig` rather than a `*SystemConfig`. I've changed all uses in `sql` to use the value, rather than a pointer.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tschottdorf** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[sql/executor.go, line 326 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rg6Rn_N6U5vgNcVuL)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L326)):</sup>
I see that, but couldn't you just copy (hash? grab version of?) the system config when the verification closure is created, and fail unless it changes?
My concern is that locking gossip updates during your operation can hide bugs (for example, grabbing the systemConfig at two different times and assuming that they are the same thing).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[sql/executor.go, line 326 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2rg6Rn_N6U5vgNcVuL)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b7035b3da02afa7ca19b0f33cbffe166c0552290/sql/executor.go#L326)):</sup>
Added a comment to explain why this is safe.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tschottdorf** [comment]
LGTM

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tamird** [comment]
@petermattis any remaining concerns?

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[sql/rename.go, line 114 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2sieppMAeE0yGxypzM)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddfe4c9077ecfcc4b73fdd80a0146cea0bc86f/sql/rename.go#L114)):</sup>
Seems like there is a lot of code shared with this closure and the one in `descriptor.go`. Is there really nothing that can be shared? Something like `expectDescriptorID(systemConfig, newKey, descID); expectDescriptor(systemConfig, descKey, descDesc); ..`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by vivekmenezes** [comment]
In WIP PR https://github.com/cockroachdb/cockroach/pull/2874 we pass the ID of the mutation created by a command, through transaction in the session object,  back to the executor, who then waits until the mutation with the mutation id has been removed from the table descriptor by the table leader. This mutation id is passed from one request to the next until the executor sees a COMMIT, which runs the wait for mutation to complete. This is needed outside of tests because we think we want commands that run schema changes to wait until they are complete even if they take hours.

Perhaps a similar kind of messaging framework is needed here.


---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[sql/executor.go, line 109 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2tjPzh_gOYNvaMjOAe)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddfe4c9077ecfcc4b73fdd80a0146cea0bc86f/sql/executor.go#L109)):</sup>
so its not safe to return this value and use a deferred unlock?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tamird** [comment]
@vivek: I'm not entirely sure how such a framework would help us here. Want to discuss in person?


---

Review status: 3 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[sql/executor.go, line 109 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2tjPzh_gOYNvaMjOAe)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddfe4c9077ecfcc4b73fdd80a0146cea0bc86f/sql/executor.go#L109)):</sup>
No, it's safe, but in trivial cases like this one performance is dominated by the `defer` mechanism. This change is just a drive-by optimisation


---

<sup>**[sql/rename.go, line 114 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099#-K2sieppMAeE0yGxypzM)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddfe4c9077ecfcc4b73fdd80a0146cea0bc86f/sql/rename.go#L114)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by vivekmenezes** [comment]
Let's discuss in person when we meet. I like the ideas in this PR very much but do not like the idea that the callback cannot be called on the latest version of the global config. If I were to use the callback mechanism in my PR, i'd make it such that it can be called on the latest version of the global config, which allows us to not freeze up gossip while we run the transaction.


---

Review status: 3 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Comment by tamird** [comment]
As discussed in person, going to leave things here as they are. Freezing gossip is an important rot-defense here.


---

Review status: 3 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3099)

**Pull request merged**
