### PR TITLE
roachtest: save timeseries dumps as artifacts

### PR DESCRIPTION
**Pull request by tbg**
- roachtest: minor logging improvements
- roachtest: fetch timeseries dump on failed tests

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 1669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65709#-MacGFoV1BTguJWHYGVo:-MacGFoV1BTguJWHYGVp:b-ho3nun) ([raw file](https://github.com/cockroachdb/cockroach/blob/35778ec531be5261b6603e676b0591786b20c787/pkg/cmd/roachtest/cluster.go#L1669)):*
> ```Go
> 				c.l.Printf("while fetching timeseries: %s", err)
> 			} else {
> 				err = c.Get(ctx, c.l, "tsdump.gob", filepath.Join(c.t.ArtifactsDir(), "tsdump.gob"), c.Node(i))
> ```

Shouldn't we output this error if non-nil?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/cmd/roachtest/cluster.go, line 1669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65709#-MacGFoV1BTguJWHYGVo:-MacTM5r7pH1yZD43D3q:bt5fk6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/35778ec531be5261b6603e676b0591786b20c787/pkg/cmd/roachtest/cluster.go#L1669)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Shouldn't we output this error if non-nil?
</blockquote></details>

Whoops, yes, this code was spaghetti. Updated.

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65709#-:-MacU5jXEjsaJ7jXpigM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
timeout in lint, filed #65715
bors r=erikgrinaker

**Comment by tbg** [comment]
hold on local CI also failed

bors r-

**Comment by tbg** [comment]
not my fault, see [slack](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1622032083029400)

```
patchelf --set-rpath '/usr/local/lib/cockroach/' lib/libgeos_c.so
CMake Error at CMakeLists.txt:20 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/c++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/go/native/x86_64-pc-linux-gnu/protobuf/CMakeFiles/CMakeOutput.log".
See also "/go/native/x86_64-pc-linux-gnu/protobuf/CMakeFiles/CMakeError.log".
make[1]: *** [Makefile:5196: cmake_check_build_system] Error 1
make: *** [Makefile:726: /go/native/x86_64-pc-linux-gnu/protobuf/protoc] Error 2
make: *** Waiting for unfinished jobs....
```

bors r=erikgrinaker

**Pull request merged**
