### PR TITLE
sql: hopefully reduce the memory usage of TestDropWhileBackfill

### PR DESCRIPTION
**Pull request by vivekmenezes**
related to #28084

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@dt I'd like to see if this will fix the broken test. Any chance you an take a look? Thanks

**Review by dt — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28145)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by vivekmenezes** [comment]
TFTR!

**Pull request merged**
