### PR TITLE
server, storage, ui: Add command queue metrics to the range debug page

### PR DESCRIPTION
**Pull request by BramGruneir**
This adds write_commands, read_commands, max_overlaps_seen and tree_size for both local and global command queues.

Part of #9797.

screen shot 2017-08-31 at 00 58 52

### CODE REVIEW

**Comment by tschottdorf** [comment]
These metrics are all-time, right? Then this may not be so useful -- when looking at the range page, we'd be interested more in a current snapshot. `write_commands` and `read_commands` as an ever-increasing counter kind of work -- you can refresh the page and guess at the rate at which they're growing -- but `max_overlaps_seen` isn't useful once it's large as then you don't know whether that's happening now or happened ten days ago.

Some of the existing fields have similar problems (Raft dropped cmds, etc), but those are counters, so you can work around it -- tracking a max is more difficult.

Apologies if these metrics aren't all-time -- I've only skimmed the diff. Either way, great to see work in this area! I've often wondered about the command queue internals.

**Comment by BramGruneir** [comment]
max_overlaps_seen is of all time, but all the rest are current. 

When a new command is added, it is added to read or write.
When a command is removed, it is subtracted from them.  Take a look at the `remove` function in the command queue.

tree_size is also current, however unlike the others, it is calculated on the fly.

**Comment by tschottdorf** [comment]
Cool, so only max overlaps is awkward. I'm sure it's still better than not having it. Thanks for the clarifications!

**Comment by nvanbenschoten** [comment]
Reviewed 7 of 12 files at r1.
Review status: 7 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 5334 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067#-Kst_ZpuCcEuHlFaKv6Z:-Kst_ZpuCcEuHlFaKv6_:bv5ritc) ([raw file](https://github.com/cockroachdb/cockroach/blob/974aa52b2289be51b635778dd97c4f93708ab808/pkg/storage/replica.go#L5334)):*
The locking notes on `Replica.cmdQMu` say:

> Locking notes: Replica.mu < Replica.cmdQMu

Since we don't want to risk getting an inconsistent metric state, let's put this lock inside `r.mu.RLock()`.

---

*[pkg/storage/replica.go, line 5335 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067#-Kst_pRvtqUsF_-AJxSM:-Kst_pRvtqUsF_-AJxSN:b-6djpaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/974aa52b2289be51b635778dd97c4f93708ab808/pkg/storage/replica.go#L5335)):*
> ```Go
> 
> 	r.cmdQMu.Lock()
> 	commandQueueMetricsLocal := r.cmdQMu.queues[spanLocal].metrics()
> ```

nit everywhere: we generally use variables called `cmdQ` instead of `commandQueue`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067)*

**Comment by BramGruneir** [comment]
Comments addressed.

Here's an updated view:


---

Review status: 2 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 5334 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067#-Kst_ZpuCcEuHlFaKv6Z:-KstiXNnuExZ2Mfjmnvi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/974aa52b2289be51b635778dd97c4f93708ab808/pkg/storage/replica.go#L5334)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The locking notes on `Replica.cmdQMu` say:

> Locking notes: Replica.mu < Replica.cmdQMu

Since we don't want to risk getting an inconsistent metric state, let's put this lock inside `r.mu.RLock()`.
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 5335 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067#-Kst_pRvtqUsF_-AJxSM:-KstiXjyOAGf4235Wnog:b-an0ur8) ([raw file](https://github.com/cockroachdb/cockroach/blob/974aa52b2289be51b635778dd97c4f93708ab808/pkg/storage/replica.go#L5335)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit everywhere: we generally use variables called `cmdQ` instead of `commandQueue`.
</blockquote></details>

Done.

I've kept the proto message type as CommandQueueMetrics, but everything else has been shortened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067#-:-KstoycCerTGUe5BBZK2:b6pp4jo)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 2 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067#-:-KsuJ_BZ_QtIbK5BEBiw:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
:lgtm: Thanks Bram!

---

Review status: 2 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18067#-:-KsuKPiNrHMlYiF2mhQQ:b-51rtoj)*

**Pull request merged**
