### PR TITLE
release-2.1: backport all of the acceptance -> roachtest changes

### PR DESCRIPTION
**Pull request by petermattis**
Backport:
  * 1/1 commits from "roachtest: fix two buglets in gossip/chaos" (#29345)
  * 2/2 commits from "roachtest: add acceptance/build-info" (#29437)
  * 7/7 commits from "roachtest: add acceptance/bank/{cluster-recovery,node-restart}" (#29449)
  * 6/6 commits from "roachtest: add acceptance/gossip/*" (#29465)
  * 1/1 commits from "roachtest: add acceptance/version-upgrade" (#29470)
  * 1/1 commits from "roachtest: deflake acceptance/status-server" (#29492)
  * 1/1 commits from "roachtest: fix acceptance/version-upgrade on remote clusters" (#29544)
  * 2/2 commits from "roachtest: add acceptance/decommission" (#29488)
  * 2/2 commits from "roachtest: add acceptance/cluster-init" (#29493)
  * 1/1 commits from "roachtest: fix acceptance/decommission on remote clusters" (#29576)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM and thanks! (don't forget: green button)

**Comment by petermattis** [comment]
Hmm, another CI problem with `github-pull-request-make`.

**Review by benesch — APPROVED** [review]

**Comment by petermattis** [comment]
Hmm, `github-pull-request-make` is doing the right thing if I check out this branch.

**Comment by petermattis** [comment]
I liked, no it isn't. It sees `TestDecommission` in the `build` package and the top-level `build` package has no Go source code.

**Comment by petermattis** [comment]
@benesch I added another commit here which I think fixes the `github-pull-request-make` problem. PTAL. I'll have to forward port that commit to master.

**Comment by petermattis** [comment]
> I added another commit here which I think fixes the github-pull-request-make problem. 

Yep, definitely fixes the problem.

**Review by benesch — APPROVED** [review]
Still LGTM

**Pull request merged**
