### PR TITLE
sql: implement ConstructOpaque in the new factory

### PR DESCRIPTION
**Pull request by yuzefovich**
Addresses: #47473.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52163#-:-ME2lbOh9z3iINrRY2E3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by adityamaru** [comment]
@yuzefovich apologies I caused bors to get Canceled cause I forgot to wait for Github CI, you might have to give it another shot.

**Comment by yuzefovich** [comment]
@adityamaru no worries, thanks for letting me know. Sometimes I find myself in a similar boat and usually ping bors to merge the canceled PR myself.

bors r+

**Comment by adityamaru** [comment]
> usually ping bors to merge the canceled PR myself

TIL, will do next time!

**Comment by yuzefovich** [comment]
bors seems to have crashed

bors r+

**Pull request merged**
