### PR TITLE
sql: unify crdb_internal.invalid_objects contents with doctor

### LINKED ISSUE #55219: Share the code between implementation of doctor tool and `crdb_internal.invalid_objects`
**Describe the problem**

Recently we have introduced two tools for detecting sql internal data inconsistencies: [`cockroach debug doctor`](https://github.com/cockroachdb/cockroach/pull/52622) and [`crdb_internal.invalid_objects`](https://github.com/cockroachdb/cockroach/pull/54017). This is a meta-issue that describes future ideas for improving these tools and more specifically how to share code between them.

***Background***

The doctor tool performs consistency checks on the client side (either reading from a live cluster or a debug zip). This is handy for fast development and deployment of new checks and for supporting old cockroach releases. Its main drawback is that it is cumbersome to use for internal sever-side checks or in tests or logic tests.

The internal table so far detects invalid objects only via the descriptor `Validate` function. The table is very useful for checking the consistency of internal objects using a sql expression and these checks can easily be embedded in tests. The table is also automatically included in debug zips which means that as old releases are phased out it will duplicate most of the doctor tool checks.

***Future plans***

The main idea is that new checks will be first implemented and perfected via the doctor tool and eventually will find their way in the `crdb_internal.invalid_objects` table or other internal tables - one can imagine a similar table for troublesome jobs.

To that end it is important to share as much error checking code between the two tools. Currently only the implementation of table validation is shared.

***Proposals***

* [x] 1. Develop interface similar to `catalog.DescGetter` for querying the state of the namespace mapping.

* We should also consider adding some cheap namespace checks to descriptor validation.

* [x] 2. Refactor function `doctor.ExamineDescriptors` to use descriptor and namespace getters instead of the raw contents of the descriptor and namespace tables. 
 
* This will require adding ability to iterate over all descriptors in `DescGetter`.

*  [x] 3. Add namespace invalid objects to `crdb_internal.invalid_objects` that are currently only detected in `doctor.ExamineDescriptors`.

* Descriptors ids pointed to in the namespace map that no longer exist.
* Draining names entries in the descriptor table.

* [x] 4. Add descriptor ids that are pointed to from jobs but no longer exist to `crdb_internal.invalid_objects`.
* This check is currently implemented only in `doctor.ExamineJobs`.

### LINKED ISSUE #55978: doctor: detect orphaned schema change jobs
**Is your feature request related to a problem? Please describe.**

The doctor tool should be able to look at the jobs in `MutationJobIDs` and determine if any of them are in a terminal state.

### PR DESCRIPTION
**Pull request by postamar**
sql: unify crdb_internal.invalid_objects contents with doctor
    
    Previously, this table would only contain one validation error per
    object (i.e. table or type descriptor). Furthermore it would not contain
    any namespace or job validation errors for these descriptors.
    
    This patch addresses these shortcomings to make this table contain the
    same data that doctor would output for descriptor checks. Furthermore
    this patch expands the check suite with checks for:
    - jobs referenced in descriptors, to detect orphaned schema change jobs,
    - descriptors referenced in jobs.
    
    Fixes #55219.
    Fixes #55978.
    
    Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-:-MX7dDyc3qrtJ9hmOukk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/catalog/desc_getter.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MX7avW-3-QnAY5rT4g9:-MX7avW0C6ay7b6uk6VK:bm3n598) ([raw file](https://github.com/cockroachdb/cockroach/blob/c81f8842bec6c169028db8ce7d5a97507f9b4b12/pkg/sql/catalog/desc_getter.go#L77)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	set := MakeDescriptorIDSet()
> 	for id := range m.Descriptors {
> 		set.Add(id)
> 	}
> 	ids := set.Ordered()
> 	ret := make([]Descriptor, len(ids))
> 	for j, id := range ids {
> 		ret[j] = m.Descriptors[id]
> 	}
> 	return ret
> ```
</details>

use `catalog.Descriptors`

```
ret := make([]Descriptor, len(ids))
for _, d := range m.Descriptors {
    ret = append(ret, d)
}
sort.Sort(Descriptors(ret))
return ret
```
___
*[pkg/sql/catalog/catalogkv/catalogkv.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MX7d2wf9p-1N2fWR_WT:-MX7covPA_y5o-ZB-hr-:b-4i1ie4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c81f8842bec6c169028db8ce7d5a97507f9b4b12/pkg/sql/catalog/catalogkv/catalogkv.go#L257)):*
> ```Go
> 	ctx context.Context, txn *kv.Txn, codec keys.SQLCodec, withNamespace bool,
> ) (m catalog.MapDescGetter, err error) {
> 	if withNamespace {
> ```

These virtual tables are a memory accounting nightmare

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62803)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @postamar)

___
*[pkg/sql/catalog/desc_getter.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MX7avW-3-QnAY5rT4g9:-MX7m5Kg8DHHoxGSqFWI:bvhrzas) ([raw file](https://github.com/cockroachdb/cockroach/blob/c81f8842bec6c169028db8ce7d5a97507f9b4b12/pkg/sql/catalog/desc_getter.go#L77)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	set := MakeDescriptorIDSet()
> 	for id := range m.Descriptors {
> 		set.Add(id)
> 	}
> 	ids := set.Ordered()
> 	ret := make([]Descriptor, len(ids))
> 	for j, id := range ids {
> 		ret[j] = m.Descriptors[id]
> 	}
> 	return ret
> ```
use `catalog.Descriptors`

```
ret := make([]Descriptor, len(ids))
for _, d := range m.Descriptors {
    ret = append(ret, d)
}
sort.Sort(Descriptors(ret))
return ret
```
</blockquote></details>

whoops, this is wrong. Needs either a 0 in the `make` call or some indexing

**Comment by postamar** [comment]
I didn't notice that either but the testing did! Thanks for pointing it out.

**Comment by postamar** [comment]
I'll fix these merge conflicts as soon as https://github.com/cockroachdb/cockroach/pull/62878 is merged.

**Review by postamar — COMMENTED** [review]
I re-opened and pushed with resolved conflicts. This didn't involve any changes of significance.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-:-MXbsrKVEuqZKdgMI5vj:b-7l3g08)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/catalog/desc_getter.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MX7avW-3-QnAY5rT4g9:-MXbshdO9z_-R6b79mCx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c81f8842bec6c169028db8ce7d5a97507f9b4b12/pkg/sql/catalog/desc_getter.go#L77)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

whoops, this is wrong. Needs either a 0 in the `make` call or some indexing
</blockquote></details>

Done.

**Comment by postamar** [comment]
I took a stab at #55978 today and found that those changes were best integrated into these. Assuming that CI doesn't complain too much this is ready for another look.

**Review by ajwerner — CHANGES_REQUESTED** [review]
Needs some cleanup but nice

> Reviewed 7 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-:-MXeb2Ia5jsCYdJgs1zt:bdlh41o)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/jobs/validate.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MXeaJPRA-wB03iH6o9K:-MXeaJPS2BVS1Elx_Adh:baof1b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/be40ace979267fd44fa99328959609ae221a8a9f/pkg/jobs/validate.go#L1)):*
> ```Go
> package jobs
> ```

copyright
___
*[pkg/jobs/validate.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MXeaLWS4Z9PFiDhWUOV:-MXeaLWS4Z9PFiDhWUOW:b-jrxcue) ([raw file](https://github.com/cockroachdb/cockroach/blob/be40ace979267fd44fa99328959609ae221a8a9f/pkg/jobs/validate.go#L11)):*
> ```Go
> )
> 
> func ValidateJobReferencesInDescriptor(
> ```

comment
___
*[pkg/jobs/validate.go, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MXeaSiYEB82QEzZ3LOM:-MXeaSiYEB82QEzZ3LON:b49fbp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/be40ace979267fd44fa99328959609ae221a8a9f/pkg/jobs/validate.go#L12)):*
> ```Go
> 
> func ValidateJobReferencesInDescriptor(
> 	desc catalog.Descriptor, jobMap map[int64]JobMetadata, errorAccFn func(error),
> ```

jobspb.JobID here? I know there were some circular dependencies elsewhere. 
___
*[pkg/jobs/validate.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MXeaMLF1UPvEf8kk5rB:-MXeaMLF1UPvEf8kk5rC:b-jrxcue) ([raw file](https://github.com/cockroachdb/cockroach/blob/be40ace979267fd44fa99328959609ae221a8a9f/pkg/jobs/validate.go#L35)):*
> ```Go
> }
> 
> func ValidateDescriptorReferencesInJob(
> ```

comment
___
*[pkg/sql/crdb_internal.go, line 4048 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MXeacTDABKOoag9pSE4:-MXeacTDABKOoag9pSE5:b-ahz60x) ([raw file](https://github.com/cockroachdb/cockroach/blob/be40ace979267fd44fa99328959609ae221a8a9f/pkg/sql/crdb_internal.go#L4048)):*
> ```Go
> }
> 
> func collectJobMap(ctx context.Context, p *planner) (map[int64]jobs.JobMetadata, error) {
> ```

`jobspb.JobID` in the map

**Comment by postamar** [comment]
Thanks, should be good now.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62803)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/sql/crdb_internal.go, line 4075 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MXiGXQM6FECC-kWzSeG:-MXiGXQM6FECC-kWzSeH:bz2xae1) ([raw file](https://github.com/cockroachdb/cockroach/blob/143da7414610428a9750219fa0149cba1f10cca7/pkg/sql/crdb_internal.go#L4075)):*
> ```Go
> 			md.Status = jobs.Status(*s)
> 		}
> 		md.Payload, err = jobs.UnmarshalPayload(payloadBytes)
> ```

I'm a bit concerned about memory usage here. I get that that may sound surprising given the cavalier nature of memory monitoring elsewhere. Jobs, unlike schema elements, have had a history of exploding. If you have a loop creating tables, your cluster tends to run into other problems because of zone configs. If you have a loop creating jobs, maybe jobs don't work well. In the general case, I don't really know how to solve this. In the short term, I'd feel content if we just accounted for these bytes as we streamed them into the map. That way we'll fail the query rather than oom.

**Comment by postamar** [comment]
Would you mind sharing an example of this accounting being done elsewhere? I've poked around a bit but I feel I'm stumbling in the dark.

**Comment by postamar** [comment]
RFAL

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62803)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/jobs/validate.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MYfMMmAEVbRWJY86sJS:-MYfMMmAEVbRWJY86sJT:bjqjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/87155ea45ca3a51a0e364da73835021a75856881/pkg/jobs/validate.go#L60)):*
> ```Go
> // ValidateDescriptorReferencesInJob checks a job for inconsistencies relative
> // to system.descriptor and passes any validation failures in the form of errors
> // to an accumulator function.
> ```

Maybe note that this only looks at GC jobs? Regular schema changes and type changes may also be interesting.
___
*[pkg/jobs/validate.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MYfLzUQEK1EHCvHewON:-MYfLzUR3qfBUcjfjJIS:b-5mdw8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/87155ea45ca3a51a0e364da73835021a75856881/pkg/jobs/validate.go#L64)):*
> ```Go
> 	j JobMetadata, descMap map[descpb.ID]catalog.Descriptor, errorAccFn func(error),
> ) {
> 	if j.Status != StatusRunning {
> ```

paused, pause-requested are interesting. 
___
*[pkg/sql/crdb_internal.go, line 4163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MYfMdAK3ijrTFvWDE-R:-MYfMdAK3ijrTFvWDE-S:blumvf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/87155ea45ca3a51a0e364da73835021a75856881/pkg/sql/crdb_internal.go#L4163)):*
> ```Go
> 			return err
> 		}
> 		acct := p.EvalContext().Mon.MakeBoundAccount()
> ```

Ideally you'd be growing the in-use memory incrementally as you add rows. Here it's all bufferred in RAM before you do the accounting; plumb the `acct` into `collectMarshaledJobMetadataMap`

**Comment by postamar** [comment]
Done & rebased on master, for recent doctor changes. Ready for another look.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-:-MYp_iIp6_6-Xklxh2Ka:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/jobs/validate.go, line 72 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62803#-MYp_LAjEV7z53X3mhj1:-MYp_LAjEV7z53X3mhj2:b2cj656) ([raw file](https://github.com/cockroachdb/cockroach/blob/57008c49333fec1ce32efe98b57375f134c69c4d/pkg/jobs/validate.go#L72)):*
> ```Go
> 	missing := catalog.MakeDescriptorIDSet()
> 	for _, id := range collectDescriptorReferences(j).Ordered() {
> 		_, tableExists := descMap[id]
> ```

nit: we use the descriptor field in the schema change job for more than just tables, maybe just call this `exists`?

**Comment by postamar** [comment]
Quite right! Done. 
Thanks for the review, I'm very happy with how this turned out in the end, much more thorough this way.

**Comment by postamar** [comment]
bors r+

CI failure is unrelated flake

**Pull request merged**
