### PR TITLE
changefeedccl: use pgx in sinkless changefeed tests

### PR DESCRIPTION
**Pull request by danhhz**
`rows.Close` hangs forever on a sinkless changefeed, but closing the
connection doesn't. Use pgx directly so we can manually close the conn
(database/sql only lets you return it to the pool).

I also looked at using lib/pq directly, but it's quite a bit more
annoying to use. Since this changes the underlying driver, I had to
tweak a couple tests that were accidentally relying on lib/pq specific
behavior.

Release note: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
LGTM but I don't know what the changes to the tests are about

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-:-LWIOGJM9DbQo3qhMl9V:b-1k1es2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIJS086cwbC1-fw3U8:-LWIJS086cwbC1-fw3U9:b2y6p5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/changefeed_test.go#L169)):*
> ```Go
> 		})
> 
> 		fooTime := f.Feed(t, `CREATE CHANGEFEED FOR foo WITH cursor=$1`, pq.FormatTimestamp(tsClock))
> ```

what's going on here?
Also, seems dubious that we use pq to format something. Sup with that?
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIJsoo1NU00UyZYIqI:-LWIJsoo1NU00UyZYIqJ:bz7iuxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/changefeed_test.go#L213)):*
> ```Go
> 		sqlDB := sqlutils.MakeSQLRunner(db)
> 		sqlDB.Exec(t, `CREATE TABLE foo (a INT PRIMARY KEY)`)
> 		sqlDB.Exec(t, `INSERT INTO foo VALUES (-1)`)
> ```

what's going on with the change to this test? Is this related to the helpers_test change?
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWINNEg8hWN-RvAixn9:-LWINNEg8hWN-RvAixnA:b-4kvii3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L287)):*
> ```Go
> 	// Use pgx directly instead of database/sql so we can close the conn
> 	// (instead of returning it to the pool). This allows us to work around an
> 	// issue where calling rows.Close on a changefeed stmt blocks forever.
> ```

similar: don't refer to rows.Close(), say that you want control over closing the connection
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWINtrP2av4zbNve3SX:-LWINtrP2av4zbNve3SY:b-vcnuwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L288)):*
> ```Go
> 	// (instead of returning it to the pool). This allows us to work around an
> 	// issue where calling rows.Close on a changefeed stmt blocks forever.
> 	pgxConfig, err := pgx.ParseConnectionString(url.String())
> ```

is this a connection to a secure server? Is so, would you do me a big favor and  use the same pattern in places where I've failed and created insecure servers cause I didn't know how to tell pgx about certs? Grep for "Andrei is too lazy".
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIMnMR2WxnTSRrbrAa:-LWIMnMR2WxnTSRrbrAb:bky3yc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L308)):*
> ```Go
> 
> type sinklessFeed struct {
> 	conn    *pgx.Conn
> ```

please put a comment on this struct
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIKbTJ8Rm_tXXanOi_:-LWIKbTJ8Rm_tXXanOia:b-765kj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L311)):*
> ```Go
> 	cleanup func()
> 	rows    *pgx.Rows
> 	queryID string
> ```

is this field still used?
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIKri6BoB07d_ax4Pm:-LWIKri6BoB07d_ax4Pn:b-6j4amz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L358)):*
> ```
> // TODO(dan): We should just be able to close the `gosql.Rows` but that
> // currently blocks forever.
> ```

Who says we should just be able to close the rows, and what change does "currently" want? :)
The golang docs are useless on the topic. You've see, of course, what libpq does - consumes all the (infinite) results.
As far as Postgres is concerned, there's no in-band signal that the client is done with a result set. In Postgres, it couldn't even be - I think Postgres doesn't read from the client until all the results are produced. That's why cancelation is an out-of-band signal.
For us, our implementation is more flexible and we could conceivably interpret some client signals as cancelation, but what those signals would be exactly is unclear. And regardless, without driver cooperation there's no point.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIN9whAm8iB5DhOH_r:-LWIN9whAm8iB5DhOH_s:b-jfd1qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L363)):*
> ```Go
> 		t.Error(err)
> 	}
> 	c.rows.Close()
> ```

I doubt this close is need by anything

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34035)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIKri6BoB07d_ax4Pm:-LWIPCtK6xDOHrh49uHQ:bt391o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L358)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> // TODO(dan): We should just be able to close the `gosql.Rows` but that
> // currently blocks forever.
> ```

Who says we should just be able to close the rows, and what change does "currently" want? :)
The golang docs are useless on the topic. You've see, of course, what libpq does - consumes all the (infinite) results.
As far as Postgres is concerned, there's no in-band signal that the client is done with a result set. In Postgres, it couldn't even be - I think Postgres doesn't read from the client until all the results are produced. That's why cancelation is an out-of-band signal.
For us, our implementation is more flexible and we could conceivably interpret some client signals as cancelation, but what those signals would be exactly is unclear. And regardless, without driver cooperation there's no point.


</blockquote></details>

Of course, resumable portals could also help - you could create a portal for the change feed, execute it with limit 1 time after time, and now after every result you have options for telling the server that you don't want more results - commit the txn.

**Review by danhhz — COMMENTED** [review]
TFTR! test changes are the tweaks I mentioned in the commit message where we were accidentally relying on lib/pq specific behavior. i've expanded on exactly which behaviors in the commit message

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-:-LWITQS7C-Nx89ZacYHO:b-uk0rsx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIJS086cwbC1-fw3U8:-LWITbDQ7UJx5YliF4nS:bnirxa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/changefeed_test.go#L169)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's going on here?
Also, seems dubious that we use pq to format something. Sup with that?
</blockquote></details>

mentioned this in the updated commit message. lib/pq was turning a time.Time into a Text for us, but pgx won't. I thought it'd be nice to keep this check around as faithfully as I could, but your skepticism has convinced me to just delete it instead.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIJsoo1NU00UyZYIqI:-LWITyf-0vBVghuRpbDJ:bp8gnks) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/changefeed_test.go#L213)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's going on with the change to this test? Is this related to the helpers_test change?
</blockquote></details>

mentioned this in the updated commit message, too. lib/pq was waiting until the first result came back from the server, so on the `CREATE CHANGEFEED FOR foo WITH updated, resolved` below more of the changefeed init code (including setting the changefeed-internal "statement timestamp") was being run before getting to the `afterFeed` line. this made one of the comparisons below flake.

turns out this -1 thing didn't work anyway. did it instead with a testing knob
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 383 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWJ-yyFA36OstnemORJ:-LWJ-yyFA36OstnemORK:b-xac06y) ([raw file](https://github.com/cockroachdb/cockroach/blob/007f1bcb047ce364b32cdd4aa670edfb2cda89cb/pkg/ccl/changefeedccl/changefeed_test.go#L383)):*
> ```Go
> 			renameColumn := f.Feed(t, `CREATE CHANGEFEED FOR rename_column`)
> 			defer renameColumn.Close(t)
> 			assertPayloads(t, renameColumn, []string{
> ```

this is another flake related to pgx returning before the first result and lib/pq not
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWINNEg8hWN-RvAixn9:-LWIUYjv8F26jisF6Rea:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L287)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

similar: don't refer to rows.Close(), say that you want control over closing the connection
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWINtrP2av4zbNve3SX:-LWIUZRfDlP0xmopbDlr:b-opshx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L288)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this a connection to a secure server? Is so, would you do me a big favor and  use the same pattern in places where I've failed and created insecure servers cause I didn't know how to tell pgx about certs? Grep for "Andrei is too lazy".
</blockquote></details>

Sure! Done
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIMnMR2WxnTSRrbrAa:-LWIX0um7eg6xv1k2TtW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L308)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please put a comment on this struct
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIKbTJ8Rm_tXXanOi_:-LWIXVeW6gPSlIymKqW8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L311)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this field still used?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIKri6BoB07d_ax4Pm:-LWIXXzm7Lz9y7XcSI8k:b3pkolf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L358)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Of course, resumable portals could also help - you could create a portal for the change feed, execute it with limit 1 time after time, and now after every result you have options for telling the server that you don't want more results - commit the txn.
</blockquote></details>

I'm not familiar with basically any of that but I trust your word on it. Removed given that it's clear from your comment that the amount of work we'd need to do this TODO is definitely not worth the incremental benefit now that you've pointed this "close the conn" thing out to me.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34035#-LWIN9whAm8iB5DhOH_r:-LWIXlwU9toj2rj3wY-4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc63064e42e00459e64e43d27ae3541864c4f0d/pkg/ccl/changefeedccl/helpers_test.go#L363)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I doubt this close is need by anything
</blockquote></details>

Done.

**Comment by danhhz** [comment]
ci failure was the TestLint flake that's going around

bors r=andreimatei

**Comment by danhhz** [comment]
tried looking at every agent and purging the bad TestLint ones

bors r=andreimatei

**Pull request merged**
