### PR TITLE
sql: added indexes to system.statement_statistics, system.transaction_statistics

### LINKED ISSUE #98624: sql: index frequently-used fields in system statistics tables
We should add indexes on the following columns/fields in `system.statement_statistics` and `system.transaction_statistics`:

- `execution_statistics.cnt`
- `statistics.svcLat`
- `execution_statistics.cpuSQLNanos`
- `execution_statistics.contentionTime`

Background thread: https://cockroachlabs.slack.com/archives/G01Q9D01NTU/p1678388421700209

Follow up on https://github.com/cockroachdb/cockroach/pull/98261.

Jira issue: CRDB-25372

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #98624.

This commit adds indexes on new computed columns to the system.statement_statistics and system.transaction_statistics tables.

Epic: none

Release note: None

### CODE REVIEW

**Comment by ericharmeling** [comment]
Here's some benchmark results: [BenchmarkSqlStatsPersistedresults.txt](https://github.com/cockroachdb/cockroach/files/11023112/BenchmarkSqlStatsPersistedresults.txt)

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99042)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @msirek)

___
*[`pkg/sql/catalog/systemschema/system.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-w6ai52NNfne5DBEC:-NR-w6ai52NNfne5DBED:b70lkl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/catalog/systemschema/system.go#L124)):*
> ```Go
> 
> 	indexUsageComputeExpr           = `(statistics->'statistics':::STRING)->'indexes':::STRING`
> 	executionCountComputeExpr       = `((statistics->'execution_statistics':::STRING)->'cnt':::STRING)::INT8`
> ```

do you need to convert this to STRING and then to INT8? can you do INT8 right away? same things for other below

also, this should bt the count from statistics -> statistics -> cnt
___
*[`pkg/sql/catalog/systemschema/system.go` line 569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-wVeXCrKqCKHIzq-d:-NR-wVeXCrKqCKHIzq-e:bf00vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/catalog/systemschema/system.go#L569)):*
> ```Go
> 			plan,
> 			index_recommendations,
>       execution_count,
> ```

nit: alignment is off
___
*[`pkg/sql/catalog/systemschema/system.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-wg9x9t_2Mp4rl_v8:-NR-wg9x9t_2Mp4rl_v9:b-e6d4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/catalog/systemschema/system.go#L615)):*
> ```Go
> 			metadata,
> 			statistics,
>       execution_count,
> ```

nit: alignment
___
*[`pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-xQ1dBi44BncWOaGm:-NR-xQ1dBi44BncWOaGn:b-c9y9gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go#L69)):*
> ```Go
> ALTER TABLE system.statement_statistics
> ADD COLUMN IF NOT EXISTS "total_estimated_execution_time" FLOAT 
> AS ((statistics->'execution_statistics'->>'cnt')::float * (statistics->'statistics'->'svcLat'->>'mean')::FLOAT) STORED
> ```

you should use `statistics -> statistics -> cnt`, because the count for exec stats is not the same and can have less that was used for the latency on stats. 
___
*[`pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-xu_v9lMG-u6OM364:-NR-xu_v9lMG-u6OM365:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go#L82)):*
> ```Go
> ALTER TABLE system.transaction_statistics
> ADD COLUMN IF NOT EXISTS "execution_count" INT8 
> AS ((statistics->'execution_statistics'->'cnt')::INT8) STORED
> ```

ditto
___
*[`pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-y5vT3oIcbUDCl75B:-NR-y5vT3oIcbUDCl75C:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go#L126)):*
> ```Go
> ALTER TABLE system.transaction_statistics
> ADD COLUMN IF NOT EXISTS "total_estimated_execution_time" FLOAT 
> AS ((statistics->'execution_statistics'->>'cnt')::float * (statistics->'statistics'->'svcLat'->>'mean')::FLOAT) STORED
> ```

ditto
___
*[`pkg/sql/sqlstats/persistedsqlstats/bench_test.go` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-yYe0E-DXLC8cbmpe:-NR-yYe0E-DXLC8cbmpf:blmndv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/sqlstats/persistedsqlstats/bench_test.go#L184)):*
> ```Go
> 
> 				// compute expressions
> 				executionCount := "((statistics->'execution_statistics'->'cnt')::INT8)"
> ```

you will need to update all references of count on the test to use the statistics one

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99042)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @msirek)

___
*[`pkg/sql/catalog/systemschema/system.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-w6ai52NNfne5DBEC:-NR0VSSw3rHcBmlCO1oL:b-g8o0fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/catalog/systemschema/system.go#L124)):*
> do you need to convert this to STRING and then to INT8? can you do INT8 right away? same things for other below

Originally, I was not explicitly casting anything except the final type (e.g., `INT8` here), but `TestSystemTableLiterals` was failing the compute expressions. The compute expressions here are what that test expects.

> also, this should bt the count from statistics -> statistics -> cnt

Done.
___
*[`pkg/sql/catalog/systemschema/system.go` line 569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-wVeXCrKqCKHIzq-d:-NR0WSNS00874-yBs4LT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/catalog/systemschema/system.go#L569)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: alignment is off
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/systemschema/system.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-wg9x9t_2Mp4rl_v8:-NR0WTvg3fC0bmypu1rQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/catalog/systemschema/system.go#L615)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: alignment
</blockquote></details>

Done.
___
*[`pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-xQ1dBi44BncWOaGm:-NR0XcKpEMYKNCOmZUzk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go#L69)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you should use `statistics -> statistics -> cnt`, because the count for exec stats is not the same and can have less that was used for the latency on stats. 
</blockquote></details>

Done.
___
*[`pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-xu_v9lMG-u6OM364:-NR0XdVWC6St0yDtVGVo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go#L82)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-y5vT3oIcbUDCl75B:-NR0Xdvr5mLRM8-0uVJh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/upgrade/upgrades/create_computed_indexes_sql_statistics.go#L126)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/bench_test.go` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-NR-yYe0E-DXLC8cbmpe:-NR0Y66kBAGK3fz66tYq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d081e5ada2bf1c27c2645b1479536d7ce7628c81/pkg/sql/sqlstats/persistedsqlstats/bench_test.go#L184)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you will need to update all references of count on the test to use the statistics one
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-:-NR184N5E_PnKXk2UzJv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Comment by rytaft** [comment]
If any of these queries are performance sensitive, I suggest adding them to your new `sql_statistics_persisted` file or another optimizer test.

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99042#-:-NR42EgX2J_V5Q-UU-h3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @msirek)

**Pull request merged**
