### PR TITLE
vendor: bump Pebble to 9656de4a3019

### PR DESCRIPTION
**Pull request by jbowens**
```
9656de4 db: write OPTIONS file to temporary path
558d587 internal/cache: prevent coldTarget from becoming greater than targetSize
634eb34 db: support nil logger in EventListener.EnsureDefaults
d2266ba internal/cache: update entry size in the etTest to etHot transition
```

Bumping now because I need 634eb34 for fixing the disk-full roachtest.

Release note: None

### CODE REVIEW

**Review by bananabrick — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by jbowens** [comment]
TFTR!

bors r=bananabrick

**Pull request merged**
