### PR TITLE
sql: implement RETURNS TABLE syntax

### LINKED ISSUE #100226: sql: RETURNS TABLE not supported for UDFs
**Describe the problem**

Trying to create a UDF with `RETURNS TABLE` currently results in a syntax error.

**To Reproduce**

Run the following in `cockroach demo` on master / 23.1:
```
CREATE FUNCTION sum_n_product_with_tab (x int)
RETURNS TABLE(sum int, product int) AS $$
    SELECT $1 + tab.y, $1 * tab.y FROM tab;
$$ LANGUAGE SQL;
```
On CRDB it results in this error:
```
invalid syntax: statement ignored: at or near "table": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE FUNCTION sum_n_product_with_tab (x int)
RETURNS TABLE(sum int, product int) AS $$
        ^
HINT: try \h CREATE FUNCTION
```

**Expected behavior**

This works on Postgres, so we should support it. But in the meantime, at least we should return an unimplemented error with an appropriate issue number.

Jira issue: CRDB-26307

gz#20015

### LINKED ISSUE #128403: sql: a function returning SETOF RECORD with OUT params returns one row
It is possible to use `RETURNS SETOF` syntax to indicate that a user-defined function returns more than one row. This syntax is compatible with the `RECORD` return type:
```
root@localhost:26257/defaultdb> create function f() returns setof record language sql as $$ select t, t::text from generate_series(1, 10) g(t); $$;
CREATE FUNCTION

Time: 128ms total (execution 128ms / network 0ms)

root@localhost:26257/defaultdb> select f();
     f
-----------
  (1,1)
  (2,2)
  (3,3)
  (4,4)
  (5,5)
  (6,6)
  (7,7)
  (8,8)
  (9,9)
  (10,10)
(10 rows)
```
However, naming the elements of the record using OUT parameters causes CRDB to truncate the result:
```
root@localhost:26257/defaultdb> create function f(out x int, out y text) returns setof record language sql as $$ select t, t::text from generate_series(1, 10) g(t); $$;
CREATE FUNCTION

Time: 154ms total (execution 154ms / network 0ms)

root@localhost:26257/defaultdb> select f();
    f
---------
  (1,1)
(1 row)
```
Contrast this with Postgres, which returns all the rows:
```
postgres=# create function f(out x int, out y text) returns setof record language sql as $$ select t, t::text from generate_series(1, 10) g(t); $$;
CREATE FUNCTION
postgres=# select f();
    f
---------
 (1,1)
 (2,2)
 (3,3)
 (4,4)
 (5,5)
 (6,6)
 (7,7)
 (8,8)
 (9,9)
 (10,10)
(10 rows)
```

Jira issue: CRDB-40994

### PR DESCRIPTION
**Pull request by DrewKimball**
#### sql: do not limit set-returning UDF when it has OUT parameters

This commit fixes a bug that caused the `SetOf` option for the UDF
`ReturnType` to be overwritten if the UDF had OUT parameters. The bug
caused a `LIMIT 1` to be imposed on the UDF's final body statement, so
that the UDF returned only a single row.

Fixes #128403

Release note (bug fix): Fixed a bug existing since v24.1 that would
cause a set-returning UDF with OUT parameters to return a single row.

#### sql: implement RETURNS TABLE syntax

This commit implements `RETURNS TABLE` for UDFs. `RETURNS TABLE` is
syntactic sugar for `RETURNS SETOF` with:
- RECORD if there are multiple TABLE parameters, or
- the type of the single TABLE parameter.
The TABLE parameters are added to the list of routine parameters.

Fixes #100226

Release note (sql change): Added support for `RETURNS TABLE` syntax when
creating a UDF.

### CODE REVIEW

**Comment by DrewKimball** [comment]
>Do you plan to backport just the first commit? Or both?

Just the first commit.

**Review by yuzefovich — APPROVED** [review]
Nice! Just some nits from me. :lgtm:

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-:-ODsxVGc9HK98xo4bzIH:b-c7dspt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_setof` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-ODswlayA6Y2KvKwiubw:-ODswlayA6Y2KvKwiubx:b6e23xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa8859be60d260b4aecf1ccdcfeba00affb5793/pkg/sql/logictest/testdata/logic_test/udf_setof#L246)):*
> ```
> subtest returns_table
> 
> statement error pgcode 42601 pq: at or near "EOF": syntax error: OUT and INOUT arguments aren't allowed in TABLE functions
> ```

nit: it seems a bit dirty that we have `at or near "EOF": syntax error:` prefix in the error message - the statement is parsable. Should we do this check after parsing for a cleaner message?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-ODsu1fR2gVDWvStKkRe:-ODsu1fR2gVDWvStKkRf:b9x6gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9edc119591834b8cd23599d4243e0f35044154e4/pkg/sql/opt/optbuilder/create_function.go#L310)):*
> ```Go
> 			// errors in shared logic later.
> 			funcReturnType = types.Void
> 			cf.ReturnType = &tree.RoutineReturnType{
> ```

nit: perhaps add an test-only assertion that for procedures `SetOf` is not set?
___
*[`pkg/sql/parser/sql.y` line 4892 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-ODsvmqt7A1TS_U4JxOD:-ODsvmqu4g7zPfDl-IMF:b-fjvw2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa8859be60d260b4aecf1ccdcfeba00affb5793/pkg/sql/parser/sql.y#L4892)):*
> ```Yacc
>     // - RECORD if there are multiple TABLE parameters, or
>     // - the type of the single TABLE parameter.
>     // The TABLE parameters are
> ```

nit: the comment seems incomplete.

**Review by DrewKimball — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-:-ODtrNeC6ku5IHWyt8QT:b-814g8k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-ODsu1fR2gVDWvStKkRe:-ODtq-1i8ha_ZS1R0i7_:bqlyd4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9edc119591834b8cd23599d4243e0f35044154e4/pkg/sql/opt/optbuilder/create_function.go#L310)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps add an test-only assertion that for procedures `SetOf` is not set?
</blockquote></details>

For procedures, `ReturnType` isn't set at all until this point.
___
*[`pkg/sql/parser/sql.y` line 4892 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-ODsvmqt7A1TS_U4JxOD:-ODtonVK8I0z2rYpNbra:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa8859be60d260b4aecf1ccdcfeba00affb5793/pkg/sql/parser/sql.y#L4892)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the comment seems incomplete.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_setof` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137251#-ODswlayA6Y2KvKwiubw:-ODtopgf0DKLE73_3NTc:bapi8ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fa8859be60d260b4aecf1ccdcfeba00affb5793/pkg/sql/logictest/testdata/logic_test/udf_setof#L246)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it seems a bit dirty that we have `at or near "EOF": syntax error:` prefix in the error message - the statement is parsable. Should we do this check after parsing for a cleaner message?
</blockquote></details>

Done. It's definitely easiest to emit the error while parsing, because we parse functions in multiple places, and it means we don't have to track table function parameters separately in the AST. I added `lexer.setErrNoDetails` for cases like this where we don't want to annotate the error beyond giving it the `Syntax` error code.

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Pull request merged**
