### PR TITLE
kvserver: remove "InitPut" apis

### LINKED ISSUE #71074: kvserver: remove `InitPut`
`InitPut` is equivalent to `CPut` with `AllowIfDoesNotExist: true` and `ExpBytes: <value>`. `InitPut` does have a `FailOnTombstones` parameter that `CPut` is lacking, but it does not appear to be in use anywhere.

We should replace all use of `InitPut` with `CPut` and remove it and the related MVCC machinery, to reduce our API surface.

Jira issue: CRDB-10385

### PR DESCRIPTION
**Pull request by XiaochenCui**
Previously, we have "InitPut" apis which is similar to "CPut" but are not used anywhere.

This commit addresses this issue by:

- Remove all "InitPut" apis

Fixes: #71074

Release note (general change): Remove "InitPut" apis which are used anywhere.

### CODE REVIEW

**Comment by XiaochenCui** [comment]
hi, @erikgrinaker 
Am I on the right track of this issue? If the answer is yes, I will remove all "InitPut" apis which are not used. There are dozens of them.

**Comment by erikgrinaker** [comment]
Hi @XiaochenCui! I'm no longer with Cockroach Labs, but @nicktrav can have someone follow up.

And yes, the idea is to remove InitPut and use CPut instead, assuming all callers can do so.

**Comment by nvanbenschoten** [comment]
Hi @XiaochenCui, thank you for the contribution! Unfortunately, much of the complexity with addressing https://github.com/cockroachdb/cockroach/issues/71074 will be in making sure that mixed-version clusters handle the removal of the API correctly. We have [an existing PR](https://github.com/cockroachdb/cockroach/pull/88519) that's working in this direction, so I'll advise against repeating that work. We just need to get that PR merged.

Instead, I'd recommend taking a look at the ["good first issue" list](https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) or the ["quick wins" list](https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+is%3Aissue++label%3AE-quick-win+), both of which contain issues from across the codebase that should be appropriate to ramp up on contributing to CockroachDB. Thanks!

**Comment by XiaochenCui** [comment]
hi, @nvanbenschoten 
Thanks for your information! I have been working for several easy issues and am looking for a solid one (medium - large), do you have any suggestions?

**Pull request closed without merging**
