### PR TITLE
sql: version-gate partitioning

### PR DESCRIPTION
**Pull request by benesch**
Just a strawman for now. Ignore the first commit (it's a large yak) until we're sure this is the right approach.

### CODE REVIEW

**Comment by danhhz** [comment]
Approach seems good. What are you thoughts on how this relates to the new range partitioning syntax? That will change the TableDescriptor and I don't think it's worth it to maintain backward compatibility since it's only been in alphas

---

Review status: 0 of 55 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20730#-:-L0LfTwChB7OJwIFTbaS:bvbkptj)*

**Comment by benesch** [comment]
I figure we'll just version gate a few more partitioning features using the same `VersionPartitioning` version. Discussing with @tschottdorf at 4:15, though, if you want to join.

---

Review status: 0 of 55 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20730#-:-L0LiTSWC92_p_beGcXy:bykcol1)*

**Comment by benesch** [comment]
Ok, this is _much_ simpler now that @tschottdorf pointed out that we need to only check the version when we're about to write a table descriptor containing partitioning information. Attempting to perform the check in `Validate()`, which is called both before writes and after reads, results in a race condition. Since `SET CLUSTER SETTING version = ...` does not apply to all nodes instantly, nor transactionally, n1 could upgrade and write a partitioning-laden descriptor, and n2 could see this descriptor and choke before it sees the cluster version upgrade.

So I moved the check to `createPartitionedBy`, which also saves a lot of SQL plumbing. PTAL!

**Comment by benesch** [comment]
FYI @danhhz, @tschottdorf is comfortable with us gating all partitioning stuff behind `VersionPartitioning` and not maintaining any sort of upgrade path between unstable versions.

**Review by danhhz — APPROVED** [review]

**Comment by benesch** [comment]
TFTR!

**Pull request merged**
