### PR TITLE
sql: Propagate an error from auto-commit to a client

### PR DESCRIPTION
**Pull request by kkaneda**
Currently we don't propagate an error coming from auto-commit (in `client.Txn.Exec`) as `Commit()` is called outside of the txn closure and the error is not stored in `sql.Result`.

This commit changes `runTxnAttempt()` to explicitly call `CommitOrCleanup()` and store an error in a `Result`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7080)

### CODE REVIEW

**Comment by andreimatei** [comment]
Thanks so much for tracking this bug down <3

<details><summary><i>Previously, kkaneda (Kenji Kaneda) wrote…</i></summary>
> #### sql: Propagate an error from auto\-commit to a client
> 
> Currently we don't propagate an error coming from auto-commit (in `client.Txn.Exec`) as `Commit()` is called outside of the txn closure and the error is not stored in `sql.Result`.
> 
> 
> 
> This commit changes `runTxnAttempt()` to explicitly call `CommitOrCleanup()` and store an error in a `Result`.
> 
> 
> 
</details>


---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/executor.go, line 544 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJfSNPuL_GGhvVKuh__:-KJfSNPuL_GGhvVKuh_a:713475725) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0e3bc210a7f7bfbda0bffc6d037e7636d16c55/sql/executor.go#L544)):*
> ```Go
> 		if err == nil && txnState.txn.Proto.Status == roachpb.PENDING && !txnState.txn.IsFinalized() {
> 			if cErr := txnState.txn.CommitOrCleanup(); cErr != nil {
> 				res := Result{PGTag: (*parser.CommitTransaction)(nil).StatementTag(), Err: cErr}
> ```

I don't think appending a result like this is kosher. The client drivers probably expect a fixed number of results. Something  will freak out when seeing this `CommitTransaction` tag although no `COMMIT` statement has been issued.
I think we should assert there's a single result without an error and overwrite the error in it.

Better yet, maybe we should leave this closure alone, since it is supposed to be idempotent.
We could do this overwriting of the result in `Executor.execRequest()`, when handling the error from
`err := txnState.txn.Exec(execOpt, txnClosure)`
There's already some massaging of the state we got into after running the closure at that point.

What do you think? I don't have a strong opinion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-:-KJfVGoMLZTuqDiEzbaq:-1217099566)*

**Comment by kkaneda** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/executor.go, line 544 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJfSNPuL_GGhvVKuh__:-KJhmDsuQE3I14mKM4pH:-614078784) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0e3bc210a7f7bfbda0bffc6d037e7636d16c55/sql/executor.go#L544)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I don't think appending a result like this is kosher. The client drivers probably expect a fixed number of results. Something  will freak out when seeing this `CommitTransaction` tag although no `COMMIT` statement has been issued.
> I think we should assert there's a single result without an error and overwrite the error in it.
> 
> Better yet, maybe we should leave this closure alone, since it is supposed to be idempotent.
> We could do this overwriting of the result in `Executor.execRequest()`, when handling the error from
> `err := txnState.txn.Exec(execOpt, txnClosure)`
> There's already some massaging of the state we got into after running the closure at that point.
> 
> What do you think? I don't have a strong opinion.
</details>
Thanks for the quick review! I see. Updated the change as suggested. Does this look better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080)*

**Comment by vivekmenezes** [comment]
Thanks for fixing this bug!

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Thanks so much for tracking this bug down <3
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-:-KJkE7ThsAjjW9Vzofjx:-361217307)*

**Comment by andreimatei** [comment]
:lgtm:

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Thanks for fixing this bug!
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/executor.go, line 544 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJfSNPuL_GGhvVKuh__:-KJkjpEEjGAR-2y9wvhW:322784547) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0e3bc210a7f7bfbda0bffc6d037e7636d16c55/sql/executor.go#L544)):*
<details><summary><i>Previously, kkaneda (Kenji Kaneda) wrote…</i></summary>
> Thanks for the quick review! I see. Updated the change as suggested. Does this look better?
</details>
it does :) thanks

---

*[sql/executor.go, line 449 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJkhcPFn9ch1p5MIMdO:-KJkhcPFn9ch1p5MIMdP:251740607) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7961d44fb05d0399efe1d4ccb1b83902d018a4/sql/executor.go#L449)):*
> ```Go
> 		// This is where the magic happens - we ask db to run a KV txn and possibly retry it.
> 		txn := txnState.txn // this might be nil if the txn was already aborted.
> 		err := txnState.txn.Exec(execOpt, txnClosure)
> ```

I would suggest we return a special err type for `AutoCommitError`, wrapping the real error, from here
https://github.com/cockroachdb/cockroach/blob/bd33879/client/txn.go#L536

then the comment for the error handling below would make more sense.

---

*[sql/executor.go, line 451 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJkdGHWf1FVBCcagV9t:-KJkdGHXLNBEF6KW-ETg:-1882795309) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7961d44fb05d0399efe1d4ccb1b83902d018a4/sql/executor.go#L451)):*
> ```Go
> 		err := txnState.txn.Exec(execOpt, txnClosure)
> 
> 		// Update the Err field of the last result if if it is nil. The error should
> ```

maybe expand this comment a bit?
```
// The error coming from implicit committing, if any, was not captured in a result.
// Set it as the result of the (only) statement here, so that the client gets the error.
```

---

*[sql/executor.go, line 457 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJkiVDJWPelj22kRd0t:-KJkiVDKToUjeZmEAZYe:-531289962) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7961d44fb05d0399efe1d4ccb1b83902d018a4/sql/executor.go#L457)):*
> ```Go
> 			if lastResult.Err == nil {
> 				lastResult.Err = err
> 				if txnState.txn.Proto.Status == roachpb.PENDING && !txnState.txn.IsFinalized() {
> ```

I think this `if` is not necessary. Particularly if you go with the special error type for AutoCommit errors, it's pretty clear that the state is not finalized (you can turn it into an assertion if you'd like).

---

*[sql/executor.go, line 463 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJkilmK38H0wJTFQYgi:-KJkilmK38H0wJTFQYgj:-791756182) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7961d44fb05d0399efe1d4ccb1b83902d018a4/sql/executor.go#L463)):*
> ```Go
> 			}
> 		}
> ```

what do you think of asserting here that, if `err` is not nil, `lastResult.Err` is also not nil? To prevent other bugs like this one, which would be pretty bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-:-KJke_-CJqydKDnxGv6k:1417088721)*

**Comment by kkaneda** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/executor.go, line 449 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJkhcPFn9ch1p5MIMdO:-KJmx5SVvgwxhwyYb5Y2:2125924728) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7961d44fb05d0399efe1d4ccb1b83902d018a4/sql/executor.go#L449)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I would suggest we return a special err type for `AutoCommitError`, wrapping the real error, from here
> https://github.com/cockroachdb/cockroach/blob/bd33879/client/txn.go#L536
> 
> then the comment for the error handling below would make more sense.
</details>
Good idea! Done.

---

*[sql/executor.go, line 451 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJkdGHWf1FVBCcagV9t:-KJmx7aSqpEWfhb0g6K_:1868231659) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7961d44fb05d0399efe1d4ccb1b83902d018a4/sql/executor.go#L451)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> maybe expand this comment a bit?
> ```
> // The error coming from implicit committing, if any, was not captured in a result.
> // Set it as the result of the (only) statement here, so that the client gets the error.
> ```
</details>
Sure,  updated.

```
// Update the Err field of the last result if the error was coming from
// auto commit. The error was generated outside of the txn closure, so it was not
// set in any result.
```

---

*[sql/executor.go, line 457 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080#-KJkiVDJWPelj22kRd0t:-KJmxDp6LdTslUi-vZxW:146269212) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7961d44fb05d0399efe1d4ccb1b83902d018a4/sql/executor.go#L457)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I think this `if` is not necessary. Particularly if you go with the special error type for AutoCommit errors, it's pretty clear that the state is not finalized (you can turn it into an assertion if you'd like).
</details>
You're right. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7080)*

**Pull request merged**
