### PR TITLE
Changed proto.PutCall to take a proto.Value instead of a []byte.

### PR DESCRIPTION
**Pull request by petermattis**
Added proto.PutBytesCall to capture the previous behavior.

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM, but does it even make sense to keep `PutBytesCall` around?

**Comment by petermattis** [comment]
I could change the various uses of `PutBytesCall` to create the `proto.Value`. There are only a handful and only in tests. Thoughts?

**Comment by tschottdorf** [comment]
I'd probably toss it, doesn't really save us anything and it's easy to add back in should we suddenly find ourselves wanting that, which I doubt.

**Comment by petermattis** [comment]
Ok, `PutBytesCall` is gone.

**Comment by tschottdorf** [comment]
:euro:

**Pull request merged**
