### PR TITLE
sql: Expand compression codec support in compress/decompress

### PR DESCRIPTION
**Pull request by miretskiy**
Add support for `lz4`, `snappy`, and `zstd` compression codecs in builtins `compress()/decompress()` function.

Replace the use of builtin compress/gzip with a much faster pgzip.

Epic none

Release note (sql change): Expand the set of supported compression algorithms in compress/decompress builtin functions to include `lz4`, `snappy`, and `zstd`.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

It would be nice to add some simple logic tests for all of the codecs plus an unsupported one - it looks like we didn't add any when `gzip` codec was added.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-:-NGJEmfKDnEx3z3HnNXf:bf8tjzc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/sql/sem/builtins/compression.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-NGJDJvr9WTmkbjYYFc-:-NGJDJvr9WTmkbjYYFc0:b-18d6gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e64d1c63d7a4444eeade7d10ec430d54946bea/pkg/sql/sem/builtins/compression.go#L41)):*
> ```Go
> var invalidCompressionCodecError = pgerror.New(
> 	pgcode.InvalidParameterValue,
> 	"only 'gzip', 'lz4', 'snappy', or 'zstd' codecs are supported for decompress()")
> ```

nit: `s/decompress/compress/`.
___
*[`pkg/sql/sem/builtins/compression.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-NGJDX6b3oyWgzKbrnZU:-NGJDX6b3oyWgzKbrnZV:b-u41kge) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e64d1c63d7a4444eeade7d10ec430d54946bea/pkg/sql/sem/builtins/compression.go#L54)):*
> ```Go
> 	c, ok := codecs[strings.ToUpper(codecName)]
> 	if !ok {
> 		return nil, pgerror.New(pgcode.InvalidParameterValue,
> ```

nit: maybe extract this into a global error too?
___
*[`pkg/sql/sem/builtins/compression.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-NGJE3pjDFK3FNt1s53G:-NGJE3pjDFK3FNt1s53H:b-g6rh8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e64d1c63d7a4444eeade7d10ec430d54946bea/pkg/sql/sem/builtins/compression.go#L132)):*
> ```Go
> 				return nil, err
> 			}
> 			return noErrorCloser{readCloserNoError: r}, err
> ```

nit: could do `s/err/nil/` since we checked the error above.
___
*[`pkg/sql/sem/builtins/compression.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-NGJEGSrEE7dFUl7d6Xm:-NGJEGSrEE7dFUl7d6Xn:b-m84g1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e64d1c63d7a4444eeade7d10ec430d54946bea/pkg/sql/sem/builtins/compression.go#L171)):*
> ```Go
> }
> 
> // decompressUsing decompresses input data using compressor returned by
> ```

nit: `s/compressor/decompressor/`.
___
*[`pkg/sql/sem/builtins/compression.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-NGJEiNj6JrZ872MVXZJ:-NGJEiNj6JrZ872MVXZK:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e64d1c63d7a4444eeade7d10ec430d54946bea/pkg/sql/sem/builtins/compression.go#L172)):*
> ```Go
> 
> // decompressUsing decompresses input data using compressor returned by
> // the getImpl function
> ```

nit: missing period.

**Review by miretskiy — COMMENTED** [review]
logic tests added for each coded + an invalid one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-:-NGOYqui9DyE0GddJlBv:b-pxuxdo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/sem/builtins/compression.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-NGJDJvr9WTmkbjYYFc-:-NGOYDfA7NQ_C37XEyNP:bxk8d3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e64d1c63d7a4444eeade7d10ec430d54946bea/pkg/sql/sem/builtins/compression.go#L41)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/decompress/compress/`.
</blockquote></details>

done (made it generic)
___
*[`pkg/sql/sem/builtins/compression.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91162#-NGJDX6b3oyWgzKbrnZU:-NGOYTjUC_XeJN3tvE8s:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e64d1c63d7a4444eeade7d10ec430d54946bea/pkg/sql/sem/builtins/compression.go#L54)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe extract this into a global error too?
</blockquote></details>

done.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91162)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

**Pull request merged**
