### PR TITLE
sql: skip tenant prefix in spans in EXPLAIN

### PR DESCRIPTION
**Pull request by asubiotto**
This was causing some logic tests to fail in the 3node-tenant configuration.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52560)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @tbg)

___
*[pkg/sql/explain_plan.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52560#-MENtj6G-yuon4q3Y1pJ:-MENtj6G-yuon4q3Y1pK:baaqqg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d684572421c7cc588c527e2faeb78421c22dda4/pkg/sql/explain_plan.go#L69)):*
> ```Go
> 	}
> 
> 	node.explainer.init(flags, !p.ExecCfg().Codec.ForSystemTenant())
> ```

Should this be using the planner's flags?
___
*[pkg/sql/explain_plan.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52560#-MENtHAp17fQBxEOTm4S:-MENtHAp17fQBxEOTm4T:bw8wo3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d684572421c7cc588c527e2faeb78421c22dda4/pkg/sql/explain_plan.go#L134)):*
> ```Go
> 
> 	// fieldsToSkipInSpans is how many fields to skip when pretty-printing spans.
> 	// Usually 2, but can be 4 when running EXPLAIN from a tenant since there will
> ```

Do you mind providing examples in this comment of how keys look before being stripped for the system and for secondary tenants?
___
*[pkg/sql/explain_plan.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52560#-MENtabX4zdYjDO-zZ1S:-MENtabX4zdYjDO-zZ1T:b-v7g9qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d684572421c7cc588c527e2faeb78421c22dda4/pkg/sql/explain_plan.go#L305)):*
> ```Go
> 	hardLimitSet bool,
> ) {
> 	spanss := sqlbase.PrettySpans(index, spans, e.fieldsToSkipInSpans)
> ```

Do we need to do this in `explain_tree.go` as well? Seems like you also have access to `planTop.flags` there as well

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52560)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/sql/explain_plan.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52560#-MENtj6G-yuon4q3Y1pJ:-MERfMsKDKMmPpnQ7dgN:b-fju8nm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d684572421c7cc588c527e2faeb78421c22dda4/pkg/sql/explain_plan.go#L69)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be using the planner's flags?
</blockquote></details>

Since this is executed at plan-time, those haven't been set yet.
___
*[pkg/sql/explain_plan.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52560#-MENtHAp17fQBxEOTm4S:-MERjSnUEiqnmuXhTLtA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d684572421c7cc588c527e2faeb78421c22dda4/pkg/sql/explain_plan.go#L134)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind providing examples in this comment of how keys look before being stripped for the system and for secondary tenants?
</blockquote></details>

Done.
___
*[pkg/sql/explain_plan.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52560#-MENtabX4zdYjDO-zZ1S:-MERfdl3AXHWhNtKUmoa:b-qyh7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d684572421c7cc588c527e2faeb78421c22dda4/pkg/sql/explain_plan.go#L305)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to do this in `explain_tree.go` as well? Seems like you also have access to `planTop.flags` there as well
</blockquote></details>

It's not necessary because those spans are never displayed (since they contain PII).

**Review by tbg — APPROVED** [review]
LGTM once Nathan is happy.

**Review by nvb — APPROVED** [review]
:lgtm: I'm very happy.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52560#-:-MEU3JHx7GakX2F_8mHN:b-8w2ceg)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
I'm happy we're all happy!

bors r=nvanbenschoten,tbg

**Pull request merged**
