### PR TITLE
Makefile: track dependencies of binaries

### PR DESCRIPTION
**Pull request by benesch**
~Just a WIP for now—needs a little more time to bake—but this makes #22957 possible. The first commit is separately tracked in #24103.~

@knz I'll eventually want your review on the middle commit ("Makefile: automatically generate dependencies for Go binaries").

/cc @RaduBerinde

### CODE REVIEW

**Comment by benesch** [comment]
@RaduBerinde this is about 90% ready. I'm sure there's still a bug or two lurking. It would be a huge help, though, if you could check this branch out locally and verify that rebuilds are only triggered when you expect them to be.

**Comment by knz** [comment]
I haven't checked the branch yet (away on vacation) but after reading the code I do want to say I'm impressed by the conciseness and cleverness of the solution. Good investment writing some go to ask the go compiler what it thinks.

I have a few minor suggestions below. Looking good otherwise.

---

Reviewed 7 of 7 files at r1, 12 of 12 files at r2, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Makefile, line 730 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-L87W18wVVCj-Ub6i1Vw:-L87W18ygQztH3Zl6MEe:b-522phl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/Makefile#L730)):*
> ```Makefile
> 	 $(XGO) $(BUILDMODE) -v $(GOFLAGS) -tags '$(TAGS)' -ldflags '$(LINKFLAGS)' $(BUILDTARGET)
> ifndef XHOST_TRIPLE
> 	 @$(COCKROACH) debug settings --format=html > docs/generated/settings/settings.html
> ```

```
foo x y z >somefile.tmp
mv -f somefile.tmp finalname
```

This way, if the generator command fails, you don't end up with a borked generated file.

---

*[Makefile, line 1270 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-L87WmW1f-Wv-fSMetT1:-L87WmW1f-Wv-fSMetT2:btepl8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7736214d9eeeb4b508d62966fff33e1be32b1a00/Makefile#L1270)):*
> ```Makefile
> $(bins): bin/%: bin/%.d | bin/prereqs $(SUBMODULES_TARGET)
> 	@echo go install -v $*
> 	bin/prereqs $(if $($*-package),$($*-package),$(PKG_ROOT)/cmd/$*) > $@.d
> ```

ditto `x > y.tmp && mv y.tmp y`

But you can make this even slightly better with:

```
x > y.tmp
cmp y y.tmp; if $? = 1; then mv -f y.tmp y; fi; rm -f y.tmp
```

this way you preserve the old timestamp when the file doesn't change.

---

*[Makefile, line 855 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-L87XUPgMawUB0aChGi1:-L87XUPgMawUB0aChGi2:b69k8m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/71c29eafe9ed4338d77dfb8d12a44475bb81158c/Makefile#L855)):*
> ```Makefile
> .PHONY: generate
> generate: ## Regenerate generated code.
> generate: protobuf $(DOCGEN_TARGETS) $(OPTGEN_TARGETS)
> ```

Maybe take the opportunity to add `$(SQLPARSER_TARGETS)` here, I know that @dt was annoyed by this for a long time.

---

*[pkg/cli/debug.go, line 802 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-L87WIHLiszEUVy6q2gU:-L87WIHNTOidZvDH9o6s:b-obl33k) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/pkg/cli/debug.go#L802)):*
> ```Go
> }
> 
> var debugSettingsCmd = &cobra.Command{
> ```

We have a `gen` command meant to cover this already (we use it for the man page, for instance). This `settings` sub-command belongs there, not in `debug`.

---

*[pkg/cli/format_table.go, line 349 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-L87WUiF4QX8ZroEefdw:-L87WUiF4QX8ZroEefdx:b-fs2zd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/pkg/cli/format_table.go#L349)):*
> ```Go
> 	nCols int
> 
> 	escape   bool
> ```

Make a separate commit for the changes to this file, and add a test for them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-:-L87Y9Y7YkaZC90GmlkD:bzh2y8q)*

**Comment by RaduBerinde** [comment]
giphy

Awesome! Thanks for working on this!

**Comment by dt** [comment]
settings change LGTM, mod sub-command organization bike shed.

the unreadble html makes me a little sad but I guess it makes sense.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Makefile, line 855 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-L87XUPgMawUB0aChGi1:-L88GAOKYDNWjr6JLpMG:b64s7m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/71c29eafe9ed4338d77dfb8d12a44475bb81158c/Makefile#L855)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe take the opportunity to add `$(SQLPARSER_TARGETS)` here, I know that @dt was annoyed by this for a long time.
</blockquote></details>

fwiw, I've forgotten about whatever it was I was sad about here.

---

*[pkg/cli/debug.go, line 802 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-L87WIHLiszEUVy6q2gU:-L88FW8mFOnhbNyLeFUW:b-e8lrml) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/pkg/cli/debug.go#L802)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We have a `gen` command meant to cover this already (we use it for the man page, for instance). This `settings` sub-command belongs there, not in `debug`.
</blockquote></details>

aha, yes, `gen`seems like a better home, and, to bikeshed, i'd call it `settings-list` or `defined-settings` or something that doesn't make it seem like it is reading a cluster's actual settings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24104#-:-L88FtFBDpTj57ZSPxA_:b-176d6p)*

**Comment by knz** [comment]
:lgtm: with nit

---

Reviewed 3 of 28 files at r4, 6 of 7 files at r5, 10 of 12 files at r6, 11 of 12 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 730 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L87W18wVVCj-Ub6i1Vw:-L96bzTqAUIEFPcROQSn:brdtc8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/Makefile#L730)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ugh, the { } magic doesn't read well. Also no need to hide the command with `@`.
I'd suggest this instead:

```
SETTINGS_DOC_PAGE = docs/generated/settings/settings.html

...

gen settings-list --format=thml >$(SETTINGS_DOC_PAGE).tmp
mv -f $(SETTINGS_DOC_PAGE).tmp $(SETTINGS_DOC_PAGE)
```

Also what's wrong with a separate rule
```
$(SETTINGS_DOC_PAGE): $(COCKROACH)
    $(COCKROACH) gen settings-list --format=html >$(SETTINGS_DOC_PAGE).tmp
    mv -f $(SETTINGS_DOC_PAGE).tmp $(SETTINGS_DOC_PAGE)
```

---

*[Makefile, line 1270 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L87WmW1f-Wv-fSMetT1:-L96cSeo2m_umDYx0nDt:b-g548lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7736214d9eeeb4b508d62966fff33e1be32b1a00/Makefile#L1270)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Preserving the old timestamp doesn't matter here, though, does it? The dependency file is always going to be older than the binary, because we generate it before generating the binary in this recipe.
</blockquote></details>

:+1: carry on.

---

*[docs/generated/settings/.gitignore, line 1 at r8](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L96cXyZAm7fNLVlhDeS:-L96cXyZAm7fNLVlhDeT:bhiiir8) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc2b7dd0a0490dd03ad46a41c7cda2b927b67fda/docs/generated/settings/.gitignore#L1)):*
> ```
> settings.tmp
> ```

Maybe *.tmp

---

*[pkg/cli/format_table.go, line 400 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L96cho1EI2zzUmgbvGE:-L96cho1EI2zzUmgbvGF:bpfwa9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21ed37d783658ef76d6b4a471f6532c8c3b6e37/pkg/cli/format_table.go#L400)):*
> ```Go
> 			p.nCols+1, nRows, util.Pluralize(int64(nRows)))
> 	}
> 	fmt.Fprintln(w, "</table>")
> ```

nice, thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-:-L96d6Km6fON3wxIrq_G:b-xv64lu)*

**Comment by benesch** [comment]
Thanks for the detailed review, @knz!

---

Review status: 1 of 34 files reviewed at latest revision, 5 unresolved discussions.

---

*[Makefile, line 730 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L87W18wVVCj-Ub6i1Vw:-L96p-Hx26FUmUlTBa0H:b-losctd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/Makefile#L730)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ugh, the { } magic doesn't read well. Also no need to hide the command with `@`.
I'd suggest this instead:

```
SETTINGS_DOC_PAGE = docs/generated/settings/settings.html

...

gen settings-list --format=thml >$(SETTINGS_DOC_PAGE).tmp
mv -f $(SETTINGS_DOC_PAGE).tmp $(SETTINGS_DOC_PAGE)
```

Also what's wrong with a separate rule
```
$(SETTINGS_DOC_PAGE): $(COCKROACH)
    $(COCKROACH) gen settings-list --format=html >$(SETTINGS_DOC_PAGE).tmp
    mv -f $(SETTINGS_DOC_PAGE).tmp $(SETTINGS_DOC_PAGE)
```
</blockquote></details>

Took your first suggestion.

The reason it's not a separate rule is because we're trying to save folks a CI cycle when they forget to run `make generate` by updating all generated files during `make build`. I don't see an easy way to pull out this out while preserving the behavior that `make build` and `make cockroach` both update the settings list as necessary.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-:-L97cHw6DUS4jolUy3rp:bpsw7eu)*

**Comment by knz** [comment]
I think this is good to go (with a rebase), but see below for a final suggestion.

---

Reviewed 1 of 29 files at r9, 6 of 8 files at r10, 10 of 12 files at r11, 15 of 16 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 730 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L87W18wVVCj-Ub6i1Vw:-L9ysaXb3EGvDYrG28Vn:bl5rp3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/Makefile#L730)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Took your first suggestion.

The reason it's not a separate rule is because we're trying to save folks a CI cycle when they forget to run `make generate` by updating all generated files during `make build`. I don't see an easy way to pull out this out while preserving the behavior that `make build` and `make cockroach` both update the settings list as necessary.
</blockquote></details>

run `$(MAKE) $(SETTINGS_DOC_PAGE)` at the end of the rule for `$(COCKROACH)`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-:-L9yt8Gx6rT8rmvN7GJC:brkb527)*

**Comment by knz** [comment]
Reviewed 1 of 29 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104)*

**Comment by benesch** [comment]
Review status: 1 of 35 files reviewed at latest revision, 4 unresolved discussions.

---

*[Makefile, line 730 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L87W18wVVCj-Ub6i1Vw:-LAWK5-_0ykd4sqEH-vW:b-f9fxrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/Makefile#L730)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

run `$(MAKE) $(SETTINGS_DOC_PAGE)` at the end of the rule for `$(COCKROACH)`.
</blockquote></details>

I've been on a quest to remove all recursive Make invocations (they're slow). I'd hate to add one back just for this. Perhaps we can have `make build` depend on `$(SETTINGS_DOC_PAGE)` which depends on `$(COCKROACH)`?

Anyway, if you don't mind, I'll leave that to another PR. I don't think I can stomach another rebase.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104)*

**Comment by knz** [comment]
Review status: 1 of 36 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 730 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104#-L87W18wVVCj-Ub6i1Vw:-LAYthuu9YNLnwOQhm9g:b7q56fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e4f35487b0dd4a7113c9d0c413a69320094f258/Makefile#L730)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I've been on a quest to remove all recursive Make invocations (they're slow). I'd hate to add one back just for this. Perhaps we can have `make build` depend on `$(SETTINGS_DOC_PAGE)` which depends on `$(COCKROACH)`?

Anyway, if you don't mind, I'll leave that to another PR. I don't think I can stomach another rebase.
</blockquote></details>

Yes, all right. Go ahead.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24104)*

**Comment by benesch** [comment]
bors r=knz

**Comment by benesch** [comment]
bors r=knz

**Pull request merged**
