### PR TITLE
sql: parser and optimizer support FOR {UPDATE,SHARE} SKIP LOCKED

### LINKED ISSUE #40476: sql: support `FOR {UPDATE,SHARE} {SKIP LOCKED,NOWAIT}`
#6583 and #40206 added support for SELECT FOR UPDATE. There is additional syntax to support: SKIP LOCKED and NOWAIT. See an example of the syntax here: https://www.postgresql.org/docs/current/sql-select.html

---

Update, Feb 2021: CockroachDB v20.2 supports the `NO WAIT` syntax. `SKIP LOCKED` is still not supported at the time of this writing.

Epic CRDB-11976

Jira issue: CRDB-5535

### PR DESCRIPTION
**Pull request by rytaft**
This PR adds support for `SKIP LOCKED` by building on commits from https://github.com/cockroachdb/cockroach/pull/83627 and https://github.com/cockroachdb/cockroach/pull/82188. See below for details.

**sql: enable the skip-locked wait policy**

Now that KV support this, we can pass the wait policy through.

Fixes #40476

Release note (sql change): `SELECT ... FOR {UPDATE,SHARE} SKIP LOCKED`
is now supported. The option can be used to skip rows that cannot be
immediately locked instead of blocking on contended row-level lock
acquisition.

**opt: optimizer updates for support of SKIP LOCKED**

For queries using `SELECT FOR {SHARE,UPDATE} SKIP LOCKED`, we need to disable
optimizations that depend on preserved-multiplicity consistency of
tables. When `SKIP LOCKED` is used, we will no longer use optimizations that
assume:
- a PK row exists for every secondary index row
- a PK row exists for every referencing FK (if the PK table uses `SKIP LOCKED`)

One result of this change is that we will no longer push limits into index
joins if the primary index uses locking wait policy `SKIP LOCKED`.

This commit also disallows use of multiple column families in tables scanned
with `SKIP LOCKED`, since it could result in returning partial rows.

Release note: None

Co-authored-by: Michael Erickson <michae2@cockroachlabs.com>

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm_strong:, though I only skimmed the second and third commit.

> Reviewed 6 of 6 files at r1, 13 of 13 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-:-N8yFFvH4cM9_jzGDRsy:bm74wch)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you for picking this up! This looks great!

> Reviewed 6 of 6 files at r1, 13 of 13 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-:-N8ylxiY-n6Ge38pt7BE:b-gfmv26)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

**Review by mgartner — APPROVED** [review]
:lgtm: Don't forget to update the commit messages when you squash them - if I understand correctly, SKIP LOCKED only affects:

1. Pushing limits below index joins
2. Optimizations that rely on multiplicity and pushing limits

> Reviewed 6 of 6 files at r1, 13 of 13 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-:-N8yi-CrESbQylgqNcnl:b-vqg82q)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/logictest/testdata/logic_test/select_for_update` line 432 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yFuku4hX6GSmhHTAa:-N8yFuku4hX6GSmhHTAb:b-gsl46t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/logictest/testdata/logic_test/select_for_update#L432)):*
> ```
> 
> # All columns are available from the secondary index on u, so no index join is
> # needed.
> ```

nit: It might be helpful to spell out that the secondary index (and lack of index join) can produce the row where k=2 instead of skipping it.
___
*[`pkg/sql/opt/table_meta.go` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yGilUDL11650Mw_Q5:-N8yGilUDL11650Mw_Q6:bipqs5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/table_meta.go#L148)):*
> ```Go
> 	// of this table (i.e. rules that assume there is always a PK row for every
> 	// secondary index row or a FK row for every FK reference).
> 	IsSkipLocked bool
> ```

It's regrettable that we need this bool in addition to the locking struct in ScanPrivate. But I see how it allows `checkIsSkipLocked` to avoid traversing the entire right subexpression. I don't see any way around it though, and I can't think of a better place to track this.

I initially thought that it could be better to include the set of skip-locked columns in relational properties - but I'm not so sure anymore. For one thing, that'd require more computation and space.
___
*[`pkg/sql/opt/memo/multiplicity_builder.go` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yjtkY-PYxxDtkoLuA:-N8yjtkY-PYxxDtkoLuB:b-r2isg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/memo/multiplicity_builder.go#L92)):*
> ```Go
> 		// If no rows are being removed from the table, add all its columns. No rows
> 		// are removed from a table if this is an un-limited, unconstrained scan
> 		// over a non-partial index.
> ```

nit: update this comment
___
*[`pkg/sql/opt/memo/multiplicity_builder.go` line 263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8ygcuMAL7CHyF3toIQ:-N8ygcuMAL7CHyF3toIR:bpkkkd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/memo/multiplicity_builder.go#L263)):*
> ```Go
> func filtersMatchAllLeftRows(left, right RelExpr, filters FiltersExpr) bool {
> 	if checkIsSkipLocked(right.Memo().Metadata(), right) {
> 		return false
> ```

nit: You could add unit tests for this in `multiplicity_builder_test.go`.
___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yab0y5Sv50pf00WlL:-N8yab0z0yV5OwFkYgA_:b-6jhcwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/xform/groupby_funcs.go#L416)):*
> ```Go
> 		// Otherwise, try to construct an IndexJoin operator that provides the
> 		// columns missing from the index.
> 		if sp.Flags.NoIndexJoin {
> ```

We should probably have tests for all these rules where we were forgetting to check `NoIndexJoin`, what do you think? You can do it in a follow-up PR if that's easier.
___
*[`pkg/sql/opt/xform/index_scan_builder.go` line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8y_Ar6AUMTdx5Fnla5:-N8y_Ar6AUMTdx5Fnla6:brcxcir) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/xform/index_scan_builder.go#L167)):*
> ```Go
> func (b *indexScanBuilder) AddIndexJoin(cols opt.ColSet) {
> 	if b.scanPrivate.Flags.NoIndexJoin {
> 		panic(errors.AssertionFailedf("attempt to create an index join with NoIndexJoin flag"))
> ```

nit: you could also add this in `check_expr` since there is at least one rule where an index join is created without using this function.

**Comment by nvanbenschoten** [comment]
Should we mark this as fixing https://github.com/cockroachdb/cockroach/issues/40476?

**Review by rytaft — COMMENTED** [review]
TFTRs!

> Don't forget to update the commit messages when you squash them 

Done.

> Should we mark this as fixing #40476?

Done :partying_face: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-:-N927WR75gGF_QNxAY37:b-f2jkak)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @michae2, and @nvanbenschoten)

___
*[`pkg/sql/logictest/testdata/logic_test/select_for_update` line 432 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yFuku4hX6GSmhHTAa:-N8zTbIK3Hdvc3BasBw8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/logictest/testdata/logic_test/select_for_update#L432)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: It might be helpful to spell out that the secondary index (and lack of index join) can produce the row where k=2 instead of skipping it.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/table_meta.go` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yGilUDL11650Mw_Q5:-N8zTfIeElfaEAIgakQ0:b-yvcktl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/table_meta.go#L148)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's regrettable that we need this bool in addition to the locking struct in ScanPrivate. But I see how it allows `checkIsSkipLocked` to avoid traversing the entire right subexpression. I don't see any way around it though, and I can't think of a better place to track this.

I initially thought that it could be better to include the set of skip-locked columns in relational properties - but I'm not so sure anymore. For one thing, that'd require more computation and space.
</blockquote></details>

Yea... I didn't see a better option either.
___
*[`pkg/sql/opt/memo/multiplicity_builder.go` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yjtkY-PYxxDtkoLuA:-N8zUD9p65qfMrSEcyqn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/memo/multiplicity_builder.go#L92)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: update this comment
</blockquote></details>

Done.
___
*[`pkg/sql/opt/memo/multiplicity_builder.go` line 263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8ygcuMAL7CHyF3toIQ:-N92273V4uLlqi4f0Kvl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/memo/multiplicity_builder.go#L263)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You could add unit tests for this in `multiplicity_builder_test.go`.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yab0y5Sv50pf00WlL:-N927tadCpArd5FtvgCk:b-9s4t4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/xform/groupby_funcs.go#L416)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We should probably have tests for all these rules where we were forgetting to check `NoIndexJoin`, what do you think? You can do it in a follow-up PR if that's easier.
</blockquote></details>

Yea, I split this out and will do it (including tests) in a follow-up PR.
___
*[`pkg/sql/opt/xform/index_scan_builder.go` line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8y_Ar6AUMTdx5Fnla5:-N91wSLK45my0A16Ym4y:b2rimxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/xform/index_scan_builder.go#L167)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could also add this in `check_expr` since there is at least one rule where an index join is created without using this function.
</blockquote></details>

Will add in a follow-up PR

**Comment by nvanbenschoten** [comment]
bors r-

It looks like `TestLint/TestLowercaseFunctionNames` is failing due to this change, which broke bors.

**Review by rytaft — COMMENTED** [review]
Thanks - fixed. I was looking at the wrong build I guess.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-:-N93773K11o5a6UTpThA:b-1ghbfh)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @michae2, and @nvanbenschoten)

___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85720#-N8yab0y5Sv50pf00WlL:-N937Udn0VDrzgJJmq3k:b-y9rf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4733eab33e92793ae80d3b3cb517cc0ee1824eb8/pkg/sql/opt/xform/groupby_funcs.go#L416)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea, I split this out and will do it (including tests) in a follow-up PR.
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/85843

**Pull request merged**
