### PR TITLE
workload: misc small fixes

### PR DESCRIPTION
**Pull request by BramGruneir**
- sort the printed histogram alphabetically
- add time.Time to the init interface
- fix a spelling error
- add better error reporting during setup

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/workload/histogram.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-L70xZS6Xe1YUIr5Jf-E:-L70xZS6Xe1YUIr5Jf-F:bi979am) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2e949eb4e17118ab87cc7c783f862a7d3fd2c6f/pkg/workload/histogram.go#L147)):*
> ```Go
> 	}
> 
> 	sort.Strings(names)
> ```

ha! i also did this in https://github.com/cockroachdb/cockroach/pull/23547

---

*[pkg/workload/histogram.go, line 149 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-L70xcivERA-4G-zRB2G:-L70xcivERA-4G-zRB2H:bsa878z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2e949eb4e17118ab87cc7c783f862a7d3fd2c6f/pkg/workload/histogram.go#L149)):*
> ```Go
> 	sort.Strings(names)
> 	for _, name := range names {
> 		mergedHist, ok := merged[name]
> ```

we don't need the `if !ok` panic, it's just adding noise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-:-L70xwQU7jMFgmwIFyod:bnfp4nl)*

**Comment by BramGruneir** [comment]
*[pkg/workload/histogram.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-L70xZS6Xe1YUIr5Jf-E:-L70zrtMThe_5_1VLCkt:bqgf8od) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2e949eb4e17118ab87cc7c783f862a7d3fd2c6f/pkg/workload/histogram.go#L147)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

ha! i also did this in https://github.com/cockroachdb/cockroach/pull/23547
</blockquote></details>

Do you want me to remove my fix and just go with yours?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549)*

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/workload/histogram.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-L70xZS6Xe1YUIr5Jf-E:-L71-l5lCwdH6g0eAZAx:b-yr8lzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2e949eb4e17118ab87cc7c783f862a7d3fd2c6f/pkg/workload/histogram.go#L147)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Do you want me to remove my fix and just go with yours?
</blockquote></details>

Nah, I'm happy to resolve the conflict

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549)*

**Comment by BramGruneir** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/workload/histogram.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-L70xZS6Xe1YUIr5Jf-E:-L710H9N78oikMepv_tT:bb7efny) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2e949eb4e17118ab87cc7c783f862a7d3fd2c6f/pkg/workload/histogram.go#L147)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Nah, I'm happy to resolve the conflict
</blockquote></details>

cool

---

*[pkg/workload/histogram.go, line 149 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-L70xcivERA-4G-zRB2G:-L710GaDiSbwdU6X-we9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2e949eb4e17118ab87cc7c783f862a7d3fd2c6f/pkg/workload/histogram.go#L149)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

we don't need the `if !ok` panic, it's just adding noise
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549)*

**Comment by danhhz** [comment]
Thanks for the fixes!

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23549#-:-L711KXyU4nUCZ5UyfNP:bceaf7a)*

**Pull request merged**
