### PR TITLE
storage/engine: Correctly handle inlined keys in MVCCGarbageCollect

### PR DESCRIPTION
**Pull request by nvb**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4601)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/engine/mvcc.go, line 1637 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEfZrA308F1v-vngB-:-KBEfZrA308F1v-vngB0:81474372) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc.go#L1637)):*
I thought inline values had a zero timestamp and that you shouldn't be calling `MVCCGarbageCollect` on inline values. Why isn't it possible to skip over the key here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1638 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEfSnbMnDyf_HwlhOe:-KBEfSnbMnDyf_HwlhOf:1603773009) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc.go#L1638)):*
if `implicitMeta` (in the old definition) is true, then you use it only in the expression `!implicitMeta || inlinedValue`. Since inline values also are implicit-meta, it looks like you shouldn't need this new definition here.

---

*[storage/engine/mvcc.go, line 1665 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEg5TzScFz4C1WxBJs:-KBEg5TzScFz4C1WxBJt:996928479) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc.go#L1665)):*
is this necessary? 

---

*[storage/engine/mvcc_test.go, line 2659 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEgNB0Eeqi0LMA1JZz:-KBEgNB0Eeqi0LMA1J_-:566390808) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc_test.go#L2659)):*
could you add another key here which doesn't exist? Preferably for non-inline as well, unless that's already covered.

---

*[storage/engine/mvcc_test.go, line 2772 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEg_6BpLdTijxCxAGI:-KBEg_6BpLdTijxCxAGJ:219852339) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc_test.go#L2772)):*
assert on an actual error (or error) please, potentially using `testutils.IsError`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1637 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEfZrA308F1v-vngB-:-KBEgovH1wO9EsOOba8h:411162729) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc.go#L1637)):*
See the comment below:

> // For version keys, don't allow GC'ing the meta key if it's
			// not marked deleted. However, for inline values we allow it;
			// they are internal and GCing them directly saves the extra

You could `Delete()` the keys and you wouldn't have to GC them, but it's more congruent to instead allowing them to be GCed even if they're non-deleted (this makes sense looking at, for example, the GCQueue).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601)*

**Comment by tschottdorf** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-:-KBEhKraVKTI3REqafGN:676834233)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1638 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEfSnbMnDyf_HwlhOe:-KBEwuX-zFEfTInsEgal:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc.go#L1638)):*
Done.

---

*[storage/engine/mvcc.go, line 1665 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEg5TzScFz4C1WxBJs:-KBEwvE50OLGDQMeJWNW:1818235899) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc.go#L1665)):*
Nope. Removed.

---

*[storage/engine/mvcc_test.go, line 2659 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEgNB0Eeqi0LMA1JZz:-KBEzh4VOLZj2bq_KF6N:1262883165) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc_test.go#L2659)):*
A key which doesn't exist? Do you mean down when we call `MVCCGarbageCollect`? If so, how does that look?

---

*[storage/engine/mvcc_test.go, line 2772 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-KBEg_6BpLdTijxCxAGI:-KBEy3Yj13DBxAmzLhlf:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/130cc7c95535c8adeede27eeb9d0108c505b365d/storage/engine/mvcc_test.go#L2772)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-:-KBF9uuUlrOqTaPiF74O:676834233)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601)*

**Comment by tschottdorf** [comment]
LGTM (still)

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4601#-:-KBGHo5P4_i3BlO6muQB:-941550526)*

**Pull request merged**
