### PR TITLE
colexec: improve handling of operators when they are removed from the tree

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: initialize operators in an edge case**

Previously, it was possible that `Init` is not called on some operators
but `DrainMeta` is. In particular, it was the case if we planned
`fixedNumTuplesNoInputOp` operator which replaced the whole subtree, and
that subtree contained some metadata sources. The assumption that all
operators in use are `Init`ialized was broken, so this commit updates
that utility operator to also initialize the subtree even though it
doesn't consider it as its input.

I noticed this when I was looking into the parallel unordered
synchronizer, and there is an open question whether the synchronizer
should perform its "full" initialization (i.e. spawn up the reader
goroutines) or whether the synchronizer should transition into "done"
state if `DrainMeta` is called before `Next`. The follow-up commit will
implement the latter.

Release justification: low-risk fix to existing functionality.

Release note: None

**colexec: fix parallel unordered sync DrainMeta if Next not called**

Due to the way we construct the vectorized flows (see previous commit),
it is possible to create an operator and add it to MetadataSources queue
and ToClose array even if the operator eventually is not part of the
operator tree that is being run. However, DrainMeta and Close might
still be called on it. Previously, if DrainMeta is called on the
parallel unordered synchronizer on which Next hasn't been called, the
synchronizer would proceed to initialize its reader goroutines and then
would drain them. However, this is unnecessary and complicated and
blocks follow-up work on simplifying context management in operators. To
go around the issue, this commit now simplifies the model so that in
this edge case the reader goroutines are not spawned up, and DrainMeta
goroutine is responsible for shutting down all infrastructure.

Additionally, we forgot to close the error channel when the last reader
goroutine exited in the happy case.

Release justification: low-risk update to existing functionality.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The idea of the first commit was to require that `Init` must be called all the time if `DrainMeta` is called and enforce with a invariants checker, but the prototype #61317 shows that it might not be that easy, so I'm a bit on the fence about the first commit.

**Review by asubiotto — CHANGES_REQUESTED** [review]
OOC, what is difficult about checking that `Init` is called before `DrainMeta`?

I'm not yet convinced about the correctness of the second commit. How can we be sure that it is ok to drop metadata from the inputs? We can't assume that there is nothing to drain if we haven't spawned an input goroutine, since it could (and most likely is) calling `Next` on a router output op, so there is another goroutine that is most likely running and draining metadata and we're choosing to not read it.

What is "the edge case" where this happens? It would be better to decide at plan time when we detect this case to mark the parallel unordered synchronizer removed from the flow similar to the columnarizer if this is the cause. This avoids us having to make assumptions about the correctness of this change.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61306#-:-MUn4_764bSI9tAp7-l6:b-ur5rp8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
My comment was poorly worded - the difficulty is not in the checking (that part is easy) but in flushing out all cases where we already break the invariant. Similar to the columnarizer fix you put out recently we might be "abandoning" some of the MetadataSources, so they are never Init'ialized yet are drained.

I agree with your concern about the correctness. I think I was a bit confused by the naming of `parallelUnorderedSynchronizerUninitialized` state treating it as "`Init` was never called" (in which case the second commit seems definitely correct to me). But that state actually means that "`Next` was never called". I'll need to think a bit more.

Do you think it is fair to say that if a part of the tree rooted in the parallel unordered synchronizer doesn't return any metadata when that part is removed from the flow? Once we add `ctx` argument to `Init` signature, we could check whether `s.Ctx` is nil and short-circuit draining if it is because it means that the synchronizer was abandoned.

First commit is one example where we are removing something from the flow, possibly there are others, and I didn't find any more upon quick audit, but I assume there are other cases because #61317 exposes some cases where `DrainMeta` is called before `Init`.

**Comment by asubiotto** [comment]
> Do you think it is fair to say that a part of the tree rooted in the parallel unordered synchronizer doesn't return any metadata when that part is removed from the flow? Once we add ctx argument to Init signature, we could check whether s.Ctx is nil and short-circuit draining if it is because it means that the synchronizer was abandoned.

My opinion is that this is the wrong way to go about doing it. We shouldn't try to determine whether we've been removed from the flow implicitly, we should rely on planning to tell us explicitly (like the `Columnarizer`) which is a lot less error-prone. Maybe we should figure out a general way to "disable" metadata sources and closers added to these slices by wrapping them in a struct and keep the reference associated to an `Operator`. This way, we'd have a way to call `Disable` or whatever on that reference, which would make future `DrainMeta`/`Close` calls no-ops.

**Comment by yuzefovich** [comment]
I like this idea of keeping some kind of "vectorized planning infrastructure" state in which we can disable operators (making them noops for DrainMeta/Close/etc). I filed #61679 to track it, and I will close this PR in favor of #61317.

**Pull request closed without merging**
