### PR TITLE
*: upgrade crlfmt, remove generics linter

### PR DESCRIPTION
**Pull request by ajwerner**
This PR enables generics in cockroach.

Epic: none

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Remove `generics` from list of linters in top-level `BUILD.bazel`

**Comment by ajwerner** [comment]
> Remove generics from list of linters in top-level BUILD.bazel

Done

**Review by knz — APPROVED** [review]
cheers

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Review by rickystewart — APPROVED** [review]

**Pull request merged**
