### PR TITLE
sql: introduce crdb_internal.index_usage_stats virtual table

### PR DESCRIPTION
**Pull request by Azhng**
This commit introduce crdb_internal.index_usage_stats virtual
table that is backed by new clusterindexusagestats package. This
new package implements a variant of the indexusagestats interface
and serves the data by issuing cluster RPC fanout.

Release note (sql change): introduce crdb_internal.index_usage_statistics
virtual table to surface index usage statistics.
sql.metrics.index_usage_stats.enabled cluster setting can be used to
turn on/off the subsystem. It is default to true.
sql.metrics.index_usage_stats.reset_interval can change the reset
interval of the collected statistics. It is default to 1 hour.

Addresses #64740

Followup to #66639

### CODE REVIEW

**Comment by Azhng** [comment]
Rebased to resolved merge conflict.

**Comment by Azhng** [comment]
Friendly ping @mgartner

**Review by mgartner — APPROVED** [review]
:lgtm: with one suggestion

I think it would be good to get someone else to take a quick look who knows more about virtual tables than I do.

> Reviewed 5 of 17 files at r6, 31 of 31 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-:-MgGwlz0-x770Tsiw0_N:b-wu7t4o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/crdb_internal.go, line 4871 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-MgGterQBuLk4aG8t1xD:-MgGterQBuLk4aG8t1xE:b-sr6gwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/52fa6672c23182ae91c639add2e6e069edc7b3fc/pkg/sql/crdb_internal.go#L4871)):*
> ```Go
> 					return catalog.ForEachIndex(table, catalog.IndexOpts{}, func(idx catalog.Index) error {
> 						indexID := idx.GetID()
> 						stats := indexStats.Get(roachpb.IndexUsageKey{
> ```

nit: `indexStats.Get(tableID, indexID)` would be a simpler interface

**Review by mgartner — APPROVED** [review]
> Reviewed 15 of 15 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66640)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng)

**Review by matthewtodd — COMMENTED** [review]
I had some comment suggestions, all nits. I'm curious, too, how we think about when to do these expensive fanouts and when to introduce some sort of caching or batching or something. Maybe we could talk about that offline, just for my own ramping up here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-:-MgH3nnpE1CKTY2DmEfL:b-swh28y)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng)

___
*[pkg/sql/crdb_internal.go, line 4846 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-MgH2pE30KALE4KpiVPC:-MgH2pE30KALE4KpiVPD:b-51pnfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd05483df31683ca7087ff06ba2816538431269/pkg/sql/crdb_internal.go#L4846)):*
> ```Go
> var crdbInternalIndexUsageStatistics = virtualSchemaTable{
> 	comment: `cluster-wide index usage statistics (in-memory, not durable).` +
> 		`This is an expensive operation since it creates a cluster-wide RPC fanout.`,
> ```

Perhaps "Querying this table is an expensive operation..."? (Since the table itself isn't an operation.)
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 135 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-MgH3EYC2LTDlI8vQ214:-MgH3EYC2LTDlI8vQ215:b6d1nci) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd05483df31683ca7087ff06ba2816538431269/pkg/sql/idxusage/local_idx_usage_stats.go#L135)):*
> ```Go
> // NewLocalIndexUsageStatsFromExistingStats returns a new instance of
> // LocalIndexUsageStats that is populated using given
> // []roachpb.CollectedIndexUsageStatistics.
> ```

Perhaps also say why someone might want to do this?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 248 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-MgH3QKXCH13e1W7fbJi:-MgH3QKXCH13e1W7fbJj:b-wesjok) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd05483df31683ca7087ff06ba2816538431269/pkg/sql/idxusage/local_idx_usage_stats.go#L248)):*
> ```Go
> 
> // batchInsertUnsafe inserts otherStats into s without taking on write lock.
> // This should only be called during initialization and we can be sure there's
> ```

Perhaps "during initialization when we can be sure"?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 249 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-MgH3YSmB0TiXecB89L_:-MgH3YSmB0TiXecB89La:b-i2ru4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd05483df31683ca7087ff06ba2816538431269/pkg/sql/idxusage/local_idx_usage_stats.go#L249)):*
> ```Go
> // batchInsertUnsafe inserts otherStats into s without taking on write lock.
> // This should only be called during initialization and we can be sure there's
> // not other users of s. This avoids the locking overhead when it's not
> ```

Maybe s/not/no
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 290 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-MgH289xAa2ZGKB5XhR9:-MgH289yAfn-H6-swJqq:b-rhoa35) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd05483df31683ca7087ff06ba2816538431269/pkg/sql/idxusage/local_idx_usage_stats.go#L290)):*
> ```Go
> 
> func (s *LocalIndexUsageStats) getStatsForTableID(
> 	id roachpb.TableID, createIfNotExists bool, unsafe bool,
> ```

I'm curious about what `unsafe` means, and what would be unsafe about this method call if I passed `true`. Perhaps it's worth a comment?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 319 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-MgH2SUe3JctuysnBIUm:-MgH2SUe3JctuysnBIUn:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd05483df31683ca7087ff06ba2816538431269/pkg/sql/idxusage/local_idx_usage_stats.go#L319)):*
> ```Go
> 
> func (t *tableIndexStats) getStatsForIndexID(
> 	id roachpb.IndexID, createIfNotExists bool, unsafe bool,
> ```

Ditto.

**Review by Azhng — COMMENTED** [review]
> how we think about when to do these expensive fanouts

I think a lot of times, fanout is our only options unless we can persist the data into the system tables. This is essentially trading a very cheap writes (local in-memory) for very expensive reads. I think gossip system / cluster setting might be a different story, but I'm not too familiar with them. 


> when to introduce some sort of caching or batching or something

For this, I think it really depends on how expensive is the fanout and how often do we need to do this. If it's something asynchronously running in the background and it's not in the critical path of query execution, it's probably ok to accept the network roundtrip cost. (e.g. this index usage stats system). Whereas if the system is critical and frequently accessed by multiple components of the db, (e.g. span resolver) then we definitely need to think about caching those data. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-:-MgHSJLg3pq3-FAZPjJU:b-dc90dn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66640#-:-MgN-CyO8rA10HjXKRUe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by Azhng** [comment]
TFTR! 

bors r+

**Pull request merged**
