### PR TITLE
go.mod: bump Pebble to 593a72bf8976

### PR DESCRIPTION
**Pull request by nicktrav**
```
593a72bf db: add NewIterWithContext to Reader
f6cde3fc internal/manual,internal/rawalloc: Reduce max array size to support MIPS.
6205042b compaction: remove the useless condition in check delete compactions
5807b591 use the constant manifest.NumLevels instead of literal value
94ccf353 vfs/errorfs: add facilities for error injection in datadriven tests
8c13366c compaction: remove the duplicated function mergeFileInfo
bbbf3df1 objstorage: fix up redaction, error message formatting
```

Release note: None.

Epic: None.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
Looks like the errorfs changes have broken something.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112756#-:-NhDhFLfAi0VEBElEcBQ:b-2foz42)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by nicktrav** [comment]
Pushed a fix. Hopefully I'm holing the API correctly. cc: @jbowens

**Review by jbowens — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112756)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nicktrav)

___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 458 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112756#-NhSsH-Z5Yj0ZLuv2inn:-NhSsH-Z5Yj0ZLuv2ino:b3o5xi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeaad5bdd7510309cb03f1e4893ef9b951e9abe/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L458)):*
> ```Go
> }
> 
> func (i *errorInjector) MaybeError(op errorfs.Op, path string) error {
> ```

Sorry for the breaking API changes. This should now look like:
```
func (i *errorInjector) MaybeError(op errorfs.Op) error {
```

You'll also need to add a `String() string` method to `*errorInjector`. It can just return something opaque like "<custom error injector>"

**Comment by nicktrav** [comment]
> Sorry for the breaking API changes. This should now look like

Np! Pushed the fixups. PTAL.

**Comment by nicktrav** [comment]
TFTRs!

bors r+

**Pull request merged**
