### PR TITLE
stats: use value encoding for upper bounds

### LINKED ISSUE #98400: opt: histogram stats do not work with collated strings
Consider the following table with the string column and the query:

```sql
CREATE TABLE t1 (k INT PRIMARY KEY, s STRING);
INSERT INTO t1 SELECT i, 'hello' FROM generate_series(1, 100) g(i);
INSERT INTO t1 SELECT i, 'world' FROM generate_series(101, 120) g(i);
INSERT INTO t1 SELECT i, 'foo' FROM generate_series(121, 130) g(i);
ANALYZE t1;

EXPLAIN (OPT, VERBOSE)
SELECT * FROM t1 WHERE s = 'hello';
```

The optimizer correctly determines that 100 rows will match the filter:

```
select
 ├── columns: k:1 s:2
 ├── stats: [rows=100, distinct(2)=1, null(2)=0]
 │   histogram(2)=  0    100
 │                <--- 'hello'
 ├── cost: 167.95
 ├── key: (1)
 ├── fd: ()-->(2)
 ├── distribution: us-east1
 ├── prune: (1)
 ├── scan t1
 │    ├── columns: k:1 s:2
 │    ├── stats: [rows=130, distinct(1)=130, null(1)=0, distinct(2)=3, null(2)=0]
 │    │   histogram(2)=  0   10    100    20
 │    │                <--- 'foo' ----- 'world'
 │    ├── cost: 166.62
 │    ├── key: (1)
 │    ├── fd: (1)-->(2)
 │    ├── distribution: us-east1
 │    └── prune: (1,2)
 └── filters
      └── s:2 = 'hello' [outer=(2), constraints=(/2: [/'hello' - /'hello']; tight), fd=()-->(2)]
```

Let's do the same with a collated string column:

```sql
CREATE TABLE t2 (k INT PRIMARY KEY, s STRING COLLATE en_US_u_ks_level2);
INSERT INTO t2 SELECT i, 'hello' FROM generate_series(1, 100) g(i);
INSERT INTO t2 SELECT i, 'world' FROM generate_series(101, 120) g(i);
INSERT INTO t2 SELECT i, 'foo' FROM generate_series(121, 130) g(i);
ANALYZE t2;

EXPLAIN (OPT, VERBOSE)
SELECT * FROM t2 WHERE s = 'hello' COLLATE en_US_u_ks_level2;
```

Now the optimizer incorrectly believes that the filter will match zero (or 2.6e-08) rows:

```
select
 ├── columns: k:1 s:2
 ├── stats: [rows=2.6e-08, distinct(2)=2.6e-08, null(2)=0]
 │   histogram(2)=
 ├── cost: 167.95
 ├── key: (1)
 ├── fd: ()-->(2)
 ├── distribution: us-east1
 ├── prune: (1)
 ├── scan t2
 │    ├── columns: k:1 s:2
 │    ├── stats: [rows=130, distinct(1)=130, null(1)=0, distinct(2)=3, null(2)=0]
 │    │   histogram(2)=  0                                     10                                      100                                               20
 │    │                <--- e'\x16\x84\x17\x71\x17q\x00\x00\x00 \x00 \x00 ' COLLATE en_US_u_ks_level2 ----- e'\x18q\x17q\x17\xbd\x17\x11\x161\x00\x00\x00 \x00 \x00 \x00 \x00 ' COLLATE en_US_u_ks_level2
 │    ├── cost: 166.62
 │    ├── key: (1)
 │    ├── fd: (1)-->(2)
 │    ├── distribution: us-east1
 │    └── prune: (1,2)
 └── filters
      └── s:2 = 'hello' COLLATE en_US_u_ks_level2 [outer=(2), constraints=(/2: [/'hello' COLLATE en_US_u_ks_level2 - /'hello' COLLATE en_US_u_ks_level2]; tight), fd=()-->(2)]
```

Jira issue: CRDB-25247

### PR DESCRIPTION
**Pull request by yuzefovich**
Currently, whenever we're encoding the upper bounds of the histogram buckets we always use the datum's key-encoding. However, some datums are composite, and we need to operate on their value encoding. This strategy happens to be ok for floats and decimals because their value part only stores some auxiliary information (like the number of trailing zeroes and the sign of zero), so even if we lose that auxiliary information, when decoding the upper bound we end up with a datum that has the same comparison properties.

Unfortunately, this is not the case for collated strings where key-encoding and value-encoding can be vastly different. So the fact that we always use the key-encoding for collated strings makes it so that when we key-decode upper bounds, we end up with garbage datums. As a result, our histograms are meaningless for collated strings.

This problem is now fixed by always using the value encoding. As mentioned above, this is required for correctness for some types (in addition to collated strings probably also arrays of collated strings), but it also seems beneficial overall. We're getting the upper bound datums when scanning the primary index, and there we get key-encoded datums from indexed and value-encoded datums non-indexed columns, so probably we should be getting more value-encoded datums already. As a result, we should need to do the change in encoding on less amount of data now.

In order to make this change backwards-compatible we gate it based on the new histogram version - if the histogram has the previous version, then it must have used key-encoding for upper bounds, so we will keep on using key-decoding as well. Only once the cluster upgrades to 24.1 version do we start creating the histograms with the new version which will use value-encoding for upper bound datums.

Fixes: #98400.

Release note (bug fix): CockroachDB now correctly uses the histograms on columns of COLLATED STRING type. The bug has been present since pre-22.1 release.

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Nice job fixing this!

Is there a unit test that would have caught this? Maybe a test that creates a histogram with a single bucket of a random type, and then checks that we can round-trip the histogram?

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-:-NoJsj8IEBo-NTY2-h0D:b-f38vg5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`-- commits` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-NoJb-QzAJolxV03iE26):*
Actually, we do collect histograms on JSON and arrays. For example:

```
demo@127.0.0.1:26257/demoapp/defaultdb> CREATE TABLE ijk (i INT PRIMARY KEY, j JSON, k STRING[], INDEX (j), INDEX (k));
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb> INSERT INTO ijk VALUES (1, '{"a": 3.25, "b": 3.50}', ARRAY['x', 'y', 'z']), (2, '{"a": 4.75, "b": 5.50}', ARRAY['m', 'n', 'o']);
INSERT 0 2

Time: 2ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb> ANALYZE ijk;
ANALYZE

Time: 40ms total (execution 39ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb> SHOW STATISTICS FOR TABLE ijk;
  statistics_name | column_names |            created            | row_count | distinct_count | null_count | avg_size | partial_predicate |    histogram_id    | full_histogram_id
------------------+--------------+-------------------------------+-----------+----------------+------------+----------+-------------------+--------------------+--------------------
  __auto__        | {i}          | 2024-01-16 23:31:13.296228+00 |         0 |              0 |          0 |        0 | NULL              | 935124904503312385 |                 0
  __auto__        | {j}          | 2024-01-16 23:31:13.296228+00 |         0 |              0 |          0 |        0 | NULL              | 935124904510324737 |                 0
  __auto__        | {k}          | 2024-01-16 23:31:13.296228+00 |         0 |              0 |          0 |        0 | NULL              | 935124904517369857 |                 0
  NULL            | {i}          | 2024-01-16 23:32:10.872031+00 |         2 |              2 |          0 |        1 | NULL              | 935125093168578561 |                 0
  NULL            | {j}          | 2024-01-16 23:32:10.872031+00 |         2 |              2 |          0 |       35 | NULL              | 935125093175918593 |                 0
  NULL            | {k}          | 2024-01-16 23:32:10.872031+00 |         2 |              2 |          0 |       11 | NULL              | 935125093182996481 |                 0
(6 rows)

Time: 4ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb> SHOW HISTOGRAM 935125093175918593;
        upper_bound       | range_rows | distinct_range_rows | equal_rows
--------------------------+------------+---------------------+-------------
  '{"a": 3.25, "b": 3.5}' |          0 |                   0 |          1
  '{"a": 4.75, "b": 5.5}' |          0 |                   0 |          1
(2 rows)

Time: 2ms total (execution 2ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb> SHOW HISTOGRAM 935125093182996481;
     upper_bound     | range_rows | distinct_range_rows | equal_rows
---------------------+------------+---------------------+-------------
  ARRAY['m','n','o'] |          0 |                   0 |          1
  ARRAY['x','y','z'] |          0 |                   0 |          1
(2 rows)

Time: 3ms total (execution 2ms / network 0ms)
```

Does this mean we need to use value encodings for other types?

Would it be safer to use value encodings for all types, in case we add another composite type one day?
___
*[`pkg/sql/show_histogram.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-NoJpH3xBRw0IRCsc6DV:-NoJpH3xBRw0IRCsc6DW:b-eib0jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d77dd63a897e6da53293b635656d4edf1eb6a7d/pkg/sql/show_histogram.go#L86)):*
> ```Go
> 				if err != nil {
> 					v.Close(ctx)
> 					return nil, err
> ```

Instead of returning the error, could we print it to the string in a similar way to `EncDatum.stringWithAlloc`?
___
*[`pkg/sql/stats/histogram.go` line 684 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-Nnv7jvFEjkxce619OTa:-Nnv7jvFEjkxce619OTb:b-1yoj5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d77dd63a897e6da53293b635656d4edf1eb6a7d/pkg/sql/stats/histogram.go#L684)):*
> ```Go
> 		// cannot yet use the newest histogram version to preserve
> 		// backwards-compatibility.
> 		version = HistVersion - 1
> ```

suggestion: This works, but it requires us to remember to change this -1 if we add another histogram version during the time when we could still upgrade from 23.2.

It might be a little safer to ignore `HistVersion` (or get rid of `HistVersion`) and instead structure this as "positive" checks instead of "negative" checks like:

```
// 22.2 - 23.2
version := HistogramVersion(2)

if st.Version.IsActive(ctx, clusterversion.V24_1) {
  version = collatedStringsValueEncodedVersion
}

// and then future versions can add if statements like:
// if st.Version.IsActive(ctx, clusterversion.V24_2) {
//   version = HistogramVersion(4)
// }
```

This is a little more robust if we add another histogram version during 24.1 development (or 24.2 development and need to support upgrades from 23.2 to 24.2).

And it might even be worth getting rid of `HistVersion` and instead creating fixed constants for `HistogramVersion(0)`, 1, and 2, similar to `collatedStringsValueEncodedVersion` that aren't expected to change like `HistVersion` did. This would better match what we do in `clusterversion`.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/collated_strings` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-NoJqdoz3n1Pje-uHvqS:-NoJqdp-5uLmxxe3HloA:b5c5wi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d77dd63a897e6da53293b635656d4edf1eb6a7d/pkg/sql/opt/exec/execbuilder/testdata/collated_strings#L34)):*
> ```
>  │    │                <--- 1 --- 2 --- 3 --- 4 --- 5 --- 6 --- 7 --- 8 --- 9 --- 10 --- 11 --- 12 --- 13
>  │    │   histogram(2)=  0                 1                 10                  2
>  │    │                <--- 'foo' COLLATE en_US_u_ks_level2 ---- 'world' COLLATE en_US_u_ks_level2
> ```

Nice! :slightly_smiling_face:

**Review by yuzefovich — COMMENTED** [review]
Thanks for the careful review!

> Is there a unit test that would have caught this? Maybe a test that creates a histogram with a single bucket of a random type, and then checks that we can round-trip the histogram?

That's a good idea, done. The newly-added test would have caught the problem for collated strings.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-:-NoOyQGG353PqqGsSrRU:b-b1c8ps)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[`-- commits` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-NoJb-QzAJolxV03iE26):*
Hm, that's a good point - I saw a comment along these lines in `deepCopyDatum` (but it must be stale) and didn't check - thanks for checking! (I think that function is redundant at this point and actually can be removed. Did that in a separate commit.)

> Would it be safer to use value encodings for all types, in case we add another composite type one day?

This sounds like a good idea.

Possible disadvantage of doing this, though, is the fact that we collect histograms _mostly_ on the indexed columns, meaning that if we were to scan the index to get datums, they would come with key-encoding present, which means that storing the value encoding would require additional step to go from one encoding to the other.

However, at least right now (and probably for the foreseeable future) we perform the scan of the primary index for stats collection purposes, so what we get is key-encoding for columns in the primary key and value-encoding columns for everything else. This observation actually makes me think that we do have value-encoding for majority of columns, so switching to always use value-encoding would be an improvement to stats collection overall (in addition to being bullet-proof from compositeness). Done.
___
*[`pkg/sql/show_histogram.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-NoJpH3xBRw0IRCsc6DV:-NoOrWiqCLkh7MiXTzrf:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d77dd63a897e6da53293b635656d4edf1eb6a7d/pkg/sql/show_histogram.go#L86)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Instead of returning the error, could we print it to the string in a similar way to `EncDatum.stringWithAlloc`?
</blockquote></details>

Good point, done.
___
*[`pkg/sql/stats/histogram.go` line 684 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-Nnv7jvFEjkxce619OTa:-NoOnUrWDrVFYAEg3LB0:b3vygxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d77dd63a897e6da53293b635656d4edf1eb6a7d/pkg/sql/stats/histogram.go#L684)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

suggestion: This works, but it requires us to remember to change this -1 if we add another histogram version during the time when we could still upgrade from 23.2.

It might be a little safer to ignore `HistVersion` (or get rid of `HistVersion`) and instead structure this as "positive" checks instead of "negative" checks like:

```
// 22.2 - 23.2
version := HistogramVersion(2)

if st.Version.IsActive(ctx, clusterversion.V24_1) {
  version = collatedStringsValueEncodedVersion
}

// and then future versions can add if statements like:
// if st.Version.IsActive(ctx, clusterversion.V24_2) {
//   version = HistogramVersion(4)
// }
```

This is a little more robust if we add another histogram version during 24.1 development (or 24.2 development and need to support upgrades from 23.2 to 24.2).

And it might even be worth getting rid of `HistVersion` and instead creating fixed constants for `HistogramVersion(0)`, 1, and 2, similar to `collatedStringsValueEncodedVersion` that aren't expected to change like `HistVersion` did. This would better match what we do in `clusterversion`.
</blockquote></details>

That's a good point. I like the idea of introducing named constants for each histogram version that we need to gate the code on, done. I decided to not remove `HistVersion` still so that places outside of histogram creation code could still easily create the histogram of the latest version (currently there is only one caller though `randHistogram`).

**Review by michae2 — APPROVED** [review]
:lgtm: Thanks for the test! This is great!

Hmm, looks like some other tests are unhappy with that value encoding for all types... hopefully nothing serious.

> Reviewed 10 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-:-NoPCZ_O4pZfsX3ptXLS:bcmjmpp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/stats/row_sampling.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-NoPCSlX9jShhRAb9eM2:-NoPCSlYCPX2t_8xpGIG:bwuv9uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/624885c463ddd4eecb406b863c78b49b683bbca9/pkg/sql/stats/row_sampling.go#L268)):*
> ```Go
> 			afterSize = dst[i].Size()
> 		} else {
> 			dst[i].Datum = deepCopyDatum(dst[i].Datum)
> ```

Nice!!

**Review by yuzefovich — COMMENTED** [review]
The failures were minor - I forgot to update a few places where we still used key-encoding to generate histograms.

Also, as it turns out, we were pretty close to noticing this bug earlier, but I chose to ~ignore it~not dig into it by skipping collated strings for histogram generation in 1902d3d919753e23a51f424054f5f92a173d3600 :/

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117714#-:-NoSdsmQ1K8qoKagkIa6:bsfbb31)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @rytaft)

**Comment by yuzefovich** [comment]
Build is green, TFTR!

bors r+

**Pull request merged**
