### PR TITLE
Add schema_privileges and table_privileges two virtual schemas

### PR DESCRIPTION
**Pull request by yznming**
pls look at #8675
schema_privileges is from MySQL and table_privileges from PostgreSQL

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9104)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Thanks for the help with this @yznming, the change is looking great so far! I had a few comments on ways we can make this a bit cleaner, as well as a refactoring I'm hoping you could help with to improve the interface exposed by `Privileges.Show()`.

---

Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQvu4nuE-SBMnFiGEs-:-KQvu4nuE-SBMnFiGEs0:bpho467) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L34)):*
> ```Go
> 		informationSchemaTableConstraintTable,
> 		informationSchemaTablesTable,
> 		informationSchemaTablePrivileges,
> ```

I've been trying to keep this in alphabetical order. Could we move:
`informationSchemaTablePrivileges` below `informationSchemaTableConstraintTable`
`informationSchemaSchemataTablePrivileges` below `informationSchemaSchemataTable`

---

*[sql/information_schema.go, line 129 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQvuxzziIakwn54MtsS:-KQvuxzziIakwn54MtsT:b27do9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L129)):*
> ```Go
> }
> 
> var informationSchemaTablePrivileges = virtualSchemaTable{
> ```

Could we move this down below the helper functions used by `informationSchemaColumnsTable`?

---

*[sql/information_schema.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQvxMz0SV8P1YDlZZEv:-KQvxMz0SV8P1YDlZZEw:bvbq946) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L145)):*
> ```Go
> 		return forEachTableDesc(p,
> 			func(db *sqlbase.DatabaseDescriptor, table *sqlbase.TableDescriptor) {
> 				for _, u := range table.Privileges.Show() {
> ```

It looks like `table.Privileges.Show()` is returning "a string of comma-separated sorted privilege names". I think we'll want to change the method to return a slice of UserPrivilegeString without the privileges being concatenated already. 

Perhaps we can change `UserPrivilegeString` to look like:

```
type UserPrivilegeString struct {
	User       string
	Privileges []string
}

func (u UserPrivilegeString) PrivilegeString() string {
    return strings.Join(u.Privileges, ", ")
}
```

`PrivilegeDescriptor.Show()` could then call `privilege.ListFromBitField(userPriv.Privileges).SortedNames()` to sort the privileges on construction.

This would require a few places to change `UserPrivilegeString.Privileges` accesses to `UserPrivilegeString.PrivilegeString()` calls.

---

*[sql/information_schema.go, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQvuqIWHyEsxDu-vJfl:-KQvuqIWHyEsxDu-vJfm:bx3gt8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L149)):*
> ```Go
> 						parser.DNull,                    // Grantor
> 						parser.NewDString(u.User),       // Grantee
> 						defString,                       // Table catalog,
> ```

nit: These comments have all been snake case and without commas (see above).

---

*[sql/information_schema.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQvzqPKbBV8P3Vb64wf:-KQvzqPL9JdA9m_fUrfx:bube6ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L216)):*
> ```Go
> 	populate: func(p *planner, addRow func(...parser.Datum)) error {
> 		return forEachDatabaseDesc(p, func(db *sqlbase.DatabaseDescriptor) {
> 			for _, u := range db.Privileges.Show() {
> ```

See comment above about `UserPrivilegeString`

---

*[sql/information_schema.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQvztgCf12K3RE6JZaW:-KQvztgCf12K3RE6JZaX:b4aufbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L218)):*
> ```Go
> 			for _, u := range db.Privileges.Show() {
> 				addRow(
> 					parser.NewDString(u.User),       // Grentee
> ```

`s/Grentee/grantee`

---

*[sql/information_schema.go, line 221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQvzxP3tEOGShKHBhij:-KQvzxP3tEOGShKHBhik:b4pxanq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L221)):*
> ```Go
> 					defString,                       // table_catalog,
> 					parser.NewDString(db.Name),      // database_name
> 					parser.NewDString(u.Privileges), // Privilege type
> ```

See above about snake case.

---

*[sql/information_schema.go, line 226 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQw-FdmMO55dyZsScyQ:-KQw-FdmMO55dyZsScyR:b56iyy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/information_schema.go#L226)):*
> ```Go
> 			}
> 
> 		},
> ```

Collapse this line and the next.

---

*[sql/testdata/information_schema, line 434 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQw-QaWFZUX_WiNriAq:-KQw-QaWFZUX_WiNriAr:benhqy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa3e47ef94047e89c3fb7e9c7b66827a7338abc/sql/testdata/information_schema#L434)):*
> ```
> def                 system             primary          system        users       PRIMARY KEY
> def                 system             primary          system        zones       PRIMARY KEY
> ```

Move all this to the end of the file and add separator comments like `## information_schema.table_constraints`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-:-KQvtynS3VYWWNrSRt7N:bfrh3wk)*

**Comment by yznming** [comment]
@nvanbenschoten got it. I will fix it.

**Comment by yznming** [comment]
@nvanbenschoten I'm not sure why we want to change the method `table.Privileges.Show()`. Do you mean exclude the privileges concatenated from database for a table?

**Comment by nvanbenschoten** [comment]
The goal is that each privilege should produce a separate row in the output for both `schema_privileges` and `table_privileges`, so instead of having a single row that looks like:

```
query TTTTTTTT colnames
SELECT * FROM information_schema.table_privileges
----
GRANTOR  GRANTEE   TABLE_CATALOG  TABLE_SCHEMA  TABLE_NAME  PRIVILEGE_TYPE IS_GRANTABLE  WITH_HIERARCHY
NULL     root      def            system        descriptor  GRANT,SELECT   NULL          NULL
```

we want multiple rows that look like:

```
query TTTTTTTT colnames
SELECT * FROM information_schema.table_privileges
----
GRANTOR  GRANTEE   TABLE_CATALOG  TABLE_SCHEMA  TABLE_NAME  PRIVILEGE_TYPE IS_GRANTABLE  WITH_HIERARCHY
NULL     root      def            system        descriptor  GRANT          NULL          NULL
NULL     root      def            system        descriptor  SELECT         NULL          NULL
```

One way to accomplish this could be to split the "comma-separated sorted privilege names" returned by `table.Privileges.Show()`, but why hack around the method's API when we can just improve it? A better solution would be to return a slice of sorted privilege strings without concatenating them from `table.Privileges.Show()`, and add a method to the struct to concatenate the strings when needed. Does that make sense?

**Comment by yznming** [comment]
@nvanbenschoten It's clear now, thanks a lot.

**Comment by nvanbenschoten** [comment]
This is looking really good now. Just a few more comments then I think it will be good to merge.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/information_schema.go, line 226 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KQw-FdmMO55dyZsScyQ:-KR5FBUAzuvEsX1XixhS:bwemthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1026e65015139c565bff835ccd98a4a07b64b501/sql/information_schema.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Collapse this line and the next.
</details>
tiny nit: `s/},\n)/})`

---

*[sql/privilege/privilege.go, line 107 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KR5FZuyKcBXpv7BgdGW:-KR5FZuyKcBXpv7BgdGX:bzc4jrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8f663d992fe61f2476d3c9a8c8395ffb773237/sql/privilege/privilege.go#L107)):*
> ```Go
> // privileges sorted by name and uses "," as separator.
> func (pl List) SortedString() string {
> 	names := pl.names()
> ```

These two lines can be replaced by `names := pl.SortedNames()`

---

*[sql/privilege/privilege.go, line 112 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KR5FPSKKD7PbPOzva5K:-KR5FPSKKD7PbPOzva5L:b249dvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8f663d992fe61f2476d3c9a8c8395ffb773237/sql/privilege/privilege.go#L112)):*
> ```Go
> }
> 
> // SortedNames is similar to SortedString() but returns
> ```

Let's make this stand on it's own. Something like `SortedNames returns a list of privilege names in sorted order`

---

*[sql/sqlbase/privilege.go, line 211 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-KR5FhzIRnFFDSo7aqJb:-KR5FhzIRnFFDSo7aqJc:byn95hi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8f663d992fe61f2476d3c9a8c8395ffb773237/sql/sqlbase/privilege.go#L211)):*
> ```Go
> }
> 
> // PrivilegeString returns a string of comma-separted reivilege names
> ```

`s/reivilege names/privilege names./`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9104#-:-KR5O7oXMSHnGy3scA2N:bwz1mzw)*

**Pull request merged**
