### PR TITLE
sql/upgrade: Added precondition check before upgrading to v22.1

### LINKED ISSUE #83432: sql,upgrades: ensure new version does not think any descriptors are invalid as a precondition
**Is your feature request related to a problem? Please describe.**

We've had a couple of issues due to stricter validation in 22.1 (https://github.com/cockroachdb/cockroach/issues/82499, https://github.com/cockroachdb/cockroach/issues/82576). It's a bummer for customers when they cannot roll back to the previous version because we've finalized the new version. 

**Describe the solution you'd like**

The upgrades package offers the notion of a precondition. We should set as a standing precondition, or something like that, to ensure that the newer version's validation won't consider existing descriptors as invalid when finalizing. This can prevent cases where clusters are stuck with invalid descriptors and cannot rollback.

Jira issue: CRDB-17068

### PR DESCRIPTION
**Pull request by Xiang-Gu**
The sql/upgrade package offers the notation of a `precondition` that
must be met before attemping a cluster version upgrade. This feature was
never used before. We recently saw issues where when customers attempted
to upgrade to v22.1, our validation logic found there are invalid
descriptors and hence rejected the upgrade, but the customer cannot
downgrade back to the previous version if `preserve_downgrade` is not
set. This negatively affects user experience since the users will be
stuck in an unfinish upgrade. Those invalid descriptors are created due
to bugs that exists in earlier version.

One compromise is to relax the validation logic to allow certain minor
violations to slip by, but this method only goes to certain extent. In
case where a serious violation is found (e.g. a table has a dangling
reference to a missing/dropped descriptor), we don't think ignorance is
no longer the right approach.

Instead, this PR utilize the handy precondition notion in the upgrade
package to assert that if there is any invalid descriptor, we reject the
upgrade with clear error messages, with the hope/expectation that the
user can (and should) fix those invalid descriptors before attempting
an upgrade again. (How? It's a different story but a descriptor surgery
is one of the solutions...)

It was coded such that it's easy to extend the precondition to include
any other checks, so long as we consider them sane.

Fix #83432

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83612)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Xiang-Gu)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83612#-N5l5zdQDPK4tclI9lJJ:-N5l5zdQDPK4tclI9lJK:bz0e3vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e5b6c120dd46018e8b8df4c4bd58d7cee32cf6/pkg/upgrade/upgrades/upgrades.go#L50)):*
> ```Go
> var registry = make(map[clusterversion.ClusterVersion]upgrade.Upgrade)
> 
> var upgrades = []upgrade.Upgrade{
> ```

We want to attach it to `Start22_1`, at least for the backport
___
*[`pkg/upgrade/upgrades/precondition_before_starting_an_upgrade_external_test.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83612#-N5l69x91tzuvljcFEzT:-N5l69x91tzuvljcFEzU:b-urenez) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e5b6c120dd46018e8b8df4c4bd58d7cee32cf6/pkg/upgrade/upgrades/precondition_before_starting_an_upgrade_external_test.go#L104)):*
> ```Go
> 			"Invalid descriptor: defaultdb.public.t (52) because 'relation \"t\" (52): invalid depended-on-by relation "+
> 			"back reference: referenced table ID 53: referenced descriptor not found'", err.Error())
> 	})
> ```

Now verify that the cluster version has not changed.

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83612)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83612#-N5l5zdQDPK4tclI9lJJ:-N5lAMEc4axkE3VsoRS5:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e5b6c120dd46018e8b8df4c4bd58d7cee32cf6/pkg/upgrade/upgrades/upgrades.go#L50)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We want to attach it to `Start22_1`, at least for the backport
</blockquote></details>

done
___
*[`pkg/upgrade/upgrades/precondition_before_starting_an_upgrade_external_test.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83612#-N5l69x91tzuvljcFEzT:-N5l9eEY0kWBxJpuI32a:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e5b6c120dd46018e8b8df4c4bd58d7cee32cf6/pkg/upgrade/upgrades/precondition_before_starting_an_upgrade_external_test.go#L104)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Now verify that the cluster version has not changed. 
</blockquote></details>

done

**Review by ajwerner — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83612)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

**Comment by ajwerner** [comment]
blathers backport 22.1

**Comment by ajwerner** [comment]
@Xiang-Gu can you backport this manually?

**Comment by Xiang-Gu** [comment]
I manually created a backport [PR](https://github.com/cockroachdb/cockroach/pull/84490) to v22.1. The reason that it needs conflict resolution is that we have changed the `migration` package to be `upgrade`.

**Pull request merged**
