### PR TITLE
storage: fallout from (closed) PR #9450

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9622)

### CODE REVIEW

**Comment by tamird** [comment]
This is pretty hard to review, there seems to be a good amount of unrelated change in various commits. Do these all compile?

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 4 of 9 files at r7.
Review status: 15 of 20 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 1621 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrXcgJAgRdfq-s39W-:-KSrXcgK6FKABeJc8RxK:b-rojlnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e8135247c47ec036c757813f12a5fcac9c8b8d3/storage/client_raft_test.go#L1621)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	errCh := make(chan error, 1)
> ```

i think this test wants a bigger refactor (snapshots should be generated in the main goroutine, random splits should be in non-main goroutines). that gives the test a more natural stopping condition. not for this PR.

---

*[storage/client_raft_test.go, line 1640 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrWi7aPxEgPUGAmN9C:-KSrWi7aPxEgPUGAmN9D:b-874298) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e8135247c47ec036c757813f12a5fcac9c8b8d3/storage/client_raft_test.go#L1640)):*
> ```Go
> 		}
> 		if _, err := rng.GetSnapshot(context.Background()); err != nil {
> 			return errors.Wrapf(err, "failed to snapshot range %s: %s", key)
> ```

wrong number of parameters

---

*[storage/client_raft_test.go, line 1998 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrdGiXP8NPfhkAnjS7:-KSrdGiYzCB6iy7U8y0I:b-tz95tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b348e00ada7947b2dc16a1bcc9f1c65dd636664/storage/client_raft_test.go#L1998)):*
> ```Go
> 		startWG.Done()
> 		defer finishWG.Done()
> 		_, pErr := client.SendWrappedWith(
> ```

the new version appears to take a different type in the first position with no accompanying change to the function being used. Am I missing something?

---

*[storage/client_split_test.go, line 1189 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrdSuUNJ3X0PvKQPoS:-KSrdSuUNJ3X0PvKQPoT:b-8evdil) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdf6c68370b6a09707fc9a04d09968e7990c0f59/storage/client_split_test.go#L1189)):*
> ```Go
> 			return nil
> 		}
> 		log.Infof(context.TODO(), "received lease request %+v", leaseReq)
> ```

:dog:

---

*[storage/gc_queue_test.go, line 239 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZgWCNd7ywnafsbdj:-KSrZgWCNd7ywnafsbdk:brjspth) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/gc_queue_test.go#L239)):*
> ```Go
> 
> 	for i, datum := range data {
> 		// TODO(tschottdorf): Fixing up the SendWrappedWith calls below to
> ```

wrong commit? no idea what's going on here

---

*[storage/queue.go, line 505 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrXw6Nt0XmO7dFsZBC:-KSrXw6O8mwiJV0RgAjs:b-k66ey9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0796fae81d118b11868f311a859ac26941f46d4b/storage/queue.go#L505)):*
> ```Go
> 	// Putting a span in ctx means that events will no longer go to the event log.
> 	// Use bq.ctx for events that are intended for the event log.
> 	ctx := opentracing.ContextWithSpan(bq.ctx, sp)
> ```

seems pretty random here

---

*[storage/queue.go, line 547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrY-E_cJ36tzWw3Qe3:-KSrY-E_cJ36tzWw3Qe4:bhxghkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/queue.go#L547)):*
> ```Go
> // mechanism for signaling re-processing of replicas held in
> // purgatory.
> func (bq *baseQueue) maybeAddToPurgatory(repl *Replica, triggeringErr error, clock *hlc.Clock, stopper *stop.Stopper) {
> ```

also seems unrelated to commit message

---

*[storage/replica_consistency_queue.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZLh2rlKCsDR2BGy7:-KSrZLh2rlKCsDR2BGy8:bv269g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/replica_consistency_queue.go#L57)):*
> ```Go
> }
> 
> func (*replicaConsistencyQueue) shouldQueue(_ hlc.Timestamp, _ *Replica,
> ```

wrap while you're here

---

*[storage/scanner.go, line 216 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZS5BED5-W_XQV0ri:-KSrZS5BED5-W_XQV0rj:b9qbtxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/scanner.go#L216)):*
> ```Go
> 			}
> 
> 			// TODO(tschottdorf): why this task?
> ```

who owns the blame?

---

*[storage/scanner_test.go, line 173 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZWNKcPR8JW6vNcJK:-KSrZWNKcPR8JW6vNcJL:brl6cjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/scanner_test.go#L173)):*
> ```Go
> func (tq *testQueue) indexOf(rangeID roachpb.RangeID) int {
> 	for i, repl := range tq.ranges {
> 		if rangeID == repl.RangeID {
> ```

nit: reverse (yoda condition)

---

*[storage/store.go, line 214 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrdwY4nEGxnpLq6DEQ:-KSrdwY4nEGxnpLq6DER:b-g8pmv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/36454d51720fd09f3741c8c2a258eca76d703549/storage/store.go#L214)):*
> ```Go
> type storeRangeSet struct {
> 	store   *Store
> 	repls   []*Replica // Replicas to be visited.
> ```

there is substantial random junk in this commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-:-KSrdzqJ7LypRFB22G20:ba97md6)*

**Comment by tschottdorf** [comment]
Yes. I extracted them from one commit to make reviewing easier and ran the `storage` tests for each. This doesn't all have to go in, feel free to suggest parts I should leave out or PR separately. This is me cleaning out my basement and doing a yard sale.

---

Review status: 15 of 20 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 1621 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrXcgJAgRdfq-s39W-:-KSrq3PbV_jbZlcmbOJD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e8135247c47ec036c757813f12a5fcac9c8b8d3/storage/client_raft_test.go#L1621)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think this test wants a bigger refactor (snapshots should be generated in the main goroutine, random splits should be in non-main goroutines). that gives the test a more natural stopping condition. not for this PR.
</details>
Done.

---

*[storage/client_raft_test.go, line 1640 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrWi7aPxEgPUGAmN9C:-KSrlzFGXyGlMqa7P3K3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e8135247c47ec036c757813f12a5fcac9c8b8d3/storage/client_raft_test.go#L1640)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wrong number of parameters
</details>
Done.

---

*[storage/client_raft_test.go, line 1998 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrdGiXP8NPfhkAnjS7:-KSrmFZaxmX5-LeerxXF:b-uxd23s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b348e00ada7947b2dc16a1bcc9f1c65dd636664/storage/client_raft_test.go#L1998)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> the new version appears to take a different type in the first position with no accompanying change to the function being used. Am I missing something?
</details>
both `client.Sender`, if that's what you mean.

---

*[storage/gc_queue_test.go, line 239 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZgWCNd7ywnafsbdj:-KSro3H6Grkk8Vo8TJvw:bt8i9lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/gc_queue_test.go#L239)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wrong commit? no idea what's going on here
</details>
Moved to its real commit (the one about ReplicaCorruption, during which I made `tc.SendWrappedWith` send through tc's Store).

---

*[storage/queue.go, line 547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrY-E_cJ36tzWw3Qe3:-KSrozauzCp4btsabDo4:bc15ioa) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/queue.go#L547)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> also seems unrelated to commit message
</details>
Moved to own commit.

---

*[storage/replica_consistency_queue.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZLh2rlKCsDR2BGy7:-KSrq-_OZ2-Fe0J2A6qQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/replica_consistency_queue.go#L57)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wrap while you're here
</details>
Done.

---

*[storage/scanner.go, line 216 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZS5BED5-W_XQV0ri:-KSrpWmxKKk-JAc0bBvZ:b7u1aw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/scanner.go#L216)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> who owns the blame?
</details>
@vivekmenezes in #1640 but I'm inclined to just remove it?

---

*[storage/scanner_test.go, line 173 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZWNKcPR8JW6vNcJK:-KSrpBx_QW64Eos7Yysa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/scanner_test.go#L173)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: reverse (yoda condition)
</details>
Done.

---

*[storage/store.go, line 214 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrdwY4nEGxnpLq6DEQ:-KSrqakrDNW0mOEvgOKi:bcw91f5) ([raw file](https://github.com/cockroachdb/cockroach/blob/36454d51720fd09f3741c8c2a258eca76d703549/storage/store.go#L214)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there is substantial random junk in this commit?
</details>
Anything you'd want in its own commit or removed? I just reviewed and it's basically what it says in the message. I suppose I could shell out the `storeRangeSet` fixes but it's mostly busy work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-:-KSrlo8eyOzjaNR8jRTa:bjzceq7)*

**Comment by tamird** [comment]
mostly :lgtm: but that one commit is pretty huge. These changes are also non-trivial and should go in with the appropriate level of care (and should be reviewed by @bdarnell || @petermattis)

---

Reviewed 17 of 17 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 10 of 10 files at r13, 1 of 1 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[storage/client_raft_test.go, line 1998 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrdGiXP8NPfhkAnjS7:-KSrrJcfkcPs2ukvzjft:bq027mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b348e00ada7947b2dc16a1bcc9f1c65dd636664/storage/client_raft_test.go#L1998)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> both `client.Sender`, if that's what you mean.
</details>
Ah, that'd be it.

---

*[storage/replica_test.go, line 4663 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrswv5HUMEL96tHRaA:-KSrswv6rF4CXSNdxGJJ:by49jga) ([raw file](https://github.com/cockroachdb/cockroach/blob/354ede5e831440a1bed2794cfd7d23c552e09db6/storage/replica_test.go#L4663)):*
> ```Go
> 		destroyed := repl.mu.destroyed
> 		corrupt := repl.mu.corrupted
> 		defer repl.mu.Unlock()
> ```

no defer necessasry

---

*[storage/scanner.go, line 216 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZS5BED5-W_XQV0ri:-KSrrgfKNWcmJAgd6Z8c:b9x21tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/scanner.go#L216)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> @vivekmenezes in #1640 but I'm inclined to just remove it?
</details>
Yeah, just remove it.

---

*[storage/store.go, line 2331 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrtbTBHX7KbDEj9USw:-KSrtbTBHX7KbDEj9USx:bm8svrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/354ede5e831440a1bed2794cfd7d23c552e09db6/storage/store.go#L2331)):*
> ```Go
> // range, store, node or cluster with corresponding actions taken.
> //
> // TODO(d4l3k): when marking a Replica corrupt, must subtract its stats from
> ```

i think it's safe to say d4l3k isn't gonna get to this.

---

*[storage/store.go, line 3214 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrtq6wag6Z36wIYtyr:-KSrtq6wag6Z36wIYtys:b-daek8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/354ede5e831440a1bed2794cfd7d23c552e09db6/storage/store.go#L3214)):*
> ```Go
> 	newStoreRangeSet(s).Visit(func(repl *Replica) bool {
> 		desc := repl.Desc()
> 		if bytes.Compare(startKey, desc.EndKey) >= 0 || bytes.Compare(desc.StartKey, endKey) >= 0 {
> ```

isn't there a `Less` on keys?

---

*[storage/store.go, line 734 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSruIJhH0-DOKC-lRXc:-KSruIJhH0-DOKC-lRXd:bbehlj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0b54780da2f25211a381dc787aecfb6778b00d6/storage/store.go#L734)):*
> ```Go
> 		})
> 		if drainingLease != nil {
> 			return fmt.Errorf("lease %s is still active", drainingLease)
> ```

errors.Errorf?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-:-KSruViF9NLcQ_3UXHO5:bibxiao)*

**Comment by tschottdorf** [comment]
You mean the ReplicaCorruption commit, right? I can take that out and PR it separately. Might chop it up while I'm at it.

**Comment by tschottdorf** [comment]
I removed the ReplicaCorruption commit. Will PR that separately in several commits.

---

Review status: 4 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/queue.go, line 505 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrXw6Nt0XmO7dFsZBC:-KSrxSBj-WqD_V3Q_-Wz:b-vxtrph) ([raw file](https://github.com/cockroachdb/cockroach/blob/0796fae81d118b11868f311a859ac26941f46d4b/storage/queue.go#L505)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> seems pretty random here
</details>
Can't argue with that. Want me to just drop it?

---

*[storage/scanner.go, line 216 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrZS5BED5-W_XQV0ri:-KSrx38gl52_MBhtcT0l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab82680019e8a2b75715a4168406d24412f815f/storage/scanner.go#L216)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, just remove it.
</details>
Done.

---

*[storage/store.go, line 2331 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrtbTBHX7KbDEj9USw:-KSrxEP1T0DOS0fAdobB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/354ede5e831440a1bed2794cfd7d23c552e09db6/storage/store.go#L2331)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think it's safe to say d4l3k isn't gonna get to this.
</details>
Done.

---

*[storage/store.go, line 3214 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrtq6wag6Z36wIYtyr:-KSrxGOhbdU74apvvvKn:b-2usa6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/354ede5e831440a1bed2794cfd7d23c552e09db6/storage/store.go#L3214)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't there a `Less` on keys?
</details>
No, thanks to range-local addressing.

---

*[storage/store.go, line 734 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSruIJhH0-DOKC-lRXc:-KSrxoO8ZU2hyr41zJLf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0b54780da2f25211a381dc787aecfb6778b00d6/storage/store.go#L734)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> errors.Errorf?
</details>
Done.

---

*[storage/replica_test.go, line 4663 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrswv5HUMEL96tHRaA:-KSrwnV2LpY-wwErIH1Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/354ede5e831440a1bed2794cfd7d23c552e09db6/storage/replica_test.go#L4663)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> no defer necessasry
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-:-KSrySpaYazrq2l2slKb:but1cy1)*

**Comment by tamird** [comment]
Thanks for pulling that guy out. A second pair of eyes wouldn't hurt, though, in case I missed something in all the back and forth.

---

Reviewed 16 of 16 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, 1 of 1 files at r20, 1 of 1 files at r21, 1 of 1 files at r22, 1 of 1 files at r23, 4 of 4 files at r24, 2 of 2 files at r25, 1 of 1 files at r26.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/queue.go, line 505 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrXw6Nt0XmO7dFsZBC:-KSsBxHNNXs2SUcYa0eL:b1r7apo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0796fae81d118b11868f311a859ac26941f46d4b/storage/queue.go#L505)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Can't argue with that. Want me to just drop it?
</details>
Yeah, I'd keep the old unless there's a reason to change it.

---

*[storage/replica.go, line 3480 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsCzTmaCM-rxTpBher:-KSsCzTnQeY7U6K-6qTa:b-n9r0uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b39340f5b6de981a056279378b3135a83afa5fc/storage/replica.go#L3480)):*
> ```Go
> // truncation. If yes, the range is added to the raft log queue.
> //
> // TODO(tschottdorf): unnecessary to have this on *Replica.
> ```

should be on the store?

---

*[storage/replica.go, line 3278 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDLbwVn2CZKSyQJzz:-KSsDLbwVn2CZKSyQK--:bcygxg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica.go#L3278)):*
> ```Go
> 		return nil
> 	}
> 	ctx := r.ctx
> ```

this is used by one line below, and all the others use r.ctx =/

---

*[storage/replica.go, line 3304 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDTQ_MZWveLCtxnIV:-KSsDTQ_MZWveLCtxnIW:b-dczb7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica.go#L3304)):*
> ```Go
> 	hasLease, pErr := r.getLeaseForGossip(r.ctx)
> 	if pErr != nil {
> 		log.Warning(ctx, errors.Wrap(pErr.GoError(), "while trying to gossip first range"))
> ```

why the log (which was not present before)?

---

*[storage/replica_trigger.go, line 440 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDuvlLataN_KZ6R55:-KSsDuvlLataN_KZ6R56:b-ua7119) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica_trigger.go#L440)):*
> ```Go
> 			r.gossipFirstRange(ctx)
> 		}); err != nil {
> 			log.Infof(ctx, "unable to gossip first range: %+v", err)
> ```

heh %+v? that' s probably overkill.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-:-KSsERMjagaQdTXt7mOK:b-z2u0c7)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 8 files at r3, 1 of 17 files at r8, 2 of 16 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, 1 of 1 files at r20, 3 of 4 files at r24, 2 of 2 files at r28, 1 of 1 files at r29.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 3304 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDTQ_MZWveLCtxnIV:-KStwwArUqXAaIN4WKex:b-j9usgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica.go#L3304)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the log (which was not present before)?
</details>
Yeah, if we're returning an error it should be the caller's decision whether or not to log it.

---

*[storage/replica.go, line 3472 at r29](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KStxCJx0CbD9tnXGuIQ:-KStxCJx0CbD9tnXGuIR:b-rsjnpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f0adb6014054dd00b4429f87e3226228a94091d/storage/replica.go#L3472)):*
> ```Go
> // range is added to the split queue.
> //
> // TODO(tschottdorf): unnecessary to have this on *Replica; it should be on
> ```

Is it still true that these more naturally belong on the Store than the Replica, now that we're not introducing ReplicaRef? This one still needs access to `r.needsSplitBySize()`. 

---

*[storage/replica.go, line 3476 at r29](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KStx3-5H3dqtnxLNjEv:-KStx3-5H3dqtnxLNjEw:bgo0hzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f0adb6014054dd00b4429f87e3226228a94091d/storage/replica.go#L3476)):*
> ```Go
> func (r *Replica) maybeAddToSplitQueue() {
> 	if r.needsSplitBySize() {
> 		// TODO(tschottdorf): illegal to pass itself out as a reference.
> ```

This comment can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-:-KSu-P9lFmUP4LfOhkzt:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/queue.go, line 505 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSrXw6Nt0XmO7dFsZBC:-KSsQr0Zgz2_G_oFOqp4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0796fae81d118b11868f311a859ac26941f46d4b/storage/queue.go#L505)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, I'd keep the old unless there's a reason to change it.
</details>
Done.

---

*[storage/replica.go, line 3480 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsCzTmaCM-rxTpBher:-KSsRh0l5ace_xEBz2SL:bbtdlye) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b39340f5b6de981a056279378b3135a83afa5fc/storage/replica.go#L3480)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should be on the store?
</details>
Yes. I adressed this TODO.

---

*[storage/replica.go, line 3278 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDLbwVn2CZKSyQJzz:-KSsR9JkpOPy_mND4lnT:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica.go#L3278)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is used by one line below, and all the others use r.ctx =/
</details>
Removed.

---

*[storage/replica.go, line 3304 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDTQ_MZWveLCtxnIV:-KSsRSFPDvbM1SRdfYba:b-m4xkkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica.go#L3304)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the log (which was not present before)?
</details>
`getLeaseForGossip` only returns an error if it's an unexpected one, so it deserves to be logged.

---

*[storage/replica.go, line 3472 at r29](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KStxCJx0CbD9tnXGuIQ:-KSv3PZE_exC1FA_7iTy:bpayftg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f0adb6014054dd00b4429f87e3226228a94091d/storage/replica.go#L3472)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Is it still true that these more naturally belong on the Store than the Replica, now that we're not introducing ReplicaRef? This one still needs access to `r.needsSplitBySize()`. 
</details>
I think the method that adds to the queue should be on the Store. There's only one call site. Addressed the TODO.

---

*[storage/replica_trigger.go, line 440 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDuvlLataN_KZ6R55:-KSsS3urvowuD2v_NgdO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica_trigger.go#L440)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> heh %+v? that' s probably overkill.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622)*

**Comment by tschottdorf** [comment]
Review status: 14 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[storage/replica.go, line 3304 at r25](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KSsDTQ_MZWveLCtxnIV:-KSv4XW9WqIIZABPwRCu:bgi9ht2) ([raw file](https://github.com/cockroachdb/cockroach/blob/07dd6c7836ab6a1df12f7818784b34f33a557cb1/storage/replica.go#L3304)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> `getLeaseForGossip` only returns an error if it's an unexpected one, so it deserves to be logged.
</details>
Oh, missed that. Changed.

---

*[storage/replica.go, line 3476 at r29](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622#-KStx3-5H3dqtnxLNjEv:-KSv4mLxHZ0HueVuRB32:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f0adb6014054dd00b4429f87e3226228a94091d/storage/replica.go#L3476)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This comment can be removed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622)*

**Comment by tamird** [comment]
Reviewed 15 of 15 files at r30, 4 of 4 files at r31, 2 of 2 files at r32, 1 of 1 files at r33, 1 of 1 files at r34, 1 of 1 files at r35.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622)*

**Comment by tschottdorf** [comment]
Checklist:

[ ] audit dependencies - @tamird
[ ] change default branch - @tschottdorf 
[ ] compile merge queue for waiting PRs - @petermattis 

Teamcity should work out of the box.

**Comment by tamird** [comment]
Reviewed 2 of 7 files at r38, 1 of 1 files at r41, 1 of 1 files at r42, 8 of 10 files at r45, 3 of 4 files at r46, 1 of 2 files at r47, 1 of 1 files at r48, 1 of 1 files at r49, 1 of 1 files at r50.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9622)*

**Pull request merged**
