### PR TITLE
clusterversion,migrations,*: remove pre-21.2 cluster versions

### LINKED ISSUE #71708: clusterversion: bump min-supported version to 21.2
**Describe the problem**

This issue tracks the work necessary to bump the min supported binary version on master. It'll need to be done before we cut any release for 22.1

https://github.com/cockroachdb/cockroach/blob/6d4ef6f4287db9b91e16cd815d4e58b94671713f/pkg/clusterversion/cockroach_versions.go#L507-L512

When doing so, we'll want to update some of our tests to override the min supported binary version for the reasons stated in https://github.com/cockroachdb/cockroach/pull/69828#issuecomment-946306532.

### PR DESCRIPTION
**Pull request by dt**
This removes all 21.1 to 21.2 cluster versions, as well as the associated cluster version checks, migrations, and migration tests, and then bumps the minimum binary version to 21.2.

Fixes #71708.

### CODE REVIEW

**Comment by dt** [comment]
For the most part, if the gates were just simple `if !version.IsActive { return x }` or something, I just removed the block, and even if it was a little more complicated, like `args = [x]; if version { args = append(args, y) }; foo(args)` I still tried to mostly inline it such that it looked natural (i.e. remove that `append` and make it `args = [x, y]`). 

However for just a couple more complicated cases that were referring to <21.2 versions that needed to be replaced when those were deleted, I added a placeholder `clusterversion.TODOPre21_2` alias for 21.2 that should have the same effect as what was there (it is always true, since the code today should never run in a <21.2 cluster) until it can be removed/updated, but allows deleting those old versions in the meantime.

**Review by postamar — APPROVED** [review]
Thanks for doing this. This looks good to me. Just one substantial comment, which might reasonably be considered as out of scope for this change.

> Reviewed 88 of 88 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74270#-:-Ms0cjQi5PYM1ONVxSiL:b-2m90l2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @irfansharif, and @samiskin)

___
*[pkg/sql/logictest/logic.go, line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74270#-Ms0Zg0R3-J3CtNGG9se:-Ms0Zg0R3-J3CtNGG9sf:b4u8t8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/053fe7d00681a49c9fc0b30c5ea780524cc0905a/pkg/sql/logictest/logic.go#L606)):*
> ```Go
> 		disableUpgrade:      true,
> 	},
> 	{
> ```

Ideally, shouldn't this be replaced by a `local-mixed-21.2-22.1`? I understand that we don't have a 22.1 version yet and for good reason, but perhaps we could instead redefine this test as
```
		bootstrapVersion:    clusterversion.TestingBinaryMinSupportedVersion,
		binaryVersion:       clusterversion.TestingBinaryVersion,
```
and give it a better name? It's not really "mixed" anyway, the name gives the wrong impression; as I understand it, the test's real purpose is to exercise the version gates.
___
*[pkg/sql/pgwire/testdata/pgtest/notice, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74270#-Ms0_4-jBHQWaLj9-hBP:-Ms0_4-jBHQWaLj9-hBQ:b-atcmn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9388505f29f96d10b3b84e590ea18aa26eca508/pkg/sql/pgwire/testdata/pgtest/notice#L58)):*
> ```
> CommandComplete
> ----
> {"Severity":"NOTICE","SeverityUnlocalized":"","Code":"00000","Message":"the data for dropped indexes is reclaimed asynchronously","Detail":"","Hint":"The reclamation delay can be customized in the zone configuration for the table.","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"drop_index.go","Line":538,"Routine":"dropIndexByName","UnknownFields":null}
> ```

If I had a dollar for every time I saw this line number change in a PR...

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @irfansharif, @postamar, and @samiskin)

___
*[pkg/sql/logictest/logic.go, line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74270#-Ms0Zg0R3-J3CtNGG9se:-Ms0pP0JDdDNMYA569rf:b-mrszub) ([raw file](https://github.com/cockroachdb/cockroach/blob/053fe7d00681a49c9fc0b30c5ea780524cc0905a/pkg/sql/logictest/logic.go#L606)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Ideally, shouldn't this be replaced by a `local-mixed-21.2-22.1`? I understand that we don't have a 22.1 version yet and for good reason, but perhaps we could instead redefine this test as
```
		bootstrapVersion:    clusterversion.TestingBinaryMinSupportedVersion,
		binaryVersion:       clusterversion.TestingBinaryVersion,
```
and give it a better name? It's not really "mixed" anyway, the name gives the wrong impression; as I understand it, the test's real purpose is to exercise the version gates.

</blockquote></details>

Hm. I'm not sure. 

I think it sorta makes sense to delete the `X -> Y` config and then add a separate new `Y -> Z` config for new tests rather than having one config that is  `getPrev() -> getNow()` which dynamically resolves its prev and now, because the tests that are using this config are explicitly testing behavior of _specifically_ `X` to `Y`, and we delete those tests when the code/behavior they testing is removed after the release.

That said, we could remove this now and then decide later that we do want the dynamic/generic config later so I do think I want to call it out of scope for now.

**Review by postamar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @irfansharif, and @samiskin)

___
*[pkg/sql/logictest/logic.go, line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74270#-Ms0Zg0R3-J3CtNGG9se:-Ms0uJdV-jDRml7yeqtq:b-s8mrbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/053fe7d00681a49c9fc0b30c5ea780524cc0905a/pkg/sql/logictest/logic.go#L606)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Hm. I'm not sure. 

I think it sorta makes sense to delete the `X -> Y` config and then add a separate new `Y -> Z` config for new tests rather than having one config that is  `getPrev() -> getNow()` which dynamically resolves its prev and now, because the tests that are using this config are explicitly testing behavior of _specifically_ `X` to `Y`, and we delete those tests when the code/behavior they testing is removed after the release.

That said, we could remove this now and then decide later that we do want the dynamic/generic config later so I do think I want to call it out of scope for now.
</blockquote></details>

You're correct, I hadn't fully thought this through.

**Comment by celiala** [comment]
Thank you for taking this on, David! 

(referencing myself @celiala here so I can follow along and update release process docs/runbooks accordingly)

**Review by jbowens — APPROVED** [review]
Storage bits :lgtm: 

> Reviewed 4 of 88 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74270#-:-MsB8U01Dhj_gdVC_JP6:b-dh11i4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @irfansharif, @postamar, and @samiskin)

**Comment by dt** [comment]
TFTRs!

bors r=postamar

**Pull request merged**
