### PR TITLE
cli: compute --drain-wait based on cluster setting values

### LINKED ISSUE #98388: cli: the `--drain-wait` arg for the `drain` command should check the `server.shutdown.*_wait` cluster settings
**Is your feature request related to a problem? Please describe.**

We have this guidance in our docs right now. https://www.cockroachlabs.com/docs/stable/node-shutdown.html#drain-timeout

> --drain-wait sets the timeout for [all draining phases](https://www.cockroachlabs.com/docs/stable/node-shutdown.html#draining) and is not related to the server.shutdown.drain_wait cluster setting, which configures the "unready phase" of draining. The value of --drain-wait should be greater than the sum of [server.shutdown.drain_wait](https://www.cockroachlabs.com/docs/stable/node-shutdown.html#server-shutdown-drain_wait), [server.shutdown.connection_wait](https://www.cockroachlabs.com/docs/stable/node-shutdown.html#server-shutdown-connection_wait), [server.shutdown.query_wait](https://www.cockroachlabs.com/docs/stable/node-shutdown.html#server-shutdown-query_wait) times two, and [server.shutdown.lease_transfer_wait](https://www.cockroachlabs.com/docs/stable/node-shutdown.html#server-shutdown-lease_transfer_wait).

This is pretty easy for anyone to miss. The impact of not setting `--drain-wait` high enough is that the drain command will be cancelled, and node shutdown will proceed non-gracefully.

**Describe the solution you'd like**

The code that uses the `--drain-wait` argument should first check the values of server.shutdown.drain_wait, server.shutdown.connection_wait, server.shutdown.query_wait, and server.shutdown.lease_transfer_wait, and if needed, increase the value of `--drain-wait` to be larger than our recommendation.

**Describe alternatives you've considered**

Instead of automatically computing  `--drain-wait`, we could fail loudly and tell the user to explicitly set `drain-wait` to an appropriate value.

Jira issue: CRDB-25243

### PR DESCRIPTION
**Pull request by rafiss**
This includes a few commits related to draining

---

### cli: compute --drain-wait based on cluster setting values

fixes https://github.com/cockroachdb/cockroach/issues/98388

Release note (cli change): The --drain-wait argument for the `drain` command will be automatically increased if the command detects that it is smaller than the sum of server.shutdown.drain_wait, server.shutdown.connection_wait, server.shutdown.query_wait times two, and server.shutdown.lease_transfer_wait.

This recommendation was already documented, but now the advice will be applied automatically.

---

### sql: fix check for closing connExecutor during draining

This fixes a minor bug in which the connection would not get closed at
the earliest possible time during server shutdown.

The connection is supposed to be closed as soon as we handle a Sync
message when the conn_executor is in the draining state and not in a
transaction. Since the transaction state was checked before state
transitions occurred, this would cause the connection to remain open for
an extra bit of time.

---

### roachtest: enhance drain test

The test now does much more:
- Checks that --drain-wait is automatically increased if it is set lower
  than the cluster settings require.
- Check that the /health?ready=1 endpoint fails during the drain_wait
  period.
- Check for the proper error message during the connection_wait phase.
- Check for the proper error message when trying to begin a new
  query/transaction  during the query_wait phase.
- Check that an open transaction is allowed to continue during the
  query_wait phase.
- Check for the proper error message when a query is canceled during
  shutdown.

### CODE REVIEW

**Comment by rafiss** [comment]
I'm investigating where this should be tested. It looks like roachtest/tests/drain.go might be best.

**Review by ZhouXing19 — DISMISSED** [review]
I reviewed the first and third commit. For the second commit, I'm not familiar with txn state transition so I would like to have others finalize the review. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-:-NQRwI550N2yodNcBrqG:b-31s6ot)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, @rafiss, and @srosenberg)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQREYkg3KRzbYpf2YQu):*
According to the code, if the `--drain-wait` is zero, we don't auto-recompute the wait time. Is this intentional? If so, maybe here it can be updated to "if the command detects that it's of positive duration but smaller than the sum ..."
___
*[`pkg/cli/rpc_node_shutdown.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQRDDQo6kG5Q92br-nl:-NQRDDQo6kG5Q92br-nm:b-mw9n20) ([raw file](https://github.com/cockroachdb/cockroach/blob/94da7b4cc5f4b76d3c92b18ca25ecff2b547a3b7/pkg/cli/rpc_node_shutdown.go#L95)):*
> ```Go
> 			"cluster settings require a value of at least %s; using the larger value",
> 			drainCtx.drainWait, minWait)
> 		drainCtx.drainWait = minWait + 10*time.Second
> ```

I'm not sure why we have these additional 10 seconds here. Also, should we instead log `using the lager value {minWait + 10 * time.Second}`?
___
*[`pkg/cmd/roachtest/tests/drain.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQRvJor4eaJAI_LubJz:-NQRvJor4eaJAI_LubK-:bo62yqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f38303be7c75cf7e695d50be75a2632efa8962/pkg/cmd/roachtest/tests/drain.go#L258)):*
> ```Go
> 		}
> 		if err == nil {
> 			return errors.New("expected pg_sleep query to fail")
> ```

Is this code reachable? if `err == nil`, then `testutils.IsError(err, "(query execution canceled|server is shutting down|connection reset by peer|unexpected EOF)")` is false, and it will just reach `return nil`.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, @srosenberg, and @ZhouXing19)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQREYkg3KRzbYpf2YQu):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

According to the code, if the `--drain-wait` is zero, we don't auto-recompute the wait time. Is this intentional? If so, maybe here it can be updated to "if the command detects that it's of positive duration but smaller than the sum ..."
</blockquote></details>

yes, i should document that. 0 just means "no timeout"
___
*[`pkg/cli/rpc_node_shutdown.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQRDDQo6kG5Q92br-nl:-NQRxL280At6RMk0vJuV:b-ulgl3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/94da7b4cc5f4b76d3c92b18ca25ecff2b547a3b7/pkg/cli/rpc_node_shutdown.go#L95)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I'm not sure why we have these additional 10 seconds here. Also, should we instead log `using the lager value {minWait + 10 * time.Second}`?
</blockquote></details>

it's basically just a little bit of buffer. yeah i will fix that log message
___
*[`pkg/cmd/roachtest/tests/drain.go` line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQRvJor4eaJAI_LubJz:-NQRxgprDSiRe4t5zLUb:bgpqeqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f38303be7c75cf7e695d50be75a2632efa8962/pkg/cmd/roachtest/tests/drain.go#L258)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Is this code reachable? if `err == nil`, then `testutils.IsError(err, "(query execution canceled|server is shutting down|connection reset by peer|unexpected EOF)")` is false, and it will just reach `return nil`.
</blockquote></details>

whoops, i shouldn't have the `!`. nice catch

**Comment by rafiss** [comment]
commit #2 i can explain: it just moves that check to the end of the function, which is after the state transitions occur: https://github.com/cockroachdb/cockroach/blob/2d633784329ae8a1d14854a827db978296e0ed6c/pkg/sql/conn_executor.go#L2185

i think you're able to review it :)

**Review by knz — COMMENTED** [review]
Like Jane, i looked at 1st and 3rd commit, and the 2nd one got me a bit confused. Maybe more words to explain what is going on in the commit message would help.

Otherwise i really like this!

> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-:-NQS7FJm8gRc8-Dn62wj:bb4ob79)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, @srosenberg, and @ZhouXing19)

___
*[`pkg/sql/conn_executor.go` line 2131 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQS6qRXC_bSZFgkl6sv:-NQS6qRXC_bSZFgkl6sw:b-tg371q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b05859dc00d24f7ba4c033f47aa7147c4403c096/pkg/sql/conn_executor.go#L2131)):*
> ```Go
> 			// a Sync is processed.
> 			defer func() {
> 				if ex.idleConn() {
> ```

Where is the res.Close call moved to?

**Review by rafiss — COMMENTED** [review]
i've added details to the commit message that should add more clarity.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-:-NQSCJQ-1k-Cf5bqYKAa:bdb1ewo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, @srosenberg, and @ZhouXing19)

___
*[`pkg/sql/conn_executor.go` line 2131 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-NQS6qRXC_bSZFgkl6sv:-NQSCCt944OzgcMDEzG_:bpzaks0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b05859dc00d24f7ba4c033f47aa7147c4403c096/pkg/sql/conn_executor.go#L2131)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Where is the res.Close call moved to?
</blockquote></details>

now we use the Close call that occurs during the normal message handling / state transitions, here: https://github.com/cockroachdb/cockroach/blob/2d633784329ae8a1d14854a827db978296e0ed6c/pkg/sql/conn_executor.go#L2238

**Review by knz — APPROVED** [review]
thanks indeed this helps.

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98390#-:-NQSEHfU5nIS33wKVz-P:b-m9wj57)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @srosenberg, and @ZhouXing19)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
