### PR TITLE
build: fix nightly stress issue posting

### PR DESCRIPTION
**Pull request by benesch**
https://github.com/cockroachdb/cockroach/pull/27287 broke stress jobs by not accounting for the fact that different versions of Make output differently-formatted informational messages. See the first commit message for details.

Here's an example of a stress job that failed to post: https://teamcity.cockroachdb.com/viewLog.html?buildId=771835&buildTypeId=Cockroach_Nightlies_Stress&tab=buildLog

/cc @tamird perhaps you want to take a look too?

### CODE REVIEW

**Review by tamird — CHANGES_REQUESTED** [review]
Just sayin': the previous implementation needed to deal with random unexpected input so it needed untrimmed fixtures.

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-:-LHAGFCB5LYZpnhzWbG4:b-82ft31)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEPNbCRKnlEf0r54N:-LHAEPNbCRKnlEf0r54O:b5l3mfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L13)):*
> ```Shell
> exit_status=0
> 
> build/builder.sh go install ./pkg/cmd/github-post
> ```

why change this?
___
*[build/teamcity-stress.sh, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEIcA8Gsu7RxIvF1o:-LHAEIcA8Gsu7RxIvF1p:bqwqrr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L21)):*
> ```Shell
> 		 STRESSFLAGS='-maxruns 100 -maxfails 1 -stderr' \
> 		 2>&1 \
>     | tee artifacts/stress.log \
> ```

what's going on with the whitespace here?
___
*[build/teamcity-stress.sh, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAERTSAOXJ964t8bZ6:-LHAERTSAOXJ964t8bZ7:b-uqdqwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L26)):*
> ```Shell
> if [ $exit_status -ne 0 ]; then
>     build/builder.sh env \
> 		     GITHUB_API_TOKEN="$GITHUB_API_TOKEN" \
> ```

why undo the `env` dance here but not above? i think i'd leave it in both places
___
*[pkg/cmd/github-post/main.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAFeil1UtbonGrj5_i:-LHAFeil1UtbonGrj5_j:b-6gl7gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L57)):*
> ```Go
> 	f func(ctx context.Context, packageName, testName, testMessage, authorEmail string) error,
> ) error {
> 	var inputBuf bytes.Buffer
> ```

whoa, why is this removed? the idea is to pass through the entire output in case of failure. You're making a lot more changes here than the commit message claims.
___
*[pkg/cmd/github-post/main.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEebF5AYN78xOgS04:-LHAEebF5AYN78xOgS05:b9fh82c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L66)):*
> ```Go
> 
> 	type TestEvent struct {
> 		//lint:ignore U1000 we disallow unused fields.
> ```

this comment explains why the field is included in the struct despite being unused, and that reason is the call to `dec.DisallowUnknownFields` above. The previous language is therefore clearer.
___
*[pkg/cmd/github-post/main.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEsB-53Qd-vp725sr:-LHAEsB-53Qd-vp725ss:btt8vgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L83)):*
> ```Go
> 	type TestEvent struct {
> 		//lint:ignore U1000 we disallow unknown fields.
> 		Time    time.Time // encodes as an RFC3339-format string
> ```

This is the phrasing used in https://godoc.org/cmd/test2json.
___
*[pkg/cmd/github-post/main.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAFNfmDYN4Mpf8WF0P:-LHAFNfmDYN4Mpf8WF0Q:b-fpe9su) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L109)):*
> ```Go
> 				delete(failures, id)
> 			}
> 		} else if te.Action == "output" {
> ```

this is the make output, yeah? perhaps a comment (but i'd rather you just back out the removal of `inputBuf` because it's important to have all the output if we can't find the failing test).
___
*[pkg/cmd/github-post/main.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAF1vT0SZ4hfn8W7eI:-LHAF1vT0SZ4hfn8W7eJ:b-nwyo6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L114)):*
> ```Go
> 		}
> 
> 		packageName := te.Package
> ```

If we ever decide to run multiple packages on a builder, you'll want to preserve this.

**Review by benesch — COMMENTED** [review]
> Just sayin': the previous implementation needed to deal with random unexpected input so it needed untrimmed fixtures.

But all 7MiB?! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-:-LHAOs6DCwcngyvwJX-W:bv48uts)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEPNbCRKnlEf0r54N:-LHAM9ul8_Zt2yMf9GOc:b-1a20uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why change this?
</blockquote></details>

Because it's mind bending to have a build/builder.sh invocation with a pipeline _inside_ the builder. At least I can't figure out how to do it cleanly. So we tend usually pipe to a program outside the builder. (This is how teamcity-test.sh works with go-test-teamcity, at least.)
___
*[build/teamcity-stress.sh, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEIcA8Gsu7RxIvF1o:-LHAMTXyA06C3qSC4iUt:b-jp6fth) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what's going on with the whitespace here?
</blockquote></details>

The whitespace in this whole file is screwy. (Lines above are tabs; these two are spaces.) I'll leave that cleanup to another commit though. Restored the original screwy formatting for now.
___
*[build/teamcity-stress.sh, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAERTSAOXJ964t8bZ6:-LHAMaKI7fgK7iQh47rt:b4hyrnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why undo the `env` dance here but not above? i think i'd leave it in both places
</blockquote></details>

github-post is now invoked outside the builder so all env variables are available. `go tool test2json` has to be invoked inside the builder though because the TC agents are still running Go 1.9 and test2json started shipping in Go 1.10.
___
*[pkg/cmd/github-post/main.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAFeil1UtbonGrj5_i:-LHAOR7B5_QjSVMv9v-1:bhfak1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L57)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

whoa, why is this removed? the idea is to pass through the entire output in case of failure. You're making a lot more changes here than the commit message claims.
</blockquote></details>

Yeah, but the entire output is a bunch of unreadable JSON garbage now. If it really is a failure in Make, before `go test` is invoked, looking at package-level Output events works perfectly. If it's something more complicated, well, there was a good chance you were going to have to go look at the TeamCity log anyway, if only to not have to stare at a bunch of JSON.
___
*[pkg/cmd/github-post/main.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEebF5AYN78xOgS04:-LHAMpQaEV0rB4jwo0PR:bd87itv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this comment explains why the field is included in the struct despite being unused, and that reason is the call to `dec.DisallowUnknownFields` above. The previous language is therefore clearer.
</blockquote></details>

Oh, I misunderstood what the comment was trying to explain. I thought it was trying to explain that we have a unused linter. How does "dec disallows unknown fields" sound? To make it clear it's the JSON decoder that disallows unknown fields.
___
*[pkg/cmd/github-post/main.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEsB-53Qd-vp725sr:-LHANWxe6zdjhyesFeiz:b-i7dktv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This is the phrasing used in https://godoc.org/cmd/test2json.
</blockquote></details>

Well that seems like an upstream typo, no? Thanks, though. I reverted that.
___
*[pkg/cmd/github-post/main.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAFNfmDYN4Mpf8WF0P:-LHAN_sW3oKHQDomE_O-:bz4hspj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L109)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is the make output, yeah? perhaps a comment (but i'd rather you just back out the removal of `inputBuf` because it's important to have all the output if we can't find the failing test).
</blockquote></details>

Yeah, plus any other garbage that's printed outside the context of a test, like "Random seed: -xxx". Added a comment.
___
*[pkg/cmd/github-post/main.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAF1vT0SZ4hfn8W7eI:-LHANnTa2LXBaS3Rym2h:bar979o) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

If we ever decide to run multiple packages on a builder, you'll want to preserve this.
</blockquote></details>

Well, if we ever want to run multiple packages we need to run `go test -json` and not `go tool test2json`, which only works on a single package. So we're screwed in a couple different directions. I'd rather not overgeneralize yet.

**Review by tamird — CHANGES_REQUESTED** [review]
I'll admit I didn't look at the size :)

Looks like you forgot to push the changes that your comments describe.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-:-LHASFA2Bb5FM_BDze_E:b-jzzp5n)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEPNbCRKnlEf0r54N:-LHASIpADhcql9FSruxx:b-prrsm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L13)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Because it's mind bending to have a build/builder.sh invocation with a pipeline _inside_ the builder. At least I can't figure out how to do it cleanly. So we tend usually pipe to a program outside the builder. (This is how teamcity-test.sh works with go-test-teamcity, at least.)
</blockquote></details>

Is it mind bending? I believe the idea was to control the toolchain, including the one used to build this program.
___
*[build/teamcity-stress.sh, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAERTSAOXJ964t8bZ6:-LHASeyD8Qg1IbNYXsWN:b-fpobet) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L26)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

github-post is now invoked outside the builder so all env variables are available. `go tool test2json` has to be invoked inside the builder though because the TC agents are still running Go 1.9 and test2json started shipping in Go 1.10.
</blockquote></details>

Yeah, this is exactly the sort of complication that _never_ using the TC agents' toolchain avoids.
___
*[pkg/cmd/github-post/main.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAFeil1UtbonGrj5_i:-LHASsOG4ySavRkrw8ZK:bwvlthd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L57)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, but the entire output is a bunch of unreadable JSON garbage now. If it really is a failure in Make, before `go test` is invoked, looking at package-level Output events works perfectly. If it's something more complicated, well, there was a good chance you were going to have to go look at the TeamCity log anyway, if only to not have to stare at a bunch of JSON.
</blockquote></details>

OK, agreed.
___
*[pkg/cmd/github-post/main.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEebF5AYN78xOgS04:-LHASWA58fKFo9eflPbl:b-xxfr03) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L66)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Oh, I misunderstood what the comment was trying to explain. I thought it was trying to explain that we have a unused linter. How does "dec disallows unknown fields" sound? To make it clear it's the JSON decoder that disallows unknown fields.
</blockquote></details>

Sure, that sounds better.

**Review by tamird — CHANGES_REQUESTED** [review]
Another thing to occurs to me: when I made the change to use `-json`, I had to remove `-v` which was previously there, because the flags are mutually exclusive. It seems to me that `test2json` is not exclusive with `-v `, but I also don't know why `-json` and `-v` *are* mutually exclusive, and it's not clear to me if we should restore `-v` or omit it, or if this approach of passing everything through test2json is sensible for other reasons. Perhaps we should just teach this make target to send its output to a file so we can keep `-json` and still omit the Make output from what we send into `github-post`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-:-LHAUUVBALmrZwJhhNlC:b-nptdc6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/github-post/main.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAF1vT0SZ4hfn8W7eI:-LHATyjl-e0z7rWmBtfn:bhoco9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L114)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Well, if we ever want to run multiple packages we need to run `go test -json` and not `go tool test2json`, which only works on a single package. So we're screwed in a couple different directions. I'd rather not overgeneralize yet.
</blockquote></details>

Are you saying that `test2json` produces output that does not list the package name, or that it blows up if you feed it input from multiple packages?

Perhaps that question deserves a comment?

**Review by benesch — COMMENTED** [review]
Ugh, looks like the push from my work laptop failed. I'll get back to this tomorrow.

>  when I made the change to use -json, I had to remove -v which was previously there

`go test -json -v ./pkg/util/duration` works fine for me?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-:-LHBSMST5omPuv6TbRMG:bm3jv85)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEPNbCRKnlEf0r54N:-LHE03Lg6JlJHb4NCIqA:bs0jukl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Is it mind bending? I believe the idea was to control the toolchain, including the one used to build this program.
</blockquote></details>

OK, I rewrote the whole script to avoid invoking the builder multiple times. PTAL.
___
*[build/teamcity-stress.sh, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEIcA8Gsu7RxIvF1o:-LHDrUk603JkPss1PLVV:b19ju6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L21)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

The whitespace in this whole file is screwy. (Lines above are tabs; these two are spaces.) I'll leave that cleanup to another commit though. Restored the original screwy formatting for now.
</blockquote></details>

Superseded by the rewrite. Everything uses spaces now.
___
*[build/teamcity-stress.sh, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAERTSAOXJ964t8bZ6:-LHE0DiN8Nj6uvWda_fZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/build/teamcity-stress.sh#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Yeah, this is exactly the sort of complication that _never_ using the TC agents' toolchain avoids.
</blockquote></details>

Done.
___
*[pkg/cmd/github-post/main.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEebF5AYN78xOgS04:-LHDsNtb0iG1lRMIknqF:b-kiy52u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Sure, that sounds better.
</blockquote></details>

Actually, why are we even disallowing unknown fields? That seems likely to break backwards compatibility if upstream decides to emit additional fields in later versions of Go. Plus, since we're no longer using `Package`, we're ignoring as many of these fields as we're using.

I've turned off `DisallowUnknownFields` and elided the unused fields from the struct.
___
*[pkg/cmd/github-post/main.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEsB-53Qd-vp725sr:-LHE0cn35WiTXY2Tbgdb:br7hp7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L83)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Well that seems like an upstream typo, no? Thanks, though. I reverted that.
</blockquote></details>

Actually, I removed the field entirely. See above.
___
*[pkg/cmd/github-post/main.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAF1vT0SZ4hfn8W7eI:-LHDrx202YaoPJhBB5pR:b-44rgo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L114)):*
Well, both. From the [docs](https://golang.org/cmd/test2json/):

> Note that test2json is only intended for converting a single test binary's output. To convert the output of a "go test" command, use "go test -json" instead of invoking test2json directly.

testj2son spits out whatever package name you tell it to with `-p PKG`, or none at all if you don't pass `-p`. Didn't seem worth threading $PKG through test2json.

**Review by tamird — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHE1dO732qq4PCpHt86:-LHE1dO732qq4PCpHt87:b-sh7fyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c073bb6841a15157b8cce8910004329ab740ed9/build/teamcity-stress.sh#L6)):*
> ```Shell
> export BUILDER_HIDE_GOPATH_SRC=1
> 
> source "$(dirname "${0}")/teamcity-support.sh"
> ```

nit: why change `${0}` to `$0`? other scripts seem to use the brace version.
___
*[pkg/cmd/github-post/main.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEebF5AYN78xOgS04:-LHE2MkR8PVcU2fmQum8:b5nbmqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L66)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Actually, why are we even disallowing unknown fields? That seems likely to break backwards compatibility if upstream decides to emit additional fields in later versions of Go. Plus, since we're no longer using `Package`, we're ignoring as many of these fields as we're using.

I've turned off `DisallowUnknownFields` and elided the unused fields from the struct.
</blockquote></details>

Yeah, that's the whole point. If upstream decides to add fields, we want to know, and this won't break anything until we actually upgrade the builder's toolchain, at which point I think we want to know that this changed.
___
*[pkg/cmd/github-post/main.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAF1vT0SZ4hfn8W7eI:-LHE2ncg4ewdGBI0iTEV:b-7p9dra) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L114)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Well, both. From the [docs](https://golang.org/cmd/test2json/):

> Note that test2json is only intended for converting a single test binary's output. To convert the output of a "go test" command, use "go test -json" instead of invoking test2json directly.

testj2son spits out whatever package name you tell it to with `-p PKG`, or none at all if you don't pass `-p`. Didn't seem worth threading $PKG through test2json.
</blockquote></details>

Wait, so, are you sure we don't want to use `go test-json`?

**Review by benesch — COMMENTED** [review]
> Reviewed 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHE1dO732qq4PCpHt86:-LHEVAif2k8YOMLejqCk:b-sgngxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c073bb6841a15157b8cce8910004329ab740ed9/build/teamcity-stress.sh#L6)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: why change `${0}` to `$0`? other scripts seem to use the brace version.
</blockquote></details>

OCD. I hate the braced form. Every shell style guide I've ever seen recommends using the $0 form for positional arguments, though. I'll revert for now and address in a later cleanup.

Hilariously it was me who added the ${0} in the first place. Wonder what I was thinking.
___
*[pkg/cmd/github-post/main.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAEebF5AYN78xOgS04:-LHE_ekD1BNcUj_SCgbQ:b14pixi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebb9fb29b3fb8c79bf55f7e8d0ac0035c9f57a3/pkg/cmd/github-post/main.go#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Yeah, that's the whole point. If upstream decides to add fields, we want to know, and this won't break anything until we actually upgrade the builder's toolchain, at which point I think we want to know that this changed.
</blockquote></details>

Yeah, and the failure mode is that github-post will exit with an error without posting an issue. We probably won't notice until someone realizes that stress builds haven't posted an issue in a few weeks. I think it's better to be tolerant of new fields. It seems unlikely that they'll change the semantics of any of the existing fields.
___
*[pkg/cmd/github-post/main.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-LHAF1vT0SZ4hfn8W7eI:-LHEFdG5CbuPLFEacPXN:b-fl9lod) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9e280308bc99a7c27ae4d2f83ad3dea3faf57e/pkg/cmd/github-post/main.go#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Wait, so, are you sure we don't want to use `go test-json`?
</blockquote></details>

I mean, we would ideally, but that requires yet another Make goal (`stressjson`?) that redirects its output to a file. (Folks run `make stress` all the time and will send me complaints if it suddenly starts vomiting JSON somewhere noticeable.)

I am planning to remove all the test targets from the Makefile and replace them with something better because Make is terrible as a task runner. E.g., we'll eventually run `crgo test` and `crgo stress`, where `crgo` is a thin wrapper around the Go command. This is likely to happen before we ever need to adapt this code for stressing multiple packages at once.

**Review by tamird — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r5, 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-:-LHErPct-9XEcS9pfv1n:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by benesch — COMMENTED** [review]
:bow: TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27414#-:-LHEsJlf-b7a4w3MoAxG:b-gp19uy)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by benesch** [comment]
bors r=tamird

**Pull request merged**
