### PR TITLE
sql: add new CREATEROLE system privilege

### PR DESCRIPTION
**Pull request by andyyang890**
This patch adds a new `CREATEROLE` system privilege, which is analogous
to the existing `CREATEROLE` role option, but can also be inherited
by role membership.

Informs #103237

Release note (sql change): There is now a `CREATEROLE` system privilege,
which is analogous to the existing `CREATEROLE` role option, but can
also be inherited by role membership.

### CODE REVIEW

**Review by annrpom — APPROVED** [review]
i just wanted to get my eyeballs on this - would wait for someone else to come by & approve 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-:-NcTmiC492BZsOOE10r9:br8vcwa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rafiss)

___
*[`pkg/sql/alter_role.go` line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-NcTlYEM1b7xF5Cyfu6Q:-NcTlYEN8rS51EQP-kT-:b-4ueyqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6380eeca8c57933270b423888df2fd56d15417d2/pkg/sql/alter_role.go#L322)):*
> ```Go
> 			}
> 		}
> 		if !hasSqlModify {
> ```

nit: if I am reading things correctly, would we be able to move the logic inside of this if into the other `if !hasSqlModify` down below?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109258)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/alter_role.go` line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-NcTlYEM1b7xF5Cyfu6Q:-NcTu8bm5Rg5Kon7qVaQ:bneoplk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6380eeca8c57933270b423888df2fd56d15417d2/pkg/sql/alter_role.go#L322)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

nit: if I am reading things correctly, would we be able to move the logic inside of this if into the other `if !hasSqlModify` down below?
</blockquote></details>

I kept it separate initially because the existing code separates the privilege and role option checks. It does seem really convoluted though so I've cleaned it up a bit!

**Review by rafiss — APPROVED** [review]
this looks great! i think it can be merged like this, but one idea to consider since we are going to add more of these: should we add a function that automatically take care of checking a system privilege, and falling back to the corresponding role option if there is one? it could save you a lot of `if`s

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-:-NchCOOME-Wem6dTy0u0:b-v4ay07)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @annrpom)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-Nch9saTAMVKAgyhPx18):*
nit: i would say "system privilege"
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 401 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-NchCDuI97L9Aa9yB_HZ:-NchCDuJ3yEZsdCLiC9j:bxdpxke) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f438d83592e0df266f28ac62aa3ba89269741c/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L401)):*
> ```
> subtest end
> 
> subtest create_role_priv
> ```

super nit: could you move the test over to the `alter_role_set` file?

**Review by andyyang890 — COMMENTED** [review]
Thanks for the suggestion! I've implemented a helper in https://github.com/cockroachdb/cockroach/pull/109652 and I'll rebase this PR on to that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-:-NczqWrz62fjsETxWXPK:b-c5yinv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 401 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-NchCDuI97L9Aa9yB_HZ:-NczqGY20rdwZ00kNOq6:b-umtci2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f438d83592e0df266f28ac62aa3ba89269741c/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L401)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: could you move the test over to the `alter_role_set` file?
</blockquote></details>

Would you mind elaborating on why? This isn't exercising the `ALTER ROLE ... SET` logic.

**Review by rafiss — CHANGES_REQUESTED** [review]
looks pretty good! just small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-:-Nd6sys5Dc304JaF2JwO:b7t7kwc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @annrpom)

___
*[`-- commits` line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-Nd6rTcy5gHhdrX-ILai):*
nit: can this be updated to say "`CREATEROLE` system privilege"?
___
*[`pkg/sql/alter_role.go` line 298 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-Nd6rjBT6DZ3wcj5p5dI:-Nd6rjBT6DZ3wcj5p5dJ:b-2mya0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/040a0c69af372d49573e4e41b0a6fb854cebffc8/pkg/sql/alter_role.go#L298)):*
> ```Go
> 			return nil, err
> 		}
> 		hasSqlModify, err := p.HasGlobalPrivilegeOrRoleOption(ctx, privilege.MODIFYSQLCLUSTERSETTING)
> ```

nit: can we still keep the old logic that short-circuits, so we avoid always checking all the privileges?

(it may be cleaner to write in a separate function)
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 401 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-NchCDuI97L9Aa9yB_HZ:-Nd6s5DN0HobwThOrhRx:b-4l0cc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f438d83592e0df266f28ac62aa3ba89269741c/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L401)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Would you mind elaborating on why? This isn't exercising the `ALTER ROLE ... SET` logic.
</blockquote></details>

oops i was just looking at usages of CREATEROLE

my thinking was that this file is for testing the synthetic privilege framework more so than testing the privileges themselves

maybe the `role` file then?
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 427 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-Nd6skOn0Ui3tGRBy7-B:-Nd6skOn0Ui3tGRBy7-C:b1hlwvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/040a0c69af372d49573e4e41b0a6fb854cebffc8/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L427)):*
> ```
> subtest end
> 
> subtest create_role_priv
> ```

can this test be updated to show that the CREATEROLE privilege is inherited?

e.g.
```
CREATE ROLE parent;
GRANT parent TO testuser;
GRANT SYSTEM CREATEROLE TO parent
```

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109258)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`-- commits` line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-Nd6rTcy5gHhdrX-ILai):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can this be updated to say "`CREATEROLE` system privilege"?
</blockquote></details>

Done.
___
*[`pkg/sql/alter_role.go` line 298 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-Nd6rjBT6DZ3wcj5p5dI:-NdJDU85Blb0cE2yzGz0:b-tsh0jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/040a0c69af372d49573e4e41b0a6fb854cebffc8/pkg/sql/alter_role.go#L298)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can we still keep the old logic that short-circuits, so we avoid always checking all the privileges?

(it may be cleaner to write in a separate function)
</blockquote></details>

I refactored it to short circuit. I also moved the check for `CREATEROLE` to be first since that was the original role option being checked before the `MODIFY{,SQL}CLUSTERSETTING` checks were added. Let me know if you'd like it moved back to last again.
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 401 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-NchCDuI97L9Aa9yB_HZ:-NdJECH04CTe4GMc7WPk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f438d83592e0df266f28ac62aa3ba89269741c/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L401)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

oops i was just looking at usages of CREATEROLE

my thinking was that this file is for testing the synthetic privilege framework more so than testing the privileges themselves

maybe the `role` file then?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/synthetic_privileges` line 427 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-Nd6skOn0Ui3tGRBy7-B:-NdJECwK7ZypnP8d9IG4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/040a0c69af372d49573e4e41b0a6fb854cebffc8/pkg/sql/logictest/testdata/logic_test/synthetic_privileges#L427)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can this test be updated to show that the CREATEROLE privilege is inherited?

e.g.
```
CREATE ROLE parent;
GRANT parent TO testuser;
GRANT SYSTEM CREATEROLE TO parent
```
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109258#-:-NdbJjAYDoPbBIg2vLXM:b-j4xmku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

**Comment by andyyang890** [comment]
tftr!

bors r=rafiss

**Pull request merged**
