### PR TITLE
rowexec: use the sorter's own context

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: none

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/rowexec/sorter.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85865#-N97I3vM2aEJz_m-0023:-N97I3vN8ne6EswT6GGn:b-m4lj7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/adac51242df1e729ea21ebb09fd63c776a8c1253/pkg/sql/rowexec/sorter.go#L253)):*
> ```Go
> 		}
> 
> 		if err := s.rows.AddRow(s.Ctx, row); err != nil {
> ```

`func newSortAllProcessor(` doesn't currently use the context passed to it. Should we modify it to  pass this to `sorterBase.init` and use it to initialize `ProcessorBaseNoHelper.Ctx` ?
I'm assuming there are other flows which set this up later, but I'm wondering if `newSortAllProcessor` shouldn't return a `sortAllProcessor` which is fully initialized.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/rowexec/sorter.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85865#-N97I3vM2aEJz_m-0023:-N97Lz3v9jLtgXiT0W9A:b-obi53t) ([raw file](https://github.com/cockroachdb/cockroach/blob/adac51242df1e729ea21ebb09fd63c776a8c1253/pkg/sql/rowexec/sorter.go#L253)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

`func newSortAllProcessor(` doesn't currently use the context passed to it. Should we modify it to  pass this to `sorterBase.init` and use it to initialize `ProcessorBaseNoHelper.Ctx` ?
I'm assuming there are other flows which set this up later, but I'm wondering if `newSortAllProcessor` shouldn't return a `sortAllProcessor` which is fully initialized.
</blockquote></details>

I have these fixes in #85782, but the change in this PR is somewhat orthogonal to what you're suggesting - `sortAllProcessor.fill()` is called in `sortAllProcessor.Start` where we get the correct execution `context.Context` and it is set into `s.Ctx`.

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85865#-:-N97NfqA441ir4jUnYTo:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/rowexec/sorter.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85865#-N97I3vM2aEJz_m-0023:-N97N26i3b900jtGZ1jT:b-qft2hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/adac51242df1e729ea21ebb09fd63c776a8c1253/pkg/sql/rowexec/sorter.go#L253)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I have these fixes in #85782, but the change in this PR is somewhat orthogonal to what you're suggesting - `sortAllProcessor.fill()` is called in `sortAllProcessor.Start` where we get the correct execution `context.Context` and it is set into `s.Ctx`.
</blockquote></details>

Right, I'm suggesting a general improvement, not specific to the changes in this PR. Since we're looking at this area, maybe it's worth including, but it sounds like this change is already in #85782 ?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85865#-:-N97PRjf-zrHu1mqOkk1:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/rowexec/sorter.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85865#-N97I3vM2aEJz_m-0023:-N97OkTrCcKI9atz0hhA:b-5l32tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/adac51242df1e729ea21ebb09fd63c776a8c1253/pkg/sql/rowexec/sorter.go#L253)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Right, I'm suggesting a general improvement, not specific to the changes in this PR. Since we're looking at this area, maybe it's worth including, but it sounds like this change is already in #85782 ? 
</blockquote></details>

I see. Actually the correct context to use for the whole execution is not the one passed in the constructor but the one in `Start`, so it would be incorrect (at least according to the current contract) to initialize `ProcessorBase.Ctx` in the constructor.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85865)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/rowexec/sorter.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85865#-N97I3vM2aEJz_m-0023:-N97QCen8lUZ8y7XV7YX:b-6zf3is) ([raw file](https://github.com/cockroachdb/cockroach/blob/adac51242df1e729ea21ebb09fd63c776a8c1253/pkg/sql/rowexec/sorter.go#L253)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I see. Actually the correct context to use for the whole execution is not the one passed in the constructor but the one in `Start`, so it would be incorrect (at least according to the current contract) to initialize `ProcessorBase.Ctx` in the constructor.
</blockquote></details>

Ah, OK. Maybe that unused parameter should be removed.

**Pull request merged**
