### PR TITLE
roachprod,cli: add roachprod logs command and improve debug merge-logs 

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in three commits. The first adds a new util/flagutil package which make it easy to create regular expression and time flags. The next adopts these flags and modestly evolves the behavior of debug merge-logs to allow it to be used with non-standard file names. Lastly it adds a roachprod command which can stream logs to the terminal.

### CODE REVIEW

**Comment by ajwerner** [comment]
Somehow I got a commit into this I didn't intend to.

**Review by petermattis — COMMENTED** [review]
:lgtm: The rsync loop is interesting. I was imaging something different (see some alternate ideas below), but as long as the overhead is low enough this is fine.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-:-LThqlAM9KwvGRVCm6pZ:b435pvj)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachprod/main.go, line 866 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThoXaX7j-Eezdofopx:-LThoXaX7j-Eezdofopy:b-t8niry) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/main.go#L866)):*
> ```Go
> 
> var logsCmd = &cobra.Command{
> 	Use:   "logs",
> ```

Nit: show the positional parameters. Something like `logs <cluster> [dest]`.
___
*[pkg/cmd/roachprod/main.go, line 868 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThoqm45TOtzGxXOeol:-LThoqm45TOtzGxXOeom:bfek6wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/main.go#L868)):*
> ```Go
> 	Use:   "logs",
> 	Short: "retrieve and merge logs in a cluster",
> 	Long: `Retrieve and merge logs in a cluster
> ```

Nit: period after `cluster`.
___
*[pkg/cmd/roachprod/main.go, line 870 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThoilD1Fm0kyX45QRD:-LThoilD1Fm0kyX45QRE:b-xsy5i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/main.go#L870)):*
> ```Go
> 	Long: `Retrieve and merge logs in a cluster
> 
> the "logs" command runs until terminated. It works similarly to get but
> ```

Nit: `s/the/The/g`, `s/but/but is/g`
___
*[pkg/cmd/roachprod/main.go, line 872 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThop-sB9yobuFPwdt-:-LThop-sB9yobuFPwdt0:b-rgtchn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/main.go#L872)):*
> ```Go
> the "logs" command runs until terminated. It works similarly to get but
> specifically focused on retrieving logs periodically and then merging them
> into a single stream
> ```

Nit: period after `stream`.
___
*[pkg/cmd/roachprod/main.go, line 895 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThow4S0R8Vgd_p0ceQ:-LThow4S0R8Vgd_p0ceR:b-codmim) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/main.go#L895)):*
> ```Go
> 	logsCmd.Flags().Var(flagutil.Time(&logsTo), "to", "time to which to stream logs")
> 	logsCmd.Flags().DurationVar(&logsInterval, "interval", 200*time.Millisecond, "interval to poll logs from host")
> 	logsCmd.Flags().StringVar(&logsDir, "logs-dir", "logs", "path to the logs dir, if remote, relative to username's home dir, ignored if local")
> ```

The other per-command flags are initialized in `main`. I'd move this initialization there for consistency.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 879 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThlfvzCFAf-oIlUxbf:-LThlfw-8KwzN4x-Tlqg:breqyy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L879)):*
> ```Go
> 		var remote string
> 		if c.IsLocal() {
> 			// This here is a bit of a hack to guess that the parent of the log dir	is
> ```

Nit: extra spacing after `log dir`.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 889 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThpJG-EAZKsLMJOFIG:-LThpJG-EAZKsLMJOFIH:bw8qmrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L889)):*
> ```Go
> 			}
> 			remote = fmt.Sprintf("%s@%s:%s/", c.user(c.Nodes[idx-1]),
> 				c.host(c.Nodes[idx-1]), logDir)
> ```

The rsync command will get slower and slower over time as the number of log files grows. Is that a problem? Is there significant overhead here with the default interval of 200ms? Ah, just read the commit message talking about the mechanisms which mitigate the overhead. So I guess no concerns. Carry on.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 968 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThqJSLBOube4XJ1VWP:-LThqJSLBOube4XJ1VWQ:b-g9z6n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L968)):*
> ```Go
> 	}
> 	for to.IsZero() || prev.Before(to) {
> 		// Subtract ~1 second to deal with the flush delay in util/log
> ```

Nit: Comments on their own line should be terminated with punctuation. Golint (or something) will likely complain about this.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 969 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThnSiO-E1Jva9UJH9x:-LThnSiPBA6QLaGcnR3P:b6ckbx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L969)):*
> ```Go
> 	for to.IsZero() || prev.Before(to) {
> 		// Subtract ~1 second to deal with the flush delay in util/log
> 		t := timeutil.Now().Add(-1100 * time.Millisecond).Truncate(time.Microsecond)
> ```

The rsync / merge loop is interesting, though having to keep track of the prev timestamp is unfortunate. When you were describing this, I was imaging you'd use something like `tail -f -n +1 <log>` to get a continuous stream. That has its own difficulties, though. 

Another thought is to extend `cockroach debug merge-logs` to take a `-f/--follow` flag. That would move some of the complexity here into `debug merge-logs` which has more insight into the timestamps of entries. Not sure if that actually simplifies anything, though.

Yet another thought about how this could work: run `cockroach debug merge-logs --follow --from ... --to ...` on the remote node to get a single log stream that tails the log output. Locally write that stream to a file and display it with another `cockroach debug merge-logs --follow` on the local per-node logs.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33067)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachprod/main.go, line 895 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThow4S0R8Vgd_p0ceQ:-LTiIpdX3R2uen_G5MsC:boaqqtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/main.go#L895)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The other per-command flags are initialized in `main`. I'd move this initialization there for consistency.
</blockquote></details>

adminurlCmd was not but is now also.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 889 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThpJG-EAZKsLMJOFIG:-LTiGzKT-egvoCNFjv5Y:bljk5si) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L889)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The rsync command will get slower and slower over time as the number of log files grows. Is that a problem? Is there significant overhead here with the default interval of 200ms? Ah, just read the commit message talking about the mechanisms which mitigate the overhead. So I guess no concerns. Carry on.
</blockquote></details>

The rsync cost mitigations seem effective. The problem I've noticed is that when there are many gigabytes of logs, the binary searching of all of the 10MB files on the local machine is the bottleneck, sometimes taking seconds per iteration. I think this can be mitigated by starting the binary search towards the end of the file, seeing if there's anything of interest and then if so,  binary searching from the beginning but I'll defer that change for another diff.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 969 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThnSiO-E1Jva9UJH9x:-LTiF2IbEqucdIvLlGn3:b-kywbl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L969)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The rsync / merge loop is interesting, though having to keep track of the prev timestamp is unfortunate. When you were describing this, I was imaging you'd use something like `tail -f -n +1 <log>` to get a continuous stream. That has its own difficulties, though. 

Another thought is to extend `cockroach debug merge-logs` to take a `-f/--follow` flag. That would move some of the complexity here into `debug merge-logs` which has more insight into the timestamps of entries. Not sure if that actually simplifies anything, though.

Yet another thought about how this could work: run `cockroach debug merge-logs --follow --from ... --to ...` on the remote node to get a single log stream that tails the log output. Locally write that stream to a file and display it with another `cockroach debug merge-logs --follow` on the local per-node logs. 
</blockquote></details>

If I'm being honest it's definitely not how I had imagined doing it either. This solution grew out of a conversation with David Taylor and a quick hack that started as a bash script that worked better than I had anticipated and then converted to go that then became this. 

Ultimately I would have liked to extend merge-logs to deal with a case where it gets to the end of an open data stream, can detect that end and report it to the merged stream and then adding a mechanism to have new writes go through some separate heap waits for its oldest element to be at least some age and moves it over to the merged heap. This ought to then enable then adding support for HTTP based retrieval underneath the merging or waiting so we can remove the requirement to have the log files locally. I imagine there are a number of cases where we have HTTP access to a cluster but not SSH access. 

This approach works better than nothing but one day I'd like to write more functionality into merge logs.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-:-LTxwh_u9AM1QQ1vHtxy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 889 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThpJG-EAZKsLMJOFIG:-LTxwJGiDfJtPY_1ipSv:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L889)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The rsync cost mitigations seem effective. The problem I've noticed is that when there are many gigabytes of logs, the binary searching of all of the 10MB files on the local machine is the bottleneck, sometimes taking seconds per iteration. I think this can be mitigated by starting the binary search towards the end of the file, seeing if there's anything of interest and then if so,  binary searching from the beginning but I'll defer that change for another diff.
</blockquote></details>

SGTM
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 969 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33067#-LThnSiO-E1Jva9UJH9x:-LTxwLZtEClrIHxweijS:ben02v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c690d2448036cf319ecf3c87a4ad37ac8a609517/pkg/cmd/roachprod/install/cluster_synced.go#L969)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If I'm being honest it's definitely not how I had imagined doing it either. This solution grew out of a conversation with David Taylor and a quick hack that started as a bash script that worked better than I had anticipated and then converted to go that then became this. 

Ultimately I would have liked to extend merge-logs to deal with a case where it gets to the end of an open data stream, can detect that end and report it to the merged stream and then adding a mechanism to have new writes go through some separate heap waits for its oldest element to be at least some age and moves it over to the merged heap. This ought to then enable then adding support for HTTP based retrieval underneath the merging or waiting so we can remove the requirement to have the log files locally. I imagine there are a number of cases where we have HTTP access to a cluster but not SSH access. 

This approach works better than nothing but one day I'd like to write more functionality into merge logs.

</blockquote></details>

Might be worth dropping a `TODO(ajwerner)` comment on this method indicating that using rsync is a bit of a hack, and outlining briefly a better but more involved approach. Your future self will thank you.

**Comment by ajwerner** [comment]
bors r=petermattis

**Pull request merged**
