### PR TITLE
kv: evict leaseholder on RPC error

### PR DESCRIPTION
**Pull request by tbg**
This addresses a situation in which we would not evict a stale
leaseholder for a long time. Consider the replicas [s1,s2,s3] and
s1 is down but is the cached leaseholder, while s2 is the actual lease
holder. The RPC layer will try s1, get an RPC error, try s2 and succeed.
Since there is no NotLeaseHolderError involved, the cache would not get
updated, and so every request pays the overhead of trying s1 first.

WIP because needs testing.

Touches #23601.

Release note (bug fix): Improve request routing during node outages.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

This is kind of the converse of #3196. Since we don't know when the lease expires, we want to evict the cache on RPC errors. If we know that the lease hadn't expired yet, we'd want to stick to that node even if we did get transient RPC errors. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23885#-:-L7beYaGA-sgT39Oh3VY:bq0geni)*

**Comment by solongordon** [comment]
:LGTM:
Nice, evicting is more straightforward than trying to populate the cache with the correct value, which I had been looking at.

**Review by tbg — COMMENTED** [review]
Rebased this and added a test, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/23885#-:-LK1QeBy6arNP3L_--mU:bx0oqms)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by solongordon — APPROVED** [review]
Test looks good, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/23885#-:-LK2Gz4F63WJOaVMY1qV:b-83ch9q)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by tschottdorf** [comment]
bors r=solongoron
TFTR!

**Pull request merged**
