### PR TITLE
roachtest: add native libraries to test specification and verify

### LINKED ISSUE #81081: roachtest: simplify bootstrapping of native libs
Currently, roachtests are responsible for explicitly staging libgeos (plus any other native libs needed by future tests). E.g., roachtests which need libgeos execute the following before starting a cluster,

```
if err := c.PutE(ctx, t.L(), t.Cockroach(),  "./cockroach"); err != nil {
	t.Fatal(err)
}
if err := c.PutLibraries(ctx, "./lib"); err != nil {
	t.Fatalf("could not initialize libraries: %v", err)
}
```

The first statement stages the currently executing binary. The second statement stages libgeos and libgeos_c; these libs are linked dynamically during crdb node startup (see `initGEOS`). Note that `roachtest` initializes (see `initBinariesAndLibraries`) `libraryFilePaths` with the (local) paths of all the supported native libs (libgeos and libgeos_c at this time) found on the machine executing `roachtest` (see `findLibrary`).

Per above, `roachtest` is already aware of present native libs. Hence, `PutLibraries` appears redundant. Furthermore, it's yet another detail the test writer has to _remember_. Thirdly, without reading the test code, there isn't an easy way to see which tests require the use of native libs. Lifting this into `TestSpec` accomplishes all of the above. E.g., 

```
type TestSpec struct {
     ...
     NativeLibs          []string
}
```

During `Run`, `TestSpec` is verified wrt `NativeLibs`; if the specified libs cannot be found, then the test is aborted. Otherwise, we use `libraryFilePaths` in conjunction with `ClusterSpec` to provision a cluster and stage the native libs.

Jira issue: CRDB-15365

### PR DESCRIPTION
**Pull request by herkolategan**
This commit adds native libraries to the test specifications.
Each native library that is required should be specified by
filename.

The spec is verified in the test runner and also takes into account
whether the test is running locally or remotely. For local tests
the lib directory is verified, and for remote tests the docker lib
(amd64) directory is verified.

Verification happens before the cluster is provisioned. The test
will fail quickly if libraries are not present to support the
planned execution.

Resolves: #81081

Release justification: test-only change.
Release note: None.

### CODE REVIEW

**Review by renatolabs — CHANGES_REQUESTED** [review]
Great job! :tada: 

Question: should we make it easier for people to indicate the test needs libgeos? The only real value we ever pass to `NativeLibs` is `[]string{"libgeos.so", "libgeos_c.so"}` right now (and this may continue to be the case for the short/medium term).

Maybe something like

```go
// cluster.go
var LibGEOS = []string{"libgeos.so", "libgeos_c.so"}

// roachtest
NativeLibs: LibGEOS,
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-:-NA6ac6s0P6zBRA_tGFf:b-kq0dh6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 1646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6TYhn7SwS9jlU9Qq5:-NA6TYhn7SwS9jlU9Qq6:b-thw9dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1646)):*
> ```Go
> // at the specified location.
> func (c *clusterImpl) PutLibraries(
> 	ctx context.Context, libraryDir string, libraries []string,
> ```

Documentation needs to change to reflect that only the libraries in `libraries` will be staged.
___
*[`pkg/cmd/roachtest/cluster.go` line 1652 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6UqLIAoL709Uz0iNa:-NA6UqLIAoL709Uz0iNb:b5awpy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1652)):*
> ```Go
> 	}
> 
> 	libSet := map[string]bool{}
> ```

Nits:

* sets in Go are slightly more idiomatic if defined as `map[T]struct{}`
* maybe we don't need a set at all and linear search here is fine (adding a `contains` function to this package). Would probably increase readability too: `if !contains(libraries, filename) { continue }`
___
*[`pkg/cmd/roachtest/cluster.go` line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6XwQX8-HYOrnp8jT4:-NA6XwQYBXnHDs-QZi7i:b1dj2mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1681)):*
> ```Go
> }
> 
> func (c *clusterImpl) VerifyLibraries(requiredLibs []string) error {
> ```

This function would benefit from comments, especially if the logic involving `local` and `hasRemoteSuffix` is indeed necessary.
___
*[`pkg/cmd/roachtest/cluster.go` line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6Y6IHDQ95lH1EuCzi:-NA6Y6IHDQ95lH1EuCzj:b-vjzi8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1681)):*
> ```Go
> }
> 
> func (c *clusterImpl) VerifyLibraries(requiredLibs []string) error {
> ```

Also, could we make this a package-level function? It doesn't not use any `Cluster`-related state and only uses package-level state. Added benefit of not having to change the `Cluster` interface.
___
*[`pkg/cmd/roachtest/cluster.go` line 1682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6VbcACcD5lNjlCiwH:-NA6VbcACcD5lNjlCiwI:b-mo0nia) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1682)):*
> ```Go
> 
> func (c *clusterImpl) VerifyLibraries(requiredLibs []string) error {
> 	if len(requiredLibs) == 0 {
> ```

Nit: since `libraryFilePaths` will be fairly small for the foreseeable future, I'd just remove the short-circuit logic and let the `return nil` emerge naturally as a consequence of the empty `requiredLibs`.
___
*[`pkg/cmd/roachtest/cluster.go` line 1693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6VrH65Bdi5GkHhBGn:-NA6VrH65Bdi5GkHhBGo:bllsye9) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1693)):*
> ```Go
> 		} else if local && hasRemoteSuffix {
> 			continue
> 		}
> ```

I'm confused by the logic here. Why do we ignore libraries in `lib` if this is a remote run and vice-versa? Is it necessary? It also concerns me that this function is coupled to the directory order defined in `findBinaryOrLibrary`, so a change there could lead to this function behaving differently which is unexpected.

I also noticed that this verification will fail on my gceworker (which has SOs on both the `lib` and `lib.docker_amd64` directories) if I run the test locally.
___
*[`pkg/cmd/roachtest/cluster_test.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6YTb48-W2-k72w1-N:-NA6YTb48-W2-k72w1-O:bp98zlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster_test.go#L243)):*
> ```Go
> 			err := c.VerifyLibraries(tc.verifyLibs)
> 			if tc.expectedError != (err != nil) {
> 				t.Fatalf("expected %t, but found %t", tc.expectedError, err != nil)
> ```

Some suggestions here:

* make `expectedError` a string instead of a boolean, with the actual error message you are expecting. Makes the test stronger, and the list of test cases easier to understand.
* print the error message you got in `t.Fatalf()`. This makes the test output a lot more actionable. Right now we just inform that two booleans didn't match, but I'd have no idea what error the function returned without running it again (in this case the function is deterministic -- imagine if this was a complicated non-deterministic test!)

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

___
*[`pkg/cmd/roachtest/cluster.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA7F87U0vemIgNNd2J_:-NA7F87U0vemIgNNd2Ja:bsvdiqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L100)):*
> ```Go
> const (
> 	defaultEncryptionProbability = 1
> 	remoteLibrarySuffix          = ".docker_amd64"
> ```

Methinks this is an artifact of the make build [1] whereas the cross-compiler puts them under `BAZEL_BIN`, copies them to `lib.docker_amd64` (presumably for compatibility with make?) and symlinks `lib`[2]. Since roachtest is already on bazel, we can probably drop make compatibility, i.e., the libs should be under `/lib`. @rickystewart Does that sound right?


PS: note, we could also have `arm64` (when cross-building) although that's in scope for a follow-up PR. 

[1] https://github.com/cockroachdb/cockroach/blob/master/build/builder.sh#L147
[2] https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh#L22

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

___
*[`pkg/cmd/roachtest/tests/activerecord.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA7LL5W6mvhD57R9tNh:-NA7LL5W6mvhD57R9tNi:b-e9pewg) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/tests/activerecord.go#L257)):*
> ```Go
> 		Owner:      registry.OwnerSQLExperience,
> 		Cluster:    r.MakeClusterSpec(1),
> 		NativeLibs: []string{"libgeos.so", "libgeos_c.so"},
> ```

`findLibrary` takes care of the suffix conditional on `runtime.GOOS`; why do we need it here?

**Review by herkolategan — COMMENTED** [review]
Thanks for the thorough review @renatolabs, I appreciate it. This will definitely help me get up to speed quicker.
Suggestion on this comment makes sense to me, the thought did cross my mind as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-:-NA9Anby8zFJrDQSEobp:b-xmer2r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/cluster.go` line 1646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6TYhn7SwS9jlU9Qq5:-NA9FWV40-QnrDcpB4pF:b7udwkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1646)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Documentation needs to change to reflect that only the libraries in `libraries` will be staged.
</blockquote></details>

Good catch. I might revert this method based on previous comments, but if I keep it I'll be sure to update the documentation. 
___
*[`pkg/cmd/roachtest/cluster.go` line 1652 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6UqLIAoL709Uz0iNa:-NA9FnAV76W1zropJyN_:bj3hvu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1652)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nits:

* sets in Go are slightly more idiomatic if defined as `map[T]struct{}`
* maybe we don't need a set at all and linear search here is fine (adding a `contains` function to this package). Would probably increase readability too: `if !contains(libraries, filename) { continue }`
</blockquote></details>

Good idea, no need for cumbersome code. And thanks for the hint on how to define `sets`
___
*[`pkg/cmd/roachtest/cluster.go` line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6XwQX8-HYOrnp8jT4:-NA9G0PWDg4xWU2Ck5zj:beud8ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1681)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This function would benefit from comments, especially if the logic involving `local` and `hasRemoteSuffix` is indeed necessary.
</blockquote></details>

Yes I agree, since the reasoning behind `hasRemoteSuffix` has a troublesome history. I'm most likely going to remove this logic, but I'll add commentary.
___
*[`pkg/cmd/roachtest/cluster.go` line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6Y6IHDQ95lH1EuCzi:-NA9GQS-0qblqusVdMCv:b8ocitj) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1681)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Also, could we make this a package-level function? It doesn't not use any `Cluster`-related state and only uses package-level state. Added benefit of not having to change the `Cluster` interface.
</blockquote></details>

I was contemplating this as well! And then completely forgot about it. I'll amend.
___
*[`pkg/cmd/roachtest/cluster.go` line 1682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6VbcACcD5lNjlCiwH:-NA9Gl2104tr6rI4gZek:bqy67xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1682)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: since `libraryFilePaths` will be fairly small for the foreseeable future, I'd just remove the short-circuit logic and let the `return nil` emerge naturally as a consequence of the empty `requiredLibs`.
</blockquote></details>

Fair enough
___
*[`pkg/cmd/roachtest/cluster.go` line 1693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6VrH65Bdi5GkHhBGn:-NA9H7zZ62-kDm0Gwgxy:bmr90jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L1693)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I'm confused by the logic here. Why do we ignore libraries in `lib` if this is a remote run and vice-versa? Is it necessary? It also concerns me that this function is coupled to the directory order defined in `findBinaryOrLibrary`, so a change there could lead to this function behaving differently which is unexpected.

I also noticed that this verification will fail on my gceworker (which has SOs on both the `lib` and `lib.docker_amd64` directories) if I run the test locally.
</blockquote></details>

The libraries in `lib` and `lib.docker_amd64` should be the _same_, but for different architectures, hence you only need to copy the correct set, depending on where the test will run.

I tested this on Linux which produces `".so"` libs in `/lib` & `/lib.docker_amd64` and it passed, similar to a test like this, which should actually be part of the test suite to confirm this scenario:

```
{
	name:             "conflict both SO",
	local:            true,
	verifyLibs:       []string{"geos.so"},
	libraryFilePaths: []string{"/lib/geos.so", fmt.Sprintf("/lib.%s/geos.so", remoteLibrarySuffix)},
	expectedError:    false,
},

```
This will pass for `local: false` as well.

Having said that, this logic is hard to read and make sense of. I gave a long-winded response on a comment @srosenberg left to explain the scenario.

You are absolutely right about relying on the output of `findBinaryOrLibrary` which I believe could cause issues, especially when more than one Linux distribution is involved between local & remote.

I believe the`findBinaryOrLibrary` should be updated to only add good candidates to the list that is compatible with the target execution cluster, and would appreciate @srosenberg and your opinion on that.

The resolution here could also be to simplify this logic and to address the possible problems with `findBinaryOrLibrary` in a different PR / issue.
___
*[`pkg/cmd/roachtest/cluster_test.go` line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA6YTb48-W2-k72w1-N:-NA9MgB1ARKM83IjvoL4:b-l5kg95) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster_test.go#L243)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Some suggestions here:

* make `expectedError` a string instead of a boolean, with the actual error message you are expecting. Makes the test stronger, and the list of test cases easier to understand.
* print the error message you got in `t.Fatalf()`. This makes the test output a lot more actionable. Right now we just inform that two booleans didn't match, but I'd have no idea what error the function returned without running it again (in this case the function is deterministic -- imagine if this was a complicated non-deterministic test!)
</blockquote></details>

Makes perfect sense, thanks for the detailed explanation.
___
*[`pkg/cmd/roachtest/tests/activerecord.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA7LL5W6mvhD57R9tNh:-NA9NAn35QUZYEVHAmKh:b-1mzitm) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/tests/activerecord.go#L257)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`findLibrary` takes care of the suffix conditional on `runtime.GOOS`; why do we need it here?
</blockquote></details>

Good catch, and no good reason; this is an oversight which I shall fix.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, @rickystewart, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NA7F87U0vemIgNNd2J_:-NA9CJNq5Q-jdpHjKSRD:b-nzg35d) ([raw file](https://github.com/cockroachdb/cockroach/blob/749721eab20ce9c0b5faaa5955a3c8e79a350620/pkg/cmd/roachtest/cluster.go#L100)):*
Excuse the long-winded response, but there are some subtle intricacies that come into play here that I want to point out:

Having said that, I think you're right and there are some things here that need revision, but it might not be in the scope of this PR as it solves a niche problem that I'll try to articulate:

I tried to solve a problem here which happens when your local system is a different flavour of Linux than the target cluster for `roachtest`. In this scenario it's possible that the test will execute and use locally built incompatible libraries against the target since the libs in `"/lib"` are also `".so"`. For remote clusters the existing code assumes as long as the suffix is `".so"` it can be added to the found libraries, but in essence a cross compilation should have been done using docker. Judging by this code snippet [1] the assumption is also that the remote target cluster is always Linux based.

The question here is if we assume that remote clusters are always Linux based, can we assume that we should be checking only for binaries / libraries in the Linux target docker output (`lib.docker_amd64`), and ignore the local `"/lib"` folder since it could be incompatible with the remote target even if it contains `".so"` libs. The `FindBinaryOrLibrary` implementation already has more specific logic to look explicitly for the cross compiled version [2], and maybe this should be applicable to the libraries as well.

But I think this should be resolved in a different PR, and I should rely on the output provided by `FindLibrary` for this PR. If the `FindBinaryOrLibrary` code is incorrect in its assumption that any `".so"` will suffice for a remote cluster we can create a different issue for that.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/cluster.go#L131
[2] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/cluster.go#L201

PS:
> copies them to lib.docker_amd64 (presumably for compatibility with make?) and symlinks lib[2].

I think this might only be for _teamcity_. On a local build the `"/lib"` folder is not sym linked to `"/lib.docker_amd64"`, and my assumption is that `"/lib"` is meant for local architecture, and `"/lib.docker_amd64"` is meant for remote architecture.

**Comment by renatolabs** [comment]
> But I think this should be resolved in a different PR

I agree further improvements on the library resolution/lookup should be addressed in a different PR and this one should focus on removing `PutLibraries` from test code.

> On a local build the "/lib" folder is not sym linked to "/lib.docker_amd64", and my assumption is that "/lib" is meant for local architecture, and "/lib.docker_amd64" is meant for remote architecture.

I wonder if this was the intention. I would expect the directory order in `findBinary` to change based on whether it's a local run, but that's not the case.

**Review by herkolategan — COMMENTED** [review]
CI Failing due to https://github.com/cockroachdb/cockroach/issues/86838

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-:-NAKYjKnEpQmptZnkRub:bldwk82)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @rickystewart, @smg260, and @srosenberg)

**Comment by rickystewart** [comment]
> Methinks this is an artifact of the make build [1] whereas the cross-compiler puts them under BAZEL_BIN, copies them to lib.docker_amd64 (presumably for compatibility with make?) and symlinks lib[2]. Since roachtest is already on bazel, we can probably drop make compatibility, i.e., the libs should be under /lib. @rickystewart Does that sound right?

Your understanding is correct. I would like to see the whole `lib.docker_amd64` thing go away, although while we're supporting `make` it's probably not possible. I agree it's fine to put this stuff under `/lib` and not bother with the whole `docker_amd64` thing.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @rickystewart, @smg260, and @srosenberg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NAthnLIC9zMdKDiBUIi:-NAthnLIC9zMdKDiBUIj:b-t0pzn7) (no related file):*
@srosenberg @renatolabs ready for another pass at your leisure.

___

**Review by renatolabs — APPROVED** [review]
:lgtm:

This looks much simpler now!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-:-NBNI4jt0vL4_lut_CAb:bkqj10h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rickystewart, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/test_runner.go` line 621 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NBNHKDgBVBLzTRj1rpH:-NBNHKDgBVBLzTRj1rpI:biqjxfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbef4b557b2cce0f392833918c849dc29d273fa/pkg/cmd/roachtest/test_runner.go#L621)):*
> ```Go
> 			t.spec.Owner = oldOwner
> 		} else {
> 			c.setTest(t)
> ```

Nit: do we need this for `PutLibraries`? We could keep this call where it used to be, right after the "running test" status is posted.
___
*[`pkg/cmd/roachtest/test_runner.go` line 622 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NBNHVae9l-CYI8MtOUd:-NBNHVae9l-CYI8MtOUe:bg4gsur) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbef4b557b2cce0f392833918c849dc29d273fa/pkg/cmd/roachtest/test_runner.go#L622)):*
> ```Go
> 		} else {
> 			c.setTest(t)
> 			c.status("copying libraries")
> ```

Nit: we don't need this, as `PutLibraries` itself will print a similar message. Also, it could be confusing in the case when there are no libraries to be copied.
___
*[`pkg/cmd/roachtest/test_runner.go` line 624 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NBNHicl86QvkZ5onYZg:-NBNHicl86QvkZ5onYZh:b-vpymow) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbef4b557b2cce0f392833918c849dc29d273fa/pkg/cmd/roachtest/test_runner.go#L624)):*
> ```Go
> 			c.status("copying libraries")
> 			if len(t.spec.NativeLibs) != 0 {
> 				if err = c.PutLibraries(ctx, "./lib", t.spec.NativeLibs); err != nil {
> ```

Nit: `PutLibraries` could handle an empty `NativeLibs` slice; otherwise, callers will only have to check before calling. I know this is the only calling site right now, so this is more of a general suggestion/API comment.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86451)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @rickystewart, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster_test.go` line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86451#-NBNyiRe3BJbtyG0YZEz:-NBNyiRe3BJbtyG0YZF-:b-n0630a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fbef4b557b2cce0f392833918c849dc29d273fa/pkg/cmd/roachtest/cluster_test.go#L184)):*
> ```Go
> 
> func TestVerifyLibraries(t *testing.T) {
> 	testCases := []struct {
> ```

Forgot to mention: while not a big deal in this case specifically, it's good to keep the package's state untouched after running this test (at the end of it, the `libraryFilePaths` package variable will be set to a test value).
We can add the following at the top to that end:

```go
originalLibraryPaths = libraryFilePaths
defer func() { libraryFilePaths = originalLibraryPaths }()
```

**Comment by smg260** [comment]
backport 22.2

**Comment by smg260** [comment]
blathers backport 22.2

**Pull request merged**
