### PR TITLE
distsql: implement sorter processor core type

### PR DESCRIPTION
**Pull request by irfansharif**
Basic implementation of the `Sorter` processor core type (not optimizing for partial orderings, no speed-ups for limits). 

This corresponds to the physical implementation of a **sorting aggregator** (see Distributed SQL [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/distributed_sql.md)) sorting elements in the input stream according to a configurable set of columns. Note that this is a no-grouping aggregator and therefore it does not produce a global ordering but simply guarantees an intra-stream ordering on the physical output stream.

Part of #7587

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9224)

### CODE REVIEW

**Comment by irfansharif** [comment]
No strong opinions on some of the function/method names I've used here, namely `convertToColumnOrdering`, `convertToSpecOrdering`, and `sorter.flush`.

**Comment by RaduBerinde** [comment]
Looks great overall! But we should be using `Sort`, not heaps, it's supposed to be faster.

---

Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/distsql/data.go, line 24 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-KRAqJx-Iqtfnz5jsCWL:-KRAqJx-Iqtfnz5jsCWM:b-kahpzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b5f7765b1bae328aad5a19fc62de5231302d8cb/sql/distsql/data.go#L24)):*
> ```Go
> )
> 
> // convertColumnOrdering converts an Ordering type (as defined in data.proto)
> ```

convertTo

---

*[sql/distsql/processors.proto, line 98 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-KRArAIFlB0ybkJeED2Z:-KRArAIFlB0ybkJeED2_:b-pa0pjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b5f7765b1bae328aad5a19fc62de5231302d8cb/sql/distsql/processors.proto#L98)):*
> ```protobuf
> // SorterSpec is the specification for a "sorting aggregator". A sorting aggregator
> // sorts elements in the input stream providing a certain output order
> // guarantee regardless of the input ordering, it is done so according to a
> ```

s/it is done so /. The output ordering is /

---

*[sql/distsql/readerbase.go, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-KRApy7G5i7pByUaT0s9:-KRApy7G5i7pByUaT0sA:b-xr73cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7c0486dcdd2c1395d420f236f50c3a58b469e07/sql/distsql/readerbase.go#L2)):*
> ```Go
> // Copyright 2016 The Cockroach Authors.
> //
> ```

What's the point of moving this? I think it belongs with the tablereader even if there is another use of it.

I don't have strong feelings, but maybe keep the old author if you don't want to get questions on this code :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-:-KRArhDUZBPygh8qO-v7:bdi4r7e)*

**Comment by irfansharif** [comment]
Thank you! Changed to use `sort.Interface` alone.

---

Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/distsql/data.go, line 24 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-KRAqJx-Iqtfnz5jsCWL:-KRCLL2li5TznSkYg1OW:b3yewz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b5f7765b1bae328aad5a19fc62de5231302d8cb/sql/distsql/data.go#L24)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> convertTo
</details>
oops, Done.

---

*[sql/distsql/processors.proto, line 98 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-KRArAIFlB0ybkJeED2Z:-KRCLM4t7-VmX9gP8eVj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b5f7765b1bae328aad5a19fc62de5231302d8cb/sql/distsql/processors.proto#L98)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> s/it is done so /. The output ordering is /
</details>
Done.

---

*[sql/distsql/readerbase.go, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-KRApy7G5i7pByUaT0s9:-KRCHfBejYbjoxqKu10F:b78lj0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7c0486dcdd2c1395d420f236f50c3a58b469e07/sql/distsql/readerbase.go#L2)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What's the point of moving this? I think it belongs with the tablereader even if there is another use of it.
> 
> I don't have strong feelings, but maybe keep the old author if you don't want to get questions on this code :)
</details>
/nitpicky but happy it drop this commit otherwise
 
also wasn't sure what the semantics for adding authors were. thought it was per new/edited file but this makes more sense. reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-:-KRCj6DT9SylCuPDso2z:b9g9dbh)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9224#-:-KRDgvneQR0DALtoQm5m:bnfp4nl)*

**Pull request merged**
