### PR TITLE
distsql: add outbox/inbound stream draining integration test

### PR DESCRIPTION
**Pull request by asubiotto**
This test fails without the accompanying bugfix where an inbound stream
would never switch into draining mode due to a faulty if statement.

Fixes #32319

Release note: None

cc @danhhz

### CODE REVIEW

**Comment by danhhz** [comment]
Thanks for the fix! I'll leave the review to Jordan

I assume you'd do this anyway, but cdc needs this backported to 2.1

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33130#-:-LTcSHsZ4bOIODEavi64:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/inbound_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33130#-LTcS5OyAI4w4IOHObw0:-LTcS5Oz9mtTUixD7QO_:b-stozqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9519b3ce06a814c3d7b531fec0460e4f59a4ee83/pkg/sql/distsqlrun/inbound_test.go#L122)):*
> ```Go
> 	// As a producer, we are now required to call ProducerDone after draining. We
> 	// do so now to simulate the fact that we have no more rows or metadata to
> 	// send.
> ```

Should we also verify that the downstream doesn't get any further rows after the drain begins?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33130)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/inbound_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33130#-LTcS5OyAI4w4IOHObw0:-LTcY-EdDerzkgKOD0jq:bxhkns0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9519b3ce06a814c3d7b531fec0460e4f59a4ee83/pkg/sql/distsqlrun/inbound_test.go#L122)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should we also verify that the downstream doesn't get any further rows after the drain begins?
</blockquote></details>

Do you mean the inbound stream or the consumer? After the drain begins, the consumer could possibly get a variable number of rows (although it won't store them) since the outbox can group together any number of rows before it realizes that the consumer is draining.

**Review by asubiotto — COMMENTED** [review]
Actually, there might be a way to assert that the outbox does not send any more rows once the main outbox goroutine knows that it's draining (instead of doing anything with the consumer) but this will only be useful if we have rows that have not been read on the RowChannel. We could do by pushing on the main outbox goroutine and racing the read of the RowChannel with a call to ProducerDone on the main testing goroutine. I'll think about this independently of the merge and will circle back with a new PR if I think it's worth doing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33130#-:-LTcq3FT5W_LnJLZpP7H:b-tmb4qx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
