### PR TITLE
ui: Upgrade yarn.lock dependencies

### PR DESCRIPTION
**Pull request by celiala**
This set of commits addresses all but [one](https://github.com/cockroachdb/cockroach/pull/36029) alert/recommendation listed [GitHub's Alert page](https://github.com/cockroachdb/cockroach/network/alerts).

### CODE REVIEW

**Comment by celiala** [comment]
Hi @vilterp -

PTAL - this addresses all but one* alert/recommendation from GitHub's Alert page.

(*see #36029 for the last one alert)

Thanks!

**Review by vilterp — APPROVED** [review]
Don't have time to click through everything to make sure it still works (and our test suite is not that good 🤦‍♂️) but if you are confident in this then LGTM!

**Comment by celiala** [comment]
TFTR!

(Yep -- I spot checked our high visibility pages and things all seemed to be working)

**Pull request merged**
