### PR TITLE
ui: small nits

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by BramGruneir** [comment]
Any chance for a before/after screenshots?

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18357#-:-KtXaMYfFKyeXee2OhWO:b-9s4q0z)*

**Comment by benesch** [comment]
Here's @dianasaur323's before:

image

And here's the new look:

screenshot 2017-09-08 14 37 07

**Comment by BramGruneir** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18357#-:-KtY95WWD5Fw40K75n4U:bnfp4nl)*

**Comment by benesch** [comment]
TFTR! Going to hold off until #18349 lands so I can bask in the glory of an embedded.go-free world. 😄

**Comment by BramGruneir** [comment]
Are we going to cherry pick this into 1.1?

**Comment by benesch** [comment]
It doesn't seem to meet the "would we cherry-pick this into 1.0" standard,
but perhaps the UI is subject to less-strict scrutiny?

**Comment by BramGruneir** [comment]
Yeah, don't know if this qualifies, but I bet @kuanluo would differ.
I just wanted to reply with a joke about having to recompile embedded.go again.

**Comment by kuanluo** [comment]
It's a fairly common view for Jobs for most clusters, so I'd love to keep
this consistent/polished to users. :)

**Comment by couchand** [comment]
As a matter of best practice it might be nice to have the text "No Results" somewhere.  Granted we tend to assume the admin UI is a very visual interface, but we should be moving towards accessibility when reasonable and possible.

**Comment by dianasaur323** [comment]
I'm all for that. Perhaps it's as simple as tagging a name attribute (or whatever it is) to the image?

**Comment by benesch** [comment]
Filed #19290 for the alt text issue.

**Pull request merged**
