### PR TITLE
sql: reduce allocations in show_create.go

### LINKED ISSUE #21064: sql: reduce allocations in show_create.go
Currently, there's a lot of wasteful string copying present in `show_create.go` to create the end representations of various SQL structures.

It would be better to convert everything there to use `bytes.Buffer` instead of `fmt.Sprintf` and friends. See the conversation in #20788 for more details on what the problem is.

### PR DESCRIPTION
**Pull request by williamyangyt**
fixes #21064 Use `bytes.Buffer` instead of `fmt.Fprintf` and `fmt.Sprintf` in show_create.go

### CODE REVIEW

**Comment by jordanlewis** [comment]
Thanks @williamyangyt! I've assigned @knz to take a look at your PR.

**Comment by knz** [comment]
Nice work! Just a small request for change

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_create.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1rdmplXuY_nax1b_Db:-L1rdmplXuY_nax1b_Dc:bg163wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/14dcb4b93fed49b3686a425fd5057465c4a13c47/pkg/sql/show_create.go#L146)):*
> ```Go
> 	var buf bytes.Buffer
> 	buf.WriteString("CREATE TABLE ")
> 	tn.Format(&buf, tree.FmtSimple)
> ```

can you use `tree.FormatNode` here too

---

*[pkg/sql/show_create.go, line 171 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1rdpXWkJyGm5B8tKo8:-L1rdpXWkJyGm5B8tKo9:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/14dcb4b93fed49b3686a425fd5057465c4a13c47/pkg/sql/show_create.go#L171)):*
> ```Go
> 		if fk := idx.ForeignKey; fk.IsSet() {
> 			buf.WriteString(",\n\tCONSTRAINT ")
> 			tree.Name(fk.Name).Format(&buf, tree.FmtSimple)
> ```

ditto

---

*[pkg/sql/show_create.go, line 277 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1rdtG5DWeb-EjuO2eb:-L1rdtG5DWeb-EjuO2ec:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/14dcb4b93fed49b3686a425fd5057465c4a13c47/pkg/sql/show_create.go#L277)):*
> ```Go
> 	}
> 	buf.WriteString(" INTERLEAVE IN PARENT ")
> 	parentName.Format(buf, tree.FmtSimple)
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-:-L1rdvY7QK_7xYi59Krb:b-y3t83u)*

**Comment by williamyangyt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_create.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1rdmplXuY_nax1b_Db:-L1v0PHaPExa_yMxtp-d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/14dcb4b93fed49b3686a425fd5057465c4a13c47/pkg/sql/show_create.go#L146)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

can you use `tree.FormatNode` here too
</blockquote></details>

Done.

---

*[pkg/sql/show_create.go, line 171 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1rdpXWkJyGm5B8tKo8:-L1v0RvAEzGEPNF7m4t7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/14dcb4b93fed49b3686a425fd5057465c4a13c47/pkg/sql/show_create.go#L171)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/show_create.go, line 277 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1rdtG5DWeb-EjuO2eb:-L1v0SthSSp2SJWN9bvW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/14dcb4b93fed49b3686a425fd5057465c4a13c47/pkg/sql/show_create.go#L277)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118)*

**Comment by knz** [comment]
Excellent!
So if you want we can complete this PR now, as the work is already good.
However if you feel like the extra challenge, I have two additional suggestions below that would enhance this PR further. Let me know if you are interested.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_create.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1w2ajaF6DVzno9IAtu:-L1w2ajbWVCUqoGvKI22:b-bqg6rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3278697a68696613188922d447d8f9557012501a/pkg/sql/show_create.go#L155)):*
> ```Go
> 		}
> 		buf.WriteString("\n\t")
> 		buf.WriteString(col.SQLString())
> ```

I just noticed that this method `SQLString()` and the one below (`PrimaryKeyString`) are also creating strings on the heap where it's not necessary.
You could replace them by `Format` methods and pass the buffer / flags to them accordingly, and achieve an even better improvement to this code.

---

*[pkg/sql/show_create.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1w32NTgZyGPxDKpeyv:-L1w32NTgZyGPxDKpeyw:bvq050x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3278697a68696613188922d447d8f9557012501a/pkg/sql/show_create.go#L235)):*
> ```Go
> 
> // formatQuoteNames quotes and adds commas between names.
> func formatQuoteNames(buf *bytes.Buffer, names ...string) {
> ```

Try this:
```go
 comma := ""
 for _, n := range names {
     buf.WriteString(comma)
     tree.FormatNode(buf, tree.FmtSimple, tree.Name(n))
     comma = ", "
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-:-L1w3NcQZ6Koax1GcTUW:bk0xbfc)*

**Comment by williamyangyt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_create.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1w2ajaF6DVzno9IAtu:-L20X_rLw8yKa1F4DeTg:b12wpbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3278697a68696613188922d447d8f9557012501a/pkg/sql/show_create.go#L155)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I just noticed that this method `SQLString()` and the one below (`PrimaryKeyString`) are also creating strings on the heap where it's not necessary.
You could replace them by `Format` methods and pass the buffer / flags to them accordingly, and achieve an even better improvement to this code.
</blockquote></details>

- `func formatColumnSQLString` and `func formatPrimaryKeyString` were added because there's no `Format` method for type `sqlbase.ColumnDescriptor` and `sqlbase.TableDescriptor`. 


- `func (desc *ColumnDescriptor) SQLString()` in structured.go was removed due to TestLint/TestMegacheck/unused error.

I'm not sure if I approach it correctly, would you like to give me some suggestions?

---

*[pkg/sql/show_create.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-L1w32NTgZyGPxDKpeyv:-L206jbm8-Tg7aI_MMlY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3278697a68696613188922d447d8f9557012501a/pkg/sql/show_create.go#L235)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Try this:
```go
 comma := ""
 for _, n := range names {
     buf.WriteString(comma)
     tree.FormatNode(buf, tree.FmtSimple, tree.Name(n))
     comma = ", "
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118)*

**Comment by williamyangyt** [comment]
@knz Thanks for your additional suggestions!
I noticed that struct FmtCtxWithBuf was added recently and I've changed the code accordingly. Please take a look at my PR again.

**Comment by knz** [comment]
All right, we'll take this. Very nice job. Thank you for your work!

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21118#-:-L2pDgOOvoSub9UBSRtx:b-u6zsb3)*

**Comment by williamyangyt** [comment]
TFTR!

**Pull request merged**
