### PR TITLE
parser: implement ALTER TABLE ... RESET (...) 

### PR DESCRIPTION
**Pull request by otan**
Only last two commits for review (rest is #75262).
See individual commits for details.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! just a nit for comments

> Reviewed 2 of 3 files at r1, 3 of 5 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75429#-:-MuJmTcKExN328L7LCdf:b-qa05bn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/paramparse/paramobserver.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75429#-MuJlN66BJtsrn5HukpF:-MuJlN66BJtsrn5HukpG:bu44fp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfd1ef9f84f9517ca9e8be9dbb438b947a85fdb6/pkg/sql/paramparse/paramobserver.go#L85)):*
> ```Go
> 	onSet(evalCtx *tree.EvalContext, key string, datum tree.Datum) error
> 	onReset(evalCtx *tree.EvalContext, key string) error
> 	runPostChecks() error
> ```

nit: could use comments on all of the interface methods

**Comment by otan** [comment]
done!

bors r=rafiss

**Comment by otan** [comment]
oops, pushed the wrong branch

bors r=rafiss

**Comment by otan** [comment]
conflict ...

bors r-

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
