### PR TITLE
DEPS: bump across etcd-io/raft#81 and disable conf change validation

### LINKED ISSUE #105797: kvserver: config change proposals can hang forever
In https://github.com/cockroachdb/cockroach/issues/104709#issuecomment-1609474175 we see a replica circuit breaker continually (un)tripping on a stuck proposal.

During an `ALTER TABLE SCATTER`, three replicas on n6 trip circuit breakers because of a slow proposal. In all cases, the proposals are `EndTxn(commit change-replicas)`, i.e. they are attempting to commit an conf change, and all of the replicas are followers.

```
E230627 12:51:40.782735 148856 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r1039/7:‹/Table/106/1/65{32837…-51266…}›] 30842 breaker: tripped with error: replica unavailable: (n6,s6):7 unable to serve request to r1039:‹/Table/106/1/65{32837936193842192-51266251951793792}› [(n3,s3):13, (n6,s6):7, (n8,s8):11, (n4,s4):14, (n9,s9):5, next=15, gen=92, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870297.597281357,0 (2023-06-27 12:51:37); raft status: {"id":"7","term":12,"vote":"e","commit":135,"lead":"e","raftState":"StateFollower","applied":135,"progress":{},"leadtransferee":"0"}: have been waiting 63.00s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹6532837936193842192›/‹RangeDescriptor›], [txn: 494e1e1e]
E230627 12:51:43.283167 149136 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r307/6:‹/Table/106/1/-68{2769…-0926…}›] 30847 breaker: tripped with error: replica unavailable: (n6,s6):6 unable to serve request to r307:‹/Table/106/1/-68{27690988321067808-09262672563116208}› [(n9,s9):7, (n7,s7):8, (n4,s4):4, (n3,s3):11, (n6,s6):6, next=12, gen=52, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870300.196827941,0 (2023-06-27 12:51:40); raft status: {"id":"6","term":12,"vote":"b","commit":127,"lead":"b","raftState":"StateFollower","applied":127,"progress":{},"leadtransferee":"0"}: have been waiting 60.50s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹-6827690988321067808›/‹RangeDescriptor›], [txn: 321479c5]
E230627 12:51:44.282776 149410 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r885/6:‹/Table/106/1/53{16569…-34997…}›] 30854 breaker: tripped with error: replica unavailable: (n6,s6):6 unable to serve request to r885:‹/Table/106/1/53{16569096169036592-34997411926988192}› [(n8,s8):11, (n4,s4):9, (n7,s7):12, (n5,s5):4, (n6,s6):6, next=13, gen=68, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870301.210269924,0 (2023-06-27 12:51:41); raft status: {"id":"6","term":13,"vote":"9","commit":122,"lead":"9","raftState":"StateFollower","applied":122,"progress":{},"leadtransferee":"0"}: have been waiting 61.50s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹5316569096169036592›/‹RangeDescriptor›], [txn: 336523e8]
```

After being tripped, we continually see these replicas re-tripping the circuit breakers every 3 seconds, as they try to repropose these EndTxns. However, the Raft groups are fully functional, and the circuit breakers also reset immediately, but keep re-tripping on these proposals that don't appear to be going through.

Screenshot 2023-06-29 at 07 55 12

We even see it after n6 regains leadership of the Raft group:

```
E230627 13:08:34.784088 650606 kv/kvserver/replica_circuit_breaker.go:175 ⋮ [T1,n6,s6,r1039/7:‹/Table/106/1/65{32837…-51266…}›] 34156 breaker: tripped with error: replica unavailable: (n6,s6):7 unable to serve request to r1039:‹/Table/106/1/65{32837936193842192-51266251951793792}› [(n3,s3):13, (n6,s6):7, (n8,s8):11, (n4,s4):14, (n9,s9):5, next=15, gen=92, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687871114.188750889,0 (2023-06-27 13:05:14); raft status: {"id":"7","term":13,"vote":"7","commit":963,"lead":"7","raftState":"StateLeader","applied":963,"progress":{"5":{"match":963,"next":965,"state":"StateReplicate"},"7":{"match":963,"next":964,"state":"StateReplicate"},"b":{"match":963,"next":965,"state":"StateReplicate"},"d":{"match":963,"next":965,"state":"StateReplicate"},"e":{"match":963,"next":965,"state":"StateReplicate"}},"leadtransferee":"0"}: have been waiting 1077.00s for slow proposal EndTxn(commit change-replicas) [/Local/Range/Table/106/1/‹6532837936193842192›/‹RangeDescriptor›], [txn: 494e1e1e]
```

We also see the transactions being cancelled:

```
I230627 12:51:40.785010 124952 kv/txn.go:878 ⋮ [T1,n6] 30843 async rollback failed: replica unavailable: (n6,s6):7 unable to serve request to r1039:‹/Table/106/1/65{32837936193842192-51266251951793792}› [(n3,s3):13, (n6,s6):7, (n8,s8):11, (n4,s4):14, (n9,s9):5, next=15, gen=92, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870297.597281357,0 (2023-06-27 12:51:37); raft status: {"id":"7","term":12,"vote":"e","commit":135,"lead":"e","raftState":"StateFollower","applied":135,"progress":{},"leadtransferee":"0"}: encountered poisoned latch ‹/Meta2/Table/106/1/6551266251951793792›@1687870207.598066812,0: "change-replica" meta={id=494e1e1e key=/Local/Range/Table/106/1/‹6532837936193842192›/‹RangeDescriptor› iso=Serializable pri=0.06378614 epo=0 ts=1687870207.598066812,0 min=1687870207.598066812,0 seq=2} lock=true stat=PENDING rts=1687870207.598066812,0 wto=false gul=1687870208.098066812,0
I230627 12:51:43.285782 124887 kv/txn.go:878 ⋮ [T1,n6] 30848 async rollback failed: replica unavailable: (n6,s6):6 unable to serve request to r307:‹/Table/106/1/-68{27690988321067808-09262672563116208}› [(n9,s9):7, (n7,s7):8, (n4,s4):4, (n3,s3):11, (n6,s6):6, next=12, gen=52, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870300.196827941,0 (2023-06-27 12:51:40); raft status: {"id":"6","term":12,"vote":"b","commit":127,"lead":"b","raftState":"StateFollower","applied":127,"progress":{},"leadtransferee":"0"}: encountered poisoned latch ‹/Meta2/Table/106/1/-6809262672563116208›@1687870210.148120953,0: "change-replica" meta={id=321479c5 key=/Local/Range/Table/106/1/‹-6827690988321067808›/‹RangeDescriptor› iso=Serializable pri=0.02487111 epo=0 ts=1687870210.148120953,0 min=1687870210.148120953,0 seq=2} lock=true stat=PENDING rts=1687870210.148120953,0 wto=false gul=1687870210.648120953,0
I230627 12:51:44.285303 124854 kv/txn.go:878 ⋮ [T1,n6] 30855 async rollback failed: replica unavailable: (n6,s6):6 unable to serve request to r885:‹/Table/106/1/53{16569096169036592-34997411926988192}› [(n8,s8):11, (n4,s4):9, (n7,s7):12, (n5,s5):4, (n6,s6):6, next=13, gen=68, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687870301.210269924,0 (2023-06-27 12:51:41); raft status: {"id":"6","term":13,"vote":"9","commit":122,"lead":"9","raftState":"StateFollower","applied":122,"progress":{},"leadtransferee":"0"}: encountered poisoned latch ‹/Meta2/Table/106/1/5334997411926988192›@1687870210.000120522,0: "change-replica" meta={id=336523e8 key=/Local/Range/Table/106/1/‹5316569096169036592›/‹RangeDescriptor› iso=Serializable pri=0.00570728 epo=0 ts=1687870210.000120522,0 min=1687870210.000120522,0 seq=2} lock=true stat=PENDING rts=1687870210.000120522,0 wto=false gul=1687870210.500120522,0
```

Jira issue: CRDB-29202

### PR DESCRIPTION
**Pull request by tbg**
We don't want raft to validate conf changes, since that causes issues due to false positives (the check is above raft, but needs to be below raft to always work correctly). We are
taking responsibility for carrying out only valid conf changes, as we always
have.

See also https://github.com/etcd-io/raft/issues/80.

Fixes #105797.
Epic: CRDB-25287
Release note (bug fix): under rare circumstances, a replication change could get
stuck when proposed near lease/leadership changes (and likely under overload),
and the replica circuit breakers could trip. This problem has been addressed.
Note to editors: this time it's really addressed (fingers crossed); a previous
attempt with an identical release note had to be reverted.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
We'll need a version gate when we start relying on this.

**Comment by tbg** [comment]
bors r=erikgrinaker
🚀

**Comment by nvanbenschoten** [comment]
@tbg @pav-kv now that we are using `DisableConfChangeValidation` and we ignore the `r.pendingConfIndex > r.raftLog.applied` condition [here](https://github.com/cockroachdb/cockroach/commit/d8d274b3f0c1f10089541873b8ec61be12149f54#diff-d7ffa919352e4a9c13fdb7b7fe6fa5302de94a745b90ae80155605e995ef5f11R1267), do we still have a guarantee that a raft leader will never propose a configuration change before it has applied the latest configuration change? In other words, does this change break the **Apply** and **Append** invariants from https://github.com/etcd-io/etcd/issues/7625#issuecomment-489232411 for split leaseholder/leader states where the leader is behind on log application? Could that lead to split brain scenarios? cc. @sumeerbhola

**Comment by pav-kv** [comment]
I had a similar concern when looking at this. I wonder if it would be sufficient to disable only the 2 checks [here](https://github.com/cockroachdb/cockroach/commit/d8d274b3f0c1f10089541873b8ec61be12149f54#diff-d7ffa919352e4a9c13fdb7b7fe6fa5302de94a745b90ae80155605e995ef5f11R1274-R1277), but leave the one that @nvanbenschoten linked which is important for raft's config change [safety](https://github.com/etcd-io/etcd/issues/7625#issuecomment-489232411).

**Comment by nvanbenschoten** [comment]
> I wonder if it would be sufficient to disable only the 2 checks [here](https://github.com/cockroachdb/cockroach/commit/d8d274b3f0c1f10089541873b8ec61be12149f54#diff-d7ffa919352e4a9c13fdb7b7fe6fa5302de94a745b90ae80155605e995ef5f11R1274-R1277), but leave the one that @nvanbenschoten linked which is important for raft's config change https://github.com/etcd-io/etcd/issues/7625#issuecomment-489232411.

That seems like a reasonable change to me. Do you want to take that @pav-kv?

**Pull request merged**
