### PR TITLE
all: add AdminTransferLease

### PR DESCRIPTION
**Pull request by petermattis**
Allow external use of RangeLookup requests.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8050)

### CODE REVIEW

**Comment by petermattis** [comment]
Extracted from #8034. Let me know if you think more specific testing is required. This is mainly piggy-backing on the existing `Replica.AdminTransferLease` method. The only specific testing is via `TestCluster.TransferRangeLease`.

**Comment by tamird** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/db_test.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeAZI3zighATOGzvYh:-KNeAZI3zighATOGzvYi:166874) ([raw file](https://github.com/cockroachdb/cockroach/blob/859637ccd473bcfbab4eef89fbe3eff9a7508dda/kv/db_test.go#L171)):*
> ```Go
> 		&roachpb.GCRequest{},
> 		&roachpb.PushTxnRequest{},
> 		&roachpb.RangeLookupRequest{},
> ```

?

---

*[testutils/testcluster/testcluster.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeARt4lTt227UGjlcS:-KNeARt4lTt227UGjlcT:-1126142040) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/testutils/testcluster/testcluster.go#L359)):*
> ```Go
> 	err = tc.Servers[0].DB().AdminTransferLease(rangeDesc.StartKey.AsRawKey(), destReplicaDesc)
> 	if err != nil {
> 		return errors.Errorf(
> ```

wrapf?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by bdarnell** [comment]
What's up with all the pb.go changes?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 357 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNePkIc5Sn9tjB7qluF:-KNePkIc5Sn9tjB7qluG:-1318677615) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L357)):*
> ```protobuf
> message AdminTransferLeaseRequest {
>   optional Span header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   optional ReplicaDescriptor target = 2 [(gogoproto.nullable) = false];
> ```

I feel like this needs more safeguards if we're going to expose it (how exposed is it? Can non-root/node users call it?). For one thing, addressing the range by key may not target the range you expect in the presence of merges (it's safe with splits on the condition that you only target the start keys of ranges). There should be a range ID in the request so that if the range isn't the one we expected we won't disrupt an unrelated range. AdminTransferLease doesn't even verify that the requested replica is a member of the range.

---

*[roachpb/api.proto, line 605 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeKZLGCCfmVl6ei2Wc:-KNeKZLHyG10BnYmgdAK:-565631114) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L605)):*
> ```protobuf
> // wants to transfer it away.
> //
> // Like a RequstLeaseRequest, this request has the effect of instituting a new
> ```

s/Requst/Request/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-:-KNePhrogUnzD2JMo-8h:-1599884730)*

**Comment by tschottdorf** [comment]
> Let me know if you think more specific testing is required.

Some bogus invocations of `(*Replica).AdminTransferLease` which fail/noop without incurring unnecessary unavailability would be good. Illegal target, target same as origin, calling without holding the lease.

Depending on how the `AdminTransferLeaseRequest` API turns out, we should test that it asserts on the Range it was addressed to.

Also curious why so many protos changed. I bet you also need `go generate ./...`.

---

Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[kv/db_test.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeAZI3zighATOGzvYh:-KNfGPG8T91nVCyVOxJd:-573994328) ([raw file](https://github.com/cockroachdb/cockroach/blob/859637ccd473bcfbab4eef89fbe3eff9a7508dda/kv/db_test.go#L171)):*
> Allow external use of RangeLookup requests.

---

*[roachpb/api.proto, line 357 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNePkIc5Sn9tjB7qluF:-KNfH0yLTArXtxF2C1mV:-2082620477) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L357)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I feel like this needs more safeguards if we're going to expose it (how exposed is it? Can non-root/node users call it?). For one thing, addressing the range by key may not target the range you expect in the presence of merges (it's safe with splits on the condition that you only target the start keys of ranges). There should be a range ID in the request so that if the range isn't the one we expected we won't disrupt an unrelated range. AdminTransferLease doesn't even verify that the requested replica is a member of the range.
</details>
Agreed. `(*Replica).AdminTransferLease` should check that the recipient is real (applyNewLease already does it, but at that point the old lease holder has already stopped serving and so the lease will be unavailable at least for a bit).

The other interesting case is that in which we ask the Replica to transfer to itself (which should be a noop, and perhaps already is).

As for specifying the Replica, perhaps the request should contain an optional RangeID (in which case it is checked), an optional origin StoreID (in which case we assert that the current lease is at that StoreID) and a required target StoreID (which is where the lease goes). As far as I can tell putting the whole descriptor in only adds more information you have to gather pre-request.
We could also allow this command to act on key ranges (i.e. transfer all the leases containing anything of table X to store 3), but that's hardly necessary for the currently intended scope.

---

*[roachpb/api.proto, line 721 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNfIxrPhuMu5fec1u2V:-KNfIxrPhuMu5fec1u2W:-1646416405) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L721)):*
> ```protobuf
>   optional AdminSplitResponse admin_split = 10;
>   optional AdminMergeResponse admin_merge = 11;
>   optional AdminTransferLeaseResponse admin_transfer_lease = 29;
> ```

Mind adding a reserved line for 28 with a comment that it was skipped intentionally (due to `TransferLease` and `RequestLease` using the same response proto)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-:-KNfJZG7O1uxx0cltf-B:-1159165995)*

**Comment by petermattis** [comment]
I'm not sure what is up with the `.pb.go` changes. I did run `go generate ./...`. Clearly CircleCI is irritated at those changes too. I need to track that down. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[kv/db_test.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeAZI3zighATOGzvYh:-KNg_m3L0VqcIRjEzhkd:677251183) ([raw file](https://github.com/cockroachdb/cockroach/blob/859637ccd473bcfbab4eef89fbe3eff9a7508dda/kv/db_test.go#L171)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> > Allow external use of RangeLookup requests.
</details>
Yep.

---

*[roachpb/api.proto, line 357 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNePkIc5Sn9tjB7qluF:-KNgac3eCQYBwg9c94XX:213863325) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L357)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Agreed. `(*Replica).AdminTransferLease` should check that the recipient is real (applyNewLease already does it, but at that point the old lease holder has already stopped serving and so the lease will be unavailable at least for a bit).
> 
> The other interesting case is that in which we ask the Replica to transfer to itself (which should be a noop, and perhaps already is).
> 
> As for specifying the Replica, perhaps the request should contain an optional RangeID (in which case it is checked), an optional origin StoreID (in which case we assert that the current lease is at that StoreID) and a required target StoreID (which is where the lease goes). As far as I can tell putting the whole descriptor in only adds more information you have to gather pre-request.
> We could also allow this command to act on key ranges (i.e. transfer all the leases containing anything of table X to store 3), but that's hardly necessary for the currently intended scope.
</details>
@bdarnell Doesn't addressing a range by key also affect `AdminSplit` and `AdminMerge`? Agreed that I need to add some safeguards to make sure the target is a replica of the range. Simplifying this down to making the target a `StoreID` feels best. Yes, I could add an optional `RangeID`, but don't currently intend to use that. 

The node user can certainly invoke this method (not sure about root), but is that really any more problematic than being able to invoke other KV operations? For example, a node user can currently use `DelRange` to delete SQL data. 

---

*[roachpb/api.proto, line 721 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNfIxrPhuMu5fec1u2V:-KNga69_8pKQDK7lNNwT:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L721)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Mind adding a reserved line for 28 with a comment that it was skipped intentionally (due to `TransferLease` and `RequestLease` using the same response proto)?
</details>
Done.

---

*[testutils/testcluster/testcluster.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeARt4lTt227UGjlcS:-KNgaGPOjcK1OjDfRxqb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/testutils/testcluster/testcluster.go#L359)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wrapf?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-:-KNgbanRa9Q33vtXQriG:-1395532533)*

**Comment by petermattis** [comment]
Fixed my `.pb.go` issues and changed `AdminTransferLeaseRequest` to only contain a `StoreID`. `Replica.AdminTransferLease` now checks both that the target is a replica in the range and that we're not trying to transfer the lease to ourself. Note that this simplified the implementation of `TestCluster.TransferRangeLease` significantly. I still need to add new tests, but otherwise this is ready for another look.

---

Review status: 7 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-:-KNgmL7r-22eALcBjFTL:1288726816)*

**Comment by tamird** [comment]
Reviewed 34 of 34 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[roachpb/api.proto, line 605 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeKZLGCCfmVl6ei2Wc:-KNgryZto1FWcqd1jfxJ:-1435652765) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L605)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/Requst/Request/
</details>
@petermattis ping

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by petermattis** [comment]
Review status: 12 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[roachpb/api.proto, line 605 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNeKZLGCCfmVl6ei2Wc:-KNgt2GETTK8wvU6G0Wc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L605)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> @petermattis ping
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by petermattis** [comment]
Extended `TestRangeTransferLease` to test transferring the lease to the current lease holder and transferring the lease to an invalid replica. PTAL.

---

Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-:-KNhNLyOg-cwQY6PZBUV:-610253349)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: 13 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/client_replica_test.go, line 527 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQSwpbp0tYvZmFU9l:-KNhQSwpbp0tYvZmFU9m:-2132353897) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L527)):*
> ```Go
> 		}
> 		newLease, _ := replica0.GetLease()
> 		if !reflect.DeepEqual(origLease, newLease) {
> ```

i think these leases can be compared without reflection

---

*[storage/client_replica_test.go, line 535 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQYOj_lNvLDCdv1OR:-KNhQYOj_lNvLDCdv1OS:-369090308) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L535)):*
> ```Go
> 		// An invalid target should result in an error.
> 		const expected = "unable to find store .* in range"
> 		if pErr := replica0.AdminTransferLease(1000); !testutils.IsError(pErr, expected) {
> ```

probably not a `pErr` if you're using testutils.IsError.

likely incorrect throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by petermattis** [comment]
Review status: 13 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/client_replica_test.go, line 527 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQSwpbp0tYvZmFU9l:-KNhVLpQrFQoPpKZc7ho:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think these leases can be compared without reflection
</details>
Done.

---

*[storage/client_replica_test.go, line 535 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQYOj_lNvLDCdv1OR:-KNhVM4TC7YlaIqolxsN:-1925945400) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L535)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> probably not a `pErr` if you're using testutils.IsError.
> 
> likely incorrect throughout.
</details>
Renamed to `err` where we actually have an `error`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/client_replica_test.go, line 527 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQSwpbp0tYvZmFU9l:-KNhYcb7OcJtabotoUxW:453449224) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Done.
</details>
Interesting that this is now comparing pointers (while I intended for struct comparison). Not an issue, just pointing out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by bdarnell** [comment]
Reviewed 7 of 39 files at r1, 5 of 34 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[roachpb/api.proto, line 357 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNePkIc5Sn9tjB7qluF:-KNhIdM4a7wctbnPU7uS:1215451018) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L357)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> @bdarnell Doesn't addressing a range by key also affect `AdminSplit` and `AdminMerge`? Agreed that I need to add some safeguards to make sure the target is a replica of the range. Simplifying this down to making the target a `StoreID` feels best. Yes, I could add an optional `RangeID`, but don't currently intend to use that. 
> 
> The node user can certainly invoke this method (not sure about root), but is that really any more problematic than being able to invoke other KV operations? For example, a node user can currently use `DelRange` to delete SQL data. 
</details>
Addressing a range by key is not a problem for AdminSplit, because whatever range that key lives on, a split can be created there.  It's a problem here because replica IDs are scoped to a single range, and you may end up trying to interpret them in a different range. Changing the argument to a StoreID mostly addresses this.

More fundamentally, we expose AdminSplit but not ChangeReplicas because the admin can know enough about the keys (current and anticipated) to make it useful.  AdminTransferLease is more like ChangeReplicas than AdminSplit - you can use it in a chaos-style test, but making it legitimately useful is more difficult. That's why I'd like to keep it locked down as much as possible. But RequestLease is exposed too and it's similarly dangerous, so that's not a blocker here if we need to expose this for out-of-process use.

Similarly, using RangeLookup externally is tricky because of all the magic around intents. That's fine if you're willing to accept some level of failures but it's going to be tricky to use it reliably from the outside. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-:-KNh_BY1JmzHY8TtI1DC:676834233)*

**Comment by petermattis** [comment]
Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 357 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNePkIc5Sn9tjB7qluF:-KNh_f7s8Wh_jFAPUZdu:-2024282183) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e768dcb7c1ec2224ed8b1756540c4dae1e550f0/roachpb/api.proto#L357)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Addressing a range by key is not a problem for AdminSplit, because whatever range that key lives on, a split can be created there.  It's a problem here because replica IDs are scoped to a single range, and you may end up trying to interpret them in a different range. Changing the argument to a StoreID mostly addresses this.
> 
> More fundamentally, we expose AdminSplit but not ChangeReplicas because the admin can know enough about the keys (current and anticipated) to make it useful.  AdminTransferLease is more like ChangeReplicas than AdminSplit - you can use it in a chaos-style test, but making it legitimately useful is more difficult. That's why I'd like to keep it locked down as much as possible. But RequestLease is exposed too and it's similarly dangerous, so that's not a blocker here if we need to expose this for out-of-process use.
> 
> Similarly, using RangeLookup externally is tricky because of all the magic around intents. That's fine if you're willing to accept some level of failures but it's going to be tricky to use it reliably from the outside. 
</details>
I don't see a legitimate use for `AdminTransferLease`, just utility for chaos-style tests. We could potentially require some environment variable to be set in order to expose it. 

I wonder if I could get rid of my use of `RangeLookup` by doing my own scan of the `meta2` keys. For my test, I think that would be sufficient.

---

*[storage/client_replica_test.go, line 527 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQSwpbp0tYvZmFU9l:-KNhZ8828mUGRPER5nim:-2050781735) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Interesting that this is now comparing pointers (while I intended for struct comparison). Not an issue, just pointing out.
</details>
Oh, I didn't notice that. It's actually somewhat appropriate as it really verifies that the lease didn't change, though perhaps I should check both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/client_replica_test.go, line 527 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQSwpbp0tYvZmFU9l:-KNhqUb8RayG-zSU8Zvu:1231721280) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Oh, I didn't notice that. It's actually somewhat appropriate as it really verifies that the lease didn't change, though perhaps I should check both.
</details>
you'd have to dereference it earlier on or else the by-value comparison is not testing anything =/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/client_replica_test.go, line 527 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KNhQSwpbp0tYvZmFU9l:-KNhxp7j2yJFNS-hFcwj:807670556) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0500ecf8e1ae8ce6b4015531254de3a456c8408/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you'd have to dereference it earlier on or else the by-value comparison is not testing anything =/
</details>
Good point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by petermattis** [comment]
@tschottdorf I'll address any additional comments you have in a follow-on PR.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 34 of 34 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_replica_test.go, line 527 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KO9mFzO4ufy6_096H_G:-KO9mFzPnygI2AcgfJnd:-1214828177) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2476be97cace886d34d2b7131b782e3383a1377/storage/client_replica_test.go#L527)):*
> ```Go
> 		}
> 		newLease, _ := replica0.GetLease()
> 		if origLease != newLease || *origLease != *newLease {
> ```

This is a bit odd. Why not just `reflect.DeepEqual`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-:-KO9mX09T8rG4UI46UcA:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_replica_test.go, line 527 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KO9mFzO4ufy6_096H_G:-KOA1sUVFXEdcBH-5unN:654739292) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2476be97cace886d34d2b7131b782e3383a1377/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> This is a bit odd. Why not just `reflect.DeepEqual`?
</details>
I did use `reflect.DeepEqual` originally and @tamird said I could compare the structs directly. I didn't particularly care so I changed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_replica_test.go, line 527 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KO9mFzO4ufy6_096H_G:-KOA349pY4dqO5JEkz4n:-1556366515) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2476be97cace886d34d2b7131b782e3383a1377/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I did use `reflect.DeepEqual` originally and @tamird said I could compare the structs directly. I didn't particularly care so I changed it.
</details>
That code definitely burned more brain cycles on my end. Not worth changing now, but there's no good reason to avoid `reflect.DeepEqual` in testing imo (unless one can really compare the structs directly, which isn't the case here given that you are also comparing pointers).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_replica_test.go, line 527 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KO9mFzO4ufy6_096H_G:-KOAl8EN8X8tGrPwuTMY:-797705246) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2476be97cace886d34d2b7131b782e3383a1377/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> That code definitely burned more brain cycles on my end. Not worth changing now, but there's no good reason to avoid `reflect.DeepEqual` in testing imo (unless one can really compare the structs directly, which isn't the case here given that you are also comparing pointers).
</details>
FWIW I was originally suggesting that we just compare the structs - comparing pointers isn't necessary for correctness AFAIK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_replica_test.go, line 527 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050#-KO9mFzO4ufy6_096H_G:-KOAqA7uW-o5L87ADX_M:-1213271421) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2476be97cace886d34d2b7131b782e3383a1377/storage/client_replica_test.go#L527)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> FWIW I was originally suggesting that we just compare the structs - comparing pointers isn't necessary for correctness AFAIK.
</details>
If we just compare the structs then we'll crash if one of the pointers is `nil`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8050)*

**Pull request merged**
