### PR TITLE
sql: use real contention events instead of the mock ones

### LINKED ISSUE #59639: sql: replace mock roachpb.ContentionEvents with real ones
Much of contention observability work on the execution side this milestone was built on top of mock contention events while KV worked on emitting real contention events. As of #58444, real contention events are added to a trace.

This issue tracks using these real contention events instead of the mock contention events produced right now. Something to note is that a `ContentionEvent` field was added to `ProducerMetadata` to propagate these back to the gateway. However, these events are added to the trace, which means we can probably get rid of this new field and instead use `Structured` to visit a trace's payload in the distsql receiver, when adding contention events to its contention registry.

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: use real contention events instead of the mock ones**

This commit switches to using the real contention events that KV layer
adds to the trace and starts adding them into the contention registry.
Previously, we were using the payload that came as part of
ProducerMetadata, and the corresponding field is now removed.

This required that we change in how the cumulative contention time is
calculated. Now all components that report it (colbatchscan, table
reader, join reader, inverted joiner) examine the trace obtained from
their context to find all contention events and accumulate total time.
This works because every processor starts a child spand in
`startInternal` already and this commit adds similar logic to the
colbatchscan.

Fixes: #59639.

Release note: None

**rowexec: improve stats collection from miscellaneous joiners**

Previously, there was no stats collection on the zigzag joiner, so this
commit adds it.

Additionally, it adds reporting of the number of bytes read by the join
reader and the inverted joiner as well as make all processors mentioned
implement `execinfra.KVReader` interface (which will allow for all to
show up nicely on the EXPLAIN ANALYZE diagrams when run via the
vectorized engine).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Hm, I guess it might be possible to attribute each contention event from the trace to a particular processor if each processor would record into the trace the spans (as in `roachpb.Span`) it has requested from the KV. Since every contention event has a contended key, we would then be able to find a single processor (probably in `ExtractStatsFromSpans`).

Am I missing something? Do you see another way to keep the "contention time" info for EXPLAIN ANALYZE diagrams when the events are recorded into the trace?

**Comment by yuzefovich** [comment]
Do we have plans to use node-level statistics? It is not used currently, so I added another commit that removes that.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Thanks for getting this out so quickly!

> Am I missing something? Do you see another way to keep the "contention time" info for EXPLAIN ANALYZE diagrams when the events are recorded into the trace?

This is what I meant when talking about the execution leaves. Instead of calling `GetCumulativeContentionTime` in the leaves and populating metadata with it, my thinking is that the processors would use a helper to inspect their span's payload (from the context) and calculate cumulative contention time from those. I'm guessing that there might be some subtlety in doing this in cases where we have two input branches (e.g. a joinreader) and want to get the contention time for only one branch, but that might be limited to using a separate context for the lookups to get only spans related to those lookups.

> Reviewed 20 of 20 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 9 of 9 files at r4, 1 of 33 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-:-MSgQH7hAgutu9CP7qpN:b1w4bc4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql_running_test.go, line 270 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MSgSkBg8sLBd1MpiN1i:-MSgSkBg8sLBd1MpiN1j:bj57k13) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54751718e1f3455dfee326f49e92c46415d4d78/pkg/sql/distsql_running_test.go#L270)):*
> ```Go
> // additionally verifies that the metric stays at zero if there is no
> // contention.
> func TestDistSQLReceiverReportsContention(t *testing.T) {
> ```

cc @tbg 

@yuzefovich could you add a check that the contention registry is updated properly?
___
*[pkg/sql/execstats/traceanalyzer.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MSgRfvP-QjTqu-CRkFz:-MSgRfvP-QjTqu-CRkG-:b-1itp9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/89e7180c12e8530dc6c87b69322345a8a00bb6e0/pkg/sql/execstats/traceanalyzer.go#L89)):*
> ```Go
> // TODO(asubiotto): Flatten this struct, we're currently allocating a map per
> //  stat.
> type NodeLevelStats struct {
> ```

The question of whether we want to keep this is a good one. I think we do because it won't be long before our users start asking for a break down of higher-level stats by node. However, I do think that we could probably clean this up a bit and maybe offer an option to calculate query level stats from just the trace for performance reasons. In any case, this commit and discussion belongs in another PR.
___
*[pkg/sql/execstats/traceanalyzer.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MSgQAYC6JmVnyuuWcCd:-MSgQAYC6JmVnyuuWcCe:b-1g1cpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9d41c74bf888753b9d494b405e7c7e7dcdd501/pkg/sql/execstats/traceanalyzer.go#L96)):*
> ```Go
> 	KVTimeGroupedByNode           map[roachpb.NodeID]time.Duration
> 	NetworkMessagesGroupedByNode  map[roachpb.NodeID]int64
> 	ContentionTimeGroupedByNode   map[roachpb.NodeID]time.Duration
> ```

I'm confused why this commit removes this, what does it fix?

**Review by yuzefovich — COMMENTED** [review]
Ok, I think it makes sense. IIUC because all processors already start a child span in the `ProcessorBase.StartInternal` method, the contention events only for the appropriate processor will show up in its trace (i.e. if we have a join reader that takes in an input from another table reader, the former will only see its own events). I added a similar logic to the ColBatchScan.

Is my logic here correct? Any ideas on how to test it programmatically? I'm not sure on how we can inject the contention events into the trace, I'm guessing we need to plumb a testing callback into the KV concurrency manager?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-:-MSjqqLX3tS6C_55btyK:b-y64hfq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, and @tbg)

___
*[pkg/sql/distsql_running_test.go, line 270 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MSgSkBg8sLBd1MpiN1i:-MSjtVEm-_PmyqAwf7qL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54751718e1f3455dfee326f49e92c46415d4d78/pkg/sql/distsql_running_test.go#L270)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

cc @tbg 

@yuzefovich could you add a check that the contention registry is updated properly?
</blockquote></details>

Done.
___
*[pkg/sql/execstats/traceanalyzer.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MSgRfvP-QjTqu-CRkFz:-MSiWShS122-D4zfZq3T:b7am2vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/89e7180c12e8530dc6c87b69322345a8a00bb6e0/pkg/sql/execstats/traceanalyzer.go#L89)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The question of whether we want to keep this is a good one. I think we do because it won't be long before our users start asking for a break down of higher-level stats by node. However, I do think that we could probably clean this up a bit and maybe offer an option to calculate query level stats from just the trace for performance reasons. In any case, this commit and discussion belongs in another PR.
</blockquote></details>

Ok, I removed the removal commit.
___
*[pkg/sql/execstats/traceanalyzer.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MSgQAYC6JmVnyuuWcCd:-MSiWLuE-LfXwP2TAZvD:b-p70juw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9d41c74bf888753b9d494b405e7c7e7dcdd501/pkg/sql/execstats/traceanalyzer.go#L96)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm confused why this commit removes this, what does it fix?
</blockquote></details>

It wasn't being used (which is a bug being fixed in another PR).

**Comment by yuzefovich** [comment]
Confirmed manually that the join reader correctly distinguishes between the contention events originated in its input and itself. Here I blocked the table reader for a bit on one transaction and blocked the lookup join for longer on another:
Screen Shot 2021-02-04 at 7 53 21 PM

**Comment by yuzefovich** [comment]
Added another commit that adds or improves the stats collection on miscellaneous joiners.

**Review by tbg — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, @tbg, and @yuzefovich)

___
*[pkg/sql/distsql_running_test.go, line 307 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MT0MxQx8DLN-Uwc3KPy:-MT0MxQy2Pu4id6fopGs:bo8zfdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54751718e1f3455dfee326f49e92c46415d4d78/pkg/sql/distsql_running_test.go#L307)):*
> ```Go
> 			// Soft check to protect against flakiness where an internal query
> 			// causes the contention metric to increment.
> 			require.GreaterOrEqual(t, metrics.ContendedQueriesCount.Count(), int64(1))
> ```

I think it would be useful to have a testing knob that intercepts the contention events handled by DistSQL (i.e. whatever increments the metric). That way, you can explicitly verify that you got what you expected all the way to the collection. Just a suggestion.

**Comment by tbg** [comment]
FYI once https://github.com/cockroachdb/cockroach/pull/59992 is in, the contention metadata should flow without turning tracing on.

**Comment by tbg** [comment]
FYI once https://github.com/cockroachdb/cockroach/pull/59992 is in, the contention metadata should flow without turning tracing on.

> FYI once #59992 is in, the contention metadata should flow without turning tracing on.

Heh, I tried and TestDistSQLReceiverReportsContention fails on top of that PR. I'll take a look at why that is later.

**Comment by tbg** [comment]
Ah, found it. There's some short-circuiting in `(*Span).GetRecording` that is no longer correct with structured payloads. I'll add it to my PR.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 11 of 33 files at r5, 41 of 41 files at r6, 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-:-MT1LnpA7VDNr_ULUE54:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, @tbg, and @yuzefovich)

___
*[pkg/sql/distsql_running_test.go, line 285 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MT1FUCR7Ilz_3bHH1LT:-MT1FUCR7Ilz_3bHH1LU:beccirq) ([raw file](https://github.com/cockroachdb/cockroach/blob/587261dc7cdbbc1a793a55686b1a56073cf13d79/pkg/sql/distsql_running_test.go#L285)):*
> ```Go
> 		if contention {
> 			// Begin a contending transaction.
> 			conn, err := db.Conn(ctx)
> ```

nit: I think this and the conn below need to be closed
___
*[pkg/sql/colexecbase/operator.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MT1IvHuDRwY1zqSwqJA:-MT1IvHuDRwY1zqSwqJB:b3t6fee) ([raw file](https://github.com/cockroachdb/cockroach/blob/587261dc7cdbbc1a793a55686b1a56073cf13d79/pkg/sql/colexecbase/operator.go#L39)):*
> ```Go
> 	// happen when 'workmem' setting is too low - just bail, even if we have
> 	// disk spilling for that operator.
> 	// TODO(yuzefovich): we probably should move ctx argument from Next into
> ```

I don't think capturing the context is a good idea (it's an anti-pattern in go), but we should probably change `Init` to accept a context. The pattern would be that callers should use the same context for all calls.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

I'll go ahead and merge this, and we can address the TODOs later.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-:-MT1a5z_4uyAc5LCy8yE:b-o1jj7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @RaduBerinde, and @tbg)

___
*[pkg/sql/distsql_running_test.go, line 307 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MT0MxQx8DLN-Uwc3KPy:-MT1_Avq98yU_8MHNQGf:b49zw2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54751718e1f3455dfee326f49e92c46415d4d78/pkg/sql/distsql_running_test.go#L307)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think it would be useful to have a testing knob that intercepts the contention events handled by DistSQL (i.e. whatever increments the metric). That way, you can explicitly verify that you got what you expected all the way to the collection. Just a suggestion.
</blockquote></details>

Good point, left a TODO for this since it requires a bit of plumbing.
___
*[pkg/sql/distsql_running_test.go, line 285 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MT1FUCR7Ilz_3bHH1LT:-MT1_eZU0Ap8hNFzMdha:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/587261dc7cdbbc1a793a55686b1a56073cf13d79/pkg/sql/distsql_running_test.go#L285)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I think this and the conn below need to be closed
</blockquote></details>

Done.
___
*[pkg/sql/colexecbase/operator.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MT1IvHuDRwY1zqSwqJA:-MT1T59_9O2B0-qxM9zA:b-h9rbce) ([raw file](https://github.com/cockroachdb/cockroach/blob/587261dc7cdbbc1a793a55686b1a56073cf13d79/pkg/sql/colexecbase/operator.go#L39)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think capturing the context is a good idea (it's an anti-pattern in go), but we should probably change `Init` to accept a context. The pattern would be that callers should use the same context for all calls.
</blockquote></details>

But what if we derive a child context in `Init`? Should we return it then? What does the caller then do with that context? With the parent?

This might be an anti-pattern, but to me it makes a lot more sense. When initializing an operator, you pass in a context that can be used to signal for cancellation. At the same time, the operator is free to derive a child context from it and use that throughout its life.

So I think ideally I'd like to see the following:
```
// We have a root context (either of the root materializer or an outbox, also of a parallel unordered synchronizer)
// which can be used to shut everything down.
_ = ctx
...
operator.Init(ctx)
...
// Here and below the operator itself is responsible for using the appropriate context.
for operator.Next() {}
...
operator.DrainMeta()
```

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59785)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @RaduBerinde, @tbg, and @yuzefovich)

___
*[pkg/sql/colexecbase/operator.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59785#-MT1IvHuDRwY1zqSwqJA:-MT4o4B8A99BKMRE7-vE:b-jhj5xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/587261dc7cdbbc1a793a55686b1a56073cf13d79/pkg/sql/colexecbase/operator.go#L39)):*
> But what if we derive a child context in Init? Should we return it then? What does the caller then do with that context? With the parent?

Exactly, just like a lot of other places (e.g. setting up and running flows). The pattern would be:
```
...
ctx = operator.Init(ctx)
...
// Here and below the operator itself is responsible for using the appropriate context.
for operator.Next(ctx) {}
...
operator.DrainMeta(ctx)
```

And we can probably enforce this with a testing-level assertion where `Init` adds a special value to the context and asserts that it is stored in the context used in `Next` and `DrainMeta`

**Pull request merged**
