### PR TITLE
sql: create region type enums for multiregion databases 

### PR DESCRIPTION
**Pull request by arulajmani**
This patch introduces a new kind of type descriptor called
`TypeDescriptor_MULTIREGION_ENUM`. This type is similar to a regular
enum, except:
- We don't create an array type alias underneath the hood.
- The user isn't allowed to directly alter/drop this type of enum.
- The parentID is not validated (currently). This is because this enum
may be created along with the database. In such scenarios, we can't
get the db desc for validation as it was created in the same txn. This
can (and should) change once the descGetter is backed by the
desc.Collection instead of reading directly from KV.

In an upcoming patch, we plan to support dropping values
(removing a region) from this type of enum as well.

As of this patch, we create a type called `region` as part of
`CREATE DATABASE` if `REGIONS` is specified. Currently, this type is
created under the public schema, but this is to change in an upcoming
patch. See #56877 for details.

Release note (sql change): When creating a database with the regions
clause specified we create a `regions` enum type underneath the hood.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MLykNSiEgdsYY7Nmf0U:-MLykNSjDciLo8E7HnbJ:b4ar52o) ([raw file](https://github.com/cockroachdb/cockroach/blob/cda5bfd0c6aa9778a9c1bf8660b258624265a5af/pkg/sql/catalog/descpb/structured.proto#L1183)):*
> ```protobuf
> 
>   // Set to true if the enum is an internal, regional enum.
>   optional bool is_region_enum = 16 [(gogoproto.nullable) = false];
> ```

Now that I look at this more, I'm starting to feel this should go on the `Kind` enum above as `MULTI_REGION_ENUM` or something instead of here. I'll make that change and update this.

**Comment by arulajmani** [comment]
Made the change mentioned above, this should be good for a look now @otan

**Review by otan — COMMENTED** [review]
Looking good besides the open questions. 

> Reviewed 3 of 8 files at r1, 12 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-:-MMOpO421e28WhdQ2B9R:b-qxcilc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @otan)

___
*[pkg/sql/alter_type.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOjeQEEO3rc1jO4zed:-MMOjeQEEO3rc1jO4zee:bhkvjh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/alter_type.go#L62)):*
> ```Go
> 		return nil, errors.WithHint(
> 			pgerror.Newf(pgcode.WrongObjectType,
> 				"%q is a multi region enum and can't be modified using the alter type command",
> ```

nit: multi-region?
___
*[pkg/sql/descriptor.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOlo496Kqa3TkELbtX:-MMOlo496Kqa3TkELbtY:b1sdm8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/descriptor.go#L124)):*
> ```Go
> 		// called region to something else? We definitely want control over what
> 		// the per database region enum is called.
> 		regionEnumID, err := p.createEnum(
> ```

can we put it in an alternative internal schema?
___
*[pkg/sql/drop_type.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOk8sU5ZM0LCMu9A2y:-MMOk8sU5ZM0LCMu9A2z:b-gmspvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/drop_type.go#L71)):*
> ```Go
> 			return nil, errors.WithHint(pgerror.Newf(
> 				pgcode.DependentObjectsStillExist,
> 				"%q is a multi region enum and cannot be modified directly",
> ```

nit: multi-region?

also prefer new line per arg, i.e.

```
return nil, errors.WithHint(
   pgerror.Newf(
     ...,
     ..,
   ),
)

```
___
*[pkg/sql/drop_type.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOkIDb4wd8n6oRZWgQ:-MMOkIDb4wd8n6oRZWgR:b-7lf3vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/drop_type.go#L73)):*
> ```Go
> 				"%q is a multi region enum and cannot be modified directly",
> 				name,
> 			), "try ALTER DATABASE DROP REGION syntax")
> ```

nit: "ALTER DATABASE DROP REGION %s", name
___
*[pkg/sql/pg_catalog.go, line 1297 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOkPCi1grDUhf5gd32:-MMOkPCi1grDUhf5gd33:b-1iyolp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/pg_catalog.go#L1297)):*
> ```Go
> 		return forEachTypeDesc(ctx, p, dbContext, func(_ *dbdesc.Immutable, _ string, typDesc *typedesc.Immutable) error {
> 			// We only want to iterate over ENUM types.
> 			// TODO(arul): How should multi-region enum interact with pg_catalog and SHOW ENUMS?
> ```

i do not like personal TODOs. can we create an issue for each of these or use TODO(#multiregion) or resolve them?
___
*[pkg/sql/catalog/descpb/structured.proto, line 1149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOkZ4gCokEF9I7Nv-U:-MMOkZ4gCokEF9I7Nv-V:b-xq0pbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/catalog/descpb/structured.proto#L1149)):*
> ```protobuf
>     // Represents a special multi-region enum type which tracks avaiable regions
>     // as its enum values.
>     MULTI_REGION_ENUM = 2;
> ```

wonder if we want MULTIREGION, hehe.....
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOl-5I5HDcCk6lVquI:-MMOl-5I5HDcCk6lVquJ:b-hy3fun) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/catalog/typedesc/type_desc.go#L197)):*
> ```Go
> // IsRegionEnum returns true if the type descriptor refers to a special
> // multi-region region enum.
> func (desc *Immutable) IsRegionEnum() bool {
> ```

nit: `IsMultiRegionEnum()`
___
*[pkg/storage/enginepb/mvcc3.pb.go, line 4230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOkwBdA1Vk8UCFFWSL:-MMOkwBdA1Vk8UCFFWSM:ba06pjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/storage/enginepb/mvcc3.pb.go#L4230)):*
> ```Go
> 
> var (
> 	ErrInvalidLengthMvcc3 = fmt.Errorf("proto: negative length found during unmarshaling")
> ```

revert these

**Review by arulajmani — COMMENTED** [review]
Thanks for the initial pass through on this. I think this is ready to be un-WIPed now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-:-MMWHK8V6xSZEThwxJNM:b-e9dk1y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/sql/descriptor.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOlo496Kqa3TkELbtX:-MMS7Oz-6S4nIaKtnfL1:bqip1nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/descriptor.go#L124)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we put it in an alternative internal schema?
</blockquote></details>

I opened up an issue for this https://github.com/cockroachdb/cockroach/issues/56877 so we can  p a r a l l e l i z e  work 
___
*[pkg/sql/pg_catalog.go, line 1297 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOkPCi1grDUhf5gd32:-MMS6e9HAm0CuQQRWrZe:b-nppkgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/pg_catalog.go#L1297)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i do not like personal TODOs. can we create an issue for each of these or use TODO(#multiregion) or resolve them?
</blockquote></details>

Ah this (and some others) were more so to get your initial opinion on them. For this one in particular, I'll open an issue and link it with a TODO(#multiregion). https://github.com/cockroachdb/cockroach/issues/56905
___
*[pkg/sql/catalog/descpb/structured.proto, line 1149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOkZ4gCokEF9I7Nv-U:-MMS6bWPAhCeazPftNZJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/catalog/descpb/structured.proto#L1149)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

wonder if we want MULTIREGION, hehe.....
</blockquote></details>

Done.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOl-5I5HDcCk6lVquI:-MMRKAuo9CDI0ElWX9im:b-dw96zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/sql/catalog/typedesc/type_desc.go#L197)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: `IsMultiRegionEnum()`
</blockquote></details>

My bad, this is unused now and I forgot to remove it between approach switches. Fixed now. 
___
*[pkg/storage/enginepb/mvcc3.pb.go, line 4230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMOkwBdA1Vk8UCFFWSL:-MMWHIPbE54-Xh4Ojh-W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4139694df589e6a7385f65cb5e5a883d2d385e59/pkg/storage/enginepb/mvcc3.pb.go#L4230)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

revert these
</blockquote></details>

Done.

**Review by otan — COMMENTED** [review]
just nits from me. @ajstorm do you want to take a squiz as well?

> Reviewed 11 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-:-MMn7Mp78ApX5l8SQ4be:b-23h3lt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @otan, and @pbardea)

___
*[pkg/sql/alter_type.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn5zmz8EgrrO4RUMig:-MMn5zmz8EgrrO4RUMih:b-1aq6ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/alter_type.go#L59)):*
> ```Go
> 		)
> 	case descpb.TypeDescriptor_MULTIREGION_ENUM:
> 		// Multi region enums can't be directly modified.
> ```

nit: Multi-region
___
*[pkg/sql/crdb_internal.go, line 1666 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn61dAB4vfbI-9YC7u:-MMn61dAB4vfbI-9YC7v:b5v5x3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/crdb_internal.go#L1666)):*
> ```Go
> 		return forEachTypeDesc(ctx, p, db, func(db *dbdesc.Immutable, sc string, typeDesc *typedesc.Immutable) error {
> 			switch typeDesc.Kind {
> 			// TODO(arul): How does TypeDescriptor_MULTIREGION_ENUM interact w CRDB
> ```

i think you can replace this with an issue number now. or remove this?
___
*[pkg/sql/create_type.go, line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn6H-x6ZlD-Fxh2mC1:-MMn6H-x6ZlD-Fxh2mC2:b-ujujfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/create_type.go#L248)):*
> ```Go
> 	dbDesc catalog.DatabaseDescriptor,
> 	typeName *tree.TypeName,
> 	isRegionEnum bool,
> ```

can we use a const or something instead?
see "Avoid Naked Parameters" in https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+coding+guidelines
even better, just use the new kind in here.
___
*[pkg/sql/create_type.go, line 329 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn6VnHEI9JVBMUwYWL:-MMn6VnHEI9JVBMUwYWM:b-i969af) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/create_type.go#L329)):*
> ```Go
> 	arrayTypeID := descpb.InvalidID
> 	if !isRegionEnum {
> 		arrayTypeID, err = p.createArrayType(params, typeName, typeDesc, dbDesc, schemaID)
> ```

do we want to do this anyway?
i think a lot of our smithing requires arrays to work
___
*[pkg/sql/drop_type.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn6i1U0iZzAahp2JHc:-MMn6i1U0iZzAahp2JHd:bqag5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/drop_type.go#L68)):*
> ```Go
> 			)
> 		case descpb.TypeDescriptor_MULTIREGION_ENUM:
> 			// The implicit array types are not directly droppable.
> ```

what's the array in this case?
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn75mm8S7t1KTGatQV:-MMn75mm8S7t1KTGatQW:b-gainai) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/catalog/typedesc/type_desc.go#L450)):*
> ```Go
> 	// exists regardless of what the type descriptor kind is. For now, I have this
> 	// here because the multi region enum can't read the database descriptor that
> 	// was created as part of the same txn.
> ```

is there an issue to follow?
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn7GT74Oq7kUmaRlgc:-MMn7GT74Oq7kUmaRlgd:baqwc9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/logictest/testdata/logic_test/multiregion#L33)):*
> ```
> 
> statement error "multi_region_test_db.public.region" is a multi-region enum and can't be modified using the alter type command
> ALTER TYPE multi_region_test_db.public.region ADD VALUE 'test3'
> ```

i think we're going to have a rebase clash here, hehe

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @otan)

___
*[pkg/ccl/backupccl/restore_planning.go, line 832 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMqQ7Xo5yAtapyKSlln:-MMqQ7Xp081azQjHnX4T:bgyr5cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/ccl/backupccl/restore_planning.go#L832)):*
> ```Go
> 		}
> 		switch t := typ.Kind; t {
> 		case descpb.TypeDescriptor_ENUM, descpb.TypeDescriptor_MULTIREGION_ENUM:
> ```

Is this what we want? Do multiregion enums have an ArrayTypeID (next line), won't it be InvalidID? 

Also, could we either add a backup/restore test with a multiregion enum (see ccl/backupccl/testdata/backup-restore/user-defined-types, or file an issue tracking multiregion enums <> backup compatibility and do that in a follow up?)

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @otan, and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 832 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMqQ7Xo5yAtapyKSlln:-MMwYTR-7v_RbPT2G-i-:b6lh1ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/ccl/backupccl/restore_planning.go#L832)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Is this what we want? Do multiregion enums have an ArrayTypeID (next line), won't it be InvalidID? 

Also, could we either add a backup/restore test with a multiregion enum (see ccl/backupccl/testdata/backup-restore/user-defined-types, or file an issue tracking multiregion enums <> backup compatibility and do that in a follow up?)
</blockquote></details>

Thanks for catching this, fixed now. We'll have to teach the backup datadriven tests about region as well -- considering this, I'll open this up as a follow up issue for the tests. It's tracked here: https://github.com/cockroachdb/cockroach/issues/57091
___
*[pkg/sql/crdb_internal.go, line 1666 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn61dAB4vfbI-9YC7u:-MMr4O_I7NL50RSOholg:bfd1t4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/crdb_internal.go#L1666)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think you can replace this with an issue number now. or remove this?
</blockquote></details>

I linked the issue from the other file. 
___
*[pkg/sql/create_type.go, line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn6H-x6ZlD-Fxh2mC1:-MMr2olT1UD9MO2j6x5k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/create_type.go#L248)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we use a const or something instead?
see "Avoid Naked Parameters" in https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+coding+guidelines
even better, just use the new kind in here.
</blockquote></details>

Done.
___
*[pkg/sql/create_type.go, line 329 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn6VnHEI9JVBMUwYWL:-MMwQhg_51W0FuAX-QUw:bz9m5j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/create_type.go#L329)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do we want to do this anyway?
i think a lot of our smithing requires arrays to work
</blockquote></details>

Created this https://github.com/cockroachdb/cockroach/issues/57089 as a followup. 
___
*[pkg/sql/drop_type.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn6i1U0iZzAahp2JHc:-MMr4g7o6kNNvmHZEHv-:bh8d2hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/drop_type.go#L68)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

what's the array in this case?
</blockquote></details>

copy pasta error oops, fixed. 
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn75mm8S7t1KTGatQV:-MMwPiXK45zGQARdO8LF:bpuj9fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/catalog/typedesc/type_desc.go#L450)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

is there an issue to follow?
</blockquote></details>

Created https://github.com/cockroachdb/cockroach/issues/57087 and linked it here.
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMn7GT74Oq7kUmaRlgc:-MMwPyPG3VjHYV0Ji3_5:b2nh4el) ([raw file](https://github.com/cockroachdb/cockroach/blob/c60eef7ee53ca17fa3a56d5969e6012945ae8189/pkg/sql/logictest/testdata/logic_test/multiregion#L33)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think we're going to have a rebase clash here, hehe
</blockquote></details>

:(

**Review by otan — COMMENTED** [review]
will take a look again after the rebase :3 

> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-:-MMyINzIEqTFFejq364X:ba7zg1c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @otan, and @pbardea)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1095 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MMyIIp61Y7CMc0LXTCV:-MMyIIp61Y7CMc0LXTCW:brvcmyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/390e651a4568fb69d170c99d1c173f66b4d6db69/pkg/sql/catalog/descpb/structured.proto#L1095)):*
> ```protobuf
>   // region enum for a multi-region database. If the database is not a
>   // multi-region database then this field is 0 and no such region enum exists.
>   optional uint32 region_enum_id = 10 [(gogoproto.nullable) = false, (gogoproto.customname) = "RegionEnumID", (gogoproto.casttype) = "ID"];
> ```

can you rebase and put this in the region config?

**Comment by arulajmani** [comment]
Did the rebase and updated this stuff to work with the multiregion config -- should RFAL. 😅

**Comment by arulajmani** [comment]
Still failing a test, but that should be resolved once #57151 goes in and I rebase on top.

**Review by otan — APPROVED** [review]
many blessings to your rebase. LGTM after tests pass, feel free to merge over the weekend

> Reviewed 3 of 9 files at r4, 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-:-MN5T_hw3XnR5_XvElZF:bh5ckjd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @otan, and @pbardea)

___
*[pkg/sql/crdb_internal.go, line 1696 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MN5TKyv4hgqq9EIn3u3:-MN5TKyv4hgqq9EIn3u4:b-qen1uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b36ff1d20ceec447438d36f14eb00a919a5f32f/pkg/sql/crdb_internal.go#L1696)):*
> ```Go
> 			switch typeDesc.Kind {
> 			// TODO(#multiregion): We're missing multi region enum introspection
> 			// currently. see https://github.com/cockroachdb/cockroach/issues/56905
> ```

nit: See

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 28 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MN5TmGnAZin158_kHh3:-MN5TmGnAZin158_kHh4:bfay7gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b36ff1d20ceec447438d36f14eb00a919a5f32f/pkg/sql/logictest/testdata/logic_test/multiregion#L28)):*
> ```
> 53        29              region  54
> 55        29              region  56
> 57        29              region  58
> ```

can we add a `SHOW ENUMS` test here, or does that not work?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @otan, and @pbardea)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 28 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56628#-MN5TmGnAZin158_kHh3:-MN5duE4AttAzbw_s1u3:b-dyjpco) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b36ff1d20ceec447438d36f14eb00a919a5f32f/pkg/sql/logictest/testdata/logic_test/multiregion#L28)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we add a `SHOW ENUMS` test here, or does that not work?
</blockquote></details>

Not yet, but I'll be sure to add one as part of the introspection followup to this.

**Comment by arulajmani** [comment]
CI is green, so should be good to merge. Thanks for the reviews on this! 

bors r=otan

**Pull request merged**
