### PR TITLE
cli: small improvements to error messages.

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13411)

### CODE REVIEW

**Comment by mjibson** [comment]
I think we need a test for this. If we had had one, it would have caught this, right?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13411#-:-KcGplzmctGSWoV4iOf5:b-mm3370)*

**Comment by knz** [comment]
Agreed, done.

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13411#-:-KcJUsQgjMlnPkhe7YUP:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
