### PR TITLE
sql: add transaction_fingerprint_id to system.statement_statistics pk

### PR DESCRIPTION
**Pull request by Azhng**
Previously, statements belong to different transaction fingerprints but
has same statement fingerprint IDs get rolled up into a single entry
in system.statement_statistics.
This commit introduce additional transaction_fingerprint_id column in the
system.statement_statistics primary key to enable that differentiation.
This commit does not implement filling the new columns. Therefore, the
new column is currently left as blank. This will be addressed in the later
PRs.

Release justification: Category 4: Low risk, high benefit changes to existing
 functionality

Release note (sql change): add transaction_fingerprint_id to
 system.statement_statistics primary key.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
From an observability perspective :lgtm: 
But get the approval from SQL Schema too

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-:-Mhxd4319ChCXR4m_cVx:b-ctmgwd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

___
*[pkg/sql/catalog/systemschema/system.go, line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-Mi2HWqBC7moaEW4omr7:-Mi2HWqC7ieV5yPS2am_:b-dbm2iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f708a8c07333c390f59a46b0e385b3a3bf784941/pkg/sql/catalog/systemschema/system.go#L480)):*
> ```Go
>     plan JSONB NOT NULL,
> 
>     PRIMARY KEY (aggregated_ts, fingerprint_id, transaction_fingerprint_id, plan_hash, app_name, node_id)
> ```

How did you decide where to put this in the primary key? Is the expectation that people will be looking up statements by `transaction_fingerprint_id` most often? 
___
*[pkg/sql/catalog/systemschema/system.go, line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-Mi2HoCiAGiA_tS5Klxc:-Mi2HoCiAGiA_tS5Klxd:bbo81zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f708a8c07333c390f59a46b0e385b3a3bf784941/pkg/sql/catalog/systemschema/system.go#L482)):*
> ```Go
>     PRIMARY KEY (aggregated_ts, fingerprint_id, transaction_fingerprint_id, plan_hash, app_name, node_id)
>       USING HASH WITH BUCKET_COUNT = 8,
>     INDEX "fingerprint_stats_idx" (fingerprint_id, aggregated_ts, transaction_fingerprint_id, plan_hash, app_name, node_id),
> ```

I should have caught this earlier, it's a bit unconventional to explicitly state these primary key columns in the index definition. All secondary indexes have all of the primary index columns in their key. I think that this should just be `INDEX (fingerprint_id)` to better capture its intention.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @maryliag)

___
*[pkg/sql/catalog/systemschema/system.go, line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-Mi2HWqBC7moaEW4omr7:-Mi2RgFx6Hwq8yZauCoV:b-lpjyt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f708a8c07333c390f59a46b0e385b3a3bf784941/pkg/sql/catalog/systemschema/system.go#L480)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How did you decide where to put this in the primary key? Is the expectation that people will be looking up statements by `transaction_fingerprint_id` most often? 
</blockquote></details>

My reasoning here is that this is primary for Transaction Detail Page in the DB Console. Since there we will be looking at the statements belonging to a `transaction_fingerprint_id`. 
___
*[pkg/sql/catalog/systemschema/system.go, line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-Mi2HoCiAGiA_tS5Klxc:-Mi2RfGo3hijw1iGjW-F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f708a8c07333c390f59a46b0e385b3a3bf784941/pkg/sql/catalog/systemschema/system.go#L482)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I should have caught this earlier, it's a bit unconventional to explicitly state these primary key columns in the index definition. All secondary indexes have all of the primary index columns in their key. I think that this should just be `INDEX (fingerprint_id)` to better capture its intention. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[pkg/sql/catalog/systemschema/system.go, line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-Mi2HWqBC7moaEW4omr7:-Mi2XtX710O5J82hqiUu:bow7ej3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f708a8c07333c390f59a46b0e385b3a3bf784941/pkg/sql/catalog/systemschema/system.go#L480)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

My reasoning here is that this is primary for Transaction Detail Page in the DB Console. Since there we will be looking at the statements belonging to a `transaction_fingerprint_id`. 
</blockquote></details>

In that case, do we want to change the secondary index to be `(fingerprint_id, transaction_fingerprint_id)`? Or do we want it to be `(fingerprint_id, aggregated_ts)`? I assume that the way this query will work is by looking up the transaction, which, I assume, has the set of statement fingerprints. Then, we'd go fetch each statement fingerprint. That means we want. an index based on fingerprint_id, transaction_fingerprint_id regardless of the timestamp, no?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @maryliag)

___
*[pkg/sql/catalog/systemschema/system.go, line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-Mi2HWqBC7moaEW4omr7:-Mi2ia5GDDAe4Py5SXLn:b-ggc5bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f708a8c07333c390f59a46b0e385b3a3bf784941/pkg/sql/catalog/systemschema/system.go#L480)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In that case, do we want to change the secondary index to be `(fingerprint_id, transaction_fingerprint_id)`? Or do we want it to be `(fingerprint_id, aggregated_ts)`? I assume that the way this query will work is by looking up the transaction, which, I assume, has the set of statement fingerprints. Then, we'd go fetch each statement fingerprint. That means we want. an index based on fingerprint_id, transaction_fingerprint_id regardless of the timestamp, no?
</blockquote></details>

Good point. Updated the secondary index to include `transaction_fingerprint_id`.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69320#-:-Mi3_9xp3TmPxL1KLx3d:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @maryliag)

**Pull request merged**
