### PR TITLE
cli/zip: emit SQL table data using TSV by default

### LINKED ISSUE #107473: cli/zip: restore the previous default of `--format` to `tsv`
Requested by @dt, @rupertharwood-crl and others.

Internal discussion [here](https://cockroachlabs.slack.com/archives/C01CNRP6TSN/p1690204772018929)

Epic: CRDB-28893

Jira issue: CRDB-30065

### PR DESCRIPTION
**Pull request by knz**
Fixes #107473.
Epic: CRDB-28893

This is a partial revert of 35738d43ee5721078c53b4c88a4aee6fb8090c73.

It changes the default value of the `--format` flag back from JSON to TSV.

Release note (backward-incompatible change):
THIS RELEASE NOTE CANCELS THE CORRESPONDING PREVIOUS BACKWARD-INCOMPATIBLE CHANGE. New behavior, compatible with previous versions of CockroachDB: the command `cockroach debug zip` stores data retrieved from SQL tables in the remote cluster using the TSV format by default.

Release note (cli change): The default value of the `--format` parameter to `cockroach debug zip` is `tsv`, like other CLI commands that can extract SQL data.

### CODE REVIEW

**Comment by knz** [comment]
i'll wait for CI to tell me which tests need updating.

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107474#-:-NaHtY1MBv632Lb31sLY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/testdata/zip/testzip_external_process_virtualization` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107474#-NaHtRS_DonR7OXveTKr:-NaHtRS_DonR7OXveTKs:bo2rdxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a805f60c3add2fbbb4710f9197386a201cfa32f/pkg/cli/testdata/zip/testzip_external_process_virtualization#L155)):*
> ```
> [node ?] ? log files found
> [node 1] [log file: ...
> [node 1] [log file: ...
> ```

nit: Just curious - what about this change impacted the test outputs such that we have these extra lines?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107474)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier)

___
*[`pkg/cli/testdata/zip/testzip_external_process_virtualization` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107474#-NaHtRS_DonR7OXveTKr:-NaNS-Hm34aVSXycyGYk:b-9m6qri) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a805f60c3add2fbbb4710f9197386a201cfa32f/pkg/cli/testdata/zip/testzip_external_process_virtualization#L155)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Just curious - what about this change impacted the test outputs such that we have these extra lines? 
</blockquote></details>

This was actually some extra non-determinism we had there already (and thus possible source of flakes).

Fixed.

**Comment by knz** [comment]
bors r=abarganier

**Pull request merged**
