### PR TITLE
opt: fix bug in histogram filtering code for uuid and string predicates

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, an equality constraint on some types such as uuids
and strings could result in inaccurate stats when using a histogram. This
was happening when the literal fell within a histogram bucket, and not at
the upper bound. Since in general it is not possible to estimate the number
of values within an arbitrary range for these types, we always guessed that
half of the values in the bucket were included. However, this can be wildly
inaccurate when the bucket contains many distinct values.

This commit fixes the problem by adding a special case for equality
conditions. Instead of estimating the selectivity to be 1/2 of the bucket,
it estimates it as 1/distinct_count of the bucket.

Release note (performance improvement): Fixed a bug in the histogram filtering
logic in the optimizer which was causing inaccurate cardinality estimates
for queries with equality predicates on UUIDs and strings, as well as
some other types. This bug has existed since histograms were first introduced
into the optimizer in the 19.2.0 release. Fixing it improves the optimizer's
cardinality estimates and results in better query plans in some cases.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48580)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-M6opJkM39MlAXlYOFd0:-M6opJkM39MlAXlYOFd1:b5r2mxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/414b34b2519574ccca269ed9e64a7da1ff8f3f61/pkg/sql/opt/props/histogram.go#L535)):*
> ```Go
> 
> 	// Extract the range sizes before and after filtering.
> 	rangeBefore, rangeAfter, ok := getRangesBeforeAndAfter(
> ```

Wouldn't it be cleaner if we improved`getRangesBeforeAndAfter` to return rangeAfter=0 for all types when the keys are equal? The end result would be the same right?
___
*[pkg/sql/opt/props/histogram.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-M6oohdPANP24-FZJ8ON:-M6oohdPANP24-FZJ8OO:bf4t9wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/414b34b2519574ccca269ed9e64a7da1ff8f3f61/pkg/sql/opt/props/histogram.go#L566)):*
> ```Go
> 	} else if ok && rangeBefore > 0 {
> 		if isDiscrete(bucketLowerBound.ResolvedType()) && !includesOriginalUpperBound {
> 			// The data type is discrete (e.g., integer or date) and the new upper
> ```

should `uuid` also be considered "discrete"? How about bools, timestamps, intervals?

**Review by rytaft — COMMENTED** [review]
TFTR!

I restructured the code a bit and added more comments to hopefully make the flow clearer.

The one thing I'm not sure about is what to do in the case where we have a type like UUID, string, or float used in a non-equality condition that does not overlap the original upper bound (e.g., `[/'abc' - /'abd']` filtering a bucket with range `[/'a' - /'f']`). Currently, the new bucket will have `NumEq` set to 0. An alternative is to assign `NumEq` to be equal to `NumRange/DistinctRange` from the original bucket, but I think that would give it too much weight relative to the new value of `NumRange`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-:-M6qFKi_6CNkPG5UYRSC:b-7k8d2j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/props/histogram.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-M6opJkM39MlAXlYOFd0:-M6pXadt3WKllsswBDEa:b-uoqb4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/414b34b2519574ccca269ed9e64a7da1ff8f3f61/pkg/sql/opt/props/histogram.go#L535)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Wouldn't it be cleaner if we improved`getRangesBeforeAndAfter` to return rangeAfter=0 for all types when the keys are equal? The end result would be the same right?
</blockquote></details>

That's already the case for all types that return ok=true. I'm not sure it helps for other types, though, since rangeBefore is undefined.

Maybe I'm not understanding the suggestion? 
___
*[pkg/sql/opt/props/histogram.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-M6oohdPANP24-FZJ8ON:-M6pZNMyE3dw_1jMV-I8:b-c5wppk) ([raw file](https://github.com/cockroachdb/cockroach/blob/414b34b2519574ccca269ed9e64a7da1ff8f3f61/pkg/sql/opt/props/histogram.go#L566)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

should `uuid` also be considered "discrete"? How about bools, timestamps, intervals?
</blockquote></details>

UUIDs and bools can't enter this block since they aren't a numeric type and would return ok=false from `getRangesBeforeAndAfter`. I haven't yet added intervals to `getRangesBeforeAndAfter`, but I probably should (I'll do it in a separate PR). Timestamp can enter this block, and I think you're right that we can consider it discrete since the range is in units of nanoseconds -- but that also means it has a negligible impact. I made the change, anyway.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

NumEq = 0 seems reasonable in that case - if the values were randomly distributed, the probability that there is even one value with exactly the new upper bound is very low.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-:-M6qwD8P8bWSnIeDNkk3:btihk1h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-M6opJkM39MlAXlYOFd0:-M6qw1RrD9b0Fw1eVMCB:b-4bl6qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/414b34b2519574ccca269ed9e64a7da1ff8f3f61/pkg/sql/opt/props/histogram.go#L535)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

That's already the case for all types that return ok=true. I'm not sure it helps for other types, though, since rangeBefore is undefined.

Maybe I'm not understanding the suggestion? 
</blockquote></details>

Ah, sorry, didn't think that through.

**Review by rytaft — COMMENTED** [review]
Sounds good - thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48580#-:-M6rWpkyC7pn_uz66oIF:b-ptp7wu)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
How come it's not possible to estimate the number of values within an arbitrary range for string/UUID? Say a bucket looked like this:
```
start: 'bear'
end: 'bobcat'
count: 100
```
And the range is ['bluejay' - 'boar'].

If the string were encoded as sorted key bytes (i.e. the CRDB key representation), then think about each byte as a base(16) number that's zero extended to be the same number of bytes (or treated as a fraction), with common bit prefixes dropped and only, say, 4 total bytes retained (since we don't need a ton of precision).
```
bear   = 62 65 61 72 00 00 00 = 0x62656172000000 = 0x56172000
bobcat = 62 6f 62 63 61 74 00 = 0x626f6263617400 = 0xf6263617
bluejay = 62 6c 75 65 6a 61 79 = 0x626c75656a6179 = 0xc75656a6
boar     = 62 6f 61 72 00 00 00 = 0x626f6172000000 = 0xf6172000
```
Then, you can estimate the number of values in the range ['beaver' - 'bee']:
```
(boar - bluejay) / (bobcat - bear) = (0xf6172000 - 0xc75656a6) / (0xf6263617 - 0x56172000) = 29.2% = 29.2 rows
```
I haven't considered each data type, but this method would probably work pretty well for many (maybe most/all?) of them, since we've already done the hard work of putting them into a sortable byte format, and most/all types will be uniformly distributed across their byte representation.

Rebecca/Radu, are there flaws in my thinking here?

**Comment by rytaft** [comment]
I think this sounds right -- we'll need to test each of the non-numeric types separately, but it's definitely worth investigating further.

**Comment by rytaft** [comment]
Opened #49568 to track this.

**Pull request merged**
