### PR TITLE
sql: add schema change state machine states to job running status

### LINKED ISSUE #32916: sql: Show the schema change state machine changes in the jobs table
Sometimes the schema change state machine hangs because it is waiting on older leases on descriptors to be released. It will be valuable to see the current state of a schema change and potentially the leases it is waiting on. Currently the system is quite opaque about the state machine and only reports on progress after the state machine has run and the system is backfilling.

A similar solution was implemented for DROP TABLE; for instance, a job for DROP TABLE now reports that the job is waiting for the GC interval to expire.

### PR DESCRIPTION
**Pull request by vivekmenezes**
fixes #32916

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@dt hmmm looks like there's more work needed here

**Comment by vivekmenezes** [comment]
@dt it would have been nice to get rid of DroppedTableDetails but that's part of SchemaChangeDetails. Leaving it out of this PR.

**Comment by vivekmenezes** [comment]
@dt this is ready for review. Thanks!

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35961)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @vivekmenezes)

___
*[pkg/sql/schema_changer.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35961#-LaS1dA5B4nQglBHU2D0:-LaS1dA5B4nQglBHU2D1:boqsa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/120cc663838cf0d6e94b0353f66659586648042f/pkg/sql/schema_changer.go#L95)):*
> ```Go
> 	// the cluster to converge to seeing the schema element in the DELETE_ONLY
> 	// state.
> 	RunningStatusDeleteOnly jobs.RunningStatus = "waiting in DELETE_ONLY"
> ```

I think we should hide these internal names.

I'd suggesting "Preparing to start (step 1 of 2)" or something.
___
*[pkg/sql/schema_changer.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35961#-LaS1u9I17xUNB3WHO5_:-LaS1u9I17xUNB3WHO5a:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/120cc663838cf0d6e94b0353f66659586648042f/pkg/sql/schema_changer.go#L99)):*
> ```Go
> 	// the cluster to converge to seeing the schema element in the
> 	// DELETE_AND_WRITE_ONLY state.
> 	RunningStatusDeleteAndWriteOnly jobs.RunningStatus = "waiting in DELETE_AND_WRITE_ONLY"
> ```

Ditto.
___
*[pkg/sql/schema_changer.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35961#-LaS1wWr5ZM2xHV6-PTp:-LaS1wWr5ZM2xHV6-PTq:b-4ypc3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/120cc663838cf0d6e94b0353f66659586648042f/pkg/sql/schema_changer.go#L102)):*
> ```Go
> 	// RunningStatusBackfill is for jobs that are currently running a backfill
> 	// for a schema element.
> 	RunningStatusBackfill jobs.RunningStatus = "backfilling"
> ```

This is probably a better known term, but I think I'd still use simpler wording e.g. "Populating index" 
___
*[pkg/sql/schema_changer.go, line 1010 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35961#-LaS2hUz9AR-q4OzXeo9:-LaS2hUz9AR-q4OzXeoA:b-sg6ys7) ([raw file](https://github.com/cockroachdb/cockroach/blob/120cc663838cf0d6e94b0353f66659586648042f/pkg/sql/schema_changer.go#L1010)):*
> ```Go
> 			}
> 		}
> 		if runStatus == "" || desc.Dropped() {
> ```

_very slight_ subjective preference: I think it was clearer with the separate, named bool.

**Comment by awoods187** [comment]
Hey I saw this today and didn't understand it:
image

**Comment by dt** [comment]
Yeah, IMO those are internal names, that only really have meaning to use. I think we could user friendlier user-facing names like "preparing (step 1/2)" and "preparing (step 2/2)" and a) it wouldn't be confusing to a user while b) if it gets stuck there and they ask us about it, the message still uniquely maps to the states so we'd still have just as much information to work with, but without putting it in front of a user to whom it is useless and confusing.

**Pull request merged**
