### PR TITLE
sql: check FKs during UPDATEs

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7081)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/rowwriter.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-KJfXAA2MvYJcLHdkZAj:-KJfXAA36Xn-bW-iIB1l:2097272261) ([raw file](https://github.com/cockroachdb/cockroach/blob/277cfdb91bdb47bcb814a7752fd2b212054d235b/sql/rowwriter.go#L365)):*
> ```Go
> 			return rowUpdater{}, err
> 		}
> 		if ru.fksBefore, err = makeFKDeleteHelper(txn, tableDesc, ru.fetchColIDtoRowIndex); err != nil {
> ```

is this is the same in both branches?

---

*[sql/rowwriter.go, line 479 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-KJfZlENTYyykr8gbkYz:-KJfZlENTYyykr8gbkZ-:723390177) ([raw file](https://github.com/cockroachdb/cockroach/blob/277cfdb91bdb47bcb814a7752fd2b212054d235b/sql/rowwriter.go#L479)):*
> ```Go
> 		}
> 
> 		if err := ru.fksBefore.checkIdx(ru.helper.tableDesc.PrimaryIndex.ID, oldValues); err != nil {
> ```

I don't understand why deleteRow and insertRow are handled differently here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081)*

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/rowwriter.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-KJfXAA2MvYJcLHdkZAj:-KJg3eNGUN5mY23oUPc7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/277cfdb91bdb47bcb814a7752fd2b212054d235b/sql/rowwriter.go#L365)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> is this is the same in both branches?
</details>
Done.

---

*[sql/rowwriter.go, line 479 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-KJfZlENTYyykr8gbkYz:-KJfe12paWcxULbPaG5l:1590968270) ([raw file](https://github.com/cockroachdb/cockroach/blob/277cfdb91bdb47bcb814a7752fd2b212054d235b/sql/rowwriter.go#L479)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I don't understand why deleteRow and insertRow are handled differently here
</details>
Delete is overly strict -- it will think unchanged values are being deleted when they are just being moved to the new row. insert was technically correct, checking everything still pointed to things, but was potentially doing more work than needed.

Refactored to always just check changed indexes individually and both the inserter and deleter now always skip FK checks when created in updater.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081)*

**Comment by paperstreet** [comment]
:lgtm:

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> #### sql: check FKs during UPDATEs
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/rowwriter.go, line 494 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-KJg8Vc5TAnocngisdfb:-KJg8Vc6d19PTVpG55Zj:-634892136) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2bade1aefaf08ac47e4de1208caccde7a30a60/sql/rowwriter.go#L494)):*
> ```Go
> 			return nil, err
> 		}
> 		if err := ru.fks.checkIdx(ru.helper.tableDesc.PrimaryIndex.ID, oldValues, ru.newValues); err != nil {
> ```

nit: is there a reason this is between the deleteRow and insertRow?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-:-KJg8j-cJMNkTsnK6xcq:1417088721)*

**Comment by dt** [comment]
(couple more small cleanups)

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/rowwriter.go, line 494 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-KJg8Vc5TAnocngisdfb:-KJgCqRGn0BXJJSjHKQr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2bade1aefaf08ac47e4de1208caccde7a30a60/sql/rowwriter.go#L494)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> nit: is there a reason this is between the deleteRow and insertRow?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7081#-:-KJgCvXbm2zQRXxm_b57:577877971)*

**Comment by bdarnell** [comment]
@dt are FKs ready to be announced and documented in this week's beta or is there more work to do?

**Comment by dt** [comment]
@bdarnell I'd prefer to write more extensive logic tests before we say they're ready for prime time.
There is also some more subtle work left to do specifically around handling in-progress schema-changes (and I think TRUNCATE).

**Pull request merged**
