### PR TITLE
opt: use histograms for inverted JSON/ARRAY scan statistics

### LINKED ISSUE #56870: opt: ensure statistics builder correctly estimates selectivity of b @> '[]' and b @> '{}'
Prior to #56732, queries like `SELECT * from d where b @> '[]';` and `SELECT * from d where b @> '{}';` would cause a full scan of the primary index, even if there was an inverted index on column `b`.

After #56732, the optimizer now plans an inverted index scan for these queries followed by an inverted filter. This is a very bad plan, however, because `b @> '[]'` and `b @> '{}'` cause a full scan of the inverted index. The statistics builder should be taught that this is the case so that the optimizer will never choose an inverted index scan with these predicates.

### PR DESCRIPTION
**Pull request by mgartner**
#### memo: simplify statisticsBuilder.constrainScan

A `ScanExpr`, which includes an `InvertedConstraint`, is always passed
to `statisticsBuilder.constrainScan`, therefore there is no need to pass
the `InvertedConstraint` separately.

Release note: None

#### memo: rename multi-column-inverted-geo test file to inverted-geo-multi-column

Release note: None

#### opt: use histograms for inverted JSON/ARRAY scan statistics

Fixes #56870

Release note (performance improvement): The optimizer now uses collected
histograms statistics to better estimate the cost of JSON and ARRAY
inverted index scans, which may lead to more efficient query plans.

### CODE REVIEW

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1755 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRgX9_P01p-Tt6sionZ:-MRgX9_P01p-Tt6sion_:bcg50a) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ba90ca5e68c5a78d73610e4a0a1ea0fb6eff95/pkg/sql/opt/xform/testdata/rules/select#L1755)):*
> ```
> # TODO(rytaft): ensure that the stats prevent us from using the inverted index.
> opt
> SELECT * FROM b WHERE j @> '{}'
> ```

I removed these tests, because I think they're not necessary anymore. They seem more stats-related than xform-related to me. I can add them back in, but if we want to prevent a full inverted index scan for the test I'll have to inject some histogram statistics.

I haven't bothered with trying to make the statistics builder smarter about the `j @> '{}'` expression without histograms because it seems like an uncommon case. I'm assuming we don't care too much about cases where histograms don't exist, but correct me if that's wrong.

**Review by rytaft — COMMENTED** [review]
Cool! Awesome that this didn't require a lot of changes.

> Reviewed 9 of 9 files at r4, 1 of 1 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-:-MRuAW4QEDLtoN0Dyr4B:b-gj93xi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu7uf_1Tn6WzG53TyJ:-MRu7uf_1Tn6WzG53TyK:b-5ubnoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L17)):*
> ```
> #   - 10 empty arrays
> #   - 990 arrays encoded into 1110 index entries
> #   - 10 empty object
> ```

[nit] objects
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 26 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu9I_2E7MQTwGeoozi:-MRu9I_2E7MQTwGeoozj:b-hdx523) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L26)):*
> ```
>     "created_at": "2018-01-01 1:00:00.00000+00:00",
>     "row_count": 2000,
>     "distinct_count": 3,
> ```

should this be ~10?
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 263 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu9BTv44iM5sG001zs:-MRu9BTv44iM5sG001zt:b-plbi9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L263)):*
> ```
>     "created_at": "2018-01-01 1:00:00.00000+00:00",
>     "row_count": 2000,
>     "distinct_count": 3,
> ```

should this be 5?
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 328 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu8wBz2p-g-kIIPyln:-MRu8wBz2p-g-kIIPylo:bsayx7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L328)):*
> ```
>            │         ├── ["7\x00\x019", "7\x00\x019"]
>            │         └── ["7\x00\xff", "8")
>            ├── stats: [rows=2e-07, distinct(1)=1.99999931e-07, null(1)=0, distinct(4)=2e-07, null(4)=0]
> ```

Why is the number of rows so tiny? Shouldn't this be 100?
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 359 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu95CK2U1y2bxe8_on:-MRu95CK2U1y2bxe8_oo:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L359)):*
> ```
>            │         ├── ["7\x00\x018", "7\x00\x018"]
>            │         └── ["7\x00\x03", "7\x00\x03"]
>            ├── stats: [rows=2e-07, distinct(1)=1.99999931e-07, null(1)=0, distinct(4)=2e-07, null(4)=0]
> ```

ditto
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1755 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRgX9_P01p-Tt6sionZ:-MRuAGSVDP2IAIoZA4WJ:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ba90ca5e68c5a78d73610e4a0a1ea0fb6eff95/pkg/sql/opt/xform/testdata/rules/select#L1755)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I removed these tests, because I think they're not necessary anymore. They seem more stats-related than xform-related to me. I can add them back in, but if we want to prevent a full inverted index scan for the test I'll have to inject some histogram statistics.

I haven't bothered with trying to make the statistics builder smarter about the `j @> '{}'` expression without histograms because it seems like an uncommon case. I'm assuming we don't care too much about cases where histograms don't exist, but correct me if that's wrong.
</blockquote></details>

Sounds good

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59326)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu7uf_1Tn6WzG53TyJ:-MRv9Qo4-fKo0phUAlOa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L17)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] objects
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 26 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu9I_2E7MQTwGeoozi:-MRv9fitEDSQ0A6UTnVo:b-tvvlxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L26)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this be ~10?
</blockquote></details>

Good catch. There's no exact number of distinct values based on the histograms, but there some minimum. I've set it to 10.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 263 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu9BTv44iM5sG001zs:-MRvAeqV31ieyCBcXoIQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L263)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this be 5?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 328 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu8wBz2p-g-kIIPyln:-MRvCAfhCL0-5Nk6yfuY:b-c2zxau) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L328)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why is the number of rows so tiny? Shouldn't this be 100?
</blockquote></details>

Good catch. The histogram buckets were no in order, which caused problems. Fixed.
___
*[pkg/sql/opt/memo/testdata/stats/inverted-json, line 359 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-MRu95CK2U1y2bxe8_on:-MRvCHB80MMg91TIAJvB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b245f8d0829ac53d2677b1fd0627d1a36d6221bb/pkg/sql/opt/memo/testdata/stats/inverted-json#L359)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59326#-:-MRvOKdO34VEO_YibX3N:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
TFTR!

bors r=rytaft

**Pull request merged**
