### PR TITLE
kv: use correct sequence number when scanning for conflicting intents

### LINKED ISSUE #92189: kv/kvnemesis: TestKVNemesisSingleNode failed
kv/kvnemesis.TestKVNemesisSingleNode [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7596517?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7596517?buildTab=artifacts#/) on master @ [8357abb668a5adaff781343b394b162fb1b66c6e](https://github.com/cockroachdb/cockroach/commits/8357abb668a5adaff781343b394b162fb1b66c6e):

```
=== RUN   TestKVNemesisSingleNode
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisSingleNode3963958602
    test_log_scope.go:79: use -show-logs to present logs inline
    kvnemesis_test.go:68: failure:
        committed txn non-atomic timestamps: [d]/Table/100/"08056413":1668847865.823418091,1-><nil> [s]/Table/100/"{102d0e5c"-66cda759"}:{0:[0,0, 0,0), gap:[<min>, 1668847865.588834720,1),[1668847865.793293449,0, <max>),[1668847865.680153892,1, 1668847865.792215515,0),[1668847865.603420672,1, 1668847865.680153892,1)}->[/Table/100/"2ab8e983":v-7] [w]/Table/100/"2ab8e983":1668847865.823418091,1->v-7 [rs]/Table/100/"{2ba47ac0"-c7658174"}:{0:[1668847865.823418091,0, <max>), gap:[<min>, 1668847865.588834720,0),[1668847865.588834720,0, 1668847865.588834720,1),[1668847865.795713494,0, <max>),[1668847865.793293449,0, 1668847865.795713494,0),[1668847865.680153892,1, 1668847865.743831142,0),[1668847865.603420672,1, 1668847865.680153892,1)}->[/Table/100/"9c5374b1":v-8]
        (1) attached stack trace
          -- stack trace:
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.(*validator).checkAtomicCommitted
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:845
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.(*validator).checkAtomic
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:600
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.(*validator).processOp
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:569
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.Validate
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:72
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.RunNemesis
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis.go:99
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.TestKVNemesisSingleNode
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:64
          | testing.tRunner
          | 	GOROOT/src/testing/testing.go:1446
          | runtime.goexit
          | 	GOROOT/src/runtime/asm_amd64.s:1594
        Wraps: (2) committed txn non-atomic timestamps: [d]/Table/100/"08056413":1668847865.823418091,1-><nil> [s]/Table/100/"{102d0e5c"-66cda759"}:{0:[0,0, 0,0), gap:[<min>, 1668847865.588834720,1),[1668847865.793293449,0, <max>),[1668847865.680153892,1, 1668847865.792215515,0),[1668847865.603420672,1, 1668847865.680153892,1)}->[/Table/100/"2ab8e983":v-7] [w]/Table/100/"2ab8e983":1668847865.823418091,1->v-7 [rs]/Table/100/"{2ba47ac0"-c7658174"}:{0:[1668847865.823418091,0, <max>), gap:[<min>, 1668847865.588834720,0),[1668847865.588834720,0, 1668847865.588834720,1),[1668847865.795713494,0, <max>),[1668847865.793293449,0, 1668847865.795713494,0),[1668847865.680153892,1, 1668847865.743831142,0),[1668847865.603420672,1, 1668847865.680153892,1)}->[/Table/100/"9c5374b1":v-8]
        Error types: (1) *withstack.withStack (2) *errutil.leafError
    kvnemesis_test.go:70: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisSingleNode3963958602
--- FAIL: TestKVNemesisSingleNode (1.68s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisSingleNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21628

### LINKED ISSUE #92217: kv/kvnemesis: TestKVNemesisMultiNode failed
kv/kvnemesis.TestKVNemesisMultiNode [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7609211?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7609211?buildTab=artifacts#/) on master @ [cfb5ae9a96e1770daa4aef1615a46e212b561a84](https://github.com/cockroachdb/cockroach/commits/cfb5ae9a96e1770daa4aef1615a46e212b561a84):

```
=== RUN   TestKVNemesisMultiNode
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode645312907
    test_log_scope.go:79: use -show-logs to present logs inline
    kvnemesis_test.go:111: failure:
        committed txn non-atomic timestamps: [rs]/Table/100/"{b38d7244"-da073381"}:{0:[1668936506.781921609,0, 1668936506.953643588,0), gap:[<min>, 1668936506.909974325,0),[1668936506.909974325,0, 1668936506.991405306,1),[1668936506.991405306,1, <max>)}->[/Table/100/"c95dd546":v-0] [s]/Table/100/"{0bc470f4"-7b81b822"}:{gap:[<min>, 1668936506.813832594,1),[1668936506.851002480,0, 1668936506.991405306,0),[1668936506.813832594,1, 1668936506.851002480,0),[1668936506.991405306,0, <max>)}->[] [w]/Table/100/"eac47ae1":missing->v-4 [rs]/Table/100/"{4defe960"-ff5c7a21"}:{0:[0,0, 0,0), 1:[1668936506.781921609,0, 1668936506.953643588,0), gap:[<min>, 1668936506.813832594,0),[1668936506.967173459,0, 1668936506.988982900,0),[1668936506.953643588,0, 1668936506.967173459,0),[1668936506.909974325,2, 1668936506.953643588,0)}->[/Table/100/"eac47ae1":v-5, /Table/100/"c95dd546":v-0] [d]/Table/100/"57a6bff9":1668936506.945266659,1-><nil> [w]/Table/100/"eac47ae1":1668936506.945266659,1->v-5
        (1) attached stack trace
          -- stack trace:
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.(*validator).checkAtomicCommitted
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:845
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.(*validator).checkAtomic
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:600
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.(*validator).processOp
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:569
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.Validate
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/validator.go:72
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.RunNemesis
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis.go:99
          | github.com/cockroachdb/cockroach/pkg/kv/kvnemesis.TestKVNemesisMultiNode
          | 	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:107
          | testing.tRunner
          | 	GOROOT/src/testing/testing.go:1446
          | runtime.goexit
          | 	GOROOT/src/runtime/asm_amd64.s:1594
        Wraps: (2) committed txn non-atomic timestamps: [rs]/Table/100/"{b38d7244"-da073381"}:{0:[1668936506.781921609,0, 1668936506.953643588,0), gap:[<min>, 1668936506.909974325,0),[1668936506.909974325,0, 1668936506.991405306,1),[1668936506.991405306,1, <max>)}->[/Table/100/"c95dd546":v-0] [s]/Table/100/"{0bc470f4"-7b81b822"}:{gap:[<min>, 1668936506.813832594,1),[1668936506.851002480,0, 1668936506.991405306,0),[1668936506.813832594,1, 1668936506.851002480,0),[1668936506.991405306,0, <max>)}->[] [w]/Table/100/"eac47ae1":missing->v-4 [rs]/Table/100/"{4defe960"-ff5c7a21"}:{0:[0,0, 0,0), 1:[1668936506.781921609,0, 1668936506.953643588,0), gap:[<min>, 1668936506.813832594,0),[1668936506.967173459,0, 1668936506.988982900,0),[1668936506.953643588,0, 1668936506.967173459,0),[1668936506.909974325,2, 1668936506.953643588,0)}->[/Table/100/"eac47ae1":v-5, /Table/100/"c95dd546":v-0] [d]/Table/100/"57a6bff9":1668936506.945266659,1-><nil> [w]/Table/100/"eac47ae1":1668936506.945266659,1->v-5
        Error types: (1) *withstack.withStack (2) *errutil.leafError
    kvnemesis_test.go:113: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode645312907
--- FAIL: TestKVNemesisMultiNode (1.59s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisMultiNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21652

### PR DESCRIPTION
**Pull request by arulajmani**
A read only request scans the lock table before it can proceed with dropping latches. It can only evaluate if no conflicting intents are found. While doing so, it also determines if the MVCC scan evaluation needs to consult intent history (by using the interleaved iterator).

The MVCC scan evaluation needs to consult intent history if we discover an intent by the transaction performing the read operation at a higher sequence number or a higher timestamp. The correct sequence numbers to compare here are those on the `BatchRequest`, and not on the transaction. Before this patch, we were using the sequence number on the transaction, which could lead us to wrongly conclude that the use of an intent interleaving iterator wasn't required.

Specifically, if the batch of the following construction was retried on the server:

```
b.Scan(a, e)
b.Put(b, "value")
```

The scan would end up (erroneously) reading "value" at key b.

As part of this patch, I've also renamed `ScanConflictingIntents` to `ScanConflictingIntentsForDroppingLatchesEarly` -- the function isn't as generalized as the old name would suggest.

Closes #92217
Closes #92189

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten turns out this only happens when we're doing server side retries -- so the hypothesis in https://github.com/cockroachdb/cockroach/issues/92189#issuecomment-1332369899 about why the transaction's sequence number is 2 doesn't quite hold. I'll run this through the debugger and try and figure out what's going on there.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93175#-:-NIi9CfsC0Kkf7dQIpSm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/storage/engine.go` line 1687 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93175#-NIi8GokBTRlWvxv1jCh:-NIi8GokBTRlWvxv1jCi:bvee34g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2d37c8c5dcc86650301687a8b61c4676a527c7b/pkg/storage/engine.go#L1687)):*
> ```Go
> // `txn` at the supplied `ts` are ignored.
> //
> // The caller must supply the sequence number of the batch request on behalf of
> ```

"the request", not "the batch request", that's what was getting us in trouble.
___
*[`pkg/storage/engine.go` line 1698 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93175#-NIi8hyMBKTUfmk10ng5:-NIi8hyMBKTUfmk10ng6:biq0fcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2d37c8c5dcc86650301687a8b61c4676a527c7b/pkg/storage/engine.go#L1698)):*
> ```Go
> 	ctx context.Context,
> 	reader Reader,
> 	txn *roachpb.Transaction,
> ```

To make this kind of mistake harder to make, should we switch to passing the `txnID uuid.UUID`? We can compare against `uuid.Nil` for the non-txn case.

**Review by arulajmani — COMMENTED** [review]
Like we spoke about offline, I think I was too quick to dismiss the hypothesis in the comment linked above; it turns, out that was indeed why we were seeing sequence number 2 the second time around, when the batch was retried. I mistakenly convinced myself that this was happening on a server side retry, because that's what I expected to happen given our construction, but I was missing [the splitting](https://github.com/cockroachdb/cockroach/blob/a9fcbd15b24bcf09e139785921be8d9ff8cad729/pkg/roachpb/batch.go#L663-L667)  that happens in the `DistSender` to decompose the batch into 2. Given this was the issue, I added the lines to reset the Sequence on the transaction before returning it in the batch response, like we spoke about earlier today. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93175#-:-NIk4NpX5edvCtEhvqKh:b-6fq41h)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/storage/engine.go` line 1698 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93175#-NIi8hyMBKTUfmk10ng5:-NIjlFgP5ZM8wzoIZwWk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2d37c8c5dcc86650301687a8b61c4676a527c7b/pkg/storage/engine.go#L1698)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To make this kind of mistake harder to make, should we switch to passing the `txnID uuid.UUID`? We can compare against `uuid.Nil` for the non-txn case.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93175#-:-NImJOuA2Il55Wq7qOgb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by nvanbenschoten** [comment]
> I also had to revert the reset Sequence on the transaction change -- turns out, we actually rely on this behaviour to ascertain if the transaction has performed any writes or not in the TxnCoordSender.

This feels potentially buggy to me. There's no guarantee that the coordinator received a response from a write request. I think we'd want to replace the `tc.mu.txn.Sequence != 0` with `tc.interceptorAlloc.txnPipeliner.hasAcquiredLocks()` like we have in `TxnCoordSender.Send`.

**Comment by arulajmani** [comment]
> This feels potentially buggy to me. There's no guarantee that the coordinator received a response from a write request. I think we'd want to replace the tc.mu.txn.Sequence != 0 with tc.interceptorAlloc.txnPipeliner.hasAcquiredLocks() like we have in TxnCoordSender.Send.

Yeah, this didn't seem great, given how we're relying on command evaluation to have written to this field and then making inferences up here. I'll file an issue about this and address it in a quick patch. 


bors r=nvanbenschoten

**Pull request merged**
