### PR TITLE
workload/tpcc: avoid validating foreign keys after dataset generation

### PR DESCRIPTION
**Pull request by nvb**
Foreign key validation was adding a significant amount of time to the initialization of TPC-C. This was especially true on very large datasets. This commit uses the new (as of #38663) ability to create Foreign Key constraints in the `Unvalidated` state using the `NOT VALID` syntax to avoid this extra work.

This will work with old versions of CockroachDB as well because the `NOT VALID` syntax has been around for a very long time, it was just ignored up until #38663.

Release note: None

### CODE REVIEW

**Review by danhhz — APPROVED** [review]

**Comment by nvanbenschoten** [comment]
bors r=danhhz

**Comment by danhhz** [comment]
Follow up Q: my mental model of this is that after fixtures import finishes, normal INSERT/UPDATE/DELETES writes to these tables still get FK checks. it's only the data in the table at the time of FK addition that doesn't get checked. is that right?

**Comment by lucy-zhang** [comment]
@danhhz yes, that's correct

**Comment by danhhz** [comment]
Perfect!

**Pull request merged**
