### PR TITLE
gossip: propagate most-distant markers on every connection

### LINKED ISSUE #30895: teamcity: failed test: TestNetworkReachesEquilibrium
The following tests appear to have failed on release-2.1 (testrace): TestNetworkReachesEquilibrium

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestNetworkReachesEquilibrium).

[#939288](https://teamcity.cockroachdb.com/viewLog.html?buildId=939288):

```
TestNetworkReachesEquilibrium
...ve active connection, skipping
I181002 19:05:07.036082 1433 gossip/gossip.go:1458  [n20] starting client to distant node 22 (8 > 5) to tighten network graph
I181002 19:05:07.042571 28979 gossip/client.go:134  [n7] closing client to node 16 (127.13.128.206:32897): received forward from node 16 to 9 (127.13.128.206:41539); already have active connection, skipping
I181002 19:05:07.049628 28952 gossip/client.go:129  [n20] started gossip client to 127.13.128.206:41555
I181002 19:05:07.062286 1411 gossip/gossip.go:1458  [n12] starting client to distant node 22 (7 > 5) to tighten network graph
I181002 19:05:07.064068 28999 gossip/client.go:129  [n12] started gossip client to 127.13.128.206:41555
I181002 19:05:07.119250 28966 gossip/server.go:276  [n22] refusing gossip from node 20 (max 3 conns); forwarding to 21 ({tcp 127.13.128.206:37987})
I181002 19:05:07.144648 29002 gossip/server.go:276  [n22] refusing gossip from node 12 (max 3 conns); forwarding to 19 ({tcp 127.13.128.206:46541})
I181002 19:05:07.249997 1353 gossip/gossip.go:1458  [n7] starting client to distant node 16 (6 > 5) to tighten network graph
I181002 19:05:07.277898 28968 gossip/client.go:129  [n7] started gossip client to 127.13.128.206:32897
I181002 19:05:07.304954 28971 gossip/server.go:276  [n16] refusing gossip from node 7 (max 3 conns); forwarding to 2 ({tcp 127.13.128.206:35865})
I181002 19:05:07.333170 28952 gossip/client.go:134  [n20] closing client to node 22 (127.13.128.206:41555): received forward from node 22 to 21 (127.13.128.206:37987)
I181002 19:05:07.393167 28999 gossip/client.go:134  [n12] closing client to node 22 (127.13.128.206:41555): received forward from node 22 to 19 (127.13.128.206:46541); already have active connection, skipping
I181002 19:05:07.416627 28929 gossip/client.go:129  [n20] started gossip client to 127.13.128.206:37987
I181002 19:05:07.575279 1411 gossip/gossip.go:1458  [n12] starting client to distant node 22 (7 > 5) to tighten network graph
I181002 19:05:07.578298 28955 gossip/client.go:129  [n12] started gossip client to 127.13.128.206:41555
I181002 19:05:07.618598 29012 gossip/server.go:276  [n22] refusing gossip from node 12 (max 3 conns); forwarding to 21 ({tcp 127.13.128.206:37987})
I181002 19:05:07.619651 28968 gossip/client.go:134  [n7] closing client to node 16 (127.13.128.206:32897): received forward from node 16 to 2 (127.13.128.206:35865); already have active connection, skipping
I181002 19:05:07.791738 1180 gossip/convergence_test.go:114  cycle: 200, cyclesWithoutChange: 0, fullyConnected: true
I181002 19:05:07.793745 28955 gossip/client.go:134  [n12] closing client to node 22 (127.13.128.206:41555): received forward from node 22 to 21 (127.13.128.206:37987); already have active connection, skipping
I181002 19:05:07.893123 1353 gossip/gossip.go:1458  [n7] starting client to distant node 16 (6 > 5) to tighten network graph
I181002 19:05:07.909678 28941 gossip/client.go:129  [n7] started gossip client to 127.13.128.206:32897
I181002 19:05:07.949019 29006 gossip/server.go:276  [n16] refusing gossip from node 7 (max 3 conns); forwarding to 18 ({tcp 127.13.128.206:44219})
I181002 19:05:08.050410 1411 gossip/gossip.go:1458  [n12] starting client to distant node 22 (7 > 5) to tighten network graph
I181002 19:05:08.084893 28911 gossip/client.go:129  [n12] started gossip client to 127.13.128.206:41555
I181002 19:05:08.144549 29014 gossip/server.go:276  [n22] refusing gossip from node 12 (max 3 conns); forwarding to 1 ({tcp 127.13.128.206:42069})
I181002 19:05:08.183692 28941 gossip/client.go:134  [n7] closing client to node 16 (127.13.128.206:32897): received forward from node 16 to 18 (127.13.128.206:44219); already have active connection, skipping
I181002 19:05:08.426119 1353 gossip/gossip.go:1458  [n7] starting client to distant node 16 (6 > 5) to tighten network graph


main.main()



***** Text was not loaded fully because its' size exceeds 2 MB, see full log for the whole text *****





```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by petermattis**
Whenever a gossip connection is created, propagate the most-distant
marker infos (i.e. `node:<id>` infos) to the remote node. These infos
are used for the `mostDistant` calculation and need to accurately
reflect the number of hops to a node.

Note that this is a bandaid. Using the info hops value to calculate the
distance to a node does not work correctly unless infos are always
propagated. The high water stamps mechanism that avoids sending an info
that the remote already has can allow the info hops value to remain
higher or lower than the actual value. Consider the following gossip
network:

```
  1 -> 2
  1 -> 3
  2 -> 3
  3 -> 4
```

When n1 gossips its `node:1` info it has multiple paths to get to n4. We
can either see `1 -> 2 -> 3 -> 4` or `1 -> 3 -> 4`. Depending on the
path the hops value will differ and the path is timing dependent. Even
worse, consider what happens when the network changes. For example,
start with the network `1 -> 2 -> 3 -> 4`. The network then changes to:

```
  1 -> 3
  2 -> 3
  3 -> 4
```

The `node:<id>` keys have a TTL of 2h. In the initial configuration, n2
is considered to be 1 hop distant from n1. But after the
reconfiguration, n2 is in reality 2 hops distant from n1, yet the
`node:2` key living on n1 will not have been updated because it hasn't
changed and the new hops value is higher. The new `gossip-clients:*`
keys give us a way out of this complexity as each node can compute the
shortest path to every other node, but those keys are not generated by
v2.0.x of CockroachDB so we'll have to wait to use them for that
purpose.

Fixes #30895

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@spencerkimball PTAL at my description of the problem with using the hops value for distance calculation. Perhaps I'm misunderstanding something about the way the `mostDistant` calculation is supposed to work and how infos are intended to propagate in the cluster.

**Review by spencerkimball — APPROVED** [review]
Is there any issue to track for when this gets cleaned up?

**Review by petermattis — COMMENTED** [review]
> Is there any issue to track for when this gets cleaned up?

Nope. I'll create one. Does that imply you don't see a way to fix this with the "hops" value?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-:-LOAknH5BBv11PJPaonN:bq4lvom)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/gossip/client.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LO9mSDoecqm94-we1j8-r2-181:-LOAjkt83zKYkXM_ZXmp:b-91pskb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18a4bce9e77bf022529039f672be2e9203ee881/pkg/gossip/client.go#L181)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Do you need to check `firstReq` here? Seems like it either added something to delta or not. Seems preferable to maintain old behavior of not sending an empty delta. 
</blockquote></details>

No, it isn't necessary. Removed.
___
*[pkg/gossip/client.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LO9mSDoecqm94-we1j8-r2-307:-LOAk3u12VzvZPP2fWYz:bwjjm3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18a4bce9e77bf022529039f672be2e9203ee881/pkg/gossip/client.go#L307)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Did you intend to keep this change?
</blockquote></details>

Nope. It was part of some debugging code. Reverted.
___
*[pkg/gossip/client.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LO9mSDoecqm94-we1j8-r2-347:-LOAkLUI6_SBBgrfwcha:bidk03l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18a4bce9e77bf022529039f672be2e9203ee881/pkg/gossip/client.go#L347)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

It would be good to specify the version at which this is true. 
</blockquote></details>

Done (I'm planning to backport this to 2.1).
___
*[pkg/gossip/infostore.go, line 436 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LO9mSDoecqm94-we1jC-r2-436:-LOAkkQ7DzvG4D3l_iEX:b-w4ayg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18a4bce9e77bf022529039f672be2e9203ee881/pkg/gossip/infostore.go#L436)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Do we really want to call these “sentinels”? That word has another important meaning in gossip. It’s confusing. How about “markers”?
</blockquote></details>

`markers` works for me. Changed.

**Review by a-robinson — DISMISSED** [review]
:lgtm: 

As you call out in #31049, this is gonna be overly optimistic, but I definitely agree that's better than the current mixture of overly optimistic and overly pessimistic.

> Reviewed 4 of 4 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-:-LOJJIgS8l36ZCbP54za:bij9xbe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/gossip/client.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LOJHYB-B5pgS7XxQeFl:-LOJHYB-B5pgS7XxQeFm:bb76mu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a2303ea3e3f140d2ece3f7bde8c405037a610f/pkg/gossip/client.go#L341)):*
> ```Go
> 	})
> 
> 	// We attempt to defer registration of the callback until we've heard a
> ```

Why?
___
*[pkg/gossip/gossip_test.go, line 454 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LOJI1RCA3a1_adeU8-3:-LOJI1RCA3a1_adeU8-4:bmbkwlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a2303ea3e3f140d2ece3f7bde8c405037a610f/pkg/gossip/gossip_test.go#L454)):*
> ```Go
> 			})
> 
> 			// Connect the network in a loop. This should halve the
> ```

halve the ?
___
*[pkg/gossip/infostore.go, line 437 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LOJIwsF4FVHVSm1RBGy:-LOJIwsG4rjT9ZlWWRx9:b5ku1b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a31afa61012b44b0521683d22c337d3373970954/pkg/gossip/infostore.go#L437)):*
> ```Go
> // populateMostDistantMarkers adds the node ID infos to the infos map. The node
> // ID infos are used as markers in the mostDistant calculation and need to be
> // propaged regardless of high water stamps.
> ```

s/propaged/propagated

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31042)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/gossip/client.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LOJHYB-B5pgS7XxQeFl:-LOJZ8L4Bc8mA-kSaeak:b-q6asa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a2303ea3e3f140d2ece3f7bde8c405037a610f/pkg/gossip/client.go#L341)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Added another line of commentary. Let me know if it is still unclear. Note that this is for symmetry with the server side which receives the client's high water stamps in the initial request.
___
*[pkg/gossip/gossip_test.go, line 454 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LOJI1RCA3a1_adeU8-3:-LOJZfQO3qfobRgV7gsM:b-t8fyss) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a2303ea3e3f140d2ece3f7bde8c405037a610f/pkg/gossip/gossip_test.go#L454)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

halve the ?
</blockquote></details>

Oops. Fixed.
___
*[pkg/gossip/infostore.go, line 437 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LOJIwsF4FVHVSm1RBGy:-LOJZtlM-Ydn95JAhhdP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a31afa61012b44b0521683d22c337d3373970954/pkg/gossip/infostore.go#L437)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/propaged/propagated
</blockquote></details>

Done.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31042)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/gossip/client.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31042#-LOJHYB-B5pgS7XxQeFl:-LOJbB5CC7pv0DxJP2y5:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/40a2303ea3e3f140d2ece3f7bde8c405037a610f/pkg/gossip/client.go#L341)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Added another line of commentary. Let me know if it is still unclear. Note that this is for symmetry with the server side which receives the client's high water stamps in the initial request.
</blockquote></details>

:thumbsup:

**Comment by petermattis** [comment]
bors r=spencerkimball,a-robinson

**Pull request merged**
