### PR TITLE
Merge nodes and stores pages

### PR DESCRIPTION
**Pull request by maxlang**
- gets rid of the stores page
- merges the node/store status objects
- adds store info on the single node detail page

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4756)

### CODE REVIEW

**Comment by mrtracy** [comment]
As discussed in person, there is little reason to keep any stores page support around at all; for example, you've also "merged" node/store status objects, but that's not necessary to support your current UI; all remaining UI components deals specifically with either NodeStatus or StoreStatus, and none of the components are a target to be made generic (as the table used to be).

---

Reviewed 8 of 12 files at r1.
Review status: 8 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[ui/ts/models/status.ts, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-KBnxjB_Q-UaIzAGd3Ko:-KBnxjBaH5Nj1C6wdVqX:2011197223) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecd7189fc5304a82ae0c61eabd4aea36d410f5b/ui/ts/models/status.ts#L181)):*
This is more than just "Aggregates", it contains all status information used and has a refresh method.

---

*[ui/ts/models/status.ts, line 192 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-KBny_QvLenq9Boz8N5r:-KBny_QvLenq9Boz8N5s:1970400241) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecd7189fc5304a82ae0c61eabd4aea36d410f5b/ui/ts/models/status.ts#L192)):*
Can these be private now?

---

*[ui/ts/models/status.ts, line 201 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-KBnxdSzAt8vAYAeUGir:-KBnxdSzAt8vAYAeUGis:-1652306249) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecd7189fc5304a82ae0c61eabd4aea36d410f5b/ui/ts/models/status.ts#L201)):*
Why does this need to be in any particular order?

---

*[ui/ts/pages/nodes.ts, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-KBnygM-SrN4ryt9Ea3g:-KBnygM-SrN4ryt9Ea3h:-1914707370) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecd7189fc5304a82ae0c61eabd4aea36d410f5b/ui/ts/pages/nodes.ts#L101)):*
Are you actually putting StoreStatus objects into this?  I think this should still be of NodeStatus.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-:-KBo-Ho_torSwqbTo-Nq:-1008173459)*

**Comment by mrtracy** [comment]
Reviewed 4 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756)*

**Comment by maxlang** [comment]
I scaled back some parts of the change, but we do still use StoreStatus on the individual NodePage.

---

Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[ui/ts/pages/nodes.ts, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-KBnygM-SrN4ryt9Ea3g:-KBo943ehB_kubfK3QZ_:1392607023) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecd7189fc5304a82ae0c61eabd4aea36d410f5b/ui/ts/pages/nodes.ts#L101)):*
Ok, not anymore.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-:-KBo9G3quReLIsvXABxx:620321095)*

**Comment by mrtracy** [comment]
LGTM

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4756#-:-KBsTsXnSzrn01I9iPWx:676834233)*

**Pull request merged**
