### PR TITLE
roach{test,prod},acceptance: no longer rely on auto-init

### PR DESCRIPTION
**Pull request by irfansharif**
`cockroach start` without `--join` auto-initializes the cluster. This
was deprecated in 19.2 and will be removed in a future commit. We update
test code that relies on the previous behavior. To (mostly) retain
existing roachprod behavior, we auto-initialize when `roachprod start`-ing 
n1. We introduce a new `--skip-init` flag for when that is
not desired (for example in roachtests that restart n1, but don't intend
to re-initialize the cluster). Most of the roachtest changes are exactly
to this effect, where tests than invoke `roachprod start` a second time
on n1 are changed to now specify this new `--skip-init` flag.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51329)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51329#-MBy9luD-PRNkz0Dtb4-:-MBy9luE6j56MvTmC2gU:b-goptgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee2ec5ad40f29f068873bd6e2c6b06264166a74/pkg/cmd/roachprod/install/cockroach.go#L304)):*
> ```Go
> 	})
> 
> 	if StartOpts.SkipInit || !bootstrappable {
> ```

I'd prefer it if we could avoid adding a `--skip-init` flag as the introduction of the flag is a change to the roachprod UX. Safer to leave the UX unchanged, which I think is possible. Instead, can we leave a marker file on node 1 once initialization has been performed? We can possibly reuse the `<dir>/settings-initialized` file that already exists that is used to initialize cluster settings only once when the cluster is first bootstrapped.

**Comment by irfansharif** [comment]
> I'd prefer it if we could avoid adding a --skip-init flag as the introduction of the flag is a change to the roachprod UX.

Done. I'd originally added a `cluster-bootstrapped` file doing exactly that, but then thought to expose the --skip-init control to it (but I see now that it's not really necessary, not yet anyway).

**Review by knz — APPROVED** [review]
No other comment than what Peter already said.

**Comment by irfansharif** [comment]
TFTRs! Ended up having to add the new marker file to the version upgrade fixtures given we're not solving it with --skip-init anymore. 

bors r+

**Comment by irfansharif** [comment]
Flaked on #48423, re-running.

**Comment by irfansharif** [comment]
Ugh, cla bot acting up. Retrying.

bors r+

**Review by petermattis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51329#-:-MCCk6Q_ANX93f8y-vlF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51329#-MCCjo1gBeToZIIvfpAh:-MCCjo1gBeToZIIvfpAi:b-iz6c2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7b36fb90ac48b3b78b77e9999a7849ce20c775/pkg/cmd/roachprod/install/cockroach.go#L330)):*
> ```Go
> 
> 		binary := cockroachNodeBinary(c, 1)
> 		path := fmt.Sprintf("%s/%s", c.Impl.NodeDir(c, nodes[i]), "cluster-bootstrapped")
> ```

One bit of fragility here is that wiping node 1 will cause a reinitialization. I wonder if we should pushing the `cluster-bootstrapped` file to all nodes. Perhaps just add a TODO for now as it isn't clear to me if this is worth worrying about.
___
*[pkg/cmd/roachprod/install/cockroach.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51329#-MCCjgVZ0xjJeIwJOAWd:-MCCjgVZ0xjJeIwJOAWe:bvmz6qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7b36fb90ac48b3b78b77e9999a7849ce20c775/pkg/cmd/roachprod/install/cockroach.go#L347)):*
> ```Go
> 
> 	if initOut != "" {
> 		fmt.Println(initOut)
> ```

This block isn't taken if the cluster is already bootstrapped, right?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51329)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis and @tbg)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51329#-MCCjo1gBeToZIIvfpAh:-MCE6tCICjGzqhfvjWX5:b-fxtbmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7b36fb90ac48b3b78b77e9999a7849ce20c775/pkg/cmd/roachprod/install/cockroach.go#L330)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

One bit of fragility here is that wiping node 1 will cause a reinitialization. I wonder if we should pushing the `cluster-bootstrapped` file to all nodes. Perhaps just add a TODO for now as it isn't clear to me if this is worth worrying about.
</blockquote></details>

yea, I'll add the TODO. I did audit through our usage of c.Wipe in roachtests to see if there were any problematic usages, and didn't find any. It helps that any sort of problematic usage will fail loudly with a clear "attempting to initialize a re-initialized cluster" message.
___
*[pkg/cmd/roachprod/install/cockroach.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51329#-MCCjgVZ0xjJeIwJOAWd:-MCE6c6K2GXZPDYZr1GI:btqqu5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7b36fb90ac48b3b78b77e9999a7849ce20c775/pkg/cmd/roachprod/install/cockroach.go#L347)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This block isn't taken if the cluster is already bootstrapped, right?
</blockquote></details>

Correct.

**Pull request merged**
