### PR TITLE
sqlproxy: update shell script

### PR DESCRIPTION
**Pull request by spaskob**
Add support for running a different proxy startup cmd than the default
in the script `cockroach mt start-prxy`.

Release note: none.

### CODE REVIEW

**Review by imjching — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57904#-:-MOXGhC4--920o1sv1bh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57904#-MOXH0ZU8Ssg356AE8oZ:-MOXH0ZU8Ssg356AE8o_:bir8s2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b520a6061ec84ef1f19ede24fa6e93572a70603f/pkg/ccl/sqlproxyccl/run_proxy.sh#L21)):*
> ```Shell
> rm -rf ~/.cockroach-certs cockroach-data
> killall -9 cockroach || true
> killall -9 sqlproxy || true
> ```

It would be nice if we could extract the binary name from the SQLPROXY environment variable, but fine without it too.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57904)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @imjching)

___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57904#-MOXH0ZU8Ssg356AE8oZ:-MOXLJhLEOS7XsUBSGzt:bailkbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b520a6061ec84ef1f19ede24fa6e93572a70603f/pkg/ccl/sqlproxyccl/run_proxy.sh#L21)):*
<details><summary><i>Previously, imjching (Jay Lim) wrote…</i></summary><blockquote>

It would be nice if we could extract the binary name from the SQLPROXY environment variable, but fine without it too.
</blockquote></details>

at some point I will add this

**Comment by spaskob** [comment]
TFTR!

**Pull request merged**
