### PR TITLE
opt: null constraints, IS/IS NOT support

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: remove isDistinctFromOp, isNotDistinctFromOp

IS NOT DISTINCT FROM is an extended version of IS: it is equivalent
whenever IS supports the operands. There is no reason to have two
operators. Similar story for IS DISTINCT FROM and IS NOT.

I am choosing to keep the simpler names isOp and isNotOp because I
can't think of a more confusing phrase than "is not distinct from". We
need to support the syntax, but we don't have to use it in our code.

Release note: None

#### opt: export IndexColumnInfo fields

These are meant to be used by the exported MakeIndexConstraints API.

Release note: None

#### opt: handle comparison ops with NULL

Expressions like a > NULL get converted to NULL during type-checking.
Asserting this in the span generation code, and adding a special case
to handle constant false or NULL expressions to return no spans in
this case.

Release note: None

#### opt: support IS (NOT) and IS (NOT) DISTINCT FROM

We add support for constraints around NULL and IS/IS NOT DISTINCT FROM
and IS NOT/IS DISTINCT FROM.

We take into account whether columns are not-nullable to avoid
unnecessary not-NULL spans on those (it would be correct to assume
everything is nullable; this is just for cosmetic purposes and
consistency with the old code).

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
You'll need to rebase above #20982. If you don't please guide the external contributor to deal with the merge conflict.
LGTM otherwise.

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 429 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20992#-L0uEiGoBRlE152G3EZT:-L0uEiGpiWHcRdhOnVBI:b-jlgprg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f420c45ed2a19d5f043207694ad63b7ebf8a4ac/pkg/sql/opt/index_constraints.go#L429)):*
> ```Go
> 	case eqOp, ltOp, gtOp, leOp, geOp:
> 		if datum == tree.DNull {
> 		}
> ```

panic missing in r3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20992#-:-L0uEToy16juI4770-CG:b-ay0dui)*

**Comment by RaduBerinde** [comment]
Thanks, I'll wait for that to merge.

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20992#-:-L0vhnYXB_20bqcztGiz:bnfp4nl)*

**Comment by knz** [comment]
it's merged, you can go ahead and rebase.

**Comment by RaduBerinde** [comment]
Thanks, done.

**Pull request merged**
