### PR TITLE
kvserver,server: discourage further use of NodeStatusLiveness

### PR DESCRIPTION
**Pull request by irfansharif**
We mark the NodeLivenessStatus proto as deprecated. It's unclear if the
enum was ever well considered. It enumerates across two distinct set of
things: the "membership" status (live/active, decommissioning,
decommissioned), and the node "process" status (live, unavailable,
available). It's possible for two of these "states" to be true,
simultaneously (consider a decommissioned, dead node). It makes for
confusing semantics, and the code attempting to disambiguate across
these states (kvserver.LivenessStatus() for e.g.) seem wholly arbitrary.

It's currently used by the Allocator to detect replicas placed on dead
nodes. But there's no good reason for the "deadness" to be proto-backed.
It should suffice to capture the "membership" status and view of node's
liveness (when was the record last heartbeated) + current time to inform
allocator decisions.

---

This was pulled out of #50329.

Release note: None.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I reviewed this and I have two general remarks:

- you forgot to update the UI sources that refer to the enum entries (there's a few - the failing UI checks in CI will tell you. You can also run `make ui-check` locally I believe)

- I come to this PR with the assumption that "deprecated" things  are also rarely-used or that their remaining uses are planned to change soon to instead use non-deprecated things. Instead in this PR I can see a bunch of uses of the enum values which have various purposes, and for which you do not make a plan/proposal to move them away. So the "deprecation" is non-sensical (or, specifically, it does not *mean* anything - it does not inform the team about what's going to happen next)

This last remark might suggest you're not going about this in the right order. If I were you, I'd have done it the other way around:
1. first have created a tech note or RFC draft that *draws an inventory of existing uses* of the enum, with some (prose) context for each.
2. then, for each existing use, point out which other things could be used instead, or what we'd need to get rid of the liveness value in that case.
3. once we have confidence that we can eliminate or replace all uses (with a sketch of "how"), proceed to issue this deprecation PR
   - however, you'd then augment it with `// TODO` annotations for every existing use, that indicates "the plan" - whether the use will be removed or replaced, and how.

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50478#-:-MAS8iGr0F4zQLzKFuzf:bya2hs6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Yeah, I broadly share Raphael's view that we need a plan here. If there's no time to make a plan I would rather leave this in place for now.

BTW, you can rename the enum to something like `NODESTATUS_DECOMMISSIONING` and there's a gogoproto option to drop the `NodeStatus` prefix in the generated code. That way it won't get in your way any more.

**Review by irfansharif — COMMENTED** [review]
Thank you for your comments, I learned that I went about it incorrectly. I've gone ahead and filed #50707 to outline what I had left implicit in my thinking when sending out this PR. My motivation here originally was to free up usage of the {DECOMMISSIONING,DECOMMISSIONED} symbols to use in #50329. I see that trying to deprecate it (partially) in one go, instead of simply renaming it, was not necessary. Updated this PR to refer to #50707 in outlining future clean up work we could possibly do, and just renaming the existing symbols. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50478#-:-MAm255D4NDY-oZIB-Ik:b3h4mtk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 24 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50478#-:-MAwRVGC-t2LU4jyK6-5:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by irfansharif** [comment]
TFTR!

**Pull request merged**
