### PR TITLE
sql: implement REGIONAL BY ROW logic on CREATE TABLE

### LINKED ISSUE #57672: sql: Implement gateway_region() builtin and utilize on insert into REGIONAL BY ROW tables
Implement a builtin which returns a string which indicates the region of the gateway node, and use it when rows are inserted to REGIONAL BY ROW tables without a crdb_region value specified.

### LINKED ISSUE #58335: sql: Implement CREATE TABLE ... REGIONAL BY ROW
WIP notes:

- Create partitioned table and indexes
- Setup zone configuration
- Setup table descriptor accordingly

### PR DESCRIPTION
**Pull request by otan**
Resolves #58335 
Resolves #57672 

Release note (sql change): Implemented REGIONAL BY ROW logic on create
table. This is gated behind the experimental session variable
`experimental_enable_implicit_column_partitioning`.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Looks really good.  Nice job! :tada: 

Doesn't need to be handled in this PR, but is there a way to make REGIONAL BY ROW not require the session variable (i.e. bypass the session variable check or automatically set it under the covers)?  This would allow us to expose REGIONAL BY ROW directly, and keep PARTITION ALL experimental (added a comment about it below as well.  Might be easy to do in this PR).

> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-:-MR0DdW84q6B9cOVkrlU:bfnl3ky)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0GmBP-HUmZytSYD_Q:-MR0GmBQ05g_Wq_-aBfw:b-x9j98s) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L36)):*
> ```
> LOCALITY REGIONAL BY ROW
> 
> statement error REGIONAL BY ROW on an UNIQUE constraint containing PARTITION BY is not supported
> ```

Nit: We might want to reword this error message.  Would "REGIONAL BY ROW on a table with a UNIQUE constraint containing PARTITION BY is not supported" be more accurate?  Or simply, "REGIONAL BY ROW is not supported on partitioned tables/indexes"?
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0FO8V5YIfUf8L0N86:-MR0FO8W0LEVl1lPu1GM:bgbdub5) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L54)):*
> ```
> ) LOCALITY REGIONAL BY ROW
> 
> # TODO(otan): hide the crdb_region column.
> ```

Nit: What to do here will depend on your decision around Andrei's update to the RFC.  Hiding is one option, and using the AS syntax is the other option.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0G1EX5YS99ron4BFR:-MR0G1EX5YS99ron4BFS:boaov6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L56)):*
> ```
> # TODO(otan): hide the crdb_region column.
> query T
> SELECT create_statement FROM [SHOW CREATE TABLE regional_by_row_table]
> ```

Nit: Once we get this working, can we add a test to ensure that the SHOW CREATE TABLE statement roundtrips?  Maybe a TODO in this PR for that?
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0HfzuCG5sN3ujHW3D:-MR0HfzuCG5sN3ujHW3E:b-bldsvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L128)):*
> ```
> 
> statement ok
> INSERT INTO regional_by_row_table (crdb_region, pk, a, b) VALUES ('ca-central-1', 7, 8, 9)
> ```

Can we add a test where we explicitly call `gateway_region()` too?
___
*[pkg/sql/create_table.go, line 1354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Kq0a9SCJbUfQCurH:-MR0Kq0a9SCJbUfQCurI:b-9jk5wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1354)):*
> ```Go
> 
> 	// Add implied columns under REGIONAL BY ROW.
> 	locality := n.Locality
> ```

Nit: might be nice to pull this out into a separate function in region_util.go.
___
*[pkg/sql/create_table.go, line 1387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Ii-C8z5OKTzsJG6R:-MR0Ii-D9i25xc4jlv9m:bxznqep) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1387)):*
> ```Go
> 					return nil, pgerror.New(
> 						pgcode.FeatureNotSupported,
> 						"REGIONAL BY ROW on an UNIQUE constraint containing PARTITION BY is not supported",
> ```

See comment above on wording here.  Do we lose much detail by combining all of these into a single error message: "REGIONAL BY ROW can not be combined with PARTITION BY" (and down the road, "or PARTITION ALL BY"?
___
*[pkg/sql/create_table.go, line 1417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0N1ycCxfJgVUfrPbo:-MR0N1ycCxfJgVUfrPbp:b1x9q2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1417)):*
> ```Go
> 			Type: &tree.OIDTypeReference{OID: oid},
> 		}
> 		c.Nullable.Nullability = tree.NotNull
> ```

Can you also hide this column?  And add a test case that selects all columns and validates that it doesn't show up?
___
*[pkg/sql/create_table.go, line 1428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0O7Wj2ZaSE0TtG5oF:-MR0O7Wj2ZaSE0TtG5oG:bekb4n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1428)):*
> ```Go
> 		columnDefaultExprs = append(columnDefaultExprs, nil)
> 
> 		// Construct the partitioning for the PARTITION ALL BY we will replace.
> ```

Super Nit: Are we really "replacing" the PARTITION ALL BY?  Or "utilizing" that partitioning?
___
*[pkg/sql/create_table.go, line 1445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0OZS38Jm4eVjnYbv7:-MR0OZS38Jm4eVjnYbv8:b-zhh4zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1445)):*
> ```Go
> 
> 	if n.PartitionByTable != nil && n.PartitionByTable.All {
> 		if !evalCtx.SessionData.ImplicitColumnPartitioningEnabled {
> ```

per the comment above, I'd be in favour of removing this check here an allowing REGIONAL BY ROW table to not have to enable the experimental implicit column partitioning.

If we eventually decide that REGIONAL BY ROW isn't sufficiently baked for 21.1, we can slap the experimental flag back on it (but with a message and flag that pertain directly to REGIONAL BY ROW).
___
*[pkg/sql/region_util.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0zHrt4mpIaTDLMTCQ:-MR0zHrt4mpIaTDLMTCR:bp143np) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/region_util.go#L119)):*
> ```Go
> }
> 
> // zoneConfigFromRegionConfigForIndexPartition generates a desired ZoneConfig based
> ```

Nit: Does it make more sense to call this `zoneConfigFromRegionConfigForPartition` seeing as how the primary key index is really the table?
___
*[pkg/sql/region_util_test.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR10svXB22DzXu5dRDS:-MR10svXB22DzXu5dRDT:b-yrqup5) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/region_util_test.go#L408)):*
> ```Go
> 				SurvivalGoal:  descpb.SurvivalGoal_ZONE_FAILURE,
> 			},
> 			expected: &zonepb.ZoneConfig{
> ```

Is this just checking one of the partition's zone configs?  If so, is there value in checking the others?

**Review by otan — COMMENTED** [review]
de-coupling that is a bit gnarly from a glance, so if we're strong on that let's do it in a separate PR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-:-MR1d9AZ3-lh3sAOat0-:bu35h0f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0HfzuCG5sN3ujHW3D:-MR1N64zET83v4RoOrNh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L128)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can we add a test where we explicitly call `gateway_region()` too?
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Kq0a9SCJbUfQCurH:-MR1N6nO4ipPHEYi83S_:b-cflv19) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1354)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: might be nice to pull this out into a separate function in region_util.go.
</blockquote></details>

There's some stuff in here that messes with local state (n.Defs, columnDefaultExprs) which makes this irritable to pull out. 
___
*[pkg/sql/create_table.go, line 1387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Ii-C8z5OKTzsJG6R:-MR1NNIq0Ki9HOftnc8R:b1uw1u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1387)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

See comment above on wording here.  Do we lose much detail by combining all of these into a single error message: "REGIONAL BY ROW can not be combined with PARTITION BY" (and down the road, "or PARTITION ALL BY"?
</blockquote></details>

I prefer being a bit more explicit since a) we can without much effort and b) the user know wheres to look :P 
___
*[pkg/sql/create_table.go, line 1417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0N1ycCxfJgVUfrPbo:-MR1NW69-G_guTz_Pk7Y:b3sm0vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1417)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can you also hide this column?  And add a test case that selects all columns and validates that it doesn't show up?
</blockquote></details>

Not without additional work which I will define as out of scope for this PR :) 
___
*[pkg/sql/create_table.go, line 1428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0O7Wj2ZaSE0TtG5oF:-MR1NkuY0wY9GYJkQpq9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1428)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Super Nit: Are we really "replacing" the PARTITION ALL BY?  Or "utilizing" that partitioning?
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0OZS38Jm4eVjnYbv7:-MR1NlfhEuLF-k1J9NUQ:bsjz2y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1445)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

per the comment above, I'd be in favour of removing this check here an allowing REGIONAL BY ROW table to not have to enable the experimental implicit column partitioning.

If we eventually decide that REGIONAL BY ROW isn't sufficiently baked for 21.1, we can slap the experimental flag back on it (but with a message and flag that pertain directly to REGIONAL BY ROW).
</blockquote></details>

REGIONAL BY ROW relies on implicit column partitioning, and these checks are pretty deep in here.
I can streamline them out, but I'd also say that's out of scope, and people will be running into the experimental behaviour so I prefer to keep this for now (at least for this PR)
___
*[pkg/sql/region_util_test.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR10svXB22DzXu5dRDS:-MR1O-Zu45pnRARClIMv:bcifpyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/region_util_test.go#L408)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is this just checking one of the partition's zone configs?  If so, is there value in checking the others?
</blockquote></details>

This specifically unit tests for a single partition given a name - checking all of them I think should be the logic test with the appropriate regions set.

**Review by ajstorm — CHANGES_REQUESTED** [review]
All good with another PR.  Can you leave a TODO as breadcrumbs (or open a new issue)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-:-MR275Nh-lQC14bBExY4:bieyww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR27VGj1M81e_04490J:-MR27VGj1M81e_04490K:bba7uhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3518ba307e8a990bdb980c4cd2feaf39083110/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L157)):*
> ```
> query TI
> INSERT INTO regional_by_row_table (crdb_region, pk, a, b) VALUES
> (gateway_region()::crdb_internal_region, 23, 24, 25)
> ```

awesome!
___
*[pkg/sql/create_table.go, line 1354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Kq0a9SCJbUfQCurH:-MR27aSc4M6q1HR6dHyL:bbie857) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1354)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

There's some stuff in here that messes with local state (n.Defs, columnDefaultExprs) which makes this irritable to pull out. 
</blockquote></details>

Was worth a try.  Some of these functions are already way too large for my linkings.
___
*[pkg/sql/create_table.go, line 1387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Ii-C8z5OKTzsJG6R:-MR27pHOC2KnjLacHQe5:b-pp6eto) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1387)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I prefer being a bit more explicit since a) we can without much effort and b) the user know wheres to look :P 
</blockquote></details>

That's fair.  This one in particular I find confusing.  Are we really defining "REGIONAL BY ROW on a UNIQUE constraint"?  Isn't it a REGIONAL BY ROW table with a UNIQUE constraint which contains a PARTITION BY clause?  Or something like that?
___
*[pkg/sql/create_table.go, line 1417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0N1ycCxfJgVUfrPbo:-MR286Lw8FQLPmJBusuu:b4jswab) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1417)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Not without additional work which I will define as out of scope for this PR :) 
</blockquote></details>

I'm starting to get the sense that you get paid on commission ;-).  I'm good with another PR.  Can you leave some breadcrumbs here?
___
*[pkg/sql/create_table.go, line 1445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0OZS38Jm4eVjnYbv7:-MR28NhUE84ICyVJwiIK:b-6jtdcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1445)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

REGIONAL BY ROW relies on implicit column partitioning, and these checks are pretty deep in here.
I can streamline them out, but I'd also say that's out of scope, and people will be running into the experimental behaviour so I prefer to keep this for now (at least for this PR)
</blockquote></details>

You get paid on PRs, I get paid on breadcrumbs :).  Can we add some here?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58987)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR27VGj1M81e_04490J:-MR2w2D86isQSf4vIani:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3518ba307e8a990bdb980c4cd2feaf39083110/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L157)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

awesome!
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Ii-C8z5OKTzsJG6R:-MR2w3N575zfos0VP0_m:burykd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1387)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

That's fair.  This one in particular I find confusing.  Are we really defining "REGIONAL BY ROW on a UNIQUE constraint"?  Isn't it a REGIONAL BY ROW table with a UNIQUE constraint which contains a PARTITION BY clause?  Or something like that?
</blockquote></details>

ive reworded this to be "on a table with a UNIQUE constraint"
___
*[pkg/sql/create_table.go, line 1417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0N1ycCxfJgVUfrPbo:-MR2w9zvEJ-5RIOnfcxi:b7bvfed) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1417)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I'm starting to get the sense that you get paid on commission ;-).  I'm good with another PR.  Can you leave some breadcrumbs here?
</blockquote></details>

I get paid off the highs of rolling in PRs :P yes, thought i did with the line below.
`		// TODO(#multiregion): set the field visibility to be hidden.`
___
*[pkg/sql/create_table.go, line 1445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0OZS38Jm4eVjnYbv7:-MR2wWu71jBkIaEmoWkR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1445)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

You get paid on PRs, I get paid on breadcrumbs :).  Can we add some here?
</blockquote></details>

Done.

**Review by ajstorm — APPROVED** [review]
Merge away....

:lgtm:  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-:-MR54cCp-0Ggb0yISf7l:b5lqg1z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/create_table.go, line 1387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0Ii-C8z5OKTzsJG6R:-MR540vX5F4NzaTVvodd:bob6hyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1387)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ive reworded this to be "on a table with a UNIQUE constraint"
</blockquote></details>

perfect
___
*[pkg/sql/create_table.go, line 1417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58987#-MR0N1ycCxfJgVUfrPbo:-MR54GBvESdwHOp1NX1t:bmqfi56) ([raw file](https://github.com/cockroachdb/cockroach/blob/24bb2434dfe8ac96cae19995f8fd1b23f36b0f1d/pkg/sql/create_table.go#L1417)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I get paid off the highs of rolling in PRs :P yes, thought i did with the line below.
`		// TODO(#multiregion): set the field visibility to be hidden.`
</blockquote></details>

Ahh, didn't see that line in the last review.  

Nit: "field visibility"?  Or "column visibility"?

**Comment by otan** [comment]
bors r=ajstorm

TFTR!

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
love a fresh rebase in the morning

bors r=ajstorm

**Comment by otan** [comment]
i dislike mondays

bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
