### PR TITLE
schemachanger: copy current deprules to release_24_3

### PR DESCRIPTION
**Pull request by annrpom**
With the server version changing soon, we need to copy the current dependency rules for the declarative schema changer to a separate package so they remain static. New rules added to the declarative schema changer will continue to modify the current rules, which now apply to version 25.1.

Epic: None

Release note: None

### CODE REVIEW

**Review by spilchen — CHANGES_REQUESTED** [review]
Thanks for doing this. I need this for my ALTER COLUMN .. ALTER TYPE changes too.

> Reviewed 10 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133452#-:-OA3rXmH-jrVOHeO0cjc:bgb1mpz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/scplan/plan.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133452#-OA3r4Um2tfvWT61IyOg:-OA3r4Um2tfvWT61IyOh:bs0tb0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/794abf043b350759cc4dd51ef44e45f8cdb09b37/pkg/sql/schemachanger/scplan/plan.go#L158)):*
> ```Go
> var rulesForReleases = []rulesForRelease{
> 	{activeVersion: clusterversion.Latest, rulesRegistry: current.GetRegistry()},
> 	{activeVersion: clusterversion.V24_3, rulesRegistry: current.GetRegistry()},
> ```

Should this point to 24.3?



_Suggestion:_
```Go
{activeVersion: clusterversion.V24_3, rulesRegistry: release_24_3.GetRegistry()},
```

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133452)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scplan/plan.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133452#-OA3r4Um2tfvWT61IyOg:-OA3vCGL3dFa1dkQtSRq:bhm0f6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/794abf043b350759cc4dd51ef44e45f8cdb09b37/pkg/sql/schemachanger/scplan/plan.go#L158)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should this point to 24.3?
</blockquote></details>

oopsie yes thank you for the catch

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133452#-:-OA43w7dDACgVdQzmRPa:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by annrpom** [comment]
TFTR! ('-')7

bors r=spilchen

**Pull request merged**
