### PR TITLE
distsql: flow diagram generator

### PR DESCRIPTION
**Pull request by RaduBerinde**
Code to generate a json data describing a diagram of a distributed flow. This
will be used by a javascript that will display the diagram.

This will help during development/debugging. We can eventually allow the debug
endpoint to request diagrams on a running server.

Demo script that consumes this json data here:  https://raduberinde.github.io/test.html  (try to drag stuff around)

CC @irfansharif

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10505)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Gentle ping.

**Comment by irfansharif** [comment]
:lgtm: very cool, thanks for the neat visualization haha. just some minor comments here.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/flow_diagram.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKtVC2QjIsjIcARn2r:-KWKtVC2QjIsjIcARn2s:bbi7pm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L31)):*
> ```Go
> 	// lines produces a title and an arbitrary number of lines that describe a
> 	// "cell" in a diagram node (input sync, processor core, or output router).
> 	lines() (string, []string)
> ```

`(title string, details|info []string)`

---

*[pkg/sql/distsql/flow_diagram.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKttblXvbYqspWfZXD:-KWKttblXvbYqspWfZXE:b-nn12xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L31)):*
> ```Go
> 	// lines produces a title and an arbitrary number of lines that describe a
> 	// "cell" in a diagram node (input sync, processor core, or output router).
> 	lines() (string, []string)
> ```

I don't think `lines` is very descriptive, my first assumption was synonymous to graph edges. maybe `summary` or equivalent?

---

*[pkg/sql/distsql/flow_diagram.go, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKmw7Fj5X338Wuqqfg:-KWKmw7Fj5X338Wuqqfh:b-mowpi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L61)):*
> ```Go
> }
> 
> func (*NoopCoreSpec) lines() (string, []string) {
> ```

interface assertions, `var _ diagramCell = &NoopCoreSpec{}`, here and the remaining specs.

---

*[pkg/sql/distsql/flow_diagram.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKuvZ7M_glJYTcz822:-KWKuvZ7M_glJYTcz823:bfk7mco) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L109)):*
> ```Go
> }
> 
> // TODO(radu): implement node() for other core types.
> ```

`s/node/lines`?

---

*[pkg/sql/distsql/flow_diagram.go, line 135 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKvginsjL-es_DX1Ug:-KWKszsTiOXI7fD5FFt4:b-oqudvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L135)):*
> ```Go
> }
> 
> type cellContents struct {
> ```

i think this should be called `diagramCellContents` or something with a `diagram` prefix.

---

*[pkg/sql/distsql/flow_diagram.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKsW4rrOfX8iGQiRML:-KWKsW4rrOfX8iGQiRMM:b-h4t5bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L137)):*
> ```Go
> type cellContents struct {
> 	Title      string   `json:"title"`
> 	ExtraLines []string `json:"lines"`
> ```

`s/ExtraLines/Lines` or `s/lines/extraLines|extra_lines`

---

*[pkg/sql/distsql/flow_diagram.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKltzb87LUblZrwIhq:-KWKltzb87LUblZrwIhr:bv8msgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L141)):*
> ```Go
> 
> type diagramProcessor struct {
> 	NodeIdx int            `json:"nodeIdx"`
> ```

this is cosmetic also i could be wrong, feel free to ignore, more accustomed to snake casing for non-protobuf generated tags. 

---

*[pkg/sql/distsql/flow_diagram.go, line 170 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKx19k_9-BSkhlgZgu:-KWKx19lBPy5Mt54-Adr:b30vsqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L170)):*
> ```Go
> 	for n := range flows {
> 		for _, p := range flows[n].Processors {
> 			pIdx := len(d.Processors)
> ```

i see how`len(d.Processors)` is an incrementing index per processor but i think it's better to be explicit like in the edge production loop below.

---

*[pkg/sql/distsql/flow_diagram.go, line 172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKruOZFFoRfKt9KMB-:-KWKruOZFFoRfKt9KMB0:b-anseda) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L172)):*
> ```Go
> 			pIdx := len(d.Processors)
> 			proc := diagramProcessor{NodeIdx: n}
> 			proc.Core.Title, proc.Core.ExtraLines = p.Core.GetValue().(diagramCell).lines()
> ```

nice, didn't know you could do this.

---

*[pkg/sql/distsql/flow_diagram.go, line 246 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKqm_kOg8TrSMf2-o6:-KWKqm_l9tgfqQ9H1-1C:b49hufj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L246)):*
> ```Go
> 						SourceOutput: srcOutput,
> 					}
> 					if o.Mailbox != nil && o.Mailbox.SyncResponse {
> ```

i believe `Mailbox` was deprecated, most recent CI tests didn't test this.

---

*[pkg/sql/distsql/flow_diagram_test.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKvHf6QdwrpN_eq08g:-KWKvHf6QdwrpN_eq08h:b-63qhui) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram_test.go#L47)):*
> ```Go
> }
> 
> func TestPlanDiagram(t *testing.T) {
> ```

`s/TestPlanDiagram/TestPlanDiagramScan`?

---

*[pkg/sql/distsql/flow_diagram_test.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKhnDoWhkLIR8k2v12:-KWKhnDoWhkLIR8k2v13:b6x5ykc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram_test.go#L97)):*
> ```Go
> 					Type: OutputRouterSpec_MIRROR,
> 					Streams: []StreamEndpointSpec{
> 						{StreamID: StreamID(2)},
> ```

`{StreamID: 2}` here for consistency, or `{StreamID: StreamID(<>)}` everywhere else.

---

*[pkg/sql/distsql/flow_diagram_test.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKzx3hDzdYX651rfTe:-KWKzx3hDzdYX651rfTf:bhua2ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram_test.go#L114)):*
> ```Go
> 				Output: []OutputRouterSpec{{
> 					Type:    OutputRouterSpec_MIRROR,
> 					Streams: []StreamEndpointSpec{{Mailbox: &MailboxSpec{SyncResponse: true}}},
> ```

ditto, deprecated `MailboxSpec`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-:-KWKzF_iK9UNOwd3ORL0:b-ky3yxm)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/sql/distsql/flow_diagram.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKtVC2QjIsjIcARn2r:-KWLjXvbVRzk4lNDmaJf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L31)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> `(title string, details|info []string)`
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKttblXvbYqspWfZXD:-KWLjYcsTj6uSUQrYNdI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L31)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> I don't think `lines` is very descriptive, my first assumption was synonymous to graph edges. maybe `summary` or equivalent?
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram.go, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKmw7Fj5X338Wuqqfg:-KWLjcqXu2tZkEyyVKsO:b-7e0u4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L61)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> interface assertions, `var _ diagramCell = &NoopCoreSpec{}`, here and the remaining specs.
</details>
It's doesn't help much here where it's obvious (we only have this one function, and the interface is defined in the same place).

---

*[pkg/sql/distsql/flow_diagram.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKuvZ7M_glJYTcz822:-KWLjtl8yhfPGPzZMXyP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L109)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> `s/node/lines`?
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram.go, line 135 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKvginsjL-es_DX1Ug:-KWLk24myURkyh9WA25s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L135)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> i think this should be called `diagramCellContents` or something with a `diagram` prefix.
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKsW4rrOfX8iGQiRML:-KWLkBPD--K7DX_p-8Bv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L137)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> `s/ExtraLines/Lines` or `s/lines/extraLines|extra_lines`
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKltzb87LUblZrwIhq:-KWLkGOqkVCq3P1P8lFy:b-mcv2yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L141)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> this is cosmetic also i could be wrong, feel free to ignore, more accustomed to snake casing for non-protobuf generated tags. 
</details>
I used camelcase in the javascript code as well so this fits better (this defines the json format).

---

*[pkg/sql/distsql/flow_diagram.go, line 170 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKx19k_9-BSkhlgZgu:-KWLlchMnXY96llLlLTa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L170)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> i see how`len(d.Processors)` is an incrementing index per processor but i think it's better to be explicit like in the edge production loop below.
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram.go, line 246 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKqm_kOg8TrSMf2-o6:-KWLlfOG5uCYkRF5XQKj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L246)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> i believe `Mailbox` was deprecated, most recent CI tests didn't test this.
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram_test.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKvHf6QdwrpN_eq08g:-KWLliHCYDp17ZO09efo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram_test.go#L47)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> `s/TestPlanDiagram/TestPlanDiagramScan`?
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram_test.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKhnDoWhkLIR8k2v12:-KWLnE0vHSmIExTjXgp7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram_test.go#L97)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> `{StreamID: 2}` here for consistency, or `{StreamID: StreamID(<>)}` everywhere else.
</details>
Done.

---

*[pkg/sql/distsql/flow_diagram_test.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKzx3hDzdYX651rfTe:-KWLli0vqH5S9WM5Qziw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram_test.go#L114)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> ditto, deprecated `MailboxSpec`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-:-KWLnJeX345P1x9JeIHG:b-814g8k)*

**Comment by irfansharif** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/flow_diagram.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKsW4rrOfX8iGQiRML:-KWLwTiOmNDVI8gSg_cC:b-desybx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L137)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Done.
</details>
we can change this to `Details`, json tag to `details`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsql/flow_diagram.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505#-KWKsW4rrOfX8iGQiRML:-KWPRRnWCy661P5qfQ0O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b326590436d4f498e179a0aca2795cb5e663902/pkg/sql/distsql/flow_diagram.go#L137)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> we can change this to `Details`, json tag to `details`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505)*

**Comment by irfansharif** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10505)*

**Pull request merged**
