### PR TITLE
*,sqlbase,descpb: pull protobufs out of sqlbase

### PR DESCRIPTION
**Pull request by ajwerner**
This commit is part of the process to better abstract descriptors. In this
step the protocol buffers which used to live in sqlbase have been extracted
to a new package `pkg/sql/catalog/descpb`.

Part of this change has required adopting wrappers around descriptors.
This change has proven to be a rather large change and I appologize to the
reviewers but am at a loss on how to split this one up.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
This remains just another step on a longer road. This however is a pretty important one. It lifts the higher-level operations off of the protocol buffer struct onto concrete implementations. I'm not super proud of the code organization at this point but I don't want to make this bigger. There's a bunch of renaming and code movement to follow but this felt like a good stopping point for review.

Thanks again!

**Comment by ajwerner** [comment]
This has an issue related to https://github.com/cockroachdb/cockroach/blob/2dbcc200cd0e12562c494018b3cfe9a4a272252c/pkg/sql/alter_table.go#L284-L293 - namely we end up validating table descriptors when writing them now in some cases and that's causing problems. I'd like to get a feel for the "right" way to solve this. I have a sense of what could work but I'm not sure I'm super pleased with it. 

The problem ends up being pretty deeply nested when setting the zone configs when running the schema change on newly created tables, or so far as I can tell. Maybe just plumbing through that I don't want to validate there is fine but I'd rather find a way to properly inject logic to read from the local collection to find the proper back-references.

**Review by thoszhang — COMMENTED** [review]
LGTM so far, just some preliminary comments

> Reviewed 238 of 450 files at r1, 18 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-:-MDpy8HfBA5AbwskVYqD:b-n986vw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDprCmCEiaJylSlSAdd:-MDprCmCEiaJylSlSAde:b-6pa3rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/ccl/backupccl/manifest_handling.go#L645)):*
> ```Go
> // unwrapDescriptor takes a descriptor retrieved using a transaction and unwraps
> // it into an immutable implementation of ExtendedDescriptorInterface. It ensures that
> // the ModificationTime is set properly.
> ```

What does this comment mean?
___
*[pkg/ccl/backupccl/restore_job.go, line 979 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpxnpP3V5RLG6rLqKN:-MDpxnpP3V5RLG6rLqKO:b5ys57j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041885ff9d03cb92147e6b237ecb93b0e7119ae/pkg/ccl/backupccl/restore_job.go#L979)):*
> ```Go
> 	var databases []*sqlbase.ImmutableDatabaseDescriptor
> 	var tables []*sqlbase.MutableTableDescriptor
> 	var tablesI []sqlbase.TableDescriptorInterface
> ```

What's going on here?
___
*[pkg/sql/catalog/accessors/logical_schema_accessors.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpludD5CJg-AOtBOkT:-MDpludD5CJg-AOtBOkU:bm0ra9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/accessors/logical_schema_accessors.go#L74)):*
> ```Go
> 	if entry, ok := l.vs.GetVirtualSchema(scName); ok {
> 		names := make(tree.TableNames, 0, entry.NumTables())
> 		schemDesc := entry.Desc()
> ```

nit: `schemaDesc`?
___
*[pkg/sql/catalog/catalogkv/catalogkv.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpq7kj6fdmfsFeftVX:-MDpq7kj6fdmfsFeftVY:b3u6ood) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/catalogkv/catalogkv.go#L101)):*
> ```Go
> 
> // unwrapDescriptor takes a descriptor retrieved using a transaction and unwraps
> // it into an immutable implementation of ExtendedDescriptorInterface. It ensures that
> ```

There are some references in the comments to `ExtendedDescriptorInterface` that I think are left over from another change.
___
*[pkg/sql/catalog/descpb/structured.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpqkrB5lDA_XbEt70Y:-MDpqkrB5lDA_XbEt70Z:b8d4aym) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/descpb/structured.go#L267)):*
> ```Go
> var AnonymousTable = tree.TableName{}
> 
> // Adding implements the BaseDescriptorInterface interface.
> ```

This is no longer applicable.
___
*[pkg/sql/catalog/lease/lease.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpijJkBjwjs7-dh_4I:-MDpijJkBjwjs7-dh_4J:b-6ccazq) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/lease/lease.go#L322)):*
> ```Go
> 	var version descpb.DescriptorVersion
> 	for lastCount, r := 0, retry.Start(retryOpts); r.Next(); {
> 		// Get the current version of the descriptor non-transactionally.
> ```

nit: Update this comment
___
*[pkg/sql/sqlbase/structured.go, line 3806 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpxdhH840oqgrw2PJy:-MDpxdhH840oqgrw2PJz:b-1l74iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041885ff9d03cb92147e6b237ecb93b0e7119ae/pkg/sql/sqlbase/structured.go#L3806)):*
> ```Go
> }
> 
> // TableDesc implements the ObjectDescriptor interface.
> ```

While you're at it, this isn't applicable anymore.

**Review by rohany — COMMENTED** [review]
On this topic of not wanting to make all of the immutable table descriptors in processors -- why not just leave them as *descpb.*Descriptor for now?

This PR is also exposing how much random stuff was in sqlbase (protos included) that could be split out and moved into new packages

**Review by ajwerner — COMMENTED** [review]
> On this topic of not wanting to make all of the immutable table descriptors in processors -- why not just leave them as *descpb.*Descriptor for now?

The reason we need them wrapped is because there's code that utilized functionality on the `unwrapped` descriptors, for example `ColumnIdxMap`. Maybe I'm missing something you're saying.

> This PR is also exposing how much random stuff was in sqlbase (protos included) that could be split out and moved into new packages

Yes, very soon. I want to merge this first

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-:-MDrKlYm3BQS5nB-_im9:bx3fhb8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDprCmCEiaJylSlSAdd:-MDr75V-3nawFK5xd9Ns:b-j1s60p) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/ccl/backupccl/manifest_handling.go#L645)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

What does this comment mean?
</blockquote></details>

copy-pasta from `catalogkv`, fixed. Updated with some new concerns due to databases which now have timestamps. 
___
*[pkg/ccl/backupccl/restore_job.go, line 979 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpxnpP3V5RLG6rLqKN:-MDr7AvGA3vm89l_QSUE:b-5ok7nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041885ff9d03cb92147e6b237ecb93b0e7119ae/pkg/ccl/backupccl/restore_job.go#L979)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

What's going on here?
</blockquote></details>

We both want a slice of MutableTableDescriptor and TableDescriptorInterface for various calls below. It's a bit gross but we don't have covariant slices in go :(. One day in the next decade we could write it generically using a type constraint. 

I've mulled some interface of table descriptor slices but am not that eager. Maybe would be better to do the copy in place. 
___
*[pkg/sql/catalog/accessors/logical_schema_accessors.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpludD5CJg-AOtBOkT:-MDrL7pZC27QOwp5qMFk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/accessors/logical_schema_accessors.go#L74)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: `schemaDesc`?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/catalogkv/catalogkv.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpq7kj6fdmfsFeftVX:-MDrMk1t4qtYyTkA5t4V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/catalogkv/catalogkv.go#L101)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

There are some references in the comments to `ExtendedDescriptorInterface` that I think are left over from another change.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/structured.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpqkrB5lDA_XbEt70Y:-MDrM-T9CphbfQbNDS8n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/descpb/structured.go#L267)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This is no longer applicable.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/structured.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDn5wJAXExbsieUrbU5-r2-217:-MDrLPPR3Z_EbarTayNZ:b-a2gx4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041885ff9d03cb92147e6b237ecb93b0e7119ae/pkg/sql/catalog/descpb/structured.go#L217)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Alot of these functions can go into the corresponding descpb/ files right?
</blockquote></details>

Sure, some of them don't need to exist. I'm not *that* bullish on this functionality being here but it's fine. I could see an argument to move them to the "unwrapped" descriptor impl. 

This file is the " I'm not super proud of the code organization at this point but I don't want to make this bigger. " I was talking about. 
___
*[pkg/sql/catalog/lease/lease.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpijJkBjwjs7-dh_4I:-MDrM5j3A1cSbtezSyva:b-xlekk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/lease/lease.go#L322)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: Update this comment
</blockquote></details>

Deleted. I never understood what that meant before... It's the same amount of transactionality now as it was before. 
___
*[pkg/sql/sqlbase/structured.go, line 3806 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpxdhH840oqgrw2PJy:-MDrMTXi2Gvy6Kt2rYlL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041885ff9d03cb92147e6b237ecb93b0e7119ae/pkg/sql/sqlbase/structured.go#L3806)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

While you're at it, this isn't applicable anymore.
</blockquote></details>

Done.

**Review by thoszhang — APPROVED** [review]
LGTM, very minor comments

> Reviewed 182 of 450 files at r1, 1 of 21 files at r2, 50 of 53 files at r3, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-:-MDrl3y_86rE6z1TWqso:b63jeak)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/ccl/backupccl/restore_job.go, line 979 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpxnpP3V5RLG6rLqKN:-MDrYNwZ1plck8p3Vh8n:b-ejz7u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041885ff9d03cb92147e6b237ecb93b0e7119ae/pkg/ccl/backupccl/restore_job.go#L979)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We both want a slice of MutableTableDescriptor and TableDescriptorInterface for various calls below. It's a bit gross but we don't have covariant slices in go :(. One day in the next decade we could write it generically using a type constraint. 

I've mulled some interface of table descriptor slices but am not that eager. Maybe would be better to do the copy in place. 
</blockquote></details>

Makes sense. I think a comment would help (as you have elsewhere).
___
*[pkg/ccl/backupccl/targets.go, line 343 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDr_Nsv4KRTFxkUnjln:-MDr_Nsv4KRTFxkUnjlo:b-jksciu) ([raw file](https://github.com/cockroachdb/cockroach/blob/363f06c4d68b2af42af444c2fdd6247a74c262b4/pkg/ccl/backupccl/targets.go#L343)):*
> ```Go
> 			case sqlbase.TableDescriptorInterface:
> 				// TODO (lucy): The immutable wrapper here can be dispensed with once we
> 				// start using catalog.Descriptor everywhere.
> ```

nit: This TODO can be deleted now.
___
*[pkg/sql/catalog/descpb/structured.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpqkrB5lDA_XbEt70Y:-MDrfXj30f5rSepLfJQo:bb5rqgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/descpb/structured.go#L267)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought `TypeDescriptor` itself no longer implements any of the new descriptor interfaces.
___
*[pkg/sql/sqlbase/database_desc.go, line 100 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDrkyfqAxGHstOuok3F:-MDrkyfqAxGHstOuok3G:b-rqmeaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf16e645840fcb212196d14eea9bfabc3dcffde/pkg/sql/sqlbase/database_desc.go#L100)):*
> ```Go
> }
> 
> // DatabaseDesc implements the ObjectDescriptor interface.
> ```

nit: also update these comments
___
*[pkg/sql/sqlbase/schema_desc.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDrksC01PaLyXo1GSVH:-MDrksC01PaLyXo1GSVI:b-rqmeaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf16e645840fcb212196d14eea9bfabc3dcffde/pkg/sql/sqlbase/schema_desc.go#L134)):*
> ```Go
> }
> 
> // SchemaDesc implements the ObjectDescriptor interface.
> ```

nit: also update these comments

**Review by ajwerner — COMMENTED** [review]
I've done some more renaming and hidden all of the post-deserialization upgrades under some new API. I think it's a good step forward, hope y'all agree. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-:-MDuTTUEAjlSe32Pr-q0:b482wnb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

___
*[pkg/ccl/backupccl/restore_job.go, line 979 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpxnpP3V5RLG6rLqKN:-MDte1yDBywX-AcU4V3d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041885ff9d03cb92147e6b237ecb93b0e7119ae/pkg/ccl/backupccl/restore_job.go#L979)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Makes sense. I think a comment would help (as you have elsewhere).
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/structured.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDpqkrB5lDA_XbEt70Y:-MDtcMZH2Qoy2RUqrzz-:b92jc5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/06e93ef12b28d67f756152b9171b1f78bf929282/pkg/sql/catalog/descpb/structured.go#L267)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I thought `TypeDescriptor` itself no longer implements any of the new descriptor interfaces.
</blockquote></details>

Lifted these up to `sqlbase`
___
*[pkg/sql/sqlbase/database_desc.go, line 100 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDrkyfqAxGHstOuok3F:-MDtcgUG7YK9nAWHOfW-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf16e645840fcb212196d14eea9bfabc3dcffde/pkg/sql/sqlbase/database_desc.go#L100)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: also update these comments
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/schema_desc.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDrksC01PaLyXo1GSVH:-MDuTQqNEVT4MLFNqdzV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf16e645840fcb212196d14eea9bfabc3dcffde/pkg/sql/sqlbase/schema_desc.go#L134)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: also update these comments
</blockquote></details>

Done.

**Review by thoszhang — APPROVED** [review]
> Reviewed 99 of 99 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/ccl/backupccl/targets.go, line 343 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDr_Nsv4KRTFxkUnjln:-MDuUSy0DHFxtvpkaAI0:b-8618j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/363f06c4d68b2af42af444c2fdd6247a74c262b4/pkg/ccl/backupccl/targets.go#L343)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: This TODO can be deleted now.
</blockquote></details>

nit: I think you deleted 1 of 2 instances of this TODO.
___
*[pkg/sql/sqlbase/descriptor.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDuYRIXAlggGhT2_9uc:-MDuYRIXAlggGhT2_9ud:b-mgzbqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf260aacd8d0215d82849385c7fdb5618329480f/pkg/sql/sqlbase/descriptor.go#L137)):*
> ```Go
> 		return t.Table.Dropped()
> 	case *descpb.Descriptor_Type:
> 		return false
> ```

Don't we still need to read the drop state directly from the `descpb.TypeDescriptor`, now that we've gotten rid of the `descpb.TypeDescriptor` methods?
___
*[pkg/sql/sqlbase/structured.go, line 694 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDuSh3HDHu7Mq_ymvxf:-MDuSh3HDHu7Mq_ymvxg:bo3ay19) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf260aacd8d0215d82849385c7fdb5618329480f/pkg/sql/sqlbase/structured.go#L694)):*
> ```Go
> // dropped and any of the indexes on the table have deprecated foreign key
> // representations.
> func TableHasDeprecatedForeignKeyRepresenation(desc *descpb.TableDescriptor) bool {
> ```

nit: `Representation`

**Review by rohany — APPROVED** [review]
We can examine the fallout after it merges. I imagine that we'll want to take a look at some profiles after this and see if there were a noticeable amount of extra allocations added by the unwrapping of descriptors where we need them

**Review by ajwerner — COMMENTED** [review]
I feel like there will be some but not a ton because we're not cloning the whole thing. Either way, we'll address that this month. 

Thank you all for the reviews. When I get a green build I'm going to bors it. Might take a couple of attempts but it'll get there. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-:-MDu_oacEu0gfAQAsI-J:b7cdrot)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

___
*[pkg/sql/sqlbase/descriptor.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDuYRIXAlggGhT2_9uc:-MDu_ler2OE_z5p3q756:b3ph5it) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf260aacd8d0215d82849385c7fdb5618329480f/pkg/sql/sqlbase/descriptor.go#L137)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Don't we still need to read the drop state directly from the `descpb.TypeDescriptor`, now that we've gotten rid of the `descpb.TypeDescriptor` methods?
</blockquote></details>

Yes, reverted.
___
*[pkg/sql/sqlbase/structured.go, line 694 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDuSh3HDHu7Mq_ymvxf:-MDu_jnl-MSMyKriF1bW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf260aacd8d0215d82849385c7fdb5618329480f/pkg/sql/sqlbase/structured.go#L694)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: `Representation`
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

___
*[pkg/ccl/backupccl/targets.go, line 343 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52238#-MDr_Nsv4KRTFxkUnjln:-MDucEDY1thOXJqx_a_4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/363f06c4d68b2af42af444c2fdd6247a74c262b4/pkg/ccl/backupccl/targets.go#L343)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: I think you deleted 1 of 2 instances of this TODO.
</blockquote></details>

Done.

**Comment by rohany** [comment]
Rebasing time :scream:

**Pull request merged**
