### PR TITLE
sql: clear zone configs on final DROP REGION of a multi-region database 

### PR DESCRIPTION
**Pull request by otan**
Refs: #61448

See individual commits for details.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62054)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region, line 1272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-MVura3HAf8luiWJjwM2:-MVura3HAf8luiWJjwM3:bg32m5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/25c207bd4410162f7692f69589bf36aba7d41eb7/pkg/ccl/logictestccl/testdata/logic_test/multi_region#L1272)):*
> ```
>                num_replicas = 3,
>                constraints = '[]',
>                lease_preferences = '[]'
> ```

Nit: Does it make sense to add a test here which modifies one of the non-MR fields (to combine the tests in the first commit, with the ones here?)
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-MVusPfl174r2ZseW_Lr:-MVusPfl174r2ZseW_Ls:b-9ej3xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/25c207bd4410162f7692f69589bf36aba7d41eb7/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L220)):*
> ```
> ----
> RANGE default  ALTER RANGE default CONFIGURE ZONE USING
>                range_min_bytes = 134217728,
> ```

Is this what we want here?  Looks like you're just dropping the ZC on drop region?  Shouldn't we preserve the previously set non-MR fields?
___
*[pkg/sql/region_util.go, line 651 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-MVuvwJz87xQgjFJfWBZ:-MVuvwJz87xQgjFJfWB_:b-93wh4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/25c207bd4410162f7692f69589bf36aba7d41eb7/pkg/sql/region_util.go#L651)):*
> ```Go
> 	// This will correctly drop the zone config in applyZoneConfigForMultiRegionDatabase
> 	// if there are no non-multi-region zone config fields set.
> 	mergeZoneConfig := zonepb.NewZoneConfig()
> ```

This looks like it should work down here, so I'm a bit confused by the results above.

**Review by ajstorm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62054)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/region_util.go, line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-MVv7wBM7cnsn8HyBGzP:-MVv7wBM7cnsn8HyBGzQ:b-lofkhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/25c207bd4410162f7692f69589bf36aba7d41eb7/pkg/sql/region_util.go#L652)):*
> ```Go
> 	// if there are no non-multi-region zone config fields set.
> 	mergeZoneConfig := zonepb.NewZoneConfig()
> 	mergeZoneConfig.NumReplicas = proto.Int32(0)
> ```

You win this time, nerd snipper.  Remove this line and you're golden.  It's a _bit_ strange that if num_replicas is set, we'll revert it to the default on the last drop, but that's probably acceptable since you'll need to force that anyway.  Might be worth validating this with a test.

_This message was brought to you by the GoLand debugger._

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62054)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region, line 1272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-MVura3HAf8luiWJjwM2:-MVxJv-19p4ABMKB0Ydp:bbejka7) ([raw file](https://github.com/cockroachdb/cockroach/blob/25c207bd4410162f7692f69589bf36aba7d41eb7/pkg/ccl/logictestccl/testdata/logic_test/multi_region#L1272)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Does it make sense to add a test here which modifies one of the non-MR fields (to combine the tests in the first commit, with the ones here?)
</blockquote></details>

seems like you already have this! 
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-MVusPfl174r2ZseW_Lr:-MVxJt3E8PJTuBvAeLtM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25c207bd4410162f7692f69589bf36aba7d41eb7/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L220)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Is this what we want here?  Looks like you're just dropping the ZC on drop region?  Shouldn't we preserve the previously set non-MR fields?
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-MVv7wBM7cnsn8HyBGzP:-MVxK3p19lZ9sJV5RsJV:bjrs97i) ([raw file](https://github.com/cockroachdb/cockroach/blob/25c207bd4410162f7692f69589bf36aba7d41eb7/pkg/sql/region_util.go#L652)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

You win this time, nerd snipper.  Remove this line and you're golden.  It's a _bit_ strange that if num_replicas is set, we'll revert it to the default on the last drop, but that's probably acceptable since you'll need to force that anyway.  Might be worth validating this with a test.

_This message was brought to you by the GoLand debugger._
</blockquote></details>

hahaha, a bit more subtle - i had to introduce a delete. but this looks good and expected now.

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62054#-:-MVxt1ve2fEiPS2KOHPt:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
