### PR TITLE
jobs: use system.jobs instead of SHOW JOBS to poll jobs

### PR DESCRIPTION
**Pull request by rafiss**
Previously, the jobs registry would check for unfinished jobs using SHOW
JOBS. This causes the crdb_internal.jobs vtable to be materialized,
which loads all rows from system.jobs and deserializes their payloads.

This work can be skipped by requesting individual rows from system.jobs
directly.

In the case of ORM test suites that frequently create and drop tables
repeatedly, populating the crdb_internal.jobs table was using a lot of
memory and time.

Release note: None

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @spaskob)

**Comment by rafiss** [comment]
thanks for the review!

bors r+

**Comment by awoods187** [comment]
Can this be backported to 20.1 and 19.2?

**Comment by lucy-zhang** [comment]
I think we should backport to 20.1. This problem doesn't exist in 19.2.

**Comment by rafiss** [comment]
I've created the backport PR

**Pull request merged**
