### PR TITLE
storageccl: add an Export command

### PR DESCRIPTION
**Pull request by danhhz**
Export dumps the requested keys into files of non-overlapping key ranges
in a format suitable for bulk ingest.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13417)

### CODE REVIEW

**Comment by danhhz** [comment]
@bdarnell This is basically unchanged from what you LGTM'd in the branch, except that it's been renamed from ExportKeys to Export. This is because we intend to use Import for the command that downloads sstables and calls WriteBatch. And Load for a user bringing in their existing postgres (or other external) data. In the RFC, these are currently called Export, Ingest, and Import, respectively. The non-parallelism of what Export and Import did was bugging me.

Happy to bikeshed this naming. Once it's all signed off on, I'll update the RFC with whatever we settle on.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOT5xKJhCKMQvBJdSk:-KcOT5xLp89aPAqoVsjK:b-moj1hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L31)):*
> ```Go
> 
> func init() {
> 	storage.SetExportCmd(storage.Command{Eval: evalExportKeys})
> ```

This needs a `DeclareKeys` field now.

---

*[pkg/ccl/storageccl/export.go, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOT9CSZeweCIgBRyAs:-KcOT9CSZeweCIgBRyAt:b-57upoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L36)):*
> ```Go
> // evalExportKeys dumps the requested keys into files of non-overlapping key
> // ranges in a format suitable for bulk ingest.
> func evalExportKeys(
> ```

Rename this to `evalExport` to match the new name.

---

*[pkg/ccl/storageccl/export.go, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOTyqrvmpBp766LX_G:-KcOTyqrvmpBp766LX_H:b-v5c1f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L39)):*
> ```Go
> 	ctx context.Context, batch engine.ReadWriter, cArgs storage.CommandArgs, resp roachpb.Response,
> ) (pd storage.EvalResult, retErr error) {
> 	// Don't bother doing anything if the context is cancelled.
> ```

We shouldn't be checking this in individual commands - we should be bailing out of read commands before evaluating them. I think we're already doing that in storage.beginCmds.

---

*[pkg/ccl/storageccl/export.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOVgrrYgcdoNoCn8kj:-KcOVgrrYgcdoNoCn8kk:b-cu7z2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L137)):*
> ```Go
> 	sst = nil
> 
> 	crc := crc32.New(crc32.MakeTable(crc32.Castagnoli))
> ```

crc32 is a really weak checksum; there's no reason to use anything less than sha256 for a file-level checksum. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-:-KcOboyzgnVCv0yJn74P:bnfp4nl)*

**Comment by danhhz** [comment]
Review status: 7 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ccl/storageccl/export.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOT5xKJhCKMQvBJdSk:-KcPTJbNxczuclNws8hW:b-o3nw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L31)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This needs a `DeclareKeys` field now.
</blockquote></details>

Done. DefaultDeclareKeys seems sufficient?

---

*[pkg/ccl/storageccl/export.go, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOT9CSZeweCIgBRyAs:-KcPTNopCgvP4boTQWfQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L36)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Rename this to `evalExport` to match the new name.
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/export.go, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOTyqrvmpBp766LX_G:-KcPTSumPdFZghk8L9E-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L39)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We shouldn't be checking this in individual commands - we should be bailing out of read commands before evaluating them. I think we're already doing that in storage.beginCmds.
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/export.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOVgrrYgcdoNoCn8kj:-KcPTTWd4NvV0J1I-E6d:b8itpg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L137)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

crc32 is a really weak checksum; there's no reason to use anything less than sha256 for a file-level checksum. 
</blockquote></details>

Fair point. I was planning on crc32c and/or md5 because the cloud providers compute it for you and I was originally thinking of it as a basic check that the files referenced in the BackupDescriptor haven't been changed in the interim.

But I guess if we think AddFile (or something like it) is ever on the table, then we'll want to checksum the actual downloaded bytes. Plus, I expect computing a checksum is not the bottleneck of anything we're doing on Import.

Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417)*

**Comment by bdarnell** [comment]
Review status: 7 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/export.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOVgrrYgcdoNoCn8kj:-KcPZfxGs13kTiXT5W9a:bcm62qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L137)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Fair point. I was planning on crc32c and/or md5 because the cloud providers compute it for you and I was originally thinking of it as a basic check that the files referenced in the BackupDescriptor haven't been changed in the interim.

But I guess if we think AddFile (or something like it) is ever on the table, then we'll want to checksum the actual downloaded bytes. Plus, I expect computing a checksum is not the bottleneck of anything we're doing on Import.

Thoughts?
</blockquote></details>

I know S3 does md5; do they do crc32 too? If that's the goal then we might want to compute a bunch of hashes and save them all. But I'm not sure it's worth it; we can compute the hashes easily enough when we need them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417)*

**Comment by danhhz** [comment]
Review status: 7 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ccl/storageccl/export.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417#-KcOVgrrYgcdoNoCn8kj:-KcPa6znjYjhNWuhGDSb:b8t7z26) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f61bf19f37b1aa91e655ef9170c9ec9b3c6a362/pkg/ccl/storageccl/export.go#L137)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I know S3 does md5; do they do crc32 too? If that's the goal then we might want to compute a bunch of hashes and save them all. But I'm not sure it's worth it; we can compute the hashes easily enough when we need them.
</blockquote></details>

S3 and Azure do md5. GCS does crc32c.

There's a little more thinking to be done here, but I don't have time to do it this second. I'd like to get this commit in to unblock the 2tb acceptance test work, so pulled this question out into an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13417)*

**Comment by danhhz** [comment]
Thanks, Ben!

**Pull request merged**
