### PR TITLE
RFCs: add resumability proposal to backup/restore RFC

### PR DESCRIPTION
**Pull request by benesch**
Also update the RFC for implementation divergence while I'm here.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/RFCS/backup_restore.md, line 241 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-KnG7joLcOocfiSQNjm_:-KnG7joLcOocfiSQNjma:btniihf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L241)):*
> ```Markdown
>   // Nanoseconds since the Unix epoch.
>   optional int64 expiration_time = 2 [(gogoproto.nullable) = false];
> }
> ```

Half-formed thought: could the job lease be based on node liveness in a similar manner to the way epoch-based range leases are? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633)*

**Comment by danhhz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/backup_restore.md, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_0vbc1hN6WbI34HvA:-Kn_0vbc1hN6WbI34HvB:b-u4jx2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L16)):*
> ```Markdown
> # Motivation
> 
> Any durable datastore is expected to have the ability to save a snapphot of data
> ```

snapshot

---

*[docs/RFCS/backup_restore.md, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_1dvMjRV6VQiTu4CW:-Kn_1dvMjRV6VQiTu4CX:bd6oko6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L66)):*
> ```Markdown
> providers will be included, as will local files (for testing and nfs mounts).
> 
> Using sstables as the storage format allows us to use RocksDB's [AddFile]
> ```

We have to rekey, so it doesn't matter if the backup uses sstables or not. 

The real reason we use sstables is so we can eventually implement read only queries over backups in an efficient-ish way

---

*[docs/RFCS/backup_restore.md, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_2U2W--Yer5n_clBI:-Kn_2U2W--Yer5n_clBJ:b-5rl4ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L98)):*
> ```Markdown
> The RocksDB snapshot is iterated and for each key the latest MVCC entry before
> the end time is streamed to the backup's configured basepath. The iteration must
> either go through the Store at the right level for the Store's read/push/resolve
> ```

we were in fact able to use the store loop

---

*[docs/RFCS/backup_restore.md, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_2WBYJMShQdhO4ojQ:-Kn_2WBYJMShQdhO4ojR:b-z8pzzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L99)):*
> ```Markdown
> the end time is streamed to the backup's configured basepath. The iteration must
> either go through the Store at the right level for the Store's read/push/resolve
> loop to take effect or implement such a loop itself. A running hash of key and
> ```

we ended up hashing the whole file, not just the keys and values

---

*[docs/RFCS/backup_restore.md, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_2DeyRCmsBFAVMenT:-Kn_2DeyRCmsBFAVMenU:b-27vl63) ([raw file](https://github.com/cockroachdb/cockroach/blob/56530adc4c6a3c54a2ec72f468a0cbe2a3267033/docs/RFCS/backup_restore.md#L103)):*
> ```Markdown
> 
> The RocksDB snapshot is iterated and for each key the latest MVCC entry before
> the end time is streamed to the backup's configured basepath. Or, if the backup
> ```

Keep this, we still might do it

---

*[docs/RFCS/backup_restore.md, line 155 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_3APSbfWxGrCqjJKL:-Kn_3APSbfWxGrCqjJKM:bflxca2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L155)):*
> ```Markdown
> corresponding segment data. The replica streams in the data, merging full and
> incremental backups as appropriate, and rewrites keys with the new table ID.
> These are applied in batches using the proposer evaluated kv `MVCCPut` command.
> ```

WriteBatch or AddSSTable

---

*[docs/RFCS/backup_restore.md, line 157 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_3ppkcKSTu2cgfHi4:-Kn_3ppkcKSTu2cgfHi5:btslkte) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L157)):*
> ```Markdown
> These are applied in batches using the proposer evaluated kv `MVCCPut` command.
> The data checksums are matched before committing. The `system.descriptor` entry
> is written for the table and a temporary name is given to the table in
> ```

we don't do this extra temp name step. we just write the two descriptors at the end

---

*[docs/RFCS/backup_restore.md, line 162 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_3Y8-LnsffVIdU3Ur:-Kn_3Y8-LnsffVIdU3Us:b6cxqok) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L162)):*
> ```Markdown
> An alternate, much faster method that doesn't send the data bytes through raft,
> and thus avoids the write amplification, is described in the [Bulk
> Import RFC](https://github.com/cockroachdb/cockroach/pull/15895).
> ```

you probably want https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/raft_sstable_sideloading.md. it does sent bytes through raft, but doesn't store them in the normal raft log (which saves us write amplification)

---

*[docs/RFCS/backup_restore.md, line 241 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-KnG7joLcOocfiSQNjm_:-Kn_TCdwL1dFHzGZhvRO:b-2tzcug) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L241)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Half-formed thought: could the job lease be based on node liveness in a similar manner to the way epoch-based range leases are? 
</blockquote></details>

Good idea. Let's flesh this out

---

*[docs/RFCS/backup_restore.md, line 283 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_5SdPvgh_gP03QpAN:-Kn_5SdPvgh_gP03QpAO:baj3kmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L283)):*
> ```Markdown
> 
> The naïve implementation of restore progress would keep track of every completed
> `Import`. The space requirements of this approach are unfortunate: O(n)
> ```

nit: worst-case space requirements

---

*[docs/RFCS/backup_restore.md, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_TX4PqfmBEqVZTrhi:-Kn_TX4PqfmBEqVZTrhj:bqlcvqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L369)):*
> ```Markdown
> ```
> 
> Only `FlushFile` will guarantee that the data has been persisted to remote
> ```

As discussed offline, let's just write out the whole file periodically for now. That can be done without any ExportStorage additions (and the future maintenance that causes as we add new ones)

---

*[docs/RFCS/backup_restore.md, line 398 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_Tn1kop0s4GviCBOX:-Kn_Tn1kop0s4GviCBOY:b2tx9a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L398)):*
> ```Markdown
> format](https://github.com/facebook/rocksdb/blob/v4.9/db/write_batch.cc#L10-L30)
> instead of sstables as the storage format. As mentioned above, sstables are
> preferable since they enable the use faster [AddFile] method.
> ```

ditto above. this is not true and also not why we use sstables

---

*[docs/RFCS/backup_restore.md, line 425 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_U3o5ddDgOQMSPogt:-Kn_U3o5ddDgOQMSPogu:bwudkm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L425)):*
> ```Markdown
> Secondary indexes are derivable from the primary data, so we could skip backing
> them up to save space. Recomputing them on restore will probably make it too
> slow. Bulk load, however, will generate any secondary indexes.
> ```

bulk load will work the same as restore (the data will contain precomputed secondary indexes)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633)*

**Comment by benesch** [comment]
RFAL! Updated with epoch-based leasing.

---

Review status: 0 of 1 files reviewed at latest revision, 13 unresolved discussions.

---

*[docs/RFCS/backup_restore.md, line 241 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-KnG7joLcOocfiSQNjm_:-Kneor3WSzSeRoDgeKQF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L241)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Good idea. Let's flesh this out
</blockquote></details>

Done.

---

*[docs/RFCS/backup_restore.md, line 283 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_5SdPvgh_gP03QpAN:-KnenANIQuZxk9cqCIji:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L283)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: worst-case space requirements
</blockquote></details>

Done.

---

*[docs/RFCS/backup_restore.md, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Kn_TX4PqfmBEqVZTrhi:-KnenScVAAt7iGVQhsPA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8deed9a37327a74b28b315e53d2277daf7e9cdd3/docs/RFCS/backup_restore.md#L369)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

As discussed offline, let's just write out the whole file periodically for now. That can be done without any ExportStorage additions (and the future maintenance that causes as we add new ones)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-:-KnepIsueZSLpS7Y6P9j:b-4zpy9y)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/backup_restore.md, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Koi8TEm8jYyTOHU_4TP:-Koi8TEm8jYyTOHU_4TQ:b-92bcys) ([raw file](https://github.com/cockroachdb/cockroach/blob/095b4705a75799d1d1171eabeb9a4b080f246c93/docs/RFCS/backup_restore.md#L273)):*
> ```Markdown
> which can use the secondary index on `status, created`, then decodes the
> `payload`, which contains the `JobLease`. The daemon will attempt to adopt the
> first job (i.e., the oldest job) whose lease have expired by writing a new
> ```

nit: "whose lease have"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-:-Koi9TlnWtufz6OgYtOz:bnfp4nl)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-:-KoiE_rA0OF1scmwLJaL:bnfp4nl)*

**Comment by benesch** [comment]
Does this need to go through final comment period?

---

Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/RFCS/backup_restore.md, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-Koi8TEm8jYyTOHU_4TP:-Kolm4ShDd-f1AfVYlO4:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/095b4705a75799d1d1171eabeb9a4b080f246c93/docs/RFCS/backup_restore.md#L273)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: "whose lease have"
</blockquote></details>

Thanks, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-:-Kolm5r_fm-NBDvv4YiF:b-gqf1et)*

**Comment by danhhz** [comment]
Probably not necessary, but may as well anyway. Maybe someone will suggest something radically better than we we've come up with. I also think it's fine to optimistically start on the impl now

---

Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16633#-:-KolzI82khdZA9GyobQo:b-iffmep)*

**Comment by benesch** [comment]
Entering final comment period.

**Pull request merged**
