### PR TITLE
sql: Secondary Region Followup

### LINKED ISSUE #68358: Replication Feature Request: Up-replication to non preferred localities after preferred region failure and fail-back
**Is your feature request related to a problem? Please describe.**
Problem: Add non preferred localities to be added to preferred localities as standby for up replication without user interaction with zone configuration changes

**Describe the solution you'd like**

Setup a Cluster with 5 primary regions to store data ranges and standby regions without data ranges only meta, liveness ranges.   When a primary region is down for more than "dead node time", cluster will start to replicate data ranges to standby regions to resolve under replication when one or more nodes are down in a preferred locality.   As preferred nodes resume, data ranges are replicated back and the standby localities data ranges are marked for deletion.   Today, this can be achieved with zone config commands and customer prefers this process to be automated.   This works partially today if a region fails, introducing new nodes in the region or in another new locality will up-replicate returning the cluster to full set of replicas.   When the failed nodes resume, replicas are rebalanced but not returned to the original states.  using Zone Config constraints to set replication preferences will not allow up-relocation to a locality not contained in the zone configuration.  

**Describe alternatives you've considered**
Using Script to monitor health of nodes, zone config commands can be submitted to change replication behavior across preferred and non preferred localites.

**Additional context**

Cluster start with 4 regions, east1-b,east4-b,west1-b,west2-b 
image

2 hours later west2b is shutdown and system is under replicated.  added west3 nodes to cluster and the system begins to up-replicate 

image

image

2.5 hours to up replicate 

image

West2 is brought back online and replicas are resumed in west2

image

setting configs such as

image

will not allow for up-replication to any newly added regions for data ranges without zone config commands

Epic CRDB-2521

Jira issue: CRDB-9001

### PR DESCRIPTION
**Pull request by e-mbrown**
Resolves #68358

For 22.2 we've decided that secondary and super regions should have
minimal interaction. Secondary regions are tied to the primary region,
both wither have to be outside of inside of a super region. In the case
of multiple super regions, the primary and secondary region must be within
the same super region.

Release note (sql change): Secondary regions, like the primary regions can
either be set inside or outside of a super region. In order to move a
secondary region `alter_primary_region_super_region_override` must be enabled
and the primary region moved.

Release justification: Low-risk update to new functionality

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
The `IF EXISTS` change feels like it ought to be at least a separate commit if not a separate PR. 

> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-:-N8QWwohC6yHVtPzJNNI:bx66xnu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @RichardJCai)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QTOY92w8aDgmkjnLa):*
nit: `s/wither/either/`, also maybe the `of` should be an `or`? Can you rework this sentence?
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QU9CM4PstRQx-SRZQ):*
do you want to add a note about `IF EXISTS` support?
___
*[`pkg/sql/alter_database.go` line 1371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QTeAh6c163WjO4j3q:-N8QTeAh6c163WjO4j3r:b-80grcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1371)):*
> ```Go
> 	}
> 
> 	//Check secondary region
> ```

nit: sentence
___
*[`pkg/sql/alter_database.go` line 1384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QW32lBWz0ISkyOPLD:-N8QW32lBWz0ISkyOPLE:b-gke7k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1384)):*
> ```Go
> 
> 			regions := tree.NameList(n.n.Regions).NameToRegionName()
> 			err := validateSecondaryRegion(regionConfig, regionConfig.SecondaryRegion(), regions)
> ```

how come we don't just always want to pass in the region list? Does it hurt to pass it in?

I'm thinking this could just be:

how about:

```go
// Only validate against the region list if it contains the primary region.
if err := validateSecondaryRegion(
    regionConfig, regionConfig.SecondaryRegion(), nameToRegionNames(n.n.Regions),
); err != nil {
    return err
}
```
___
*[`pkg/sql/alter_database.go` line 1611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QUjiC3DVA9h9vB7qr:-N8QUjiC3DVA9h9vB7qs:bn6pfxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1611)):*
> ```Go
> 	}
> 
> 	//Iterate over new regions and make sure the secondary and primary ar inside or outside?
> ```

nit: rework this to be clearer, consider explaining what you mean by inside or outside. 
___
*[`pkg/sql/alter_database.go` line 1622 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QUsF6DbTzolRF5EFh:-N8QUsF6DbTzolRF5EFi:b-dkkrip) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1622)):*
> ```Go
> 	}
> 
> 	// Check that the secondary region isn't being dropped
> ```

nit: period at the end of the sentence.
___
*[`pkg/sql/alter_database.go` line 1631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QWGGuEahlR6vQcv0z:-N8QWGGuEahlR6vQcv1-:b-974wve) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1631)):*
> ```Go
> 
> 	if regionConfig.SecondaryRegion() != catpb.RegionName(tree.SecondaryRegionNotSpecifiedName) {
> 		primaryInSuperRegion := regionConfig.IsMemberOfExplicitSuperRegion(regionConfig.PrimaryRegion())
> ```

can you help me understand why we need to check this condition and why it's wrong to pass regions if this is not true?
___
*[`pkg/sql/alter_database.go` line 1815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QWQ7Q80QjfPICasRr:-N8QWQ7Q80QjfPICasRs:boo263m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1815)):*
> ```Go
> 			return err
> 		}
> 	}
> ```

Can you explain what this code is doing in commentary? I don't get it. 



_Code quote:_
```Go
	regions, err := prevRegionConfig.GetSuperRegionRegionsForRegion(prevRegionConfig.PrimaryRegion())
	if err != nil {
		err = validateSecondaryRegion(prevRegionConfig, catpb.RegionName(n.n.SecondaryRegion), nil)
		if err != nil {
			return err
		}
	} else {
		err = validateSecondaryRegion(prevRegionConfig, catpb.RegionName(n.n.SecondaryRegion), regions)
		if err != nil {
			return err
		}
	}
```
___
*[`pkg/sql/alter_database.go` line 1989 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QWY5z3OR0-WkW4KqJ:-N8QWY6-ENBK-VRRPTw3:bs3isa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1989)):*
> ```Go
> ) error {
> 
> 	if regions != nil {
> ```

The structure of the code here where you have a bunch of code above this which has to do work to decide whether or not to set the `regions` parameter followed by the conditional in here to look at whether it's set is a code smell. May I request that you take another pass at making the concepts at the call sites and this helper clearer in terms of what it's validating. It might be that you need to helper functions. It might be that you need some other mechanism to express the intended state. 
___
*[`pkg/sql/sem/tree/name_part.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QTtql4aKmpkKQj73z:-N8QTtql4aKmpkKQj74-:b-dg1h2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/sem/tree/name_part.go#L132)):*
> ```Go
> }
> 
> // NameToRegionName returns a slice of region names.
> ```

`catpb` and `tree` are mutually not allowed to import each other. Just make the helper which takes `[]Name` and gives you back what you want in the `sql` package. 



_Code quote:_
```Go
// NameToRegionName returns a slice of region names.
func (l NameList) NameToRegionName() []catpb.RegionName {
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/secondary_region` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QX2J7E0m06KXDz1f6:-N8QX2J7E0m06KXDz1f7:bzb4rwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/ccl/logictestccl/testdata/logic_test/secondary_region#L370)):*
> ```
> 
> statement ok
> ALTER DATABASE db DROP SECONDARY REGION IF EXISTS
> ```

can you add testing for the notice? 



_Code quote:_
```
statement ok
ALTER DATABASE db DROP SECONDARY REGION IF EXISTS
```

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @RichardJCai)

___
*[`pkg/sql/alter_database.go` line 1989 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QWY5z3OR0-WkW4KqJ:-N8UXOgr7PAFIbYr-brK:b-3v3any) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/alter_database.go#L1989)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The structure of the code here where you have a bunch of code above this which has to do work to decide whether or not to set the `regions` parameter followed by the conditional in here to look at whether it's set is a code smell. May I request that you take another pass at making the concepts at the call sites and this helper clearer in terms of what it's validating. It might be that you need to helper functions. It might be that you need some other mechanism to express the intended state. 
</blockquote></details>

I see what you mean. I'll give it another go
___
*[`pkg/sql/sem/tree/name_part.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QTtql4aKmpkKQj73z:-N8UXbmy95ltMNlBU_56:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/sql/sem/tree/name_part.go#L132)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`catpb` and `tree` are mutually not allowed to import each other. Just make the helper which takes `[]Name` and gives you back what you want in the `sql` package. 
</blockquote></details>

Done.

**Comment by e-mbrown** [comment]
Friendly ping 

@ajwerner could you take another look, when you have the time.

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @RichardJCai)

___
*[`pkg/sql/alter_database.go` line 1371 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97D9hQCj_MXgzk-BOD:-N97D9hQCj_MXgzk-BOE:bfmx2g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1371)):*
> ```Go
> 	}
> 
> 	// Check if the primary and secondary regions are members of this super region
> ```

nit: add period 
___
*[`pkg/sql/alter_database.go` line 1379 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97DSJh9-dVEj9QgfEO:-N97DSJh9-dVEj9QgfEP:biibn54) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1379)):*
> ```Go
> 	}
> 
> 	if regionConfig.SecondaryRegion() != catpb.RegionName(tree.SecondaryRegionNotSpecifiedName) {
> ```

Does `regionConfig.HasSecondaryRegion` work here?
___
*[`pkg/sql/alter_database.go` line 1383 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97DcHMDf9WHL5beARg:-N97DcHMDf9WHL5beARh:b-ydl4de) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1383)):*
> ```Go
> 		primaryInSuper := tree.NameList(n.n.Regions).Contains(tree.Name(primaryRegion))
> 		regions := nameToRegionName(n.n.Regions)
> 		err := validateSecondaryRegion(regionConfig, regionConfig.SecondaryRegion(), regions, primaryInSuper)
> ```

Can we do the 
```
	primaryRegion := regionConfig.PrimaryRegionString()
		primaryInSuper := tree.NameList(n.n.Regions).Contains(tree.Name(primaryRegion))
```
from within 

`validateSecondaryRegion`

We're passing the `regionConfig` and `regions` in so we can and this check is specific to secondaryregions.
___
*[`pkg/sql/alter_database.go` line 1620 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97DsQ48rdEe3OxxnjO:-N97DsQ48rdEe3OxxnjP:bza1q1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1620)):*
> ```Go
> 	}
> 
> 	if regionConfig.SecondaryRegion() != catpb.RegionName(tree.SecondaryRegionNotSpecifiedName) {
> ```

ditto, replace with `regionConfig.HasSecondaryRegion`
___
*[`pkg/sql/alter_database.go` line 1621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97E1sc50ZYhXVVc-YS:-N97E1sc50ZYhXVVc-YT:b-yhwvnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1621)):*
> ```Go
> 
> 	if regionConfig.SecondaryRegion() != catpb.RegionName(tree.SecondaryRegionNotSpecifiedName) {
> 		primaryInSuper := tree.NameList(n.n.Regions).Contains(tree.Name(regionConfig.PrimaryRegion()))
> ```

Let's delegate doing this into `validateSecondaryRegion`?
___
*[`pkg/sql/alter_database.go` line 1789 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97EIP50IRaJTHD0n90:-N97EIP50IRaJTHD0n91:b-r7frst) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1789)):*
> ```Go
> 	regions, err := prevRegionConfig.GetSuperRegionRegionsForRegion(prevRegionConfig.PrimaryRegion())
> 	if err != nil {
> 		if prevRegionConfig.IsMemberOfExplicitSuperRegion(catpb.RegionName(n.n.SecondaryRegion)) {
> ```

I'm a bit lost here, if the`err != nil` why don't we return the err here?
And then do the validation afterwards.
___
*[`pkg/sql/alter_database.go` line 1969 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97EXoQ0p9Qf6s9O9TP:-N97EXoQ0p9Qf6s9O9TQ:b-bn85e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1969)):*
> ```Go
> 
> 	secondaryInCurrSuper := false
> 	for _, region := range regions {
> ```

Can also do the primary region check here

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @RichardJCai)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/secondary_region` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N8QX2J7E0m06KXDz1f6:-N8deMLeDTkvoITGXSjk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b166b879ba6895a2abdaa0cbd30a7ced2f3aae53/pkg/ccl/logictestccl/testdata/logic_test/secondary_region#L370)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you add testing for the notice? 
</blockquote></details>

Done.
___
*[`pkg/sql/alter_database.go` line 1379 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97DSJh9-dVEj9QgfEO:-N9CN0477cG67om7q6Hp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1379)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Does `regionConfig.HasSecondaryRegion` work here?
</blockquote></details>

Done.
___
*[`pkg/sql/alter_database.go` line 1383 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97DcHMDf9WHL5beARg:-N9CPvY1C4FP5zn_oJW4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1383)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Can we do the 
```
	primaryRegion := regionConfig.PrimaryRegionString()
		primaryInSuper := tree.NameList(n.n.Regions).Contains(tree.Name(primaryRegion))
```
from within 

`validateSecondaryRegion`

We're passing the `regionConfig` and `regions` in so we can and this check is specific to secondaryregions.
</blockquote></details>

Done.
___
*[`pkg/sql/alter_database.go` line 1620 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97DsQ48rdEe3OxxnjO:-N9CPvw845NohWCFUgTe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1620)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

ditto, replace with `regionConfig.HasSecondaryRegion`
</blockquote></details>

Done.
___
*[`pkg/sql/alter_database.go` line 1621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97E1sc50ZYhXVVc-YS:-N9CS8NBAz_ujoncOX1I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1621)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Let's delegate doing this into `validateSecondaryRegion`?
</blockquote></details>

Done.
___
*[`pkg/sql/alter_database.go` line 1789 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97EIP50IRaJTHD0n90:-N9CSFWw7x0eIx-I6OGw:bdw29jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1789)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I'm a bit lost here, if the`err != nil` why don't we return the err here?
And then do the validation afterwards.
</blockquote></details>

Wouldn't that be confusing? The error would tell the user that the primary region isn't in a super region, which isnt actually a problem.
___
*[`pkg/sql/alter_database.go` line 1969 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N97EXoQ0p9Qf6s9O9TP:-N9CSV533PbMpiVpW0RK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0200cd761f13d80cc7d8f873c4690ad7153bb1ff/pkg/sql/alter_database.go#L1969)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Can also do the primary region check here
</blockquote></details>

Done.

**Review by RichardJCai — COMMENTED** [review]
Close, one last thing from me

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @RichardJCai)

___
*[`pkg/sql/alter_database.go` line 1790 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N7pnXw5eMKzmxvDLTgL-r6-1790:-N9He0tb50Dc8Awy_0Kz:bhvx665) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03ab8426a2b402da7ba133fa49823da14c211a6/pkg/sql/alter_database.go#L1790)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

maybe we should be more clear in this error message and specify that we're referring to the same super region

Also I think we should use `errors.Wrap` and return the underlying message as well 

</blockquote></details>

`GetSuperRegionRegionForRegion` returns an assertion error, due to the function being used for creating zone configs. Don't think we can return the error and since its used for zone configs we cant change it. I can leave a comment or get the regions another way, though that would involve looping through all super regions on the `regionConfig`.

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @RichardJCai)

___
*[`pkg/sql/alter_database.go` line 1790 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/84999#-N7pnXw5eMKzmxvDLTgL-r6-1790:-N9YeR0m5RIXpSY5Nhoq:brt02cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03ab8426a2b402da7ba133fa49823da14c211a6/pkg/sql/alter_database.go#L1790)):*
<details><summary><i>Previously, e-mbrown (Ebony Brown) wrote…</i></summary><blockquote>

`GetSuperRegionRegionForRegion` returns an assertion error, due to the function being used for creating zone configs. Don't think we can return the error and since its used for zone configs we cant change it. I can leave a comment or get the regions another way, though that would involve looping through all super regions on the `regionConfig`.
</blockquote></details>

I think we can just change it to not be an assertion error or update `GetSuperRegionRegionsForRegion` to return (bool, catpb.RegionNames) with bool indicating whether the primary region is in a super region or not.

**Review by RichardJCai — APPROVED** [review]

**Comment by RichardJCai** [comment]
Thanks for the changes! :lgtm:

**Comment by e-mbrown** [comment]
TFTR bors r+

**Comment by e-mbrown** [comment]
bors r+

TFTR

**Pull request merged**
