### PR TITLE
kv: don't mix prefix and non-prefix iters when collecting intents

### LINKED ISSUE #47219: kv: READ_UNCOMMITTED scan observes WriteIntentError, hits assertion
In https://github.com/cockroachdb/cockroach/pull/47120, we saw instances of the following assertion fire:
https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/kv/kvserver/replica_send.go#L247-L249

At this point in the `executeBatchWithConcurrencyRetries` retry loop, we expect any request that hits a `WriteIntentError` to be holding latches. The assertion was firing because a meta2 scan, which uses the `READ_UNCOMMITTED` read consistency level and therefore [does not acquire latches](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/kv/kvserver/concurrency/concurrency_manager.go#L221-L223), was hitting a `WriteIntentError`. This should not be possible, as the MVCC layer is [extra careful](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/storage/rocksdb.go#L2529) to never return this form of error to inconsistent reads.

Further debugging revealed that the `WriteIntentError` was actually coming from the [`ScanRequest`'s call](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/kv/kvserver/batcheval/cmd_scan.go#L79) into [`CollectIntentRows `](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/kv/kvserver/batcheval/intent.go#L29). `CollectIntentRows` is called to look up the provisional value associated with each intent observed by a `READ_UNCOMMITTED` scan. This is critical to avoid deadlock during range splits, where a range lookup may need to consider a meta2 intent to be the source of truth in terms of range addressing in order to resolve that intent.

It's completely unexpected that `CollectIntentRows` would be returning a `WriteIntentError`, because it uses `MVCCGetAsTxn` to lookup the provisional values of intents that we just saw during the scan. However, in the failure, we saw that the `WriteIntentError` was for a different transaction than the one responsible for the original intent. How could this be? Shouldn't we be working off of a consistent engine snapshot in `MVCCScan`?

Well, no. Read-only requests use a "read-only engine" returned from `Engine.NewReadOnly`. This engine by itself *does not* guarantee a consistent snapshot across all uses. The read-only engine contains two cached iterators, one for normal iteration and one for prefix iteration. Each iterator has an implicit snapshot of the DB, but those can be slightly different snapshots. In this case, the `MVCCScan` used a non-prefix iterator and the `MVCCGetAsTxn` used a prefix iterator. And since the `READ_UNCOMMITTED` scan wasn't holding latches, it had no guarantee of isolation within its keyspan across its two iterators.

So to summarize what happened here:
- a meta2 `READ_UNCOMMITTED` came in and did not acquire latches
- is scanned using a non-prefix iterator and hit an intent
- it passed this intent to `CollectIntentRows`
- this used a different prefix iterator and hit a different intent
- some other write must have slipped in and resolved and replaced the first intent with the second intent between the two iterator creations
- the scan returned a WriteIntentError to the concurrency manager
- the assertion blew up

### PR DESCRIPTION
**Pull request by nvb**
Fixes #47219.

This commit addresses the bug diagnosed and explained in #47219. In that issue, we saw an assertion failure all the way up in the concurrency manager because a `READ_UNCOMMITTED` scan was hitting a `WriteIntentError`, which should not be possible. The root cause of this issue was that `READ_UNCOMMITTED` scans were mixing prefix and non-prefix iterators pulled from a read-only engine between the time that they were collecting intent keys and they were returning to fetch the provisional values for those keys. This mixing of iterators did not guarantee that the two stages of the operation would observe a consistent snapshot of the underlying engine, and because the `READ_UNCOMMITTED` scans also did not acquire latches, writes were able to slip in and change the intent while the scan wasn't looking. This caused the scan to throw a `WriteIntentError` for the new intent transaction, which badly confused other parts of the system (rightfully so).

This commit fixes this issue in a few different ways:
1. it ensures that we always use the same iterator type (prefix or non-prefix) when retrieving the provisional values for a collection of intents retrieved by an earlier scan during `READ_UNCOMMITTED` operations.
2. it adds an assertion inside of `batcheval.CollectIntentRows` that the function never returns a `WriteIntentError`. This would have caught the bug much more easily, especially back before we had the concurrency manager assertion and this bug could have materialized as stuck range lookups and potentially even deadlocked splits due to the dependency cycle between those two operations.
3. it documents the limited guarantees that read-only engines provide with respect to consistent engine snapshots across iterator instances.

We'll want to backport this fix as far back as possible. It won't crash earlier releases of Cockroach, but as stated above, it might cause even more disastrous results. REMINDER: when backporting, remember to change the release note.

Release notes (bug fix): a bug that could cause Cockroach processes to crash due to an assertion failure with the text "expected latches held, found none" has been fixed.

Release justification: fixes a high-priority bug in existing functionality. The bug became louder (now crashes servers) due to recent changes that added new assertions into the code.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
The plumbing of `usePrefixIter` :lgtm:. I'm not familiar with `CollectIntentRows` and its usage, though, so it might be worthwhile for someone else to give this change a look as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-:-M4U675vEwaRGAQat3i8:b-by9s2t)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/kv/kvserver/batcheval/intent.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4U4bWq294svx_fFV53:-M4U4bWq294svx_fFV54:b85dndy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L41)):*
> ```Go
> // TODO(nvanbenschoten): remove the usePrefixIter complexity when we're fully on
> // Pebble and can guarantee that all iterators created from a read-only engine
> // are consistent.
> ```

Note that there is additional work needed in Pebble to make this work. Specifically, we need to add an `Iterator.Clone()` method. Doing so should be straightforward. I mention this only because right now using Pebble would encounter this same problem.

**Review by nvb — COMMENTED** [review]
TFTR! There's no one who is particularly familiar with `CollectIntentRows` because it hasn't been touched in years. 

@irfansharif do you mind giving this a pass as well? There are only three callers of `CollectIntentRows` and only two uses of `roachpb.READ_UNCOMMITTED`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-:-M4Ug79W2FCZbwF2QllK:b-rddjf5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/kv/kvserver/batcheval/intent.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4U4bWq294svx_fFV53:-M4UgHaY02eVO3wuKDWP:b3ons5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L41)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Note that there is additional work needed in Pebble to make this work. Specifically, we need to add an `Iterator.Clone()` method. Doing so should be straightforward. I mention this only because right now using Pebble would encounter this same problem.
</blockquote></details>

Yeah, I mentioned that in the TODO in `engine.go`. It seemed too specific for this TODO though.

**Comment by nvanbenschoten** [comment]
Actually, @irfansharif is on the L2 rotation this week, so he's got a lot of interrupts on his plate already. @ajwerner said he'd take a quick look.

**Comment by irfansharif** [comment]
It was L1, and I just rotated off. Taking a look anyway, curious to learn what you learnt here.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47247)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/kv/kvserver/batcheval/intent.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VCDjwBoYKDRRPg5gh:-M4VCDjxCCzB87DJI2Ae:ba0iqh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L80)):*
> ```Go
> 			return roachpb.KeyValue{}, err
> 		} else if val == nil {
> 			return roachpb.KeyValue{}, errors.Errorf("provisional value for intent %+v not found", intent)
> ```

This seems like a change in behavior. Before it seems like we used to just skip the intent. Is it the case that actually val is never nil and instead val.Value is empty on deletes and you're fixing an old bug? 

Should we add testing for this case? When can it happen?

**Review by irfansharif — APPROVED** [review]
LGTM.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-:-M4VJFjT5Y0VTYKolBuO:b-85i63v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/batcheval/intent.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VHOQi3gxGBL7_j16W:-M4VHOQi3gxGBL7_j16X:b-sf4eiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L79)):*
> ```Go
> 		if err != nil {
> 			return roachpb.KeyValue{}, err
> 		} else if val == nil {
> ```

nit: was clearer without the `else`. Could just be an isolated `if`.
___
*[pkg/kv/kvserver/batcheval/intent.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VCDjwBoYKDRRPg5gh:-M4VH2gh7MVxRYKHrTkQ:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L80)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This seems like a change in behavior. Before it seems like we used to just skip the intent. Is it the case that actually val is never nil and instead val.Value is empty on deletes and you're fixing an old bug? 

Should we add testing for this case? When can it happen? 
</blockquote></details>

Ditto.
___
*[pkg/kv/kvserver/batcheval/intent.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VHv9k5zqBuClsIfBh:-M4VHv9k5zqBuClsIfBi:b-eaf1ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L84)):*
> ```Go
> 		return roachpb.KeyValue{Key: intent.Key, Value: *val}, nil
> 	}
> 	res, err := storage.MVCCScanAsTxn(
> ```

It seems that MVCCScanAsTxn uses the non-prefix iterator. For my own curiosity, where is the code for that? (what I really want to know is the when one is chosen over the other)
___
*[pkg/storage/mvcc.go, line 2547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VFSo-DZNS1TDE55ye:-M4VFSo-DZNS1TDE55yf:bsnod2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/storage/mvcc.go#L2547)):*
> ```Go
> // should rarely be used.
> //
> // The read is carried out without the chance of uncertainty restarts.
> ```

Here and MVCCGetAsTxn, is it worth asserting on this?

**Review by nvb — COMMENTED** [review]
> It was L1, and I just rotated off.

Ah, sorry, I thought you were ahead of me in the KV L2 rotation, so that's where my mind jumped to.

Thanks for the two reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-:-M4VJbQB8suhyW9p2q_Z:b-7ne5de)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @irfansharif, and @petermattis)

___
*[pkg/kv/kvserver/batcheval/intent.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VHOQi3gxGBL7_j16W:-M4VK83w1HvB6YQbHDhU:b-szcx1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L79)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

nit: was clearer without the `else`. Could just be an isolated `if`.
</blockquote></details>

Done here and below.
___
*[pkg/kv/kvserver/batcheval/intent.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VCDjwBoYKDRRPg5gh:-M4VEstW6Z0BDqUkla7D:bubguol) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L80)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

This is a good catch! I was thinking that the previous code was unnecessary because we would never even see a deletion intent in the first place, but that's incorrect. We'll see the intent when scanning non-transactionally, but then we'll get a [nil `roachpb.Value`](https://github.com/cockroachdb/cockroach/blob/3967538f10b8382359d6f12063f9dda6c22f9bb0/pkg/storage/mvcc.go#L732) from `MVCCGet` because we're not scanning for tombstones. I've revived the earlier logic and added tests for all of these cases.
___
*[pkg/kv/kvserver/batcheval/intent.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VHv9k5zqBuClsIfBh:-M4VJo74CPOtTtDYXKz2:b-a8yok6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/kv/kvserver/batcheval/intent.go#L84)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

It seems that MVCCScanAsTxn uses the non-prefix iterator. For my own curiosity, where is the code for that? (what I really want to know is the when one is chosen over the other)
</blockquote></details>

That's right at the top of `MVCCScan` and `MVCCGet`. Notice how the`IterOptions` they provide to `reader.NewIterator` differ.
___
*[pkg/storage/mvcc.go, line 2547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VFSo-DZNS1TDE55ye:-M4VJ_fT3LW6doWJmFhZ:batzmqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2b95290df17ab7fb5957926afc3d1bc3ccfc490/pkg/storage/mvcc.go#L2547)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Here and MVCCGetAsTxn, is it worth asserting on this?
</blockquote></details>

Done at the same place I added the assertion against `WriteIntentErrors`.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-:-M4VLhgH-L5QBYihqgEJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @petermattis)

___
*[pkg/kv/kvserver/batcheval/intent_test.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VLLFi95d958pxGjnU:-M4VLLFi95d958pxGjnV:bb1swx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebf50ff1326cbdb6530336055776c67e8d48e55/pkg/kv/kvserver/batcheval/intent_test.go#L113)):*
> ```Go
> 	for _, c := range testCases {
> 		t.Run(c.name, func(t *testing.T) {
> 			// Test with and without deletion intents. If a READ_UNCOMMITTED request
> ```

These semantics seem potentially surprising and probably deserve to be documented somewhere if they aren't already. Is it correct that if you run a read in `READ_UNCOMMITTED` and there's an uncommitted deletion we'll return the current value? 

This is definitely not for this PR though. Always interesting to learn about the edge cases in the bespoke, rarely used modes like `READ_UNCOMMITTED`

**Review by nvb — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-:-M4VXd_G5c3hV_Rx7yoz:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @petermattis)

___
*[pkg/kv/kvserver/batcheval/intent_test.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47247#-M4VLLFi95d958pxGjnU:-M4VXnuM4xgYS0upxpWt:b-mpi91v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebf50ff1326cbdb6530336055776c67e8d48e55/pkg/kv/kvserver/batcheval/intent_test.go#L113)):*
> These semantics seem potentially surprising and probably deserve to be documented somewhere if they aren't already. Is it correct that if you run a read in READ_UNCOMMITTED and there's an uncommitted deletion we'll return the current value?

Yes, that is true. So we probably should be returning deletion tombstones in the `IntentRows` slice to indicate that the committed value is being deleted. I added a comment to the documentation on these fields.

**Pull request merged**
