### PR TITLE
sql: refactored diff tool strucutres to remove JSON complexity

### PR DESCRIPTION
**Pull request by mnovelodou**
Previously, diff tool shared the same structures for table metadata
and diffs
This was inadequate because they have different concerns
To address this, this patch refactored the code so every concern or
process have their own data types

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70952)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou and @RichardJCai)

___
*[pkg/sql/testdata/postgres_test_expected_diffs_on_pg_catalog.json, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-MlLa0Gw3on4JTbaXm6y:-MlLa0Gw3on4JTbaXm6z:b-mmxdw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c05da639c68c5139d4d4d0672a52d06a5b9532e/pkg/sql/testdata/postgres_test_expected_diffs_on_pg_catalog.json#L8)):*
> ```JSON
>     "MissingTables": 0,
>     "MissingColumns": 0,
>     "DatatypeMismatches": 0
> ```

just curious: when did we resolve these dataTypeMisMatches?

**Review by mnovelodou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70952)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/testdata/postgres_test_expected_diffs_on_pg_catalog.json, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-MlLa0Gw3on4JTbaXm6y:-MlLmHnG4vojL-eQzCLN:b-l0j9cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c05da639c68c5139d4d4d0672a52d06a5b9532e/pkg/sql/testdata/postgres_test_expected_diffs_on_pg_catalog.json#L8)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just curious: when did we resolve these dataTypeMisMatches?
</blockquote></details>

This is a nice catch, if you noticed there are datatype mismatches below, let me check

**Review by RichardJCai — APPROVED** [review]
Mostly LGTM, minor nits. Awesome change though thanks for this.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-:-MlRLqfZ2eUg_f3OiQNL:b-hnqisi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou and @rafiss)

___
*[pkg/sql/pg_metadata_diff.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-MlRLEr81v8m-M_sZm-U:-MlRLEr81v8m-M_sZm-V:b6r8bbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d6305d6f253cbaea79dd21351b5109033f58f2/pkg/sql/pg_metadata_diff.go#L60)):*
> ```Go
> }
> 
> // PGMetadataColumnDiff describes diffs information for a column type. Fields are exported for Marshaling purposes.
> ```

nit: Lower case marshaling
___
*[pkg/sql/pg_metadata_diff.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-MlRLCxQDI3WIJfp3_3s:-MlRLCxQDI3WIJfp3_3t:ba9o2s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d6305d6f253cbaea79dd21351b5109033f58f2/pkg/sql/pg_metadata_diff.go#L71)):*
> ```Go
> type PGMetadataColumnDiffs map[string]*PGMetadataColumnDiff
> 
> // PGMetadataTableDiffs Is used to store and load expected diffs:
> ```

nit: s/Is/is
___
*[pkg/sql/pg_metadata_test.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-MlRLTSAB0y1zSZ7lwsl:-MlRLTSAB0y1zSZ7lwsm:b-bq3axa) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d6305d6f253cbaea79dd21351b5109033f58f2/pkg/sql/pg_metadata_test.go#L95)):*
> ```Go
> // Where to start when debugging?
> // -> func TestDiffTool
> //
> ```

Nice, thanks for this detailed writeup here.
___
*[pkg/sql/pg_metadata_test.go, line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-MlRLgJaCAGl01gUp1gp:-MlRLgJaCAGl01gUp1gq:b5kwf2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d6305d6f253cbaea79dd21351b5109033f58f2/pkg/sql/pg_metadata_test.go#L267)):*
> ```Go
> }
> 
> type DiffTool struct {
> ```

Nit: Maybe we should use a more specific name here, VirtualSchemaDiffTool perhaps?

**Review by mnovelodou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70952)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/pg_metadata_test.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70952#-MlRLTSAB0y1zSZ7lwsl:-MlRTzFp8YsBngL_A7Ds:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d6305d6f253cbaea79dd21351b5109033f58f2/pkg/sql/pg_metadata_test.go#L95)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Nice, thanks for this detailed writeup here.
</blockquote></details>

Done.

**Pull request merged**
