### PR TITLE
docs/RFCs: draft MVCC-ification of bulk operations

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Release justification: none.

### CODE REVIEW

**Comment by dt** [comment]
Did we work out all the comments/questions while this was a pre-RFC doc? anything left to do here?

**Comment by tbg** [comment]
Haven't read this yet, sorry - putting on top of queue for a pass tomorrow
AM

(sent from mobile, please excuse my brevity)

**Comment by dt** [comment]
It currently says explicitly that it is not specifying the design for individual pieces required:
> It describes at a high level the pieces required for this shift and how they fit together to get there, while leaving the actual detailed design specification of each piece to subsequent separate design documents.

I expanded on that a bit in the `Technical Design` header as well, specifying that while there are some hypothetical implementations discussed, it is only explored insofar as to prove the feasibility of those pieces, not to concretely specify their designs.
> Each of these major pieces and how they replace an existing non-MVCC operations is discussed in more detail below. Note however that the below discussions are *not* intended to specify the actual details of the design and implementation of each piece: it is expected that most or all of these pieces will each have a stand-alone RFC specifying their design and implementation. Insofar as the sections below describe implementation details, it is only intended to demonstrate that it is indeed a feasible component to include in this higher level plan.

Other those those bits, it is pretty much just the text of the google doc, with the appendixes on del-range and addsstable removed.

**Review by tbg — APPROVED** [review]

**Comment by dt** [comment]
TFTR! 

Going to merge this as is, since we’ve started breaking individual issues out for roadmaps, and can amend later if we change our minds about any parts.

bors r=tbg

**Pull request merged**
