### PR TITLE
storage,backupccl: add cluster settings for backup-related sst compression

### PR DESCRIPTION
**Pull request by nicktrav**
**storage,backupccl: allow for configuring compression of backup ssts**

Currently, there exists a single cluster setting,
`storage.sstable.compression_algorithm`, that controls the compression
algorithm used by the cluster when writing SSTables. This cluster
setting currently defaults to `snappy`.

There are various end destinations and use cases for SSTables - those
that reside in a Pebble store (the most common), those sent over the
wire via `AddSSTable`, and those generated as part of a backup for
storage in S3/GCS. Each of these destinations and use cases benefit from
being able to independently alter the compression algorithm.

In addition to the existing cluster setting, add two backup-specific
cluster settings:

- `storage.sstable.compression_algorithm_backup_storage`: applies to
  SSTs generated as part of a backup, where SSTs will reside in blob
  storage. These require compression, but not at the cost of additional
  CPU at generation time. Defaults to `snappy`, the existing algorithm
  used.
- `storage.sstable.compression_algorithm_backup_transport`: applies to
  SSTs generated as part of a backup that are sent, immediately
  iterated, and then discarded (i.e. they are never persisted). Such
  SSTs typically have larger block sizes and benefit from compression.
  Defaults to `snappy`, the existing algorithm used.

While this change introduces new cluster settings that allows
independently altering the compression algorithm for different types of
SSTs, the existing compression behavior is unchanged.

Touches https://github.com/cockroachdb/cockroach/issues/123953.

Release note (general change): Adds two new cluster settings,
`storage.sstable.compression_algorithm_backup_storage` and
`storage.sstable.compression_algorithm_backup_transport`, that in
addition to the existing cluster setting
`storage.sstable.compression_algorithm`, can be used to alter the
compression algorithm used for various types of SSTs.

Epic: None.

### CODE REVIEW

**Comment by nicktrav** [comment]
First commit should be the focus of the review.

The second commit just changes a default and updates some tests.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-:-NyV_ul09__kCSQ4FZpN:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @jbowens, and @nicktrav)

___
*[`pkg/storage/pebble.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVZsK49JJQQwOiL2fO:-NyVZsK49JJQQwOiL2fP:b-hx119c) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L125)):*
> ```Go
> // CompressionAlgorithm is an enumeration of available compression algorithms
> // available.
> type CompressionAlgorithm int64
> ```

[nit] Why do we need this enum, can't we just use the `pebble.Compression` enum? Its string representation is the same if we lowercase it. I guess it doesn't map exactly because of the 24.1 check, maybe we could leave a TODO for when that's not there anymore.
___
*[`pkg/storage/pebble.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVa3P85qRl6W3KbZee:-NyVa3P95QP2QD-V1Igb:b-qx1eys) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L147)):*
> ```Go
> // cluster setting with the given name, description and default value.
> func RegisterCompressionAlgorithmClusterSetting(
> 	name settings.InternalKey, desc, defaultValue string,
> ```

[nit] The defaultValue should be a `CompressionAlgorithm` not a string
___
*[`pkg/storage/pebble.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVZnCm-K8BLE_ssdSB:-NyVZnCm-K8BLE_ssdSC:bnkk4d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L158)):*
> ```Go
> 		defaultValue,
> 		map[int64]string{
> 			int64(CompressionAlgorithmSnappy): CompressionAlgorithmSnappy.String(),
> ```

How come we don't have a "no compression" setting? Seems like it would be useful, at least for experiments (to compare CPU usage and sizes).
___
*[`pkg/storage/pebble.go` line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVZBs0ECMII87b5cpE:-NyVZBs0ECMII87b5cpF:b-553xz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L173)):*
> ```Go
> 	"storage.sstable.compression_algorithm",
> 	`determines the compression algorithm to use when compressing sstable data blocks for use in a Pebble store;`+
> 		` supported values: "snappy", "zstd"`,
> ```

[nit] "; supported values" could be added by `RegisterCompressionAlgorithmClusterSetting`

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124245)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @jbowens)

___
*[`pkg/storage/pebble.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVZsK49JJQQwOiL2fO:-Nzit60v-9gg4KyPU9uh:b-2kdzn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L125)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Why do we need this enum, can't we just use the `pebble.Compression` enum? Its string representation is the same if we lowercase it. I guess it doesn't map exactly because of the 24.1 check, maybe we could leave a TODO for when that's not there anymore.
</blockquote></details>

My fear is that we're already making use of the enum ints in the wild. Maybe with some care we can rework. I'll follow up on this part separately. Agree, it would be nice to make use of the Pebble enum / strings.
___
*[`pkg/storage/pebble.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVa3P85qRl6W3KbZee:-NzeRHHu4TB0VPBHonVx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L147)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] The defaultValue should be a `CompressionAlgorithm` not a string
</blockquote></details>

Done.
___
*[`pkg/storage/pebble.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVZnCm-K8BLE_ssdSB:-NzeSqZj8jOlW6Ck3tzM:b-2afl1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L158)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How come we don't have a "no compression" setting? Seems like it would be useful, at least for experiments (to compare CPU usage and sizes).
</blockquote></details>

I was going to do this separately. We have #122991 for it.
___
*[`pkg/storage/pebble.go` line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124245#-NyVZBs0ECMII87b5cpE:-Nzf3QHEDzhvA_t4hnk_:bnpzjcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/83695c22cfebb4b7c1375da3521d88d0b8e08260/pkg/storage/pebble.go#L173)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "; supported values" could be added by `RegisterCompressionAlgorithmClusterSetting`
</blockquote></details>

I'll follow up separately.

**Comment by nicktrav** [comment]
I'm going to back out the second commit here to try and get CI to pass. I have a suspicion the timeouts I'm seeing could be related to elevated CPU due to switching the compression alg.

**Comment by nicktrav** [comment]
TFTR!

bors r=RaduBerinde

**Pull request merged**
