### PR TITLE
colfetcher: produce batches only of needed columns

### PR DESCRIPTION
**Pull request by yuzefovich**
**colbuilder: reuse the SemaCtx**

Also inline a single function in the flow diagram.

Release note: None

**colfetcher: produce batches only of needed columns**

This commit updates the cFetcher to operate only on the needed columns.
Previously, it would get all columns present in the whole table and
create `coldata.Batch`es for each of the columns, even when only
a subset of columns is needed (or even available if the index is not
covering).

For example, imagine we have a table like
```
t (a INT PRIMARY KEY, b INT, c INT, d INT, INDEX b_idx (b))
```
and we have a query like `SELECT b FROM t@b_idx`. Previously, we would
create a batch with 4 `int64` columns with only 1 (for column `b`) being
actually populated and all others marked as "not needed" and set to all
NULL values.

This is suboptimal, and this commit refactors things so that a batch
with only a single vector is created. This is achieved in two steps:
- first, we populate the slice of column descriptors that are accessible
from the index. These are all columns of the table for covering indexes.
For non-covering secondary indexes we only keep columns present in the
index
- next, we examine the set of columns that need to be fetched and prune
all not needed columns away.

Note that we are always careful to update the post-processing spec
accordingly so that the spec always refers to correct new ordinals.

It's worth pointing out that since we're modifying the spec directly, we
had to introduce some special logic to keep the original state of the
`PostProcessSpec` in order for the flow diagrams to refer to the
original columns.

Release note: None

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 19 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71441)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 88 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-MmdRk-dBqv3FxwUdxXE:-MmdRk-e2eoid2SYWhGx:b-o4j51g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5715d2ec96c138a34d32fb8ebbe0623edf0dfcef/pkg/sql/colfetcher/cfetcher_setup.go#L88)):*
> ```
> [0, 0, 1, 0].
> ```
Could you elaborate on how/why this idxMap was reached in this example? After walking through the code a couple times I'm still unsure why the idxMap isn't [1, 0, 0, 0] and why it's ok for indexes 2 and 4 to be 0 in the idxMap.
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 125 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-MmdSI_l0vcOCk7NFkLa:-MmdSI_l0vcOCk7NFkLb:bcdcm6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5715d2ec96c138a34d32fb8ebbe0623edf0dfcef/pkg/sql/colfetcher/cfetcher_setup.go#L125)):*
> ```
> var idxMap []int
> ```
Could make this a named return value.
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 218 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-Mme3sFn5C45jc3MMZxU:-Mme3sFn5C45jc3MMZxV:b8a9xx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5715d2ec96c138a34d32fb8ebbe0623edf0dfcef/pkg/sql/colfetcher/cfetcher_setup.go#L218)):*
> ```Go
> 		neededColIdx := 0
> 		for idx, ok := neededColumnsSet.Next(0); ok; idx, ok = neededColumnsSet.Next(idx + 1) {
> 			idxMap[idx] = neededColIdx
> ```

This seems like duplicate work if idxMap was non-nil. Will idxMap change if it's already populated?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71441)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rharding6373)

___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 88 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-MmdRk-dBqv3FxwUdxXE:-MmeV5qL2OmlQCRwu3ij:bpvgsw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5715d2ec96c138a34d32fb8ebbe0623edf0dfcef/pkg/sql/colfetcher/cfetcher_setup.go#L88)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

> ```
> [0, 0, 1, 0].
> ```
Could you elaborate on how/why this idxMap was reached in this example? After walking through the code a couple times I'm still unsure why the idxMap isn't [1, 0, 0, 0] and why it's ok for indexes 2 and 4 to be 0 in the idxMap.
</blockquote></details>

Expanded the comment. Values for indexed 2 and 4 are undefined (they should never be used anyway) because these columns are not present in the index. Added this to the comment as well.
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 125 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-MmdSI_l0vcOCk7NFkLa:-MmeUCDx3eLEI38IKaEV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5715d2ec96c138a34d32fb8ebbe0623edf0dfcef/pkg/sql/colfetcher/cfetcher_setup.go#L125)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

> ```
> var idxMap []int
> ```
Could make this a named return value.
</blockquote></details>

Done.
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 218 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-Mme3sFn5C45jc3MMZxU:-MmeTjv2-wDaCUJEB1uO:b-pgwh84) ([raw file](https://github.com/cockroachdb/cockroach/blob/5715d2ec96c138a34d32fb8ebbe0623edf0dfcef/pkg/sql/colfetcher/cfetcher_setup.go#L218)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This seems like duplicate work if idxMap was non-nil. Will idxMap change if it's already populated?
</blockquote></details>

Yes, it'll change and we do want for it to change. In a sense, we're applying a projection on top another projection. I expanded the comment here as well as added an example. Let me know if things now make sense.

**Review by rharding6373 — COMMENTED** [review]
> the flow diagrams for EXPLAIN ANALYZE will refer to the remapped
> ordinals rather than "absolute" ordinals among all columns in the table
This potentially will add confusion when debugging, no? Is there a method for people to find the mapping in the logs or elsewhere that can be added to the commit/PR message? If not, could we log the remapping?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-:-Mmyr-mODSAdQCbuJvh8:breh2m9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 223 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-MmyoUmxEXPmvpBt7vuE:-MmyoUmxEXPmvpBt7vuF:b-37da84) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5e4ea8295d73793edce8666ba44a834a7a58733/pkg/sql/colfetcher/cfetcher_setup.go#L223)):*
> ```Go
> 		//
> 		// If non-nil idxMap was passed into this method, we have to update it
> 		// by essentially applying a projection on top of already present
> ```

nit: s/already/the already
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 237 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-MmyoOIT92Rl1TQEF7py:-MmyoOIT92Rl1TQEF7pz:b2cxf6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5e4ea8295d73793edce8666ba44a834a7a58733/pkg/sql/colfetcher/cfetcher_setup.go#L237)):*
> ```Go
> 		// update the index map to be
> 		//   idxMap = [x, 0, x, x]
> 		// and then to remap the post-processing spec below so that it refers to
> ```

nit: s/to remap/remap

**Review by yuzefovich — COMMENTED** [review]
Just want to call out the impact. Before this change `Out: @1` as in the diagram below

always referred to the column with ordinal `1` in the whole table, but after this change in order to understand which column `@1` is referring to, one would need to understand which columns are actually needed to be produced by the TableReader, so yeah, it can definitely lead to some confusion.

However, I think that we rarely if ever look at the concrete ordinals in that `Out` line - personally, I can't recall a single time where I needed to get that information, on the `EXPLAIN (DISTSQL)` diagrams I usually quickly glance only on the number of columns produced, and then if I want to understand which columns are propagated by each stage of processors, I'll look at another flavor of `EXPLAIN`. Assuming we're debugging with a stmt bundle, we'll have the correct information in other places.

In terms of exposing this remapping somewhere - I doubt anyone but engineers on SQL Queries will even think about using it, so I'd rather not tell users about it.

Still, let me take another stab at fixing this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-:-MmyuGCyDnKZ_0-4Qc4W:bo6qx1f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rharding6373)

**Review by yuzefovich — COMMENTED** [review]
Ok, I think I figured out a way to keep the flow diagrams unchanged.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-:-MmzDY-7-sssU8vmgNMc:becwuah)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rharding6373)

**Review by rharding6373 — APPROVED** [review]
Thanks! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71441#-:-Mn-5-No6s7I6ESlhSBc:b6duv8n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rharding6373)

**Pull request merged**
