### PR TITLE
sql: implement ALTER PROCEDURE

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/parser: parse ALTER PROCEDURE

This commit updates the parser so that it can parse `ALTER PROCEDURE`
statements.

Release note: None

#### sql/sem/tree: rename AlterFunction[Rename|SetSchema|SetOwner]

This commit renames some structs to be more general:

  * `AlterFunctionRename` => `AlterRoutineRename`
  * `AlterFunctionSetSchema` => `AlterRoutineSetSchema`
  * `AlterFunctionSetOwner` => `AlterRoutineSetOwner`

Release note: None

#### sql: implement ALTER PROCEDURE...RENAME TO

This commit implements the `ALTER PROCEDURE...RENAME TO` statement.

Release note: None

#### sql: implement ALTER PROCEDURE...SET SCHEMA

This commit implements the `ALTER PROCEDURE...SET SCHEMA` statement.

Release note: None

#### sql: implement ALTER PROCEDURE...OWNER TO

This commit implements the `ALTER PROCEDURE...OWNER TO` statement.

Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first 5 commits are from #111808.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work!

I think there's a missing check for `SET SCHEMA` (mentioned above). Apart from that, I just have a few questions.

> Reviewed 10 of 10 files at r1, 7 of 7 files at r2, 12 of 12 files at r3, 32 of 32 files at r4, 41 of 41 files at r5, 18 of 18 files at r6, 5 of 5 files at r7, 1 of 3 files at r8, 79 of 79 files at r9, 70 of 70 files at r10, 3 of 3 files at r11, 2 of 2 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-:-Ng798sQ30Z2sffL4t6P:bho2mzj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava, @mgartner, and @rharding6373)

___
*[`pkg/sql/alter_function.go` line 325 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng78Rl8C1GGKaw9C6TY:-Ng78Rl8C1GGKaw9C6TZ:b-6hv5ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ff2bcac52b897e51912e47f94b562d77393d60a/pkg/sql/alter_function.go#L325)):*
> ```Go
> 	if err != nil {
> 		return err
> 	}
> ```

We should check whether the routine is a procedure here like above, right?
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_schema_change` line 108 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng77q4L6I3xRmFL0y3Z:-Ng77q4MBWd0hEfRdTLf:bnrraw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a256684b2566bb718aee9998f9dc731c2b8ef220/pkg/sql/logictest/testdata/logic_test/procedure_schema_change#L108)):*
> ```
> SELECT oid, proname, prosrc
> FROM pg_catalog.pg_proc WHERE proname IN ('f_test_sc')
> ORDER BY oid
> ```

What's this testing?
___
*[`pkg/sql/parser/testdata/alter_procedure` line 23 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng6o3d76H1R_-wPqqZ6:-Ng6o3d76H1R_-wPqqZ7:bdsxjkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb5ce9fbb3bf310b2c05fe24dbc18cb8c85aae3/pkg/sql/parser/testdata/alter_procedure#L23)):*
> ```
> ALTER PROCEDURE p(IN INT8) SET SCHEMA test_sc -- fully parenthesized
> ALTER PROCEDURE p(IN INT8) SET SCHEMA test_sc -- literals removed
> ALTER PROCEDURE _(IN INT8) SET SCHEMA test_sc -- identifiers removed
> ```

Shouldn't `test_sc` be removed? If so it's broken for `ALTER FUNCTION` too, so no need to fix here.

**Review by rharding6373 — APPROVED** [review]
:lgtm: I only have a test suggestion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-:-Ng9Svwt-Nyi4QratV6w:b-atsie3)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jayshrivastava and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/procedure_schema_change` line 10 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng9RixTBgEMH98sNPFr:-Ng9RixTBgEMH98sNPFs:b5h3vpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92e659746b4a360a5aa98dd4b23409576b36f75/pkg/sql/logictest/testdata/logic_test/procedure_schema_change#L10)):*
> ```
> 
> statement ok
> CREATE PROCEDURE p_int(INT) LANGUAGE SQL AS 'SELECT 1'
> ```

It would be good to add a test that renames p_int to p_func. This should succeed, since their argument signatures are different.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111961)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @jayshrivastava)

___
*[`pkg/sql/alter_function.go` line 325 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng78Rl8C1GGKaw9C6TY:-NgJstxtENQGVFqC8OLO:bllaydm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ff2bcac52b897e51912e47f94b562d77393d60a/pkg/sql/alter_function.go#L325)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We should check whether the routine is a procedure here like above, right?
</blockquote></details>

Great catch! Done.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_schema_change` line 10 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng9RixTBgEMH98sNPFr:-NgJkt_Z9u0MddIJ7kET:b-fflhqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92e659746b4a360a5aa98dd4b23409576b36f75/pkg/sql/logictest/testdata/logic_test/procedure_schema_change#L10)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It would be good to add a test that renames p_int to p_func. This should succeed, since their argument signatures are different.
</blockquote></details>

Great idea. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_schema_change` line 108 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng77q4L6I3xRmFL0y3Z:-NgJlFcA1Ut_2DZUL7WL:b1llovr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a256684b2566bb718aee9998f9dc731c2b8ef220/pkg/sql/logictest/testdata/logic_test/procedure_schema_change#L108)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What's this testing?
</blockquote></details>

copy-pasta :spaghetti:

It now shows the OIDs of the three procedures to give some context to the tests below. 
___
*[`pkg/sql/parser/testdata/alter_procedure` line 23 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng6o3d76H1R_-wPqqZ6:-NgJmcLj72lBedNj_mOj:b-al6w3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb5ce9fbb3bf310b2c05fe24dbc18cb8c85aae3/pkg/sql/parser/testdata/alter_procedure#L23)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Shouldn't `test_sc` be removed? If so it's broken for `ALTER FUNCTION` too, so no need to fix here.
</blockquote></details>

Yes, good catch. I'll fix this in a follow-up PR.

**Comment by mgartner** [comment]
*[`pkg/sql/parser/testdata/alter_procedure` line 23 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111961#-Ng6o3d76H1R_-wPqqZ6:-NgKcJBXDeOSO_TaMm4C:bfqx1y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb5ce9fbb3bf310b2c05fe24dbc18cb8c85aae3/pkg/sql/parser/testdata/alter_procedure#L23)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes, good catch. I'll fix this in a follow-up PR.
</blockquote></details>

See #112046.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
