### PR TITLE
changfeedccl: bound per-changefeed memory buffer capacity

### PR DESCRIPTION
**Pull request by danhhz**
Any changefeed that uses RangeFeed has an in-memory buffer that slurps
from the RangeFeed as fast as possible to avoid SLOW_CONSUMER
disconnections. Previously this buffer had an unbounded capacity, which
meant that a slow sink (or an issue like we're seeing in #35114 where
lots of duplicates get emitted), would OOM. Prevent this by setting a
100MB limit.

Ideally all changefeeds would share a single capacity that was given by
the operater at startup, like we do for RocksDB and SQL, but this is a
much bigger change.

Also ideally, this would do something smarter than erroring, like shut
down the RangeFeeds and keep the changefeed running (so it affects the
changefeed.max_behind_nanos which users are expected to monitor), but
this erroring is simplest to start with.

Touches #35114

Release note (bug fix): `CHANGEFEED`s connected to a slow sink now error
instead of using unbounded amounts of memory.

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
I'm going to run an instance of the ledger and tpcc-1000 roachtests with this change. I'm expecting it to fail the former with this error but still have enough capacity in the budget to pass the latter.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-:-L_xMLf5A7DWcZsvR8tS:bxn3js5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1751 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-L_xLoha0pWvCMNlmYYA:-L_xLoha0pWvCMNlmYYB:bco1udr) ([raw file](https://github.com/cockroachdb/cockroach/blob/72176a23ca7c293ccb3fb8e5fcf360123573ae08/pkg/ccl/changefeedccl/changefeed_test.go#L1751)):*
> ```Go
> 		sqlDB.Exec(t, `INSERT INTO foo SELECT i, 'foofoofoo' FROM generate_series(1, $1) AS g(i)`, rows)
> 		var err error
> 		for i := 0; i < rows; i++ {
> ```

I think this is racy as written. We could happen to get everything from RangeFeed spaced out just enough that they stay perfectly under the budget. I haven't seen any flakes when stressing it locally, but I'd still like to do something smarter with blocking the BeforeEmitRow knob. That was flaking pretty often with changefeed shutdown, so not as easy as I'd hoped.

**Comment by danhhz** [comment]
Screen Shot 2019-03-14 at 11 14 27 AM

🙌

**Comment by danhhz** [comment]
Okay, this has been verified to turn the OOM in cdc/ledger into an error. I'm giving up on testing this with tpcc-1000. I keep getting errors that are clearly unrelated to this change and at some point I have to move back to working on #35114. I'm pretty familiar with the buffer in/out graph of tpcc-1000 at this point and I've never seen anything from it that makes me believe that buffer would be full enough to trigger this condition.

This should be ready to go. The race I pointed out in the test is unfortunate, but don't see a great way to fix it, and it doesn't seem to flake in practice so I'm tempted to leave it as a TODO.

**Comment by danhhz** [comment]
@nvanbenschoten The cdc/ledger test seems to pass as of what I have here. Still some work to do to really harden it, but perhaps this is enough for 19.1.0. PTAL

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35745)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @nvanbenschoten, and @tbg)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1754 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-L_yxlbC26J3dQHIgd-b:-L_yxlbC26J3dQHIgd-c:b-3tyef2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3505debbe908baa4b586505565d5bf0acc96961/pkg/ccl/changefeedccl/changefeed_test.go#L1754)):*
> ```Go
> 		// but I'd still like to do something smarter with blocking the
> 		// BeforeEmitRow knob, but there are some subtleties with that approach to
> 		// work out.
> ```

Using either a knob or preventing rows from being flushed to the sink is what I would suggest.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1764 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-L_yxSlN8g20iNTKvbRM:-L_yxSlN8g20iNTKvbRN:bwy5cbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3505debbe908baa4b586505565d5bf0acc96961/pkg/ccl/changefeedccl/changefeed_test.go#L1764)):*
> ```Go
> 		}
> 		if !testutils.IsError(err, `memory budget exceeded`) {
> 			t.Fatalf(`expected "memory budget exceeded error got: %v`, err)
> ```

Missing closing quotes.
___
*[pkg/storage/replica_rangefeed.go, line 261 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-L_yyN1IBZ9HWJXKsSDt:-L_yyN1IBZ9HWJXKsSDu:b-jyfxpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/85949191dd9cd8ecb27e10a3d92256d64e1c1d11/pkg/storage/replica_rangefeed.go#L261)):*
> ```Go
> 		Span:             desc.RSpan(),
> 		TxnPusher:        &tp,
> 		EventChanCap:     4096,
> ```

The size of an `event` is 112 bytes, so this will result in an allocation on the order of ~512KB. That's probably ok given the number of ranges on a node that we'd like to support with active rangefeeds, but it's certainly on the upper end of the range.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35745)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1754 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-L_yxlbC26J3dQHIgd-b:-La0weOCCKCjQpNAhqFt:bcqngj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3505debbe908baa4b586505565d5bf0acc96961/pkg/ccl/changefeedccl/changefeed_test.go#L1754)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Using either a knob or preventing rows from being flushed to the sink is what I would suggest.
</blockquote></details>

Yeah, that's what I tried, but I was hitting deadlocks in changefeed teardown. After sleeping on it, realized the fix is pretty simple if I plumb a ctx into the BeforeEmitHook
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1764 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-L_yxSlN8g20iNTKvbRM:-La0x6u30b9MBwEr-k-1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3505debbe908baa4b586505565d5bf0acc96961/pkg/ccl/changefeedccl/changefeed_test.go#L1764)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Missing closing quotes.
</blockquote></details>

Done
___
*[pkg/storage/replica_rangefeed.go, line 261 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-L_yyN1IBZ9HWJXKsSDt:-La0x26c84xn128dh_6c:bq0l0kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/85949191dd9cd8ecb27e10a3d92256d64e1c1d11/pkg/storage/replica_rangefeed.go#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The size of an `event` is 112 bytes, so this will result in an allocation on the order of ~512KB. That's probably ok given the number of ranges on a node that we'd like to support with active rangefeeds, but it's certainly on the upper end of the range.
</blockquote></details>

I'm anxious about this too. Made a note.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35745#-:-La1kesV3OQhQ7UAUQi-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

**Comment by danhhz** [comment]
Flake looks like #35758

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
