### PR TITLE
sql: more HP cleanup (remove sql.physicalProps)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: clean up scan and merge join ordering code

Remove the code that was used by the HP to initialize orderings for
scans and merge joins.

Release note: None

#### sql: don't use physicalProps

Remove uses of `physicalProps`, replacing with just a required
ordering.

Release note: None

#### sql: remove physicalProps

Remove `physicalProps` code and rename `plan_physical_props.go` to
`plan_ordering.go`.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
Nice cleanup! :lgtm:

> Reviewed 7 of 7 files at r1, 19 of 19 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41668#-:-LrPJZLU3KBe6hQj_Xyq:b-jy7zf3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 19 of 19 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41668#-:-LrPb2k5AEHbti8_WN-q:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/join_test.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41668#-LrPYZQmA5eKf_YiqOBy:-LrPYZQmA5eKf_YiqOBz:bdlsom1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a3625f279ac3c25fbb500b7aedf85e8e2790d/pkg/sql/join_test.go#L83)):*
> ```Go
> //
> // If merge-join can be used, the function returns a ColumnOrdering that refers
> // to the equality columns by their index in colA/ColB. Specifically column i in
> ```

[nit] ColB -> colB
___
*[pkg/sql/join_test.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41668#-LrP_6Aq5Bg-YVqwRZDD:-LrP_6Aq5Bg-YVqwRZDE:b-4bkkiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a3625f279ac3c25fbb500b7aedf85e8e2790d/pkg/sql/join_test.go#L89)):*
> ```Go
> // The returned ordering can be partial, i.e. only contains a subset of the
> // equality columns.
> func computeMergeJoinOrdering(
> ```

Where is this used?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41668)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/join_test.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41668#-LrPYZQmA5eKf_YiqOBy:-LrZJaV9CaXDiA6ua6Gk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a3625f279ac3c25fbb500b7aedf85e8e2790d/pkg/sql/join_test.go#L83)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] ColB -> colB
</blockquote></details>

Done.
___
*[pkg/sql/join_test.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41668#-LrP_6Aq5Bg-YVqwRZDD:-LrZJameC3QvRSWoZBu3:b-8oew80) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a3625f279ac3c25fbb500b7aedf85e8e2790d/pkg/sql/join_test.go#L89)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Where is this used?
</blockquote></details>

In `distsql_plan_join_test.go`. I moved it to that file, I didn't realize it was just one.

**Pull request merged**
