### PR TITLE
sql: make database, table, view and columns lookups properly case-sensitive

### LINKED ISSUE #8862: sql: Identifiers should always be case-folded unless double quoted
The Postgres JDBC driver makes a few assumptions about SQL identifiers (table names, column names, etc.) being case-folded unless double quoted. This provides the desired behavior that most usages of identifiers are case-insensitive. PG's documentation on this behavior is [here](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).

Postgres Behavior Example:

```
postgres=# CREATE TABLE a (i int);
CREATE TABLE
postgres=# select * from a;
 i

---
(0 rows)

postgres=# select * from A;
 i

---
(0 rows)

postgres=# select * from "a";
 i

---
(0 rows)

postgres=# select * from "A";
ERROR:  relation "A" does not exist
LINE 1: select * from "A";
                      ^
```

In CockroachDB however, we handle identifiers differently. Instead of performing this case-folding early in our parser, we have case-insensitive comparisons scattered throughout our code. This means that the case of object names in descriptors could be lower-case, upper-case, or mixed. This is proving to be problematic.

Because the PGJDBC driver makes the assumption that all identifiers are case-folded unless explicitly told not to (using double quotes), it often performs case-sensitive comparisons against introspective statement results. This means that a series of statements like the following work for Postgres, but don't work for us. 

```
CREATE TABLE Test (a int);
SELECT * FROM pg_class WHERE relname = 'test'
```

Note also that the `select * from "A";` example above would select from table `a` in CockroachDB, which is a deviation from Postgres and may not be desirable. 

I propose that we change our SQL parser to perform case-folding early on, and always store case-folded names in db/table descriptors (again, unless told not to with double quotes). This will allow us to ignore identifier case throughout the rest of the `sql` package, and will fix the two issues discussed above for free.

### LINKED ISSUE #16858: sql: "SHOW INDEXES" claiming table does not exist
`build:      CCL b5fffc159 @ 2017/07/05 16:23:29 (go1.8.1)`

- What did you do?
`cockroach sql -d test`
```
root@:26257 ?> CREATE DATABASE test;
root@:26257/test> show tables;
+-------+
| Table |
+-------+
+-------+
(0 rows)
root@:26257/test> CREATE TABLE "A" ("id" serial NOT NULL PRIMARY KEY, "uni" varchar(1000) NOT NULL);
CREATE TABLE
root@:26257/test> SHOW INDEXES FROM a;
pq: table "a" does not exist
root@:26257/test> show create table a;
+-------+-------------------------------------------------+
| Table |                   CreateTable                   |
+-------+-------------------------------------------------+
| a     | CREATE TABLE a (␤                               |
|       |     id INT NOT NULL DEFAULT unique_rowid(),␤    |
|       |     uni STRING(1000) NOT NULL,␤                 |
|       |     CONSTRAINT "primary" PRIMARY KEY (id ASC),␤ |
|       |     FAMILY "primary" (id, uni)␤                 |
|       | )                                               |
+-------+-------------------------------------------------+
(1 row)
root@:26257/test>
```
- What did you expect to see?
Some indexes.

- What did you see instead?
`pq: table "a" does not exist`

### PR DESCRIPTION
**Pull request by knz**
### sql: sanitize the production of error message for tables/views

- use the same word "relation" for tables and views for permission
  errors and "descriptor does not exist" errors, for consistency with
  the existing "already exists" message that already uses the word
  "relation".

- ensure that names containing special characters are not
  doubly quoted in the error message.

### sql: make table and view lookups properly case-sensitive

An earlier change introduced pre-normalization of descriptor names
upon descriptor creation, thereby aiming for two goals:

- normalize descriptor names upon creation of the descriptor, so as to
  avoid the time overhead of re-normalizing the name on every access;

- creating a distinction, like one exists in postgres, between
  descriptors created with the syntax `"A"` and the syntax `A` - the
  latter is normalized, the former is not. This makes case sensitivity
  opt-in for client applications.

Unfortunately, prior to this patch, most SQL statements also used a
case-insensitive *lookup* of database/table/view/column names from
storage, preventing the aforementioned benefits.

This patch completes the earlier change by making name lookups
case-sensitive. An exhaustive set of tests is modified/introduced to confirm
that the change is invisible to most common use cases -- i.e. as long
as client apps were not double quoting their identifiers.

Fixes #8862.
Fixes #16858.

### CODE REVIEW

**Comment by knz** [comment]
Added the part for column names too.

**Comment by eisenstatdavid** [comment]
Thanks so much for your hard work on this! Aside from some nits (noted below), my main concern is that there are no new/altered tests concerned with Unicode normalization.

Also, has management approved this behavior change?

---

Reviewed 38 of 48 files at r1, 56 of 56 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/targets.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Kogw23XAY0zYXAWOhgM:-Kogw23XAY0zYXAWOhgN:bf9akku) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/ccl/sqlccl/targets.go#L35)):*
> ```Go
> 	starByDatabase := make(map[string]validity, len(targets.Databases))
> 	for _, d := range targets.Databases {
> 		starByDatabase[string(d)] = maybeValid
> ```

Can you change the type of the map instead of converting everywhere?

---

*[pkg/sql/alter_table.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-KogxDtdtBKafLFOSASG:-KogxDtdtBKafLFOSASH:b-ruoole) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/alter_table.go#L89)):*
> ```Go
> 				return err
> 			}
> 			_, dropped, err := n.tableDesc.FindColumnByName(string(d.Name))
> ```

Could we change the signature of `FindColumnByName` instead?

---

*[pkg/sql/data_source.go, line 677 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-KogxqvhDIOI0BhbAZ0Z:-KogxqvhDIOI0BhbAZ0_:b-vwv3pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/data_source.go#L677)):*
> ```Go
> 		if !ok {
> 			return nil, nil, fmt.Errorf("relation %q not found",
> 				parser.AsStringWithFlags(&tableName, parser.FmtBareIdentifiers))
> ```

Is this a change that should be made more systematically?

---

*[pkg/sql/drop.go, line 433 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-KogyLOQhbtlYm7f04LD:-KogyLOQhbtlYm7f04LE:b-uklnhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/drop.go#L433)):*
> ```Go
> 			}
> 			// View does not exist, but we want it to: error out.
> 			return nil, sqlbase.NewUndefinedTableError(tn)
> ```

Perhaps rename to `NewUndefinedRelationError`?

---

*[pkg/sql/table.go, line 388 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Koh-mpnx-B0eKkUzM3K:-Koh-mpnx-B0eKkUzM3L:b-1il2qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/table.go#L388)):*
> ```Go
> 			return nil, sqlbase.NewUndefinedTableError(
> 				&parser.TableName{
> 					TableName:               parser.Name(fmt.Sprintf("<id=%d>", tableID)),
> ```

I vaguely remember that the parser accepts a different syntax for specifying tables by ID? Perhaps I'm confused.

---

*[pkg/sql/logictest/testdata/logic_test/case_sensitive_names, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Koh0Z0SxizmqzHtFBAA:-Koh0Z0T63Yb_FvfirTi:b-qzg675) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/logictest/testdata/logic_test/case_sensitive_names#L36)):*
> ```
> SHOW CREATE TABLE "A"
> 
> statement error relation "test.A" does not exist
> ```

Is there a good reason that this one is not like the others?

---

*[pkg/sql/logictest/testdata/logic_test/select, line 173 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Koh1b3Q1_JBZHkyqEBB:-Koh1b3Q1_JBZHkyqEBC:b-spfvg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/logictest/testdata/logic_test/select#L173)):*
> ```
> 
> query T
> SELECT "foo"."v" FROM kv AS foo WHERE foo.k = 'a'
> ```

Are the quotes still needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-:-Koh3E3sTRhU9UZMDsj4:b-lusjza)*

**Comment by knz** [comment]
@bdarnell said "ok as long as it brings us closer to pg compatibility".

---

Review status: 69 of 99 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/ccl/sqlccl/targets.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Kogw23XAY0zYXAWOhgM:-Kp1gN9XG40FVYIBAmvi:b-sda8c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/ccl/sqlccl/targets.go#L35)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Can you change the type of the map instead of converting everywhere?
</blockquote></details>

Not comfortable about that: there are more uses below which do not convert.

---

*[pkg/sql/alter_table.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-KogxDtdtBKafLFOSASG:-Kp1hLeRnBM7FY1hWUDo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/alter_table.go#L89)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Could we change the signature of `FindColumnByName` instead?
</blockquote></details>

Done.

---

*[pkg/sql/data_source.go, line 677 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-KogxqvhDIOI0BhbAZ0Z:-Kp1zDsbmxDudPrcXcXQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/data_source.go#L677)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Is this a change that should be made more systematically?
</blockquote></details>

Done.

---

*[pkg/sql/drop.go, line 433 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-KogyLOQhbtlYm7f04LD:-Kp1iqzJkXfSQVVNhn5i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/drop.go#L433)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Perhaps rename to `NewUndefinedRelationError`?
</blockquote></details>

Done.

---

*[pkg/sql/table.go, line 388 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Koh-mpnx-B0eKkUzM3K:-Kp1XcALcxGz3tgL15wr:b-ghdmg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/table.go#L388)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

I vaguely remember that the parser accepts a different syntax for specifying tables by ID? Perhaps I'm confused.
</blockquote></details>

Not yet. This feature will only come when #15388 is merged (or the underlying commit which adds the syntax).

---

*[pkg/sql/logictest/testdata/logic_test/case_sensitive_names, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Koh0Z0SxizmqzHtFBAA:-Kp1XkWK5OCSdwZEtGXL:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/logictest/testdata/logic_test/case_sensitive_names#L36)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Is there a good reason that this one is not like the others?
</blockquote></details>

Fixed.

---

*[pkg/sql/logictest/testdata/logic_test/select, line 173 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Koh1b3Q1_JBZHkyqEBB:-Kp1g-cDsaIDetjW_RKZ:b-3onfp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/logictest/testdata/logic_test/select#L173)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Are the quotes still needed?
</blockquote></details>

they are not needed, it's only a smoke test to check that the double quote syntax is allowed also in expression context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-:-Kp1U2hVl3rfFrnSvbT-:b9qj75c)*

**Comment by knz** [comment]
Review status: 69 of 100 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/table.go, line 388 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-Koh-mpnx-B0eKkUzM3K:-Kp63B2AnRjXcOcirifY:bq1cl8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/87da6556cc6b823cfb380e761ea7f9f4e77051c7/pkg/sql/table.go#L388)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not yet. This feature will only come when #15388 is merged (or the underlying commit which adds the syntax).
</blockquote></details>

Scratch that, actually we supported the feature already. Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884)*

**Comment by knz** [comment]
Added a unicode normalization test as requested.

**Comment by eisenstatdavid** [comment]
:lgtm_strong: Thanks again!

---

Reviewed 31 of 31 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16884#-:-KpGs8q07l4M3JD0cQpX:b-q12p17)*

**Comment by knz** [comment]
TFYRs!

**Pull request merged**
