### PR TITLE
sql: change TableDescriptor.Deleted to ADD,PUBLIC, or DROP

### PR DESCRIPTION
**Pull request by dt**
The boolean deleted indicated a table that was no longer public, however some schema changes (eg FKs) also require a non-public state during table creation.

Changing the simple bool to an enum with states for `public`, `adding` and `dropping` allows modeling the whole lifecycle.

Existing checks of `Deleted` can instead just look for the `DROP` state, which is also
wrapped in a shorter helper.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6510)

### CODE REVIEW

**Comment by knz** [comment]
If possible I'd appreciate queuing this after #6492 lands :)

**Comment by vivekmenezes** [comment]
Is https://github.com/cockroachdb/cockroach/pull/6309 ready for another
look?

**Comment by knz** [comment]
LGTM

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510#-KH0TI5C8Q0Xp2rcShQ0:-KH0TI5C8Q0Xp2rcShQ1:-1927665902) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0060b757792ee745fc3d23c01e33ed88fa4a0de/sql/lease.go#L126)):*
wanna return a different error for not PUBLIC?

---

*[sql/structured.proto, line 266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510#-KH0SpVHirtmR1s6jAkB:-KH0SpVHirtmR1s6jAkC:-187894946) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0060b757792ee745fc3d23c01e33ed88fa4a0de/sql/structured.proto#L266)):*
not used? seems wong.

And ADD is commented out? Add a TODO or remove it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510#-:-KH0ThiZOIiLCmneBYLM:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510#-KH0TI5C8Q0Xp2rcShQ0:-KH0UXZqEmkqmtGgx6SE:-648840388) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0060b757792ee745fc3d23c01e33ed88fa4a0de/sql/lease.go#L126)):*
hm, what would be the rational? a non-public table, for user-facing purposes, just doesn't exist, right?

---

*[sql/structured.proto, line 266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510#-KH0SpVHirtmR1s6jAkB:-KH0UKxRPzzZkKvkJTL5:1688713894) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0060b757792ee745fc3d23c01e33ed88fa4a0de/sql/structured.proto#L266)):*
`ADD` would be unused at the moment and make our linter unhappy, but I think it logically belongs in this diff with the other states.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510)*

**Comment by andreimatei** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510#-KH0TI5C8Q0Xp2rcShQ0:-KH0V29THTc9OI7fG88N:24437005) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0060b757792ee745fc3d23c01e33ed88fa4a0de/sql/lease.go#L126)):*
well, doesn't exist is `DescriptorNotFound` above. As opposed to the descriptor existing, but being some other type of descriptor than a table.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6510)*

**Pull request merged**
