### PR TITLE
Fix the bank benchmark.

### PR DESCRIPTION
**Pull request by petermattis**
It was erroring on every statement due to failing type checking on the
CASE expression. Add support for running the bank benchmark against
postgres.

name              time/op
Bank_Cockroach-8   173µs ±16%
Bank_Postgres-8   45.9µs ± 5%

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4109)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4109#-:-K9cGVhN6nSKtEvtgVoE:676834233)*

**Comment by tamird** [comment]
LGTM

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bank_test.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4109#-K9cUK2Fpt_CDYH2yUx6:-K9cUK2Fpt_CDYH2yUx7:-1789614608) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf5fff75a7df139565b2ab2cce1dee43422ad2f6/sql/bank_test.go#L81)):*
can you add casts to the place holders as type hints?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4109)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bank_test.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4109#-K9cUK2Fpt_CDYH2yUx6:-K9cVU1CaG6hE82Nw89i:1491360729) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf5fff75a7df139565b2ab2cce1dee43422ad2f6/sql/bank_test.go#L81)):*
I don't know. Can this be added to your list of tests for the new typing stuff you're working on?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4109)*

**Pull request merged**
