### PR TITLE
server: assert `ApproximateDiskBytes` from db details is non-zero

### LINKED ISSUE #105504: server: TestAdminAPIDatabaseDetails failed
server.TestAdminAPIDatabaseDetails [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10660514?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10660514?buildTab=artifacts#/) on release-22.2 @ [e36a88e4bd22dae1108e1276d6a4cdc680bc6a1b](https://github.com/cockroachdb/cockroach/commits/e36a88e4bd22dae1108e1276d6a4cdc680bc6a1b):

```
=== RUN   TestAdminAPIDatabaseDetails
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/5b2c9b3a394428c7572d34050aad8975/logTestAdminAPIDatabaseDetails1011264950
    test_log_scope.go:79: use -show-logs to present logs inline
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
    admin_cluster_test.go:75: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/admin_cluster_test.go:75
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:69
        	            				github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:75
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:57
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:40
        	            				github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/admin_cluster_test.go:59
        	Error:      	Not equal: 
        	            	expected: 0x0
        	            	actual  : 0x9b1
        	Test:       	TestAdminAPIDatabaseDetails
        	Messages:   	ApproximateDiskBytes
    admin_cluster_test.go:79: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/5b2c9b3a394428c7572d34050aad8975/logTestAdminAPIDatabaseDetails1011264950
--- FAIL: TestAdminAPIDatabaseDetails (23.48s)
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #103394 server: TestAdminAPIDatabaseDetails failed [A-cluster-observability C-test-failure O-robot T-cluster-observability branch-release-22.1]
</p>
</details>
/cc @cockroachdb/obs-inf-prs @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAdminAPIDatabaseDetails.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29085

### PR DESCRIPTION
**Pull request by xinhaoz**
This test changes the assertion for the `ApproximateDiskBytes` field in the db details api test to ensure that we have a non-zero value. Previously, we asserted this value was 0 as often times the data had not yet been flushed by the storage engine. This change deflakes the test by flushing each store before making the call to fetch db details.

Epic: none
Fixes: #105504

Release note: None

### CODE REVIEW

**Review by zachlite — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106624)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`pkg/server/admin_cluster_test.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106624#-N_5mzUNCrnysxwMgt7H:-N_5mzUNCrnysxwMgt7I:bb741sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2681393cab16f7ddbf49ea367b29357b43de25/pkg/server/admin_cluster_test.go#L58)):*
> ```Go
> 		s := tc.Server(i)
> 		err = s.GetStores().(*kvserver.Stores).VisitStores(func(store *kvserver.Store) error {
> 			return store.TODOEngine().Flush()
> ```

TIL!
___
*[`pkg/server/admin_cluster_test.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106624#-N_5mKWZ8g9T7L84tUru:-N_5mKWZ8g9T7L84tUrv:bgl8wfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2681393cab16f7ddbf49ea367b29357b43de25/pkg/server/admin_cluster_test.go#L61)):*
> ```Go
> 		})
> 	}
> 	require.NoError(t, err)
> ```

quick fix: Can you assert there's no error after each iteration?

**Comment by xinhaoz** [comment]
*[`pkg/server/admin_cluster_test.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106624#-N_5mKWZ8g9T7L84tUru:-N_5qbIgAieBzImtYe4g:bqsuixr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2681393cab16f7ddbf49ea367b29357b43de25/pkg/server/admin_cluster_test.go#L61)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

quick fix: Can you assert there's no error after each iteration?
</blockquote></details>

oops -- yup, done!

**Review by zachlite — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106624#-:-N_5t-0x72fhPu2XbBuB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
