### PR TITLE
cli: Enable profiles and other debug info for tenants

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR updates debug.zip functionality to
collect goroutine stacks and profiles for all
active SQL instances for a tenant.
This PR also addresses a bug where the nodes.json
and status.json data was not getting populated
correctly due to the switch to the `NodesList` API.
This bug has been addressed by using the p;d
`Nodes` API when the debug zip command is run against
a storage server.

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Looking good! A few nits/questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-:-MvyjjL1Az6KdXP8uXY6:bbowoj5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rimadeodhar)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvyVtZfBs6qKuwP6spk):*
Any chance these can be split into 2 separate commits? I think it would make it easier to reason about which diffs are relevant.



_Code quote:_
```
also addresses a bug
```
___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvyVX9L7kbBN3aonqWE):*
nit: typo



_Code quote:_
```
p;d
```
___
*[pkg/cli/zip_cluster_wide.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mvyj8LW2h01XYbs1Jid:-Mvyj8LXC_crnuYBouiC:b-nnv408) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/cli/zip_cluster_wide.go#L201)):*
> ```Go
> 	nodesResponse, err := zc.status.Nodes(ctx, &serverpb.NodesRequest{})
> 	nodesList := &serverpb.NodesListResponse{}
> 	if code := status.Code(errors.Cause(err)); code == codes.Unimplemented {
> ```

nit: Should this also include some kind of `err != nil` check?



_Code quote:_
```Go
if code := status.Code(errors.Cause(err)); code == codes.Unimplemented {
```
___
*[pkg/server/status_util.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvyamuM6_Td6KuAZzjg:-MvyamuM6_Td6KuAZzjh:b-l92xxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/status_util.go#L31)):*
> ```Go
> // This file contains helper functions used by tenantStatusServer and statusServer.
> func profileLocal(
> 	ctx context.Context, req *serverpb.ProfileRequest, st *cluster.Settings,
> ```

nit: For this fn and the 2 below, would it make sense to try and decouple the params list from the request objects? It might help keep them flexible to be used elsewhere in the future - or do we *want* them to be coupled? :thinking:  



_Code quote:_
```Go
req *serverpb.ProfileRequest
```
___
*[pkg/server/status_util.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvygOsOAnGsYJIXT0Qz:-MvygOsP-JzJ2cfZLbvu:b4ojglu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/status_util.go#L97)):*
> ```Go
> func getLocalFiles(
> 	req *serverpb.GetFilesRequest,
> 	heapProfileDirName string,
> ```

Yay! This means we should get active query dumps in tenant debug.zip's for each SQL server instance. :tada: 



_Code quote:_
```Go
	heapProfileDirName string,
```
___
*[pkg/server/tenant_status.go, line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvycLFk2GL8u_ng6hsN:-MvycLFlEbMSEBo47qcV:b9tradu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/tenant_status.go#L810)):*
> ```Go
> 	}
> 
> 	instanceID, local, err := t.parseInstanceID(request.NodeId)
> ```

nit: consider updating the docstring comments on the request proto message to note that this can also be an instance ID



_Code quote:_
```Go
request.NodeId
```
___
*[pkg/server/tenant_status.go, line 838 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvydB1a-2cLFLH5j3Uu:-MvydB1b4gHnqWLNrUF8:b51l13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/tenant_status.go#L838)):*
> ```Go
> 	}
> 
> 	instanceID, local, err := t.parseInstanceID(request.NodeId)
> ```

nit: same as above



_Code quote:_
```Go
request.NodeId
```
___
*[pkg/server/tenant_status.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvyfC5L3iBKCWwBzjxv:-MvyfC5L3iBKCWwBzjxw:btp7g19) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/tenant_status.go#L1100)):*
> ```Go
> 	}
> 
> 	instanceID, local, err := t.parseInstanceID(req.NodeId)
> ```

nit: ditto above



_Code quote:_
```Go
req.NodeId
```

**Review by knz — APPROVED** [review]
:lgtm: on the overall structure. I'll let your team judge on local correctness.

> Reviewed 15 of 15 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-:-Mw74QBtCub8SYns_n4o:bgpuooe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @rimadeodhar, and @srosenberg)

___
*[pkg/server/status_util.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73Qog57fr8b_0MTLo:-Mw73Qog57fr8b_0MTLp:b-vtqoic) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

file name: `status_local_file_retrieval.go`

(The name `_util.go` suggests this should become a dumping ground. Let's avoid creating that impression.)
___
*[pkg/server/status_util.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73Wvl1yG-C4K8HXE0:-Mw73Wvl1yG-C4K8HXE1:b-1nhdfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2022, not 2021
___
*[pkg/server/status_util.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73d1gAyqzxx7R-y-S:-Mw73d1h6ko1G48m-OpN:b-5h5e3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L30)):*
> ```Go
> )
> 
> // This file contains helper functions used by tenantStatusServer and statusServer.
> ```

Here and below: explain whether each function returns a gRPC error or not.
___
*[pkg/server/status_util.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73m0N2aGY0ReIl1Oc:-Mw73m0N2aGY0ReIl1Od:b-86kysd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L47)):*
> ```Go
> 			}
> 			if err := pprof.StartCPUProfile(&buf); err != nil {
> 				return err
> ```

what about this err return
___
*[pkg/server/status_util.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73k7D16yRnlNRD-Hh:-Mw73k7D16yRnlNRD-Hi:b-86kysd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L57)):*
> ```Go
> 			}
> 		}); err != nil {
> 			return nil, err
> ```

what about this err return

**Review by dhartunian — COMMENTED** [review]
> Reviewed 15 of 15 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76539)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @rimadeodhar, and @srosenberg)

___
*[-- commits, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MwYiFFs59_0ILKvlmBf):*
nit: storage nodes instead of kv?
___
*[-- commits, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb4GiDEl2YKqhwHiAf):*
From reading this commit message I don't gain any understanding about what the problem was. Can you provide some more info here on what the issue is and why the `NodesList` API is inadequate while the `Nodes` API is.
___
*[pkg/cli/zip.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MwbAZpa7UWZ5R2ldr6z:-MwbAZpa7UWZ5R2ldr7-:b-5fxc2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip.go#L99)):*
> ```Go
> 	ctx context.Context,
> 	ni nodesInfo,
> 	fn func(ctx context.Context, nodeDetails serverpb.NodeDetails, nodeStatus *statuspb.NodeStatus) error,
> ```

Consider adding a comment here that `nodeStatus` should be expected to be nil for valid SQL-only nodes.
___
*[pkg/cli/zip.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MwYiYlL6W3kIZD2m3Ic:-MwYiYlMDaEYQRr1Z2hw:b-f25z0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip.go#L105)):*
> ```Go
> 		return errors.AssertionFailedf("nodes list is empty")
> 	}
> 	if ni.nodeStatusResponse != nil && len(ni.nodeStatusResponse.Nodes) != len(ni.nodeListResponse.Nodes) {
> ```

Are these guaranteed to match?  Just wondering if, for instance, one lists recently decommissioned nodes and another does not. It's possible the count may not match in exactly those situations where we take a debug.zip so just want to check.
___
*[pkg/cli/zip_cluster_wide.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb64T9Ch4WZVkXxl62:-Mwb64T9Ch4WZVkXxl63:b-p7m8mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip_cluster_wide.go#L118)):*
> ```Go
> // SQL only servers will only return nodeDetails for all SQL nodes.
> // Storage servers will return both nodeDetails as well as nodeStatus
> // for all KV nodes.
> ```

Nothing below is named `nodeDetails`. Can you clarify?
___
*[pkg/cli/zip_cluster_wide.go, line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb7ZmV4g7ouyF5U9k_:-Mwb7ZmV4g7ouyF5U9ka:bc4amxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip_cluster_wide.go#L121)):*
> ```Go
> type nodesInfo struct {
> 	nodeStatusResponse *serverpb.NodesResponse
> 	nodeListResponse   *serverpb.NodesListResponse
> ```

nit: should naming match type? plural `nodesList...` and `nodesStatus...`?
___
*[pkg/cli/zip_cluster_wide.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb7kxHBWUOS0epVyTT:-Mwb7kxHBWUOS0epVyTU:b-958iw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip_cluster_wide.go#L204)):*
> ```Go
> 	if code := status.Code(errors.Cause(err)); code == codes.Unimplemented {
> 		// Likely a SQL only server; try the NodesList endpoint.
> 		nodesList, err = zc.status.NodesList(ctx, &serverpb.NodesListRequest{})
> ```

if we know this is a SQL-only server should we just return from here? I got a bit confused about why the if clause below was overwriting the `nodesList` but I get that it's for storage/kv nodes only now.
___
*[pkg/cli/zip_cluster_wide.go, line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb79d6C3Yf2IrjQVdF:-Mwb79d6C3Yf2IrjQVdG:bewoet2) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip_cluster_wide.go#L206)):*
> ```Go
> 		nodesList, err = zc.status.NodesList(ctx, &serverpb.NodesListRequest{})
> 	}
> 	if err != nil {
> ```

this `err` gets overwritten sometimes by the `NodesList` call above...any way we can still catch the error messages from the `Nodes` call?
___
*[pkg/server/tenant_status.go, line 830 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MwYi-pdCh8ZL-yGCDfK:-MwYi-pdCh8ZL-yGCDfL:bf1wozc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/tenant_status.go#L830)):*
> ```Go
> func (t *tenantStatusServer) Stacks(
> 	ctx context.Context, request *serverpb.StacksRequest,
> ) (*serverpb.JSONResponse, error) {
> ```

should this one have an Admin permission check>?

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76539)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @knz, and @srosenberg)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvyVtZfBs6qKuwP6spk):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Any chance these can be split into 2 separate commits? I think it would make it easier to reason about which diffs are relevant.
</blockquote></details>

Done.
___
*[-- commits, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb4GiDEl2YKqhwHiAf):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

From reading this commit message I don't gain any understanding about what the problem was. Can you provide some more info here on what the issue is and why the `NodesList` API is inadequate while the `Nodes` API is.
</blockquote></details>

Done.
___
*[pkg/cli/zip.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MwbAZpa7UWZ5R2ldr6z:-Mwcnz0pCBfcuh7b8gyT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip.go#L99)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Consider adding a comment here that `nodeStatus` should be expected to be nil for valid SQL-only nodes.
</blockquote></details>

Done.
___
*[pkg/cli/zip.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MwYiYlL6W3kIZD2m3Ic:-Mwco4Fu8rK9zP1Z4UdB:b-seiuqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip.go#L105)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Are these guaranteed to match?  Just wondering if, for instance, one lists recently decommissioned nodes and another does not. It's possible the count may not match in exactly those situations where we take a debug.zip so just want to check.
</blockquote></details>

Yes, it is guaranteed to match since the nodeListResponse is constructed from the nodeStatusResponse on storage servers.
___
*[pkg/cli/zip_cluster_wide.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mvyj8LW2h01XYbs1Jid:-MwcoCrJ81vl6uAAeN4h:b-gp0zm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/cli/zip_cluster_wide.go#L201)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Should this also include some kind of `err != nil` check?
</blockquote></details>

The nil check does happen subsequently. So, we first check to see if the error is an unimplemented method error and if so, we try the new API. If not, then we perform the nil check below. The original error will get overwritten by the error returned by `NodesListRequest` in case the initial error was an unimplemented method error but that is intentional.
___
*[pkg/cli/zip_cluster_wide.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb64T9Ch4WZVkXxl62:-MwcoBcz1UriRhYQIUgN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip_cluster_wide.go#L118)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Nothing below is named `nodeDetails`. Can you clarify?
</blockquote></details>

Done.
___
*[pkg/cli/zip_cluster_wide.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb7kxHBWUOS0epVyTT:-MwcoczA8gxNQoT2uECZ:b-7m8tey) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip_cluster_wide.go#L204)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

if we know this is a SQL-only server should we just return from here? I got a bit confused about why the if clause below was overwriting the `nodesList` but I get that it's for storage/kv nodes only now.
</blockquote></details>

There is no way to know at this point whether the server is SQL only or not. So, we allow the method to complete execution.
___
*[pkg/cli/zip_cluster_wide.go, line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mwb79d6C3Yf2IrjQVdF:-MwcopZABWnHRNu-kcAF:beisoa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c7cf56063858bac2e522a16d9d813db8033f82/pkg/cli/zip_cluster_wide.go#L206)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

this `err` gets overwritten sometimes by the `NodesList` call above...any way we can still catch the error messages from the `Nodes` call?
</blockquote></details>

Thats intentional. The only time the error will get overwritten if the original call to `NodesRequest` returns an unimplemented error indicating this is a SQL only server.
___
*[pkg/server/tenant_status.go, line 830 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MwYi-pdCh8ZL-yGCDfK:-MwcpDCbCdcM4K5JcI3_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/tenant_status.go#L830)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

should this one have an Admin permission check>?
</blockquote></details>

Done.
___
*[pkg/server/status_util.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvyamuM6_Td6KuAZzjg:-Mwcp0tA9vj8ujBqen3-:b3yqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/status_util.go#L31)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: For this fn and the 2 below, would it make sense to try and decouple the params list from the request objects? It might help keep them flexible to be used elsewhere in the future - or do we *want* them to be coupled? :thinking:  
</blockquote></details>

I have intentionally couple it with the request types as these methods are meant to be helper methods to both the tenant and storage status servers. I don't want these methods to be used as general purpose util methods.
___
*[pkg/server/status_util.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvygOsOAnGsYJIXT0Qz:-MwcpBo99V0-NvWIjrNB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/status_util.go#L97)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Yay! This means we should get active query dumps in tenant debug.zip's for each SQL server instance. :tada: 
</blockquote></details>

Done.
___
*[pkg/server/status_util.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73Qog57fr8b_0MTLo:-MwcozeJBFPaAuWp-Csb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

file name: `status_local_file_retrieval.go`

(The name `_util.go` suggests this should become a dumping ground. Let's avoid creating that impression.)
</blockquote></details>

Done.
___
*[pkg/server/status_util.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73d1gAyqzxx7R-y-S:-Mwcp-xd5O0pk6-A0bNI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L30)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Here and below: explain whether each function returns a gRPC error or not.
</blockquote></details>

Done.
___
*[pkg/server/status_util.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73m0N2aGY0ReIl1Oc:-MwcpAhr0ujiaJTwQPV3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L47)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what about this err return
</blockquote></details>

Done.
___
*[pkg/server/status_util.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mw73k7D16yRnlNRD-Hh:-MwcpB8r3uIrfyEQAIDx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae8b49bdf15b2aadfc19cbd48750e7337e9a4b28/pkg/server/status_util.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what about this err return
</blockquote></details>

Done.

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-:-MwgYdlPEvzAxV29Djt8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @knz, @rimadeodhar, and @srosenberg)

___
*[pkg/cli/zip_cluster_wide.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-Mvyj8LW2h01XYbs1Jid:-MwgYQjjDA3Mtho7ivWj:b-7f3iu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/cli/zip_cluster_wide.go#L201)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

The nil check does happen subsequently. So, we first check to see if the error is an unimplemented method error and if so, we try the new API. If not, then we perform the nil check below. The original error will get overwritten by the error returned by `NodesListRequest` in case the initial error was an unimplemented method error but that is intentional.
</blockquote></details>

I see, thanks for clarifying. SGTM!
___
*[pkg/server/status_util.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76539#-MvyamuM6_Td6KuAZzjg:-MwgYXuyEZibLzPQs1MA:b-785cyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9101acb25b3ec951d62859ec97fd520210dd5eb8/pkg/server/status_util.go#L31)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I have intentionally couple it with the request types as these methods are meant to be helper methods to both the tenant and storage status servers. I don't want these methods to be used as general purpose util methods.
</blockquote></details>

:thumbsup: Sounds good to me.

**Review by dhartunian — APPROVED** [review]
> Reviewed 4 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76539)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @knz, @rimadeodhar, and @srosenberg)

**Comment by rimadeodhar** [comment]
TFTR!

bors r+

**Comment by rimadeodhar** [comment]
Retrying merge.

bors r+

**Pull request merged**
