### PR TITLE
backup,sql/importer,sql: pause job if a node is running out of disk

### PR DESCRIPTION
**Pull request by dt**
See commits.

Significantly friendlier with #78543.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @stevendanna)

___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78546#-Mz6ERb89TLdkSbRkCO2:-Mz6ERb89TLdkSbRkCO3:b-fqbx99) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c881c19e33a502402ab51c129c1f7c72c4a82f2/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L80)):*
> ```Go
> 	settings.SystemOnly,
> 	"kv.bulk_io_write.min_capacity_remaining_fraction",
> 	"remaining store capacity fraction below which an addsstable request is rejected",
> ```

nit: comment that anything <=0 disables?
___
*[pkg/roachpb/errors.proto, line 718 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78546#-Mz6EBNcDjxhzTu4d5XR:-Mz6EBNcDjxhzTu4d5XS:b-arz2pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c881c19e33a502402ab51c129c1f7c72c4a82f2/pkg/roachpb/errors.proto#L718)):*
> ```protobuf
> 
> // InsufficientSpaceError is an error due to insufficient space remaining.
> message InsufficientSpaceError {
> ```

does addition of this error type require version gate?
___
*[pkg/roachpb/errors.proto, line 734 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78546#-Mz6EGZ50YUQoMDzBDRZ:-Mz6EGZ50YUQoMDzBDR_:bvg9m5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c881c19e33a502402ab51c129c1f7c72c4a82f2/pkg/roachpb/errors.proto#L734)):*
> ```protobuf
>    // RequiredFraction is the required remaining capacity fraction.
>    optional double required = 5 [(gogoproto.nullable) = false];
> }
> ```

nit: spaces after '}'?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78546#-Mz6ERb89TLdkSbRkCO2:-Mz6G7h0441X9AHLSxJs:b-ykozcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c881c19e33a502402ab51c129c1f7c72c4a82f2/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L80)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: comment that anything <=0 disables?
</blockquote></details>

heh, I thought about that but then elected against it since that is just implied by the definition

(also: this file was in the other PR and already merged)
___
*[pkg/roachpb/errors.proto, line 718 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78546#-Mz6EBNcDjxhzTu4d5XR:-Mz6GZ38Dlt0o4yBSgQj:bioroym) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c881c19e33a502402ab51c129c1f7c72c4a82f2/pkg/roachpb/errors.proto#L718)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

does addition of this error type require version gate?
</blockquote></details>

don't think so, it just will be an untyped opaque error on older nodes. 

I do _not_ want a gate since I'm aiming for 21.x backports.

(also: this file was in the other PR and already merged)
___
*[pkg/roachpb/errors.proto, line 734 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78546#-Mz6EGZ50YUQoMDzBDRZ:-Mz6Gvm30On5YDzsTDW3:b-3tqw0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c881c19e33a502402ab51c129c1f7c72c4a82f2/pkg/roachpb/errors.proto#L734)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: spaces after '}'?
</blockquote></details>

This file was in the other PR and already merged. Oh well, I'll get it later.

**Comment by dt** [comment]
As mentioned in the inline replies, all the comments were on changes that merged in #78541, so as far as what's in this one I think we're all set. 

TFTR!

bors r+

**Comment by dt** [comment]
blathers backport 22.1

**Pull request merged**
