### PR TITLE
Makefile: unbreak the fresh-checkout build

### LINKED ISSUE #45976: Makefile: circular dependency
I am currently debugging the `Makefile` because a fresh clone of the repo does not build any more.

The proximate symptom is that the `vendor` tree is not ready when the first Go target is being built.

I found the following:

1. Makefile includes build/deps.mk
2. build rule for deps.mk depends on deps.mk.sig
3. build rule for deps.mk.sig depends on variable definitions in Makefile
4. var defs depend on the contents of deps.mk being included at step (1)

It's because of the circular dependency (which make cannot resolve) that the target bin/.submodules-initialized does not get processed properly.

### PR DESCRIPTION
**Pull request by knz**
Fixes #45976

Release justification: Category 1: Non-production code changes

### CODE REVIEW

**Comment by knz** [comment]
(I manually checked that `make` does the right thing when invoked on a fresh checkout.)

**Comment by knz** [comment]
nb: CI fails because the Docker image used to run `verify-archive.sh` uses a severely outdated GNU make. Looking into it.

**Review by tbg — APPROVED** [review]

**Comment by tbg** [comment]
Oof, LGTM but I definitely don't understand anything but the high-level picture here.

**Comment by knz** [comment]
I fixed the old make compat problem + another typo found by the verify-archives script. Now waiting for green CI.

**Comment by knz** [comment]
verify-archive took forever (30mn) because the deps.mk was being re-generated multiple times with the same contents. added a `cmp` invocation in there to avoid that.

**Comment by knz** [comment]
@petermattis if you happen to see this in the coming 20mn (the time for a CI run) I'd love if you could have a 2nd look.

**Comment by petermattis** [comment]
I’ll be able to take a look around 8-8:30am ET.

**Comment by knz** [comment]
ok I'll wait until then

**Review by petermattis — COMMENTED** [review]
Can you remind me what the difference is between “include” and “-include”? Looking at this on my phone without easy access to docs.

**Comment by knz** [comment]
`include` mandates the file to exist (incl generating it if it does not exist but there's a rule for it)

`-include` tries do do like `include`, but if that fails ignores the error.

**Review by petermattis — COMMENTED** [review]
I'm having a bit of trouble deciphering what actually changed vs what is movement. Was the rule movement actually necessary? See my comment about rule ordering being insignificant.

(I'm still working through what this PR is doing, despite this).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-:-M28_hhhBhQrMCyQsFyA:b-9q49vp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[Makefile, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-M28_QRi8xIRWwEIgCvI:-M28_QRi8xIRWwEIgCvJ:bnfwzbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd334ce462393aa38e61d5dda5651115d13b4b5/Makefile#L23)):*
> ```Makefile
> # improvements!
> 
> # We need to define $(GO) early because it's needed for defs.mk.
> ```

Similar to the comment below, this is at odds with my understanding of how make "executes" a file. 
___
*[Makefile, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-M28ZuXoCXou9rbZ0XlO:-M28ZuXoCXou9rbZ0XlP:b-t5auej) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd334ce462393aa38e61d5dda5651115d13b4b5/Makefile#L32)):*
> ```Makefile
> # noop builds.
> # This needs to be the first rule because we're including build/defs.mk
> # first thing below, and Make needs to know how to build it.
> ```

This comment is at odds with my understanding of rule ordering. The GNU make manual says: `The order of rules is not significant, except for determining the default goal: the target for make to consider, if you do not otherwise specify one.`

The order of `include` directives is important, though. I think it actually might be clearer to move all of the includes to one location in the `Makefile`. Usually I've seen them performed at the very end.

**Comment by knz** [comment]
If that makes your review easier, I can move the lines of Makefile in a separate commit from where they are modified.

Here's the rationale for the rest of the change:

1) `include` order not only matters; it actually blocks further processing of the Makefile.

> The include directive tells make to suspend reading the current makefile and read one or more other makefiles before continuing. 
> https://www.gnu.org/software/make/manual/make.html#Include

Given that the `include build/defs.mk` was at the beginning, its dependencies needed to come first.

2) the order of var assignments with `:=` matter. These assignments are effective "immediately" and impact all subsequent text in the `Makefile`

There a plenty of vars at the beginning, like `SUFFIX := $(GOEXE)` that need their var dependencies to be set yet. In this case they come from `defs.mk`.

3) we have plenty of _rules_ (where the target or the dependency) is expressed using a make variable defined previously with `:=`.

Therefore, I don't think we are at liberty of simply moving all the `includes` at the end. 

I did move the one include where it didn't matter though (variables.mk)

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[Makefile, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-M28az3G-gmq1GBAgXmS:-M28az3G-gmq1GBAgXmT:b9ey1iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd334ce462393aa38e61d5dda5651115d13b4b5/Makefile#L59)):*
> ```Makefile
> # on it, we'll have it listed first thing.
> #
> # Note how the actions for this rule are *not* using $(GIT_DIR) which
> ```

Is this what is actually fixing the problem? I'm also not clear if this is necessary. You've switched to using `include build/defs.mk` which will ensure that we actually include that file while previously that rule would have been skipped if `build/defs.mk` didn't exist. Regardless, I think this is cleaner than what was present before because I think it is better to encode logic inside rules, rather than in how the rules are defined.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[Makefile, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-M28_QRi8xIRWwEIgCvI:-M28bfU5BlGC4IS85rV5:b-n6r8uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd334ce462393aa38e61d5dda5651115d13b4b5/Makefile#L23)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Similar to the comment below, this is at odds with my understanding of how make "executes" a file. 
</blockquote></details>

see my response in previous comment
___
*[Makefile, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-M28ZuXoCXou9rbZ0XlO:-M28bhA9AFuBej0yoSY9:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd334ce462393aa38e61d5dda5651115d13b4b5/Makefile#L32)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This comment is at odds with my understanding of rule ordering. The GNU make manual says: `The order of rules is not significant, except for determining the default goal: the target for make to consider, if you do not otherwise specify one.`

The order of `include` directives is important, though. I think it actually might be clearer to move all of the includes to one location in the `Makefile`. Usually I've seen them performed at the very end. 
</blockquote></details>

ditto
___
*[Makefile, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-M28az3G-gmq1GBAgXmS:-M28bhso6ASTXQH_vitw:b-5joc0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd334ce462393aa38e61d5dda5651115d13b4b5/Makefile#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this what is actually fixing the problem? I'm also not clear if this is necessary. You've switched to using `include build/defs.mk` which will ensure that we actually include that file while previously that rule would have been skipped if `build/defs.mk` didn't exist. Regardless, I think this is cleaner than what was present before because I think it is better to encode logic inside rules, rather than in how the rules are defined.
</blockquote></details>

It is fixing _one_ of the problems, specifically that of "having to run make twice, because the first time didn't work".

**Comment by knz** [comment]
FYI The order-agnosticism of `make` is only for makefile that are disciplined about 

1) assigning all vars with `=` and not `:=` (we do `:=` for performance, but it's really antithetical to make's 'all var definitions should be pure' principle)
2) including all their files at the end
3) therefore,  not using the content of included files to define variables used in the main makefile

**Review by petermattis — COMMENTED** [review]
> If that makes your review easier, I can move the lines of Makefile in a separate commit from where they are modified.

This would definitely be helpful.

> FYI The order-agnosticism of make is only for makefiles that are disciplined about

Ok, thanks for talking this through. Gah, I dislike `make`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-:-M28cl1X5Qwl4AWGF8to:b-wnupsb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

**Comment by knz** [comment]
> This would definitely be helpful.

ok I'm doing this now

**Comment by knz** [comment]
I split the commits as requested; RFAL

**Review by petermattis — APPROVED** [review]
:lgtm: Thanks for splitting this up. Much clearer what is being done.

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-:-M28igug86TXrCV2WE9i:bnxxyy8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @petermattis)

___
*[Makefile, line 837 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45977#-M28iLu75NPhWHIbnzLp:-M28iLu75NPhWHIbnzLq:b8oqnri) ([raw file](https://github.com/cockroachdb/cockroach/blob/c28904eabc58bd3dc6e7cefa608668f64fd7dbfd/Makefile#L837)):*
> ```Makefile
> execgen-exclusions = $(addprefix -not -path ,$(EXECGEN_TARGETS))
> 
> $(shell build/cleanup.sh $(execgen-exclusions))
> ```

Tangential to this PR: I feel there must be a better way to do this cleanup.

**Comment by knz** [comment]
> Tangential to this PR: I feel there must be a better way to do this cleanup.

That'd need a way to guarantee a script to be called on every git branch change. I don't know how to do that.

**Comment by knz** [comment]
bors r=petermattis,tbg

**Pull request merged**
