### PR TITLE
opt: support selecting any table column when grouping by PK

### LINKED ISSUE #26709: sql: group by does not conform with postgres
org.hibernate.userguide.hql.HQLTest test_hql_group_by_example_3 fails

```sql
create table Phone (
   id int8 not null,
    phone_number varchar(255),
    phone_type varchar(255),
    person_id int8,
    order_id int4,
    primary key (id)
);
create table phone_call (
   id int8 not null,
    duration int4 not null,
    call_timestamp timestamp,
    phone_id int8,
    primary key (id)
);
create table Person (
   id int8 not null,
    address varchar(255),
    createdOn timestamp,
    name varchar(255),
    nickName varchar(255),
    version int4 not null,
    primary key (id)
);
select
    person2_.id as col_0_0_,
    sum(call0_.duration) as col_1_0_,
    person2_.id as id1_2_,
    person2_.address as address2_2_,
    person2_.createdOn as createdO3_2_,
    person2_.name as name4_2_,
    person2_.nickName as nickName5_2_,
    person2_.version as version6_2_ 
from
    phone_call call0_ 
inner join
    Phone phone1_ 
        on call0_.phone_id=phone1_.id 
inner join
    Person person2_ 
        on phone1_.person_id=person2_.id 
group by
    person2_.id;
```

This should parse and execute, but instead it produces
`ERROR: column "address" must appear in the GROUP BY clause or be used in an aggregate function`

From the postgres docs: 
> When GROUP BY is present, or any aggregate functions are present, it is not valid for the SELECT list expressions to refer to ungrouped columns except within aggregate functions or when the ungrouped column is functionally dependent on the grouped columns, since there would otherwise be more than one possible value to return for an ungrouped column. A functional dependency exists if the grouped columns (or a subset thereof) are the primary key of the table containing the ungrouped column.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: clean up optbuilder group-by code

This refactoring cleans up some aspects of the group-by code in the
optbuilder.

Currently each scope contains a set of fields (collected in the
`groupby` struct). But building an aggregation involves multiple
scopes and subsets of these fields are used by different scopes (e.g.
`aggs` is used on the `aggOutScope`). In addition, many helper
functions related to grouping are implemented by `*scope`, and you
have to know which of the scopes needs to be used for each one (even
worse, sometimes you need to pass around information like
`groupingsLen` because it's not all in one place).

This change addresses these issues. There is now a single `groupby`
structure per grouping context and it is now a pointer inside the
`scope`. All related functionality has been moved as methods on this
structure.

Release note: None

#### opt: support selecting any table column when grouping by PK

Postgres supports selecting columns that are not grouping columns if
the entire PK is part of the grouping columns (see
https://www.postgresql.org/docs/current/sql-select.html#SQL-GROUPBY).
This commit implements this feature, motivated by the desire for
compatibility with various ORMs.

We implement this feature by adding these columns as grouping columns
on-the-fly; in other words, we interpret `SELECT v FROM kv GROUP BY k`
as having `GROUP BY k,v` (which is equivalent). Normalization rules
will subsequently trim down the list of columns.

Fixes #26709.

Release note (sql change): It is now valid for SELECT and HAVING to
refer to ungrouped columns in the special case when the grouped
columns contain the primary key of the table containing the ungrouped
column.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
I am not fond of this "feature" :( but :lgtm: in the name of PG compat!

> Reviewed 5 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-:-LrjC3Tw6VaxyuiDQQHC:b-svp9ue)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by RaduBerinde** [comment]
TFTR! I wasn't fond of it either, but I'm coming around - I think there are some usecases where it makes sense. For example: `SELECT t.k, t.v, COUNT(*) FROM t JOIN other ON .. GROUP BY t.k` if you want to figure out how many join "matches" each row has. It's tedious (and clearly unnecessary) to have to add all selected values to the `GROUP BY`

**Review by rytaft — COMMENTED** [review]
First commit :lgtm:, will finish reviewing the second one tomorrow morning.

> Reviewed 5 of 5 files at r1, 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-:-LrlbFn41AHwRQvz4qEY:b-odgkbt)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-LrlWrEV2Z-WnRi5NrJy:-LrlWrEV2Z-WnRi5NrJz:b-ngf088) ([raw file](https://github.com/cockroachdb/cockroach/blob/3572d1057a9626c065c7152f2307c8b53d5dc828/pkg/sql/opt/optbuilder/groupby.go#L136)):*
> ```Go
> // getAggregateArgCols returns the columns in the aggInScope corresponding to
> // arguments to aggregate functions. If the aggregate has a filter, the column
> // corresponding to its input will immediately follow its inputs.
> ```

"its" is used multiple times here -- I think to refer to different things. Is one of them the aggregate and one the filter? (I know you just copied this over... but seems like a good opportunity to improve it :) )
___
*[pkg/sql/opt/optbuilder/groupby.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-LrlZl0S3U9ltUxsvfqs:-LrlZl0S3U9ltUxsvfqt:b-mh0lsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3572d1057a9626c065c7152f2307c8b53d5dc828/pkg/sql/opt/optbuilder/groupby.go#L458)):*
> ```Go
> //          indicates that the grouping is on the second select expression, k.
> //
> // See Builder.buildStmt for a description of the remaining input values.
> ```

[nit] this comment to see `Builder.buildStmt` is less useful with different scope names. I'd just remove the comment here and below (but maybe also add `fromScope` with a brief description to the list of params above).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41732)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-LrlWrEV2Z-WnRi5NrJy:-LrnikK-7k0H_coAXNOM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3572d1057a9626c065c7152f2307c8b53d5dc828/pkg/sql/opt/optbuilder/groupby.go#L136)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

"its" is used multiple times here -- I think to refer to different things. Is one of them the aggregate and one the filter? (I know you just copied this over... but seems like a good opportunity to improve it :) )
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-LrlZl0S3U9ltUxsvfqs:-LrnkMm_4VLkDQ08T1HL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3572d1057a9626c065c7152f2307c8b53d5dc828/pkg/sql/opt/optbuilder/groupby.go#L458)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] this comment to see `Builder.buildStmt` is less useful with different scope names. I'd just remove the comment here and below (but maybe also add `fromScope` with a brief description to the list of params above).
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-:-Lro5B1I7muVEcDW4V9b:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 3485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-Lro4JHj9zFR3uXNCU2_:-Lro4JHj9zFR3uXNCU2a:be7dgi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/932992e40cd68500b9e790b7a2b465cfef902b19/pkg/sql/opt/optbuilder/testdata/aggregate#L3485)):*
> ```
> error (0A000): count(): json_each(): generator functions are not allowed in aggregate
> 
> # Tests for projecting non-grouping columns when we group by a PK.
> ```

Do you have any tests where you're grouping by a superset of the PK?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41732)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 3485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41732#-Lro4JHj9zFR3uXNCU2_:-Lroa7gq-hBe-80Er48a:b-2ymw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/932992e40cd68500b9e790b7a2b465cfef902b19/pkg/sql/opt/optbuilder/testdata/aggregate#L3485)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you have any tests where you're grouping by a superset of the PK?
</blockquote></details>

Good idea, added.

**Pull request merged**
