### PR TITLE
builtins: add parse and to_char_with_style variants for date types

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1864 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEOivYBEV5ypq70jQF:-MgEOivYBEV5ypq70jQG:b-m60wcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a58dbdc7069e0444d9b8afc80c5ec21bf7aac086/pkg/sql/logictest/testdata/logic_test/datetime#L1864)):*
> ```
> SELECT
>   parse_timestamp(s),
>   parse_timestamp(s, 'iso,mdy'),
> ```

should this also work with just `parse_timestamp(s, 'mdy')` ?
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1887 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEQMEs3gF68SMBjljO:-MgEQMEs3gF68SMBjljP:b-dk96k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/68c21d6a802ad6fea77d0df834e63bdc5cae4fad/pkg/sql/logictest/testdata/logic_test/datetime#L1887)):*
> ```
>   parse_date(s, 'iso,mdy'),
>   parse_date(s, 'iso,dmy'),
>   parse_date(s, 'iso,ymd')
> ```

similar, should this work with `parse_date(s, 'mdy')` etc?
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1908 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEROSH45rnWfXKjAv-:-MgEROSH45rnWfXKjAv0:b-sx14v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6e2f8418e306b3a0cff7da6efb487b7640ecb4d/pkg/sql/logictest/testdata/logic_test/datetime#L1908)):*
> ```
> INSERT INTO time_datestyle_parse VALUES
>   (1, '2007-09-12 11:30:45.123+06'),
>   (2, '2007-09-12 11:30:45.123+03')
> ```

how does DMY ordering affect these tests?
___
*[pkg/sql/logictest/testdata/logic_test/interval, line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgENnPE8RI5-h41X31u:-MgENnPE8RI5-h41X31v:bftgfcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca8ca2cb6eab5c67a8b9df5ecf4b04b8d6cd0b8/pkg/sql/logictest/testdata/logic_test/interval#L456)):*
> ```
>     to_char_with_style(i, 'iso_8601') AS iso,
>     to_char_with_style(i, 'sql_standard') AS sql_std,
>     to_char_with_style(i) AS default_std
> ```

nit: why `default_std`? a name like `default_style` makes more sense to me
___
*[pkg/sql/logictest/testdata/logic_test/interval, line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEO--uAtCCwZBnfD-c:-MgEO--uAtCCwZBnfD-d:b-vzxnza) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca8ca2cb6eab5c67a8b9df5ecf4b04b8d6cd0b8/pkg/sql/logictest/testdata/logic_test/interval#L463)):*
> ```
>   iso,
>   sql_std,
>   default_std,
> ```

could also add a check for making sure `pg == default_std`
___
*[pkg/sql/sem/builtins/builtins.go, line 2358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgENhJ871ej54jlh_aR:-MgENhJ871ej54jlh_aS:byls4nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca8ca2cb6eab5c67a8b9df5ecf4b04b8d6cd0b8/pkg/sql/sem/builtins/builtins.go#L2358)):*
> ```Go
> 				return tree.NewDString(buf.String()), nil
> 			},
> 			Info:       "Convert an interval to a string assuming the Postgres IntervalStyle.",
> ```

hm, the name `to_char_with_style` might be a bit confusing given that it doesn't actually take a `style` param. is it better to name it `to_char`?
___
*[pkg/sql/sem/builtins/builtins.go, line 2391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEP1At0NL5-m30S520:-MgEP1At0NL5-m30S521:b-55lsg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a58dbdc7069e0444d9b8afc80c5ec21bf7aac086/pkg/sql/sem/builtins/builtins.go#L2391)):*
> ```Go
> 				return tree.NewDString(tree.AsStringWithFlags(&ts, tree.FmtBareStrings)), nil
> 			},
> 			Info:       "Convert an timestamp to a string assuming the ISO, MDY DateStyle.",
> ```

similar to other comment: `to_char_with_style` without a style parameter might be confusing
___
*[pkg/sql/sem/builtins/builtins.go, line 2394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEPdyg1fnnidyTdqLm:-MgEPdyg1fnnidyTdqLn:bs96i1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a58dbdc7069e0444d9b8afc80c5ec21bf7aac086/pkg/sql/sem/builtins/builtins.go#L2394)):*
> ```Go
> 			Volatility: tree.VolatilityImmutable,
> 		},
> 		tree.Overload{
> ```

should all these two-arg overloads use `stringOverload2()`?
___
*[pkg/sql/sem/builtins/builtins.go, line 2419 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEQa7F3fnaCRd_gBnE:-MgEQa7F3fnaCRd_gBnF:b8txm52) ([raw file](https://github.com/cockroachdb/cockroach/blob/68c21d6a802ad6fea77d0df834e63bdc5cae4fad/pkg/sql/sem/builtins/builtins.go#L2419)):*
> ```Go
> 				return tree.NewDString(tree.AsStringWithFlags(&ts, tree.FmtBareStrings)), nil
> 			},
> 			Info:       "Convert an date to a string assuming the ISO, MDY DateStyle.",
> ```

similar: `to_char_with_style` without a style param might be confusing
___
*[pkg/sql/sem/tree/datum.go, line 1865 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEQrwJ1xcrABeEVudL:-MgEQrwJ1xcrABeEVudM:bvmfrqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/68c21d6a802ad6fea77d0df834e63bdc5cae4fad/pkg/sql/sem/tree/datum.go#L1865)):*
> ```Go
> // be used instead of direct type assertions wherever a *DDate wrapped by a
> // *DOidWrapper is possible.
> func AsDDate(e Expr) (DDate, bool) {
> ```

where is `AsDDate` used, and also when would `*DDate` be wrapped by `DOidWrapper`?

**Review by rafiss — APPROVED** [review]
lgtm! though maybe you have some unpublished reviewable comments?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-:-MgSPq9d-oCeQuQxrbRq:b-cvm3j2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by otan — COMMENTED** [review]
ah oops

> Dismissed @rafiss from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-:-Mgbgas-5IY4dq1KgP6f:bhes3o7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1864 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEOivYBEV5ypq70jQF:-MgF0SPG4Rs0dX175CBJ:b63jfn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a58dbdc7069e0444d9b8afc80c5ec21bf7aac086/pkg/sql/logictest/testdata/logic_test/datetime#L1864)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this also work with just `parse_timestamp(s, 'mdy')` ?
</blockquote></details>

yeah it all works. did you want me to test all 9 perms? :P the parse function is relatively well unit tested.
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1887 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEQMEs3gF68SMBjljO:-MgF0ZvF-fTDgYO6m-sr:bbw4h2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/68c21d6a802ad6fea77d0df834e63bdc5cae4fad/pkg/sql/logictest/testdata/logic_test/datetime#L1887)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar, should this work with `parse_date(s, 'mdy')` etc?
</blockquote></details>

see above.
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1908 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEROSH45rnWfXKjAv-:-MgF5x5kDlj3RgzeQZQr:bwgwk7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6e2f8418e306b3a0cff7da6efb487b7640ecb4d/pkg/sql/logictest/testdata/logic_test/datetime#L1908)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

how does DMY ordering affect these tests?
</blockquote></details>

in reality none. in theory, validation of the dates.
___
*[pkg/sql/logictest/testdata/logic_test/interval, line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEO--uAtCCwZBnfD-c:-MgF1b8k4Mf_-htZVYCI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca8ca2cb6eab5c67a8b9df5ecf4b04b8d6cd0b8/pkg/sql/logictest/testdata/logic_test/interval#L463)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could also add a check for making sure `pg == default_std`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgENhJ871ej54jlh_aR:-MgF1cad2nVbeSZNXteA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca8ca2cb6eab5c67a8b9df5ecf4b04b8d6cd0b8/pkg/sql/sem/builtins/builtins.go#L2358)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, the name `to_char_with_style` might be a bit confusing given that it doesn't actually take a `style` param. is it better to name it `to_char`?
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEPdyg1fnnidyTdqLm:-MgF0LNw7UJe4ANJ6X0z:bkp87hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a58dbdc7069e0444d9b8afc80c5ec21bf7aac086/pkg/sql/sem/builtins/builtins.go#L2394)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should all these two-arg overloads use `stringOverload2()`?
</blockquote></details>

i liked named args, so i'm going to keep it this way.
___
*[pkg/sql/sem/builtins/builtins.go, line 2419 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEQa7F3fnaCRd_gBnE:-MgF3mqj0l11sQRQcpZS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68c21d6a802ad6fea77d0df834e63bdc5cae4fad/pkg/sql/sem/builtins/builtins.go#L2419)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar: `to_char_with_style` without a style param might be confusing
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/datum.go, line 1865 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68351#-MgEQrwJ1xcrABeEVudL:-MgF0CkB9UnWYgtz7K2I:b9bs0sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/68c21d6a802ad6fea77d0df834e63bdc5cae4fad/pkg/sql/sem/tree/datum.go#L1865)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

where is `AsDDate` used, and also when would `*DDate` be wrapped by `DOidWrapper`?
</blockquote></details>

this is used by `MustBeDDate`, and i'm just copying what all the other `AsD<datum>` things are doing. Not sure!

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
