### PR TITLE
sql: don't re-decode index keys when unnecessary

### LINKED ISSUE #21565: sql: RowFetcher should avoid re-decoding index keys that are guaranteed to be the same
Currently, the RowFetcher doesn't take into account any prior information about the span that it's looking at. This causes a ton of unnecessary decoding and allocation activity in certain cases.

Consider the following table and query:

```
CREATE TABLE t (a TEXT PRIMARY KEY, b TEXT);

SELECT * FROM t WHERE a = 'this string is going to get decoded a million times';
```

The span generated for this query guarantees that column a will always be equal to the filter string. However, the `RowFetcher` doesn't know that currently, and decodes the index key's text (and inflates it into a Datum and EncDatum) once per row. This is very wasteful.

We should teach the RowFetcher to skip decoding columns stored in the key that are guaranteed not to change from row to row by virtue of the span's prefix.

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, in multi column family tables, the row fetcher would
unconditionally decode the prefix of every key, then check to see if
that prefix was identical to the last prefix to determine whether or not
a new row was found.

This commit reverses the order - first we check the prefix, so that if
it's identical to the last prefix, we can completely skip decoding the
key.

Fixes #21565.

```
name                     old time/op    new time/op    delta
CountTwoCF/Cockroach-24    51.3ms ± 1%    50.4ms ± 1%  -1.70%  (p=0.000 n=10+9)

name                     old alloc/op   new alloc/op   delta
CountTwoCF/Cockroach-24    6.97MB ± 0%    6.98MB ± 0%    ~     (p=0.515 n=10+8)

name                     old allocs/op  new allocs/op  delta
CountTwoCF/Cockroach-24     1.99k ± 2%     1.99k ± 1%    ~     (p=0.828 n=10+8)
```

I'm not sure why the benchmark results don't look better. In local
testing, I see more like a 10% improvement. Either way, this is an
unambiguous win.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Reason I found this, by the way, was trying to fix up the column rowfetcher from #31354 - this isn't completely out of the blue :)

**Comment by jordanlewis** [comment]
Ooh, looks like this fixes an ancient issue I filed: #21565.

**Review by asubiotto — APPROVED** [review]
This LGTM, but you might want to get solon's approval on this since I'm not too familiar with this code.

> Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31713#-:-LQ-PfXIB_BRdTNxl6-K:bsajit6)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by solongordon — APPROVED** [review]
Also confusing to me but looks good. One comment typo to fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31713#-:-LQ5XpzG6l7ub-boE4dF:b-xzh1v6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/row/fetcher.go, line 574 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31713#-LQ5VQqo0PryKM-p9MIX:-LQ5VQqo0PryKM-p9MIY:b-ysgqr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e19a42bc68b29ccb5f29cdc5207cec2af9677dd5/pkg/sql/row/fetcher.go#L574)):*
> ```Go
> 			// Skip decoding!
> 			// We must set the rowReadyTable to the currentTable like ReadIndexKey
> 			// would do. This will happen when we see 2 rows in a row with the same
> ```

2 rows in a row?

**Comment by jordanlewis** [comment]
bors r+

TFT(old)Rs!

**Pull request merged**
