### PR TITLE
Move replicas from decommissioning nodes

### PR DESCRIPTION
**Pull request by garvitjuniwal**
Please review the PR for overall approach. Will add unittests once we are happy with that.

### CODE REVIEW

**Comment by garvitjuniwal** [comment]
@petermattis @tschottdorf Can you please take a look?

**Comment by a-robinson** [comment]
Looks like a good approach! I have a few comments, but tests would be a good next step.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 224 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojuAJ-N9YxefRDsMgd:-KojuAJ-N9YxefRDsMge:b-eiqvb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L224)):*
> ```Go
> 		// the current replica count and the quorum of the desired replica count.
> 		neededQuorum := computeQuorum(need)
> 		priority := addMissingReplicaPriority + float64(neededQuorum-have)
> ```

I'm not sure how I feel about prioritizing this at the same level as ranges that are actually missing replicas, but I guess that the second `neededQuorum-have` component is sufficient to put decommissioning-related rebalances behind more urgent work.

Splitting the decommissioning logic into a separate conditional between this one and the `deadReplicas` might be a little clearer.

---

*[pkg/storage/allocator.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojuIq_pWprQVpI1mH7:-KojuIq_pWprQVpI1mH8:b-rv5uda) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L226)):*
> ```Go
> 		priority := addMissingReplicaPriority + float64(neededQuorum-have)
> 		if log.V(3) {
> 			log.Infof(ctx, "AllocatorAdd - need=%d, have=%d, priority=%.2f", need, have, priority)
> ```

Mind addition info to this log so that we can tell if this was triggered by decommissioning replicas?

---

*[pkg/storage/replicate_queue.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsKEbTWGtleAIrY6o:-KojsKEbTWGtleAIrY6p:barhcf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L331)):*
> ```Go
> 			log.Infof(ctx, "removing a replica")
> 		}
> 		// If there is any decommissioning replica, remove that first.
> ```

Unless I'm misunderstanding, we shouldn't need code here to handle this. `allocator.ComputeAction` should just return `AllocatorRemoveDead` if there's a decommissioned replica ready to be removed.

---

*[pkg/storage/replicate_queue.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsVhJrANd00njYdLo:-KojsVhJrANd00njYdLp:bqgkwvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L348)):*
> ```Go
> 		}
> 		if removeReplica.StoreID == repl.store.StoreID() {
> 			// TODO: Does this need special consideration in case of removing a
> ```

It shouldn't, since the new leaseholder will also know that the store has been decommissioned.

---

*[pkg/storage/store_pool.go, line 174 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojozYUp9h2mzQ1G4OF:-KojozYUp9h2mzQ1G4OG:b-831w90) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/store_pool.go#L174)):*
> ```Go
> 		return storeStatusDecommissioning
> 	case nodeStatusUnknown:
> 		// TODO(garvit): Do we need a new store status for decommissioning state?
> ```

Forget to remove this?

---

*[pkg/storage/store_pool.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojrAuUyvaw8QjSjBlx:-KojrAuVFZlI15hxuseF:b-9o0qar) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/store_pool.go#L396)):*
> ```Go
> 		detail := sp.getStoreDetailLocked(repl.StoreID)
> 		// Mark replica as dead if store is dead.
> 		switch detail.status(now, sp.timeUntilStoreDead.Get(), rangeID, sp.nodeLivenessFn) {
> ```

Looks like you forgot to add a case for `storeStatusDecommissioning` here (to add it to `deadReplicas`). If you add one, their removal should automatically be highly prioritized by the replicate queue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-:-KojuiFudg2wLswHqz55:b-di3un2)*

**Comment by tschottdorf** [comment]
Looks good!

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kom8FKdncN4QfO3m1kN:-Kom8FKdncN4QfO3m1kO:blkfhz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L230)):*
> ```Go
> 		return AllocatorAdd, priority
> 	}
> 	liveReplicas, deadReplicas := a.storePool.liveAndDeadReplicas(desc.RangeID, desc.Replicas)
> ```

now that `deadReplicas` contains decommissioning ones, rename the variable. Suggestion: `undesiredReplicas`.

---

*[pkg/storage/replicate_queue.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kom8pWULQ0SunRpWJUG:-Kom8pWULQ0SunRpWJUH:b-3glxwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L295)):*
> ```Go
> 		// larger quorum. For example, up-replicating from 1 to 2 replicas only
> 		// makes sense if it is possible to be able to go to 3 replicas.
> 		// NB: If willHave > need, then always allow up-replicating as that will be
> ```

nit: Add a (commented) newline above the `NB:`.

---

*[pkg/storage/replicate_queue.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsKEbTWGtleAIrY6o:-KomIIgyuI7-YNywkMss:b7embpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L331)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Unless I'm misunderstanding, we shouldn't need code here to handle this. `allocator.ComputeAction` should just return `AllocatorRemoveDead` if there's a decommissioned replica ready to be removed.
</blockquote></details>

It also seems that we shouldn't skip `filterUnremovableReplicas`. I agree with Alex' suggestion, but should we rename `AllocatorRemoveDead` to `AllocatorRemoveDeadOrDecommissioning` or something like that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-:-KomJiTl1ny7GSK1hynm:b-vs1prh)*

**Comment by garvitjuniwal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/storage/allocator.go, line 224 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojuAJ-N9YxefRDsMgd:-KonfYDPpc8EWDXCtxLl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L224)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'm not sure how I feel about prioritizing this at the same level as ranges that are actually missing replicas, but I guess that the second `neededQuorum-have` component is sufficient to put decommissioning-related rebalances behind more urgent work.

Splitting the decommissioning logic into a separate conditional between this one and the `deadReplicas` might be a little clearer.
</blockquote></details>

Done.

---

*[pkg/storage/allocator.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojuIq_pWprQVpI1mH7:-KonfZQ5TM8RzV57Ljxg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L226)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Mind addition info to this log so that we can tell if this was triggered by decommissioning replicas?
</blockquote></details>

Done.

---

*[pkg/storage/allocator.go, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kom8FKdncN4QfO3m1kN:-KonZSVijuLIoyeLuOZR:b-x0xcbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L230)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

now that `deadReplicas` contains decommissioning ones, rename the variable. Suggestion: `undesiredReplicas`.
</blockquote></details>

decommissioning replicas are neither in deadReplicas or liveReplicas. I added a separate function to return decommissioningReplicas from the storePool

---

*[pkg/storage/replicate_queue.go, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kom8pWULQ0SunRpWJUG:-KonfguHots-cQCEvxEs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L295)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

nit: Add a (commented) newline above the `NB:`.
</blockquote></details>

Done.

---

*[pkg/storage/replicate_queue.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsKEbTWGtleAIrY6o:-KonfoIQqLJlWKZz25Cy:bypckkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L331)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It also seems that we shouldn't skip `filterUnremovableReplicas`. I agree with Alex' suggestion, but should we rename `AllocatorRemoveDead` to `AllocatorRemoveDeadOrDecommissioning` or something like that?
</blockquote></details>

According to my understanding, decomm will not complete until the replica count on the decomming node reaches 0. Once you have a node that is decomming, we will start up-replicating ranges that have a necessary replica on a decomming node (this is done in the new case I added in allocator.ComputeAction). Once that is done, we will have an extra replica for that range, so the need > have case will be triggered and allocator.ComputeAction will return AllocatorRemove (which is really AllocatorRemoveExtra -- I could make this rename change if you guys want.)
Once the queue is processing that removal, I want to make sure that that decomming replica is the one that is selected for removal.

I agree with not skipping filterUnremovableReplicas and have made that change. Any better places for handling this case other than here?

---

*[pkg/storage/store_pool.go, line 174 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojozYUp9h2mzQ1G4OF:-Konhctl8g1E7nSfQj9Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/store_pool.go#L174)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Forget to remove this?
</blockquote></details>

Done.

---

*[pkg/storage/store_pool.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojrAuUyvaw8QjSjBlx:-KonhltITfy5uyFWplZK:b-4nbr7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/store_pool.go#L396)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Looks like you forgot to add a case for `storeStatusDecommissioning` here (to add it to `deadReplicas`). If you add one, their removal should automatically be highly prioritized by the replicate queue.
</blockquote></details>

I tried that approach first, but figured that we really need to up-replicate a range that has a decomming replica first, and then remove the decommed replica at ease later. I have also updated the docstring of this method to highlight this. Do you see any issues with the current approach?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968)*

**Comment by a-robinson** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kom8FKdncN4QfO3m1kN:-KorAXKvaexlnTc-zxgA:blmhvdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L230)):*
<details><summary><i>Previously, garvitjuniwal (Garvit Juniwal) wrote…</i></summary><blockquote>

decommissioning replicas are neither in deadReplicas or liveReplicas. I added a separate function to return decommissioningReplicas from the storePool
</blockquote></details>

We can discuss this more in the comment on store_pool.go, but if `liveAndDeadReplicas` doesn't include the decommissioning replicas, then the comment below shouldn't even mention "or decommissioning replicas".

---

*[pkg/storage/replicate_queue.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsKEbTWGtleAIrY6o:-KorAoBLRHv62die_Ab4:b314wvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L331)):*
<details><summary><i>Previously, garvitjuniwal (Garvit Juniwal) wrote…</i></summary><blockquote>

According to my understanding, decomm will not complete until the replica count on the decomming node reaches 0. Once you have a node that is decomming, we will start up-replicating ranges that have a necessary replica on a decomming node (this is done in the new case I added in allocator.ComputeAction). Once that is done, we will have an extra replica for that range, so the need > have case will be triggered and allocator.ComputeAction will return AllocatorRemove (which is really AllocatorRemoveExtra -- I could make this rename change if you guys want.)
Once the queue is processing that removal, I want to make sure that that decomming replica is the one that is selected for removal.

I agree with not skipping filterUnremovableReplicas and have made that change. Any better places for handling this case other than here?
</blockquote></details>

I think that both @tschottdorf and I were assuming that the code would "make sure that that decomming replica is the one that is selected for removal" by including decommissioning replicas in the list of dead replicas. Was there a particular reason not to do that?

---

*[pkg/storage/store_pool.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojrAuUyvaw8QjSjBlx:-KorA0AXCq44Kj4OPJAw:b1bo200) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/store_pool.go#L396)):*
<details><summary><i>Previously, garvitjuniwal (Garvit Juniwal) wrote…</i></summary><blockquote>

I tried that approach first, but figured that we really need to up-replicate a range that has a decomming replica first, and then remove the decommed replica at ease later. I have also updated the docstring of this method to highlight this. Do you see any issues with the current approach?
</blockquote></details>

Isn't that already handled by your change to `(*Allocator).ComputeAction`? It checks for decommissioning replicas that need to be replaced before checking for dead replicas that need to be removed, so I'd think that the up-replicating will always happen first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968)*

**Comment by a-robinson** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968)*

**Comment by garvitjuniwal** [comment]
I have added unittests for store_pool.go and allocator.go
I am not really sure how to test the new code in replicate_queue. I could not find the testcluster methods that would allow me to add a node to the cluster in decommissioning status. Any pointers?

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/storage/allocator.go, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kom8FKdncN4QfO3m1kN:-KotycAe3A9bYemfLZN5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/allocator.go#L230)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

We can discuss this more in the comment on store_pool.go, but if `liveAndDeadReplicas` doesn't include the decommissioning replicas, then the comment below shouldn't even mention "or decommissioning replicas".
</blockquote></details>

Done.

---

*[pkg/storage/replicate_queue.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsKEbTWGtleAIrY6o:-KotyeZrF5Y-N6I6WqPm:b4o0v5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L331)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I think that both @tschottdorf and I were assuming that the code would "make sure that that decomming replica is the one that is selected for removal" by including decommissioning replicas in the list of dead replicas. Was there a particular reason not to do that?
</blockquote></details>

The reason to not do that is the following case. For replication factor of 3, consider a range that has 4 replicas, 1 live, 1 decommissioning, 2 dead. If decommissioning replica is considered dead, we might end up removing it which would be really bad if that replica was our last chance of survival.

I made things clearer by introducing a new action AllocatorRemoveDecommissioning. Hope things are clearer now.

---

*[pkg/storage/replicate_queue.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsVhJrANd00njYdLo:-Kou--g1TIDZmcoiItRj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L348)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It shouldn't, since the new leaseholder will also know that the store has been decommissioned.
</blockquote></details>

Done.

---

*[pkg/storage/store_pool.go, line 396 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojrAuUyvaw8QjSjBlx:-Kou-7Sf4aXukmsvf49p:b-vompv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/store_pool.go#L396)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Isn't that already handled by your change to `(*Allocator).ComputeAction`? It checks for decommissioning replicas that need to be replaced before checking for dead replicas that need to be removed, so I'd think that the up-replicating will always happen first.
</blockquote></details>

That is correct. But there is an edge case of removing a decommissioned replica that was needed (see previous comment.) I think it is better to keep decommissioning replicas separate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-:-Kou-Z2FSfq03VqrzrL5:bkyruv2)*

**Comment by a-robinson** [comment]
I really like the new allocator test! Just a few more comments.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator_test.go, line 1940 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFnCuvVAdlAcKkln7P:-KpFnCuvVAdlAcKkln7Q:b-s2vgf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/allocator_test.go#L1940)):*
> ```Go
> 		if tcase.expectedAction != action {
> 			t.Errorf("Test case %d expected action %d, got action %d", i, tcase.expectedAction, action)
> 			continue
> ```

Why continue?

---

*[pkg/storage/allocator_test.go, line 2045 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFniC1u0eCYWQbkINh:-KpFniC1u0eCYWQbkINi:b-mvght1) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/allocator_test.go#L2045)):*
> ```Go
> 				},
> 			},
> 			expectedAction:  AllocatorRemoveDecommissioning,
> ```

This case concerns me. Removing the decommissioning node here effectively leaves the range without any room for further failures. It also seems like a bad sign that we'd remove a decommissioning replica before a dead replica. We should probably use the same `len(liveReplicas) >= quorum` logic as we do for dead replicas

---

*[pkg/storage/replicate_queue.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KojsKEbTWGtleAIrY6o:-KpFlOIFkxvfz46THKFS:b-azerai) ([raw file](https://github.com/cockroachdb/cockroach/blob/abd5889c2fc45a6c5205726617ab2fb1be95342c/pkg/storage/replicate_queue.go#L331)):*
<details><summary><i>Previously, garvitjuniwal (Garvit Juniwal) wrote…</i></summary><blockquote>

The reason to not do that is the following case. For replication factor of 3, consider a range that has 4 replicas, 1 live, 1 decommissioning, 2 dead. If decommissioning replica is considered dead, we might end up removing it which would be really bad if that replica was our last chance of survival.

I made things clearer by introducing a new action AllocatorRemoveDecommissioning. Hope things are clearer now.
</blockquote></details>

Good point, thanks for being patient and explaining.

---

*[pkg/storage/replicate_queue.go, line 73 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFlaVzQIyZUdOuc5Mj:-KpFlaVzQIyZUdOuc5Mk:bgfjh6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/replicate_queue.go#L73)):*
> ```Go
> 	RemoveReplicaCount                *metric.Counter
> 	RemoveDeadReplicaCount            *metric.Counter
> 	RemoveDecommissioningReplicaCount *metric.Counter
> ```

Do you have any particular uses in mind for this metric? I'm a little torn on whether it's worth tracking. Every new metric costs a little extra resource usage within the cluster, and I'm not sure whether this would be useful to anyone.

---

*[pkg/storage/replicate_queue.go, line 387 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFm3Rb-SbjwD7MJoxN:-KpFm3Rb-SbjwD7MJoxO:b-juevgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/replicate_queue.go#L387)):*
> ```Go
> 		}
> 		decommissioningReplicas := rq.allocator.storePool.decommissioningReplicas(desc.RangeID, desc.Replicas)
> 		decommissioningReplica := decommissioningReplicas[0]
> ```

This could cause a panic if it got removed between `ComputeTarget` and here. We need to revalidate that it's not empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-:-KpFoaVRFy7krjNBlmMs:b-ud9ymz)*

**Comment by a-robinson** [comment]
Need any further help with this, @garvitjuniwal?

**Comment by garvitjuniwal** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/storage/allocator_test.go, line 1940 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFnCuvVAdlAcKkln7P:-Kpu-upgbU7-revjuJpt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/allocator_test.go#L1940)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why continue?
</blockquote></details>

Done.

---

*[pkg/storage/allocator_test.go, line 2045 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFniC1u0eCYWQbkINh:-KpvIzek3iw2xGgXadMa:bqccwf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/allocator_test.go#L2045)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This case concerns me. Removing the decommissioning node here effectively leaves the range without any room for further failures. It also seems like a bad sign that we'd remove a decommissioning replica before a dead replica. We should probably use the same `len(liveReplicas) >= quorum` logic as we do for dead replicas
</blockquote></details>

Done.
Changed to RemoveDead in case there is a dead replica and have > need.
also move lr >= quorum condition before all removal actions.

---

*[pkg/storage/replicate_queue.go, line 73 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFlaVzQIyZUdOuc5Mj:-KpvJRp_Fcy0nd290_zT:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/replicate_queue.go#L73)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Do you have any particular uses in mind for this metric? I'm a little torn on whether it's worth tracking. Every new metric costs a little extra resource usage within the cluster, and I'm not sure whether this would be useful to anyone.
</blockquote></details>

removed

---

*[pkg/storage/replicate_queue.go, line 387 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-KpFm3Rb-SbjwD7MJoxN:-KpvKCy5Nl6W_8tdbw4E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01dd0c6353dbf6aa502ff1b70c28e3c031192236/pkg/storage/replicate_queue.go#L387)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This could cause a panic if it got removed between `ComputeTarget` and here. We need to revalidate that it's not empty.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968)*

**Comment by a-robinson** [comment]
:lgtm:

Let me know if you run into problems with the additional test you said you're working on!

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-:-KpzEkPGjEA90gG72sUa:bll2dqg)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r5.
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 2471 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kq3ahy5Z3NJxsP_q7VZ:-Kq3ahy5Z3NJxsP_q7V_:b-utiswl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2defa44c0548559481513d463036ceb84d022a7d/pkg/storage/client_raft_test.go#L2471)):*
> ```Go
> 			return errors.Errorf("Expected 3 replicas, got %v", curReplicas)
> 		}
> 		if reflect.DeepEqual(origReplicas, curReplicas) {
> ```

It'd be nice to test that the decommissioning node is the one whose replica been removed, since any movement of replicas will pass the test as currently written.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-:-Kq3atp90w8UEE0fQ_Ct:bnfp4nl)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 2460 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968#-Kq8Pn1BQfw_CbIHYGDo:-Kq8Pn1BQfw_CbIHYGDp:b2mt76) ([raw file](https://github.com/cockroachdb/cockroach/blob/78046a3c2d9a273b762715b5ccb4c83503f423e2/pkg/storage/client_raft_test.go#L2460)):*
> ```Go
> 		SetDecommissioning(ctx, decommingNodeID, true)
> 
> 	replacementNodeIdx := 2
> ```

I'm.... confused by this. Why is it ok to use the same index here as for the decommissioning node? And how is it possible that the replica ID doesn't change when a replica is added to the replacement node and removed from the decommissioning node?

I think that this new version of the test is only going to succeed *before* any movement of replicas happens. It'd be sufficient to just keep the old version of the test and add a check that `curReplicas` doesn't include the decommissioned node's ID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16968)*

**Comment by a-robinson** [comment]
I pushed a minor fix to the test to avoid taking up any more of your time and will merge once CI has run. Thanks @garvitjuniwal!

**Pull request merged**
