### PR TITLE
sql: track optimizer cost in app_stats

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds the estimated query cost to statement statistics, for
later consumption in the UI. It also adds the cost to
crdb_internal.node_statement_statistics.

Release note (sql change): add estimated_cost_avg and estimated_cost_var
to crdb_internal.node_statement_statistics, which contain the average
and variance of the optimizer's estimate of each statement's cost.

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: simple but useful. I'm curious what the optimizer team thinks about surfacing this cost.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55476#-:-MJW7cKGDMMRNY_yeoIF:b-hx17fd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/executor_statement_metrics.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55476#-MJW7GSZ0AaDl_Spe7LY:-MJW7GSZ0AaDl_Spe7LZ:beohbpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af2daf487155a1f43d7926c8fd0d680d46de2aa/pkg/sql/executor_statement_metrics.go#L199)):*
> ```Go
> 	}
> 
> 	planCost := planner.curPlan.mem.RootExpr().(memo.RelExpr).Cost()
> ```

nit: why not assign this directly to the struct field?

**Review by yuzefovich — COMMENTED** [review]
Very cool! Does it already show up on the UI? I think no, but I'm confused by the changes to `appStats.ts`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55476#-:-MJXkihdAqt2HYmLstKn:b-2rixvi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by RaduBerinde — APPROVED** [review]
I'm skeptical of showing the cost in the UI. It will lead to a lot of questions with no good answers, especially when upgrading between versions that have cost model changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55476#-:-MJY3J2wAA95nJ8Wy4TT:bpzuldy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by dhartunian — COMMENTED** [review]
:lgtm: 

@yuzefovich the changes in `appStats.ts` are to a function that aggregates stats for display. Statement stats are provided grouped by `node_id` and we do a client-side aggregation to display stats by fingerprint across all nodes. My understanding is that @jordanlewis will have a separate PR that adds UI elements. This one is likely necessitated by Typescript since he added new fields to an object that we operate on.

> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55476#-:-MJYzuK80HkBRNgPWGjE:b89dtu)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by jordanlewis** [comment]
We've decided that we don't really want to be showing optimizer cost in the UI, so I'll close this one.

**Pull request closed without merging**
