### PR TITLE
clusterversion: reduce stuttering in package API

### PR DESCRIPTION
**Pull request by irfansharif**
This package was extracted out of pkg/settings/cluster in #45455. Now
that we're coupling it tightly with our migrations infrastructure
(pkg/migration), let's remove some unnecessary stuttering for ease of
use.

```diff
- if <settings handle>.Version.IsActive(ctx, clusterversion.VersionSomething) {
+ if <settings handle>.Version.IsActive(ctx, clusterversion.Something) {
```

All the diffs here are just mechanical goland-renames.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: with nit

> Reviewed 46 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57338#-:-MNYWdUw8vCvKlp3FesU:b-xv64lu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/server/updates_test.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57338#-MNYWT_-8ERh27poV4--:-MNYWT_-8ERh27poV4-0:bz9dumz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d418d9004cde7969dc365f8bfbb3ea4e9585227/pkg/server/updates_test.go#L150)):*
> ```Go
> 		}
> 	}
> 	// ListBetween 10 and 100 queries is quantized to 10.
> ```

Please revert this file.

**Review by tbg — APPROVED** [review]

**Review by irfansharif — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57338#-:-MNYvEP05Z0b3hb07VI8:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[pkg/server/updates_test.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57338#-MNYWT_-8ERh27poV4--:-MNYvAlJBF5kOEJzmv9C:bpnfts3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d418d9004cde7969dc365f8bfbb3ea4e9585227/pkg/server/updates_test.go#L150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please revert this file.
</blockquote></details>

Woops, done.

**Pull request merged**
