### PR TITLE
sql: Comment and test types package (patch 14/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

Rearrange and clean up methods in the package, including moving some
functionality from the package to other locations (e.g. information
schema related methods). Add comments to all exported structs and methods
in the types package. Add tests for all functionality in the package.

Fix compatibility issue in pg_type table, where oidvector and int2vector
had array oid types of 0.

Release note (sql change): Display correct array type oids for oidvector
and int2vector types in pg_type table, for better PG compatibility.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Generally LGTM but there are many changes here that belong to previous patches in the series. Please move them where they are relevant to get a green CI build on every intermediate step. Thanks.

> Reviewed 36 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-:-Lc67KL-DG2L-5a-eyLM:bhpsju2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/acceptance/testdata/java/src/main/java/MainTest.java, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc63_701P6sDHVpS01Q:-Lc63_701P6sDHVpS01R:b-n8nsz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/acceptance/testdata/java/src/main/java/MainTest.java#L178)):*
> ```Java
>         Array ar = rs.getArray(1);
>         Integer[] fs = (Integer[]) ar.getArray();
>         Assert.assertArrayEquals(new Integer[]{123}, fs);
> ```

Move this change to the commit in #36704, where this is first  useful.
___
*[pkg/internal/client/db.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc64RRr7jRiwiqoGjzj:-Lc64RRr7jRiwiqoGjzk:b-fahs8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/internal/client/db.go#L236)):*
> ```Go
> }
> 
> // Wrapped returns the wrapped sender.
> ```

Move this change to #36710 where it belongs.
___
*[pkg/sql/sem/types/types.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65fD389TXTH-fgVOm:-Lc65fD389TXTH-fgVOn:b9dx7h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L38)):*
> ```Go
> //   DECIMAL(10, 3)           - any base-10 value with at most 10 digits, with
> //                              up to 3 to right of decimal point
> //   []FLOAT                  - array of 64-bit IEEE 754 floating-point values
> ```

the syntax is `FLOAT[]` not `[]FLOAT` IIRC?
___
*[pkg/sql/sem/types/types.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65kV85xS8E1cHOAnk:-Lc65kV85xS8E1cHOAnl:bklohor) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L53)):*
> ```Go
> //   Locale          - location which governs sorting, formatting, etc. (string)
> //   ArrayDimensions - array bounds ([]int)
> //   ArrayContents   - array element type (T)
> ```

This needs to be looked at again in the light of the discussion on #36702.
___
*[pkg/sql/sem/types/types.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc663a2CRwlEgRvZoMi:-Lc663a2CRwlEgRvZoMj:b-rda13c) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L451)):*
> ```Go
> 	if semTyp != t.SemanticType() {
> 		if semTyp != COLLATEDSTRING || STRING != t.SemanticType() {
> 			panic(pgerror.NewAssertionErrorf(
> ```

These panics don't sit super-well with me. 

- is it only used in testing? If yes, rename the function to `TestingMakeScalar()`
- otherwise consider having this function have an error return
___
*[pkg/sql/sem/types/types.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc672edBcvgR0L14rmX:-Lc672edBcvgR0L14rmY:b-z5zjb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/sem/types/types.go#L451)):*
> ```Go
> }
> 
> func (t *T) Name() string {
> ```

It would be better for the diff to avoid moving this function across the file. If you want to move it, please do this in a separate commit than where you're editing comments.
___
*[pkg/sql/sem/types/types.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc66GXU9RgMi2_S6q5X:-Lc66GXU9RgMi2_S6q5Y:b-comlhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L511)):*
> ```Go
> }
> 
> // MakeBit constructs a new instance of the BIT semantic type (oid = T_bit)
> ```

ditto this and below
___
*[pkg/sql/sem/types/types.go, line 799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc66KMd-mJuSQDAAL02:-Lc66KMd-mJuSQDAAL03:b-52kri7) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L799)):*
> ```Go
> }
> 
> // Name returns a single word description of the type that describes it
> ```

Please move the addition of this comment to the commit in #36705 where it belongs.
___
*[pkg/sql/sem/types/types.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc67BJE2u05KHk4Y3x4:-Lc67BJE2u05KHk4Y3x5:bvqwlju) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L1485)):*
> ```Go
> 			temp := *t.InternalType.ArrayContents
> 			err := temp.downgradeType()
> 			if err != nil {
> ```

This is a functional change. Please add a comment to explain why this is needed here.
If it belongs to one of the previous patches in the series, please add it here.
___
*[pkg/sql/sqlbase/table.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65H4h7AVpe68dH2z_:-Lc65H4h7AVpe68dH2za:b-4hkopm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/sqlbase/table.go#L76)):*
> ```Go
> 	switch t.SemanticType() {
> 	case types.BIT:
> 		if t.Width() > math.MaxInt32 {
> ```

Where are these constraints enforced, if not here?
___
*[pkg/testutils/lint/lint_test.go, line 1454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65SVV6LFg3V954J-Q:-Lc65SVV6LFg3V954J-R:b-d6o69w) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/testutils/lint/lint_test.go#L1454)):*
> ```Go
> 				stream.GrepNot("sql/.*exported func .* returns unexported type sql.planNode"),
> 				stream.GrepNot("struct field (XXX_NoUnkeyedLiteral|XXX_sizecache) should be"),
> 				stream.GrepNot("pkg/sql/types/types.go.* var Uuid should be UUID"),
> ```

Move this change (or a variant of it) to the commit in #36699.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36711)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/sem/types/types.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc663a2CRwlEgRvZoMi:-LcA5aKuCBKCSRSNYUbi:b-wp2ez9) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L451)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

These panics don't sit super-well with me. 

- is it only used in testing? If yes, rename the function to `TestingMakeScalar()`
- otherwise consider having this function have an error return
</blockquote></details>

I don't fully agree here. We use these `Make` methods all over the place. Previously, we were just constructing raw `ColumnType` structs. If we set those up incorrectly, we'd likely just panic down the line in a way that wasn't handled anyway (or even worse, it *wouldn't* panic and instead result in data corruption of some kind). Furthermore, we'd have no way of knowing who set them up incorrectly. At least now it will be evident from the call stack where the bad code is. And requiring that I change every place where we construct a type to have to now handle an error is a higher standard than the previous code was held to (and is unrelated to the goal of this PR).

I've also got a more general concern that by demanding that we never explicitly panic, we're encouraging developers to not add asserts to their code. Because as soon as they do, they have to add ugly error-handling to trivial accessor/constructor methods like these. And then add more ugly code to every caller. I guarantee you that developers will respond to that by just not adding asserts in those cases (I've been tempted multiple times!). And their code will then panic (or silently corrupt) anyway, but in ways that are harder to debug.

I think we're going at this the wrong way. Panics are going to happen no matter what. We should be restructuring our code to *always* handle panics, like we did in `optbuilder` and `execbuilder`. That way, we handle both planned and unplanned panics.

All that said, I'd be OK with changing `MakeScalar` to return an error, since it's seldom used (mainly test code), and there's a good argument to be made that some future code might want to use it as a validation mechanism for constructing parameterized types. But I'm definitely against changing all the other more specific `Make` methods to return errors. I'd rather just remove the asserts in that case, since I doubt those asserts will actually get hit anyway. They're mainly there to strengthen the API for testing and development, not because I think they'll get hit in production.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36711)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/sem/types/types.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc663a2CRwlEgRvZoMi:-LcB-Dtn5SMaszjk9-D3:b5hwbkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L451)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't fully agree here. We use these `Make` methods all over the place. Previously, we were just constructing raw `ColumnType` structs. If we set those up incorrectly, we'd likely just panic down the line in a way that wasn't handled anyway (or even worse, it *wouldn't* panic and instead result in data corruption of some kind). Furthermore, we'd have no way of knowing who set them up incorrectly. At least now it will be evident from the call stack where the bad code is. And requiring that I change every place where we construct a type to have to now handle an error is a higher standard than the previous code was held to (and is unrelated to the goal of this PR).

I've also got a more general concern that by demanding that we never explicitly panic, we're encouraging developers to not add asserts to their code. Because as soon as they do, they have to add ugly error-handling to trivial accessor/constructor methods like these. And then add more ugly code to every caller. I guarantee you that developers will respond to that by just not adding asserts in those cases (I've been tempted multiple times!). And their code will then panic (or silently corrupt) anyway, but in ways that are harder to debug.

I think we're going at this the wrong way. Panics are going to happen no matter what. We should be restructuring our code to *always* handle panics, like we did in `optbuilder` and `execbuilder`. That way, we handle both planned and unplanned panics.

All that said, I'd be OK with changing `MakeScalar` to return an error, since it's seldom used (mainly test code), and there's a good argument to be made that some future code might want to use it as a validation mechanism for constructing parameterized types. But I'm definitely against changing all the other more specific `Make` methods to return errors. I'd rather just remove the asserts in that case, since I doubt those asserts will actually get hit anyway. They're mainly there to strengthen the API for testing and development, not because I think they'll get hit in production.
</blockquote></details>

You do not need to convince me that handling errors using panics (exceptions) is generally preferable in Go, with regards to both performance and code readability. I have proved that independently ([1](https://science.raphael.poss.name/measuring-errors-vs-exceptions-in-go-and-cpp.html)).

The problem I have here is that we're currently letting these panics crash nodes. That's undesirable. If you think we should handle these cases like in `optbuilder` and `execbuilder` then you have my full support. This needs: 

1) using error objects as panic arguments (`pgerror.NewAssertionErrorf` which will capture the error details in a way suitable for sentry), this you can do in this commit already.
2) at some later point, extending the panic catch logic in the SQL executor to block panics that are also error objects from crashing the node, and let them return a value to the client instead. This would need to be filed as to-do item for the SQL team (although I am considering doing that as part of my error refactoring work as well).

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36711)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @knz)

___
*[pkg/acceptance/testdata/java/src/main/java/MainTest.java, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc63_701P6sDHVpS01Q:-LcKMOM74s91Dy8B1fNc:bkud1lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/acceptance/testdata/java/src/main/java/MainTest.java#L178)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Move this change to the commit in #36704, where this is first  useful.
</blockquote></details>

I reverted this and filed #36811.
___
*[pkg/sql/sem/types/types.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc672edBcvgR0L14rmX:-LcKMsj98ovAWxbk-2Pb:b-wltuw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/sem/types/types.go#L451)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It would be better for the diff to avoid moving this function across the file. If you want to move it, please do this in a separate commit than where you're editing comments.
</blockquote></details>

Agree, but not sure how to do that without messing up the separate PR's you opened.

**Review by andy-kimball — COMMENTED** [review]
I'm ready to push an update, but I've got a patch 13.5 that does code movement only to make diff easier. I'll modify the `split.sh` script to skip that one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-:-LcMDUB26ZuA0BEmzCQN:bb29v8b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @knz)

___
*[pkg/internal/client/db.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc64RRr7jRiwiqoGjzj:-LcMDJ-q1YyN0I6_8126:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/internal/client/db.go#L236)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Move this change to #36710 where it belongs.
</blockquote></details>

Done.
___
*[pkg/sql/sem/types/types.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65fD389TXTH-fgVOm:-LcM8zoa1CPYl0gy0O1c:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L38)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the syntax is `FLOAT[]` not `[]FLOAT` IIRC?
</blockquote></details>

Fixed.
___
*[pkg/sql/sem/types/types.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65kV85xS8E1cHOAnk:-LcM99qz1LTcPsA7N-qY:b-duaxa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L53)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This needs to be looked at again in the light of the discussion on #36702.
</blockquote></details>

Removed `ArrayDimensions` from list.
___
*[pkg/sql/sem/types/types.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc663a2CRwlEgRvZoMi:-LcM9OP8B6CuP8sjT4yB:b-vsqfvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L451)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You do not need to convince me that handling errors using panics (exceptions) is generally preferable in Go, with regards to both performance and code readability. I have proved that independently ([1](https://science.raphael.poss.name/measuring-errors-vs-exceptions-in-go-and-cpp.html)).

The problem I have here is that we're currently letting these panics crash nodes. That's undesirable. If you think we should handle these cases like in `optbuilder` and `execbuilder` then you have my full support. This needs: 

1) using error objects as panic arguments (`pgerror.NewAssertionErrorf` which will capture the error details in a way suitable for sentry), this you can do in this commit already.
2) at some later point, extending the panic catch logic in the SQL executor to block panics that are also error objects from crashing the node, and let them return a value to the client instead. This would need to be filed as to-do item for the SQL team (although I am considering doing that as part of my error refactoring work as well).
</blockquote></details>

1. I believe I'm using `pgerror.NewAssertionErrorf` in every explicit panic.
2. Can you take that over, then, and follow-up?

Also, I took  look at callers of `MakeScalar`. One is `CastExpr.Format`, another is `CastExpr.doc`, and a third is a test case. This illustrates another aspect of the problem: those contexts don't even have a way to return errors. I think panic catch logic in the SQL executor is the way to handle these situations, as you say. Given that I'd just need to panic in the callers anyway, I'm going to leave `MakeScalar` as-is.
___
*[pkg/sql/sem/types/types.go, line 799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc66KMd-mJuSQDAAL02:-LcMDMuZ99ZYjY1sHf_d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L799)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please move the addition of this comment to the commit in #36705 where it belongs.
</blockquote></details>

Done.
___
*[pkg/sql/sem/types/types.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc67BJE2u05KHk4Y3x4:-LcMCdJX3Y_mDIONQ1D-:bnbn1tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L1485)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is a functional change. Please add a comment to explain why this is needed here.
If it belongs to one of the previous patches in the series, please add it here.
</blockquote></details>

Should no longer be any functional change here.
___
*[pkg/sql/sqlbase/table.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65H4h7AVpe68dH2z_:-LcMCmyW85Jilh9g2pDq:b-883wfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/sqlbase/table.go#L76)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Where are these constraints enforced, if not here?
</blockquote></details>

Given that Width is an `int32` value, that code was doing nothing. Before, it was an `int`, so it was necessary. So this is just a small cleanup item that has no functional effect.
___
*[pkg/testutils/lint/lint_test.go, line 1454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc65SVV6LFg3V954J-Q:-LcMDBbU39e2GWSiiuRM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/testutils/lint/lint_test.go#L1454)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Move this change (or a variant of it) to the commit in #36699.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
For simplicity you could have changed the order and put an extra patch at the "end" of the sequence (after the package migration) and let `split.sh` create an additional thing at the end. But this works fine too I guess.

:lgtm: 

> Reviewed 29 of 29 files at r2, 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-:-LcfQkoX1GuhcZ72kPjh:b-vwxrs8)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sem/types/types.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36711#-Lc663a2CRwlEgRvZoMi:-LcfRYHSBbGYJWlzFbHO:b-locel6) ([raw file](https://github.com/cockroachdb/cockroach/blob/458475d5ac0116081b4321ae9385908378a38bd1/pkg/sql/sem/types/types.go#L451)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

1. I believe I'm using `pgerror.NewAssertionErrorf` in every explicit panic.
2. Can you take that over, then, and follow-up?

Also, I took  look at callers of `MakeScalar`. One is `CastExpr.Format`, another is `CastExpr.doc`, and a third is a test case. This illustrates another aspect of the problem: those contexts don't even have a way to return errors. I think panic catch logic in the SQL executor is the way to handle these situations, as you say. Given that I'd just need to panic in the callers anyway, I'm going to leave `MakeScalar` as-is.
</blockquote></details>

Ok thanks.

**Pull request closed without merging**
