### PR TITLE
release-21.2: server: do not check decommission list for the tenant

### PR DESCRIPTION
**Pull request by jeffswenson**
Backport 1/1 commits from #75766.

/cc @cockroachdb/release

---

Previously, the system tenant would return PermissionDenied if the
tenant's instance_id was equivalent to a decommissioned node's id.

Now, the system tenant does not check the decommissioned node list if
the incoming node_id belongs to a non-system tenant.

This PR feeds the request context down to the OnOutgoingPing and
OnIncomingPing callbacks. Previously the callbacks were using the
ambient context. The only use of the context was a storage.MVCCGet call
in nodeTombstoneStorage.IsDecommissioned.

Release note: None

Release justification: This is impacting production Serverless clusters. See SREOPS-4111.

### CODE REVIEW

**Comment by JeffSwenson** [comment]
I removed the regression test from the backport. It was failing with the following error:

```
test logs left over in: /tmp/logTestTenantWithDecommissionedID508539754
    panic.go:1038: clusterID already set
        goroutine 30663 [running]:
        runtime/debug.Stack()
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
        github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func1()
        	/home/jeffswenson/go/src/github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:110 +0x11f
        panic({0x4011d80, 0x5cf4a00})
        	/usr/local/go/src/runtime/panic.go:1038 +0x215
        github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc0057bc200, {0x5de8be0, 0xc000136000})
        	/home/jeffswenson/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:502 +0x325
        panic({0x4011d80, 0x5cf4a00})
        	/usr/local/go/src/runtime/panic.go:1038 +0x215
        github.com/cockroachdb/cockroach/pkg/util/log.SetNodeIDs({0xc00e19cf60, 0xc01022e764}, 0x0)
        	/home/jeffswenson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:261 +0x225
        github.com/cockroachdb/cockroach/pkg/server.StartTenant({_, _}, _, {_, _}, {0xc003eae000, 0xc005a22ee0, {0xc00c1fe180, 0x0, 0x0, ...}, ...}, ...)
        	/home/jeffswenson/go/src/github.com/cockroachdb/cockroach/pkg/server/tenant.go:279 +0x11d5
        github.com/cockroachdb/cockroach/pkg/server.(*TestServer).StartTenant(_, {_, _}, {{0xa}, 0x1, 0x0, 0x0, 0x0, {{0x0, 0x0}, ...}, ...})
        	/home/jeffswenson/go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:599 +0x6b4
        github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartTenant({_, _}, {_, _}, {{0xa}, 0x1, 0x0, 0x0, 0x0, {{0x0, ...}, ...}, ...})
        	/home/jeffswenson/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:362 +0x87
        github.com/cockroachdb/cockroach/pkg/ccl/serverccl.TestTenantWithDecommissionedID(0xc00b1cc000)
        	/home/jeffswenson/go/src/github.com/cockroachdb/cockroach/pkg/ccl/serverccl/tenant_decommissioned_host_test.go:57 +0x457
        testing.tRunner(0xc00b1cc000, 0x4e76c20)
        	/usr/local/go/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1306 +0x35a
```

I believe this error is unrelated to what the test is actually covering. The static logging set in the tenant was removed by https://github.com/cockroachdb/cockroach/commit/0e6abb5778079f9560eae51b33979654c0894639.

**Comment by knz** [comment]
You can use `log.TestingClearServerIdentifiers()` in your test before starting tenant servers. It's already used in a couple other multi-tenant tests.

**Comment by knz** [comment]
Let's investigate #75923 before this merges.

**Comment by JeffSwenson** [comment]
I pulled the test back into this PR with the changes from #75964.

**Review by knz — APPROVED** [review]

**Pull request merged**
