### PR TITLE
acceptance: disable flaky TestDockerCLI test

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]

**Comment by knz** [comment]
Huh why not just disable those two tests that are flaky instead of the entire suite... want me to look at doing this?

**Comment by benesch** [comment]
@knz per Slack @petermattis is busy for the next little bit, if that changes your calculus.

**Comment by knz** [comment]
Ok let's merge this, this will enable progress on a bunch of non-cli-related PRs. I'll still work on a better workaround today though.

**Comment by tamird** [comment]
@knz I think you can update @petermattis' branch, so it's not like you need
to wait for him.

**Comment by knz** [comment]
Ah ok, will do.

**Comment by knz** [comment]
Done.

**Pull request merged**
