### PR TITLE
opt: prune RHS of a semi/anti join

### LINKED ISSUE #38704: opt: Add pruning rule for columns on the right side of Semi/Anti joins
Consider this schema and query:
```
create table t1 (a int primary key, b int);
create table t2 (c int primary key, d int);
explain (opt,types) select * from t1 where exists(select * from t2 where c=a);
```
The optimized query uses a semi-join:
```
semi-join (merge)
 ├── columns: a:1(int!null) b:2(int)
 ├── left ordering: +1
 ├── right ordering: +3
 ├── scan t1
 │    └── columns: a:1(int!null) b:2(int)
 ├── scan t2
 │    └── columns: c:3(int!null) d:4(int)
 └── filters (true)
```
However, the `d` column can be pruned here, since it is not used by the join, and is not returned as an output column.

We should add a new `prune_cols.opt` rule that prunes unused columns on the right side of a Semi or Anti join (assuming the columns are in the `PruneCols` rule property set).

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Fixes #38704.

This change adds a PruneSemiAntiJoinRightCols to prune
columns in the RHS of a semi/anti join. Alternatively,
we could just tag the PruneJoinRightCols rule as higher
priority to achieve the same effect (previously that rule
was never triggered because the `EliminateProjects` rule
would fire and remove the projections after
`PruneJoinLeftCols` rule is applied). I prefer this rule
because it avoids requiring an ordering of transformations.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:LGTM:

[nit] in the commit message, avoids require -> avoids requiring

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39472#-:-LlrLuEo98rSFmSLrvQ0:bqqdq1o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Review by andy-kimball — APPROVED** [review]
:lgtm:  Do you know if there's any impact on TPCH Q21 performance?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39472#-:-LlrjM-S0rDJpGpkgoFl:b-22jqsg)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @ridwanmsharif)

___
*[pkg/sql/opt/norm/rules/prune_cols.opt, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39472#-LlriX04C3b0yaRZF_DU:-LlriVN063xycndO4WxE:bp7nprq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc422a7182bded855647454cd78ffe38dea8764/pkg/sql/opt/norm/rules/prune_cols.opt#L255)):*
> ```
>     $on:*
>     $private:* &
>     (CanPruneCols
> ```

NIT: Indent `(CanPruneCols` another level like other rules (or maybe there's tab vs. space issue?).

**Review by ridwanmsharif — COMMENTED** [review]
This is interesting indeed. From what I'm seeing over multiple runs the average time for TPCH Q21 increases from ~27.16s to ~28.88s.

The only change I see in the Q21 plan as a result of this change (apart form some columns being pruned away) is that we're using the `l_sk` index when scanning the `lineitem` table (because after pruning all the columns returned are available in the index). This in turn, has the `SemiJoin` use the hash join instead of the merge join because the scan of `lineitem` doesn't order by `orderkey`. This sounds like an issue with costing merge joins and hash joins correctly (scanning using the pk and doing a merge join vs scanning using an index and doing a hash join) and so I don't think this blocks this PR. I'll merge if the team agrees.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39472#-:-LmLAwfr6wVPTv5PgYjD:bq9inoc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/norm/rules/prune_cols.opt, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39472#-LlriX04C3b0yaRZF_DU:-LmLAta7EGCtoW0mWnDj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc422a7182bded855647454cd78ffe38dea8764/pkg/sql/opt/norm/rules/prune_cols.opt#L255)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Indent `(CanPruneCols` another level like other rules (or maybe there's tab vs. space issue?).
</blockquote></details>

Done.

**Pull request merged**
