### PR TITLE
config,sqlbase: move computation of splits for SQL tables to sqlbase

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, the config package was in charge of figuring out the
split points to be created by the split queue - generally between tables
and between partitions where there's an applicable zone config.
This patch moves the code for determining the splits to sqlbase, where
it belongs better: there was no good reason for the config package to
deal with table keys and, in the future we'll likely tie zone configs
and table descriptors more and more (and the config package doesn't have
access to table descriptor). Besides generally seeming like a
good direction, I've got some more immediate optimizations that I want
to make to the splitting code that requires access to table descriptor
when deciding the split points.

This patch also rationalizes the remaining code dealing with splits in
the config package, which was flirting with unreadability.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
r2,3,4 are #39721

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-:-LmRD_Bo4NjGe2UnkPQq:b-cppzyz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @solongordon)

**Review by knz — COMMENTED** [review]
Can you rebase this now that the other PR has been merged?

Overall code OK but I'd like to request several additional clarifying comments.
Also some missing unit tests.

As we've discussed, your PR is crystallizing some assumptions we're making about the structure of SQL keys. Maybe it would be good to put a small reminder of these assumptions (with examples) in the commit message.

> Reviewed 100 of 100 files at r1, 6 of 6 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-:-LnMIMI04UFlbEi1Vou_:bojxs1w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/config/system.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMJahHBZZzX7Xo-f0v:-LnMJahHBZZzX7Xo-f0w:b-wi74hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L113)):*
> ```Go
> // tests that install zone configs without actually creating a corresponding
> // table. They expect a split point around that zone, but were it not for this,
> // they wouldn't get it.
> ```

Please provide some illustrative examples that show what this method does and the cases where it doesn't work.
___
*[pkg/config/system.go, line 430 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMJt7F9_Uh9hBgNnzY:-LnMJt7F9_Uh9hBgNnzZ:buuak5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L430)):*
> ```Go
> 		for id := startID; id <= endID; id++ {
> 			// This code is not equipped to deal with subzones (which would require
> 			// splits), so assume that the system zones (to the extent that they
> ```

Can you report this assumption (and any other you deem relevant for this change) in the commit message.
___
*[pkg/config/system.go, line 453 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMK0N8Ds70m4r2wk64:-LnMK0N8Ds70m4r2wk65:b-kdbqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L453)):*
> ```Go
> // [startKey-endKey) by only considering user-space splits (i.e. between tables
> // and possibly indexes and partitions). Ultimately the decision of where to
> // split is delegate to sqlbase.
> ```

delegated*
___
*[pkg/config/system.go, line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMMRK_B9JmAXECT8nC:-LnMMRKbEi83u2gvt5iz:buez2hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L474)):*
> ```Go
> 
> 	// Iterate over all the tables in between startKey and endKey.
> 	// endID could be smaller than startID if we don't have user tables.
> ```

Just for clarification: is this function called for arbitrary spans over the entire key space? What guarantee do you have here that this loop is not going to scan a large number (hundreds) of descriptors?
___
*[pkg/config/system_test.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMMq7q9OnkvrUI-97h:-LnMMq7q9OnkvrUI-97i:b37flqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system_test.go#L51)):*
> ```Go
> }
> 
> func descriptor(descriptorID uint64) roachpb.KeyValue {
> ```

Can you create a comment for this function that explains what it does.
In particular I want to understand why it now populates the value part, and what makes you think this value part is safe for use (AFAICS this descriptor is invalid).
___
*[pkg/sql/sqlbase/table.go, line 477 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMN9Tg6tdF6CP0x7Qn:-LnMN9Tg6tdF6CP0x7Qo:b-gi89p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/sql/sqlbase/table.go#L477)):*
> ```Go
> //
> // The split keys are returned sorted.
> // An error is returned iff a descVal is not a descriptor.
> ```

This function is in ask of a unit test alongside in the same package.
___
*[pkg/storage/client_split_test.go, line 1300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMNHHk4o3eUvEatCsC:-LnMNHHk4o3eUvEatCsD:b-houidt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/storage/client_split_test.go#L1300)):*
> ```Go
> 					Union: &sqlbase.Descriptor_Table{
> 						Table: &sqlbase.TableDescriptor{
> 							// Fill in the descriptor just enough for the test to work.
> ```

ditto my comment above - I understand that this is what's needed for the test, but the comment should explain/remind the reader _why_ 
1) a value is needed at all alongside the key 
2) why just the desc ID is sufficient.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39722)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @solongordon)

___
*[pkg/config/system.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMJahHBZZzX7Xo-f0v:-Lql_RZG7HccjOgj91Hf:bft90tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please provide some illustrative examples that show what this method does and the cases where it doesn't work.
</blockquote></details>

Not sure what you mean :)
The method is very simple; there's no cases where it "doesn't work". I added more words to its comment to reference the `testingZoneConfig` global map. Does that help?
___
*[pkg/config/system.go, line 430 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMJt7F9_Uh9hBgNnzY:-Lqlbd_S6sGnid6p5eL-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L430)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you report this assumption (and any other you deem relevant for this change) in the commit message.
</blockquote></details>

done
___
*[pkg/config/system.go, line 453 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMK0N8Ds70m4r2wk64:-LqlcF6y4iw7j8h6eTke:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L453)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

delegated*
</blockquote></details>

Done.
___
*[pkg/config/system.go, line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMMRK_B9JmAXECT8nC:-LqldEGhBIdbXD43X9se:b1km7vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L474)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Just for clarification: is this function called for arbitrary spans over the entire key space? What guarantee do you have here that this loop is not going to scan a large number (hundreds) of descriptors?
</blockquote></details>

It can be called over arbitrary spans but limited to a range. In practice, I think it would only be called with a span spanning more than one table if you create a bunch of tables in quick succession.

The key here is that this loop early-returns, so as soon as we find a table that doesn't correspond to the start key, we return. I've added a comment to that effect.
___
*[pkg/config/system_test.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMMq7q9OnkvrUI-97h:-Lqlein22w9NDpumhOkK:bem6h7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system_test.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you create a comment for this function that explains what it does.
In particular I want to understand why it now populates the value part, and what makes you think this value part is safe for use (AFAICS this descriptor is invalid).
</blockquote></details>

added a comment

I don't remember why I had to change this exactly; presumably because the code being tested by its users became a little more needy in terms of what they expect from these KeyValues. Note that before the value was a straight-up nil, so I'm only making things more realistic.
___
*[pkg/sql/sqlbase/table.go, line 477 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMN9Tg6tdF6CP0x7Qn:-Lqm9hlVE2Qv6CYxUkvN:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/sql/sqlbase/table.go#L477)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This function is in ask of a unit test alongside in the same package.
</blockquote></details>

done
___
*[pkg/storage/client_split_test.go, line 1300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMNHHk4o3eUvEatCsC:-LqlfEv35dJEyqdQJo2m:btgmxg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/storage/client_split_test.go#L1300)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto my comment above - I understand that this is what's needed for the test, but the comment should explain/remind the reader _why_ 
1) a value is needed at all alongside the key 
2) why just the desc ID is sufficient.
</blockquote></details>

Well, I kinda respectfully disagree. I think a comment that says "Fill in the descriptor just enough for the test to work" is pretty sufficient (and, in fact, above our usual standards if I may say so myself :P). It alerts the reader that we're cutting some corners. But going beyond that is not very useful in my opinion, and will be quick to rot.

The way I see it, your question is going the wrong way :). The better question is why *wasn't* a value needed before? In fact, the code before was just wrong. It was writing a `TableDescriptor`, but what's supposed to correspond to those keys is a `Descriptor`. The reason why I had to change this must be that now the test is invoking code that actually deserializes that value and expects a `Descriptor`. But I wouldn't put a comment about it; it's natural. As for why the ID is needed, I don't remember...

**Review by knz — APPROVED** [review]
:lgtm: with nit

> Reviewed 62 of 81 files at r4, 5 of 5 files at r5, 4 of 6 files at r6, 13 of 13 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-:-LqqstrW9Tnu8-D4t3PS:b-xv64lu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/config/system.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMJahHBZZzX7Xo-f0v:-LqqrSDa8TxvEKZdyQAm:b-l6wj6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Not sure what you mean :)
The method is very simple; there's no cases where it "doesn't work". I added more words to its comment to reference the `testingZoneConfig` global map. Does that help?
</blockquote></details>

yes thanks
___
*[pkg/config/system.go, line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMMRK_B9JmAXECT8nC:-LqqrZawDcZQiNuGi6a_:b-ed5i8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L474)):*
> It can be called over arbitrary spans but limited to a range. 

Please add this sentence too to the comment.
___
*[pkg/storage/client_split_test.go, line 1300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMNHHk4o3eUvEatCsC:-Lqqrts04IAKhOq-8TIK:b1lgkr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/storage/client_split_test.go#L1300)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Well, I kinda respectfully disagree. I think a comment that says "Fill in the descriptor just enough for the test to work" is pretty sufficient (and, in fact, above our usual standards if I may say so myself :P). It alerts the reader that we're cutting some corners. But going beyond that is not very useful in my opinion, and will be quick to rot.

The way I see it, your question is going the wrong way :). The better question is why *wasn't* a value needed before? In fact, the code before was just wrong. It was writing a `TableDescriptor`, but what's supposed to correspond to those keys is a `Descriptor`. The reason why I had to change this must be that now the test is invoking code that actually deserializes that value and expects a `Descriptor`. But I wouldn't put a comment about it; it's natural. As for why the ID is needed, I don't remember...


</blockquote></details>

Thanks now I understand better.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39722)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @solongordon)

___
*[pkg/config/system.go, line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMMRK_B9JmAXECT8nC:-LrjgOQH-Y6y63G-Tpbi:b-m10nn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L474)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> It can be called over arbitrary spans but limited to a range. 

Please add this sentence too to the comment.
</blockquote></details>

I don't really know what to say, beyond what the comment already says: that we return early at the first table id...

**Review by andreimatei — COMMENTED** [review]
replying in thread

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-:-Lro24FO1J_h4eu4__rh:b9si476)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @solongordon)

___
*[pkg/config/system.go, line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39722#-LnMMRK_B9JmAXECT8nC:-Lro0eu_3qwiRbL4GA0C:bgo50ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc923c255eb764d65fc829feab15d359524a6f8/pkg/config/system.go#L474)):*
> When I say "please add this sentence to the comment" there is nothing left for you to think about other than a copy/paste. Adding to the comment has no negative effect and a potential upside (I had to ask, so the next reader will ask too)

Copy-paste what where exactly? As far as this function is concerned, it can be called over arbitrary portions of the key space. Commenting on how it's actually used in practice is not necessary unless that's particularly important (cause then a reader starts wondering why that's important, and how does it jibe with tests that call this without even having any ranges). And in this case, it's not particularly important. The reason why we're not looping over too many descriptors is because of the early return. I think any comment beyond that does more harm than good.

But you can still convince me otherwise if you care.

**Pull request merged**
