### PR TITLE
roachtest: fix UT for selective test

### LINKED ISSUE #132656: cmd/roachtest: Test_updateSpecForSelectiveTests failed
cmd/roachtest.Test_updateSpecForSelectiveTests [failed](https://tanzanite.cluster.engflow.com/invocations/default/99137d9a-1226-4fa5-b3d8-23d4fa39bd13?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY21kL3JvYWNodGVzdDpyb2FjaHRlc3RfdGVzdA==) on master @ [a1b013e763abd1454603985996a45663b6e6bcad](https://github.com/cockroachdb/cockroach/commits/a1b013e763abd1454603985996a45663b6e6bcad):

```
=== RUN   Test_updateSpecForSelectiveTests
=== RUN   Test_updateSpecForSelectiveTests/expect_CategoriseTests_to_fail_which_causes_fall_back_to_run_all_tests
running all tests! error selecting tests: failed to prepare
=== RUN   Test_updateSpecForSelectiveTests/expect_no_failure
3 selected out of 10 successful tests.
11 out of 16 tests selected for the run!
=== RUN   Test_updateSpecForSelectiveTests/run_with_randomised_data
==================
WARNING: DATA RACE
Write at 0x00c002009ce0 by goroutine 1278:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.Test_updateSpecForSelectiveTests.func4.3()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main_test.go:198 +0x26c
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.Test_updateSpecForSelectiveTests.func4.gowrap1()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main_test.go:256 +0x41

Previous read at 0x00c002009ce0 by goroutine 1276:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.Test_updateSpecForSelectiveTests.func4.3.1()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main_test.go:215 +0xca
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest/testselector.getConnect()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/testselector/selector.go:163 +0x69
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest/testselector.CategoriseTests()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/testselector/selector.go:92 +0x77
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.updateSpecForSelectiveTests()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main.go:313 +0x155
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.Test_updateSpecForSelectiveTests.func4.3()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main_test.go:217 +0xae4
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.Test_updateSpecForSelectiveTests.func4.gowrap1()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main_test.go:256 +0x41

Goroutine 1278 (running) created at:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.Test_updateSpecForSelectiveTests.func4()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main_test.go:196 +0x2d3
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1743 +0x44

Goroutine 1276 (running) created at:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.Test_updateSpecForSelectiveTests.func4()
      github.com/cockroachdb/cockroach/pkg/cmd/roachtest/main_test.go:196 +0x2d3
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1743 +0x44
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*Test_updateSpecForSelectiveTests.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43211

### PR DESCRIPTION
**Pull request by nameisbhaskar**
Currently we run a randomized test that generates 100 random tests and runs them 1000 times concurrently. All the 1000 concurrent iterations maintains the mock DB in a list. Now, the list gets concurrently updated by all the goroutines when the mock db for each iteration is initialized. This PR ensures that the race condition is avoided by creating the mock DB within a lock.

Fixes: #132656
Epic: None
Release note: None

### CODE REVIEW

**Review by DarrylWong — COMMENTED** [review]
This change looks good to me but what's the reason again that we need a slice of `dbs` and `mocks`. Why can't we just have a single db and mock scoped to each goroutine?

**Comment by nameisbhaskar** [comment]
> This change looks good to me but what's the reason again that we need a slice of `dbs` and `mocks`. Why can't we just have a single db and mock scoped to each goroutine?

The reason is that the EXPECT assertion sequence gets messed up and causes random behaviour.

**Review by DarrylWong — APPROVED** [review]
Ah I see, it's because the `SqlConnectorFunc` is shared.

FWIW, the following diff worked for me 5/5 times:

```
--- a/pkg/cmd/roachtest/main_test.go
+++ b/pkg/cmd/roachtest/main_test.go
@@ -184,8 +184,6 @@ func Test_updateSpecForSelectiveTests(t *testing.T) {
                defer func() {
                }()
-               dbs := make([]*gosql.DB, totalIterations)
-               mocks := make([]sqlmock.Sqlmock, totalIterations)
                // each iteration is run in a go routine
                wg := sync.WaitGroup{}
@@ -195,11 +193,11 @@ func Test_updateSpecForSelectiveTests(t *testing.T) {
                                defer wg.Done()
-                               dbs[i], mocks[i], err = sqlmock.New()
+                               dbs, mocks, err := sqlmock.New()
                                require.Nil(t, err)
                                specsLengthBefore := len(specs)
                                countOfSpecSkippedTests := 0
@@ -212,7 +210,7 @@ func Test_updateSpecForSelectiveTests(t *testing.T) {
                                mu.Lock()
+                                       return dbs, err
                                }

```

Still need the mutex around SqlConnectorFunc usage but don't need the dbs/mocks array.

**Comment by nameisbhaskar** [comment]
> Ah I see, it's because the `SqlConnectorFunc` is shared.
> 
> FWIW, the following diff worked for me 5/5 times:
> 
> ```
> --- a/pkg/cmd/roachtest/main_test.go
> +++ b/pkg/cmd/roachtest/main_test.go
> @@ -184,8 +184,6 @@ func Test_updateSpecForSelectiveTests(t *testing.T) {
>                 defer func() {
>                 }()
> -               dbs := make([]*gosql.DB, totalIterations)
> -               mocks := make([]sqlmock.Sqlmock, totalIterations)
>                 // each iteration is run in a go routine
>                 wg := sync.WaitGroup{}
> @@ -195,11 +193,11 @@ func Test_updateSpecForSelectiveTests(t *testing.T) {
>                                 defer wg.Done()
> -                               dbs[i], mocks[i], err = sqlmock.New()
> +                               dbs, mocks, err := sqlmock.New()
>                                 require.Nil(t, err)
>                                 specsLengthBefore := len(specs)
>                                 countOfSpecSkippedTests := 0
> @@ -212,7 +210,7 @@ func Test_updateSpecForSelectiveTests(t *testing.T) {
>                                 mu.Lock()
> +                                       return dbs, err
>                                 }
> ```
> 
> Still need the mutex around SqlConnectorFunc usage but don't need the dbs/mocks array.

Interesting. Actually, this looks right. The dbs is initiated within and the same value will be returned as we lock in the same sequence. May be I got to this due to multiple iterations. I will change to this! Thanks!

**Comment by nameisbhaskar** [comment]
Thanks @DarrylWong for the review. I have made the changes. PTAL.

**Comment by nameisbhaskar** [comment]
bors r=@DarrylWong

**Pull request merged**
