### PR TITLE
sql: add "public" pseudo-role.

### LINKED ISSUE #23818: sql: introduce PUBLIC pseudo-role for virtual schema privileges
Virtual schemas (`information_schema`, `pg_catalog`, etc.) are a little funky when it comes to privileges. All users have permission to query them, but they do not actually [store](https://github.com/cockroachdb/cockroach/blob/523c056ba5ef398ce4e54467ae1c7db408b4dc7e/pkg/sql/virtual_schema.go#L199) any privileges on their descriptor. This leads to [strange cases](https://github.com/nvanbenschoten/cockroach/blob/94c25be0f5dcbde7d64d1caa15c93d0b5c4cff83/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L670) where certain places show that users don't have sufficient privileges to SELECT from them. We should fix this.

The reason why this is a little tricky is that privileges are stored on descriptors as `(user, privilege)` pairs. We could add a privilege pair for every user in existence at the time of virtual table initialization, but this still creates an issue for new users created after virtual table initialization. We could work around this by modifying the privilege list when we create a new user, but this is a bad path to start going down.

Luckily, Postgres has the same issue and has solved it with their `PUBLIC` pseudo-role. Documented [here](https://www.postgresql.org/docs/current/static/sql-grant.html#SQL-GRANT-DESCRIPTION-OBJECTS), the keyword indicates that
> the privileges are to be granted to all users/roles, including those that might be created later. PUBLIC can be thought of as an implicitly defined group that always includes all roles.

We should introduce a similar concept and use this to correct the privileges we expose for virtual schemas.

### PR DESCRIPTION
**Pull request by mberhault**
Fixes #23818

The "public" role is special in the sense that:
* it does not have an entry in the system table
* all users are implicit members (but not listed)
* it can have privileges assigned to it

It has SELECT privileges on virtual tables.

The errors returned when attempting to do illegal things with "public"
are odd, but follow postgres behavior:
* creating "public": "public is reserved"
* dropping "public": "cannot use special role specifier"
* change role memberships (as member or as role): "role does not exist"

The last one is odd and due to the fact that the role technically does
not exist but is reserved. I would prefer to spit out a "reserved role
public cannot be a member of another role".

We also add a migration to ensure that there is no user or role named
"public" in system.users. If there is, we fail and tell the user to drop
it and try again.

Release note (sql change): add "public" pseudo-role.

### CODE REVIEW

**Comment by mberhault** [comment]
@nvanbenschoten since you created the issue :)
@benesch for migrations

**Comment by mberhault** [comment]
Ping. This is ready and not meant for today's alpha.

**Comment by nvanbenschoten** [comment]
Planning on taking a look at this today. Thanks for making the change so fast!

**Comment by nvanbenschoten** [comment]
The changes here all look good, although I don't think they are extensive enough. The original issue mentioned that https://github.com/nvanbenschoten/cockroach/blob/94c25be0f5dcbde7d64d1caa15c93d0b5c4cff83/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L670 (along with anything else that looked at the privileges of virtual tables) was wrong. I think we need a bit more logic for these privilege inquiry functions. Something like the following should do the trick:

```
--- a/pkg/sql/sem/builtins/pg_builtins.go
+++ b/pkg/sql/sem/builtins/pg_builtins.go
@@ -412,7 +412,7 @@ func evalPrivilegeCheck(
        for _, p := range privChecks {
                query := fmt.Sprintf(`
                        SELECT bool_or(privilege_type IN ('%s', '%s')) IS TRUE
-                       FROM information_schema.%s WHERE grantee = $1 AND %s`,
+                       FROM information_schema.%s WHERE grantee IN ('public', $1) AND %s`,
                        privilege.ALL, p, infoTable, pred)
                r, err := ctx.Planner.QueryRow(ctx.Ctx(), query, user)
                if err != nil {
```

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/ccl/logictestccl/testdata/logic_test/role, line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-LBNAUJ26wzD-AWuG2bB:-LBNAUJ26wzD-AWuG2bC:b-rccgkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/abfff86ce044a56a35a496258a7b7e51841fd313/pkg/ccl/logictestccl/testdata/logic_test/role#L731)):*
> ```
> 
> statement error user or role public does not exist
> GRANT admin TO public
> ```

Add tests for revoking to/from the public role.

---

*[pkg/sql/create_user.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-LBN0fxY1OSs7yyRtAM1:-LBN0fxY1OSs7yyRtAM2:b-5i0ovu) ([raw file](https://github.com/cockroachdb/cockroach/blob/abfff86ce044a56a35a496258a7b7e51841fd313/pkg/sql/create_user.go#L86)):*
> ```Go
> 	// Reject the "public" role. It does not have an entry in the users table but is reserved.
> 	if normalizedUsername == sqlbase.PublicRole {
> 		return pgerror.NewErrorf(pgerror.CodeReservedNameError, "%s is a reserved role name", sqlbase.PublicRole)
> ```

Any reason not to mirror PG completely here and do `role name "public" is reserved`?

---

*[pkg/sql/logictest/testdata/logic_test/information_schema, line 952 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-LBNDHLEAm1ez4sElJCS:-LBNDHLEAm1ez4sElJCT:bkwqidh) ([raw file](https://github.com/cockroachdb/cockroach/blob/abfff86ce044a56a35a496258a7b7e51841fd313/pkg/sql/logictest/testdata/logic_test/information_schema#L952)):*
> ```
> ----
> grantor  grantee  table_catalog  table_schema        table_name                         privilege_type  is_grantable  with_hierarchy
> NULL     public   system         information_schema  administrable_role_authorizations  SELECT          NULL          NULL
> ```

Postgres seems to capitalize PUBLIC in the grantee column. I'm curious if you think this will be an issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-:-LBNCN4I6h9Pasz248tP:b-355dbh)*

**Comment by mberhault** [comment]
Oops. I missed that, done.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/logictestccl/testdata/logic_test/role, line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-LBNAUJ26wzD-AWuG2bB:-LBQlPZa078KC6Lz6CCD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abfff86ce044a56a35a496258a7b7e51841fd313/pkg/ccl/logictestccl/testdata/logic_test/role#L731)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add tests for revoking to/from the public role.
</blockquote></details>

Done.

---

*[pkg/sql/create_user.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-LBN0fxY1OSs7yyRtAM1:-LBQks_WARIfZQcAJoq2:b34ftkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/abfff86ce044a56a35a496258a7b7e51841fd313/pkg/sql/create_user.go#L86)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any reason not to mirror PG completely here and do `role name "public" is reserved`?
</blockquote></details>

Done. Although as long as the error code matches it really matter if the message does. I mean some of them are just ridiculous. eg: `cannot use special role specifier in DROP ROLE` when running `DROP ROLE public`.

---

*[pkg/sql/logictest/testdata/logic_test/information_schema, line 952 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-LBNDHLEAm1ez4sElJCS:-LBQkyYz44hqUQ-XedFc:bn5wjrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/abfff86ce044a56a35a496258a7b7e51841fd313/pkg/sql/logictest/testdata/logic_test/information_schema#L952)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Postgres seems to capitalize PUBLIC in the grantee column. I'm curious if you think this will be an issue.
</blockquote></details>

If someone does a `WHERE grantee = 'public'`, that's obviously not going to work. We could add a special case for 'public' to either inject a capitalized version, or store it capitalized and ignore all normalization, but that feels really gross.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-:-LBQlUeLBt9osNhFt4pJ:b-hv8k6b)*

**Comment by nvanbenschoten** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25099#-:-LBRrAG9B9r7D09sVZ7U:b-uwkowd)*

**Pull request merged**
