### PR TITLE
liveness: make CreateLivenessRecord retry on a TransactionError

### LINKED ISSUE #50977: cli: TestRemoveDeadReplicas failed
[(cli).TestRemoveDeadReplicas failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2062941&tab=buildLog) on [master@456a07cfc1e53b87abc7709052e54efb1450e758](https://github.com/cockroachdb/cockroach/commits/456a07cfc1e53b87abc7709052e54efb1450e758):

```
=== RUN   TestRemoveDeadReplicas/2/4/r=4
W200704 06:07:10.112919 176174 server/status/runtime.go:310  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W200704 06:07:10.220959 176569 kv/kvserver/store.go:1656  [n1,s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
W200704 06:07:10.440045 176174 server/status/runtime.go:310  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W200704 06:07:10.463437 176174 gossip/gossip.go:1504  [n?] no incoming or outgoing connections
W200704 06:07:10.510884 176174 jobs/registry.go:561  [n2] unable to get node liveness: node not in the liveness table
W200704 06:07:10.514814 176174 server/status/runtime.go:310  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W200704 06:07:10.533440 176174 gossip/gossip.go:1504  [n?] no incoming or outgoing connections
W200704 06:07:10.587817 176174 server/status/runtime.go:310  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W200704 06:07:10.596631 176174 gossip/gossip.go:1504  [n?] no incoming or outgoing connections
W200704 06:07:13.757583 269291 kv/kvserver/intentresolver/intent_resolver.go:440  failed to push during intent resolution: failed to push meta={id=be7c138a key=/Local/Range/Table/14/RangeDescriptor pri=0.00224742 epo=0 ts=1593842833.743310055,0 min=1593842833.743310055,0 seq=7} lock=true stat=PENDING rts=0,0 wto=false max=0,0


ERROR: signal: segmentation fault (core dumped)

68 runs completed, 1 failures, over 49m19s
context canceled

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestRemoveDeadReplicas PKG=./pkg/cli TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRemoveDeadReplicas.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by lunevalex**
Fixes #50977

CreateLivenessRecord has no fault tolerance built in, which makes
the server startup facility flaky. The startup procesure allocates a
nodeId, storeId and then creates a liveness record. If there
is a hiccup or brief period of unavailability during the liveness
creation we end up cycing through node/store ids which is undesirable.
This made the TestRemoveDeadReplicas test flaky because nodes
ended up cycling through a few node ids on startup, making it no possible
to match epected node ids with the actual ones. To fix this issue
we retry liveness creation when it encounters an AmbigiousError
or TransactionError. This is similar behavior to the update code
path for the liveness record.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
s/TransactionError/TransactionStatusError

please rebase on https://github.com/cockroachdb/cockroach/pull/69442 which takes `TransactionStatusError` out of the liveness equation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-:-Mi8Y-AICEXu9ZxZs3Vk:bwyaymc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — COMMENTED** [review]
Approach looks good, I'll leave the details to @andreimatei, thanks both of you!

**Comment by lunevalex** [comment]
> s/TransactionError/TransactionStatusError
> 
> please rebase on #69442 which takes `TransactionStatusError` out of the liveness equation.
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-:-Mi8Y-AICEXu9ZxZs3Vk:bwyaymc)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

@andreimatei if we take `TransactionStatusError` ouf of the equation here, it will not help this flake please note this comment https://github.com/cockroachdb/cockroach/issues/50977#issuecomment-907486389

**Comment by lunevalex** [comment]
@andreimatei rebased, PTAL?

**Review by andreimatei — APPROVED** [review]
:lgtm: with a fix.

Consider adding a test / exercising `CreateLivenessRecord` in the retry tests we already have for the other one. I think I touched some tests in my PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-:-Mjo5osCA2AyY1Kw0KUX:bd8bmmr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lunevalex)

___
*[pkg/kv/kvserver/liveness/liveness.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-Mjo5vox2VkUgAPD8I7E:-Mjo5vox2VkUgAPD8I7F:b-tb3to) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2d3848d56e6df98f6c9dda33b083c556d9cc82/pkg/kv/kvserver/liveness/liveness.go#L80)):*
> ```Go
> 
> func isErrRetryLiveness(err error) bool {
> 	if errors.HasType(err, (*roachpb.TransactionStatusError)(nil)) {
> ```

AmbiguousResultError
___
*[pkg/kv/kvserver/liveness/liveness.go, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-Mjo5-c9-YZ_kGh0bTMC:-Mjo5-c9-YZ_kGh0bTMD:b-hmfdod) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2d3848d56e6df98f6c9dda33b083c556d9cc82/pkg/kv/kvserver/liveness/liveness.go#L580)):*
> ```Go
> 			return err
> 		}
> 		log.VEventf(ctx, 2, "Failed to create liveness record for node %d, because of %s retrying...", nodeID, err)
> ```

log messages start with lowercase. Also I think you want a period after `%s`.
___
*[pkg/kv/kvserver/liveness/liveness.go, line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-Mjo5Uw96jqDolNoKLwN:-Mjo5Uw96jqDolNoKLwO:bjakdkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2d3848d56e6df98f6c9dda33b083c556d9cc82/pkg/kv/kvserver/liveness/liveness.go#L585)):*
> ```Go
> 		return err
> 	}
> 	return errors.Newf("failed to create liveness record for node %d", nodeID)
> ```

I don't think this is reachable. Instead, assert that `ctx.Err()` is non-nil after the loop.

**Review by lunevalex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69501)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/kv/kvserver/liveness/liveness.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-Mjo5vox2VkUgAPD8I7E:-Mm3HBQL90vdq42hQ-oE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2d3848d56e6df98f6c9dda33b083c556d9cc82/pkg/kv/kvserver/liveness/liveness.go#L80)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

AmbiguousResultError
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/liveness/liveness.go, line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-Mjo5-c9-YZ_kGh0bTMC:-Mm3HAbh07K4wnkMuNy0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2d3848d56e6df98f6c9dda33b083c556d9cc82/pkg/kv/kvserver/liveness/liveness.go#L580)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

log messages start with lowercase. Also I think you want a period after `%s`.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/liveness/liveness.go, line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69501#-Mjo5Uw96jqDolNoKLwN:-Mm3HcrUCNVxo4veGyk3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2d3848d56e6df98f6c9dda33b083c556d9cc82/pkg/kv/kvserver/liveness/liveness.go#L585)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think this is reachable. Instead, assert that `ctx.Err()` is non-nil after the loop.
</blockquote></details>

Done.

**Comment by lunevalex** [comment]
@andreimatei finally got a chance to update this and write test, going to leave it open for a couple of days in case you want to take another look.

**Pull request merged**
