### PR TITLE
memo: count partial index predicate selectivity only once

### LINKED ISSUE #104434: unoptimized-query-oracle/opt: estimated zero rows for scan
roachtest.unoptimized-query-oracle/disable-rules=all/rand-tables [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10409513?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10409513?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all/rand-tables) on master @ [530e2ef6d3e974202b2015c22c7ea9eb1c20a29e](https://github.com/cockroachdb/cockroach/commits/530e2ef6d3e974202b2015c22c7ea9eb1c20a29e):

```
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/rand-tables/run_1
(query_comparison_util.go:253).runOneRoundQueryComparison: internal error while running optimized statement. 1344 statements run: pq: internal error: estimated row count must be non-zero
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all/rand-tables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28525

### PR DESCRIPTION
**Pull request by msirek**
When row count on a scan from a partitioned partial index is estimated, and multiple constraint spans are generated for the IN list values in the partitioning expressions, the selectivity of the predicate is applied in a compounding fashion because the call to
```
statisticsBuilder.constrainScan ->
    statisticsBuilder.applyFilters->
        statisticsBuilder.applyFiltersItem
```
modifies the `RowCount` and `Selectivity` in `relProps.Statistics()`. The code is intending to apply the partial index predicate with each span individually to find the selectivity of one constraint span plus the index predicate. But by not resetting `RowCount` and `Selectivity` in between calls to `constrainScan`, the selectivities are multiplied instead of being calculated independently.

The solution is to restore the `RowCount` and `Selectivity` of `relProps.Statistics()` in between calls to `constrainScan`.

Fixes: #104434

Release note (bug fix): This patch fixes a bug in optimizer row count estimates of a scan from a partitioned partial index, which may cause an underestimated row count or a panic if the row count goes to zero.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for the fix!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105966#-:-NZax7uv97JNLgu-Lq4L:b-72sm86)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105966#-NZaw38tCBpzlguoAPEq:-NZaw38tCBpzlguoAPEr:b-o7twz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b677d44fca7cb3ab0eef8d0f9b4e4b6c9fe362b/pkg/sql/opt/memo/statistics_builder.go#L848)):*
> ```Go
> 	// Make a copy of the stats so we don't modify the original.
> 	spanStatsUnion.CopyFrom(s)
> 	origRowCount := s.RowCount
> ```

[nit] I think it would be nicer to make scratch fields (and reset them each iteration) instead of resetting the original ones. Would it be enough to do that with `relProps`? Since `s` is the `Statistics` field of `relProps`. Although, maybe that solution would have noticeable overhead. Up to you.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105966)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105966#-NZaw38tCBpzlguoAPEq:-NZdceFW5H2T_yr46cgC:b-4fwauo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b677d44fca7cb3ab0eef8d0f9b4e4b6c9fe362b/pkg/sql/opt/memo/statistics_builder.go#L848)):*
> I think it would be nicer to make scratch fields

What do you mean by scratch fields?  I don't quite follow what you're saying. Are you suggesting to add new `RowCount` and `Selectivity` fields to `props.Relational` and then instead of calling `Statistics.UnionWith`, do a similar stats unioning operation on the new fields of `props.Relational`?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105966)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105966#-NZaw38tCBpzlguoAPEq:-NZdlV_-8WTvdQvruW7y:b7v91e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b677d44fca7cb3ab0eef8d0f9b4e4b6c9fe362b/pkg/sql/opt/memo/statistics_builder.go#L848)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> I think it would be nicer to make scratch fields

What do you mean by scratch fields?  I don't quite follow what you're saying. Are you suggesting to add new `RowCount` and `Selectivity` fields to `props.Relational` and then instead of calling `Statistics.UnionWith`, do a similar stats unioning operation on the new fields of `props.Relational`?
</blockquote></details>

So, instead of passing `relProps` to `constrainScan` we'd pass `scratchRelProps`, which we'd copy `relProps` into before each iteration. Very nit, though and possibly less performant, so up to you.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105966)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105966#-NZaw38tCBpzlguoAPEq:-NZdwoRoAT-ZVsapUt3P:b-vlkeld) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b677d44fca7cb3ab0eef8d0f9b4e4b6c9fe362b/pkg/sql/opt/memo/statistics_builder.go#L848)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

So, instead of passing `relProps` to `constrainScan` we'd pass `scratchRelProps`, which we'd copy `relProps` into before each iteration. Very nit, though and possibly less performant, so up to you.
</blockquote></details>

I see. Yeah, I was previously looking into a similar fix which copied all of the stats, but felt like it was a bit of overkill, and wasn't sure if it would have a negative impact on garbage collection.  The current fix may look a bit manual, but I feel like it's clearly showing the reader we're only interested in saving and restoring `RowCount` and `Selectivity`.  This fix will keep the number of compiled instructions to a minimum and is guaranteed not to have any GC side effects, so I'd rather just go with this simpler fix.

**Review by DrewKimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105966)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105966#-NZaw38tCBpzlguoAPEq:-NZdzCxb25_8TMoQvRck:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b677d44fca7cb3ab0eef8d0f9b4e4b6c9fe362b/pkg/sql/opt/memo/statistics_builder.go#L848)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I see. Yeah, I was previously looking into a similar fix which copied all of the stats, but felt like it was a bit of overkill, and wasn't sure if it would have a negative impact on garbage collection.  The current fix may look a bit manual, but I feel like it's clearly showing the reader we're only interested in saving and restoring `RowCount` and `Selectivity`.  This fix will keep the number of compiled instructions to a minimum and is guaranteed not to have any GC side effects, so I'd rather just go with this simpler fix.
</blockquote></details>

SGTM

**Review by msirek — COMMENTED** [review]
TFTR!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105966#-:-NZfshKA2Md6KBfXrebD:bihs03x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Pull request merged**
