### PR TITLE
bazel: provide method for constructing distdir for offline builds

### LINKED ISSUE #73316: bazel: provide method for constructing `distdir` for bazel build
[ref](https://docs.bazel.build/versions/main/guide.html#distribution-files-directories)

the `@additional_distfiles//:archives.tar` rule can be consulted as a reference.

Presumably this rule would be auto-generated. We would consult the URL's and SHA's in `WORKSPACE`, `DEPS.bzl`, and other sources (e.g. toolchains in `build/toolchains`) to construct a list of "all" archives needed to build, and then auto-generate the rule in that way. Also provide documentation on how to build the `distdir`, how to specify `--distdir` on the command-line for building in an airgapped environment, etc.

Epic CRDB-8306

Jira issue: CRDB-11538

### PR DESCRIPTION
**Pull request by rickystewart**
This commit enables bootstrapping a `distdir` containing all the
dependencies. In doing so you can easily perform offline builds. In
particular, you can now do the following:

```
bazel build @distdir//:archives
mkdir -p ~/distdir
tar -xzf _bazel/bin/external/distdir/archives.tar --strip-components=1 -C ~/distdir
```

Doing so will decompress all the dependencies needed for the build into
`~/distdir`. At this point you can build with the command-line flag
`--distdir=~/distdir` which will direct Bazel to consult the `~/distdir`
directory instead of hitting the network where possible.

To enable this we do all of the following:

1. Update `WORKSPACE` to contain SHA256 sums for the Go SDK and
   node/yarn. This doesn't change the functionality of the actual build
   (the same data is baked-in in the `rules_go` and `rules_nodejs`
   libraries) but makes it easier to enumerate all the archives we
   depend on.
2. Vendor the `rules_pkg` library that we'll use for building the
   `distdir`.
3. Add a new `generate-distdir` binary that enumerates all of the URL's
   that we depend on for the build. We have to check in three places:
   `WORKSPACE`, `DEPS.bzl`, and the `c-deps` directory. Integrate this
   with `dev generate bazel`. For the most part we search for
   `http_archive`s and add each URL/SHA256 that we find to the list, but
   the `c-deps`, Go SDK, and Node/Yarn require special handling.
4. Add a new `distdir` repository rule to capture all of the
   dependencies. The `@distdir//:archives` target consumes the list of
   URL's and SHA's produced by `generate-distdir` and builds a single
   `.tar` file.

Closes https://github.com/cockroachdb/cockroach/issues/73316.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Wrote new documentation to cover this: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/2524381398/Offline+builds+with+Bazel

**Review by rail — APPROVED** [review]
Wooooooooo! This looks great! TYVM, now we can compile on a plane ;)
The linter errors look like lies to me, no idea why... :thinking: 
Just need to update `CODEOWNERS`.

> Reviewed 6 of 7 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80512#-:-N0aDlxCCc1ICyGIGFuP:b-76m30s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mari-crl)

___
*[`pkg/build/starlarkutil/starlarkutil.go` line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80512#-N0aCCwn1DCRIYXMYKx6:-N0aCCwn1DCRIYXMYKx7:b-angnkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e795429889bac8966971c4e0de45cdb22d8b3c/pkg/build/starlarkutil/starlarkutil.go#L64)):*
> ```Go
> }
> 
> func downloadableArtifactsFromDepsBzl(in interface{}) (map[string]DownloadableArtifact, error) {
> ```

Not a big deal, but we can limit `in` to `io.Reader`.

**Comment by rickystewart** [comment]
> The linter errors look like lies to me, no idea why... 🤔

Yeah, the non-Bazel linter gets confused about Bazel-only code. I'll disable it.

> Just need to update CODEOWNERS.

Done.

> Not a big deal, but we can limit in to io.Reader.

I've kept it as `interface{}` so I can pass a `string` to the function in the tests.

**Comment by rickystewart** [comment]
TFTR!

bors r=rail

**Pull request merged**
