### PR TITLE
exec: add count and any not null aggs

### PR DESCRIPTION
**Pull request by jordanlewis**
Add 2 new aggregates - COUNT(*) and ANY_NOT_NULL. The latter is required for most group bys.

Once this and #32673 are merged, we'll be able to fully run TPC-H q1.

Previously, since exec couldn't import distsqlrun directly, it had to
duplicate the aggregator func enum. Now that the protos have been moved
to distsqlpb, exec can import them and use rather than having to mimic
the enum.

```
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1/numInputBatches=1-8                 1000000              1093 ns/op        7492.63 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1/numInputBatches=2-8                 1000000              1964 ns/op        8341.59 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1/numInputBatches=64-8                  30000             57372 ns/op        9138.24 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=512/numInputBatches=1-8               1000000              1058 ns/op        7741.03 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=512/numInputBatches=2-8               1000000              1961 ns/op        8354.28 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=512/numInputBatches=64-8                30000             57550 ns/op        9110.11 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1024/numInputBatches=1-8              1000000              1058 ns/op        7737.66 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1024/numInputBatches=2-8              1000000              1961 ns/op        8354.85 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1024/numInputBatches=64-8               30000             57410 ns/op        9132.34 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1/numInputBatches=1-8                   1000000              1263 ns/op        6484.39 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1/numInputBatches=2-8                   1000000              2128 ns/op        7697.26 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1/numInputBatches=64-8                    30000             57414 ns/op        9131.67 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=512/numInputBatches=1-8                 1000000              1223 ns/op        6697.72 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=512/numInputBatches=2-8                 1000000              2116 ns/op        7739.48 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=512/numInputBatches=64-8                  30000             57648 ns/op        9094.49 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1024/numInputBatches=1-8                1000000              1225 ns/op        6683.79 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1024/numInputBatches=2-8                1000000              2157 ns/op        7592.34 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1024/numInputBatches=64-8                 30000             58543 ns/op        8955.46 MB/s
```

Also, fix a couple of small bugs in aggregation.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Great stuff

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 3 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-:-LTawzRn0WTMTAlQ3i7c:b-9g0l9g)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYcZoC-t-4CF3AO5b4:-LTYcZoC-t-4CF3AO5b5:bpb7yvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836269d93ad4c471f6500bdc7ec0e0709daf7a7/pkg/sql/exec/aggregator.go#L204)):*
> ```Go
> 			continue
> 		}
> 		a.outputTyps[i] = a.aggTyps[i][0]
> ```

Would it be possible to set this in `NewOrderedAggregator` rather than in `Init` so that you have access to the agg function? I'm wondering if you could also pass in the output types to `NewOrderedAggregator`.
___
*[pkg/sql/exec/aggregator.go, line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYddyDD0StyROUrLmO:-LTYddyDD0StyROUrLmP:bpvibjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836269d93ad4c471f6500bdc7ec0e0709daf7a7/pkg/sql/exec/aggregator.go#L233)):*
> ```Go
> 			// the current index must also be copied.
> 			a.scratch.ColVec(i).Copy(a.scratch.ColVec(i), a.scratch.outputSize, a.scratch.resumeIdx+1, a.outputTyps[i])
> 			a.aggregateFuncs[i].SetOutputIndex(newResumeIdx)
> ```

I assume this is caught by tests now?
___
*[pkg/sql/exec/aggregator_test.go, line 396 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYVoL31K_SEB_R1OyM:-LTYVoL31K_SEB_R1OyN:ben8rb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c7810d2d3c0998e85048e9c23db7740a5eb1e1c/pkg/sql/exec/aggregator_test.go#L396)):*
> ```Go
> 
> 	for _, aggFn := range []distsqlpb.AggregatorSpec_Func{
> 		distsqlpb.AggregatorSpec_ANY_NOT_NULL,
> ```

What are the benchmark results?
___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYVq1u9IMoOgcdx-bC:-LTYVq1u9IMoOgcdx-bD:b74nxzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c7810d2d3c0998e85048e9c23db7740a5eb1e1c/pkg/sql/exec/any_not_null_agg_tmpl.go#L32)):*
> ```Go
> )
> 
> func newAnyNotNullAgg(t types.T) (aggregateFunc, error) {
> ```

This might be a dumb question but what is an any not null aggregate function used for? I've only seen it used to output the value of a grouping column.
___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYYONQ3kg9pImhFuWH:-LTYYONQ3kg9pImhFuWI:b-h878fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c7810d2d3c0998e85048e9c23db7740a5eb1e1c/pkg/sql/exec/any_not_null_agg_tmpl.go#L107)):*
> ```Go
> 		sel = sel[:inputLen]
> 		for _, i := range sel {
> 			if a.groups[i] {
> ```

It seems kind of impossible to do this without an if statement, right?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32969)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYcZoC-t-4CF3AO5b4:-LTd6Xw9-UFb_sn8qHWv:b-yy3yq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836269d93ad4c471f6500bdc7ec0e0709daf7a7/pkg/sql/exec/aggregator.go#L204)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Would it be possible to set this in `NewOrderedAggregator` rather than in `Init` so that you have access to the agg function? I'm wondering if you could also pass in the output types to `NewOrderedAggregator`.
</blockquote></details>

Good call - done.
___
*[pkg/sql/exec/aggregator.go, line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYddyDD0StyROUrLmO:-LTd7Sda-AyOa4JhIqy4:b-q94e8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836269d93ad4c471f6500bdc7ec0e0709daf7a7/pkg/sql/exec/aggregator.go#L233)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I assume this is caught by tests now?
</blockquote></details>

Yes, the new randomized tests catch this issue.
___
*[pkg/sql/exec/aggregator_test.go, line 396 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYVoL31K_SEB_R1OyM:-LTd632p3AbDKWpn1MUY:br20uf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c7810d2d3c0998e85048e9c23db7740a5eb1e1c/pkg/sql/exec/aggregator_test.go#L396)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What are the benchmark results?
</blockquote></details>

```
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1/numInputBatches=1-8                 1000000              1093 ns/op        7492.63 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1/numInputBatches=2-8                 1000000              1964 ns/op        8341.59 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1/numInputBatches=64-8                  30000             57372 ns/op        9138.24 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=512/numInputBatches=1-8               1000000              1058 ns/op        7741.03 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=512/numInputBatches=2-8               1000000              1961 ns/op        8354.28 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=512/numInputBatches=64-8                30000             57550 ns/op        9110.11 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1024/numInputBatches=1-8              1000000              1058 ns/op        7737.66 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1024/numInputBatches=2-8              1000000              1961 ns/op        8354.85 MB/s
BenchmarkAggregator/ANY_NOT_NULL/groupSize=1024/numInputBatches=64-8               30000             57410 ns/op        9132.34 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1/numInputBatches=1-8                   1000000              1263 ns/op        6484.39 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1/numInputBatches=2-8                   1000000              2128 ns/op        7697.26 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1/numInputBatches=64-8                    30000             57414 ns/op        9131.67 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=512/numInputBatches=1-8                 1000000              1223 ns/op        6697.72 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=512/numInputBatches=2-8                 1000000              2116 ns/op        7739.48 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=512/numInputBatches=64-8                  30000             57648 ns/op        9094.49 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1024/numInputBatches=1-8                1000000              1225 ns/op        6683.79 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1024/numInputBatches=2-8                1000000              2157 ns/op        7592.34 MB/s
BenchmarkAggregator/COUNT_ROWS/groupSize=1024/numInputBatches=64-8                 30000             58543 ns/op        8955.46 MB/s
```
___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYVq1u9IMoOgcdx-bC:-LTd58mC9Bd8Hw5BN_lu:bhldmdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c7810d2d3c0998e85048e9c23db7740a5eb1e1c/pkg/sql/exec/any_not_null_agg_tmpl.go#L32)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This might be a dumb question but what is an any not null aggregate function used for? I've only seen it used to output the value of a grouping column.
</blockquote></details>

It's used to output the value of a grouping column. That's it! Sometimes DistSQL needs to emit them for internal reasons as well, I believe.
___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-LTYYONQ3kg9pImhFuWH:-LTd5HXc4nu-ANw8ZvfS:bphb8o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c7810d2d3c0998e85048e9c23db7740a5eb1e1c/pkg/sql/exec/any_not_null_agg_tmpl.go#L107)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It seems kind of impossible to do this without an if statement, right?
</blockquote></details>

I think so, yeah.

**Review by asubiotto — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32969#-:-LTwxCU9-OPbEbKpYd5W:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
