### PR TITLE
server: Hide VirtualSchemas from admin API calls

### LINKED ISSUE #9689: ui: many errors on node page resulting from virtual tables
On my local machine, with a vanilla `master`, I navigate to http://localhost:8080/#/nodes/1 and my chrome console fills with:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:8080/_admin/v1/databases/pg_catalog Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:8080/_admin/v1/databases/information_schema Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2http://localhost:8080/_admin/v1/databases/pg_catalog Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:8080/_admin/v1/databases/information_schema Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:8080/_admin/v1/databases/pg_catalog Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:8080/_admin/v1/databases/information_schema Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:8080/_admin/v1/databases/pg_catalog Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:8080/_admin/v1/databases/information_schema Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

### PR DESCRIPTION
**Pull request by nvb**
Resolves #9689.

In person, it had been decided that the best approach to dealing with
virtual schemas from the admin UI was to ignore them. They don't add a
lot of value to users, and they don't make sense in the context of
endpoints like `TableStats`. This change simply ignores these schemas in
all relevant API calls.

I'm not sure if a `404` error is correct here.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10920)

### CODE REVIEW

**Comment by tamird** [comment]
404 is probably not right. you probably want something that maps to a 400. Also, tests?

How come you never have to call `IsVirtualTable`?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10920#-:-KX7sx_MxQx5vW54Utin:bkxe32e)*

**Comment by nvanbenschoten** [comment]
Added tests, switched to a 400, and pulled out the virtual schema assertion into a helper. PTAL.

`IsVirtualTable` is never needed because we already check if the database is a virtual schema.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10920#-:-KX8F2wh95-rxRTeyv__:b-22jzor)*

**Comment by tamird** [comment]
So it's not possible for a non-virtual database to contain a virtual table?

:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/admin.go, line 524 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10920#-KX8LxlkCR8e8WVGbK21:-KX8LxlkCR8e8WVGbK22:b-l6mwxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f513849f4f6e2e5efb75fb45bd639967b1f59209/pkg/server/admin.go#L524)):*
> ```Go
> 	ctx context.Context, req *serverpb.TableStatsRequest,
> ) (*serverpb.TableStatsResponse, error) {
> ```

remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10920#-:-KX7siksTNlL8x-0F_xc:bcbs1gg)*

**Comment by nvanbenschoten** [comment]
No, that is not possible. TFTR

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/admin.go, line 524 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10920#-KX8LxlkCR8e8WVGbK21:-KX8RNlwoOzNr9JJc2YH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f513849f4f6e2e5efb75fb45bd639967b1f59209/pkg/server/admin.go#L524)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> remove
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10920#-:-KX8RKlw4MuG6Kk2P50x:b-wynft)*

**Pull request merged**
