### PR TITLE
streamingccl: support restoring a tenant X from replication stream in to a new tenant Y

### LINKED ISSUE #76946: Support restoring tenant X from replication stream into a new tenant Y
Add support for restoring a tenant into a cluster with new tenant ID from a replication stream as a tenant ID is globally unique across clusters.

Only the tenant key space will be restored and any other data that reference this tenant ID (tenant being restored) will not.

Jira issue: CRDB-13338

Epic CRDB-14842

### PR DESCRIPTION
**Pull request by gh-casper**
Closes: https://github.com/cockroachdb/cockroach/issues/76946

Release note (sql change): Extend stream replication statement to be
RESTORE TENANT $1 FROM REPLICATION STREAM FROM $2 AS TENANT $3.

Release justification: Category 4.

### CODE REVIEW

**Comment by miretskiy** [comment]
I would like to separate key rewriter stuff into separate commit w/ its own tests.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 17 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @gh-casper)

___
*[pkg/ccl/backupccl/key_rewriter.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxiuLgp4ZPzvDOXXRKC:-MxiuLgp4ZPzvDOXXRKD:b-5s40la) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/backupccl/key_rewriter.go#L88)):*
> ```Go
> 
> 	// Whether we are using this KeyWriter to restore a tenant from a replication stream.
> 	restoreTenantFromStream bool
> ```

Not clear why we need this.  Can't we determine that based on the fact that we have tenant rekey w/ different tenant ids?
___
*[pkg/ccl/streamingccl/streamclient/random_stream_client.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxivpQe75rIJyVfp4Fr:-MxivpQe75rIJyVfp4Fs:byqvpaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L408)):*
> ```Go
> 
> 			if event.Type() == streamingccl.KVEvent {
> 				// Use the originally generated KeyValue copy as the event might get modified.
> ```

who's modifying?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxiwG_97QW1cy0HLbvZ:-MxiwG_97QW1cy0HLbv_:bwbzq9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go#L167)):*
> ```Go
> 
> 		//TODO(casper): make target to be tenant only and add validation check, e.g., both
> 		// target tenant and new tenant cannot be system tenant.
> ```

I think it's a good idea to add check against system tenant id now.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxixLzCAN1Qb9RAaAcx:-MxixLzCAN1Qb9RAaAcy:bjtiznl) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L556)):*
> ```Go
> 		return errors.New("kv event expected to have kv")
> 	}
> 	if sip.rekeyer != nil {
> ```

In general, we will always have a rekey-er; I suppose the exception is if you restore into the same tenant.
Would it make sense to create a no-op rekeyer in that case so that we don't have to check sip.rekeyer != nil?
___
*[pkg/sql/parser/sql.y, line 3120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxixpWW92n_uZusI8yd:-MxixpWW92n_uZusI8ye:ba8nin1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/sql/parser/sql.y#L3120)):*
> ```Yacc
> | RESTORE targets FROM REPLICATION STREAM FROM string_or_placeholder_opt_list opt_as_of_clause AS TENANT a_expr
>   {
>    $$.val = &tree.StreamIngestion{
> ```

Would be nice to add a data driven test for parsing.
See e.g. `pkg/sql/parser/testdata/alter_changefeed`.
This can be done in a separate PR.
___
*[pkg/sql/parser/sql.y, line 3124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxiwrBT7xfu8ZqnK1mC:-MxiwrBT7xfu8ZqnK1mD:b-9zcerb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/sql/parser/sql.y#L3124)):*
> ```Yacc
>      From: $7.stringOrPlaceholderOptList(),
>      AsOf: $8.asOfClause(),
>      AsTenant: $11.expr(),
> ```

This is probably too wide -- expr is any SQL expr, and looking at stream creation code, you don't support
arbitrary expression, and require AsTenatn to be an int.  Why not require tenant to be an iconst64, and just use `$11.int64()`
___
*[pkg/ccl/backupccl/key_rewriter_test.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-Mxiu_zoDZB4Qqb6si0z:-Mxiu_zoDZB4Qqb6si1-:b-x1zzzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/backupccl/key_rewriter_test.go#L157)):*
> ```Go
> 			newKr, err := MakeKeyRewriterFromRekeys(destCodec, []execinfrapb.TableRekey{
> 				{OldID: uint32(oldID), NewDesc: mustMarshalDesc(t, desc.TableDesc())},
> 			}, nil /* tenantRekeys */, false /* restoreTenantFromStream */)
> ```

we probably need to add tests which rewrite into another tenant.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-Mxiuo7M8_3oKo_rqKlc:-Mxiuo7M8_3oKo_rqKld:b3bxns9) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go#L121)):*
> ```Go
> 		}
> 		highwater := timeutil.Unix(0, progress.GetHighWater().WallTime)
> 		fmt.Printf("highwater: %s cutover: %s\n", highwater, cutoverTime)
> ```

stray fmt.Printf?

**Review by gh-casper — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-:-MycpPk-8mSYKbYzzvNs:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/key_rewriter.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxiuLgp4ZPzvDOXXRKC:-MyTmYfI19W71FPmIR2r:bb7z46m) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/backupccl/key_rewriter.go#L88)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Not clear why we need this.  Can't we determine that based on the fact that we have tenant rekey w/ different tenant ids?
</blockquote></details>

Changed this. Now reusing the variable `fromSystemTenant` since only system tenant can restore a tenant from replication stream.
___
*[pkg/ccl/streamingccl/streamclient/random_stream_client.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxivpQe75rIJyVfp4Fr:-MyTndZa3Z_l4issTDpA:b-msosr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L408)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

who's modifying?
</blockquote></details>

Ingestion processor's key rewriter may modify the event. The random client is doing extra logic after it sends the event: calling the interceptor on the sent event which might get modified so it should be the random client (instead of ingestion processor) that create another copy of the original event and makes sure the interceptor was called on the original copy.



_Code quote:_
```Go
				// Use the originally generated KeyValue copy as the event might get modified.
```
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxiwG_97QW1cy0HLbvZ:-MyTwn-51Szglke0flj_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go#L167)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think it's a good idea to add check against system tenant id now.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxixLzCAN1Qb9RAaAcx:-MyVj8uA8BpBp9SfhOZR:b-mv3222) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L556)):*
> rekeyer
Done. Rekeyer's prefixRewrite indeed has a noop flag which is turned on when old tenant ID is equal to the new tenant ID.
___
*[pkg/sql/parser/sql.y, line 3120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxixpWW92n_uZusI8yd:-MyVjgpl9MRW8PSg1ogT:b416p9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/sql/parser/sql.y#L3120)):*
> alter_changefeed
Sure. Will do it in another PR.
___
*[pkg/sql/parser/sql.y, line 3124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MxiwrBT7xfu8ZqnK1mC:-Myf8aOh87dnwodKA7tr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/sql/parser/sql.y#L3124)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is probably too wide -- expr is any SQL expr, and looking at stream creation code, you don't support
arbitrary expression, and require AsTenatn to be an int.  Why not require tenant to be an iconst64, and just use `$11.int64()`


</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/key_rewriter_test.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-Mxiu_zoDZB4Qqb6si0z:-Mycp7xeBwgjdU7xQAb-:b-fyuioz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/backupccl/key_rewriter_test.go#L157)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we probably need to add tests which rewrite into another tenant.
</blockquote></details>

Have added unit tests for MakeKeyRewriterFromRekeys in another PR. We also have e2e test that rewrites into another tenant for this in this PR.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-Mxiuo7M8_3oKo_rqKlc:-MycpOU46g06t2Yv1_CE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea76b9dca01964584421679d73a27c2b695cb19/pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go#L121)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

stray fmt.Printf?
</blockquote></details>

Done.

**Review by gh-casper — COMMENTED** [review]
Make it a separate DRAFT PR https://github.com/cockroachdb/cockroach/pull/78164. If necessary, I can request it for separate review as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-:-Myf8izW508jXbRR2cmv:bjxeshw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 5 of 23 files at r2, 12 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @gh-casper, and @miretskiy)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MygIUrE0YVjUhYTHPuh):*
need release justification.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 561 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MygJrKz1dLS515ZQGHz:-MygJrKz1dLS515ZQGI-:bsjyise) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5be7848773752f9111b378384d0aa7d36d10602/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L561)):*
> ```Go
> 	kv.Key = rekey
> 	kv.Value.ClearChecksum()
> 	kv.Value.InitChecksum(kv.Key)
> ```

do we have to do this even if we didn't rekey?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_test_utils.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MygK1W77InkXZWqPKA3:-MygK1W77InkXZWqPKA4:bic47p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5be7848773752f9111b378384d0aa7d36d10602/pkg/ccl/streamingccl/streamingest/stream_ingestion_test_utils.go#L25)):*
> ```Go
> 	rekeyer *backupccl.KeyRewriter
> 
> 	mu syncutil.Mutex
> ```

what is this mu protecting?
___
*[pkg/sql/parser/sql.y, line 974 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MygKKag9Ovld7-JMNCY:-MygKKag9Ovld7-JMNCZ:bqykjih) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5be7848773752f9111b378384d0aa7d36d10602/pkg/sql/parser/sql.y#L974)):*
> ```Yacc
> 
> // ALTER TENANT CLUSTER SETTINGS
> %type <tree.Statement> alter_tenant_csetting_stmt
> ```

csetting? a typo?
___
*[pkg/sql/parser/sql.y, line 6794 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-MygKQY866pqvvEIM_rV:-MygKQY866pqvvEIM_rW:b15o210) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5be7848773752f9111b378384d0aa7d36d10602/pkg/sql/parser/sql.y#L6794)):*
> ```Yacc
>   }
> // TODO(knz): This should learn how to parse more complex expressions
> // and placeholders.
> ```

not sure why this todo is shown as modified?

**Review by miretskiy — APPROVED** [review]
Somebody from bulk should also take a look; mostly nits from me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77521#-:-MygKkAN9gqEjBmX9gm0:b-utg6dz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @gh-casper, and @miretskiy)

**Pull request merged**
