### PR TITLE
server: add a node debug page

### PR DESCRIPTION
**Pull request by BramGruneir**
This page shows version information as well as environment variables and arguments that were used when starting up each node.

Clearly more needs to be added here, but it's a start.

screen shot 2017-06-02 at 23 24 48

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: though the table is going to get unmanageable when you get more than a handful of nodes in a cluster. Perhaps the default should be to show a single node.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-:-Klj9-mqqZelpKiUMsFz:buppgiw)*

**Comment by mberhault** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/debug_nodes.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-KljBeXSRFuSVjHRoVmm:-KljBeXSRFuSVjHRoVmn:bh0wnd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f90968890a8a4b944f52f404f1dc57e2e863d6/pkg/server/debug_nodes.go#L203)):*
> ```Go
> 		addOutput(2, nodeStatus.Desc.Locality.String())
> 		addOutputs(3, nodeStatus.Desc.Attrs.Attrs)
> 		addOutputs(4, nodeStatus.Env)
> ```

env might contain some sensitive information (eg: cloud credentials). We should be careful about those, either censoring them, or dropping them entirely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/debug_nodes.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-KljBeXSRFuSVjHRoVmm:-KljDfUmJsCgZcOSQTRz:bywh8h5) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f90968890a8a4b944f52f404f1dc57e2e863d6/pkg/server/debug_nodes.go#L203)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

env might contain some sensitive information (eg: cloud credentials). We should be careful about those, either censoring them, or dropping them entirely.
</blockquote></details>

We could have a regex that filters which env vars are shown. Something like: `^(GO|COCKROACH_).*`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300)*

**Comment by BramGruneir** [comment]
Done.  Now the first link shows only the local node.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/debug_nodes.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-KljBeXSRFuSVjHRoVmm:-KlsksoKyqEiXbjmSGrP:bydo5ss) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f90968890a8a4b944f52f404f1dc57e2e863d6/pkg/server/debug_nodes.go#L203)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We could have a regex that filters which env vars are shown. Something like: `^(GO|COCKROACH_).*`.
</blockquote></details>

Done.  Perhaps we should do this before storing the node statuses altogether?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-:-KlsoH4zD3I2Qda4SUYY:bf2p7yu)*

**Comment by BramGruneir** [comment]
Can I get a quick final review so I can merge this?  Got another PR ready to go already.

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/debug.go, line 153 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-KltSShO_Wm0MnehKxVw:-KltSShO_Wm0MnehKxVx:bwt9p69) ([raw file](https://github.com/cockroachdb/cockroach/blob/933ffb7f3c647e3a797dec4bd029ce0c376694ba/pkg/server/debug.go#L153)):*
> ```Go
>       </tr>
>       <tr>
>         <td>nodes diagnostics</td>
> ```

`s/nodes/node/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300)*

**Comment by BramGruneir** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/debug.go, line 153 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-KltSShO_Wm0MnehKxVw:-KltTHGF9Ruo5DOJ55ca:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/933ffb7f3c647e3a797dec4bd029ce0c376694ba/pkg/server/debug.go#L153)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/nodes/node/g`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/debug_nodes.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-KljBeXSRFuSVjHRoVmm:-KltUkLjT0RrSWafst2i:b-epa2h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f90968890a8a4b944f52f404f1dc57e2e863d6/pkg/server/debug_nodes.go#L203)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Done.  Perhaps we should do this before storing the node statuses altogether?
</blockquote></details>

Yeah, we should filter these early instead of storing the whole environment. Even `^GO` seems too broad - it could match something like `GOOGLE_API_KEY` (although google's CLI tools apparently use a `CLOUDSDK` prefix instead). Maybe it should whitelist all the known Go env vars instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16300#-:-KltVkMvZGrGm_2buX_W:bnfp4nl)*

**Pull request merged**
