### PR TITLE
sql,server: support SCRAM authentication for SQL sessions

### LINKED ISSUE #42519: security: support SCRAM-SHA-256 authentication method
### Summary

Add the SCRAM-SHA-256 auth method:

- [ ] extend WITH PASSWORD to recognize scram passwords and store the client-supplied hashes in `system.users` (distinguish pw encoding types using a prefix; our current `bcrypt`-based encoding always starts with `$`, and pg's implementation has a standard encoding that starts with `scran-sha-256:` and 5 fields)
- [ ] allow specifying the SCRAM method in the HBA config
- [ ] implement the SCRAM exchange in pgwire w/ tests
- [ ] Add support for the `password_encryption` session setting: https://www.postgresql.org/docs/current/runtime-config-connection.html

### Protocol summary

Example SCRAM client-server exchange as per [RFC 7677](https://tools.ietf.org/html/rfc7677):

```
   This is a simple example of a SCRAM-SHA-256 authentication exchange
   when the client doesn't support channel bindings.  The username
   'user' and password 'pencil' are being used.

   C: n,,n=user,r=rOprNGfwEbeRWgbNEkqO

   S: r=rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF$k0,
      s=W22ZaJ0SNY7soEsUEjb6gQ==,i=4096

   C: c=biws,r=rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF$k0,
      p=dHzbZapWIk4jUhN+Ute9ytag9zjfMHgsqmmiz7AndVQ=

   S: v=6rriTRBi23WpRR/wtup+mMhUZUn/dB5nLTJRsjl95G4=
```

Summary of the protocol as per [RFC 5802](https://tools.ietf.org/html/rfc5802):

```
     SaltedPassword  := Hi(Normalize(password), salt, i)
     ClientKey       := HMAC(SaltedPassword, "Client Key")
     StoredKey       := H(ClientKey)
     AuthMessage     := client-first-message-bare + "," +
                        server-first-message + "," +
                        client-final-message-without-proof
     ClientSignature := HMAC(StoredKey, AuthMessage)
     ClientProof     := ClientKey XOR ClientSignature
     ServerKey       := HMAC(SaltedPassword, "Server Key")
     ServerSignature := HMAC(ServerKey, AuthMessage)

   The server authenticates the client by computing the ClientSignature,
   exclusive-ORing that with the ClientProof to recover the ClientKey
   and verifying the correctness of the ClientKey by applying the hash
   function and comparing the result to the StoredKey.  If the ClientKey
   is correct, this proves that the client has access to the user's
   password.

   Similarly, the client authenticates the server by computing the
   ServerSignature and comparing it to the value sent by the server.  If
   the two are equal, it proves that the server had access to the user's
   ServerKey.
```

What gets stored in the database:

```
   If the password is
   encrypted with SCRAM-SHA-256, it consists of 5 fields separated by colons.
   The first field is the constant <literal>scram-sha-256</literal>, to
   identify the password as a SCRAM-SHA-256 verifier. The second field is a
   salt, Base64-encoded, and the third field is the number of iterations used
   to generate the password.  The fourth field and fifth field are the stored
   key and server key, respectively, in hexadecimal format. A password that
   does not follow either of those formats is assumed to be unencrypted.
```

### Special note about SCRAM for SQL

>  SCRAM specifies `"n=user"` is the username in the initial client message.
>  However, in PostgreSQL the username is sent in the startup packet, and
> the username in the SCRAM exchange is ignored.  libpq always sends it
> as an empty string.

postgres source code, function `read_client_first_message` in `auth-scram.c`

### Special note about leaking information

> If a user doesn't exist, perform a "mock" authentication, by constructing
> an authentic-looking challenge on the fly. The challenge is derived from
> a new system-wide random value, "mock authentication nonce", which is
> created at initdb, and stored in the control file. We go through these
> motions, in order to not give away the information on whether the user
> exists, to unauthenticated users.

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=818fd4a67d610991757b610755e3065fb99d80a5#patch11

### References

- Reference docs:
  - [RFC 5802](https://tools.ietf.org/html/rfc5802) defines SCRAM
  - [RFC 7677](https://tools.ietf.org/html/rfc7677) specializes SCRAM to SHA-256
  - [patch that added SCRAM to the pg source code](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=818fd4a67d610991757b610755e3065fb99d80a5#patch11)
  - [pg docs about scram auth](https://www.postgresql.org/docs/current/sasl-authentication.html#SASL-SCRAM-SHA-256)

- Example implementations:

  - [simple SCRAM client code in the Go MongoDB driver](https://github.com/go-mgo/mgo/blob/v2/internal/scram/scram.go)
  - [PR that added SCRAM support in lib/pq](https://github.com/lib/pq/pull/833)

 
### Motivation

Postgres added support for [SCRAM-SHA-256](https://www.postgresql.org/docs/current/sasl-authentication.html#SASL-SCRAM-SHA-256) password encryption in version 10. This is a more modern password authentication mechanism than the old "MD5" password authentication mechanism that pg was previously using. 

Note that CockroachDB doesn't even support MD5 authentication, and instead requires the client to present the password in cleartext. This is because CRDB uses a non-standard  encoding of the password hash in-DB using bcrypt.

The benefit of SCRAM is twofold:

1. it increases overall server security, by ensuring that **the server never sees cleartext passwords** even during authn verification.

2. it pushes the CPU cost of password checks to the client-side.

Note that implementing pg's native MD5 authentication would achieve the same goals, but MD5 authn is vulnerable to various attack vectors where SCRAM is not.

Epic CRDB-5349

### LINKED ISSUE #74511: security: provide controls and automation to upgrade password hash complexities
This issue is a followup to https://github.com/cockroachlabs/managed-service/pull/7408
and [this comment](https://github.com/cockroachdb/cockroach/pull/74301#issuecomment-1006058457)

Requested by @aaron-crl and @bdarnell 

### Description of problem

Currently the password code fixes the bcrypt cost to 10 used when generating/storing new password hashes server-side.
The scram PR #74301 follows this model and hardcodes  4096 as the pkbf2 iteration count.

Both values are very low and have become inadequate as of 2022.
They are meant to be increased over time has hardware performance increases. 

@bdarnell recalls a heuristic that the bcrypt cost should be increased by 1 each year; and that for pkbf2 / sha256, folk were already using 64000 iterations a few years ago.

**CockroachDB should provide some mechanism to evolve the cost function over time**

### Design ideas

A simple design could be to provide a cluster setting that controls the cost used for **new passwords**. 
For long-lived CockroachDB deployments, we could ship increases to the default value of the cluster setting in patch releases.

A question then arises of what to do with existing passwords, created with a previous (lower) iteration count.

For this, we can observe that increasing the iteration count is an associative operation: iter(iter(H, x), y) = iter(H, x+y)
This means that we can increase the iteration count for an already-computed hash by simply further iterating the hash function on the hash that's stored already.

This helps us define an **automatic upgrade for existing passwords**: a process that iterates over `system.users.hashedPassword` and further hashes up to the value indicated by the current target cost.

### Design constraint: fixed iteration counts

We have offered operators the ability to pre-hash passwords and store pre-computed hashes.

We should assume that operators are interested to control the cost function. For example, in the CC control plane we generate hashes with a lower iteration count, because we control the entropy of the generated password (see https://github.com/cockroachlabs/managed-service/pull/7408). 

When the operator controls the iteration count, we do not wish to automatically update it inside CockroachDB.

### Design sketch

- a cluster setting sets the desired target cost.
- the default value of that cluster setting is increased in patch releases over time.
- when a new password is generated from plaintext server-side, we use the cluster setting to select the cost.
- we start storing, in the `system.users.hashedPassword` column using the format prefix, a bit that indicates whether the cost was auto-selected by crdb or was manually set by an operator.
- (optionally, see comments below) we modify the CC control plane (extending [this PR](https://github.com/cockroachlabs/managed-service/pull/7408)) to use that bit to force the cost function to remain fixed.
- periodically, we scan `system.users` and upgrade the non-fixed hashes to the configured target cost in the cluster setting.

Epic CRDB-5349

### PR DESCRIPTION
**Pull request by knz**
Fixes #42519.
Fixes #74511.
Informs #65117.
Epic CRDB-5349

**tldr:** this PR adds support for the SCRAM-SHA-256 authentication method, as defined by IETF RFCs [5802](https://datatracker.ietf.org/doc/html/rfc5802) and [7677](https://datatracker.ietf.org/doc/html/rfc7677) and as supported by PostgreSQL. This offers [multiple security benefits](#scram-benefits) over CockroachDB's current use of cleartext password authentication. To use this feature,
1) the stored password hashes must use the SCRAM encoding (this requires a migration away from crdb's bcrypt-based hashes); and
2) one of the SCRAM authentication methods must be enabled explictly via the HBA configuration (cluster setting `server.host_based_authentication.configuration`).

### How to review this work

The addition of the feature goes as follows:

1. adding HBA syntax and authentication method hooks for `scram-sha-256` and `cert-scram-sha-256`. These are gated behind a new cluster version, so that previous-version nodes do not get confused by the new syntax.

   Split into separate PR: #74842

2. extending ALTER/CREATE USER/ROLE WITH PASSWORD to recognize SCRAM hashes. This allows operators to use these SQL statements to populate SCRAM hashes.
    (This should also be seen as the more desirable way to configure SQL user accounts: it ensures that the CockroachDB node never ever sees the cleartext password of an account. Even if we later support computing the SCRAM hash server-side, pre-computing the hash client-side should be seen and documented as the superior approach.)

   Split into separate PR: #74843

3. extending the existing cleartext methods inside CockroachDB (used for the HTTP interface and the `password`-based methods in SQL) to compare a cleartext password to a pre-computed SCRAM hash. This ensures that the existing password mechanisms that are cleartext-based continue to work even after the stored credentials start using the SCRAM encoding.

   Split into separate PRs: #74844 and #74845

4. extending the code created at step 1 to actually use the stored SCRAM credentials for client authentication. This achieves the main goal.

   Split into separate PRs: #74846 and #74847

5. making the hash method used to encode cleartext passwords passed to ALTER/CREATE USER/ROLE WITH PASSWORD configurable, using a new cluster setting `server.user_login.password_encryption`, and exposing its value via the pg-compatible session variable `password_encryption`.
   This is a convenience feature - properly secured deployments should not need this, as they should use pre-hashing client-side instead (see note at point 2 above).

   Split into separate PR: #74848

6. making crdb auto-select SCRAM authn if the stored password uses SCRAM. This is one step to ensuring that previous-version clusters are automatically opted into SCRAM.

   Split into separate PR: #74849

7. Auto-upgrade the stored credentials from bcrypt to SCRAM, when enabled and possible.

   Split into separate PR: #74850

The reviewer is invited to consider each PR in turn, read its commit message(s) to understand the goal of that PR, then review the PR to ascertain that the implementation (and relevant tests) match the goals announced in the commit message.

### CODE REVIEW

**Comment by knz** [comment]
todo:
- load passwords from system.users in different formats
- when auth method is 'scram', only allow scram
- when auth method is 'password' or 'cert-password', allow both
  - implement scram client loopback if encoding is scram for plaintext password
- check other paths that use passwords (UI auth?) . Implement scram client loopback for plaintext password
- new auth method 'cert-scram-sha-256'

optional:
- option to auto-rewrite passwords to scram upon successful login (ben's suggestion)

**Comment by knz** [comment]
@bdarnell all the pieces are in place to implement [your magic migration idea](https://github.com/cockroachdb/cockroach/issues/42519#issuecomment-721824728): 

> The best migration we could do would be to convert passwords to the SCRAM format the next time they log in. 

The way I'd see it, we would make this auto-migration enabled by default, but opt-out with a cluster setting. The code would also be gated behind a cluster version, so that it only runs after all nodes know how to use SCRAM stored hashes. Can you confirm my understanding is right?

**Comment by knz** [comment]
TODO (self): add a new value `auto` to the pw_encryption setting, to automatically upgrade to scram-sha-256 after the cluster version has been bumped up.

**Comment by bdarnell** [comment]
> The way I'd see it, we would make this auto-migration enabled by default, but opt-out with a cluster setting. The code would also be gated behind a cluster version, so that it only runs after all nodes know how to use SCRAM stored hashes. Can you confirm my understanding is right?

Correct. I'm not sure I'd even bother with an opt-out, but it does need the cluster version gate.(or the opt-out could be based on the `password_encryption` setting: on a cleartext login, upgrade the user's stored password if the stored format doesn't match the current `password_encryption` setting).

Do we need the `password_encryption` setting at all? Why would someone choose to use bcrypt instead of scram for storage? (There are driver compatibility reasons why one might continue to use cleartext logins, but storage shouldn't matter). There are some cases in which compliance might force a particular password encryption method, but the standards like FIPS generally dislike bcrypt (and prefer PBKDF2), so I'm not sure there's any real reason to give folks this knob.

> rotate or re-issue passwords for SQL clients by ensuring they
are written in CockroachDB using the SCRAM hash format.

So the admin must rotate 100% of passwords (or lock out non-compliant users) before they can enable scram authentication for anybody. That's unfortunate, and requires that we have a setting to prohibit storing new bcrypt-hashed passwords (including pre-hashed) to avoid races. It would be better to look at the user's stored password so we could fall back to plain password auth if the stored password doesn't support scram. I realize this conflicts with the performance improvement you just put in, but I think I'd rather have support for incremental movement to the new auth protocol than removing a little latency from the new connection process.

**Comment by knz** [comment]
> There are driver compatibility reasons why one might continue to use cleartext logins, but storage shouldn't matter.

Yes, correct.

> Why would someone choose to use bcrypt instead of scram for storage?

To control the latency of the hash validation (and thus the connection latency); I'm thinking about this PR specifically: https://github.com/cockroachlabs/managed-service/pull/7408

> I'm not sure there's any real reason to give folks this knob.

Yes that's also why I'm not pushing to have the session var be writable at all.

> So the admin must rotate 100% of passwords (or lock out non-compliant users) before they can enable scram authentication for anybody. [...] It would be better to look at the user's stored password so we could fall back to plain password auth if the stored password doesn't support scram.

I am aware of the opportunity to do this encoding-dependent protocol detection. 

But consider this: pg itself does do auto-selection of protocol between scram and md5; but not between scram and cleartext.
I went to investigate pg's sources to understand why. It turns out that there is another concern you've not considered yet: the guarantee offered by the scram HBA config, that the server won't ever see the cleartext password. That turns out to be a big deal, something operators want, and is the reason why pg does not implement cleartext  password when the HBA config says "scram".

(Interestingly: pg _does_ support md5 authn, for backward compatibility, if the HBA config says "scram", and the other way around: it does scram if the HBA config says "md5". It's all about promising that once the HBA config is set, there's no cleartext on the wire anymore)

> That's unfortunate, and requires that we have a setting to prohibit storing new bcrypt-hashed passwords (including pre-hashed) to avoid races.

I don't see how that follows? Can you explain more?

**Comment by knz** [comment]
@bdarnell @aaron-crl are suggesting to extend this work to make the scram iteration count configurable. Will add a commit to do this.

**Comment by knz** [comment]
@ben and I discussed how to finalize the work here. There are two separate sub-projects:

1. this PR: we'll extend the PR with a mechanism that automatically evolves existing clusters into using scram, using auto-promotion of the authn protocol. I'll add a commit to achieve that and massage the release notes accordingly.

   In this PR, the scram iteration count will remain fixed (constant), like the bcrypt one.

2. another issue (then another PR), yet to be filed, to deal with incrementing the iteration count over time.

   Here we want to reconcile two goals:
   - we want to increase the iteration count over time, to increase the cpu cost in proportion to hardware performance

      (For this purpose, we've noticed it's possible to do this for an already-stored hash using an automatic DB migration, by simply further hashing the existing hash.)

   - however, we also want to block increasing the iteration count automatically, for those password hashes generated automatically in the CC control plane with a lower iter count but a higher base entropy (https://github.com/cockroachlabs/managed-service/pull/7408)
 
   How to reconcile the two objectives? We're thinking about creating a new password storage prefix besides `crdb-bcrypt$` / `scram-sha-256$`, for example `scram-sha-256-fixed$`, that tells the code "please keep this hash's iter count constant". The CC control plane would use that.

As to next steps:
- I'll extend the PR in the direction discussed above
- I'll file the followup issue about increasing hashing costs
- i'll kickstart a discussion with Jeff S and Kyle P to determine the parameters

**Review by rafiss — DISMISSED** [review]
reviewed r11-r20

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-:-Msg63UjEZXKldRxngui:b-gbdk4v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @ajwerner, @bdarnell, and @knz)

___
*[pkg/security/password.go, line 143 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MsfybmiA-LwSgLlZZxI:-MsfybmiA-LwSgLlZZxJ:b-wysf8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b51de7f3af006eb3d4564d915939e0794628323d/pkg/security/password.go#L143)):*
> ```Go
> ) (
> 	isPreHashed, supportedScheme bool,
> 	issueLink int,
> ```

nit: should be named `issueNum`
___
*[pkg/security/password.go, line 74 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg0YHY4OSBI-6504To:-Msg0YHY4OSBI-6504Tp:b-bs952g) ([raw file](https://github.com/cockroachdb/cockroach/blob/48708cdaad5fe258da133b3d45a18b914a5a4c2c/pkg/security/password.go#L74)):*
> ```Go
> 
> // PasswordHash represents the type of a password hash loaded from a credential store.
> type PasswordHash interface {
> ```

nit: add no-op declarations for all the implementing types
___
*[pkg/security/password.go, line 411 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg2wk4DmFDRKCpj_Yo:-Msg2wk4DmFDRKCpj_Yp:b-lo9osn) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b7770d84d536d326b69749b095809e6e76b210/pkg/security/password.go#L411)):*
> ```Go
> var envMaxHashComputeConcurrency = envutil.EnvOrDefaultInt("COCKROACH_MAX_PW_HASH_COMPUTE_CONCURRENCY", 0)
> 
> // getExpensiveHashComputeSem retrieves the bcrypt semaphore.
> ```

nit: reword "bcrypt semaphore"
___
*[pkg/security/password.go, line 419 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg30X69GY0BeTY7p33:-Msg30X69GY0BeTY7p34:b-o7lai5) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b7770d84d536d326b69749b095809e6e76b210/pkg/security/password.go#L419)):*
> ```Go
> 			n = envMaxHashComputeConcurrency
> 		} else {
> 			// We divide by 8 so that the max CPU usage of bcrypt checks
> ```

nit: reword "bcrypt" here and 2 occurrences right below this
___
*[pkg/sql/pgwire/testdata/auth/scram, line 7 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg5kkk7Jx9Epz4K4Wf:-Msg5kkk7Jx9Epz4K4Wg:b-gifuh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/76bd2247753b790fa2b525a983684a8b00f50939/pkg/sql/pgwire/testdata/auth/scram#L7)):*
> ```
> CREATE USER foo WITH PASSWORD 'abc';
> SET CLUSTER SETTING server.user_login.password_encryption = 'scram-sha-256';
> CREATE USER abc WITH PASSWORD 'abc'
> ```

nit: maybe amend the usernames here to indicate that one is using bcrypt, and one is using scram

also, can we keep a test for creating a user with a pre-hashed scram password? (i'm looking at the r19->r20 diff right now; maybe this test already exists somewhere else?)

**Comment by rafiss** [comment]
perhaps we can do the github.com/xdg-go/scram dependency upgrade as a separate PR, to reduce the hassle of iterating on this PR.

**Comment by knz** [comment]
> perhaps we can do the github.com/xdg-go/scram dependency upgrade as a separate PR, to reduce the hassle of iterating on this PR.

Good idea: #74510

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @ajwerner, @bdarnell, and @rafiss)

___
*[pkg/security/password.go, line 143 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MsfybmiA-LwSgLlZZxI:-Msj7qzL7TpXoM_R7Gcq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b51de7f3af006eb3d4564d915939e0794628323d/pkg/security/password.go#L143)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should be named `issueNum`
</blockquote></details>

Done.
___
*[pkg/security/password.go, line 74 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg0YHY4OSBI-6504To:-Msj9HVsB5XLgoRFIf6C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48708cdaad5fe258da133b3d45a18b914a5a4c2c/pkg/security/password.go#L74)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: add no-op declarations for all the implementing types
</blockquote></details>

Done.
___
*[pkg/security/password.go, line 411 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg2wk4DmFDRKCpj_Yo:-Msj9X5T8JNtPEKhkGg8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b7770d84d536d326b69749b095809e6e76b210/pkg/security/password.go#L411)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: reword "bcrypt semaphore"
</blockquote></details>

Done.
___
*[pkg/security/password.go, line 419 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg30X69GY0BeTY7p33:-Msj9Xxj-Lub2qcB0zm3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b7770d84d536d326b69749b095809e6e76b210/pkg/security/password.go#L419)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: reword "bcrypt" here and 2 occurrences right below this
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/testdata/auth/scram, line 7 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-Msg5kkk7Jx9Epz4K4Wf:-MsjALkYCwoTCFATFAoY:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/76bd2247753b790fa2b525a983684a8b00f50939/pkg/sql/pgwire/testdata/auth/scram#L7)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: maybe amend the usernames here to indicate that one is using bcrypt, and one is using scram

also, can we keep a test for creating a user with a pre-hashed scram password? (i'm looking at the r19->r20 diff right now; maybe this test already exists somewhere else?)
</blockquote></details>

Good idea. Done.

**Comment by knz** [comment]
Added one of the two improvements agreed on by @bdarnell previously:

When using the HBA authentication
method `cert-password` (the default) for SQL client connections, and
the SQL client does not present a TLS client certificate to the
server, CockroachDB now automatically upgrades the password handshake
protocol to use SCRAM-SHA-256 if the user's stored password uses the
SCRAM encoding.

The previous behavior of requesting a cleartext password is still used
if the stored password is encoded using the CRDB-BCRYPT format.

An operator can force to _always_ request SCRAM-SHA-256 when a TLS
client cert is not provided (so as to guarantee the various
security benefits of SCRAM) using the authentication methods
`cert-scram-sha-256` (either TLS client cert _or_ SCRAM-SHA-256); and
`scram-sha-256` (only SCRAM-SHA-256).

(As previously, mandatory cleartext password authentication
can be requested, e.g. for debugging purposes, by using the HBA
method `password`.)

----

I need one more iteration to auto-convert the stored password then this PR will be good for review.

**Comment by knz** [comment]
I'm being informed by failing unit tests that client drivers expect the SCRAM handshake to complete without error once it's started, even if the password is invalid (that's what a pg server does). I'll tweak the code accordingly.

Separately, the sqlproxy unit tests report that the pgproto3 encoding for SASLInitialResponse do not populate all the messages properly. Will need to tweak the code server-side to tolerate incompletenesses.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-xmpp/info/issues/1
- https://github.com/cockroachdb/cockroach/issues/42519
- https://github.com/cockroachdb/cockroach/issues/55788
- https://github.com/cockroachdb/cockroach/pull/60150
- https://github.com/cockroachdb/cockroach/issues/74300
- https://github.com/cockroachdb/cockroach/pull/74301

**Comment by knz** [comment]
@rafiss can I request your help? The very last commit here, upon request from @bdarnell , tries to update the password hash after a succeeded authentication. For this I added a new function in `sql/user.go` (at the very end), which execs the appropriate  UPDATE statement.

However, it also needs to update the auth cache. Which method/function should I use for this?

**Comment by knz** [comment]
@rafiss maybe instead of executing UPDATE on system.users, I could run `ALTER USER WITH PASSWORD` instead. Do you think that will work via the internal executor? Thanks

**Review by jeffswenson — COMMENTED** [review]
> Reviewed 4 of 11 files at r12, 3 of 29 files at r21, 1 of 4 files at r22, 1 of 24 files at r33, 2 of 4 files at r34, 2 of 10 files at r36, 3 of 6 files at r38, 7 of 11 files at r40, 1 of 9 files at r44, 4 of 8 files at r47, 11 of 12 files at r48.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @ajwerner, @bdarnell, @knz, and @rafiss)

___
*[pkg/ccl/sqlproxyccl/authentication.go, line 52 at r46](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKIrbb7NrSJs0dh7DD:-MtKIrbb7NrSJs0dh7DE:b-57oalr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1129ffca40d35eb29c405aee6b6a5baf6712c13d/pkg/ccl/sqlproxyccl/authentication.go#L52)):*
> ```Go
> 			*pgproto3.AuthenticationCleartextPassword,
> 			*pgproto3.AuthenticationMD5Password,
> 			*pgproto3.AuthenticationSASLContinue,
> ```

It is unfortunate that SCRAM uses more round trips than clear text authorization. For collocated clients this should only add a few ms, but it will be significant for clients that are far from the sql node.
___
*[pkg/security/password.go, line 241 at r46](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKMy7H4rPIB0mQgajE:-MtKMy7IEZ7xJ3LgJ9Xr:bm4pt2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1129ffca40d35eb29c405aee6b6a5baf6712c13d/pkg/security/password.go#L241)):*
> ```Go
> 		return bcryptHash(storedHash)
> 	}
> 	if parts := scramHashRe.FindSubmatch(storedHash); parts != nil {
> ```

nit: this would be easier to use read if there were symmetry between the hash implementations. I'm thinking something like:

```
if isBcryptHash(storedHash) {
   return bcryptHash(storedHash)
} 
if isScramHash(storedHash) {
  return scramHash(storedHash)
}
return invalidHash(storedHash)
 ```

scramHash could return invalidHash if there is a parse error or isScramHash could return false if the format is invalid.
___
*[pkg/security/password.go, line 304 at r48](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKbVuDCGqFxnrNV8ly:-MtKbVuDCGqFxnrNV8lz:b-bfc06k) ([raw file](https://github.com/cockroachdb/cockroach/blob/670016dd1eb78f7d6736716ef8de9b3450a474c7/pkg/security/password.go#L304)):*
> ```Go
> 		return false, nil
> 
> 	case bcryptHash:
> ```

nit: instead of implementing this as a type switch, this could be a function on PasswordHash.

```
func Compare(ctx context.Context, password PasswordHAsh) (bool, error)

ok, err := hashedPassword.Compare(ctx, password)
```
___
*[pkg/sql/user.go, line 691 at r48](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKYtHr-qPMVc0-yER6:-MtKYtHr-qPMVc0-yER7:bue0tae) ([raw file](https://github.com/cockroachdb/cockroach/blob/670016dd1eb78f7d6736716ef8de9b3450a474c7/pkg/sql/user.go#L691)):*
> ```Go
> 			ctx, ie, execCfg.DB,
> 			func(ctx context.Context, txn *kv.Txn, _ *descs.CollectionFactory) error {
> 				_, err = params.extendedEvalCtx.ExecCfg.InternalExecutor.Exec(
> ```

I think there is a race condition here. If auto upgrade races with a user run ALTER ROLE WITH PASSWORD, the ALTER ROLE may be overwritten. We can fix that by extending the WHERE clause to verify the pre-update hash is what we found during authentication.

**Comment by knz** [comment]
Upon suggestion by @lunevalex I'm going to split this PR into its individual sub-components to ease review. Let's hold on reviewing further here.

**Comment by knz** [comment]
Here's the list of PRs to review:

- [ ] security,*: extend CheckPasswordHashValidity to return a GH issue number (scram 1/10) #74841 
- [ ] pgwire,sqlproxyccl: base support for a SCRAM authentication flow (scram 2/10) #74842 
- [ ] sql,security: support storing SCRAM hashes in ALTER/CREATE USER/ROLE (scram 3/10) #74843 
- [ ] sql,security: create a password hash abstraction (scram 4/10) #74844 
- [ ] security: enable plaintext authentication with SCRAM credentials (scram 5/10) #74845 
- [ ] sql,pgwire,server: factor the password expiry code (scram 6/10) #74846 
- [ ] pgwire: support the SCRAM authentication flow (scram 7/10) #74847 
- [ ] sql: make the stored hash method configurable (scram 8/10) #74848 
- [ ] pgwire: auto-upgrade password authentication with SCRAM hashes (scram 9/10) #74849 
- [ ] pgwire,security: auto-upgrade bcrypt hashes to SCRAM-SHA-256 (scram 10/10) #74850

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @ajwerner, @bdarnell, @JeffSwenson, and @rafiss)

___
*[pkg/ccl/sqlproxyccl/authentication.go, line 52 at r46](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKIrbb7NrSJs0dh7DD:-MtONYrTEuyKeBO6k-OM:b-btgcjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1129ffca40d35eb29c405aee6b6a5baf6712c13d/pkg/ccl/sqlproxyccl/authentication.go#L52)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

It is unfortunate that SCRAM uses more round trips than clear text authorization. For collocated clients this should only add a few ms, but it will be significant for clients that are far from the sql node.
</blockquote></details>

Discussed here: https://github.com/cockroachdb/cockroach/pull/74842#issuecomment-1013004700
___
*[pkg/security/password.go, line 241 at r46](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKMy7H4rPIB0mQgajE:-MtP0rh14o5gZ2VKP9TF:b-6djg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1129ffca40d35eb29c405aee6b6a5baf6712c13d/pkg/security/password.go#L241)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

nit: this would be easier to use read if there were symmetry between the hash implementations. I'm thinking something like:

```
if isBcryptHash(storedHash) {
   return bcryptHash(storedHash)
} 
if isScramHash(storedHash) {
  return scramHash(storedHash)
}
return invalidHash(storedHash)
 ```

scramHash could return invalidHash if there is a parse error or isScramHash could return false if the format is invalid.
</blockquote></details>

Done, #74844 and later PRs.
___
*[pkg/security/password.go, line 304 at r48](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKbVuDCGqFxnrNV8ly:-MtONhG67qaEJ8Npvs__:buqbl4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/670016dd1eb78f7d6736716ef8de9b3450a474c7/pkg/security/password.go#L304)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

nit: instead of implementing this as a type switch, this could be a function on PasswordHash.

```
func Compare(ctx context.Context, password PasswordHAsh) (bool, error)

ok, err := hashedPassword.Compare(ctx, password)
```

</blockquote></details>

Sure, why not. Done #74844 / #74845
___
*[pkg/sql/user.go, line 691 at r48](https://reviewable.io/reviews/cockroachdb/cockroach/74301#-MtKYtHr-qPMVc0-yER6:-MtONsyX2XgmrWlhvNtu:b-gwfase) ([raw file](https://github.com/cockroachdb/cockroach/blob/670016dd1eb78f7d6736716ef8de9b3450a474c7/pkg/sql/user.go#L691)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

I think there is a race condition here. If auto upgrade races with a user run ALTER ROLE WITH PASSWORD, the ALTER ROLE may be overwritten. We can fix that by extending the WHERE clause to verify the pre-update hash is what we found during authentication.
</blockquote></details>

Very well spotted! Handled here: #74850.

**Comment by knz** [comment]
All the sub-PRs have been approved, will proceed to merge this once CI is happy.

**Comment by knz** [comment]
bors r=rafiss,JeffSwenson,bdarnell,aaron-crl,kpatron-cockroachlabs

**Comment by knz** [comment]
merge skew

bors r-

**Comment by knz** [comment]
bors r=rafiss,JeffSwenson,bdarnell,aaron-crl,kpatron-cockroachlabs

**Comment by knz** [comment]
unrelated flake

bors r=rafiss,JeffSwenson,bdarnell,aaron-crl,kpatron-cockroachlabs

**Comment by Neustradamus** [comment]
Thanks @knz, and all others!

Linked to:
- https://github.com/scram-sasl/info/issues/1

**Pull request merged**
