### PR TITLE
ccl：import MYSQLOUTFILE will produce duplicate data

### PR DESCRIPTION
**Pull request by pananc**
relate to #26153

### CODE REVIEW

**Comment by pananc** [comment]
I find some test cases failed, but i do not find below test cases in my cockroach code, what should i do to deal with below test cases?

TestSQLAlchemy 	
TestSQLAlchemy/FirstRun

**Comment by bdarnell** [comment]
Those tests live in https://github.com/cockroachdb/examples-orms and are known to be a little flaky, so I don't think those failures are related to this change.

**Comment by mjibson** [comment]
Thanks for finding this bug and indeed a start to a solution. Sadly we have other refactors in line for this code that will fix it in a different way, so we're going to close this PR instead of do the normal review process.

**Comment by pananc** [comment]
ok  @mjibson

**Pull request closed without merging**
