### PR TITLE
ui: prevent /_status/nodes calls for secondary tenants

### PR DESCRIPTION
**Pull request by kyle-a-wong**
/_status/nodes is not implemented for secondary tenants, resulting in 501
responses in cloud for serverless tenants. To fix, this api is now gated by
a tenant check and will no longer be called by serverless / secondary tenants.

Fixes: CC-26900
Epic: None
Release note: None

### CODE REVIEW

**Review by xinhaoz — COMMENTED** [review]
Code changes look good to me - just minor comment on the commit msg and issue linking.

> Reviewed 6 of 7 files at r1, 5 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124233#-:-NxxPjyQ03aF3lvJ3TA8:b-rqwp5h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @kyle-a-wong)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124233#-NxxOlUF4lGJINIYlS_8):*
Hmm I see there's no equivalent GitHub ticket for this. Since this work is in the cockroachdb repo there typically should be a github issue that is synced to a jira issue, but this seems like a gray area because this change should only affect CC. You could just put the link you have in your PR message here under the `Fixes: ` tag, we'll see if the CI complains. Then you can clean up the PR description with the edit here too.

**Review by kyle-a-wong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124233)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124233#-NxxOlUF4lGJINIYlS_8):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Hmm I see there's no equivalent GitHub ticket for this. Since this work is in the cockroachdb repo there typically should be a github issue that is synced to a jira issue, but this seems like a gray area because this change should only affect CC. You could just put the link you have in your PR message here under the `Fixes: ` tag, we'll see if the CI complains. Then you can clean up the PR description with the edit here too.
</blockquote></details>

Done.

**Review by xinhaoz — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124233#-:-NxxzDuLCRm3HN461RdL:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by kyle-a-wong** [comment]
bors retry

**Pull request merged**
