### PR TITLE
storeliveness: add Transport

### LINKED ISSUE #125062: storeliveness: add Transport
Set up a transport layer for `StoreLiveness` similar to Raft transport. The transport is asynchronous with respect to the caller, and internally multiplexes outbound messages. Internally, each message is queued on a per-destination queue before being asynchronously delivered.

Jira issue: CRDB-39248

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by miraradeva**
This commit introduces the Store Liveness Transport component, which is responsible for sending and receiving Store Liveness messages. Each node maintains a single instance of Transport that handles sending and receiving messages on behalf of all stores on the node.

The transport is asynchronous with respect to the caller, and internally multiplexes outbound messages by queuing them on a per-destination queue before delivering them asynchronously.

The Store Liveness transport is similar in many respects to Raft transport.

Fixes: #125062

Release note: None

### CODE REVIEW

**Comment by miraradeva** [comment]
I'm looking for feedback on testing. In addition to the tests I added, I was also thinking about testing the following:
1. A single store hanging while handling messages (e.g. due to sync write and a stalled disk) does not affect the ability of other stores on the same node to receive messages. This will not be an issue for our implementation of the `MessageHandler` (which only enqueues the messages into a receive queue), but if we were to test the Transport independently, we could add a test that demonstrates the effect of a blocking `MessageHandler`.
2. Raft transport has a test that verifies that messages are delivered in order between a given sender and a given receiver. We could do the same but I didn't because the Store Liveness protocol doesn't depend on this property.
3. Various failure modes are currently not tested very well. E.g. when we return errors in the send/receive loops, the loops terminate, but we don't ensure they get started properly again. Being able to inject some of these errors might require restructuring the code.

**Review by nvb — COMMENTED** [review]
> A single store hanging while handling messages (e.g. due to sync write and a stalled disk) does not affect the ability of other stores on the same node to receive messages. This will not be an issue for our implementation of the `MessageHandler` (which only enqueues the messages into a receive queue), but if we were to test the Transport independently, we could add a test that demonstrates the effect of a blocking `MessageHandler`.

We say in the `MessageHandler` interface that it shouldn't block, so testing that a broken implementation of `MessageHandler` breaks `RaftTransport` doesn't feel all that worthwhile. If anything, this should be a test of `MessageHandler`. Up to you though, as the additional test wouldn't hurt.

> Raft transport has a test that verifies that messages are delivered in order between a given sender and a given receiver. We could do the same but I didn't because the Store Liveness protocol doesn't depend on this property.

This might be worthwhile, even though the algorithm doesn't rely on ordering. Do we have such a guarantee across stream reconnects?

> Various failure modes are currently not tested very well. E.g. when we return errors in the send/receive loops, the loops terminate, but we don't ensure they get started properly again. Being able to inject some of these errors might require restructuring the code.

The case that caught my eye while reviewing as being worthy of a test is the `StoreNotFound` path. That's the one case where we return an error from the server to the client. Will we do anything with that error? Will we do anything to prevent starvation of other messages to the same node?

We may want to process the rest of the batch on the server before returning the error, as a safeguard against starvation.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-:-O1N3OM83MZ6P3to6Nht:b-v7b0d1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1MqJan3aGFN3-fqUlq:-O1MqJan3aGFN3-fqUlr:b-xd4588) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L72)):*
> ```Go
> //
> // The transport is asynchronous with respect to the caller, and internally
> // multiplexes outbound messages by queuing them on a per-destination queue
> ```

"per-destination"

We should clarify whether a destination is a node or a store on a node.
___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1MqaUjDzDRvzwV9Ufx:-O1MqaUjDzDRvzwV9Ufy:b-tykmj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L76)):*
> ```Go
> type Transport struct {
> 	log.AmbientContext
> 	clock   *hlc.Clock
> ```

nit: for consistency with the Raft transport, let's move `clock` below `stopper` in the field order, constructor signature, and struct construction.
___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1N32aL6Dyiyblnkq_-:-O1N32aL6Dyiyblnkq_0:b766j12) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L82)):*
> ```Go
> 	// queues maintains a map[roachpb.NodeID]*sendQueue and stores the outgoing
> 	// message queue for each node, keyed by the destination node ID.
> 	queues syncutil.IntMap
> ```

I'm going to push on https://github.com/cockroachdb/cockroach/pull/120604 today to allow you to clean this up.
___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1N0UFYAf1yFyEEo7iS:-O1N0UFYAf1yFyEEo7iT:b1jom0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L157)):*
> ```Go
> 
> // handleMessage proxies a request to the corresponding store's MessageHandler.
> func (t *Transport) handleMessage(ctx context.Context, msg slpb.Message) *kvpb.Error {
> ```

Does this need to return a `kvpb.Error`, which is just converted to an `error` one level above with the call to `GoError`? Can we just use `error`s throughout.
___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1N08-y955XW3i8jPXv:-O1N08-y955XW3i8jPXw:b-9p9rng) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L165)):*
> ```Go
> 	}
> 
> 	h.HandleMessage(ctx, &msg)
> ```

Let's have `handleMessage` take a `*slpb.Message`, so that we don't need to heap allocate here on each message.

In `Stream`, we'll switch the loop over a batch to:
```go
for i := range batch.Messages {
	if err := t.handleMessage(ctx, &batch.Messages[i]); err != nil {
		return err.GoError()
	}
}
```
___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1N25rL-alt0oCMdzVr:-O1N25rL-alt0oCMdzVs:bxvlxlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L207)):*
> ```Go
> 		if logSendQueueFullEvery.ShouldLog() {
> 			log.Warningf(t.AnnotateCtx(context.Background()),
> 				"Store Liveness send queue to n%d is full", toNodeID)
> ```

nit: `s/Store Liveness/store liveness/`
___
*[`pkg/kv/kvserver/storeliveness/transport_test.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1N57PYDSFL-yZ66YKV:-O1N57PYDSFL-yZ66YKW:b-9g118l) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport_test.go#L160)):*
> ```Go
> }
> 
> // TestTransportSendAndReceive tests the basic send-and-receive functionality of
> ```

I haven't carefully reviewed these tests yet.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126837)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1N32aL6Dyiyblnkq_-:-O1RvltH0TZKMyUehAVs:b-1fpekr) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm going to push on https://github.com/cockroachdb/cockroach/pull/120604 today to allow you to clean this up.
</blockquote></details>

This is now merged. We'll want to make similar changes to what that PR did to `pkg/kv/kvserver/raft_transport.go`: https://github.com/cockroachdb/cockroach/pull/120604/files#diff-6e3ef780033b487397142b63fc9ad776ec18d74eb69fc4453900804a4125c404

**Comment by miraradeva** [comment]
> > A single store hanging while handling messages (e.g. due to sync write and a stalled disk) does not affect the ability of other stores on the same node to receive messages. This will not be an issue for our implementation of the `MessageHandler` (which only enqueues the messages into a receive queue), but if we were to test the Transport independently, we could add a test that demonstrates the effect of a blocking `MessageHandler`.
> 
> We say in the `MessageHandler` interface that it shouldn't block, so testing that a broken implementation of `MessageHandler` breaks `RaftTransport` doesn't feel all that worthwhile. If anything, this should be a test of `MessageHandler`. Up to you though, as the additional test wouldn't hurt.

Agree, I'll add a test for that in `SupportManager`, which will implement `MessageHandler`. 

> 
> > Raft transport has a test that verifies that messages are delivered in order between a given sender and a given receiver. We could do the same but I didn't because the Store Liveness protocol doesn't depend on this property.
> 
> This might be worthwhile, even though the algorithm doesn't rely on ordering. Do we have such a guarantee across stream reconnects?

According to the [GRPC docs](https://grpc.io/docs/what-is-grpc/core-concepts/), the messages are guaranteed to be in order only within a single RPC call. To me this means that we don't get the ordering guarantee if we re-open a client stream. That should be the same for Raft transport, right? And `TestInOrderDelivery` in `raft_transport_test.go` verifies in-order delivery only within a single RPC call. I think I'd rather not add the test since (a) the property doesn't hold in all cases, and (b) the algorithm doesn't depend on it. I'll add a note about it somewhere though.

> 
> > Various failure modes are currently not tested very well. E.g. when we return errors in the send/receive loops, the loops terminate, but we don't ensure they get started properly again. Being able to inject some of these errors might require restructuring the code.
> 
> The case that caught my eye while reviewing as being worthy of a test is the `StoreNotFound` path. That's the one case where we return an error from the server to the client. Will we do anything with that error? Will we do anything to prevent starvation of other messages to the same node?
> 
> We may want to process the rest of the batch on the server before returning the error, as a safeguard against starvation.

I added a test for this. With the existing code, sending a message to a store that doesn't have a registered handler prevents other stores on the node from receiving subsequent messages. This is because we return an error and exit from `func (t *Transport) Stream(stream slpb.StoreLiveness_StreamServer) error`, and close the stream. This affects not just messages in the current batch, but messages in subsequent batches too. 

Since we don't have a particular plan to handle `StoreNotFound` error anywhere up the stack, I changed `handleMessage` to not return an error at all. If there is no registered handler, it just moves on.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126837)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1N32aL6Dyiyblnkq_-:-O1RqMhD2408u1AT_WwR:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/952d9be1650bb092955436b3efacf5f75534c7c1/pkg/kv/kvserver/storeliveness/transport.go#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm going to push on https://github.com/cockroachdb/cockroach/pull/120604 today to allow you to clean this up.
</blockquote></details>

Thanks!

**Review by nvb — APPROVED** [review]
:lgtm: 

> Since we don't have a particular plan to handle `StoreNotFound` error anywhere up the stack, I changed `handleMessage` to not return an error at all. If there is no registered handler, it just moves on.

This SGTM. We would expect that the sender will eventually stop requesting support from the non-existent store.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-:-O1SqCrJ2eav6PXq9FNl:b-5af4o0)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1Sq-BF2__8D6WKr7en:-O1Sq-BF2__8D6WKr7eo:b-keuw56) ([raw file](https://github.com/cockroachdb/cockroach/blob/52ce4f9dff655521bcf5b39a28fd71a8d4f27e4f/pkg/kv/kvserver/storeliveness/transport.go#L276)):*
> ```Go
> 			return nil
> 
> 		case <-idleTimer.C:
> ```

Would it be worthwhile to add a test for the `idleTimer`?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126837)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126837#-O1Sq-BF2__8D6WKr7en:-O1qdigRAAhQS_y84Kiw:b-fenqao) ([raw file](https://github.com/cockroachdb/cockroach/blob/52ce4f9dff655521bcf5b39a28fd71a8d4f27e4f/pkg/kv/kvserver/storeliveness/transport.go#L276)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Would it be worthwhile to add a test for the `idleTimer`?
</blockquote></details>

Added a TODO and will do as part of #125067 after adding some metrics.

**Comment by miraradeva** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
