### PR TITLE
opt: fix normalization of comparisons with constants

### LINKED ISSUE #90053: roachtest: unoptimized-query-oracle/disable-rules=all failed
roachtest.unoptimized-query-oracle/disable-rules=all [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6975915?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6975915?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all) on release-22.2 @ [5bbbb4fefe2cca87aa8dd34c007702bb2faa20ef](https://github.com/cockroachdb/cockroach/commits/5bbbb4fefe2cca87aa8dd34c007702bb2faa20ef):

```
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/run_1
	query_comparison_util.go:237,query_comparison_util.go:66,unoptimized_query_oracle.go:54,test_runner.go:930: . 21551 statements run: expected unoptimized and optimized results to be equal
		(1) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*queryComparisonHelper).makeError
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/query_comparison_util.go:345
		  | [...repeated from below...]
		Wraps: (2) . 21551 statements run
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runUnoptimizedQueryOracleImpl
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go:168
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerUnoptimizedQueryOracle.func1.1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go:57
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runOneRoundQueryComparison
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/query_comparison_util.go:236
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runQueryComparison
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/query_comparison_util.go:66
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerUnoptimizedQueryOracle.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go:54
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:930
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1594
		Wraps: (4) expected unoptimized and optimized results to be equal
		  |   []string{
		  |   	"0,105,0.5054834485054016,1970-04-11 00:08:20 +0000 +0000,0000000"...,
		  |   	"0,105,0.5054834485054016,1970-04-11 00:08:20 +0000 +0000,1110101"...,
		  |   	"0,105,0.5054834485054016,1970-04-11 00:08:20 +0000 +0000,NULL,NU"...,
		  | - 	``0,105,0.5054834485054016,1970-04-11 00:08:20 +0000 +0000,NULL,NULL,0,"``,
		  |   }
		  | sql: SELECT
		  | 	0:::OID AS col_88556,
		  | 	tab_27011.tableoid AS col_88557,
		  | 	0.5054834485054016:::FLOAT8 AS col_88558,
		  | 	'1970-04-11 00:08:20':::TIMESTAMP AS col_88559,
		  | 	tab_27011.col2_14 AS col_88560,
		  | 	tab_27011.col2_9 AS col_88561,
		  | 	0:::OID AS col_88562,
		  | 	tab_27011.col2_15 AS col_88563
		  | FROM
		  | 	defaultdb.public.table2@[0] AS tab_27011
		  | WHERE
		  | 	(EXISTS (SELECT ARRAY[32297:::INT8,15358:::INT8] AS col_88555 FROM defaultdb.public.table2@[0] AS tab_27012) AND ('00:01:40.01+09:00:00':::TIMETZ < (tab_27011.col2_8::TIMETZ + '-83 years -1 mons -38 days -10:32:23.707137':::INTERVAL::INTERVAL)::TIMETZ))
		  | ORDER BY
		  | 	tab_27011.col2_10, tab_27011.col2_1, tab_27011.col2_0, tab_27011.col2_5 DESC
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #89572 roachtest: unoptimized-query-oracle/disable-rules=all failed [C-test-failure O-roachtest O-robot T-sql-queries branch-master]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20572

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: fix normalization of comparisons with constants

A prior commit in #88199 attempted to fix a bug in the
`NormalizeCmpPlusConst`, `NormalizeCmpMinusConst`, and
`NormalizeCmpConstMinus` rules by checking for overflow/underflow in the
addition/subtraction of constants in a comparison expression. This was
insufficient to completely fix the bug because the transformation is
invalid if the non-normalized expression would have overflowed. Consider
an expression:

    t::TIME + '-11 hrs'::INTERVAL > '01:00'::TIME

`NormalizeCmpPlusConst` would successively normalize it to this:

    t::TIME > '01:00'::TIME - '-11 hrs'::INTERVAL
    => t::TIME > '12:00'::TIME

This expression is not semantically equivalent to the original
expression. It yields different results when `t` is a value that would
underflow when eleven hours is subtracted from it. For example, consider
`t = '03:00'::TIME`:

    Original expression:
    t::TIME + '-11 hrs'::INTERVAL > '01:00'::TIME
    => '03:00'::TIME + '-11 hrs'::INTERVAL > '01:00'::TIME
    => '16:00'::TIME > '01:00'::TIME
    => true

    Normalized expression:
    t::TIME > '12:00'::TIME
    => '03:00'::TIME > '12:00'::TIME
    => false

These normalization rules are only valid with types where overflow or
underflow during addition and subtraction results in an error.

This commit restricts these normalization rules to only operate on
integers, floats, and decimals, which will error if there is underflow
or overflow.

Fixes #90053

Release note (bug fix): A bug has been fixed that caused incorrect
evaluation of comparison expressions involving time and interval types,
like `col::TIME + '10 hrs'::INTERVAL' > '01:00'::TIME`.

#### opt: replace FoldBinaryCheckOverflow with FoldBinary

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
I'm planning on backporting only the first commit.

**Review by rytaft — APPROVED** [review]
:lgtm: great find!

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90266#-:-NElc1o96uodNgxuBBtG:b-3952fu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @msirek)

___
*[`pkg/sql/opt/norm/comp_funcs.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90266#-NElcD739h1JlzXFzTdH:-NElbJbJAKk2A5Z2Yi8r:b-aapg1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8aa40b62f7b339cd9d6e460c8aed7ed6c9c8713/pkg/sql/opt/norm/comp_funcs.go#L74)):*
> ```Go
> 	// for this NULL check. The NULL check might not be necessary since we no
> 	// longer use this function on TIME and INTERVAL types, so maybe we can
> 	// reuse FoldBinary instead.
> ```

For the backport, why don't you at least rename this function to FindBinaryCheckNull, since there is no overflow checking.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90266)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @msirek, and @rytaft)

___
*[`pkg/sql/opt/norm/comp_funcs.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90266#-NElcD739h1JlzXFzTdH:-NEldbNd7c9PebwQ5onF:bves986) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8aa40b62f7b339cd9d6e460c8aed7ed6c9c8713/pkg/sql/opt/norm/comp_funcs.go#L74)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

For the backport, why don't you at least rename this function to FindBinaryCheckNull, since there is no overflow checking.
</blockquote></details>

Good catch! Fixed.

**Review by msirek — APPROVED** [review]
Nice fix!
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90266#-:-NEllimH8ivJxiDAOzkf:b8ig6vo)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rytaft)

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90266)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Pull request merged**
