### PR TITLE
opt: don't apply huge cost for full scans of virtual tables

### LINKED ISSUE #122708: sql: don't apply disallow_full_table_scans to virtual tables
Since we currently don't collect stats for virtual tables, (tracked in https://github.com/cockroachdb/cockroach/issues/27611), we unconditionally apply costing changes due to the `disallow_full_table_scans` setting for virtual table scans, even if `large_full_scan_rows` is larger than the row count. Until tracked in https://github.com/cockroachdb/cockroach/issues/27611 is fixed, we should prevent `disallow_full_table_scans` from applying to virtual tables, likely using a setting.

Jira issue: CRDB-38031

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes - what I believe is - an oversight where we applied the huge cost to the plans with full scans of virtual tables when `disallow_full_table_scans` variable is set. The intent behind this penalty is to make plans with full scans prohibitively expensive so that other plans (without full scans) would be preferred, and if there is no other plan, then the query would error out. Implementation of this approach was incomplete for virtual tables: namely, we'd apply the cost penalty, but then we would not actually error out the query. Additionally, given that we don't have stats on virtual tables, we would apply the cost penalty to all full scans of virtual tables.

As a result, we would either pick a plan without the full scan (that might actually be worse) or would allow the plan with the full scan to get executed still. We would also favor plans with fewer full scans of virtual tables (which might also be worse than had we not applied the cost penalty). This commit adjusts the code to not apply the cost penalty to full scans of virtual tables.

This change is gated based on the new session variable `optimizer_apply_full_scan_penalty_to_virtual_tables` which defaults to `false` on master. We can discuss on the backport PRs whether it should be default to `true` there to require users to opt in for this PR to have an effect.

Fixes: #122708.

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for fixing this!

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-:-NxMdKBIE4_sY2N7Yl6m:b-mws4q9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-NxMc9t_CZ3K50LPC9W8):*
[nit] Should we add a release note since the issue this is fixing has an O-support label?

**Comment by michae2** [comment]
I will look today.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-NxMc9t_CZ3K50LPC9W8):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Should we add a release note since the issue this is fixing has an O-support label?
</blockquote></details>

My thinking was that the default value for `disallow_full_table_scans` is `false`, so this could be considered a bug fix to a non-default configuration, in which I thought we generally don't include the release notes. (I did see that we did include some release notes in the past for this feature though.) For the single customer that ran into this we'll be communicating directly, so I don't think they care whether we include it or not.

I can add a release note if we think it's worth it.

**Review by DrewKimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-NxMc9t_CZ3K50LPC9W8):*
>I don't think they care whether we include it or not.

If that's the case, I'm fine with just leaving it out.

**Review by rytaft — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-:-NxOc52n1tJ4BvEUS2MT:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

**Review by michae2 — CHANGES_REQUESTED** [review]
foo

> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-:-NxPUOQ5EjuvF21vCMKS:b2ni2sh)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/opt/xform/coster.go` line 791 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-NxPfF_jDUUVbpVUy1II:-NxPfF_jDUUVbpVUy1IJ:b-habv7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb9662072449750fd5fbd2de48c3c9873e57187/pkg/sql/opt/xform/coster.go#L791)):*
>			// TODO(#123783): once we start rejecting plans with full scans of>
>			// virtual tables, we should apply the cost penalty here.

Do we want to reject plans with full scans of virtual tables? I thought according to https://github.com/cockroachdb/cockroach/issues/122708 we decided to not apply `disallow_full_table_scans` to virtual tables? And it seems like this PR also fixes that issue by removing hugeCost?

I find the purpose of `optimizer_apply_full_scan_penalty_to_virtual_tables` a little muddy: it brings back the old behavior, but the old behavior was not correct as you point out in https://github.com/cockroachdb/cockroach/issues/123783. Would it make more sense to add a `disallow_full_virtual_table_scans` setting which, when enabled has both the hugeCost and the ContainsLargeFullTableScan flag, fixing 123783, and when disabled has neither, fixing 122708?

**Review by michae2 — COMMENTED** [review]
sorry, ignore the foo :facepalm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-:-NxPioWk9jJGZktot4mP:b-7x9dlw)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/opt/xform/coster.go` line 791 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-NxPfF_jDUUVbpVUy1II:-NxQ5fvcDKaP7F87TCw9:bkpl92s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb9662072449750fd5fbd2de48c3c9873e57187/pkg/sql/opt/xform/coster.go#L791)):*
> Do we want to reject plans with full scans of virtual tables?

This is the question that I don't know the answer to. I find this problem quite confusing - I believe that originally "disallow full table scans" feature was designed with user tables in mind, so we probably didn't consider how it should behave for virtual tables. The goal is for DB infra team to force their app developers think better about schema / query design in order to not introduce expensive queries (to protect stability of the cluster), and we use "full scan" or "large scan" as a proxy for being expensive. However, for virtual tables our users have no control over the schema; true, in some cases they could rewrite the queries to avoid full scans of vtables, but I'd guess it's usually not possible - this is due to CRDB missing virtual indexes (in case it is possible to implement those). Do we want to error out such queries without having any workaround? I'm not sure.

This thinking is why I decided to file (rather than fix it right away) #123783 so that we could discuss in case we want to have a way to prohibit full scans of vtables. The current approach allows us to fix the issue for the customer with low risk and have a backportable solution. As a follow-up, I plan to remove this session variable altogether on master (so that this behavior is unconditional), and then it'll be up to us to fix #123783 (where a new session variable would be warranted) separately, and we'll have the session var available on older releases (where I think we should consider defaulting to enabling this patch, and the session var would provide us an escape hatch in case there is a regression).

WDYT?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/opt/xform/coster.go` line 791 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-NxPfF_jDUUVbpVUy1II:-NxQ9iqmAbUPN5mZ2ebb:b-de6y1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb9662072449750fd5fbd2de48c3c9873e57187/pkg/sql/opt/xform/coster.go#L791)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> Do we want to reject plans with full scans of virtual tables?

This is the question that I don't know the answer to. I find this problem quite confusing - I believe that originally "disallow full table scans" feature was designed with user tables in mind, so we probably didn't consider how it should behave for virtual tables. The goal is for DB infra team to force their app developers think better about schema / query design in order to not introduce expensive queries (to protect stability of the cluster), and we use "full scan" or "large scan" as a proxy for being expensive. However, for virtual tables our users have no control over the schema; true, in some cases they could rewrite the queries to avoid full scans of vtables, but I'd guess it's usually not possible - this is due to CRDB missing virtual indexes (in case it is possible to implement those). Do we want to error out such queries without having any workaround? I'm not sure.

This thinking is why I decided to file (rather than fix it right away) #123783 so that we could discuss in case we want to have a way to prohibit full scans of vtables. The current approach allows us to fix the issue for the customer with low risk and have a backportable solution. As a follow-up, I plan to remove this session variable altogether on master (so that this behavior is unconditional), and then it'll be up to us to fix #123783 (where a new session variable would be warranted) separately, and we'll have the session var available on older releases (where I think we should consider defaulting to enabling this patch, and the session var would provide us an escape hatch in case there is a regression).

WDYT?
</blockquote></details>

IIRC, the customer that ran into #122708 is the same that requested this feature originally. Perhaps we should reach out to them to see what they think with regards to prohibiting full scans of vtables?

**Review by michae2 — APPROVED** [review]
:lgtm: We talked a bit, and I'm ok with this version, too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123780#-:-NxTJXUo2CzZTHB0L2cF:b-8ilr24)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
