### PR TITLE
engine: create new OpLoggerBatch to log logical MVCC ops

### PR DESCRIPTION
**Pull request by nvb**
This change creates a new Batch implementation that logs logical
MVCC operations. This allows a Replica to selectively decide when
a request's logical MVCC operations should be attached to a raft
command. This is important for rangefeed because it operates off
of logical operations, not physical ones.

With this change, a Replica will never decide to turn on logical op
logging, so it doesn't change any behavior yet. A future change will
include logic to conditionally log and replica logical MVCC ops.
This turns out to be fairly involved, so I figured it would be preferable
to split this into its own PR. A description of the tentative plan for that
is included in `replica.go`. Suggestions are very welcome!

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28362)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc_logical_ops.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28362#-LJPDPfj5Wcztt1FWAVQ:-LJPDPfj5Wcztt1FWAVR:b-pdx4v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae5eacd1224f2d91c70554c3f4485f1067e850/pkg/storage/engine/mvcc_logical_ops.go#L61)):*
> ```Go
> 	// never be invalidated, an OpLoggerBatch will make a copy of all references
> 	// before adding it to the log. TestMVCCOpLogWriter fails without this.
> 	Unsafe bool
> ```

Maybe invert this, so that if it's left at the default we'll make a redundant copy but won't break anything.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28362)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/rocksdb.go, line 1053 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28362#-LJPXWht2emQNk7lJtNv:-LJPXWhuBl6glmJhxvH5:bi6566i) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae5eacd1224f2d91c70554c3f4485f1067e850/pkg/storage/engine/rocksdb.go#L1053)):*
> ```Go
> 
> func (r *rocksDBReadOnly) LogData(data []byte) error {
> 	panic("not implemented")
> ```

it seems awkward to add this to the `engine.Writer` interface if most of the impls don't support it. thoughts on instead plumbing it down to the handful of mvcc methods that need it?

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28362#-:-LJRkx8R85zHQ7fIpC79:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc_logical_ops.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28362#-LJPDPfj5Wcztt1FWAVQ:-LJRiuN23QodC8rZSU8I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae5eacd1224f2d91c70554c3f4485f1067e850/pkg/storage/engine/mvcc_logical_ops.go#L61)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe invert this, so that if it's left at the default we'll make a redundant copy but won't break anything. 
</blockquote></details>

Done.
___
*[pkg/storage/engine/rocksdb.go, line 1053 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28362#-LJPXWht2emQNk7lJtNv:-LJRiv-K4nNkI5pQUKD2:b3iay0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae5eacd1224f2d91c70554c3f4485f1067e850/pkg/storage/engine/rocksdb.go#L1053)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

it seems awkward to add this to the `engine.Writer` interface if most of the impls don't support it. thoughts on instead plumbing it down to the handful of mvcc methods that need it?
</blockquote></details>

Yeah, I don't love this approach but I also haven't found any options I like even remotely as close. I started with the plan of adding another parameter to every MVCC function and then I realized:

```
cockroach: git grep -i '[ :]= MVCC' | wc -l
     509
```

This would also have to be threaded down through a few layers in Replica. FWIW I talked this over with @benesch a while back and nothing came to mind for him either and he also decided that this was the least bad approach.

The one real reason why I think it makes sense to tie this to an `engine.Writer` is because it's the only way we're ever going to reasonably be able to have logical log entries point into the write batch (mentioned [here](https://github.com/cockroachdb/cockroach/pull/26782/files#diff-6de5fa05d2024241f5a8e7c3dc98503dR460)) without a lot of ugly code. This is still somewhat speculative, but it deserves a mention here.

I'm totally open to alternatives though. Options considered so far are:
- new argument in MVCC functions (read: every function in cockroach)
- add it to `engine.Writer`
- add it to `context.Context` because it's kind of like a trace

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28362)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/rocksdb.go, line 1053 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28362#-LJPXWht2emQNk7lJtNv:-LJU9ged78gBhvovKryA:b-38mlt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae5eacd1224f2d91c70554c3f4485f1067e850/pkg/storage/engine/rocksdb.go#L1053)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I don't love this approach but I also haven't found any options I like even remotely as close. I started with the plan of adding another parameter to every MVCC function and then I realized:

```
cockroach: git grep -i '[ :]= MVCC' | wc -l
     509
```

This would also have to be threaded down through a few layers in Replica. FWIW I talked this over with @benesch a while back and nothing came to mind for him either and he also decided that this was the least bad approach.

The one real reason why I think it makes sense to tie this to an `engine.Writer` is because it's the only way we're ever going to reasonably be able to have logical log entries point into the write batch (mentioned [here](https://github.com/cockroachdb/cockroach/pull/26782/files#diff-6de5fa05d2024241f5a8e7c3dc98503dR460)) without a lot of ugly code. This is still somewhat speculative, but it deserves a mention here.

I'm totally open to alternatives though. Options considered so far are:
- new argument in MVCC functions (read: every function in cockroach)
- add it to `engine.Writer`
- add it to `context.Context` because it's kind of like a trace
</blockquote></details>

gotcha. you only use it in a handful of them here (and it doesn't seem like there needs to be more?) so I was thinking there wouldn't be so many to thread it to. it sounds like you've thought this through, so I'm happy

**Pull request merged**
