### PR TITLE
kv: introduce setting for maximum lock wait-queue depth

### LINKED ISSUE #66017: kv: introduce cluster setting for maximum lock wait-queue depth
The [lock-table](https://github.com/cockroachdb/cockroach/blob/84499c94c01b86dc50be03e927fc0e2ff1cd3d69/pkg/kv/kvserver/concurrency/concurrency_control.go#L431)'s [wait-queues](https://github.com/cockroachdb/cockroach/blob/84499c94c01b86dc50be03e927fc0e2ff1cd3d69/pkg/kv/kvserver/concurrency/lock_table.go#L735) currently have no limit on the number of writers that can be queued on a given key. This can lead to unbounded queueing and diminishing quality of service for all writers as the queues build up. This is especially bad with high replication latency in multi-region clusters, as locks are held for the duration of a consensus replication round.

We should introduce a cluster setting that, when configured, limits the size that a single queue (`lockWaitQueue.queuedWriters.Len()`) can grow to before it begins rejecting new requests. If a request attempts to enter a queue that is already at this size limit, the request will be immediately rejected.

----

NOTE: Admission control and quality-of-service are deep topics and this issue doesn't attempt to provide a complete solution for them. Instead, it attempts to provide a limited, coarse-grained solution that we know will help serve as a release valve in various "hot key" scenarios.

A related item that this issue is not discussing is the queueing policy for these lock wait-queues. These queues are currently [FIFO with a few caveats](https://github.com/cockroachdb/cockroach/blob/84499c94c01b86dc50be03e927fc0e2ff1cd3d69/pkg/kv/kvserver/concurrency/concurrency_control.go#L60). This provides fairness, but also leads to quality of service degradation for all as queues grow. Furthermore, this leads to starvation when requests have a timeout that fires before any single request can get to the head of the queue. A LIFO queueing policy would help with this, though at the expense of fairness.

Alternatively, we could maintain fairness while avoiding starvation by introducing a dynamic maximum lock wait-queue depth based on request timeout duration. Given a request's maximum wait time before being canceled and the expected processing time of each item in the queue, we should be able to determine an optimal maximum wait-queue depth.

cc. @sumeerbhola. I'm going to try to prototype something here this Friday. Do we have an error type that we plan to use for request rejections?

### PR DESCRIPTION
**Pull request by nvb**
Fixes #66017.
Related to #67513.

This PR introduces a new `kv.lock_table.maximum_lock_wait_queue_length` cluster setting, which controls the maximum length of a lock wait-queue that requests are willing to enter and wait in. The setting can be used to ensure some level of quality-of-service under severe per-key contention. If set to a non-zero value and an existing lock wait-queue is already equal to or exceeding this length, requests will be rejected eagerly instead of entering the queue and waiting.

Before this change, the lock-table's wait-queues had no limit on the number of writers that could be queued on a given key. This could lead to unbounded queueing and diminishing quality of service for all writers as the queues built up. It could also leave to starvation (i.e. zero throughput) when requests had a timeout that fires before any single request can get to the head of the queue. This was all especially bad with high replication latency in multi-region clusters, as locks are held for the duration of a consensus replication round. 

We can see this in the following experiment. Here, we run a multi-region (demo) cluster in three configurations: `default`, `timeout`, and `queue_limit`. Under the `default` configuration, we change nothing. Under the `timeout` configuration, we set `sql.defaults.statement_timeout='250ms'`. Under the `queue_limit` configuration, we set `kv.lock_table.maximum_lock_wait_queue_length=3`. We then run a single-row, update-only workload (workload "U", mocked out in this patch):
```
./cockroach demo --global --empty --nodes=9
./cockroach sql -e 'create database ycsb primary region "us-east1" regions "us-west1", "europe-west1" survive region failure'
./cockroach workload init ycsb --families=false --insert-count=1
./cockroach workload run  ycsb --families=false --insert-count=1 --workload=U --duration=30s --tolerate-errors --concurrency=?
```

This results in the following behavior:

| setting     | concurrency | qps  | errors | p50 (ms) | p95 (ms) |
|-------------|-------------|------|--------|----------|----------|
| default     | 1           | 13.7 | 0      | 67.1     | 71.3     |
| default     | 2           | 12.6 | 0      | 142.6    | 151.0    |
| default     | 4           | 12.3 | 0      | 302.0    | 385.9    |
| default     | 8           | 12.2 | 0      | 570.4    | 1610.6   |
| default     | 16          | 12.0 | 0      | 1208.0   | 2550.1   |
| default     | 32          | 8.0  | 0      | 4563.4   | 5637.1   |
| timeout     | 1           | 14.7 | 0      | 67.1     | 67.1     |
| timeout     | 2           | 12.8 | 17     | 142.6    | 142.6    |
| timeout     | 4           | 0.2  | 464    | 71.3     | 352.3    |
| timeout     | 8           | 0.2  | 913    | 67.1     | 335.5    |
| timeout     | 16          | 0    | -      | -        | -        |
| timeout     | 32          | 0    | -      | -        | -        |
| queue_limit | 1           | 14.5 | 0      | 67.1     | 71.3     |
| queue_limit | 2           | 14.2 | 0      | 134.2    | 176.2    |
| queue_limit | 4           | 13.3 | 0      | 285.2    | 369.1    |
| queue_limit | 8           | 13.0 | 1934   | 352.3    | 486.5    |
| queue_limit | 16          | 12.8 | 4290   | 352.3    | 486.5    |
| queue_limit | 32          | 11.6 | 9203   | 385.9    | 671.1    |

The first thing to note is that under the `default` config, throughput remains relatively steady as concurrency grows, but latency grows linearly with concurrency. Next, note that under the `timeout` config, throughput falls to 0 the moment the p50 latency exceeds the `statement_timeout`. Finally, note that under the `queue_limit` config, errors begin to build once the queue limit is exceeded. However, throughput and latency hold steady as concurrency grows, as desired. So some requests are rejected, but the ones that are not are provided a good quality-of-service.

/cc @cockroachdb/kv @sumeerbhola

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> Before this change, the lock-table's wait-queues had no limit on the number of writers that could be queued on a given key. This could lead to unbounded queueing and diminishing quality of service for all writers as the queues built up. It could also leave to starvation (i.e. zero throughput) when requests had a timeout that fires before any single request can get to the head of the queue.

Can you explain the 0-throughput a bit more to me? I'd hope that requests timing out in the queue don't affect requests queued up after them because, somehow, the timed out request's ctx gets canceled and so the requests either gets out of the queue or otherwise "runs" quickly when it's its turn. So, I'd expect that some requests still would manage to get lucky and go through the queue within their timeout, stepping on the corpses of the timed out waiters in front of them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-:-MbbWoYW0Uj85GO6Xg9M:b-pr73g2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> Can you explain the 0-throughput a bit more to me? I'd hope that requests timing out in the queue don't affect requests queued up after them because, somehow, the timed out request's ctx gets canceled and so the requests either gets out of the queue or otherwise "runs" quickly when it's its turn. So, I'd expect that some requests still would manage to get lucky and go through the queue within their timeout, stepping on the corpses of the timed out waiters in front of them.

This is the hope, but it's not how these kinds of queuing problems with large processing times and equal timeouts behave in practice. Instead, they quickly reach an equilibrium where everyone reaches the head of the queue, but then gets canceled before they can finish processing. This is because the timeout doesn't just apply to queueing - it also applies to the processing itself. 

We can derive this mathematically, assuming all requests have the same expected processing time (how long they need to process before completing successfully) and timeout.

```
queue_time = (concurrency - 1) * processing_time
queue_time + processing_time = timeout

queue_time = timeout - processing_time
timeout - processing_time = (concurrency - 1) * processing_time

processing_time = timeout/concurrency
```
Notice how the processing time becomes a function of the timeout and the concurrency. So if timeout/concurrency drops below the expected processing time, this means that everyone is getting canceled before they complete. That's why qps drops to 0 with a timeout of 250ms once concurrency hits 4 - `250ms/4 = 62.5 > 67.1`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MbcDPeb3scJjUmeM30R:-MbcDPeb3scJjUmeM30S:b64vs7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L514)):*
> ```Go
> 		// The transaction cannot continue in this epoch whether this is
> 		// a retryable error or not.
> 		// WIP: we need some way to indicate that a request definitely did not leave
> ```

do you want a review before doing something here?

**Comment by nvanbenschoten** [comment]
> do you want a review before doing something here?

Not immediately. This is just a draft to prove out the idea and to solicit @sumeerbhola's feedback about how this relates to the hard rejections in the larger admission control project.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MbfswFq1R9acm2zlQpu:-MbfswFq1R9acm2zlQpv:bgl1mnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L516)):*
> ```Go
> 		// WIP: we need some way to indicate that a request definitely did not leave
> 		// an intent. Otherwise, during hard rejects, we end up attempting to
> 		// resolve intents and disrupting traffic that was not rejected.
> ```

I didn't understand this comment. Is this talking about the some other request in the txn that had a rejected request, and that other request leaving an intent? If so, what is the issue with resolving that intent -- there is no latch contention given everyone is waiting on the intent after releasing latches. What am I missing?
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MbftKAn7TsPW0M0k7P2:-MbftKAn7TsPW0M0k7P3:b-u3q8u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvserver/concurrency/concurrency_manager.go#L64)):*
> ```Go
> 		return nil
> 	},
> )
> ```

This is fine, but would be worth having some commentary on more sophisticated alternatives like CoDel which take into account queueing time before rejecting https://queue.acm.org/detail.cfm?id=2209336, or the Facebook variant mentioned in https://queue.acm.org/detail.cfm?id=2839461
There is also the LIFO option, or adaptive-LIFO, but I think it does not work easily with the lock table with a request in multiple queues and reservations -- a newer request would potentially keep breaking some subset of locks.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-Mbfqrlv8QNuBYZsgLBE:-Mbfqrlv8QNuBYZsgLBF:bp5mzy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvserver/concurrency/lock_table.go#L329)):*
> ```Go
> // - The waitQueueMaxLengthExceeded state is used to indicate that the request
> //   was rejected because it attempted to enter a lock wait-queue whose length
> //   was already equal to or exceeding the configured maximum.
> ```

this is only for writers, yes?

**Review by nvb — COMMENTED** [review]
Thanks for the reviews on this PR so far! I've gone through, addressed comments, and polished off what was already here. I also added two new commits that ensure that we get the desired behavior under UPDATE contention.

The first commit here is pulled from https://github.com/cockroachdb/cockroach/pull/67514, so please ignore that. But otherwise, PTAL when you get a chance.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-:-MeTUpdnE293whzmmdZq:buxigsa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @sumeerbhola)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MbcDPeb3scJjUmeM30R:-MeTEwcq8v9v6GJuGH-0:b4vix6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L514)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do you want a review before doing something here?
</blockquote></details>

No, I went back and reworked this. Please see the new first commit, titled "don't add intents from unambiguously failed requests to lock footprint".
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MbfswFq1R9acm2zlQpu:-MeTEoxO3LTqjLPQAXGr:b-k9cequ) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L516)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand this comment. Is this talking about the some other request in the txn that had a rejected request, and that other request leaving an intent? If so, what is the issue with resolving that intent -- there is no latch contention given everyone is waiting on the intent after releasing latches. What am I missing?
</blockquote></details>

The issue was that if we added the request to our lock spans, we would then try to resolve it in our `EndTxn(abort)` rollback batch. Typically, no-op intent resolution is fast because even though we grab latches, we bail before going through Raft because the Raft proposal is empty. However, in this case, the no-op intent resolution was still disruptive because we would hold latches, then delete our transaction record, then perform no-op intent resolution. Since we wrote to our txn record, the request still needed to go through Raft, so it held latches on the contended key across that entire duration.

I've fixed this in two different ways, either of which is enough to make the rest of this PR work correctly.

First, I've addressed this TODO by introducing a new commit here that builds upon https://github.com/cockroachdb/cockroach/pull/67514. This ensures that we don't count requests that hit lock wait-queue length limits in our lock tracking set, since we know we did not acquire a lock on that key.

I've also added a new commit that ensures that we only write tombstones to delete transaction records when the record previously existed. This can help make the `EndTxn(abort)` rollback batch in these cases much faster, as it allows them to skip Raft entirely.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MbftKAn7TsPW0M0k7P2:-MeTUEAYBpH2l8FxVb4y:bkgq6h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvserver/concurrency/concurrency_manager.go#L64)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is fine, but would be worth having some commentary on more sophisticated alternatives like CoDel which take into account queueing time before rejecting https://queue.acm.org/detail.cfm?id=2209336, or the Facebook variant mentioned in https://queue.acm.org/detail.cfm?id=2839461
There is also the LIFO option, or adaptive-LIFO, but I think it does not work easily with the lock table with a request in multiple queues and reservations -- a newer request would potentially keep breaking some subset of locks.
</blockquote></details>

Done. I also added a reference to https://github.com/cockroachdb/cockroach/issues/67513, which I think is a good medium-term project to improve these kinds of situations. The knob already exists in Postgres (so it can be viewed as a compatibility project) and it should address the pathological behavior described in https://github.com/cockroachdb/cockroach/pull/66146#issuecomment-856160965 by only setting a timeout on lock acquisition and not on an entire statement.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-Mbfqrlv8QNuBYZsgLBE:-MeTPWiO0FJ4FOPzzFhA:bo11hi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fce6fd5d98e88df38f2e9ea0ab2ed359b9d6305/pkg/kv/kvserver/concurrency/lock_table.go#L329)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is only for writers, yes?
</blockquote></details>

Yes, commented.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 548 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWNgfFANCBp5nsCGQc:-MeWNgfFANCBp5nsCGQd:b-vvcb3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e309c0ea7233aa15de5ecd7cf8857ad0aa2aa68f/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L548)):*
> ```Go
> 	// concurrent requests for extended periods of time. See #3346.
> 	if pErr != nil {
> 		// However, as an optimization, if the error indicates that a specific
> ```

nit: s/specific request/specific request (identified by pErr.Index)
___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 375 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWQ0oa1hgkNvrHKfFg:-MeWQ0oa1hgkNvrHKfFh:bvkk5tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/concurrency_control.go#L375)):*
> ```Go
> 	// to a non-zero value and an existing lock wait-queue is already equal
> 	// to or exceeding this length, the request will be rejected eagerly
> 	// instead of entering the queue and waiting.
> ```

consider specifying how the request is rejected - what error
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWQB7792fVpfCC6jEQ:-MeWQB7792fVpfCC6jER:bdi6d3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/concurrency_manager.go#L74)):*
> ```Go
> 			return nil // disabled
> 		}
> 		// Don't let the setting be dropped below a reasonable value that we don't
> ```

why this min? What's wrong with setting it to 1? (i.e. a cluster-wide NOWAIT policy)
If there's no particular reason, my vote is to remove the min.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWRV1r4HPxOQe4aZVv:-MeWRV1r4HPxOQe4aZVw:b20ov6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/lock_table.go#L68)):*
> ```Go
> 
> 	// waitQueueMaxLengthExceeded indicates that the request attempted to enter a
> 	// lock wait-queue as a writer and found that the queue's length was already
> ```

where does the "as a writer" come from? Are we not rejecting readers just the same?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @sumeerbhola)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go, line 548 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWNgfFANCBp5nsCGQc:-Mea5Zh295SQSLKA9J2P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e309c0ea7233aa15de5ecd7cf8857ad0aa2aa68f/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L548)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: s/specific request/specific request (identified by pErr.Index)
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 375 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWQ0oa1hgkNvrHKfFg:-Mea5y0-9GOzYQUqaZZF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/concurrency_control.go#L375)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider specifying how the request is rejected - what error
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWQB7792fVpfCC6jEQ:-Mea61Mp7LItc9rhwDIf:b-v954vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/concurrency_manager.go#L74)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why this min? What's wrong with setting it to 1? (i.e. a cluster-wide NOWAIT policy)
If there's no particular reason, my vote is to remove the min.
</blockquote></details>

It seems dangerous to me for this to be able to impact internal transaction processing, so I don't want users to risk shooting themselves in the foot. I think the long-term preferred approach is for this setting to be set to something high like 128 and then for specific operations to opt-in to an aggressive `lock_timeout` setting.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWRV1r4HPxOQe4aZVv:-Mea6qxRDmVl2QTfywcs:b-pk8gbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/lock_table.go#L68)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

where does the "as a writer" come from? Are we not rejecting readers just the same?
</blockquote></details>

No, we are not. Readers don't wait in lock wait-queues in the same way that writers do. See the distinction between `lockWaitQueue.queuedWriters` and `lockWaitQueue.waitingReaders`.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3, 4 of 24 files at r6, 2 of 14 files at r7, 9 of 21 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-:-MefasMo2MufAAKsYcya:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWQB7792fVpfCC6jEQ:-MefZSlO7hrs5qbG5sF1:b2rrm7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/concurrency_manager.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It seems dangerous to me for this to be able to impact internal transaction processing, so I don't want users to risk shooting themselves in the foot. I think the long-term preferred approach is for this setting to be set to something high like 128 and then for specific operations to opt-in to an aggressive `lock_timeout` setting.
</blockquote></details>

Is there a plan to run some experiments (can be after this PR merges) with highly contended workloads and see the effect of adjusting this cluster setting?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1439 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-Mef_3ubDN8udrJpzr3r:-Mef_3ubDN8udrJpzr3s:bgagd9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c14c9a38b88c20f11340696cf9a4fc230bdf15cb/pkg/kv/kvserver/concurrency/lock_table.go#L1439)):*
> ```Go
> 			} else if g.maxWaitQueueLength > 0 && curLen >= g.maxWaitQueueLength {
> 				// The wait-queue is longer than the request is willing to wait for.
> 				// Instead of entering the queue, immediately reject the request.
> ```

can you add to this comment that for simplicity we are not finding the position of this writer in the queue and rejecting the tail of the queue above the max length. That would be more fair, but more complicated, and we expect that the common case is that this waiter will be at the end of the queue.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1465 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-Mef_cTG4i_cllgNHCpT:-Mef_cTG4i_cllgNHCpU:b-wx2bo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c14c9a38b88c20f11340696cf9a4fc230bdf15cb/pkg/kv/kvserver/concurrency/lock_table.go#L1465)):*
> ```Go
> 			}
> 			g.mu.locks[l] = struct{}{}
> 			waitForState.queuedWriters = l.queuedWriters.Len()
> ```

so we're not setting queuedReaders for a writer and not setting queuedWriters for a reader?
Can you update the comment where these fields are declared.

**Review by andreimatei — APPROVED** [review]
:LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-:-MekMp-QCqpOXS-atneb:b-8fbjav)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWQB7792fVpfCC6jEQ:-MekKCIW-fPwhVwfZX61:b-skyhj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/concurrency_manager.go#L74)):*
> It seems dangerous to me for this to be able to impact internal transaction processing

OK.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWRV1r4HPxOQe4aZVv:-MekKWIt9W-CoKJZUjTP:bub2zr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/lock_table.go#L68)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No, we are not. Readers don't wait in lock wait-queues in the same way that writers do. See the distinction between `lockWaitQueue.queuedWriters` and `lockWaitQueue.waitingReaders`.
</blockquote></details>

consider hinting at the difference between reads and writes in the comment on the cluster setting.

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-:-MfFbk3A5C0D7YSVlZxu:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWQB7792fVpfCC6jEQ:-MfFa_prDKiMd9MOq-Bj:b-igzhy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/concurrency_manager.go#L74)):*
> Is there a plan to run some experiments (can be after this PR merges) with highly contended workloads and see the effect of adjusting this cluster setting?

What kinds of experiments are you thinking? There are some experimental results included in the PR description, but I imagine you're thinking of more realistic benchmarks on real machines.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-MeWRV1r4HPxOQe4aZVv:-MfFb6vHDA2bEwQCvm-u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0786e26ac9a441fd1655f594aa06148c2379c8d1/pkg/kv/kvserver/concurrency/lock_table.go#L68)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider hinting at the difference between reads and writes in the comment on the cluster setting.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1439 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-Mef_3ubDN8udrJpzr3r:-MfFbIczCPDCQevOUcHh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c14c9a38b88c20f11340696cf9a4fc230bdf15cb/pkg/kv/kvserver/concurrency/lock_table.go#L1439)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add to this comment that for simplicity we are not finding the position of this writer in the queue and rejecting the tail of the queue above the max length. That would be more fair, but more complicated, and we expect that the common case is that this waiter will be at the end of the queue.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1465 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66146#-Mef_cTG4i_cllgNHCpT:-MfFbKT5BczyfkwjKYj1:brq5ok0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c14c9a38b88c20f11340696cf9a4fc230bdf15cb/pkg/kv/kvserver/concurrency/lock_table.go#L1465)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so we're not setting queuedReaders for a writer and not setting queuedWriters for a reader?
Can you update the comment where these fields are declared.
</blockquote></details>

We are. We set the initial values of this up above. This is updating the value to reflect the new size. I added comments to make that clearer.

**Pull request merged**
