### PR TITLE
vendor: bump pebble to af0d71572c7bd24deb066d09eee646b6cb7460a4

### LINKED ISSUE #49154: roachtest: acceptance/build-analyze failed
[(roachtest).acceptance/build-analyze failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1947362&tab=buildLog) on [master@5156843cc23adecb6a70fabf19f51f46de1241ec](https://github.com/cockroachdb/cockroach/commits/5156843cc23adecb6a70fabf19f51f46de1241ec):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/build-analyze/run_1
	build_info.go:90,acceptance.go:94,test_runner.go:753: scanelf returned non-empty output (executable stack): RWX --- ---  cockroach

```

<details><summary>More</summary><p>

Artifacts: [/acceptance/build-analyze](https://teamcity.cockroachdb.com/viewLog.html?buildId=1947362&tab=artifacts#/acceptance/build-analyze)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aacceptance%2Fbuild-analyze.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by petermattis**
* internal/private: ratchet visible sequence number too
* internal/rate: add Limiter.Delay{,N}
* db: refactor tableCache.estimateDiskUsage into withReader
* internal/cache: optimize common case of Cache.Delete()
* internal/cache: remove weak cache handles
* internal/randvar: optimize Uniform.IncMax
* internal/{manual,rawalloc}: remove empty assembly files
* internal/replay: assign ingested tables correct sequence number
* db: wait for pending writes during ingestion
* db: replace tableCacheShard LRU with CLOCK-Pro
* internal/randvar: reduce exclusive locks in randvar
* cmd/pebble: miscellaneous ycsb benchmark improvements
* internal/rate: change Reserve{,N} to return a value

Fixes #49154

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49285)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by petermattis** [comment]
TFTR!

bors r+

**Comment by petermattis** [comment]
SQL logictest failures that look unrelated to this PR. Retrying.

bors r+

**Comment by otan** [comment]
(you have won the race, i can wait)

**Comment by petermattis** [comment]
`no inbound stream connection` in `acceptance/version-upgrade`. See #47024 

bors r+

**Comment by otan** [comment]
o_o

bors r+

**Pull request merged**
