### PR TITLE
roachtest: version gate convert to schema step in schema change test

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73645#-:-MqV8x5r1Tj86Emd3mnJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/schema_change_database_version_upgrade.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73645#-MqV8s7j4PtPwZUbZ5HM:-MqV8s7j4PtPwZUbZ5HN:b-ay9re9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3073d2a90d3c00adb47b6133aba183cc0086787e/pkg/cmd/roachtest/tests/schema_change_database_version_upgrade.go#L161)):*
> ```Go
> 
> 	createParentDatabaseStep := func(ctx context.Context, t test.Test, u *versionUpgradeTest) {
> 		if publicSchemaWithDescriptorsVersion.LessEq(u.clusterVersion(ctx, t, 1)) {
> ```

Seems like you don’t need to skip the create or drop.

**Comment by RichardJCai** [comment]
> :lgtm:
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73645#-:-MqV8x5r1Tj86Emd3mnJ:bnfp4nl)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)
> 
> _[pkg/cmd/roachtest/tests/schema_change_database_version_upgrade.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73645#-MqV8s7j4PtPwZUbZ5HM:-MqV8s7j4PtPwZUbZ5HN:b-ay9re9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3073d2a90d3c00adb47b6133aba183cc0086787e/pkg/cmd/roachtest/tests/schema_change_database_version_upgrade.go#L161)):_
> 
> > ```go
> > 	createParentDatabaseStep := func(ctx context.Context, t test.Test, u *versionUpgradeTest) {
> > 		if publicSchemaWithDescriptorsVersion.LessEq(u.clusterVersion(ctx, t, 1)) {
> > ```
> 
> Seems like you don’t need to skip the create or drop.

Figured we might as well skip the drop and create anyways since they wouldn't do anything. Save that precious compute power.

**Comment by RichardJCai** [comment]
TFTR 
bors r=ajwerner

**Comment by RichardJCai** [comment]
bors r=ajwerner

**Comment by rafiss** [comment]
@ajwerner @RichardJCai i saw this flyby and was a bit confused. is `ALTER DATABASE CONVERT TO SCHEMA` being disabled entirely in 22.1? doesn't it need to go through a deprecation cycle first? i also noticed that the commit where it happens (7780e1e085dbfa849defcef63b5138e80c18a17b) has it as a `sql change` release note, but it seems more like a `backwards-incompatible change` -- i worry that it won't be surfaced appropriately in the release notes.

**Comment by RichardJCai** [comment]
> @ajwerner @RichardJCai i saw this flyby and was a bit confused. is `ALTER DATABASE CONVERT TO SCHEMA` being disabled entirely in 22.1? doesn't it need to go through a deprecation cycle first? i also noticed that the commit where it happens ([7780e1e](https://github.com/cockroachdb/cockroach/commit/7780e1e085dbfa849defcef63b5138e80c18a17b)) has it as a `sql change` release note, but it seems more like a `backwards-incompatible change` -- i worry that it won't be surfaced appropriately in the release notes.

Yeah that release note should definitely be backwards-incompatible change. I disabled it in #72000 since there wasn't really a great way around it as CONVERT TO SCHEMA was only allowed for the special case where all tables were in the public schema and not UDS, but now that the public is the same as an UDS, we'd have to do some more work to make it work.

My thoughts were that this was such a niche feature and likely no one is using it in prod that we could simply disallow it. I can't imagine anyone actually depending on it in a workload where it breaks their workflow cause of this change.

We should look at the telemetry on this and determine if it's worth adding this back.

**Pull request merged**
