### PR TITLE
invertedidx: derive geog/geom filters which enable inverted index scan

### LINKED ISSUE #103616: roachtest/unoptimized-query-oracle: incorrect results for geospatial
roachtest.unoptimized-query-oracle/disable-rules=all/rand-tables [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10137691?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10137691?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all/rand-tables) on release-23.1 @ [4d53217fb2d27559257d46261badb3be91428d1a](https://github.com/cockroachdb/cockroach/commits/4d53217fb2d27559257d46261badb3be91428d1a):

```
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/rand-tables/run_1
(query_comparison_util.go:252).runOneRoundQueryComparison: . 1294 statements run: expected unoptimized and optimized results to be equal
  []string(
- 	nil,
+ 	{
+ 		"BOX(-0.17596396378499507 -0.7935108588146653,1.6507331385363777 0.3892996820427791)",
+ 		"BOX(-0.44992608732063816 -0.8355313727814945,0.7592064540513982 -0.10620010400194807)",
+ 		"BOX(-0.5991572309955492 -1.0771724478708085,1.4605257094972963 0.8794544719921826)",
+ 		"BOX(-0.6567783142434518 -0.20189765997084663,-0.5427570031482938 -0.11573451853214733)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		"BOX(-0.8295263453828648 -0.12921899431101314,-0.6879662233412243 1.7261578865680827)",
+ 		...,
+ 	},
  )
sql: SELECT
	"tÂb😌389"."col2_'6" AS "coͯ
l1275"
FROM
	defaultdb.public."table2"@[0] AS "tÂb😌389"
WHERE
	(1.2345678901234566e-43:::FLOAT8 <= st_distance("tÂb😌389".c😽ol2_4::GEOGRAPHY, '0106000020E610000000000000':::GEOGRAPHY::GEOGRAPHY)::FLOAT8)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all/rand-tables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28097

### PR DESCRIPTION
**Pull request by msirek**
The query normalization rules FoldEqZeroSTDistance,
FoldCmpSTDistanceLeft, FoldCmpSTDistanceRight, FoldCmpSTMaxDistanceLeft
and FoldCmpSTMaxDistanceRight replace binary comparison operations,
=, <, >, <=, >= involving the `st_distance` or `st_maxdistance` functions
with equivalent function calls which may enable inverted index scan, for
example st_dwithin, and st_dfullywithin. For non-null and non-empty
geographies and geometries, this rewrite is semantically equivalent, but
for null or empty inputs, `st_distance` uses three-valued boolean logic
and returns a null. `st_dwithin` always returns true or false, so may
return a different value when the expression is negated. For example,
the following test returns `true`, but should return `null`:
```sql
CREATE TABLE g1 (geog GEOGRAPHY);
INSERT INTO g1 VALUES (ST_GeogFromText('MULTILINESTRING EMPTY'));
SELECT ST_Distance('POINT(0 0)'::GEOGRAPHY, geog) > 1 AS predicate_result FROM g1;
  predicate_result
--------------------
         t
```

The solution is to move all of the logic in the above normalization
rules into `geoFilterPlanner.extractInvertedFilterConditionFromLeaf`,
and use the derived predicate only for the purposes of finding inverted
index scan spans. The spans will always include all rows qualified for
the original predicate, but may include additional rows. The original
filter is then applied to the results of the inverted index scan to
filter out any results with nulls or empty geographies and geometries.

Epic: none
Fixes: #103616

Release note (bug fix): This patch fixes a bug in geospatial queries,
where a query filter of the form `ST_Distance(geog1, geog2) > constant`,
or `ST_MaxDistance(geom1, geom2) > constant`, where the operator is one
of >, <, >=, <=, or a filter of the form `ST_Distance(geog1, geog2, false) = 0`
may mistakenly evaluate to `true` when one or both of the inputs is null
or an empty geography/geometry. More rows could be returned by the query
than expected.

----
xform: move st_distance rules tests from norm to xform

This commit moves the tests for the old normalization rules
FoldEqZeroSTDistance, FoldCmpSTDistanceLeft, FoldCmpSTDistanceRight,
FoldCmpSTMaxDistanceLeft and FoldCmpSTMaxDistanceRight from norm
into xform. The tests now check whether the derived filter triggers the
GenerateInvertedIndexScans rule.

Epic: none
Informs: #103616

Release note: None

----
invertedidx: move geospatial filter derivation functions out of norm

This commit moves functions previously associated with normalization
rules, but now associated with exploration-time geospatial filter
derivation out of the norm package.

Epic: none
Informs: #103616

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
*[`pkg/sql/opt/invertedidx/geo.go` line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8lQM24or0IHTQOq-U:-Nc8lQM24or0IHTQOq-V:b-mek2tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/opt/invertedidx/geo.go#L427)):*
> ```Go
> 		makeSTDWithinFunc = g.factory.CustomFuncs().MakeSTDFullyWithin
> 	}
> 	return makeSTDWithinFunc(op, args, boundExpr, leftIsFunction), true
> ```

[nit] I think I'd prefer something like this:
```
	c := g.factory.CustomFuncs() // Could do this higher in the method
	if private.Name == "st_distance" {
		return c.MakeSTDWithin(op, args, boundExpr, leftIsFunction), true
	}
	return c.MakeSTDFullyWithin(op, args, boundExpr, leftIsFunction), true

```
Feel free to keep it if you'd prefer, though.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work! Just some nits and questions.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-:-Nc8sGGsBxy2XtuQU5gq:b-v2e83e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/invertedidx/geo.go` line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8lQM24or0IHTQOq-U:-Nc8sB9Q-EDDQYU5ORs8:b-vynvjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/opt/invertedidx/geo.go#L427)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] I think I'd prefer something like this:
```
	c := g.factory.CustomFuncs() // Could do this higher in the method
	if private.Name == "st_distance" {
		return c.MakeSTDWithin(op, args, boundExpr, leftIsFunction), true
	}
	return c.MakeSTDFullyWithin(op, args, boundExpr, leftIsFunction), true

```
Feel free to keep it if you'd prefer, though.
</blockquote></details>

(This is less applicable now)
___
*[`pkg/sql/opt/norm/comp_funcs.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8pAHz9f4bFID4eQ4q:-Nc8pAHz9f4bFID4eQ4r:b9wz7bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/opt/norm/comp_funcs.go#L195)):*
> ```Go
> // otherwise false.
> func (c *CustomFuncs) MakeSTDFullyWithin(
> 	op opt.Operator, args memo.ScalarListExpr, bound opt.ScalarExpr, fnIsLeftArg bool,
> ```

[nit] Since we're already eliminating the left/right variants, why not go the whole way and just call `MakeSTDWithin` directly?
___
*[`pkg/sql/opt/norm/comp_funcs.go` line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8pQ7E8izzaw5r2T_c:-Nc8pQ7E8izzaw5r2T_d:b-qn8q42) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/opt/norm/comp_funcs.go#L210)):*
> ```Go
> 	op opt.Operator, args memo.ScalarListExpr, bound opt.ScalarExpr, fnName string, fnIsLeftArg bool,
> ) opt.ScalarExpr {
> 	var not bool
> ```

[nit] We can probably remove the `not` logic now, right?
___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6049 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8qDNU4fOKDQuCRpyT:-Nc8qDNU4fOKDQuCRpyU:b-d7py0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/logictest/testdata/logic_test/geospatial#L6049)):*
> ```
> # Null and empty geom values should not appear in the output.
> query T rowsort
> SELECT tag FROM t103616@geog_idx
> ```

Should this use `geom_idx` instead?
___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6065 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8qWt41hN_7z5aBRcO:-Nc8qWt41hN_7z5aBRcP:b1mqssl) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/logictest/testdata/logic_test/geospatial#L6065)):*
> ```
> # Null and empty geog values should not appear in the output.
> query T rowsort
> SELECT tag FROM t103616
> ```

Why not specify the index like above?

**Review by msirek — COMMENTED** [review]
Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-:-Nc9aEqPBXo0wg8gTVcZ:b-zcjvte)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/opt/invertedidx/geo.go` line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8lQM24or0IHTQOq-U:-Nc9TfpL-1Jgu4DErH1b:bol96zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/opt/invertedidx/geo.go#L427)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

(This is less applicable now)
</blockquote></details>

Modified as suggested
___
*[`pkg/sql/opt/norm/comp_funcs.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8pAHz9f4bFID4eQ4q:-Nc9VDuf0PpuyvVC3SMy:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/opt/norm/comp_funcs.go#L195)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Since we're already eliminating the left/right variants, why not go the whole way and just call `MakeSTDWithin` directly?
</blockquote></details>

Done
___
*[`pkg/sql/opt/norm/comp_funcs.go` line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8pQ7E8izzaw5r2T_c:-Nc9Vz3v61LWbNNFEULj:b-simz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/opt/norm/comp_funcs.go#L210)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] We can probably remove the `not` logic now, right?
</blockquote></details>

I've removed generation of a NOT expression, but still need to detect the `not` case and return the fact that nothing was derived.
___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6049 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8qDNU4fOKDQuCRpyT:-Nc9_Vd_8A4Du3vpEUxc:b-fpnnsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/logictest/testdata/logic_test/geospatial#L6049)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should this use `geom_idx` instead?
</blockquote></details>

The comment was wrong, not the index. Updated the comment.
___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6065 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8qWt41hN_7z5aBRcO:-Nc9a-cIEbimBqS9z2pL:bd2rbf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/logictest/testdata/logic_test/geospatial#L6065)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why not specify the index like above?
</blockquote></details>

Because the query would error out as inverted index scan can't be used.

**Review by DrewKimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108954)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek)

___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6065 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8qWt41hN_7z5aBRcO:-NcA5nEQETNtn5RlyOD5:b-svfso2) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/logictest/testdata/logic_test/geospatial#L6065)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Because the query would error out as inverted index scan can't be used.
</blockquote></details>

Got it, I was confused by the other case with `NOT`, but I'm guessing it can use the index because the `NOT` folds into the comparison.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108954)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6065 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-Nc8qWt41hN_7z5aBRcO:-NcBBm3P8QYahXXEPDXN:ba5dw0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eed8357cd2476ce5738d0821de31994faed3d1/pkg/sql/logictest/testdata/logic_test/geospatial#L6065)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Got it, I was confused by the other case with `NOT`, but I'm guessing it can use the index because the `NOT` folds into the comparison.
</blockquote></details>

Yeah, the NOT just changes `>` to `<=`, but it's the NOT case in the derived term that matters.

**Comment by michae2** [comment]
Do we also want to backport this to release-23.1.9-rc?

**Comment by msirek** [comment]
> Do we also want to backport this to release-23.1.9-rc?

Yes, I think so. Included it.

**Review by mgartner — APPROVED** [review]
:lgtm: This bug was confusing - great job finding a nice solution! Thanks for organizing the commits thoughtfully - it made reviewing it pleasant!

Hopefully we can get some adequate baking time for this on master and the release branches incase there are any edge cases that we missed here.

> Reviewed 2 of 6 files at r1, 5 of 5 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-:-NcXnoWc5hXShlzHTZ7p:b-slakc6)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/opt/norm/testdata/rules/comp` line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-NcXnYI15Y0Zaq2objA3:-NcXnYI15Y0Zaq2objA4:b7tnvuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e144ce5e1618cc5829750c43a4c6a99ce896858/pkg/sql/opt/norm/testdata/rules/comp#L11)):*
> ```
>   val FLOAT,
>   INVERTED INDEX(geom),
>   INVERTED INDEX(geog)
> ```

nit: you can remove these indexes in the second commit.

**Review by msirek — COMMENTED** [review]
Thanks, I'll merge to master first and let the backport PRs sit for a while once opened.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-:-Nc_6Pe_DpJP3BMVCF-R:b7w5jmu)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/opt/norm/testdata/rules/comp` line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/108954#-NcXnYI15Y0Zaq2objA3:-Nc_6LhnC5sPulw_DJA5:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e144ce5e1618cc5829750c43a4c6a99ce896858/pkg/sql/opt/norm/testdata/rules/comp#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you can remove these indexes in the second commit.
</blockquote></details>

Done

**Comment by msirek** [comment]
bors r=DrewKimball,mgartner

**Pull request merged**
