### PR TITLE
opt: constant-fold regclass casts via resolver

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit teaches norm.Factory to constant-fold casts from string to
regclass (which look up table ids given table names) via the schema
resolver.

To do this, a cat.Catalog reference is threaded into norm.Factory at
Init time.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: modulo some comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-:-LvfEmY7788V7YqPuCfD:b6eq0yt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/opt/norm/fold_constants.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfDi_fA1DdJ0pxDT6R:-LvfDi_fA1DdJ0pxDT6S:b923hhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/norm/fold_constants.go#L112)):*
> ```Go
> 				// Special case: we're casting a string to a REGCLASS oid, which is a
> 				// table id lookup.
> 				flags := cat.Flags{AvoidDescriptorCaches: false /* TODO(jordan) is this right? */, NoTableStats: true}
> ```

Yeah we should use the caches by default unless we have a known reason not to.
___
*[pkg/sql/opt/norm/fold_constants.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfCqVy3VnaU2ynJGph:-LvfCqVy3VnaU2ynJGpi:b-uw6yhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/norm/fold_constants.go#L117)):*
> ```Go
> 				tn, err := c.f.evalCtx.Planner.ParseQualifiedTableName(c.f.evalCtx.Ctx(), string(s))
> 				if err != nil {
> 					return nil
> ```

Add the "save this cast for the execbuilder" comment here (this looks like a typo). Or reverse the check to `if err == nil { ... }` and let it fall through
___
*[pkg/sql/opt/xform/optimizer.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfDwMa36auVAIEhQ6k:-LvfDwMa36auVAIEhQ6l:b-wcu157) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/xform/optimizer.go#L117)):*
> ```Go
> func (o *Optimizer) DetachMemo() *memo.Memo {
> 	detach := o.f.DetachMemo()
> 	o.Init(o.evalCtx, nil)
> ```

This seems wrong. We can use the optimizer after `DetachMemo` (specifically`AssignPlaceholders` and `Optimize`), we should maintain the correct catalog reference.

You can test this using a placeholder inside one of these casts. The normalization rule can only kick in after `AssignPlaceholders`

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43040)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/opt/norm/fold_constants.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfK_0A2ahpVKw2PCHC:-LvfK_0A2ahpVKw2PCHD:b1a639a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/norm/fold_constants.go#L112)):*
> ```Go
> 				// Special case: we're casting a string to a REGCLASS oid, which is a
> 				// table id lookup.
> 				flags := cat.Flags{AvoidDescriptorCaches: false /* TODO(jordan) is this right? */, NoTableStats: true}
> ```

NIT: Would be nice for clarity to factor out this block of code into a helper method, since it's very distinct and standalone.
___
*[pkg/sql/opt/norm/fold_constants.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfL06V3KLEWvtyXKL9:-LvfL06V3KLEWvtyXKLA:bqkl7pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/norm/fold_constants.go#L119)):*
> ```Go
> 					return nil
> 				}
> 				ds, resName, err := c.f.catalog.ResolveDataSource(c.f.evalCtx.Context, flags, tn)
> ```

Can't the catalog reference be `nil`? If that's possible in production, we should have test of that case somewhere.
___
*[pkg/sql/opt/xform/optimizer.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfDwMa36auVAIEhQ6k:-LvfKOcn6iZ5UhRtonzg:bx74ba2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/xform/optimizer.go#L117)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems wrong. We can use the optimizer after `DetachMemo` (specifically`AssignPlaceholders` and `Optimize`), we should maintain the correct catalog reference.

You can test this using a placeholder inside one of these casts. The normalization rule can only kick in after `AssignPlaceholders`
</blockquote></details>

We should store the catalog in the optimizer as a member variable (as well as the factory). We can then provide that reference to `Init`.

**Review by jordanlewis — COMMENTED** [review]
PTAL. I had to add a new method to catalog.Object unfortunately, since we need a way to get back the original descriptor ID of virtual tables now that we're using those ids to report directly. Hope that's not too gross.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-:-LvkvVCu66_FL7Fr9O2Z:b-t7vun7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/fold_constants.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfCqVy3VnaU2ynJGph:-Lvkls8IElZk0WVxmVf7:b-z44bpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/norm/fold_constants.go#L117)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Add the "save this cast for the execbuilder" comment here (this looks like a typo). Or reverse the check to `if err == nil { ... }` and let it fall through
</blockquote></details>

It should just fail here rather than letting it fall through, fixed.
___
*[pkg/sql/opt/norm/fold_constants.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LvfL06V3KLEWvtyXKL9:-Lvklq5N9iZZyBQ5sRSM:b-6a0yqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12f1aaedb088437778fd52033f6e2c4bdf07e75/pkg/sql/opt/norm/fold_constants.go#L119)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can't the catalog reference be `nil`? If that's possible in production, we should have test of that case somewhere.
</blockquote></details>

No, it's not possible.

**Comment by jordanlewis** [comment]
Pushed one more revision. A few annoying things to fix. I had to refactor `ParseQualifiedTableName` a little bit to make sure the opt tester could see it, so I moved it to `parser`, which works in most but all cases. To finish the refactor I think we need to eventually move `builtins` into a different package than `tree`, but I obviously can't do that right now.

**Comment by jordanlewis** [comment]
PTAL

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

Pretty cool, came out cleaner than I expected.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-:-LwKvxdoDQ0VQQ24rgi8:bislwds)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @jordanlewis)

___
*[pkg/sql/opt/norm/fold_constants.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43040#-LwKvPuR8XaZpIGv6rCB:-LwKvPuR8XaZpIGv6rCC:bmjgq22) ([raw file](https://github.com/cockroachdb/cockroach/blob/762edec06de100052da9f37842657a0062cb2b3d/pkg/sql/opt/norm/fold_constants.go#L128)):*
> ```Go
> 	c.mem.Metadata().AddDependency(opt.DepByName(&resName), ds, privilege.SELECT)
> 
> 	return c.f.ConstructConstVal(tree.NewDOidWithName(tree.DInt(ds.PostgresDescriptorID()), types.RegClass, string(tn.TableName)),
> ```

[nit] pull out `oid := tree.NewDOidWithName(..)`

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Pull request merged**
