### PR TITLE
backupccl: add opt-in last-backup-time metric

### LINKED ISSUE #54412: backup schedules: ability to monitor specific schedule last success
Some operators (like CC) want the ability to monitor when a specific schedule / schedules last completed.

Currently the time-series metrics do not include any keys specific to a given user-created record, as a cluster could contain thousands of schedules and we do not want each to create separate time series keys. However, operators want to be able to look at time series to determine that they're hitting their RPO SLA, which implies seeing the last successful time for the schedule(s) that actually provides that RPO.

To avoid creating an unbounded number of time series keys by making a gauge per schedule by default but still allow this, we could allow an operator to opt into creating and updating a gauge based on the schedule name. Alternatively, we could have one pre-made time series for "last-rpo-designated-run" or something where an option on the schedule causes it to update that gauge when it completes (while maintaining the invariant that a given binary has a pre-determined set of time series keys it can emit).

### PR DESCRIPTION
**Pull request by dt**
This adds a metric for the time captured by the last completed backup run by a schedule
designated as updating this metric. This can be used to specify a schedule as maintaining
your RPO (say you hourly cluster backup) and thus have a timeseries metric tracking that RPO
which can then be monitored.

Note: if an operator wants granular tracking of separate schedules to monitor the RPO of
one database or another, they should use SHOW against those specific schedules or some other
means, as we do not want to add an unbounded number of user-defined timeseries to our metrics.
Instead, this adds only one metric, and the operator can decide, which, if any, schedules
completing will update that metric.

Fixes #54412.

Release note (sql change): Add an option to scheduled backups to maintain a timeseries metric for last backed up timestamp.

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHs20r87PYqZoK4Ujrl:-MHs20r87PYqZoK4Ujrm:b-obhpna) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/create_scheduled_backup.go#L39)):*
> ```
> "updates_last_backup_metric"
> ```
do we want to slot "time" into this option name somewhere? Could be a little ambiguous on face value as to what metric of the last backup we are updating.
___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHs1_jn1y2phBKRaerA:-MHs1_jn1y2phBKRaerB:b5q7pqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/create_scheduled_backup.go#L288)):*
> ```
> updateMetricOnSucess
> ```
nit: updateMetricOnSuccess

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHs20r87PYqZoK4Ujrl:-MHvGwD53a6gDJnz9ALJ:b-az7zpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/create_scheduled_backup.go#L39)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> "updates_last_backup_metric"
> ```
do we want to slot "time" into this option name somewhere? Could be a little ambiguous on face value as to what metric of the last backup we are updating.
</blockquote></details>

I would also maybe drop metric? It's kinda specific to how we do things.
How about `track_last_backup_time`?
___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHvHks0-OYUR50YX8O5:b8stn9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
> ```Go
> 				rpoMetric: metric.NewGauge(metric.Metadata{
> 					Name:        "schedules.BACKUP.last-completed-time",
> 					Help:        "The unix timestamp of the most recently completed backup by a scehedule specified as maintaining this metric",
> ```

So, this is not a per-schedule metric...  Didn't we want per-schedule opt in metric? Like schedules.BACKUP.full_cluster = <timestamp>
schedules.BACKUP.some_other_schedule = <timestamp>

Also, don't we need to register this metric with the registry?
If we do want to have just one of these metrics, then, why not add it to the metrics struct above?

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHvMmEfAxUz4LIO9E7y:b-swb4vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

So, this is not a per-schedule metric...  Didn't we want per-schedule opt in metric? Like schedules.BACKUP.full_cluster = <timestamp>
schedules.BACKUP.some_other_schedule = <timestamp>

Also, don't we need to register this metric with the registry?
If we do want to have just one of these metrics, then, why not add it to the metrics struct above?
</blockquote></details>

Ahh.. I see -- this is exactly how you wanted it.  I think adding this single variable to the metrics struct probably makes sense?

Still though, I'm not sure just how useful it would be to have just 1 schedule that can have this set (and, it also looks like we are not enforcing this in any way, making it easy to make operator mistake of assigning this metric to multiple schedules).

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHs20r87PYqZoK4Ujrl:-MHvNser2dBC4UL62CUl:bxxsap3) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/create_scheduled_backup.go#L39)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would also maybe drop metric? It's kinda specific to how we do things.
How about `track_last_backup_time`?
</blockquote></details>

"track" it _where_ though? like, yes, the name is specific to metrics, but that's because it is specifically asking to update the "last backup" metric. You could imagine we might also have a last-backup file, or last-backup row in a special table, or I dunno, any number of other ways one might track this, but this specific option is for a time-series metric since that is what a lot of our operator/SRE folks prefer to use for passive monitoring. 
___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHvOM2ADG_G0r1_Ft0J:b-mdnzmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Ahh.. I see -- this is exactly how you wanted it.  I think adding this single variable to the metrics struct probably makes sense?

Still though, I'm not sure just how useful it would be to have just 1 schedule that can have this set (and, it also looks like we are not enforcing this in any way, making it easy to make operator mistake of assigning this metric to multiple schedules).

</blockquote></details>

I don't think adding to the general `jobs`-defined metrics struct makes sense: this feature -- an RPO metric -- is specific to backups. But I do want it in the struct returned by `Metrics()` so it gets registered as you mention, so wrapped the jobs one and added it there. 

To the other question though:

I don't think we want per-schedule metrics:  if you want to monitor schedule 52 and schedule 71 and schedule 34, then you should use an API (i.e. SQL for now, maybe the admin HTTP interface in the future) to interact with and inspect those schedules and do what you want with the results. We offer that, and you can build whatever you need on it. 

But I do think a single metric is useful for a large number of deployments. In the common case 1 cluster = 1 inc+full schedule doing cluster backup. In this case, that/those schedule(s) "own" the RPO for that cluster. So having a single metric for that cluster, and then allowing you to designate which schedule(s) update it is a "make easy things easy" win for this common case (including all of CC).

The one protection I think makes sense here is only admins should be allowed to use this option since it affects cluster-wide state (currently all schedules are admin but that might change).

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHs20r87PYqZoK4Ujrl:-MHvYN154h4OQJTuIUdA:b-h7zymj) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/create_scheduled_backup.go#L39)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

"track" it _where_ though? like, yes, the name is specific to metrics, but that's because it is specifically asking to update the "last backup" metric. You could imagine we might also have a last-backup file, or last-backup row in a special table, or I dunno, any number of other ways one might track this, but this specific option is for a time-series metric since that is what a lot of our operator/SRE folks prefer to use for passive monitoring. 
</blockquote></details>

record_last_backup_time?
___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHvYdkaAMNjqpAAubO1:b-yqsms5) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think adding to the general `jobs`-defined metrics struct makes sense: this feature -- an RPO metric -- is specific to backups. But I do want it in the struct returned by `Metrics()` so it gets registered as you mention, so wrapped the jobs one and added it there. 

To the other question though:

I don't think we want per-schedule metrics:  if you want to monitor schedule 52 and schedule 71 and schedule 34, then you should use an API (i.e. SQL for now, maybe the admin HTTP interface in the future) to interact with and inspect those schedules and do what you want with the results. We offer that, and you can build whatever you need on it. 

But I do think a single metric is useful for a large number of deployments. In the common case 1 cluster = 1 inc+full schedule doing cluster backup. In this case, that/those schedule(s) "own" the RPO for that cluster. So having a single metric for that cluster, and then allowing you to designate which schedule(s) update it is a "make easy things easy" win for this common case (including all of CC).

The one protection I think makes sense here is only admins should be allowed to use this option since it affects cluster-wide state (currently all schedules are admin but that might change).
</blockquote></details>

I see re metrics specific to backup.  It might still make sense to 
have BackupMetrics {
  ExecutorMetrics
}
and just initialize those here.  This way the rest of the code (job_scheduler.go) would still work correctly and register those metrics with the registry.

I don't know about the rest.  If we are saying "use API to monitor those other schedules"... then just use API.  Why would you want to have one way to monitor schedule A & B, and completely different way to monitor your RPO schedule.  

If we insist on having just 1 (and only 1) metric for those RPO backups, then why are we adding a key/value to `create schedule` statement? Doesn't that imply that this metric applies to the schedule I'm creating?  I think we're causing more confusion here.  If this is truly a single instance metric, then maybe setting cluster setting to indicate which schedule you want to have this RPO tracking on might make more sense (in my opinion).

I do think that if we are adding this opt in feature *per schedule*, then we should support this per schedule.  THe number of metrics is not unbounded (it is opt in), and the interface where you specify `keep_track_of_this_schedule` per schedule is pretty clear (IMO) wrt to the expected behavior.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHvav1Y4gzFtQyn919f:b3a1mek) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I see re metrics specific to backup.  It might still make sense to 
have BackupMetrics {
  ExecutorMetrics
}
and just initialize those here.  This way the rest of the code (job_scheduler.go) would still work correctly and register those metrics with the registry.

I don't know about the rest.  If we are saying "use API to monitor those other schedules"... then just use API.  Why would you want to have one way to monitor schedule A & B, and completely different way to monitor your RPO schedule.  

If we insist on having just 1 (and only 1) metric for those RPO backups, then why are we adding a key/value to `create schedule` statement? Doesn't that imply that this metric applies to the schedule I'm creating?  I think we're causing more confusion here.  If this is truly a single instance metric, then maybe setting cluster setting to indicate which schedule you want to have this RPO tracking on might make more sense (in my opinion).

I do think that if we are adding this opt in feature *per schedule*, then we should support this per schedule.  THe number of metrics is not unbounded (it is opt in), and the interface where you specify `keep_track_of_this_schedule` per schedule is pretty clear (IMO) wrt to the expected behavior.

</blockquote></details>

re: struct / embedding -- isn't that what the code is now doing? not sure I follow.

On the rest: opt-in per-schedule metrics is still unbounded metrics -- tt's a ~hard rule that the set of metrics must be statically defined by the binary. Imagine a flawed script passes the opt-in and accidentally makes a new schedule every second -- If it opts all the schedules in to one metrics, that metric is nonsensical but the system is otherwise fine. If it makes hundreds of thousands of metrics, all the o(n) time series code (the scraper/endpoints, the ui, etc) will fall over and affect far more than backups. So, pretty :thumbsdown: on any per-schedule metrics.

We could have _no_ RPO metric since you _can_ actively come in and inspect the schedule or schedules that constitute RPO for the thing or things you need to monitor. But that means you still need to run a service like cron, backupper, etc that'll periodically connect to your cluster and run some commands in order to ensure you're maintaining your RPO -- ie. the exact thing we're aiming to not require with the scheduled backup feature. Our SREs pointed out that operators already have monitoring in place via passive time series inspection and that that how they want to monitor things -- anything else is cumbersome. For simple clusters with a single RPO target, I think we can meet them there: we give them a metric, they decide which schedule(s) completing constitute their RPO and then we have those maintain the metric.

 For complex setups, if you, say, have multiple teams with their own DBs and their own schedules and different RPO SLAs, then sure, this won't work, but we're we optimizing for the common-case first, and operators doing complex things like the latter can more reasonably be expected to need to put in a bit more work (i.e. a scraper that actively inspects individual schedules) for their more complex setups.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHwRsFXDhsTyQ9u2Bt2:b-e8vbzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

re: struct / embedding -- isn't that what the code is now doing? not sure I follow.

On the rest: opt-in per-schedule metrics is still unbounded metrics -- tt's a ~hard rule that the set of metrics must be statically defined by the binary. Imagine a flawed script passes the opt-in and accidentally makes a new schedule every second -- If it opts all the schedules in to one metrics, that metric is nonsensical but the system is otherwise fine. If it makes hundreds of thousands of metrics, all the o(n) time series code (the scraper/endpoints, the ui, etc) will fall over and affect far more than backups. So, pretty :thumbsdown: on any per-schedule metrics.

We could have _no_ RPO metric since you _can_ actively come in and inspect the schedule or schedules that constitute RPO for the thing or things you need to monitor. But that means you still need to run a service like cron, backupper, etc that'll periodically connect to your cluster and run some commands in order to ensure you're maintaining your RPO -- ie. the exact thing we're aiming to not require with the scheduled backup feature. Our SREs pointed out that operators already have monitoring in place via passive time series inspection and that that how they want to monitor things -- anything else is cumbersome. For simple clusters with a single RPO target, I think we can meet them there: we give them a metric, they decide which schedule(s) completing constitute their RPO and then we have those maintain the metric.

 For complex setups, if you, say, have multiple teams with their own DBs and their own schedules and different RPO SLAs, then sure, this won't work, but we're we optimizing for the common-case first, and operators doing complex things like the latter can more reasonably be expected to need to put in a bit more work (i.e. a scraper that actively inspects individual schedules) for their more complex setups.
</blockquote></details>

I don't think it was doing it in the first version you sent.  Anyway, good re backupMetrics.

I kinda think that if we do wind up with faulty script creating backups every second or whatnot, I would imagine falling over if we try to scrape anything would be pretty low on the priority list.

This type of misuse, vis-a-vis too many metrics, can also be easily mitigated and detected.  For example, we can keep track of the number of RPO metrics either by doing expensive-ish select to count number of schedule with RPO tracking, or, quite simply, adding cluster setting that gets incremented when we create new rpo tracking schedule).  We can also have a max cluster setting to control the limit on those.  So, these types of scenarios are not too worrisome to me.

Regarding having no rpo metric: I made a point that having 1 RPO metric, which for some reason is associated with `create schedule statement`, even though you cannot/should not have more than 1 of those, is simply confusing.  I made this argumet as a reply to your argument that if you want to have more than 1, then monitor the rest of the schedules using something else (i.e. SQL). 
 It's this part that's really confusing to me.

So, to summaries:
  1. `create schedule WITH rpo` seems to imply to me, as an end user, that this RPO thing is specific to *this* schedule.  It doesn't not say: create this 1 rpo metric for my cluster.
  2. If we tell to end users that in order to have more than one of those monitored they have to resort to some other means (including external crontab) makes it even worse: I think in that case we should offer *none* -- just tell users they have to use external system. 
  3. If we really do believe there should be one and only one rpo backup metric, then this is clearly not a schedule specific setting -- it's a scheduled backup specific setting -- for *all* scheduled backups -- and thus, it's a cluster setting.

I have to disagree on your :thumbsdown:  re opt-in RPO tracking.  I think doing what this PR proposes is the least desirable outcome.  It creates confusing interface that will be hard to explain to end users; it introduces ample opportunity to misconfigure system (by tracking multiple backups -- and thus producing wrong or misleading signal to the end users); and for anything more complex (like CC wanting to keep track of 2 backups for 2 clients), it would still require some external system.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHwa2BHCGKHM9TVc-_O:b-2n0lon) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't think it was doing it in the first version you sent.  Anyway, good re backupMetrics.

I kinda think that if we do wind up with faulty script creating backups every second or whatnot, I would imagine falling over if we try to scrape anything would be pretty low on the priority list.

This type of misuse, vis-a-vis too many metrics, can also be easily mitigated and detected.  For example, we can keep track of the number of RPO metrics either by doing expensive-ish select to count number of schedule with RPO tracking, or, quite simply, adding cluster setting that gets incremented when we create new rpo tracking schedule).  We can also have a max cluster setting to control the limit on those.  So, these types of scenarios are not too worrisome to me.

Regarding having no rpo metric: I made a point that having 1 RPO metric, which for some reason is associated with `create schedule statement`, even though you cannot/should not have more than 1 of those, is simply confusing.  I made this argumet as a reply to your argument that if you want to have more than 1, then monitor the rest of the schedules using something else (i.e. SQL). 
 It's this part that's really confusing to me.

So, to summaries:
  1. `create schedule WITH rpo` seems to imply to me, as an end user, that this RPO thing is specific to *this* schedule.  It doesn't not say: create this 1 rpo metric for my cluster.
  2. If we tell to end users that in order to have more than one of those monitored they have to resort to some other means (including external crontab) makes it even worse: I think in that case we should offer *none* -- just tell users they have to use external system. 
  3. If we really do believe there should be one and only one rpo backup metric, then this is clearly not a schedule specific setting -- it's a scheduled backup specific setting -- for *all* scheduled backups -- and thus, it's a cluster setting.

I have to disagree on your :thumbsdown:  re opt-in RPO tracking.  I think doing what this PR proposes is the least desirable outcome.  It creates confusing interface that will be hard to explain to end users; it introduces ample opportunity to misconfigure system (by tracking multiple backups -- and thus producing wrong or misleading signal to the end users); and for anything more complex (like CC wanting to keep track of 2 backups for 2 clients), it would still require some external system.



</blockquote></details>

I think another way to frame this is metrics are _per cluster_ and describe a _cluster-wide_ (or node-wide) attribute, e.g. number of jobs the _cluster_ ran, length of disk delays, etc. They're not per-object within that node/cluster. 

What our SREs asked us for is "a metric for the cluster's RPO", so they don't need to keep running backupper -- scheduled backups doesn't benefit them much without it if they still need to run their own daemon  to perform periodic backup-related tasks, i.e. exactly what scheduled backups was meant to replace. A metric is per-cluster and not per-object, but that's OK for our SREs and most operators in the common case, who similarly are just concerned with "I want to backup my cluster and know it is backed up". A single metric doesn't serve operators with less common needs, like "I want to backup dbA here and dbB there and dbC over there" but we've said from the beginning that schedules in general is about optimizing for making the common-case easy to operate, because the weird/complex cases already expect to do more of their own work. 

A metric is the operator/SRE-preferred way to monitor that, and the fact a metric is per-cluster isn't a problem for our SREs when that's all they care about anyway -- when did the _cluster_ last get backed up?

Now, the issue is that we don't know which schedule or schedules qualify as meeting that definition, only the operator who set them up and will be looking at the metric does. 

We could make a cluster setting with the list of schedule IDs that qualify as the cluster RPO and check if a completed schedule ID is in it, but that is basically the same as putting a bit on the schedule but instead by sticking what is basically an unchecked FK in string-y encoding. I don't see this as much better than letting the operator express it via a bit on the schedule itself.

Also, I don't think it is necessarily invalid to have multiple schedules that count as updating the RPO, and indeed, is expected even with the full-plus-inc schedules -- either one completing provides an RP. If you also had a weekly offsite backup or whatever, as long as you deemed it completing sufficient for your RPO SLA, there's no reason you shouldn't be able to flip the bit on it too (since maybe you skip for local SAN backup that day if you're backing up offsite already).

To the confusion point: yes, we're saying "how do I monitor my RPO? you alert on this metric and then flip this bit on the schedule(s) you consider to be your rpo" "okay, cool" .... "how do I monitor the rpo of this db versus that db? you need to run SHOW JOBS FOR SCHEDULE on each and update your metics yourself" and that isn't ideal, but I think it is reasonable within the 0, 1, n rule: the first answer is for 1 RPO, the second is for n.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mwang1026)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MHwjMti8byiaEfGTE2m:b9vs1st) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
To be clear: I'm not saying "1 metric" is wrong.  Just saying that the existing approach 
is not ideal, IMO.  

Regarding:
> We could make a cluster setting with the list of schedule IDs that qualify as the cluster RPO and check if a completed schedule ID is in it, but that is basically the same as putting a bit on the schedule but instead by sticking what is basically an unchecked FK in string-y encoding. I don't see this as much better than letting the operator express it via a bit on the schedule itself.

I do disagree with this from the UX/UI perspective (perhaps @mwang1026 can provide more insight): To me, when I say `CREATE SCHEDULE ... WITH track_rpo` -- that "track_rpo" bit applies to the schedule I'm creating right now.  And because you can create multiple schedules, the fact that `CREATE SCHEDULE` takes this clause implies that this is a schedule specific setting.  Now,of course, we can write docs saying, in effect, that this "track_rpo" bit is not actually per schedule.  And explain things in detail.  However, I am huge fan of interfaces that are easy to use correctly, and are intuitive.  To me, the fact that we need external explainer on that setting makes it suboptimal.  And that's why I think that cluster setting, while not different in what it accomplishes, *IS* different from UI/interface perspective.  We are no longer associating this setting with a schedule -- instead, we are associating schedule ID (or IDs) with the cluster.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mwang1026)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHs20r87PYqZoK4Ujrl:-MHwlNfl7Wu6juCtd0gq:b-2jnbqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/create_scheduled_backup.go#L39)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

record_last_backup_time?
</blockquote></details>

Perhaps a more clear name could be `updates_cluster(wide)_last_backup_time_metric` or something

**Review by mwang1026 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @mwang1026)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHvHks0-OYUR50YX8O4:-MI-WtkS1FZK8lZgFKp0:bnyt3j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/schedule_exec.go#L254)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

To be clear: I'm not saying "1 metric" is wrong.  Just saying that the existing approach 
is not ideal, IMO.  

Regarding:
> We could make a cluster setting with the list of schedule IDs that qualify as the cluster RPO and check if a completed schedule ID is in it, but that is basically the same as putting a bit on the schedule but instead by sticking what is basically an unchecked FK in string-y encoding. I don't see this as much better than letting the operator express it via a bit on the schedule itself.

I do disagree with this from the UX/UI perspective (perhaps @mwang1026 can provide more insight): To me, when I say `CREATE SCHEDULE ... WITH track_rpo` -- that "track_rpo" bit applies to the schedule I'm creating right now.  And because you can create multiple schedules, the fact that `CREATE SCHEDULE` takes this clause implies that this is a schedule specific setting.  Now,of course, we can write docs saying, in effect, that this "track_rpo" bit is not actually per schedule.  And explain things in detail.  However, I am huge fan of interfaces that are easy to use correctly, and are intuitive.  To me, the fact that we need external explainer on that setting makes it suboptimal.  And that's why I think that cluster setting, while not different in what it accomplishes, *IS* different from UI/interface perspective.  We are no longer associating this setting with a schedule -- instead, we are associating schedule ID (or IDs) with the cluster.
</blockquote></details>

Ideal ideal world IMO is you have a API you can hit to check for RPO. I don't remember from the conversation -- was there a reason they preferred a metric vs. say us logging "last successful run" in the Schedules table and they could poll the schedule itself by running SHOW SCHEDULES? Was it that they didn't want to touch/run SQL at all? Would they have been OK if it was some http endpoint?

If we're forced to use a metric, I think customers will have to live with the limitations of one per cluster. Right now, since we only support BACKUP, we should be OK -- it's unlikely there will be two backup schedules (I may be totally wrong here but willing to incur the risk). We were hoping for an API a user could hit but that didn't happen so we're left with using metrics and so have to make do with what we have. Moving forward, I feel like this is even more reason for us to push for / figure out a way to get to a point where there's a better way to monitor and track certain progress against schedules.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-MHs20r87PYqZoK4Ujrl:-MI-iME7D_0vOhq9Ij3U:bm6iz9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c43366948ffdf937def306d81f6cc3a2e4d5c6/pkg/ccl/backupccl/create_scheduled_backup.go#L39)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Perhaps a more clear name could be `updates_cluster(wide)_last_backup_time_metric` or something 
</blockquote></details>

Per discussion -- your suggestion above is a good one.  I'd be okay with taking this option, as long as option name is super explicit (like you have above) in that it says, in effect, "update cluster wide rpo metric when this schedule completes"

**Review by miretskiy — APPROVED** [review]
:lgtm: with updated option name.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54655#-:-MI-isagCZqAJGt8zrrr:b857n1k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

**Pull request merged**
