### PR TITLE
sql/parser: finalize v1 BACKUP & RESTORE grammar

### PR DESCRIPTION
**Pull request by danhhz**
For both BACKUP and RESTORE, allow more fine grained control over the
databases and tables that are selected, support AS OF SYSTEM TIME, and a
generic kv option syntax. For RESTORE, allow specifying multiple restore
bases, for full+incrementals.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12956)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 971 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956#-KaiGOWzVuQVYMzrh941:-KaiGOWzVuQVYMzrh942:bjyaxw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d717108b1c53b3212fe36b7ba684a969cb324429/pkg/sql/parser/sql.y#L971)):*
> ```Yacc
> | /* EMPTY */ {}
> 
> // TODO(dan): Rename privlege_target to reflect its new use when merging upstream.
> ```

"when merging upstream" = now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956)*

**Comment by danhhz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/sql.y, line 971 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956#-KaiGOWzVuQVYMzrh941:-KaiNPF_Lh83fgdShaBH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d717108b1c53b3212fe36b7ba684a969cb324429/pkg/sql/parser/sql.y#L971)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

"when merging upstream" = now?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956#-:-KaiODsgE7svWNIawlK4:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/sql.y, line 108 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956#-KaiPUQ-LC6CYK-bD7P7:-KaiPUQ-LC6CYK-bD7P8:bm3zi49) ([raw file](https://github.com/cockroachdb/cockroach/blob/380fd7374e8c1d6b874d27b8f32a31493c24be15/pkg/sql/parser/sql.y#L108)):*
> ```Yacc
> }
> func (u *sqlSymUnion) strs() []string {
>     if stmt, ok := u.val.([]string); ok {
> ```

@nvanbenschoten do we need to avoid this or is it ok? That is, should the EMPTY branches populate an empty []string instead of an untyped nil?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 108 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956#-KaiPUQ-LC6CYK-bD7P7:-KajQ50N27lipewBzZ8C:b-v1qupi) ([raw file](https://github.com/cockroachdb/cockroach/blob/380fd7374e8c1d6b874d27b8f32a31493c24be15/pkg/sql/parser/sql.y#L108)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

@nvanbenschoten do we need to avoid this or is it ok? That is, should the EMPTY branches populate an empty []string instead of an untyped nil?
</blockquote></details>

Either way would be fine because `[]string` is a concrete type and not an interface, but convention (and the comment at line 73) would favor leaving this as it was and doing what you suggest. We recently refined the cases where checks like these are necessary, but it did result in the rules becoming slightly more complicated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956)*

**Comment by danhhz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 108 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956#-KaiPUQ-LC6CYK-bD7P7:-Kan0IXNRP0xzjpiczM4:b-4gora) ([raw file](https://github.com/cockroachdb/cockroach/blob/380fd7374e8c1d6b874d27b8f32a31493c24be15/pkg/sql/parser/sql.y#L108)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Either way would be fine because `[]string` is a concrete type and not an interface, but convention (and the comment at line 73) would favor leaving this as it was and doing what you suggest. We recently refined the cases where checks like these are necessary, but it did result in the rules becoming slightly more complicated.
</blockquote></details>

Oh, I didn't know we'd standardized this. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956)*

**Comment by knz** [comment]
Nice, I like this.

May I however suggest for future commits / PRs to make the commit message slightly more informative, in particular by including examples of the new accepted syntax.

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12956#-:-Kb5OeuZeTaZpZATzxbV:biyyhya)*

**Pull request merged**
