### PR TITLE
Only push metrics to Graphite if in whitelist

### PR DESCRIPTION
**Pull request by neeral**

### CODE REVIEW

**Review by neeral — COMMENTED** [review]
Please ignore extraneous log messages - I'll remove them shortly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-:-LJtvmDd6O0f3xna1UHU:b-465rr3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by neeral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28587)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/metric/graphite_exporter.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-LJuvQkR8znxyMy3e1nc:-LJuvQkR8znxyMy3e1nd:b-r8f5ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1e1f2b54726894132d53144fddc10895e03a0c/pkg/util/metric/graphite_exporter.go#L93)):*
> ```Go
> 	if names != nil {
> 		for k, family := range ge.pm.families {
> 			if inWhitelist(family) {
> ```

this should be `!inWhitelist(family)`

**Review by mvijaykarthik — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28587)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/node.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-LK0GDAH18XaE3In1DYQ:-LK0GDAH18XaE3In1DYR:b-sp17q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1e1f2b54726894132d53144fddc10895e03a0c/pkg/server/node.go#L114)):*
> ```Go
> 	graphiteWhitelistPath = settings.RegisterStringSetting(
> 		"external.graphite.whitelistpath",
> 		"if nonempty, enable whitelist for which metrics to push based on contents at this path",
> ```

Let's mention that regex is supported and give example format of the file. Like every line is a new metric regex. If any one line matches the metric is white-listed.
___
*[pkg/util/metric/graphite_exporter.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-LK0DAbj1rTR9qFPPdX-:-LK0DAbj1rTR9qFPPdX0:bjcl68h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1e1f2b54726894132d53144fddc10895e03a0c/pkg/util/metric/graphite_exporter.go#L66)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
> 		if f, err := os.Open(whitelistPath); err == nil {
> 			defer f.Close()
>  
> 			scanner := bufio.NewScanner(f)
> 			for scanner.Scan() {
> 				names = append(names, strings.TrimSpace(scanner.Text()))
> 			}
> 			if err = scanner.Err(); err == nil {
> 				log.Errorf(ctx, "neeral reading file %s to give %v of size %d", whitelistPath, names, len(names))
> 			} else {
> 				log.Errorf(ctx, "neeral error reading from file %s: %v", whitelistPath, err)
> 			}
> 		}
> ```
</details>


Shall we create a function for this?
___
*[pkg/util/metric/graphite_exporter.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-LK0GdJWAK4WkczrrlMw:-LK0GdJWAK4WkczrrlMx:b-jeuc5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1e1f2b54726894132d53144fddc10895e03a0c/pkg/util/metric/graphite_exporter.go#L94)):*
> ```Go
> 		for k, family := range ge.pm.families {
> 			if inWhitelist(family) {
> 				delete(ge.pm.families, k)
> ```

This can cause side effects to `pm` externally since it's a pointer We could either
1. Document this side effect
2. Create a deep copy
3. Create and use a local `pm`

**Review by neeral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28587)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/node.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-LK0GDAH18XaE3In1DYQ:-LK2fRhkDCp81vrsCfhJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1e1f2b54726894132d53144fddc10895e03a0c/pkg/server/node.go#L114)):*
<details><summary><i>Previously, vijaykarthik-rubrik wrote…</i></summary><blockquote>

Let's mention that regex is supported and give example format of the file. Like every line is a new metric regex. If any one line matches the metric is white-listed.
</blockquote></details>

Done.
___
*[pkg/util/metric/graphite_exporter.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-LK0DAbj1rTR9qFPPdX-:-LK2gkw01gwe8fV-pFjW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1e1f2b54726894132d53144fddc10895e03a0c/pkg/util/metric/graphite_exporter.go#L66)):*
<details><summary><i>Previously, vijaykarthik-rubrik wrote…</i></summary><blockquote>

> ```
> 		if f, err := os.Open(whitelistPath); err == nil {
> 			defer f.Close()
>  
> 			scanner := bufio.NewScanner(f)
> 			for scanner.Scan() {
> 				names = append(names, strings.TrimSpace(scanner.Text()))
> 			}
> 			if err = scanner.Err(); err == nil {
> 				log.Errorf(ctx, "neeral reading file %s to give %v of size %d", whitelistPath, names, len(names))
> 			} else {
> 				log.Errorf(ctx, "neeral error reading from file %s: %v", whitelistPath, err)
> 			}
> 		}
> ```

Shall we create a function for this?

</blockquote></details>

Done.
___
*[pkg/util/metric/graphite_exporter.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28587#-LK0GdJWAK4WkczrrlMw:-LK2gnbY8zqWR-RGBkN5:b-9i3pe9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1e1f2b54726894132d53144fddc10895e03a0c/pkg/util/metric/graphite_exporter.go#L94)):*
<details><summary><i>Previously, vijaykarthik-rubrik wrote…</i></summary><blockquote>

This can cause side effects to `pm` externally since it's a pointer We could either
1. Document this side effect
2. Create a deep copy
3. Create and use a local `pm`
</blockquote></details>

The graphite exporter uses its own instance of a `pm`. This is part of its design.

**Pull request closed without merging**
