### PR TITLE
randutil: adds NewTestRand to provide more deterministic random number generation

### PR DESCRIPTION
**Pull request by rharding6373**
This PR adds NewTestRand, a random number generator seeded by a random number 
taken from the global rand. This provides more determinism for a test than the existing
NewPseudoRand by using a seed that is reproducible, provided the test has no other
sources of non-determinism.

As part of this PR we also migrate test use cases of NewPseudoRand and all uses of
NewTestPseudoRand to NewTestRand.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Why is `NewTestPseudoRand` not sufficient?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-:-MlWplBL7r-kahYP598x:b-gwp0e2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rharding6373, and @shermanCRL)

___
*[pkg/util/randutil/rand.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlWqYYM1PhDzWxGd5tl:-MlWqYYM1PhDzWxGd5tm:b-n6huw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f55138faf398251971d5e93e681ac43512ccf87/pkg/util/randutil/rand.go#L62)):*
> ```Go
> // rand. This rand.Rand is useful in testing for deterministic behavior.
> func NewTestRand() (*rand.Rand, int64) {
> 	seed := rand.Int63()
> ```

What's the logic behind using the global rand? Even if the global rand is deterministically seeded (via `SeedForTests()`), the seed we get here will depend on how many times the global rand was used (which would depend on which tests in that package ran before). It would be impossible to reproduce a single test if the failure occurred when the entire package was tested.

**Review by rharding6373 — COMMENTED** [review]
There is discussion about the motivation behind this and various options in this thread: https://cockroachlabs.slack.com/archives/C0HM2DZ34/p1632944127270600

`NewTestPseudoRand` relies on `NewPseudoRand` which gets its seed from `crypto_rand.Reader`, which doesn't have deterministic behavior across test runs. `NewTestPseudoRand` logs the seed it uses, but many tests create multiple RNGs, as well as using the global `rand` with its own seed, so it's not useful in producing deterministic randomized tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-:-MlWspBY0k6CsEKXhXOy:bjue488)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RaduBerinde, and @shermanCRL)

___
*[pkg/util/randutil/rand.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlWqYYM1PhDzWxGd5tl:-MlWtyaf8Gh2yC8aZY0l:b7ucg50) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f55138faf398251971d5e93e681ac43512ccf87/pkg/util/randutil/rand.go#L62)):*
The rationale behind using the global rand is that a test could be reproduced using a single seed: the one seeding global rand. It allows RNGs in the same test to have different seeds.

>It would be impossible to reproduce a single test if the failure occurred when the entire package was tested.

That's definitely a downside to this, and I'm open to suggestions to make it better! (e.g., being disciplined about one RNG per test could be helpful, but doesn't help in the cases where a test has to use multiple RNGs or the test also relies on global rand). This change doesn't solve the deterministic test problem for all situations, but provides the possibility of easily reproducing test conditions that wasn't possible before this change.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rharding6373, and @shermanCRL)

___
*[pkg/util/randutil/rand.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlWqYYM1PhDzWxGd5tl:-MlWzo-M3uXHC4B2xCNu:b-56bnpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f55138faf398251971d5e93e681ac43512ccf87/pkg/util/randutil/rand.go#L62)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

The rationale behind using the global rand is that a test could be reproduced using a single seed: the one seeding global rand. It allows RNGs in the same test to have different seeds.

>It would be impossible to reproduce a single test if the failure occurred when the entire package was tested.

That's definitely a downside to this, and I'm open to suggestions to make it better! (e.g., being disciplined about one RNG per test could be helpful, but doesn't help in the cases where a test has to use multiple RNGs or the test also relies on global rand). This change doesn't solve the deterministic test problem for all situations, but provides the possibility of easily reproducing test conditions that wasn't possible before this change.
</blockquote></details>

I see.. How about setting up a separate, internal`*rand.Rand` instance that is only used for generating the seeds for `NewTestRand()`? That way at least it won't matter if tests use the global rand.

We could add a function that you can call at the beginning of your test and it reports the current state of this rand instance, with a way to set it to be the same in the future if you want to repro just that one test. We could even do this automatically in `NewTestRand` - we can inspect the stack (`runtime.Callers`) to find the test name and print it out the first time we see a test.

One question is if it's worth having both this and `NewTestPseudoRand()`. I didn't even know there were two variants, I just used whatever I saw in use elsewhere.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @RaduBerinde)

___
*[pkg/util/randutil/rand.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlWqYYM1PhDzWxGd5tl:-MllKPOmDjeUW6gf5t2_:b-76fwoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f55138faf398251971d5e93e681ac43512ccf87/pkg/util/randutil/rand.go#L62)):*
These are interesting ideas. I changed the implementation to try to improve reproducibility at the individual test level, incorporating these ideas. The seeds for `NewTestRand` are produced by an RNG that is reseeded using the global seed every time a new test is detected. We use a global seed because in some packages an RNG is used in TestMain as well as the actual test, and it also means we only need to apply one seed with `COCKROACH_RANDOM_SEED`.

This approach has some limitations: 1) Tests that use `t.Parallel()` won't be deterministic (this only appears to affect TestFastIntSet and TestFastIntMap; otherwise, `t.Parallel()` is not commonly used in the code base). 2) RNGs are reset at the test function level, so if a test function has multiple tests in it (e.g., TestDefaultAggregateFunc/hash/StringAgg vs TestDefaultAggregateFunc/ordered/StringAgg), running an individual test with the same seed as the entire test or at the package level may not produce the same results.

> One question is if it's worth having both this and NewTestPseudoRand()

I had removed this in a separate commit in the same PR, but decided to squash the commits so it's easier to see all the changes together.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-:-MlmVyE6AS-Tksb5PSx1:b-qyabs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @knz, and @rharding6373)

___
*[pkg/util/randutil/rand.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlWqYYM1PhDzWxGd5tl:-MlmUkiG9nlP7v5ODb6b:b-wiyacy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f55138faf398251971d5e93e681ac43512ccf87/pkg/util/randutil/rand.go#L62)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

These are interesting ideas. I changed the implementation to try to improve reproducibility at the individual test level, incorporating these ideas. The seeds for `NewTestRand` are produced by an RNG that is reseeded using the global seed every time a new test is detected. We use a global seed because in some packages an RNG is used in TestMain as well as the actual test, and it also means we only need to apply one seed with `COCKROACH_RANDOM_SEED`.

This approach has some limitations: 1) Tests that use `t.Parallel()` won't be deterministic (this only appears to affect TestFastIntSet and TestFastIntMap; otherwise, `t.Parallel()` is not commonly used in the code base). 2) RNGs are reset at the test function level, so if a test function has multiple tests in it (e.g., TestDefaultAggregateFunc/hash/StringAgg vs TestDefaultAggregateFunc/ordered/StringAgg), running an individual test with the same seed as the entire test or at the package level may not produce the same results.

> One question is if it's worth having both this and NewTestPseudoRand()

I had removed this in a separate commit in the same PR, but decided to squash the commits so it's easier to see all the changes together.
</blockquote></details>

Very cool!!
___
*[pkg/util/randutil/rand.go, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlmULP50tVX8eZpciRE:-MlmULP50tVX8eZpciRF:bbj7etz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9b581d43a4d6f07bd7766ff108a0799d25158a/pkg/util/randutil/rand.go#L69)):*
> ```Go
> func NewTestRand() (*rand.Rand, int64) {
> 	fxn := getTestName()
> 	if fxn != "" && lastTestName != fxn {
> ```

This is racy, rng and lastTestName need to be protected by a mutex. (I realize that if called concurrently, any hope of determinisim goes out of the window anyway, but the race detector will complain)

**Review by srosenberg — COMMENTED** [review]
> NewTestPseudoRand
`NewTestPseudoRand` should be synchronized as per Radu's comment; otherwise, great work!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-:-MlrDnszBabtsKAnc5Mz:b-72mk1h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @knz, and @rharding6373)

**Review by srosenberg — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 115 of 117 files at r2, 7 of 8 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @knz, and @rharding6373)

**Review by rharding6373 — COMMENTED** [review]
TFTRs! I'll wait until Monday to merge in case there's any other feedback.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-:-MlvotT1EQ00cj6GhRkV:bqmumxn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @knz, @rharding6373, and @srosenberg)

___
*[pkg/util/randutil/rand.go, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlmULP50tVX8eZpciRE:-MlvorMbDCtSjbezD1Iu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9b581d43a4d6f07bd7766ff108a0799d25158a/pkg/util/randutil/rand.go#L69)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is racy, rng and lastTestName need to be protected by a mutex. (I realize that if called concurrently, any hope of determinisim goes out of the window anyway, but the race detector will complain)
</blockquote></details>

Done.

**Review by srosenberg — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @knz, and @rharding6373)

___
*[pkg/util/randutil/rand.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-Mlw8S2t1ksPz4vxo-ae:-Mlw8S2t1ksPz4vxo-af:b-7ovy2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/16dc8cfc93dd36a838a79ff887434c55249b8b60/pkg/util/randutil/rand.go#L43)):*
`init` is never racy, and its execution happens-before any other (non-init) function in the same package [1],

> Package initialization—variable initialization and the invocation of init functions—happens in a single goroutine, sequentially, one package at a time. An init function may launch other goroutines, which can run concurrently with the initialization code. However, initialization always sequences the init functions: it will not invoke the next one until the previous one has returned.

Thus, mutex is never needed inside `init`.

[1] https://golang.org/ref/spec#Package_initialization
___
*[pkg/util/randutil/rand.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-MlwDup70ef-rP1xdNnT:-MlwDup70ef-rP1xdNnU:b-k4k672) ([raw file](https://github.com/cockroachdb/cockroach/blob/16dc8cfc93dd36a838a79ff887434c55249b8b60/pkg/util/randutil/rand.go#L74)):*
> ```Go
> // reproducible behavior.
> func NewTestRand() (*rand.Rand, int64) {
> 	mtx.Lock()
> ```

Yep. Theoretically, this yields a _partial_ order on the sequence of seeds.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71350)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @knz, @rharding6373, and @srosenberg)

___
*[pkg/util/randutil/rand.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71350#-Mlw8S2t1ksPz4vxo-ae:-Mm-KcsRDngK8lAGhBCh:b-i2uez6) ([raw file](https://github.com/cockroachdb/cockroach/blob/16dc8cfc93dd36a838a79ff887434c55249b8b60/pkg/util/randutil/rand.go#L43)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`init` is never racy, and its execution happens-before any other (non-init) function in the same package [1],

> Package initialization—variable initialization and the invocation of init functions—happens in a single goroutine, sequentially, one package at a time. An init function may launch other goroutines, which can run concurrently with the initialization code. However, initialization always sequences the init functions: it will not invoke the next one until the previous one has returned.

Thus, mutex is never needed inside `init`.

[1] https://golang.org/ref/spec#Package_initialization
</blockquote></details>

Thanks for the reference!

**Pull request merged**
