### PR TITLE
logconfig: support YAML arrays to configure channels

### LINKED ISSUE #58958: logs: support YAML arrays in channel selection for log configuration
When configuring logs using the new `--log=` flag, we need to pass a list of channels as a string when configuring a file group sink:

```
sinks:
 file-groups:
   security:
     channels: "SESSIONS, USER_ADMIN, PRIVILEGES, SENSITIVE_ACCESS"
```

It would be nice to support an array in the YAML itself:
```
sinks:
 file-groups:
   health:
     channels:
       - HEALTH
       - OPS
```
or

```
sinks:
 file-groups:
   health:
     channels: [HEALTH, OPS]
```

cc @thtruo

### PR DESCRIPTION
**Pull request by knz**
Requested by @piyush-singh during QA to limit UX surprise.
Fixes #58958. 

Release note (cli change): the `channels` parameter for
the log sink configurations now supports a more flexible
input configuration format:

- syntax to include specific channels:
  - `channels: dev,sessions`  (yaml string)
  - `channels: 'dev,sessions'` (yaml string, equivalent to previous)
  - `channels: [dev,sessions]` (yaml array, can use multi-line syntax with hyphens too)
  - `channels: ['dev','sessions']` (same as previous)
  - `channels: '[dev,sessions]'` (bracket-enclosed list inside yaml string)

- syntax to include all channels:
  - `channels: all` (yaml string)
  - `channels: 'all'` (same as previous)
  - `channels: [all]` (yaml array)
  - `channels: ['all']` (same as previous)
  - `channels: '[all]'` (bracket-enclosed "all" inside yaml string)

- syntax to include all channels except some:
  - `channels: all except dev,sessions` (yaml string)
  - `channels: 'all except dev,sessions'`  (same as previous, quoted string)
  - `channels: 'all except [dev,sessions]'` (same as previous, list is bracket enclosed)

This makes it possible to e.g. do:

```
sinks:
  stderr:
    channels:
    - DEV
    - SQL_SESSIONS
```

which uses the "native" YAML syntax for lists.

### CODE REVIEW

**Comment by knz** [comment]
(Also added a section to explain this in #59083)

**Comment by knz** [comment]
rebased this, RFAL

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59352#-:-MS3pmPj4LT1hBsNkXPA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/testdata/logflags, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59352#-MS3s8mCD5soS1gFJggt:-MS3s8mCD5soS1gFJggu:b-hxh5zy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2989bd44511ceb634d99828ec6de48711f890c9/pkg/cli/testdata/logflags#L17)):*
> ```
> config: {<stdFileDefaults(<defaultLogDir>)>,
> sinks: {file-groups: {default: <fileCfg([DEV,
> OPS,
> ```

Nit: The line breaks here seem a bit excessive and seem to break the pattern, right? I imagine it's due to the `,flow` added to the struct field definition. Not a big point so feel free to ignore it, but maybe we could just remove it if it isn't necessary.

**Review by knz — COMMENTED** [review]
TFYR!

bors r=itsbilal

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59352#-:-MSCzy-8E3K7bIqfvzZp:b-71bxos)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/cli/testdata/logflags, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59352#-MS3s8mCD5soS1gFJggt:-MSCzmf07oNJ5Q9wbKI-:b520xna) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2989bd44511ceb634d99828ec6de48711f890c9/pkg/cli/testdata/logflags#L17)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nit: The line breaks here seem a bit excessive and seem to break the pattern, right? I imagine it's due to the `,flow` added to the struct field definition. Not a big point so feel free to ignore it, but maybe we could just remove it if it isn't necessary.
</blockquote></details>

Alas, the go regexp library does not offer us primitives rich enough to both substitute this and remove the extraneous newlines. The best way I found makes the test significantly harder to understand and maintain, and I didn't like where that brings us in the trade-off. So I'm going to keep it as is.

**Pull request merged**
