### PR TITLE
sql: make DROP TABLE be a schema change

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6336)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Will look at this later tonight

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/drop.go, line 64 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKeS0B6BzvP9GPodqf:-KGKeS0CbjK2xdvjUJlN:319369472) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/drop.go#L64)):*
for _, tbName := range tbNames {

and use tbName

---

*[sql/drop.go, line 218 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKeqk4DkeFoRMhdMkv:-KGKeqk4DkeFoRMhdMkw:335829395) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/drop.go#L218)):*
and no existing leases are in use.

---

*[sql/drop.go, line 273 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKfZWQnn4qLOtloHHa:-KGKfZWQnn4qLOtloHHb:-254654364) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/drop.go#L273)):*
I think it will be neater to split this into two transactions: one for the truncation and the other for the deletion.

---

*[sql/lease.go, line 591 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKgwpXjVH0FO5OWcVH:-KGKgwpXjVH0FO5OWcVI:-361200691) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/lease.go#L591)):*
I'm not too keen on this change because I much prefer the gossip mechanism being solely a method to notify that the descriptor has changed. The actual change on the descriptor should be read from the kv store. I think this change is okay but it breaks that principle.

---

*[sql/lease_test.go, line 421 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKhw9HzGOWJMS2_vBS:-KGKhw9HzGOWJMS2_vBT:776632711) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/lease_test.go#L421)):*
this is actually a problem and we should create an issue for it. I'd prefer we not resolve it in this PR.

---

*[sql/schema_changer.go, line 168 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKj80LMNDb_AQnC6we:-KGKj80LMNDb_AQnC6wf:1541804664) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/schema_changer.go#L168)):*
perhaps we should not do this and instead ignore the DescriptorDeletedError returned from ReleaseLease below.

---

*[sql/schema_changer.go, line 184 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKjdrXFc45RNV2wylY:-KGKjdrXFc45RNV2wylZ:1584301933) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/schema_changer.go#L184)):*
how about extending the lease before waiting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-:-KGKkhLmo55uPpQsTqyF:1417088721)*

**Comment by andreimatei** [comment]
Review status: 0 of 16 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/drop.go, line 64 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKeS0B6BzvP9GPodqf:-KGNgVbN6S3284F_01oM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/drop.go#L64)):*
Done.

---

*[sql/drop.go, line 218 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKeqk4DkeFoRMhdMkv:-KGNgmevmY3itbv1u0xp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/drop.go#L218)):*
Done.

---

*[sql/drop.go, line 273 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKfZWQnn4qLOtloHHa:-KGNh7lfhvBTjZS35qV8:-358327931) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/drop.go#L273)):*
It's convenient for that `truncateTable` function to take a txn (it's got another caller) and so I'd be more code to split in two transactions here with no benefit. In fact we get some benefit this way - if we fail to delete the descriptor somehow, we also didn't truncate. Seems good...

---

*[sql/schema_changer.go, line 168 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKj80LMNDb_AQnC6we:-KGNnma5OkYEMF3ibf9J:-1482353655) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/schema_changer.go#L168)):*
meh, I think it's clean this way

---

*[sql/schema_changer.go, line 184 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKjdrXFc45RNV2wylY:-KGNoPkSL2_xr7kHVVoN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/schema_changer.go#L184)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 16 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/drop.go, line 273 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336#-KGKfZWQnn4qLOtloHHa:-KGNxjX5Yi-MiO-LaAgB:5174689) ([raw file](https://github.com/cockroachdb/cockroach/blob/293ee1e049e4661b44e83e9bae1aad86ca1b8756/sql/drop.go#L273)):*
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6336)*

**Pull request merged**
