### PR TITLE
opt: compact scalar expressions in test output

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding a formatting flag that converts fully scalar subtrees into SQL
expressions and prints the entire expression as a single node.

Because this code uses the execbuilder, it lives in the testutils
package (and we call into it through a formatting interceptor
callback).

Release note: None

### CODE REVIEW

**Comment by justinj** [comment]
:lgtm:, I might be tempted to invert it (`ExpandScalars?`), since it seems way more pleasant to read?

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LD8U62L8HkXMTQEaQ41:b-7jjsiy)*

**Comment by RaduBerinde** [comment]
TFTR! I didn't do that because all the flags are for hiding stuff (0 means we show everything).

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LD8UsXE8fAzIIVSZWBZ:b-kyimhl)*

**Comment by andy-kimball** [comment]
:lgtm:, with some additional formatting suggestions we might try.

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/norm/testdata/props/prune_cols, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-LD8frTJ8ErWuhl_6ECp:-LD8frTJ8ErWuhl_6ECq:b3stzb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d522b542fd28c189f694515f68e30c992a40a1/pkg/sql/opt/norm/testdata/props/prune_cols#L46)):*
> ```
>  │    ├── keys: (1)
>  │    └── prune: (1-4)
>  └── {(a.k = 1) AND (a.f = 1.0)} [type=bool, outer=(1,3), constraints=(/1: [/1 - /1]; /3: [/1.0 - /1.0]; tight)]
> ```

Braces look OK, but maybe try `[ ` (with a space after the bracket). Or maybe just a space after the brace. I think that a bit of extra whitespace might make the expressions "pop" a bit more, making them easier for the eye to pick out.

Another idea that occurs to me is something like this, which fits with our formatting elsewhere:
```
└── filter: (a.k = 1) AND (a.f = 1.0)  [type=bool, outer=(1,3), constraints=(/1: [/1 - /1]; /3: [/1.0 - /1.0]; tight)]
```
The idea would be to print the name of the field, followed by a colon.

---

*[pkg/sql/opt/norm/testdata/rules/comp, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-LD8fOpABl61MGPOUrjC:-LD8fOpABl61MGPOUrjD:b4jh1js) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d522b542fd28c189f694515f68e30c992a40a1/pkg/sql/opt/norm/testdata/rules/comp#L222)):*
> ```
>  │    └── {()} [type=tuple{}]
>  └── projections
>       └── {true} [type=bool]
> ```

I think we should special case some simple expressions like constants (true, false, const, null, etc), and maybe empty tuple as well (for emptyrow case).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LD8iGO7-FT6FDjr0BcM:by84mo4)*

**Comment by rytaft** [comment]
:lgtm: Very nice - this makes the test output much more compact and generally easier to read!

The only downside to this change is that some of the long scalar expressions are now a bit hard to read. Is it possible to add some line breaks? One idea might be to keep the `filters` node and have all the conjuncts as child scalar expressions. (But feel free to ignore this if you disagree or the change is too onerous...)

super nit: I'm not totally convinced that curly braces are a good choice for enclosing scalar expressions, since it makes it look like the expression is part of a json or something. Why not just print the bare expression?

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/norm/testdata/rules/combo, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-LD8c1F_0nT3VlrGoEzo:-LD8c1F_0nT3VlrGoEzp:bkozov1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d522b542fd28c189f694515f68e30c992a40a1/pkg/sql/opt/norm/testdata/rules/combo#L72)):*
> ```
>   +      └── {(a.k = xy.x) AND (a.i = (10 - 1))} [type=bool, outer=(1,2,6), constraints=(/1: (/NULL - ]; /2: (/NULL - ]; /6: (/NULL - ])]
> --------------------------------------------------------------------------------
> SimplifyFilters (no changes)
> ```

Why is this changing the application of different rules? Shouldn't this change only affect the formatting?

---

*[pkg/sql/opt/norm/testdata/rules/comp, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-LD8d5u7-nuUgLEQ-z_U:-LD8d5u7-nuUgLEQ-z_V:b2r3uzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d522b542fd28c189f694515f68e30c992a40a1/pkg/sql/opt/norm/testdata/rules/comp#L63)):*
> ```
>  │    ├── columns: k:1(int!null) i:2(int) f:3(float) s:4(string) j:5(jsonb)
>  │    └── keys: (1)
>  └── {((((a.i = (2 - 1)) AND ((a.f + a.f) < (5.0 - 2.0))) AND (a.i <= (length('foo') - 1))) AND (a.i > ((10 - 2) - 2))) AND (a.i::INTERVAL >= ('02:00:00' - '01:00:00'))} [type=bool, outer=(2,3), constraints=(/2: (/NULL - ])]
> ```

Is it possible to add some line breaks to this expression?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LD8cZrz7w-LtyNfyJVt:b76yb6b)*

**Comment by andy-kimball** [comment]
The problem with no delimiters at all is that some expressions look really strange, like just `x`, or just `1`. I made a couple other suggestions below to see if we can find something else. But probably all possibilities will have flaws.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LD8wH7ZAgNwW-Icou5X:b-2nw4pc)*

**Comment by RaduBerinde** [comment]
I blacklisted more ops, including Filters. Now we print the filters node and each filter separately. I think this fixes the problem with huge filter expressions.

I tried the `[ .. ]` delimiter. I am not sure we still need the delimiter given the other changes.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/norm/testdata/rules/combo, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-LD8c1F_0nT3VlrGoEzo:-LD8jjko2_BbZdDgaTd3:b-7atsc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d522b542fd28c189f694515f68e30c992a40a1/pkg/sql/opt/norm/testdata/rules/combo#L72)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is this changing the application of different rules? Shouldn't this change only affect the formatting?
</blockquote></details>

It isn't, it's the same sequence of rules, the output just isn't changing anymore (notice that before the only difference was in the internal structure of the filters expr)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LD92YA721myfJM3S6Jd:b-pgedaf)*

**Comment by andy-kimball** [comment]
Yeah, looking at the latest output, I think you can do away with the delimiters. I think special-casing the simple operators was the key thing. More complex expressions don't really need delimiters, since they tend to pop out on their own.

---

Review status: 7 of 32 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LD9BQU26FEiD0tXQ2r7:bb0xvt7)*

**Comment by RaduBerinde** [comment]
Thanks, removed the delimiters and rebased.

**Comment by RaduBerinde** [comment]
@andy-kimball let me know if the current version is ok to merge. Thanks!

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25744#-:-LDCbPBD6wPOv8Z9IVlo:bnfp4nl)*

**Comment by andy-kimball** [comment]
Yes, looks good.

**Pull request merged**
