### PR TITLE
lease: fix lease retention bug for tables taken offline

### LINKED ISSUE #57834: lease: leases are not retained after IMPORT INTO
**Describe the problem**

IMPORT INTO takes a table offline. When the lease manager notices that a table is offline, it marks the table as dropped. When the table comes back online the table, the dropped annotation is never removed. This leads to the lease always being dropped upon dereferencing.

**To Reproduce**

Run `IMPORT INTO` on a table and then try to interact with it. With vmodule logging you can see that the lease will get released upon dereference.

**Expected behavior**

Leases would be retained once the table is back online.

**Additional context**

Restarting the nodes after the `IMPORT INTO` will resolve the problem as the invalid state is just in memory.

### PR DESCRIPTION
**Pull request by postamar**
Tables can temporarily be taken offline, either permanently or
temporarily. For example, executing a DROP TABLE statement will take
a table offline permanently, and an IMPORT INTO will take a table
offline only for the duration of the import and will bring it online
again afterward.

Previously, the lease manager would not distinguish between those two
cases and would behave as if the table was gone forever. As a result any
lease acquired after the table came back online would always be dropped
upon dereferencing. Although this behavior is valid, it is inefficient,
hence this patch.

Fixes #57834.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
@ajwerner I'm thinking there has to be a better way to test this. I figure, by manipulating the descriptors themselves and `Publish`ing them via the lease manager? I haven't found out how to do this. I'm not too keen on running IMPORT INTO statements which require a CCL binary and in turn require the test to live here; we're not really testing that IMPORT INTO works as it should, we're testing the lease manager, really.

**Review by ajwerner — COMMENTED** [review]
> I figure, by manipulating the descriptors themselves and Publishing them via the lease manager? I haven't found out how to do this

That seems right. You'll probably want to do it from an `lease_test` test file. See `descs.Txn`. Here's an example of it being used https://github.com/cockroachdb/cockroach/blob/aa4c9706f324c1fcc10937e9514ae08a72e729ff/pkg/sql/temporary_schema_test.go#L93-L99. The idea is that you'll resolve the mutable table and then modify it to be offline and write it (using `descriptors.WriteDesc`). Then, I suspect, do it again to put it back online. Then read from the table. Then introspect the leases (the lease manager has a thing for that), and make sure that there's a lease for the table. Should be pretty clean.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59375#-:-MRu3g6kA5-mLtv9k2xR:b-rdw6ob)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by postamar** [comment]
I suspect my test is racy but I can't figure out how. The fact that it fails here https://github.com/cockroachdb/cockroach/pull/59375/commits/da43863d3505fd116ead2f83bb3bd8951acee8b9#diff-71454f0880aa77dc0913414bed74e3ce5fec6de5977dbda2556b2eb567651ca2R2475 because it acquired the lease twice at that point is particularly baffling. Any ideas?

**Comment by postamar** [comment]
It took a few tries but I believe I now have a test which is both meaningful and robust enough. Phew.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59375)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/catalog/lease/lease.go, line 867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59375#-MRw_TvV8atGJmtzOQDs:-MRw_TvV8atGJmtzOQDt:bmi6snd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a060650bb6849070fc2d174b228b2e7d098be940/pkg/sql/catalog/lease/lease.go#L867)):*
> ```Go
> 		t := m.findDescriptorState(id, false /* create */)
> 		t.mu.Lock()
> 		t.mu.takenOffline = false
> ```

Should this instead be based on the state of the descriptor? Namely if it goes from offline to dropped, it seems like this would flip it to not being offline. It seems like takenOffline could be something like `!desc.Public()`

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59375)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/lease/lease.go, line 867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59375#-MRw_TvV8atGJmtzOQDs:-MRzOAYW89CmK5ROikiy:b-g5ej8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a060650bb6849070fc2d174b228b2e7d098be940/pkg/sql/catalog/lease/lease.go#L867)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Should this instead be based on the state of the descriptor? Namely if it goes from offline to dropped, it seems like this would flip it to not being offline. It seems like takenOffline could be something like `!desc.Public()`
</blockquote></details>

I'd thought about this a bit. I'm assuming (perhaps incorrectly!) that once a table is dropped we're not going to be re-acquiring a lease on it anyway (unless perhaps in some edge cases that don't matter much) so this would work pretty neatly. Please correct me if I'm wrong.

**Review by ajwerner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59375)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/catalog/lease/lease.go, line 867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59375#-MRw_TvV8atGJmtzOQDs:-MRzxBk36aD_szR2eLq5:b-qip3yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a060650bb6849070fc2d174b228b2e7d098be940/pkg/sql/catalog/lease/lease.go#L867)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'd thought about this a bit. I'm assuming (perhaps incorrectly!) that once a table is dropped we're not going to be re-acquiring a lease on it anyway (unless perhaps in some edge cases that don't matter much) so this would work pretty neatly. Please correct me if I'm wrong.
</blockquote></details>

Hmm, okay, I'm on board. This probably deserves a comment.

**Review by postamar — COMMENTED** [review]
bors r+

Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59375#-:-MS3tDlS1lulnT1eqfHu:b-gcwg9a)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/catalog/lease/lease.go, line 867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59375#-MRw_TvV8atGJmtzOQDs:-MS3t32_5bIbzI_atfPS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a060650bb6849070fc2d174b228b2e7d098be940/pkg/sql/catalog/lease/lease.go#L867)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Hmm, okay, I'm on board. This probably deserves a comment. 
</blockquote></details>

Done.

**Pull request merged**
