### PR TITLE
sqlccl: support fastpath primary index repartitionings

### PR DESCRIPTION
**Pull request by danhhz**
This adds the new ALTER TABLE PARTITION BY ... synxtax. PARTITION BY NOTHING is added to allow for removal of a partitioning. Secondary index repartitionings, non-fastpath repartitionings, and triggering zone config cleanups are all left for followup work.

The experimental sql interface for zone configs is also changed because of some parser conflicts

### CODE REVIEW

**Comment by benesch** [comment]
I actually quite like this new `ALTER PARTITION` syntax.

:lgtm_strong: 

---

Reviewed 4 of 4 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/partition_test.go, line 171 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rIsRaHu7MBacXqXw0:-L-rIsRaHu7MBacXqXw1:b-jlrcqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/ccl/sqlccl/partition_test.go#L171)):*
> ```Go
> 				// ALTER TABLE/PARTITION/EXPERIMENTAL CONFIGURE ZONE.
> 				fmt.Fprintf(&zoneConfigStmts,
> 					`ALTER PARTITION %s OF TABLE data.%s EXPERIMENTAL CONFIGURE ZONE 'constraints: [%s]';`,
> ```

This probably belonged in the last commit, but don't waste time fixing it.

---

*[pkg/ccl/sqlccl/partition_test.go, line 734 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rN4gI7da6r5uWtB0w:-L-rN4gI7da6r5uWtB0x:b-tffhr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb2c78108fdab89bfe45b58bf20d2784b8623d8/pkg/ccl/sqlccl/partition_test.go#L734)):*
> ```Go
> 		old, new   string
> 		isFastPath bool
> 	}{
> ```

omg reviewable is generating such a garbage diff 

---

*[pkg/ccl/sqlccl/partition_test.go, line 1033 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rNjwTUt1domwE7UDi:-L-rNjwTUt1domwE7UDj:b-f1i5mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/ccl/sqlccl/partition_test.go#L1033)):*
> ```Go
> 				// overwrite any with the same name and the repartitioning
> 				// removes any for partitions that no longer exists, but there
> 				// could still be some sitting around. This in intentional.
> ```

"This in"

---

*[pkg/sql/alter_table.go, line 449 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rNxQHccrrCl41cLsG:-L-rNxQHccrrCl41cLsH:b-pc367q) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/alter_table.go#L449)):*
> ```Go
> 			}
> 			descriptorChanged = !proto.Equal(
> 				&previousTableDesc.PrimaryIndex.Partitioning,
> ```

totally optional nit: probably a bit more efficient to only copy the old partitioning descriptor instead of the whole table desc. Feel free to ignore.

---

*[pkg/sql/alter_table.go, line 465 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJlKhYSYBqaS8o7I0:-L-rJlKhYSYBqaS8o7I1:b-i5h41q) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/alter_table.go#L465)):*
> ```Go
> 				// TODO(dan): Remove zone configs which no longer point at a
> 				// partition. This also needs to be done for indexes.
> 			}
> ```

My goodness this is simple! Nice!

---

*[pkg/sql/create_table.go, line 883 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJgHskKH_93qyJD-F:-L-rJgHtoYodoCo0MTxT:b-cgjgni) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/create_table.go#L883)):*
> ```Go
> 	// logic for this is simple, but I'm intentionally leaving it unimplemented
> 	// until there is a test for it.
> 	return false, errors.New("repartitioning in a non-ccl binary is currently unimplimented")
> ```

"unimplimented"

---

*[pkg/sql/parser/sql.y, line 3069 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJGjAe6N9ApoJZt08:-L-rJGjAe6N9ApoJZt09:blfoh47) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/parser/sql.y#L3069)):*
> ```Yacc
>   {
>     $$.val = (*tree.PartitionBy)(nil)
>   }
> ```

If we stick with `PARTITION BY NOTHING` instead of `REMOVE PARTITIONING`, I think I'd prefer for the syntax to be folded into the `partition_by` nonterminal so that `CREATE TABLE ... PARTITION BY NOTHING` is valid (but noisy) syntax.

---

*[pkg/sql/sem/tree/alter_table.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJ5Ihyf2VHYOKgjVo:-L-rJ5Ihyf2VHYOKgjVp:b-mx0dlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb2c78108fdab89bfe45b58bf20d2784b8623d8/pkg/sql/sem/tree/alter_table.go#L36)):*
> ```Go
> 	}
> 	FormatNode(buf, f, &node.Table)
> 	buf.WriteByte(' ')
> ```

Won't this break formatting in other cases? I'm very confused how the tests are passing with this! (Or how they were passing before.) What am I misunderstanding?

---

*[pkg/sql/sem/tree/create.go, line 744 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rIXKBvVKuE8fNukV0:-L-rIXKBvVKuE8fNukV1:bx4frrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/sem/tree/create.go#L744)):*
> ```Go
> func (node *PartitionBy) Format(buf *bytes.Buffer, f FmtFlags) {
> 	if node == nil {
> 		buf.WriteString(` PARTITION BY NOTHING`)
> ```

I'm not convinced that we shouldn't use `REMOVE PARTITIONING` for "consistency" with Oracle/MySQL, but don't hold up this PR. We can bikeshed that later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-:-L-rILaSfDbSPc-ZdakX:b-1y0g37)*

**Comment by danhhz** [comment]
Review status: 2 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ccl/sqlccl/partition_test.go, line 1033 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rNjwTUt1domwE7UDi:-L-s-UsKiG5lGUhYgRNk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/ccl/sqlccl/partition_test.go#L1033)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"This in"
</blockquote></details>

Done.

---

*[pkg/sql/alter_table.go, line 449 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rNxQHccrrCl41cLsG:-L-s-WCS3zz0mhv0cIQg:b-gm1o6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/alter_table.go#L449)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

totally optional nit: probably a bit more efficient to only copy the old partitioning descriptor instead of the whole table desc. Feel free to ignore.
</blockquote></details>

I thought of this but was doing it to match RepartitioningFastPathAvailable, which takes TableDescriptors. Of course, RepartitioningFastPathAvailable could also be acting on PartitioningDescriptors but then it would need a really complicated method signature and it felt weird to impose that on the sql<->sqlccl hook. Added a TODO

---

*[pkg/sql/create_table.go, line 883 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJgHskKH_93qyJD-F:-L-s1THZjC-fyRmpsPf7:b24mcsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/create_table.go#L883)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"unimplimented"
</blockquote></details>

I can't spell this word to save my life

---

*[pkg/sql/parser/sql.y, line 3069 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJGjAe6N9ApoJZt08:-L-s1gbV7uiyG5Gqa2lr:b-rk9sxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/parser/sql.y#L3069)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

If we stick with `PARTITION BY NOTHING` instead of `REMOVE PARTITIONING`, I think I'd prefer for the syntax to be folded into the `partition_by` nonterminal so that `CREATE TABLE ... PARTITION BY NOTHING` is valid (but noisy) syntax.
</blockquote></details>

Isn't that what I have?

---

*[pkg/sql/sem/tree/alter_table.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJ5Ihyf2VHYOKgjVo:-L-s1krCEgO05YW2vhvT:bszxse4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb2c78108fdab89bfe45b58bf20d2784b8623d8/pkg/sql/sem/tree/alter_table.go#L36)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Won't this break formatting in other cases? I'm very confused how the tests are passing with this! (Or how they were passing before.) What am I misunderstanding?
</blockquote></details>

Reviewable has helpfully collapsed the whitespace changes below that make this output the same again

---

*[pkg/sql/sem/tree/create.go, line 744 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rIXKBvVKuE8fNukV0:-L-s26LdDF_AGqq-izBn:b-e53b6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/sem/tree/create.go#L744)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm not convinced that we shouldn't use `REMOVE PARTITIONING` for "consistency" with Oracle/MySQL, but don't hold up this PR. We can bikeshed that later.
</blockquote></details>

Crap, you made that comment after I'd implemented this and I simply forgot. Let's merge this and I'm happy to add that later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561)*

**Comment by benesch** [comment]
:shipit: 

---

Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/sql.y, line 3069 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJGjAe6N9ApoJZt08:-L-s8_RX_ADz7Wc-OAhp:b3rm2sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc89f336d424a2967ffbfc76b90438f23937ffe4/pkg/sql/parser/sql.y#L3069)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Isn't that what I have?
</blockquote></details>

Huh, so it is. Must have misread. My bad!

---

*[pkg/sql/sem/tree/alter_table.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-L-rJ5Ihyf2VHYOKgjVo:-L-s8EDFFOBqQlp-4J6g:b5rytfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb2c78108fdab89bfe45b58bf20d2784b8623d8/pkg/sql/sem/tree/alter_table.go#L36)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Reviewable has helpfully collapsed the whitespace changes below that make this output the same again
</blockquote></details>

@$%!#%

Thanks. Thought I was going crazy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20561#-:-L-s8s5Sq64JhwM9N8qj:bizlbj6)*

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
