### PR TITLE
asim: refactor and setup for test framework

### PR DESCRIPTION
**Pull request by kvoli**
This series of patches performs misc refactoring to setup for adding a simulation testing framework.

The first two commits move only files around. The later commits perform limited refactoring of the workload, metrics and simulation variables.

Part of: #90138 

Release note: None

### CODE REVIEW

**Review by shralex — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 17 of 17 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @kvoli)

___
*[`pkg/kv/kvserver/asim/metrics/tracker.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96822#-NNwZxotDGYcG6zEDXLS:-NNwZxou4Y76HYe9hayB:bubl7b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/db43407c49437945666dd84c298b66c4c55b3763/pkg/kv/kvserver/asim/metrics/tracker.go#L34)):*
> ```Go
> 	Replicas           int64
> 	Leases             int64
> 	LeaseTransfers     int64
> ```

in / out or both combined ?
___
*[`pkg/kv/kvserver/asim/metrics/tracker.go` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96822#-NNw_2GF-sUCmCbOJ2Wo:-NNw_2GF-sUCmCbOJ2Wp:b-ec9jd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/db43407c49437945666dd84c298b66c4c55b3763/pkg/kv/kvserver/asim/metrics/tracker.go#L35)):*
> ```Go
> 	Leases             int64
> 	LeaseTransfers     int64
> 	Rebalances         int64
> ```

same here, can you clarify
___
*[`pkg/kv/kvserver/asim/metrics/tracker.go` line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96822#-NNwaOVi66LGbr1LfYyY:-NNwaOVi66LGbr1LfYyZ:bukiyi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/db43407c49437945666dd84c298b66c4c55b3763/pkg/kv/kvserver/asim/metrics/tracker.go#L104)):*
> ```Go
> 	}
> 
> 	sort.Slice(sms, func(i, j int) bool {
> ```

is sorting necessary here ?



_Code quote:_
```Go
usage.StoreUsage
```

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @shralex)

___
*[`pkg/kv/kvserver/asim/metrics/tracker.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96822#-NNwZxotDGYcG6zEDXLS:-NNx-umaA_vEC0kx94kT:bc4w533) ([raw file](https://github.com/cockroachdb/cockroach/blob/db43407c49437945666dd84c298b66c4c55b3763/pkg/kv/kvserver/asim/metrics/tracker.go#L34)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

in / out or both combined ?
</blockquote></details>

Updated with comment. It the store who authored the changed, this is the same as the real store metrics.
___
*[`pkg/kv/kvserver/asim/metrics/tracker.go` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96822#-NNw_2GF-sUCmCbOJ2Wo:-NNx085z2bn1mr_i1ycU:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/db43407c49437945666dd84c298b66c4c55b3763/pkg/kv/kvserver/asim/metrics/tracker.go#L35)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

same here, can you clarify
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/metrics/tracker.go` line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96822#-NNwaOVi66LGbr1LfYyY:-NNwxRay9wEAqMI1s-vI:bbbyvky) ([raw file](https://github.com/cockroachdb/cockroach/blob/db43407c49437945666dd84c298b66c4c55b3763/pkg/kv/kvserver/asim/metrics/tracker.go#L104)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

is sorting necessary here ?
</blockquote></details>

Yes it is necessary because otherwise the callers would need to sort the data to ensure determinism.

**Review by shralex — APPROVED** [review]
> Reviewed 24 of 24 files at r6, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

**Comment by kvoli** [comment]
TYFTR

**Comment by kvoli** [comment]
bors r=shralex

**Pull request merged**
