### PR TITLE
sql: disambiguate formatting of FuncExprs

### PR DESCRIPTION
**Pull request by jordanlewis**
FuncExprs can't roundtrip properly in certain circumstances, because
some FuncExprs are using non-default overloads of builtins. It's hard to
detect that situation exactly, so for now, we disambiguate all
non-window non-generator FuncExprs while formatting them in FmtParsable.

This issue might not be possible in the current state of affairs, but
once we permit nodes that aren't supported by distsql to receive input
from distsql processors (partial plan wrapping), we'll run into this
problem.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Ugh... this changes a lot more test than I was hoping. Maybe it's worth the effort to make it precise - only add type annotations when it's strictly required.

**Comment by jordanlewis** [comment]
PTAL - it's only necessary to add these annotations when the builtin has an overload with PreferredOverload set.

**Review by knz — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28420)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/expr.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28420#-LJmTjleDTYFcWz0cpg6:-LJmTjleDTYFcWz0cpg7:b-8s85cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/09296729a4ca786ae3bede9ab27ce2d3abd4d071/pkg/sql/sem/tree/expr.go#L1273)):*
> ```Go
> 	ctx.WriteByte(')')
> 	if ctx.HasFlags(FmtParsable) && node.typ != nil {
> 		if node.fnProps.AmbiguousReturnType {
> ```

Find a way to ensure that AmbiguousReturnType implies typ != TTuple, so you don't have to check it here

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28420)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/expr.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28420#-LJmTjleDTYFcWz0cpg6:-LJnZ2Hz-TO3Rc7fPjBa:b-psdho) ([raw file](https://github.com/cockroachdb/cockroach/blob/09296729a4ca786ae3bede9ab27ce2d3abd4d071/pkg/sql/sem/tree/expr.go#L1273)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Find a way to ensure that AmbiguousReturnType implies typ != TTuple, so you don't have to check it here
</blockquote></details>

but that doesn't really conceptually make sense, does it? You can still have a tuple ambiguous return type.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28420)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/expr.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28420#-LJmTjleDTYFcWz0cpg6:-LJng4BiEeXjGTJ8e6_q:b3cmch3) ([raw file](https://github.com/cockroachdb/cockroach/blob/09296729a4ca786ae3bede9ab27ce2d3abd4d071/pkg/sql/sem/tree/expr.go#L1273)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

but that doesn't really conceptually make sense, does it? You can still have a tuple ambiguous return type.
</blockquote></details>

Your code below explicitly disables the special case for tuples (because of lack of syntax) so that case doesn't need to be covered.

What I was suggesting was to compute the AmbiguousReturnType attribute in the function props upfront to be `false` if the return type is ttuple.

I appreciate that conceptually this would not make sense if the same function name had two overloads, one returning tuple and one returning non-tuple. However we luckily do not have such overloads now. I invite you to assert this in the init function that computes AmbiguousReturnType with a panic, so we can revisit the topic if/when we start wanting such overloads in the future.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28420)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/expr.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28420#-LJmTjleDTYFcWz0cpg6:-LJpCurN47sW9u7kD1qM:b-ydvjc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/09296729a4ca786ae3bede9ab27ce2d3abd4d071/pkg/sql/sem/tree/expr.go#L1273)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Your code below explicitly disables the special case for tuples (because of lack of syntax) so that case doesn't need to be covered.

What I was suggesting was to compute the AmbiguousReturnType attribute in the function props upfront to be `false` if the return type is ttuple.

I appreciate that conceptually this would not make sense if the same function name had two overloads, one returning tuple and one returning non-tuple. However we luckily do not have such overloads now. I invite you to assert this in the init function that computes AmbiguousReturnType with a panic, so we can revisit the topic if/when we start wanting such overloads in the future.
</blockquote></details>

It's impossible to know the return type of a builtins at init time. Some builtins have dynamic return types that depend on their inputs. Therefore, we need the dynamic check no matter what - so I prefer to keep it the way I have things.

**Comment by jordanlewis** [comment]
@knz am I good to go ahead here?

**Review by knz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28420)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/expr.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28420#-LJmTjleDTYFcWz0cpg6:-LJtDWF6E2PSYTNuwsfi:b68mgjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/09296729a4ca786ae3bede9ab27ce2d3abd4d071/pkg/sql/sem/tree/expr.go#L1273)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It's impossible to know the return type of a builtins at init time. Some builtins have dynamic return types that depend on their inputs. Therefore, we need the dynamic check no matter what - so I prefer to keep it the way I have things.
</blockquote></details>

Ok but please file a followup cleanup issue, add a TODO here to refer to it and cc me on it. Thanks

**Pull request merged**
