### PR TITLE
backup: use span frontier to check coverage

### PR DESCRIPTION
**Pull request by dt**
This replaces calling OverlappingCoveringMerge to compute the import span covering
as a means of verifying that that covering is complete w.r.t time spans with a new
implementation that uses a span.Frontier, which should be significantly cheaper to
execute in time and space than computing the whole non-overlapping covering just to
check for the side-effect of gaps.

Release note (performance improvement): Incremental BACKUPs now use less memory to verify coverage of prior backups.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
Do you think you could capture some profiles (heap or performance) to show the differences?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-:-MsWAcTV7wWXuf0QWXYH:bgkgckv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsW98q_-WMpmtCdUU3s:-MsW98qaCS9r9Z9XgtdS:b5l9g2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L36)):*
> ```Go
> 
> 	// The main loop below requires the entire frontier be caught up to the start
> 	// time of each steap it proceeds, however a span introduced in a later backup
> ```

s/steap/step/
___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsW9hCbCSFWw2wkfulN:-MsW9hCbCSFWw2wkfulO:b-27kvur) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L40)):*
> ```Go
> 	// all layers first to unconditionally advance the introduced spans.
> 	for i := range backups {
> 		for _, sp := range backups[i].IntroducedSpans {
> ```

Few questions: 
Would adding a method to span frontier to "expand" frontier (add more spans) post construction help this and avoid the need
to do this step beforehand.

Does IntroducedSpans guaranteed to be a subset of spans?  The reason why I ask is that span frontier Forward method ignores
parts of the span that are outside the set of spans tracked by the frontier. I suspect that's not what you want.
___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsWAWQd0NmE7s13ODq7:-MsWAWQd0NmE7s13ODq8:b-m7hbm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L80)):*
> ```Go
> 
> // uncoveredSpans retuns the subet of `spans` that is not covered by `covered`.
> // This is similar to roachpb.SubtractSpans, but does not mutate `required``.
> ```

what about SpanGroup.Sub() does that do what you want?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsW9hCbCSFWw2wkfulN:-MsWC0PwEXlZJ7EDY8CC:b-bwxnbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L40)):*
> Would adding a method to span frontier to "expand" frontier (add more spans) post construction help this and avoid the need
to do this step beforehand.

I don't think that helps? The frontier is setup by tracking the spans we actually need to be covered, which may be a subset of the spans in the backups, but also may be a superset of some spans in earlier backups if those spans were introduced later. 

I think if we wanted to remove this what we'd instead do is add a way to query the frontier of some sub-span, so we could say "I want to forward [a, b) *from t1* to t2", and fail if it is not at t1. Right now we check that by checking the whole frontier is at t1, which is sufficient but overkill to just advance [a, b), and means spans we know will be first advanced later need to be advanced first. Overall though I think the current approach is fine: introduced spans are defined as advancing from 0 to start, so we just unconditionally advance them all. Spans are defined as advancing from start to end, so we advance them when start is start.

> Does IntroducedSpans guaranteed to be a subset of spans? The reason why I ask is that span frontier Forward method ignores
parts of the span that are outside the set of spans tracked by the frontier. I suspect that's not what you want.

subset of spans or backups[i].Spans? former no, latter yes. I think I _do_ what the part that doesn't overlap the tracked spans to be discarded... why do you think otherwise?
___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsWAWQd0NmE7s13ODq7:-MsWAy06E_YxmG2S-JqS:bxfilq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L80)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

what about SpanGroup.Sub() does that do what you want?
</blockquote></details>

That's just a wrapper for RangeGroup.Sub which is what I'm using here. I guess I can switch it to remove a the two loops.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsW98q_-WMpmtCdUU3s:-MsWFnKPD71elEeI40OF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L36)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

s/steap/step/
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsWAWQd0NmE7s13ODq7:-MsWFoSfBp2DddzXAj85:brpmqc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L80)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

That's just a wrapper for RangeGroup.Sub which is what I'm using here. I guess I can switch it to remove a the two loops.
</blockquote></details>

removed.

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsW9hCbCSFWw2wkfulN:-MsWPEEqEFyyefEnkcjJ:b-9408ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L40)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

> Would adding a method to span frontier to "expand" frontier (add more spans) post construction help this and avoid the need
to do this step beforehand.

I don't think that helps? The frontier is setup by tracking the spans we actually need to be covered, which may be a subset of the spans in the backups, but also may be a superset of some spans in earlier backups if those spans were introduced later. 

I think if we wanted to remove this what we'd instead do is add a way to query the frontier of some sub-span, so we could say "I want to forward [a, b) *from t1* to t2", and fail if it is not at t1. Right now we check that by checking the whole frontier is at t1, which is sufficient but overkill to just advance [a, b), and means spans we know will be first advanced later need to be advanced first. Overall though I think the current approach is fine: introduced spans are defined as advancing from 0 to start, so we just unconditionally advance them all. Spans are defined as advancing from start to end, so we advance them when start is start.

> Does IntroducedSpans guaranteed to be a subset of spans? The reason why I ask is that span frontier Forward method ignores
parts of the span that are outside the set of spans tracked by the frontier. I suspect that's not what you want.

subset of spans or backups[i].Spans? former no, latter yes. I think I _do_ what the part that doesn't overlap the tracked spans to be discarded... why do you think otherwise?
</blockquote></details>

Just seems strange that forwarding introduced span may discard part of the span... I wanted to make sure that that's the intended behavior.  I guess I don't quite understand introduced spans stuff  -- so, just flagging this frontier behavior to make sure it's what you want.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/backupccl/backup_span_coverage.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74393#-MsW9hCbCSFWw2wkfulN:-MsWQAMZDP5eHXVu1-wM:b-9nj0dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f66c9f6e05db86be82ee5ed55b713a26771fd6b4/pkg/ccl/backupccl/backup_span_coverage.go#L40)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just seems strange that forwarding introduced span may discard part of the span... I wanted to make sure that that's the intended behavior.  I guess I don't quite understand introduced spans stuff  -- so, just flagging this frontier behavior to make sure it's what you want.
</blockquote></details>

the non-introduced spans will also drop anything that doesn't overlap when forwarded --I'm pretty sure if it isn't being tracked, we just don't care.

**Comment by dt** [comment]
Added a benchmark. `makeImportSpans` is somehow even worse than I had even imagined.

```
CoverageChecks/numBackups=24/numSpans=20/numFiles=100/checkCoverage-10        927µs ± 4%
CoverageChecks/numBackups=24/numSpans=20/numFiles=100/makeImportSpans-10     2.59ms ± 2%
CoverageChecks/numBackups=24/numSpans=20/numFiles=1000/checkCoverage-10       932µs ± 1%
CoverageChecks/numBackups=24/numSpans=20/numFiles=1000/makeImportSpans-10    37.3ms ± 2%
CoverageChecks/numBackups=24/numSpans=20/numFiles=10000/checkCoverage-10      917µs ± 3%
CoverageChecks/numBackups=24/numSpans=20/numFiles=10000/makeImportSpans-10    558ms ± 2%

CoverageChecks/numBackups=24/numSpans=20/numFiles=100/checkCoverage-10        415kB ± 0%
CoverageChecks/numBackups=24/numSpans=20/numFiles=100/makeImportSpans-10      835kB ± 0%
CoverageChecks/numBackups=24/numSpans=20/numFiles=1000/checkCoverage-10       415kB ± 0%
CoverageChecks/numBackups=24/numSpans=20/numFiles=1000/makeImportSpans-10    2.90MB ± 0%
CoverageChecks/numBackups=24/numSpans=20/numFiles=10000/checkCoverage-10      415kB ± 0%
CoverageChecks/numBackups=24/numSpans=20/numFiles=10000/makeImportSpans-10   23.7MB ± 0%
```

Treating `checkCoverage` as new and `makeImportSpans` as old:
```
CoverageChecks/numBackups=24/numSpans=20/numFiles=100       2.59ms ± 2%    0.93ms ± 4%   -64.20%  (p=0.000 n=10+10)
CoverageChecks/numBackups=24/numSpans=20/numFiles=1000      37.3ms ± 2%     0.9ms ± 1%   -97.50%  (p=0.000 n=10+9)
CoverageChecks/numBackups=24/numSpans=20/numFiles=10000      558ms ± 2%       1ms ± 3%   -99.84%  (p=0.000 n=9+9)

CoverageChecks/numBackups=24/numSpans=20/numFiles=100        835kB ± 0%     415kB ± 0%   -50.30%  (p=0.000 n=9+10)
CoverageChecks/numBackups=24/numSpans=20/numFiles=1000      2.90MB ± 0%    0.41MB ± 0%   -85.71%  (p=0.000 n=10+10)
CoverageChecks/numBackups=24/numSpans=20/numFiles=10000     23.7MB ± 0%     0.4MB ± 0%   -98.25%  (p=0.000 n=10+10)
```

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by dt** [comment]
blathers backport 21.2

**Pull request merged**
