### PR TITLE
roachpb: add lock durability info to Get/Scan/ReverseScan requests

### PR DESCRIPTION
**Pull request by arulajmani**
This patch adds lock durability information to Get, Scan, and ReverseScan requests. This field is only ever meaningful in conjunction with a locking strength that's not lock.None.

By default, all locking requests ask for best-effort locks. This preserves the mixed version story between 23.1 <-> 23.2 nodes. However, transactions that need them for correctness (read: read committed), will now have the option to ask for guranteed durability locks. These will then correspond to replicated locks. Note that the field here is named in terms of durability guarantees, and not the specific implementation detail we'll use to provide this -- this is intentional. It allows us to offer a different kind of durable locks in the future, for example schemes that selectively replicate locks because they have buy-in from the both the kvserver and kvclient, in conjunction with some scheme to verify locks at commit time.

Informs #109672

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-NdlEV1315jfHyB58o9v:-NdlEV1315jfHyB58o9w:b-wkkv4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/982ff4c7e8687ec4e137a749699f8fb9902f3682/pkg/kv/kvclient/kvstreamer/size.go#L41)):*
> ```Go
> 		unsafe.Sizeof(kvpb.ScanRequest{}))
> 	// TODO(XXX): understand this.
> 	if requestOverhead+8 != scanRequestOverhead {
> ```

@yuzefovich looks like introducing this new field caused these request sizes to diverge. How would you feel if we picked the higher of the two (`scanRequestOverhead`) in requestSize. We would be overestimating `GetRequests` by 8 bytes in our tracking -- is that fine?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-NdlNQSg5_vWwGl3T0L0):*
Bump in the size of `ScanRequest` is unfortunate - I think it pushes the object from 64 byte size class into 80 byte size class. Would it be possible to adjust existing `lock.Strength` proto to incorporate the durability information too? I.e. rather than existing `Shared` and `Exclusive`, we'd have old-but-renamed `SharedBestEffort` and `ExclusiveBestEffort` plus newly added `SharedGuaranteed` and `ExclusiveGuaranteed`. Are there many places in the code we'd need to teach about this? If not, perhaps this micro-optimization would be worth it.
___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-NdlEV1315jfHyB58o9v:-NdlGhKDCXaRxKYOZjWD:b-ntcqyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/982ff4c7e8687ec4e137a749699f8fb9902f3682/pkg/kv/kvclient/kvstreamer/size.go#L41)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

@yuzefovich looks like introducing this new field caused these request sizes to diverge. How would you feel if we picked the higher of the two (`scanRequestOverhead`) in requestSize. We would be overestimating `GetRequests` by 8 bytes in our tracking -- is that fine?
</blockquote></details>

We should separate out `requestOverhead` into `getRequestOverhead` and `scanRequestOverhead`, and then remove unified `requestSize` method in favor of two new methods `getRequestSize` and `scanRequestSize`. Before this change, two overheads were the same, and this check in `init` was asserting that; now that the sizes are different, we should split it and remove this particular assertion.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-NdlNQSg5_vWwGl3T0L0):*
It's 72 to 80 bytes, but yeah. It's unfortunate that gogoproto gives int32s to us for these enums -- we really don't need that much memory. 

> Would it be possible to adjust existing `lock.Strength` proto to incorporate the durability information too?

They're used all over in the lock table code and these strengths are also persisted in storage (in the lock table key). It'll be fairly invasive for the lock table, so I'm a bit hesitant to make this change. We'd also need to make sure we never see a `SharedBestEffort` or `ExclusiveBestEffort` down in storage, as they map to unreplicated Shared/Exclusive locks, which should never make it there. 

A better alternative, inspired by your suggestion, would be to create a new enum that includes both strength + durability information and use that for `Get/Scan/RevScan` requests (instead of changing lock.Strength). We could then decompose it into lock strength/durability on the kv server side. But even then, we'll have to figure out the mixed version story and it'll take 1 full release until we can fully deprecate the use of lock.Strength here.
___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-NdlEV1315jfHyB58o9v:-NdlVQxq7U213zI2GoYh:b-cvpm0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/982ff4c7e8687ec4e137a749699f8fb9902f3682/pkg/kv/kvclient/kvstreamer/size.go#L41)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We should separate out `requestOverhead` into `getRequestOverhead` and `scanRequestOverhead`, and then remove unified `requestSize` method in favor of two new methods `getRequestSize` and `scanRequestSize`. Before this change, two overheads were the same, and this check in `init` was asserting that; now that the sizes are different, we should split it and remove this particular assertion.
</blockquote></details>

Ack, that sounds much better than the overestimation thing. Thanks for the suggestion.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-NdlNQSg5_vWwGl3T0L0):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It's 72 to 80 bytes, but yeah. It's unfortunate that gogoproto gives int32s to us for these enums -- we really don't need that much memory. 

> Would it be possible to adjust existing `lock.Strength` proto to incorporate the durability information too?

They're used all over in the lock table code and these strengths are also persisted in storage (in the lock table key). It'll be fairly invasive for the lock table, so I'm a bit hesitant to make this change. We'd also need to make sure we never see a `SharedBestEffort` or `ExclusiveBestEffort` down in storage, as they map to unreplicated Shared/Exclusive locks, which should never make it there. 

A better alternative, inspired by your suggestion, would be to create a new enum that includes both strength + durability information and use that for `Get/Scan/RevScan` requests (instead of changing lock.Strength). We could then decompose it into lock strength/durability on the kv server side. But even then, we'll have to figure out the mixed version story and it'll take 1 full release until we can fully deprecate the use of lock.Strength here.
</blockquote></details>

Note that after https://github.com/cockroachdb/cockroach/pull/107961 is merged there will be one more property ("Locking Form", either record or predicate) that will need to be set in `GetRequest` (and maybe one day for both scan requests but not necessarily in 23.2, though it could be).

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5JiXP-iqX5bFhMT9P:-Ne5JiXP-iqX5bFhMT9Q:blnbmd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/456a06bf687fa841b33db14334ec531450471233/pkg/kv/kvclient/kvstreamer/size.go#L73)):*
> ```Go
> // overhead. key and endKey are the keys from the span of the request header
> // (we choose to avoid taking in a roachpb.Span in order to reduce allocation).
> func getRequestSize(key, endKey roachpb.Key) int64 {
> ```

For a `GetRequest`, don't we expect the EndKey to be empty?
___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5JuzJ12Lth1wRe9jH:-Ne5JuzJ12Lth1wRe9jI:b8ilsjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/456a06bf687fa841b33db14334ec531450471233/pkg/kv/kvclient/kvstreamer/size.go#L79)):*
> ```Go
> func requestsMemUsage(reqs []kvpb.RequestUnion) (memUsage int64) {
> 	for _, r := range reqs {
> 		h := r.GetInner().Header()
> ```

nit: `RequestUnion.GetInner` isn't free, so let's extract it into a variable.
___
*[`pkg/kv/kvpb/api.proto` line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5KXmVEVWeuKSyAj0b:-Ne5KXmVEVWeuKSyAj0c:bfr7iqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddf4b43d8e62e9a2f7bb6bc3eed1ac618736831a/pkg/kv/kvpb/api.proto#L244)):*
> ```proto
> 
>   // Durability denotes the durability with which locks, if any are acquired,
>   // should be acquired with. It is only ever meaningful when KeyLocking is set
> ```

nit: instead of saying "is only ever meaningful", let's say something a little more prescriptive, like "must only be set when ...".
___
*[`pkg/kv/kvpb/api.proto` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5Kh8e8UE1tPjRydB6:-Ne5Kh8e8UE1tPjRydB7:bqu9tf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddf4b43d8e62e9a2f7bb6bc3eed1ac618736831a/pkg/kv/kvpb/api.proto#L252)):*
> ```proto
>   // they are faster to acquire and resolve when compared to replicated locks.
>   // This makes them an appealing choice for transactions that do not require
>   // locks for correctness (read: serializable isolation transactions).
> ```

Another example is implicit SFU in weak isolation transactions. If we know we're going to immediately perform an intent write to the key, we can (and will) avoid the lock replication.
___
*[`pkg/kv/kvpb/api.proto` line 261 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5KOUR7HRw59P2D5hI:-Ne5KOUR7HRw59P2D5hJ:bx5o7js) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddf4b43d8e62e9a2f7bb6bc3eed1ac618736831a/pkg/kv/kvpb/api.proto#L261)):*
> ```proto
>   // transactions that need guaranteed locks for correctness (read:
>   // read-committed or snapshot isolation transactions).
>   kv.kvserver.concurrency.lock.Durability durability = 3;
> ```

We should name this `key_locking_durability` and rename `key_locking` to `key_locking_strength`. "durability" along is quite vague.
___
*[`pkg/kv/kvpb/api.proto` line 641 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5KvML7VfwHI6EAdPN:-Ne5KvML7VfwHI6EAdPO:bwmesx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddf4b43d8e62e9a2f7bb6bc3eed1ac618736831a/pkg/kv/kvpb/api.proto#L641)):*
> ```proto
>   kv.kvserver.concurrency.lock.Strength key_locking = 5;
> 
>   // Durability denotes the durability with which locks, if any are acquired,
> ```

Same comments as above.
___
*[`pkg/kv/kvpb/api.proto` line 726 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5Kx8gBALRLC05-ttY:-Ne5Kx8gBALRLC05-ttZ:bwmesx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddf4b43d8e62e9a2f7bb6bc3eed1ac618736831a/pkg/kv/kvpb/api.proto#L726)):*
> ```proto
>   kv.kvserver.concurrency.lock.Strength key_locking = 5;
> 
>   // Durability denotes the durability with which locks, if any are acquired,
> ```

Same comments as above.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5SA6M8WiPvgZvxQGm:-Ne5SA6M8WiPvgZvxQGn:b54ghgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/456a06bf687fa841b33db14334ec531450471233/pkg/kv/kvclient/kvstreamer/size.go#L40)):*
> ```Go
> 
> func init() {
> 	reverseScanRequestOverhead := int64(unsafe.Sizeof(kvpb.RequestUnion_Scan{}) +
> ```

Shouldn't we use `RequestUnion_ReverseScan` here?
___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5JiXP-iqX5bFhMT9P:-Ne5SGjlEADKZ8Q6H40a:b48tocy) ([raw file](https://github.com/cockroachdb/cockroach/blob/456a06bf687fa841b33db14334ec531450471233/pkg/kv/kvclient/kvstreamer/size.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

For a `GetRequest`, don't we expect the EndKey to be empty?
</blockquote></details>

Right, we do expect the EndKey to be empty, so now that we're splitting `requestSize` function into two we can have different signatures too (the original `requestSize` function did take advantage of the end key being empty for Gets).

**Review by arulajmani — COMMENTED** [review]
Addressed comments; RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-:-Ne8_BiU8-V5slh-Qqv2:byywb6k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @nvanbenschoten, and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5SA6M8WiPvgZvxQGm:-Ne8TL5s9jmqTyM75Phb:b-jtrkjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/456a06bf687fa841b33db14334ec531450471233/pkg/kv/kvclient/kvstreamer/size.go#L40)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Shouldn't we use `RequestUnion_ReverseScan` here?
</blockquote></details>

Oops copy pasta. Fixed.
___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5JiXP-iqX5bFhMT9P:-Ne8TxFX6EsZUDQvgLyP:bombmv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/456a06bf687fa841b33db14334ec531450471233/pkg/kv/kvclient/kvstreamer/size.go#L73)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Right, we do expect the EndKey to be empty, so now that we're splitting `requestSize` function into two we can have different signatures too (the original `requestSize` function did take advantage of the end key being empty for Gets).
</blockquote></details>

Good call. Done.
___
*[`pkg/kv/kvclient/kvstreamer/size.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5JuzJ12Lth1wRe9jH:-Ne8UcMe8SgmGZ1mhlHE:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/456a06bf687fa841b33db14334ec531450471233/pkg/kv/kvclient/kvstreamer/size.go#L79)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `RequestUnion.GetInner` isn't free, so let's extract it into a variable.
</blockquote></details>

Done. 
___
*[`pkg/kv/kvpb/api.proto` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5Kh8e8UE1tPjRydB6:-Ne8W_fR6LBTGV98IdWN:bis9olu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddf4b43d8e62e9a2f7bb6bc3eed1ac618736831a/pkg/kv/kvpb/api.proto#L252)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Another example is implicit SFU in weak isolation transactions. If we know we're going to immediately perform an intent write to the key, we can (and will) avoid the lock replication.
</blockquote></details>

Good point. Added.
___
*[`pkg/kv/kvpb/api.proto` line 261 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne5KOUR7HRw59P2D5hI:-Ne8WeB43iqR03VySF2u:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddf4b43d8e62e9a2f7bb6bc3eed1ac618736831a/pkg/kv/kvpb/api.proto#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should name this `key_locking_durability` and rename `key_locking` to `key_locking_strength`. "durability" along is quite vague.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: mod the one question about the `LockingReadRequest` interface.

> Reviewed 7 of 7 files at r4, 19 of 19 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-:-Ne8coeV0EbfdJwjBqzp:bdf78dt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @yuzefovich)

___
*[`pkg/kv/kvpb/api.go` line 201 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne8cLKsDXuaAAsxmA6i:-Ne8cLKsDXuaAAsxmA6j:bzcfgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0f977b183cfe4b4d5943ca501599bf4520afedf/pkg/kv/kvpb/api.go#L201)):*
> ```Go
> type LockingReadRequest interface {
> 	Request
> 	KeyLockingStr() lock.Strength
> ```

What do you think about calling this `KeyLocking()` and having it return `(lock.Strength, lock.Durability)`? I think that's actually what we want in the use of the method in `collectSpansRead`.

**Review by arulajmani — COMMENTED** [review]
Made the change to `LockingReadRequest`. I also realized that I hadn't `s/KeyLocking/KeyLockingStrength/`for `{,Reverse}ScanRequests`, which is now done. 

TFTR!

bors r=nvanbenschoten 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-:-Ne8l1VJ8UiTrPe3zNUF:bmgho8w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2, @nvanbenschoten, and @yuzefovich)

___
*[`pkg/kv/kvpb/api.go` line 201 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110201#-Ne8cLKsDXuaAAsxmA6i:-Ne8kH2q9l54mU4yfnAP:b1f1onv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0f977b183cfe4b4d5943ca501599bf4520afedf/pkg/kv/kvpb/api.go#L201)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you think about calling this `KeyLocking()` and having it return `(lock.Strength, lock.Durability)`? I think that's actually what we want in the use of the method in `collectSpansRead`.
</blockquote></details>

Sounds good to me. I don't think we'll end up using durability information in `collectSpansRead`, but it's weird to not copy it over.

**Pull request merged**
