### PR TITLE
release-22.2: security: add a cache to store client cert expirations for users

### PR DESCRIPTION
**Pull request by cameronnunez**
Backport 1/1 commits from #103592.

/cc @cockroachdb/release

---

Fixes https://github.com/cockroachdb/cockroach/issues/100699.

This change introduces a new node-level, FIFO cache for storing the minimum time-until-expiration of the set of client certs seen (per user). 

Entries in the cache are username-gauge pairs, where the gauges contain the expiration values. Periodically, gauges with 
expiration values that are not in the future will be cleared from the cache. The purging process triggers hourly. 

The gauges in the cache are children of an aggregate gauge `ClientExpiration`, so the aggregated value for that metric 
is not meaningful and only serves as a link to the children. `ClientExpiration` (`security.certificate.expiration.client`)
is exported as a metric and the children gauges are labeled by SQL user.

Release note (security update): There is a new `server.client_cert_expiration_cache.capacity` setting which, when set to a non-zero number, makes it so that the minimum time-until-expiration of the set of client certificates seen is stored (for every user). This setting can be used to ensure client cert expirations are exported as a metric (if set to zero, the metric `security.certificate.expiration.client` will have a value of zero).

---

Release justification: high-priority request

### CODE REVIEW

**Comment by knz** [comment]
@cameronnunez why did you select PR https://github.com/cockroachdb/cockroach/pull/95524 for backport?

**Comment by cameronnunez** [comment]
@knz due to a merge conflict. changes were made to `aggmetric` in that PR

**Comment by knz** [comment]
I think the better approach is to keep just the backport of your PR and fix the merge conflict by hand in your commit (by changing the name of the function in your code)

**Comment by cameronnunez** [comment]
Good point, that is the better approach. Fixed

**Review by knz — APPROVED** [review]

**Pull request merged**
