### PR TITLE
filetable: read chunks as needed

### PR DESCRIPTION
**Pull request by dt**
This changes filetable to read only the block needed from the table
instead of reading the whole file at once.

Release note: none.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by dt** [comment]
another flake?

bors r+

**Pull request merged**
