### PR TITLE
raft: persist LeadEpoch in HardState

### LINKED ISSUE #124497: raft: persist LeadEpoch in HardState
Needed for leader leases: https://github.com/cockroachdb/cockroach/issues/123847.

Related to https://github.com/cockroachdb/cockroach/issues/124421.

Jira issue: CRDB-38930

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
Closes https://github.com/cockroachdb/cockroach/issues/124497

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127385#-:-O21POdX5nJhA7y9yEry:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raftpb/raft.proto` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127385#-O21NJniDORj_XCtedr6:-O21NJniDORj_XCtedr7:bwkf51g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9288cbff6cfed99ec434e0f61000a36d8cfdcd54/pkg/raft/raftpb/raft.proto#L92)):*
> ```proto
> 	optional uint64      commit      = 8  [(gogoproto.nullable) = false];
> 	optional uint64      lead        = 16 [(gogoproto.nullable) = false, (gogoproto.casttype) = "PeerID"];
>   optional uint64      leadEpoch   = 17 [(gogoproto.nullable) = false,
> ```

The alignment on this looks off as well. We seem to use spaces instead of tabs in other `.proto` files. We must have just missed that when importing `etcd/raft`. Should we switch this file to use space indentation (in a separate commit)?


___
*[`pkg/raft/raftpb/raft.proto` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127385#-O21NqdjCnPlKJ41sO97:-O21NqdjCnPlKJ41sO98:b48rgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9288cbff6cfed99ec434e0f61000a36d8cfdcd54/pkg/raft/raftpb/raft.proto#L135)):*
> raftstoreliveness.StoreLivenessEpoch

This is a bit of a mouthful, and it seems to run afoul of Go's "anti-stuttering" rule (https://go.dev/doc/effective_go#package-names). Should we rename to `raftstoreliveness.Epoch`?

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127385#-:-O21X74C2kAUkIOdvynS:b-l0r5kv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/raftpb/raft.proto` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127385#-O21NJniDORj_XCtedr6:-O21Wjcf1RwWIXHYfIfP:b-jbo5xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9288cbff6cfed99ec434e0f61000a36d8cfdcd54/pkg/raft/raftpb/raft.proto#L92)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The alignment on this looks off as well. We seem to use spaces instead of tabs in other `.proto` files. We must have just missed that when importing `etcd/raft`. Should we switch this file to use space indentation (in a separate commit)?


</blockquote></details>

Ugh sorry about that. Fixed in the first commit and then updated to use spaces in the second. 
___
*[`pkg/raft/raftpb/raft.proto` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127385#-O21NqdjCnPlKJ41sO97:-O21X4_k0pMNufsmmSN4:b-dtdzt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9288cbff6cfed99ec434e0f61000a36d8cfdcd54/pkg/raft/raftpb/raft.proto#L135)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> raftstoreliveness.StoreLivenessEpoch

This is a bit of a mouthful, and it seems to run afoul of Go's "anti-stuttering" rule (https://go.dev/doc/effective_go#package-names). Should we rename to `raftstoreliveness.Epoch`?
</blockquote></details>

I had the same thought. Renamed.

**Comment by arulajmani** [comment]
bors r=nvanbenschoten

**Comment by arulajmani** [comment]
Forgot to update `TestProtoMemorySizes`. 

bors r+

**Pull request merged**
