### PR TITLE
pkg: add an experimental cluster setting for enum use

### LINKED ISSUE #49426: sql: add an experimental flag for enums
We should have one, since there are definitely panics lurking (#48728, #49300)

### PR DESCRIPTION
**Pull request by rohany**
Fixes: #49426.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
is there a reason we want this to be experimental? is it expected to be experimental going in to 20.2.0? seems a little sad we have to mark it as such -- much lower adoption :(

**Comment by rohany** [comment]
No i plan on getting rid of it before 20.2, but I want to mark it as experimental now until i get rid of all the known panics/bugs. It should also def be experimental before we have leasing of types

**Comment by otan** [comment]
Is there an advantage of adding this in and deleting this later vs just adding this before the release?

**Comment by rohany** [comment]
We've done it in the past with primary key changes -- it seems good to master stable with these features that could break other things.

**Review by otan — APPROVED** [review]
if you insist :3

**Pull request merged**
