### PR TITLE
distsql: put the SQL into diagrams

### PR DESCRIPTION
**Pull request by RaduBerinde**
We have seen cases where we get an `EXPLAIN ANALYZE` output from a
client and it's not clear which variation of a big query it was from.
This change adds the SQL to the diagram. A corresponding change on the
diagram rendering side is in progress.

Release justification: low-risk change with customer benefit.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
image

**Comment by jordanlewis** [comment]
Lol

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41129#-:-Lq81WzmBefe6tR2zN-S:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Pull request merged**
