### PR TITLE
workload/schemachange: add SET LOCALITY REGIONAL BY ROW [AS]

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

### CODE REVIEW

**Comment by otan** [comment]
hmm, i don't understand the failure:

```

I210401 02:10:50.444333 597596 testutils/testcluster/testcluster.go:101  [-] 222348  TestCluster quiescing nodes
W210401 02:10:50.444414 599702 sql/sqlliveness/slinstance/slinstance.go:183  [n3] 222349  exiting heartbeat loop
W210401 02:10:50.444508 599703 jobs/registry.go:729  [-] 222350  canceling all adopted jobs due to stopper quiescing
W210401 02:10:50.444570 613534 kv/kvserver/closedts/sidetransport/receiver.go:125  [n3] 222351  closed timestamps side-transport connection dropped from node: 2
W210401 02:10:50.444612 616879 kv/kvserver/closedts/sidetransport/receiver.go:125  [n2] 222352  closed timestamps side-transport connection dropped from node: 3
W210401 02:10:50.444730 600006 kv/kvserver/closedts/sidetransport/receiver.go:125  [n3] 222354  closed timestamps side-transport connection dropped from node: 1
W210401 02:10:50.444690 616890 kv/kvserver/closedts/sidetransport/receiver.go:125  [n1] 222353  closed timestamps side-transport connection dropped from node: 3
W210401 02:10:50.444779 598111 sql/sqlliveness/slinstance/slinstance.go:183  [n1] 222355  exiting heartbeat loop
W210401 02:10:50.444843 598112 jobs/registry.go:729  [-] 222356  canceling all adopted jobs due to stopper quiescing
W210401 02:10:50.444836 613289 kv/kvserver/closedts/sidetransport/receiver.go:125  [n1] 222357  closed timestamps side-transport connection dropped from node: 2
W210401 02:10:50.444959 599286 jobs/registry.go:729  [-] 222358  canceling all adopted jobs due to stopper quiescing
W210401 02:10:50.445017 599979 kv/kvserver/closedts/sidetransport/receiver.go:125  [n2] 222359  closed timestamps side-transport connection dropped from node: 1
W210401 02:10:50.445109 614051 kv/kvserver/raft_transport.go:633  [n2] 222360  while processing outgoing Raft queue to node 3: EOF:
W210401 02:10:50.445149 600562 kv/kvserver/raft_transport.go:633  [n1] 222361  while processing outgoing Raft queue to node 2: EOF:
W210401 02:10:50.445204 599285 sql/sqlliveness/slinstance/slinstance.go:183  [n2] 222362  exiting heartbeat loop
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange	260.801s
FAIL
```

nothing looks dead o_o schema changes seem like they're doing ok.

**Comment by otan** [comment]
ah nvm it's higher up

```
--- FAIL: TestWorkload (5.55s)
    schema_change_external_test.go:111:
        	Error Trace:	schema_change_external_test.go:111
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: relation "table160" (89): unimplemented: cannot perform a schema change operation while a primary key change is in progress (SQLSTATE 0A000)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:401
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:435
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange_test.TestWorkload.func3.1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:100
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	  | runtime.goexit
        	            	  | 	/usr/local/opt/go@1.15/libexec/src/runtime/asm_amd64.s:1374
        	            	Wraps: (3) ***UNEXPECTED ERROR; Received an unexpected execution error
        	            	Wraps: (4) ERROR: relation "table160" (89): unimplemented: cannot perform a schema change operation while a primary key change is in progress (SQLSTATE 0A000)
        	            	Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.withPrefix (4) pgx.PgError
        	Test:       	TestWorkload
```

**Review by ajwerner — COMMENTED** [review]
Can I get an honest experience report? How is this going?

I think you need a rebase for the test failure. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-:-MXAcKPt93eHNIkEWu34:b-kr5m3v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/schemachange/error_screening.go, line 808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXA_HnMBanzmKD2n4lx:-MXA_HnMBanzmKD2n4ly:b-w2otyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/error_screening.go#L808)):*
> ```Go
> 		tx,
> 		`
> 		SELECT EXISTS (SELECT table_id FROM crdb_internal.schema_changes
> ```

I'm torn here. One the one hand, ideally we'll use the catalog tables and they will work great and yay. On the other hand, many (almost all) catalog tables lack virtual indexes which means that the more of these checks which use those tables we have, the more likely we are to scan the entire descriptor table and thus conflict with all other schema change transactions. On the other, other hand, we already do have a lot of checks which result in said scans. 

I'm filing an issue (https://github.com/cockroachdb/cockroach/issues/62930) to create virtual indexes for every virtual table which we can index by table. That will help a lot. In the meantime, you could write this like:

```
SELECT json_array_length(
        crdb_internal.pb_to_json(
            'cockroach.sql.sqlbase.Descriptor',
            descriptor
        )->'table'->'mutations'
       )
       = 0
  FROM system.descriptor
 WHERE id = $1::REGCLASS;
```

Take it or leave it, I really am fine if you leave it. 
___
*[pkg/workload/schemachange/operation_generator.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAYxYNBbE-gS9T0PtB:-MXAYxYODejw7qnYe5XW:b8quhod) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/operation_generator.go#L462)):*
> ```Go
> 	tx *pgx.Tx, tableName *tree.TableName,
> ) (bool, error) {
> 	if len(og.opsInTxn) > 0 {
> ```

:thinking: why? The changes are likely for a different table. 
___
*[pkg/workload/schemachange/schemachange.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAZtL0COLOfL1S_Uqf:-MXAZtL0COLOfL1S_Uqg:b1hr27f) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/schemachange.go#L358)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 		// Some ops can only be done executed if they are standalone (e.g.
> 		// anything using ALTER PRIMARY KEY). Early exit if so.
> 		if len(w.opGen.opsInTxn) > 0 {
> 			switch w.opGen.opsInTxn[len(w.opGen.opsInTxn)-1] {
> 			case alterTableLocality:
> 				break
> 			}
> 		}
> ```
</details>

isn't this just saying that it's the last operation, not that it's standalone. I also don't really understand the condition or why to special case this. Is it just that you'd like it to not fail most of the time and it is only likely to succeed if there's just one operation? I've been thinking that probably this uniform distribution of the number of commands isn't wise. Perhaps we should do something more exponential.

**Review by otan — COMMENTED** [review]
> Can I get an honest experience report? How is this going?

it's.... ok. it's a little annoying having to think of all the error cases upfront, and some data is hard to access (e.g. existing schema change). the UDT stuff seems rare to hit as well. but rewarding for sure :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-:-MXAcr-l1QbtM2vZMiP8:b-ieclfe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/workload/schemachange/operation_generator.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAYxYNBbE-gS9T0PtB:-MXAd1gw4rkV5nV38E5Q:bmx8da4) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/operation_generator.go#L462)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:thinking: why? The changes are likely for a different table. 
</blockquote></details>

hmm, it needs to be the only mutation on the table and might not be committed yet?
but the schema_change / scan you mention above takes care of this i think, so removing it!
___
*[pkg/workload/schemachange/schemachange.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAZtL0COLOfL1S_Uqf:-MXAdLtz2vNZxthHDEux:b-gtey4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/schemachange.go#L358)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		// Some ops can only be done executed if they are standalone (e.g.
> 		// anything using ALTER PRIMARY KEY). Early exit if so.
> 		if len(w.opGen.opsInTxn) > 0 {
> 			switch w.opGen.opsInTxn[len(w.opGen.opsInTxn)-1] {
> 			case alterTableLocality:
> 				break
> 			}
> 		}
> ```
isn't this just saying that it's the last operation, not that it's standalone. I also don't really understand the condition or why to special case this. Is it just that you'd like it to not fail most of the time and it is only likely to succeed if there's just one operation? I've been thinking that probably this uniform distribution of the number of commands isn't wise. Perhaps we should do something more exponential. 
</blockquote></details>

hmm, i removed it. might be because earlier on i had a bad in progress schema_changes check.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62909)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/workload/schemachange/operation_generator.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAYxYNBbE-gS9T0PtB:-MXb63Yb6mSx4c7FzKBS:b-r9uhsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/operation_generator.go#L462)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm, it needs to be the only mutation on the table and might not be committed yet?
but the schema_change / scan you mention above takes care of this i think, so removing it!
</blockquote></details>

seems like it is still present

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62909)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/workload/schemachange/operation_generator.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAYxYNBbE-gS9T0PtB:-MXb7Wjx6QZYDB4J7Kyv:b-usqlm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/operation_generator.go#L462)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

seems like it is still present
</blockquote></details>

Deleting this gives me:

```
W210406 12:20:16.933591 175236 kv/kvserver/raft_transport.go:633  [n1] 65343  while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
--- FAIL: TestWorkload (9.18s)
    schema_change_external_test.go:111:
        	Error Trace:	schema_change_external_test.go:111
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:392
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:426
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange_test.TestWorkload.func3.1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:100
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	  | runtime.goexit
        	            	  | 	/usr/local/opt/go@1.15/libexec/src/runtime/asm_amd64.s:1374
        	            	Wraps: (3) ***UNEXPECTED ERROR; Received an unexpected execution error
        	            	Wraps: (4) ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.withPrefix (4) pgx.PgError
        	Test:       	TestWorkload
```

**Comment by otan** [comment]
___
*[pkg/workload/schemachange/operation_generator.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAYxYNBbE-gS9T0PtB:-MXb7hQb9nvbmogpjRH0:b-3wk828) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/operation_generator.go#L462)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Deleting this gives me:

```
W210406 12:20:16.933591 175236 kv/kvserver/raft_transport.go:633  [n1] 65343  while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
--- FAIL: TestWorkload (9.18s)
    schema_change_external_test.go:111:
        	Error Trace:	schema_change_external_test.go:111
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:392
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:426
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange_test.TestWorkload.func3.1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:100
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	  | runtime.goexit
        	            	  | 	/usr/local/opt/go@1.15/libexec/src/runtime/asm_amd64.s:1374
        	            	Wraps: (3) ***UNEXPECTED ERROR; Received an unexpected execution error
        	            	Wraps: (4) ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.withPrefix (4) pgx.PgError
        	Test:       	TestWorkload
```
</blockquote></details>

```
{
 "workerId": 0,
 "clientTimestamp": "12:21:46.345019",
 "ops": [
  "BEGIN",
  "ALTER TABLE schema271.table279 ADD COLUMN col279_286 INT4",
  "SELECT 'validating all objects'",
  "ALTER TABLE schema271.table279 SET LOCALITY REGIONAL BY ROW"
 ],
 "expectedExecErrors": "",
 "expectedCommitErrors": "",
 "message": "***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: unimplemented: cannot perform a locality change on table279 with other schema changes on table279 in the same transaction (SQLSTATE 0A000)",
 "txStatus": "TxStatusRollbackSuccess"
}
```

or this :\

**Comment by otan** [comment]
___
*[pkg/workload/schemachange/schemachange.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAZtL0COLOfL1S_Uqf:-MXb8RXd9uZyfePxsJiY:b-2ji3d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/schemachange.go#L358)):*
> is currently undergoing a schema change

on re-running the test, it seems like removing this gives:

```
W210406 12:20:16.933591 175236 kv/kvserver/raft_transport.go:633  [n1] 65343  while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
--- FAIL: TestWorkload (9.18s)
    schema_change_external_test.go:111:
        	Error Trace:	schema_change_external_test.go:111
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:392
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:426
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange_test.TestWorkload.func3.1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:100
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	  | runtime.goexit
        	            	  | 	/usr/local/opt/go@1.15/libexec/src/runtime/asm_amd64.s:1374
        	            	Wraps: (3) ***UNEXPECTED ERROR; Received an unexpected execution error
        	            	Wraps: (4) ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.withPrefix (4) pgx.PgError
        	Test:       	TestWorkload
```

**Comment by otan** [comment]
___
*[pkg/workload/schemachange/schemachange.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAZtL0COLOfL1S_Uqf:-MXb9D6h3z8zqJyArvIt:b-jd3cp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/schemachange.go#L358)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> is currently undergoing a schema change

on re-running the test, it seems like removing this gives:

```
W210406 12:20:16.933591 175236 kv/kvserver/raft_transport.go:633  [n1] 65343  while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
--- FAIL: TestWorkload (9.18s)
    schema_change_external_test.go:111:
        	Error Trace:	schema_change_external_test.go:111
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:392
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:426
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange_test.TestWorkload.func3.1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:100
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	  | runtime.goexit
        	            	  | 	/usr/local/opt/go@1.15/libexec/src/runtime/asm_amd64.s:1374
        	            	Wraps: (3) ***UNEXPECTED ERROR; Received an unexpected execution error
        	            	Wraps: (4) ERROR: unimplemented: table table342 is currently undergoing a schema change (SQLSTATE 0A000)
        	            	Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.withPrefix (4) pgx.PgError
        	Test:       	TestWorkload
```
</blockquote></details>

(might be wrong on this one, but hitting the hay now)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62909)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/workload/schemachange/operation_generator.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAYxYNBbE-gS9T0PtB:-MXb8ejbBOCrBAGQcFPu:bweba4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/operation_generator.go#L462)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

```
{
 "workerId": 0,
 "clientTimestamp": "12:21:46.345019",
 "ops": [
  "BEGIN",
  "ALTER TABLE schema271.table279 ADD COLUMN col279_286 INT4",
  "SELECT 'validating all objects'",
  "ALTER TABLE schema271.table279 SET LOCALITY REGIONAL BY ROW"
 ],
 "expectedExecErrors": "",
 "expectedCommitErrors": "",
 "message": "***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: unimplemented: cannot perform a locality change on table279 with other schema changes on table279 in the same transaction (SQLSTATE 0A000)",
 "txStatus": "TxStatusRollbackSuccess"
}
```

or this :\ 

</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/af0e2cb6f347413ea370591524a3e1dbe49464b4/pkg/sql/alter_primary_key.go#L94-L106 grr this is a pretty opaque policy to put into the check.

**Review by ajwerner — COMMENTED** [review]
I accept if you add some commentary around that odd rule. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-:-MXb9Nir8NyGnGMCpSS9:b-zbczur)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by otan** [comment]
___
*[pkg/workload/schemachange/operation_generator.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62909#-MXAYxYNBbE-gS9T0PtB:-MXbE2wU14uhxF9bir7s:b-8q3ibb) ([raw file](https://github.com/cockroachdb/cockroach/blob/38529354ba454b4a96c7df518b1259968d6cbd3e/pkg/workload/schemachange/operation_generator.go#L462)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/af0e2cb6f347413ea370591524a3e1dbe49464b4/pkg/sql/alter_primary_key.go#L94-L106 grr this is a pretty opaque policy to put into the check. 
</blockquote></details>

realised the latter one was a typo -- should be > 0 not = 0 for the length check.

**Comment by otan** [comment]
i've had successful runs barring other issues in the schemachange workload (SET DATA TYPE runs into other issues?) so i'm merging this one!

bors r=ajwerner

**Comment by otan** [comment]
bors r-

ooh, one more thing

**Comment by ajstorm** [comment]
Just noticed that the case here has gone cold.  Was that intentional?  Should this PR be closed?

**Comment by otan** [comment]
Still needs to be done? With our blocks on concurrent changes it'll take a bit more massaging...

**Comment by otan** [comment]
works after reverting #63725 so merging this one
feel free to set ADD/DROP REGION to 0 if it breaks when we unflake schemachange

bors r=ajwerner

**Pull request merged**
