### PR TITLE
kvcoord: fix error index in case of range split

### LINKED ISSUE #111481: pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test: TestCCLLogic_regional_by_row_read_committed failed
pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test.TestCCLLogic_regional_by_row_read_committed [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11981022?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11981022?buildTab=artifacts#/) on master @ [27e7c166b5591b0e05bb2fd23780309b490d7af9](https://github.com/cockroachdb/cockroach/commits/27e7c166b5591b0e05bb2fd23780309b490d7af9):

```
pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.

pkg/sql/logictest/logic.go:1556: ((*logicTest).newCluster)
	NOTICE: .StartTenant() called via implicit interface TenantControlInterface;
HINT: consider using .TenantController().StartTenant() instead.
[07:01:16] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3188/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test_/multiregion-9node-3region-3azs-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed: 11 statements
    logic.go:2576: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3188/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test_/multiregion-9node-3region-3azs-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed:180: 
        expected:
        pq: duplicate key value violates unique constraint "river_region_outlet_key"\nDETAIL: Key \(region, outlet\)=\('us-east-1', 'Salish Sea'\) already exists\.
        got:
        pq: duplicate key value got decoding error: insufficient bytes to decode uvarint value
[07:01:17] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3188/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test_/multiregion-9node-3region-3azs-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed with config multiregion-9node-3region-3azs-tenant: 32 tests, 1 failures
    logic.go:3993: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3188/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test_/multiregion-9node-3region-3azs-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed:183: error while processing
    logic.go:3993: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3188/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test_/multiregion-9node-3region-3azs-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed:183: too many errors encountered, skipping the rest of the input
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/0451cbd40094c53fa53acd1ee2497281/logTestCCLLogic_regional_by_row_read_committed239503891
--- FAIL: TestCCLLogic_regional_by_row_read_committed (29.31s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCCLLogic_regional_by_row_read_committed.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31919

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes the DistSender to set the correct error index in case an error is encountered after `divideAndSendBatchToRanges` was called recursively due to a stale range cache. In this scenario, previously we would have the error index set as if the original batch was the one right before the recursive call, which is incorrect in case that batch itself was split (e.g. because the original batch touched multiple ranges, and each sub-batch was executed in parallel). We already had the error index mapping code in place for the main code path, but we forgot to do the error index re-mapping after two recursive calls, which is now fixed.

This commit additionally pulls out the logic to set `response.positions` out of `sendPartialBatch` since there are fewer places to do that one level up.

This bug has been present for a very long time, but it seems relatively minor, so I decided to not include the release note.

Fixes: #111481.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I did briefly try the suggestion to do it in the same place where we call `br.Combine`, but that didn't work. I tried the following diff
```
--- a/pkg/kv/kvclient/kvcoord/dist_sender.go
+++ b/pkg/kv/kvclient/kvcoord/dist_sender.go
@@ -1542,6 +1542,9 @@ func (ds *DistSender) divideAndSendBatchToRanges(
                for _, responseCh := range responseChs {
                        resp := <-responseCh
                        if resp.pErr != nil {
+                               if pErr.Index != nil && pErr.Index.Index != -1 && resp.positions != nil {
+                                       pErr.Index.Index = int32(resp.positions[pErr.Index.Index])
+                               }
                                if pErr == nil {
                                        pErr = resp.pErr
                                        // Update the error's transaction with any new information from
```
To me the current fix seems less risky, so I chose to not investigate this further.

**Comment by yuzefovich** [comment]
> I did briefly try the suggestion to do it in the same place where we call `br.Combine`, but that didn't work.

That diff was missing setting `resp.positions` in one place, once added, things seem to work. Let me know which approach is preferable.

Also, the newly added test has a race on updating `RangeCache.db` field. I don't think that we want to add any synchronization around that just for the test in the production path, perhaps we could hide it behind `buildutil.CrdbTestBuild`? Any other ideas of going around that? We could also just skip the test under race.

**Review by nvb — COMMENTED** [review]
> Let me know which approach is preferable.

I like the approach that you have here.

If you wanted to take it one step further, you could remove the `positions` param from `sendPartialBatch` entirely and have the callers assign it to the response before pushing on the channel. That way, it couldn't be missed.

> Also, the newly added test has a race on updating `RangeCache.db` field. I don't think that we want to add any synchronization around that just for the test in the production path, perhaps we could hide it behind `buildutil.CrdbTestBuild`? Any other ideas of going around that? We could also just skip the test under race.

Did you consider using the `waitThenSwitchToSplitDesc` strategy that the `TestDescriptorChangeAfterRequestSubdivision` uses? I believe that avoids the need to synchronize on the `RangeCache.db` field itself.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113111#-:-Ni7cIBh-jpXUPt84uZE:bycvg5o)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
> If you wanted to take it one step further, you could remove the `positions` param from `sendPartialBatch` entirely and have the callers assign it to the response before pushing on the channel. That way, it couldn't be missed.

Nice, I like it, done.

> Did you consider using the `waitThenSwitchToSplitDesc` strategy that the `TestDescriptorChangeAfterRequestSubdivision` uses? I believe that avoids the need to synchronize on the `RangeCache.db` field itself.

Oh, indeed, that works, thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113111#-:-NiBFA_O5maKY8E5KxJy:b-gqqfef)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113111#-:-NiBRzu1ENvyiL735ZPj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Thanks a lot of the pointers and the review!

bors r+

**Pull request merged**
