### PR TITLE
raft: add counters for flow state changes

### LINKED ISSUE #136533: kvserver: add counter metric which records transitions into state snapshot
This issue is to add a counter metric which represents the number of replicas transitioning into StateSnapshot, as observed by the leader.

The issue could be extended to also include StateProbe.

Jira issue: CRDB-45108

### PR DESCRIPTION
**Pull request by pav-kv**
Resolves #136533

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

These are per-node metrics, while the ones in https://github.com/cockroachdb/cockroach/pull/137023 are per-store. I wonder whether that will be confusing. In general, we have had issues in the past with metrics that should have been per-store, being per-node, but I wonder whether this falls in that category too, or per-node is fine.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137091#-:-ODlCtfR77tc06kgw7jp:bvxjnnb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Review by pav-kv — COMMENTED** [review]
@sumeerbhola These are per-store, located [here](https://github.com/cockroachdb/cockroach/blob/28d9b53ddd918190f3f3864800c816fd38352c7b/pkg/kv/kvserver/store.go#L910).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137091#-:-ODlFPz37fQszq6M4aib:bo4l3ao)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by pav-kv** [comment]
Found one gap when manually testing this. It only measures flow state changes when we're already leader. We need to also register all things entering `StateProbe` when we become leader.

**Review by kvoli — APPROVED** [review]
:lgtm: -- may have missed another PR, were you planning on testing these, or are the basic enough that its not worth it?

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137091#-:-ODm2iLjC5I2SmCZbzyq:bgypchr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @pav-kv)

**Comment by pav-kv** [comment]
I tested this manually. Started a local cluster, then restarted a node a couple of times (leader and follower). And watched that the graphs make sense. This prompted the second commit, after which I also tested this again.

**Comment by kvoli** [comment]
SGTM -- if you're comfortable that we don't need regression testing I am too.

**Comment by pav-kv** [comment]
bors r=kvoli

**Comment by pav-kv** [comment]
bors retry

**Comment by pav-kv** [comment]
bors retry

**Comment by pav-kv** [comment]
Can't backport to `24.3` easily because the introduction of metrics in `raft` #134543 hasn't been backported.

**Comment by pav-kv** [comment]
blathers backport 24.3

**Pull request merged**
