### PR TITLE
storage: add a shuffle to the store pool's getStoreList.

### PR DESCRIPTION
**Pull request by BramGruneir**
**Describe the problem**

there was no notification that the upgrade to 21.1.0 would now report server_version as 13.0.0

**To Reproduce**

look at server variables.

**Expected behavior**

some clients restrict functionality based on postgre server version. a bump from 9.5 to 13 should at least be noted in the changelog

**Environment:**
 - CockroachDB version 21.1.0

**Additional context**
What was the impact?

not yet known

Jira issue: CRDB-7599

### CODE REVIEW

**Comment by tamird** [comment]
There is probably a reason that `kv.ReplicaSlice.randPerm()` is written the way it is. Perhaps it's time to extract that to something that takes a sort.Interface.

**Comment by BramGruneir** [comment]
Its used as part of SortByCommonAttributePrefix.  Which is a very special case and isn't required elsewhere.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWEoi_cBZHaro4x39Nj:b-h3yz5w)*

**Comment by tamird** [comment]
I can't tell if you're being glib, but I'll assume you aren't. The point I was making is that this pattern (though subtly different from the way you wrote it, probably for good reason) exists elsewhere. See also https://github.com/cockroachdb/cockroach/blob/25449d9/pkg/storage/store.go#L290:L293

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWErNiiUtY1AHE1wxvS:b-xe9j19)*

**Comment by BramGruneir** [comment]
Ah, I didn't realize what you were saying.  I thought you meant to split it into two functions, randPerm and shuffle.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/roachpb/metadata.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWEnDD_1z05kihMPlTA-r1-52:-KWExcpglnyHp22gw4kL:b9psuy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ea89987fc2f9de442e43c0f9cc3db38e663f0b8/pkg/roachpb/metadata.go#L52)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `rand.Intn(1) == 0`. The first iteration of this loop is useless which is why this is written elsewhere as:
> 
> 
> 
> ```
> 
> for i := 1; i < len(s); i++ {
> 
>   s.Swap(i, rand.Intn(i + 1))
> 
> }
> 
> ```
</details>
Ah, of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWExTI_4DtQI-hMHC7O:b8svk9i)*

**Comment by tamird** [comment]
OK; so, could you extra such a thing, please?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWEzI3NS5yuC9Xeyw5y:b3flusl)*

**Comment by BramGruneir** [comment]
yep, I'll have it ready shortly.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWF02fmOyoCiUEESzSZ:bppacy6)*

**Comment by BramGruneir** [comment]
Good for another review.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWJj3SlLhJLSUMEEm1T:bgx82p0)*

**Comment by tamird** [comment]
:lgtm: though i don't think the shuffle tests are terribly useful.

Also, (*storeReplicaVisitor).Visit() could also benefit from this method.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/shuffle/shuffle.go, line 21 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJke7Kw39UYLk9wcby:-KWJke7LaWYvc6TPhaH1:b-7yd9ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L21)):*
> ```Go
> // Interface for shuffle. When it is satisfied, a collection can be shuffled by
> // the routines in this package. The methods require that the elements of the
> // collection be enumerated by an integer index. This interface is similar to
> ```

s/enumerated/enumerable/?

---

*[pkg/util/shuffle/shuffle.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJkox2fxYREgIf2xbr:-KWJkox2fxYREgIf2xbs:b-qycfer) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L31)):*
> ```Go
> 
> // Shuffle randomizes the order of the array.
> func Shuffle(data Interface) {
> ```

can't this be implemented in terms of `between`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWJlnmMEXLySka3xPri:bhi48eu)*

**Comment by BramGruneir** [comment]
Done.

I'd rather have some tests than none and they mimic the original ones from replicaSlice. 

---

Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/util/shuffle/shuffle.go, line 21 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJke7Kw39UYLk9wcby:-KWJmhrs9wzOR0fVOczs:b-g6x2g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/enumerated/enumerable/?
</details>
hmm...

enumerate: mention one by one.

enumerable : able to be counted by one-to-one correspondence with the set of all positive integers.

I cribbed the comment from the go source for sort's interface, but I think you're right, enumerable seems more correct.  Updated.

---

*[pkg/util/shuffle/shuffle.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJkox2fxYREgIf2xbr:-KWJo3eT39JYyCCKsvkg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L31)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can't this be implemented in terms of `between`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-:-KWJo5hJMeK4qxFt32MC:b-cr6hnu)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/kv/replica_slice.go, line 121 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJzAWiQIwUP2D8ztSw:-KWJzAWiQIwUP2D8ztSx:b-ctyymn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c652737c48b299562871da52cde5396a0adcddd9/pkg/kv/replica_slice.go#L121)):*
> ```Go
> 		}
> 		if topIndex < len(rs)-1 {
> 			shuffle.Between(rs, firstNotOrdered, topIndex)
> ```

can't this be `shuffle.Shuffle(rs[firstNotOrdered:topIndex])`?

---

*[pkg/util/shuffle/shuffle.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJkox2fxYREgIf2xbr:-KWJz2AJe1eSRxsg1_Y2:b9u17bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L31)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Done.
</details>
On second thought, can't we remove `Between` entirely? It's equivalent to the caller passing a sub-slice into Shuffle. I've left a comment in the only caller that cares.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/util/shuffle/shuffle.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJkox2fxYREgIf2xbr:-KWK-HfIitwDYwUxAJcW:b-vgdhvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L31)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> On second thought, can't we remove `Between` entirely? It's equivalent to the caller passing a sub-slice into Shuffle. I've left a comment in the only caller that cares.
</details>
When you make this change, note that there's no need for the local variable `n := data.Len()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/kv/replica_slice.go, line 121 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJzAWiQIwUP2D8ztSw:-KWK7XB4kxhklLoB4XtO:bqcdzs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c652737c48b299562871da52cde5396a0adcddd9/pkg/kv/replica_slice.go#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can't this be `shuffle.Shuffle(rs[firstNotOrdered:topIndex])`?
</details>
actually yes, it can be.

---

*[pkg/util/shuffle/shuffle.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJkox2fxYREgIf2xbr:-KWK7YtaWdUDfxIqGjnn:b-uligdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L31)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> When you make this change, note that there's no need for the local variable `n := data.Len()`.
</details>
won't the for loop call data.Len() each time if we don't cache the value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607)*

**Comment by tamird** [comment]
Ah good point about the repeated calls

**Comment by BramGruneir** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/kv/replica_slice.go, line 121 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJzAWiQIwUP2D8ztSw:-KWKEwY7dGGjq56bPRnN:b-k1f461) ([raw file](https://github.com/cockroachdb/cockroach/blob/c652737c48b299562871da52cde5396a0adcddd9/pkg/kv/replica_slice.go#L121)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> actually yes, it can be.
</details>
I think it should be `shuffle.Shuffle(rs[firstNotOrdered:topIndex+1]`

---

*[pkg/util/shuffle/shuffle.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607#-KWJkox2fxYREgIf2xbr:-KWKF7LUt4VmqWvWvS9R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0899d163b8d51b8b067329ff8ccfaf78feea18bc/pkg/util/shuffle/shuffle.go#L31)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> won't the for loop call data.Len() each time if we don't cache the value?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10607)*

**Pull request merged**
