### PR TITLE
storage: Disallow stats-based rebalancing when UseVersion=1.0

### PR DESCRIPTION
**Pull request by a-robinson**

### CODE REVIEW

**Comment by tamird** [comment]
Rationale?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17695#-:-KrgM1HNTU9qwhBWLnW3:b-qfyzg3)*

**Comment by a-robinson** [comment]
Updated the commit message, thanks.

**Review by tbg — APPROVED** [review]

**Comment by tschottdorf** [comment]
(and sorry about that poorly refactored code you had to touch but hey, at least you didn't need to plumb anything! :trollface:)

**Comment by a-robinson** [comment]
Many thanks for doing all the plumbing! :)

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17695)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17695)*

**Pull request merged**
