### PR TITLE
smithcmp

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37925)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @mjibson, @rafiss, and @solongordon)

___
*[pkg/internal/sqlsmith/random.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37925#-Lg8j6Nq8Ri2Dy1JUjgC:-Lg8j4NZ-MZVJ9IYHmIo:b-g9vdi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/48fa256bd755fe080ebec299c0c7f54bdd71d5aa/pkg/internal/sqlsmith/random.go#L26)):*
> ```Go
> 
> func (s *Smither) d9() int {
> 	return s.rnd.Intn(6) + 1
> ```

probably a copypasta miss -- should be `Intn(9)`?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37925)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @rafiss, and @solongordon)

___
*[pkg/internal/sqlsmith/random.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37925#-Lg8j6Nq8Ri2Dy1JUjgC:-Lg8tK0p8h9dAYgSAgG0:b-pqwda5) ([raw file](https://github.com/cockroachdb/cockroach/blob/48fa256bd755fe080ebec299c0c7f54bdd71d5aa/pkg/internal/sqlsmith/random.go#L26)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

probably a copypasta miss -- should be `Intn(9)`?
</blockquote></details>

Good find. Done.

**Comment by mjibson** [comment]
ping anyone who wants to review this. also since it's not like actually going into cockroach a light skim is fine.

**Review by justinj — COMMENTED** [review]
:lgtm: It would be dope if we could make (some) logic tests run in this compare mode somehow.

Oops sorry! I queued up some comments last week and forgot to publish :( some of them might no longer be relevant

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37925#-:-Lg8H4uk-Dx2YgPddMS3:b-mx2oci)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @mjibson, @rafiss, and @solongordon)

___
*[pkg/internal/sqlsmith/random.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37925#-Lg8j6Nq8Ri2Dy1JUjgC:-LgXqynG6iuQLJ9CyuCT:b-ifzys3) ([raw file](https://github.com/cockroachdb/cockroach/blob/48fa256bd755fe080ebec299c0c7f54bdd71d5aa/pkg/internal/sqlsmith/random.go#L26)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Good find. Done.
</blockquote></details>

Doesn't look changed from my diff
___
*[pkg/internal/sqlsmith/sqlsmith.go, line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37925#-Lg8GcBp1OgDoey60LUK:-Lg8GcBp1OgDoey60LUL:b-df9ad9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f1899c956c4c3ffb55d2f26f9963f9e2ae8befb/pkg/internal/sqlsmith/sqlsmith.go#L193)):*
> ```Go
> type simpleDatums struct{}
> 
> func (d simpleDatums) Apply(s *Smither) {
> ```

nice, this is great
___
*[pkg/internal/sqlsmith/sqlsmith.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37925#-Lg8G9AAD2s6VWbKUfbS:-Lg8G9AB5SmzCkqLzCjL:b-t6l0ss) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f1899c956c4c3ffb55d2f26f9963f9e2ae8befb/pkg/internal/sqlsmith/sqlsmith.go#L241)):*
> ```Go
> }
> 
> // CompareMode causes the Smither to generate statements that have idempotent
> ```

nit: I feel like "idempotent" is a property of the impact on the state of world (`f(x) = f(f(x))`) rather than a property of the output of the operation. I think maybe "deterministic" might be a better word here?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37925)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @mjibson, @rafiss, and @solongordon)

___
*[pkg/internal/sqlsmith/random.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37925#-Lg8j6Nq8Ri2Dy1JUjgC:-LgZ1Gs8460R7GIDCTUE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48fa256bd755fe080ebec299c0c7f54bdd71d5aa/pkg/internal/sqlsmith/random.go#L26)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Doesn't look changed from my diff
</blockquote></details>

Done.

**Pull request merged**
