### PR TITLE
sql: implement pg_trgm without index acceleration

### PR DESCRIPTION
**Pull request by jordanlewis**
Split off from #79705.
Updates #41285.

This PR adds the builtin functions, overloads, session settings, and CREATE EXTENSION statement for `pg_trgm`. See commits for details.

This PR doesn't add any index support yet. That will be included in a different PR.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[`pkg/sql/create_extension.go` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KLuAOCcP_W0hP1Dyf:-N2KLuAOCcP_W0hP1Dyg:b-8awc0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/307a28d9cfc111c88d9be3fced5b4b004e7bf7b3/pkg/sql/create_extension.go#L47)):*
> ```Go
> 	switch n.CreateExtension.Name {
> 	case "postgis",
> 		"pg_trgm",
> ```

are you sure it's OK to do this when we still have lots of other unimplemented pg_trgm functions?
___
*[`pkg/sql/vars.go` line 2154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KK8yO7jyGwas319Hn:-N2KK8yO7jyGwas319Ho:b-vvr2dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35b848edb3f5562199b0f56bc27a6c576073d5d/pkg/sql/vars.go#L2154)):*
> ```Go
> 		for vName := range varGen {
> 			res = append(res, vName)
> 			if strings.Contains(vName, ".") {
> ```

hmmm, rather than allowing any variable with dots, i think maybe we should make an allowlist

the reason is, we need to make sure that `IsCustomOptionSessionVariable` keeps working, and that works just by looking for `.`s right now
___
*[`pkg/sql/sem/builtins/builtins.go` line 5655 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KEN7G5ddNw2Qd0e03:-N2KEN7G5ddNw2Qd0e04:bkhv4mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/sql/sem/builtins/builtins.go#L5655)):*
> ```Go
> 				return jsonNumInvertedIndexEntries(ctx, args[0])
> 			},
> 			Info:       "This function is used only by CockroachDB's developers for testing purposes.",
> ```

nit: i think we might as well make this Info field the same as the comment above: " Returns the number of distinct inverted index entries that would be generated for a value."
___
*[`pkg/sql/sem/builtins/trigram_builtins.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KFZoc2Nw8IZpgZiIm:-N2KFZoc2Nw8IZpgZiIn:b-ct4j0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/sql/sem/builtins/trigram_builtins.go#L61)):*
> ```Go
> 					}
> 				}
> 				shared := float32(nShared)
> ```

nit: since types.Float is a FLOAT8 should we use float64 here?
___
*[`pkg/sql/sem/tree/eval.go` line 1108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KLUss79LlfjWFo0fw:-N2KLUss79LlfjWFo0fx:bkbb14d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea86b7c0406621ed8cd75b59447a549340735def/pkg/sql/sem/tree/eval.go#L1108)):*
> ```Go
> 			// this as a normalization that returns the expanded predicate
> 			// 1 - (string <-> string) > pg_trgm.similarity_threshold. That way we
> 			// don't have to ship similarity_threshold across the DistSQL network.
> ```

should we do this TODO now? otherwise it might be annoying to clean up the SessionData proto later?
___
*[`pkg/util/trigram/trigram.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KGFh451gd2R4wuIgK:-N2KGFh5A6uE0JMA4a07:bcgiqg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/util/trigram/trigram.go#L26)):*
> ```Go
> func MakeTrigramsDatum(s string) tree.Datum {
> 	arr := MakeTrigrams(s, true /* pad */)
> 	ret := tree.NewDArray(types.String)
> ```

i forget: when are we supposed to use DatumAlloc?

separately, it looks like most code that uses DArrays only modifies it using `Append`; do we need that here?
___
*[`pkg/util/trigram/trigram.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KJJ2y4Z2eP9e3uY_9:-N2KJJ2y4Z2eP9e3uY_A:b-b8vzin) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/util/trigram/trigram.go#L42)):*
> ```Go
> // Words are separately trigrammed. If pad is true, the string will be padded
> // with 2 spaces at the front and 1 at the back, producing 3 extra trigrams.
> func MakeTrigrams(s string, pad bool) []string {
> ```

nit: is `pad` always passed as true?
___
*[`pkg/sql/logictest/testdata/logic_test/information_schema` line 4794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KKjED54gR9Vj3bdEV:-N2KKjED54gR9Vj3bdEW:b99go38) ([raw file](https://github.com/cockroachdb/cockroach/blob/86486f93503f774094c49e4ec7e089e30fbb6552/pkg/sql/logictest/testdata/logic_test/information_schema#L4794)):*
> ```
> parallelize_multi_key_lookup_joins_enabled            off
> password_encryption                                   scram-sha-256
> pg_trgm.similarity_threshold                          0.30000001192092896
> ```

nit: it looks weird. would it be better if the default were `"3e-1"` instead?
___
*[`pkg/sql/logictest/testdata/logic_test/trigram_builtins` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KIiXJ7Qlt5wueLyBr:-N2KIiXJ7Qlt5wueLyBs:b-kwlzs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/sql/logictest/testdata/logic_test/trigram_builtins#L2)):*
> ```
> query TTTTTT
> SELECT show_trgm(''), show_trgm('a'), show_trgm('ab'), show_trgm('abc'), show_trgm('abcd'), show_trgm(NULL)
> ```

nit: i prefer this way since it is more readable and easier to add more test cases:
```
SELECT show_trgm(str) FROM ( VALUES
   (''),
   ('a'),
   -- etc
) tbl(str)
```
___
*[`pkg/sql/logictest/testdata/logic_test/trigram_builtins` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KJrKG6q_M2qFcqvii:-N2KJrKG6q_M2qFcqvij:bgeixhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/sql/logictest/testdata/logic_test/trigram_builtins#L32)):*
> ```
> # Test the similarity builtin.
> query FFFF
> SELECT similarity('foo', 'bar'), similarity('foo', 'far'), similarity('foo', 'for'), similarity('foo', 'foo')
> ```

nit: the SELECT .. FROM .. VALUEs trick should work here too

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/create_extension.go` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KLuAOCcP_W0hP1Dyf:-N2MS2CJBKcsH3dxc3yC:b-76u4j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/307a28d9cfc111c88d9be3fced5b4b004e7bf7b3/pkg/sql/create_extension.go#L47)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

are you sure it's OK to do this when we still have lots of other unimplemented pg_trgm functions?
</blockquote></details>

I think it's fine, yeah - from a client's perspective, it moves an error when doing CREATE EXTENSION to an error when doing an unimplemented function. I don't see a problem with it. Do you?
___
*[`pkg/sql/vars.go` line 2154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KK8yO7jyGwas319Hn:-N2MhPCyA_-7hTKfUmj_:bpu6lrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35b848edb3f5562199b0f56bc27a6c576073d5d/pkg/sql/vars.go#L2154)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmmm, rather than allowing any variable with dots, i think maybe we should make an allowlist

the reason is, we need to make sure that `IsCustomOptionSessionVariable` keeps working, and that works just by looking for `.`s right now
</blockquote></details>

Discussed offline, this is fine as is.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5655 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KEN7G5ddNw2Qd0e03:-N2MTM4V1u7d3F3bCIom:b191pr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/sql/sem/builtins/builtins.go#L5655)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think we might as well make this Info field the same as the comment above: " Returns the number of distinct inverted index entries that would be generated for a value."
</blockquote></details>

I was just copying the text that's used in all of the other ones. I'll make a separate commit for it.
___
*[`pkg/sql/sem/builtins/trigram_builtins.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KFZoc2Nw8IZpgZiIm:-N2MTF6XCtzWHpY_vCNh:b-96t6xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/sql/sem/builtins/trigram_builtins.go#L61)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: since types.Float is a FLOAT8 should we use float64 here?
</blockquote></details>

I was copying what Postgres does and that's float32, but yeah, I guess there's no harm in making it a float64, fixed.
___
*[`pkg/sql/sem/tree/eval.go` line 1108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KLUss79LlfjWFo0fw:-N2MTyVeCtp2wHEiJRoT:bv29fhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea86b7c0406621ed8cd75b59447a549340735def/pkg/sql/sem/tree/eval.go#L1108)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we do this TODO now? otherwise it might be annoying to clean up the SessionData proto later?
</blockquote></details>

I should have just removed this TODO - I decided against this idea because it's quite difficult to make it work. Also, it's low cost to add more fields to SessionData - we already have many of them. And it is not hard to clean up SessionData.

I've updated the TODO to sound less scary, and moved it to a better spot.
___
*[`pkg/util/trigram/trigram.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KGFh451gd2R4wuIgK:-N2Mf6o-6Kq2hK-9FRbB:b-g8to8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/util/trigram/trigram.go#L26)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i forget: when are we supposed to use DatumAlloc?

separately, it looks like most code that uses DArrays only modifies it using `Append`; do we need that here?
</blockquote></details>

DatumAlloc isn't usable from builtins I don't think. Good point about Append, fixed.
___
*[`pkg/util/trigram/trigram.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KJJ2y4Z2eP9e3uY_9:-N2MUvtI8dYMjio3Mqmu:bx9tcaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/util/trigram/trigram.go#L42)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: is `pad` always passed as true?
</blockquote></details>

It is, but it won't be forever, there are some functions that will pass false (the other builtins that I didn't implement yet, that are also less popular), so I'll leave it for now.
___
*[`pkg/sql/logictest/testdata/logic_test/information_schema` line 4794 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KKjED54gR9Vj3bdEV:-N2MVQ79-uAaQe9sDqx1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/86486f93503f774094c49e4ec7e089e30fbb6552/pkg/sql/logictest/testdata/logic_test/information_schema#L4794)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it looks weird. would it be better if the default were `"3e-1"` instead?
</blockquote></details>

Done
___
*[`pkg/sql/logictest/testdata/logic_test/trigram_builtins` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KIiXJ7Qlt5wueLyBr:-N2MVgUx-4eHDhIHvTyR:bagrtdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/08cec49a883b0ac1575ea683ca026c6f63d113c6/pkg/sql/logictest/testdata/logic_test/trigram_builtins#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i prefer this way since it is more readable and easier to add more test cases:
```
SELECT show_trgm(str) FROM ( VALUES
   (''),
   ('a'),
   -- etc
) tbl(str)
```
</blockquote></details>

Nice suggestion!

**Comment by jordanlewis** [comment]
RFAL 👼

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @jordanlewis, and @rafiss)

___
*[`pkg/sql/vars.go` line 1246 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2U7Di17O-jiAcDsumJ:-N2U7Di17O-jiAcDsumK:bf9h3fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c2fca155941b0e411ad82a0f63f06869e070c5b/pkg/sql/vars.go#L1246)):*
> ```Go
> 		// initialization loop with the planner.
> 		GlobalDefault: func(sv *settings.Values) string {
> 			return ".3"
> ```

curious how `0.3` was chosen, copied from postgres I assume? :)

**Comment by jordanlewis** [comment]
> curious how 0.3 was chosen, copied from postgres I assume? :)
Correct, heh. :)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r5, 9 of 9 files at r6, 10 of 10 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-:-N2d9jsb7Wn54cOS0T-n:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81418)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[`pkg/sql/create_extension.go` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KLuAOCcP_W0hP1Dyf:-N35r26r5VVE_bi5ENE5:bq0ml81) ([raw file](https://github.com/cockroachdb/cockroach/blob/307a28d9cfc111c88d9be3fced5b4b004e7bf7b3/pkg/sql/create_extension.go#L47)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it's fine, yeah - from a client's perspective, it moves an error when doing CREATE EXTENSION to an error when doing an unimplemented function. I don't see a problem with it. Do you?
</blockquote></details>

sounds fine
___
*[`pkg/sql/sem/tree/eval.go` line 1108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KLUss79LlfjWFo0fw:-N35vJgE3vSBw-XhO8Rt:b-v0kbsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea86b7c0406621ed8cd75b59447a549340735def/pkg/sql/sem/tree/eval.go#L1108)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I should have just removed this TODO - I decided against this idea because it's quite difficult to make it work. Also, it's low cost to add more fields to SessionData - we already have many of them. And it is not hard to clean up SessionData.

I've updated the TODO to sound less scary, and moved it to a better spot.
</blockquote></details>

i didn't see where this got moved to

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81418)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[`pkg/sql/sem/tree/eval.go` line 1108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81418#-N2KLUss79LlfjWFo0fw:-N35xmEb2KErApWGt38e:bd9ujza) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea86b7c0406621ed8cd75b59447a549340735def/pkg/sql/sem/tree/eval.go#L1108)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i didn't see where this got moved to
</blockquote></details>

Moved to /sem/eval/binary_op.go

**Pull request merged**
