### PR TITLE
sql, opt: interface between sql and opt for plan execution

### PR DESCRIPTION
**Pull request by RaduBerinde**
We want to be able to convert an optimizer expression to a planNode
tree (for testing).

This commit proposes an abstract interface that is implemented by sql
and is used by opt to generate planNode trees. Currently only (full)
table scans are supported.

The Executor implements the top-level interface, with all the relevant
code in a separate file.

Renaming opt test directive `exec` to `exec-raw`; adding `exec`
directive which uses the new interface to execute a plan.

I will look into adding an Explain function so we can see the details
of the generated plan as well.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-:-L2X99ey2jelrleM1YfH:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2XfaNdo-jpgZN3YYTb:-L2XfaNdo-jpgZN3YYTc:brnpiuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/executor_opt_interface.go#L47)):*
> ```Go
> 
> // Scan is part of the opt.ExecBuilder interface.
> func (eb *execBuilder) Scan(table optbase.Table) (opt.ExecNode, error) {
> ```

This wasn't too bad. It will be interesting to see what passing in index constraints will look like. 

---

*[pkg/sql/opt/exec.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2XgVhSnF1qJJzaTSBj:-L2XgVhSnF1qJJzaTSBk:bnrbjx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/opt/exec.go#L27)):*
> ```Go
> type ExecNode interface {
> 	// Run() executes the plan and returns the results as a Datum table.
> 	Run() ([]tree.Datums, error)
> ```

It's sort of strange that `ExecNode` has a `Run()` method. When you add another operator that takes an `ExecNode` as input you'll have to extract the `planNode`. For example:

```
type ExecBuilder interface {
  Project(input ExecNode, columns ...)
}
```

---

*[pkg/sql/opt/exec.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2Xh9YYZtXH-BOVm5MW:-L2Xh9YYZtXH-BOVm5MX:bblygwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/opt/exec.go#L34)):*
> ```Go
> type ExecBuilder interface {
> 	// Scan returns an ExecNode that represents a scan of the given table.
> 	// TODO(radu): support list of columns, index, index constraints
> ```

Have you thought about how we'll identify columns for the builder? We'll want to be passing column indexes to the builder because that's what we have in scalar expressions. But the builder needs to be able to map those back to outputs from relations and columns in tables. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2XfaNdo-jpgZN3YYTb:-L2XkKrDCxvxSnFNkOxy:baorjzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/executor_opt_interface.go#L47)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This wasn't too bad. It will be interesting to see what passing in index constraints will look like. 
</blockquote></details>

I plan to pass `LogicalSpans` (`sql` already knows how to convert those).

---

*[pkg/sql/opt/exec.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2XgVhSnF1qJJzaTSBj:-L2Xk8i5I1hh2nI0ON7m:b8clmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/opt/exec.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It's sort of strange that `ExecNode` has a `Run()` method. When you add another operator that takes an `ExecNode` as input you'll have to extract the `planNode`. For example:

```
type ExecBuilder interface {
  Project(input ExecNode, columns ...)
}
```
</blockquote></details>

Yeah, passing `ExecNode`s was my plan.

Not sure what alternative to `Run` you are suggesting. Having a separate `Run` API in some other interface? (it's more or less the same thing no?)

---

*[pkg/sql/opt/exec.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2Xh9YYZtXH-BOVm5MW:-L2Xkk3ouWL2Y4LTKgch:b-xn389x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/opt/exec.go#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Have you thought about how we'll identify columns for the builder? We'll want to be passing column indexes to the builder because that's what we have in scalar expressions. But the builder needs to be able to map those back to outputs from relations and columns in tables. 
</blockquote></details>

I'm thinking a list of `optbase.Column`s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by petermattis** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2XgVhSnF1qJJzaTSBj:-L2_Nidd3Z35q_nGx42M:b-2115l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/opt/exec.go#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, passing `ExecNode`s was my plan.

Not sure what alternative to `Run` you are suggesting. Having a separate `Run` API in some other interface? (it's more or less the same thing no?)
</blockquote></details>

I didn't have a suggestion, just pointing out that it is a bit odd. Seems fine for now. 

---

*[pkg/sql/opt/exec.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2Xh9YYZtXH-BOVm5MW:-L2_Nor93gkHSAaCe-fx:b-6h4rze) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/opt/exec.go#L34)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm thinking a list of `optbase.Column`s.
</blockquote></details>

For a list of columns that works. Won't we need something else for scalar expressions which will contain the equivalent of `IndexedVar`? Or perhaps they will contain `IndexedVar`. I'm sure you've thought about this more than I have.

---

*[pkg/sql/opt/opt_test.go, line 405 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2_fTR5XFuY89kZDUrK:-L2_fTR5XFuY89kZDUrL:b7djb4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4b5a057d31b36a8c85d140a5a7f9130cffa459/pkg/sql/opt/opt_test.go#L405)):*
> ```Go
> 						}
> 
> 					case "exec-raw":
> ```

`exec-raw` might be confused with `exec`. Perhaps `define`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2Xh9YYZtXH-BOVm5MW:-L2_gsC_wzR3mNJNBmU8:bkixt1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e4498be705d158e051b8e13ec53e6348345d2/pkg/sql/opt/exec.go#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

For a list of columns that works. Won't we need something else for scalar expressions which will contain the equivalent of `IndexedVar`? Or perhaps they will contain `IndexedVar`. I'm sure you've thought about this more than I have.
</blockquote></details>

Not sure yet.. My plan is to try to make them `IndexedVar`s, we'll see how it works out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/opt_test.go, line 405 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2_fTR5XFuY89kZDUrK:-L2_gMVrUH_Li6VTkVUS:b-juvkvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4b5a057d31b36a8c85d140a5a7f9130cffa459/pkg/sql/opt/opt_test.go#L405)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`exec-raw` might be confused with `exec`. Perhaps `define`.
</blockquote></details>

Hm, I don't see how `define` applies. This executes a statement against the database, it can be anything (e.g. the test file has INSERT statements).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by petermattis** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/opt_test.go, line 405 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2_fTR5XFuY89kZDUrK:-L2_hYMIEJmF1Zp-v6Gz:b4meq4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4b5a057d31b36a8c85d140a5a7f9130cffa459/pkg/sql/opt/opt_test.go#L405)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, I don't see how `define` applies. This executes a statement against the database, it can be anything (e.g. the test file has INSERT statements).
</blockquote></details>

Oh, I get confused at times and was still thinking this was similar to the `opttoy/v3` exec. Which it isn't. Still not fond of the name, but `define` definitely doesn't make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec.go, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2X8hGsGwKWQI0uB9wo-r3-32:-L2aeBVofULAvZQOhgQB:bmyw9rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4b5a057d31b36a8c85d140a5a7f9130cffa459/pkg/sql/opt/exec.go#L32)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I called this pattern "Factory" rather than "Builder" in v4. The "factory" was the thing that actually built the expressions (and had methods like ConstructScan, ConstructInnerJoin, etc). The "builder" was the thing that _directed_ the building of expressions (the caller of the factory). I'm OK with using different terminology, but want us to be consistent. So we should agree on what to call each pattern, and then change one or the other places to use the same name as the other.
</blockquote></details>

Your naming makes more sense. I will switch to that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec.go, line 35 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2X8hGsGwKWQI0uB9wo-r3-35:-L2aeETPmMlAAjEwcyFk:bewa14p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4b5a057d31b36a8c85d140a5a7f9130cffa459/pkg/sql/opt/exec.go#L35)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In what circumstances would this return an error?
</blockquote></details>

There's a big class of errors that we don't expect to ever happen, but we prefer errors to panics when possible (if we have a bug, it's better to fail just that odd query). In this case, there are legitimate errors too, e.g. no SELECT privilege on the table.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec.go, line 39 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2X8hGsGwKWQI0uB9wo-r3-39:-L2aeb_GjNLuwDACSzEK:brmlzr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4b5a057d31b36a8c85d140a5a7f9130cffa459/pkg/sql/opt/exec.go#L39)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why have an interface here? Why not just have callers create the concrete builder directly using a New method?
</blockquote></details>

The code to create a builder is in `sql`; `opt` can't depend on `sql` and we want to use this from opt_test. We could move `opt_test.go` to `opt_test` package but it might get annoying if we need unexported fields in the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec.go, line 39 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391#-L2X8hGsGwKWQI0uB9wo-r3-39:-L2ag5Fe2pEyzBYsB9sU:b-ozqimb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb4b5a057d31b36a8c85d140a5a7f9130cffa459/pkg/sql/opt/exec.go#L39)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The code to create a builder is in `sql`; `opt` can't depend on `sql` and we want to use this from opt_test. We could move `opt_test.go` to `opt_test` package but it might get annoying if we need unexported fields in the test.
</blockquote></details>

Another alternative is to change the API a bit, and have an API in the ExecFactory to generate a "context" for a plan (the sql state needed by the planner), and pass that in as an arg to construct functions. So then we would have a singleton ExecFactory, we wouldn't create one for each query we run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21391)*

**Comment by RaduBerinde** [comment]
Opened PR #21403, I think it addresses your comments.

**Pull request merged**
