### PR TITLE
release-2.0: sql: improve PG compatibility to support pgweb unit tests

### PR DESCRIPTION
**Pull request by nvb**
Cherry-pick of #23370.

### CODE REVIEW

**Review by vilterp — APPROVED** [review]

**Comment by davestgermain** [comment]
Is this change available in v2.0-beta.20180319? 
I'm running that beta, but pgweb v0.9.11 fails with "pq: unknown function: has_schema_privilege()"

**Comment by nvanbenschoten** [comment]
The change that actually added support for pgweb was moved to our release branch in https://github.com/cockroachdb/cockroach/pull/23839. This was not included in the beta you're using but will be included in the [beta](https://github.com/cockroachdb/cockroach/issues/24032) that's being released early next week.

**Comment by davestgermain** [comment]
Thanks. You may want to correct the release notes: https://www.cockroachlabs.com/docs/releases/v2.0-beta.20180319.html

**Comment by nvanbenschoten** [comment]
Good catch! I just opened https://github.com/cockroachdb/docs/pull/2755 to address this.

**Pull request merged**
