### PR TITLE
README: explaining how to run tests

### PR DESCRIPTION
**Pull request by nanduu04**
Previously only visual regression tests docs were written

Added docs for e2e cypress tests describing steps to run and add new e2e tests

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63322)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nanduu04)

___
*[pkg/ui/cypress/README.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63322#-MXm_I5g-eHkt1xoyY9V:-MXm_I5g-eHkt1xoyY9W:b33fhga) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20a2258d9d0b72c24f60a61b0e9b093ff446a77/pkg/ui/cypress/README.md#L13)):*
> ```Markdown
> 
> ```
> yarn cypress:run-visual-regression
> ```

Can you check and see if these tests still work? If not, maybe just mention that these are broken for now and will be addressed later.
___
*[pkg/ui/cypress/README.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63322#-MXmQyxO9T1uPsS-2CYJ:-MXmQyxO9T1uPsS-2CYK:b-2xfkoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20a2258d9d0b72c24f60a61b0e9b093ff446a77/pkg/ui/cypress/README.md#L34)):*
> ```Markdown
> ### Option 1: Makefile
> 
> This command will install cypress, run the admin-cli command to create the test user, and open cypress
> ```

The `admin-cli` command is CockroachCloud thing that's not needed here.
___
*[pkg/ui/cypress/README.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63322#-MXmZvj67Yz3S2P2i7UZ:-MXmZvj67Yz3S2P2i7U_:bbcqec8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20a2258d9d0b72c24f60a61b0e9b093ff446a77/pkg/ui/cypress/README.md#L42)):*
> ```Markdown
> ### Option 2: Manual process
> 
> If this is your first time running Cypress, install it and dependencies:
> ```

Can you check these steps, I think someone would need to run `yarn` inside `pkg/ui/opt` to install Cypress specifically.

you can test by deleting the `node_modules` directories in `pkg/ui` and `pkg/ui/opt` and check which steps are required.

**Review by nanduu04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63322)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ui/cypress/README.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63322#-MXm_I5g-eHkt1xoyY9V:-MXmd2a21YTE6gW4DI06:b-i4upmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20a2258d9d0b72c24f60a61b0e9b093ff446a77/pkg/ui/cypress/README.md#L13)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you check and see if these tests still work? If not, maybe just mention that these are broken for now and will be addressed later.
</blockquote></details>

Tests do run but they all fail. Something to be adressed later
___
*[pkg/ui/cypress/README.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63322#-MXmQyxO9T1uPsS-2CYJ:-MXmd9R1C6PoRhOdYQa_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20a2258d9d0b72c24f60a61b0e9b093ff446a77/pkg/ui/cypress/README.md#L34)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

The `admin-cli` command is CockroachCloud thing that's not needed here.
</blockquote></details>

Done
___
*[pkg/ui/cypress/README.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63322#-MXmZvj67Yz3S2P2i7UZ:-MXmdANU1w2W-XM4QZ-u:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20a2258d9d0b72c24f60a61b0e9b093ff446a77/pkg/ui/cypress/README.md#L42)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you check these steps, I think someone would need to run `yarn` inside `pkg/ui/opt` to install Cypress specifically.

you can test by deleting the `node_modules` directories in `pkg/ui` and `pkg/ui/opt` and check which steps are required.
</blockquote></details>

Fixed

**Review by dhartunian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63322)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Pull request merged**
