### PR TITLE
cli: add health check to haproxy

### LINKED ISSUE #14071: stability: requests sent via haproxy can return EOF if a node is down?
In a 6-node cluster, when one of the nodes is down, when a client connects to haproxy after the cluster being started I periodically see the SQL connection being closed. I'm speculating that this is because haproxy tried to connect to the down node. This is using the following haproxy config:

```
global
  maxconn 4096
  pidfile /tmp/cockroach-loadbalancer.pid

defaults
    mode                tcp
    log                 global
    option              dontlognull
    retries             2
    timeout connect     10s
    timeout client      5s
    timeout server      2m
    maxconn             4096

listen psql
    bind 0.0.0.0:27183
    mode tcp
    balance roundrobin
    server cockroach1 cockroach-denim-0001:26257
    server cockroach2 cockroach-denim-0002:26257
    server cockroach3 cockroach-denim-0003:26257
    server cockroach4 cockroach-denim-0004:26257
    server cockroach5 cockroach-denim-0005:26257
    server cockroach6 cockroach-denim-0006:26257
```

When opening a new connection to haproxy, I would expect it to retry a backend connection if no bytes have been sent on it. Perhaps I'm misunderstanding what is happening. When all 6 nodes are up, the problem does not occur. Are we missing some haproxy configuration?

### PR DESCRIPTION
**Pull request by mberhault**
This enables health checks on the server.
Defaults with this config are tcp-level checks with:
* interval: 2s
* rise (num successful checks before considering UP): 2
* fall (num failed checks before considering DOWN): 3

Fixes #14071

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14624)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM 🐶

**Comment by mberhault** [comment]
ugh. how do we kick `licence/cla`? is a re-push the only way?

**Comment by petermattis** [comment]
What sort of health check does haproxy perform on TCP connections?

**Comment by mberhault** [comment]
it just checks for `syn/ack` from the server. This of course doesn't tell you if the process is healthy, but hitting `/health` requires knowing the http port which I believe we don't include in the nodes list.

**Comment by asubiotto** [comment]
Would it make sense to add sql-level health checks instead?

**Comment by petermattis** [comment]
> it just checks for syn/ack from the server.

Ok, so haproxy won't send data on the connection until the connection is established? That should be sufficient.

**Comment by mberhault** [comment]
sql level health checks would require haproxy to have working certs as well, that makes it tricker to have a plug-and-play generated config.
This is also meant to be a minimal config file, not a fully-tweaked one.

**Comment by tamird** [comment]
@mberhault kicked it for you. It's at https://cla-assistant.io/ FWIW.

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by mberhault** [comment]
@sploiselle: the generated haproxy config will now have a "check" at the end of each server line.
eg:
```
  server <blah> <blah> check
```

**Pull request merged**
