### PR TITLE
sql: move function privilege check to execution time

### PR DESCRIPTION
**Pull request by RaduBerinde**
Addressing this old TODO, as this planning-time check is problematic
from a plan-caching perspective.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/sql/sem/tree/eval.go, line 3579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34312#-LXM-HkF8nQcDl41AF5d:-LXM-HkF8nQcDl41AF5e:b-a3fue1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7fd528859b7e6b614f7ff93ff75f727604e4b8f/pkg/sql/sem/tree/eval.go#L3579)):*
> ```Go
> 	// Check that the built-in is allowed for the current user.
> 	if expr.fnProps.Privileged && ctx.SessionData.User != security.RootUser {
> 		return nil, errors.Wrapf(errInsufficientPriv, "%s()", expr.Func.String())
> ```

I don't love this because it gets evaluated once per row. We'd really like to avoid unnecessary once per row computation in things like scalar expressions.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/sem/tree/eval.go, line 3579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34312#-LXM-HkF8nQcDl41AF5d:-LXMC2RRERS3CNMo1B97:bsxp2et) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7fd528859b7e6b614f7ff93ff75f727604e4b8f/pkg/sql/sem/tree/eval.go#L3579)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't love this because it gets evaluated once per row. We'd really like to avoid unnecessary once per row computation in things like scalar expressions.
</blockquote></details>

I pushed this check down into the respective `Fn` implementations, and removed the `Privileged` flag altogether.

**Review by jordanlewis — COMMENTED** [review]
:lgtm:, I did like that privileged "property" because it was more DRY, but if you don't see a way to preserve that easily then I'm okay with this. I do find it a bit unfortunate that we have no plan-time way of doing this, but it's not that big of a deal as we seem to only have a couple of these privileged builtins to speak of anyway. 

Perhaps we could make some kind of privilege checking hook that planning populateS? I assume the problem is that at plan time you're not allowed to check which user it is, because it would break the cache? Could we instantiate some hooks or is that even grosser than this already is?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34312#-:-LXMDNaH7nD71pFLNXIc:bux6r5e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by RaduBerinde** [comment]
Given that we're talking about a couple special functions, I don't think building any kind of new infrastructure just for this is worth it. Frankly I prefer having no `Privileged` field because I don't have to look through the code to figure out how it is used exactly.

> I assume the problem is that at plan time you're not allowed to check which user it is, because it would break the cache?

Yes, a non-root user would use a memo cached by the root user and would be able to run it.

**Review by jordanlewis — COMMENTED** [review]
Agreed that it's not too big of a deal since we're just talking about a couple of special builtins.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34312#-:-LXMNLsv5zSu8tonizKw:b3rebtc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — APPROVED** [review]
:lgtm: because 

1) the only privileged functions are in `crdb_internal` which we officially don't care about.
2) it's actually unlikely we'll ever have a built-in function that's both privileged _and_ in common use. If it's in common use in SQL queries, by definition it can't be privileged. I can't see a SQL engine providing "common functionality" that's restricted to a few users only.

Thanks for that insight, I hadn't thought about it before.

> Reviewed 3 of 25 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34312#-:-LXNz7tB9CvVz6EmNaO-:b-kyjwh2)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @knz)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
