### PR TITLE
sqlbase: rename multirowfetcher to rowfetcher

### PR DESCRIPTION
**Pull request by jordanlewis**
There's only one row fetcher: the multi row fetcher. I don't see a strong reason why it should have a long name.

### CODE REVIEW

**Comment by jordanlewis** [comment]
I debated not sending this because it's just churn, but then I accidentally wiped my local `cockroach-data` directory with the 100 warehouse TPCC dataset while running the global rename. So now I have to send it because sunk cost fallacy something something.

**Comment by BramGruneir** [comment]
Big fan of this rename.  :lgtm: 

---

Reviewed 16 of 18 files at r1.
Review status: 14 of 16 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21555#-:-L3A9vjHyQu9oAcJFBRE:b-3x7n75)*

**Comment by BramGruneir** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21555)*

**Comment by jordanlewis** [comment]
TFTR

**Pull request merged**
