### PR TITLE
sql: properly synchronize the internal executor iterator

### LINKED ISSUE #62415: sql: crdb_internal.jobs cannot be safely joined with other tables
**Describe the problem**

This seems like a major regression. This works on 20.2.6. I don't understand the source of concurrency. This query does some crazy stuff down here: https://github.com/cockroachdb/cockroach/blob/0796cbcd0493220e88982beebd45b9a077b713e9/pkg/sql/delegate/show_jobs.go#L63-L71. 

The root of the problem is that we have this streaming iterator thing which we kick off underneath a virtual plan node. That thing, however, concurrently uses the same transaction as we use elsewhere. This leads to problems. The below query is just one example. There are plenty of other examples. 

```
demo@127.0.0.1:39361/movr> SHOW JOBS WHEN COMPLETE SELECT job_id FROM [SHOW JOBS] WHERE job_type = 'SCHEMA CHANGE GC' AND  description like '%idx1%' ;
ERROR: internal error: crdb-internal-jobs-table: concurrent txn use detected. ba: Get [/Table/3/1/15/2/1,/Min), [txn: fcfa4280], [can-forward-ts]
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:73: SendLocked()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:46: SendLocked()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:126: SendLocked()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:267: sendLockedWithRefreshAttempts()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:202: SendLocked()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:253: SendLocked()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:105: SendLocked()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:171: SendLocked()
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:503: Send()
github.com/cockroachdb/cockroach/pkg/kv/db.go:808: sendUsingSender()
github.com/cockroachdb/cockroach/pkg/kv/txn.go:936: Send()
github.com/cockroachdb/cockroach/pkg/kv/db.go:719: sendAndFill()
github.com/cockroachdb/cockroach/pkg/kv/txn.go:607: Run()
github.com/cockroachdb/cockroach/pkg/kv/txn.go:374: Get()
github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:414: getDescriptorByID()
github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:519: GetMutableDescriptorByID()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:370: getDescriptorFromStore()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:553: getObjectByName()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:602: getTableByName()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:586: GetImmutableTableByName()
github.com/cockroachdb/cockroach/pkg/sql/catalog/accessors/logical_schema_accessors.go:177: GetObjectDesc()
github.com/cockroachdb/cockroach/pkg/sql/resolver.go:197: LookupObject()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/name_resolution.go:334: ResolveExisting()
github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:156: ResolveExistingObject()
github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:93: ResolveExistingTableObject()
github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:205: ResolveDataSource()
github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:284: CheckDependencies()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:296: IsStale()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:477: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:194: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:937: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:818: dispatchToExecutionEngine()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.
```

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: fix an edge case in the internal executor**

`SetColumns` contract allows for the argument to be nil, yet the
iterator of the streaming internal executor expects that column schema,
if set, is non-nil. I don't think this could happen in practice, but
theoretically previously we could encounter an assertion error due to
none of the four fields in `ieIteratorResult` object being non-nil, and
now this is fixed.

Release note: None

**sql: add context to IncrementRowsAffected interface**

Release note: None

**sql: properly synchronize the internal executor iterator**

We recently merged an update to the internal executor to make it
streaming. Currently it is implemented by having two goroutines (the
iterator, "the consumer"; and the connExecutor, "the producer"). The
communication between them is done on the buffered channel. As a result,
both goroutines can run concurrently.

However, a crucial point was overlooked - our `kv.Txn`s cannot be used
concurrently. Imagine a plan that reads from two tables each of which is
populated via the internal executor: if we read from the first, and then
from the second concurrently, we will have the concurrent usage of the
txn for that plan.

This commit the problem by carving out a new abstraction to optionally
synchronize the execution of the internal executor with its corresponding
iterator. The abstraction comes in sync and async flavors. In the sync
form, the ieResultChannel ensures that the reader and writer do not
concurrently operate, and, additionally provides a mechanism whereby the
reader may ensure that the writer observes an error when its attempts to
publish the previous row returns. This last point is critical to ensure
that transactions are not erroneously used after it has become unsafe.

The async flavor is still used by the internal executor when it doesn't
return an iterator directly and executes the query to completion itself.

Fixes: #62415.

Release note: None (no stable release with this bug).

### CODE REVIEW

**Comment by yuzefovich** [comment]
Andrew, this solution almost works, but it doesn't work well with the vectorized engine where we use the context cancellation to shut everything down. For one of the queries mentioned in the issue we have the following plan:
```
demo@127.0.0.1:26257/defaultdb> explain SHOW JOBS WHEN COMPLETE SELECT job_id FROM [SHOW JOBS] WHERE job_type = 'SCHEMA CHANGE GC' AND  description like '%idx1%' ;
                                                                              info
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • render
  │
  └── • hash join (semi)
      │ equality: (job_id) = (job_id)
      │
      ├── • filter
      │   │
      │   └── • virtual table
      │         table: jobs@primary
      │
      └── • render
          │
          └── • filter
              └── • virtual table
                    table: jobs@primary
```
When performing hash join on the empty cluster, the right side will be empty, and as a result, we will short-circuit the execution of the whole query without reading anything from the left side of the join. The whole query then shuts down which cancels the context. However, the left side has a connExecutor goroutine running the virtual table, and it will still proceed to fully execute the read, but that read will encounter a context cancellation error at the distSender level. Which makes the whole txn to be in a non-retriable state, and the whole query errors out.

I'm not quite sure what to do here.
- removing the optimization in the hash joiner might not be sufficient (possibly we might have some other edge cases elsewhere)
- refactoring the vectorized engine to use some other method of shutting everything down will be too invasive at this point
- ideally, we wouldn't have to fully drain the data channel in `rowsIterator.Close`. I actually have a TODO for this and was looking into addressing it a few weeks ago, but I got distracted. I guess I gotta get back to it.

I'm curious whether you have some insights here.

**Comment by ajwerner** [comment]
Huh, if the right side is empty than the query should just return no rows, right? I don't think I've fully digested what you're saying. When does the context plumbed into the virtual table get canceled?

**Comment by yuzefovich** [comment]
Yes, the query will return no rows, but the way the cleanup of the virtual table on the left currently works is that the left scan will still proceed until the very end because we don't have a way to stop the connExecutor from executing the query to completion. I originally removed some parts of the plan which probably made it confusing, so I put them back in. The table is not empty itself, everything is filtered out.

I'm currently trying to plumb the shutdown of query execution of the left side when the iterator for it is closed. We'll see whether the hack at least works.

**Comment by yuzefovich** [comment]
Sorry, didn't answer your question - the context is canceled right before returning from the main query. The main query is ready to return no rows, but during the shutdown of the vectorized infrastructure, we cancel the context of the vectorized flow; then, after the vectorized infra is cleaned up, we call `cleanup` on `virtualTableNode`,  there we will call `rowsIterator.Close` which fully drains the data channel and the corresponding connExecutor goroutine executes the left side till completion. This is where the txn gets into the non-retriable error state.

**Comment by yuzefovich** [comment]
Just added another commit as a prototype, but it didn't work :/ Possibly I screwed something up though.

**Comment by yuzefovich** [comment]
Hm, possibly my understanding of the situation is wrong too because the error (`aborted during DistSender.Send: context canceled`) occurs when `Start`ing the table reader (presumably from the left side). I would expect it to happen before the corresponding `rowsIterator` is returned.

Oh, while typing it out I realized that I might see the problem - `SetColumns` is called before the query execution starts (I think).

**Comment by yuzefovich** [comment]
Yeah, that was it, apologies for panicking too early. At least the couple of queries in the issue now work. I'll polish up the PR tomorrow for review.

However, I'm still concerned about the scenario I typed up above about the way the vectorized flows are shutdown. Possibly we might never actually run into such case, but I don't know all the details of how context cancellation might affect things. One example that comes to my mind is with the changefeeds (some details [here](https://github.com/cockroachdb/cockroach/issues/55408#issuecomment-712350540)).

**Review by ajwerner — COMMENTED** [review]
I'm not concerned about changefeeds and the internal executor. We could add some defensive checks to not execute sinkless changefeeds on an internal executor but I doubt it will happen. 

This wasn't too bad

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MWfKWw7DVih3PSKwWqd:bmtcroq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/conn_executor_internal_test.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MWfLAEr6PUjl9wxeimK:-MWfLAEr6PUjl9wxeimL:b-q11snk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d77c08ae35760f256032e1519e400d6897f68ee/pkg/sql/conn_executor_internal_test.go#L305)):*
> ```Go
> 		},
> 		dataCh: dataCh,
> 		waitCh: waitCh,
> ```

just pass a closed waitCh?
___
*[pkg/sql/internal.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MWfMt9W2_3XPV3N6F9k:-MWfMt9W2_3XPV3N6F9l:bsstxof) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d77c08ae35760f256032e1519e400d6897f68ee/pkg/sql/internal.go#L294)):*
> ```Go
> 	}()
> 
> 	// TODO(yuzefovich): de-duplicate this with the code below.
> ```

I believe in your ability to make a closure
___
*[pkg/sql/internal.go, line 811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MWfMm5Y60lrdye5oKLt:-MWfMm5Y60lrdye5oKLu:b-3g7uno) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d77c08ae35760f256032e1519e400d6897f68ee/pkg/sql/internal.go#L811)):*
> ```Go
> 	// the first object is sent on the data channel.
> 	first, ok := <-dataCh
> 	if ok && first.cols != nil {
> ```

can you explain this part to me?

**Review by yuzefovich — COMMENTED** [review]
I mentioned changefeeds as an example of when the way of shutting down the vectorized flows (by context cancellation) interferes with some other features. (I didn't mean that the work we're doing here will affect the changefeeds.) In general I'm still concerned about the correctness.

Also, the CI seems to be unhappy, and in particular `TestShowJobWhenComplete/show_jobs` currently fails easily (often, but not every time). I wonder whether you have some ideas of what we're missing because I don't see what we're doing wrong :/

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MWg2_M86yk0FnXLUeGp:b-elsxsy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/conn_executor_internal_test.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MWfLAEr6PUjl9wxeimK:-MWg1Igu0GwlBgVybDb7:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d77c08ae35760f256032e1519e400d6897f68ee/pkg/sql/conn_executor_internal_test.go#L305)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

just pass a closed waitCh?
</blockquote></details>

Good point, done.
___
*[pkg/sql/internal.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MWfMt9W2_3XPV3N6F9k:-MWg1TcfAAR3ArvVe30u:by3349j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d77c08ae35760f256032e1519e400d6897f68ee/pkg/sql/internal.go#L294)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I believe in your ability to make a closure
</blockquote></details>

Thanks! I wanted to see whether CI was happy :) it wasn't :(
___
*[pkg/sql/internal.go, line 811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MWfMm5Y60lrdye5oKLt:-MWg2NIW519_doez3F4i:bmairc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d77c08ae35760f256032e1519e400d6897f68ee/pkg/sql/internal.go#L811)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you explain this part to me?
</blockquote></details>

This was the last piece that I added to make a couple of queries from the issue happy.

I just added a more explicit comment about what's going on here. Let me know if more info is worth it.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/internal.go, line 733 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MWg5pV9E25gJhOPFnyA:-MWg5pV9E25gJhOPFnyB:b-9u4anl) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d9f8dce676544dac7a1bc08c6c5d0bd7457ad8/pkg/sql/internal.go#L733)):*
> ```Go
> 				// skipped.
> 				dataCh <- ieIteratorResult{err: res.Err()}
> 				<-waitCh
> ```

Note that some of these waits are not necessary, but I think it might be a good idea to follow the same pattern (of "send on dataCh, block on waitCh") everywhere.

**Review by ajwerner — COMMENTED** [review]
> Also, the CI seems to be unhappy, and in particular TestShowJobWhenComplete/show_jobs 

This seems better now, no? Is this RFAL?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MWxxH_tAceeHB3yZIJK:bvby2i9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by yuzefovich — COMMENTED** [review]
I think the failures are non-deterministic, but last time I looked `TestShowJobWhenComplete/show_jobs` (among other things) was failing pretty reliably. I don't see where the problem might be, so any suggestions are welcome. I'll look into debugging this more later today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MWyYGkz3j-2Ca4b2QWT:by0zmsh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by yuzefovich** [comment]
Hm, the CI I kicked off this morning succeeded, and now I can no longer repro `TestShowJobWhenComplete/show_jobs` failures I saw last week. I don't believe I changed anything in the code, maybe I was just using the wrong branch or something 🤷 . I'll kick off several runs of CI to make sure that failures disappeared for good.

Anyway, I think it is RFAL then.

**Review by ajwerner — COMMENTED** [review]
Generally I'm concerned about the need for selects and detecting context cancellation on the two channels. Can you convince me it's not a problem? 

> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MX-GsWl3hT_oxedeckW:bwcq4p5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @yuzefovich)

___
*[pkg/sql/internal.go, line 811 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MX-G_v1-sIgdTB2bTph:-MX-G_v25-qxDWm1_Tnc:bhz2ghn) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b87943d9addbb48165abeb72e83a386ecb673c/pkg/sql/internal.go#L811)):*
> ```Go
> 		// the next piece from the data channel.
> 		//
> 		// Note that only only statements of ROWS type should send the cols, but
> ```

`only only`
___
*[pkg/sql/internal.go, line 816 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MX-Gf6mBV_JYFVS3jRs:-MX-Gf6n5ArwUV9bbwol:b-vijemm) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b87943d9addbb48165abeb72e83a386ecb673c/pkg/sql/internal.go#L816)):*
> ```Go
> 			resultColumns = first.cols
> 		}
> 		waitCh <- struct{}{}
> ```

does this need to be done in a select? If the context underneath is canceled, then it seems possible that nobody will receive this.

**Review by yuzefovich — COMMENTED** [review]
I believe your concern is totally on point, and I addressed it. I'm feeling optimistic that now we have the correct fix in place.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MX-PQE_2JCyQK-0DKv_:b-dncz46)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/internal.go, line 816 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MX-Gf6mBV_JYFVS3jRs:-MX-OBVD9ukxu-_MqeFg:b-17m463) ([raw file](https://github.com/cockroachdb/cockroach/blob/14b87943d9addbb48165abeb72e83a386ecb673c/pkg/sql/internal.go#L816)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

does this need to be done in a select? If the context underneath is canceled, then it seems possible that nobody will receive this. 
</blockquote></details>

That's a very good point. I think you are totally right, and this is the thing that I missed.

I updated the code so that the reader always listens for context cancellation when operating with the channels. We don't need to do that on the writer (connExecutor) side because the reader will properly drain/close the channels in `rowsIterator.Close` (`Close` must be called whenever an iterator is returned by the internal executor).

**Comment by yuzefovich** [comment]
Ok, fixed some comments and a minor issue. PTAL.

**Comment by yuzefovich** [comment]
The problem with `TestShowJobWhenComplete/show_jobs` is still there - I had a typo when stressing it locally (`TestShowJobsWhenComplete/show_jobs`), oops.

**Review by ajwerner — COMMENTED** [review]
I added two more commits which I speculate fix the problems. See what you think. 

For what it's worth, I'm not super pleased with them. I'm thinking we should refactor some of this synchronization into an abstraction. Also the context management around here is not particularly principled. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MX0K8t54DAOQJUdLXaF:b-oe120o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @pbardea)

**Review by ajwerner — COMMENTED** [review]
I cleaned it up. I'm happier with it now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MX0qmnS-w-hDz44OksK:b-3p3no5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @pbardea)

**Comment by yuzefovich** [comment]
I was missing the crucial observation you added to the commit message. I think now the requirement of listening on the ctx cancellation on the writer side makes sense.

I squashed the two larger commits into one with some cosmetic modifications. The notable changes are moving the logic of draining `dataCh` from `rowsIterator.Close` into `asyncIEResultChannel.close` (to match the comment on `ieResultReader.close`) and closing `waitCh` in `syncIEResultChannel.finish`.

Thanks a lot for baby-sitting this PR. PTAL.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MX4wSUn10qLBrM033QY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by ajwerner — COMMENTED** [review]
Actually, I feel like we can make this a tad better. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MX57EAb2yHjeKAxkOx1:b87qrm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/internal_result_channel.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MX56Nbc8th53y0KVk6u:-MX56Nbc8th53y0KVk6v:b-msbi8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/655ce637431fa73b7c931c5caf4e7c3d28ffe3d3/pkg/sql/internal_result_channel.go#L39)):*
> ```Go
> 	// is non-nil. Err will be non-nil if either close has been called or
> 	// the passed context is finished.
> 	nextResult(ctx context.Context) (_ ieIteratorResult, done bool, err error)
> ```

There's something that still smells a little bit about this interface. The semantics of done and err are a bit off. The semantics of close feel off too. I;m alarmed by the way that close on the async channel consumes everything and propagates errors from the sender while close on the sync channel just effectively no-ops. It's probably fine but I'm having a hard time reasoning about what we want here. Are we trying to wait for the writer or preempt it? It feels like the later as on the happy path we should always see done from `nextResult`.  I'm inclined to make the close behavior much more uniform between the two impls here.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/internal_result_channel.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-MX56Nbc8th53y0KVk6u:-MX9BFiTAbdwF1EWi8D2:b6qkyr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/655ce637431fa73b7c931c5caf4e7c3d28ffe3d3/pkg/sql/internal_result_channel.go#L39)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

There's something that still smells a little bit about this interface. The semantics of done and err are a bit off. The semantics of close feel off too. I;m alarmed by the way that close on the async channel consumes everything and propagates errors from the sender while close on the sync channel just effectively no-ops. It's probably fine but I'm having a hard time reasoning about what we want here. Are we trying to wait for the writer or preempt it? It feels like the later as on the happy path we should always see done from `nextResult`.  I'm inclined to make the close behavior much more uniform between the two impls here. 
</blockquote></details>

Updated the usage of `context.Canceled` error per our discussion.

**Review by ajwerner — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62581#-:-MX9EG67-Gi4zL_tL8PU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by yuzefovich** [comment]
Thanks for the help with this PR!

bors r+

**Pull request merged**
