### PR TITLE
pgwire,clisqlshell: implement a crdb-specific request cancel protocol

### LINKED ISSUE #75203: cli/sql: make an ad-hoc crdb-specific query cancellation work for Ctrl+C
Related to #41335

We want some way to cancel queries with Ctrl+C, even if it's not the standard pg way.

### PR DESCRIPTION
**Pull request by knz**
Fixes #75203.
RFC PR: #75307

The key background understanding needed for this change is the
realization that a pg client provides its key/value parameters to the
server prior to authentication.

This means we can stuff a full-sized cancellation key in there with a
custom status parameter to request crdb-specific cancellation, in a
way that does not require double authentication.

This commit capitalizes on this finding to define a status parameter
called `crdb:cancel_request`, which the client can set to a target
session ID / cancel key pair. Assuming there can be at most one query
running in a given session, this information is sufficient to cancel
the current query.

We propose two different security protocols.

The first one is a "simple" protocol with a shared secret key. Like in
pg's protocol, this exchange does not provide protection against
replay, i.e. a malicious user who can sniff one valid cancel request
can cancel further requests on the same connection.

The second one is based on a secret key, but where requests are HMACs
of the secret and a nonce. This provides protection against
replay, *even when the cancellation request is transmitted over a
non-encrypted link*.

Release note (cli change): The SQL shell now recognizes Ctrl+C during
query execution to cancel the currently executing query, without
closing the connection.

### CODE REVIEW

**Comment by knz** [comment]
@kpatron-cockroachlabs could you have a look at this PR, the API definition in `security/cancel_request.go` and the implementation in `cancel_request_hmac.go`? Thanks

**Comment by knz** [comment]
TODO notes for self:
- SQL built-in function to mint cancel requests for testing
- interactive tests
- cluster setting (hidden) to control protocol
- cluster setting to control logging
- store authnenticator input into serializable session data

**Review by kpatron-cockroachlabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75211)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @kpatron-cockroachlabs)

___
*[pkg/security/cancel_request_hmac.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75211#-MuBjSE3D6jQpYTEti7z:-MuBjSE3D6jQpYTEti8-:b-1mrmv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/65e18c527331f93a3718709c0f53430a21de37cd/pkg/security/cancel_request_hmac.go#L110)):*
> ```Go
> ) (bool, bool, ClientMessage, error) {
> 	curNonce := s.nonce
> 	s.nonce++
> ```

We may want to only increment the nonce when a cancel request is accepted. This would only come up if a malicious person is trying to cancel by brute forcing the HMAC key. In such a scenario a legitimate user might never be able to cancel because the malicious actor is causing the nonce to increment between any two requests from the legitimate client.
___
*[pkg/security/cancel_request_hmac.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75211#-MuBmRjXDGQcyTNFPq_Y:-MuBmRjYDLCGDqfm_uk_:b-8m66vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/65e18c527331f93a3718709c0f53430a21de37cd/pkg/security/cancel_request_hmac.go#L134)):*
> ```Go
> func computeCancelHMAC(sharedSecret string, nonce uint32) []byte {
> 	mac := hmac.New(sha256.New, []byte(sharedSecret))
> 	fmt.Fprintf(mac, "%d", nonce)
> ```

Nit: It is slightly unusual not to including the full identifier in the HMAC. In this case I'm thinking of the sessionID. Since the relationship between sharedSecret and sessionID is 1:1 it should be fine to not include it though.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75211)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs)

___
*[pkg/security/cancel_request_hmac.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75211#-MuBjSE3D6jQpYTEti7z:-MuGWa_N8DG6JFnI6B3l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65e18c527331f93a3718709c0f53430a21de37cd/pkg/security/cancel_request_hmac.go#L110)):*
<details><summary><i>Previously, kpatron-cockroachlabs wrote…</i></summary><blockquote>

We may want to only increment the nonce when a cancel request is accepted. This would only come up if a malicious person is trying to cancel by brute forcing the HMAC key. In such a scenario a legitimate user might never be able to cancel because the malicious actor is causing the nonce to increment between any two requests from the legitimate client.
</blockquote></details>

Done.
___
*[pkg/security/cancel_request_hmac.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75211#-MuBmRjXDGQcyTNFPq_Y:-MuGWaue-mKNb22swzC_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65e18c527331f93a3718709c0f53430a21de37cd/pkg/security/cancel_request_hmac.go#L134)):*
<details><summary><i>Previously, kpatron-cockroachlabs wrote…</i></summary><blockquote>

Nit: It is slightly unusual not to including the full identifier in the HMAC. In this case I'm thinking of the sessionID. Since the relationship between sharedSecret and sessionID is 1:1 it should be fine to not include it though.
</blockquote></details>

Done.

**Comment by knz** [comment]
so apparently we're doing this in a different way. closing.
Thanks @rafiss for all the input!

**Pull request closed without merging**
