### PR TITLE
sql: move row allocation inside RowContainer

### PR DESCRIPTION
**Pull request by RaduBerinde**
The majority of RowContainer.AddRow() callers make copies of the rows; most are
unoptimized (one allocation per row).

Changing RowContainer to manage row storage internally, instead of using the
slices passed by the caller. We allocate rows in chunks, which reduces the
allocations as well as the overhead of storing a slice for every row. The
callers are simplified.

This change also fixes a couple of bugs that were uncovered:
 - explainTraceNode exposed incorrect Columns();
 - insert code was appending to a row returned by a plan node via Values().

CC @nvanbenschoten for the first commit

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10534)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
First commit :lgtm_strong: 

---

Reviewed 2 of 3 files at r1.
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/values.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW1uwRKpWVssnodwBLv:-KW1uwRKpWVssnodwBLw:b-k1f7on) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb85b13537891c065394a158de2bb5164f84d7da/pkg/sql/values.go#L40)):*
> ```Go
> 
> 	// rowsPopped is used for heaps, it indicates the number of rows that were
> 	// "popped". These rows are still part of the underlying RowContainer.
> ```

For ease of future understanding, consider adding something about the popped rows being at the back of the RowContainer in the range `[length-rowsPopped, length)`

---

*[pkg/sql/values.go, line 269 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW1tHBmJGPSAKzGi4Aq:-KW1tHBmJGPSAKzGi4Ar:b4b3l1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb85b13537891c065394a158de2bb5164f84d7da/pkg/sql/values.go#L269)):*
> ```Go
> }
> 
> // Pop implements the heap.Interface interface.
> ```

The awkwardness of this interface and its related functions always catches me off-guard

---

*[pkg/sql/values.go, line 289 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW1sWPf4qMkyTAV0tO0:-KW1sWPf4qMkyTAV0tO1:b-gvecl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb85b13537891c065394a158de2bb5164f84d7da/pkg/sql/values.go#L289)):*
> ```Go
> }
> 
> // ResetLen resets the length to that of the underlying row container.
> ```

You might want to include the motivation for this. Something along the lines of: "this resets the effect that popping values had on the `valuesNode` length"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-:-KW1v_Z0UlUlNPlVlPdJ:b-lla9dq)*

**Comment by knz** [comment]
Yeah this first commit is very good. Thanks for this :)

---

Reviewed 3 of 3 files at r1.
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-:-KW2AlCmi5w6yUg4N8Vn:blrjwjp)*

**Comment by knz** [comment]
And the 2nd one is very good too. I still see wisdom in splitting commits for different issues though, the overlap here is insufficient to justify grouping them.

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/insert.go, line 296 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2EjrE21lXY0qPDkIP:-KW2EjrFgIIY7xc-TWpq:b-ry56x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/insert.go#L296)):*
> ```Go
> 
> 	if len(rowVals) < len(n.insertCols) {
> 		// It's not cool to append to the slice returned by a node; make a copy.
> ```

1) Can you think of a test that would reveal this bug?
2) perhaps this too would be best in a separate commit.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW2CUALogDnTNZKJY5s:b9m51u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
> ```Go
> 	if nCols != 0 {
> 		c.rowsPerChunk = (targetChunkSize + nCols - 1) / nCols
> 		preallocChunks := (rowCapacity + c.rowsPerChunk - 1) / c.rowsPerChunk
> ```

Move `preallocChunks := ... allocChunks(preallocChunks)` to a conditional `if c.chunks == nil { ... } ` in `AddRow`. 
This is because this allocation should really be accounted for to the monitor and the constructor is too early to do so.

---

*[pkg/sql/row_container.go, line 190 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2DIPpugdXhdxQPNba:-KW2DIPqv2lN3PvuOgIh:brwltcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L190)):*
> ```Go
> 		return nil
> 	}
> 	// This is a potential hot path, use int32 for faster division.
> ```

This comment is redundant with the one in `getChunkAndPos`.

---

*[pkg/sql/trace.go, line 54 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2DncQxxV9UNlENbje:-KW2DncQxxV9UNlENbjf:b-5srmfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/trace.go#L54)):*
> ```Go
> // Internally, the explainTraceNode also returns a timestamp column which is
> // used during sorting.
> var traceColumnsWithTS = append(traceColumns, ResultColumn{
> ```

This seems like an unrelated bug in the implementation of EXPLAIN(TRACE). I would recommend a separate commit for this.

---

*[pkg/sql/testdata/explain, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2EJoEHaosI6GclP85:-KW2EJoEHaosI6GclP86:b-o1jen7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/testdata/explain#L69)):*
> ```
> Level  Type                  Description             Columns                                                                                                  Ordering
> 0      select                                        ("Cumulative Time", Duration, "Span Pos", Operation, Event, RowIdx, Key, Value, Disposition)             +9,+"Span Pos"
> 1      sort                  +Timestamp,+"Span Pos"  ("Cumulative Time", Duration, "Span Pos", Operation, Event, RowIdx, Key, Value, Disposition)             +9,+"Span Pos"
> ```

See my comment above - probably best in separate commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-:-KW2Et0-EDnHf5tBR9NC:b-e9n0js)*

**Comment by RaduBerinde** [comment]
TFTRs, updated!

---

Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/insert.go, line 296 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2EjrE21lXY0qPDkIP:-KW33xPD0MHQqSTQCrQP:b-iy7tf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/insert.go#L296)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> 1) Can you think of a test that would reveal this bug?
> 2) perhaps this too would be best in a separate commit.
</details>
It doesn't really cause any issues right now - it was revealed while I was working on the change and `RowContainer.At()` wasn't limiting the capacity of the returned slice. Now it doesn't really break anything anymore but this is the right thing to do (and more efficient).
I'll split into a different commit.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW35Ghn7dMHpSBsXyqy:bdm704v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Move `preallocChunks := ... allocChunks(preallocChunks)` to a conditional `if c.chunks == nil { ... } ` in `AddRow`. 
> This is because this allocation should really be accounted for to the monitor and the constructor is too early to do so.
</details>
But even if we are doing it in the first row, we are allocating more than that single row. Should I account for the chunk allocation separately from the per-row allocation? I'm asking because I'm not entirely sure what the intended model is (note that the old code it was ignoring the `rows` slice itself)

---

*[pkg/sql/row_container.go, line 190 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2DIPpugdXhdxQPNba:-KW35ajNkYBtHI_p_E0Y:br01qyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L190)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> This comment is redundant with the one in `getChunkAndPos`.
</details>
Leftover, removed.

---

*[pkg/sql/trace.go, line 54 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2DncQxxV9UNlENbje:-KW34nzkGgk-yzKTanvA:b-dnf8ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/trace.go#L54)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> This seems like an unrelated bug in the implementation of EXPLAIN(TRACE). I would recommend a separate commit for this.
</details>
I am splitting it off. It's related in that it causes a panic in the new implementation which actually checks that it gets rows of the correct length.

---

*[pkg/sql/values.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW1uwRKpWVssnodwBLv:-KW3607FlOGNGRLiJP3j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb85b13537891c065394a158de2bb5164f84d7da/pkg/sql/values.go#L40)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> For ease of future understanding, consider adding something about the popped rows being at the back of the RowContainer in the range `[length-rowsPopped, length)`
</details>
Done.

---

*[pkg/sql/values.go, line 289 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW1sWPf4qMkyTAV0tO0:-KW366yDcPlGLo8-1G2C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb85b13537891c065394a158de2bb5164f84d7da/pkg/sql/values.go#L289)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> You might want to include the motivation for this. Something along the lines of: "this resets the effect that popping values had on the `valuesNode` length"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-:-KW3Akn5IjRaze1CNgsz:b3z53a0)*

**Comment by knz** [comment]
Reviewed 3 of 12 files at r3.
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW3BqceVVC5Lcohe9sY:b-5phc3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> But even if we are doing it in the first row, we are allocating more than that single row. Should I account for the chunk allocation separately from the per-row allocation? I'm asking because I'm not entirely sure what the intended model is (note that the old code it was ignoring the `rows` slice itself)
</details>
Yes it's better to add the chunk allocation as a whole. The model is that we should capture as much as possible, so that users don't get a OOM crash without expecting it. Meanwhile we don't want to over-shoot too much either so as to not restrict client connections excessively. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by knz** [comment]
Reviewed 9 of 12 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW3EmYRadn5tked1ZBO:b-ta0aem) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Yes it's better to add the chunk allocation as a whole. The model is that we should capture as much as possible, so that users don't get a OOM crash without expecting it. Meanwhile we don't want to over-shoot too much either so as to not restrict client connections excessively. 
</details>
Got it. In fact preallocating 1 chunk here doesn't do much, AddRow would have done the same.. But when we are given a non-zero `rowCapacity` (which is basically asking us to prealloc a certain amount), shouldn't we do it and account for it here in the constructor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW3Gq2MlD10wpIoIEd6:baofbcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Got it. In fact preallocating 1 chunk here doesn't do much, AddRow would have done the same.. But when we are given a non-zero `rowCapacity` (which is basically asking us to prealloc a certain amount), shouldn't we do it and account for it here in the constructor?
</details>
Yeah that was a shortcoming of the previous implementation. The initial/original code had the accounting in the constructor too, but then I bailed out when I saw the amount of additional error checking needed to ensure the container is closed in all cases. Then I decided that omitting to account for the pre-allocated row array was the better trade-off against the performance loss of re-allocating to grow the array when the size ought to have been known in advance. Perhaps you'll think better about this than I did.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW3I9sE1OHG9reYdVPd:b-kjfysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Yeah that was a shortcoming of the previous implementation. The initial/original code had the accounting in the constructor too, but then I bailed out when I saw the amount of additional error checking needed to ensure the container is closed in all cases. Then I decided that omitting to account for the pre-allocated row array was the better trade-off against the performance loss of re-allocating to grow the array when the size ought to have been known in advance. Perhaps you'll think better about this than I did.
</details>
Ah, yes, I just realized the difficulty with error checking. Yes, seems like doing it on the first `AddRow` makes most sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by RaduBerinde** [comment]
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW3PedadERJRywrL8K8:bevftus) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, yes, I just realized the difficulty with error checking. Yes, seems like doing it on the first `AddRow` makes most sense.
</details>
Done, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/row_container.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW2CUAK71TgZbne7kqH:-KW3SRipPnTHaSo1suKg:b-sp0bym) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b38825ef46d6901cb4f8e134f02344c9baa9de/pkg/sql/row_container.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Done, PTAL.
</details>
Yep, looks good.

---

*[pkg/sql/row_container.go, line 185 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW3Sn0-TKZINk2bXTrR:-KW3Sn001NlNzHUXl_PY:bhzo5jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b02c8a1decca9fe022a02cfaee7075f0d893e2/pkg/sql/row_container.go#L185)):*
> ```Go
> 		if len(c.chunks) > 0 {
> 			// Grow the number of chunks by a fraction.
> 			numChunks = 1 + len(c.chunks)/8
> ```

I think you can drop the conditional and replace this with `numChunks := c.preallocChunks + len(c.chunks)/8`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/row_container.go, line 185 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW3Sn0-TKZINk2bXTrR:-KW3V13VZwiPBwCeYfdp:b-a6xtjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b02c8a1decca9fe022a02cfaee7075f0d893e2/pkg/sql/row_container.go#L185)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think you can drop the conditional and replace this with `numChunks := c.preallocChunks + len(c.chunks)/8`.
</details>
But if say we preallocate 1000 chunks and then we need more, I don't want to allocate 1125 more..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by RaduBerinde** [comment]
Verified there are no regressions in the basic benchmarks https://gist.github.com/RaduBerinde/099fe880b3c664d4b40bf789b44a7b9d

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-:-KW3Vu0kHX03NUxkOcvH:brwhtth)*

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/row_container.go, line 185 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KW3Sn0-TKZINk2bXTrR:-KW3WNW0hhhbVqJ6CWVl:b-dcojil) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b02c8a1decca9fe022a02cfaee7075f0d893e2/pkg/sql/row_container.go#L185)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> But if say we preallocate 1000 chunks and then we need more, I don't want to allocate 1125 more..
</details>
Woops yes you're right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-:-KW3WS7fnr-FnzvLRrh8:bnfp4nl)*

**Comment by irfansharif** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/row_container.go, line 215 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KWFV37P9VH0Mtj-YQbr:-KWFV37P9VH0Mtj-YQbs:bbe5foz) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b02c8a1decca9fe022a02cfaee7075f0d893e2/pkg/sql/row_container.go#L215)):*
> ```Go
> 	}
> 	chunk, pos := c.getChunkAndPos(i)
> 	return c.chunks[chunk][pos : pos+c.numCols : pos+c.numCols]
> ```

why `return c.chunks[chunk][pos : pos+c.numCols : pos+c.numCols]` and not `return c.chunks[chunk][pos : pos+c.numCols]`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/row_container.go, line 215 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534#-KWFV37P9VH0Mtj-YQbr:-KWFW-j6G556Uu1CcIIJ:bc9a1sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b02c8a1decca9fe022a02cfaee7075f0d893e2/pkg/sql/row_container.go#L215)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> why `return c.chunks[chunk][pos : pos+c.numCols : pos+c.numCols]` and not `return c.chunks[chunk][pos : pos+c.numCols]`?
</details>
Because if someone tries to append to a row returned by `At()`, they will overwrite other rows. That's not really something that one is supposed to do with these rows, but there was such code that I fixed as part of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10534)*

**Pull request merged**
