### PR TITLE
backupccl: rework schema rewriting during restore

### PR DESCRIPTION
**Pull request by adityamaru**
This patch reworks how we rewrite the parent schema
IDs of schema objects  during restore
to use the `ParentSchemaID` field on the rewrite proto.

This work simplifies the work required in https://github.com/cockroachdb/cockroach/pull/72000
to support restoring a physical public descriptor.

Release note: None

### CODE REVIEW

**Comment by RichardJCai** [comment]
I think this approach LGTM, we have some failing tests cause `pkg/ccl/backupccl/import_job.go`

**Review by RichardJCai — APPROVED** [review]
Nice! LGTM

**Comment by adityamaru** [comment]
@dt Richard is blocked on this so I'm checking it in. If you see something fishy I'll keep a lookout for comments. CI passed so I _think_ we should be fine.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/restore_planning.go, line 872 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouByYvDdZco6zI6xv-:-MouByYvDdZco6zI6xv0:b-m3eno6) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L872)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	// At this point, descriptorRewrites contains an entry for every database,
> 	// schema, table and type that needs to be restored. As a final step we
> 	// populate the parent schema ID of all tables and types. This is easiest to
> 	// do once the descriptorRewrites map contains a rewrite for every schema that
> 	// is being restored.
> ```
</details>

Can I be honest, this comment isn't super clear to me. It tells me about some motivation, but it doesn't really tell me how to read what's going on. 
___
*[pkg/ccl/backupccl/restore_planning.go, line 876 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouC9AJBrJ4EnkZE8iP:-MouC9AJBrJ4EnkZE8iQ:b-bj9fj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L876)):*
> ```Go
> 		var newSchemaTableID descpb.ID
> 		curTableSchemaID := table.GetParentSchemaID()
> 		if curTableSchemaID == keys.PublicSchemaID && !table.IsTemporary() {
> ```

Is the second half of this possible? For something to be temporary, doesn't it need to be in a temporary schema, which, by definition, is not 29?
___
*[pkg/ccl/backupccl/restore_planning.go, line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouCQ6r0aTv7wlHk9JT:-MouCQ6r0aTv7wlHk9JU:b5vcvtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L877)):*
> ```Go
> 		curTableSchemaID := table.GetParentSchemaID()
> 		if curTableSchemaID == keys.PublicSchemaID && !table.IsTemporary() {
> 			newSchemaTableID = curTableSchemaID
> ```

what is this case given we're going to overwrite it below unconditionally?
___
*[pkg/ccl/backupccl/restore_planning.go, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouAqRw-pIYtIDyab0X:-MouAqRw-pIYtIDyab0Y:b-oisttv) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L898)):*
<details><summary><i alt="summary">Quoted 26 lines of code…</i></summary>

> ```
> 	for _, table := range tablesByID {
> 		var newSchemaTableID descpb.ID
> 		curTableSchemaID := table.GetParentSchemaID()
> 		if curTableSchemaID == keys.PublicSchemaID && !table.IsTemporary() {
> 			newSchemaTableID = curTableSchemaID
> 		}
> 		if rw, ok := descriptorRewrites[curTableSchemaID]; ok {
> 			newSchemaTableID = rw.ID
> 		} else {
> 			newSchemaTableID = curTableSchemaID
> 		}
> 		descriptorRewrites[table.ID].ParentSchemaID = newSchemaTableID
> 	}
> 	for _, typ := range typesByID {
> 		var newSchemaTypeID descpb.ID
> 		curTypeSchemaID := typ.GetParentSchemaID()
> 		if curTypeSchemaID == keys.PublicSchemaID {
> 			newSchemaTypeID = curTypeSchemaID
> 		}
> 		if rw, ok := descriptorRewrites[curTypeSchemaID]; ok {
> 			newSchemaTypeID = rw.ID
> 		} else {
> 			newSchemaTypeID = curTypeSchemaID
> 		}
> 		descriptorRewrites[typ.ID].ParentSchemaID = newSchemaTypeID
> 	}
> ```
</details>

factor this together:

```go
isTempTable := func(desc catalog.Descriptor) bool {
    table, isTable := desc.(catalog.TableDescriptor)
    return isTable && table.IsTemporary()
}
rewriteObject := func(desc catalog.Descriptor) {
 		var newSchemaTypeID descpb.ID
 		curTypeSchemaID := desc.GetParentSchemaID()
 		if curTypeSchemaID == keys.PublicSchemaID && !isTempTable(desc)
 			newSchemaTypeID = curTypeSchemaID
 		}
 		if rw, ok := descriptorRewrites[curTypeSchemaID]; ok {
 			newSchemaTypeID = rw.ID
 		} else {
 			newSchemaTypeID = curTypeSchemaID
 		}
 		descriptorRewrites[desc.GetID()].ParentSchemaID = newSchemaTypeID
} 
for _, table := range tablesByID {
    rewriteObject(table)
}
for _, typ := range typesByID {
    rewriteObject(typ)
}
```

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/ccl/backupccl/restore_planning.go, line 872 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouByYvDdZco6zI6xv-:-Moukl7zC5jF9GkJkNyR:b-wlikz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L872)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// At this point, descriptorRewrites contains an entry for every database,
> 	// schema, table and type that needs to be restored. As a final step we
> 	// populate the parent schema ID of all tables and types. This is easiest to
> 	// do once the descriptorRewrites map contains a rewrite for every schema that
> 	// is being restored.
> ```
Can I be honest, this comment isn't super clear to me. It tells me about some motivation, but it doesn't really tell me how to read what's going on. 
</blockquote></details>

I agree, I've reworded it to be more targeted.
___
*[pkg/ccl/backupccl/restore_planning.go, line 876 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouC9AJBrJ4EnkZE8iP:-MouksHD96pr44zce8ah:bak2ia0) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L876)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is the second half of this possible? For something to be temporary, doesn't it need to be in a temporary schema, which, by definition, is not 29?
</blockquote></details>

You're right, I don't think we need this if condition at all. descriptorRewrites should not currently have an entry for `keys.PublicSchemaID` since it was not backed by a physical descriptor when backed up.
___
*[pkg/ccl/backupccl/restore_planning.go, line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouCQ6r0aTv7wlHk9JT:-Moul5eo6xotWKt4Laac:brpmqc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L877)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what is this case given we're going to overwrite it below unconditionally?
</blockquote></details>

removed.
___
*[pkg/ccl/backupccl/restore_planning.go, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-MouAqRw-pIYtIDyab0X:-Moul6XlAh0iSneGO_OR:bd5l6mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/566797cac9345979fd8fc137e0f8eef5981f87e9/pkg/ccl/backupccl/restore_planning.go#L898)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	for _, table := range tablesByID {
> 		var newSchemaTableID descpb.ID
> 		curTableSchemaID := table.GetParentSchemaID()
> 		if curTableSchemaID == keys.PublicSchemaID && !table.IsTemporary() {
> 			newSchemaTableID = curTableSchemaID
> 		}
> 		if rw, ok := descriptorRewrites[curTableSchemaID]; ok {
> 			newSchemaTableID = rw.ID
> 		} else {
> 			newSchemaTableID = curTableSchemaID
> 		}
> 		descriptorRewrites[table.ID].ParentSchemaID = newSchemaTableID
> 	}
> 	for _, typ := range typesByID {
> 		var newSchemaTypeID descpb.ID
> 		curTypeSchemaID := typ.GetParentSchemaID()
> 		if curTypeSchemaID == keys.PublicSchemaID {
> 			newSchemaTypeID = curTypeSchemaID
> 		}
> 		if rw, ok := descriptorRewrites[curTypeSchemaID]; ok {
> 			newSchemaTypeID = rw.ID
> 		} else {
> 			newSchemaTypeID = curTypeSchemaID
> 		}
> 		descriptorRewrites[typ.ID].ParentSchemaID = newSchemaTypeID
> 	}
> ```
factor this together:

```go
isTempTable := func(desc catalog.Descriptor) bool {
    table, isTable := desc.(catalog.TableDescriptor)
    return isTable && table.IsTemporary()
}
rewriteObject := func(desc catalog.Descriptor) {
 		var newSchemaTypeID descpb.ID
 		curTypeSchemaID := desc.GetParentSchemaID()
 		if curTypeSchemaID == keys.PublicSchemaID && !isTempTable(desc)
 			newSchemaTypeID = curTypeSchemaID
 		}
 		if rw, ok := descriptorRewrites[curTypeSchemaID]; ok {
 			newSchemaTypeID = rw.ID
 		} else {
 			newSchemaTypeID = curTypeSchemaID
 		}
 		descriptorRewrites[desc.GetID()].ParentSchemaID = newSchemaTypeID
} 
for _, table := range tablesByID {
    rewriteObject(table)
}
for _, typ := range typesByID {
    rewriteObject(typ)
}
```
</blockquote></details>

thanks!

**Review by dt — APPROVED** [review]

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72959#-:-Mp7OOx53EFiu53Iordz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by adityamaru** [comment]
TFTRs!

bors r+

**Pull request merged**
