### PR TITLE
opt: add update checks for unique constraints

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds checks for unique constraints when planning updates
in the optimizer. This does not yet impact anything outside of the optimizer
tests, since `UNIQUE WITHOUT INDEX` is still not fully supported outside of the
optimizer test catalog.

Informs #41535

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-:-MOchtDA40RNvKW8_zdr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOchKiq3Ltoi6EMMf6d:-MOchKiq3Ltoi6EMMf6e:b-q1nktg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L42)):*
> ```Go
> 		// a check.
> 		if mb.tab.Unique(i).WithoutIndex() && h.init(mb, i) {
> 			mb.uniqueChecks = append(mb.uniqueChecks, h.buildInsertionCheck())
> ```

[nit] maybe a comment why the insertion check just works
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOch-vS19spccMh33Y1:-MOch-vS19spccMh33Y2:b46amdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L48)):*
> ```Go
> }
> 
> func (mb *mutationBuilder) buildUniqueChecksForUpdate() {
> ```

[nit] worth adding a comment, and mention that this builds checks for "unique without index" constraints
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOcgPbp8iHWWJZjv2Q9:-MOcgPbp8iHWWJZjv2QA:b-fqdsq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L75)):*
> ```Go
> // UNIQUE WITHOUT INDEX constraints on the table. Also returns the ordinal of
> // the first matching constraint if one exists.
> func (mb *mutationBuilder) hasUniqueWithoutIndexConstraints() (ord int, ok bool) {
> ```

I don't think returning the ordinal is worthwhile here. It's a minuscule optimization, this stuff pales in comparison with the total cost of the actual uniqueness check.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOcgt7x2XMmW_UaVNQi:-MOcgt7x2XMmW_UaVNQj:buvzxp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L77)):*
> ```Go
> func (mb *mutationBuilder) hasUniqueWithoutIndexConstraints() (ord int, ok bool) {
> 	uniqueCount := mb.tab.UniqueCount()
> 	if uniqueCount == 0 {
> ```

[nit] We shouldn't need this special code path

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-:-MOhgrCn5505GaiC0z9s:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOchKiq3Ltoi6EMMf6d:-MOh-60Z3e78SGOsAt88:b6jaxka) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L42)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe a comment why the insertion check just works
</blockquote></details>

Did you mean to add this to the update code below? I added a comment there (let me know if that's not what you had in mind).
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOch-vS19spccMh33Y1:-MOhga2oBsduyq_I_yFk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L48)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] worth adding a comment, and mention that this builds checks for "unique without index" constraints
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOcgPbp8iHWWJZjv2Q9:-MOh-LigCCG5FhKaQsN9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L75)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think returning the ordinal is worthwhile here. It's a minuscule optimization, this stuff pales in comparison with the total cost of the actual uniqueness check.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOcgt7x2XMmW_UaVNQi:-MOh-TKj3U7AWumbwVMn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L77)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We shouldn't need this special code path
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-:-MOhlPcDCPXgoO_H4kYh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-MOchKiq3Ltoi6EMMf6d:-MOhlHzO7oFUxn8WYo1z:bjzb8i7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eddd70ecb274d6aaede250a0bec1e436f119aaf/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L42)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did you mean to add this to the update code below? I added a comment there (let me know if that's not what you had in mind).
</blockquote></details>

Yeah, looks good, I pointed to the wrong section

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57930#-:-MOii-Z91_wwNOyJZAPD:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Pull request merged**
