### PR TITLE
distsqlrun: disable tracing when writing results for CREATE STATISTICS

### PR DESCRIPTION
**Pull request by rytaft**
This commit disables tracing inside the `writeResults` function of the
`sampleAggregator`. This is necessary so that the output of `EXPLAIN
ANALYZE (DISTSQL) CREATE STATISTICS` only shows the DistSQL flow from
the read-only statistics collection transaction, and is not muddled by
tracing from the update transaction.

Informs #36724

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36760)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36760#-LcC0jkf7_r5s5D6VRND:-LcC0jkg12sKZB8v68KI:bf8r4iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7764babc5295af6d046d41329c590d483d9c732/pkg/sql/distsqlrun/sample_aggregator.go#L271)):*
> ```Go
> func (s *sampleAggregator) writeResults(ctx context.Context) error {
> 	// Turn off tracing so these writes don't affect the results of EXPLAIN
> 	// ANALYZE.
> ```

This also hides the traces in other contexts:
 - when we're not recording (and just looking at traces sent to a backend)
 - when we're recording as part of session tracing.

For the first one, we could check if the current span is recording:
```
if span := opentracing.SpanFromContext(ctx); span != nil && tracing.IsRecording(span) {
  ctx = opentracing.ContextWithSpan(ctx, nil)
}
```

I don't have a good idea about the second one. I would just leave a "TODO: this also hides this from SQL session traces".

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36760)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36760#-LcC2EJWDX8MbxY82stx:-LcC2EJWDX8MbxY82sty:b-y9vf7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7764babc5295af6d046d41329c590d483d9c732/pkg/sql/distsqlrun/sample_aggregator.go#L32)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	"github.com/opentracing/opentracing-go"
> ```

[nit] good practice to add an explicit `opentracing` alias when it doesn't match the path basename. (I find that whatever is running in my editor when I save a file does that automatically)

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36760)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36760#-LcC2EJWDX8MbxY82stx:-LcCc5kv6rOu9X5jmJI4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7764babc5295af6d046d41329c590d483d9c732/pkg/sql/distsqlrun/sample_aggregator.go#L32)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] good practice to add an explicit `opentracing` alias when it doesn't match the path basename. (I find that whatever is running in my editor when I save a file does that automatically)
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36760#-LcC0jkf7_r5s5D6VRND:-LcCc8W97ncvc9ITlcDp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7764babc5295af6d046d41329c590d483d9c732/pkg/sql/distsqlrun/sample_aggregator.go#L271)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This also hides the traces in other contexts:
 - when we're not recording (and just looking at traces sent to a backend)
 - when we're recording as part of session tracing.

For the first one, we could check if the current span is recording:
```
if span := opentracing.SpanFromContext(ctx); span != nil && tracing.IsRecording(span) {
  ctx = opentracing.ContextWithSpan(ctx, nil)
}
```

I don't have a good idea about the second one. I would just leave a "TODO: this also hides this from SQL session traces".
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
LGTM

I'd run the tests under `make stress` for a bit, if you haven't already.

**Review by rytaft — COMMENTED** [review]
TFTR!

Ran `make stress` for several minutes with no flakes, so I think we're good to go.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36760#-:-LcCm3Sc1sqSP0mf1RDD:bvlxi1q)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
