### PR TITLE
asim: add exact_bound, upper_bound, lower_bound to CmdArgs

### PR DESCRIPTION
**Pull request by wenyihu6**
**asim: move sim helper functions to helpers_test.go**

This patch moves helper functions for scanning and parsing arguments from
`datadriven_simulation_test.go` to `helpers_test.go`.

Note that this commit does not change any existing functionality.

Epic: None

Release Note: None

---

**asim: add exact_bound, upper_bound, lower_bound to CmdArgs**

Previously, the allocator simulator's assertions were limited to accepting only
a single threshold value for type=balance, type=steady, and type=stat
assertions. This single threshold functioned as an upper limit for balance and
steady and as an exact limit for stat. This is less ideal as there are instances
where different types of bounds need to be asserted. To improve this, this patch
replaces the argument `threshold=` with 
`exact_bound=, upper_bound=, and lower_bound=`. Note that only one 
argument should be specified at a time. If multiple are specified, the expected 
precedence order is exact_bound > upper_bound > lower_bound.

Note that this commit does not change any existing functionality.

Epic: None

Release Note: None

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105795)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/asim/tests/assert.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDTUNp7ETTnG0Y-g2d:-NZDTUNp7ETTnG0Y-g2e:b-tdq1wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/assert.go#L37)):*
> ```Go
> // threshold is created by parsing CmdArgs array and is used for assertion to
> // validate user-defined threshold constraints.
> type threshold struct {
> ```

Could you add a `String()` method, then replace the `%+v` formatters with `%v` when this is printed below in assertions.
___
*[`pkg/kv/kvserver/asim/tests/assert.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDU1D86XFKmNukSqvI:-NZDU1D86XFKmNukSqvJ:b9nyy16) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/assert.go#L226)):*
> ```Go
> // storeStatAssertion implements the SimulationAssertion interface. The
> // storeStatAssertion declares an assertion. A common use case is to specify an
> // exact_bound for the type=steady threshold. With this configuration, the given
> ```

Isn't the `type=steady` related to `steadyStateAssertion`?
___
*[`pkg/kv/kvserver/asim/tests/testdata/example_rebalancing` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDT8WG9x852w_eZQZ9:-NZDT8WH5p2WRmb1LGHb:b2zi4q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/testdata/example_rebalancing#L79)):*
> ```
> ----
> failed assertion sample 2
>   balance stat=qps threshold={value:1.15 thresholdType:1} ticks=6
> ```

This is the formatting I referred to in a comment above.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/assert.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDTUNp7ETTnG0Y-g2d:-NZDUjRP-xeDHlNuS-f0:b4flr6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/assert.go#L37)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you add a `String()` method, then replace the `%+v` formatters with `%v` when this is printed below in assertions.
</blockquote></details>

I was thinking about it, but that requires marking `thresholdType` as exported for the `threshold` struct. Wdyt?

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105795)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/asim/tests/assert.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDTUNp7ETTnG0Y-g2d:-NZb3uau1PTsPc7V0RhL:b-hep38m) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/assert.go#L37)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I was thinking about it, but that requires marking `thresholdType` as exported for the `threshold` struct. Wdyt?
</blockquote></details>

Why does it require marking the `thresholdType` as exported?

Aren't you able to do something like 


```go
func (tht thresholdType) String() string {
    switch tht {
    case exactBound:
        return "="
    case upperBound:
        return "<"
    case lowerBound:
        return ">"
    default:
        panic(...)
    }
}

func (th *threshold) String() string {
    return fmt.Sprintf("%s%.2f", th.thresholdType, th.threshold)
}
```

Alternatively, implement a string function just on the threshold using a bounds notation -- `[x,y]` with infinity for upper or lower bound thresholds.

Would that work? I may be missing something.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/assert.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDTUNp7ETTnG0Y-g2d:-NZcAZJf4RD6KnWc9fPJ:bae7532) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/assert.go#L37)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Why does it require marking the `thresholdType` as exported?

Aren't you able to do something like 


```go
func (tht thresholdType) String() string {
    switch tht {
    case exactBound:
        return "="
    case upperBound:
        return "<"
    case lowerBound:
        return ">"
    default:
        panic(...)
    }
}

func (th *threshold) String() string {
    return fmt.Sprintf("%s%.2f", th.thresholdType, th.threshold)
}
```

Alternatively, implement a string function just on the threshold using a bounds notation -- `[x,y]` with infinity for upper or lower bound thresholds.

Would that work? I may be missing something.
</blockquote></details>

Ah sorry about the confusion. I wasn't sure about string formatting behavior in Go and thought there would be no difference between passing by value and reference for the struct method when it comes to string formatting. It wasn't working since I used pass by reference for the `String()` method. It should be fixed now.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/assert.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDU1D86XFKmNukSqvI:-NZcAkruCy93ajcFMfIs:bb71op5) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/assert.go#L226)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Isn't the `type=steady` related to `steadyStateAssertion`?
</blockquote></details>

Opps

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/testdata/example_rebalancing` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-NZDT8WG9x852w_eZQZ9:-NZcAuE2DJm-kCGHWOuB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816cf78d2ce50aa047352daf5093a398e89c62/pkg/kv/kvserver/asim/tests/testdata/example_rebalancing#L79)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This is the formatting I referred to in a comment above.
</blockquote></details>

Done.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105795#-:-NZg2aB167bIV6Oa6K4A:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

**Comment by wenyihu6** [comment]
TFTR!

bors r=kvoli

**Pull request merged**
