### PR TITLE
build: generate .pb.go files in the bazel sandbox

### LINKED ISSUE #56067: build: Generate all the protobuf files with Bazel

### PR DESCRIPTION
**Pull request by rickystewart**
We used to use the checked-in `.pb.go` files in our Bazel build, but
these files should really be generated during the build (this is normal
Bazel style, and avoids the weird extra step of having to run
`make generate` and check in the `.pb.go` files whenever a `.proto` is
updated). Some specific implementation notes:

* Add a couple `go_proto_compiler`s for the `protoc-gen-gogoroach`
  plugin.

* We enable Gazelle handling of `.proto` files in `BUILD.bazel`, and add
  `.pb.gw.go` generation for those files that need it as well.

* In that file, we also add a bunch of `gazelle:resolve` and
  `gazelle:exclude` directives that fix some build issues. Generally,
  this is necessary for vendored protos, which Gazelle doesn't index
  correctly.

* Add a couple ad-hoc manual fixes to make compilation work (they can
  generally be found by searching for lines in `BUILD.bazel` files that
  are marked `keep`). Usually, this is necessary because of annotations,
  which Gazelle can't properly track the dependencies for.

* Do some extra dependency munging, which becomes necessary due to our
  usage of `rules_go`. First, move `go_repository()` declarations from
  `DEPS.bzl` to `WORKSPACE` so we can override the dependencies pulled
  in by `go_rules_dependencies()`. Finally, we have to patch some of the
  vendored code as well; the patches can be found in `build/patches`. We
  do this because Gazelle's default behavior would be to generate
  `proto_library()` and `go_proto_library()` declarations for every
  vendored `.proto` file, which is sometimes not what we want because it
  can introduce various compiler or linker issues. Where relevant, we
  use vendored pre-generated `.pb.go` files so we don't have to
  re-build those files ourselves. Elsewhere we need to replace the
  Gazelle-inferred dependencies on rules in
  `@io_bazel_rules_go//proto/wkt` with other Go libraries which can be
  safely linked. See [this thread](https://github.com/grpc-ecosystem/grpc-gateway/issues/1847#issuecomment-739988828)
  for additional context.

Fixes #56067.

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
Nice, pretty exciting! :lgtm_strong: 

(cc-ing just in-case @otan misses it.)

> Reviewed 91 of 91 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-:-MQYbsHo9qBYbt-QA2wW:buuh059)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[BUILD.bazel, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYNtFo3YkYNn0_0rGm:-MQYNtFo3YkYNn0_0rGn:by6ul8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/BUILD.bazel#L16)):*
> ```Starlark
> # gazelle:build_file_name BUILD.bazel
> 
> # We disable protobuf generation for our dependencies.
> ```

This comment could be updated.
___
*[DEPS.bzl, line 2842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYa1CI0encbAhJKcyz:-MQYa1CI0encbAhJKcz-:b-l2abg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/DEPS.bzl#L2842)):*
> ```Starlark
>         build_file_proto_mode = "disable_global",
>         importpath = "go.etcd.io/etcd/raft/v3",
>         patch_args = ["-p1"],
> ```

Mildly surprised these diffs didn't need explicit `# keep` directives. If we were to bump any of these dependencies, do these edits disappear?
___
*[WORKSPACE, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYaRbj22mBaFM3M9Xs:-MQYaRbj22mBaFM3M9Xt:bwj49zd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/WORKSPACE#L88)):*
> ```Starlark
> git_repository(
>     name = "com_google_protobuf",
>     commit = "09745575a923640154bcf307fba8aedff47f240a",
> ```

Doesn't have to be this PR, but now that we're generating pb.go files under bazel, we'll want to tackle https://github.com/cockroachdb/cockroach/issues/58227 next. The SHA in use here is not the one we're using through our Makefile-based builds I think IIRC.
___
*[build/patches/BUILD.bazel, line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYb0nbA_aGoAe80YwP:-MQYb0nbA_aGoAe80YwQ:b-bez4uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb71d88fb96a4ded0eb5414eb2eb88faaaf5895/build/patches/BUILD.bazel#L0)):*
Why this empty BUILD file? Could be removed I think.
___
*[build/patches/com_github_cockroachdb_errors.patch, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYbBrf2Ox2rszWZt22:-MQYbBrf2Ox2rszWZt23:b8ulsuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/build/patches/com_github_cockroachdb_errors.patch#L15)):*
> ```Diff
>  )
> +
> +#keep
> ```

Perhaps worth adding a comment/readme somewhere in this directory to make sense of these patches.

**Comment by otan** [comment]
noice!

**Review by rickystewart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58660)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[BUILD.bazel, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYNtFo3YkYNn0_0rGm:-MQYjnyA9hKix619-tI1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/BUILD.bazel#L16)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This comment could be updated.
</blockquote></details>

Done.
___
*[DEPS.bzl, line 2842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYa1CI0encbAhJKcyz:-MQYiHvQ5474qCYujk5h:b-gidc6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/DEPS.bzl#L2842)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Mildly surprised these diffs didn't need explicit `# keep` directives. If we were to bump any of these dependencies, do these edits disappear?
</blockquote></details>

No -- I've been playing with it a lot and Gazelle is really robust about these changes. `make bazel-generate` has never trampled any of the changes I make to `DEPS.bzl` or `WORKSPACE`.
___
*[WORKSPACE, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYaRbj22mBaFM3M9Xs:-MQYiXQr-Xn3OSe-vPlx:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/WORKSPACE#L88)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Doesn't have to be this PR, but now that we're generating pb.go files under bazel, we'll want to tackle https://github.com/cockroachdb/cockroach/issues/58227 next. The SHA in use here is not the one we're using through our Makefile-based builds I think IIRC.
</blockquote></details>

ack
___
*[build/patches/BUILD.bazel, line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYb0nbA_aGoAe80YwP:-MQYjGn23IoXSTA5riw3:bg9leyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb71d88fb96a4ded0eb5414eb2eb88faaaf5895/build/patches/BUILD.bazel#L)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Why this empty BUILD file? Could be removed I think.
</blockquote></details>

No, removing it introduces this error: 

```
ERROR: An error occurred during the fetch of repository 'io_etcd_go_etcd_raft_v3':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ricky/be70b24e7357091e16c49d70921b7985/external/bazel_gazelle/internal/go_repository.bzl", line 192, column 10, in _go_repository_impl
		patch(ctx)
	File "/private/var/tmp/_bazel_ricky/be70b24e7357091e16c49d70921b7985/external/bazel_gazelle/internal/go_repository.bzl", line 282, column 33, in patch
		patchfile = ctx.path(patchfile),
Error in path: Unable to load package for @cockroach//build/patches:io_etcd_go_etcd_raft_v3.patch: BUILD file not found in directory 'build/patches' of external repository @cockroach. Add a BUILD file to a directory to mark it as a package.
ERROR: /Users/ricky/go/src/github.com/cockroachdb/cockroach/pkg/cli/BUILD.bazel:3:11: //pkg/cli:cli depends on @io_etcd_go_etcd_raft_v3//raftpb:raftpb in repository @io_etcd_go_etcd_raft_v3 which failed to fetch. no such package '@io_etcd_go_etcd_raft_v3//raftpb': Unable to load package for @cockroach//build/patches:io_etcd_go_etcd_raft_v3.patch: BUILD file not found in directory 'build/patches' of external repository @cockroach. Add a BUILD file to a directory to mark it as a package.
```
___
*[build/patches/com_github_cockroachdb_errors.patch, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58660#-MQYbBrf2Ox2rszWZt22:-MQYjmyaEqeMULBpGGD6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d628566ccac829ac4fdfbd218a951de0706542c/build/patches/com_github_cockroachdb_errors.patch#L15)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Perhaps worth adding a comment/readme somewhere in this directory to make sense of these patches.
</blockquote></details>

Done.

**Comment by irfansharif** [comment]
Ah, gotcha; minor nit: add a comment to the empty BUILD file.

**Comment by rickystewart** [comment]
Yes, [already done](https://github.com/cockroachdb/cockroach/pull/58660/files#diff-40888ef08281e91675ad42ddab209aa1d8fc8edcfe5467240d37aedd5f772b17) :)

**Pull request merged**
