### PR TITLE
sql: allow UDFs with SETOF return types

### LINKED ISSUE #86391: sql: udf to support `SETOF` return types
**Describe the solution you'd like**
`SETOF` return type syntax is accepted but unimplemented error is returned because execution doesn't support that yet. We need to add support in execution before we can remove the unimplemented error.

Epic: CRDB-18734

### PR DESCRIPTION
**Pull request by mgartner**
#### distsql: check projectSetNode exprs for distribution recommendation

Previously, the scalar expressions within a `projectSetNode` were not
checked for their ability to be distributed. This commit fixes this.

Release note: None

#### sql: use `eval.ValueGenerator` for evaluation of routines

This commit creates a new implementation of the `eval.ValueGenerator`
that is used to evaluate `tree.Routine` expressions. This will allow for
a more unified implementation of both scalar and set-returning UDFs in a
future commit.

Release note: None

#### sql: allow UDFs with SETOF return types

Set-returning UDFs can now be created by specifying a `SETOF` return
type. For example:

    CREATE FUNCTION fn() RETURNS SETOF INT LANGUAGE SQL AS $$
      SELECT a FROM abc;
    $$

Fixes #86391

Release note (sql change): Set-returning user-defined functions can now
be created by specific a `SETOF` return type.

### CODE REVIEW

**Comment by mgartner** [comment]
Hold off on reviewing - there's still some bugs to iron out.

**Comment by mgartner** [comment]
This is ready for a look.

**Review by rharding6373 — APPROVED** [review]
This is fantastic. Only have minor optional nits. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-:-NNmmutpAFHbYs0OJ_iQ:bhgsc7f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/routine.go` line 63 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmMNtx4iloFAo7pJRk:-NNmMNtx4iloFAo7pJRl:bhfouhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/routine.go#L63)):*
> ```Go
> 		res = row[0]
> 	}
> 	if len(expr.Args) == 0 && !expr.EnableStepping {
> ```

Are expr.Args expected to be different from args? From the call sites it looks like they currently aren't different in terms of length. For consistency, may be better to use args here, or add a comment to help point readers.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 683 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmM-6zD9RXWgBFHtOd:-NNmM-6zD9RXWgBFHtOe:b-3uqy4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/optbuilder/scalar.go#L683)):*
> ```Go
> 			// first can simply be ignored. The limit could be beneficial
> 			// because it could allow additional optimization.
> 			if o.Class != tree.GeneratorClass {
> ```

minor nit: add a var `isSetReturning := o.Class == tree.GeneratorClass` for readability.

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 27 of 27 files at r3, 1 of 1 files at r4, 26 of 27 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96698)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 777 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmyfmK16FFGpp-kP3N:-NNmyfmK16FFGpp-kP3O:b-ibrxj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/optbuilder/scalar.go#L777)):*
> ```Go
> 				),
> 			},
> 			out,
> ```

What happens here if the UDF is non-scalar? Postgres gives `set-returning functions are not allowed in CASE` if you attempt to use an SRF (UDF or otherwise) in a CASE statement.
___
*[`pkg/sql/opt/ordering/scan.go` line 171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmpN9985Fv7fvKoLrW:-NNmpN9985Fv7fvKoLrX:b5ii3of) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/ordering/scan.go#L171)):*
> ```Go
> 			// cannot be determined. This is possible when a memo is not fully
> 			// optimized.
> 			return false
> ```

[super nit] Could do `return ok && reverse`
___
*[`pkg/sql/logictest/testdata/logic_test/udf_setof` line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmulYF8gZ0zVFxhgEp:-NNmulYF8gZ0zVFxhgEq:b-3ere72) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/logictest/testdata/logic_test/udf_setof#L128)):*
> ```
> # Nested set-returning functions are not yet supported.
> statement error unimplemented: nested set-returning functions
> SELECT all_a_lt(all_a())
> ```

Other cases that we could test:
- UDF that returns table type (both as projection and table source) - do we have any tests that use a UDF that returns table type as a table source, scalar or not?
- UDF that returns a tuple with multiple labeled elements (see #58438)
- strict UDF that takes at least one argument (see above question)
- (error) test with a UDF that returns multiple columns

Example for the first point:
```
--Setup
CREATE TYPE e_93314 AS ENUM ('a', 'b');
CREATE TABLE t_93314 (i INT, e e_93314);
INSERT INTO t_93314 VALUES (1, 'a');

CREATE OR REPLACE FUNCTION f_93314 () RETURNS t_93314 AS
$$
  SELECT i, e
  FROM t_93314
  ORDER BY i
  LIMIT 1;
$$ LANGUAGE SQL;

--Postgres
postgres=# SELECT * FROM f_93314();
 i | e
---+---
 1 | a
(1 row)

--UDFs
root@localhost:26257/defaultdb> SELECT * FROM f_93314();
  f_93314
-----------
  (1,a)
(1 row)
```
Is this a known issue?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96698)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/routine.go` line 63 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmMNtx4iloFAo7pJRk:-NOBA3AR60hDM0562M7H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/routine.go#L63)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Are expr.Args expected to be different from args? From the call sites it looks like they currently aren't different in terms of length. For consistency, may be better to use args here, or add a comment to help point readers.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 683 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmM-6zD9RXWgBFHtOd:-NOBAIGa4LWWZ9kZXr17:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/optbuilder/scalar.go#L683)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

minor nit: add a var `isSetReturning := o.Class == tree.GeneratorClass` for readability.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 777 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmyfmK16FFGpp-kP3N:-NOBs7_MCpzTcvg8KjAM:blmy9js) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/optbuilder/scalar.go#L777)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What happens here if the UDF is non-scalar? Postgres gives `set-returning functions are not allowed in CASE` if you attempt to use an SRF (UDF or otherwise) in a CASE statement.
</blockquote></details>

I couldn't figure out a clever way to solve this so I've just put this logic in the evaluation of the routine for now.
___
*[`pkg/sql/opt/ordering/scan.go` line 171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmpN9985Fv7fvKoLrW:-NOBB1fA1ZEn1727r4Zu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/ordering/scan.go#L171)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[super nit] Could do `return ok && reverse`
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_setof` line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmulYF8gZ0zVFxhgEp:-NOBCJbXAdcQ94T8ha9L:b-1k9rae) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/logictest/testdata/logic_test/udf_setof#L128)):*
> UDF that returns table type (both as projection and table source) - do we have any tests that use a UDF that returns table type as a table source, scalar or not?

Good catch. This was not a known issue, AFAIK, so I created an issue to track this: #97059.

> UDF that returns a tuple with multiple labeled elements (see #58438)

I'm not exactly sure what you mean by this. I added some tests - let me know if a case you were thinking about is not covered.

> strict UDF that takes at least one argument (see above question)

Great catch. I couldn't figure out a clean way to do this with a CASE/COALESCE or any similar expression, unfortunately. For now, I've implemented this in the evalatuion logic, which should work fine for now because we are not inlining SETOF UDFs. In order to inline them, we'll need to figure out an expression that can be used to achieve STRICT behavior.

> (error) test with a UDF that returns multiple columns

Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work! This is a big milestone!

> Reviewed 1 of 28 files at r6, 28 of 29 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-:-NOCXqTi-lTFPiOVXYck:bqhz71k)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 777 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmyfmK16FFGpp-kP3N:-NOCD0gY26r-w5lZxl_S:bjfwka5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/optbuilder/scalar.go#L777)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I couldn't figure out a clever way to solve this so I've just put this logic in the evaluation of the routine for now.
</blockquote></details>

Seems related to #94890, and probably a similar fix too. I'll add some type-checking that will produce the expected error when I put up a fix for that.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_setof` line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmulYF8gZ0zVFxhgEp:-NOCL0Dw6CY59FosES_Y:b-p171vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/logictest/testdata/logic_test/udf_setof#L128)):*
>I'm not exactly sure what you mean by this. I added some tests - let me know if a case you were thinking about is not covered.

Hm, I'm actually not sure exactly how to make a function return a labeled tuple type... I mean a type like that of this expression for context: `((1, 2) AS a, b)`. And actually, I don't think it should be a problem anyway until #97059 is fixed, since the difficulty is in the logic that decides when to unnest the function return type into multiple columns. I think it's good for now.

>I couldn't figure out a clean way to do this with a CASE/COALESCE or any similar expression, unfortunately.

I think we could get the expected short-circuiting behavior using a cross join ON TRUE where the other input returns no rows if the argument is NULL, and one row otherwise. Maybe best to leave for the future, though. We'd have to make sure rules don't prevent the short-circuiting.

The tests here LGTM.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96698)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 777 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96698#-NNmyfmK16FFGpp-kP3N:-NOFbyRR63N7pwvfsYnZ:b-g07dom) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2f6d773ccccfc964a92eddd2a639c8de824e68/pkg/sql/opt/optbuilder/scalar.go#L777)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Seems related to #94890, and probably a similar fix too. I'll add some type-checking that will produce the expected error when I put up a fix for that.
</blockquote></details>

Oh sorry, I was referring the STRICT logic for SETOF UDFs.

CRDB allows any set-returning function in a CASE expression, UDF or built-in, while PG does not. I've created #97119 to track this and the related bug I found with these types of expressions.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
