### PR TITLE
sql: basic SCATTER implementation

### PR DESCRIPTION
**Pull request by RaduBerinde**
Initial simplistic implementation of SCATTER: we pick three random stores in the
cluster for each range. The intention is to later replace this with a complete
implementation which gets replica stores recommendations according to the zone
config.

Updates #13665.

### CODE REVIEW

**Comment by petermattis** [comment]
The general approach in the `server,storage` packages looks like what I was imagining.

I took a brief look at the `sql` changes before realizing that someone from sql-land should review them.

---

Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/server/server.go, line 283 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-KhSvC7kPSRyFYCmWasO:-KhSvC7kPSRyFYCmWasP:b2l5zel) ([raw file](https://github.com/cockroachdb/cockroach/blob/bca343c755c95daaec46e434402d923d892110ef/pkg/server/server.go#L283)):*
> ```Go
> 		HistogramWindowInterval: s.cfg.HistogramWindowInterval(),
> 
> 		ClusterStoresUpcall: func() []roachpb.ReplicationTarget {
> ```

Might want to call this `ReplicationCandidates` or something like that. Also, I think you'll want to pass in the range ID and the implementation should eventually call `storage.allocationCandidates` after retrieving the constraints for the specified range ID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-:-KhSx5GRgnLvKufDY6GT:bpwya3s)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/server/server.go, line 283 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-KhSvC7kPSRyFYCmWasO:-KhT4CLf1K5d9Zh-qObp:b-d48rp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bca343c755c95daaec46e434402d923d892110ef/pkg/server/server.go#L283)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Might want to call this `ReplicationCandidates` or something like that. Also, I think you'll want to pass in the range ID and the implementation should eventually call `storage.allocationCandidates` after retrieving the constraints for the specified range ID.
</blockquote></details>

Yes, the intention is to replace this with the real API. Defining that API is not trivial though so I didn't do it in this change. The complication is that we will want to do multiple relocations in parallel, so we need an API that works for multiple recommendations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-:-KhTNdhx937EPXGDwPjW:bnfp4nl)*

**Comment by danhhz** [comment]
Thanks for doing this radu! Do you think we'll be able to move some of this logic down into an admin kv command? RESTORE can't use this as is, since the table won't exist (and thus won't resolve) when the splitting needs to be done

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-:-KhTQ9pkHjHe6Rw0ePYE:blfa45j)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-:-KhTRNwK6JrGAW0nzwDL:bnfp4nl)*

**Comment by RaduBerinde** [comment]
@danhhz Sigh...I was under the impression that restore can use the SCATTER command as proposed. This should have been made clear in the RFC discussion for this (#14146).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-:-KhTZQLQgcqSe0a1Km7a:b-vgjn5s)*

**Comment by danhhz** [comment]
I reread the comment thread on that rfc and realized I should have been way more explicit. I'm sorry.

I don't think this is at all incompatible with what we need for RESTORE. It should be pretty trivial to make an admin kv command that takes the spans to be scattered as input and with the contents of your scatterNode.Next as its impl. I'm happy to do that. This lgtm

I do also think this is incredibly useful as a SQL command. I think both interfaces should exist

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14796#-:-KhTghDQn8WCIVeAkAxn:b-iwjtq6)*

**Comment by RaduBerinde** [comment]
Thanks Dan!

**Pull request merged**
