### PR TITLE
workload/movr: add --multi-region and --survive settings

### PR DESCRIPTION
**Pull request by otan**
Release note (general change): Added multi-region workloads for
`cockroach demo movr --geo-partitioned-replicas. Specifying
`--multi-region` allows for multi-region workloads, and specifying
`--survive` allows for surviving AZ or REGION failures.

### CODE REVIEW

**Comment by otan** [comment]
lol oops, not ready yet!

**Comment by awoods187** [comment]
Can we make sure this work is in sync with what @ericharmeling has been working on in https://github.com/cockroachdb/movr

**Comment by otan** [comment]
it is!

**Review by ajstorm — CHANGES_REQUESTED** [review]
Nice changes!  Mostly nits, but one question about RBR.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-:-MaFcIgYERN-oAAEh8-l:b-92hr4y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/movr/movr.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-MaFZbDW0tT4OcZRtA1X:-MaFZbDW0tT4OcZRtA1Y:b-s6lnsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/47652a66fe36808121b242be7c160f017cb25afd/pkg/workload/movr/movr.go#L57)):*
> ```Go
>   address VARCHAR NULL,
>   credit_card VARCHAR NULL,
>   PRIMARY KEY (%[1]sid ASC)
> ```

clever
___
*[pkg/workload/movr/movr.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-MaFa4D521IZW1arq5Pu:-MaFa4D521IZW1arq5Pv:b-qd8tmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/47652a66fe36808121b242be7c160f017cb25afd/pkg/workload/movr/movr.go#L317)):*
> ```Go
> 					return err
> 				}
> 				for _, rbrTable := range []string{
> ```

Nit: For readability and maintainability, does it make sense to pull this slice out of the for loop and give it a name?  `regionalByRowTables`?
___
*[pkg/workload/movr/movr.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-MaFb4KDCKUvxW9cX-i8:-MaFb4KDCKUvxW9cX-i9:btj5at6) ([raw file](https://github.com/cockroachdb/cockroach/blob/47652a66fe36808121b242be7c160f017cb25afd/pkg/workload/movr/movr.go#L329)):*
> ```Go
> 								`ALTER TABLE %s ADD COLUMN crdb_region crdb_internal_region NOT NULL AS (
> 								CASE
> 									WHEN city IN ('new york', 'boston', 'washington dc') THEN 'us-east1'
> ```

Nit: Does it make sense to slicify these city names too?  Might make it easier if we ever try to change them down the road,
___
*[pkg/workload/movr/movr.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-MaFc1sdAyASNlOesiOR:-MaFc1sdAyASNlOesiOS:bfvp6vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/47652a66fe36808121b242be7c160f017cb25afd/pkg/workload/movr/movr.go#L335)):*
> ```Go
> 							END) STORED`,
> 								rbrTable,
> 							),
> ```

Do we also need an `ALTER TABLE ... REGIONAL BY ROW AS` statement here?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/workload/movr/movr.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-MaFc1sdAyASNlOesiOR:-MaQG6OEDT1Tzt2Up3Pd:bckslzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/47652a66fe36808121b242be7c160f017cb25afd/pkg/workload/movr/movr.go#L335)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we also need an `ALTER TABLE ... REGIONAL BY ROW AS` statement here?
</blockquote></details>

nope, crdb_region is automatically made up.

**Review by ajstorm — APPROVED** [review]
:lgtm: 

Is there a logical place to add tests for this stuff?  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-:-MaTQxygBcfP3v43kw59:bh79o2t)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/workload/movr/movr.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-MaFc1sdAyASNlOesiOR:-MaTQfSzAuqZx4reVNoW:buua9xb) ([raw file](https://github.com/cockroachdb/cockroach/blob/47652a66fe36808121b242be7c160f017cb25afd/pkg/workload/movr/movr.go#L335)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nope, crdb_region is automatically made up.
</blockquote></details>

Ahh, my bad.  Reviewable hid the RBR call below because it wasn't new.  Didn't realize that there was a previous PR which did that part.

**Comment by otan** [comment]
> Is there a logical place to add tests for this stuff?

the only tests that i saw were in a disabled test file (test_demo_partitioning.tcl), which was disabled because it can timeout/flake on CI. not game for that!

**Comment by otan** [comment]
bors r=ajstorm

**Review by ajstorm — COMMENTED** [review]
Can we at least open an issue for adding some testing?  It makes me uncomfortable that we have no testing around something we're building demos around.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65493#-:-MaYgsTw-rVaBq3onrwZ:b-26zwmf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
