### PR TITLE
kvserver: metamorphically enable `kv.expiration_leases_only.enabled`

### LINKED ISSUE #98126: kvserver: metamorphically enable expiration leases
When #94457 lands, we should metamorphically enable expiration leases in various tests. In particular, to verify the new quiescence logic in #97289.

Jira issue: CRDB-25091

Epic CRDB-25199

### PR DESCRIPTION
**Pull request by erikgrinaker**
Resolves #98126.

Epic: none
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
This has passed a few CI runs now while the setting was always enabled.

A few of the tests that explicitly disable this metamorphism warrant further investigation, opened #98618 to follow up.

**Review by andrewbaptist — APPROVED** [review]
:lgtm: Minor nit - could you add a reference to #98618 next to the TODO comments (and also list them in that issue). It would be good to track them all down as I'm worried they will be hard to find later. Thanks and I'm glad you made this metamorphic like you do as it will really get good coverage of all these tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98516#-:-NQh8_Kr1kIOQYLrVZHg:bjmgfz4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by erikgrinaker — COMMENTED** [review]
Sure, done. Should be pretty easy to find anyway, just by searching for the setting. I'm going to go over these shortly in any case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98516#-:-NQjyef264fzuYUsETt7:bled2pv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Comment by erikgrinaker** [comment]
bors r-

```
=== RUN   TestStoreCapacityAfterSplit
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/c6156e329ef0e4dd2f31712f19cdbe2a/logTestStoreCapacityAfterSplit1208026245
    test_log_scope.go:79: use -show-logs to present logs inline
    testcluster.go:1059: condition failed to evaluate within 45s: lease still an expiration based lease
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/c6156e329ef0e4dd2f31712f19cdbe2a/logTestStoreCapacityAfterSplit1208026245
--- FAIL: TestStoreCapacityAfterSplit (46.28s)
```

**Comment by erikgrinaker** [comment]
Ended up fixing the failures in #98618 here directly. They were just test artifacts, didn't find any bugs.

**Comment by erikgrinaker** [comment]
bors retry

**Pull request merged**
