### PR TITLE
release-21.2: xform: hoist projection from join only for canonical scans/selects

### LINKED ISSUE #79943: opt: join reordering and project pull-ups causes OOM
roachtest.sqlsmith/setup=rand-tables/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4888455&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4888455&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl) on master @ [cc07b5e7e670097560cb8412b380484773df1e96](https://github.com/cockroachdb/cockroach/commits/cc07b5e7e670097560cb8412b380484773df1e96):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
	sqlsmith.go:284,sqlsmith.go:304,test_runner.go:875: ping node 1: dial tcp 35.231.160.85:26257: connect: connection refused
		previous sql:
		WITH
			with_29360 (col_177842, col_177843)
				AS (
					SELECT
						NULL AS col_177842, (NULL, ARRAY[(-22928):::INT8,(-17919):::INT8]) AS col_177843
					FROM
						defaultdb.public.table1@[0] AS tab_93041,
						defaultdb.public.table2@table2_col2_16_col2_11_col2_8_col2_0_key AS tab_93042,
						defaultdb.public.table2@[0] AS tab_93043,
						defaultdb.public.table2@table2_col2_16_col2_11_col2_8_col2_0_key AS tab_93044
					WHERE
						EXISTS(
							WITH
								with_29359 (col_177840)
									AS (
										SELECT
											*
										FROM
											(VALUES ((-0.6331317560465642):::FLOAT8), (NULL)) AS tab_93045 (col_177840)
									)
							SELECT
								'0107000020E610000000000000':::GEOGRAPHY AS col_177841
							FROM
								with_29359 AS cte_ref_8529
						)
				)
		SELECT
			'tvg':::rand_typ_1 AS col_177844,
			('1994-10-29':::DATE, ARRAY[(-4656):::INT8,(-4371):::INT8,(-19496):::INT8]) AS col_177845,
			cte_ref_8530.col_177843 AS col_177846,
			'tvg':::rand_typ_1 AS col_177847,
			cte_ref_8531.col_177843 AS col_177848,
			'tvg':::rand_typ_1 AS col_177849
		FROM
			with_29360 AS cte_ref_8530, with_29360 AS cte_ref_8531, with_29360 AS cte_ref_8532
		ORDER BY
			cte_ref_8532.col_177842 DESC;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by msirek**
Backport 1/1 commits from #80212.

/cc @cockroachdb/release

---

Fixes #79943

Previously, HoistProjectFromInnerJoin would explore joins with the right
input projection pulled up to the parent of the join, no matter the type
of relation underneath the projection.

This was inadequate because queries involving many joins may invoke the
ReorderJoins rule many times, which creates many new join expressions
(orders of magnitude greater than the number of joins in the query),
which need to be explored. Each of those may trigger projection pull-up,
adding a new join expression to a memo group, further increasing the
search space. Each of those added join expressions may themselves have a
subtree of joins below them involving projections which may fire the
rule again, leading to an explosion of rule firings and a query which
never completes optimization (hangs).

To address this, this patch alters the conditions required to fire
HoistProjectFromInnerJoin so that when the right input of the join is a
projection, the input to the projection must be a canonical scan or a
select from a canonical scan.

HoistProjectFromInnerJoin, added through #59780, is meant to enable more
lookup joins because converting a projection on the right side of a join
into a canonical scan allows GenerateLookupJoins to fire. Likewise,
other join transformations such as SplitDisjunctionOfJoinTerms may
require either a canonical scan or a select from a canonical scan as
join inputs in order to fire.  Other cases are unlikely to cause any new
join transformations to fire since those rules check for canonical scans
as input, so skipping their exploration will not result in any missed
optimizations.

Release note (bug fix): Prior to this fix, queries with many joins and
projections of multicolumn expressions, e.g. col1 + col2, either
present in the query or within a virtual column definition, could
experience very long optimization times or hangs, where the query is
never sent for execution.

**sql: Add disable_hoist_projection_in_join_limitation session flag**

This commit adds the disable_hoist_projection_in_join_limitation session flag.
    
Release note: none

**opttester: support session settings in opt tests**

This commit adds the set opttest flag which can be used to set
session flags via "set=flagname=value".

Release note: none

Release justification: Low risk fix for lengthy exploration time on complex queries.

### CODE REVIEW

**Comment by rytaft** [comment]
Are you still looking for approval on this PR, or was there another one opened in its place?

**Review by msirek — COMMENTED** [review]
Yes, this needs approval.  It does pick up one commit from #85935, which has some open discussions though, so maybe that one should be approved first.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-:-N9qZbKJCsi3F9zfM08H:b-uh18n5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 9 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-:-NA6WH_j9gD_bELxcd-_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-NA6W8rl8Xyef91SQcOF:-NA6W8rl8Xyef91SQcOG:b-rqxxu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e33f2b5cdc5e432214616a70f2056100ade66f4/pkg/sql/opt/testutils/opttester/opt_tester.go#L247)):*
> ```Go
> 	// UseMultiColStats is the value for SessionData.OptimizerUseMultiColStats.
> 	// It defaults to true in New.
> 	UseMultiColStats bool
> ```

doesn't look like this is used.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85872)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-NA6W8rl8Xyef91SQcOF:-NAAkM_ZAC6VLEbkn6Lb:b-33vprz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e33f2b5cdc5e432214616a70f2056100ade66f4/pkg/sql/opt/testutils/opttester/opt_tester.go#L247)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

doesn't look like this is used.
</blockquote></details>

Removed it, thanks.

**Review by rytaft — COMMENTED** [review]
> Reviewed 11 of 11 files at r4, 9 of 9 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85872)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 497 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-NAAm9Yr2j63MDQgsVR3:-NAAm9Yr2j63MDQgsVR4:b-6eki3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b2a2fd34a1f6ff4c7c8dabbae7121dd27c29a3d/pkg/sql/opt/testutils/opttester/opt_tester.go#L497)):*
> ```Go
> //         ----
> //
> >>>>>>> 40a8d44c26... Address review comments
> ```

leftover

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85872)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 497 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-NAAm9Yr2j63MDQgsVR3:-NAAmq1i1-SbPevO9H4Q:b4qqjev) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b2a2fd34a1f6ff4c7c8dabbae7121dd27c29a3d/pkg/sql/opt/testutils/opttester/opt_tester.go#L497)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

leftover
</blockquote></details>

Thanks! fixed

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-:-NAAoJdTC7SjA62-QqqN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
LGTM

**Review by msirek — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85872#-:-NAMcVyr3oUCUNE-gZn1:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
