### PR TITLE
builtins: implement ST_IsPolygonCW/CCW and ST_ForcePolygonCW/CCW

### LINKED ISSUE #48935: geo/geomfn: implement ST_ForcePolygonCCW({geometry})
Implement `ST_ForcePolygonCCW` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_ForcePolygonCCW.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Adaptable from CCW code in pkg/geo

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:37:11Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48936: geo/geomfn: implement ST_ForcePolygonCW({geometry})
Implement `ST_ForcePolygonCW` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_ForcePolygonCW.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Adaptable from CCW code in pkg/geo

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:37:11Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48956: geo/geomfn: implement ST_IsPolygonCCW({geometry})
Implement `ST_IsPolygonCCW` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_IsPolygonCCW.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Adaptable from CCW code in pkg/geo

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48957: geo/geomfn: implement ST_IsPolygonCW({geometry})
Implement `ST_IsPolygonCW` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_IsPolygonCW.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Adaptable from CCW code in pkg/geo

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Resolves #48956
Resolves #48957
Resolves #48935
Resolves #48936 

Release note (sql change): implement the ST_IsPolygonCW,
ST_IsPolygonCCW, ST_ForcePolygonCW and ST_ForcePolygonCCW builtins.

Release justification: low risk, high benefit changes

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53243)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[docs/generated/sql/functions.md, line 1343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53243#-MFbHwb32h4uqM8J4o-j:-MFbHwb32h4uqM8J4o-k:bnnjvmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/84553d0993b64d286f3774ba921ca7f33023f7bc/docs/generated/sql/functions.md#L1343)):*
> ```Markdown
> <tr><td><a name="st_isempty"></a><code>st_isempty(geometry: geometry) &rarr; <a href="bool.html">bool</a></code></td><td><span class="funcdesc"><p>Returns whether the geometry is empty.</p>
> </span></td></tr>
> <tr><td><a name="st_ispolygonccw"></a><code>st_ispolygonccw(geometry: geometry) &rarr; <a href="bool.html">bool</a></code></td><td><span class="funcdesc"><p>Returns whether the Polygon objects inside the Geometry all have CCW orientation. Non-Polygon objects are considered counter-clockwise.</p>
> ```

this means outer ring CCW and inner ring CW, yes?
___
*[pkg/geo/geomfn/orientation.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53243#-MFcSoKk8p8UzMg_EJiR:-MFcSoKk8p8UzMg_EJiS:b-lp8mqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd679561f52bc92cfdfa6ae1580004bdbae81544/pkg/geo/geomfn/orientation.go#L124)):*
> ```Go
> 				coords := g.LinearRing(i).FlatCoords()
> 				for c := 0; c < len(coords); c += g.Stride() {
> 					coords[c], coords[c+1] = coords[c+1], coords[c]
> ```

I didn't understand this -- isn't this switching an (X, Y) point to be (Y, X) instead of reversing the ordering across the points.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53243)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[docs/generated/sql/functions.md, line 1343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53243#-MFbHwb32h4uqM8J4o-j:-MFcX6tb5ECplT2l5wxb:b-gnkuxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/84553d0993b64d286f3774ba921ca7f33023f7bc/docs/generated/sql/functions.md#L1343)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this means outer ring CCW and inner ring CW, yes?
</blockquote></details>

Yep! fixed up the docos.
___
*[pkg/geo/geomfn/orientation.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53243#-MFcSoKk8p8UzMg_EJiR:-MFcX8T383Dp0NJ3aWNJ:b-xvfxbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd679561f52bc92cfdfa6ae1580004bdbae81544/pkg/geo/geomfn/orientation.go#L124)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand this -- isn't this switching an (X, Y) point to be (Y, X) instead of reversing the ordering across the points.
</blockquote></details>

Yeah uhm, good catch.

Testing with strict squares doesn't help you catch this bug :( added a test that would've caught it.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53243#-:-MFfRFp5C37Xuk3bnLEU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geomfn/orientation.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53243#-MFcSoKk8p8UzMg_EJiR:-MFfPqbnCOQL9ryHMnY3:b-eqw1gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd679561f52bc92cfdfa6ae1580004bdbae81544/pkg/geo/geomfn/orientation.go#L124)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yeah uhm, good catch.

Testing with strict squares doesn't help you catch this bug :( added a test that would've caught it.
</blockquote></details>

Remind me, the first and last coordinate is explicitly the same in `LinearRing` and not implied by the type itself, yes? So the minimum number of coordinates is 4? So `len(coords)/2` is like a `pivot` and all points before this pivot need to be swapped with points after the pivot. The pivot itself might be in the middle of a point, if there are an odd number of points in the ring, but that point stays where it is.
Could you add a code comment that says something to this effect.

**Comment by otan** [comment]
___
*[pkg/geo/geomfn/orientation.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53243#-MFcSoKk8p8UzMg_EJiR:-MFfULEtB98u5yzqOZyC:b-fx5km7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd679561f52bc92cfdfa6ae1580004bdbae81544/pkg/geo/geomfn/orientation.go#L124)):*
> Remind me, the first and last coordinate is explicitly the same in LinearRing and not implied by the type itself, yes? So the minimum number of coordinates is 4?

Yep

>  So len(coords)/2 is like a pivot and all points before this pivot need to be swapped with points after the pivot. The pivot itself might be in the middle of a point, if there are an odd number of points in the ring, but that point stays where it is. Could you add a code comment that says something to this effect.

Ok

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
