### PR TITLE
opt: reduce optstepsweb max query param length to ~7000

### PR DESCRIPTION
**Pull request by mgartner**
I encountered 503 errors from Github when a link generated by
`optstepsweb` created a URL with ~7400 characters. Using a fragment
(which is not sent to the server) instead of a query parameter (which is
sent to the server) prevents the link from causing an error.

See #71212 for more context.

Release justification: This is a test-only change.

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77989#-:-MyK9OhNCwCAoe31S4O0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by cucaroach — COMMENTED** [review]
:LGTM:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77989#-:-MyMKjA46ONDgFurDtR8:bmxilld)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
