### PR TITLE
storage: mvcc_stats_test add new range tombstone ops

### LINKED ISSUE #87384: storage: add `MVCCGarbageCollectRangeKeys` to `TestMVCCStatsRandomized`
Jira issue: CRDB-19313

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by aliher1911**
Previously TestMVCCStatsRandomized was not exercising range tombstone
GC operations. This commit adds range tombstone GC operations to the test.

Release note: None
Release justification: Test only change.

Fixes: #87384

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Thanks! Did you confirm that this test fails when GC didn't handle range tombstone merges?

**Comment by erikgrinaker** [comment]
Actually, isn't this test just going to write single range tombstones across the entire keyspan? How will that exercise merges when there's only a single stack?

**Comment by aliher1911** [comment]
Yeah this is a bit limited test that just updates randomly generated history for a single key.
It still makes sense to update it to include range key deletions and GC, but it won't help with various range key overlap cases.

Maybe retrofitting stats to randomized GC tests would be a right solution as all the generation infrastructure is already in place.

**Review by erikgrinaker — APPROVED** [review]

**Comment by aliher1911** [comment]
Closing this as Tobi added the same.

**Comment by aliher1911** [comment]
I just realized that range tombstone was added but GC was not. I'll rebase and only keep that.

**Pull request merged**
