### PR TITLE
spanconfig,kv: merge adjacent ranges with identical configs 

### LINKED ISSUE #66063: config,kvserver: don't unconditionally split on table boundaries for the host tenant
**Is your feature request related to a problem? Please describe.**

On the host tenant, we unconditionally split on all table/index/partition boundaries. There are two reasons this might have been desirable:
(a) Performance: splitting off each table/index/partition into its own range guarantees independent range processing of the data within that table/index/partition.
(b) Diverging zone configs: if two tables have different zone configs attached to them (remember: the "unit" of what a zone config can apply to is a db/table/index/partition), that necessarily implies a split. By unconditionally splitting on table boundaries, we didn't have to write code to reason about adjacent-keys-but-from-different-tables-with-diverging-zone-configs.

**Describe the solution you'd like**

For (a) we could support syntax for users to specify intentional split on table boundaries [#65903](https://github.com/cockroachdb/cockroach/issues/65903). For (b), we're soon going to introduce zone configs for secondary tenants. By default we don't split on table boundaries for secondary tenants due to the order-of-magnitude ranges that would create, but with secondary tenant zone configs, we're opening the door to tenant-initiated splits in the tenant keyspace. That means we're going to write code that reasons about adjacent-keys-but-from-different-tables-with-diverging-zone-configs, to determine where the necessary split points would be, so we may as well coalesce host tenant tables into single ranges when possible. If secondary indexes or groups of tables are placed on the same range, txns that span them could benefit from 1PC optimizations.

**Describe alternatives you've considered**

Keeping the status quo. I think this issue only really matters for on-prem customers (without multi-tenancy) where each table would today create a new range. For users with many small tables, the overhead of the very many tiny ranges might be undesirable. With tenant zone configs we'll soon be addressing the O(descriptors) bottleneck that today prevent having too many tables. Perhaps it's time to look ahead.

Jira issue: CRDB-7866

### LINKED ISSUE #72389: kv: collapse adjacent span configs to reduce number of necessary splits
After #67679 + enabling the infrastructure by default, we'll get to a place where we'll split on every schema object boundary for all tenants (including, as before, the host tenant). That's mighty expensive and comes with a lot of overhead and is a scalability bottleneck for how many tenants we can pack into the same cluster. #70555 proposes some rudimentary guardrails, but on the KV side we can do better. The spanconfig.Store introduced in #70287 can be augmented to recognize that certain span config entries are adjacent to one another (S1.EndKey == S2.Key) and have the same configs. We expect the majority of span configs to be applicable here, given almost everything inherits from RANGE DEFAULT. When recognizing such an adjacency, we can avoid unconditionally splitting on that boundary. This should let us claw back a low range count with secondary tenants while still enabling multi-tenant zone configs.

Some neighboring issues: 
- #66063 (this same optimization can be applied to the host tenant)
- #65903 (might still be desirable to induce manual splits on table boundaries, for say, perf reasons)
- #65726 (orthogonal issue describing a scheme to reduce the total number of ranges in the system)

Jira issue: CRDB-11130

### PR DESCRIPTION
**Pull request by irfansharif**
**spanconfig,kv: merge adjacent ranges with identical configs**

Fixes #72389.
Fixes #66063 (gated behind a cluster setting).

This should drastically reduce the total number of ranges in the system,
especially when running with a large number of tables and/or tenants. To
understand what the new set of split points are, consider the following
test snippet:

    exec-sql tenant=11
    CREATE DATABASE db;
    CREATE TABLE db.t0();
    CREATE TABLE db.t1();
    CREATE TABLE db.t2();
    CREATE TABLE db.t3();
    CREATE TABLE db.t4();
    CREATE TABLE db.t5();
    CREATE TABLE db.t6();
    CREATE TABLE db.t7();
    CREATE TABLE db.t8();
    CREATE TABLE db.t9();
    ALTER TABLE db.t5 CONFIGURE ZONE using num_replicas = 42;
    ----

    # If installing a unique zone config for a table in the middle, we
    # should observe three splits (before, the table itself, and after).

    diff offset=48
    ----
    --- gossiped system config span (legacy)
    +++ span config infrastructure (current)
    ...
     /Tenant/10                                 database system (tenant)
     /Tenant/11                                 database system (tenant)
    +/Tenant/11/Table/106                       range default
    +/Tenant/11/Table/111                       num_replicas=42
    +/Tenant/11/Table/112                       range default

This PR introduces two cluster settings to selectively opt into this
optimization: spanconfig.{tenant,host}_coalesce_adjacent.enabled
(defaulting to true and false respectively). We also don't coalesce
system table ranges on the host tenant. We had a few implementation
choices here:

(a) Down in KV, augment the spanconfig.Store to coalesce the in-memory
    state when updating entries. On every update, we'd check if the span
    we're writing to has the same config as the preceding and/or
    succeeding one, and if so, write out a larger span instead. We
    previously prototyped a form of this in #68491.

    Pros:
    - reduced memory footprint of spanconfig.Store
    - read path (computing splits) stays fast -- just have to look up
      the right span from the backing interval tree
    Cons:
    - uses more persisted storage than necessary
    - difficult to disable the optimization dynamically (though still
      possible -- we'd effectively have to restart the KVSubscriber and
      populate in-memory span config state using a store that
      does/doesn't coalesce configs)
    - difficult to implement; our original prototype did not have #73150
      which is important for reducing reconciliation round trips

(b) Same as (a) but coalesce configs up in the spanconfig.Store
    maintained in reconciler itself.

    Pros:
    - reduced storage use (both persisted and in-memory)
    - read path (computing splits) stays fast -- just have to look up
      the right span from the backing interval tree
    Cons:
    - very difficult to disable the optimization dynamically (each
      tenant process would need to be involved)
    - most difficult to implement

(c) Same as (a) but through another API on the spanconfig.Store
    interface that accepts only a single update at a time and does not
    generate deltas (not something we need down in KV). Removes the
    implementation complexity.

(d) Keep the contents of `system.span_configurations` and the in-memory
    state of spanconfig.Stores as it is today, uncoalesced. When
    determining split points, iterate through adjacent configs within
    the provided key bounds and see whether we could ignore certain
    split keys.

    Pros:
    - easiest to implement
    - easy to disable the optimization dynamically, for ex. through a
      cluster setting
    Cons:
    - uses more storage (persisted and in-memory) than necessary
    - read path (computing splits) is more expensive if iterating
      through adjacent configs

This PR implements option (d). For a benchmark on how slow (d) is going
to be in practice with varying numbers of entries to be scanning over
(10k, 100k, 1m):
```
    $ dev bench pkg/spanconfig/spanconfigstore -f=BenchmarkStoreComputeSplitKey -v
    BenchmarkStoreComputeSplitKey
    BenchmarkStoreComputeSplitKey/num-entries=10000
    BenchmarkStoreComputeSplitKey/num-entries=10000-10               1166842 ns/op
    BenchmarkStoreComputeSplitKey/num-entries=100000
    BenchmarkStoreComputeSplitKey/num-entries=100000-10             12273375 ns/op
    BenchmarkStoreComputeSplitKey/num-entries=1000000
    BenchmarkStoreComputeSplitKey/num-entries=1000000-10           140591766 ns/op
    PASS
```
It's feasible that in the future we re-work this in favor of (c).

---

**spanconfig/store: use templatized btree impl instead**

```
   $ dev bench pkg/spanconfig/spanconfigstore -f=BenchmarkStoreComputeSplitKey -v
    BenchmarkStoreComputeSplitKey
    BenchmarkStoreComputeSplitKey/num-entries=10000
    BenchmarkStoreComputeSplitKey/num-entries=10000-10                431093 ns/op
    BenchmarkStoreComputeSplitKey/num-entries=100000
    BenchmarkStoreComputeSplitKey/num-entries=100000-10              4308200 ns/op
    BenchmarkStoreComputeSplitKey/num-entries=1000000
    BenchmarkStoreComputeSplitKey/num-entries=1000000-10            43827373 ns/op
    PASS

    $ benchstat old.txt new.txt # from previous commit
    name                                         old time/op  new time/op  delta
    StoreComputeSplitKey/num-entries=10000-10    1.17ms ¬± 0%  0.43ms ¬± 0%   ~     (p=1.000 n=1+1)
    StoreComputeSplitKey/num-entries=100000-10   12.4ms ¬± 0%   4.3ms ¬± 0%   ~     (p=1.000 n=1+1)
    StoreComputeSplitKey/num-entries=1000000-10   136ms ¬± 0%    44ms ¬± 0%   ~     (p=1.000 n=1+1)
```

---

**spanconfig/store: intern span configs**

- Avoid the expensive proto.Equal() when computing split keys;
- Reduce memory overhead of the data structure
```
    $ dev bench pkg/spanconfig/spanconfigstore -f=BenchmarkStoreComputeSplitKey -v
    BenchmarkStoreComputeSplitKey
    BenchmarkStoreComputeSplitKey/num-entries=10000
    BenchmarkStoreComputeSplitKey/num-entries=10000-10                 90323 ns/op
    BenchmarkStoreComputeSplitKey/num-entries=100000
    BenchmarkStoreComputeSplitKey/num-entries=100000-10               915936 ns/op
    BenchmarkStoreComputeSplitKey/num-entries=1000000
    BenchmarkStoreComputeSplitKey/num-entries=1000000-10             9575781 ns/op

    $ benchstat old.txt new.txt # from previous commit
    name                                         old time/op  new time/op  delta
    StoreComputeSplitKey/num-entries=10000-10     431¬µs ¬± 0%    90¬µs ¬± 0%   ~     (p=1.000 n=1+1)
    StoreComputeSplitKey/num-entries=100000-10   4.31ms ¬± 0%  0.92ms ¬± 0%   ~     (p=1.000 n=1+1)
    StoreComputeSplitKey/num-entries=1000000-10  43.8ms ¬± 0%   9.6ms ¬± 0%   ~     (p=1.000 n=1+1)
```

Release note: None
Release justification: high benefit change to existing functionality
(affecting only multi-tenant clusters).

### CODE REVIEW

**Comment by irfansharif** [comment]
This should be ready for review. There are some random out-of-package tests that need to be updated since they expect splits post-table creation (they were added after we introduced tenant range splits), and I also want to write a small benchmark for the read path. Like discussed offline, plan for this PR is to let it bake on master for a few days before backporting to 22.1, aiming for the .1 release. I also think this PR makes #78299 redundant (LMK if you disagree) -- so I'm just going to close that as well.

**Comment by irfansharif** [comment]
> There are some random out-of-package tests that need to be updated since they expect splits post-table creation (they were added after we introduced tenant range splits), and I also want to write a small benchmark for the read path.

Done and done.

**Comment by BramGruneir** [comment]
Would it be possible to backport this to 22.1?

**Comment by irfansharif** [comment]
Yup.

> plan for this PR is to let it bake on master for a few days before backporting to 22.1, aiming for the .1 release.

For single-tenant clusters it won't be enabled by default; there'll be an opt-in cluster setting.

**Comment by BramGruneir** [comment]
Awesome!  Thanks.

**Comment by irfansharif** [comment]
@ajwerner, @nvanbenschoten and @arulajmani: Bump for reviews. Like discussed elsewhere, this PR should get baking time to build confidence. We're also aiming for this to be part of 22.1.1 when rolling out to multi-tenant clusters.

**Review by ajwerner — COMMENTED** [review]
Let's get that benchmark down on computing the split key, or do something about it, like (c). In general, I think a combination of interning the configs and specializing the tree which stores them will make the whole data structure massively faster and more memory efficient. 

High-level, this seems good to me. 

> Reviewed 2 of 5 files at r1, 12 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-:-N0BaufSDfs7NKdm5X2B:bce6lrz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigstore/store_test.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0BeyHfCp0J2EgUhzO1:-N0BeyHfCp0J2EgUhzO2:b1ourle) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/store_test.go#L274)):*
> ```Go
> }
> 
> func BenchmarkStoreComputeSplitKey(b *testing.B) {
> ```

nit: add a sentence explaining what this benchmark does
___
*[pkg/spanconfig/spanconfigstore/span_store.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0BdzZg3tmPoayQbsuc:-N0BdzZg3tmPoayQbsud:b-kj91t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store.go#L153)):*
> ```Go
> 	rem, matchTenID, err := keys.DecodeTenantPrefix(match.span.Key)
> 	if err != nil {
> 		log.Fatalf(ctx, "%v", err)
> ```

can we do better than this?
___
*[pkg/spanconfig/spanconfigstore/span_store.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0Bedjm-RFxEM7WskQr:-N0Bedjm-RFxEM7WskQs:bh4yqqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store.go#L158)):*
> ```Go
> 	if !s.knobs.StoreIgnoreCoalesceAdjacentExceptions {
> 		if matchTenID.IsSystem() {
> 			systemTableUpperBound := keys.SystemSQLCodec.TablePrefix(keys.MaxReservedDescID + 1)
> ```

keys.MaxReservedDescID isn't that meaningful anymore. In practice we've set the rangefeed flag on system descriptors, but I wonder if we want to have some other flag on the span config to say that it shouldn't be merged into adjacent ranges. This seems fine for the moment, but please put some commentary here. 
___
*[pkg/spanconfig/spanconfigstore/span_store.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0Be1Br-CVZKeeTJ1Ah:-N0Be1Br-CVZKeeTJ1Ai:b-kj91t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store.go#L188)):*
> ```Go
> 	_, firstMatchTenID, err := keys.DecodeTenantPrefix(firstMatch.span.Key)
> 	if err != nil {
> 		log.Fatalf(ctx, "%v", err)
> ```

can we do better than this?
___
*[pkg/spanconfig/spanconfigstore/span_store.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0Be4JI0DWCcJGQ0Qtf:-N0Be4JI0DWCcJGQ0Qtg:b-20aau1) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store.go#L203)):*
> ```Go
> 		_, entryTenID, err := keys.DecodeTenantPrefix(nextEntry.span.Key)
> 		if err != nil {
> 			log.Fatalf(ctx, "%v", err)
> ```

can we do better than this?

Maybe make yourself a helper closure and have that thing say a bit more in the log entry and use `Depth`?
___
*[pkg/spanconfig/spanconfigstore/span_store_test.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0Bcc4i-E3nHmO1a7Vs:-N0Bcc4i-E3nHmO1a7Vt:bj5p57x) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store_test.go#L210)):*
> ```Go
> 	))
> 
> 	querySpan := getRandomSpan()
> ```

can you add some commentary about what this section of code is about to do? Consider a subtest?

**Review by irfansharif — COMMENTED** [review]
PTAL at the last two commits; used the templatized btree + interned span configs. I don't actually know what typical interning code/data structures look like, so probably the API/terminology is off -- open to suggestions. For 1M span config entries it's down to 10ms now, compared to 130+ms before. Uses a lot less memory as well.

```
name                                         old time/op  new time/op  delta
StoreComputeSplitKey/num-entries=10000-10    1.17ms ¬± 0%  0.09ms ¬± 0%   ~     (p=1.000 n=1+1)
StoreComputeSplitKey/num-entries=100000-10   12.4ms ¬± 0%   0.9ms ¬± 0%   ~     (p=1.000 n=1+1)
StoreComputeSplitKey/num-entries=1000000-10   136ms ¬± 0%    10ms ¬± 0%   ~     (p=1.000 n=1+1)
```

I'll add tests for the interner data structure + address remaining comments tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-:-N0didRl0UFVk342TJH4:byakc9g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

**Review by ajwerner — COMMENTED** [review]
nice! Love to see a 10x win!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-:-N0f8rfZDoj7sRr_HuKH:bp8wd1s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[`pkg/spanconfig/spanconfigstore/span_store.go` line 79 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0f73y68xFzE9APGkyf:-N0f73y77hn8xY-BtRPD:b63fpph) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0df858ecbf19ff1f579f66beedfd028bbad015/pkg/spanconfig/spanconfigstore/span_store.go#L79)):*
> ```Go
> func (s *spanConfigStore) copy(ctx context.Context) *spanConfigStore {
> 	clone := newSpanConfigStore(s.settings, s.knobs)
> 	_ = s.forEachOverlapping(keys.EverythingSpan, func(sp roachpb.Span, conf roachpb.SpanConfig) error {
> ```

The btree has an `O(1)` clone method. The interner does not, however, the interner is likely to be much smaller than the tree in terms of number of entries and it should be much cheaper to just copy the intener than to rebuilt it incrementally. 

At the end, maybe this looks like: 
```go
return &spanConfigStore{
    settings: s.settings,
    knobs: s.knobs,
    btree: s.btree.Clone(),
    internet: s.interner.clone(),
}
```

**Review by irfansharif — COMMENTED** [review]
Addressed everything, just appended a commit for review changes because it was too much work to fix up the earlier ones. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-:-N0mKQ5E-i3pYo4BOSwJ:b-3ajdwu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[`pkg/spanconfig/spanconfigstore/store_test.go` line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0BeyHfCp0J2EgUhzO1:-N0gV85A2lvKgzyQaSyP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/store_test.go#L274)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: add a sentence explaining what this benchmark does
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigstore/span_store.go` line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0Bedjm-RFxEM7WskQr:-N0gUcGx6_uCbyPaN1rE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store.go#L158)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

keys.MaxReservedDescID isn't that meaningful anymore. In practice we've set the rangefeed flag on system descriptors, but I wonder if we want to have some other flag on the span config to say that it shouldn't be merged into adjacent ranges. This seems fine for the moment, but please put some commentary here. 
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigstore/span_store.go` line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0Be4JI0DWCcJGQ0Qtf:-N0gjDxAB3nezC6DNgOa:b2hul7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store.go#L203)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can we do better than this?

Maybe make yourself a helper closure and have that thing say a bit more in the log entry and use `Depth`?
</blockquote></details>

Done at the caller for all of these.
___
*[`pkg/spanconfig/spanconfigstore/span_store.go` line 79 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0f73y68xFzE9APGkyf:-N0gTU615p7bZnU8VVcT:b379h6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0df858ecbf19ff1f579f66beedfd028bbad015/pkg/spanconfig/spanconfigstore/span_store.go#L79)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The btree has an `O(1)` clone method. The interner does not, however, the interner is likely to be much smaller than the tree in terms of number of entries and it should be much cheaper to just copy the intener than to rebuilt it incrementally. 

At the end, maybe this looks like: 
```go
return &spanConfigStore{
    settings: s.settings,
    knobs: s.knobs,
    btree: s.btree.Clone(),
    internet: s.interner.clone(),
}
```
</blockquote></details>

Neat, done.
___
*[`pkg/spanconfig/spanconfigstore/span_store_test.go` line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0Bcc4i-E3nHmO1a7Vs:-N0gfIO86vooXayc26Pr:bo18cmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/28fde02b6aa6b8004a222b473fd1e3623f7d2c91/pkg/spanconfig/spanconfigstore/span_store_test.go#L210)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you add some commentary about what this section of code is about to do? Consider a subtest?
</blockquote></details>

Done.

```
Properties for computed split keys:

(1) sp.ProperlyContains(ComputeSplitKey(sp))
    (i) When computing the set of all split keys over a given span, they
        should be sorted
(2) Configs at adjacent split keys must be non-identical
(3) Span config entries between two split keys 'a' and 'b' should have a
    config identical to the config at 'a'
    (i) The config at the last split key should be identical the last
        config that overlaps with the query span
    (ii) Properties (3) and (1) imply that the first split key should
         have a different config than the first config that overlaps with
        the query span if the first entry start key == query span start
        key.

This subtest computes the set of all split keys over a randomly generated
span and asserts on all the properties above.
```

**Review by ajwerner — COMMENTED** [review]
> Reviewed 6 of 24 files at r4, 1 of 7 files at r6, 5 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[`pkg/spanconfig/spanconfigstore/interner.go` line 31 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0pzcPV2uAEb1t8RWNU:-N0pzcPV2uAEb1t8RWNV:b-97rtfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0042af0b985b8f2ce1859bbf134ebf017f7b8f71/pkg/spanconfig/spanconfigstore/interner.go#L31)):*
> ```Go
> 	internIDAlloc internerID
> 
> 	configToID   map[string]internerID
> ```

another possibility on how to frame this would be to get rid of the `internerID` altogether and just have:

```
configToCanonical map[string]*roachpb.SpanConfig
refCounts         map[*roachpb.SpanConfig]uint64
```

I think this is more elegant in a variety of ways. Then your entry in your tree would just be the tuple of `roachpb.Span` and `*roachpb.SpanConfig` and the equality check can be pointer equality. This should also make the tree more compact: no need to put the SpanConfig itself as a value into the tree plus the intern key, now you can have just one pointer. 



_Code quote:_
```Go


	configToID   map[string]internerID
	idToConfig   map[internerID]roachpb.SpanConfig
	idToRefCount map[internerID]uint64
```

**Comment by ajwerner** [comment]
While you're at it, give the `string` a strong type like `spanConfigKey`

**Review by ajwerner — APPROVED** [review]
:lgtm: mod the nits and refactor of the interner 

> Reviewed 7 of 24 files at r4, 1 of 9 files at r5, 8 of 15 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-:-N0qabOtBglP1JU0tWq-:b-o8ujos)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[`pkg/ccl/spanconfigccl/spanconfigcomparedccl/testdata/multitenant` line 32 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0qaJW79nFu2ahm97n-:-N0qaJW79nFu2ahm97n0:b4ffm55) ([raw file](https://github.com/cockroachdb/cockroach/blob/0042af0b985b8f2ce1859bbf134ebf017f7b8f71/pkg/ccl/spanconfigccl/spanconfigcomparedccl/testdata/multitenant#L32)):*
> ```
> 
> reconcile tenant=11
> ----
> ```

thoughts on having a version of this test when the coalescing is disabled? 
___
*[`pkg/spanconfig/spanconfigstore/span_store.go` line 194 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0qZzK72tNsD73Tem8l:-N0qZzK72tNsD73Tem8m:b-lmav71) ([raw file](https://github.com/cockroachdb/cockroach/blob/0042af0b985b8f2ce1859bbf134ebf017f7b8f71/pkg/spanconfig/spanconfigstore/span_store.go#L194)):*
> ```Go
> 			firstMatch = iter.Cur().spanConfigPairInterned
> 			break // we're done
> 		}
> ```

this seems like an `if` statement masquerading as a for loop



_Code quote:_
```Go
		for iter.FirstOverlap(query); iter.Valid(); {
			firstMatch = iter.Cur().spanConfigPairInterned
			break // we're done
		}
```

**Review by irfansharif — COMMENTED** [review]
> While you're at it, give the string a strong type like spanConfigKey

Done.

Thanks for reviewing! I'll open the backport now but not merge to the release until some point mid next week, to see if this shakes out anything in CI on master. I'll merge this on green.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-:-N0qmAja8J477ryUi1sA:bjnuil4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[`pkg/spanconfig/spanconfigstore/interner.go` line 31 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0pzcPV2uAEb1t8RWNU:-N0qkxUL4gNPawJHkJha:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0042af0b985b8f2ce1859bbf134ebf017f7b8f71/pkg/spanconfig/spanconfigstore/interner.go#L31)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

another possibility on how to frame this would be to get rid of the `internerID` altogether and just have:

```
configToCanonical map[string]*roachpb.SpanConfig
refCounts         map[*roachpb.SpanConfig]uint64
```

I think this is more elegant in a variety of ways. Then your entry in your tree would just be the tuple of `roachpb.Span` and `*roachpb.SpanConfig` and the equality check can be pointer equality. This should also make the tree more compact: no need to put the SpanConfig itself as a value into the tree plus the intern key, now you can have just one pointer. 
</blockquote></details>

Done.
___
*[`pkg/ccl/spanconfigccl/spanconfigcomparedccl/testdata/multitenant` line 32 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0qaJW79nFu2ahm97n-:-N0ql-EC60iBpNrKEUO1:bx95wwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0042af0b985b8f2ce1859bbf134ebf017f7b8f71/pkg/ccl/spanconfigccl/spanconfigcomparedccl/testdata/multitenant#L32)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

thoughts on having a version of this test when the coalescing is disabled? 
</blockquote></details>

The non-multitenant test file in this package is not coalescing today (since it's disabled for the host tenant), so it's doing what you're saying. I originally tried toggling cluster settings in this test but the synchronization was annoying to add to make this test deterministic + fast. 

BTW this entire test package is not going to age well into 22.2 since we wrote it primarily to diff against the gossiped system config span. I'm planning to come back here and remove all that verbiage and this "diff" syntax after 22.1.2-ish is out when we rip out all that dead code/migrations from master.
___
*[`pkg/spanconfig/spanconfigstore/span_store.go` line 194 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/79700#-N0qZzK72tNsD73Tem8l:-N0qkywQ0MyiBy_BR8Z6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0042af0b985b8f2ce1859bbf134ebf017f7b8f71/pkg/spanconfig/spanconfigstore/span_store.go#L194)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this seems like an `if` statement masquerading as a for loop
</blockquote></details>

Done.

**Comment by theodore-hyman** [comment]
@irfansharif Thank you for your time and attention on this matter. I am chiming in just to confirm the timeline here as a quick sanity check. 

Again, I know you just said that this would be backported to v22.1.1 and you just said: 

`I'll open the backport now but not merge to the release until some point mid next week` 

However just re-confirming, apologies for the redundancy. This is related to a highly escalated customer situation as you're likely aware.

My understanding is that this fix, in the form of a new hidden config option, will be released as part of v22.1.1 that is scheduled for public release June 6, 2022. Please confirm or let me know if I am misunderstanding. Thank you

**Comment by irfansharif** [comment]
The backport (#80811) was merged, so it'll make it to 22.1.1 whenever that goes out. That said, I don't know which customer you're referring to (DM?) and whether this would help. This PR wasn't intended as a fix for anything, so let's discuss elsewhere what we're expecting this to help with.

**Pull request merged**
