### PR TITLE
opt: Clean up work on logical properties

### PR DESCRIPTION
**Pull request by andy-kimball**
- Move base table props generation to props package
- Streamline logicalPropsBuilder

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/metadata.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEeHC9J5swLD2Kf1T5N:-LEiz698DBwRQS3BzGKq:b-1a6c7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea29d00c5e4c81e2014fe5170285fe6d8b4f142/pkg/sql/opt/metadata.go#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would it be more efficient to have a fixed size array with a bunch of "slots"? There could be a global function that other pkgs could use to assign a slot during init `var weakKeySlot = opt.NewTableAnnotationSlot()`.
</blockquote></details>

Interesting idea...I made that change.

---

*[pkg/sql/opt/metadata.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEeH6xbAv9GaCSTlz9h:-LEj-bjS3EAkBmqxC4i_:b-qvxirp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea29d00c5e4c81e2014fe5170285fe6d8b4f142/pkg/sql/opt/metadata.go#L210)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this if is not necessary
</blockquote></details>

But it will panic if I remove the check, if no annotations have been added to the table...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26570)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 8 of 11 files at r2, 3 of 3 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/metadata.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEeH6xbAv9GaCSTlz9h:-LEjI17y10Bzek41M6_O:b-yih1ac) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea29d00c5e4c81e2014fe5170285fe6d8b4f142/pkg/sql/opt/metadata.go#L210)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

But it will panic if I remove the check, if no annotations have been added to the table...
</blockquote></details>

That code went away, but wanted to mention that a nil map behaves like an empty map when reading.

---

*[pkg/sql/opt/metadata.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEjIxQvBmtmeJAnfvmY:-LEjIxQvBmtmeJAnfvmZ:b-915zut) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed0250095901aca4692c43259011611148167c4/pkg/sql/opt/metadata.go#L85)):*
> ```Go
> 
> 	// anns annotates the table metadata with arbitrary data.
> 	anns []interface{}
> ```

We could make it an array of a fixed size `maxAnnID`, and have `NewTableAnnID` panic if we ever reach that. It would save the allocation and make things a bit simpler.

---

*[pkg/sql/opt/metadata.go, line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEjIh47-xGkfBUdIDGN:-LEjIh47-xGkfBUdIDGO:b-87k6uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed0250095901aca4692c43259011611148167c4/pkg/sql/opt/metadata.go#L247)):*
> ```Go
> // NewTableAnnID allocates a unique annotation identifier that is used to
> // associate arbitrary data with table metadata. It is not thread-safe, and
> // therefore should only be called during Go's program initialization phase.
> ```

Go init guarantees init code runs for one package at a time, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-:-LEjK-y08eRYzbeQoyHv:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/metadata.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEeH6xbAv9GaCSTlz9h:-LEjSe-rC2XFhNQpB9Tn:b-xb4m66) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea29d00c5e4c81e2014fe5170285fe6d8b4f142/pkg/sql/opt/metadata.go#L210)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

That code went away, but wanted to mention that a nil map behaves like an empty map when reading.
</blockquote></details>

I'd forgotten that.

---

*[pkg/sql/opt/metadata.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEjIxQvBmtmeJAnfvmY:-LEjSdJ39oP_6MxWRiCR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed0250095901aca4692c43259011611148167c4/pkg/sql/opt/metadata.go#L85)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We could make it an array of a fixed size `maxAnnID`, and have `NewTableAnnID` panic if we ever reach that. It would save the allocation and make things a bit simpler.
</blockquote></details>

Done.

---

*[pkg/sql/opt/metadata.go, line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEjIh47-xGkfBUdIDGN:-LEjSfxL1s0VEzxz5noh:bqz0anv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ed0250095901aca4692c43259011611148167c4/pkg/sql/opt/metadata.go#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Go init guarantees init code runs for one package at a time, right?
</blockquote></details>

Yes, I added comment to that effect.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26570)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26570)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 8 of 11 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/metadata.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEkpRhyElHwqFW7fl8y:-LEkpRhyElHwqFW7fl8z:b-gchddm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9e99062b00987d0b3c742b2a4b44936fe80ac56/pkg/sql/opt/metadata.go#L31)):*
> ```Go
> // metadata. A table annotation allows arbitrary values to be cached with table
> // metadata, which can be used to avoid recalculating base table properties or
> // other information each time it's needed.
> ```

[nit] maybe say what table annotations are currently used, and if someone wants to create more, they need to update `maxTableAnnIDCount`

---

*[pkg/sql/opt/metadata.go, line 33 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEkqp-w1lG0gUTqh0GI:-LEkqp-w1lG0gUTqh0GJ:b98r56p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9e99062b00987d0b3c742b2a4b44936fe80ac56/pkg/sql/opt/metadata.go#L33)):*
> ```Go
> // other information each time it's needed.
> //
> // To create a TableAnnID, call NewTableAnnID during Go's program initialization
> ```

A code example might help here

---

*[pkg/sql/opt/metadata.go, line 249 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-LEknksQCLbYTM_hCrfC:-LEknksQCLbYTM_hCrfD:bw92sgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9e99062b00987d0b3c742b2a4b44936fe80ac56/pkg/sql/opt/metadata.go#L249)):*
> ```Go
> //
> // This method is not thread-safe, and therefore should only be called during
> // Go's program initialization phase (which uses single goroutine to init
> ```

[nit] uses single goroutine -> uses a single goroutine

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26570#-:-LEkqZcM-dMq4KgFDI2g:bnfp4nl)*

**Pull request merged**
