### PR TITLE
roachtest: remove network/* family of toxiproxy tests

### PR DESCRIPTION
**Pull request by tbg**
These were originally introduced in #33282 in response to a resource leak
(goroutine buildup) under prolonged network partitions. However this type of
testing never caught on and the meaningful part of these tests has been skipped
for years at this point, with little hope for a comeback.

It's not impossible that we may consider toxiproxy again in the future and I'm
not generically against that. When and if we do, the git history will still
contain bits and pieces that we can salvage.

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]

**Review by srosenberg — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80230)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg and @tbg)

___
*[pkg/cmd/roachtest/tests/network.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80230#-N06XB2bBNF9ozXydByS:-N06XB2cEim7LM6ifbdB:b-6yamnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea67fd5d4966508877fc88ba21bdd498ff162e8/pkg/cmd/roachtest/tests/network.go#L114)):*
> ```Go
> // of system.users, and then validates that the time required to create
> // new connections to the cluster afterwards remains under a reasonable limit.
> func runNetworkAuthentication(ctx context.Context, t test.Test, c cluster.Cluster) {
> ```

This tests uses iptables instead of toxiproxy. It's also a regression for a fairly recent issue: https://github.com/cockroachdb/cockroach/pull/66768
Should we keep it?

**Review by AlexTalks — COMMENTED** [review]
nit: remove `toxiproxy` from `DEPS.bzl` and `go.mod`.

Otherwise, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80230#-:-N0D7ZSa1-KP177DC4xJ:b-szdymj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg and @tbg)

**Comment by tbg** [comment]
Well spotted Stan - thanks for the careful review. I agree, I shouldn't have deleted this test.
Patched this up.

**Comment by tbg** [comment]
bors r=srosenberg

**Comment by tbg** [comment]
blathers backport 22.1

**Pull request merged**
