### PR TITLE
tracing: disallow children of sterile span with different Tracer

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, creating a "child" of a sterile span with a different Tracer than the one used to create the sterile span was tolerated - on the argument that sterile spans don't actually get children (the would-be child span is created as a root), so the arguments for not allowing a children to be created with different tracers don't apply. At the same time, creating a child of a noop span with a different Tracer than the noop span's Tracer was documented to not be allowed. In practice, it was, because the code was confused [1].

This patch disallows creating children of sterile spans with a different tracer, for consistency with all the other spans. The patch also makes it a panic for the children of noop spans to be created with a different Tracer.

This is all meant as a cleanup / code simplification.

[1] WithParent(sp) meant to treat sterile spans differently than noop spans but it was using sp.IsSterile(), which returns true for both. As such, it was unintentionally returning an empty parent option. startSpanGeneric() meant to check the tracer of parent noop spans, but it was failing to actually do so because it was going through the opts.Parent.empty().

Release note: None
Epic: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @andreimatei)

___
*[`pkg/util/tracing/tracer.go` line 1122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93354#-NJCI0wI3xFYgu3LqipI:-NJCI0wI3xFYgu3LqipJ:bquh8jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/153448e1488abbdf49a0ea6dc77b99f0da235eb0/pkg/util/tracing/tracer.go#L1122)):*
> ```Go
> 		if opts.Parent.IsNoop() {
> 			// If the parent is a no-op, we'll create a root span.
> 			opts.Parent.decRef()
> ```

I don't follow this change. Why remove this? do noop spans opt out of the reference counting?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/util/tracing/tracer.go` line 1122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93354#-NJCI0wI3xFYgu3LqipI:-NJCY-Vp3OJbQcgXz7IQ:b-hvy87i) ([raw file](https://github.com/cockroachdb/cockroach/blob/153448e1488abbdf49a0ea6dc77b99f0da235eb0/pkg/util/tracing/tracer.go#L1122)):*
> do noop spans opt out of the reference counting?

Yes. noop spans are statically allocated singletons (one per tracer). Their reference count is always zero; calling `decRef()` on them panics.
We weren't crashing before this patch because of another bug canceling out this call: `WithParent(noopSpan)` was returning an empty ref (so this whole block was avoided because of the `if !opts.Parent.empty() {` check above), because the `IsSterile()` check in `WithParent` returned true for noops (mostly by accident).

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93354#-:-NJCkLcWAh0IYSP-otuP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @andreimatei)

___
*[`pkg/util/tracing/tracer.go` line 1122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93354#-NJCI0wI3xFYgu3LqipI:-NJCkJru2FvtTs62msp0:b-nwv2m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/153448e1488abbdf49a0ea6dc77b99f0da235eb0/pkg/util/tracing/tracer.go#L1122)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> do noop spans opt out of the reference counting?

Yes. noop spans are statically allocated singletons (one per tracer). Their reference count is always zero; calling `decRef()` on them panics.
We weren't crashing before this patch because of another bug canceling out this call: `WithParent(noopSpan)` was returning an empty ref (so this whole block was avoided because of the `if !opts.Parent.empty() {` check above), because the `IsSterile()` check in `WithParent` returned true for noops (mostly by accident).
</blockquote></details>

Gotcha. Thanks for clarifying.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93354#-:-NJH1VvHD4ySCM3cSQJg:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier)

**Pull request merged**
