### PR TITLE
admission: fix overflow bug in ioLoadListener

### LINKED ISSUE #69461: roachtest: sysbench/oltp_delete/nodes=3/cpu=32/conc=128 failed
roachtest.sysbench/oltp_delete/nodes=3/cpu=32/conc=128 [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3366874&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3366874&tab=artifacts#/sysbench/oltp_delete/nodes=3/cpu=32/conc=128) on master @ [8cae60f603ccc4d83137167b3b31cab09be9d41a](https://github.com/cockroachdb/cockroach/commits/8cae60f603ccc4d83137167b3b31cab09be9d41a):

```
		  | (1) signal: killed
		  | Error types: (1) *exec.ExitError
		Wraps: (5) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *cluster.WithCommandDetails (4) *secondary.withSecondaryError (5) *errors.errorString

	monitor.go:128,sysbench.go:129,sysbench.go:150,test_runner.go:777: monitor failure: unexpected node event: 2: dead (exit status 134)
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:116
		  | main.(*monitorImpl).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:124
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runSysbench
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/sysbench.go:129
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerSysbench.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/sysbench.go:150
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (2) monitor failure
		Wraps: (3) unexpected node event: 2: dead (exit status 134)
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString

	cluster.go:1249,context.go:89,cluster.go:1237,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-3366874-1630046181-66-n4cpu32 --oneshot --ignore-empty-nodes: exit status 1 4: skipped
		2: dead (exit status 134)
		1: 13592
		3: 12683
		Error: UNCLASSIFIED_PROBLEM: 2: dead (exit status 134)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1173
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:281
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:2107
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:225
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (3) 2: dead (exit status 134)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sysbench/oltp_delete/nodes=3/cpu=32/conc=128.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by sumeerbhola**
Fixes #69461,#69463

Release justification: High-severity bug fix to new funtionality.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Could you say a few words here about how the bug triggered? Feels like when the code was originally written, we assumed that we would only hit the `MaxInt64` endpoint and not `MaxInt64 - small_number`. (I lack the understanding of what the context of this code is).

Also, I think this fixes all of these: https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+is%3Aissue+label%3AC-test-failure+assignee%3Asumeerbhola+

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69567#-:-MiMJx8a74SN9gd1c1uq:blfd4mt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by sumeerbhola** [comment]
TFTR!

> Could you say a few words here about how the bug triggered? Feels like when the code was originally written, we assumed that we would only hit the MaxInt64 endpoint and not MaxInt64 - small_number. (I lack the understanding of what the context of this code is).

I still don't know. I've been trying to reproduce the roachtest failures with additional instrumentation, but haven't been successful so far. I'll keep trying this afternoon, since it might uncover some other badness. Meanwhile I'll merge this.

**Comment by sumeerbhola** [comment]
btw, do you know what exit code 134 is? I could not find it in `cli/exit/codes.go` and the roachtest consistently fails with that code. When I look in the stderr log, all nodes failed with 134, but there is nothing in `cockroach.log` indicating any problem.

```
16:04:03 sysbench.go:115: test status: preparing workload
1: 11603
2: 11126
3: 11141
3: dead (exit status 134)
16:10:51 test_impl.go:323: test failure: 	cluster.go:1893,sysbench.go:117,monitor.go:106,errgroup.go:57: output in run_160405.550649000_n4_sysbench: /Users/sumeer/go/src/github.com/cockroachdb/cockroach/bin/roachprod run sumeer-1630339241-01-n4cpu32:4 -- sysbench \: context canceled
```

**Comment by tbg** [comment]
You need to look at `cockroach-stderr.log` (or cockroach.stderr.log, I forget which one it is). I'm not sure exactly where exit status 134 comes from but the process crashes because of a runtime panic (the one you're fixing now) and so it exits nonzero.

**Comment by tbg** [comment]
Ah, 134 is just 128+SIGABRT

**Comment by RaduBerinde** [comment]
I don't get it.. How would `totalTokens` be close to but not quite `MaxInt64` (aka `unlimitedTokens`)? We're either setting it to `unlimitedTokens` or we're calculating what should be a reasonable value.

**Comment by RaduBerinde** [comment]
I'd add more assertions: check that `bytesAdded >= 0` and that `io.totalTokens > 0` in `adjustTokens`.

**Comment by sumeerbhola** [comment]
> Ah, 134 is just 128+SIGABRT

So is it code 7 which is `FatalError`? I don't see where/whether these are being used as bit masks.

> I'd add more assertions: check that bytesAdded >= 0 and that io.totalTokens > 0 in adjustTokens.

I can't even get the current assertion to fire, at least based on looking at the logs.

**Comment by tbg** [comment]
I'm not sure where the exit code comes from. On a panic like the one hit in these tests, the exit code should be 2. We invoke CRDB through systemd via a shell script, this may make a difference, but the exit code grabbed from the crdb process within that script is also 134 as evidenced by the log files.

https://github.com/cockroachdb/cockroach/blob/0de4773f4ed9d83d52c05200b0ae212152cd3551/pkg/cmd/roachprod/install/scripts/start.sh#L57-L61

**Comment by sumeerbhola** [comment]
I have a reproduction -- this PR is not going to fix it since `ioLoadListener.totalTokens` is negative.

**Comment by RaduBerinde** [comment]
Is it because `bytesAdded` is negative? That was the only possibility I could find in the code when I looked earlier.

**Comment by sumeerbhola** [comment]
> Is it because bytesAdded is negative?

It was simpler than that -- `bytesAdded` can be 0, so we get +inf for `numAdmit`.

**Pull request merged**
