### PR TITLE
colflow: add bytes sent stat on streams

### LINKED ISSUE #48112: colexec: collect specialized statistics from outboxes
With #47347 we added "statistics propagation" on the streams, however, we still use the same type of statistics as for the operators. We should collect specialized statistics from outboxes (e.g. number of bytes sent).

### PR DESCRIPTION
**Pull request by cathymw**
Fixes: #48112
This commit (follow-up to #47347) adds the "bytes sent" information collected at inboxes to stream statistics.
Also changed the inline comments from `ioReadingOp` to `ioReader` to be more consistent with the argument name.

The following screenshot shows that the stream stats now include "bytes sent":
image

Release note (sql change):: EXPLAIN ANALYZE diagrams now contain "bytes
sent" information on streams.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Looks very good! I have just a couple of nits.

- you should include what you have in the PR description as the commit message
- you could use something like `Fixes: #48112` in the PR description so that once this PR merges, the issue is closed automatically. Note that I usually do not include this line into the commit message (in order to not create the span on the issue because I tend to amend commits and force-push very often), so I write a decent commit message and a release note if necessary, then copy-paste that message as the PR description and add this Fixes thing.
- for release note, you should specify a category. In this case it would be `Release note (sql change): ...`.

I also think that some tests are likely to fail, so let's wait for CI to tell us which ones, and then you could do something like `make testbaselogic TESTFLAGS='-rewrite' FILES=explain_analyze_plans` on all the logic test files that need an update. If the failing tests are `opt/exec/execbuilder`, then you'd use `make testoptlogic ...`.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54518#-:-MHSES-V1tkMQJ9RpFdW:bmze171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54518#-MHSECyd2EvnFa6R5PsW:-MHSECyd2EvnFa6R5PsX:b-dcdh1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/52e8bcaab4184432bdf50c9ca7e09b020b45af10/pkg/sql/colflow/colrpc/inbox.go#L114)):*
> ```Go
> }
> 
> var _ colexecbase.Operator = &Inbox{}
> ```

nit: now that `Inbox` implements `IOReader` interface, we should add a check for it, like
```
var _ execinfra.IOReader = &Inbox{}
```

**Review by yuzefovich — APPROVED** [review]
:lgtm:

Nit about communication: once you've addressed the comments, you should say something like "RFAL" so that the reviewers know you're done addressing the feedback. Also, for the inlined comments it's a good practice to reply as "Done" or something like that when you fixed it (thinking about the `var _ execinfrap.IOReader` thing) - this way it is clear for you and for the reviewers that it has been addressed.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54518#-:-MHT1qRq3g85Fzzd9MPa:bhl75zr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by cathymw** [comment]
Gotcha! I was waiting to make sure that there were no more CI failures before asking for a review again, but I'll keep that in mind for next time! TFTR!

bors r+

**Comment by yuzefovich** [comment]
Oh, if you were still waiting for CI, then it's my bad for reviewing too quickly :D Next time I'll wait for a ping :)

**Review by asubiotto — COMMENTED** [review]
Great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54518#-:-MHV-9DS3bTlfRw3iOLR:b-9dwnzc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cathymw)

___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54518#-MHV--3y9rD25hDsblHN:-MHV--3y9rD25hDsblHO:b-yes3dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/acbc011679b88bcdba1b8fd2880b66c7799ae45a/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L54)):*
> ```
> https://cockroachdb.github.io/distsqlplan/decode.html#eJzMWF1v4jgUfd9fYd2nmR0zwflghkgjUe2yEiMGuqUPu1vxkBIvRNAk6zilVdX_vgqZqoWCY2NM8lYSO-ec6-NT-z5B9t8KfJj0h_3frlHOVuiPq_EPdNP_63J4MRihi9HF8O9_-ujD74PJ9eTP4Uf0c-iv5cDlPfo-HozQco3GI7S8_7xE39By_Xk5BQxxEtJRcEcz8G-AAAYbMDiAwQUMHkwxpCyZ0SxLWDHkaTNhED6A38YQxWnOi8dTDLOEUfCfgEd8RcGH6-B2Ra9oEFJmtQFDSHkQrTYwy_teyqK7gD0ChkkaxJmPWlYBfBvw2YJmKMl5mnMfFRN5nq7ePCo4DsaIR3fUR-0MMLBknSFGg7B4OX3GUA4t6b7QuX1EiyBbbBPpFeOnGDIezCn45Bkfp6-zo2_9Xp9FmqDQPqjw9TsJCymj4e53PhXAUqP2FOsHZXP6PYliyiyy44YV_Zd_6JFPH7-xaL4o_wQM46IUPYJ7Nu45uOfK144-0FnOoyR-LeF2zV7r4UjUI4_3ad0rc5S0ktQi3rZACdqeGm13izaRNyqp3oiW3bKc2o1KjlX4RWIrNkKhfVDhGbciaepWtOVX3JbwtNOyFFifxdMKCr9KeLoRCu2DCs_oabupnnbkV9yR8LTbsrzaV5wcq7Ar4elGKLQPKjyjp52metqVX3FXwtNeq_b1Jsfq86od3bIICuIQEZTwBWW1a7UPaj2jt92merviAnhFszSJM7pzLdj_5XZRBhrOaVncLMnZjF6yZLaBKX-ON_M2Z8GQZrx8a5c_BvHLq4wHXPZa0T4oX4VCR5fCW_cqYnd1sKt3jgoVor0UGnUgnlFwouBB24wHxRQ6uhQ05Hd1sFU9KKZCtJdCow47Hjw1uL0L3n4L7mz7f3eyI5xMtu3TNuNg12yQC4snxtZOcH35WkGuKd9wcleAayW3anx4ZoNcWAcxtnaCy3hQTEEryDXlG07uCnCt5Fb1YEclyM1S-VJjJIuxzR6qxdjaWSyzFcUU9CL5tDYwfLb-WmMki7HNHqrF2NpZLONBMQW9SFb1YAUXs2frbnMimRjud4gvOAY7HScuhNkDcwW4_olZ6spfb8_DcNNDB1wrmZWNaLD9oVsI_WOzlBFrbXwQpc6HYS-8a6ScLp1PzMXsCboC3HA6i8EN9zOq0LVjWWpLqnTTTAekSnft5Omg0lc7M7jpdrRSZ83U_4Z3rZUzpvP0-Zf_AwAA__9s9Vdr
> ```
The bytes read does not show up here, is it because testing code zeroes it out due to non-determinism and this results in not displaying the label?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54518)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54518#-MHV--3y9rD25hDsblHN:-MHY21Q26vXkjWbB_cAx:bugxxgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/acbc011679b88bcdba1b8fd2880b66c7799ae45a/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L54)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

> ```
> https://cockroachdb.github.io/distsqlplan/decode.html#eJzMWF1v4jgUfd9fYd2nmR0zwflghkgjUe2yEiMGuqUPu1vxkBIvRNAk6zilVdX_vgqZqoWCY2NM8lYSO-ec6-NT-z5B9t8KfJj0h_3frlHOVuiPq_EPdNP_63J4MRihi9HF8O9_-ujD74PJ9eTP4Uf0c-iv5cDlPfo-HozQco3GI7S8_7xE39By_Xk5BQxxEtJRcEcz8G-AAAYbMDiAwQUMHkwxpCyZ0SxLWDHkaTNhED6A38YQxWnOi8dTDLOEUfCfgEd8RcGH6-B2Ra9oEFJmtQFDSHkQrTYwy_teyqK7gD0ChkkaxJmPWlYBfBvw2YJmKMl5mnMfFRN5nq7ePCo4DsaIR3fUR-0MMLBknSFGg7B4OX3GUA4t6b7QuX1EiyBbbBPpFeOnGDIezCn45Bkfp6-zo2_9Xp9FmqDQPqjw9TsJCymj4e53PhXAUqP2FOsHZXP6PYliyiyy44YV_Zd_6JFPH7-xaL4o_wQM46IUPYJ7Nu45uOfK144-0FnOoyR-LeF2zV7r4UjUI4_3ad0rc5S0ktQi3rZACdqeGm13izaRNyqp3oiW3bKc2o1KjlX4RWIrNkKhfVDhGbciaepWtOVX3JbwtNOyFFifxdMKCr9KeLoRCu2DCs_oabupnnbkV9yR8LTbsrzaV5wcq7Ar4elGKLQPKjyjp52metqVX3FXwtNeq_b1Jsfq86od3bIICuIQEZTwBWW1a7UPaj2jt92merviAnhFszSJM7pzLdj_5XZRBhrOaVncLMnZjF6yZLaBKX-ON_M2Z8GQZrx8a5c_BvHLq4wHXPZa0T4oX4VCR5fCW_cqYnd1sKt3jgoVor0UGnUgnlFwouBB24wHxRQ6uhQ05Hd1sFU9KKZCtJdCow47Hjw1uL0L3n4L7mz7f3eyI5xMtu3TNuNg12yQC4snxtZOcH35WkGuKd9wcleAayW3anx4ZoNcWAcxtnaCy3hQTEEryDXlG07uCnCt5Fb1YEclyM1S-VJjJIuxzR6qxdjaWSyzFcUU9CL5tDYwfLb-WmMki7HNHqrF2NpZLONBMQW9SFb1YAUXs2frbnMimRjud4gvOAY7HScuhNkDcwW4_olZ6spfb8_DcNNDB1wrmZWNaLD9oVsI_WOzlBFrbXwQpc6HYS-8a6ScLp1PzMXsCboC3HA6i8EN9zOq0LVjWWpLqnTTTAekSnft5Omg0lc7M7jpdrRSZ83U_4Z3rZUzpvP0-Zf_AwAA__9s9Vdr
> ```
The bytes read does not show up here, is it because testing code zeroes it out due to non-determinism and this results in not displaying the label?
</blockquote></details>

Yeah, we're setting `BytesRead` to 0 in `VectorizedStatsCollector.OutputStats`. I remember I tried not zeroing it out, but I saw some non-determinism, it might be worth trying it out again.

**Comment by cathymw** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54518#-MHV--3y9rD25hDsblHN:-MHkz1kV8i5_P8Icizx3:buxb9lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/acbc011679b88bcdba1b8fd2880b66c7799ae45a/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L54)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, we're setting `BytesRead` to 0 in `VectorizedStatsCollector.OutputStats`. I remember I tried not zeroing it out, but I saw some non-determinism, it might be worth trying it out again.
</blockquote></details>

Good idea, I'll try it again later today!

**Comment by cathymw** [comment]
Update on zeroing out `BytesRead`: it currently can't be removed. I tried stressing a couple logic test files and saw some non-determinism. The `explain_analyze_plans` test file didn't have any failures (up to ~1min), but the `dist_vectorize` one failed pretty quickly (less than 15s).

**Pull request merged**
