### PR TITLE
kvserver: retry failures to rebalance decommissioning replicas

### PR DESCRIPTION
**Pull request by aayushshah15**
Related to https://github.com/cockroachdb/cockroach/pull/80993
Relates to https://github.com/cockroachdb/cockroach/issues/79453

This commit makes it such that failures to rebalance replicas on
decommissioning nodes no longer move the replica out of the
replicateQueue as they previously used to. Instead, these failures now
put these replicas into the replicateQueue's purgatory, which will retry
these replicas every minute.

All this is intended to improve the speed of decommissioning towards
its tail end, since previously, failures to rebalance these replicas
meant that they were only retried after about 10 minutes.

Release note: None

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
Are there any existing tests for purgatory retry; or ensuring that on failure it is reprocessed at replicateQueuePurgatoryCheckInterval?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-:-N1_zWW898-tIn4wrq3K:bsf9gct)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @AlexTalks, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-N1_z8At9qzKOHcXgasm:-N1_z8At9qzKOHcXgasn:b7fmtbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/60f3f3a149738eec88ec82ab1867248ae30c9a94/pkg/kv/kvserver/replicate_queue.go#L395)):*
> ```Go
> 	}
> 
> 	// Register gossip and node liveness callbacks to signal that
> ```

I'm curious why not have both a callback on a gossip update and also a retry interval?

**Review by aayushshah15 — COMMENTED** [review]
>Are there any existing tests purgatory; or ensuring that on failure it is reprocessed at replicateQueuePurgatoryCheckInterval?

There's `TestBaseQueuePurgatory`, which asserts on the behavior of the base queue purgatory. This patch isn't doing much on top of that, since we're just tying the purg channel to a golang ticker (this is also what the mergeQueue currently does).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-:-N2Cu-J-3JAAyVF0sIpg:b-twsaau)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @kvoli, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-N1_z8At9qzKOHcXgasm:-N2CuMDb0kdSM3VpUaBW:b-qpud3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/60f3f3a149738eec88ec82ab1867248ae30c9a94/pkg/kv/kvserver/replicate_queue.go#L395)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I'm curious why not have both a callback on a gossip update and also a retry interval?
</blockquote></details>

That callback was never being used because none of the replicate queue errors were being marked as purgatory errors. Those callbacks would've only been useful if we were appropriately marking some "interesting" allocator errors as purg-errors.

However, determining "interesting" here with some accuracy is kind of hard without a refactor of some of the allocator's rebalancing logic. We'd need to restructure that code in a way that makes it more feasible to disambiguate between when the allocator can't find rebalance opportunities _due to zone configs_ and when it can't find opportunities due to other reasons (like when the system is already balanced).  

At the moment, it seems simpler to switch this to a more general "retry replicas in the purgatory every minute".

**Review by AlexTalks — COMMENTED** [review]
Overall looks good, but would it be worth adding a test for the case where we (now) get one of the `decommissionPurgatoryError`s on replacing/removing a decommissioning replica?  (Happy to take over and add if needed of course, which could be a useful exercise).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-:-N2EpyEk7a7NPYF5bJC-:b-t40v38)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @nvanbenschoten)

**Review by aayushshah15 — COMMENTED** [review]
> but would it be worth adding a test for the case where we (now) get one of the decommissionPurgatoryErrors on replacing/removing a decommissioning replica

Done, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-:-N2I2QFG3PuJF4TZ0yFf:b5vclp3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @nvanbenschoten)

**Review by kvoli — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-:-N2IEaPP6LMGffrvckT6:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by AlexTalks — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-:-N2JAMCYBtGnkhCeZoM7:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by aayushshah15** [comment]
TFTRs! 

bors r+

**Review by aayushshah15 — COMMENTED** [review]
> That callback was never being used because none of the replicate queue errors were being marked as purgatory errors.

Turns out this was a lie. There were indeed a couple of cases where the replicateQueue's errors were being marked as purgatory errors. 

See the first commit in this patch for how I've addressed the issue. cc @kvoli 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005#-:-N4JCXfK0idSMMSB8AQ7:b-z374r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @kvoli and @nvanbenschoten)

**Review by kvoli — APPROVED** [review]
> Reviewed 8 of 14 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81005)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nvanbenschoten)

**Comment by aayushshah15** [comment]
TFTRs

bors r+

**Pull request merged**
