### PR TITLE
idxconstraint: refactor benchmark

### PR DESCRIPTION
**Pull request by RaduBerinde**
Uncommenting and refactoring the index constraints benchmark.

Comparison with the same benchmark in the `opt` code:
```
name                               old time/op    new time/op    delta
IndexConstraints/point-lookup-8       291ns ± 0%     506ns ± 1%  +73.88%  (p=0.029 n=4+4)
IndexConstraints/no-constraints-8     802ns ± 1%     223ns ± 1%  -72.18%  (p=0.029 n=4+4)
IndexConstraints/range-8             1.25µs ± 1%    2.34µs ± 2%  +86.71%  (p=0.029 n=4+4)
IndexConstraints/range-2d-8          4.56µs ± 1%    4.23µs ± 0%   -7.40%  (p=0.029 n=4+4)
IndexConstraints/many-columns-8      8.32µs ± 1%    8.17µs ± 1%   -1.82%  (p=0.029 n=4+4)

name                               old alloc/op   new alloc/op   delta
IndexConstraints/point-lookup-8        208B ± 0%      256B ± 0%  +23.08%  (p=0.029 n=4+4)
IndexConstraints/no-constraints-8      272B ± 0%      144B ± 0%  -47.06%  (p=0.029 n=4+4)
IndexConstraints/range-8               528B ± 0%      664B ± 0%  +25.76%  (p=0.029 n=4+4)
IndexConstraints/range-2d-8          1.76kB ± 0%    1.01kB ± 0%  -42.73%  (p=0.029 n=4+4)
IndexConstraints/many-columns-8      3.82kB ± 0%    1.86kB ± 0%  -51.26%  (p=0.029 n=4+4)

name                               old allocs/op  new allocs/op  delta
IndexConstraints/point-lookup-8        4.00 ± 0%      5.00 ± 0%  +25.00%  (p=0.029 n=4+4)
IndexConstraints/no-constraints-8      3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.029 n=4+4)
IndexConstraints/range-8               14.0 ± 0%      19.0 ± 0%  +35.71%  (p=0.029 n=4+4)
IndexConstraints/range-2d-8            43.0 ± 0%      27.0 ± 0%  -37.21%  (p=0.029 n=4+4)
IndexConstraints/many-columns-8        88.0 ± 0%      40.0 ± 0%  -54.55%  (p=0.029 n=4+4)
```

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Those are some large deltas for the first 3 benchmarks. Any ideas what is going on?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23209#-:-L6RzdfguvrE0HS4Q2Eq:b-bgqs4b)*

**Comment by RaduBerinde** [comment]
I took a look at the first case. About 20% of the time is spent in `ConstructTrue` (which is how `RemainingFilter` represents a filter that has been completely simplified). The `ExprView` helper is also visible (10% for Child(), 2% for ChildCount(), 2% for Private()). I don't see anything else egregious.

**Comment by RaduBerinde** [comment]
We should investigate if using a big `switch` instead of a function table for things like `ChildCount`, `ChildGroup` is better (it might, since the function calls can't get inlined). We can also look at not using `TrueOp` and just return GroupID 0 (though it will require a bunch of special cases).

Anyway, part of the new code will be rewritten to integrate with Andy's constraint library. I also plan to investigate an alternate implementation where the remaining filter is computed directly when we calculate the spans (which avoids calculating the spans twice). So I don't plan to spend too much time optimizing the current version.

**Comment by rytaft** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23209#-:-L6S7FHs65avvC20eFiZ:bnfp4nl)*

**Comment by RaduBerinde** [comment]
I added a commit that skips `ConstructTrue` when the spans are tight. This reduces the hit on the "point-lookup" bench.

**Comment by rytaft** [comment]
:thumbsup: 

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23209#-:-L6S_n62wC-s04Zpt8U_:b4c9lyr)*

**Comment by andy-kimball** [comment]
I'm sure you all agree, but I'll state it here anyway : ). When improving micro-benchmarks, the only optimizations we should do are ones that don't interfere with or compromise the abstractions. An example of a change that doesn't interfere would be to use `switch` instead of a func lookup. An example of a change that does interfere would be using 0 for `TrueOp` in a way that forces special-cases to be sprinkled about. We should only ever consider doing the latter kind of change if we have a higher-level benchmark that suggests it's worthwhile. Otherwise, we might find we're cutting off microseconds down deep that make no difference up higher.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23209#-:-L6Se7ReNlhAOdh2FCsN:b-j8as46)*

**Comment by RaduBerinde** [comment]
Ok, I removed that commit. I verified that it makes no difference on the `Planning` benchmarks (which are in the hundred microsecond range).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23209#-:-L6SlealTzBwKQ817EOo:b8akake)*

**Comment by andy-kimball** [comment]
For the record, I didn't have a problem with returning 0 at the top level. That's pretty simple and scoped. I'd only be worried if there were special cases sprinkled all over.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23209#-:-L6SrVDekCCsD_sQaqDK:b-9lmvm)*

**Comment by RaduBerinde** [comment]
I see. I am hoping we'll find a better way to optimize this out (otherwise, if we go that direction, we will end up with more special cases).

One idea could be to always pre-allocate group 1 for TrueOp and have `ConstructTrue` just return 1. We could even tag singleton ops in the definitions with a special tag that makes them be pre-allocated.

**Pull request merged**
