### PR TITLE
release-22.1: kv/bulk: parallelize sending SSTs due to range bounds

### PR DESCRIPTION
**Pull request by dt**
Backport:
  * 2/2 commits from "kv/bulk: track send-wait by store" (#79612)
  * 2/2 commits from "kv/bulk: parallelize sending SSTs due to range bounds" (#79967)

Please see individual PRs for details.

/cc @cockroachdb/release

Addresses https://github.com/cockroachdb/cockroach/issues/79615

Release justification: high impact change motivated by customer request.

### CODE REVIEW

**Review by shermanCRL — APPROVED** [review]
Approved for extraordinary backport, pending code review from @nvanbenschoten.

**Review by nvb — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 9 of 9 files at r2, 1 of 1 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/kv/bulk/sst_batcher.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0I1WsA1_eZKeTo7RHA:-N0I1WsA1_eZKeTo7RHB:b-w4pf5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f838af21427ada68c637f64d667389d76ed4de4f/pkg/kv/bulk/sst_batcher.go#L483)):*
> ```Go
> 	}
> 
> 	if reason == rangeFlush {
> ```

I'm struggling to understand how this interacts with the `b.mu.lastRange` state. When we issue multiple AddSSTables concurrently, the information added to `b.mu.lastRange` will be non-deterministic (the previous request may not have finished, or its result may have been cloberred). Is this ok because we're only using concurrency in the `rangeFlush` case, and we only want to perform manual splits in the `rangeSize` case where we still issue requests serially? If so, I wonder whether we could make that more clear in the code. If the state in `b.mu.lastRange` is meaningless because it's non-deterministic, should we even set it in those cases?
___
*[pkg/kv/bulk/sst_batcher.go, line 692 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0I2mQX7u4MSqqyI8g2:-N0I2mQX7u4MSqqyI8g3:b9qs7d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f838af21427ada68c637f64d667389d76ed4de4f/pkg/kv/bulk/sst_batcher.go#L692)):*
> ```Go
> 	}
> 	b.mu.Lock()
> 	b.stats.splitRetries += files - 1
> ```

Should `b.stats` be in the `mu` struct?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/bulk/sst_batcher.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0I1WsA1_eZKeTo7RHA:-N0I3hjpBrl8MSIlpVEA:b-6tr565) ([raw file](https://github.com/cockroachdb/cockroach/blob/f838af21427ada68c637f64d667389d76ed4de4f/pkg/kv/bulk/sst_batcher.go#L483)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm struggling to understand how this interacts with the `b.mu.lastRange` state. When we issue multiple AddSSTables concurrently, the information added to `b.mu.lastRange` will be non-deterministic (the previous request may not have finished, or its result may have been cloberred). Is this ok because we're only using concurrency in the `rangeFlush` case, and we only want to perform manual splits in the `rangeSize` case where we still issue requests serially? If so, I wonder whether we could make that more clear in the code. If the state in `b.mu.lastRange` is meaningless because it's non-deterministic, should we even set it in those cases?
</blockquote></details>

async requests will indeed overwrite each other's `lastRange`, but i think last-write-wins is probably going to be fine, since as you say, if we're sending async flushes at all, we're probably already in the small-ssts-to-many-ranges case where we don't send our own splits anyway.

I could just make only size-flushes update lastRange if you'd prefer?
___
*[pkg/kv/bulk/sst_batcher.go, line 692 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0I2mQX7u4MSqqyI8g2:-N0I39bWAtz9b9lFM6L4:b-jc9f9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f838af21427ada68c637f64d667389d76ed4de4f/pkg/kv/bulk/sst_batcher.go#L692)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should `b.stats` be in the `mu` struct?
</blockquote></details>

Hm, I'd tried to avoid moving it, since most of the fields are accessed without holding mu. Indeed, the reader of this field doesn't lock it, since reads are done only by the log statement that is called after a flush() which has called .Wait(), so the locking is _only_ for write/write races.

I decided that was too confusing with the other ones and just made them atomics to avoid commenting all that; I could do the same here if you feel strongly.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/kv/bulk/sst_batcher.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0I1WsA1_eZKeTo7RHA:-N0I7RCBA0IlIYPOWrKz:b-fc9hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f838af21427ada68c637f64d667389d76ed4de4f/pkg/kv/bulk/sst_batcher.go#L483)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

async requests will indeed overwrite each other's `lastRange`, but i think last-write-wins is probably going to be fine, since as you say, if we're sending async flushes at all, we're probably already in the small-ssts-to-many-ranges case where we don't send our own splits anyway.

I could just make only size-flushes update lastRange if you'd prefer?
</blockquote></details>

If you did that then we could pull `b.mu.lastRange` out of the mutex, right? I would find that much easier to reason about.
___
*[pkg/kv/bulk/sst_batcher.go, line 692 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0I2mQX7u4MSqqyI8g2:-N0I7f6E14CzdhAhem7L:b-nzrnc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f838af21427ada68c637f64d667389d76ed4de4f/pkg/kv/bulk/sst_batcher.go#L692)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Hm, I'd tried to avoid moving it, since most of the fields are accessed without holding mu. Indeed, the reader of this field doesn't lock it, since reads are done only by the log statement that is called after a flush() which has called .Wait(), so the locking is _only_ for write/write races.

I decided that was too confusing with the other ones and just made them atomics to avoid commenting all that; I could do the same here if you feel strongly.
</blockquote></details>

I feel less strongly about this one. I'll defer to you.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @nvanbenschoten)

___
*[pkg/kv/bulk/sst_batcher.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0I1WsA1_eZKeTo7RHA:-N0IAbBS0XHU-93TBia7:b-1sfr77) ([raw file](https://github.com/cockroachdb/cockroach/blob/f838af21427ada68c637f64d667389d76ed4de4f/pkg/kv/bulk/sst_batcher.go#L483)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If you did that then we could pull `b.mu.lastRange` out of the mutex, right? I would find that much easier to reason about.
</blockquote></details>

added a commit (will forward port it to master too if it looks like what you were thinking)

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/kv/bulk/sst_batcher.go`, line 542 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0OtdfGCA543Odpt2Lx:-N0OtdfGCA543Odpt2Ly:b7obibq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46b95d4a270c29965a7ad2afc1aa36103317601/pkg/kv/bulk/sst_batcher.go#L542)):*
> ```Go
> 	sstBytes []byte,
> 	stats enginepb.MVCCStats,
> 	reason int,
> ```

Should this be the reason, or should this be a bool indicating that the addSSTable is being run concurrently? Or should this be a `trackLastRange bool`? In other words, whose responsibility should it be to make the decision about whether setting `b.lastRange` is needed and is thread-safe?

**Comment by stevendanna** [comment]
Heads up: I _think_ this change is implicated in a couple of nightly failures over on master; so we might want to hold off merging this until we have resolved https://github.com/cockroachdb/cockroach/issues/80436 and https://github.com/cockroachdb/cockroach/issues/80437

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/bulk/sst_batcher.go` line 542 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-N0OtdfGCA543Odpt2Lx:-N0VcITk8o9gSogh5ktY:b-9v1iz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46b95d4a270c29965a7ad2afc1aa36103317601/pkg/kv/bulk/sst_batcher.go#L542)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be the reason, or should this be a bool indicating that the addSSTable is being run concurrently? Or should this be a `trackLastRange bool`? In other words, whose responsibility should it be to make the decision about whether setting `b.lastRange` is needed and is thread-safe?
</blockquote></details>

Good point, makes sense.

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80386#-:-N0VgfJMBGlp_pk4wr9G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Pull request merged**
