### PR TITLE
streamingccl: skip TestStreamingRegionalConstraint

### PR DESCRIPTION
**Pull request by stevendanna**
Informs #112541

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
This might not be needed. It's possible the places we've seen this just haven't yet gotten https://github.com/cockroachdb/cockroach/pull/112597

**Comment by adityamaru** [comment]
nah i think I see this 3m45 sec timeout also not being enough: `condition failed to evaluate within 3m45s: from replication_stream_e2e_test.go:1207: running iterate callback: found table data located on another node 3` 😢 

cc: @msbutler

**Review by adityamaru — APPROVED** [review]

**Comment by adityamaru** [comment]
flake is unrelated

bors r=adityamaru

**Comment by adityamaru** [comment]
sorry i didnt see the conversation on the other issue. I will wait to get confirmation we want this.

bors r-

**Pull request closed without merging**
