### PR TITLE
opt: add rule to push a join into an index join

### LINKED ISSUE #49449: opt: reorder index joins with other joins
It some cases it is beneficial to push joins under index joins, especially if there is a hard limit that can be pushed down as well. A general solution seems very complicated, but we could at least have Limit-specific rules like `(Limit (Join (IndexJoin ..))) -> (IndexJoin (Limit (Join ..)))`

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds a rule that pushes InnerJoins and LeftJoins into an
IndexJoin if:
1. The IndexJoin is the left input of the non-index join (pushdown
   would be invalid for a LeftJoin, and an InnerJoin will simply be
   commuted).
2. The right input of the non-index join does not have outer columns.
3. The ON condition of the non-index join only references columns
   from its right input and the input of the index join.
4. The non-index join does not have any join hints.

This transformation can lead to a better plan if the non-index join
has a selective predicate.

Partially fixes #49449

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
Here are stats for the TPCH query that changed, for anyone curious:


Master Plan (ms) | Rule Plan (ms) | Master Total (ms) | Rule Total (ms)
-- | -- | -- | --
4.362333333 | 5.456666667 | 5372.876667 | 2453.687667

**Comment by DrewKimball** [comment]
I'm not sure if the check for outer columns in the right input of the non-index join is necessary; I'd appreciate any thoughts on this.

**Comment by DrewKimball** [comment]
@RaduBerinde do you think it's ok to use the TableID from the IndexJoin for the LookupJoin?

**Comment by RaduBerinde** [comment]
Yeah, that should be fine. Nice improvement in that query!!

**Review by rytaft — APPROVED** [review]
:lgtm: Nice improvement!

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-:-MB0rrU851gmaBEezepR:b-6f8vr5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, and @RaduBerinde)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0q_JVC_qU2Pp6xumw:-MB0q_JW562LucKWLAmd:bkd2ojz) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/custom_funcs.go#L2583)):*
> ```Go
> // ConvertIndexToLookupPrivate constructs a new LookupJoinPrivate using the
> // given IndexJoinPrivate with the given output columns.
> func (c *CustomFuncs) ConvertIndexToLookupPrivate(
> ```

[nit] I think this function name should include the word "join" somewhere
___
*[pkg/sql/opt/xform/rules/join.opt, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0pzZ91-cvpy38Nny4:-MB0pzZA2GnQdPfbgtJy:b-tocs7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/rules/join.opt#L244)):*
> ```
> # PushJoinIntoIndexJoin pushes an InnerJoin or LeftJoin into an IndexJoin. The
> # IndexJoin is replaced with a LookupJoin, since it now must output columns from
> # the right side of the join as well as from the original lookup table.
> ```

It would help to give a bit of insight about why this might be a better plan in some cases.
___
*[pkg/sql/opt/xform/rules/join.opt, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0pNDT0YTJNsOrc85L:-MB0pNDT0YTJNsOrc85M:bhvjdzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/rules/join.opt#L247)):*
> ```
> # Matching conditions:
> # 1. The IndexJoin is the left input of the non-index join (push-down would be
> #    invalid for a LeftJoin, and an InnerJoin will simply be commuted).
> ```

This is a bit confusing -- I'd either leave out the part in parentheses or go into more detail.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0rQLf-XRnlkecg9ES:-MB0rQLf-XRnlkecg9ET:bynppkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/testdata/rules/join#L3220)):*
> ```
>  ├── lookup columns are key
>  ├── fd: (1)-->(2-5)
>  ├── inner-join (lookup abc@ab)
> ```

are there any test cases where this remains a left join?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50679)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 2583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0q_JVC_qU2Pp6xumw:-MB7zySgBN8r1bfWx16M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/custom_funcs.go#L2583)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I think this function name should include the word "join" somewhere
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0pzZ91-cvpy38Nny4:-MB83epBDRX1Ex3zIIRB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/rules/join.opt#L244)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It would help to give a bit of insight about why this might be a better plan in some cases.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0pNDT0YTJNsOrc85L:-MB8-QOK68u7Yrz2NTcl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/rules/join.opt#L247)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is a bit confusing -- I'd either leave out the part in parentheses or go into more detail.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0rQLf-XRnlkecg9ES:-MB82_Bn7w0SDPKhLPuZ:bit3r4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/testdata/rules/join#L3220)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

are there any test cases where this remains a left join?
</blockquote></details>

Huh. Actually, that was just a stupid bug - I was replacing LeftJoins with InnerJoins. 

I'm now realizing that the LeftJoin case isn't interesting anyway; a LeftJoin can't decrease the cardinality of rows that serve as input to the IndexJoin since unmatched left rows are just added back. If and when we add a rule that pushes a limit into a LookupJoin, matching LeftJoins might become worth it.

I think I'll remove LeftJoins entirely, at least for the time being.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-:-MB99xxSEtUcCrvpwGLO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, and @RaduBerinde)

___
*[pkg/sql/opt/xform/rules/join.opt, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB99TtDAKlKs5sSJRg7:-MB99TtEEx8WyQquR3_X:bjeku2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebbb567831accf5284be99953c65bf19896830bf/pkg/sql/opt/xform/rules/join.opt#L252)):*
> ```
> # 2. The ON condition of the InnerJoin only references columns from its right
> #    input and the input of the IndexJoin.
> # 4. The InnerJoin does not have any join hints.
> ```

4 -> 3
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB0rQLf-XRnlkecg9ES:-MB99s2xEBJdymgSznNB:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/833ea10d3234ff35165b723dce520649a745e74f/pkg/sql/opt/xform/testdata/rules/join#L3220)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Huh. Actually, that was just a stupid bug - I was replacing LeftJoins with InnerJoins. 

I'm now realizing that the LeftJoin case isn't interesting anyway; a LeftJoin can't decrease the cardinality of rows that serve as input to the IndexJoin since unmatched left rows are just added back. If and when we add a rule that pushes a limit into a LookupJoin, matching LeftJoins might become worth it.

I think I'll remove LeftJoins entirely, at least for the time being.
</blockquote></details>

Sounds good.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50679)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/rules/join.opt, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50679#-MB99TtDAKlKs5sSJRg7:-MBAbXzc93gbo8I-Og1p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebbb567831accf5284be99953c65bf19896830bf/pkg/sql/opt/xform/rules/join.opt#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

4 -> 3
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50679)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

**Comment by DrewKimball** [comment]
TFTR!

**Pull request merged**
