### PR TITLE
kvccl: Propogate context through follower read validation

### PR DESCRIPTION
**Pull request by navsetlur**
We currently don't propogate the context through the code that validates if a request can use a follower to read data. We need the context to log any debug messages, so updating this code to take in a context argument.

Epic: none
Release note: none

### CODE REVIEW

**Review by nvb — APPROVED** [review]

**Review by dt — APPROVED** [review]
nit: commit message title (first line) should be something like `kvccl/kvfollowerreadsccl: propagate...` or just `kvccl: propagate...`

and then you don't need the `pkg: ` line in the body.

**Comment by navsetlur** [comment]
bors r=nvanbenschoten,dt

**Comment by coditamar** [comment]
@CodiumAI-Agent /review

**Comment by coditamar** [comment]
@CodiumAI-Agent /improve

**Comment by coditamar** [comment]
@CodiumAI-Agent /describe
--pr_description.publish_labels=false
--pr_description.publish_description_as_comment=true

**Pull request merged**
