### PR TITLE
storage: add MVCC range tombstone handling for scans and gets

### PR DESCRIPTION
**Pull request by erikgrinaker**
This is for the `mvcc-range-tombstones` branch. Only the last commit should be reviewed here -- the former are from #78085 and its ancestors.

This will need performance optimizations both in MVCC and Pebble before being merged, as it's been seen to have a severe performance penalty (up to 40%). For now, focus on correctness.

---

This patch adds MVCC range tombstone handling for scans and gets. In the
basic case, this simply means that point keys below an MVCC range
tombstone are not visible.

When tombstones are requested by the caller, the MVCC range tombstones
themselves are never exposed, to avoid having to explicitly handle these
throughout the codebase. Instead, synthetic MVCC point tombstones are
emitted at the start of MVCC range tombstones and wherever they overlap
a point key (above and below). Additionally, point gets return synthetic
point tombstones even if no existing point key exists.

The point tombstone synthesis is implemented by a new
`pointSynthesizingIterator`, an `MVCCIterator` implementation that wraps
an existing `MVCCIterator`. This allows e.g. `pebbleMVCCScanner` to
remain unchanged, and automatically take MVCC range tombstones into
account for e.g. conflict/uncertainty checks.

Point tombstone synthesis must be enabled even when the caller has not
requested tombstones, because they must always be taken into account for
conflict/uncertainty checks. However, in these cases we enable range key
masking below the read timestamp, omitting any covered points since
these are no longer needed.

Touches #70412.

Release note: None

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[pkg/storage/testdata/mvcc_histories/range_tombstone_scans, line 6 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-MzvluZN7E-_uOhClb1V:-MzvluZN7E-_uOhClb1W:b-hl5occ) ([raw file](https://github.com/cockroachdb/cockroach/blob/855437f9523cb46b4c9114cf04e66ff670e38ed9/pkg/storage/testdata/mvcc_histories/range_tombstone_scans#L6)):*
> ```
> #
> #  T
> #  6                 [e6]     
> ```

nit: looks like there's some extra whitespace here.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, @jbowens, and @nicktrav)

___
*[pkg/storage/point_synthesizing_iter.go, line 21 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-N-TmuTeE_blAW7SLAMQ:-N-TmuTeE_blAW7SLAMR:bcrczw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3987c8131ffe2c578a0e6ae636aaf717e8c888/pkg/storage/point_synthesizing_iter.go#L21)):*
> ```Go
> 
> // pointSynthesizingIter wraps an MVCCIterator, and synthesizes point tombstones
> // for range tombstones above/below existing point keys. It does not emit range
> ```

is "range tombstones" the same as "MVCC range tombstone" accomplished via a RANGEKEYSET?
Just calling it "range tombstone" will confuse folks who are thinking of Pebble range tombstones.
I don't have good naming ideas.
___
*[pkg/storage/point_synthesizing_iter.go, line 23 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-N-To4efDi8t3DoZdSrN:-N-To4efDi8t3DoZdSrO:b-8pbc2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3987c8131ffe2c578a0e6ae636aaf717e8c888/pkg/storage/point_synthesizing_iter.go#L23)):*
> ```Go
> // for range tombstones above/below existing point keys. It does not emit range
> // keys at all, since these would appear to conflict with the synthesized point
> // keys.
> ```

how does this honor scans that set FailOnMoreRecent or want to do Uncertainty checking? They need to see a range key even if there is no overlapping point, yes?

**Review by jbowens — COMMENTED** [review]
I like the general approach of synthesizing point tombstones. 

> When the Tombstones option is disabled, range key masking is enabled
to omit point keys below older range tombstones during iteration.
However, point synthesis must still be enabled in this case to account
for future range tombstones in uncertainty checks.

Does this mean point tombstones are synthesized at the start key of the range tombstone in this case?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-:-N-UlX3aET67YMy4CRaS:b-x06gib)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @nicktrav)

**Review by erikgrinaker — COMMENTED** [review]
>Does this mean point tombstones are synthesized at the start key of the range tombstone in this case?

Not currently -- they're synthesized around point keys that are above the masking range tombstone. Consider e.g. the case where we're masking @2, and have b@1, [a-c)@2, b@3, [a-c)@4. In this case, b@1 is masked, but we'll synthesize point tombstones for b@2 and b@4.

However, we should likely synthesize points at the start of each range key fragment too -- this handles both FailOnMoreRecent for bare range tombstones and tombstone synthesis for point reads where there is no existing point (replaces `emitOnSeek`). Not sure yet whether this on-start behavior should always be enabled, or if we should make it optional -- will probably start off with always-on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-:-N-mVJG-6MqO6l5gmML5:b-q3wrc0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @nicktrav, and @sumeerbhola)

___
*[pkg/storage/point_synthesizing_iter.go, line 21 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-N-TmuTeE_blAW7SLAMQ:-N-mWPBF0d2wPE8T4kgr:b-xslzq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3987c8131ffe2c578a0e6ae636aaf717e8c888/pkg/storage/point_synthesizing_iter.go#L21)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is "range tombstones" the same as "MVCC range tombstone" accomplished via a RANGEKEYSET?
Just calling it "range tombstone" will confuse folks who are thinking of Pebble range tombstones.
I don't have good naming ideas.
</blockquote></details>

Yes, MVCC range tombstones. I don't think it's too confusing -- we already have the same issue with point tombstones and I don't find it too hard to distinguish between Pebble and MVCC point tombstones from context. But I'll be more consistent in specifying MVCC/Pebble tombstones.
___
*[pkg/storage/point_synthesizing_iter.go, line 23 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-N-To4efDi8t3DoZdSrN:-N-mWioWDY4w0OPc-fOF:b-128z3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3987c8131ffe2c578a0e6ae636aaf717e8c888/pkg/storage/point_synthesizing_iter.go#L23)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how does this honor scans that set FailOnMoreRecent or want to do Uncertainty checking? They need to see a range key even if there is no overlapping point, yes?
</blockquote></details>

Good point. We should synthesize points at the start/seek key of range tombstones too, which handles both FailOnMoreRecent and Uncertainty for both scans and gets without point keys. This would replace `emitOnSeek`.
___
*[pkg/storage/testdata/mvcc_histories/range_tombstone_scans, line 6 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/78946#-MzvluZN7E-_uOhClb1V:-N-mXYL5-xCemrlwq_5o:b-x52gbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/855437f9523cb46b4c9114cf04e66ff670e38ed9/pkg/storage/testdata/mvcc_histories/range_tombstone_scans#L6)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: looks like there's some extra whitespace here.
</blockquote></details>

Thanks, fixed.

**Comment by erikgrinaker** [comment]
This should be ready for a high-level review now. It should be functionally complete and correct.

However, this comes with a significant performance hit for scans, on the order of 30-50%. A quick looked indicated that much of this was in Pebble. We'll need to do more systematic benchmarking and optimization before we merge this to `master`.

**Comment by erikgrinaker** [comment]
Tests caught an invariant violation. I don't think it affects correctness, but I'm going to restructure the internal logic a bit since I think it hints at a possible simplification and performance optimization. Reverting this to draft for now, since I have some other stuff to get to first.

**Comment by erikgrinaker** [comment]
Ok, this should be ready for a high-level review now.

**Comment by erikgrinaker** [comment]
Replaced by #82045.

**Pull request closed without merging**
