### PR TITLE
tests,ui: add a multi-store test with single overloaded store

### PR DESCRIPTION
**Pull request by sumeerbhola**
Admission control will slow down writes to that store without
affecting operations on the other store.

Also fixed some related graphs on the overload dashboard
- the "IO tokens exhausted" graph should have been using a rate
- the kv-stores metrics were missing

Informs #65955,#65957

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69241#-MhnnHi94K1548QgMPro:-MhnnHi94K1548QgMPrp:b-q0vegg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5962902919a5e46a54dea2c6fa3e6c0686bcbdf/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L135)):*
> ```XML
>             <Metric
>               key={nid}
>               name="cr.node.admission.admitted.kv-stores"
> ```

what are these `kv-stores` metrics?

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69241#-:-MhnnaVp7_ORgzjd-tpE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69241#-:-Mhnt_M59JVrmJuncPO0:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69241#-MhnnHi94K1548QgMPro:-MhnquXs1UwGhJQTzFAo:biilpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5962902919a5e46a54dea2c6fa3e6c0686bcbdf/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L135)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what are these `kv-stores` metrics?
</blockquote></details>

I've now fixed the title. These are KV writes that go through the per-store admission queue for writes to that store.
Unfortunately, these get aggregated across the stores for a node, so one has to look at the logs like the following to figure out what is happening:
```
I210823 16:22:51.409270 438 util/admission/granter.go:1508 ⋮ [-] 161  IO overload on store 2: admitted: 53095, added: 4004169100, removed (2439986424, 1832396738), admit: (12148.725787, 8307)
```

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69241)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69241#-MhnnHi94K1548QgMPro:-MhnvY_213fAjgUPJuzU:b62v9hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5962902919a5e46a54dea2c6fa3e6c0686bcbdf/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L135)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I've now fixed the title. These are KV writes that go through the per-store admission queue for writes to that store.
Unfortunately, these get aggregated across the stores for a node, so one has to look at the logs like the following to figure out what is happening:
```
I210823 16:22:51.409270 438 util/admission/granter.go:1508 ⋮ [-] 161  IO overload on store 2: admitted: 53095, added: 4004169100, removed (2439986424, 1832396738), admit: (12148.725787, 8307)
```
</blockquote></details>

Right right, fwiw we do store the data per store. We're aggregating it here at query time. See the `sources` thing. I think it's a rather big lift to plumb that sort of change all the way to the ui. I filed that here https://github.com/cockroachdb/cockroach/issues/68987.

**Pull request merged**
