### PR TITLE
ui: statement insight details page v1

### PR DESCRIPTION
**Pull request by ericharmeling**
This PR adds the Statement Insights Details page to the DB Console.

https://www.loom.com/share/e9c7be3eb5da47b784b119b6fc9bbeb9

Release justification: low-risk updates to new functionality

Release note (ui change): Added statement insight details page to DB Console.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 16 of 16 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 23 of 27 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx` line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAK4cFAB7IDxN6DNeeP:-NAK4cFAB7IDxN6DNeeQ:b-t98kpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ae32f9b23a923d865244a1106c5415789b838e/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx#L130)):*
> ```XML
>     return (
>       <>
>         <section>
> ```

after you rebase, change to `<section className={tableCx("section")}>`
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx` line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAK4lMACbpxWIzl63jV:-NAK4lMACbpxWIzl63jW:bw2s2ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ae32f9b23a923d865244a1106c5415789b838e/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx#L133)):*
> ```XML
>           <Row gutter={24}>
>             <Col className="gutter-row" span={24}>
>               <SqlBox value={insightDetails.query} />
> ```

after you rebase, add `size={SqlBoxSize.custom}`

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`pkg/ui/workspaces/db-console/src/views/insights/insightsSelectors.ts` line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAKI2-68N7z1kG22NBO:-NAKI2-68N7z1kG22NBP:b-mq8e6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ae32f9b23a923d865244a1106c5415789b838e/pkg/ui/workspaces/db-console/src/views/insights/insightsSelectors.ts#L80)):*
> ```XML
>     }
>     const insightId = getMatchParamByName(props.match, "id");
>     return insights.data.find(insight => insight.statementID === insightId);
> ```

if the users go to this page directly, this value might not have been set, so add `.data?.find`

**Review by maryliag — COMMENTED** [review]
Great to see the refactors, looks great!

> Reviewed 2 of 27 files at r5, 18 of 20 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-:-NAPyjRyAvu3lGxbRELR:biz1ni4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 307 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAPxz1FBT_ESCyveUvh:-NAPxz1G9GsrX_LtwRgG:b3ftnbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29a10ef502c5b39419c0e1f242cae7ba39e70aa/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L307)):*
> ```XML
> }
> 
> export function getPriorityFromNumber(priority: number): string {
> ```

are you still gonna need this, after the PR Jake merged about changing the priority to the string already?

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/utils.ts` line 307 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAPxz1FBT_ESCyveUvh:-NAPz___AKiDhXB9SMLs:b-9oovcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29a10ef502c5b39419c0e1f242cae7ba39e70aa/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L307)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

are you still gonna need this, after the PR Jake merged about changing the priority to the string already?
</blockquote></details>

Good point! Just fixed this (and verified that it worked).
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx` line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAK4cFAB7IDxN6DNeeP:-NAPzgDR6O8suDcj4BRu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ae32f9b23a923d865244a1106c5415789b838e/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx#L130)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

after you rebase, change to `<section className={tableCx("section")}>`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx` line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAK4lMACbpxWIzl63jV:-NAPzfxi5JxquSHcJQPS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ae32f9b23a923d865244a1106c5415789b838e/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx#L133)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

after you rebase, add `size={SqlBoxSize.custom}`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/insights/insightsSelectors.ts` line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-NAKI2-68N7z1kG22NBO:-NAKSFRZ3iodOD5zLGI1:biz05lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ae32f9b23a923d865244a1106c5415789b838e/pkg/ui/workspaces/db-console/src/views/insights/insightsSelectors.ts#L80)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if the users go to this page directly, this value might not have been set, so add `.data?.find`
</blockquote></details>

Great point. Done.

**Review by maryliag — APPROVED** [review]
Awesome! :lgtm: 

> Reviewed 1 of 20 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86779#-:-NAQOewO3QFzUghTrf1r:b-i581jd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Pull request merged**
