### PR TITLE
vendor: bump apd to v3.1.2

### PR DESCRIPTION
**Pull request by cucaroach**
vendor: bump apd to v3.1.2
    
Pull in optimizations around decimal string handling.
    
Release note: None

Epic [CRDB-14916](https://cockroachlabs.atlassian.net/browse/CRDB-14916)

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90982#-:-NFieO_-1aJ7bPbNw-ya:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

**Comment by cucaroach** [comment]
Looked good except a Bazel Essential CI flake so re-running.

**Pull request merged**
