### PR TITLE
sql: return an error message when trying to show grants for an invalid user

### LINKED ISSUE #32811: sql: SHOW GRANTS on empty db does not show grant on db until new table is created.
**Describe the problem**

After freshly installing CockroachDB and creating 2 user, I tried to grant privileges to a user. The command doesn't fail but the desired outcome is not achieved. Upon looking into all the `grants` for the user it shows blank.

**To Reproduce**
`
#cockroach sql --insecure --user=root
#Welcome to the cockroach SQL interface.
#All statements must be terminated by a semicolon.
#To exit: CTRL + D.
#
#Server version: CockroachDB CCL v2.1.1 (x86_64-unknown-linux-gnu, built 2018/11/19 18:24:21, go1.10.3) (same version as client)
#Cluster ID: e76fcc16-02a9-41d6-90a6-5679d62302dc
#
#Enter \? for a brief introduction.
#
root@:26257/defaultdb> show databases;
  database_name
+---------------+
  apimgtdb
  defaultdb
  postgres
  regdb
  statdb
  system
  userdb
(7 rows)

Time: 2.1338ms
root@:26257/defaultdb> show users;
   user_name
+-------------+
  cmu
  root
  wso
(3 rows)

Time: 1.847701ms
root@:26257/defaultdb> GRANT SELECT ON DATABASE apimgtdb to wso;
GRANT

Time: 5.316302ms

root@:26257/defaultdb> show grants for wso;
  database_name | schema_name | table_name | grantee | privilege_type
+---------------+-------------+------------+---------+----------------+
(0 rows)

Time: 4.539601ms

`

**Expected behavior**
That user `wso` should have privileges

**Environment:**
# cockroach version
Build Tag:    v2.1.1
Build Time:   2018/11/19 18:24:21
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  4523f9819d2dde9b054fc8faf1568e107f130986
Build Type:   release

OS: Centos7

### PR DESCRIPTION
**Pull request by jackcwu**
Release justification: None, waiting for 22.1
Release note: None

Resolves https://github.com/cockroachdb/cockroach/issues/32811

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work!

one nit: the convention is to make the PR title have a title of `package: lower case description`. And in the PR body you should add a line like references #32811, which will automatically link to the issue. (Usually, you don't need the Github issue link in the commit, just in the PR)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-:-MjozGTp3uoeKFOqtMjJ:b-6xk05y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu and @RichardJCai)

___
*[pkg/sql/opt_catalog.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-Mjoz4ha3vvqhJJ3ntR4:-Mjoz4ha3vvqhJJ3ntR5:b-ao2atu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0f9db7ed51b66ac7f5d103490a1af1ccbe1ed0/pkg/sql/opt_catalog.go#L374)):*
> ```Go
> }
> 
> // RoleExists returns true if the role exists.
> ```

nit: the comment can mention the interface, like

```
// RoleExists is part of the cat.Catalog interface.
```
___
*[pkg/sql/delegate/show_grants.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-Mjoyms8E_l1jAJpJWxs:-Mjoyms8E_l1jAJpJWxt:b-umytx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0f9db7ed51b66ac7f5d103490a1af1ccbe1ed0/pkg/sql/delegate/show_grants.go#L242)):*
> ```Go
> 	// terminate on invalid users
> 	for _, p := range n.Grantees {
> 		user, _ := security.MakeSQLUsernameFromUserInput(string(p), security.UsernameValidation)
> ```

nit: let's check the error from `MakeSQLUsernameFromUserInput`

**Review by RichardJCai — APPROVED** [review]
LGTM after nit fixes

Also still need to address Rafis point about changing the PR title and commit name.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-:-Mk8UCv-65tvnIf5pBX3:b-4rk574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu, @rafiss, and @RichardJCai)

___
*[pkg/sql/delegate/show_grants.go, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-Mk8TqI645_YeKMbYYsZ:-Mk8TqI645_YeKMbYYs_:b-nm68c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d097b5cd6a2b6ed822729c9d1eb250e60f6fe520/pkg/sql/delegate/show_grants.go#L240)):*
> ```Go
> 	`, source.String(), cond.String(), orderBy)
> 
> 	// terminate on invalid users
> ```

nit: End comment on period and capitalize first char, we like to use correct grammar in comments.
___
*[pkg/sql/logictest/testdata/logic_test/grant_database, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-Mk8U05h2OtlqLvbM5_B:-Mk8U05h2OtlqLvbM5_C:byvgypm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d097b5cd6a2b6ed822729c9d1eb250e60f6fe520/pkg/sql/logictest/testdata/logic_test/grant_database#L188)):*
> ```
> b              public       t           testuser  ALL
> 
> # Calling SHOW GRANTS on an invalid user should error out
> ```

nit: add period
___
*[pkg/sql/opt/cat/catalog.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-Mk8U1oJ1MW0k26QnuLt:-Mk8U1oJ1MW0k26QnuLu:byvgypm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d097b5cd6a2b6ed822729c9d1eb250e60f6fe520/pkg/sql/opt/cat/catalog.go#L161)):*
> ```Go
> 	FullyQualifiedName(ctx context.Context, ds DataSource) (DataSourceName, error)
> 
> 	// RoleExists returns true if the role exists
> ```

nit: add period

**Review by rafiss — APPROVED** [review]
lgtm! also, btw, since the 21.2 branch has been cut now, we don't need release justifications anymore :)

> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-:-MkFZDtn8ek6WKjRwt97:bmvud8y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu)

**Review by rafiss — APPROVED** [review]
when you're ready to merge add a comment that either says `bors r+` or `bors r=rafiss,RichardJCai`

(the bors comment has to be on its own line)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-:-MkFZKHp0zxYY8C-IJwc:baupn22)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu)

**Review by rafiss — CHANGES_REQUESTED** [review]
the CI is failing because of the import ordering linter: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3509877?expandedTest=build%3A%28id%3A3509867%29%2Cid%3A7408

seems like your automatic crlfmt might be missing

**Review by jackcwu — COMMENTED** [review]
got it, hopefully it'll work this time

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-:-MkrhKsGDwmTv41I55bO:b-clre9e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

**Comment by rafiss** [comment]
ah looks like the bazel dependencies need to be updated too. you can do it with
```
make bazel-generate
```

**Review by jackcwu — COMMENTED** [review]
updated!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70361#-:-MkwkG-p8796_-ur14DL:b-cypxrp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

**Review by rafiss — APPROVED** [review]
lgtm! feel free to merge by adding a `bors r+` (or `bors r=rafiss,RichardJCai`) comment

**Pull request merged**
