### PR TITLE
ui: Add search and filtering to the databases pages

### LINKED ISSUE #68825: ui: add search to the databases pages
Part of #65737 (see designs there). Also a follow-on to #68390.

Jira issue: CRDB-9289

Epic CRDB-20388

### PR DESCRIPTION
**Pull request by gtr**
Part Of [#68826](https://github.com/cockroachdb/cockroach/issues/68826), [#68825](https://github.com/cockroachdb/cockroach/issues/68825).

Previously, the databases and databases details pages did not contain
search and filter components that the txns and stmts pages did. This
change adds search and filter components to both the databases and
databases details pages. The search box filters by database/table name
while the filter allows filtering by node and region.

[Databases Page video](https://www.loom.com/share/185c66981f6c495b9b194eab027045ea).

[Tables Page video](https://www.loom.com/share/8ae9ccaba8db43bd80c009519b026c70).

Release note (ui change): the databases page and the databases details
pages each now contain search and filter components, allowing the
ability to search and filter through databases and their tables.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92589)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI7xWHDE3XqmMTc8nk1):*
Nit: you can't use `Fixes` because it still needs to be done on CC Console, so this should be `Part Of`, and you should include on the commit message
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI7yPWf7JhlW78aFRgk:-NI7yPWf7JhlW78aFRgl:b-wr0efl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c39728da264870fc5ee8c968df40b9da9504cbb/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L51)):*
> ```XML
>   calculateActiveFilters,
> } from "src/queryFilter";
> import { nodeRegions } from "src/transactionsPage/transactions.fixture";
> ```

fixture files are used for testing, if you need a new struct type, it should be created on another location

**Review by maryliag — COMMENTED** [review]
Nice work!
What happens when you're on Database details and change from tables to grants?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-:-NI8S-Om7-jEIaI2T1gT:b-u3q139)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8QORl0Gb_JNWksRfj:-NI8QORl0Gb_JNWksRfk:b-8rt52y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L372)):*
> ```XML
>       {
>         app: filters.app,
>         timeNumber: filters.timeNumber,
> ```

you don't need to sync values that you don't actually show filters for
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8QecwBJ3OuUUZdkFC:-NI8QecwBJ3OuUUZdkFD:b4bizq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L415)):*
> ```XML
>         table => {
>           if (regionsSelected.length == 0 && nodesSelected.length == 0) return true;
>           if (isTenant) return true;
> ```

why is returning true for tenants?
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8RI6a82sTMWYr2uLm:-NI8RI6a82sTMWYr2uLn:b-r3jchg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L752)):*
> ```XML
>     const activeFilters = calculateActiveFilters(filters);
> 
>     const nodes = isTenant
> ```

tenants will have a list of nodes, we just don't show nodes info when is tenant, we hide that and show only region info
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8RR31Dnj5sNzkfk0v:-NI8RR31Dnj5sNzkfk0w:b-xxn0u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L758)):*
> ```XML
>         .sort();
> 
>     const regions = isTenant
> ```

tenants do have regions
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8SLVJCfaR7QArUn8T:-NI8SLVJCfaR7QArUn8U:b-esibh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L51)):*
> ```XML
>   handleFiltersFromQueryString
> } from "../queryFilter";
> import { merge} from "lodash";
> ```

nit: you need the space after `merge`
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 413 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8SuDu7TpJfIpoZhhT:-NI8SuDu7TpJfIpoZhhU:b1uupj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L413)):*
> ```XML
>       {
>         app: filters.app,
>         timeNumber: filters.timeNumber,
> ```

ditto: sync only the values you're using on this filter
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8T0UB9EgTFkBj8Gd-:-NI8T0UB9EgTFkBj8Gd0:boqelhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L447)):*
> ```XML
>         db => {
>           if (regionsSelected.length == 0 && nodesSelected.length == 0) return true;
>           if (isTenant) return true;
> ```

same question: why returning true on this case?
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 599 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8T9SwEgkasNYSpW5n:-NI8T9SwEgkasNYSpW5o:b-urmst2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L599)):*
> ```XML
> 
>   render(): React.ReactElement {
>     this.columns.find(c => c.name === "nodeRegions").showByDefault = true;
> ```

curious: why this change?
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8TDoA5Qd1P_RXlSdp:-NI8TDoB0VS8LyDAZZQh:bfaw8xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L620)):*
> ```XML
>         .sort();
> 
>     console.log("nodes:", Object.keys(nodeRegions).join(","));
> ```

remove this log
___
*[`pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8ToKM5SO_n_LApm74:-NI8ToKM5SO_n_LApm75:b1k6v6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts#L201)):*
> ```XML
>       lastError: null,
>       name: "system",
>       nodes: [],
> ```

if you want to test, you should add actual values for the cases where it loaded and have no error

**Review by gtr — COMMENTED** [review]
Good question! My most recent update makes it so that when you're on the Database details page and change from tables to grants, the filters component gets hidden. The search box still works because it looks at the table name column.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-:-NIJfrNPEqyStoscnZsB:b-nb9hzs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI7xWHDE3XqmMTc8nk1):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Nit: you can't use `Fixes` because it still needs to be done on CC Console, so this should be `Part Of`, and you should include on the commit message
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI7yPWf7JhlW78aFRgk:-NI8x50pAnOzLPh8mn-p:b-ddrguu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c39728da264870fc5ee8c968df40b9da9504cbb/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L51)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

fixture files are used for testing, if you need a new struct type, it should be created on another location
</blockquote></details>

Good catch! I added a selector for nodeRegions in the Redux layer.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8QORl0Gb_JNWksRfj:-NI8xJcl6piuf8sSyGro:b-tgc7p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L372)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you don't need to sync values that you don't actually show filters for
</blockquote></details>

Removed all the values except nodes and regions.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8QecwBJ3OuUUZdkFC:-NIJgLKF3ax9JNPpJIkS:b7y52s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L415)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why is returning true for tenants?
</blockquote></details>

I was under the assumption that if the cluster is a tenant cluster, then the node/region would be irrelevant. Removed this line.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8RI6a82sTMWYr2uLm:-NI9-WM18h9PRzodlbhI:bckcmcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L752)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

tenants will have a list of nodes, we just don't show nodes info when is tenant, we hide that and show only region info
</blockquote></details>

Oh okay, got it! I removed the `isTenant` check for this line but added a check to the Filter's `showNodes` option to only show nodes when it is **not** a tenant and then the length of the nodes is greater than 1:
```
showNodes={!isTenant && nodes.length > 1}
```
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8RR31Dnj5sNzkfk0v:-NI911nH8kf2iBiJX2CE:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L758)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

tenants do have regions
</blockquote></details>

Fixed.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8SLVJCfaR7QArUn8T:-NI94sy55nX7M4rt6MNb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L51)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you need the space after `merge`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 413 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8SuDu7TpJfIpoZhhT:-NI94s45EIA4lOHfGl_1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L413)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

ditto: sync only the values you're using on this filter
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8T0UB9EgTFkBj8Gd-:-NIJgYPrBUWq_Qxh34GA:bai136l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L447)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same question: why returning true on this case?
</blockquote></details>

Removed this line.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 599 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8T9SwEgkasNYSpW5n:-NI9AAeO2RZ6YH7X3uDD:b10886j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L599)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

curious: why this change?
</blockquote></details>

I left this in by accident! Reverted back.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8TDoA5Qd1P_RXlSdp:-NI974Y07I3ArJNiFXjb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L620)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

remove this log
</blockquote></details>

Done.



_Code quote:_
```XML
console.log("
```
___
*[`pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8ToKM5SO_n_LApm74:-NIJgaa0Emao6Uom_3bA:b-1ucev4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts#L201)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if you want to test, you should add actual values for the cases where it loaded and have no error
</blockquote></details>

I added test cases for different nodes:
```typescript
driver.assertDatabaseProperties("system", {
    ...
    nodes: [1, 2, 4],
    ...
    nodesByRegionString: "undefined(n1,n2,n4)",
    ...
 });
```
But I am unable to define a region; currently it displays `undefined`.

**Review by maryliag — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92589)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NIZ6kh1EDTHW7R5oxUg):*
tip: if you just type `#68826` github automatically creates the link for you, so you don't need to worry
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8QecwBJ3OuUUZdkFC:-NIZ7DJ08dvbb_o5OH81:b-wse9k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L415)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

I was under the assumption that if the cluster is a tenant cluster, then the node/region would be irrelevant. Removed this line.
</blockquote></details>

The line is still here :) 
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 413 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8SuDu7TpJfIpoZhhT:-NIZ7_QT-9hB7FYVB3cZ:b-i0h2sw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L413)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still seeing all the non-used value
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8T0UB9EgTFkBj8Gd-:-NIZ7doP2LCtqpvI-OOm:bo5pxak) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L447)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Removed this line.
</blockquote></details>

Still seeing
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 611 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NIZ7j9BADHXfVaSAbKE:-NIZ7j9BADHXfVaSAbKF:bfaw8xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3e8b6755a4b686f1e1979c1fa7104f861d5787/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L611)):*
> ```XML
>     } = this.props;
> 
>     console.log("databasesPage.isTenant =", isTenant);
> ```

remove this log
___
*[`pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts` line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NIZ7xf09Dg8KF9C5anh:-NIZ7xf09Dg8KF9C5ani:bgxpvx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3e8b6755a4b686f1e1979c1fa7104f861d5787/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts#L380)):*
> ```XML
> });
> 
> // function makeStateWithNodeRegions() {
> ```

remove unused function/comment

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92589)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NIZ6kh1EDTHW7R5oxUg):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

tip: if you just type `#68826` github automatically creates the link for you, so you don't need to worry
</blockquote></details>

Got it! I had done this on the GitHub's description but not the git commit comment.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8QecwBJ3OuUUZdkFC:-NIZdEaX8myNqOio-LdE:b-bq1wwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L415)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

The line is still here :) 
</blockquote></details>

Oops, deleted.



_Code quote:_
```XML
if (isTenant) return true;
```
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 413 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8SuDu7TpJfIpoZhhT:-NIZeH-6Dx61ajd6L0De:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L413)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Still seeing all the non-used value
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NI8T0UB9EgTFkBj8Gd-:-NIZddIK6nckMxwxI7ad:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1650d487fcf759cee1d9dd1638f87bb2b163b832/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L447)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Still seeing
</blockquote></details>

Done.



_Code quote:_
```XML
 if (isTenant) return true;
```
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 611 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NIZ7j9BADHXfVaSAbKE:-NIZdez6A6mEUJtzwPsu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3e8b6755a4b686f1e1979c1fa7104f861d5787/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L611)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

remove this log
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts` line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-NIZ7xf09Dg8KF9C5anh:-NIZdwv3DIczoXS0imiw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3e8b6755a4b686f1e1979c1fa7104f861d5787/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts#L380)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

remove unused function/comment
</blockquote></details>

Done.



_Code quote:_
```XML
makeStateWithNodeRegions()
```

**Comment by gtr** [comment]
Updates on the `pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts` test file:

In order to test the database properties (specifically `nodes` and `nodesByRegionString`, it was necessary to introduce a `stubNodesUI` function to the `fakeAPI` in order to stub in information about which nodes belong to which regions:
```typescript
export function stubNodesUI(
  response: cockroach.server.serverpb.INodesResponseExternal,
) {
  stubGet(`/nodes_ui`, NodesResponse.encode(response), STATUS_PREFIX);
}
```

The assertion happens after we fill in the database details and node/region info:
```typescript
driver.assertDatabaseProperties("system", {
    ...
    name: "system",
    nodes: [1, 2, 4],
    sizeInBytes: 7168,
    tableCount: 2,
    rangeCount: 3,
    nodesByRegionString: "gcp-us-east1(n1,n2,n4)",
    ...
});

driver.assertDatabaseProperties("test", {
    ...
    name: "test",
    nodes: [3, 5, 6],
    sizeInBytes: 1234,
    tableCount: 1,
    rangeCount: 42,
    nodesByRegionString: "gcp-europe-west1(n3,n6), gcp-europe-west2(n5)",
    ...
});
```

The next part of testing this function involves recognizing whether the cluster is a tenant cluster. If so, we redact node information and only show the regions for `nodesByRegionString`, e.g. `"gcp-europe-west1(n3,n6), gcp-europe-west2(n5)"` becomes `"gcp-europe-west1, gcp-europe-west2"`. This was a little more difficult to test since from my understanding, we don't support multi tenant on `db-console` so when connecting the state to the props in `pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts`, I hardcoded a value for `isTenant`:
```typescript
// Hardcoded isTenant value for db-console.
const isTenant = false;
```

However, I modified the functions that generate the `nodesByRegionString` value to be aware of the `isTenant` value. So if we change the `isTenant` hardcoded value to `true`, this is what we see in the UI:

image

The region column and the region filter only displays the region names. However, I'm still not entirely convinced that we should hard code this value since there would be three places where we would have to do so: 
- `db-console/src/views/databases/databasesPage/redux.ts`
- `db-console/src/views/databases/databaseDetailsPage/redux.ts`
- `db-console/src/views/databases/databaseTablePage/redux.ts`

**Review by maryliag — APPROVED** [review]
The value for `isTenant` is only set when the page comes from CC on the props, but we don't set it when coming from DB console, this way the value will be undefined and when doing checks of `isTenant?` it will only be true when coming from CC, but undefined from DB console. 
Because we only use on the page itself, we don't need to worry about setting a value for DB console, but now because you changed some of the functions definitions/parameter on the redux file, then you indeed need to hard code a value to be passed on.

> Reviewed 10 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-:-NKxKoEt9jKz2-x5Wn4K:b-sitq5r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

**Comment by gtr** [comment]
> The value for `isTenant` is only set when the page comes from CC on the props, but we don't set it when coming from DB console, this way the value will be undefined and when doing checks of `isTenant?` it will only be true when coming from CC, but undefined from DB console. Because we only use on the page itself, we don't need to worry about setting a value for DB console, but now because you changed some of the functions definitions/parameter on the redux file, then you indeed need to hard code a value to be passed on.
> 
> > Reviewed 10 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92589#-:-NKxKoEt9jKz2-x5Wn4K:b-sitq5r)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

Okay that makes sense, TFTR!

**Pull request merged**
