### PR TITLE
sql: unify InternalExecutor and SessionBoundInternalExecutor

### PR DESCRIPTION
**Pull request by andreimatei**
The internal executor is a library that started bad and got worse. It
came in two flavors: InternalExecutor and SessionBoundInternalExecutor.
The interface was confusing, only matched by the implementation. And
besides tomes of code, neither of them could do the basic thing of
allowing a higher layer to bind most of the session data for future
internal queries, but let the user be overriden at the query site.

This patch does away with the SessionBoundInternalExecutor. It's
functionality is absorbed into the InternalExecutor. The ie now gets a
SetSessionData() method, used to bind session data. An extended query
interface is added, allowing some aspects of this session data to be
overriden on a per-query basis.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks it was useful to extract this in its own PR because now TC is teaching you something useful. I think the tests are pointing out that the default db should not be set automatically in some cases (that's on purpose). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44170#-:-Lz93-6vA4JTbhLlM_tm:bv2abe3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by andreimatei** [comment]
Well TC was teaching me the same thing on the old branch too.
But anyway, can you tell me more about what you suspect is going on with this failure? I thought it's because we now end up *not* setting some database in `sessionData`. You think it's the opposite?

**Comment by knz** [comment]
yes it is the opposite. The message `cannot access virtual schema in anonymous database` must occur when the two following conditions are met together:

- the current database is the empty string
- the test is querying `info_schema` or `pg_catalog`

If the current db is not the empty string, the vtable can be accessed properly and instead the regular SQL semantics on the result kick in.

**Comment by knz** [comment]
So the test is telling you "I want my current db to be empty" and your new internal executor is making it non-empty.

**Comment by andreimatei** [comment]
I've fixed the failing test by no longer running in the "system" database when running as root.
The implicit "run as root" behavior that we have really bothers me. I've done what I could to mark the respective methods as deprecated and have others require a user. PTAL.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 19 of 22 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44170#-:-LzBQ5Ay3Eb7e59X5tkb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/internal.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44170#-LzBPOwu6z1veeYPuTV_:-LzBPOwu6z1veeYPuTVa:b-6pehqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5252cccda4d5cfc0bf513442d930460436521a35/pkg/sql/internal.go#L178)):*
> ```Go
> //
> // Query is deprecated because it may transparently execute a query as root. Use
> // QueryEx instead.
> ```

Can you file an issue and assign it to @otan and me to review all the SQL builtins and check that they are not using this method in unsafe ways (i.e. giving access to privileged data to non-admin users).
This implicit-run-as-root behavior is indeed highly problematic and I'm not sure we fully realized that before. There may be a sec vulnerability hidden in there.
___
*[pkg/sql/sqlutil/internal_executor.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44170#-LzBPtAq8E9Qz11Wi2QT:-LzBPtAr1XDhzXwcTHXR:b-59dl9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5252cccda4d5cfc0bf513442d930460436521a35/pkg/sql/sqlutil/internal_executor.go#L57)):*
> ```Go
> 
> 	// Query executes the supplied SQL statement and returns the resulting rows.
> 	// The statement is executed as the root user.
> ```

Please update the mention about the user here.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44170)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @otan)

___
*[pkg/sql/internal.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44170#-LzBPOwu6z1veeYPuTV_:-LzDpGlR-9z4azyDSOyI:b-l67l1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5252cccda4d5cfc0bf513442d930460436521a35/pkg/sql/internal.go#L178)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you file an issue and assign it to @otan and me to review all the SQL builtins and check that they are not using this method in unsafe ways (i.e. giving access to privileged data to non-admin users).
This implicit-run-as-root behavior is indeed highly problematic and I'm not sure we fully realized that before. There may be a sec vulnerability hidden in there.
</blockquote></details>

https://github.com/cockroachdb/cockroach/issues/44223
___
*[pkg/sql/sqlutil/internal_executor.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44170#-LzBPtAq8E9Qz11Wi2QT:-LzDOc5KEJ4jo9Q0Q6DH:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5252cccda4d5cfc0bf513442d930460436521a35/pkg/sql/sqlutil/internal_executor.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please update the mention about the user here.
</blockquote></details>

done

**Comment by knz** [comment]
:+1:

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44170#-:-LzI7UwtCwZEqlThS0g5:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @otan)

**Pull request merged**
