### PR TITLE
enginepb: strongly type TxnEpoch, TxnSeq, and TxnPriority

### PR DESCRIPTION
**Pull request by nvb**
Over the past few releases, we've slowly increased the role that transaction sequence numbers play in the transaction model. Even with their increased role, working with sequence numbers is a little tough because they aren't strongly typed.

This PR fixes that by creating a `TxnSeq` type. While doing so, it also does the same for `TxnEpoch` and `TxnPriority`. This allows us to let the compiler take the lead when refactoring related areas. It also gives us a good place to add authoritative documentation on each concept.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@tbg This is the first step in me addressing your final comment from #35763.

> What's so tricky about the migration? You wouldn't start using parallel commits until all nodes have upgraded, and so the only thing you have to guarantee is that a pre-parallel-commits txn record doesn't get mistaken for one that has parallel commits going on, but the txn status alone will do that.
BTW couldn't you get away with replacing Span with SpanAndSeq, using the zero seqno for non-in-flight writes.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 12 of 12 files at r2, 23 of 23 files at r3, 28 of 28 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36073#-:-LapKbVT48OlizZYNDoj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/api.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36073#-LapJoQwD9-QfsieSil6:-LapJoQwD9-QfsieSil7:b-fn99dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cac063ae1cb578130afbafb2abf4035268a10c9/pkg/roachpb/api.go#L56)):*
> ```Go
> )
> 
> // A RangeID is a unique ID associated to a Raft consensus group.
> ```

nit: commit message claims that you're moving stuff from and to `metadata.go`.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36073)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/api.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36073#-LapJoQwD9-QfsieSil6:-LaqTETC5XqI1uJW0ob4:bksbihv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cac063ae1cb578130afbafb2abf4035268a10c9/pkg/roachpb/api.go#L56)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: commit message claims that you're moving stuff from and to `metadata.go`.
</blockquote></details>

The message just says "move RangeID and RangeIDSlice to metadata.go". Unless I'm missing something?

**Pull request merged**
