### PR TITLE
go.mod: import etcd-io/raft at 4967cffe

### PR DESCRIPTION
**Pull request by pav-kv**
This includes a fix for the leaks in the in-flight tracker.

Release note: none
Epic: none

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
Need to scan what other upstream things are added here.

**Comment by tbg** [comment]
https://github.com/etcd-io/raft/compare/5fe1c31c5158...4967cffe43c1b5c369bc571fb6e80750978007f2

Looks like it's mostly your changes around slice hygiene. Are we comfortable picking these up? Otherwise we can temporarily fork raft and only cherry-pick the fix.

**Comment by pavelkalinnikov** [comment]
> Are we comfortable picking these up? Otherwise we can temporarily fork raft and only cherry-pick the fix.

Yeah, comfortable to pick it up in master. Did the suggested cherry-pick in the release branch.

**Review by tbg — APPROVED** [review]

**Comment by pavelkalinnikov** [comment]
bors r=tbg

**Pull request merged**
