### PR TITLE
jobs,sql: prevent mutation from reverting multiple times

### LINKED ISSUE #46018: sql: re-adopting a reverting schema change with rolled-back mutations may not work
When reverting schema change jobs, the `OnFailOrCancel` hook currently attempts to roll back any mutations on the table descriptor unconditionally. This will cause problems if we have to re-adopt the reverting job multiple times. I suspect (but don't know for sure) that we'll hit this assertion error when we try to reverse the same mutations multiple times:
https://github.com/cockroachdb/cockroach/blob/3b2f269147b5c78c9942d2f927d86858967bc4f5/pkg/sql/schema_changer.go#L1343

### PR DESCRIPTION
**Pull request by pbardea**
When schema changes fail or are canceled, the mutations corresponding to
the schema change are reversed. If a schema changer is abandoned after
it has reversed the mutation, but before it completes it can be adopted
again and the mutations cannot be reversed again, so the job
continuously fails.

This commit updates the schema change to only revert mutations if they
have not already been reverted.

Fixes #46018.

Release justification: this fixes a bug in the schema change to jobs
refactor. Note that this bug was never shipped in a release.

Release note: None (fixes bug in feature not released yet)

### CODE REVIEW

**Comment by danhhz** [comment]
Subscribe

**Review by thoszhang — APPROVED** [review]
It might be useful to mention in the release note (just for our sake, not for users) that this fixes a bug that was never released, since it purely affects the new schema change job.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46232#-:-M2idno_7i3drvdpxBHP:bw6vzp7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/sql/schema_changer.go, line 1064 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46232#-M2ieOkg0etdsc145dba:-M2ieOkg0etdsc145dbb:bioexin) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dc27220e8c385c814766e732e49dae266a8ea43/pkg/sql/schema_changer.go#L1064)):*
> ```Go
> // applying a schema change. If a column being added is reversed and dropped,
> // all new indexes referencing the column will also be dropped.
> func (sc *SchemaChanger) reverseMutations(ctx context.Context, causingError error) error {
> ```

Maybe rename to `maybeReverseMutations`?
___
*[pkg/sql/schema_changer_test.go, line 5799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46232#-M2if6Ou2bh2jNAC0arT:-M2if6Ou2bh2jNAC0arU:b7ie8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dc27220e8c385c814766e732e49dae266a8ea43/pkg/sql/schema_changer_test.go#L5799)):*
> ```Go
> 		t.Fatal(err)
> 	}
> }
> ```

I think it'd be useful to do `SELECT v FROM t.test` or something at the end, to make sure that the rollback happened correctly.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/schema_changer.go, line 1064 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46232#-M2ieOkg0etdsc145dba:-M2iihwsAYNRG7XCKU8T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dc27220e8c385c814766e732e49dae266a8ea43/pkg/sql/schema_changer.go#L1064)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Maybe rename to `maybeReverseMutations`?
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 5799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46232#-M2if6Ou2bh2jNAC0arT:-M2iiiKo8PkSOEBCV3I9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dc27220e8c385c814766e732e49dae266a8ea43/pkg/sql/schema_changer_test.go#L5799)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I think it'd be useful to do `SELECT v FROM t.test` or something at the end, to make sure that the rollback happened correctly.
</blockquote></details>

Done.

**Review by pbardea — COMMENTED** [review]
Updated the release justification and release notes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46232#-:-M2ijEaVCrBAAIc5-e4M:b-36hxrl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Review by thoszhang — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Comment by pbardea** [comment]
TFTR!
bors r+

**Comment by pbardea** [comment]
Forgot to update the PR text with the updated commit text.
bors r=lucy-zhang

**Pull request merged**
