### PR TITLE
sql: implement ALTER TABLE LOCALITY !(REGIONAL BY ROW) -> REGIONAL BY ROW

### PR DESCRIPTION
**Pull request by otan**
This change introduces the ability to add a column before doing an alter
primary key for transforming to REGIONAL BY ROW if the crdb_region does
not already exist.

We exclusively whitelist the check in AlterPrimaryKey which allows an
add column mutation from SET LOCALITY CHANGES. Since we
do not run this mutation in conjunction with any other schema changes,
it is a safer space to reason about.

We also whitelist the ability for CreatePartitioning to partition a
non-backfilled column for only the ALTER TABLE LOCALITY case.

The rest of the logic "falls out" fairly easily since the schema changer
seems to be able to support this state. Tests have been added to
simulate cancels during both the ADD COLUMN and ADD PRIMARY KEY step.

Release note (sql change): Implement the ability to ALTER TABLE SET
LOCALITY to REGIONAL BY ROW without specifying AS for global and
regional by table items.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Buttery smooth :grin: 

Nit on the comment: "items" at the end is a bit abstract.  "tables"?  If you're worried about the double "table" at the end, just switch the order of the two table types.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-:-MSmjhK81nm-p0dmiF5I:b3dgbyb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSml0S04538DZTqPXW1:-MSml0S04538DZTqPXW2:b-q97lgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L438)):*
> ```
> 
> query TT
> SHOW ZONE CONFIGURATION FOR TABLE created_as_global
> ```

Dumb question - remind me why we don't show the partition-level zone configs here.  Wouldn't they apply to the table more than the database-level zone config?
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmlYtoD9Ouklzp3HkZ:-MSmlYtoD9Ouklzp3Hk_:bbyjp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L459)):*
> ```
>   index(b),
>   unique(i),
>   crdb_region crdb_internal_region,
> ```

This is an interesting case, and one I'm not sure we want to allow.  If I'm understanding things correctly, the column you've added is of the correct type, but it's got no default value.  Does this mean that we'll be able to add NULL values to the column?  Or will that get rejected because NULL is not in the enum?  Either way, it would be good to test.  I'd think though, that we'd need NOT NULL and a DEFAULT value defined on this column.
___
*[pkg/ccl/partitionccl/partition.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmoLEPC9Adk5IpYOvA:-MSmoLEPC9Adk5IpYOvB:b-be32wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/ccl/partitionccl/partition.go#L335)):*
> ```Go
> 	for _, allowedNewColName := range allowedNewColumnNames {
> 		if allowedNewColName == col {
> 			f = tableDesc.FindActiveOrNewColumnByName
> ```

Nit: for performance does it make sense to add a `break` here after we find the first one?
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmqe-N689t4equdN03:-MSmqe-N689t4equdN04:b-figecf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/ccl/partitionccl/regional_by_row_test.go#L59)):*
> ```Go
> 	// To round up x / y using integers, we do (x + y - 1) / y.
> 	// In this case, since x=maxValue+1, we do (maxValue + chunkSize) / chunkSize.
> 	var chunksPerBackfill = (maxValue + int(chunkSize)) / int(chunkSize)
> ```

@arulajmani if you're only going to review part of this PR, can you take a look at this testcase?  It looks reasonable to me, but I've never written one of these before, so I can't be certain.
___
*[pkg/sql/alter_primary_key.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmruIL3Zp-CsJpr7WY:-MSmruIL3Zp-CsJpr7WZ:bc8az4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_primary_key.go#L34)):*
> ```Go
> type alterPrimaryKeyLocalitySwap struct {
> 	localityConfigSwap descpb.PrimaryKeySwap_LocalityConfigSwap
> 	// AllowMutationOnSameTxnIdx is the index of the mutation to allow exist on
> ```

Nit: I'd call this indexWhichCanBeMutatedInSameTxn.   Also, the wording of this comment doesn't parse for me.  Maybe "indexWhichCanBeMutatedInSameTxn is the index for which we allow mutations to exist in the same transaction as the ALTER PRIMARY KEY...".

Actually, wait, I may be misunderstanding the intent here.  This is a column index (and not a secondary index), right?  If so, I'd suggest columnIdxWhichCandBeMutatedInSameTxn (it's long, but hopefully is accurate).
___
*[pkg/sql/alter_primary_key.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmx9xx2pZmb5vGInWH:-MSmx9xx2pZmb5vGInWI:b-2pxiiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_primary_key.go#L39)):*
> ```Go
> 	// where we allow a column add an a primary key change in the same
> 	// transaction.
> 	// It is nilable to prevent the 0 index being allowed in case the struct is
> ```

To "prevent"?  Or to "allow"?  I'm not fully following this part of the comment.
___
*[pkg/sql/alter_table_locality.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn0SOeAt3CUo3PWvip:-MSn0SOeAt3CUo3PWviq:b-ujgaml) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_table_locality.go#L204)):*
> ```Go
> 	if err != nil {
> 		// If this column does not exist and we are using REGIONAL BY ROW, we create
> 		// the new column. Otherwise, we have an undefined column.
> ```

Nit: This comment might read better if we break up the two conditions we're checking below.  Something like "Return the error if we get anything other than "undefined column" back from the function above, and we were actually looking for a column".

On second thought, this code might be clearer if we check for the active column only if we're not in the "newLocality.RegionalByRowColumn == tree.RegionalByRowRegionNotSpecifiedName" case.  Then we could set `createDefaultRegionCol = true` unconditionally in that case.
___
*[pkg/sql/alter_table_locality.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn4-nGBvps8oboowKp:-MSn4-nGBvps8oboowKq:bjg60iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_table_locality.go#L244)):*
> ```Go
> 			return err
> 		}
> 	} else {
> ```

Nit: Might be easier to follow if this was a separate `if` branch before the `if` above.  That way you don't have to scroll way up to figure out to what this `else` is referring.
___
*[pkg/sql/alter_table_locality.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn4HE6C6s3ivjzu3p0:-MSn4HE6C6s3ivjzu3p1:b-e96ow8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_table_locality.go#L248)):*
> ```Go
> 			return pgerror.Newf(
> 				pgcode.InvalidTableDefinition,
> 				"cannot use column %s for REGIONAL BY ROW as it does not have the %s type",
> ```

Nit: "...for a REGIONAL BY ROW TABLE..."
___
*[pkg/sql/create_table.go, line 2633 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn-s0t1JPTole2V_zB:-MSn-s0t1JPTole2V_zC:bj8jkvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/create_table.go#L2633)):*
> ```Go
> 	c.DefaultExpr.Expr = &tree.CastExpr{
> 		Expr: &tree.FuncExpr{
> 			Func: tree.WrapFunction("gateway_region"),
> ```

Nit: Can we make this a tree const?  I could imagine uses for this elsewhere.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSml0S04538DZTqPXW1:-MSzAKUy131J56vocmlz:b-l5md6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L438)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Dumb question - remind me why we don't show the partition-level zone configs here.  Wouldn't they apply to the table more than the database-level zone config?
</blockquote></details>

https://github.com/cockroachdb/cockroach/issues/56969
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmlYtoD9Ouklzp3HkZ:-MSzHga848JYEg-J4JZb:b-bfrrvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L459)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This is an interesting case, and one I'm not sure we want to allow.  If I'm understanding things correctly, the column you've added is of the correct type, but it's got no default value.  Does this mean that we'll be able to add NULL values to the column?  Or will that get rejected because NULL is not in the enum?  Either way, it would be good to test.  I'd think though, that we'd need NOT NULL and a DEFAULT value defined on this column.
</blockquote></details>

ive added a check for NULL - that was bad. good catch.

i don't think we should assert any default value here in case it's desired to be explicit (same reason we don't assert it to be hidden).
___
*[pkg/sql/alter_primary_key.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmruIL3Zp-CsJpr7WY:-MSzIm0lEtk3ZCuOd8Fd:ba4d5ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_primary_key.go#L34)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I'd call this indexWhichCanBeMutatedInSameTxn.   Also, the wording of this comment doesn't parse for me.  Maybe "indexWhichCanBeMutatedInSameTxn is the index for which we allow mutations to exist in the same transaction as the ALTER PRIMARY KEY...".

Actually, wait, I may be misunderstanding the intent here.  This is a column index (and not a secondary index), right?  If so, I'd suggest columnIdxWhichCandBeMutatedInSameTxn (it's long, but hopefully is accurate).
</blockquote></details>

not quite, it is the `mutation idx`.  `mutationIdxAllowedInSameTxn`
___
*[pkg/sql/alter_table_locality.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn0SOeAt3CUo3PWvip:-MSzBvTu-qDXDHJ6f5r-:boe8jgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_table_locality.go#L204)):*
> On second thought, this code might be clearer if we check for the active column only if we're not in the "newLocality.RegionalByRowColumn == tree.RegionalByRowRegionNotSpecifiedName" case. Then we could set createDefaultRegionCol = true unconditionally in that case.

Don't think so;  we still want to take crdb_region if it already exists I feel. Unless I misunderstand what you're saying; mind typing out what you had in mind?
___
*[pkg/sql/create_table.go, line 2633 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn-s0t1JPTole2V_zB:-MSzBSKo5ryjifWog5P7:b-99z7so) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/create_table.go#L2633)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Can we make this a tree const?  I could imagine uses for this elsewhere.
</blockquote></details>

i think it's very specific and only tied to this function, so i think i want to leave this as is for now.

**Review by ajstorm — APPROVED** [review]
Only nits left.  :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-:-MT10J8X-scjaKBp0NMz:b1mnojo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT0rxir9ekfRo3lzawe:-MT0rxir9ekfRo3lzawf:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L480)):*
> ```
> 
> statement error cannot use column crdb_region for REGIONAL BY ROW table as it may contain NULL values
> ALTER TABLE created_as_global SET LOCALITY REGIONAL BY ROW
> ```

Nice!
___
*[pkg/sql/alter_primary_key.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSmruIL3Zp-CsJpr7WY:-MT0t0uN7NlpSQf7L4eD:b-htvx48) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_primary_key.go#L34)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not quite, it is the `mutation idx`.  `mutationIdxAllowedInSameTxn`
</blockquote></details>

Thanks for the clarification.  The comment above still doesn't parse for me.  Can we change it to "mutationIdxAllowedInSameTxn is the index of the mutation which is allowed to exist in the same transaction as an ALTER PRIMARY KEY.  It is required for the case where we're adding a column to the table (the implicit crdb_internal_region colunm) as part of a PRIMARY KEY change, when transitioning a table to REGIONAL BY ROW."  We can then also simplify the second comment, which contains vital information relevant to the first field.

Also, at the end of the comment, super-nit: "It is nilable to prevent the 0 index _from_ being used..."
___
*[pkg/sql/alter_table_locality.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn0SOeAt3CUo3PWvip:-MT0v9KpErkhU44X9Ofn:b3a9qgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/alter_table_locality.go#L204)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> On second thought, this code might be clearer if we check for the active column only if we're not in the "newLocality.RegionalByRowColumn == tree.RegionalByRowRegionNotSpecifiedName" case. Then we could set createDefaultRegionCol = true unconditionally in that case.

Don't think so;  we still want to take crdb_region if it already exists I feel. Unless I misunderstand what you're saying; mind typing out what you had in mind?
</blockquote></details>

Oh yeah, I didn't think of that case.  Can we restructure slightly, so that it's a bit more readable (and that case is called out more clearly)?

```
	var partCol <type>
        partColName := newLocality.RegionalByRowColumn
	if newLocality.RegionalByRowColumn == tree.RegionalByRowRegionNotSpecifiedName {
		partColName = tree.RegionalByRowRegionDefaultColName
                // It's possible that we'll need to create a column to store the region, but the column may already 
                // exist if the user created a crdb_region column manually.
                mightNeedToCreateDefaultRegionCol = true
	}
	   partCol, err := n.tableDesc.FindColumnWithName(partColName)
	   if !sqlerrors.IsUndefinedColumnError(err) || !mightNeedToCreateDefaultRegionCol {
			// The column that was specified doesn't exist, or we got an error searching for it.
                        return err
	    }
            createDefaultRegionCol = true   
        }
```
___
*[pkg/sql/create_table.go, line 2633 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MSn-s0t1JPTole2V_zB:-MT107bA-BvJyKkCPQre:b819iv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a15e03131a95381354c9695c0203d272cdbe4e7/pkg/sql/create_table.go#L2633)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think it's very specific and only tied to this function, so i think i want to leave this as is for now.
</blockquote></details>

Don't we also use it in defining the build-in though? Could we not use the same constant for there, here?

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @otan)

___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1EnDtCkEmKZ08JGQT:-MT1EnDu3lHoLD8-bxhH:b3ridiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L138)):*
> ```Go
> 			setupQuery:            `CREATE TABLE t.test (k INT NOT NULL, v INT) LOCALITY GLOBAL`,
> 			toRegionalByRowQuery:  `ALTER TABLE t.test SET LOCALITY REGIONAL BY ROW`,
> 			checkAfterCancel:      checkGlobal,
> ```

In addition to checking the locality of the table, we should also ensure that the column is rolled back. 
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1ExoRDDShKN4rVWEy:-MT1ExoRDDShKN4rVWEz:bq0t28h) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L145)):*
> ```Go
> 			setupQuery:            `CREATE TABLE t.test (k INT NOT NULL, v INT) LOCALITY GLOBAL`,
> 			toRegionalByRowQuery:  `ALTER TABLE t.test SET LOCALITY REGIONAL BY ROW`,
> 			checkAfterCancel:      checkGlobal,
> ```

Same comment as above, we should probably be ensuring that the column is rolled back correctly. 
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1EHwMAcwiIKMen1rO:-MT1EHwMAcwiIKMen1rP:b1pe5e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L192)):*
> ```Go
> 							return nil
> 						}
> 						if _, err := db.Exec(`CANCEL JOB (
> ```

Is there any difference between the job getting cancelled and there being an error during the backfill? Do we need to test both scenarios?
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1HM_s39zDR57BsrDj:-MT1HM_s39zDR57BsrDk:bx4uvfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L225)):*
> ```Go
> 			}
> 
> 			if _, err := sqlDB.Exec(`
> ```

Maybe I'm misunderstanding this, but don't you want to get rid of this? (In all cases except the ones which are `REGIONAL BY ROW AS`)
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1Ff2fASU7WQ81Ml04:-MT1Ff2fASU7WQ81Ml05:bdszybk) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L232)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			// This will fail, so we don't want to check the error.
> ```

If this is expected to fail we should check `err == nil` and maybe even check the specific error that's expected here using `testutils.IsError`

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @lucy-zhang)

___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1EnDtCkEmKZ08JGQT:-MT2Z4IG6WFSCCuAmQv-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L138)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

In addition to checking the locality of the table, we should also ensure that the column is rolled back. 
</blockquote></details>

Done.
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1ExoRDDShKN4rVWEy:-MT2Z3t21NKQWeZ27AVx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L145)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same comment as above, we should probably be ensuring that the column is rolled back correctly. 
</blockquote></details>

Done.
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1EHwMAcwiIKMen1rO:-MT2_t7bCoCtepgw0Wqp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L192)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is there any difference between the job getting cancelled and there being an error during the backfill? Do we need to test both scenarios?
</blockquote></details>

Done.
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1HM_s39zDR57BsrDj:-MT2Z9x1-VUecEfWO-L1:b-s0sezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L225)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Maybe I'm misunderstanding this, but don't you want to get rid of this? (In all cases except the ones which are `REGIONAL BY ROW AS`)
</blockquote></details>

we can always add it; the non AS version will make the new implicit column anyway. The AS test needs it, it's easier in the test setup to just include it on all tables :D
___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1Ff2fASU7WQ81Ml04:-MT2Z8y3756lql7zBYW7:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L232)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

If this is expected to fail we should check `err == nil` and maybe even check the specific error that's expected here using `testutils.IsError`
</blockquote></details>

Done

**Review by arulajmani — APPROVED** [review]
You probably want someone from Schema to give you the final approval, but things LGTM 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-:-MT2sBAb2NWDGQkDwGS-:b-s3l0o5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1HM_s39zDR57BsrDj:-MT2po0t9MtVahBdNma8:bnkqxzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L225)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

we can always add it; the non AS version will make the new implicit column anyway. The AS test needs it, it's easier in the test setup to just include it on all tables :D
</blockquote></details>

Yeah, the column name is `cr`, not `crdb_region`. Could you add a comment for future us? 
___
*[pkg/sql/alter_primary_key.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT2q7sg0AoUpZfnFc3O:-MT2q7sg0AoUpZfnFc3P:bitj7ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1197fb5ce85147dc8e248cd86344f06b56d35ad/pkg/sql/alter_primary_key.go#L41)):*
> ```Go
> 	// It is nilable to prevent the 0 index from being used in case the struct
> 	// is initialized with values improperly set.
> 	mutationIdxAllowedInSameTxn *int
> ```

Are mutation indexes stable, or do we want the mutation ID instead?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @lucy-zhang)

___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT1HM_s39zDR57BsrDj:-MT2uJWQ3MLg62YA8Af5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/845ea767bc961342539f7b5c8caacabbeaacda27/pkg/ccl/partitionccl/regional_by_row_test.go#L225)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Yeah, the column name is `cr`, not `crdb_region`. Could you add a comment for future us? 
</blockquote></details>

Done.
___
*[pkg/sql/alter_primary_key.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT2q7sg0AoUpZfnFc3O:-MT2u79m4i2RkzdOrLCs:bqivm0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1197fb5ce85147dc8e248cd86344f06b56d35ad/pkg/sql/alter_primary_key.go#L41)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Are mutation indexes stable, or do we want the mutation ID instead?
</blockquote></details>

mutation IDs may not be assigned yet, and a mutation ID can last across multiple mutations.
the checks that are bypassed only exist during a time in which the mutation indexes are stable.

**Review by ajwerner — APPROVED** [review]
:lgtm: just nits

> Reviewed 3 of 11 files at r1, 2 of 7 files at r2, 2 of 5 files at r3, 2 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-:-MT8G-W4-gujhRImNf0R:busdgnz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/partitionccl/regional_by_row_test.go, line 56 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT8APLuDHTmS6xO23YW:-MT8APLuDHTmS6xO23YX:b-x7ck6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cf160d2fa1855ade1e6d9b1386053ce54382e/pkg/ccl/partitionccl/regional_by_row_test.go#L56)):*
> ```
> 
> 	// BulkInsertIntoTable adds from 0 to maxValue inclusive, so round up
> 	// we round (maxValue + 1) / chunkSize to the nearest int.
> ```
nit: the grammar is a tad off here. 
___
*[pkg/sql/alter_table.go, line 811 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT8BQLRCqgHF486S0hs:-MT8BQLS97i6JzACqFje:b6u8ht8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cf160d2fa1855ade1e6d9b1386053ce54382e/pkg/sql/alter_table.go#L811)):*
> ```Go
> 				*n.tableDesc.GetPrimaryIndex().IndexDesc(),
> 				t.PartitionBy,
> 				nil,
> ```

nit:`// allowedNewColumnNames`
___
*[pkg/sql/alter_table_locality.go, line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT8C25E2C0aU3-q2sy5:-MT8C25E2C0aU3-q2sy6:brqmgdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cf160d2fa1855ade1e6d9b1386053ce54382e/pkg/sql/alter_table_locality.go#L204)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 		// and we were actually looking for a column.
> 		if !(sqlerrors.IsUndefinedColumnError(err) && mayNeedImplicitCRDBRegionCol) {
> 			return err
> 		}
> 		createDefaultRegionCol = true
> 	}
> ```
</details>

nits: It's not very obvious from this code that createDefaultRegionCol is only going to be true if `mayNeedImplicitCRDBRegionCol` is true.

How do you feel about:
```
var createDefaultRegionCol bool
var partCol catalog.Column
if mayNeedImplicitCRDBRegionCol {
    partCol, err = n.tableDesc.FindColumnWithName(partColName)
    createDefaultRegionCol = sqlerrors.IsUndefinedColumnError(err)
    if err != nil && !createDefaultRegionCol {
        return err
    }
}
```
___
*[pkg/sql/schema_changer.go, line 1039 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT8Fqx3Bq8ZVxj6NAN4:-MT8Fqx3Bq8ZVxj6NAN5:b-e0z04f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cf160d2fa1855ade1e6d9b1386053ce54382e/pkg/sql/schema_changer.go#L1039)):*
> ```Go
> //
> // It also kicks off GC jobs as needed.
> func (sc *SchemaChanger) done(ctx context.Context) error {
> ```

this function upsets me
___
*[pkg/sql/schema_changer.go, line 1176 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59824#-MT8FFbnDndCr5jbQE6-:-MT8FFbo4F6TOWjnj7g_:bt3l527) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cf160d2fa1855ade1e6d9b1386053ce54382e/pkg/sql/schema_changer.go#L1176)):*
> ```Go
> 					}
> 
> 					opts := make([]applyZoneConfigForMultiRegionTableOption, 0, 2)
> ```

nit: comment the 2? If it's obvious now, it won't be later

**Comment by otan** [comment]
thanks erre1

bors r=ajwerner,arulajmani

**Comment by otan** [comment]
bors r=ajwerner,arulajmani

**Pull request merged**
