### PR TITLE
ui: show aggregated stats for localities w/ gauge

### PR DESCRIPTION
**Pull request by vilterp**
When the cluster viz shows a locality, sum up its disk usage metrics and show them with the gauge.

screen shot 2018-02-01 at 5 53 38 pm

Release note: None

### CODE REVIEW

**Comment by couchand** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bHKhAL6xNKc1CLpOn:-L4bHKhAL6xNKc1CLpOo:b-1tbvgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L47)):*
> ```XML
> 
>     const leavesUnderMe = getLeaves(this.props.locality);
>     const totalCapacity = _.sum(leavesUnderMe.map((nodeStatus) =>
> ```

perhaps `sumBy`?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bHi40nIi5lQWq2Yor:-L4bHi40nIi5lQWq2Yos:b-cibf72) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L48)):*
> ```XML
>     const leavesUnderMe = getLeaves(this.props.locality);
>     const totalCapacity = _.sum(leavesUnderMe.map((nodeStatus) =>
>       nodeStatus.metrics[MetricConstants.capacity],
> ```

i see that it's just cribbed from the node component, but here and there i think we need to use the new `availableCapacity` logic from `nodeGraphs/summaryBar` and `clusterOverview`... probably should extract that so we don't triplicate it

---

*[pkg/ui/src/redux/localities.ts, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bGh3NQlTycVqRe4JK:-L4bGh3O7mrW5AKoZf2U:b5616b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/src/redux/localities.ts#L56)):*
> ```XML
> }
> 
> export function getLeaves(tree: LocalityTree): NodeStatus$Properties[] {
> ```

test please?  also, maybe put this in `utils/localities`?

---

*[pkg/ui/src/redux/localities.ts, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bGlvn_MFvZf_IS4BB:-L4bGlvn_MFvZf_IS4BC:b-3511vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/src/redux/localities.ts#L62)):*
> ```XML
>     _.forEach(curTree.localities, (localityValues) => {
>       _.forEach(localityValues, (localityValue) => {
>         recur(localityValue);
> ```

fwiw this could be point-free

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381)*

**Comment by vilterp** [comment]
Pulled out `usableCapacity` logic into the new `sumNodeStats` function. This turned out to be a pretty big change because (a) other things use it and (b) it takes liveness as a parameter, which I had to plumb through.

However, we need liveness indicators in the clusterviz anyway, so that plumbing is just paving the way for that.

Also, I broke up the `sumNodeStats` refactor into its own commit.

---

Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bHKhAL6xNKc1CLpOn:-L4bd1aTG7Eakyyy3JBH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L47)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

perhaps `sumBy`?
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bHi40nIi5lQWq2Yor:-L4cBOe6xd5Wmpq3jNnQ:b1cvkbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L48)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

i see that it's just cribbed from the node component, but here and there i think we need to use the new `availableCapacity` logic from `nodeGraphs/summaryBar` and `clusterOverview`... probably should extract that so we don't triplicate it
</blockquote></details>

Done. See top-level comment.

---

*[pkg/ui/src/redux/localities.ts, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bGh3NQlTycVqRe4JK:-L4bgmXfF1v6zj8EZwsi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/src/redux/localities.ts#L56)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

test please?  also, maybe put this in `utils/localities`?
</blockquote></details>

Done.

---

*[pkg/ui/src/redux/localities.ts, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4bGlvn_MFvZf_IS4BB:-L4beF9HsdA_eaPJ9ms6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa041fd03e17ddd93c72635ada9ca7ac09eef8a/pkg/ui/src/redux/localities.ts#L62)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

fwiw this could be point-free
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-:-L4cBQfj46Ea0KRwhxWy:b4qpo2c)*

**Comment by couchand** [comment]
Reviewed 1 of 5 files at r2, 2 of 3 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 20 unresolved discussions, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 29 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fn3tvqeHeaqecP0cZ:-L4fn3twZXREW2t6K9D4:b-5t6v21) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L29)):*
> ```XML
> import { cockroach } from "src/js/protos";
> 
> type NodeLivenessStatus = cockroach.storage.NodeLivenessStatus;
> ```

looks like we're already aliasing this in `redux/nodes`, maybe we could just use that rather than importing `js/protos` here?

(also, maybe we should move that next to `util/proto` alongside the `NodeStatus$Properties` alias?)

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fk_TS6HZU_1u5zDnh:-L4fk_TS6HZU_1u5zDni:b-z5503o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L33)):*
> ```XML
> interface LocalityViewProps {
>   localityTree: LocalityTree;
>   liveness: Dictionary<NodeLivenessStatus>;
> ```

what, `{ [id: string]: NodeLivenessStatus }` isn't good enough for you?

I'm inclined to follow the kernel advice on this one: https://www.kernel.org/doc/html/latest/process/coding-style.html#typedefs

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fkj2fvGdLaruyKAEW:-L4fkj2fvGdLaruyKAEX:b-txalqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L44)):*
> ```XML
>   onClick = () => {
>     const destination =
>       CLUSTERVIZ_ROOT + "/" + generateLocalityRoute(this.props.localityTree.tiers);
> ```

Myself, I would do almost anything to make this not have a linebreak.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4foFJk2Twnsmh3cahF:-L4foFJk2Twnsmh3cahG:b-se7o9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L146)):*
> ```XML
>     tree.nodes.forEach((node) => {
>       children.push(
>         <NodeBox node={node} liveness={this.props.liveness} />,
> ```

where did `nodeHistory` go?  I suppose to get the sparkline we'll need to rethink/remove it, but until then we may as well leave it so we can keep the current QPS calculation, right?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx, line 32 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fnZ7YlIeY1fN211aH:-L4fnZ7YlIeY1fN211aI:b-fn8vqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx#L32)):*
> ```XML
> import spinner from "assets/spinner.gif";
> import {cockroach} from "oss/src/js/protos";
> import NodeLivenessStatus = cockroach.storage.NodeLivenessStatus;
> ```

no `oss` plz, and same thought about using the existing alias

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx, line 106 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fnkK3REooKy8-8Zzu:-L4fnkK3REooKy8-8Zzv:bf6gdj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx#L106)):*
> ```XML
>   locationStatus: CachedDataReducerState<any>;
>   liveness: Dictionary<NodeLivenessStatus>;
>   livenessStatus: CachedDataReducerState<any>;
> ```

oh man, did I never get around to fixing those `any` types?  oh well.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx, line 166 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fpBvh-_deXx3fkHhO:-L4fpBvh-_deXx3fkHhP:b-o27gu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx#L166)):*
> ```XML
>     return (
>       <Loading
>         loading={ !this.props.localityStatus.valid || !this.props.locationStatus.valid }
> ```

should probably include liveness status here, too.

maybe it would be worth just moving this conditional into a selector down in the mapStateToProps rather than dealing with the individual statuses?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx, line 27 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fmaneI0zuH04qQjv-:-L4fmaneI0zuH04qQjv0:b30w4ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx#L27)):*
> ```XML
>   render() {
>     const { node, liveness } = this.props;
>     const { capacityUsable, capacityUsed } = sumNodeStats([node], liveness);
> ```

the unfortunate side-effect here is that, when the nodes being shown include a dead one, that one will be listed as having zero values for the stats, rather than the last known values.  probably not the intended behavior.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fpY_EOK21t4IcSPFP:-L4fpY_EOK21t4IcSPFQ:b-gqoztt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx#L33)):*
> ```XML
>         usableCapacity={capacityUsable}
>         usedCapacity={capacityUsed}
>         label={this.props.node.desc.address.address_field}
> ```

can just be `node.desc...` now that it's destructured

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 1 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fpffzhUQRapESFKI9:-L4fpffzhUQRapESFKIA:bha7sy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L1)):*
> ```XML
> // Copyright 2018 The Cockroach Authors.
> ```

leaving lots of comments here even though i know you just pulled it out of `NodeView`.  feel free to send these back my way if you don't feel like doing anything on them

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 29 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fpnoLF_xB9kwyHX3J:-L4fpnoLF_xB9kwyHX3K:b-a5mvp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L29)):*
> ```XML
>   static arcWidth = StatsView.radius * 0.11111;
>   static outerRadius = StatsView.radius + StatsView.arcWidth;
>   static maxRadius = StatsView.outerRadius + StatsView.arcWidth;
> ```

if these aren't used anywhere else (and I can't see why they would be) i'd prefer to make them file-level `const`s instead of class static properties

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 36 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fmIum3RUfenCcbZnP:-L4fmIum3RUfenCcbZnQ:b-6fcqc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L36)):*
> ```XML
>         className="capacity-background"
>         d={PathMath.createArcPath(
>           StatsView.radius, StatsView.outerRadius, PathMath.arcAngleFromPct(0), PathMath.arcAngleFromPct(1),
> ```

i'd calculate this ahead of time

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 49 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fqCXDDw_FjSAcfT0c:-L4fqCXDDw_FjSAcfT0d:b-bjgbz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L49)):*
> ```XML
> 
>     const usedX = Math.cos(PathMath.angleFromPct(capacityUsedPct));
>     const usedY = Math.sin(PathMath.angleFromPct(capacityUsedPct));
> ```

i'd multiply by the radius here rather than down below.

oh, this looks a lot like the circle layout!  we can probably refactor them to use a more general routine in the future.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 55 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fqOi8lgf0_PByeCUz:-L4fqOi8lgf0_PByeCV-:b-e0vk8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L55)):*
> ```XML
>         <text
>           className="capacity-label"
>           x={(StatsView.outerRadius + StatsView.arcWidth) * Math.cos(0)}
> ```

definitely precalculate this constant

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 79 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4frEW-7BBdS01SQPhW:-L4frEW-7BBdS01SQPhX:bn6ejlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L79)):*
> ```XML
>           <svg width={StatsView.outerRadius * 2} height={StatsView.outerRadius * 2}>
>             <text className="capacity-used-pct-label" x="50%" y="40%">
>               {Math.round(100 * capacityUsedPct) + "%"}
> ```

i did a brief survey of our app and we already have three different percentage formatter routines:

`util/format`: `Math.floor(n/d * 100).toString() + "%"`
`clusterOverview`: `d3.format("0.1%")`
`nodeGraphs/summaryBar`: `d3.format(".2%")`

just noting that fact.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 92 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fsS1aNHb2R_5Ju-wT:-L4fsS1aNHb2R_5Ju-wU:b6uogt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L92)):*
> ```XML
>   renderNetworkActivity() {
>     const barsX = StatsView.radius * Math.cos(PathMath.angleFromPct(0));
>     const barsWidth = StatsView.outerRadius - barsX - 4;
> ```

we can probably precalculate all this magic?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 98 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fsYK_MUn_EgDkGLFa:-L4fsYK_MUn_EgDkGLFb:bbj46dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L98)):*
> ```XML
> 
>     return (
>       <g transform={`translate(0,${StatsView.radius * Math.sin(PathMath.angleFromPct(0))})`} >
> ```

precalculate! also, move the `outerRadius` and `labelH` into here so we don't have to repeat them on the `line`

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 103 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fsh8B6L3QL-vL2WUY:-L4fsh8B6L3QL-vL2WUZ:b-1qxjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L103)):*
> ```XML
>           x1={StatsView.outerRadius - 2}
>           y1={-labelH}
>           x2={Math.round(StatsView.outerRadius - barsWidth * nodeHistory.clientActivityRate / maxClientActivityRate)}
> ```

this is just begging for a `d3.scaleLinear`

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx, line 132 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4ftIly-eOLUH1_kuGc:-L4ftIly-eOLUH1_kuGd:bbix3yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/statsView.tsx#L132)):*
> ```XML
>     return (
>       <g className="locality">
>         <g className="capacity-centric">
> ```

that's an odd class name

---

*[pkg/ui/src/util/localities.spec.ts, line 7 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4flcrHnNyqi9eNmZy1:-L4flcrIgbxm04hXv7L2:bfr9i7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/src/util/localities.spec.ts#L7)):*
> ```XML
> import {
>   generateLocalityRoute, parseLocalityRoute, getNodeLocalityTiers, getLocality,
>   getLeaves,
> ```

personally prefer all on one line or each on their own line, not a mix (also fwiw this will be a merge conflict)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381)*

**Comment by a-robinson** [comment]
The capacity calculations/comments/plumbing :lgtm: I didn't review any of the other logic.

---

Reviewed 5 of 5 files at r2, 3 of 3 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 20 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-:-L4g0umG8hamZjMsNVn7:b-gs5m13)*

**Comment by vilterp** [comment]
TFTR @a-robinson

**Comment by vilterp** [comment]
@couchand `StatsView` is substantially rewritten in https://github.com/vilterp/cockroach/pull/1, so I'm not going to address those comments yet.

---

Review status: 1 of 10 files reviewed at latest revision, 20 unresolved discussions.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 29 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fn3tvqeHeaqecP0cZ:-L4gX6rI05Kq8M3kIh5M:b-nmckqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L29)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

looks like we're already aliasing this in `redux/nodes`, maybe we could just use that rather than importing `js/protos` here?

(also, maybe we should move that next to `util/proto` alongside the `NodeStatus$Properties` alias?)
</blockquote></details>

Done.

Yeah idk what my opinion is about these aliases overall…

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fk_TS6HZU_1u5zDnh:-L4gV40SnvtpIl7ZVjFK:b-s7g9bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L33)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

what, `{ [id: string]: NodeLivenessStatus }` isn't good enough for you?

I'm inclined to follow the kernel advice on this one: https://www.kernel.org/doc/html/latest/process/coding-style.html#typedefs
</blockquote></details>

Done. Agreed — was fighting with the typechecker at the time and thought it had to be a dictionary to pass; the problem was actually LivenessStatus vs NodeLivenessStatus or something.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fkj2fvGdLaruyKAEW:-L4gX_kXjpzD8toV3t4U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L44)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Myself, I would do almost anything to make this not have a linebreak.
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4foFJk2Twnsmh3cahF:-L4gd0WDpD32TuGCrAvk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/modalLocalities.tsx#L146)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

where did `nodeHistory` go?  I suppose to get the sparkline we'll need to rethink/remove it, but until then we may as well leave it so we can keep the current QPS calculation, right?
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx, line 32 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fnZ7YlIeY1fN211aH:-L4gYNT-3VggG4OjYs_6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx#L32)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

no `oss` plz, and same thought about using the existing alias
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx, line 166 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fpBvh-_deXx3fkHhO:-L4gafVWM_iZTRbPxGZt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeSimulator.tsx#L166)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

should probably include liveness status here, too.

maybe it would be worth just moving this conditional into a selector down in the mapStateToProps rather than dealing with the individual statuses?
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4fpY_EOK21t4IcSPFP:-L4gbszl19JkwSXcX9a5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx#L33)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

can just be `node.desc...` now that it's destructured
</blockquote></details>

Done.

---

*[pkg/ui/src/util/localities.spec.ts, line 7 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-L4flcrHnNyqi9eNmZy1:-L4gbSIKJ7gzabTwwG7d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99a7ee83dcfc4e2202a2a22b1d3c771445a4b15/pkg/ui/src/util/localities.spec.ts#L7)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

personally prefer all on one line or each on their own line, not a mix (also fwiw this will be a merge conflict)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381#-:-L4gdnuC8Hv5PJlYWQdw:b-1s5jak)*

**Comment by couchand** [comment]
Reviewed 2 of 5 files at r2, 2 of 3 files at r6, 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22381)*

**Comment by couchand** [comment]
:lgtm:

**Pull request merged**
