### PR TITLE
cli: add cpu benchmark to cockroach

### PR DESCRIPTION
**Pull request by m-schneider**
Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
https://github.com/petermattis/pebble/blob/master/cmd/pebble/test.go is the benchmarking framework I mentioned in person today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-:-LSHk_si6SsfnslROpVL:bo21y55)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
The benchmark itself looks fine. My major comment is that I think you should copy over the framework from pebble that I mentioned in my previous comment. That should massively reduce the duplication here. That framework was inspired by some of the structure in `workload` which was inspired by various `loadgen` tools. Some day this might become something reusable, but not yet .

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-:-LSKsublEDruQoomOHjG:b-gzola8)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/cpu_bench.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSKsp0jDIQ3Rh-mhckg:-LSKsp0kBJtDhdGbGf8E:b-5g4sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L91)):*
> ```Go
> // If any number gives a remainder of 0, the next number is calculated.
> func newWorkerCPUPrimes(ctx context.Context, cpuOptions *CPUOptions) worker {
> ```

Nit: spurious blank line.

**Comment by m-schneider** [comment]
Will do!

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/cpu_bench.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSL2I9_2a78G_tUtDTs:-LSL2I9aANIEm5PoWZ8t:b9uprfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L59)):*
> ```Go
> 	for {
> 		limit := math.Sqrt(float64(dividend))
> 		divisor := 1
> ```

Is this doing enough work per iteration to give a good signal? Seems like each iteration will be dominated by the costs of the clock accesses, the locking, and the histogram operations.

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/cpu_bench.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSL2I9_2a78G_tUtDTs:-LSLJ3X62D_XtcoG2tfz:bmzlls) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L59)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I was thinking about that too, so I ran some tests on it yesterday to get some confidence in the benchmark and it did look like faster CPUs could do more ops/second. This is also a copy of sysbench logic, so I wouldn't want to change the core logic. We could update the histogram less frequently maybe?
</blockquote></details>

Faster CPUs will cause all of this to be faster, so that's not super surprising. My bigger concern is that a change to any of this will make results incomparable. What if Go changes their semaphore implementation? What if we change the histogram? I think we should isolate exactly what is being measured (a fixed number of divisions?) and make that explicit.

**Comment by m-schneider** [comment]
___
*[pkg/cli/systembench/cpu_bench.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSL2I9_2a78G_tUtDTs:-LSLMCjU2JDd_GZHfUXk:b416zuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Faster CPUs will cause all of this to be faster, so that's not super surprising. My bigger concern is that a change to any of this will make results incomparable. What if Go changes their semaphore implementation? What if we change the histogram? I think we should isolate exactly what is being measured (a fixed number of divisions?) and make that explicit.
</blockquote></details>

I mean the other question is if we really need a histogram for this test?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/cpu_bench.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSL2I9_2a78G_tUtDTs:-LSQ7Q7x5e2l5U3TrsR5:boknp2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L59)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I mean the other question is if we really need a histogram for this test?
</blockquote></details>

No, we probably don't need a histogram. If the overhead of the recording is too high, you could perform several iterations per record. Something like:

```
start := timeutil.Now()
// Find the next 10 primes, starting at dividend.
for i := 0; i < 10; i++ {
  limit := math.Sqrt(float64(dividend))
  divisor := 1
  for float64(divisor) <= limit {
    if dividend % divisor == 0 {
      dividend++
      break
    }
    divisor++
  }
}
elapsed := timeutil.Since(start)
atomic.AddInt64(&count, 10)
```

**Comment by m-schneider** [comment]
___
*[pkg/cli/systembench/cpu_bench.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSL2I9_2a78G_tUtDTs:-LSQBC__BZrExcvEgWx8:b-h2i2yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

No, we probably don't need a histogram. If the overhead of the recording is too high, you could perform several iterations per record. Something like:

```
start := timeutil.Now()
// Find the next 10 primes, starting at dividend.
for i := 0; i < 10; i++ {
  limit := math.Sqrt(float64(dividend))
  divisor := 1
  for float64(divisor) <= limit {
    if dividend % divisor == 0 {
      dividend++
      break
    }
    divisor++
  }
}
elapsed := timeutil.Since(start)
atomic.AddInt64(&count, 10)
```
</blockquote></details>

Ok I'll play around with the pprof endpoints to optimize.

**Review by m-schneider — COMMENTED** [review]
I updated with histogram from pebble.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-:-LSqAk6n9ZmfzVoMjJQK:b-jobtvl)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/cpu_bench.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSL2I9_2a78G_tUtDTs:-LSqApHdAXtyvNZTu5uf:b-blbiyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L59)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Ok I'll play around with the pprof endpoints to optimize.
</blockquote></details>

I did a bunch of testing on this code to try to figure out if the overhead of recording is too high to come up with a batch size. Looking at pprof didn't really help much, so I ran the test for an hour slowly incrementing the batch size to see where the ops/second stopped increasing. Then I ran the same with increased concurrency and then on a GCE worker. The ops/second leveled off at about a batch size of 500, but I added a bit more just in case. Ops/second didn't increase after 500 even with batch size in the millions with any machine configuration.
___
*[pkg/cli/systembench/cpu_bench.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSKsp0jDIQ3Rh-mhckg:-LSqAZGu0f6_BnUzRr76:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5dd154f1e3c7aabafc9d374c0feed525827ace/pkg/cli/systembench/cpu_bench.go#L91)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: spurious blank line.
</blockquote></details>

Done!

**Review by petermattis — COMMENTED** [review]
> I updated with histogram from pebble.

There is also `runTest` which I think applies here too as you can put the boilerplate code in that function. The boilerplate I'm thinking about is the tick loop, setting up the signal handler and the timeout goroutine, etc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-:-LStVpKSEyL1Q35CjOvs:bst66ur)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/cpu_bench.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LStV_nq3sLJIQLSnAsS:-LStV_nq3sLJIQLSnAsT:b-kwonix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d282716921677b8c5e65b129079f6de351310a3/pkg/cli/systembench/cpu_bench.go#L58)):*
> ```Go
> 	// This is to make sure we're measuring the divisions
> 	// vs the performance of locking.
> 	batchSize := 700
> ```

Nit: `const batchSize = 700`, though I would probably do `const batchSize = 1000` because `700` is such an odd constant.

**Review by m-schneider — COMMENTED** [review]
Yes that makes sense, I added a similar loop but with an error group.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-:-LSue2sM0dtnKcmT1yne:bc3115w)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/cpu_bench.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LStV_nq3sLJIQLSnAsS:-LSue9YP-f9_wHK6eU4_:b-tlidih) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d282716921677b8c5e65b129079f6de351310a3/pkg/cli/systembench/cpu_bench.go#L58)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `const batchSize = 700`, though I would probably do `const batchSize = 1000` because `700` is such an odd constant.
</blockquote></details>

Yeah it is.

**Review by petermattis — APPROVED** [review]
:lgtm: modulo a small question in `runTests`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-:-LSv6nOj4-gz6KUwb7PO:b9t6uo)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cli/systembench/tests.go, line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSv6gZD8txA7eOYXUrl:-LSv6gZE3jz19fFsz525:b-jy1t2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d194031f380d25e31b39f324ef45c101478f734f/pkg/cli/systembench/tests.go#L188)):*
> ```Go
> 	defer ticker.Stop()
> 
> 	errs := make(chan error, 1)
> ```

What is this used for? You don't seem to be reading from this channel anywhere.

**Comment by m-schneider** [comment]
___
*[pkg/cli/systembench/tests.go, line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32620#-LSv6gZD8txA7eOYXUrl:-LSv8eltA5cMkxw1u0_7:bd2m5x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d194031f380d25e31b39f324ef45c101478f734f/pkg/cli/systembench/tests.go#L188)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What is this used for? You don't seem to be reading from this channel anywhere.
</blockquote></details>

Added the reader.

**Pull request merged**
