### PR TITLE
kvserver: return destination from AdminScatter

### PR DESCRIPTION
**Pull request by pbardea**
This commit updates the AdminScatter request to return the node of the
leaseholder after the scattering for each range that is scattered in the
request.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @dt, and @pbardea)

___
*[pkg/roachpb/api.proto, line 1549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCmriWtE_WLS7UgDv_Y:-MCmriWtE_WLS7UgDv_Z:b-9712ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/19c0ecc9d173e027bf411ac61f68badf1b102fc4/pkg/roachpb/api.proto#L1549)):*
> ```protobuf
>     reserved 2;
>     // DestinationNodeID is the range's leaseholder after the scattering.
>     int32 destination_node_id = 3 [
> ```

call this `leaseholder`.

But let's do this for real. Let's deprecate this `message Range`, and return a `repeated RangeInfo` - which is a descriptor and a lease. `r.adminScatter` can use `r.GetDescAndLease()` to get a consistent view of both a descriptor and a lease.

**Review by pbardea — COMMENTED** [review]
Thank you for taking a look, this is RFAL.

I've gone ahead and deprecated `AdminScatter`'s `Range`.

`scatter.go` now constructs `AdminScatterResponse_DeprecatedRange` based on the RangeInfos if available with a TODO to rework that section to use `RangeInfos` in 21.1.
I considered requesting the RangeInfos on the batch response header directly (à la RangeStatsResponse) and ripping out `DeprecatedRange` from `scatter.go` all together. In the end I opted for this approach since using `ReturnRangeInfos` isn't a desirable pattern either, and we'd need to keep `DeprecatedRange` around anyway for backwards compatibility.

Please let me know if you prefer that approach over this one though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-:-MCseTo35hgH-P0y5oar:b-b2j9vp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[pkg/roachpb/api.proto, line 1549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCmriWtE_WLS7UgDv_Y:-MCrzUkA9oM3EAiTZMCc:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/19c0ecc9d173e027bf411ac61f68badf1b102fc4/pkg/roachpb/api.proto#L1549)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

call this `leaseholder`.

But let's do this for real. Let's deprecate this `message Range`, and return a `repeated RangeInfo` - which is a descriptor and a lease. `r.adminScatter` can use `r.GetDescAndLease()` to get a consistent view of both a descriptor and a lease.

</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
This patch doesn't actually use the returned leases, does it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-:-MCw9zqJCqBHUoUFOmqF:bak4ru9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @dt, and @pbardea)

___
*[pkg/roachpb/api.proto, line 1546 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw7Fhb29gEK7LXQLzO:-MCw7Fhb29gEK7LXQLzP:b-arvvu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/roachpb/api.proto#L1546)):*
> ```protobuf
> 
> 
>   message DeprecatedRange {
> ```

it's weird to "deprecate" a struct. I'd leave the message called `Range` and just rename the field to `deprecated_ranges`.
___
*[pkg/sql/scatter.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw8dfUE9nFMWQ5zuG1:-MCw8dfUE9nFMWQ5zuG2:bdrgw48) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L125)):*
> ```Go
> 
> 	rangeIdx int
> 	ranges   []roachpb.AdminScatterResponse_DeprecatedRange
> ```

make this `roachpb.Span`
___
*[pkg/sql/scatter.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw9UPn--TeDKJII87y:-MCw9UPn--TeDKJII87z:b-uzl50y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L140)):*
> ```Go
> 	scatterRes := res.(*roachpb.AdminScatterResponse)
> 	n.run.rangeIdx = -1
> 	if scatterRes.RangeInfos != nil {
> ```

I'm not sure if this nil check works or if the proto decoder will always allocate a 0-len slice.
___
*[pkg/sql/scatter.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw7d_PA1BWBwG1bk1z:-MCw7d_PA1BWBwG1bk2-:b-u8u1ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L142)):*
> ```Go
> 	if scatterRes.RangeInfos != nil {
> 		// TODO(pbardea): In 21.1, remove all references to DeprecatedRange.
> 		// RangeInfos should also not be nullable then.
> ```

I see that you've already made `RangeInfos` not nullable - in the sense that there's no `*[]Range` - so this comment is confusing. I'd remove this TODO; the compatibility note below is enough.
___
*[pkg/sql/scatter.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCwBc8l5w5Ft1npM9x_:-MCwBc8l5w5Ft1npM9xa:b-pz1l9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L152)):*
> ```Go
> 			}
> 		}
> 	} else {
> ```

is this correct? Given how we combine responses, you can get a response with both `RangeInfos` and `DeprecatedRanges`.  I think `DeprecatedRanges` will always be a superset of `RangeInfos`. So I think you want to dedupe and use both.  Or, given that you're not using the lease, just use `DeprecatedRanges`. Or, better yet, make the `combine()` always populate `RangeInfos` (use empty leases for the info coming from `DeprecatedRanges`) and wipe `DeprecatedRanges` such that above the DistSender one either gets only `RangeInfos` (when responses were combined or non-combined response from 21.1) or only `DeprecatedRanges` (non-combined response coming from 20.1) or both as exact duplicates (non-combined response coming from 20.2).

We can also investigate adding a compatibility response translator in the `DistSender` itself if you feel like it.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[pkg/roachpb/api.proto, line 1546 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw7Fhb29gEK7LXQLzO:-MCwHgvp-dIpAa13fNqE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/roachpb/api.proto#L1546)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's weird to "deprecate" a struct. I'd leave the message called `Range` and just rename the field to `deprecated_ranges`.
</blockquote></details>

Done.
___
*[pkg/sql/scatter.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw8dfUE9nFMWQ5zuG1:-MCwHjbw1UwkhZ3TR3al:b-7fvrbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L125)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

make this `roachpb.Span`
</blockquote></details>

Done. That's much nicer - thanks.
___
*[pkg/sql/scatter.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw9UPn--TeDKJII87y:-MDFZ2jI1M8y9ldJmkVp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L140)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not sure if this nil check works or if the proto decoder will always allocate a 0-len slice.
</blockquote></details>

Done.
___
*[pkg/sql/scatter.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCw7d_PA1BWBwG1bk1z:-MCwHpXtCkaO2DnyJElK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L142)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see that you've already made `RangeInfos` not nullable - in the sense that there's no `*[]Range` - so this comment is confusing. I'd remove this TODO; the compatibility note below is enough.
</blockquote></details>

Done.
___
*[pkg/sql/scatter.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCwBc8l5w5Ft1npM9x_:-MDFZ3Ix8vcOAqhAXD5r:b3oazcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L152)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this correct? Given how we combine responses, you can get a response with both `RangeInfos` and `DeprecatedRanges`.  I think `DeprecatedRanges` will always be a superset of `RangeInfos`. So I think you want to dedupe and use both.  Or, given that you're not using the lease, just use `DeprecatedRanges`. Or, better yet, make the `combine()` always populate `RangeInfos` (use empty leases for the info coming from `DeprecatedRanges`) and wipe `DeprecatedRanges` such that above the DistSender one either gets only `RangeInfos` (when responses were combined or non-combined response from 21.1) or only `DeprecatedRanges` (non-combined response coming from 20.1) or both as exact duplicates (non-combined response coming from 20.2).

We can also investigate adding a compatibility response translator in the `DistSender` itself if you feel like it.
</blockquote></details>

I've updated `combine` to always populate `RangeInfos` if it's empty. My original concern was that the range descriptor's range ID would not be set since the `DeprecatedRanges` only contain span info. Is that an issue?

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-:-MDQI7SL5clFVMfNw7Sw:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @dt, and @pbardea)

___
*[pkg/sql/scatter.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51607#-MCwBc8l5w5Ft1npM9x_:-MDQHtyJ6EQlqBnery1V:bkbtlf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98d4d7f22c35f962232ac61e670932f282e905d/pkg/sql/scatter.go#L152)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I've updated `combine` to always populate `RangeInfos` if it's empty. My original concern was that the range descriptor's range ID would not be set since the `DeprecatedRanges` only contain span info. Is that an issue?
</blockquote></details>

well, hopefully nobody else will use `RangeInfos` until 20.2 is out

**Comment by pbardea** [comment]
TFTR!
bors r+

**Pull request merged**
