### PR TITLE
sql: preserve (and generate as needed) FK contraint names

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7627)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 402 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-KLwdegQp-7DXRkr2hzT:-KLwdegQp-7DXRkr2hzU:211229627) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd19eca36e4a621741c977710f61ed10cf8b685e/sql/create.go#L402)):*
> ```Go
> 
> 	if constraintName == "" {
> 		constraintName = parser.Name(fmt.Sprintf("%s_ref_%s_%s", fromCol, target.Name, targetColName))
> ```

our other autogenerated names have a prefix of the type ("idx" and "fam")

---

*[sql/create.go, line 402 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-KLweVNKGOagrGdpb3jf:-KLweVNKGOagrGdpb3jg:97133567) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd19eca36e4a621741c977710f61ed10cf8b685e/sql/create.go#L402)):*
> ```Go
> 
> 	if constraintName == "" {
> 		constraintName = parser.Name(fmt.Sprintf("%s_ref_%s_%s", fromCol, target.Name, targetColName))
> ```

check that these are unique in `(tableDesc).Validate`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627)*

**Comment by dt** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 402 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-KLwdegQp-7DXRkr2hzT:-KLwiHH7Dl2gHijs65-P:-1761031166) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd19eca36e4a621741c977710f61ed10cf8b685e/sql/create.go#L402)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> our other autogenerated names have a prefix of the type ("idx" and "fam")
</details>
I started with `ref_` as the prefix but changed it to this to read more naturally (/as an infix operator)

---

*[sql/create.go, line 402 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-KLweVNKGOagrGdpb3jf:-KLwiUbi5ABLYyjFPNTD:-1294431995) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd19eca36e4a621741c977710f61ed10cf8b685e/sql/create.go#L402)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> check that these are unique in `(tableDesc).Validate`
</details>
heh, funny you should mention that -- already tracked on #7537 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627)*

**Comment by paperstreet** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 402 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-KLwdegQp-7DXRkr2hzT:-KM0SAHb5d0wZlhSqTBW:948856708) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd19eca36e4a621741c977710f61ed10cf8b685e/sql/create.go#L402)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I started with `ref_` as the prefix but changed it to this to read more naturally (/as an infix operator)
</details>
Sure. I still don't like the inconsistency. Maybe some third option? fk_foo_ref_bar_baz?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627)*

**Comment by dt** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 402 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-KLwdegQp-7DXRkr2hzT:-KM0pbY7om4k2YaPnIY5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd19eca36e4a621741c977710f61ed10cf8b685e/sql/create.go#L402)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Sure. I still don't like the inconsistency. Maybe some third option? fk_foo_ref_bar_baz?
</details>
Done.

---

*[sql/create.go, line 402 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-KLweVNKGOagrGdpb3jf:-KM5G0-pdYFcHKRqhfLn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd19eca36e4a621741c977710f61ed10cf8b685e/sql/create.go#L402)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> heh, funny you should mention that -- already tracked on #7537 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7627#-:-KM5GitpOzvD265WZLqZ:1417088721)*

**Pull request merged**
