### PR TITLE
cli: introduce a retryable txn wrapper for rm/set zone commands

### LINKED ISSUE #8775: cli: transaction restart leaked to `cockroach zone set`
```
./cockroach zone set .default -f -
Error: pq: restart transaction: retry txn "sql/executor.go:492 sql txn" id=16fc5c56 key=/Table/5/1/0/2/1 rw=false pri=0.02391739 iso=SERIALIZABLE stat=PENDING epo=1 ts=1471974703.647907362,1 orig=1471974703.647907362,1 max=1471974698.272573117,0 wto=false rop=false
Failed running "zone"
```

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #8775

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/sql_util.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14963#-Khn_HLirydY1bC8qfCr:-Khn_HLjyjv6DT_Mtt5a:b-o5qyfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc527e44253dfa340aea6837777ba1db0de3b04/pkg/cli/sql_util.go#L114)):*
> ```Go
> 		}
> 	}
> }
> ```

Was this cribbed from `github.com/cockroachdb/cockroach-go/crdb`? Lot of new code not to be tested, which means I don't trust it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14963)*

**Comment by spencerkimball** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/sql_util.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14963#-Khn_HLirydY1bC8qfCr:-KhnaJ7_AkP0m5WMvhdQ:b75fc9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc527e44253dfa340aea6837777ba1db0de3b04/pkg/cli/sql_util.go#L114)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Was this cribbed from `github.com/cockroachdb/cockroach-go/crdb`? Lot of new code not to be tested, which means I don't trust it.
</blockquote></details>

It was moved over pretty directly, minus the ambiguous result stuff. Unfortunately this cli code uses raw driver connections instead of `sql.DB` objects, so I couldn't just use crdb directly. Do you understand the reason why that's being done here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14963)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/sql_util.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14963#-Khn_HLirydY1bC8qfCr:-Kho4PUl3dLNGYHgDmMp:b-rz2wty) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc527e44253dfa340aea6837777ba1db0de3b04/pkg/cli/sql_util.go#L114)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

It was moved over pretty directly, minus the ambiguous result stuff. Unfortunately this cli code uses raw driver connections instead of `sql.DB` objects, so I couldn't just use crdb directly. Do you understand the reason why that's being done here?
</blockquote></details>

`database/sql` didn't provide support for multiple results so we needed to use the `lib/pq` connection directly. This may no longer be true. Add a comment indicating that this code was copied from `cockroach-go/crdb` and file an issue that we should investigate whether we can move back to using the standard `database/sql` interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14963#-:-Kho4oDb6ZOP9kYI0_vd:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14963#-:-KhrGCTkXlwiz7r3nru8:bnfp4nl)*

**Pull request merged**
