### PR TITLE
sqlstats: modify usage of `sql.stats.flush.latency` metric

### PR DESCRIPTION
**Pull request by abarganier**
The `sql.stats.flush.latency` metric previously measured the latency of the time spent flushing a single stmt or txn statistic, instead of the entire batch.

As we look to stabilize & optimize SQL stats, this metric is not very useful. Instead, what we want to measure is the latency of the *entire batch* of stats being flushed to disk.

This patch updates the metric to measure this instead.

Release note: none

Epic: none

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: let's backport this to 24.1

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122919#-:-NwMEbrVBLjesdwWSgMO:b8jcu1k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nkodali and @xinhaoz)

**Comment by abarganier** [comment]
TFTR!

bors r=dhartunian

**Comment by abarganier** [comment]
Thought I spotted a bug, but I was wrong. Nevermind, bors! 

bors r=dhartunian

**Pull request merged**
