### PR TITLE
sql: fix merge skew from NamedArgTypes rename

### PR DESCRIPTION
**Pull request by jordanlewis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13152)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

3 skews against the same change? solid.

**Comment by dt** [comment]
LGTM.
@tamird where's the third? the change itself hit a skew and then there's this one

**Comment by tamird** [comment]
I was going by @jordanlewis' self-reported "3".

**Comment by jordanlewis** [comment]
That would be @dt's comment, wouldn't it? I said no such thing!

**Pull request merged**
