### PR TITLE
all: allow go1.7rc4

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8229)

### CODE REVIEW

**Comment by tamird** [comment]
May as well replace rc3? LGTM

**Comment by tschottdorf** [comment]
Don't want to force the `rc3` folks to update (I would personally be happy just using `go1.7rc`).

**Comment by tamird** [comment]
You may as well make it go1.7 =/

On Tue, Aug 2, 2016 at 11:12 AM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
Also fine with me, though that would allow `1.7.1` automatically as well once it comes out. There must have been some reason for not making these more general since it's such a hassle to update, so I don't want to just change it. I'll merge since it's green.

**Pull request merged**
