### PR TITLE
build: generate .pb.go files in the bazel sandbox

### LINKED ISSUE #56067: build: Generate all the protobuf files with Bazel

### PR DESCRIPTION
**Pull request by rickystewart**
We used to use the checked-in `.pb.go` files in our Bazel build, but
these files should really be generated during the build (this is normal
Bazel style, and avoids the weird extra step of having to run
`make generate` and check in the `.pb.go` files whenever a `.proto` is
updated). Some specific implementation notes:

* Add a couple `go_proto_compiler`s for the `protoc-gen-gogoroach`
  plugin.

* We enable Gazelle handling of `.proto` files in `BUILD.bazel`.

* In that file, we also add a bunch of `gazelle:resolve` and
  `gazelle:exclude` directives that fix some build issues. The
  `vendor` directory is especially problematic and likely to
  introduce circular dependencies, so those get special attention.

* Add a couple ad-hoc manual fixes to make compilation work (they can
  generally be found by searching for lines in `BUILD.bazel` files that
  are marked `keep`). These are typically necessary because Gazelle
  couldn't resolve the dependencies correctly for whatever reason.

It's unclear to me at this point how well Gazelle will do as a
long-term automatic solution for our protos. We may decide that
additional investment is required to make everything usable without a
prohibitive amount of manual intervention; that requires further
investigation. Vendoring is definitely the most problematic thing from
this perspective.

Fixes #56067.

Release note: None

### CODE REVIEW

**Review by irfansharif — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[WORKSPACE, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOimSRNA0016zAUNdpz:-MOimSRNA0016zAUNdq-:b-3y8r90) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/WORKSPACE#L44)):*
> ```Starlark
> #      https://github.com/bazelbuild/bazel-gazelle/issues/591
> #
> # TODO(irfansharif): We're not yet using this. We'll eventually need to when we
> ```

We can remove this TODO now. If I've read correctly (https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#proto-dependencies) we still need to load to protobuf dependency we're doing here. Aside: seems like I added a typo up above with "depedency".
___
*[WORKSPACE, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOimpkL64ccS0bIa16O:-MOimpkL64ccS0bIa16P:bil3mhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/WORKSPACE#L85)):*
> ```Starlark
> 
> 
> # Extra dependencies for Go proto compilation.
> ```

Mind referencing https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#grpc-dependencies here? Looking at that reference, it suggests that we'd need to include `build_file_proto_mode = "disable"`, but looks like we didn't have to? It also suggests other dependencies we'd need "at minimum", which we seem to have done without? Do you know what's up with these? 

Were these dependencies already loaded through DEPS.bzl? Hmm, looks like they were, and we're overriding one of them here. Do we want that to happen? Or can we elide those entirely? Seeing as how those dependencies are generated from go.mod, I suspect this version here could fall out sync unexpectedly.
___
*[pkg/build/util.bzl, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOiuCtVCb1H_f_gbQnB:-MOiuCtVCb1H_f_gbQnC:bfoss64) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/pkg/build/util.bzl#L4)):*
> ```Starlark
> load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
> 
> def proto_lib(**kwargs):
> ```

I'm a bit sad that we're having to write custom wrappers to generate pb.go files within the bazel sandbox. I was hoping there'd be a way to auto-generate the right rules through gazelle, like suggested in https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#option-1-use-go_proto_library-exclusively. Looking at what was needed to build schedule.pb.go within the sandbox, we had to construct by hand the right (albeit simple) `proto_lib` invocation. So every time someone introduces a .proto file/service, they'd have to do it by hand. Perhaps that's fine, we don't introduce too many of these and don't do it all that often, + it's simple enough to figure out, but because it's not automagically generated somehow through `bazel run //:gazelle`, crdb engineers would have to touch these files by hand. Again, perhaps that's fine, but I'm a bit surprised we couldn't get gazelle to automatically do the right thing. 

PS: you might've already seen this, but we've asked gazelle to not do this yet here: https://github.com/cockroachdb/cockroach/blob/e69fd0d9b76b02f64a60db95f324f8a61a1aaf50/BUILD.bazel#L16-L18.

So I guess my question is: is it not possible to teach gazelle to generate the right `{go_,}proto_library` invocations, including the right set of dependencies and pointing to our custom protoc-gen-gogoroach compiler? If not, let's also update the comment near the reference above to say that we generate the protobuf rules by hand because of X, Y, Z reasons.
___
*[pkg/cmd/protoc-gen-gogoroach/BUILD.bazel, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOio0ye-r855Byy7Y5x:-MOio0ye-r855Byy7Y5y:b-7rxrki) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/pkg/cmd/protoc-gen-gogoroach/BUILD.bazel#L22)):*
> ```Starlark
> )
> 
> go_proto_compiler(
> ```

Mind referencing https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#go_proto_compiler here? And possibly pointing to our usage of it it `go_proto_lib`? This stuff might be obvious to more experienced bazel folks, and probably us in a few years, but until then I think these pointers would help (me) go a long way.
___
*[pkg/cmd/protoc-gen-gogoroach/BUILD.bazel, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOimHiY0B8tEktZPVss:-MOimHiY0B8tEktZPVst:bmjw386) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/pkg/cmd/protoc-gen-gogoroach/BUILD.bazel#L26)):*
> ```Starlark
>     options = [
>         "plugins=grpc",
>         "Mgoogle/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api",
> ```

Mind teaching me how you worked out these options? Were these grafted from elsewhere? Ditto for the deps below. What's up with the "M" prefix?

**Review by rickystewart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @miretskiy)

___
*[WORKSPACE, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOimSRNA0016zAUNdpz:-MP5X9yvATlbBAcmq0V9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/WORKSPACE#L44)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We can remove this TODO now. If I've read correctly (https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#proto-dependencies) we still need to load to protobuf dependency we're doing here. Aside: seems like I added a typo up above with "depedency".
</blockquote></details>

Done.
___
*[WORKSPACE, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOimpkL64ccS0bIa16O:-MP5XBVc4pvq_8AP5Bm4:b-ujojlj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/WORKSPACE#L85)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Mind referencing https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#grpc-dependencies here? Looking at that reference, it suggests that we'd need to include `build_file_proto_mode = "disable"`, but looks like we didn't have to? It also suggests other dependencies we'd need "at minimum", which we seem to have done without? Do you know what's up with these? 

Were these dependencies already loaded through DEPS.bzl? Hmm, looks like they were, and we're overriding one of them here. Do we want that to happen? Or can we elide those entirely? Seeing as how those dependencies are generated from go.mod, I suspect this version here could fall out sync unexpectedly.
</blockquote></details>

Not necessary any more (removed in the latest version of the commit).
___
*[pkg/build/util.bzl, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOiuCtVCb1H_f_gbQnB:-MP5XGea4b95_ubedMXW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/pkg/build/util.bzl#L4)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm a bit sad that we're having to write custom wrappers to generate pb.go files within the bazel sandbox. I was hoping there'd be a way to auto-generate the right rules through gazelle, like suggested in https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#option-1-use-go_proto_library-exclusively. Looking at what was needed to build schedule.pb.go within the sandbox, we had to construct by hand the right (albeit simple) `proto_lib` invocation. So every time someone introduces a .proto file/service, they'd have to do it by hand. Perhaps that's fine, we don't introduce too many of these and don't do it all that often, + it's simple enough to figure out, but because it's not automagically generated somehow through `bazel run //:gazelle`, crdb engineers would have to touch these files by hand. Again, perhaps that's fine, but I'm a bit surprised we couldn't get gazelle to automatically do the right thing. 

PS: you might've already seen this, but we've asked gazelle to not do this yet here: https://github.com/cockroachdb/cockroach/blob/e69fd0d9b76b02f64a60db95f324f8a61a1aaf50/BUILD.bazel#L16-L18.

So I guess my question is: is it not possible to teach gazelle to generate the right `{go_,}proto_library` invocations, including the right set of dependencies and pointing to our custom protoc-gen-gogoroach compiler? If not, let's also update the comment near the reference above to say that we generate the protobuf rules by hand because of X, Y, Z reasons.
</blockquote></details>

Done.
___
*[pkg/cmd/protoc-gen-gogoroach/BUILD.bazel, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOio0ye-r855Byy7Y5x:-MP5Xt034QHnOlVmRxqv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/pkg/cmd/protoc-gen-gogoroach/BUILD.bazel#L22)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Mind referencing https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#go_proto_compiler here? And possibly pointing to our usage of it it `go_proto_lib`? This stuff might be obvious to more experienced bazel folks, and probably us in a few years, but until then I think these pointers would help (me) go a long way.
</blockquote></details>

Done.
___
*[pkg/cmd/protoc-gen-gogoroach/BUILD.bazel, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57974#-MOimHiY0B8tEktZPVss:-MP5XtKwBP9JKj8TNcb8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba509812aa359207cd4b590bf4d155207a09e62/pkg/cmd/protoc-gen-gogoroach/BUILD.bazel#L26)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Mind teaching me how you worked out these options? Were these grafted from elsewhere? Ditto for the deps below. What's up with the "M" prefix?
</blockquote></details>

Done.

**Comment by rickystewart** [comment]
Sorry for the churn -- conflicts should be resolved and this should be fully working now.

**Comment by rickystewart** [comment]
@irfansharif Can you help me understand the `lint` error [on TeamCity](https://teamcity.cockroachdb.com/viewLog.html?buildId=2534111&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Check)?

From my perspective, all the important stuff is clean on my machine (`bazel run //:gazelle`, `make bazel-generate`, etc.)

`make -k vendor_rebuild` updates some stuff, but the changes that it makes are generally wrong (it makes a couple changes to things in the working directory that would cause the build to break, and it deletes a bunch of the stuff that needs to be there, like rules I've added marked `# keep`). What's going on here?

**Comment by rickystewart** [comment]
I think this has to do with the change I had to make in `cockroachdb/errors` to get everything to compile. I lifted that into https://github.com/cockroachdb/errors/pull/60 which I'll close and incorporate here before merging this.

**Comment by irfansharif** [comment]
I've filed #58227, which I think would be the next step after this work.

**Comment by irfansharif** [comment]
> @irfansharif Can you help me understand the `lint` error [on TeamCity](https://teamcity.cockroachdb.com/viewLog.html?buildId=2534111&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Check)?
> 
> From my perspective, all the important stuff is clean on my machine (`bazel run //:gazelle`, `make bazel-generate`, etc.)
> 
> `make -k vendor_rebuild` updates some stuff, but the changes that it makes are generally wrong (it makes a couple changes to things in the working directory that would cause the build to break, and it deletes a bunch of the stuff that needs to be there, like rules I've added marked `# keep`). What's going on here?

(pardon the verbosity, was learning as I go)

So `make -k vendor_rebuild` wants to assert that `go mod vendor` + 
`bazel run //:gazelle` are sufficient to generate everything you need under
 `vendor/` which is not the case if you’re wanting to change `BUILD.bazel`
within `vendor/` files by hand.

In an ideal world the BUILD files generated through gazelle automatically do
the right thing, but that’s not true for us because it doesn’t play well with
.proto files in our dependencies (which is why we needed to tweak them by hand,
and exclude those paths in the top-level BUILD file).

Basically in an ideal world we’d either be using `go_proto_library` exclusively,
i.e. everything gazelle generated just works out of the box, or we pre-generate
_all_ pb.go files. Ref: https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts

To get past our CI assertion, we could generate a `.patch` file that adds your
manual changes to all the BUILD files within `vendor`, and apply that patch as
part of `make -k vendor_rebuild`. I think that's the easiest path forward, and I
think it makes sense. Whenever someone's bumping a dependency, we want an
idempotent way to generate everything under `vendor/`, which today we check for
by nuking the whole thing and building it from scratch (check
`build/vendor_rebuild.sh`).

So teaching `make -k vendor_rebuild` to correctly bazel-ify `vendor/` seems
appropriate to me, which for us now includes these manual BUILD overrides. We
already did the same earlier by running `bazel run //:gazelle` as part of `make
-k vendor_rebuild`.

**Review by irfansharif — APPROVED** [review]
Everything else here LGTM. FWIW I played around with it, and we don't need all the `resolve` directives. I also think we should change some of the `gazelle:resolve proto ...` directives to explicitly specify the import language. If we don't do so, re-ordering the directives ends up actually breaking the bazel build, which is a bit non-obvious.

```diff
diff --git a/BUILD.bazel b/BUILD.bazel
index 831907e0e7..5a59b5a79a 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -22,19 +22,16 @@ load("@bazel_gazelle//:def.bzl", "gazelle")

 # Gazelle needs the following resolve hints.
 #
-# gazelle:resolve go github.com/grpc-ecosystem/grpc-gateway/internal //vendor/github.com/grpc-ecosystem/grpc-gateway/internal
 # gazelle:resolve go github.com/envoyproxy/protoc-gen-validate/validate //vendor/github.com/envoyproxy/protoc-gen-validate/validate:validate_go_proto
-# gazelle:resolve go google.golang.org/genproto/googleapis/api/annotations //vendor/google.golang.org/genproto/googleapis/api/annotations
-# gazelle:resolve go google.golang.org/genproto/googleapis/api/httpbody //vendor/google.golang.org/genproto/googleapis/api/httpbody
-# gazelle:resolve go google.golang.org/genproto/googleapis/rpc/code //vendor/google.golang.org/genproto/googleapis/rpc/code
-# gazelle:resolve go google.golang.org/genproto/googleapis/rpc/status //vendor/google.golang.org/genproto/googleapis/rpc/status
-# gazelle:resolve proto errorspb/errors.proto //vendor/github.com/cockroachdb/errors/errorspb:errorspb_proto
+# gazelle:resolve go github.com/prometheus/client_model/go //vendor/github.com/prometheus/client_model/go
 # gazelle:resolve proto go errorspb/errors.proto //vendor/github.com/cockroachdb/errors/errorspb
-# gazelle:resolve proto gogoproto/gogo.proto //vendor/github.com/gogo/protobuf/gogoproto:gogo_proto
 # gazelle:resolve proto go gogoproto/gogo.proto //vendor/github.com/gogo/protobuf/gogoproto
-# gazelle:resolve proto etcd/raft/v3/raftpb/raft.proto //vendor/go.etcd.io/etcd/raft/v3/raftpb:raft_proto
 # gazelle:resolve proto go etcd/raft/v3/raftpb/raft.proto //vendor/go.etcd.io/etcd/raft/v3/raftpb
-# gazelle:resolve go github.com/prometheus/client_model/go //vendor/github.com/prometheus/client_model/go
+# gazelle:resolve proto go prometheus/client_model/metrics.proto //vendor/github.com/prometheus/client_model:io_prometheus_client_go_proto
+# gazelle:resolve proto proto errorspb/errors.proto //vendor/github.com/cockroachdb/errors/errorspb:errorspb_proto
+# gazelle:resolve proto proto gogoproto/gogo.proto //vendor/github.com/gogo/protobuf/gogoproto:gogo_proto
+# gazelle:resolve proto proto etcd/raft/v3/raftpb/raft.proto //vendor/go.etcd.io/etcd/raft/v3/raftpb:raft_proto
+# gazelle:resolve proto proto prometheus/client_model/metrics.proto //vendor/github.com/prometheus/client_model:io_prometheus_client_proto
```

**Comment by rickystewart** [comment]
#58229 breaks this -- I'm going to rebase on that, and get this working again in much the same way as before.

**Comment by rickystewart** [comment]
Something's wrong. Going to close while I figure this out. :)

**Pull request closed without merging**
