### PR TITLE
rowexec: change invertedFilterer to handle the inverted column

### PR DESCRIPTION
**Pull request by sumeerbhola**
at an arbitrary column index

The previous behavior expected it to be index 0, which is creating
difficulties in PR #50158

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
nit: the commit message is too long (we try to keep it on a single line)

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-:-MA6mUv18ci6GsyucF5R:b-eqw1dk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6nns87E7cumlEDIBN:-MA6nns87E7cumlEDIBO:bxr9dvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L536)):*
> ```protobuf
> // on a table by evaluating an invertedexpr.SpanExpressionProto on an inverted
> // index of the table. The input consists of the inverted index rows from
> // InvertedExpr.SpansToRead.  It is acceptable for a filter on the primary key
> ```

nit: seems like multiple spaces before "It".
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 541 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6mlVt2Fi46d7jO_yh:-MA6mlVt2Fi46d7jO_yi:b-a30v5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L541)):*
> ```protobuf
> // TODO(sumeer): pushing the PK filter down before the inverted filtering
> // would usually be better than the OnExpr evaluated here since the former can
> // always be distributed. The only case where doing the OnExpr here (which
> ```

nit: feels like a word is missing, maybe "where doing the OnExpr *is better* here...".
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6ne3r75Lfd3p-mxlI:-MA6ne3r75Lfd3p-mxlJ:b-t6q3d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L545)):*
> ```protobuf
> // evaluate, has high selectivity, and evaluating it on duplicates of the same
> // PK is more expensive than the de-duplicated evaluation that happens here.
> // Should we remove the OnExpr from here or keep it for now?
> ```

I think if, in general, it is faster to push the filter to the scan, then we should remove `OnExpr` field. You could leave a TODO to introduce it later and use the field for the case when it is faster to not push it down.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6pxxR4oo8d569DYIW:-MA6pxxR4oo8d569DYIX:b8lwuve) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/rowexec/inverted_filterer.go#L98)):*
> ```Go
> 	inputTypes := input.OutputTypes()
> 	outputColTypes := make([]*types.T, 0, len(inputTypes)-1)
> 	for i := range inputTypes {
> ```

Rather than performing the iteration, we could do two `copy` calls:
```
copy(outputColTypes, inputTypes[:ifr.invertedColIdx])
copy(outputColTypes[ifr.invertedColIdx], inputTypes[ifr.invertedColIdx+1:])
```
___
*[pkg/sql/rowexec/inverted_filterer.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6pGmT4ARvZ_faITJu:-MA6pGmUB7_xukl3oX1x:b-x26ka4) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/rowexec/inverted_filterer.go#L194)):*
> ```Go
> 		return ifrEmittingRows, nil
> 	}
> 	// Replace missing values with nulls to appease the row container. And
> ```

super nit: I'd combine two sentences into one.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6qJgL457zJb2TqBeZ:-MA6qJgL457zJb2TqBe_:b-d2iths) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/rowexec/inverted_filterer.go#L202)):*
> ```Go
> 		}
> 		if i != int(ifr.invertedColIdx) {
> 			ifr.keyRow[j] = row[i]
> ```

ditto for two `copy` calls outside of the for loop.

**Review by sumeerbhola — COMMENTED** [review]
> nit: the commit message is too long (we try to keep it on a single line)

Fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-:-MAQqOaiBpDwtPqWK6jR:b-da75au)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6nns87E7cumlEDIBN:-MAQk9H7C-rC_NSS7U0J:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L536)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: seems like multiple spaces before "It".
</blockquote></details>

Done
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 541 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6mlVt2Fi46d7jO_yh:-MAQkxisBW-7W70o9yoP:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L541)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: feels like a word is missing, maybe "where doing the OnExpr *is better* here...".
</blockquote></details>

Done
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6ne3r75Lfd3p-mxlI:-MAQl3yI0fs6kN5CVQtB:bumre1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L545)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think if, in general, it is faster to push the filter to the scan, then we should remove `OnExpr` field. You could leave a TODO to introduce it later and use the field for the case when it is faster to not push it down.
</blockquote></details>

@rytaft : do you have an opinion on this? 
___
*[pkg/sql/rowexec/inverted_filterer.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6pxxR4oo8d569DYIW:-MAQmpMh7SSqBLYyrL8u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/rowexec/inverted_filterer.go#L98)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Rather than performing the iteration, we could do two `copy` calls:
```
copy(outputColTypes, inputTypes[:ifr.invertedColIdx])
copy(outputColTypes[ifr.invertedColIdx], inputTypes[ifr.invertedColIdx+1:])
```
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6pGmT4ARvZ_faITJu:-MAQmwzWA9Tnyoo51FWb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/rowexec/inverted_filterer.go#L194)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: I'd combine two sentences into one.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6qJgL457zJb2TqBeZ:-MAQnXbDADe5ZfEY9G-E:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/rowexec/inverted_filterer.go#L202)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto for two `copy` calls outside of the for loop.
</blockquote></details>

Done

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-:-MASR8WsCdLyQ2jO7Wt8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6ne3r75Lfd3p-mxlI:-MASOOT_DJo5I5c19IEV:byyap2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L545)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

@rytaft : do you have an opinion on this? 
</blockquote></details>

At the moment we don't consider any predicates to be "expensive" in the optimizer other than geospatial functions, which would never use only primary keys.

I think it's fine to remove the `OnExpr` field and leave a TODO/comment.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-:-MASk_FbDfrLWXubeQhw:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-:-MAWPZas08zRku3om8CS:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50389#-MA6ne3r75Lfd3p-mxlI:-MAWMDdFCOlWRSBC2QBz:bwu5vs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/42f546fea5c6800af2af000caa325be79ba6c7c2/pkg/sql/execinfrapb/processors_sql.proto#L545)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

At the moment we don't consider any predicates to be "expensive" in the optimizer other than geospatial functions, which would never use only primary keys.

I think it's fine to remove the `OnExpr` field and leave a TODO/comment.
</blockquote></details>

The TODO was turning out to be confusing, and since this situation is far-fetched, I've simply removed the `on_expr`.

**Pull request merged**
