### PR TITLE
release-21.1: sql: graciously handle vectorize=201auto option removal

### PR DESCRIPTION
**Pull request by yuzefovich**
In 21.1 cycle we removed `vectorize='201auto'` option. However, if on
20.2 cluster used it as the cluster setting, then during upgrade to 21.1
an error will be logged about not being able to find the value (note
that we still would have gotten the desired behavior of using `on` as
the default after upgrade). This commit makes that migration nicer by
explicitly mapping the deleted value to `on`.

Note that this commit will only be present on release-21.1 branch since
21.2 branch already contains the desired state.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/exec_util.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61743#-MVRamqJ2nfM0fwsxLHc:-MVRamqJ2nfM0fwsxLHd:b-l8c4m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d65c9c01f0880425e17458447c6e07eba6714b8/pkg/sql/exec_util.go#L392)):*
> ```Go
> // only in order to handle the upgrade from 20.2 to 21.1 clusters without an
> // error.
> const deprecatedVectorize201Auto = 1
> ```

Why not put this in the `VectorizeExecMode` const declaration (in sessiondatapb)? It'll be a lot clearer I think (and also explain the missing `1` value)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/exec_util.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61743#-MVRamqJ2nfM0fwsxLHc:-MVRy81tBzfqWiSu1Ax1:b-9j8ojh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d65c9c01f0880425e17458447c6e07eba6714b8/pkg/sql/exec_util.go#L392)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not put this in the `VectorizeExecMode` const declaration (in sessiondatapb)? It'll be a lot clearer I think (and also explain the missing `1` value) 
</blockquote></details>

This was my original approach as well, but it failed [many tests](https://teamcity.cockroachdb.com/viewLog.html?buildId=2760633&buildTypeId=Cockroach_UnitTests), so I thought this approach would be least invasive. Still it also failed many tests, so I'll need to take a closer look.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/exec_util.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61743#-MVRamqJ2nfM0fwsxLHc:-MVS3-yBAjYBhukuEmT2:b-aocxad) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d65c9c01f0880425e17458447c6e07eba6714b8/pkg/sql/exec_util.go#L392)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This was my original approach as well, but it failed [many tests](https://teamcity.cockroachdb.com/viewLog.html?buildId=2760633&buildTypeId=Cockroach_UnitTests), so I thought this approach would be least invasive. Still it also failed many tests, so I'll need to take a closer look.
</blockquote></details>

Missed one spot where we also needed to perform the mapping. RFAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: minus the rename to add a `Deprecated` prefix

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61743#-:-MVS6gyFEM_qF3Q-NzmX:b-51anca)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/sessiondatapb/session_data.proto, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61743#-MVS6Zr03GfZWK_ugHZp:-MVS6Zr03GfZWK_ugHZq:b1o0rog) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0071d82d1494798cb21a4c1a36798426d152be/pkg/sql/sessiondatapb/session_data.proto#L100)):*
> ```protobuf
>   // It exists only in order to handle the upgrade from 20.2 to 21.1 clusters
>   // without an error.
>   Vectorize201Auto = 1;
> ```

nit: `s/Vectorize201Auto/DeprecatedVectorize201Auto`

**Pull request merged**
