### PR TITLE
sql: support ALTER DEFAULT PRIVILEGES IN SCHEMA

### LINKED ISSUE #67376: sql: support ALTER DEFAULT PRIVILEGES IN SCHEMA
Once default privileges are implemented at the database level, support default privileges on the schema.

Depends on: https://github.com/cockroachdb/cockroach/pull/66785

Would also like to wait on this https://github.com/cockroachdb/cockroach/issues/55793 so that public schemas have descriptors to simplify where we store default privileges.

Epic CRDB-1521

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change):
Support ALTER DEFAULT PRIVILEGES IN SCHEMA <schemas...>
Users can now in addition to specifying default privileges globally
(within a database), specify default privileges in a specific schema.

When creating an object that has default privileges specified at
the database (global) and at the schema level, the union of the
default privileges are taken.

Resolves https://github.com/cockroachdb/cockroach/issues/67376

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[docs/generated/eventlog.md, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp13Tq9d1MT6uBeOFN:-Mqp13TrEbzq3KS43Olu:b136aq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/docs/generated/eventlog.md#L1562)):*
> ```Markdown
> | `RoleName` | Either role_name should be populated or for_all_roles should be true. The role having its default privileges altered. | yes |
> | `ForAllRoles` | Identifies if FOR ALL ROLES is used. | no |
> | `SchemaName` | The names of the affected schema. | yes |
> ```

nit: the field should be plural (`SchemaNames`) if it's a list
___
*[pkg/sql/drop_role.go, line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MqWr0CdACSeH1JG69da:-MqWr0CdACSeH1JG69db:b-2y027f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/drop_role.go#L426)):*
> ```Go
> // accumulateDependentDefaultPrivileges checks for any default privileges
> // that the users in userNames have and append them to the objectAndType array.
> // Only one of db or sc should be non-nil.
> ```

this is a little brittle. why don't we instead make the parameter a `catalog.DefaultPrivilegeDescriptor` so that the caller has to call `GetDefaultPrivilegeDescriptor`?
___
*[pkg/sql/catalog/catprivilege/default_privilege.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MqWrcnX7s6_tQbuPnK6:-MqWrcnX7s6_tQbuPnK7:b-snvrni) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege.go#L80)):*
> ```Go
> }
> 
> // Calls expandPrivileges before calling the function passed in and calls
> ```

nit: the function comment should be a full sentence, and should start with `grantOrRevokeDefaultPrivilegesHelper calls ...`
___
*[pkg/sql/catalog/catprivilege/default_privilege.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp4831067Y1DNSkrH_:-Mqp4831067Y1DNSkrHa:b-nwsh1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege.go#L171)):*
> ```Go
> // the default privilege descriptor from the database or both the db and schema.
> func CreatePrivilegesFromDefaultPrivileges(
> 	defaultPrivilegeDescriptors []catalog.DefaultPrivilegeDescriptor,
> ```

why use a slice here instead of passing in one arg for the dbDefaultPrivs and another arg for schemaDefaultPrivs
___
*[pkg/sql/catalog/catprivilege/default_privilege_test.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp4uEQ1gyvttUiCwN6:-Mqp4uEQ1gyvttUiCwN7:b7rl8it) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege_test.go#L165)):*
> ```Go
> 
> 	for _, tc := range testCases {
> 		defaultPrivilegeDescriptor := MakeNewDatabaseDefaultPrivilegeDescriptor()
> ```

after seeing this a few times, i wonder if it would be more readable to have one `MakeDefaultPrivilegeDescriptor` that accepts a `descriptorType` parameter?

also nit: `MakeNewXyz` is redundant; i think `MakeXyz` is sufficient.
___
*[pkg/sql/catalog/catprivilege/default_privilege_test.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp5KBN48s6kJXAAaTP:-Mqp5KBO06Slh11x45Il:b7on4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege_test.go#L379)):*
> ```Go
> 		// for a schema.
> 		if newPrivileges.CheckPrivilege(creatorUser, privilege.ALL) {
> 			t.Errorf("expected creator to have not ALL privileges on %s", targetObject)
> ```

nit: "to have not ALL" is confusing. is there a typo?

also, just to clarify, this check is different than the "base" schema privileges that the "public" role has?
___
*[pkg/sql/catalog/descpb/privilege.proto, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp5mkTDhVLaifb_x6M:-Mqp5mkTDhVLaifb_x6N:b-ldc2re) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/descpb/privilege.proto#L93)):*
> ```protobuf
>   option (gogoproto.equal) = true;
>   repeated DefaultPrivilegesForRole default_privileges_per_role = 1 [(gogoproto.nullable) = false];
>   enum DefaultPrivilegeDescriptorType {
> ```

hm, since we're adding this to the proto, does that mean all the logic that looks at this enum needs to be version gated? maybe it can be avoided if the deserialization logic defaults to setting this to 0?
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7cvT1khzlhm8CsBV:-Mqp7cvT1khzlhm8CsBW:b-w0052b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L120)):*
> ```
> statement ok
> ALTER DEFAULT PRIVILEGES FOR ROLE testuser IN SCHEMA s, public REVOKE ALL ON TABLES FROM testuser2;
> ALTER DEFAULT PRIVILEGES FOR ALL ROLES IN SCHEMA s, public GRANT SELECT ON TABLES TO testuser2;
> ```

just to confirm, does this cover the case where default privs on (db+schema) overrides default privs on db? and make sure the override is actually per-schema?
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7Ba8581BEO8NvhhI:-Mqp7Ba8581BEO8NvhhJ:bpfem3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L161)):*
> ```
> test           public       t9          admin      ALL
> test           public       t9          root       ALL
> test           public       t9          testuser   CREATE
> ```

i think this is unrelated to your current work, but what does CREATE really mean here? isn't CREATE a DB privilege? so why are schema and table_name set?
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7GeHDdSHU-GuwWCl:-Mqp7GeHDdSHU-GuwWCm:b9f3cq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L193)):*
> ```
> 
> # Default privileges for schemas have no defaults - no privileges are defined
> # initially.
> ```

i thought we had CREATE granted to public by default? (ref https://github.com/cockroachdb/cockroach/issues/70266)
___
*[pkg/util/log/eventpb/privilege_events.proto, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MqWudJY-emuP3sXNonY:-MqWudJY-emuP3sXNonZ:b-yu1f06) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/util/log/eventpb/privilege_events.proto#L138)):*
> ```protobuf
>   // Identifies if FOR ALL ROLES is used.
>   bool for_all_roles = 6 [(gogoproto.jsontag) = ",omitempty"];
>   // The names of the affected schema.
> ```

nit: should be `name` not `names`

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[docs/generated/eventlog.md, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp13Tq9d1MT6uBeOFN:-Mqu83xbEUSxvFJI-bTq:b8d5imr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/docs/generated/eventlog.md#L1562)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the field should be plural (`SchemaNames`) if it's a list
</blockquote></details>

Oops this actual should just be one schema right now.
___
*[pkg/sql/drop_role.go, line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MqWr0CdACSeH1JG69da:-Mqu8U2bCV7Os7umhTf3:bjvg1xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/drop_role.go#L426)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is a little brittle. why don't we instead make the parameter a `catalog.DefaultPrivilegeDescriptor` so that the caller has to call `GetDefaultPrivilegeDescriptor`?
</blockquote></details>

That's much nicer good call.
___
*[pkg/sql/catalog/catprivilege/default_privilege.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MqWrcnX7s6_tQbuPnK6:-Mqu8euq2pHdVD6oYDrp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege.go#L80)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the function comment should be a full sentence, and should start with `grantOrRevokeDefaultPrivilegesHelper calls ...`
</blockquote></details>

Done
___
*[pkg/sql/catalog/catprivilege/default_privilege.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp4831067Y1DNSkrH_:-Mqu9tbECOd2wnG3nMSL:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege.go#L171)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why use a slice here instead of passing in one arg for the dbDefaultPrivs and another arg for schemaDefaultPrivs
</blockquote></details>

Good call, done.
___
*[pkg/sql/catalog/catprivilege/default_privilege_test.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp4uEQ1gyvttUiCwN6:-MquAnHd6kwT7nKALZAR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege_test.go#L165)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

after seeing this a few times, i wonder if it would be more readable to have one `MakeDefaultPrivilegeDescriptor` that accepts a `descriptorType` parameter?

also nit: `MakeNewXyz` is redundant; i think `MakeXyz` is sufficient.
</blockquote></details>

Done
___
*[pkg/sql/catalog/catprivilege/default_privilege_test.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp5KBN48s6kJXAAaTP:-MquBRFt4DKBG0zbbJKT:by5yk22) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/catprivilege/default_privilege_test.go#L379)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: "to have not ALL" is confusing. is there a typo?

also, just to clarify, this check is different than the "base" schema privileges that the "public" role has?
</blockquote></details>

Reworded to `creator should not have ALL privileges`

This check is different.
I checked with PG there is no "default" / preset privileges for default privileges on schemas.
___
*[pkg/sql/catalog/descpb/privilege.proto, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp5mkTDhVLaifb_x6M:-MquCDME4oUOzW6up7Ua:bh8tqax) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/descpb/privilege.proto#L93)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, since we're adding this to the proto, does that mean all the logic that looks at this enum needs to be version gated? maybe it can be avoided if the deserialization logic defaults to setting this to 0?
</blockquote></details>

I think the `DefaultPrivilegeDescriptorType` will resolve to 0 on older versions so that should be okay. I'll double check.
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7cvT1khzlhm8CsBV:-MquCNu88-XZ4hF432aJ:bw87ytl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L120)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just to confirm, does this cover the case where default privs on (db+schema) overrides default privs on db? and make sure the override is actually per-schema?
</blockquote></details>

It's not override it's actually the union of the privileges on the db and schema

```
# When creating an object, take the union of the default privileges on
# the schema and the database.
# In the following test cases, testuser2 should have INSERT and SELECT.
statement ok
ALTER DEFAULT PRIVILEGES FOR ROLE testuser GRANT INSERT ON TABLES TO testuser2

statement ok
CREATE TABLE t2()

query TTTTT colnames
SHOW GRANTS ON t2
----
database_name  schema_name  table_name  grantee    privilege_type
test           public       t2          admin      ALL
test           public       t2          root       ALL
test           public       t2          testuser   ALL
test           public       t2          testuser2  INSERT
test           public       t2          testuser2  SELECT
```

this case covers that
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7Ba8581BEO8NvhhI:-MquCmn5DTSkEwgZyfml:brpvses) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L161)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this is unrelated to your current work, but what does CREATE really mean here? isn't CREATE a DB privilege? so why are schema and table_name set?
</blockquote></details>

I think `CREATE` on table was used to substitute for some owner privileges, ie since we didn't have the concept of ownership before, you needed `CREATE` to alter or drop the table. `CREATE` still lets you do those things.
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7GeHDdSHU-GuwWCl:-MquCgoSBL3iugWHUlIM:b-5c9qd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L193)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i thought we had CREATE granted to public by default? (ref https://github.com/cockroachdb/cockroach/issues/70266)
</blockquote></details>

I believe thats on the public schema
___
*[pkg/util/log/eventpb/privilege_events.proto, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MqWudJY-emuP3sXNonY:-Mqu81nn3OUYU_0Vp83G:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/util/log/eventpb/privilege_events.proto#L138)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should be `name` not `names`
</blockquote></details>

Done

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[docs/generated/eventlog.md, line 1562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MquJIi_3xPc7cUGvQAl:-MquJIi_3xPc7cUGvQAm:b5viou9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae581c4b4b1ea6784ae2b9062f2d1d84631745e/docs/generated/eventlog.md#L1562)):*
> ```Markdown
> | `RoleName` | Either role_name should be populated or for_all_roles should be true. The role having its default privileges altered. | yes |
> | `ForAllRoles` | Identifies if FOR ALL ROLES is used. | no |
> | `SchemaName` | The names of the affected schema. | yes |
> ```

nit: should be "The name of the affected schema" 
___
*[pkg/sql/drop_role.go, line 426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MquJZNm1QQfaN2jzF4s:-MquJZNm1QQfaN2jzF4t:bf8fk7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae581c4b4b1ea6784ae2b9062f2d1d84631745e/pkg/sql/drop_role.go#L426)):*
> ```Go
> // accumulateDependentDefaultPrivileges checks for any default privileges
> // that the users in userNames have and append them to the objectAndType array.
> // Only one of db or sc should be non-nil.
> ```

nit: update comment that describes the params
___
*[pkg/sql/catalog/descpb/privilege.proto, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp5mkTDhVLaifb_x6M:-MquKDQe6zF0-V92swtH:b-kx506s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/descpb/privilege.proto#L93)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think the `DefaultPrivilegeDescriptorType` will resolve to 0 on older versions so that should be okay. I'll double check.
</blockquote></details>

is there already a mixed-version test for this? i think that should be sufficient
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7GeHDdSHU-GuwWCl:-MquKvG1AA_jCJ3Lvd1l:b-2s9r17) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L193)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I believe thats on the public schema
</blockquote></details>

ah right, so that would be seen from `show grants on schema public;` right? i think we'd want a test for that too, although i guess that might be considered out of scope for this PR. would you be open to adding that as a separate commit?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[docs/generated/eventlog.md, line 1562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MquJIi_3xPc7cUGvQAl:-MquleUQ7QZiSxVaWqel:b-c1qujf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae581c4b4b1ea6784ae2b9062f2d1d84631745e/docs/generated/eventlog.md#L1562)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should be "The name of the affected schema" 
</blockquote></details>

It was updated in r3 I think you saw an older commit.
___
*[pkg/sql/drop_role.go, line 426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MquJZNm1QQfaN2jzF4s:-Mqulqkw24M6E9jkNvn3:b-yuswkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae581c4b4b1ea6784ae2b9062f2d1d84631745e/pkg/sql/drop_role.go#L426)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: update comment that describes the params
</blockquote></details>

Oops done
___
*[pkg/sql/catalog/descpb/privilege.proto, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp5mkTDhVLaifb_x6M:-MqumYiUCfyQDb2p8ZKb:b98mglf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/descpb/privilege.proto#L93)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there already a mixed-version test for this? i think that should be sufficient
</blockquote></details>

```
func TestUnsetDefaultPrivilegeDescriptorType(t *testing.T) {
	emptyDefaultPrivilegeDescriptor := descpb.DefaultPrivilegeDescriptor{}

	// If Type is not set, it should resolve to
	// descpb.DefaultPrivilegeDescriptor_DATABASE by default.
	require.Equal(t, emptyDefaultPrivilegeDescriptor.Type, descpb.DefaultPrivilegeDescriptor_DATABASE)
}
```

is this test sufficient?

I think a mixed-version test is overkill and a little unclear.
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7GeHDdSHU-GuwWCl:-MqunI8u-IBKyynKnklz:b2klnr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L193)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah right, so that would be seen from `show grants on schema public;` right? i think we'd want a test for that too, although i guess that might be considered out of scope for this PR. would you be open to adding that as a separate commit?
</blockquote></details>

Yeah I don't think that is relevant to this PR as it's not handled as a default privilege at all.
Right now that's hardcoded in descriptor.go

I can add a test for that in another logic test if you want.

```
	publicSchemaID, err := catalogkv.GenerateUniqueDescID(ctx, p.ExecCfg().DB, p.ExecCfg().Codec)
	if err != nil {
		return descpb.InvalidID, err
	}

	// Every database must be initialized with the public schema.
	// Create the SchemaDescriptor.
	// In postgres, the user "postgres" is the owner of the public schema in a
	// newly created db. Postgres and Public have USAGE and CREATE privileges.
	// In CockroachDB, root is our substitute for the postgres user.
	publicSchemaPrivileges := descpb.NewBasePrivilegeDescriptor(security.AdminRoleName())
	// By default, everyone has USAGE and CREATE on the public schema.
	publicSchemaPrivileges.Grant(security.PublicRoleName(), privilege.List{privilege.CREATE, privilege.USAGE}, false)
	publicSchemaDesc := schemadesc.NewBuilder(&descpb.SchemaDescriptor{
		ParentID:   dbID,
		Name:       tree.PublicSchema,
		ID:         publicSchemaID,
		Privileges: publicSchemaPrivileges,
		Version:    1,
	}).BuildCreatedMutableSchema()
```

**Review by rafiss — APPROVED** [review]
lgtm! but can you add in the error propagation?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-:-MqzEnB87x02LdxKgQx-:bpaymge)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 432 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-MqzE44rCUmrrxlpI9JN:-MqzE44rCUmrrxlpI9JO:b-yqpmey) ([raw file](https://github.com/cockroachdb/cockroach/blob/f125ed2abfad8eafd07b4d603566cd06165e8d3b/pkg/sql/drop_role.go#L432)):*
> ```Go
> 	// The func we pass into ForEachDefaultPrivilegeForRole will never
> 	// err so no err will be returned.
> 	_ = defaultPrivilegeDescriptor.ForEachDefaultPrivilegeForRole(func(
> ```

didn't realize the error was getting swallowed here. even though we don't need it know it is more future-proof to propagate the error up (so `accumulateDependentDefaultPrivileges` should return an error). otherwise a future refactoring could easily lead to bad error handling.
___
*[pkg/sql/catalog/descpb/privilege.proto, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp5mkTDhVLaifb_x6M:-MqzEWtk8mXnF-OSPRud:bdhhm19) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/catalog/descpb/privilege.proto#L93)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

```
func TestUnsetDefaultPrivilegeDescriptorType(t *testing.T) {
	emptyDefaultPrivilegeDescriptor := descpb.DefaultPrivilegeDescriptor{}

	// If Type is not set, it should resolve to
	// descpb.DefaultPrivilegeDescriptor_DATABASE by default.
	require.Equal(t, emptyDefaultPrivilegeDescriptor.Type, descpb.DefaultPrivilegeDescriptor_DATABASE)
}
```

is this test sufficient?

I think a mixed-version test is overkill and a little unclear.
</blockquote></details>

this is sufficient, thanks!
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7cvT1khzlhm8CsBV:-MqzEZQVB6fGRLS6lTT0:b-zgam8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L120)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

It's not override it's actually the union of the privileges on the db and schema

```
# When creating an object, take the union of the default privileges on
# the schema and the database.
# In the following test cases, testuser2 should have INSERT and SELECT.
statement ok
ALTER DEFAULT PRIVILEGES FOR ROLE testuser GRANT INSERT ON TABLES TO testuser2

statement ok
CREATE TABLE t2()

query TTTTT colnames
SHOW GRANTS ON t2
----
database_name  schema_name  table_name  grantee    privilege_type
test           public       t2          admin      ALL
test           public       t2          root       ALL
test           public       t2          testuser   ALL
test           public       t2          testuser2  INSERT
test           public       t2          testuser2  SELECT
```

this case covers that
</blockquote></details>

got it thanks for explaining
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7Ba8581BEO8NvhhI:-MqzEaq69sIA4T73C8EF:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L161)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think `CREATE` on table was used to substitute for some owner privileges, ie since we didn't have the concept of ownership before, you needed `CREATE` to alter or drop the table. `CREATE` still lets you do those things.
</blockquote></details>

done
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73576#-Mqp7GeHDdSHU-GuwWCl:-MqzEdBA7uzUt1fjqrRa:b-2mjh0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd3c7e3fdd11cb310bd5a78f1cca7ccbb3e8f3d4/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_in_schema#L193)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Yeah I don't think that is relevant to this PR as it's not handled as a default privilege at all.
Right now that's hardcoded in descriptor.go

I can add a test for that in another logic test if you want.

```
	publicSchemaID, err := catalogkv.GenerateUniqueDescID(ctx, p.ExecCfg().DB, p.ExecCfg().Codec)
	if err != nil {
		return descpb.InvalidID, err
	}

	// Every database must be initialized with the public schema.
	// Create the SchemaDescriptor.
	// In postgres, the user "postgres" is the owner of the public schema in a
	// newly created db. Postgres and Public have USAGE and CREATE privileges.
	// In CockroachDB, root is our substitute for the postgres user.
	publicSchemaPrivileges := descpb.NewBasePrivilegeDescriptor(security.AdminRoleName())
	// By default, everyone has USAGE and CREATE on the public schema.
	publicSchemaPrivileges.Grant(security.PublicRoleName(), privilege.List{privilege.CREATE, privilege.USAGE}, false)
	publicSchemaDesc := schemadesc.NewBuilder(&descpb.SchemaDescriptor{
		ParentID:   dbID,
		Name:       tree.PublicSchema,
		ID:         publicSchemaID,
		Privileges: publicSchemaPrivileges,
		Version:    1,
	}).BuildCreatedMutableSchema()
```
</blockquote></details>

actually i'll just make a PR to add it so you don't have to context switch

**Comment by RichardJCai** [comment]
TFTR 
bors r=rafiss

**Pull request merged**
