### PR TITLE
sql, opt: support hint to disallow full scan, update coster to avoid full scans

### LINKED ISSUE #70795: what exactly does disallow_full_table_scans do? / is it working correctly?
I apologize if this is the wrong venue for this.  I can't tell if this behavior is buggy or just not what I expected.

**Describe the problem**

The `disable_full_table_scans` option seems so close to what I'm looking for, but not quite right.

My team is building an application atop CockroachDB with the intent of scaling horizontally.  Naturally, we want to avoid using queries that require full scans on tables that might grow arbitrarily large.  We're trying to figure out the best way to avoid accidentally introducing such a query.  Ideally, we'd like to find out early during development that a query is problematic, not when we go to do large-scale testing later.  I was excited to find `disallow_full_table_scans=off` because I thought it might help us identify queries that _require_ a table scan.  But it doesn't seem to work quite the way I'd expect in two ways.

First, it seems to allow some full scans?  Take this query:

```
root@127.0.0.1:32221/omicron> set disallow_full_table_scans=on;
SET

Time: 52ms total (execution 0ms / network 51ms)

root@127.0.0.1:32221/omicron> EXPLAIN SELECT * FROM
  vpcsubnet,
  vpc,
  project
WHERE
  project.name = 'test1' AND
  project.time_deleted IS NULL AND
  project.id = vpc.project_id AND
  vpc.name = 'vpc1' AND
  vpc.time_deleted IS NULL AND
  vpc.id = vpcsubnet.vpc_id AND
  vpcsubnet.time_deleted IS NULL
ORDER BY
  vpcsubnet.name ASC
LIMIT
  100
;
              tree              |        field        |                 description
--------------------------------+---------------------+----------------------------------------------
                                | distribution        | full
                                | vectorized          | false
  limit                         |                     |
   │                            | count               | 100
   └── sort                     |                     |
        │                       | order               | +name
        └── hash join           |                     |
             │                  | equality            | (vpc_id) = (id)
             │                  | right cols are key  |
             ├── filter         |                     |
             │    │             | filter              | time_deleted IS NULL
             │    └── scan      |                     |
             │                  | estimated row count | 1
             │                  | table               | vpcsubnet@primary
             │                  | spans               | FULL SCAN
             └── hash join      |                     |
                  │             | equality            | (project_id) = (id)
                  │             | right cols are key  |
                  ├── filter    |                     |
                  │    │        | filter              | (name = 'vpc1') AND (time_deleted IS NULL)
                  │    └── scan |                     |
                  │             | estimated row count | 1
                  │             | table               | vpc@primary
                  │             | spans               | FULL SCAN
                  └── filter    |                     |
                       │        | filter              | (name = 'test1') AND (time_deleted IS NULL)
                       └── scan |                     |
                                | estimated row count | 1
                                | table               | project@primary
                                | spans               | FULL SCAN
(30 rows)

Time: 54ms total (execution 3ms / network 51ms)
```

There are three `FULL SCAN` nodes there.  Why is that allowed with `disallow_full_table_scans=on`?

Note that when I ran this, all three of these tables were empty:

<details>

```
root@127.0.0.1:32221/omicron> select count(*) from vpcsubnet;
ERROR: query `select count(*) from vpcsubnet` contains a full table/index scan which is explicitly disallowed
SQLSTATE: P0003
HINT: try overriding the `disallow_full_table_scans` cluster/session setting
root@127.0.0.1:32221/omicron> set disallow_full_table_scans=off;
SET

Time: 53ms total (execution 0ms / network 53ms)

root@127.0.0.1:32221/omicron> select count(*) from vpcsubnet;
  count
---------
      0
(1 row)

Time: 53ms total (execution 0ms / network 53ms)

root@127.0.0.1:32221/omicron> select count(*) from vpc;
  count
---------
      0
(1 row)

Time: 52ms total (execution 1ms / network 52ms)

root@127.0.0.1:32221/omicron> select count(*) from project;
  count
---------
      0
(1 row)

Time: 53ms total (execution 1ms / network 52ms)
```

</details>

If you want the schema to reproduce this:

<details>

```
root@127.0.0.1:32221/omicron> SHOW CREATE TABLE vpc;
  table_name |                                               create_statement
-------------+----------------------------------------------------------------------------------------------------------------
  vpc        | CREATE TABLE public.vpc (
             |     id UUID NOT NULL,
             |     name STRING(63) NOT NULL,
             |     description STRING(512) NOT NULL,
             |     time_created TIMESTAMPTZ NOT NULL,
             |     time_modified TIMESTAMPTZ NOT NULL,
             |     time_deleted TIMESTAMPTZ NULL,
             |     project_id UUID NOT NULL,
             |     dns_name STRING(63) NOT NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     UNIQUE INDEX vpc_project_id_name_key (project_id ASC, name ASC) WHERE time_deleted IS NULL,
             |     FAMILY "primary" (id, name, description, time_created, time_modified, time_deleted, project_id, dns_name)
             | )
(1 row)

Time: 56ms total (execution 5ms / network 51ms)

root@127.0.0.1:32221/omicron> SHOW CREATE TABLE vpcsubnet;
  table_name |                                                    create_statement
-------------+--------------------------------------------------------------------------------------------------------------------------
  vpcsubnet  | CREATE TABLE public.vpcsubnet (
             |     id UUID NOT NULL,
             |     name STRING(63) NOT NULL,
             |     description STRING(512) NOT NULL,
             |     time_created TIMESTAMPTZ NOT NULL,
             |     time_modified TIMESTAMPTZ NOT NULL,
             |     time_deleted TIMESTAMPTZ NULL,
             |     vpc_id UUID NOT NULL,
             |     ipv4_block INET NULL,
             |     ipv6_block INET NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     UNIQUE INDEX vpcsubnet_vpc_id_name_key (vpc_id ASC, name ASC) WHERE time_deleted IS NULL,
             |     FAMILY "primary" (id, name, description, time_created, time_modified, time_deleted, vpc_id, ipv4_block, ipv6_block)
             | )
(1 row)

Time: 56ms total (execution 5ms / network 51ms)

root@127.0.0.1:32221/omicron> SHOW CREATE TABLE project;
  table_name |                                    create_statement
-------------+------------------------------------------------------------------------------------------
  project    | CREATE TABLE public.project (
             |     id UUID NOT NULL,
             |     name STRING(63) NOT NULL,
             |     description STRING(512) NOT NULL,
             |     time_created TIMESTAMPTZ NOT NULL,
             |     time_modified TIMESTAMPTZ NOT NULL,
             |     time_deleted TIMESTAMPTZ NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     UNIQUE INDEX project_name_key (name ASC) WHERE time_deleted IS NULL,
             |     FAMILY "primary" (id, name, description, time_created, time_modified, time_deleted)
             | )
(1 row)

Time: 56ms total (execution 5ms / network 51ms)
```

</details>

I suspected that maybe this was allowed because the query planner chose to use a full scan even when it wasn't needed (because it knows the table is tiny -- empty, really).  However, I ran into a different case where the query planner _chose_ to do a table scan when an index was available, and that query _was_ disallowed by `disallow_full_table_scans`.  This was the second thing I found surprising.

This time, I'm using this table:

```
root@127.0.0.1:32221/omicron> SHOW CREATE TABLE saga;
  table_name |                                                          create_statement
-------------+--------------------------------------------------------------------------------------------------------------------------------------
  saga       | CREATE TABLE public.saga (
             |     id UUID NOT NULL,
             |     creator UUID NOT NULL,
             |     template_name STRING(127) NOT NULL,
             |     time_created TIMESTAMPTZ NOT NULL,
             |     saga_params JSONB NOT NULL,
             |     saga_state STRING(31) NOT NULL,
             |     current_sec UUID NULL,
             |     adopt_generation INT8 NOT NULL,
             |     adopt_time TIMESTAMPTZ NOT NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     UNIQUE INDEX saga_current_sec_id_key (current_sec ASC, id ASC) WHERE saga_state != 'done':::STRING,
             |     FAMILY "primary" (id, creator, template_name, time_created, saga_params, saga_state, current_sec, adopt_generation, adopt_time)
             | )
(1 row)

Time: 60ms total (execution 8ms / network 52ms)
```

Again, starting from an empty table:

```
root@127.0.0.1:32221/omicron> select count(*) from saga;
  count
---------
      0
(1 row)

Time: 51ms total (execution 1ms / network 50ms)
```

I was surprised that this query _didn't_ work with disallow_full_table_scans:

```
root@127.0.0.1:32221/omicron> SELECT * from saga WHERE current_sec = '971E7E1D-3DBB-48A2-9692-646B825A8560'
AND saga_state !=
'done' ORDER BY id ASC;
ERROR: query `SELECT * from saga WHERE current_sec = '971E7E1D-3DBB-48A2-9692-646B825A8560' AND saga_state !=
'done' ORDER BY id ASC` contains a full table/index scan which is explicitly disallowed
SQLSTATE: P0003
HINT: try overriding the `disallow_full_table_scans` cluster/session setting
```

It's not surprising that the query planner would choose to do a table scan here, since the table is empty, and sure enough:

```
root@127.0.0.1:32221/omicron> EXPLAIN SELECT * from saga WHERE current_sec = '971E7E1D-3DBB-48A2-9692-646B825A8560' AND saga_s
tate != 'done' ORDER BY id ASC;
     tree    |        field        |                                     description
-------------+---------------------+--------------------------------------------------------------------------------------
             | distribution        | local
             | vectorized          | false
  index join |                     |
   │         | table               | saga@primary
   └── scan  |                     |
             | estimated row count | 0
             | table               | saga@saga_current_sec_id_key (partial index)
             | spans               | [/'971e7e1d-3dbb-48a2-9692-646b825a8560' - /'971e7e1d-3dbb-48a2-9692-646b825a8560']
(8 rows)

Time: 53ms total (execution 1ms / network 53ms)
```

So I inserted 500-1000 records using:

```
seq 0 500 | while read i; do cockroach sql --url postgresql://root@127.0.0.1:32221/omicron?sslmode=disable -e "INSERT INTO Saga (id, creator, template_name, time_created, saga_params, saga_state, adopt_generation, adopt_time) VALUES ('$(uuidgen)', '$(uuidgen)', 'dummy-template', NOW(), '{}', 'bogus', 0, NOW())"; done
```

and sure enough I get a new plan that uses the index and I can run it even with disallow_full_table_scans:

```
root@127.0.0.1:32221/omicron> EXPLAIN SELECT * from saga WHERE current_sec = '971E7E1D-3DBB-48A2-9692-646B825A8560' AND saga_s
tate != 'done' ORDER BY id ASC;
     tree    |        field        |                                     description
-------------+---------------------+--------------------------------------------------------------------------------------
             | distribution        | local
             | vectorized          | false
  index join |                     |
   │         | table               | saga@primary
   └── scan  |                     |
             | estimated row count | 0
             | table               | saga@saga_current_sec_id_key (partial index)
             | spans               | [/'971e7e1d-3dbb-48a2-9692-646b825a8560' - /'971e7e1d-3dbb-48a2-9692-646b825a8560']
(8 rows)

Time: 53ms total (execution 1ms / network 53ms)

root@127.0.0.1:32221/omicron> show disallow_full_table_scans;
  disallow_full_table_scans
-----------------------------
  on
(1 row)

Time: 52ms total (execution 1ms / network 51ms)

root@127.0.0.1:32221/omicron> SELECT * from saga WHERE current_sec = '971E7E1D-3DBB-48A2-9692-646B825A8560' AND saga_state !=
'done' ORDER BY id ASC;
  id | creator | template_name | time_created | saga_params | saga_state | current_sec | adopt_generation | adopt_time
-----+---------+---------------+--------------+-------------+------------+-------------+------------------+-------------
(0 rows)

Time: 51ms total (execution 1ms / network 50ms)
```

More on this below, but the fact that this behavior depends on which plan the query planner chooses makes it a lot less useful for what we're trying to do.

**To Reproduce**

Set up a CockroachDB cluster with default configuration.

Use the above `CREATE TABLE` statements to set up the schema, then run the above `EXPLAIN` and observe the query plan.  (If you need the example where a query was disallowed, even when an index was available, let me know.)  Observe it doing a full scan.  You can do this again with the second example and observe it disallow the query.

**Expected behavior**

In the first case, given that CockroachDB chose a full scan, I expected it to disallow the query.  Instead, it executed the query.

Alternatively, if the expected behavior of `disallow_full_table_scans` is that it only disallows queries that can _only_ be completed with a full scan, then I expected my second query to _not_ produce an error. 

**Additional data / screenshots**

> If the problem is SQL-related, include a copy of the SQL query and the schema
> of the supporting tables.

See above.

**Environment:**

Server:

```
$ cockroach version
Build Tag:        v20.2.5
Build Time:       2021/03/17 21:00:51
Distribution:     OSS
Platform:         illumos amd64 (x86_64-pc-solaris2.11)
Go Version:       go1.16.2
C Compiler:       gcc 9.3.0
Build Commit ID:  162c5ac4968cf31c0ed54cd29aa8aeccd66247bb
Build Type:       release
```

Client: `cockroach sql`:

```
dap@zathras ~ $ cockroach version
Build Tag:        v20.2.5
Build Time:       2021/02/16 12:57:34
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin14)
Go Version:       go1.13.14
C Compiler:       4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build Commit ID:  162c5ac4968cf31c0ed54cd29aa8aeccd66247bb
Build Type:       release
```

**Additional context**

> Add any other context about the problem here.

Between these two examples, I can't tell what the exactly behavior of `disallow_full_table_scans` is _supposed_ to be.  Is it supposed to change nothing about the query plan and simply deny queries that get planned with a full scan?  If so, why did the first one work?  Or is it supposed to encourage the query planner to avoid a table scan and fail only if it couldn't?  If so, why did the second query get denied?

Our real goal is to avoid building our application using queries that will clearly require table scans as tables get large.  So it's tempting to set `disallow_full_table_scans=on` in the application.  That way, if we have good test coverage, we can have confidence that we're not going to run into scaling limitations due to table scans.  (Obviously, this isn't a substitute for actual scale testing, but anything we can do to catch this early in development would be a big help.)  I'm also excited by #67964, since that would allow us to set this only on tables that we know will be large.

But it doesn't seem like this will work.  Because `disallow_full_table_scans=on` disallows queries for which the planner _happens_ to have chosen a table scan, not just those that _require_ a table scan, it produces false positives any time a table is small.

Thanks for reading this far.  If there's a better way to achieve what we're trying to do, please let me know!

### PR DESCRIPTION
**Pull request by rytaft**
**sql: partial index scans are exempt from `disallow_full_table_scans`**

Release note (sql change): Fixed an oversight in which a full scan of a
partial index could be rejected due to the `disallow_full_table_scans`
setting. Full scans of partial indexes will no longer be rejected if
`disallow_full_table_scans` is true, since a full scan of a partial index
must be a constrained scan of the table.

**opt: update coster to avoid full scans with `disallow_full_table_scans`**

Updated the coster so that full table scans and full scans of non-partial
indexes are given a "huge cost" if `disallow_full_table_scans` is true and
stats are unavailable or the estimated row count is greater than
`large_full_scan_rows`. Since disallow_full_table_scans and
`large_full_scan_rows` can now affect the chosen plan, the optimizer now tracks
these settings in the memo to ensure cached plans are not stale.

Fixes #70795

Release note (sql change): The optimizer has been updated so that if
`disallow_full_table_scans` is true, it will never plan a full table scan with 
an estimated row count greater than `large_full_scan_rows`. If no alternative
plan is possible, an error will be returned, just as it was before. However,
cases where an alternative plan is possible will no longer produce an error,
since the alternative plan will be chosen. As a result, users should see
fewer errors due to `disallow_full_table_scans`.

A side effect of this change is that if `disallow_full_table_scans` is set along
with statement-level hints such as an index hint, the optimizer will try to
avoid a full scan while also respecting the index hint. If this is not
possible, the optimizer will return an error and might not log the attempted
full table scan or update the `sql.guardrails.full_scan_rejected.count` metric.
If no index hint is used, the full scan will be logged and the metric updated.

**opt,sql: support hint to disallow full scan**

Release note (sql change): Added support for a new index hint,
`NO_FULL_SCAN`, which will prevent the optimizer from planning a
full scan for the specified table. The hint can be used in the
same way as other existing index hints. For example,
`SELECT * FROM table_name@{NO_FULL_SCAN};`. Note that a full scan
of a partial index may still be planned, unless `NO_FULL_SCAN` is
forced in combination with a specific partial index via
`FORCE_INDEX=index_name`.

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
Nice, I love to see this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-MlV_0gD2hR4n0CXLUjY:b4gfdof)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @RaduBerinde)

**Review by mgartner — CHANGES_REQUESTED** [review]
Reviewed just the first commit for now.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-MlWFLFu8i-d8iMeaT1e:b-spfttj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @RaduBerinde, and @rytaft)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWETSz-ybvH8Y_dCWe):*
I brought this up when `disallow_full_table_scans` was added and AFAIK this was intentional. @arulajmani Do you remember why we made the decision to have `disallow_full_table_scans` prevent full scans on partial indexes?
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2804 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWF6wh0klKYfLva7pj:-MlWF6wh0klKYfLva7pk:b-cgg449) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c46982983ac2859f98cd3a469c23f11810a1922/docs/generated/sql/bnf/stmt_block.bnf#L2804)):*
> ```
> 	| 'NO_INDEX_JOIN'
> 	| 'NO_ZIGZAG_JOIN'
> 	| 'NO_FULL_SCAN'
> ```

nit: seems like this change should not be in the first commit?
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWF-YD6a2Ymu93W8hF:-MlWF-YD6a2Ymu93W8hG:b-l30ax6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c46982983ac2859f98cd3a469c23f11810a1922/pkg/sql/opt/exec/execbuilder/relational.go#L673)):*
> ```Go
> 	// Save if we planned a full table/index scan on the builder so that the
> 	// planner can be made aware later. We only do this for non-virtual tables.
> 	if !tab.IsVirtualTable() && isUnfiltered {
> ```

nit: assignment to a variable seems unnecessary

**Review by rytaft — COMMENTED** [review]
TFTR! The other commits are RFAL now too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-MlWLmJB5LXlkgTLiQUS:b-w2vl6m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @mgartner, @michae2, and @RaduBerinde)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWETSz-ybvH8Y_dCWe):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I brought this up when `disallow_full_table_scans` was added and AFAIK this was intentional. @arulajmani Do you remember why we made the decision to have `disallow_full_table_scans` prevent full scans on partial indexes?
</blockquote></details>

Maybe it was intentional, but it seems very suboptimal to me -- why should a full scan on `INDEX (b) WHERE b > 0` fail while a constrained scan of `INDEX (b)` succeeds?
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2804 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWF6wh0klKYfLva7pj:-MlWKjLfEwHyz7VXPQ2o:btfa7qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c46982983ac2859f98cd3a469c23f11810a1922/docs/generated/sql/bnf/stmt_block.bnf#L2804)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: seems like this change should not be in the first commit?
</blockquote></details>

Oops good catch. Fixed
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWF-YD6a2Ymu93W8hF:-MlWJ7cX4FYmYSqz1qMJ:b81mprc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c46982983ac2859f98cd3a469c23f11810a1922/pkg/sql/opt/exec/execbuilder/relational.go#L673)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: assignment to a variable seems unnecessary
</blockquote></details>

The variable is used again in a later commit

**Review by michae2 — APPROVED** [review]
This is great! :lgtm_strong: I think many people will be really happy with this!

> Reviewed 5 of 8 files at r1, 15 of 15 files at r6, 8 of 8 files at r7, 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-MlX90n-7OV71dsHkKEB:bltclkp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 665 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlX73N_8JKGbA7isFsp:-MlX73N_8JKGbA7isFsq:bdu1jdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed1e6bc8fe05cfb99793d6e637a6f762363640c/pkg/sql/opt/exec/execbuilder/relational.go#L665)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		// Normally a full scan of a partial index would be allowed with the
> 		// NO_FULL_SCAN hint (isUnfiltered is false for partial indexes), but if the
> 		// user has explicitly forced the partial index *and* used NO_FULL_SCAN, we
> 		// disallow the full index scan.
> ```
</details>


Just clarifying: is this because forcing the partial index without a matching predicate could lead to a full scan of the partial index plus a constrained scan of another index to include the rows not in the partial index? And that wouldn't be detected as a full scan?

**Review by RaduBerinde — COMMENTED** [review]
Nice, this will be useful! :lgtm:

Could you add some tests with `UPDATE` and `DELETE`? (we can have a filter like `k IN (...)` where the list is significantly larger than the table size - this kind of query would otherwise do a full table scan. There are some existing tests with hints in execbuilder/testdata/update and delete

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-MlXOCFGCZ5WU9e4Lbci:bott610)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @arulajmani and @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r6, 8 of 8 files at r7, 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-Mlje2gTAt7_R0_Q2OhU:bg7igkv)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWETSz-ybvH8Y_dCWe):*
I agree with you on this, just wanted to bring it to your attention. I searched for anything we wrote down about this decision but didn't find anything. My guess is that we just used the same logic from the `sql.log.slow_query.experimental_full_table_scans.enabled] setting added [here](https://github.com/cockroachdb/cockroach/commit/1349017629eba3084cd8c0fd84bef343101bad60). 

[Tthe docs](https://www.cockroachlabs.com/docs/v21.1/set-vars) say this about `disallow_full_table_scans`:

> If set to on, all queries that have planned a full table or full secondary index scan will return an error message. This setting does not apply to internal queries, which may plan full table or index scans without checking the session variable.

Maybe we should clarify `full non-partial secondary index scan`?
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWF-YD6a2Ymu93W8hF:-MljYcm58S8YQ7jvy6Io:b5jnckt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c46982983ac2859f98cd3a469c23f11810a1922/pkg/sql/opt/exec/execbuilder/relational.go#L673)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The variable is used again in a later commit
</blockquote></details>

Oops, sorry.

**Review by rytaft — COMMENTED** [review]
TFTRs!

> Could you add some tests with UPDATE and DELETE?

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-Mll-Uef3ziOC157W3rL:b-xpsyor)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @mgartner, @michae2, and @stbof)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWETSz-ybvH8Y_dCWe):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I agree with you on this, just wanted to bring it to your attention. I searched for anything we wrote down about this decision but didn't find anything. My guess is that we just used the same logic from the `sql.log.slow_query.experimental_full_table_scans.enabled] setting added [here](https://github.com/cockroachdb/cockroach/commit/1349017629eba3084cd8c0fd84bef343101bad60). 

[Tthe docs](https://www.cockroachlabs.com/docs/v21.1/set-vars) say this about `disallow_full_table_scans`:

> If set to on, all queries that have planned a full table or full secondary index scan will return an error message. This setting does not apply to internal queries, which may plan full table or index scans without checking the session variable.

Maybe we should clarify `full non-partial secondary index scan`?
</blockquote></details>

Good call. I assume this will get picked up from the release note, but cc @stbof for awareness that the docs on `disallow_full_table_scans` will need an update.
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 665 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlX73N_8JKGbA7isFsp:-MlkyDgP9eHz_jmTQFdW:b-hclc2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed1e6bc8fe05cfb99793d6e637a6f762363640c/pkg/sql/opt/exec/execbuilder/relational.go#L665)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 		// Normally a full scan of a partial index would be allowed with the
> 		// NO_FULL_SCAN hint (isUnfiltered is false for partial indexes), but if the
> 		// user has explicitly forced the partial index *and* used NO_FULL_SCAN, we
> 		// disallow the full index scan.
> ```

Just clarifying: is this because forcing the partial index without a matching predicate could lead to a full scan of the partial index plus a constrained scan of another index to include the rows not in the partial index? And that wouldn't be detected as a full scan?
</blockquote></details>

Forcing the partial index without a matching predicate would fail with an error "index "index_name" is a partial index that does not contain all the rows needed to execute this query".

I just added this exception because I've seen examples from customer queries where CRDB was performing a full scan of the partial index when it really could have constrained it further. For example, if we have a partial index `index (a) where a > 0` and a predicate `a = 1`, we should be able to use the partial index and constrain it to `a: [/1 - /1]`. This exception will allow us to hint more precisely in cases like this.

It also just seems intuitive that if you're using `NO_FULL_SCAN` with a specific index, you really want to avoid a full scan of that index.

Does this help clarify?

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @mgartner, @michae2, and @stbof)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 665 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlX73N_8JKGbA7isFsp:-Mll5scE1YimExDS_upe:b-wtkc5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed1e6bc8fe05cfb99793d6e637a6f762363640c/pkg/sql/opt/exec/execbuilder/relational.go#L665)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Forcing the partial index without a matching predicate would fail with an error "index "index_name" is a partial index that does not contain all the rows needed to execute this query".

I just added this exception because I've seen examples from customer queries where CRDB was performing a full scan of the partial index when it really could have constrained it further. For example, if we have a partial index `index (a) where a > 0` and a predicate `a = 1`, we should be able to use the partial index and constrain it to `a: [/1 - /1]`. This exception will allow us to hint more precisely in cases like this.

It also just seems intuitive that if you're using `NO_FULL_SCAN` with a specific index, you really want to avoid a full scan of that index.

Does this help clarify?
</blockquote></details>

Yes, thank you!

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-:-MllOJZG2owdbHyRNtWg:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @mgartner, @michae2, and @stbof)

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71317)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71317#-MlWETSz-ybvH8Y_dCWe):*
> @arulajmani Do you remember why we made the decision to have disallow_full_table_scans prevent full scans on partial indexes?

Just catching up on my mentions. I can't remember exactly how we ended up on this behaviour, but I think we were concerned about an unbounded partial index scan. This was probably the wrong way of looking at things now that I see the example Becca illustrated above so happy for things to change here!

**Comment by RaduBerinde** [comment]
Adding `docs-todo` label - we need to document `NO_FULL_SCAN` in https://www.cockroachlabs.com/docs/v21.2/table-expressions#force-index-selection

**Comment by stbof** [comment]
There is a docs ticket for this: https://github.com/cockroachdb/docs/issues/12279

**Pull request merged**
