### PR TITLE
base: use separate lease duration for liveness range

### PR DESCRIPTION
**Pull request by erikgrinaker**
The first few commits are from #91947, only the last commit should be reviewed here.

---

This patch adds a separate lease duration for the liveness range. When the liveness range leaseholder is lost, other nodes are unable to heartbeat and extend their leases, which can lead to the loss of most leases in the system. Shortening the liveness lease duration shortens the period of unavailability for other leases.

Release note (ops change): The duration of the liveness range lease has been reduced to 2.5s, half of the regular lease duration. When the liveness range leaseholder is lost (e.g. due to an infrastructure outage), other nodes are unable to heartbeat and thus extend their own leases, which can lead to the loss of many of the leases throughtout the cluster. Reducing the liveness lease duration reduces the period of unavailability.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@tbg I've been playing around with a few different setting here, testing with `failover/liveness/crash`:

| Lease | Liveness lease | Lost leases | pMax |
|-------|----------------|-------------|------|
| 9.0s  | 9.0s           | 96%         | 9.7s |
| 9.0s  | 3.0s           | 40%         | 2.3s |
| 5.0s  | 5.0s           | 46%         | 7.5s |
| 5.0s  | 2.5s           | 5%          | 2.4s |

(the "Lost leases" metric is unreliable due to the time series sampling resolution)

Even with the "old" leases of 9.0s, I had to drop the liveness lease all the way down to 3.0s to get a significant improvement, and I was still unable to eliminate the effect. It seems like regardless of whether we reduce the standard lease durations in #91947, we'll still have a large blast radius on the liveness range leaseholder, but reducing the liveness lease does improve things in both cases. This will likely be far worse in the case of a network outage, where the network timeouts also come into play.

I'm not really comfortable reducing it this far down -- it's pretty tight, and the write latency of the extension can't exceed 1s before we start having issues due to the stasis period. I think we should consider alternative approaches to coalesced lease extensions that don't have single points of failure, as part of the lease protocol improvements we're exploring.

Would be interested to get your take here.

**Comment by tbg** [comment]
Ran a tiny experiment:

```diff
diff --git a/pkg/kv/kvserver/replica_proposal.go b/pkg/kv/kvserver/replica_proposal.go
index 1e3fdf6f89..52fcc49f23 100644
--- a/pkg/kv/kvserver/replica_proposal.go
+++ b/pkg/kv/kvserver/replica_proposal.go
@@ -266,6 +266,13 @@ func (r *Replica) leasePostApplyLocked(
 		// Log lease acquisitions loudly when verbose logging is enabled or when the
 		// new leaseholder is draining, in which case it should be shedding leases.
 		// Otherwise, log a trace event.
+		if prevExp, newPropTS := prevLease.GetExpiration(), newLease.ProposedTS.ToTimestamp(); prevExp.IsSet() && prevExp.Less(newPropTS) {
+			log.Warningf(ctx,
+				"new range lease %s following %s (downtime at least %.2fs, previous expired at %s, acquisition started at %s)",
+				newLease, prevLease, time.Duration(newPropTS.WallTime-prevExp.WallTime).Seconds(),
+				time.Unix(0, prevExp.WallTime), time.Unix(0, newPropTS.WallTime))
+		}
+
 		if log.V(1) || r.store.IsDraining() {
 			log.Infof(ctx, "new range lease %s following %s", newLease, prevLease)
 		} else {

```

Start local 3 node cluster, wait for things to settle, bring down the leaseholder, grab the log message.

> I221206 13:44:38.077957 319 kv/kvserver/replica_proposal.go:270 ⋮ [n1,s1,r2/1:‹/System/NodeLiveness{-Max}›,raft] 584  new range lease repl=(n1,s1):1 seq=6 start=1670334275.261080000,1 exp=1670334287.067535000,0 pro=1670334278.067535000,0 following repl=(n3,s3):2 seq=5 start=1670334239.716025000,1 exp=1670334275.261080000,0 pro=1670334266.261080000,0 (downtime at least 2.81s, previous expired at 2022-12-06 14:44:35.26108 +0100 CET, acquisition started at 2022-12-06 14:44:38.067535 +0100 CET)

So it took 2.81s *post the expiration of the lease* until we started proposing the new lease.

I had finished killing the old leaseholder at `t0=14:44:28`. We had to wait until `14:44:35 (t0+7s)` due to the expiration, but since we heartbeat every 4.5s there were two heartbeats waiting to be served at that point in time. And yet, we spent another 2.81s doing nothing.

Maybe something in this experiment is broken because I'm not isolating the liveness range (and so there are more leases lost than just liveness). Still, I wonder if we can run with this diff in your liveness-isolated test once or twice to see what outputs we get. Ideally, the number reported by this test for the "min downtime" should be ~0 as we ought to be acquiring the lease non-cooperatively the very instant this is possible. If we find that this is not happening, this is worth looking into.

If this peters out - I agree that we may not be able to fix this problem sufficiently by moving towards lower lease liveness expirations, and I share your concern about being too aggressive in lowering them. It may then make sense to postpone attacking this issue.

**Comment by erikgrinaker** [comment]
>So it took 2.81s post the expiration of the lease until we started proposing the new lease.

I suspect this is because we have to wait for a heartbeat message to come it, and they're fairly rare at 4.5s. But yeah, I can rerun an experiment with this.

**Comment by tbg** [comment]
> I suspect this is because we have to wait for a heartbeat request to come in,

We already waited 7s until that point, and definitely lost the leader during these 7s, so there ought to be 2 of them (one for each remaining node) already queued.

**Comment by erikgrinaker** [comment]
Yeah, but they have timeouts, so maybe they timed out and then had to wait for the next one to fire. I'll have a closer look.

**Comment by erikgrinaker** [comment]
Did some runs with `failover/liveness/crash` on top of this PR, looks like the delay is caused by the Raft election. Here's one particularly long lease acquisition at 2.9 seconds:

```
W221209 16:58:09.087724 [n2,s2,r2/3:‹/System/NodeLiveness{-Max}›,raft] new range lease repl=(n2,s2):3 seq=7 start=1670605086.189420895,1 exp=1670605091.586130392,0 pro=1670605089.086130392,0 following repl=(n4,s4):4 seq=6 start=1670605057.668047498,0 exp=1670605086.189420895,0 pro=1670605083.689420895,0 (downtime at least 2.90s, previous expired at 2022-12-09 16:58:06.189420895 +0000 UTC, acquisition started at 2022-12-09 16:58:09.086130392 +0000 UTC)
```

Notice how the lease expired at 16:58:06, and was reacquired at 16:58:09. I cross-referenced this with liveness heartbeat requests on n2 attempting to acquire leases, and see a bunch of these continually between 16:58:06 and 16:58:09:

```
W221209 16:58:08.667060 kv/kvserver/replica_send.go:827 ⋮ [n2,s2,r2/3:‹/System/NodeLiveness{-Max}›] invalid lease for request ConditionalPut [/System/NodeLiveness/1,/Min), EndTxn(commit modified-span (node-liveness)) [/System/NodeLiveness/1], [txn: f1ff8912], [can-forward-ts] at 1670605088.664223743,0
W221209 16:58:08.667687 kv/kvserver/replica_send.go:833 ⋮ [n2,s2,r2/3:‹/System/NodeLiveness{-Max}›] lease response: status={<empty> 0,0 0,0 ‹ERROR› ‹› ‹liveness(nid:0 epo:0 exp:0,0)› 0,0} pErr=‹[NotLeaseHolderError] refusing to acquire lease on follower; r2: replica (n2,s2):3 not lease holder; current lease is repl=(n4,s4):4 seq=0 start=0,0 exp=<nil>›
```

That last error comes from here:

https://github.com/cockroachdb/cockroach/blob/6ed91486435892122ba1fb9f1bc64cc339f160c3/pkg/kv/kvserver/replica_proposal_buf.go#L1252-L1269

Which originates while we're proposing the lease transfer, and is rejected because we're not the Raft leader:

https://github.com/cockroachdb/cockroach/blob/6ed91486435892122ba1fb9f1bc64cc339f160c3/pkg/kv/kvserver/replica_proposal_buf.go#L614-L627

So in order to make this work reliably we'll have to drop the Raft election timeout well below the lease expiration, maybe something like 1s consider it's randomized by a 1-2x factor, and that really isn't going to work very well.

I think we'll have to consider other approaches here.

**Pull request closed without merging**
