### PR TITLE
storage: Avoid nil pointer dereference in tickRaftMuLocked

### LINKED ISSUE #11610: stability: segfault in raft/rawnode
`blue` crashed on segfault in raft:
sha: 07705f2
node: `40.123.43.229`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10389f3]

goroutine 98 [running]:
panic(0x1759dc0, 0xc420018040)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420388120)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x1759dc0, 0xc420018040)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).ReportUnreachable(0x0, 0x3)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:243 +0x83
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tickRaftMuLocked(0xc434197800, 0x1aa9100, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2533 +0x14f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tick(0xc434197800, 0xc420471b00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2519 +0x85
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processTick(0xc420898700, 0x1bd2, 0xc439eadf00)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3268 +0xfb
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42095a000, 0xc420388120)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:225 +0x2b6
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420388120, 0xc420e7cd60)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

This looks like @petermattis's build, but this comes after the vendoring change, apparently with an update to raft.

### PR DESCRIPTION
**Pull request by a-robinson**
FIxes #11610

@mberhault @arjunravinarayan

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11622)

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11622#-:-KXTpiU8e-UabUoIuteT:bnfp4nl)*

**Comment by mberhault** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 2543 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11622#-KXX5Kh1bmpXMDal1E7h:-KXX5Kh1bmpXMDal1E7i:bcxduwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e589204513d7210d147fa2dedc527246b549376/pkg/storage/replica.go#L2543)):*
> ```Go
> 	if r.mu.internalRaftGroup == nil {
> 		return false, nil
> 	}
> ```

Should this check occur after we set `Replica.unreachablesMu.remotes` to `nil`? That field should only be non-nil if we have a Raft group. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11622)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 2543 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11622#-KXX5Kh1bmpXMDal1E7h:-KXb30K5di5Gkmj5UhgJ:bgzcg3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e589204513d7210d147fa2dedc527246b549376/pkg/storage/replica.go#L2543)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Should this check occur after we set `Replica.unreachablesMu.remotes` to `nil`? That field should only be non-nil if we have a Raft group. 
</details>
I'm not very familiar with this code, but shouldn't that field already be nil if the internalRaftGroup is nil (and thus the replica hasn't yet been initialized)?

Also, if it is possible to have unreachable remotes without an internal raft group, it seems as though it may be better to wait to record them than to forget about them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11622)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 2543 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11622#-KXX5Kh1bmpXMDal1E7h:-KXf6lPrxTZxoBcxmvXZ:bz1y5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e589204513d7210d147fa2dedc527246b549376/pkg/storage/replica.go#L2543)):*
Yes, `unreachablesMu.remotes` should be nil if `internalRaftGroup` is nil, but clearly it isn't because of of the nil-pointer dereference this PR is fixing. I'm actually not quite sure how this nil-pointer dereference happened. The current node must have been the Raft leader in order to send the heartbeat. Then, before the heartbeat determined the remote was unreachable, the leadership must have been transferred to another node and then this replica was removed from the Raft group (i.e. `Store.RemoveReplica` was called). 

> unreachable remotes without an internal raft group

No, it isn't possible. Only the Raft leader sends heartbeats and in order for there to be a Raft leader there needs to be a Raft group.

> it seems as though it may be better to wait to record them than to forget about them?

My preference is to lean in the other direction and clear this state. If the remotes are still unreachable when this node becomes a leader again, it will quickly discover that by sending a heartbeat. Given the above scenario, this replica is unlikely to become the leader again as it was probably removed from the Raft group. We might want to clear `unreachablesMu.remotes` in `Store.RemoveReplica`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11622)*

**Pull request merged**
