### PR TITLE
storage, server: assorted cleanups around server startup and cluster bootstrap

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

These are all minor. I'm trying to somehow get server creation to only happen after a node id is known, but I'm getting a bit discouraged cause everything is tangled.

### CODE REVIEW

**Comment by andreimatei** [comment]
@petermattis you said you like cleanups; here's some more.
r1 and r2 are in another PR.

**Review by petermattis — COMMENTED** [review]
:lgtm: though I only looked at `r3` through `r9`. I do like these cleanups. In particular, the cleanup of `bootstrapCluster` is very nice. 

The commit message for `r4` is classic Andrei. Worth a read for any bystanders. 

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 8 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-:-LW89QRx6OW8grazDbTY:b5zyyt3)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/server/node.go, line 202 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW89fQTDK0Zu7UGHvyG:-LW89fQU9ky7bP94O1L8:buuyjjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L202)):*
> ```Go
> // ranges cannot be accessed by KV in regular means until the node liveness is
> // written, since epoch-based leases cannot be granted until then.
> // All other engines are initialized with their StoreIdent. These identities
> ```

For consistency, put a blank line between paragraphs (i.e. before this line).
___
*[pkg/server/node.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW89v5V9p7q_sQAVKBl:-LW89v5V9p7q_sQAVKBm:b-ddyauq) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L261)):*
> ```Go
> 		}
> 
> 		// Initialize store with the store ident and cluster version.
> ```

You're initializing the engine, not the store, right? Perhaps `Initialize the engine backing the store with the store ident and cluster version`.
___
*[pkg/server/node.go, line 290 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW8AeO10LAcAUeL0Bfr:-LW8AeO10LAcAUeL0Bfs:b9fg4ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L290)):*
> ```Go
> 			}
> 		}
> 		if err := s.Start(ctx, stopper); err != nil {
> ```

What? We don't need to start the `Store` anymore? This was always a super annoying wart.
___
*[pkg/server/node.go, line 262 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW8Auc28ZssVwGgf2HM:-LW8Auc37rQFEBhZs7ok:b2y0sv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ad830379862fb496361250bef0bbe2bab3d9c/pkg/server/node.go#L262)):*
> ```Go
> 			// a cluster (except in some tests that specifically want to set up
> 			// an "old-looking" cluster).
> 			if err := s.WriteInitialData(
> ```

Perhaps `WriteInitialData` should be a top-level function in `storage` and not a method on `Store`. It uses almost nothing in the `Store` itself other than the engine and the config, which you passed in when you created the store above. 

Update: smart minds think alike. I see that you did exactly this in the next commit. 
___
*[pkg/storage/store.go, line 2011 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW8BgjB8bbfh4FjAQ5K:-LW8BgjB8bbfh4FjAQ5L:boxknvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cecdf8a08dbb11ba8ec9e4b0979b5169bdf572b6/pkg/storage/store.go#L2011)):*
> ```Go
> }
> 
> // WriteInitialClusterDataToEngine writes bootstrapping data to an engine. It
> ```

Nit: I would name this function `WriteInitialClusterData`. The `ToEngine` suffix is a little bit redundant with the engine parameter, IMO.

**Review by tbg — APPROVED** [review]
:lgtm: very nice. I also didn't look at r1 and r2 in this PR.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 8 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, 1 of 1 files at r7, 12 of 12 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-:-LWBMD2tAx95XuSN56zT:b-vuqsq1)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/server/node.go, line 205 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LWBIYVG9xNE0Xr81dcy:-LWBIYVG9xNE0Xr81dcz:b-1zw28q) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L205)):*
> mechanisms

Why do you need to do anything with the other engines?

**Review by andreimatei — COMMENTED** [review]
I've remove the first commits (which are #33653), as they need more attention.
I'm gonna merge after the 19.1 branch is cut.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-:-La8qG3602evpbpQX80D:b-e270sj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @petermattis and @tbg)

___
*[pkg/server/node.go, line 202 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW89fQTDK0Zu7UGHvyG:-La8Vff57AxX-Gp12LMn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L202)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

For consistency, put a blank line between paragraphs (i.e. before this line).
</blockquote></details>

Done.
___
*[pkg/server/node.go, line 205 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LWBIYVG9xNE0Xr81dcy:-La8Yi09CRcouu-PqZmw:b-gjyzrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L205)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> mechanisms

Why do you need to do anything with the other engines?
</blockquote></details>

I'm just documenting crap, not doing anything new.
I guess the reason why this method deals with engines other than the first is because the code is written such that the thing that writes the initial state of the first engine already allocates ids for all the engines.
And I was trying to put some apologist explanation here, but now thinking about it I don't think it computes. I've deleted it and put a TODO about making this function only deal with the first engine.
___
*[pkg/server/node.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW89v5V9p7q_sQAVKBl:-La8WjHVDFcK59cAaMEb:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L261)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You're initializing the engine, not the store, right? Perhaps `Initialize the engine backing the store with the store ident and cluster version`.
</blockquote></details>

done
___
*[pkg/server/node.go, line 290 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW8AeO10LAcAUeL0Bfr:-La8brP40kZi_qjLWj_2:bb7pv6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/61f7316ac6fa6ce84e69e8ea9481bcf22e146bf7/pkg/server/node.go#L290)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What? We don't need to start the `Store` anymore? This was always a super annoying wart.
</blockquote></details>

w00t
___
*[pkg/server/node.go, line 262 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW8Auc28ZssVwGgf2HM:-La8WADp4SXETur5k2v_:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ad830379862fb496361250bef0bbe2bab3d9c/pkg/server/node.go#L262)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps `WriteInitialData` should be a top-level function in `storage` and not a method on `Store`. It uses almost nothing in the `Store` itself other than the engine and the config, which you passed in when you created the store above. 

Update: smart minds think alike. I see that you did exactly this in the next commit. 
</blockquote></details>

:)
___
*[pkg/storage/store.go, line 2011 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-LW8BgjB8bbfh4FjAQ5K:-La8kazQ1rQiKSgsNatu:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cecdf8a08dbb11ba8ec9e4b0979b5169bdf572b6/pkg/storage/store.go#L2011)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: I would name this function `WriteInitialClusterData`. The `ToEngine` suffix is a little bit redundant with the engine parameter, IMO.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33691#-:-LaIAn60Cf0mpgbxxmtq:b-slrpgb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @petermattis and @tbg)

**Comment by tbg** [comment]
bors r+

FTFY

**Pull request merged**
