### PR TITLE
opt: include ENV information in statement bundles

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: refactor EXPLAIN(OPT,ENV) code

This change factors to most of the EXPLAIN(OPT,ENV) code into a helper, to be
used for EXPLAIN BUNDLE. The only functional difference is that we no longer
use the same transaction to issue the environment queries.

Release note: None

#### opt: include ENV information in statement bundles

This change adds the "env" part of `EXPLAIN (OPT,ENV)` to the
statement diagnostics bundle. The data is split among multiple files:
 - `env.sql` - contains version information and session settings
 - `schema.sql` - contains schema information
 - `stats-<tableName>.sql` - contains statistics, one file per table

Release note (sql change): the statement diagnostics bundle now
contains all the information in EXPLAIN (OPT,ENV).

Release justification: fix for new functionality.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-:-M3BxiUvB33UZRoj9XIf:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/conn_executor_exec.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-M3Btnc_83K6U4wu_gIx:-M3Btnc_83K6U4wu_gIy:b-eyi6w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/727963ed763b52045ccba2641464a8cc776c6d86/pkg/sql/conn_executor_exec.go#L229)):*
> ```Go
> 			trace := tracing.GetRecording(sp)
> 			ctx := origCtx
> 			db := ex.server.cfg.DB
> ```

[nit] looks like you can also move this down into the if block
___
*[pkg/sql/explain_bundle.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-M3BurYeENSVYK7OdS64:-M3BurYeENSVYK7OdS65:b-c7hkv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/727963ed763b52045ccba2641464a8cc776c6d86/pkg/sql/explain_bundle.go#L308)):*
> ```Go
> 
> 	first := true
> 	blank := func() {
> ```

[nit] I think `blank_line` would be clearer
___
*[pkg/sql/opt_exec_factory.go, line 1004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-M3Bruai53zcXQXwzDyL:-M3Bruai53zcXQXwzDyM:b-37qkw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/60287ea886482e87408912926600b3f692fa9484/pkg/sql/opt_exec_factory.go#L1004)):*
> ```Go
> 		// NOTE: The histogram buckets take up a ton of vertical space and we
> 		// don't use them in planning, so don't include them.
> 		// TODO(justin): Revisit this once we use histograms in planning.
> ```

While you're making changes, this comment can be updated

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-:-M3C9Q0D4GMa8i8NKHlT:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @rytaft)

___
*[pkg/sql/conn_executor_exec.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-M3Btnc_83K6U4wu_gIx:-M3C8Eoj6Hm6HixhcmNn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/727963ed763b52045ccba2641464a8cc776c6d86/pkg/sql/conn_executor_exec.go#L229)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] looks like you can also move this down into the if block
</blockquote></details>

Done.
___
*[pkg/sql/explain_bundle.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-M3BurYeENSVYK7OdS64:-M3C8RZv4BWt8qGeotL1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/727963ed763b52045ccba2641464a8cc776c6d86/pkg/sql/explain_bundle.go#L308)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I think `blank_line` would be clearer
</blockquote></details>

Done.
___
*[pkg/sql/opt_exec_factory.go, line 1004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46441#-M3Bruai53zcXQXwzDyL:-M3C8j0k5FWMFRHkX8Zu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60287ea886482e87408912926600b3f692fa9484/pkg/sql/opt_exec_factory.go#L1004)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

While you're making changes, this comment can be updated
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 7 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46441)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

**Pull request merged**
