### PR TITLE
Added latency stats to chaos test

### PR DESCRIPTION
**Pull request by vivekmenezes**
Retry verifying database data.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4246)

### CODE REVIEW

**Comment by tschottdorf** [comment]
I'm not really sure what you're measuring there. Most of the time the cluster is recovering, and it looks like the time spent waiting for locks doesn't count, so you're like... measuring non-recovery latency in a test which almost always is in recovery mode? Maybe add a comment if I'm missing the point.
What does the log output look like?

**Comment by vivekmenezes** [comment]
It prints a histogram like:

Histogram (unit: ms)
Count: 791  Min: 1  Max: 3559  Avg: 13.90
------------------------------------------------------------
[   1,    2)   55    7.0%    7.0%  #
[   2,    3)  250   31.6%   38.6%  ###
[   3,    5)  299   37.8%   76.4%  ####
[   5,   10)  121   15.3%   91.7%  ##
[  10,   18)   53    6.7%   98.4%  #
[  18,   33)    4    0.5%   98.9%  
[  33,   59)    4    0.5%   99.4%  
[  59,  104)    2    0.3%   99.6%  
[ 104,  182)    0    0.0%   99.6%  
[ 182,  317)    0    0.0%   99.6%  
[ 317,  550)    0    0.0%   99.6%  
[ 550,  951)    0    0.0%   99.6%  
[ 951, 1644)    0    0.0%   99.6%  
[1644, 2839)    2    0.3%   99.9%  
[2839, 4901)    1    0.1%  100.0%  
[4901, 8458)    0    0.0%  100.0%  
[8458,  inf)    0    0.0%  100.0%  

There is the question of why do some queries take a lot of time. 

I also think there is no value in shutting down a majority of the nodes in this test. Should I change it to only shutdown a single node at a time so that it is more realistic?

**Comment by tschottdorf** [comment]
I wrote the test specifically with this case in mind - cluster failure is something that does happen in the wild, and recovery should be smooth. If you're removing that part, the test has lost my original intent. You could separate out the chaos monkey part and parametrize so that it can run the original chaos test and something you want (a "yellow cluster test"), and put those into different tests.

I'm still not convinced the measurements here make sense (on a freshly restarted node, you could be waiting for Raft elections, and it isn't really interesting that in the first second of a node starting its latencies are worse than during normal operation - somewhat expected, with all caches blank and things just starting up). What would be interesting is the time-to-recovery histogram (i.e. the time until the cluster at least "yellow" again, whatever that means (for now, it could mean having one client that makes progress).

**Comment by vivekmenezes** [comment]
Okay. I think it probably makes sense to at least rename the test from
chaos to cluster_failure_test. I'll send out a refactoring PR to take the
chaos monkey out so that it can be used elsewhere with different parameters.

I'll close this PR for now.

**Comment by tschottdorf** [comment]
Sounds good, thanks.

**Comment by tschottdorf** [comment]
(I'll close since your comment indicates that that's the desired state for now).

**Pull request closed without merging**
