### PR TITLE
ui: modify statements and transactions pages to use the TimeScaleDropdown component

### LINKED ISSUE #70997: UX updates to statement/transaction time picker and 'Clear SQL stats' button
Logging a couple of improvements to the statement/transaction time picker and 'Clear SQL stats' button ([Figma Designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3486%3A76244))

Screen Shot 2021-10-01 at 12 49 54 PM

- Introduce previous/next arrows to make it easier to navigate quickly to past time ranges (following the same functionality as the DB console metrics page time picker arrows)
- Replace 'reset time' link with 'Now' button (again same behavior as DB console metrics page time picker. 'Now' button would always be visible). See [designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3486%3A76476) for more details on behaviors.  
- Move 'Clear SQL stats' button next to time picker controls, and use underline tooltip treatment

### PR DESCRIPTION
**Pull request by jocrl**
Resolves https://github.com/cockroachdb/cockroach/issues/70997

This commit modifies the Statements and Transactions pages in DB Console
and CC Console to use the TimeScaleDropdown component that is currently
used in the Metrics page.

Release note (ui change): The time pickers on the Statements and
Transactions pages now have the same style and functionality as the
time picker on the Metrics page.

Previously:
image

Now:
image

### CODE REVIEW

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageConnected.tsx, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqPypkI03jqPCXHJVR3:-MqPypkI03jqPCXHJVR4:b-qf80pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2559c4bc20384845d230cb3d6db770ddb4fab3a2/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageConnected.tsx#L72)):*
> ```
>           sqlStatsActions.updateDateRange({
>             start: start.unix(),
>             end: end.unix(),
> ```
The prior implementation stored start and end dates in UNIX format. I am instead implicitly storing windowEnd in UTC format, due to the default serialization of `moment.Moment`. I only convert to UNIX (ultimately to `Long`) when making the request. The implicit format feels weird, but is consistent with what the Metrics page currently does for its time picker.
___
*[pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqPySm12nnVMQfBqfAB:-MqPySm12nnVMQfBqfAC:bsylgpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2559c4bc20384845d230cb3d6db770ddb4fab3a2/pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L51)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> const defaultDateRange: StatementsDateRangeState = {
>   start: moment
>     .utc()
>     .subtract(1, "hours")
>     .unix(),
>   end: moment.utc().unix() + 60, // Add 1 minute to account for potential lag.
> };
> ```
</details>

The prior implementation would add 1 minute into the future to the end of the time scale, to account for potential lag. This is lost with my current implementation that naively uses TimeScaleDropdown. Does anyone (@maryliag?) know if this is okay, or if should I implement this buffer (probably in TimeScaleDropdown)?
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts, line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqPyhKu300TB4PWZLv7:-MqPyhKu300TB4PWZLv8:bedk83z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69d485693d060a42e73ace5372583a2e16f52db/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts#L0)):*
Deleted this fixture file because there is no story.

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 22 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqPySm12nnVMQfBqfAB:-MqQ7vsnAw8E2FUCLMOM:b-wy09sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2559c4bc20384845d230cb3d6db770ddb4fab3a2/pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L51)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

> ```
> const defaultDateRange: StatementsDateRangeState = {
>   start: moment
>     .utc()
>     .subtract(1, "hours")
>     .unix(),
>   end: moment.utc().unix() + 60, // Add 1 minute to account for potential lag.
> };
> ```
The prior implementation would add 1 minute into the future to the end of the time scale, to account for potential lag. This is lost with my current implementation that naively uses TimeScaleDropdown. Does anyone (@maryliag?) know if this is okay, or if should I implement this buffer (probably in TimeScaleDropdown)?
</blockquote></details>

Don't need to worry about this. If we hit this again in the future we can make adjustments.
___
*[pkg/ui/workspaces/db-console/src/redux/statementsTimeScale.ts, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqQCnBu54cSbriNgUBI:-MqQCnBu54cSbriNgUBJ:bnz9go6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69d485693d060a42e73ace5372583a2e16f52db/pkg/ui/workspaces/db-console/src/redux/statementsTimeScale.ts#L20)):*
> ```XML
>   AdminUIState,
>   TimeScale
> >("statements_time_scale", localSettingsSelector, defaultTimeScaleSelected);
> ```

nit: can you use the same key we're using on cluster-ui? so `timeScale/StatementsPage`. So we can keep things aligned
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsActions.ts, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqQCxqM4Y5xQi7V5PJi:-MqQCxqM4Y5xQi7V5PJj:b6qsb64) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69d485693d060a42e73ace5372583a2e16f52db/pkg/ui/workspaces/db-console/src/redux/statements/statementsActions.ts#L13)):*
> ```XML
> import { Action } from "redux";
> import { PayloadAction } from "src/interfaces/action";
> import { TimeScale } from "oss/src/redux/timewindow";
> ```

nit: remove the `oss`, start import with `src/...`

**Comment by jocrl** [comment]
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsActions.ts, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqQCxqM4Y5xQi7V5PJi:-MqQfqrm53uuWtKY6E-O:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69d485693d060a42e73ace5372583a2e16f52db/pkg/ui/workspaces/db-console/src/redux/statements/statementsActions.ts#L13)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: remove the `oss`, start import with `src/...`
</blockquote></details>

done

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/db-console/src/redux/statementsTimeScale.ts, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqQCnBu54cSbriNgUBI:-MqQfxlkCujYGkyCTSQy:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69d485693d060a42e73ace5372583a2e16f52db/pkg/ui/workspaces/db-console/src/redux/statementsTimeScale.ts#L20)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: can you use the same key we're using on cluster-ui? so `timeScale/StatementsPage`. So we can keep things aligned
</blockquote></details>

done

**Review by Azhng — COMMENTED** [review]
> Reviewed 4 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR7myqDZWir8w5gQ9U):*
nit: extra space in the commit msg ? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR8dbL45xxhfhdhsIv:-MqR8dbM9ZpUuvDwXOOQ:b-8wlwq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L150)):*
> ```XML
>   timeScale: {
>     windowSize: moment.duration(5, "day"),
>     sampleSize: moment.duration(5, "minutes"),
> ```

Hmm is the discrepancy between the `windowSize` and `sampleSize` possible in real life scenario?  I think i'm just not entirely sure whats' the difference between `windowSize` and `sampleSize` here 
___
*[pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR9YCn8LnuKVAbg6e9:-MqR9YCo9OIXmrHmGW6G:bip1zd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts#L66)):*
> ```XML
>   const { ts } = action.payload;
>   yield put(
>     // TODO(azhng): do we want to rename this into dataRange/SQLActivity?
> ```

do you mind update this todo :stuck_out_tongue:

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR7myqDZWir8w5gQ9U):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: extra space in the commit msg ? 
</blockquote></details>

done
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR8dbL45xxhfhdhsIv:-MqUiWxU3F9LbLRXDnFi:buavus3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L150)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm is the discrepancy between the `windowSize` and `sampleSize` possible in real life scenario?  I think i'm just not entirely sure whats' the difference between `windowSize` and `sampleSize` here 
</blockquote></details>

So I know `windowSize` is the straightforward one, it's the size of the time window.

For `sampleSize`, the comment string is: "The expected duration of individual samples for queries at this time scale.". I think this has to do with how fine-grained the information on the statements and transactions tables are. `sampleSize` is [specified](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts#L18) for all default options. In every case it's smaller than `windowSize`.

However, you raise a point that I'm pretty sure this isn't sent in the request. My IDE says that the only usage is [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L173)... which looks like it's just setting a floor on the `sampleSize`.

@xinhaoz, do you have an idea what `sampleSize` is for, or if the metrics page currently uses it? Or @maryliag if it's for some upcoming functionality?
___
*[pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR9YCn8LnuKVAbg6e9:-MqUmSWG4S8_uJlIi9Ib:b-jj5wcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts#L66)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

do you mind update this todo :stuck_out_tongue: 
</blockquote></details>

Done, and renamed to `timeScale/SQLActivity`.
Any suggestions for the name when this also gets shared by the Metrics page? 😛

**Comment by jocrl** [comment]
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR8dbL45xxhfhdhsIv:-MqUneXVDYGNj9G_kPDT:b-4tin) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L150)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

So I know `windowSize` is the straightforward one, it's the size of the time window.

For `sampleSize`, the comment string is: "The expected duration of individual samples for queries at this time scale.". I think this has to do with how fine-grained the information on the statements and transactions tables are. `sampleSize` is [specified](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts#L18) for all default options. In every case it's smaller than `windowSize`.

However, you raise a point that I'm pretty sure this isn't sent in the request. My IDE says that the only usage is [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L173)... which looks like it's just setting a floor on the `sampleSize`.

@xinhaoz, do you have an idea what `sampleSize` is for, or if the metrics page currently uses it? Or @maryliag if it's for some upcoming functionality?


</blockquote></details>

edit: my bad with the usage search; it's used for [request in the Metrics page](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/shared/containers/metricDataProvider/index.tsx#L273). It's not (at least, currently) used in the request for the Statements or Transactions pages

**Comment by jocrl** [comment]
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR8dbL45xxhfhdhsIv:-MqVKc6wC3q8x70jXO4Z:b-hloudy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L150)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

edit: my bad with the usage search; it's used for [request in the Metrics page](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/shared/containers/metricDataProvider/index.tsx#L273). It's not (at least, currently) used in the request for the Statements or Transactions pages
</blockquote></details>

double edit: it seems like using `sampleSize` for the Statements and Transactions pages is part of my next task for aggregated stats 🙂

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR8dbL45xxhfhdhsIv:-MqVNhgL0FvyUsZFe_aa:b-26t0s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L150)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

double edit: it seems like using `sampleSize` for the Statements and Transactions pages is part of my next task for aggregated stats 🙂
</blockquote></details>

Interesting, seems like it's used by the tsDB to represent the granularity of each sample point. Though I think it might be slightly difficult to adapt this for Statement / Transaction Page, since we don't have the aggregating capability in the backend yet. IIRC we do most of our aggregation in the frontend for now.
___
*[pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR9YCn8LnuKVAbg6e9:-MqVPJLW76VtGEDJcPWi:b2rwqmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts#L66)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Done, and renamed to `timeScale/SQLActivity`.
Any suggestions for the name when this also gets shared by the Metrics page? 😛
</blockquote></details>

Hmm good question, `timeScale/Global` or `timeScale/Observability` ?

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-:-MqZkpSi7sGKslKz4PnE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-MqR9YCn8LnuKVAbg6e9:-MqZkD_t1HvxGa4Rdwo_:bdwgytb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0c721f676e10b425242b8a8754e0a957ddc550/pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts#L66)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm good question, `timeScale/Global` or `timeScale/Observability` ? 
</blockquote></details>

I think we can still keep as `timeScale/SQLActivity` for that case, because the metrics there are also SQL Activity related

**Review by matthewtodd — APPROVED** [review]
:lgtm: :tada: 

> Reviewed 17 of 24 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73608#-:-MqoVyWk-Hzj2hL6aVFb:by6fmpn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @xinhaoz)

**Pull request merged**
