### PR TITLE
storage/engine: Use datadriven tests for disk_map implementations

### PR DESCRIPTION
**Pull request by itsbilal**
Replace some diskmap tests with datadriven-based one to improve readability,
coverage, and to reduce code size. Also move some test-specific DiskMap
functions to the test file instead of keeping them in the public
interface.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
:lgtm:

This is almost exactly what I was imagining. A few small comments below, and a suggestion for how to incorporate the sandbox tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-:-LmA5sWj460iQAyCknoS:b-ukag8c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/disk_map_test.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA3jGyCTLgFpEr5Vqs:-LmA3jGz9zNjts2E6bg5:byyy9wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L53)):*
> ```Go
> 	datadriven.RunTest(t, filename, func(d *datadriven.TestData) string {
> 		switch d.Cmd {
> 		case "batch-write":
> ```

In the Pebble data-driven tests, I call this command `"batch"` or `"define"`.
___
*[pkg/storage/engine/disk_map_test.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA40yR8n8D39gYtAHp:-LmA40yR8n8D39gYtAHq:b-n5ye07) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L69)):*
> ```Go
> 				case "put":
> 					if len(parts) != 3 {
> 						return fmt.Sprintf("seek <key> <value>\n")
> ```

`s/seek/put/g`
___
*[pkg/storage/engine/disk_map_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA49J33t46llxSBiUq:-LmA49J33t46llxSBiUr:b6qnhq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L111)):*
> ```Go
> 					fmt.Fprintf(&b, "err=%v\n", err)
> 				} else {
> 					fmt.Fprintf(&b, "end\n")
> ```

The Pebble data-driven iterator tests use `.` to indicate end of iteration. Let's do the same here for consistency.
___
*[pkg/storage/engine/disk_map_test.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA4W38634A0hCJ5HoC:-LmA4W38634A0hCJ5HoD:b-dvkbme) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L117)):*
> ```Go
> 		default:
> 			// No other commands supported.
> 			t.FailNow()
> ```

The common pattern I use is `return fmt.Sprintf("unknown command: %s", td.Cmd)`. The return here allows the removal of the return below as the compiler can determine that it is never reached.
___
*[pkg/storage/engine/disk_map_test.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA4oqJD8punMbvaAZv:-LmA4oqJD8punMbvaAZw:b-eq7qpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L460)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	ctx := context.Background()
> 	dir, err := ioutil.TempDir("", "TestPebbleStore")
> ```

Should this temp directory be removed with a `defer` when the test finishes?
___
*[pkg/storage/engine/disk_map_test.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA5B7t2sF6ULjJ01Kq:-LmA5B7t2sF6ULjJ01Kr:b-wazhn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L482)):*
> ```Go
> // initialized with the same Pebble storage engine cannot read or write
> // another instance's data.
> func TestPebbleMapSandbox(t *testing.T) {
> ```

You could fold this test into the datadriven tests as well. You'd need to add commands to create a new sorted disk map and then be able to create separate iterators and batches for specific maps. Something like:

```
new-map <name>
----

close-map <name>
----

# Create and apply a batch to the named map.
batch <name>
...
----

# Create an iterator for the named map.
iter <name>
...
----
```

The data-driven test would need a "global" `map[string]SortedDiskMap`.

**Review by itsbilal — COMMENTED** [review]
Thanks for the review! Made the multiple map change, and rolled the sandbox test into this as well. Should hopefully make the negative line count delta even nicer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-:-LmAj4Ss0B3SuJxlxUJ1:b-ivnf81)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @petermattis)

___
*[pkg/storage/engine/disk_map_test.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA3jGyCTLgFpEr5Vqs:-LmAIS026TQgOCaBcoiY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L53)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

In the Pebble data-driven tests, I call this command `"batch"` or `"define"`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/disk_map_test.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA40yR8n8D39gYtAHp:-LmAQkgI0u2Adrx_3cNK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L69)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/seek/put/g`
</blockquote></details>

Done.
___
*[pkg/storage/engine/disk_map_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA49J33t46llxSBiUq:-LmAQlODBOB862WXRAM3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L111)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The Pebble data-driven iterator tests use `.` to indicate end of iteration. Let's do the same here for consistency.
</blockquote></details>

Done.
___
*[pkg/storage/engine/disk_map_test.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA4W38634A0hCJ5HoC:-LmAiwt84b0CcGVwdGJ3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L117)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The common pattern I use is `return fmt.Sprintf("unknown command: %s", td.Cmd)`. The return here allows the removal of the return below as the compiler can determine that it is never reached.
</blockquote></details>

Done.
___
*[pkg/storage/engine/disk_map_test.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA4oqJD8punMbvaAZv:-LmAixbl9NUdwFsPnqvM:bdboczt) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L460)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this temp directory be removed with a `defer` when the test finishes?
</blockquote></details>

Good point, there's a testutils helper for this. Done.
___
*[pkg/storage/engine/disk_map_test.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmA5B7t2sF6ULjJ01Kq:-LmAj06WBYn3HqZ3Ofg5:bw8if24) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L482)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You could fold this test into the datadriven tests as well. You'd need to add commands to create a new sorted disk map and then be able to create separate iterators and batches for specific maps. Something like:

```
new-map <name>
----

close-map <name>
----

# Create and apply a batch to the named map.
batch <name>
...
----

# Create an iterator for the named map.
iter <name>
...
----
```

The data-driven test would need a "global" `map[string]SortedDiskMap`.
</blockquote></details>

Done. Should hopefully grow the negative diff delta.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39608)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr and @itsbilal)

___
*[pkg/storage/engine/disk_map_test.go, line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmBXO5a8k-eIOrNfq6d:-LmBXO5a8k-eIOrNfq6e:b-uyxikl) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L296)):*
> ```Go
> 
> 	// Verify that a diskMap cleans up its keyspace when closed.
> 	t.Run("KeyspaceDelete", func(t *testing.T) {
> ```

Is there still test coverage of verifying that the map's keyspace is cleaned up when the map is closed? I think you might need to add a `raw-iter` command, or perhaps a `raw-scan` which would return all of the keys and values present in the engine.
___
*[pkg/storage/engine/disk_map_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmBWRuS-qzCh1O9PaR3:-LmBWRuT2py8K-JPUX-k:b-1ecg8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0927f061ec94d732b32e9bc8579cdcb7f021435b/pkg/storage/engine/disk_map_test.go#L51)):*
> ```Go
> 		case "new-map":
> 			duplicates := false
> 			for _, arg := range d.CmdArgs[1:] {
> ```

This could almost be replaced with `d.ScanArgs`. The fact that it can't is unfortunate. Not suggesting anything here other than the datadriven library could use some additional convenience facilities.
___
*[pkg/storage/engine/disk_map_test.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmBWpH83CXFYiFP4sPf:-LmBWpH83CXFYiFP4sPg:b-11yybt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0927f061ec94d732b32e9bc8579cdcb7f021435b/pkg/storage/engine/disk_map_test.go#L69)):*
> ```Go
> 		}
> 
> 		diskMap, ok := diskMaps[d.CmdArgs[0].Key]
> ```

This was more straightforward than I was expecting. Nice.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39608)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/disk_map_test.go, line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmBXO5a8k-eIOrNfq6d:-LmBrK_xAWk7-pmXT-Z2:b-4hto05) ([raw file](https://github.com/cockroachdb/cockroach/blob/404230f5c99cefed88b1c916733cc81588755af2/pkg/storage/engine/disk_map_test.go#L296)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there still test coverage of verifying that the map's keyspace is cleaned up when the map is closed? I think you might need to add a `raw-iter` command, or perhaps a `raw-scan` which would return all of the keys and values present in the engine.
</blockquote></details>

Done. Added a "raw-scan" - had to write engine-specific code for it since the raw iterator interfaces aren't as nice, but at least that case is covered now. Good catch.
___
*[pkg/storage/engine/disk_map_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmBWRuS-qzCh1O9PaR3:-LmBr0icCxDtRQDlCoeB:b-c3qii1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0927f061ec94d732b32e9bc8579cdcb7f021435b/pkg/storage/engine/disk_map_test.go#L51)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This could almost be replaced with `d.ScanArgs`. The fact that it can't is unfortunate. Not suggesting anything here other than the datadriven library could use some additional convenience facilities.
</blockquote></details>

Yeah. Maybe we shouldn't use the Pythonic mix of positional and keyword arguments to begin with.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39608)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr and @itsbilal)

___
*[pkg/storage/engine/disk_map_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmBWRuS-qzCh1O9PaR3:-LmCDTS75ohw243vSq-r:b-2sb8l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0927f061ec94d732b32e9bc8579cdcb7f021435b/pkg/storage/engine/disk_map_test.go#L51)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah. Maybe we shouldn't use the Pythonic mix of positional and keyword arguments to begin with.
</blockquote></details>

I've been thinking we need a convenient way to parse both the commands, and lines such as `put <key> <value>`.
___
*[pkg/storage/engine/disk_map_test.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCDuDO6qGwKzf-_NO_:-LmCDuDO6qGwKzf-_NOa:b2kgqmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/disk_map_test.go#L56)):*
> ```Go
> 				defer iter.Close()
> 
> 				for iter.Seek(NilKey); ; iter.Next() {
> ```

`s/iter.Seek(NilKey)/iter.First/g`
___
*[pkg/storage/engine/disk_map_test.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCMoyE7WgEr_tg34LP:-LmCMoyE7WgEr_tg34LQ:bljcbo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/disk_map_test.go#L76)):*
> ```Go
> 				}()
> 
> 				for iter.SeekGE(EncodeKey(NilKey)); ; iter.Next() {
> ```

`s/iter.SeekGE(EncodeKey(NilKey))/iter.First/g`

Slightly more idiomatic with Pebble is to structure this like:

```
for valid := iter.First(); valid; vali = iter.Next() {
}
```
___
*[pkg/storage/engine/testdata/diskmap, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCDggV01JAqDqLjY5L:-LmCDggV01JAqDqLjY5M:b-b454zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/testdata/diskmap#L125)):*
> ```
> ----
> 
> raw-scan
> ```

Let's add a test-case that `raw-scan` does find data after `sandbox1` is closed. That is, you should see the same data there as the `iter sandbox2` command. One complexity with this is that the keys will have the prefix. I suppose that will just make the keys ugly when you output them. You might want to format them with `%q`.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39608)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr and @petermattis)

___
*[pkg/storage/engine/disk_map_test.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCDuDO6qGwKzf-_NO_:-LmFWrQHA-AXUhAuFFA9:b9zf6x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/disk_map_test.go#L56)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/iter.Seek(NilKey)/iter.First/g`
</blockquote></details>

RocksDB's iterator doesn't seem to have a `First`?
___
*[pkg/storage/engine/disk_map_test.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCMoyE7WgEr_tg34LP:-LmFWvXQ2p9PDY5cjNMF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/disk_map_test.go#L76)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/iter.SeekGE(EncodeKey(NilKey))/iter.First/g`

Slightly more idiomatic with Pebble is to structure this like:

```
for valid := iter.First(); valid; vali = iter.Next() {
}
```
</blockquote></details>

Done.
___
*[pkg/storage/engine/testdata/diskmap, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCDggV01JAqDqLjY5L:-LmFWzstBqXBTTlOc0Wa:bf805e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/testdata/diskmap#L125)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's add a test-case that `raw-scan` does find data after `sandbox1` is closed. That is, you should see the same data there as the `iter sandbox2` command. One complexity with this is that the keys will have the prefix. I suppose that will just make the keys ugly when you output them. You might want to format them with `%q`.
</blockquote></details>

Done. I ended up adding a `raw-count` instead - the pebble/rocksdb raw key outputs wouldn't have matched due to the different encoding schemes, preventing us from sharing the testdata file. It's much simpler to just test the count of keys found by the raw iterator.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-:-LmFZdyV1eeuIMX22zmh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @itsbilal)

___
*[pkg/storage/engine/disk_map_test.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCDuDO6qGwKzf-_NO_:-LmFZHt12Nq281MaK7zr:brpxwyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/disk_map_test.go#L56)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

RocksDB's iterator doesn't seem to have a `First`?
</blockquote></details>

Hmm, you're right. RocksDB does have it, but we don't expose it via the engine interface.
___
*[pkg/storage/engine/testdata/diskmap, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39608#-LmCDggV01JAqDqLjY5L:-LmFZE3g0V6LA3akUjhq:bh2d9tq) ([raw file](https://github.com/cockroachdb/cockroach/blob/56fe46ebbd0ae59e16192ea08569c6bc0094e5cf/pkg/storage/engine/testdata/diskmap#L125)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. I ended up adding a `raw-count` instead - the pebble/rocksdb raw key outputs wouldn't have matched due to the different encoding schemes, preventing us from sharing the testdata file. It's much simpler to just test the count of keys found by the raw iterator.
</blockquote></details>

Ack. That works for me.

**Comment by itsbilal** [comment]
Thanks for the review!

bors r+

**Pull request merged**
