### PR TITLE
sql: fix LIKE with '_...%', '%..._' and escaped character patterns

### LINKED ISSUE #20556: '_%' doesn't match strings like 'ab' in "like expression"
Hello,

'_%' doesn't match strings like 'ab' in "like expression", which seems to be different from postgres. 

Thanks. 

cockroachdb (1.1.3):
```
root@:26257/> SELECT 'ab' LIKE '_%';
+----------------+
| 'ab' LIKE '_%' |
+----------------+
| false          |
+----------------+
```

postgres (9.5.10):
```
Type "help" for help.

postgres=# select 'ab' like '_%';
 ?column? 
----------
 t
```

### PR DESCRIPTION
**Pull request by richardwu**
Fixes #20556, #20606

Release note: (bug fix) Fixed an issue with `(NOT) (I)LIKE` pattern
matching on `'_...%'` and `'%..._'` returning the incorrect result(s).

Release note: (bugfix) fixed an issue where escaped characters like "\A"
and "\\" in LIKE/ILIKE patterns were not handled properly.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/eval.go, line 3427 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L0-4evbR_EZJjffdwG2:-L0-4evc1nLTczwbcD_i:bcizz5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3427)):*
> ```Go
> 					if prefix[0] == '_' {
> 						prefix = prefix[1:]
> 						s = s[1:]
> ```

that will break if len(s) == 0

---

*[pkg/sql/sem/tree/eval.go, line 3443 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L0-4imy5U1j00ZSMdps:-L0-4imy5U1j00ZSMdpt:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3443)):*
> ```Go
> 					if suffix[len(suffix)-1] == '_' {
> 						suffix = suffix[:len(suffix)-1]
> 						s = s[:len(s)-1]
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600)*

**Comment by nvanbenschoten** [comment]
Nice catch!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/eval.go, line 3405 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L000OIgXeDKqaADsbs9:-L000OIgXeDKqaADsbsA:b-kk6ouk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3405)):*
> ```Go
> 		}
> 	default:
> 		if !strings.ContainsAny(pattern[1:len(pattern)-1], "_%") {
> ```

I guess this should have just been `ContainsAny(... , "%")`, right?

---

*[pkg/sql/sem/tree/eval.go, line 3427 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L0-4evbR_EZJjffdwG2:-L000b4U7QU-IsZWWGkj:bp7mvm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3427)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

that will break if len(s) == 0
</blockquote></details>

Conveniently, we're in the default case of `switch len(pattern)` :)

---

*[pkg/sql/sem/tree/eval.go, line 3441 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L000vRJWlY5CvzvgA38:-L000vRJWlY5CvzvgA39:b-mykfar) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3441)):*
> ```Go
> 					// block does not check the last
> 					// character for '_'.
> 					if suffix[len(suffix)-1] == '_' {
> ```

Does this handle escaped `_` characters correctly? See `anyEnd`.

Perhaps we should create `singleAnyStart` and `singleAnyEnd` variables. Then we can do what we're doing here in addition to a little more:

```
case singleAnyStart && singleAnyEnd:
    return func(s string) bool {
        return len(s) == 2
    }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-:-L0008USwj3Wz5Gjx8FY:b-73m6vw)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/eval.go, line 3427 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L0-4evbR_EZJjffdwG2:-L00iZRxedRkEcOIzcpb:b-qi8g0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3427)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Conveniently, we're in the default case of `switch len(pattern)` :)
</blockquote></details>

len(pattern) != len(s)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600)*

**Comment by richardwu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 3405 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L000OIgXeDKqaADsbs9:-L00ynx8WnPjkw-h7Ky2:bl24tfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3405)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I guess this should have just been `ContainsAny(... , "%")`, right?
</blockquote></details>

So this check sees if any of the characters in the pattern (besides the first and last character) contains a wildcard. If it does then we can't really do the string comparison optimization here.

The issue before was in the one-sided cases `case anyEnd; case anyStart`, it was still possible for the other side to contain the single wildcard character `_`.

I believe this check is still correct.

---

*[pkg/sql/sem/tree/eval.go, line 3427 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L0-4evbR_EZJjffdwG2:-L00zIkuiS-tMpyW1u_J:bsjaqqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3427)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

len(pattern) != len(s)
</blockquote></details>

Good catch, thanks @knz!

---

*[pkg/sql/sem/tree/eval.go, line 3441 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L000vRJWlY5CvzvgA38:-L00zM8B3cXiX9u0BxL3:bys9x7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3441)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this handle escaped `_` characters correctly? See `anyEnd`.

Perhaps we should create `singleAnyStart` and `singleAnyEnd` variables. Then we can do what we're doing here in addition to a little more:

```
case singleAnyStart && singleAnyEnd:
    return func(s string) bool {
        return len(s) == 2
    }
```
</blockquote></details>

Ahhh, good point. Fixed with additional test cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600)*

**Comment by richardwu** [comment]
So while addressing the first issue I noticed that we weren't handling escaped characters correctly both in the optimized and non-optimized case (issue #20606).

I've added a second commit to address this.

**Comment by nvanbenschoten** [comment]
Reviewed 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/eval.go, line 3405 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L000OIgXeDKqaADsbs9:-L04p8B9-SiBggFpu9bt:bxmp4vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e365d530d44ead053d385f170435f348051e9c44/pkg/sql/sem/tree/eval.go#L3405)):*
<details><summary><i>Previously, richardwu (Richard Wu) wrote…</i></summary><blockquote>

So this check sees if any of the characters in the pattern (besides the first and last character) contains a wildcard. If it does then we can't really do the string comparison optimization here.

The issue before was in the one-sided cases `case anyEnd; case anyStart`, it was still possible for the other side to contain the single wildcard character `_`.

I believe this check is still correct.
</blockquote></details>

Ah yeah sorry, my memory of how any of this worked returned progressively over the course of reviewing this change. I meant to delete this comment.

---

*[pkg/sql/sem/tree/eval.go, line 3458 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04r1GnPFE9Nq9XLv23:-L04r1GnPFE9Nq9XLv24:b-ghda6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/786f35faf389949a8dbace1bbdd79c0dde2b8927/pkg/sql/sem/tree/eval.go#L3458)):*
> ```Go
> 				}
> 
> 			case singleAnyStart && singleAnyEnd:
> ```

You can probably collapse these three cases into one:
```
case singleAnyStart || singleAnyEnd:
    return func(s string) bool {
        if singleAnyStart {
            // trim ...
        }
        if singleAnyEnd {
            // trim ...
        }
        // compare ...
    }
```

---

*[pkg/sql/sem/tree/eval.go, line 3535 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04rcc9eCGYZEBaT2fP:-L04rcc9eCGYZEBaT2fQ:b9rcp9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3535)):*
> ```Go
> // token in the return string.
> // For example, suppose we have escape token `\` (e.g. `B` is escaped in
> // `A\BC` and `\\` is escaped in `A\\C`).
> ```

and `\` is escaped in `A\\C`, right?

---

*[pkg/sql/sem/tree/eval.go, line 3547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04tcniNqt4gSzOUZz9:-L04tcniNqt4gSzOUZzA:btilbjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3547)):*
> ```Go
> //    `\\\\` --> `\\`
> func unescapePattern(pattern, escapeToken string) (string, error) {
> 	if pattern == escapeToken {
> ```

If we remove this check will we fall into the `nextIdx == len(pattern)-len(escapeToken)` case later?  

---

*[pkg/sql/sem/tree/eval.go, line 3568 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04u9WDMI-35ieoqt6N:-L04u9WDMI-35ieoqt6O:b-t09stg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3568)):*
> ```Go
> 	ret := make([]byte, len(pattern)-nEscapes*len(escapeToken))
> 	retWidth := 0
> 	start := 0
> ```

nit for here and below: a pattern that's often used is slicing the prefix of the string itself instead of keeping a start index into it (ie. `pattern =  pattern[remove:]`). Feel free to disregard.

---

*[pkg/sql/sem/tree/eval.go, line 3603 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04tZbPqwfNX-fgbVnK:-L04tZbPqwfNX-fgbVnL:b-5lmqom) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3603)):*
> ```Go
> //    replaceUnescaped("TE\\\\_ST", "_", ".", `\\`) --> "TE\\\\.ST"
> func replaceUnescaped(s, old, new string, escapeToken string) string {
> 	if len(s) == 0 {
> ```

We can collapse this case into the next one.

---

*[pkg/sql/sem/tree/eval.go, line 3623 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04twKnCak89Hgf1iLh:-L04twKnCak89Hgf1iLi:bh5skoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3623)):*
> ```Go
> 	// tokens without manually iterating through the entire string and
> 	// keeping track of escaped escape tokens.
> 	ret := make([]byte, len(s)+nOld*(len(new)-len(old)))
> ```

Could this ever underestimate the length if `(len(new)-len(old)) < 0`?

---

*[pkg/sql/sem/tree/eval.go, line 3656 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04uwzd7tSYgxgPRyKN:-L04uwzd7tSYgxgPRyKO:b701qhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3656)):*
> ```Go
> 			// TODO(richardwu): if we require 'old' to be
> 			// under 1 byte (ASCII), then we can simply do + 1
> 			// instead of a runtime computation of len(old).
> ```

Do you think this will be a problem in practice? `len(str)` just references the string's `len` field.

---

*[pkg/sql/sem/tree/eval.go, line 3666 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04vl1lea2fndtzdyxZ:-L04vl1lea2fndtzdyx_:b-83k63n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3666)):*
> ```Go
> 		// Two copies is more efficient than concatenating the slices.
> 		retWidth += copy(ret[retWidth:], s[start:nextIdx])
> 		retWidth += copy(ret[retWidth:], new)
> ```

This is supposed to be overwriting part of what we just copied to `ret`, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600)*

**Comment by richardwu** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/eval.go, line 3458 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04r1GnPFE9Nq9XLv23:-L05Gr87ubjLPAtMylXZ:bfdujxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/786f35faf389949a8dbace1bbdd79c0dde2b8927/pkg/sql/sem/tree/eval.go#L3458)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You can probably collapse these three cases into one:
```
case singleAnyStart || singleAnyEnd:
    return func(s string) bool {
        if singleAnyStart {
            // trim ...
        }
        if singleAnyEnd {
            // trim ...
        }
        // compare ...
    }
```
</blockquote></details>

Much cleaner :+1: 

---

*[pkg/sql/sem/tree/eval.go, line 3535 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04rcc9eCGYZEBaT2fP:-L05ExHC0jKrNDvxFvhH:bj3eoea) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3535)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

and `\` is escaped in `A\\C`, right?
</blockquote></details>

Fixed, thanks.

---

*[pkg/sql/sem/tree/eval.go, line 3547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04tcniNqt4gSzOUZz9:-L05HCB3DRnqgPO4pRR9:b-pb6z7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3547)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we remove this check will we fall into the `nextIdx == len(pattern)-len(escapeToken)` case later?  
</blockquote></details>

Hrm, I guess it would. I wanted to avoid the extra allocation, but I guess it's not too big a deal since this errors out anyways.

---

*[pkg/sql/sem/tree/eval.go, line 3568 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04u9WDMI-35ieoqt6N:-L05Ib1p_-54hrooKlhp:bqivu1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3568)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit for here and below: a pattern that's often used is slicing the prefix of the string itself instead of keeping a start index into it (ie. `pattern =  pattern[remove:]`). Feel free to disregard.
</blockquote></details>

I like it, changed :+1: 

---

*[pkg/sql/sem/tree/eval.go, line 3603 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04tZbPqwfNX-fgbVnK:-L05Jd0hDLueWv_0jo-U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3603)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can collapse this case into the next one.
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/eval.go, line 3623 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04twKnCak89Hgf1iLh:-L05K6CxrtMlvEQKtls0:b-2glhfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3623)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could this ever underestimate the length if `(len(new)-len(old)) < 0`?
</blockquote></details>

Ah good point: it doesn't affect correctness but I've clarified the comment.

---

*[pkg/sql/sem/tree/eval.go, line 3656 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04uwzd7tSYgxgPRyKN:-L05DZY-PEbgj9m-pxj6:b88a0xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3656)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think this will be a problem in practice? `len(str)` just references the string's `len` field.
</blockquote></details>

Hrm, I guess not! Removed.

---

*[pkg/sql/sem/tree/eval.go, line 3666 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04vl1lea2fndtzdyxZ:-L05CmGJ3HChGnqAU_MT:b-jphv62) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3666)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is supposed to be overwriting part of what we just copied to `ret`, right?
</blockquote></details>

I guess the comment is a bit misleading: `nextIdx` is the index of the old string so it'll copy everything up to the old string to be replaced. It then copies over the new string afterwards.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600)*

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 3 files at r4.
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/eval.go, line 3623 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04twKnCak89Hgf1iLh:-L06M-DtKgBo6BzUorA0:b-iflg15) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3623)):*
<details><summary><i>Previously, richardwu (Richard Wu) wrote…</i></summary><blockquote>

Ah good point: it doesn't affect correctness but I've clarified the comment.
</blockquote></details>

Will it naturally extend? Do we have a test for this case? My prediction is that one of these `copys` will silently discard bytes if we run out of space in `ret`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600)*

**Comment by richardwu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/sem/tree/eval.go, line 3623 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-L04twKnCak89Hgf1iLh:-L06RuNQ2wbVGQSOBOh5:b-4qve0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2547907ac2f5e521b173d8c975237f3a409f6b/pkg/sql/sem/tree/eval.go#L3623)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Will it naturally extend? Do we have a test for this case? My prediction is that one of these `copys` will silently discard bytes if we run out of space in `ret`.
</blockquote></details>

Ah right my mistake, the test case I previously added didn't hit this edge case. Fixed and added a test case, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600)*

**Comment by nvanbenschoten** [comment]
:lgtm: thanks for catching this then following up with a fix and rock solid testing!

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-:-L06ToKDCUM1NmQdVSm5:bbp9fcf)*

**Comment by richardwu** [comment]
Thanks for the review(s)! Is this good to cherry-pick into 1.1 too?

**Comment by nvanbenschoten** [comment]
It's pretty big for a cherry-pick, but it seems like a clear improvement. I'd say yes but I'll defer to the release gatekeeper @bdarnell.

**Comment by bdarnell** [comment]
The new code is in `optimizedLikeFunc`. Instead of providing optimized support for these in a cherry-pick could we detect them and route them to the non-optimized implementation? If that's simple then that might be best; otherwise I'm OK with this given the thorough testing.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20600#-:-L06YbY2NKfg8fiTM_do:b-kbwo7i)*

**Comment by richardwu** [comment]
@bdarnell It's not too difficult to re-route the first commit change to the optimized section: I'll do that in the cherry-pick.

**Pull request merged**
