### PR TITLE
opt/memo: add memo.(*statisticsBuilder).colStatTopK

### PR DESCRIPTION
**Pull request by michae2**
In statistics builder, we have a buildTopK but were missing a colStatTopK. Add one based on colStatLimit. We currently only add TopK expressions during exploration, so this is never called anyway, but if we ever add TopK during optbuild or normalization this would be called. Seems better to have it rather than hit the assertion in colStat.

Epic: None

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
The diff looks a little funny because I also moved colStatLimit to be immediately after buildLimit to match the convention used in the rest of statistics builder.

No test because it's not currently possible to call this.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for the quick fix!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120448#-:-NsuKKOZ0I07qP2rJ-MB:b-yq9ynn)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by michae2** [comment]
And thank you for the review!

bors r=DrewKimball

**Review by mgartner — COMMENTED** [review]
I think we should have some stats tests for this. But if we can't come up with a case where it is used, then maybe we don't need it?

**Comment by mgartner** [comment]
Just read the commit message again - I see the issue. Could we test this code with an `expr` opt test?

**Comment by michae2** [comment]
> Just read the commit message again - I see the issue. Could we test this code with an `expr` opt test?

Let me try it out.

**Comment by michae2** [comment]
> > Just read the commit message again - I see the issue. Could we test this code with an `expr` opt test?
> 
> Let me try it out.

It worked! Opened https://github.com/cockroachdb/cockroach/pull/120569 with tests.

**Pull request merged**
