### PR TITLE
sql: make SHOW and SET more consistent.

### PR DESCRIPTION
**Pull request by knz**
This patch is intended to smoothe user experience:

- `SHOW TRANSACTION STATUS` can display the current transaction state;
  make `SHOW ALL` report this as well.
- `SHOW ALL` can displayy the value of `session_user`. Ensure that `SHOW
  SESSION_USER` works too.

Also this patch annotates the grammar to avoid separate syntax diagrams
for the various syntactic variants of the (single) SHOW and SET
statements.

Needed for #12408.

Corresponding doc changes covered in https://github.com/cockroachdb/docs/pull/1107.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13678)

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm: assuming the docs folks are ok with the changes in sql.y

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13678#-:-KdUCgNuu6BgZUmBaQRH:b9yz3ov)*

**Comment by jseldess** [comment]
Looks good at a glance, @knz , but I need to find a stretch of time without kids (on vacation). Will review more closely as soon as I can.

**Comment by knz** [comment]
On 21-02-17 15:44, jseldess wrote:
> Looks good at a glance, @knz <https://github.com/knz> , but I need to
> find a stretch of time without kids (on vacation). Will review more
> closely as soon as I can.
> 

It can wait until next week! Enjoy vacation!

-- 
Raphael 'kena' Poss

**Comment by knz** [comment]
Rebased to current master.
@sploiselle this PR goes together with cockroachdb/docs#1107. I'll wait on your comments there before I merge this one.

**Comment by knz** [comment]
I'm going to merge this so that we get the fix for `show transaction status` and `show session_user` in for the RC. We can carry the docs conversation asynchronously by simply not re-generating the sql diagrams until that discussion is resolved.

**Comment by sploiselle** [comment]
Thanks @knz. Sorry for the delay in reviewing this.

**Pull request merged**
