### PR TITLE
storageccl: optionally return export SST content

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]
Code LGTM, but I'd like a justification or issue link explaining what it's for in the commit message.

**Comment by danhhz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export.go, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762#-L0f_gEzZj7t0DOpVQX3:-L0f_gEzZj7t0DOpVQX4:bmbvm6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/93f4b15015c981f1c48ee55ab00d7bc6c9d561f3/pkg/ccl/storageccl/export.go#L223)):*
> ```Go
> 	}
> 
> 	if args.ReturnSST {
> ```

shouldn't this get a cluster version check?

---

*[pkg/roachpb/api.proto, line 989 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762#-L0f_Jm5AtmPVccnmYeM:-L0f_Jm5AtmPVccnmYeN:b8mirg) ([raw file](https://github.com/cockroachdb/cockroach/blob/93f4b15015c981f1c48ee55ab00d7bc6c9d561f3/pkg/roachpb/api.proto#L989)):*
> ```protobuf
>   MVCCFilter mvcc_filter = 4 [(gogoproto.customname) = "MVCCFilter"];
> 
>   // Return the SST data, rather than writing it directly to storage.
> ```

"rather than" makes it sound like either/or, but I don't think the impl matches this. I think setting both Storage and ReturnSST would do both things, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/storageccl/export.go, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762#-L0f_gEzZj7t0DOpVQX3:-L0fnmFfaJ5IK1rkTf2x:b-c0s7f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/93f4b15015c981f1c48ee55ab00d7bc6c9d561f3/pkg/ccl/storageccl/export.go#L223)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

shouldn't this get a cluster version check?
</blockquote></details>

I thought we'd concluded that because the setting already checked all nodes, we were just going to guard with a single check at call sites, instead of in each evaluating node?

---

*[pkg/roachpb/api.proto, line 989 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762#-L0f_Jm5AtmPVccnmYeM:-L0fo4yYNdd-eGZ4PwON:bnbo1ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/93f4b15015c981f1c48ee55ab00d7bc6c9d561f3/pkg/roachpb/api.proto#L989)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

"rather than" makes it sound like either/or, but I don't think the impl matches this. I think setting both Storage and ReturnSST would do both things, right?
</blockquote></details>

whoops, holdover from when it was instead-of, but it turned out to be slightly easier to test in a single req with it like this.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/export.go, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762#-L0f_gEzZj7t0DOpVQX3:-L0jQCZVs57O-SdttBVt:b-50pjh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/93f4b15015c981f1c48ee55ab00d7bc6c9d561f3/pkg/ccl/storageccl/export.go#L223)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I thought we'd concluded that because the setting already checked all nodes, we were just going to guard with a single check at call sites, instead of in each evaluating node?
</blockquote></details>

ah, nevermind me. the check needs to be at the usage site, which is not introduced in this PR

---

*[pkg/roachpb/api.proto, line 989 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762#-L0f_Jm5AtmPVccnmYeM:-L0jQN_3M8I7ZR23aQVP:bgtl169) ([raw file](https://github.com/cockroachdb/cockroach/blob/93f4b15015c981f1c48ee55ab00d7bc6c9d561f3/pkg/roachpb/api.proto#L989)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

whoops, holdover from when it was instead-of, but it turned out to be slightly easier to test in a single req with it like this.
Done.
</blockquote></details>

:thumbsup: i also like this more than either/or

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20762#-:-L0jQYqD76CTpENig8PT:bnfp4nl)*

**Pull request merged**
