### PR TITLE
builtins: add CURRENT_TIME functionality

### LINKED ISSUE #31708: sql: support current_time
For hibernate test org.hibernate.jpa.test.criteria.QueryBuilderTest.

### PR DESCRIPTION
**Pull request by otan**
Resolves #31708
Refs #26097

This PR adds CURRENT_TIME as a builtin.

Release note (sql change): This PR adds the CURRENT_TIME builtin, which
can be used with precision, e.g. `SELECT CURRENT_TIME, CURRENT_TIME(3)`.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
It seems like the TIMETZ version differs from Postgres in that it does not reflect the session time zone. Is that right? For example `set time zone -5; select current_time::text;` returns different results between CRDB and Postgres.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42928#-:-LvN0MG0BHEpYuJfl1ca:bk9rbkf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42928#-:-LvNLPT91TS_7Fi3ccB9:b-dfd6k)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by otan — COMMENTED** [review]
trying to figure out why current_timestamp is okay though...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42928#-:-LvNLdqZCkL9R3rKPkJ_:bm2lce0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by otan — COMMENTED** [review]
hint: it is not -- https://github.com/cockroachdb/cockroach/pull/43012

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42928#-:-LvNMLSMACGyIADXhLZk:bmt2fu6)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by solongordon — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42928)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
