### PR TITLE
server: serve overview at /debug/

### PR DESCRIPTION
**Pull request by tbg**
screen shot 2016-04-01 at 4 26 14 am

Did I miss anything?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5795)

### CODE REVIEW

**Comment by petermattis** [comment]
There is also `/_status/stacks/`, though I'm wondering about the utility given the `/pprof/goroutines` endpoint. Perhaps it can be removed.

**Comment by petermattis** [comment]
LGTM

**Comment by nvanbenschoten** [comment]
Nice! LGTM

**Comment by tschottdorf** [comment]
Added a TODO on `_status/stacks` - maybe being able to get the goroutines by NodeID is useful, but hard to tell.

**Pull request merged**
