### PR TITLE
Adds the databases table to the databases page.

### PR DESCRIPTION
**Pull request by maxlang**
This PR adds the databases page and wires up the /databases
API endpoint. It also creates a util/api.ts file where more
API rest endpoints can be added.

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6656)

### CODE REVIEW

**Comment by mrtracy** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/next/app/containers/databases.tsx, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcGEyb7vdamtlQ1stZ:-KHcGEyb7vdamtlQ1st_:-1591924222) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/containers/databases.tsx#L22)):*
> ```XML
>  * DatabasesTableColumn provides an enumeration value for each column in the databases table.
>  */
> enum DatabasesTableColumn {
> ```

Seeing all of this copied here for a one column table, I really wonder if I can find a way to get all of this boilerplate reduced.  There doesn't appear to be anything wrong with the implementation here, though, although I think it is a bit overkill for a single column (I assume you are planning ahead for a multi-column page).

---

*[ui/next/app/redux/databases.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcDNPLWrYPOFSKTDce:-KHcDNPM0sPy86yqYW1x:193310427) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/redux/databases.ts#L32)):*
> ```XML
>  */
> export default function reducer(state: DatabaseListState = new DatabaseListState(), action: Action): DatabaseListState {
>   // @mrtracy when would this happen?
> ```

It shouldn't ever happen, we can drop this in our reducers.

---

*[ui/next/app/redux/databases.ts, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcDVerDOcXbHsJij2o:-KHcDVerDOcXbHsJij2p:331556014) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/redux/databases.ts#L37)):*
> ```XML
>   }
> 
>   let stateClone = _.clone(state);
> ```

Don't do this here, this creates a clone for every action dispatched from anywhere, even if it's not relevant to the database reducer. Clone inside of the switch statement, in each case.

---

*[ui/next/app/util/api.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcEohJTtIuDUZz14m3:-KHcEohKTDgouwmYkumh:-1309998127) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/util/api.ts#L24)):*
> ```XML
> function generateGetEndpoint<TRequest, TResponse>(endpoint: string, toUrl?: (params: TRequest) => string) {
>   return function (params?: TRequest) {
>     return timeout(fetch(`${API_PREFIX}/${endpoint}${toUrl ? "/" + toUrl(params) : ""}`, {
> ```

The timeout part is fine.

I think you could generate a restful endpoint in terms of two functions: one which takes `TRequest` and returns the url, the other takes whatever `r.json()` returns (probably`any`) and returns `TResult`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656)*

**Comment by maxlang** [comment]
Review status: 0 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[ui/next/app/containers/databases.tsx, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcGEyb7vdamtlQ1stZ:-KHnYAnyg09AJEKNihuB:1722854648) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/containers/databases.tsx#L22)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Seeing all of this copied here for a one column table, I really wonder if I can find a way to get all of this boilerplate reduced.  There doesn't appear to be anything wrong with the implementation here, though, although I think it is a bit overkill for a single column (I assume you are planning ahead for a multi-column page).</details>
Yeah it will be multi-column. I think some simplifications will become obvious once we're more comfortable with the various frameworks.

---

*[ui/next/app/redux/databases.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcDNPLWrYPOFSKTDce:-KHnYJyY5Z4W1vpGZASa:-1856761875) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/redux/databases.ts#L32)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> It shouldn't ever happen, we can drop this in our reducers.</details>
Whoops, I'd already asked you this in person a while ago.

---

*[ui/next/app/redux/databases.ts, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcDVerDOcXbHsJij2o:-KHnYPVciox0H44vK_bp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/redux/databases.ts#L37)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Don't do this here, this creates a clone for every action dispatched from anywhere, even if it's not relevant to the database reducer. Clone inside of the switch statement, in each case.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656)*

**Comment by mrtracy** [comment]
Reviewed 13 of 16 files at r1.
Review status: 13 of 18 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[ui/next/app/interfaces/action.d.ts, line 16 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv-fV-bu14W5f-lLd2:-KHv-fV0wd_j-SwBBVfW:564391788) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/interfaces/action.d.ts#L16)):*
> ```XML
>   payload: T;
>   error?: boolean;
>   meta?: any;
> ```

Did you mean to add these?

---

*[ui/next/app/redux/databases.spec.ts, line 59 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv5OjhWJxjFFSLub_Y:-KHv5OjhWJxjFFSLub_Z:-496242658) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/redux/databases.spec.ts#L59)):*
> ```XML
>       assert.isUndefined(state.databaseList);
>       assert.deepEqual(state.lastError, dbErr);
>     });
> ```

There is no test for the refreshDatabases action creator, which has all of the asynchronous code.  Please add a TODO.

---

*[ui/next/app/redux/databases.ts, line 103 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv4i3gCcd97ysAMSiz:-KHv4i3gCcd97ysAMSj-:-758110049) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/redux/databases.ts#L103)):*
> ```XML
>     // If there is a query in flight, or if the most recent results are still
>     // valid, do nothing.
>     if (databaseList.inFlight || databaseList.databaseList) {
> ```

This appears to never be invalidated, and in fact it appears to have no way to invalidate it yet other than refreshing the page.  Please add a TODO to this effect.

---

*[ui/next/app/util/api.spec.tsx, line 7 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv3yJXxuSIL6V7ORVm:-KHv3yJXxuSIL6V7ORVn:113046580) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/util/api.spec.tsx#L7)):*
> ```XML
> import {getDatabaseList, API_PREFIX, setFetchTimeout} from "./api";
> 
> type DatabasesRespone = cockroach.server.DatabasesResponse;
> ```

DatabasesResponse

---

*[ui/next/app/util/api.ts, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv4HqhGQV2vSCG_6pH:-KHv4HqhGQV2vSCG_6pI:-533253345) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/util/api.ts#L33)):*
> ```XML
>  * @return returns a function that runs fetch and returns a promise
>  */
> function generateGetEndpoint<TRequest, TResponse>(endpoint: string, toUrl?: (params: TRequest) => string) {
> ```

I would take out the toUrl part entirely, it is not being used anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656)*

**Comment by maxlang** [comment]
Review status: 13 of 18 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[ui/next/app/interfaces/action.d.ts, line 16 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv-fV-bu14W5f-lLd2:-KHvOSQ44W5O7Itkyio5:810225269) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/interfaces/action.d.ts#L16)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Did you mean to add these?</details>
Yeah I added them earlier expecting to use them - it's part of the spec. I can remove them if you want.

---

*[ui/next/app/redux/databases.spec.ts, line 59 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv5OjhWJxjFFSLub_Y:-KHvOZKDQ80zTKLzurSS:1877942539) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/redux/databases.spec.ts#L59)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> There is no test for the refreshDatabases action creator, which has all of the asynchronous code.  Please add a TODO.</details>
Yeah I figured the API tests were the most important here. I'll add a TODO for completeness.

---

*[ui/next/app/redux/databases.ts, line 103 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv4i3gCcd97ysAMSiz:-KHvOf2rJ0pq81VA9yJr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/redux/databases.ts#L103)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> This appears to never be invalidated, and in fact it appears to have no way to invalidate it yet other than refreshing the page.  Please add a TODO to this effect.</details>
Done.

---

*[ui/next/app/util/api.spec.tsx, line 7 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv3yJXxuSIL6V7ORVm:-KHvPjz81-O5_v3q8nwM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/util/api.spec.tsx#L7)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> DatabasesResponse</details>
Done.

---

*[ui/next/app/util/api.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHcEohJTtIuDUZz14m3:-KHvQ0ofJXLtCsIDotEk:-388286367) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e20f5c1ade3b0a3daf72b856e9e8eb436bc8a2/ui/next/app/util/api.ts#L24)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> The timeout part is fine.
> 
> I think you could generate a restful endpoint in terms of two functions: one which takes `TRequest` and returns the url, the other takes whatever `r.json()` returns (probably`any`) and returns `TResult`.
> 
> </details>
Makes sense. I'll do this in a future PR as necessary.

---

*[ui/next/app/util/api.ts, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv4HqhGQV2vSCG_6pH:-KHvPyhffDTOlFGK9_Gt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/util/api.ts#L33)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I would take out the toUrl part entirely, it is not being used anywhere.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656)*

**Comment by mrtracy** [comment]
LGTM

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> #### Adds the databases table to the databases page\.
> 
> This PR adds the databases page and wires up the /databases
> 
> API endpoint. It also creates a util/api.ts file where more
> 
> API rest endpoints can be added.
> 
> 
> 
> </details>


---

Reviewed 1 of 16 files at r1, 6 of 10 files at r3.
Review status: 15 of 19 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[ui/next/app/interfaces/action.d.ts, line 16 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv-fV-bu14W5f-lLd2:-KHvSqKnD82PPFr43J4d:-505591452) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/interfaces/action.d.ts#L16)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Yeah I added them earlier expecting to use them - it's part of the spec. I can remove them if you want.</details>
I'm not sure what spec this is part of, but yeah, lets remove them until we have a use for them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-:-KHvTePk-9eUKOc_HKMz:676834233)*

**Comment by maxlang** [comment]
Review status: 14 of 18 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[ui/next/app/interfaces/action.d.ts, line 16 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656#-KHv-fV-bu14W5f-lLd2:-KHvWnCX_nBMVK17tqqr:-860870523) ([raw file](https://github.com/cockroachdb/cockroach/blob/2721756f983728d914262aac496facc0d43b1e90/ui/next/app/interfaces/action.d.ts#L16)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I'm not sure what spec this is part of, but yeah, lets remove them until we have a use for them.</details>
Removed.

I was going by this: https://github.com/acdlite/flux-standard-action

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6656)*

**Pull request merged**
