### PR TITLE
backupccl: skip more TestProtectedTimestampSpanSelectionDuringBackup subtests

### PR DESCRIPTION
**Pull request by RaduBerinde**
Informs #57546.

Release justification: non-production code change.

Release note: None

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]

**Comment by RaduBerinde** [comment]
Heh hit another subtest in CI. Maybe I should skip the entire test..

**Comment by RaduBerinde** [comment]
Skipped `revs-span-merge` as well.

**Pull request merged**
