### PR TITLE
sql: move CFetcher from sql/row into sql/colexec

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously CFetcher lived in sql/row which caused several things
that ought to live in sql/colexec to actually be in sql/colflow.
This also forced the "planning" code for columnar operators to be
in sql/colflow which didn't allow for reuse of that code in the
unit tests of the operators. Now CFetcher is moved into sql/colexec
(a few things needed to be exposed from sql/row) and several things
are moved into sql/colexec from sql/colflow.

I needed to extract things out of colexec/vecbuiltins package in
order not to create a cycle with colexec due to the movement of the
planning code into colexec.

Release justification: Category 1: Non-production code changes.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
> Reviewed 48 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r=jordanlewis

**Comment by yuzefovich** [comment]
Test timeout - seems like a flake.

bors r=jordanlewis

**Comment by yuzefovich** [comment]
Bors seems to have crashed.

bors r-

**Comment by yuzefovich** [comment]
bors r=jordanlewis

**Pull request merged**
