### PR TITLE
sql: fix conflicting udf options validation

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
A silly mistake that forgot to add option type to the map :(

Release note: None
Release justification: Fixing a bug that function options can be
conflicting with each other. Also Fixing a bug that leakproof can
be set for non-immutable function with ALTER FUNCTION

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N99DvVs6Zv85O25ipz6:-N99DvVt18nKjF7dF94u:bj43gjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e63c9ea0ce1f296044887e29f52d238b064084/pkg/sql/logictest/testdata/logic_test/udf#L25)):*
> ```
> 
> statement error pq: conflicting or redundant options
> CREATE FUNCTION f() RETURNS INT IMMUTABLE LANGUAGE SQL LANGUAGE SQL AS $$ SELECT 1 $$;
> ```

nit: add test with `CALLED ON NULL INPUT/STRICT/RETURNS NULL ON NULL INPUT` too
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N99E1Tk7BStrc8wdX3_:-N99E1Tk7BStrc8wdX3a:b-iyygwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e63c9ea0ce1f296044887e29f52d238b064084/pkg/sql/opt/optbuilder/create_function.go#L72)):*
> ```Go
> 	for _, option := range cf.Options {
> 		optTypeName := reflect.TypeOf(option).Name()
> 		if _, ok := options[optTypeName]; ok {
> ```

It's not a super performance critical code path, but the map and reflection are an anti-pattern. You could define a helper to check for duplicate options that simply stores a bool for each option type.

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/opt/optbuilder/create_function.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N99E1Tk7BStrc8wdX3_:-N9CFUl3A1cyFVbGjeMT:b-azc83o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e63c9ea0ce1f296044887e29f52d238b064084/pkg/sql/opt/optbuilder/create_function.go#L72)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's not a super performance critical code path, but the map and reflection are an anti-pattern. You could define a helper to check for duplicate options that simply stores a bool for each option type.
</blockquote></details>

ah yeah, I agree, I'll make a helper for it. thanks.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N99DvVs6Zv85O25ipz6:-N9E3h8hCncwHQ3g56EO:bxvyt9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e63c9ea0ce1f296044887e29f52d238b064084/pkg/sql/logictest/testdata/logic_test/udf#L25)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add test with `CALLED ON NULL INPUT/STRICT/RETURNS NULL ON NULL INPUT` too
</blockquote></details>

Added more tests.
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N99E1Tk7BStrc8wdX3_:-N9E3_ob5PkL4UmLNH7U:b-xw1m8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e63c9ea0ce1f296044887e29f52d238b064084/pkg/sql/opt/optbuilder/create_function.go#L72)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

ah yeah, I agree, I'll make a helper for it. thanks.
</blockquote></details>

changed as suggested, thanks again!

**Review by ajwerner — APPROVED** [review]
:lgtm: mod nits

> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-:-N9jIhpv5mJwO3nFUX4E:b-tkmfg9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @mgartner)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N9jII4O9rS9KaQMOuq4):*
Can you make this commit message more clear? 
___
*[`pkg/sql/sem/tree/udf_test.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N9jIc2R7rs_chVNWH8H:-N9jIc2S6xGrx_6Hlfbq:b-4nd9w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b93072be283cc22fc01da629ee6eca67f07597/pkg/sql/sem/tree/udf_test.go#L76)):*
> ```Go
> 
> 	for i, tc := range testCases {
> 		t.Run(strconv.Itoa(i+1), func(t *testing.T) {
> ```

nit: the options do know how to turn themselves into strings. It might make for better subtest names

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85922)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @mgartner)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N9jII4O9rS9KaQMOuq4):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you make this commit message more clear? 
</blockquote></details>

oops... fixed.
___
*[`pkg/sql/sem/tree/udf_test.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85922#-N9jIc2R7rs_chVNWH8H:-N9lENrt82I3eYOpo64G:bgvrrui) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b93072be283cc22fc01da629ee6eca67f07597/pkg/sql/sem/tree/udf_test.go#L76)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: the options do know how to turn themselves into strings. It might make for better subtest names
</blockquote></details>

added test names by hand instead. thanks.

**Comment by chengxiong-ruan** [comment]
TFTR! 🙏 
bors r+

**Pull request merged**
