### PR TITLE
pkg/cmd: bump pebble nightly runtime

### PR DESCRIPTION
**Pull request by bananabrick**
Reasons for bumping are outlined here:
https://github.com/cockroachdb/pebble/issues/1343

Release note: None

### CODE REVIEW

**Review by itsbilal — COMMENTED** [review]
Change looks good, but I wonder if it's a good idea to add a separate pebble-nightly roachtest run that has a 90-min timeout, or alternatively they could be named `duration=90m` and `duration=10m` . You can then update `teamcity-nightly-pebble.sh` to only call the 90m versions. Or you could pass in `tag:nightly` that changes the duration, and you could pass that flag in that file but not when we run it ourselves.

I think there's value in still keeping the 10m roachtest so we can quickly manually verify the results of a change.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71943#-:-MmyWOc9ELj-sP_jsGm9:b1qk2x5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick)

**Review by bananabrick — COMMENTED** [review]
Thanks. I agree.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71943#-:-MnY0ML87xYxHIaV8j1m:b-xapomf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by jlinder — APPROVED** [review]
From the dev-inf perspective, this looks good. We were tagged for review because of the change to `build/teamcity-nightly-pebble.sh`. 

Deferring to @itsbilal for the roachtest change review.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71943#-:-Mo0foO99BNKxeQ_DHag:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

___
*[build/teamcity-nightly-pebble.sh, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71943#-Mo0ffkT7XhEtnnXQwDZ:-Mo0ffkT7XhEtnnXQwD_:bvytf4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e7ac46c7682c02258fafc406cf4722ee9453ea/build/teamcity-nightly-pebble.sh#L60)):*
> ```Shell
>   --teamcity \
>   --cpu-quota=384 \
>   tag:pebble_nightly pebble; then
> ```

Wonder if we could do something with `tag:pebble tag:nightly` i.e. two separate tags, and have the test change its duration if it has the nightly tag set, but this works too.

**Comment by bananabrick** [comment]
tftr! bors r+

**Pull request merged**
