### PR TITLE
roachpb,kv,storage: unify OrigTimestamp and RefreshedTimestamp

### PR DESCRIPTION
**Pull request by andreimatei**
This patch deprecates the txn.OrigTimestamp field and elevates
txn.RefreshedTimestamp to be the one and only field that dictates a
transaction's read timestamp (modulo backwards compatibility).
Before this change, the main field used to dictate the read timestamp
was OrigTimestamp. And then code was ratcheting that up to
RefreshedTimestamp, if set (although I think not very consistently,
albeit I fixed some inconsistencies in prior commits). This is one too
many timestamps. The point of having two of them was that it used to be
necessary to maintain the timestamp that an epoch began with (hence the
"orig" name), in addition to the latest refresh. The reasons for keeping
that original timestamp around have gone away by now.

So, this patch makes all the code use RefreshedTimestamp everywhere,
with fallbacks to OrigTimestamp for compatibility. This will make it
easy to delete OrigTimestamp in 20.2. RefreshedTimestamp is now also
always set.
The next commit will rename RefreshedTimestamp->ReadTimestamp and
OrigTimestamp->DeprecatedOrigTimestamp. The rename is kept separated to
help the code review.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
All the renames are now done.
Reviewable seems to refuse to show commits in isolation (cause there's too many of them?). If you prefer, I can split it into multiple PRs. But the only large commit that's not mechanic is `unify OrigTimestamp and RefreshedTimestamp`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-:-LtWXWuF9ci-b97ai8RF:bjv415q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
:100: this is great! Thanks for doing the cleanup.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-:-LtXtWnsEC41b0lHCkVM:b-bps0va)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/internal/client/sender.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXrDso2KEknhdhm-54:-LtXrDso2KEknhdhm-55:b98fe5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/internal/client/sender.go#L344)):*
> ```Go
> 
> 	// For backwards compatibility with 19.2, set the DeprecatedOrigTimestamp too (although
> 	// not really needed by this Mock sender).
> ```

Add a TODO.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXr_4C9zoEuxZ_z3iT:-LtXr_4C9zoEuxZ_z3iU:bgeldwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/kv/txn_interceptor_span_refresher.go#L279)):*
> ```Go
> // timestamp. Returns whether the refresh was successful or not.
> func (sr *txnSpanRefresher) tryUpdatingTxnSpans(
> 	ctx context.Context, refreshTxn *roachpb.Transaction, refreshFrom hlc.Timestamp,
> ```

It's too bad that we lost the comment on this when we made it a param. I'm also not sure how I feel about getting this from the proto instead of `sr.refreshedTimestamp`. Why did you make that change.

Also, I think we should have a test for the behavior specified in:
```		
// More importantly, reads that have happened since we've previously
// refreshed don't need to be checked below below the timestamp at which
// they've been read (which is the timestamp to which we've previously
// refreshed). Checking below that timestamp (like we would, for example,
// if we simply used txn.OrigTimestamp here), could cause false-positives
// that would fail the refresh.
```
___
*[pkg/roachpb/api.proto, line 1510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnIcMCUvK_ckW9d4B:-LtXnIcMCUvK_ckW9d4C:b-cskp3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/api.proto#L1510)):*
> ```protobuf
> 
> // RefreshRequest is arguments to the Refresh() method, which verifies
> // that no write has occurred since the a provided timestamp
> ```

"since the a provided"
___
*[pkg/roachpb/api.proto, line 1514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnQ5Q4tozpYU_toGx:-LtXnQ5Q4tozpYU_toGy:btxyzdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/api.proto#L1514)):*
> ```protobuf
> // updated according to the write parameter. A transaction must be
> // supplied with this request. If the key has been written more
> // recently than the provided txn timestamp, an error is returned
> ```

`s/provided txn timestamp/provided "refresh from" timestamp/`?
___
*[pkg/roachpb/api.proto, line 1517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnZVU3N4q5yowtPPl:-LtXnZVU3N4q5yowtPPm:b-b7rz2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/api.proto#L1517)):*
> ```protobuf
> // and the timestamp cache is not updated.
> //
> // The timestamp cache is updated to txn.read_timestamp, like it is for all
> ```

nit: wrap to same width as rest of comment.
___
*[pkg/roachpb/batch.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXmBI88fvbtZUZPezH:-LtXmBI88fvbtZUZPezI:b4h6x0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/batch.go#L41)):*
> ```Go
> 		// commit timestamp has been forwarded, so that all reads within a txn
> 		// observe the same snapshot of the database regardless of how the
> 		// provisional commit timestamp evolves..
> ```

Double period.
___
*[pkg/roachpb/data.go, line 1261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXmQ8nBpHc9RDw8dB6:-LtXmQ8nBpHc9RDw8dB7:b4d8d3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/data.go#L1261)):*
> ```Go
> // specified in the supplied error can be retried at a refreshed timestamp to
> // avoid a client-side transaction restart. If true, returns a cloned, updated
> // Transaction object with the commit timestamp and refreshed timestamp set
> ```

"provisional commit timestamp"
___
*[pkg/roachpb/data.proto, line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXsUyF3WZquZCrXET0:-LtXsUyF3WZquZCrXET1:bd3akd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/data.proto#L334)):*
> ```protobuf
>   // retry.
>   bool commit_timestamp_fixed = 16;
>   // The refreshed timestamp is the transaction's read timestamp. All reads are
> ```

This comment needs some love now that "refreshed timestamp" is no longer a thing.
___
*[pkg/storage/gc_queue_test.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXsn0x7IGt41WeVKYj:-LtXsn0x7IGt41WeVKYk:b-piv9tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/gc_queue_test.go#L450)):*
> ```Go
> 				txn.ReadTimestamp = datum.ts
> 				txn.WriteTimestamp = datum.ts
> 				txn.DeprecatedOrigTimestamp = datum.ts
> ```

Why are we still providing this in tests? We shouldn't be requiring it to be set anywhere on the server or we won't be able to get rid of it in 20.2.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXqbcm2-uqkxFn_ig0:-LtXqbcn-ssATjfxZm_7:b-7v25u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bfb721ea4f4f6371f228c0623d8eca1cd9002a5/pkg/storage/batcheval/cmd_end_transaction.go#L241)):*
> ```Go
> 					"programming error: epoch regression: %d", h.Txn.Epoch,
> 				))
> 			} else if h.Txn.Epoch == reply.Txn.Epoch && reply.Txn.Timestamp.Less(h.Txn.OrigTimestamp) {
> ```

You could compare against `h.Txn.MinTimestamp`. I'm not sure that that's worth it though.
___
*[pkg/storage/batcheval/cmd_refresh.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnz4K19OhzgWtqcCN:-LtXnz4K19OhzgWtqcCO:b-hzchr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/batcheval/cmd_refresh.go#L50)):*
> ```Go
> 	refreshFrom := args.RefreshFrom
> 	if refreshFrom.IsEmpty() {
> 		// Compatibility with 19.2 nodes, which didn't set the args.RefreshFrom field.
> ```

Leave a TODO to remove this with a description of when that is possible.
___
*[pkg/storage/batcheval/cmd_refresh.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXmlfC1PXKPkT5LFGY:-LtXmlfC1PXKPkT5LFGZ:b-e5ydld) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/batcheval/cmd_refresh.go#L66)):*
> ```Go
> 		return result.Result{}, err
> 	} else if val != nil {
> 		if ts := val.Timestamp; !ts.Less(refreshFrom) {
> ```

No need for the `batcheval: clarify comment about pessimization` commit since it's completely removed by the end of this PR.
___
*[pkg/storage/batcheval/cmd_refresh_range.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXo4VR-iy1kDT9e6Y0:-LtXo4VR-iy1kDT9e6Y1:b-hzchr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/batcheval/cmd_refresh_range.go#L50)):*
> ```Go
> 	refreshFrom := args.RefreshFrom
> 	if refreshFrom.IsEmpty() {
> 		// Compatibility with 19.2 nodes, which didn't set the args.RefreshFrom field.
> ```

Leave a TODO to remove this with a description of when that is possible.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/internal/client/sender.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXrDso2KEknhdhm-54:-LtbeGdwDWQMRwn3up8f:b41svb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/internal/client/sender.go#L344)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a TODO.
</blockquote></details>

it's clear...
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXr_4C9zoEuxZ_z3iT:-LtbbyQy4v43W_VLlkk3:b6ysh0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/kv/txn_interceptor_span_refresher.go#L279)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's too bad that we lost the comment on this when we made it a param. I'm also not sure how I feel about getting this from the proto instead of `sr.refreshedTimestamp`. Why did you make that change.

Also, I think we should have a test for the behavior specified in:
```		
// More importantly, reads that have happened since we've previously
// refreshed don't need to be checked below below the timestamp at which
// they've been read (which is the timestamp to which we've previously
// refreshed). Checking below that timestamp (like we would, for example,
// if we simply used txn.OrigTimestamp here), could cause false-positives
// that would fail the refresh.
```
</blockquote></details>

Well, I had made the change because OrigTimestamp going away made things awkward for keeping track of what the "refresh from" should be. But you're right, it is better to use `sr.refreshedTimestamp`. I've now switched to using `sr.refreshedTimestamp`, but for that I had set that at the beginning of the txn (i.e. on the first batch that flows through) too. PTAL.

Spurred by this, I've also added a commit at the end cleaning up the protection we had against concurrent txn use. PTAL at that too.

The comment is now back. I will write the respective test tomorrow.
___
*[pkg/roachpb/api.proto, line 1510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnIcMCUvK_ckW9d4B:-LtbdpEd1IJOpHQexNSR:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/api.proto#L1510)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"since the a provided"
</blockquote></details>

done
___
*[pkg/roachpb/api.proto, line 1514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnQ5Q4tozpYU_toGx:-LtbdqD55wJBl5X1gyGQ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/api.proto#L1514)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/provided txn timestamp/provided "refresh from" timestamp/`?
</blockquote></details>

done
___
*[pkg/roachpb/api.proto, line 1517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnZVU3N4q5yowtPPl:-Ltbdt8p69VWZsZycJw4:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/api.proto#L1517)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: wrap to same width as rest of comment.
</blockquote></details>

done
___
*[pkg/roachpb/batch.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXmBI88fvbtZUZPezH:-LtbefRCDWfKFn5wQOY6:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/batch.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Double period.
</blockquote></details>

done
___
*[pkg/roachpb/data.go, line 1261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXmQ8nBpHc9RDw8dB6:-LtberRJCkF2NLAcBx07:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/data.go#L1261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"provisional commit timestamp"
</blockquote></details>

done
___
*[pkg/roachpb/data.proto, line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXsUyF3WZquZCrXET0:-LtbblaS3DWvC9h47cbO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/roachpb/data.proto#L334)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment needs some love now that "refreshed timestamp" is no longer a thing.
</blockquote></details>

done
___
*[pkg/storage/gc_queue_test.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXsn0x7IGt41WeVKYj:-Ltbaev-A3izbLZxuzLD:byvvlh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/gc_queue_test.go#L450)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why are we still providing this in tests? We shouldn't be requiring it to be set anywhere on the server or we won't be able to get rid of it in 20.2.
</blockquote></details>

Because we need to override what `newTransaction()` sets (through the regular txn ctor). In the ctor, setting the `OrigTS` is not gated by a cluster version cause I didn't take the trouble.
But this can all go in 20.2.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXqbcm2-uqkxFn_ig0:-LtbfOyU5z2kyFhrGiER:b-wnr3yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bfb721ea4f4f6371f228c0623d8eca1cd9002a5/pkg/storage/batcheval/cmd_end_transaction.go#L241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You could compare against `h.Txn.MinTimestamp`. I'm not sure that that's worth it though.
</blockquote></details>

yeah... I'd leave it alone.
___
*[pkg/storage/batcheval/cmd_refresh.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXnz4K19OhzgWtqcCN:-LtbexgQ11t0mnjh7jCD:bed50dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/batcheval/cmd_refresh.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a TODO to remove this with a description of when that is possible.
</blockquote></details>

it clear...
___
*[pkg/storage/batcheval/cmd_refresh.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXmlfC1PXKPkT5LFGY:-Ltbf8S47Zz0deX2YnxQ:bjl2yvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/batcheval/cmd_refresh.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need for the `batcheval: clarify comment about pessimization` commit since it's completely removed by the end of this PR.
</blockquote></details>

I'll leave it for the history
___
*[pkg/storage/batcheval/cmd_refresh_range.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXo4VR-iy1kDT9e6Y0:-LtbeApx4NtUdWvh8cTG:bcr3x5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/batcheval/cmd_refresh_range.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a TODO to remove this with a description of when that is possible.
</blockquote></details>

but it's clear...

**Review by andreimatei — COMMENTED** [review]
And thanks for the read!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-:-Ltbffy40MMUDFAIqxXE:b-gmxxj8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_span_refresher.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXr_4C9zoEuxZ_z3iT:-LtgOxn-BNywQ1TQmNNe:b-mvvvvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/kv/txn_interceptor_span_refresher.go#L279)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Well, I had made the change because OrigTimestamp going away made things awkward for keeping track of what the "refresh from" should be. But you're right, it is better to use `sr.refreshedTimestamp`. I've now switched to using `sr.refreshedTimestamp`, but for that I had set that at the beginning of the txn (i.e. on the first batch that flows through) too. PTAL.

Spurred by this, I've also added a commit at the end cleaning up the protection we had against concurrent txn use. PTAL at that too.

The comment is now back. I will write the respective test tomorrow.
</blockquote></details>

Added the test in the commit about "kv: optimize refresh timestamp ranges" commit.

**Review by nvb — APPROVED** [review]
:lgtm: nice test.

> Reviewed 2 of 86 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-:-LtlfKgiDTeN6EQFudQ_:b-kdse7s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/internal/client/sender.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXrDso2KEknhdhm-54:-LtlbsOXAK5BBilhTnS6:b7yxuqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/internal/client/sender.go#L344)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's clear...
</blockquote></details>

The point isn't that this isn't clear, it's that the TODO allows you/me/someone to search for `TODO.*20.2` and find all the code we can cleanup right after the next release. I guess as long as you have once of these TODOs on the `DeprecatedOrigTimestamp` field then its fine.
___
*[pkg/kv/dist_sender_server_test.go, line 2890 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtlemetDuntF4wj3G3N:-LtlemetDuntF4wj3G3O:bqsajut) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d9aecb06a0c22471e4a702a31b9f88240162c1b/pkg/kv/dist_sender_server_test.go#L2890)):*
> ```Go
> // - someone else writes "a" @ 200
> // - txn attempts to write "a" and is pushed to 200. The refresh succeeds.
> // - txn reads something that has a value in [100,200]. For example, "a", which
> ```

I think 200 is exclusive here, so below "as it would find b@200" also needs to change.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtldA629tsjlaFGPClw:-LtldA629tsjlaFGPClx:bkfe3tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/kv/txn_interceptor_span_refresher.go#L169)):*
> ```Go
> 		ba.Txn.ReadTimestamp.Forward(largestRefreshTS)
> 		if !sr.appendRefreshSpans(ctx, ba, br) {
> 			// The refresh spans are out of date, return a generic client-side retry error.
> ```

What allowed us to get rid of this? The concurrent txn detection? Is that enough to detect concurrent use with dist sql flows?
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-Ltlch40B_0Iqqsc0xOB:-Ltlch40B_0Iqqsc0xOC:b-5nrew4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d9aecb06a0c22471e4a702a31b9f88240162c1b/pkg/kv/txn_interceptor_span_refresher.go#L130)):*
> ```Go
> 	autoRetryCounter *metric.Counter
> 
> 	// requestInFlight is set while a request is being processed by the next
> ```

Why is this detection in the span refresher? It seems like a good idea, but I don't see why it belongs here. I'd move it to the TxnCoordSender itself.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-Ltlcrbo-5aFCbdgNPtG:-Ltlcrbo-5aFCbdgNPtH:b-ppx662) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d9aecb06a0c22471e4a702a31b9f88240162c1b/pkg/kv/txn_interceptor_span_refresher.go#L162)):*
> ```Go
> 	} else if sr.refreshedTimestamp != batchReadTimestamp {
> 		// Sanity check: we're supposed to control the read timestamp. What we're
> 		// tracking in sr. refreshedTimestamp is not supposed to get out of sync
> ```

sr.refreshedTimestamp
___
*[pkg/storage/gc_queue_test.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXsn0x7IGt41WeVKYj:-LtleIor5EYNcGFPNLYf:bmdn7rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/storage/gc_queue_test.go#L450)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Because we need to override what `newTransaction()` sets (through the regular txn ctor). In the ctor, setting the `OrigTS` is not gated by a cluster version cause I didn't take the trouble.
But this can all go in 20.2.
</blockquote></details>

Ack. Thanks for the explanation.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/internal/client/sender.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtXrDso2KEknhdhm-54:-Lu-4j35B7ses16xEU32:b-oabdpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/internal/client/sender.go#L344)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The point isn't that this isn't clear, it's that the TODO allows you/me/someone to search for `TODO.*20.2` and find all the code we can cleanup right after the next release. I guess as long as you have once of these TODOs on the `DeprecatedOrigTimestamp` field then its fine.
</blockquote></details>

right - one TODO on DeprecatedOrigTimestamp to rule them all
___
*[pkg/kv/dist_sender_server_test.go, line 2890 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtlemetDuntF4wj3G3N:-Lu-ANt58ADjUrQgZ4nK:b8k03vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d9aecb06a0c22471e4a702a31b9f88240162c1b/pkg/kv/dist_sender_server_test.go#L2890)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think 200 is exclusive here, so below "as it would find b@200" also needs to change.
</blockquote></details>

I clarified that the txn is pushed to `(200,1)`. And below it should have been `a@200`.
See now.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-LtldA629tsjlaFGPClw:-Lu-19KO7kkQsDzg__J9:b8hj20b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab31ecf8cf66ea6da9b1cb5b9c506293d0b4ac2/pkg/kv/txn_interceptor_span_refresher.go#L169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What allowed us to get rid of this? The concurrent txn detection? Is that enough to detect concurrent use with dist sql flows?
</blockquote></details>

Yes to all the questions.
But as discussed, I've added yet another assertion error back here.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-Ltlch40B_0Iqqsc0xOB:-Lu-0LsVDh6TADfMERZS:b-lzvx1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d9aecb06a0c22471e4a702a31b9f88240162c1b/pkg/kv/txn_interceptor_span_refresher.go#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why is this detection in the span refresher? It seems like a good idea, but I don't see why it belongs here. I'd move it to the TxnCoordSender itself.
</blockquote></details>

moved to the gatekeeper
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42236#-Ltlcrbo-5aFCbdgNPtG:-Lu-0aUI9lkUwxhxMYm4:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d9aecb06a0c22471e4a702a31b9f88240162c1b/pkg/kv/txn_interceptor_span_refresher.go#L162)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

sr.refreshedTimestamp
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
> Reviewed 2 of 86 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42236)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Comment by andreimatei** [comment]
Bors r+

**Pull request merged**
