### PR TITLE
sql: use errors.Is instead of direct error compares

### PR DESCRIPTION
**Pull request by knz**
As suggested in the error handling RFC.

Release justification: Fix to earlier fix for release.

Release note: None

### CODE REVIEW

**Review by pbardea — APPROVED** [review]
LGTM
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41474#-:-LqlXC_RAnuAFEgNCU9P:b-9cpdtl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by knz** [comment]
bors r=pbardea

**Comment by tbg** [comment]
This doesn't need a backport, right?

**Comment by knz** [comment]
Not until we find a bug that this fixes.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
