### PR TITLE
geo/geomfn: implement ST_TileEnvelope({int4,int4,int4,geometry})

### LINKED ISSUE #49053: geo/geomfn: implement ST_TileEnvelope({int4,int4,int4,geometry})
Implement `ST_TileEnvelope` on arguments {int4,int4,int4,geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_TileEnvelope.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2023-09-03T23:16:38Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by zagraves**
Implements builtin for `ST_TileEnvelope` function, porting the code from PostGIS

Fixes: #49053

Release note (sql change): Implement the postgis ST_TileEnvelope function

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Thank you for your contribution! This is looking like it's in pretty good shape. I have mostly nits and test suggestions. I noticed that one of the test outputs differs from postgres, but I haven't figured out why yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-:-NjFR_UUAo8HulV7phyp:b-p7mxq3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @zagraves)

___
*[`pkg/geo/geomfn/tile_envelope.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjFEUmI9uX1bA0F4U4h:-NjFEUmI9uX1bA0F4U4i:b-hgtm5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/geo/geomfn/tile_envelope.go#L35)):*
> ```Go
> 	worldTileSize := uint32(0x01) << tileZoomu
> 
> 	if tileZoom < 0 || tileZoom >= 32 {
> ```

nit: move these 3 checks before the cast to tileZoomu
___
*[`pkg/sql/sem/builtins/geo_builtins.go` line 7140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjFPYcjE6bJLpW1cPeX:-NjFPYcjE6bJLpW1cPeY:be0dsdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/sql/sem/builtins/geo_builtins.go#L7140)):*
> ```Go
> 				{Name: "tileX", Typ: types.Int4},
> 				{Name: "tileY", Typ: types.Int4},
> 			},
> ```

All three overloads need the property `CalledOnNullInput: true`.
___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjF9bKz2_iYda7hGF5B:-NjF9bKz2_iYda7hGF5C:b-7gh3sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/sql/logictest/testdata/logic_test/geospatial#L6228)):*
> ```
> SELECT ST_AsText(ST_TileEnvelope(8, 1, 2));
> ----
> POLYGON ((-19880965.308861203491688 19567879.241005122661591, -19880965.308861203491688 19724422.274933163076639, -19724422.274933163076639 19724422.274933163076639, -19724422.274933163076639 19567879.241005122661591, -19880965.308861203491688 19567879.241005122661591))
> ```

Postgres rounds to 9 decimal places. Any idea how this implementation leads to more precision than postgis?
___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjFRCSABRyAF4EMM0jf:-NjFRCSABRyAF4EMM0jg:b-nxcdfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/sql/logictest/testdata/logic_test/geospatial#L6240)):*
> ```
> POLYGON ((-140.625 42.1875, -140.625 70.3125, -84.375 70.3125, -84.375 42.1875, -140.625 42.1875))
> 
> subtest end
> ```

nit: Please add a newline at the end of the file.
___
*[`pkg/geo/geomfn/tile_envelope_test.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjFRGKv9g4cXvyHQ1C1:-NjFRGKw3u9E1XaSlrKf:bxa4ym4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/geo/geomfn/tile_envelope_test.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

nit: s/2020/2023
___
*[`pkg/geo/geomfn/tile_envelope_test.go` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjFQk1G8lPcMi7M9ShP:-NjFQk1G8lPcMi7M9ShQ:b6epqtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/geo/geomfn/tile_envelope_test.go#L20)):*
> ```Go
> )
> 
> func TestTileEnvelope(t *testing.T) {
> ```

In either this test or the logic test, could you please add tests with NULLs for each of the inputs?
___
*[`pkg/geo/geomfn/tile_envelope_test.go` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjFQvWC--2tLObG2FEu:-NjFQvWC--2tLObG2FEv:bcdmhun) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/geo/geomfn/tile_envelope_test.go#L20)):*
> ```Go
> )
> 
> func TestTileEnvelope(t *testing.T) {
> ```

Thanks for adding this unit test!

**Comment by zagraves** [comment]
@rharding6373 Looking at the precision, I noticed `st_astext` uses a precision default of 15 decimals. The actual WKB output of `st_tileenvelope` is consistent between Postgis and this implementation. 

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go#L69

```
> select st_tileenvelope(8,1,2);
                                                                                           st_tileenvelope
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0103000020110F000001000000050000007218F154C0F572C13028DB7350A972417218F154C0F572C15120666488CF72415120666488CF72C15120666488CF72415120666488CF72C13028DB7350A972417218F154C0F572C13028DB7350A97241
```

**Review by rharding6373 — APPROVED** [review]
:lgtm: Thanks for following through on this! I'm going to push a patch to fix the formatting errors for the linter and then put this in the merge queue. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-:-NkXcT5p-FIMv61WPskj:b-ba9i23)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @zagraves)

___
*[`pkg/sql/logictest/testdata/logic_test/geospatial` line 6228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112971#-NjF9bKz2_iYda7hGF5B:-NkXZPcq0Y5azEqaLifG:b-ymri6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f28515967617c6f0c34404a645f3c3ed45604d6/pkg/sql/logictest/testdata/logic_test/geospatial#L6228)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Postgres rounds to 9 decimal places. Any idea how this implementation leads to more precision than postgis?
</blockquote></details>

Thanks for confirming that this is a discrepency in `ST_AsText`.

**Pull request merged**
