### PR TITLE
scripts: add bump-pebble script

### PR DESCRIPTION
**Pull request by jbowens**
Add a script to automate some of the steps involved in bumping the
Pebble version.

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68928)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[scripts/bump-pebble.sh, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MhKoG1N0FzZsaMWGSic:-MhKoG1N0FzZsaMWGSid:b-5zzxjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L1)):*
> ```Shell
> #!/usr/bin/env zsh
> ```

Looks like the other files in this dir are mix of `sh` and `bash`. Is there anything in here that's `zsh`-specific?
___
*[scripts/bump-pebble.sh, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MhKoT6JCSS6VzBqsweK:-MhKoT6JCSS6VzBqsweL:b9991uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L23)):*
> ```Shell
> # Pebble repository.
> 
> set -ex
> ```

nit: not sure if we have a style guide for shell scripts, but if you haven't seen "[strict bash](http://redsymbol.net/articles/unofficial-bash-strict-mode/)", `set -euo pipefail` is a nice default stance.

I've also found [`shellcheck`](https://github.com/koalaman/shellcheck) good as a linter - there are a few checks applicable to this script (double quotes, equal checks, backticks, to name a few).
___
*[scripts/bump-pebble.sh, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MhKpYDJCCAmRlgZ9r6R:-MhKpYDK9swtmf9Fr33M:b2cr3bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L37)):*
> ```Shell
> # upstream and grab the current Pebble SHA.
> pushd $COCKROACH_DIR
> git fetch upstream "$BRANCH"
> ```

Is there a convention for calling the main CRL repo `upstream`, vs `origin` for our own personal forks? I've adopted the convention you have here, but I'm wondering if this will break for those that have different remote names?

**Review by bananabrick — COMMENTED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-:-MjVxNap0afsWMcEL1Xd:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[scripts/bump-pebble.sh, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MjVxKZp5tID6KcytDBP:-MjVxKZp5tID6KcytDBQ:b-dctjzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L68)):*
> ```Shell
> pushd $VENDORED_DIR
> git branch -D "$VENDORED_BRANCH" || true
> git co -b $VENDORED_BRANCH
> ```

co -> checkout to make it more general

**Review by jbowens — COMMENTED** [review]
I got pretty distracted over the past month. Just fixed this up a bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-:-MjWLDZGBTNW-Nb7-_tQ:bot757p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @nicktrav)

___
*[scripts/bump-pebble.sh, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MhKoG1N0FzZsaMWGSic:-MjWIWuY1ZUMYlcoxcJB:bshenxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L1)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Looks like the other files in this dir are mix of `sh` and `bash`. Is there anything in here that's `zsh`-specific?
</blockquote></details>

Naw, I had put zsh just because it's now the default shell on Mac OS X. I'll switch it to bash for portability.
___
*[scripts/bump-pebble.sh, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MhKoT6JCSS6VzBqsweK:-MjWL8K85SfnFr1gtgmy:b6uy60b) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L23)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: not sure if we have a style guide for shell scripts, but if you haven't seen "[strict bash](http://redsymbol.net/articles/unofficial-bash-strict-mode/)", `set -euo pipefail` is a nice default stance.

I've also found [`shellcheck`](https://github.com/koalaman/shellcheck) good as a linter - there are a few checks applicable to this script (double quotes, equal checks, backticks, to name a few).
</blockquote></details>

Nice, good rec.
___
*[scripts/bump-pebble.sh, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MhKpYDJCCAmRlgZ9r6R:-MjWIfsoArZq4JTXKKFq:bgk5gu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L37)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is there a convention for calling the main CRL repo `upstream`, vs `origin` for our own personal forks? I've adopted the convention you have here, but I'm wondering if this will break for those that have different remote names?
</blockquote></details>

Good question. I'm not sure how solid of a convention it is. I updated the script to error if the upstream remote URLs do match expectations.
___
*[scripts/bump-pebble.sh, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-MjVxKZp5tID6KcytDBP:-MjWFRKJ6duzrgS9o6mC:b4g0byb) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ae48631c7cde88a9fc904502ebcd0857e27318/scripts/bump-pebble.sh#L68)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

co -> checkout to make it more general
</blockquote></details>

oops, done!

**Review by nicktrav — APPROVED** [review]
LGTM!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-:-Mj_1XHg9L-aOJ8Wcrk0:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @nicktrav)

**Review by jbowens — COMMENTED** [review]
TFTR!

bors r=nicktrav

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68928#-:-Mj_FwMH1DrN-KsBbjA7:b1zv9gn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @nicktrav)

**Pull request merged**
