### PR TITLE
compactor: never stop the loop

### LINKED ISSUE #21824: storage: compactions and consistency checks queued over more than a week
Reported by forums user leokwan: 
https://forum.cockroachlabs.com/t/upgrade-to-v2-0-alpha-20180122/1312

"
I’ve a 5 nodes idle cluster running v2.0-alpha.20171218. I shut down all nodes, and do a upgrade to v2.0-alpha.20180122. The upgrade seems to be success; however, the Consistency Checker Queue keeps growing

ccq

And then I may see some nodes become dead on the overview page, but it will come back to normal after a few minutes. However, it will become dead again later.

I check the log on the server, I may see some warnings like this for all nodes

```
W180126 16:52:57.404974 734198 kv/dist_sender.go:1261 [ts-poll,n1] have been waiting 1m0s sending RPC to r9005 (currently pending: [(n5,s5):3]) for batch: Merge [/System/tsd/cr.store.tscache.skl.write.rotations/1/10s/2018-01-26T16:00:00Z,/Min) 
W180126 16:52:57.405259 228 kv/dist_sender.go:1261 [ts-poll,n1] have been waiting 1m0s sending RPC to r21 (currently pending: [(n3,s3):8]) for batch: Merge [/System/tsd/cr.store.valcount/1/10s/2018-01-26T16:00:00Z,/Min) 
W180126 16:52:57.405306 734199 kv/dist_sender.go:1261 [ts-poll,n1] have been waiting 1m0s sending RPC to r3434 (currently pending: [(n1,s1):4]) for batch: Merge [/System/tsd/cr.store.valbytes/1/10s/2018-01-26T16:00:00Z,/Min) 
W180126 16:53:00.329842 249 storage/node_liveness.go:426 [n1,hb] slow heartbeat took 4.5s 
W180126 16:53:00.329860 249 storage/node_liveness.go:365 [n1,hb] failed node liveness heartbeat: context deadline exceeded
W180126 16:53:00.812591 735175 storage/node_liveness.go:426 [n1,s1,r1028/7:/System/tsd/cr.node.sql.…] slow heartbeat took 6.2s
W180126 16:53:00.812967 735177 storage/node_liveness.go:426 [n1,s1,r344/1:/System/tsd/cr.node.sql.mem.a…] slow heartbeat took 6.2s
W180126 16:53:00.813158 735148 storage/node_liveness.go:426 [n1,s1,r9218/6:/System/tsd/cr.node.sql.mem.a…] slow heartbeat took 6.2s
W180126 16:53:00.813452 735179 storage/node_liveness.go:426 [n1,s1,r72/1:/System/tsd/cr.node.sql.exec.…] slow heartbeat took 6.2s
W180126 16:53:00.813757 735234 storage/node_liveness.go:426 [n1,s1,r1544/6:/System/tsd/cr.node.distsende…] slow heartbeat took 6.2s
W180126 16:53:00.813939 735194 storage/node_liveness.go:426 [n1,s1,r9260/4:/System/tsd/cr.node.sql.dists…] slow heartbeat took 6.2s
W180126 16:53:00.814265 735225 storage/node_liveness.go:426 [n1,s1,r9303/1:/System/tsd/cr.node.sql.exec.…] slow heartbeat took 6.2s
W180126 16:53:00.814507 735238 storage/node_liveness.go:426 [n1,s1,r9025/1:/System/tsd/cr.node.sql.exec.…] slow heartbeat took 6.2s
W180126 16:53:00.814718 735227 storage/node_liveness.go:426 [n1,s1,r9457/4:/System/tsd/cr.node.{di…-ex…}] slow heartbeat took 6.2s
W180126 16:53:00.815050 735100 storage/node_liveness.go:426 [n1,s1,r231/7:/System/tsd/cr.node.sql.mem.a…] slow heartbeat took 6.2s
W180126 16:53:00.815257 735230 storage/node_liveness.go:426 [n1,s1,r3369/1:/System/tsd/cr.node.gossip.…] slow heartbeat took 6.2s
W180126 16:53:00.815521 735243 storage/node_liveness.go:426 [n1,s1,r206/1:/System/tsd/cr.node.gossip.co…] slow heartbeat took 6.2s
W180126 16:53:00.815807 735245 storage/node_liveness.go:426 [n1,s1,r9038/1:/System/tsd/cr.node.round-tri…] slow heartbeat took 6.2s
W180126 16:53:00.816024 735251 storage/node_liveness.go:426 [n1,s1,r3486/1:/System/tsd/cr.node.round-tri…] slow heartbeat took 6.2s
W180126 16:53:00.816294 735104 storage/node_liveness.go:426 [n1,s1,r6147/1:/System/tsd/cr.node.gossip.in…] slow heartbeat took 6.2s
W180126 16:53:00.816585 735253 storage/node_liveness.go:426 [n1,s1,r7446/1:/System/tsd/cr.node.sql.mem.c…] slow heartbeat took 6.2s
W180126 16:53:00.816798 735267 storage/node_liveness.go:426 [n1,s1,r9096/1:/System/tsd/cr.node.sql.dists…] slow heartbeat took 6.2s
W180126 16:53:00.817008 735269 storage/node_liveness.go:426 [n1,s1,r9092/1:/System/tsd/cr.node.sql.mem.c…] slow heartbeat took 6.2s
W180126 16:53:00.817234 735271 storage/node_liveness.go:426 [n1,s1,r204/1:/System/tsd/cr.node.sql.mem.c…] slow heartbeat took 6.2s
I180126 16:53:00.817613 174 storage/replica_proposal.go:196 [n1,s1,r1028/7:/System/tsd/cr.node.sql.…] new range lease repl=(n1,s1):7 seq=0 start=1516977068.248659932,5 epo=126 pro=1516985574.658469514,0 following repl=(n1,s1):7 seq=0 start=1516977068.248659932,5 epo=126 pro=1516984961.125563733,0
```

From dstat, all nodes have read/write actions constantly , and it looks like one of the CPU thread would keep busy.

fe78b491aad8c59c6fe3d15f71cd8c21f32de626

The cluster become very unstable. I then downgrade to v2.0-alpha.20171218, the Consistency Checker Queue eventually clear and the cluster looks to be back to normal.

Leo
"

### PR DESCRIPTION
**Pull request by tbg**
The compactor had an optimization that would stop the compactor loop when
no work was to be done.

Unfortunately, the condition to probe this was incorrect. Essentially,
whenever *any* work had been done, the loop stopped and would not reawaken
until the next incoming suggestion. In the absence of such a suggestion,
the skipped existing suggestions would never be revisited, and thus never
discarded. This created confusion as it kept the "queued bytes" metric up.

Refactor the code so that instead of stopping, the loop waits for the max
age before running again (except if there are further suggestions).

It's hard to use timers correctly, so this commit should be scrutinized. In
particular, whether it's correct to call `t.Reset` in a select that does
not read from the timer's channel.

The test change makes `make test PKG=./pkg/storage/compactor` fail every
time on my machine before the fix.

I would suggest not backporting this, at least not until there is a
follow-up bugfix that needs backporting and doesn't apply cleanly on top of
this diff.

Fixes #21824.

Release note (bug fix): Expired compaction suggestions are now dropped not
too soon after they expire. Previously, this could be delayed indefinitely.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/storage/compactor/compactor.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHoVn4BAfLR-HX_DFo:-LDHoVn4BAfLR-HX_DFp:b-1oj86j) ([raw file](https://github.com/cockroachdb/cockroach/blob/87205b2e1027be51e365db12e68bf48f81a5344d/pkg/storage/compactor/compactor.go#L90)):*
> ```Go
> }
> 
> func (c *Compactor) poke() {
> ```

Give this method a comment.

---

*[pkg/storage/compactor/compactor.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHojxPCCODYSTAoKOw:-LDHojxPCCODYSTAoKOx:b-g4wqbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/87205b2e1027be51e365db12e68bf48f81a5344d/pkg/storage/compactor/compactor.go#L111)):*
> ```Go
> 		var timerSet bool
> 
> 		ctx = log.WithLogTagStr(ctx, "compactor", "")
> ```

nit: should this be done outside of the worker? I think that's the pattern we usually use. It probably doesn't matter now, but at the very least it will run `Stopper.Recover` with the log tag as well.

---

*[pkg/storage/compactor/compactor.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHpYBJ0ZYrx70BgI5t:-LDHpYBJ0ZYrx70BgI5u:byhdvig) ([raw file](https://github.com/cockroachdb/cockroach/blob/87205b2e1027be51e365db12e68bf48f81a5344d/pkg/storage/compactor/compactor.go#L194)):*
> ```Go
> func (c *Compactor) processSuggestions(ctx context.Context) (bool, error) {
> 	var cleanup func()
> 	ctx, cleanup = tracing.EnsureContext(ctx, c.st.Tracer, "process suggested compactions")
> ```

Go doesn't like `ctx, cleanup :=`? I figured it would.

---

*[pkg/storage/compactor/compactor.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHrTCM537lmfMUmkPM:-LDHrTCM537lmfMUmkPN:b-lvbxdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b104a961393de9be8d4a1bc01aeb8fda6293dbc4/pkg/storage/compactor/compactor.go#L109)):*
> ```Go
> 		var timer timeutil.Timer
> 		defer timer.Stop()
> 		var isFast bool // whether the timer is on minInterval (false when unset or on maxAge)
> ```

Consider taking this comment one step further and explaining why the timer gets set to minInterval vs maxAge.

---

*[pkg/storage/compactor/compactor.go, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHqI0o9H2z37AQFnxZ:-LDHqI0o9H2z37AQFnx_:b-etrhtm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b104a961393de9be8d4a1bc01aeb8fda6293dbc4/pkg/storage/compactor/compactor.go#L132)):*
> ```Go
> 				if !isFast {
> 					isFast = true
> 					timer.Reset(c.minInterval())
> ```

This is fine. In fact, it's exactly why we need to keep track of `timer.Read`.

---

*[pkg/storage/compactor/compactor.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHqhVk2Wk9GXn8Z3V7:-LDHqhVk2Wk9GXn8Z3V8:b-x9y0vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b104a961393de9be8d4a1bc01aeb8fda6293dbc4/pkg/storage/compactor/compactor.go#L145)):*
> ```Go
> 					// that were skipped for now. Revisit when they are certainly expired.
> 					isFast = false
> 					timer.Reset(c.maxAge())
> ```

Checking my understanding: the omission of this line was the bug, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26039)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-:-LDZQRwbBE9XKBsJqu68:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/compactor/compactor.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHoVn4BAfLR-HX_DFo:-LD_8e4VD7UgQsNlTxtR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87205b2e1027be51e365db12e68bf48f81a5344d/pkg/storage/compactor/compactor.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this method a comment.
</blockquote></details>

Done.

---

*[pkg/storage/compactor/compactor.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHojxPCCODYSTAoKOw:-LD_9IG96bllFM7AVFMb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87205b2e1027be51e365db12e68bf48f81a5344d/pkg/storage/compactor/compactor.go#L111)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: should this be done outside of the worker? I think that's the pattern we usually use. It probably doesn't matter now, but at the very least it will run `Stopper.Recover` with the log tag as well.
</blockquote></details>

Done.

---

*[pkg/storage/compactor/compactor.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHpYBJ0ZYrx70BgI5t:-LD_9T4_1-iMpMVnKC2P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87205b2e1027be51e365db12e68bf48f81a5344d/pkg/storage/compactor/compactor.go#L194)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Go doesn't like `ctx, cleanup :=`? I figured it would.
</blockquote></details>

Done.

---

*[pkg/storage/compactor/compactor.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHrTCM537lmfMUmkPM:-LD_9DFJ-pX8_JryP8Vm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b104a961393de9be8d4a1bc01aeb8fda6293dbc4/pkg/storage/compactor/compactor.go#L109)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider taking this comment one step further and explaining why the timer gets set to minInterval vs maxAge.
</blockquote></details>

Done.

---

*[pkg/storage/compactor/compactor.go, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHqI0o9H2z37AQFnxZ:-LD_9Jca72_rCIedqkfH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b104a961393de9be8d4a1bc01aeb8fda6293dbc4/pkg/storage/compactor/compactor.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is fine. In fact, it's exactly why we need to keep track of `timer.Read`.
</blockquote></details>

Done.

---

*[pkg/storage/compactor/compactor.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26039#-LDHqhVk2Wk9GXn8Z3V7:-LD_9KvBB60KrGLd52XA:bb77ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b104a961393de9be8d4a1bc01aeb8fda6293dbc4/pkg/storage/compactor/compactor.go#L145)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Checking my understanding: the omission of this line was the bug, right?
</blockquote></details>

Yep.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26039)*

**Comment by tschottdorf** [comment]
bors r=bdarnell

**Comment by tschottdorf** [comment]
bors r=bdarnell

Hadn't pushed everything before.

**Comment by tschottdorf** [comment]
bors r=bdarnell

Flake was https://github.com/cockroachdb/cockroach/issues/24528

**Comment by tschottdorf** [comment]
bors r=bdarnell

flake was

> version_upgrade_test.go:222: 0: pq: value differs between gossip (2.0-5) and KV (2.0); try again later (<nil> after 18.494190087s)

**Pull request merged**
