### PR TITLE
sqlproxy: optimize denylist monitoring

### LINKED ISSUE #65694: Refactor denylist monitoring in `proxyHandler.handle`
Currently, in `pkg/ccl/sqlproxyccl/proxy_handler.go` the `proxyHandler.handle` creates a new go routine for each new connection to monitor changes in the denylist and to terminate existing connections in case that the IP or the tenant ID is added to the denylist.

This is a bit of a problem as it isn't feasible to have an extra go routine for each connections when the number of connections is in tens of thousands. 

So we want to refactor this by creating a registry of the active connections. Each new connection should be added to the connection registry on accept and removed once it closes. A single go routine can monitor for changes in the denylist and once detects a change - iterate through all connections in the registry that needs to close and actively close them.

### PR DESCRIPTION
**Pull request by jeffswenson**
Previously each connection spawned a goroutine that polled the denylist. Now
a single goroutine monitors the denylist and connections use channels to listen
for changes.

The `denylist.Watcher` was introduced to watch the denylist and track each of
the listeners. The denylist parsing code in `denylist/file.go` was refactored
to publish denylist changes on a channel instead of mutating an internal structure.
This simplified testing for the denylist.Watcher and removes one of the locks
needed to consult the denylist.

Release note: None
Fixes #65694

### CODE REVIEW

**Review by darinpp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpDNDABV_vfa6Wp9-i:-McpDNDABV_vfa6Wp9-j:bi0tuop) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L159)):*
> ```Go
> 		dl, newDl := denylist.NewDenylistWithFile(ctx, options.Denylist,
> 			denylist.WithPollingInterval(options.PollConfigInterval))
> 		handler.denyListWatcher = denylist.NewWatcher(dl, newDl)
> ```

This may be a bit more compact if you change to `handler.denyListWatcher = denylist.NewDenylistWithFile(ctx, ...).Watcher()`?
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpErb65wqWOA5LYTl7:-McpErb65wqWOA5LYTl8:bqefr0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L223)):*
> ```Go
> 	}
> 
> 	deniedListener, err := handler.denyListWatcher.ListenForDenied(
> ```

Can we change so `deniedListener` doesn't have separate channel, we pass in the `ctx` and `cancel` (which means moving the `ctx, cancel := context.WithCancel(ctx)` before this line), return just `err` and use the context `cancel` function and as a result the channel that the context already has?
So when a connection is flagged as denied, the watcher can just log that and then call cancel.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpNs8F1_0IW_mTtoKF:-McpNs8F1_0IW_mTtoKG:b8kn7ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L230)):*
> ```Go
> 		return err
> 	}
> 	defer handler.denyListWatcher.RemoveListener(deniedListener)
> ```

The `deniedListener` can actually be func doing this line, so the defer is just `defer removeListener()`. Assuming that we don't need the channel that it has and use the context's`cancel`
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpJjn_2-4hhJHjgNjU:-McpJjn_2-4hhJHjgNjV:b-pce8j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L369)):*
> ```Go
> 		handler.metrics.updateForError(err)
> 		return err
> 	case err := <-deniedListener.Denied:
> ```

If we use the context cancel we won't need to have separate channel and this block. The metrics update can be part of the cancel callback (so instead of passing `cancel` as cancellation func you can pass `func() { handler.metrics.updateForError(...); cancel() }`. 
___
*[pkg/ccl/sqlproxyccl/denylist/watcher.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpOxh5BZfrDQioNkD4:-McpOxh5BZfrDQioNkD5:b-odk2v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/denylist/watcher.go#L118)):*
> ```Go
> 
> func (w *Watcher) updateDenyList(list *Denylist) {
> 	w.mu.Lock()
> ```

Not sure if it is an issue that we are locking for the duration of the traversal. With thousands of connections, wouldn't that be a problem? Would it make sense to convert the `listeners` to a map keyed on the item/type being denied (similar to `DenyList.entries`), have it be `sync.Map` perhaps and not block new connections from being added (or checked against the map) while updating? The value in that case will be the list of listeners and may have separate lock that would block just the given tenant/IP. As far as I can see, we will do one traversal per polling interval ... correct?

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpDNDABV_vfa6Wp9-i:-McupFl_2d5yLVL4k0LG:b-65omkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L159)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

This may be a bit more compact if you change to `handler.denyListWatcher = denylist.NewDenylistWithFile(ctx, ...).Watcher()`?
</blockquote></details>

Done. I added the WatcherFromFile method.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpErb65wqWOA5LYTl7:-Mcu0tdE1NK8VMetiBNn:b-5b0oop) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L223)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

Can we change so `deniedListener` doesn't have separate channel, we pass in the `ctx` and `cancel` (which means moving the `ctx, cancel := context.WithCancel(ctx)` before this line), return just `err` and use the context `cancel` function and as a result the channel that the context already has?
So when a connection is flagged as denied, the watcher can just log that and then call cancel.
</blockquote></details>

I prefer the semantics of returning a channel to accepting a callback function. If we iterate with a lock, calling a function risks deadlocking if the callback interacts with the watcher.

If we iterate with something like sync map (or any other non-blocking strategy), the semantics of remove are tricky. It's possible the callback will fire after remove returns successfully. E.x. the following code would contain a data race.

object := someObject()
removeListener := watcher.AddListener(connection, func() {
   object = nil
})
removeListener()
if object != nil {
    object.DoSomething() // object may be nil
}
___
*[pkg/ccl/sqlproxyccl/denylist/watcher.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpOxh5BZfrDQioNkD4:-Mcubvmo0-L7ZECidEEu:b-izcz42) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/denylist/watcher.go#L118)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

Not sure if it is an issue that we are locking for the duration of the traversal. With thousands of connections, wouldn't that be a problem? Would it make sense to convert the `listeners` to a map keyed on the item/type being denied (similar to `DenyList.entries`), have it be `sync.Map` perhaps and not block new connections from being added (or checked against the map) while updating? The value in that case will be the list of listeners and may have separate lock that would block just the given tenant/IP. As far as I can see, we will do one traversal per polling interval ... correct?
</blockquote></details>

I did not know about SyncMap. I read the source code and wrote a little benchmark. Unfortunately it doesn't help us if the goal is to reduce connection setup latency. Internally sync.Map maintains two maps. A "read only" and a "dirty" map. map.Range requires a stable set of keys, so calling Range causes sync.Map to lock itself and replace the read only map with the dirty map. This operation is fast, but the next insertion into the sync.Map needs to recreate the dirty map. The dirty map is a copy of the entire map, and this operation actually blocks new connection creation for slightly more time than consulting the denylist while holding the mutex. 

Benchmark:
https://gist.github.com/JeffSwenson/3555477e0367c201586efbfeea63b315

```
jeffswenson@Jeffs-MBP iteration_benchmark % go test -bench . iteration_test.go
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkMap-16        	     136	   9181502 ns/op
BenchmarkSyncMap-16    	     100	  11284644 ns/op
```

Idea 1: Track New/Removed Listeners in a Map
Instead of maintaining a single map of listeners, the watcher would contain a map tracking changes to listeners. Periodically the watcher's goroutine would lock the structure, replace the change map with an empty map, unlock the watcher, then update an internal data structure owned by the goroutine. 
 
Idea 2: Sharded Map
Instead of maintaining a single hash map, the watcher contains multiple hashmaps each with their own mutex. This reduces the amount of time each hash map is locked while the goroutine iterates over it. Sharding the map 16 ways would reduce wait time to <1 ms. This is actually the strategy I've seen most often for contended hash maps. We could even implement the same interface as sync.Map, but avoid the copy overhead.

Idea 3: 
Use a map[item]map[int64]*Listener to track the listeners instead. This is the simplest, but may degrade badly if we need to push a large denylist (e.x. a machine generated denylist with thousands of blocked ips). I prefer looping over the connections, because it minimizes the performance impact of pushing a large config. Generally I want runtime config changes to be as safe as possible. 


WDYT?

**Review by darinpp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpErb65wqWOA5LYTl7:-Mcv7iQhAnFwZ5fK88Hq:b6ycv10) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L223)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

I prefer the semantics of returning a channel to accepting a callback function. If we iterate with a lock, calling a function risks deadlocking if the callback interacts with the watcher.

If we iterate with something like sync map (or any other non-blocking strategy), the semantics of remove are tricky. It's possible the callback will fire after remove returns successfully. E.x. the following code would contain a data race.

object := someObject()
removeListener := watcher.AddListener(connection, func() {
   object = nil
})
removeListener()
if object != nil {
    object.DoSomething() // object may be nil
}
</blockquote></details>

There is no reason for the cancel function to interact with the watcher.  We simply want it to close the cancellable context's channel. This is what is used when the proxy shuts down and will be used as well for tracking session expiration for the su proxy. The deny list isn't special so no need to add separate channels for each of the sources that can trigger cancellation. Canceling the connection's context is good enough for all the sources.

Not sure how the semantics are tricky. Firing the cancellation func after the connection is removed is not a problem. The cancellation func doesn't have anything to do with the connection but just closes the connection context's channel.
___
*[pkg/ccl/sqlproxyccl/denylist/watcher.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpOxh5BZfrDQioNkD4:-Mcv6IRl7weB7tjZ2JG8:b-hhet37) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/denylist/watcher.go#L118)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

I did not know about SyncMap. I read the source code and wrote a little benchmark. Unfortunately it doesn't help us if the goal is to reduce connection setup latency. Internally sync.Map maintains two maps. A "read only" and a "dirty" map. map.Range requires a stable set of keys, so calling Range causes sync.Map to lock itself and replace the read only map with the dirty map. This operation is fast, but the next insertion into the sync.Map needs to recreate the dirty map. The dirty map is a copy of the entire map, and this operation actually blocks new connection creation for slightly more time than consulting the denylist while holding the mutex. 

Benchmark:
https://gist.github.com/JeffSwenson/3555477e0367c201586efbfeea63b315

```
jeffswenson@Jeffs-MBP iteration_benchmark % go test -bench . iteration_test.go
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkMap-16        	     136	   9181502 ns/op
BenchmarkSyncMap-16    	     100	  11284644 ns/op
```

Idea 1: Track New/Removed Listeners in a Map
Instead of maintaining a single map of listeners, the watcher would contain a map tracking changes to listeners. Periodically the watcher's goroutine would lock the structure, replace the change map with an empty map, unlock the watcher, then update an internal data structure owned by the goroutine. 
 
Idea 2: Sharded Map
Instead of maintaining a single hash map, the watcher contains multiple hashmaps each with their own mutex. This reduces the amount of time each hash map is locked while the goroutine iterates over it. Sharding the map 16 ways would reduce wait time to <1 ms. This is actually the strategy I've seen most often for contended hash maps. We could even implement the same interface as sync.Map, but avoid the copy overhead.

Idea 3: 
Use a map[item]map[int64]*Listener to track the listeners instead. This is the simplest, but may degrade badly if we need to push a large denylist (e.x. a machine generated denylist with thousands of blocked ips). I prefer looping over the connections, because it minimizes the performance impact of pushing a large config. Generally I want runtime config changes to be as safe as possible. 


WDYT?
</blockquote></details>

I was suggesting what you have as Idea 3. Index the connections into one or two maps (by ip/tenant id with type into one map or without type into two maps), do the traversal on the denylist and the lookups on the connection index(es). If the `sync.Map` is not good - just lock RW mutex on each lookup. Don't worry right now for the impact of a large denylist. We will try to do something else if we have to support this.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpErb65wqWOA5LYTl7:-Md-5J8j1gMGgRWo-pDx:b-2isohy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L223)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

There is no reason for the cancel function to interact with the watcher.  We simply want it to close the cancellable context's channel. This is what is used when the proxy shuts down and will be used as well for tracking session expiration for the su proxy. The deny list isn't special so no need to add separate channels for each of the sources that can trigger cancellation. Canceling the connection's context is good enough for all the sources.

Not sure how the semantics are tricky. Firing the cancellation func after the connection is removed is not a problem. The cancellation func doesn't have anything to do with the connection but just closes the connection context's channel.
</blockquote></details>

The one problem with cancelling the context is that we get a generic "context cancelled" error rather than something more custom. Jeff suggested using a `func(err error)` callback instead, which is similar, but lets the watcher construct a nicer error.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-Md-5xvUEJDI8bDF888B:-Md-5xvUEJDI8bDF888C:bb4qr3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b1b55cd4b94bb26805e1288141f897eaf9a3a6/pkg/ccl/sqlproxyccl/proxy_handler.go#L225)):*
> ```Go
> 		denylist.ConnectionTags{IP: ipAddr, Cluster: tenID.String()})
> 	if err != nil {
> 		err = newErrorf(codeProxyRefusedConnection, "connection matched denylist: %v", err)
> ```

I believe this will be a customer-facing error (see `sendErrToClient`). I don't think we want to provide internal details like this. I'd just say something generic like `connection refused`, with no further details. Instead, log the details here so we're able to see them.

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @darinpp)

___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpErb65wqWOA5LYTl7:-Md2cOJU05f1a3agLkfT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L223)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The one problem with cancelling the context is that we get a generic "context cancelled" error rather than something more custom. Jeff suggested using a `func(err error)` callback instead, which is similar, but lets the watcher construct a nicer error.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpNs8F1_0IW_mTtoKF:-Md2bLnNC1vyybQrE1k9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L230)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

The `deniedListener` can actually be func doing this line, so the defer is just `defer removeListener()`. Assuming that we don't need the channel that it has and use the context's`cancel`
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpJjn_2-4hhJHjgNjU:-Md2bPKkDWkdZo341Ozm:b-oleniq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/proxy_handler.go#L369)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

If we use the context cancel we won't need to have separate channel and this block. The metrics update can be part of the cancel callback (so instead of passing `cancel` as cancellation func you can pass `func() { handler.metrics.updateForError(...); cancel() }`. 
</blockquote></details>

Done. I ended up reusing the errConnectionCopy channel to report the error.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-Md-5xvUEJDI8bDF888B:-Md3B8Ce1qitH09Smnrk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3b1b55cd4b94bb26805e1288141f897eaf9a3a6/pkg/ccl/sqlproxyccl/proxy_handler.go#L225)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I believe this will be a customer-facing error (see `sendErrToClient`). I don't think we want to provide internal details like this. I'd just say something generic like `connection refused`, with no further details. Instead, log the details here so we're able to see them.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/denylist/watcher.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-McpOxh5BZfrDQioNkD4:-Md2bs3T7LWOrAXRVEmp:b-o7879o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65701c5e9628035f61e2cb80fc96e9ac1bc71dc/pkg/ccl/sqlproxyccl/denylist/watcher.go#L118)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

I was suggesting what you have as Idea 3. Index the connections into one or two maps (by ip/tenant id with type into one map or without type into two maps), do the traversal on the denylist and the lookups on the connection index(es). If the `sync.Map` is not good - just lock RW mutex on each lookup. Don't worry right now for the impact of a large denylist. We will try to do something else if we have to support this.
</blockquote></details>

I've switched the map over to a btree. It's effectively a drop in replacement for the map, but the btree has a O(1) clone operation that allows us to iterate here without blocking new connections.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-:-Md7dXsoDGVDfyp72f8o:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/denylist/watcher.go, line 21 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-Md7dNV74elgbHUfq7th:-Md7dNV74elgbHUfq7ti:b-i5vadr) ([raw file](https://github.com/cockroachdb/cockroach/blob/be173169696d0a46b0d03f696f45af7756782909/pkg/ccl/sqlproxyccl/denylist/watcher.go#L21)):*
> ```Go
> // Watcher maintains a list of connections waiting for changes to the
> // denylist. If a connection is added to the denylist, the watcher notifies
> // the connection via the Listener.Denied channel.
> ```

NIT: Would be good to add a comment saying that all methods on `Watcher` are thread-safe.
___
*[pkg/ccl/sqlproxyccl/denylist/watcher.go, line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-Md7d8Dt2Knx2RkWdiIh:-Md7d8Dt2Knx2RkWdiIi:bojme7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/be173169696d0a46b0d03f696f45af7756782909/pkg/ccl/sqlproxyccl/denylist/watcher.go#L126)):*
> ```Go
> 	l := &listener{
> 		id: id,
> 		// The channel is buffered so that the watcher does not need to block when inserting
> ```

NIT: out-of-date comment

**Review by darinpp — COMMENTED** [review]
Looks good. You will also need to delete `util.Jitter` that isn't used anywhere else after your changes. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-:-MdFPhaF3ELbu5XT4qj8:bl3h5rj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

**Review by darinpp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-:-MdFPlfD8EZVqajkvdxN:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

**Review by jaylim-crl — COMMENTED** [review]
Once this gets merged, we need to bump the SHA in the CC repo (i.e. `manifests.SqlproxyImage`), and update the `TestIntegrationSQLProxy` test to reflect the new changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66681#-:-MdIOqzx-EyIbyIvFySM:bl8xdzy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @darinpp)

**Pull request merged**
