### PR TITLE
kv/storage: Add metrics that track wedged requests

### LINKED ISSUE #12001: storage: add metric for stuck/wedged operations
During processing of a request, there are several places an operation can either block for a long period of time or retry excessively. We should add a handful of metrics to instrument those places to catch operations that are taking longer than some threshold value (e.g. `60s`). Some examples of places to instrument: waiting in the command queue, waiting trying to acquire the lease, waiting for Raft to process a request, and waiting at the `DistSender` for an RPC to return. I'm thinking of the corresponding metrics as being part of a group: `requests.wedged.{commandqueue,lease,raft,distsender}`.

See #12000.

Cc @cockroachdb/stability

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #12001

Make sure I hit the all the right spots, I'm not very confident I did.

@petermattis

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12106)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: This captures the problems spots I was thinking of. Should we bikeshed the name `wedged`? 

@tamird Yes, there isn't necessarily a difference between `wedged` and `slow`. So perhaps `s/wedged/slow/g`. I'm not quite sure why you think this approach feels hacky. I haven't heard of an alternative that will give us as clear a signal about these slow/wedged requests.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-:-KYKm5kI3-Zsj3ViL7nX:beo9it4)*

**Comment by a-robinson** [comment]
Switched from "wedged" to "slow".

It doesn't generalize, but it does seem to provide useful information. Counting in-flight requests or total time spent in queue don't seem like they'd make a few outliers all that apparent, particularly in clusters with a lot of throughput.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-:-KYKvu671vmaFNbxVStz:b-9roh0n)*

**Comment by bdarnell** [comment]
I think instead of a counter of all commands which have ever reached the threshold, I'd rather see a gauge of requests that have taken that long and are still in progress (i.e. increment the metric when the timer fires, and when a request finishes with `nil` `slowTimer`, decrement it again). That would potentially show some revealing patterns, like if some event unblocks a lot of requests at once. 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-:-KYOUsr_3GhfTf9hhJQz:b73uz7e)*

**Comment by petermattis** [comment]
@bdarnell's suggestion sounds reasonable to me.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-:-KYOq1sH8wmkby05ie1_:bqyptz8)*

**Comment by a-robinson** [comment]
I agree with the suggestion, but the Coda Hale metrics library we're using doesn't make it easy, since it seemingly offers no way to atomically increment or decrement gauges, only to read their value and set their value. 

I can't imagine this one deficiency would make it worth the pain to switch to a different metrics library, so I guess I'll wrap the gauge type with a new type :/

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-:-KYOzcWO2Y-wtXaSqx3U:b-2nj66p)*

**Comment by a-robinson** [comment]
PTAL - I've added an IncrementableGauge type and used it for the new metrics. It gets exported from the process in exactly the same way as the normal Gauge type.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-:-KYP5oak5bPWRG6brG6B:b-e0fd5e)*

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/kv/dist_sender.go, line 1168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-KYPCBVm11cZyaC3_wZk:-KYPCBVmBUHhe14vdKk_:b6qq5aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c224eef31d11cc2ff64a1e8fd877f52282a11c5/pkg/kv/dist_sender.go#L1168)):*
> ```Go
> 				base.SlowRequestThreshold, args.Summary())
> 			ds.metrics.SlowRequestsCount.Inc(1)
> 			defer ds.metrics.SlowRequestsCount.Dec(1)
> ```

Nice use of `defer`.

---

*[pkg/util/metric/metric.go, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-KYPBtklBFWBJC7I70em:-KYPBtkl23WM_pFoWKUy:b-djkzd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcf3dd40aa8805bc3b40efc8ec4b1defad968f8d/pkg/util/metric/metric.go#L392)):*
> ```Go
> // NewIncrementableGauge creates a IncrementableGauge.
> func NewIncrementableGauge(metadata Metadata) *IncrementableGauge {
> 	return &IncrementableGauge{Gauge: Gauge{metadata, metrics.NewGauge()}}
> ```

`metrics.StandardGauge` is quite simple. I wonder if you should have a fork of it here which adds the `Inc` and Dec` methods using atomics. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-:-KYPCJIl45BlrYsgaCtw:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/metric/metric.go, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-KYPBtklBFWBJC7I70em:-KYPFjoRA_IGFpulFuds:b-xg8edz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcf3dd40aa8805bc3b40efc8ec4b1defad968f8d/pkg/util/metric/metric.go#L392)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`metrics.StandardGauge` is quite simple. I wonder if you should have a fork of it here which adds the `Inc` and Dec` methods using atomics. 
</blockquote></details>

Updated to give that approach a try. It feels like a lot of extra (duplicated) code just to avoid adding the lock, but I suppose it's not like we modify this code often. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106)*

**Comment by petermattis** [comment]
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/util/metric/metric.go, line 387 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-KYPIvQs0xFrW9D4pu93:-KYPIvQsAb_QCzAv0f-P:b-wrtq7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/140c8753f6c48911cfee7bb4f2934aea79722ca9/pkg/util/metric/metric.go#L387)):*
> ```Go
> type IncrementableGauge struct {
> 	Metadata
> 	*incrementableGauge
> ```

Yeah, there is some unfortunate replication there. An alternative is:

```
type IncrementableGauge struct {
  Gauge
  internal incrementableGauge
}
```

Then `incrementableGauge` would only have to implement the `metrics.Gauge` interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106)*

**Comment by a-robinson** [comment]
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/metric/metric.go, line 387 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-KYPIvQs0xFrW9D4pu93:-KYPKMrg2UY8xmPEbxvI:b-1vpfix) ([raw file](https://github.com/cockroachdb/cockroach/blob/140c8753f6c48911cfee7bb4f2934aea79722ca9/pkg/util/metric/metric.go#L387)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yeah, there is some unfortunate replication there. An alternative is:

```
type IncrementableGauge struct {
  Gauge
  internal incrementableGauge
}
```

Then `incrementableGauge` would only have to implement the `metrics.Gauge` interface.
</blockquote></details>

If we do that, then we'd have to manually capture the metrics.Gauge interface's methods and pass them to internal. At that point, we could just embed the value into IncrementableGauge instead. And if we go that far, why not just merge Gauge with IncrementableGauge, since we've already gotten to the point of re-implementing metrics.Gauge?

I've switched things around to work like that. I think we should either go with this or with the original lock-based approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/metric/metric.go, line 387 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106#-KYPIvQs0xFrW9D4pu93:-KYPOT6y6K0xlbUX_D8O:btfp6k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/140c8753f6c48911cfee7bb4f2934aea79722ca9/pkg/util/metric/metric.go#L387)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

If we do that, then we'd have to manually capture the metrics.Gauge interface's methods and pass them to internal. At that point, we could just embed the value into IncrementableGauge instead. And if we go that far, why not just merge Gauge with IncrementableGauge, since we've already gotten to the point of re-implementing metrics.Gauge?

I've switched things around to work like that. I think we should either go with this or with the original lock-based approach.
</blockquote></details>

This approach looks good to me. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12106)*

**Pull request merged**
