### PR TITLE
cli: avoid using special unicode characters to mark newlines

### LINKED ISSUE #18507: sql/cli: pretty results force-close the k8s interactive client with "New state of 'nil' is invalid."
**BUG REPORT**

When running this query

```
select manifest from build_version_details;
```

from a container started with

```
kubectl run cockroachdb-client -it --image=cockroachdb/cockroach:v1.0.6 --rm --restart=Never -- sql
```

against the following table (source: https://github.com/estafette/estafette-ci-api/blob/master/cockroach/migrations/00006_create_build_version_details_table.sql)

```
CREATE TABLE build_version_details (
  id INT PRIMARY KEY DEFAULT unique_rowid(),
  build_version VARCHAR(256),
  repo_source VARCHAR(256),
  repo_full_name VARCHAR(256),
  repo_branch VARCHAR(256),
  repo_revision VARCHAR(256),
  manifest TEXT,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE INDEX build_version_details_build_version_repo_source_repo_full_name_idx (build_version, repo_source, repo_full_name)
);
```

in a CockroachDB version 1.0.6 cluster running on Google Container Engine version 1.7.3 it fails and shows the following error or something similar, but always ending in `New state of 'nil' is invalid.`:

```
root@cockroachdb-public:26257/estafette_ci_api> select manifest from build_version_details;
E0915 16:54:22.973396    5620 v2.go:147] New state of 'nil' is invalid.
```

This seems to be caused by type TEXT, because querying any of the other fields works fine:

```
select id,build_version,repo_source,repo_full_name,repo_branch,repo_revision from build_version_details;
```

From my golang application using library github.com/lib/pq it works fine though, so the data seems to be okay.

**logs**

All nodes start with the following logs:

```
2017-09-14 19:28:20 | WARNING | RUNNING IN INSECURE MODE! | cli/start.go:587
-- | -- | -- | --
2017-09-14 19:28:20 | INFO | line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓ | util/log/clog.go:1013
2017-09-14 19:28:20 | INFO | [config] arguments: [/cockroach/cockroach start --logtostderr --insecure --host cockroachdb-0.cockroachdb.estafette.svc.cluster.local --http-host 0.0.0.0 --join cockroachdb-public] | util/log/clog.go:1013
2017-09-14 19:28:20 | INFO | [config] binary: CockroachDB CCL v1.0.6 (linux amd64, built 2017/09/14 15:15:48, go1.8.3) | util/log/clog.go:1013
2017-09-14 19:28:20 | INFO | [config] running on machine: cockroachdb-0 | util/log/clog.go:1013
2017-09-14 19:28:20 | INFO | [config] file created at: 2017/09/14 19:28:20 | util/log/clog.go:1013
2017-09-14 19:28:20 | INFO | CockroachDB CCL v1.0.6 (linux amd64, built 2017/09/14 15:15:48, go1.8.3) | cli/start.go:593
2017-09-14 19:28:20 | INFO | system total memory: 2.0 GiB | server/config.go:375
2017-09-14 19:28:20 | INFO | server configuration: | server/config.go:377
2017-09-14 19:28:20 | INFO | starting cockroach node | cli/start.go:340
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #18507.

Prior to this patch, the 'pretty' formatter would use the special
character '␤' to mark newline characters in multi-line rows. This was
intended to distinguish multi-line rows from multiple one-line rows
when the table has a single column.

Unfortunately this choice causes issues in the wild, for example users
have reported that this confuses the k8s controller on Windows.

This patch removes the special characters and instead simply renders
multi-line cells as wrapped multi-paragraph, for increased readability.

Example table that remains unchanged:
```
root@:26257/> values (1,'a'), (2,'b');
+---------+---------+
| column1 | column2 |
+---------+---------+
|       1 | a       |
|       2 | b       |
+---------+---------+
(2 rows)
```

Example table where cells contain newline characters:
```
root@:26257/> values (1,e'a\nb\nc'), (2,e'd\ne');
+---------+---------+
| column1 | column2 |
+---------+---------+
|       1 | a       |
|         |         |
|         | b       |
|         |         |
|         | c       |
|       2 | d       |
|         |         |
|         | e       |
+---------+---------+
(2 rows)
```

Example of paragraph wrapping; before:
```
root@:26257/startrek> select * from quotes where characters ilike 'vanna%';
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+----------+---------+
|                                                                                                                quote                                                                                                                 |   characters   | stardate | episode |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+----------+---------+
| "It's hard to believe that something which is neither seen nor felt can do so much harm." "That's true.  But an idea can't be seen or felt.  And that's what kept the Troglytes in the mines all these centuries.  A mistaken idea." | Vanna and Kirk |   5819.0 |      76 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+----------+---------+
(1 row)
```

After:

```
root@:26257/startrek> select * from quotes where characters ilike 'vanna%';
+--------------------------------+----------------+----------+---------+
|             quote              |   characters   | stardate | episode |
+--------------------------------+----------------+----------+---------+
| "It's hard to believe that     | Vanna and Kirk |   5819.0 |      76 |
| something which is neither     |                |          |         |
| seen nor felt can do so much   |                |          |         |
| harm." "That's true.  But an   |                |          |         |
| idea can't be seen or felt.    |                |          |         |
|  And that's what kept the      |                |          |         |
| Troglytes in the mines all     |                |          |         |
| these centuries.  A mistaken   |                |          |         |
| idea."                         |                |          |         |
+--------------------------------+----------------+----------+---------+
(1 row)
```

Release note (cli change): the `pretty` formatter does not introduce
special unicode characters in multi-line table cells, for better
compatibility with certain clients. To disambiguate multi-line cells
from multiple single-line cells, a user can use WITH ORDINALITY to add
a row numbering column.

### CODE REVIEW

**Comment by jordanlewis** [comment]
I find the new format confusing. It's not obvious to me what the `+` column is about, and I don't think it will be obvious to users either. Thanks for thinking about this! But I think we need to think of some other ideas.

**Comment by knz** [comment]
@jordanlewis `psql` does the same more or less. I'm not inventing anything.

**Comment by knz** [comment]
Also please consider that multi-line cells are exceedingly rare.

**Comment by jordanlewis** [comment]
For posterity, here's `psql`:

```
jordan=# create table foo (a int, b text);
CREATE TABLE
jordan=# insert into foo values(1, 'foo');
INSERT 0 1
jordan=# insert into foo values(2, 'foo;
jordan'# bar');
INSERT 0 1
jordan=# insert into foo values(3, 'foo');
INSERT 0 1
jordan=# select * from foo;
 a |  b
---+------
 1 | foo
 2 | foo;+
   | bar
 3 | foo
(3 rows)
```

**Comment by jordanlewis** [comment]
```
sqlite> create table foo (a int, b text);
sqlite> insert into foo values(1, 'foo');
sqlite> insert into foo values(2, 'foo
   ...> bar');
sqlite> insert into foo values(3, 'foo');
sqlite> select * from foo;
1|foo
2|foo
bar
3|foo
```

```
mysql> create table foo (a int, b text);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into foo values(1, 'foo');
Query OK, 1 row affected (0.01 sec)

mysql> insert into foo values(2, 'foo
    '> bar');
Query OK, 1 row affected (0.00 sec)

mysql> insert into foo values(3, 'foo');
Query OK, 1 row affected (0.01 sec)

mysql> select * from foo;
+------+---------+
| a    | b       |
+------+---------+
|    1 | foo     |
|    2 | foo
bar |
|    3 | foo     |
+------+---------+
3 rows in set (0.00 sec)
```

**Comment by knz** [comment]
Yes I think we can agree that neither sqlite nor mysql give examples to follow.

We could do `psql` closely but that requires a change in the upstream `tablewriter` which is so niche that I doubt the upstream maintainer will accept the PR. Hence my choice for an extra column. In the 2.1 timeframe I want to address #21660 which will probably imply introducing a simpler, more adequate pretty-printer.

**Comment by jordanlewis** [comment]
I'm okay with it. Can we think of a title to give the column that will help users understand? Also I think you should add a test where the column with newlines isn't the final column in the table.

**Comment by knz** [comment]
I'd like to keep the title 1 character wide to keep the column unobtrusive. Would a single `\` be OK as column title?

Alternatively (or in combination) we can add a text sentence just before the table to remind the user what to expect. Like this:

```
root@:26257/> values (1,e'a\nb\nc'), (2,e'd\ne');
Note: a + in the last column indicates that the next line continues the current row.
+---------+---------+---+
| column1 | column2 |   |
+---------+---------+---+
|       1 | a       | + |
|         | b       | + |
|         | c       |   |
|       2 | d       | + |
|         | e       |   |
+---------+---------+---+
(2 rows)
```

**Comment by jordanlewis** [comment]
Yeah putting a `\` seems okay, or maybe one of those special newline characters. Another option is using a `\` instead of a `+`, since `\` is commonly used to indicate a line continuation.

**Comment by jordanlewis** [comment]
Nevermind about the special newline character, obviously the point of this patch is to banish it completely.

**Comment by bdarnell** [comment]
I don't like the new column; there's no clear precedent for showing line continuations this way. Now that we've iterated on a few different ways to show newlines in an ascii-art tabular format, I'm coming to the conclusion that simply letting the raw newline break the layout as in sqlite and mysql is the best approach. It's simple to implement and to explain, and it retains the ability to copy/paste the string with its newlines. It's not perfect, but none of the options are, and I think that it's better to do the simple thing here and move on. If you need to handle data that may contain newlines, you'll have a better experience in a GUI tool or a programmatic interface than in an ascii-art CLI shell.  (all our demonstrations of this feature are using very short lines, but realistically if there are newlines, there are probably going to be 80+-column lines and those are just never going to be practical in this kind of environment)

My second choice after breaking the layout is to render newlines as `\n` and apply backslash escaping in the pretty format, so we force everything into a single line per record instead of trying to present multi-line data within a single record. 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/cli_test.go, line 824 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22324#-L4YUR-Wd3mXqyvWt5JO:-L4YUR-Wd3mXqyvWt5JP:b-9ld3my) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2a5041394ec33bc2fff4dcdf33c7e4bf42ff6c9/pkg/cli/cli_test.go#L824)):*
> ```Go
> 	// |     Field      | Type | Null | Default | Indices |   |
> 	// +----------------+------+------+---------+---------+---+
> 	// | f"oo           | INT  | true | NULL    | {}      |
> ```

Some of these lines appear to be missing their trailing pipes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22324#-:-L4YUTopbMhAR1foySmD:b-t0q5gs)*

**Comment by knz** [comment]
So I too have been thinking about this more. 

While I strongly disagree with you Ben that it is acceptable to render newline characters as-is (the UX is terrible), I also realized something fundamental: my approach so far was assuming it was essential to distinguish multi-line rows from multiple one-line rows. But this assumption is mistaken! It is mistaken because for any query, a user who wishes to disambiguate visually can always use WITH ORDINALITY. 

In other words, as usual, I was torturing myself to solve a problem that didn't really exist. (hah!)

So, strong with this newfound confidence, and letting go of complexity that I had mistakenly perceived as necessary, here's a new version of this PR: it simply renders the multi-line rows with no special treatment for newlines.

It also, as a bonus, introduces paragraph wrapping.  Since the `pretty` format was never meant to be information-preserving, and WITH ORDINALITY can always be used to determine row boundaries, I think the visual compactness is a net win.

What do you think? PTAL

**Comment by jordanlewis** [comment]
Interesting idea. It does look rather nice.

I'm concerned that it'll be confusing to users that the number of output rows reported may not be the same as the number of rows pretty printed. You can easily make an ambiguous case by having some rows with newlines and some rows with empty string values in the non-newline column... and the average user doesn't know what `WITH ORDINALITY` is or why they should care to learn.

I know it's okay for the pretty format to be lossy, but it seems that we're introducing more lossiness over time, which is concerning.

**Comment by knz** [comment]
Again remember that multi-line rows/cells are comparatively rather rare.

**Comment by jordanlewis** [comment]
Okay, fair enough. :lgtm: 

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r3.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22324#-:-L4gOFZdWckicRvHa7fC:b-if8afx)*

**Comment by knz** [comment]
TFYR!

**Comment by jordanlewis** [comment]
```
root@:26257/> show all cluster settings;
+---------------------------------------------------+-------------------------------------+------+--------------------------------------------------------------------------+
|                       name                        |            current_value            | type |                               description                                |
+---------------------------------------------------+-------------------------------------+------+--------------------------------------------------------------------------+
| cloudstorage.gs.default.key                       |                                     | s    | if set, JSON key to use during Google Cloud Storage operations           |
| cloudstorage.http.custom_ca                       |                                     | s    | custom root CA (appended to system's default CAs) for verifying          |
|                                                   |                                     |      | certificates when interacting with HTTPS storage                         |
| cluster.organization                              | Cockroach Labs - Production Testing | s    | organization name                                                        |
| debug.panic_on_failed_assertions                  | false                               | b    | panic when an assertion fails rather than reporting                      |
| diagnostics.reporting.enabled                     | true                                | b    | enable reporting diagnostic metrics to cockroach labs                    |
| diagnostics.reporting.interval                    | 1h0m0s                              | d    | interval at which diagnostics data should be reported                    |
| diagnostics.reporting.send_crash_reports          | true                                | b    | send crash and panic reports                                             |
| kv.allocator.lease_rebalancing_aggressiveness     | 1E+00                               | f    | set greater than 1.0 to rebalance leases toward load more aggressively,  |
|                                                   |                                     |      | or between 0 and 1.0 to be more conservative about rebalancing leases    |
```

Do you really think this looks good? If you're reading the right hand string column, you have to use the clue of whether the middle column has a value in it to figure out whether you're on a new row or not. I find this exceptionally hard to read, to be honest.

**Comment by knz** [comment]
This is tracked in #22628 and #21660. Will have a look.

**Comment by bdarnell** [comment]
> Do you really think this looks good?

I think it looks about as good as an ascii-art tabular format can get (and it specifically looks better than the inline "NL" characters we used to use or a new column for the purposes of showing line continuations as an earlier version of this PR used. Changing the `|` separators to a different character for continuation lines might be OK). My main complaint with this format is that it's 173 characters wide, so it's a mess unless you run a very wide terminal. 

I think the `records` format is better for multi-line textual data like this. The mysql shell has a feature that ending your query with `\G` uses their `records`-like format. This is cryptic, but being able to switch formats for a single query is sometimes more convenient than our session variable (some commands, such as the mysql `show innodb status` command are nearly always run with `\G` instead of the default format)

We may want to reconsider showing the help text in the default output of `show all cluster settings`. It needs a very wide terminal to be legible at all, and even then it introduces this multi-line problem and can never be as detailed as the separate docs. A separate help command wouldn't have this problem.

**Comment by knz** [comment]
> I think the records format is better for multi-line textual data like this. The mysql shell has a feature that ending your query with \G uses their records-like format. 

I was toying with the idea of a prefix or a key combo to do the same. I think there's a good idea lurking in here.

Another option is to peek in the first N rows of results with a buffer (N < 10) and see if the output needs to be wide and decide automatically.

**Pull request merged**
