### PR TITLE
sql: miscellaneous SHOW improvements

### PR DESCRIPTION
**Pull request by knz**
Summary:
- a new method `(*planner).delegateQuery` for all your future SHOW needs, you should use this instead of `(*planner).query()` or `queryRows()`
- much code in SHOW is factored/simplified

Motivations:
- the previous code was using `p.query` /  `containerValuesNode` all over the place, causing mandatory duplication of the rows in memory

### CODE REVIEW

**Comment by jordanlewis** [comment]
So much good stuff in here! As discussed offline I think if you do any changes to this you should just break this PR up into two - one up to r7 and one for everything else. To be honest I'd prefer that split anyway, but up to you!

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 9 of 9 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 5 of 5 files at r8, 4 of 4 files at r9, 7 of 7 files at r10, 5 of 5 files at r11, 1 of 1 files at r12.
Review status: 14 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/crdb_internal.go, line 597 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjvNwji-8cOs1KZYQH:-KnjvNwji-8cOs1KZYQI:bsz3d0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0709a5995b155ec8f3d65e38a16569ae24238f6b/pkg/sql/crdb_internal.go#L597)):*
> ```Go
> var crdbInternalClusterSettingsTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE crdb_internal.cluster_settings (
> ```

I wonder if it's mildly misleading to users to have this be a table that can't be `UPDATE`d even though these are all user settings. Probably not a big deal for now but could be a topic of future improvement to either make this modifiable directly (not via SET CLUSTER SETTING) or making it exposed as a `VIEW`.

---

*[pkg/sql/plan.go, line 183 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjh_BwigXiJstNFwCa:-Knjh_BwigXiJstNFwCb:b-apczc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/83d0cb98a8ea7c0a5b6893ddb9af1722b6ebbcd0/pkg/sql/plan.go#L183)):*
> ```Go
> 	if stmt.ExpectedTypes != nil {
> 		if !stmt.ExpectedTypes.TypesEqual(planColumns(plan)) {
> 			plan.Close(ctx)
> ```

I think I smell something funny ... is there a better way to remember to close plans on error besides adding plan.Close() to every error case? Perhaps the body of this should be extracted into a helper function so we can just check for error once on the outside of the helper? Weight this suggestion more or less important depending on whether or not you think we'll be adding more error cases aroud here in the future.

---

*[pkg/sql/show.go, line 885 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjwKJsVvS6L4KbDox0:-KnjwKJsVvS6L4KbDox1:bp2eqhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e6df2069b1eb1244e9836272b8005a4a0b8a24/pkg/sql/show.go#L885)):*
> ```Go
> 	return p.delegateQuery(ctx, fmt.Sprintf(
> 		`SELECT * FROM crdb_internal.builtin_functions WHERE function ILIKE %s`,
> 		parser.EscapeSQLString(string(n.Name))), nil)
> ```

Nice! synergy! though to be fair I don't think any user will think of putting a % in their `HELP` statement to do a fuzzy search unless we either document it or otherwise make it obvious :)

---

*[pkg/sql/show.go, line 174 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjxPaUyYEuwnoBgfe9:-KnjxPaUyYEuwnoBgfeA:bad6m1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0705df5aaf959f7048fa101a70809f122b20b46/pkg/sql/show.go#L174)):*
> ```Go
> 
> 	return p.delegateQuery(ctx, fmt.Sprintf(
> 		`SELECT IFNULL(value, `+
> ```

I think I understand what's going on here vaguely but it's not super obvious when trying to read this query with fresh eyes, especially given all the interpolation. I think it would be helpful to add an explanatory comment above this call to delegateQuery.

---

*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1060 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjk_Vatq7cbx4cdNqT:-Knjk_Vatq7cbx4cdNqU:bdwphi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1060)):*
> ```
> SELECT COUNT(*) FROM pg_catalog.pg_tables WHERE schemaname='constraint_db'
> ----
> 3
> ```

This I don't understand - why did this change? Was it completely incorrect before?

---

*[pkg/sql/parser/encode.go, line 55 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjkfesk4rsuBYCSZKB:-Knjkfesk4rsuBYCSZKC:b3hqje7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/parser/encode.go#L55)):*
> ```Go
> }
> 
> // EscapeSQLString returns an escaped SQL representation of the given string.
> ```

Is this always suitable as a drop-in replacement for internal users of $1-style placeholders? If so, can you please document that? I certainly have FUD about this subject and have strongly preferred to use $1-style placeholders over doing string substitution myself, even if the latter would be more efficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-:-KnjxhCyPip8nMHJ89dS:bd3h7np)*

**Comment by knz** [comment]
I reduced the patchset to a few preparatory commits + the first significant SHOW refactoring only.  I'll send the follow-up changes as separate PRs when this one merges.

---

Review status: 0 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/crdb_internal.go, line 597 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjvNwji-8cOs1KZYQH:-KnkIIMDGRodcOhAmSFt:b-39cipz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0709a5995b155ec8f3d65e38a16569ae24238f6b/pkg/sql/crdb_internal.go#L597)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I wonder if it's mildly misleading to users to have this be a table that can't be `UPDATE`d even though these are all user settings. Probably not a big deal for now but could be a topic of future improvement to either make this modifiable directly (not via SET CLUSTER SETTING) or making it exposed as a `VIEW`.
</blockquote></details>

All our vtables are read-only. The word "TABLE" here is misleading, all of them are really "views".

---

*[pkg/sql/plan.go, line 183 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjh_BwigXiJstNFwCa:-KnkIORWGiOt-s4S_PRd:b-8q9zze) ([raw file](https://github.com/cockroachdb/cockroach/blob/83d0cb98a8ea7c0a5b6893ddb9af1722b6ebbcd0/pkg/sql/plan.go#L183)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think I smell something funny ... is there a better way to remember to close plans on error besides adding plan.Close() to every error case? Perhaps the body of this should be extracted into a helper function so we can just check for error once on the outside of the helper? Weight this suggestion more or less important depending on whether or not you think we'll be adding more error cases aroud here in the future.
</blockquote></details>

You are right this was actually incorrect. I removed this "fix" from the patchset.

---

*[pkg/sql/show.go, line 885 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjwKJsVvS6L4KbDox0:-KnkI60mvVQFS9i_M-W2:b-q1e04i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2e6df2069b1eb1244e9836272b8005a4a0b8a24/pkg/sql/show.go#L885)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nice! synergy! though to be fair I don't think any user will think of putting a % in their `HELP` statement to do a fuzzy search unless we either document it or otherwise make it obvious :)
</blockquote></details>

The commit message documents it, as well as the PR description. I'll add the docs-todo label.

---

*[pkg/sql/show.go, line 174 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjxPaUyYEuwnoBgfe9:-KnkIS_id-D4rnoTJEiz:b-pehs4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0705df5aaf959f7048fa101a70809f122b20b46/pkg/sql/show.go#L174)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think I understand what's going on here vaguely but it's not super obvious when trying to read this query with fresh eyes, especially given all the interpolation. I think it would be helpful to add an explanatory comment above this call to delegateQuery.
</blockquote></details>

Will add comment.

---

*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1060 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjk_Vatq7cbx4cdNqT:-KnkIBiQ-o1rueUqHu_v:blid7rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1060)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This I don't understand - why did this change? Was it completely incorrect before?
</blockquote></details>

I separated this change in a separate commit, that exhibits what's going on. PTAL.

---

*[pkg/sql/parser/encode.go, line 55 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjkfesk4rsuBYCSZKB:-KnkIFpUngHtT85gBBFv:b770kxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/parser/encode.go#L55)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is this always suitable as a drop-in replacement for internal users of $1-style placeholders? If so, can you please document that? I certainly have FUD about this subject and have strongly preferred to use $1-style placeholders over doing string substitution myself, even if the latter would be more efficient.
</blockquote></details>

I'll add a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-:-KnkIVECKA7Di1U0ArM6:b-mmra2m)*

**Comment by jordanlewis** [comment]
Thanks - this :lgtm: except for the removal of the descriptor filtering which I think is incorrect.

---

Reviewed 16 of 16 files at r14.
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/crdb_internal.go, line 597 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjvNwji-8cOs1KZYQH:-KnkK2ooLmyysnAM_EW_:b-e63obt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0709a5995b155ec8f3d65e38a16569ae24238f6b/pkg/sql/crdb_internal.go#L597)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

All our vtables are read-only. The word "TABLE" here is misleading, all of them are really "views".
</blockquote></details>

Yes I know. My comment isn't particularly constructive for this patchset - just musing!

---

*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1060 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjk_Vatq7cbx4cdNqT:-KnkP-Lu5KLoMcNAiXL4:bf2ymrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1060)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I separated this change in a separate commit, that exhibits what's going on. PTAL.
</blockquote></details>

Okay, upon reflection I believe this change is incorrect. The comment above these tests explains what we are testing. This is an important feature for ORM compatibility, actually, and removing this will cause issues. A non-root user should not be able to see tables for database `x` in `pg_table` when the current database is not `x`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-:-KnkTnPn1KDVjlHRPJ1x:bi6s24e)*

**Comment by jordanlewis** [comment]
s/pg_table/pg_class/

On Jun 28, 2017 4:56 PM, "Jordan Lewis" <notifications@github.com> wrote:

Thanks - this [image: :lgtm:]
<https://camo.githubusercontent.com/41b3ec3419116e3b3f84507ad965646ce4ce1f0c/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67>
except for the removal of the descriptor filtering which I think is
incorrect.
------------------------------

Reviewed 16 of 16 files at r14.
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved
discussions, some commit checks failed.
------------------------------

*pkg/sql/crdb_internal.go, line 597 at r8
<https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-KnjvNwji-8cOs1KZYQH:-KnkK2ooLmyysnAM_EW_:b-e63obt>
(raw file
<https://github.com/cockroachdb/cockroach/blob/0709a5995b155ec8f3d65e38a16569ae24238f6b/pkg/sql/crdb_internal.go#L597>):*
*Previously, knz (kena) wrote…*

All our vtables are read-only. The word "TABLE" here is misleading, all of
them are really "views".

Yes I know. My comment isn't particularly constructive for this patchset -
just musing!
------------------------------

*pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1060 at r5
<https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjk_Vatq7cbx4cdNqT:-KnkP-Lu5KLoMcNAiXL4:bf2ymrc>
(raw file
<https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1060>):*
*Previously, knz (kena) wrote…*

I separated this change in a separate commit, that exhibits what's going
on. PTAL.

Okay, upon reflection I believe this change is incorrect. The comment above
these tests explains what we are testing. This is an important feature for
ORM compatibility, actually, and removing this will cause issues. A
non-root user should not be able to see tables for database x in pg_table
when the current database is not x.
------------------------------

*Comments from Reviewable
<https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-:-KnkTnPn1KDVjlHRPJ1x:bi6s24e>*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/pull/16760#issuecomment-311787734>,
or mute the thread

**Comment by knz** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1060 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjk_Vatq7cbx4cdNqT:-KnmvtYWPbqzgX33mdvU:bj92fxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1060)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

*pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1060 at r5 <https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjk_Vatq7cbx4cdNqT:-KnkP-Lu5KLoMcNAiXL4:bf2ymrc> (raw file <https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1060>):* *Previously, knz (kena) wrote…*

I separated this change in a separate commit, that exhibits what's going on. PTAL.

Okay, upon reflection I believe this change is incorrect. The comment above these tests explains what we are testing. This is an important feature for ORM compatibility, actually, and removing this will cause issues. A non-root user should not be able to see tables for database x in pg_table when the current database is not x. 
</blockquote></details>

I believe this is incorrect.
In Postgres if I create a separate schema other than the current one (e.g. `create schema blah`) then a table in there (`create table blah.x(y int)`) I can see both `blah` and `x` in `information_schema`.

Can you please check where this change was coming from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760)*

**Comment by knz** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/parser/encode.go, line 55 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjkfesk4rsuBYCSZKB:-KnnUsG65v-s-Zy8UoDJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/parser/encode.go#L55)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'll add a comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760)*

**Comment by jordanlewis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1060 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-Knjk_Vatq7cbx4cdNqT:-Kno_yMMLNWUZCjZRrHN:b-7jn0ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/9024f4f8e21c3ca50447b6805b159bcd00f0f1f6/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1060)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I believe this is incorrect.
In Postgres if I create a separate schema other than the current one (e.g. `create schema blah`) then a table in there (`create table blah.x(y int)`) I can see both `blah` and `x` in `information_schema`.

Can you please check where this change was coming from?
</blockquote></details>

That's true for Postgres *schemas*, but not for Postgres *databases*.

I know that our "database" concept falls somewhere in between that of Postgres' schema and database, but unfortunately to external clients our databases must behave for all intents and purposes as Postgres databases.

To illustrate why this is important, consider how ActiveRecord manages local databases. There's typically two - a development database and a testing database. The two databases are usually kept in sync with the schema - you'll have jordan-testing and jordan-development, and they'll both have the same tables inside.

When ActiveRecord performs migrations, it checks to see whether the table that it's trying to create already exists in the current database. It does that check via one of information_schema/pg_catalog/regclass casts. So that check will report incorrect information after the testing database is created, during the creation of the development database.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760)*

**Comment by knz** [comment]
Rebased after our discussions, thanks for helping! PTAL

**Comment by jordanlewis** [comment]
I'm happy about this turned out. Very nice :lgtm: 

---

Reviewed 10 of 10 files at r15, 12 of 12 files at r16, 6 of 6 files at r17.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16760#-:-KoIf2vm2iB4TnwdDBRD:b-wfoz16)*

**Comment by knz** [comment]
TFYR and your help!

**Pull request merged**
