### PR TITLE
server: add insecure to URL params

### LINKED ISSUE #15739: updates: make the reporting loop report whether the cluster is running insecure
As soon as v1.0 is out, script kiddies and attackers will start scanning the net for open CockroachDB clusters with insecurity. With known and unknown bugs in CockroachDB it is probably not difficult to escape from the SQL sandbox and make the host system do anything. 

In order to prevent this risk from tarnishing CockroachDB's reputation, it would be thus useful to have the reporting loop tell us which users may be unknowingly exposing themselves to disagreeable situations.

For this the reporting loop should be extended to include:
- whether the cluster is running with --insecure
- whether, if running insecure, they provided a non-empty --host

### PR DESCRIPTION
**Pull request by dt**
Fixes #15739.

add the secure/insecure status to the URL params when reporting diagnostics or when checking for updates.

### CODE REVIEW

**Comment by knz** [comment]
Thank you for the fast reaction!
Although as highligted in #15739 --insecure is not half as bad if `--host=xxx` is also specified, hence my suggestion below.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/updates.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15747#-KjZW350BXxtW2n5_dyV:-KjZW351f89TfI0rKVbR:b-lxhu40) ([raw file](https://github.com/cockroachdb/cockroach/blob/6933f242658158f522e13bdc2f402016d1d09834/pkg/server/updates.go#L189)):*
> ```Go
> 	q.Set("nodeid", s.NodeID().String())
> 	q.Set("uptime", strconv.Itoa(int(runningTime.Seconds())))
> 	q.Set("insecure", strconv.FormatBool(s.cfg.Insecure))
> ```

add
`q.Set("defaultlisten", strconv.FormatBool(c.cfg.Addr == ":26257"))` (or some suitably defined common constant from the server package)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15747#-:-KjZWOfjaf1whR2RAk8c:bh4dyik)*

**Comment by dt** [comment]
Eh, we might be trying to get too clever here: just because they told cockroach to bind all interfaces doesn't mean they have a public IP, that their machine's (or network) firewall allows arbitrary incoming connections, they're not running in a container env the is managing port mappings, etc.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/updates.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15747#-KjZW350BXxtW2n5_dyV:-KjZsD1LN0M1NSi3xsOe:bl18t0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6933f242658158f522e13bdc2f402016d1d09834/pkg/server/updates.go#L189)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

add
`q.Set("defaultlisten", strconv.FormatBool(c.cfg.Addr == ":26257"))` (or some suitably defined common constant from the server package)

</blockquote></details>

`strings.HasPrefix(s.cfg.Addr, ":")` I think, but see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15747#-:-KjZsNfl2MwxOjx6Z3nk:b7u12vc)*

**Comment by dt** [comment]
@knz [friendly](https://www.youtube.com/watch?v=sLdgM8VQu7I) ping

**Comment by knz** [comment]
Apologies for the late answer; you've convinced me. LGTM.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15747#-:-Kjj2iTSWvkY2V8BJGEK:b9yhxw5)*

**Comment by knz** [comment]
@benesch we need to extend the reg server schema accordingly and populate the new column

**Pull request merged**
