### PR TITLE
cli: use bufio for reading lines in non-interactive mode

### PR DESCRIPTION
**Pull request by petermattis**
readline.Instance.ReadLine has horrific performance for very long
lines. bufio.ReadString('\n') measured at 224,000x faster in a
benchmark.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13174)

### CODE REVIEW

**Comment by knz** [comment]
The acceptance test reveals that the new code is not dealing properly with a missing terminating newline.

**Comment by petermattis** [comment]
Thanks for the pointer. Should be easy to fix. 

```
func TestReadline(t *testing.T) {
	{
		ins, _ := readline.NewEx(&readline.Config{
			Stdin: strings.NewReader("hello world"),
			DisableAutoSaveHistory: true,
		})
		l, err := ins.Readline()
		fmt.Println(l, err)
	}

	{
		buf := bufio.NewReader(strings.NewReader("hello world"))
		l, err := buf.ReadString('\n')
		fmt.Println(l, err)
	}
}
```

This outputs:

```
=== RUN   TestBufio
hello world <nil>
hello world EOF
```

**Comment by petermattis** [comment]
Fixed the missing terminator behavior. Also made the `bufio` code path strip off the trailing `\n` which `readline` does automatically. This fixed the TODO related to `TestSQLLex`.

PTAL

**Comment by RaduBerinde** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13174#-:-KbVVezMfRCfh2LhJirF:bnfp4nl)*

**Pull request merged**
