### PR TITLE
opt: improvements for inverted index constraints

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: partial support for conjunctions in inverted index

We now generate the spans from at most one of the "contains"
conditions in a conjunction. The rest of the conditions are in the
remaining filter.

Release note: None

#### opt: normalize containedByOp

Flip containedByOp to containsOp (which is supported by index
constraints).

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm:

Now that you've got this done, can you and/or @m-schneider ensure that we decompose contains filters whose operands have multiple paths into a conjunction? Either this is explicitly barred right now or its broken. For example:

```
SELECT * FROM t WHERE j @> '{"foo": 1, "bar": 2}' // should become
SELECT * FROM t WHERE j @> '{"foo": 1}' AND j @> '{"bar": 2}'
```

This could already be done but just flagging it.

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 733 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21370#-L2Ve_K6J1TEDYFzmhhw:-L2Ve_K6J1TEDYFzmhhx:bxrrncu) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b6faf21a7aa881b322c0eecdf3f33ffbc17a23/pkg/sql/opt/index_constraints.go#L733)):*
> ```Go
> 			sp, ok, _ := c.makeInvertedIndexSpansForExpr(child)
> 			if ok {
> 				// TODO(radu, masha): for now, the beset we can do is to generate
> ```

nit: best

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21370#-:-L2VesLupFqE0hzxIRs6:b4mszot)*

**Comment by m-schneider** [comment]
@jordanlewis it's explicitly prohibited at the moment.
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21370#-:-L2WA_FGJQiFracIyYhi:btbrjgx)*

**Comment by RaduBerinde** [comment]
TFTR! What you suggest should be done as part of expression normalization (either in `opt` or in `tree`).

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21370#-:-L2WMeK0uXruwxhD9T_3:bsu776e)*

**Comment by m-schneider** [comment]
The way that we generate inverted index KV keys would actually return a list of the correct prefixes which we can convert to spans. If we used that we wouldn't even need to normalize ?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21370#-:-L2WTSK-ioi2sSKahi8l:b33ory6)*

**Comment by jordanlewis** [comment]
I like the idea of a normalization step because it could cut down on the amount of duplicated code that will be generated. I think it's better to centralize the logic for constructing the correct scan in the part of the code that deals with a conjunction of contains predicates. If we also teach the code that generates spans about contains operands that have multiple paths, then we'll probably end up with some duplicate logic.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21370#-:-L2WTx1h2I_KlqS15up0:b-l5tb4g)*

**Comment by RaduBerinde** [comment]
> The way that we generate inverted index KV keys would actually return a list of the correct prefixes which we can convert to spans. If we used that we wouldn't even need to normalize ?

How would we convert those to spans? This is just like the AND case, we can't come up with some spans that correspond to `a @> 'foo' AND b @> 'bar'`. We can't just scan both `/foo` and `/bar`, we need to join the results of each using the PK columns.

**Comment by m-schneider** [comment]
We could do it the same way as we convert one of them to a span, but yes we would have to do a merge on the PKs.

**Pull request merged**
