### PR TITLE
sql: add show default privileges for grantee

### LINKED ISSUE #107741: sql: add SHOW DEFAULT PRIVILEGES FOR GRANTEE
Currently, `SHOW DEFAULT PRIVILEGES FOR <ROLE | USER | ALL ROLES>` statements are supported to list default privileges for the objects created by users/roles; however, there is not an easy way to find out what default privileges a grantee has. It would be nice if there was a way to `SHOW DEFAULT PRIVILEGES FOR GRANTEE <grantee>`.

For example:

```
 SHOW DEFAULT PRIVILEGES FOR GRANTEE root;
                                 
  role | for_all_roles | object_type | grantee | privilege_type | is_grantable
-------+---------------+-------------+---------+----------------+---------------
  root |       f       | functions   | root    | ALL            |      t
  root |       f       | schemas     | root    | ALL            |      t
  root |       f       | sequences   | root    | ALL            |      t
  root |       f       | tables      | root    | ALL            |      t
  root |       f       | types       | root    | ALL            |      t
(5 rows)
```

Jira issue: CRDB-30179

Epic: CRDB-25481

### PR DESCRIPTION
**Pull request by annrpom**
Previously, `SHOW DEFAULT PRIVILEGES [FOR <ROLE|USER|ALL ROLES>]` statements were supported. However, support for finding default privileges for a grantee did not exist. This patch adds a new syntax for showing the default privileges that a grantee received.

Fixes: #107741
Epic: CRDB-25481

Release note (sql change): This adds a new syntax to `SHOW DEFAULT PRIVILEGES`, `SHOW DEFAULT PRIVILEGES FOR GRANTEE <grantee>`, that shows the default privileges that a grantee received.

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
Nice work! Left a few nits and suggestions for further testing

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-:-NamNEI5-Ih9OmdSj_Ec:b-syhu9d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/delegate/show_default_privileges.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamKz7rEYe2MxfChQv0:-NamKz7rEYe2MxfChQv1:b-oi8a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L44)):*
> ```Go
> 	)
> 
> 	colName := "role"
> ```

nit: move this into the `else if` case where it's actually used. whenever possible (and within reason), we try to reduce the scope of variables
___
*[`pkg/sql/delegate/show_default_privileges.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamLd7d79iIaKbjbTzQ:-NamLd7d79iIaKbjbTzR:b-8jaffq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L44)):*
> ```Go
> 	)
> 
> 	colName := "role"
> ```

nit: let's also name this variable something more specific, maybe like `targetCol`
___
*[`pkg/sql/delegate/show_default_privileges.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamKkut7Boo3bFP5oEM:-NamKkut7Boo3bFP5oEN:b-cn3nb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L52)):*
> ```Go
> 		query += " AND for_all_roles=true"
> 	} else if len(n.Roles) > 0 {
> ```

nit: delete this extra newline
___
*[`pkg/sql/delegate/show_default_privileges.go` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamKuPM6dMrLiSoeo2-:-NamKuPM6dMrLiSoeo20:b9fw1w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L60)):*
> ```Go
> 		}
> 
> 		query = fmt.Sprintf("%s AND for_all_roles=false AND %s in (", query, colName)
> ```

nit: capitalize "in"
___
*[`pkg/sql/sem/tree/show.go` line 1337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamH7gm2kU4T407Lv8W:-NamH7gm2kU4T407Lv8X:b-h1on6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/sem/tree/show.go#L1337)):*
> ```Go
> 	ctx.WriteString("SHOW DEFAULT PRIVILEGES ")
> 	if len(n.Roles) > 0 {
> 		forColName := "FOR ROLE "
> ```

nit: use an if-else statement instead of a variable
___
*[`pkg/sql/logictest/testdata/logic_test/show_default_privileges` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamMujL8vQ7XNqYs-mH:-NamMujL8vQ7XNqYs-mI:b-hgxx99) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/logictest/testdata/logic_test/show_default_privileges#L346)):*
> ```
> 
> query TBTTTB colnames,rowsort
> SHOW DEFAULT PRIVILEGES FOR GRANTEE testuser
> ```

It'd be nice if we also had some tests where the grantor is different from the grantee too. Let's test both when the default privilege is granted by an `ALTER DEFAULT PRIVILEGS FOR ALL ROLES` and one where we specifically granted it to the grantee

**Review by chengxiong-ruan — COMMENTED** [review]
very nice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-:-NamS8A837pLS2j2-_TR:biuimdo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @annrpom)

___
*[`pkg/sql/sem/tree/show.go` line 1337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamH7gm2kU4T407Lv8W:-NamRr0-1CzipHSKetPJ:b7jw61o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/sem/tree/show.go#L1337)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: use an if-else statement instead of a variable
</blockquote></details>

I actually prefer Annie's way heh

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/delegate/show_default_privileges.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamKz7rEYe2MxfChQv0:-NaqVjjs1cRZvgi09a8C:boebgle) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L44)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: move this into the `else if` case where it's actually used. whenever possible (and within reason), we try to reduce the scope of variables
</blockquote></details>

ah - that makes sense! done
___
*[`pkg/sql/delegate/show_default_privileges.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamLd7d79iIaKbjbTzQ:-NaqVogtCRFgGBqfappg:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L44)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: let's also name this variable something more specific, maybe like `targetCol`
</blockquote></details>

done
___
*[`pkg/sql/delegate/show_default_privileges.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamKkut7Boo3bFP5oEM:-NaqVqJ8Dd81-RejRH_G:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L52)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: delete this extra newline
</blockquote></details>

done
___
*[`pkg/sql/delegate/show_default_privileges.go` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamKuPM6dMrLiSoeo2-:-NaqW0lW0K96jWap9Q9_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/delegate/show_default_privileges.go#L60)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: capitalize "in"
</blockquote></details>

done
___
*[`pkg/sql/sem/tree/show.go` line 1337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamH7gm2kU4T407Lv8W:-NaqdS6j1qvrC0r2FQQC:b-4lfsu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/sem/tree/show.go#L1337)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I actually prefer Annie's way heh
</blockquote></details>

done - i think it makes more sense to do the if-else statement since it seems to me like it is stylistically more similar to the existing code
___
*[`pkg/sql/logictest/testdata/logic_test/show_default_privileges` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamMujL8vQ7XNqYs-mH:-NaqteYFErOpK54_rcuK:b-j4xwho) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/logictest/testdata/logic_test/show_default_privileges#L346)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

It'd be nice if we also had some tests where the grantor is different from the grantee too. Let's test both when the default privilege is granted by an `ALTER DEFAULT PRIVILEGS FOR ALL ROLES` and one where we specifically granted it to the grantee
</blockquote></details>

done i believe

**Review by andyyang890 — CHANGES_REQUESTED** [review]
This is looking really good! I just had one more comment about the logic test.

> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-:-Nau8gTl1Ymili74yKeT:bjdjfel)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/show_default_privileges` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamMujL8vQ7XNqYs-mH:-Nau3wAhD95zu5KH0uBd:b-9yv2a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/logictest/testdata/logic_test/show_default_privileges#L346)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

done i believe
</blockquote></details>

I think we might still want a test where we do `ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT ... TO <grantee>` and then check `SHOW DEFAULT PRIVILEGES FOR GRANTEE` on the aforementioned grantee.

For example, earlier in the file there's this line:
```
ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT DROP, ZONECONFIG ON TABLES TO foo WITH GRANT OPTION;
```

So if we now do
```
SHOW DEFAULT PRIVILEGES FOR GRANTEE foo
```
we would expect to see a row with `(role,grantee,privileges_type) = (X,foo,DROP)` for every user `X` (and another such row for `ZONECONFIG`).

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/show_default_privileges` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-NamMujL8vQ7XNqYs-mH:-Nawaz7m8azf_e9nmcSR:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5319e8f5a4672576ab136d1fec368d2264f82de9/pkg/sql/logictest/testdata/logic_test/show_default_privileges#L346)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I think we might still want a test where we do `ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT ... TO <grantee>` and then check `SHOW DEFAULT PRIVILEGES FOR GRANTEE` on the aforementioned grantee.

For example, earlier in the file there's this line:
```
ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT DROP, ZONECONFIG ON TABLES TO foo WITH GRANT OPTION;
```

So if we now do
```
SHOW DEFAULT PRIVILEGES FOR GRANTEE foo
```
we would expect to see a row with `(role,grantee,privileges_type) = (X,foo,DROP)` for every user `X` (and another such row for `ZONECONFIG`).
</blockquote></details>

done

**Comment by annrpom** [comment]
hmmm... this does not match the expected behavior that was commented - let me take a look at if my understanding is incorrect

**Comment by annrpom** [comment]
yup - actually, this was a misunderstanding on my end of the functionality of `SHOW DEFAULT PRIVILEGES FOR GRANTEE ...` when considering the behavior of `ALTER DEFAULT PRIVILEGES FOR ALL ROLES...`

**Review by andyyang890 — COMMENTED** [review]
> I don't think I'd expect that. instead of having a row-per-user, shouldn't this just return two rows that looks like (note the `for_all_roles` column):
> 
> ```
>   role | for_all_roles | object_type | grantee | privilege_type | is_grantable
> -------+---------------+-------------+---------+----------------+---------------
>   root |       t       | tables      | foo     | DROP           |      f
>   root |       t       | tables      | foo     | ZONECONFIG     |      f
> ```

Ah yeah you're right, my bad. Although like Annie observed, I think it should be `NULL` as the `role`, not `root`.

> [@rafiss](https://github.com/rafiss) to my understanding, the "grantor" in an `ALTER DEFAULT PRIVILEGES FOR ALL ROLES...` should always be NULL since the grantor is technically "ForAllRoles" - which isn't a valid user (I came to this conclusion after seeing [this comment](https://github.com/cockroachdb/cockroach/blob/4f41f5e20baac884bb8a424f6f13051da8b9ebe2/pkg/sql/logictest/testdata/logic_test/show_default_privileges#L303) in the tests). everything else in the updated commit should be good, though

@annrpom The code for this is here if you're curious:
https://github.com/cockroachdb/cockroach/blob/1d3c11efe8a5368cff3a3eec4668bf866c10952d/pkg/sql/crdb_internal.go#L6313-L6318

Just an FYI that it's usually better to verify with code than comments since comments can become outdated.

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-:-NawztYE7okxgoOwcWDj:b-v2ylsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by andyyang890 — APPROVED** [review]
This :lgtm: now! Nice work! I'll defer to Rafi for final approval.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107953#-:-Nax1s9E8bIsPBmNUBP7:bxxsqrq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
this looks great! nice work. i'll add a backport label as well

**Comment by annrpom** [comment]
TFTR! ('-')7

bors r=andyyang890, rafiss

**Pull request merged**
