### PR TITLE
roachtest: add new decommissionBench configurations

### PR DESCRIPTION
**Pull request by AlexTalks**
This change adds new configurations to the decommission benchmark test,
as well as cleaning up some existing configurations. This includes
benchmarking decommissions when we have a high number of store targets,
as well as decommissioning a node when we have just added a new node to
the cluster.

Depends on #81874, #82760.

Release note: None

### CODE REVIEW

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83352#-:-N5sD0L64KlbwpfKcz66:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by AlexTalks** [comment]
bors cancel

**Comment by yuzefovich** [comment]
A linter complains.

bors r-

**Pull request merged**
