### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tamird**
Remove TODO related to GRPC's handling of certificate errors now that
https://github.com/grpc/grpc-go/issues/622 is resolved.

Also use upstream's unconvert.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8317)

### CODE REVIEW

**Comment by tamird** [comment]
@jordanlewis there are tertiary commits here that may be of interest to you.

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/server.go, line 464 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8317#-KOHr2eZzAm0LgBOXkGU:-KOHr2e_VkcjIhif1sBX:186150883) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ace91c62fe1c2dc66f46985e79f92af54ddc1e/server/server.go#L464)):*
> ```Go
> 		return err
> 	}
> 	conn, err := s.rpcContext.GRPCDial(s.ctx.Addr, dialOpt)
> ```

You shouldn't need to pass in `dialOpt` like this as internally `GRPCDial` will prepend `GRPCDialOption` to the list of options.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8317#-:-KOHrTyYHFkSJ2gMJStu:1417088721)*

**Comment by tamird** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 464 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8317#-KOHr2eZzAm0LgBOXkGU:-KOHsJLNiRPcCGFDwM8i:1828397398) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ace91c62fe1c2dc66f46985e79f92af54ddc1e/server/server.go#L464)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> You shouldn't need to pass in `dialOpt` like this as internally `GRPCDial` will prepend `GRPCDialOption` to the list of options.
</details>
Oh yeah, good point. Not sure what this was doing. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8317)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8317#-:-KOPu0kbYMRfiA-g528T:bnfp4nl)*

**Pull request merged**
