### PR TITLE
roachpb: replace `gogoproto.onlyone` with `oneof` in ErrorDetail

### PR DESCRIPTION
**Pull request by tamird**
According to @nvanbenschoten:

Improves throughput by 1.9% against a patched version of `kv --read-percent=0 --seed=<something-fixed>` that used INSERTs instead of UPSERTs to create all primary key violations. With the change to avoid the allocation of `roachpb.Error.ErrorDetail` this change in theory is strictly an improvement because we're simply trading one big allocation (`ErrorDetail`) for a much smaller one (`isErrorDetail_Value`). I also suspect the constant-time dynamic dispatch of the interface is faster than the linear-time "dynamic" dispatch of the union struct.

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27902)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27902#-LID7Xx55BJzELsjuzHW:-LID7Xx55BJzELsjuzHX:b1qc7lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/082752fce38410fe3e7a10dcb413bf7245a8f129/Makefile#L299)):*
> ```Makefile
> bin/.submodules-initialized:
> ifneq ($(GIT_DIR),)
> 	git submodule update --init --recursive
> ```

Thanks. Been meaning to fix this for a while. If you go through CI again, can you make the same change to all the githooks?

**Review by tamird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27902)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27902#-LID7Xx55BJzELsjuzHW:-LIDDpFk2Kg5DXQnwYqC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/082752fce38410fe3e7a10dcb413bf7245a8f129/Makefile#L299)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Thanks. Been meaning to fix this for a while. If you go through CI again, can you make the same change to all the githooks?
</blockquote></details>

Done.

**Comment by tamird** [comment]
@benesch `ccache: error: /root/.ccache/ccache.conf: No such file or directory` - have you seen this before?

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=794914&_focus=1022

**Comment by benesch** [comment]
Yep. Haven't been able to track it down. I'll trigger you another build.

**Review by nvb — CHANGES_REQUESTED** [review]
Code :lgtm:. Thanks @tamird! I'll see if this moves the needle on a workload that hits a lot of unique constrain violations. Let's not merge until we see what the benchmarks say.

Also, for the record, before this change, `ErrorDetail` was `240` bytes. It's now `16`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27902#-:-LIHWHnmEK07lyXKXoMn:b-qetmej)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/roachpb/errors.proto, line 503 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27902#-LIHZJOc7-GugzKFxZ5g:-LIHZJOc7-GugzKFxZ5h:b-6ilf5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84a7ffadd79626a251b5e2809ae162482fe5e4d/pkg/roachpb/errors.proto#L503)):*
> ```protobuf
>   // If an ErrorDetail is present, it may contain additional structured data
>   // about the error.
>   optional ErrorDetail detail = 6;
> ```

We should explore making this non-nullable now that it's just wrapping an interface. We can use a `nil` `ErrorDetail.Value` to indicate a detail that does not exist. Or we can introduce a new `NoError` `ErrorDetail` variant, although that will have complications with backwards compatibility.

**Review by nvb — COMMENTED** [review]
I ran this against a patched version of `kv --read-percent=0 --seed=<something-fixed>` that used `INSERTs` instead of `UPSERTs` to create all primary key violations. Over the course of three trials before and after, this change actually reduced throughput by **2.4%**. So I don't think this is mergeable as-is.

I think we should explore two changes that might swing this into a win:
1. make `Error.detail` non-nullable to avoid pointless indirection and an unnecesary extra alloc.
2. group `isErrorDetail_Value` impl allocs with their corresponding error allocation. This would be similar to what we do in `BatchRequest.CreateReply`. We have most of the error constructors in `roachpb/errors.go`, so we could abstract this away to some extend. This might not be easy though, since we call `SetInner` on the error detail all the way in `Error.setGoError`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27902#-:-LIHcFgc1NDQ4XHNsOX9:b-ctepjv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by tamird — COMMENTED** [review]
1. Done
2. is harder, as you say. Let's test this for now?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27902#-:-LIJYpIf69oV-v_LZ5Q0:b-mis7j1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/roachpb/errors.proto, line 503 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27902#-LIHZJOc7-GugzKFxZ5g:-LIJZ1wG2Jtj5x5MsBvY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84a7ffadd79626a251b5e2809ae162482fe5e4d/pkg/roachpb/errors.proto#L503)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should explore making this non-nullable now that it's just wrapping an interface. We can use a `nil` `ErrorDetail.Value` to indicate a detail that does not exist. Or we can introduce a new `NoError` `ErrorDetail` variant, although that will have complications with backwards compatibility.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
Ok, that seems to have spun this into a **1.9%** throughput win on my "all errors" kv test. With your change to avoid the allocation of `ErrorDetail` this change in theory is strictly an improvement because we're simply trading one big allocation (`ErrorDetail`) for a much smaller one (`isErrorDetail_Value`). I also suspect the constant-time dynamic dispact of the interface is faster than the linear-time "dynamic" dispatch of the union struct. 

So the measured improvement lines up with expectations. Merge away!

**Comment by tamird** [comment]
Very nice, thanks! It's also worth mentioning that I don't think there's a backwards compatibility issue here, since the old code always calls `GetValue` if `Detail` is non-nil - so `Detail` will be non-nil, but `GetValue` will return nil, which should be equivalent.

bors r=nvanbenschoten

**Pull request merged**
