### PR TITLE
roachpb: make TenantID a proto message

### PR DESCRIPTION
**Pull request by dt**
This replaces the plain go struct with a proto message with the same field,
so the existing methods are unchanged, though a new IsSet helper is added
as it seems likely that this will often find itself in nullable=false protos.

Release note: none.

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Review by tbg — CHANGES_REQUESTED** [review]
I have to take this back. The following unit test explodes:

```go
func TestErrorToJsonPB(t *testing.T) {
	// Verify that Error can marshal to JSON without blowing up.
	jsonpb := protoutil.JSONPb{
		Indent: "  ",
	}
	pErr := NewErrorf("foo")
	jsonpb.Marshal(pErr)
}
```

because `Error` has fields that have a package-private customname. The same would be true for `TenantID`. We need to figure out how this should work before we introduce another ubiquitous private field into our codebase.

**Comment by dt** [comment]
we could just export it as RawID or something?

**Comment by dt** [comment]
And if we like the "just export it with a name that suggests it isn't for direct use", any opinions on aggressive we should be with that suggestion?

Could do customname = `RawID`, `InternalID`, `PrivateID` or go even uglier, since nobody should see this anyway, like `PrivateID_DoNotAccessDirectly` or something?

**Comment by RaduBerinde** [comment]
I'll add `InternalValue` to the pile.

I know we said that custom marshal/unmarshal is too much work, but what if we do that once and embed that implementation in all cases where we want this (including NodeID, SQLInstanceID, etc)?

**Comment by RaduBerinde** [comment]
By the way, we have a similar precedent where the field is public (it happened to deserve a very unfriendly name): https://github.com/cockroachdb/cockroach/blob/master/pkg/util/optional/uint.go

**Comment by dt** [comment]
Rebased with it public as "InternalValue"

**Comment by dt** [comment]
I don't know if a custom marshal actually helps us much -- it'd let us use a int wire type instead of a message type containing that int, but I think I agree with tbg that that is a pretty minor difference that is only relevant if we're migrating an existing field, and these don't seem widely enough used or hard enough to just have old and new side-by-side to warrant the ongoing complexity / cost of maintaining custom marshal?

**Review by RaduBerinde — APPROVED** [review]

**Comment by dt** [comment]
TFTRs!

bors r+

**Comment by RaduBerinde** [comment]
It would be nice if this was in a more base package than `roachpb`. Ideally we should be able to use `TenantID` ~everywhere. I think I'd like to use it in cluster settings.

Somewhat related, the same is being requested for node/sql-instance IDs, maybe they all belong in the same package? https://github.com/cockroachdb/cockroach/pull/73309#pullrequestreview-834757018

**Comment by dt** [comment]
Alternatively roachpb should be that base package, and api.proto should move out of it, into `kvapipb` or something.

**Comment by dt** [comment]
yeah, poking around, it looks like `pkg/roachpb` is pulling in most of its non-pb/non-datatype-utuil deps to have helpers like `MakeLockAcquisition` or  `PrepareTransactionForRetry`, which we should jut move to live somewhere under `pkg/kv`.

**Pull request merged**
