### PR TITLE
*: migrate more uses of CPutDeprecated

### PR DESCRIPTION
**Pull request by danhhz**
The signature of CPut was changed so the expected value is now
*roachpb.Value instead of interface{}. This was primarily motivated by
protos because 1) the protobuf spec specifically mentions not to rely on
the serialized version being stable and 2) we had actual issues with
backward compatibility when trying to add new non-nullable fields as
described in #38308. Instead, we now use the roachpb.Value bytes
actually fetched from kv.

Touches #38308

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
The first commit LGTM, the second commit I also understand but I'd want someone else to confirm that all of these calls to `ConditionalGetTableDescFromTxn` aren't going to create problems.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40397#-:-LnvK_rj4ijlW9HfwXry:b-9v8j05)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @tbg)

___
*[pkg/sql/sqlbase/table.go, line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40397#-LnvKL4l38V3v68p4huj:-LnvKL4l38V3v68p4huk:b-fa67jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d121fd15b84fb1934fcc02a27b88f8392849e45f/pkg/sql/sqlbase/table.go#L469)):*
> ```Go
> // because the marshalling is not guaranteed to be stable and also because it's
> // sensitive to things like missing vs default values of fields.
> func ConditionalGetTableDescFromTxn(
> ```

We're adding lots of calls to this where previously KV wasn't hit. Do we need an audit of them?

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @tbg)

___
*[pkg/sql/sqlbase/table.go, line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40397#-LnvKL4l38V3v68p4huj:-LnwaLbn2pOIjgBGwKgl:b-yas9ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/d121fd15b84fb1934fcc02a27b88f8392849e45f/pkg/sql/sqlbase/table.go#L469)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We're adding lots of calls to this where previously KV wasn't hit. Do we need an audit of them?
</blockquote></details>

Only 5. I audited them when I wrote this. All of them are in either restore or import and are once per table for some job state change SUCCESS/FAIL/CANCEL/RESUME. Adding @dt anyway to get a second pair of eyes on this

**Comment by danhhz** [comment]
The race failure doesn't repro before my first commit and does with only the first commit, so seems like the issue is in there somewhere. I don't think it's my addition of `ClearChecksum()` in CPut, must be something about the usage in https://github.com/cockroachdb/cockroach/blob/9d32e4a8475a70f2237621ae48719b305e2374f1/pkg/internal/client/lease.go#L184

**Review by danhhz — COMMENTED** [review]
Race failure should be fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40397#-:-Lnwoskg0-PaRbE-pJ-y:bi7nobo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @tbg)

___
*[pkg/kv/dist_sender_server_test.go, line 1718 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40397#-Lnwod243a2rY0zkgtLk:-Lnwod243a2rY0zkgtLl:bg7tan0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c7c5398f9ca144cb54e2626ad47c58a3394cb9/pkg/kv/dist_sender_server_test.go#L1718)):*
> ```Go
> 	// around) will clear and re-init the checksum, so defensively copy it before
> 	// we save it.
> 	origVal = roachpb.Value{RawBytes: append([]byte(nil), origVal.RawBytes...)}
> ```

I didn't see any race failures with this, but it's the same issue as the other one

**Review by dt — APPROVED** [review]
Yeah, I'm not worried about going to KV o(tables) times in the bulk stuff since those costs will be inconsequential compared to the actual job so that aspect LGTM.

I haven't been following the cput-vs-proto-bytes stuff closely, so I don't have anything beyond vague understanding of the implications of what the actual change means -- I'm slightly uneasy handling of new unknown fields... but on TableDesc the contract is (or is supposed to be) that `ID` and `Version` uniquely determines the content of the whole desc, so it shouldn't matter how any other fields are/are not compared as long as those two are there, so I think I can just not worry about it.

Thanks for fixing these up!

**Comment by danhhz** [comment]
New unknown fields is actually the motivation for this. If you have some serialized proto in kv that was written by version v1, read and parse it with version v2 (which has a new non-nullable field), then try to use that parsed version as a CPut expectation, it will fail. This is because gogo will include that field in the proto serialization, even if it's set to the default value. You have to make the field nullable and leave it unset (and we had to do this on RangeDescriptor for a few things in 19.2). Nullable fields have bad usability (needing to grab pointers to stuff everywhere), allocating more, and they break comparing two protos with `==` (which we probably shouldn't do, but definitely do in a lot of places because it happens to work most of the time, i wonder if we can lint for this).

The idea behind this CPut interface change is you should read the proto into a roachpb.Value, manually deserialize it into the proto if necessary, then use the original roachpb.Value as the expecation in CPut, which is guaranteed to have the semantics you want.

The `ConditionalGetTableDescFromTxn` change here is a little different than that, but it's the pattern we use with RangeDescriptor and I was thinking it's much less disruptive than passing the roachpb.Value.RawBytes around through the job. But, while sitting down to explain how it's safe in the general case of proto schema migrations, i'm starting to wonder if we should just pass the raw bytes

**Comment by dt** [comment]
I'm of slightly too minds: on the one hand, it scares me a little that if the raw-byte comparison would fail but this doesn't that suggests we might be blowing away some new field we don't know about. The current code in import and restore uses the cput since it assumes it, and only it, it messing with that table and if that cput fails, something has already gone wrong. However, thinking though it more, if we're _resuming_ on a different version, it might not be the case that someone messed with it -- we might just be adding a zero value like you mention. I dunno, this stuff is all confusing.

One thing to be really, really careful with we've found from experience in IMPORT is relying on anything in the `Job` since we've had problems with the in-memory job's fields, particularly if they're mutable, diverging from the persisted ones in subtle ways. This is something I'm hoping some refactoring of the job API will get us (minimizing the use of the in-mem `Job` copy of something) but I have greater confidence in this re-read pattern than I would in passing raw bytes back.

**Comment by danhhz** [comment]
SGTM

bors r=tbg,dt

**Pull request merged**
