### PR TITLE
server: persist correct cluster version on join

### LINKED ISSUE #27162: roachtest: version/mixedWith=v2.0.0/nodes=3 failed on master
SHA: https://github.com/cockroachdb/cockroach/commits/faa1d2b46708f4f84cd552af6dc7258373fdebb0

Parameters:

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=757857&tab=buildLog

```
	test.go:493,cluster.go:750,version.go:170,errgroup.go:58: /home/agent/work/.go/bin/roachprod start teamcity-757857-version-mixedwith-v2-0-0-nodes-3:2: exit status 1

```

### LINKED ISSUE #27525: storage: unable to use store fixture generated with 2.1 binary with latest 2.1
Running `roachtest run clearrange` with that test configured to use the fixture `gs://cockroach-fixtures/workload/bank/version=1.0.0,payload-bytes=10240,ranges=0,rows=65104166,seed=3` (notice the `seed=3`) and nodes 2-10 exit at startup with the error:

```
Error: cockroach server exited with error: inspecting engines: store <no-attributes>=/mnt/data1/cockroach, last used with cockroach version v1.1, is too old for running version v2.0-8 (which requires data from v2.0 or later)
```

The fixture was generated with version `v2.0-7` (this is stored in the name of the store subdirectory for the above fixture). Did we foul something up with the recent cluster version bumps?

Cc @nvanbenschoten who touched some code in this area recently.

### PR DESCRIPTION
**Pull request by tbg**
Prior to this commit, when a node joined an existing cluster, it would
likely persist its MinSupportedVersion as the cluster version (even
though it would operate at the correct version). This is problematic
since this node's data directories wouldn't be regarded compatible with
the successor version of the real version, even though they are.

The problem was that the callback which receives the real cluster
version would fire before the stores were bootstrapped, and bootstrap
would erroneously pick the minimum supported version. We now "backfill"
the correct cluster version after having bootstrapped all stores.

Even though the fixtures will need to be regenerated:
Fixes #27525.

Optimistically:
Fixes #27162.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
Interestingly we'll have to do something about the mixed version tests still, since that test involves nodes that don't have the code. My preference would be to add an extra stop-restart cycle in the test which will update the cluster version in-place even on the old binaries.

**Comment by tschottdorf** [comment]
Still playing with the roachtest -- got it failing immediately with a

```
> /Users/tschottdorf/go/bin/roachprod run local:1 -- ./cockroach quit --insecure --port {pgport:1}
Error: Failed to connect to the node: initial connection heartbeat failed: rpc error: code = Unknown desc = version compatibility check failed on ping request: cluster requires at least version 2.0-9, but peer has version 2.0
```

which is odd because the cluster version *is* supposedly 2.0. Looking.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27639#-:-LHhgqLy6uXX1tBTkjO_:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/stores.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27639#-LHhgkae8WEKSyUzheCb:-LHhgkae8WEKSyUzheCc:b-3n9x3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a670b0266834cee431b017fa4d9a3ddba6c613f/pkg/storage/stores.go#L447)):*
> ```Go
> 	}
> 	// If the update downgrades the minimum version, ignore it. Must be
> 	// a reordering. Note that we do carry out the upgrade if the MinVersion
> ```

Can you elaborate on the reordering that is possible here?

**Review by tbg — COMMENTED** [review]
RFAL, the new commits take care of the roachtest failures.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27639#-:-LHhxFqU8g2rdGNhC3LB:bgmtf61)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/stores.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27639#-LHhgkae8WEKSyUzheCb:-LHhubbqEc_MvM-upClE:b-4cy7bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a670b0266834cee431b017fa4d9a3ddba6c613f/pkg/storage/stores.go#L447)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you elaborate on the reordering that is possible here?
</blockquote></details>

Done. (Along with a small refactor).

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27639)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/upgrade.go, line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27639#-LHiHeLj2D1tskAGdjCb:-LHiHeLj2D1tskAGdjCc:bwzwwcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa7677f934d2570e48a5fc84f6ad678a1c722be8/pkg/cmd/roachtest/upgrade.go#L55)):*
> ```Go
> 
> 		// TODO(tschottdorf): this is a hack similar to the one in the mixed version
> 		// test. Remove it when we have a 2.0.x binary that has #27639 fixed.
> ```

Might want to file an issue so you don't forget about this. Or just don't forget about this.

**Comment by tschottdorf** [comment]
Reminder filed: https://github.com/cockroachdb/cockroach/issues/27717

bors r=petermattis
TFTR!

**Pull request merged**
