### PR TITLE
sql: scrub constants from sampled logical plan

### PR DESCRIPTION
**Pull request by celiala**
We were previously exposing the raw `EXPLAIN` output
of sampled logical plans.

This commit scrubs constants from sampled logical plans,
to match the same amount of information we expose in the
statement's fingerprint.

Before:

scrub before

After:

scrub after

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @jordanlewis, @knz, and @piyush-singh)

___
*[pkg/sql/explain_plan.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8l9Ez2nHEg_XeyLm1:-LY8l9Ez2nHEg_XeyLm2:bbpcmo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_plan.go#L281)):*
> ```Go
> 	e.entries = nil
> 	observer := e.observer()
> 	_ = populateEntriesForObserver(ctx, plan, subqueryPlans, observer, false /* returnError */, tree.FmtSimple)
> ```

Hmm, I kind of think this should be FmtHideConstants too - wouldn't this mean we show constants in subquery strings?
___
*[pkg/sql/explain_tree.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8klCD8vxH3yUpRtiu:-LY8klCD8vxH3yUpRtiv:byuauh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_tree.go#L26)):*
> ```Go
> 
> const (
> 	//
> ```

empty comment? maybe you meant to write something here :)
___
*[pkg/sql/explain_tree.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8ktCI78h_4zGNZ4cs:-LY8ktCI78h_4zGNZ4ct:b-ctab7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_tree.go#L59)):*
> ```Go
> 				Name: nodeName,
> 			})
> 			if nodeName == "subquery" {
> ```

I'm not sure what this is for - it looks like we'll return `true, nil` in either case!

**Review by celiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @piyush-singh)

___
*[pkg/sql/explain_plan.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8l9Ez2nHEg_XeyLm1:-LYCxqhcDHPCkyHsuLa6:b-yref4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_plan.go#L281)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, I kind of think this should be FmtHideConstants too - wouldn't this mean we show constants in subquery strings?
</blockquote></details>

Ah, good callout. I took a closer look at `populateEntries`, and it's being used by `planToString` and `populateExplain`:

* `planToString` explicitly sets `e.fmtFlags` to `FmtSymbolicSubqueries`, so this should change so that subquery logic uses that as well.
* I think(?) `populateExplain` generates the output for `EXPLAIN`? If so, it looks like `EXPLAIN` exposes constants for other node/field types, so subquery logic should do the same.

So I've fixed the param to use `e.fmtFlags`, which should solve for both cases above.
___
*[pkg/sql/explain_tree.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8klCD8vxH3yUpRtiu:-LYD2_516bwk22KeLXOn:b-6qgv5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_tree.go#L26)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

empty comment? maybe you meant to write something here :)
</blockquote></details>

oops -- was reviewing wrong diff & pushed up before cleaning up all my code :woman_facepalming:
___
*[pkg/sql/explain_tree.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8ktCI78h_4zGNZ4cs:-LYCgoY8CNd8aEi9X7RQ:b-ujg1st) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_tree.go#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm not sure what this is for - it looks like we'll return `true, nil` in either case!
</blockquote></details>

 :woman_facepalming: (oops, my hack for debugging, will remove ;) )

**Comment by celiala** [comment]
TFTR :) PTAL --

Re your first comment: reading through the adjacent code, I _think_ using `e.fmtFlags` is what we want, but let me know if it should be different (see thought process inline).

**Comment by celiala** [comment]
Not ready for review yet -- 

Tests are failing because of mismatched subquery results. Let me take a closer look and fix.

**Review by celiala — COMMENTED** [review]
PTAL -- thanks! 

Fixed tests and PR is ready for another look:

* After trying `e.fmtFlags` and `FmtHideConstants` for `planToString` and `populateExplain`, I think we still want to stick with `FmtSimple` (see comment inline).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-:-LYEBXar0wvXA3qLdY-C:b-9uwnai)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @piyush-singh)

___
*[pkg/sql/explain_plan.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8l9Ez2nHEg_XeyLm1:-LYDzyEi8Ta8sdHGmmma:buqzk2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_plan.go#L281)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

Ah, good callout. I took a closer look at `populateEntries`, and it's being used by `planToString` and `populateExplain`:

* `planToString` explicitly sets `e.fmtFlags` to `FmtSymbolicSubqueries`, so this should change so that subquery logic uses that as well.
* I think(?) `populateExplain` generates the output for `EXPLAIN`? If so, it looks like `EXPLAIN` exposes constants for other node/field types, so subquery logic should do the same.

So I've fixed the param to use `e.fmtFlags`, which should solve for both cases above.
</blockquote></details>

I think sticking to `tree.FmtSimple` for `planToString` and `planExplain` is what we want, but let me know if you disagree:

* I tried using  the explainer's `.fmtFlags` to format subqueries for both `planToString` and `planExplain`, but that was too aggressive, changing `original sql=(SELECT unnest(ARRAY[x, y]) FROM xy)` to `original sql=@S1`.

* Next I tried `tree.FmtHideConstants` for `planToString` and `planExplain`, but this means that we'd be changing what users see when they use `EXPLAIN` (see failed test below for diff). This could indeed be what we want(?), but would love your thoughts here @jordanlewis.

So for now, I'll keep the formatter for `planToString` and `planExplain` subqueries the same (`tree.FmtSimple`).


Example failed test to show how we'd be changing `EXPLAIN`'s output:
```
                testdata/scalar:591: EXPLAIN (VERBOSE) SELECT ARRAY(SELECT generate_series(1,10) ORDER BY 1 DESC)
                expected:
                    root                          ·              ·                                                ("array")          ·
                     ├── values                   ·              ·                                                ("array")          ·
                     │                            size           1 column, 1 row                                  ·                  ·
                     │                            row 0, expr 0  ARRAY @S1                                        ·                  ·
                     └── subquery                 ·              ·                                                ("array")          ·
                          │                       id             @S1                                              ·                  ·
                          │                       original sql   (SELECT generate_series(1, 10) ORDER BY 1 DESC)  ·                  ·
                          │                       exec mode      all rows                                         ·                  ·
                          └── sort                ·              ·                                                (generate_series)  -generate_series
                               │                  order          -generate_series                                 ·                  ·
                               └── project set    ·              ·                                                (generate_series)  ·
                                    │             render 0       generate_series(1, 10)                           ·                  ·
                                    └── emptyrow  ·              ·                                                ()                 ·

                but found (query options: "") :
                    root                          ·              ·                                               ("array")          ·
                     ├── values                   ·              ·                                               ("array")          ·
                     │                            size           1 column, 1 row                                 ·                  ·
                     │                            row 0, expr 0  ARRAY @S1                                       ·                  ·
                     └── subquery                 ·              ·                                               ("array")          ·
                          │                       id             @S1                                             ·                  ·
                          │                       original sql   (SELECT generate_series(_, _) ORDER BY _ DESC)  ·                  ·
                          │                       exec mode      all rows                                        ·                  ·
                          └── sort                ·              ·                                               (generate_series)  -generate_series
                               │                  order          -generate_series                                ·                  ·
                               └── project set    ·              ·                                               (generate_series)  ·
                                    │             render 0       generate_series(1, 10)                          ·                  ·
                                    └── emptyrow  ·              ·                                               ()                 ·
```
___
*[pkg/sql/explain_tree.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8klCD8vxH3yUpRtiu:-LYECFkzAN0SQbrAMyTw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_tree.go#L26)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

oops -- was reviewing wrong diff & pushed up before cleaning up all my code :woman_facepalming:
</blockquote></details>

Done.
___
*[pkg/sql/explain_tree.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8ktCI78h_4zGNZ4cs:-LYECGLT56YCW1DwzLmf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_tree.go#L59)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

 :woman_facepalming: (oops, my hack for debugging, will remove ;) )
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-:-LYEFaEb07eRrgDe8Ju7:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @piyush-singh)

___
*[pkg/sql/explain_plan.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34724#-LY8l9Ez2nHEg_XeyLm1:-LYEEaeX5GunGJInErfS:b-uwf30b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b407ba4a073a00858d083274006d68c902ce91d/pkg/sql/explain_plan.go#L281)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

I think sticking to `tree.FmtSimple` for `planToString` and `planExplain` is what we want, but let me know if you disagree:

* I tried using  the explainer's `.fmtFlags` to format subqueries for both `planToString` and `planExplain`, but that was too aggressive, changing `original sql=(SELECT unnest(ARRAY[x, y]) FROM xy)` to `original sql=@S1`.

* Next I tried `tree.FmtHideConstants` for `planToString` and `planExplain`, but this means that we'd be changing what users see when they use `EXPLAIN` (see failed test below for diff). This could indeed be what we want(?), but would love your thoughts here @jordanlewis.

So for now, I'll keep the formatter for `planToString` and `planExplain` subqueries the same (`tree.FmtSimple`).


Example failed test to show how we'd be changing `EXPLAIN`'s output:
```
                testdata/scalar:591: EXPLAIN (VERBOSE) SELECT ARRAY(SELECT generate_series(1,10) ORDER BY 1 DESC)
                expected:
                    root                          ·              ·                                                ("array")          ·
                     ├── values                   ·              ·                                                ("array")          ·
                     │                            size           1 column, 1 row                                  ·                  ·
                     │                            row 0, expr 0  ARRAY @S1                                        ·                  ·
                     └── subquery                 ·              ·                                                ("array")          ·
                          │                       id             @S1                                              ·                  ·
                          │                       original sql   (SELECT generate_series(1, 10) ORDER BY 1 DESC)  ·                  ·
                          │                       exec mode      all rows                                         ·                  ·
                          └── sort                ·              ·                                                (generate_series)  -generate_series
                               │                  order          -generate_series                                 ·                  ·
                               └── project set    ·              ·                                                (generate_series)  ·
                                    │             render 0       generate_series(1, 10)                           ·                  ·
                                    └── emptyrow  ·              ·                                                ()                 ·

                but found (query options: "") :
                    root                          ·              ·                                               ("array")          ·
                     ├── values                   ·              ·                                               ("array")          ·
                     │                            size           1 column, 1 row                                 ·                  ·
                     │                            row 0, expr 0  ARRAY @S1                                       ·                  ·
                     └── subquery                 ·              ·                                               ("array")          ·
                          │                       id             @S1                                             ·                  ·
                          │                       original sql   (SELECT generate_series(_, _) ORDER BY _ DESC)  ·                  ·
                          │                       exec mode      all rows                                        ·                  ·
                          └── sort                ·              ·                                               (generate_series)  -generate_series
                               │                  order          -generate_series                                ·                  ·
                               └── project set    ·              ·                                               (generate_series)  ·
                                    │             render 0       generate_series(1, 10)                          ·                  ·
                                    └── emptyrow  ·              ·                                               ()                 ·
```

</blockquote></details>

Ok, yeah, it looks like this would really change a bunch more things at once than we intend. I do think that this can still leak user data though - if somebody put a username inside of the subquery we'd end up showing it here, right?

But now that I look at your tests it looks like that that's happening anyway! So I think I must have misunderstood something before.

**Comment by piyush-singh** [comment]
LGTM! Deployed this branch via roachprod and ran tests using Celia's Movies db and some adhoc queries on tables I created. Was able to verify that no sensitive information was leaking in plans in any of my tests.

**Review by piyush-singh — APPROVED** [review]

**Comment by celiala** [comment]
TFTR!

bors r+

**Pull request merged**
