### PR TITLE
libroach: make DBSstFileWriter output work with time bound iterator

### LINKED ISSUE #26870: storageccl: data loaded by Import does not play well with TimeBoundIterator
`TimeBoundIterator` works by looking in sstable metadata for bounds on the mvcc timestamps contained. If the iterator's timestamps don't overlap, the sstable can be skipped entirely. Import doesn't add the metadata when constructing the sstables that it sends off to `AddSSTable` so, when TimeBoundIterator encounters one of these, it has to be pessimistic and scan the file. Import should be adding the appropriate metadata to the files it sends (really `engine.RocksDBSstFileWriter` is what is going to handle this).

The performance of `TimeBoundIterator` is pretty important to the "initial scan" phase of cdc, so this essentially breaks cdc on any data that comes from `RESTORE` or `IMPORT` until it's compacted (which adds the metadata). A workaround in the meantime is to run `./cockroach debug compact`.

### PR DESCRIPTION
**Pull request by danhhz**
The time bounded iterator optimization looks for sstable metadata that
indicates the min and max mvcc timestamp included. The iterator (which
is configured with a min and max bounds) can use this to skip tables
that don't have relevant data. When the bounds aren't set, it has to
fall back to checking the table.

The TimeBoundTblPropCollectorFactory already sets the metadata on
sstable creation, but it wasn't hooked up to DBSstFileWriter. This meant
that IMPORT and RESTORE (both of which use DBSstFileWriter via the
Import command) would create and ingest sstables that hit the no bounds
fall back.

This commit adds TimeBoundTblPropCollectorFactory to DBSstFileWriter
which means data ingested via RESTORE and IMPORT now work with time
bounded iterators just like any other sstables.

Closes #26870

Release note (performance improvement): data ingested with RESTORE and
IMPORT is now eligible for a performance optimization used in
incremental BACKUP and CHANGEFEEDs

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm: awesome!

I think it would be cleaner to move the properties collector into its own header file (tableprops.h?), but totally fine as is!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27966#-:-LINHLhuAR-TwkdLHDvd:b-hwo3u4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[c-deps/libroach/db.cc, line 712 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27966#-LINGXZf8BqY1HOm2Wkh:-LINGXZf8BqY1HOm2Wki:b-h49lc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/744c0d5da6f6ed4c45d635a8978f235d81e95415/c-deps/libroach/db.cc#L712)):*
> ```cpp
>   std::shared_ptr<rocksdb::TablePropertiesCollectorFactory> time_bound_prop_collector(
>       DBMakeTimeBoundCollector());
>   options->table_properties_collector_factories.push_back(time_bound_prop_collector);
> ```

You should be able to either do

```
options->table_properties_collector_factories.emplace_back(DBMakeTimeBoundCollector());
```

or

```
options->table_properties_collector_factories.emplace_back(
    std::make_shared(DBMakeTimeBoundCollector()));
```

to avoid the temporary.

**Review by danhhz — COMMENTED** [review]
Moved into timebound.{h,cc}. RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27966#-:-LIR_B9E9BpnPyrDHQJL:b-dir4qh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[c-deps/libroach/db.cc, line 712 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27966#-LINGXZf8BqY1HOm2Wkh:-LIR_7TLANT9VRWEqyxU:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/744c0d5da6f6ed4c45d635a8978f235d81e95415/c-deps/libroach/db.cc#L712)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You should be able to either do

```
options->table_properties_collector_factories.emplace_back(DBMakeTimeBoundCollector());
```

or

```
options->table_properties_collector_factories.emplace_back(
    std::make_shared(DBMakeTimeBoundCollector()));
```

to avoid the temporary.
</blockquote></details>

Done

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27966#-:-LIRf9wM3wGjQ8MYvVo5:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by danhhz** [comment]
Thanks for the reviews!

bors r=benesch

**Pull request merged**
