### PR TITLE
kv: use AmbientContext in TxnCoordSender

### PR DESCRIPTION
**Pull request by RaduBerinde**
Part of #9807.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10139)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

This series of changes makes me so happy.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/kv/txn_coord_sender.go, line 198 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd-whIAA0dpLbOqfxZ:-KUd-whIAA0dpLbOqfx_:b-idnj3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/kv/txn_coord_sender.go#L198)):*
> ```Go
> // concerned. stats).
> func (tc *TxnCoordSender) printStatsLoop() {
> 	ctx := tc.AnnotateCtx(context.Background())
> ```

Can this move up the stack so it's closer to the RunTask or RunWorker?

---

*[pkg/kv/txn_coord_sender_test.go, line 806 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0BeoN9_aRnU1goD_:-KUd0BeoN9_aRnU1goDa:biw68ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/kv/txn_coord_sender_test.go#L806)):*
> ```Go
> 		ambient := log.AmbientContext{Tracer: tracing.NewTracer()}
> 		ts := NewTxnCoordSender(
> 			ambient, senderFn(senderFunc), clock, false, stopper,
> ```

while you're here, mind putting each arg on its own line?

---

*[pkg/kv/txn_coord_sender_test.go, line 1002 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0IWgYEJ1R7kNcV-_:-KUd0IWgYEJ1R7kNcV-a:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/kv/txn_coord_sender_test.go#L1002)):*
> ```Go
> 			ambient := log.AmbientContext{Tracer: tracing.NewTracer()}
> 			ts := NewTxnCoordSender(
> 				ambient, senderFn(senderFunc), clock, false, stopper,
> ```

ditto

---

*[pkg/server/node_test.go, line 107 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0NtQg1mLVbhA_VcV:-KUd0NtQg1mLVbhA_VcW:boss5j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/server/node_test.go#L107)):*
> ```Go
> 	}, g)
> 	cfg.AmbientCtx.Tracer = tracing.NewTracer()
> 	sender := kv.NewTxnCoordSender(cfg.AmbientCtx, distSender, cfg.Clock, false, stopper,
> ```

ditto, maybe? (since you didn't touch both lines)

---

*[pkg/server/server.go, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0PSJ0ZRKEuRp963e:-KUd0PSJ0ZRKEuRp963f:boss5j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/server/server.go#L202)):*
> ```Go
> 	txnMetrics := kv.MakeTxnMetrics(s.cfg.MetricsSampleInterval)
> 	s.registry.AddMetricStruct(txnMetrics)
> 	s.txnCoordSender = kv.NewTxnCoordSender(s.cfg.AmbientCtx, s.distSender, s.clock, cfg.Linearizable,
> ```

ditto, maybe? (since you didn't touch both lines)

---

*[pkg/server/server_test.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0Vfgq0lmyoThpRCs:-KUd0Vfgq0lmyoThpRCt:boss5j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/server/server_test.go#L213)):*
> ```Go
> 	}, ts.Gossip())
> 	ambient := log.AmbientContext{Tracer: tracing.NewTracer()}
> 	tds := kv.NewTxnCoordSender(ambient, ds, s.Clock(), ts.Cfg.Linearizable,
> ```

ditto, maybe? (since you didn't touch both lines)

---

*[pkg/server/server_test.go, line 310 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0WD9hifBuGn2ReTO:-KUd0WD9hifBuGn2ReTP:boss5j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/server/server_test.go#L310)):*
> ```Go
> 		}, ts.Gossip())
> 		ambient := log.AmbientContext{Tracer: tracing.NewTracer()}
> 		tds := kv.NewTxnCoordSender(ambient, ds, ts.Clock(), ts.Cfg.Linearizable,
> ```

ditto, maybe? (since you didn't touch both lines)

---

*[pkg/storage/client_test.go, line 603 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0UXAn2ok8k4aY9kd:-KUd0UXAn2ok8k4aY9ke:boss5j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/storage/client_test.go#L603)):*
> ```Go
> 	}, m.gossips[idx])
> 	ambient := log.AmbientContext{Tracer: tracing.NewTracer()}
> 	sender := kv.NewTxnCoordSender(ambient, m.distSenders[idx], m.clock, false,
> ```

ditto, maybe? (since you didn't touch both lines)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-:-KUd0XUxW84ytVO6GQuN:b-5pu77x)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/kv/txn_coord_sender.go, line 198 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd-whIAA0dpLbOqfxZ:-KUd4E4CCZjqfSz6mkyA:b-80tlqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/kv/txn_coord_sender.go#L198)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Can this move up the stack so it's closer to the RunTask or RunWorker?
</details>
Sure.

---

*[pkg/kv/txn_coord_sender_test.go, line 806 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-KUd0BeoN9_aRnU1goD_:-KUd4F9vonB3zihANTA1:blxpw5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fead4432cf8a35fa9f0402ccadf114e1690972d/pkg/kv/txn_coord_sender_test.go#L806)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> while you're here, mind putting each arg on its own line?
</details>
Ok, but note that the consensus in #9687 was not to bikeshed over this on reviews (even if we had agreed on a particular form, which we didn't).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139#-:-KUd5zhZQVc-OJ1_Cy09:b-814g8k)*

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10139)*

**Comment by tamird** [comment]
Yep, consider all the bikeshedding optional.

**Pull request merged**
