### PR TITLE
cli: allow `node status` to work in unavailable/broken clusters

### LINKED ISSUE #16489: cli: let commands return partial information when run against unavailable/broken clusters
Users expect to be able to get some information after running cockroach node status, even in the case of partitioning or loss of quorum.

It would be helpful to reveal some information from the local node (basically a warning that the node is no longer able to communicate with the rest of the cluster).

### PR DESCRIPTION
**Pull request by petermattis**
Expand the `crdb_internal.gossip_liveness` table to include columns
needed to satisfy the basic usage of `node status`. Specifically, added
`address`, `build`, `started_at`, `updated_at` and `replicas`
columns. Changed `node status` to use `gossip_liveness` instead of
`kv_node_status`. The latter table requires the range containing the
consistent node status descriptors to be available, while
`gossip_liveness` only retrieves info from gossip.

`node status` and `node status --decommission` will work on
unavailable/broken clusters as long as the node they are pointed to is
up. `node status {--stats,--ranges,--all}` continue to require a
reasonably healthy cluster.

Fixes #16489

Release note (cli change): Enhance `node status` to work on
unavailable/broken clusters.

### CODE REVIEW

**Comment by petermattis** [comment]
This needs a test. @knz do any of the cli tests start up multi-node clusters? If yes, can you point me towards where that is done.

**Comment by petermattis** [comment]
Rather than extend `gossip_liveness`, perhaps I should be adding these new fields to `gossip_nodes` and then joining with that table.

**Comment by petermattis** [comment]
> Rather than extend gossip_liveness, perhaps I should be adding these new fields to gossip_nodes and then joining with that table.

This is done. Still need to add a test.

**Review by bdarnell — APPROVED** [review]
LGTM aside from tests. None of the CLI tests start a multi-node cluster (but `test_init_command.tcl` comes closest). Or you could do it in a regular test using TestCluster (like I did for the remove-dead-replicas command). Not quite end-to-end, but close enough.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28249#-:-LJErJ4F3AjwrelQjY63:b-bzsnem)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
Yeah the hassle to do this using a TCL test is comparable to that of a Go test, so in this case I would recommend a Go test.

It can also become an acceptance test instead of a CLI test. In acceptance tests we have multi-node clusters and we're properly testing end-to-end.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28249#-:-LJI6oLE64oMfMlzY8wy:b-j3dw51)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal.go, line 1835 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28249#-LJI6XZI8v9klC3218A3:-LJI6XZI8v9klC3218A4:b-1nptm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c445a945e25feaac90d67212a3e2256730294a48/pkg/sql/crdb_internal.go#L1835)):*
> ```Go
> }
> 
> // crdbInternalGossipLivenessTable exposes local information about the nodes' liveness.
> ```

1) Extend this comment to explain the information can be stale / incomplete because gossip doesn't come with a guarantee of accuracy.
2) please check if the query against this table in `workloadccl/fixture.go` is still correct with your changes.

**Review by petermattis — COMMENTED** [review]
(I still need to add a test).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28249#-:-LJUGm5FE-VP-EXvyyu7:br5i2qq)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal.go, line 1835 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28249#-LJI6XZI8v9klC3218A3:-LJUGPLN9Yy3axvMMlVQ:b-3pgc9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c445a945e25feaac90d67212a3e2256730294a48/pkg/sql/crdb_internal.go#L1835)):*
Extended the comment, though any time the term gossip is used, the reader should understand that consistency and freshness are not present.

> please check if the query against this table in workloadccl/fixture.go is still correct with your changes.

Thanks for the pointer. That query is `SELECT count(node_id) FROM "".crdb_internal.gossip_liveness`. Do you have any reason to suspect it wouldn't continue to work?

**Review by petermattis — COMMENTED** [review]
I've added a `cli/node-status` roachtest and also added that roachtest to the list that is run on every CI. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28249#-:-LJZKN0U91D2MKyVSDSA:b-a1nv5)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 6 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28249)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by petermattis** [comment]
bors r=bdarnell

**Comment by petermattis** [comment]
bors r=bdarnell

**Pull request merged**
