### PR TITLE
kvserver: add new version of Stores.GetReplForRange 

### PR DESCRIPTION
**Pull request by andreimatei**
The existing version is broken because it doesn't handle multiple stores
having a replica for the same range, and it's also inneficient because
it allocates in case of failure to find the replicas.

This patch adds a new version of the function which returns all the
replicas, and modifies some callers to use it. The new version takes in
slices to be populated in order to avoid repeated allocations for these
slices.

Release note: None
Release justification: low risk, needed by a different patch

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
:lgtm_strong: for the first two commits.

I'm less in love with the third one. Creating a new `ForEachReplicaWithRangeID` version that accepts a `func(*Store, *Replica) error` seems like the way to go. And you can hook it up to use `iterutil.StopIteration()`. That won't allocate as long as you don't pass the function through an interface.

> Reviewed 5 of 5 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61276#-:-MUj5ZCt0gUJsqYyt4Ep:breehoi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
removed the last commit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61276#-:-MUkv-LzBktoMp9LuEIE:b-6wn89f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Review by aayushshah15 — APPROVED** [review]
LGTM

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61276#-:-MUl2YN66-kpKjlq-FZ6:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Pull request merged**
