### PR TITLE
sqlproxy: use SAN instead of common name in test server certificate

### LINKED ISSUE #56377: sqlproxyccl: TestFailedConnection has different error messages on Go 1.15
Some connection error messages can be different with the upgrade.

Looks like some of the sqlproxyccl error messages have changed (https://teamcity.cockroachdb.com/viewLog.html?buildId=2423317&buildTypeId=Cockroach_UnitTests)
```

=== RUN   TestFailedConnection/defaultdb_29?sslmode=verify-full&sslrootcert=testserver.crt
I201106 16:15:32.668491 40 ccl/sqlproxyccl/server.go:148  handling client 127.0.0.1:54432
I201106 16:15:32.668544 40 ccl/sqlproxyccl/server.go:150  client 127.0.0.1:54432 disconnected after 0.00s: <nil>
I201106 16:15:32.676866 69 ccl/sqlproxyccl/server.go:148  handling client 127.0.0.1:54434
    proxy_test.go:119: 
        	Error Trace:	proxy_test.go:119
        	Error:      	"failed to connect to `host=localhost user=unused database=defaultdb_29`: dial error (dial tcp [::1]:43363: connect: cannot assign requested address)" does not contain "unable to reach backend SQL server"
        	Test:       	TestFailedConnection/defaultdb_29?sslmode=verify-full&sslrootcert=testserver.crt
    --- FAIL: TestFailedConnection/defaultdb_29?sslmode=verify-full&sslrootcert=testserver.crt (0.02s)
```

PR: https://github.com/cockroachdb/cockroach/pull/56363

### PR DESCRIPTION
**Pull request by spaskob**
go1.15 no longer accepts self-signed certs that rely on Common Name.
Instead it requires using Subject Alt Name (SAN). Regenerate new certs
that include the SAN and add certificate config file.

See also https://github.com/golang/go/issues/39568.

Fixes #56377.

Release note: none.

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Comment by spaskob** [comment]
TFTR!

**Comment by spaskob** [comment]
bors r=tbg

**Comment by spaskob** [comment]
bors r=tbg

**Comment by tbg** [comment]
Not your fault

bors r+

**Pull request merged**
