### PR TITLE
sql: sqlType creation

### PR DESCRIPTION
**Pull request by maryliag**
Creation of the sqlType that classifies all Statements between DDL, DML, DCL or TCL

Release node (sql change): Adding new classification of Statements between DDL, DML, DCL or TCL

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/roachpb/app_stats.proto, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnhHwA7W9_jSqzGyr:-MXDnhHwA7W9_jSqzGys:beixym4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/roachpb/app_stats.proto#L94)):*
> ```protobuf
>   optional ExecStats exec_stats = 21 [(gogoproto.nullable) = false];
> 
>   // SqlType is the type of the sql, between DDL, DML and DCL
> ```

or TCL!
___
*[pkg/sql/sem/tree/stmt.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnTE6DBUda_UIH78L:-MXDnTE6DBUda_UIH78M:b8mrw7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L74)):*
> ```Go
> 
> 	StatementReturnType() StatementReturnType
> 	// StatementType returns the SQL Type as DDL, DML or DCL
> ```

nit: we also return TCL!
___
*[pkg/sql/sem/tree/stmt.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnRQ3DMLoe3auHFoQ:-MXDnRQ3DMLoe3auHFoR:b-8nsl6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L81)):*
> ```Go
> 	// concerned with rights, permissions and other controls of the database system.
> 	// TCL (Transaction Control Language) deals with a transaction within a database.
> 	StatementType() string
> ```

I think it would make sense to define these in an enum, the way `StatementReturnType` is done. Then it would prevent typos or other mistakes in the returned strings. We can define a string representation of them as well, the same way as in `StatementReturnType`. 
___
*[pkg/sql/sem/tree/stmt.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDksBH-fb-TTvtsCzw:-MXDksBH-fb-TTvtsCzx:bax5yfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L165)):*
> ```Go
> 
> // StatementReturnType implements the Statement interface.
> func (*AlterDatabaseOwner) StatementReturnType() StatementReturnType { return DDL }
> ```

I think this would be DCL, since it's about permissions?
___
*[pkg/sql/sem/tree/stmt.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDmf1S3ZFcmubf_F00:-MXDmf1S3ZFcmubf_F01:b-z54kkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L253)):*
> ```Go
> 
> // StatementReturnType implements the Statement interface.
> func (*AlterTableOwner) StatementReturnType() StatementReturnType { return DDL }
> ```

DCL I think?
___
*[pkg/sql/sem/tree/stmt.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDmmBY3miFxvs3XHOj:-MXDmmBY3miFxvs3XHOk:b-di2n6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L417)):*
> ```Go
> 
> // StatementType implements the Statement interface.
> func (*CannedOptPlan) StatementType() string { return "DML" }
> ```

I'm not sure about this one cc @rytaft 
___
*[pkg/sql/sem/tree/stmt.go, line 806 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnAaJDkv6L2tIkwQq:-MXDnAaJDkv6L2tIkwQr:b-v5cy35) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L806)):*
> ```Go
> 
> // StatementType implements the Statement interface.
> func (*ReassignOwnedBy) StatementType() string { return "DDL" }
> ```

DCL maybe?
___
*[pkg/sql/sem/tree/stmt.go, line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnBki13DNEKMDR6Dl:-MXDnBki13DNEKMDR6Dm:b-v5cy35) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L815)):*
> ```Go
> 
> // StatementType implements the Statement interface.
> func (*DropOwnedBy) StatementType() string { return "DDL" }
> ```

DCL maybe?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rytaft)

___
*[pkg/roachpb/app_stats.proto, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnhHwA7W9_jSqzGyr:-MXE10NYAd_ST6fJC9Sp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/roachpb/app_stats.proto#L94)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

or TCL!
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/stmt.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnRQ3DMLoe3auHFoQ:-MXE1B2b105Aj_Fg-0tM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L81)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it would make sense to define these in an enum, the way `StatementReturnType` is done. Then it would prevent typos or other mistakes in the returned strings. We can define a string representation of them as well, the same way as in `StatementReturnType`. 
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/stmt.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDksBH-fb-TTvtsCzw:-MXE1D1C4G4LpyezEh7s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L165)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this would be DCL, since it's about permissions?
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/stmt.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDmf1S3ZFcmubf_F00:-MXE1F3hCoCSNKDUX__Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L253)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

DCL I think?
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/stmt.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDmmBY3miFxvs3XHOj:-MXE1djX6IGXNeoHBKFB:b4ffdn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L417)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm not sure about this one cc @rytaft 
</blockquote></details>

I went with DML on this one just because the ReturnType was Rows and was DML for the majority of the ones returning Rows
___
*[pkg/sql/sem/tree/stmt.go, line 806 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnAaJDkv6L2tIkwQq:-MXE1K714P-akWJVFVz_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L806)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

DCL maybe?
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/stmt.go, line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnBki13DNEKMDR6Dl:-MXE1L7O2ovtBtxwfOxq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L815)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

DCL maybe?
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @maryliag, and @rytaft)

___
*[pkg/roachpb/app_stats.proto, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnhHwA7W9_jSqzGyr:-MXE7ISV1w4zr6A814BU:b-kjknhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/roachpb/app_stats.proto#L94)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should this be an enum? If not, can we at least list what the values stand for in the comment? (had to google CL and TCL)
___
*[pkg/roachpb/app_stats.proto, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXE7yMe6rx4azVTOQUN:-MXE7yMe6rx4azVTOQUO:b-azj50i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db3343f6ab85e59aaeff64fdf3c495d763a6d09/pkg/roachpb/app_stats.proto#L94)):*
> ```protobuf
>   optional ExecStats exec_stats = 21 [(gogoproto.nullable) = false];
> 
>   // SqlType is the type of the sql (DDL, DML, DCL or TCL)
> ```

[nit] we should override this field's name to `SQLType` using `"(gogoproto.customname)": "SQLType"`
___
*[pkg/sql/sem/tree/stmt.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXE8DVgEv-DohQank2p:-MXE8DVgEv-DohQank2q:b-qsbqkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L49)):*
> ```Go
> 	// report RowsAffected to the client, not DDL.
> 	// Use CanModifySchema() below instead.
> 	DDL
> ```

Do we still need a DDL StatementReturnType?  I'm guessing having this distinction here was mainly a hack because we were lacking the separate classification.
___
*[pkg/sql/sem/tree/stmt.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnRQ3DMLoe3auHFoQ:-MXE8ghSA4ETDkHEV-KX:b-pmkt1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L81)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we want the values to be public (capitalized), no?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @maryliag, and @rytaft)

___
*[pkg/sql/sem/tree/stmt.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDmmBY3miFxvs3XHOj:-MXE9xSk0Vtni_DLWR9w:b9gbt4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L417)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I went with DML on this one just because the ReturnType was Rows and was DML for the majority of the ones returning Rows
</blockquote></details>

Yeah I would keep it DML (in principle, it could be anything, but it's only used for testing)
___
*[pkg/sql/sem/tree/stmt.go, line 374 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXEAREk9ICnhQ2Og3wo:-MXEAREk9ICnhQ2Og3wp:b-affpcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db3343f6ab85e59aaeff64fdf3c495d763a6d09/pkg/sql/sem/tree/stmt.go#L374)):*
> ```Go
> 
> // StatementType implements the Statement interface.
> func (*ControlJobs) StatementType() StatementType { return typeDML }
> ```

Should these "control" ops be TCL instead? They don't neatly fit in either.
___
*[pkg/sql/sem/tree/stmt.go, line 1662 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXEB2O29R6XFd_5jOyR:-MXEB2O29R6XFd_5jOyS:bwzgmu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db3343f6ab85e59aaeff64fdf3c495d763a6d09/pkg/sql/sem/tree/stmt.go#L1662)):*
> ```Go
> 
> func (n StatementType) String() string {
> 	return [...]string{"DDL", "DML", "DCL", "TCL"}[n]
> ```

[nit] Don't we have a `//go:generate stringer -type=StatementType` for this type?
If we want our own, we should define the table right where we define the enum values, and we should key off of them:
```
var statementTypeStr = [...]string{
  typeDDL: "DDL",
  ...
}
```

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/roachpb/app_stats.proto, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnhHwA7W9_jSqzGyr:-MXEBnzI5-WgF0PEoFgw:b-jqee91) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/roachpb/app_stats.proto#L94)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this be an enum? If not, can we at least list what the values stand for in the comment? (had to google CL and TCL)
</blockquote></details>

I believe the enum would be even less clear, so I'll keep as the string and add a comment about each one
___
*[pkg/sql/sem/tree/stmt.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXE8DVgEv-DohQank2p:-MXEFIgX4DhKyLKJpmZy:b-idiyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L49)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we still need a DDL StatementReturnType?  I'm guessing having this distinction here was mainly a hack because we were lacking the separate classification.
</blockquote></details>

I didn't want to risk replacing the existing function because seems to be used for documentation and I didn't want to break any other code
___
*[pkg/sql/sem/tree/stmt.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDnRQ3DMLoe3auHFoQ:-MXEZ1UfDDZ0muQV-HDj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we want the values to be public (capitalized), no?
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/stmt.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXDmmBY3miFxvs3XHOj:-MXEZ5Ob5Kz3I4_SeiCK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0da6ccc612fb24ec2d7a442ed3a2e30fde2c8a9/pkg/sql/sem/tree/stmt.go#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah I would keep it DML (in principle, it could be anything, but it's only used for testing)
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/stmt.go, line 1662 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXEB2O29R6XFd_5jOyR:-MXEF6__AncL-9GoOWyL:b-5555fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db3343f6ab85e59aaeff64fdf3c495d763a6d09/pkg/sql/sem/tree/stmt.go#L1662)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Don't we have a `//go:generate stringer -type=StatementType` for this type?
If we want our own, we should define the table right where we define the enum values, and we should key off of them:
```
var statementTypeStr = [...]string{
  typeDDL: "DDL",
  ...
}
```
</blockquote></details>

I was using this for testing and forgot to remove it. Thanks for the catch!

**Review by jordanlewis — COMMENTED** [review]
I think you need to `make bazel-generate` to fix the lint error

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-:-MXHiBrz6iUGQa6CyQ_I:b6trovm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @maryliag, and @RaduBerinde)

___
*[pkg/roachpb/app_stats.go, line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXHhRqd4wSePRvI7TaA:-MXHhRqd4wSePRvI7TaB:b-u3o32s) ([raw file](https://github.com/cockroachdb/cockroach/blob/11f1751d39c9bedbbc496b0760fc4dab6a696277/pkg/roachpb/app_stats.go#L128)):*
> ```Go
> 		s.MaxRetries = other.MaxRetries
> 	}
> 	s.SQLType = "DDL"
> ```

This doesn't seem quite right - I think the SQLType will have been set on both StatementStatistics objects, so we should take one or the other. We probably should compare them too, and if they're different, I'm not sure which we should take...

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/roachpb/app_stats.go, line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXHhRqd4wSePRvI7TaA:-MXXBYWf8HRLnOG4ErIX:b-wq7vmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/11f1751d39c9bedbbc496b0760fc4dab6a696277/pkg/roachpb/app_stats.go#L128)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This doesn't seem quite right - I think the SQLType will have been set on both StatementStatistics objects, so we should take one or the other. We probably should compare them too, and if they're different, I'm not sure which we should take...
</blockquote></details>

Since is grouping by fingerprint, the sqlType will be the same for statement or other.

**Review by jordanlewis — COMMENTED** [review]
Seems like you need to enable crlfmt in your editor! :) https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-:-MXXXwLu8mDZAOVBfm9q:b-t73ogr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @maryliag, and @RaduBerinde)

___
*[pkg/sql/sem/tree/stmt.go, line 88 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXXXbSP0iUqq0zqT4K0:-MXXXbSP0iUqq0zqT4K1:b-aroyez) ([raw file](https://github.com/cockroachdb/cockroach/blob/a70827cea644d31d1f1536877cb6b67ece0b1f34/pkg/sql/sem/tree/stmt.go#L88)):*
> ```Go
> 	NodeFormatter
> 
> 	StatementReturnType() StatementReturnType
> ```

Add a comment to this. Something like:

// StatementType identifies whether the statement is a DDL, DML, DCL, or TCL.

Might as well add one for `StatementReturnType` while you're here as well.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/sem/tree/stmt.go, line 88 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-MXXXbSP0iUqq0zqT4K0:-MXXcHdLDbOnRAdqsl__:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a70827cea644d31d1f1536877cb6b67ece0b1f34/pkg/sql/sem/tree/stmt.go#L88)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Add a comment to this. Something like:

// StatementType identifies whether the statement is a DDL, DML, DCL, or TCL.

Might as well add one for `StatementReturnType` while you're here as well.
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: assuming you got the lint issues!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-:-MXXdpaoBTgqFLBfo16n:bk4ezrm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Review by Azhng — COMMENTED** [review]
nit: seems like this PR has two commits, and second commit overwrites most of the changes in the first commit. Be sure to squash both commits before merging. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62989#-:-MXXiADA-pg3bc72bUPH:b-jazn3g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Comment by maryliag** [comment]
bors +

**Pull request merged**
