### PR TITLE
workload,randgen: make schema object names more deterministic

### LINKED ISSUE #117422: workload/schemachange: running workload with same seed generates different schema identifiers
Running the `schemachange` workload with the same seed (with `COCKROACH_RANDOM_SEED=x`) produces the same operations, but with different identifiers. For example, at the time of writing, these are the first two operations generated by running the following command two times:

```COCKROACH_RANDOM_SEED=9082679504586840611 ./bin/workload run schemachange --concurrency 2 --max-ops 10 --verbose 1```

Run 1:

```json
{
 "workerId": 1,
 "clientTimestamp": "20:42:05.993818",
 "ops": [
  "BEGIN",
  {
   "sql": "CREATE INDEX \"IrrelevantName\" ON public.table2 (\"IrrelevantColumn\" ASC)",
   "expectedExecErr": "42P01"
  }
 ],
 "expectedExecErrors": "42P01",
 "expectedCommitErrors": "",
 "message": "ROLLBACK; Successfully got expected execution error.: ERROR: relation \"public.table2\" does not exist (SQLSTATE 42P01)"
}
{
 "workerId": 0,
 "clientTimestamp": "20:42:05.993707",
 "ops": [
  "BEGIN",
  {
   "sql": "DROP TABLE public.table3",
   "expectedExecErr": "42P01"
  }
 ],
 "expectedExecErrors": "42P01",
 "expectedCommitErrors": "",
 "message": "ROLLBACK; Successfully got expected execution error.: ERROR: relation \"public.table3\" does not exist (SQLSTATE 42P01)"
}
```

Run 2:

```json
{
 "workerId": 1,
 "clientTimestamp": "20:42:13.542074",
 "ops": [
  "BEGIN",
  {
   "sql": "CREATE INDEX \"IrrelevantName\" ON public.table7 (\"IrrelevantColumn\" ASC)",
   "expectedExecErr": "42P01"
  }
 ],
 "expectedExecErrors": "42P01",
 "expectedCommitErrors": "",
 "message": "ROLLBACK; Successfully got expected execution error.: ERROR: relation \"public.table7\" does not exist (SQLSTATE 42P01)"
}
{
 "workerId": 0,
 "clientTimestamp": "20:42:13.542037",
 "ops": [
  "BEGIN",
  {
   "sql": "DROP TABLE public.table8",
   "expectedExecErr": "42P01"
  }
 ],
 "expectedExecErrors": "42P01",
 "expectedCommitErrors": "",
 "message": "ROLLBACK; Successfully got expected execution error.: ERROR: relation \"public.table8\" does not exist (SQLSTATE 42P01)"
}
```

There seems to be some other form of non determinism outside the seed passed that makes the identifiers different. Having `schemachange` generate the same identifiers has at least two big advantages:

* increases the chances of us being able to reproduce failures, especially in cases where the failure happens due  to interactions of several calls to the `schemachange` workload (for example, the failure observed in #117409).
* ease of debugging: it's a better debugging experience if we are able to run the test with the same seed and scan the output generated by the workload if the identifiers are identical. 

Jira issue: CRDB-35168

### PR DESCRIPTION
**Pull request by rafiss**
Now each worker of the schema change workload has its own sequence number. This makes it so the names that are generated are now deterministic for each worker, rather than depending on how the worker execution is interleaved.

fixes https://github.com/cockroachdb/cockroach/issues/117422
Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117585)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @herkolategan, @rafiss, and @renatolabs)

___
*[`pkg/util/randident/api.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117585#-Nno4KZ9Ej58pzsUoUIo:-Nno4KZ9Ej58pzsUoUIp:b9wm5u5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b49c2da6d714cb3a0d2c3968fd492563e356631/pkg/util/randident/api.go#L29)):*
> ```Go
> 	// The specified number is included in the name if Number is true
> 	// in the attached NameGeneratorConfig.
> 	GenerateOne(numberSuffix string) string
> ```

This arg can be `suffix` now that it can be any string and update the comment. The config fields `Number`, `numberSuffix`, and `numberReplace` can be renamed and have comments updated to make this all consistent.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117585)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @herkolategan, @mgartner, and @renatolabs)

___
*[`pkg/util/randident/api.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117585#-Nno4KZ9Ej58pzsUoUIo:-NnpRWV18GHIrXh2xfw4:b-kfhv1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b49c2da6d714cb3a0d2c3968fd492563e356631/pkg/util/randident/api.go#L29)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This arg can be `suffix` now that it can be any string and update the comment. The config fields `Number`, `numberSuffix`, and `numberReplace` can be renamed and have comments updated to make this all consistent.
</blockquote></details>

good point. fixed

**Comment by renatolabs** [comment]
Code LGTM!

I ran the command on #117422 on this branch. While single-worker (`--concurrency 1`) behaviour is identical now when the same seed is passed, I still see different behaviour when more than one worker is involved.

I suspect (haven't looked at schemachange code in detail) that this might be because workers introspect on database state to decide the operation being performed. Do we know if that's the case? Or if that's not it, where is the non-determinism is coming from?

**Comment by rafiss** [comment]
> I suspect (haven't looked at schemachange code in detail) that this might be because workers introspect on database state to decide the operation being performed. Do we know if that's the case?

Yes, that is the case. One example is here: https://github.com/cockroachdb/cockroach/blob/6bf526e1fd1b5ee02308d3975cc55edddb1dd6ec/pkg/workload/schemachange/operation_generator.go#L3575-L3574

When the workload needs a table name, it will either generate a new one, or look up an existing one. And when it needs to look up an existing one, it will pick randomly: https://github.com/cockroachdb/cockroach/blob/6bf526e1fd1b5ee02308d3975cc55edddb1dd6ec/pkg/workload/schemachange/operation_generator.go#L3588-L3592

I'm not sure if there's a way to propagate the deterministic randomization into the SQL query.

**Review by renatolabs — APPROVED** [review]
Even if there's still the possibility of non-determinism, I think this is a great improvement!

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117585#-:-Np0_0DM5DnRIV_h1m0h:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @herkolategan)

**Comment by rafiss** [comment]
TFTRs! if anyone thinks of a way to make the SQL queries deterministic as well, we can make that change later

bors r+

**Pull request merged**
