### PR TITLE
distsql: implement MERGE JOIN (inner, left outer, right outer, full outer)

### PR DESCRIPTION
**Pull request by irfansharif**
Adds the implementation for a merge join processor, extending
MergeJoinerSpec. We chunk up the input row streams into co-groups 
(sets of rows with the same group key comprised of the set of ordered 
columns) and emit the cross-product of matching co-groups from 
each stream in successive batches.

Part of #7587, extension to #10054.

cc @RaduBerinde

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10346)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for working on this!

---

Review status: 0 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/mergejoiner.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUqeQdWpwotHm0sEaL:-KVUqeQdWpwotHm0sEaM:bttr84w) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/mergejoiner.go#L88)):*
> ```Go
> 	}
> 
> 	err = m.filter.init(spec.Expr, append(spec.LeftTypes, spec.RightTypes...), flowCtx.evalCtx)
> ```

Can't we init this filter the first time we're using it in render? There we already have the types and we wouldn't need to put LeftTypes,RightTypes in the spec.

---

*[pkg/sql/distsql/stream_merger.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUrQad-kRHPD2-rsQw:-KVUrQad-kRHPD2-rsQx:bx0oe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L28)):*
> ```Go
> // stream is a thin wrapper around an ordered RowSource buffering in the most
> // recently received rows.
> type stream struct {
> ```

stream is a very generic name, this should have a more particular name. eg streamCacher

---

*[pkg/sql/distsql/stream_merger.go, line 78 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUxybPmXssrZCz_n6e:-KVUxybPmXssrZCz_n6f:b-oseb2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L78)):*
> ```Go
> 	right        stream
> 	datumAlloc   sqlbase.DatumAlloc
> 	outputBuffer []sqlbase.EncDatumRows
> ```

this is a pretty bad structure because of the overhead of one slice for each pair of rows. `[][2]EncDatumRow` would be better (or `[]rowPair` where `rowPair` is a struct with two rows).

---

*[pkg/sql/distsql/stream_merger.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUsR6An8cKJ3pgfLKg:-KVUsR6An8cKJ3pgfLKh:buo07hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L94)):*
> ```Go
> // computeBatch adds the cross-product of the next matching set of co-groups
> // from each of streams to the output buffer.
> func (sm *streamMerger) computeBatch() error {
> ```

It would be better if this just returns two slices of rows and the higher level does the cross-product (or whatever it needs to do). First, it would allow the filtering and rendering to happen directly, without accumulating the cross-product in a buffer. Second, it would leave the inner/outer distinction up to the caller - otherwise, this code will become a lot more complex when we implement outer joins.

---

*[pkg/sql/distsql/stream_merger.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUu3fGm-pqw2zezzPF:-KVUu3fGm-pqw2zezzPG:b4tguun) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L95)):*
> ```Go
> // from each of streams to the output buffer.
> func (sm *streamMerger) computeBatch() error {
> 	lrow := sm.left.rows[0]
> ```

I feel that we're making this more complicated than it needs to be.

Instead of the `stream` stuff, we could simply implement a function that reads a set of rows as long as they are all "equal".

```
func getRowGroup(currRow, receiver) (currRow, []rows) {
  init slice to currRow
  for {
    currRow = receiver next row
    if currRow == nil || currRow not "equal" to slice[0] {
      return currRow, slice
    }
    append currRow to slice
   }
}
```

Then NextBatch (with the interface I suggested above) can be roughly:
```
if lrow == nil && rrow == nil { we are done }

cmp := compare rows (with "nil" meaning "larger")
if cmp <= 0 {
  lrow, leftSlice = getRowGroup(lrow, leftReceiver)
}
if cmp >= 0 {
  rrow, rightSlice = getRowGroup(rrow, rightReceiver)
}
return leftSlice, rightSlice
```

---

*[pkg/sql/distsql/stream_merger.go, line 165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUsGw9qHdUOrVmNxat:-KVUsGw9qHdUOrVmNxau:b-8wc9mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L165)):*
> ```Go
> 			// We've finished with the co-groups above, for each stream we
> 			// discard all the rows save the row from the next co-group.
> 			sm.left.rows = sm.left.rows[len(sm.left.rows)-1:]
> ```

If we want `stream` to be a separate type, it would be preferable to do this through an API. Accessing the last group above should also be done through a method instead of accessing `sm.left.rows` directlyadva

---

*[pkg/sql/distsql/stream_merger.go, line 174 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUvgqWGFRBsgvEchqN:-KVUrroSLeyuSbyEdL8E:b-mi7g84) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L174)):*
> ```Go
> }
> 
> func (sm *streamMerger) compare(lhs, rhs sqlbase.EncDatumRow) (int, error) {
> ```

it would make the higher code easier (less nil checks) if this accepts at most one side to be `nil`, and treats the non-nil side as smaller

---

*[pkg/sql/distsql/stream_merger.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUrp5YIDz9sy69ML8-:-KVUrp5YIDz9sy69ML80:b-xhm551) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L178)):*
> ```Go
> 		return 0, errors.New("empty row")
> 	}
> 	for i := 0; i < len(sm.left.ordering); i++ {
> ```

`range sm.left.ordering`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-:-KVUzC-yKtxYLY4Wo2yr:b-4v1jpi)*

**Comment by irfansharif** [comment]
Review status: 0 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/mergejoiner.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUqeQdWpwotHm0sEaL:-KVVFcRAQ-L4ksiKa9Dl:b-6x1tn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/mergejoiner.go#L88)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Can't we init this filter the first time we're using it in render? There we already have the types and we wouldn't need to put LeftTypes,RightTypes in the spec.
</details>
adding in my changes for outer join support to this same PR, will get back to this after discussions resolved there because depending on how `render` is used according to how I first thought about it you could very well have `nil` `lhs/rhs` rows the first time it's called.

---

*[pkg/sql/distsql/stream_merger.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUrQad-kRHPD2-rsQw:-KVVGsMM1v3rrHRVgKRR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L28)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> stream is a very generic name, this should have a more particular name. eg streamCacher
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 78 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUxybPmXssrZCz_n6e:-KVVGoa_tuFF7tZPHTeT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> this is a pretty bad structure because of the overhead of one slice for each pair of rows. `[][2]EncDatumRow` would be better (or `[]rowPair` where `rowPair` is a struct with two rows).
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUsR6An8cKJ3pgfLKg:-KVWDM8T57Wwy4FXeaQH:b2xlnzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L94)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It would be better if this just returns two slices of rows and the higher level does the cross-product (or whatever it needs to do). First, it would allow the filtering and rendering to happen directly, without accumulating the cross-product in a buffer. Second, it would leave the inner/outer distinction up to the caller - otherwise, this code will become a lot more complex when we implement outer joins.
</details>
Not doing this in my most recent revision with the cross-product taking place down in the `streamMerger`, I found it simpler to implement. Needs more review.

---

*[pkg/sql/distsql/stream_merger.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUu3fGm-pqw2zezzPF:-KVWD64i7cvsLc8GqGSF:b-sf6pxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L95)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I feel that we're making this more complicated than it needs to be.
> 
> Instead of the `stream` stuff, we could simply implement a function that reads a set of rows as long as they are all "equal".
> 
> ```
> func getRowGroup(currRow, receiver) (currRow, []rows) {
>   init slice to currRow
>   for {
>     currRow = receiver next row
>     if currRow == nil || currRow not "equal" to slice[0] {
>       return currRow, slice
>     }
>     append currRow to slice
>    }
> }
> ```
> 
> Then NextBatch (with the interface I suggested above) can be roughly:
> ```
> if lrow == nil && rrow == nil { we are done }
> 
> cmp := compare rows (with "nil" meaning "larger")
> if cmp <= 0 {
>   lrow, leftSlice = getRowGroup(lrow, leftReceiver)
> }
> if cmp >= 0 {
>   rrow, rightSlice = getRowGroup(rrow, rightReceiver)
> }
> return leftSlice, rightSlice
> ```
</details>
Added `FULL OUTER`, `LEFT OUTER` and `RIGHT OUTER` and restructured things a bit similar to what's here. Needs more review.

---

*[pkg/sql/distsql/stream_merger.go, line 165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUsGw9qHdUOrVmNxat:-KVVSDULSTAH4n3i3x2x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> If we want `stream` to be a separate type, it would be preferable to do this through an API. Accessing the last group above should also be done through a method instead of accessing `sm.left.rows` directlyadva
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 174 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUvgqWGFRBsgvEchqN:-KVVTMGggUG-R_6bBvTa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L174)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> it would make the higher code easier (less nil checks) if this accepts at most one side to be `nil`, and treats the non-nil side as smaller
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUrp5YIDz9sy69ML8-:-KVVGrJytbEAyKblRF6g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/stream_merger.go#L178)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> `range sm.left.ordering`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql/mergejoiner.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUqeQdWpwotHm0sEaL:-KVWHrcaQkv9eWHE_Av6:bt8v395) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/mergejoiner.go#L88)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> adding in my changes for outer join support to this same PR, will get back to this after discussions resolved there because depending on how `render` is used according to how I first thought about it you could very well have `nil` `lhs/rhs` rows the first time it's called.
</details>
Interesting, I see, if there are no rows on one side and we're doing a full outer, we would need to know the types of those `NULL`s that we fill in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346)*

**Comment by irfansharif** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/mergejoiner.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVUqeQdWpwotHm0sEaL:-KVWKW-J_RAt5z1F1PBT:b-r43zgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a09ab7aebc05c2a6cb0125ca5fde045527fd1c/pkg/sql/distsql/mergejoiner.go#L88)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Interesting, I see, if there are no rows on one side and we're doing a full outer, we would need to know the types of those `NULL`s that we fill in.
</details>
Should've clarified that better but yes, exactly. messy for any case where the first `lhs/rhs` pair has atleast one nil row but you still need to evaluate the filter (should fail if any constraints on a nil column).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346)*

**Comment by RaduBerinde** [comment]
Looking great!

There is one more annoying complication with outer joins. Feel free to file an issue to address this later though.

Consider this example:

```sql
CREATE TABLE U (K INT, A INT, B INT);
CREATE TABLE V (K INT, C INT, D INT);

INSERT INTO U VALUES (1, 2, 2);
INSERT INTO V VALUES (1, 3, 3);

SELECT * FROM U FULL OUTER JOIN V ON U.K=V.K AND U.A>V.C;
```

In our case the streams will be ordered by `K`, but the rest of the expression (` U.A>V.C`) will have to be evaluated (like the filter). With inner joins, there is no difference between an `ON` condition and ` WHERE` condition, but with outer joins there is. The example above results in:
```
 k | a | b | k | c | d 
---+---+---+---+---+---
 1 | 2 | 2 |   |   |  
   |   |   | 1 | 3 | 3
```

With the condition moved to `WHERE` (`SELECT * FROM U FULL OUTER JOIN V ON U.K=V.K WHERE U.A > V.C;`) we get no results.

I believe that in general this means we will need both an `ON` expression and a `WHERE` expression in the spec (but we should disallow setting both if the join is inner).

---

Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/mergejoiner.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWwjAhvtOO18Jfq4n3:-KVWwjAiPFkD6PagJEvX:b-dha09t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/mergejoiner.go#L145)):*
> ```Go
> // render evaluates the provided filter and constructs a row with columns from
> // both rows as specified by the provided output columns.
> func (m *mergeJoiner) render(left, right sqlbase.EncDatumRow) (sqlbase.EncDatumRow, error) {
> ```

explain here that we expect left or right to be nil if there was no "join" match

---

*[pkg/sql/distsql/stream_merger.go, line 29 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWvqPA13oKwVtGSRGN:-KVWvqPA13oKwVtGSRGO:b-hs2q1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L29)):*
> ```Go
> // recently received rows.
> type streamCacher struct {
> 	noCopy util.NoCopy
> ```

I don't think there is any issue with copying these structures (even if that's not the intended  use). We shouldn't include noCopy if copying doesn't break anything

---

*[pkg/sql/distsql/stream_merger.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWs04TUna1kWM8VWjD:-KVWs04Uln9OXqZ-aSP6:by92iqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L52)):*
> ```Go
> }
> 
> // we ignore the last row of the row buffer because this is either a nil row
> ```

[nit]  this comment belongs inside the function

---

*[pkg/sql/distsql/stream_merger.go, line 63 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWtWWf1XNl91pWb-Dm:-KVWtWWf1XNl91pWb-Dn:b-o87xic) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L63)):*
> ```Go
> // next group.
> func (s *streamCacher) advanceGroup() sqlbase.EncDatumRow {
> 	s.rows = s.rows[len(s.rows)-1:]
> ```

it would be better if we did `s.rows[0] = s.rows[len(s.rows)-1]; s.rows = s.rows[:1]`; otherwise we will keep having to reallocate the slice (it keeps "advancing")

---

*[pkg/sql/distsql/stream_merger.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWs9LhJyJKIBmSEOzt:-KVWs9LhJyJKIBmSEOzu:bg70oyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L73)):*
> ```Go
> 	for {
> 		next, err := s.nextRow()
> 		if err != nil {
> ```

[nit] these two ifs can just be `if err != nil || next == nil { return err }` (this check is pretty common in distsql code)

---

*[pkg/sql/distsql/stream_merger.go, line 125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWumk5MCE-qSMFpNLv:-KVWumk5MCE-qSMFpNLw:b-novfrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L125)):*
> ```Go
> 	}
> 
> 	if cmp == -1 {
> ```

use < 0, > 0 (or check and panic if cmp is not 0,1,or-1); otherwise it will be hard to track this down if some compare function changes

---

*[pkg/sql/distsql/stream_merger.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWu1SIuNaCCHEVeQ4v:-KVWu1SIuNaCCHEVeQ4w:bvjze3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L168)):*
> ```Go
> func (sm *streamMerger) compare(lhs, rhs sqlbase.EncDatumRow) (int, error) {
> 	if lhs == nil && rhs == nil {
> 		// return 0, errors.New("comparing two nil rows")
> ```

[nit] remove this (I'd keep the panic)

---

*[pkg/sql/distsql/stream_merger.go, line 203 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWvU6hvix1XGnCDTDR:-KVWvU6hvix1XGnCDTDS:b-y8bdq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L203)):*
> ```Go
> 		sm.initialized = true
> 	}
> 	sm.outputBuffer = sm.outputBuffer[:0]
> ```

the `computeBatch` code would be a bit clearer if this was in there

---

*[pkg/sql/distsql/stream_merger.go, line 210 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWw0uUKqf6mUjsLJMb:-KVWw0uUKqf6mUjsLJMc:biuualf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L210)):*
> ```Go
> }
> 
> func makeStreamMerger(
> ```

The structure is fairly small, this could return a `streamMerger` and avoid the allocation. Probably not important though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-:-KVWzJiVSQhYU-GrkQCf:bbz76qr)*

**Comment by irfansharif** [comment]
Filed #10394, thanks for the review! 

---

Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/distsql/mergejoiner.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWwjAhvtOO18Jfq4n3:-KV_XCSUngcbll-ELLM5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/mergejoiner.go#L145)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> explain here that we expect left or right to be nil if there was no "join" match
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 29 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWvqPA13oKwVtGSRGN:-KV_YW4eMXbapEd5sLkP:b5efaez) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I don't think there is any issue with copying these structures (even if that's not the intended  use). We shouldn't include noCopy if copying doesn't break anything
</details>
There was an issue copying over `streamCacher` due to the internal `rows []sqlbase.EncDatumRow` and came up before when I multiple `streamCacher`'s and running `range` over them, given now it is an explicit `left` and `right` this doesn't come up but I'll remove it anyway.

---

*[pkg/sql/distsql/stream_merger.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWs04TUna1kWM8VWjD:-KV_ZGW7Ak5BBpnX8OUa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L52)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit]  this comment belongs inside the function
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 63 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWtWWf1XNl91pWb-Dm:-KV__ufaYukhHboQZtc0:br93ce7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L63)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> it would be better if we did `s.rows[0] = s.rows[len(s.rows)-1]; s.rows = s.rows[:1]`; otherwise we will keep having to reallocate the slice (it keeps "advancing")
</details>
cool! Done.

---

*[pkg/sql/distsql/stream_merger.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWs9LhJyJKIBmSEOzt:-KV_a1PYpm-TZmXXx_i-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] these two ifs can just be `if err != nil || next == nil { return err }` (this check is pretty common in distsql code)
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWumk5MCE-qSMFpNLv:-KV_csRX2hvJuSfDBLsj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L125)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> use < 0, > 0 (or check and panic if cmp is not 0,1,or-1); otherwise it will be hard to track this down if some compare function changes
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWu1SIuNaCCHEVeQ4v:-KV_b0dpvtWYq--BSwdt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L168)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] remove this (I'd keep the panic)
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 203 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWvU6hvix1XGnCDTDR:-KV_bFli0_5b0OGlvjnj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L203)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> the `computeBatch` code would be a bit clearer if this was in there
</details>
Done.

---

*[pkg/sql/distsql/stream_merger.go, line 210 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVWw0uUKqf6mUjsLJMb:-KV_dnWarAQ64qRPJuZq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3acacdec811deaa1b301f72e7424cc5ae91974/pkg/sql/distsql/stream_merger.go#L210)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The structure is fairly small, this could return a `streamMerger` and avoid the allocation. Probably not important though
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-:-KV_ceK6eqi3BcOv4LGx:bwokk3b)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsql/mergejoiner.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVaGdL05sWnGX3gkgaj:-KVaGdL1SiJ0fMY_YMEX:b-oz5qhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e36b649e68a429d013be010ae92627dc004818e/pkg/sql/distsql/mergejoiner.go#L145)):*
> ```Go
> // render evaluates the provided filter and constructs a row with columns from
> // both rows as specified by the provided output columns. We expect left or
> // right to be nil of there was no explicit "join" match, the filter is then
> ```

s/of/if/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-:-KVaGr6f2eo2LSMnVvYM:bnfp4nl)*

**Comment by irfansharif** [comment]
pulling it in now.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql/mergejoiner.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-KVaGdL05sWnGX3gkgaj:-KVaIfwB1oC98SA91x6x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e36b649e68a429d013be010ae92627dc004818e/pkg/sql/distsql/mergejoiner.go#L145)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> s/of/if/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10346#-:-KVaInH_tJSmX5VFf6KO:b-uwk8sa)*

**Pull request merged**
