### PR TITLE
acceptance+cloud: fix Terraform 0.7.0+ breakage

### PR DESCRIPTION
**Pull request by cuongdo**
**terrafarm: always quote Terraform values**
When setting Terraform variables, Farmer was only quoting the values of
two variables.  Now, we quote all values. This resolves the issue where
passed in TESTFLAGS (e.g. `-tf.cockroach-binary`) were being silently
ignored when passed into Terraform because of some unexpected behavior
when using implicitly typed Terraform values with Terraform functions
such as `coalesce`.

For example, when specifying `-tf.cockroach-binary`, Farmer passes
`-var=cockroach_binary=foo` to Terraform. `main.tf` does this to figure
out which `cockroach` binary to copy to the new nodes:

```
coalesce(cockroach_binary, ...)
```

`coalesce` is supposed to return the first non-empty string passed to
it. When `cockroach_binary` is an unquoted string, `coalesce` is
silently ignores the non-empty value for `cockroach_binary`.

**acceptance/terraform+cloud: fix cluster join**
6f59f86 fixed some Terraform warnings but broke the process of new
nodes joining the cluster. It was creating `supervisor.conf` files with
empty `--join` parameters for `cockroach`.

Changing the `template_file` Terraform `resource` to `data` seems to
have the side effect of not implicitly generating the `count` variable.
So, `template_file.join_address` was being set to "", which causes all
created nodes to start a new cluster.

Future Free Friday project: see if there's a viable subset of Terraform to
reimplement for our tests

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9232)

### CODE REVIEW

**Comment by cuongdo** [comment]
Note that this fixes #9228 (Terraform-based nightly tests breaking) -- forgot to paste that part in from commit message

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9232#-:-KREU4eaKGqvc3wEZtLy:bnfp4nl)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9232#-:-KREX1FRwjDFWtVsgy6O:bnfp4nl)*

**Comment by vivekmenezes** [comment]
thanks for fixing this!

**Pull request merged**
