### PR TITLE
Set LastUpdateNanos to a max value in Add and Subtract

### PR DESCRIPTION
**Pull request by kkaneda**
Don't fully understand the semantics, but it seems better than
calculating LastUpdateNanos from {New,Removed}RangeEvent. For example, without this change, we set `SplitRangeEvent.Delta.LastUpdateNanos` to `-1 * SplitRangeEvent.New.LastUpdateNanos`.

### CODE REVIEW

**Comment by tschottdorf** [comment]
it's possible that `Subtract` and `Add` should change. Why would it subtract timestamps? I would imagine that the right thing to do in either case would be to use the larger of the two timestamps involved (since for incremental updates on the right hand side, there's often a zero). The current code is definitely botched: LastUpdateNanos should never decrease, let alone be negative.

**Comment by kkaneda** [comment]
Thanks for the review, @tschottdorf . Yes, made the change and it looks better. I've modified `rangeStats. MergeMVCCStats` and expected values of `monitor_test.go` and `recorder_test.go`.

**Comment by mrtracy** [comment]
This change LGTM.

Looking to further improvements, the confusing bit here is that the logic for accumulating an incremental updates may be different than the logic for simply summing two MVCCStats (for example, these timestamps or especially the intent age field). I think the most correct model would be to create an entirely different structure for incremental update data, even if it is as simple as `type MVCCDiff MVCCStats`.

Then the (immutable) method signatures for MVCCStats would be:
```
type MVCCStatsInterface interface {
  // Accumulate from an incremental update.
  Accumulate(diff MVCCDiff) MVCCStats
  // Add values of two MVCCStats together.
  Add(other MVCCStats) MVCCStats
  // Subtract the values of another MVCCStat.
  Subtract(other MVCCStats) MVCCStat.
}
```

**Comment by tamird** [comment]
I don't follow, why does this complicate incremental updates? It looks like it just picks the greater of the two timestamps, which is exactly what I'd expect. Anyway, this LGTM and any follow up discussion should live in a new issue.

**Comment by kkaneda** [comment]
Sure, filed #1724.

**Pull request merged**
