### PR TITLE
sql: implement `ALTER SCHEMA RENAME TO`

### LINKED ISSUE #50880: sql: add support for the `ALTER SCHEMA RENAME TO` command
This command renames a schema.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50880.

This commit implements the `ALTER SCHEMA RENAME TO` command. It reuses
the existing schema change infrastructure to handle a more general case
of an arbitrary descriptor that just needs names and existing leases
drained.

Release note (sql change): Implement the `ALTER SCHEMA RENAME TO`
command.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 12 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @lucy-zhang, and @rohany)

___
*[pkg/jobs/jobspb/jobs.proto, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOwDVi1exPwJH2WZrN:-MEOwDVjDmt9El5P0kCq:b-9g7v2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/jobs/jobspb/jobs.proto#L295)):*
> ```protobuf
>   // simple schema changes on SchemaDescriptors and DatabaseDescriptors without
>   // implementing a new job for each.
>   uint32 desc_id = 5 [(gogoproto.customname) = "DescID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
> ```

Would it be crazy to add an enum indicating the type?
___
*[pkg/sql/alter_schema.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOwaW4ApQJvdCJqrms:-MEOwaW4ApQJvdCJqrmt:bxa7ass) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/sql/alter_schema.go#L27)):*
> ```Go
> type alterSchemaNode struct {
> 	n    *tree.AlterSchema
> 	db   *sqlbase.ImmutableDatabaseDescriptor
> ```

We should also just get a mutable database descriptor here. 
___
*[pkg/sql/alter_schema.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOwiFnAJnkopKqlbZf:-MEOwiFnAJnkopKqlbZg:b-sqnll) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/sql/alter_schema.go#L110)):*
> ```Go
> 	// Update the schema mapping in the parent database.
> 	mutDB := sqlbase.NewMutableExistingDatabaseDescriptor(*db.DatabaseDesc())
> 	// Mark the old schema name as dropped.
> ```

nit: confirm there's no entry for the new name and that there is an entry for the old name. 
___
*[pkg/sql/schema.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOx1rz5lX4e6r2bjap:-MEOx1rz5lX4e6r2bjaq:b-q99p8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/sql/schema.go#L31)):*
> ```Go
> )
> 
> func isSchemaNameValid(name string) error {
> ```

nit: put this in sqlbase in `schema_desc`. 
___
*[pkg/sql/schema_changer.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOxHCu1uuVCPQQxxy8:-MEOxHCu1uuVCPQQxxy9:b-p43fnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/sql/schema_changer.go#L453)):*
> ```Go
> 	}
> 
> 	// If this descriptor is a table, then check that we are the first in line
> ```

nit: move this back to a helper function that returns early if it's not a table. 
___
*[pkg/sql/schema_changer.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOxUy72yPgFPV-s8_6:-MEOxUy72yPgFPV-s8_7:byqdgqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/sql/schema_changer.go#L516)):*
> ```Go
> 	// If the target descriptor is a table, then handle table specific schema
> 	// change steps before the backfill.
> 	if tableDesc, ok := desc.(*sqlbase.ImmutableTableDescriptor); ok {
> ```

nit: invert this condition to front-load the early return.

**Review by thoszhang — COMMENTED** [review]
I'll do a real review sometime later today. Sorry the database descriptor fetching is still annoying. I'm hoping to have #52553 merged soon.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-:-MEP4PLK5p_xn0-DDrPB:b-76g7vn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @lucy-zhang, and @rohany)

___
*[pkg/jobs/jobspb/jobs.proto, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOwDVi1exPwJH2WZrN:-MEP3eqRA-7W2Sbflca-:bb5afa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/jobs/jobspb/jobs.proto#L295)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Would it be crazy to add an enum indicating the type?
</blockquote></details>

What if we just added a separate schema ID field? For what it's worth, I was planning to reappropriate `dropped_database_id` as the ID for databases undergoing schema changes in general.

Roughly speaking, I'm envisioning that `[dropped_]database_id`, `schema_id`, and `table_id` are populated when there's a "top-level" schema change for the respective descriptor type. Probably also `dropped_schemas` once schemas are also dropped in the 2-phase process. But I'm not sure what the best way is to cram everything into the schema changer.

**Comment by rohany** [comment]
> What if we just added a separate schema ID field? For what it's worth, I was planning to reappropriate dropped_database_id as the ID for databases undergoing schema changes in general.

I'm not a fan of this -- it's adding more fields that are already conditionally set. I'm also not sure how much worth there is in adding an enum since this information is present in the retrieved descriptor anyway.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/sql/alter_schema.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEOwaW4ApQJvdCJqrms:-MEP6fbhCtnihZCoYK9X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d8a764dca7d97ce478cebce2131b48b13c5d4ce/pkg/sql/alter_schema.go#L27)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We should also just get a mutable database descriptor here. 
</blockquote></details>

Done.

**Comment by lucy-zhang** [comment]
> I'm not a fan of this -- it's adding more fields that are already conditionally set. I'm also not sure how much worth there is in adding an enum since this information is present in the retrieved descriptor anyway.

That's fair. I don't have a strong preference here. If we end up going with this, I might rework my PR slightly to switch over to using `desc_id` for databases.

**Review by thoszhang — APPROVED** [review]
> Reviewed 2 of 17 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @rohany)

___
*[pkg/jobs/jobspb/jobs.proto, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEWJCrGEZ14loimB7A0:-MEWJCrGEZ14loimB7A1:b-ys21sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc2776d11181a8901c91dd0926985094b984458/pkg/jobs/jobspb/jobs.proto#L307)):*
> ```protobuf
>   // mutation_id is the mutation ID that the schema changer is to process. It is
>   // only set when desc_id references a TableDescriptor.
>   uint32 mutation_id = 6 [(gogoproto.customname) = "MutationID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.MutationID"];
> ```

Can this now become `table_mutation_id`?
___
*[pkg/sql/alter_schema.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEWJk_CE8svUMc-nBXe:-MEWJk_CE8svUMc-nBXf:b-lfxdz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc2776d11181a8901c91dd0926985094b984458/pkg/sql/alter_schema.go#L117)):*
> ```Go
> 	if !oldPresent {
> 		return errors.Newf(
> 			"programming error: old name %q not present in database schema mapping",
> ```

Should these be assertion errors?
___
*[pkg/sql/alter_schema.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEWJqMS1v8p_sNZV4Kk:-MEWJqMS1v8p_sNZV4Kl:bjhjcup) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc2776d11181a8901c91dd0926985094b984458/pkg/sql/alter_schema.go#L134)):*
> ```Go
> 	}
> 	// Create an entry for the new schema name.
> 	db.Schemas[newName] = descpb.DatabaseDescriptor_SchemaInfo{
> ```

I feel like these operations are conceptually part of updating the namespace entry. Maybe there should be a function that handles both. It's not that important, though.
___
*[pkg/sql/schema_changer.go, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEWM_Ww6j8Xr6BRLBW-:-MEWM_Ww6j8Xr6BRLBW0:byjvvqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc2776d11181a8901c91dd0926985094b984458/pkg/sql/schema_changer.go#L463)):*
> ```Go
> 	// Retrieve the descriptor that is being changed.
> 	var desc catalog.Descriptor
> 	if err := sc.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> ```

I think reading the descriptor (and maybe even draining names?) is going to have to move out of `exec()` soon, or else it'll be tricky to deal with the current situation where jobs for database jobs call `exec()` on each child table/type to drop them. But that doesn't have to be now.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @lucy-zhang, and @rohany)

___
*[pkg/jobs/jobspb/jobs.proto, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEWJCrGEZ14loimB7A0:-MEYGcVF-AWSpmngBWUx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc2776d11181a8901c91dd0926985094b984458/pkg/jobs/jobspb/jobs.proto#L307)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can this now become `table_mutation_id`?
</blockquote></details>

Done.
___
*[pkg/sql/alter_schema.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEWJk_CE8svUMc-nBXe:-MEYGdEC1eMw5A08aCX_:b-jyjrht) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc2776d11181a8901c91dd0926985094b984458/pkg/sql/alter_schema.go#L117)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Should these be assertion errors?
</blockquote></details>

done, woops.
___
*[pkg/sql/alter_schema.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEWJqMS1v8p_sNZV4Kk:-MEYGeWp6ntk_ePewTcX:b-q1cfsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc2776d11181a8901c91dd0926985094b984458/pkg/sql/alter_schema.go#L134)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I feel like these operations are conceptually part of updating the namespace entry. Maybe there should be a function that handles both. It's not that important, though.
</blockquote></details>

I'll see if we need to reuse something like this again before doing so. What i've found so far is that these draining names cases are all slightly different, which makes it hard to wrap it nicely in a function.

**Review by thoszhang — APPROVED** [review]
> Reviewed 2 of 17 files at r1, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @lucy-zhang, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/schema, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEcE65P1bjYWi4b0_oA:-MEcE65Q1efxkoL7H8YZ:bnv7a81) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd00154a3d8292b4fffde7f435ad27a75f2302c5/pkg/sql/logictest/testdata/logic_test/schema#L138)):*
> ```
> # to make another schema with the old name.
> statement ok
> CREATE SCHEMA myschema
> ```

Should we also have some tests for renaming schemas in a transaction?

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-:-MEcRRN6DtDaVSX-LWWJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/schema, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52349#-MEcRJ5q6OkEkm0JKq70:-MEcRJ5rC_BSslk9_SWo:belh7mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c644dc05024e8029c6591c630b409a12af5d68e3/pkg/sql/logictest/testdata/logic_test/schema#L156)):*
> ```
> statement ok
> ROLLBACK
> ```

any interest in adding some tests related to permissions and ownership?

**Comment by rohany** [comment]
> any interest in adding some tests related to permissions and ownership?

Those aren't quite ready yet. @RichardJCai is going to add that stuff (i think he's working on it right now)

**Pull request merged**
