### PR TITLE
roachtest: enable schema changes in acceptance/version-upgrade

### LINKED ISSUE #58489: roachtest: schemaChangeStep is skipped in acceptance/version-upgrade
[(roachtest).acceptance/version-upgrade failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2561359&tab=buildLog) on [master@cee475331ca3629b503cd2e7c7919b72c98a5ca5](https://github.com/cockroachdb/cockroach/commits/cee475331ca3629b503cd2e7c7919b72c98a5ca5):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/version-upgrade/run_1
	versionupgrade.go:258,versionupgrade.go:114,versionupgrade.go:189,versionupgrade.go:177,acceptance.go:69,acceptance.go:110,test_runner.go:760: write tcp 172.17.0.3:52698->35.192.202.190:26257: write: broken pipe

	cluster.go:1637,context.go:140,cluster.go:1626,test_runner.go:841: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2561359-1609916496-07-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 5485
		4: 5484
		2: 5508
		1: dead
		Error: UNCLASSIFIED_PROBLEM: 1: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1850
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 1: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/acceptance/version-upgrade](https://teamcity.cockroachdb.com/viewLog.html?buildId=2561359&tab=artifacts#/acceptance/version-upgrade)
Related:
- #58329 roachtest: acceptance/version-upgrade failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-note-script-update](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-note-script-update) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #58307 roachtest: acceptance/version-upgrade failed  [A-schema-descriptors](https://api.github.com/repos/cockroachdb/cockroach/labels/A-schema-descriptors) [C-bug](https://api.github.com/repos/cockroachdb/cockroach/labels/C-bug) [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [branch-release-20.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.2)

- #58139 roachtest: acceptance/version-upgrade failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1)

- #53812 roachtest: acceptance/version-upgrade failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aacceptance%2Fversion-upgrade.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

Jira issue: CRDB-3386

### PR DESCRIPTION
**Pull request by fqazi**
Previously, due to flakes we disabled schema changes inside the version update test. This patch re-enables them, since we are confident that the workload itslef is now stable in a mixed version state.

Fixes: #58489
Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]

**Review by renatolabs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @herkolategan)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk1Xgb9t3YXg-Ezcto:-NQk1Xgc2dcqAd1PezSM:b-dsgwmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L480)):*
> ```Go
> 
> // Run performs `cluster.RunE` on a randomly picked node.
> func (h *Helper) Run(rng *rand.Rand, cmd ...string) error {
> ```

I'm not convinced this function needs to be part of `*Helper` (I'd like to only add functions to this struct once there are many call sites that would benefit from it). I know we have `Query` related functions here already, but one distinction is that when we need to run SQL in a test, we will always connect to one gateway node; for running commands, it's very common that commands will need to run on multiple  nodes at the same time, and it's not great to have behavior/logging be different if we are running a command in one vs many nodes.

In the mixed-version closure, you can achieve the same behavior with


```go
node := h.RandomNode(rng, c.All())
c.RunE(...)
```
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 487 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk2rAQ3BF4Izi9VD7T:-NQk2rAQ3BF4Izi9VD7U:b-iohb0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L487)):*
> ```Go
> 
> // InitLegacyWorkload initializes a legacy workload on all nodes.
> func (h *Helper) InitLegacyWorkload(workloadPath string, workload string) {
> ```

I also believe this function is doing something too specific to warrant a function in `*Helper`. In addition, it sounds like a function that the caller would always need to make sure to call just once. This is not quite the type of function that should live here. I'll make a comment down below.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk34fr8utJ0AZa41MU:-NQk34fr8utJ0AZa41MV:b-kynyad) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L490)):*
> ```Go
> 	// Stage workload on all nodes as the load node to run workload is chosen
> 	// randomly.
> 	h.runner.cluster.Put(h.ctx, workloadPath, "./workload", h.runner.crdbNodes)
> ```

What's the reason we need to use `./workload` instead of `./cockroach workload`?
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk3AAs5B3o2z7Wp6IM:-NQk3AAs5B3o2z7Wp6IN:b9mzq9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/tests/versionupgrade.go#L134)):*
> ```Go
> 		func(ctx context.Context, l *logger.Logger, rng *rand.Rand, h *mixedversion.Helper) error {
> 			initWorkload.Do(func() {
> 				h.InitLegacyWorkload(t.DeprecatedWorkload(), "schemachange")
> ```

Instead of using the `sync.Once`, I think it makes more sense to call `mvt.OnStartup` and init the workload there.
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk3T36DJseDJlkFWBU:-NQk3T36DJseDJlkFWBV:b-pwbbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/tests/versionupgrade.go#L142)):*
> ```Go
> 				fmt.Sprintf("--concurrency %d", 2),
> 				fmt.Sprintf("{pgurl:1-%d}", len(c.All())),
> 			}
> ```

Nit: consider using `commandbuilder`, we've been trying to use more structured data types for commands in roachtest.
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk3fZA9Fe2NLdOcmWB:-NQk3fZD7ENSHruSYT_j:b78whfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/tests/versionupgrade.go#L143)):*
> ```Go
> 				fmt.Sprintf("{pgurl:1-%d}", len(c.All())),
> 			}
> 			return h.Run(rng, runCmd...)
> ```

Please use `cluster.RunE`. We want to return errors instead of calling `t.Fatal` in these callbacks.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk1Xgb9t3YXg-Ezcto:-NQk53NO0bhFruxez1zY:buud6dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L480)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I'm not convinced this function needs to be part of `*Helper` (I'd like to only add functions to this struct once there are many call sites that would benefit from it). I know we have `Query` related functions here already, but one distinction is that when we need to run SQL in a test, we will always connect to one gateway node; for running commands, it's very common that commands will need to run on multiple  nodes at the same time, and it's not great to have behavior/logging be different if we are running a command in one vs many nodes.

In the mixed-version closure, you can achieve the same behavior with


```go
node := h.RandomNode(rng, c.All())
c.RunE(...)
```
</blockquote></details>

I was debating if it should be in the helper at all. I'll move this code out.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk34fr8utJ0AZa41MU:-NQk4iT1EUW1UQespR0V:bdaq0u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L490)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

What's the reason we need to use `./workload` instead of `./cockroach workload`?
</blockquote></details>

The schemachange workload is not supported under the cockroach binary, that's something that we should get done. I'll get an issue open for it.
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk3AAs5B3o2z7Wp6IM:-NQk51MV99cQNlKS6OXe:b-ylbuvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/tests/versionupgrade.go#L134)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Instead of using the `sync.Once`, I think it makes more sense to call `mvt.OnStartup` and init the workload there.
</blockquote></details>

Good point I'll switch this.
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk3fZA9Fe2NLdOcmWB:-NQk5D0nD9f2s-a0FChk:b2zvxvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/tests/versionupgrade.go#L143)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Please use `cluster.RunE`. We want to return errors instead of calling `t.Fatal` in these callbacks.
</blockquote></details>

The run wrapper was doing this, but I"ll remove it and put the calls here directly on cluster.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 487 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQk2rAQ3BF4Izi9VD7T:-NQkqblc9QgCCfrYhiG0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8987d104df63dd28f8d798f8138b1efd41a917/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L487)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I also believe this function is doing something too specific to warrant a function in `*Helper`. In addition, it sounds like a function that the caller would always need to make sure to call just once. This is not quite the type of function that should live here. I'll make a comment down below.
</blockquote></details>

Done.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQl4w_MEcQOb0acgHcQ:-NQl4w_MEcQOb0acgHcR:ba76egz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f65e5df54a04ae9b7e517b7365e3f7a5926f384/pkg/cmd/roachtest/tests/versionupgrade.go#L112)):*
> ```Go
> 		if err := c.PutE(ctx, t.L(), t.DeprecatedWorkload(), "./workload", c.All()); err != nil {
> 			return err
> 		}
> ```

Probably cleaner to stash `./workload` "out-of-band" -- i.e., you can just call `c.Put()` (no need for `PutE`) before the `mvt := mixedversion.NewTest` line. If that fails, we don't waste time setting up the mixed-version test, and it also simplifies this closure too.
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQl6vl4AdJawUb3mgmp:-NQl6vl4AdJawUb3mgmq:btgndn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f65e5df54a04ae9b7e517b7365e3f7a5926f384/pkg/cmd/roachtest/tests/versionupgrade.go#L113)):*
> ```Go
> 			return err
> 		}
> 		return c.RunE(ctx, c.All(), "./workload init", "schemachange")
> ```

Nit: since these are all consts, probably reads better as a single string: `c.RunE(ctx, c.All(), "./workload init schemachange")`
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQl6-QJEOioaOuT_U2X:-NQl6-QJEOioaOuT_U2Y:b-ixkmfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f65e5df54a04ae9b7e517b7365e3f7a5926f384/pkg/cmd/roachtest/tests/versionupgrade.go#L145)):*
> ```Go
> 			runCmd.Flag("max-ops", 10)
> 			runCmd.Flag("concurrency", 2)
> 			runCmd.Arg("{pgurl:1-%d}", len(c.All()))
> ```

Nit: these can be chained

```go
runCmd := roachtestutil.NewCommand("...")
    .Flag("verbose", 1)
    .Flag("max-ops", 10)
```
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQl6D6dCHUjCrexAfCs:-NQl6D6dCHUjCrexAfCt:bw3dvke) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f65e5df54a04ae9b7e517b7365e3f7a5926f384/pkg/cmd/roachtest/tests/versionupgrade.go#L146)):*
> ```Go
> 			runCmd.Flag("concurrency", 2)
> 			runCmd.Arg("{pgurl:1-%d}", len(c.All()))
> 			randomNode := c.All().RandNode()
> ```

We should use `h.RandomNode()` here (i.e., using the `rng` provided as parameter instead of the global `rand`).

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQl4w_MEcQOb0acgHcQ:-NQlLf9H63zKRfOQsd7u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f65e5df54a04ae9b7e517b7365e3f7a5926f384/pkg/cmd/roachtest/tests/versionupgrade.go#L112)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Probably cleaner to stash `./workload` "out-of-band" -- i.e., you can just call `c.Put()` (no need for `PutE`) before the `mvt := mixedversion.NewTest` line. If that fails, we don't waste time setting up the mixed-version test, and it also simplifies this closure too.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-NQl6D6dCHUjCrexAfCs:-NQlLpFE6rzazpnq3Sju:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f65e5df54a04ae9b7e517b7365e3f7a5926f384/pkg/cmd/roachtest/tests/versionupgrade.go#L146)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

We should use `h.RandomNode()` here (i.e., using the `rng` provided as parameter instead of the global `rand`).
</blockquote></details>

Done.

**Review by renatolabs — APPROVED** [review]
:lgtm:

Thank you for adding the `schemachange` workload back!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98855#-:-NQlNWBX93r75V-MSRtq:b-r69akt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan)

**Comment by fqazi** [comment]
@renatolabs @chengxiong-ruan TFTR!

**Comment by fqazi** [comment]
This will need some tweaks on the workload side, we don't handle a specific version case for CREATE's properly. It should be minor will try and validate it a few times on Monday (otherwise there is a risk of intermittent failures).

**Pull request merged**
