### PR TITLE
sql: support `COMMENT ON COLUMN`

### PR DESCRIPTION
**Pull request by hueypark**
Informs #19472.

This patch introduces support for table column comments.

The syntax to set or delete a comment is the same as postgres:
`COMMENT ON COLUMN ... IS ...`. See:
https://www.postgresql.org/docs/9.1/sql-comment.html

Release note (sql change): CockroachDB now supports associating
comments to SQL table column using PostgreSQL's `COMMENT ON COLIMN`
syntax. This also provides proper support for pg's
`pg_catalog.pg_description` and built-in function `col_description()`.

### CODE REVIEW

**Comment by dt** [comment]
cc @knz, just so this is on your radar after the holidays

**Review by knz — COMMENTED** [review]
Thank you for the work!

My general comment here is that you have created a new concept of "column number" and this is not needed / unnecessary complex / not what postgres does.

Check this out:

```
kena=> create table t(a int, b int, c int);
CREATE TABLE
kena=> comment on column t.a is 'a';
COMMENT
kena=> comment on column t.b is 'b';
COMMENT
kena=> comment on column t.c is 'c';
COMMENT

kena=> select * from pg_description where description in ('a','b','c');
 objoid | classoid | objsubid | description
--------+----------+----------+-------------
  16395 |     1259 |        1 | a
  16395 |     1259 |        2 | b
  16395 |     1259 |        3 | c
(3 rows)

kena=> alter table t drop column b;
ALTER TABLE

kena=> select * from pg_description where description in ('a', 'c');
 objoid | classoid | objsubid | description
--------+----------+----------+-------------
  16395 |     1259 |        1 | a
  16395 |     1259 |        3 | c
(2 rows)
```

The comment table stores the actual column ID (In CockroachDB this is the `ID` field in the ColumnDescriptor struct). This does not change when a column is deleted/added. You can remove this logic from your patch, use the ID field directly and simplify the code accordingly.

Another thing: please add a test to check the following works:

```
BEGIN;
ALTER TABLE t ADD COLUMN x INT;
COMMENT ON COLUMN t.x IS 'foo';
COMMIT;
```

If this test fails, you may need to change your code peek at the "mutation columns". Let us know if you need help.


Thank you!

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-:-LUpAirWCi7AystCu5yC:bmogmkm)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/comment_on_column.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp7rgc7ES98XN8ttVA:-LUp7rgc7ES98XN8ttVB:b2fxsgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/comment_on_column.go#L55)):*
> ```Go
> 		_, err := params.p.extendedEvalCtx.ExecCfg.InternalExecutor.Exec(
> 			params.ctx,
> 			"upsert-column-comment",
> ```

"set-column-comment" - the word "upsert" is an implementation detail
___
*[pkg/sql/parser/sql.y, line 2016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp9Khn1-hHMnoMayDj:-LUp9Khn1-hHMnoMayDk:b-j393uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/parser/sql.y#L2016)):*
> ```Yacc
>       return 1
>     }
>     $$.val = &tree.CommentOnColumn{ColumnPath: columnPath, Comment: $6.strPtr()}
> ```

Use `tree.classifyColumnItem()` instead (you will need to ensure it is exported) then store a `ColumnItem` in `CommentOnColumn`.

No need to add a new "column path" struct.
___
*[pkg/sql/sem/tree/column_path.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp9TGl9MPTi4_DSok7:-LUp9TGl9MPTi4_DSok8:b83ajch) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/sem/tree/column_path.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

see my previous comment - use the existing ColumnItem instead.
___
*[pkg/sql/sem/tree/name_resolution.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp9ZMM4u-m8fEBZrMU:-LUp9ZMM4u-m8fEBZrMV:b-upbitz) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/sem/tree/name_resolution.go#L63)):*
> ```Go
> 
> // NormalizeColumnPath transforms an UnresolvedName into a ColumnPath.
> func NormalizeColumnPath(n *UnresolvedName) (columnPath ColumnPath, err error) {
> ```

see before - classifyColumnItem already does what you need.
___
*[pkg/sql/sqlbase/structured.go, line 1925 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUpAgnD-CRgdsseLZDy:-LUpAgnEAkGI1v6TZ2hs:b-vodu1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/sqlbase/structured.go#L1925)):*
> ```Go
> 
> // FindColumnNumberByName finds the column number with the specified name.
> func (desc *TableDescriptor) FindColumnNumberByName(name tree.Name) (int, error) {
> ```

This is not needed, see my comment at top.

**Review by hueypark — COMMENTED** [review]
Thank you for your review!

I removed the "column number" and this change triggered the change the "pg_catalog.pg_attribute".

I added a transaction test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-:-LUwjvoj0n0iMLgO3LIM:bhj58vx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/comment_on_column.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp7rgc7ES98XN8ttVA:-LUwoNLF1ID4OuxV1M4Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/comment_on_column.go#L55)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"set-column-comment" - the word "upsert" is an implementation detail
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 2016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp9Khn1-hHMnoMayDj:-LUwoQnbAApETvMuBKvj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/parser/sql.y#L2016)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Use `tree.classifyColumnItem()` instead (you will need to ensure it is exported) then store a `ColumnItem` in `CommentOnColumn`.

No need to add a new "column path" struct.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/column_path.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp9TGl9MPTi4_DSok7:-LUwoT0t-L7T63-xVL8j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/sem/tree/column_path.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see my previous comment - use the existing ColumnItem instead.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/name_resolution.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUp9ZMM4u-m8fEBZrMU:-LUwoUiw7vEotT8XeE_i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/sem/tree/name_resolution.go#L63)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see before - classifyColumnItem already does what you need.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 1925 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUpAgnD-CRgdsseLZDy:-LUwoWM5BsE-csmcsbPV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d00de53867138571178bbcf7ca8e223917fd2f/pkg/sql/sqlbase/structured.go#L1925)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is not needed, see my comment at top.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
Very good. Thank you for this change. I have just one minor comment remaining and this is good to go.

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-:-LUzNqoq65uig8yq0dKC:b8m1c0y)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/sql.y, line 2011 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUzN1Ks81psvNth2BnS:-LUzN1Ks81psvNth2BnT:b34cfsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cff17b26e2a787adf517f6ff590a321ec21deed/pkg/sql/parser/sql.y#L2011)):*
> ```Yacc
> | COMMENT ON COLUMN column_path IS comment_text
>   {
>     varName, err := $4.unresolvedName().NormalizeVarName()
> ```

Since `column_path` can only ever produce column items, I think you can do this:

```go
columnItem := $4.unresolvedName().NormalizeVarName().(*tree.ColumnItem)
```

and simplify accordingly.
___
*[pkg/sql/sem/tree/comment_on_column.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUzNYFOEo-QqI9xtji4:-LUzNYFPDbukLZqk9bxV:b-yfon1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cff17b26e2a787adf517f6ff590a321ec21deed/pkg/sql/sem/tree/comment_on_column.go#L21)):*
> ```Go
> // CommentOnColumn represents an COMMENT ON COLUMN statement.
> type CommentOnColumn struct {
> 	ColumnItem
> ```

Since `NormalizeVarName` allocates a ColumnItem on the heap always, you can store the pointer in `CommentOnColumn`.

If you store it by value here, you would be forcing a copy from the heap value to the new copy, and then discard the heap value. This is unnecessary data movement.

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33355)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/sql.y, line 2011 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUzN1Ks81psvNth2BnS:-LV2iHCc2CJ_SvePScfU:b8akox7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cff17b26e2a787adf517f6ff590a321ec21deed/pkg/sql/parser/sql.y#L2011)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Since `column_path` can only ever produce column items, I think you can do this:

```go
columnItem := $4.unresolvedName().NormalizeVarName().(*tree.ColumnItem)
```

and simplify accordingly.
</blockquote></details>

I can't do that beacause of NormalizeVarName() returns 2 value.
___
*[pkg/sql/sem/tree/comment_on_column.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LUzNYFOEo-QqI9xtji4:-LV2iLP55X5BOVTkCGen:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cff17b26e2a787adf517f6ff590a321ec21deed/pkg/sql/sem/tree/comment_on_column.go#L21)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Since `NormalizeVarName` allocates a ColumnItem on the heap always, you can store the pointer in `CommentOnColumn`.

If you store it by value here, you would be forcing a copy from the heap value to the new copy, and then discard the heap value. This is unnecessary data movement.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33355)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/sql.y, line 2023 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LV3ILve5bDafiuCfJcE:-LV3ILvfEFR3Nd9_OVJS:b-e5vmrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/83b1a4e8828fee93cd4c16cd9c4c739fbb8b0ff2/pkg/sql/parser/sql.y#L2023)):*
> ```Yacc
>     columnItem, ok := varName.(*tree.ColumnItem)
>     if !ok {
>       sqllex.Error(fmt.Sprintf("invalid column name: %s", $4.unresolvedName()))
> ```

We prefer to do this to ensure quoting is always done properly: `Sprintf("... %q", tree.ErrString($4.unresolvedName()))`

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33355)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/sql.y, line 2023 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-LV3ILve5bDafiuCfJcE:-LV3VZ2D0p34rvOK4OsO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83b1a4e8828fee93cd4c16cd9c4c739fbb8b0ff2/pkg/sql/parser/sql.y#L2023)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We prefer to do this to ensure quoting is always done properly: `Sprintf("... %q", tree.ErrString($4.unresolvedName()))`
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
Thank you!

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33355#-:-LV3WKVADZ5GmeNkDYIM:b-9755fn)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
We are most grateful for your contributions. Happy new year 2019!

bors r+

**Pull request merged**
