### PR TITLE
sql: allowlist non-system tenant configurable settings

### PR DESCRIPTION
**Pull request by otan**
Previously, we used SystemOnly() to denylist the setting of certain
cluster settings. This flips the script and only allowlist a small
subset of cluster settings. These are still overridable for root users,
which in the case of tenants are only SREs.

Resolves CRDB-8007

Release note (general change): Non-system tenants can now only
configure specific CLUSTER SETTINGs when they are not root.

### CODE REVIEW

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68406)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @piyush-singh, and @rafiss)

___
*[pkg/settings/duration.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68406#-MhJPRUB1Lv92Mnzmu_B:-MhJPRUCCh15i2Hr2QWT:b-11px4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/91f7e83ee63d77d3aff6cf5422a6206412b46487/pkg/settings/duration.go#L125)):*
> ```Go
> // WithNonSystemTenantConfigurable marks this setting as settable by
> // non-system tenants and can be chained.
> func (d *DurationSetting) WithNonSystemTenantConfigurable() *DurationSetting {
> ```

Nit: What do you think of the name WithTenantConfigurable?

**Comment by dt** [comment]
I have significant misgivings about this -- reserving some rows in the settings table -- approach to controlling guest tenant behavior.

If we are relying on a hosted tenant process behavior reading a certain configuration, we should read that configuration from _a place that process cannot write_, e.g. a CLI flag, env var, or, in this case, I'd say a span of rows in the host cluster's key-space, via the TenantConnector. 

Storing values that the host cluster wants to have the exclusive right to set inside some, but not all, rows of a table inside the tenant -- where the other rows _are_ writable by the tenant, seems like very messy, leaky abstraction. Indeed, in this change as is, I could just `insert into system.settings values (name-of-setting-i-should-not-set, some-value)` right? Or I could craft start cockroach demo, where I am root, set whatever settings I want, take a backup, and then RESTORE that backup in my tenant. Sure, we _could_ start adding row-level permissions checks to SQL, or try to take away non-`node` writes, and then paper over RESTORE, but I think having to add all these extra checks points to the underlying scheme being not safe-by-default, and thus prune to a mistake. If we're relying on these for availability or security of the hosted service -- and we might start doing so if we acclimate to "we control these", that seems like a risk.

Instead, I would propose that we add an accessor to the TenantConenctor, so that host controlled settings are read _from the host_, from a key-span that the tenant process _cannot_ write to. That seems like it would robust by default.

I haven't prototyped this to know the exact details, but here's a strawman: 
1) add a `GetTenantSettings()` to the connector that scans the tenantID's prefix of the host cluster's tenant_settings table and returns each setting/value pair (recall we only store overrides of defaults) and returns a map of overridden settings (you could make it a sorted iterator to avoid materializing it too).
2) in the settings loop, any time we read the settings table, check the connector and if it returns anything, read the value from it, not the settings table.
3) add one cluster setting like `cluster.host-settings.last-updated` that we can touch, from the host cluster, whenever the host cluster UI changes any host-controlled settings for that tenant. NB: We are not relying on it having any particular value -- the tenant can set it too if they want with no ill effect, so it is okay to be in the tenant's key space. When it changes, it will show up in the tenant's settings changes rangefeed, just like if any other (tenant-controlled) setting changed, to trigger a re-read of settings.

What I like about this: 
a) we can after-the-fact override *any* setting, even if in the code we didn't originally mark it as host-only, if we find ourselves in a situation where we need it to have a particular value, and we can be assured it will _stay_ at that value regardless of what the tenant sets it to.
b) we don't need to worry about what the tenant can or can't write to their own settings table -- if we choose to override a setting from the host, that's its value. 
c) we can, and probably should, mark settings that we want the host to always win -- we can reject attempts to set them but, unlike this PR here, we can also *ignore* any value they may have in the settings table as well, if they somehow snuck one in there, because we've mark it as only-ever-read-from-host.

Again, that's a strawman -- maybe we'd rather access them individually, or use gossip, or I donno, something else, but I think the core principle of reading from the host is the important difference (and not reading from the tenant's table at all for a setting marked as host-only).

**Comment by ajwerner** [comment]
My counterargument on all of this is that we are approaching this world with a threat model that the tenant process might do literally anything if compromised. I agree that operators need some knobs to control tenant behavior. I am not yet convinced that the values that those knobs take on must not be stored within the tenant keyspace. Things like what we're doing here form conventions on what the tenant pod will actually set. 

When I look at [the proposal for which settings are per tenant but not be possibly controlled by the tenant](https://docs.google.com/document/d/1VZVriPUn3DGJRi73HD1aQFt326AgGyM2rnpDq7TWUyM/edit#heading=h.o96vxb35lm3t), I find myself surprised and confused. Many of these features would affect the behavior of the sql pods in ways that the user might care about. If the host cluster is not robust to these different behavioral settings, some of which may be detrimental for the user, then we have a different problem on our hands related to control and isolation.

If the user wants to set some limits to be high and then finds that they experience crashing, I'm not necessarily upset about it. I guess our SREs would be, hence this PR here.

So, I feel like we should form conventions about what settings we allow non-admins to set from their pod via software enforcement (this PR), we should add tools for an operator to set setting values within a tenant, and then call it a day. 

Can I ask for some examples of settings where this proposal would be unacceptable?

**Comment by otan** [comment]
Some missing context: this is meant to be a stopgap before implementing all of https://docs.google.com/document/d/1VZVriPUn3DGJRi73HD1aQFt326AgGyM2rnpDq7TWUyM/edit#heading=h.o96vxb35lm3t. I think your confusion @ajwerner should be addressed there.

We're trying to get something into v21.2 that addresses the problems outlined in https://docs.google.com/document/d/1Nz0bmtJV8tBrlhYOjnyTxfXsIRTb2BKQ8LlclArnUNo/edit. 

> Instead, I would propose that we add an accessor to the TenantConenctor, so that host controlled settings are read from the host, from a key-span that the tenant process cannot write to. That seems like it would robust by default.

i can buy that but oh boy, that'd take a while (partly due to taking a while to get updates on CRDB-8007 :\). @piyush-singh would be good to contribute your thoughts here.

**Comment by dt** [comment]
> This flips the script and only allowlist a small subset of cluster settings.

I share @ajwerner's concerns about the broadness of the shift from deny-list to allow-list: Just looking at a couple settings that become unreachable for serverless users here: `kv.bulk_ingest.max_pk_buffer_size` lets you limit how much of your SQL memory budget a backfill might claim from SQL traffic or `bulkio.index_backfill.batch_size` allows controlling backfill reads and their impact on your other traffic -- both of those seem equally likely to be something a tenant or non-tenant may need to tune. It seems likely there are many more?

I do not immediately why we think _running as a tenant_, i.e. running with your KV storage separated from your SQL execution, should also mean you now default don't have a need for these controls we added over SQL behaviors? We obviously added those controls because we thought some users may need them; why do we think users who have their SQL and KV processes split default to not needing them?

Obviously we've identified some settings that a tenant should _not_ be able to adjust, because we're relying on those settings having, or not having, particular values for our ability to deliver a hosted service. But that seems like all the more reason to take extra care and ensure that the value of those knobs is somewhere we exclusively control e.g. read via the tenantconnector as described above or just from cli params or the env, or maybe even at the most primitive stop-gap, the code itself, by saying that tenant pods do not read the values for systemOnly settings and always use their defaults.

**Comment by otan** [comment]
Well, both Piyush and Vy are away (Piyush until October) so any product expertise on the original discussions there is unavailable :)

Vy comes back next week, so I'll discuss it with her then. 

I think the problem of cluster settings being too "vague" is fixable by taking a larger inventory of cluster settings we want people to set - this was the rudimentary list I was given and I know there have been comms to fish for more. 

>  But that seems like all the more reason to take extra care and ensure that the value of those knobs is somewhere we exclusively control e.g. read via the tenantconnector as described above or just from cli params or the env, or maybe even at the most primitive stop-gap, the code itself, by saying that tenant pods do not read the values for systemOnly settings and always use their defaults.

The argument i've been hearing from the flip side is we want to be conservative in what we allow, but be overridable just in case, which is why this was put in place. For me, the solution feels like the best compromise between "SREs can configure these manually" (by logging in as the root user, tenants have admin role but are never root), "tenants can't (easily) put their session settings out of control" (because they're blocked unless they edit the data directly from what i understand of your proposal) and least amount of throwaway work before any long term proposal (which is looking into the direction of the RFC, arguably we could go in a different direction instead but hey, stability is next week). The fallback that SREs can override settings that users may want to control means there's always a way out.

If we're concerned about the `INSERT INTO cluster_settings ... ` case, which seems like the main overriding concern which is not addressed this way, I guess the question comes down to abuse vectors and how much we have mitigated this.

> Or I could craft start cockroach demo, where I am root, set whatever settings I want, take a backup, and then RESTORE that backup in my tenant.

Do we backup and restore cluster settings? If so that seems .... bad? Or is it just that any user can set anything in `system.settings` if they are admin (which they are). Would disallowing permissions to set the cluster setting tables in tenants for non-root users enough?

cc @vy-ton

**Pull request closed without merging**
