### PR TITLE
opt: reorganize selectivity calculations

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add disable flag to opttester

Add a flag to norm/opt that disables specific rules.

Release note: None

#### opt: add testcases showing stats problem

Release note: None

#### opt: reorganize selectivity calculations

Fixing a few issues with selectivity calculations, related to the
handling of constraints in conjunction with equivalencies. In
principle, applying the filter `a=10 AND a=b` should result in similar
stats with applying `a=10` and then applying `a=b` but this was not
the case.

Changes:
 - We were updating the distinct counts to take into account the
   equivalencies before we estimated selectivity. This can lead to the
   selectivity of some constraints effectively being applied twice.
   The call to applyEquivalencies is moved after the selectivity
   calculations.

 - When calculating selectivity from distinct counts we were taking
   into account equivalencies, even though we later apply the
   selectivity of equivalencies separately. The fix is to only look at
   the distinct count of each column, rather than taking the minimum
   across the equivalency group.

 - When calculating selectivity for equivalency, we were looking
   at the "input" distinct counts. But if some distinct counts were
   updated by a constraint, we want to use the updated values; so the
   code now checks `ColStats` first. An example with some intuition
   for this: when applying a filter `a=10 AND a=b`, the behavior
   should be the same with first applying filter `a=10` and then
   applying `a=b`. So the "input" to the equivalency calculation needs
   to reflect `a=10`.

 - Finally, another difference when handling a conjunction is that we
   only calculate RowCount and bound the distinct counts at the end.
   We now update the RowCount "in step" with Selectivity; in addition,
   RowCount is used as an upper bound when consulting "input" stats.

Release note: None

### CODE REVIEW

**Review by madhavsuresh — APPROVED** [review]
:lgtm_strong:  
An idea for beefier stats: a series of tests that demonstrate/enforce monotonicity of stats w.r.t. selectivity. It seems like this bug could have been uncovered with a monotonicity check. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-:-LKRvEX59Xeg-L2MUk_a:bvo5i3d)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/stats/select, line 505 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKRoM9B-ZTC2uRFfeR2:-LKRoM9B-ZTC2uRFfeR3:b-1tsr34) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/memo/testdata/stats/select#L505)):*
> ```
> select
>  ├── columns: order_id:1(int!null) item_id:2(int!null) customer_id:3(int!null) year:4(int)
>  ├── stats: [rows=1, distinct(1)=1, distinct(2)=1, distinct(3)=1]
> ```

I think we need to be very clear about what row counts represent. Do they represent the probability of finding a row, or do they represent an estimate of the row counts? When row counts are above one, are we certain we will find a row? Of course these things will change once histograms are in the mix. We should state it somewhere and make a pact of to adhere to it.  

I'm also not entirely clear why your change caused the distinct counts and row counts to stabilize around 1. For example, the next test case in the file (intuitively) should have less selectivity (higher row and distinct counts), right?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28892)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/stats/select, line 505 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKRoM9B-ZTC2uRFfeR2:-LKSIrBo7bFJXXQ1jANV:b-jsna90) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/memo/testdata/stats/select#L505)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

I think we need to be very clear about what row counts represent. Do they represent the probability of finding a row, or do they represent an estimate of the row counts? When row counts are above one, are we certain we will find a row? Of course these things will change once histograms are in the mix. We should state it somewhere and make a pact of to adhere to it.  

I'm also not entirely clear why your change caused the distinct counts and row counts to stabilize around 1. For example, the next test case in the file (intuitively) should have less selectivity (higher row and distinct counts), right? 
</blockquote></details>

In my mind, row counts are (an estimation of) the expected value of rows. When it is < 1, the expected value is roughly the probability of having 1 row (technically it's the sum `i * probability-of-having-i-rows`). There are no hard guarantees. It could be 100000 and it's still no guarantee that we won't have 0 rows (especially in the absence of stats).

I agree this should be thought through more and written down.

As for the test below, it's pretty much due to limitations in the implementation. Even though `item_id > 0 AND item_id < 5` would form a tight constraint with distinct count 4, they appear in conjunction with an equality so the constraint isn't tight. That makes them be considered separately, and each one is treated as having unknown selectivity `1/3`.

@rytaft might have more thoughs here.

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28892)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSltPy9lo7B9BbZEaI:-LKSltPy9lo7B9BbZEaJ:bzd8r7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/memo/statistics_builder.go#L446)):*
> ```Go
> 	}
> 
> 	// Calculate row count and selectivity
> ```

Why did you move the selectivity header? Seems like that calculation is still happening below....
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1656 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSmx_EAwek39qb5LEr:-LKSmx_EAwek39qb5LEs:b-eax31z) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/memo/statistics_builder.go#L1656)):*
> ```Go
> // selectivityFromEquivalencies determines the selectivity of equality
> // constraints. It uses the distinct values before they are updated to take into
> // consideration the equivalencies.
> ```

This comment is a bit confusing. Maybe instead say it must be called before `applyEquivalencies`?
___
*[pkg/sql/opt/memo/testdata/stats/join, line 723 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSknST4AhbdrrFn4P0:-LKSknST4AhbdrrFn4P1:bd2h7xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1401e97b644fa201a319e8d56e3f727db1f2e66/pkg/sql/opt/memo/testdata/stats/join#L723)):*
> ```
> 
> norm disable=(PushFilterIntoJoinLeftAndRight,PushFilterIntoJoinLeft,PushFilterIntoJoinRight,MapFilterIntoJoinLeft,MapFilterIntoJoinRight)
> SELECT * FROM (SELECT * FROM uvw WHERE w=1) JOIN (SELECT * FROM xyz WHERE x=10) ON u=x
> ```

these aren't quite equivalent since the filter `x=10` should be pushed down to both sides (as `u=10` on the left side)... does that change anything?
___
*[pkg/sql/opt/memo/testdata/stats/select, line 603 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSlQHA4tq3TGjdpwa5:-LKSlQHA4tq3TGjdpwa6:b-qknxlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1401e97b644fa201a319e8d56e3f727db1f2e66/pkg/sql/opt/memo/testdata/stats/select#L603)):*
> ```
>       └── rowid int not null (hidden)
> 
> # Test selectivity calculations by applying the two constraints in different
> ```

nice tests!
___
*[pkg/sql/opt/memo/testdata/stats/select, line 505 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKRoM9B-ZTC2uRFfeR2:-LKSnuPw5LbV3piz6CJP:b-l132ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/memo/testdata/stats/select#L505)):*
Yea, the row counts are the expected value of the rows. It's not pure probability because we are making the same assumption outlined by the Postgres optimizer:
> Consistency of clauses
> ----------------------
> 
> Functional dependencies only express general dependencies between columns,
> without referencing particular values. This assumes that the equality clauses
> are in fact consistent with the functional dependency, i.e. that given a
> dependency (a=>b), the value in (b=?) clause is the value determined by (a=?).
> If that's not the case, the clauses are "inconsistent" with the functional
> dependency and the result will be over-estimation.

In other words, we assume the users will write queries that make sense.

Regarding the query with `item_id > 0 AND item_id < 5` -- that is a current limitation that will need to be fixed at some point. I think it will be relatively straightforward to fix once we support null counts. It didn't seem important enough to write a special case for right now...
___
*[pkg/sql/opt/props/statistics.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSqen_0M4E7RD7I4H7:-LKSqen_0M4E7RD7I4H8:b-5dfl4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/props/statistics.go#L106)):*
> ```Go
> // Selectivity are updated, as well as any DistinctCounts that are larger than
> // the RowCount.
> func (s *Statistics) ApplySelectivity(selectivity float64) {
> ```

It would be good to add an explanation for why we aren't directly applying the selectivity to distinct counts. (Something related to the fact that at the time this function is called, the only column stats we have are from explicitly constrained columns)

**Comment by rytaft** [comment]
:lgtm: nicely done!

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28892)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSltPy9lo7B9BbZEaI:-LKTMog-7kJf9E0UeYet:brmx44y) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/memo/statistics_builder.go#L446)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you move the selectivity header? Seems like that calculation is still happening below....
</blockquote></details>

I wanted to consolidate "row count" and "selectivity" since they happen together. Moved it down.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1656 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSmx_EAwek39qb5LEr:-LKTN5Xr325e8eEhUo8O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/memo/statistics_builder.go#L1656)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment is a bit confusing. Maybe instead say it must be called before `applyEquivalencies`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/join, line 723 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSknST4AhbdrrFn4P0:-LKTNBZB781PT0tkCd0Z:bzddy8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1401e97b644fa201a319e8d56e3f727db1f2e66/pkg/sql/opt/memo/testdata/stats/join#L723)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

these aren't quite equivalent since the filter `x=10` should be pushed down to both sides (as `u=10` on the left side)... does that change anything?
</blockquote></details>

These tests disable the join pushdown rules.
___
*[pkg/sql/opt/props/statistics.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSqen_0M4E7RD7I4H7:-LKTPXuJ25UmkKFQiImI:by1gl2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a2136a9f62d31c85ac907b9a009c0ed9c5ed33/pkg/sql/opt/props/statistics.go#L106)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It would be good to add an explanation for why we aren't directly applying the selectivity to distinct counts. (Something related to the fact that at the time this function is called, the only column stats we have are from explicitly constrained columns)
</blockquote></details>

I moved this to `props` so the description should be less dependent on how we use it. I mentioned that we don't update the DistinctCounts, and also moved `applySelectivityToColStat` to this file as `ColumnStatistic.ApplySelectivity` and mentioned that function in the comment.

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/memo/testdata/stats/join, line 723 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSknST4AhbdrrFn4P0:-LKTVDyAERtSDm4s-dOB:b-9b6wxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1401e97b644fa201a319e8d56e3f727db1f2e66/pkg/sql/opt/memo/testdata/stats/join#L723)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These tests disable the join pushdown rules.
</blockquote></details>

Right, but maybe you could add another test for this:
`SELECT * FROM (SELECT * FROM uvw WHERE w=1 AND u=10) JOIN (SELECT * FROM xyz WHERE x=10) ON u=x`

Hopefully it will also have a similar row count....

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28892)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28892)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 723 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSknST4AhbdrrFn4P0:-LKTsLja68hKAPKZ7HSY:b-b2nbfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1401e97b644fa201a319e8d56e3f727db1f2e66/pkg/sql/opt/memo/testdata/stats/join#L723)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Right, but maybe you could add another test for this:
`SELECT * FROM (SELECT * FROM uvw WHERE w=1 AND u=10) JOIN (SELECT * FROM xyz WHERE x=10) ON u=x`

Hopefully it will also have a similar row count....
</blockquote></details>

Oh. This has much lower row count (I kind of expected that, I was trying to compare cases with the same left input).

```
norm disable=(PushFilterIntoJoinLeftAndRight,PushFilterIntoJoinLeft,PushFilterIntoJoinRight,MapFilterIntoJoinLeft,MapFilterIntoJoinRight)
SELECT * FROM (SELECT * FROM uvw WHERE w=1 AND u=10) JOIN (SELECT * FROM xyz WHERE x=10) ON u=x
----
inner-join
 ├── columns: u:1(int!null) v:2(int) w:3(int!null) x:5(int!null) y:6(int) z:7(int)
 ├── stats: [rows=0.0029154519, distinct(1)=0.00204081633, distinct(5)=0.00204081633]
 ├── fd: ()-->(1,3,5), (1)==(5), (5)==(1)
 ├── select
 │    ├── columns: u:1(int!null) v:2(int) w:3(int!null)
 │    ├── stats: [rows=0.00204081633, distinct(1)=0.00204081633, distinct(3)=0.00204081633]
 │    ├── fd: ()-->(1,3)
 │    ├── scan uvw
 │    │    ├── columns: u:1(int) v:2(int) w:3(int)
 │    │    └── stats: [rows=1000, distinct(1)=700, distinct(3)=700]
 │    └── filters [type=bool, outer=(1,3), constraints=(/1: [/10 - /10]; /3: [/1 - /1]; tight), fd=()-->(1,3)]
 │         ├── w = 1 [type=bool, outer=(3), constraints=(/3: [/1 - /1]; tight)]
 │         └── u = 10 [type=bool, outer=(1), constraints=(/1: [/10 - /10]; tight)]
 ├── select
 │    ├── columns: x:5(int!null) y:6(int) z:7(int)
 │    ├── stats: [rows=1.42857143, distinct(5)=1]
 │    ├── fd: ()-->(5)
 │    ├── scan xyz
 │    │    ├── columns: x:5(int) y:6(int) z:7(int)
 │    │    └── stats: [rows=1000, distinct(5)=700]
 │    └── filters [type=bool, outer=(5), constraints=(/5: [/10 - /10]; tight), fd=()-->(5)]
 │         └── x = 10 [type=bool, outer=(5), constraints=(/5: [/10 - /10]; tight)]
 └── filters [type=bool, outer=(1,5), constraints=(/1: (/NULL - ]; /5: (/NULL - ]), fd=(1)==(5), (5)==(1)]
      └── u = x [type=bool, outer=(1,5), constraints=(/1: (/NULL - ]; /5: (/NULL - ])]
```

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28892)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 723 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28892#-LKSknST4AhbdrrFn4P0:-LKU1X2T65rJ3UmrdiGD:buedb1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1401e97b644fa201a319e8d56e3f727db1f2e66/pkg/sql/opt/memo/testdata/stats/join#L723)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh. This has much lower row count (I kind of expected that, I was trying to compare cases with the same left input).

```
norm disable=(PushFilterIntoJoinLeftAndRight,PushFilterIntoJoinLeft,PushFilterIntoJoinRight,MapFilterIntoJoinLeft,MapFilterIntoJoinRight)
SELECT * FROM (SELECT * FROM uvw WHERE w=1 AND u=10) JOIN (SELECT * FROM xyz WHERE x=10) ON u=x
----
inner-join
 ├── columns: u:1(int!null) v:2(int) w:3(int!null) x:5(int!null) y:6(int) z:7(int)
 ├── stats: [rows=0.0029154519, distinct(1)=0.00204081633, distinct(5)=0.00204081633]
 ├── fd: ()-->(1,3,5), (1)==(5), (5)==(1)
 ├── select
 │    ├── columns: u:1(int!null) v:2(int) w:3(int!null)
 │    ├── stats: [rows=0.00204081633, distinct(1)=0.00204081633, distinct(3)=0.00204081633]
 │    ├── fd: ()-->(1,3)
 │    ├── scan uvw
 │    │    ├── columns: u:1(int) v:2(int) w:3(int)
 │    │    └── stats: [rows=1000, distinct(1)=700, distinct(3)=700]
 │    └── filters [type=bool, outer=(1,3), constraints=(/1: [/10 - /10]; /3: [/1 - /1]; tight), fd=()-->(1,3)]
 │         ├── w = 1 [type=bool, outer=(3), constraints=(/3: [/1 - /1]; tight)]
 │         └── u = 10 [type=bool, outer=(1), constraints=(/1: [/10 - /10]; tight)]
 ├── select
 │    ├── columns: x:5(int!null) y:6(int) z:7(int)
 │    ├── stats: [rows=1.42857143, distinct(5)=1]
 │    ├── fd: ()-->(5)
 │    ├── scan xyz
 │    │    ├── columns: x:5(int) y:6(int) z:7(int)
 │    │    └── stats: [rows=1000, distinct(5)=700]
 │    └── filters [type=bool, outer=(5), constraints=(/5: [/10 - /10]; tight), fd=()-->(5)]
 │         └── x = 10 [type=bool, outer=(5), constraints=(/5: [/10 - /10]; tight)]
 └── filters [type=bool, outer=(1,5), constraints=(/1: (/NULL - ]; /5: (/NULL - ]), fd=(1)==(5), (5)==(1)]
      └── u = x [type=bool, outer=(1,5), constraints=(/1: (/NULL - ]; /5: (/NULL - ])]
```

</blockquote></details>

Similarly, for the select tests `SELECT * FROM uvw WHERE u=v AND u=10 AND v=10` has much fewer rows than `SELECT * FROM uvw WHERE u=v AND u=10`.  Before this change, they both had the small number of rows.

Note though that replacing with `u=10 AND v=5` gives the same stats, which is not surprising given that the code doesn't actually care about the specific values. From that perspective, I guess the rowcount reflects the probability that the conditions are compatible.

**Comment by RaduBerinde** [comment]
I am merging this - it doesn't seem to affect any plans negatively and it unblocks the lookup join work. I think we should definitely continue thinking through these cases though.

bors r+

**Pull request merged**
