### PR TITLE
jobs: record error when marking job as reverting

### PR DESCRIPTION
**Pull request by thoszhang**
When a job resumer returns an error in the job state machine, we will
now record the error in the job payload in a new `final_resume_error`
field, in the same transaction in which the job is marked as reverting.
This allows the error to be decoded and handled in `OnFailOrCancel`.

Whether a job has encountered an error that makes it ineligible to be
resumed is now determined from `final_resume_error` for the purposes of
controlling state transitions.  The existing `error` field is still
populated and used for reporting errors.

Release note: None

### CODE REVIEW

**Review by spaskob — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @spaskob)

___
*[pkg/jobs/jobs.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45263#-M0Z4HWE7nRXYeSer1OC:-M0Z4HWE7nRXYeSer1OD:bxk7gbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd6ae24174a106f51a153cfe5b0c044acf07026/pkg/jobs/jobs.go#L328)):*
> ```Go
> 		// We use the absence of error to determine what state we should
> 		// resume into.
> 		if md.Payload.Error == "" || md.Payload.FinalResumeError != nil {
> ```

this actually highlights a bug that I introduced, I think my intention was to mark the error when setting the job to reverting but I never did.
The condition should be:

```
md.Payload.FinalResumeError == nil
```

I will add a test and make sure it fails on master.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/jobs/jobs.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45263#-M0Z4HWE7nRXYeSer1OC:-M0Z9j-90lNT6ckRHfrG:bpjjtle) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd6ae24174a106f51a153cfe5b0c044acf07026/pkg/jobs/jobs.go#L328)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

this actually highlights a bug that I introduced, I think my intention was to mark the error when setting the job to reverting but I never did.
The condition should be:

```
md.Payload.FinalResumeError == nil
```

I will add a test and make sure it fails on master. 
</blockquote></details>

Okay, I see. I think I also need to replace the condition here:
https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobs.go#L354

That gets rid of all the usages of `payload.Error` for determining state transitions, and `payload.Error` will only be used for displaying errors to the user. I think this should be safe. The only situations where `payload.Error` can be non-empty while `payload.FinalResumeError` is nil will be if the job is marked as failed without ever having gone through the reverting state. In that case, we're in a terminal state and there are no more state transitions to worry about.

**Review by thoszhang — COMMENTED** [review]
I updated `Reverted()` to start writing `Payload.Error()` (though now it matters less), and got rid of the one other instance of checking whether `Payload.Error()` is empty (to determine whether a job is cancellable).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45263#-:-M0ZH6QjC_WWamWt22xy:bs52bp8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/jobs/jobs.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45263#-M0Z4HWE7nRXYeSer1OC:-M0ZPxNTDFAwU2v5rGre:b4sw4x6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd6ae24174a106f51a153cfe5b0c044acf07026/pkg/jobs/jobs.go#L328)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Okay, I see. I think I also need to replace the condition here:
https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobs.go#L354

That gets rid of all the usages of `payload.Error` for determining state transitions, and `payload.Error` will only be used for displaying errors to the user. I think this should be safe. The only situations where `payload.Error` can be non-empty while `payload.FinalResumeError` is nil will be if the job is marked as failed without ever having gone through the reverting state. In that case, we're in a terminal state and there are no more state transitions to worry about.
</blockquote></details>

cool thank you!

**Comment by lucy-zhang** [comment]
TFTR

bors r+

**Pull request merged**
