### PR TITLE
util/fsm: small improvements

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Release notes: none

### CODE REVIEW

**Comment by andreimatei** [comment]
The description renders like this:

s

**Comment by andreimatei** [comment]
cc @knz

**Comment by andreimatei** [comment]
@nvanbenschoten rebased; ptal

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-:-L2MscTFb4PxoPIImuTP:bmd2chr)*

**Comment by knz** [comment]
Thank you!

---

Reviewed 2 of 2 files at r1, 3 of 7 files at r2.
Review status: 3 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-:-L2Mx50Z1Xh88xSYjiKc:b-9755fn)*

**Comment by nvanbenschoten** [comment]
Reviewed 2 of 2 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/util/fsm/debug.go, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NLEXEY6qR0hrn8EAQ:-L2NLEXEY6qR0hrn8EAR:b-c2atfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1d685cd4bf162461735948f44953c49cf980cb/pkg/util/fsm/debug.go#L37)):*
> ```Go
> // Event to the specified State and the bool true, or false if there is no
> // associated transition.
> func (di debugInfo) eventAppliedToState(sName, eName string) (State, string, bool) {
> ```

I'd return a `Transition` here.

---

*[pkg/util/fsm/fsm.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NKaqzfKs_IKRf7t-H:-L2NKaqzfKs_IKRf7t-I:bi0fph2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc4c8924b7b6437c942268182ca52ad017f5aa0d/pkg/util/fsm/fsm.go#L23)):*
> ```Go
> // This package encourages the Pattern to be declared as a map literal. When
> // declaring this literal, be careful to not declare two equal keys: they'll
> // result in the second overwriting the first with no warning. Note that keys
> ```

Expand this a bit to point out that this is an artifact of Go's map rules and not a result of something we do during pattern expansion.

---

*[pkg/util/fsm/fsm.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NKFen5caZFB-5t4e8:-L2NKFen5caZFB-5t4e9:b-s10lxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc4c8924b7b6437c942268182ca52ad017f5aa0d/pkg/util/fsm/fsm.go#L24)):*
> ```Go
> // declaring this literal, be careful to not declare two equal keys: they'll
> // result in the second overwriting the first with no warning. Note that keys
> // that are not technically equal, but where one is a superser of the other,
> ```

`s/superser/superset/`

---

*[pkg/util/fsm/fsm.go, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NKr1G9X_UhnJJqAK9:-L2NKr1G9X_UhnJJqAKA:b-9hwri7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc4c8924b7b6437c942268182ca52ad017f5aa0d/pkg/util/fsm/fsm.go#L168)):*
> ```Go
> 
> // GetCurState returns the current state.
> func (m *Machine) GetCurState() State {
> ```

`s/GetCurState/CurState/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/util/fsm/debug.go, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NLEXEY6qR0hrn8EAQ:-L2RIQ_GBaoQRlJltDds:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1d685cd4bf162461735948f44953c49cf980cb/pkg/util/fsm/debug.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd return a `Transition` here.
</blockquote></details>

Done.

---

*[pkg/util/fsm/fsm.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NKaqzfKs_IKRf7t-H:-L2RHRHneXlQ4FvK2aHx:b5gmygf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc4c8924b7b6437c942268182ca52ad017f5aa0d/pkg/util/fsm/fsm.go#L23)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Expand this a bit to point out that this is an artifact of Go's map rules and not a result of something we do during pattern expansion.
</blockquote></details>

Done.

Also I've moved this to doc.go

---

*[pkg/util/fsm/fsm.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NKFen5caZFB-5t4e8:-L2RHR0Yqu8ssD5ywRzM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc4c8924b7b6437c942268182ca52ad017f5aa0d/pkg/util/fsm/fsm.go#L24)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/superser/superset/`
</blockquote></details>

Done.

---

*[pkg/util/fsm/fsm.go, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-L2NKr1G9X_UhnJJqAK9:-L2RHQIOhMvmurjSobaQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc4c8924b7b6437c942268182ca52ad017f5aa0d/pkg/util/fsm/fsm.go#L168)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/GetCurState/CurState/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21180#-:-L2RJdpaWQrZLbtMv8SS:bnfp4nl)*

**Pull request merged**
