### PR TITLE
colexec: add optimized support of "contains" LIKE match

### PR DESCRIPTION
**Pull request by clucle**
Previously, Like matching has "prefix" match(test%) and "suffix" match(%test).

This commit adds "contains" match (%test%) using bytest.Contains function.

Release note (sql change): Add support for "contains" match(%test%) using bytes.Contains function

### CODE REVIEW

**Comment by clucle** [comment]
bors r=yuzefovich

**Review by yuzefovich — APPROVED** [review]
Thanks for working on this! I have a nit, but otherwise the code LGTM.

Note that bors is our "merging bot", and only authorized developers can actually merge the code. I'll merge it once you address the nit.

I think it's also worth adding a release note in the commit message and the PR description.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51598#-:-MCgtaUF29x0kWfgAPK9:bjuljo0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @clucle)

___
*[pkg/sql/colexec/like_ops.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51598#-MCgtBPK3Venr-Ao7ipj:-MCgtBPL-ZP2sncPzw5q:b-3gxrxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/276dd82713a37572a565acd4c282780e2a627d44/pkg/sql/colexec/like_ops.go#L38)):*
> ```Go
> 	likeRegexp
> 	likeRegexpNegate
> 	likeContains
> ```

nit: I'd move newly defined values above `likeRegexp` because that is the "default" slow case. The same goes for all code additions ("prefix", "suffix", and "contains" are alike, so they should be grouped together).

**Review by yuzefovich — APPROVED** [review]
Thanks!

bors r=yuzefovich

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51598#-:-MCiS_dt5BNguCTn2aLl:b6az1yq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
bors r-

One tests needs to be updated.

**Comment by yuzefovich** [comment]
Hey @clucle, I was trying to fix up your commit (I needed simply to rebase on top of the current master of cockroach and run `make testbaselogic FILES=tpch_vec TESTFLAGS='-rewrite'` to update `tpch_vec` logic test - the update was necessary because the plan has just been changed), but it appears because you were merging from your master, the PR got automatically closed, and I can't seem to fix it. Do you mind opening up a new PR? Sorry about this.

**Comment by yuzefovich** [comment]
I pushed amended commit to https://github.com/yuzefovich/cockroach/tree/clucle_master

**Comment by clucle** [comment]
I'll open a new PR after work 😄

**Pull request closed without merging**
