### PR TITLE
logictest: add local-mixed-22.2-23.1 to default configs

### PR DESCRIPTION
**Pull request by rafiss**
This will help catch mixed version bugs. Ever since 4424f869 was merged, this config will use the v22.2 system schema while operating with a v23.1 binary.

Epic: None
Release note: None

### CODE REVIEW

**Comment by knz** [comment]
filed #100609

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rafiss)

___
*[`pkg/sql/sqlitelogictest/tests/local-mixed-22.2-23.1/BUILD.bazel` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99866#-NSI4XgB4bN_RNChJyeQ:-NSI4XgB4bN_RNChJyeR:bjru5ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/34471dda670bdde363cc7b5d3d254bdc9c556c41/pkg/sql/sqlitelogictest/tests/local-mixed-22.2-23.1/BUILD.bazel#L5)):*
> ```Starlark
> 
> go_test(
>     name = "local-mixed-22_2-23_1_test",
> ```

Just double checking that you ran sqlite tests with this config too, right?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99866)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/sqlitelogictest/tests/local-mixed-22.2-23.1/BUILD.bazel` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99866#-NSI4XgB4bN_RNChJyeQ:-NSICQQk8Ujgh1yarZw_:b-z9gdag) ([raw file](https://github.com/cockroachdb/cockroach/blob/34471dda670bdde363cc7b5d3d254bdc9c556c41/pkg/sql/sqlitelogictest/tests/local-mixed-22.2-23.1/BUILD.bazel#L5)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Just double checking that you ran sqlite tests with this config too, right?
</blockquote></details>

yes, those tests passed

**Review by chengxiong-ruan — APPROVED** [review]
LGTM!

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by rafiss** [comment]
blathers backport 23.1

**Pull request merged**
