### PR TITLE
sql: add create_session_revival_token builtin

### PR DESCRIPTION
**Pull request by rafiss**
refs https://github.com/cockroachdb/cockroach/issues/74643

This builtin function will be used by sqlproxy in order to migrate
sessions from one sql node to another. The token will be used to
authenticate as the current user without using a password.

The builtin is only usable by tenants.

No release note since this is only meant to be used internally.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Nice.

> Reviewed 1 of 1 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-:-MtN48MeARnFcs4WbuTd:b-83sjo4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/base/config.go, line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtN3dV-4DHpoW9YPimQ:-MtN3dV-4DHpoW9YPimR:b-58vnal) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/base/config.go#L237)):*
> ```Go
> 	// AllowSessionRevival is true if the cluster is allowed to create session
> 	// revival tokens and use them to authenticate a session.
> 	AllowSessionRevival bool
> ```

What's the motivation to put this in `base.Config`, instead of just `server.Config` or `server.SQLConfig`?
___
*[pkg/sql/session_revival_token.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtN3mm47cqKqAkV80V8:-MtN3mm47cqKqAkV80V9:ba7ox21) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/sql/session_revival_token.go#L39)):*
> ```Go
> 		return nil, err
> 	}
> 	cert, err := cm.GetTenantSigningCert()
> ```

Please move this line and everything below to a suitable function/method in pkg/security (or perhaps a sub-package, if that's needed to prevent circular deps), thanks.
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 3149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtN42j49xxMhVmEddco:-MtN42j49xxMhVmEddcp:bb9qaxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/sql/logictest/testdata/logic_test/builtin_function#L3149)):*
> ```
> 
> # create_session_revival_token requires tenant-signing certs, so only work
> # in 3node-tenant. The token can't be tested for validity here, but we can
> ```

An idea: a SQL builtin function to check the token's signature? This way we can use in tests and also in demos.

**Comment by otan** [comment]
just a few minor suggestions

**Review by rafiss — COMMENTED** [review]
@otan i didn't see your suggestions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-:-MtiNWBP6fulLjX8rIgy:b-gfo8uv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[pkg/base/config.go, line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtN3dV-4DHpoW9YPimQ:-MtOatbT8iYWJo_PbcOH:b-fgsnss) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/base/config.go#L237)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What's the motivation to put this in `base.Config`, instead of just `server.Config` or `server.SQLConfig`?
</blockquote></details>

ah i can move it. i originally had it here since i was hoping to avoid needing to add it in ExecCfg
___
*[pkg/sql/session_revival_token.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtN3mm47cqKqAkV80V8:-MtOb2B97RXiC5t9W7aS:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/sql/session_revival_token.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please move this line and everything below to a suitable function/method in pkg/security (or perhaps a sub-package, if that's needed to prevent circular deps), thanks.
</blockquote></details>

done
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 3149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtN42j49xxMhVmEddco:-MtOb3080hcMfZS_Dxz9:b-rlht68) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/sql/logictest/testdata/logic_test/builtin_function#L3149)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

An idea: a SQL builtin function to check the token's signature? This way we can use in tests and also in demos.
</blockquote></details>

nice call. done

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[pkg/sql/sessiondatapb/session_revival_token.proto, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtdpY-m9mUiO1EdeOko:-MtdpY-m9mUiO1EdeOkp:bexvi8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/sql/sessiondatapb/session_revival_token.proto#L24)):*
> ```protobuf
>     string user = 1;
>     // The algorithm used to sign the payload. Can be either Ed25519 or RSA.
>     string algorithm = 2;
> ```

can we make this an enum?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[pkg/security/sessionrevival/session_revival.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-Mtiv71a0GdpBSilzwgv:-Mtiv71a0GdpBSilzwgw:b-ohkxxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/78834c8f1e9f3d870877ed7e864d3df03c548ec4/pkg/security/sessionrevival/session_revival.go#L89)):*
> ```Go
> 	err = protoutil.Unmarshal(tokenBytes, token)
> 	if err != nil {
> 		return false, nil
> ```

it would be nice if these were all wrapped in a `pgcode` error explaining which field could not be validated.

**Comment by otan** [comment]
___
*[pkg/security/sessionrevival/session_revival.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-Mtiv71a0GdpBSilzwgv:-MtivHWB3MAW4iegyB8L:b-n5wowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/78834c8f1e9f3d870877ed7e864d3df03c548ec4/pkg/security/sessionrevival/session_revival.go#L89)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it would be nice if these were all wrapped in a `pgcode` error explaining which field could not be validated.
</blockquote></details>

(would also have nice unit tests!)

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 3183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtivRTs0Dw7BkhG86U9:-MtivRTs0Dw7BkhG86UA:b-58z9h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/78834c8f1e9f3d870877ed7e864d3df03c548ec4/pkg/sql/logictest/testdata/logic_test/builtin_function#L3183)):*
> ```
>   crdb_internal.validate_session_revival_token(a.token || 'abc'::bytes)
> FROM
>   c, a;
> ```

nit: omit trailing semicolon

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[pkg/security/sessionrevival/session_revival.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-Mtiv71a0GdpBSilzwgv:-Mtj_Ffr0eqAhYgmqjtj:bp98sce) ([raw file](https://github.com/cockroachdb/cockroach/blob/78834c8f1e9f3d870877ed7e864d3df03c548ec4/pkg/security/sessionrevival/session_revival.go#L89)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(would also have nice unit tests!)
</blockquote></details>

hm, well i actually wanted all of these to return `false` rather than an error (as per above comment). i don't think the end user should ever really care about the contents of the token. also the pgcode wouldn't help with tests anyway, since the builtin doesn't ever allow you to construct an invalid token.

but unit tests are good -- i'll add those in the code.
___
*[pkg/sql/sessiondatapb/session_revival_token.proto, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtdpY-m9mUiO1EdeOko:-MtjYCT4BSLBFyIuA63V:b-uig53h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/sql/sessiondatapb/session_revival_token.proto#L24)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we make this an enum?
</blockquote></details>

hm, it'd require another layer of translation in the token creation code which we'd have to remember to update if we support additional algorithms. e.g.

```
var algToEnum = map[x509.PublicKeyAlgorithm]sessiondatapb.SessionRevivalToken_Algorithm{
	x509.Ed25519: sessiondatapb.SessionRevivalToken_Ed25519,
	x509.RSA:     sessiondatapb.SessionRevivalToken_RSA,
}

// and then later use it with
algToEnum[cert.PublicKeyAlgorithm]
```

 i'm not sure how much value we get out of an enum - but open to hearing why we should go for it
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 3183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtivRTs0Dw7BkhG86U9:-Mtj_Cuq3_U0wDc5Y1Uh:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/78834c8f1e9f3d870877ed7e864d3df03c548ec4/pkg/sql/logictest/testdata/logic_test/builtin_function#L3183)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: omit trailing semicolon
</blockquote></details>

done

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[pkg/security/sessionrevival/session_revival.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-Mtiv71a0GdpBSilzwgv:-MtkN6YL7wWe_lG7ctJm:b3m16fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/78834c8f1e9f3d870877ed7e864d3df03c548ec4/pkg/security/sessionrevival/session_revival.go#L89)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, well i actually wanted all of these to return `false` rather than an error (as per above comment). i don't think the end user should ever really care about the contents of the token. also the pgcode wouldn't help with tests anyway, since the builtin doesn't ever allow you to construct an invalid token.

but unit tests are good -- i'll add those in the code.
</blockquote></details>

i'd rather at the very least this validate return an error (maybe a typed error), we could potentially have a `invalid_token_reason` builtin if we want the reason. i think it'd be useful in debugging for sure.
___
*[pkg/sql/sessiondatapb/session_revival_token.proto, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-MtdpY-m9mUiO1EdeOko:-MtkNI2d71XPhE28V65L:b-2hihjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a667393540c3db9bd93df3c3c29605f32fedcefa/pkg/sql/sessiondatapb/session_revival_token.proto#L24)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, it'd require another layer of translation in the token creation code which we'd have to remember to update if we support additional algorithms. e.g.

```
var algToEnum = map[x509.PublicKeyAlgorithm]sessiondatapb.SessionRevivalToken_Algorithm{
	x509.Ed25519: sessiondatapb.SessionRevivalToken_Ed25519,
	x509.RSA:     sessiondatapb.SessionRevivalToken_RSA,
}

// and then later use it with
algToEnum[cert.PublicKeyAlgorithm]
```

 i'm not sure how much value we get out of an enum - but open to hearing why we should go for it
</blockquote></details>

constrains the list of values, but not fussed

**Review by knz — APPROVED** [review]
This is very nice.

@catj-cockroach do you also want to have a look at the token generation code, to double check we're not embedding an oopsie by accident.

> Reviewed 6 of 10 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-:-MtmGtLV3bqzyWW592RH:b-w6rdw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[pkg/security/sessionrevival/session_revival.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74823#-Mtiv71a0GdpBSilzwgv:-Mtn4rRC1h7GOpqOr3Oe:b-7gkyw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/78834c8f1e9f3d870877ed7e864d3df03c548ec4/pkg/security/sessionrevival/session_revival.go#L89)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i'd rather at the very least this validate return an error (maybe a typed error), we could potentially have a `invalid_token_reason` builtin if we want the reason. i think it'd be useful in debugging for sure.
</blockquote></details>

ok - this builtin is only used for testing anyway, so added errors

**Review by catj-cockroach — APPROVED** [review]
Looks good to me!

**Comment by rafiss** [comment]
thank you for all the reviews!

bors r=catj-cockroach,knz,otan

**Comment by rafiss** [comment]
bors r=catj-cockroach,knz,otan

**Comment by rafiss** [comment]
bors r=catj-cockroach,knz,otan

**Pull request merged**
