### PR TITLE
storage: refactor MVCCIterate to use iterutil.State

### PR DESCRIPTION
**Pull request by vrongmeal**
This pull request also makes a couple of other changes:

 - Fixes Allocator function in server package (0cd7ccd)
 - Adds StopE method for iterutil.Cur (13bf5c4)

Context: #48709

### CODE REVIEW

**Comment by vrongmeal** [comment]
@tbg tagging you for review

**Review by tbg — COMMENTED** [review]
Thanks! This looks good (better than before for sure) but I think I was asleep at the wheel when we discussed `StopE`. The responsibility for stopping the loop on error is now with each individual loop, not with the `iterutil.State`, where I think it ought to be (otherwise, we basically always have to invoke `StopE` when returning an error, which is 100% not intuitive, besides, all loops realistically will stop on error, so what is StopE for?)

I made a suggestion to address this below, see if you like it. Either way, `StopE` should go. If we just remove it, we are saying that it's up to each loop to handle errors as they see fit. I think that's ok as well, but the `Invoke` API is more well-rounded in that it wholly owns the decision to stop. Of course, it would not idiomatically support a loop that did want to continue past errors, but such a loop could simply *not* return the error from the closure, so its not worth optimizing for.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-:-MEbwOSm2cfDuM11rLwU:b-fpbgmf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @vrongmeal)

___
*[pkg/kv/kvserver/replica_raftstorage.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MEbtQyd9mr9dRyFEEeY:-MEbtQyd9mr9dRyFEEeZ:b-2npbqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7ec82b442236e40f9ea537c8a68e99663c8a47/pkg/kv/kvserver/replica_raftstorage.go#L152)):*
> ```Go
> 				)
> 				if err != nil {
> 					return cur.StopE(err)
> ```

Looking at this again, there is no way we would ever want to continue through an error, right? Can't we remove `StopE` again and say that if an error is returned, the iteration stops automatically? Surely the old code didn't just continue iterating?
___
*[pkg/kv/kvserver/store.go, line 1342 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MEbtnJK3YQAlx0_gS6G:-MEbtnJK3YQAlx0_gS6H:by72ufk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7ec82b442236e40f9ea537c8a68e99663c8a47/pkg/kv/kvserver/store.go#L1342)):*
I think you could even avoid the `var desc` above and instead do

`kv.Value.GetProto(iterState.Elem.(*roachpb.RangeDescriptor)`

Hmm, ok, let's not do that - the closure we invoke in `(*Store).Start` actually holds on to the descriptor. Leave the code as is but add a comment above `var desc` saying something like

> // NB: each iteration gets its own RangeDescriptor since, at the time of writing, some uses of this code hold on to the descriptor.
___
*[pkg/storage/mvcc.go, line 2660 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MEbvEuHAY9kis46sXrg:-MEbvEuHAY9kis46sXrh:btj1lcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7ec82b442236e40f9ea537c8a68e99663c8a47/pkg/storage/mvcc.go#L2660)):*
> ```Go
> 		for i := range res.KVs {
> 			*iterState.Elem.(*roachpb.KeyValue) = res.KVs[i]
> 			if err := f(iterState.Current()); err != nil {
> ```

Perhaps the API does not another round of polish. For example, the err and done checks could be merged:

```go
if err := iterState.Invoke(f); iterState.Done() {
  return err
}

func (s *State) Invoke(f func(Cur) error) error {
  err := f(s.Cur())
  if err != nil {
    s.done = true
  }
  return err
}
```

**Review by vrongmeal — COMMENTED** [review]
`Invoke` does seem like a better option. I'll remove `StopE`.

Should we rather not return error from `Stop`. The point of having this was to be able to stop before returning from the function, iirc. So it completely leaves it to the closure handle error.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-:-MEdFVZQ26t2-7RSy9mA:bn8jxjl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/replica_raftstorage.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MEbtQyd9mr9dRyFEEeY:-MEdEa9Z4R1V5U0hmkbz:bkkf7aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7ec82b442236e40f9ea537c8a68e99663c8a47/pkg/kv/kvserver/replica_raftstorage.go#L152)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Looking at this again, there is no way we would ever want to continue through an error, right? Can't we remove `StopE` again and say that if an error is returned, the iteration stops automatically? Surely the old code didn't just continue iterating?
</blockquote></details>

Yeah it didn't. Basically earlier the code was:

```go
cur.Stop()
return err
```
___
*[pkg/kv/kvserver/store.go, line 1342 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MEbtnJK3YQAlx0_gS6G:-MEdFBSz6Wb3UAs6lQsC:bb71kmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7ec82b442236e40f9ea537c8a68e99663c8a47/pkg/kv/kvserver/store.go#L1342)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think you could even avoid the `var desc` above and instead do

`kv.Value.GetProto(iterState.Elem.(*roachpb.RangeDescriptor)`

Hmm, ok, let's not do that - the closure we invoke in `(*Store).Start` actually holds on to the descriptor. Leave the code as is but add a comment above `var desc` saying something like

> // NB: each iteration gets its own RangeDescriptor since, at the time of writing, some uses of this code hold on to the descriptor.
</blockquote></details>

Okay
___
*[pkg/storage/mvcc.go, line 2660 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MEbvEuHAY9kis46sXrg:-MEdFQtX4Y8SNXHNOGrC:b44egm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7ec82b442236e40f9ea537c8a68e99663c8a47/pkg/storage/mvcc.go#L2660)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Perhaps the API does not another round of polish. For example, the err and done checks could be merged:

```go
if err := iterState.Invoke(f); iterState.Done() {
  return err
}

func (s *State) Invoke(f func(Cur) error) error {
  err := f(s.Cur())
  if err != nil {
    s.done = true
  }
  return err
}
```
</blockquote></details>

Yeah, this seems much better!

**Comment by vrongmeal** [comment]
On second thought, I don't think it's a good idea to write the `Invoke` method. In most cases, to check for both error and done, one can do:

```go
if err := f(iterState.Current()); err != nil || iterState.Done() {
	return err
}
```

It still feels more intuitive to let the closure declares if it wants to stop the iteration and gives freedom to the parent function to decide to stop/continue on error.

**Comment by vrongmeal** [comment]
@tbg Updated the PR. I did not add the `Invoke` method, which seemed confusing for someone using the iterutil package.

**Review by tbg — COMMENTED** [review]
Thanks! I probably didn't explain it properly, but I feel very strongly that the pattern

```go
c.Stop()
return err
```

should be avoided as it makes the mistake

```go
if err != nil {
  c.Stop()
}
// do more stuff
```

more likely. I *think* your intent is now to basically never use `c.Stop()` when there is an error, right? I would be on board with that, but please remove the redundant `c.Stop()` calls.

I'm tempted to make another suggestion, which is removing `c.Stop()`. If we make the assumption that almost all of the time, the loop should visit all elements unless an `error` is returned, `c.Stop()` invites more problems than it solves. Instead, the few loops that do want it, can use a signal error instead. What do you think? In code this could mean having

```go
c.Stop()
return nil
```

replaced by

```go
return iterutil.Break
```

which then of course the loop impl needs to handle (this would not be an issue with `Invoke`, but I understand that `Invoke` has its own problems).

> Reviewed 15 of 15 files at r4, 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-:-MF028zF2Er_uRumYjND:b-9sp5w7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vrongmeal)

___
*[pkg/kv/kvserver/replica_raftstorage.go, line 152 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MF04FyQ9V-1sLEuT2tc:-MF04FyQ9V-1sLEuT2td:b-xkr56f) ([raw file](https://github.com/cockroachdb/cockroach/blob/077d97a69814230af5a23a32bd1fa327c602b177/pkg/kv/kvserver/replica_raftstorage.go#L152)):*
> ```Go
> 				)
> 				if err != nil {
> 					cur.Stop()
> ```

Is this necessary? We stop on error, right?
___
*[pkg/storage/mvcc.go, line 2661 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52764#-MF05E466qT-Ewh-FJR1:-MF05E466qT-Ewh-FJR2:b-fv72iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/077d97a69814230af5a23a32bd1fa327c602b177/pkg/storage/mvcc.go#L2661)):*
> ```Go
> 			*iterState.Elem.(*roachpb.KeyValue) = res.KVs[i]
> 			if err := f(iterState.Current()); err != nil {
> 				return nil, err
> ```

so if MVCCIterate returns on error (as I hoped it would) nobody using it needs to be using `c.Stop()`, except to terminate early.

**Comment by vrongmeal** [comment]
This is what I suggested in [this comment](https://github.com/cockroachdb/cockroach/issues/48709#issuecomment-662978322), i.e., to return an error that signifies that the loop should break.

Also, a follow-up, if we do go with this approach (of returning an error to signify), we can remove the iterutils package (State and Cur) and just have an error and a function to check if error just means we need to stop the loop as suggested in the aforementioned comment.

**Comment by tbg** [comment]
@ajwerner just had the same thought over in #48709 and I think that makes sense. In the original response to your suggestion,

> One problem with the approach is that the sentinel error ErrStopIteration isn't easily discoverable, i.e. if you want to stop early you may have to poke around to learn how to do so. Instead, we could make it such that the closures passed to the iteration get a signature of the kind

I was basically completely off-base as we shouldn't optimize for the uncommon case of aborting a loop early. My apologies for sending you down an ultimately undesirable road.

**Comment by vrongmeal** [comment]
Closing this PR in favour of new sentinel error approach.

**Pull request closed without merging**
