### PR TITLE
test: add datadriven tests to sql api

### PR DESCRIPTION
**Pull request by maryliag**
Previously, the tests for the sql api was not using data driven tests, making the test itself hard to read.
This commit replace the total latency test with a data driven one. It creates a default file to insert data which can be used be the other tests on the same file.

A following PR will update the remaining tests on this file.

Part Of CRDB-35217

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117579)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @maryliag)

___
*[`pkg/server/application_api/testdata/combined_stmts_api` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nny_GpH9q_v7epqA92V:-Nny_GpH9q_v7epqA92W:b6ftcvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/combined_stmts_api#L4)):*
> ```
> # Start January 1, 2024 10:00:00
> # End January 1, 2024 10:20:00
> check-total-latency start=1704103200 end=1704104400
> ```

Seeing these test cases in isolation makes me think that the test cases should be merged in with them instead of being in a separate fixture.
For instance, your comments are now coupled with the fixtures and could drift easily.

Or perhaps you can come up with a DSL that tells a better "story" here.
For instance:

insert-stmt-stats x y z ts=a
insert-stmt-stats d e f ts=b
check-total-latency start=a end=b

Also, can we just take the "pretty" dates as arguments and parse them into the numbers in the case? Then you don't have to use the comments to explain.
___
*[`pkg/server/application_api/testdata/combined_stmts_api` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nny_7A_ApcQnf2WKl1F:-Nny_7A_ApcQnf2WKl1G:bors04s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/combined_stmts_api#L6)):*
> ```
> check-total-latency start=1704103200 end=1704104400
> ----
> Error: , Source table: crdb_internal.statement_statistics_persisted, Statements count: 1, Total latency: 3
> ```

Can you split output between Error and success? Reading `Error: ,` as a prefix on every test case is a bit odd. If the output is just the error, it will cause a mismatch anyway.
___
*[`pkg/server/application_api/testdata/sql_stats_default` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NnyaCoc6aC5SGzXIjg3:-NnyaCoc6aC5SGzXIjg4:bffmnzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/sql_stats_default#L44)):*
> ```
>   '{"Children": [], "Name": ""}',
>   ARRAY[]
> ),
> ```

Can this be simplified into a few args that "matter" for our tests? The entire SQL query is very heavy here and doesn't help with understanding the important parts of the entry.
___
*[`pkg/server/application_api/sql_stats_test.go` line 1476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nnyahe74wbhewawVSL9:-Nnyahe74wbhewawVSLA:b-ab46p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/sql_stats_test.go#L1476)):*
> ```Go
> 				db.Exec(t, strings.ReplaceAll(d.Input, "\n", ""))
> 				fmt.Fprintf(&buf, "")
> 			case "run-sql-select-count":
> ```

this command is too specific given that it takes arbitrary SQL input. can't we just check the output on the regular `run` statement? do we have access on execution of the number of rows inserted that we can check against?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117579)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/application_api/testdata/combined_stmts_api` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nny_GpH9q_v7epqA92V:-NnytNzM4iY23Yoe2fu2:b2qip2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/combined_stmts_api#L4)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Seeing these test cases in isolation makes me think that the test cases should be merged in with them instead of being in a separate fixture.
For instance, your comments are now coupled with the fixtures and could drift easily.

Or perhaps you can come up with a DSL that tells a better "story" here.
For instance:

insert-stmt-stats x y z ts=a
insert-stmt-stats d e f ts=b
check-total-latency start=a end=b

Also, can we just take the "pretty" dates as arguments and parse them into the numbers in the case? Then you don't have to use the comments to explain.
</blockquote></details>

I'm using the same fixture for all the tests on this same file. The options are:
1- Keep one fixture and use on multiple tests, and have extra test files for each specific test area
2 - Each test load its own fixture, with duplicated code, and run its tests

I went with option 1, but you're saying it should be option 2?

and yes, I can update the dates to use the "pretty" format instead
___
*[`pkg/server/application_api/testdata/combined_stmts_api` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nny_7A_ApcQnf2WKl1F:-Nnytmwr64xW8D71mK9e:b1qz07z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/combined_stmts_api#L6)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you split output between Error and success? Reading `Error: ,` as a prefix on every test case is a bit odd. If the output is just the error, it will cause a mismatch anyway.
</blockquote></details>

I have done this on my following PR, so let me add that change to this commit aswell
___
*[`pkg/server/application_api/testdata/sql_stats_default` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NnyaCoc6aC5SGzXIjg3:-NnytusYEL3wViA4BGsK:b-nkiqac) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/sql_stats_default#L44)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can this be simplified into a few args that "matter" for our tests? The entire SQL query is very heavy here and doesn't help with understanding the important parts of the entry.
</blockquote></details>

Several of those will make the api fail if non-existing, because it expects something. Also my idea behind it was to use this as the default for several tests, so each one might be checking different things. Which is the option 1 from me previous message

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117579)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/application_api/sql_stats_test.go` line 1476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nnyahe74wbhewawVSL9:-NnzZQ7v9l0VJwhjDa-2:b-82e0f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/sql_stats_test.go#L1476)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

this command is too specific given that it takes arbitrary SQL input. can't we just check the output on the regular `run` statement? do we have access on execution of the number of rows inserted that we can check against?
</blockquote></details>

removed this command and use only the run-sql and return the results
___
*[`pkg/server/application_api/testdata/combined_stmts_api` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nny_7A_ApcQnf2WKl1F:-NnzZVyUDh7-HsH8ZudZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/combined_stmts_api#L6)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I have done this on my following PR, so let me add that change to this commit aswell
</blockquote></details>

done

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117579)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/application_api/testdata/combined_stmts_api` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nny_GpH9q_v7epqA92V:-NoDHkgIEE_RECZRg9Rd:b-c5ewkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/combined_stmts_api#L4)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm using the same fixture for all the tests on this same file. The options are:
1- Keep one fixture and use on multiple tests, and have extra test files for each specific test area
2 - Each test load its own fixture, with duplicated code, and run its tests

I went with option 1, but you're saying it should be option 2?

and yes, I can update the dates to use the "pretty" format instead
</blockquote></details>

To better understand why I want this default populate, here is a following PR that uses those same fixtures on another test: https://github.com/cockroachdb/cockroach/pull/117790

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117579)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @maryliag)

___
*[`pkg/server/application_api/testdata/sql_stats_default` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NnyaCoc6aC5SGzXIjg3:-NoHt20FCv4wNtIQZU94:b-rjuevg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/sql_stats_default#L44)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Several of those will make the api fail if non-existing, because it expects something. Also my idea behind it was to use this as the default for several tests, so each one might be checking different things. Which is the option 1 from me previous message
</blockquote></details>

I understand all the args are necessary, but can they be inserted by the test runner instead of appearing here? What I'm trying to understand, that the current setup makes a bit challenging, is how to match up these inputs with the output expectations in `combined_stmts_total_latency`. Which numbers are supposed to add up there? Is there any way to make that easier to follow?
___
*[`pkg/server/application_api/sql_stats_test.go` line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NoHtPV8-RI6WHRzTfxI:-NoHtPV905Mxc4sdf6Hb:b-rtsxv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeb55da539fae23a1e4fd60225f23f9886925d7e/pkg/server/application_api/sql_stats_test.go#L562)):*
> ```Go
> 			errorMsg := ""
> 			if err != nil {
> 				errorMsg = err.Error()
> ```

You can return `errorMsg` here and the test will fail when the error is generated
___
*[`pkg/server/application_api/sql_stats_test.go` line 564 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NoHtVqV-TW0Nm8N-ALm:-NoHtVqV-TW0Nm8N-ALn:b-vw829q) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeb55da539fae23a1e4fd60225f23f9886925d7e/pkg/server/application_api/sql_stats_test.go#L564)):*
> ```Go
> 				errorMsg = err.Error()
> 			}
> 			fmt.Fprintf(&buf, "Error: %s\n", errorMsg)
> ```

no need to output this line on every case

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117579)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/application_api/testdata/sql_stats_default` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NnyaCoc6aC5SGzXIjg3:-NoIW61p4jzKbsx1-q3u:b-ukx27u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/sql_stats_default#L44)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I understand all the args are necessary, but can they be inserted by the test runner instead of appearing here? What I'm trying to understand, that the current setup makes a bit challenging, is how to match up these inputs with the output expectations in `combined_stmts_total_latency`. Which numbers are supposed to add up there? Is there any way to make that easier to follow?
</blockquote></details>

the values being generated/inserted by the test runner is how things are currently, and it was deemed confusing, so I moved the values to this insert here.
All those stats need to be generated one way or another, I know is a long list, but the names are straight forward, so they shouldn't be complex to read. 

If we want to have to test runner to decide the values and then insert, I think it will be messy to mix the data driven with the creation of the insert, so I would rather no use the data driven in this case. 
One option would be to keep the insert as is, even though is required a lot of lines of code, and only have the data driven tests for the api calls.

I can't think of another solution that would make this easier to read. I can always add more comments if that would help.

**Review by abarganier — COMMENTED** [review]
Looking good, just a couple small tweaks and we're ready to ship! :ship: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-:-NpuGdRgCksvHnqZ7zTc:bs7urkm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/server/application_api/testdata/sql_stats_default` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NnyaCoc6aC5SGzXIjg3:-NpuCVjm2W0Po0YUuVFN:b-8jnb6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/testdata/sql_stats_default#L44)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the values being generated/inserted by the test runner is how things are currently, and it was deemed confusing, so I moved the values to this insert here.
All those stats need to be generated one way or another, I know is a long list, but the names are straight forward, so they shouldn't be complex to read. 

If we want to have to test runner to decide the values and then insert, I think it will be messy to mix the data driven with the creation of the insert, so I would rather no use the data driven in this case. 
One option would be to keep the insert as is, even though is required a lot of lines of code, and only have the data driven tests for the api calls.

I can't think of another solution that would make this easier to read. I can always add more comments if that would help.
</blockquote></details>

Personally I think it's okay to have the full queries here, but I agree with David that it's a bit difficult to understand the intended set up here.

Comments sound like a good idea - can we write some info about the scenario that we set up with all the data inserted within this file? That way a curious reader can read that first for context, and the raw SQL will be easier to understand afterwards.
___
*[`pkg/server/application_api/sql_stats_test.go` line 1476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-Nnyahe74wbhewawVSL9:-NpuGbDf2uueMxlcpAcF:b-ubyqgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be8393916c65e886474f3889ce9f4ce5eb1764c/pkg/server/application_api/sql_stats_test.go#L1476)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

removed this command and use only the run-sql and return the results
</blockquote></details>

Thanks, lgtm. 
___
*[`pkg/server/application_api/sql_stats_test.go` line 564 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117579#-NoHtVqV-TW0Nm8N-ALm:-NpuFmIECsaBnSBqAl0p:bhd5twa) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeb55da539fae23a1e4fd60225f23f9886925d7e/pkg/server/application_api/sql_stats_test.go#L564)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

no need to output this line on every case
</blockquote></details>

I agree with David's idea here. If there's an error, just return `errorMsg` immediately so that the output is nothing but the error message.

In the case where we don't get an error, we can just include `Source table`, `Statements count`, and `Total latency`.

**Pull request closed without merging**
