### PR TITLE
UI: Changes the latency graph to show the max value per percentile

### LINKED ISSUE #5533: ui: make latency-max a true maxiumum
Currently it's the average of the maximum latency across all nodes.

### PR DESCRIPTION
**Pull request by maxlang**
This PR attempts to address the issue that averaging percentiles
is at best a bad practice and at worst very misleading. Instead
of averaging each percentile, we show the highest value across
all nodes.

fixes #5533 

screen shot 2016-04-19 at 4 13 32 pm

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6161)

### CODE REVIEW

**Comment by maxlang** [comment]
I put "do not merge" in the title because I felt this might be a little contentious.

**Comment by maxlang** [comment]
cc @jseldess

**Comment by tschottdorf** [comment]
I like it this way. Of course, the sweet spot (though of course that might
stretch what's possible) would be to show the individual nodes'
contributions to the maximum (or only the worst offender) when you hover
over a data point (i.e. you hover over a bad spike, and you see that
percentile's latency distribution, but by node).

On Tue, Apr 19, 2016 at 4:20 PM Max Lang <notifications@github.com> wrote:

> cc @jseldess <https://github.com/jseldess>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/6161#issuecomment-212109479>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Taking the max across nodes seems better than averaging. It is also more appropriate given your name.

Why does the tooltip say "estimated time"? Isn't the time that we're calculating the actual time between receiving the request and sending the response?

**Comment by cuongdo** [comment]
I think this has value. It is useful to see worst-case latencies in the
overview. To the Max!

**Comment by maxlang** [comment]
It currently isn't available from the backend, but perhaps the max and min downsamplers could provide a second set of information indicating a node for each datapoint (not guaranteed to be the only node with that value of course.)

eg

```
  "datapoints": [
        {
          "timestamp_nanos": ...,
          "value": 300,
          "node_id": 1
        },
        {
          "timestamp_nanos": ...,
          "value": 350,
          "node_id": 3
        },
...
```

I'll open an issue to discuss.

**Comment by maxlang** [comment]
@petermattis Good point - I think estimated was just one way of trying to sugar-coat the average. Removed.

**Comment by tschottdorf** [comment]
> I'll open an issue to discuss.

For that issue (don't see it yet): or the top3 `(NodeID, Value)` pairs along (to have some more relevant information to display).

I think it also makes sense to have graphs somewhere (node graphs page?) that, for a single percentile, plot all the nodes (on node X's page, would probably grey out all of the other nodes so that it's obvious which line belongs to X).

**Comment by jseldess** [comment]
@maxlang, I've been trying to rework the tooltip following your in-person explanation yesterday. It's hard to explain exactly what we're doing in the space of a tooltip. I think it'll be easier in the docs. But here are some suggestions.

**If we don't want to explain the method too much:**
For each latency percentile, the max time between query requests and responses over a 10 second period across all nodes. 

**If we want the method to be in here:**
The latency between query requests and responses, in milliseconds, over a 10 second period. Percentiles are first calculated on each node. For each percentile, the maximum latency across all nodes is then shown.

For the graph title, I don't think we should overload it with a parenthetical. I'd stick with just "Query Time" or "Query Time Percentiles".

Also, for each percentile, since we're showing the highest from just one particular node (the node with the highest time for that percentile), it seems like the user might want to know which node is being shown so as to troubleshoot that node. Perhaps just adding a Query Time graph at the node level would be enough? Maybe this is what @thschroeter has suggested already...

**Comment by maxlang** [comment]
@tschottdorf just opened the issue here #6177

**Comment by maxlang** [comment]
Worked with @jseldess on the wording for clarity. I also added the latency graph to the individual nodes page. I'll add a page to compare graphs across nodes in a separate PR.

screen shot 2016-04-20 at 6 12 41 pm
screen shot 2016-04-20 at 6 12 33 pm

**Comment by mrtracy** [comment]
Reviewed 7 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/ts/models/metrics.ts, line 187 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6161#-KFtxR3kT1swvgzx0gDf:-KFtxR3kT1swvgzx0gDg:1725892815) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7e4ed18ef65911f6b4af10acd78680b67f1107/ui/ts/models/metrics.ts#L187)):*
You also need to set the "aggregator" to Max - not just the downsampling function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6161)*

**Comment by maxlang** [comment]
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/ts/models/metrics.ts, line 187 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6161#-KFtxR3kT1swvgzx0gDf:-KFu55WzhYWprIuJInxJ:547803335) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc7e4ed18ef65911f6b4af10acd78680b67f1107/ui/ts/models/metrics.ts#L187)):*
Whoops, fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6161)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6161#-:-KFu5wlhdhIzYZ_3Uxjg:1417088721)*

**Pull request merged**
