### PR TITLE
eventpb: new JSON serialization with redaction markers

### LINKED ISSUE #45643: bulkio: provide visibility for events in debug logs
Customer request: provide visibility for cluster level events in the logs. We're already recording these cluster level events in the `system.events` table, and exposing them in the UI, but the customer wants to tail logs. Their ideal is for the `system.events` rows to be replicated in every node's logs in case one or more of the nodes are down.

This doesn't really fall under any team's ownership, but I'm taking Bulk I/O because jobs are one of the more frequent creators of events.

### PR DESCRIPTION
**Pull request by knz**
Fixes  #45643

All commits but the last from  #58070 and prior 
This is a prereq for presenting structured events "inline" in  #57170. 

This patch introduces a new code generator and infrastructure to emit
structured event payloads using the JSON syntax, but also including
redaction markers for fields not marked explicitly as safe for
reporting.

This is not yet connected to the remainder of the logging system --
this change will be performed in a later commit.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
I am aware of a CI failure which is going to be fixed by a dep bump: https://github.com/cockroachdb/redact/pull/14

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 20 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57990#-:-MP52BVMExxG04RgfhCr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[docs/generated/eventlog.md, line 1241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57990#-MP5-j-t2Wdi_0KuCTHt:-MP5-j-t2Wdi_0KuCTHu:bdse0op) ([raw file](https://github.com/cockroachdb/cockroach/blob/e265fcf76187a7fa96eba4223c9dbc0f9ec2be0e/docs/generated/eventlog.md#L1241)):*
> ```Markdown
> ### Common fields
> 
> | Field | Description | Sensitive |
> ```

Is there room to clarify what `sensitive` means, somewhere near the top of this file? At first I was slightly confused as it could also mean "case sensitive" when in reality it's redaction/PII sensitive. Maybe I'm thinking too much, feel free to ignore this point.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57990)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[docs/generated/eventlog.md, line 1241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57990#-MP5-j-t2Wdi_0KuCTHt:-MP5Mx926iOVU55rkT22:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e265fcf76187a7fa96eba4223c9dbc0f9ec2be0e/docs/generated/eventlog.md#L1241)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Is there room to clarify what `sensitive` means, somewhere near the top of this file? At first I was slightly confused as it could also mean "case sensitive" when in reality it's redaction/PII sensitive. Maybe I'm thinking too much, feel free to ignore this point.
</blockquote></details>

Good idea. Done.

**Comment by knz** [comment]
TFYR!

bors r=itsbilal

**Pull request merged**
