### PR TITLE
opt: Allow reuse of optimizer

### PR DESCRIPTION
**Pull request by andy-kimball**
Allow the optimizer data structures to be reused for optimizing
multiple queries. Also, use a different data structure for detecting
rule cycles in order to save creation of a map.

before:
```
name                      time/op
Phases/kv-read/OptBuild   18.8µs ± 2%
Phases/kv-read/Normalize  18.8µs ± 1%
Phases/kv-read/Explore    24.5µs ± 3%
```
after:
```
Phases/kv-read/OptBuild   18.0µs ± 1%
Phases/kv-read/Normalize  17.8µs ± 3%
Phases/kv-read/Explore    23.1µs ± 2%
```

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-:-LK1_ySc1BLHr-vh9Tla:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_executor_exec.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_EOb7hWIQFMKEGGp:-LK1_EOb7hWIQFMKEGGq:b-5xymby) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/conn_executor_exec.go#L752)):*
> ```Go
> 
> 	optimizerPlanned, err := planner.optionallyUseOptimizer(ctx, ex.sessionData, stmt)
> 	//optimizerPlanned, err := false, error(nil)
> ```

Detritus?
___
*[pkg/sql/opt/xform/optimizer.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_iL5ErUGJsaamtIF:-LK1_iL5ErUGJsaamtIG:b2gyvjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/opt/xform/optimizer.go#L91)):*
> ```Go
> // must be called before the optimizer can be used (or reused).
> func (o *Optimizer) Init(evalCtx *tree.EvalContext) {
> 	o.evalCtx = evalCtx
> ```

It might be safer to leave this as:

```
*o = Optimizer{
  evalCtx: evalCtx,
  stateMap: ...
}
```

That way, if you add a new field to `Optimizer` you don't have to remember to clear it out below.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-:-LK1zqIi7krSWq-SoROv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28687)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/optimizer.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_iL5ErUGJsaamtIF:-LK2J2oY3jIXCwLbfEIg:bjqapqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/opt/xform/optimizer.go#L91)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It might be safer to leave this as:

```
*o = Optimizer{
  evalCtx: evalCtx,
  stateMap: ...
}
```

That way, if you add a new field to `Optimizer` you don't have to remember to clear it out below.
</blockquote></details>

But one of the main points of the change is to reuse fields that were allocated previously (like `stateAlloc`, and in the case of other helper classes, various "scratch" buffers). I know that the `Init` pattern makes code more fragile, and that's why I resisted doing it for so long, but to do what you suggest would give up one of the main benefits I'm looking to get from it...
___
*[pkg/sql/conn_executor_exec.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_EOb7hWIQFMKEGGp:-LK2K6p720ILEPlxGCA1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/conn_executor_exec.go#L752)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Detritus?
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28687)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/optimizer.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_iL5ErUGJsaamtIF:-LK2KJfY1WTFvKZw3fof:b-co1ubi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/opt/xform/optimizer.go#L91)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

But one of the main points of the change is to reuse fields that were allocated previously (like `stateAlloc`, and in the case of other helper classes, various "scratch" buffers). I know that the `Init` pattern makes code more fragile, and that's why I resisted doing it for so long, but to do what you suggest would give up one of the main benefits I'm looking to get from it...
</blockquote></details>

Ah, you're suggesting that I pass in existing fields to that constructor so that I retain the benefit I want to get. I see, OK.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28687)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/optimizer.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_iL5ErUGJsaamtIF:-LK2SnSj4OFfKPfnj3jY:b-ya18aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/opt/xform/optimizer.go#L91)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ah, you're suggesting that I pass in existing fields to that constructor so that I retain the benefit I want to get. I see, OK.
</blockquote></details>

Yep. Any field you want to keep you pass in to `Optimizer{...}`.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28687)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/optimizer.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_iL5ErUGJsaamtIF:-LK2T70e007WayXOoKOm:bivci2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/opt/xform/optimizer.go#L91)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yep. Any field you want to keep you pass in to `Optimizer{...}`.
</blockquote></details>

Yeah, but trouble is that several of those fields themselves require a call to `init`. If I copy them in, and then call init, I'm copying twice. Worse, those calls to `init` themselves have sub-fields that need calls to `init` for the same reason. So the same memory could be zero'd 4 times if there are 4 levels of init and I follow the `Optimizer{...}` pattern.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28687)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/optimizer.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28687#-LK1_iL5ErUGJsaamtIF:-LK2TypdENx0Gr87K8ae:b-8vdrrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ed1a2ded6158ee2cce1c0b80dcac3e018a3285/pkg/sql/opt/xform/optimizer.go#L91)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yeah, but trouble is that several of those fields themselves require a call to `init`. If I copy them in, and then call init, I'm copying twice. Worse, those calls to `init` themselves have sub-fields that need calls to `init` for the same reason. So the same memory could be zero'd 4 times if there are 4 levels of init and I follow the `Optimizer{...}` pattern.
</blockquote></details>

Ack. Leave as-is then.

**Pull request merged**
