### PR TITLE
colexec: wrap DrainMeta with panic-catcher and protect columnarizer

### LINKED ISSUE #62514: roachtest: sqlsmith: nil ctx when draining the vectorized flow
[(roachtest).sqlsmith/setup=rand-tables/setting=no-ddl failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2808064&tab=buildLog) on [release-21.1@23e7cb53bf5baede071832b59bd92ea8164531a6](https://github.com/cockroachdb/cockroach/commits/23e7cb53bf5baede071832b59bd92ea8164531a6):

```
The test failed on branch=release-21.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
	cluster.go:1667,context.go:140,cluster.go:1656,test_runner.go:848: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2808064-1616565608-14-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 4: 4961
		2: 5834
		3: dead
		1: 7159
		Error: UNCLASSIFIED_PROBLEM: 3: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 3: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=rand-tables/setting=no-ddl](https://teamcity.cockroachdb.com/viewLog.html?buildId=2808064&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Drand-tables%2Fsetting%3Dno-ddl.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: wrap DrainMeta with panic-catcher and protect columnarizer**

Previously, in some edge cases (like when a panic is encountered during
`Operator.Init`) the metadata sources could have been uninitialized, so
when we tried to drain them, we'd encounter a crash. In order to avoid
that in the future, now all root components will wrap the draining with
the panic-catcher. Additionally, we now protect the columnarizer in this
case explicitly - if it wasn't initialized, it won't drain the wrapped
processor in `DrainMeta`.

Fixes: #62514.

Release note: None

**rowexec: remove redundant implementations of MetadataSource interface**

Previously, some row-by-row processors implemented
`execinfra.MetadataSource` interface. The idea behind that originally
was to allow for wrapped processors to return their metadata in the
vectorized flow, but nothing explicit is actually needed because every
wrapped processor has a columnarizer after it which will drain the
processor according to row-by-row model (by moving into draining state
and exhausting the trailing meta). This commit removes those redundant
implementations.

This allows us to move the interface into `colexecop` package where it
belongs.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Note that the first commit fixes a GA-blocker (which I'm not sure whether it deserves such status), so I intend to backport the first commit to 21.1 branch (possibly for 21.1.0).

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, 30 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63108#-:-MXg7EDn4BFPlLY5Ss_e:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colflow/routers.go, line 640 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63108#-MXg3pcg2mygv4yGtHW5:-MXg3pcg2mygv4yGtHW6:b-uynwyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af7aeddc6e390ee3472013430aa0b3a8126692a/pkg/sql/colflow/routers.go#L640)):*
> ```Go
> 	if inputInitialized {
> 		// If we encountered a panic when initializing the input, the metadata
> 		// sources might be uninitialized, so we drain them only otherwise.
> ```

nit: "so we drain them only otherwise" -> "so we only drain them if initialized"
___
*[pkg/sql/colflow/routers.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63108#-MXg4Qnq8EF-y_k2MQW-:-MXg4Qnq8EF-y_k2MQW0:b-5hzpjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af7aeddc6e390ee3472013430aa0b3a8126692a/pkg/sql/colflow/routers.go#L643)):*
> ```Go
> 		// Although the DrainMeta call contains a panic-catcher, we would rather
> 		// not emit errors (which are likely to occur) in this case.
> 		r.bufferedMeta = append(r.bufferedMeta, r.metadataSources.DrainMeta(ctx)...)
> ```

is there no way to tell from the `metadataSources` directly whether they are initialized? Seems like this check could go inside the `DrainMeta` function (maybe before the panic catcher?)

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63108#-:-MXh34J-4uxFqx23FK4-:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @rytaft)

___
*[pkg/sql/colflow/routers.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63108#-MXg4Qnq8EF-y_k2MQW-:-MXh1VaR2PgEyenV81Kg:b-3slixb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af7aeddc6e390ee3472013430aa0b3a8126692a/pkg/sql/colflow/routers.go#L643)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is there no way to tell from the `metadataSources` directly whether they are initialized? Seems like this check could go inside the `DrainMeta` function (maybe before the panic catcher?)
</blockquote></details>

Good point. We already had protection in most places, and I updated the code to add the check to the columnarizer (the only place that I found to be missing the initialization check), so I removed this "input initialized" business.

Actually, doing just that should be sufficient to fix the issue, but I think that it is beneficial to keep the panic-catcher around draining for stability.

**Comment by yuzefovich** [comment]
A flake.

bors r+

**Pull request merged**
