### PR TITLE
jobs: protected timestamps refresh logic is not transactional

### LINKED ISSUE #92427: TestCCLLogic_regional_by_row  flaked on master
https://teamcity.cockroachdb.com/viewLog.html?buildId=7668792&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-21765

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #92427

Previously, the refresh logic for protected timestamps would fetch jobs with transactions before attempting to update an existing one. Due to a recent change to allow this API to reflect any changes into individual job objects, we no longer do that correctly. This patch fixes the protected timestamp manager to update timestamps in a transactionally, safe manner since multiple updates can be happening concurrently for schema changes.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
LGTM thanks!

**Comment by msbutler** [comment]
ooof, thanks for catching this!

**Comment by fqazi** [comment]
@ajwerner @msbutler TFTR!

**Pull request merged**
