### PR TITLE
opt: support projection in the exec builder

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding support for ProjectOp.

Splitting the test into multiple files, similar to the opt/build
tests.

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 107 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qh7nERTQAx_wvHTE9:-L4qh7nERTQAx_wvHTEA:b-zefb0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/executor_opt_interface.go#L107)):*
> ```Go
> 	for _, expr := range exprs {
> 		expr = r.ivarHelper.Rebind(expr, false /* alsoReset */, false /* normalizeToNonNil */)
> 		exprStr := symbolicExprStr(expr)
> ```

I thought `symbolicExprStr` printed the entire expression tree. Don't you just want a name for the column? How come that wouldn't come from col metadata (and eventually from physical props)?

---

*[pkg/sql/opt/exec/factory.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qhdrtGMVZGE1YESaF:-L4qhdrtGMVZGE1YESaG:b-k69qga) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/factory.go#L38)):*
> ```Go
> 	// ConstructProjection returns a node that applies a projection on the results
> 	// of the given input node.
> 	ConstructProjection(n Node, exprs tree.TypedExprs) (Node, error)
> ```

We use `ConstructProject` on the `opt` side. Is `ConstructProjection` better on the exec side, or does it not matter either way?

---

*[pkg/sql/opt/exec/build/testdata/project, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qiMcknLS3uam-UO2y:-L4qiMcknLS3uam-UO2z:b751llw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/project#L117)):*
> ```
> exec
> SELECT u + v FROM (SELECT x + 3, y + 10 FROM t.a) AS foo(u, v)
> ----
> ```

I'd add test cases for duplicate columns, aliased columns, hidden columns (table without primary key?).

---

*[pkg/sql/opt/exec/build/testdata/scan, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qiyxUX48ovAvnUdKW:-L4qiyxUX48ovAvnUdKX:bdw5u63) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/scan#L31)):*
> ```
> 1  1.0
> 2  2.0
> 3  3.0
> ```

I'd add a test case for hidden cols.

---

*[pkg/sql/opt/exec/build/testdata/select, line 69 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qjG5OdPEfsgZUAgtQ:-L4qjG5OdPEfsgZUAgtR:b-gyn39s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/select#L69)):*
> ```
> SELECT * FROM t.a WHERE x > 1 AND y < 30
> ----
> 2  20
> ```

I'd add a test case for hidden cols. Also, we're missing test cases for scalar exprs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 107 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qh7nERTQAx_wvHTE9:-L4ql0dikxoZxVnNFmdR:b-fkssy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/executor_opt_interface.go#L107)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I thought `symbolicExprStr` printed the entire expression tree. Don't you just want a name for the column? How come that wouldn't come from col metadata (and eventually from physical props)?
</blockquote></details>

Good question. I don't think these names matter for execution. But they do show up in the `exec-explain` output so what you suggest makes sense. Done.

---

*[pkg/sql/opt/exec/factory.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qhdrtGMVZGE1YESaF:-L4qkpSXRPDiRFuHqP4Y:b1iglol) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/factory.go#L38)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

We use `ConstructProject` on the `opt` side. Is `ConstructProjection` better on the exec side, or does it not matter either way?
</blockquote></details>

I think ProjectOp is a good name for the op, and ConstructProject follows from that. Renamed this to ConstructProject as well.

---

*[pkg/sql/opt/exec/build/testdata/project, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qiMcknLS3uam-UO2y:-L4qnbtu_lLc2g3UdAeA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/project#L117)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd add test cases for duplicate columns, aliased columns, hidden columns (table without primary key?).
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/build/testdata/scan, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qiyxUX48ovAvnUdKW:-L4qoVNucaofP8NB210g:b-2gqhb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/scan#L31)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd add a test case for hidden cols.
</blockquote></details>

Done. Note that I'm selecting `rowid` because this is a test for scan and not for the project.

---

*[pkg/sql/opt/exec/build/testdata/select, line 69 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qjG5OdPEfsgZUAgtQ:-L4qmPNLEsrhZ7KhiKiD:b-wp4daq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/select#L69)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd add a test case for hidden cols. Also, we're missing test cases for scalar exprs.
</blockquote></details>

Done. We can't execute scalar expressions..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 3 of 9 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/build/relational_builder.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qxRvM-V0CgSej6KcH:-L4qxRvM-V0CgSej6KcI:b-9hg0dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7291c60552113c4d154553ce5e2139c09bd76c/pkg/sql/opt/exec/build/relational_builder.go#L139)):*
> ```Go
> 	}
> 	ep := execPlan{root: node}
> 	for i := 0; i < len(exprs); i++ {
> ```

[nit] is there a reason you are using `for i := range exprs {` above and `for i := 0; i < len(exprs); i++ {` here?

---

*[pkg/sql/opt/exec/build/testdata/select, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qzhDsUBc_3T3zhXXm:-L4qzhDsUBc_3T3zhXXn:b-v7y6oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7291c60552113c4d154553ce5e2139c09bd76c/pkg/sql/opt/exec/build/testdata/select#L74)):*
> ```
> 
> exec-explain
> SELECT x FROM t.b WHERE rowid > 0
> ```

I think these are the only tests combining projection and filters. Maybe add some similar tests for the non-hidden columns case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-:-L4r-US_-ZBY6CcaWYy_:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 6 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/opt/exec/build/relational_builder.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qxRvM-V0CgSej6KcH:-L4r1QUuAfkfnMFqzFVr:b-vfkka4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7291c60552113c4d154553ce5e2139c09bd76c/pkg/sql/opt/exec/build/relational_builder.go#L139)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] is there a reason you are using `for i := range exprs {` above and `for i := 0; i < len(exprs); i++ {` here?
</blockquote></details>

No, fixed.

---

*[pkg/sql/opt/exec/build/testdata/select, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qzhDsUBc_3T3zhXXm:-L4r0wAdQNTMpLiE_Tfb:b-8yyf70) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7291c60552113c4d154553ce5e2139c09bd76c/pkg/sql/opt/exec/build/testdata/select#L74)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think these are the only tests combining projection and filters. Maybe add some similar tests for the non-hidden columns case?
</blockquote></details>

Added in the project file. Moved this there too, so that we don't have any projects in this file (left a testcae with hidden column and no project).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514)*

**Comment by rytaft** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/build/testdata/project, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qiMcknLS3uam-UO2y:-L4r5g7hQ0asoGoJ_O2P:b8g0q76) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/project#L117)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: looks good, but what about aliased columns? Like using AS in the project.

---

*[pkg/sql/opt/exec/build/testdata/select, line 69 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qjG5OdPEfsgZUAgtQ:-L4r5rB_R-ghaEVCtNao:b-6c8vu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/select#L69)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done. We can't execute scalar expressions..
</blockquote></details>

I mean testing various scalar expressions in the context of a project or a filter, in order to exercise the code in `scalarBuilder.go`. It doesn't matter that they aren't "at the top level".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514)*

**Comment by andy-kimball** [comment]
LGTM, but I would like to see tests for the functionality in `scalar_builder.go`. I'd test it by using the various scalar expression types in a project list or a filter condition (doesn't really matter what the "carrier" is). You can do that in a later PR, though, since it's not directly related to this PR.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-:-L4r6FVo3cwH2Tu_M-IB:b-qku92v)*

**Comment by RaduBerinde** [comment]
Makes sense. I'll do it in a separate PR.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/build/testdata/project, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-L4qiMcknLS3uam-UO2y:-L4rAEURLZVQsiej8zYK:bqux4tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c4d91e92d2d5e66e1bf33c9c6a64f8522c846ae/pkg/sql/opt/exec/build/testdata/project#L117)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

nit: looks good, but what about aliased columns? Like using AS in the project.
</blockquote></details>

I tried `SELECT u + v FROM (SELECT x + 3 AS u, y + 10 AS v FROM t.a)` but it doesn't build (`BuildOpt: unknown column u`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22514#-:-L4r9O8NbD9yZ-yX4mdS:b-jxt8e1)*

**Pull request merged**
