### PR TITLE
sql: assorted fixes for bugs found via TestRandomSyntaxGeneration

### LINKED ISSUE #95612: sql/tests: TestRandomSyntaxGeneration failed
sql/tests.TestRandomSyntaxGeneration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/8208463?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/8208463?buildTab=artifacts#/) on master @ [642afd6e8c8d1f967da4aa0c3c08e2bdc0495100](https://github.com/cockroachdb/cockroach/commits/642afd6e8c8d1f967da4aa0c3c08e2bdc0495100):

```
crypto/tls.(*atLeastReader).Read(0xc05661a8b8, {0xc04a583d40?, 0x0?, 0x389488168619053b?})
	GOROOT/src/crypto/tls/conn.go:787 +0x3d fp=0xc0339d0938 sp=0xc0339d08f0 pc=0x86799d
bytes.(*Buffer).ReadFrom(0xc0569a3078, {0x6c2e660, 0xc05661a8b8})
	GOROOT/src/bytes/buffer.go:202 +0x98 fp=0xc0339d0990 sp=0xc0339d0938 pc=0x565858
crypto/tls.(*Conn).readFromUntil(0xc0569a2e00, {0x6c3dd20?, 0xc04bd20b18}, 0x80deb1fe72be5d74?)
	GOROOT/src/crypto/tls/conn.go:809 +0xe5 fp=0xc0339d09d0 sp=0xc0339d0990 pc=0x867b85
crypto/tls.(*Conn).readRecordOrCCS(0xc0569a2e00, 0x0)
	GOROOT/src/crypto/tls/conn.go:616 +0x116 fp=0xc0339d0d58 sp=0xc0339d09d0 pc=0x864fd6
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).readHandshake(0xc0569a2e00)
	GOROOT/src/crypto/tls/conn.go:1019 +0x6d fp=0xc0339d0e38 sp=0xc0339d0d58 pc=0x868ded
crypto/tls.(*serverHandshakeStateTLS13).readClientCertificate(0xc0339d11c0)
	GOROOT/src/crypto/tls/handshake_server_tls13.go:787 +0x65 fp=0xc0339d10c0 sp=0xc0339d0e38 pc=0x8948e5
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc0339d11c0)
	GOROOT/src/crypto/tls/handshake_server_tls13.go:78 +0xb6 fp=0xc0339d10e0 sp=0xc0339d10c0 pc=0x890bb6
crypto/tls.(*Conn).serverHandshake(0xc0569a2e00, {0x6c75730, 0xc0569a0b00})
	GOROOT/src/crypto/tls/handshake_server.go:54 +0xd0 fp=0xc0339d12b8 sp=0xc0339d10e0 pc=0x88b550
crypto/tls.(*Conn).serverHandshake-fm({0x6c75730?, 0xc0569a0b00?})
	<autogenerated>:1 +0x39 fp=0xc0339d12e0 sp=0xc0339d12b8 pc=0x89f4d9
crypto/tls.(*Conn).handshakeContext(0xc0569a2e00, {0x6c75768, 0xc000080048})
	GOROOT/src/crypto/tls/conn.go:1462 +0x32f fp=0xc0339d14a8 sp=0xc0339d12e0 pc=0x86b6cf
crypto/tls.(*Conn).HandshakeContext(...)
	GOROOT/src/crypto/tls/conn.go:1405
crypto/tls.(*Conn).Handshake(...)
	GOROOT/src/crypto/tls/conn.go:1389
crypto/tls.(*Conn).Read(0xc0569a2e00, {0xc0569c4438, 0x4, 0x493f10?})
	GOROOT/src/crypto/tls/conn.go:1274 +0x65 fp=0xc0339d1518 sp=0xc0339d14a8 pc=0x86ab25
io.ReadAtLeast({0x7eff005e27f8, 0xc0569a2e00}, {0xc0569c4438, 0x4, 0x4}, 0x4)
	GOROOT/src/io/io.go:332 +0x9a fp=0xc0339d1560 sp=0xc0339d1518 pc=0x50ccba
io.ReadFull(...)
	GOROOT/src/io/io.go:351
github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgwirebase.(*ReadBuffer).ReadUntypedMsg(0xc0569c4420, {0x7eff005e27f8, 0xc0569a2e00})
	github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgwirebase/encoding.go:155 +0x65 fp=0xc0339d1720 sp=0xc0339d1560 pc=0x27e6c85
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).readVersion(0xc000cf23c0, {0x7eff005e27f8, 0xc0569a2e00})
	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1371 +0x127 fp=0xc0339d17a8 sp=0xc0339d1720 pc=0x38ce567
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).maybeUpgradeToSecureConn(0xc000cf23c0, {0x0?, 0xffc?}, {0x6cbb9a8, 0xc04bd20b18}, 0x2, 0x6c3dd20?, 0xc0339d1bc0)
	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1315 +0x35d fp=0xc0339d1878 sp=0xc0339d17a8 pc=0x38cdd9d
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc000cf23c0, {0x6c75730, 0xc056b06880}, {0x6cbb9a8?, 0xc04bd20b18}, 0x6a?)
	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:811 +0x59e fp=0xc0339d1e20 sp=0xc0339d1878 pc=0x38ca83e
github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).startServeSQL.func1.1({0x6c757d8?, 0xc0568207b0?}, {0x6cbb9a8, 0xc04bd20b18})
	github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1568 +0xc8 fp=0xc0339d1eb0 sp=0xc0339d1e20 pc=0x3b95648
github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1({0x6c757d8, 0xc0568207b0})
	github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:188 +0xc7 fp=0xc0339d1f30 sp=0xc0339d1eb0 pc=0x17d96a7
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146 fp=0xc0339d1fe0 sp=0xc0339d1f30 pc=0x10fdae6
runtime.goexit()
	GOROOT/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0339d1fe8 sp=0xc0339d1fe0 pc=0x4c4021
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #89363 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot T-sql-sessions branch-release-22.2.0]
- #87572 sql/tests: TestRandomSyntaxGeneration failed [DROP OWNED BY timeout] [C-test-failure O-robot T-sql-schema branch-release-22.2]
- #77893 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot T-sql-sessions branch-release-22.1]
- #74271 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot branch-release-21.2]
- #65210 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot branch-release-21.1]
</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxGeneration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23617

### PR DESCRIPTION
**Pull request by knz**
Fixes #95612.

See the individual commits for details.

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Thanks for jumping on these.

In the commit message for "sql: avoid a RSG error on tenant specs containing a cast", it may help those less familiar with this part of the system (read: me) to add a sentence or two more. Namely, I'm interested in why we need need to explicitly parenthesis things in `(*TenantSpec).Format)` while other tree nodes that contain Expr's don't.

**Comment by knz** [comment]
> In the commit message for "sql: avoid a RSG error on tenant specs containing a cast", it may help those less familiar with
> this part of the system (read: me) to add a sentence or two more. Namely, I'm interested in why we need need to
> explicitly parenthesis things in (*TenantSpec).Format) while other tree nodes that contain Expr's don't.

Fair. I have extended the PR accordingly. PTAL.

**Review by stevendanna — APPROVED** [review]
Thanks!

**Comment by knz** [comment]
thank you!

bors r=stevendanna

**Pull request merged**
