### PR TITLE
release-22.1: sql: add txn_fingerprint_id to node_statement_statistics

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit adds the `txn_fingerprint_id` column to
`crdb_internal.node_statement_statistics`.

Release note (sql): `txn_fingerprint_id` has been added to
`crdb_internal.node_statement_statistics`. The type of the
column is NULL or STRING.Backport 2/2 commits from #83616.

/cc @cockroachdb/release

---

# Commit 1
### sql: add txn_fingerprint_id to node_statement_statistics

This commit adds the `txn_fingerprint_id` column to
`crdb_internal.node_statement_statistics`.

Release note (sql): `txn_fingerprin_id` has been added to
`crdb_internal.node_statement_statistics`. The type of the
column is NULL or STRING.

------------------------------
# Commit 2
### sql, sqlstats: create temporary stats container for all txns

Fixes: #81470

Previously, the stats collector followed different procedures for stats
collection depending on whether or not the txn was explicit.

For explicit transactions, all the stmts in the txn must be recorded with
the same `transactionFingerprintID`, which is  only known after all stmts
in the txn have been executed. In order to record the correct
txnFingerprintID, a temporary stats container was created for stmts in the
current transaction. The `transactionFingerprintID` was then populated for
all stmts in the temp container, and the temp container was merged with
the parent.

For implict transactions, the assumption was there would only be a single
stmt in the txn, and so no temporary container was created, with stmts
being written directly to the application stats.

This assumption was incorrect, as it is possible for implicit txns to have
multiple stmts, such as stmts sent in a batch.

This commit ensures that stats are properly collected for implicit txns
with multiple stmts. The stats collector now follows the same procedure
for both explicit and implicit txns, creating a temporary container for
local txn stmts and merging on txn finish.

Release note (bug fix): Statement and transaction stats are now properly
recorded for implicit txns with multiple stmts.

Release justification: bug fix

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84020#-:-N6OsU2MBJ40GEUsI6FW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rafiss** [comment]
Is it necessary to backport the first commit? It might be odd for a user to see the new column on some nodes, but not others, if they are in a mixed version state.

**Comment by rafiss** [comment]
That said, I don't know of any specific risk with doing that.

**Comment by xinhaoz** [comment]
@rafiss It's not necessary for the bug fix, it's just that there's a test case using the new column. I can remove that test case if we don't want to include the new column in the backport.

**Comment by xinhaoz** [comment]
Looks like [the behaviour](https://github.com/cockroachdb/cockroach/pull/76834) I was testing using the new column was not backported to 22.1. I'm wondering if multi-stmt implicit txns are even possible in 22.1 that would require this fix? For now I'll modify this to drop the first commit and remove the test case.  @maryliag @rafiss

**Pull request merged**
