### PR TITLE
storage: get rid of the write timestamp cache

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Release note: None

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
Why doesn't a write timestamp cache hit imply that a future refresh will fail? Semantically, it's a write and a subsequent refresh should logically fail. You could argue that the refresh is moot since the write TS cache is only in play for DelRanges where nothing was deleted, but as long as the write timestamp cache exists it seems to me that it's a bug that it's not checked by refresh. 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-:-LvQuPGq5z1RcgJwtGtK:bwwco0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/storage/replica_tscache.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvQowkw177tt1kSktkc:-LvQowkw177tt1kSktkd:b335gl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1014ffec80182f61ebaaee42ea8f44f291ab8c75/pkg/storage/replica_tscache.go#L292)):*
> ```Go
> 
> 			// On more recent writes, forward the timestamp and set the
> 			// write too old boolean for transactions. Note that currently
> ```

Update this comment too.

**Review by andreimatei — COMMENTED** [review]
> You could argue that the refresh is moot since the write TS cache is only in play for DelRanges where nothing was deleted

That's indeed what I would argue.

If I read your comment correctly, you don't have a problem with this PR as it was when you read it, but you have a problem in general with the fact that the Refresh requests don't check the write timestamp cache? 
In any case, I've expanded the PR to remove the wts cache completely... I haven't done the final deletion of the data structure yet; sending this out to verify that we're on the same page and everybody thinks everything is safe.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-:-LvSQjZq8F4V6PgK5iDz:b3uyx6d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/storage/replica_tscache.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvQowkw177tt1kSktkc:-LvSRywK0QE-J0Pz6p9_:bb7gzl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1014ffec80182f61ebaaee42ea8f44f291ab8c75/pkg/storage/replica_tscache.go#L292)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Update this comment too. 
</blockquote></details>

gone

**Review by bdarnell — APPROVED** [review]
> If I read your comment correctly, you don't have a problem with this PR as it was when you read it, but you have a problem in general with the fact that the Refresh requests don't check the write timestamp cache?

My intention was just for there to be comments reflecting this fact, that *conceptually* the write ts cache should require a refresh but it's not necessary in current usage. But going ahead and ripping the thing out is good too :)

> Reviewed 5 of 5 files at r2, 19 of 19 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-:-Lvf_Cg17OPs2Ov5y8ww:b-m4lran)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/keys/keys.go, line 431 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvfYUoEEiw5DSGr4z2Z:-LvfYUoF8bKZ5e0ZnwZr:b-x0zrsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/keys.go#L431)):*
> ```Go
> // transaction record after the transaction record has been cleaned up (i.e. by
> // a BeginTxn being evaluated out of order or arriving after another txn
> // Push(Abort)'ed the txn).
> ```

It's nice that we have these methods as an anchor to talk about how this works. I didn't realize we were using the read and write timestamp caches separately for transaction records. It feels a bit hacky looking at it all together, but at least we're clear about what we're doing now.
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvfSwO380DCqtsX3leh:-LvfSwO380DCqtsX3lei:b-ln5uar) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/kv/txn_interceptor_span_refresher.go#L366)):*
> ```Go
> 
> 	ba.RefreshSpanIterate(br, func(span roachpb.Span) {
> 		if log.ExpensiveLogEnabled(ctx, 3) {
> ```

Is this explicit ExpensiveLogEnabled check needed? I thought we only needed this when it was expensive to construct the arguments to Veventf.

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, 19 of 19 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/keys/constants.go, line 178 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqqMd15zyWIOQPgQX8:-LvqqMd15zyWIOQPgQX9:b2mcb33) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/constants.go#L178)):*
> ```Go
> 	LocalTransactionSuffix = roachpb.RKey("txn-")
> 
> 	TransactionTombstoneTSCacheSuffix  = roachpb.RKey("-tmbs")
> ```

I don't think these belong here. They're not real keys, so I think they should go where they're used - in `replica_tscache.go`.
___
*[pkg/keys/keys.go, line 425 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-Lvqqc1CAHguN1cMG8bw:-Lvqqc1CAHguN1cMG8bx:bs2087m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/keys.go#L425)):*
> ```Go
> }
> 
> // TransactionTombstoneTSCacheKey returns the key used by the marker indicating
> ```

Same comment. I don't think this belongs in the `pkg/keys` package.
___
*[pkg/keys/printer.go, line 458 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqqhIz5PRIRKlI3q8c:-LvqqhIz5PRIRKlI3q8d:b-z5hw9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/printer.go#L458)):*
> ```Go
> 				}
> 				if bytes.Equal(s.suffix, LocalTransactionSuffix) {
> 					qualifier := ""
> ```

There's no need for this.
___
*[pkg/roachpb/data.proto, line 467 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqRfINBNcbIARi3xLk:-LvqRfIO1JZI3rajkZfU:b-gmq4dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/roachpb/data.proto#L467)):*
> ```protobuf
>   // not when this flag is set (since lost updates cannot be tolerated even in
>   // SNAPSHOT). In SERIALIZABLE isolation, transactions generally don't commit
>   // with a bumped write timestamp.
> ```

Finish this off with something like:

"with a bumped write timestamp, so this flag doesn't tell us anything more than ReadTimestamp != WriteTimestamp"
___
*[pkg/storage/replica_tscache.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqS1Zz5dKcRFSELFv5:-LvqS1Zz5dKcRFSELFv6:bg32yr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/storage/replica_tscache.go#L204)):*
> ```Go
> 		default:
> 			if roachpb.UpdatesWriteTimestampCache(args) {
> 				// Only requests specially cased above update the timestamp cache.
> ```

"update the write timestamp cache"
___
*[pkg/storage/replica_tscache.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqS41BAUecgVVMolOS:-LvqS41BAUecgVVMolOT:b-xlq1ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/storage/replica_tscache.go#L205)):*
> ```Go
> 			if roachpb.UpdatesWriteTimestampCache(args) {
> 				// Only requests specially cased above update the timestamp cache.
> 				log.Fatalf(context.TODO(), "unexpected update of the timestamp cache for request: %s", args)
> ```

"of the write timestamp cache"
___
*[pkg/storage/tscache/cache.go, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqSF-YA7SoqgqOHdDi:-LvqSF-YA7SoqgqOHdDj:b-5ea4kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/storage/tscache/cache.go#L74)):*
> ```Go
> 	// GetMaxWrite behaves like GetMaxRead, but returns the maximum write
> 	// timestamp which overlaps the key.
> 	GetMaxWrite(key roachpb.Key) (hlc.Timestamp, uuid.UUID)
> ```

What's up with this change? I thought we were going to get rid of MaxWrite/MaxRead entirely.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @nvanbenschoten)

___
*[pkg/keys/constants.go, line 178 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqqMd15zyWIOQPgQX8:-LxbTqAU1milgoZzSQk0:b-43chi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/constants.go#L178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think these belong here. They're not real keys, so I think they should go where they're used - in `replica_tscache.go`.
</blockquote></details>

They arguable are keys, because the ts cache interface is written in terms of keys. Let's discuss on your comment below on the pretty printer.
___
*[pkg/keys/keys.go, line 431 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvfYUoEEiw5DSGr4z2Z:-LxbTL8_1wccH0db1pqs:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/keys.go#L431)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's nice that we have these methods as an anchor to talk about how this works. I didn't realize we were using the read and write timestamp caches separately for transaction records. It feels a bit hacky looking at it all together, but at least we're clear about what we're doing now.
</blockquote></details>

ack
___
*[pkg/keys/printer.go, line 458 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqqhIz5PRIRKlI3q8c:-LxbTUgABexnl9uW4EPz:bom82i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/printer.go#L458)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There's no need for this.
</blockquote></details>

but I like it. When I print one of these faux keys (and I might print it since it is represented in the tscache as a key), this pretty suffix is gold.
No?
___
*[pkg/kv/txn_interceptor_span_refresher.go, line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvfSwO380DCqtsX3leh:-LxbQNQC87VhkwNuMOTR:b2j9vh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/kv/txn_interceptor_span_refresher.go#L366)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Is this explicit ExpensiveLogEnabled check needed? I thought we only needed this when it was expensive to construct the arguments to Veventf.
</blockquote></details>

I was just maintaining what we had before, but yeah, removed.
___
*[pkg/roachpb/data.proto, line 467 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqRfINBNcbIARi3xLk:-LxbPllWAfHkjm8kqm0F:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/roachpb/data.proto#L467)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Finish this off with something like:

"with a bumped write timestamp, so this flag doesn't tell us anything more than ReadTimestamp != WriteTimestamp"
</blockquote></details>

done
___
*[pkg/storage/replica_tscache.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqS1Zz5dKcRFSELFv5:-LxbQ6vtBi34qY7l4A6L:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/storage/replica_tscache.go#L204)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"update the write timestamp cache"
</blockquote></details>

done
___
*[pkg/storage/replica_tscache.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqS41BAUecgVVMolOS:-LxbQ7jJ7UmQwghkRJvw:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/storage/replica_tscache.go#L205)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"of the write timestamp cache"
</blockquote></details>

done
___
*[pkg/storage/tscache/cache.go, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqSF-YA7SoqgqOHdDi:-LxbQ9g81xPa0M5Gt1R6:boeonay) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa95fb550041d032e262285ab9c509db6128ac2/pkg/storage/tscache/cache.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's up with this change? I thought we were going to get rid of MaxWrite/MaxRead entirely.
</blockquote></details>

yeah, this is incremental

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 25 files at r5, 19 of 22 files at r6, 5 of 6 files at r7, 13 of 13 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @bdarnell)

___
*[pkg/keys/printer.go, line 458 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqqhIz5PRIRKlI3q8c:-LxbihAuBY7B9UH-vJIi:b-ghvkxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/printer.go#L458)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

but I like it. When I print one of these faux keys (and I might print it since it is represented in the tscache as a key), this pretty suffix is gold.
No?
</blockquote></details>

When do we print these keys?

I'm concerned about this because we point to the `keys` package as a source of documentation for what is written into RocksDB. It's the best source of documentation for this. But these new "keys" are never written into RocksDB. They're completely synthetic and are an artifact of the new use of timestamp cache. No one outside of a reader of the timestamp cache code should ever need to know about their existence. I'd pretty strongly push against their inclusion in the `keys` package.
___
*[pkg/storage/apply/cmd.go, line 210 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-Lxbk89j-o6Rh6WoP6PG:-Lxbk89j-o6Rh6WoP6PH:b-joqd71) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ca217765fc1b4d85807f2bd750b782236e2e0c/pkg/storage/apply/cmd.go#L210)):*
> ```Go
> // iterator. The function closes the provided iterator.
> func forEachAppliedCmdIter(
> 	ctx context.Context, iter AppliedCommandIterator, fn func(context.Context, AppliedCommand) error,
> ```

Can we still use method references in `task.go` if we switch this to `fn func(AppliedCommand, context.Context) error`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/keys/keys.go, line 425 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-Lvqqc1CAHguN1cMG8bw:-LxbqMhx7pdymtt5qi0P:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/keys.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same comment. I don't think this belongs in the `pkg/keys` package.
</blockquote></details>

done
___
*[pkg/keys/printer.go, line 458 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqqhIz5PRIRKlI3q8c:-Lxbq3kR6zD_AXyD2pwH:b-uce9ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/printer.go#L458)):*
> When do we print these keys?

I was thinking if you want to look through the tscache contents. I forgot exactly why I had added this pretty printing support exactly, but it makes sense to me.

Anyway, moved all this stuff to the tscache file.
___
*[pkg/storage/apply/cmd.go, line 210 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-Lxbk89j-o6Rh6WoP6PG:-LxblOOZCGAL7B4cJVI4:bbazntg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ca217765fc1b4d85807f2bd750b782236e2e0c/pkg/storage/apply/cmd.go#L210)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we still use method references in `task.go` if we switch this to `fn func(AppliedCommand, context.Context) error`?
</blockquote></details>

that's how I had written it at first, but then I switched it. With ctx as a 2nd argument I had to add a comment here about why we do it, plus I was afraid that a linter will yell at me. I think it's not worth it.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 16 files at r9, 11 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @nvanbenschoten)

___
*[pkg/keys/constants.go, line 177 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxbtkB53OF4BiO2euQP:-LxbtkB53OF4BiO2euQQ:bgob9o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8d1f8e35b59fa9f6688f786fa2f49863a9c8b57/pkg/keys/constants.go#L177)):*
> ```Go
> 	// (storage/engine/rocksdb/db.cc).
> 	LocalTransactionSuffix = roachpb.RKey("txn-")
> ```

nit: remove this new line as well to get rid of the diff in this file.
___
*[pkg/keys/printer.go, line 458 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LvqqhIz5PRIRKlI3q8c:-LxbuGNCDWeDnf-HG-g0:bz5p5fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32d40a3f0db049028fd6a2598645accf7ccf181/pkg/keys/printer.go#L458)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> When do we print these keys?

I was thinking if you want to look through the tscache contents. I forgot exactly why I had added this pretty printing support exactly, but it makes sense to me.

Anyway, moved all this stuff to the tscache file.
</blockquote></details>

Thanks, this seems much nicer now that it's all localized in the `replica_tscache.go` file.
___
*[pkg/storage/apply/cmd.go, line 210 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-Lxbk89j-o6Rh6WoP6PG:-LxbtvOqD-48npOQOBnf:bnm5fnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ca217765fc1b4d85807f2bd750b782236e2e0c/pkg/storage/apply/cmd.go#L210)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

that's how I had written it at first, but then I switched it. With ctx as a 2nd argument I had to add a comment here about why we do it, plus I was afraid that a linter will yell at me. I think it's not worth it.
</blockquote></details>

If the linter doesn't yell at you then I'd make the switch. The method reference makes it obvious that it's avoiding capturing any state or allocating. It's always much harder to say with closures and it's more subtle when things do go wrong.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/keys/constants.go, line 177 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxbtkB53OF4BiO2euQP:-Lxbyswt8jp_gQEv-RM4:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8d1f8e35b59fa9f6688f786fa2f49863a9c8b57/pkg/keys/constants.go#L177)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: remove this new line as well to get rid of the diff in this file.
</blockquote></details>

done
___
*[pkg/storage/apply/cmd.go, line 210 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-Lxbk89j-o6Rh6WoP6PG:-Lxc0uib1LcrLwlNJTV1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ca217765fc1b4d85807f2bd750b782236e2e0c/pkg/storage/apply/cmd.go#L210)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If the linter doesn't yell at you then I'd make the switch. The method reference makes it obvious that it's avoiding capturing any state or allocating. It's always much harder to say with closures and it's more subtle when things do go wrong.
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 13 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-:-Lxc1RyxEnOA0qk2cyPa:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
I had forgotten that I hadn't actually removed the code for the write ts cache. Appended a commit to do it. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-:-LxcUGMu5ADkoIxr-eff:b-bpcox)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 34 files at r13, 11 of 22 files at r15, 1 of 3 files at r16, 10 of 13 files at r17, 22 of 22 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @bdarnell)

___
*[pkg/storage/batcheval/cmd_push_txn.go, line 303 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZLCpDF0edA-j9EZO:-LxvZLCqC4LK3JN-SYnf:bxtrmy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/storage/batcheval/cmd_push_txn.go#L303)):*
> ```Go
> 	// transaction record. To ensure that a timestamp push or an abort is
> 	// respected for transactions without transaction records, we rely on markers
> 	// in the read timestamp cache.
> ```

It looks like you got rid of all references to "write timestamp cache" but left some references to "read timestamp cache". We can kill that off too.
___
*[pkg/storage/tscache/metrics.go, line 21 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZkMB6UC0GlIIvOKN:-LxvZkMB6UC0GlIIvOKO:b5in7m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/storage/tscache/metrics.go#L21)):*
> ```Go
> 
> // sklImplMetrics holds all metrics relating to an sklImpl Cache implementation.
> type sklImplMetrics struct {
> ```

There's no need for this struct anymore.
___
*[pkg/storage/tscache/metrics.go, line 40 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZbhjCYf4FzRAtRDx:-LxvZbhjCYf4FzRAtRDy:b-ck3fbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/storage/tscache/metrics.go#L40)):*
> ```Go
> var (
> 	metaSklReadPages = metric.Metadata{
> 		Name:        "tscache.skl.read.pages",
> ```

Remove the "read" portion.
___
*[pkg/ts/catalog/chart_catalog.go, line 677 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZxH2-qyMMIbq-3Qn:-LxvZxH38kYKwwFOkdWV:b49e6xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/ts/catalog/chart_catalog.go#L677)):*
> ```Go
> 				Title: "Page Counts",
> 				Metrics: []string{
> 					"tscache.skl.read.pages",
> ```

This will need to be updated.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_push_txn.go, line 303 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZLCpDF0edA-j9EZO:-Lxw9rqp7QphqjiHn0W9:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/storage/batcheval/cmd_push_txn.go#L303)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It looks like you got rid of all references to "write timestamp cache" but left some references to "read timestamp cache". We can kill that off too.
</blockquote></details>

done
___
*[pkg/storage/tscache/metrics.go, line 21 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZkMB6UC0GlIIvOKN:-Lxw9tI0Dv5xU-oMJSS1:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/storage/tscache/metrics.go#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There's no need for this struct anymore.
</blockquote></details>

removed
___
*[pkg/storage/tscache/metrics.go, line 40 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZbhjCYf4FzRAtRDx:-Lxw3Wwd3qeh9roHvTlO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/storage/tscache/metrics.go#L40)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Remove the "read" portion.
</blockquote></details>

done
___
*[pkg/ts/catalog/chart_catalog.go, line 677 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZxH2-qyMMIbq-3Qn:-Lxw3Xct17VgQ4ma-PYR:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/ts/catalog/chart_catalog.go#L677)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This will need to be updated.
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 11 of 22 files at r21, 1 of 3 files at r22, 9 of 13 files at r23, 25 of 25 files at r24.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-:-LxwCX8AEcgC-kfRuENB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/ts/catalog/chart_catalog.go, line 677 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZxH2-qyMMIbq-3Qn:-LxwCUgc9E800SzfCW4t:b-alzhb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/ts/catalog/chart_catalog.go#L677)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done
</blockquote></details>

No it wasn't.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/ts/catalog/chart_catalog.go, line 677 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-LxvZxH2-qyMMIbq-3Qn:-LxwDXW2BoQE82M59axi:b1nya4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8784e05e49979303ae69ece6a9ec77a515c4cf/pkg/ts/catalog/chart_catalog.go#L677)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No it wasn't.
</blockquote></details>

now for real, sorry

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 1 files at r25.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43008#-:-LxwjZxlBexUboQo3jJb:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

**Pull request merged**
