### PR TITLE
sql: get rid of DescriptorDeletedError error detail

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6547)

### CODE REVIEW

**Comment by dt** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[roachpb/errors.proto, line 236 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547#-KH24pzCNqe2uxf5IXjo:-KH24pzCNqe2uxf5IXjp:-2093741953) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3f64a7fde1c454d0da3e140e4fe26eff016bf47/roachpb/errors.proto#L236)):*
ditto comment on other PR re: deleting fields.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 93 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547#-KH2Z7oncFHH6AyyYU5b:-KH2Z7oncFHH6AyyYU5c:-423414124) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dbec7de171dab812e59395904e77064fe0807c/sql/lease.go#L93)):*
why is the error message "table" while the name of the error is "descriptor"?

---

*[sql/lease.go, line 619 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547#-KH2Z-dP4-Wv_bnnZEFB:-KH2Z-dP4-Wv_bnnZEFC:-710222950) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dbec7de171dab812e59395904e77064fe0807c/sql/lease.go#L619)):*
why can't this retain the old form? `deleted = err == errDescriptorDeleted`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547)*

**Comment by andreimatei** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 93 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547#-KH2Z7oncFHH6AyyYU5b:-KH6-1qnJWqaFg4c75r3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dbec7de171dab812e59395904e77064fe0807c/sql/lease.go#L93)):*
Done.

---

*[sql/lease.go, line 619 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547#-KH2Z-dP4-Wv_bnnZEFB:-KH5zABVYoAP56_EPopU:756215001) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dbec7de171dab812e59395904e77064fe0807c/sql/lease.go#L619)):*
it's a matter of taster. The idea is that the code wants to emphasize setting `deleted` in a certain case, not re-setting it always.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6547#-:-KH60vlvTRYlBxKXAcdf:1417088721)*

**Pull request merged**
