### PR TITLE
colexechash: cleanup and speed up the hash table a bit (mostly around null handling)

### LINKED ISSUE #64762: colexec: distinct benchmark on bytes has too much variance for some reason
Here is a snippet of running the same benchmark three times using exactly the same commits for "before" and "after":
```
name                                                                                            old speed      new speed      delta
Distinct/Unordered/hasNulls=true/newTupleProbability=0.001/rows=262144/ordCols=0/type=bytes-24   142MB/s ± 2%    97MB/s ± 2%  -31.94%  (p=0.000 n=10+10)
```
```
name                                                                                            old speed      new speed      delta
Distinct/Unordered/hasNulls=true/newTupleProbability=0.001/rows=262144/ordCols=0/type=bytes-24   111MB/s ± 2%   114MB/s ± 1%  +2.26%  (p=0.000 n=10+9)
```
```
name                                                                                            old speed      new speed      delta
Distinct/Unordered/hasNulls=true/newTupleProbability=0.001/rows=262144/ordCols=0/type=bytes-24  96.4MB/s ± 2%  99.6MB/s ± 1%  +3.35%  (p=0.000 n=10+10)
```
We should figure out why it produces so much variance (in a sense that the absolute speed changes this drastically). Note that the integers don't seem to have this problem.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: switch min to any_not_null for aggregator benchmarks**

`any_not_null` will have the least impact when benchmarking the
aggregators. For 22.1 cycle we will keep the previous function (`min`)
so that we could use it for comparison against 21.2 branch.

Release note: None

**colexec: shuffle input for unordered distinct benchmark**

Previously, we were using the same way to construct the input data set
for both ordered and unordered distinct benchmarks (the latter was just
not taking an explicit advantage of the ordering). However, this is not
very realistic - we should properly shuffle the input for the unordered
distinct which is what this commit adds.

Note that this commit doesn't remove the old benchmark - instead, a new
bench case with a different name is added in order to preserve the
comparison against 21.2 branch. The old benchmark can be removed in
22.2.

Additionally, this commit removes a couple of bench cases which have too
high variance in the numbers. For example, here is a comparison of the
same code against itself:
```
Distinct/Unordered/hasNulls=false/newTupleProbability=0.001/rows=262144/ordCols=0/type=int-24     536MB/s ± 1%   679MB/s ± 2%  +26.67%  (p=0.000 n=10+10)
Distinct/Unordered/hasNulls=false/newTupleProbability=0.001/rows=262144/ordCols=0/type=bytes-24   236MB/s ± 1%   146MB/s ± 1%  -38.28%  (p=0.000 n=10+10)
Distinct/Unordered/hasNulls=true/newTupleProbability=0.001/rows=262144/ordCols=0/type=int-24      278MB/s ± 2%   218MB/s ± 2%  -21.68%  (p=0.000 n=10+10)
Distinct/Unordered/hasNulls=true/newTupleProbability=0.001/rows=262144/ordCols=0/type=bytes-24    184MB/s ± 1%   151MB/s ± 1%  -18.03%  (p=0.000 n=10+9)
```
Fixes: #64762.

Release note: None

**colexechash: move a non-templated function out of generated code**

Release note: None

**colexechash: pull out nulls bitmap retrieval out of the loop**

Release note: None

**colexechash: remove most comments from the generated code**

This commit converts all inline comments within the functions with the
generated code into the template-time only comments (i.e. the comments
are now only present in the template files). These comments aren't that
useful in the generated code. Additionally, the comments are reworded
slightly and wrapped at 80 characters.

Release note: None

**colexechash: clean up the check functions**

This commit cleans up the template for the functions that check the
results of a single iteration of probing (i.e. the code that runs after
probing tuples have been compared against the corresponding possible
matches, and we now have `differs` and `distinct` populated).

Previously, the code was of the form:
```
if !differs[i] {
...
// In some cases, set differs[i] to true.
...
}
if differs[i] {
...
}
```
This was so because we were modifying `differs` in the first block and
wanted to perform the logic of the second block. This commit, instead,
inlines the code of the second block in the case where we previously
were updating `differs[i]`. As a result, two `if`s have been squashed
into `if-else`.

Additionally, the comments have been improved.

Release note: None

**colexechash: clean up the logic around null checks**

This commit restructures the code so that the code for null checks is
only generated when the vectors might have null values. Additionally,
now the check whether null equality is allowed is only performed when we
have a NULL value (previously it was always performed, even when no
NULLs are present in the vectors).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Benchmarks of the last 5 commits are [here](https://gist.github.com/yuzefovich/6f5c0ae2b82747daac07645f406d124e).

I ended up not implementing (at least for now) the idea we mentioned during the collaboration session (where we'd short-circuit per-column check if `distinct[toCheck]` or `differs[toCheck]` was already true). It is beneficial only when we have multiple columns in the DISTINCT clause, and in some cases it seems cheaper to perform the actual comparison (like for int64s).

**Review by rharding6373 — APPROVED** [review]
:lgtm: nice work! I only have a few minor comments. If there isn't an issue open already to remove the old benchmarks in 22.2, it seems useful to make one and then link to it in the TODO comments, so it can be scheduled at the right time.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-:-MtiKUQM1lppPYu5QieK:b-wpn6bg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-MtiHAcM3mQaXfu7yLQI:-MtiHAcM3mQaXfu7yLQJ:blpop2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fee781a6acaef0b654ebc91e4bf3df689732610/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L129)):*
> ```Go
> 		if keyID != 0 {
> 			// {{end}}
> 			// the build table key (calculated using keys[keyID - 1] = key) is
> ```

Why isn't this comment useful anymore?
___
*[pkg/sql/colexec/aggregators_test.go, line 1183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-MtiBDbyBvCbTqX1PqVh:-MtiBDbyBvCbTqX1PqVi:b-mbaa7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4e0cc78e557c7dfe8e34e2fdf812ef069688b95/pkg/sql/colexec/aggregators_test.go#L1183)):*
> ```Go
> 		// any_not_null in 22.1 cycle. It is kept so that we could use it for
> 		// comparison of 22.1 against 21.2.
> 		// TODO(yuzefovich): use only any_not_null in 22.2.
> ```

Is there an issue open for this change? Could probably use the same issue to address all the benchmarks in this PR that should be removed in 22.2.
___
*[pkg/sql/colexec/distinct_test.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-MtiDYZJA7kOWCldW5mb:-MtiDYZJA7kOWCldW5mc:b-lf97aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/107567aa9b519cb8f3ae133d77bcadbe4f34a31b/pkg/sql/colexec/distinct_test.go#L506)):*
> ```Go
> 			if shuffleInput {
> 				// Pick a random value among already existing ones.
> 				col[i] = col[rng.Intn(i)]
> ```

My gut tells me that if `newValueProbability` is less than .5, then algorithm will favor the value in `col[0]` for most of the input. I haven't done a thorough analysis and I'm not sure it matters, just wanted to make sure we're ok with a potentially uneven distribution of values.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the quick review!

I opened an issue to track the TODOs.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-:-MtjG0x18yWsTDJmi6iq:bze95mh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rharding6373)

___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-MtiHAcM3mQaXfu7yLQI:-MtjECFy64ImVIrBm_AL:b4fale) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fee781a6acaef0b654ebc91e4bf3df689732610/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L129)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why isn't this comment useful anymore?
</blockquote></details>

I thought it was redundant with the improved description on `GroupID`, but it doesn't hurt to be more verbose and explicit in comments, especially in the template files since the navigation for `_tmpl.go` file into the regular `.go` file is not that easy. Added a reworded comment back.
___
*[pkg/sql/colexec/aggregators_test.go, line 1183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-MtiBDbyBvCbTqX1PqVh:-Mtj9JD70gnRR0Io901T:b-o071oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4e0cc78e557c7dfe8e34e2fdf812ef069688b95/pkg/sql/colexec/aggregators_test.go#L1183)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is there an issue open for this change? Could probably use the same issue to address all the benchmarks in this PR that should be removed in 22.2.
</blockquote></details>

I think we usually don't open issues for such things and just rely on these TODOs that will be addressed at some point. Often someone would do a PSA in the engineering slack channel to check the TODOs that have been added during the last release cycle. However, opening an issue seems like a simple way to remind about this, so I opened #75106.
___
*[pkg/sql/colexec/distinct_test.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74897#-MtiDYZJA7kOWCldW5mb:-MtjAfCF3ej-bE8_qGo9:b-6dsvqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/107567aa9b519cb8f3ae133d77bcadbe4f34a31b/pkg/sql/colexec/distinct_test.go#L506)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

My gut tells me that if `newValueProbability` is less than .5, then algorithm will favor the value in `col[0]` for most of the input. I haven't done a thorough analysis and I'm not sure it matters, just wanted to make sure we're ok with a potentially uneven distribution of values.
</blockquote></details>

Indeed, that's a very good observation. This wasn't intentional, so I refactored this change.

**Comment by yuzefovich** [comment]
I reran `BenchmarkDistinct/UnorderedShuffled`, and the results [didn't change](https://gist.github.com/yuzefovich/b087ffea2fad3adc50e022a764df5b3f) (still good improvement when `hasNulls=true`).

**Pull request merged**
