### PR TITLE
 changefeedccl: changefeed concurrency and frontier observability #67206

### LINKED ISSUE #67190: cdc: setting to control the concurrency of changefeed backfills
Currently, changefeeds overload `kv.bulk_io_write.concurrent_export_requests` for changefeed concurrency. The latter should be an independent setting. (Feature request from a customer.)

cc @ajwerner

### LINKED ISSUE #67192: changefeedccl: Log more information in frontier
Add logs and metrics to change frontier to improve visibility around job state checkpoiting.
At the very least, We need to log how often we update jobs table; how long it takes;

### PR DESCRIPTION
**Pull request by miretskiy**
Stop relying on ExportRequestLimit to determine the number of concurrent
export requests, and introduce a decidated ScanRequestLimit setting.

If the setting is specified, uses that setting; otherwise, the default
value is computed as 3 * (number of nodes in the cluster), which is the
old behavior, but we cap this number so that concurrency does not get
out of hand if running in a very large cluster.

Fixes #67190

Improve Observability of of change frontier updates.

Add a metric to keep track of the number of frontier updates in the
changefeed. Add logging when job progress updates take excessive amount
of time.

Fixes #67192

Release Nodes: Provide a better configurability of scan request
concurrency. Scan requests are issued by changefeeds during the
backfill.

### CODE REVIEW

**Comment by miretskiy** [comment]
@HonoreDB I pushed PR you already looked at to another branch.  Can you take another look?

**Review by stevendanna — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67268#-:-MdwBx387WNl38tthHgs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67268#-MdwAiup1AGNHVMak39c:-MdwAiup1AGNHVMak39d:b-f9mbot) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e41c99772261b09f019c446d76a0997b1cd389/pkg/ccl/changefeedccl/kvfeed/scanner.go#L285)):*
> ```Go
> 	// This is all hand-wavy: 3 per node used to be the default for a very long time.
> 	// However, this could get out of hand if the clusters are large.
> 	// So cap the max to an arbitrary value of a 100.
> ```

I like the addition of the cap (although perhaps moving it to a constant might be nice.

One question I have is why we want to scale by the node count at this point at all.  We will naturally be scaling the number of scans that happen by the node count because change aggregators for different ranges are distributed across all of the nodes, so why account for it again here?

In a conversation about this, one item that came up is that in the case of core changefeeds, this makes a bit more sense.

To keep it backportable I think it makes sense to leave it as you have it here, but perhaps this is something we could follow-up on.

**Review by HonoreDB — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67268)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 1291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67268#-MdwDgxx0q6Yc740DC5r:-MdwDgxx0q6Yc740DC5s:bdt6720) ([raw file](https://github.com/cockroachdb/cockroach/blob/fefdf03b71db89a22d9dc3b7832bae8843869ef6/pkg/ccl/changefeedccl/changefeed_processors.go#L1291)):*
> ```Go
> 	}()
> 
> 	cf.metrics.Flushes.Inc(1)
> ```

Is Flushes the right metric to be incrementing here?
___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67268#-MdwAiup1AGNHVMak39c:-MdwEDEJ3ym0SDOKLjqo:b50kuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e41c99772261b09f019c446d76a0997b1cd389/pkg/ccl/changefeedccl/kvfeed/scanner.go#L285)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I like the addition of the cap (although perhaps moving it to a constant might be nice.

One question I have is why we want to scale by the node count at this point at all.  We will naturally be scaling the number of scans that happen by the node count because change aggregators for different ranges are distributed across all of the nodes, so why account for it again here?

In a conversation about this, one item that came up is that in the case of core changefeeds, this makes a bit more sense.

To keep it backportable I think it makes sense to leave it as you have it here, but perhaps this is something we could follow-up on.

</blockquote></details>

I think the rationale is that it's different kinds of nodes that can in theory be scaled independently? But fair point, as-is this doesn't really help with that, it just implicitly assumes that our ability to serve ExportRequests is O(number of changefeed aggregator nodes * total number of nodes =~ number of nodes squared), if I understand correctly, which grows faster than our actual capacity.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67268)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67268#-MdwAiup1AGNHVMak39c:-MdwJexn2Z3-Kl-wXXgw:b-q283ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e41c99772261b09f019c446d76a0997b1cd389/pkg/ccl/changefeedccl/kvfeed/scanner.go#L285)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I think the rationale is that it's different kinds of nodes that can in theory be scaled independently? But fair point, as-is this doesn't really help with that, it just implicitly assumes that our ability to serve ExportRequests is O(number of changefeed aggregator nodes * total number of nodes =~ number of nodes squared), if I understand correctly, which grows faster than our actual capacity.
</blockquote></details>

I would like to keep things as they are so that this change can be backported.
We should specify an argument to kvfeed whether or not the changefeed is a core style changefeed.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67268)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @HonoreDB, @miretskiy, and @stevendanna)

**Comment by miretskiy** [comment]
tftr
bors r+

**Pull request merged**
