### PR TITLE
obs: replace runtime.ReadGCStats with runtime/metrics

### LINKED ISSUE #119462: obs: replace `runtime.ReadGCStats` with `runtime/metrics`
See discussion in https://github.com/cockroachdb/cockroach/issues/88178.

This is less important than https://github.com/cockroachdb/cockroach/issues/119461, because:
https://github.com/cockroachdb/cockroach/blob/a40dd43f89d758c7fb6c12eca60b931ed9899e7c/pkg/server/status/runtime.go#L604-L606

Still, it will be nice cleanup.

### PR DESCRIPTION
**Pull request by lyang24**
This commit replaces runtime.ReadGCStats call with metrics derived from runtime metrics. Specifically the metric "/gc/cycles/total:gc-cycles" replaces GCStats's NumGC field and we convert "/sched/pauses/total/gc:seconds" to nanosecond to replace PauseTotal field.

Fixes: #119462

Release note: None

### CODE REVIEW

**Review by lyang24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122463)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nkodali and @nvanbenschoten)

___
*[`pkg/server/status/runtime.go` line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nvc1lCE6yq1csrzmPMG:-Nvc1lCE6yq1csrzmPMH:b8eq0m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L384)):*
> ```Go
> 
> // Count of all completed GC cycles.
> const runtimeMetricGCCount = "/gc/cycles/total:gc-cycles"
> ```

I checked the source code i am fairly confident both this metric and NumGC field derive data from `memstats.numgc`
total gc cycles
https://github.com/lyang24/go/blob/450ecbe90508f56684b69e39823d4da155846932/src/runtime/metrics.go#L653
NumGC field https://github.com/lyang24/go/blob/b2efd1de97402ec4b8fb4e9e0ec29c8e49e8e200/src/runtime/mstats.go#L585
___
*[`pkg/server/status/runtime.go` line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nvc3N_Z-KcDiV42ZQMm:-Nvc3N_Z-KcDiV42ZQMn:b-usgfo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L392)):*
> ```Go
> // /sched/pauses/stopping/gc:seconds), during which some threads
> // may still be running. Bucket counts increase monotonically.
> const runtimeMetricGCPauseTotal = "/sched/pauses/total/gc:seconds"
> ```

Unfortunately runtime metrics lacks the 1:1 mapping to readGC stats `/sched/pauses/total/gc:seconds` offers a float64histogram, we can iterate each bucket and sum(lower bound * count) to get an estimated value cc @nvanbenschoten   what do you think

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122463)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @lyang24 and @nkodali)

___
*[`pkg/server/status/runtime.go` line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nvc1lCE6yq1csrzmPMG:-NvhYbjj9SNOCQfYFZUx:bz8v41e) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L384)):*
<details><summary><i>Previously, lyang24 (Lanqing Yang) wrote…</i></summary><blockquote>

I checked the source code i am fairly confident both this metric and NumGC field derive data from `memstats.numgc`
total gc cycles
https://github.com/lyang24/go/blob/450ecbe90508f56684b69e39823d4da155846932/src/runtime/metrics.go#L653
NumGC field https://github.com/lyang24/go/blob/b2efd1de97402ec4b8fb4e9e0ec29c8e49e8e200/src/runtime/mstats.go#L585
</blockquote></details>

Double checked and can confirm, `/gc/cycles/total:gc-cycles` looks equivalent to `GCStats.NumGC`.
___
*[`pkg/server/status/runtime.go` line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nvc3N_Z-KcDiV42ZQMm:-NvhblCz5d3f8iSz0Lxj:bvisf6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L392)):*
<details><summary><i>Previously, lyang24 (Lanqing Yang) wrote…</i></summary><blockquote>

Unfortunately runtime metrics lacks the 1:1 mapping to readGC stats `/sched/pauses/total/gc:seconds` offers a float64histogram, we can iterate each bucket and sum(lower bound * count) to get an estimated value cc @nvanbenschoten   what do you think
</blockquote></details>

I agree that there is no 1:1 mapping. `/cpu/classes/gc/pause:cpu-seconds` is close, but is expressed in CPU-seconds. Computing a sum of the buckets in the histogram SGTM.
___
*[`pkg/server/status/runtime.go` line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-NvhcnUZ3GJHabN2mnxt:-NvhcnUZ3GJHabN2mnxu:bd69781) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L392)):*
> ```Go
> // /sched/pauses/stopping/gc:seconds), during which some threads
> // may still be running. Bucket counts increase monotonically.
> const runtimeMetricGCPauseTotal = "/sched/pauses/total/gc:seconds"
> ```

`/sched/pauses/total/gc:seconds` was just introduced in Go 1.22 (https://tip.golang.org/doc/go1.22) and replaces `/gc/pauses:seconds`. Since we're still in a transitionary period (the FIPS build has not yet been updated), what do you think about using that metric name instead and leaving a TODO to switch over to this one in a few weeks?
___
*[`pkg/server/status/runtime.go` line 870 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nvhdckv59hK-gP0-1XY:-Nvhdckv59hK-gP0-1XZ:b8iaqeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L870)):*
> ```Go
> 	rsr.CgoAllocBytes.Update(int64(cs.CGoAllocatedBytes))
> 	rsr.CgoTotalBytes.Update(int64(cs.CGoTotalBytes))
> 	rsr.GcCount.Update(int64(rsr.goRuntimeSampler.uint64(runtimeMetricGCCount)))
> ```

`gcCount`

**Review by lyang24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122463)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nkodali and @nvanbenschoten)

___
*[`pkg/server/status/runtime.go` line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-NvhcnUZ3GJHabN2mnxt:-Nvmn_8u4WytbNlC-rzM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L392)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`/sched/pauses/total/gc:seconds` was just introduced in Go 1.22 (https://tip.golang.org/doc/go1.22) and replaces `/gc/pauses:seconds`. Since we're still in a transitionary period (the FIPS build has not yet been updated), what do you think about using that metric name instead and leaving a TODO to switch over to this one in a few weeks?
</blockquote></details>

done
___
*[`pkg/server/status/runtime.go` line 870 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nvhdckv59hK-gP0-1XY:-NvmnaM05MUoSiaxLfX8:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a0bd8e0e3411ac18b37f20d2a0fd056f0874fd/pkg/server/status/runtime.go#L870)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`gcCount`
</blockquote></details>

done

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122463)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @lyang24 and @nkodali)

___
*[`pkg/server/status/runtime.go` line 453 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6m4SS5NK-Y9DI-Ebn:-Nw6m4SS5NK-Y9DI-Ebo:babwdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L453)):*
> ```Go
> 
> // float64HistogramSum performs an estimated sum to the float64histogram.
> // The sum is estimated by taking the average of the bucket boundaries * count.
> ```

"their count"
___
*[`pkg/server/status/runtime.go` line 454 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6m5ff6uh5d17fSecl:-Nw6m5ff6uh5d17fSecm:b96jhau) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L454)):*
> ```Go
> // float64HistogramSum performs an estimated sum to the float64histogram.
> // The sum is estimated by taking the average of the bucket boundaries * count.
> // Bucket with extreme boundary values such as -inf or inf will be normalized
> ```

"Buckets"
___
*[`pkg/server/status/runtime.go` line 459 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6m_YxBpeipgYXhwDA:-Nw6m_YxBpeipgYXhwDB:b-x6b1ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L459)):*
> ```Go
> 	estSum := 0.0
> 	var start, end float64 // start and end of current bucket
> 	for i := len(h.Counts) - 1; i >= 0; i-- {
> ```

nit: any reason to iterate in reverse?
___
*[`pkg/server/status/runtime.go` line 461 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6mfjfBhaFAXYNkDoo:-Nw6mfjfBhaFAXYNkDop:b-a2kq1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L461)):*
> ```Go
> 	for i := len(h.Counts) - 1; i >= 0; i-- {
> 		start, end = h.Buckets[i], h.Buckets[i+1]
> 		if i == 0 && math.IsInf(h.Buckets[0], -1) { // -Inf
> ```

Instead of `h.Buckets[0]` here, can we just use `start`? Also same below? So something like:
```go
start, end = h.Buckets[i], h.Buckets[i+1]
if math.IsInf(start, -1) { // -Inf
    start = end
}
if math.IsInf(end, +1) { // +Inf
    end = start
}
```
___
*[`pkg/server/status/runtime.go` line 461 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6mzeP59THY3FlDO6F:-Nw6mzeQ95gcAqMNCBdV:b-qjtpgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L461)):*
> ```Go
> 	for i := len(h.Counts) - 1; i >= 0; i-- {
> 		start, end = h.Buckets[i], h.Buckets[i+1]
> 		if i == 0 && math.IsInf(h.Buckets[0], -1) { // -Inf
> ```

Is there a risk that there are only two buckets, with `[-Inf, Inf)` boundaries?
___
*[`pkg/server/status/runtime.go` line 473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6nMDb5s_tUED88N1v:-Nw6nMDc0Kpw3qsSzXPK:b-f5w94a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L473)):*
> ```Go
> 		estBucketValue := start
> 		if end != start {
> 			estBucketValue = (end - start) / 2.0
> ```

This is supposed to be the average value, right? So `(start + end) / 2.0`? Or to avoid overflow, `start + (end - start)/2.0`?

**Review by lyang24 — COMMENTED** [review]
Thanks for catching the miscalculation let me run a comparison in cockroach workload with high gc pressure and see if estimated new value is in the ballpark 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-:-Nw6uFFo-H5RAuz5ivfO:b518unk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nkodali and @nvanbenschoten)

___
*[`pkg/server/status/runtime.go` line 461 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6mzeP59THY3FlDO6F:-Nw6tmiLD0BVBAGXI6cf:b-uelp2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L461)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a risk that there are only two buckets, with `[-Inf, Inf)` boundaries?
</blockquote></details>

yes i did an edge case check before the loop and panic if this happens 
___
*[`pkg/server/status/runtime.go` line 473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6nMDb5s_tUED88N1v:-Nw6u1J-DV9XloCaIg05:b51y2kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L473)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is supposed to be the average value, right? So `(start + end) / 2.0`? Or to avoid overflow, `start + (end - start)/2.0`?
</blockquote></details>

great catch my bad intent is `estBucketValue += (end - start) / 2.0` missed the +=

**Comment by lyang24** [comment]
gc pause time 
this branch estimated with runtime metrics
image
vs master read GCStats
image

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-:-NwAZH-M83Y4VwcFsMrU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @lyang24 and @nkodali)

___
*[`pkg/server/status/runtime.go` line 461 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6mfjfBhaFAXYNkDoo:-NwAZP5-CEalayaJbP8y:bl4nstc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L461)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of `h.Buckets[0]` here, can we just use `start`? Also same below? So something like:
```go
start, end = h.Buckets[i], h.Buckets[i+1]
if math.IsInf(start, -1) { // -Inf
    start = end
}
if math.IsInf(end, +1) { // +Inf
    end = start
}
```
</blockquote></details>

Do we even need the comparison against `i`? If so, maybe turn them into assertions?

```go
start, end = h.Buckets[i], h.Buckets[i+1]
if math.IsInf(start, -1) { // -Inf
    if i != 0 { panic(...) }
    start = end
}
if math.IsInf(end, +1) { // +Inf
    if i != len(h.Counts)-1 { panic(...) }
    end = start
}
```
___
*[`pkg/server/status/runtime_test.go` line 198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-NwAYKt71NAq2W7YM17V:-NwAYKt71NAq2W7YM17W:bfpudss) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ca037f9c1fdd82cb8d255fa398ad2db3e1d1f5/pkg/server/status/runtime_test.go#L198)):*
> ```Go
> 	}
> 	for _, tc := range testCases {
> 		require.Equal(t, tc.sum, int64(float64HistogramSum(&tc.h)*1e9))
> ```

Why the `*1e9`? It makes the test appear like it should not pass. Mind removing it?

**Review by lyang24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122463)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nkodali and @nvanbenschoten)

___
*[`pkg/server/status/runtime.go` line 461 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122463#-Nw6mfjfBhaFAXYNkDoo:-NwB7Yr0Bvx0g09RxYIA:b-tyi6f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8ead122a760e1312694e301aaccabbd468b1ee/pkg/server/status/runtime.go#L461)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we even need the comparison against `i`? If so, maybe turn them into assertions?

```go
start, end = h.Buckets[i], h.Buckets[i+1]
if math.IsInf(start, -1) { // -Inf
    if i != 0 { panic(...) }
    start = end
}
if math.IsInf(end, +1) { // +Inf
    if i != len(h.Counts)-1 { panic(...) }
    end = start
}
```
</blockquote></details>

right we do not need check against i

**Comment by yuzefovich** [comment]
This needs a minor adjustment:
```
=== RUN   TestLint/TestMissingLeakTest
=== PAUSE TestLint/TestMissingLeakTest
=== CONT  TestLint/TestMissingLeakTest
    gen-lint_test.go:430: 
        server/status/runtime_test.go: TestFloat64HistogramSum: missing defer leaktest.AfterTest
    --- FAIL: TestLint/TestMissingLeakTest (1.85s)
```

bors r-

**Pull request merged**
