### PR TITLE
sql: use manual replication mode in testcluster for scatter test

### PR DESCRIPTION
**Pull request by RaduBerinde**

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by RaduBerinde** [comment]
Removed the commit to disable the replica GC queue (I see an error when a test is trying to relocate some recently split ranges: `pq: snapshot failed: r11: remote couldn't accept snapshot with error: [n1,s1],r11: cannot apply snapshot: snapshot intersects existing range [n1,s1,r2/1:/Table/51/1/1{-0}]`).

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15008#-:-Ki0coIVt3MKW3YD_x6k:bnfp4nl)*

**Comment by danhhz** [comment]
LGTM

Is this to fix the "lease owned by replica that no longer exists" panic? And that panic could also happen in prod, right? If so, put a TODO to fix the panic and remove the manual replication please

**Comment by RaduBerinde** [comment]
Good point, done.

**Pull request merged**
