### PR TITLE
sql: use txn.NewBatch instead of &kv.Batch{}

### PR DESCRIPTION
**Pull request by rafiss**
This will make these requests properly passes along the admission control headers.

informs https://github.com/cockroachdb/cockroach/issues/79212
Epic: None
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Maybe add a linter for this too (like simple text based, over `pkg/sql*` ignoring tests)?

**Comment by rafiss** [comment]
> Maybe add a linter for this too 

There is a usage in pkg/sql/tenant_gc.go that I don't know how to address. I was planning to reach out to the multi-tenant team to see if that can be addressed separately.

There are also some in pkg/server that I don't know what to do about.

**Comment by rafiss** [comment]
I also found usages like this one: https://github.com/cockroachdb/cockroach/blob/5acb9994e479834fbfea51edc8abb3005f7b75dd/pkg/sql/gcjob/table_garbage_collection.go#L245-L251

It seems like it would be better to have a linter or runtime assertion to check that `AdmissionHeader` is always set, one way or another.

**Review by fqazi — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107236)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @yuzefovich)

**Comment by rafiss** [comment]
tftr!

bors r=fqazi

**Pull request merged**
