### PR TITLE
make acceptance tests resilient to job lease transfers

### PR DESCRIPTION
**Pull request by danhhz**
This is accomplished via the new RunAndWaitForTerminalState, which runs
a closure and potentially tracks its progress using the system.jobs
table.

### CODE REVIEW

**Comment by benesch** [comment]
:lgtm:

It took me forever to convince myself that `RunAndWaitForTerminalState` was correct, but I don't think it's worth trying to fix now. Not clear whether my comments will result in a net improvement. I marked things I don't care about below as "Satisified", but the couple nits that aren't marked as "Satisfied" should be easy enough to address now!

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 498 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsPy_1Tpv82vEmeMOfK:-KsPy_1Tpv82vEmeMOfL:b-kcdbv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L498)):*
> ```Go
> 	}
> 
> 	ctx, _ = context.WithTimeout(ctx, time.Second)
> ```

Is this intentional, or left over from your testing to avoid progress logging contention?

---

*[pkg/sql/jobs/jobs.go, line 662 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsPyoRT6d2fEaIGl6GX:-KsPyoRT6d2fEaIGl6GY:b8envia) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L662)):*
> ```Go
> // TODO(dan): Return a *Job instead of just the id and status.
> //
> // TODO(dan): This assumes that the next entry to the jobs table was made but
> ```

I think you meant "was made by"?

---

*[pkg/sql/jobs/jobs.go, line 684 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ5WiIyE5PSv-rTYb6:-KsQ5WiIyE5PSv-rTYb7:b-h1ueol) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L684)):*
> ```Go
> 		atomic.StoreUint32(&execDone, 1)
> 		return err
> 	})
> ```

This `errgroup` seems to be more trouble than it's worth, since you have to introduce an atomic variable. I think it'd be clearer with a normal goroutine? Don't bother now.

```
execErr := make(chan error)
go func() {
  execErr <- execFn(ctx)
}
```

Then you could derive whether the goroutine has completed or not by doing a nonblocking read from `execErr`.

---

*[pkg/sql/jobs/jobs.go, line 687 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ1_GpKn7n4Ub0uTzh:-KsPzaWou12Md9LZdM-0:b-7rw831) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L687)):*
> ```Go
> 
> 	var jobID int64
> 	for wait := time.Nanosecond; ; wait = boundWait(2 * wait) {
> ```

You could potentially use the built-in retry package here

```
for r := retry.StartWithCtx(ctx, retry.Options{InitialBackoff: time.Nanosecond, MaxBackoff: time.Second});;
```

which exposes a `r.NextCh` you could use in the select below. I'm inclined to think switching is more trouble than it's worth, given that you've already verified this approach works.

---

*[pkg/sql/jobs/jobs.go, line 723 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ-FjP889c3wC-Eici:-KsQ-FjP889c3wC-Eicj:b-rru444) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L723)):*
> ```Go
> 		var status Status
> 		var jobErr gosql.NullString
> 		err := sqlDB.QueryRow(`SELECT status, error FROM crdb_internal.jobs WHERE id = $1`, jobID).Scan(
> ```

`FROM [SHOW JOBS]` to avoid using an internal API.

---

*[pkg/sql/jobs/jobs.go, line 729 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ-OP7zs26yr4Pd3Dd:-KsQ-OP7zs26yr4Pd3De:b5ok1ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L729)):*
> ```Go
> 			return jobID, "", errors.Wrapf(err, "getting status of job %d", jobID)
> 		}
> 		if !status.Terminal() {
> ```

Love this! `Terminal()` is way more useful than I would have suspected.

---

*[pkg/sql/jobs/jobs.go, line 730 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ59RGgXl9bm47R8xV:-KsQ59RGgXl9bm47R8xW:byyljom) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L730)):*
> ```Go
> 		}
> 		if !status.Terminal() {
> 			log.Infof(ctx, "job %d is %s: created %s ago", jobID, status, timeutil.Since(begin))
> ```

This looks super spammy given that the retry loop starts with a backoff of a nanosecond. Maybe not worth fixing.

---

*[pkg/sql/jobs/jobs_test.go, line 716 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ4zxOEqmq2xKKFjSb:-KsQ4zxOEqmq2xKKFjSc:b-p0jbec) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs_test.go#L716)):*
> ```Go
> 				return job.Succeeded(ctx)
> 			},
> 		},
> ```

Ideally one more test for a job that fails without a lease transfer?

---

*[pkg/sql/jobs/jobs_test.go, line 763 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ51E_bV4iqJ1xcZ4o:-KsQ51E_bV4iqJ1xcZ4p:beap3aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs_test.go#L763)):*
> ```Go
> 			}
> 		})
> 	}
> ```

These tests are awesome!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-:-KsQAK06KJUJSfJbHOrY:b38foof)*

**Comment by benesch** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 498 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsPy_1Tpv82vEmeMOfK:-KsQAl98i_VoJCHAy8ew:b-mgmvdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L498)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Is this intentional, or left over from your testing to avoid progress logging contention?
</blockquote></details>

Ah, you already caught it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932)*

**Comment by benesch** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932)*

**Comment by danhhz** [comment]
Thanks for the review! RFAL

---

Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/jobs/jobs.go, line 662 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsPyoRT6d2fEaIGl6GX:-KsQFFYdJgT2_zJPoSIn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L662)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you meant "was made by"?
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs.go, line 684 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ5WiIyE5PSv-rTYb6:-KsQK9MhEdxDCmHwrHG3:b60rts3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L684)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This `errgroup` seems to be more trouble than it's worth, since you have to introduce an atomic variable. I think it'd be clearer with a normal goroutine? Don't bother now.

```
execErr := make(chan error)
go func() {
  execErr <- execFn(ctx)
}
```

Then you could derive whether the goroutine has completed or not by doing a nonblocking read from `execErr`.
</blockquote></details>

it's a tiny bit more complicated than that (unless i'm missing something). done, ptal

---

*[pkg/sql/jobs/jobs.go, line 687 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ1_GpKn7n4Ub0uTzh:-KsQK6uMpiFqCc2H_u_E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L687)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You could potentially use the built-in retry package here

```
for r := retry.StartWithCtx(ctx, retry.Options{InitialBackoff: time.Nanosecond, MaxBackoff: time.Second});;
```

which exposes a `r.NextCh` you could use in the select below. I'm inclined to think switching is more trouble than it's worth, given that you've already verified this approach works.
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs.go, line 723 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ-FjP889c3wC-Eici:-KsQCMYXX4UGZcM5KCo1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L723)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`FROM [SHOW JOBS]` to avoid using an internal API.
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs.go, line 730 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ59RGgXl9bm47R8xV:-KsQCIiilK0BGcIv2Pr7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L730)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This looks super spammy given that the retry loop starts with a backoff of a nanosecond. Maybe not worth fixing.
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs_test.go, line 716 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ4zxOEqmq2xKKFjSb:-KsQCDt97zn6fOff6hh7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs_test.go#L716)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ideally one more test for a job that fails without a lease transfer?
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs_test.go, line 763 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ51E_bV4iqJ1xcZ4o:-KsQKIbxIQGMY-_PpR7a:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs_test.go#L763)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

These tests are awesome!
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-:-KsQKKvDGLOaAeBRWbpp:b-6sx6b6)*

**Comment by benesch** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/jobs/jobs.go, line 684 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-KsQ5WiIyE5PSv-rTYb6:-KsQNdKiGv-iqSsvLdA0:b7wd583) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74aae3817beb382617b6fe737d45849a6bce8e4/pkg/sql/jobs/jobs.go#L684)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

it's a tiny bit more complicated than that (unless i'm missing something). done, ptal
</blockquote></details>

Oh, right, you don't want it to immediately pop you out of the select. Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17932#-:-KsQNiDO_02G79Ub_AtD:b-uwkowd)*

**Comment by danhhz** [comment]
TFTRs!

**Pull request merged**
