### PR TITLE
distsql: fix nil pointer in sort benchmarks

### PR DESCRIPTION
**Pull request by solongordon**
Sorter benchmarks were failing with nil pointer errors due to a missing
disk monitor.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31208#-:-LOUDS0L18OWEtsHxjJi:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by jordanlewis — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31208#-:-LOUD64Q7rEGjlrT6Hn7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by asubiotto — COMMENTED** [review]
Awesome. Could you remove the skips so that they are now run with `benchshort` in CI?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31208#-:-LOUFJXJ-nbqbAvhy3Id:bcwo14n)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by solongordon — COMMENTED** [review]
@asubiotto Good call, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31208#-:-LOUGN_v9kcWnxXIQN8X:bqdif6w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by knz** [comment]
maybe this wants a backport if the benchmark is available in the 2.1 branch

**Comment by solongordon** [comment]
Good point @knz, done.

**Pull request merged**
