### PR TITLE
gossip: fix incoming-request-during-shutdown race

### LINKED ISSUE #4395: Failed tests (12851):
The following test appears to have failed:

[#12851](https://circleci.com/gh/cockroachdb/cockroach/12851):

```
I0216 06:05:02.262480 212 gossip/server.go:242  @1: distantHops: 1 from 2
I0216 06:05:02.262715 212 gossip/client.go:163  node 1 received [node:3] from node 3 (0 fresh)
I0216 06:05:02.262845 212 gossip/server.go:242  @1: distantHops: 1 from 2
E0216 06:05:02.266479 212 gossip/client.go:221  rpc error: code = 1 desc = "context canceled"
==================
WARNING: DATA RACE
Read by goroutine 35:
  sync.raceRead()
      /tmp/workdir/go/src/sync/race.go:37 +0x2e
  sync.(*WaitGroup).Add()
      /tmp/workdir/go/src/sync/waitgroup.go:66 +0xfa
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:95 +0x43
  github.com/cockroachdb/cockroach/gossip.(*server).Gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/server.go:137 +0x637
  github.com/cockroachdb/cockroach/gossip._Gossip_Gossip_Handler()
--
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/google.golang.org/grpc/server.go:658 +0x150a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/google.golang.org/grpc/server.go:323 +0xad

Previous write by goroutine 42:
  sync.raceWrite()
      /tmp/workdir/go/src/sync/race.go:41 +0x2e
  sync.(*WaitGroup).Wait()
      /tmp/workdir/go/src/sync/waitgroup.go:124 +0xf9
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:223 +0x22a
  github.com/cockroachdb/cockroach/gossip.TestGossipCullNetwork()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip_test.go:147 +0x881
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Goroutine 35 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/google.golang.org/grpc/server.go:324 +0xa7
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /go/src/google.golang.org/grpc/transport/http2_server.go:212 +0x17fa
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /go/src/google.golang.org/grpc/transport/http2_server.go:276 +0x114d
  google.golang.org/grpc.(*Server).serveStreams()
      /go/src/google.golang.org/grpc/server.go:325 +0x1dc
  google.golang.org/grpc.(*Server).serveNewHTTP2Transport()
      /go/src/google.golang.org/grpc/server.go:312 +0x54d
  google.golang.org/grpc.(*Server).handleRawConn()
      /go/src/google.golang.org/grpc/server.go:289 +0x529

Goroutine 42 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck()
      /go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:37 +0x2e
  github.com/cockroachdb/cockroach/gossip_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/gossip/main_test.go:34 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:112 +0x209
--
=== RUN   TestGossipStorage
--- SKIP: TestGossipStorage (0.01s)
	storage_test.go:69: #3755
PASS
Found 1 data race(s)
FAIL	github.com/cockroachdb/cockroach/gossip	2.562s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.030s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #4395.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4407)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Add a comment. This stopception will surely make innocent bystanders scratch their head.

**Comment by tamird** [comment]
Done.

**Comment by bdarnell** [comment]
LGTM

**Comment by tschottdorf** [comment]
LGTM

**Pull request merged**
