### PR TITLE
vendor: bump Pebble to c2c0273062ce

### PR DESCRIPTION
**Pull request by jbowens**
```
c2c02730 db: fix SetOptions batch range{del,key} refresh logic
2aebabad sstable: remove obsolete linter ignore directive
dc391ef8 docs: use local scale by default on nightly benchmarks page
ef1ca573 compaction: elision-only compactions for tables with only range keys
4a952c0d db: document Batch as unsafe for concurrent access
9a8e4742 db: support SetOptions on iterators created through NewExternalIter
f13de498 db: fix nil-pointer in external iterator range key iteration
65702e71 db: avoid allocation in newIters
f185d7fa db: remove RangeKeysArena
ae99f4f1 *: start reading range keys from sstables
d72083df *: implement compaction/flushing of range keys
a015e5a0 db: exclude empty batch range deletion, range key iterators
8b7a68b8 compaction: introduce multi level compaction mechanics
67f2653a *: pass keyspan.Spans by pointer not value
83b45b0a internal/keyspan: refactor InterleavingIter bounds checking
c3053e0b internal/keyspan: manually inline {start,end}Bound in MergingIter
728722c5 internal/keyspan: refactor DefragmentingIter's invalid span checks
a5d4e00e db: add BenchmarkIteratorSeekNoRangeKeys
96dc71db internal/keyspan: preallocate merging iter levels, items
86dd6fd5 internal/keyspan: replace calls to Span.Visible
```

Release note: none

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83000#-:-N4hcvki1K8JroV9v135:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by rickystewart — CHANGES_REQUESTED** [review]
Build is broken.

```
[17:54:10 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ScratchProjectPutTcExperimentsInHere_BazelBuild/5491564?buildTab=log&focusLine=765&linesState=765)    pkg/storage/pebble.go:464:19: opts.Experimental.RangeKeys undefined (type struct { L0CompactionConcurrency int; CompactionDebtConcurrency int; DeleteRangeFlushDelay time.Duration; MinDeletionRate int; ReadCompactionRate int64; ReadSamplingMultiplier int64; TableCacheShards int; KeyValidationFunc func([]byte) error; ValidateOnIngest bool; MultiLevelCompaction bool; MaxWriterConcurrency int; ForceWriterParallelism bool; CPUWorkPermissionGranter pebble.CPUWorkPermissionGranter } has no field or method RangeKeys)
[17:54:10 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ScratchProjectPutTcExperimentsInHere_BazelBuild/5491564?buildTab=log&focusLine=766&linesState=766)    pkg/storage/pebble.go:464:36: undefined: pebble.RangeKeysArena
```

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83000)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Comment by jbowens** [comment]
TFTR!

bors r=nicktrav

**Pull request merged**
