### PR TITLE
release-23.1: kv, storage: fix handling of ambiguous failures on commit

### PR DESCRIPTION
**Pull request by AlexTalks**
Backport:
  * 1/1 commits from #107680
  * 1/1 commits from #107323
  * 1/1 commits from #108154
  * 1/1 commits from #108001
  * 1 new commit: **kvcoord: fix ambiguous commit tests for 23.1 behavior**
  * 1/1 commits from #107658
  * 1 new commit: **kvcoord: modify ambiguous commit tests for WTO deferral on 23.1**

Please see individual PRs for details.

/cc @cockroachdb/release

---

Release justification: Backporting fix for outstanding bug described in #103817.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 80 of 80 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110757)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @jbowens)

___
*[`pkg/kv/kvserver/logstore/logstore.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110757#-NecmM2G-NbACb53PDVz:-NecmM2G-NbACb53PDW-:b-k9d1ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bc0fcfa89af6e88f855bba56766c0ea4c9efb0/pkg/kv/kvserver/logstore/logstore.go#L36)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
> 	"github.com/cockroachdb/errors"
> 	"go.etcd.io/raft/v3"
> ```

Did you mean to remove this import? From the diff, I don't see what it would be removed.
___
*[`pkg/kv/kvserver/logstore/stateloader.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110757#-NecmZ8p0ZQRMfBjwLIr:-NecmZ8p0ZQRMfBjwLIs:b-cvhj4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cbb195ae31190574ac3ddcd0524c4100f104f6d/pkg/kv/kvserver/logstore/stateloader.go#L185)):*
> ```Go
> 	ctx context.Context, writer storage.Writer, replicaID roachpb.ReplicaID,
> ) error {
> <<<<<<< HEAD
> ```

Cherry-pick skew?
___
*[`pkg/storage/engine_test.go` line 1606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110757#-Necp4yH5xnoMPvnsO6i:-Necp4yH5xnoMPvnsO6j:bd7ywwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cbb195ae31190574ac3ddcd0524c4100f104f6d/pkg/storage/engine_test.go#L1606)):*
> ```Go
> 	// However, certain clearers cannot clear intents, range keys, or point keys.
> 	writeInitialData := func(t *testing.T, rw ReadWriter) {
> 		var localTS hlc.ClockTimestamp
> ```

Should we just delete `localTS`?

**Comment by AlexTalks** [comment]
It is possible we may require backporting #102808 and #102809 in order for the tests to work (without removing them for 23.1), @nvanbenschoten let me know if you have some thoughts on this?

**Comment by AlexTalks** [comment]
As discussed on Slack, I've updated some of the tests to use `CPut`s instead of `Put`s, but unfortunately it is somewhat clear (especially in the last commit) that without #102808 and #102809, any time a retried blind write happens _after_ the initial intents have been cleaned up, WTO deferral will mean we can't fully avoid getting `transaction unexpectedly committed` without further changes.

It feels like we have a few options from here:
* Proceed with backporting as is, knowing that there are some cases of the bug that won't be fully fixed on 23.1.
* Also backport #102808 and #102809, if we feel there isn't significant risk associated.
* Make additional changes to the `DistSender`, something like:
```
br, err = transport.SendNext(ctx, ba)
...
if err == nil {
  if br.Error == nil {
    if ambiguousError != nil && br.Txn != nil && br.Txn.WriteTooOld {
      return nil, kvpb.NewAmbiguousResultErrorf("error=%v [propagate] (last error: WriteTooOld)", ambiguousError)
    }
  }
}
```

(I'm not sure if it would be ok to leave around the intent written on the retry though?)

@nvanbenschoten feel free to let me know if you have some thoughts or preferences here!

**Comment by nvanbenschoten** [comment]
> Also backport https://github.com/cockroachdb/cockroach/pull/102808 and https://github.com/cockroachdb/cockroach/pull/102809, if we feel there isn't significant risk associated.

These changes feel too large and too risky to be backported. They also comes with some user-visible behavior changes that aren't appropriate for a patch release.

> Make additional changes to the DistSender, something like ...

This seems like a reasonable change, although making it will require additional testing and introduces some additional risk for the backport. How do you feel about it?

Independent of that, we should get to the bottom of the flakiness in https://github.com/cockroachdb/cockroach/issues/110187 before backporting the flaky test to other release branches.

**Comment by AlexTalks** [comment]
@nvanbenschoten agreed.  I actually put up a draft of the fix I am proposing in https://github.com/cockroachdb/cockroach/pull/111017.

**Comment by AlexTalks** [comment]
Closing this in favor of #111017 .

**Comment by daniel-crlabs** [comment]
Affects this customer: https://cockroachdb.zendesk.com/agent/tickets/19344

**Pull request closed without merging**
