### PR TITLE
geoindex,invertedidx,rowexec,encoding,...: add bounding box to invert…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…ed column

The bounding box is encoded after the cellid, and used to perform
"pre-filtering", i.e., filtering after the inverted row is fetched
but before it is added to various set expressions.

The fundamental weakness with the cell covering
approach is that the coverings for convex shapes are typically
worse than a bounding box and we pay significant cost in doing
a lookup join to eliminate the false positives. This attempts
to reduce those false positives for the lookup join, and part
of the inverted join (the invertedJoiner can avoid adding a
row to the RowContainer).

For the canonical nyc st_intersects and st_dwithin queries
the joinReader would see a much higher input row count than
the output due to false positives. Specifically,
- st_intersects: input 3110, output 490
- st_dwithin: input 23183, output 8606
With this change the input counts are 1064 and 11177. There
is the additional cost of reading extra bytes and applying
the bounding box filter, but it is more than offset by the
gains (see comparison numbers below).

This is a format change for the index, so is easier to do
before the launch of spatial features.

The encoding here is trivial, and consumes 17 bytes for points
and 33 bytes for others. An experiment with a more complicated
encoding that converted to integers while bounding the
relative error did not show any improvement wrt the following
benchmarks.

There are TODOs for followup PRs:
- Do such pre-filtering for invertedFilterer. This will need
  a spec change.
- Support pre-filtering for expressions containing more than
  one function.

Comparison numbers:

old is master
```
name                                   old ms     new ms     delta
Test/nyc/nyc-intersects                80.0 ±23%  69.0 ±30%  -13.76%  (p=0.000 n=49+48)
Test/nyc/nyc-dwithin                    225 ±13%   169 ± 8%  -24.88%  (p=0.000 n=46+45)
Test/nyc/nyc-coveredby                 84.1 ±11%  69.0 ±14%  -17.96%  (p=0.000 n=50+49)
Test/nyc/nyc-expand-blocks             85.7 ± 6%  84.6 ± 8%   -1.22%  (p=0.030 n=45+47)
Test/nyc/nyc-dwithin-and-dfullywithin   195 ± 7%   195 ± 6%     ~     (p=1.000 n=46+49)
Test/postgis_geometry_tutorial/11.2b   1.66 ±24%  1.53 ±45%   -7.87%  (p=0.006 n=50+50)
Test/postgis_geometry_tutorial/11.6    1.61 ±19%  1.66 ±32%     ~     (p=0.329 n=46+50)
Test/postgis_geometry_tutorial/12.1.2  0.89 ±26%  0.91 ±26%     ~     (p=0.532 n=46+50)
Test/postgis_geometry_tutorial/12.2.3  1.33 ±20%  1.38 ±36%     ~     (p=0.308 n=49+49)
Test/postgis_geometry_tutorial/12.2.4  1.30 ±27%  1.29 ±18%     ~     (p=0.746 n=49+45)
Test/postgis_geometry_tutorial/13.0    1.49 ±36%  1.55 ±33%     ~     (p=0.141 n=49+50)
Test/postgis_geometry_tutorial/13.1a    233 ± 7%   197 ± 7%  -15.45%  (p=0.000 n=48+47)
Test/postgis_geometry_tutorial/13.1c   24.9 ±15%  19.4 ±18%  -22.17%  (p=0.000 n=50+48)
Test/postgis_geometry_tutorial/13.2     309 ± 4%   257 ± 7%  -16.92%  (p=0.000 n=43+47)
Test/postgis_geometry_tutorial/14.1a   1.51 ±15%  1.70 ±16%  +12.93%  (p=0.000 n=48+44)
Test/postgis_geometry_tutorial/14.2b   6.28 ±22%  6.07 ±19%     ~     (p=0.050 n=50+45)
Test/postgis_geometry_tutorial/14.2c   3.70 ±14%  3.47 ±10%   -5.98%  (p=0.000 n=48+46)
Test/postgis_geometry_tutorial/14.3c   31.9 ±11%  25.9 ±12%  -18.60%  (p=0.000 n=48+49)
Test/postgis_geometry_tutorial/15.0    1.50 ±20%  1.50 ±20%     ~     (p=0.860 n=48+49)
```

Release justification: This is an incompatible format change,
and discussions with engineering and product indicated a
preference to do this now before we launch spatial features

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
the encoding logic and math LGTM, but i more or less skimmed the opt / rowexec bits.
one question about extending this to support knn.

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-:-MGOvVbx5dirC16IenUO:bxxag0b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/geo/geoindex/s2_geometry_index.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGOtWjJ1HI4Q-k7Mruw:-MGOtWjJ1HI4Q-k7Mrux:bbyqo70) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c02c57338637237ad8ae7b1416177175471bd9c/pkg/geo/geoindex/s2_geometry_index.go#L197)):*
> ```Go
> 	bboxRef := g.BoundingBoxRef()
> 	if bboxRef == nil && len(keys) > 0 {
> 		return keys, bbox, errors.Errorf("non-empty geometry should have bounding box")
> ```

nit: maybe `AssertionFailedf` (as with others errors.Error in this PR)?
___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGOtn_FBo23D8vG38vW:-MGOtn_FBo23D8vG38vX:b-y3vy0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c02c57338637237ad8ae7b1416177175471bd9c/pkg/sql/opt/invertedexpr/geo_expression.go#L68)):*
> ```Go
> 	}
> 	// Avoid per-span heap allocations.
> 	b := make([]byte, 0, len(ukSpans)*(2*encoding.MaxVarintLen+2))
> ```

noob question: why the +2 
___
*[pkg/util/encoding/encoding.go, line 865 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGOuhW-76yvllU5kG-o:-MGOuhW060vULLzyBGn3:bybmpyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c02c57338637237ad8ae7b1416177175471bd9c/pkg/util/encoding/encoding.go#L865)):*
> ```Go
> 	encodeTwoFloats := loX == hiX && loY == hiY
> 	if encodeTwoFloats {
> 		b = append(b, byte(geoInvertedTwoFloats))
> ```

side question: do you think this will help knn in any way? will this help/hinder sorting?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/geo/geoindex/s2_geometry_index.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGOtWjJ1HI4Q-k7Mruw:-MGPCshCD5n9oRKYY8DN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c02c57338637237ad8ae7b1416177175471bd9c/pkg/geo/geoindex/s2_geometry_index.go#L197)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: maybe `AssertionFailedf` (as with others errors.Error in this PR)?
</blockquote></details>

Done
___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGOtn_FBo23D8vG38vW:-MGPDSVCAwaeQ5pToL3R:bd31q2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c02c57338637237ad8ae7b1416177175471bd9c/pkg/sql/opt/invertedexpr/geo_expression.go#L68)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

noob question: why the +2 
</blockquote></details>

It is the 1 byte marker x 2 (two keys in a span). I've added a comment.
___
*[pkg/util/encoding/encoding.go, line 865 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGOuhW-76yvllU5kG-o:-MGPDYwA8G5H3gHRSa7L:b-1xxa9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c02c57338637237ad8ae7b1416177175471bd9c/pkg/util/encoding/encoding.go#L865)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

side question: do you think this will help knn in any way? will this help/hinder sorting?
</blockquote></details>

The sort ordering of all the rows in the index that share the same cellid is not going to be helpful, IMO. If we are reading a particular cellid, because the search has expanded to that cellid, we will want to read all the rows for that cellid.
___
*[pkg/util/encoding/encoding.go, line 1572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGPBv9zCmIKaheQoZBe:-MGPBvA-DRYlwuWnsEli:b-ompoxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c02c57338637237ad8ae7b1416177175471bd9c/pkg/util/encoding/encoding.go#L1572)):*
> ```Go
> 	ArrayKeyDesc Type = 23 // Array key encoded descendingly
> 	Box2D        Type = 24
> 	geoInverted  Type = 25 // Not exported since only used for pretty-printing
> ```

I've undone this pretty printing change since it is hard to make it work: the code also pretty prints cases where we have a span for reading, which only has the cellid. And I can't hack it to just read the uvarint if there is nothing left in the `[]byte` because there is a fallback path in `PrettyPrintValue` when it isn't a uvarint that tries to undo the effect of `PrefixEnd`.

**Review by rytaft — APPROVED** [review]
:lgtm: Nice work! Just some nits below...

> Reviewed 22 of 26 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-:-MG_9W4F7eSE1rss2PpB:bm419on)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGZxtswAwhTM-cZ7Uxc:-MGZxtsxA7R_cO0-wN-L:b-8jt2yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedexpr/expression.go#L52)):*
> ```Go
> 	// index that has a true value. PreFilter must only be called when CanPreFilter()
> 	// is true. This batching of pre-filter application for a looked up row allows
> 	// enc to be decoded once.
> ```

This is all a bit abstract -- could you make it more concrete with an example?
___
*[pkg/sql/opt/invertedidx/geo.go, line 713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGZywmh7UGQQrs_0MHV:-MGZywmh7UGQQrs_0MHW:b57cy2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L713)):*
> ```Go
> 		}
> 		srid = g.SRID()
> 	}
> ```

probably still worth adding a `default` case with a panic just to be safe...
___
*[pkg/sql/opt/invertedidx/geo.go, line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4xVh1Bc6BmfChv0k:-MG_4xVh1Bc6BmfChv0l:b-rdetyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L725)):*
> ```Go
> // PreFilter pre-filters a retrieved inverted values against a set
> // of pre-filter states.
> func (p *PreFilterer) PreFilter(
> ```

What does the state returned in `result` mean v. the single boolean return value?
___
*[pkg/sql/opt/invertedidx/geo.go, line 745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_-6D67uRB3FCupDgF:-MG_-6D67uRB3FCupDgG:b-hhbtsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L745)):*
> ```Go
> 		}
> 		rv := false
> 		for i := range preFilters {
> ```

why would we have multiple `preFilters`?
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_0xPD7GFT62DqZ_Xa:-MG_0xPD7GFT62DqZ_Xb:b-p14wq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo_test.go#L525)):*
> ```Go
> 			shapes:       geoShapes,
> 			expected: [][]bool{
> 				{true, false, false, true}, {false, true, false, true}, {false, false, true, false},
> ```

[nit] I think this would be easier to read if the four rows were stacked on top of each other like a matrix

Also, would be good to add a comment somewhere explaining what this is testing. It seems like you're comparing each of the four shapes above with each other, but making that explicit would help.

Are there any tests here where the preFilter returns true but the final result would be false? Might help to note that with a comment.
___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4Pdb4Dg4nqxG0On_:-MG_4Pdb4Dg4nqxG0Ona:b-ys3uoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/rowexec/inverted_expr_evaluator.go#L373)):*
> ```Go
> 				append(nextSpan.exprAndSetIndexList, pendingSpans[i].exprAndSetIndexList...)
> 		}
> 		sort.Sort(exprAndSetIndexSorter(nextSpan.exprAndSetIndexList))
> ```

[nit] add a comment to explain what this block of code is doing
___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4Vcp6P5IZvHtp537:-MG_4Vcp6P5IZvHtp538:btvimbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/rowexec/inverted_expr_evaluator.go#L482)):*
> ```Go
> // TODO(sumeer): if this will be called in non-decreasing order of enc,
> // use that to optimize the binary search.
> func (b *batchedInvertedExprEvaluator) prepareAddIndexRow(
> ```

[nit] add a comment to explain what is happening here in `prepareAddIndexRow` v. `addIndexRow`. Also explain what the return value means.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!
I've addressed the comments.
I need to get to the bottom of the failure in `TestStats/inverted-geo` caused by a plan change -- it has chosen to use the invertedFilterer. https://teamcity.cockroachdb.com/viewLog.html?buildId=2249375&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-:-MGiZlxT2zB5fLYmF9m0:b-bjtrkl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGZxtswAwhTM-cZ7Uxc:-MGiZby3AFMEz7CUJ6vw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedexpr/expression.go#L52)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is all a bit abstract -- could you make it more concrete with an example?
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/geo.go, line 713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGZywmh7UGQQrs_0MHV:-MGiJJnRDIy9e8M8Sfw2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L713)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

probably still worth adding a `default` case with a panic just to be safe...
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/geo.go, line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4xVh1Bc6BmfChv0k:-MGiKDmWAC-feHwt85yu:b-dy0rk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L725)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What does the state returned in `result` mean v. the single boolean return value?
</blockquote></details>

Added a comment. It represents whether there is at least one `result` with a true value.
___
*[pkg/sql/opt/invertedidx/geo.go, line 745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_-6D67uRB3FCupDgF:-MGiKKnW5u3aV1aodYsU:bmrg1ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L745)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why would we have multiple `preFilters`?
</blockquote></details>

Each of the left-side in a batch has a pre-filter extracted for it (the bounding box and SRID).
There is a comment where `DatumsToInvertedExpr` is declared that motivates this: "This batching of pre-filter application for a looked up row allows enc to be decoded once."
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_0xPD7GFT62DqZ_Xa:-MGiLnzr4ARlIVrsjpaP:bmztkaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo_test.go#L525)):*
> [nit] I think this would be easier to read if the four rows were stacked on top of each other like a matrix

Done

> Also, would be good to add a comment somewhere explaining what this is testing. It seems like you're comparing each of the four shapes above with each other, but making that explicit would help.

Added a comment

> Are there any tests here where the preFilter returns true but the final result would be false? Might help to note that with a comment.

I've added a test where all the results are false, so the return value would be false. 
___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4Pdb4Dg4nqxG0On_:-MGiVxDv7cUEdiReWiTH:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/rowexec/inverted_expr_evaluator.go#L373)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] add a comment to explain what this block of code is doing
</blockquote></details>

Done
___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4Vcp6P5IZvHtp537:-MGiWxeR7JoBIuGxn_zR:b-ho7sx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/rowexec/inverted_expr_evaluator.go#L482)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] add a comment to explain what is happening here in `prepareAddIndexRow` v. `addIndexRow`. Also explain what the return value means.
</blockquote></details>

Done. Also removed the unused parameter from `addIndexRow`

**Review by sumeerbhola — COMMENTED** [review]
> failure in TestStats/inverted-geo caused by a plan change -- it has chosen to use the invertedFilterer

it is fixed now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-:-MGigRefB3DW6e2Su4v9:b-qxtidg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

**Review by rytaft — APPROVED** [review]
> Reviewed 7 of 7 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGZxtswAwhTM-cZ7Uxc:-MGicrFUBnsgZ0AvcHn6:b-9zpon1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedexpr/expression.go#L52)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It might also help to give some hint about what the `interface{}` objects contain.
___
*[pkg/sql/opt/invertedidx/geo.go, line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4xVh1Bc6BmfChv0k:-MGie5wUC9dFDHGgzZMH:bfek8lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L725)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Added a comment. It represents whether there is at least one `result` with a true value.
</blockquote></details>

Ah, didn't realize this was the interface implementation. I think it's more common to have a comment like `// PreFilter is part of the DatumsToInvertedExpr interface.`, and put all the relevant info on the interface method.
___
*[pkg/sql/opt/invertedidx/geo.go, line 714 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGidvQkA3V2p9w4-C2r:-MGidvQkA3V2p9w4-C2s:b-a3sakj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d83c18277c3a636a689b4a4a490282699d9aa4f/pkg/sql/opt/invertedidx/geo.go#L714)):*
> ```Go
> 		srid = g.SRID()
> 	default:
> 		panic(errors.Errorf("datum of unhandled type: ", d))
> ```

I think all these panic errors should be AssertionFailedf

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGZxtswAwhTM-cZ7Uxc:-MGj0zL13FseOKQgDqpN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedexpr/expression.go#L52)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It might also help to give some hint about what the `interface{}` objects contain.
</blockquote></details>

Done
___
*[pkg/sql/opt/invertedidx/geo.go, line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MG_4xVh1Bc6BmfChv0k:-MGj1M2TCLsDZqnbRKb6:bsd9yl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6ff8a7afdcf0cb31035c18d9a3e690de8506840/pkg/sql/opt/invertedidx/geo.go#L725)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ah, didn't realize this was the interface implementation. I think it's more common to have a comment like `// PreFilter is part of the DatumsToInvertedExpr interface.`, and put all the relevant info on the interface method.
</blockquote></details>

The same thing is stated in `DatumsToInvertedExpr`. I've updated the comment to state that `PreFilterer` does not implement the full interface (which is why the comment was not saying "PerFilter is part of the ..." -- I thought it may mislead the reader).
___
*[pkg/sql/opt/invertedidx/geo.go, line 714 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGidvQkA3V2p9w4-C2r:-MGj22Dm9KaOjDOaKcN4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d83c18277c3a636a689b4a4a490282699d9aa4f/pkg/sql/opt/invertedidx/geo.go#L714)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think all these panic errors should be AssertionFailedf
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/invertedidx/geo.go, line 727 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGj81AP0In_fjo9q7mZ:-MGj81AP0In_fjo9q7m_:b-i8vpv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30d0da881969fe010e4146b5a061efd949cc6e3/pkg/sql/opt/invertedidx/geo.go#L727)):*
> ```Go
> // PreFilter pre-filters a retrieved inverted value against a set of
> // pre-filter states. The function signature matches the PreFilter function of
> // the DatumsToInvertedExpr interface (PreFilterer does not implment the full
> ```

implment -> implement

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53963)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/sql/opt/invertedidx/geo.go, line 727 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/53963#-MGj81AP0In_fjo9q7mZ:-MGjLaB_03PCQnkkwn-T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30d0da881969fe010e4146b5a061efd949cc6e3/pkg/sql/opt/invertedidx/geo.go#L727)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

implment -> implement 
</blockquote></details>

Done.

**Pull request merged**
