### PR TITLE
kvserver: add hidden cluster setting kv.gc.intent_age_threshold

### LINKED ISSUE #61654: kv: make IntentAgeThreshold a cluster setting
See https://github.com/cockroachdb/cockroach/issues/60585#issuecomment-780851425.

Combined with #60619, this should give us a better toolbox to resolve intent buildup issues manually when they come up, until we eliminate the problem entirely.

### PR DESCRIPTION
**Pull request by aliher1911**
Added hidden cluster setting to change intent age threshold.

Fixes #61654
 
Setting is read on queue level and passed to GC as an arg. This is done to avoid passing cluster setting to GC directly as it currently decoupled from the cluster infrastructure.

### CODE REVIEW

**Comment by aliher1911** [comment]
Advice regarding setting name and its location appreciated.
I briefly looked on how we name settings. Can't see a lot of consistency there.

**Review by nvb — COMMENTED** [review]
Nice! We're somewhat lacking in testing directly in `pkg/kv/kvserver/gc` because the package was recently extracted from the rest of the kvserver. But we shouldn't let that stop us from trying to write a test for this in `gc_test.go`. I think `gc.Run` is mocked out sufficiently that we can test this out by creating a `storage.Engine` with an intent in it, passing in a large threshold and making sure that an intent is not passed to `cleanupIntentsFn`, and then passing in a smaller threshold and making sure that an intent is not passed to `cleanupIntentsFn`.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-:-MWaPhNwDKAYNhlEsz3j:b-e9r30y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/cli/debug.go, line 578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWaNbzOEgY_KnQdQiy4:-MWaNbzOEgY_KnQdQiy5:b-ahl1cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b2d06cecdf809fbf8a141ff575be9d7b71b6341/pkg/cli/debug.go#L578)):*
> ```Go
> 	var rangeID roachpb.RangeID
> 	gcTTLInSeconds := int64((24 * time.Hour).Seconds())
> 	intentAgeThresholdSeconds := int64((2 * time.Hour).Seconds())
> ```

Let's keep this as a `time.Duration` type, not an `int64` so we don't need the conversion down below.

Also, I'm thinking we should set this to `gc.IntentAgeThreshold`'s default value. But that doesn't seem too easy to access. What do you think about exposing a `Default` method (similar to `EncodedDefault`) on each `Setting` type?
___
*[pkg/kv/kvserver/gc/gc.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWaPmHa3AmB8sqPIicv:-MWaPmHa3AmB8sqPIicw:b-awm2kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b2d06cecdf809fbf8a141ff575be9d7b71b6341/pkg/kv/kvserver/gc/gc.go#L51)):*
> ```Go
> // will be resolved.
> var IntentAgeThreshold = settings.RegisterDurationSetting(
> 	"kv.gc.intent_age_threshold",
> ```

This name and the location of the setting LGTM.
___
*[pkg/kv/kvserver/gc/gc.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWaPBtZ5KT8fgGRoCnZ:-MWaPBt_DTG0oSew4Irr:bvlm9xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b2d06cecdf809fbf8a141ff575be9d7b71b6341/pkg/kv/kvserver/gc/gc.go#L52)):*
> ```Go
> var IntentAgeThreshold = settings.RegisterDurationSetting(
> 	"kv.gc.intent_age_threshold",
> 	"age threshold for intent resolution during GC operation",
> ```

Let's add a bit more to this descriptor to explain what it means for an intent to fall above or below this threshold.

**Review by aliher1911 — COMMENTED** [review]
I'm trying to adapt uniformDistSpec to produce gc test data to add a test. Unless there's a better way to insert objects without creating quite a bit of context that setupTest from data_distribution provides.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-:-MWe2O-h08hRkkiMRrF7:b-tga959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/cli/debug.go, line 578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWaNbzOEgY_KnQdQiy4:-MWd2rsG5SyBksz98k0U:b75v698) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b2d06cecdf809fbf8a141ff575be9d7b71b6341/pkg/cli/debug.go#L578)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's keep this as a `time.Duration` type, not an `int64` so we don't need the conversion down below.

Also, I'm thinking we should set this to `gc.IntentAgeThreshold`'s default value. But that doesn't seem too easy to access. What do you think about exposing a `Default` method (similar to `EncodedDefault`) on each `Setting` type?
</blockquote></details>

Something in these lines: #62592 (settings: add default value accessors for settings)  ?
I would make those separate commits in pull request for readability then so we don't mix plumbing with actual change.

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/cli/debug.go, line 578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWaNbzOEgY_KnQdQiy4:-MWgcSIf9bA3UwBJORfv:b4692gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b2d06cecdf809fbf8a141ff575be9d7b71b6341/pkg/cli/debug.go#L578)):*
> Something in these lines: #62592 (settings: add default value accessors for settings)  ?

Yes, exactly.

> I would make those separate commits in pull request for readability then so we don't mix plumbing with actual change.

:thumbsup: 
___
*[pkg/cli/debug.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWgcGzl0FQOMp1_aSnE:-MWgcGzl0FQOMp1_aSnF:bcg2gh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c375dd05649b3374d5bb8b2f41bf6a9f5067678/pkg/cli/debug.go#L119)):*
> ```
> #{i}
> ```

Wrong langauge? :smiley: 
___
*[pkg/kv/kvserver/gc/gc.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWaPBtZ5KT8fgGRoCnZ:-MWgd4qS1GxP-0eTiO71:b-lw0evl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b2d06cecdf809fbf8a141ff575be9d7b71b6341/pkg/kv/kvserver/gc/gc.go#L52)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's add a bit more to this descriptor to explain what it means for an intent to fall above or below this threshold.
</blockquote></details>

This looks better, but maybe consider just a bit of a tweak to help people unfamiliar with this understand:
```
intents older than this threshold will be resolved when encountered by the GC queue
```
___
*[pkg/kv/kvserver/gc/gc_test.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWge1gp5b-b2j8HArfH:-MWge1gp5b-b2j8HArfI:b-2i2w83) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c375dd05649b3374d5bb8b2f41bf6a9f5067678/pkg/kv/kvserver/gc/gc_test.go#L96)):*
> ```Go
> }
> 
> // TestIntentAgeThresholdSetting test verifies that resolution threshold could be adjusted
> ```

`s/test verifies ... it uses/verifies that the GC intent resolution threshold can be adjusted. It uses/`
___
*[pkg/kv/kvserver/gc/gc_test.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWgeQjF8QF6awMASdPA:-MWgeQjF8QF6awMASdPB:bw2nym6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c375dd05649b3374d5bb8b2f41bf6a9f5067678/pkg/kv/kvserver/gc/gc_test.go#L122)):*
> ```Go
> 
> 	intentTs := now - (intentShortThreshold+intentLongThreshold)/2
> 	distSpec := uniformDistSpec{
> ```

Yeah, I think we should try to avoid `uniformDistSpec` and just write the single intent that we want into the engine. This is a pretty heavyweight dependency and we don't really need much from it.

I think the code would look something like:
```go
txn = &roachpb.Transaction{
	TxnMeta: enginepb.TxnMeta{
		Key:            roachpb.Key("key"),
		ID:             uuid.MakeV4(),
		Epoch:          1,
		WriteTimestamp: intentTs,
	},
	Status:                 roachpb.PENDING,
	ReadTimestamp: intentTs,
}
val := roachpb.MakeValueFromString("val")
require.NoError(t, storage.MVCCPut(ctx, eng, nil, kv.Key.Key, intentTs, val, txn))
require.NoError(t, eng.Flush())
```
___
*[pkg/kv/kvserver/gc/gc_test.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWgfi9m9--wM0RM1DtH:-MWgfi9n-jPO4Zy_9YCz:b-w75do9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c375dd05649b3374d5bb8b2f41bf6a9f5067678/pkg/kv/kvserver/gc/gc_test.go#L141)):*
> ```Go
> 	info, err := Run(ctx, &desc, snap, nowTs, nowTs, intentLongThreshold, policy, &fakeGCer, fakeGCer.resolveIntents,
> 		fakeGCer.resolveIntentsAsync)
> 	if err != nil {
> ```

Over the past few years, we've started using the `require` library more and more. It gives up a small degree of type safety, but in exchange, leads to significantly denser assertion logic, which we found has led to engineers writing more tests and more comprehensive tests.

So this would become:
```go
require.NoError(t, err)
require.Equal(t, 0, info.IntentsConsidered)
```

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/gc/gc_test.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWgfi9m9--wM0RM1DtH:-MWiHYl5CMYAvq-1Z3TE:b-rh1aez) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c375dd05649b3374d5bb8b2f41bf6a9f5067678/pkg/kv/kvserver/gc/gc_test.go#L141)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Over the past few years, we've started using the `require` library more and more. It gives up a small degree of type safety, but in exchange, leads to significantly denser assertion logic, which we found has led to engineers writing more tests and more comprehensive tests.

So this would become:
```go
require.NoError(t, err)
require.Equal(t, 0, info.IntentsConsidered)
```
</blockquote></details>

I was after something like that, because plain comparisons are not expressive enough for tests imho, this is much better!

**Review by nvb — APPROVED** [review]
:lgtm: pending a few nits. Thanks for doing this!

> Reviewed 1 of 8 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-:-MWkWcVvEwzHKRqD1fTI:b8zr60n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/kv/kvserver/gc/gc_test.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWkWQhECdrZSjlaiBCu:-MWkWQhECdrZSjlaiBCv:bjqkr5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/26bacf71d0d135f18691644a0a61d4630aeb117f/pkg/kv/kvserver/gc/gc_test.go#L98)):*
> ```Go
> // adjusted. It uses short and long threshold to verify that intents inserted between two
> // thresholds are not considered for resolution when threshold is high (1st attempt) and
> // considered when threshold is low (2nd attempt.)
> ```

nit: period on the outside of the parens.
___
*[pkg/kv/kvserver/gc/gc_test.go, line 106 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/62519#-MWkW2aJ5QAjQD6JHm-z:-MWkW2aK2Qt9aPQG4hSU:b-66eb68) ([raw file](https://github.com/cockroachdb/cockroach/blob/26bacf71d0d135f18691644a0a61d4630aeb117f/pkg/kv/kvserver/gc/gc_test.go#L106)):*
> ```Go
> 	defer eng.Close()
> 
> 	// Test event timeline
> ```

nit: our [style guide](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines), which pulls from https://golang.org/doc/effective_go#commentary, mandates proper punctuation in comments. So let's add periods at the end of each of these comments.

**Comment by aayushshah15** [comment]
Do we plan on backporting this to 20.2?

**Pull request merged**
