### PR TITLE
colexec: fix bug where vectorized engine couldn't use inverted indexes

### LINKED ISSUE #46183: colexec: v19.2.4: assertion failed while skipping json column that is not needed
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1568549881/?referrer=webhooks_plugin

Panic message:

>*errors.errorString
*safedetails.withSafeDetails: unsupported type %+v (1)
column_type_encoding.go:226: *withstack.withStack (2)
*assert.withAssertionFailure
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/sqlbase/column_type_encoding.go#L225-L227 in pkg/sql/sqlbase.SkipTableKey
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colencoding/key_encoding.go#L143-L145 in pkg/sql/colencoding.DecodeKeyValsToCols
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colencoding/key_encoding.go#L100-L102 in pkg/sql/colencoding.DecodeIndexKeyToCols
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/cfetcher.go#L613-L615 in pkg/sql/colexec.(*cFetcher).NextBatch
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/colbatch_scan.go#L71-L73 in pkg/sql/colexec.(*colBatchScan).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/cancel_checker.go#L46-L48 in pkg/sql/colexec.(*CancelChecker).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/simple_project.go#L93-L95 in pkg/sql/colexec.(*simpleProjectOp).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/materializer.go#L148-L150 in pkg/sql/colexec.(*Materializer).next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/materializer.go#L139-L141 in pkg/sql/colexec.(*Materializer).nextAdapter
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/execerror/error.go#L90-L92 in pkg/sql/colexec/execerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/materializer.go#L176-L178 in pkg/sql/colexec.(*Materializer).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/execinfra/indexjoiner.go#L153-L155 in pkg/sql/execinfra.(*IndexJoiner).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/columnarizer.go#L101-L103 in pkg/sql/colexec.(*Columnarizer).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/count.go#L61-L63 in pkg/sql/colexec.(*countOp).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/deselector.go#L48-L50 in pkg/sql/colexec.(*deselectorOp).Next
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colflow/colrpc/outbox.go#L216-L218 in pkg/sql/colflow/colrpc.(*Outbox).sendBatches.func1
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colexec/execerror/error.go#L90-L92 in pkg/sql/colexec/execerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colflow/colrpc/outbox.go#L223-L225 in pkg/sql/colflow/colrpc.(*Outbox).sendBatches
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colflow/colrpc/outbox.go#L303-L305 in pkg/sql/colflow/colrpc.(*Outbox).runWithStream
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colflow/colrpc/outbox.go#L163-L165 in pkg/sql/colflow/colrpc.(*Outbox).Run
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colflow/vectorized_flow.go#L263-L265 in pkg/sql/colflow.(*vectorizedFlowCreator).setupRemoteOutputStream.func1
https://github.com/cockroachdb/cockroach/blob/eb883734bcdafd85d98eb0e49126749bc2cc1284/pkg/sql/colflow/vectorized_flow.go#L738-L740 in pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1
/usr/local/go/src/runtime/asm_amd64.s#L1336-L1338 in runtime.goexit
</details>

```
pkg/sql/sqlbase/column_type_encoding.go in pkg/sql/sqlbase.SkipTableKey at line 226
pkg/sql/colencoding/key_encoding.go in pkg/sql/colencoding.DecodeKeyValsToCols at line 144
pkg/sql/colencoding/key_encoding.go in pkg/sql/colencoding.DecodeIndexKeyToCols at line 101
pkg/sql/colexec/cfetcher.go in pkg/sql/colexec.(*cFetcher).NextBatch at line 614
pkg/sql/colexec/colbatch_scan.go in pkg/sql/colexec.(*colBatchScan).Next at line 72
pkg/sql/colexec/cancel_checker.go in pkg/sql/colexec.(*CancelChecker).Next at line 47
pkg/sql/colexec/simple_project.go in pkg/sql/colexec.(*simpleProjectOp).Next at line 94
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 149
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 140
pkg/sql/colexec/execerror/error.go in pkg/sql/colexec/execerror.CatchVectorizedRuntimeError at line 91
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 177
pkg/sql/execinfra/indexjoiner.go in pkg/sql/execinfra.(*IndexJoiner).Next at line 154
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 102
pkg/sql/colexec/count.go in pkg/sql/colexec.(*countOp).Next at line 62
pkg/sql/colexec/deselector.go in pkg/sql/colexec.(*deselectorOp).Next at line 49
pkg/sql/colflow/colrpc/outbox.go in pkg/sql/colflow/colrpc.(*Outbox).sendBatches.func1 at line 217
pkg/sql/colexec/execerror/error.go in pkg/sql/colexec/execerror.CatchVectorizedRuntimeError at line 91
pkg/sql/colflow/colrpc/outbox.go in pkg/sql/colflow/colrpc.(*Outbox).sendBatches at line 224
pkg/sql/colflow/colrpc/outbox.go in pkg/sql/colflow/colrpc.(*Outbox).runWithStream at line 304
pkg/sql/colflow/colrpc/outbox.go in pkg/sql/colflow/colrpc.(*Outbox).Run at line 164
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupRemoteOutputStream.func1 at line 264
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1 at line 739
/usr/local/go/src/runtime/asm_amd64.s in runtime.goexit at line 1337
```

| Tag | Value |
|---|---|
| Cockroach Release | `v19.2.4` |
| Cockroach SHA: | eb883734bcdafd85d98eb0e49126749bc2cc1284 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v19.2.4 |
| Command | server |
| Go Version | `go1.12.12`|
| # of CPUs |2 |
| # of Goroutines |230 |

### PR DESCRIPTION
**Pull request by rohany**
Fixes #46183.

Release justification: bug fix

Release note (bug fix): This PR fixes a bug where the vectorized
engine would throw an internal error when executing a query that
utilized an inverted index.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Nice find, thank you for the fix. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46267#-:-M2km1xA4oV2l_dkA-7C:b-9cw881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rohany)

___
*[pkg/util/encoding/encoding.go, line 1370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46267#-M2kls5pBI10Pz4FKa8A:-M2kls5pBI10Pz4FKa8B:b-c00n0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/240947ff52d1b0083be10d627c7578e22be169e5/pkg/util/encoding/encoding.go#L1370)):*
> ```Go
> // index key in an encoded key. It will throw an assertion error
> // if the next data value in the key is not an inverted index key.
> func SkipJSONInvertedIndexKey(b []byte) ([]byte, error) {
> ```

Can you add a test for this function specifically? `pkg/util/json/json_test.go` has other inverted index key tests that you could hijack. I recommend inserting a test per test case that makes sure that all of the encoded keys can be skipped properly.

**Comment by rohany** [comment]
Added a test!

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @rohany)

___
*[pkg/sql/sqlbase/column_type_encoding.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46267#-M2n_aGe4rIgRsJwrk2-:-M2n_aGe4rIgRsJwrk20:br8j0xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88c1452b8275405301afb7ccb1cab64f71a01de/pkg/sql/sqlbase/column_type_encoding.go#L228)):*
> ```Go
> 		}
> 	case types.JsonFamily:
> 		rkey, err = encoding.SkipJSONInvertedIndexKey(key)
> ```

I remember that there was some reason not to use `PeekLength` in these cases but can't remember why, do you know? If there's a good reason, this seems like we're effectively using `PeekLength` for `JsonFamily`, is this ok?

**Comment by rohany** [comment]
> I remember that there was some reason not to use PeekLength in these cases but can't remember why, do you know? If there's a good reason, this seems like we're effectively using PeekLength for JsonFamily, is this ok?

I wasn't aware of any -- I came across this solution by studying what the row fetcher did to decode/skip json keys

**Review by asubiotto — COMMENTED** [review]
Oh, I *think* it was that `PeekLength` should only be used for values, not keys, guess this makes sense for this case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46267#-:-M2nay4U8r1x7fbwNhY7:b-zd7czn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
The peek length code seems like it works on keys -- do you remember where the discussion about this was?

**Review by asubiotto — COMMENTED** [review]
Here it is: https://github.com/cockroachdb/cockroach/pull/42616#pullrequestreview-320561591

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46267#-:-M2ncZOpEbshnbuUtMRZ:b-3um8sn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
Hmm -- @jordanlewis can you clarify / double check your comment there? I think it's incorrect -- `PeekLength` is used for keys, and `PeekValueLength` is used for values. @asubiotto's original implementation for `SkipTableKey` seems correct and we'd avoid these random errors in the future by using it.

**Review by jordanlewis — COMMENTED** [review]
Yeah, I think you're right. Sorry for the original misfire...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46267#-:-M2qEsCr7Eyr5UgA3CaK:b-q37sj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
updated, PTAL

**Comment by asubiotto** [comment]
LGTM but I'll defer to @jordanlewis

**Review by jordanlewis — COMMENTED** [review]
:lgtm_strong: curious to see a basic benchmark - i think this might help things appreciably!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46267#-:-M38Lo2v7O9FyCLN784O:b-gob30v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
Small benchmark here (not sure whether I should check it in though)
```
Master
BenchmarkVecSkipScan/Bench_scan_with_skip-16         	2000	   1106103 ns/op
Vec-Json
BenchmarkVecSkipScan/Bench_scan_with_skip-16         	2000	   1085575 ns/op
```

The benchmark creates a table with 6 columns, all in the primary key, and then selects only 1 of the columns. Turns out theres no real improvement for large strings because the decode and peek methods on strings are basically the same.

**Comment by jordanlewis** [comment]
Cool. Might as well check it in.

**Comment by rohany** [comment]
bors r=jordanlewis

**Pull request merged**
