### PR TITLE
sql: use IndexFetchSpec for inverted joiner

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### rowexec: address TODO in inverted joiner

This commit addresses a TODO in the inverted joiner. We now reuse a
buffer for encoding the prefix key. In the general case we still need
to make a copy since we are storing multiple prefix keys; but now we
try to reuse the last copy if the prefix is the same.

We also remove the temporary use of `indexRow` which is confusing here
(it wasn't obvious at first but this code has nothing to do with index
rows and is just using `indexRow` as a temporary buffer).

Release note: None

#### geoindex: minor cleanup around Config

This change changes `IsEmptyConfig`, `IsGeographyConfig`,
`IsGeometryConfig` to methods on the `geoindex.Config` type.

We also switch to passing configs by value which is cleaner and avoids
some allocations.

Release note: None

#### sql: use IndexFetchSpec for inverted joiner

This commit reworks the InvertedJoiner to use an IndexFetchSpec
instead of table and index descriptors.

The "internal schema" now matches the fetched columns (leading to
simplifications in both planning and execution code).

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice cleanup! :lgtm:

> Reviewed 2 of 2 files at r1, 17 of 17 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77875#-:-MyFj0Qm2GtqUrDN4wMR:b-jy7zf3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77875#-MyFfL6B6BlfCRqowo-H):*
nit: "change changes" sounds not good :)
___
*[pkg/sql/opt/cat/index.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77875#-MyFfj725QmZHp7L1Dc1:-MyFfj725QmZHp7L1Dc2:b-wksk1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e4502ab7e0de145b4810b493e21863b117f921/pkg/sql/opt/cat/index.go#L190)):*
> ```Go
> 	ImplicitPartitioningColumnCount() int
> 
> 	// GeoConfig returns a geospatial index configuration. If non-nil, it
> ```

nit: "not-nil" is no longer applicable.
___
*[pkg/sql/rowexec/inverted_joiner.go, line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77875#-MyFdxyNCUqXw1-z2NUM:-MyFdxyO9Oe2M3yeg1SD:b-oqsztv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad8fb2638566322ac1414081d9dc121f73b8c9d/pkg/sql/rowexec/inverted_joiner.go#L459)):*
> ```Go
> 			} else {
> 				keyCols := ij.desc.IndexFetchSpecKeyAndSuffixColumns(ij.index)
> 				// Encode the prefix key; we reuse a buffer to avoid extra allocations when appending values.
> ```

nit: seems like a long line.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77875#-:-MyNfzXW6RunKm2MfC_M:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

**Review by mgartner — APPROVED** [review]
:lgtm: Nice cleanup! Sorry for the late drive-by.

> Reviewed 1 of 2 files at r1, 34 of 34 files at r4, 17 of 17 files at r5, 18 of 18 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77875#-:-MyO-3VS5OSOusRKIh9p:bb00iky)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/geo/geoindex/config.go, line 14 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77875#-MyNz1u30pnjrhgzqwkh:-MyNz1u30pnjrhgzqwki:b6jm4vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f85a0b6586dd59eca12468de40ec694cbf3ab71/pkg/geo/geoindex/config.go#L14)):*
> ```Go
> 
> // IsEmpty returns whether the config contains a geospatial index
> // configuration.
> ```

nit: I know you just copied the comments from before, but "returns whether ..." is less clear than "returns true if ...". Ditto for the other comments below.

**Pull request merged**
