### PR TITLE
kvserver: deflake TestRollbackSyncRangedIntentResolution

### PR DESCRIPTION
**Pull request by erikgrinaker**
Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
How long does the test take to run? The Bazel test is configured to time out after 900 seconds, and that's with concurrency so other tests will slow it down as well.

**Comment by erikgrinaker** [comment]
It's running a performance regression test with a hardcoded timeout of 20 seconds for a rollback operation (bumped to 30 seconds here). The point of the test is to make sure it completes within a reasonable timeframe, i.e. the timeout is the test objective, so we need predictable performance on CI runs.

**Comment by andreimatei** [comment]
:LGTM:

**Comment by andreimatei** [comment]
The [bazel build](https://github.com/cockroachdb/cockroach/blob/d50207096369e6aa673d9701879e264fdad491a2/build/bazelutil/bazeltest.sh#L6) seems to just do 
```
bazci test //pkg:small_tests //pkg:medium_tests //pkg:large_tests //pkg:enormous_tests
```

The [non-bazel build](https://github.com/cockroachdb/cockroach/blob/036d9ff2b3247933884fd1214344e85b8a066254/build/teamcity-test.sh#L21) just does `make test`. I'm surprised that we don't control the inter-package parallelism in this build (`-p`). We do it for a bunch of other builds (anything under stress or race for sure).
So I guess my question is what's the inter-package parallelism for the bazel run? Looking at a random run, the bazel build took 6min whereas the regular one took 46min. Don't know what to make of that.


Btw, @rickystewart, as you bazelize all the builds, don't forget to port over [the stressing of new tests](https://github.com/cockroachdb/cockroach/blob/036d9ff2b3247933884fd1214344e85b8a066254/build/teamcity-test.sh#L18). That has proven to be a great idea over the years.

**Comment by rickystewart** [comment]
> It's running a performance regression test with a hardcoded timeout of 20 seconds for a rollback operation (bumped to 30 seconds here). The point of the test is to make sure it completes within a reasonable timeframe, i.e. the timeout is the test objective, so we need predictable performance on CI runs.

Sorry, I didn't mean this specific test you're updating in this PR. I meant all the tests in the package, i.e., `go test ./pkg/kv/kvserver`. That's what would be timing out in the Bazel case.

> So I guess my question is what's the inter-package parallelism for the bazel run?

Not really sure what question you're asking here. The Bazel test runner is different from the Go test runner and there isn't a 1:1 correspondence between Go command-line flags like `-p`.

> Looking at a random run, the bazel build took 6min whereas the regular one took 46min. Don't know what to make of that.

I can't find the run you're talking about, but there's going to be (significant) variance. Bazel test results are cached, whereas the "regular" tests are never cached.

**Comment by erikgrinaker** [comment]
>>It's running a performance regression test with a hardcoded timeout of 20 seconds for a rollback operation (bumped to 30 seconds here). The point of the test is to make sure it completes within a reasonable timeframe, i.e. the timeout is the test objective, so we need predictable performance on CI runs.
>
>Sorry, I didn't mean this specific test you're updating in this PR. I meant all the tests in the package, i.e., `go test ./pkg/kv/kvserver`. That's what would be timing out in the Bazel case.

No, the Bazel build is [failing](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/2992588?) with `context deadline exceeded` for this specific test because the rollback operation does not complete within the allotted 30 seconds. Locally it completes in about 7 seconds, and the normal CI run succeeds within the 20 second deadline, so it's taking significantly longer with Bazel CI.

**Comment by rickystewart** [comment]
> No, the Bazel build is [failing](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/2992588?) with `context deadline exceeded` for this specific test because the rollback operation does not complete within the allotted 30 seconds. Locally it completes within seconds, and the normal CI run succeeds within the 20 second deadline, so it's taking significantly longer with Bazel CI.

Ah, thanks for the pointer :) Yeah, concurrency is probably going to be much higher for the Bazel test. No, the test runs on the same machine in either the Bazel- or non-Bazel case.

I don't have any easy answers for you right now, but `skip.UnderBazelWithIssue()` exists if you just want to get this change landed/get rid of the Bazel flake.

**Comment by erikgrinaker** [comment]
Thanks @rickystewart, added #65407 to track the Bazel concurrency issue and skipped the test under Bazel.

**Comment by erikgrinaker** [comment]
@andreimatei Mind pressing the ✅ button?

**Comment by andreimatei** [comment]
LGTM

**Review by andreimatei — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
You probably want to update the PR description though :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65380#-:-Ma-yTtt962Lo-Tmcm63:b-nb2gqc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker)

**Comment by erikgrinaker** [comment]
bors r=andreimatei

**Pull request merged**
