### PR TITLE
[WIP] Split prepare and execute for the Select node and its helpers

### PR DESCRIPTION
**Pull request by knz**
Including scanNode, indexJoinNode etc.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6594)

### CODE REVIEW

**Comment by knz** [comment]
I am currently stuck at commit a1dec16fcad19c50aad3fa66ee671926248b75ce in particular, this introduces two errors (at least):

```
--- FAIL: TestLogic (0.19s)
        logic_test.go:701: testdata/aggregate:385: expected:
                "0"  "group"  "COUNT(k)"    
                "1"  "scan"   "kv@primary"  
                but found:
                "0"  "group"  "COUNT(k)"    
                "1"  "scan"   "kv@primary -"  
```

and

```
--- FAIL: TestRaceWithBackfill (3.52s)
    [...]
        schema_changer_test.go:452: schema change DROP INDEX t.test@vidx took 167.917846ms
        schema_changer_test.go:660: e = 0, v = 4000
    [...]
        schema_changer_test.go:660: e = 3999, v = 1
        schema_changer_test.go:660: e = 4000, v = 0
        schema_changer_test.go:660: e = 4001, v = 0
        schema_changer_test.go:660: e = 4002, v = 1
   [...]
        schema_changer_test.go:660: e = 7998, v = 3997
        schema_changer_test.go:660: e = 7999, v = 3998
        schema_changer_test.go:660: e = 8000, v = 3999
        schema_changer_test.go:660: e = 8001, v = 4000
        schema_changer_test.go:671: read the wrong number of rows: e = 4001, v = 8002
```

I do not yet understand these errors nor how to investigate them further.
@RaduBerinde perhaps you have an idea?

**Comment by RaduBerinde** [comment]
Hi Raphael,

For the `logic_test.go:701: testdata/aggregate:385` error, the `-` doesn't make a difference functionally but it does indicate that we are running some code that we probably shouldn't be running.

This string is supposed to show the spans (a span is a key range that we are scanning). An empty string means no spans, a `-` means a single span without any bounds (i.e. the entire table).

When we can't construct any spans (like this case, where there is no filter), `scanNode.spans` is empty. Then, when `initScan` runs, we put in a single span for the entire table: https://github.com/cockroachdb/cockroach/blob/master/sql/scan.go#L126

I'll comment on the code where I think the problem is.

I'm not familiar with the other test, maybe @andreimatei can help.

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/index_selection.go, line 85 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHPsuJXEwGx4sIgBKKb:-KHPsuJXEwGx4sIgBKKc:-526946119) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/index_selection.go#L85)):*
> ```Go
> // If preferOrderMatching is true, we prefer an index that matches the desired
> // ordering completely, even if it is not a covering index.
> func (s *scanNode) selectIndex(analyzeOrdering analyzeOrderingFn, preferOrderMatching bool) (planNode, error) {
> ```

This is a nit but I actually changed this function to not be a method on the `scanNode`. It is a higher level function than methods normally are because it can return another node that "wraps" `s`.

---

*[sql/scan.go, line 133 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHPsLhvAn62D-XkqK_h:-KHPsLhvAn62D-XkqK_i:-905822514) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/scan.go#L133)):*
> ```Go
> 	}
> 
> 	if err := n.fetcher.StartScan(n.p.txn, n.spans, n.limitHint); err != nil {
> ```

Do we call `Start()` during prepare, or for `EXPLAIN`? If yes, then calling StartScan here is incorrect. This actually sends out KV commands and retrieves the first batch of rows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594)*

**Comment by RaduBerinde** [comment]
The other failure might be the same issue - it indicates that we are reading twice the number of rows so it could be caused by reading the rows during `Start()`.

**Comment by andreimatei** [comment]
I bet the `RaceWithBackfill` test problem is that you're now calling both `start()` and `next()` before doing any backfill work, so you're probably starting by backfilling two chunks instead of one.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The other failure might be the same issue - it indicates that we are reading twice the number of rows so it could be caused by reading the rows during `Start()`.</details>


---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-:-KHQ0xgrNpQiiXraV1J7:-1926754604)*

**Comment by knz** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/index_selection.go, line 85 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHPsuJXEwGx4sIgBKKb:-KHQ6ETie7ejQ1yRCy83:-496877950) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/index_selection.go#L85)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This is a nit but I actually changed this function to not be a method on the `scanNode`. It is a higher level function than methods normally are because it can return another node that "wraps" `s`.</details>
I changed it because I was not too happy (surprised) about selectIndex modifying the scanNode in-place. This looks too much like a method to me.  I'm not sure what the best way forward is. Ideally what I'd like is that only the functions/methods in the file where the node is defined can modify the node in-place -- I want to narrow down the scope of things to look at to understand the state a node is currently in. Perhaps the right way would be to change selectIndex to construct a new scanNode instead. What do you think?

---

*[sql/scan.go, line 133 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHPsLhvAn62D-XkqK_h:-KHQ7HKjTEIbhDqTinuP:102250823) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/scan.go#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Do we call `Start()` during prepare, or for `EXPLAIN`? If yes, then calling StartScan here is incorrect. This actually sends out KV commands and retrieves the first batch of rows.</details>
Woah this is a good catch. This means we have some bugs to fix. Filed as #6613.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/index_selection.go, line 85 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHPsuJXEwGx4sIgBKKb:-KHQE8D5B4wZXuo1FRl4:402378258) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/index_selection.go#L85)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I changed it because I was not too happy (surprised) about selectIndex modifying the scanNode in-place. This looks too much like a method to me.  I'm not sure what the best way forward is. Ideally what I'd like is that only the functions/methods in the file where the node is defined can modify the node in-place -- I want to narrow down the scope of things to look at to understand the state a node is currently in. Perhaps the right way would be to change selectIndex to construct a new scanNode instead. What do you think?</details>
I see what you mean. Maybe we can move out the mutation part into a `scanNode.setupIndex()` method that we call with the index, spans etc.
`makeIndexJoin` (and the index join code in general) has the same issue. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 4 of 4 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/index_selection.go, line 424 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQGvh6gV-I6a916sEL:-KHQGvh6gV-I6a916sEM:1403039853) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eb34d2c2c5f4c6728901329b8b84ca07002c68/sql/index_selection.go#L424)):*
> ```Go
> // getQValColIdx detects whether an expression is a straightforward
> // reference to a column or index variable. In this case it returns
> // the index of that column's in the descriptor's Column[] array.
> ```

`[]Column`

---

*[sql/join.go, line 45 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQGl-pRb0Yxz4e_NIg:-KHQGl-pRb0Yxz4e_NIh:-1549438690) ([raw file](https://github.com/cockroachdb/cockroach/blob/678466bfa2573d4a412fb232baffaeeab3ff5ece/sql/join.go#L45)):*
> ```Go
> }
> 
> func (p *planner) makeIndexJoin(indexScan *scanNode, exactPrefix int) *indexJoinNode {
> ```

hm, not so sure about this change. perhaps it should be a method on `scanNode`?

---

*[sql/scan.go, line 114 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQH5umoxU036hHDUHN:-KHQH5un3c_HviB4CN14:1992467366) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/scan.go#L114)):*
> ```Go
> func (n *scanNode) Start() error {
> 	if n.scanInitialized {
> 		panic("scanNode already initialized")
> ```

why don't you return an error instead?

---

*[sql/scan.go, line 176 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQHBwtpcmsjOoXaDAU:-KHQHBwtpcmsjOoXaDAV:-440785716) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/scan.go#L176)):*
> ```Go
> 
> 	if !n.scanInitialized {
> 		panic("scanNode was not initialized")
> ```

probably want to check this before the error check now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/index_selection.go, line 424 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQGvh6gV-I6a916sEL:-KHax4Qi1bJRPkiFlh7P:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/87eb34d2c2c5f4c6728901329b8b84ca07002c68/sql/index_selection.go#L424)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `[]Column`</details>
Done.

---

*[sql/index_selection.go, line 85 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHPsuJXEwGx4sIgBKKb:-KHawj_pGcwDkEFyE4md:-662440216) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/index_selection.go#L85)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I see what you mean. Maybe we can move out the mutation part into a `scanNode.setupIndex()` method that we call with the index, spans etc.
> `makeIndexJoin` (and the index join code in general) has the same issue. </details>
Ok I have reverted this change, you convinced me it wasn't too useful. `makeIndexJoin` is a different matter entirely, I have a separate commit that makes it a method of `planner` (and that simplifies things).

---

*[sql/join.go, line 45 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQGl-pRb0Yxz4e_NIg:-KHax5X2wXhulAkv51v_:-1804616040) ([raw file](https://github.com/cockroachdb/cockroach/blob/678466bfa2573d4a412fb232baffaeeab3ff5ece/sql/join.go#L45)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> hm, not so sure about this change. perhaps it should be a method on `scanNode`?</details>
So all the nother node constructors (Delete, SelectClause, etc) are methods of planner. This node also builds a new node so it is conceptually in the same category. That's why I put it there more clearly.

---

*[sql/scan.go, line 114 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQH5umoxU036hHDUHN:-KHaxHh2F4JdZ3jZonq2:-245730928) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/scan.go#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why don't you return an error instead?</details>
I hope to remove this entire check before I submit the final version of this PR. It is there for now to debug the issue I'm having. 

---

*[sql/scan.go, line 176 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHQHBwtpcmsjOoXaDAU:-KHaxQy-UcSafoulTS7v:-1311320734) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dec16fcad19c50aad3fa66ee671926248b75ce/sql/scan.go#L176)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> probably want to check this before the error check now?</details>
Good catch. Thanks for the suggestion. (Although the check will eventually disappear.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594)*

**Comment by tamird** [comment]
I did my best, but at 13 commits, I'm declaring bankruptcy on this PR :(

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I bet the `RaceWithBackfill` test problem is that you're now calling both `start()` and `next()` before doing any backfill work, so you're probably starting by backfilling two chunks instead of one.</details>


---

Reviewed 1 of 12 files at r11, 1 of 2 files at r12, 1 of 2 files at r13, 1 of 2 files at r15, 1 of 5 files at r20, 3 of 3 files at r21, 2 of 2 files at r22, 1 of 1 files at r23, 10 of 10 files at r24.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/select_qvalue.go, line 112 \[r24\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHgao4J2Cmz4CyQxpEH:-KHgao4K03RmEXS0O5ht:1578902092) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ee4889c9a98b256e77efd3ee1db788b305e15e2/sql/select_qvalue.go#L112)):*
> ```Go
> func (q *qvalue) Walk(v parser.Visitor) parser.Expr {
> 	e, changed := parser.WalkExpr(v, q.datum)
> 	if changed {
> ```

if e, changed := ...;changed {

---

*[sql/subquery.go, line 39 \[r24\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-KHgars4ZUJrPNR9PjSv:-KHgars4ZUJrPNR9PjSw:453885197) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ee4889c9a98b256e77efd3ee1db788b305e15e2/sql/subquery.go#L39)):*
> ```Go
> 
> const (
> 	execModeExists  = 0
> ```

use iota and a custom type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6594#-:-KHgb6VtFsNW5gG2SRV1:-1728252961)*

**Comment by knz** [comment]
@tamird, agreed; I'm forking of PR #6681 to be reviewed preliminarily.

**Comment by knz** [comment]
Closing this one as it is getting unwieldy.

**Pull request closed without merging**
