### PR TITLE
*: new logging channels OPS and HEALTH

### PR DESCRIPTION
**Pull request by knz**
These two commits introduce the OPS and HEALTH channel.

See the individual commits for details.

### CODE REVIEW

**Comment by knz** [comment]
Rebased, RFAL

**Comment by knz** [comment]
I have rebased this off `master` so as to not make it dependent on #57170. Hopefully this makes it easier to review. @itsbilal can you have a look? Thanks

**Review by itsbilal — APPROVED** [review]
:lgtm: save for some minor comments

> Reviewed 15 of 15 files at r1, 48 of 48 files at r2, 4 of 4 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57171#-:-MOXy6J52S5WjMqzVeTM:bdqeqzk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/gossip/gossip.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57171#-MOXwfPY6q7eJRmrH5Gv:-MOXwfPY6q7eJRmrH5Gw:btzgzuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/61acec83628901b637261e037f98b4d8118b9706/pkg/gossip/gossip.go#L495)):*
> ```Go
> 	if newResolverFound {
> 		if log.V(1) {
> 			log.Health.Infof(ctx, "found new resolvers from storage; signaling bootstrap")
> ```

This seems more like an Ops event to me?
___
*[pkg/server/status/runtime.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57171#-MOXx3tSCkZMlC8baG_z:-MOXx3tSCkZMlC8baGa-:blv2zqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/61acec83628901b637261e037f98b4d8118b9706/pkg/server/status/runtime.go#L452)):*
> ```Go
> 	mem := gosigar.ProcMem{}
> 	if err := mem.Get(pid); err != nil {
> 		log.Health.Errorf(ctx, "unable to get mem usage: %v", err)
> ```

Also seems like more of an Ops error, as we can probably stay healthy without this? (Same for all the other calls in this method). I don't feel strongly either way though.
___
*[pkg/util/log/logconfig/testdata/yaml, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57171#-MOXxVEiAVBwi7rUOCF4:-MOXxVEiAVBwi7rUOCF5:b-uj1v2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/61acec83628901b637261e037f98b4d8118b9706/pkg/util/log/logconfig/testdata/yaml#L99)):*
> ```
> ----
> ERROR: yaml: unmarshal errors:
>   line 26: field fluent-servers not found in type logconfig.SinkConfig
> ```

Might want to remove the `fluent-servers` part from this PR.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57171)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal)

___
*[pkg/gossip/gossip.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57171#-MOXwfPY6q7eJRmrH5Gv:-MOcPKRFDI2uy1FqwqFL:b-hk0dkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/61acec83628901b637261e037f98b4d8118b9706/pkg/gossip/gossip.go#L495)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This seems more like an Ops event to me?
</blockquote></details>

yep, good catch
___
*[pkg/server/status/runtime.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57171#-MOXx3tSCkZMlC8baG_z:-MOcPXm1ABvfeXpUpsIf:b-5flfpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/61acec83628901b637261e037f98b4d8118b9706/pkg/server/status/runtime.go#L452)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Also seems like more of an Ops error, as we can probably stay healthy without this? (Same for all the other calls in this method). I don't feel strongly either way though.
</blockquote></details>

All good points. Done.
___
*[pkg/util/log/logconfig/testdata/yaml, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57171#-MOXxVEiAVBwi7rUOCF4:-MOcOoweAuVMLubpxmFi:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/61acec83628901b637261e037f98b4d8118b9706/pkg/util/log/logconfig/testdata/yaml#L99)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Might want to remove the `fluent-servers` part from this PR.
</blockquote></details>

Good point. Done.

**Comment by knz** [comment]
TFYR!

bors r=itsbilal

**Comment by knz** [comment]
bors r=itsbilal

**Pull request merged**
