### PR TITLE
gossip: callbacks take a roachpb.Value

### PR DESCRIPTION
**Pull request by tamird**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3042)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1, 11 of 11 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[storage/engine/mvcc.go, line 891 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3042#-K2gvowOIH_WFq-9Ftyh)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fe9aad8e57964fb50d4f21ff82dc567a98310d/storage/engine/mvcc.go#L891)):</sup>
you already have `expValue == nil` equal to `existVal == nil`, so you can drop the `existVal != nil`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3042)

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[storage/engine/mvcc.go, line 891 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3042#-K2gvowOIH_WFq-9Ftyh)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fe9aad8e57964fb50d4f21ff82dc567a98310d/storage/engine/mvcc.go#L891)):</sup>
Changed this up a bit.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3042)

**Comment by tschottdorf** [comment]
LGTM


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3042)

**Pull request merged**
