### PR TITLE
cli: cockroach node status should show when a node is dead

### PR DESCRIPTION
**Pull request by pananc**
related to #19924

### CODE REVIEW

**Comment by knz** [comment]
Hi @pananc! Thank you for looking into this!

:lgtm: but please 

1) insert a space between "cli:" and "cockroach" in your commit message
2) squash all the commits into one before we can merge this. Thank you!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20192#-:-KzYJFY8tyXs3MMNCZon:be22398)*

**Comment by pananc** [comment]
i do not know how to squash all the commits into one

**Comment by pananc** [comment]
i do not know how to squash all the commits into one, should i fork a new branch and patch my code on it. then new pull request to let you review?

**Comment by knz** [comment]
Thank  you! Very good work!

**Comment by pananc** [comment]
Thank you!

**Pull request merged**
