### PR TITLE
colexec: increase support of aggregate functions

### LINKED ISSUE #38823: exec: AVG aggregator should support ints
Currently only Decimal, Float32, and Float64 are supported (see avg_agg_gen.go).

It seems like it might require some special casing, since the output type should be a float if the input type is an int.

### LINKED ISSUE #38845: exec: some aggregations should promote the return type
Currently in the vectorized engine, SUM and AVG will always return the same type as the input type. 

But consulting the Postgres pg_catalog shows that the return type should differ sometimes:
```
postgres> select proname, proargtypes[0]::regtype as arg, prorettype::regtype as ret from pg_catalog.pg_proc where proname = 'sum' and proargt
 ypes[0] != prorettype;
+-----------+----------+---------+
| proname   | arg      | ret     |
|-----------+----------+---------|
| sum       | bigint   | numeric |
| sum       | integer  | bigint  |
| sum       | smallint | bigint  |
+-----------+----------+---------+

postgres> select proname, proargtypes[0]::regtype as arg, prorettype::regtype as ret from pg_catalog.pg_proc where proname = 'avg' and proargt
 ypes[0] != prorettype;
+-----------+----------+------------------+
| proname   | arg      | ret              |
|-----------+----------+------------------|
| avg       | bigint   | numeric          |
| avg       | integer  | numeric          |
| avg       | smallint | numeric          |
| avg       | real     | double precision |
+-----------+----------+------------------+
```

It might be best to knock out #38823 at the same time as doing this.

Also perhaps doing this would eliminate the need for the SUM_INT aggregator.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add support of avg on ints and intervals**

This commit adds support of `avg` aggregate function on ints and
intervals. Adding intervals support was straightforward, but ints
support was a little trickier: average of ints is a decimal, so there
is some additional setup up work needed to override the result type.
Another complication was that we need to perform the summation using
"DECIMAL + INT" overload. In order to make the code more comprehensible
I introduced a separate `avgTmplInfo` struct that contains all the
necessary information for the code generation.

Fixes: #38823.
Addresses: #38845.

Release note (sql change): Vectorized execution engine now supports
`AVG` aggregate function on `Int`s and `Interval`s.

**colexec: add full support of sum and sum_int**

This commit adds the full support of `sum` and `sum_int` when operating
on integers (previously, `sum` wasn't supported at all whereas `sum_int`
only on `INT8`). The complication here is that `sum` on ints returns
a decimal and `sum_int` always returns `INT8` regardless of the argument
type width. The former is resolved in a similar fashion to how `avg` is
supported on ints, and the latter required introduction of a special
`assignFunc` that promotes the return type.

Fixes: #38845.

Release note (sql change): Vectorized execution engine now fully
supports `SUM` aggregate function (previously, the summation of integers
was incomplete).

**colexec: support min and max on int2 and int4**

Previously, `min` and `max` were disabled on INT2 and INT4 columns
because there was a mismatch between the logical expected type (INT8)
and the actual physical type (the type of the argument). Now this is
fixed by performing the cast and some extra templating.

Additionally, this commit cleans up the way we populate the output types
of the aggregate functions as well as removes some redundant return
values.

Release note (sql change): Vectorized execution engine now support `MIN`
and `MAX` aggregate functions on columns of INT2 and INT4 types.

**sql: miscellaneous cleanups**

This commit does the following:
1. unifies the way we set "no filter" on the window functions as well as
reuses the same constant for "column omitted" index
2. sets `VectorizeMode` of the testing eval context to `on` by default
3. disables fallback to rowexec for operators against processors tests
4. updates execplan to be defensive about nil processorConstructor.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
cc @helenmhe do you want to take a stab at reviewing this? I will probably also review this later on but it's always good to have a fresh perspective on PR reviews. Even if the review is just any questions you might have about the code, those are more than welcome!

**Review by asubiotto — CHANGES_REQUESTED** [review]
cc @jordanlewis for the templating stuff in case it gives you any ideas. I think that we should avoid template conditionals and be more explicit about the template info structs we're working on. I think this is a usual source of confusion for me, I'd be interested in hearing if that's the case for anyone else.

> Reviewed 4 of 4 files at r1, 11 of 11 files at r2, 5 of 5 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-:-M9YjckJ1_51jxLcPNsz:bmyv8t8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9JXzxhBmV6mgCkscyv:-M9JXzxhBmV6mgCkscyw:bz204l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/aggregate_funcs.go#L203)):*
> ```Go
> 			if typeconv.TypeFamilyToCanonicalTypeFamily(aggTyps[i][0].Family()) == types.IntFamily {
> 				// Average of integers is a decimal.
> 				outTyps[i] = types.Decimal
> ```

I don't think we should add code to figure out what the return type is here. Can you reuse `GetAggregateInfo`? Or maybe refactor that and reuse only what you need here.
___
*[pkg/sql/colexec/aggregate_funcs.go, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Ye7Ap9GUbhAOD5fK3:-M9Ye7Ap9GUbhAOD5fK4:b-ox8u3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e12c0b3f1eaf0a79e9150c437dfee44cb032e1/pkg/sql/colexec/aggregate_funcs.go#L216)):*
> ```Go
> 			}
> 		case execinfrapb.AggregatorSpec_SUM_INT:
> 			if typeconv.TypeFamilyToCanonicalTypeFamily(aggTyps[i][0].Family()) == types.IntFamily {
> ```

Doesn't `SUM_INT` only work on integers? We should return an error in the else case if I understand correctly.
___
*[pkg/sql/colexec/aggregate_funcs.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Yi36MAG_CHqnsg5bm:-M9Yi36MAG_CHqnsg5bn:bwb71l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e683db85eb1976766684b2f3884066a14bef6b6f/pkg/sql/colexec/aggregate_funcs.go#L249)):*
> ```Go
> func isAggregateSupported(
> 	allocator *colmem.Allocator, aggFn execinfrapb.AggregatorSpec_Func, inputTypes []*types.T,
> ) (bool, error) {
> ```

I don't think there's any need for the first argument. I would change the signature and the contract such that a `nil` error means the aggregate is supported, and not otherwise.
___
*[pkg/sql/colexec/sum_agg_tmpl.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YfSyi2fw2i4gQ9o_T:-M9YfSyi2fw2i4gQ9o_U:b-j63lwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e12c0b3f1eaf0a79e9150c437dfee44cb032e1/pkg/sql/colexec/sum_agg_tmpl.go#L128)):*
> ```Go
> func (a *sum_KIND_TYPEAgg) Compute(b coldata.Batch, inputIdxs []uint32) {
> 	// _IF_INTEGER_TYPE
> 	// {{if not (eq "_KIND" "Int")}}
> ```

same re conditionals vs explicit template info structs. I think this should be a pattern we follow more often. In this example, I think it's clearer to make a `sumTmplInfo` struct that has a `Kind` field that is set explicitly.
___
*[pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YZZ5q7cjiJvqetxpi:-M9YZZ5q7cjiJvqetxpj:b9642j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go#L74)):*
> ```Go
> 		"_TYPE_WIDTH", typeWidthReplacement,
> 		"_IF_INTEGER_TYPE", ifIntegerType,
> 		"_RET_GOTYPE", ifIntegerType+`apd.Decimal{{else}}{{.GoType}}{{end}}`,
> ```

I'm not sure I like that we have all these template conditionals mostly because they're confusing, even though they're more concise. I prefer that we clearly define a template struct with what we need (i.e. ret type and a "runtime" method that returns whether the input type is an integer) even though it might be more verbose instead of trying to make this work with `oneArgOverload`. For example:
```
type avgTmplInfo struct {
    InputTyp string
    RetTyp string
    AddOverload string
    <...>   
}

func (a avgTmplInfo) IsIntType() {
     return a.InputTyp == ...
}
```
What do you think?
___
*[pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YeP92Ej2F0uMcN6jn:-M9YeP935hQdsPG-eA2-:b-1zczzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go#L101)):*
> ```Go
> 	// family-width overload - onto the top level).
> 	var tmplInfos = []*oneArgOverload{getDecimalPlusIntAsOneArgOverload()}
> 	for _, typ := range []*types.T{types.Decimal, types.Float, types.Interval} {
> ```

We should at least add more unit tests for `Interval`. Are there logic tests that would previously run through row execution that now run through colexec?
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 847 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YckmW48Vqf1yUMlwi:-M9YckmW48Vqf1yUMlwj:b1v64p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L847)):*
> ```Go
> // correctly ("int" is considered to be the single argument). The result of
> // executing this overload is a decimal.
> func getDecimalPlusIntAsOneArgOverload() *oneArgOverload {
> ```

Instead of reworking a twoArgOverload to get this oneArgOverload, would it be possible to somehow construct it at a "base" level. For example, I see we have an `intDecimal` customizer. Can we define it handling a `tree.Plus` in its `getBinOpAssignFunc`?
___
*[pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Yhm6-5ApE3sSRsnH_:-M9Yhm6-5ApE3sSRsnHa:b-qe9a4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e12c0b3f1eaf0a79e9150c437dfee44cb032e1/pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go#L68)):*
> ```Go
> 
> 	assignAddRe := makeFunctionRegex("_ASSIGN_ADD", 6)
> 	if isSumInt {
> ```

This is also complexity that I think would be easier to understand when pushed to a `sumTmplInfo` struct. 
___
*[pkg/sql/distsql/columnar_operators_test.go, line 912 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YjEUKCijpO3vZWS9X:-M9YjEUKCijpO3vZWS9Y:b-1zi6go) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e5229f58097e3be6f211f20d3b705f70c052885/pkg/sql/distsql/columnar_operators_test.go#L912)):*
> ```Go
> 								Ordering:     generateOrderingGivenPartitionBy(rng, nCols, nOrderingCols, partitionBy),
> 								OutputColIdx: uint32(nCols),
> 								FilterColIdx: tree.NoFilterInWindowFn,
> ```

How come not specifying this was fine before?
___
*[pkg/sql/distsql/columnar_utils_test.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Yj2hBDlCvi69fc1uK:-M9Yj2hBDlCvi69fc1uL:bsuva5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/432a1c53bdc486fe4474d45df045b9fd87ebfc53/pkg/sql/distsql/columnar_utils_test.go#L141)):*
> ```Go
> 		Inputs:               columnarizers,
> 		StreamingMemAccount:  &acc,
> 		ProcessorConstructor: rowexec.NewProcessor,
> ```

This is disabled because we now expect to run all variants through colexec, right? Did you stress the corresponding tests?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49900)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9JXzxhBmV6mgCkscyv:-M9_UzEW-D3anQo53ztS:b-4t0qni) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/aggregate_funcs.go#L203)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think we should add code to figure out what the return type is here. Can you reuse `GetAggregateInfo`? Or maybe refactor that and reuse only what you need here.
</blockquote></details>

Good point. I think this method was introduced initially because we had a separate `coltypes.T` type system, but now we can reuse `GetAggregateInfo`. Furthermore, the third commit removes the only place where we had type deviation from the row engine, so I refactored this code in the third commit.
___
*[pkg/sql/colexec/aggregate_funcs.go, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Ye7Ap9GUbhAOD5fK3:-M9_VhQwEW7BSE-ir5lm:brpcpos) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e12c0b3f1eaf0a79e9150c437dfee44cb032e1/pkg/sql/colexec/aggregate_funcs.go#L216)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Doesn't `SUM_INT` only work on integers? We should return an error in the else case if I understand correctly.
</blockquote></details>

Yes, and that should actually be checked during the type checking. This code is now refactored in the third commit.
___
*[pkg/sql/colexec/aggregate_funcs.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Yi36MAG_CHqnsg5bm:-M9_VqQw6QQWTGk8lT7p:b-tajiuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e683db85eb1976766684b2f3884066a14bef6b6f/pkg/sql/colexec/aggregate_funcs.go#L249)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think there's any need for the first argument. I would change the signature and the contract such that a `nil` error means the aggregate is supported, and not otherwise.
</blockquote></details>

Good point, removed in the third commit.
___
*[pkg/sql/colexec/sum_agg_tmpl.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YfSyi2fw2i4gQ9o_T:-M9aPEk0BB1IUUQ9nWNz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e12c0b3f1eaf0a79e9150c437dfee44cb032e1/pkg/sql/colexec/sum_agg_tmpl.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

same re conditionals vs explicit template info structs. I think this should be a pattern we follow more often. In this example, I think it's clearer to make a `sumTmplInfo` struct that has a `Kind` field that is set explicitly.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YZZ5q7cjiJvqetxpi:-M9a9kCR8R9HENHOV3nM:b-65latz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go#L74)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure I like that we have all these template conditionals mostly because they're confusing, even though they're more concise. I prefer that we clearly define a template struct with what we need (i.e. ret type and a "runtime" method that returns whether the input type is an integer) even though it might be more verbose instead of trying to make this work with `oneArgOverload`. For example:
```
type avgTmplInfo struct {
    InputTyp string
    RetTyp string
    AddOverload string
    <...>   
}

func (a avgTmplInfo) IsIntType() {
     return a.InputTyp == ...
}
```
What do you think?
</blockquote></details>

I implemented your suggestion. I think that when looking at `avg_tmpl` in isolation, your suggestion is beneficial since it is probably easier to understand, so this is a plus.

However, the downside is that previously most of the templates have been unified in a way - they had access to `oneArgOverload` at the dot (`.`), and this suggestion breaks that unification. Now you need to write a separate "overload resolution" method (i.e. `newAvgAggAlloc` in this particular case), and `avgTmplInfo` is populated only with the information necessary for the average template. If we start going down this road, I'm worried it might make the work that Jordan is doing with AST approach to execgen harder - I don't know whether it will be so, maybe it'll be easier.

I'm interested in converting `avg` and `sum` templates to this more customized to a particular template approach, and we'll see which one is easier to convert to new execgen style (if that's possible).
___
*[pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YeP92Ej2F0uMcN6jn:-M9a93X5-DgxFQ6AXGvr:b-sdh62c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/execgen/cmd/execgen/avg_agg_gen.go#L101)):*
Done.

> Are there logic tests that would previously run through row execution that now run through colexec?

I think yes (for avg of ints case - I assume we have those somewhere, but not necessarily for intervals). However, `TestAggregatorAgainstProcessor` should pick these new additions, and since in the last commit we disable the fallback to rowexec, we'll make to exercise the vectorized engine for all possible input types.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 847 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YckmW48Vqf1yUMlwi:-M9a9Vda3UovFcijQpUR:b8707qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc7d5e50802265f29e1bf8da16ff137952186db/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L847)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of reworking a twoArgOverload to get this oneArgOverload, would it be possible to somehow construct it at a "base" level. For example, I see we have an `intDecimal` customizer. Can we define it handling a `tree.Plus` in its `getBinOpAssignFunc`?
</blockquote></details>

Refactored the code which removed the necessity of this method. There is still some special behavior for "decimal + int" case, but the new approach should be more comprehensible.
___
*[pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Yhm6-5ApE3sSRsnH_:-M9aPGIp9HZPuDom5JYj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4e12c0b3f1eaf0a79e9150c437dfee44cb032e1/pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go#L68)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is also complexity that I think would be easier to understand when pushed to a `sumTmplInfo` struct. 
</blockquote></details>

Done.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 912 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9YjEUKCijpO3vZWS9X:-M9_W2_XCaCD0yU8ABSA:b-vmtxs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e5229f58097e3be6f211f20d3b705f70c052885/pkg/sql/distsql/columnar_operators_test.go#L912)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How come not specifying this was fine before?
</blockquote></details>

Our code is so well-written that we were falling back to the row engine even without realizing it :)
___
*[pkg/sql/distsql/columnar_utils_test.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9Yj2hBDlCvi69fc1uK:-M9_WGAM-GPMVUGAIjkC:bpgtfmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/432a1c53bdc486fe4474d45df045b9fd87ebfc53/pkg/sql/distsql/columnar_utils_test.go#L141)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is disabled because we now expect to run all variants through colexec, right? Did you stress the corresponding tests?
</blockquote></details>

Yes, and yes. I think it is a mistake to allow for the fallback to occur - if for some reason we don't fully support a particular processor core, then we should make sure to not generate test cases that would trigger the fallback.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 25 of 25 files at r5, 10 of 10 files at r6, 7 of 7 files at r7, 17 of 17 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-:-M9sPs6XBpyC7dYOAtF_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 285 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9sMkrrBszoIe1S7Coo:-M9sMkrrBszoIe1S7Cop:bqkmzrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae9185f65090d7bec5c8ba301aeca226e0d6545a/pkg/sql/colexec/aggregate_funcs.go#L285)):*
> ```Go
> }
> 
> func newAvgAggAlloc(
> ```

How come these aren't templated any more?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-:-M9sRHaY0R4qhmdJ_Ehs:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregate_funcs.go, line 285 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49900#-M9sMkrrBszoIe1S7Coo:-M9sQCGi4lMf7kzGYrCP:b-9t65h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae9185f65090d7bec5c8ba301aeca226e0d6545a/pkg/sql/colexec/aggregate_funcs.go#L285)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How come these aren't templated any more?
</blockquote></details>

Because we introduce special `avgTmplInfo` that is stored in a "flat" manner (i.e. all objects are on the "same level" in a slice), we no longer can use the approach of switching on type family and then on the type width (because we would get multiple `types.IntFamily` cases for every integer width). This is the disadvantage of having custom tmpl info structs - we need to come up with some way to resolve the aggregate function - we either need to type out the resolution function manually or introduce the layered "family-width" structure similar to regular overloads into the way we provide tmpl infos into `Execute` call. I tried the former approach for now.

**Pull request merged**
