### PR TITLE
exec: add count operator

### PR DESCRIPTION
**Pull request by jordanlewis**
It counts the number of tuples in its input.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31931)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/count.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31931#-LPm9INAD4LumScFpveH:-LPm9INAD4LumScFpveI:b-6asg41) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed513b0df8a1d0f5c24b017a7b3f7a489b6f2531/pkg/sql/exec/count.go#L61)):*
> ```Go
> 		c.count += int64(length)
> 	}
> 	c.internalBatch.SetLength(0)
> ```

I would probably change this to:
```
if c.done {
    c.internalBatch.SetLength(0)
    return c.internalBatch
}
< counting logic >
c.done = true
return batch
```
Because as it is you do two if checks per loop (`done` and `length`) when you could just do one. I guess it's not that expensive since it's per batch though.

**Comment by jordanlewis** [comment]
Done.

**Review by asubiotto — APPROVED** [review]

**Pull request merged**
