### PR TITLE
release-19.2: cli/zip: misc fixes

### PR DESCRIPTION
**Pull request by knz**
Backport 1/1 commits from #48096.
Backport 1/1 commits from #48099. 
Backport 1/1 commits from #48109.
Backport 1/1 commits from #48150. 

/cc @cockroachdb/release

---

### CODE REVIEW

**Comment by knz** [comment]
at least TC is green on this one

**Comment by knz** [comment]
(friendly review ping)

**Comment by knz** [comment]
(friendly ping)

**Comment by andreimatei** [comment]
LGTM

**Pull request merged**
