### PR TITLE
sql: create schemaexpr package

### PR DESCRIPTION
**Pull request by mgartner**
This commit adds a new package for dealing with expressions within table
schemas, such as check constraints, computed columns, and partial index
predicates.

The utility provided previously by the following functions have been moved
and refactored into this new package:

  dequalifyColumnRefs - Now provided by DequalifyColumnRefs.

  makeCheckConstraint - Now provided by CheckConstraintBuilder.

  validateComputedColumn - Now provided by ComputedColumnValidator.

  validateIndexPredicate - Now provided by IndexPredicateValidator.

In addition, several helper functions were refactored into the new
package, including generateMaybeDuplicateNameForCheckConstraint,
generateNameForCheckConstraint, iterColDescriptorsInExpr, and
replaceVars. dummyColumnItems were also moved into the new package.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Nice!

r2 sounds like a refactoring but is also adding new stuff. What code is new? I assume the one in partial_index.go (which LGTM), anything else?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49657#-:-M8Rcxk756WF7CCfu67v:bvh8obb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by mgartner** [comment]
Ahh, I'm going to undo the first commit, since it looks like I'll need a `context.Context` anyway for `SanitizeFreeVars` now. Bear with me for a moment...

**Review by mgartner — COMMENTED** [review]
@raduberinde it was my mistake that there were some changes in functionality originally in the first revision or two. There should now be no changes to current functionality in this PR - it's meant to just be a refactor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49657#-:-M8RiB4F1E32ZZM5sGTt:bd6chhf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by mgartner** [comment]
@RaduBerinde oops, there's one minor change. In `partial_index.go` I've added dequalifition of the column names of the expression. The result is from `IndexPredicateValidator.Validate` is not being used yet, so no tests need to be added or changed. I'll leave this as-is because it seems minor, but happy to revert that and add back in in the next PR if you'd like.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  (but wait for Jordan to take a look too)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49657#-:-M8SItu66N_hsneJ7lSk:b-ahdpgt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by jordanlewis** [comment]
Refactor looks good to me, thanks for doing it. Of course as refactors of this nature tend to highlight, we now have no unit tests for these components. I don't think I would ask you to write unit tests for all of the old code you moved in to the package, but could I persuade you to write a few for your new index predicate validation struct? At the very least, it will be nice to have a pattern available for people in the future, so if they modify or add new code to this package, they won't be tempted themselves to add no unit tests.

**Comment by mgartner** [comment]
> I don't think I would ask you to write unit tests for all of the old code you moved in to the package, but could I persuade you to write a few for your new index predicate validation struct?

Absolutely. I'll start with the parital index predicate stuff and some of the functions in `column.go`. If I don't run out of steam I'll write tests for everything, otherwise I'll leave some TODOs for myself to come back and do so after I recharge my battery.

**Comment by andy-kimball** [comment]
Love that you're taking on the SQL refactoring beast, or at least some part of it. Its big toe, perhaps? But that's how to defeat it - one toe at a time, then the feet, then the legs, and so on.

**Comment by mgartner** [comment]
> Love that you're taking on the SQL refactoring beast, or at least some part of it. Its big toe, perhaps? But that's how to defeat it - one toe at a time, then the feet, then the legs, and so on.

Crossing my fingers that its Achilles and we only have to make it to the heel...

**Comment by mgartner** [comment]
@jordanlewis I added unit tests for the `IndexPredicateValidator` and the `DequalifyColumnRefs` function. I also left some TODOs which I'll come back to to unit test the rest. PTAL and let me know what you think.

**Review by RaduBerinde — APPROVED** [review]
Very nice tests! :lgtm: 

> Reviewed 2 of 13 files at r2, 20 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49657#-:-M8lLsB4-1Ws2eEmkaV_:b-psbssu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Pull request merged**
