### PR TITLE
sql/parser: correct broken error handling

### PR DESCRIPTION
**Pull request by tamird**
One original, one copy pasta.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
Should we just change invertComparisonOp to panic in the default case? Propagating up an "Internal error" seems pretty pointless.

**Comment by tamird** [comment]
Meh, I don't see how that solves the general problem of typing `nil` instead of `err`.

**Comment by jordanlewis** [comment]
Well, we wouldn't have to return an `error` from `invertComparisonOp` anymore, which would allow us to delete 8 LOC from this file. Either way though.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14705#-:-Kh8QcFjgVJDkibrkLoN:bnfp4nl)*

**Pull request merged**
