### PR TITLE
release-21.2: pgwire: fix buffer size limiting behavior for addBatch

### LINKED ISSUE #83837: pgwire: check if buffer should be flushed for each row
**Describe the problem**

In 21.2, we introduced the ability to directly write vectorized batches to a buffer to be sent to the client, whereas before the traditional row-wise datums had to be materialized. However, currently we only check if the buffer has exceeded its memory limit after the entire batch has been buffered, which can cause the buffer to greatly exceed its limit when rows are wide. This can translate to increased memory usage for a cluster and even OOM conditions in extreme cases.

**To Reproduce**

- Create a table with a bytes column that has wide rows (~64KiB).
- Perform repeated full-table select queries over the large-row table.
- Observe significant allocations resulting from the large pgwire buffer.
```
defaultdb> create table large (b BYTES);
defaultdb> insert into large (SELECT (SELECT string_agg(x, '')::BYTES FROM (SELECT 'vbX5ajNEOh1VlLJ4' FROM generate_series(1, 4000)) s(x)) FROM generate_series(1, 1000));
while true; do ./cockroach sql --insecure -d defaultdb -e 'select * from large' > /dev/null; printf . ; done
```

**Expected behavior**

We should check if the buffer needs to be flushed after each row, instead of each batch.

**Environment:**
 - CockroachDB version 21.2+

**Additional context**
A customer ran into this issue when they upgraded their cluster from 21.1 to 21.2.

Here is a screenshot of a flamegraph that resulted from running the above reproduction steps:
Screen Shot 2022-07-05 at 12 36 47 PM

Jira issue: CRDB-17294

### PR DESCRIPTION
**Pull request by DrewKimball**
Backport 1/1 commits from #83870.

/cc @cockroachdb/release

---

Previously, the size of the buffer used to store results before sending them
to the client was checked after buffering each batch entirely. This could
result in significantly exceeding the buffer memory limit when a batch had wide
rows on average.

This patch modifies the pwire logic to ensure that `maybeFlush` is called each
time a row is buffered. This ensures that the pre-21.2 behavior is preserved.

Fixes #83837

Release note (bug fix): Fixed a bug that was introduced in release 21.2 that
could cause increased memory usage when scanning a table with wide rows.

Release justification: bug fix.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84921#-:-N7bWe6nAFvi5PpxRGz-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by mgartner — APPROVED** [review]
Thanks for backporting! You'll just need to add a release justification to the PR description.

**Comment by mgartner** [comment]
@DrewKimball @yuzefovich Should we merge this today to get it into 21.2.14?

**Comment by yuzefovich** [comment]
Yes, it'd be good.

**Comment by mgartner** [comment]
👍 Thanks!

**Pull request merged**
