### PR TITLE
sql: skip TestAggregatesMonitorMemory

### PR DESCRIPTION
**Pull request by adityamaru**
Issue: https://github.com/cockroachdb/cockroach/issues/78482

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
LGTM. I wonder if the problem is just that we have more asynchronous processes at startup that are now memory monitored.  This test is almost always failing before the query under test is even run.

Perhaps rather than skipping it we could bump `lowMemoryBudget`

**Review by arulajmani — APPROVED** [review]
Saw this flake on a bors run

**Review by yuzefovich — APPROVED** [review]
:lgtm:

I think Steven is right, but it's ok to skip it - I'm looking at the proper fix right now.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78933#-:-MzLJpNC1DRA2ctKVm15:b-1qwgoe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by yuzefovich** [comment]
I already have a PR up (#78964), so no need to skip the test.

bors r-

**Pull request closed without merging**
