### PR TITLE
appstatspb: extract app_stats from roachpb into new package

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extracts `app_stats.proto` and a couple of corresponding files into a new package `sql/appstatspb` from `roachpb`. The rationale for this is that we want to trim down `roachpb` to be specifically about very low-level details of CRDB where the app stats protos don't belong - these are primarily concerned with the SQL layer. Follow-up PRs will move more things out of `roachpb`.

Epic: None

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96403#-:-NNISH5e3annf-RzPxTh:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
bors r-

Will add a justification.

**Pull request merged**
