### PR TITLE
util/cgroups: add ability to read current memory usage from cgroup

### PR DESCRIPTION
**Pull request by abarganier**
Currently we have methods that allow us to read the cgroup memory limit
for processes running in unix containers, but we have no method to
get the actual current memory usage from the cgroup memory subsystem.

This commit adds the ability to do so. This is a useful metric to help
better enable observability into memory usage. We aim to make use of
this metric to be able to more accurately identify when nodes are on
their way to being killed due to OOMs, where periodic checks can be
compared against the cgroup memory limit.

The commit also does some slight refactoring to the existing code that
fetches the cgroup memory limit, to avoid code duplication.

Release note: none

Informs https://github.com/cockroachdb/cockroach/pull/66901

A follow up PR will also expose the ability to read cache usage from the cgroup (`memory.stat:total_inactive_file` for v1 and `memory.stat:inactive_file` for v2) as this is generally subtracted from `memory.usage_in_bytes` when [determining memory usage stats](https://docs.docker.com/engine/reference/commandline/stats/#extended-description).

### CODE REVIEW

**Review by rimadeodhar — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68204)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @itsbilal, and @knz)

___
*[pkg/util/cgroups/cgroups.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68204#-MfnTQ6iEqUHusiYCxR0:-MfnTQ6j6DKCRxa0w3Jr:b1znbmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e41f537678eef3786242bb95c5cdaefdb84c4c31/pkg/util/cgroups/cgroups.go#L44)):*
> ```
> 	cgroupV1MemUsageFilename     = "memory.usage_in_bytes"
> 	cgroupV2MemUsageFilename     = "memory.current"
> ```

Out of curiosity, what does V1 and V2 denote? I'm guessing some form of versioning but what are these versions corresponding to?
___
*[pkg/util/cgroups/cgroups.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68204#-MfnV0oA1t25KnsB4lRp:-MfnV0oA1t25KnsB4lRq:b1mfpsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e41f537678eef3786242bb95c5cdaefdb84c4c31/pkg/util/cgroups/cgroups.go#L322)):*
> ```
> 	defer func() {
> 		_ = file.Close()
> 	}()
> ```
Can we just do defer file.Close()?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68204)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @rimadeodhar)

___
*[pkg/util/cgroups/cgroups.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68204#-MfnTQ6iEqUHusiYCxR0:-MfnXJXw33JBt6KGQOvy:baewnk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e41f537678eef3786242bb95c5cdaefdb84c4c31/pkg/util/cgroups/cgroups.go#L44)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

> ```
> 	cgroupV1MemUsageFilename     = "memory.usage_in_bytes"
> 	cgroupV2MemUsageFilename     = "memory.current"
> ```

Out of curiosity, what does V1 and V2 denote? I'm guessing some form of versioning but what are these versions corresponding to?
</blockquote></details>

It denotes the cgroupfs version number ([version1](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/cgroups.html) vs. [version2](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html)). There are some semantic differences between the two in terms of how cgroup hierarchies are treated, and some of the filenames (or available files in general) in the subsystems are different between the two. 
___
*[pkg/util/cgroups/cgroups.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68204#-MfnV0oA1t25KnsB4lRp:-MfnX8Jb8Ypa1Rhnotle:b1iebdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e41f537678eef3786242bb95c5cdaefdb84c4c31/pkg/util/cgroups/cgroups.go#L322)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

> ```
> 	defer func() {
> 		_ = file.Close()
> 	}()
> ```
Can we just do defer file.Close()?
</blockquote></details>

Good idea, done.

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68204)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @knz)

**Comment by abarganier** [comment]
bors r=rimadeodhar

**Comment by abarganier** [comment]
(test failures appear to be spurious)

**Pull request merged**
