### PR TITLE
storage: convert the rest of the reservation consts to env variables for testing.

### PR DESCRIPTION
**Pull request by BramGruneir**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7283)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/reservation.go, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRMTVjzWVrxxJ5ISY:-KKPRMTVjzWVrxxJ5ISZ:-772876764) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation.go#L35)):*
> ```Go
> 	// defaultMaxReservedBytes is the total number of bytes that can be
> 	// reserved, by all active reservations, at any time.
> 	defaultMaxReservedBytes = 250 * (1 << 20) // 250 MiB
> ```

nit: `250 << 20`?

---

*[storage/reservation.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRlFqx75pf5aoQfNN:-KKPRlFqx75pf5aoQfNO:-1123342174) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation.go#L78)):*
> ```Go
> type bookie struct {
> 	clock              *hlc.Clock
> 	reservationTimeout time.Duration // How long each reservation is held. Defaults to ttlStoreGossip.
> ```

nit: why bother mentioning the default (especially by name - just asking for rot) here but not below?

---

*[storage/reservation_test.go, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRuUyNpI_Etv6nK2n:-KKPRuUyNpI_Etv6nK2o:1238941635) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation_test.go#L35)):*
> ```Go
> 	clock := hlc.NewClock(mc.UnixNano)
> 	b := newBookie(clock, stopper, newStoreMetrics())
> 	b.maxReservations = 20
> ```

this is now really far from the test that wants `20`, making it hard to understand other hard coded values in that test. Can you make the values in the test based on `b.maxReservations`, and perhaps avoid setting this at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by cuongdo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/reservation.go, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPZfdIt_ipHzcKzDGI:-KKPZfdIt_ipHzcKzDGJ:1325665099) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation.go#L31)):*
> ```Go
> const (
> 	// defaultMaxReservations is the number of concurrent reservations that are
> 	// allowed at once.
> ```

nit: s/ at once.// (redundant with "concurrent")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by BramGruneir** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/reservation.go, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPZfdIt_ipHzcKzDGI:-KKPt5m62HqF9_rpKwo-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation.go#L31)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> nit: s/ at once.// (redundant with "concurrent")
</details>
Done.

---

*[storage/reservation.go, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRMTVjzWVrxxJ5ISY:-KKPt8UgiphCO_siFo9L:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: `250 << 20`?
</details>
Done.

---

*[storage/reservation.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRlFqx75pf5aoQfNN:-KKPtFyxyino_jKnDHs0:-1054325829) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation.go#L78)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: why bother mentioning the default (especially by name - just asking for rot) here but not below?
</details>
removed

---

*[storage/reservation_test.go, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRuUyNpI_Etv6nK2n:-KKPtJIlLfzJvKZolS4-:1741666030) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation_test.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is now really far from the test that wants `20`, making it hard to understand other hard coded values in that test. Can you make the values in the test based on `b.maxReservations`, and perhaps avoid setting this at all?
</details>
Move it into the test directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKQ2BHZ1qj5x5wY3KSu:1417088721)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/reservation_test.go, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRuUyNpI_Etv6nK2n:-KKQ43WYYIi-mYlAf93i:25814997) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation_test.go#L35)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Move it into the test directly.
</details>
Better, but still a bummer that you're hardcoding magic numbers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/reservation_test.go, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKQ4G4L324kMVM87cYJ:-KKQ4G4L324kMVM87cYK:-949860585) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fd2dd169402a524385c25ca87dfeb1ae567aa42/storage/reservation_test.go#L36)):*
> ```Go
> 	b := newBookie(clock, stopper, newStoreMetrics())
> 	b.reservationTimeout = reservationTimeout
> 	b.metrics.available.Update(100000)
> ```

also this is a bummer. i don't even know why it's needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by BramGruneir** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/reservation_test.go, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKPRuUyNpI_Etv6nK2n:-KKR057mbJ7ddz4swKcq:-1972866365) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f1a23976dadd37baf8ae7e5d8e88f999a634ff/storage/reservation_test.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Better, but still a bummer that you're hardcoding magic numbers.
</details>
This is just because the test queues up 7 reservations.  I've added a comment so it's not just a random number.

---

*[storage/reservation_test.go, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKQ4G4L324kMVM87cYJ:-KKR0FDi2V0rY9l0GsW1:529190157) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fd2dd169402a524385c25ca87dfeb1ae567aa42/storage/reservation_test.go#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> also this is a bummer. i don't even know why it's needed.
</details>
This is for a mocked version of the metrics so that we have enough space free.  I've added a comment and made the number related to default max res bytes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by tamird** [comment]
eh putting all this state under lock is funky - what's racing?

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKR5QWumBo7SrbzPuVm:-1476991929)*

**Comment by BramGruneir** [comment]
Every time I adjusted maxReservations was the culprit, because it was being using in both the main loop in Start.  The other two are safer, but could race if not protected.  Tt's really only in tests were any of these are set after the bookie is already created.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKR5_p9en2sX2-vTS9c:-1015586981)*

**Comment by BramGruneir** [comment]
See https://circleci.com/gh/BramGruneir/cockroach/606 for an example.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKR6S4oaZL2U_5SnHXR:-1928723208)*

**Comment by tamird** [comment]
Understood, but you end up synchronizing outside of tests as well. Why not
plumb these values into your test constructors?

**Comment by BramGruneir** [comment]
Where do I sync outside the tests?  I only added the extra lock statements inside tests.
As for plumbing them in the test contractor, that would work if I split the tests up in more tests, which seems excessive.  I test specific cases of hitting these limits.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKR8Q90aA4ijdbozFQq:1228516336)*

**Comment by cuongdo** [comment]
I'm not sure what @tamird means by "syncing outside of tests as well", but it does seem odd to have `maxReservations` be in the `mu` struct if you're generally accessing it without calling `mu.Lock()`.  It does make more sense as part of the test constructor.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKVE0C8ss24waqu-eR6:-653098442)*

**Comment by BramGruneir** [comment]
There's no point in which any of them are accessed that was not already under the lock.  That's why I was ok moving them into one.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKiHFnOdo13hrW5APab:-2034655648)*

**Comment by BramGruneir** [comment]
(besides the test code that is)

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-:-KKiHRf6UpWn7J0QJp9U:-1259206396)*

**Comment by tamird** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/reservation.go, line 83 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKj47hvHIK-rYV8N_5D:-KKj47hvHIK-rYV8N_5E:1870122977) ([raw file](https://github.com/cockroachdb/cockroach/blob/72fa875468f5aa629a196568370812b579961c90/storage/reservation.go#L83)):*
> ```Go
> 		reservationsByRangeID map[roachpb.RangeID]*reservation // All active reservations
> 		size                  int64                            // Total bytes required for all reservations.
> 		reservationTimeout    time.Duration                    // How long each reservation is held.
> ```

as discussed offline, let's move these configuration members back out of the mutex (leaving comment so you can ping it when done).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by BramGruneir** [comment]
*[storage/reservation.go, line 83 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKj47hvHIK-rYV8N_5D:-KKlTPEN17ou_F-rzsDE:-904224389) ([raw file](https://github.com/cockroachdb/cockroach/blob/72fa875468f5aa629a196568370812b579961c90/storage/reservation.go#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> as discussed offline, let's move these configuration members back out of the mutex (leaving comment so you can ping it when done).
</details>
This is done.  And I split the test into 3 different tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/reservation_test.go, line 169 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKmEeoy31ZRkG9NRCeH:-KKmEeozA09CKbWKGkDh:700723533) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b3362334c51633af8c8af2467bebba82afd7fc/storage/reservation_test.go#L169)):*
> ```Go
> }
> 
> // TestBookieReserveMaxRanges ensures that there is no over-booking on the
> ```

this comment is broken

---

*[storage/reservation_test.go, line 190 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKmFHnVYYyXIPWKAzXs:-KKmFHnWn9cvjU77XgvD:-455478640) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b3362334c51633af8c8af2467bebba82afd7fc/storage/reservation_test.go#L190)):*
> ```Go
> 		}
> 		if !b.Reserve(req).Reserved {
> 			t.Errorf("%d: could add reservation", i)
> ```

could not?

---

*[storage/reservation_test.go, line 231 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKmFR661kEf0mEJELLw:-KKmFR661kEf0mEJELLx:-455478640) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b3362334c51633af8c8af2467bebba82afd7fc/storage/reservation_test.go#L231)):*
> ```Go
> 		}
> 		if !b.Reserve(req).Reserved {
> 			t.Errorf("%d: could add reservation", i)
> ```

could not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by BramGruneir** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/reservation_test.go, line 169 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKmEeoy31ZRkG9NRCeH:-KKnXL5__DTFNVsdPx2A:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b3362334c51633af8c8af2467bebba82afd7fc/storage/reservation_test.go#L169)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this comment is broken
</details>
Done.

---

*[storage/reservation_test.go, line 190 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKmFHnVYYyXIPWKAzXs:-KKnXMqpnJ-DjfCMP6GJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b3362334c51633af8c8af2467bebba82afd7fc/storage/reservation_test.go#L190)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> could not?
</details>
Done.

---

*[storage/reservation_test.go, line 231 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283#-KKmFR661kEf0mEJELLw:-KKnXOKvP-oKQG3Sv_1q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/46b3362334c51633af8c8af2467bebba82afd7fc/storage/reservation_test.go#L231)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> could not?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7283)*

**Pull request merged**
