### PR TITLE
workload/schemachanger: allocate enough connections for monitoring

### LINKED ISSUE #101256: roachtest: schemachange/random-load failed
roachtest.schemachange/random-load [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9538069?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9538069?buildTab=artifacts#/schemachange/random-load) on master @ [a5d61d2cf2bfc11bd6bdc27dcab32467334fb123](https://github.com/cockroachdb/cockroach/commits/a5d61d2cf2bfc11bd6bdc27dcab32467334fb123):

```
test artifacts and logs in: /artifacts/schemachange/random-load/run_1
(test_runner.go:1012).runTest: test timed out (3h0m0s)
(schemachange_random_load.go:169).runSchemaChangeRandomLoad: output in run_173008.532973903_n1_workload-run-schemac: ./workload run schemachange --verbose=1 --tolerate-errors=false  --histograms=perf/stats.json --max-ops 5000 --concurrency 20 --txn-log /mnt/data1/cockroach/transactions.ndjson returned: parallel execution failure: COMMAND_PROBLEM: ssh verbose log retained in ssh_173008.541852973_n1_workload-run-schemac.log: exit status 134
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/random-load.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26882

### PR DESCRIPTION
**Pull request by fqazi**
With recent changes, there is a cap on the maximum number of connections inside the workload connection pools, which can interfere with watchdog connections in this workload. This workload was allocating only enough connections for concurrency, which made this limit problematic. This patch allocates extra connections for monitoring inside this workload.

Fixes: #101256

Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
LGTM

**Comment by chengxiong-ruan** [comment]
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101731#-NTJfsDQ3q5H0mR2iIOK):*
nit: remove this from commit message :)

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101731#-NTJfsDQ3q5H0mR2iIOK):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

nit: remove this from commit message :)
</blockquote></details>

@chengxiong-ruan Yikes, good catch :)

**Pull request merged**
