### PR TITLE
roachtest: add `--encrypt` flag to roachtest run

### PR DESCRIPTION
**Pull request by ghost**
Added `--encrypt` flag to `roachtest run` to start all nodes with encryption
at rest turned on. Users are responsible for ensuring the test logic satisfy
the workflow of encryption of rest such as the use of old keys.

Part of encryption at rest #19783.
Release note: None

### CODE REVIEW

**Comment by windchan7** [comment]
Do not merge before roachprod part merges: https://github.com/cockroachdb/roachprod/pull/170

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26094#-:-LDMs1RoBZYP58H_0k6F:bnfp4nl)*

**Comment by mberhault** [comment]
LGTM

**Pull request merged**
