### PR TITLE
distsql: add stall time to InputStats

### PR DESCRIPTION
**Pull request by asubiotto**
This collects the cumulative amount of time that a caller is stuck
waiting on a RowSource.Next() to return. The tableReader and hashJoiner
collect this time and report it on the visual query plan through EXPLAIN
ANALYZE.

Part of stat collection issue #25743 and #19476

Release note: None

cc @jordanlewis 

Screenshot (simple):
screen shot 2018-06-06 at 12 53 14 pm

Screenshot (more complex):
screen shot 2018-06-06 at 12 44 00 pm

We had a conversation yesterday about whether this stat is useful. I still think it is but it's true that it can start to get confusing when interpreting the values of downstream processors. Maybe we should only send them back for the `tableReader`?

One thing I'm still trying to figure out is that the current test in the logic tests for stats (removed in this PR for now to highlight it) doesn't work anymore due to the variation in stall times. I was thinking of plumbing a testing knob into processors with the distsql configs and keeping this test but was wondering what thoughts on that were.

### CODE REVIEW

**Comment by asubiotto** [comment]
Just to be clear: I definitely think that there is more to do with respect to timing (e.g. how long we're spending in a processor) but this is a good data point to have too.

**Comment by andreimatei** [comment]
Does this have any measurable impact on perf? Is `InputStatCollector` only used when the query is traced/explained?

> We had a conversation yesterday about whether this stat is useful. I still think it is but it's true that it can start to get confusing when interpreting the values of downstream processors. Maybe we should only send them back for the tableReader?

Provided we can implement it efficiently, I think it'd be very useful. What's confusing about it?

**Comment by jordanlewis** [comment]
:lgtm: 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-:-LELOhzp0S7V97SJp1xG:bg7igkv)*

**Comment by asubiotto** [comment]
> Does this have any measurable impact on perf? Is InputStatCollector only used when the query is traced/explained?

No impact when not tracing.`InputStatCollector` is only used when the query is traced/explained.

> Provided we can implement it efficiently, I think it'd be very useful. What's confusing about it?

Maybe nothing, I think the issues arise when you start trying to explain too much with these (for example trying to deduce processing times)

**Comment by solongordon** [comment]
Nice! For readability, may I recommend displaying everything in milliseconds and ditching the fractional part? It's hard to compare the stall times at a glance.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/logictest/testdata/planner_test/distsql_auto_mode, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-LELZyN79si1YkBzpopZ:-LELZyN79si1YkBzpop_:b-q7vg9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/56686b61097d143e35248d102fe0ea13f5a03075/pkg/sql/logictest/testdata/planner_test/distsql_auto_mode#L133)):*
> ```
> SELECT "URL" FROM [EXPLAIN ANALYZE (DISTSQL) SELECT * FROM kv JOIN kw ON kv.k=kw.w];
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJyckkFr4zAQhe_7K8ScEhDEdvYkWBB7anpoSuit-KBa00TEtsyM3CQE__diuZA6JG3To968N994xkeovcUHUyGDeoYUcgkN-QKZPfXSYFjYPahEgqubNvRyLqHwhKCOEFwoERQ8mZcSV2gs0iwBCRaDcWVs25CrDB309g0kkN-xIDRWiQTyToJvw6krB7NGUGknf0dOr5B3PyVnV8knYFt7skhoR7C8T35nuTD-neHNvXc10iwbT1_ia5jodPqP3HoTJjqbgoyiGH2KhFg_Fzl4QivYWVQiOkBCZfaiwsrTQbSMvVP8_5Ct4-1IXLZBCZ1KnUk9l_rv1Z3Nb7nWCrnxNeP57i52TvqFoV3jcAD2LRX4SL6ImOG5jLkoWOQwVLPhsahjKf5On8PpDeHsPJx9GZ6PwkmXd3_eAwAA___kgB3h
> ```

Why did this go away?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-:-LEL_00f5v-FFIkZ1wFl:b-l7x42y)*

**Comment by asubiotto** [comment]
I'm wary of imposing a unit on the displayed times because of how they could vary per query but I rounded the times to the nearest `time.Microsecond`, which hopefully makes the times clearer:


Still need to write a test for this

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/planner_test/distsql_auto_mode, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-LELZyN79si1YkBzpopZ:-LELgJd4BX2Z9JF4lOOO:b61p53e) ([raw file](https://github.com/cockroachdb/cockroach/blob/56686b61097d143e35248d102fe0ea13f5a03075/pkg/sql/logictest/testdata/planner_test/distsql_auto_mode#L133)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why did this go away?
</blockquote></details>

Just to highlight that I can't use this test anymore because of the non-deterministic stats. Another alternative to the one in the PR message would be to add an extra end-to-end test where I check for the existence of these details but ignore the values. What do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-:-LELhD6T2R6pmpHCnzqe:bplbwzr)*

**Comment by jordanlewis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/logictest/testdata/planner_test/distsql_auto_mode, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-LELZyN79si1YkBzpopZ:-LEPvxaA9bwNwB9AUup4:b-lc60rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/56686b61097d143e35248d102fe0ea13f5a03075/pkg/sql/logictest/testdata/planner_test/distsql_auto_mode#L133)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Just to highlight that I can't use this test anymore because of the non-deterministic stats. Another alternative to the one in the PR message would be to add an extra end-to-end test where I check for the existence of these details but ignore the values. What do you think?
</blockquote></details>

Maybe we could think of a way to solve this with EXPLAIN options. EXPLAIN ANALYZE (STALLS) or something. Then again, these options tend to proliferate in a confusing way. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26471)*

**Comment by solongordon** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/logictest/testdata/planner_test/distsql_auto_mode, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-LELZyN79si1YkBzpopZ:-LEQQ_HTEj0H7xWYBIZ4:bt9ht7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/56686b61097d143e35248d102fe0ea13f5a03075/pkg/sql/logictest/testdata/planner_test/distsql_auto_mode#L133)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Maybe we could think of a way to solve this with EXPLAIN options. EXPLAIN ANALYZE (STALLS) or something. Then again, these options tend to proliferate in a confusing way. 
</blockquote></details>

Oops, sorry I missed your comment. None of the testing options sound especially appealing to me so whatever you think is best.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-:-LEQRX547mE5M1kRz_U_:bnfp4nl)*

**Comment by asubiotto** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/logictest/testdata/planner_test/distsql_auto_mode, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26471#-LELZyN79si1YkBzpopZ:-LER1MRe4yyacVG7eXcB:b-rwzszn) ([raw file](https://github.com/cockroachdb/cockroach/blob/56686b61097d143e35248d102fe0ea13f5a03075/pkg/sql/logictest/testdata/planner_test/distsql_auto_mode#L133)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Oops, sorry I missed your comment. None of the testing options sound especially appealing to me so whatever you think is best.
</blockquote></details>

I went with plumbing a boolean in testing knobs on logic test setup

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26471)*

**Pull request merged**
