### PR TITLE
sqlccl: check view dependencies in restore

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14574)

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-:-KgpGxrvqo5IK61C_9S_:bnfp4nl)*

**Comment by a-robinson** [comment]
Attempting to restore (non-materialized) views seems pretty dangerous without putting a lot of thought into all the different edge cases. I thought from #14521 that the plan was to just not support it for now, but I may have misunderstood.

I have a few questions that hopefully aren't completely retreading ground for you:

* When tables get restored, are they always given the same table name and database name? Views' stored queries completely depend on the table and DB names not having changed.
* Is it possible to restore all databases in a cluster at once? If not, it'll be effectively impossible to backup/restore a view that depends on a relation in a different database.
* How important is restoring views? It might be better to not support it for now than to support it with a bunch of cases in which it doesn't work, locking us in to supporting it for a long time for backwards-compatibility reasons.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/restore.go, line 273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpJVPBgZ-A5AhXqdG5:-KgpJVPBgZ-A5AhXqdG6:bs00ojx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/restore.go#L273)):*
> ```Go
> 				table.DependsOn[i] = newID
> 			} else {
> 				return errors.Errorf("cannot restore %q without referenced table %d", table.Name, dest)
> ```

This error could probably be a little more specific, e.g. in the case where the view is being restored but the table that it depends on already exists. Maybe something like "cannot restore %q without also restoring referenced relation %d in the same operation"

---

*[pkg/ccl/sqlccl/restore.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpJqA8CHhaxeTg9j7-:-KgpJqA8CHhaxeTg9j70:bpc3hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/restore.go#L278)):*
> ```Go
> 		origRefs := table.DependedOnBy
> 		table.DependedOnBy = nil
> 		for _, ref := range origRefs {
> ```

Just to make sure this is sane, you can't restore on top of an existing table name, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-:-KgpDzBrObndfXv-x2tB:b-2o4jra)*

**Comment by dt** [comment]
To your last point first: when I mentioned our initial plan was just to discard views, there was some suggestion that that wasn't ideal, and that maybe we should handle the disaster recovery case (clean slate, restore everything) if possible.

That case does seem easy enough to cover with a simple "restore view if all IDs in restore otherwise error" logic here.

* Name are not usually changed during RESTORE, though the `into_db` option is the exception -- I'll check and err if it is set.

* Yeah, you can restore across multiple DBs in a single op (don't really treat it as DBs, just a list of tables, the parent's of which must exist). 

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/restore.go, line 273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpJVPBgZ-A5AhXqdG5:-KgpLDakaqX-PTTisdZI:bh8h88r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/restore.go#L273)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This error could probably be a little more specific, e.g. in the case where the view is being restored but the table that it depends on already exists. Maybe something like "cannot restore %q without also restoring referenced relation %d in the same operation"
</blockquote></details>

good point. That said, this matches the other cods-table reference restore errors, all of which are slated for some polish once we can plumb the names rather than IDs though to them.

---

*[pkg/ccl/sqlccl/restore.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpJqA8CHhaxeTg9j7-:-KgpL85wlN4DOCNXAzgi:b-6b9nxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/restore.go#L278)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Just to make sure this is sane, you can't restore on top of an existing table name, right?
</blockquote></details>

correct, you can only restore into new names. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-:-KgpLfsHKKmg3P1l8j1l:b-d7i5pu)*

**Comment by a-robinson** [comment]
Ok, thanks for explaining. Once you cover the `into_db` case this'll look good to me.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup_test.go, line 648 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpQrMD2ionEO4Fgv2f:-KgpQrMESmGv5xandv0u:b-b9t4my) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/backup_test.go#L648)):*
> ```Go
> 		}
> 
> 		// columns not depended on by the view are unaffected.
> ```

Should you also check that the column that is depended on can't be dropped?

---

*[pkg/ccl/sqlccl/backup_test.go, line 655 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpQDAWYazaZmYZBqkF:-KgpQDAWYazaZmYZBqkG:bt6q1k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/backup_test.go#L655)):*
> ```Go
> 	})
> 
> 	t.Run("restore multi-table view", func(t *testing.T) {
> ```

It seems worth adding a test for restoring a view that depends on a table or view in a different database.

---

*[pkg/ccl/sqlccl/restore.go, line 273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpJVPBgZ-A5AhXqdG5:-KgpQyHqyIs_SU2xH8Av:bn4h074) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/restore.go#L273)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

good point. That said, this matches the other cods-table reference restore errors, all of which are slated for some polish once we can plumb the names rather than IDs though to them.
</blockquote></details>

I'm not commenting on using the ID vs the name, but rather on clarifying that the important issue is that the referenced relation has to be restored in the same operation. The current error could confuse someone who already has the referenced table in their cluster (e.g. because they restored it first).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-:-KgpRFPJFejz2gseq5qH:blew5zv)*

**Comment by dt** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup_test.go, line 648 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpQrMD2ionEO4Fgv2f:-KgpS2cYtZ_twjGRW2ln:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/backup_test.go#L648)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Should you also check that the column that is depended on can't be dropped?
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup_test.go, line 655 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpQDAWYazaZmYZBqkF:-KgpSXbNlPEFOKl3FeRR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/backup_test.go#L655)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It seems worth adding a test for restoring a view that depends on a table or view in a different database.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/restore.go, line 273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpJVPBgZ-A5AhXqdG5:-KgpVzJgsy_kIOlJWBQP:bb61j9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/restore.go#L273)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'm not commenting on using the ID vs the name, but rather on clarifying that the important issue is that the referenced relation has to be restored in the same operation. The current error could confuse someone who already has the referenced table in their cluster (e.g. because they restored it first).
</blockquote></details>

Done.

I just meant that the non-helpful error wasn't specific to this one -- all the must-be-restored-in-same-op errors are worded the same way and all need polish -- but I went ahead and reworded this one for now.

the just  'restore users table first to get site back up, then restore the rest' use-case is a known-issue, but introduces lots of edge cases and won't be in 1.0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-:-KgpVtIFzLm_TsU05Zzv:b-896fix)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/restore.go, line 273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-KgpJVPBgZ-A5AhXqdG5:-KgpYsoG8eYA24m98SJM:b-2tdtrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb26dae7bee287e6ac9eb4e1da47442205ca832/pkg/ccl/sqlccl/restore.go#L273)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.

I just meant that the non-helpful error wasn't specific to this one -- all the must-be-restored-in-same-op errors are worded the same way and all need polish -- but I went ahead and reworded this one for now.

the just  'restore users table first to get site back up, then restore the rest' use-case is a known-issue, but introduces lots of edge cases and won't be in 1.0.
</blockquote></details>

Ah, sorry for the misunderstanding!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14574#-:-KgpYyGrVqYi017t1rxs:bnfp4nl)*

**Pull request merged**
