### PR TITLE
githooks: avoid accidental branch push to origin

### PR DESCRIPTION
**Pull request by dt**
Branches are expected to be pushed to forks instead.

Release note: none.

### CODE REVIEW

**Review by rail — APPROVED** [review]
LGTM, :shipit:

**Comment by dt** [comment]
This won't prevent branches created on origin by folks using the github web editor but I don't think we can prevent those, as far as I can tell, without taking away push/merge rights entirely (which, I suppose we _could_ do if we went all-in on bors and had a CI job to tag releases for us). It seems like branch protection only works for existing branches, not creating branches. But hopefully it'll at least stem the tide of stray branches ending up on origin?

**Comment by dt** [comment]
Hm. I'm not sure if the makefile will re-run the githooks symlinking and set this up after people pull or if if we need to somehow invalidate that.

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by dt** [comment]
testing blathers here, plz ignore.

**Comment by dt** [comment]
blathers backport 21.2

**Comment by dt** [comment]
blathers backport 21.1

**Pull request merged**
