### PR TITLE
kvserver: fix bizarre race in node_liveness

### PR DESCRIPTION
**Pull request by ajwerner**
It seems that the transport_race can tickle a bizarre race in the face of a
retry in updating node liveness record and the transport race stuff.

This patch does mean we'll allocate a roachpb.Value per retry, but that seems fine
as we should almost never retry.

See the trace attached to the file I'll append to this PR.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
cc @jayshrivastava 

[datarace.txt](https://github.com/cockroachdb/cockroach/files/5294611/datarace.txt)

**Comment by knz** [comment]
Is this PR still relevant?

@irfansharif you may be interested in this too.

**Review by irfansharif — APPROVED** [review]
LGTM if still applicable.

**Review by andreimatei — COMMENTED** [review]
I think this patch is a bit unfortunate; I'd try to do something else instead. I believe the code that's being changed here is innocent; it's the race transport's fault for introducing the race when it shouldn't. The race transport is trying to protect against the "server" holding on to request memory beyond the life of the request. It does that by repeatedly reading all of the request - which would trigger a race with the server trying to mutate that memory. Unfortunately, this scheme cannot differentiate between the server mutating that memory and the client mutating that memory. Here it's the client that's doing the mutation, which should be allowed (in fact, giving the client the ability to retain ownership over that memory is the whole reason why the server is not allowed to hold on to the request). If you [look at the transport](https://github.com/cockroachdb/cockroach/blob/8c5253bbccea8966fe20e3cb8cc6111712f6f509/pkg/kv/kvclient/kvcoord/transport_race.go#L58-L63), you see that it already copies some parts of the request that the client mutates. I think it should copy more given this one client - perhaps clone `CPuts`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54883#-:-M_M0mB0-ObPbTwsc0N0:b-mfd2zk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
@andreimatei Would this patch make you happier:

```go
--- a/pkg/kv/kvclient/kvcoord/transport_race.go
+++ b/pkg/kv/kvclient/kvcoord/transport_race.go
@@ -15,9 +15,9 @@ package kvcoord
 import (
        "context"
        "encoding/json"
+       "github.com/cockroachdb/cockroach/pkg/util/protoutil"
        "io/ioutil"
        "math/rand"
-       "reflect"
        "sync/atomic"
        "time"
 
@@ -55,22 +55,12 @@ type raceTransport struct {
 func (tr raceTransport) SendNext(
        ctx context.Context, ba roachpb.BatchRequest,
 ) (*roachpb.BatchResponse, error) {
-       // Make a copy of the requests slice, and shallow copies of the requests.
-       // The caller is allowed to mutate the request after the call returns. Since
-       // this transport has no way of checking who's doing mutations (the client -
-       // which is allowed, or the server - which is not). So, for now, we exclude
-       // the slice and the requests from any checks, since those are the parts that
-       // the client currently mutates.
-       requestsCopy := make([]roachpb.RequestUnion, len(ba.Requests))
-       for i, ru := range ba.Requests {
-               // ru is a RequestUnion interface, so we need some hoops to dereference it.
-               requestsCopy[i] = reflect.Indirect(reflect.ValueOf(ru)).Interface().(roachpb.RequestUnion)
-       }
-       ba.Requests = requestsCopy
+       // Make a deep copy of the request. The caller is allowed to mutate the request
+       // after the call returns. Since this transport has no way of checking who's
+       // doing mutations (the client - which is allowed, or the server - which is not).
+       // So, copy the whole request to allow the client to modify things as it pleases.
+       ba := *(protoutil.Clone(&ba).(*roachpb.BatchRequest))
        select {
-       // We have a shallow copy here and so the top level scalar fields can't
-       // really race, but making more copies doesn't make anything more
-       // transparent, so from now on we operate on a pointer.
        case incoming <- &ba:
        default:
                // Avoid slowing down the tests if we're backed up.
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54883#-:-M_MKUrI8cu5-OXL6ptH:bhj6qfk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
I think so, yeah. I'm surprised that `protoutil.Clone` works with a `BatchRequest`; I though there's things that it can't handle. But since you claim it can, I wonder why the race transport hasn't been written like this from the beginning... Cause this seems like the right way to catch illegal server accesses without catching client accesses to the request. @nvanbenschoten do you have thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54883#-:-M_MTtZ02VBBck4oJeQo:bz1kdjb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
of course, if clone doesn't work, marshall+unmarshall will

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54883#-:-M_MVvvgCdXMssj7V6Lt:b-40w330)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> @nvanbenschoten do you have thoughts?

I'm very positive about your proposal, but only if what you said below is correct.

> The race transport is trying to protect against the "server" holding on to request memory beyond the life of the request. It does that by repeatedly reading all of the request - which would trigger a race with the server trying to mutate that memory. Unfortunately, this scheme cannot differentiate between the server mutating that memory and the client mutating that memory. Here it's the client that's doing the mutation, which should be allowed (in fact, giving the client the ability to retain ownership over that memory is the whole reason why the server is not allowed to hold on to the request).

Is this the case? Are we ok with a client mutating a request even after it has gotten an error back from the server? What if request's context was canceled and the server hasn't noticed yet and is still touching the request memory? What if the server has some asynchronous process that holds on to the memory (like async Raft application)? We're not disciplined about memory lifetimes on the server, which is why we've been forced to treat most memory as immutable by all actors.

**Review by andreimatei — COMMENTED** [review]
>  What if request's context was canceled and the server hasn't noticed yet and is still touching the request memory

There's two big cases - the server is remote or local. If it's remote, then the discussion is moot because there's no shared memory. If it's local, then the ctx cancelation should be synchronous.

> What if the server has some asynchronous process that holds on to the memory (like async Raft application)? 

Yeah... There are [various](https://github.com/cockroachdb/cockroach/blob/8c5253bbccea8966fe20e3cb8cc6111712f6f509/pkg/kv/kvclient/kvcoord/transport_race.go#L59) [comments](https://github.com/cockroachdb/cockroach/blob/cfb4b95d94e717e985423d5313c58187fbde5da4/pkg/kv/sender.go#L76-L88) that suggest that the client is free to mutate the request after the call returns, but indeed I think they all lie.

This area has always been a source of fear for me. I wonder if we should make the local transport always clone the whole request (perhaps just for writes) and let the client take ownership.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54883#-:-M_Muh8I6iB8mSypJbec:b-isdzq5)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
I'm going to assume that this has gone stale.

**Pull request closed without merging**
