### PR TITLE
sql: scanNode cleanup

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: remove unused scanColumnsConfig field

Release note: None

#### sql: don't check column visibility when initializing scanNode

This commit removes a left-over piece of code which verifies the
visibility of scanNode columns. Execution is not the place to do this,
these semantics are implemented in the optbuilder.

Release note: None

#### sql: simplify scanColumnsConfig

This change removes two fields from `scanColumnsConfig`:
 - `addUnwantedAsHidden`: the last use of this was in the physical
   scrub, which has recently been.. scrubbed.
 - `visibility`: this was always set to `ScanVisibilityPublicAndNotPublic`.

Release note: None

#### sql: remove index flags logic from scanNode

This commit removes leftover logic related to index hints which is now
defunct.

Released note: None

#### sql: remove privilege checks at scanNode init time

This commit removes privilege checks when initializing a scanNode.
This is no longer the business of this code.

Release note: None

#### sql: clean up unnamed struct in scanColumnsConfig

This commit replaces an unnamed struct with two fields.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-:-MtLyjxHCvfAwPdzvjQ2:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[-- commits, line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLwLrQ4P8FVGgMAVXW):*
Lol
___
*[-- commits, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLyDPLC3dwIuNNytk3):*
Where are the checks done now?
___
*[pkg/sql/distsql_physical_planner.go, line 1298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLx3hb1RORb67O2YHV:-MtLx3hb1RORb67O2YHW:b-3f3n53) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc02fe30e419ef85c9a06c6b22a454863ed5922/pkg/sql/distsql_physical_planner.go#L1298)):*
> ```Go
> 	// scanNodeToTableOrdinalMap is a map from scan node column ordinal to
> 	// table reader column ordinal.
> 	scanNodeToTableOrdinalMap := toTableOrdinals(n.cols, n.desc, execinfra.ScanVisibilityPublicAndNotPublic)
> ```

nit: looks like there are two callers of `toTableOrdinals` and both use `PublicAndNotPublic`, might be worth pushing it into the function itself.
___
*[pkg/sql/distsql_physical_planner.go, line 2275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLxPA21LRIZm8y3mr2:-MtLxPA21LRIZm8y3mr3:b-cu4e3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc02fe30e419ef85c9a06c6b22a454863ed5922/pkg/sql/distsql_physical_planner.go#L2275)):*
> ```Go
> 
> 	for i := range n.cols {
> 		ord := tableOrdinal(n.table.desc, n.cols[i].GetID(), execinfra.ScanVisibilityPublicAndNotPublic)
> ```

`tableOrdinal` now uses `Public` only for zigzag joiners, is that intended? Maybe it should also be using `PublicAndNotPublic`, similar to the lookup join? Then we could push the visibility into `tableOrdinal`.
___
*[pkg/sql/scan.go, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLyKmf7J37e5cTRrA4:-MtLyKmf7J37e5cTRrA5:b4qy7bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/84618cda72ee7874dfeec8bac7e8fd88987f9d38/pkg/sql/scan.go#L184)):*
> ```Go
> 
> 	if !p.skipSelectPrivilegeChecks {
> 		if err := p.CheckPrivilege(ctx, n.desc, privilege.SELECT); err != nil {
> ```

We have a similar check in `distSQLSpecExecFactory.constructZigzagJoinSide` and probably want to remove that too.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74839)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[-- commits, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLyDPLC3dwIuNNytk3):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Where are the checks done now?
</blockquote></details>

optbuilder, updated the commit message.
___
*[pkg/sql/distsql_physical_planner.go, line 2275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLxPA21LRIZm8y3mr2:-MtM91YGDOQ9emnlP49F:b-sk0tlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc02fe30e419ef85c9a06c6b22a454863ed5922/pkg/sql/distsql_physical_planner.go#L2275)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`tableOrdinal` now uses `Public` only for zigzag joiners, is that intended? Maybe it should also be using `PublicAndNotPublic`, similar to the lookup join? Then we could push the visibility into `tableOrdinal`.
</blockquote></details>

I agree, removed. This argument was just for another check which no longer makes sense here.
___
*[pkg/sql/scan.go, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtLyKmf7J37e5cTRrA4:-MtPINQD78D0pRCQjKIy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84618cda72ee7874dfeec8bac7e8fd88987f9d38/pkg/sql/scan.go#L184)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We have a similar check in `distSQLSpecExecFactory.constructZigzagJoinSide` and probably want to remove that too.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 6 of 6 files at r7, 1 of 1 files at r8, 6 of 6 files at r9, 2 of 2 files at r10, 4 of 4 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74839)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/distsql_physical_planner.go, line 2243 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtPWKex7ONmM9scrnVN:-MtPWKex7ONmM9scrnVO:b1b9iuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/309380642b12bcfe96a5006c6b822d9e6173f13e/pkg/sql/distsql_physical_planner.go#L2243)):*
> ```Go
> 		IndexIdx:          0,
> 		Type:              descpb.InnerJoin,
> 		Visibility:        execinfra.ScanVisibilityPublicAndNotPublic,
> ```

Do we also want to remove `Visibility` field from the processor specs? The comment on `TableReaderSpec.Visibility` suggests that `Public` is commonly used, but now I think we'll only use `PublicAndNotPublic`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74839)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2243 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-MtPWKex7ONmM9scrnVN:-MtPb4lPC1FFs5e9VZDs:bb77uf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/309380642b12bcfe96a5006c6b822d9e6173f13e/pkg/sql/distsql_physical_planner.go#L2243)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do we also want to remove `Visibility` field from the processor specs? The comment on `TableReaderSpec.Visibility` suggests that `Public` is commonly used, but now I think we'll only use `PublicAndNotPublic`.
</blockquote></details>

Yes!

**Review by yuzefovich — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r13, 3 of 3 files at r14, 4 of 4 files at r15, 4 of 4 files at r16, 15 of 15 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74839#-:-MtPjxFeCzoGFKt9n4Ke:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Pull request merged**
