### PR TITLE
roachtest: disable grafana annotations when not available for a cluster

### PR DESCRIPTION
**Pull request by renatolabs**
This updates the `AddGrafanaAnnotation` function to only return a
"grafana not available for this cluster" error once for each test
run. Support for the public Grafana instance is currently only
available on GCE, so if a test attempts to add several annotations and
logs on error, it could add a lot of noise to test logs.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
@DarrylWong let me know if this makes sense to you!

**Review by DarrylWong — APPROVED** [review]
This is fine with me as is, but I wonder if the `disableGrafanaAnnotations` logic should be implemented in `cluster`/`c.AddGrafanaAnnotation` instead. 

Non-mixedversion tests probably don't want to be spammed either is my thinking and this would avoid having to reimplement it for every test.

`c.grafanaTags` won't ever be added to besides the initial setup, so if we hit `ErrGrafanaNotAvailable` once we will hit it every time. So I don't think there's an edge case there.

**Comment by DarrylWong** [comment]
If you do decide to move `disableGrafanaAnnotations` to `cluster` I think you'd have to make sure to reset it in `WipeForReuse`. Seems unlikely but it is possible for `c.AddLabels` to fail adding the `testRunID` and Grafana won't be available for that test.

**Comment by renatolabs** [comment]
Makes sense! Lifted that logic to `clusterImpl`.

**Comment by DarrylWong** [comment]
LGTM, thanks for adding 😄

**Review by srosenberg — APPROVED** [review]

**Comment by renatolabs** [comment]
TFTRs!

bors r=DarrylWong,srosenberg

**Pull request merged**
