### PR TITLE
gossip: Race condition bug fix + miscellaneous cleanup/fixes

### PR DESCRIPTION
**Pull request by a-robinson**
Ignore the first four commits, they're just copied over from #12880.

Beyond that, the other commits include two style changes and three bug fixes / behavior improvements, respectively. See commit messages for descriptions.

@tamird @spencerkimball

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12920)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 5 of 5 files at r9.
Review status: 6 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/gossip/gossip.go, line 685 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPCfvoY-JrBzA_PVdG:-KaPCfvoY-JrBzA_PVdH:b-4crr22) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d2922192abf1fd1f26225c17bbf46cd3131ef8f/pkg/gossip/gossip.go#L685)):*
> ConnectionsRefused

camel case implies this being a name, i think you want "connection refused".

---

*[pkg/gossip/gossip.go, line 914 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPG2jBnkuAxKOonEmz:-KaPG2jBnkuAxKOonEn-:b-nn40rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip.go#L914)):*
> ```Go
> // node in the system, according to the infos which have reached
> // this node via gossip network.
> func (g *Gossip) MaxHops() uint32 {
> ```

drive-by: this method is only used in one place; it might make sense to export `mostDistant` instead of maintaining both.

---

*[pkg/gossip/gossip.go, line 1136 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFKRh08onMpCdeyBm:-KaPFKRh08onMpCdeyBn:b51odj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip.go#L1136)):*
> ```Go
> 		distantNodeID, distantHops := g.mu.is.mostDistant(g.hasOutgoingLocked)
> 		if log.V(2) {
> 			log.Infof(ctx, "distantHops: %d from %d", distantHops, distantNodeID)
> ```

veventf?

---

*[pkg/gossip/gossip.go, line 1138 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFWxtgIuK7_nw52cQ:-KaPFWxtgIuK7_nw52cR:bxuq9hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip.go#L1138)):*
> ```Go
> 			log.Infof(ctx, "distantHops: %d from %d", distantHops, distantNodeID)
> 		}
> 		if distantHops <= MaxHops {
> ```

where is maxHops defined?

---

*[pkg/gossip/gossip_test.go, line 229 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFph-X_Fx91VuEoGB:-KaPFph-X_Fx91VuEoGC:brrn4qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip_test.go#L229)):*
> ```Go
> 
> 	// Verify that we can't open more than maxPeers connections. We have to muck
> 	// with the infostore's data so that the other nodes will appear far enogh
> ```

s/enogh/enough/

---

*[pkg/gossip/gossip_test.go, line 238 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFsI7cjJd0lU1wc1U:-KaPFsI7cjJd0lU1wc1V:b-ndvkih) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip_test.go#L238)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	local.mu.Unlock()
> ```

the fatal above here might mess with shutdown. unlock before checking the error?

---

*[pkg/gossip/infostore.go, line 380 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPEbLLy7qd--vIMluj:-KaPEbLLy7qd--vIMluk:b9jf3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/infostore.go#L380)):*
> ```Go
> // This check is particularly useful if mostDistant is called multiple times
> // in quick succession.
> func (is *infoStore) mostDistant(
> ```

this method has one non-test caller; perhaps it wants to be a method on `gossip.Gossip` directly?

---

*[pkg/gossip/infostore_test.go, line 280 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPEmE_Mv4tTPaPRv2B:-KaPEmE_Mv4tTPaPRv2C:b-hf9c9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/infostore_test.go#L280)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		nodeID, hops := is.mostDistant(func(roachpb.NodeID) bool { return false })
> ```

does this compile? i'd expect you to need `_ roachpb.NodeID` here.

---

*[pkg/gossip/server.go, line 226 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPDRzTZC4WfCKidH9W:-KaPDRzUZlgBAEmQV7pu:boxmz4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L226)):*
> ```Go
> 	defer s.mu.Unlock()
> 
> 	// This is a duplicate connection from a node.
> ```

this is a duplicate comment? or did you mean for there to be a blank line between this one and the next?

---

*[pkg/gossip/server.go, line 285 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPDji-hrwiQEiJ7SBf:-KaPDji-hrwiQEiJ7SBg:bxn97ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L285)):*
> ```Go
> 	return func() {
> 		if log.V(2) {
> 			log.Infof(ctx, "removing node %d from incoming set", args.NodeID)
> ```

VEventf?

---

*[pkg/gossip/server.go, line 66 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFDLvtKBPUjIByO75:-KaPFDLvtKBPUjIByO76:b-gy5llu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/server.go#L66)):*
> ```Go
> 		ready chan struct{}
> 	}
> 	tighten chan struct{} // Channel indicating that we may want to tighten the network
> ```

dubious comment usefulness

---

*[pkg/gossip/server.go, line 366 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFBm8MAYnqjOYFyrU:-KaPFBm8MAYnqjOYFyrV:b-l6mwxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/server.go#L366)):*
> ```Go
> 	case s.tighten <- struct{}{}:
> 	default:
> 		// Do nothing.
> ```

remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-:-KaPEFGZGjzUF1AHLWo6:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r4, 1 of 3 files at r6, 5 of 5 files at r9.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[pkg/gossip/server.go, line 138 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaSuU-qETbXGI2SDfRA:-KaSuU-qETbXGI2SDfRB:b-hrupve) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L138)):*
> ```Go
> 	defer func() { syncChan <- struct{}{} }()
> 
> 	doneFn, err := s.initGossipReceiver(ctx, args, send)
> ```

I don't understand why `gossipReceiver` was split into two functions. Wouldn't it be enough to move this check for duplicate connections from `server.Gossip` into `gossipReceiver`? 

---

*[pkg/gossip/server.go, line 220 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaStBKl3SxZyc-CPQmq:-KaStBKl3SxZyc-CPQmr:bl3zloh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L220)):*
> ```Go
> 			log.Infof(ctx, "ignoring gossip from node %d (loopback)", args.NodeID)
> 		}
> 		return nil, nil
> ```

Shouldn't this return an error? 

---

*[pkg/gossip/server.go, line 263 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaStWBYxLNQD60VjZVt:-KaStWBYxLNQD60VjZVu:bcn0d97) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L263)):*
> ```Go
> 
> 		// Unlock while sending RPC, but re-lock before returning to avoid violating
> 		// the caller's expectations.
> ```

It's not the caller, it's the deferred unlock in this function.

---

*[pkg/gossip/server.go, line 267 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaStj5debU--4QvHKrw:-KaStj5debU--4QvHKrx:br8fb9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L267)):*
> ```Go
> 		err := senderFn(reply)
> 		s.mu.Lock()
> 		return nil, err
> ```

The old code specifically did not return here to ensure that the reply was processed before the connection is closed.  Was that unnecessary before? I don't see why the need for that would be changing now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-:-KaSvohKcJLStkFxqfdC:bnfp4nl)*

**Comment by a-robinson** [comment]
Thanks for the reviews! You might want to take a second look at the server.go logic, since I've moved the connection initialization logic back into gossipReceiver.

---

Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[pkg/gossip/gossip.go, line 685 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPCfvoY-JrBzA_PVdG:-Kaf2vBoWjegtdrQBtlK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d2922192abf1fd1f26225c17bbf46cd3131ef8f/pkg/gossip/gossip.go#L685)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> ConnectionsRefused

camel case implies this being a name, i think you want "connection refused".
</blockquote></details>

Done.

---

*[pkg/gossip/gossip.go, line 914 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPG2jBnkuAxKOonEmz:-KaheLPVVNiaTsZ_e_d3:bx7p32) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip.go#L914)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

drive-by: this method is only used in one place; it might make sense to export `mostDistant` instead of maintaining both.
</blockquote></details>

I must be misunderstanding your comment, since we can't export infostore's `mostDistant` method because it requires the lock to be held. It also would have to be wrapped by gossip.Gossip since the infostore member isn't embedded. And it'd also be exporting the behavior of returning the most distant node, which would be exposing info that isn't needed outside this package.

---

*[pkg/gossip/gossip.go, line 1136 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFKRh08onMpCdeyBm:-KahsBECRN-geqOp3o9k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip.go#L1136)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

veventf?
</blockquote></details>

Done.

---

*[pkg/gossip/gossip.go, line 1138 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFWxtgIuK7_nw52cQ:-Kaf3G0pXpckHJTQRzhs:bued2sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip.go#L1138)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

where is maxHops defined?
</blockquote></details>

It's a package-level constant. It apparently isn't exported anywhere though, so I've made it private.

---

*[pkg/gossip/gossip_test.go, line 229 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFph-X_Fx91VuEoGB:-Kaf4I7pcfVXIBjaKAEL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip_test.go#L229)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/enogh/enough/
</blockquote></details>

Done.

---

*[pkg/gossip/gossip_test.go, line 238 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFsI7cjJd0lU1wc1U:-Kaf4Z3I17PjYCCc0Rzw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/gossip_test.go#L238)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the fatal above here might mess with shutdown. unlock before checking the error?
</blockquote></details>

Done.

---

*[pkg/gossip/infostore.go, line 380 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPEbLLy7qd--vIMluj:-Kahfn6lKbQJBh_LVNSb:b-nbq7sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/infostore.go#L380)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this method has one non-test caller; perhaps it wants to be a method on `gossip.Gossip` directly?
</blockquote></details>

Two non-test callers (`MaxHops` and `tightenNetwork`), but you're right that it doesn't particularly belong here. Neither do the infostore's `delta` and `leastUseful` methods, but I don't think their placement is a terribly big deal at the moment, particularly given that they're nicely grouped with each other.

---

*[pkg/gossip/infostore_test.go, line 280 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPEmE_Mv4tTPaPRv2B:-Kaf6nUfv2RP4kALb5LS:bzfcyhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/infostore_test.go#L280)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

does this compile? i'd expect you to need `_ roachpb.NodeID` here.
</blockquote></details>

Yeah, it compiles and runs just fine.

---

*[pkg/gossip/server.go, line 138 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaSuU-qETbXGI2SDfRA:-KahgMFMNEsw6LB0fFZ3:b-cgb5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L138)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't understand why `gossipReceiver` was split into two functions. Wouldn't it be enough to move this check for duplicate connections from `server.Gossip` into `gossipReceiver`? 
</blockquote></details>

I was trying to separate the concerns, but you're right that it didn't really have to be split. We just had to not do the connection acceptance test in every loop iteration. Moved it back into `gossipReceiver`, but added a variable to avoid doing the connection init checks more than once such that we can safely do the duplicate connection check.

---

*[pkg/gossip/server.go, line 220 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaStBKl3SxZyc-CPQmq:-KahgBJZAc4MThW14BOU:bzfccxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L220)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Shouldn't this return an error? 
</blockquote></details>

Great catch, yeah. This was negative fallout from trying to move the init code to its own method.Great catch, yeah. This was negative fallout from trying to move the init code to its own method. Not relevant after moving the code back

---

*[pkg/gossip/server.go, line 226 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPDRzTZC4WfCKidH9W:-Kaf7iqBrzpq066BaQc3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L226)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is a duplicate comment? or did you mean for there to be a blank line between this one and the next?
</blockquote></details>

Done.

---

*[pkg/gossip/server.go, line 263 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaStWBYxLNQD60VjZVt:-Kaf7uAMDKFMAUl3umQI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L263)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's not the caller, it's the deferred unlock in this function.
</blockquote></details>

Done.

---

*[pkg/gossip/server.go, line 267 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaStj5debU--4QvHKrw:-KahpuPxwjMU6Z4PbKC9:b8vf8gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L267)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The old code specifically did not return here to ensure that the reply was processed before the connection is closed.  Was that unnecessary before? I don't see why the need for that would be changing now. 
</blockquote></details>

Not relevant anymore, but I believe what I had done here was safe - the carefulness that's needed inside gossipReceiver is due to the way it interacts with the send loop in 

---

*[pkg/gossip/server.go, line 285 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPDji-hrwiQEiJ7SBf:-KahrJAxOt9QDtjAqoJw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea5b59e5fb4c202a9a5b238eabcb139a09f203c/pkg/gossip/server.go#L285)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

VEventf?
</blockquote></details>

Done.

---

*[pkg/gossip/server.go, line 66 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFDLvtKBPUjIByO75:-Kaf7Rwgog7G-iTvbhlZ:b-eqi7q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/server.go#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

dubious comment usefulness
</blockquote></details>

Tweaked a little.

---

*[pkg/gossip/server.go, line 366 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-KaPFBm8MAYnqjOYFyrU:-KahdtR-gvSrtv01mup8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eaf20a384064cfc27837c57afe36231e55fcd22/pkg/gossip/server.go#L366)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920#-:-KahsBq_MKC8bfObshLO:bf0ppmd)*

**Comment by tamird** [comment]
Reviewed 1 of 6 files at r4, 8 of 8 files at r10, 1 of 2 files at r12, 3 of 5 files at r14, 2 of 2 files at r15.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12920)*

**Pull request merged**
