### PR TITLE
opt: support multiple expression spans, implement neOp

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: simplify scalar expression printout

Remove the unnecessary intermediate "inputs:" node from scalar
expression tree printouts.

Release note: None

#### opt: support multiple expression spans, implement neOp

The existing code only works with expressions that generate a single span.
This change adds support for multiple spans. We implement neOp as the first
use-case.

We make a small change on how we use LogicalKeys: instead of modifying them in
place (by copying from one Vals to another), we now allow LogicalKeys to alias
the same slices. This works because the only mutation we allow is appending.

Release Note: None.

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

Just a few suggestions below for clarifying the comments.

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 347 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0GuNnELEFMXUsPDLcP:-L0GuNnELEFMXUsPDLcQ:b-jt14iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/index_constraints.go#L347)):*
> ```Go
> 
> // intersectSpanSet intersects a span with (the union of) a set of spans. The
> // spans must be ordered and non-overlapping. The spanSet is modified in-place
> ```

It doesn't look like it's modified in place...

---

*[pkg/sql/opt/index_constraints.go, line 477 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0GyCY20PtXY5e7lY4a:-L0GyCY20PtXY5e7lY4b:b-uh5888) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/index_constraints.go#L477)):*
> ```Go
> 			// Special case when the start and end keys are equal (i.e. an exact value
> 			// on this column). This is the only case where we can break up a single
> 			// span into multiple spans.
> ```

I think this could use a little more explanation.  I think I understand now after looking at the test cases, but maybe you could give some examples here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-:-L0H-CtTgnMc81gCZcYK:bfelu18)*

**Comment by petermattis** [comment]
First commit LGTM. I need to give the second commit a closer look later.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0GzEuXFVB0GARguMlE:-L0GzEuYFL73P8wQHosV:b-lmqshx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/index_constraints.go#L52)):*
> ```Go
> 
> // Returns a copy that can be extended independently.
> func (k *LogicalKey) copy() LogicalKey {
> ```

Is there a reason this is operating on a pointer receiver? 

We use the term `clone` elsewhere in the code base.

---

*[pkg/sql/opt/testdata/index-constraints, line 12 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0Gzrsq03jBJTf_xK2S:-L0Gzrsq03jBJTf_xK2T:b-xyy9bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/testdata/index-constraints#L12)):*
> ```
> 
> build-scalar,normalize,index-constraints int
> @1 != 2
> ```

I assume you're looking at existing test cases in `opt_index_selection_test.go`. Might be worthwhile to telegraph the work that remains by copying over and commenting out test-cases which don't work yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-:-L0H-CehB7z0s1RwL40P:bwhy3aj)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/index_constraints.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0GzEuXFVB0GARguMlE:-L0H4eIRwHGnwMbvC19P:by1dz64) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/index_constraints.go#L52)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason this is operating on a pointer receiver? 

We use the term `clone` elsewhere in the code base.
</blockquote></details>

Figured it saves a copy of the structure, not sure. Changed to clone and non-pointer receiver.

---

*[pkg/sql/opt/index_constraints.go, line 347 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0GuNnELEFMXUsPDLcP:-L0H4u2DZNDxupjfHXzi:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/index_constraints.go#L347)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It doesn't look like it's modified in place...
</blockquote></details>

Fixed.

---

*[pkg/sql/opt/index_constraints.go, line 477 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0GyCY20PtXY5e7lY4a:-L0H4ZmQFRrZ0Pa8Pq-U:b-qsphwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/index_constraints.go#L477)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this could use a little more explanation.  I think I understand now after looking at the test cases, but maybe you could give some examples here as well.
</blockquote></details>

Done. Added an example below as well.

---

*[pkg/sql/opt/testdata/index-constraints, line 12 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0Gzrsq03jBJTf_xK2S:-L0H2_6ZhCBVAF2Kwa76:bhgq77d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/testdata/index-constraints#L12)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I assume you're looking at existing test cases in `opt_index_selection_test.go`. Might be worthwhile to telegraph the work that remains by copying over and commenting out test-cases which don't work yet.
</blockquote></details>

Ah, I haven't looked at those yet. Will go through them when I get farther along.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 477 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0GyCY20PtXY5e7lY4a:-L0H9mIIHr1EfvegWrkP:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8cc571a04754663373d86a1cb9f3f3046da0c0/pkg/sql/opt/index_constraints.go#L477)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done. Added an example below as well.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 490 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0HqOx6xM0NPXR1uUpg:-L0HqOx6xM0NPXR1uUph:bv50zrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac91e85c6536a402e46c7a90a0069119a51ce493/pkg/sql/opt/index_constraints.go#L490)):*
> ```Go
> 			//    [/1/3 - /1/3]
> 			//    [/1/4 - /1/4]
> 			//    [/1/5 - /1/5]
> ```

Love this comment and some of the others, though it seems we don't support `IN` yet, right? I was looking for this example in the tests and couldn't find it. That's fine, just making sure I'm not missing anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-:-L0Hr7I9gZk_qznciRM7:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 490 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695#-L0HqOx6xM0NPXR1uUpg:-L0Hs2FFzarmXZlb3UHL:bro8k0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac91e85c6536a402e46c7a90a0069119a51ce493/pkg/sql/opt/index_constraints.go#L490)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Love this comment and some of the others, though it seems we don't support `IN` yet, right? I was looking for this example in the tests and couldn't find it. That's fine, just making sure I'm not missing anything.
</blockquote></details>

We don't. But look out for a new PR in 5, 4, ..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20695)*

**Pull request merged**
