### PR TITLE
client: send Txn BatchRequests through db.send

### PR DESCRIPTION
**Pull request by nvb**
Addresses a TODO which is possible now that `db.send` takes a context.

It also removes a blank identifier assignment of `Txn.ReverseScan`
use to avoid an unused warning previously, along with an associated
TODO.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13638)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13638#-:-KdBK5mf-45TqdskLnmd:bnfp4nl)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/internal/client/txn.go, line 579 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13638#-KdBbLbssBsGwohLe5WZ:-KdBbLbssBsGwohLe5W_:bhn0t7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/daacbc9a0f3c1c045a763c31cd3b1d1f010c3e3d/pkg/internal/client/txn.go#L579)):*
> ```Go
> 		return nil, nil
> 	}
> 	if pErr := txn.db.prepareToSend(&ba); pErr != nil {
> ```

care to remove `prepareToSend` entirely? it has one remaining caller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13638#-:-KdBbc7KLkcxNO46jwCX:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/internal/client/txn.go, line 579 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13638#-KdBbLbssBsGwohLe5WZ:-KdCwYM5NRVvvN1A04np:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/daacbc9a0f3c1c045a763c31cd3b1d1f010c3e3d/pkg/internal/client/txn.go#L579)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

care to remove `prepareToSend` entirely? it has one remaining caller.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13638)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13638)*

**Comment by nvanbenschoten** [comment]
TFTRs.

**Pull request merged**
