### PR TITLE
distsqlrun: Ignore breaker when outbox dials node

### LINKED ISSUE #38602: distsqlrun: ignore breaker when outbox dials node
https://github.com/cockroachdb/cockroach/blob/5a0ae02c62d8a1eb50e930eeda634d32be297d58/pkg/sql/distsqlrun/outbox.go#L220

When nodes in the cluster have recently restarted, the above dial can fail which results in the "dialee" failing with a "no inbound stream connection" error after a long timeout (10s).

In the outbox, one is relatively sure that the node is reachable (otherwise, the gateway probably would not have set the flow up that way), so it might be better in general to ignore the breaker, or to mitigate this somewhat.

See https://github.com/cockroachdb/cockroach/pull/38484#issuecomment-507592410

### PR DESCRIPTION
**Pull request by rohany**
Fixes #38602.

Release justification: Fixes an outstanding bug.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Let me know if this approach makes sense, and the best way to test a change like this.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40691)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rohany, and @tbg)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-LoX1XmF022LrNKljxf_:-LoX1XmGCAEbjfWLHxIp:b-yjtilp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f354516ddda9b5ed7355f08be6a2326b225c9eda/pkg/rpc/nodedialer/nodedialer.go#L95)):*
> ```Go
> // DialNoBreaker ignores the breaker if there is an error dialing. This function
> // should only be used when there is good reason to believe that the node is reachable.
> func (n *Dialer) DialNoBreaker(
> ```

it seems like this is implemented the same as the above function apart from the breaker stuff. to keep the code DRY, would it make sense to have `Dial` and `DialNoBreaker` call out to the same helper function? the only line we would want to skip in the latter case is `breaker.Fail(err)` i think, so the helper function could just accept a flag for that.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40691)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @tbg)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-LoX1XmF022LrNKljxf_:-LoX3VtwAYBXXKZgSwDj:bu4jrvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f354516ddda9b5ed7355f08be6a2326b225c9eda/pkg/rpc/nodedialer/nodedialer.go#L95)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it seems like this is implemented the same as the above function apart from the breaker stuff. to keep the code DRY, would it make sense to have `Dial` and `DialNoBreaker` call out to the same helper function? the only line we would want to skip in the latter case is `breaker.Fail(err)` i think, so the helper function could just accept a flag for that.
</blockquote></details>

theres some other breaker related stuff happening in unexported `node.dial` that we want to avoid too. However, it turned out to be cleaner there than I thought than to just handle a nil breaker.

**Review by asubiotto — APPROVED** [review]
:lgtm: from my perspective, might be good to add a test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-:-LoZBpdC-AU3OXgBGX9s:b-cf1ajh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, @rohany, and @tbg)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-LoZBhG07NKPUHbt0JKK:-LoZBhG07NKPUHbt0JKL:bhqlamw) ([raw file](https://github.com/cockroachdb/cockroach/blob/888452c21cf905b9b7e993c485c991b9f4fccb46/pkg/rpc/nodedialer/nodedialer.go#L193)):*
> ```Go
> 	// as a stop-gap before the reconciliation occurs.
> 	if breaker != nil {
> 		breaker.Success()
> ```

Maybe make these nil checks part of the `Fail` and `Success` methods?
___
*[pkg/sql/distsqlrun/outbox.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-LoZBVvl0uDbQmxeoDD1:-LoZBVvl0uDbQmxeoDD2:boq3d30) ([raw file](https://github.com/cockroachdb/cockroach/blob/888452c21cf905b9b7e993c485c991b9f4fccb46/pkg/sql/distsqlrun/outbox.go#L226)):*
> ```Go
> 			// a critical part of query execution: if this step doesn't work, the
> 			// receiving side might end up hanging or timing out.
> 			// TODO(asubiotto): We should retry a failed Dial. This rests on the
> ```

I think we can remove this TODO, if we attempt to connect to a node that was healthy at plan time and it fails even while ignoring the breaker, that's probably a good enough reason to exit.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40691)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @tbg)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-LoZBhG07NKPUHbt0JKK:-Lo_uHkMBiKOz4Nfqe8p:bin5as6) ([raw file](https://github.com/cockroachdb/cockroach/blob/888452c21cf905b9b7e993c485c991b9f4fccb46/pkg/rpc/nodedialer/nodedialer.go#L193)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe make these nil checks part of the `Fail` and `Success` methods?
</blockquote></details>

I think it is more explicit this way that we are ignoring the breaker.
___
*[pkg/sql/distsqlrun/outbox.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-LoZBVvl0uDbQmxeoDD1:-Lo_uWT90akCLDvimMjg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/888452c21cf905b9b7e993c485c991b9f4fccb46/pkg/sql/distsqlrun/outbox.go#L226)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we can remove this TODO, if we attempt to connect to a node that was healthy at plan time and it fails even while ignoring the breaker, that's probably a good enough reason to exit.
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm too, and i agree about adding a test if you can

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-:-LoaRDXS9yNUyVTgDfG6:b-e3rov0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @rafiss, and @tbg)

**Review by rafiss — APPROVED** [review]
the test looks great!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40691#-:-Lob9Vc_EohLxbm6HKeQ:b-8um8di)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @rafiss, and @tbg)

**Comment by rohany** [comment]
I think this is a test flake. Retrying.

bors r+

**Comment by rafiss** [comment]
The flake should be resolved by #40757

**Comment by rohany** [comment]
run it back -- some other PR's got in

bors r+

**Pull request merged**
