### PR TITLE
sql/parser: remove extra allocation while parsing x'val' literals

### LINKED ISSUE #7156: sql: remove extra allocation when parsing x'val' literals
Scanning x'val' literals does an extra copy and allocation, since `scanString` returns a string that the literal parser just converts into bytes and back when using `hex.DecodeString`. Remove this extra work.

From @petermattis's comment on #7138:

> It's mildly unfortunate for scanString to scan into a buf []byte, then convert that to a string before returning just so it can be passed to hex.DecodeString. It might be better to pass an additional flag to scanString so that we could call hex.Decode(buf) instead, avoiding an allocation and a copy. Also, it looks like hex.Decode(buf, buf) works as the writing to the output trails the input. This would avoid an additional allocation.

### PR DESCRIPTION
**Pull request by nexthack**
The existing code scans the x'val'-style input bytes and passes the string
for hex decoding.While decoding the string is again converted to bytes and
decoded. Finally the decoded bytes are converted to the final string.This
commit modifies the code to remove these extra allocations.

@jordanlewis 

Fixes #7156.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10660)

### CODE REVIEW

**Comment by jordanlewis** [comment]
Thanks for your submission!

This LGTM, but I don't love how you've had to modify the signature of `scanString` for this particular use case of decoding hex, since it adds complexity to every callsite. Can you think of a way to avoid this?

One initial thought that comes to mind is a small refactor where `scanString` is renamed to something like `scanStringOrHex`, and a new `scanString` introduced that has the same signature as the old `scanString` that simply calls `scanStringOrHex` with a `decodeHex` argument of false.

**Comment by crackerplace** [comment]
@jordanlewis I agree on the complexity as I initially thought of ways to overcome.Somehow I was struck in other directions.Will implement as that looks simple.
Should I amend the commit or go for a new one ?

**Comment by jordanlewis** [comment]
Amending would be preferable. Thank you!

**Comment by crackerplace** [comment]
@jordanlewis Amended the changes.Thanks.

**Review by jordanlewis — APPROVED** [review]
LGTM!

**Pull request merged**
