### PR TITLE
raft: switch LazyReplication dynamically

### PR DESCRIPTION
**Pull request by pav-kv**
This PR makes it possible to dynamically switch the lazy `MsgApp` replication mode for flows in `StateReplicate`.

Part of #128779

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131701#-:-O89GpNX7H7tDNw7lYCe:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — COMMENTED** [review]
Looks good to me - very clean. Will you add a datadriven test before merge?

**Comment by pav-kv** [comment]
@tbg

> Will you add a datadriven test before merge?

There was one (last commit).

**Comment by pav-kv** [comment]
bors r=tbg,sumeerbhola

**Comment by tbg** [comment]
Oh, sorry about that - missed the scroll in the commit list. Lgtm

**Pull request merged**
