### PR TITLE
cli/debug: new sub-command `list-files`

### PR DESCRIPTION
**Pull request by knz**
Prerequisite to #64094.

This is meant to assist the human operator select appropriate
flags for the `debug zip` command.

Release note (cli change): The new command `debug list-files`
show the list of files that can be retrieved via the `debug zip`
command. It supports the `--nodes` and `--exclude-nodes` parameters
in the same way as `debug zip`.

### CODE REVIEW

**Review by stevendanna — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxXX9V2-EcHGFdqNXf:-MYxXX9V2-EcHGFdqNXg:b-6x2ue5) (no related file):*
This seems like a nice addition!

I left a few comments but nothing blocking except for the small function name-change that happened that is likely the cause of the CI failures.  Would it make sense to add a test or two for this?  I imagine a lot of the underlying tooling is already tested and I see there are some test additions in the follow-on PR re file filtering, so I leave it to your judgement there.

---
___
*[pkg/cli/debug_list_files.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxUlb7AQerdw-QRBZ5:-MYxUlb7AQerdw-QRBZ6:b-l2vgw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db236d57a68c67f4c3163f5d509e04aa1274d1a/pkg/cli/debug_list_files.go#L124)):*
> ```Go
> 	var rows [][]string
> 	for _, nodeID := range nodeList {
> 		nodeIDs := fmt.Sprintf("%d", nodeID)
> ```

If you fancy: we could use strconv.FormatInt here and a few other places in this file.
___
*[pkg/cli/debug_list_files.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxUqiaE3cCQte3bSDb:-MYxUqiaE3cCQte3bSDc:b64y3hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db236d57a68c67f4c3163f5d509e04aa1274d1a/pkg/cli/debug_list_files.go#L131)):*
> ```Go
> 			fileType := int32(ft)
> 			for _, other := range otherFiles[nodeID][fileType] {
> 				rows = append(rows, []string{nodeIDs, strings.ToLower(serverpb.FileType_name[fileType]), other.Name, fmt.Sprintf("%d", other.FileSize)})
> ```

It almost surely doesn't matter, but we could construct a small map of these while iterating over FileType_value above so we don't need to ToLower the same string repeatedly.
___
*[pkg/cli/debug_list_files.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxUaT-0RochGzQXDMP:-MYxUaT-0RochGzQXDMQ:b-x0q5f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db236d57a68c67f4c3163f5d509e04aa1274d1a/pkg/cli/debug_list_files.go#L136)):*
> ```Go
> 	}
> 
> 	return printQueryOutput(os.Stdout, fileTableHeaders, newRowSliceIter(rows, alignment))
> ```

`printQueryOutput` and `newRowSliceIter` were changed to exported functions in 3caed9e4b37a06333b0fcc8ad216e8f01cc9d48b

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[pkg/cli/debug_list_files.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxUlb7AQerdw-QRBZ5:-MYxuQaB96fhD3zk8HJx:b-hoai67) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db236d57a68c67f4c3163f5d509e04aa1274d1a/pkg/cli/debug_list_files.go#L124)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

If you fancy: we could use strconv.FormatInt here and a few other places in this file.
</blockquote></details>

I thought about it, and unfortunately I find `strconv.FormatInt(int64(nodeID), 10)` less readable.
___
*[pkg/cli/debug_list_files.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxUqiaE3cCQte3bSDb:-MYxudq5Bou0A4iwAObz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db236d57a68c67f4c3163f5d509e04aa1274d1a/pkg/cli/debug_list_files.go#L131)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

It almost surely doesn't matter, but we could construct a small map of these while iterating over FileType_value above so we don't need to ToLower the same string repeatedly.
</blockquote></details>

Done.
___
*[pkg/cli/debug_list_files.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxUaT-0RochGzQXDMP:-MYxv-xP40toVLVFKIEy:blp8bhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db236d57a68c67f4c3163f5d509e04aa1274d1a/pkg/cli/debug_list_files.go#L136)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

`printQueryOutput` and `newRowSliceIter` were changed to exported functions in 3caed9e4b37a06333b0fcc8ad216e8f01cc9d48b
</blockquote></details>

Thank you! fixed.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[pkg/cli/debug_list_files.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64071#-MYxUlb7AQerdw-QRBZ5:-MYy3IWS8pYduRNewIix:b-e7shts) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db236d57a68c67f4c3163f5d509e04aa1274d1a/pkg/cli/debug_list_files.go#L124)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I thought about it, and unfortunately I find `strconv.FormatInt(int64(nodeID), 10)` less readable.
</blockquote></details>

Ah, I missed that nodeID's aren't already ints here.  So probably the shortest you could get with strconv is `strconv.Itoa(int(nodeID))`. Anyway, current code is fine by me. :+1:

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Comment by knz** [comment]
gosh, darn linter

bors r=stevendanna

**Comment by knz** [comment]
that was bors on a stale SHA, retrying

bors r=stevendanna

**Pull request merged**
