### PR TITLE
kvstreamer: fix a couple of edge case bugs

### LINKED ISSUE #74898: kv/kvclient/kvstreamer: TestStreamerBudgetErrorInEnqueue failed
kv/kvclient/kvstreamer.TestStreamerBudgetErrorInEnqueue [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4132347&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4132347&tab=artifacts#/) on master @ [5ad21e3896ee809e9c3ebc28bb22166f1275acca](https://github.com/cockroachdb/cockroach/commits/5ad21e3896ee809e9c3ebc28bb22166f1275acca):

Fatal error:

```
panic: root: no bytes in account to release, current 10, free 1048627 [recovered]
	panic: root: no bytes in account to release, current 10, free 1048627

```
Stack: 

```
goroutine 2080 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0015303f0, {0x4e6b130, 0xc0014076a0})
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:251 +0x94
panic({0x3acbfe0, 0xc000d0ad38})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0x4e6b130, 0xc0014076a0}, 0xc0005d4000, {0x3e35ec2, 0x40}, {0xc0021f3a18, 0x7fbdc8ed1108, 0x50})
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:376 +0x1af
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc000d0a4f8, {0x4e6b130, 0xc0014076a0}, 0x100033)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:636 +0x127
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*budget).release(0xc001d1cc80, {0x4e6b130, 0xc0014076a0}, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/budget.go:117 +0xa9
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*workerCoordinator).performRequestAsync.func1({0x4e6b130, 0xc0014076a0})
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/streamer.go:1025 +0x3af
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488 +0x12a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:478 +0x445
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestStreamerBudgetErrorInEnqueue/single_key_exceeds_root_pool_size
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStreamerBudgetErrorInEnqueue.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: fix rare race condition**

This commit refactors the locking logic in an error case in `Enqueue`
where previously we had a rare race condition. We divided the locking
state across two things (the mutex and a boolean indicating whether the
mutex is locked) which together were not accessed atomically. This
commit removes the boolean by forcing that the mutex is held when
`Enqueue` returns.

Release note: None

**kvstreamer: fix the case when root pool is exhausted**

Each request processed asynchronously assumes that the memory footprint
of the spans in the request has already been accounted for. This
assumption was broken in case `Enqueue` encountered an error when
consuming from the budget due to root pool being exhausted.

The sequence of steps to get into a problematic state was as follows:
- spin up the worker coordinator, it blocks until there are any requests
to serve
- populate requests to serve
- `s.mu` is unlocked to perform the memory accounting
- the worker coordinator wakes up and picks up some work
- memory reservation is denied in `Enqueue`, an error is returned; thus,
we have a drift in the memory accounting
- concurrent request is responded to, and when it attempts to reconcile
the memory accounting, a crash (in test builds) occurs because the
memory reservation in `Enqueue` was denied.

This is now fixed by not telling the worker coordinator about the
requests to serve until after the memory accounting is performed.

Fixes: #74898.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75078)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MtiD4Fz7U2YQNDDohDV:-MtiD4Fz7U2YQNDDohDW:b-xqa8w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a0255d7dcb555475d54aa347aef8327a85a40c/pkg/kv/kvclient/kvstreamer/streamer.go#L395)):*
> ```Go
> 	defer func() {
> 		// We assume that the Streamer's mutex is held when Enqueue returns.
> 		s.mu.AssertHeld()
> ```

You're still paying the price of getting a bad behavior if there's a panic raised during the call to `s.budget.consume`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75078)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rharding6373)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MtiD4Fz7U2YQNDDohDV:-Mtj2SIL4FcqRIl2h9et:b-4jljec) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a0255d7dcb555475d54aa347aef8327a85a40c/pkg/kv/kvclient/kvstreamer/streamer.go#L395)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You're still paying the price of getting a bad behavior if there's a panic raised during the call to `s.budget.consume`.
</blockquote></details>

If a panic occurs in `s.budget.consume`, then CRDB node will crash, and this is the behavior we want. In such a scenario `mu.Unlock` will encounter a "run-time error if mu is not locked on entry to Unlock", and that seems ok, right? Or are you thinking about some `recover`s we have higher up the stack trying to crash cleanly?

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Thanks for the bug fixes! Just a few comments.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-:-Mtsapi8BfN5aftskMGI:bdzixr1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[-- commits, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MtsYaeT6qbzhKF17LHY):*
s/fixes/fixed
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MtsXdGH97pp4RRkRCKV:-MtsXdGIDl3uqtkQ4404:b-gkz57l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a0255d7dcb555475d54aa347aef8327a85a40c/pkg/kv/kvclient/kvstreamer/streamer.go#L396)):*
> ```Go
> 		// We assume that the Streamer's mutex is held when Enqueue returns.
> 		s.mu.AssertHeld()
> 		if retErr != nil && s.mu.err == nil {
> ```

If there's a `retErr` and already an err in `s.mu.err`, can we wrap the errors so we return both?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-Mts_8ZD-Jy3ucjjbg_E:-Mts_8ZD-Jy3ucjjbg_F:b-agq3ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/8085210689f312395ddb95f8525f5b8ef0af4dad/pkg/kv/kvclient/kvstreamer/streamer.go#L511)):*
> ```Go
> 	// totalReqsMemUsage.
> 	numRequestsToServe := len(s.mu.requestsToServe)
> 	s.mu.requestsToServe = s.mu.requestsToServe[:0]
> ```

I still can't believe that go lets you get away with resetting the slice length like this... Alternatively, could we put new requests in a local var until we get budget approval, then append them to `s.mu.requestsToServe` while we hold the mutex below?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 530 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-Mts_gVL3j0PiER9kZiZ:-Mts_gVL3j0PiER9kZi_:b-ikfsaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8085210689f312395ddb95f8525f5b8ef0af4dad/pkg/kv/kvclient/kvstreamer/streamer.go#L530)):*
> ```Go
> 
> 	if err != nil {
> 		return err
> ```

Are the requests in `s.mu.requestsToServe` lost forever now?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75078)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rharding6373)

___
*[-- commits, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MtsYaeT6qbzhKF17LHY):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

s/fixes/fixed
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MtsXdGH97pp4RRkRCKV:-MttSset0jVTWmNHEjn2:b-n8c6q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a0255d7dcb555475d54aa347aef8327a85a40c/pkg/kv/kvclient/kvstreamer/streamer.go#L396)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If there's a `retErr` and already an err in `s.mu.err`, can we wrap the errors so we return both?
</blockquote></details>

Hm, apparently this could be a bad idea if `s.mu.err` already has a retryable error (see https://github.com/cockroachdb/cockroach/issues/74892#issuecomment-1017859918), and `retErr` cannot be retryable, so it seems safer to  not wrap both errors.

Also, given the refactor in the second commit, `s.mu.err` must be `nil` here since no concurrent goroutines will do anything until `Enqueue` returns. Adjusted the second commit to assert that.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-Mts_8ZD-Jy3ucjjbg_E:-MttVlzNEheSEipz0HaA:b-dtxptm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8085210689f312395ddb95f8525f5b8ef0af4dad/pkg/kv/kvclient/kvstreamer/streamer.go#L511)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I still can't believe that go lets you get away with resetting the slice length like this... Alternatively, could we put new requests in a local var until we get budget approval, then append them to `s.mu.requestsToServe` while we hold the mutex below?
</blockquote></details>

Refactored to use a local variable. 
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 530 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-Mts_gVL3j0PiER9kZiZ:-MttTMtHAs_atcDcMt-V:bjrjiug) ([raw file](https://github.com/cockroachdb/cockroach/blob/8085210689f312395ddb95f8525f5b8ef0af4dad/pkg/kv/kvclient/kvstreamer/streamer.go#L530)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Are the requests in `s.mu.requestsToServe` lost forever now?
</blockquote></details>

Yes, but that's ok because we're returning an error to the client, and the whole query will result in an error too.

**Comment by yuzefovich** [comment]
Moved some code from the second commit into the first one. RFAL.

**Comment by yuzefovich** [comment]
@knz @rharding6373 PTAL

**Review by knz — COMMENTED** [review]
I'm sorry I still find this locking pattern too hard to analyze, so I don't feel confident enough to review this. Maybe ask someone who's more experienced with concurrency patterns. I just wish there was a way to organize the code so that we could see the invariants being preserved at every sub-block. Perhaps extracting bits and pieces in separate sub-functions, each of them with a "locked" suffix and a small(er) scope for the variables they can write to, would help? (I'm not sure)

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-:-MuGMt433QdgH6N1O51-:b-82xd1q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rharding6373, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 396 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MuGMZ3d-uiEl5VKcpuB:-MuGMZ3d-uiEl5VKcpuC:b-zibscj) ([raw file](https://github.com/cockroachdb/cockroach/blob/288bcd3717deecabdcdcaeff5fdd08205ae5b4e6/pkg/kv/kvclient/kvstreamer/streamer.go#L396)):*
> ```Go
> 	defer func() {
> 		// We assume that the Streamer's mutex is held when Enqueue returns.
> 		s.mu.AssertHeld()
> ```

you could write `defer s.mu.Unlock()` right away here, which would ensure that in the panic case the lock gets unlocked properly.

**Review by yuzefovich — COMMENTED** [review]
Good point. I refactored the code to extract a helper function where we're temporarily unlocking the Streamer's mutex. Now in `Enqueue` it is more clear that the Streamer's mutex is always being held.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-:-MuHsaLaEYTAkQJo_g5s:bmeyscm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rharding6373)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 396 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75078#-MuGMZ3d-uiEl5VKcpuB:-MuHqJ4wBNQw7VBCeS5S:bcwoy1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/288bcd3717deecabdcdcaeff5fdd08205ae5b4e6/pkg/kv/kvclient/kvstreamer/streamer.go#L396)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you could write `defer s.mu.Unlock()` right away here, which would ensure that in the panic case the lock gets unlocked properly.
</blockquote></details>

Done. `defer` within `defer`, nice :)

**Comment by yuzefovich** [comment]
I addressed all of the feedback on this PR and will merge it as part of #75127.

**Pull request closed without merging**
