### PR TITLE
sql: added inet function to support conversion to inet type

### LINKED ISSUE #82052: support `inet` function postgres
**Is your feature request related to a problem? Please describe.**
I'm trying to load maxmind database into cockroachdb.

Tutorial postgres at https://dev.maxmind.com/geoip/importing-databases/postgresql?lang=en, but because https://github.com/cockroachdb/cockroach/issues/18846 is not supported yet.

Then I'm looking at tutorial on mysql https://dev.maxmind.com/geoip/importing-databases/mysql?lang=en, only found out that a function akin to `inet_aton` in mysql is `inet` in postgres is also not supported yet (and I can't github issue for that).

**Describe the solution you'd like**
Either support `cidr` or `inet function` would work.

**Additional context**
```sql
# postgres
postgres=# select inet('::111');
 inet  
-------
 ::111
(1 row)
```

```sql
# cockroachdb
root@:26257/defaultdb> select inet('::111');         
ERROR: unknown function: inet()
SQLSTATE: 42883
```

---

Instructions:
- Add a builtin definition in pkg/sql/sem/builtins/builtins.go
- It can be implemented by calling `eval.PerformCast`
- Add logic tests in pkg/sql/logictest/testdata/logic_test/builtin_function

---

Jira issue: CRDB-16454

### PR DESCRIPTION
**Pull request by surahman**
Release note (sql change):
The inet function has been added to support the conversion of a supplied type to that of the inet
type family. If the conversion fails a SQL error will be output.

Closes #82052.

### CODE REVIEW

**Comment by surahman** [comment]
I am doubtful of whether the [SQL parser](https://github.com/cockroachdb/cockroach/tree/master/pkg/sql/parser) needs to be updated to handle this or if there is some automated generation process. Some of the builtins do not provide any additions to the SQL parser.

The function currently returns an error if the conversion fails. I was unable to find the documentation for the `inet` function in [PostreSQL](https://www.postgresql.org/docs/14/functions-net.html). [MySQL](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_inet-aton) handles a failed conversion by returning a `NULL`. How should this case be handled?

I have selected the input as `type.Any`. The issue did not specify a specific conversion type (sample contains `string`) so I went the route of trying to convert whatever type is provided. How should input type be defined?

**Comment by surahman** [comment]
Not sure about the benchmark failures there are no details in the CI logs. I think they might be spurious. Everything passes locally.

**Review by rafiss — CHANGES_REQUESTED** [review]
thank you for your contribution!

i left a few small comments, but this looks good

you will need to run `./dev generate docs` or `make buildshort` to make sure the generated docs are up to date

please address the comments, and amend your original commit with the changes. thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83668#-:-N6zXS61ET54ZTBODxzl:bofo4t4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @surahman)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83668#-N6zXNeA2bJiFFAlO3Fj):*
nit: please add newlines to the message so it's at most 100 characters wide
___
*[`pkg/sql/sem/builtins/builtins.go` line 1051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83668#-N6zWOBF0AQEZG2Em1GO:-N6zWOBG53C1ru1I23Oh:b-xh0wks) ([raw file](https://github.com/cockroachdb/cockroach/blob/c719bae56abf9d519b9d7f4ce54f0f591b2b7400/pkg/sql/sem/builtins/builtins.go#L1051)):*
> ```Go
> 	"inet": makeBuiltin(defProps(),
> 		tree.Overload{
> 			Types:      tree.ArgTypes{{"val", types.Any}},
> ```

to match postgres, we should make this only accept `types.String`. (PG actually accepts type `cstring` here, but CRDB doesn't have that)
___
*[`pkg/sql/sem/builtins/builtins.go` line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83668#-N6zW_J48pww7BMSGAlc:-N6zW_J5BNGbl2sdi6h_:b-lqno6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c719bae56abf9d519b9d7f4ce54f0f591b2b7400/pkg/sql/sem/builtins/builtins.go#L1057)):*
> ```Go
> 				if err != nil {
> 					return nil, pgerror.Newf(
> 						pgcode.InvalidParameterValue, "could not convert to INet: %s", args[0])
> ```

to match postgres, let's use `pgcode.InvalidTextRepresentation`

also, instead of `pgerror.Newf`, please use the original error
```
return nil, pgerror.WithCandidateCode(err, pgcode.InvalidTextRepresentation)
```
___
*[`pkg/sql/sem/builtins/builtins.go` line 1061 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83668#-N6zXDOtDDT7M2QM69y4:-N6zXDOtDDT7M2QM69y5:b-a29xir) ([raw file](https://github.com/cockroachdb/cockroach/blob/c719bae56abf9d519b9d7f4ce54f0f591b2b7400/pkg/sql/sem/builtins/builtins.go#L1061)):*
> ```Go
> 				return inet, nil
> 			},
> 			Info:       "If possible, converts input to that of type INet.",
> ```

please use "inet" instead of "INet"

**Comment by surahman** [comment]
Thank you @rafiss

**Comment by surahman** [comment]
Bazel CI failure appears to be unrelated.

```bash
[17:02:04][Run unit tests] === RUN   TestTenantLogic/3node-tenant/grant_on_all_sequences_in_schema
[17:02:04][Run unit tests] [17:02:02] setting distsql_workmem='34458B';
[17:02:04][Run unit tests] [17:02:02] setting distsql_workmem='34458B';
[17:02:04][Run unit tests] [17:02:03] rng seed: 1456840546540403413
[17:02:04][Run unit tests] 
[17:02:04][Run unit tests] -- Test timed out at 2022-07-15 17:02:03 UTC --
```

[grant_on_all_sequences_in_schema](https://github.com/cockroachdb/cockroach/blob/93658781963736591b60741e77867834719c3fd3/pkg/sql/logictest/testdata/logic_test/grant_on_all_sequences_in_schema)

**Review by rafiss — APPROVED** [review]
thanks for your work! this looks good to me

bors r+

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83668#-:-N7M9ntn960XUJfy7SW3:bxwcagn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @surahman)

**Pull request merged**
