### PR TITLE
docs: update SQL section of Life of a Query

### PR DESCRIPTION
**Pull request by erikgrinaker**
[Rendered](https://github.com/cockroachdb/cockroach/blob/706eadfe7833662afbf116d9425909e83a1eef21/docs/tech-notes/life_of_a_query.md)

This patch rewrites most of the SQL sections of Life of a Query to
update them with cost-based optimization, distributed SQL processing,
and vectorized execution.

A final pass over the entire document will be done later to tighten it
up and polish it.

Touches #65196.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-:-MbbQ8XhExd5e4ckUYcV:b-vkvjo7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @rytaft)

**Review by aliher1911 — APPROVED** [review]
:lgtm:
This so good! Can't wait for KV part.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-:-MbbXSpCEw5X0OEDA-SO:b-2gstn6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

**Review by erikgrinaker — COMMENTED** [review]
>This so good! Can't wait for KV part.

Thanks! It'll be a short wait since I updated KV last week: #65883 :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-:-Mbb_kOg0Q9XxE41mSn3:b7c4tgo)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

**Review by mgartner — APPROVED** [review]
Thanks for updating this! The Logical Planning and Optimization section :lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-:-MbboFyr0LUhQk7f2H6n:b9vle1q)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
This is really great! Thanks so much for taking the time to get all the code pointers, too! I worry they will quickly become stale, but I think it's still better to have them than not.

@yuzefovich might have some feedback about the DistSQL planning/vectorized execution sections, but he's out of office today. Not sure if he'll have time to look later this week...

Just left a few minor comments, but overall :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-:-Mbfpp001a1NFnIYpH0r:bhz1fgy)* status: :shipit: complete! 4 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[docs/tech-notes/life_of_a_query.md, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-MbbpjOM1f5rRcfwhoQq:-MbbpjOM1f5rRcfwhoQr:bqupzo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L61)):*
> ```Markdown
> broadly goes through the following stages:
> 
> Parsing → Logical Planning → Optimization → Physical Planning → Vectorized Execution
> ```

nit: Logical Planning and Optimization are really one step.  Also not everything is vectorized yet. I'd change this to something like:
Parsing → Logical Planning & Optimization → Physical Planning → Execution
___
*[docs/tech-notes/life_of_a_query.md, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-Mbbsh2y4dWKvXaH68xb:-MbbsImO5fHWa-E2gvVt:bwk3ykt) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L239)):*
> ```Markdown
> 
> Each node in the plan is a relational operator, and results flow upwards from
> one node to the next. We can see that the planner has decided to do a full table
> ```

nit: I'd change the word "planner" to "optimizer" in most places here, since `planner` is a specific struct in the `sql` package that has a bunch of per-query state but defers most actual planning to the optimizer, which is called from the `planner`'s `optPlanningCtx`. Although "planner" is technically correct, I think "optimizer" is used more frequently internally.
___
*[docs/tech-notes/life_of_a_query.md, line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-Mbc6Fqm5CJq_SXEQQE8:-Mbc6Fqm5CJq_SXEQQE9:bgfhwdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L362)):*
> ```Markdown
> [`norm.Factory`](https://github.com/cockroachdb/cockroach/blob/5ffe3c531385bbf52e5a414addbc489279f3d535/pkg/sql/opt/norm/factory.go#L64)
> that builds normalized memo expressions. We've seen this factory before:
> the `opt.Builder` [used it](https://github.com/cockroachdb/cockroach/blob/2e5cce372e402faa2155c6f6e85410a9c7bdd238/pkg/sql/opt/optbuilder/select.go#L543)
> ```

nit: `opt.Builder` -> `optbuilder.Builder`
___
*[docs/tech-notes/life_of_a_query.md, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-Mbc61eD2k7SgikqKcEa:-Mbc61eD2k7SgikqKcEb:bkx1bo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L363)):*
> ```Markdown
> that builds normalized memo expressions. We've seen this factory before:
> the `opt.Builder` [used it](https://github.com/cockroachdb/cockroach/blob/2e5cce372e402faa2155c6f6e85410a9c7bdd238/pkg/sql/opt/optbuilder/select.go#L543)
> to construct a normalized `ScanExpr` node for a `FROM` clause table name.
> ```

You could make this a bit more explicit and say here that the `ConstructXXX` functions called by the `optbuilder.Builder` contain the generated go code from the normalization rules, and therefore the un-normalized memo is never actually materialized. The optbuilder might think it's constructing one thing, but if a normalization rule fires, it might actually construct something else. Only the fully normalized memo is ever materialized.
___
*[docs/tech-notes/life_of_a_query.md, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-MbffsCt7MDzChfiJI3D:-MbffsCt7MDzChfiJI3E:b7mnslj) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L417)):*
> ```Markdown
> sending it all across the network first.
> 
> This is done by the DistSQL engine which operates similarly to
> ```

You might want to mention somewhere here that not all physical plans are distributed, even if there is remote data that needs to be fetched. [`getPlanDistribution`](https://github.com/cockroachdb/cockroach/blob/5a92a58a6239d05cf48465e704d3a40535bc8684/pkg/sql/exec_util.go#L1127) checks if the plan should be distributed or not, and if not, the entire plan is executed on the gateway node (although it still uses the same DistSQL processors). In this case, the processors will use the kv API to fetch remote data.
___
*[docs/tech-notes/life_of_a_query.md, line 509 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-MbfhZL-6nguqclBC5EL:-MbfhZL0BWESyHd0SG98:b89bfr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L509)):*
> ```Markdown
> [`scanNode`](https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/distsql_physical_planner.go#L2785-L2786)
> for the `companies` table, which corresponds to a table scan (originally a
> `opt.ScanExpr` memo expression). This
> ```

nit: `opt.ScanExpr` -> `memo.ScanExpr`
___
*[docs/tech-notes/life_of_a_query.md, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-Mbfhw1v9qpTXu-PlXml:-Mbfhw1v9qpTXu-PlXmm:bhx5hsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L545)):*
> ```Markdown
> The final plan node is the `sortNode`, which simply
> [attaches](https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/distsql_physical_planner.go#L1445)
> a local [`SortedSpec`](https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/execinfrapb/processors_sql.proto#L412)
> ```

nit: `SortedSpec` -> `SorterSpec`
___
*[docs/tech-notes/life_of_a_query.md, line 637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-MbfoGYV6VxLP4fJ_OgC:-MbfoGYV6VxLP4fJ_OgD:bz2lpdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L637)):*
> ```Markdown
> [way back in `connExecutor.execWithDistSQLEngine()`](https://github.com/cockroachdb/cockroach/blob/fc67a0c9202af348e919afc1e1f70acc9a83b300/pkg/sql/conn_executor_exec.go#L1005).
> This triggers a cascade of recursive `Next()` calls on the child operators all
> the way do the flow leaves. Using the example from earlier (see diagram):
> ```

nit: do -> down to?
___
*[docs/tech-notes/life_of_a_query.md, line 693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-Mbfp9604r74lWPXRPsa:-Mbfp9604r74lWPXRPsb:bx3v8y4) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L693)):*
> ```Markdown
> [decoding](https://github.com/cockroachdb/cockroach/blob/5c00812b5d495749133beb1e217639e03fd02246/pkg/sql/row/kv_fetcher.go#L115), this time of MVCC metadata, and
> delegates to [`txnKVFetcher`](https://github.com/cockroachdb/cockroach/blob/d6d394bf5c4974d79e21efe8c03f65ebf0bc10fa/pkg/sql/row/kv_batch_fetcher.go#L68)
> where the actual fething happens.
> ```

nit: fething -> fetching

**Review by erikgrinaker — COMMENTED** [review]
Thanks @rytaft, appreciate the input!

The code pointers will definitely get stale, but I think they're the most valuable part of the document. The old pointers were several years out of date, but when I was onboarding they were really the only connection I had between handwavey architecture descriptions and the actual code, which made this the most useful onboarding material by far (to me at least). It can be tough for a newcomer to navigate a codebase of this size without any concrete points of reference.

I'm doing a final cleanup pass on Friday (need a break first), if @yuzefovich has any input before then he's welcome to get in touch. And we can always improve this later as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-:-Mbgr3w64RRmN9m4YnC4:bs3vr0v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 4 stale) (waiting on @aliher1911, @mgartner, and @rytaft)

___
*[docs/tech-notes/life_of_a_query.md, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-Mbc61eD2k7SgikqKcEa:-Mbgm5jN5U1A6iFpaIqg:blolpud) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L363)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You could make this a bit more explicit and say here that the `ConstructXXX` functions called by the `optbuilder.Builder` contain the generated go code from the normalization rules, and therefore the un-normalized memo is never actually materialized. The optbuilder might think it's constructing one thing, but if a normalization rule fires, it might actually construct something else. Only the fully normalized memo is ever materialized.
</blockquote></details>

Good idea, added a note on this.
___
*[docs/tech-notes/life_of_a_query.md, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66120#-MbffsCt7MDzChfiJI3D:-MbgphsT9r5zGGyZntz8:biduyhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/717b5fe85ec40ee8ae58b38f900b3e9ce51f253c/docs/tech-notes/life_of_a_query.md#L417)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You might want to mention somewhere here that not all physical plans are distributed, even if there is remote data that needs to be fetched. [`getPlanDistribution`](https://github.com/cockroachdb/cockroach/blob/5a92a58a6239d05cf48465e704d3a40535bc8684/pkg/sql/exec_util.go#L1127) checks if the plan should be distributed or not, and if not, the entire plan is executed on the gateway node (although it still uses the same DistSQL processors). In this case, the processors will use the kv API to fetch remote data.
</blockquote></details>

Good idea, added a note

**Comment by erikgrinaker** [comment]
bors r=rytaft,mgartner,andreimatei,aliher1911

**Pull request merged**
