### PR TITLE
kv: consolidate cancellation in TxnCoordSender

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8313)

### CODE REVIEW

**Comment by d4l3k** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-:-KOHLDfpSg1jrtBl-p1V:1417088721)*

**Comment by bdarnell** [comment]
What problems does this solve? It's not clear to me that this is sufficient improvement to warrant this much change to such subtle code. 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-KOINmrSJrQPtqGO_HXA:-KOINmrSJrQPtqGO_HXB:299638988) ([raw file](https://github.com/cockroachdb/cockroach/blob/96cfa1cf902be7242e70e73f00dd13c8fd2daacb/kv/txn_coord_sender.go#L80)):*
> ```Go
> 	timeoutDuration time.Duration
> 
> 	ctx    context.Context
> ```

The context docs warn against putting contexts in structs. These fields need comments explaining when this context is used (versus one that could be passed in to the method). Why isn't the context passed into `heartbeatLoop` in the argument?

This field isn't initialized until fairly late. Following #8306, should we fill it in at creation time with context.Background so we never have a nil context? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-:-KOIPV2xVc3K8SXwNjkA:1951337772)*

**Comment by tamird** [comment]
It makes the code easier to reason about, nothing more. I was surprised to discover a number of call sites that do the same thing in different ways while making this change. For instance, the old version called `tryAsyncAbort` in three different places.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-KOINmrSJrQPtqGO_HXA:-KOIQL5AXbPpRpP7q3ru:-1223186759) ([raw file](https://github.com/cockroachdb/cockroach/blob/96cfa1cf902be7242e70e73f00dd13c8fd2daacb/kv/txn_coord_sender.go#L80)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The context docs warn against putting contexts in structs. These fields need comments explaining when this context is used (versus one that could be passed in to the method). Why isn't the context passed into `heartbeatLoop` in the argument?
> 
> This field isn't initialized until fairly late. Following #8306, should we fill it in at creation time with context.Background so we never have a nil context? 
> 
> 
</details>
They do? And yet net.Request has a context in Go 1.7.

The field is initialized immediately after creation.

The context isn't passed into `heartbeatLoop ` because `cleanupTxnLocked` wants to cancel it, and it'd be odd to have a cancel function without its context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-:-KOIQxn__kwCCxntQLnh:15986347)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-KOINmrSJrQPtqGO_HXA:-KOIRQeRJYSP_PnGJbqs:885900209) ([raw file](https://github.com/cockroachdb/cockroach/blob/96cfa1cf902be7242e70e73f00dd13c8fd2daacb/kv/txn_coord_sender.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> They do? And yet net.Request has a context in Go 1.7.
> 
> The field is initialized immediately after creation.
> 
> The context isn't passed into `heartbeatLoop ` because `cleanupTxnLocked` wants to cancel it, and it'd be odd to have a cancel function without its context.
</details>
net/http.Request, not net.Request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313)*

**Comment by petermattis** [comment]
I think we should be moving towards using contexts for cancellation, but I'm anxious about making this change without a pressing reason while @tschottdorf is on vacation. Can we put it on hold until he gets back? Alternately, find a scenario in which the old code is broken. 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-:-KOKks8LU_jpTb_fM--r:819043111)*

**Comment by bdarnell** [comment]
Yeah, I'd rather not take the time to page this code back in and give this a proper review unless there's a more compelling reason. 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-KOINmrSJrQPtqGO_HXA:-KOQiGscgg9m63JGclUg:bd31m7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a150d7bbad9f67a7dee9efc0aaca409a1404ee28/kv/txn_coord_sender.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> net/http.Request, not net.Request.
</details>
Yes, the [docs](https://github.com/golang/go/blob/10316757cec3c2744ea61088e0fc905cfeb28fb2/src/context/context.go#L29) say you shouldn't put Contexts in a struct. The addition of Context to net/http.Request was considered to be the lesser evil for compatibility purposes (and [bradfitz](https://groups.google.com/d/msg/golang-dev/cQs1z9LrJDU/Gg-PyManCgAJ) suggested softening the rule although that didn't make it into the docs)

I don't see what's odd about having a cancel function without its context; it seems better to me to pass around an opaque cancellation function than to also store a context that should not be used. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8313#-:-KOQjaBcPiWViY29qe07:byfbl9k)*

**Pull request closed without merging**
