### PR TITLE
sql: make the generator built-ins restartable

### PR DESCRIPTION
**Pull request by knz**
Needed for  #20511.

This makes it possible to "restart" a generator built-in.

This patch also reduces pressure on the garbage collector by
pre-allocating Datum arrays.

Release note: None

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm: with a few comments

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26229#-LDlPNSL2AXYLmOZ8U5J:-LDlPNSMARAXxdyxI9yr:b-9opfpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/89690e007f3f4bab973a107754f471d140d5373f/pkg/sql/logictest/testdata/logic_test/json_builtins#L635)):*
> ```
> {"a": "1", "b": "2", "c": "3", "d e f": "a b c"}
> 
> query error pq: json_each\(\): cannot deconstruct an array as an object
> ```

Is this error change related?  I do agree that it looks better but perhaps add a comment in the commit message.

---

*[pkg/sql/sem/builtins/generator_builtins.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26229#-LDlPlIT2b-60urBZfB1:-LDlPlIT2b-60urBZfB2:b8ptafq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f61cae32b84c52818fcb7464ae31fdc330aedbae/pkg/sql/sem/builtins/generator_builtins.go#L380)):*
> ```Go
> 	s.nextOK = true
> 	s.start = s.origStart
> 	s.value = s.start
> ```

nit: This would be a tiny bit clearer if you set both to s.origStart instead of passing it through.

---

*[pkg/sql/sem/builtins/generator_builtins.go, line 573 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26229#-LDlQu1d5p8exc09VVdm:-LDlQu1d5p8exc09VVdn:b-1ezmbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f61cae32b84c52818fcb7464ae31fdc330aedbae/pkg/sql/sem/builtins/generator_builtins.go#L573)):*
> ```Go
> 	// Generate Subscript's indexes are 1 based.
> 	*s.buf[0].(*tree.DInt) = tree.DInt(s.avg.nextIndex + 1)
> 	return s.buf[:]
> ```

Is there a need to return a new slice instead of just s.buf?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26229#-:-LDlSAFo3K56CWOERVTx:b-afkoyi)*

**Comment by jordanlewis** [comment]
LGTM

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26229)*

**Comment by knz** [comment]
Change and tests embedded in #26223.

**Pull request closed without merging**
