### PR TITLE
ui: add unit tests to linegraph component for coverage

### PR DESCRIPTION
**Pull request by Santamaura**
Previously, there were no unit tests for the linegraph component.
The unit tests are needed because it may have averted a prod impact and could avert future ones.
Added unit tests for linegraph component.

Release note ui: add unit tests to linegraph component

Should resolve this github [issue](https://github.com/cockroachdb/cockroach/issues/67134)

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @nathanstilwell, and @Santamaura)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeOVV9K2AD9zejevFYz:-MeOVV9K2AD9zejevFZ-:bvq1k4z) (no related file):*
fyi, build fails with following error:
```
lint_test.go:263: did not find expected license header (ccl=false) in ui/src/views/cluster/components/linegraph/linegraph.spec.tsx
```
to check it locally, you can run `make lintshort` target

---
___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeOTXsVBsrJob6ThRo-:-MeOTXsX1nfL_XDJKvtA:bcbd4tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5037e805032e91f5fa937662c34f09aba703442/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L359)):*
> ```XML
> // uPlot object.
> export class LineGraph extends React.Component<LineGraphProps, {}> {
>   props: any;
> ```

what is the reason of redefining type of `props` from `LineGraphProps` to `any`?

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, and @nathanstilwell)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeOVV9K2AD9zejevFYz:-MeQSbKO77VVs73nDlCY:b-y82xpg) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

fyi, build fails with following error:
```
lint_test.go:263: did not find expected license header (ccl=false) in ui/src/views/cluster/components/linegraph/linegraph.spec.tsx
```
to check it locally, you can run `make lintshort` target
</blockquote></details>

Locally the errors don't really indicate much and I'm not sure why the license header would be false, is there something specific I need to add to the test file?

---
___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeOTXsVBsrJob6ThRo-:-MeQSoDF9Cvr4V1MmtEZ:blwa5el) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5037e805032e91f5fa937662c34f09aba703442/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L359)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

what is the reason of redefining type of `props` from `LineGraphProps` to `any`?
</blockquote></details>

Was added early on to pass some lint error that no longer shows up, I removed it.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, and @nathanstilwell)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeOVV9K2AD9zejevFYz:-MeQaTgvEhuG3nE7pnxX:b-faulo2) (no related file):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Locally the errors don't really indicate much and I'm not sure why the license header would be false, is there something specific I need to add to the test file?
</blockquote></details>

Sorry disregard, was an unrelated issue with outdated make. I added the license in.

---

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, @nathanstilwell, and @Santamaura)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeYOLLM6iGXi9UY-8uv:-MeYOLLM6iGXi9UY-8uw:b-zb5ck7) (no related file):*
LGTM in general, and just curious if you could add one more test that covers this specific case with empty data https://github.com/cockroachdb/cockroach/pull/66897 ?

---

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, and @nathanstilwell)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeYOLLM6iGXi9UY-8uv:-Mf4-daJAzQT_E5JALD8:b3dxidt) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

LGTM in general, and just curious if you could add one more test that covers this specific case with empty data https://github.com/cockroachdb/cockroach/pull/66897 ?
</blockquote></details>

I just ran the tests w/ debug to check, in the 3rd test the options that return only have 1 item in the series so it would hit that logic and be covered

---

**Review by koorosh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, and @nathanstilwell)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67431#-MeYOLLM6iGXi9UY-8uv:-Mf7VJuN3ZROea3u16ld:b-uek1i3) (no related file):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

I just ran the tests w/ debug to check, in the 3rd test the options that return only have 1 item in the series so it would hit that logic and be covered
</blockquote></details>

Great 🎉

---

**Comment by Santamaura** [comment]
blathers backport 21.1 20.2

**Pull request merged**
