### PR TITLE
raft: introduce and make use of SupportTracker 

### LINKED ISSUE #125264: raft: add SupportTracker
**Describe the problem**

Part of https://github.com/cockroachdb/cockroach/issues/123847

As part of leader leases, leaders will fortify their leadership term by requesting fortification support from followers. The leader should track this support in a `SupportTracker` struct, similar to the `ProgressTracker` struct that tracks progress today.

Jira issue: CRDB-39355

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
This patch adds a new type of tracker called a SupportTracker. Then,
leaders make use of this tracker to record fortification support from
followers on successful MsgFortifyLeaderResp messages.

Closes https://github.com/cockroachdb/cockroach/issues/125264

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130025)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ydq7A2qO9QNI-ptNf:-O5ydq7A2qO9QNI-ptNg:b-i8aq89) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/raft.go#L454)):*
> ```Go
> 
> 	r.electionTracker = tracker.MakeElectionTracker(&r.config)
> 	r.supportTracker = tracker.MakeSupportTracker(&r.config, r.storeLiveness)
> ```

Do we need to reset some or all of this tracker in some of the same places we reset `r.electionTracker`? It's only needed in `raft.reset`, because a replica cannot transition from a `Leader` to a `PreCandidate`.

A `ResetSupport` method would probably only touch the `support` map, while leaving `leaderMaxSupported` alone. That's because we still want access to `leaderMaxSupported` after a leader step-down.
___
*[`pkg/raft/raft.go` line 713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ybhVN25MuDMxv27jo:-O5ybhVN25MuDMxv27jp:b-md6f71) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/raft.go#L713)):*
> ```Go
> 		if live {
> 			r.leadEpoch = epoch
> 			r.supportTracker.RecordSupport(r.id, epoch)
> ```

Is it valid to record support from the leader here, before the `LeadEpoch` has been durably persisted? I was thinking that we instead wanted a self-MsgFortifyLeaderResp ack which is only delivered back the leader after a durable write, analagous to how we handle the situation in `raft.appendEntry`.
___
*[`pkg/raft/raft.go` line 2072 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ycJlH-tTAl77m-Bn7:-O5ycJlH-tTAl77m-Bn8:b-usf6s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/raft.go#L2072)):*
> ```Go
> 	assertTrue(r.state == StateLeader, "only leaders should be handling fortification responses")
> 	if m.Reject {
> 		return // couldn't successfully fortify follower; we'll try again later
> ```

Are there any code references we can point to? Also, can we put a few words into why a follower might reject a `MsgFortifyLeader` request?
___
*[`pkg/raft/rawnode.go` line 499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yd2M9EguKweHn5xJs:-O5yd2M9EguKweHn5xJt:b6ar6j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/rawnode.go#L499)):*
> ```Go
> // leader support information.
> func (rn *RawNode) LeadSupportStatus() LeadSupportStatus {
> 	return getLeadSupportStatus(rn.raft)
> ```

Does it make sense to address the two `TODO(arul): populate this field` in `status.go` at this point? Will that give us more test coverage for free?
___
*[`pkg/raft/rawnode.go` line 502 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yd7ws-kcWOxj7mp0l:-O5yd7ws-kcWOxj7mp0m:bcgy0gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/rawnode.go#L502)):*
> ```Go
> }
> 
> // TODO(nvanbenschoten): remove this one the method is used.
> ```

Mind addressing this TODO for me? The method is now used.
___
*[`pkg/raft/rafttest/interaction_env_handler_raftstate.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ydXPXD8ryAK07l94O:-O5ydXPXD8ryAK07l94P:b-aw1p09) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/rafttest/interaction_env_handler_raftstate.go#L22)):*
> ```Go
> import (
> 	"fmt"
> 	"github.com/cockroachdb/datadriven"
> ```

nit: did gofmt run on this file? The imports look out of place.
___
*[`pkg/raft/rafttest/interaction_env_handler_raftstate.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ydaDI72PaAMJKCLyD:-O5ydaDI72PaAMJKCLyE:bgqa1ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/rafttest/interaction_env_handler_raftstate.go#L57)):*
> ```Go
> }
> 
> // handleRaftState pretty-prints the support map being tracked by a raft peer.
> ```

This comment looks off.
___
*[`pkg/raft/tracker/supporttracker.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ycVJR6eO_3U-lRdXj:-O5ycVJR6eO_3U-lRdXk:b-cbbrsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L22)):*
> ```Go
> )
> 
> type SupportTracker struct {
> ```

Let's give this struct a comment describing what the tracker is tracking.
___
*[`pkg/raft/tracker/supporttracker.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yeZBE2vucp7NmTJqt:-O5yeZBF5ICU5ankH_Ag:b-46rynu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L44)):*
> ```Go
> 	st := SupportTracker{
> 		config:        config,
> 		support:       map[pb.PeerID]pb.Epoch{},
> ```

small nit: move this one line down to match field order.
___
*[`pkg/raft/tracker/supporttracker.go` line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yelzT3FgmstfvT12J:-O5yelzT3FgmstfvT12K:b-h2n1de) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L64)):*
> ```Go
> 		return hlc.Timestamp{}
> 	}
> 	supportExpMap := make(map[pb.PeerID]hlc.Timestamp)
> ```

Let's leave a TODO to try to avoid this map allocation. We'll be calling `LeadSupportUntil` on relatively hot paths, so avoiding it will be nice.
___
*[`pkg/raft/tracker/supporttracker.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ycf3d5x9DdHwTzUSo:-O5ycf3d5x9DdHwTzUSp:b-wh0rrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L78)):*
> ```Go
> 	supportUntil := st.config.Voters.LeadSupportExpiration(supportExpMap)
> 
> 	st.leaderMaxSupported.Forward(supportUntil)
> ```

As written, this is going to cause issues with `RawNode.Status()` and variants, because those methods are assumed to be read-only and only require a `RWMutex` held in read-mode. Do we want to put this behind a fine-grained `Mutex`? That could play well with the suggestion to recycle a `map[pb.PeerID]hlc.Timestamp]`.
___
*[`pkg/raft/tracker/supporttracker.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yfsEf4_niPEp6dblH:-O5yfsEf4_niPEp6dblI:bavc8y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L88)):*
> ```Go
> 	var buf strings.Builder
> 	for id, epoch := range st.support {
> 		buf.WriteString(fmt.Sprintf("%d : %d\n", id, epoch))
> ```

nit: `fmt.Fprintf` to avoid the intermediate allocation and memcpy.
___
*[`pkg/raft/tracker/supporttracker_test.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ygB-601o5Sga15ogm:-O5ygB-601o5Sga15ogn:b-f9sndw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker_test.go#L21)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> 	"github.com/stretchr/testify/require"
> 	"testing"
> ```

Same question about gofmt/crlfmt.
___
*[`pkg/raft/tracker/supporttracker_test.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ygS2YCg83BCq0Jp33:-O5ygS2YCg83BCq0Jp34:bamt2mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker_test.go#L45)):*
> ```Go
> 		ids           []pb.PeerID
> 		storeLiveness raftstoreliveness.StoreLiveness
> 		run           func(t *testing.T, supportTracker SupportTracker)
> ```

It's fairly non-standard to have a pseudo-table driven test where the actually test logic and assertions are in an opaque `run` function. Any reason not to make this look more normal, with a map of `(id, epoch)` support pairs and an `expLeadSupportUntil` timestamp?

**Review by arulajmani — COMMENTED** [review]
Thanks for the review. Made some of the changes we discussed on call yesterday; RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-:-O67aINVDnUuGI7v2YvS:b4icn4m)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ydq7A2qO9QNI-ptNf:-O67_gbSCCscwlm-vuAu:b-yqflzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/raft.go#L454)):*
> That's because we still want access to `leaderMaxSupported` after a leader step-down.

+1. I wrote myself a TODO as a reminder. 
___
*[`pkg/raft/raft.go` line 713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ybhVN25MuDMxv27jo:-O67Y9THDuYOGva3faGA:b14p3gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/raft.go#L713)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it valid to record support from the leader here, before the `LeadEpoch` has been durably persisted? I was thinking that we instead wanted a self-MsgFortifyLeaderResp ack which is only delivered back the leader after a durable write, analagous to how we handle the situation in `raft.appendEntry`.
</blockquote></details>

Done. Thanks for catching.
___
*[`pkg/raft/raft.go` line 2072 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ycJlH-tTAl77m-Bn7:-O67GlJx3KjG-0vXH8aW:b-g46ts6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/raft.go#L2072)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are there any code references we can point to? Also, can we put a few words into why a follower might reject a `MsgFortifyLeader` request?
</blockquote></details>

Done, though the code reference is partially true, given we've not landed re-fortification yet.
___
*[`pkg/raft/rawnode.go` line 499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yd2M9EguKweHn5xJs:-O67JV9X-2PHoGBUdDvz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/rawnode.go#L499)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does it make sense to address the two `TODO(arul): populate this field` in `status.go` at this point? Will that give us more test coverage for free?
</blockquote></details>

Done.
___
*[`pkg/raft/rawnode.go` line 502 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yd7ws-kcWOxj7mp0l:-O67J4Nz8rq-pCQKQSYJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/rawnode.go#L502)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mind addressing this TODO for me? The method is now used.
</blockquote></details>

Done.
___
*[`pkg/raft/rafttest/interaction_env_handler_raftstate.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ydXPXD8ryAK07l94O:-O67GrpI4HmD8TPqimo4:b-70mwbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/rafttest/interaction_env_handler_raftstate.go#L22)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: did gofmt run on this file? The imports look out of place.
</blockquote></details>

Seems like my `crlfmt` watcher just went away. Fixed. 
___
*[`pkg/raft/tracker/supporttracker.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ycVJR6eO_3U-lRdXj:-O67Iypz9aTpGyVCXsHP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L22)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's give this struct a comment describing what the tracker is tracking.
</blockquote></details>

Done.
___
*[`pkg/raft/tracker/supporttracker.go` line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5yelzT3FgmstfvT12J:-O67HztmEWaw9nlddXrE:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's leave a TODO to try to avoid this map allocation. We'll be calling `LeadSupportUntil` on relatively hot paths, so avoiding it will be nice.
</blockquote></details>

Good point, done.
___
*[`pkg/raft/tracker/supporttracker.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ycf3d5x9DdHwTzUSo:-O67I0KZ0calbZN3xRTT:b-rjrsru) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

As written, this is going to cause issues with `RawNode.Status()` and variants, because those methods are assumed to be read-only and only require a `RWMutex` held in read-mode. Do we want to put this behind a fine-grained `Mutex`? That could play well with the suggestion to recycle a `map[pb.PeerID]hlc.Timestamp]`.
</blockquote></details>

We spoke about this offline. I hadn't intended to copy `leadMaxSupported` from the prototype in this PR; instead, I wanna introduce it later, when we need it. I've taken it out for now. 

Separately, fine grained mutex sounds good for when we get here.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-:-O67hbhd1cO-c1O7kTX8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/tracker/supporttracker.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ycf3d5x9DdHwTzUSo:-O67h1Wm1jl7QyQoxh1Z:brnw2zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker.go#L78)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We spoke about this offline. I hadn't intended to copy `leadMaxSupported` from the prototype in this PR; instead, I wanna introduce it later, when we need it. I've taken it out for now. 

Separately, fine grained mutex sounds good for when we get here.
</blockquote></details>

We also discussed potentially not needing a mutex if we don't pass all lead support timestamps through `leadMaxSupported`, but instead introduce a `leadMaxSupportedAtLastConfigChange` (or something like that) and then always compute the max on-demand. That means that `LeadSupportUntil` becomes read-only again.
___
*[`pkg/raft/tracker/supporttracker_test.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ygB-601o5Sga15ogm:-O67hTSa8dF_8s00Mq34:b-c2bpn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker_test.go#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same question about gofmt/crlfmt.
</blockquote></details>

I think this still need to be addressed. But whatever CI says goes.
___
*[`pkg/raft/tracker/supporttracker_test.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ygS2YCg83BCq0Jp33:-O67hXeg-sUVzMHY2ytm:bfj4l5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker_test.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's fairly non-standard to have a pseudo-table driven test where the actually test logic and assertions are in an opaque `run` function. Any reason not to make this look more normal, with a map of `(id, epoch)` support pairs and an `expLeadSupportUntil` timestamp?
</blockquote></details>

Any thoughts on this? It can also be addressed (if we want to) in a separate PR.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130025)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/tracker/supporttracker_test.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ygB-601o5Sga15ogm:-O67nMFK91DAFazHI5K9:b-esrxnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker_test.go#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think this still need to be addressed. But whatever CI says goes.
</blockquote></details>

Na, I think I just missed addressing comments on this file. My bad, fixed. 
___
*[`pkg/raft/tracker/supporttracker_test.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-O5ygS2YCg83BCq0Jp33:-O67nRfF4NIpJToC-20f:bzbpmnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4750f06ba2d7993dc60be5cdd563ba604eefb952/pkg/raft/tracker/supporttracker_test.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any thoughts on this? It can also be addressed (if we want to) in a separate PR.
</blockquote></details>

Sorry I missed this. I was misremembering how `TestProtectedTimestampsPreventGC` was written. I've switched to a `setup`/`expTS` approach instead.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130025#-:-O67qKPa-Ejy6OG0ccr-:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
TFTR!

bors r=nvanbenschoten

**Comment by arulajmani** [comment]
A couple of tests needed updating because we now send a self addressed `MsgFortifyLeaderResp`.

bors r=nvanbenschoten

**Pull request merged**
