### PR TITLE
opt: Add initial version of the explorer

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR has two commits:
1. Add explorer, along with the first exploration rule.
2. Add execution support for index scans.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: 

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/metadata.go, line 119 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8PJy-wxdS_49jWU4LA:-L8PJy-wxdS_49jWU4LB:bsqq2ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/metadata.go#L119)):*
> ```Go
> // ColumnOrdinal returns the ordinal position of the column in its table.
> func (md *Metadata) ColumnOrdinal(tabID TableID, colID ColumnID) int {
> 	return int(colID) - int(tabID)
> ```

[nit] This formula looks rather strange, I'd add a comment reminding the reader that the table id matches the column id of its first column

---

*[pkg/sql/opt/xform/explorer.go, line 118 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8SDD8IAp6tWoRIDZdW:-L8SDD8IAp6tWoRIDZdX:b-1y0hd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L118)):*
> ```Go
> //           ... explore (e1, e2, e3) combo ...
> //
> func (e *explorer) exploreGroup(group memo.GroupID) *exploreState {
> ```

[nit] does this need to return the entire `*exploreState` or is an `fullyExplored bool` sufficient?

---

*[pkg/sql/opt/xform/explorer.go, line 162 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8PI-PZzx3-5PLs7H-z:-L8PI-PZzx3-5PLs7H0-:b-h7fj63) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L162)):*
> ```Go
> 
> // TODO(andyk): This dispatcher method needs to be generated by Optgen.
> func (e *explorer) exploreExpr(state *exploreState, eid memo.ExprID) (fullyExplored bool) {
> ```

[nit] A pointer to where what "fullyExplored" means for an expression (maybe `markExprAsFullyExplored`) would help here.

---

*[pkg/sql/opt/xform/explorer.go, line 179 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8PJ2lBCSUR1lSsQ4u0:-L8PJ2lBCSUR1lSsQ4u1:b-v1wbt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L179)):*
> ```Go
> 	//	$scan:(Scan & (IsPrimaryScan $scan)) => (ImplementIndexScan $scan)
> 	{
> 		// No sub-patterns, so this rule only needs to be matched once.
> ```

I don't quite understand "this rule only needs to be matched once" means (and what the consequence on this code is). Is it once per expression (as opposed to rules that depend on some of the children of the expression)?

---

*[pkg/sql/opt/xform/explorer.go, line 226 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8PJW7oIvgdXCXYnjdN:-L8PJW7oIvgdXCXYnjdO:b-heic49) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L226)):*
> ```Go
> 
> 		// Ensure that the index includes the set of needed columns (def.Cols).
> 		found := true
> ```

[nit] this block could be a helper function on ScanOpDef (I'm sure we'll need it in more than one place). BTW this could build a FastIntSet for the index columns and do `def.Cols.SubsetOf(..)` instead of repeated search.

---

*[pkg/sql/opt/xform/explorer.go, line 256 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8SBfTS0bKt-UCaQosw:-L8SBfTS0bKt-UCaQosx:b-xx58tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L256)):*
> ```Go
> 	// start and end specify which expressions need to be explored in the
> 	// current pass. Expressions before start have been partly explored during
> 	// previous passes. Expressions after end are new expression added during
> ```

expressions.

Isn't `end` exclusive? (in which case it should be "expressions starting with <end> are new expressions`)
In any case, we should mention explicitly here whether `end` is inclusive or exclusive

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 109 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8SDSkOAWB-WScs9Q9E:-L8SDSkOAWB-WScs9Q9F:bgtg7db) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/physical_props_factory.go#L109)):*
> ```Go
> 		// The index can provide the required ordering in either of these cases:
> 		// 1. The ordering columns are a prefix of the index columns.
> 		// 2. The index's columns are a prefix of the ordering columns (this
> ```

[nit] "index columns"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-:-L8SDrLj-EeMdXinQlqG:bg7igkv)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 22 of 22 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/memo.go, line 413 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8XQ1vRIDM6PHUoAjHj:-L8XQ1vRIDM6PHUoAjHk:b5o04yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/memo/memo.go#L413)):*
> ```Go
> 	for i := 0; i < cnt; i++ {
> 		best := mgrp.bestExpr(bestOrdinal(i))
> 		if best.op != opt.UnknownOp {
> ```

Why would it be unknown?

---

*[pkg/sql/opt/xform/explorer.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8XSc1gqc1ZVQrwpNFE:-L8XSc1gqc1ZVQrwpNFF:b-vrnexs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L40)):*
> ```Go
> //  )
> //  =>
> //  ...
> ```

Maybe add one or two examples of the possible outputs?

---

*[pkg/sql/opt/xform/explorer.go, line 78 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8XT2l1midhA6kx_RKW:-L8XT2l1midhA6kx_RKX:bdgdzed) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L78)):*
> ```Go
> // the start of the next pass. For example:
> //
> //   pass1         pass2         pass3
> ```

nice example!

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8XYCCn7fX_jt7hXhvp:-L8XYCCn7fX_jt7hXhvq:b-w12127) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/physical_props_factory.go#L103)):*
> ```Go
> 
> 	case opt.ScanOp:
> 		// Scan naturally orders according to the primary index.
> ```

not just primary anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-:-L8XacISFVsv5WmfkNnW:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 16 of 29 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/opt/metadata.go, line 119 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8PJy-wxdS_49jWU4LA:-L8XflcVO4k3t4rqH2Ns:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/metadata.go#L119)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This formula looks rather strange, I'd add a comment reminding the reader that the table id matches the column id of its first column
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/memo.go, line 413 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8XQ1vRIDM6PHUoAjHj:-L8XjvtQ-eVD5E1CVc-H:b-l94je0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/memo/memo.go#L413)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why would it be unknown?
</blockquote></details>

I decided to do it a different way so that it's never unknown. Before, it could be Unknown in the case where we allocated it during exploration to hold explore state, but then never actually used it.

---

*[pkg/sql/opt/xform/explorer.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8XSc1gqc1ZVQrwpNFE:-L8Xq237zycM-GI9w-ic:b-btqy08) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L40)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe add one or two examples of the possible outputs?
</blockquote></details>

I added some extra text at the bottom of the comment to discuss how the explorer handles the replace pattern.

---

*[pkg/sql/opt/xform/explorer.go, line 118 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8SDD8IAp6tWoRIDZdW:-L8XqOBbtebUiEFx8g_M:b-aedrdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] does this need to return the entire `*exploreState` or is an `fullyExplored bool` sufficient?
</blockquote></details>

We don't yet have a complex enough explore rule (i.e. one in which we match sub-expressions) to show why it's useful to get the entire `*exploreState`. The other Optgen PR has an `AssociateJoin` rule that needs to recursively call `exploreGroup`, and that needs to use the returned `exploreState`.

---

*[pkg/sql/opt/xform/explorer.go, line 162 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8PI-PZzx3-5PLs7H-z:-L8Xqr8qCMSBIeDzIiE9:bm764y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L162)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] A pointer to where what "fullyExplored" means for an expression (maybe `markExprAsFullyExplored`) would help here.
</blockquote></details>

This code is just a temporary placeholder, and will be going away once Optgen generates it. It's just here so I can split up the PR's.

---

*[pkg/sql/opt/xform/explorer.go, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8PJ2lBCSUR1lSsQ4u0:-L8XrAhLJc5aeZVfES0L:bw1ujzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L179)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't quite understand "this rule only needs to be matched once" means (and what the consequence on this code is). Is it once per expression (as opposed to rules that depend on some of the children of the expression)?
</blockquote></details>

This code is just a temporary placeholder, and will be going away once Optgen generates it. It's just here so I can split up the PR's.

There's a lot more explanation of how the generated code works in that PR. If you still have questions after reading that, I can add more commentary there.

---

*[pkg/sql/opt/xform/explorer.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8PJW7oIvgdXCXYnjdN:-L8Y0bOcNw1mtWZGs3wn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L226)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this block could be a helper function on ScanOpDef (I'm sure we'll need it in more than one place). BTW this could build a FastIntSet for the index columns and do `def.Cols.SubsetOf(..)` instead of repeated search.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/explorer.go, line 256 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8SBfTS0bKt-UCaQosw:-L8Y1X1FLtsF4LleyRGQ:b6ldv2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/explorer.go#L256)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

expressions.

Isn't `end` exclusive? (in which case it should be "expressions starting with <end> are new expressions`)
In any case, we should mention explicitly here whether `end` is inclusive or exclusive
</blockquote></details>

Yes, it's exclusive. I updated comment.

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8XYCCn7fX_jt7hXhvp:-L8Y1uxTfwtc6-K9_bnv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/physical_props_factory.go#L103)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

not just primary anymore
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188#-L8SDSkOAWB-WScs9Q9E:-L8Y1whNOnEStvcQrHDP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f796a7b3b6ea6d5b44257110ec46e2052843b23b/pkg/sql/opt/xform/physical_props_factory.go#L109)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "index columns"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24188)*

**Comment by rytaft** [comment]
Reviewed 7 of 13 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/xform/explorer.go, line 73 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8Y9NcVDV-6UpU7M_1n:-L8Y9NcVDV-6UpU7M_1o:b-4fsvog) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ccd9297c91d781ce9a87124878e0433f0938409/pkg/sql/opt/xform/explorer.go#L73)):*
> ```Go
> //      $r
> //      $t
> //      (Filters (ConstructConditionsNotUsing $t $lowerOn $upperOn))
> ```

should this be conditions not using `$s`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/explorer.go, line 73 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8Y9NcVDV-6UpU7M_1n:-L8YMzGqCDpfCgDODgBG:b-cg9ftn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ccd9297c91d781ce9a87124878e0433f0938409/pkg/sql/opt/xform/explorer.go#L73)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should this be conditions not using `$s`?
</blockquote></details>

Whoops, yes. I'll fix it in my other PR so I don't have to re-run tests...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/xform/explorer.go, line 73 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188#-L8Y9NcVDV-6UpU7M_1n:-L8YNNMJC6xfKUTvvDiD:b-fv2hv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ccd9297c91d781ce9a87124878e0433f0938409/pkg/sql/opt/xform/explorer.go#L73)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Whoops, yes. I'll fix it in my other PR so I don't have to re-run tests...
</blockquote></details>

Sounds good - I think the one below should be `$s` too (ConstructConditionsUsing).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24188)*

**Pull request merged**
