### PR TITLE
util/tracing: assorted perf optimizations and bug fixes

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Cool improvements! :lgtm: modulo some comments around `SpanAlloc`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-:-LNQBL-hC-b9uKCt7m_w:b-lah5i2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/tracing/tracer.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ6PxG8ZkH8AXHbiGk:-LNQ6PxG8ZkH8AXHbiGl:bsfqknu) ([raw file](https://github.com/cockroachdb/cockroach/blob/976872d80c6237c0be541c7aa5985e0c466c1f82/pkg/util/tracing/tracer.go#L341)):*
> ```Go
> }
> 
> // RecordableRootOpt specifies whether a root span should be recordable.
> ```

[nit] Is `Root` necessary in these names? I think it's enough if the comment mentions "root span". It's not like it can be used anywhere other than `StartRootSpan`
___
*[pkg/util/tracing/tracer.go, line 385 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ80tl5EPBsrPo-n79:-LNQ80tl5EPBsrPo-n7A:bd1rsu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer.go#L385)):*
> ```Go
> // InitRootSpan is like StartRootSpan, except it operates on a pre-allocated
> // SpanAlloc. The caller can get the initialized span using alloc.GetSpan().
> func (t *Tracer) InitRootSpan(alloc *SpanAlloc, opName string, logTags *logtags.Buffer) {
> ```

This should mention the requirements on the caller. They can't use `alloc` again until this span is `Finished`? Is that sufficient (I don't remember if recordings can hold on to spans for longer?)

Ideally there would be a mechanism to panic if we try to reuse a span when we shouldn't.

[nit] This can return `opentracing.Span`, and we can remove `SpanAlloc.GetSpan`
___
*[pkg/util/tracing/tracer.go, line 414 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQAZdQ9CIjXpyONB2Y:-LNQAZdQ9CIjXpyONB2Z:b-dgorlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer.go#L414)):*
> ```Go
> 
> 	if logTags != nil {
> 		for _, t := range logTags.Get() {
> ```

[nit] can prealloc `s.tags` here to `len(logTags.Get())`
___
*[pkg/util/tracing/tracer_span.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQArwh7sz2QiuRofT1:-LNQArwh7sz2QiuRofT2:bdlw7ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L97)):*
> ```Go
> )
> 
> // SpanAlloc is an exported span for the purposes of allowing other packages to
> ```

This has different semantics than our other `..Alloc` types which allocate in chunks. I would name it differently, maybe `PreallocatedSpan`
___
*[pkg/util/tracing/tracer_span.go, line 157 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ9Z8h4rMvlR9bFeU7:-LNQ9Z8h4rMvlR9bFeU8:b-t6oxhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L157)):*
> ```Go
> 
> func (s *span) reset() {
> 	s.spanMeta = spanMeta{}
> ```

This seems fragile (wrt adding new members). We could just do
```go
tags := s.mu.tags[:0]
*s = span{}
s.mu.tags = tags
```
___
*[pkg/util/tracing/tracer_span.go, line 392 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQAGz99czwmWBTSZ4v:-LNQAGz99czwmWBTSZ4w:b-4a78fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L392)):*
> ```Go
> func (s *span) SetTag(key string, value interface{}) opentracing.Span {
> 	var valStr string
> 	if s, ok := value.(string); ok {
> ```

When I did something similar for the logtags, @nvanbenschoten suggested to also handle `Stringer` case and call `String()` directly, which saves an allocation from `Sprint`.

https://github.com/cockroachdb/cockroach/blob/master/pkg/util/log/logtags/tag.go#L37
___
*[pkg/util/tracing/tracer_span.go, line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ9Kqh-ZSYspZ3-HCN:-LNQ9Kqh-ZSYspZ3-HCO:bqgnaby) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L411)):*
> ```Go
> 		s.mu.Lock()
> 	}
> 	s.mu.tags = append(s.mu.tags, tag{key: key, val: val})
> ```

[nit] if s.mu.tags is empty, we could preallocate for a bunch of tags (e.g. 4) since we'll likely have a few

**Review by nvb — APPROVED** [review]
:lgtm: mod most of @RaduBerinde's comments. Good change!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 14 of 14 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-:-LNS4JOm1BHNCXAg8r3w:bgdr67u)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/txn_state.go, line 164 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNS0Mub5fW3_hUhtHaC:-LNS0Mub5fW3_hUhtHaD:b-4us55b) ([raw file](https://github.com/cockroachdb/cockroach/blob/976872d80c6237c0be541c7aa5985e0c466c1f82/pkg/sql/txn_state.go#L164)):*
> ```Go
> 	// TODO(andrei): We should use tracing.EnsureChildSpan() as that's much more
> 	// efficient that StartSpan (and also it'd be simpler), but that interface
> 	// doesn't current support the Recordable option.
> ```

All the more reason to stop making this span recordable. Tracing should be as close to free as possible when not enabled.
___
*[pkg/util/tracing/shadow.go, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNS3oOh1DMfwAMSbr_a:-LNS3oOh1DMfwAMSbr_b:b-otvmrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/shadow.go#L95)):*
> ```Go
> 	opts = append(opts, opentracing.StartTime(s.startTime))
> 	if s.mu.tags != nil {
> 		var otTags opentracing.Tags
> ```

How does this work? Shouldn't it panic because you never created the map?
___
*[pkg/util/tracing/tracer.go, line 385 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ80tl5EPBsrPo-n79:-LNS3wKW6hJWXNYLJ8Ag:b-euyex6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer.go#L385)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should mention the requirements on the caller. They can't use `alloc` again until this span is `Finished`? Is that sufficient (I don't remember if recordings can hold on to spans for longer?)

Ideally there would be a mechanism to panic if we try to reuse a span when we shouldn't.

[nit] This can return `opentracing.Span`, and we can remove `SpanAlloc.GetSpan`
</blockquote></details>

+1 to all of this.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30705)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/txn_state.go, line 164 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNS0Mub5fW3_hUhtHaC:-LNS6Vd6ATt5inGZMAd9:b971s3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/976872d80c6237c0be541c7aa5985e0c466c1f82/pkg/sql/txn_state.go#L164)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

All the more reason to stop making this span recordable. Tracing should be as close to free as possible when not enabled.
</blockquote></details>

well now StartSpan is only used when there's something funky going on
___
*[pkg/util/tracing/shadow.go, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNS3oOh1DMfwAMSbr_a:-LNS8db67y1qEXS7A_mZ:b-fxcaaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/shadow.go#L95)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How does this work? Shouldn't it panic because you never created the map?
</blockquote></details>

woops, fixed.
I was planning on running this with Jaegar or something before merging :P
___
*[pkg/util/tracing/tracer.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ6PxG8ZkH8AXHbiGk:-LNRj9ZY1JGz0gQfDVbQ:bbsm1f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/976872d80c6237c0be541c7aa5985e0c466c1f82/pkg/util/tracing/tracer.go#L341)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Is `Root` necessary in these names? I think it's enough if the comment mentions "root span". It's not like it can be used anywhere other than `StartRootSpan`
</blockquote></details>

I put `Root` as to not clash with `Recordable`. Renamed to RecordableOpt/RecordableSpan.
___
*[pkg/util/tracing/tracer.go, line 385 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ80tl5EPBsrPo-n79:-LNRzoG04DLlQ1MHOjCj:b-1iygjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer.go#L385)):*
> This should mention the requirements on the caller. They can't use alloc again until this span is Finished? Is that sufficient (I don't remember if recordings can hold on to spans for longer?)

Done. Recordings do survive the Finish(). The contract states that the span in the alloc shouldn't be in use any more, period. Prompted by this, I've also wrote a bit of code to clarify that the contract holds for sql txn spans that are recording. Check out `releaseSpanFromAllocIfEqual()`. When executing `set tracing=on`, we start recording on the current txn's span, and also open another span that will record all future txns until `set tracing=off`. The first span was in apparent danger of being clobbered before its recording was read; it wasn't happening, but I don't want to explain why.

> Ideally there would be a mechanism to panic if we try to reuse a span when we shouldn't.

Done, we now assert that the span has been Finish()ed (or it's just a span{} that was never used).

> [nit] This can return opentracing.Span, and we can remove SpanAlloc.GetSpan

I think I've had a better idea. `SpanAlloc` is now a type alias for `span`. This gets rid of `GetSpan()`; `*SpanAlloc` can be used as an `opentracing.Span`. But I've still taken the suggestion to make this return an `opentracing.Span` although it seems weird to return the exactly the input... But I see we've done this elsewhere.
___
*[pkg/util/tracing/tracer.go, line 414 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQAZdQ9CIjXpyONB2Y:-LNS56K4BxR03EFxeUeO:btx2uq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer.go#L414)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can prealloc `s.tags` here to `len(logTags.Get())`
</blockquote></details>

done, here and elsewhere
___
*[pkg/util/tracing/tracer_span.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQArwh7sz2QiuRofT1:-LNS5KJzCPQOegWFbmJs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L97)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This has different semantics than our other `..Alloc` types which allocate in chunks. I would name it differently, maybe `PreallocatedSpan`
</blockquote></details>

done
___
*[pkg/util/tracing/tracer_span.go, line 157 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ9Z8h4rMvlR9bFeU7:-LNS5NQd4fjsPRAF7TUE:b-8ft9vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L157)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems fragile (wrt adding new members). We could just do
```go
tags := s.mu.tags[:0]
*s = span{}
s.mu.tags = tags
```
</blockquote></details>

:100:
___
*[pkg/util/tracing/tracer_span.go, line 392 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQAGz99czwmWBTSZ4v:-LNS6-RB3eEboQdUu11p:bmpqysp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L392)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

When I did something similar for the logtags, @nvanbenschoten suggested to also handle `Stringer` case and call `String()` directly, which saves an allocation from `Sprint`.

https://github.com/cockroachdb/cockroach/blob/master/pkg/util/log/logtags/tag.go#L37
</blockquote></details>

done. But the code you link, as well as this one, doesn't handle typed nil Stringers. Should it? I say we expect the Stringer implementations to handle it internally...
___
*[pkg/util/tracing/tracer_span.go, line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ9Kqh-ZSYspZ3-HCN:-LNS63Ga3QPbh2hE-HXs:b-2blvc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L411)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] if s.mu.tags is empty, we could preallocate for a bunch of tags (e.g. 4) since we'll likely have a few
</blockquote></details>

I've preallocated in one of the callers; don't know if it's worth doing more

**Review by RaduBerinde — COMMENTED** [review]
I would try out a version with a span allocator that allocs spans in chunks (similar to DatumAlloc). If the perf benefits are similar, that would be a cleaner solution.

You can also try using a `sync.Pool`, and something like `releaseSpanFromAllocIfEqual` would choose whether to put the span back into the pool or let it loose. It still requires that the "won't use it again" logic is correct though.

Another potential option is to recognize that most sessions won't ever record a span and optimize for those. We could use a preallocated span until the first time `StartTracing` runs, at which point we switch to allocating new spans each time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-:-LNTBhQB4yAdZi0XmUpB:b-lhzqi6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/txn_state.go, line 447 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNTAZhrCAfXeKLmVLT7:-LNTAZhrCAfXeKLmVLT8:b-itazz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/44af162767a71f176ffea30d81b238827164ff7c/pkg/sql/txn_state.go#L447)):*
> ```Go
> func (ts *txnState) releaseSpanFromAllocIfEqual(sp opentracing.Span) {
> 	if &ts.alloc.sp == sp {
> 		ts.alloc.sp = tracing.PreallocatedSpan{}
> ```

I don't understand this. We are not "putting a fresh one in", we're zeroing it out. The next span will still point here, just like `sp`.
___
*[pkg/util/tracing/tracer.go, line 385 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ80tl5EPBsrPo-n79:-LNTAzlZ3Q44-7Bt_Uqd:b-xl9wnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer.go#L385)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> This should mention the requirements on the caller. They can't use alloc again until this span is Finished? Is that sufficient (I don't remember if recordings can hold on to spans for longer?)

Done. Recordings do survive the Finish(). The contract states that the span in the alloc shouldn't be in use any more, period. Prompted by this, I've also wrote a bit of code to clarify that the contract holds for sql txn spans that are recording. Check out `releaseSpanFromAllocIfEqual()`. When executing `set tracing=on`, we start recording on the current txn's span, and also open another span that will record all future txns until `set tracing=off`. The first span was in apparent danger of being clobbered before its recording was read; it wasn't happening, but I don't want to explain why.

> Ideally there would be a mechanism to panic if we try to reuse a span when we shouldn't.

Done, we now assert that the span has been Finish()ed (or it's just a span{} that was never used).

> [nit] This can return opentracing.Span, and we can remove SpanAlloc.GetSpan

I think I've had a better idea. `SpanAlloc` is now a type alias for `span`. This gets rid of `GetSpan()`; `*SpanAlloc` can be used as an `opentracing.Span`. But I've still taken the suggestion to make this return an `opentracing.Span` although it seems weird to return the exactly the input... But I see we've done this elsewhere.

</blockquote></details>

I'm not crazy about the alias, which is effectively exporting the type, allowing calling any capitalized `span` methods, and allowing it to be passed as an `opentracing.Span` to anything. I liked an obtuse type more because there was only one way in which you could use it.
___
*[pkg/util/tracing/tracer_span.go, line 392 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQAGz99czwmWBTSZ4v:-LNTAn-s1NOzlCG_LpME:biijrbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer_span.go#L392)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done. But the code you link, as well as this one, doesn't handle typed nil Stringers. Should it? I say we expect the Stringer implementations to handle it internally...
</blockquote></details>

I'd say they should handle it if a `nil` object of that type is a thing

**Review by andreimatei — COMMENTED** [review]
I've taken out the last commit - the one about preallocating spans.
I'm doing something else instead - redoing the way "session tracing" works so that the txn spans can be noopSpans when it's not used. But it's taking a while.

I believe there were no remaining comments on the other commits, so please stamp when you can.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-:-LNkw74E46PuYl1M7M70:bvs4iyz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/txn_state.go, line 447 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNTAZhrCAfXeKLmVLT7:-LNkwVUH7kkK1MFgtHES:bh89j5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/44af162767a71f176ffea30d81b238827164ff7c/pkg/sql/txn_state.go#L447)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't understand this. We are not "putting a fresh one in", we're zeroing it out. The next span will still point here, just like `sp`.
</blockquote></details>

removed commit
___
*[pkg/util/tracing/tracer.go, line 385 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-LNQ80tl5EPBsrPo-n79:-LNkwXX-1RPsFCWh-zyH:bh89j5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1a410356c2a543a118b5b3d4ee5d00148b2631b/pkg/util/tracing/tracer.go#L385)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not crazy about the alias, which is effectively exporting the type, allowing calling any capitalized `span` methods, and allowing it to be passed as an `opentracing.Span` to anything. I liked an obtuse type more because there was only one way in which you could use it.
</blockquote></details>

removed commit

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-:-LNkyLdU6bYGXHj4H_cN:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30705#-:-LNl4MUwCJWeYILLmhDX:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
