### PR TITLE
sql, opt: avoid full scans in mutation queries with cost flags

### LINKED ISSUE #79683: opt: the optimizer cost model should consider contention
Currently, CockroachDB's optimizer tries to find the best plan for a query in isolation and doesn't concern itself with the possibility that reading more rows than needed could cause write conflicts. Consider the following example:
```
CREATE TABLE tab (
  a INT,
  b INT,
  INDEX (b)
);
INSERT INTO tab SELECT generate_series(1,500), 1;
INSERT INTO tab SELECT generate_series(501,1000), 2;
ANALYZE tab;
EXPLAIN UPDATE tab SET a = 2000 WHERE b = 1;
                                             info
-----------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • update
  │ table: tab
  │ set: a
  │ auto commit
  │
  └── • render
      │ estimated row count: 500
      │
      └── • filter
          │ estimated row count: 500
          │ filter: b = 1
          │
          └── • scan
                estimated row count: 1,000 (100% of the table; stats collected 2 seconds ago)
                table: tab@tab_pkey
                spans: FULL SCAN
```
The optimizer chooses a full scan of the primary index instead of using the index on `b`, since in isolation, this is less expensive than performing an index join with half the rows in the table. However, it means that any other query that wants to update rows where `b = 2` will block, even though technically there is no conflict.

Ideally, the optimizer would almost never choose a full scan for mutation queries such as this one where a suitable index is available, due to the impact on contention.

Epic CRDB-37836

Jira issue: CRDB-14977

gz#11932

gz#18109

### PR DESCRIPTION
**Pull request by rytaft**
**opt: convert `memo.Cost` to a struct with `CostFlags`**

This is a mechanical change that will set up the ability to use
`CostFlags` in a future commit.

Release note: None

**opt,sql: support hint to avoid full scan**

Added a hint to avoid full scans (see release note below for details).
To support this change, added a field to `memo.Cost` with a new type
`memo.CostFlags`, which contains a number of boolean flags and supports
"multi-dimensional costing". This allows the optimizer to compare plans
based on the flags set in addition to the single-dimensional float64
cost. For example, plans with the new `FullScanPenalty` cost flag enabled
will always be more expensive than plans without any cost flags, even
if the base float64 cost is lower.

The new `CostFlags` type also includes a flag for `HugeCostPenalty`, which
must be set for plans with `hugeCost`. This ensures that existing
hints that use `hugeCost` still work if some other cost flags are set,
since `HugeCostPenalty` takes precedence over other cost flags.

This new `CostFlags` field is needed to support hints that do not cause an
error if the optimizer cannot find a plan complying with the hint. This
is needed because the previous approach of simply using `hugeCost` to
avoid certain plans meant that if such plans were unavoidable, we could
not effectively compare plans with cost greater than `hugeCost` due to
loss of floating point precision.

Informs https://github.com/cockroachdb/cockroach/issues/79683

Release note (sql change): Added support for a new index hint,
`AVOID_FULL_SCAN`, which will prevent the optimizer from planning a
full scan for the specified table if any other plan is possible. The
hint can be used in the same way as other existing index hints. For
example, `SELECT * FROM table_name@{AVOID_FULL_SCAN};`. This hint is
similar to `NO_FULL_SCAN`, but will not error if a full scan cannot be
avoided. Note that normally a full scan of a partial index would not
be considered a "full scan" for the purposes of the `NO_FULL_SCAN` and
`AVOID_FULL_SCAN` hints, but if the user has explicitly forced the
partial index via `FORCE_INDEX=index_name`, we do consider it a full
scan.

**sql,opt: add setting `avoid_full_table_scans_in_mutations`**

Fixes https://github.com/cockroachdb/cockroach/issues/79683

Release note (sql change): Added a new session setting
`avoid_full_table_scans_in_mutations`, which when set to true, causes
the optimizer to avoid planning full table scans for mutation queries
if any other plan is possible. It now defaults to true.

**opt: remove a stale comment above `optbuilder.buildScan`**

Removed a comment that references a function parameter that no longer
exists.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2770 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2_pQEDFobZ8FcYzRZ:-OF2_pQFCRkRZHZSBNYs:bqz8loj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/xform/testdata/rules/limit#L2770)):*
> ```
>                 ├── scan t82730a@t82730a_col1_1_col1_3_key
>                 │    ├── columns: col1_0:7!null col1_1:8 col1_3:9
>                 │    ├── constraint: /8/9
> ```

I'm looking into this.

**Comment by rytaft** [comment]
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2844 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2_wEvEShLH2paRJFP:-OF2_wEx4RkRq5ybEK0M:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/xform/testdata/rules/limit#L2844)):*
> ```
>                 ├── scan t82730b@t82730b_col1_1_col1_3_key [as=tab_41831]
>                 │    ├── columns: col1_0:7!null col1_1:8 col1_3:9
>                 │    ├── constraint: /8/9
> ```

Ditto

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137984)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2770 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2_pQEDFobZ8FcYzRZ:-OF2jAlqAcIol57X_Hw5:b-gx7uze) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/xform/testdata/rules/limit#L2770)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm looking into this.
</blockquote></details>

This is an unrelated bug: https://github.com/cockroachdb/cockroach/issues/137994
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2844 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2_wEvEShLH2paRJFP:-OF2jED2A2nxLKO8FJFg:bthha92) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/xform/testdata/rules/limit#L2844)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

See https://github.com/cockroachdb/cockroach/issues/137994

**Comment by rytaft** [comment]
*[`pkg/sql/opt/memo/cost.go` line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2m1iF0FbQPwDj4pRT:-OF2m1iH2VMcmkD_8WGX:b-pdwj1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/memo/cost.go#L14)):*
> ```Go
> // TODO: Need more details about what one "unit" of cost means.
> type Cost struct {
> 	Cost  float64
> ```

Happy to bikeshed on names here -- maybe the "Cost" data member should just be "C"?

**Review by mgartner — APPROVED** [review]
Great idea! 

:lgtm:

> Reviewed 24 of 24 files at r1, 24 of 24 files at r2, 84 of 84 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-:-OF8mYBi1cu-9wMElyGb:b1cwje)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/memo/cost.go` line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2m1iF0FbQPwDj4pRT:-OF8eO4p6ywwLczg7eJR:b-s5i9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/memo/cost.go#L14)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Happy to bikeshed on names here -- maybe the "Cost" data member should just be "C"?
</blockquote></details>

I like `C`. :+1: 
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2770 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2_pQEDFobZ8FcYzRZ:-OF8m5g-3KfvklVj2NVH:b4esrcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/xform/testdata/rules/limit#L2770)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is an unrelated bug: https://github.com/cockroachdb/cockroach/issues/137994
</blockquote></details>

I'm worried this change makes this bad plan more likely to hit, so I'm going to label that bug a GA-blocker for now.
___
*[`pkg/sql/opt/memo/cost.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF8i_XWB_KlWRIefN4w:-OF8i_XWB_KlWRIefN4x:bx89bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/85a9bf4a5ddcba061a913cec98d7a6b40916f989/pkg/sql/opt/memo/cost.go#L53)):*
> ```Go
> type CostFlags struct {
> 	FullScanPenalty bool
> 	HugeCostPenalty bool
> ```

nit: an explanation of each of these might be useful
___
*[`pkg/sql/opt/xform/coster.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF8iTr05MoFmtAt8RKG:-OF8iTr1CDMQ6CkB6hRi:b-qqhbnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/85a9bf4a5ddcba061a913cec98d7a6b40916f989/pkg/sql/opt/xform/coster.go#L193)):*
> ```Go
> 	// If the final expression has this cost or larger, it means that there was no
> 	// plan that could satisfy the hints.
> 	hugeCost = memo.Cost{Cost: 1e100, Flags: memo.CostFlags{HugeCostPenalty: true}}
> ```

Do we still need the `1e100` cost for hugeCost?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 505 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF8jCnnDHkXRU4vjuO0:-OF8jCnnDHkXRU4vjuO1:b8ljhr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce131c71914103803b64dbbe4c7a5c573f61df10/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L505)):*
> ```
> # Delete accessing all regions should fail.
> retry
> statement error pq: Query has no home region\. Try adding a filter on messages_rbr\.crdb_region and/or on key column \(messages_rbr\.message\)\. For more information, see https://www.cockroachlabs.com/docs/stable/cost-based-optimizer.html#control-whether-queries-are-limited-to-a-single-region
> ```

Any idea why this changed?

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-:-OFETzSw6qZdeO32GaJj:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/memo/cost.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF8i_XWB_KlWRIefN4w:-OF9z0HQ42YGp5-4NkeM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85a9bf4a5ddcba061a913cec98d7a6b40916f989/pkg/sql/opt/memo/cost.go#L53)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: an explanation of each of these might be useful
</blockquote></details>

Done.
___
*[`pkg/sql/opt/memo/cost.go` line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2m1iF0FbQPwDj4pRT:-OF9v0lx5yiC8KEE2Gfh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/memo/cost.go#L14)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I like `C`. :+1:
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/coster.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF8iTr05MoFmtAt8RKG:-OF9z2AM5VLrgCpblUxB:bxq5m4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/85a9bf4a5ddcba061a913cec98d7a6b40916f989/pkg/sql/opt/xform/coster.go#L193)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do we still need the `1e100` cost for hugeCost?
</blockquote></details>

We shouldn't need it anymore, but I didn't want to make more changes than necessary for this PR.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 505 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF8jCnnDHkXRU4vjuO0:-OFEU0gW6V7D8oyqIlL5:bioj1cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce131c71914103803b64dbbe4c7a5c573f61df10/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L505)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Any idea why this changed?
</blockquote></details>

The reason is that the plan changed from a full table scan of the primary index to a constrained scan of the secondary index (only when enforce_home_region is true... otherwise the constrained scan was also chosen before). The error message is constructed based on the chosen plan (which may not be the best approach... but anyway, that's the explanation).
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2770 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137984#-OF2_pQEDFobZ8FcYzRZ:-OF9zSTC0vFivmvV1Jpj:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0b63a56cac93183fff7c9102b5629b1dafeec4f/pkg/sql/opt/xform/testdata/rules/limit#L2770)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm worried this change makes this bad plan more likely to hit, so I'm going to label that bug a GA-blocker for now.
</blockquote></details>

:thumbsup:

**Pull request merged**
