### PR TITLE
catalog: protobuf and cluster versioning for autostats table settings

### PR DESCRIPTION
**Pull request by msirek**
This commit adds protobuf and cluster versioning needed for #78110

Release note: none

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
The bazel flake on this PR was juicy. I got sniped: https://github.com/cockroachdb/cockroach/issues/79015. 

I'm cool with this change. Thanks for going through the iterations on the details of using the fields. 

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79009#-:-MzNZi807YeUtqcGQCh_:bmi6tbp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Review by rytaft — APPROVED** [review]
:lgtm:

Do you want to add the backport-22.1 label?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79009#-:-MzNdjlx8KM0TtuiWyyW:bnfbfbf)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @postamar)

**Comment by michae2** [comment]
While we're at it, can we preallocate another table descriptor field? 😬 https://github.com/cockroachdb/cockroach/pull/79025

**Review by msirek — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79009#-:-MzOHHfH9I28Vt2KSMqI:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @postamar)

**Pull request merged**
