### PR TITLE
sql: allow PRIMARY REGION syntax for CREATE / ALTER DATABASE

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Introduced stubs for ALTER DATABASE ...
PRIMARY REGION and CREATE TABLE ... PRIMARY REGION

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56883)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/parser/parse_test.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56883#-MMWx4b622ztyMvOZFOv:-MMWx4b622ztyMvOZFOw:b-ywv6e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b3b8dbc25b13bc37d2b870ea237b73801f3afe/pkg/sql/parser/parse_test.go#L77)):*
> ```Go
> 		{`CREATE DATABASE a SURVIVE REGION FAILURE`},
> 		{`CREATE DATABASE a SURVIVE ZONE FAILURE`},
> 		{`CREATE DATABASE a PRIMARY REGION = "us-west-1"`},
> ```

Nit - Stupid question, but why is the "=" semantics the one that we parse to by default?
___
*[pkg/sql/sem/tree/create.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56883#-MMWyLMI8FCN1dWHe4e8:-MMWyLMI8FCN1dWHe4e9:b-bbg3bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b3b8dbc25b13bc37d2b870ea237b73801f3afe/pkg/sql/sem/tree/create.go#L80)):*
> ```Go
> 	}
> 	if node.PrimaryRegion != "" {
> 		ctx.WriteString(" PRIMARY REGION = ")
> ```

Nit: Same question about "=" here.  I'd think we'd default to no "="

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56883)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/parser/parse_test.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56883#-MMWx4b622ztyMvOZFOv:-MMXE8S_2snHhF5OzfA4:b-qsseby) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b3b8dbc25b13bc37d2b870ea237b73801f3afe/pkg/sql/parser/parse_test.go#L77)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit - Stupid question, but why is the "=" semantics the one that we parse to by default?
</blockquote></details>

fixed!

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56883#-:-MMXGgUr4SlNbbd01WLI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

**Comment by otan** [comment]
thanks!

bors r=ajstorm

**Pull request merged**
