### PR TITLE
kv: allow secondary tenants to view range metadata for their ranges 

### PR DESCRIPTION
**Pull request by arulajmani**
This patch introduces a new GetRangeDescriptorsRPC to scan over range
descriptors. The RPC returns a consistent view of range descriptors in
the system for ranges that overlap with the requested keyspan. The RPC
is setup to allow for a streaming response in the future, but for now,
we only return a single response. Care must be taken to uphold the
consistency semantics if we were to make use of the streaming behaviour
in the future.

This RPC is then used to allow secondary tenants to view range metadata
for ranges they own. This is done by proxying scans through the
`Connector` for secondary tenants, and performing the usual keybound
authorization we do in other places.

This patch serves as the enabler for secondary tenants to do things
like `SHOW RANGES` or have scoped access to
`crdb_internal.ranges_no_leases` in the future.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, @renatolabs, and @smg260)

___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhUcl4QOrsuSvkQgJ:-NHzhUcl4QOrsuSvkQgK:b-hwnu0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L454)):*
> ```Go
> 
> // Scan implements the rangedesc.Scanner interface.
> func (c *Connector) Scan(
> ```

I wonder if we wouldn't want this `Scan` method to also return an iterator of sorts.

(With, for your convenience, a first implementation that pre-loads all the values in RAM; but still an iterator as public API)
___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 468 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhOEc6Hr7OWVQ0sKj:-NHzhOEc6Hr7OWVQ0sKk:b-aymsua) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L468)):*
> ```Go
> 		if err != nil {
> 			log.Warningf(ctx, "error issuing GetRangeDescriptors RPC: %v", err)
> 			c.tryForgetClient(ctx, client)
> ```

why is this needed? perhaps explain comment.
___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 472 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhKufDAp87ZWKfYGm:-NHzhKufDAp87ZWKfYGn:b-acykb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L472)):*
> ```Go
> 		}
> 
> 		for {
> ```

i believe you need to check  ctx in this loop too.
___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhQIvCSD4WpSGn-gR:-NHzhQIvCSD4WpSGn-gS:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L480)):*
> ```Go
> 				// Soft RPC error. Drop client and retry.
> 				log.Warningf(ctx, "error consuming GetRangeDescriptors RPC: %v", err)
> 				c.tryForgetClient(ctx, client)
> ```

ditto
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhumE9bMEMDViuWzZ:-NHzhumE9bMEMDViuWz_:b-fu7q05) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/kv/kvclient/kvtenant/connector.go#L67)):*
> ```Go
> 	// this ensures SQL-only tenants are not able to access Range Metadata for
> 	// Ranges not owned by the requesting tenant.
> 	rangedesc.Scanner
> ```

Please discuss with @ecwall and @dhartunian  - we're aiming to merge some of these interfaces, see #92599.nn

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @ecwall, @knz, @renatolabs, and @smg260)

___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhUcl4QOrsuSvkQgJ:-NHzoriu9EJ6H__kXPpI:b-1yrwax) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L454)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I wonder if we wouldn't want this `Scan` method to also return an iterator of sorts.

(With, for your convenience, a first implementation that pre-loads all the values in RAM; but still an iterator as public API)
</blockquote></details>

Maybe I'm missing something, but don't we need to buffer all range descriptors in memory to serve `SHOW RANGES` anyway? Would an iterator here get us much?
___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhumE9bMEMDViuWzZ:-NHzjP4SADlyX71wdGvR:baxbvmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/kv/kvclient/kvtenant/connector.go#L67)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please discuss with @ecwall and @dhartunian  - we're aiming to merge some of these interfaces, see #92599.nn
</blockquote></details>

Were you hinting at merging `RangeDescriptorDB` with this interface? I actually spent a fair bit of time trying to do that in my initial implementation, but it fell apart because of how low-level the `RangeDescriptorDB` implementation is. Specifically, because it's implemented by the `DistSender` for the system tenant, it can't make use of the `kv.Txn` interface. In the end I just gave up on trying to merge these two together and decided to add this.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dhartunian, @ecwall, @renatolabs, and @smg260)

___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhUcl4QOrsuSvkQgJ:-NHzuEOG0wgH2jXrHmHb:bl32ccz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L454)):*
> don't we need to buffer all range descriptors in memory to serve SHOW RANGES anyway?

I don't see why - the vtable generators have iterator-like interfaces. They're meant to not accumulate their results in RAM.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, @renatolabs, and @smg260)

___
*[`pkg/kv/kvclient/kvtenant/connector.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhumE9bMEMDViuWzZ:-NHzuMXR-BnkuM3kJ8FV:bwqh93j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/kv/kvclient/kvtenant/connector.go#L67)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Were you hinting at merging `RangeDescriptorDB` with this interface? I actually spent a fair bit of time trying to do that in my initial implementation, but it fell apart because of how low-level the `RangeDescriptorDB` implementation is. Specifically, because it's implemented by the `DistSender` for the system tenant, it can't make use of the `kv.Txn` interface. In the end I just gave up on trying to merge these two together and decided to add this. 
</blockquote></details>

no objection

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @renatolabs, and @smg260)

___
*[`pkg/util/rangedesc/rangedesc.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NI4B50E3obZq1hzdLIz:-NI4B50FEX0bpo4XXwmi:byks7h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/util/rangedesc/rangedesc.go#L86)):*
> ```Go
> }
> 
> // NewScanner returns a Scanner.
> ```

Can `Scanner.Scan` and `Iterator.Iterate` be methods in `DB`?

This pattern requires that a new interface be added for each new function instead of adding those functions to the existing interface.

**Comment by ajwerner** [comment]
An `hlc.Timestamp` names a snapshot. I'm not totally convinced a snapshot it that important here. Is there a reason we rejected using the regular ol' `kvcoord.RangeIterator`?

**Comment by knz** [comment]
> the regular ol' kvcoord.RangeIterator?

This one uses the range cache and the range cache does not immediately reflect the result of Admin kv commands. Our tests want the range descs retrieved here to immediately reflect admin changes.

**Review by arulajmani — COMMENTED** [review]
> An hlc.Timestamp names a snapshot. I'm not totally convinced a snapshot it that important here. Is there a reason we rejected using the regular ol' kvcoord.RangeIterator?

What Rafa said -- this stuff was briefly discussed in https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1668789452895839 as well. 

Changed things such that we now use an `rangedesc.IteratorFactory` and `rangedesc.Iterator` interface instead of the `Scanner` stuff I had before. The `Connector` implements the `rangedesc.IteratorFactory` interface for secondary tenants. PTAL.  

> Dismissed @knz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-:-NI4ZqmfB_HY1L6r755d:bf27gsf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, @renatolabs, and @smg260)

___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhUcl4QOrsuSvkQgJ:-NI4ZiHz1JQnnVcej_3S:bcds1i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L454)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> don't we need to buffer all range descriptors in memory to serve SHOW RANGES anyway?

I don't see why - the vtable generators have iterator-like interfaces. They're meant to not accumulate their results in RAM.
</blockquote></details>

I switched things around to use an `Iterator` interface instead. PTAL. 
___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 468 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhOEc6Hr7OWVQ0sKj:-NI4ZR0843kHjhQyujkb:b-76jmfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L468)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

why is this needed? perhaps explain comment.
</blockquote></details>

Added the generic "Soft RPC error. Drop client and retry.", though I copied this stuff from elsewhere in the file. 
___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 472 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhKufDAp87ZWKfYGm:-NI4ZcfOBdxuFPAHM7eY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L472)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

i believe you need to check  ctx in this loop too.
</blockquote></details>

Done.
___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NHzhQIvCSD4WpSGn-gR:-NI4_K_OCxy7wEv141Te:b-yxqmto) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/ccl/kvccl/kvtenantccl/connector.go#L480)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Something other than this "soft RPC error"? Honestly, I copied this stuff from a different place in the file. 
___
*[`pkg/util/rangedesc/rangedesc.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NI4B50E3obZq1hzdLIz:-NI4YDXE8cj-GkgJlX-0:bkpxrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6b1d474eed0766d3f863f3b954ce29dc4822eb7/pkg/util/rangedesc/rangedesc.go#L86)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Can `Scanner.Scan` and `Iterator.Iterate` be methods in `DB`?

This pattern requires that a new interface be added for each new function instead of adding those functions to the existing interface.
</blockquote></details>

Note that some of this has changed in my push to address Rafa's comment above, but I'll address your conceptual question about a new interface vs. adding a method on `DB`. 

In this specific case, we want to implement the interface on the `Connector` for secondary tenants and a different place for the system tenant. This allows us to leverage keybound checks when a secondary tenant tries to fetch range descriptors for its ranges.

**Review by knz — COMMENTED** [review]
Nice, this looks good now. Just a thing about error handling and this is good to go.

> Reviewed 12 of 34 files at r3, 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-:-NI8GLi42uhSun3r0chw:b-mcusip)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, @renatolabs, and @smg260)

___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 487 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NI8G1iE8OZhlHJKg7bv:-NI8G1iE8OZhlHJKg7bw:b-1mnyrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a7810561a6a190f344e6d3f58c10249189ce2cb/pkg/ccl/kvccl/kvtenantccl/connector.go#L487)):*
> ```Go
> 		}
> 	}
> 	return nil, ctx.Err()
> ```

Don't you want to pick up the last `err` from inside the loop here?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @renatolabs, and @smg260)

___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 487 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NI8G1iE8OZhlHJKg7bv:-NIASDQA7XMaqYXEhT2a:b-zhg2b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a7810561a6a190f344e6d3f58c10249189ce2cb/pkg/ccl/kvccl/kvtenantccl/connector.go#L487)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Don't you want to pick up the last `err` from inside the loop here?
</blockquote></details>

Right now, we're treating all errors inside the loop as "retryable". I think this relates to the question @ecwall had on Slack earlier today, where he mentioned some errors should be treated as terminal (such as the request trying to access descriptors outside the tenant's keyspan). That's a reasonable ask, though it would mean we'd have to identify all such "fatal" errors and handle them. For now, I'm inclined to put a TODO here.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 24 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-:-NICN9dxC7Sw7L0y0KWn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall, @renatolabs, and @smg260)

___
*[`pkg/ccl/kvccl/kvtenantccl/connector.go` line 487 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92603#-NI8G1iE8OZhlHJKg7bv:-NICMQSR4--0vAqxGq2E:batxfqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a7810561a6a190f344e6d3f58c10249189ce2cb/pkg/ccl/kvccl/kvtenantccl/connector.go#L487)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Right now, we're treating all errors inside the loop as "retryable". I think this relates to the question @ecwall had on Slack earlier today, where he mentioned some errors should be treated as terminal (such as the request trying to access descriptors outside the tenant's keyspan). That's a reasonable ask, though it would mean we'd have to identify all such "fatal" errors and handle them. For now, I'm inclined to put a TODO here. 
</blockquote></details>

Ok I'm seeing the other functions in this file are using the same pattern. No further comment from me.

**Comment by arulajmani** [comment]
TFTR! 

bors r=knz

**Comment by rail** [comment]
bors retry

**Pull request merged**
