### PR TITLE
sql/schemachanger: reduce dependency layering in scrun

### PR DESCRIPTION
**Pull request by ajwerner**
The explicit dependencies added recently were a very good thing for testing.
A problem with them is that not everything which needed to happen as a part
of mutation transactions was being layered underneath the execution of the
actual stage. The problem with not layering the work underneath the op
execution itself is at least twofold:

* It forced several additional layers of dependency injection in order
  to properly capture side-effects. These layers were crufty and hard to
  model mentally.
* It compromised a key design goal which allowed the in-memory manipulation
  of data to be tested and composed independently of the interactions with
  the underlying data storage system. If we needed to have code both above
  and below the op execution layer modifying descriptors and jobs, if we ever
  wanted to batch these things together, we'd require even more gymnastics
  in terms of state encapsulation.

The solution here is to add more ops in the scrun layer and inject them into
execution. This ends up working out reasonably well. I look forward to getting
feedback on it.

This isn't the only reworking that I envision here, I think that the validation
and backfills likely ought not execute in quite the same context as the
mutations. They generally don't want a transaction and do want to create
multiple transactions of their own.

One rough edge here is that we currently don't lock all of the descriptor
types with the job; only the tables. This needs to change soon. The rough
edge is that we read the immutable descriptor before deciding to check out
the descriptor.

Release note: None

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
I really like this change, especially the core idea of defining the schema changer job manipulations as ops. This Is The Way.

I feel you could go further and add these new ops in the planning, perhaps when building the stage. Even if you don't go this far, there are a few small areas which warrant a bit more polish before this is merged. Nothing big and I look forward to stamping this.

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73433#-:-Mq-imdT1QxZlIjcx7km:b2qvsla)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scop/ops.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73433#-Mq-gBQX9409FORByrsj:-Mq-gBQY9fxA-LTJFHlp:b-78c1zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1123cb47745094c2f105e1c79a8c0cdad9a72067/pkg/sql/schemachanger/scop/ops.go#L31)):*
> ```Go
> func ExtendOps(existing Ops, added ...Op) (_ Ops, err error) {
> 	return makeOps(append(existing.Slice(), added...)...)
> }
> ```

Consider making this a method on State perhaps?
___
*[pkg/sql/schemachanger/scrun/scrun.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73433#-Mq-gUic261YbnIhmI_k:-Mq-gUic261YbnIhmI_l:b-lf2zvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1123cb47745094c2f105e1c79a8c0cdad9a72067/pkg/sql/schemachanger/scrun/scrun.go#L161)):*
> ```Go
> 			}
> 		}
> 	}
> ```

I find this for-loop block hard to reason about, although I eventually understood it. In the short term, please at least add more comments explaining that if this is a mutation stage we can just do the extra ops in the same txn as the planned stage's ops, and vice-versa in a non-mutation stage because those ops aren't done in a transaction.

Thinking more broadly, perhaps each stage should have two classes of ops, transactional ops and non-transactional. Also, I feel that these `opsToAdd` should simply be planned in scplan, same with the pre-commit job creation. I know we don't have the job ID at that point but this doesn't feel like a big problem.
___
*[pkg/sql/schemachanger/scrun/scrun.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73433#-Mq-fSRS6ddfv8EIRYWj:-Mq-fSRS6ddfv8EIRYWk:b-fsju3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1123cb47745094c2f105e1c79a8c0cdad9a72067/pkg/sql/schemachanger/scrun/scrun.go#L182)):*
> ```Go
> 	if err != nil {
> 		err = errors.Wrapf(err, "error executing %s", stage.String())
> 		return scgraphviz.DecorateErrorWithPlanDetails(err, p)
> ```

It seems that this error decoration should be moved to a higher level now.

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scrun/scrun.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73433#-Mq-taORAZNGk_e9AV_K:-Mq-taORAZNGk_e9AV_L:bufxemz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eac67679a67128ea809ad00935ea6f416a10cd0e/pkg/sql/schemachanger/scrun/scrun.go#L53)):*
> ```Go
> 	) error {
> 		var opsToAdd []scop.Op
> 		jobID, opsToAdd = createSchemaChangeJobAndAddDescriptorJobReferenceOps(deps, stage.After, stage.Revertible)
> ```

Would it make sense to push this into the opgen logic and have rules for emitting these ops? Or is the concern I guess reverts where we can start at an arbitrary point. Or even make this a part of MakePlan vs execution?

**Review by fqazi — COMMENTED** [review]
I love the idea of the ops, I think we can reason about them being in planning. If we are deleting descriptors we also need to skip these ops or have them occur earlier, so it would fall nicely if we could get into opgen or MakePlan.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73433#-:-Mq-uAroDLCXr3yVt6i_:b-wrrqgf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
All this feedback makes sense. Let me ponder for a little bit how best to make the planner deal with this. 

One possibility is to make the job into an element. It's interesting for changes which don't have post-commit phases and thus don't have jobs. Maybe I can leverage dep edges for that. 

A simpler but potentially less satisfying alternative would be to augment the plan in the planner effectively like I did here. 

This need to issue mutation ops in backfill and validation stages is hinting to me that we don't quite have the right abstractions. I don't need to solve that right now. 

Thoughts?

**Comment by fqazi** [comment]
> All this feedback makes sense. Let me ponder for a little bit how best to make the planner deal with this.
> 
> One possibility is to make the job into an element. It's interesting for changes which don't have post-commit phases and thus don't have jobs. Maybe I can leverage dep edges for that.
> 
> A simpler but potentially less satisfying alternative would be to augment the plan in the planner effectively like I did here.
> 
> This need to issue mutation ops in backfill and validation stages is hinting to me that we don't quite have the right abstractions. I don't need to solve that right now.
> 
> Thoughts?

I like the job element approach it allows us to order things for deletion and have clean solutions for certain operations. One example would be Type deletion where if we had the job ID in there we could remove it before wiping the descriptor. The simpler solution also works and my main concern with this stuff was poor encapsulation, where runtime was scanning the graph to set these operations up, which felt really leaky. I'm more of a fan of the first solution rather than the second one.

**Comment by postamar** [comment]
I'm in favour of going with the simple solution so that this can get merged today. It's not an either/or thing, I see this particular change as a strict improvement which won't prevent anyone from thinking about what we _really_ want.

**Review by fqazi — APPROVED** [review]

**Comment by ajwerner** [comment]
Okay, I moved the logic into `scplan`. It took a couple of iterations to get the pieces to fit.

**Review by fqazi — APPROVED** [review]
> Reviewed 9 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Review by postamar — COMMENTED** [review]
I've only had a superfluous look at your recent changes, but it looks good and I'm glad you're merging it.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73433#-:-MqGF0gI0sNU-sqmUmL0:b1ozjku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Pull request merged**
