### PR TITLE
sql: implement plan_cache_mode=auto

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: implement plan_cache_mode=auto

The `plan_cache_mode=auto` session setting has been implemented which
instructs the database to pick generic query plans for prepared
statements when they have a cost less than or equal to custom plans.

The current strategy matches Postgres's strategy quite closely. Under
`plan_cache_mode=auto`, custom query plans will be generated for the
first five executions of a prepared statement. On the sixth execution, a
generic query plan will be generated. If the cost of the generic query
plan is less than the average cost of the custom plans (plus some
overhead for re-optimization), then the generic query plan will be used.

Epic: CRDB-37712

Release note (sql change): The session setting `plan_cache_mode=auto`
can now be used to instruct the system to automatically determine
whether to use "custom" or "generic" query plans for the execution of a
prepared statement. Custom query plans are optimized on every execution,
while generic plans are optimized once and reused on future executions
as-is. Generic query plans are beneficial in cases where query
optimization contributes significant overhead to the total cost of
executing a query.

#### rfc: minor edits to generic query plans RFC

The term "absolute generic plan" has been replaced with "ideal generic
query plan".

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first 3 commits are from #126528.

**Review by DrewKimball — APPROVED** [review]
I have some suggestions, nits, but overall 
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 23 of 23 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-:-O1JR0WtAAKFEu8AvDHE:b-cg1831)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/prepared_stmt.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JMhyqAB4AL0QWjhnp:-O1JMhyqAB4AL0QWjhnq:babltns) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/prepared_stmt.go#L61)):*
> ```Go
> 	// optimizer during prepare of a SQL statement.
> 	//
> 	// It may be a fully-optimized memo if it contains a "perfect generic plan"
> ```

Some possibilities other than "perfect": best, ideal, optimal, final, finalized. (I'm not unhappy with perfect, just throwing out some ideas)
___
*[`pkg/sql/prepared_stmt.go` line 139 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JQqCm2u-cvrSFr1jc:-O1JQqCm2u-cvrSFr1jd:bdcu9kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/prepared_stmt.go#L139)):*
> ```Go
> 	// plan_cache_mode=auto before attempting to generate a generic plan. It is
> 	// also the maximum number of custom plan costs tracked the planCostStats.
> 	CustomPlanThreshold = 5
> ```

[nit] Should this be a setting?
___
*[`pkg/sql/opt/memo/memo.go` line 528 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JOPxxE2oNP9NvHGnx:-O1JOPxxE2oNP9NvHGny:b-3uw9ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/opt/memo/memo.go#L528)):*
> ```Go
> 	// TODO(mgartner): Package these constants up in a shared location.
> 	const cpuCostFactor = 0.01
> 	return Cost(m.Metadata().NumTables()) * 1000 * cpuCostFactor
> ```

We could also consider using the number of expressions in the memo / the estimated size in bytes. I think it would also be very reasonable to use the `grunning` library to track the CPU time spent optimizing.

Alternatively, we could do something totally different, and track both optimization and execution time for the previous runs. Maybe we could do a little algebra, like this:
```
<expected generic total time> = <avg custom execution time> * <generic plan cost> / <custom plan avg cost>
```
Then, we'd only choose the generic plan when measured planning time is a significant portion of total runtime.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/generic` line 735 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JOtUR7yh0MlpqwXLG:-O1JOtUR7yh0MlpqwXLH:b-5t3xy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/opt/exec/execbuilder/testdata/generic#L735)):*
> ```
> 
> # On the sixth execution a generic query plan will be generated. The cost of the
> # generic plan is more than less than the average cost of the five custom plans
> ```

[nit] `more than less than` -> `more than`

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/prepared_stmt.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JMhyqAB4AL0QWjhnp:-O1OHO8E9qmqeviNbp-h:bno6xpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/prepared_stmt.go#L61)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Some possibilities other than "perfect": best, ideal, optimal, final, finalized. (I'm not unhappy with perfect, just throwing out some ideas)
</blockquote></details>

I like "ideal".
___
*[`pkg/sql/prepared_stmt.go` line 139 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JQqCm2u-cvrSFr1jc:-O1OEzCz4wQ1-a-ePTpZ:bpwlvl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/prepared_stmt.go#L139)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Should this be a setting?
</blockquote></details>

Ya, maybe. I'm inclined to keep it simple for now and add a setting if we need it in the future.
___
*[`pkg/sql/opt/memo/memo.go` line 528 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JOPxxE2oNP9NvHGnx:-O1ODRu665ewzT9hofLn:b-l4ubq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/opt/memo/memo.go#L528)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We could also consider using the number of expressions in the memo / the estimated size in bytes. I think it would also be very reasonable to use the `grunning` library to track the CPU time spent optimizing.

Alternatively, we could do something totally different, and track both optimization and execution time for the previous runs. Maybe we could do a little algebra, like this:
```
<expected generic total time> = <avg custom execution time> * <generic plan cost> / <custom plan avg cost>
```
Then, we'd only choose the generic plan when measured planning time is a significant portion of total runtime.
</blockquote></details>

All good ideas. I think we can explore them in the future if we find this implementation to be insufficient—I'm planning on testing the limits of this simple logic during stability. But for an initial implementation, I think this should be fine. I mostly just want `auto` do have a different behavior rather than a no-op.

I'm a bit skeptical of basing the decision on measured execution and optimization time because that can vary quite wildly regardless of the logical plan, e.g., because of data distribution, resource utilization, background work, contention, MVCC garbage. I could see it causing a lot of flapping or poor decisions. But I do think it's worth more thought.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/generic` line 735 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JOtUR7yh0MlpqwXLG:-O1OEu_x4J6utGcyG-0v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/opt/exec/execbuilder/testdata/generic#L735)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `more than less than` -> `more than`
</blockquote></details>

Done.

**Review by DrewKimball — APPROVED** [review]
> Reviewed 24 of 25 files at r6, 21 of 21 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`-- commits` line 8 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1OhrOx9CULJ_Bv_SMW):*
[nit] `currently` -> `current`
___
*[`pkg/sql/prepared_stmt.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JMhyqAB4AL0QWjhnp:-O1OhPde-93H65cblkdA:b-670ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/prepared_stmt.go#L61)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I like "ideal".
</blockquote></details>

We could also approach from the other direction, and go with something like "imperfect", "heuristic", "approximate", "ad-hoc". That also makes me think of "exact". Or even, something like "simple" and "complex".

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 8 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1OhrOx9CULJ_Bv_SMW):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `currently` -> `current`
</blockquote></details>

Done.
___
*[`pkg/sql/prepared_stmt.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JMhyqAB4AL0QWjhnp:-O1SF5OmBhcWhNT-l7FR:bjdkwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/prepared_stmt.go#L61)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We could also approach from the other direction, and go with something like "imperfect", "heuristic", "approximate", "ad-hoc". That also makes me think of "exact". Or even, something like "simple" and "complex".
</blockquote></details>

Thanks for all the good ideas! I still like "ideal"—a modified for the special cases seems to make sense to me. I'll be ironing out this code after backporting it and we can revisit the naming then if we're not all in agreement—it won't be too hard to change. SGTY?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/prepared_stmt.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JMhyqAB4AL0QWjhnp:-O1Sp3xe50ertS8IdVZM:b-81nlyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/prepared_stmt.go#L61)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Thanks for all the good ideas! I still like "ideal"—a modified for the special cases seems to make sense to me. I'll be ironing out this code after backporting it and we can revisit the naming then if we're not all in agreement—it won't be too hard to change. SGTY?
</blockquote></details>

SGTM!

**Review by michae2 — APPROVED** [review]
Same, just nits, or things we can refactor when adding generic query plans to the plan cache. Nice work! :lgtm:

> Reviewed 3 of 6 files at r4, 1 of 25 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-:-O1T0A8kAaD7V3gZxefP:bo808zf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/plan_opt.go` line 489 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1Rob_F9WHjoSofHzyQ:-O1Rob_GEssznn8fkiVr:b-hk6zw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a488ec17e2aeb36fdb615f1de29ba9a3793b85/pkg/sql/plan_opt.go#L489)):*
> ```Go
> 		}
> 		// With a canned plan, we don't want to optimize the memo.
> 		return opc.optimizer.DetachMemo(ctx), memoTypeCustom, nil
> ```

Kind of an academic question since we're not really using `PREPARE AS OPT PLAN`, but should this be `memoTypeIdealGeneric` since there were no placeholders and we treat the canned plan as fully optimized?
___
*[`pkg/sql/plan_opt.go` line 617 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1T-bgpB6__uzE2zhed:-O1T-bgpB6__uzE2zhee:bvs7ig8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a205d7c59dfa44c3fb2a81e84b169ae09d6fbc/pkg/sql/plan_opt.go#L617)):*
> ```Go
> 	// Next check for a non-stale, generic memo.
> 	if reuseGeneric && genericMemo != nil {
> 		isStale, err := genericMemo.IsStale(ctx, opc.p.EvalContext(), opc.catalog)
> ```

If the generic memo is stale, should we be resetting `prep.GenericCost` to zero? Without doing so, it seems like maybe we could get stuck with an artificially high `prep.GenericCost` if some DDL both renders the memo stale and makes plans much cheaper?
___
*[`pkg/sql/plan_opt.go` line 694 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1Szy-V4je8sbJUZCth:-O1Szy-V4je8sbJUZCti:bkiwdox) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a205d7c59dfa44c3fb2a81e84b169ae09d6fbc/pkg/sql/plan_opt.go#L694)):*
> ```Go
> 				prep.GenericCost < prep.CustomCosts.Avg()
> 		}
> 	}
> ```

Is this the same code block as above, except for `prep.GenericCost == 0`? Would it make sense to broaden the responsibilities of `planCostStats` a little and push this code block down into a method of `planCostStats`?
___
*[`pkg/sql/prepared_stmt.go` line 79 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1SqKxGD2Kmae32ONEm:-O1SqKxHD25K4HEls0my:b6ji7tn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a205d7c59dfa44c3fb2a81e84b169ae09d6fbc/pkg/sql/prepared_stmt.go#L79)):*
> ```Go
> 
> 	// CustomCosts tracks the costs of previously optimized "custom plans".
> 	CustomCosts planCostStats
> ```

When we add generic query plans to the plan cache, will this also be included in the plan cache? If so, I wonder if it would make sense to put it in `PrepareMetadata`?
___
*[`pkg/sql/opt/memo/memo.go` line 528 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JOPxxE2oNP9NvHGnx:-O1SpkCyBf3GgIjleBuv:b-toput2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/opt/memo/memo.go#L528)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

All good ideas. I think we can explore them in the future if we find this implementation to be insufficient—I'm planning on testing the limits of this simple logic during stability. But for an initial implementation, I think this should be fine. I mostly just want `auto` do have a different behavior rather than a no-op.

I'm a bit skeptical of basing the decision on measured execution and optimization time because that can vary quite wildly regardless of the logical plan, e.g., because of data distribution, resource utilization, background work, contention, MVCC garbage. I could see it causing a lot of flapping or poor decisions. But I do think it's worth more thought.
</blockquote></details>

Another (future) idea is to factor in the total number of columns / variables.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/plan_opt.go` line 489 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1Rob_F9WHjoSofHzyQ:-O1TKeJ-0p-VRsRIjY2t:b-3bbm9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a488ec17e2aeb36fdb615f1de29ba9a3793b85/pkg/sql/plan_opt.go#L489)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Kind of an academic question since we're not really using `PREPARE AS OPT PLAN`, but should this be `memoTypeIdealGeneric` since there were no placeholders and we treat the canned plan as fully optimized?
</blockquote></details>

Sure. I don't think any behavior changes because of it, but I guess it makes more sense to consider it ideal.
___
*[`pkg/sql/plan_opt.go` line 617 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1T-bgpB6__uzE2zhed:-O1TLASE0s4grSijNebj:b-domiu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a205d7c59dfa44c3fb2a81e84b169ae09d6fbc/pkg/sql/plan_opt.go#L617)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If the generic memo is stale, should we be resetting `prep.GenericCost` to zero? Without doing so, it seems like maybe we could get stuck with an artificially high `prep.GenericCost` if some DDL both renders the memo stale and makes plans much cheaper?
</blockquote></details>

Good catch. Makes sense to me. I think we should also clear the custom plan costs if the base memo is stale, so I've added that.
___
*[`pkg/sql/plan_opt.go` line 694 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1Szy-V4je8sbJUZCth:-O1Tf2HQEztKWU1TfZo0:b58uqag) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a205d7c59dfa44c3fb2a81e84b169ae09d6fbc/pkg/sql/plan_opt.go#L694)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is this the same code block as above, except for `prep.GenericCost == 0`? Would it make sense to broaden the responsibilities of `planCostStats` a little and push this code block down into a method of `planCostStats`?
</blockquote></details>

I did some refactoring along these lines, but slightly differently. LMK what you think.
___
*[`pkg/sql/prepared_stmt.go` line 79 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1SqKxGD2Kmae32ONEm:-O1TeNEPEdHMOazr2JYq:bbw14ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a205d7c59dfa44c3fb2a81e84b169ae09d6fbc/pkg/sql/prepared_stmt.go#L79)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

When we add generic query plans to the plan cache, will this also be included in the plan cache? If so, I wonder if it would make sense to put it in `PrepareMetadata`?
</blockquote></details>

I need to think more about how generic plans could be added to the query cache. There's a few tricky things to figure out, one of them being how to store costs and use them to decide whether to use a generic or custom plan. 
___
*[`pkg/sql/opt/memo/memo.go` line 528 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1JOPxxE2oNP9NvHGnx:-O1Tf08B9wBuNinOSuet:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09c89c37981e959d06bea4bdd96be1d26f0c7ca/pkg/sql/opt/memo/memo.go#L528)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Another (future) idea is to factor in the total number of columns / variables.
</blockquote></details>

:+1:

**Review by michae2 — APPROVED** [review]
:lgtm: Noticed one minor thing, but I'm not sure how important it is. Ship it!

> Reviewed 5 of 5 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-:-O1TxUQC-aIayCzABlg2:b-iei7z3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/plan_opt.go` line 694 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1Szy-V4je8sbJUZCth:-O1Tgghn6zWG1mfM7CbW:bb70w76) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a205d7c59dfa44c3fb2a81e84b169ae09d6fbc/pkg/sql/plan_opt.go#L694)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I did some refactoring along these lines, but slightly differently. LMK what you think.
</blockquote></details>

Nice
___
*[`pkg/sql/plan_opt.go` line 732 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1TugFbB8PBNCy-QzLv:-O1TugFbB8PBNCy-QzLw:berr42e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5fd50407101e63d8939fb5c1ec6161a9dc21d34/pkg/sql/plan_opt.go#L732)):*
> ```Go
> 			// case we have a custom plan that can be reused as a starting point
> 			// for optimization. The function should not recurse more than once.
> 			return opc.fetchPreparedMemo(ctx)
> ```

I'm thinking about a sequence of events like the following, with `plan_cache_mode=auto`:

0. starting with custom avg cost of 5 and generic cost of 4
1. some DDL renders all memos stale and slightly more expensive
2. `chooseValidPreparedMemo` picks the generic plan because 4 < 5, but returns nil due to staleness
3. we build a new generic plan with cost of 6. 5 < 6 so we call `fetchPreparedMemo` recursively
4. `chooseValidPreparedMemo` picks the custom plan because 5 < 6, but returns nil due to staleness
5. we build a new base plan. after `reuseMemo` it pushes avg cost of custom plans up to 7

Even though the new custom plan has higher cost, we use it anyway because there isn't another call to `useGenericPlan` or `fetchPreparedMemo` after rebuilding the stale base plan.

I'm not sure if we need to fix this, since by this point we've already build the custom plan, but one way to fix it would be to call `useGenericPlan` again after the recursive call to `fetchPreparedMemo`.

**Review by mgartner — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-:-O1XeKle32vPRRc1OGMn:b-tlx7ko)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/plan_opt.go` line 732 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/126863#-O1TugFbB8PBNCy-QzLv:-O1X_aG67bh6aKB8ZG0o:b6lppgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5fd50407101e63d8939fb5c1ec6161a9dc21d34/pkg/sql/plan_opt.go#L732)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I'm thinking about a sequence of events like the following, with `plan_cache_mode=auto`:

0. starting with custom avg cost of 5 and generic cost of 4
1. some DDL renders all memos stale and slightly more expensive
2. `chooseValidPreparedMemo` picks the generic plan because 4 < 5, but returns nil due to staleness
3. we build a new generic plan with cost of 6. 5 < 6 so we call `fetchPreparedMemo` recursively
4. `chooseValidPreparedMemo` picks the custom plan because 5 < 6, but returns nil due to staleness
5. we build a new base plan. after `reuseMemo` it pushes avg cost of custom plans up to 7

Even though the new custom plan has higher cost, we use it anyway because there isn't another call to `useGenericPlan` or `fetchPreparedMemo` after rebuilding the stale base plan.

I'm not sure if we need to fix this, since by this point we've already build the custom plan, but one way to fix it would be to call `useGenericPlan` again after the recursive call to `fetchPreparedMemo`.
</blockquote></details>

I think this is fine. If the base memo is stale, we're clearing all the custom plan costs, so we'll need to build 5 custom plans before we re-decide to use a generic plan or not.

FWIW, AFAICT, Postgres does not clear the custom plans costs when a memo becomes stale. It will only reset the generic cost if it builds a new generic plan. 

This sequence is confusing, though. I'm going to be iteratively trying to make this logic easier to follow, and hopefully iron out peculiarities like this.

**Pull request merged**
