### PR TITLE
storage: deflake TestRefreshPendingLeases

### PR DESCRIPTION
**Pull request by petermattis**
See #8397

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10152)

### CODE REVIEW

**Comment by petermattis** [comment]
Ran `make stress PKG=./storage/ TESTS=TestRefreshPendingCommands TESTTIMEOUT=30s STRESSFLAGS="-maxfails 1 -stderr -p 16"` for 10 min without problem.

**Comment by petermattis** [comment]
Fixed the final test scenario which was testing the periodic refreshing proposals. This test scenario was failing because of an interaction with quiescence. I don't think this could have happened in practice due to the other proposal refresh mechanisms, but it certainly wasn't intentional.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 687 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152#-KUrW9IhGojM96F_TO-e:-KUrW9IhGojM96F_TO-f:ba3dfna) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4bcd6b0ef578d0003e18b7916f0d0c956e568d0/pkg/storage/client_raft_test.go#L687)):*
> ```Go
> 
> 	// TODO(peter): Debugging to track down #8397. Remove when fixed.
> 	// if err := flag.Lookup("vmodule").Value.Set("raft=5,store=5,replica=5,replica_command=5,replica_range_lease=5"); err != nil {
> ```

Remove?

---

*[pkg/storage/client_raft_test.go, line 707 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152#-KUrWETFRAr7C8Ju0T5O:-KUrWETFRAr7C8Ju0T5P:b49ta6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4bcd6b0ef578d0003e18b7916f0d0c956e568d0/pkg/storage/client_raft_test.go#L707)):*
> ```Go
> 			sc := storage.TestStoreConfig()
> 			sc.TestingKnobs = c
> 			sc.TestingKnobs.DisablePeriodicGossips = true
> ```

Add brief comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152#-:-KUrWHhPdaYx7fbI_p8H:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/client_raft_test.go, line 687 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152#-KUrW9IhGojM96F_TO-e:-KUraxT7EXVhQ9ZZlpkC:b-p3hbwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4bcd6b0ef578d0003e18b7916f0d0c956e568d0/pkg/storage/client_raft_test.go#L687)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Remove?
</details>
Done. Don't know why I was leaving that in. 

---

*[pkg/storage/client_raft_test.go, line 707 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152#-KUrWETFRAr7C8Ju0T5O:-KUrb45rvkte4JV9u59Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4bcd6b0ef578d0003e18b7916f0d0c956e568d0/pkg/storage/client_raft_test.go#L707)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Add brief comment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10152)*

**Pull request merged**
