### PR TITLE
roachtest: add kv benchmarks with expiration-based leases

### PR DESCRIPTION
**Pull request by erikgrinaker**
Epic: none
Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm: Thanks for adding. Will be good to track this over time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100593#-:-NSBevea3138BnTXreBO:b-j4qcsh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @renatolabs, and @smg260)

**Comment by erikgrinaker** [comment]
bors r-

Forgot to add a string tag for these.

**Pull request merged**
