### PR TITLE
vendor: update c-protobuf and misc others

### PR DESCRIPTION
**Pull request by tamird**
Notably includes minor raft changes:
- coreos/etcd@9342647
- coreos/etcd@bc6bebe

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13714)

### CODE REVIEW

**Comment by petermattis** [comment]
What's with all the `.pb.go` changes? Do you have to rebuild with go1.7?

**Comment by tamird** [comment]
Checking. There's a chance I rebuilt the protos with Go 1.8.

**Comment by tamird** [comment]
OK, fixed.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 29 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13714#-:-KdbLLFzMGcZFZf35eac:bnfp4nl)*

**Comment by dt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 28 of 28 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13714#-KdbLVzQqwf9RxF6Ql4w:-KdbLVzQqwf9RxF6Ql4x:b-o18w9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e54c5c63cb9008f7728545981d829f510d691bb/Makefile#L89)):*
> ```Makefile
> endif
> 
> export MACOSX_DEPLOYMENT_TARGET=10.9
> ```

nit: could throw a comment here for future readers, as this isn't read anywhere in the repo and might appear unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13714#-:-KdbLyzs4uygnnmGuANq:bnfp4nl)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13714#-KdbLVzQqwf9RxF6Ql4w:-KdbMJMfmD3hi2MR9XQx:b59w7ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e54c5c63cb9008f7728545981d829f510d691bb/Makefile#L89)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: could throw a comment here for future readers, as this isn't read anywhere in the repo and might appear unused.
</blockquote></details>

Yeah, I considered that, but this guy got its own commit so the git blame is there to document the intent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13714)*

**Pull request merged**
