### PR TITLE
rpc: give first heartbeats a longer timeout

### LINKED ISSUE #13983: stability: nightly test gossip failures
Two tests failed after waiting for 2 minutes for the full cluster to be visible in the gossip state:
* https://teamcity.cockroachdb.com/viewLog.html?buildId=172570&buildTypeId=Cockroach_AllocatorTest3to510g
* https://teamcity.cockroachdb.com/viewLog.html?buildId=172573&buildTypeId=C_BW_4Nodes_6Hours

A quick scan of the [3->5 allocator/load test node.2 log](https://teamcity.cockroachdb.com/repository/download/Cockroach_AllocatorTest3to510g/172570:id/allocator_test_logs/node.2/cockroach.stderr) shows these errors early on:

```
W170308 07:13:34.185513 130 storage/store.go:1405  [n3,s3] could not gossip system config: [NotLeaseHolderError] range 331: replica {3 3 3} not lease holder; lease holder unknown
I170308 07:13:34.707229 278 gossip/client.go:131  [n3] started gossip client to rebal-3to5s-happywilliams-cockroach-2:26257
I170308 07:13:34.708890 278 gossip/client.go:138  [n3] closing client to rebal-3to5s-happywilliams-cockroach-2:26257: rpc error: code = 2 desc = duplicate connection from node at {tcp rebal-3to5s-happywilliams-cockroach-3:26257}
```

### LINKED ISSUE #14064: acceptance: Tests failing with non-zero exit code
#14024
#14027
#14029
#14047
And maybe #14023, although that failed slightly differently.

Possibly related to #13983, which isn't yet fixed.

Any thoughts, @tamird?

### PR DESCRIPTION
**Pull request by tamird**
This addresses a number of issues where the remote side is slow to
start, causing spurious disconnects.

Closes #13983.
Closes #14064.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14073)

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14073#-:-KethLzzV6oC5vbpGTbd:bnfp4nl)*

**Comment by bdarnell** [comment]
This doesn't seem like the right fix - why do we need to make sure that the first heartbeat succeeds, instead of allowing it to fail and be retried?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14073#-:-Kf7TrVj_ogiSEp4Bhhm:bmjk4rz)*

**Comment by tamird** [comment]
I'm not sure what you mean; we use heartbeat timeouts to detect network partitions and close the underlying grpc connection so that other pending RPCs to that address fail immediately.

In the cases addressed here, the destination node may still be starting, so a grace period is desired. It is unlikely that there are deadlocked RPCs to the destination while the first heartbeat is deadlocked.

The concrete issue here are:
- gossip will eventually stop retrying a node after it has successfully bootstrapped
- CLI clients never retry

We could special case the CLI clients to avoid heartbeating altogether, but what would you suggest be done about gossip?

**Comment by bdarnell** [comment]
For gossip (as described in https://github.com/cockroachdb/cockroach/issues/13983#issuecomment-285151422), when node 2 and 3 connect, they form a gossip network but they don't have the cluster id because they haven't connected to the bootstrapping node 1. Gossip should keep retrying all join/bootstrap nodes until it gets the cluster id, instead of stopping once it has some gossip connections. 

For CLI clients (this is just clients that use the GRPC interface, right?), they should probably just turn off heartbeating.

**Comment by tamird** [comment]
> For gossip (as described in #13983 (comment)), when node 2 and 3 connect, they form a gossip network but they don't have the cluster id because they haven't connected to the bootstrapping node 1. Gossip should keep retrying all join/bootstrap nodes until it gets the cluster id, instead of stopping once it has some gossip connections.

@spencerkimball this is still not the current behaviour, correct?

> For CLI clients (this is just clients that use the GRPC interface, right?), they should probably just turn off heartbeating.

OK, I'll do that (probably by turning off heartbeat if the clock maxoffset is zero, which is only the case for CLI clients).

**Comment by spencerkimball** [comment]
Yes, gossip will keep looking until it has received the cluster id. In #13983, the cluster id is gossiped by other nodes which are already connected and it's merely node 1 which has no `-join` hosts, and so is left waiting for another node to connect to it. Unfortunately the rest of the cluster (the other four nodes) all connect, get the cluster ID, and at that point give up on their bootstrap hosts (Node 2 has node 1 as a bootstrap host).

This change is **not** necessary for #13983 to be fixed. Like @bdarnell I'm not convinced we need to make this change. It's ugly; if we can avoid it, I'd prefer to.

**Comment by bdarnell** [comment]
Ah, so this wasn't bootstrapping, it was restarted from on-disk state so all the nodes had the cluster id even though they had never talked to node 1 (at its current address). I think in that case I think we either need to retry `--join` hosts more aggressively (perhaps continuing until we have connected to them at least once, even if that connection is subsequently culled) or strongly discourage running any nodes without a valid `--join` flag (especially when restarting like this, but I should revive my campaign to bring back explicit initialization).

**Pull request merged**
