### PR TITLE
Cleanup from testing on go1.5beta2

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM.

I'm not seeing the connection to go 1.5 in several of these commits. Is there something I'm missing or are these just unrelated things you happened to notice?

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
@bdarnell I think just the first and third were specifically go 1.5 things, the rest are just things I noticed while testing that stuff.

**Comment by tschottdorf** [comment]
can you explain how the unbuffered channel stuff relates to Go1.5? I.e. why that became a problem in this test?

**Comment by tamird** [comment]
I don't remember the details, but here's what happens when I revert that commit locally:
```
go test -tags ''  -i ./storage
go test -tags ''  -run TestRangeCommandQueue -cpu 1 ./storage -timeout 30s
I0723 14:39:43.897438 5564 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0723 14:39:43.898920 5564 storage/range.go:996  gossiping cluster id test from store 1, range 1
I0723 14:39:43.899616 5564 storage/range_command.go:823  range 1: new leader lease replica 1:1 19:00:00.000 +1.000s
I0723 14:39:43.899716 5564 storage/range.go:1063  gossiping accounting config from store 1, range 1
I0723 14:39:43.899760 5564 storage/range.go:1063  gossiping permissions config from store 1, range 1
I0723 14:39:43.899800 5564 storage/range.go:1063  gossiping user config from store 1, range 1
I0723 14:39:43.899859 5564 storage/range.go:1063  gossiping zones config from store 1, range 1
I0723 14:39:43.899944 5564 storage/range.go:1004  gossiping sentinel from store 1, range 1
I0723 14:39:43.899959 5564 storage/range.go:1008  gossiping first range from store 1, range 1
--- FAIL: TestRangeCommandQueue (0.11s)
	range_test.go:1184: test 1: should not have been able execute cmd1 while blocked
	leaktest.go:136: Test appears to have leaked a range command:
		github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).SubmitCommand(0xc820130180, 0x1, 0xc820171410, 0x10, 0xc8200b69c0, 0x37, 0x37, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:335 +0x31e
		github.com/cockroachdb/cockroach/storage.(*Store).ProposeRaftCommand(0xc8200be9c0, 0xc820171410, 0x10, 0x1, 0x100000001, 0x0, 0xc82007f340, 0x0, 0x0, 0x0, ...)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/store.go:1459 +0x5b3
		github.com/cockroachdb/cockroach/storage.(*Range).proposeRaftCommand(0xc820080a20, 0x5746ee8, 0xc8201786c0, 0x5747838, 0xc82007f340, 0x0, 0x8)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:770 +0x890
		github.com/cockroachdb/cockroach/storage.(*Range).addWriteCmd(0xc820080a20, 0x5746ee8, 0xc8201786c0, 0x5747838, 0xc82007f340, 0x0, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:725 +0x79c
		github.com/cockroachdb/cockroach/storage.(*Range).AddCmd(0xc820080a20, 0x5746ee8, 0xc8201786c0, 0x5747838, 0xc82007f340, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:522 +0x328
		github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue.func4(0xc8201711d0, 0x6, 0x8, 0xc820170eb0, 0xc8200bcaf0, 0xc820080630, 0xc820170ea0, 0xc8200b3020)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1155 +0x12e
		created by github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1161 +0x730

		github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue.func2(0x5747638, 0xc820014900, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1113 +0xf0
		github.com/cockroachdb/cockroach/storage.(*Range).executeCmd(0xc820080a20, 0x5745030, 0xc8200300e8, 0x0, 0x5747638, 0xc820014900, 0x0, 0x0, 0x0, 0x0, ...)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_command.go:53 +0x157
		github.com/cockroachdb/cockroach/storage.(*Range).addReadOnlyCmd(0xc820080a20, 0x5746ee8, 0xc820137e00, 0x5747638, 0xc820014900, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:638 +0x807
		github.com/cockroachdb/cockroach/storage.(*Range).AddCmd(0xc820080a20, 0x5746ee8, 0xc820137e00, 0x5747638, 0xc820014900, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:519 +0x249
		github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue.func3(0xc820170ee0, 0x6, 0x8, 0xc820170eb0, 0xc8200bcaf0, 0xc820080630, 0xc820170ea0, 0xc8200b2de0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1140 +0x155
		created by github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1146 +0x66f

		testing.RunTests(0x4d49ff0, 0x4fe6c00, 0xb6, 0xb6, 0x1)
			/Users/tamird/src/go1.5beta2/src/testing/testing.go:561 +0x8ad
		testing.(*M).Run(0xc82003ff08, 0xc8200132c0)
			/Users/tamird/src/go1.5beta2/src/testing/testing.go:493 +0x70
		github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc82003ff08)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x21
		github.com/cockroachdb/cockroach/storage_test.TestMain(0xc82003ff08)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x21
		main.main()
			github.com/cockroachdb/cockroach/storage/_test/_testmain.go:424 +0x113
I0723 14:39:44.007470 5564 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0723 14:39:44.008374 5564 storage/range.go:996  gossiping cluster id test from store 1, range 1
I0723 14:39:44.008912 5564 storage/range_command.go:823  range 1: new leader lease replica 1:1 19:00:00.000 +1.000s
I0723 14:39:44.008986 5564 storage/range.go:1063  gossiping accounting config from store 1, range 1
I0723 14:39:44.009032 5564 storage/range.go:1063  gossiping permissions config from store 1, range 1
I0723 14:39:44.009071 5564 storage/range.go:1063  gossiping user config from store 1, range 1
I0723 14:39:44.009113 5564 storage/range.go:1063  gossiping zones config from store 1, range 1
I0723 14:39:44.009188 5564 storage/range.go:1004  gossiping sentinel from store 1, range 1
I0723 14:39:44.009205 5564 storage/range.go:1008  gossiping first range from store 1, range 1
--- FAIL: TestRangeCommandQueueInconsistent (0.10s)
	leaktest.go:136: Test appears to have leaked a range command:
		github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).SubmitCommand(0xc820130180, 0x1, 0xc820171410, 0x10, 0xc8200b69c0, 0x37, 0x37, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:335 +0x31e
		github.com/cockroachdb/cockroach/storage.(*Store).ProposeRaftCommand(0xc8200be9c0, 0xc820171410, 0x10, 0x1, 0x100000001, 0x0, 0xc82007f340, 0x0, 0x0, 0x0, ...)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/store.go:1459 +0x5b3
		github.com/cockroachdb/cockroach/storage.(*Range).proposeRaftCommand(0xc820080a20, 0x5746ee8, 0xc8201786c0, 0x5747838, 0xc82007f340, 0x0, 0x8)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:770 +0x890
		github.com/cockroachdb/cockroach/storage.(*Range).addWriteCmd(0xc820080a20, 0x5746ee8, 0xc8201786c0, 0x5747838, 0xc82007f340, 0x0, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:725 +0x79c
		github.com/cockroachdb/cockroach/storage.(*Range).AddCmd(0xc820080a20, 0x5746ee8, 0xc8201786c0, 0x5747838, 0xc82007f340, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:522 +0x328
		github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue.func4(0xc8201711d0, 0x6, 0x8, 0xc820170eb0, 0xc8200bcaf0, 0xc820080630, 0xc820170ea0, 0xc8200b3020)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1155 +0x12e
		created by github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1161 +0x730

		github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue.func2(0x5747638, 0xc820014900, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1113 +0xf0
		github.com/cockroachdb/cockroach/storage.(*Range).executeCmd(0xc820080a20, 0x5745030, 0xc8200300e8, 0x0, 0x5747638, 0xc820014900, 0x0, 0x0, 0x0, 0x0, ...)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_command.go:53 +0x157
		github.com/cockroachdb/cockroach/storage.(*Range).addReadOnlyCmd(0xc820080a20, 0x5746ee8, 0xc820137e00, 0x5747638, 0xc820014900, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:638 +0x807
		github.com/cockroachdb/cockroach/storage.(*Range).AddCmd(0xc820080a20, 0x5746ee8, 0xc820137e00, 0x5747638, 0xc820014900, 0x0, 0x0, 0x0, 0x0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range.go:519 +0x249
		github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue.func3(0xc820170ee0, 0x6, 0x8, 0xc820170eb0, 0xc8200bcaf0, 0xc820080630, 0xc820170ea0, 0xc8200b2de0)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1140 +0x155
		created by github.com/cockroachdb/cockroach/storage.TestRangeCommandQueue
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/range_test.go:1146 +0x66f

		testing.RunTests(0x4d49ff0, 0x4fe6c00, 0xb6, 0xb6, 0x0)
			/Users/tamird/src/go1.5beta2/src/testing/testing.go:561 +0x8ad
		testing.(*M).Run(0xc82003ef08, 0xc8200132c0)
			/Users/tamird/src/go1.5beta2/src/testing/testing.go:493 +0x70
		github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc82003ef08)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x21
		github.com/cockroachdb/cockroach/storage_test.TestMain(0xc82003ef08)
			/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x21
		main.main()
			github.com/cockroachdb/cockroach/storage/_test/_testmain.go:424 +0x113
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	0.230s
make: *** [test] Error 1
```

**Pull request merged**
