### PR TITLE
sql/opt: make VALUES type inference handle nested tuples

### LINKED ISSUE #73197: roachtest: sqlsmith/setup=empty/setting=no-mutations failed [error when decoding tuples with arrays]
roachtest.sqlsmith/setup=empty/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3804493&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3804493&tab=artifacts#/sqlsmith/setup=empty/setting=no-mutations) on master @ [40f11fead0a0453969634f8ddb0502c1f78b2806](https://github.com/cockroachdb/cockroach/commits/40f11fead0a0453969634f8ddb0502c1f78b2806):

```
SELECT
  t2.c4
FROM
  (VALUES (NULL, NULL), (NULL, 0::INT8)) AS t1 (c1, c2),
  (
    VALUES
      (NULL, (1:::DECIMAL, ARRAY[]:::RECORD[])),
      (NULL, (2:::DECIMAL, ARRAY[(1::INT8, 2::INT8)]))
  )
    AS t2 (c3, c4)
ORDER BY
  t1.c1 ASC;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
Fixes https://github.com/cockroachdb/cockroach/issues/73197

In 21b124749b1a93621786412bd54b7816a6fb1bf4 this code was enhanced to
handle empty arrays of tuples.

This commit makes it even smarter, so that it handles tuples that
themselves contain arrays of empty tuples (and further levels of nesting
as well).

This fixes internal errors that were caused by queries that used tuples
like this.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/distsql_physical_planner.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFXqZfB78pmUUv7KWj:-MqFXqZfB78pmUUv7KWk:b-7kt6x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/distsql_physical_planner.go#L263)):*
> ```Go
> 		}
> 		for _, e := range t.D {
> 			allowed, _ := v.VisitPre(e)
> ```

nit: this seems slightly suspicious - the first return argument is `recurse`, and we're treating it as `allowed`. As `VisitPre` is written currently, it seems ok, but imagine a scenario where we introduce some expression that _can_ be executed with distsql regardless of its contents, then on such expr we would return `recurse=false` although the expr is "allowed". How about checking `v.err` for being non-nil, and if it is non-nil, then stopping the recursion? This will also preserve the original error that prohibits the use of the distsql.
___
*[pkg/sql/opt/optbuilder/values.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFZWBY5y1Yv6vNRiEW:-MqFZWBY5y1Yv6vNRiEX:bi0i4bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/opt/optbuilder/values.go#L166)):*
> ```Go
> 		}
> 	}
> 	// In this base case, preference is given to the right type so that nested
> ```

nit: I think it'd be more clear if we moved this comment and `return true` part into the `else` just above. My reasoning is as follows: there, we're comparing two tuples and neither of them is `AnyTuple`, we've iterated over all elements and didn't find a single one that was more specific on the left, meaning that the right is at least as specific (or more) on each element, so we can `return true` there. Then there is a separate question about what should we return at the base when comparing two datums that are not arrays nor tuples simultaneously - in theory, it should not matter what we return (or at least we haven't found a case for that), so I'd default to `return false`. Thoughts?

**Review by mgartner — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/values.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFZWBY5y1Yv6vNRiEW:-MqF_VeX0izSLN7uRL1E:b-zdnoxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/opt/optbuilder/values.go#L166)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think it'd be more clear if we moved this comment and `return true` part into the `else` just above. My reasoning is as follows: there, we're comparing two tuples and neither of them is `AnyTuple`, we've iterated over all elements and didn't find a single one that was more specific on the left, meaning that the right is at least as specific (or more) on each element, so we can `return true` there. Then there is a separate question about what should we return at the base when comparing two datums that are not arrays nor tuples simultaneously - in theory, it should not matter what we return (or at least we haven't found a case for that), so I'd default to `return false`. Thoughts?
</blockquote></details>

This confuses me too. It seems like in the example given this `return true` would never be reached.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[pkg/sql/opt/optbuilder/values.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFZWBY5y1Yv6vNRiEW:-MqF_yR2EEuNHBhadV08:b-8qvivl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/opt/optbuilder/values.go#L166)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This confuses me too. It seems like in the example given this `return true` would never be reached.
</blockquote></details>

I think it will be reached:
- both types are tuples
- for both elements in the tuples, `!rightHasMoreSpecificTuple` evaluates to `false`, so we don't return from inside of the `else` and fall through to the base case.

Typing this out made me realize that if we do `return false` as the base case, then on the first element in the example (decimals) we would get `false` at the base case, so we would stop iteration among elements of the tuple and return `false` overall, which is not desirable.

Maybe - to clarify things - we should change the signature to something like
```
func hasMoreSpecificTuple(left, right *types.T) (rightIsMoreSpecific bool, eitherCanWork bool)
```
so that we could distinguish between "left is more specific" and "both are equal in specificity" cases.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFXqZfB78pmUUv7KWj:-MqFaFUlDbN1CKargyPa:bd5stxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/distsql_physical_planner.go#L263)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this seems slightly suspicious - the first return argument is `recurse`, and we're treating it as `allowed`. As `VisitPre` is written currently, it seems ok, but imagine a scenario where we introduce some expression that _can_ be executed with distsql regardless of its contents, then on such expr we would return `recurse=false` although the expr is "allowed". How about checking `v.err` for being non-nil, and if it is non-nil, then stopping the recursion? This will also preserve the original error that prohibits the use of the distsql.
</blockquote></details>

thanks - that's a good idea
___
*[pkg/sql/opt/optbuilder/values.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFZWBY5y1Yv6vNRiEW:-MqFaeCBBIlgCTiLNMty:bs5uvf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/opt/optbuilder/values.go#L166)):*
yeah i agree it's confusing, but i struggled with the best way of writing it.

> It seems like in the example given this return true would never be reached.

i confirmed that it does reach `true` with a debugger too. was going to explain but as i was typing yahor posted his explanation too :)

> so that we could distinguish between "left is more specific" and "both are equal in specificity" cases.

yeah, i was also going to explain why simply moving this above into the `else` wouldn't work, but looks like we agree on that now. i will try out this suggestion. another option is to only recurse if the arguments are both arrays or both tuples.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/values.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFZWBY5y1Yv6vNRiEW:-MqFbX4-CSeVvKdcp9Kf:bd87ym4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/opt/optbuilder/values.go#L166)):*
> another option is to only recurse if the arguments are both arrays or both tuples.

I like this option because it'll make it more clear that this function is only concerned with tuple and array types, but doesn't care about content types like `types.Any`. I don't see the value in the `eitherCanWork` boolean because the user of this function only needs to know if the right is more specific than the left. If `eitherCanWork` is `true`, then `rightIsMoreSpecific` should be false always.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFXqZfB78pmUUv7KWj:-MqIC-0eETyvnrMSEK-R:bt8pkef) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/distsql_physical_planner.go#L263)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

thanks - that's a good idea
</blockquote></details>

actually, i realized that it's a mistake to make VisitPre recursive -- inspecting the elements of the tuple should actually be done by `Walk`, so i updated that instead.
___
*[pkg/sql/opt/optbuilder/values.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-MqFZWBY5y1Yv6vNRiEW:-MqKNQba4O3phRdE0Fpa:b-l222rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cc6e15a208d78ef760cd951d795ddcec1a6cec/pkg/sql/opt/optbuilder/values.go#L166)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> another option is to only recurse if the arguments are both arrays or both tuples.

I like this option because it'll make it more clear that this function is only concerned with tuple and array types, but doesn't care about content types like `types.Any`. I don't see the value in the `eitherCanWork` boolean because the user of this function only needs to know if the right is more specific than the left. If `eitherCanWork` is `true`, then `rightIsMoreSpecific` should be false always.
</blockquote></details>

went with the extra check before recursion - also helped me realize that my first draft allowed for an index out of bounds panic

**Review by yuzefovich — COMMENTED** [review]
Looks like there is a concerning CI failure, but the code LGTM.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-:-MqKv3zb6E2EU2q3iUWt:bo8wu7q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by rafiss** [comment]
Fixing it required one more check to be added

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73486#-:-MqLe-sr2eoZaYYoBwpq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by rafiss** [comment]
tftr!

bors r=yuzefovich

**Pull request merged**
