### PR TITLE
sql: show hash check constraints if set NOT VALID

### PR DESCRIPTION
**Pull request by ZhouXing19**
If check constraints that accompanies hash shared index are accidentally
set `NOT VALID`, it should show up in the `SHOW CREATE TABLE`'s output.

Informs: #89012

Release note (sql change): show hash shared check constraint in `SHOW CREATE TABLE`if
it is set NOT VALID

### CODE REVIEW

**Comment by ZhouXing19** [comment]
The failed test doesn't seem related so this PR is ready for review.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89517#-:-NE1OUMZ8cE5mvAG6vzI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/show_create_table_test.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89517#-NE1OFPt2BjrW3z9gKpz:-NE1OFPt2BjrW3z9gKq-:bl7fzf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e39b060aa5c825cc58ee617209c8d0aa4741f9/pkg/sql/show_create_table_test.go#L115)):*
> ```Go
> 					"\\n\\tCONSTRAINT check_crdb_internal_y_shard_16 CHECK ("+
> 					"crdb_internal_y_shard_16 IN (0:::INT8, 1:::INT8, 2:::INT8, 3:::INT8, "+
> 					"4:::INT8, 5:::INT8, 6:::INT8, 7:::INT8, 8:::INT8, 9:::INT8, 10:::INT8, "+
> ```

nit: this and above seems like a good use case for backtick quoted strings



_Code quote:_
```Go
				"e'CREATE TABLE schema.\"table\" ("+
					"\\n\\tx INT8 NULL,"+
					"\\n\\ty INT8 NULL,"+
					"\\n\\tcrdb_internal_y_shard_16 INT8 NOT VISIBLE NOT NULL AS ("+
					"mod(fnv32(crdb_internal.datums_to_bytes(y)), 16:::INT8)) VIRTUAL,"+
					"\\n\\trowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),"+
					"\\n\\tCONSTRAINT table_pkey PRIMARY KEY (rowid ASC),"+
					"\\n\\tINDEX table_y_idx (y ASC) USING HASH WITH (bucket_count=16),"+
					"\\n\\tCONSTRAINT check_crdb_internal_y_shard_16 CHECK ("+
					"crdb_internal_y_shard_16 IN (0:::INT8, 1:::INT8, 2:::INT8, 3:::INT8, "+
					"4:::INT8, 5:::INT8, 6:::INT8, 7:::INT8, 8:::INT8, 9:::INT8, 10:::INT8, "+
					"11:::INT8, 12:::INT8, 13:::INT8, 14:::INT8, 15:::INT8)) NOT VALID\\n)'", rows[1].String())
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89517)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @ZhouXing19)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89517#-NE2c_v35koRzynx-AwM):*
nit: it should be `Release note (bug fix)`

**Comment by ajwerner** [comment]
I could see `Release note (sql change)`

**Comment by rafiss** [comment]
Yeah, I'm fine with `sql change`

**Comment by ZhouXing19** [comment]
TFTR! Updated the commit message.
Failed tests are irrelevant.
bors r=ajwerner

**Pull request merged**
