### PR TITLE
release-22.2: sql: fix formatting of import, backup and alter tenant

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes: #95618

This commit is trying to fix 2 things found in the TestRandomSyntaxGeneration failures:
1. TenenatID expr in `ALTER TENANT` and `SHOW ... FOR TENANT` should be formatted as being wrapped with parenthesises. This was fixed in 23.1. The idea is copied
from there.
2. IMPORT/BACKUP options are formatted without being wrapped with `OPTIONS ()`.  This sometimes got confused with other `WITH SOME_KEYWORD = xxx` syntax, for example `WITH BUCkET_COUNT = 123`.

Release note: None
Release justification: test fixes

### CODE REVIEW

**Comment by rafiss** [comment]
Seems like we may need this on `master` (and probably 23.1 also): https://github.com/cockroachdb/cockroach/issues/99185#issuecomment-1641435916

**Comment by chengxiong-ruan** [comment]
> Seems like we may need this on `master` (and probably 23.1 also): [#99185 (comment)](https://github.com/cockroachdb/cockroach/issues/99185#issuecomment-1641435916)

@rafiss yes, I'll apply some of the changes in this PR 23.1 and master as well.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/sem/tree/tenant_settings.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107185#-NaHplow9ml9Da6_c2T5:-NaHplow9ml9Da6_c2T6:b-uufrpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e4bdc68525c61b3eaa6f4e7a72dd776dd1effc7/pkg/sql/sem/tree/tenant_settings.go#L90)):*
> ```Go
> // all the d_expr expression *types*. We can only do so for a few
> // types for which we know that *all possible objects* of that type
> // are well-delimited, such as Subquery, NumVal or Placeholder.
> ```

very nice explanation!

maybe the multi-tenant team should be aware? it seems that `ALTER TENANT` and `SHOW CLUSTER SETTINGS FOR TENANT` are the only statements affected by this problem?
___
*[`pkg/sql/sem/tree/tenant_settings.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107185#-NaHpSlADfZmvH0tfh1p:-NaHpSlADfZmvH0tfh1q:b-t4xzbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e4bdc68525c61b3eaa6f4e7a72dd776dd1effc7/pkg/sql/sem/tree/tenant_settings.go#L109)):*
> ```Go
> 	ctx.WriteString(" FOR TENANT ")
> 	_, canOmitParentheses := node.TenantID.(alreadyDelimitedAsSyntacticDExpr)
> 	if !canOmitParentheses {
> ```

just want to understand better: what is the problem if we _always_ add the parenthesis here?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/sem/tree/tenant_settings.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107185#-NaHplow9ml9Da6_c2T5:-NaHqrBH8V_ZKRoEPo4x:b-41yzxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e4bdc68525c61b3eaa6f4e7a72dd776dd1effc7/pkg/sql/sem/tree/tenant_settings.go#L90)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

very nice explanation!

maybe the multi-tenant team should be aware? it seems that `ALTER TENANT` and `SHOW CLUSTER SETTINGS FOR TENANT` are the only statements affected by this problem?
</blockquote></details>

hehe, I stole this from master. Huge credits to @knz who added that. But yes.
___
*[`pkg/sql/sem/tree/tenant_settings.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107185#-NaHpSlADfZmvH0tfh1p:-NaHrLgs0jebX1XyXNWL:b-18hxk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e4bdc68525c61b3eaa6f4e7a72dd776dd1effc7/pkg/sql/sem/tree/tenant_settings.go#L109)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just want to understand better: what is the problem if we _always_ add the parenthesis here?
</blockquote></details>

good question, I think it's fine, but just looking weird in some cases, for example `(NULL)`...

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @knz)

___
*[`pkg/sql/sem/tree/tenant_settings.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107185#-NaHpSlADfZmvH0tfh1p:-NaI0GmW7safZejGNBWj:be263ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e4bdc68525c61b3eaa6f4e7a72dd776dd1effc7/pkg/sql/sem/tree/tenant_settings.go#L109)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

good question, I think it's fine, but just looking weird in some cases, for example `(NULL)`...
</blockquote></details>

ah OK, if the team already decided on fixing it this way on `master` then i suppose we should do that here too instead of always adding parentheses.

**Pull request merged**
