### PR TITLE
server: start purging web_sessions in secondary tenants

### LINKED ISSUE #90522: server: old entries in server.web_sessions not deleted for secondary tenants
**Describe the problem**

The call to `startPurgeOldSessions` is missing from secondary tenant servers.

Found while working on #90384.

Jira issue: CRDB-20818
Epic: CRDB-14537

### PR DESCRIPTION
**Pull request by knz**
Fixes #90522.

The next PR #90384 will ensure this code lands in the right place.

### CODE REVIEW

**Comment by rafiss** [comment]
drive-by to link this related issue, which might help eliminate some complexity here in the long term: https://github.com/cockroachdb/cockroach/issues/89453

**Review by aadityasondhi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90523#-:-NFAN0Ow2UUwy9BGiyv9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
TFYR!

bors r=aadityasondhi

**Review by stevendanna — APPROVED** [review]

**Comment by knz** [comment]
@rafiss This PR started failing on TestComposeGSSPython since yesterday, without any change in the code. Do you have an inkling of what changed?

**Comment by rafiss** [comment]
No I don't know anything that changed. I'll try looking into this.

Also, does this need a backport?

**Comment by knz** [comment]
>  I'll try looking into this.

we have an internal slack thread

> Also, does this need a backport?

not that i know

**Comment by rafiss** [comment]
My concern was that our serverless customers (all of which are going to be on v22.2) could potentially see unbounded growth of this table. See https://github.com/cockroachlabs/support/issues/1812 for an example of how that led to issues on a self-hosted cluster. I'm worried that if it leads to CPU usage issues in serverless, then we would charge a customer for RUs that they cannot control.

**Comment by knz** [comment]
> My concern was that our serverless customers (all of which are going to be on v22.2) could potentially see unbounded growth of this table. 

oh yeah I can see this too. So your recommendation would be to backport?

(We have the same problem with system.eventlog btw. There's no PR for that yet.)

**Comment by knz** [comment]
it's this issue #90521

**Comment by knz** [comment]
bors r=aadityasondhi,stevendanna

**Pull request merged**
