### PR TITLE
security: parse certificates at load time and export expiration time.

### PR DESCRIPTION
**Pull request by mberhault**
Work towards #15027

Parse certificates at load time. Any failures are persisted for clarity.
For now, only the expiration time is used (in `cockroach cert list` and metrics) but debug pages will make use of the parsed certificates.

### CODE REVIEW

**Comment by mberhault** [comment]
Second commit adds metrics for ca/node expiration times.

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/security/certificate_loader.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-KkgpZuU2nnKWr5NZYQS:-KkgpZuU2nnKWr5NZYQT:b4c4qwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cee3838486de34053ca1b15d14b73c9bd98d914/pkg/security/certificate_loader.go#L371)):*
> ```Go
> 
> 	// PEM-decode the file.
> 	derCerts, err := PEMToCertificates(ci.FileContents)
> ```

Not important, but what does the "der" in `derCerts` mean?

---

*[pkg/security/certificate_manager.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-KkgqWtAPf_zTXS-x5HL:-KkgqWtBbLMz5bagcgdb:b-rcp070) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5c08d5418acd82cf5efd8f5015043039c8b7ce/pkg/security/certificate_manager.go#L41)):*
> ```Go
> 	metaNodeExpiration = metric.Metadata{
> 		Name: "security.certificate.expiration.node",
> 		Help: "Expiration timemestamp for the node certificate. 0 means no certificate or error."}
> ```

s/timemestamp/timestamp

---

*[pkg/security/certificate_manager.go, line 248 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-Kkgqo2xQ5_UTCrx1jlr:-Kkgqo2xQ5_UTCrx1jls:b-q5w1pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5c08d5418acd82cf5efd8f5015043039c8b7ce/pkg/security/certificate_manager.go#L248)):*
> ```Go
> func (cm *CertificateManager) updateMetricsLocked() {
> 	// Metrics could be nil if we're inside a manually-constructed CertificateManager (eg: tests).
> 	if cm.caCert != nil && cm.caCert.Error == nil && cm.certMetrics.CAExpiration != nil {
> ```

Should we explicitly `Update` the value to 0 if `cm.caCert` or `cm.caCert.Error` is nil? That'll be necessary if it's possible for a process to have had a valid certificate and then only have invalid certificates after reloading them.

Ditto for the node cert metric.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-:-KkgrDXjcZ6SG3Yy86vs:bnfp4nl)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/security/certificate_loader.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-KkgpZuU2nnKWr5NZYQS:-KkhE35xPlevoy8nEG4k:br00643) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cee3838486de34053ca1b15d14b73c9bd98d914/pkg/security/certificate_loader.go#L371)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Not important, but what does the "der" in `derCerts` mean?
</blockquote></details>

it's the encoding format for the certificate. not to be confused with PEM encoding which is more of an envelope.
And in case that wasn't clear, here's the snippet from wikipedia:
`DER is a restricted variant of BER for producing unequivocal transfer syntax for data structures described by ASN.1. Like CER, DER encodings are valid BER encodings. DER is the same thing as BER with all but one sender's options removed.`

---

*[pkg/security/certificate_manager.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-KkgqWtAPf_zTXS-x5HL:-KkhEjj5F51SSYmqrJuG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5c08d5418acd82cf5efd8f5015043039c8b7ce/pkg/security/certificate_manager.go#L41)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/timemestamp/timestamp
</blockquote></details>

Done.

---

*[pkg/security/certificate_manager.go, line 248 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-Kkgqo2xQ5_UTCrx1jlr:-KkhF0i9qnouvsudPOwt:b-9zymlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5c08d5418acd82cf5efd8f5015043039c8b7ce/pkg/security/certificate_manager.go#L248)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Should we explicitly `Update` the value to 0 if `cm.caCert` or `cm.caCert.Error` is nil? That'll be necessary if it's possible for a process to have had a valid certificate and then only have invalid certificates after reloading them.

Ditto for the node cert metric.
</blockquote></details>

True. It's currently not possible (I bail early from the caller if the cert goes from good to bad), but it doesn't hurt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/certificate_loader.go, line 130 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-KkhZWa-gQRJkKii-H1R:-KkhZWa0xJCvkYwp64lm:b-9zbulo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1225799e0de5c1f2c7f9a121f25881d19f5960c9/pkg/security/certificate_loader.go#L130)):*
> ```Go
> 	Name string
> 
> 	// Parsed certificates. This is used to debugging/printing/monitoring only,
> ```

`s/to/by/g`

---

*[pkg/security/certificate_loader.go, line 136 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-Kkh_EBq0wddgCD8lA1G:-Kkh_EBq0wddgCD8lA1H:b-ym9s78) ([raw file](https://github.com/cockroachdb/cockroach/blob/1225799e0de5c1f2c7f9a121f25881d19f5960c9/pkg/security/certificate_loader.go#L136)):*
> ```Go
> 	ParsedCertificates []*x509.Certificate
> 
> 	// Expiration time is the latest "Not After" date across all parsed certificates.
> ```

Should this be the earliest `Not After` date across all parsed certificates? Note that the code matches the comment. The question is about what the correct behavior should be. I have no idea what it means for the parsed certificates to have different `Not After` dates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/certificate_loader.go, line 130 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-KkhZWa-gQRJkKii-H1R:-KkhwIJ2h3t0i8ofPXec:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1225799e0de5c1f2c7f9a121f25881d19f5960c9/pkg/security/certificate_loader.go#L130)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/to/by/g`
</blockquote></details>

Done.

---

*[pkg/security/certificate_loader.go, line 136 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-Kkh_EBq0wddgCD8lA1G:-KkhwIrRUg7LFRpjeSVJ:b-voisv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1225799e0de5c1f2c7f9a121f25881d19f5960c9/pkg/security/certificate_loader.go#L136)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be the earliest `Not After` date across all parsed certificates? Note that the code matches the comment. The question is about what the correct behavior should be. I have no idea what it means for the parsed certificates to have different `Not After` dates.
</blockquote></details>

Only CA cert files should have more than one certificate (it's technically possible to have more than one in non-CA cert files, but it won't do anything).

When your CA cert is about to expire (ideally months before), you should generate a new CA certificate and add it to the same file, using all CAs in your pool. This means that you may have one cert about to expire (or already expired) and another expiring in X years. Assuming the rest of your certificate rollout is done properly, your deadline is expiration date of the longest-lived CA.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045)*

**Comment by mberhault** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/security/certificate_loader.go, line 136 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-Kkh_EBq0wddgCD8lA1G:-KkhzZf0OtgfnXuJwnmH:bqetk1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1225799e0de5c1f2c7f9a121f25881d19f5960c9/pkg/security/certificate_loader.go#L136)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Only CA cert files should have more than one certificate (it's technically possible to have more than one in non-CA cert files, but it won't do anything).

When your CA cert is about to expire (ideally months before), you should generate a new CA certificate and add it to the same file, using all CAs in your pool. This means that you may have one cert about to expire (or already expired) and another expiring in X years. Assuming the rest of your certificate rollout is done properly, your deadline is expiration date of the longest-lived CA.
</blockquote></details>

There is one caveat but it's on the node cert, not the CA cert:
if the node certificate expires in 3 years but was signed with a CA cert expiring in 2 years, we should really compute the earliest expiration date in the chain and report that. I've added a TODO. The tricky part here is building the certificate chain.
Some of this trickery can be addressed by documentation on how to properly renew certificates, but we should be as accurate as we can here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045)*

**Comment by mberhault** [comment]
The need to monitor certificate chains is alleviated a bit by #16055. However, someone not using the cockroach cli to generate certs could still have mismatched node/CA expirations.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 2 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16045#-:-KkkmeDnZ_n1O2YNquNw:bnfp4nl)*

**Pull request merged**
