### PR TITLE
storage/engine: add Pebble benchmarks for ComputeStats and FindSplitKey

### PR DESCRIPTION
**Pull request by petermattis**
RocksDB (old) vs Pebble (new):

```
name                               old time/op    new time/op    delta
MVCCComputeStats/valueSize=8-16       183ms ± 1%     176ms ± 2%   -4.11%  (p=0.000 n=10+10)
MVCCComputeStats/valueSize=32-16      124ms ± 5%     107ms ± 2%  -13.95%  (p=0.000 n=10+9)
MVCCComputeStats/valueSize=256-16    58.4ms ± 3%    49.4ms ± 6%  -15.44%  (p=0.000 n=10+9)
MVCCFindSplitKey/valueSize=32-16     88.0ms ± 2%    81.8ms ± 1%   -7.06%  (p=0.000 n=10+10)

name                               old speed      new speed      delta
MVCCComputeStats/valueSize=8-16     366MB/s ± 1%   382MB/s ± 2%   +4.29%  (p=0.000 n=10+10)
MVCCComputeStats/valueSize=32-16    539MB/s ± 4%   627MB/s ± 2%  +16.18%  (p=0.000 n=10+9)
MVCCComputeStats/valueSize=256-16  1.15GB/s ± 2%  1.36GB/s ± 5%  +18.31%  (p=0.000 n=10+9)
MVCCFindSplitKey/valueSize=32-16    763MB/s ± 2%   821MB/s ± 1%   +7.60%  (p=0.000 n=10+10)
```

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/storage/engine/pebble_batch.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41674#-LrPUK8645UQHLuIvAq_:-LrPUK8645UQHLuIvAqa:b-xodwtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/67dbac68880c62fc6af98756d583192c5cd2142e/pkg/storage/engine/pebble_batch.go#L314)):*
> ```Go
> 	// flushing the buffered writes which is a significant performance
> 	// optimization. In Pebble we're still using the same underlying batch and if
> 	// it is indexed we'll still be indexing it as we Go.
> ```

@itsbilal, @ajkr, @sumeerbhola does this make sense? I can elaborate if necessary.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr and @itsbilal)

___
*[pkg/storage/engine/pebble_batch.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41674#-LrPUK8645UQHLuIvAq_:-LrUoT8EBXOsiwAtgZ7f:bxt8jk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/67dbac68880c62fc6af98756d583192c5cd2142e/pkg/storage/engine/pebble_batch.go#L314)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@itsbilal, @ajkr, @sumeerbhola does this make sense? I can elaborate if necessary.
</blockquote></details>

I still have no clue what a distinct batch is, how it relates to parent batches and how one shares a pebble.Batch and avoid seeing changes from a different pebbleBatch (came up in a previous review). Could you elaborate?

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41674#-:-LrVKDAR9gHEtBZMAfWZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr)

___
*[pkg/storage/engine/pebble_batch.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41674#-LrPUK8645UQHLuIvAq_:-LrVIw3FDcsrDhxE96pk:bgnqyvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/67dbac68880c62fc6af98756d583192c5cd2142e/pkg/storage/engine/pebble_batch.go#L314)):*
> how one shares a pebble.Batch and avoid seeing changes from a different pebbleBatch (came up in a previous review)

None of the Cockroach code actually relies on distinct batches not seeing changes from the parent batch past the point of creation of the distinct batch. That's why we have all the `distinct batch open` panics in both the rocksdb and pebble batch code - to catch any case where we unintentionally change the parent `pebbleBatch`. Does this help?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41674)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr)

___
*[pkg/storage/engine/pebble_batch.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41674#-LrPUK8645UQHLuIvAq_:-LrYszUX52io5MnyJ3C1:b-acis2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/67dbac68880c62fc6af98756d583192c5cd2142e/pkg/storage/engine/pebble_batch.go#L314)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

> how one shares a pebble.Batch and avoid seeing changes from a different pebbleBatch (came up in a previous review)

None of the Cockroach code actually relies on distinct batches not seeing changes from the parent batch past the point of creation of the distinct batch. That's why we have all the `distinct batch open` panics in both the rocksdb and pebble batch code - to catch any case where we unintentionally change the parent `pebbleBatch`. Does this help?
</blockquote></details>

In `rocksDBBatch` we buffer mutations on the Go side via a `RocksDBBatchBuilder`. This is done to avoid Cgo crossings. But if we need to read from a batch, those mutations need to be flushed to C++. A series of `MVCCPut` calls would then result in buffering 1 or 2 mutations on the Go side, and then flushing those mutations to C++ in order to handle retrieval of the MVCC metadata that occurs as part of `MVCCPut`.

It is extremely common that a series of `MVCCPut` operations that occur within a `BatchRequest` are all to distinct keys. When that occurs, we do not need for the batch to read its own writes. That is what a distinct batch does. It allows buffering a set of mutations, and not flushing those buffered mutations when a read is performed.

With Pebble, we're not using a `RocksDBBatchBuilder` and none of this applies. We could actually get rid of all of this distinct stuff, but I think it is worthwhile to keep it around for now to make sure the semantics when using Pebble are exactly the same as when using RocksDB.

If there is still confusion here, I can draw it out on a whiteboard on Monday. My summary would be: distinct batches are an optimization to reduce Cgo transitions which is not necessary with Pebble.

**Comment by petermattis** [comment]
TFTR!

bors r=itsbilal

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41674)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr)

___
*[pkg/storage/engine/pebble_batch.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41674#-LrPUK8645UQHLuIvAq_:-LriU4MY0SOHsXhKchn7:b-9w7pzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/67dbac68880c62fc6af98756d583192c5cd2142e/pkg/storage/engine/pebble_batch.go#L314)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

In `rocksDBBatch` we buffer mutations on the Go side via a `RocksDBBatchBuilder`. This is done to avoid Cgo crossings. But if we need to read from a batch, those mutations need to be flushed to C++. A series of `MVCCPut` calls would then result in buffering 1 or 2 mutations on the Go side, and then flushing those mutations to C++ in order to handle retrieval of the MVCC metadata that occurs as part of `MVCCPut`.

It is extremely common that a series of `MVCCPut` operations that occur within a `BatchRequest` are all to distinct keys. When that occurs, we do not need for the batch to read its own writes. That is what a distinct batch does. It allows buffering a set of mutations, and not flushing those buffered mutations when a read is performed.

With Pebble, we're not using a `RocksDBBatchBuilder` and none of this applies. We could actually get rid of all of this distinct stuff, but I think it is worthwhile to keep it around for now to make sure the semantics when using Pebble are exactly the same as when using RocksDB.

If there is still confusion here, I can draw it out on a whiteboard on Monday. My summary would be: distinct batches are an optimization to reduce Cgo transitions which is not necessary with Pebble.
</blockquote></details>

The conversation this morning, and these replies really helped!
The code comment "In RocksDB, a distinct batch allows reading from a batch without flushing ..." was a bit confusing. IIUC, it "allows reading" because we know we don't need to read anything from the batch, so the fact that it has not been sent over to the C++ side is fine. A related question: will a `isDistinct` `pebbleBatch` ever have a `parentBatch.batch.IsIndexed()`? My assumption would be no since we know we don't need to do any reads of what is in the batch. Is that correct?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41674)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr)

___
*[pkg/storage/engine/pebble_batch.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41674#-LrPUK8645UQHLuIvAq_:-LriW3wK4vF5dVv-lEdM:b-r2zb56) ([raw file](https://github.com/cockroachdb/cockroach/blob/67dbac68880c62fc6af98756d583192c5cd2142e/pkg/storage/engine/pebble_batch.go#L314)):*
> A related question: will a isDistinct pebbleBatch ever have a parentBatch.batch.IsIndexed()? My assumption would be no since we know we don't need to do any reads of what is in the batch. Is that correct?

Yes, a `pebbleBatch` where `isDistinct == true` can have `parentBatch.batch.IsIndexed() == true`. This happens when we call `Distinct()` and the receiver is indexed. I believe this actually happens more frequently than the parent batch not be indexed. What benefit does distinct provide in this case with Pebble? None. Every write to the distinct batch is still getting indexed.

**Pull request merged**
