### PR TITLE
sqlsmith, tests: Compare result sets in TLP testing

### PR DESCRIPTION
**Pull request by nehageorge**
Previously, only the result counts of the unpartitioned
and partitioned TLP queries were compared. This was inadequate
because it allowed for different row values in the two result sets
to go undetected, as long as the row counts were the same.
To address this, the rows in the result sets are compared
directly to ensure they are the same, as expected.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
We might not get exactly the same results when they are FLOAT or DECIMAL. Unfortunately a query could in principle cast a FLOAT to STRING and then we'd have no idea that there are two acceptable string values..

**Comment by nehageorge** [comment]
@RaduBerinde Sorry I'm having trouble understanding which case you're talking about... Could you give an example of this?

**Comment by yuzefovich** [comment]
There is also `cmpconn.CompareConns` that executes the same query on multiple connections and then verifies that the results match. I wonder if we can refactor that function somehow and use it here.

**Comment by nehageorge** [comment]
@yuzefovich Seems doable if it were modified to execute different queries. I wonder if would be best to create a new function though, as modifying the behaviour seems like it would affect existing uses of `cmpconn.CompareConns`

**Comment by yuzefovich** [comment]
Yeah - I imagine we would like to extract out the common code that performs the matching between sets of results, and we would use it in `CompareConns` as well as in the TLP case.

**Comment by RaduBerinde** [comment]
For example aggregations: `SELECT SUM(f) FROM T` where `f` is `FLOAT`. If we execute this query as the sum of `SELECT SUM(f)` for different partitions, we may get slightly different floating point results.

**Comment by mgartner** [comment]
> For example aggregations: SELECT SUM(f) FROM T where f is FLOAT. If we execute this query as the sum of SELECT SUM(f) for different partitions, we may get slightly different floating point results.

Good point. We currently only do `min`, `max`, and `count` aggregations, which should be ok I think. We should definitely make note of this limitation though.

**Comment by nehageorge** [comment]
> > For example aggregations: SELECT SUM(f) FROM T where f is FLOAT. If we execute this query as the sum of SELECT SUM(f) for different partitions, we may get slightly different floating point results.
> 
> Good point. We currently only do `min`, `max`, and `count` aggregations, which should be ok I think. We should definitely make note of this limitation though.

Yep, I agree. Will be noted.

**Comment by nehageorge** [comment]
Looks like returns a `sql.Rows` object while `compareRows` (the helper function that `cmpcpnn.CompareConn` uses) takes in `pgx.Rows`. So the code isn't really reusable. Do we think it's worth it to rewrite the function fully for this purpose?

**Comment by yuzefovich** [comment]
Hm, I'm guessing that changing `runTLPQuery` method to operate with `pgx.Rows` should be doable since we use `cmpconn.CompareConns` in another roachtest (`tpcdsvec`). So I'd look into `roachtest/tests/tpcdsvec.go` for inspiration and see how we can adapt `roachtest/tests/tlp.go` to also use `cmpconn` package. I don't immediately see big obstacles, but I could be wrong.

**Comment by nehageorge** [comment]
> Hm, I'm guessing that changing `runTLPQuery` method to operate with `pgx.Rows` should be doable since we use `cmpconn.CompareConns` in another roachtest (`tpcdsvec`). So I'd look into `roachtest/tests/tpcdsvec.go` for inspiration and see how we can adapt `roachtest/tests/tlp.go` to also use `cmpconn` package. I don't immediately see big obstacles, but I could be wrong.

You're right. I think this would need significant enough refactoring in `roachtest/tests/tlp.go` that it's worth closing this PR and opening a new one. Closing this for now.

**Comment by mgartner** [comment]
FWIW, I'd be fine with this naive `::STRING` approach for now, as long as we have some reasonable confidence that it won't cause TLP false positives, which we can get be running TLP for a while and observing no failures are caused by it.

But using the `cmpconn` package seems like it would be more robust, so I think it's worth exploring.

**Comment by nehageorge** [comment]
> FWIW, I'd be fine with this naive `::STRING` approach for now, as long as we have some reasonable confidence that it won't cause TLP false positives, which we can get be running TLP for a while and observing no failures are caused by it.
> 
> But using the `cmpconn` package seems like it would be more robust, so I think it's worth exploring.

Yep, there is definitely reasonable confidence in that regard (we shouldn't see TLP failures with this PR). However I do see how Yahor's suggested approach would make for cleaner and more thorough code. I will explore this more next week and if it turns out to be fruitful, I'll put up a PR for it. Otherwise I'll reopen this PR for review.

**Pull request closed without merging**
