### PR TITLE
cherrypick-2.0: libroach: detect leaked iterators

### PR DESCRIPTION
**Pull request by petermattis**
And fix an iterator leak.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by petermattis** [comment]
Looks like I have to cherry-pick Nikhil's printf hygiene commit as well. Added that as another commit.

**Comment by benesch** [comment]
My commit broke the windows build so you might not want to include it.

**Comment by petermattis** [comment]
> My commit broke the windows build so you might not want to include it.

Well, without your commit everything breaks. I'll wait for you to get master fixed and then add your fix on to this PR.

**Comment by benesch** [comment]
Ha, sounds good.

**Comment by petermattis** [comment]
@benesch Ok, added your fix for the Windows build. 🤞

**Review by benesch — APPROVED** [review]
Seems to work!

**Pull request merged**
