### PR TITLE
multiregionccl: add zone config waiting for partitioned tables

### PR DESCRIPTION
**Pull request by pawalt**
Previously, wait-for-zone-configs could only wait on tables, meaning we
couldn't wait for zone config changes to apply to REGIONAL BY ROW
partitions. This PR adds a `partition-name` flag to allow users to wait
on a specific partition.

Release note: None

A future PR will extend the tracing to allow us to trace REGIONAL BY ROW queries, but those changes combined with these will likely be too large for a single PR.

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68444)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68444#-MgMJiBR8nRMMOQaMeMS:-MgMJiBR8nRMMOQaMeMT:b9ii43z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e62594112b0c6c189feae958035ba4a9030f5f2/pkg/ccl/multiregionccl/datadriven_test.go#L681)):*
> ```Go
> 
> 	var lookupKey roachpb.Key
> 	if !d.HasArg(partitionName) {
> ```

nit: return early if there's no `partitionName` arg so you can get rid of the else case here. 
___
*[pkg/testutils/serverutils/test_cluster_shim.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68444#-MgMFFI0CQoxXhkD2qvc:-MgMFFI0CQoxXhkD2qvd:b-a4h03q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e62594112b0c6c189feae958035ba4a9030f5f2/pkg/testutils/serverutils/test_cluster_shim.go#L197)):*
> ```Go
> 	// LookupTable returns the table descriptor for the specified database and
> 	// table names.
> 	LookupTable(database, table string) (catalog.TableDescriptor, error)
> ```

I don't think this should be an interface method on `TestClusterInterface`, mostly because Tables are a catalog concept and all the other interface methods here seem to be a function of the cluster/server. 

Looks like the only thing that `LookupTable` needs from the test cluster is an executor config. I'd recommend passing that into the function instead of making it a method on `TestCluster` below. 

As for where this should live, maybe we need a `testutils` file in the descs package which exposes a `LookupHydratedTableDescriptor`. I'm not sure, maybe @ajwerner might have a suggestion. 

Alternatively, considering there's only one use of this method right now, you could move it into the file that you're calling it from for now as well.

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68444)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/testutils/serverutils/test_cluster_shim.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68444#-MgMFFI0CQoxXhkD2qvc:-MgR9F4w98_Srtr_geBW:b-613zs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e62594112b0c6c189feae958035ba4a9030f5f2/pkg/testutils/serverutils/test_cluster_shim.go#L197)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think this should be an interface method on `TestClusterInterface`, mostly because Tables are a catalog concept and all the other interface methods here seem to be a function of the cluster/server. 

Looks like the only thing that `LookupTable` needs from the test cluster is an executor config. I'd recommend passing that into the function instead of making it a method on `TestCluster` below. 

As for where this should live, maybe we need a `testutils` file in the descs package which exposes a `LookupHydratedTableDescriptor`. I'm not sure, maybe @ajwerner might have a suggestion. 

Alternatively, considering there's only one use of this method right now, you could move it into the file that you're calling it from for now as well. 
</blockquote></details>

I've moved this to a helper function within the test file

**Review by arulajmani — APPROVED** [review]
:lgtm: once the comment is addressed. 

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68444#-:-Mgklzvf41y63wm97zfH:b-f9oswh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68444#-MgklMxgAg1IOsDK2oIl:-MgklMxgAg1IOsDK2oIm:btjy90p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7628c956c0915236bd5a9762a700795e58ae3fac/pkg/ccl/multiregionccl/datadriven_test.go#L290)):*
> ```Go
> 				// wrapped in a succeeds soon.
> 				if err := testutils.SucceedsSoonError(func() error {
> 					lookupKey, err := getRangeKeyForInput(t, d, ds.tc)
> ```

Any reason this is inside the succeeds soon? Can we pull it out so we fail quickly in case some arguments aren't provided?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68444)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @arulajmani)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68444#-MgklMxgAg1IOsDK2oIl:-Mgl4tdhDtkXsJQTWXbM:bdtw735) ([raw file](https://github.com/cockroachdb/cockroach/blob/7628c956c0915236bd5a9762a700795e58ae3fac/pkg/ccl/multiregionccl/datadriven_test.go#L290)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Any reason this is inside the succeeds soon? Can we pull it out so we fail quickly in case some arguments aren't provided?
</blockquote></details>

Good point; no reason why this should fail. I'll move it out.

**Comment by pawalt** [comment]
bors r=arulajmani

**Pull request merged**
