### PR TITLE
engine: propertly support batches containing only LogData

### PR DESCRIPTION
**Pull request by tbg**
Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

`s/propertly/properly/g` in the first commit message (which was admittedly my typo).

`TestRocksDBWALFileEmptyBatch` verifies that an empty batch does not result in a write to the log file. You could adapt that approach to verify that a batch containing only `LogData` does result in a write to the log file.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33122#-:-LTbu1Lx8NVyTSlHj-oi:brjqzpv)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/engine/engine_test.go, line 798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33122#-LTbtovaBLKN-FMlztQK:-LTbtovaBLKN-FMlztQL:b-oiqcob) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f814be7cbab10fd233436a1eafc50ab35e0375a/pkg/storage/engine/engine_test.go#L798)):*
> ```Go
> // accidentally make Commit a no-op (via an errant fast-path) when a batch
> // contained only LogData.
> func TestWCommitBatchLogData(t *testing.T) {
> ```

`s/TestWCommit/TestCommit/g`

**Review by tbg — COMMENTED** [review]
Good idea, done. Wanna give it another glance? I verified it fails as expected when I undo your change to `Empty()`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33122#-:-LTcF9-w901kTsRvYwFx:bvhrmiw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/engine/engine_test.go, line 798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33122#-LTbtovaBLKN-FMlztQK:-LTcF7a4D71d1bqvQYcq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f814be7cbab10fd233436a1eafc50ab35e0375a/pkg/storage/engine/engine_test.go#L798)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/TestWCommit/TestCommit/g`
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33122#-:-LTcFd5k7JeN_9bqe0Sk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
TFTR!

bors r=petermattis

**Comment by tbg** [comment]
Fixed whitespace.

bors r=petermattis

**Pull request merged**
