### PR TITLE
upgrades: try to repair catalog corruptions during upgrade

### LINKED ISSUE #85265: upgrades: make descriptor migrations more robust in the face of corruption
Particularly in the face of corrupt back-references. Invalid back-references should simply be removed automatically.

Jira issue: CRDB-18255

Epic CRDB-28665

### LINKED ISSUE #104425: catalog: update RunPostDeserializationChanges to fix common cases of orphaned jobs
We have seen more examples of corruption caused by https://github.com/cockroachdb/cockroach/issues/93010 (bug where the planner would autocommit incorrectly, without cleaning up schema change jobs).

So far we have been resolving them using manual descriptor surgery. We should be able to add an automatic repair step into RunPostDeserializationChanges so that anytime a descriptor is read, it will attempt to repair the problem if it is able to. This can be best-effort, since there are likely some cases that we can't fix automatically.

Jira issue: CRDB-28522

Epic CRDB-28665

### PR DESCRIPTION
**Pull request by postamar**
This change enhances the recently-added upgrade precondition check which
checks for catalog corruptions by trying to repair these automatically
when possible.

Fixes: #104425
Fixes: #85265

Release note (general change): upgrading the cluster version to a new
release will not only check for descriptor- and other catalog
corruptions but will attempt to repair some of them on a best-effort
basis. This should seamlessly get rid of all longstanding descriptor
back-reference corruptions, which typically don't manifest themselves
until a schema change or an upgrade are performed.

### CODE REVIEW

**Comment by postamar** [comment]
This is ready for review, I'll reconcile the conflicts around hardcoded OIDs before borsing.

**Review by fqazi — APPROVED** [review]
:lgtm: Great work, this really good!

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 16 of 16 files at r3, 4 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-:-NZaoIGW76aCp-1MBENH:b-wxendi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @knz, @postamar, and @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-NZamYN01elLObHkWcvw:-NZamYN11w2RJMq_fNwP:bbiemre) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d33e179cc1928ec7292b5642d2d66885a0a979/pkg/sql/sem/builtins/builtins.go#L5226)):*
> ```Go
> SELECT
> 	CASE corruption
> 	WHEN 'descriptor'
> ```

Maybe document the corruption types in the code, just to make things a bit cleaner.
___
*[`pkg/upgrade/upgrades/first_upgrade.go` line 139 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-NZanpAr3tmqBI2WQvI-:-NZanpAs3Y5maoVIRM7C:b-dlqxy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b28c87890b36f49f76c0cffba4e2f42d7d368ba/pkg/upgrade/upgrades/first_upgrade.go#L139)):*
> ```Go
> 	} else if hasRows {
> 		// Attempt to repair catalog corruptions.
> 		log.Info(ctx, "auto-repairing catalog corruptions detected during upgrade attempt")
> ```

From a diagnosability viewpoint, do you think logging which descriptors/corruption type is worth logging?  It might be helpful for customer scenarios where we didn't cover something.
___
*[`pkg/sql/logictest/testdata/logic_test/schema_repair` line 284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-NZamtYt2ViSwY6s6rh4:-NZamtYt2ViSwY6s6rh5:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d33e179cc1928ec7292b5642d2d66885a0a979/pkg/sql/logictest/testdata/logic_test/schema_repair#L284)):*
> ```
> SELECT * FROM "".crdb_internal.kv_repairable_catalog_corruptions ORDER BY 1,2,3,4
> ----
> 104  105  _corrupt_backref_typ  114    descriptor
> ```

Nice!

**Review by postamar — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-:-NZbE0SECRswe8ytfCBO:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @fqazi, @knz, and @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-NZamYN01elLObHkWcvw:-NZbE2We1j4fIuN6N42d:bk1prnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d33e179cc1928ec7292b5642d2d66885a0a979/pkg/sql/sem/builtins/builtins.go#L5226)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Maybe document the corruption types in the code, just to make things a bit cleaner.
</blockquote></details>

Done, in the vtable definition mostly.
___
*[`pkg/upgrade/upgrades/first_upgrade.go` line 139 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-NZanpAr3tmqBI2WQvI-:-NZbE5MaBkxgTu-vHC0Q:bjppaax) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b28c87890b36f49f76c0cffba4e2f42d7d368ba/pkg/upgrade/upgrades/first_upgrade.go#L139)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

From a diagnosability viewpoint, do you think logging which descriptors/corruption type is worth logging?  It might be helpful for customer scenarios where we didn't cover something.
</blockquote></details>

Good question. I'm worried there's a real possibility of there being too many of them. In fact, I should perform the repair in batches!
___
*[`pkg/sql/logictest/testdata/logic_test/schema_repair` line 284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-NZamtYt2ViSwY6s6rh4:-NZbEDtJCGq0Ca9wtbOd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d33e179cc1928ec7292b5642d2d66885a0a979/pkg/sql/logictest/testdata/logic_test/schema_repair#L284)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Done.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105832)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @knz, @postamar, and @rafiss)

___
*[`pkg/upgrade/upgrades/first_upgrade.go` line 139 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/105832#-NZanpAr3tmqBI2WQvI-:-NZbHg7sAUzs2KGhLMK1:bbwv80j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b28c87890b36f49f76c0cffba4e2f42d7d368ba/pkg/upgrade/upgrades/first_upgrade.go#L139)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Good question. I'm worried there's a real possibility of there being too many of them. In fact, I should perform the repair in batches!
</blockquote></details>

Batching here makes tons of sense. I guess we could limit that type of logging into a small number or the First N of these, but I'll leave that up to you.

**Comment by postamar** [comment]
I'll leave that for a later time, I think. 

bors r+

**Pull request merged**
