### PR TITLE
*: Add linter for license headers

### PR DESCRIPTION
**Pull request by bdarnell**
Update a few licenses that got missed. Standardize the language used
on the CCL side (javascript was using slightly different language).

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @petermattis)

___
*[pkg/testutils/lint/lint_test.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38114#-LgrhX7EDxKTeIdfaSMM:-LgrhX7EDxKTeIdfaSMN:b99na) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9fd14afa71174cef8b2965da52708b2aaf4d12/pkg/testutils/lint/lint_test.go#L156)):*
> ```Go
> // in the file licenses/BSL.txt and at www.mariadb.com/bsl11.
> //
> // Change Date: 2022-10-01
> ```

I must say having this change date baked into every file seems very annoying. We're going to have a full pass and each engineer needs to update their template twice a year... can this be avoided somehow by noting the change date in the BSL (or in an adjacent file)? I assume we're never going to have more than one change date in the codebase for a given SHA.

**Comment by tbg** [comment]
I'm just seeing that the change date is already in the license. Interesting that we need to duplicate it. Anyway I'm pretty sure that you wouldn't have duplicated if that wasn't necessary. Still wanted to double check.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38114#-:-LgxZO3uDxlqcKGW78eT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/testutils/lint/lint_test.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38114#-LgrhX7EDxKTeIdfaSMM:-LgxZ44O8-VwHtOxfLip:b5wbkxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9fd14afa71174cef8b2965da52708b2aaf4d12/pkg/testutils/lint/lint_test.go#L156)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I must say having this change date baked into every file seems very annoying. We're going to have a full pass and each engineer needs to update their template twice a year... can this be avoided somehow by noting the change date in the BSL (or in an adjacent file)? I assume we're never going to have more than one change date in the codebase for a given SHA.
</blockquote></details>

Can we have the change date updated by `goimports` or `crlfmt`? Then your template could potentially be `Change date: YYYY-MM-DD` and that gets auto-filled on save.

**Comment by bdarnell** [comment]
bors r=petermattis,tbg

Yeah, the change date is annoying but that's what MariaDB does. I'll check with the lawyers to see whether it's necessary. Either way, we'll automate it or eliminate it before the next time we have to change it.

**Pull request merged**
