### PR TITLE
sqlccl: set CSV table desc creation timestamp

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by vivekmenezes** [comment]
More accurately we should be using the timestamp used in the backup representation for each K:V as the ModificationTime for the table descriptor. Thoughts?

**Comment by mjibson** [comment]
We are. That walltime is plumbed through the entire creation process and is set as the backup descriptor time, KV MVCC time, and now the create table time.

**Comment by danhhz** [comment]
What's the context here?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18086#-:-KstkUi7koYmfek67AEn:b-gibgt8)*

**Comment by mjibson** [comment]
Added a link to the original issue and removed the TODO referencing this.

**Comment by mjibson** [comment]
https://github.com/cockroachdb/cockroach/pull/17378#issuecomment-320968079 contains just a bit more about this. Although it's unclear to us exactly why we need to set a timestamp (besides it being part of the function call).

**Comment by vivekmenezes** [comment]
LGTM

**Comment by danhhz** [comment]
> #17378 (comment) contains just a bit more about this. Although it's unclear to us exactly why we need to set a timestamp (besides it being part of the function call).

👍

**Pull request merged**
