### PR TITLE
opt: Add TryDecorrelateInnerJoin rule

### PR DESCRIPTION
**Pull request by andy-kimball**
TryDecorrelateInnerJoin tries to decorrelate an InnerJoin operator nested
beneath another Join operator by pulling up its join condition to the outer
join. This may be enough to decorrelate the outer join, or it may allow any
outer column references to continue to journey upwards.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-LGV7drI0ZBGbRLCG6Sc:-LGV7drI0ZBGbRLCG6Sd:bhq833v) ([raw file](https://github.com/cockroachdb/cockroach/blob/495f7f6cf88782076de623c9ccd4e27a1fefc6c0/pkg/sql/opt/norm/rules/decorrelate.opt#L153)):*
> ```
> # DetectCycle and HighPriority tags are in use.
> [TryDecorrelateInnerJoin, Normalize, DetectCycle, HighPriority]
> (InnerJoin | InnerJoinApply | LeftJoin | LeftJoinApply |
> ```

Do we want a symmetric rule for RightJoin/RightJoinApply?  Perhaps we should always build right joins as left joins (right joins would only show up in exploration)?

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-LGV7Cx890XnXejCAZgW:-LGV7Cx9AughoymBHbLe:b-68pvww) ([raw file](https://github.com/cockroachdb/cockroach/blob/495f7f6cf88782076de623c9ccd4e27a1fefc6c0/pkg/sql/opt/norm/rules/decorrelate.opt#L156)):*
> ```
>  SemiJoin | SemiJoinApply | AntiJoin | AntiJoinApply
>     $left:*
>     $right:* &
> ```

[nit] this is a little strange, we match * and then we also match `(InnerJoin | ...)`. Can't we do `$right: (InnerJoin ..) & (HasOuterCols ..)`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-:-LGV8XiYEP0JLtVyuEQ5:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-LGV80DL3TXNJESTG9f1:-LGV80DL3TXNJESTG9f2:b-n07is9) ([raw file](https://github.com/cockroachdb/cockroach/blob/495f7f6cf88782076de623c9ccd4e27a1fefc6c0/pkg/sql/opt/norm/rules/decorrelate.opt#L157)):*
> ```
>     $left:*
>     $right:* &
>         (HasOuterCols $right) &
> ```

Why don't you just match the rule on the Apply joins? Then you shouldn't need this check, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-:-LGV9zou1XpuS0AN_-Vo:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-LGV7drI0ZBGbRLCG6Sc:-LGVc1LhCCCBj2YcJh-K:b-am0rnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/495f7f6cf88782076de623c9ccd4e27a1fefc6c0/pkg/sql/opt/norm/rules/decorrelate.opt#L153)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we want a symmetric rule for RightJoin/RightJoinApply?  Perhaps we should always build right joins as left joins (right joins would only show up in exploration)?
</blockquote></details>

It's an interesting point, and we should continue to think about it. I'm going to hold off on the right join case for now, since it's so much less important (hard to even come up with test case for it without LATERAL support), but will add TODO for it.

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-LGV7Cx890XnXejCAZgW:-LGV_dGn3wLuRUl3NRms:bx6ub37) ([raw file](https://github.com/cockroachdb/cockroach/blob/495f7f6cf88782076de623c9ccd4e27a1fefc6c0/pkg/sql/opt/norm/rules/decorrelate.opt#L156)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this is a little strange, we match * and then we also match `(InnerJoin | ...)`. Can't we do `$right: (InnerJoin ..) & (HasOuterCols ..)`?
</blockquote></details>

The reason is that `HasOuterCols` is a quick check, and is also a very selective check. So I'd rather do that first, before bothering to match the child. It's a small thing, but will help a bit.

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-LGV80DL3TXNJESTG9f1:-LGV_skL1zJhpvRYqlwB:b7uqbow) ([raw file](https://github.com/cockroachdb/cockroach/blob/495f7f6cf88782076de623c9ccd4e27a1fefc6c0/pkg/sql/opt/norm/rules/decorrelate.opt#L157)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why don't you just match the rule on the Apply joins? Then you shouldn't need this check, right?
</blockquote></details>

The outer cols could reference variables outside the scope of the join, as with this query:
```
SELECT k
FROM a
WHERE EXISTS
(
    SELECT *
    FROM xy
    WHERE EXISTS
    (
        SELECT * FROM uv INNER JOIN uv AS uv2 ON uv2.u=k
    )
)
```
We don't handle this case too well, yet, but it illustrates a reference to a "grandfather join".

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27118)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27118#-LGV80DL3TXNJESTG9f1:-LGVjVBLCu_7x0S-9rOd:b-rfb863) ([raw file](https://github.com/cockroachdb/cockroach/blob/495f7f6cf88782076de623c9ccd4e27a1fefc6c0/pkg/sql/opt/norm/rules/decorrelate.opt#L157)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The outer cols could reference variables outside the scope of the join, as with this query:
```
SELECT k
FROM a
WHERE EXISTS
(
    SELECT *
    FROM xy
    WHERE EXISTS
    (
        SELECT * FROM uv INNER JOIN uv AS uv2 ON uv2.u=k
    )
)
```
We don't handle this case too well, yet, but it illustrates a reference to a "grandfather join".
</blockquote></details>

Ah got it - thanks for the explanation!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27118)*

**Pull request merged**
