### PR TITLE
opt: generate spans for IN filters

### PR DESCRIPTION
**Pull request by justinj**
This code is largely based off of makeSpansForTupleIn, though I wasn't
able to reuse much of it since the context is slightly different.

Also fix up a CREATE STATISTICS statement and modify a TPCC query.

Release note: None

### CODE REVIEW

**Comment by justinj** [comment]
@RaduBerinde I can rework this if you'd prefer we did non-tight single-col spans, I had the impression from the conversation that we settled on this approach but if you think single-cols would work better then I'm happy to change it.

**Comment by RaduBerinde** [comment]
The single composite span is ok for now. We can always go back and add single-col spans if we need that.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/constraint_builder.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEv6L2h8J_rlCbCEylb:-LEv6L2h8J_rlCbCEylc:b5nm6x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b447562e4b4d17c961d6fcf27a25363bc936fdd/pkg/sql/opt/memo/constraint_builder.go#L212)):*
> ```Go
> 			elem := val.Child(colIdxsInLHS[j])
> 			if !elem.IsConstValue() {
> 				return unconstrained, false
> ```

We may still be able to generate a constraint on other columns (e.g. `(a, b) IN ((1, x)) =>  a=1`. We should check this in the code where we decide which `cols` participate.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEv5MxlCKgIroAQ54rD:-LEv5MxlCKgIroAQ54rE:b-amtrip) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b447562e4b4d17c961d6fcf27a25363bc936fdd/pkg/sql/opt/memo/constraint_builder.go#L225)):*
> ```Go
> 		// constraints.
> 		if hasNull {
> 			continue
> ```

I think it's no longer tight in this case.
`(x, y) IN ((1, 2), (NULL, 4))` is not the same as `(x, y) IN ((1,2))`, the latter is `NULL` on (3,4)

At least not the way we define `tight` above. Maybe it's enough to say it's tight if it's true IFF the constraints are true. Maybe make it not tight here but add a TODO to revisit the definition of "tight".

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-:-LEv59PU9kvDXdaf-zhm:bbr4ih2)*

**Comment by justinj** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/constraint_builder.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEv6L2h8J_rlCbCEylb:-LEvJk4lCH6YMtWj2KgB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b447562e4b4d17c961d6fcf27a25363bc936fdd/pkg/sql/opt/memo/constraint_builder.go#L212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We may still be able to generate a constraint on other columns (e.g. `(a, b) IN ((1, x)) =>  a=1`. We should check this in the code where we decide which `cols` participate.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEv5MxlCKgIroAQ54rD:-LEvJl8q8vWGrNSV6V1Q:b-rp2lfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b447562e4b4d17c961d6fcf27a25363bc936fdd/pkg/sql/opt/memo/constraint_builder.go#L225)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think it's no longer tight in this case.
`(x, y) IN ((1, 2), (NULL, 4))` is not the same as `(x, y) IN ((1,2))`, the latter is `NULL` on (3,4)

At least not the way we define `tight` above. Maybe it's enough to say it's tight if it's true IFF the constraints are true. Maybe make it not tight here but add a TODO to revisit the definition of "tight".
</blockquote></details>

Ah, good call, I hadn't considered that distinction. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26708)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/constraint_builder.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEvS86u0YlYyqtAPN1n:-LEvS86u0YlYyqtAPN1o:b-1e16w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8a5854f90f3425cfc571095c8384213949678d7/pkg/sql/opt/memo/constraint_builder.go#L217)):*
> ```Go
> 			// If one of the LHS entries is not a bare column then our constraints
> 			// are no longer tight.
> 			tight = false
> ```

[nit] it's annoying to have to set this in two places, maybe just do `tight = (len(constrainedCols) == lhs.ChildCount())` after the loop.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEvSLvlCwyVhy9owIly:-LEvSLvlCwyVhy9owIlz:b-295029) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8a5854f90f3425cfc571095c8384213949678d7/pkg/sql/opt/memo/constraint_builder.go#L247)):*
> ```Go
> 			//   (x, y) IN ((1, 2), (NULL, 4))
> 			// is not the same as
> 			//   (x, y) IN ((1,2)),
> ```

[nit] `1, 2` so it matches the one above

---

*[pkg/sql/opt/memo/constraint_builder.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEvT2i2BC16nChmXHOg:-LEvT2i2BC16nChmXHOh:b-aaupdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8a5854f90f3425cfc571095c8384213949678d7/pkg/sql/opt/memo/constraint_builder.go#L255)):*
> ```Go
> 		key := constraint.MakeCompositeKey(vals...)
> 		sp.Init(key, constraint.IncludeBoundary, key, constraint.IncludeBoundary)
> 		c = c.Union(cb.evalCtx, constraint.SingleSpanConstraint(&keyCtx, &sp))
> ```

You could use `Spans` (like the single column IN does) and use `Spans.SortAndMerge` to avoid this being quadratic. Can just add a TODO though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-:-LEvTxyP2zfK6aYWq-Mx:bnfp4nl)*

**Comment by justinj** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/constraint_builder.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEvS86u0YlYyqtAPN1n:-LEyepJuCsf0ntaiydTJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8a5854f90f3425cfc571095c8384213949678d7/pkg/sql/opt/memo/constraint_builder.go#L217)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it's annoying to have to set this in two places, maybe just do `tight = (len(constrainedCols) == lhs.ChildCount())` after the loop.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEvSLvlCwyVhy9owIly:-LEyepf1CL1yhl-U8SiA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8a5854f90f3425cfc571095c8384213949678d7/pkg/sql/opt/memo/constraint_builder.go#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `1, 2` so it matches the one above
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEvT2i2BC16nChmXHOg:-LEyfw7R7DjrugANMXSB:b-7gm5ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8a5854f90f3425cfc571095c8384213949678d7/pkg/sql/opt/memo/constraint_builder.go#L255)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You could use `Spans` (like the single column IN does) and use `Spans.SortAndMerge` to avoid this being quadratic. Can just add a TODO though.
</blockquote></details>

Pretty straightforward change! Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26708)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-:-LEyk_ze20gRiRTDQfu6:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 470 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEyp61G1CiA6BgCyUbO:-LEyp61G1CiA6BgCyUbP:b1vnxx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a41086922a1c394630e7846926593945ec77283/pkg/sql/opt/exec/execbuilder/testdata/select_index#L470)):*
> ```
> ·          spans     /1/4-/1/5  ·       ·
> 
> # TODO(radu): in this case, we're not preferring abcd, unlike 2.0
> ```

NIT: Remove comment now that this is fixed.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEyqoBZ6Jsz2LsCTjqH:-LEyqoBZ6Jsz2LsCTjqI:bi3jh0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a41086922a1c394630e7846926593945ec77283/pkg/sql/opt/memo/constraint_builder.go#L193)):*
> ```Go
> 	constrainedCols := make([]opt.OrderingColumn, 0, lhs.ChildCount())
> 	colIdxsInLHS := make([]int, 0, lhs.ChildCount())
> 	for i, n := 0, lhs.ChildCount(); i < n; i++ {
> ```

What's the purpose of setting `n` rather than saying `i < lhs.ChildCount()`? My understanding is that Go will only evaluate `lhs.ChildCount()` once at the beginning of the loop, so I think just makes the code harder to understand without improving perf.

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 760 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEyqN6Z3m67ta53E5-J:-LEyqN6Z3m67ta53E5-K:bgy4kzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a41086922a1c394630e7846926593945ec77283/pkg/sql/opt/memo/testdata/logprops/constraints#L760)):*
> ```
>                 └── tuple [type=tuple{int, int}]
>                      ├── const: 5 [type=int]
>                      └── const: 100 [type=int]
> ```

What about test where RHS contains something that's not a Tuple?

Also, to make sure testing is complete, one thing I often do is deliberately introduce subtle bugs into different parts of the code I'm testing, and make sure that one of my tests fails.

---

*[pkg/sql/opt/xform/testdata/external/tpcc, line 604 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEysTE1E1sjzIZMFNuw:-LEysTE1E1sjzIZMFNux:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a41086922a1c394630e7846926593945ec77283/pkg/sql/opt/xform/testdata/external/tpcc#L604)):*
> ```
>  ├── prune: (1,3,8,14-17)
>  └── project
>       ├── columns: stock.s_i_id:1(int!null) stock.s_quantity:3(int) stock.s_dist_05:8(string) stock.s_ytd:14(int) stock.s_order_cnt:15(int) stock.s_remote_cnt:16(int) stock.s_data:17(string)
> ```

Nice.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-:-LEysXoA-H4M6FgIAJIH:bnfp4nl)*

**Comment by justinj** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/memo/constraint_builder.go, line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEyqoBZ6Jsz2LsCTjqH:-LEzN08o1XBf95yHCiOT:bd0lqpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a41086922a1c394630e7846926593945ec77283/pkg/sql/opt/memo/constraint_builder.go#L193)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What's the purpose of setting `n` rather than saying `i < lhs.ChildCount()`? My understanding is that Go will only evaluate `lhs.ChildCount()` once at the beginning of the loop, so I think just makes the code harder to understand without improving perf.
</blockquote></details>

We talked on slack - looking at the assembly it does look like it will re-evaluate `ChildCount` each time.

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 760 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26708#-LEyqN6Z3m67ta53E5-J:-LEzbNG05xubxgmuEw7f:bd6zikh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a41086922a1c394630e7846926593945ec77283/pkg/sql/opt/memo/testdata/logprops/constraints#L760)):*
I'm unclear on whether or not any such situations will get through typechecking, I actually tried to find one but couldn't, although postgres allows this (but we don't):
```
> SELECT (3, 50) IN ((1, 2), (select (3, 50)), (5, 100));
```
so I'll add a check for safety just in case this changes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26708)*

**Pull request merged**
