### PR TITLE
opt: do not build unnecessary assignment casts

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: refactor mutationBuilder.addAssignmentCasts

This commit refactors `mutationBuilder.AddAssignmentCasts` so that it
takes a list of target column IDs as input. This will allow the function
to be used more generally for adding assignment casts to DEFAULT columns,
computed columns, UPDATEs, and UPSERTs.

A number of column names changed in test opt trees because they are now
given unique metadata names. There is no semantic difference because of
this change.

Release note: None

#### opt: do not build unnecessary assignment casts

The optimizer no longer adds assignment casts for insert values if the
source column type is identical to the target column type. Also, the
EliminateCast rule has been removed because it is no longer necessary.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-:-Mr8RFMABrVSw0DSzPzw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

**Review by rharding6373 — APPROVED** [review]
Nice! I only have a couple of nits. :lgtm: 

> Reviewed 45 of 45 files at r1, 14 of 47 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-:-Mr8WV1Z9cWQmpwJQUWm:b-6wdpgc)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-Mr8N09UC1f2V5MEBCDf:-Mr8N09UC1f2V5MEBCDg:b82o461) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6805fd70ba09a7823365121b3b014108c433f65/pkg/sql/opt/exec/execbuilder/testdata/fk#L74)):*
> ```
>         │
>         └── • hash join (anti)
>             │ equality: (column11) = (p)
> ```

So this changed from a column named consistently with the table (`y`) to a generic column name (`column11). Is this consistent with the metadata changes? Just checking because the patterns different than most (but not all) other tests.

Also, would you be able to point me to where we decide column names? E.g., I noticed below there's one named `?column?` that was changed, and I'm curious how/why we have names like that and if it has any special meaning.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-Mr8ScKj8iNA_Xpc_x_4:-Mr8ScKj8iNA_Xpc_x_5:b-oroibe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6805fd70ba09a7823365121b3b014108c433f65/pkg/sql/opt/optbuilder/mutation_builder.go#L1399)):*
> ```Go
> // srcCols should be either insertColIDs, updateColIDs, or upsertColsIDs where
> // the length of srcCols is equal to the number of columns in the target table.
> // The columns in srcCols are updated with new column IDs TODO
> ```

nit: sentence seems incomplete.



_Code quote:_
```Go
The columns in srcCols are updated with new column IDs TODO
```

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73969)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-Mr8ScKj8iNA_Xpc_x_4:-Mr989e51VDM2pfuycmK:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6805fd70ba09a7823365121b3b014108c433f65/pkg/sql/opt/optbuilder/mutation_builder.go#L1399)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: sentence seems incomplete.
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-Mr8N09UC1f2V5MEBCDf:-Mr98RpODBA8fsZZGeCI:b1atv6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6805fd70ba09a7823365121b3b014108c433f65/pkg/sql/opt/exec/execbuilder/testdata/fk#L74)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

So this changed from a column named consistently with the table (`y`) to a generic column name (`column11). Is this consistent with the metadata changes? Just checking because the patterns different than most (but not all) other tests.

Also, would you be able to point me to where we decide column names? E.g., I noticed below there's one named `?column?` that was changed, and I'm curious how/why we have names like that and if it has any special meaning.
</blockquote></details>

In optbuilder we keep track of two names for each column - the reference name and the metadata name. The reference name is the name by which the column can be referenced in other expressions. For example, if we build a projection of a CHECK constraint expression, like `CHECK (a > 0)`, we use the reference name to resolve the column that `a` refers to. The reference name is not used after the optbuild phase: it has no effect on normalization or exploration. It's not even stored in the memo.

The metadata name is only used when printing opt expression trees, it has no semantic effect on the optimizer. We could change all metadata names to "asdf" and everything would still behave as expected, though the opt trees would certainly be more confusing.

This particular column metadata name changed from `y` to `column11` in the first commit for 2 reasons:

1.  `addAssignmentCast` previously used the metadata name of the casted column as-is when creating the assignment-cast result column. It now clears the metadata name: https://github.com/cockroachdb/cockroach/pull/73969/files#diff-d3e224320c1f00d30d0921131d5dd834bede47c74c10e27e769b214bcf58eb26R1438
2. (1) was motivated by the fact that [the call to `addAssignmentCasts` was moved](https://github.com/cockroachdb/cockroach/commit/acd4b0bf4be736acd2c343574519a1b74976baa6#diff-6d37709a596b5c8872ea2af91102e064ceddf7096bc6d50a456538c98ef9ce58) so that it was called after the name of the insert columns were set (notice the location of`inCol.name = scopeColName(tree.Name(mb.md.ColumnMeta(mb.targetColList[i]).Alias))`), which resulted in the insert VALUES columns having the same name as the target table columns and was confusing. I'd like to give insert VALUES columns more descriptive metadata names, which would unfortunately create another huge diff, but I think would be worth it. I'll save that for another PR.

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-Mr8N09UC1f2V5MEBCDf:-Mr9F7LI9PYKEza1dSNh:b-nwc9uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6805fd70ba09a7823365121b3b014108c433f65/pkg/sql/opt/exec/execbuilder/testdata/fk#L74)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

In optbuilder we keep track of two names for each column - the reference name and the metadata name. The reference name is the name by which the column can be referenced in other expressions. For example, if we build a projection of a CHECK constraint expression, like `CHECK (a > 0)`, we use the reference name to resolve the column that `a` refers to. The reference name is not used after the optbuild phase: it has no effect on normalization or exploration. It's not even stored in the memo.

The metadata name is only used when printing opt expression trees, it has no semantic effect on the optimizer. We could change all metadata names to "asdf" and everything would still behave as expected, though the opt trees would certainly be more confusing.

This particular column metadata name changed from `y` to `column11` in the first commit for 2 reasons:

1.  `addAssignmentCast` previously used the metadata name of the casted column as-is when creating the assignment-cast result column. It now clears the metadata name: https://github.com/cockroachdb/cockroach/pull/73969/files#diff-d3e224320c1f00d30d0921131d5dd834bede47c74c10e27e769b214bcf58eb26R1438
2. (1) was motivated by the fact that [the call to `addAssignmentCasts` was moved](https://github.com/cockroachdb/cockroach/commit/acd4b0bf4be736acd2c343574519a1b74976baa6#diff-6d37709a596b5c8872ea2af91102e064ceddf7096bc6d50a456538c98ef9ce58) so that it was called after the name of the insert columns were set (notice the location of`inCol.name = scopeColName(tree.Name(mb.md.ColumnMeta(mb.targetColList[i]).Alias))`), which resulted in the insert VALUES columns having the same name as the target table columns and was confusing. I'd like to give insert VALUES columns more descriptive metadata names, which would unfortunately create another huge diff, but I think would be worth it. I'll save that for another PR.
</blockquote></details>

Forgot to point you to where we decide column names. It happens in many different places: basically anywhere `scopeColumn.name` is set to a `scopeColumnName`. See https://github.com/cockroachdb/cockroach/blob/a121be591d3fe5f9db3199cc5c72f9eeac01cfe5/pkg/sql/opt/optbuilder/scope_column.go#L198-L280.

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73969#-Mr8N09UC1f2V5MEBCDf:-Mr9IIab54g3CrKDhVC3:b-v13a9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6805fd70ba09a7823365121b3b014108c433f65/pkg/sql/opt/exec/execbuilder/testdata/fk#L74)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Forgot to point you to where we decide column names. It happens in many different places: basically anywhere `scopeColumn.name` is set to a `scopeColumnName`. See https://github.com/cockroachdb/cockroach/blob/a121be591d3fe5f9db3199cc5c72f9eeac01cfe5/pkg/sql/opt/optbuilder/scope_column.go#L198-L280.
</blockquote></details>

One more thing to point out - changing a scopeColumn's metadata name only has an effect on the opt tree if the column has not yet been added to the metadata. If a scopeColumn has already been added to the metadata (which happens in tow places [here](https://github.com/cockroachdb/cockroach/blob/630d1420b71a2af275d98faa2ac2a78c69320d95/pkg/sql/opt/optbuilder/util.go#L203) and [here](https://github.com/cockroachdb/cockroach/blob/630d1420b71a2af275d98faa2ac2a78c69320d95/pkg/sql/opt/optbuilder/util.go#L217)) then changing the scopeColumn's metadata does not change the column name in the metadata and therefore does not affect the name of the column in an opt tree.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
