### PR TITLE
builtins: fix topological sort for SHOW CREATE ALL

### LINKED ISSUE #76077: sql: v21.2.4: show_create_all_tables_builtin failed. len(ids): 62 not equal to len(topologicallySortedIDs): 63
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/2988809625/?referrer=webhooks_plugin

Panic message:

>show_create_all_tables_builtin.go:142: show_create_all_tables_builtin failed. len(ids): 62 not equal to len(topologicallySortedIDs): 63
--
*errutil.leafError: show_create_all_tables_builtin failed. len(ids): 62 not equal to len(topologicallySortedIDs): 63 (1)
show_create_all_tables_builtin.go:142: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L141-L143 in pkg/sql/sem/builtins.getTopologicallySortedTableIDs
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/sem/builtins/generator_builtins.go#L1730-L1732 in pkg/sql/sem/builtins.(*showCreateAllTablesGenerator).Start
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/rowexec/project_set.go#L157-L159 in pkg/sql/rowexec.(*projectSetProcessor).nextInputRow
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/rowexec/project_set.go#L240-L242 in pkg/sql/rowexec.(*projectSetProcessor).Next
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/colexec/columnarizer.go#L221-L223 in pkg/sql/colexec.(*Columnarizer).Next
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/colflow/stats.go#L97-L99 in pkg/sql/colflow.(*batchInfoCollector).Next
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/colflow/flow_coordinator.go#L238-L240 in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/colexecerror/error.go#L90-L92 in pkg/sql/colexecerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/colflow/flow_coordinator.go#L242-L244 in pkg/sql/colflow.(*BatchFlowCoordinator).next
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/colflow/flow_coordinator.go#L281-L283 in pkg/sql/colflow.(*BatchFlowCoordinator).Run
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/colflow/vectorized_flow.go#L257-L259 in pkg/sql/colflow.(*vectorizedFlow).Run
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/distsql_running.go#L547-L549 in pkg/sql.(*DistSQLPlanner).Run
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/distsql_running.go#L1288-L1290 in pkg/sql.(*DistSQLPlanner).PlanAndRun
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor_exec.go#L1379-L1381 in pkg/sql.(*connExecutor).execWithDistSQLEngine
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor_exec.go#L1070-L1072 in pkg/sql.(*connExecutor).dispatchToExecutionEngine
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor_exec.go#L708-L710 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor_exec.go#L128-L130 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor.go#L1706-L1708 in pkg/sql.(*connExecutor).execCmd.func1
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor.go#L1708-L1710 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor.go#L1630-L1632 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/conn_executor.go#L669-L671 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/0c8df44947208da2f6234d2736e8ab6d3b0937c0/pkg/sql/pgwire/conn.go#L647-L649 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
/usr/local/go/src/runtime/asm_amd64.s#L1370-L1372 in runtime.goexit
</details>

```
pkg/sql/sem/builtins/show_create_all_tables_builtin.go in pkg/sql/sem/builtins.getTopologicallySortedTableIDs at line 142
pkg/sql/sem/builtins/generator_builtins.go in pkg/sql/sem/builtins.(*showCreateAllTablesGenerator).Start at line 1731
pkg/sql/rowexec/project_set.go in pkg/sql/rowexec.(*projectSetProcessor).nextInputRow at line 158
pkg/sql/rowexec/project_set.go in pkg/sql/rowexec.(*projectSetProcessor).Next at line 241
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 222
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 98
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 239
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 91
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 243
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 282
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 258
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 548
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1289
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1380
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1071
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 709
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 129
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1707
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1709
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1631
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 670
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 648
/usr/local/go/src/runtime/asm_amd64.s in runtime.goexit at line 1371
```

| Tag | Value |
|---|---|
| Cockroach Release | `v21.2.4` |
| Cockroach SHA: | 0c8df44947208da2f6234d2736e8ab6d3b0937c0 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | development |
| Command | start-single-node |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/76077

Release note (bug fix): Fixed an error that could sometimes happen when
sorting the output of the SHOW CREATE ALL TABLES command.

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin_test.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76639#-Mw0FHJkD4A14r9gI-hz:-Mw0FHJl4rgjDDOs6QGb:blj6ika) ([raw file](https://github.com/cockroachdb/cockroach/blob/7861c12face286021460be18a42968e8742a2b88/pkg/sql/sem/builtins/show_create_all_tables_builtin_test.go#L29)):*
> ```Go
> 
> 	ctx := context.Background()
> 	monitor := mon.NewMonitor(
> ```

nit: you can use `execinfra.NewTestMemMonitor`.

**Review by rafiss — COMMENTED** [review]
tftr!

bors r=otan

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76639#-:-Mw2YKT-E-XDam75P-Hx:bb8b2eb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin_test.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76639#-Mw0FHJkD4A14r9gI-hz:-Mw2YJYODc8uNZ9P8etY:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7861c12face286021460be18a42968e8742a2b88/pkg/sql/sem/builtins/show_create_all_tables_builtin_test.go#L29)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: you can use `execinfra.NewTestMemMonitor`.
</blockquote></details>

done

**Comment by yuzefovich** [comment]
My suggestion created an import cycle :/

bors r-

**Comment by rafiss** [comment]
> My suggestion created an import cycle :/

ah i didn't notice because using `./dev generate bazel` worked and i thought that would detect it.

**Comment by rafiss** [comment]
bors r=otan

**Comment by rafiss** [comment]
blathers backport 21.2

**Pull request merged**
