### PR TITLE
UI - Add Decommissioned node history page

### PR DESCRIPTION
**Pull request by koorosh**
- url path for new page is following: '**#/reports/nodes/history'**,
please let me know if it has to be changed to something more meaningful.
I decided to make it more generic in case we want to extend it with
other 'historical' content. Also, it is nested route under 'nodes' as it
belongs to this entity.
- this page is supposed to display the history of all decommissioned
nodes in one place;
- the logic of retrieving and displaying nodes are almost the same as
in Nodes Overview container with adjustments according to provided
designs;
- Redux selectors, and helper functions are refactored to external
utils module so it reduces code duplication;
- This PR does not expose any visual links on this page so users won't be 
able to navigate to it (will be added with next PR)

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
I'm assuming the release note is "None" because we don't link to this page yet

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-:-LwTsvMw10A0s7OqZX4j:b-4wqkn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Koorosh and @nathanstilwell)

___
*[pkg/ui/src/index.tsx, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwPkIgaAQG6CPxUwEmj:-LwPkIgbCDFLdYob_Hj2:b-yq85w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f93270644e1f63f1d2e6f9c4eae19295fae92/pkg/ui/src/index.tsx#L42)):*
> ```XML
> import NodeOverview from "src/views/cluster/containers/nodeOverview";
> import NodeLogs from "src/views/cluster/containers/nodeLogs";
> import DecommissionedNodeHistory from "src/views/reports/containers/nodesHistory/decommissionedNodeHistory";
> ```

This nesting feels too complex. What do you think of just keeping everything in the `nodes` directory?

If we keep it, can we rename the directory to `nodeHistory` instead of `nodesHistory`?
___
*[pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwPo9I3-ly_ME19KFb0:-LwPo9I3-ly_ME19KFb1:b-u2l3am) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f93270644e1f63f1d2e6f9c4eae19295fae92/pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx#L110)):*
> ```XML
>                   const deadTime = liveness.expiration.wall_time;
>                   const deadMoment = LongToMoment(deadTime);
>                   return `${moment.duration(deadMoment.diff(moment())).humanize()} ago`;
> ```

I think I saw somewhere that were trying to avoid vague time amounts like this. @piyush-singh can you comment?
___
*[pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwURu5m33Jqinct-_br:-LwURu5m33Jqinct-_bs:b-te55yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/807aa6b58426b2ddbfd3568ad36b342c226534ba/pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx#L66)):*
> ```XML
>     const { status, statuses, nodesSummary, sortSetting, setSort } = this.props;
>     if (!statuses || statuses.length === 0) {
>       return null;
> ```

I haven't seen the future commits yet but want to note that we should render a basic page with an empty list of decommissioned nodes instead of null. This is the base component of a route so it should have some basic visuals even if the data table is empty.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nathanstilwell, and @piyush-singh)

___
*[pkg/ui/src/index.tsx, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwPkIgaAQG6CPxUwEmj:-LwmLLQo13Lodo7VNn8M:b-tocsyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f93270644e1f63f1d2e6f9c4eae19295fae92/pkg/ui/src/index.tsx#L42)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This nesting feels too complex. What do you think of just keeping everything in the `nodes` directory?

If we keep it, can we rename the directory to `nodeHistory` instead of `nodesHistory`?
</blockquote></details>

Agree, 
- all `reports` containers are re-imported from top-level `index` file so it simplifies import statements in general;
- the directory is renamed to `nodeHistory`;
___
*[pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwPo9I3-ly_ME19KFb0:-LwmMvN05Vhaz-k-fiBW:b-8rbnx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f93270644e1f63f1d2e6f9c4eae19295fae92/pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx#L110)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think I saw somewhere that were trying to avoid vague time amounts like this. @piyush-singh can you comment?
</blockquote></details>

Yes, we have a dedicated task to eliminate relative time representations across entire Admin UI: https://github.com/cockroachdb/cockroach/issues/37019 (as the next step of UI redesign)
I propose to fix this within the scope of `37019` issue to have a generic solution on this instead of local fix.
___
*[pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwURu5m33Jqinct-_br:-LwmMAZf-JOssJBrgKyD:bhhkfdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/807aa6b58426b2ddbfd3568ad36b342c226534ba/pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx#L66)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I haven't seen the future commits yet but want to note that we should render a basic page with an empty list of decommissioned nodes instead of null. This is the base component of a route so it should have some basic visuals even if the data table is empty.
</blockquote></details>

You are correct, this logic was added in the latest commits.
Pagination and empty table behaviors can be found in the next PR: https://github.com/cockroachdb/cockroach/pull/42904

**Review by koorosh — COMMENTED** [review]
Updated release note in comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-:-LwmRSWI5tGlwgBtSLJW:bagzf27)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nathanstilwell, and @piyush-singh)

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nathanstilwell, and @piyush-singh)

___
*[pkg/ui/src/index.tsx, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwPkIgaAQG6CPxUwEmj:-Lx0XglU2UU5QmWQEHvd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f93270644e1f63f1d2e6f9c4eae19295fae92/pkg/ui/src/index.tsx#L42)):*
<details><summary><i>Previously, Koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Agree, 
- all `reports` containers are re-imported from top-level `index` file so it simplifies import statements in general;
- the directory is renamed to `nodeHistory`;
</blockquote></details>

Done.
___
*[pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwPo9I3-ly_ME19KFb0:-Lx0XltX2E4fDmnOD6yU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f93270644e1f63f1d2e6f9c4eae19295fae92/pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx#L110)):*
<details><summary><i>Previously, Koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Yes, we have a dedicated task to eliminate relative time representations across entire Admin UI: https://github.com/cockroachdb/cockroach/issues/37019 (as the next step of UI redesign)
I propose to fix this within the scope of `37019` issue to have a generic solution on this instead of local fix.

</blockquote></details>

Done.
___
*[pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42817#-LwURu5m33Jqinct-_br:-Lx0XkIB09tXli-XHCx7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/807aa6b58426b2ddbfd3568ad36b342c226534ba/pkg/ui/src/views/reports/containers/nodesHistory/decommissionedNodeHistory.tsx#L66)):*
<details><summary><i>Previously, Koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

You are correct, this logic was added in the latest commits.
Pagination and empty table behaviors can be found in the next PR: https://github.com/cockroachdb/cockroach/pull/42904
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
> Reviewed 1 of 7 files at r5, 4 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @nathanstilwell)

**Pull request merged**
