### PR TITLE
roachtest: Add a django testing framework and blacklist

### PR DESCRIPTION
**Pull request by rohany**
This PR creates a roachtest that runs a subset of the django tests
against cockroachdb, as well as performing a refactor of the python ORM
testing frameworks.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
This is still a WIP, as there are some things I'm unsure about. However, please review it and give pointers on what to fix / how to fix the todos

**Comment by yuzefovich** [comment]
I did a similar refactor while working go-pg: https://github.com/cockroachdb/cockroach/pull/41477/commits/30a06cbbd3715f166f3b27f04cb004117eb00e7d

**Comment by rohany** [comment]
Yeah i got the inspiration from that. I think that the parsing code for the java and python tests are slightly different, so I made a new struct.

**Comment by yuzefovich** [comment]
It looks to me that the struct is the same. I extracted that commit into a separate PR so that you could rebase on top of that. We should strive for unifying this infrastructure as much as possible and for DRY so that it is easier to maintain. If you need something extra in that struct, you should extend it.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rohany)

___
*[pkg/cmd/roachtest/django.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LqvzlrP3YSrGkl8vLpF:-LqvzlrP3YSrGkl8vLpG:brqoev4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8604f4c9a560672f6551b49ae1ad136c42ea8e2/pkg/cmd/roachtest/django.go#L187)):*
> ```Go
> 			version, blacklistName, ignoredlistName)
> 
> 		// TODO (rohany): should this be a file-backed buffer?
> ```

I guess it depends on the amount of output, right?

**Comment by rohany** [comment]
Alright, updated the PR using Yahor's test refactor. PTAL

**Review by yuzefovich — APPROVED** [review]
I left a bunch of nits, but it :lgtm:

> Reviewed 1 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-:-LrEpmqVAP3LWMr38CAA:b-inkgyh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @rohany)

___
*[pkg/cmd/roachtest/django.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEnVIo7fATZ8Iivand:-LrEmjor7PfQq3zfFGmB:bx7e43k) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L49)):*
> ```Go
> 		if err := repeatRunE(
> 			ctx, c, node, "update apt-get",
> 			`
> ```

[super nit]: seems like an extra newline.
___
*[pkg/cmd/roachtest/django.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEpvdj1Ei0q-bbToc9:-LrEpvdj1Ei0q-bbTocA:b-66vyaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L67)):*
> ```Go
> 
> 		// Set python3.6 as default.
> 		if err := repeatRunE(
> ```

[nit]: I think these comments are not particularly useful since they repeat the message from the command.
___
*[pkg/cmd/roachtest/django.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEnLrY0y9pGYH2TCTA:-LrEnLrY0y9pGYH2TCTB:b-e17jq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L72)):*
> ```Go
>     		sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
>     		sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2 
> 				sudo update-alternatives --config python3`,
> ```

[super nit]: the indentation is a little off.
___
*[pkg/cmd/roachtest/django.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEnRkx6QWQ8WvgXi35:-LrEnRkx6QWQ8WvgXi36:b-e17jq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L136)):*
> ```Go
> 			ctx, c, node, "install cockroach-django",
> 			`cd /mnt/data1/django/tests/cockroach-django/ && 
> 								pip3 install psycopg2-binary --user && pip3 install . --user`,
> ```

[super nit]: the indentation is a little off.
___
*[pkg/cmd/roachtest/django_blacklist.go, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEq0AS6Yb-iTusXBfE:-LrEq0AS6Yb-iTusXBfF:b-s2exng) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django_blacklist.go#L17)):*
> ```Go
> // in alphabetical order. As more progress is made adding compatibility,
> // more test apps should be added here to prevent against regression.
> var enabledDjangoTests = []string{
> ```

[nit]: (above) maybe `made with improving compatibility`? It feels like a word is missing in there.
___
*[pkg/cmd/roachtest/python_helpers.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEp5rnDqANaAiQlwfL:-LrEp5rnDqANaAiQlwfM:b-wlhm6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/python_helpers.go#L20)):*
> ```Go
> )
> 
> var pythonUnittestOutputRegex = regexp.MustCompile(`(?P<name>.*) \((?P<class>.*)\) \.\.\. (?P<result>[^ ']*)(?: u?['"](?P<reason>.*)['"])?`)
> ```

[nit]: `s/Unittest/UnitTest/g`.
___
*[pkg/cmd/roachtest/python_helpers.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEpDp12LLxJ7hwW_84:-LrEpDp12LLxJ7hwW_85:b-ksfj7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/python_helpers.go#L23)):*
> ```Go
> 
> func (r *ormTestsResults) parsePythonUnittestOutput(
> 	input []byte, ignoredList blacklist, expectedFailures blacklist,
> ```

[super nit]: I'd switch the order of ignore and black lists to keep it consistent with other functions.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41516)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @rohany)

___
*[pkg/cmd/roachtest/python_helpers.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEp5rnDqANaAiQlwfL:-LrEqLpN5S4imBHr3Z8D:b-b93680) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/python_helpers.go#L20)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/Unittest/UnitTest/g`.
</blockquote></details>

The empty comment was: `s/Unittest/UnitTest/g`.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41516)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @yuzefovich)

___
*[pkg/cmd/roachtest/django.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LqvzlrP3YSrGkl8vLpF:-LrErZXX0sHgzuP5AgM1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8604f4c9a560672f6551b49ae1ad136c42ea8e2/pkg/cmd/roachtest/django.go#L187)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I guess it depends on the amount of output, right?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/django.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEnVIo7fATZ8Iivand:-LrErBEC4IFIfrkYx4ty:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L49)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: seems like an extra newline.
</blockquote></details>

done
___
*[pkg/cmd/roachtest/django.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEpvdj1Ei0q-bbToc9:-LrErHQt4TPpY4Me80dL:b-n3z38x) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L67)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I think these comments are not particularly useful since they repeat the message from the command.
</blockquote></details>

yeah you're right.
___
*[pkg/cmd/roachtest/django.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEnLrY0y9pGYH2TCTA:-LrErRab7Sa_nsbb-fkX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L72)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: the indentation is a little off.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/django.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEnRkx6QWQ8WvgXi35:-LrErYau6R_ln107KCtG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django.go#L136)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: the indentation is a little off.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/django_blacklist.go, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEq0AS6Yb-iTusXBfE:-LrEsYqV7NhTx_FTy0NT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/django_blacklist.go#L17)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: (above) maybe `made with improving compatibility`? It feels like a word is missing in there.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/python_helpers.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEp5rnDqANaAiQlwfL:-LrEsdEXC9-PIOZ-ZRD5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/python_helpers.go#L20)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The empty comment was: `s/Unittest/UnitTest/g`.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/python_helpers.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41516#-LrEpDp12LLxJ7hwW_84:-LrEsom184RxhpWsEbgy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa1fbace43470ab1fb7a56c9af52d4dad8ab4a06/pkg/cmd/roachtest/python_helpers.go#L23)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: I'd switch the order of ignore and black lists to keep it consistent with other functions.
</blockquote></details>

Done.

**Pull request merged**
