### PR TITLE
sql/multitenancy: implement SHOW/CANCEL QUERIES/SESSIONS

### LINKED ISSUE #47895: sql: SHOW/CANCEL QUERIES/SESSIONS needs work for multi-tenancy
[See here for background](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#)

SHOW/CANCEL (and some others) uses the statusServer which is not available on a SQL tenant server. However, in phase 2, there's only ever at most one SQL tenant process running on behalf of a given tenant, meaning that all sessions and queries are available via the local node.

When running in a tenant process, the necessary information should thus be available (but is not, since the status server is not supplied). This can be fixed in a number of ways, the most desirable seemingly being to thin out the dependency on the status server interface to reflect only what's required of it, and injecting a "local-only" impl when starting up as a tenant server.

Similarly, when actually cancelling requests, this should call into the local process (since all queries/session are local).

Tenatively labeling this a blocker since there are many places that use the status server and this solution can fix all of them. The cumulative fallout of having none of them work may qualify as a blocker.

### PR DESCRIPTION
**Pull request by asubiotto**
This PR narrows down the StatusServer service into an interface used by SQL minus `Nodes` which remains in the `TenantDeprecatedWrapper` as a separate interface to discourage use of any other StatusServer methods. The narrowed-down interface is then implemented using a local-only `tenantStatusServer` which gives us the ability to SHOW/CANCEL QUERIES/SESSIONS.

Release note: None

Closes #47895

### CODE REVIEW

**Review by tbg — APPROVED** [review]
LGTM

Looks like you're catching a rebase and the linters are complaining, but on the plus side, it looks like you're getting away with the ccl import in the test!

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-:-MFZlCPsDHJiW6ARfqWc:blubkar)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @nvanbenschoten, and @tbg)

___
*[pkg/server/serverpb/status.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZf232BFh2Q2iz3BTj:-MFZf232BFh2Q2iz3BTk:b-bak5f5) ([raw file](https://github.com/cockroachdb/cockroach/blob/36730acd1e1678ad47480ee187d8a61d02cb4633/pkg/server/serverpb/status.go#L19)):*
> ```Go
> )
> 
> // SQLStatusServer is a smaller version of the serverpb.StatusInterface which
> ```

accidental deletion
___
*[pkg/server/serverpb/status.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZf7NnAPqtF0TcloA-:-MFZf7No38jdYaOf_RcK:b-kx2d0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/676884dc668e9893a3a30f4dabf8ff6a73e5c148/pkg/server/serverpb/status.go#L30)):*
> ```Go
> // inside the SQL subsystem. In practice, it is present on the system tenant,
> // and not present on "regular" tenants.
> type OptionalNodesStatusServer struct {
> ```

Does the "Nodes" refer to something in particular? Nodes as in KV nodes?
___
*[pkg/server/serverpb/status.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZk__i-eqer_VNHsll:-MFZk__i-eqer_VNHslm:b-p0gct7) ([raw file](https://github.com/cockroachdb/cockroach/blob/676884dc668e9893a3a30f4dabf8ff6a73e5c148/pkg/server/serverpb/status.go#L37)):*
> ```Go
> // OptionalNodesStatusServer. The provided server will be returned via
> // OptionalNodesStatusServer() if and only if it is not nil.
> func MakeOptionalNodesStatusServer(s StatusServer) OptionalNodesStatusServer {
> ```

Take a `NodesStatusServer` here.
___
*[pkg/sql/exec_util.go, line 1310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZkCax7vMmqdnwsLSW:-MFZkCax7vMmqdnwsLSX:bmkvimv) ([raw file](https://github.com/cockroachdb/cockroach/blob/676884dc668e9893a3a30f4dabf8ff6a73e5c148/pkg/sql/exec_util.go#L1310)):*
> ```Go
> 
> // CancelQuery looks up the associated query in the session registry and cancels it.
> func (r *SessionRegistry) CancelQuery(queryIDStr string, username string) (bool, error) {
> ```

Reminder to remove before merge.

**Review by asubiotto — COMMENTED** [review]
Rebased although I need to investigate a test failure and possibly update some newly added tests. @tbg Is this something we want to get in during the stability period or is it enough that this demonstrates how to add the CANCEL QUERY/SESSIONS and we can punt this until later. I guess this is a good example of different multitenancy feature needs.

cc @solongordon it would be nice if you could take a quick look since the rebase wasn't trivial and I extracted some functionality you added in #53291 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-:-MG4-ES9D23iScVk-GX8:bdhf9tx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/server/serverpb/status.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZf232BFh2Q2iz3BTj:-MG4-rGSEUOE4JY-mb_V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36730acd1e1678ad47480ee187d8a61d02cb4633/pkg/server/serverpb/status.go#L19)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

accidental deletion
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZf7NnAPqtF0TcloA-:-MG4-rw17gwQZfLVfs1b:b-coq9fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/676884dc668e9893a3a30f4dabf8ff6a73e5c148/pkg/server/serverpb/status.go#L30)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Does the "Nodes" refer to something in particular? Nodes as in KV nodes?
</blockquote></details>

Yeah, this RPC is to get KV node statuses.
___
*[pkg/server/serverpb/status.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZk__i-eqer_VNHsll:-MG40D_Y36UZdoY8HXzP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/676884dc668e9893a3a30f4dabf8ff6a73e5c148/pkg/server/serverpb/status.go#L37)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Take a `NodesStatusServer` here.
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 1310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-MFZkCax7vMmqdnwsLSW:-MG40GE7APcdV-L4RPLn:bw10jn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/676884dc668e9893a3a30f4dabf8ff6a73e5c148/pkg/sql/exec_util.go#L1310)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Reminder to remove before merge.
</blockquote></details>

Oops, done.

**Comment by tbg** [comment]
Were you planning to merge this? I would support that if possible. At the very least, we will want to backport it, but that seems to be more trouble than getting it in now.

**Comment by asubiotto** [comment]
I was waiting for your opinion since there's a bit more work to do re new tests, sorry if that wasn't clear. I'm on board with merging.

**Comment by tbg** [comment]
Oh sorry. Had slipped my radar.

**Review by solongordon — COMMENTED** [review]
Sorry @asubiotto, I rudely changed something out from under you yesterday. Would you please incorporate the changes from #53910 into your `checkCancelPrivilege` function? Other than that your privilege check refactors look good to me.

> Reviewed 4 of 20 files at r3, 2 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53211#-:-MGOdFy66xtK2CjlEpnv:b-mvh9v5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon and @tbg)

**Comment by asubiotto** [comment]
Rebased and added a small test fix. It was non-trivial to integrate tenant test cases into the permissions tests because of the lack of certificates and I decided it wasn't worth the effort to get these working with tenants. I'm not too concerned about this because the same privilege checking function is reused and tested during the system tenant tests.

Planning on merging this on green CI.

**Comment by asubiotto** [comment]
Seems like `acceptance/version-upgrade` is not happy:
```
e6ac9aa635f3> E200905 12:29:45.042258 687 util/log/crash_reporting.go:138 â‹® a panic has occurred!
job 587328990381899780: skipping: no liveness record for the job's node 4
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	/usr/local/go/src/runtime/panic.go:679
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:338
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).deprecatedMaybeAdoptJob
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/deprecated.go:200
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func7
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:657
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func10
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:742
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (3) job 587328990381899780: skipping: no liveness record for the job's node 4
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.leafError
```

Stressing locally but no repro so far. My first thought is that somehow I broke something with the `Nodes` refactor but nothing stands out to me. Won't be able to take a closer look until next week.

**Comment by tbg** [comment]
Pretty sure this is my pr. Will look on Tuesday

**Comment by tbg** [comment]
I take it back. My PR had not merged yet. @ajwerner mind taking a look? Btw the error message is already suspicious. At the time of writing, there's nothing that forces a liveness record to exist for every allocated NodeID (@irfansharif is about to change that though). The question is if this is an invariant that should still hold in this situation given that a job was created. That presumably presupposes being live at some point (meaning the record should be there). Not sure.
There's also https://github.com/cockroachdb/cockroach/issues/53972 which looks like it could be related.

**Comment by ajwerner** [comment]
> I take it back. My PR had not merged yet. @ajwerner mind taking a look? Btw the error message is already suspicious. At the time of writing, there's nothing that forces a liveness record to exist for every allocated NodeID (@irfansharif is about to change that though). The question is if this is an invariant that should still hold in this situation given that a job was created. That presumably presupposes being live at some point (meaning the record should be there). Not sure.


The assumption here is that if a node writes a job lease with its node ID that that ID is live. I think the place where we expect this invariant to be true now is before running SQL migrations. This one is interesting because it is not obviously new. @tbg do you think it's reasonable to add some code for system tenants to wait to be live (or at least to have written a liveness record) before starting sql migrations? 

> There's also #53972 which looks like it could be related.

Not related

**Comment by asubiotto** [comment]
It doesn't seem like this PR is somehow making it easier to hit this issue. I've been stressing `acceptance/version-upgrade` for hours without running into this and it seems like the failure has happened on master (#54082, #54079). Going to merge this and add it to the 20.2 backports meta-issue (#53662).

bors r=tbg

**Comment by tbg** [comment]
@ajwerner let's continue on https://github.com/cockroachdb/cockroach/issues/54079

**Pull request merged**
