### PR TITLE
sql/contention/txnidcache: avoid recording nil txnID

### LINKED ISSUE #77371: sql: txnID of the active txn not properly captured when connExecutor closes
Previously reported: 

https://github.com/cockroachdb/cockroach/issues/75994#issuecomment-1046523561

Jira issue: CRDB-13556

### PR DESCRIPTION
**Pull request by Azhng**
Resolves #77371

Previously, there are edge cases where the txnID in the resolvedTxnID
emitted from connExecutor will be nil, (e.g. when the connExecutor closes
while a transaction is still active). Writing invalid txnID into the
writer can potentially cause data loss, since the TxnID cache stops
processing the input batch when it encounters the first invalid txnID.
This commit prevents invalid txnID from being written into TxnID Cache.

Release justification: bug fix to existing functionality
Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Can you add tests for this case?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77502#-:-Mxf10Vf8JhxslEvrW7R:blpqcyg)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by Azhng** [comment]
Test added.

**Review by maryliag — APPROVED** [review]
Great :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77502#-:-Mxj4SNr3d3y-2ZP8VMC:br5kxoc)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by Azhng** [comment]
TFTR!

bors r=maryliag

**Pull request merged**
