### PR TITLE
opt, tree: window functions fixes in some edge cases

### LINKED ISSUE #43083: sql: a crash with window function with RANGE mode with offsets
Found with sqlsmith.

The reproduction:
```
CREATE TABLE IF NOT EXISTS seed AS
        SELECT
                g::INT2 AS _int2,
                g::INT4 AS _int4,
                g::INT8 AS _int8,
                g::FLOAT4 AS _float4,
                g::FLOAT8 AS _float8,
                '2001-01-01'::DATE + g AS _date,
                '2001-01-01'::TIMESTAMP + g * '1 day'::INTERVAL AS _timestamp,
                '2001-01-01'::TIMESTAMPTZ + g * '1 day'::INTERVAL AS _timestamptz,
                g * '1 day'::INTERVAL AS _interval,
                g % 2 = 1 AS _bool,
                g::DECIMAL AS _decimal,
                g::STRING AS _string,
                g::STRING::BYTES AS _bytes,
                substring('00000000-0000-0000-0000-' || g::STRING || '00000000000', 1, 36)::UUID AS _uuid,
                '0.0.0.0'::INET + g AS _inet,
                g::STRING::JSONB AS _jsonb
        FROM
                generate_series(1, 5) AS g;

CREATE TABLE table0 (col0 REGTYPE, col1 REGCLASS, col2 BIT(2), col3 INT4 NULL, col4 INTERVAL, col5 REGTYPE NOT NULL, col6 BIT(43), col7 DATE NOT NULL, col8 INT2 NULL, col9 VARCHAR NULL, col10 OID NOT NULL, col11 INT4 NOT NULL, col12 TIMETZ NOT NULL, PRIMARY KEY (col10, col7 ASC, col12), INDEX (col11 ASC, col0), INDEX (col10 DESC, col1,
col3, col9 DESC), INDEX (col12 ASC, col2 ASC, col8 DESC), UNIQUE (col0 DESC, col3 ASC, col12 DESC, col9, col1 ASC, col6, col10 ASC, col8 DESC, col2 ASC), INDEX (col8 ASC, col10 DESC, col1, col4 ASC, col7 DESC, col9, col12, col11, col0 DESC, col6 DESC), INDEX (col7 ASC, col4, col9, col0, col1 DESC, col2 ASC, col3 DESC, col11, col8, col12 DESC, col5, col6 DESC), UNIQUE
(col3, col2 DESC, col11 ASC, col7, col0 ASC, col12, col1, col9 DESC, col10), INDEX (col1 ASC, col0, col9 DESC, col12), INDEX (col10, col6 DESC, col0, col11 DESC, col1 ASC, col4, col7 ASC, col5 ASC, col12 DESC, col8 ASC, col3 ASC, col2, col9 ASC), FAMILY (col4, col9), FAMILY (col5, col2), FAMILY (col0, col11), FAMILY (col3, col6), FAMILY (col8, col1));CREATE TABLE table1 (col0 INT4 NULL, col1 DATE NOT NULL, col2 STRING NULL, col3 INT2, col4 UUID, col5 INET, col6 REGPROCEDURE NOT NULL, col7 REGPROCEDURE, col8 REGNAMESPACE, col9 TIMETZ NOT NULL, col10
TIME NULL, col11 BIT(46), col12 "char" NOT NULL, col13 STRING NOT NULL, col14 CHAR, col15 INT8 NOT NULL, col16 OID NOT NULL, PRIMARY KEY (col15 DESC, col12 DESC, col6, col1), INDEX (col16), INDEX (col0, col7, col15 DESC, col6, col4, col8, col16 ASC, col5 ASC, col3 DESC, col12 DESC, col9 DESC, col2 DESC, col11 ASC, col10 ASC, col1, col13 ASC, col14 ASC), FAMILY (col16), FAMILY (col3, col0, col5), FAMILY (col13, col4, col11, col10), FAMILY (col9, col14), FAMILY (col2), FAMILY (col7, col8));

SELECT
                min(tab_67548._timestamp::TIMESTAMP) OVER (PARTITION BY tab_67548._float8 ORDER BY tab_67548._timestamp ASC, tab_67548._float8 ASC)::TIMESTAMP
                        AS col_162250,
                min(tab_67548._uuid::UUID) OVER (PARTITION BY tab_67548._float8, tab_67548._uuid, tab_67548._timestamp)::UUID
                        AS col_162251,
                max(tab_67548._float8::FLOAT8) OVER (PARTITION BY tab_67548._timestamp, tab_67548._float8 ORDER BY tab_67548._float8 DESC RANGE BETWEEN pow(3.4028234663852886e+38:::FLOAT8::FLOAT8, 0.2906520102112073:::FLOAT8::FLOAT8)::FLOAT8 FOLLOWING AND 0.07386016697833764:::FLOAT8 FOLLOWING)::FLOAT8
                        AS col_162252
        FROM
                defaultdb.public.seed AS tab_67548
        GROUP BY
                tab_67548._uuid, tab_67548._timestamp, tab_67548._float8
        HAVING
                bool_or(tab_67548._bool::BOOL)::BOOL
        ORDER BY
                tab_67548._float8 DESC, tab_67548._float8 DESC
        LIMIT
                76:::INT8;
```

### PR DESCRIPTION
**Pull request by yuzefovich**
**opt: reconstruct simplified ordering in window functions in some cases**

Execution engine needs to know the index of the column from ORDER BY
clause in RANGE mode of framing when at least one of the bounds is
'offset PRECEDING' or 'offset FOLLOWING'. Previously, the ordering could
be simplified such that it no longer contained any columns (in case when
PARTITION BY clause also contained the same column). Now we store
additional information and reconstruct the ordering to keep the
execution engine happy.

Fixes: #43083.

Release note (bug fix): Previously, CockroachDB would crash when using
a window function with RANGE mode of framing with 'offset PRECEDING' or
'offset FOLLOWING' boundary such that the single column in ORDER BY
clause is also mentioned in PARTITION BY clause, and now this has been
fixed.

**sem/tree: fix window function utilities**

Previously, we would crash when trying to calculate the "physical"
boundary of the frame when the current value in the single column from
ORDER BY with RANGE mode of framing was NULL because we would attempt to
do something like 'NULL + 1` where `plus` binary operator assumed that
both sides were integers. This is fixed by returning NULL right away,
without performing binary operation.

Additionally, the boundaries of the window frame were not computed
correctly in case of `0 PRECEDING` or `0 FOLLOWING` due to incorrect
assumption that "preceding" cannot go past the current row and
"following" cannot go prior to the current row (both scenarios are
possible with zero offsets).

Release note (bug fix): Previously, CockroachDB could crash when
computing window functions with RANGE mode of framing when one of the
bounds was either of 'offset PRECEDING' or 'offset FOLLOWING' type when
there were NULL values in the single column from ORDER BY clause.
Additionally, also in RANGE mode bounds '0 PRECEDING' and '0 FOLLOWING'
could be handled incorrectly. Now this has been fixed.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44666)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 3626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CMywe11vPFOoEaV7b:-M-CMywe11vPFOoEaV7c:b8o2eer) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/logictest/testdata/logic_test/window#L3626)):*
> ```
> query R
> SELECT
> 	sum(a) OVER (
> ```

[nit] no tabs please
___
*[pkg/sql/opt/ops/relational.opt, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CN8UO3mc1YXCj3uVK:-M-CN8UO3mc1YXCj3uVL:b-cnx212) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/opt/ops/relational.opt#L843)):*
> ```
>     Ordering OrderingChoice
> 
>     # OrderingSimplificationProhibited indicates that Ordering is not allowed
> ```

This comment should explain more. I would actually love to understand exactly what is required. Can it not be simplified at all? Or can it be simplified as long as the simplified version is not empty?

I'm also wondering if we shouldn't remember the original ordering (for the purposes of passing it to execution) rather than disabling simplification.

In your example in the issue, what is `ORDER BY a` used for in execution? We know that all rows in the partition have the same `a` value, so how could it make a difference?
___
*[pkg/sql/opt/optbuilder/testdata/window, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CMtYU9RiAoUVEYL1U:-M-CMtYU9RiAoUVEYL1V:btoq6x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/opt/optbuilder/testdata/window#L1562)):*
> ```
> build
> SELECT
> 	sum(col8) OVER (
> ```

[nit] tabs

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44666)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 3626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CMywe11vPFOoEaV7b:-M-CP22b0Avtb-2XIcQG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/logictest/testdata/logic_test/window#L3626)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] no tabs please
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/relational.opt, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CN8UO3mc1YXCj3uVK:-M-CPgbw0UOVCJgODnYe:bvl3ms9) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/opt/ops/relational.opt#L843)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This comment should explain more. I would actually love to understand exactly what is required. Can it not be simplified at all? Or can it be simplified as long as the simplified version is not empty?

I'm also wondering if we shouldn't remember the original ordering (for the purposes of passing it to execution) rather than disabling simplification.

In your example in the issue, what is `ORDER BY a` used for in execution? We know that all rows in the partition have the same `a` value, so how could it make a difference?
</blockquote></details>

My bad, I forgot to include crucial detail - this is only required when one of the bounds contains `offset`. Execution needs to know the type of the single column from ORDER BY clause to know how to deserialize that offset and which binary operator to choose.
___
*[pkg/sql/opt/optbuilder/testdata/window, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CMtYU9RiAoUVEYL1U:-M-CPIJl0LGQXM7_HJeQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/opt/optbuilder/testdata/window#L1562)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] tabs
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44666)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @yuzefovich)

___
*[pkg/sql/opt/ops/relational.opt, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CN8UO3mc1YXCj3uVK:-M-CV21e0yhuPKASa2Ii:b-36j8xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/opt/ops/relational.opt#L843)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

My bad, I forgot to include crucial detail - this is only required when one of the bounds contains `offset`. Execution needs to know the type of the single column from ORDER BY clause to know how to deserialize that offset and which binary operator to choose.
</blockquote></details>

If it is only the case for a single column, and we only need its type, could we not just remember that type?

I'm trying to see if we can come up with something that is easier to reason about and doesn't disable a normalization rule (which seems a bit fragile).

**Review by andy-kimball — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44666)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/ops/relational.opt, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-M-CN8UO3mc1YXCj3uVK:-M-DSwos8CBakI3bWyJG:b-xxmky9) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c26444a8fd3beb71137bd1a679fe1c123bfc57/pkg/sql/opt/ops/relational.opt#L843)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If it is only the case for a single column, and we only need its type, could we not just remember that type?

I'm trying to see if we can come up with something that is easier to reason about and doesn't disable a normalization rule (which seems a bit fragile).
</blockquote></details>

I agree with Radu that this fix seems too specific for this one case, and too fragile. For example, say that some developer in the future added another rule that produced an empty ordering. You'd have to somehow know to disable that rule as well.

In terms of getting the type, couldn't you get it from one of the RANGE bounds rather than the ordering? An empty ordering (i.e. constant ordering) is an important special case that the execution code really should handle.

But, if we don't want to fix the execution code to handle constant orderings, we could add a rule to have the optimizer remove a RANGE `windows-item` when the ordering is empty (assuming that is correct in all situations?). So for example:
```
project
 └── window partition=(2)
      ├── scan ab
      └── windows
           └── windows-item: range from offset to current-row
                └── window-from-offset
                     ├── sum
                     │    └── variable: a
                     └── const: 1

```
=>
```
project
 └── window partition=(2)
      ├── scan ab
      └── windows
           └── sum
                └── variable: a
```

**Comment by yuzefovich** [comment]
Together with Andy we took a look at adding an optimizer rule to modify window frame so that offsets are omitted from it when the ordering is not empty. Unfortunately, this didn't quite work - we learned that depending on the value of offset and the bound type the frame can either be empty or contain all rows in the partition.

Then I tried to fix the issue purely from the execution side. This *almost* worked, but, unfortunately, not entirely - I learned that NULLs have to be handled differently. If a value is NULL in the ordering column (the ordinal of which the execution doesn't know due to already empty ordering at distsql physical planning stage), then the corresponding row is always in the frame. One could take a look at the logic test I added (I confirmed the output with Postgres).

So it seems like we have to somehow remember the ordinal index of the column in the optimizer before simplifying the ordering and tell that ordinal to execution. :sigh:

Any ideas?

**Comment by RaduBerinde** [comment]
I would try remembering the column in the operator and then "manufacturing" an ordering in the opt exec factory to keep execution happy.

What I'm still surprised about is that somehow a single column is special.. Don't we have the same problem (esp. with NULLs) if we partition and order by the same two columns?

**Comment by yuzefovich** [comment]
Could you please clarify what you mean by "in operator"?

The single ordering column is special because with `RANGE` mode with `offset` boundaries a single column must be present in `ORDER BY` clause. This allows us to compute "physical" boundaries of the frame using the binary search. For example, if we have a row `{100}` and frame as `RANGE BETWEEN 50 PRECEEDING AND 50 FOLLOWING`, then we know that the start of the "physical" frame will be rows in which value is `>= 100-50` and the end will be rows in which value is `<= 100+50`. If we don't order the data according to that single column, the frame could be non-continuous (i.e. it could have gaps). (By the way, this my understanding.)

Somewhat similarly, if we were to order the rows on two columns and kept a single offset value, then on which column the range should be? In theory we could introduce a variable-length number of offsets, for each of the columns in ordering, but we would be going from 1D space into a multidimensional, and window functions are too complex as they are already, so let's not go there :)

**Comment by RaduBerinde** [comment]
I see. I am suggesting that instead of adding `OrderingSimplificationProhibited` to the operator, we add a `RangeOffsetColumn opt.ColumnID` and we add a corresponding field to `exec.WindowInfo`. Then in `(*execFactory).ConstructWindow`, we use that column to manufacture an ordering if there isn't one already.

**Review by yuzefovich — COMMENTED** [review]
Implemented Radu's suggestion which fixed the crash. Also found another bug on the execution side. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-:-M-NP8sFEwNp21j4MTB5:b-ic3wgy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
Optimizer fix LGTM

Not familiar with the other code you fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-:-M-PL_x20vZRDxHsIIPu:bfei584)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Comment by yuzefovich** [comment]
Hm, I wrote the code in question year and a half ago and it hasn't been touched since. I guess @jordanlewis might have the most context on it. Could you please review the second commit?

**Comment by yuzefovich** [comment]
Friendly ping @jordanlewis.

**Comment by yuzefovich** [comment]
@asubiotto maybe you could take a look at the second commit?

**Review by asubiotto — APPROVED** [review]
Second commit :lgtm: 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44666#-:-M1kc9kxE2XZeL9Ayf_Z:bq42zbm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @RaduBerinde)

**Comment by yuzefovich** [comment]
TFTRs!

**Pull request merged**
