### PR TITLE
sql/catalog: avoid making copies of table descriptors

### LINKED ISSUE #121579: catalog: only clone descriptors when necessary
This came up in https://github.com/cockroachlabs/support/issues/2870: we do an unconditional clone of descriptor protos in `RunPostDeserializationChanges` - which is an unnecessary expense in cases where no changes are needed.

We should find a way to avoid cloning in those cases.

Jira issue: CRDB-37351

Epic CRDB-24134

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we would copy table descriptors even if no PostDeserialization changes would apply eagerly. This could lead to extra over head when accessing a large number of tables in the pg_catalog tables. To address this, this patch will make a copy only if we need to modify the original descriptor because of a post deserialization change.

Fixes: #121579

Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
I had a few suggestions to help with understanding the code, but otherwise the changes makes sense to me.

> Reviewed 1 of 1 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-:-O381qdE7DH1G9y0ZGL5:b-eqqxoo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @fqazi)

___
*[`pkg/sql/catalog/catprivilege/fix.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O382KXIDvexJtV0KjJm:-O382KXIDvexJtV0KjJn:bifqga8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/catprivilege/fix.go#L29)):*
> ```Go
> // dummyPrivilegeDescriptorBuilder implements PrivilegeDescriptorBuilder with
> // the assumption that the privilege descriptor is mutable.
> type dummyPrivilegeDescriptorBuilder struct {
> ```

nit: The term `dummy` suggests that it doesn’t actually do anything or is only used for testing purposes, at least that’s my impression. I believe we use it to fix actual descriptors, though it might be suboptimal in terms of memory allocations. Perhaps we could call it `SimplePrivilegeDescriptorBuilder`, or if we intend to eventually replace all uses of this builder and want to discourage new usage, maybe `DeprecatedPrivilegeDescriptorBuilder`.
___
*[`pkg/sql/catalog/catprivilege/fix.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O37xuih4dzGzb8Y5jlF:-O37xuih4dzGzb8Y5jlG:b-w0i8wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/catprivilege/fix.go#L34)):*
> ```Go
> 
> // GetLatestPrivilege implements PrivilegeDescriptorBuilder.
> func (d dummyPrivilegeDescriptorBuilder) GetLatestPrivilege() *catpb.PrivilegeDescriptor {
> ```

nit: I find it odd that `GetLatest...` may not be the most recent if a change was made to the descriptor returned from `GetMutable...`. Perhaps a better name is `GetReadOnlyPrivilege()`?
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 946 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O380CjIDwPXcWMA4C78:-O380CjIDwPXcWMA4C79:bnzfth6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/tabledesc/table_desc_builder.go#L946)):*
> ```Go
> 		if len(s) < len(ref.ColumnIDs) {
> 			d = builder.getOrInitModifiedDesc()
> 			ref.ColumnIDs = s
> ```

Do we need to update `ref`? I think it still points to something in the read-only version of the descriptor
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 955 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O380NBT3gmK5oh9YcxG:-O380NBT3gmK5oh9YcxH:bcyy3y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/tabledesc/table_desc_builder.go#L955)):*
> ```Go
> 		if s := cleanedIDs(col.UsesSequenceIds); len(s) < len(col.UsesSequenceIds) {
> 			d = builder.getOrInitModifiedDesc()
> 			col.UsesSequenceIds = s
> ```

Same comment here but for `col`.
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 960 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O380Tlo8tM3WvLvRMJ1:-O380Tlo8tM3WvLvRMJ2:b-f9lb0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/tabledesc/table_desc_builder.go#L960)):*
> ```Go
> 		if s := cleanedIDs(col.OwnsSequenceIds); len(s) < len(col.OwnsSequenceIds) {
> 			d = builder.getOrInitModifiedDesc()
> 			col.OwnsSequenceIds = s
> ```

Same comment here
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 988 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O380tDNBg5dZUdWZrJ4:-O380tDNBg5dZUdWZrJ5:b-uxk4bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/tabledesc/table_desc_builder.go#L988)):*
> ```Go
> 		if !mutationIDs.Contains(int(backref.MutationID)) {
> 			tbl = builder.getOrInitModifiedDesc()
> 			hasChanged = true
> ```

nit: could we break out of the loop once we set `tbl`?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127028)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @spilchen)

___
*[`pkg/sql/catalog/catprivilege/fix.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O382KXIDvexJtV0KjJm:-O39AN4qByQDosbqNy1R:b-66oz06) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/catprivilege/fix.go#L29)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: The term `dummy` suggests that it doesn’t actually do anything or is only used for testing purposes, at least that’s my impression. I believe we use it to fix actual descriptors, though it might be suboptimal in terms of memory allocations. Perhaps we could call it `SimplePrivilegeDescriptorBuilder`, or if we intend to eventually replace all uses of this builder and want to discourage new usage, maybe `DeprecatedPrivilegeDescriptorBuilder`.
</blockquote></details>

Done.

Renamed to `SimplePrivilegeDescriptorBuilder`, and hopefully we will just remove it in future PRs.
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 946 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O380CjIDwPXcWMA4C78:-O39ASgP1XtRGcbVlmpD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/tabledesc/table_desc_builder.go#L946)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do we need to update `ref`? I think it still points to something in the read-only version of the descriptor
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 955 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O380NBT3gmK5oh9YcxG:-O39AT4h0dW7SxRykQM8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/tabledesc/table_desc_builder.go#L955)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Same comment here but for `col`.
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 960 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O380Tlo8tM3WvLvRMJ1:-O39AUYc49eMPJp7iAmG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1537a487168331c81566ca20d7da7bc78b5661/pkg/sql/catalog/tabledesc/table_desc_builder.go#L960)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Same comment here
</blockquote></details>

Done.

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-:-O3AOKY860FMMHzkl7Hy:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Review by spilchen — APPROVED** [review]
I took another pass since you found a few more cases. It looks good to me, just had a few minor suggestions.

> Reviewed 3 of 6 files at r7, 3 of 4 files at r8, 1 of 2 files at r9, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-:-O3Hp-Ub7hy7Mpb97zzM:b-7braka)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @fqazi)

___
*[`pkg/sql/catalog/catprivilege/fix.go` line 114 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O3HmWYC7pr9qDxRgtVa:-O3HmWYC7pr9qDxRgtVb:bxjpcig) ([raw file](https://github.com/cockroachdb/cockroach/blob/f79765561b60578fa3316f565788b5d841545cfb/pkg/sql/catalog/catprivilege/fix.go#L114)):*
> ```Go
> 			} else {
> 				privs, _ = reader.GetMutablePrivilege().FindUser(user)
> 				privs.Privileges = allowedPrivilegesBits
> ```

Could you check if `oldPrivilegeBits != allowedPrivilegesBits` before calling `GetMutablePrivilege`? Not sure how common that will be to make a difference though.
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 120 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O3HnpPx034v4L_BAW2R:-O3HnpPx034v4L_BAW2S:bqpsai7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f79765561b60578fa3316f565788b5d841545cfb/pkg/sql/catalog/tabledesc/table_desc_builder.go#L120)):*
> ```Go
> 	// Set the ModificationTime field before doing anything else.
> 	// Other changes may depend on it.
> 	mustSetModTime, err := descpb.MustSetModificationTime(
> ```

nit: maybe have a comment that says the error will be handled later via another call to `MustSetModificationTime` in a code path that can deal with errors.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127028)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @spilchen)

___
*[`pkg/sql/catalog/catprivilege/fix.go` line 114 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/127028#-O3HmWYC7pr9qDxRgtVa:-O3JbqTs5DYRpExUa4Kf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f79765561b60578fa3316f565788b5d841545cfb/pkg/sql/catalog/catprivilege/fix.go#L114)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Could you check if `oldPrivilegeBits != allowedPrivilegesBits` before calling `GetMutablePrivilege`? Not sure how common that will be to make a difference though.
</blockquote></details>

Done.

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Pull request merged**
