### PR TITLE
roachtest: run clearrange without downloading data

### PR DESCRIPTION
**Pull request by tbg**
This test failed all the time due to a timeout downloading the store dumps.
Granted, 90 minutes to download 2TB is asking for 370 MBps which isn't
nothing, but it's better to rely on the local infra anyway as that
trivially translates to other platforms and also gives us an incentive to
make it better.

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-:-LXdiLVnC4S3PRqHKqyW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz, @petermattis, and @tbg)

___
*[pkg/cmd/roachtest/clearrange.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-LXdhWx1CenDUHu2MKiu:-LXdhWx206_OhbBd1Xck:b6wbt0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0fb121252b239aef36efd7fb544275d9264688/pkg/cmd/roachtest/clearrange.go#L47)):*
> ```Go
> 		// Use ZFS so the data directories can instantly be rolled back to
> 		// their pristine state. Useful for iterating quickly on the test.
> 		// c.Reformat(ctx, c.All(), "zfs")
> ```

Intentional?
___
*[pkg/cmd/roachtest/clearrange.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-LXdhY0m7HSy1Bz0fkT7:-LXdhY0m7HSy1Bz0fkT8:b6wbt0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0fb121252b239aef36efd7fb544275d9264688/pkg/cmd/roachtest/clearrange.go#L54)):*
> ```Go
> 		// NB: on a 10 node cluster, this should take well below 3h.
> 		c.Run(ctx, c.Node(1), "./cockroach", "workload", "fixtures", "import", "bank",
> 			//"--payload-bytes=10240", "--ranges=10", "--rows=65104166", "--seed=4")
> ```

Intentional?
___
*[pkg/cmd/roachtest/clearrange.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-LXdhxiU4xccxKlGkxHh:-LXdhxiU4xccxKlGkxHi:b2phf5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0fb121252b239aef36efd7fb544275d9264688/pkg/cmd/roachtest/clearrange.go#L56)):*
> ```Go
> 			//"--payload-bytes=10240", "--ranges=10", "--rows=65104166", "--seed=4")
> 			"--payload-bytes=10240", "--ranges=10", "--rows=651", "--seed=4")
> 		// Work around a limitation in `cockroach fixtures import` that can't rename the database.
> ```

`fixtures import <...> --db=bigbank` doesn't work?
___
*[pkg/cmd/roachtest/clearrange.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-LXdiAlM5N9Q42slNCF-:-LXdiAlM5N9Q42slNCF0:b6wbt0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0fb121252b239aef36efd7fb544275d9264688/pkg/cmd/roachtest/clearrange.go#L61)):*
> ```Go
> 		t.Status()
> 
> 		// c.Run(ctx, c.All(), "test -e /sbin/zfs && sudo zfs snapshot data1@pristine")
> ```

Intentional?

**Review by tbg — COMMENTED** [review]
Thanks for catching all of this gunk, should've given this another look before pushing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-:-LY2-bJ71jZNBWt-0_al:b8y9kym)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @petermattis)

___
*[pkg/cmd/roachtest/clearrange.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-LXdhxiU4xccxKlGkxHh:-LY2-XWZBFPfRkv-w-R1:b9dyz7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0fb121252b239aef36efd7fb544275d9264688/pkg/cmd/roachtest/clearrange.go#L56)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

`fixtures import <...> --db=bigbank` doesn't work?
</blockquote></details>

```
./cockroach workload fixtures import --db xxx
...
Error: unknown flag: --db
```

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34490)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/cmd/roachtest/clearrange.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-LXdhxiU4xccxKlGkxHh:-LY2VkKh4Wlb2kF7XRVC:bxoixtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0fb121252b239aef36efd7fb544275d9264688/pkg/cmd/roachtest/clearrange.go#L56)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

```
./cockroach workload fixtures import --db xxx
...
Error: unknown flag: --db
```
</blockquote></details>

The --db flag is only defined on the generator subcommand so you're missing a "tpcc" (sounds like this structure is confusing though. I've wondering a few times if I should have put the generator name before the action)

```
./cockroach workload fixtures import tpcc --db foo
```

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=danhhz

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-:-LYRUN2S4RR9aDANql6C:b-vwgs12)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @petermattis)

___
*[pkg/cmd/roachtest/clearrange.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34490#-LXdhxiU4xccxKlGkxHh:-LYRTzs77moGKQ5-U8Nk:b-71z941) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0fb121252b239aef36efd7fb544275d9264688/pkg/cmd/roachtest/clearrange.go#L56)):*
> sounds like this structure is confusing though. I've wondering a few times if I should have put the generator name before the action

No, I was just being sloppy. Thanks for the heads up, worked like a charm.

**Pull request merged**
