### PR TITLE
roachtest: allow test registration to use flags

### LINKED ISSUE #24461: roachtest: parse flags before registering tests
Tests currently register themselves in `init()` functions and thus do so before flags have been parsed. This is error prone as it is easy to use the `local` var (controlled by the `--local` flag) before it has been parsed. One option is to centralize test registration in `main()` and perform the registration after flags have been parsed. There might be other options as well.

### PR DESCRIPTION
**Pull request by petermattis**
Add a central `registerTests` function to register tests just before
execution. This allows tests registration to utilize command line
flags. `registerTests` is automatically constructed by looking for
global functions with the signature `register*(*registry)`.

Fixes #24461

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
I only converted the tests in `kv.go`. If this looks good, I'll convert the other tests.

**Comment by tschottdorf** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/cmd/roachtest/kv.go, line 60 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-L9MjCyg3m9cnMqPEnVm:-L9MjCyg3m9cnMqPEnVn:b-gamhbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8044a759c2546acbb63e1a2d30c944db5ead538d/pkg/cmd/roachtest/kv.go#L60)):*
> ```Go
> }
> 
> func registerKVSplits(r *registry) {
> ```

Could you just leave this as `init()` and instead use the pattern


```go
Register(func(r *registry) testSpec {
  return testSpec{ ... }
})
```

Having to pass a closure into `Register` is not great, but neither is this `go generate` workaround -- it's super magical and having to `go generate` is always a bad thing because it will be forgotten and caught in CI, which is a drag.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/roachtest/kv.go, line 60 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-L9MjCyg3m9cnMqPEnVm:-L9Q6tXREV_Ot0VpUl7O:btj9wby) ([raw file](https://github.com/cockroachdb/cockroach/blob/8044a759c2546acbb63e1a2d30c944db5ead538d/pkg/cmd/roachtest/kv.go#L60)):*
Thanks for the feedback. This is exactly what I was looking for.

Having each registration function return a single test-spec could be a bit awkward as we have some tests which register a few variants. I suppose we could return a slice or call `r.Add`. Practically, this would look like:

```
func init() {
  Register(func(r *registry) {
    r.Add(testSpec{...})
    r.Add(testSpec{...})
  })
}
```

This is more obvious in some ways, though I'm mildly worried that folks will still use flags outside of the registration function.

> Having to pass a closure into Register is not great, but neither is this go generate workaround -- it's super magical and having to go generate is always a bad thing because it will be forgotten and caught in CI, which is a drag.

If you forget to run `go generate`, your test will not be registered which I'm hoping you would notice before CI. Think of the `go generate` as convenience. Another option would be to manually add registration functions to `registry.go`. I'd be fine with that as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530)*

**Comment by danhhz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/roachtest/kv.go, line 60 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-L9MjCyg3m9cnMqPEnVm:-L9QRZWWE92J0HE6uQYy:b-r3hueq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8044a759c2546acbb63e1a2d30c944db5ead538d/pkg/cmd/roachtest/kv.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Thanks for the feedback. This is exactly what I was looking for.

Having each registration function return a single test-spec could be a bit awkward as we have some tests which register a few variants. I suppose we could return a slice or call `r.Add`. Practically, this would look like:

```
func init() {
  Register(func(r *registry) {
    r.Add(testSpec{...})
    r.Add(testSpec{...})
  })
}
```

This is more obvious in some ways, though I'm mildly worried that folks will still use flags outside of the registration function.

> Having to pass a closure into Register is not great, but neither is this go generate workaround -- it's super magical and having to go generate is always a bad thing because it will be forgotten and caught in CI, which is a drag.

If you forget to run `go generate`, your test will not be registered which I'm hoping you would notice before CI. Think of the `go generate` as convenience. Another option would be to manually add registration functions to `registry.go`. I'd be fine with that as well.
</blockquote></details>

My main feedback is that I think we should avoid a go generate solution if at all possible.

Secondarily, I still like the strawman I proposed in https://beta.reviewable.io/reviews/cockroachdb/cockroach/22282#-L4DxuU1S2BFkBRwX0Ux

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cmd/roachtest/kv.go, line 60 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-L9MjCyg3m9cnMqPEnVm:-L9QSyQ38mEBV285JN2n:bxncmrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8044a759c2546acbb63e1a2d30c944db5ead538d/pkg/cmd/roachtest/kv.go#L60)):*
@danhhz I'm not seeing how your strawman proposal would fit in here. The problem to address is that we want tests to be registered after flags have been parsed. Am I missing something?

> My main feedback is that I think we should avoid a go generate solution if at all possible.

Ok. I pushed another commit which makes the process manual. I could reintroduced using a per-file `init()` function, but see my comment above about how that opens the window to accidentally using flags before they are parsed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530)*

**Comment by danhhz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cmd/roachtest/kv.go, line 60 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-L9MjCyg3m9cnMqPEnVm:-L9QVnUa5_UfFLLgbMGc:b-swz7eo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8044a759c2546acbb63e1a2d30c944db5ead538d/pkg/cmd/roachtest/kv.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@danhhz I'm not seeing how your strawman proposal would fit in here. The problem to address is that we want tests to be registered after flags have been parsed. Am I missing something?

> My main feedback is that I think we should avoid a go generate solution if at all possible.

Ok. I pushed another commit which makes the process manual. I could reintroduced using a per-file `init()` function, but see my comment above about how that opens the window to accidentally using flags before they are parsed.
</blockquote></details>

Oh, I said that assuming that the only reason that you wanted flags was for selecting which tests would be run. I just read the issue linked in the commit message, apologies for the hasty assumption

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cmd/roachtest/kv.go, line 60 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-L9MjCyg3m9cnMqPEnVm:-L9QXjfpAvLvSrNttLvB:bsrh9h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8044a759c2546acbb63e1a2d30c944db5ead538d/pkg/cmd/roachtest/kv.go#L60)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Oh, I said that assuming that the only reason that you wanted flags was for selecting which tests would be run. I just read the issue linked in the commit message, apologies for the hasty assumption
</blockquote></details>

Another thought is that perhaps we make it impossible to access the flag values until after they are parsed. I've been considering moving some of the `roachtest` infrastructure (i.e. `test`, `registry`, `cluster`) into `cmd/roachtest/internal/roachtest`.  The various flags would then become accessors on `test` or `cluster`. Not sure if this completely addresses the issue, though, as it is still natural to want to access flags such as `--local` during test registration. This approach would only prevent such access, not make it possible and useful.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-:-L9RA8CzDPWHCq2jyZAl:bnfp4nl)*

**Comment by petermattis** [comment]
Ok, I've converted all of the tests over to use `register*` functions and to call those functions from `registerTests`. No `go generate` magic, but I did include the shell pipeline for easily generating the list of `register*` functions.

One unanticipated side-effect is that `allTests` as it was being used no longer worked. That wasn't terribly important so I've indicated in the `run` help text how to get the list of tests via `run -n`. I also removed the global `tests` registry and register tests into a local variable when the `run` command is executed.

PTAL

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24530#-:-L9ViSoz7KvxGTVKoMjY:bnfp4nl)*

**Comment by petermattis** [comment]
bors r=tschottdorf

**Pull request merged**
