### PR TITLE
gossip: remove grpc.WithBlock()

### LINKED ISSUE #6108: gossip: performance regression in KV tests
Commit ac60bac038 tripled the running time of tests in the KV package (the slowdown was noticed in #6038 and the offending commit found via `git bisect`). We should investigate and figure out how we can get that performance back.

### PR DESCRIPTION
**Pull request by tamird**
This roughly cuts kv test time in half.

Fixes #6108.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6156)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/client.go, line 70 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6156#-KFjm20S9WrRqXzj4NG9:-KFjm20S9WrRqXzj4NGA:520563027) ([raw file](https://github.com/cockroachdb/cockroach/blob/9239a3ce89e0dcbf2561cf56aad1beefc338a40d/gossip/client.go#L70)):*
Can you add a comment to not add `grpc.WithBlock`? Do you have an explanation for why this affected `kv` test time so much?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6156)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/client.go, line 70 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6156#-KFjm20S9WrRqXzj4NG9:-KFk9U9g7tIn-P26Gdzt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9239a3ce89e0dcbf2561cf56aad1beefc338a40d/gossip/client.go#L70)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6156)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6156#-:-KFkCTZ8tH79kH6xW5jV:1417088721)*

**Pull request merged**
