### PR TITLE
release-24.2: storage: per-store categorized write metrics

### LINKED ISSUE #126431: storage: categorized write metrics are inflated
In a multi-store configuration, the categorized write metrics can report inflated numbers.

For example, the following was pulled from a single node that has four stores:

Screenshot 2024-06-28 at 2 13 09 PM

Note also that the metrics per store are ~identical, which is sus.

Digging into the code, we have a single `DiskWriteStatsCollector` for all engines, and the collector doesn't internally separate based on store.

[More context (internal)](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1719609559087359).

Jira issue: CRDB-39906

### PR DESCRIPTION
**Pull request by aadityasondhi**
Backport 1/1 commits from #127266.

/cc @cockroachdb/release

---

Previously, we were using a single node-level `DiskWriteStatsCollector`, which led to inflated metrics in multi-store deployments.

This patch introduces a `WriteStatsManager` that maps physical disk `DeviceID` to a unique `DiskWriteStatsCollector`. By doing this, we are able to attribute categorized disk writes to each store's physical disks, and track other writes such as CRDB logs and sql spills.

Fixes #126431.

Release note: None

Release justification: Fix metric bug that causes inflated disk write metrics

### CODE REVIEW

**Comment by jbowens** [comment]
Needs #128042 too, right?

**Review by aadityasondhi — COMMENTED** [review]
Yes, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128009#-:-O3D7NfU7z4PKkAPho2P:b60r506)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — APPROVED** [review]

**Comment by RaduBerinde** [comment]
Note that we will need to backport to the rc branch if we want this in 24.2.0.

**Comment by aadityasondhi** [comment]
Looks like I missed the window by a few hours. Thanks for the call out @RaduBerinde.

**Comment by aadityasondhi** [comment]
To close the loop here, we decided to not push the backport to 24.2.0-rc since this is a rare bug (only on multi-store deployments) that only affects metrics (so not on a critical path). We are okay with having this fixed in 24.2.1.

**Pull request merged**
