### PR TITLE
cli: flags cleanup

### PR DESCRIPTION
**Pull request by RaduBerinde**
The main benefit of the cleanup is that the flag names, shorthands, environment
variables and descriptions are all in the same place. The environment variables
are now explicitly defined (so they are greppable in the code); we assert that
they have the correct name.

Functional fixes:
- the default values shown in usage used to reflect the value set via the
  envvar (if it was set); now the actual default is shown
- the insecure flag had a weird behavior where the envvar would set the
  "no option default"; the flag would take precedence if the value was
  specified (`--insecure=true/false`) but the environment variable would take
  precedence if it was specified using `--insecure`. This is fixed - as with
  other flags, what's on the command line always takes precedence.

Output looks ok AFAICT, here's the output for `start --help` https://gist.github.com/RaduBerinde/184c164de8654384c3c17b028b19e37a

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8509)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cli/cliflags/flags.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509#-KP47TNkFoxCZ8aCM7PL:-KP47TNkFoxCZ8aCM7PM:b-ypqydp) ([raw file](https://github.com/cockroachdb/cockroach/blob/049fdf46148680155b385c22e18c2e09083d5956/cli/cliflags/flags.go#L36)):*
> ```Go
> 	// embedding the tag "<STOPWRAP>": this tag is removed from the text and
> 	// signals that everything that follows should not be re-wrapped. To start
> 	// wrapping again, use "<STARTWRAP>".
> ```

See my comment in the other PR regarding whether this should be `<WRAP>` and `</WRAP>`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509#-:-KP47dsoJIKGhqffmhHO:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cli/cliflags/flags.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509#-KP47TNkFoxCZ8aCM7PL:-KP8OnqJwWgb-hxHfqg4:b9jh770) ([raw file](https://github.com/cockroachdb/cockroach/blob/049fdf46148680155b385c22e18c2e09083d5956/cli/cliflags/flags.go#L36)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> See my comment in the other PR regarding whether this should be `<WRAP>` and `</WRAP>`. 
</details>
TFTR!

Wrapping should be the default (so that these tags are only used for the couple of commands that need them). So it would have to be `<NOWRAP>...</NOWRAP>`.. Or if we really want to be HTML-like, maybe `<PRE>..</PRE>` since that's something people might be familiar with? Could also do three backquotes since we're used to that. Let me know which you prefer, I am ok with any of these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cli/cliflags/flags.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509#-KP47TNkFoxCZ8aCM7PL:-KP8Q6MbehwRIEOU0aU2:b-co7e3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/049fdf46148680155b385c22e18c2e09083d5956/cli/cliflags/flags.go#L36)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> TFTR!
> 
> Wrapping should be the default (so that these tags are only used for the couple of commands that need them). So it would have to be `<NOWRAP>...</NOWRAP>`.. Or if we really want to be HTML-like, maybe `<PRE>..</PRE>` since that's something people might be familiar with? Could also do three backquotes since we're used to that. Let me know which you prefer, I am ok with any of these.
</details>
Actualy forget the backquotes idea, these are backquoted literals so it's not easy to put backquotes inside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cli/cliflags/flags.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509#-KP47TNkFoxCZ8aCM7PL:-KPDJWGF2-pnSnoz4MC4:b-glnde3) ([raw file](https://github.com/cockroachdb/cockroach/blob/049fdf46148680155b385c22e18c2e09083d5956/cli/cliflags/flags.go#L36)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Actualy forget the backquotes idea, these are backquoted literals so it's not easy to put backquotes inside.
</details>
`<PRE>..</PRE>` sounds good. The pseudo-html might be confusing, but it would be reasonably obvious to the casual reader.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[cli/cliflags/flags.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509#-KP47TNkFoxCZ8aCM7PL:-KPDv2vitmqfAE5qcQzP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/049fdf46148680155b385c22e18c2e09083d5956/cli/cliflags/flags.go#L36)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `<PRE>..</PRE>` sounds good. The pseudo-html might be confusing, but it would be reasonably obvious to the casual reader.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8509)*

**Pull request merged**
