### PR TITLE
sql: add user_id column to system.role_options table 

### PR DESCRIPTION
**Pull request by RichardJCai**
The system.role_options user_id column is populated after
the system.users user_id column is populated in the case of the
migration.

Release note: None

### CODE REVIEW

**Comment by RichardJCai** [comment]
This PR borrows a lot from https://github.com/cockroachdb/cockroach/pull/81457 - the PR to add the user_id column to system.users but should be slightly more straightforward since we no longer have to generate IDs, they should exist in `system.users` already

**Review by ajwerner — APPROVED** [review]
This seems fine. :lgtm: 

> Reviewed 4 of 4 files at r1, 30 of 57 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85845#-:-N9CuA4iBixK3AtDo4iH:bxdscro)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, @RichardJCai, and @stevendanna)

___
*[`pkg/bench/rttanalysis/testdata/benchmark_expectations` line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85845#-N9ChvDLE2QtCTvR3p_e:-N9ChvDLE2QtCTvR3p_f:bq8k1v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e635a2a1d248a04b4a529d9233543287fc196c85/pkg/bench/rttanalysis/testdata/benchmark_expectations#L32)):*
> ```
> 14,CreateRole/create_role_with_1_option
> 17,CreateRole/create_role_with_2_options
> 20,CreateRole/create_role_with_3_options
> ```

how come these are going up?



_Code quote:_
```
14,CreateRole/create_role_with_1_option
17,CreateRole/create_role_with_2_options
20,CreateRole/create_role_with_3_options
15,CreateRole/create_role_with_no_options
```

**Comment by RichardJCai** [comment]
> This seems fine. :lgtm:
> 
> > Reviewed 4 of 4 files at r1, 30 of 57 files at r2, 1 of 2 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85845#-:-N9CuA4iBixK3AtDo4iH:bxdscro)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, @RichardJCai, and @stevendanna)
> 
> _[`pkg/bench/rttanalysis/testdata/benchmark_expectations` line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85845#-N9ChvDLE2QtCTvR3p_e:-N9ChvDLE2QtCTvR3p_f:bq8k1v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e635a2a1d248a04b4a529d9233543287fc196c85/pkg/bench/rttanalysis/testdata/benchmark_expectations#L32)):_
> 
> > ```
> > 14,CreateRole/create_role_with_1_option
> > 17,CreateRole/create_role_with_2_options
> > 20,CreateRole/create_role_with_3_options
> > ```
> 
> how come these are going up?
> 
> _Code quote:_
> 
> ```
> 14,CreateRole/create_role_with_1_option
> 17,CreateRole/create_role_with_2_options
> 20,CreateRole/create_role_with_3_options
> 15,CreateRole/create_role_with_no_options
> ```

Additional round trip from looking up user_id from username, I'm gonna add caching for this.

**Comment by RichardJCai** [comment]
Thanks for reviewing!

bors r=ajwerner

**Comment by RichardJCai** [comment]
Trying again
bors r=ajwerner

**Comment by RichardJCai** [comment]
bors r=ajwerner

**Pull request merged**
