### PR TITLE
sql: turn vtable constructors into generators

### PR DESCRIPTION
**Pull request by changangela**
Relates to #23052.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal.go, line 1583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJDEbE2JbrPdwXVuPi:-LMJDEbE2JbrPdwXVuPj:bx1oh19) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/crdb_internal.go#L1583)):*
> ```Go
> 		i := 0
> 
> 		return func() (tree.Datums, bool, error) {
> ```

:100: this is a great strategy, and very simple!
___
*[pkg/sql/virtual_schema.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJCOygD3p1I3Mih2We:-LMJCOyh0-njW0eWw3dQ:bh9w7n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_schema.go#L57)):*
> ```Go
> 	schema    string
> 	populate  func(ctx context.Context, p *planner, db *DatabaseDescriptor, addRow func(...tree.Datum) error) error
> 	generator func(ctx context.Context, p *planner, db *DatabaseDescriptor) (func() (tree.Datums, bool, error), error)
> ```

It's not great that the other two fields on this struct have no comment - but your new one definitely needs one!

You should document the contract of this function signature.

Actually, I would recommend making the output function a separate typedef, and documenting that as well. Otherwise it will be unclear how to use the result of the generator for other users of this contract, later.
___
*[pkg/sql/virtual_schema.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJCucD9EMxcukEZVJU:-LMJCucD9EMxcukEZVJV:b-xvhvoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_schema.go#L131)):*
> ```Go
> 		}
> 
> 		if e.tableDef.generator != nil {
> ```

I would recommend making an assertion around here that the `tableDef` doesn't have both `generator` and `constructor` set. That might prevent bugs later on.
___
*[pkg/sql/virtual_table_values.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJD-pfByAf2RjqZ9XD:-LMJD-pfByAf2RjqZ9XE:bbl26qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_table_values.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

2018 :)
___
*[pkg/sql/virtual_table_values.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJDThr47eJyD3BMRw9:-LMJDThr47eJyD3BMRwA:b-orzvsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc89ed50bd077459d919fa3b537a567fc70f3081/pkg/sql/virtual_table_values.go#L61)):*
> ```Go
> 			return false, err
> 		}
> 		n.rows.AddRow(params.ctx, row)
> ```

Hmm, this doesn't seem right - shouldn't we be invoking our generator? I'm assuming this is WIP - maybe this is what you wanted to talk about! :)

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/virtual_schema.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJCOygD3p1I3Mih2We:-LMcnJtF77j_qwF_y2ln:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_schema.go#L57)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It's not great that the other two fields on this struct have no comment - but your new one definitely needs one!

You should document the contract of this function signature.

Actually, I would recommend making the output function a separate typedef, and documenting that as well. Otherwise it will be unclear how to use the result of the generator for other users of this contract, later.
</blockquote></details>

Done.
___
*[pkg/sql/virtual_schema.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJCucD9EMxcukEZVJU:-LMcpVGf3BmhA7OJojpm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_schema.go#L131)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would recommend making an assertion around here that the `tableDef` doesn't have both `generator` and `constructor` set. That might prevent bugs later on.
</blockquote></details>

Done.
___
*[pkg/sql/virtual_table_values.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJD-pfByAf2RjqZ9XD:-LMcpx71AQyPDkK4zJDl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_table_values.go#L1)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

2018 :)
</blockquote></details>

Done.
___
*[pkg/sql/virtual_table_values.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJDThr47eJyD3BMRw9:-LMcpWeu8SriOxxS_RhI:b-7pyo2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc89ed50bd077459d919fa3b537a567fc70f3081/pkg/sql/virtual_table_values.go#L61)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, this doesn't seem right - shouldn't we be invoking our generator? I'm assuming this is WIP - maybe this is what you wanted to talk about! :)
</blockquote></details>

I've made the virtualTableNodes simpler, and got rid of functions like Reset as we discussed last Thursday. Only problem is, I now have an empty `Close` function which is required for planNodes, and this planNode no longer does any caching (like valuesNode) does. Should we keep it this way?

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal.go, line 1583 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMctWiUDK7coUFJCbx0:-LMctWiUDK7coUFJCbx1:byguzsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/crdb_internal.go#L1583)):*
> ```Go
> 		i := 0
> 
> 		return func() (tree.Datums, bool, error) {
> ```

Hmm, I couldn't figure out how to use the newly defined virtableTableGenerator type here instead of manually defining the return signature. Any ideas?

**Review by jordanlewis — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal.go, line 1583 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMctWiUDK7coUFJCbx0:-LMcyZ3PAhCXx3I8PaUv:b-5e1o0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/crdb_internal.go#L1583)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Hmm, I couldn't figure out how to use the newly defined virtableTableGenerator type here instead of manually defining the return signature. Any ideas?
</blockquote></details>

I don't think you can in this context.
___
*[pkg/sql/virtual_schema.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJCOygD3p1I3Mih2We:-LMd-KpVAP9O1aZ-ErEn:birlxdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_schema.go#L57)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

minor style nit: to match the other comments in this file, you should use`//` comments for fields, and to have the first sentence start with the name of the field. In this case, it should be something like `// generator, if non-nil, is a function that..`

You should also mention somewhere nearby that this struct must have exactly one of `generator` or `populate` set.
___
*[pkg/sql/virtual_schema.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd1tYK3SBYSWRGlbsF:-LMd1tYL-ViPEp8Wx1zU:bcw9qsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_schema.go#L109)):*
> ```Go
> var errInvalidVirtualSchema = pgerror.NewError(pgerror.CodeObjectNotInPrerequisiteStateError,
> 	"virtualSchema cannot have both the populate and generator functions defined",
> ).SetHintf("remove the populate function definition")
> ```

This is a good idea, but I don't think the error code is right. Fundamentally this is a programming error - there's nothing a *user* could have done to cause this state, I believe. So I think the error code should be the Internal one (xx000), there should be a "programming error: " prefix to the error code, and you should remove the hint.
___
*[pkg/sql/virtual_table.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd2Igb6YJyALwWnxpB:-LMd2Igb6YJyALwWnxpC:bn9vd2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_table.go#L28)):*
> ```Go
>  * returns a tree.Datums corresponding to the next row of the virtual schema
>  * table. If there is no next row (end of table is reached), then return false.
>  * If there is an error, then return false and error. */
> ```

Same style comment - please use `//` comments instead, to match what we do elsewhere. It occurs to me that we should add a linter for this.
___
*[pkg/sql/virtual_table.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd4j0sCWgc1t0Zk9-L:-LMd4j0sCWgc1t0Zk9-M:bm016rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_table.go#L31)):*
> ```Go
> type virtualTableGenerator func() (tree.Datums, bool, error)
> 
> type virtualTableNode struct {
> ```

You should add a comment that explains what this planNode does. Something like:

```
// virtualTableNode is a planNode that constructs its rows by repeatedly invoking a 
// virtualTableGenerator function.
```
___
*[pkg/sql/virtual_table.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd53_L9RfxY09QD9xO:-LMd53_L9RfxY09QD9xP:b-1od06t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_table.go#L36)):*
> ```Go
> }
> 
> func (p *planner) newContainerVirtualTableValuesNode(
> ```

This constructor name should match the name of the planNode after it was changed to virtualTableNode.
___
*[pkg/sql/virtual_table_values.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJDThr47eJyD3BMRw9:-LMd45mZAPqw_7dgp2Pb:b-i8fxml) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc89ed50bd077459d919fa3b537a567fc70f3081/pkg/sql/virtual_table_values.go#L61)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

I've made the virtualTableNodes simpler, and got rid of functions like Reset as we discussed last Thursday. Only problem is, I now have an empty `Close` function which is required for planNodes, and this planNode no longer does any caching (like valuesNode) does. Should we keep it this way?
</blockquote></details>

It's okay to have an empty Close function.

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/virtual_schema.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJCOygD3p1I3Mih2We:-LMdE4KQ9nxG_H4xz65_:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2a2366fc3b978c6d637f276e6b7d33305dc8bf/pkg/sql/virtual_schema.go#L57)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

minor style nit: to match the other comments in this file, you should use`//` comments for fields, and to have the first sentence start with the name of the field. In this case, it should be something like `// generator, if non-nil, is a function that..`

You should also mention somewhere nearby that this struct must have exactly one of `generator` or `populate` set.
</blockquote></details>

Done.
___
*[pkg/sql/virtual_schema.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd1tYK3SBYSWRGlbsF:-LMdDux88JW1k58Sm9sI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_schema.go#L109)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is a good idea, but I don't think the error code is right. Fundamentally this is a programming error - there's nothing a *user* could have done to cause this state, I believe. So I think the error code should be the Internal one (xx000), there should be a "programming error: " prefix to the error code, and you should remove the hint.
</blockquote></details>

Done.
___
*[pkg/sql/virtual_table.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd2Igb6YJyALwWnxpB:-LMdDxUy6T_r-h0EBHkX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_table.go#L28)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Same style comment - please use `//` comments instead, to match what we do elsewhere. It occurs to me that we should add a linter for this.
</blockquote></details>

Done.
___
*[pkg/sql/virtual_table.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd4j0sCWgc1t0Zk9-L:-LMdDyiT3miCUz-phged:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_table.go#L31)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You should add a comment that explains what this planNode does. Something like:

```
// virtualTableNode is a planNode that constructs its rows by repeatedly invoking a 
// virtualTableGenerator function.
```
</blockquote></details>

Done.
___
*[pkg/sql/virtual_table.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd53_L9RfxY09QD9xO:-LMdDzuE52Apn4OxNlAr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_table.go#L36)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This constructor name should match the name of the planNode after it was changed to virtualTableNode.
</blockquote></details>

Done.
___
*[pkg/sql/virtual_table_values.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMJDThr47eJyD3BMRw9:-LMdE0AL9fZTUB8pqREg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc89ed50bd077459d919fa3b537a567fc70f3081/pkg/sql/virtual_table_values.go#L61)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It's okay to have an empty Close function.
</blockquote></details>

Done.

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/virtual_table.go, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhD_X12YXLcv67ja5w:-LMhD_X12YXLcv67ja5x:b-2f0z16) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_table.go#L44)):*
> ```Go
> ) *virtualTableNode {
> 	return &virtualTableNode{
> 		columns: columns,
> ```

I added this field in in order to return it in the switch statement in `plan_columns.go`. Also had to add *virtualTableNode in a bunch of other switch statements since it was failing a bunch of unit tests.

**Review by asubiotto — COMMENTED** [review]
Nice work. I wonder if you can think of a way of showing the improvement that this code offers via an experiment/benchmark. I recall that the admin ui was having trouble using the ranges virtual table.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-:-LMhGLx9D88qOt_Gn6hF:b2ujkng)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2370 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhAjpZ5c1EPsYISQXP:-LMhAjpZ5c1EPsYISQXQ:b-sr0wkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/distsql_physical_planner.go#L2370)):*
> ```Go
> 		}
> 	case *virtualTableNode:
> 		plan, err = dsp.wrapPlan(planCtx, n)
> ```

You can get away with not adding a case, since it will fall back to the `default` case and wrap the node
___
*[pkg/sql/virtual_schema.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhHSuT1oTVRLidYlzI:-LMhHSuT1oTVRLidYlzJ:b-ms4n9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_schema.go#L56)):*
> ```Go
> type virtualSchemaTable struct {
> 	// Exactly one of the populate and generator fields should be defined for
> 	// each virtualSchemaTable.
> ```

I think it would be nice to expand the comment with the difference in behavior between populate/generator
___
*[pkg/sql/virtual_table.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMd2Igb6YJyALwWnxpB:-LMhDIhB0512yKn5O-Cn:b2vaxad) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e8c46086b1f74df55dfc4dc25e3a6e0b5c4d12b/pkg/sql/virtual_table.go#L28)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: trailing `*/`
___
*[pkg/sql/virtual_table.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhG9ya41Rc9qFil8DE:-LMhG9ya41Rc9qFil8DF:bcic2sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_table.go#L29)):*
> ```Go
> // table. If there is no next row (end of table is reached), then return false.
> // If there is an error, then return false and error. */
> type virtualTableGenerator func() (tree.Datums, bool, error)
> ```

Have you thought of not returning a boolean and have the caller deduce that there are no more rows if `tree.Datums == nil && err == nil`
___
*[pkg/sql/virtual_table.go, line 33 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhDO0C2QWNz00qMCh4:-LMhDO0C2QWNz00qMCh5:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_table.go#L33)):*
> ```Go
> // virtualTableNode is a planNode that constructs its rows by repeatedly
> // invoking a virtualTableGenerator function.
> ```

nit: extra line

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2370 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhAjpZ5c1EPsYISQXP:-LMhNaZ4EJbn2W9ejQwS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/distsql_physical_planner.go#L2370)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You can get away with not adding a case, since it will fall back to the `default` case and wrap the node
</blockquote></details>

Done.
___
*[pkg/sql/virtual_schema.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhHSuT1oTVRLidYlzI:-LMhNbT95ASDPgs6KwXI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_schema.go#L56)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it would be nice to expand the comment with the difference in behavior between populate/generator
</blockquote></details>

Done.
___
*[pkg/sql/virtual_table.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhG9ya41Rc9qFil8DE:-LMhNeeMARjoKZOgfCrR:b-549to8) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_table.go#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Have you thought of not returning a boolean and have the caller deduce that there are no more rows if `tree.Datums == nil && err == nil`
</blockquote></details>

Yeah, I was choosing between the two approaches. I ended up putting a boolean value because I thought it wasn't intuitive to return `nil, nil` when we want to signify there are no more rows. It would also complicate the `Next` logic a little bit because they also return the redundant boolean. I'm open to changing it though, thoughts?
```go
	if err != nil {
		return false, err
	} else {
		if row != nil {
			return true, nil
		} else {
			return false, nil
		}
	}
```

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/virtual_table.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhG9ya41Rc9qFil8DE:-LMiGmg1C2ESm4YSap2-:bbp57st) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_table.go#L29)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Yeah, I was choosing between the two approaches. I ended up putting a boolean value because I thought it wasn't intuitive to return `nil, nil` when we want to signify there are no more rows. It would also complicate the `Next` logic a little bit because they also return the redundant boolean. I'm open to changing it though, thoughts?
```go
	if err != nil {
		return false, err
	} else {
		if row != nil {
			return true, nil
		} else {
			return false, nil
		}
	}
```
</blockquote></details>

We use the (nil, nil) approach with processors in distsql when calling Next. I think the logic could be simplified to:
```
if err != nil {
    return false, err
}
return row != nil, nil
```

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/virtual_table.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMhG9ya41Rc9qFil8DE:-LMigBL14AX49h9b1f3l:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/785a941ce6c738fae6032bbf9a9059244ef29c53/pkg/sql/virtual_table.go#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We use the (nil, nil) approach with processors in distsql when calling Next. I think the logic could be simplified to:
```
if err != nil {
    return false, err
}
return row != nil, nil
```
</blockquote></details>

Done. Thanks!

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-:-LMmGtnd9FVUYyfIrrTz:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 440 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMmFzcD7OeA3xDIO0Pl:-LMmFzcD7OeA3xDIO0Pm:b1q6ieh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2400a8f4a6ba874709bed2f908b1195c420233/pkg/sql/distsql_physical_planner.go#L440)):*
> ```Go
> 		return canDistribute, nil
> 	case *virtualTableNode:
> 		return cannotDistribute, newQueryNotSupportedErrorf("unsupported node %T", node)
> ```

You don't need this - it'll get caught by the default statement below, just like the other switch statement

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30204)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 440 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30204#-LMmFzcD7OeA3xDIO0Pl:-LMmw61zEIcVmK76MXyU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2400a8f4a6ba874709bed2f908b1195c420233/pkg/sql/distsql_physical_planner.go#L440)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You don't need this - it'll get caught by the default statement below, just like the other switch statement
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]

**Pull request merged**
