### PR TITLE
sql: Assert correct types on virtual schema row population

### LINKED ISSUE #9577: sql: Change virtual schema row population to use column-name indexed maps
Per @cuongdo's suggestion about `virtual_schema.go`'s use of the `addRow` closure:
> These calls to addRow seem error-prone to me. For example, it seems easy to accidentally swap
> a pair of the DBools below, which would slip by type checking and many tests. It seems cleaner 
> to have addRow take in a map[string]]parser.Datum to ensure that the right values are mapped
> to the right columns.

### PR DESCRIPTION
**Pull request by nvb**
~~Fixes #9577.~~

~~This change uses a column name-indexed map when populating virtual
schema rows.~~

~~I'm not sold on this change. It adds a lot of overhead when asserting preconditions and requires lots of map manipulation, all for every single virtual schema row populated, every single time the schema is queried. I also think it makes the code less readable. I understand the concern in #9577, but I think thorough testing is a better solution, especially because these table definitions should never change once introduced.~~

Closes #9577.

This change asserts the type of all datums passed to the virtual schema
row population function, making sure the datum type matches its
corresponding column type.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9741)

### CODE REVIEW

**Comment by knz** [comment]
Thanks for preparing this. Indeed the end result also convinces me this is not the right approach. Really what we need is zero-overhead named arguments like there are in OCaml, Obj-C, Python and others. 

The proper way to do this in Go is not a map but instead an array.
May I suggest that each schema exports a set of constants whose value are the indices of the corresponding column in a DTuple. Then you can "cook" a datum row in the caller using these constant names as indices. Et voila, zero overhead and good readability. 

What do you think?

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9741#-:-KTH_a393MmNYQOIVvsS:b-qn3ao5)*

**Comment by cuongdo** [comment]
Yes, perhaps a set of constants & an array would be better. Could you try
it with a small subset of the code to see how well that would work? (No
need to go through converting all of the code unless it shows promise.)

**Comment by nvanbenschoten** [comment]
The original issue was that it was possible for the column order in the populated row to get out of order with the table's columns. For instance, if the order of columns changed in the `CREATE TABLE` statement. Using a map allowed us to avoid this issue because we would map from column names directly to values. Unfortunately, using a set of constants whose values are indices for their corresponding columns has the same issue as we previously had, albeit hidden behind a layer of indirection. We still have the issue that if the column order changes, we need to make corresponding changes elsewhere. Because of that, I don't think the large amount of duplication to create all of these constants would be worth it (unless maybe they were auto-generated, but that would be a different mess). In fact, I think it actually exposes more surface area for error.

I still maintain that because these table definitions should never be changed (they are part of the SQL standard, after all), proper testing with the previous approach is sufficient to prevent errors. That said, I could bring some of the type assertions added in this PR in `sql/virtual_schema.go` to any of the approaches to give us an extra layer of sanity checking on the column values.

**Comment by knz** [comment]
Ok LGTM.

**Comment by nvanbenschoten** [comment]
LGTM meaning you're ok with removing all of this except for the new type assertions for each column?

**Comment by knz** [comment]
Yes that's what I mean.

**Comment by cuongdo** [comment]
+1

**Comment by nvanbenschoten** [comment]
I just made the change to revert to the previous approach but assert correct datum types. PTAL.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9741#-:-KTfZSwRoy33O1d4o5OM:bnfp4nl)*

**Pull request merged**
