### PR TITLE
server: use actual TenantID for multi-tenant KV admission control

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #65954

Release note (ops change): Enabling admission.kv.enabled may provide
better inter-tenant isolation for multi-tenant KV nodes.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
There are no experiments yet to measure effectiveness in multi-tenant settings. Those will come later (and are mentioned in the corresponding issue).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67533#-:-MeVNNZ91lng3nI9A-ch:bqeopjp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67533#-:-MeVerZgCHLYLPmpwfHh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67533#-:-MeVkCCMA3QWilJ8_T1z:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by sumeerbhola** [comment]
TFTRs!

**Pull request merged**
