### PR TITLE
rfc: heuristics in column groups

### PR DESCRIPTION
**Pull request by danhhz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6868)

### CODE REVIEW

**Comment by paperstreet** [comment]
cc @petermattis @bdarnell 

Side question: After starting the implementation work, I'm finding that "Group" is unclear on its own (and even ambiguous with GROUP BY in places) while "Column Group" everywhere is wordy. How do people feel about stealing the Bigtable terminology and using "Family"? It sounds enough like a feature that even without the "Column" prefix, I think it's always clear what you're talking about. We'd have to use it externally, too, which is why I'm asking and not just doing it, but I think it'd have the same benefits there.

**Comment by dt** [comment]
re "column family": note that RocksDB has things called "Column Families" as well (we always use the Default cf IIRC) so there still might be some room for confusion in the codebase https://github.com/facebook/rocksdb/wiki/Column-Families

**Comment by petermattis** [comment]
I'm fine with renaming `Group` to something else. Using the term `Family` might be a bit confusing because what we're doing isn't the same as BigTable or RocksDB or Cassandra column families.

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> re "column family": note that RocksDB has things called "Column Families" as well (we always use the Default cf IIRC) so there still might be some room for confusion in the codebase https://github.com/facebook/rocksdb/wiki/Column-Families
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/sql_column_groups.md, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIYMGNRTKC_JM42ZoM-:-KIYMGNRTKC_JM42ZoM0:558743874) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacc2b8d7d77157fb042a478440f88c21e96643/docs/RFCS/sql_column_groups.md#L120)):*
> ```Markdown
> 
> - Group 0 (the sentinal) always has at least one column. Non-nullable and fixed
> sized columns are preferred.
> ```

`s/sentinal/sentinel/g`

What about the following table:

```
CREATE TABLE t (
  k INT,
  v INT,
  PRIMARY KEY (k, v)
```

All of the columns are part of the primary key so nothing should be stored in the value. 

---

*[docs/RFCS/sql_column_groups.md, line 122 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIYLpHRKcKFZeJlCsXG:-KIYLpHRKcKFZeJlCsXH:303791600) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacc2b8d7d77157fb042a478440f88c21e96643/docs/RFCS/sql_column_groups.md#L122)):*
> ```Markdown
> sized columns are preferred.
> 
> - Columns in the primary index are assigned to group 0.
> ```

Columns that are part of the primary key are not explicitly stored in values because those column values are already stored in the primary key.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-:-KIYMe6cbc9TgOSq5dYl:915877942)*

**Comment by paperstreet** [comment]
I'd forgotten about RocksDB families, but at least it's a conflict at the highest and lowest abstraction levels of the codebase. Seems better than GROUP BY, which is also in sql.

Some of the details of Bigtable families and what's proposed here are different, but the overall goal feels similar. Bigtable families control what columns are stored together, so does this. Bigtable families can be put into locality groups, which have replication controls (and other knobs), which we could also do here eventually.

Any suggestions for what I'd use besides family? Bunch? Bundle? Pack? Pack isn't bad. A group of cockroaches is an "intrusion" according to http://www.factmonster.com/ipka/A0004725.html, which doesn't really help.

<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm fine with renaming `Group` to something else. Using the term `Family` might be a bit confusing because what we're doing isn't the same as BigTable or RocksDB or Cassandra column families.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/sql_column_groups.md, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIYMGNRTKC_JM42ZoM-:-KIYPX4qUScAEt8Ygv0w:2008282774) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacc2b8d7d77157fb042a478440f88c21e96643/docs/RFCS/sql_column_groups.md#L120)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/sentinal/sentinel/g`
> 
> What about the following table:
> 
> ```
> CREATE TABLE t (
>   k INT,
>   v INT,
>   PRIMARY KEY (k, v)
> ```
> 
> All of the columns are part of the primary key so nothing should be stored in the value. 
</details>
Ah, yes. This case was unclear

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-:-KIYQCAvJvHFQPLcnEiq:-512758100)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868)*

**Comment by paperstreet** [comment]
FYI, I brought up GROUP vs FAMILY vs something else at the sql weekly and we decided on FAMILY. I'll send a PR after this one to move to the new terminology

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I'd forgotten about RocksDB families, but at least it's a conflict at the highest and lowest abstraction levels of the codebase. Seems better than GROUP BY, which is also in sql.
> 
> Some of the details of Bigtable families and what's proposed here are different, but the overall goal feels similar. Bigtable families control what columns are stored together, so does this. Bigtable families can be put into locality groups, which have replication controls (and other knobs), which we could also do here eventually.
> 
> Any suggestions for what I'd use besides family? Bunch? Bundle? Pack? Pack isn't bad. A group of cockroaches is an "intrusion" according to http://www.factmonster.com/ipka/A0004725.html, which doesn't really help.
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-:-KIZ5yxCtl-vt0M_0tsN:1936593393)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/sql_column_groups.md, line 119 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIZ7r8ei7DwfCcgFHAq:-KIZ7r8ei7DwfCcgFHAr:858510288) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b31e05434b2969096d9a6f50ed7b97d9c9c8684/docs/RFCS/sql_column_groups.md#L119)):*
> ```Markdown
> ## Heuristics for Fitting Columns into Groups
> 
> - Fixed sized columns (`INT`, `DECIMAL`, `FLOAT`, `BOOL`, `DATE`, `TIMESTAMP`,
> ```

DECIMAL (without a precision or scale) is not a fixed size. It probably deserves a treatment similar to STRINGS and BYTES.

---

*[docs/RFCS/sql_column_groups.md, line 121 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIZ7Y2RAQNQKYx07gml:-KIZ7Y2RAQNQKYx07gmm:450188374) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b31e05434b2969096d9a6f50ed7b97d9c9c8684/docs/RFCS/sql_column_groups.md#L121)):*
> ```Markdown
> - Fixed sized columns (`INT`, `DECIMAL`, `FLOAT`, `BOOL`, `DATE`, `TIMESTAMP`,
> `INTERVAL`, `STRING` with length, `BYTES` with length) will be packed into a
> group, up to a threshold (strawman: 256 bytes).
> ```

What is the plan for once groups exceed this threshold? Will then just spill over into another group, or do we want to try to balance them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868)*

**Comment by paperstreet** [comment]
Is this ready to merge?

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> FYI, I brought up GROUP vs FAMILY vs something else at the sql weekly and we decided on FAMILY. I'll send a PR after this one to move to the new terminology
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/sql_column_groups.md, line 119 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIZ7r8ei7DwfCcgFHAq:-KId3nI5dzJD_xKg4bIA:1710412561) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b31e05434b2969096d9a6f50ed7b97d9c9c8684/docs/RFCS/sql_column_groups.md#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> DECIMAL (without a precision or scale) is not a fixed size. It probably deserves a treatment similar to STRINGS and BYTES.
</details>
Good catch. Done

---

*[docs/RFCS/sql_column_groups.md, line 121 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIZ7Y2RAQNQKYx07gml:-KId3phhz3BFv3LT-ldE:707525583) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b31e05434b2969096d9a6f50ed7b97d9c9c8684/docs/RFCS/sql_column_groups.md#L121)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> What is the plan for once groups exceed this threshold? Will then just spill over into another group, or do we want to try to balance them?
</details>
I was planning on doing the most naive thing first (spill over). This seems a little too low-level for the rfc, so I was planning to omit it, but I'll stick it in there if you feel strongly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-:-KId4b6__3HhfAHAL2MS:-944048386)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/sql_column_groups.md, line 121 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIZ7Y2RAQNQKYx07gml:-KIdBGOZHPI2lr_Zy-BK:1322810231) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b31e05434b2969096d9a6f50ed7b97d9c9c8684/docs/RFCS/sql_column_groups.md#L121)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I was planning on doing the most naive thing first (spill over). This seems a little too low-level for the rfc, so I was planning to omit it, but I'll stick it in there if you feel strongly
</details>
This is fine for the RFC. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/sql_column_groups.md, line 121 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-KIZ7Y2RAQNQKYx07gml:-KIdBc6ZXgJPWhSmNmnC:-2075396089) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b31e05434b2969096d9a6f50ed7b97d9c9c8684/docs/RFCS/sql_column_groups.md#L121)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This is fine for the RFC. Thanks.
</details>
By that I mean what you already have is fine for the RFC. I was just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868)*

**Comment by petermattis** [comment]
:lgtm:

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Is this ready to merge?
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-:-KIdFqMLMMfJ_Vf1orcd:1417088721)*

**Comment by andreimatei** [comment]
:lgtm:

<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6868#-:-KIdNigbthNkRawIzSJo:1417088721)*

**Pull request merged**
