### PR TITLE
sql: add user_id column to system.privileges table

### PR DESCRIPTION
**Pull request by andyyang890**
This patch adds a new `user_id` column to the `system.privileges` table,
which corresponds to the existing `username` column. Migrations are
also added to alter and backfill the table in older clusters.

Part of https://github.com/cockroachdb/cockroach/issues/87079

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this looks good! i just had one nit about the index

as a separate point, i just realized that longer term (after 23.1) we will need to start thinking about changing the primary keys of all the system tables that have username in the PK. that project currently has a few unknowns. nothing to do relating to this right now though.

sorry for the very long delay in reviewing

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93090#-:-NNnDN7OA8m2eod2dLHl:b-1zdfy1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rhu713)

___
*[`pkg/sql/catalog/systemschema/system.go` line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93090#-NNnBJbGEn0Ld5lUHwbH:-NNnBJbGEn0Ld5lUHwbI:b38tqs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b34530c17c395c7890aca1fb59c204858c0293c/pkg/sql/catalog/systemschema/system.go#L743)):*
> ```Go
> 	user_id OID,
> 	CONSTRAINT "primary" PRIMARY KEY (username, path),
> 	UNIQUE INDEX (user_id, path),
> ```

nit: could you change this to be a unique index on `(path, user_id) STORING (privileges, grant_options)`. the reason is that we have some queries that access this by `path` without specifying a user. and the STORING clause makes it so all the data can be read from this index without having to also consult the primary index.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rhu713)

___
*[`pkg/sql/catalog/systemschema/system.go` line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93090#-NNnBJbGEn0Ld5lUHwbH:-NNnFhDbCfCwqcMfgiS9:b-lojlby) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b34530c17c395c7890aca1fb59c204858c0293c/pkg/sql/catalog/systemschema/system.go#L743)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could you change this to be a unique index on `(path, user_id) STORING (privileges, grant_options)`. the reason is that we have some queries that access this by `path` without specifying a user. and the STORING clause makes it so all the data can be read from this index without having to also consult the primary index.
</blockquote></details>

sure, i'll make this change. also, do you mind explaining why the index should be on `(path,  user_id)` if the query only accesses the table by specifying `path`?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rhu713)

___
*[`pkg/sql/catalog/systemschema/system.go` line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93090#-NNnBJbGEn0Ld5lUHwbH:-NNrdXFADPWi5ESXd_ib:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b34530c17c395c7890aca1fb59c204858c0293c/pkg/sql/catalog/systemschema/system.go#L743)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

sure, i'll make this change. also, do you mind explaining why the index should be on `(path,  user_id)` if the query only accesses the table by specifying `path`?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm! it just needs a rewrite for a test

**Comment by andyyang890** [comment]
bors r=rafiss

**Comment by andyyang890** [comment]
bors r=rafiss

**Pull request merged**
