### PR TITLE
docs/tech-notes: admission control overview

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release justification: Non-production code change.
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-:-MjBWQqV-QQ4_lKQpmH7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[docs/tech-notes/admission_control.md, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjBVkpkECqpp9IJ0yGl:-MjBVkpkECqpp9IJ0yGm:b-pf1rde) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L153)):*
> ```
> and would ideally not be needed
> ```
Is another reason for this ordering requirement the inability to track completion or size of `SQL-KV` or `SQL-SQL` work? If we could determine how much work was being done and make execution of sql yield cooperatively when it did more work than it had tokens, would we do something different, even if we didn't have direct control over the scheduler?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69982)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[docs/tech-notes/admission_control.md, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjBVkpkECqpp9IJ0yGl:-MjCKQoNDjvtRKG-URi3:b-cvayus) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L153)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> and would ideally not be needed
> ```
Is another reason for this ordering requirement the inability to track completion or size of `SQL-KV` or `SQL-SQL` work? If we could determine how much work was being done and make execution of sql yield cooperatively when it did more work than it had tokens, would we do something different, even if we didn't have direct control over the scheduler?

</blockquote></details>

Yes, if it could yield cooperatively when it had done more than it was granted (via token or slot), we would have something very much akin to CPU scheduling control, and could possibly collapse these into a single queue.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69982)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[docs/tech-notes/admission_control.md, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjBVkpkECqpp9IJ0yGl:-MjCZDUr6X6X_R48jSdD:bd6bpfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L153)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yes, if it could yield cooperatively when it had done more than it was granted (via token or slot), we would have something very much akin to CPU scheduling control, and could possibly collapse these into a single queue.
</blockquote></details>

I wonder then if that's the avenue to go down. It feels more likely that we can either convince the go runtime folks or manage a fork that adds cpu usage tracking than more bespoke scheduling control. @knz has a prototype described [here](https://github.com/golang/go/issues/41554#issuecomment-783526873) to track cpu nanos for a set of goroutines. For things like columnar execution, doing cooperative yielding seems pretty straightforward. That doesn't help you to yield when blocked. 

It's pretty sad that we'd go to these lengths when the runtime has the info we care about. I don't think the general problem is worse than memory monitoring (assuming we had access to the data), but memory monitoring has proven to be super painful.

**Comment by sumeerbhola** [comment]
> That doesn't help you to yield when blocked.

Yes, that's the other issue here. But that may be tractable since we can enumerate the main places in the code that block (though we will probably still want dynamic slot adjustment in case we overlook something, and we may not want to yield for every mutex acquisition attempt). I think these are:
- latch or lock acquisition, where we are explicitly waiting on a channel. We can release the slot before waiting on the channel and acquire it after.
- in Pebble, when we miss on the ssblock cache. The IO is synchronous, and the cpu consumption there is tiny, so we can release the slot before doing the IO and acquire it after.
- RPC calls

I think it is worth getting some experience with the current scheme before designing the next improved version. And if the improvements we need are mainly driven by serverless, we'll have a narrower problem to solve.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-:-MjGRt-M1WqqI4p9WLGn:b-8gk8uj)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[docs/tech-notes/admission_control.md, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjGQ0F22jjWHKvA6rRQ:-MjGQ0F22jjWHKvA6rRR:b-8tiu4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L211)):*
> ```Markdown
> 
> KV work concurrency slots are adjusted by monitoring the runnable
> goroutine count, and additively decreasing or increasing the total
> ```

[nit] maybe s/additively/gradually
___
*[docs/tech-notes/admission_control.md, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjGQ8pr-LrbjqRCAr6w:-MjGQ8pr-LrbjqRCAr6x:birq160) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L212)):*
> ```Markdown
> KV work concurrency slots are adjusted by monitoring the runnable
> goroutine count, and additively decreasing or increasing the total
> slots, when the runnable count is too high or too low. The adjustment
> ```

This is the first reference to "runnable count" in the doc, I think that should be introduced somewhere.
___
*[docs/tech-notes/admission_control.md, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjGRcD_4mhNXm1cJ8Mr:-MjGRcD_4mhNXm1cJ8Ms:b9oe32s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L337)):*
> ```Markdown
>   https://github.com/cockroachdb/cockroach/pull/65850#issue-656777155
>   and
>   https://github.com/cockroachdb/cockroach/pull/69311#issue-978297918
> ```

[nit] missing newline

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-:-MjUnqDU9C89AJQfiGUJ:bodi8iv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @sumeerbhola)

___
*[docs/tech-notes/admission_control.md, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjGQ0F22jjWHKvA6rRQ:-MjUlysU-NLrnHDk6Q1c:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L211)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe s/additively/gradually
</blockquote></details>

Done
___
*[docs/tech-notes/admission_control.md, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjGQ8pr-LrbjqRCAr6w:-MjUnTcK4sGcJRLDnELm:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is the first reference to "runnable count" in the doc, I think that should be introduced somewhere.
</blockquote></details>

Done
___
*[docs/tech-notes/admission_control.md, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69982#-MjGRcD_4mhNXm1cJ8Mr:-MjUnbFACDTYnHeBobdH:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10abd66326eaa192905dd95958c7378fb5f242b/docs/tech-notes/admission_control.md#L337)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] missing newline
</blockquote></details>

Done

**Pull request merged**
