### PR TITLE
sql: require any privilege on table-based SHOW commands

### LINKED ISSUE #8038: sql: audit privileges on SHOW CREATE TABLE
And other SHOW commands. For example SHOW CREATE TABLE currently can be done by any user on any table.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #8038 

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8070)

### CODE REVIEW

**Comment by tamird** [comment]
needs tests.

**Comment by mjibson** [comment]
Added tests. Changed permissions to be any permission, similar to MySQL.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8070#-:-KO6_4Q_pfyjEFVMyTx0:-932918377)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8070#-:-KO6hSU3MaXHUSsxWJtI:1417088721)*

**Comment by tamird** [comment]
Update the commit message and PR description plz

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8070#-:-KO6hTjGvgGaadUkZQJZ:1292286726)*

**Comment by jseldess** [comment]
@mjibson, just starting to update the docs, but I'm confused about the results I'm getting for `show columns`. As a user who has no privileges on a certain table, `users`, I'm able to get a response. This PR is supposed to prevent that, right?

```
$ cockroach sql --user=jseldess
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.

jseldess@:26257> show grants on users;
+-------+------+------------+
| Table | User | Privileges |
+-------+------+------------+
| users | root | ALL        |
+-------+------+------------+
(1 row)
jseldess@:26257> show columns from test.users;
+--------+-----------+-------+---------+
| Field  |   Type    | Null  | Default |
+--------+-----------+-------+---------+
| id     | INT       | false | NULL    |
| joined | TIMESTAMP | true  | NULL    |
| name   | STRING    | true  | NULL    |
| data   | BYTES     | true  | NULL    |
+--------+-----------+-------+---------+
(4 rows)
```

**Comment by mjibson** [comment]
Yeah that's odd. Could you make an issue about this and assign it to me?

**Comment by jseldess** [comment]
Done, @mjibson: https://github.com/cockroachdb/cockroach/issues/8524

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/558

**Pull request merged**
