### PR TITLE
server: add throttle metadata api

### PR DESCRIPTION
**Pull request by dhartunian**
This commit adds an API under `_status/throttling` to return metadata about the cluster-wide throttle status based on either license and grace period expiry, or telemetry delivery problems.

The consumer of this API will be the banner on DB Console that provides information about throttling behavior.

A few quirks that are needed to properly display the banner:

* When we request throttle status from the `Enforcer` we tell it that we're already at 6 connections so that the throttling *intent* is signaled. It's possible for the cluster to be in throttling state but not actually do anything if the user is only running at <=5 QPS. In that scenario, we'd still want to display the banner in DB Console for information purposes.

* Each node has separate telemetry delivery status, so we fan out to the cluster to see if any node is running into problems. This can arise, for instance, if the customer has a misconfigured firewall in a single region. When returning information in the response, we list all the NodeIDs that have telemetry delivery problems (license status is cluster-wide). This information can help the operator debug problems.

Resolves: CRDB-40396
Epic: CRDB-40853

Release note: None

### CODE REVIEW

**Review by angles-n-daemons — CHANGES_REQUESTED** [review]
couple of questions, looking or input but nothing clearly blocking

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-:-O7_YW2cE7dJFuuV1AE3:b-t2wfg0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`docs/generated/http/full.md` line 5489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-O7_ItTrEXQ_VZcmYpo4:-O7_ItTrEXQ_VZcmYpo5:bfnnyg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef34940d845b1fdaf5d0fc4a78ad73762019185/docs/generated/http/full.md#L5489)):*
> ```Markdown
> | Field | Type | Label | Description | Support status |
> | ----- | ---- | ----- | ----------- | -------------- |
> | throttled | [bool](#cockroach.server.serverpb.GetThrottlingMetadataResponse-bool) |  | throttled is true if at least one node in the cluster is actively being throttled. | [reserved](#support-status) |
> ```

I quite like these generated docs. Could we add descriptions to the other fields on the protobuf? 
___
*[`pkg/server/status.go` line 4329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-O7_NOfQ9SDnzpD4Nmkt:-O7_NOfRC8pPr1d6qzec:b-n27drl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef34940d845b1fdaf5d0fc4a78ad73762019185/pkg/server/status.go#L4329)):*
> ```Go
> 	// We use 6 here as a number that's definitely more than what's
> 	// allowed to trigger the throttling error if possible.
> 	err := e.MaybeFailIfThrottled(ctx, 6 /* txnsOpened */)
> ```

Absent a clear `ThrottlingInEffect` mechanism, I'd use a larger number, perhaps `math.MaxUint32` to ensure that this is far above whatever the throttling limit could be
___
*[`pkg/server/application_api/telemetry_test.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-O7_K0f93y9L2uMJUERl:-O7_K0f93y9L2uMJUERm:bep7bi9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef34940d845b1fdaf5d0fc4a78ad73762019185/pkg/server/application_api/telemetry_test.go#L133)):*
> ```Go
> }
> 
> func TestThrottlingMetadata(t *testing.T) {
> ```

These tests are awesome.

To clarify my understanding of the system, I've added some bullet points which I'd like to sanity check:
 - An active enterprise or evaluation license will not throttle.
 - An active trial and free license will only throttle if telemetry is not being sent.
 - An expired free license will throttle 30 days after the license has expired.
 - An expired trial license will throttle 7 days after the license has expired.
 - A free license will also throttle if the system goes 7 days without successfully sending diagnostics.

In addition to the above bullet points, I have some questions which may be answered by an additional test:
 - How does throttling work if an enterprise or evaluation license has expired?
 - Does the trial license behave the same as the free license wrt grace period / telemetry?

Beyond that, I have some questions which need not be answered by a test:
 - How is a grace period determined if there is no license? (not totally clear on reading this: https://docs.google.com/document/d/1T4jc07BUnFG0ZtBYAXGp6ssTp1VFdmXkF_M9gpwfq9k/edit#heading=h.9ndo02nsmu)

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131242)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons)

___
*[`docs/generated/http/full.md` line 5489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-O7_ItTrEXQ_VZcmYpo4:-O7dme7G8cd1xf09u4WR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef34940d845b1fdaf5d0fc4a78ad73762019185/docs/generated/http/full.md#L5489)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I quite like these generated docs. Could we add descriptions to the other fields on the protobuf?
</blockquote></details>

Done.
___
*[`pkg/server/status.go` line 4329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-O7_NOfQ9SDnzpD4Nmkt:-O7dmoDg1o5tM5SWT9HB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef34940d845b1fdaf5d0fc4a78ad73762019185/pkg/server/status.go#L4329)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Absent a clear `ThrottlingInEffect` mechanism, I'd use a larger number, perhaps `math.MaxUint32` to ensure that this is far above whatever the throttling limit could be
</blockquote></details>

Done.
___
*[`pkg/server/application_api/telemetry_test.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-O7_K0f93y9L2uMJUERl:-O7dmsnLEAgi7ra5dgrQ:b9ltavo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef34940d845b1fdaf5d0fc4a78ad73762019185/pkg/server/application_api/telemetry_test.go#L133)):*
Agree with your bullet points above.

> How does throttling work if an enterprise or evaluation license has expired?
No throttling happens if they have one of these licenses.

> Does the trial license behave the same as the free license wrt grace period / telemetry?
Yes.

> How is a grace period determined if there is no license? 
I think we default to the 7d period.

All that said, it is not the responsibility of this PR to define these requirements, just to translate them from the enforcer to the metadata endpoint.

**Review by angles-n-daemons — APPROVED** [review]
:lgtm: the tests make for an easy review - thanks for those

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131242#-:-O7jBeyy7vrcVyE5ubHV:boj3br7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by dhartunian** [comment]
TFTR!

bors r=angles-n-daemons

**Comment by dhartunian** [comment]
bors r=angles-n-daemons

**Pull request merged**
