### PR TITLE
kv/storage: disable observed timestamps for async resolved intents that are pushed

### LINKED ISSUE #36431: kv: stale read because intent from our past gets committed in our certain future?
Together with @nvanbenschoten and @ajwerner we're speculating on the following hazard:

- txn W is coordinated by node B. It lays down an intent on node A (key k) at ts 95.
- txn W gets pushed to ts 105 (taken from B's clock). It refreshes successfully and commits at 105. Node A's clock is at, say, 100; this is within clock offset bounds.
- after all this, txn R starts on node A. It gets assigned ts 100. The txn has no uncertainty for node A.
- txn W's async intent resolution comes around and resolves the intent on node A, moving the value fwd from ts 95 to 105. Node A's clock I think is not pushed to 105 by this ResolveIntent, but anyway the value of the clock does not matter any more.
- txn R reads key k and doesn't see anything. There's a value at 105, but we have no uncertainty. We think it's in our future and so we ignore it.

This is a stale read.
Are we missing anything? It seems that the "observed timestamps" mechanism (and the special case of no uncertainty on the gateway) seems to not work with the fact that we started changing intents' timestamps (through the refresh mechanism). I guess even before refreshing, we used to change intents' ts in SNAPSHOT txns, back in the day.

@tbg @spencerkimball @bdarnell @ajwerner @nvanbenschoten @petermattis 

Epic: CRDB-1514

Jira issue: CRDB-4498

### LINKED ISSUE #49360: roachtest: jepsen/multi-register/strobe-skews failed [likely #36431]
This is a long-standing test failure. We have reasonable confidence (read the thread below) that it is exposing the bug in https://github.com/cockroachdb/cockroach/issues/36431.

Jira issue: CRDB-4234

### PR DESCRIPTION
**Pull request by nvb**
Fixes #36431.
Fixes #49360.

This commit fixes the potential for a stale read as detailed in #36431 using the approach detailed in https://github.com/cockroachdb/cockroach/issues/36431#issuecomment-718347165. This bug requires a combination of skewed clocks, multi-key transactions split across ranges whose leaseholders are stored on different nodes, a transaction read refresh, and the use of observed timestamps to avoid an uncertainty restart. With the combination of these four factors, it was possible to construct an ordering of events that violated real-time ordering and allowed a transaction to observe a stale read. Upon the discovery of the bug, we [introduced](https://github.com/cockroachdb/jepsen/pull/19) the `multi-register` test to the Jepsen test suite, and have since observed the test fail when combined with the `strobe-skews` nemesis due to this bug in #49360 (and a few issues linked to that one). This commit stabilizes that test.

### Explanation

The combination of all of the factors listed above can lead to the stale read because it breaks one of the invariants that the observed timestamp infrastructure[^1] relied upon for correctness. Specifically, observed timestamps relied on the guarantee that a leaseholder's clock must always be equal to or greater than the timestamp of all writes that it has served. However, this guarantee did not always hold. It does hold for non-transactional writes. It also holds for transactions that perform all of their intent writes at the same timestamp and then commit at this timestamp. However, it does not hold for transactions which move their commit timestamp forward over their lifetime before committing, writing intents at different timestamps along the way and "pulling them up" to the commit timestamp after committing.

In violating the invariant, this third case reveals an ambiguity in what it means for a leaseholder to "serve a write at a timestamp". The meaning of this phrase is straightforward for non-transactional writes. However, for an intent write whose original timestamp is provisional and whose eventual commit timestamp is stored indirectly in its transaction record at its time of commit, the meaning is less clear. This reconciliation to move the intent write's timestamp up to its transaction's commit timestamp is asynchronous from the transaction commit (and after it has been externally acknowledged). So even if a leaseholder has only served writes with provisional timestamps up to timestamp 100 (placing a lower bound on its clock of 100), it can be in possession of intents that, when resolved, will carry a timestamp of 200. To uphold the real-time ordering property, this value must be observed by any transaction that begins after the value's transaction committed and was acknowledged. So for observed timestamps to be correct as currently written, we would need a guarantee that this value's leaseholder would never return an observed timestamp < 200 at any point after the transaction commits. But with the transaction commit possibly occurring on another node and with communication to resolve the intent occurring asynchronously, this seems like an impossible guarantee to make.

This would appear to undermine observed timestamps to the point where they cannot be used. However, we can claw back some utility by recognizing that only a small fraction[^2] of transactions commit at a different timestamps than the one they used while writing intents. We can also recognize that if we were to compare observed timestamps against the timestamp that a committed value was originally written (its provisional value if it was once an intent) instead of the timestamp that it had been moved to on commit, then the invariant would hold.

This commit does not take full advantage of this second observation, because we do not retain "written timestamps" in committed values (though we do in intents). Instead, we do something less optimal but cheaper and more convenient. Any intent whose timestamp is changed during asynchronous intent resolution is marked as "synthetic". Doing so is a compressed way of saying that the value could have originally been written as an intent at any time (even min_timestamp) and so observed timestamps cannot be used to limit uncertainty by pulling a read's uncertainty interval below the value's timestamp.

This application of the synthetic bit prevents observed timestamps from being used to avoid uncertainty restarts with the set of committed values whose timestamps do not reflect their original write time and therefore do not make a claim about the clock of their leaseholder at the time that they were committed. It does not change the interaction between observed timestamps and any other committed value.

### Correctness testing

I was not able to stress `jepsen/multi-register/strobe-skews` hard enough to cause it to fail, even on master. We've only seen the test fail a handful of times over the past few years, so this isn't much of a surprise. Still, this prevents us from saying anything concrete about an reduced failure rate.

However, the commit does add a new test called `TestTxnReadWithinUncertaintyIntervalAfterIntentResolution` which controls manual clocks directly and was able to deterministically reproduce the stale read before this fix in a few different ways. After this fix, the test passes.

### Performance analysis

This correctness fix will lead to an increased rate of transaction retries under some workloads. 

TODO(nvanbenschoten):
- observe TPC-C performance
-- top-line performance
-- uncertainty retry rate
-- commit-wait rate (should be zero)
- compare YCSB performance

----

Release note (bug fix): fixed a rare race condition that could allow for a transaction to serve a stale read and violate real-time ordering under moderate clock skew.

[^1]: see [pkg/kv/kvserver/observedts/doc.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/observedts/doc.go) for an explanation of the role of observed timestamps in the transaction model. This commit updates that documentation to include this fix.

[^2]: see analysis in https://github.com/cockroachdb/cockroach/issues/36431#issuecomment-714221846.

### CODE REVIEW

**Comment by sumeerbhola** [comment]
> Add WrittenTimestamp metadata field to roachpb.Value.

Is putting this in the value inherent to the design? I am asking since occasionally the idea of separating keys and values in storage has come up (see https://github.com/cockroachdb/pebble/issues/112) when storing rows that are very large. In  such an implementation values would be lazily loaded, and it would be wasteful to load a value only to parse the timestamp part and realize that it is not needed. Is it possible to keep this optional written timestamp in the key?

**Comment by nvanbenschoten** [comment]
No, the WrittenTimestamp could be in the key or in the value. I don't have strong opinions about where it should live, other than that it feels slightly more natural to store additional metadata in the value so that it does not impact key ordering. Although I guess it would live in the key suffix and we could ignore it in the custom key comparator. Does one option seem simpler than the other to you?

Your point about storing the WrittenTimestamp in the key so that we can avoid fetching the value in some cases is interesting. Based on the uncertainty rules (`when encountering an intent or value iff WrittenTimestamp < LocalUncertantyLimit && Timestamp < GlobalUncertaintyLimit` and when `ReadTimestamp < Timestamp`) and the fact that `LocalUncertantyLimit` can be at most `max_offset` less than `GlobalUncertaintyLimit`, I don't expect that an avoidable value fetch in the `WrittenTimestamp > LocalUncertantyLimit && Timestamp < GlobalUncertaintyLimit` case will make much of an impact in practice.

That said, when a key-value is uncertain, we don't actually need the value – we just return an error. So there is something nice about simplifying the condition for whether the value is needed or not to just `ReadTimestamp >= Timestamp`. But that's not to say that we would never complicate this condition later on. For instance, as discussed here and elsewhere, we may want to store per-KV TTLs at some point in the future. If we did, would we want to store those in the key as well?

**Comment by sumeerbhola** [comment]
> and the fact that LocalUncertantyLimit can be at most max_offset less than GlobalUncertaintyLimit, I don't expect that an avoidable value fetch in the WrittenTimestamp > LocalUncertantyLimit && Timestamp < GlobalUncertaintyLimit case will make much of an impact in practice.

My understanding is that our current max_offset is 500ms (I realize we want to reduce it), so
- GlobalUncertaintyLimit is txn-start-time + max_offset so can potentially capture many transactions
- common case: LocalUncertaintyLimit close to txn-start-time; most txns have WrittenTimestamp=Timestamp.
So the common case will fall in that category above. What am I missing?

> That said, when a key-value is uncertain, we don't actually need the value – we just return an error. So there is something nice about simplifying the condition for whether the value is needed or not to just ReadTimestamp >= Timestamp. But that's not to say that we would never complicate this condition later on. For instance, as discussed here and elsewhere, we may want to store per-KV TTLs at some point in the future. If we did, would we want to store those in the key as well?

The TTL question is interesting. I am assuming the fidelity required is 1min or lower, so 32 bits would be sufficient, and we could put it in the key. We would probably use TBI to optimize the scan for TTL enforcement, since once we switch TBI to block property collectors, it will likely be effective even for big L6 files that will have the expired data hopefully in a small number of blocks in the file (outlined in https://github.com/cockroachdb/pebble/issues/1190#issue-942213468). So maybe we could leave it in the value.

btw, in addition to the complete key-value separation outlined in https://github.com/cockroachdb/pebble/issues/112 there is also an intermediate approach that I've worked on in the past that keep keys and values in different parts of the same file. Such a scheme is helpful when filters can be applied to the key -- this isn't quite as valuable with CockroachDB since (a) there are secondary indexes, and (b) some of the filters may be on columns in the value. But it may still be narrowly useful when values are large enough and many of them don't need reading after examining the timestamps in the key.

**Comment by nvanbenschoten** [comment]
> So the common case will fall in that category above. What am I missing?

Well the common case is `ReadTimestamp > Timestamp`. The point I was trying to make (which wasn't very clear) was that the bounded interval between GlobalUncertaintyLimit and LocalUncertaintyLimit places an upper bound (assuming a fixed rate of new KV versions) on the number of values that a given transaction could avoid loading with this optimization.

Independent of uncertainty, it seems to me that the larger win with the lazy value loading in https://github.com/cockroachdb/pebble/issues/112 wouldn't be avoiding loading values whose keys have a `Timestamp > ReadTimestamp`, but in avoiding the need to load values for KV versions that are shadowed by later KV versions [during the iteration](https://github.com/cockroachdb/cockroach/blob/1f705cca89cc77b634899e971f8934ef1c1331e3/pkg/storage/pebble_mvcc_scanner.go#L593) from one key to the next. In some sense, I think that means that lazily loaded values provide some of the same benefit as https://github.com/cockroachdb/pebble/issues/1170.

> Does one option seem simpler than the other to you?

Did you have an opinion about this?

**Comment by sumeerbhola** [comment]
> Does one option seem simpler than the other to you?
> Did you have an opinion about this?

I would lean towards putting it in the key suffix as an optional part and adjusting the key comparator.

> Independent of uncertainty, it seems to me that the larger win with the lazy value loading in cockroachdb/pebble#112 wouldn't be avoiding loading values whose keys have a Timestamp > ReadTimestamp, but in avoiding the need to load values for KV versions that are shadowed by later KV versions during the iteration from one key to the next. In some sense, I think that means that lazily loaded values provide some of the same benefit as cockroachdb/pebble#1170.

The simplest way of implementing such key-value separation in the same file ends up with the values in the same order as the corresponding keys (for preserving locality). With 32KB blocks, and N bytes per row, we'd need 32KB/N to be small enough that at least 1 whole block gets skipped before the seek optimization in `pebbleMVCCScanner` gets applied. I've wondered about the distribution of N in production workloads, in case you have any insights (and the distribution of key lengths).

In contrast, https://github.com/cockroachdb/pebble/issues/1170 can be helpful even for small N, but is much harder of course. But you've raised a very interesting point. I am wondering whether all we need to do is separate keys and values in the same file, and change the ordering of the values such that we proceed from the latest version of a roachpb.Key to the latest version of the next roachpb.Key, so that locality is high for the latest version of values. Infrequently one of these latest versions will have been deleted (e.g. aborted transaction), but there is no correctness problem with that.

**Pull request closed without merging**
