### PR TITLE
sql/schemachanger: Add DSC support for trivial data type alters

### PR DESCRIPTION
**Pull request by spilchen**
This moves ALTER COLUMN .. SET TYPE support into the declarative schema changer (DSC). Prior to this, it was always done in the legacy schema changer.

Only trivial alterations are moved to the DSC in this commit. Trivial changes are those where no backfill is needed for the data. An example is changing a SMALLINT to a BIGINT; the existing data is fine and doesn’t need to be rewritten. If a complex alteration is requested, we will error out and fall back to the legacy schema changer.

Much of the logic in AlterColumnType, which is for the legacy schema changer, was duplicated since the DSC has a different state system. Many of the catalog state checks were reimplemented using the element state system that DSC uses. There is one check for TTL (in ValidateTTLExpressionDoesNotDependOnColumn) that hasn’t been duplicated yet. That will be handled in a follow-up change.

There are some changes to ensure the error messages are the same between the legacy and DSC. This allows us to run the same test twice, once with each schema changer.

Epic: CRDB-25314
Informs: #126143
Release note: None

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
Great work, just some minor nits so far. I only looked the declarative stuff, I'll make a deeper pass later today.

> Reviewed 12 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-:-O1qhPz2CShUu08wTHpg:b-1jbwlx)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1qf5Mb5rzafwGEDvi3:-O1qf5Mb5rzafwGEDvi4:b-wpbc3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e2b3cbafef339e74b3e4a66793564d24c5e7c8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L58)):*
> ```Go
> 			}
> 			elts := b.QueryByID(e.TableID).Filter(hasColumnIDAttrFilter(e.ColumnID))
> 			_, _, computedColName := scpb.FindColumnName(elts.Filter(publicTargetFilter))
> ```

Lets use the non-deprecated: FilterColumnName, with MustGetOne
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1qfF4Y20eqhFCwWLDe:-O1qfF4Y20eqhFCwWLDf:b604q2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e2b3cbafef339e74b3e4a66793564d24c5e7c8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L61)):*
> ```Go
> 			panic(sqlerrors.NewDependentBlocksOpError(op, objType, t.Column.String(), "computed column", computedColName.Name))
> 		case *scpb.View:
> 			_, _, ns := scpb.FindNamespace(b.QueryByID(col.TableID))
> ```

Nit: Same issue  as above.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/column.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1qh8SV7JbbQos_aXSC:-O1qh8SV7JbbQos_aXSD:b-yjznko) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e2b3cbafef339e74b3e4a66793564d24c5e7c8/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L77)):*
> ```Go
> 	}
> 	col := mut.AsColumn().ColumnDesc()
> 	col.Type = op.ColumnType.Type
> ```

Wonder if we can just operate on catCol here? MustFindColumnByID includes mutations too
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/column.go` line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1qgMC503bPQpRcKW2t:-O1qgMC503bPQpRcKW2u:besefd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e2b3cbafef339e74b3e4a66793564d24c5e7c8/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L378)):*
> ```Go
> 	ctx context.Context, op scop.UpsertColumnType, desc *descpb.ColumnDescriptor,
> ) error {
> 	kind, err := schemachange.ClassifyConversion(ctx, desc.Type, op.ColumnType.Type)
> ```

I think the purpose of this is more of an assertion right? In theory the builder should never generate anything that isn't trivial?

**Review by spilchen — COMMENTED** [review]
Thanks for the early review Faizan. I made some changes based on that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-:-O1rRQYd0LV1DQpx0CgM:b-1jygq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1qf5Mb5rzafwGEDvi3:-O1rFdRu30SUEdUvDA1u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e2b3cbafef339e74b3e4a66793564d24c5e7c8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L58)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Lets use the non-deprecated: FilterColumnName, with MustGetOne
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/column.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1qh8SV7JbbQos_aXSC:-O1rLyIy3UwyVyUDweTx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e2b3cbafef339e74b3e4a66793564d24c5e7c8/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L77)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Wonder if we can just operate on catCol here? MustFindColumnByID includes mutations too
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/column.go` line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1qgMC503bPQpRcKW2t:-O1rMHqa6gkh-BZt7RNk:bgbnz8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e2b3cbafef339e74b3e4a66793564d24c5e7c8/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L378)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think the purpose of this is more of an assertion right? In theory the builder should never generate anything that isn't trivial?
</blockquote></details>

Correct. We would have already checked the conversion type earlier (in `alterTableAlterColumnType`). For anything that isn't trivial, that would have returned `NotImplementedErrorf`. So, we should not get here at the moment.

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 26 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1sg_QR8PZilr4_sfyB:-O1sg_QR8PZilr4_sfyC:b-fela5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L46)):*
> ```Go
> 	reflect.TypeOf((*tree.AlterTableValidateConstraint)(nil)): {fn: alterTableValidateConstraint, on: true, checks: nil},
> 	reflect.TypeOf((*tree.AlterTableSetDefault)(nil)):         {fn: alterTableSetDefault, on: true, checks: nil},
> 	reflect.TypeOf((*tree.AlterTableAlterColumnType)(nil)):    {fn: alterTableAlterColumnType, on: true, checks: nil},
> ```

Add a version check here for 24.2
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1shFa3A0kqxJ9pmTxC:-O1shFa3A0kqxJ9pmTxD:bqev3vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L97)):*
> ```Go
> 
> 	// Okay to proceed with DSC. Queue up the change.
> 	b.Add(&newColType)
> ```

Think we want to queue a drop for the old type at the same time?
___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1shMD65CAEQ7dd0h-3:-O1shMD65CAEQ7dd0h-4:b-eqg15k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain#L12)):*
> ```
>  │    └── Stage 1 of 1 in StatementPhase
>  │         ├── 1 element transitioning toward PUBLIC
>  │         │    └── ABSENT → PUBLIC ColumnType:{DescID: 104 (t), ColumnFamilyID: 0 (primary), ColumnID: 2 (j), TypeName: "CHAR(25)"}
> ```

I think we should see the old type heading for drop and the new type heading towards public. Otherwise, transactional schema changes could be in trouble, because we could pick the wrong type for this column (the graph will have two in public).

For extra safety can add a rule which says the swap occurs in a single stage.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1sg_QR8PZilr4_sfyB:-O1vsubX7pcPYJPIF_ID:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L46)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Add a version check here for 24.2
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1shFa3A0kqxJ9pmTxC:-O1vszcQ8rpEMEuzlR1Q:bpfk32o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L97)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Think we want to queue a drop for the old type at the same time?
</blockquote></details>

I added the drop operation. The drop needs to be a no-op in `opgen` because `RemoveDroppedColumnType` will interfere with the type in the descriptor. It sets the type to `types.Any`, which, if done before the add, prevents the upsert from recognizing the old type, and if done after the add, will undo the change made by the upsert. `RemoveDroppedColumnType` is only emitted for user-defined types, so for trivial cases, it is already a no-op. I left a TODO comment to revisit this for more general alter type support, which should handle user-defined types.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1shMD65CAEQ7dd0h-3:-O1vxEoX621ViY82VDvz:b7xlnw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain#L12)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think we should see the old type heading for drop and the new type heading towards public. Otherwise, transactional schema changes could be in trouble, because we could pick the wrong type for this column (the graph will have two in public).

For extra safety can add a rule which says the swap occurs in a single stage.
</blockquote></details>

I added this. But I don't know about making the swap occur in a single stage. Is that strictly required? If so, how do I set that.

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1shMD65CAEQ7dd0h-3:-O1vxmwmAZ89sXbyrhHT:brdaidd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain#L12)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I added this. But I don't know about making the swap occur in a single stage. Is that strictly required? If so, how do I set that.
</blockquote></details>

Its not strictly needed yet, but probably will be as we exercise more complex txns. We would add a new rule similar to index swaps: pkg/sql/schemachanger/scplan/internal/rules/current/dep_swap_index.go. It would just say that if we are dropping and creating a column type then the drop should happen first in terms of precedence.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1shFa3A0kqxJ9pmTxC:-O2-fbz87twONB0a-zon:bml0mhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L97)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I added the drop operation. The drop needs to be a no-op in `opgen` because `RemoveDroppedColumnType` will interfere with the type in the descriptor. It sets the type to `types.Any`, which, if done before the add, prevents the upsert from recognizing the old type, and if done after the add, will undo the change made by the upsert. `RemoveDroppedColumnType` is only emitted for user-defined types, so for trivial cases, it is already a no-op. I left a TODO comment to revisit this for more general alter type support, which should handle user-defined types.
</blockquote></details>

I ended up adding the logic to ensure removing a column type for type alters doesn't emit `RemoveDroppedColumnType`.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O1shMD65CAEQ7dd0h-3:-O2-gKGL3J9XhRJBDwo-:bya2qmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9a3f12cd4a87e3feb5b1f9e1b95371bd3983aa4/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type/alter_table_alter_column_type__statement_2_of_2.explain#L12)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Its not strictly needed yet, but probably will be as we exercise more complex txns. We would add a new rule similar to index swaps: pkg/sql/schemachanger/scplan/internal/rules/current/dep_swap_index.go. It would just say that if we are dropping and creating a column type then the drop should happen first in terms of precedence.
</blockquote></details>

I added the new dependency rule.

**Review by fqazi — APPROVED** [review]
:lgtm: Great work @spilchen 

> Reviewed 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-:-O20-KU13IbZzsO-PaR8:b-10q9c1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O2-yk1zE6F95qIJW6W-:-O2-yk1zE6F95qIJW6W0:b-3nba4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbabd14dafaca062ea2eae152d99f13a7bb84063/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L98)):*
> ```Go
> 	// Do not emit anything if the column type is not changing. The operation is a
> 	// no-op.
> 	if newColType.Equal(oldColType) {
> ```

Nit: I don't think we need this? The Add and Drop should cancel out effectively below. Or are we actually making operations.

**Review by spilchen — COMMENTED** [review]
Thanks for reviewing @fqazi 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-:-O20IORQ9cBle1mUi4p6:b-z4diro)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go` line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127151#-O2-yk1zE6F95qIJW6W-:-O20HzoaDBOnBb2iR4FV:b-tvbqnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbabd14dafaca062ea2eae152d99f13a7bb84063/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_type.go#L98)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: I don't think we need this? The Add and Drop should cancel out effectively below. Or are we actually making operations.
</blockquote></details>

You are correct. Previously, I had decomposed the operation into an "add" followed by a "drop," which required this check. However, with the correct order being "drop" followed by "add," the two operations cancel each other out. Therefore, this check is no longer needed, and I have removed it.

**Comment by spilchen** [comment]
tftr @fqazi 

bors r+

**Pull request merged**
