### PR TITLE
changfeedccl: Fix schema feed test flake

### LINKED ISSUE #116011: ccl/changefeedccl/schemafeed: TestTableHistoryIngestionTracking failed
ccl/changefeedccl/schemafeed.TestTableHistoryIngestionTracking [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/13075157?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/13075157?buildTab=artifacts#/) on release-23.2 @ [43a2532550ca7abfc3c5682df31b0cc20da934b0](https://github.com/cockroachdb/cockroach/commits/43a2532550ca7abfc3c5682df31b0cc20da934b0):

Fatal error:

```
panic: test timed out after 4m55s
running tests:
	TestTableHistoryIngestionTracking (4m55s)

```
Stack: 

```
goroutine 31 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestTableHistoryIngestionTracking
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTableHistoryIngestionTracking.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34377

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #116011

Release notes: None

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
Could you explain why deleting the earlier waiter at timestamp 8 fixes the problem? I understand that there is one fewer goroutine that needs to wake up but shouldn't the second goroutine at timestamp 8 wake up regardless?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116101#-:-NlQOvXyARy2i2J0NfJ-:b-p2p858)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

___
*[`pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116101#-NlQ7sQt8OvjdSCIIZ58:-NlQ7sQt8OvjdSCIIZ59:b-n3eczh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9778734198a6771318081421a637d79f5b0f5a/pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go#L153)):*
> ```Go
> 
> 	// This test is very brittle and probably needs to be rewritten.
> 	// Clear out any waiters we may have (ts(8)).  This waitor
> ```

nit: s/waitor/waiter
___
*[`pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116101#-NlQN3Qr2icqSLWhPEvd:-NlQN3Qr2icqSLWhPEve:b-4bz7df) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9778734198a6771318081421a637d79f5b0f5a/pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go#L162)):*
> ```Go
> 		m.mu.Lock()
> 		defer m.mu.Unlock()
> 		m.mu.waiters = m.mu.waiters[:0]
> ```

Instead of manually clearing the waiters ourselves, should we instead delete the waiter in `waitForTS` when the context is canceled?

**Review by andyyang890 — COMMENTED** [review]
Oh I see, the send in `adjustTimestamps` will be blocking.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116101#-:-NlQQ7qh2B_M1icxCuSC:b-raamo2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

**Review by andyyang890 — COMMENTED** [review]
(Disregard my previous comment.)

We discussed this offline and determined that the actual bug is that the highwater is incorrectly cached between mutex lock calls (there is an implicit lock and unlock in `tf.highWater()`):
https://github.com/cockroachdb/cockroach/blob/e9a6d3d7c935dd347a4254729edf2db8c764dcbf/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L528-L549

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116101#-:-NlQV8F9BZA9Tt6Q5HRm:b-r6bwfl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116101#-:-NlQj4euEEOQm5rnsVbO:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

**Comment by miretskiy** [comment]
> It looks like your PR touches production code but doesn't add or edit any test code. Did you consider adding tests to your PR?
> 
> 🦉 Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).

The existing (flaky) test is no longer flaky.

**Comment by andyyang890** [comment]
blathers backport 23.1 23.2

**Pull request merged**
