### PR TITLE
sql: Fix window functions with column references above windowing

### PR DESCRIPTION
**Pull request by nvb**
Given a legal query like `SELECT a + rank() OVER () FROM x`, we would
previously return an incorrect value for all but the last row processed
by the underlying `selectNode`. The problem was that `a` would be replaced
by an `IndexedVar`, and when the `a + rank() OVER()` was evaluated for each
row (after reading in all rows), `a` would always have the same value.
This was because `selectNode` (which is the `IndexesVar's`
`IndexedVarContainer`) never changes its `curSourceRow` once it has
completed processing.

The solution was to walk the expressions in `windowNode's` constructor
after the `extractWindowFuncsVisitor` has been run and replace all
`IndexedVars` above the windowing layer with new `IndexedVars` that
point to `windowNode` as their `IndexedVarContainer`.

This was requested by @andreimatei, who is already recklessly abusing
window functions.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10186)

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/window.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186#-KUudHaow5Lh0mt6wU2O:-KUudHaprFMSqIlNA69n:b-pqgzml) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35c420608b926ff0a9aa8c22ad0b63ed13e1f3d/pkg/sql/window.go#L95)):*
> ```Go
> 	window.wrappedRenderVals = p.NewRowContainer(renderCols, 0)
> 	window.wrappedWindowDefVals = p.NewRowContainer(windowDefCols, 0)
> 	window.wrappedIndexedVarVals = p.NewRowContainer(indexedVarCols, 0)
> ```

Is the additional row container necessary?

Please check the implementation of `upsertHelper.IndexedVarEval()` and its friends in `upsert.go`. Is that something you could use here?

---

*[pkg/sql/window.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186#-KUudq5_B7CnWC6zG0-X:-KUudq5_B7CnWC6zG0-Y:b-l7mjuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35c420608b926ff0a9aa8c22ad0b63ed13e1f3d/pkg/sql/window.go#L290)):*
> ```Go
> 				// We add a new render to the wrapped selectNode for each new IndexedVar we
> 				// see. We also register this mapping in the ivarIdxMap.
> 				s.render = append(s.render, iv)
> ```

I feel like we would gain from a check that this particular indexedvar is not already rendered, and otherwise use the existing render. It looks to me you would see the same column used multiple times if there are multiple window functions. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/window.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186#-KUudHaow5Lh0mt6wU2O:-KUwMpG-nGNsn-qRLbxN:bxpcwyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35c420608b926ff0a9aa8c22ad0b63ed13e1f3d/pkg/sql/window.go#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Is the additional row container necessary?
> 
> Please check the implementation of `upsertHelper.IndexedVarEval()` and its friends in `upsert.go`. Is that something you could use here?
</details>
I might be missing your question, but the issue here is that we can't stream these values row-by-row like `upsertHelper` can, instead we need to let the underlying `planNode` finish before we can move on (there's a term for it that I'm forgetting and it's driving me crazy). Because of that, we need to buffer all of these values. 

---

*[pkg/sql/window.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186#-KUudq5_B7CnWC6zG0-X:-KUwNLXbWkSmliNuVq2u:bycgjos) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35c420608b926ff0a9aa8c22ad0b63ed13e1f3d/pkg/sql/window.go#L290)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I feel like we would gain from a check that this particular indexedvar is not already rendered, and otherwise use the existing render. It looks to me you would see the same column used multiple times if there are multiple window functions. What do you think?
</details>
Multiple window functions will still only add a single render for each necessary column used, that's what the `n.ivarIdxMap[iv.Idx]; !ok` check above is providing. We will have up to 2 renders if the column is used above the windowing and below (ie. `SELECT a, a + max(b) over (), a + rank() over () from t` -> `s.renders = [a, b, a]`), but I'm not too concerned about that. We're already messing with the `selectNode's` renders, and this allows us to split the values in `Next` up in a straightforward way. I'll add an `EXPLAIN (TYPES)` test to demonstrate this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/window.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186#-KUudHaow5Lh0mt6wU2O:-KUwZTkUkwEOn6alwaMA:b-59g0af) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35c420608b926ff0a9aa8c22ad0b63ed13e1f3d/pkg/sql/window.go#L95)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I might be missing your question, but the issue here is that we can't stream these values row-by-row like `upsertHelper` can, instead we need to let the underlying `planNode` finish before we can move on (there's a term for it that I'm forgetting and it's driving me crazy). Because of that, we need to buffer all of these values. 
</details>
What I don't get is that these 3 row containers contain the same number of rows, and they get populated at the same time. 
On top of that wrappedRenderVals and wrappedIndexedVarVals have the same lifetime. So I would suggest using a single row container for both where each row is the concatenation of both the render vals and the indexedvar vals. Does this make more sense?

---

*[pkg/sql/window.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186#-KUudq5_B7CnWC6zG0-X:-KUwZu5LQ9kKu-Is8b57:b-g803yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35c420608b926ff0a9aa8c22ad0b63ed13e1f3d/pkg/sql/window.go#L290)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Multiple window functions will still only add a single render for each necessary column used, that's what the `n.ivarIdxMap[iv.Idx]; !ok` check above is providing. We will have up to 2 renders if the column is used above the windowing and below (ie. `SELECT a, a + max(b) over (), a + rank() over () from t` -> `s.renders = [a, b, a]`), but I'm not too concerned about that. We're already messing with the `selectNode's` renders, and this allows us to split the values in `Next` up in a straightforward way. I'll add an `EXPLAIN (TYPES)` test to demonstrate this.
</details>
Oh yes my bad I hadn't see the map above. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/window.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186#-KUudHaow5Lh0mt6wU2O:-KUwbQEwdz0JpE4fqInf:bscns6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35c420608b926ff0a9aa8c22ad0b63ed13e1f3d/pkg/sql/window.go#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> What I don't get is that these 3 row containers contain the same number of rows, and they get populated at the same time. 
> On top of that wrappedRenderVals and wrappedIndexedVarVals have the same lifetime. So I would suggest using a single row container for both where each row is the concatenation of both the render vals and the indexedvar vals. Does this make more sense?
</details>
Ah yeah you're completely right that the three row containers could be combined into one. The reason I did it this way (and split the single one in the first commit into two) was for clarity. I found the original approach difficult to work with. This way is a lot easier to extend and conceptualize, and I'm not very concerned with the small fixed amount of overhead associated with it. It also breaks the dependency between how renders are added and how their values are "parsed" in `Next`, and how the rest of the code works with these different data sources, which is a nice side-effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10186)*

**Comment by knz** [comment]
Ok thanks for explaining. LGTM

Just put a TODO above the container definition to highlight they have the same lifetime but are separated for clarity.

**Comment by knz** [comment]
(not TODO sorry)

**Comment by nvanbenschoten** [comment]
Done. Thanks for the review @knz.

**Pull request merged**
