### PR TITLE
release-22.1: storage: omit `MVCCIterator.Stats()` call during `MVCCScan`/`MVCCGet`

### PR DESCRIPTION
**Pull request by erikgrinaker**
Backport:

* #86084
* #74342

/cc https://github.com/orgs/cockroachdb/teams/release

---

Release justification: performance improvements.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@nvanbenschoten How do you feel about backporting these? I very much doubt the perf gains are as large on 22.1, since much of this is likely due to the new range key iterator infrastructure in Pebble.

**Comment by jbowens** [comment]
I don’t think the stats calls became any more expensive with the introduction of range keys, so if we’re not calling it more with range keys I think we’ll see the same perf win. m

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86094#-:-NAjQVoe0M-ffq_el7Rf:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by erikgrinaker** [comment]
Performance improvements don't qualify for backports, closing this out.

**Pull request closed without merging**
