### PR TITLE
server: declare node ready while decommissioning

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, a decommissioning or draining, but otherwise healthy,
node would return an error from the /health?ready=1 endpoint, thus
declaring itself unready and signaling load balancers to send traffic
away. This patch makes it so that the decommissioning status no longer
matters for the readyness determination. Draining nodes continue to
declare themselves unready.
Note that decommissioning nodes typically go through draining at the
end of the process.

The justification is that a node can be decommissioning for an arbitrary
amount of time. During that time it can continue to hold leases, etc. So
trying to avoid traffic is not particularly desirable. In fact, some
people even want to keep a node in a decommissioning state indefinitely
(by restarting a decommissioning node without recommissioning it).
Also, the server.shutdown.drain_wait cluster setting is there to give
load balancers ample time to find out about a draining node.

Also, tactically, the code is simplified.

Release note (general change): A node no longer declares itself to not
be ready through the /health/ready=1 endpoint while it's in the process
of decommissioning. It continues to declare itself unready while
draining.

### CODE REVIEW

**Comment by andreimatei** [comment]
started a discussion about the change here
https://groups.google.com/forum/#!topic/cockroach-db/P3v85IJIycE

**Comment by andreimatei** [comment]
I got a nod from @asubiotto on the mailing list, so I think this is good to go

**Review by ajwerner — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43889#-:-LyZhxWOAS4ygng14ZiU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43889#-:-Ly_fEa3ADBjp9RYjXlH:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by andreimatei — COMMENTED** [review]
flaked on #43957

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43889#-:-Ly_kRdpBOqY1ikTNOU9:b38nst)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Pull request merged**
