### PR TITLE
fix a race condition in a test

### LINKED ISSUE #3629: replicateQueue.shouldQueue races against unknown
https://circleci.com/gh/tschottdorf/cockroach/1929 in (I think) `TestDates` (likely could happen in any test).

```
WARNING: DATA RACE
Read by goroutine 54:
  github.com/cockroachdb/cockroach/storage.(*replicateQueue).shouldQueue()
      /go/src/github.com/cockroachdb/cockroach/storage/replicate_queue.go:84 +0x2ec
  github.com/cockroachdb/cockroach/storage.(*baseQueue).MaybeAdd()
      /go/src/github.com/cockroachdb/cockroach/storage/queue.go:239 +0x4d8
  github.com/cockroachdb/cockroach/storage.(*replicateQueue).MaybeAdd()
      <autogenerated>:112 +0x67
  github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess.func1()
      /go/src/github.com/cockroachdb/cockroach/storage/scanner.go:185 +0x127
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:116 +0x283
  github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess()
      /go/src/github.com/cockroachdb/cockroach/storage/scanner.go:187 +0x385
  github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1()
      /go/src/github.com/cockroachdb/cockroach/storage/scanner.go:217 +0xaf
  github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit()
      /go/src/github.com/cockroachdb/cockroach/storage/store.go:225 +0x45b
  github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
      /go/src/github.com/cockroachdb/cockroach/storage/scanner.go:219 +0x451
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x5f

Previous write by goroutine 17:
  [failed to restore the stack]

Goroutine 54 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x6f
  github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop()
      /go/src/github.com/cockroachdb/cockroach/storage/scanner.go:240 +0x105
  github.com/cockroachdb/cockroach/storage.(*replicaScanner).Start()
      /go/src/github.com/cockroachdb/cockroach/storage/scanner.go:108 +0x118
  github.com/cockroachdb/cockroach/storage.(*Store).Start.func4()
      /go/src/github.com/cockroachdb/cockroach/storage/store.go:578 +0x160
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x5f

Goroutine 17 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck()
      /go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x2e
  github.com/cockroachdb/cockroach/sql/driver.TestMain()
      /go/src/github.com/cockroachdb/cockroach/sql/driver/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/sql/driver/_test/_testmain.go:64 +0x209
==================
```

### PR DESCRIPTION
**Pull request by andreimatei**
don't have two Servers running at the same time

fixes #3629

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3813)

### CODE REVIEW

**Comment by petermattis** [comment]
Mind spelling out what the race is. It isn't obvious why running two Servers at the same time is problematic.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/driver/driver_test.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-K7wtliyMl3Ej-2zngUY:-K7wtliyMl3Ej-2zngUZ:79919269) ([raw file](https://github.com/cockroachdb/cockroach/blob/784c1cd020b0fe9ff4cf3bda6af64e6506b32f60/sql/driver/driver_test.go#L81)):*
FYI, you can keep this in `TestData` by using a closure that you invoke right away:

```
  func() {
    server, db := setup(t, loc)
    defer cleanup(server, db)
  }()
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-:-K7wu0DMzvAz6vDw8gJc:2115485550)*

**Comment by tschottdorf** [comment]
LGTM, but what @petermattis says.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-:-K7wwFfmt_BnZ0c5E-rl:-1697705248)*

**Comment by andreimatei** [comment]
The race is rather obscure - it's on a ZoneConfig read from the Scanner (
github.com/cockroachdb/cockroach/storage.(*replicateQueue).shouldQueue()
      /go/src/github.com/cockroachdb/cockroach/storage/replicate_queue.go:84
)

and written during TestServer setup
https://github.com/cockroachdb/cockroach/blob/9da9375a1cac0368a7bc01263be2cbda9e024879/server/testserver.go#L178

I don't know enough about these ZoneConfigs to understand if the read
should be protected in any way?
Regardless, I assumed that running two of these servers in a process is
probably not sane. For example, there was another race that happened much
more infrequently when I was stressing this that I didn't look into (and it
went away now). Is it surprising that two Servers is no bueno?

**Comment by bdarnell** [comment]
Yes, it's surprising that you can't run two `TestServers` in a process. It's also bad that `TestServer` doesn't clean up after itself when it modifies the globals. @mberhault how close are we to being able to set the zone config in some other way?

**Comment by andreimatei** [comment]
OK I've talked to @bdarnell and @mrtracy a bit. Maybe this is not the right solution for this, but it sounds like we don't currently have a way to modify ZoneConfigs for ranges outside sql tables. One idea was to make the `DefaultZoneConfig` a member of the `StoreConfig` so it's not a global any more. I'll check with @mberhault about what he thinks the way to solve this is.

**Comment by mberhault** [comment]
moving the default zone config (as well as zone config for non-structured span and system DB) is still a TODO: https://github.com/cockroachdb/cockroach/issues/2506
Not sure on the ETA.

**Comment by andreimatei** [comment]
ok I've talked to @mberhault. Seems like for now this fix is the best idea so I'll merge it unless someone objects. Somebody will need to figure out the zone config story for all ranges before beta and get rid of this global default.

I've added some cleanup to `TestServer` so that the global is at least restored when the server is shut down.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/driver/driver_test.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-K7wtliyMl3Ej-2zngUY:-K80NaQpK8pOSSB4Fawf:-468414451) ([raw file](https://github.com/cockroachdb/cockroach/blob/6380ef9ce6d2926fd63a713794f38f7492c4dd53/sql/driver/driver_test.go#L81)):*
wouldn't this stop the server too soon, right after setup? Or are you suggesting putting the whole test body in the closure?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-:-K80OA7CP5fGy0wxzCko:1641401460)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/driver/driver_test.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-K7wtliyMl3Ej-2zngUY:-K80RTzMu7tNe3w-aK8K:-1580272731) ([raw file](https://github.com/cockroachdb/cockroach/blob/6380ef9ce6d2926fd63a713794f38f7492c4dd53/sql/driver/driver_test.go#L81)):*
Yeah, the idea is to put the whole thing in the closure.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-:-K80RcQFvLw_20RBrdND:676834233)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/driver/driver_test.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813#-K7wtliyMl3Ej-2zngUY:-K80TCMvCjQ-yFsKBstL:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/6380ef9ce6d2926fd63a713794f38f7492c4dd53/sql/driver/driver_test.go#L81)):*
+1

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3813)*

**Comment by tschottdorf** [comment]
@petermattis: test failure on this branch looks cgo-spooky: https://circleci.com/gh/cockroachdb/cockroach/11378

**Comment by tschottdorf** [comment]
is this a "RocksDB was already closed" type of scenario again?

```
goroutine 1967 [syscall, locked to thread]:
runtime.cgocall(0xe1ba70, 0xc82077f590, 0x0)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc82077f548 sp=0xc82077f518
github.com/cockroachdb/cockroach/storage/engine._Cfunc_DBNewIter(0x0, 0x1, 0x0)
	??:0 +0x3a fp=0xc82077f590 sp=0xc82077f548
github.com/cockroachdb/cockroach/storage/engine.newRocksDBIterator(0x0, 0x1, 0xd)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:499 +0x2e fp=0xc82077f5c0 sp=0xc82077f590
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).NewIterator(0xc820286870, 0xc82010f201, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:257 +0x3d fp=0xc82077f5f0 sp=0xc82077f5c0
github.com/cockroachdb/cockroach/storage/engine.InMem.NewIterator(0xc820286870, 0x100000001, 0x0, 0x0)
	<autogenerated>:72 +0x4c fp=0xc82077f618 sp=0xc82077f5f0
github.com/cockroachdb/cockroach/storage/engine.mvccPutInternal(0x7f0ada719798, 0xc820286870, 0x0, 0xc82032cb40, 0x6, 0x6, 0x0, 0x0, 0xc82097d220, 0x43,
```

**Comment by bdarnell** [comment]
Yeah, looks like "rocksdb already closed". This could be a misleading stack trace: `TestNodeJoin` uses four separate stoppers, and if BootstrapCluster fails or createAndStartTestNode panics, those stoppers will not be stopped but the engine stopper will be.

**Comment by tschottdorf** [comment]
@andrei can you get this merged (unless the test failure should somehow be related)? It's still prominent in builds.

**Pull request merged**
