### PR TITLE
rpc: cleanup latencyInfos for closed connection

### LINKED ISSUE #95772: rpc: cleanup latencyInfos for closed connections to avoid stale data
**Is your feature request related to a problem? Please describe.**
Currently, when connection between nodes is closed, `RemoteClocksMonitor` still 
keeps recent latency information for closed connections as well. This can mislead
and provide incorrect metrics about closed connection.

**Describe the solution you'd like**
Clean up `latencyInfos` map for all closed connections.

Related Jira epic: [CRDB-21710](https://cockroachlabs.atlassian.net/browse/CRDB-21710)

Jira issue: CRDB-23728

### PR DESCRIPTION
**Pull request by koorosh**
Before, `RemoteClockMonitor` tracked most recent measurements on remote latency from connected node and didn't clean up this info after connection is closed. It led to keeping stale information about latency between nodes even if it doesn't exist anymore. Current change introduces `OnDisconnect` func that is called when heartbeat failed and connection closed.
This change will be necessary for upcoming changes to properly observe network partition between particular nodes.

Release note: None

Related to [CRDB-21710](https://cockroachlabs.atlassian.net/browse/CRDB-21710)
Resolves #95772

### CODE REVIEW

**Comment by knz** [comment]
cc @andrewbaptist since you were looking at this code recently too.

**Review by knz — APPROVED** [review]

**Comment by andrewbaptist** [comment]
This PR will conflict with the PR I have outstanding (and hoping to merge today) #95701. I would recommend waiting for to merge first and then change this to use `NodeID` rather than `addr`. 

I'm a little concerned about the fact that we clear all information for a node when a single connection disconnects since the node may have multiple open connections. It seems like this would be better if we kept a counter of open connections and only clear this when the counter gets to zero.

**Comment by knz** [comment]
Yeah that is indeed a concern, we have multiple connection classes and so one different connection per class.

Also, Andrew's PR just merged

**Comment by koorosh** [comment]
> It seems like this would be better if we kept a counter of open connections and only clear this when the counter gets to zero.

@andrewbaptist , thanks for suggestion! Updated PR to track down number of connections.

**Review by tbg — APPROVED** [review]

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/rpc/clock_offset.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95818#-NMjIzl546rUbLgYIJcl:-NMjIzl546rUbLgYIJcm:bhk3ob9) ([raw file](https://github.com/cockroachdb/cockroach/blob/043f3537b20f57e66525e2aaa220d4348b165265/pkg/rpc/clock_offset.go#L196)):*
> ```Go
> 	ctx context.Context, id roachpb.NodeID, offset RemoteOffset, roundTripLatency time.Duration,
> ) {
> 	emptyOffset := offset == RemoteOffset{}
> ```

Can we remove this emptyOffset handling as part of this PR as well. It was attempting to do the same thing, but didn't do it correctly. Having both mechanisms will be confusing.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/rpc/clock_offset.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95818#-NMjIzl546rUbLgYIJcl:-NMmg16E0dNrGFcWnZNW:bso7d54) ([raw file](https://github.com/cockroachdb/cockroach/blob/043f3537b20f57e66525e2aaa220d4348b165265/pkg/rpc/clock_offset.go#L196)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Can we remove this emptyOffset handling as part of this PR as well. It was attempting to do the same thing, but didn't do it correctly. Having both mechanisms will be confusing.
</blockquote></details>

I'm not quite sure it handles the same cases. 

In  `UpdateOffset`, `offsets` map is cleaned up when:
- heartbeat response comes back but it took more time than allowed, so offset isn't taken into account and set to empty;
- and when recent offset value is stale. 
- it doesn't clean up `latencyInfos` in this case because it might be useful to track cases with increased latency responses;

In `OnDisconnect` func, `offsets` map is cleaned when heartbeat didn't respond and connection is closed;

I'd rather keep both cases if I understand this logic properly.

**Review by andrewbaptist — APPROVED** [review]
You are right about them being slightly different. You might want to add a comment relating to this as it is a little confusing today, but I'm changing this to approve.

**Comment by koorosh** [comment]
> You might want to add a comment relating to this as it is a little confusing

Definitely, will add comments to make it more clear for future readers. 
TFTR!

**Pull request merged**
