### PR TITLE
opt: show columns hidden by presentation

### PR DESCRIPTION
**Pull request by RaduBerinde**
Example:
```
 group-by
 ├── columns: sum:4(decimal)  hidden: b:2(int!null)
```

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

Maybe add brackets around the hidden columns to further delimit them?
```
  group-by
  ├── columns: sum:4(decimal)  [hidden: b:2(int!null)]
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32141#-:-LQOrnO16FbfiKGTH3Xt:bb990dx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
Added brackets.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32141#-:-LQWjDKJ7Yuhu8AR7plx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/expr_format.go, line 633 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32141#-LQWhq5z8B9l4AOuYTtq:-LQWhq5z8B9l4AOuYTtr:b34zlul) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb15d2f51a0b2a543ee9f54c747d3f737d34319/pkg/sql/opt/memo/expr_format.go#L633)):*
> ```Go
> 
> // toList converts a ColSet to a ColList, in column ID order.
> func toList(set opt.ColSet) opt.ColList {
> ```

Seems like this function should go in `metadata_column.go` to be parallel with `ToSet`, which does the reverse of this function.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32141)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/expr_format.go, line 633 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32141#-LQWhq5z8B9l4AOuYTtq:-LQoLaJr5hk24js4OO-V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb15d2f51a0b2a543ee9f54c747d3f737d34319/pkg/sql/opt/memo/expr_format.go#L633)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like this function should go in `metadata_column.go` to be parallel with `ToSet`, which does the reverse of this function.
</blockquote></details>

Done.

**Pull request merged**
