### PR TITLE
cli: Add --listening-url-file flag

### LINKED ISSUE #13327: cli: add --listening-url-file flag
There are many cases (like https://github.com/cockroachdb/cockroach-go/pull/24) where exposing Cockroach on a random, automatically assigned port is desired. For instance, it is useful to avoid `address already in use` errors when running multiple instances of Cockroach side-by-side. This can be accomplished using the `--port` flag when running `cockroach start`, and setting this value to `0`, which uses [`ListenTCP`](https://golang.org/pkg/net/#ListenTCP)'s automatic port selection functionality.

However, in cases where a port is automatically assigned, a user cannot know the address to communicate with Cockroach ahead of time. Instead, they must wait for Cockroach to tell them where to connect. Currently, the only way to find this address is to parse the startup logs and find the line that looks like `sql: postgresql://root@localhost:26257?sslmode=disable`. We should introduce a more structured method to retrieve this targetted feedback from new Cockroach servers.

The current idea here is to add a new `--listening-url-file` flag, which would specify a filename to which the url would be written once startup is complete. This is analogous to PID files, where the process id of a running process is stored in a file in a well-known location. Implementation of this will need to handle error cases and cleanup on server shutdown in a similar manner to PID files.

### PR DESCRIPTION
**Pull request by pydima**
Closes #13327.

### CODE REVIEW

**Comment by tamird** [comment]
Thank you for the contribution! Could you add a simple test, as well? Looks good otherwise.

cc @a-robinson because CLI flags.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/server.go, line 867 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KipBV5M9C0auke0YsQY:-KipBV5M9C0auke0YsQZ:b-5gakw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f9d79313a4acc64d6ce92ed3c9243bc5d389c8/pkg/server/server.go#L867)):*
> ```Go
> 		pgURL, err := s.cfg.PGURL(url.User(security.RootUser))
> 		if err == nil {
> 			err = ioutil.WriteFile(s.cfg.ListeningURLFile, []byte(fmt.Sprintf("%s\n", pgURL)), 0644)
> ```

I'm not sure we want this newline, but I don't feel strongly. I think a simple test will make the choice clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-:-KipBXdH-ewnfRu3n3U8:b2ibnp0)*

**Comment by pydima** [comment]
Thanks for your review, I've added a simple test case.

---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/server.go, line 867 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KipBV5M9C0auke0YsQY:-KipuKYoiqBWGiHUqfkv:b-2ijn2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f9d79313a4acc64d6ce92ed3c9243bc5d389c8/pkg/server/server.go#L867)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I'm not sure we want this newline, but I don't feel strongly. I think a simple test will make the choice clearer.
</blockquote></details>

My intention here was to follow the way how it's done with PID files and it has a new line, but I'm totally OK to change this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-:-Kipv01VQIxeMY5sSb88:bg3jrz0)*

**Comment by tamird** [comment]
Looking good! Just a few questions.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/server_test.go, line 498 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KipwpeLY-Tb33HnBl7s:-Kipw0qRyij0E2AQrr2a:b-sf4fsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1723c997fdfe9f1a7ab229ef5684adf5bbc28ae/pkg/server/server_test.go#L498)):*
> ```Go
> 	defer s.Stopper().Stop(context.TODO())
> 	defer func() {
> 		os.Remove(filePath)
> ```

would you mind checking the error here?

```
defer func() {
  if err := os.Remove(filePath); err != nil {
    t.Fatal(err)
  }
}()
```

---

*[pkg/server/server_test.go, line 501 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-Kipx4EBXWPWT04C_RI-:-Kipx4EBXWPWT04C_RI0:bfqusvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1723c997fdfe9f1a7ab229ef5684adf5bbc28ae/pkg/server/server_test.go#L501)):*
> ```Go
> 	}()
> 
> 	testutils.SucceedsSoon(t, func() error {
> ```

is this retry loop required? I would have expected StartServer to return only after the file was written.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-:-KipxAWV-MYlQ3D_cph7:b-iv6jtu)*

**Comment by pydima** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/server_test.go, line 498 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KipwpeLY-Tb33HnBl7s:-Kiq02o6eQWpjMij35Dz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1723c997fdfe9f1a7ab229ef5684adf5bbc28ae/pkg/server/server_test.go#L498)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

would you mind checking the error here?

```
defer func() {
  if err := os.Remove(filePath); err != nil {
    t.Fatal(err)
  }
}()
```
</blockquote></details>

Done.

---

*[pkg/server/server_test.go, line 501 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-Kipx4EBXWPWT04C_RI-:-KipyBIIYy1EVLBr3GNj:b-glgl4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1723c997fdfe9f1a7ab229ef5684adf5bbc28ae/pkg/server/server_test.go#L501)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this retry loop required? I would have expected StartServer to return only after the file was written.
</blockquote></details>

You're right, looked at wrong place in code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468)*

**Comment by tamird** [comment]
I think this is almost ready to go. We've had some badness on master, so you'll need to rebase, and then I left a minor comment.

Thanks again for your contribution!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/server_test.go, line 491 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KiqWyFq5DgvzcSqCo6n:-KiqWyFq5DgvzcSqCo6o:b-17b1vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db7fb26135ac402d7a4eb6a48e49a7ef9c43499/pkg/server/server_test.go#L491)):*
> ```Go
> 	}
> 
> 	file, err := ioutil.TempFile(cwd, "listening_url_file")
> ```

Would you mind using os.TempDir instead of cwd? Also, could you make the file name include t.Name() so it's clear where it came from, in case that ever matters?

---

*[pkg/server/server_test.go, line 495 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KiqcBvkjNW5_AOpByV5:-KiqcBvkjNW5_AOpByV6:bpmimax) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db7fb26135ac402d7a4eb6a48e49a7ef9c43499/pkg/server/server_test.go#L495)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	file.Close()
> ```

optional: check this error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-:-KiqbJS4HI8w39pZlooB:b71mn54)*

**Comment by pydima** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/server_test.go, line 491 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KiqWyFq5DgvzcSqCo6n:-Kirz31jXU820OpLTMRS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db7fb26135ac402d7a4eb6a48e49a7ef9c43499/pkg/server/server_test.go#L491)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Would you mind using os.TempDir instead of cwd? Also, could you make the file name include t.Name() so it's clear where it came from, in case that ever matters?
</blockquote></details>

Done.

---

*[pkg/server/server_test.go, line 495 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468#-KiqcBvkjNW5_AOpByV5:-Kirz3pWwsEMt8KuUKPM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db7fb26135ac402d7a4eb6a48e49a7ef9c43499/pkg/server/server_test.go#L495)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

optional: check this error
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15468)*

**Comment by tamird** [comment]
Thank you!

**Pull request merged**
