### PR TITLE
sql: add json{,b}_to_record{,set}; recordtype srfs

### LINKED ISSUE #70037: sql: support json_populate_record, json_populate_recordset, json_to_record, json_to_recordset
Needed for #69010.

This was originally tracked in https://github.com/cockroachdb/cockroach/issues/20120.

We currently don't support the following four builtin functions, which are different ways to convert an unstructured JSON datum (or set of JSON datums) into a structure record datum (or set of record datums):

* [x] `json_populate_record`
* [x] `json_populate_recordset`
* [ ] `json_to_record`
* [ ] `json_to_recordset`

As with most builtins, these have corresponding `jsonb` versions which should get identical implementations.

These builtins will be more useful once we address https://github.com/cockroachdb/cockroach/issues/70036.

Epic CRDB-10300

Jira issue: CRDB-9913

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #70037

This commit adds support for the family of four json{,b}_to_record{,set}
functions, which deconstruct JSON input (either an object or an array)
and return a row or set of rows with well-typed elements from the JSON,
governed by the *table alias* that the function is invoked with.

For example, the query below deconstructs the input JSON, returning each
of the keys "requested" by the table alias definition. Missing keys are
replaced with `NULL`.

```
SELECT * FROM json_to_record('{"a": "b", "c": true}') AS t(a TEXT, z INT)
----
b  NULL
```

The logic that governs the type casting from JSON to SQL mimics the
logic in the similar `json_populate_record` family of functions, and
should be identical to Postgres's such logic. It's permissible to use
the virtual table type to deconstruct a sub-object into a record field
within the top level JSON, like this:

```
CREATE TABLE mytable (a INT, b TEXT)

SELECT * FROM json_to_record('{"foo": {"a": 3, "b": "bar"}}') AS t(foo mytable)
----
(3,bar)

```

Functions like these ones that return record types in PostgreSQL must be
aliased to a named and typed tuple (like `AS t(a INT, b INT)`) to be
usable. As a result, this commit:

1. adds parser support for this form of alias, with types
2. pushes the alias information for an aliased expression down the
	optimizer's call stack so that the aliased expression can access the
	alias information. Previously, the aliased expression was blind to
	any aliases that were applied to it.
3. teaches the generator function factories to get the alias information
	plumbed in as well.

Release note (sql change): add the json{,b}_to_record{,set} builtin
functions, which transform JSON into structured SQL records.

Release justification: low risk, high reward change to existing functionality

### CODE REVIEW

**Comment by jordanlewis** [comment]
Hi @mgartner, would you please take a look at the optimizer changes required for this? The crux of the difficulty was that we needed to pass in the alias information (e.g. `AS t(x INT, y INT)`) into the set-generating function that is being aliased, which is of course backward. So it required some sneaky behavior.

**Review by rytaft — COMMENTED** [review]
Cool! I just looked at the optimizer files for now

> Reviewed 2 of 41 files at r1, 4 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-:-N7n9Duk0m6dPZCPMI_s:b-gs97jz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @rafiss)

___
*[`pkg/sql/opt/optbuilder/select.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N7n8HFr4AjACcKu232-:-N7n8HFr4AjACcKu2320:b8o9wan) ([raw file](https://github.com/cockroachdb/cockroach/blob/5995ec11bae973c8812ed195ad1d6301c2569fca/pkg/sql/opt/optbuilder/select.go#L49)):*
> ```Go
> 	}(inScope.atRoot)
> 	inScope.atRoot = false
> 	if b.lastAlias != nil {
> ```

Did you try using the `scope` for this field instead of `Builder`? Intuitively I would think `scope` should be the right place for it.
___
*[`pkg/sql/opt/optbuilder/srfs.go` line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N7n8jcH8gE4gjP4cFOp:-N7n8jcH8gE4gjP4cFOq:b6wv51e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5995ec11bae973c8812ed195ad1d6301c2569fca/pkg/sql/opt/optbuilder/srfs.go#L146)):*
> ```Go
> // (SRF) such as generate_series() or unnest(). It synthesizes new columns in
> // outScope for each of the SRF's output columns.
> func (b *Builder) finishBuildGeneratorFunction(
> ```

You should add some tests for these functions in `opt/optbuilder/testdata/srfs` that exercise this logic
___
*[`pkg/sql/opt/optgen/cmd/optgen/metadata.go` line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N7n7qRw59PEeUqY54zY:-N7n7qRw59PEeUqY54zZ:b-t5zpdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5995ec11bae973c8812ed195ad1d6301c2569fca/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L210)):*
> ```Go
> 		"WindowFrame":         {fullName: "memo.WindowFrame", passByVal: true},
> 		"FKCascades":          {fullName: "memo.FKCascades", passByVal: true},
> 		"ColumnDefList":       {fullName: "tree.ColumnDefList", passByVal: true},
> ```

Why do you need to add this here? Doesn't look like you've updated any `opt` files

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82435)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rafiss, and @rytaft)

___
*[`pkg/sql/opt/optbuilder/select.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N7n8HFr4AjACcKu232-:-N8AVr018jKUwd9K1uhs:b2mzoc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5995ec11bae973c8812ed195ad1d6301c2569fca/pkg/sql/opt/optbuilder/select.go#L49)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did you try using the `scope` for this field instead of `Builder`? Intuitively I would think `scope` should be the right place for it.
</blockquote></details>

This is a good point. I've moved the lastAlias field into scope.
___
*[`pkg/sql/opt/optbuilder/srfs.go` line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N7n8jcH8gE4gjP4cFOp:-N8AcH87DASz71ZibbTc:b-yr0g2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5995ec11bae973c8812ed195ad1d6301c2569fca/pkg/sql/opt/optbuilder/srfs.go#L146)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You should add some tests for these functions in `opt/optbuilder/testdata/srfs` that exercise this logic
</blockquote></details>

Done, added some tests that try to break the scoping logic.
___
*[`pkg/sql/opt/optgen/cmd/optgen/metadata.go` line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N7n7qRw59PEeUqY54zY:-N8AW1un5M-RwPbx3eRQ:bnpwwbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5995ec11bae973c8812ed195ad1d6301c2569fca/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L210)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why do you need to add this here? Doesn't look like you've updated any `opt` files
</blockquote></details>

Good point, I think this was leftover from a different way I was trying to solve this problem.

**Review by rytaft — COMMENTED** [review]
> Reviewed 3 of 13 files at r4, 3 of 5 files at r5, 1 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82435)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @rafiss)

___
*[`pkg/sql/opt/optbuilder/scope.go` line 639 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N8OvRihAN530UM6AqQR:-N8OvRihAN530UM6AqQS:bki9f7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a3dcb05858b214a39909f0d9a4737a91f9059a/pkg/sql/opt/optbuilder/scope.go#L639)):*
> ```Go
> // statement, or nil if there was none.
> func (s *scope) getLastAlias() *tree.AliasClause {
> 	for ; s != nil; s = s.parent {
> ```

When would we want to get the last alias from the parent scope?
___
*[`pkg/sql/opt/optbuilder/select.go` line 55 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N8Ouuy6AK70Gnin4ddJ:-N8Ouuy6AK70Gnin4ddK:b11qxrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a3dcb05858b214a39909f0d9a4737a91f9059a/pkg/sql/opt/optbuilder/select.go#L55)):*
> ```Go
> 			defer func() { b.lastAlias = nil }()
> 		}
> 	*/
> ```

Looks like this is dead code now
___
*[`pkg/sql/opt/optbuilder/select.go` line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N8Ovmga3NpbeszHlaPL:-N8Ovmga3NpbeszHlaPM:b-bkprmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a3dcb05858b214a39909f0d9a4737a91f9059a/pkg/sql/opt/optbuilder/select.go#L72)):*
> ```Go
> 		outScope = b.buildDataSource(source.Expr, indexFlags, locking, inScope)
> 
> 		inScope.lastAlias = previousLastAlias
> ```

This is fine, but one reason I suggested using `scope` was that I thought you might be able to allocate a new scope for building the data source and only use the `lastAlias` from the current scope (i.e., not look in the parent). Then you wouldn't need to save and restore the previous alias. Maybe that doesn't work, though?

**Review by jordanlewis — COMMENTED** [review]
Alright, PTAL. It would definitely be nice to land this but I know it's a big change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-:-NA7yM60EZHMaS2ewMd7:bgynih9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rafiss, and @rytaft)

___
*[`pkg/sql/opt/optbuilder/scope.go` line 639 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N8OvRihAN530UM6AqQR:-NA7yHVw8AL4pkIZKbDm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a3dcb05858b214a39909f0d9a4737a91f9059a/pkg/sql/opt/optbuilder/scope.go#L639)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

When would we want to get the last alias from the parent scope?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/select.go` line 55 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N8Ouuy6AK70Gnin4ddJ:-NA7yGsG9gRg6j4X3_1u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a3dcb05858b214a39909f0d9a4737a91f9059a/pkg/sql/opt/optbuilder/select.go#L55)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Looks like this is dead code now
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/select.go` line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-N8Ovmga3NpbeszHlaPL:-NA7yILy6E2iPEipS7OI:blagre1) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a3dcb05858b214a39909f0d9a4737a91f9059a/pkg/sql/opt/optbuilder/select.go#L72)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is fine, but one reason I suggested using `scope` was that I thought you might be able to allocate a new scope for building the data source and only use the `lastAlias` from the current scope (i.e., not look in the parent). Then you wouldn't need to save and restore the previous alias. Maybe that doesn't work, though? 
</blockquote></details>

Good point, please take another look.

**Comment by rafiss** [comment]
For what it's worth, the Hasura team recently reached out to us again saying that this change would improve CockroachDB support, though we haven't yet identified the priority.

**Review by rytaft — APPROVED** [review]
Optimizer stuff :lgtm:
@rafiss will you be able to review the rest? Otherwise I can look in more detail at the rest...

> Reviewed 1 of 22 files at r3, 6 of 21 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-:-NAAnx3RCdOMMTwZPtTS:b42bxfi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

**Review by rafiss — CHANGES_REQUESTED** [review]
i reviewed the non-opt parts, and they look good to me with one nit inline, and one question -- do you know if the syntax changes will work OK in a mixed version cluster?

as for merging, my feeling is that as long as the above is fine, this seems like a purely additive change and it's known to be highly beneficial for tools we want to support, so perhaps we should make an exception and merge it during the stability period?

> Reviewed 1 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-:-NAFKNaA9V3ObcgZr2oy:b-llsui4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @mgartner)

___
*[`pkg/sql/parser/sql.y` line 365 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/82435#-NAFJ0F24CQnWzOMd3fH:-NAFJ0F6Bvt4sCSvrhWV:b-3oyj60) ([raw file](https://github.com/cockroachdb/cockroach/blob/747b47d5359b62ba8e5c4f1450a5480891b7653c/pkg/sql/parser/sql.y#L365)):*
> ```Yacc
>     return u.val.(*tree.ColumnTableDef)
> }
> func (u *sqlSymUnion) colDef() tree.ColumnDef {
> ```

should the return values for the two new functions here be pointers?

**Comment by jordanlewis** [comment]
>  do you know if the syntax changes will work OK in a mixed version cluster?

The new generator functions will fail at runtime with a somewhat cryptic error "unexpected mismatched types/labels list in json record generator %v %v". I can fix this if you like, I don't think it's really important because it's net new functionality.

> we should make an exception and merge it during the stability period?
+1

> should the return values for the two new functions here be pointers?

I don't see a strong reason, do you? Lots of similar methods in the parser return values, and the thing being returned here is quite small a struct.

**Comment by jordanlewis** [comment]
@rafiss is it expected that this PR would edit function OIDs? I'm not familiar with the latest here. Example failure:

``` 
        expected:
            upper  upper  upper  829

        but found (query options: "") :
            upper  upper  upper  833
```

I assume this is because this PR is adding 4 new functions. I'll just amend the PR with the updates, but hoping for confirmation this is all good.

**Comment by rafiss** [comment]
It's expected; see https://cockroachlabs.slack.com/archives/C04U1BTF8/p1660567442297489?thread_ts=1660445734.576339&cid=C04U1BTF8 and https://github.com/cockroachdb/cockroach/pull/86008

**Review by rafiss — APPROVED** [review]

**Comment by rafiss** [comment]
> >    do you know if the syntax changes will work OK in a mixed version cluster?
>
> The new generator functions will fail at runtime with a somewhat cryptic error "unexpected mismatched types/labels list in json record generator %v %v". I can fix this if you like, I don't think it's really important because it's net new functionality.

I also wanted to make sure the syntax changes didn't affect any other existing commands

**Comment by jordanlewis** [comment]
> I also wanted to make sure the syntax changes didn't affect any other existing commands

They do not.

**Pull request merged**
