### PR TITLE
sql: clean up some long argument lists in fetchers

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR is a pure refactor that replaces some overly-long argument lists with argument structs.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 14 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78539#-:-Mz2vLorADcMVupwWLl1:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @miretskiy)

___
*[pkg/sql/row/fetcher.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78539#-Mz2uPWP5RHbbYZlBIVt:-Mz2uPWP5RHbbYZlBIVu:b-yc2si3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3041697b20ae8de8bcf595ff2a87c6460c25ea79/pkg/sql/row/fetcher.go#L218)):*
> ```Go
> 
> // Init sets up a Fetcher for a given table and index. If we are using a
> // non-primary index, tables.ValNeededForCol can only refer to columns in the
> ```

nit: might as well update this comment - `tables.ValNeededForCol` has been removed in favor of `IndexFetchSpec`.

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Courtesy rebase, will bors it once CI is green :)

**Comment by jordanlewis** [comment]
Thanks! Sorry, this slipped my notice - I recently reconfigured my GitHub notifications and hopefully that is going to improve my time-to-response on GitHub back to something reasonable.

**Comment by jordanlewis** [comment]
bors r_

**Pull request merged**
