### PR TITLE
storage: synchronize replica destruction on readOnlyCmdMu

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10583)

### CODE REVIEW

**Comment by tamird** [comment]
This causes TestReplicaCommandQueueInconsistent to deadlock. I'm investigating.

**Comment by tamird** [comment]
This ready for a look.

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 2034 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10583#-KWE5KaW85_ptDPxpqdV:-KWE5KaW85_ptDPxpqdW:b-8ar5qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a75e6d3b892758f4c6b1468f9e496854f5666b30/pkg/storage/store.go#L2034)):*
> ```Go
> 		log.Fatalf(ctx, "unexpectedly overlapped by %v", placeholder)
> 	}
> 	delete(s.mu.replicaPlaceholders, rep.RangeID)
> ```

Was there a purpose to the movement of this deletion? Seemed more consistent where it was previously (next to the other map deletions).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10583#-:-KWE5Uk6cEZY6lztDgJW:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 2034 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10583#-KWE5KaW85_ptDPxpqdV:-KWE6kiL3f2tEfCL8Snx:b-41r3jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a75e6d3b892758f4c6b1468f9e496854f5666b30/pkg/storage/store.go#L2034)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Was there a purpose to the movement of this deletion? Seemed more consistent where it was previously (next to the other map deletions).
</details>
It was to more closely match the bodies of `addPlaceholderLocked` and `removePlaceholderLocked`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10583)*

**Pull request merged**
