### PR TITLE
sql: avoid tenant ID reuse

### LINKED ISSUE #100615: sql: avoid tenant ID reuse
Tenant ID reuse is known to incur correctness problems in the following two cases:

-  we do not yet wait for server shutdown when the service mode is changed to 'NONE'. This makes it possible to start dropping a tenant and then reusing its ID before servers from the previous record have fully shut down. This creates a possibility for a past server to start serving traffic for a freshly created tenant, which is unacceptable.

-   we have a cache of tenant capabilites on every node. We do not yet implement an invalidation protocol to clear that cache upon tenant deletion. This makes it possible for requests from a new tenant to be authorized using the capabilities of a previous tenant, which is also unacceptable.

Until we implement the necessary synchronization, we can avoid the correctness issues by preventing ID reuse.

Jira issue: CRDB-26522

### PR DESCRIPTION
**Pull request by knz**
As per [internal conversation](https://cockroachlabs.slack.com/archives/C02HWA24541/p1680631136839209).

We really want to use different tenant IDs every time, to avoid tenant
ID reuse. For this, we use a new sequence `system.tenant_id_seq`.

However, there are two obstacles that prevent us from using only the
sequence.

The first is that the sequence is added in a migration and at the
point this function is called the migration may not have been
run yet.

Separately, we also have the function
`crdb_internal.create_tenant()` which can define an arbitrary tenant
ID.

So we proceed as follows:
- we find the maximum tenant ID that has been used so far. This covers
  cases where the migration has not been run yet and also arbitrary
  ID selection by create_tenant().
- we also find the next value of the sequence, if it exists already.
- we take the maximum of the two values (plus one) as the next ID.
- we also update the sequence with the new value we've chosen.

Fixes #100615.
Replaces #100613 if successful.
Epic: CRDB-23559

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Thanks for jumping on this!

Overall, the logic in tenant_creation.go seems to make sense to me. My main request is a few tests here that assert that IDs aren't reused after tenant GC finishes and one that also tests that if we have a manual ID from create_tenant we handle that as intended.

**Comment by knz** [comment]
RFAL

> a few tests here that assert that IDs aren't reused after tenant GC finishes

Done.

> and one that also tests that if we have a manual ID from create_tenant we handle that as intended.

Done.

**Review by stevendanna — APPROVED** [review]
Left a few comments but nothing major.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101322)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @rhu713, and @stevendanna)

___
*[`pkg/sql/tenant_creation.go` line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101322#gh-1166546596:-NSzqgVB-fs6eOpdNf2N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ed93a6ec1a63a44d8083e9eefc6a4e0304a65ef/pkg/sql/tenant_creation.go#L580)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Rather than having this testing hook looked at multiple times in this function, it might be a bit cleaner to have somewhere near the top

```
if testingEnableTenantIDReuse {
    return getNextAvailableIDWithReuseForTesting(...)
}
```
</blockquote></details>

Done.
___
*[`pkg/sql/tenant_creation.go` line 597 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101322#gh-1166631992:-NSzqhCG5H2-AD0a3P1J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ed93a6ec1a63a44d8083e9eefc6a4e0304a65ef/pkg/sql/tenant_creation.go#L597)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Must will panic, but I think in this case we may be OK with that since an invalid tenant ID means we've written something incorrect to our tenants table.

But, if we wanted to avoid the possibility of a panic here, we are already returning an error, so we could use MakeTenantID
</blockquote></details>

Done.
___
*[`pkg/ccl/backupccl/backup_test.go` line 6858 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101322#gh-1166626759:-NSzqjWH1okFY4TbluIS:b-j5462) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ed93a6ec1a63a44d8083e9eefc6a4e0304a65ef/pkg/ccl/backupccl/backup_test.go#L6858)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

My expectation here is that the primary reason these tests fails without reuse is that the testing setup only creates a certificates for tenants 10, 11, 20, and 2. So, any tenant we connect to needs one of those IDs.

Perhaps in a follow-up PR, we could add a set of embedded certs that aren't so restricted.
</blockquote></details>

I tried that and then I ran into other types of issues. I also think this is not exactly worth investigating, because the primary purpose of these tests is to exercise backup/restore, not the assignment of tenant IDs.

**Comment by knz** [comment]
github ci failure is unrelated: #101544

**Comment by knz** [comment]
@stevendanna could you assist with the remaining CI failure here? `TestDataDriven` in ccl/backupccl is now timing out. I can't discern a specific reason why it would time out; it just does so reliably in CI (and I can't repro locally).

**Comment by knz** [comment]
@stevendanna RFAL

**Comment by knz** [comment]
All right this looks solid now so i'll go with it.

bors r=stevendanna

**Pull request merged**
