### PR TITLE
opt: Enable additional logic tests for opt configs

### PR DESCRIPTION
**Pull request by andy-kimball**
Enable more logic tests (orms -> snapshot_unrelated_update).
Fix various bugs and issues that were failing tests.

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/pgoidtype, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDcV60S9_MDsE1YDRm5:-LDcV60S9_MDsE1YDRm6:b-ye4mhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c617cb0543a1b8686df5b47ec2ca760e7c13b5d/pkg/sql/logictest/testdata/logic_test/pgoidtype#L52)):*
> ```
> 
> query TTTTT
> EXPLAIN (TYPES) SELECT 'pg_constraint'::REGCLASS
> ```

why did you remove this test?

---

*[pkg/sql/logictest/testdata/logic_test/select_index, line 473 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDcWZzlAXevFVv24WEy:-LDcWZzlAXevFVv24WEz:b4rxuht) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c617cb0543a1b8686df5b47ec2ca760e7c13b5d/pkg/sql/logictest/testdata/logic_test/select_index#L473)):*
> ```
> 
> query IT rowsort
> SELECT i, s FROM ab WHERE (i, s) < (1, 'c')
> ```

why did you delete this test?

---

*[pkg/sql/logictest/testdata/logic_test/select_non_covering_index_filtering, line 151 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDcX6NI2Y88OaGm66gO:-LDcX6NJ2xCTengJUU66:b-kauhv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c617cb0543a1b8686df5b47ec2ca760e7c13b5d/pkg/sql/logictest/testdata/logic_test/select_non_covering_index_filtering#L151)):*
> ```
> 
> query I rowsort
> SELECT a FROM t WHERE b = 2 OR ((b BETWEEN 2 AND 1) AND ((s != 'a') OR (s = 'a')))
> ```

Did you add this test in a different file?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-:-LDcYta_95hydM-iPvyw:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/pgoidtype, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDcV60S9_MDsE1YDRm5:-LDd9mVl51BpDWFHtwaw:b59jl49) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c617cb0543a1b8686df5b47ec2ca760e7c13b5d/pkg/sql/logictest/testdata/logic_test/pgoidtype#L52)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why did you remove this test?
</blockquote></details>

It's redundant with the next several non-explain tests. We should only use `EXPLAIN` if it's contributing additional information, and this didn't seem to be contributing anything worthwhile.

---

*[pkg/sql/logictest/testdata/logic_test/select_index, line 473 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDcWZzlAXevFVv24WEy:-LDdAD9IC6NHeV-OMvoY:b-d7tzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c617cb0543a1b8686df5b47ec2ca760e7c13b5d/pkg/sql/logictest/testdata/logic_test/select_index#L473)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why did you delete this test?
</blockquote></details>

I don't see a good reason to delete it, so maybe I mistakenly thought it was redundant with the test below. I restored it.

---

*[pkg/sql/logictest/testdata/logic_test/select_non_covering_index_filtering, line 151 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDcX6NI2Y88OaGm66gO:-LDdCAT6BNJChvvEHiwv:bu5h5wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c617cb0543a1b8686df5b47ec2ca760e7c13b5d/pkg/sql/logictest/testdata/logic_test/select_non_covering_index_filtering#L151)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Did you add this test in a different file?
</blockquote></details>

Executing this with the new optimizer requires the lookup join operator, which we don't yet implement. When I split it, I think I skipped it because it was giving an execution error, and forgot to add it back in. Good catch.

I've added the variation into the `select_index` test, but commented it out with at TODO for Justin to re-enable once he merges his PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26143)*

**Comment by rytaft** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/sem/tree/type_check.go, line 756 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDfS-DO9p1qaticrrq0:-LDfS-DPE7Ski4Bv_54u:b-fwwdkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a9dcb8d0cbc903529f4cb6e7e683817c0e069f/pkg/sql/sem/tree/type_check.go#L756)):*
> ```Go
> 		return expr, nil
> 	}
> 	return nil, pgerror.NewErrorf(pgerror.CodeInternalError, "name \"%s\" is not defined", name)
> ```

Did you mean to set this back to the way it was before?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26143)*

**Comment by andy-kimball** [comment]
Review status: 8 of 93 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sem/tree/type_check.go, line 756 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-LDfS-DO9p1qaticrrq0:-LDgJnETCQ6I8xEh6XOI:btwoban) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a9dcb8d0cbc903529f4cb6e7e683817c0e069f/pkg/sql/sem/tree/type_check.go#L756)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Did you mean to set this back to the way it was before?
</blockquote></details>

I consolidated the error message changes into one commit that I was going to include in the next PR. But I see now that I've got to pull it into this PR, as the tests aren't succeeding. I've merged that commit into this PR. Can you take a look?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26143)*

**Review by knz — APPROVED** [review]

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26143#-:-LDgV9raEprF-ddkEz7S:bnfp4nl)*

**Pull request merged**
