### PR TITLE
rac2,replica_rac2: use SendTokenWatcher to pop from send-queue

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #130433

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
This lacks tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-:-O8HUmUd1vhdVh-NmccO:bfpv8ic)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — COMMENTED** [review]
Approach 
:lgtm: -- will re-review once tests are in.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-:-O8HeUET8R3V9cYFl-0W:bp0sgvs)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HdfGO4REnEteZRHIR:-O8HdfGP1po5_hbJ3XxQ:b-mfviym) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2196)):*
> ```Go
> }
> 
> func (rss *replicaSendStream) stopAttemptingToEmptySendQueue(ctx context.Context, disconnect bool) {
> ```

nit: `stopAttemptingToEmptySendQueueLocked`
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8Hdo4LDWckPw3ritHS:-O8Hdo4LDWckPw3ritHT:b-jiqof2) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2201)):*
> ```Go
> }
> 
> func (rss *replicaSendStream) stopAttemptingToEmptySendQueueViaWatcher(
> ```

nit: `stopAttemptingToEmptySendQueueViaWatcherLocked` -- although that is quite the mouthful, is that why the Locked suffix is omitted?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HecF14GsouTy_h-h-:-O8HecF14GsouTy_h-h0:b-gpunii) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2209)):*
> ```Go
> 		rss.mu.sendQueue.deductedForSchedulerTokens = 0
> 	}
> 	if rss.mu.sendQueue.tokenWatcherHandle != (SendTokenWatcherHandle{}) {
> ```

nit: this might be cleaner:

```go
if handle := rss.mu.sendQueue.tokenWatcherHandle; handle != (SendTokenWatcherHandle{}) {
		rss.parent.parent.opts.SendTokenWatcher.CancelHandle(ctx, handle)
```

Also consider specifying a zero value var `EmptySendTokenWatcherHandle` and comparing against that instead of `SendTokenWatcherHandle{}`
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HeMMB3Kv4mpwNSimG:-O8HeMMB3Kv4mpwNSimH:b-2frmyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2215)):*
> ```Go
> }
> 
> func (rss *replicaSendStream) startAttemptingToEmptySendQueueViaWatcher(ctx context.Context) {
> ```

nit: `startAttemptingToEmptySendQueueViaWatcherLocked`
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HeC3RDNQzMgjwL_HW:-O8HeC3RDNQzMgjwL_HX:b5hg24k) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2259)):*
> ```Go
> }
> 
> func (rss *replicaSendStream) approxQueueSize() kvflowcontrol.Tokens {
> ```

nit: `approxQueueSizeLocked`

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

Adjusted some of the existing tests.

Still needs more tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-:-O8IB_pEAvarpegR_Okr:b-ilwpzn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HdfGO4REnEteZRHIR:-O8I9x2UE1GmkctHtaj0:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2196)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: `stopAttemptingToEmptySendQueueLocked`
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8Hdo4LDWckPw3ritHS:-O8IA-t50iAYvU1kLEKd:bp47y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2201)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: `stopAttemptingToEmptySendQueueViaWatcherLocked` -- although that is quite the mouthful, is that why the Locked suffix is omitted?
</blockquote></details>

It was inadvertent. In recent PRs I have been inconsistent. Added, and fixed a few other cases.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HecF14GsouTy_h-h-:-O8IAQOIEq4w0kzut7hh:b-j71o38) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2209)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: this might be cleaner:

```go
if handle := rss.mu.sendQueue.tokenWatcherHandle; handle != (SendTokenWatcherHandle{}) {
		rss.parent.parent.opts.SendTokenWatcher.CancelHandle(ctx, handle)
```

Also consider specifying a zero value var `EmptySendTokenWatcherHandle` and comparing against that instead of `SendTokenWatcherHandle{}`
</blockquote></details>

Done. I didn't add a zero value, since I can't make it a const.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HeMMB3Kv4mpwNSimG:-O8IA8oNBzAbJCQqaJvx:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2215)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: `startAttemptingToEmptySendQueueViaWatcherLocked`
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8HeC3RDNQzMgjwL_HW:-O8IAmk_4iWaOQgqYiS1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bfdbbcbd6b862a274b81c6c3f05cd6b06d782e/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2259)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: `approxQueueSizeLocked`
</blockquote></details>

Done

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 15 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-:-O8IJ3XMEIzG-2F6nhWU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-O8IIcV75tl7aFZAMSmo:-O8IIcV75tl7aFZAMSmp:b8uqe3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67c11ad23b826922fc97060c6b7ebc9df69c9bf/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush#L43)):*
> ```
>   term=1 index=3  tokens=1048576
> ++++
> (n2,s2):2: state=replicate closed=false inflight=[1,1) send_queue=[1,4) precise_q_size=+3.0 MiB watching-for-tokens
> ```

This is a nice change, the output is easier to grok.

**Review by kvoli — APPROVED** [review]

**Review by sumeerbhola — COMMENTED** [review]
Added send_q_watcher and fixed a bug. Also verified that code coverage with the test is good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131818#-:-O8IRRI23bxX4IfvninS:b-xq4h8v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
