### PR TITLE
roachtest: remove --tolerate-errors from schema change

### LINKED ISSUE #47430: Categorize all validation errors in `sqlbase`
`structured.go` has a few validate functions that return uncategorized pg errors. i.e code `XXUUU`. We should categorize them with the appropriate pg error.

### PR DESCRIPTION
**Pull request by otan**
I was able to run this for ~1 hour successfully locally.

Resolves #47430 (not sure if I'm missing something here)

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55220#-:-MItkILd7bZKf4XwSAH-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
Looks like this fails version-upgrade because 20.1 does not have all these errors categorised.

Should I leave --tolerate-errors on for version-upgrade, or change the min version to v20.2 (since we already have tests for 20.1 -> 20.2 running presumably on the 20.2 branch?)

**Comment by lucy-zhang** [comment]
Aren't we using `roachtest` on master for roachtests on all release branches? I think there was some talk of maybe changing that, but that's how it is for now. What if you just set that flag on or off in the test depending on the cockroach version?

**Comment by otan** [comment]
I think there's a mixed version thing-a-ma-bob here: https://sourcegraph.com/github.com/cockroachdb/cockroach/-/blob/pkg/cmd/roachtest/mixed_version_schemachange.go#L27:15

**Comment by lucy-zhang** [comment]
I was thinking of something like this https://github.com/cockroachdb/cockroach/blob/20fc710f16dde471b39704563c0d94aa15d73932/pkg/cmd/roachtest/schemachange.go#L423

**Comment by otan** [comment]
gotcha

**Comment by otan** [comment]
bors r=ajwerner

**Pull request merged**
