### PR TITLE
make check: add `misspell` and fix typos

### PR DESCRIPTION
**Pull request by tamird**
Temporarily work around https://github.com/client9/misspell/issues/28.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4342)

### CODE REVIEW

**Comment by tschottdorf** [comment]
That's really pushing the boundary on "linting" (the again, I was tempted to send a PR to fix all the typos when I saw the report card, which is about as insane). How long does the misspell lint run locally?

**Comment by tamird** [comment]
```
real	0m0.331s
user	0m0.779s
sys	0m0.062s
```

**Comment by petermattis** [comment]
While I appreciate these linters keeping our code sane, the time `make check` takes (~30 sec) is becoming a small irritant. Perhaps we should remove `check` from the `all` target and only run it manually. We would still have it run by CircleCI, so nothing should accidentally slip by.

**Comment by tamird** [comment]
Yeah, I think that's reasonable. I'd also be open to pulling out the slow bits and leaving the fast ones in the critical path.

**Comment by tamird** [comment]
BTW, can I merge this? It adds 300ms to `make check`.

**Comment by petermattis** [comment]
LGTM

**Pull request merged**
