### PR TITLE
storage: don't assert on-disk ReplicaState after Raft log truncations 

### LINKED ISSUE #23347: storage: investigate excessive calls to assertStateLocked
We seem to be calling `assertStateLocked` when `ReplicatedEvalResult.State != nil`, but `*ReplicatedEvalResult.State == storagebase.ReplicaState{}`. Noticed when running `tpcc -warehouses=10 -no-wait` against a local single node cockroach cluster.

```diff
diff --git a/pkg/storage/replica_proposal.go b/pkg/storage/replica_proposal.go
index 0343ccfba..9c1b2ef6c 100644
--- a/pkg/storage/replica_proposal.go
+++ b/pkg/storage/replica_proposal.go
@@ -484,9 +484,17 @@ func (r *Replica) handleReplicatedEvalResult(
                r.store.splitQueue.MaybeAdd(r, r.store.Clock().Now())
        }

+       if rResult.State != nil && (*rResult.State == storagebase.ReplicaState{}) {
+               rResult.State = nil
+       }
+
        // The above are always present, so we assert only if there are
        // "nontrivial" actions below.
        shouldAssert = !rResult.Equal(storagebase.ReplicatedEvalResult{})
+       if shouldAssert {
+               diff := pretty.Diff(rResult, storagebase.ReplicatedEvalResult{})
+               fmt.Printf("shouldAssert: %s\n", diff)
+       }

        // Process Split or Merge. This needs to happen after stats update because
        // of the ContainsEstimates hack.
```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #23347.

This change reduces the frequency that we perform on-disk == in-memory
ReplicaState assertions. These assertions are fairly expensive because
they need to load the entire ReplicaState from disk, so performing them
after Raft log truncations was gratuitous.

An earlier commit also fixes a bug where it was possible for a GC request to
create a non-nil but empty `ReplicaState`, which would trigger this assertion
for no reason. This is no longer possible.

This change is borderline too critical to cherry-pick. I'll defer to
others on that decision.

Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

I'm OK with cherry-picking this if the performance gains are not trivial. @petermattis how much time was spent here in the TPCC runs that prompted #23347?

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23410#-:-L6s772MOnTYuiE0-YUo:b499nzb)*

**Comment by petermattis** [comment]
> I'm OK with cherry-picking this if the performance gains are not trivial. @petermattis how much time was spent here in the TPCC runs that prompted #23347?

It wasn't large (a few single digit percent), but that can be deceptive in a CPU profile. It would be good to do some before/after testing with `kv --min-block-bytes=4096 --max-block-bytes=4097`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23410#-:-L6sDdUZHHX3s534F2Ym:b-8lx8f2)*

**Comment by tschottdorf** [comment]
:lgtm:
Did not review the code movements in the third commit in detail except for their spirit.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23410#-:-L6st5MccFaRBLwtH17w:b671sk2)*

**Comment by nvanbenschoten** [comment]
> It would be good to do some before/after testing with kv --min-block-bytes=4096 --max-block-bytes=4097.

I ran `kv` (4KB and 64 KB) with the assertion disabled entirely, both locally and on a three-node cluster. I wasn't able to see a significant performance difference in either setup. This does fit my expectation because I don't think we'll start to see this make a difference until a benchmark is close to maxing out a cluster's CPU (as we see in TPC-C). I'm going to try again with a single node cluster running TPC-C at its limit, right where its latency tanks, and see if disabling the assertion makes any difference.

**Comment by nvanbenschoten** [comment]
I ran more tests with `assertStateLocked` conditionally disabled. This time, I ran the tests on a 3-node cluster with `n1-standard-16` nodes. I brought TPC-C's warehouse count up to its latency inflection point, which was at about 1800 warehouses. Around this point, we know that the cluster becomes CPU bound. I then ran a series of 5-minute tests with the assertion enabled and disabled. I didn't see any noticeable impact on the performance.

Because the performance gains are not significant here, I'm only going to cherry-pick the first and second commit in this PR. The third has a bit too much code movement to justify.

**Pull request merged**
