### PR TITLE
jobs: paginate job deletions

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, a cleanup iteration (which happens once per hour per
node) would only cleanup up to 1k rows. This patch makes it cleanup up
all eligible jobs, and do so in batches smaller than 1000. We've seen a
case where having 3 ndoes trying to cleanup 1000 jobs at once led to
thrashing.

Release note: None

### CODE REVIEW

**Review by ajwerner — CHANGES_REQUESTED** [review]
This is good stuff. I'm going to slap a `backport-20.2` label on this bad boy. 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57041#-:-MMrjgOq0MSAQuuxk2tL:balzh1m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/jobs/registry.go, line 719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57041#-MMrf82a2FGCUcgNLnpj:-MMrf82b0Jcc_TPmrTD8:b-yrw4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cf0863af19c9e01be52c653c373e3ce1e4d4987/pkg/jobs/registry.go#L719)):*
> ```Go
> 		// nodes restart at once.
> 		jitterFraction := rand.Float64() / 6
> 		timer.Reset(time.Duration(float64(gcInterval()) * jitterFraction))
> ```

This isn't how we usually jitter. I'm not even really clear on what this means. It's multiplying the interval by a random number uniform from `[0, 1/6)`. I feel like what you want here is:

```
const jitter = 1/6
jitterFraction := 1 + (2 * rand.Float64() - 1) * jitter
jitterredDuration := float64(gcInterval()) * jitterFraction
```
___
*[pkg/jobs/registry_test.go, line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57041#-MMrjVx08khlucRU-tJG:-MMrjVx08khlucRU-tJH:bqaicl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f012f5a81898182993366f410bd85090f19e9f79/pkg/jobs/registry_test.go#L399)):*
> ```Go
> 
> 	ts := timeutil.Now()
> 	require.NoError(t, s.JobRegistry().(*Registry).cleanupOldJobs(ctx, ts.Add(-10*time.Minute)))
> ```

any interest in gathering a trace on the context and sussing out how many pages there were? You could even randomize it a bit and check that the number is what you expect.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57041)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57041#-MMrf82a2FGCUcgNLnpj:-MMrnkMw2kp1XPivEjVP:bbvwp7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cf0863af19c9e01be52c653c373e3ce1e4d4987/pkg/jobs/registry.go#L719)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This isn't how we usually jitter. I'm not even really clear on what this means. It's multiplying the interval by a random number uniform from `[0, 1/6)`. I feel like what you want here is:

```
const jitter = 1/6
jitterFraction := 1 + (2 * rand.Float64() - 1) * jitter
jitterredDuration := float64(gcInterval()) * jitterFraction
```
</blockquote></details>

done, 10x
___
*[pkg/jobs/registry_test.go, line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57041#-MMrjVx08khlucRU-tJG:-MMrn1ol2K3p1NKjr_RI:b5tseso) ([raw file](https://github.com/cockroachdb/cockroach/blob/f012f5a81898182993366f410bd85090f19e9f79/pkg/jobs/registry_test.go#L399)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

any interest in gathering a trace on the context and sussing out how many pages there were? You could even randomize it a bit and check that the number is what you expect. 
</blockquote></details>

Not particularly, to be honest. I think the assumption that the deletion takes more than one iteration is safe enough (and even that there were 3 pages). On a less busy day I would nevertheless, but I'm taking the rest of the week off, and so... Next time.

Unrelated, I'm kinda scared because `TestRegistryGC` above is skipped... Do you know anything about that?

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57041#-:-MMrpNCx1gv_MuehpKqt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/jobs/registry_test.go, line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57041#-MMrjVx08khlucRU-tJG:-MMrpIWTAC_lcebdYy7n:b-wbm74r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f012f5a81898182993366f410bd85090f19e9f79/pkg/jobs/registry_test.go#L399)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Not particularly, to be honest. I think the assumption that the deletion takes more than one iteration is safe enough (and even that there were 3 pages). On a less busy day I would nevertheless, but I'm taking the rest of the week off, and so... Next time.

Unrelated, I'm kinda scared because `TestRegistryGC` above is skipped... Do you know anything about that?
</blockquote></details>

sgtm and I don't know but I'll find out.

**Pull request merged**
