### PR TITLE
roachtest: add cdc/tpcc-1000/sink=null test

### PR DESCRIPTION
**Pull request by stevendanna**
This adds an example test using the new null sink. To do this it also
adds the ability to manually specify sinkURIs in the test spec.

Depends on #61526

Release note: None

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL)

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL and @stevendanna)

___
*[pkg/cmd/roachtest/cdc.go, line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62953#-MXhGmCLC1XltyVxfje8:-MXhGmCLC1XltyVxfje9:bys89su) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1573c6e3565b94e9addf297890294d21204a38/pkg/cmd/roachtest/cdc.go#L610)):*
> ```Go
> 				workloadType:             tpccWorkloadType,
> 				tpccWarehouseCount:       1000,
> 				workloadDuration:         "120m",
> ```

do we want to run for 120m?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @shermanCRL)

___
*[pkg/cmd/roachtest/cdc.go, line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62953#-MXhGmCLC1XltyVxfje8:-MXhOH_M9moOXge3eX4N:b4v2duj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1573c6e3565b94e9addf297890294d21204a38/pkg/cmd/roachtest/cdc.go#L610)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want to run for 120m?
</blockquote></details>

I'm happy to change this to whatever.  The `manual` tag further up in the spec means this won't be running in CI yet, it is just for local exploration for now (and an example of using sinkURI) and likely the kind of thing you would modify for your needs.

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL and @stevendanna)

___
*[pkg/cmd/roachtest/cdc.go, line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62953#-MXhGmCLC1XltyVxfje8:-MXhYH1l2tDXlz6jn_Nw:b32wwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1573c6e3565b94e9addf297890294d21204a38/pkg/cmd/roachtest/cdc.go#L610)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I'm happy to change this to whatever.  The `manual` tag further up in the spec means this won't be running in CI yet, it is just for local exploration for now (and an example of using sinkURI) and likely the kind of thing you would modify for your needs.
</blockquote></details>

sg

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62953)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL)

**Comment by stevendanna** [comment]
bors r=[miretskiy,HonoreDB]

**Pull request merged**
