### PR TITLE
sql: more EXPLAIN (DEBUG) implementations

### PR DESCRIPTION
**Pull request by RaduBerinde**
Split into commits, see the message for each commit. For #4110

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5227)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, 12 of 12 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/limit.go, line 103 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq57o54e-VThJIFozb:-KCq57o6P-Rn1amupd0t:-238889054) ([raw file](https://github.com/cockroachdb/cockroach/blob/81cfe75acd4bf855fb414777ca6b94f2f9eaaf98/sql/limit.go#L103)):*
is the first part of this expression necessary?

---

*[sql/sort.go, line 190 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq6jmqHB2WC2Bqekyn:-KCq6jmqHB2WC2Bqekyo:729401716) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee26e6726664c8bccc186ba74761cb00ad564d03/sql/sort.go#L190)):*
does `explainMode` implement `fmt.Stringer`? might be better to log as a string

---

*[sql/testdata/aggregate, line 547 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq69v_tu6kjTAsyV43:-KCq69v_tu6kjTAsyV44:1547331788) ([raw file](https://github.com/cockroachdb/cockroach/blob/b541a2de8556fa53fa2a672a09f7cd8482f7c67f/sql/testdata/aggregate#L547)):*
can you include a test case with an explicit GROUP BY clause?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-:-KCq6rC_5AqRsE9BL6YE:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/limit.go, line 103 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq57o54e-VThJIFozb:-KCqDC1rdkzjeU5ES1UW:-128114928) ([raw file](https://github.com/cockroachdb/cockroach/blob/81cfe75acd4bf855fb414777ca6b94f2f9eaaf98/sql/limit.go#L103)):*
Ah, no, guess I was in an "unsigned" mindset. Fixing.

---

*[sql/testdata/aggregate, line 547 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq69v_tu6kjTAsyV43:-KCqGBLopb7cz8QxV3CV:899611836) ([raw file](https://github.com/cockroachdb/cockroach/blob/b541a2de8556fa53fa2a672a09f7cd8482f7c67f/sql/testdata/aggregate#L547)):*
I verified one manually. Unfortunately GROUP BY emits the buckets in random (map) order, so we can't verify the results exactly. The debug data includes row indices so `rowsort` doesn't help.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/testdata/aggregate, line 547 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq69v_tu6kjTAsyV43:-KCqIfjLf31bzNCJkygd:472544203) ([raw file](https://github.com/cockroachdb/cockroach/blob/b541a2de8556fa53fa2a672a09f7cd8482f7c67f/sql/testdata/aggregate#L547)):*
couldn't you add an ORDER BY clause?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227)*

**Comment by RaduBerinde** [comment]
*[sql/testdata/aggregate, line 547 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq69v_tu6kjTAsyV43:-KCqIu70w-B0Ijqek0X0:2049677100) ([raw file](https://github.com/cockroachdb/cockroach/blob/b541a2de8556fa53fa2a672a09f7cd8482f7c67f/sql/testdata/aggregate#L547)):*
yes but the debug info is strong, it will show the rows being buffered into the sorting node :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227)*

**Comment by RaduBerinde** [comment]
*[sql/testdata/aggregate, line 547 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq69v_tu6kjTAsyV43:-KCqJD0Fpd6WvExBVosc:-1516853225) ([raw file](https://github.com/cockroachdb/cockroach/blob/b541a2de8556fa53fa2a672a09f7cd8482f7c67f/sql/testdata/aggregate#L547)):*
This is an example I tried:
```
query ITTT
EXPLAIN (DEBUG) SELECT v, COUNT(k) FROM kv GROUP BY v ORDER BY v DESC
----
0 /kv/primary/1    NULL      BUFFERED
0 /kv/primary/1/v  2         BUFFERED
0 /kv/primary/1/w  3         BUFFERED
0 /kv/primary/1/s  'a'       BUFFERED
1 /kv/primary/3    NULL      BUFFERED
1 /kv/primary/3/v  4         BUFFERED
1 /kv/primary/3/w  5         BUFFERED
1 /kv/primary/3/s  'a'       BUFFERED
2 /kv/primary/5    NULL      BUFFERED
2 /kv/primary/5/w  5         BUFFERED
3 /kv/primary/6    NULL      BUFFERED
3 /kv/primary/6/v  2         BUFFERED
3 /kv/primary/6/w  3         BUFFERED
3 /kv/primary/6/s  'b'       BUFFERED
4 /kv/primary/7    NULL      BUFFERED
4 /kv/primary/7/v  2         BUFFERED
4 /kv/primary/7/w  2         BUFFERED
4 /kv/primary/7/s  'b'       BUFFERED
5 /kv/primary/8    NULL      BUFFERED
5 /kv/primary/8/v  4         BUFFERED
5 /kv/primary/8/w  2         BUFFERED
5 /kv/primary/8/s  'A'       BUFFERED
0 0                (4, 2)    BUFFERED       <------ these ones here will be in random order
1 1                (NULL, 1) BUFFERED
2 2                (2, 3)    BUFFERED
0 0                (4, 2)    ROW
1 1                (2, 3)    ROW
2 2                (NULL, 1) ROW
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/testdata/aggregate, line 547 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq69v_tu6kjTAsyV43:-KCqJmkcG0Xo9Hb0x6T0:-1568866478) ([raw file](https://github.com/cockroachdb/cockroach/blob/b541a2de8556fa53fa2a672a09f7cd8482f7c67f/sql/testdata/aggregate#L547)):*
Ah, OK.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227)*

**Comment by RaduBerinde** [comment]
Actually I was able to craft an example where all the rows outputted by GROUP BY are identical. TFTR!

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-:-KCqMQjVCKr66s9OekKv:256081415)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/sort.go, line 190 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq6jmqHB2WC2Bqekyn:-KCqNuKSDq2WPQrNTsVM:677940215) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee26e6726664c8bccc186ba74761cb00ad564d03/sql/sort.go#L190)):*
ping

---

*[sql/testdata/explain_debug, line 168 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCqNo9pnAIFFgfwD8X-:-KCqNo9pnAIFFgfwD8X0:705735667) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cc04f0ef0bbb8a9e3afb3a1cbea1bb9bcc30bd/sql/testdata/explain_debug#L168)):*
are there trailing spaces here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/sort.go, line 190 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCq6jmqHB2WC2Bqekyn:-KCqOEFPYLz89xdAC5Gm:-2076872421) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee26e6726664c8bccc186ba74761cb00ad564d03/sql/sort.go#L190)):*
it does not. displaying the int value provides adequate information for debugging, we don't gain much by making it pretty

---

*[sql/testdata/explain_debug, line 168 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227#-KCqNo9pnAIFFgfwD8X-:-KCqOBw1dKN85ntEcILQ:1394151673) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cc04f0ef0bbb8a9e3afb3a1cbea1bb9bcc30bd/sql/testdata/explain_debug#L168)):*
yeah sorry fixed in the following commit

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5227)*

**Pull request merged**
