### PR TITLE
sql: Correctly send timestamps with(out) offset based on `WITH TIME ZONE`

### LINKED ISSUE #5863: sql: support `TIMESTAMP WITH(OUT) TIME ZONE`
## The spec says:

>          6) If the data type of CR is TIME or TIMESTAMP, then the implicit
>             time zone of the data is the current default time zone for the
>             SQL-session.
> 
>          7) If the data type of CR is TIME WITH TIME ZONE or TIMESTAMP WITH
>             TIME ZONE, then the time zone of the data is the time zone rep-
>             resented in the value of CR.

## When inserting a timestamp / parsing a value:
`WITHOUT ZONE` (or no modifier) does not consider the session offset.
Open Question: should it even accept a ts that has an explicit offset? If so, what should it do? (postgres does, and silently ignores it(!))

 `WITH ZONE` should use supplied offset if present to calculate UTC time and insert UTC, and should otherwise use the session offset to calculate UTC and insert that.

## When returning a timestamp:
`WITHOUT ZONE` (or no modifier) should *not* include an offset (we currently do). The session offset isn't considered and no shift is required.
`WITH ZONE` *should* include an offset when returned, and it should ideally be the session offset, thus the timestamp should be shifted as needed, since the stored time is UTC.

### LINKED ISSUE #5953: sql: error parsing string as timestamp through Postgres JDBC driver
ERROR: param $3: could not parse string "2016-04-07 23:00:02.965000 +00:00:00" as timestamp

### PR DESCRIPTION
**Pull request by dt**
A `TIMESTAMP WITH TIME ZONE` should be rendered in the session timezone and include an explicit offset, while a `TIMESTAMP` should have no offset (and some clients in fact fail to parse one with an offset).

To support that we also need to correctly parse `WITH TIME ZONE` and plumb that attribute through to/from the column type, and make the session's location available to pgwire's rendering.

Closes #5863.
Closes #5953.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6138)

### CODE REVIEW

**Comment by dt** [comment]
To clarify since there was some discussion on #5863: 
This PR does _not_ introduce a new type. As implemented, a `timestamp with time zone` and a `timestamp` are comparable, and, in a departure from the SQL spec, plain `timestamp` values are assumed to be in UTC, not "implicitly in the session timezone", for the purposes of said comparison, but, as they are returned _in UTC_ without an explicit offset, a no-offset string should round-trip un-changed.

Other than comparing them, a second potential misuse due to our departure from spec is that sending a plain `timestamp` with an offset will cause it to be shifted to UTC -- meaning it will not round-trip, and if the application assumes a non-offset when it reads it back, this could bite a user.

We'll need to cover these departures from the spec in our docs.

**Comment by petermattis** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/session.go, line 109 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjDw0VVOjzL9-CYj_P:-KFjDw0VVOjzL9-CYj_Q:-622935926) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/session.go#L109)):*
`Session.GetLocation` was previously used to lazily load time zone information so that we weren't doing it on every request. Now that we have a `Session` struct that persists in memory, it might be easier to just get rid of this and populate an `EvalContext.Timezone` field. You're most of the way there with this change anyways.

---

*[sql/table.go, line 164 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjEypAzlNjAK9rj1hs:-KFjEypAzlNjAK9rj1ht:1667852735) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/table.go#L164)):*
Is there a reason for not adding a `ColumnType.WithZone` field?

---

*[sql/parser/datum.go, line 625 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjFRNWbY1-Ik01JBQI:-KFjFRNXKEull-q8GIYU:-858694585) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/parser/datum.go#L625)):*
This won't be preserved through operations such as `<timestamp> + <interval>`. 

---

*[sql/parser/sql.y, line 2774 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjEJ1pRc3oLH2iqKZb:-KFjEJ1pRc3oLH2iqKZc:-1889082234) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/parser/sql.y#L2774)):*
Ah, you discovered `WITH_LA`!

---

*[sql/testdata/datetime, line 519 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjGD9dyBuuX4MSoVyr:-KFjGD9dyBuuX4MSoVys:217652745) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/testdata/datetime#L519)):*
Add a test case for `SELECT c + INTERVAL '1m' FROM tz`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138)*

**Comment by bdarnell** [comment]
This closes #4361.

**Comment by dt** [comment]
Alternative implementation that uses separate types for timestamps with and without offsets #6165

**Comment by dt** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/session.go, line 109 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjDw0VVOjzL9-CYj_P:-KFjZ0MoM1R01HRnMRWo:-248700639) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/session.go#L109)):*
Yeah, it seemed like we'd end up loading it on every render of a timestamp as it was, plus I like the having any failures occur at the `SET` op, rather than having to handle potential errors when it's used.

---

*[sql/table.go, line 164 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjEypAzlNjAK9rj1hs:-KFjZRhBOmgwWbiwsshN:-1828695277) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/table.go#L164)):*
No strong reason, just avoiding proto churn (esp if we decide later to switch to a new type).

---

*[sql/parser/datum.go, line 625 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138#-KFjFRNWbY1-Ik01JBQI:-KFjVgMacObhpODlRP0f:-1088857461) ([raw file](https://github.com/cockroachdb/cockroach/blob/f78a9c0b251718b25a007b0ae97a9c08b0e62dc8/sql/parser/datum.go#L625)):*
Correct. Since we didn't want to go the disparate types route, we'll always type such an expression as returning `DummyTimestamp`, regardless of the `DTimestamp` value actually passed to it at execution. If we wanted to change the return type base on the arg, I think that suggests we really do want separate types for the different args.

As is, this would always return no-offset and a user would need to cast back to tz to get an offset back :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6138)*

**Pull request closed without merging**
