### PR TITLE
Refactor storage test initialization.

### PR DESCRIPTION
**Pull request by bdarnell**
Use a struct instead of multiple return values (of which only a subset
are used on any invocation), and allow values to be pre-filled to avoid
creating additional createTestRange variants.

@spencerkimball  @cockroachdb/developers

### CODE REVIEW

**Comment by bdarnell** [comment]
If this looks good to people I'll convert the rest of the tests.

**Comment by tschottdorf** [comment]
LGTM

**Comment by spencerkimball** [comment]
LGTM. Go ahead and convert rest of tests...

**Comment by bdarnell** [comment]
OK, I've converted all the tests (and in the process moved the handful of tests that were using a real-time clock to a manual clock).

**Pull request merged**
