### PR TITLE
sql/sqlbase: move MakeTableDesc and friends to `sql`

### PR DESCRIPTION
**Pull request by dt**
Prior to this changeset, the code that translated a parsed `CREATE TABLE` statement into a TableDescriptor was split between `sql` and `sqlbase`. The main traversal of the AST to generate a TableDescriptor, implemented in `MakeTableDesc`, was in `sqlbase`, however some nodes in that AST were only handled in `sql`, e.g. those that required leasing another table to lookup an index. At best, this just made it harder to maintain and extend the related code. 

Unifying the implementation in one place will make it cleaner, safer, and easier to maintain/add support more table features that are non-trivially derived from the AST. Since execution involves e.g. resolving and leasing other tables, the unified implementation likely belongs in `sql`, not `sqlbase`.

The package-level vars in the `sqlbase` package for the system tables are set during package initialization. Prior to this changeset, this was done by parsing `CREATE TABLE` statements and calling `MakeTableDesc`. This only worked while the schemas used for those happened to only include the subset of the AST nodes that `MakeTableDesc` could correctly handle.

With `MakeTableDesc` moving to `sql`, these vars will need to be initialized some other way, with the most direct option being to include simple TableDescriptor literals, as well as a unit test (that can depend on the full, well tested and trusted implementation in `sql`) comparing the result of parsing and generating their specified schemas with the literal descriptors to ensure correctness.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8141)

### CODE REVIEW

**Comment by dt** [comment]
I think there are some other options we could pursue too, along with the reasons they weren't my fist choice:
* unifying the implementation in `sqlbase` instead, plumbing some of the the higher-level dependencies in behind an interface like `SchemaAccessor` 
  - my experience is that layers of dependency injection just gets messy, and it still doesn't solve the issue of bootstrapping before those higher-level layers are ready
* moving MakeTableDesc and the system tables both to `sql` and keeping init-time parsing/AST traversal
  - still might be only be able to handle a subset of possible `CREATE` statements though during bootstrapping, so not a complete solution.

**Comment by RaduBerinde** [comment]
Thanks for cleaning this up!  I agree this was needed, I couldn't find a good way to split this up when I created `sqlbase` and I took the path of least resistance since the change was already very big.
I also agree this is preferable to the other possibilities you mentioned.

---

Reviewed 3 of 6 files at r1, 6 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/sqlbase/system.go, line 111 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KNwfDXlCZbeR7ku3ZWM:-KNwfDXlCZbeR7ku3ZWN:52753844) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee5be6427666afcd54ed5a20ed327f9e75e85fe/sql/sqlbase/system.go#L111)):*
> ```Go
> 
> 	// NamespaceTable is the descriptor for the namespace table.
> 	NamespaceTable = TableDescriptor{
> ```

Instead of hardcoding them, would it be possible to have them be initialized by `sql` through a special call that happens during initialization? (`sql` package could have an `init()` function that generates the descriptors and calls into `sqlbase` to set these values).  Hm but that would be problematic for tests, as they would need to depend on `sql`.. So maybe this way is better (especially since we have a test that verifies they are kept correct).

Another idea would be to generate this code automatically. We could have a tiny program in a subdir that uses both `sql` and `sqlbase`, creates descriptors, uses reflection to print them out into a .go file. Then we could hook that up to a go:generate.

---

*[sql/sqlbase/system_test.go, line 26 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KNweEf7q3p7PiTNOi7A:-KNweEf7q3p7PiTNOi7B:-681695920) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8fd544d914c35c20773feb2b4edde182d96d84/sql/sqlbase/system_test.go#L26)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/roachpb"
> 	"github.com/cockroachdb/cockroach/security"
> 	"github.com/cockroachdb/cockroach/sql"
> ```

It's not great to have a `sqlbase` test depending on `sql`.. Can we move this test in `sql/` now? It's already not part of `sqlbase` so it should be easy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-:-KNwgJIupUdEiEc9J_eF:-716736743)*

**Comment by dt** [comment]
Review status: 3 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/system_table_test.go, line 26 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KNweEf7q3p7PiTNOi7A:-KO77vFc4jJ4yjDmxmt5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8fd544d914c35c20773feb2b4edde182d96d84/sql/system_table_test.go#L26)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It's not great to have a `sqlbase` test depending on `sql`.. Can we move this test in `sql/` now? It's already not part of `sqlbase` so it should be easy
</details>
Done.

---

*[sql/sqlbase/system.go, line 111 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KNwfDXlCZbeR7ku3ZWM:-KO76fpQT-wSPNLtAehN:-1960553956) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee5be6427666afcd54ed5a20ed327f9e75e85fe/sql/sqlbase/system.go#L111)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Instead of hardcoding them, would it be possible to have them be initialized by `sql` through a special call that happens during initialization? (`sql` package could have an `init()` function that generates the descriptors and calls into `sqlbase` to set these values).  Hm but that would be problematic for tests, as they would need to depend on `sql`.. So maybe this way is better (especially since we have a test that verifies they are kept correct).
> 
> Another idea would be to generate this code automatically. We could have a tiny program in a subdir that uses both `sql` and `sqlbase`, creates descriptors, uses reflection to print them out into a .go file. Then we could hook that up to a go:generate.
</details>
I'm not keen on more init-time calls: they often are happening before all the usual machinery is fully setup and in place and thus fell more brittle and hard to maintain.

I'm not opposed to the `go:generate` integration but I'm not entirely convinced it is worth the effort: the generation program would potentially need to bootstrap the `sql` package (since the point was to have a single impl of the transformation) and then that gets us right back to the same chicken-egg problem.

The current test prints the `%+v` of generated and expected, which I used to get the literals that are in there now (started with an empty struct in, let it fail and then used the output) -- not quite automated, but it dodged the bootstrapping problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 10 files at r4, 6 of 7 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/sqlbase/system.go, line 111 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KNwfDXlCZbeR7ku3ZWM:-KO7BTMr2hgMB_wWfJDl:-1075345265) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee5be6427666afcd54ed5a20ed327f9e75e85fe/sql/sqlbase/system.go#L111)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I'm not keen on more init-time calls: they often are happening before all the usual machinery is fully setup and in place and thus fell more brittle and hard to maintain.
> 
> I'm not opposed to the `go:generate` integration but I'm not entirely convinced it is worth the effort: the generation program would potentially need to bootstrap the `sql` package (since the point was to have a single impl of the transformation) and then that gets us right back to the same chicken-egg problem.
> 
> The current test prints the `%+v` of generated and expected, which I used to get the literals that are in there now (started with an empty struct in, let it fail and then used the output) -- not quite automated, but it dodged the bootstrapping problem.
</details>
The generation program would of course depend on `sql` but it can live anywhere (and in any package).

I'm ok with merging as is though, I would just add a big comment in TestSystem with an explanation appropriate for someone who has no prior knowledge of any of this (including the suggested way of producing the correct code like you mentioned). My worry is mostly someone in the future changing some descriptor and then scratching their head trying to understand the TestSystem failure.

---

*[sql/sqlbase/table.go, line 47 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KO7DvrH3balZcNSl6sR:-KO7DvrH3balZcNSl6sS:-1913608616) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a156d33947fa14d13040bd47ff3beed4ac4c697/sql/sqlbase/table.go#L47)):*
> ```Go
> // SanitizeVarFreeExpr verifies a default expression is valid, has the
> // correct type and contains no variable expressions.
> func SanitizeVarFreeExpr(expr parser.Expr, expectedType parser.Datum, context string) error {
> ```

Should this move as well (together with the error funcs above)?

---

*[sql/sqlbase/table.go, line 63 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KO7E467x68m55YcPM2_:-KO7E467x68m55YcPM2a:35230520) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a156d33947fa14d13040bd47ff3beed4ac4c697/sql/sqlbase/table.go#L63)):*
> ```Go
> // MakeColumnDefDescs creates the column descriptor for a column, as well as the
> // index descriptor if the column is a primary key or unique.
> func MakeColumnDefDescs(d *parser.ColumnTableDef) (*ColumnDescriptor, *IndexDescriptor, error) {
> ```

Should this move as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/sqlbase/system.go, line 110 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KO7ENhgZZAtZfQiNOlh:-KO7ENhgZZAtZfQiNOli:1881072773) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a156d33947fa14d13040bd47ff3beed4ac4c697/sql/sqlbase/system.go#L110)):*
> ```Go
> 	}
> 
> 	// NamespaceTable is the descriptor for the namespace table.
> ```

Also add a comment here mentioning that we verify these descriptors in TestSystemTables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141)*

**Comment by paperstreet** [comment]
Thanks for picking this off! Feel free to ignore any of my comments, :lgtm: 

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 741 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOApz0B4TAv2Tr88Yo0:-KOApz0B4TAv2Tr88Yo1:262468467) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a156d33947fa14d13040bd47ff3beed4ac4c697/sql/create.go#L741)):*
> ```Go
> 
> // MakeTableDesc creates a table descriptor from a CreateTable statement.
> func MakeTableDesc(p *parser.CreateTable, parentID sqlbase.ID) (sqlbase.TableDescriptor, error) {
> ```

:thumbsup: 

---

*[sql/system_table_test.go, line 76 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOAn_cgQDOa-5C_Hnnk:-KOAn_cgQDOa-5C_Hnnl:1953193287) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ff0a7c2038feb51608ccfe54fa112022e495a8/sql/system_table_test.go#L76)):*
> ```Go
> }
> 
> func TestSystemTables(t *testing.T) {
> ```

Comment on why this test is here.

---

*[sql/system_table_test.go, line 90 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOAnQRDAFiWrnV4YowO:-KOAnQRDAFiWrnV4YowP:917538806) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ff0a7c2038feb51608ccfe54fa112022e495a8/sql/system_table_test.go#L90)):*
> ```Go
> 		gen := sqlbase.CreateTableDescriptor(test.id, keys.SystemDatabaseID, test.schema,
> 			sqlbase.NewPrivilegeDescriptor(security.RootUser, sqlbase.SystemConfigAllowedPrivileges[test.id]))
> 		if !reflect.DeepEqual(test.pkg, gen) {
> ```

proto.Equal?

---

*[sql/system_table_test.go, line 85 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOAp2Hy57oGkiLUb7st:-KOAp2HzkEhVqbOUAvTC:-2139376391) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2fe34f1f2c63931dfaae0aa5d8877786a6658d/sql/system_table_test.go#L85)):*
> ```Go
> 	}
> 
> 	// test the tables with specific permissions
> ```

nit: upper case and punctuation

---

*[sql/sqlbase/system.go, line 33 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOAnd0VsnllPqWQwIYf:-KOAnd0VsnllPqWQwIYg:-144231161) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ff0a7c2038feb51608ccfe54fa112022e495a8/sql/sqlbase/system.go#L33)):*
> ```Go
> 	// sql CREATE commands and full schema for each system table.
> 
> 	// NamespaceTableSchema is checked in TestSystemTables.
> ```

more words, plz

---

*[sql/sqlbase/system.go, line 157 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOApYhs2aonFVA-zGdt:-KOApYhs2aonFVA-zGdu:-57283806) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2fe34f1f2c63931dfaae0aa5d8877786a6658d/sql/sqlbase/system.go#L157)):*
> ```Go
> 			{Name: "fam_2_descriptor", ID: 2, ColumnNames: []string{"descriptor"}, ColumnIDs: []ColumnID{2}, DefaultColumnID: 2},
> 		},
> 		PrimaryIndex:   pk("id"),
> ```

It seems to me that it would be better to remove these indirections and inline everything. That way, it's just a copy paste of printing them out with %+v if they ever have to be updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-:-KOAq5jAbMZ-_IHoVB59:-1557167242)*

**Comment by dt** [comment]
Review status: 3 of 12 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[sql/system_table_test.go, line 90 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOAnQRDAFiWrnV4YowO:-KOAuPvtHhngExYXpZFA:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ff0a7c2038feb51608ccfe54fa112022e495a8/sql/system_table_test.go#L90)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> proto.Equal?
</details>
Done.

---

*[sql/sqlbase/system.go, line 111 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KNwfDXlCZbeR7ku3ZWM:-KOAtm_N4PKZW3v3qMh7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee5be6427666afcd54ed5a20ed327f9e75e85fe/sql/sqlbase/system.go#L111)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The generation program would of course depend on `sql` but it can live anywhere (and in any package).
> 
> I'm ok with merging as is though, I would just add a big comment in TestSystem with an explanation appropriate for someone who has no prior knowledge of any of this (including the suggested way of producing the correct code like you mentioned). My worry is mostly someone in the future changing some descriptor and then scratching their head trying to understand the TestSystem failure.
</details>
Done.

---

*[sql/sqlbase/system.go, line 33 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOAnd0VsnllPqWQwIYf:-KOAtp-b1nAzngZb8H1b:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ff0a7c2038feb51608ccfe54fa112022e495a8/sql/sqlbase/system.go#L33)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> more words, plz
</details>
Done.

---

*[sql/sqlbase/system.go, line 157 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOApYhs2aonFVA-zGdt:-KOAt1bpuAXdZRHKAYHT:-735931934) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2fe34f1f2c63931dfaae0aa5d8877786a6658d/sql/sqlbase/system.go#L157)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> It seems to me that it would be better to remove these indirections and inline everything. That way, it's just a copy paste of printing them out with %+v if they ever have to be updated
</details>
I started with just`%#v` but it is is _very_ verbose since it includes all of the zero values explicitly for all the nested structs. Maybe its just me, but I found it easier to see what was actually happening (for whatever that's worth) with a little hand pruning of that output.

---

*[sql/sqlbase/system.go, line 110 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KO7ENhgZZAtZfQiNOlh:-KOAtncY65hp6dGk1yXt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a156d33947fa14d13040bd47ff3beed4ac4c697/sql/sqlbase/system.go#L110)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Also add a comment here mentioning that we verify these descriptors in TestSystemTables
</details>
Done.

---

*[sql/sqlbase/table.go, line 47 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KO7DvrH3balZcNSl6sR:-KOAZYZW4jpD-Ozy7zcG:254814273) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a156d33947fa14d13040bd47ff3beed4ac4c697/sql/sqlbase/table.go#L47)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Should this move as well (together with the error funcs above)?
</details>
Yeah, this change is just the first step and should allow for follow-ups like that but I wanted to keep the change size manageable. 

---

*[sql/sqlbase/table.go, line 63 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KO7E467x68m55YcPM2_:-KOAZmbxlcogoCohlW9G:-966071903) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a156d33947fa14d13040bd47ff3beed4ac4c697/sql/sqlbase/table.go#L63)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Should this move as well?
</details>
Yeah, though ditto above about this change being a pre-req and doing more moves in follow ups.

Moving this one in particular though is the one of the primary motivations of this change, since this is the one where we've been feeling the pain of not having a planner/txn/etc to do lookups of other tables that are mentioned in column qualifications.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141)*

**Comment by dt** [comment]
Review status: 3 of 12 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[sql/system_table_test.go, line 76 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-KOAn_cgQDOa-5C_Hnnk:-KOAuRXeymmbVNXbapqI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ff0a7c2038feb51608ccfe54fa112022e495a8/sql/system_table_test.go#L76)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Comment on why this test is here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 3 of 12 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-:-KOBCSr25s5sS5L4eooy:1417088721)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r4, 6 of 7 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8141#-:-KOBE9fQd5nxRw8QcL6i:1417088721)*

**Pull request merged**
