### PR TITLE
GLOCKFILE: update dependencies

### PR DESCRIPTION
**Pull request by tamird**
Summary of not-definitely-irrelevant changes:
- github.com/chzyer/readline: add HistorySearchFold
  https://github.com/chzyer/readline/pull/86
- github.com/docker/docker: Refactor to new events api
  https://github.com/docker/docker/commit/d6bd79c18f5ab5dbdaa472ccd921ad2858117507
- github.com/docker/docker: client: don't hide context errors
  https://github.com/docker/docker/commit/8e5ef8af5c90a3fbc93173cb485d42e044ca56ae
- github.com/elastic/gosigar: Add a working implementation of ProcFDUsage for FreeBSD
  https://github.com/elastic/gosigar/commit/1b4827b60599a995d730259b046619a96d900435
- github.com/gogo/protobuf: packed repeated fields in proto3
  https://github.com/gogo/protobuf/commit/3660948db4266bc218b5ee7321966626ab44297c
- github.com/google/btree: backwards iteration
  https://github.com/google/btree/pull/7
- github.com/google/btree: Fix memory leak in removeAt methods
  https://github.com/google/btree/pull/9
- github.com/pkg/errors: Add WithStack and WithMessage
  https://github.com/pkg/errors/commit/4f8d1cf2a2224e69506b66a8e3d7702fad3a7762
- github.com/rcrowley/go-metrics: Adding FunctionalGauge
  https://github.com/rcrowley/go-metrics/pull/157
- golang.org/x/crypto: lots of random fixes
  https://github.com/golang/crypto/compare/1ce41b6ca7dccc03377edf55652ffa334b6c06ce...84e98f45760e87786b7f24603b8166a6fa09811d
- golang.org/x/net: lots of random fixes
  https://github.com/golang/net/compare/07b51741c1d6423d4a6abab1c49940ec09cb1aaf...0f2be02c5ddfa7c7936000ad519b04c6c795eab3
- gopkg.in/yaml.v2: Fix unmarshaler handling of empty strings
  https://github.com/go-yaml/yaml/commit/a5b47d31c556af34a302ce5d659e6fea44d90de0
- honnef.co/go/simple: Detect HasPrefix use that could be TrimPrefix
  https://github.com/dominikh/go-simple/commit/e4b33f62951a263109be351a6e7f516df082e667
- honnef.co/go/unused: Add flag to ignore reflection
  https://github.com/dominikh/go-unused/commit/b87f9a8e8a85e299bc12d87a5ab27b3434e6ae6e

Skipped:
- github.com/cockroachdb/c-rocksdb (@petermattis will do this soon)
- github.com/gordonklaus/ineffassign (reveals lots of issues)
- google.golang.org/grpc (likely to break stuff, will do separately)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9680)

### CODE REVIEW

**Comment by tamird** [comment]
cc @knz

**Comment by tschottdorf** [comment]
LGTM

**Comment by knz** [comment]
LGTM

**Comment by petermattis** [comment]
LGTM

Btw, I think we should consider updates to `c-rocksdb` and `grpc` as "risky" and sequence their deployment to test clusters.

**Comment by tamird** [comment]
Yep, I agree.

**Pull request merged**
