### PR TITLE
storage: better sleep discipline in TestReplicaRemovalCampaign

### PR DESCRIPTION
**Pull request by tamird**
Also log an error when it's available.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7142)

### CODE REVIEW

**Comment by d4l3k** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> #### storage: better sleep discipline in TestReplicaRemovalCampaign
> 
> Also log an error when it's available.
> 
> 
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1043 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-KJq_jdt_GL6GDlCwsZ3:-KJq_jdt_GL6GDlCwsZ4:601677465) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf835b592787599278643dbe0a49217e0a4b843/storage/client_raft_test.go#L1043)):*
> ```Go
> 				})
> 			} else {
> 				for start := timeutil.Now(); timeutil.Since(start) < time.Second; time.Sleep(10 * time.Millisecond) {
> ```

Any reason you're increasing the time taken from 100ms to 1s?

---

*[storage/replica_command.go, line 2276 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-KJq_sTsdPYjBwry5zks:-KJq_sTsdPYjBwry5zkt:959143980) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf835b592787599278643dbe0a49217e0a4b843/storage/replica_command.go#L2276)):*
> ```Go
> 				replica, err := r.store.GetReplica(newRng.RangeID)
> 				if err != nil {
> 					log.Infof("new replica %d possibly removed before campaigning: %s", r.mu.replicaID, err)
> ```

Do we have any way to check whether the error is "can't find replica" vs "everything is broken"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-:-KJqaZcGEEtleT-kExj7:1417088721)*

**Comment by d4l3k** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1043 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-KJq_jdt_GL6GDlCwsZ3:-KJqc6GZAqaQi2mG4GqZ:-2036067662) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf835b592787599278643dbe0a49217e0a4b843/storage/client_raft_test.go#L1043)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Any reason you're increasing the time taken from 100ms to 1s?
</details>
Not really, just want to give things ample time to quiesce.

---

*[storage/replica_command.go, line 2276 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-KJq_sTsdPYjBwry5zks:-KJqbaju1Cwdz1i8_8gE:-1831885280) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf835b592787599278643dbe0a49217e0a4b843/storage/replica_command.go#L2276)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Do we have any way to check whether the error is "can't find replica" vs "everything is broken"?
</details>
Yeah, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142)*

**Comment by arjunravinarayan** [comment]
:lgtm:

<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-:-KJqchzSdfyfIAd1TLEn:1417088721)*

**Comment by d4l3k** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/client_raft_test.go, line 1043 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-KJq_jdt_GL6GDlCwsZ3:-KJqdJFe9DLXy6rOD7aX:-1341738544) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf835b592787599278643dbe0a49217e0a4b843/storage/client_raft_test.go#L1043)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Not really, just want to give things ample time to quiesce.
</details>
Okay. I really hate adding more time to test run time, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[storage/client_raft_test.go, line 1043 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-KJq_jdt_GL6GDlCwsZ3:-KJqe3WwxS7eEZ70wsif:1987131250) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf835b592787599278643dbe0a49217e0a4b843/storage/client_raft_test.go#L1043)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Okay. I really hate adding more time to test run time, though.
</details>
That's noble, but perhaps we have lower handing fruit.
```
make testslow PKG=./storage
...
11.80s TestSplitSnapshotRace_SnapshotWins
6.18s TestStoreRangeSystemSplits
2.06s TestSplitSnapshotRace_SplitWins
1.90s TestRangeDescriptorSnapshotRace
1.35s TestReplicaRemovalCampaign <---
1.12s TestRaftRemoveRace
0.91s TestRestoreReplicas
0.82s TestStoreRangeDownReplicate
0.67s TestRaftHeartbeats
0.65s TestSendAndReceive
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[storage/client_raft_test.go, line 1043 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142#-KJq_jdt_GL6GDlCwsZ3:-KJqe_FQf-VI7aGI0B44:-1485256356) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf835b592787599278643dbe0a49217e0a4b843/storage/client_raft_test.go#L1043)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> That's noble, but perhaps we have lower handing fruit.
> ```
> make testslow PKG=./storage
> ...
> 11.80s TestSplitSnapshotRace_SnapshotWins
> 6.18s TestStoreRangeSystemSplits
> 2.06s TestSplitSnapshotRace_SplitWins
> 1.90s TestRangeDescriptorSnapshotRace
> 1.35s TestReplicaRemovalCampaign <---
> 1.12s TestRaftRemoveRace
> 0.91s TestRestoreReplicas
> 0.82s TestStoreRangeDownReplicate
> 0.67s TestRaftHeartbeats
> 0.65s TestSendAndReceive
> ```
</details>
s/handing/hanging/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7142)*

**Pull request merged**
