### PR TITLE
kv: clean up txn intents after AmbiguousResultErrors

### PR DESCRIPTION
**Pull request by nvb**
`TxnCoordSender` made sure to track and eventually clean up intents
for transactions that were put into Writing mode before seeing an
error. However, it did not previously make an effort to track and
clean up intents when it saw an `AmbiguousResultErrors` during the
first request of a transaction. This change fixes that.

This was giving me all kinds of trouble when trying to write a test
for #20589. Split requests continued to leave lots of dangling intents
around whenever they were canceled, which slowed down the test and
required lots of intent pushing. This change seems to resolve those
complications.

Release note (bug fix): clean up dangling intents eagerly when
AmbiguousResultErrors are seen.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 909 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628#-L0AD_h__c5zxlx2LSeN:-L0AD_h__c5zxlx2LSeO:b-kojrds) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39e7db82c3df339d3b60d82cf871d146443b7a0/pkg/kv/txn_coord_sender.go#L909)):*
> ```Go
> 	//
> 	// An extension of this case is that of a transaction which receives an
> 	// ambiguous result error on its first writing request. Here, the
> ```

Can reads ever get ambiguous errors at this level? I know that logically reads can always be retried, but I can't remember where (or if) we have logic that takes care of that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628#-:-L0AE-MyVDm1dNcOIPED:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 909 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628#-L0AD_h__c5zxlx2LSeN:-L0AR-rEtVjW3EG4Lez7:b-164u8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39e7db82c3df339d3b60d82cf871d146443b7a0/pkg/kv/txn_coord_sender.go#L909)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Can reads ever get ambiguous errors at this level? I know that logically reads can always be retried, but I can't remember where (or if) we have logic that takes care of that. 
</blockquote></details>

The only place where I can see that being possible is with some of our gRPC handling (notably [here](https://github.com/cockroachdb/cockroach/blob/6a2820c4fb6dea9509ad9b4d6995f6d1e7c95e7b/pkg/kv/dist_sender.go#L1249)). Every other instance of an `AmbiguousResultError` comes from from Raft command proposals. I guess this still means it would be possible to see them when in clockless mode, though.

Are you worried about entering this branch for reads that get an ambiguous error? It looks like it would be a no-op, although it would certainly be worth a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628)*

**Comment by bdarnell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 909 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628#-L0AD_h__c5zxlx2LSeN:-L0Artfvh4mxF-SePXPn:b-dpy73r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39e7db82c3df339d3b60d82cf871d146443b7a0/pkg/kv/txn_coord_sender.go#L909)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The only place where I can see that being possible is with some of our gRPC handling (notably [here](https://github.com/cockroachdb/cockroach/blob/6a2820c4fb6dea9509ad9b4d6995f6d1e7c95e7b/pkg/kv/dist_sender.go#L1249)). Every other instance of an `AmbiguousResultError` comes from from Raft command proposals. I guess this still means it would be possible to see them when in clockless mode, though.

Are you worried about entering this branch for reads that get an ambiguous error? It looks like it would be a no-op, although it would certainly be worth a comment.
</blockquote></details>

Yeah, I was just concerned about entering this block for reads. Even if it's safe now it deserves a comment to make sure we preserve that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/kv/txn_coord_sender.go, line 909 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628#-L0AD_h__c5zxlx2LSeN:-L0BJ0jRlW68Q4HTvzQ2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39e7db82c3df339d3b60d82cf871d146443b7a0/pkg/kv/txn_coord_sender.go#L909)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, I was just concerned about entering this block for reads. Even if it's safe now it deserves a comment to make sure we preserve that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20628)*

**Pull request merged**
