### PR TITLE
sql/schemachanger: infra to move ALTER COLUMN .. SET TYPE to DSC

### PR DESCRIPTION
**Pull request by spilchen**
This lays the groundwork for moving `ALTER COLUMN .. SET TYPE` into the
declarative schema changer. I am staging this to avoid one huge PR. This
PR focuses on making test changes to accommodate new changes to the
explain output. Specifically:
- Add a new `TypeName` attribute to the ColumnType element. This allows
  us to update an existing column type. This is necessary because
  modifying an existing element will be treated as a no-op if none of
  the attributes change.
- Rename the SetAddedColumnType operation to UpsertColumnType. In
  a follow-up PR, I will add logic to this operation to handle
  updates of existing types.

The type name depends on having the type descriptor hydrated. This was
missing in a couple of tests (scdecomp and scbuild), so I had to logic for
that.

Epic: CRDB-25314
Informs: #126143
Release note: none

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1NywhfBQDtKZaAku2x:bifa197) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
> ```proto
>   // instance, if this is embedded in a column type, you can change the column's
>   // type by changing the type and this sequence.
>   uint32 seq_num = 3;
> ```

I think we just want to drop and create a ColumnType element and have handling around that? I don't think we should need a sequence number? If you look inside attr.go you can see what keys that make a ColumnType unique:
```
	rel.EntityMapping(t((*scpb.ColumnType)(nil)),
		rel.EntityAttr(DescID, "TableID"),
		rel.EntityAttr(ColumnFamilyID, "FamilyID"),
		rel.EntityAttr(ColumnID, "ColumnID"),
		rel.EntityAttr(ReferencedTypeIDs, "ClosedTypeIDs"),
	),
```

So, we should be able to drop and create a type without them being seen as duplicates.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1RaAMVBKy14GLNwhTX:bwcm9z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think we just want to drop and create a ColumnType element and have handling around that? I don't think we should need a sequence number? If you look inside attr.go you can see what keys that make a ColumnType unique:
```
	rel.EntityMapping(t((*scpb.ColumnType)(nil)),
		rel.EntityAttr(DescID, "TableID"),
		rel.EntityAttr(ColumnFamilyID, "FamilyID"),
		rel.EntityAttr(ColumnID, "ColumnID"),
		rel.EntityAttr(ReferencedTypeIDs, "ClosedTypeIDs"),
	),
```

So, we should be able to drop and create a type without them being seen as duplicates.
</blockquote></details>

I originally went down this path, but I encountered a few roadblocks. None of the attributes of the `ColumnType` element refer back to the type of the column. So, if all you are doing is changing the column type, the attributes for the elements stay the same. When trying to decompose this into a drop/add, the add was being ignored (in [this file](https://github.com/cockroachdb/cockroach/blob/99d10d419c08d68db4e3a5d62c9dec009d6cdef6/pkg/sql/schemachanger/scbuild/builder_state.go#L95C1-L99C3)) because an element with the same attributes and state already exists.

I then tried to look at including the type (`types.TypeT`) as an attribute. That way, it would look like a changed element. But it couldn't handle the complex nature of the type. It works well if a new attribute is a string or int, but failed when it encountered a complex struct like `types.TypeT`.

I noticed that with Annie's DSC changes, she dealt with updates to zone configs by using sequence numbers. So, that's why I opted to go with this approach.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1RcggF3Y1ZmSrKIB7i:bnerhwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I originally went down this path, but I encountered a few roadblocks. None of the attributes of the `ColumnType` element refer back to the type of the column. So, if all you are doing is changing the column type, the attributes for the elements stay the same. When trying to decompose this into a drop/add, the add was being ignored (in [this file](https://github.com/cockroachdb/cockroach/blob/99d10d419c08d68db4e3a5d62c9dec009d6cdef6/pkg/sql/schemachanger/scbuild/builder_state.go#L95C1-L99C3)) because an element with the same attributes and state already exists.

I then tried to look at including the type (`types.TypeT`) as an attribute. That way, it would look like a changed element. But it couldn't handle the complex nature of the type. It works well if a new attribute is a string or int, but failed when it encountered a complex struct like `types.TypeT`.

I noticed that with Annie's DSC changes, she dealt with updates to zone configs by using sequence numbers. So, that's why I opted to go with this approach.
</blockquote></details>

Sorry, slight correction. The add isn't a no-op; it actually reverts the drop ([see code here](https://github.com/cockroachdb/cockroach/blob/33ae309c0434fe9cec56f9743b340b9a575e7319/pkg/sql/schemachanger/scbuild/builder_state.go#L136-L140)). This happens because nothing has changed in the element's attributes. So, performing the drop (PUBLIC -> ABSENT) followed by the add (ABSENT -> PUBLIC) cancels itself out. 

So, I think something in the attributes has to change for this to work. Should it be the type, or is sequence number okay?

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1Ri3fS08RZ-V26y63O:bipm0xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Sorry, slight correction. The add isn't a no-op; it actually reverts the drop ([see code here](https://github.com/cockroachdb/cockroach/blob/33ae309c0434fe9cec56f9743b340b9a575e7319/pkg/sql/schemachanger/scbuild/builder_state.go#L136-L140)). This happens because nothing has changed in the element's attributes. So, performing the drop (PUBLIC -> ABSENT) followed by the add (ABSENT -> PUBLIC) cancels itself out. 

So, I think something in the attributes has to change for this to work. Should it be the type, or is sequence number okay?
</blockquote></details>

Oh, for some reason I thought ClosedTypeIDs included the types ID (but it does't).  Can we add the OID in to the type instead, and use that for uniqueness? I think that would solve it and be a bit cleaner

For ZoneConfig's didn't have anything numeric so its honestly feels like a kludge :(

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1Rl0P-3Ew0VED5gmyR:b-l52igp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Oh, for some reason I thought ClosedTypeIDs included the types ID (but it does't).  Can we add the OID in to the type instead, and use that for uniqueness? I think that would solve it and be a bit cleaner

For ZoneConfig's didn't have anything numeric so its honestly feels like a kludge :(
</blockquote></details>

I don't think the OID would change in all cases. If the alteration changes the type in a way that doesn't require creating a shadow column, the OID would remain the same. For instance, a trivial change like switching from a SMALLINT to a BIGINT would keep the OID unchanged. Let me reconsider including `types.TypeT` as an attribute.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1RnelEA-MOIzZwUOwc:buh7joc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I don't think the OID would change in all cases. If the alteration changes the type in a way that doesn't require creating a shadow column, the OID would remain the same. For instance, a trivial change like switching from a SMALLINT to a BIGINT would keep the OID unchanged. Let me reconsider including `types.TypeT` as an attribute.
</blockquote></details>

I don't think we can embed the full type easily, but OID + TypeModifer I think would cover everything. Normally that sufficient for reconstructing the exact type

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1SVIROC00s7Xqi-3-R:by57qs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I don't think we can embed the full type easily, but OID + TypeModifer I think would cover everything. Normally that sufficient for reconstructing the exact type
</blockquote></details>

Discussed this more offline. We would need to include the locale too to make it unique. So, I am going to replace the SeqNum with a new attribute that has the output of the types SQLString(). This will include all of the things we need to detect changes in the type: type, precision, and locale.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @michae2)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-O1NywhfBQDtKZaAku2w:-O1XsD2c8Vj4L2vqQ7sN:bygt54w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb6c8e249f9da80125c4fd81522e82ab0c419c28/pkg/sql/schemachanger/scpb/elements.proto#L171)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Discussed this more offline. We would need to include the locale too to make it unique. So, I am going to replace the SeqNum with a new attribute that has the output of the types SQLString(). This will include all of the things we need to detect changes in the type: type, precision, and locale.
</blockquote></details>

I finished adding the new TypeName attribute. Please have a look when you get a chance. Thanks.

**Review by fqazi — COMMENTED** [review]
:lgtm_strong:  Great work!

I'm guessing a follow on PR will hook this into attr.go, since we don't need the uniqueness yet.

> Reviewed 3 of 188 files at r1, 202 of 202 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907#-:-O1YEuijDNupVTXpoAZp:b-db182s)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by fqazi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126907)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by spilchen** [comment]
tftr!

bors r=fqazi

**Pull request merged**
