### PR TITLE
opt: support ARRAY expressions

### PR DESCRIPTION
**Pull request by justinj**
This commit adds support for ARRAY literals in the optbuilder.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/memo/expr.og.go, line 3505 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8m3NJo7wrbECyeQhFJ:-L8m3NJo7wrbECyeQhFK:by7r44p) ([raw file](https://github.com/cockroachdb/cockroach/blob/842e45dce114d8baf98356b5a45e1af0d9822b87/pkg/sql/opt/memo/expr.og.go#L3505)):*
> ```Go
> 
> // ArrayExpr is an ARRAY literal of the form ARRAY[<expr1>, <expr2>, ..., <exprN>].
> // We store the type of the array on it because in the case of an empty array
> ```

Where is this comment coming from? Do you need to run `make generate PKG=./pkg/sql/opt/...` again?

---

*[pkg/sql/sem/tree/expr.go, line 615 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8m4326-RnKq2Ux9r6m:-L8m4326-RnKq2Ux9r6n:b-9raizw) ([raw file](https://github.com/cockroachdb/cockroach/blob/842e45dce114d8baf98356b5a45e1af0d9822b87/pkg/sql/sem/tree/expr.go#L615)):*
> ```Go
> }
> 
> // NewTypedArrayExpr returns an ArrayExpr that is well-typed.
> ```

[nit] Array not ArrayExpr

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-:-L8m4CyR5wy6wzBYpeqF:bb6ywmx)*

**Comment by justinj** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/memo/expr.og.go, line 3505 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8m3NJo7wrbECyeQhFJ:-L8mANHR9Mzr4VUO-YCS:b-h7ysmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/842e45dce114d8baf98356b5a45e1af0d9822b87/pkg/sql/opt/memo/expr.og.go#L3505)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Where is this comment coming from? Do you need to run `make generate PKG=./pkg/sql/opt/...` again?
</blockquote></details>

Ah yes, my bad, forgot to rerun.

---

*[pkg/sql/sem/tree/expr.go, line 615 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8m4326-RnKq2Ux9r6m:-L8mAT_R8bQp_eQbW0Iz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/842e45dce114d8baf98356b5a45e1af0d9822b87/pkg/sql/sem/tree/expr.go#L615)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Array not ArrayExpr
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/optbuilder/testdata/scalar, line 569 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mBdNlChaQko1SRI4S:-L8mBdNlChaQko1SRI4T:b-wacfc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/optbuilder/testdata/scalar#L569)):*
> ```
>  └── array: int[] [type=int[]]
> 
> build-scalar vars=(string[])
> ```

Would be interesting to have a case that uses array elements of different literal types, like `ARRAY[1, 1.0, '1']`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-:-L8mCS0d8Gpjx-gl1TCe:bnfp4nl)*

**Comment by rytaft** [comment]
Reviewed 6 of 11 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8mHLWhBV93VWEn-QrL:bk1a7n8) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
> ```
> [Scalar]
> define Array {
>     Elements ExprList
> ```

[nit] for consistency, I'd change this to `Elems` to match the other scalar rules above.

Also, why do we need to store the type? Can't it be inferred from the type of the elements (See Tuple or Coalesce, for example)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Comment by justinj** [comment]
Review status: 8 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8mKxXy5MlvdyaSgUFo:bkchie) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] for consistency, I'd change this to `Elems` to match the other scalar rules above.

Also, why do we need to store the type? Can't it be inferred from the type of the elements (See Tuple or Coalesce, for example)
</blockquote></details>

Good call, done.

We can't always do that because of the empty array. It's kind of annoying, the empty array is only allowed in some contexts, for instance, if its type can't be inferred we don't allow it:
```
root@:26257/> SELECT ARRAY[];
pq: cannot determine type of empty array. Consider annotating with the desired type, for example ARRAY[]:::int[]
```
but in other cases we do:
```
root@:26257/d> CREATE TABLE x (a INT[]);
CREATE TABLE
root@:26257/d> INSERT INTO x VALUES (ARRAY[]);
INSERT 1
```

---

*[pkg/sql/opt/optbuilder/testdata/scalar, line 569 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mBdNlChaQko1SRI4S:-L8mH5nu0Oa8ffNbkPxG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/optbuilder/testdata/scalar#L569)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Would be interesting to have a case that uses array elements of different literal types, like `ARRAY[1, 1.0, '1']`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8mMstO8D8oc18TXbZF:b-eqwcmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Good call, done.

We can't always do that because of the empty array. It's kind of annoying, the empty array is only allowed in some contexts, for instance, if its type can't be inferred we don't allow it:
```
root@:26257/> SELECT ARRAY[];
pq: cannot determine type of empty array. Consider annotating with the desired type, for example ARRAY[]:::int[]
```
but in other cases we do:
```
root@:26257/d> CREATE TABLE x (a INT[]);
CREATE TABLE
root@:26257/d> INSERT INTO x VALUES (ARRAY[]);
INSERT 1
```
</blockquote></details>

Got it - thanks for the explanation! In that case, can you add a couple of tests with an empty array?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-:-L8mN9NvEekdpNjYnOvg:bnfp4nl)*

**Comment by justinj** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8mRgNo7ecKeml1SKt0:bwxg0o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Got it - thanks for the explanation! In that case, can you add a couple of tests with an empty array?
</blockquote></details>

I have a test where the empty array is allowed, and I looked into adding one where it's not, but it appears that in the testing framework we distinguish between errors that come through at a lower level of the system from ones that originate in the optimizer (we can assert against the latter but not the former, the former just immediately fails the test) - changing this is easy, but it seems like this might have been done intentionally? It seems ok to me to just assume that the optimizer will always have a typable array?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8mSoyc4FoPp9Jat08e:bs62qw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I have a test where the empty array is allowed, and I looked into adding one where it's not, but it appears that in the testing framework we distinguish between errors that come through at a lower level of the system from ones that originate in the optimizer (we can assert against the latter but not the former, the former just immediately fails the test) - changing this is easy, but it seems like this might have been done intentionally? It seems ok to me to just assume that the optimizer will always have a typable array?
</blockquote></details>

Can you paste the testcase and the name of the file you're adding it to?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Comment by justinj** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8ma3Cq0GVhcZJS5faO:b-gwg5v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you paste the testcase and the name of the file you're adding it to?
</blockquote></details>

```
build-scalar
ARRAY[]
----
error: cannot determine type of empty array. Consider annotating with the desired type, for example ARRAY[]:::int[]
```
Which doesn't pass because [this line fails instead of returning the error](https://github.com/justinj/cockroach/blob/2d160d98c11d97f53f4bf23021b29537fe01ffba/pkg/sql/opt/optbuilder/builder_test.go#L123).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8mbWa22P59KauQxeVi:b-j2epwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

```
build-scalar
ARRAY[]
----
error: cannot determine type of empty array. Consider annotating with the desired type, for example ARRAY[]:::int[]
```
Which doesn't pass because [this line fails instead of returning the error](https://github.com/justinj/cockroach/blob/2d160d98c11d97f53f4bf23021b29537fe01ffba/pkg/sql/opt/optbuilder/builder_test.go#L123).
</blockquote></details>

Ah, the build-scalar tests are kind of special, they assume the expression can be type-checked. I would add this as part of a regular "build" test, e.g. as `SELECT ARRAY[]`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/ops/scalar.opt, line 473 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316#-L8mHLWg9OdjqvcCNu_B:-L8mtqITEiSc_xjj5ulb:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e664b485909e732ea9c2856b8d938cd1f15839/pkg/sql/opt/ops/scalar.opt#L473)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24316)*

**Pull request merged**
