### PR TITLE
 sql: save some EvalCtx allocations

### PR DESCRIPTION
**Pull request by danhhz**
EvalCtx is big, so we shouldn't be passing it anyway. Found by digging
into allocations that pprof attributed to the method signature of
sql.GenerateInsertRow. I tried to see if this showed up on any of our
SQL level INSERT benchmarks, but it seemed to be in the noise.

    name                                  old time/op    new time/op    delta
    ConvertToKVs/tpcc/warehouses=1-8         3.83s ± 0%     3.66s ± 1%   -4.53%  (p=0.016 n=4+5)
    ConvertToSSTable/tpcc/warehouses=1-8     5.50s ± 4%     5.13s ± 1%   -6.80%  (p=0.008 n=5+5)

    name                                  old speed      new speed      delta
    ConvertToKVs/tpcc/warehouses=1-8      23.2MB/s ± 0%  24.3MB/s ± 1%   +4.77%  (p=0.016 n=4+5)
    ConvertToSSTable/tpcc/warehouses=1-8  15.1MB/s ± 4%  16.2MB/s ± 1%   +7.27%  (p=0.008 n=5+5)

    name                                  old alloc/op   new alloc/op   delta
    ConvertToKVs/tpcc/warehouses=1-8         953MB ± 0%     704MB ± 0%  -26.17%  (p=0.029 n=4+4)
    ConvertToSSTable/tpcc/warehouses=1-8    1.64GB ± 0%    1.39GB ± 0%  -15.19%  (p=0.016 n=4+5)

    name                                  old allocs/op  new allocs/op  delta
    ConvertToKVs/tpcc/warehouses=1-8         17.4M ± 0%     16.8M ± 0%   -3.45%  (p=0.008 n=5+5)
    ConvertToSSTable/tpcc/warehouses=1-8     17.4M ± 0%     16.8M ± 0%   -3.45%  (p=0.008 n=5+5)

Also a small cleanup in some import code to use EvalCtx's Copy method
instead of passing around a function closure.

Touches #34809

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/ccl/importccl/read_import_workload.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37575#-Lf6TDM8E0ddQQ3DTszT:-Lf6TDM93nzdpTD0Enuk:b-qeigy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/969368ae20819dea20a8074981e12fd95a4ac73c/pkg/ccl/importccl/read_import_workload.go#L178)):*
> ```Go
> 		if err := ctxgroup.GroupWorkers(ctx, runtime.NumCPU(), func(ctx context.Context) error {
> 			evalCtx := w.evalCtx.Copy()
> 			return wc.Worker(ctx, evalCtx.Copy(), finishedBatchFn)
> ```

Two copies?

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/ccl/importccl/read_import_workload.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37575#-Lf6TDM8E0ddQQ3DTszT:-Lf6UoqC9dpkZnh68wfN:b66foy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/969368ae20819dea20a8074981e12fd95a4ac73c/pkg/ccl/importccl/read_import_workload.go#L178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Two copies?
</blockquote></details>

Just making extra sure, y'know

(Good eye, done. Also added the ImportFixture/tpcc benchmark to the commit message. The two benchmarks I had before are below this codepath, which is why I didn't notice the double copy, but ImportFixture includes it.)

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37575#-:-Lf6Z4-h4TgW9mBGlRhD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/importccl/read_import_workload.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37575#-Lf6TDM8E0ddQQ3DTszT:-Lf6Yy3i4y6_N8p0CFO8:b-xkwm8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/969368ae20819dea20a8074981e12fd95a4ac73c/pkg/ccl/importccl/read_import_workload.go#L178)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Just making extra sure, y'know

(Good eye, done. Also added the ImportFixture/tpcc benchmark to the commit message. The two benchmarks I had before are below this codepath, which is why I didn't notice the double copy, but ImportFixture includes it.)
</blockquote></details>

You can't be too careful these days.

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
