### PR TITLE
sql/importer: skip a flaky test

### PR DESCRIPTION
**Pull request by knz**
Informs #91828.
Informs  #91845.
Informs #91850.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]

**Comment by knz** [comment]
thanks!

bors r=rafiss

**Comment by knz** [comment]
ooh another test to skip :)

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
bors r=rafiss

**Comment by yuzefovich** [comment]
What's the problem with `TestExternalSortMemoryAccounting`? Do you have a link to a failure?

**Comment by yuzefovich** [comment]
Nvm, see the linked issue.

**Pull request merged**
