### PR TITLE
physicalplan: add support for multi-stage execution of aggregate func…

### PR DESCRIPTION
**Pull request by piao88**
Needed for #58347

This commit  adds  support for muti-stage execution of the following aggregate functions , `sqrdiff` `stddev_pop`  `var_pop` `regr_count` `regr_avgx` `regr_avgy` `regr_sxx` `regr_syy`. besides , I add the aggregate functions `regr_sx`( Calculates sum of the independent variable) and `regr_sy`( Calculates sum of the dependent variable.) in support of building `regr_sxx` and `regr_syy` muti-stage function. The rest functions (`corr` ,`covar_pop`, `covar_samp`,`regr_intercept`,`regr_r2`,`regr_slope`,`regr_sxy` ) are not finished yet.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This is great, thanks for the contribution! We will, however need some logictests for all these functions. The logictests are powerful because they run in many configurations, including "local" (where multi-stage won't be planned) and "fakedist" (which fakes a random distribution of table data in each run); so they would automatically cross-check the results with multi-stage planning against those without it.

**Comment by piao88** [comment]
hi,thanks for your review ! 
  I find some bugs about decimal precision  in this commit . It has a little different between the result of miti-stage aggregate function and "local" function . (e.g. `82499.99999999999999999965` is the result of `sqrdiff` in "muti-stage" and `82499.99999999999999999985` is the result in "local" ) . I will take some days to fix it .

**Comment by RaduBerinde** [comment]
Those kind of differences are expected since the result is calculated through a different sequence of operations. The logictests have a tolerance for float results (https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/logic.go#L2881).

**Review by RaduBerinde — COMMENTED** [review]
There are a lot of `TestDistAggregationTable` failures; perhaps the tolerated errors in those tests need to be relaxed a bit (though they've been sufficient so far).

Please bump the `Version` in `execinfra/version.go` (and add a note in the comment).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59174#-:-MRx2DUvCqfvs7G6AinZ:b-kgrbc1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @piao88 and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/distsql_agg, line 660 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59174#-MRx0zkEByf_28HTh-uo:-MRx0zkEByf_28HTh-up:b-hzc8ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b84c4e9c28b28a7dd03e87b029beaecc6b2adb0/pkg/sql/logictest/testdata/logic_test/distsql_agg#L660)):*
> ```
> # Test muti-stage aggregate functions for #58347 (add support for multi-stage execution of aggregate functions).
> statement ok
> CREATE TABLE t (a INT, b INT, c FLOAT, d DECIMAL, PRIMARY KEY (a, b, c, d))
> ```

This test would be better in the `aggregate` file. We don't need the part starting from ALTER TABLE - that file runs under `fakedist` configuration which will pretend there is a random multi-node distribution of data each time it is run. By the way, some existing tests in that file now fail.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 1957 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59174#-MRx2iEI7yvdqCw6bEkK:-MRx2iEI7yvdqCw6bEkL:bosk2m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b84c4e9c28b28a7dd03e87b029beaecc6b2adb0/pkg/sql/sem/builtins/aggregate_builtins.go#L1957)):*
> ```Go
> }
> 
> func newFloatFinalRegressionSyyAggregate(
> ```

Why do we need these two variants if they're the same thing?
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 3590 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59174#-MRx345l76UQ5-bfbV-U:-MRx345l76UQ5-bfbV-V:bkvffep) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b84c4e9c28b28a7dd03e87b029beaecc6b2adb0/pkg/sql/sem/builtins/aggregate_builtins.go#L3590)):*
> ```Go
> }
> 
> func newFloatFinalStddevPopAggregate(
> ```

Isn't this exactly the same with `newDecimalFinalStdDevAggregate`? Why not use the existing one? I would review all the new ones and keep only those for which we can't use an existing built-in.

**Comment by yuzefovich** [comment]
#58347 has been fixed on master.

**Pull request closed without merging**
