### PR TITLE
sql: support SHOW SEQUENCES

### LINKED ISSUE #29045: sql: provide SHOW SEQUENCES alongside the others
There are already ways to see all the tables, views, schemas, databases etc using the `SHOW` command. Why don't we have `SHOW SEQUENCES`? Currently it seems there is no easy way to view all the sequences defined in a database.

This came up during QA for #28158.

### PR DESCRIPTION
**Pull request by knz**
Fixes #29045.
Docs PR: https://github.com/cockroachdb/docs/pull/4438

Typing `select sequence_name from information_schemas.sequences where
schema_name='public'` was getting old.

Release note (sql change): CockroachDB now supports `SHOW SEQUENCES`
to list the sequences in a given database or the current database,
alongside `SHOW TABLES` which was already able to list both tables and
views.

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm: just add one more test please

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35215#-:-LZfZRRt1R5ME0HI_xuH:bbf09ij)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter and @knz)

___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35215#-LZfZG7MEcjdcUjqd2x2:-LZfZG7NE9ok8dBMw-wC:b-dcb87z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e903d9162333eeb292772ce0b924c8d87c0708/pkg/sql/logictest/testdata/logic_test/sequences#L154)):*
> ```
> 
> query T
> SHOW SEQUENCES
> ```

Please add a test with `FROM` as well.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35215)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter and @BramGruneir)

___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35215#-LZfZG7MEcjdcUjqd2x2:-LZf_npb7j5cKApYXuGR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e903d9162333eeb292772ce0b924c8d87c0708/pkg/sql/logictest/testdata/logic_test/sequences#L154)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add a test with `FROM` as well.
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
