### PR TITLE
import,backup,engine: re-work bulk "row" counting

### LINKED ISSUE #44998: backup,import: primary key changes will break backup/restore/import row counts
The very [low-level row counter](https://github.com/cockroachdb/cockroach/blob/master/c-deps/libroach/row_counter.cc#L108) used in in the KV commands used by BACKUP, RESTORE and IMPORT counts "rows" processed as it iterates KVs, and the way it distinguishes rows from index entries is currently by extracting the index ID and comparing it to `1`, assuming that PK index ID is always 1. However after PK changes this assumption will be incorrect.

NB: there is also a go version of it used in pebble-based BACKUP and in IMPORT: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/row_counter.go#L65

### PR DESCRIPTION
**Pull request by dt**
Bulk operations use a low-level – c++ in some cases – row counter to
track what they process, such as how many rows are backed up, how many
bytes are imported, etc. While iterating individual KVs during an export
or import operation, a counter inspects each KV to maintain the count of
rows, index entries and total data size processed.

As mentioned above, these is done at a very low-level for performance
reasons, for example in BACKUP the entire construction of the resulting
data files is pushed all the way down to c++ so a single cgo call can
iterate directly from rocksdb into the result file. Thus this "row"
counter is a simple utility and doesn't use our higher level SQL
decoding libraries which use the actual table metadata, and instead used
a hardcoded comparison of the extracted index ID to 1 to determine if
that KV belonged to the primary key and this represented a "row".

However, with the addition of ALTER PRIMARY KEY in 20.1, this logic that
assumes ID 1 is the PK is no longer correct: the PK have ID 7 in one
table and ID 4 in another table.

To fix this the row counter now just counts how many entries it sees in
each index of each table, returning these to the caller and letting it
decide which, if any, it wants to call out as 'rows' based on its
knowledge of which indexes are primary vs secondary.

Fixes #44998.

Release note: none.

### CODE REVIEW

**Review by rohany — COMMENTED** [review]
I don't know this area of the code well enough for a good review, so @pbardea should take a look.

> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-:-M0tBwECCZ7TzY2VuuZc:baum5un)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @pbardea, and @rohany)

___
*[c-deps/libroach/row_counter.cc, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M0tA7xZEgRKh88S41jP:-M0tA7xZEgRKh88S41jQ:b-yqg5k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f994e136a7dfc9a773a632a11f900bd723ea399/c-deps/libroach/row_counter.cc#L107)):*
> ```cpp
>   }
> 
>   (*summary->mutable_entry_counts())[(tbl << 32) | index_id]++;
> ```

I'd pull this `(tbl << 32) | index_id)` out into a function and have it and the go version mention each other to avoid rot.
___
*[pkg/ccl/backupccl/backup_test.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M0tAUjq81yIqhd83yQK:-M0tAUjq81yIqhd83yQL:bgrcptt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f994e136a7dfc9a773a632a11f900bd723ea399/pkg/ccl/backupccl/backup_test.go#L447)):*
> ```Go
> 	)
> 	if exportedRows != numAccounts {
> 		// TODO(dt): fix row-count including interleaved garbarge
> ```

[nit]: period
___
*[pkg/roachpb/api.proto, line 1373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M0tBrIQ3ORmG4W29q7A:-M0tBrIQ3ORmG4W29q7B:be7sxge) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f994e136a7dfc9a773a632a11f900bd723ea399/pkg/roachpb/api.proto#L1373)):*
> ```protobuf
>   // pair, stored under the key (tableID << 32) | indexID. This EntryCount key
>   // generation logic is also available in the BulkOpSummaryID helper.
>   map<uint64, int64> entry_counts = 5;
> ```

are there any limitations to limiting the tableid and indexid to 32 bits each?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @rohany)

___
*[c-deps/libroach/row_counter.cc, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M0tA7xZEgRKh88S41jP:-M0yqFGc0v0eBVBHr3zP:b-xtrzu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f994e136a7dfc9a773a632a11f900bd723ea399/c-deps/libroach/row_counter.cc#L107)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'd pull this `(tbl << 32) | index_id)` out into a function and have it and the go version mention each other to avoid rot.
</blockquote></details>

I pulled it into a named var with a comment. I didn't want to mess with making a new method/updating the header file/etc unless you feel strongly.
___
*[pkg/ccl/backupccl/backup_test.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M0tAUjq81yIqhd83yQK:-M0yqRj6CnX6MQxi3b6k:b-4pj7rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f994e136a7dfc9a773a632a11f900bd723ea399/pkg/ccl/backupccl/backup_test.go#L447)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

[nit]: period
</blockquote></details>

Done.

No idea why I added that comment.
___
*[pkg/roachpb/api.proto, line 1373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M0tBrIQ3ORmG4W29q7A:-M0tEAOy2LN4qT8px9rn:b148pgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f994e136a7dfc9a773a632a11f900bd723ea399/pkg/roachpb/api.proto#L1373)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

are there any limitations to limiting the tableid and indexid to 32 bits each?
</blockquote></details>

I'm pretty sure they are uint32s in structured.proto already.

**Review by pbardea — APPROVED** [review]
> Reviewed 14 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @pbardea, and @rohany)

___
*[pkg/roachpb/api.go, line 1175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M12Dm7u-jZXMMp-JI6K:-M12Dm7v9_1G7AlzkKJY:b-8q14sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6121ee5a77a08fb47b44f68223bb87e2c31c8152/pkg/roachpb/api.go#L1175)):*
> ```Go
> // BulkOpSummaryID returns the key within a BulkOpSummary's EntryCounts map for
> // the given table and index ID. This logic is mirrored in c++ in rowcounter.cc.
> func BulkOpSummaryID(tableID, indexID uint64) uint64 {
> ```

Would it be possible for `BulkOpSummaryID` to take in `uint32`s to ensure we're never wiping bits away from the top of the table id?
___
*[pkg/roachpb/api.proto, line 1360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M12G3J-7-_3ILbbR08n:-M12G3J-7-_3ILbbR08o:bb64z50) ([raw file](https://github.com/cockroachdb/cockroach/blob/6121ee5a77a08fb47b44f68223bb87e2c31c8152/pkg/roachpb/api.proto#L1360)):*
> ```protobuf
>   // entries in the index with ID 1, however since 20.1 and the introduction of
>   // PK changes, the low-level counters that produce BulkOpSummaries are unable
>   // to assume which index is primarry and thus cannot distinguish "rows" vs
> ```

[nit] primarry

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @pbardea, and @rohany)

___
*[pkg/roachpb/api.go, line 1175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45282#-M12Dm7u-jZXMMp-JI6K:-M12Isuw1LU_nsqo79vV:b-mhg4f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6121ee5a77a08fb47b44f68223bb87e2c31c8152/pkg/roachpb/api.go#L1175)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Would it be possible for `BulkOpSummaryID` to take in `uint32`s to ensure we're never wiping bits away from the top of the table id?
</blockquote></details>

Eh, I thought about it but even if we did that, _callers_ would still be casting their sqlbase.ID or sqlbase.IndexID to uint32 so I which would discard all the same, so i'm not sure it buys us any added safety?

**Comment by dt** [comment]
chatted offline today, can't see a way around the casts mentioned above, so moving forward with this as is for now.

TFTRs!

bors r+

**Pull request merged**
