### PR TITLE
kvserver,status: change monotonic counter metrics to Counters

### PR DESCRIPTION
**Pull request by jbowens**
Update the metric type of runtime metrics that are semantically counters.
Historically these were gauges because the counter was maintained by the
runtime or the operating system, and our Counter type had no way of setting the
current counter value. In https://github.com/cockroachdb/cockroach/pull/125611 the Counter was adjusted to support updating
the current value of the counter from an externally-maintained value.

Reporting the correct metric type is important for some tooling that consumes
these metrics.

Epic: none
Release note: none

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127006#-:-O1XkSpk6u5f9U6JppwP:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by RaduBerinde — COMMENTED** [review]
We should backport to `release-24.2` too - it doesn't need any extra process since we haven't picked a beta yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127006#-:-O1XpbOK3yc17Ei0pSHQ:b-f1lv3u)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by jbowens** [comment]
TFTR!

bors r=RaduBerinde

**Comment by jbowens** [comment]
@kevin-v-ngo This was motivated by Datadog. Most of these metrics were being reported incorrectly by Datadog because they were reported as a gauge. Although the uptime metric specifically is semantically a counter, apparently it's more difficult to consume from Datadog.

See https://cockroachlabs.slack.com/archives/C074TGF3QVC/p1720559313555749

It's a bit frustrating working around Datadog's inflexibility around metric types (especially compared with Prometheus).

**Comment by kevin-v-ngo** [comment]
Thanks for the context Jackson! Solved other Datadog issues but introduced one for how this metric was being used.

**Pull request merged**
