### PR TITLE
spanconfig: set stage for migration

### PR DESCRIPTION
**Pull request by irfansharif**
**spanconfig: get rid of ReconciliationDependencies interface**

It was hollow, simply embedding the spanconfig.Reconciler interface. In
a future commit we end up relying on each pod's span config reconciler
outside of just the reconciliation job. This makes the interface even
awkwarder than it was.

**spanconfig/reconciler: export the checkpoint timestamp**

We'll make use of it in a future commit.

**kvserver: plumb in a context into (*Store).GetConfReader**

We'll use it in a future commit.

**clusterversion: improve a version comment**

Gets rid of a squiggly line in Goland.

---

Set of commits to set the stage for #73876.

### CODE REVIEW

**Comment by irfansharif** [comment]
(Gentle bump.)

**Review by arulajmani — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 7 of 7 files at r3, 9 of 9 files at r4, 9 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/migration/migrations/migrate_span_configs.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDvcJC-ZKyPg_Ba6ze:-MtDvcJC-ZKyPg_Ba6zf:b-7ohx5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrate_span_configs.go#L34)):*
> ```Go
> 
> 	for r := retry.StartWithCtx(ctx, base.DefaultRetryOptions()); r.Next(); {
> 		if !d.SpanConfig.Reconciler.Checkpoint().IsEmpty() {
> ```

I'm not very familiar with the migrations framework, but how would things work if this is run on a node that isn't running the reconciliation job? 
___
*[pkg/migration/migrations/migrations.go, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDwbllCMNEiVWar5s6:-MtDwbllCMNEiVWar5s7:b-3ndz28) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrations.go#L156)):*
> ```Go
> 		insertMissingPublicSchemaNamespaceEntry,
> 	),
> 	migration.NewTenantMigration(
> ```

Should this be a `NewSystemMigration` as well?
___
*[pkg/migration/migrations/migrate_span_configs_test.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDv8QY07yvCmtgQJ51:-MtDv8QY07yvCmtgQJ52:bvjabdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrate_span_configs_test.go#L43)):*
> ```Go
> 	tc := testcluster.StartTestCluster(t, 1, base.TestClusterArgs{
> 		ServerArgs: base.TestServerArgs{
> 			EnableSpanConfigs: true,
> ```

I took this for a spin, is this failing because we haven't turned on the cluster settings to create the reconciliation job?

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 7 of 7 files at r3, 9 of 9 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvserver/queue_helpers_testutil.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtIopH40KBy12Q4yaZD:-MtIopH40KBy12Q4yaZE:b-y3zm2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8a6b8de33b8ce2895bf2cdaa3cfc9608d5945a/pkg/kv/kvserver/queue_helpers_testutil.go#L55)):*
> ```Go
> // enqueues any that need to be replicated.
> func (s *Store) ForceReplicationScanAndProcess() error {
> 	return forceScanAndProcess(context.TODO(), s, s.replicateQueue.baseQueue)
> ```

IIRC elsewhere we've decided that for testing calls like this we just use context.Background.
___
*[pkg/migration/migrations/migrate_span_configs.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDvcJC-ZKyPg_Ba6ze:-MtIpmsI7sso9nTzmfdD:b-7ro92z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrate_span_configs.go#L34)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm not very familiar with the migrations framework, but how would things work if this is run on a node that isn't running the reconciliation job? 
</blockquote></details>

:point_up:, I think we need to persist the checkpoint as a pre-req to making this migration work. It's also a task we need to do anyway
___
*[pkg/migration/migrations/migrations.go, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDwbllCMNEiVWar5s6:-MtIq-ba530pU3_y7zlg:b-xl9h8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrations.go#L156)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be a `NewSystemMigration` as well?
</blockquote></details>

NewTenantMigration is run on the system tenant too

**Review by irfansharif — COMMENTED** [review]
TFTRs! I thought this PR would be cleanly separable from the one enabling everything by default, but it isn't. The migrations here depend on the reconciliation job running, and that in turn depends on the infra being enabled. Given that, here's what I think we should do:

- Review the migration code here, in this PR. Happy to iterate further.
- Once rubber stamped, I'll land these commits as part of https://github.com/cockroachdb/cockroach/pull/73876.

Does that work?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-:-MtJda0U5j4T61YP9hA8:b-cc19hk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/kv/kvserver/queue_helpers_testutil.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtIopH40KBy12Q4yaZD:-MtJFEVHADEFySYU1l4t:b-pncyve) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8a6b8de33b8ce2895bf2cdaa3cfc9608d5945a/pkg/kv/kvserver/queue_helpers_testutil.go#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

IIRC elsewhere we've decided that for testing calls like this we just use context.Background.
</blockquote></details>

Everything else in this file is using context.TODO(), just did it for that reason.
___
*[pkg/migration/migrations/migrate_span_configs.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDvcJC-ZKyPg_Ba6ze:-MtJFMDw3vawU0jMj4cB:btij4nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrate_span_configs.go#L34)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:point_up:, I think we need to persist the checkpoint as a pre-req to making this migration work. It's also a task we need to do anyway
</blockquote></details>

Done. We're still not actually using the checkpoint, just persisting it. Using it is just slightly more involved (need a few reconciler changes to detect if `system.{zones,descriptor}` haven't already been GC-ed at the given timestamp). Given this PR is holding up a few others, could we get to it after?
___
*[pkg/migration/migrations/migrate_span_configs_test.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDv8QY07yvCmtgQJ51:-MtJFT12C4gW-xKtvHfM:bp8y6r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrate_span_configs_test.go#L43)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I took this for a spin, is this failing because we haven't turned on the cluster settings to create the reconciliation job? 
</blockquote></details>

Woops, that's right, had pulled it out of the other PR that enabled it by default so it's failing here.

**Review by ajwerner — COMMENTED** [review]
I'm cool with that. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-:-MtJxfyZ4nYuGlo7jp1h:b-9cew9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @HonoreDB, and @nvanbenschoten)

**Review by arulajmani — APPROVED** [review]
:lgtm: for me. I have a mild aesthetic preference for reverting the commit that exposed the `Checkpoint` on the `Reconciler` now that we don't make use of it in the migration. 

> Reviewed 32 of 32 files at r6, 7 of 7 files at r7, 7 of 7 files at r8, 9 of 9 files at r9, 16 of 16 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-:-MtK8ulS6GEQmznLWyO7:b-ugvl9i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @HonoreDB, and @nvanbenschoten)

___
*[pkg/migration/migrations/migrations.go, line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74266#-MtDwbllCMNEiVWar5s6:-MtK8J4o1VCIN-XNb1p5:b7omz72) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce2bb6a89f239ac1e75d3937a4a3e1c4157f6ad/pkg/migration/migrations/migrations.go#L156)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

NewTenantMigration is run on the system tenant too
</blockquote></details>

We don't do any work and return early for secondary tenants though, so maybe we could change this to just run on the system tenant.

**Comment by irfansharif** [comment]
Thanks! Closing this in favor of #73876 now.

**Comment by irfansharif** [comment]
Got rid of the beefy migration commit in this PR, just going the land the rest of the tiny ones.

bors r+

**Pull request merged**
