### PR TITLE
geomfn: fixes for ST_MakePolygon

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
flaky flaky flaky

bors r=rafiss

**Comment by otan** [comment]
backport 21.2 21.1

**Comment by otan** [comment]
blathers backport 21.2 21.1

**Comment by otan** [comment]
blathers backport 20.2

**Pull request merged**
