### PR TITLE
build: show logs for testrace PEKV

### PR DESCRIPTION
**Pull request by nvb**
Should help debug #14563.

We can revert if we don't want to keep this.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14600)

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
This will show logs for testrace with or without PEKV, but I think that's fine.

**Comment by RaduBerinde** [comment]
Seems like this requires messing with `TestStatusLocalLogs `. I am hoping we will see the logs anyway now that #14590 is in.

**Comment by nvanbenschoten** [comment]
Yeah, I was hoping that even with the test failure we could still try to see a race, but I'm not sure that's possible. I'll rebase the original change onto #14590 and see if that triggers anything.

**Comment by RaduBerinde** [comment]
I tried that quite a bit yesterday with a couple PRs, triggered a few runs hoping it would hit but it didn't.. very elusive.

**Comment by RaduBerinde** [comment]
We could just `Skip()` `TestStatusLocalLogs` if showflags is set. We already skip that test if verbosity is high.

**Comment by nvanbenschoten** [comment]
Skipping that test indiscriminately for now without a plan to actually merge this. Hopefully we can just see the race here.

**Pull request closed without merging**
