### PR TITLE
storage: rationalize server-side refreshes and fix bugs

### LINKED ISSUE #42849: 1PC CPuts suffering from lost updates
When running as a 1PC, a CPut can erroneously miss to consider the last value on its key. This is because we mistakenly ignore a write too old condition in some cases. The ignoring happens here:
https://github.com/cockroachdb/cockroach/blob/c276b70cdff27b1bf4111f4b27b1459122804d70/pkg/storage/replica_evaluate.go#L344

An example of a bad scenario is the following:
- txnA starts at ts 10
- a Put of key a happens at ts 15
- txnA does a CPut that writes the key if there's nothing there, in the same batch as an EndTransaction
- the CPut evaluates at the "read timestamp" (so no key is seen) and so it erroneously succeeds, overwriting the first Put. A WriteTooOldError is returned from the CPut evaluation, which is turned into a WriteTooOld flag by `evaluateBatch()`
- the EndTransaction is the evaluated and succeeds, despite the WriteTooOld flag

The conditions under which this happens are:
- no reads before the EndTransaction batch. If there would be any reads, the EndTransaction would refuse to commit when the `WriteTooOld` flag is set on the txn at the end, insisting that the client refresh.
- no pipelined writes that are unresolved by the time of the EndTransaction. If there's any such writes, the EndTransaction moves the txn record to STAGING (instead of COMMITTED), and the erroneous ignoring of the wto condition doesn't kick in (by a happy accident)?

So in 19.2 this leaves mostly 1PC txns vulnerable. But in 19.1 I think the second condition above doesn't stand, so maybe the problem was even worse?

It would appear the bug was introduced in #38668, which was backported to 19.1.5.

Here's a test exemplifying the problem.

```go
func TestXXX(t *testing.T) {
	defer leaktest.AfterTest(t)()
	ctx := context.Background()

	s, _, db := serverutils.StartServer(t, base.TestServerArgs{})
	defer s.Stopper().Stop(ctx)
	keyA := "a"
	txn := client.NewTxn(ctx, db, 1 /* gatewayNodeID */, client.RootTxn)
	log.Infof(ctx, "!!! test starting txn: %s", txn.ID())

	if err := db.Put(ctx, keyA, "a"); err != nil {
		t.Fatal(err)
	}

	b := txn.NewBatch()
	b.CPut(keyA, "b", nil /* exp */)
	if err := txn.CommitInBatch(ctx, b); err != nil {
		t.Fatal(err)
	}

	val, err := db.Get(ctx, keyA)
	if err != nil {
		t.Fatal(err)
	}
	v, err := val.Value.GetBytes()
	require.NoError(t, err)
	log.Infof(ctx, "!!! val: %s", string(v)) // This will be "b".
```

### PR DESCRIPTION
**Pull request by andreimatei**
This is most #42969, which had been reverted. Different other parts of #42969 have been re-merged separately.

---------

Before this patch, we had several issues due to the server erroneously
considering that it's OK to commit a transaction at a bumped timestamp.

One of the issues was a lost update: a CPut could erroneously succeed
even though there's been a more recent write. This was caused by faulty
code in evaluateBatch() that was thinking that, just because an EndTxn
claimed to have been able to commit a transaction, that means that any
WriteTooOldError encountered previously by the batch was safe to
discard. An EndTxn might consider that it can commit even if there had
been previous write too old conditions if the NoRefreshSpans flag is
set. The problems is that a CPut that had returned a WriteTooOldError
also evaluated at the wrong read timestamp, and so its evaluation can't
be relied on.

Another issue is that, when the EndTxn code mentioned above considers
that it's safe to commit at a bumped timestamp, it doesn't take into
considerations that the EndTxn's batch might have performed reads (other
than CPuts)  that have been evaluated at a lower timestamp. This can
happen, for example in the following scenario: - a txn sends a Put which
gets bumped by the ts cache - the txn then sends a Scan + EndTxn. The
scan gets evaluated at the original timestamp, but then we commit at a
bumped one because the NoRefreshSpans flag is set.

The patch fixes the bugs by reworking how evaluation takes advantage of
the fact that some requests have flexible timestamps. EndTxn no longer
is in the business of committing at bumped timestamps, and its code is
thus simplified. Instead, the replica's "local retries" loop takes over.
The replica already had code handling non-transactional batches that
evaluated them repeatedly in case of WriteTooOldErrors. This patch
rationalizes and expands this code to deal with transactional batches
too, and with pushes besides WriteTooOldErrors. This reevaluation loop
now handles the cases in which the EndTxn used to bump the commit
timestamp.

The patch also fixes a third bug: the logic evaluateBatch() for
resetting the WriteTooOld state after a successful EndTransaction was
ignoring the STAGING state, meaning that the server would return a
WriteTooOldError even though the transaction was committed. I'm not sure
if this had dramatic consequences or was benign...

Fixes #42849

Release note (bug fix): A bug causing lost update transaction anomalies
was fixed.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
hold off on this review. I've got some more tweaks I want to do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-:-LzssNUoCs0wtNu9DWxl:bvwx7ho)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
PTAL. Compared to the previous time you've seen this, there's now a small preamble refactor commit (the first commit), and in the main commit I've improved some stuff around server-side refreshes of 1PC attempts (we no longer needlessly attempt them when `CanCommitAtHigherTimestamp` is not set. Also, not deferring WTOE on `IsReadAndWrite()` is back; the previous iteration had removed it based on the fact that we don't defer anything anyway because the `ba.DeferWriteTooOldError` flag is never set, but... I've put it back.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-:-LzxicCuEaxhyv_VXsHQ:b-au6cm2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 14 of 14 files at r3, 5 of 5 files at r4, 19 of 19 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/dist_sender_server_test.go, line 2071 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CJz5G2H1yly3mjJlD:-M-CJz5H5ahdIxKGyYMQ:bh7xt1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/kv/dist_sender_server_test.go#L2071)):*
> ```Go
> 			},
> 			retryable: func(ctx context.Context, txn *client.Txn) error {
> 				if err := txn.Put(ctx, "aother", "another put"); err != nil {
> ```

s/aother/another/
___
*[pkg/kv/dist_sender_server_test.go, line 2077 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CKSVFESrwrZhq4bd5:-M-CKSVFESrwrZhq4bd6:b-rm0mlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/kv/dist_sender_server_test.go#L2077)):*
Consider adding:

> ```
> // We expect the request to succeed after a server-side retry.
> txnCoordRetry: false,
> ```
___
*[pkg/roachpb/batch.go, line 579 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CJV_WAn8YHowqCLrP:-M-CJV_WAn8YHowqCLrQ:buc96bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6664d69311ad6b2a86af4d37063dfad68d1adb6/pkg/roachpb/batch.go#L579)):*
> ```Go
> 		if et, ok := req.(*EndTxnRequest); ok {
> 			h := req.Header()
> 			str = append(str, fmt.Sprintf("%s(commit:%t) [%s] tsflex:%t",
> ```

nit: did you consider putting this in the parenthesis? Something like `EndTxn(commit:false, tsflex: false)`
___
*[pkg/roachpb/batch.go, line 99 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CKnuq2QN75vEihKzK:-M-CKnuq2QN75vEihKzL:b-jy7zo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/roachpb/batch.go#L99)):*
> ```Go
> }
> 
> // IsReadAndWrite returns true if the request both reads and writes
> ```

I think you added this back in the wrong file. It should be in `api.go`.
___
*[pkg/storage/replica_evaluate.go, line 356 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CMp9-2pHDE-6Xn8oM:-M-CMp902CXjxdd2bwHa:b-xmdlcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_evaluate.go#L356)):*
> ```Go
> 	if baHeader.Txn != nil && baHeader.Txn.Status.IsCommittedOrStaging() {
> 		if writeTooOldState.err != nil {
> 			log.Fatalf(ctx, "committed txn with writeTooOld err: %s", writeTooOldState.err)
> ```

I'm confused. Isn't this exactly what we expect to see when we perform a server-side refresh during an EndTxn? What am I missing?

Also, we might as well restructure these two conditions to `if writeTooOldState.err != nil { ... }`
___
*[pkg/storage/replica_evaluate.go, line 424 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CNQNV8HDnPu_ycYis:-M-CNQNV8HDnPu_ycYit:bb76mu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_evaluate.go#L424)):*
> ```Go
> 	var pd result.Result
> 
> 	cArgs := batcheval.CommandArgs{
> ```

Why?
___
*[pkg/storage/replica_test.go, line 545 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CNgaUD8-WePXOHE6q:-M-CNgaUD8-WePXOHE6r:b-ywseo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_test.go#L545)):*
> ```Go
> 				}
> 
> 				// Emulate what a server actually does and bump the write timestamp when
> ```

Which ones? None of the test cases changed.
___
*[pkg/storage/replica_test.go, line 547 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CNaR_34BquFqjJWSw:-M-CNaR_34BquFqjJWSx:bknstnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_test.go#L547)):*
> ```Go
> 				// Emulate what a server actually does and bump the write timestamp when
> 				// possible. This makes some batches with diverged read and write
> 				// timestamps to still pass isOnePhaseCommit().
> ```

`s/to still//`
___
*[pkg/storage/replica_write.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CI0Y2BlBYePoQGk29:-M-CI0Y37IxfPdeNZODh:bj8jyax) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e54fee0d8ffa8d4bdbc7ad3fa4f70ec0a462cc/pkg/storage/replica_write.go#L380)):*
> ```Go
> }
> 
> // newBatchedEngine creates and engine.Batch. Depending on whether rangefeeds
> ```

s/and/an/
___
*[pkg/storage/replica_write.go, line 310 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-COHS96ZChLIraCqbF:-M-COHS96ZChLIraCqbG:byxke25) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L310)):*
> ```Go
> 			res   result.Result
> 		}
> 		synthesizeEndTxnResponse := func() onePCResult {
> ```

Could you double-check that this isn't causing anything new to escape to the heap? To be honest, this whole `onePCResult` stuff seems hard to read to me, so I'd vote to avoid it if possible.
___
*[pkg/storage/replica_write.go, line 312 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-COSBq6zuud1R0lqv4:-M-COSBq6zuud1R0lqv5:bdub5l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L312)):*
> ```Go
> 		synthesizeEndTxnResponse := func() onePCResult {
> 			if pErr != nil {
> 				return onePCResult{success: false}
> ```

We're not setting `pErr` here? Could you comment why?
___
*[pkg/storage/replica_write.go, line 318 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-COvFYD4E72T5M4B7-:-M-COvFYD4E72T5M4B70:b-hulp8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L318)):*
> ```
> otherwise we wouldn't have attempted 1PC
> ```

Is this true? What if the txn had read before and hit an uncertainty retry?
___
*[pkg/storage/replica_write.go, line 475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CPY7NCebp3D1hJgCt:-M-CPY7NCebp3D1hJgCu:bcu01n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L475)):*
> ```Go
> }
> 
> // canDoServersideRetry looks at the error produced by evaluating ba and decides
> ```

nit: I know we talked about this before and I might have been the one to push you towards this, but "can" seems like the wrong word here. We often "can" perform a serverside retry - that doesn't mean that we "should".

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/dist_sender_server_test.go, line 2071 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CJz5G2H1yly3mjJlD:-M-Cpfih9fLN8-5zq1D6:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/kv/dist_sender_server_test.go#L2071)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/aother/another/
</blockquote></details>

done
___
*[pkg/kv/dist_sender_server_test.go, line 2077 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CKSVFESrwrZhq4bd5:-M-CpsP50y7z9k82IpHT:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/kv/dist_sender_server_test.go#L2077)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider adding:

> ```
> // We expect the request to succeed after a server-side retry.
> txnCoordRetry: false,
> ```

</blockquote></details>

done
___
*[pkg/roachpb/batch.go, line 579 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CJV_WAn8YHowqCLrP:-M-Cr6Bq4eeShc8X2Mit:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6664d69311ad6b2a86af4d37063dfad68d1adb6/pkg/roachpb/batch.go#L579)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: did you consider putting this in the parenthesis? Something like `EndTxn(commit:false, tsflex: false)`
</blockquote></details>

done
___
*[pkg/roachpb/batch.go, line 99 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CKnuq2QN75vEihKzK:-M-CqSpV-E30o7tMRf8t:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/roachpb/batch.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you added this back in the wrong file. It should be in `api.go`.
</blockquote></details>

done
___
*[pkg/storage/replica_evaluate.go, line 356 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CMp9-2pHDE-6Xn8oM:-M-CsvH66KPiusW8AXfH:b-duzhnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_evaluate.go#L356)):*
> I'm confused. Isn't this exactly what we expect to see when we perform a server-side refresh during an EndTxn? What am I missing?

No... If there's an `EndTxn` in the batch, then we can't return the `WriteTooOld` flag... We never did.
I mean, we *could*, subject I guess to the same reasoning as returning a `WriteTooOld` flag when a CPut encounters a write-too-old. No?

> Also, we might as well restructure these two conditions to if writeTooOldState.err != nil { ... }

Done
___
*[pkg/storage/replica_evaluate.go, line 424 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CNQNV8HDnPu_ycYis:-M-Cv91K9p7zJ5CwTV-O:bs58r13) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_evaluate.go#L424)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

reverted the change
___
*[pkg/storage/replica_test.go, line 545 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CNgaUD8-WePXOHE6q:-M-Cvd8R-eyJ5IJgjrhl:b-8bzvc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_test.go#L545)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Which ones? None of the test cases changed.
</blockquote></details>

well I think preventing the tests from changing was the point here. `IsOnePhaseCommit()` used to indirectly check `CanForwardCommitTimestampWithoutRefresh()`. Now it no longer does.
___
*[pkg/storage/replica_test.go, line 547 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CNaR_34BquFqjJWSw:-M-CvPUv4XFF3r26rBIT:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_test.go#L547)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/to still//`
</blockquote></details>

done
___
*[pkg/storage/replica_write.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CI0Y2BlBYePoQGk29:-M-Hgwq68MeuWRVF_Ued:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e54fee0d8ffa8d4bdbc7ad3fa4f70ec0a462cc/pkg/storage/replica_write.go#L380)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/and/an/
</blockquote></details>

done
___
*[pkg/storage/replica_write.go, line 310 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-COHS96ZChLIraCqbF:-M-D3bSJ9iA0ou56D_Eo:b-ytsxcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L310)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you double-check that this isn't causing anything new to escape to the heap? To be honest, this whole `onePCResult` stuff seems hard to read to me, so I'd vote to avoid it if possible.
</blockquote></details>

I've extracted the 1PC evaluation to a new method; I think it's a lot more readable now. PTAL.

I've stared at the goescape output for a while; things look pretty good.
___
*[pkg/storage/replica_write.go, line 312 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-COSBq6zuud1R0lqv4:-M-D4Q_k6UnTaUjoyRmj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L312)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're not setting `pErr` here? Could you comment why?
</blockquote></details>

done
___
*[pkg/storage/replica_write.go, line 318 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-COvFYD4E72T5M4B7-:-M-D6h0LDHSBsyddwTmm:b-57p06q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L318)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> otherwise we wouldn't have attempted 1PC
> ```

Is this true? What if the txn had read before and hit an uncertainty retry?
</blockquote></details>

well I was relying on the splitting of reads and writes. But I got rid of this assertion.
___
*[pkg/storage/replica_write.go, line 475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CPY7NCebp3D1hJgCt:-M-D71P5EjwKjyQrXrPB:b1nwkd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L475)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I know we talked about this before and I might have been the one to push you towards this, but "can" seems like the wrong word here. We often "can" perform a serverside retry - that doesn't mean that we "should". 
</blockquote></details>

When shouldn't we?

**Review by nvb — COMMENTED** [review]
> Reviewed 29 of 29 files at r7, 1 of 1 files at r8, 14 of 14 files at r9, 5 of 5 files at r10, 20 of 20 files at r11, 4 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/storage/replica_evaluate.go, line 356 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CMp9-2pHDE-6Xn8oM:-M-LBj315VvKjlJgjsyB:b-6ihs4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_evaluate.go#L356)):*
> No... If there's an EndTxn in the batch, then we can't return the WriteTooOld flag... We never did.

Sure, I'm not saying we can, I'm just confused how the code is working. We're never setting `writeTooOldState.err` to nil when we see an EndTxn that performs a server-side refresh, so what happens if it was set by a previous request in the same batch and then refreshed away during the evaluation of `EndTxn`?

Oh, or did we get rid of server-side refreshes within `cmd_end_transaction.go`? That must be it. I've looked at too many subtle variations of this change to have a sound mental model for how this works right now :smiley: 
___
*[pkg/storage/replica_write.go, line 475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CPY7NCebp3D1hJgCt:-M-LDWRB7zYuIFKQZIbe:bb41vww) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L475)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

When shouldn't we?
</blockquote></details>

When we succeeded in running the batch. But this is fine.
___
*[pkg/storage/replica_write.go, line 265 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-LCwyrB_d9VEaiNPHX:-M-LCwyrB_d9VEaiNPHY:bapplg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ac9e1375983bf41acad14270818dff4eda11a5/pkg/storage/replica_write.go#L265)):*
> ```Go
> 	if isOnePhaseCommit(ba) {
> 		res := r.evaluate1PC(ctx, idKey, ba, spans)
> 		if res.success == onePCSucceeded {
> ```

nit: use a switch statement and exhaustively check all three cases.
___
*[pkg/storage/replica_write.go, line 312 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-LD8UM60bRBBvK_Skw:-M-LD8UM60bRBBvK_Skx:b-v6j9pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ac9e1375983bf41acad14270818dff4eda11a5/pkg/storage/replica_write.go#L312)):*
> ```Go
> func (r *Replica) evaluate1PC(
> 	ctx context.Context, idKey storagebase.CmdIDKey, ba *roachpb.BatchRequest, spans *spanset.SpanSet,
> ) (_res onePCResult) {
> ```

What's up with the underscore? I'd name it something else if you don't want it to clash with `res`. Maybe `onePCRes`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_evaluate.go, line 356 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CMp9-2pHDE-6Xn8oM:-M-LFXjMD0sOJFr-_z3f:b-epwxvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_evaluate.go#L356)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> No... If there's an EndTxn in the batch, then we can't return the WriteTooOld flag... We never did.

Sure, I'm not saying we can, I'm just confused how the code is working. We're never setting `writeTooOldState.err` to nil when we see an EndTxn that performs a server-side refresh, so what happens if it was set by a previous request in the same batch and then refreshed away during the evaluation of `EndTxn`?

Oh, or did we get rid of server-side refreshes within `cmd_end_transaction.go`? That must be it. I've looked at too many subtle variations of this change to have a sound mental model for how this works right now :smiley: 
</blockquote></details>

Right, this commit gets rid of refreshing in `cmd_end_transaction.go`.
___
*[pkg/storage/replica_write.go, line 475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-CPY7NCebp3D1hJgCt:-M-LGgtm9RN77S3XKmrl:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3b30ba63fadd2eae5bc22ff25ca1c69c05db607/pkg/storage/replica_write.go#L475)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When we succeeded in running the batch. But this is fine.
</blockquote></details>

ack
___
*[pkg/storage/replica_write.go, line 265 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-LCwyrB_d9VEaiNPHX:-M-LG0e-22DBbvSTysfd:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ac9e1375983bf41acad14270818dff4eda11a5/pkg/storage/replica_write.go#L265)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: use a switch statement and exhaustively check all three cases.
</blockquote></details>

done
___
*[pkg/storage/replica_write.go, line 312 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-M-LD8UM60bRBBvK_Skw:-M-LGKxrCzadJBL3NLGM:b8hl9zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ac9e1375983bf41acad14270818dff4eda11a5/pkg/storage/replica_write.go#L312)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's up with the underscore? I'd name it something else if you don't want it to clash with `res`. Maybe `onePCRes`.
</blockquote></details>

done

But I like the underscores to indicate that the named ret vals are only to be used in defers.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-:-M-LLcliECRfxg866bQw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44507#-:-M-VqlG3B21I_b9V3_vL:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
