### PR TITLE
sql,distsqlrun,gossip: don't plan on incompatible nodes

### PR DESCRIPTION
**Pull request by andreimatei**
If we attempt to schedule a flow on a node who's DistSQL version is
incompatible, the scheduling is going to return an error.
This patch attempts to minimize the occurrence of these errors by not
planning flows on incompatible nodes. This is done by having each node
gossip it's range of accepted versions, and having planning consult
gossip before deciding to map key spans onto a node. Spans owned by
incompatible nodes are mapped to the gateway.

The planning version check is done in distSQLPlanner.partitionSpans().
This may not sounds like the right place for it, but there's currently
no better place. That's the layer that's currently similarly concerned
with node health because everything planned above TableReaders currently
mechanically follows the set of nodes decided in partitionSpans().
An alternative would be to lift the remapping onto the gateway to a
step done after the plan has been build, but that would lead to worse
plans.

### CODE REVIEW

**Comment by andreimatei** [comment]
@bdarnell for gossip stuff
cc @RaduBerinde 

I ran into trouble with #17497 which was supposed to make us resilient to DistSQL version mismatch errors (and other errors) through a runtime fallback mechanism - the fundamental issue is that it's hard to decide when to fallback because it's hard to conclude that you've connected to the wrong node.
So let's do this about version mismatch errors while I ponder fallbacks some more.

**Comment by RaduBerinde** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747#-Ks4M3a8jBG3Mu6aib_L:-Ks4M3a8jBG3Mu6aib_M:b-dmisv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/110558c7bf67a8aafc21001ca06cbcd3ecbff3cb/pkg/sql/distsql_physical_planner.go#L517)):*
> ```Go
> 					if compat, ok = nodeVerCompatMap[nodeID]; !ok {
> 						compat = dsp.nodeVersionIsCompatible(nodeID, dsp.planVersion)
> 						nodeVerCompatMap[nodeID] = compat
> ```

If we have an older node, then we upgrade it, it will be stuck as non-compatible forever no? Ideally these entries should time out

---

*[pkg/sql/executor.go, line 339 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747#-Ks4LXJHJ8J7vrTE_-k5:-Ks4LXJHJ8J7vrTE_-k6:b-l55gew) ([raw file](https://github.com/cockroachdb/cockroach/blob/110558c7bf67a8aafc21001ca06cbcd3ecbff3cb/pkg/sql/executor.go#L339)):*
> ```Go
> 	// accepting any version, the callback can return a 0..+inf acceptable version
> 	// range.
> 	OverrideDistSQLVersionCheck func(node roachpb.NodeID, res *distsqlrun.DistSQLVersionGossipInfo) error
> ```

[nit] Would be cleaner for this to return `(distsqlrun.DistSQLVersionGossipInfo, error)` instead of taking a pointer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747)*

**Comment by andreimatei** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747#-Ks4M3a8jBG3Mu6aib_L:-Ks4OFbejtSfvj4-QcpM:bwt9z1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/110558c7bf67a8aafc21001ca06cbcd3ecbff3cb/pkg/sql/distsql_physical_planner.go#L517)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we have an older node, then we upgrade it, it will be stuck as non-compatible forever no? Ideally these entries should time out
</blockquote></details>

`nodeVerMap` is just a per-query map (like `planCtx.nodeAddresses`).
When a node is upgraded, it will gossip its new version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747#-Ks4M3a8jBG3Mu6aib_L:-Ks5Ul5nsuSDE6BBMSs7:b7cztnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/110558c7bf67a8aafc21001ca06cbcd3ecbff3cb/pkg/sql/distsql_physical_planner.go#L517)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`nodeVerMap` is just a per-query map (like `planCtx.nodeAddresses`).
When a node is upgraded, it will gossip its new version.
</blockquote></details>

Ah, indeed, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747#-:-Ks5UmcKBi2G2pgEaPpz:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 339 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747#-Ks4LXJHJ8J7vrTE_-k5:-Ks65hilQtfrrrVPkaPr:b-cg8lzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/110558c7bf67a8aafc21001ca06cbcd3ecbff3cb/pkg/sql/executor.go#L339)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Would be cleaner for this to return `(distsqlrun.DistSQLVersionGossipInfo, error)` instead of taking a pointer
</blockquote></details>

done. I had written it like this to resemble the gossip interface, but I think I had already departed from that untyped interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17747)*

**Pull request merged**
