### PR TITLE
colflow: prevent deadlocks when many queries spill to disk at same time

### LINKED ISSUE #80290: roachtest: tpch_concurrency failed
roachtest.tpch_concurrency [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4935120&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4935120&tab=artifacts#/tpch_concurrency) on release-22.1 @ [81f47f1835784439f834c854f5c04cc97636b13f](https://github.com/cockroachdb/cockroach/commits/81f47f1835784439f834c854f5c04cc97636b13f):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/tpch_concurrency/run_1
	test_runner.go:1006,test_runner.go:905: test timed out (18h0m0s)
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #79870 roachtest: tpch_concurrency failed [C-test-failure O-roachtest O-robot T-sql-queries branch-master]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpch_concurrency.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-15783

### PR DESCRIPTION
**Pull request by yuzefovich**
**colflow: prevent deadlocks when many queries spill to disk at same time**

This commit fixes a long-standing issue which could cause
memory-intensive queries to deadlock on acquiring the file descriptors
quota when vectorized execution spills to disk. This bug has been
present since the introduction of disk-spilling (over two and a half
years ago, introduced in #45318 and partially mitigated in #45892), but
we haven't seen this in any user reports, only in `tpch_concurrency`
roachtest runs, so the severity seems pretty minor.

Consider the following query plan:
```
   Node 1                   Node 2

TableReader              TableReader
    |                         |
HashRouter                HashRouter
    |     \  ___________ /    |
    |      \/__________       |
    |      /           \      |
HashAggregator         HashAggregator
```
and let's imagine that each hash aggregator has to spill to disk. This
would require acquiring the file descriptors quota. Now, imagine that
because of that hash aggregators' spilling, each of the hash routers has
slow outputs causing them to spill too. As a result, this query plan can
require `A + 2 * R` number of FDs of a single node to succeed where `A`
is the quota for a single hash aggregator (equal to 16 - with the
default value of `COCKROACH_VEC_MAX_OPEN_FDS` environment variable which
is 256) and `R` is the quota for a single router output (2). This means
that we can estimate that 20 FDs from each node are needed for the query
to finish execution with 16 FDs being acquired first.

Now imagine that this query is run with concurrency of 16. We can end up
in such a situation that all hash aggregators have spilled, fully
exhausting the global node limit on each node, so whenever the hash
router outputs need to spill, they block forever since no FDs will ever
be released, until a query is canceled or a node is shutdown. In other
words, we have a deadlock.

This commit fixes this situation by introducing a retry mechanism to
exponentially backoff when trying to acquire the FD quota, until a time
out. The randomizations provided by the `retry` package should be
sufficient so that some of the queries succeed while others result in
an error.

Unfortunately, I don't see a way to prevent this deadlock from occurring
in the first place without possible increase in latency in some case.
The difficult thing is that we currently acquire FDs only once we need
them, meaning once a particular component spills to disk. We could
acquire the maximum number of FDs that a query might need up-front,
before the query execution starts, but that could lead to starvation of
the queries that ultimately won't spill to disk. This seems like a much
worse impact than receiving timeout errors on some analytical queries
when run with high concurrency. We're not an OLAP database, so this
behavior seems ok.

Fixes: #80290.

Release note (bug fix): Previously, CockroachDB could deadlock when
evaluating analytical queries f multiple queries had to spill to disk
at the same time. This is now fixed by making some of the queries error
out instead.

**roachtest: remove some debugging printouts in tpch_concurrency**

This was added to track down the deadlock fixed in the previous commit,
so we no longer need it.

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Unfortunately, I don't see a way to prevent this deadlock from occurring
> in the first place without possible increase in latency in some case.

Do you think it would be a good idea to expose the current number of acquired FDs and the estimated number a new query might use to admission control?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84398#-:-N6turgh6DcRXxDCJyvF:b-eyp6tt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/colflow/vectorized_flow.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84398#-N6tuKtH4jU5oMsV5eCW:-N6tuKtH4jU5oMsV5eCX:b-tfxap2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c9a09245a7a9dd7383a3126751158df9478f9d6/pkg/sql/colflow/vectorized_flow.go#L102)):*
> ```Go
> 	// it possible for other queries to proceed.
> 	opts := retry.Options{
> 		InitialBackoff:      100 * time.Millisecond,
> ```

This feels like a pretty long initial backoff time; what make you choose it?

**Review by yuzefovich — COMMENTED** [review]
Added a regression test with a single query. I think it is possible to come up with a single query without the usage of the testing knobs that would never be executed successfully (like a query with 16 hash joins, and each of them having to spill to disk, like a chain of operators with all of them as the right input to each other), and previously such a query would just deadlock, now it'll always result in an error. This is an extreme edge case, so probably not worth spending too much time thinking about it.

> Do you think it would be a good idea to expose the current number of acquired FDs and the estimated number a new query might use to admission control?

I think this number of file descriptors would be a bad resource to ask the admission control to pace. Imagine we execute a query with a hash join, with the current setting, it would be estimated to require 16 FDs. Let's assume that 99% of query executions don't spill to disk. Currently we can run such a query with concurrency of 1600 (256 / 16 / 1%) (subject to memory limits, if the tables are small) with no extra latency, but if we start estimating the FDs upfront and ask the admission control to pace these query executions, then we'd probably be able to only sustain on the order of 100 of such queries (it'll depend on what node-wide limit on number of FDs we'd use - I'd expect larger than 256, but not more than 10000 slots).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84398#-:-N6uFUnL4yjBgUB0AZBM:b-vrlt8f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @DrewKimball)

___
*[`pkg/sql/colflow/vectorized_flow.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84398#-N6tuKtH4jU5oMsV5eCW:-N6uF2NT1EPExWmtzOqL:bf4wdyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c9a09245a7a9dd7383a3126751158df9478f9d6/pkg/sql/colflow/vectorized_flow.go#L102)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

This feels like a pretty long initial backoff time; what make you choose it?
</blockquote></details>

My thinking is that we did try the fast path right above, and we couldn't acquire the quota, which means that the FD limit has been used up. This code path occurs only when spilling to disk, so the query latency is likely to be on the order of hundreds of milliseconds at least, thus, 100ms looks a good starting point (to allow other queries that spilled to finish and release the quota). Added some more commentary.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84398#-:-N6uNMZW4R5d2HLK5b7l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @DrewKimball)

**Review by yuzefovich — COMMENTED** [review]
Made a fix to a possibly infinite retry loop (I was misunderstanding was `MaxBackoff` was about). Also added another tiny commit, would appreciate another quick look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84398#-:-N6x9pL0ACFN-g5lkQce:b-iboaqb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @DrewKimball)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84398#-:-N6yRGhs6MGXhFGCXrOD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @DrewKimball)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
