### PR TITLE
distsql: initialize the transaction proto before using it in Flows

### PR DESCRIPTION
**Pull request by andreimatei**
cc @bdarnell

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/internal/client/txn.go, line 721 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-Kipmm-2ITJKmBz4mbrC:-Kipmm-2ITJKmBz4mbrD:bk7c77i) ([raw file](https://github.com/cockroachdb/cockroach/blob/16cb7fc346d46c675bda7afb0eca7333ca959644/pkg/internal/client/txn.go#L721)):*
> ```Go
> // after the transaction had been aborted), but DistSQL does it explicitly on
> // the gateway.
> func (txn *Txn) InitProtoIfNotInitialized() {
> ```

This name is a mouthful. How about `MaybeInitProto` or `EnsureProto`?

---

*[pkg/sql/executor.go, line 1861 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-KipmuePVIrnMKoeqO77:-KipmuePVIrnMKoeqO78:b-as7prw) ([raw file](https://github.com/cockroachdb/cockroach/blob/16cb7fc346d46c675bda7afb0eca7333ca959644/pkg/sql/executor.go#L1861)):*
> ```Go
> // possibly find problems if things change in the future, so it is left in.
> func SetTxnTimestamps(txn *client.Txn, ts hlc.Timestamp) {
> 	// TODO(andrei): These updates should be done with the txn locked.
> ```

I like TODOs, but sometimes they get lost. Mind filing an issue about this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-:-Kipn-_Kth-_CdS3UhZ-:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_running.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-KipoVLOfkOBvb3rFWv4:-KipoVLPyScakrnq7lMp:bglrfay) ([raw file](https://github.com/cockroachdb/cockroach/blob/16cb7fc346d46c675bda7afb0eca7333ca959644/pkg/sql/distsql_running.go#L124)):*
> ```Go
> 	// DistSQL needs to initialize the Transaction proto before we put it in the
> 	// FlowRequest's below. This is because we might not have used the txn do to
> 	// anything else (we haven't sent any requests throu
> ```

Finish the comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-:-Kipoqyalylo0oIj88Fg:bnfp4nl)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-:-KipovSYKe112lgfS7zG:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/internal/client/txn.go, line 721 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-Kipmm-2ITJKmBz4mbrC:-Kiq0920pvq-w13afWeG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16cb7fc346d46c675bda7afb0eca7333ca959644/pkg/internal/client/txn.go#L721)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This name is a mouthful. How about `MaybeInitProto` or `EnsureProto`?
</blockquote></details>

Done.

---

*[pkg/sql/distsql_running.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-KipoVLOfkOBvb3rFWv4:-Kiq0-UNby17Q3G_WOOH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16cb7fc346d46c675bda7afb0eca7333ca959644/pkg/sql/distsql_running.go#L124)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Finish the comment. 
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 1861 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-KipmuePVIrnMKoeqO77:-Kiq09_HuPNqhXEtkzYd:b-ovqdny) ([raw file](https://github.com/cockroachdb/cockroach/blob/16cb7fc346d46c675bda7afb0eca7333ca959644/pkg/sql/executor.go#L1861)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I like TODOs, but sometimes they get lost. Mind filing an issue about this?
</blockquote></details>

I'll go back and create issues for a number of TODOs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476)*

**Comment by RaduBerinde** [comment]
Update LGTM

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15476#-:-Kiq4uZtQ0jSHvx21SnN:b-2kmioq)*

**Pull request merged**
