### PR TITLE
server,settingswatcher: fix the local persisted cache

### LINKED ISSUE #70567: server: storeCachedSettingsKVs does not remove unset settings values
**Is your feature request related to a problem? Please describe.**

In `settingsworker.go` we store on disk in the system tenant a cache of settings. This allows us to have some access to all settings before the KV layer becomes available (e.g. during node restarts). 

When the settings watcher finds a rangefeed update, we write it https://github.com/cockroachdb/cockroach/blob/9c8aa87293a026a874dec816869e0cfa1e833154/pkg/server/settingsworker.go#L60

The issue is, when we write it, we don't clear out the values which are now unset. See https://github.com/cockroachdb/cockroach/blob/9c8aa87293a026a874dec816869e0cfa1e833154/pkg/server/settings_cache.go#L24-L38

**Describe the solution you'd like**
We should clear the keys which do exist and are not in the set we want to write.

**Additional context**

This can be very annoying as we might retain values which are no longer valid. See https://github.com/cockroachdb/cockroach/issues/68335. 

Jira issue: CRDB-10124
Epic: CRDB-6671

### LINKED ISSUE #111328: roachtest: change-replicas/mixed-version failed
roachtest.change-replicas/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11947061?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11947061?buildTab=artifacts#/change-replicas/mixed-version) on master @ [4b2badd7bc6c11a7646e66b131f5bcaf8328916a](https://github.com/cockroachdb/cockroach/commits/4b2badd7bc6c11a7646e66b131f5bcaf8328916a):

```
(test_runner.go:1140).runTest: test timed out (20m0s)
(versionupgrade.go:345).func1: timed out after 10m0s: expected n1 to be at cluster version 23.1-26, but is still at 23.1: not upgraded yet
test artifacts and logs in: /artifacts/change-replicas/mixed-version/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-11947061/change-replicas-mixed-version/1695793339137/1695794692336)

</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*change-replicas/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31859

### LINKED ISSUE #111422: server: broken setting reader
**Describe the problem**
Setting resets are currently broken across restarts. It was broken by #111145.

**To Reproduce**

1. change setting
2. reset setting
3. restart server
4. observe: the reset did not stick

**Expected behavior**

1. resets should propagate to the persisted cache
2. there should be a unit test for this functionality!!

Epic: CRDB-6671

Jira issue: CRDB-31891

### PR DESCRIPTION
**Pull request by knz**
There's two commits here, fixing 2 separate issues.
Epic: CRDB-6671

### server,settingswatcher: properly evict entries from the local persisted cache

Fixes #70567.
Supersedes #101472.

(For context, on each node there is a local persisted cache of cluster
setting customizations. This exists to ensure that configured values
can be used even before a node has fully started up and can start
reading customizations from `system.settings`.)

Prior to this patch, entries were never evicted from the local
persisted cache: when a cluster setting was reset, any previously
saved entry in the cache would remain there.

This is a very old bug, which was long hidden and was recently
revealed when commit https://github.com/cockroachdb/cockroach/commit/2f5d717178a87b42fa94c20a226cc491d185455d was
merged. In a nutshell, before this recent commit the code responsible
to load the entries from the cache didn't fully work and so the stale
entries were never restored from the cache. That commit fixed the
loader code, and so the stale entries became active, which made the
old bug visible.

To fix the old bug, this present commit modifies the settings watcher
to preserve KV deletion events, and propagates them to the persisted
cache.

(There is no release note because there is no user-facing release where
the bug was visible.)

### settingswatcher: write-through to the persisted cache

Fixes #111422.
Fixes #111328.

Prior to this patch, the rangefeed watcher over `system.settings` was
updating the in-RAM value store before it propagated the updates to
the persisted local cache.

In fact, the update to the persisted local cache was lagging quite a
bit behind, because the rangefeed watcher would buffer updates and
only flush them after a while.

As a result, the following sequence was possible:

1. client updates a cluster setting.
2. server is immediately shut down. The persisted cache
   has not been updated yet.
3. server is restarted. For a short while (until the settings watcher
   has caught up), the old version of the setting remains active.

This recall of ghost values of a setting was simply a bug. This patch
fixes that, by ensuring that the persisted cache is written through
before the in-RAM value store.

By doing this, we give up on batching updates to the persisted local
store. This is deemed acceptable because cluster settings are not
updated frequently.

### CODE REVIEW

**Review by stevendanna — DISMISSED** [review]
Thanks for digging into this situation.  Overall this looks good to me. Left a couple of minor comments for your consideration.

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-:-NfVDwWv0oqapO_55ZVg:b-uf4rhx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @knz)

___
*[`pkg/server/settingswatcher/settings_watcher.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVA29z3ALJuUs5ToFB:-NfVA29z3ALJuUs5ToFC:btrh2dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db9035242c80aa18b9007b72db383e41de56671/pkg/server/settingswatcher/settings_watcher.go#L296)):*
> ```Go
> 	// updates in the onUpdate rangefeed function.
> 	if s.storage != nil {
> 		s.snapshot = rangefeedbuffer.MergeKVsKeepingDeletions(s.snapshot, []roachpb.KeyValue{rkv})
> ```

I wondered for a bit whether it was possible to make the merging code more efficient given that we only ever update 1 value at a time. But, ultimately decided that, like you mentioned in one of the commit messages, settings are updated infrequently.

Another thing we could consider if this becomes an issue is returning some indicator about whether anything was actually updated to avoid extra KV traffic if it is unnecessary. For instance, if the rangefeed restarts under the hood such that we see a flurry of duplicates.

But again, let's handle that if we see it become an issue.  This traffic should be trivial overall.
___
*[`pkg/kv/kvclient/rangefeed/rangefeedbuffer/kvs_test.go` line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfV7YIA8j7SJ7gkqiZ5:-NfV7YIA8j7SJ7gkqiZ6:b-ittnl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea6a78d2575fc1dfa5e4fb372bc9f22b1190b581/pkg/kv/kvclient/rangefeed/rangefeedbuffer/kvs_test.go#L107)):*
> ```Go
> 
> // TestMergeKVs tests the logic of MergeKVsKeepingDeletions and the
> // logic of to extract KVs from a slice of events.
> ```

[nit] missing "EventToKVs" between "of" and "to" in the comment I think.
___
*[`pkg/kv/kvclient/rangefeed/rangefeedbuffer/kvs_test.go` line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVFIE18IJKaNFLdCL-:-NfVFIE18IJKaNFLdCL0:b6z2e70) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea6a78d2575fc1dfa5e4fb372bc9f22b1190b581/pkg/kv/kvclient/rangefeed/rangefeedbuffer/kvs_test.go#L168)):*
> ```Go
> 				{"c", 4, ""},
> 				{"d", 4, ""},
> 			},
> ```

Should we add some out of order keys in this update (I see the updates for b are out of timestamp order, but I mean something like reversing d and c).

Perhaps also a key at a lower timestamp than what we have in the existing snapshot.  Which I don't think can happen easily in the first commit but can definitely happen when we move this to being used in the translateEvent callback.

Both of these cases should work given your current implementation, so the test is just to prevent regressions there.
___
*[`pkg/settings/integration_tests/settings_test.go` line 292 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVBuKt7QAIs2qqsftJ:-NfVBuKt7QAIs2qqsftK:bhl1vpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db9035242c80aa18b9007b72db383e41de56671/pkg/settings/integration_tests/settings_test.go#L292)):*
> ```Go
> }
> 
> func TestSettingsPersistenceEndToEnd(t *testing.T) {
> ```

I wonder if we want a test that adds some testing hook into server startup so that we can test accessing settings in a way that guarantees we are relying on the version of the on-disk cache. I don't feel strongly about this suggestion.

**Review by aliher1911 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[`pkg/server/settingswatcher/settings_watcher.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVA29z3ALJuUs5ToFB:-NfVJkNcA01Yxo5WZIZa:b-kqhscm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db9035242c80aa18b9007b72db383e41de56671/pkg/server/settingswatcher/settings_watcher.go#L296)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I wondered for a bit whether it was possible to make the merging code more efficient given that we only ever update 1 value at a time. But, ultimately decided that, like you mentioned in one of the commit messages, settings are updated infrequently.

Another thing we could consider if this becomes an issue is returning some indicator about whether anything was actually updated to avoid extra KV traffic if it is unnecessary. For instance, if the rangefeed restarts under the hood such that we see a flurry of duplicates.

But again, let's handle that if we see it become an issue.  This traffic should be trivial overall.
</blockquote></details>

We must be only writing to a local store, not even under proper mvcc so the only downside must be pebble compaction/iteration over garbage which I think is negligible here. At least that's how I understand this setting storage here.
___
*[`pkg/server/settings_cache_test.go` line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVKdOFANnK3_icLz38:-NfVKdOFANnK3_icLz39:biarp1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db9035242c80aa18b9007b72db383e41de56671/pkg/server/settings_cache_test.go#L185)):*
> ```Go
> 	testutils.SucceedsSoon(t, func() error {
> 		store, err := ts.GetStores().(*kvserver.Stores).GetStore(1)
> 		if err != nil {
> ```

We can `require.NoError(t, err, "failed to get store")` here and below to avoid retry in cases where we can only get fatal errors. Also less lines to read.

**Comment by stevendanna** [comment]
Backfilling some commentary from slack. An issue we might want to consider is what happens when:

```
1. What happens if the following happens:
2. Write cluster setting a
3. See range feed update for write
4. Update cache
5. Reset cluster setting a
6. Crash before range feed sees update
```

**Review by knz — COMMENTED** [review]
The special case mentioned above is now handled via DeleteRange.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-:-NfWwHiPCZ33z8MHYlXi:bbgyw9v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @stevendanna)

___
*[`pkg/server/settingswatcher/settings_watcher.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVA29z3ALJuUs5ToFB:-NfWwCsK8tZFKroaod1W:bsmz3eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db9035242c80aa18b9007b72db383e41de56671/pkg/server/settingswatcher/settings_watcher.go#L296)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

We must be only writing to a local store, not even under proper mvcc so the only downside must be pebble compaction/iteration over garbage which I think is negligible here. At least that's how I understand this setting storage here.
</blockquote></details>

I went for the DeleteRange route. It's so much easier to read and understand.
___
*[`pkg/server/settings_cache_test.go` line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVKdOFANnK3_icLz38:-NfWtV42445fEbYgvdxl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db9035242c80aa18b9007b72db383e41de56671/pkg/server/settings_cache_test.go#L185)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

We can `require.NoError(t, err, "failed to get store")` here and below to avoid retry in cases where we can only get fatal errors. Also less lines to read.
</blockquote></details>

Done.
___
*[`pkg/settings/integration_tests/settings_test.go` line 292 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfVBuKt7QAIs2qqsftJ:-NfWtXKSAMwXzYnne9Hc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db9035242c80aa18b9007b72db383e41de56671/pkg/settings/integration_tests/settings_test.go#L292)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I wonder if we want a test that adds some testing hook into server startup so that we can test accessing settings in a way that guarantees we are relying on the version of the on-disk cache. I don't feel strongly about this suggestion.
</blockquote></details>

Done.

**Comment by knz** [comment]
PTAL

**Review by stevendanna — APPROVED** [review]

**Comment by knz** [comment]
TFYRs!

bors r=stevendanna,aliher1911

**Comment by knz** [comment]
bors r-

the kv testsuite is not happy yet

**Comment by knz** [comment]
unrelated flake: #111426

**Comment by knz** [comment]
bors r=stevendanna,aliher1911

**Review by RaduBerinde — COMMENTED** [review]
LGTM with one question

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-:-NfXSvt96egqc-PzSCaf:b-pg846l)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/server/settingswatcher/settings_watcher.go` line 297 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111475#-NfXSQK592GbfNcKvh7m:-NfXSQK592GbfNcKvh7n:b-9ojpml) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5af6243bde3fdf75e51f7728914e01267a935cb/pkg/server/settingswatcher/settings_watcher.go#L297)):*
> ```Go
> 	if s.storage != nil {
> 		s.snapshot = rangefeedbuffer.MergeKVs(s.snapshot, []roachpb.KeyValue{rkv})
> 		s.storage.SnapshotKVs(ctx, s.snapshot)
> ```

SnapshotKV runs the update asynchronously... If we're not waiting for it, we reduced the window but it's still there. Maybe that's ok but then the comment should be honest about that, currently it suggests a clear sequencing.

**Comment by knz** [comment]
> SnapshotKV runs the update asynchronously... If we're not waiting for it, we reduced the window but it's still there.

:scream: i did not see this.

**Pull request merged**
