### PR TITLE
roachtest: attempt to fix cancel test

### LINKED ISSUE #38417: roachtest: cancel/tpcc/distsql/w=10,nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/2811e0fb4deded2a459594f0f3065650ca92cf6d

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=cancel/tpcc/distsql/w=10,nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1359691&tab=buildLog

```
The test failed on branch=provisional_201906242300_v19.2.0-alpha.20190701, cloud=gce:
	cancel.go:65: query completed before it could be canceled
	cluster.go:1511,cancel.go:82,cluster.go:1849,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1359691-cancel-tpcc-distsql-w-10-nodes-3:1 -- ./cockroach sql --insecure -e "CANCEL QUERIES
			SELECT query_id FROM [SHOW CLUSTER QUERIES] WHERE query not like '%SHOW CLUSTER QUERIES%'" returned:
		stderr:
		
		stdout:
		CANCEL QUERIES 0
		: signal: killed
	cluster.go:1870,cancel.go:100,cancel.go:118,test.go:1249: Goexit() was called

```

### PR DESCRIPTION
**Pull request by jordanlewis**
There was some suspicious stuff going on in the test, which has been
failing - try to fix it in the hopes that next time it'll be more clear
what's going on.

Attempt to fix #38417

Release note: None
Release justification: test-only change

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]

**Comment by rohany** [comment]
LGTM

I wonder how hard it is to write a linter for this...

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41032)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/cmd/roachtest/cancel.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41032#-LpYnAYQ521-N57xl7Zy:-LpYnAYQ521-N57xl7Zz:b59gsmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/68037fe5289ebb3f423a3edafb6cc61dfaa6cae2/pkg/cmd/roachtest/cancel.go#L59)):*
> ```Go
> 			for _, q := range queries {
> 				sem := make(chan struct{}, 1)
> 				go func(q string) {
> ```

i wonder why `q` needs to be a param, but `t` and `queryPrefix` do not?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41032)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/cancel.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41032#-LpYnAYQ521-N57xl7Zy:-LpYoC4a9Xlx_ARIMfxh:b-gf1tzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/68037fe5289ebb3f423a3edafb6cc61dfaa6cae2/pkg/cmd/roachtest/cancel.go#L59)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i wonder why `q` needs to be a param, but `t` and `queryPrefix` do not?
</blockquote></details>

only things that are "changing" in the loop need to be captured as arguments

**Comment by jordanlewis** [comment]
Oops, used the wrong logger method...

bors r+

**Pull request merged**
