### PR TITLE
sql: add txn isolation to crdb_internal.cluster_locks

### LINKED ISSUE #100152: sql: add txn isolation to crdb_internal.cluster_locks
With the introduction of multiple isolation levels, we should add a new iso_level column to the `crdb_internal.cluster_locks` virtual table.

Once `IsoLevel` is included in `TxnMeta` (https://github.com/cockroachdb/cockroach/pull/100019), each lock holder's isolation level will be returned by the `QueryLocks` API.

Jira issue: CRDB-26573

Epic CRDB-26547

### PR DESCRIPTION
**Pull request by annrpom**
This adds the `isolation_level` column to internal table `crdb_internal.cluster_locks`.

Epic: CRDB-26547
Fixes: #100152

Release note (sql change): The crdb_internal.cluster_locks table now has a column for isolation level (isolation_level).

### CODE REVIEW

**Review by andyyang890 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107309)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @ericharmeling)

___
*[`pkg/sql/crdb_internal.go` line 7404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107309#-N_pInWd2tXkiClLF3-Q:-N_pInWd2tXkiClLF3-R:b-v09i3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ae4f40ff743332fbf7b2f82b8f57fbbee6217d/pkg/sql/crdb_internal.go#L7404)):*
> ```Go
>     contended           BOOL NOT NULL,
>     duration            INTERVAL,
>     iso_level 					STRING NOT NULL,
> ```

Maybe we should name this `isolation_level` to be more internally (pun intended) consistent with other `crdb_internal` tables

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107309)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @ericharmeling, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 7404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107309#-N_pInWd2tXkiClLF3-Q:-N_sprWZEdBBShqRV3MS:b-6axe0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ae4f40ff743332fbf7b2f82b8f57fbbee6217d/pkg/sql/crdb_internal.go#L7404)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Maybe we should name this `isolation_level` to be more internally (pun intended) consistent with other `crdb_internal` tables
</blockquote></details>

nod nod - i did `iso_level` to coordinate with the `IsoLevel` i saw in `TxnMeta`; would it make more sense for the other `crdb_internal` tables to follow along with this naming or does the distinction make little to no difference (in which case i shall change to match with the internal tables) ?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107309)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @ericharmeling, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 7404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107309#-N_pInWd2tXkiClLF3-Q:-N_sxD9W4umQVRrnmc6N:b-jco09d) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ae4f40ff743332fbf7b2f82b8f57fbbee6217d/pkg/sql/crdb_internal.go#L7404)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

nod nod - i did `iso_level` to coordinate with the `IsoLevel` i saw in `TxnMeta`; would it make more sense for the other `crdb_internal` tables to follow along with this naming or does the distinction make little to no difference (in which case i shall change to match with the internal tables) ?
</blockquote></details>

I would say that the important thing is that the tables have internally consistent names since they're what the user would see. I would just stick with `isolation_level` since that's already out in the wild.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107309)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @ericharmeling, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 7404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107309#-N_pInWd2tXkiClLF3-Q:-N_szGOM7WbJbelMCDhu:b-lj3rb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ae4f40ff743332fbf7b2f82b8f57fbbee6217d/pkg/sql/crdb_internal.go#L7404)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I would say that the important thing is that the tables have internally consistent names since they're what the user would see. I would just stick with `isolation_level` since that's already out in the wild.
</blockquote></details>

yessir - sgtm!

**Review by andyyang890 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107309#-:-N_tML0O1YttHruVNITE:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @rafiss)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107309)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @annrpom, and @ericharmeling)

___
*[`pkg/sql/crdb_internal.go` line 7679 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107309#-N_tYWrkCH6BMYKlxRJk:-N_tYWrl8cutH8cmdKzQ:bb1m22c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab36ca43ace433c633657d814daee16f29dbdad/pkg/sql/crdb_internal.go#L7679)):*
> ```Go
> 				tree.MakeDBool(len(curLock.Waiters) > 0),              /* contended */
> 				durationDatum,                                         /* duration */
> 				tree.NewDString(curLock.LockHolder.IsoLevel.String()), /* isolation_level */
> ```

super nit: could you make this `kvTxnIsolationLevelToTree(curLock.LockHolder.IsoLevel).String()`. that version is the one that we use in our user-facing syntax (it changes things to upper case like READ_COMMITTED)

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107309)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890, @ericharmeling, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 7679 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107309#-N_tYWrkCH6BMYKlxRJk:-N_tkSCC1Apgs3uWLr9W:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab36ca43ace433c633657d814daee16f29dbdad/pkg/sql/crdb_internal.go#L7679)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: could you make this `kvTxnIsolationLevelToTree(curLock.LockHolder.IsoLevel).String()`. that version is the one that we use in our user-facing syntax (it changes things to upper case like READ_COMMITTED)
</blockquote></details>

done!

**Pull request merged**
