### PR TITLE
server: log runtime stats as a structured event

### LINKED ISSUE #63750: server: report runtime stats as a structured event
Every 10 seconds, the server reports health metrics in the HEALTH logging channel, for example:

```
I210323 20:53:53.714286 232 2@server/status/runtime.go:553 ⋮ [n1] 1  runtime stats: 106 MiB RSS, 248 goroutines (stacks: 4.3 MiB), 28 MiB/51 MiB Go alloc/total (heap fragmentation: 5.2 MiB, heap reserved: 2.5 MiB, heap released: 24 MiB), 18 MiB/30 MiB CGO alloc/total (0.0 CGO/sec), 0.0/0.0 %%(u/s)time, 0.0 %%gc (0x), 46 KiB/107 KiB (r/w)net
```

(this logging occurs in `server/status/runtime.go`)

Our users have expressed interest in making this information more reliably parsable. We should use a structured event for this purpose.

To do this requires approximately the following steps:

1. define a new category for HEALTH events in `pkg/util/log/eventpb`, possibly in `cluster_events.go`
2. define a new event type for the runtime stats. Use descriptive names for the fields and document them
3. use `log.Structured` instead of `log.Health.Infof` in `runtime.go`.

### PR DESCRIPTION
**Pull request by cameronnunez**
Fixes [#63750](https://github.com/cockroachdb/cockroach/issues/63750).

Runtime stats were logged using a flat text format.
This is not stable and not easy to parse.
It has now been converted to structured logging.

Release note (cli change): server health metrics are now a structured event sent to
the HEALTH logging channel. Refer to the reference docs for details about the event
payload.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
The overall structure of the code is good, and so is your commit message :100: 

Yet I'd like to challenge you: why did you choose to pre-format the various values as strings?
All the numeric values could be stored in the proto data structure as numeric (either integer or float). What is the added value of converting them to string upfront? How does this influence the ability of other monitoring tools downstream to re-interpret the data numerically?

> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-:-M_Vc0uK5Be0J46SIUUx:b-5rmjyf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[pkg/server/BUILD.bazel, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_Vb29u3JvmsUGr8XiR:-M_Vb29vCOwRsbTNrGtz:b-swkrsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffdb749cf8948063d0fd0deb54df87b89ea0103a/pkg/server/BUILD.bazel#L198)):*
> ```Starlark
>     ] + select({
>         "@io_bazel_rules_go//go/platform:aix": [
>             "//pkg/util/log/eventpb",
> ```

please lift this entry into the common list above, so it doesn't need to be repeated N times

(in fact, I suspect you edited this file manually; the CI failure is telling me that much. I think this is not desired nor necessary. You can use `make bazel-generate` to re-populate this file from the remainder of the sources.)
___
*[pkg/server/status/runtime_stats_test.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_VbMmJ3Po6Z6LTkBCO:-M_VbMmJ3Po6Z6LTkBCP:b-7swhsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffdb749cf8948063d0fd0deb54df87b89ea0103a/pkg/server/status/runtime_stats_test.go#L60)):*
> ```Go
> 		}
> 		foundEntry = true
> 		e.Message = strings.TrimPrefix(e.Message, "Structured entry:")
> ```

The other tests you've used for inspiration contain explanatory comments here that explain that part of this code should be deleted in a later version. These comments are relevant in your test just as well, so you should keep them.

**Comment by cameronnunez** [comment]
Thanks! @knz 
> The overall structure of the code is good, and so is your commit message 💯
> 
> Yet I'd like to challenge you: why did you choose to pre-format the various values as strings?
> All the numeric values could be stored in the proto data structure as numeric (either integer or float). What is the added value of converting them to string upfront? How does this influence the ability of other monitoring tools downstream to re-interpret the data numerically?

The advantage I was thinking of was that the users would clearly see the units (mebibytes for most of the fields), but maybe that would be obvious given the values and/or the standard. Is this the case? Having the fields as strings would clearly make them more difficult to interpret numerically by the downstream monitoring tools. 

I can remove the pre-formatting but just wondering: will users have access to units information for the event fields?

**Review by rauchenstein — COMMENTED** [review]
@cameronnunez 
> The advantage I was thinking of was that the users would clearly see the units [...]

One of the main benefits of adding structure to logs is to make it easy for a machine to ingest this data.  Humans looking at logfiles is a real use-case -- that's why they're ASCII, after all -- but it may not be the use-case to optimize for.  Other use-cases would be a machine reading the logfiles, finding the lines with this structured data, and storing it in a database.  From there maybe it can be directly queried and analyzed, or drive graphs on a dashboard somewhere, or send out alerts if certain thresholds are met.  If I was writing such a system, I'd really appreciate having plain numbers to work with instead of having to parse strings with varying units.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-:-M_Wa11f3QibDOyFkPvQ:bp56lo5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

**Comment by knz** [comment]
Unsure if y'all discussed this already, but what we can do is to log side-by-side:

- the current template with formatted values on the DEV channel
- the structured payload on the HEALTH channel

**Review by rauchenstein — CHANGES_REQUESTED** [review]
If we go the direction of separately formatted logging, I'd suggest that the protobuf be authoritative and the template be factored into a function of the protobuf.  This would avoid situations where we need to hunt down both logs to get the "full picture," since the template could not contain additional information not derived from the protobuf.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-:-M_a7gPa603H2SWsmUIw:b-ov1qjd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[pkg/util/log/eventpb/health_events.proto, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_a5j_64ooxrF-S5ihZ:-M_a5j_64ooxrF-S5ih_:b-o6e37k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffdb749cf8948063d0fd0deb54df87b89ea0103a/pkg/util/log/eventpb/health_events.proto#L39)):*
> ```protobuf
>   string num_goroutines = 3 [(gogoproto.jsontag) = ",omitempty"];
>   // The stack system memory used. Expressed as mebibytes.
>   string stack_sys_memory = 4 [(gogoproto.jsontag) = ",omitempty"];
> ```

Are these fields strings instead of numbers to match existing logged protobufs?  If not, I'd suggest letting numbers be numbers for type-safety when ingesting it down the line -- no need to worry about parsing errors.

Similarly, the "ratio" fields would then need to be two separate fields.  For instance, host_net_bytes_ratio (currently a string containing both the kB sent and kB received) would be a separate field for bytes sent and bytes received.

**Review by knz — COMMENTED** [review]
Thank you for this!

Just a few things and this will be good to go.

(and I love the humor in the release note! although you may want to extend that sentence a little bit and refer the reader to the fact it's now structured entry and they should refer to the event docs for details.)

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-:-M_asIvoATXIiioi3y_G:biua9zr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[pkg/server/status/runtime.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_asCQ8AsFM17bf-QNy:-M_asCQ8AsFM17bf-QNz:b-ws23ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1c637b870b6f87cf14f0db424c6e5616a7b941/pkg/server/status/runtime.go#L529)):*
> ```Go
> 	// Log summary of statistics to console.
> 	cgoRate := float64((numCgoCall-rsr.last.cgoCall)*int64(time.Second)) / dur
> 	goMemStatsStale := timeutil.Now().Sub(ms.Collected) > time.Second
> ```

I think we want to preserve a boolean in the struct to report the staleness as well.
___
*[pkg/util/log/eventpb/health_events.proto, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_arsLlCcO7_t8dPhRs:-M_arsLmCjROVHXPWj-U:bl6t74h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1c637b870b6f87cf14f0db424c6e5616a7b941/pkg/util/log/eventpb/health_events.proto#L23)):*
> ```protobuf
> // Events in this category pertain to the health of one or more servers.
> //
> // They are relative to a particular SQL tenant.
> ```

This paragraph is not relevant to health events, since these do not get persisted. So you can remove it (and re-generate the auto-doc).
___
*[pkg/util/log/eventpb/health_events.proto, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_arC-j7nCvGsP9S2mb:-M_arC-j7nCvGsP9S2mc:b6y19t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1c637b870b6f87cf14f0db424c6e5616a7b941/pkg/util/log/eventpb/health_events.proto#L36)):*
> ```protobuf
>   CommonEventDetails common = 1 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
>   // The process RSS. Expressed as bytes.
>   int64 rss = 2 [(gogoproto.customname) = "RSS", (gogoproto.jsontag) = ",omitempty"];
> ```

Most of the fields are positive numbers so you can use the `uint64` type instead.

**Comment by cameronnunez** [comment]
Thank you @knz!

> > 	goMemStatsStale := timeutil.Now().Sub(ms.Collected) > time.Second
> 
> I think we want to preserve a boolean in the struct to report the staleness as well.

Yes! Actually added in a boolean in the struct `GoStatsStale` which replaces the string `StaleMessage`.

**Review by rauchenstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[docs/generated/eventlog.md, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_b-VgD1kCzfiY_Q7YM:-M_b-VgD1kCzfiY_Q7YN:b-ddpfwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffdb749cf8948063d0fd0deb54df87b89ea0103a/docs/generated/eventlog.md#L159)):*
> ```Markdown
> | Field | Description | Sensitive |
> |--|--|--|
> | `RSS` | The process RSS. Expressed as mebibytes. | yes |
> ```

Probably worth spelling out Resident Set Size in the description.
___
*[pkg/server/status/runtime.go, line 533 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_b3PRI7U3W1V5npIkO:-M_b3PRI7U3W1V5npIkP:b-mwazwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1c637b870b6f87cf14f0db424c6e5616a7b941/pkg/server/status/runtime.go#L533)):*
> ```Go
> 
> 	log.StructuredEvent(ctx, &eventpb.RuntimeStats{
> 		RSS: int64(mem.Resident),
> ```

nit: Are all these casts necessary?
___
*[pkg/util/log/eventpb/health_events.proto, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-M_b085rCgg0JLBOEbPl:-M_b085rCgg0JLBOEbPm:b-emk1mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1c637b870b6f87cf14f0db424c6e5616a7b941/pkg/util/log/eventpb/health_events.proto#L33)):*
> ```protobuf
> 
> // RuntimeStats is recorded every 10 seconds as server health metrics.
> message RuntimeStats {
> ```

Would suggest:
"_bytes" suffix for all relevant fields.
"mem_" prefix to group memory-related fields not already sharing "go_", "heap_" or "cgo_" prefixes.  (rss and stack_sys)
cgo_rate -> cgo_call_rate to make clear what it's a rate of.
Might change "host_net_" prefix to "net_host_" in anticipation of future network-related stats, which would then share a common "net_" prefix.
Currently cpu_*_percent stats are in the range [0,1] instead of scaled [0,100], i.e. it's not a percentage.  Either scale the stat or name it "_util" (for utilization) or something.
Naming inconsistency in count-type stats: num_goroutines vs gc_count.  Maybe goroutine_count?
Not sure if there's a better name for gc_count to make clearer what it's actually counting.  Runs?  Passes?  Sweeps?  It's not awful as-is, but maybe you'll think of something.

I think that's the last of my field naming tweaks, so LGTM after that.

**Review by rauchenstein — COMMENTED** [review]
Hold up, if we're actually bothering to calculate exactly how state our data is, would it makes sense to log ms.Collected instead of reducing this to a bool?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-:-M_b5qNn-KmtiZACFcrw:b-guf69t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

**Comment by cameronnunez** [comment]
> Hold up, if we're actually bothering to calculate exactly how state our data is, would it makes sense to log ms.Collected instead of reducing this to a bool?

Good catch. It make sense to me that logging how stale the data is is preferable.

**Comment by cameronnunez** [comment]
> > Hold up, if we're actually bothering to calculate exactly how state our data is, would it makes sense to log ms.Collected instead of reducing this to a bool?
> 
> Good catch. It make sense to me that logging how stale the data is is preferable.

@rauchenstein do you think it is reasonable to express this in seconds? In previous logs, entries were considered stale
if they were at least 1 second old.

**Review by rauchenstein — COMMENTED** [review]
Yeah, staleness in seconds seems reasonable.  As a float, of course, otherwise we're back to usually being 0-or-1 seconds.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-:-M_bHlbk2sh0IfsMwDIr:bequwjl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

**Review by rauchenstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @knz)

**Review by knz — APPROVED** [review]
:lgtm: very nice

although the CI failure is trying to tell you something, so there's one more thing remaining.

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65024#-:-M_erw1J2Y0cRm_ss4kL:b-5l9pso)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cameronnunez)

**Comment by cameronnunez** [comment]
bors r=knz,rauchenstein

**Pull request merged**
