### PR TITLE
allocator2: structural normalization of SpanConfig

### PR DESCRIPTION
**Pull request by sumeerbhola**
The structural normalization is invoked as part of the normalization step. Also includes unit testing of all the normalization code.

Informs #103320

Epic: CRDB-25222

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
:lgtm: 

Some minor comments.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-:-NVZxxo311n4Sb2zCn_N:b-py32j2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVWls1DBLYyU35hG_hb:-NVWls1DBLYyU35hG_hc:b-e4joef) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/constraint.go#L90)):*
> ```Go
> 	//   their SpanConfigs and retries.
> 	//
> 	// - Write the code for this structural-normalization. It will establish
> ```

Can this TODO be removed now?
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZsXwz2OC8jWd0E2g_:-NVZsXwz2OC8jWd0E2ga:boloxmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/constraint.go#L474)):*
> ```Go
> 	for {
> 		added := false
> 		for i := index; i < len(rels) && rels[i].voterAndAllRel == conjStrictSuperset; i++ {
> ```

I found this a bit difficult to follow, I think it could use a comment on the mechanism.

My understanding is this iterating over strict superset relations repeatedly and when finding a normalized voter constraint which doesn't add to the original voter constraint, adding a new voter constraint with the relating all-replica constraint. After the first pass, this is only bumping the constraints made in the first iteration?

Also double checking, this readjustment includes the empty voter constraint index?

Is there a test case which hits the second iteration, I'm not sure I saw one below.
___
*[`pkg/roachpb/span_config.proto` line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZvCWb8GHsSYuNtRzE:-NVZvCWb8GHsSYuNtRzF:b-ggj231) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/roachpb/span_config.proto#L173)):*
> ```protobuf
>   // defined as: if we satisfy VoterConstraints (by satisfying NumVoters and
>   // ConstraintsConjunction.NumReplicas for all ConstraintsConjunctions in
>   // VoterConstraints), then:
> ```

Could we add an examples of span configs which meet this strictness requirement and those which do not. 

The last two test case sin the datadriven test would fit the bill for violating strictness.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint_test.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZwyGK9CSZNS_7aBFb:-NVZwyGK9CSZNS_7aBFc:b-6rnj50) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/constraint_test.go#L31)):*
> ```Go
> // - rangeAnalyzedConstraints read-only functions.
> 
> func TestNormalizedSpanConfig(t *testing.T) {
> ```

Really nice test!

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-:-NV_j6Ul-b36EPMmrdzV:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVWls1DBLYyU35hG_hb:-NV_Pj8W5kbKyBwuBt66:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/constraint.go#L90)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Can this TODO be removed now?
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZsXwz2OC8jWd0E2g_:-NV_RPeS-aqSmPraKBGT:b-rdlirj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/constraint.go#L474)):*
> I found this a bit difficult to follow, I think it could use a comment on the mechanism.

> My understanding is this iterating over strict superset relations repeatedly and when finding a normalized voter constraint which doesn't add to the original voter constraint, adding a new voter constraint with the relating all-replica constraint.

Added a comment

> After the first pass, this is only bumping the constraints made in the first iteration?

I didn't understand this question. Could you elaborate?

> Also double checking, this readjustment includes the empty voter constraint index?

Correct. Included in the new comment.

> Is there a test case which hits the second iteration, I'm not sure I saw one below.

Good point. Added one (see the comment `# Single-region very under-specified.`).
___
*[`pkg/roachpb/span_config.proto` line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZvCWb8GHsSYuNtRzE:-NV_imeN8ubzSBEauj7G:bbrwtt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/roachpb/span_config.proto#L173)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could we add an examples of span configs which meet this strictness requirement and those which do not. 

The last two test case sin the datadriven test would fit the bill for violating strictness.

</blockquote></details>

Added an example. Let me know if you want more examples.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103325)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NV_jFvl6MDlyjF_d8Zy:-NV_jFvl6MDlyjF_d8Zz:bpz5k61) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74c895810528c0d2e2dbfcca8ecf5004afbfdb/pkg/kv/kvserver/allocator/allocator2/constraint.go#L475)):*
> ```Go
> 	// to narrow unnecessarily, and so if emptyConstraintIndex has some
> 	// remainingReplicas, we take them here.
> 	if emptyVoterConstraintIndex > 0 && emptyConstraintIndex > 0 {
> ```

I lifted the code that was happening after the narrowing up here since we don't want to narrow unnecessarily.
This has changed some of the unit test output.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NV_jUvF0ttcC4_Ntz2I:-NV_jUvG29g9i7NNTBhj:b-79gu30) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config#L68)):*
> ```
>  voter-constraints:
>    +zone=us-west-a:2
>    +rack=10,-zone=us-west-b:1
> ```

this was unnecessarily narrowed. We can steal from the empty constraint that has 2 remaining replicas. Let the non-voters be more constrained.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NV_jrjs7M7KXYEtgtjB:-NV_jrjs7M7KXYEtgtjC:b-ijtc7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74c895810528c0d2e2dbfcca8ecf5004afbfdb/pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config#L95)):*
> ```
>    +region=a,+zone=a1:1
>    +region=a,-zone=a1:1
>    :1
> ```

this one had also been unnecessarily narrowed. The two non-empty voter constraints have used 2 replicas from the empty constraint, but there is still 1 remaining.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NV_kCzg9Jxs0klJEBTR:-NV_kCzg9Jxs0klJEBTS:b-q4u0d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74c895810528c0d2e2dbfcca8ecf5004afbfdb/pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config#L104)):*
> ```
> constraint num-replicas=1 +region=d
> voter-constraint num-replicas=1 +region=a +zone=a1
> voter-constraint num-replicas=1 +region=a -zone=a1
> ```

In this case the empty constraint starts with 2 remaining replicas, which are both consumed by the non-empty voter constraints. So the empty voter constraint does get narrowed.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config` line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NV_kZRx2hXbteKlEQYt:-NV_kZRx2hXbteKlEQYu:b9z1oua) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74c895810528c0d2e2dbfcca8ecf5004afbfdb/pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config#L246)):*
> ```
>    +region=a:1
>    +region=b:1
>    :2
> ```

another unnecessary narrowing. There were 4 replicas in the empty constraint, and only 2 got consumed by this non-empty voter constraint (+region=f), so there were 2 more to give.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config` line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NV_krWx1EmJC-QbUV7q:-NV_krWx1EmJC-QbUV7r:b1watn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74c895810528c0d2e2dbfcca8ecf5004afbfdb/pkg/kv/kvserver/allocator/allocator2/testdata/normalize_config#L344)):*
> ```
> constraint num-replicas=3 +region=a +zone=a2
> constraint num-replicas=3 +region=a +zone=a3
> voter-constraint num-replicas=5 +region=a
> ```

this is the case that causes multiple iterations of the outer for loop.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-:-NV_mV2e1dqfmhe-KVPY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZsXwz2OC8jWd0E2g_:-NV_kGmkEcePbPcwpa-T:bl5hcad) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/constraint.go#L474)):*
> After the first pass, this is only bumping the constraints made in the first iteration?

I meant to clarify: are all new voter constraints constructed during the first iteration of `rels` which are`conjStrictSuperset`, then any subsequent iteration over `rels` (outer for loop) only adding voters to existing constraints?
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NV_jFvl6MDlyjF_d8Zy:-NV_lomB6RbMM_jClk1k:b-ipys7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/db74c895810528c0d2e2dbfcca8ecf5004afbfdb/pkg/kv/kvserver/allocator/allocator2/constraint.go#L475)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I lifted the code that was happening after the narrowing up here since we don't want to narrow unnecessarily.
This has changed some of the unit test output.
</blockquote></details>

ack - I thought it was intentionally narrowing for some purpose on my first pass.
___
*[`pkg/roachpb/span_config.proto` line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZvCWb8GHsSYuNtRzE:-NV_l33QDyr5dGYI5zoe:br06oxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/roachpb/span_config.proto#L173)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Added an example. Let me know if you want more examples.
</blockquote></details>

Looks good, thanks!

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103325)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103325#-NVZsXwz2OC8jWd0E2g_:-NVdyu_i8s0JBeqW-nzr:b-2i8ppa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4bd872de11bc959a3d66a38f0f0e95da2fadab/pkg/kv/kvserver/allocator/allocator2/constraint.go#L474)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> After the first pass, this is only bumping the constraints made in the first iteration?

I meant to clarify: are all new voter constraints constructed during the first iteration of `rels` which are`conjStrictSuperset`, then any subsequent iteration over `rels` (outer for loop) only adding voters to existing constraints?
</blockquote></details>

Yes, that is correct, since the multiple passes are just for load-balancing by adding 1 replica at a time.

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
