### PR TITLE
build: run benchmarks on a single TC builder

### PR DESCRIPTION
**Pull request by tamird**
This doesn't upload the benchmarks anywhere; it just runs them and
stores the output.

### CODE REVIEW

**Comment by benesch** [comment]
Nice! I don't see any problems, but deferring to @marc's judgment.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/teamcity-benchmarks.sh, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15365#-KifYCM7-qzZa2wWkJL6:-KifYCM7-qzZa2wWkJL7:b6t0bve) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2522206f32678e523f644f59be392ef77b15ec7/build/teamcity-benchmarks.sh#L11)):*
> ```Shell
> 	make TYPE=release bench \
> 	TESTFLAGS='-benchmem -count 10' \
> 	BENCHTIMEOUT=24h \
> ```

This seems unnecessarily high. If it's reliably less than ~8 hours seems worth it to clamp it at 8h, so that we're notified the morning after a benchmark-breaking change lands instead of two mornings after.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15365#-:-KifYcczunSIKQ_k4Dub:bluhb3w)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/teamcity-benchmarks.sh, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15365#-KifYCM7-qzZa2wWkJL6:-KifZ83sD2l8ATBW7wXb:b6jkz68) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2522206f32678e523f644f59be392ef77b15ec7/build/teamcity-benchmarks.sh#L11)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This seems unnecessarily high. If it's reliably less than ~8 hours seems worth it to clamp it at 8h, so that we're notified the morning after a benchmark-breaking change lands instead of two mornings after.
</blockquote></details>

No idea how long they actually take, so let's ratchet this after we've seen it run once or twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15365)*

**Comment by benesch** [comment]
Actually, @tamird has pointed out that our current benchmark project in TeamCity has been broken for months, which means this is a strict improvement,so :lgtm:.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15365#-:-KifjTCXMdVmiv7hlCro:b-mcul1t)*

**Comment by tamird** [comment]
For posterity, immediately after merging this I intend to:
- unhook https://github.com/cockroachdb/cockroach-prod from teamcity
- disable [Upload Benchmark Data to S3](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_UploadAwsTest)
- open a PR to remove building of test binaries, which are no longer used.

**Pull request merged**
