### PR TITLE
sql: stale descriptor state could be observed in crdb_internal tables

### LINKED ISSUE #75825: builtins: `pg_get_constraintdef` broken during DROP CONSTRAINT in txn
This is a new failure introduced between 4d6d79d...7897f24, so my guess is 617d300 is the cause of the regression.

The following should not error:
```sql
BEGIN;
create table tbl (price int, quantity int);
alter table tbl add constraint quan_check check (quantity > 0);
alter table tbl add constraint pr_check check (price > 0);

SELECT conname, pg_get_constraintdef(c.oid) AS constraintdef, c.convalidated AS valid
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE c.contype = 'c'
              AND t.relname = 'tbl'; -- this query beforehand  is required to trigger the error; without it everything is fine
alter table tbl drop constraint quan_check;
SELECT conname, pg_get_constraintdef(c.oid) AS constraintdef, c.convalidated AS valid
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE c.contype = 'c'
              AND t.relname = 'tbl'; -- this fails
COMMIT;
```

example output:
```
root@127.0.0.1:26257/defaultdb> BEGIN;
create table tbl (price int, quantity int);
alter table tbl add constraint quan_check check (quantity > 0);
alter table tbl add constraint pr_check check (price > 0);

SELECT conname, pg_get_constraintdef(c.oid) AS constraintdef, c.convalidated AS valid
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE c.contype = 'c'
              AND t.relname = 'tbl'; 
alter table tbl drop constraint quan_check;
SELECT conname, pg_get_constraintdef(c.oid) AS constraintdef, c.convalidated AS valid
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE c.contype = 'c'
              AND t.relname = 'tbl';
COMMIT;
BEGIN


Time: 0ms total (execution 0ms / network 0ms)

CREATE TABLE


Time: 3ms total (execution 3ms / network 0ms)

ALTER TABLE


Time: 12ms total (execution 12ms / network 0ms)

ALTER TABLE


Time: 9ms total (execution 9ms / network 0ms)

   conname   |     constraintdef      | valid
-------------+------------------------+--------
  pr_check   | CHECK ((price > 0))    | true
  quan_check | CHECK ((quantity > 0)) | true
(2 rows)


Time: 11ms total (execution 11ms / network 0ms)

ALTER TABLE


Time: 2ms total (execution 2ms / network 0ms)

ERROR: pg_get_constraintdef(): unknown constraint (OID=1220880198)
SQLSTATE: 22023
ROLLBACK


Time: 2ms total (execution 1ms / network 2ms)
```

`pg_get_constraintdef`: https://github.com/cockroachdb/cockroach/blob/be1b6c4fd4778b784658459f77d28e6ed746c349/pkg/sql/sem/builtins/pg_builtins.go#L300-L319

Refs https://github.com/cockroachdb/cockroach/issues/68363#issuecomment-1027287913

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #75825

Previously, when an uncommitted descriptor was added
to a descriptor collection, we would not reset the cache of
all immutable descriptors (used by some crdb_internal functions).
This was inadequate because this could result in
incorrect results from crdb_internal tables which returned
information related to constraints, columns. To address this,
this patch will reset the descriptor cache for all
fetched descriptors when an uncommitted descriptor is
added into the collection.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/catalog/descs/collection.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76381#-MvZbu2jEGee9557uoAw:-MvZbu2jEGee9557uoAx:b-5f9n1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/587656c0b94fe505898cab4977fdc93e8b22a09a/pkg/sql/catalog/descs/collection.go#L212)):*
> ```Go
> 	// Invalidate all the cached descriptors since a stale copy of this may be
> 	// included.
> 	tc.kv.releaseAllDescriptors()
> ```

my sense is we should remove the code that calls this on the read path

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76381#-:-Mvb5ILU-KV8ebSImslQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Comment by fqazi** [comment]
@ajwerner TFTR!

**Comment by rafiss** [comment]
thanks for the fix! any chance for a 21.2 backport? i think it might be affecting https://github.com/cockroachdb/cockroach/issues/70008#issuecomment-1035987439 too

**Comment by rafiss** [comment]
blathers backport 21.2

**Pull request merged**
