### PR TITLE
colexec: add binary overloads on datum-backed types

### PR DESCRIPTION
**Pull request by yuzefovich**
**tree, colexec: preliminary steps for datum-backed binary overloads**

This commit does a few things that are preliminary to adding support of
binary operations on datum-backed vectors:
1. it exports `fn` field of `tree.BinaryExpr` - we will be using this
function to evaluate the binary operation on datum-backed vectors
2. it renames `decimalOverloadScratch` to `overloadHelper` and plumbs it
from the planning stage for projection and selection operators. This
struct will be used to supply the resolved `BinaryExpr.Fn` function (and
possibly other information) later
3. it cleans up `vectorize_types` logic test a bit since we now support
all types.

Release note: None

**colexec: add support for binary operations on datum-backed types**

This commit adds the support for 4 binary operations when at least one
of the arguments is datum-backed vector and the result is datum-backed
vector as well. We reuse the same function that row engine uses when
evaluating such expressions, and the function is plumbed during the
planning via `overloadHelper` struct. Native (i.e. not datum-backed)
arguments are converted to datums at runtime.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
I have to admit that a lot of the templating code is over my head and I didn't scrutinize it closely. I don't have much input other than that I'm worried that it's starting to get pretty complex but I'm not sure how to make that better.

> Reviewed 23 of 23 files at r1, 8 of 8 files at r2, 6 of 6 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-:-M8Gczp1D46Z7H1LVS6v:bynwcl5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8G_MWjArZRPYF7eoGQ:-M8G_MWjArZRPYF7eoGR:b9zbspm) ([raw file](https://github.com/cockroachdb/cockroach/blob/18c486e6c47be94b6089cb4c01d1bdc2d96cbfe1/pkg/col/coldataext/datum_vec.go#L57)):*
> ```Go
> 
> // BinFn evaluates the provided binary function between the receiver and other.
> // dVec is the datumVec that stores either d or other and is needed to supply
> ```

I'm having trouble wrapping my head around what `dVec is the datumVec that stores either d or other` means. Is it just saying that it's any datum vec but it doesn't matter because we just want to get the evalCtx?
___
*[pkg/sql/colexec/hash_utils_test.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYA8wBUYHgf_Dvh5X:-M8GYA8wBUYHgf_Dvh5Y:b-l1y43e) ([raw file](https://github.com/cockroachdb/cockroach/blob/245df166526780000efed145091009ef21191278/pkg/sql/colexec/hash_utils_test.go#L42)):*
> ```Go
> 	var (
> 		cancelChecker   CancelChecker
> 		_overloadHelper overloadHelper
> ```

I would prefer to name this something else rather than adding an `_`
___
*[pkg/sql/colexec/hash_utils_tmpl.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYHhhEW9a0CwzfviF:-M8GYHhi17Bd5r4wtbIT:buo9nmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/245df166526780000efed145091009ef21191278/pkg/sql/colexec/hash_utils_tmpl.go#L129)):*
> ```Go
> 	sel []int,
> 	cancelChecker CancelChecker,
> 	_overloadHelper overloadHelper,
> ```

Same here
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8Gcq5BCKukrmKwPZnN:-M8Gcq5BCKukrmKwPZnO:b-cqj5bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/79dc9d1e0e0befab7515d3dd9a5bd4166cc885a4/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L296)):*
> ```Go
> 				{{if .CheckRightIsZero}}
> 				if {{.Right}} == 0.0 {
> 					colexecerror.ExpectedError(tree.ErrDivByZero)
> ```

Should this be part of the previous commit?
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYq35539NWpew6bDO:-M8GYq369Y6l9rJMwzU0:b-rrhvek) ([raw file](https://github.com/cockroachdb/cockroach/blob/def9bb7b68edb50b388b9193f9214d4ae5306e62/pkg/sql/logictest/testdata/logic_test/vectorize_types#L83)):*
> ```
> 
> query IBB
> SELECT _id2, _bool, _bool2 FROM skip_unneeded_cols
> ```

It's still useful to have a test that skips unneeded columns, even if we could decode them, right? What changes here is that now, that column's type is supported. I'm not sure I would delete these tests.
___
*[pkg/sql/sem/tree/eval.go, line 1238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GcFJL-2Z-mZt4Y6rl:-M8GcFJM19rvkIIzbd31:btg5saw) ([raw file](https://github.com/cockroachdb/cockroach/blob/18c486e6c47be94b6089cb4c01d1bdc2d96cbfe1/pkg/sql/sem/tree/eval.go#L1238)):*
> ```Go
> 				dd.SetFinite(int64(MustBeDInt(left)), 0)
> 				cond, err := DecimalCtx.Quo(&dd.Decimal, &dd.Decimal, div)
> 				if cond.DivisionByZero() {
> ```

Was this not working as intended?

**Review by yuzefovich — COMMENTED** [review]
I agree about the complexity, but these new customizers are similar to what we already have, so in a sense this PR doesn't bring any "new complexity", it only slightly "expands the old one".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-:-M8IOd4I74NeA_7WX7Rp:bm1rx7a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/col/coldataext/datum_vec.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8G_MWjArZRPYF7eoGQ:-M8I6qQW37v_mJdW9bjT:bagrgmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/18c486e6c47be94b6089cb4c01d1bdc2d96cbfe1/pkg/col/coldataext/datum_vec.go#L57)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm having trouble wrapping my head around what `dVec is the datumVec that stores either d or other` means. Is it just saying that it's any datum vec but it doesn't matter because we just want to get the evalCtx?
</blockquote></details>

Yes, exactly. In some cases we have a constant on the left, so `d` is created at runtime `coldataext.Datum` based on that constant and it is not stored in `datumVec`, but we have `other` which is a `coldataext.Datum` coming from the `datumVec`. I reworded the comment to make this less confusing.
___
*[pkg/sql/colexec/hash_utils_test.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYA8wBUYHgf_Dvh5X:-M8IN7BqC5zWGrDrFDrp:b-4sxlly) ([raw file](https://github.com/cockroachdb/cockroach/blob/245df166526780000efed145091009ef21191278/pkg/sql/colexec/hash_utils_test.go#L42)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would prefer to name this something else rather than adding an `_`
</blockquote></details>

Can you provide a better naming suggestion? To me this seems reasonable because a variable of `overloadHelper` type needs to be in scope of templated functions, so adding `_` as the prefix follows some of our conventions in that code. 

If your comment was more about the function argument names, I removed the underscore in a couple of such places.
___
*[pkg/sql/colexec/hash_utils_tmpl.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYHhhEW9a0CwzfviF:-M8IOXwSCHd0EO6fcHGA:b-wi0ruo) ([raw file](https://github.com/cockroachdb/cockroach/blob/245df166526780000efed145091009ef21191278/pkg/sql/colexec/hash_utils_tmpl.go#L129)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Removed the underscore.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8Gcq5BCKukrmKwPZnN:-M8I9e2i9yk4puHKJ-AT:bm7h7la) ([raw file](https://github.com/cockroachdb/cockroach/blob/79dc9d1e0e0befab7515d3dd9a5bd4166cc885a4/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L296)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should this be part of the previous commit?
</blockquote></details>

Yes, it should. I was being lazy, updated.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYq35539NWpew6bDO:-M8ILArv5fHKpFM4eDBM:b-ps2142) ([raw file](https://github.com/cockroachdb/cockroach/blob/def9bb7b68edb50b388b9193f9214d4ae5306e62/pkg/sql/logictest/testdata/logic_test/vectorize_types#L83)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's still useful to have a test that skips unneeded columns, even if we could decode them, right? What changes here is that now, that column's type is supported. I'm not sure I would delete these tests.
</blockquote></details>

Hm, I don't see a value in having these tests, can you expand on why you still find them useful? The original goal of them was to make sure that `cFetcher` was able to successfully skip over unneeded columns and put `unknown` vector in there, but now that custom logic is gone, and I believe these tests should have been removed in the datum-vec PR. If we want to exercise whether a table reader (either `rowexec.tableReader` or `colexec.cFetcher`) can read only needed columns, I'd argue that should be in a separate logic test file, without `vectorize_` prefix.
___
*[pkg/sql/sem/tree/eval.go, line 1238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GcFJL-2Z-mZt4Y6rl:-M8IMSVkCa93u79bZB47:b-3il890) ([raw file](https://github.com/cockroachdb/cockroach/blob/18c486e6c47be94b6089cb4c01d1bdc2d96cbfe1/pkg/sql/sem/tree/eval.go#L1238)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Was this not working as intended?
</blockquote></details>

In this particular case, I think it was working as intended.

However, I tried using the same approach for floor division and modulus, and in those cases performing a decimal operation and then checking `cond` variable for div-by-zero condition didn't work (or I was using the wrong method). So I thought I might as well do the zero check in all code paths in the same manner because to me it makes more sense to do so rather than performing the division or whatnot, and checking the condition afterwards.

**Review by asubiotto — APPROVED** [review]
:lgtm: but it might be nice to get @jordanlewis' input as well

> Reviewed 16 of 17 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-:-M8LQAkJBczDGTKjTQcA:boyl04w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/hash_utils_test.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYA8wBUYHgf_Dvh5X:-M8LQJiO9KrL3bH1BBEE:b-fm533s) ([raw file](https://github.com/cockroachdb/cockroach/blob/245df166526780000efed145091009ef21191278/pkg/sql/colexec/hash_utils_test.go#L42)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Can you provide a better naming suggestion? To me this seems reasonable because a variable of `overloadHelper` type needs to be in scope of templated functions, so adding `_` as the prefix follows some of our conventions in that code. 

If your comment was more about the function argument names, I removed the underscore in a couple of such places.
</blockquote></details>

I guess it's fine, but in general want to avoid using underscores for variables in go code mostly due to conventions
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYq35539NWpew6bDO:-M8LQuhc91bPlY4DkO71:b-d8f1kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/def9bb7b68edb50b388b9193f9214d4ae5306e62/pkg/sql/logictest/testdata/logic_test/vectorize_types#L83)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I don't see a value in having these tests, can you expand on why you still find them useful? The original goal of them was to make sure that `cFetcher` was able to successfully skip over unneeded columns and put `unknown` vector in there, but now that custom logic is gone, and I believe these tests should have been removed in the datum-vec PR. If we want to exercise whether a table reader (either `rowexec.tableReader` or `colexec.cFetcher`) can read only needed columns, I'd argue that should be in a separate logic test file, without `vectorize_` prefix.
</blockquote></details>

Yes, the use I see is having tests that test that the `cFetcher` skips over unneeded columns properly, regardless of whether the type is supported or not (before we were testing both this **and** that an `unknown` vector was used). Do tests like this exist elsewhere?

**Review by yuzefovich — COMMENTED** [review]
Ok, I'll let this PR to hang for a bit so that @jordanlewis could have a chance to take a look at it if he wants.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-:-M8ReRms-tkG8TiYb7dZ:bt7sh5y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/hash_utils_test.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYA8wBUYHgf_Dvh5X:-M8RdKT31g2NQ4jL298v:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/245df166526780000efed145091009ef21191278/pkg/sql/colexec/hash_utils_test.go#L42)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I guess it's fine, but in general want to avoid using underscores for variables in go code mostly due to conventions
</blockquote></details>

Ack.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_types, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8GYq35539NWpew6bDO:-M8RdMoZAFrvXYr0IeU7:b-clv99n) ([raw file](https://github.com/cockroachdb/cockroach/blob/def9bb7b68edb50b388b9193f9214d4ae5306e62/pkg/sql/logictest/testdata/logic_test/vectorize_types#L83)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yes, the use I see is having tests that test that the `cFetcher` skips over unneeded columns properly, regardless of whether the type is supported or not (before we were testing both this **and** that an `unknown` vector was used). Do tests like this exist elsewhere?
</blockquote></details>

I disagree - we were testing that `cFetcher` skips over unneeded columns with these logic tests **only** because we had `unknown` vector placeholders which would panic if accessed (which would mean that `cFetcher` doesn't skip the unneeded columns). Now we will always create valid vectors in the batch of `cFetcher`, so if unneeded columns are accessed, there will be no panic, and the logic tests won't fail.

I think logic tests are now the wrong framework to test the skipping behavior of `cFetcher` - it should be done in a unit test.

**Review by jordanlewis — COMMENTED** [review]
Can you separate this PR into 2 pieces? The second 2 commits don't belong here and it's making it harder to review. I have some comments on the first 2 commits but I'm finding it quite hard to understand as well.

> Reviewed 16 of 23 files at r1, 17 of 17 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-:-M8WAVfj48tLnc2GxcQ1:bfglc4n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/hash_utils_tmpl.go, line 134 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8TP2GX0I4GADlMI_xw:-M8TP2GX0I4GADlMI_xx:b-462tvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/002368d787f6edc7af889f6ca130a51e4da69f24/pkg/sql/colexec/hash_utils_tmpl.go#L134)):*
> ```Go
> 	// In order to inline the templated code of overloads, we need to have a
> 	// "_overloadHelper" local variable of type "overloadHelper".
> 	_overloadHelper := overloadHelper
> ```

We're starting to get into a hard to understand zone with this. The idea with making the "template functions" everywhere was that we would be able to pass in variables to them, to make it clear to the code reader where a particular variable is used. What needs _overloadHelper in this block? Is it _REHASH_BODY? Should _REHASH_BODY therefore be modified to take this as a parameter?

**Review by yuzefovich — COMMENTED** [review]
Removed the last 2 commits and will open a new PR once this goes in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-:-M8WQmdgDuivAT9M5eLF:b-t5p5x4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/hash_utils_tmpl.go, line 134 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49419#-M8TP2GX0I4GADlMI_xw:-M8WR1WtCrXWxgGEZE92:b-f2ghyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/002368d787f6edc7af889f6ca130a51e4da69f24/pkg/sql/colexec/hash_utils_tmpl.go#L134)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We're starting to get into a hard to understand zone with this. The idea with making the "template functions" everywhere was that we would be able to pass in variables to them, to make it clear to the code reader where a particular variable is used. What needs _overloadHelper in this block? Is it _REHASH_BODY? Should _REHASH_BODY therefore be modified to take this as a parameter?
</blockquote></details>

`_overloadHelper` is needed by datum-vec implementation of `_ASSIGN_HASH` which is templated inside of `_REHASH_BODY`.

I agree that it is not obvious without opening IDE and stepping through the code, but I also don't see a good way to handle such variables better without the refactoring of `execgen` as we were discussing. The difficulty is that we have two kinds of function arguments: "meta" templated parameters  which are used by `execgen` to generate the appropriate code, and "local variables" that are in scope of the templated code. The former should always be listed in the templated "function signature" and we have done a good job with this, but the latter are often omitted from the signature. In fact, I've been slowly removing such arguments because they clutter the signatures without providing any more clarity (IMO). This `_overloadHelper` is an example of the latter.

**Comment by jordanlewis** [comment]
Ideally, each template function call would have 2 kinds of arguments: template arguments (the former) and runtime arguments (the latter). Both should be listed. The former should be visually distinguishable from the latter. But I agree that we need to do a refactor to improve the situation and adding this isn't making things that much worse...

**Review by jordanlewis — APPROVED** [review]
Let's merge this, I don't really have more substantive comments :)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
