### PR TITLE
geo/geos: add ClipWKBByRect to clip a geometry by the rectangle

### PR DESCRIPTION
**Pull request by sumeerbhola**
constraints of the index

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geos/geos_unix.cc, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4D3PYY6Z_uid_7RL23:-M4D3PYY6Z_uid_7RL24:bg4xbgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb378d81654d32921b04344c31e3fe2e5446f7b/pkg/geo/geos/geos_unix.cc#L161)):*
> ```cpp
> }
> 
> // TODO(sumeer): return error.
> ```

hmm, what's the error?
___
*[pkg/geo/geos/geos_unix.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4D0nWr3b5xDZNErvsg:-M4D0nWr3b5xDZNErvsh:by79flt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb378d81654d32921b04344c31e3fe2e5446f7b/pkg/geo/geos/geos_unix.go#L158)):*
> ```Go
> 	unsafeWKB := cSliceToUnsafeGoBytes(cWKB)
> 	clippedWKB := make([]byte, len(unsafeWKB))
> 	copy(clippedWKB, unsafeWKB)
> ```

hmm, any reason we don't provide a `cSliceToSafeGoBytes` where we copy the bytes?
seems like we'll need to do this multiple times.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-:-M4EJWIL9Sonpkleffh5:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geos/geos_unix.cc, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4D3PYY6Z_uid_7RL23:-M4E95mg2D6GBG_MaZrf:bxe81fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb378d81654d32921b04344c31e3fe2e5446f7b/pkg/geo/geos/geos_unix.cc#L161)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm, what's the error?
</blockquote></details>

The reader interfaces don't return an error if the input is not valid. My understanding is that the `handle` is being passed the error, based on reading https://sourcegraph.com/github.com/libgeos/geos/-/blob/capi/geos_ts_c.cpp#L2459 which seems to call this `execute()` https://sourcegraph.com/github.com/libgeos/geos@312c085bdc9606896281c7d0610c1a1b3931e014/-/blob/capi/geos_ts_c.cpp#L365
which calls a `GEOSMessageHandler` `https://sourcegraph.com/github.com/libgeos/geos/-/blob/capi/geos_ts_c.cpp#L259`.
I think we could set the message handler, and return the error in a `CR_GEOS_Slice`.

I haven't actually tried the above to verify that geos is using c++ exceptions for error handling, but returning `nullptr` seems highly insufficient ,so would be surprising if that is all they have.
___
*[pkg/geo/geos/geos_unix.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4D0nWr3b5xDZNErvsg:-M4EDyAkEbXwwILITaoh:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb378d81654d32921b04344c31e3fe2e5446f7b/pkg/geo/geos/geos_unix.go#L158)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm, any reason we don't provide a `cSliceToSafeGoBytes` where we copy the bytes?
seems like we'll need to do this multiple times.
</blockquote></details>

Done

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geos/geos_unix.cc, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4D3PYY6Z_uid_7RL23:-M4F9BWz8gxTLeM8sFaY:bfyf6m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb378d81654d32921b04344c31e3fe2e5446f7b/pkg/geo/geos/geos_unix.cc#L161)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The reader interfaces don't return an error if the input is not valid. My understanding is that the `handle` is being passed the error, based on reading https://sourcegraph.com/github.com/libgeos/geos/-/blob/capi/geos_ts_c.cpp#L2459 which seems to call this `execute()` https://sourcegraph.com/github.com/libgeos/geos@312c085bdc9606896281c7d0610c1a1b3931e014/-/blob/capi/geos_ts_c.cpp#L365
which calls a `GEOSMessageHandler` `https://sourcegraph.com/github.com/libgeos/geos/-/blob/capi/geos_ts_c.cpp#L259`.
I think we could set the message handler, and return the error in a `CR_GEOS_Slice`.

I haven't actually tried the above to verify that geos is using c++ exceptions for error handling, but returning `nullptr` seems highly insufficient ,so would be surprising if that is all they have.
</blockquote></details>

can you expand that in the comment?
otherwise, except for the lint error, this LGTM!

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geos/geos_unix.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4F9Wlh9dacQ3OlhA70:-M4F9Wlh9dacQ3OlhA71:bjvn9ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdfd6d6661fd2d8c59315031ad552d6fad7a9d75/pkg/geo/geos/geos_unix.go#L126)):*
> ```Go
> 
> // Additionally, this frees the memory in the C slice.
> func cSliceToSafeGoBytes(s C.CR_GEOS_Slice) []byte {
> ```

nit: hmm, maybe follow the form of "cSliceToSafeGoBytes... " as well

**Review by sumeerbhola — COMMENTED** [review]
I've added a trivial test, which should also fix the lint failure.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-:-M4FbqAn5O2c9Lq-NfS1:boife9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geos/geos_unix.cc, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4D3PYY6Z_uid_7RL23:-M4FOHki9A7Hub1w0HcP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb378d81654d32921b04344c31e3fe2e5446f7b/pkg/geo/geos/geos_unix.cc#L161)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you expand that in the comment?
otherwise, except for the lint error, this LGTM!
</blockquote></details>

Done.
___
*[pkg/geo/geos/geos_unix.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47061#-M4F9Wlh9dacQ3OlhA70:-M4FQqp-4pOWxc5aVcXk:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdfd6d6661fd2d8c59315031ad552d6fad7a9d75/pkg/geo/geos/geos_unix.go#L126)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: hmm, maybe follow the form of "cSliceToSafeGoBytes... " as well
</blockquote></details>

Done

**Comment by sumeerbhola** [comment]
CI failure is unrelated, in TestLogic/fakedist-vec/vectorize_types

**Pull request merged**
