### PR TITLE
sql: normalize age and timestamptz intervals like postgres

### PR DESCRIPTION
**Pull request by otan**
sql: normalize age and timestamptz intervals like postgres

Release note (sql change, bug fix): Previously, `timestamp/timestamptz -
timestamp/timestamptz` operators would normalize the interval into
months, days, H:M:S (in older versions, this may be just H:M:S).

This could result in an incorrect result:
```
> select '2020-01-01'::timestamptz - '2018-01-01';
     ?column?
-------------------
  2 years 10 days
```
This has now been fixed such that it is only normalized into
days/H:M:S. This is now more postgres compatible.

Release note (sql change, bug fix): Previously, the `age` builtin would
incorrectly normalize months and days based on 30 days a month (in older
versions this may be just H:M:S).

This can give an incorrect result, e.g.
```
> select age('2020-01-01'::timestamptz, '2018-01-01');
     ?column?
-------------------
  2 years 10 days
```

This is not the most accurate it could be as `age` can use the given
timestamptz arguments to be more accurate.
This is now more postgres compatible.

Revert "sql: age returns normalized intervals"

This reverts commit 88a5d9468e8f1dbc7f59006efb2aec38afda3583.

Release note: None

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
I think our release note needs to call out that the previous behavior could produce incorrect results for timestamp subtraction. For instance like this:
```
> select '2020-01-01'::timestamptz - '2018-01-01';
     ?column?
-------------------
  2 years 10 days
```
It seems hard to spin that as just a "sql change" and not a bug fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56667#-:-MM2LKcP0JRnrM2L45h8:b-ud3eq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/timestamp, line 487 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56667#-MM2MR85DBqlcx8dvPSw:-MM2MR85DBqlcx8dvPSx:b-wr6bw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f089923a8fc969006f231120d08983cad0225bd/pkg/sql/logictest/testdata/logic_test/timestamp#L487)):*
> ```
> 29 days 05:43:04                  -29 days -05:43:04                    29 days 05:43:04    -29 days -05:43:04    29 days 05:43:04    -29 days -05:43:04
> -1 mons -1 days -17:16:56         1 mon 1 day 17:16:56                  -29 days -17:16:56  29 days 17:16:56      -29 days -18:16:56  29 days 18:16:56
> -18:16:56                         18:16:56                              -18:16:56           18:16:56              -18:16:56           18:16:56
> ```

@jordanlewis also proposed having a randomized test which asserts that adding and subtracting the same interval from a timestamp results in the same timestamp. Do you think that would also be valuable here or is this logic test sufficient? Though now that I'm saying this I'm remembering there might be counterexamples of this invariant in Postgres?
___
*[pkg/sql/sem/builtins/builtins.go, line 2116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56667#-MM2KIq_3ccJKqg1LGZg:-MM2KIq_3ccJKqg1LGZh:b-w4uan1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f089923a8fc969006f231120d08983cad0225bd/pkg/sql/sem/builtins/builtins.go#L2116)):*
> ```Go
> 			Info: "Calculates the interval between `val` and the current time, normalized into years, months and days." + `
> 
> 			Note this may not be an accurate time span since years and months are normalized from days, and years and months are out of context. Use ` + "`timestamptz - now()`" + ` for day rounding which maintains this accuracy.`,
> ```

Did you mean `now() - timestamptz`? Also "rounding" seems like a confusing term here.

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/timestamp, line 487 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56667#-MM2MR85DBqlcx8dvPSw:-MM2VtCc1AdNnfQAptjC:b-ydlya7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f089923a8fc969006f231120d08983cad0225bd/pkg/sql/logictest/testdata/logic_test/timestamp#L487)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

@jordanlewis also proposed having a randomized test which asserts that adding and subtracting the same interval from a timestamp results in the same timestamp. Do you think that would also be valuable here or is this logic test sufficient? Though now that I'm saying this I'm remembering there might be counterexamples of this invariant in Postgres?
</blockquote></details>

This does not work for `age`. The other randomized tests testing invariants may be useful (smells like metamorphic tests), I think it's worth filing a separate issue such we that we have those. Sounds like we can generalise these kinds of invariants.

**Review by solongordon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56667)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @otan)

___
*[pkg/util/duration/duration.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56667#-MMGANQPCv0BhT8iwz8i:-MMGANQPCv0BhT8iwz8j:b-9iq12s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d3c6832d9e978053920982f83bc9e83ca2bf46/pkg/util/duration/duration.go#L166)):*
> ```Go
> 	// to be too large from the math above anyway.
> 	for nanos < 0 {
> 		nanos += int64(time.Nanosecond)
> ```

It looks like this should be nanos per second, not `int64(time.Nanosecond)` which is `1`. Could you update this and include nanoseconds in your test cases?

**Comment by otan** [comment]
___
*[pkg/util/duration/duration.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56667#-MMGANQPCv0BhT8iwz8i:-MMHHk35EtEjB2y0hwsN:bx582q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d3c6832d9e978053920982f83bc9e83ca2bf46/pkg/util/duration/duration.go#L166)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It looks like this should be nanos per second, not `int64(time.Nanosecond)` which is `1`. Could you update this and include nanoseconds in your test cases?
</blockquote></details>

ah the one case i wish i had go coverage tools.
nice catch, cheers!
fixed.

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56667)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by otan** [comment]
bors r=solongordon

thanks!

**Pull request merged**
