### PR TITLE
storage: misc cleanup

### PR DESCRIPTION
**Pull request by tamird**
Addressing my own comments.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7844)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm: but see the `replicate_queue.go` comment

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/helpers_test.go, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf3zerLqDmG7OT38Q2:-KMf3zerLqDmG7OT38Q3:-95445601) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/helpers_test.go#L114)):*
> ```Go
> }
> 
> // SetRaftLogQueueActive enables or disables the raft log queue.
> ```

-1 on this. You're not gaining anything with this duplication. The (now-private) methods are test-only anyway.

---

*[storage/queue.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf5O3s5ER_UdpyzzaF:-KMf5O3s5ER_UdpyzzaG:1230422959) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/queue.go#L309)):*
> ```Go
> }
> 
> func (bq *baseQueue) requiresSplit(cfg config.SystemConfig, repl *Replica) bool {
> ```

please add a method comment

---

*[storage/queue.go, line 315 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf6MnvselnmO9ZFR6e:-KMf6MnvselnmO9ZFR6f:-918242029) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/storage/queue.go#L315)):*
> ```Go
> // splittingDisabledForTest returns true if a store's split queue has been
> // disabled. This only happens in tests.
> func splittingDisabledForTest(store *Store) bool {
> ```

I pretty ambivalent about this change. The previous version had a `ForTest` suffix, which was good. There was some code duplication, but now you have to read `requiresSplit` to see what it does; the semantics cannot be captured in the name well.
If you keep it, consider `shouldDeferProcessingAfterSplit()`. Also consider keeping just `!bq.acceptsUnsplitRanges && cfg.NeedsSplit(desc.StartKey, desc.EndKey)` in the new method, and also separately calling `splittingDisabledForTest()` everywhere.

---

*[storage/replicate_queue.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf4w1mmXc75ALGV5vK:-KMf4w1mmXc75ALGV5vL:-789235249) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/replicate_queue.go#L81)):*
> ```Go
> func (rq *replicateQueue) shouldQueue(now hlc.Timestamp, repl *Replica,
> 	sysCfg config.SystemConfig) (shouldQ bool, priority float64) {
> 	if repl.needsSplitBySize() {
> ```

I think testing if splitting is enabled is valid, no? If replication is enabled, but splitting is not, you want the replication to happen regardless of size.

---

*[storage/store.go, line 2639 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf4f5kdQ_B7HNb7-E3:-KMf4f5l4ZwMgBbCYpk4:2013196062) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/storage/store.go#L2639)):*
> ```Go
> }
> 
> // The methods below can be used to control a store's queues. Stopping a queue
> ```

this comment is still valid, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-:-KMf8RB3WoLvwazfA0na:-1988755058)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/helpers_test.go, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf3zerLqDmG7OT38Q2:-KMfPSQ56j26jPiKMj2s:1659647460) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/helpers_test.go#L114)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> -1 on this. You're not gaining anything with this duplication. The (now-private) methods are test-only anyway.
</details>
I'm not following. This isn't duplication, since these methods do not duplicate the logic.

The private methods are test-only, but now it's not possible to publicly call these methods from non-test code.

---

*[storage/queue.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf5O3s5ER_UdpyzzaF:-KMfPkzzeTEbAECy-HEb:-997833353) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/queue.go#L309)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> please add a method comment
</details>
Really? The name isn't descriptive?

---

*[storage/queue.go, line 315 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf6MnvselnmO9ZFR6e:-KMfPrGW8wRi-LSIqzS8:2110768006) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/storage/queue.go#L315)):*
Why is any of that better?

> The previous version had a `ForTest` suffix

Who's that helping? It's better not to have such a method at all.

>  now you have to read `requiresSplit` to see what it does; the semantics cannot be captured in the name well.

Can't they? This method literally returns true if the queue requires a split to proceed.

---

*[storage/replicate_queue.go, line 81 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf4w1mmXc75ALGV5vK:-KMgffCTf1MArvtbynCu:1819003988) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/replicate_queue.go#L81)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I think testing if splitting is enabled is valid, no? If replication is enabled, but splitting is not, you want the replication to happen regardless of size.
</details>
Agreed. Restored and commented.

---

*[storage/store.go, line 2639 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf4f5kdQ_B7HNb7-E3:-KMgeqwk28lxun3zwaSw:181201435) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/storage/store.go#L2639)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> this comment is still valid, no?
</details>
Hm, good point. Restored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844)*

**Comment by andreimatei** [comment]
still LGTM, don't need to answer if you don't want

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/helpers_test.go, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf3zerLqDmG7OT38Q2:-KMj-y8U2cEQt1Sk71BH:-1149370747) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/helpers_test.go#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not following. This isn't duplication, since these methods do not duplicate the logic.
> 
> The private methods are test-only, but now it's not possible to publicly call these methods from non-test code.
</details>
Those methods should not ever be called from non-test code. So it shouldn't matter if they're exported or not. The benefit you're gaining by making them non-public (i.e. the fact that non-test code in other packages is gonna be less incentivized to start using them) is close to nothing.

The downsides are:

a) now tests in other packages (other than storage and storage_test) can't use them
b) if somebody needs them in any test, what are the chances they'll look in _helpers to see if there happens to be an exported version of them?
c) more code

---

*[storage/queue.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf5O3s5ER_UdpyzzaF:-KMj2uJ5P5008xihhNwZ:779043728) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/queue.go#L309)):*
> helping

---

*[storage/queue.go, line 315 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf6MnvselnmO9ZFR6e:-KMj1_tZu06nD5dtdgGV:1755611480) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/storage/queue.go#L315)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Why is any of that better?
> 
> > The previous version had a `ForTest` suffix
> 
> Who's that helping? It's better not to have such a method at all.
> 
> >  now you have to read `requiresSplit` to see what it does; the semantics cannot be captured in the name well.
> 
> Can't they? This method literally returns true if the queue requires a split to proceed.
</details>
The `ForTest` suffix was good because... it told you that there's testing sketchiness going on. Now not even the comment tells you that in relation to splitting being stopped.

If the config says the range should be split, but the splitting queue is stopped, does this queue "require" a split? I dunno... Have to read the function to see.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-:-KMj1ziFJCreZ9_v0em1:961003890)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/helpers_test.go, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf3zerLqDmG7OT38Q2:-KMjAY-_bCtdJ_jeiYUH:-53450629) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/helpers_test.go#L114)):*
> a) now tests in other packages (other than storage and storage_test) can't use them

This is an upside, not a downside.

> b) if somebody needs them in any test, what are the chances they'll look in _helpers to see if there happens to be an exported version of them?

We already made that trade when we introduced that file.

> c) more code

Meh, there's no duplication here, it won't rot.

---

*[storage/queue.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf5O3s5ER_UdpyzzaF:-KMjADsocarqPUBcZQDb:166874) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/queue.go#L309)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> > helping
</details>
?

---

*[storage/queue.go, line 315 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf6MnvselnmO9ZFR6e:-KMjHv9-yCAo_jnIe9Dx:-1064016711) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/storage/queue.go#L315)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> The `ForTest` suffix was good because... it told you that there's testing sketchiness going on. Now not even the comment tells you that in relation to splitting being stopped.
> 
> If the config says the range should be split, but the splitting queue is stopped, does this queue "require" a split? I dunno... Have to read the function to see.
</details>
The argument that you have to read the method is pretty thin - the same is true of the queue's `acceptsUnsplitRanges` property, and for that you have to go to a different file!

Unfortunately `ForTest` is also one of those things that amounts to FUD. 
Imagine: you're investigating a crash and end up here, but nothing looks suspicious; you didn't read the method body, right? after all, it's named `ForTest`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844)*

**Comment by andreimatei** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/helpers_test.go, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf3zerLqDmG7OT38Q2:-KMjMx7oyGVJ1IEA65Ol:771078223) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/helpers_test.go#L114)):*
> This is an upside, not a downside.
Well, what do you think is gonna happen the first time a test outside of storage *does* need to start/stop the queues?

> We already made that trade when we introduced that file.
I'm in general not a big fan of these helpers_test files, but I think this is an example of something particularly unlikely to be looked for there - an exported accessor for a method that already exists elsewhere (as opposed to methods that don't exist elsewhere). I think a better pattern would be  `TestAccess` struct inside the `Store` struct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/helpers_test.go, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844#-KMf3zerLqDmG7OT38Q2:-KMjunjPYygAb0lNzzEE:745772417) ([raw file](https://github.com/cockroachdb/cockroach/blob/418b074928d62a80ffa5bdb5ed88b21b89fe07b7/storage/helpers_test.go#L114)):*
> Well, what do you think is gonna happen the first time a test outside of storage does need to start/stop the queues?

They'll have to make this stuff accessible, and hopefully there will be some scrutiny of that.

> I think a better pattern would be `TestAccess` struct inside the `Store` struct.

I think TestAccess is basically equivalent to making things public.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7844)*

**Pull request merged**
