### PR TITLE
ui: update Jobs Details page

### LINKED ISSUE #83949: Improve layout and labeling in Job Details page
The Creation time and Users labels are too small and should be above the value.

The values should be smaller and not bold.

Users should be User to match the Jobs page or User Name. See https://github.com/cockroachdb/cockroach/issues/83872

ui_jobs_page_details

FYI @Annebirzin 

Jira issue: CRDB-17365

### PR DESCRIPTION
**Pull request by maryliag**
Update Jobs Details page to most recent design,
aligning with the format from Statement Details page.
New information added for Last Execution Time, Next
Execution Time and Execution Count.

Fixes #83949

Before
Screen Shot 2022-07-15 at 12 21 44 PM

After
Screen Shot 2022-07-15 at 2 02 34 PM

Release note (ui change): Update Jobs Details page to new design
and add information about Last Execution Time, Next Execution
Time and Execution Count.

### CODE REVIEW

**Review by ericharmeling — APPROVED** [review]
This looks so much better! Just had a minor suggestion

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84498#-:-N72UO1r2onP0HHf6z15:bpx7w6o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84498#-N72UYZPEoiku6sLsCFM:-N72UYZPEoiku6sLsCFN:bm8xsgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cf6823a550b5ce148bbd95a8f57d3a8c3577f68/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L92)):*
> ```XML
>               <JobStatusCell job={job} lineWidth={1.5} hideDuration={true} />
>               <h3 className={jobCx("summary--card--title", "secondary")}>
>                 Next Execution Time:
> ```

nit: Should we label this "Next Planned Execution Time"?



_Suggestion:_
```XML
Next Planned Execution Time:
```

**Review by maryliag — COMMENTED** [review]
Thank you! :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84498#-:-N72f3qrC3m81XIwn0Ck:b87vtke)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84498#-N72UYZPEoiku6sLsCFM:-N72f1NkBX8QUbxfLCqk:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cf6823a550b5ce148bbd95a8f57d3a8c3577f68/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L92)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: Should we label this "Next Planned Execution Time"?
</blockquote></details>

Done!

**Review by ericharmeling — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

**Pull request merged**
