### PR TITLE
security/password: trim down dependencies further

### PR DESCRIPTION
**Pull request by knz**
This removes many more indirect dependencies by not requiring
quotapool and util/log.

Release note: None

### CODE REVIEW

**Review by ZhouXing19 — COMMENTED** [review]
:lgtm_strong: Thanks for making this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80760#-:-N0mYww00Ftar8wEllKv:b-fbzkrj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @ZhouXing19)

___
*[`pkg/security/password.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80760#-N0mYpkaB0YiRg1010rB:-N0mYpkaB0YiRg1010rC:b-xfnl82) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b3d6a17539297505b28fa2ffe1c0957f5cd558/pkg/security/password.go#L220)):*
> ```Go
> 			return nil, err
> 		}
> 		return alloc.Release, err
> ```

nit: should return `alloc.Release, nil`

**Comment by ZhouXing19** [comment]
*[`pkg/security/password.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80760#-N0mYpkaB0YiRg1010rB:-N0md1Il8k-bQI5c_X30:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b3d6a17539297505b28fa2ffe1c0957f5cd558/pkg/security/password.go#L220)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: should return `alloc.Release, nil`
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
In https://github.com/cockroachdb/cockroach/pull/80687 I pull `username` out of `security`. I think even with this, it'd be a fine thing to do. Thoughts?

**Comment by ZhouXing19** [comment]
> I think even with this, it'd be a fine thing to do.

Yes I agree, and seems to me that the two PRs do not conflict.

**Pull request merged**
