### PR TITLE
colexec: add number of rows read by ColBatchScan

### LINKED ISSUE #49609: explain analyze not showing rows read from computed column full table scan
I have a table that includes the following columns: id and JSON
I create a computed column from the JSON column called Serial_Number and cast it as an INT.
I query on the new column for Serials between 10,500 and 11,000
```
select id, serial_number from vehicles where serial_number <= 11000 and serial_number
> 10500;
```
When I use explain on this query it notes a full table scan:
```
 tree |    field    |                     description
+------+-------------+------------------------------------------------------+
       | distributed | true
       | vectorized  | true
  scan |             |
       | table       | vehicles@primary
       | spans       | FULL SCAN
       | filter      | (serial_number <= 11000) AND (serial_number > 10500)
(6 rows)
```
When I use explain analyze on this query I get the following output, image attached.
It's not clear from the explain-analyze that a full table scan is happening. 
Screen Shot 2020-05-26 at 3 25 04 PM
It does say "Spans" which apparently infers a full table scan, but there's no clear full row count.

### LINKED ISSUE #49760: sql: vectorized EXPLAIN ANALYZE diagram should show number of table rows read
The EXPLAIN ANALYZE diagram shows the number of rows output by every processor. But if we have a TableReader with a filter, there is no way of knowing how many rows we actually had to read before filtering. We should include that information.

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds the information about the number of rows read by
`ColBatchScan` to EXPLAIN ANALYZE diagrams. Wrapped `joinReader` and
`tableReader` processors were already populating that information, so no
action was required for them (other than implementing the common
interface). Additionally, this commit fixes the display of `bytes read`
for wrapped processors (it was broken during the refactor of the commit
that added that recently).

Fixes: #49609.
Closes: #49760

Release justification: low risk, high benefit change.

Release note (sql change): EXPLAIN ANALYZE diagrams now contain the
information about the number of rows read by the vectorized table
reader.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Here are the links for TPCH Q17 with vectorize [off](https://cockroachdb.github.io/distsqlplan/decode.html#eJyclV9v2zYUxd_3KS7uHioXnKL_UggUkLI4XTZH7mx3a7cZhmJdGFr0rxS1xQjy3QfZjmNlCVvHTyQvj3h_h8fSHTZfcuQ4_PRhFF3GEMXR6PMfQ9DOL6ez6a-jAUyHo-GPM2jaQssXdCupTCmtRbakAZyArxsQTSH5Z7VYUyLyNVxMxleQZyVlkgoGdSIk_P7TcDIETdPqRTe_oTW8g_xhPIAoPgetXlyLpEzhHbw56wbfW_abwb62rEqZZCWJrn41PIez8ad9OV98aZNSZnINf7WGYS9B27Vt6Ba87do72DPo97jrLj9obd_mYIAMyyqlOCmoQf4nmjhnWItqSU1TiW7pbrPhMr1FbjDMyrqV3fKc4bIShPwOZSZzQo6z5DqnCSUpiRMDGaYkkyzfPLY7L6xFViRijQyndVI2HH5AhhdZLklw0EKnZw3nfDqbXMbvdx6E_qEzj1VkOG4lh9BkocNCHxmK6t8GBCUpB8vofsiwkUmeg8wK4mAGvm7ap0WDDK_XkvabA7jKznB-z7Bq5SNnI5MVITfv2bd78XOVlTsrzL4VD_cS5ov6BhmOquqmreHvKiuhKjuQQySLhfYGzH2GzXkCZrmufnpqbsCyMqVbONjuGUGwX-_Z4euB5RTNi-DWK8GtF8Afc_A_doeF3iG-afaZdxA96MDQDcc_EtqyA912fQW1fQx1tFoJWiWyEid2n3p7nSIlQenucqP48yIezxbxx9FIC80uwtFv77XQ6kaT7gUkOITWW0O3OOcXo3E0C9hWqrbCdTzdsb2NFUVyCwUVlVhD23RHOwb8oki388pLdo5Mt_Vsur2vRdt1At1z7WOjbeh-oIq2-0pq9_ho2yzsVOMYQtN4eI8f_tm_4X49U_d872gTXN0_tRUueK-Mutd3YfrxahfnfYjNE1839iHuA7qB_4TP833dMP3n82uq8-sfwzChpq7Khnr9v_Rk437OkNIVbb-GTdWKJX0Q1XJzzHY63ug2Cyk1cls1t5PLclvqGjwUm0qxpRZbSrGtFttKsaMWO0qxqxa7SrGnFntKsf9EPL__7r8AAAD__0GfHss=) and vectorize [on](https://cockroachdb.github.io/distsqlplan/decode.html#eJyklm9z2kYQxt_3U-xsX0RkrvLd6b9mMiNc45QWQwqkTdoyjIxuqGohKadTa8bjj9Uv0E_WEQgiglGCw6u73XtOuz_2ETxg8SFBH3vv3gy6_SF0h93B-996oF31J9PJz4MOTHqD3vdTKMqVlszFvRJpJKJcxgvRgQtwdArdCYR_L-drEcpkDdfj0Q0kcSpiJVYE8lAq-PWH3rgHmqbl82p_J9bwCpLdugPd4RVo-fxWhmkEr-DFZbX4lhsvOvvcIktVGKdCVvmb3hVcjt7t08n8QxmmKlZr-KOk1FiAVpdNdQ4vq_IaZzqHNdbVJY3S9mV2OkgwzSIxDFeiQP93ZDgjmMtsIYoik1XoYXOgH92jTwnGaV6qKjwjuMikQP8BVawSgT5Ow9tEjEUYCXlBkWAkVBgnm2ur5wW5jFehXCPBSR6mhQ_fIcHrOFFC-qAF5gEa3_cn03F_-LpmEDhNMh-zSHBUKh8CRgKTBA4SvA3V4k9RQFaqvEoxbiBBVeZJI8ipiQT7I1DxSvjADaY73FkVlX6tRAFShJEP3IWb-BIJyuyfQq9jtPrg7JHg9raaR6HCpUCfPZIvZ_ZjFqc1MnaIbPf9Bck8v0OCgyy7K3P4K4tTyNKq4WbrnATGBoC1ZVCVu2th02mhwiTZN8t15lmbZuM0EvfQOG5T193HmyrGPd2wa0SfIraOCdcXiXuxKFWcpbtrDEd3bPuYNIef4suTVPkzqfITVD8O4xFYkwR2ky1jh0DrxppsDIfpnnMmUJNR3eNfDdQ0mc5s6wgo091WosY5RLvLpRTLUGXywjgkup1DGQkponoqu8P38-FoOh--HQy0gFUe7f7yWgt4tRpXb1jpQ8BfUp37vn89GHWnLtlKjziccu7RWDH637_FyWbNZ46PeaYp-ZOmtD_nSJdR3fG8cx1JdZvxrzekbtns2I_Ubh0f65lErfMNaZCgUo2GEDC6-wlsvv8-b1CXW7pp8TMBe57usKf50mO-lus8hZe6umcd83UNr5Wv_Ux72od8J29vagvujccuHJ3ujfdlpmNPdMaNNsc559Q_FkWepYU4qP3UzfRxRlBES7H9e1JkpVyINzJbbB6z3Y42uk0gEoXaZtl200-3qarAppi1inm7mLeKjXax0So228Vmq9hqF1utYrtdbLeKnU_Es8dv_g8AAP__LWyh3g==) for comparison.

**Review by asubiotto — CHANGES_REQUESTED** [review]
How come the explain analyze logic tests don't need to be updated?

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-:-MGDpQ_bBf-MVtY-KP-K:b-9qpt4u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/execinfra/server_config.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-MGDolVS1TqXI5L8hUL4:-MGDolVS1TqXI5L8hUL5:bm2p4lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f86847dd93d5dfd08156f31eab475774e903b65/pkg/sql/execinfra/server_config.go#L72)):*
> ```Go
> // MinAcceptedVersion is the oldest version that the server is
> // compatible with; see above.
> const MinAcceptedVersion execinfrapb.DistSQLVersion = 37
> ```

Does the distsql version need to be bumped? It's ok for a server that knows about the rows read protobuf field to receive a protobuf with that missing field, right? I think it'll just be set to 0. Also, if sent to a previous version, I think that field will just be dropped.

**Review by asubiotto — COMMENTED** [review]
small nit, in the vectorize on link above it seems that rows read is displayed as `rows.read`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-:-MGDphRgEU4TvMx_AMgx:b-hug2ik)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Explain analyze logic tests aren't updated because we hide number of rows read if it is 0 (and it is always zero in the tests to get deterministic output).

Fixed the nit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-:-MGEUZfg4p3oVN7E_GCj:b-vjyem3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/execinfra/server_config.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-MGDolVS1TqXI5L8hUL4:-MGEV8lM9Vz1dD0YpkjH:bxyg39d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f86847dd93d5dfd08156f31eab475774e903b65/pkg/sql/execinfra/server_config.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does the distsql version need to be bumped? It's ok for a server that knows about the rows read protobuf field to receive a protobuf with that missing field, right? I think it'll just be set to 0. Also, if sent to a previous version, I think that field will just be dropped.
</blockquote></details>

Removed. In this case my knowledge is limited, so I tend to lean on the safe side of bumping the version.

**Comment by asubiotto** [comment]
> and it is always zero in the tests to get deterministic output

I don't understand why, the number of rows shouldn't change right? So `DeterministicStats` shouldn't set the number of rows to 0.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/execinfra/server_config.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-MGDolVS1TqXI5L8hUL4:-MGE_cxE2F31XDINHGDl:b-l0lkop) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f86847dd93d5dfd08156f31eab475774e903b65/pkg/sql/execinfra/server_config.go#L72)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Removed. In this case my knowledge is limited, so I tend to lean on the safe side of bumping the version.
</blockquote></details>

Found this: https://docs.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-3.1#non-breaking-changes. In the latter case, there is a collection of "unknown fields" that the new field value would be put into if deserializing in a prior version.

**Review by yuzefovich — COMMENTED** [review]
Yeah, good point, I didn't give it much thought. I updated the code to not zero out `rows read` and stressed it for a bit and didn't see any failures.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-:-MGEctb3EmTMtNuruVBO:bqn3z7m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/execinfra/server_config.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-MGDolVS1TqXI5L8hUL4:-MGEcqW0DEcen4gQBMvT:b9ldnc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f86847dd93d5dfd08156f31eab475774e903b65/pkg/sql/execinfra/server_config.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Found this: https://docs.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-3.1#non-breaking-changes. In the latter case, there is a collection of "unknown fields" that the new field value would be put into if deserializing in a prior version.
</blockquote></details>

Cool, thanks.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-:-MGIu3hK-Un2KK8PqhVt:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-MGIu8L3ChmRBxmiuTle:-MGIu8L3ChmRBxmiuTlf:b-tb7hry) ([raw file](https://github.com/cockroachdb/cockroach/blob/f170a42639134f5b13cfb822460b54c6b707cdae/pkg/sql/colexec/stats.go#L161)):*
> ```Go
> 	vsc.finalizeStats()
> 	if deterministicStats {
> 		vsc.VectorizedStats.Time = 0
> ```

I think out of all of these, we only need `Time` to be zeroed out.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-:-MGJPVme9dkKpZ5nS2Uq:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/stats.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-MGIu8L3ChmRBxmiuTle:-MGJOSZ-9IKt4cHcntbH:bkrrd5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f170a42639134f5b13cfb822460b54c6b707cdae/pkg/sql/colexec/stats.go#L161)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think out of all of these, we only need `Time` to be zeroed out.
</blockquote></details>

I don't think so: because we randomize `coldata.BatchSize()` we can definitely get different number of batches, additionally, that number will also influence the dynamic batch size behavior which, in turn, can change the amount of memory allocated.

I thought that I could remove `BytesRead` resetting from here, but I stressed the queries a bit and they failed pretty quickly. I didn't look into why that happens because I think, in general, this is not very important because deterministic stats are used only in test environment. One could argue that this might the only our way to actually test the stats collection though.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53775)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53775#-MGIu8L3ChmRBxmiuTle:-MGJUV0e4vdDOelMjIUI:bog4djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f170a42639134f5b13cfb822460b54c6b707cdae/pkg/sql/colexec/stats.go#L161)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think so: because we randomize `coldata.BatchSize()` we can definitely get different number of batches, additionally, that number will also influence the dynamic batch size behavior which, in turn, can change the amount of memory allocated.

I thought that I could remove `BytesRead` resetting from here, but I stressed the queries a bit and they failed pretty quickly. I didn't look into why that happens because I think, in general, this is not very important because deterministic stats are used only in test environment. One could argue that this might the only our way to actually test the stats collection though.
</blockquote></details>

Fair enough. The `BytesRead` failure is definitely unexpected, I wonder what's going on there.

**Pull request merged**
