### PR TITLE
acceptance: switch to auto upgrade at the end of TestVersionUpgrade.

### PR DESCRIPTION
**Pull request by ghost**
To make TestVersionUpgrade less racy, we make the final step in TestVersionUpgrade
to observe that the auto upgrade happens instead of manually upgrading.

Fixes: #25577.
Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm: and thanks!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/acceptance/version_upgrade_test.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25616#-LCizsV_9bNDgq_Zb3tf:-LCizsV_9bNDgq_Zb3tg:b-3f1no8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5253525fb98e4d09b066ffacf2febdf39d98321/pkg/acceptance/version_upgrade_test.go#L273)):*
> ```Go
> 
> 		binaryVersionUpgrade{newVersion: sourceVersion},
> 		clusterVersionUpgrade{newVersion: clusterversion.BinaryServerVersion.String(), manual: false},
> ```

nit (only if CI fails): you can omit `manual: false` (as we will do for all future versions).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25616#-:-LCj-0Vy4XAnhy_jjDWU:bc6pnq8)*

**Comment by tschottdorf** [comment]
@windchan7 please triage the test flake before (i.e. post a comment what it was if it's a known issue, or create an issue if it's new, or post a comment that it was a flake on this PR that you then fixed).

**Comment by windchan7** [comment]
@tschottdorf That's a known issue: https://github.com/cockroachdb/cockroach/issues/25203.

**Pull request merged**
