### PR TITLE
dashboards: switch flushes/compactions graphs to bytes written

### PR DESCRIPTION
**Pull request by dt**
Release note (ui change): The Flushes/Compactions graph on the Storage metrics Dashboard now shows bytes written by these operations, and has been split into separate graphs which are each per-node.

Screen Shot 2022-03-09 at 1 46 29 PM

Release justification: low risk, seems useful (we've frequently wished we had it in escalations from prior versions)

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
love it :lgtm: 

I'm wondering whether we should also throw `ingested-bytes` somewhere on this dashboard, maybe in the same graph as flushes. It would be nice to be able to quickly view bytes being added to the LSM.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77558#-:-Mxk4vxBAfxv5nRYwtxi:b-qwblva)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

**Comment by dt** [comment]
> we should also throw ingested-bytes somewhere on this dashboard
➕ 

> maybe in the same graph as flushes

I didn't see any examples of multi-metric _and_ per-node graphs, but maybe I didn't look hard enough.

**Comment by dt** [comment]
> we should also throw ingested-bytes somewhere on this dashboard

Done.

**Comment by dt** [comment]
@jbowens you okay with the additional graph for ingestions? I asked in slack if we ever did multi-metric per-node graphs and  and @dhartunian confirmed that we don't, so I think it'd be a separate graph if we want it (and want to keep flushes and it per-node, which I think we do?)

**Comment by jbowens** [comment]
@dt yeah, separate graph works 👍

**Comment by dt** [comment]
Perfect.

TFTR!

bors r=jbowens

**Pull request merged**
