### PR TITLE
sql: separate row formation from scanNode

### PR DESCRIPTION
**Pull request by RaduBerinde**
Separating the code to convert from key/values to rows into rowFetcher. The
rowFetcher will be used by the new TableReader.

Had to refactor a few things, especially the way we generate debug values (we
now generate them in processKV instead of "leaking" things from the function).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6193)

### CODE REVIEW

**Comment by andreimatei** [comment]
:LGTM:

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/rowfetcher.go, line 217 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFtuwwRqX6lLhbE4PCN:-KFtuwwRqX6lLhbE4PCO:1379604208) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf4f4c261e5a174b5138f7da99cc3a02fbe4d71/sql/rowfetcher.go#L217)):*
please add a comment to this function and the args

---

*[sql/rowfetcher.go, line 246 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFtvbDEVIKDFU_cnCul:-KFtvbDEVIKDFU_cnCum:1505216087) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf4f4c261e5a174b5138f7da99cc3a02fbe4d71/sql/rowfetcher.go#L246)):*
what does `v` stand for? How about `colId`?

---

*[sql/rowfetcher.go, line 266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFtvmVJNzRFfQZsdvoM:-KFtvmVJNzRFfQZsdvoN:-1000955725) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf4f4c261e5a174b5138f7da99cc3a02fbe4d71/sql/rowfetcher.go#L266)):*
nit: `V(2)` is the level we use for all the debugging logs, but this seem very verbose. Maybe a higher one?

---

*[sql/scan.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFtuF059MJt0y2y0PGO:-KFtuF059MJt0y2y0PGP:113324109) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf4f4c261e5a174b5138f7da99cc3a02fbe4d71/sql/scan.go#L113)):*
what's the return value? How come it's not `error`?

---

*[sql/scan.go, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFtzOH5qBBVd47pA72W:-KFtzOH5qBBVd47pA72X:-1813592117) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf4f4c261e5a174b5138f7da99cc3a02fbe4d71/sql/scan.go#L169)):*
can we split this debug mode read in a separate function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-:-KFtzhDR3zRne5g6Xq0B:1386550993)*

**Comment by RaduBerinde** [comment]
TFTR! All comments addressed.

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/scan.go, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFtzOH5qBBVd47pA72W:-KFu84Mu8kpBKnwKQhiI:-580824449) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf4f4c261e5a174b5138f7da99cc3a02fbe4d71/sql/scan.go#L169)):*
Great idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-:-KFu86MyIiYk5gRC9LyS:2119974708)*

**Comment by tamird** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/scan.go, line 115 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFyOGyIfzpL8Lqy8lt2:-KFyOGyIfzpL8Lqy8lt3:1620150597) ([raw file](https://github.com/cockroachdb/cockroach/blob/c911eae13eca52ebffec45b68662299a23e2876c/sql/scan.go#L115)):*
how come this isn't the body of `Start`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193)*

**Comment by petermattis** [comment]
@tamird Did you fat-finger that merge button?

**Comment by tamird** [comment]
Whoa, apparently? How'd that happen

**Comment by RaduBerinde** [comment]
TFTR! No problem, it was ready to merge anyway.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-:-KFz4xRJ3FF2s35KtpnB:492901023)*

**Comment by RaduBerinde** [comment]
*[sql/scan.go, line 115 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193#-KFyOGyIfzpL8Lqy8lt2:-KFz4jXXLiE6hEu7PQua:2083067712) ([raw file](https://github.com/cockroachdb/cockroach/blob/c911eae13eca52ebffec45b68662299a23e2876c/sql/scan.go#L115)):*
in the index join case, it can be called multiple times (once for each batch). it's a bit of a hack since the indexjoin code is mucking with the scan internals a bit, we should clean that up and add a proper API at some point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6193)*

**Pull request merged**
