### PR TITLE
sql: Improve INTERVAL input format

### PR DESCRIPTION
**Pull request by theangryangel**
This a first attempt at a patch to provide iso8601 (with designators) and postgres compatiable interval strings to cockroach (issue #2710). I'm kinda expecting you'll want extra changes :smile:

I wasn't really sure if leaving the string parsing functions in the sql/parser package was the "correct" place.

As far as I can tell iso8601 and postgres interval formats don't support units lower than a second. I don't know if this is an issue, but it is counter to the native time.ParseDuration.

I've added functional tests, to eval_test.go, and I'm happy to setup something for interval_test.go as well.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4858)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/parser/eval.go, line 1038 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IXuktIO3h4eXNC1j:-KC1IXuktIO3h4eXNC1k:977032065) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1038)):*
you're already inside a type switch here, so you can change `switch d.(type) {` to `switch v := d.(type) {` instead of adding this line. I believe you can get by without casting `DString` to `string`.

---

*[sql/parser/eval.go, line 1041 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1J5PxM_O8vtcrg3eS:-KC1J5PxM_O8vtcrg3eT:-1531992895) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1041)):*
"most likely" - do we need to fall through to another case if we hit an error here?

---

*[sql/parser/eval.go, line 1042 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1J-CERty6wBS1Qsys:-KC1J-CERty6wBS1Qsyt:-1608546963) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1042)):*
Comments should be well-formed sentences, so this needs to end in a period.

---

*[sql/parser/eval.go, line 1043 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IvcPO8hffBqFAOgB:-KC1IvcPO8hffBqFAOgC:-823392251) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1043)):*
can you link to the "format with designators" documentation you consulted here?

---

*[sql/parser/interval.go, line 1 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1JFz8LYl7-w-XXH3E:-KC1JFz8LYl7-w-XXH3F:676036456) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L1)):*
2016

---

*[sql/parser/interval.go, line 77 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1JuX9xH8DJK_NY-S7:-KC1JuX9xH8DJK_NY-S8:1410175126) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L77)):*
have you considered using https://github.com/ChannelMeter/iso8601duration?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by theangryangel** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/parser/eval.go, line 1038 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IXuktIO3h4eXNC1j:-KC1erSHNEbSI1Ibj0qt:-1899015367) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1038)):*
The main reason why I was casting to a string was because the code I've written uses maps, and I wasn't aware of a better way to look up something in the map when passing in a DString. 

---

*[sql/parser/eval.go, line 1041 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1J5PxM_O8vtcrg3eS:-KC1Zp_3KEJk7dodzhVQ:-1395573669) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1041)):*
Going by the postgres documentation the only supported interval formats are: 
 - postgres
 - sql 
- both iso8601 formats

The code doesn't deal with sql or the "other" iso format (yet), and the fallback to golang is the only option I can see at this point. 

The only other option *should* be malformed input, or a golang parseDuration compatible string. 

---

*[sql/parser/eval.go, line 1042 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1J-CERty6wBS1Qsys:-KC1gE4sMYqjPXADw0B8:144265524) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1042)):*
I'll address this in the next patch, pending rest of the feedback.

---

*[sql/parser/eval.go, line 1043 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IvcPO8hffBqFAOgB:-KC1aqaJ2STxuba88_Kq:-460070192) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1043)):*
Unfortunately I've had to piece it together from various sources:
  - http://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES
  - https://en.wikipedia.org/wiki/ISO_8601#Time_intervals
  - https://en.wikipedia.org/wiki/ISO_8601#Durations

I've realised I've missed weeks out of the this PR.

---

*[sql/parser/interval.go, line 77 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1JuX9xH8DJK_NY-S7:-KC1gPI-BwzB_X1Fb74x:-1292828195) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L77)):*
I hadn't come across it, honestly. Not sure how.

That said, my reservation is the notice at the top of the file "Package duration provides a partial implementation of ISO8601 durations. (no months)", which postgres does support.

On top of that, I realise I've missed weeks from the implementation. I need to confirm if postgres also supports weeks, and if they do, I can add to this this implementation and I believe it should match postgres' behaviour (i'll double check).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by theangryangel** [comment]
*[sql/parser/eval.go, line 1038 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IXuktIO3h4eXNC1j:-KC1kC1IGQGSTFdjwtnr:560880813) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1038)):*
I've just done a quick test and a bit of investigation and I'm also running into problems with the ContainsRune and ParseDuration calls in this file. I'm not super experienced with go, and I don't know the cockroach codebase well enough to know if this is do-able in a better way than casting to a string. Please let me know if I should continue looking?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by tschottdorf** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/parser/eval.go, line 1040 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC26WbOSBfDSfIjDytW:-KC26WbOSBfDSfIjDytX:1836101819) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1040)):*
is `len(str) > 0` guaranteed?

---

*[sql/parser/interval.go, line 81 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC26mZYSTXxfvkEAaFh:-KC26mZYSTXxfvkEAaFi:-497687465) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L81)):*
`s == ""`?

---

*[sql/parser/interval.go, line 102 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC26ytfv14-b52vd4Cz:-KC26ytfv14-b52vd4D-:-443698280) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L102)):*
now it seems possible again that `s == ""`.

---

*[sql/parser/interval.go, line 183 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC278OgY3s95_IiIEJv:-KC278OgY3s95_IiIEJw:-1326951571) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L183)):*
`len(u) == 0`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by tamird** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/parser/eval.go, line 1038 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IXuktIO3h4eXNC1j:-KC2Ih5j6WVBUc4v-_N2:-2005528335) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1038)):*
There are two parts to my comment - can you address the first? If you still need the `string` cast, that is fine.

---

*[sql/parser/eval.go, line 1041 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1J5PxM_O8vtcrg3eS:-KC2J9wNyeThTgqxh27S:389779399) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1041)):*
Can you adjust the comment to reflect this additional information?

---

*[sql/parser/eval.go, line 1043 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IvcPO8hffBqFAOgB:-KC2Iws6l8fD06J6ZPEA:-1994798025) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1043)):*
To clarify, these links should appear in the comment, if they are necessary for understanding the rest of the comment or the code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by theangryangel** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[sql/parser/eval.go, line 1038 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IXuktIO3h4eXNC1j:-KCI150v_k0c64h78FYv:-471121004) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1038)):*
I've added `v := d.(type)`, in what I believe in the right way. I'll update the pull request shortly.

---

*[sql/parser/eval.go, line 1040 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC26WbOSBfDSfIjDytW:-KCI1EYgrniIKc3sdKLd:-111115040) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1040)):*
Appears not, I've added an early exit. I'll update the pull request shortly.

---

*[sql/parser/interval.go, line 102 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC26ytfv14-b52vd4Cz:-KCHzcQwpyGe2EyJZ2LT:1281191889) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L102)):*
Unless I'm being thick this evening, I think it should be safe since it's covered by the loop condition, and nothing has been removed by this point?

---

*[sql/parser/interval.go, line 183 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC278OgY3s95_IiIEJv:-KCI-DDlXzEjvh1DFaMi:-380725009) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L183)):*
I don't think this case should be hit, since consumeUnit will return an error if there is no string found. However, if you'd like an additional check I'll add it :smile:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[sql/parser/interval.go, line 52 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLkfWSkpdEQHkPk7EI:-KCLkfWSkpdEQHkPk7EJ:-759195603) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L52)):*
>= '9' implies >= '0'

---

*[sql/parser/interval.go, line 62 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLjU4REuUQIL8HKC7u:-KCLjU4Swb3EnnaWvDTe:764241869) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L62)):*
Is it possible for you to make these consume methods use slices. We really do not want to keep creating strings

---

*[sql/parser/interval.go, line 68 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLfEQAvdszAxcCnHGF:-KCLfEQBDa6ETpuqnP1l:-365928067) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L68)):*
or leap year

---

*[sql/parser/interval.go, line 173 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLicvM3IGP18Xl_PRF:-KCLicvNVermRVL_7hN8:1897227717) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L173)):*
Did you mean '9'? A test to catch that? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by theangryangel** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[sql/parser/interval.go, line 62 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLjU4REuUQIL8HKC7u:-KCgG3sLNLCumfgO7S0k:904460307) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L62)):*
No problem. I only followed this pattern because that's how golang time/format.go implemented this. I'll switch to slices instead and update the PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by theangryangel** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[sql/parser/eval.go, line 1038 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1IXuktIO3h4eXNC1j:-KDxY6qUoSVvGmBq2gBm:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/eval.go#L1038)):*
Done.

---

*[sql/parser/interval.go, line 1 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC1JFz8LYl7-w-XXH3E:-KDxWUqOmWg1JE1KKiU5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L1)):*
Done.

---

*[sql/parser/interval.go, line 81 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC26mZYSTXxfvkEAaFh:-KDxWjfO3nr_OZ8z3ech:1393201899) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L81)):*
Check added.

---

*[sql/parser/interval.go, line 183 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KC278OgY3s95_IiIEJv:-KDxWnl16FddxMP9gTGM:1616194310) ([raw file](https://github.com/cockroachdb/cockroach/blob/19acf9ce4fa34c56177e148282837599d7cb0bf7/sql/parser/interval.go#L183)):*
Additional check added. Done.

---

*[sql/parser/interval.go, line 52 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLkfWSkpdEQHkPk7EI:-KDxWWzIN8kUGLOattDy:120048057) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L52)):*
I think this updated version is a bit more readable? Hopefully.

---

*[sql/parser/interval.go, line 68 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLfEQAvdszAxcCnHGF:-KDxW_azhJ9a9cfSYgCR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L68)):*
Done.

---

*[sql/parser/interval.go, line 173 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KCLicvM3IGP18Xl_PRF:-KDxWqodrR8tX73SPNBl:273141521) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb403f81a2162b98cfa1b568f18831755279736/sql/parser/interval.go#L173)):*
Typo. Fix added. Done?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by tamird** [comment]
Reviewed 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/parser/interval.go, line 27 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KDxqVsrAYzfdbUnjn-0:-KDxqVssmmlLK70kOemY:-186404093) ([raw file](https://github.com/cockroachdb/cockroach/blob/a21ffabac2e7e220c55ed3bd97429700d668249a/sql/parser/interval.go#L27)):*
looks like much of this is lifted from the time package, but wouldn't it be more idiomatic to implement this using a scanner?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by theangryangel** [comment]
*[sql/parser/interval.go, line 27 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858#-KDxqVsrAYzfdbUnjn-0:-KDyiCD7xkkazqO3KuN1:-927312373) ([raw file](https://github.com/cockroachdb/cockroach/blob/a21ffabac2e7e220c55ed3bd97429700d668249a/sql/parser/interval.go#L27)):*
Honestly, my experience with go is a little limited at the moment, and I made the assumption that the time/format.go was an example of idiomatic go, since it's part of the core library. 

Are you telling me you'd rather have the whole implementation (read: file) to using scanners instead, not just the 2 consume methods? (because that's what I think you're asking for ultimately). Previously someone from the cockroach team asked for it to be switched to slices, rather than allocating strings - which now seems like a waste of my time since I think scanners would basically invalidate most of the implementation? It's not that it's taken a huge amount of time, but just that this is revision 3/4, and I figured I was past refactoring it...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4858)*

**Comment by tamird** [comment]
@theangryangel we appreciate your contribution to the project, but ultimately and perhaps unfortunately, we are not always able to optimize for short feedback cycles for external contributors, especially when the desired implementation is not well known in advance.

If you'd like to leave this as-is, that's more than OK. Someone from the core will pick up this work and finish it up

**Pull request closed without merging**
