### PR TITLE
sql: use time-based sampling for logical plans

### PR DESCRIPTION
**Pull request by celiala**
Previously, the rate at which we sampled logical plans was once every 1000th
time that fingerprint was executed. This diff changes the sampling rate from
count-based (once every 1000th execution) to a time-based cluster setting
(the default is set to once every 5 minutes).

This solves the following:
- For fingerprints with high execution counts, this prevent us from sampling
  too often and creating unnecessary overhead.
- For fingerprints with lower execution counts, this allows us to refresh
  plans more frequently, which could be helpful if a user wants to verify
  that a configuration change has improved a fingerprint's logical plan and
  execution time.
- Because stats are stored per node, having a timestamp additionally means
  that the UI can now determine and surface the plan that's the most
  recent across all nodes.
- This also solves an edge case where statementStatistics might exist
  without a sample, which can happen if user has set
  `sql.metrics.statement_details.plan_collection.enabled` to false, or if the
  stats were collected before this feature was introduced.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Very good initiative! 
I think it should be configurable with a cluster setting, see below for details.
LGTM otherwise.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34231#-:-LX3q6Vx8wvCQqkm0dve:b-6xindk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala)

___
*[pkg/sql/app_stats.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34231#-LX3pRlT75uJMTIM4_xi:-LX3pRlUDC_djsr7Jm9n:b4bsiaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c776001c06b5c55c0bd1c7102131567729a959/pkg/sql/app_stats.go#L107)):*
> ```Go
> 
> // logicalPlanSamplingFrequencyInMinutes is frequency at which we save a logical plan for each fingerprint.
> const logicalPlanSamplingFrequencyInMinutes = 5
> ```

Maybe create a cluster setting for this? I would recommend this:

1) rename the current `sql.metrics.statement_details.sample_logical_plans` to `sql.metrics.statement_details.plan_collection.enabled`
2) add `sql.metrics.statement_details.plan_collection.period` 

This can be a regular go duration object, see `server.web_session_timeout` for an example.

**Review by celiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34231)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/app_stats.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34231#-LX3pRlT75uJMTIM4_xi:-LX4QbYJ-EoWZtmYvw1o:b3o9we7) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c776001c06b5c55c0bd1c7102131567729a959/pkg/sql/app_stats.go#L107)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe create a cluster setting for this? I would recommend this:

1) rename the current `sql.metrics.statement_details.sample_logical_plans` to `sql.metrics.statement_details.plan_collection.enabled`
2) add `sql.metrics.statement_details.plan_collection.period` 

This can be a regular go duration object, see `server.web_session_timeout` for an example.
</blockquote></details>

Great suggestion - will do!

**Review by celiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34231)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/app_stats.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34231#-LX3pRlT75uJMTIM4_xi:-LX68dR7-0_3WFGTIYMc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c776001c06b5c55c0bd1c7102131567729a959/pkg/sql/app_stats.go#L107)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

Great suggestion - will do!
</blockquote></details>

Done.

**Comment by celiala** [comment]
RFAL:

- sampling frequency has been moved into cluster setting (sql.metrics.statement_details.plan_collection.period)

**Review by knz — APPROVED** [review]
LGTM but please rebase on top of the PR on collection which was merged yesterday.
Thanks again!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34231#-:-LXOhQ6g0Bjm6DRCTy7p:bpvyyj1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by celiala** [comment]
bors r=knz

**Comment by celiala** [comment]
bors r=knz

**Comment by knz** [comment]
what's going on with this PR? you should not close the PR yourself, bors will do it?

**Comment by knz** [comment]
here it goes. give it time

**Comment by knz** [comment]
@celiala you were clicking the "close and comment" button -- "comment" was the button you need.

**Comment by celiala** [comment]
Thank you!

[I accidentally clicked the wrong button, and tried to reopen and re-do `bors`, but I guess that didn't work? Thank you for fixing!]

**Pull request merged**
