### PR TITLE
roachprod: add `ip` subcommand

### PR DESCRIPTION
**Pull request by rolandcrosby**
Adds a `roachprod ip [cluster]` command to retrieve the IP addresses of the
specified nodes. Also accepts a `--external` argument to retrieve the public-
facing IP addresses of the nodes.

Mostly copypasta'd from the existing `adminurl`/`pgurl` commands, so please
let me know if anything looks amiss.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32513#-:-LRn3csf5SvOwxP931fW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by petermattis** [comment]
Try:

bors r=petermattis

**Comment by rolandcrosby** [comment]
bors r=petermattis

**Comment by petermattis** [comment]
@rolandcrosby bors is already working on it.

**Pull request merged**
