### PR TITLE
ui: Database details page

### LINKED ISSUE #45479: ui: add 'last cleared' timestamp to statement list on table detail page
- [ ] add 'last cleared' timestamp to statement list on table detail page
Screen Shot 2020-02-26 at 5 44 38 PM

### LINKED ISSUE #45480: ui: add pagination to statement list on table detail page
- [x] add pagination to the statement list on table detail page (note: I also created ticket #45479 for adding the 'last cleared' timestamp)

Databases_07

### PR DESCRIPTION
**Pull request by vladlos**
Take out `Statements table`, `Statements Pagination` and `Last cleared` to single component,.
Used `StatementSortTable` in `Database details page`.
Refactoring and clean up code.

Resolves: #45480, #45479

Release note (ui): none

### CODE REVIEW

**Comment by dhartunian** [comment]
This is a new feature, not really a fixit so deprioritizing review for Monday.

**Review by dhartunian — CHANGES_REQUESTED** [review]
@elkmaster can you just help me get comfortable here that this change doesn't break the existing statements page? screenshots or tests would be great.

* Please add a screenshot illustrating the change
* Please add a release note like: "Statements list on database table details page is now paginated and shows last update date matching the global statements list page"
* Please add a release justification

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45637#-:-M2tcqIR76qIvOIkERnZ:bm7s1ql)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45637#-M3gADU89cPbJzb6M8iD:-M3gADU89cPbJzb6M8iE:b-3bq02c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2573fb36d6e185c48fcd73d8d5517b0960f66d/pkg/ui/src/views/statements/statementsPage.tsx#L246)):*
> ```XML
>                 sortSetting={this.state.sortSetting}
>                 onChangeSortSetting={this.changeSortSetting}
>                 renderNoResult={this.noStatementResult()}
> ```

The behavior appears to have changed here. The extracted component does not have a `renderNoResult` prop. Please be careful when introducing changes like this. You either need to have tests verifying the empty states or show screenshots.

Otherwise, you can keep this component here and only use the new component on the database table details page if you're worried about preserving functionality.

**Comment by elkmaster** [comment]
Grants
Statements
Overview

**Comment by dhartunian** [comment]
@elkmaster Can you rebase on master so we can sync up with the table statements page removal?

**Comment by dhartunian** [comment]
Actually, let's hold off I think we can just put this away for now.

**Pull request closed without merging**
