### PR TITLE
ui: fix sql stats page data refreshing

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit fixes a couple of bugs with sql stats page data fetching.

First - we missed clearing the initial timeout to fetch data that was created on mount - it should be cleared when a new time range is selected on the page or when the page is unmounted. Currently, this bug can lead to unexpeted data refetches of the incorrect (previously selected) time range.

Second - with the introduction of new pages that use the time picker, such as insights, sql stats pages are no longer the only page that can change the time range. Previously, data was only fetched on mount for sql stats pages if it was not previously fetched, or a data refresh was scheduled based on last update time if the current time range was not a custom (fixed) range. We should now also refetch when the data is outdated due to a new time range being selected on a different page. This commit introduces the `isDataValid` prop to sql stats pages to determine this and refetch data accordingly.

Epic: none

CC - just showing all the fetching is still working:
https://www.loom.com/share/1b24ec65dbe64dcd9c23cd2be980b877

DB Console -
https://www.loom.com/share/0afe1722d7ab418bb7f41c2462f4d84a

### CODE REVIEW

**Review by ericharmeling — APPROVED** [review]
Great catch! I noticed just a few things, otherwise LGTM.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-:-NM0u4003fMwDUlLvaqG:bu4j0hz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0sd3Y7LAilTJl6Wrh:-NM0sd3Y7LAilTJl6Wri:b-api965) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L157)):*
> ```XML
>   RouteComponentProps<unknown>;
> 
> function statementsRequestFromProps(
> ```

Should we rename this now?



_Suggestion:_
```XML
statementsRequestFromTimeScale
```
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx` line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0tHyD3iuuAhophUXC:-NM0tHyD3iuuAhophUXD:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L121)):*
> ```XML
>   RouteComponentProps;
> 
> function statementsRequestFromProps(
> ```





_Suggestion:_
```XML
statementsRequestFromTimeScale
```
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.selectors.ts` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0t_M7573RpUjerqFK:-NM0t_M7573RpUjerqFL:b-rzl21f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.selectors.ts#L23)):*
> ```XML
> );
> 
> export const selectTxnsDataValid = createSelector(
> ```

This looks like the same selector as `selectStatementsDataValid`. Could you just use that one?



_Code quote:_
```XML
selectTxnsDataValid 
```

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0vVFg5bkhLb_g1azG:-NM0vVFg5bkhLb_g1azH:bmlzh3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L347)):*
> ```XML
>       nextRefresh = now;
>     } else if (this.props.timeScale.key !== "Custom") {
>       nextRefresh = this.props.lastUpdated
> ```

Same q here about `lastUpdated` as below.
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx` line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0uvxk0PYQjAWZpA5G:-NM0uvxk0PYQjAWZpA5H:b-na65n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L241)):*
> ```XML
>       nextRefresh = now;
>     } else if (this.props.timeScale.key !== "Custom") {
>       nextRefresh = this.props.lastUpdated
> ```

Can we count on `lastUpdated` to exist here now? The previous code had `this.props.lastUpdated?.clone()...`, with the `?`.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @matthewtodd)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0sd3Y7LAilTJl6Wrh:-NM0wXE--gxwXobtn0ZP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L157)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Should we rename this now?
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx` line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0uvxk0PYQjAWZpA5G:-NM0vp2lB8Us6eLSRQMa:b-ngxdsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L241)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Can we count on `lastUpdated` to exist here now? The previous code had `this.props.lastUpdated?.clone()...`, with the `?`.
</blockquote></details>

Yup, if lastUpdated is nullish, it would have gone into the previous block.
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.selectors.ts` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0t_M7573RpUjerqFK:-NM0xKTrDtR2vXe6vjUH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.selectors.ts#L23)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

This looks like the same selector as `selectStatementsDataValid`. Could you just use that one?
</blockquote></details>

Done.

**Review by matthewtodd — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx` line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95397#-NM0uvxk0PYQjAWZpA5G:-NM4J4PvDWnRSXf1VLCS:brm37qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf5f49bcb9ea26ecfd2cde4fc63633291573b3d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L241)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Yup, if lastUpdated is nullish, it would have gone into the previous block.
</blockquote></details>

:facepalm: of course. Thanks.

**Pull request merged**
