### PR TITLE
go.mod: bump Pebble to f235f568816e

### PR DESCRIPTION
**Pull request by raggar**
```
f235f568 Related to: #103744
ac69476c db: avoid logging to stdout in unit tests
a40f14d1 db: annotate table number when tables cannot be loaded
e7aa90f2 sharedcache: move to a dedicated package
bb4fc952 db: deflake additional TestCompactionTombstones cases
4ca2bec5 sharedcache: improved randomized test, fix bugs
5a007460 *: Implement iterators and seqnum substitution for foreign SSTs
45069a0f db: consider scheduling compaction when adding point tombstone compensation
2ff7efbd db: remove experimental point tombstone weight option
a8d7345e sharedcache: implement a randomized test
cf66a4c9 sharedcache: fix two bugs, add assertions & test case
ed934f88 vfs: add logging for OpenReadWrite & WriteAt
25a8e9bb db: add DeleteSized and corresponding compaction heuristics
49ae5454 db: fix leak for compaction bytes-in-progress metric
f72555ca tool: improve `wal dump` output
7a5a70ca vfs: make in-mem vfs satisfy the vfs contract
229d8ca9 secondarycache: implement a minimal functional secondary cache
cc71ef1d secondarycache: implement a minimal skeleton
e44902ba vfs: support WriteAt
e892f45b objstorage: implement read-ahead for shared objects
4151e559 objstorage: rename MaxReadahead to SetupForCompaction
f6eaf9a6 sstable: don't rely on Stats.NumEntries for virtual sstable creation
5db2191d sstable: clean up suffix rewriter comment, test
```

Release note: none 
Epic: none

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
CI is failing because the vfs.FS interface was modified to introduce a new method `OpenReadWrite`. (cc @RaduBerinde)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104087#-:-NWhLVO30zmqU8NV_P03:bggqm7u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by RaduBerinde** [comment]
> CI is failing because the vfs.FS interface was modified to introduce a new method OpenReadWrite

It would be ok to add the missing methods with a `panic('unimplemented')` inside.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104087#-:-NWn0Q9K44wg_Q5rLaU4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104087#-:-NWn5pz5-qXWjbkHmtMG:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by RahulAggarwal1016** [comment]
bors retry

**Comment by jbowens** [comment]
bors retry

:)

**Pull request merged**
