### PR TITLE
builtins: implement ST_Length2D and ST_Perimeter2D

### LINKED ISSUE #48966: geo/geomfn: implement ST_Length2D({geometry})
Implement `ST_Length2D` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Length2D.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Use ST_Length

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-07-16T23:54:21Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #49006: geo/geomfn: implement ST_Perimeter2D({geometry})
Implement `ST_Perimeter2D` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Perimeter2D.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Implemented by GEOS.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
In addition, refactor builtins which are aliases to be initalized by
initGeoBuiltins, instead of having to define them twice in the map.

Resolves #48966.
Resolves #49006

Release note (sql change): Implement ST_Length2D and ST_Perimeter2D for
geometry types.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-:-MCgB0S64LzlEvpEVdu1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCg8TBI9BTuAgE6e0qX:-MCg8TBI9BTuAgE6e0qY:btgda0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L225)):*
> ```Go
> 	types.Float,
> 	infoBuilder{
> 		info:         "Returns the area of the given geometry.",
> ```

should you specify meters^2?
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCg8NNB9vQoOqeEQewh:-MCg8NNB9vQoOqeEQewi:bbdffs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L241)):*
> ```Go
> 	types.Float,
> 	infoBuilder{
> 		info: `Returns the length of the given geometry.
> ```

should you specify meters here?
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 3498 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCgAF9k0PeeIbt-yx3u:-MCgAF9l8Cr4CxMmefRu:bkyzzkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L3498)):*
> ```Go
> 	}
> 
> 	// Indexed functions have an underscore prepended to the name, which
> ```

[super nit] this comment is sort of confusing. Maybe say something like "Indexed functions have an alternative version with an underscore prepended..."

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51556)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCg8NNB9vQoOqeEQewh:-MCgopIx5JZXSYiEN1oE:b-jmmcrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L241)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should you specify meters here?
</blockquote></details>

units*
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 3498 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCgAF9k0PeeIbt-yx3u:-MCgp6F8BEqMPjg7by8u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L3498)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[super nit] this comment is sort of confusing. Maybe say something like "Indexed functions have an alternative version with an underscore prepended..."
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51556)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCg8NNB9vQoOqeEQewh:-MCgwScr3PoIfCAWs5VC:b-k9e9l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L241)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

units*
</blockquote></details>

Why is perimeter in meters but length is just generic units?

**Comment by otan** [comment]
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCg8NNB9vQoOqeEQewh:-MCgy7Dc-88T3qfSJmmX:blhx68h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L241)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why is perimeter in meters but length is just generic units?
</blockquote></details>

because that's a typo ^_^ thanks for noticing

**Review by rytaft — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51556)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51556#-MCg8NNB9vQoOqeEQewh:-MCgzNHw-0oM-O_mmZzr:b31g3yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8675b4af7db8b08157932d49fdde9ed042213da/pkg/sql/sem/builtins/geo_builtins.go#L241)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

because that's a typo ^_^ thanks for noticing
</blockquote></details>

Ah ok -- in that case, maybe not worth mentioning units at all? I'm fine with whatever you think is best...

**Comment by otan** [comment]
bors r=rytaft

**Comment by otan** [comment]
bors r=rytaft

**Comment by otan** [comment]
bors r=rytaft

**Pull request merged**
