### PR TITLE
ui: fix errors on numbers formatting on metrics graphs 

### PR DESCRIPTION
**Pull request by koorosh**
ui: prevent sending metrics query requests in none queries available

Before, there waa an issue when on initial Metrics page loading
query request was dispatched without any queries in payload.
It led to failed request with error that queries list is empty.
This fix introduces validation that frontend creates query
request if queries list is not empty.

ui: use d3-format lib to format data points on graphs

This patch uses d3.format function to format numbers
instead of Number.toFixed func. It is necessary to
properly handle cases when provided number is primitive
or undefined and fails to call `toFixed` method.
Initially, we used d3 formatting functions before
moving this code to `cluster-ui`, so this change
brings this functionality back.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86041)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86041#-N9HNFz2B_QMfqko555J):*
nit: was
___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86041#-N9HNQ4cCwRqdN0VLZjw):*
can't you do a check with `n?.toFixed(1)` instead of needing to import d3 again?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86041)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86041#-N9HNFz2B_QMfqko555J):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: was
</blockquote></details>

Done. Thanks! 
___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86041#-N9HNQ4cCwRqdN0VLZjw):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can't you do a check with `n?.toFixed(1)` instead of needing to import d3 again?
</blockquote></details>

Makes sense, then it can be like this: `n?.toFixed(1) || "0"`.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86041#-:-N9HyhZx296ODlgG3H20:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by koorosh** [comment]
TFTR Marylia! 
bors r+

**Comment by koorosh** [comment]
bors single on

**Pull request merged**
