### PR TITLE
roachtest,workload: support generating store dumps

### LINKED ISSUE #24337: storage: tocommit is out of range
backup2tb crashed in this nightly run: https://teamcity.cockroachdb.com/viewLog.html?buildId=586079&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildLog

At 11:40, we see a very concerning raft problem on n10 that brings the node down.

```
E180329 11:40:01.157113 263 util/log/crash_reporting.go:451  [n1,s1] Reported as error a24b491ae75e4888b3ee0f3b35da4a1b
panic: tocommit(26) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? [recovered]
	panic: tocommit(26) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

goroutine 263 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42002a240, 0x26120a0, 0xc427505470)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:177 +0x11f
panic(0x1fddd20, 0xc426b888d0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc4267fe900, 0x23a90b0, 0x5d, 0xc44b994260, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:106 +0xfe
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc430c9b110, 0x1a)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc42e1a4400, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1232 +0x54
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.stepFollower(0xc42e1a4400, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1177 +0x44c
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc42e1a4400, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:898 +0x1308
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).Step(0xc442924fc0, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:195 +0xdd
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup.func1(0xc442924fc0, 0x2612020, 0xc4200400c0, 0x26120a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3329 +0xa8
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc44ac34000, 0x2418800, 0xc42c4e1b88, 0xc42c4e1b70, 0x6fe709)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:607 +0x10f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc44ac34000, 0xc42c4e1b88, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:624 +0x88
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup(0xc44ac34000, 0xc4568b36c0, 0x2099860, 0x30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3324 +0x50
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequestWithReplica(0xc420819000, 0x26120a0, 0xc43dbf5a10, 0xc44ac34000, 0xc4568b36c0, 0xc43dbf5a10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3175 +0xeb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x26120a0, 0xc43dbf5a10, 0xc44ac34000, 0x26120a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3793 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc420819000, 0x26120a0, 0xc43dbf5a10, 0xc4568b36c0, 0xc42c4e1ed0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3121 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420819000, 0x26120a0, 0xc427505470, 0x706c)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3787 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420b80000, 0x26120a0, 0xc427505470)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:226 +0x21b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x26120a0, 0xc427505470)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4262f8ec0, 0xc42002a240, 0xc4262f8eb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad
```

https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/586079:id/20180328-586079/backup2TB/10.logs/cockroach.log

Two minutes later, the SSH connection to n1, the node coordinating the backup, gets OOM killed (!).

```
[11:42:11]	[Step 3/3] 	cluster.go:642,backup.go:52,cluster.go:784,errgroup.go:58: roachprod ssh teamcity-586079-backup2tb:1 -- ./cockroach sql --insecure -e "
[11:42:11]	[Step 3/3] 						BACKUP bank.bank TO 'gs://cockroachdb-backup-testing/teamcity-586079-backup2tb'": signal: killed
```

There's not a whole lot in n1's logs:

```
I180329 11:40:01.353808 1350 storage/store.go:3470  [n1,s1,r349/5:/Table/51/1/470{0456/0-3729}] added to replica GC queue (contacted deleted peer)
W180329 11:40:01.565404 308031 vendor/google.golang.org/grpc/server.go:961  grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
W180329 11:40:01.568787 429 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {teamcity-586079-backup2tb-0010:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180329 11:40:01.568830 429 vendor/google.golang.org/grpc/clientconn.go:1277  grpc: addrConn.transportMonitor exits due to: context canceled
W180329 11:40:01.674317 848092 vendor/google.golang.org/grpc/server.go:625  grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF"
```

https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/586079:id/20180328-586079/backup2TB/1.logs/cockroach.log

/cc @vilterp

### LINKED ISSUE #25085: roachtest: generate and upload prebuilt TPC-C store directories
Part of the challenge in making #25084 run fast is that each independent run of the TPC-C roachtest will need to populate a full dataset. To begin with, the roachtest will do so by using `RESTORE`, but this is still slower than we'd like (~30min for TPC-C 1k, ~18h for TPC-C 10k). 

We want the benchmark to take as little time as possible so that we can iterate on it quickly. One way to accomplish this is to upload store directories to google cloud storage and copy these directories onto nodes before starting the cockroach cluster using `gsutil`. This is what we already do in the `backup2TB` roachtest.

One challenge here is that we'll need to create different directory backups for each `(cluster size, warehouse count)` combination. In doing so, it will probably make sense to automate this process to some degree.

### PR DESCRIPTION
**Pull request by benesch**
Support generating store dumps like those used by the backup2tb test. Store dumps can bootstrap a CockroachDB cluster with data more quickly than RESTORE can, but they must be regenerated for every desired number of stores.

The core performance team plans to use these store dumps to quickly bootstrap performance tests.

For example, here's how I'm regenerating the backup2tb stores (to fix #24337):

```
./roachtest store-gen --stores=10 bank --payload-bytes=10240 --ranges=0 --rows=65104166
```

Fix #25085.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: 5 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/ccl/workloadccl/fixture.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgr8T61BiwcBMiylb3:-LBgr8T61BiwcBMiylb4:b35cc7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48a27a2be2b3a3a839236a612f049e06f4917a3/pkg/ccl/workloadccl/fixture.go#L110)):*
> ```Go
> }
> 
> func FixtureURL(config FixtureConfig, gen workload.Generator) string {
> ```

You'll probably need a comment here.

---

*[pkg/cmd/roachtest/main.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgsX1WEooW3v8AUuY4:-LBgsX1WEooW3v8AUuY5:bqxebmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/main.go#L98)):*
> ```Go
> 	var storeGenCmd = &cobra.Command{
> 		Use:   "store-gen [workload]",
> 		Short: "generate store directory dumps\n",
> ```

Do we need the new line here?

---

*[pkg/cmd/roachtest/main.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtqqsDLRnYqhCc-dB:-LBgtqqsDLRnYqhCc-dC:b-dby1j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/main.go#L105)):*
> ```Go
> 		RunE: func(_ *cobra.Command, args []string) error {
> 			r := newRegistry()
> 			registerStoreGen(r, args)
> ```

I was considering the same pattern of arg processing in tpccbench. I'm curious what @petermattis thinks about the approach.

---

*[pkg/cmd/roachtest/store_gen.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtfEYED3Z9DbjK9Fh:-LBgtfEYED3Z9DbjK9Fi:b-szrhgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/store_gen.go#L42)):*
> ```Go
> 
> 				t.Status("uploading store dumps")
> 				var wg sync.WaitGroup
> ```

I'd use an errgroup here. It will save a few lines of code and make error handling a little cleaner.

---

*[pkg/cmd/workload/fixtures.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgs2zn7fIeuRNCkbeK:-LBgs2zn7fIeuRNCkbeL:b9jk6xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48a27a2be2b3a3a839236a612f049e06f4917a3/pkg/cmd/workload/fixtures.go#L71)):*
> ```Go
> 	Short: `Load a fixture into a running cluster. An enterprise license is required.`,
> })
> var fixturesURLCmd = setCmdDefaults(&cobra.Command{
> ```

I think we're missing some of the plumbing here. Looks like it fell into the next commit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321)*

**Comment by benesch** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/ccl/workloadccl/fixture.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgr8T61BiwcBMiylb3:-LBh58gU5fmKaEKdgpYM:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48a27a2be2b3a3a839236a612f049e06f4917a3/pkg/ccl/workloadccl/fixture.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You'll probably need a comment here.
</blockquote></details>

Good point. Done.

---

*[pkg/cmd/roachtest/main.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgsX1WEooW3v8AUuY4:-LBh5A1jAv1KgaYe_Iow:b-y6fkya) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/main.go#L98)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need the new line here?
</blockquote></details>

Yeah, I think it was an intentional spacing between the important commands and the help command in the usage output:

```
roachtest is a tool for testing cockroach clusters.

Usage:
  roachtest [command]

Available Commands:
  run         run automated tests on cockroach cluster
  store-gen   generate store directory dumps

  help        Help about any command

Flags:
  -c, --cluster string     name of an existing cluster to use for running tests
      --cockroach string   path to cockroach binary to use
  -h, --help               help for roachtest
  -l, --local              run tests locally
  -u, --user string        username to run under, detect if blank
      --workload string    path to workload binary to use

Use "roachtest [command] --help" for more information about a command.
```

I agree it's kind of a hack but we do it in a bunch of our CLI tools.

---

*[pkg/cmd/roachtest/store_gen.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtfEYED3Z9DbjK9Fh:-LBh64Yn2PYP8uNm3ikN:b5zff2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/store_gen.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd use an errgroup here. It will save a few lines of code and make error handling a little cleaner.
</blockquote></details>

Done. Though somehow it doesn't actually save any lines of code. :smile: 

---

*[pkg/cmd/workload/fixtures.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgs2zn7fIeuRNCkbeK:-LBh5J5CCMKmN2IDv_iB:bag33kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48a27a2be2b3a3a839236a612f049e06f4917a3/pkg/cmd/workload/fixtures.go#L71)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we're missing some of the plumbing here. Looks like it fell into the next commit.
</blockquote></details>

Whoops, good catch. I actually amended two commits together and botched the unsplit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/cmd/roachtest/main.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgsX1WEooW3v8AUuY4:-LBh8T1095fAL80KVOBG:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/main.go#L98)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, I think it was an intentional spacing between the important commands and the help command in the usage output:

```
roachtest is a tool for testing cockroach clusters.

Usage:
  roachtest [command]

Available Commands:
  run         run automated tests on cockroach cluster
  store-gen   generate store directory dumps

  help        Help about any command

Flags:
  -c, --cluster string     name of an existing cluster to use for running tests
      --cockroach string   path to cockroach binary to use
  -h, --help               help for roachtest
  -l, --local              run tests locally
  -u, --user string        username to run under, detect if blank
      --workload string    path to workload binary to use

Use "roachtest [command] --help" for more information about a command.
```

I agree it's kind of a hack but we do it in a bunch of our CLI tools.
</blockquote></details>

SGTM

---

*[pkg/cmd/roachtest/store_gen.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtfEYED3Z9DbjK9Fh:-LBh7mR_2m_zbFqjzJsF:bhgmxbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/store_gen.go#L42)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done. Though somehow it doesn't actually save any lines of code. :smile: 
</blockquote></details>

`return c.RunE(...` and we'll save a precious line of code!

In all seriousness, I'm not sure how roachtest handles failures in goroutines. I hope it's handled better than in the rest of Go's testing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321)*

**Comment by benesch** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cmd/roachtest/store_gen.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtfEYED3Z9DbjK9Fh:-LBh8ykoCP3ahMlOXZcB:b3vcqqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/store_gen.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`return c.RunE(...` and we'll save a precious line of code!

In all seriousness, I'm not sure how roachtest handles failures in goroutines. I hope it's handled better than in the rest of Go's testing.
</blockquote></details>

It calls `runtime.Goexit`, killing the thread, and marks the test as failed. So the end result is eventually a failing exit status but I think the test's main goroutine churns right ahead and does potentially who knows what with invalid state, just like Go's normal tests. ¯\_(ツ)_/¯  

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cmd/roachtest/store_gen.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtfEYED3Z9DbjK9Fh:-LBh9xjH45FgXzXWgAzv:b-tb8qd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/store_gen.go#L42)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It calls `runtime.Goexit`, killing the thread, and marks the test as failed. So the end result is eventually a failing exit status but I think the test's main goroutine churns right ahead and does potentially who knows what with invalid state, just like Go's normal tests. ¯\_(ツ)_/¯  
</blockquote></details>

That's leaps and bounds better than Go's normal tests, which often seem to silently swallow failures on non-main goroutines.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321)*

**Comment by petermattis** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/main.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtqqsDLRnYqhCc-dB:-LBhUBof0M3dXhDoCo-H:bgngvuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/main.go#L105)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was considering the same pattern of arg processing in tpccbench. I'm curious what @petermattis thinks about the approach.
</blockquote></details>

Which approach are you thinking of? This comment isn't on a line of code that makes it obvious to me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/main.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtqqsDLRnYqhCc-dB:-LBhZYag-AgkeGu5Qopz:b-vvqqay) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/main.go#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Which approach are you thinking of? This comment isn't on a line of code that makes it obvious to me.
</blockquote></details>

Yeah, I think things got moved around in later commits. If you go to revision 3 you can see what we're doing with the command line args for this `store-gen` subcommand. Specifically, we're using them to configure the "test" and then passing nil as the filter to `registry.Run`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321)*

**Comment by tschottdorf** [comment]
> For example, here's how I'm regenerating the backup2tb stores (to fix #24337):

Did you paste the wrong thing below that? I thought I'd see an invocation of the store dir recreation. Are the store dumps versioned just like the fixtures? The compat story here is much more complicated. For example, you would generate a store dir using `master` and then it may end up being used in nightly runs against a `release-2.0` binary. It may be a non-goal to deal with this in the first place (it being a nightmare and all), but make sure to call it out.

The reason I bring it up is because I was also hoping to use store dir fixtures for some roachtests that create anomalous conditions on a range, such as having lots of MVCC tombstones, etc.
It'd be a shame if those tests were to break all the time (I suppose the backup test has this problem today). If you were to address this, how's the following:

1. fixtures are versioned with the `./cockroach version` (rather `node_binary_version`) they are created with. Ideally, we always create fixtures with released versions.
1. roachtests then request specific versions. For example, during the 2.1 cycle (now), you'd request fixtures made with `2.0`.
1. fixtures will have to be regenerated every now and then, but that's true anyway.
1. roachtests have to be updated every major release, which also seems ok.

**Comment by petermattis** [comment]
@benesch is away for 2 weeks. @nvanbenschoten do you want to fix up the lint failure and merge this?

**Comment by benesch** [comment]
I procrastinated packing by fixing the lint failure here. I assume this LGTY, @petermattis? Double-checking because I don't think either @tschottdorf or @nvanbenschoten actually LGTM'd this yet.

---

Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cmd/roachtest/store_gen.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-LBgtfEYED3Z9DbjK9Fh:-LCGScIvAhLLCpKH7jmm:b-iu550) ([raw file](https://github.com/cockroachdb/cockroach/blob/b81c4db8c31816908629d4a3630b4ce8a6c2862a/pkg/cmd/roachtest/store_gen.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's leaps and bounds better than Go's normal tests, which often seem to silently swallow failures on non-main goroutines.
</blockquote></details>

Oh gosh, I didn't realize it was that bad. I've only seen `t.Fatal`ing from a different goroutine produce incomprehensible failures, but failures nonetheless.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-:-LCGSudeANoIr8mtIbMW:b8j2fuv)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25321#-:-LCGaf6-Dk6fSnG32ezP:bnfp4nl)*

**Comment by benesch** [comment]
bors r=tschottdorf

**Pull request merged**
