### PR TITLE
cli: add mt cert create-tenant-signing command

### PR DESCRIPTION
**Pull request by rafiss**
refs #74643 

This key/cert will be used to generate session revival tokens.

No release note since this is only intended to be used internally.

Release note: None

### CODE REVIEW

**Review by catj-cockroach — CHANGES_REQUESTED** [review]
I have a few quick requests about how we're generating the certificate and verifying information output by them, but this looks good to me otherwise!

> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-:-Mt9EeFJ9y8GnsOunGQ7:b-s1ried)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/security/x509.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-Mt95MDa2bO2bMQDmgOp:-Mt95MDa2bO2bMQDmgOq:b-mow4f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a7c039d6cad2d3f9185a6adcfa0af6436b4a71/pkg/security/x509.go#L285)):*
> ```Go
> 	publicKey crypto.PublicKey, privateKey crypto.PrivateKey, lifetime time.Duration,
> ) ([]byte, error) {
> 	template, err := newTemplate(caCommonName, lifetime)
> ```

In my opinion we should use a distinct template for the tenant signing key, rather than reusing the generate template code. We need to store very little information in the certificate, something like this would be sufficient:

```golang
template := &x509.Certificate{
		Subject: pkix.Name{
			CommonName: fmt.Sprintf("Tenant %d Token Signing Certificate", tenantID),
		},
		SerialNumber:          big.NewInt(1), // The serial number does not matter because we are not using a certificate authority and replace this certificate with a new certificate.
		BasicConstraintsValid: true,
		IsCA:                  false, // This certificate CANNOT sign other certificates.
		PublicKey:             publicKey,
		NotAfter:              time.Now().Add(lifetime),
		KeyUsage:              x509.KeyUsageDigitalSignature, // This certificate can ONLY make signatures.
	}
```
___
*[pkg/security/certs_tenant_test.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-Mt9D5IB2VHNp18nMstu:-Mt9D5IB2VHNp18nMstv:b1gnuuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a7c039d6cad2d3f9185a6adcfa0af6436b4a71/pkg/security/certs_tenant_test.go#L162)):*
> ```Go
> 	payload := []byte{1, 2, 3}
> 	signature := ed25519.Sign(ed25519PrivateKey, payload)
> 	ed25519PubKey, isEd25519 := signingCert.ParsedCertificates[0].PublicKey.(ed25519.PublicKey)
> ```

Rather than interacting with the `ParsedCertificates`, could we use the CheckSignature function?

```golang
	err = certActual.CheckSignature(x509.PureEd25519, payload, signature)
	require.NoError(t, err)
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74646)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach and @knz)

___
*[pkg/security/x509.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-Mt95MDa2bO2bMQDmgOp:-Mt9PBDT0k0HmnACH4uE:bcpu1ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a7c039d6cad2d3f9185a6adcfa0af6436b4a71/pkg/security/x509.go#L285)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

In my opinion we should use a distinct template for the tenant signing key, rather than reusing the generate template code. We need to store very little information in the certificate, something like this would be sufficient:

```golang
template := &x509.Certificate{
		Subject: pkix.Name{
			CommonName: fmt.Sprintf("Tenant %d Token Signing Certificate", tenantID),
		},
		SerialNumber:          big.NewInt(1), // The serial number does not matter because we are not using a certificate authority and replace this certificate with a new certificate.
		BasicConstraintsValid: true,
		IsCA:                  false, // This certificate CANNOT sign other certificates.
		PublicKey:             publicKey,
		NotAfter:              time.Now().Add(lifetime),
		KeyUsage:              x509.KeyUsageDigitalSignature, // This certificate can ONLY make signatures.
	}
```
</blockquote></details>

oh, nice, happy to simplify this
___
*[pkg/security/certs_tenant_test.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-Mt9D5IB2VHNp18nMstu:-Mt9Uo5t05_JCTL2l9Fx:be96n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a7c039d6cad2d3f9185a6adcfa0af6436b4a71/pkg/security/certs_tenant_test.go#L162)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Rather than interacting with the `ParsedCertificates`, could we use the CheckSignature function?

```golang
	err = certActual.CheckSignature(x509.PureEd25519, payload, signature)
	require.NoError(t, err)
```
</blockquote></details>

nice, this seems like a better way (i still had to access `ParsedCertificates[0]`, but maybe i'm missing something from your suggestion

**Review by knz — APPROVED** [review]
I like this. Just a nit and this is good to go from my perspective (but I'll let Catherine approve).

> Reviewed 7 of 37 files at r1, 3 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-:-Mt9Y8lo4dwAZyNVMSXz:b-p6oap7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach and @rafiss)

___
*[pkg/cli/mt_cert.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-Mt9Xh0K0FOh3r-TJmyB:-Mt9Xh0K0FOh3r-TJmyC:b-r5zil4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d06d94d52135ef095e6ad1939330b0120defcd0/pkg/cli/mt_cert.go#L126)):*
> ```Go
> If --overwrite is true, any existing files are overwritten.
> `,
> 	Args: cobra.MinimumNArgs(1),
> ```

ExactArgs?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74646)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach and @knz)

___
*[pkg/cli/mt_cert.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-Mt9Xh0K0FOh3r-TJmyB:-Mt9_bR2A3aFghs9mNtF:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d06d94d52135ef095e6ad1939330b0120defcd0/pkg/cli/mt_cert.go#L126)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ExactArgs?
</blockquote></details>

fixed

**Review by catj-cockroach — APPROVED** [review]
> Reviewed 2 of 37 files at r1, 26 of 27 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74646)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/security/certs_tenant_test.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74646#-Mt9D5IB2VHNp18nMstu:-MtE3Zby1Cv0dP-3DNby:b-dn1io1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a7c039d6cad2d3f9185a6adcfa0af6436b4a71/pkg/security/certs_tenant_test.go#L162)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice, this seems like a better way (i still had to access `ParsedCertificates[0]`, but maybe i'm missing something from your suggestion
</blockquote></details>

Ahhh, I thought `signingCert` was an x509.Certificate. In this case, i might throw a `require.Len(t, signingCert.ParsedCertificates, 1)` in there but other than that looks good to me!

**Comment by rafiss** [comment]
tftr!

bors r=knz,catj-cockroach

**Pull request merged**
