### PR TITLE
sql: also support SET DEFAULT_TRANSACTION_ISOLATION.

### LINKED ISSUE #10032: Changing isolation level with psycopg2 doesn't work
AKA: Consider supporting `SET default_transaction_isolation` in the postgresql wire API.

Calling [`set_isolation_level`](http://initd.org/psycopg/docs/connection.html#connection.set_isolation_level) to change the isolation level of a psycopg2 connection to cockroach fails with this error: `ERROR: unknown variable: "DEFAULT_TRANSACTION_ISOLATION"`.  That happens because psycopg2 sends `SET default_transaction_isolation TO '<the isolation level>'` but cockroach doesn't support that syntax in the postgres wire API (it does in the CLI).

The easiest way to reproduce this it to connect to a cockroach server using `psql` (`psql postgres://localhost:26257`) and executing the command at the prompt, e.g. `SET default_transaction_isolation TO 'serializable'`.

Note: the problem only shows up via psycopg2 if you set the isolation level to something other than the default, i.e. `ISOLATION_LEVEL_READ_UNCOMMITTED` or `ISOLATION_LEVEL_READ_COMMITTED` because psycopg2 won't send the command if the isolation level doesn't need to change.

### PR DESCRIPTION
**Pull request by knz**
Required by psycopg2.

Fixes #10032.

@alamaison can you please also run a quick check that this fix indeed solves your problem. I don't have a psycopg2 client ready to test this. (But I did test using `psql` as you suggested.)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10087)

### CODE REVIEW

**Comment by alamaison** [comment]
I'll try to test the fix.  I've never compiled cockroach before so please bear with me

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/testdata/txn, line 426 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10087#-KUSyiEQz01F5wtiXi79-r1-426:-KUT0GI8cty_XPpSweyo:bjzsuus) ([raw file](https://github.com/cockroachdb/cockroach/blob/e012753c8ce5cd6af4448e9d2391bb50ca299489/pkg/sql/testdata/txn#L426)):*
<details><summary><i>Previously, alamaison wrote…</i></summary>
> It might be a good idea to keep testing both variants.
</details>
I concur.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10087)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/testdata/txn, line 426 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10087#-KUSyiEQz01F5wtiXi79-r1-426:-KUTJuHssw4OaMZ6tGJY:b-nq9c3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e012753c8ce5cd6af4448e9d2391bb50ca299489/pkg/sql/testdata/txn#L426)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I concur.
</details>
Please check the 30 lines above this snippet. The test for the previous variant is still there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10087)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10087#-:-KUTWNiPxTDZB_PLeI-m:bnfp4nl)*

**Comment by alamaison** [comment]
I confirm this PR fixed it.  I can change isolation level using psycopg2 now.

**Comment by knz** [comment]
nice, glad it helped.

**Pull request merged**
