### PR TITLE
opt: fix comment for GenerateLocalityOptimizedScan

### LINKED ISSUE #94427: opt: fix comment in GenerateLocalityOptimizedScan doc
This comment is out-of-date: https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/opt/xform/rules/scan.opt#L17-L21

We now plan locality-optimized scans in more cases, such as limited scans.

Jira issue: CRDB-22887

### PR DESCRIPTION
**Pull request by mgartner**
Fixes #94427

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Thanks for fixing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-:-NwublwJ0KvrYVEeJtGw:b-whxd1j)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/xform/rules/scan.opt` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-NwubCiq51vCoi4U4cG6:-NwubCiq51vCoi4U4cG7:b6iacz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/db601ae8754d6a30e4ce603230195864567f3fe6/pkg/sql/opt/xform/rules/scan.opt#L19)):*
> ```
> # LocalityOptimizedSearch can be planned under the following conditions:
> #  - A hard limit or known maximum cardinality of the original scan could be
> #    satisfied by a local-only scan. Thus, locality optimized search typically
> ```

why local only? is this related to the kv batch size? I think this is written in a slightly confusing manner.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/xform/rules/scan.opt` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-NwubCiq51vCoi4U4cG6:-NwunXDw8uJQTlU3np6J:b-q3mk4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/db601ae8754d6a30e4ce603230195864567f3fe6/pkg/sql/opt/xform/rules/scan.opt#L19)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why local only? is this related to the kv batch size? I think this is written in a slightly confusing manner.
</blockquote></details>

I was parroting the comments here:

https://github.com/cockroachdb/cockroach/blob/452a2de1fb99885b74cd590b72c912e76f25f360/pkg/sql/opt/xform/scan_funcs.go#L235-L237

and here:

https://github.com/cockroachdb/cockroach/blob/452a2de1fb99885b74cd590b72c912e76f25f360/pkg/sql/opt/xform/scan_funcs.go#L242-L248

I'll try rewriting this to make it more clear.

**Comment by rytaft** [comment]
*[`pkg/sql/opt/xform/rules/scan.opt` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-NwubCiq51vCoi4U4cG6:-Nwv-amnA3rx8STuOo6X:b-8df0ma) ([raw file](https://github.com/cockroachdb/cockroach/blob/db601ae8754d6a30e4ce603230195864567f3fe6/pkg/sql/opt/xform/rules/scan.opt#L19)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I was parroting the comments here:

https://github.com/cockroachdb/cockroach/blob/452a2de1fb99885b74cd590b72c912e76f25f360/pkg/sql/opt/xform/scan_funcs.go#L235-L237

and here:

https://github.com/cockroachdb/cockroach/blob/452a2de1fb99885b74cd590b72c912e76f25f360/pkg/sql/opt/xform/scan_funcs.go#L242-L248

I'll try rewriting this to make it more clear.
</blockquote></details>

Thanks -- I realize my knowledge on this topic is now a bit stale (both of those comments were written while I was on leave in the fall).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123472)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

___
*[`pkg/sql/opt/xform/rules/scan.opt` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-NwubCiq51vCoi4U4cG6:-O26AzknDRzz9RVwYxC3:b-x5o7my) ([raw file](https://github.com/cockroachdb/cockroach/blob/db601ae8754d6a30e4ce603230195864567f3fe6/pkg/sql/opt/xform/rules/scan.opt#L19)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Thanks -- I realize my knowledge on this topic is now a bit stale (both of those comments were written while I was on leave in the fall).
</blockquote></details>

Updated this, PTAL!

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123472)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/xform/rules/scan.opt` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-O27IL3xANt8Tht2peDH:-O27IL3y5I3lBLGXy2XD:b-6ghj2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffcb0df839bc0caf52e5db2ca6dea4f5aa50ca5/pkg/sql/opt/xform/rules/scan.opt#L29)):*
[nit] Typos in `localitly` and `searhc`

>If either of these conditions are not met

Shouldn't this be `If both of these conditions are not met`? Since either one is sufficient for the locality optimized scan to be useful, if I'm reading the comment above correctly. It might be simpler to reverse this line and say 
```
If one of these conditions is met, then the scan may be satisfied with only the local spans, so there is benefit to using locality-optimized search.
```

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123472)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/xform/rules/scan.opt` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-O27IL3xANt8Tht2peDH:-O27nc_z9x4l_fIKw2eh:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffcb0df839bc0caf52e5db2ca6dea4f5aa50ca5/pkg/sql/opt/xform/rules/scan.opt#L29)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Typos in `localitly` and `searhc`

>If either of these conditions are not met

Shouldn't this be `If both of these conditions are not met`? Since either one is sufficient for the locality optimized scan to be useful, if I'm reading the comment above correctly. It might be simpler to reverse this line and say 
```
If one of these conditions is met, then the scan may be satisfied with only the local spans, so there is benefit to using locality-optimized search.
```
</blockquote></details>

+1

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123472)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/xform/rules/scan.opt` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-O27IL3xANt8Tht2peDH:-O2jtMUeDrZodX-9NV7G:b-o7vuhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffcb0df839bc0caf52e5db2ca6dea4f5aa50ca5/pkg/sql/opt/xform/rules/scan.opt#L29)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Good catch! Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123472#-:-O2k4HL_BKTKsAIjc3l7:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
