### PR TITLE
roachtest: add `failover` variants for replica deadlocks

### LINKED ISSUE #103192: roachtest: `failover` variant with replica deadlocks
We should have a `failover` variant where either one of more replicas on a single node deadlock. We can possibly use a UNIX signal to trigger the deadlock.

Jira issue: CRDB-27879

Epic CRDB-25212

### PR DESCRIPTION
**Pull request by erikgrinaker**
**builtins: add `crdb_internal.unsafe_lock_replica()`**

This patch adds `crdb_internal.unsafe_lock_replica()` which can be used to (un)lock a given replica mutex on the gateway node. It requires the env var `COCKROACH_ENABLE_UNSAFE_TEST_BUILTINS=true`. This is useful to test replica deadlocks or stalls in end-to-end resiliency tests.
  
**roachtest: add `failover` variants for replica deadlocks**

This patch adds `failover` variants that benchmark the pMax unavailability when 5 random leaseholder replicas are deadlocked on a node. The node remains alive, and continues to heartbeat both via liveness and RPC, as do other replicas on the node. The deadlocked replicas will be entirely unresponsive however, and depending on the timing this can also cause deadlocks on other mutexes.

This failure mode is representative of all failure modes that leave a replica unresponsive. This includes disk stalls, which will also hold replica locks during the stall, but disk stalls have specialized handling in e.g. Pebble and during node heartbeats that eventually resolve them while deadlocks don't.

We currently don't handle this failure mode at all, and expect permanent unavailability.

Resolves #103192.
Epic: none
Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
I'm concerned this is too powerful and dangerous to put into a release. What if a serverless cluster customer calls `crdb_internal.unsafe_lock_replica` on range 1 or 2. This will topple the entire cluster in most cases. 

At a minimum, this should be protected behind a config flag if enabled, but it might be better to require an environment variable to be set `SQL_ENABLE_UNSAFE_TESTING` or something similar (so that we don't need a new flag for everything like this). I definitely see the value in this and can think of other things that could also fall into this category. 

If we didn't have serverless I'd be less worried, but its still not ideal.

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
See comment - This should be put behind a config / env flag.

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
See comment - This should be put behind a config / env flag.

**Comment by erikgrinaker** [comment]
We already have far more powerful functions, see e.g. `crdb_internal.force_panic()` and `crdb_internal.unsafe_upsert_descriptor()`. 

I'm assuming `HasAdminRole()` deals with the serverless case -- I just cargo-culted this from some other functions, but it'd be worth confirming this with someone. Perhaps @knz knows.

**Comment by erikgrinaker** [comment]
(that's not to say that I object to an envvar, just that there's existing precedence here and admin users can already irrecoverably wreck a cluster in all sorts of ways)

**Comment by erikgrinaker** [comment]
Ah, the `StoresIterator` interface can't be used in multitenant anyway:

https://github.com/cockroachdb/cockroach/blob/e241a2ebff7efc6d1b511127ae111c6e051f3b2c/pkg/server/tenant.go#L1193-L1194

```
> select crdb_internal.unsafe_lock_replica(1, true);
ERROR: crdb_internal.unsafe_lock_replica(): unimplemented: operation is unsupported in multi-tenancy mode
SQLSTATE: 0A000
```

**Comment by erikgrinaker** [comment]
See discussion in [Slack](https://cockroachlabs.slack.com/archives/C02HWA24541/p1684487663922369), will add an envvar.

**Comment by erikgrinaker** [comment]
Added `COCKROACH_ENABLE_UNSAFE_TEST_BUILTINS`.

**Review by andrewbaptist — COMMENTED** [review]
:lgtm: I added a nit, but you can ignore it (or take parts of it). This is useful enough as it is, and we can change the behavior later if needed.

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103261#-:-NW8hB_y-QU3ap769LPb:b-rybv7d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker, @herkolategan, @pavelkalinnikov, and @srosenberg)

___
*[`pkg/sql/sem/builtins/builtins.go` line 6330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103261#-NW8fOHIACKZeqo_Dfai:-NW8fOHIACKZeqo_Dfaj:b-ihatw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1814235490b14117aec365520bfe0f6c3de96eb7/pkg/sql/sem/builtins/builtins.go#L6330)):*
> ```Go
> 					// We do TryLock() as a best-effort guard against this, but it will be
> 					// racey. The caller is expected to have locked the mutex first.
> 					replicaMu.TryLock()
> ```

nit: Add a log message here if it was not already locked (TryLock returns true). Basically just to note that the unlock command was a no-op. 

It might also be worth considering returning true/false from this method based on whether it did something. It seems incorrect to have the SQL request making the call to `crdb_internal.unsafe_lock_replica` to ever deadlock. I think it would be preferable to also have that call `TryLock` and return a boolean based on whether that did anything.  So the changed behavior would now be:
`crdb_internal.unsafe_lock_replica` never blocks
If already locked, and lock is called, then it returns `false` (didn't do anything). 
If not locked and lock is called, then return `true` - it acquired the lock

If already locked and unlock is called, then it returns `true` (unlocked it). 
If not locked and unlock is called, then it returns `false` (didn't do anything).

The one problem with this is that if you are contending with someone else on the lock case, it would require the "outside" caller to busy loop to lock, but this is probably better than having this call itself deadlock.

This is all somewhat theoretical since we are trying to simulate something that isn't exactly clear, but since we are adding this, it seems like it would be a bit more powerful and safer.

**Review by erikgrinaker — COMMENTED** [review]
Thanks! Will need a :heavy_check_mark:.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103261#-:-NW8lbRkDtBA1i3xW5BE:b-riaita)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @pavelkalinnikov, and @srosenberg)

___
*[`pkg/sql/sem/builtins/builtins.go` line 6330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103261#-NW8fOHIACKZeqo_Dfai:-NW8j6aT8XO6pcppG_zL:b-ltjgcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1814235490b14117aec365520bfe0f6c3de96eb7/pkg/sql/sem/builtins/builtins.go#L6330)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Add a log message here if it was not already locked (TryLock returns true). Basically just to note that the unlock command was a no-op. 

It might also be worth considering returning true/false from this method based on whether it did something. It seems incorrect to have the SQL request making the call to `crdb_internal.unsafe_lock_replica` to ever deadlock. I think it would be preferable to also have that call `TryLock` and return a boolean based on whether that did anything.  So the changed behavior would now be:
`crdb_internal.unsafe_lock_replica` never blocks
If already locked, and lock is called, then it returns `false` (didn't do anything). 
If not locked and lock is called, then return `true` - it acquired the lock

If already locked and unlock is called, then it returns `true` (unlocked it). 
If not locked and unlock is called, then it returns `false` (didn't do anything).

The one problem with this is that if you are contending with someone else on the lock case, it would require the "outside" caller to busy loop to lock, but this is probably better than having this call itself deadlock.

This is all somewhat theoretical since we are trying to simulate something that isn't exactly clear, but since we are adding this, it seems like it would be a bit more powerful and safer. 
</blockquote></details>

There's no benefit in overengineering this. The only (probably ever) caller wants to wait until it acquires the lock, isn't going to deadlock itself, and doesn't care about the returned value. The only reason I even added the `TryLock()` call was as an extremely cheap best-effort guard against crashing the node, but we don't really need it, especially now that it's guarded by an environment variable. If we ever need something else, we can change it then.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

**Pull request merged**
