### PR TITLE
scripts: add helper to restore vendor submodule after glide replacement

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11689)

### CODE REVIEW

**Comment by tamird** [comment]
this is now duplicating functionality from glide-up.sh. Combine the two, somehow?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[scripts/fix-vendor-submodule.sh, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11689#-KXlLWtOC6qAxbFtfHrD:-KXlLWtPcDs1PN3G6BHy:b6rf2wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da21a7eaa3cd33814abb4b090c8d96245c45191/scripts/fix-vendor-submodule.sh#L11)):*
> ```Shell
> #
> # This script restores the .git submodule pointer and then the README.
> echo "gitdir: ../.git/modules/vendor" > vendor/.git
> ```

single quotes

---

*[scripts/fix-vendor-submodule.sh, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11689#-KXlLX_Muq-ELPZfkbyg:-KXlLX_Muq-ELPZfkbyh:b-4yr6dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da21a7eaa3cd33814abb4b090c8d96245c45191/scripts/fix-vendor-submodule.sh#L12)):*
> ```Shell
> # This script restores the .git submodule pointer and then the README.
> echo "gitdir: ../.git/modules/vendor" > vendor/.git
> git -C vendor checkout README.md
> ```

newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11689#-:-KXlLOqF4qAvQGQ3igBL:b-sco2ux)*

**Comment by dt** [comment]
I wanted a more general helper than just `glide up`, but wouldn't the "combined" script just be `glide up && ./scripts/fix-vendor-submodule.sh` ? Is that worth checking in? 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[scripts/fix-vendor-submodule.sh, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11689#-KXlLWtOC6qAxbFtfHrD:-KXlO3bLdNlxGT6ierRL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da21a7eaa3cd33814abb4b090c8d96245c45191/scripts/fix-vendor-submodule.sh#L11)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

single quotes
</blockquote></details>

Done.

---

*[scripts/fix-vendor-submodule.sh, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11689#-KXlLX_Muq-ELPZfkbyg:-KXlO4HWbnxuzrKynegk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da21a7eaa3cd33814abb4b090c8d96245c45191/scripts/fix-vendor-submodule.sh#L12)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11689#-:-KXlOEPGS-reSw7EtuyC:berxmsj)*

**Comment by tamird** [comment]
Either it's worth checking in or it isn't, you're currently leaving checked in the `glide-up.sh` script which is either duplicative with this or completely redundant.

Btw, on a local branch I have the following change:
```
commit 5f03d9c44019bbe22b177193b8dc5f881cccf65e
Author: Tamir Duberstein <tamird@gmail.com>
Date:   Thu Nov 24 17:10:59 2016 -0500

    scripts: improve glide-up

diff --git a/scripts/glide-up.sh b/scripts/glide-up.sh
index 59d0e4e..f1db78c 100755
--- a/scripts/glide-up.sh
+++ b/scripts/glide-up.sh
@@ -2,7 +2,9 @@
 
 set -euxo pipefail
 
-mv vendor/.git vendorgit && \
-glide up && \
-mv vendorgit vendor/.git && \
-git -C vendor checkout README.md
+mv vendor/.git vendorgit
+function finish() {
+  mv vendorgit vendor/.git && git -C vendor checkout README.md
+}
+trap finish EXIT
+glide up "$@"

```
So it's not quite as trivial as you say.

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11689#-:-KXlL_P95JRdt7MavzQM:bcv3qyi)*

**Comment by dt** [comment]
k, I'll leave glide-up.sh alone and just put this one in my bash aliases.

**Pull request closed without merging**
