### PR TITLE
storage: do not mutate ba.Requests in optimizePuts and executeWriteBatch

### PR DESCRIPTION
**Pull request by tbg**
This fixes a source of data races in the experimental proposer-evaluated KV
PR #10327.

Updated `TestOptimizePuts` so that prior to the fix, it failed with

```
--- FAIL: TestOptimizePuts (0.01s)
      	replica_test.go:1522: 2: optimizePuts mutated the original
request
       slice: [[0].Put.Blind: false != true [1].Put.Blind: false != true
       [2].Put.Blind: false != true [3].Put.Blind: false != true
       [4].Put.Blind: false != true [5].Put.Blind: false != true
       [6].Put.Blind: false != true [7].Put.Blind: false != true
       [8].Put.Blind: false != true [9].Put.Blind: false != true]
```

storage: don't mutate caller's transaction in executeWriteBatch

    With proposer-evaluated Raft, this would mutate the caller's transaction
    proto, with unclear (but definitely bad) implications.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10419)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 3422 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb-X-QbHZVrXHWQWIj:-KVb-X-QbHZVrXHWQWIk:bjc14c) ([raw file](https://github.com/cockroachdb/cockroach/blob/68601cffad71f9dd6568b974ac88756fe49531df/pkg/storage/replica.go#L3422)):*
> ```Go
> ) (*roachpb.BatchResponse, ProposalData, *roachpb.Error) {
> 	br := ba.CreateReply()
> 	if ba.Txn != nil {
> ```

can you move this closer to the site of the mutation? the comment is also not correct, the following code appears below:
```
ba.Txn.Timestamp.Forward(tErr.ActualTimestamp)
ba.Txn.WriteTooOld = true`
```

---

*[pkg/storage/replica.go, line 3389 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb0n2ilvnV4utNZSkp:-KVb0n2ilvnV4utNZSkq:b-90rtyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3389)):*
> ```Go
> 	}
> 
> 	if len(reqs) < optimizePutThreshold { // don't bother if below this threshold
> ```

so the caller checks this too? NYC but let's remove one of the checks

---

*[pkg/storage/replica.go, line 3407 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb0Pfvf0fsdG1e2cb9:-KVb0Pfvf0fsdG1e2cbA:b-eprzb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3407)):*
> ```Go
> 	// keyspace to "blindly" put values.
> 	newReqs := append([]roachpb.RequestUnion(nil), origReqs...)
> 	for i := range reqs {
> ```

this is pretty awkward; you now have `reqs`, `origReqs`, and `newReqs` all in scope. AFAICT, there is no need for `origReqs`.

Also, should this iterate over `newReqs` instead of `reqs`? I think that would be less surprising

---

*[pkg/storage/replica.go, line 3414 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb1Mbzt0aR9h7NagkD:-KVb1Mbzt0aR9h7NagkE:b79kqwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3414)):*
> ```Go
> 				shallow := *t
> 				shallow.Blind = true
> 				(&newReqs[i]).MustSetInner(&shallow)
> ```

there's no need for this bizarre construction; `slice[i].method()` does exactly the same thing

---

*[pkg/storage/replica.go, line 3418 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb1PXNPSUPdF-hB_4T:-KVb1PXNPSUPdF-hB_4U:b79kqwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3418)):*
> ```Go
> 				shallow := *t
> 				shallow.Blind = true
> 				(&newReqs[i]).MustSetInner(&shallow)
> ```

there's no need for this bizarre construction; `slice[i].method()` does exactly the same thing

---

*[pkg/storage/replica_test.go, line 1515 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb0ynhNKaCQ87u1Khl:-KVb0ynhNKaCQ87u1Khm:b79kqwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica_test.go#L1515)):*
> ```Go
> 		for i := range goldenRequests {
> 			clone := protoutil.Clone(goldenRequests[i].GetInner()).(roachpb.Request)
> 			(&goldenRequests[i]).MustSetInner(clone)
> ```

there's no need for this bizarre construction; `slice[i].method()` does exactly the same thing

---

*[pkg/storage/replica_test.go, line 1517 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb17ZYSCCoJbfJzYEy:-KVb17ZZVc8NwICbcQlL:b-q64sbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica_test.go#L1517)):*
> ```Go
> 			(&goldenRequests[i]).MustSetInner(clone)
> 		}
> 		oldRequests := batch.Requests
> ```

add a comment explaining why this doesn't do:
```
newRequests := optimizePuts(...)
compare(newRequests, batch.Requests)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-:-KVb1T_y_5wPC8YEK1ak:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 3422 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb-X-QbHZVrXHWQWIj:-KVbE1aMlurhElghffUM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68601cffad71f9dd6568b974ac88756fe49531df/pkg/storage/replica.go#L3422)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you move this closer to the site of the mutation? the comment is also not correct, the following code appears below:
> ```
> ba.Txn.Timestamp.Forward(tErr.ActualTimestamp)
> ba.Txn.WriteTooOld = true`
> ```
</details>
Done.

---

*[pkg/storage/replica.go, line 3389 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb0n2ilvnV4utNZSkp:-KVbEzNchktzLbW6ZN-M:bsrzrty) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3389)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> so the caller checks this too? NYC but let's remove one of the checks
</details>
These are not the same checks. `optimizePuts` always does work even if it decides not to optimize. Moving it in here can only be worse (though I don't know if it will measure). Won't touch this here.

---

*[pkg/storage/replica.go, line 3407 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb0Pfvf0fsdG1e2cb9:-KVbD6g53-QtwZsxnLuc:b-ufclpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3407)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is pretty awkward; you now have `reqs`, `origReqs`, and `newReqs` all in scope. AFAICT, there is no need for `origReqs`.
> 
> Also, should this iterate over `newReqs` instead of `reqs`? I think that would be less surprising
</details>
`origReqs` is that which you clone. `reqs` is somewhat redundant; could just track the `i` such that `reqs == origReqs[:i]`. The iteration is supposed to be over `reqs` which is all the requests we have to mutate. We don't want to mutate all of them (which is what you'd get if you iterated over `newReqs`, except that you'd probably hit the fatal path in practice).
Removed `newReqs`, PTAL.

---

*[pkg/storage/replica.go, line 3414 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb1Mbzt0aR9h7NagkD:-KVbDYdubl2LMoca91_R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3414)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's no need for this bizarre construction; `slice[i].method()` does exactly the same thing
</details>
Done.

---

*[pkg/storage/replica.go, line 3418 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb1PXNPSUPdF-hB_4T:-KVbDZ2aoJZjMkM9oXof:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica.go#L3418)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's no need for this bizarre construction; `slice[i].method()` does exactly the same thing
</details>
Done.

---

*[pkg/storage/replica_test.go, line 1515 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb0ynhNKaCQ87u1Khl:-KVbE6zS4_mM8NRUoGFD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica_test.go#L1515)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's no need for this bizarre construction; `slice[i].method()` does exactly the same thing
</details>
Done.

---

*[pkg/storage/replica_test.go, line 1517 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVb17ZYSCCoJbfJzYEy:-KVbEbYWbR34D93EnWA3:b-pyzydj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7372926c30125237934dd0c9a89f0e229ebbfd0/pkg/storage/replica_test.go#L1517)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> add a comment explaining why this doesn't do:
> ```
> newRequests := optimizePuts(...)
> compare(newRequests, batch.Requests)
> ```
</details>
Done. (?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419)*

**Comment by tschottdorf** [comment]
TFTR, probably want to give this another quick look @tamird.

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-:-KVbGZ62Th_2hqdyfgwf:bi2vurs)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_test.go, line 6347 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-KVbtFKARmx2JWRdYwr9:-KVbtFKARmx2JWRdYwrA:bfrytaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab872170f16c7e0065146fdd42358d1f63c72b78/pkg/storage/replica_test.go#L6347)):*
> ```Go
> 
> 	batch, _, _, _, pErr := tc.rng.executeWriteBatch(ctx, makeIDKey(), ba)
> 	defer batch.Close()
> ```

heh, that'll be an assert alright

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10419#-:-KVdH0XJYnPzJ7NWfW9J:bnfp4nl)*

**Pull request merged**
