### PR TITLE
Set --scan-max-idle-time=200ms in order to speed up range replication.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. Does this allow use to reduce the test timeout?

**Comment by bdarnell** [comment]
Spencer wants to get rid of these flags. It might be better to fix this by giving the replication queue a kick whenever a new node is discovered in gossip.

**Comment by petermattis** [comment]
@bdarnell I consider this flag and setting its value here a temporary hack.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
