### PR TITLE
kv: remove Txn.ManualRefresh

### PR DESCRIPTION
**Pull request by nvb**
`Txn.ManualRefresh` was added in 91352871 as part of #60567. In df1c620d, we stopped using it in range merge transactions. This commit removes the API to eliminate complexity from the TxnCoordSender.

Epic: None
Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101778#-:-NTKpAJn0G4LHudV8A_p:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=arulajmani

**Comment by nvanbenschoten** [comment]
Unrelated flake.

bors r=arulajmani

**Comment by nvanbenschoten** [comment]
Flaky `acceptance/version-upgrade`.

bors r=arulajmani

**Pull request merged**
