### PR TITLE
Document the ContainerRemove hack in retryingDockerClient

### LINKED ISSUE #5612: sql: pgwire timestamp parsing
[`cockroachdb/pq.formatTs`](https://github.com/cockroachdb/pq/blob/master/encode.go#L436) formats timestamps for the wire using `time.RFC3339Nano`. But [`cockroachdb/pq.ParseTimestamp`](https://github.com/cockroachdb/pq/blob/master/encode.go#L339) cannot parse such timestamps. We need to figure out why the discrepancy. Does postgres send back non-RFC3339 timestamps on the wire?

### LINKED ISSUE #5734: acceptance/cluster: verify "No such container" behavior for ContainerRemove
`resilientDockerClient.ContainerRemove` silently ignores errors containing the string `No such container`. Is this hack necessary? Per PR feedback: either document the need for the hack in a comment or remove.

### PR DESCRIPTION
**Pull request by danhhz**
Closes #5734.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5850)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/cluster/docker.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5850#-KEXX4wzEtKA28XTeYYI:-KEXX4wzEtKA28XTeYYJ:1322485072) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c43573eddef296d4d86b8c8ba017654da279e6d/acceptance/cluster/docker.go#L403)):*
I realized this was because of retries, so it should be in `retryingDockerClient` instead of `resilientDockerClient`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5850)*

**Comment by bdarnell** [comment]
I don't think that's the bug number you meant to link to, but LGTM

**Comment by petermattis** [comment]
LGTM

**Comment by paperstreet** [comment]
Indeed. Bug number fixed.

**Comment by tamird** [comment]
LGTM modulo closing the associated issue. That issue was about the hammer we're using here to nuke all the containers when creating a new one; has that been verified to occur in practice? under what circumstances does it occur?

**Comment by tschottdorf** [comment]
It definitely happens. In most cases I've seen  the command which gets
stuck does execute.

**Comment by paperstreet** [comment]
I'm a little confused. IIUC https://github.com/cockroachdb/cockroach/issues/5734 was about the "No such container" error that happens when you try to delete a container that doesn't exist, which happens often during retries of ContainerRemove. Are you talking about something else?

**Comment by tamird** [comment]
I'm talking about "retries" of ContainerRemove happening during retries of
ContainerCreate, because ContainerCreate is trying to ContainerRemove
aggressively.

**Comment by paperstreet** [comment]
At the very least, the timeout that was introduced in my original PR can cause a container to be created, but with the timeout error returned. This will cause a retry that will fail because the container exists.

I also suspect that most of the time we were seeing these errors in circleci, the request would do what it was supposed to but never return. If I'm right, this will handle when that happens to ContainerCreate.

**Comment by tamird** [comment]
>  If I'm right, this will handle when that happens to ContainerCreate.

Yeah, I agree. That's the point of my original comment though - the
associated issue was about figuring out if this hypothesis is true or not.

**Pull request merged**
