### PR TITLE
rowcontainer: move row containers to their own package

### PR DESCRIPTION
**Pull request by asubiotto**
Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Great idea! Make sure to coordinate the order of this and #34092 with @yuzefovich though.

**Comment by asubiotto** [comment]
Yep, was thinking of letting that get in first

**Comment by asubiotto** [comment]
RFAL

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 68 of 68 files at r1, 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34164#-:-LXQtGDf6UI6MIodTiZ9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsql_running.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34164#-LXQr_Gq4BWeMOUsjn1F:-LXQr_Gq4BWeMOUsjn1G:bg5fk5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/85676531eb1b08647d4b321145291e0913360e9b/pkg/sql/distsql_running.go#L38)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/mon"
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	opentracing "github.com/opentracing/opentracing-go"
> ```

[nit]: do we need the first word?
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34164#-LXQssUdCqg3It61AOWG:-LXQssUdCqg3It61AOWH:bkfixh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/85676531eb1b08647d4b321145291e0913360e9b/pkg/sql/rowcontainer/hash_row_container.go#L204)):*
> ```Go
> 
> // MakeHashMemRowContainer creates a HashMemRowContainer from the given
> // rowContainer. This rowContainer must still be Close()d by the caller.
> ```

[nit]: this comment probably needs amending since my change deviated from it.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34164)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34164#-LXQr_Gq4BWeMOUsjn1F:-LXUeu0XEBWbSCaGUjY0:b-mftmwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/85676531eb1b08647d4b321145291e0913360e9b/pkg/sql/distsql_running.go#L38)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: do we need the first word?
</blockquote></details>

No. Unfortunately this is not consistent across the codebase. Will leave as is though since this PR doesn't change this.
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34164#-LXQssUdCqg3It61AOWG:-LXUfEtR2LEzVg9szSup:b-y0iph5) ([raw file](https://github.com/cockroachdb/cockroach/blob/85676531eb1b08647d4b321145291e0913360e9b/pkg/sql/rowcontainer/hash_row_container.go#L204)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: this comment probably needs amending since my change deviated from it.
</blockquote></details>

Will make a followup PR for this.

**Comment by asubiotto** [comment]
Fixed some lint failures

bors r+

**Pull request merged**
