### PR TITLE
sql: add fullStatisticsID column to system.table_statistics

### PR DESCRIPTION
**Pull request by faizaanmadhani**
This commit adds a column to system.table_statistics used by partial statistics to store an id that references the full statistic that the partial statistics was derived from. For full statistics, the value in this column will be NULL.

This commit updates a migration/upgrade that just included the partialPredicate column.

Epic: CRDB-19449

Release note (sql change): system.table_statistics now contains a column called fullStatisticsID to store an id referencing the full table statistic the partial statistic was derived from.

### CODE REVIEW

**Comment by faizaanmadhani** [comment]
I just wanted draw attention that the histogram_id and the statistics_id are the same, so for the purposes of testing and making sure that the partial statistic shown contains the statistics_id of the full statistic it was derived from, we can just use that as we currently do not include statistics_id as an output column in the output of show_statistics.

**Review by michae2 — COMMENTED** [review]
Thank you for staying up late to do this! I really appreciate that you worked hard to make this feature extra safe. This will definitely help me sleep better at night when I'm on call. :slightly_smiling_face:

> Reviewed 12 of 16 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-:-NJRMPlsEIcRgY-Ey8-B:basjhqj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/alter_table.go` line 1352 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRCEEXCSvxqFcPJzj6:-NJRCEEXCSvxqFcPJzj7:b-whiwoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/alter_table.go#L1352)):*
> ```Go
> 					histogram,
> 					"partialPredicate",
>           "fullStatisticsID"
> ```

nit: Indentation is off here.
___
*[`pkg/sql/show_stats.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRJ8keEd3JmrnPjm4D:-NJRJ8keEd3JmrnPjm4E:b-27p52g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/show_stats.go#L53)):*
> ```Go
> 	{Name: "avg_size", Typ: types.Int},
> 	{Name: "partial_predicate", Typ: types.String},
> 	{Name: "full_statistics_id", Typ: types.Int},
> ```

bikeshedding: In `SHOW STATISTICS` output instead of "statisticID" we call it "histogram_id", so maybe this should be "full_histogram_id" or "parent_histogram_id" or something like that. And it might be nice to put it after histogram_id.
___
*[`pkg/sql/show_stats.go` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRKDHw2-uLNAGI3jW6:-NJRKDHw2-uLNAGI3jW7:bb0diwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/show_stats.go#L148)):*
> ```Go
> 				avgSizeIdx
> 				partialPredicateIdx
> 				fullStatisticsIdx
> ```

micro-nit: `fullStatisticsIDIdx`
___
*[`pkg/sql/catalog/systemschema/system.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRCstb23hm2XTnCYFH:-NJRCstb23hm2XTnCYFI:bfb4lzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/catalog/systemschema/system.go#L268)):*
> ```Go
> 	"avgSize"            INT8       NOT NULL DEFAULT 0,
> 	"partialPredicate"   STRING,
> 	"fullStatisticsID"    INT8,
> ```

suggestion: If we're going to use `PartialPredicate = ""` and `FullStatisticID = 0` for full statistics in various places, then it might be simpler to make these columns `NOT NULL` and use those sentinel values on disk, too.
___
*[`pkg/sql/stats/new_stat.go` line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRLcjS8474gcYc7zpk:-NJRLcjS8474gcYc7zpl:b-b2xnrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/stats/new_stat.go#L98)):*
> ```Go
> 
> 	if !settings.Version.IsActive(ctx, clusterversion.V23_1AddPartialStatisticsColumns) {
> 		_, err := executor.Exec(
> ```

While we're here, could you add a check that returns an error if `partialPredicate != ""` (as described [in this comment](https://reviewable.io/reviews/cockroachdb/cockroach/91228#-NHb78EYDveTyCS3HLCI))?
___
*[`pkg/sql/stats/new_stat.go` line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRLDsqAn7I32Tuxkxt:-NJRLDsqAn7I32Tuxkxu:b-ru2xoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/stats/new_stat.go#L141)):*
> ```Go
> 					histogram,
> 					"partialPredicate",
>           "fullStatisticsID"
> ```

nit: Indentation is off.
___
*[`pkg/upgrade/upgrades/upgrades.go` line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJR78ug-U_qHLwgH3WB:-NJR78ug-U_qHLwgH3WC:b-6hr78o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/upgrade/upgrades/upgrades.go#L210)):*
> ```Go
> 		descIDSequenceForSystemTenant,
> 	),
> 	upgrade.NewTenantUpgrade("add a partial predicate column to system.table_statistics",
> ```

nit: Would be nice to also change this message.
___
*[`pkg/upgrade/upgrades/alter_table_statistics_partial_predicate_and_id.go` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRAoahC9iB1qp79sGs:-NJRAoahC9iB1qp79sGt:b-68sur1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/upgrade/upgrades/alter_table_statistics_partial_predicate_and_id.go#L26)):*
> ```Go
> ADD COLUMN IF NOT EXISTS "partialPredicate" STRING,
> ADD COLUMN IF NOT EXISTS "fullStatisticsID" INT8
> FAMILY "fam_0_tableID_statisticID_name_columnIDs_createdAt_rowCount_distinctCount_nullCount_histogram"`
> ```

nit: I don't think we need this `FAMILY` part. (This table only has one column family, which these columns will be added to automatically.)



_Code quote:_
```Go
fam_0_tableID_statisticID_name_columnIDs_createdAt_rowCount_distinctCount_nullCount_histogram
```

**Review by mgartner — COMMENTED** [review]
> Reviewed 7 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93751)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani and @rytaft)

___
*[`pkg/sql/stats/table_statistic.proto` line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRVUVHEpnoZMVu-qRO:-NJRVUVHEpnoZMVu-qRP:bke9by4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/stats/table_statistic.proto#L65)):*
> ```protobuf
>   // that it was created from. It is 0 for full statistics which will be
>   // NULL when stored in system.table_statistics.
>   uint64 full_statistics_id = 12 [(gogoproto.customname) = "FullStatisticsID", (gogoproto.nullable) = true];
> ```

So if this will be `0` for full statistics, should `(gogoproto.nullable)` be `false`?

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93751)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani and @rytaft)

___
*[`pkg/sql/catalog/systemschema/system.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRCstb23hm2XTnCYFH:-NJRZhPm27jueJJJnf-E:b-dm4th4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/catalog/systemschema/system.go#L268)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

suggestion: If we're going to use `PartialPredicate = ""` and `FullStatisticID = 0` for full statistics in various places, then it might be simpler to make these columns `NOT NULL` and use those sentinel values on disk, too.
</blockquote></details>

One more bikeshed / nit: the other column is singular ("statisticID" rather than "statisticsID") so could we make this new column singular, to match ("fullStatisticID")?

**Review by faizaanmadhani — COMMENTED** [review]
Thanks for the reviews! I've addressed all the comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-:-NJRi9Pm5t2OSHo32878:be6jyry)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/alter_table.go` line 1352 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRCEEXCSvxqFcPJzj6:-NJRgVE_1Ae04LshHzUZ:b-2czrqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/alter_table.go#L1352)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Indentation is off here.
</blockquote></details>

Fixed! Sorry this keeps happening -- i don't actually see the incorrect indentation in Goland so it's almost guesswork to try to align it correctly.
___
*[`pkg/sql/show_stats.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRJ8keEd3JmrnPjm4D:-NJRgRxq3uxAtMkTNbdE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/show_stats.go#L53)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

bikeshedding: In `SHOW STATISTICS` output instead of "statisticID" we call it "histogram_id", so maybe this should be "full_histogram_id" or "parent_histogram_id" or something like that. And it might be nice to put it after histogram_id.
</blockquote></details>

Done.
___
*[`pkg/sql/show_stats.go` line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRKDHw2-uLNAGI3jW6:-NJRd16q4bAdmTG260KR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/show_stats.go#L148)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

micro-nit: `fullStatisticsIDIdx`
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/systemschema/system.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRCstb23hm2XTnCYFH:-NJRhFdY4JeXpEOosjLm:b-za4hrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/catalog/systemschema/system.go#L268)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

One more bikeshed / nit: the other column is singular ("statisticID" rather than "statisticsID") so could we make this new column singular, to match ("fullStatisticID")?
</blockquote></details>

I still think it would be better to keep the columns as NULL. It's not very complicated to translate between a tree.DNull datum and the value that we need and we do it consistently for other nullable fields (notably histograms -- I think histogram_id is NULL for multi-column statistics but an id for single column statistics, even though no histogram_id would ever be 0). Additionally, from the users perspective, it makes more sense that the column is NULL rather than 0 because 0 may indicate it references to a full statistic even though no statisticID can be 0. 
___
*[`pkg/sql/stats/new_stat.go` line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRLcjS8474gcYc7zpk:-NJRghb3AQbImY0PMTS6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/stats/new_stat.go#L98)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

While we're here, could you add a check that returns an error if `partialPredicate != ""` (as described [in this comment](https://reviewable.io/reviews/cockroachdb/cockroach/91228#-NHb78EYDveTyCS3HLCI))?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/table_statistic.proto` line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRVUVHEpnoZMVu-qRO:-NJRgm558Q96VSULGeAg:bcquwjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/stats/table_statistic.proto#L65)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

So if this will be `0` for full statistics, should `(gogoproto.nullable)` be `false`?
</blockquote></details>

So, we can't make it true because doing so throws this error when running `./dev gen protobuf`.
```
ERROR: field TableStatisticProto.FullStatisticsId is a native type and in proto3 syntax with nullable=false there exists conflicting implementations when encoding zero values--gogoroach_out: protoc-gen-gogoroach: Plugin failed with status code 1.
2022/12/16 15:38:53 error running protoc: exit status 1
```

However, I removed them and I think this is just true by default because it didn't change the resulting generated go file.

**Review by michae2 — CHANGES_REQUESTED** [review]
So close! This is looking great!

> Reviewed 6 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-:-NJRpx6KAIZbYK-w-wnI:b-ep51b7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/alter_table.go` line 1352 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRCEEXCSvxqFcPJzj6:-NJRmTnW-vwtPCE1_QdE:b-58bg55) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/alter_table.go#L1352)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Fixed! Sorry this keeps happening -- i don't actually see the incorrect indentation in Goland so it's almost guesswork to try to align it correctly.
</blockquote></details>

No big deal :slightly_smiling_face: (There might be a Goland setting to highlight tabs vs spaces?)
___
*[`pkg/sql/alter_table.go` line 1364 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRmqslAn0qYYahwZes:-NJRmqslAn0qYYahwZet:bj9wdol) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc73ace1eab33d85e7ab5e8b2cf7773bcf4d1e6d/pkg/sql/alter_table.go#L1364)):*
> ```Go
> 		histogram,
> 		predicateValue,
> 		s.FullStatisticsID,
> ```

Will this sometimes be 0? Do we need to do the same `interface{}` stuff we're doing above for the predicate to insert `NULL`?
___
*[`pkg/sql/show_stats.go` line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRnkWJ9f2iQC2cSqYv:-NJRnkWJ9f2iQC2cSqYw:b-wvfjdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc73ace1eab33d85e7ab5e8b2cf7773bcf4d1e6d/pkg/sql/show_stats.go#L126)):*
> ```Go
> 						  %s
>     				  histogram,
>               %s
> ```

If `partialStatsVerActive` is false, this will leave a trailing comma after `histogram,` which will throw a SQL error. So I think the query needs to be something like `"avgSize", %s histogram %s FROM` and then `fullStatisticIDCol` needs to be something like `,"fullStatisticID"`.

(Also indentation is off here :stuck_out_tongue:)
___
*[`pkg/sql/catalog/systemschema/system.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRCstb23hm2XTnCYFH:-NJRplE-8yiBVXHNMW6M:b-a9oi96) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/catalog/systemschema/system.go#L268)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

I still think it would be better to keep the columns as NULL. It's not very complicated to translate between a tree.DNull datum and the value that we need and we do it consistently for other nullable fields (notably histograms -- I think histogram_id is NULL for multi-column statistics but an id for single column statistics, even though no histogram_id would ever be 0). Additionally, from the users perspective, it makes more sense that the column is NULL rather than 0 because 0 may indicate it references to a full statistic even though no statisticID can be 0. 
</blockquote></details>

:thumbsup: Good points! Never mind.
___
*[`pkg/sql/execinfrapb/processors_table_stats.proto` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRpdicCAOMk6Njiis2:-NJRpdicCAOMk6Njiis3:bjp1415) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc73ace1eab33d85e7ab5e8b2cf7773bcf4d1e6d/pkg/sql/execinfrapb/processors_table_stats.proto#L61)):*
> ```protobuf
>   // statistics. It is the statistic id of the full statistic that this partial
>   // statistic was derived from.
>   optional uint64 full_statistics_id = 8 [(gogoproto.customname) = "FullStatisticsID", (gogoproto.nullable) = false];
> ```

nit: I swear this is the last one, could we also make this one singular to match? :sorry_face:
___
*[`pkg/sql/stats/stats_cache.go` line 769 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRpJMJ20lHVxinq2S7:-NJRpJMJ20lHVxinq2S8:bnu43pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc73ace1eab33d85e7ab5e8b2cf7773bcf4d1e6d/pkg/sql/stats/stats_cache.go#L769)):*
> ```Go
> 	"avgSize",
>   %s
>   histogram,
> ```

Same problem here: I think it needs to be `"avgSize", %s histogram %s FROM` without the comma after histogram, and the comma will need to be added to `fullStatisticIDCol`.
___
*[`pkg/sql/stats/table_statistic.proto` line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRVUVHEpnoZMVu-qRO:-NJRlt6B9rqGgR0N1ZPr:bbjcn6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/stats/table_statistic.proto#L65)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

So, we can't make it true because doing so throws this error when running `./dev gen protobuf`.
```
ERROR: field TableStatisticProto.FullStatisticsId is a native type and in proto3 syntax with nullable=false there exists conflicting implementations when encoding zero values--gogoroach_out: protoc-gen-gogoroach: Plugin failed with status code 1.
2022/12/16 15:38:53 error running protoc: exit status 1
```

However, I removed them and I think this is just true by default because it didn't change the resulting generated go file.
</blockquote></details>

(You might hate me for this) nit: could we also make this one singular? (i.e. "full_statistic_id" and "FullStatisticID" instead of "full_statistics_id" and "FullStatisticsID"). :ducks_flying_shoe:

**Review by faizaanmadhani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93751)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/alter_table.go` line 1364 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRmqslAn0qYYahwZes:-NJS075-DTmBr_rga0U-:b-acqmhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc73ace1eab33d85e7ab5e8b2cf7773bcf4d1e6d/pkg/sql/alter_table.go#L1364)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Will this sometimes be 0? Do we need to do the same `interface{}` stuff we're doing above for the predicate to insert `NULL`?
</blockquote></details>

Yup! Done.
___
*[`pkg/sql/show_stats.go` line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRnkWJ9f2iQC2cSqYv:-NJS4QgZ6Pn4v2d0Y-Tr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc73ace1eab33d85e7ab5e8b2cf7773bcf4d1e6d/pkg/sql/show_stats.go#L126)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If `partialStatsVerActive` is false, this will leave a trailing comma after `histogram,` which will throw a SQL error. So I think the query needs to be something like `"avgSize", %s histogram %s FROM` and then `fullStatisticIDCol` needs to be something like `,"fullStatisticID"`.

(Also indentation is off here :stuck_out_tongue:)
</blockquote></details>

Done.
___
*[`pkg/sql/stats/stats_cache.go` line 769 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRpJMJ20lHVxinq2S7:-NJS4uvr3lN1hU8fabfW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc73ace1eab33d85e7ab5e8b2cf7773bcf4d1e6d/pkg/sql/stats/stats_cache.go#L769)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Same problem here: I think it needs to be `"avgSize", %s histogram %s FROM` without the comma after histogram, and the comma will need to be added to `fullStatisticIDCol`.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/table_statistic.proto` line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-NJRVUVHEpnoZMVu-qRO:-NJS4z0QCZTLaeDRuUC4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6d4f3393c270e43c0f45f6b78067324013ba06/pkg/sql/stats/table_statistic.proto#L65)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

(You might hate me for this) nit: could we also make this one singular? (i.e. "full_statistic_id" and "FullStatisticID" instead of "full_statistics_id" and "FullStatisticsID"). :ducks_flying_shoe:
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice! Thank you!

> Reviewed 2 of 13 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93751#-:-NJS9up2Difd7RvdXGkv:b-o2v16l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

**Comment by faizaanmadhani** [comment]
TFTRs!! 🎉 

bors r=michae2

**Pull request merged**
