### PR TITLE
sql: use a structured error to detect roachpb.BatchTimestampBeforeGCE…

### LINKED ISSUE #50198: sql: specific strings in table data cause job to never terminate
Run the following SQL:

```sql
> CREATE TABLE t AS SELECT 'must be after GC replica threshold' AS x;
> ALTER TABLE t ADD COLUMN y INT AS (x::INT) STORED;
```

Observe: the job remains in status "running" forever

```
root@/defaultdb> show jobs;
-[ RECORD 1 ]
job_id             | 564125022800936961
job_type           | SCHEMA CHANGE
description        | ALTER TABLE defaultdb.public.t ADD COLUMN y INT8 AS (x::INT8) STORED
statement          |
user_name          | root
status             | running
running_status     | populating schema
created            | 2020-06-15 13:28:14.555411+00:00
started            | 2020-06-15 13:28:14.56666+00:00
finished           | NULL
modified           | 2020-06-15 13:30:13.527146+00:00
fraction_completed | 0
error              |
coordinator_id     | 1
```

This bug had been predicted all the way in [this](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md#vulnerability-to-embedded-application-strings) and [that](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md#excessively-loose-coupling) RFC sections. 

The problem is this code in `isPermanentSchemaChangeError()`:

```go
  // Ignore error thrown because of a read at a very old timestamp.
  // The Backfill will grab a new timestamp to read at for the rest
  // of the backfill.
  if strings.Contains(⊙.Error(), "must be after replica GC threshold") {
    return false
  }
```

(With kudos to @ajwerner for helping me figuring out the exact example syntax)

### PR DESCRIPTION
**Pull request by ajwerner**
…rror

Fixes #50198.

See the issue for more details. This issue is so obscure it does not deserve
a release note.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
I could see killing the test. i just wanted to make sure that it did make it across the network correctly.

**Review by thoszhang — APPROVED** [review]
I could take or leave the test. It seems like it's mostly just testing that the library works. But having it is fine.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52015#-:-MDLjCTd7uqwYBdK0UtD:b-ycgrkd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
bors r=lucy-zhang

**Comment by knz** [comment]
thanks :sparkling_heart:

**Pull request merged**
