### PR TITLE
awsdms: properly retry initial migration

### LINKED ISSUE #81651: roachtest: awsdms failed
roachtest.awsdms [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/5238644?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/5238644?buildTab=artifacts#/awsdms) on master @ [5c400e31f33b97a7b3232bb54abdd55645f0e978](https://github.com/cockroachdb/cockroach/commits/5c400e31f33b97a7b3232bb54abdd55645f0e978):

```
The test failed on branch=master, cloud=aws:
test artifacts and logs in: /artifacts/awsdms/run_1
	awsdms.go:161,test_runner.go:884: pq: relation "test_table" does not exist
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*awsdms.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16018

### PR DESCRIPTION
**Pull request by otan**
fixes https://github.com/cockroachdb/cockroach/issues/81651

This loop was previously not retrying correctly, erroring the entire
test out when it first encounters an error. This commit rectifies this
to initiate a retry if an error occurs.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81667)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by otan — COMMENTED** [review]
bors r=rafiss

**Comment by rafiss** [comment]
Does this need a backport still?

**Comment by otan** [comment]
no ... we never backported the roachtest onto 22.1 ...

**Comment by rafiss** [comment]
Hm I see. Well then I removed the label

**Pull request merged**
