### PR TITLE
kvserver: remove detritus for old change replicas and preemptive snaps

### PR DESCRIPTION
**Pull request by tbg**
See individual commits.

- kvserver: remove deprecated fields in ChangeReplicasTrigger
- kvserver: improve comment on raft send buffer size
- kvserver: improve comment on split trigger helper
- kvserver: remove TODO for removing DisableEagerReplicaRemoval
- kvserver: remove snapshot CanDecline flag
- kvserver: reflect absence of preemptive snaps in more comments
- kvserver: remove IsPreemptive()
- kvserver: bump snapshotReservationWaitWarnThreshold
- kvserver: add TODO about removing snapshot log sending code.
- kvserver: assert that local descriptor "always" contains the replica
- kvserver: remove env-defaults for snapshot rate limits

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: nice cleanup.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 10 of 10 files at r5, 8 of 8 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72237#-:-MnBttAu5o3VVUPOPdzI:b-qbsc6a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/raft.proto, line 174 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72237#-MnBqO5w01VIefirqzg_:-MnBqO5x7wJgAdhSUsvE:b-33612h) ([raw file](https://github.com/cockroachdb/cockroach/blob/60a41f6fa7cc35e6dac1d4d0211785a208c47d4d/pkg/kv/kvserver/raft.proto#L174)):*
> ```protobuf
>     // by raft because at that point it is better to queue up the stream
>     // than to cancel it.
>     bool can_decline = 4;
> ```

Same here. We should reserve this field number as well.
___
*[pkg/roachpb/data.proto, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72237#-MnBpejK-MaoXoS1rqJs:-MnBpejK-MaoXoS1rqJt:bb4f3m3) ([raw file](https://github.com/cockroachdb/cockroach/blob/60a41f6fa7cc35e6dac1d4d0211785a208c47d4d/pkg/roachpb/data.proto#L228)):*
> ```protobuf
>   // TODO(tbg): when removing this, also rename internal_x_replicas to just
>   // x_replicas and remove the getter.
>   ReplicaChangeType deprecated_change_type = 1;
> ```

Should we mark these field numbers as reserved?

**Review by tbg — COMMENTED** [review]
TFTR! I had to massage the assertion I added a little bit to account for the testing knob that some tests use (and which can violate the assertions).
Addressed the missing reserved fields too, so will merge on green.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72237#-:-MnCecOs76AOxxAJvhbw:byaq61t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Comment by tbg** [comment]
bors r-

messed something up

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Pull request merged**
