### PR TITLE
go.mod: upgrade sarama from v1.22.2 to v1.27.2

### PR DESCRIPTION
**Pull request by pbardea**
Sarama release note updates, and commits: https://github.com/Shopify/sarama/releases. Diff is the one referenced in this change in the vendored repo.

Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
I took a look at the release note updates/commits in the update, and would also appreciate your review of those -- thanks!

**Comment by HonoreDB** [comment]
Thanks, don't see anything worrisome-looking in the release notes.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59801)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by pbardea** [comment]
TFTR!
bors r+

**Pull request merged**
