### PR TITLE
opt: use optional filters to constrain multi-column inverted indexes

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: test multi-column inverted index scans with unconstrained prefix columns

This commit adds tests that verify that multi-column inverted index
scans are not generated when the prefix columns are unconstrained.
Previous tests did not test these cases.

Release note: None

#### opt: use optional filters to constrain multi-column inverted indexes

This commit enables the optimizer to use check constraints and computed
column expressions to constrain non-inverted prefix columns of
multi-column inverted index scans. This is acheived by passing these
expressions as optional filters to the index constraint builder.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

Do you need a release note for the second commit?

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-:-MMHXIzn2fLcYyUupJGb:by62ib9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/xform/select_funcs.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-MMHWhG7275TvUvZG1uY:-MMHWhG7275TvUvZG1uZ:bzdjlfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/821e0a38f35d384b4e91986c818a46f20b8ab288/pkg/sql/opt/xform/select_funcs.go#L817)):*
> ```Go
> 		// TODO(rytaft): Unify these two cases so both return a spanExpr.
> 		// TODO(mgartner): Consider optional filters (like check constraints)
> 		// that can help constrain the prefix columns.
> ```

can you remove this TODO, now?

**Review by mgartner — COMMENTED** [review]
> Do you need a release note for the second commit?

I'm not sure I've ever fully understood what should be put in release notes for un-released features. Multi-column inverted indexes are currently only accessible by setting the `experimental_enable_multi_column_inverted_indexes` session setting. If I put release notes in for all the commits to build multi-column inverted indexes, then the release notes for 21.1 will contain a bunch of notes for new capabilities and bug fixes for multi-column inverted indexes, which seems odd if the entire feature is new in 21.1. Is it not weird to have release notes that read like "adds partitioned inverted indexes" and "check constraints can be used to constraint the non-inverted prefix columns of partitioned indexes" and "fixes bug in partitioned indexes that ...." and on and on?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-:-MMHYh7m5xviSz-LHRwP:bwtij5p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/select_funcs.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-MMHWhG7275TvUvZG1uY:-MMHYbjf6LTkf7HgyLL8:byvyago) ([raw file](https://github.com/cockroachdb/cockroach/blob/821e0a38f35d384b4e91986c818a46f20b8ab288/pkg/sql/opt/xform/select_funcs.go#L817)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you remove this TODO, now?
</blockquote></details>

Yes. Done.

**Review by rytaft — APPROVED** [review]
Fair enough, I forgot about `experimental_enable_multi_column_inverted_indexes`. I think it's fine to leave out the release note then.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-:-MMHfKX8Dzwt3HCITOgY:b-ot2e1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/xform/select_funcs.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-MMHWhG7275TvUvZG1uY:-MMHfcro9BbFExS_pj1q:b-bpn854) ([raw file](https://github.com/cockroachdb/cockroach/blob/821e0a38f35d384b4e91986c818a46f20b8ab288/pkg/sql/opt/xform/select_funcs.go#L817)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes. Done.
</blockquote></details>

It's still there

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56709)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/select_funcs.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-MMHWhG7275TvUvZG1uY:-MMHgB7x5kKk_A75IpA1:btjs8rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/821e0a38f35d384b4e91986c818a46f20b8ab288/pkg/sql/opt/xform/select_funcs.go#L817)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's still there
</blockquote></details>

Oops forgot to push. Ok now it's gone for good.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56709)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56709#-:-MMJTveh2VDGF3TgowQ_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
