### PR TITLE
leaktest: track goroutine IDs

### PR DESCRIPTION
**Pull request by tamird**
This prevents the case where goroutines leak by livelock, and leaktest reports
leaks in every single test that follows the test that leaked them.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12092)

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/leaktest/leaktest.go, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12092#-KYKDwDEAh7dft3noNYn:-KYKDwDE7ceUbu2OSYFg:b-g9qfrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e6fa401a99e4c22d5ee75cc250eae086b8b493b/pkg/util/leaktest/leaktest.go#L91)):*
> ```Go
> 				continue
> 			}
> 			sort.Strings(leaked)
> ```

Don't you want to sort by goroutine id? This is almost, but not quite that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12092)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/leaktest/leaktest.go, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12092#-KYKDwDEAh7dft3noNYn:-KYKFS1B3Bj-BmkD_Y3E:bc0dug2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e6fa401a99e4c22d5ee75cc250eae086b8b493b/pkg/util/leaktest/leaktest.go#L91)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Don't you want to sort by goroutine id? This is almost, but not quite that.
</blockquote></details>

Nah, not really. I don't even think we care about sorting, just restoring the old `sort.Strings` that was previously in `interestingGoroutines`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12092)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12092#-:-KYKFu1c-tOu1MH9sNrI:bnfp4nl)*

**Pull request merged**
