### PR TITLE
keys: better reversing of pretty-printed keys

### PR DESCRIPTION
**Pull request by andreimatei**
This commit moves keysutil.UglyPrint() to a PrettyScanner struct, and
make it somewhat configurable. A client can now specify a callback for
processing keys in the /Table span. Without that, UglyPrint() was
incapable of processing any /Table keys. One can imagine such callbacks
that are aware of table descriptors and thus capable of reversing
pretty-printed keys from those tables.

Then it introduces an example in the new testutils/keysutils package
that decodes keys like /Table/<table name>/<index name>/1/2/3 by making
some assumptions about the actual types of those ints and the direction
in which they should be encoded. The plan is to use this utility in a
future commit, and it also seems generally useful enough.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
r2 OK
r3 OK overall but I'm confused a bit
r1 I'm very confused (which is also why I'm confused by r3)

Also I'd like to know what this new code thinks of a key that's just `/Table/<id>` without additional parts afterwards. I don't see this tested anywhere. Ditto with `/Table/<id>/#PrefixEnd`

> Reviewed 1 of 1 files at r1, 3 of 4 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-:-LnMHeOWC3J-JaEVpJNr:b-jkf5kl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @darinpp, and @tbg)

___
*[pkg/keys/printer.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMGhdPEzvhTcsbh-4S:-LnMGhdPEzvhTcsbh-4T:b-m8ibc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e12dba0c4ec2f989f5425d177a1fefd4862aa59/pkg/keys/printer.go#L255)):*
> ```Go
> }
> 
> func tableIndexParse(input string) (string, roachpb.Key) {
> ```

Please provide a comment explaining what this function does.
___
*[pkg/keys/printer.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMGf2y6w0wdFP_Hm_8:-LnMGf2z0OHTkqyWm4ya:b-dri9u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e12dba0c4ec2f989f5425d177a1fefd4862aa59/pkg/keys/printer.go#L259)):*
> ```Go
> 	slashPos := strings.Index(input, "/")
> 	if slashPos < 0 {
> 		slashPos = len(input)
> ```

I don't understand this default case, can you explain with an example?
___
*[pkg/keys/printer.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMGk3q8jGGm5ILbQtd:-LnMGk3q8jGGm5ILbQte:b-ck81cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e12dba0c4ec2f989f5425d177a1fefd4862aa59/pkg/keys/printer.go#L269)):*
> ```Go
> 
> 	output := encoding.EncodeUvarintAscending(nil /* key */, uint64(indexID))
> 	return remainder, output
> ```

Maybe this function would benefit from a small set of unit tests.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHFl02f6qjJHRx0-e:-LnMHFl02f6qjJHRx0-f:bdnqug5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L60)):*
> ```Go
> 	slashPos := strings.Index(input, "/")
> 	if slashPos < 0 {
> 		slashPos = len(input)
> ```

Ditto what is this default case about.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHJDOD4Mctb3zjZGQ:-LnMHJDOD4Mctb3zjZGR:b-pob3os) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L66)):*
> ```Go
> 	tableID, ok := tableNameToID[tableName]
> 	if !ok {
> 		panic(fmt.Sprintf("unknown table: %s", tableName))
> ```

You could return errors here.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHLhf-hDCbKLu-8Qj:-LnMHLhf-hDCbKLu-8Qk:b-91hz7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L78)):*
> ```Go
> 	slashPos = strings.Index(input, "/")
> 	if slashPos < 0 {
> 		slashPos = len(input)
> ```

ditto - I'm confused here.

Also why don't you use the function introduced at r1 for the index part.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHQbg4Dvn-am7SxOA:-LnMHQbg4Dvn-am7SxOB:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L89)):*
> ```Go
> 		idxID, ok = idxNameToID[fmt.Sprintf("%s.%s", tableName, idxName)]
> 		if !ok {
> 			panic(fmt.Sprintf("unknown index: %s", idxName))
> ```

ditto
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHR_8-xbhMaBH-6Ja:-LnMHR_8-xbhMaBH-6Jb:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L106)):*
> ```Go
> 	slash, out := mustShift(in)
> 	if slash != "/" {
> 		panic("expected /: " + in)
> ```

ditto
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHSGkAhSbMzJD-f2i:-LnMHSGkAhSbMzJD-f2j:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L113)):*
> ```Go
> func mustShift(in string) (first, remainder string) {
> 	if len(in) == 0 {
> 		panic("premature end of string")
> ```

ditto
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHX5s4qKQW4G9Tje3:-LnMHX5s4qKQW4G9Tje4:b-ti46ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L150)):*
> ```Go
> 	slashPos := strings.Index(input, "/")
> 	if slashPos < 0 {
> 		slashPos = len(input)
> ```

ditto confusion

**Review by andreimatei — COMMENTED** [review]
TFTR!

> Also I'd like to know what this new code thinks of a key that's just /Table/<id> without additional parts afterwards. I don't see this tested anywhere. Ditto with /Table/<id>/#PrefixEnd

Let's make sure we're on the same page here.
Before r1, `UglyPrint` could only deal with `/Table/<table id>[/]`. Nothing after it.
r1 adds support for `/Table/<table id>/<index id>[/]`. Nothing after it.

`/Table/<id>` now has a test (see the one using `revertSupportUnknown`) 
By `/Table/<id>/#PrefixEnd` you mean `(/Table/<id>).PrefixEnd()`, right? Which is `/Table/<id+1>`.


Then r3 has nothing to do with the extra support added in r1. r3 does not handle ids. It handles a new format: `/Table/<table *name*>/<index *name*>/int/int/...`. This format is to be used by tests; it's not something produced by `PrettyPrint()` (although it probably should be when names are available).

Does this help?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-:-LnNo3ji-2UoVWnzhWwP:b-al3btt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @darinpp, @knz, and @tbg)

___
*[pkg/keys/printer.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMGhdPEzvhTcsbh-4S:-LnNf-FR2rRkZH9cSZiV:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e12dba0c4ec2f989f5425d177a1fefd4862aa59/pkg/keys/printer.go#L255)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please provide a comment explaining what this function does.
</blockquote></details>

done
___
*[pkg/keys/printer.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMGf2y6w0wdFP_Hm_8:-LnNfL8s6QsWN5wg7i6N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e12dba0c4ec2f989f5425d177a1fefd4862aa59/pkg/keys/printer.go#L259)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand this default case, can you explain with an example?
</blockquote></details>

Done.
___
*[pkg/keys/printer.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMGk3q8jGGm5ILbQtd:-LnNjWQBD0uftZC4EdA0:b-d8tfii) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e12dba0c4ec2f989f5425d177a1fefd4862aa59/pkg/keys/printer.go#L269)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe this function would benefit from a small set of unit tests.
</blockquote></details>

added one in `TestPrettyPrint` - the only one that uses `revertMustSupport`.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHFl02f6qjJHRx0-e:-LnNllrR4J2SOt0T0sQV:b-4mhpgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L60)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ditto what is this default case about.
</blockquote></details>

added a comment
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHJDOD4Mctb3zjZGQ:-LnNmx5-9P1wNCzPF9ao:b-s58ijg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L66)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You could return errors here.
</blockquote></details>

I tried but gave up cause there's too many places to return errors from (like `mustShift`), and having a combination of errors and panics would be worse. And also I'd have to panic on the errors anyway in the callback I pass to `MakePrettyScanner` cause that guy can't return errors. 
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHLhf-hDCbKLu-8Qj:-LnNnYJv7NfLw9Ys8HYq:bfdg6ma) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto - I'm confused here.

Also why don't you use the function introduced at r1 for the index part.
</blockquote></details>

Added a comment.

The reason why I haven't used that function is because here we're dealing with index names, not int ids.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHQbg4Dvn-am7SxOA:-LnNni8hD2ttz2nPjqMd:bz0d85p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L89)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

stuck with panics
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHSGkAhSbMzJD-f2i:-LnNnjY_8g3gt5W-HaDg:bjup7a5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

stuck with panics
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHX5s4qKQW4G9Tje3:-LnNo-K0B6yOrDmxEuKW:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto confusion
</blockquote></details>

Added a comment.

**Review by knz — COMMENTED** [review]
Yes it helps thanks.

LGTM with some nits.

> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-:-LnNu73_4S_JrTZA4_Gq:b-yy9gju)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @darinpp, and @tbg)

___
*[pkg/testutils/keysutils/pretty_scanner.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHLhf-hDCbKLu-8Qj:-LnNto5O6TWzWvKCew3O:b-k40w1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L78)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Added a comment.

The reason why I haven't used that function is because here we're dealing with index names, not int ids.
</blockquote></details>

Yet the comment you just added 2 lines above mention ids, not names.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHSGkAhSbMzJD-f2i:-LnNttMg2n8Ac2VPa0lQ:bw4nhoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

stuck with panics
</blockquote></details>

what about panicing an `errors.AssertionFailedf` instead of a raw string
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 151 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnNu0j_EpqX330Gy3r_:-LnNu0j_EpqX330Gy3ra:b-z0j6iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/677c75fed5e13077faa8c85196fcff8937e24a9e/pkg/testutils/keysutils/pretty_scanner.go#L151)):*
> ```Go
> 	slashPos := strings.Index(input, "/")
> 	if slashPos < 0 {
> 		// Deal with the case where there's no remainder.
> ```

expand the comment: `no remainder: the entire string is the index ID`.

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-:-LnOHNEc6G6pIAVY_Xwv:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @darinpp, @knz, and @tbg)

___
*[pkg/testutils/keysutils/pretty_scanner.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHLhf-hDCbKLu-8Qj:-LnOFfx_-H10ol0fdFmu:blz9pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yet the comment you just added 2 lines above mention ids, not names.
</blockquote></details>

my bad, fixed
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnMHSGkAhSbMzJD-f2i:-LnOFxdB8s_SxiZaWpzZ:b-p9mqdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82cad49743248778be543aa6535d35ee6251345/pkg/testutils/keysutils/pretty_scanner.go#L113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what about panicing an `errors.AssertionFailedf` instead of a raw string
</blockquote></details>

Is there an advantage to doing that? Does anything ever look inside panics and it'd benefit from that error (cause realistically definitely in the tests that are gonna use this it doesn't matter)?
If you tell me why that's a better practice, I'll gladly change it. But I'll merge this for now cause I want to use it.
___
*[pkg/testutils/keysutils/pretty_scanner.go, line 151 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40202#-LnNu0j_EpqX330Gy3r_:-LnOGiXP03Hj6IapX4P6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/677c75fed5e13077faa8c85196fcff8937e24a9e/pkg/testutils/keysutils/pretty_scanner.go#L151)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

expand the comment: `no remainder: the entire string is the index ID`.
</blockquote></details>

Done.

**Pull request merged**
