### PR TITLE
util: add more primitives to FastIntSet

### PR DESCRIPTION
**Pull request by RaduBerinde**
- Intersects
 - DifferenceWith
 - non-mutating variants of union/diff/intersect
 - Len
 - changing some methods to non-pointer receiver (so they can be used
   on sets returned from function calls)

Release note: none

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/fast_int_set.go, line 362 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095#-Kz5Nx9smPB0xM7htvmv:-Kz5Nx9smPB0xM7htvmw:b-eihvy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8182b0c94f9a55eabe7c48300b8b963c9234026/pkg/util/fast_int_set.go#L362)):*
> ```Go
> // String returns a list representation of elements. Sequential runs of positive
> // numbers are shown as ranges. For example:
> // MakeFastIntSet
> ```

This comment looks incomplete.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095#-:-Kz5O4DPdocvSDp1zL9Z:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/fast_int_set.go, line 362 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095#-Kz5Nx9smPB0xM7htvmv:-Kz5PcUV57VWsY-a5jM8:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8182b0c94f9a55eabe7c48300b8b963c9234026/pkg/util/fast_int_set.go#L362)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This comment looks incomplete.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/fast_int_set.go, line 362 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095#-Kz5Nx9smPB0xM7htvmv:-Kz5_Q6UQlE0O7AE-Wu0:b-xmcrb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8182b0c94f9a55eabe7c48300b8b963c9234026/pkg/util/fast_int_set.go#L362)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Shouldn't that be `0-2,5-6,10`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/fast_int_set.go, line 362 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095#-Kz5Nx9smPB0xM7htvmv:-Kz5_xlXOwsFuJThh83u:bqxsfzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8182b0c94f9a55eabe7c48300b8b963c9234026/pkg/util/fast_int_set.go#L362)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't that be `0-2,5-6,10`?
</blockquote></details>

Ah, I see that a run of length 2 is separated by commas. Carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095)*

**Comment by RaduBerinde** [comment]
*[pkg/util/fast_int_set.go, line 362 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095#-Kz5Nx9smPB0xM7htvmv:-Kz5au51rKTE4XhBY47K:b6el279) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8182b0c94f9a55eabe7c48300b8b963c9234026/pkg/util/fast_int_set.go#L362)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ah, I see that a run of length 2 is separated by commas. Carry on.
</blockquote></details>

Yeah, I saw `0-1` in opttoy and found it confusing at first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20095)*

**Pull request merged**
