### PR TITLE
storage: De-flake TestGossipHandlesReplacedNode

### LINKED ISSUE #15432: storage: TestGossipHandlesReplacedNode failed in testrace
Found in https://teamcity.cockroachdb.com/viewLog.html?buildId=236125&buildTypeId=Cockroach_UnitTests

```
Test ended in panic. 
------- Stdout: -------
[...]
E170427 21:43:23.670624 67525 storage/queue.go:634  [replicate,n2,s2,r2/2:/System/{-tsd}] range requires a replication change, but lacks a quorum of live replicas (0/2)
W170427 21:43:24.323235 67890 storage/replica.go:4399  [n3,s3,r2/?:/System/{-tsd}] could not acquire lease for range gossip: range 2 was not found
W170427 21:43:24.323442 67890 storage/store.go:1337  [n3,s3,r2/?:/System/{-tsd}] could not gossip node liveness: range 2 was not found
E170427 21:43:24.876972 67525 storage/queue.go:634  [replicate,n2,s2,r2/2:/System/{-tsd}] range requires a replication change, but lacks a quorum of live replicas (0/2)
W170427 21:43:25.421630 67890 storage/replica.go:4399  [n3,s3,r2/?:/System/{-tsd}] could not acquire lease for range gossip: range 2 was not found
W170427 21:43:25.421805 67890 storage/store.go:1337  [n3,s3,r2/?:/System/{-tsd}] could not gossip node liveness: range 2 was not found
W170427 21:43:26.566704 67890 storage/replica.go:4399  [n3,s3,r2/?:/System/{-tsd}] could not acquire lease for range gossip: range 2 was not found
W170427 21:43:26.566852 67890 storage/store.go:1337  [n3,s3,r2/?:/System/{-tsd}] could not gossip node liveness: range 2 was not found
E170427 21:43:27.090567 67525 storage/queue.go:634  [replicate,n2,s2,r2/2:/System/{-tsd}] range requires a replication change, but lacks a quorum of live replicas (0/2)
W170427 21:43:27.568872 67890 storage/replica.go:4399  [n3,s3,r2/?:/System/{-tsd}] could not acquire lease for range gossip: range 2 was not found
W170427 21:43:27.569370 67890 storage/store.go:1337  [n3,s3,r2/?:/System/{-tsd}] could not gossip node liveness: range 2 was not found
W170427 21:43:28.484761 67890 storage/replica.go:4399  [n3,s3,r2/?:/System/{-tsd}] could not acquire lease for range gossip: range 2 was not found
W170427 21:43:28.484929 67890 storage/store.go:1337  [n3,s3,r2/?:/System/{-tsd}] could not gossip node liveness: range 2 was not found
panic: test timed out after 15m0s
```

cc @spencerkimball

### PR DESCRIPTION
**Pull request by a-robinson**
I haven't been able to reproduce the flake despite hours of running
with stressrace on an azworker, but it looks as though what happened
is that when we remove the node from the cluster, the range we later
choose to write to only has two copies, one on the first node and one
on the second. When we remove the second node, the range becomes
unavailable and will never become available since the test never
brings the second node back up.

Fixes #15432

### CODE REVIEW

**Comment by tamird** [comment]
Keep fighting the good fight! Left a few questions.

Also, could you expand the commit message to include a description of the solution?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/gossip_test.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4FfFGhwIN4CZueIcL:-Kj4FfFGhwIN4CZueIcM:b-9o7pqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8096804775834d468a50760a9d2d8993b7521796/pkg/storage/gossip_test.go#L160)):*
> ```Go
> 	tc := testcluster.StartTestCluster(t, 3,
> 		base.TestClusterArgs{
> 			// Use manual replication so that we can ensure the range is properly
> ```

If you left this on Auto but added the `AddReplicas` calls below, would they still correctly block? My understanding is that the change here is about waiting for replication, rather than avoiding automatic movement of replicas.

---

*[pkg/storage/gossip_test.go, line 169 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4ErQ9pIApaOw0ls-x:-Kj4ErQ9pIApaOw0ls-y:b-45a5s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8096804775834d468a50760a9d2d8993b7521796/pkg/storage/gossip_test.go#L169)):*
> ```Go
> 	// Ensure that the first range is fully replicated before moving on.
> 	firstRangeKey := keys.MinKey
> 	tc.AddReplicas(firstRangeKey, tc.Target(1))
> ```

can this be a single call to AddReplicas? for context, we have some other tests where the answer is "no", so there's a semantic difference between the two (i.e. i'm not concerned about the performance here, just semantics).

If the answer is yes, please add a comment explaining the reasoning.

---

*[pkg/storage/gossip_test.go, line 181 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4FPTkoE0oVjnf-tQ3:-Kj4FPTl3Gxry-qgExow:b-ohpvnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8096804775834d468a50760a9d2d8993b7521796/pkg/storage/gossip_test.go#L181)):*
> ```Go
> 	newServerArgs.PartOfCluster = true
> 	newServerArgs.JoinAddr = tc.Servers[1].ServingAddr()
> 	// We have to manually disable these because the testcluster only handles
> ```

Ouch. Can we push this to the testcluster? Sounds like someone's bound to run into this elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-:-Kj4FYAkJFMbyBusNXIm:b-du8cug)*

**Comment by a-robinson** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/gossip_test.go, line 160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4FfFGhwIN4CZueIcL:-Kj4O2EqASACOoWYWaL-:b-1dev72) ([raw file](https://github.com/cockroachdb/cockroach/blob/8096804775834d468a50760a9d2d8993b7521796/pkg/storage/gossip_test.go#L160)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

If you left this on Auto but added the `AddReplicas` calls below, would they still correctly block? My understanding is that the change here is about waiting for replication, rather than avoiding automatic movement of replicas.
</blockquote></details>

They'd block forever, it turns out. `AddReplicas` doesn't work if the replica already exists.

---

*[pkg/storage/gossip_test.go, line 169 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4ErQ9pIApaOw0ls-x:-Kj4OJ5JkuV2WiySz1oA:bdsfvqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8096804775834d468a50760a9d2d8993b7521796/pkg/storage/gossip_test.go#L169)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can this be a single call to AddReplicas? for context, we have some other tests where the answer is "no", so there's a semantic difference between the two (i.e. i'm not concerned about the performance here, just semantics).

If the answer is yes, please add a comment explaining the reasoning.
</blockquote></details>

I was just cargo-culting from elsewhere, I have no reason to believe that it won't always work in a single call. Changed.

---

*[pkg/storage/gossip_test.go, line 181 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4FPTkoE0oVjnf-tQ3:-Kj4OejuPabP0pvBIigs:bszun54) ([raw file](https://github.com/cockroachdb/cockroach/blob/8096804775834d468a50760a9d2d8993b7521796/pkg/storage/gossip_test.go#L181)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ouch. Can we push this to the testcluster? Sounds like someone's bound to run into this elsewhere.
</blockquote></details>

Yeah, this is the only use of `AddServer` today, but it's not too much work to move it there. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-:-Kj4VPvQ_sgaknqvwwNo:b-896fix)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/testutils/testcluster/testcluster.go, line 144 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4WMF5SpfMZ8jI38_n:-Kj4WMF6Hw6wlRo7s0IA:b-ycx81) ([raw file](https://github.com/cockroachdb/cockroach/blob/34736b8e24aa242d80ca890cf8b3d0fe1fa4763e/pkg/testutils/testcluster/testcluster.go#L144)):*
> ```Go
> 	switch args.ReplicationMode {
> 	case base.ReplicationAuto:
> 	case base.ReplicationManual:
> ```

heh, I'd have probably left this as a switch-case. was there a reason to change it?

---

*[pkg/testutils/testcluster/testcluster.go, line 184 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4WWKZUvIMvdtqS7aj:-Kj4WWKZUvIMvdtqS7ak:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/10086c444a10ec3d58c3c3904aa09f2614c74df4/pkg/testutils/testcluster/testcluster.go#L184)):*
> ```Go
> func (tc *TestCluster) AddServer(t testing.TB, serverArgs base.TestServerArgs) {
> 	serverArgs.Stopper = stop.NewStopper()
> 	if tc.replicationMode == base.ReplicationManual {
> ```

:100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-:-Kj4WYFYmkGQeJuM6O1r:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/testutils/testcluster/testcluster.go, line 144 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-Kj4WMF5SpfMZ8jI38_n:-Kj4Y6-_T-A1X5i4BJvC:b74jc11) ([raw file](https://github.com/cockroachdb/cockroach/blob/34736b8e24aa242d80ca890cf8b3d0fe1fa4763e/pkg/testutils/testcluster/testcluster.go#L144)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

heh, I'd have probably left this as a switch-case. was there a reason to change it?
</blockquote></details>

Not really, just an insignificant style preference. If there had been three options I'd have left it as a switch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/gossip_test.go, line 182 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-KjOjsoWt5e_13B2I9lG:-KjOjsoWt5e_13B2I9lH:bdo04fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/10086c444a10ec3d58c3c3904aa09f2614c74df4/pkg/storage/gossip_test.go#L182)):*
> ```Go
> 	newServerArgs.PartOfCluster = true
> 	newServerArgs.JoinAddr = tc.Servers[1].ServingAddr()
> 	// We have to manually disable these because the testcluster only handles
> ```

is this still true now that you've moved the mangling of `StoreKnobs` to `tc.AddServer`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/gossip_test.go, line 182 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555#-KjOjsoWt5e_13B2I9lG:-KjQZmvdQIBRg9VuUiCn:b-qns1dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/10086c444a10ec3d58c3c3904aa09f2614c74df4/pkg/storage/gossip_test.go#L182)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this still true now that you've moved the mangling of `StoreKnobs` to `tc.AddServer`?
</blockquote></details>

Nope, it should have gotten removed. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15555)*

**Pull request merged**
