### PR TITLE
config,sql: prepare to support zone configs on indices and partitions

### PR DESCRIPTION
**Pull request by benesch**
Some helpers that prepare for upcoming work to allow specifying zone configs on indices and partitions of indices, as described in the partitioning RFC.

### CODE REVIEW

**Comment by danhhz** [comment]
this is a little overwhelming, could the last two commits be punted to a separate PR?

---

Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.go, line 298 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxsa6G_Vj3ociKags7i:-Kxsa6G_Vj3ociKags7j:byckj2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone.go#L298)):*
> ```Go
> // targeted by this ZoneConfig, leaving only the subzone configs, if any. After
> // calling ClearSelf, IsZubzonePlaceholder will return true.
> func (z *ZoneConfig) ClearSelf() {
> ```

I can't put my finger on why, but I don't love the name of this. I also don't love the mismatch of ClearSelf and DeleteSubzone

---

*[pkg/config/zone.go, line 317 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxs_Y8AUsDaVd6i7F36:-Kxs_Y8AUsDaVd6i7F37:bdqmqbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone.go#L317)):*
> ```Go
> 
> // GetSubzone returns the Subzone for the specified index ID and partition, if
> // it exists.
> ```

document that this can be called with partition="" to find a partition (and that if you're looking for a partition, you also need to set the indexID)

---

*[pkg/config/zone.go, line 320 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxs_hzwhT4pCdrgDuWv:-Kxs_hzwhT4pCdrgDuWw:bvxna4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone.go#L320)):*
> ```Go
> func (z *ZoneConfig) GetSubzone(indexID uint32, partition string) *Subzone {
> 	for _, s := range z.Subzones {
> 		if s.IndexID == indexID && s.PartitionName == partition {
> ```

We should revisit whether IndexID is set when PartitionName is. After the `GenerateSubzoneSpans` PR, I'm leaning toward no. It doesn't buy anything as far as I can see and it's just one more thing that could mismatch.

---

*[pkg/config/zone_test.go, line 78 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxsa_uWOG3xtXqn9ONU:-Kxsa_uWOG3xtXqn9ONV:b-wx2iu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone_test.go#L78)):*
> ```Go
> func TestZoneConfigSubzones(t *testing.T) {
> 	zone := config.DefaultZoneConfig()
> 	subzoneA1 := config.Subzone{IndexID: 1, PartitionName: "a", Config: config.ZoneConfig{}}
> ```

subzoneAInvalid?

---

*[pkg/config/zone_test.go, line 96 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-KxsajumF55-Dx-CtoXy:-KxsajumF55-Dx-CtoXz:bg97w3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone_test.go#L96)):*
> ```Go
> 		t.Errorf("expected zone validation to succeed, but got %s", err)
> 	}
> 	if subzone := zone.GetSubzone(1, "a"); !reflect.DeepEqual(&subzoneA2, subzone) {
> ```

why not `!subzoneA2.Equal(subzone)`? you went through all the trouble of adding the proto equal in a previous PR

---

*[pkg/sql/config.go, line 136 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-KxsZf2L--NXs9Q4WBWi:-KxsZf2L--NXs9Q4WBWj:b-p22t90) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeacc8159b29fda52c9a9fb535f4e5c3069d0380/pkg/sql/config.go#L136)):*
> ```Go
> }
> 
> var GenerateSubzoneSpansHook = func(
> ```

nit: just call this GenerateSubzoneSpans

---

*[pkg/sql/config.go, line 139 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-KxsZrd3zYe8pf1MCIFi:-KxsZrd3zYe8pf1MCIFj:b-pdtzjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeacc8159b29fda52c9a9fb535f4e5c3069d0380/pkg/sql/config.go#L139)):*
> ```Go
> 	*sqlbase.TableDescriptor, []config.Subzone,
> ) ([]config.SubzoneSpan, error) {
> 	return nil, fmt.Errorf("setting zone configs on indexes or partitions requires a CCL binary")
> ```

hmm, this is a more actionable error message than we have for the other ones: `unimplemented command: AddSSTable`. I wonder if we should tidy those up a bit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-:-KxsbZG_rXz3Zex0RWsJ:b-4dt85e)*

**Comment by benesch** [comment]
Yup, punted. PTAL!

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/config/zone.go, line 298 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxsa6G_Vj3ociKags7i:-KxxmJSDD55ainh60fB-:bvxkmsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone.go#L298)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I can't put my finger on why, but I don't love the name of this. I also don't love the mismatch of ClearSelf and DeleteSubzone
</blockquote></details>

Changed to `DeleteTableConfig`.

---

*[pkg/config/zone.go, line 317 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxs_Y8AUsDaVd6i7F36:-Kxxn4obvZk8_zMJ5qgA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone.go#L317)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

document that this can be called with partition="" to find a partition (and that if you're looking for a partition, you also need to set the indexID)
</blockquote></details>

Done.

---

*[pkg/config/zone.go, line 320 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxs_hzwhT4pCdrgDuWv:-KxxnO2AyhadMqykoGjl:bovdhwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone.go#L320)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

We should revisit whether IndexID is set when PartitionName is. After the `GenerateSubzoneSpans` PR, I'm leaning toward no. It doesn't buy anything as far as I can see and it's just one more thing that could mismatch.
</blockquote></details>

Still down to punt on this for now?

---

*[pkg/config/zone_test.go, line 78 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxsa_uWOG3xtXqn9ONU:-KxxnVmODfny5zIAXh-x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone_test.go#L78)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

subzoneAInvalid?
</blockquote></details>

Done.

---

*[pkg/config/zone_test.go, line 96 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-KxsajumF55-Dx-CtoXy:-Kxxnb1H868BrNaVLaDd:bho63yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone_test.go#L96)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why not `!subzoneA2.Equal(subzone)`? you went through all the trouble of adding the proto equal in a previous PR
</blockquote></details>

Heh, done. (I went through all that trouble because `proto.Equal` was choking on the recursive type, I think.)

---

*[pkg/sql/config.go, line 136 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-KxsZf2L--NXs9Q4WBWi:-Kxxp-WIGF0wz9MavS2_:b-c0k1gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeacc8159b29fda52c9a9fb535f4e5c3069d0380/pkg/sql/config.go#L136)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: just call this GenerateSubzoneSpans
</blockquote></details>

(No longer in this PR.)

---

*[pkg/sql/config.go, line 139 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-KxsZrd3zYe8pf1MCIFi:-Kxxp0sUTyE4dc7OvQb1:b-c0k1gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeacc8159b29fda52c9a9fb535f4e5c3069d0380/pkg/sql/config.go#L139)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

hmm, this is a more actionable error message than we have for the other ones: `unimplemented command: AddSSTable`. I wonder if we should tidy those up a bit
</blockquote></details>

(No longer in this PR.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-:-KxxpX5MwlDbROtzGRxL:b-6ipvvx)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/config/zone.go, line 320 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-Kxs_hzwhT4pCdrgDuWv:-Kxxqrmx2_0P_K9tfsHT:b2nhtan) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6d27b2fb2451dd49e56297b2465856d123d934/pkg/config/zone.go#L320)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Still down to punt on this for now?
</blockquote></details>

Yup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19717#-:-Kxxr0K2LqgbNslsQ_Jn:bnfp4nl)*

**Comment by benesch** [comment]
TFTR!

**Pull request merged**
