### PR TITLE
engineccl: Fix data key generation for v2 encryption

### PR DESCRIPTION
**Pull request by bdarnell**
Prior tests of v2 encryption were too low-level and did not cover the data key generation. The new roachtest provides end-to-end coverage.

This fixes a bug in not-yet-released functionality

Epic: none
Release note: none

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-:-Ntv1eWz8XXdqpD1Tu4_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @bdarnell, @DarrylWong, @jbowens, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/encryption.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Ntv1UEq-PG_pyyR2S5Y:-Ntv1UEr9hl6CjGkxpEl:b39b841) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9e27dc5c7dc53c2aef61f3a24e686565f08d65d/pkg/cmd/roachtest/tests/encryption.go#L38)):*
> ```Go
> 		httpClient := roachtestutil.DefaultHTTPClient(c, t.L())
> 
> 		// Starting with two copies of "plain" lets us avoid special-casing the first key in our rotation test.
> ```

I don't get this.. Looks like the first loop iteration is doing a `plain` to `plain` rotation.. do we want that?
___
*[`pkg/cmd/roachtest/tests/encryption.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Ntv1QrzAMPPv_NmMNp4:-Ntv1QrzAMPPv_NmMNp5:b-nuzhei) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9e27dc5c7dc53c2aef61f3a24e686565f08d65d/pkg/cmd/roachtest/tests/encryption.go#L40)):*
> ```Go
> 		// Starting with two copies of "plain" lets us avoid special-casing the first key in our rotation test.
> 		keys := []string{"plain", "plain"}
> 		// Rotate through multiple keys with different key sizes and both implementation versions.
> ```

[nit] Comments usually wrap at 80
___
*[`pkg/ccl/storageccl/engineccl/testdata/data_key_manager` line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Ntv0bWSDBxzuxUsBEy2:-Ntv0bWSDBxzuxUsBEy3:boui3ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9e27dc5c7dc53c2aef61f3a24e686565f08d65d/pkg/ccl/storageccl/engineccl/testdata/data_key_manager#L254)):*
> ```
> get-active-data-key
> ----
> encryption_type:AES_128_CTR_V2 creation_time:26 source:"data key manager" parent_key_id:"v2key"
> ```

[nit] missing `\n`

**Review by bdarnell — COMMENTED** [review]
I had trouble getting the test to work in remote roachtests (before I sent the PR I had only tested it locally), so I snuck in an additional feature to address part of #110123: Now you can specify `path=*` instead of matching the exact path from the store flag. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-:-Nu2wrKq9RkMvr1Q9GD1:b-x60lcf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @jbowens, @RaduBerinde, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/encryption.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Ntv1UEq-PG_pyyR2S5Y:-Nu2wXmE1p9I6sMsxMg7:bd5x6aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9e27dc5c7dc53c2aef61f3a24e686565f08d65d/pkg/cmd/roachtest/tests/encryption.go#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't get this.. Looks like the first loop iteration is doing a `plain` to `plain` rotation.. do we want that?
</blockquote></details>

Updated comments to explain what's going on: we have to specify pairs of keys so to have the current key be "plain" we need to specify the previous key as "plain" too. Or we could make the addition of the `--enterprise-encryption` key conditional on the loop index (skip it on the first start) but this way felt simpler.
___
*[`pkg/cmd/roachtest/tests/encryption.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Ntv1QrzAMPPv_NmMNp4:-Nu2wnwp47St0EDAGHY9:b-p99nyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9e27dc5c7dc53c2aef61f3a24e686565f08d65d/pkg/cmd/roachtest/tests/encryption.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Comments usually wrap at 80
</blockquote></details>

Rewrapped everything. 
___
*[`pkg/ccl/storageccl/engineccl/testdata/data_key_manager` line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Ntv0bWSDBxzuxUsBEy2:-Nu2wq2s8qrutJSQjA9o:b-lx4fj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9e27dc5c7dc53c2aef61f3a24e686565f08d65d/pkg/ccl/storageccl/engineccl/testdata/data_key_manager#L254)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] missing `\n`
</blockquote></details>

Fixed.

**Review by jbowens — APPROVED** [review]
Just looked at the new commit to address part of #110123 and it lgtm

> Reviewed 2 of 8 files at r2, 1 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-:-Nu4UJpo3ScBG_8rBcpN:b-p9n27c)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @DarrylWong, @RaduBerinde, and @srosenberg)

___
*[`-- commits` line 15 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Nu4TfBg0-gNs24xtKOO):*
looks like some of the template survived

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121111)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @jbowens, @RaduBerinde, and @srosenberg)

___
*[`-- commits` line 15 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121111#-Nu4TfBg0-gNs24xtKOO):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

looks like some of the template survived
</blockquote></details>

Derp, I wish that part of the template started with `#` like the rest.

**Comment by bdarnell** [comment]
bors r=RaduBerinde,jbowens

**Pull request merged**
