### PR TITLE
ui: compute graph domains correctly for stacked graphs

### LINKED ISSUE #9414: ui: raft messages received graph broken/confusing
The "raft messages received" graph is either broken or confusing. The numbers are accurate, but much of the graph doesn't fit within the visible area.

screen shot 2016-09-15 at 5 07 23 pm

### PR DESCRIPTION
**Pull request by maxlang**
Fixes #9414

cc @petermattis 

Once this is in I'll cherry pick it to master

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9478)

### CODE REVIEW

**Comment by petermattis** [comment]
Shouldn't this go to master and then be merged into develop during the usual master->develop merges?

**Comment by tamird** [comment]
Yes, it should.

**Comment by maxlang** [comment]
Remade against master as PR #9542

**Comment by tamird** [comment]
There is no need to close and reopen PRs this way; GitHub allows changing
the target branch.

**Comment by maxlang** [comment]
@tamird how would this work with embedded.go?

**Comment by tamird** [comment]
What? You'd need to rebase it anyway.

**Pull request closed without merging**
