### PR TITLE
system: Add new table_metadata system table

### PR DESCRIPTION
**Pull request by kyle-a-wong**
Adds a new system table, `table_metadata` for holding table level statatistics and metadata. This table is intended to be used as a cache and will be periodically updated via a new job.

Epic: [CRDB-37558](https://cockroachlabs.atlassian.net/browse/CRDB-37558)
Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 106 of 113 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127290)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O34o7dc2SMPDTf5jAa9:-O34o7dc2SMPDTf5jAaA:bob1b6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/920e2e84999f9d31bda78d253f02eeae94812d41/pkg/sql/catalog/systemschema/system.go#L1179)):*
> ```Go
> 	);`
> 
> 	crdbInternalTableIdLastUpdatedShard = "mod(fnv32(md5(crdb_internal.datums_to_bytes(table_id, last_updated))), 16:::INT8)"
> ```

What is the purpose of this?
___
*[`pkg/sql/catalog/systemschema/system.go` line 1204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O34lBb3C1JowDlv4uLN:-O34lBb44Y_BwrWWMF78:b-flqb4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/920e2e84999f9d31bda78d253f02eeae94812d41/pkg/sql/catalog/systemschema/system.go#L1204)):*
> ```Go
> 		INVERTED INDEX table_name_gin (table_name gin_trgm_ops),
> 		INVERTED INDEX regions_gin (regions),
>     FAMILY "primary" (
> ```

Why do you need this family that omits the shard ID?

**Review by kyle-a-wong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127290)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O34o7dc2SMPDTf5jAa9:-O38xhNm5MwAWhzPtGBf:b7q7qpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/920e2e84999f9d31bda78d253f02eeae94812d41/pkg/sql/catalog/systemschema/system.go#L1179)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

What is the purpose of this?
</blockquote></details>

This is needed for the last updated  hash index defined below, 
___
*[`pkg/sql/catalog/systemschema/system.go` line 1204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O34lBb3C1JowDlv4uLN:-O38yP_X5yd-krqysK51:b-2kzm5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/920e2e84999f9d31bda78d253f02eeae94812d41/pkg/sql/catalog/systemschema/system.go#L1204)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Why do you need this family that omits the shard ID?
</blockquote></details>

Im not sure why it needs to be omitted, maybe because its a virtual column

**Review by dhartunian — COMMENTED** [review]
Just a few nits, otherwise looks fine

> Reviewed 14 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-:-O4LN9Z7053veE8hPqL6:bwxlv4m)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @kyle-a-wong, and @mgartner)

___
*[`pkg/upgrade/upgrades/v24_3_table_metadata_systems_table.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LHfEt6mwE75_kzGXc:-O4LHfEt6mwE75_kzGXd:bc4md9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a77c3604f8ea9779fcd707d6fb023a357a352fd/pkg/upgrade/upgrades/v24_3_table_metadata_systems_table.go#L1)):*
> ```Go
> // Copyright 2024 The Cockroach Authors.
> ```

can you make sure the file name is consistent. I think it should be `system_table`, not plural, right?
___
*[`pkg/sql/logictest/testdata/logic_test/gen_test_objects` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LHomA7CXwK18PQCS0:-O4LHomA7CXwK18PQCS1:b-rp7fic) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a77c3604f8ea9779fcd707d6fb023a357a352fd/pkg/sql/logictest/testdata/logic_test/gen_test_objects#L193)):*
> ```
> sqlliveness
> statement_diagnosti cs
> sta😣tement_statistics
> ```

why is stuff in this file changing? it seems unrelated
___
*[`pkg/sql/logictest/testdata/logic_test/system_namespace` line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LIDZYDBWV8tYU1kvt:-O4LIDZYDBWV8tYU1kvu:b-h5cdk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a77c3604f8ea9779fcd707d6fb023a357a352fd/pkg/sql/logictest/testdata/logic_test/system_namespace#L71)):*
> ```
> 1    29  tenant_tasks                     60
> 1    29  tenant_usage                     45
> 1    29  tenants                          8
> ```

is there any guarantee on that the diff here preserves everything and just changes order?

**Review by mgartner — COMMENTED** [review]
> Reviewed 18 of 113 files at r1, 8 of 31 files at r2, 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127290)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @dt, and @kyle-a-wong)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LcxJtA7jiX3onYC98:-O4LcxJtA7jiX3onYC99:b9bsg7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/df32df824fc68518db16b42be5e2f5b20b96a04e/pkg/sql/catalog/systemschema/system.go#L1204)):*
> ```Go
> 		schema_name STRING NOT NULL,
>     table_name STRING NOT NULL,
> 		span_stats JSONB NOT NULL,
> ```

What's the benefit of using JSONB here instead of separate columns for each of the computed columns below?
___
*[`pkg/sql/logictest/logic.go` line 2951 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LfG9OBqV53dkdnrkG:-O4LfG9OBqV53dkdnrkH:b-c4as1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/df32df824fc68518db16b42be5e2f5b20b96a04e/pkg/sql/logictest/logic.go#L2951)):*
> ```Go
> 				for i := 0; i < repeat; i++ {
> 					if t.retry && !*rewriteResultsInTestfiles {
> ```

nit: remove unnecessary change

**Review by kyle-a-wong — COMMENTED** [review]
> Reviewed 1 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127290)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @dt, and @mgartner)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LcxJtA7jiX3onYC98:-O4Qc1xL6GK-wByLos62:b19codw) ([raw file](https://github.com/cockroachdb/cockroach/blob/df32df824fc68518db16b42be5e2f5b20b96a04e/pkg/sql/catalog/systemschema/system.go#L1204)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What's the benefit of using JSONB here instead of separate columns for each of the computed columns below?
</blockquote></details>

After some decisions, we decided that this column isn't needed and switched to non-computed columns
___
*[`pkg/sql/logictest/testdata/logic_test/gen_test_objects` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LHomA7CXwK18PQCS0:-O4MG1CEAaEdyb_FUL1x:b-czya4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a77c3604f8ea9779fcd707d6fb023a357a352fd/pkg/sql/logictest/testdata/logic_test/gen_test_objects#L193)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why is stuff in this file changing? it seems unrelated
</blockquote></details>

Hmmm, I'm not 100% sure about this, but I do see that before this test, there are tables created via `SELECT crdb_internal.generate_test_objects('{"seed":1234,"counts":[10],"table_templates":["system.*"]}'::JSONB)-`. I haven't looked into how `generate_test_objects` works, I'm assuming our new table affects this. 
___
*[`pkg/sql/logictest/logic.go` line 2951 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LfG9OBqV53dkdnrkG:-O4MCtGXCYEqSyiQ-Lpi:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/df32df824fc68518db16b42be5e2f5b20b96a04e/pkg/sql/logictest/logic.go#L2951)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: remove unnecessary change
</blockquote></details>

Done
___
*[`pkg/upgrade/upgrades/v24_3_table_metadata_systems_table.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LHfEt6mwE75_kzGXc:-O4MD2dz50HTBIzU7o1C:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a77c3604f8ea9779fcd707d6fb023a357a352fd/pkg/upgrade/upgrades/v24_3_table_metadata_systems_table.go#L1)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can you make sure the file name is consistent. I think it should be `system_table`, not plural, right?
</blockquote></details>

Done

**Review by dhartunian — APPROVED** [review]
:lgtm: I prefer the simplified schema, thanks for making the change.

> Reviewed 3 of 9 files at r4, 10 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-:-O4qO-UA7INp3oUyjHG0:b7mf1ac)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt, @kyle-a-wong, and @mgartner)

**Review by mgartner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127290)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @dt, and @kyle-a-wong)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127290#-O4LcxJtA7jiX3onYC98:-O4uHeW18-ybbLlDjsX0:b-1hahpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/df32df824fc68518db16b42be5e2f5b20b96a04e/pkg/sql/catalog/systemschema/system.go#L1204)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

After some decisions, we decided that this column isn't needed and switched to non-computed columns
</blockquote></details>

:+1: SGTM. I think this is the right move to avoid the complexity of computed columns, assuming it works with your design.

**Comment by kyle-a-wong** [comment]
TFTR!!

bors r+

**Pull request merged**
