### PR TITLE
opt: hoist uncorrelated equality subqueries

### LINKED ISSUE #83392: opt: hoist uncorrelated scalar subquery with equality
The following query plan shows a simple point lookup:
```sql
root@127.0.0.1:26257/movr> explain select * from promo_codes where code = 'test';

  • scan
    estimated row count: 1 (<0.01% of the table; stats collected 23 minutes ago)
    table: promo_codes@promo_codes_pkey
    spans: [/'test' - /'test']
```

When a subquery is used in an IN predicate, we can decorrelate the subquery and turn the predicate into a join. Arguably the join is redundant and we could eliminate it in this case because the tables on both sides are the same, but this is good enough.

```sql
root@127.0.0.1:26257/movr> explain select * from promo_codes where code IN (select code from promo_codes where code = 'test');

  • cross join (semi)
  │ estimated row count: 1
  │
  ├── • scan
  │     estimated row count: 1 (<0.01% of the table; stats collected 23 minutes ago)
  │     table: promo_codes@promo_codes_pkey
  │     spans: [/'test' - /'test']
  │
  └── • scan
        estimated row count: 1 (<0.01% of the table; stats collected 23 minutes ago)
        table: promo_codes@promo_codes_pkey
        spans: [/'test' - /'test']
```

However, when a subquery is used in an equality predicate, we can't decorrelate the subquery. Instead, we evaluate it, then perform a full table scan, then filter the result of that scan using the result of the subquery.

```sql
root@127.0.0.1:26257/movr> explain select * from promo_codes where code = (select code from promo_codes where code = 'test');

  • root
  │
  ├── • filter
  │   │ estimated row count: 333,664
  │   │ filter: code = @S1
  │   │
  │   └── • scan
  │         estimated row count: 1,000,991 (100% of the table; stats collected 26 minutes ago)
  │         table: promo_codes@promo_codes_pkey
  │         spans: FULL SCAN
  │
  └── • subquery
      │ id: @S1
      │ original sql: (SELECT code FROM promo_codes WHERE code = 'test')
      │ exec mode: one row
      │
      └── • scan
            estimated row count: 1 (<0.01% of the table; stats collected 26 minutes ago)
            table: promo_codes@promo_codes_pkey
            spans: [/'test' - /'test']
```

This is unfortunate and may look artificial, but while flying over the rocky mountains, @andreimatei and I found this by looking at real queries, like the following:
```sql
root@127.0.0.1:26257/movr> explain delete from promo_codes where code = (select code from promo_codes limit 1);

  • root
  │
  ├── • delete
  │   │ from: promo_codes
  │   │ auto commit
  │   │
  │   └── • filter
  │       │ estimated row count: 333,664
  │       │ filter: code = @S1
  │       │
  │       └── • scan
  │             estimated row count: 1,000,991 (100% of the table; stats collected 35 minutes ago)
  │             table: promo_codes@promo_codes_pkey
  │             spans: FULL SCAN
  │
  └── • subquery
      │ id: @S1
      │ original sql: (SELECT code FROM promo_codes LIMIT 1)
      │ exec mode: one row
      │
      └── • scan
            estimated row count: 1 (<0.01% of the table; stats collected 35 minutes ago)
            table: promo_codes@promo_codes_pkey
            spans: LIMITED SCAN
            limit: 1
```

Jira issue: CRDB-17044

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: hoist uncorrelated equality subqueries

Subqueries that are in equality expressions with a variable are now
hoisted. When these expressions exist in a filter, hoisting the subquery
can allow the main query to plan a lookup join, rather than an
inefficient full-table scan.

For example, consider the table and query:

    CREATE TABLE t (
      a INT,
      INDEX (a)
    );

    SELECT * FROM t WHERE a = (SELECT max(a) FROM t);

Prior to this commit, the query plan for this query required a full
table scan:

    select
     ├── columns: a:1
     ├── scan t@t_a_idx
     │    ├── columns: a:1
     │    └── constraint: /1/2: (/NULL - ]
     └── filters
          └── eq
               ├── a:1
               └── subquery
                    └── scalar-group-by
                         ├── columns: max:9
                         ├── scan t@t_a_idx,rev
                         │    ├── columns: a:5
                         │    ├── constraint: /5/6: (/NULL - ]
                         │    └── limit: 1(rev)
                         └── aggregations
                              └── const-agg [as=max:9, outer=(5)]
                                   └── a:5

By hoisting the subquery, the full table scan is replaced with a lookup
join:

    project
     ├── columns: a:1
     └── inner-join (lookup t@t_a_idx)
          ├── columns: a:1 max:9
          ├── key columns: [9] = [1]
          ├── scalar-group-by
          │    ├── columns: max:9
          │    ├── scan t@t_a_idx,rev
          │    │    ├── columns: a:5
          │    │    ├── constraint: /5/6: (/NULL - ]
          │    │    └── limit: 1(rev)
          │    └── aggregations
          │         └── const-agg [as=max:9, outer=(5)]
          │              └── a:5
          └── filters (true)

This hoisting is enabled by default, but can be disabled by setting the
`optimizer_hoist_uncorrelated_equality_subqueries` session setting to
`false`.

Fixes #83392
Informs #51820
Informs #93829
Informs #100855

Release note (performance improvement): Queries that have subqueries in
equality expressions are now more efficiently planned by the optimizer.

### CODE REVIEW

**Comment by mgartner** [comment]
In the backports for this I'll default this session setting to `false`.

Here's some analysis of the performance improvements for a simple query that benefits from this change: https://gist.github.com/mgartner/9aa764ecbdb6d879d71863eb6b32b4c2

**Comment by mgartner** [comment]
Hold off on reviewing for now - there's some interesting test failures this has caused.

**Comment by mgartner** [comment]
This is currently blocked on #100915.

**Comment by mgartner** [comment]
The first three commits are from #100926 which should have fixed the broken `builtin_function` logic test, but it's still failing. No need to review just yet.

**Comment by mgartner** [comment]
The first three commits are from #101324 and #101327.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great idea! Do you have benchmark results for tpch Q15?

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100881#-:-NSr079J2iLTpR0wNs6f:ba9br7v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: nice!

> Do you have benchmark results for tpch Q15?

+1

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100881#-:-NT-VaMpElZXygJHK_8f:b-4jj43y)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> Do you have benchmark results for tpch Q15?

How do I run the TPC-H benchmark?

I ran q15 manually in a demo on my GCE worker, and its ~5% slower than before this commit. Before it took ~6.3s and not it takes ~6.6s. It's not super obvious from the statement bundles why it's slower - it seems like it should be faster based on the query plan. And most of the time in both cases is spent on index-joins - so q15 would be best optimized with a `STORING` index to eliminate them. That'd have a significantly greater impact than this 5% regression. So I think this is fine. What do you all think?


Master stmt-bundle: https://gist.github.com/mgartner/3ce71bb0d8861011820e05b11bf5391e
Hoist subquery stmt-bundle: https://gist.github.com/mgartner/f9170879a8bc1a24a82f44979c3be4cd

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100881#-:-NTEgBzyENKmuguKYGGi:b-1tu1sv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @rytaft)

**Review by rytaft — APPROVED** [review]
Running queries manually is how I normally check for TPC-H regressions. How many times did you run the query? 5% seems small enough that it could just be noise. In any case, I'm not too concerned.

Regarding a `STORING` index -- I'm not sure what's allowed according to the spec, but if it's legal, I'm all for it (in a separate PR, obviously).

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100881#-:-NTEjVRv0E6KfdahDFTu:blb3wdj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
I don't think it was noise because it was consistently ~5% slower when run multiple times in multiple demos. I'm not too concerned about the 5% either.

**Comment by mgartner** [comment]
I'm going to go ahead and merge. TFTRs!

bors r+

**Pull request merged**
