### PR TITLE
sqlliveness/slstorage: break InternalExecutor depedency

### PR DESCRIPTION
**Pull request by ajwerner**
There was no fundamental reason to rely on SQL for this low-level subsystem.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Change LGTM, but CI is telling you that there are now a couple of dead functions that you should remove.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65648#-:-Maha-hX7aSjkyRVNveT:beso8kr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/sqlliveness/slstorage/slstorage_test.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65648#-MahZqfuEBHw47xmCnwC:-MahZqfuEBHw47xmCnwD:b-4pugf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7956dbd091a740182694d32a7180ba4186674349/pkg/sql/sqlliveness/slstorage/slstorage_test.go#L64)):*
> ```Go
> 		tDB.Exec(t, schema)
> 		var tableID descpb.ID
> 		tDB.QueryRow(t, "SELECT $1::regclass::int",
> ```

that regclass cast under the hood recurses into a lot of subsystems. There's a lot of opportunity for things to go wrong.

What about 
```sql
select u.id 
  from system.namespace t
  join system.namespace u 
    on t.id = u."parentID" 
 where t.name = $1 and u.name = 'sqlliveness'
```

with `dbName` as argument
___
*[pkg/sql/sqlliveness/slstorage/slstorage_test.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65648#-Mah_o8R7VKV6Str_mew:-Mah_o8R7VKV6Str_mex:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7956dbd091a740182694d32a7180ba4186674349/pkg/sql/sqlliveness/slstorage/slstorage_test.go#L319)):*
> ```Go
> 	tDB.Exec(t, schema)
> 	var tableID descpb.ID
> 	tDB.QueryRow(t, "SELECT $1::regclass::int",
> ```

ditto

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/sqlliveness/slstorage/slstorage_test.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65648#-MahZqfuEBHw47xmCnwC:-MbicfBpCOeySm9DJXpe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7956dbd091a740182694d32a7180ba4186674349/pkg/sql/sqlliveness/slstorage/slstorage_test.go#L64)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

that regclass cast under the hood recurses into a lot of subsystems. There's a lot of opportunity for things to go wrong.

What about 
```sql
select u.id 
  from system.namespace t
  join system.namespace u 
    on t.id = u."parentID" 
 where t.name = $1 and u.name = 'sqlliveness'
```

with `dbName` as argument
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by knz** [comment]
will appreciate a backport to 21.1

**Comment by ajwerner** [comment]
TFTR!

bors r=knz

**Pull request merged**
