### PR TITLE
storage/engine: remove unused GetTickersAndHistograms function from Pebble

### PR DESCRIPTION
**Pull request by hueypark**
See #42479

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45439#-:-M10n4PU3CUTkF1dFWDi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by hueypark — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45439#-:-M10ncOh2Bay5IuyzjgK:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by petermattis** [comment]
(I'll kick off the bors request as soon as CI is green).

**Pull request merged**
