### PR TITLE
sqlsmith: add initial support for PL/pgSQL

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: add support for NULL statements

This commit implements the PL/pgSQL NULL statement, which is a no-op.
This will be convenient for the following commit, which adds initial
support for PL/pgSQL to sqlsmith.

Informs #117744
Informs #106368

Release note (sql change): Added support for the PL/pgSQL NULL statement.

#### sqlsmith: add initial support for PL/pgSQL

This commit adds initial support for PL/pgSQL routines. The following
statements are supported:
* Block
* If/Elsif/Else
* Return
* Null
* Assign
* SQL statements

Informs #106368

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first three commits are #119034.

**Comment by DrewKimball** [comment]
Example generated statement:
```
CREATE FUNCTION func_29()
	RETURNS RECORD
	LANGUAGE plpgsql
	AS $funcbody$
DECLARE
decl_205 NAME := e'C\x14':::STRING:::NAME;
"D
ecl_206" INET := '218.182.213.88/3':::INET;
"😃Decl_207" VOID;
decl_208 TIMETZ;
"de
   cl_209" REFCURSOR := e'q2Jm\x046j':::REFCURSOR;
"d e%pcl_210" REGTYPE := 1023113024:::OID;
BEGIN
"D
ecl_206" := "D
ecl_206";
RETURN (1461997381:::OID, '23:03:00.602946':::TIME, 783147277:::OID);
NULL;
SELECT e'w24G9,\x06%':::REFCURSOR AS col_3019, "t{ab_1855"."c.ol0__2" AS col_3020, '115.161.46.85/21':::INET AS col_3021 FROM defaultdb.public.tab_1110@"tab_1110_c.ol0__2_key" AS "t{ab_1855" LIMIT 89:::INT8;
IF false THEN
	DELETE FROM defaultdb.public.tab_1110 AS tab_1856 USING defaultdb.public.tab_1110 AS "tab\g_1857", defaultdb.public.tab_1110 AS tab_1858, defaultdb.public.tab_1110 AS t😰ab_1859, defaultdb.public.tab_1110 AS "ta\\u3F42b͌_1860" WHERE false LIMIT 25:::INT8;
ELSIF true THEN
	"d e%pcl_210" := 3429146290:::OID;
END IF;
END;
$funcbody$;
```

**Review by yuzefovich — COMMENTED** [review]
Nice! I have a few nits.

> Reviewed 3 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-:-NqUM1DQAyS9mNPolbZk:baobgul)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

___
*[`pkg/internal/sqlsmith/plpgsql.go` line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUIHAq4fkpWy4k5xRv:-NqUIHAq4fkpWy4k5xRw:bi9xogd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L90)):*
> ```Go
> 	for i := 0; i < numStmts; i++ {
> 		for {
> 			// No need for a retry counter, because eventually a NULL statement will
> ```

I'm a bit confused by this comment - can you expand on it? Is it effectively saying that we don't need to count the number of times `Next` is called when it returns `ok = false` because at some point `NULL` stmt is returned which will have `ok = true`, so infinite loop is impossible?
___
*[`pkg/internal/sqlsmith/plpgsql.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUJPr7AkNgABDI7RJX:-NqUJPr7AkNgABDI7RJY:b-9vk35g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L109)):*
> ```Go
> 	}
> 	if s.coin() {
> 		numElsIfs := s.rnd.Intn(3) + 1
> ```

nit: perhaps `s/numElsIfs/numElseIfs/`.
___
*[`pkg/internal/sqlsmith/plpgsql.go` line 136 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUJavkEOPoFP8rsyV1:-NqUJavkEOPoFP8rsyV2:bpcdyov) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L136)):*
> ```Go
> }
> 
> // TODO(#106368): implement generation for the remaining statements.
> ```

nit: this issue is being closed by this PR right now - should this refer to a different issue? Or should this PR not fully close it?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119037)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`pkg/internal/sqlsmith/plpgsql.go` line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUIHAq4fkpWy4k5xRv:-NrE0VV24bUZ0NdJFMps:bhqabuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L90)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm a bit confused by this comment - can you expand on it? Is it effectively saying that we don't need to count the number of times `Next` is called when it returns `ok = false` because at some point `NULL` stmt is returned which will have `ok = true`, so infinite loop is impossible?
</blockquote></details>

Yes, that's exactly it. I modified the comment to explain that better.
___
*[`pkg/internal/sqlsmith/plpgsql.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUJPr7AkNgABDI7RJX:-NrE0qhm5pdYDG4YGN7B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L109)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps `s/numElsIfs/numElseIfs/`.
</blockquote></details>

Done.
___
*[`pkg/internal/sqlsmith/plpgsql.go` line 136 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUJavkEOPoFP8rsyV1:-NrE13rACCr2hZsc7KmS:btsks8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L136)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this issue is being closed by this PR right now - should this refer to a different issue? Or should this PR not fully close it?
</blockquote></details>

Good point. I'll leave the issue open to track support for other statements.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 3 files at r7, 2 of 2 files at r8, 3 of 3 files at r9, 5 of 5 files at r10, 17 of 17 files at r11, 16 of 16 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-:-NsjQgcvAZCxriB6WmNa:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/internal/sqlsmith/plpgsql.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUJPr7AkNgABDI7RJX:-NsjPhaF3GAGGx8qHWXR:b-to9wpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L109)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I didn't realize that `ELSIF` is the keyword - up to you whether you want to revert the change in response to my comment.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119037)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/internal/sqlsmith/plpgsql.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119037#-NqUJPr7AkNgABDI7RJX:-NsjRM7J7VGVu4GhbFwa:bng2zs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7566d370897b8e14f8641d2e93c072e305d045fd/pkg/internal/sqlsmith/plpgsql.go#L109)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Sorry, I didn't realize that `ELSIF` is the keyword - up to you whether you want to revert the change in response to my comment.
</blockquote></details>

Eh, I think `numElseIfs` is good. TFYR!

**Pull request merged**
