### PR TITLE
*: upgrade to go 1.18.4

### PR DESCRIPTION
**Pull request by rickystewart**
* [ ] Adjust the Pebble tests to run in new version.
* [x] Adjust version in Docker image ([source](./builder/Dockerfile)).
* [x] Adjust version in the TeamCity agent image ([setup script](./packer/teamcity-agent.sh))
* [ ] Rebuild and push the Docker image (following [Basic Process](#basic-process))
* [x] Download ALL the archives (`.tar.gz`, `.zip`) for the new Go version from https://golang.org/dl/ and mirror them in the `public-bazel-artifacts` bucket in the `Bazel artifacts` project in GCP (sub-directory `go`, next to the other Go SDK's).
* [x] Bump the version in `WORKSPACE` under `go_download_sdk`. You may need to bump [rules_go](https://github.com/bazelbuild/rules_go/releases). Also edit the filenames listed in `sdks` and update all the hashes to match what you mirrored in the step above.
* [x] Run `./dev generate bazel` to refresh `distdir_files.bzl`, then `bazel fetch @distdir//:archives` to ensure you've updated all hashes to the correct value.
* [ ] Bump the version in `builder.sh` accordingly ([source](./builder.sh#L6)).
* [x] Bump the version in `go-version-check.sh` ([source](./go-version-check.sh)), unless bumping to a new patch release.
* [ ] Bump the go version in `go.mod`. You may also need to rerun `make vendor_rebuild` if vendoring has changed.
* [x] Bump the default installed version of Go in `bootstrap-debian.sh` ([source](./bootstrap/bootstrap-debian.sh)).
* [x] Replace other mentions of the older version of go (grep for `golang:<old_version>` and `go<old_version>`).
* [ ] Update the `builder.dockerImage` parameter in the TeamCity [`Cockroach`](https://teamcity.cockroachdb.com/admin/editProject.html?projectId=Cockroach&tab=projectParams) and [`Internal`](https://teamcity.cockroachdb.com/admin/editProject.html?projectId=Internal&tab=projectParams) projects.
* [ ] Ask the Developer Infrastructure team to deploy new TeamCity agent images according to [packer/README.md](./packer/README.md)

Release note (build change): Upgrade to golang 1.18.4

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 58 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @msbutler, @rickystewart, and @tbg)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VfhJjD1rYVH9uzcAQ:-N7VfhJk-XCB0XaDthgC:bubmyox) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/ccl/changefeedccl/changefeed_stmt.go#L978)):*
> ```Go
> 				// due to a transient, retryable error.
> 				err = jobs.MarkAsRetryJobError(err)
> 				lastRunStatusUpdate = b.setJobRunningStatus(ctx, lastRunStatusUpdate, "retryable flow error: %s", err)  //lint:ignore SA4006
> ```

This looks like an outright bug. I'd remove the lint ignore directive and ask @honoredb what's up with it.
___
*[`pkg/cli/debug_merge_logs.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VfzANAgOZqL5MoQEV:-N7VfzANAgOZqL5MoQEW:bsossdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/cli/debug_merge_logs.go#L341)):*
> ```Go
> 	}
> 	//lint:ignore SA4006
> 	to = to.Truncate(time.Second) // log files only have second resolution
> ```

The fact that `to` is not used any more is either a bug (the code below should use it), or a remnant from a previous version.
In any case, a linter ignore here is not desirable.
@abarganier what should we do here?
___
*[`pkg/kv/kvserver/deprecated_store_rebalancer.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VgD9M-7k7HDx56avf:-N7VgD9M-7k7HDx56avg:b-ezq8pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f650c14a3f1b73b80ab7fc1713991d7897f55e05/pkg/kv/kvserver/deprecated_store_rebalancer.go#L124)):*
> ```Go
> 			}
> 
> 			filteredStoreList := storeList.ExcludeInvalid(conf.Constraints)
> ```

wowzer. This also looks like a bug. The removal you just made doesn't look like the right fix? I think we need to combine them somehow.
Even though the file name  says "deprecated" I believe this code is still in use.

@aayushshah15 what do you think?
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VgOmW8pN7CuBNlnuB:-N7VgOmW8pN7CuBNlnuC:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f650c14a3f1b73b80ab7fc1713991d7897f55e05/pkg/kv/kvserver/store_rebalancer.go#L461)):*
> ```Go
> 		}
> 
> 		filteredStoreList := allStoresList.ExcludeInvalid(conf.Constraints)
> ```

ditto
___
*[`pkg/sql/colexec/columnarizer.go` line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7Vgj21Cb_tAHTwYjPc:-N7Vgj21Cb_tAHTwYjPd:b-wflx8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/sql/colexec/columnarizer.go#L218)):*
> ```Go
> 		newRows := make(rowenc.EncDatumRows, c.batch.Capacity())
> 		_ = newRows[len(oldRows)]
> 		//lint:ignore S1001
> ```

Maybe add a comment to explain we're avoiding copy because we need gcassert below.

( @yuzefovich could we use copy here? That's what the compiler is trying to tell us. )
___
*[`pkg/sql/opt/cat/zone.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7Vh5bqDq09TTNlcstT:-N7Vh5brDWHHEGzrThb6:b-40iiuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/sql/opt/cat/zone.go#L308)):*
> ```Go
> 	voterChild := zoneChild
> 	if zone.VoterConstraintsCount() > 1 {
> 		voterChild = voterChild.Childf("voter replica constraints")  //lint:ignore SA4006
> ```

This also looks suspicious. I don't think we should ignore this linter warning.
@mgartner @rytaft do you want to have a look?
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 4122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VhFUtELxBMljsUoly:-N7VhFUtELxBMljsUolz:bdlcv49) ([raw file](https://github.com/cockroachdb/cockroach/blob/f650c14a3f1b73b80ab7fc1713991d7897f55e05/pkg/sql/opt/memo/statistics_builder.go#L4122)):*
> ```Go
> 
> 	for f := 0; f < len(h.filters); f++ {
> 		conjunctSelectivity = props.OneSelectivity
> ```

Here i'm also not what's up - why are we not looking at the conjunct selectivity any more?

cc @rytaft @mgartner 
___
*[`pkg/sql/opt/xform/scan_funcs.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VhWmY6FQGJ7_-FFcy:-N7VhWmY6FQGJ7_-FFcz:barezyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/sql/opt/xform/scan_funcs.go#L320)):*
> ```Go
> 	// let's not hide the problem by still generating a locality-optimized search
> 	// that doesn't fully cover local spans.
> 	//lint:ignore S1009
> ```

It's possible we do care about the difference between a nil slice reference and a zero-sized non-nil slice here, but I'm not sure.
Perhaps the code can indeed be simplified. If we keep it, we need an explanatory comment to motivate the linter ignore.

@mgartner can you provide guidance?

**Comment by rickystewart** [comment]
I've already contacted a couple people about some of these linter failures (but not all of them).

@rytaft addressed the problem with `zone.go` in #84768.

@ajwerner addressed the problem with `debug_merge_logs.go` in #84769.

I reached out to @aayushshah15 about the `store_rebalancer` issues but did not get a response yet.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @msbutler, @rickystewart, and @tbg)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VfhJjD1rYVH9uzcAQ:-N7WEQD1DYC1l_tBT306:b-bkamz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/ccl/changefeedccl/changefeed_stmt.go#L978)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This looks like an outright bug. I'd remove the lint ignore directive and ask @honoredb what's up with it.
</blockquote></details>

I don't know;... it's True that we return below; but normally lastRunStatusUpdate is used, and is updated in a loop;
I suppose we could say "_ = b.setJobRunningStatus"... But is it that much better?  It's definitely not a bug.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @msbutler, @rickystewart, and @tbg)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VfhJjD1rYVH9uzcAQ:-N7WEcwC5thITsXzwRVb:b-ff1za6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/ccl/changefeedccl/changefeed_stmt.go#L978)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't know;... it's True that we return below; but normally lastRunStatusUpdate is used, and is updated in a loop;
I suppose we could say "_ = b.setJobRunningStatus"... But is it that much better?  It's definitely not a bug.
</blockquote></details>

Also, ignoring return values.. perhaps it's a thing, but I personally really don't like it.

**Comment by HonoreDB** [comment]
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7VfhJjD1rYVH9uzcAQ:-N7WEeF-6IGlc60nchpR:buqxd26) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/ccl/changefeedccl/changefeed_stmt.go#L978)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Also, ignoring return values.. perhaps it's a thing, but I personally really don't like it.
</blockquote></details>

Agree that it's not a bug. It's confusing to ignore the return value but arguably it'd be worse to have two different methods that do the same thing but one returns nothing.

**Comment by rickystewart** [comment]
> Here i'm also not what's up - why are we not looking at the conjunct selectivity any more?

The lint failure is:

```
pkg/sql/opt/memo/statistics_builder.go:4122:3: this value of conjunctSelectivity is never used (SA4006)
```

Looked to me like the initialization was unnecessary, but if this is an actual bug we can also resolve another way.

**Comment by rickystewart** [comment]
Going off the discussion above I updated `pkg/ccl/changefeedccl/changefeed_stmt.go` to explicitly ignore the return value.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @knz, @msbutler, @rickystewart, and @tbg)

___
*[`pkg/sql/colexec/columnarizer.go` line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-N7Vgj21Cb_tAHTwYjPc:-N7WWaAu6o-d2zEXOjzX:brhrua6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b005b602faabdeecc4a899b371dfd6f2a0a28913/pkg/sql/colexec/columnarizer.go#L218)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe add a comment to explain we're avoiding copy because we need gcassert below.

( @yuzefovich could we use copy here? That's what the compiler is trying to tell us. )
</blockquote></details>

We can replace the first `for` loop with the copy (it'd be nicer to put that `copy` before `_ = newRows[len(oldRows)]` line).

**Comment by rickystewart** [comment]
> We can replace the first for loop with the copy (it'd be nicer to put that copy before _ = newRows[len(oldRows)] line).

Done.

**Comment by rickystewart** [comment]
Already raised this to @knz in a DM, but I'm seeing these deprecation errors in non-test code (plus the same errors in `pkg/util/contextutil/context_test.go`).

```
        pkg/util/netutil/net.go:140:52: ne.Temporary has been deprecated since Go 1.18 because it shouldn't be used: Temporary errors are not well-defined. Most "temporary" errors are timeouts, and the few exceptions are surprising. Do not use this method.  (SA1019)
    lint_test.go:1765:
        pkg/util/netutil/net.go:173:11: netError.Temporary has been deprecated since Go 1.18 because it shouldn't be used: Temporary errors are not well-defined. Most "temporary" errors are timeouts, and the few exceptions are surprising. Do not use this method.  (SA1019)
```

**Comment by knz** [comment]
Hi Ricky
can we add a linter ignore for SA1019 on these two cases.
I have investigated this, and there's currently no better implementation in the go stdlib than the `Temporary()` interface, despite what the deprecation notice says. For example, an  `EAI_AGAIN` address resolution failure in the C stdlib should be retried, but go does not offer visibility into this other than `Temporary()`.

**Comment by rickystewart** [comment]
> can we add a linter ignore for SA1019 on these two cases.

OK, done.

**Comment by rickystewart** [comment]
This is now passing CI and apparently fully ready for review. 🙏 

I've added a lint ignore directive for every lint error that someone hasn't already given me a dedicated fix for.

**Review by knz — APPROVED** [review]
:lgtm: nice :100: :fire: 

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 3 files at r7, 12 of 14 files at r9, 13 of 13 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84590#-:-N7lpBGK0zl2xy2UYdWD:bvsaf5x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @knz, @msbutler, @rickystewart, and @tbg)

**Comment by rickystewart** [comment]
TFTR!

bors r=knz

**Pull request merged**
