### PR TITLE
colexec: fix hash joiner when types of inputs are different

### LINKED ISSUE #44547: Internal error for NATURAL JOIN and VECTORIZE='experimental_on'
Consider the following test case:

```sql
SET SESSION VECTORIZE='experimental_on';
CREATE TABLE t0(c0 INT4);
CREATE TABLE t1(c0 INT8);
INSERT INTO t0(c0) VALUES(0);
INSERT INTO t1(c0) VALUES(0);
SELECT * FROM t0 NATURAL JOIN t1; -- internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int32, not []int64
```

Unexpectedly, the `SELECT` results in an error with the following stacktrace:

```
ERROR: internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int32, not []int64
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:70: func1()
runtime/panic.go:679: gopanic()
runtime/iface.go:255: panicdottypeE()
github.com/cockroachdb/cockroach/pkg/col/coldata/vec.go:202: Int64()
github.com/cockroachdb/cockroach/pkg/sql/colexec/hashtable.eg.go:398: rehash()
github.com/cockroachdb/cockroach/pkg/sql/colexec/hashtable.go:332: computeBuckets()
github.com/cockroachdb/cockroach/pkg/sql/colexec/hashtable.go:363: lookupInitial()
github.com/cockroachdb/cockroach/pkg/sql/colexec/hashjoiner.go:442: exec()
github.com/cockroachdb/cockroach/pkg/sql/colexec/hashjoiner.go:223: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:149: next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:140: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:91: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:177: Next()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:170: Run()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:749: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:375: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:977: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:877: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:769: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:471: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1316: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1245: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:452: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:566: func1()
runtime/asm_amd64.s:1357: goexit()
```

I found this bug based on commit `bf96530216efcaaafcd3e88db22089b4f0269480`.

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, an assumption that two inputs to the hash joiner have
exactly the same types in the equality columns was built in into the
operator. However, this is incorrect - the types have to comparable.
This is now fixed by specifying the types of the probe side explicitly.

Fixes: #44547.

Release note: None (hash joiner was planned only with experimental_on
vectorize setting).

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-O7G1C-lFAee4XwMW0:-M-O7G1C-lFAee4XwMW1:b-sixpmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/distsql/columnar_operators_test.go#L467)):*
> ```Go
> 									//rInputTypes = generateRandomComparableTypes(rng, lInputTypes)
> 									// TODO(yuzefovich): use the commented out line instead.
> 									rInputTypes = lInputTypes
> ```

There are some bugs that need to be fixed before we can use it on master (for example, #44797, possibly others).
___
*[pkg/sql/distsql/columnar_operators_test.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-O7QtqA32EWn60a18J:-M-O7QtqA32EWn60a18K:bh0sntq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/distsql/columnar_operators_test.go#L643)):*
> ```Go
> 								//rInputTypes = generateRandomComparableTypes(rng, lInputTypes)
> 								// TODO(yuzefovich): use the commented out line instead.
> 								rInputTypes = lInputTypes
> ```

Merge joiner actually suffers from the same problem as what this PR is fixing in the hash joiner - the assumption of exactly the same types on the equality columns. Filed an issue for that.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-O7G1C-lFAee4XwMW0:-M-Q4-tFE6wkL5f24lrT:b-lk4svs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/distsql/columnar_operators_test.go#L467)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

There are some bugs that need to be fixed before we can use it on master (for example, #44797, possibly others).
</blockquote></details>

Can we return an error if the probe types don't equal the build types until the bugs are fixed? Do you know what the bug is or simply that there is a bug but don't know yet?
___
*[pkg/sql/logictest/testdata/logic_test/exec_hash_join, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-Q4CV_7bxL1JcrVcXf:-M-Q4CV_7bxL1JcrVcXg:b-c3ucrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/logictest/testdata/logic_test/exec_hash_join#L173)):*
> ```
> NULL 0
> 
> # Regression test for the inputs have comparable but different types.
> ```

nit: `s/inputs have/inputs that have`. May be useful to link the issue number as well.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-O7G1C-lFAee4XwMW0:-M-Q7-YrDYInYQq3x_xN:b-oti01p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/distsql/columnar_operators_test.go#L467)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we return an error if the probe types don't equal the build types until the bugs are fixed? Do you know what the bug is or simply that there is a bug but don't know yet?
</blockquote></details>

I'd rather not return an error because still hash joiner is used only with `experimental_on`, and running it on master might help us uncover more issues (wink-wink at MRigger). I know that there is at least one bug, possibly others, but I didn't look into it.
___
*[pkg/sql/logictest/testdata/logic_test/exec_hash_join, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-Q4CV_7bxL1JcrVcXf:-M-Q7lgC7E1E5ouVXaG3:b-caj9l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/logictest/testdata/logic_test/exec_hash_join#L173)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/inputs have/inputs that have`. May be useful to link the issue number as well.
</blockquote></details>

Fixed.

I started putting the issue number in the table names if possible, and then having only text description of the issue. Personally, I like this convention.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-O7G1C-lFAee4XwMW0:-M-QD64v7tt8zjMYuH8M:b-rzhjbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/distsql/columnar_operators_test.go#L467)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'd rather not return an error because still hash joiner is used only with `experimental_on`, and running it on master might help us uncover more issues (wink-wink at MRigger). I know that there is at least one bug, possibly others, but I didn't look into it.
</blockquote></details>

I think I know what the problem is even without debugging - we use different hash functions for different physical types (i.e. for `int64` and `int16` for example), so when we're probing, there are no matches of hash values. We'll probably have to convert all ints to int64 before hashing and remove int32 and int16 hash variants.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-:-M-QItqa9JUQoupluNTg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44796#-M-O7G1C-lFAee4XwMW0:-M-QIQ1SDlRG_UUWGzUU:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c02526f4265b7f88c9d9bf50a51e23e36c4cb1a/pkg/sql/distsql/columnar_operators_test.go#L467)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think I know what the problem is even without debugging - we use different hash functions for different physical types (i.e. for `int64` and `int16` for example), so when we're probing, there are no matches of hash values. We'll probably have to convert all ints to int64 before hashing and remove int32 and int16 hash variants.
</blockquote></details>

SGTM.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
