### PR TITLE
storage: Document locking of Store and Replica

### LINKED ISSUE #4476: storage: Prevent/handle replica ID changes in `handleRaftReady`
`handleRaftReady` releases and reacquires the replica's lock several times. It would be bad if the replica ID changed during that time (and therefore the raftGroup was replaced with a new object). We need to either ensure that it is impossible for the replica ID to change during `handleRaftReady` (this may already be true by accident, but if so we should at least document what locks/goroutines/etc provide this guarantee), or handle it gracefully (which may be as easy as skipping the final `Advance` call if the replica ID changes over the course of the method. 

We should also simplify the concurrency of this method by reducing the number of distinct lock/unlock pairs and ensure that there are no other bad interactions with other methods while the lock is released.

### LINKED ISSUE #7710: storage: internal documentation of Store and Replica locking/synchronization
Similar to #7704 and #7683. Document the locking and synchronization used by `Store` and `Replica`, specifically `Store.processRaftMu`, the `Store` raft goroutine, `Store.mu.Mutex`, `Store.pendingRaftGroups.mu.Mutex` and `Replica.mu.Mutex`.

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes #7710
Fixes #4476

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7736)

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store.go, line 325 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMM5iv1EECLag-YvYL9:-KMM5iv1EECLag-YvYLA:-1791335652) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L325)):*
> ```Go
> 
> 	// Locking notes: To avoid deadlocks, the following lock order must
> 	// be obeyed: Store.processRaftMu < Replica.readOnlyCmdMu <
> ```

Just to be 100% clear, can we explicitly define the < relation? I'm assuming that X.mu < Y.mu means that X.mu needs to be acquired before Y.mu is acquired.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store.go, line 325 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMM5iv1EECLag-YvYL9:-KMM8-Nf190Hs9v63vTl:-2121383359) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L325)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Ravi Narayan) wrote…</i></summary>
> Just to be 100% clear, can we explicitly define the < relation? I'm assuming that X.mu < Y.mu means that X.mu needs to be acquired before Y.mu is acquired.
</details>
Correct. I think this notation came from the google-internal precursor to https://www.chromium.org/developers/lock-and-condition-variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736)*

**Comment by petermattis** [comment]
:lgtm:

Probably should file an issue or issues regarding the new TODOs. 

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 327 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMH8y-zU6T0KKAREd-:-KMMH8y0Qnus_R1679Uf:-533729327) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L327)):*
> ```Go
> 	// be obeyed: Store.processRaftMu < Replica.readOnlyCmdMu <
> 	// Store.mu.Mutex < Replica.mu.Mutex <
> 	// Store.pendingRaftGroups.Mutex.
> ```

Whoa, holy lock hierarchy!

---

*[storage/store.go, line 338 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMK4PT7lk8bQQlijFl:-KMMK4PU0qWanNgte3Qw:1783168062) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L338)):*
> ```Go
> 	// (including splits) modify the Store. Therefore we generally lock
> 	// Store.mu to find a Replica, release it, then call a method on the
> 	// Replica.
> ```

I think it's also worth calling out `processRaftMu` and its special powers here. Or at least mentioned that mutex and pointing to the paragraph below. I personal finally the `Store.mu` and `Replica.mu` locking reasonable, but `processRaftMu` subtle. 

---

*[storage/store.go, line 342 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMHOocjsMenVjBSjKi:-KMMHOocjsMenVjBSjKj:1803422165) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L342)):*
> ```Go
> 	// There are two major entry points to this stack of locks:
> 	// Store.Send (which handles incoming RPCs) and raft-related message
> 	// processing. Reads are processed solely through Store.Send; writes
> ```

Is "raft-related message processing" equivalent to `Store.processRaft`? If so, can you call that out explicitly.

---

*[storage/store.go, line 379 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMJ2lmWLJf_oKz-X6Z:-KMMJ2lmWLJf_oKz-X6_:-930466388) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L379)):*
> ```Go
> 	//
> 	// * Replica.mu: Protects the Replica's in-memory state. Acquired
> 	//   and released briefly as needed. This lock should be held when
> ```

If this lock is held when calling raft methods, then I'm not sure if that qualifies as briefly given that Raft might calling `Replica.Snapshot` and other `Storage`-interface methods that do I/O.

---

*[storage/store.go, line 407 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMJLXhF_khpO4U5C6T:-KMMJLXhF_khpO4U5C6U:-496223046) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L407)):*
> ```Go
> 	// accesses the replicaID more than once, and we rely on
> 	// processRaftMu to ensure that this is not modified by a concurrent
> 	// handleRaftMessage. (#4476)
> ```

This is where a lot of subtlety is IMO. What prevents a replica from being destroyed during `Replica.handleRaftReady` or any time `Replica.mu` is released? I think the answer is almost always `processRaftMu`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-:-KMMH_dAHZLFfMV7DfVq:1713988851)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 338 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMK4PT7lk8bQQlijFl:-KMQuRgyeAab_fPUfBVY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L338)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think it's also worth calling out `processRaftMu` and its special powers here. Or at least mentioned that mutex and pointing to the paragraph below. I personal finally the `Store.mu` and `Replica.mu` locking reasonable, but `processRaftMu` subtle. 
</details>
Done.

---

*[storage/store.go, line 342 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMHOocjsMenVjBSjKi:-KMQuTLmwSfLtHF67jGI:1232229386) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L342)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Is "raft-related message processing" equivalent to `Store.processRaft`? If so, can you call that out explicitly.
</details>
Almost: it's processRaft/handleRaftReady and handleRaftMessage.

---

*[storage/store.go, line 379 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMJ2lmWLJf_oKz-X6Z:-KMQuZEMAcDoHLg3SzgE:-1892359667) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L379)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> If this lock is held when calling raft methods, then I'm not sure if that qualifies as briefly given that Raft might calling `Replica.Snapshot` and other `Storage`-interface methods that do I/O.
</details>
Maybe. I called it "brief" because it's not held throughout an entire request. I'll explain that it's still held while doing I/O in some cases (including `Replica.Entries`, but *not* `Replica.Snapshot` - that does all its I/O on a background goroutine)

---

*[storage/store.go, line 407 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMJLXhF_khpO4U5C6T:-KMQv4RV2z8Cq7J1Yaxq:2101406455) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L407)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This is where a lot of subtlety is IMO. What prevents a replica from being destroyed during `Replica.handleRaftReady` or any time `Replica.mu` is released? I think the answer is almost always `processRaftMu`. 
</details>
Right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 327 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736#-KMMH8y-zU6T0KKAREd-:-KMUeBWoxy_zu6t9Ir7B:-2135375608) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a998053ccc9b7dcad32076da8d36914d875bcb/storage/store.go#L327)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Whoa, holy lock hierarchy!
</details>
Yeah, I lost *days* to grokking this lock hierarchy through trial and error. Perhaps we should think about whether there's a better way to do things, or at least document this hierarchy more explicitly. There are entire classes of methods that cannot be used after certain locks are acquired (and since there's this lattice of locks, you need to be aware of all your callers and which locks they might have acquired), and apart from recursively reading through every method description that you call, there's no real way of figuring it out ahead of time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7736)*

**Pull request merged**
