### PR TITLE
*: Prep work for supporting CONFIGURE ZONE in declarative schema changer

### PR DESCRIPTION
**Pull request by Xiang-Gu**
This PR consists several preparation work that will be needed for properly supporting CONFIGURE ZONE stmts in declarative schema changer. They're separated out for easier review and bc I expect those to be a lot less controversial than the main work. See each commit for details.

Informs #117574
Epic: CRDB-31473

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 11 of 11 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117572)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @michae2, @srosenberg, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 1129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpMcRT1UMUrfgd2hx3:-NnpMcRT1UMUrfgd2hx4:brkjumr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e44fd516e92386c0fc9703c2e8cc65f772423d96/pkg/sql/schemachanger/scbuild/builder_state.go#L1129)):*
> ```Go
> 	}
> 	if p.RequiredPrivilege != 0 {
> 		if err := b.checkPrivilege(rel.GetID(), p.RequiredPrivilege); err != nil {
> ```

We could have a helper called requirePrivilege which does the panic, avoid duplication
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 226 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpKeAM9wCTRjD80YL6:-NnpKeAM9wCTRjD80YL7:baqkpxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d57ef4f762aed738872e88dea5888ef8ea4d93ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L226)):*
> ```Go
> 	// CheckGlobalPrivilege panics if the current user does not have the specified
> 	// global privilege.
> 	CheckGlobalPrivilege(privilege privilege.Kind) error
> ```

I think this fine. Just to play devils advocate is there any case where the element model will be responsible for granting the privilege and we need to be aware?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpMN0BDNA5GTK2n3Yw:-NnpMN0BDNA5GTK2n3Yx:b-2ff4m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e44fd516e92386c0fc9703c2e8cc65f772423d96/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L338)):*
> ```Go
> 	// descriptor.
> 	// If 0, no privilege checking is performed.
> 	RequiredPrivilege privilege.Kind
> ```

Have a constant for this behaviour?

**Review by fqazi — COMMENTED** [review]
This is all pretty good, just some minor comments / suggestions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-:-NnpMoqm-tgs1vqB746V:b-xxd9e0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @michae2, @srosenberg, and @Xiang-Gu)

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117572)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @fqazi, @michae2, @rafiss, and @srosenberg)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 1129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpMcRT1UMUrfgd2hx3:-Nnt94Ki2VSZ2PB3I8qN:b-3vu7o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e44fd516e92386c0fc9703c2e8cc65f772423d96/pkg/sql/schemachanger/scbuild/builder_state.go#L1129)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We could have a helper called requirePrivilege which does the panic, avoid duplication
</blockquote></details>

done. In fact, I went a step further to push the check for `priv == 0 { return }` down into `hasPrivileges` to further reduce duplication. This will allow us to call into CheckPrivilege with priv==0.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 226 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpKeAM9wCTRjD80YL6:-Nnt8HJ29AILnhq6kVaB:b-bfvbm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d57ef4f762aed738872e88dea5888ef8ea4d93ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L226)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think this fine. Just to play devils advocate is there any case where the element model will be responsible for granting the privilege and we need to be aware?
</blockquote></details>

I think when we implement `GRANT/REVOKE` in the declarative schema changer, we will need to introduce elements whose transitioning to PUBLIC/REVOKE emits operations to grant/revoke privileges to descriptors (or to grant/revoke global privileges). 

Why? Does that somehow affect/change anything here?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpMN0BDNA5GTK2n3Yw:-NntEaBh6bv7wHMugod6:b3ofzcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e44fd516e92386c0fc9703c2e8cc65f772423d96/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L338)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Have a constant for this behaviour?
</blockquote></details>

I have some worries that adding a new constant to the list of privileges in `privileges/kind.go` is going to make the privilege API more confusing. I discussed this with @rafiss offline and he agrees that we can just do `if priv == 0` without introducing a new privilege constant.

**Review by fqazi — APPROVED** [review]
> Reviewed 15 of 15 files at r5, 3 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117572)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @michae2, @rafiss, @srosenberg, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 1129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpMcRT1UMUrfgd2hx3:-Nnu7bpD4N0g_R0E3NIi:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e44fd516e92386c0fc9703c2e8cc65f772423d96/pkg/sql/schemachanger/scbuild/builder_state.go#L1129)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

done. In fact, I went a step further to push the check for `priv == 0 { return }` down into `hasPrivileges` to further reduce duplication. This will allow us to call into CheckPrivilege with priv==0.
</blockquote></details>

Nice!
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 226 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpKeAM9wCTRjD80YL6:-Nnu7fQs8g9UIzm6RBqE:b-gh7gmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d57ef4f762aed738872e88dea5888ef8ea4d93ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L226)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I think when we implement `GRANT/REVOKE` in the declarative schema changer, we will need to introduce elements whose transitioning to PUBLIC/REVOKE emits operations to grant/revoke privileges to descriptors (or to grant/revoke global privileges). 

Why? Does that somehow affect/change anything here?
</blockquote></details>

Nope, just thinking if we need to poke at these interfaces in the future, but this in the builder so it can fetch those elements if needed.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117572#-NnpMN0BDNA5GTK2n3Yw:-Nnu7ocCBXrDsVmbTzzt:br92akv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e44fd516e92386c0fc9703c2e8cc65f772423d96/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L338)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I have some worries that adding a new constant to the list of privileges in `privileges/kind.go` is going to make the privilege API more confusing. I discussed this with @rafiss offline and he agrees that we can just do `if priv == 0` without introducing a new privilege constant.
</blockquote></details>

I was just suggesting a constant in the scbuild package not a global one.

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
