### PR TITLE
ci: update pebble metamorphic nightly to use bazel

### LINKED ISSUE #67335: ci: duplicate `Pebble Nightly - AWS` build config for ci
Epic CRDB-8306

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #67335.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
successful run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyPebbleMetamorphicBazelTesting/4241971?showRootCauses=false

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75585#-:-MukzfYgER9iGkrLuFqm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/patches/com_github_cockroachdb_pebble.patch, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75585#-MukyFcgBP8PEJIguCD4:-MukyFcgBP8PEJIguCD5:b-564eg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a25a0d9ac1813248af77120dd6fe2a58a9beb92/build/patches/com_github_cockroachdb_pebble.patch#L8)):*
> ```Diff
>          "finalizer_off.go",
>          "finalizer_on.go",
> +        "off.go",
> ```

What's the reason for needing this patch? Any way we can put a comment somewhere about it?
___
*[pkg/cmd/mirror/mirror.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75585#-MukzIiIBQaAs2I25Zkh:-MukzIiIBQaAs2I25Zki:b948bgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a25a0d9ac1813248af77120dd6fe2a58a9beb92/pkg/cmd/mirror/mirror.go#L458)):*
> ```Go
> 		fmt.Printf(`    go_repository(
>         name = "%s",
> `, repoName)
> ```

nit: formatting

**Comment by rickystewart** [comment]
> What's the reason for needing this patch? Any way we can put a comment somewhere about it?

Done (put in `README.md` for that folder).

> nit: formatting

Not sure exactly what this comment means, but the whitespace is significant here.

**Comment by nicktrav** [comment]
> Not sure exactly what this comment means, but the whitespace is significant here.

Disregard. I didn't notice the backticks.

**Comment by rickystewart** [comment]
TFTR!

bors r=nicktrav

**Pull request merged**
