### PR TITLE
storage: Get wait chans for local spans from local command queue

### PR DESCRIPTION
**Pull request by a-robinson**
This looks like a copy-and-paste bug that could cause some inconsistent/mis-ordered reads when reading range-local data, but maybe it's just confusing code that needs a comment?

edit: Looks like this is also in the write path, so scratch the part of my original comment about this only affecting reads.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12770)

### CODE REVIEW

**Comment by tamird** [comment]
Looks like a bug to me. Care to add a test?

**Comment by a-robinson** [comment]
Yeah, I can try adding a test. cc @bdarnell for double confirmation that this wasn't intended.

**Comment by petermattis** [comment]
Looks like a bug to me too.

**Comment by bdarnell** [comment]
Definitely not intended. The only range-local data that currently uses the command queue is the range descriptor so this could potentially cause problems around concurrent splits and rebalances, although I don't think we've seen any evidence of this. The local command queue is about to get a lot more important with propEvalKV.

**Comment by a-robinson** [comment]
@tamird on second glance, is this something that really needs its own test?

**Comment by tamird** [comment]
Given the presence of this bug, don't you think so?

**Comment by bdarnell** [comment]
Doesn't need to be a new test from scratch, but we should probably have new subtests of TestReplicaCommandQueue that use local keys rather than global ones.

**Comment by a-robinson** [comment]
Alright, done. Although it took much longer than expected because I found out that TestReplicaCommandQueue wasn't really working very well. I've fixed the existing version of the test in the second commit and added the local keys to it in the third commit (along with the fix that motivated this PR). The new first commit is just a minor de-duplication of logic in the keys package.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12770#-:-Ka40VJupBVmvuvQ7clb:bnfp4nl)*

**Pull request merged**
