### PR TITLE
proto: add functionality to marshal protobuf binary from file descriptor

### PR DESCRIPTION
**Pull request by cpustejovsky**
see commit message for details.

### CODE REVIEW

**Comment by rimadeodhar** [comment]
Hi @cpustejovsky,  we appreciate your contribution and the time you've invested in creating this PR. Unfortunately, our DB team is facing a high workload at the moment and we likely won't be able to review your PR anytime soon. My apologies for the inconvenience. We will prioritize this for review once we have more bandwidth available. 

If you have any questions or concerns in the meantime, please feel free to reach out. We appreciate your understanding and continued collaboration.

**Comment by cpustejovsky** [comment]
@rimadeodhar is this for this specific PR and issue or for all community contributions?

**Review by fqazi — CHANGES_REQUESTED** [review]
A couple of minor comments, otherwise I think this looks fairly reasonable.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116262#-:-O-bbDyzDniATKATTFM2:blilxb2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @cpustejovsky)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116262#-O-bZ2j9B_Cp2dwiP0e3):*
Informs: #47534
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116262#-O-bYLDb-XLJ6M2U6gEs):*
Nit: NewJSONMessageFromFileDescriptor
___
*[`pkg/sql/protoreflect/gprototest/gprototest.proto` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116262#-O-bYhCNER3O202D96bm:-O-bYhCNER3O202D96bn:b-a9kugn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fbde84bd8da5a7cb6ae6a8a612c95fec100abc0/pkg/sql/protoreflect/gprototest/gprototest.proto#L1)):*
> ```proto
> // Copyright 2021 The Cockroach Authors.
> ```

Nit: update the year
___
*[`pkg/util/protoutil/marshal.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116262#-O-baqpZ394O9d_OE8wH:-O-baqpZ394O9d_OE8wI:bf93ouu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fbde84bd8da5a7cb6ae6a8a612c95fec100abc0/pkg/util/protoutil/marshal.go#L79)):*
> ```Go
> }
> 
> func TODOMarshal(pb gproto.Message) ([]byte, error) {
> ```

Lets add a comment indicating this is short term to workaround the linter and to use the latest Protobuf package

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116262#-:-O-fkpXrBe61LDVkO20N:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @cpustejovsky)

**Pull request merged**
