### PR TITLE
sql: add event logs for SET SCHEMA statements

### LINKED ISSUE #57741: sql: missing event log entries for ALTER .. SET SCHEMA statements
We have event log entries for table/views/sequence renames, however no event log entry is generated for SET SCHEMA.

This is inconsistent, as SET SCHEMA definitely changes the way that objects are named.

(Also arguably ALTER TYPE RENAME should also have a separate event log type)

Found while working on #57737

### PR DESCRIPTION
**Pull request by the-ericwang35**
Fixes https://github.com/cockroachdb/cockroach/issues/57741.

Previously, we had event log entries for table/views/sequence renames,
however no event log entry is generated for SET SCHEMA.
This is inconsistent, as SET SCHEMA changes the way that objects are named.
To address this, this patch adds event logs for SET SCHEMA statements.

Release note (bug fix): add event logs for SET SCHEMA statements

### CODE REVIEW

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/set_schema.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MQylbYf4ePjJ7wyAK6o:-MQylbYf4ePjJ7wyAK6p:b-81fse9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58831054e42c5d0900eea6908d9da97605cc132/pkg/sql/set_schema.go#L69)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	oldSchemaQualified, err := p.getQualifiedSchemaName(ctx, oldSchema)
> 	if err != nil {
> 		return 0, err
> 	}
> ```
</details>


In retrospect, this isn't what we want. When we're setting the schema on something, what we want is the fully qualified name of the thing before and after. That will clearly imply what the old and new schema names are as well as what was actually moved.

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/set_schema.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MQylbYf4ePjJ7wyAK6o:-MR5sd_MAjopX1qHLJ1z:brfbm6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58831054e42c5d0900eea6908d9da97605cc132/pkg/sql/set_schema.go#L69)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	oldSchemaQualified, err := p.getQualifiedSchemaName(ctx, oldSchema)
> 	if err != nil {
> 		return 0, err
> 	}
> ```

In retrospect, this isn't what we want. When we're setting the schema on something, what we want is the fully qualified name of the thing before and after. That will clearly imply what the old and new schema names are as well as what was actually moved. 
</blockquote></details>

Done, changed it to the fully qualified name

**Review by thoszhang — COMMENTED** [review]
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/sql/alter_table_set_schema.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MRftczGDuR2BIruiI7i:-MRftczGDuR2BIruiI7j:b-mm4gsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1062389017727d6a61749fcde97a6f4f98dc3d1d/pkg/sql/alter_table_set_schema.go#L188)):*
> ```Go
> 
> // getKind returns a string representation of the table descriptor.
> func getKind(td catalog.TableDescriptor) string {
> ```

Can we use `tree.GetTableType()` for this?
___
*[pkg/sql/resolver.go, line 428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MRfuUkf89Nn8PQXcuij:-MRfuUkf89Nn8PQXcuik:bq8yhyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1062389017727d6a61749fcde97a6f4f98dc3d1d/pkg/sql/resolver.go#L428)):*
> ```Go
> // getQualifiedTypeName returns the database-qualified name of the type
> // represented by the provided descriptor.
> func (p *planner) getQualifiedTypeName(
> ```

Can we unify this with the existing `getQualifiedTableName` method and call it `getQualifiedObjectName` (returning a `tree.ObjectName`)?

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/alter_table_set_schema.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MRftczGDuR2BIruiI7i:-MRqYLaKDkGbL0hqDtnB:b-9f087b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1062389017727d6a61749fcde97a6f4f98dc3d1d/pkg/sql/alter_table_set_schema.go#L188)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can we use `tree.GetTableType()` for this?
</blockquote></details>

Yep, done.
___
*[pkg/sql/resolver.go, line 428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MRfuUkf89Nn8PQXcuij:-MRqjOey4yrKPD7QQLY3:b-84zr0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1062389017727d6a61749fcde97a6f4f98dc3d1d/pkg/sql/resolver.go#L428)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can we unify this with the existing `getQualifiedTableName` method and call it `getQualifiedObjectName` (returning a `tree.ObjectName`)?
</blockquote></details>

Sure, I've made the change. I had to do some type casting down the line since some functions want a `*tree.TableName` rather than a `tree.ObjectName`, please let me know if there are any issues with this.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-:-MS-2cnC66z6aQZWrHrr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

**Review by thoszhang — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/sql/resolver.go, line 428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MRfuUkf89Nn8PQXcuij:-MS-5c4n36I9392uizKP:b-ao6w6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1062389017727d6a61749fcde97a6f4f98dc3d1d/pkg/sql/resolver.go#L428)):*
<details><summary><i>Previously, the-ericwang35 (Eric Wang) wrote…</i></summary><blockquote>

Sure, I've made the change. I had to do some type casting down the line since some functions want a `*tree.TableName` rather than a `tree.ObjectName`, please let me know if there are any issues with this.
</blockquote></details>

Hmm, I think this was actually a bad suggestion. We lose type safety since we have to pass in a `catalog.Descriptor` (arguably we should have a `catalog.ObjectDescriptor` for tables and types, but we don't), and it doesn't really simplify anything. We should probably go back to the way it was before and just have a separate `getQualifiedTypeName`.

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/resolver.go, line 428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58737#-MRfuUkf89Nn8PQXcuij:-MS-QtQO6ISrzPlLEbYl:bnt0gix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1062389017727d6a61749fcde97a6f4f98dc3d1d/pkg/sql/resolver.go#L428)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Hmm, I think this was actually a bad suggestion. We lose type safety since we have to pass in a `catalog.Descriptor` (arguably we should have a `catalog.ObjectDescriptor` for tables and types, but we don't), and it doesn't really simplify anything. We should probably go back to the way it was before and just have a separate `getQualifiedTypeName`.
</blockquote></details>

Sounds good, I've changed it back to have a separate `getQualifiedTypeName`.

**Review by thoszhang — APPROVED** [review]
> Reviewed 18 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58737)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Comment by the-ericwang35** [comment]
TFTR!

bors r+

**Pull request merged**
