### PR TITLE
acceptance: restore caching of pulled images

### PR DESCRIPTION
**Pull request by tbg**
Two main changes:

1. remove the `make build` that I erroneously placed at the end of `acceptance/run.sh`.
   We don't use this in CI, but anyone running `make acceptance` locally might have
   encountered odd behavior.
2. Fix Docker image caching.
   The code had rotted (or never worked correctly), so we were always
   re-pulling the image. Given the inherent flakiness of reaching out to the
   Docker registry, this should significantly reduce our CI failure rate.
   
   Also added a check that prevents regression: when we pull the image we also
   check that we find it again after. This fired before, and now passes.

### CODE REVIEW

**Comment by tamird** [comment]
Nice. :lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/prepare.sh, line 13 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-KsdtG-oB2VhsLFBnCrF:-KsdtG-pi_HS5ODrR4Aq:b-9z1j72) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ee4923dfdfc09a1bf06b7caf56e0ae9b63ade3/pkg/acceptance/prepare.sh#L13)):*
> ```Shell
> echo "Building Docker binary"
> build/builder.sh make build TAGS=clockoffset TYPE=release-linux-gnu
> # Build the standard binary to ./cockroach for those tests that don't use Docker.
> ```

y u no wrap

---

*[pkg/acceptance/cluster/docker.go, line 77 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-Ksdu4cRCOyM6UejFmQ5:-Ksdu4cRCOyM6UejFmQ6:b-3knfps) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36497021dfb3ad2ea480446e00ef919ea7dd42f/pkg/acceptance/cluster/docker.go#L77)):*
> ```Go
> 
> func hasImage(ctx context.Context, l *DockerCluster, ref string) bool {
> 	// At the time of writing, our incoming ref is something like:
> ```

can you use https://godoc.org/github.com/docker/distribution/reference#ParseNamed instead? that's the function used under the hood by the docker client.

```
distributionRef, err := distreference.ParseNamed(ref)
if err ...
images, err := l.client.ImageList(ctx, types.ImageListOptions{
	MatchName: distributionRef.Name(),
	All:       true,
})
if err ...
...
if repoTag == distributionRef.String() {
  return true
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-:-KsdvK4DsgYuiVXvAvn_:b-i2pyn4)*

**Comment by tschottdorf** [comment]
Review status: 6 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/acceptance/cluster/docker.go, line 77 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-Ksdu4cRCOyM6UejFmQ5:-Kse4ODBOsBZYorRv-Iu:b81n2xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36497021dfb3ad2ea480446e00ef919ea7dd42f/pkg/acceptance/cluster/docker.go#L77)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you use https://godoc.org/github.com/docker/distribution/reference#ParseNamed instead? that's the function used under the hood by the docker client.

```
distributionRef, err := distreference.ParseNamed(ref)
if err ...
images, err := l.client.ImageList(ctx, types.ImageListOptions{
	MatchName: distributionRef.Name(),
	All:       true,
})
if err ...
...
if repoTag == distributionRef.String() {
  return true
}
```
</blockquote></details>

Tried, but that `.Name()` is still the wrong thing (library/.../ubuntu`, not `ubuntu`). Added to the comment.

---

*[pkg/acceptance/prepare.sh, line 13 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-KsdtG-oB2VhsLFBnCrF:-Kse4T_MBzSZB1n0kbMa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ee4923dfdfc09a1bf06b7caf56e0ae9b63ade3/pkg/acceptance/prepare.sh#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

y u no wrap
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 8 of 8 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/acceptance/util.go, line 383 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-KseMlUV5EJlcazwESCF:-KseMlUV5EJlcazwESCG:b2r0z6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2567d8cde5e30862289e0658c3208a4575036d/pkg/acceptance/util.go#L383)):*
> ```Go
> 	options ...func(*cluster.TestConfig),
> ) {
> 	ctx, cfg := prepareTest(t)
> ```

what's this method about? it doesn't seem to do anything useful?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960)*

**Comment by tschottdorf** [comment]
:lgtm: thanks for patching this up!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/util.go, line 383 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-KseMlUV5EJlcazwESCF:-KseN2olUPgYPBkrHUpN:br9xg6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2567d8cde5e30862289e0658c3208a4575036d/pkg/acceptance/util.go#L383)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what's this method about? it doesn't seem to do anything useful?
</blockquote></details>

Used in my WIP, but feel free to inline `prepareTest` in this PR.

---

*[pkg/acceptance/zchaos_test.go, line 402 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-KseNLt5E3GrlRzizFNB:-KseNLt5E3GrlRzizFNC:b-ncqnwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857a5309f9e16b1eb7d259423358b7a6d6dd53f/pkg/acceptance/zchaos_test.go#L402)):*
> ```Go
> // The test measures read/write performance in the presence of restarts.
> func TestNodeRestart(t *testing.T) {
> 	s := log.Scope(t)
> ```

Oops, this is spurious. Could you restore that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-:-KseNcxh3fAPJZVSYvlM:b3ybqej)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/util.go, line 383 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-KseMlUV5EJlcazwESCF:-KseSJiX6ZDy5HsDN539:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2567d8cde5e30862289e0658c3208a4575036d/pkg/acceptance/util.go#L383)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Used in my WIP, but feel free to inline `prepareTest` in this PR.
</blockquote></details>

Done.

---

*[pkg/acceptance/zchaos_test.go, line 402 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960#-KseNLt5E3GrlRzizFNB:-KseSPOSKHWZuKZtY1o1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857a5309f9e16b1eb7d259423358b7a6d6dd53f/pkg/acceptance/zchaos_test.go#L402)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Oops, this is spurious. Could you restore that?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17960)*

**Pull request merged**
