### PR TITLE
upgrade: block 24.3 upgrade if core license used

### PR DESCRIPTION
**Pull request by spilchen**
Before this change, clusters using the core license could upgrade to version 24.3 without restriction. With the deprecation of the core license, we now block upgrades to 24.3 if it would lead to license violations that trigger throttling. Since rollback isn’t possible after finalization, it's crucial to prevent upgrades before they finalize.

We now enforce two checks as preconditions, which are evaluated before any upgrade task is run:
- No license is installed, indicating the cluster was previously using the core license.
- A trial or free license is installed, which requires telemetry, but telemetry is disabled.

These checks are built into a new 24.3 upgrade step and run as preconditions. If they fail, the upgrade doesn’t proceed at all. The new upgrade step itself is a no-op, as it doesn't make any persistent changes.

I opted to place these checks in the upgrade step so they only apply when upgrading to 24.3. Once the minimum supported version moves past 25.1+, these checks will be removed.

Epic: CRDB-39988
Closes: CRDB-40068
Release note (general change): Upgrading to 24.3 is blocked if no license is installed, or if a trial/free license is installed with telemetry disabled.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130576)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/clusterversion/cockroach_versions.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130576#-O6bEvBS0mOWCMQFVgBD:-O6bEvBS0mOWCMQFVgBE:b-ue0mgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c43e7bf784ad992ef87114c92b87e14d6a87f4/pkg/clusterversion/cockroach_versions.go#L248)):*
> ```Go
> 	// the cluster would not be unknowingly in violation of the new license
> 	// policies.
> 	V24_3_MaybePreventUpgradeForCoreLicenseDeprecation
> ```

we should check that this results in the desired behavior. i am pretty sure it may not, since if the upgrade reaches this internal version and fails this check, then the upgrade will be stuck at that version. i.e., it will no longer be possible to rollback to 24.2, since the cluster version will already be at 24.2-16.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130576)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/clusterversion/cockroach_versions.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130576#-O6bEvBS0mOWCMQFVgBD:-O6bbFSy8gugHIRueylI:b-chr6j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c43e7bf784ad992ef87114c92b87e14d6a87f4/pkg/clusterversion/cockroach_versions.go#L248)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should check that this results in the desired behavior. i am pretty sure it may not, since if the upgrade reaches this internal version and fails this check, then the upgrade will be stuck at that version. i.e., it will no longer be possible to rollback to 24.2, since the cluster version will already be at 24.2-16.
</blockquote></details>

I did some testing and here are the results I observed:

1.  Created a cluster on 24.2 without a license installed.
2.  Started the server using the 24.3 binary.
3.  Observed in `cockroach.log` that the auto-upgrade was blocked.
4.  Attempted a manual upgrade and got the following error:  
    `roachprod@localhost:26257/defaultdb> SET CLUSTER SETTING version = '24.2-upgrading-to-24.3-step-016';`  
    `ERROR: verifying precondition for version 24.2-upgrading-to-24.3-step-016: upgrade blocked: no license installed`
5.  Verified no 24.2\* entries in `system.migrations`.
6.  Confirmed `SHOW CLUSTER SETTING version` still displayed 24.2.
7.  Downgraded back to 24.2, and the instance started without issues.

The key point here is that the upgrade process runs all preconditions before executing any upgrade tasks. If no license is installed, the precondition fails, and no upgrade tasks are executed.

Perhaps I need to word this description a bit differently so that this is more obvious?

**Review by rafiss — APPROVED** [review]
thanks for confirming. the code and tests lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130576#-:-O6brUTV64LZhjFiSWRf:b-ker2ql)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/clusterversion/cockroach_versions.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130576#-O6bEvBS0mOWCMQFVgBD:-O6bqrDS8BziuMBGnurf:b-vqqd1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c43e7bf784ad992ef87114c92b87e14d6a87f4/pkg/clusterversion/cockroach_versions.go#L248)):*
Thanks for double checking this!

> The key point here is that the upgrade process runs all preconditions before executing any upgrade tasks. If no license is installed, the precondition fails, and no upgrade tasks are executed.

This was the main part I was missing. I forgot that the precondition checks worked in this way. I see the commit message already mentions that, but feel free to emphasize it even more if you think that would help.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130576)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/clusterversion/cockroach_versions.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130576#-O6bEvBS0mOWCMQFVgBD:-O6cqYZ0CXmhOzzRHkfE:bufgfw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c43e7bf784ad992ef87114c92b87e14d6a87f4/pkg/clusterversion/cockroach_versions.go#L248)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Thanks for double checking this!

> The key point here is that the upgrade process runs all preconditions before executing any upgrade tasks. If no license is installed, the precondition fails, and no upgrade tasks are executed.

This was the main part I was missing. I forgot that the precondition checks worked in this way. I see the commit message already mentions that, but feel free to emphasize it even more if you think that would help.
</blockquote></details>

I updated the commit/PR message, which I think will help in understanding this.

**Comment by sergeyshaykhullin** [comment]
@spilchen Hello!

Sorry for this question, but I can't find any info which one version can be used with Core license and sales doesn't contact to me for a couple of days)

As I understood in this pr code changes and comments - latest version is 24.2 and 23.10 for now and this versions will under core license without any restrictions?

Or core will apply only for 22.1.9? And all versions from 23.1+ already deployed start throttling from 18th November?

Thank you!

**Comment by spilchen** [comment]
Existing Binaries (e.g. 23.1.26 which was released on 9/12) will be unchanged after Nov 18. The Core licensing (BSL) will continue to exist. After Nov 18, New Patch Releases (e.g. 23.1.30) will be released under the new Enterprise-only licensing scheme with the Core licensing removed.

**Comment by sergeyshaykhullin** [comment]
> Existing Binaries (e.g. 23.1.26 which was released on 9/12) will be unchanged after Nov 18. The Core licensing (BSL) will continue to exist. After Nov 18, New Patch Releases (e.g. 23.1.30) will be released under the new Enterprise-only licensing scheme with the Core licensing removed.

Thank you so much! This explanation is much clearer

**Pull request merged**
