### PR TITLE
sql: statically allocate common queryNotSupportedError instance

### PR DESCRIPTION
**Pull request by nvb**
We shouldn't be allocating error values on the common path of
`checkSupportForNode`, which is hit by all mutations and many
other plans.

Also fix ordering of cases in `checkSupportForNode` while here
to keep them alphabetized.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44409#-:-M0Q_fTh5KF9O7gen_Kk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by otan** [comment]
ah sorry, the license/cla didn't trigger on my build. try bors again.

**Pull request merged**
