### PR TITLE
sql: consider column direction in index when doing index selection

### LINKED ISSUE #3862: TestLogic -bigtest is broken because desc indexes are scanned in reverse order when they shouldn't
currently trying to understand the logic that computes this direction

### PR DESCRIPTION
**Pull request by andreimatei**
… so that we don't reverse an index unnecessarily

fixes #3862

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3866)

### CODE REVIEW

**Comment by andreimatei** [comment]
I don't understand the index selection code well enough yet to say if this is correct, but it seems to fix the LogicTest and doesn't break anything else, so we might as well have it in while I convince myself.

**Comment by andreimatei** [comment]
actually nvm, still a similar failure in the test

**Comment by petermattis** [comment]
I'm surprised this doesn't work. It looks correct, IMO. I think you need to create some simple test cases in `sql/testdata` that fail so we can debug what is going on.

**Comment by andreimatei** [comment]
I think the next problem is in the interaction between a `sortNode` and multiple index spans. Sorting is agnostic of the possible existence of multiple spans (and so it might say it's not needed, for example), and scanning the spans is agnostic of the ordering needed between them.

**Comment by petermattis** [comment]
Spans use to be generated in the same order has index traversal. Is that no longer true?

**Comment by andreimatei** [comment]
I think spans used to always  be generated "ascendingly", as a byproduct of the fact that we sort tuples. I've added an explicit sort step for the spans.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3866#-:-K868sqfYDY42-VsLu6l:1262938397)*

**Comment by petermattis** [comment]
LGTM, though it would be good to add a few simple test cases to `sql/testdata`.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 1070 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3866#-K86HVZ9tuGkjcEObmFy:-K86HVZ9tuGkjcEObmFz:1031458144) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f3040ba9f9cd1f3c513f73de8f20970d9861cb/sql/select.go#L1070)):*
Maybe a comment explaining why the sort is necessary. We can't over comment this code. A lot of it is subtle.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3866#-:-K86HOUrbqs7juhx-1pB:1514984096)*

**Comment by andreimatei** [comment]
what test would you add besides the ones I've put?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 1070 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3866#-K86HVZ9tuGkjcEObmFy:-K86MbEecTP1xJz6fwre:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f3040ba9f9cd1f3c513f73de8f20970d9861cb/sql/select.go#L1070)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3866#-:-K86Mc7l7iOi0_cDi3jl:-1763644824)*

**Comment by petermattis** [comment]
Oh, somehow I missed those tests. Reviewable error or human error? LGTM.

**Pull request merged**
