### PR TITLE
sql: allow UDFs with non-identical argument types of the same family

### LINKED ISSUE #94146: sql: allow multiple UDFs with in-exact type parameters of the same family
CRDB returns an error `function "xxx" already exists with same argument types` when trying to create two UDFs with parameters from the same type family. For example:

```sql
CREATE FUNCTION f(i INT2) RETURNS INT STRICT LANGUAGE SQL AS 'SELECT 2';
CREATE FUNCTION f(i INT4) RETURNS INT STRICT LANGUAGE SQL AS 'SELECT 4';
```

This is because `pkg/sql/create_function.go` uses the `TypeList.Match` function to find matching function overloads. `Match` checks for lists of equivalent types, but we need to check for lists of identical types.

Jira issue: CRDB-22708

### PR DESCRIPTION
**Pull request by il9ue**
This commit makes it possible to create multiple UDFs with arguments of
non-identical types of the same family.

Epic: None

Fixes #94146

Release note (bug fix): A bug has been fixed that caused errors when
creating multiple user-defined functions with the same name and
different argument types in the same type family. For example, it was
impossible to create both functions `f(i INT2)` and `f(INT4)`.

### CODE REVIEW

**Comment by il9ue** [comment]
Hi @mgartner I've prepared a new patchset (apply release note, leave a comment on param length condition)
I'd appreciate it if you give a quick review!

**Comment by il9ue** [comment]
@mgartner can you please leave a review or merge? thanks.

**Review by mgartner — COMMENTED** [review]
Sorry for the delay, I was out-of-office.

It's very close, just a few more comments. Alternatively, if you allow me to push changes to your branch then I can make the final adjustments and merge this. (I might not be able to push to your branch because it's your `master` branch).

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-:-NOAjFejDe73i088rcrK:b-9b5y5w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @il9ue)

___
*[`pkg/sql/sem/tree/type_check.go` line 3032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAu7n2AJUVrELY--Ax:-NOAu7n2AJUVrELY--Ay:bfsi9z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/sem/tree/type_check.go#L3032)):*
> ```Go
> 			// Since there are ambiguity errors when udf with the same family
> 			// parameter types, function signature has to be sorted out
> 			// to directly match specific udf function for execution, e2e tests added
> ```

No need to mention "e2e tests added" here.
___
*[`pkg/sql/sem/tree/type_check.go` line 3051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAu17n6FliHZCT_T91:-NOAu17n6FliHZCT_T92:b-lc5pir) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/sem/tree/type_check.go#L3051)):*
> ```Go
> 					udfExactDup = true
> 					break
> 				}
> ```

I don't think this is necessary - the tests pass without it. Can you remove it?
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 3066 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAtzXD6tAT2VJyJO1T:-NOAtzXD6tAT2VJyJO1U:b-9kp1hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/logictest/testdata/logic_test/udf#L3066)):*
> ```
> SELECT f_94146(1::INT2)
> ----
> 2
> ```

You need a new line at the end of the file.
___
*[`pkg/sql/sem/tree/function_definition_test.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAu4WY-QiSOubNNjIb:-NOAu4WZ6ECxBCh1Ag98:b-o5ww68) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/sem/tree/function_definition_test.go#L228)):*
> ```Go
> 		})
> 	}
> ```

nit: remove this blank line

**Review by il9ue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/sem/tree/type_check.go` line 3032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAu7n2AJUVrELY--Ax:-NOKPrqYDSmjbZUUZUFI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/sem/tree/type_check.go#L3032)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

No need to mention "e2e tests added" here.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/type_check.go` line 3051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAu17n6FliHZCT_T91:-NOKPKtqDevamwoUnrJr:bcgc1p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/sem/tree/type_check.go#L3051)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think this is necessary - the tests pass without it. Can you remove it?
</blockquote></details>

You mean 
				if len(srcParams.Types()) == 0 {
					udfExactDup = true
					break
				}

this block? 
Actually it fails in my local with "./dev test pkg/sql/sem/tree", if the above block isn't there.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 3066 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAtzXD6tAT2VJyJO1T:-NOKPnw3CnH2XrCjUjLM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/logictest/testdata/logic_test/udf#L3066)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You need a new line at the end of the file.
</blockquote></details>

Done.

**Review by il9ue — COMMENTED** [review]
Thanks for reply. I will try to apply your comments soon and push new one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-:-NOKPx7v92AzoxVY-Igi:b63o2zx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by il9ue** [comment]
@mgartner could you give a review? applied all comments except bypassing logic for `dev test pkg/sql/sem/tree`

**Review by mgartner — APPROVED** [review]
This looks great and should be good to merge. I've just made a few minor tweaks. I'll merge this once all the tests pass. Thanks again!

> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-:-NOPzm-IEq6iZ9bkAH6M:b-99j0bh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @il9ue)

___
*[`pkg/sql/sem/tree/type_check.go` line 3051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96481#-NOAu17n6FliHZCT_T91:-NOPzM8m8UPtVXNl73eZ:bc5hsnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dda09567250904301e3d08034020dce16b78fa2/pkg/sql/sem/tree/type_check.go#L3051)):*
<details><summary><i>Previously, il9ue (ilque) wrote…</i></summary><blockquote>

You mean 
				if len(srcParams.Types()) == 0 {
					udfExactDup = true
					break
				}

this block? 
Actually it fails in my local with "./dev test pkg/sql/sem/tree", if the above block isn't there.
</blockquote></details>

Looks like it was due to a bug in the logic below. I've fixed it and simplified things a bit.

**Comment by mgartner** [comment]
Thanks again @il9ue!

bors r+

**Pull request merged**
