### PR TITLE
opt: add support for OR in the constraint library

### LINKED ISSUE #38722: opt: Improve row count estimation for common OR clause pattern
Consider this query, which uses TPC-H schema:
```
EXPLAIN (opt,types) SELECT * FROM nation WHERE n_name = 'FRANCE' OR n_name = 'GERMANY';
```
The optimizer estimates 8.33 rows will be returned from this query. However, if the query is changed to this:
```
EXPLAIN (opt,types) SELECT * FROM nation WHERE n_name IN ('FRANCE', 'GERMANY');
```
The optimizer correctly estimates 2 rows.

We should add an optimization rule that normalizes OR conditions as an IN clause where possible, since our statistics estimation is able to do a better job of estimation with IN clauses.

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Fixes #38722.

This change adds support for OR in the constraints library
which imporves stats estimation for queries involving any
OR filters.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
Nice improvements on the stats quality!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-:-LkVLVB60QHhKmCN3-de:bwgq8mm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ridwanmsharif)

___
*[pkg/sql/opt/memo/constraint_builder.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkVKdem5J0qGdEUXkgK:-LkVKdem5J0qGdEUXkgL:bl5j917) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f2ff5433670356d6ce2b1469f60b14cb1be7857/pkg/sql/opt/memo/constraint_builder.go#L441)):*
> ```Go
> 		cl = cl.Union(cb.evalCtx, cr)
> 		tightl = tightl && tightr
> 		return cl, (tightl || cl == contradiction)
> ```

If `cl` is `contradiction`, then both the original `cl` and `cr` also had to be `contradiction`, right? Which would mean that both `tightl` and `tightr` are true.

But what's more, I'm not sure this logic is correct. Look at the comment above `Union`:
```
// Union creates a new set with constraints that allow any value that either of
// the input sets allowed. Compatible constraints (that share same column list)
// that exist in both sets are merged with one another. Note that the results
// may not be "tight", meaning that the new constraint set might allow
// additional combinations of values that neither of the input sets allowed. For
// example:
//   (x > 1 AND y > 10) OR (x < 5 AND y < 50)
// the union is unconstrained (and thus allows combinations like x,y = 10,0).
//
// Union returns the merged set.
```
Even if both constraint sets being unioned are tight, that doesn't mean that their union is tight. I think that means that we always have to just report this as "not tight".

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39057)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkVuao11UgMINFd6aJa:-LkVuao11UgMINFd6aJb:b-hx7epn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ccac99bdf0550ebadabe457d8766a31942f0a9/pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join#L247)):*
> ```
> https://cockroachdb.github.io/distsqlplan/decode.html#eJzslEFr2zAUx-_7FOL1koKCLClOV0FBgzHoGMnIetty0KxH6i2VjCTDRsl3H46XxgmJ67FLDz3az3__pR8_3iM4b3FmHjCC-gocKAigkMOSQhV8gTH60IzaD2_tL1AZhdJVdWpeLykUPiCoR0hlWiMouDPf17hAYzGwDChYTKZcb39fhfLBhN-6MgFdasq-VMZFRRjnY8YFu2B5zjjLBTHOEkF8uscQgcKHcp0wKDIaaU6-1VkmixvCpVLqdnb39pLMF50R3hB-_TR6N3tPuinBd6PLNteJyacZLDcUfJ3294zJrBAU39DhLD760v1FIU-jWAXjbHFfrm3D_ZP3P-uK_PClI94pohtG8xkZjUZa7i_Hjy4nTyDZMZHnmcjzTLo5eb5O7uuag9ZJES2pnlCdUz2l-opqcZakOEtyD7B2PlgMaA_oLTcnWM_82FdsevTh6Wp5UM2HC80HC92Recy4ZBdbpXmr9As2-hkYHaMnr0b3Gi2GayUGa3U9ZiLbqTXNXrBIz1y_I1L-KtLg1XiC5AJj5V3EQZsva1Yn2hW2ezb6OhT4OfhiW9M-zre57QuLMbVT3j7cunbUHLAb5r1hcRDmx2HRG77qb5a94Ul_ePI_x857w9P-5uk_NS83b_4EAAD__9H90mw=
> 
> # TODO(ridwanmsharif) Confirm that this is better than before.
> ```

@justinj do the changes in this file make sense?
___
*[pkg/sql/opt/memo/constraint_builder.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkVKdem5J0qGdEUXkgK:-LkVuS6Q8AmVno-y5mhZ:bkm764f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f2ff5433670356d6ce2b1469f60b14cb1be7857/pkg/sql/opt/memo/constraint_builder.go#L441)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

If `cl` is `contradiction`, then both the original `cl` and `cr` also had to be `contradiction`, right? Which would mean that both `tightl` and `tightr` are true.

But what's more, I'm not sure this logic is correct. Look at the comment above `Union`:
```
// Union creates a new set with constraints that allow any value that either of
// the input sets allowed. Compatible constraints (that share same column list)
// that exist in both sets are merged with one another. Note that the results
// may not be "tight", meaning that the new constraint set might allow
// additional combinations of values that neither of the input sets allowed. For
// example:
//   (x > 1 AND y > 10) OR (x < 5 AND y < 50)
// the union is unconstrained (and thus allows combinations like x,y = 10,0).
//
// Union returns the merged set.
```
Even if both constraint sets being unioned are tight, that doesn't mean that their union is tight. I think that means that we always have to just report this as "not tight".
</blockquote></details>

You're right, the union here doesn't guarantee that it it tight. Done.

**Review by justinj — COMMENTED** [review]
:lgtm: but cc @rytaft for a look at the stats

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-:-LkVyumWEki0vQ7Uvl0P:b-xd1r1e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @ridwanmsharif)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkVuao11UgMINFd6aJa:-LkVw3sE6SrKDemP2U_s:b-82w8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ccac99bdf0550ebadabe457d8766a31942f0a9/pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join#L247)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

@justinj do the changes in this file make sense?
</blockquote></details>

Like we discussed in person, the interleaved joins are probably better, but we don't have information about interleaves in the optimizer today, so it's not surprising to me that changing stats would cause us to stop using them when they were good.

Either way, remove the opt,verbose test below, since this file is for distsql tests.
___
*[pkg/sql/opt/memo/testdata/stats/select, line 1480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkVwweG2DtAUh8a4y_c:-LkVwweG2DtAUh8a4y_d:b-m0iey9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ccac99bdf0550ebadabe457d8766a31942f0a9/pkg/sql/opt/memo/testdata/stats/select#L1480)):*
> ```
> 
> opt
> SELECT * FROM nation WHERE (n_name = 'FRANCE' AND neighbour = 'GERMANY') OR (n_name = 'GERMANY' AND neighbour = 'FRANCE')
> ```

Hm, interesting that these two create different constraints. It seems like we'd want to force them into one form or another, but I'm not sure. Seems odd that these two have different stats.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39057)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @ridwanmsharif)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join, line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkVuao11UgMINFd6aJa:-LkW_eyK81Jr6J7galUR:bageh8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ccac99bdf0550ebadabe457d8766a31942f0a9/pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join#L247)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Like we discussed in person, the interleaved joins are probably better, but we don't have information about interleaves in the optimizer today, so it's not surprising to me that changing stats would cause us to stop using them when they were good.

Either way, remove the opt,verbose test below, since this file is for distsql tests.
</blockquote></details>

The point of these tests (and the corresponding tests in sql/logictest) is to test the interleaved joins that distsql can plan. We need to find a way to cajole these cases into not using a lookup join. I would try increasing the constants in the condition, or injecting stats (with a lot of rows but few distinct values on pid1)

**Review by rytaft — APPROVED** [review]
:lgtm:

Awesome improvement on the stats quality! Can you try running the queries with the new and old plans to see the performance difference (and add that info to the commit message)?

> Reviewed 4 of 16 files at r1, 13 of 13 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-:-LkZO8dQ6reIeNbemskS:b-r2dplf)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @ridwanmsharif)

___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 2350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkZQsXL95Z2bW3wsaEI:-LkZQsXL95Z2bW3wsaEJ:b-ynupyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/892d067d3973eacf903fe8b00f1026ec77844445/pkg/sql/opt/norm/testdata/rules/decorrelate#L2350)):*
> ```
>  │    │    ├── ordering: +7
>  │    │    └── left-join (hash)
>  │    │         ├── columns: k:1(int!null) i:2(int) y:7(int)
> ```

Looks like we're missing an opportunity to update the logical props -- this should be `y:7(int!null)`. You don't need to do that in this PR, but maybe open an issue?
___
*[pkg/sql/opt/norm/testdata/rules/select, line 564 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkZJakBCFTuALEbc6lp:-LkZJakBCFTuALEbc6lq:b-zb8bhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ccac99bdf0550ebadabe457d8766a31942f0a9/pkg/sql/opt/norm/testdata/rules/select#L564)):*
> ```
>  │    └── filters (true)
>  └── filters
>       └── (i < y) OR (y IS NULL) [type=bool, outer=(2,7), constraints=(/7: [/NULL - ])]
> ```

Would be better to leave this as unconstrained since this constraint is equivalent to unconstrained

**Review by ridwanmsharif — COMMENTED** [review]
There are some interesting results when looking at the change in plan in the tpch Q7.

Here are some results that I found after running the query on a 1 node local cluster:
With the change:
```3.862354s, 3.76474s, 3.862704s, 4.116051s, 3.771424s, 3.917422s```

Without the Or change:
```6.6733s, 6.916926s, 6.734223s, 7.028038s, 6.598402s, 6.668144s```


That looks good. However, it is not all good news. Here are some results for 
when I ran with a 3 node cluster:
With the Or change:
```8.277532s, 9.245219s, 8.310798s, 8.310798s```

Without the Or change:
```5.353379s, 4.92064s, 4.977948s, 5.050735s```

It seems that with more nodes the plan picked is much worse than before.
This is probably because the new plan has more lookup joins and looking up
from other nodes may be expensive. Maybe we at some point should consider
adding cluster information to the cost model? 
@rytaft suggested offline that we could make lookup joins less desirable for now.

cc @rytaft, @justinj

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-:-LlDW_yCBx_YcRkIRD9C:brfpk0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/select, line 1480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkVwweG2DtAUh8a4y_c:-LlCdJpoBM-ItSa5nZMS:bg2mv9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ccac99bdf0550ebadabe457d8766a31942f0a9/pkg/sql/opt/memo/testdata/stats/select#L1480)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Hm, interesting that these two create different constraints. It seems like we'd want to force them into one form or another, but I'm not sure. Seems odd that these two have different stats.
</blockquote></details>

Maybe yeah, this looks like of how constraints generated are different for `AND` and `IN`. Leaving it out of this PR.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 2350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkZQsXL95Z2bW3wsaEI:-LlCdZVE5AfFB-jmELTn:bnkpf1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/892d067d3973eacf903fe8b00f1026ec77844445/pkg/sql/opt/norm/testdata/rules/decorrelate#L2350)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Looks like we're missing an opportunity to update the logical props -- this should be `y:7(int!null)`. You don't need to do that in this PR, but maybe open an issue?
</blockquote></details>

I'll create an issue for it. Good catch!
___
*[pkg/sql/opt/norm/testdata/rules/select, line 564 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39057#-LkZJakBCFTuALEbc6lp:-LlCeGwI19MNiwBDbIYb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ccac99bdf0550ebadabe457d8766a31942f0a9/pkg/sql/opt/norm/testdata/rules/select#L564)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Would be better to leave this as unconstrained since this constraint is equivalent to unconstrained
</blockquote></details>

Done.

**Pull request merged**
