### PR TITLE
sql: nuke the old index constraints code

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: nuke the old index constraints code

Removing the old index constraints code; fixing up the spans and exact
prefix tests to use the new code. Some of the testcases were trimmed
down (the index constraints code has its own tests).

I was hoping to remove `opt_decompose.go` as part of this but
`SimplifyExpr` is also used by the partitioning code.

Release note: None

#### sql: clean up the "experimental" from index constraints code

The new index constraint code is no longer experimental.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
:fire: :baby: :fire:

:lgtm_strong: 

---

Reviewed 10 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22453#-:-L4i40AJBqR_T8mpB0x3:b-3z277)*

**Comment by petermattis** [comment]
:lgtm: so much deletion!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22453#-:-L4i4olvpxFsbkCb-UQd:b-4ypf9n)*

**Comment by knz** [comment]
> so much deletion!

wow, amaze
🐶

**Review by jordanlewis — APPROVED** [review]
LGTM!

image

**Pull request merged**
