### PR TITLE
sql: implement custom session options

### LINKED ISSUE #70033: sql: support customized session options
Needed for https://github.com/cockroachdb/cockroach/issues/69010.

Postgres allows arbitrary session parameters to be set for a session, as long as they have a two-part name (i.e. contain a period). Tools can use this to store and retrieve arbitrary local session state.

We should ensure the arbitrary state has memory accounting.

```sql
> SELECT set_config('mytool.state', 'some val', false);
 set_config
------------
 some val
(1 row)

> SELECT current_setting('mytool.state');
 current_setting
-----------------
 some val
(1 row)
```

PG docs: https://www.postgresql.org/docs/current/runtime-config-custom.html

<details><summary>Prototype:</summary>
<p>

```go
diff --git a/pkg/sql/exec_util.go b/pkg/sql/exec_util.go
index 42dded41fb..de40f98631 100644
--- a/pkg/sql/exec_util.go
+++ b/pkg/sql/exec_util.go
@@ -2788,6 +2788,13 @@ func (m *sessionDataMutator) SetLocation(loc *time.Location) {
 	m.bufferParamStatusUpdate("TimeZone", sessionDataTimeZoneFormat(loc))
 }
 
+func (m *sessionDataMutator) SetCustomOption(name, val string) {
+	if m.data.CustomOptions == nil {
+		m.data.CustomOptions = make(map[string]string)
+	}
+	m.data.CustomOptions[name] = val
+}
+
 func (m *sessionDataMutator) SetReadOnly(val bool) {
 	// The read-only state is special; it's set as a session variable (SET
 	// transaction_read_only=<>), but it represents per-txn state, not
diff --git a/pkg/sql/sessiondata/session_data.go b/pkg/sql/sessiondata/session_data.go
index a86e467b5f..67964914af 100644
--- a/pkg/sql/sessiondata/session_data.go
+++ b/pkg/sql/sessiondata/session_data.go
@@ -48,6 +48,9 @@ type SessionData struct {
 	// SequenceState gives access to the SQL sequences that have been
 	// manipulated by the session.
 	SequenceState *SequenceState
+	CustomOptions map[string]string
 }
 
 // Clone returns a clone of SessionData.
diff --git a/pkg/sql/vars.go b/pkg/sql/vars.go
index 16de1f2361..b38b0863d0 100644
--- a/pkg/sql/vars.go
+++ b/pkg/sql/vars.go
@@ -1956,6 +1956,14 @@ func (p *planner) GetSessionVar(
 	_ context.Context, varName string, missingOk bool,
 ) (bool, string, error) {
 	name := strings.ToLower(varName)
+	if isCustomOption(name) {
+		v, ok := p.SessionData().CustomOptions[name]
+		if !ok && !missingOk {
+			return false, "", pgerror.Newf(pgcode.UndefinedObject,
+				"unrecognized configuration parameter %q", name)
+		}
+		return true, v, nil
+	}
 	ok, v, err := getSessionVar(name, missingOk)
 	if err != nil || !ok {
 		return ok, "", err
@@ -1966,6 +1974,18 @@ func (p *planner) GetSessionVar(
 // SetSessionVar implements the EvalSessionAccessor interface.
 func (p *planner) SetSessionVar(ctx context.Context, varName, newVal string, isLocal bool) error {
 	name := strings.ToLower(varName)
+	if isCustomOption(name) {
+		// Ignore isLocal.
+		_ = isLocal
+		return p.applyOnSessionDataMutators(
+			ctx,
+			isLocal,
+			func(m sessionDataMutator) error {
+				m.SetCustomOption(name, newVal)
+				return nil
+			},
+		)
+	}
 	_, v, err := getSessionVar(name, false /* missingOk */)
 	if err != nil {
 		return err
@@ -1995,3 +2015,7 @@ func (p *planner) SetSessionVar(ctx context.Context, varName, newVal string, isL
 		},
 	)
 }
+
+func isCustomOption(varName string) bool {
+	return strings.Contains(varName, ".")
+}

```

</p>
</details>

Epic CRDB-10300

### PR DESCRIPTION
**Pull request by otan**
Resolves #70033

See individual commit for details. I've left out memory accounting for now.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71915)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/show_var.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-YBcQ22cCBlNHunDZ:-Mn-YBcR21p1Qnu7JqgA:bxqmusd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/show_var.go#L21)):*
> ```Go
> 
> // showVarNode represents a SHOW <var> statement.
> // This is reached is <var> contains a period.
> ```

nit: "if"
___
*[pkg/sql/vars.go, line 1985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-WIWo0DTYobCCxvlM:-Mn-WIWo0DTYobCCxvlN:b-qjr776) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/vars.go#L1985)):*
> ```Go
> 	if !ok {
> 		if strings.Contains(name, ".") {
> 			return true, sessionVar{
> ```

separate from the memory accounting point: do we need to be worried about where the reference to this `sessionVar` struct might end up getting used?
___
*[pkg/sql/vars.go, line 1990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-V_M679kJ533jtVSb:-Mn-V_M679kJ533jtVSc:b-m4clih) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/vars.go#L1990)):*
> ```Go
> 				},
> 				Set: func(ctx context.Context, m sessionDataMutator, val string) error {
> 					// TODO(#sql-experience): do some memory accounting.
> ```

heh i realize now that we also don't have memory accounting for the session data stack. would you mind filing a backlog issue that is about adding memory accounting both here and for the stack?
___
*[pkg/sql/delegate/show_var.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-Wjf69QU0rVOTbnpe:-Mn-Wjf69QU0rVOTbnpf:b-qg4ky1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/delegate/show_var.go#L37)):*
> ```Go
> 	}
> 
> 	if name == "all" {
> ```

we should add a test that `SHOW ALL` does _not_ shows the custom vars (seems like that's what PG does)

and i assume also not in pg_settings.
___
*[pkg/sql/delegate/show_var.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-Yju3-VmDwIdQvzfV:-Mn-Yju3-VmDwIdQvzfW:b-stk3ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/delegate/show_var.go#L44)):*
> ```Go
> 
> 	if _, ok := ValidVars[name]; !ok {
> 		// Allow for custom options.
> ```

nit: comment could mention that this goes to the planNode impl
___
*[pkg/sql/logictest/testdata/logic_test/set, line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-UYOWEgE3CdHr_Zy3:-Mn-UYOWEgE3CdHr_Zy4:b-3rb0g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/logictest/testdata/logic_test/set#L558)):*
> ```
> 
> statement ok
> SET custom_option.set_SQL = 'abc';
> ```

can you also test custom options with `ALTER ROLE SET`? there's a separate logic test for that at pkg/sql/logictest/testdata/logic_test/alter_role_set

similarly, can you also make sure this works with serialize_session and deserialize_session?

finally, can you add a test in `TestSetSessionArguments` in conn_test.go
___
*[pkg/sql/logictest/testdata/logic_test/set, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-Z5KrARbfwTNoddv_:-Mn-Z5KrARbfwTNoddva:b-hazusu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/logictest/testdata/logic_test/set#L564)):*
> ```
> 
> query T colnames
> SHOW Custom_option.set_sql
> ```

nit: i think we do want a test to make sure that they are case-insensitive, but add a comment to mention that we test case insensitivity
___
*[pkg/sql/logictest/testdata/logic_test/set, line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-YZFtDVhyTMQCT6JO:-Mn-YZFtDVhyTMQCT6JP:b653zka) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/logictest/testdata/logic_test/set#L583)):*
> ```
> 
> query T
> SHOW custom_option.set_config
> ```

nit: add one more test for SHOW on a custom var name that has never been used before

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71915)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/vars.go, line 1985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-WIWo0DTYobCCxvlM:-Mn-tl7n6v9CT8eqrB_2:bujmudg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/vars.go#L1985)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

separate from the memory accounting point: do we need to be worried about where the reference to this `sessionVar` struct might end up getting used?
</blockquote></details>

don't think it matters; it can be GC'd safely
___
*[pkg/sql/vars.go, line 1990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-V_M679kJ533jtVSb:-Mn-w9iyCpiLUM0PYKqm:b-95wkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/vars.go#L1990)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

heh i realize now that we also don't have memory accounting for the session data stack. would you mind filing a backlog issue that is about adding memory accounting both here and for the stack?
</blockquote></details>

Done. #72026
___
*[pkg/sql/delegate/show_var.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-Wjf69QU0rVOTbnpe:-Mn-ubUs7qjtKb5gN3rc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/delegate/show_var.go#L37)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should add a test that `SHOW ALL` does _not_ shows the custom vars (seems like that's what PG does)

and i assume also not in pg_settings.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/set, line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-UYOWEgE3CdHr_Zy3:-Mn-wtLMArkbn-j26v5a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/logictest/testdata/logic_test/set#L558)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you also test custom options with `ALTER ROLE SET`? there's a separate logic test for that at pkg/sql/logictest/testdata/logic_test/alter_role_set

similarly, can you also make sure this works with serialize_session and deserialize_session?

finally, can you add a test in `TestSetSessionArguments` in conn_test.go
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/set, line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-Mn-YZFtDVhyTMQCT6JO:-Mn-uALiBYWaCbQ0Ttus:b-krych5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d960e841ccd84e2c520e97b0a839dd83c536125/pkg/sql/logictest/testdata/logic_test/set#L583)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: add one more test for SHOW on a custom var name that has never been used before
</blockquote></details>

This is done on the second commit. Required more infrastructure.

**Review by rafiss — APPROVED** [review]
looks great!

> Reviewed 10 of 17 files at r1, 10 of 17 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71915#-:-MnROZ7u8-4tVP8M6Tn9:b6lqmcl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
