### PR TITLE
add value encoding support to EncDatum

### PR DESCRIPTION
**Pull request by danhhz**
I'm still a little concerned about the benchmark diffs in the first commit. Thoughts?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6932)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This looks fantastic! :lgtm_strong: 

Did you run into any `TestEncDatumFromBuffer` failures while you were working on this? It should be testing encoding and decoding for the new stuff automatically.

As for the benchmarks, the differences in absolute terms are very small - in the realm of a couple nanoseconds. I wouldn't worry about it.

@nvanbenschoten might want to take a look too

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> #### add value encoding support to EncDatum
> 
> I'm still a little concerned about the benchmark diffs in the first commit. Thoughts?
> 
> 
> 
</details>


---

Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[roachpb/data.go, line 451 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIictXdzK8YAO9lpUaF:-KIictXdzK8YAO9lpUaG:1075268361) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L451)):*
> ```Go
> 		// varint.
> 		i := len(appendTo)
> 		appendTo = appendZeros(appendTo, binary.MaxVarintLen64)
> ```

Introducing appendZeros  is a bit overkill.. we could have just done `appendTo = append(appendTo, 0, 0, 0, .. <10 times>)`. Or could have used an array of MaxVarintLen64 size like above. We could even declare a global array of size MaxVarintLen64 and append that.

---

*[roachpb/data.go, line 519 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIidOVj8y4h7MQ1fpNQ:-KIidOVj8y4h7MQ1fpNR:-807516237) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L519)):*
> ```Go
> 		return b[n+int(i):], b[n : n+int(i)], nil
> 	}
> 	return nil, nil, fmt.Errorf("value type is not %s or %s: %s", ValueType_BYTES, ValueType_DELIMITED_BYTES, tag)
> ```

long line

---

*[roachpb/data.go, line 473 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIiiJzDMAFVWE5B2a39:-KIiiJzDMAFVWE5B2a3A:-875519666) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/roachpb/data.go#L473)):*
> ```Go
> func DecodeIntValue(b []byte) ([]byte, int64, error) {
> 	if len(b) == 0 {
> 		return nil, 0, fmt.Errorf("array is empty")
> ```

It's possible functions like this aren't getting inlined because of the error cases - the `Errorf` calls with arguments come with a lot of surrounding instructions (each argument has to be allocated, copied, and put in an `interface{}`). 

That could be fixed by returning simpler errors:

```
var emptyArrErr error = fmt.Errorf("array is empty")

type invalidTagErr struct {
   expected, actual ValueType
}
func (e invalidTagErr) Error() string {
   return fmt.Sprintf("value type is not %s: %s", e.expected, e.actual)
}

etc
```

I doubt this is worth the effort but figured I should mention it in case you are curious to try.

---

*[roachpb/data.go, line 736 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIiddlXw1aAMUwcBLyf:-KIiddlXw1aAMUwcBLyg:1023677154) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/roachpb/data.go#L736)):*
> ```Go
> 		return 1 + n, err
> 	}
> 	return 0, util.Errorf("unknown tag %q", tag)
> ```

I would add a special error for the non-delimited stuff (`unkown tag` might not be that helpful)

---

*[roachpb/data.go, line 739 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIidvjCs4rEvxkllcAr:-KIidvjCs4rEvxkllcAs:489603588) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/roachpb/data.go#L739)):*
> ```Go
> }
> 
> func getVarintLen(b []byte) (int, int, error) {
> ```

should be `getGoVarintLen` like the corresponding encoding function, especially since we are using it "close" to where we use the similar sounding GetMultiVarintLen which itself uses a different function called `getVarintLen`

---

*[roachpb/data.proto, line 66 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIicJDyOcQ5v3q4MAeT:-KIicJDyOcQ5v3q4MAeU:1745725842) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.proto#L66)):*
> ```protobuf
>   FLOAT = 2;
>   BYTES = 3;
>   DELIMITED_BYTES = 8;
> ```

Maybe add some comments here about what DELIMITED means

---

*[sql/sqlbase/table.go, line 426 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIieU_rp85dzz96I6xE:-KIieU_rp85dzz96I6xF:-1698646650) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/sql/sqlbase/table.go#L426)):*
> ```Go
> 		if *t {
> 			x = 1
> 		} else {
> ```

don't really need this else branch (it's 0 anyway)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-:-KIienrZopM7HO0omRrw:1749184942)*

**Comment by RaduBerinde** [comment]
By the way, if this encoding is significantly faster, we could also use it for encoding values for `STORING` columns into index keys.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This looks fantastic! :lgtm_strong: 
> 
> Did you run into any `TestEncDatumFromBuffer` failures while you were working on this? It should be testing encoding and decoding for the new stuff automatically.
> 
> As for the benchmarks, the differences in absolute terms are very small - in the realm of a couple nanoseconds. I wouldn't worry about it.
> 
> @nvanbenschoten might want to take a look too
</details>


---

Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-:-KIikLEZ4I3XeiA1HCq1:925372939)*

**Comment by nvanbenschoten** [comment]
:lgtm:

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> By the way, if this encoding is significantly faster, we could also use it for encoding values for `STORING` columns into index keys.
</details>


---

Reviewed 6 of 6 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[roachpb/data.go, line 411 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIind4YFEGls2Qxm6fT:-KIind4YFEGls2Qxm6fU:2136929776) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L411)):*
> ```Go
> // buffer, and returns the final buffer.
> func EncodeBytesValue(appendTo []byte, data []byte, delimited bool) []byte {
> 	if delimited {
> ```

nit: it might make the effect of `delimited` a little more clear if the structure of this function was something like:

```
if delimited {
    appendTo = append(appendTo, byte(ValueType_DELIMITED_BYTES))
    appendTo = encodeGoVarint(appendTo, int64(len(data)))
} else {
    appendTo = append(appendTo, byte(ValueType_BYTES))
}
return append(appendTo, data...)
```

---

*[roachpb/data.go, line 428 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIio81YtPAgBCRRcJ0-:-KIio81YtPAgBCRRcJ00:-905774479) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L428)):*
> ```Go
> 
> // appendZeros is equivalent to append(appendTo, make([]byte, n)), but without
> // the extra allocation.
> ```

`s/the extra/the guaranteed extra/`

---

*[roachpb/data.go, line 434 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIioI9YjweRpA0k_4j_:-KIioI9YjweRpA0k_4ja:875662177) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L434)):*
> ```Go
> 	}
> 	newSize := len(appendTo) * 2
> 	if len(appendTo)+n > newSize {
> ```

Consider

```
if someVar := ...; someVar > newSize {
    newSize = someVar
}
```

or even better, pull that `len(appendTo)+n` into a variable and use it below as well.

---

*[roachpb/data.go, line 451 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIictXdzK8YAO9lpUaF:-KIip6Fx0w85bmmKQKQw:-1620888209) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L451)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Introducing appendZeros  is a bit overkill.. we could have just done `appendTo = append(appendTo, 0, 0, 0, .. <10 times>)`. Or could have used an array of MaxVarintLen64 size like above. We could even declare a global array of size MaxVarintLen64 and append that.
</details>
There's a chance `append(appendTo, 0, 0, 0, .. <10 times>)` will allocate as well because it's using a vararg, although hopefully it does so statically.

---

*[roachpb/data.go, line 568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIinCzA8ofRJiZtYZxH:-KIinCzA8ofRJiZtYZxI:1459330751) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L568)):*
> ```Go
> }
> 
> // SetBytes sets the bytes and tag field of the receiver and clears the checksum.
> ```

nit: It's a little strange that these are in a different order than above.

---

*[roachpb/data_test.go, line 872 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIilnx_raMJOm94JAJY:-KIilnx_raMJOm94JAJZ:-1566611873) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data_test.go#L872)):*
> ```Go
> 
> func BenchmarkEncodeGoVarint(b *testing.B) {
> 	bytes := make([]byte, b.N*binary.MaxVarintLen64)
> ```

I believe `b.N` is actually dynamic based on the duration of a single loop, so I'm surprised this is working. Maybe I just don't understand how Go benchmarks work well enough though. Still, mind double checking this is doing what you're expecting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-:-KIiqH41Rg0Qsa9dj51l:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[roachpb/data_test.go, line 872 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIilnx_raMJOm94JAJY:-KIisBKl1dENoa7kSYFF:-1344715290) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data_test.go#L872)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I believe `b.N` is actually dynamic based on the duration of a single loop, so I'm surprised this is working. Maybe I just don't understand how Go benchmarks work well enough though. Still, mind double checking this is doing what you're expecting.
</details>
It's just a member of a struct, it can't change once the function is called.

It's "dynamic" in that go calls the function multiple times, ramping up the value of `N`. See https://golang.org/src/testing/benchmark.go?s=1642:2246#L195 for the nitty gritty

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932)*

**Comment by RaduBerinde** [comment]
*[roachpb/data_test.go, line 872 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIilnx_raMJOm94JAJY:-KIiu36SpuSN8bOPSLjX:1074961659) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data_test.go#L872)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It's just a member of a struct, it can't change once the function is called.
> 
> It's "dynamic" in that go calls the function multiple times, ramping up the value of `N`. See https://golang.org/src/testing/benchmark.go?s=1642:2246#L195 for the nitty gritty
</details>
Sorry correct link is https://golang.org/src/testing/benchmark.go#L195

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932)*

**Comment by paperstreet** [comment]
Review status: 3 of 11 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[roachpb/data.go, line 411 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIind4YFEGls2Qxm6fT:-KIivwkHyqupVycy9vgf:925052031) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L411)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> nit: it might make the effect of `delimited` a little more clear if the structure of this function was something like:
> 
> ```
> if delimited {
>     appendTo = append(appendTo, byte(ValueType_DELIMITED_BYTES))
>     appendTo = encodeGoVarint(appendTo, int64(len(data)))
> } else {
>     appendTo = append(appendTo, byte(ValueType_BYTES))
> }
> return append(appendTo, data...)
> ```
</details>
I was 50/50 on this. Done.

---

*[roachpb/data.go, line 428 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIio81YtPAgBCRRcJ0-:-KIj2MS3OOjupco-Uqgj:-111438181) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L428)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/the extra/the guaranteed extra/`
</details>
Deleted the function.

---

*[roachpb/data.go, line 434 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIioI9YjweRpA0k_4j_:-KIj2OLKCHwiKOFYJrxa:-111438181) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L434)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Consider
> 
> ```
> if someVar := ...; someVar > newSize {
>     newSize = someVar
> }
> ```
> 
> or even better, pull that `len(appendTo)+n` into a variable and use it below as well.
</details>
Deleted the function.

---

*[roachpb/data.go, line 451 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIictXdzK8YAO9lpUaF:-KIixnCJB0207Gs4AQou:-1851414859) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L451)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> There's a chance `append(appendTo, 0, 0, 0, .. <10 times>)` will allocate as well because it's using a vararg, although hopefully it does so statically.
</details>
Looks like no allocation. Much better, thanks Radu.

---

*[roachpb/data.go, line 519 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIidOVj8y4h7MQ1fpNQ:-KIiyKcehJj22P43pFel:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L519)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> long line
</details>
Done.

---

*[roachpb/data.go, line 568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIinCzA8ofRJiZtYZxH:-KIiyMTLS8rret9G8uis:-1705974224) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.go#L568)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> nit: It's a little strange that these are in a different order than above.
</details>
Agreed. I didn't want the extraneous diff of shuffling them around here and the above is in the same order as the entries in ValueType

---

*[roachpb/data.go, line 473 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIiiJzDMAFVWE5B2a39:-KIiy7XCFUyhDhQsXPH6:2146645873) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/roachpb/data.go#L473)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It's possible functions like this aren't getting inlined because of the error cases - the `Errorf` calls with arguments come with a lot of surrounding instructions (each argument has to be allocated, copied, and put in an `interface{}`). 
> 
> That could be fixed by returning simpler errors:
> 
> ```
> var emptyArrErr error = fmt.Errorf("array is empty")
> 
> type invalidTagErr struct {
>    expected, actual ValueType
> }
> func (e invalidTagErr) Error() string {
>    return fmt.Sprintf("value type is not %s: %s", e.expected, e.actual)
> }
> 
> etc
> ```
> 
> I doubt this is worth the effort but figured I should mention it in case you are curious to try.
</details>
Interesting idea. There's enough different error cases here (two tags in expected vs 1, etc) that I'd rather wait for a followup if this proves to be an issue

---

*[roachpb/data.go, line 736 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIiddlXw1aAMUwcBLyf:-KIj2AwKyWAaQeW5D_-s:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/roachpb/data.go#L736)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I would add a special error for the non-delimited stuff (`unkown tag` might not be that helpful)
</details>
Done.

---

*[roachpb/data.go, line 739 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIidvjCs4rEvxkllcAr:-KIj1nEdTw9xZ0MO4pzw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/roachpb/data.go#L739)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> should be `getGoVarintLen` like the corresponding encoding function, especially since we are using it "close" to where we use the similar sounding GetMultiVarintLen which itself uses a different function called `getVarintLen`
</details>
Done.

---

*[roachpb/data.proto, line 66 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIicJDyOcQ5v3q4MAeT:-KIiyyulxzQPMJGIwlWo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data.proto#L66)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Maybe add some comments here about what DELIMITED means
</details>
Done.

---

*[roachpb/data_test.go, line 872 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIilnx_raMJOm94JAJY:-KIj2Pfv4TmdJOtk5pB3:629634530) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data_test.go#L872)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Sorry correct link is https://golang.org/src/testing/benchmark.go#L195
</details>
 =radu

---

*[sql/sqlbase/table.go, line 426 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIieU_rp85dzz96I6xE:-KIj2FhR0tJ_RtGmTBTj:-2078170409) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd66ac31e49bb5871bb701baf1b4b8b4988c848/sql/sqlbase/table.go#L426)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> don't really need this else branch (it's 0 anyway)
</details>
I was copying EncodeTableKey and noticed this as well. You've convinced me to fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[roachpb/data.go, line 435 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIj8yJ3xzsjJ3ehq7hW:-KIj8yJ3xzsjJ3ehq7hX:249857797) ([raw file](https://github.com/cockroachdb/cockroach/blob/3916577f3341f747b0919b9e59640f8d853c5b04/roachpb/data.go#L435)):*
> ```Go
> 		// encode the varint, and shift the encoded decimal to the end of the
> 		// varint.
> 		i := len(appendTo)
> ```

intPos or varintPos

---

*[roachpb/data.go, line 440 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIj8L6ZeeCVXg7lGMRj:-KIj8L6ZeeCVXg7lGMRk:-1702901997) ([raw file](https://github.com/cockroachdb/cockroach/blob/3916577f3341f747b0919b9e59640f8d853c5b04/roachpb/data.go#L440)):*
> ```Go
> 		appendTo = encoding.EncodeNonsortingDecimal(appendTo, d)
> 		decLen := len(appendTo) - i - binary.MaxVarintLen64
> 		decOffset := i + binary.MaxVarintLen64
> ```

I would do `decOffset := len(appendTo)` after appending 0s, and `decLen := len(appendTo) - decOffset`. That way it doesn't actually matter that the number of 0s matches `MaxVarintLen64`, as long as there's enough of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932)*

**Comment by paperstreet** [comment]
Btw, I did use TestEncDatumFromBuffer the entire time I was working on this and it was great! I modified it to only use the value encoding and one datum type, implemented them one by one, then undid my test changes and everything worked.

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 3 of 14 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[roachpb/data.go, line 435 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIj8yJ3xzsjJ3ehq7hW:-KIjCjnpi4wnDdxOtJ9M:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3916577f3341f747b0919b9e59640f8d853c5b04/roachpb/data.go#L435)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> intPos or varintPos
</details>
Done.

---

*[roachpb/data.go, line 440 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIj8L6ZeeCVXg7lGMRj:-KIjCoJNDhssU5ztWD65:-1788007727) ([raw file](https://github.com/cockroachdb/cockroach/blob/3916577f3341f747b0919b9e59640f8d853c5b04/roachpb/data.go#L440)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I would do `decOffset := len(appendTo)` after appending 0s, and `decLen := len(appendTo) - decOffset`. That way it doesn't actually matter that the number of 0s matches `MaxVarintLen64`, as long as there's enough of them.
</details>
Yeah, that's better

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-:-KIjD2GmRQ4ZyAT8RCIu:-1586834835)*

**Comment by RaduBerinde** [comment]
Cool! :lgtm: 

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Btw, I did use TestEncDatumFromBuffer the entire time I was working on this and it was great! I modified it to only use the value encoding and one datum type, implemented them one by one, then undid my test changes and everything worked.
</details>


---

Review status: 3 of 14 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-:-KIjI-_l3_yWDu0HQ_lu:-828102425)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 14 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/data_test.go, line 872 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932#-KIilnx_raMJOm94JAJY:-KIjUblSS3ZI8M2-DenQ:-773621910) ([raw file](https://github.com/cockroachdb/cockroach/blob/007947f14084b48a4bde3cc94adc20eef0612743/roachpb/data_test.go#L872)):*
<details><summary><i>Previously, paperstreet (Dan Harrison) wrote…</i></summary>
>  =radu
</details>
Ah cool, I didn't realize the benchmark function itself was called multiple times with different `*testing.B` structs. TIL!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6932)*

**Pull request merged**
