### PR TITLE
roachtest: remove panic from bare `go` function

### PR DESCRIPTION
**Pull request by renatolabs**
Unhandled panics in `go` functions cause the entire process to crash. In the case of roachtest, if a test does this, the entire nightly test suite crashes.

In this commit, we fix one instance where this can happen in the `perturbation` tests.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
As an example, see today's nightly run: [link](https://teamcity.cockroachdb.com/viewLog.html?buildId=16902836&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv).

**Review by nameisbhaskar — APPROVED** [review]
LGTM!

**Review by andrewbaptist — APPROVED** [review]
Thanks! I didn't realize a panic could take down the whole roachtest suite!

**Comment by renatolabs** [comment]
TFTRs!

bors r=nameisbhaskar,andrewbaptist

**Pull request merged**
