### PR TITLE
kvserver: skip TestStoreRangeMergeRHSLeaseExpiration

### PR DESCRIPTION
**Pull request by irfansharif**
It's been flaking on master. Tracking in #52514.

Release note: None

### CODE REVIEW

**Review by aayushshah15 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52515#-:-ME9-xj400qT8Sns1UQ7:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by nvb — APPROVED** [review]

**Comment by irfansharif** [comment]
```
Unexpected error: java.lang.RuntimeException: Failed to create context for build runner: Error creating bean with name 'jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor#0' defined in URL [jar:file:/home/agent/lib/agent.jar!/META-INF/buildAgentPerRunnerContext.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'runnerBuildRunAction' defined in URL [jar:file:/home/agent/lib/agent.jar!/META-INF/buildAgentPerRunnerContext.xml]: Cannot create inner bean 'jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallBuildRunnerPrecondition#55a30e2f' of type [jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallBuildRunnerPrecondition] while setting constructor argument with key [6]; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallBuildRunnerPrecondition#55a30e2f' defined in URL [jar:file:/home/agent/lib/agent.jar!/META-INF/buildAgentPerRunnerContext.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'agentServiceLocator': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'jetbrains.buildServer.agent.AgentFiles' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

Huh? @rafiss, know anything about this?

**Comment by rafiss** [comment]
@irfansharif not sure about that -- but it looks like it's coming from the guts of TeamCity possibly https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206240179-Build-agent-broken-after-upgrade

**Comment by jlinder** [comment]
It was caused by the agent being shut down. The agents run on preemptible servers that could be shut down at any time. From the logs: 
Screen Shot 2020-08-10 at 3 27 52 PM

**Pull request merged**
