### PR TITLE
sqlsmith: add COUNT in TLP testing

### PR DESCRIPTION
**Pull request by nehageorge**
Previously, only MAX and MIN aggregations were tested.
In this PR, the COUNT aggregation testing is restored from
the original TLP implementation. Albeit, this implementation
is modified to used SUM in conjunction with COUNT.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Cool!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-:-MlC4heG9etGIk3Z35wH:b-89q77x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge)

___
*[pkg/internal/sqlsmith/tlp.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-MlC4cSx5Y6tnU9byM1F:-MlC4cSx5Y6tnU9byM1G:b-m20p7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6d97fbf5633daea81e043daef96af050b482c3/pkg/internal/sqlsmith/tlp.go#L266)):*
> ```Go
> // are supported are MAX(), MIN(), SUM() and COUNT(). AVG() is also a valid TLP
> // aggregation, and the SUM/COUNT implementations can be extended to be
> // separated from one another.
> ```

not sure I understand what you mean by "separated from one another"
___
*[pkg/internal/sqlsmith/tlp.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-MlC49b4Eh1GBWOeZ2XU:-MlC49b4Eh1GBWOeZ2XV:b-64gog6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6d97fbf5633daea81e043daef96af050b482c3/pkg/internal/sqlsmith/tlp.go#L314)):*
> ```Go
> 		innerAgg, outerAgg = "MIN", "MIN"
> 	default:
> 		innerAgg, outerAgg = "COUNT", "SUM"
> ```

Can't you also support "SUM", "SUM"? The comment implies you support that too...

**Review by mgartner — APPROVED** [review]
Looks great. I think we should add SUM in this PR like @rytaft suggests while we're at it.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-:-MlCAWCx1qYbdft2vNp0:b-m5mwdk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge and @rytaft)

___
*[pkg/internal/sqlsmith/tlp.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-MlC4cSx5Y6tnU9byM1F:-MlC9ZhC23rbO6dri6Qf:bu7kzwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6d97fbf5633daea81e043daef96af050b482c3/pkg/internal/sqlsmith/tlp.go#L266)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

not sure I understand what you mean by "separated from one another"
</blockquote></details>

I believe Neha means that even though COUNT and SUM are currently tested together in a single TLP query, it should be possible to test them independently. 

IMO this can be left out of the sentence entirely. The inner aggregation performed on each partition is really the aggregation that is being tested. The fact that tests with COUNT have to have a SUM outer aggregation doesn't really mean that we are testing SUM. Of course, you could argue that we are testing anything in the entire query, but I would consider the outer query and UNIONs to be more "test infrastructure" than "test case".

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70985)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/internal/sqlsmith/tlp.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-MlC4cSx5Y6tnU9byM1F:-MlC6rET6SCl6XETnOrz:b1woaox) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6d97fbf5633daea81e043daef96af050b482c3/pkg/internal/sqlsmith/tlp.go#L266)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I believe Neha means that even though COUNT and SUM are currently tested together in a single TLP query, it should be possible to test them independently. 

IMO this can be left out of the sentence entirely. The inner aggregation performed on each partition is really the aggregation that is being tested. The fact that tests with COUNT have to have a SUM outer aggregation doesn't really mean that we are testing SUM. Of course, you could argue that we are testing anything in the entire query, but I would consider the outer query and UNIONs to be more "test infrastructure" than "test case".
</blockquote></details>

What I was trying to convey was how we could have a TLP oracle that uses COUNT without using SUM and vice versa. For COUNT, the structure of the query would need to be slightly restructured. Consider:

Partitioned:
```
SELECT COUNT(*) FROM (
  SELECT * FROM table WHERE (p)
  UNION ALL
  SELECT * FROM table WHERE NOT (p)
  UNION ALL
  SELECT * FROM table WHERE (p) IS NULL
)
```
Unpartitioned:
```
SELECT COUNT(*) FROM table
```

I thought it wouldn't make sense to create a separate function with this structure because COUNT is already tested in some manner. For SUM/SUM, see my other comment. However, I see how this comment can be confusing so I'll reword it.
___
*[pkg/internal/sqlsmith/tlp.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-MlC49b4Eh1GBWOeZ2XU:-MlC8ek4DrDBfY93d2jp:b-lnb9tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6d97fbf5633daea81e043daef96af050b482c3/pkg/internal/sqlsmith/tlp.go#L314)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can't you also support "SUM", "SUM"? The comment implies you support that too...
</blockquote></details>

This should always work for integer fields. However, with floats, we run into rounding issues. I think that we can definitely have a SUM oracle though, as Manuel Rigger discusses it in his [paper](https://www.manuelrigger.at/preprints/TLP.pdf). The implementation would be slightly less simple though, and Manuel discusses that aggregate functions are of lowest priority when implementing TLP, so I don't think it's worth it. 

I'll update the comment to be more clear.

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70985)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/internal/sqlsmith/tlp.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-MlC4cSx5Y6tnU9byM1F:-MlCCMeD91KVK0w2Rxwi:b-v6gwdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6d97fbf5633daea81e043daef96af050b482c3/pkg/internal/sqlsmith/tlp.go#L266)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

What I was trying to convey was how we could have a TLP oracle that uses COUNT without using SUM and vice versa. For COUNT, the structure of the query would need to be slightly restructured. Consider:

Partitioned:
```
SELECT COUNT(*) FROM (
  SELECT * FROM table WHERE (p)
  UNION ALL
  SELECT * FROM table WHERE NOT (p)
  UNION ALL
  SELECT * FROM table WHERE (p) IS NULL
)
```
Unpartitioned:
```
SELECT COUNT(*) FROM table
```

I thought it wouldn't make sense to create a separate function with this structure because COUNT is already tested in some manner. For SUM/SUM, see my other comment. However, I see how this comment can be confusing so I'll reword it.
</blockquote></details>

In regards to Marcus' comment:

I see what you're saying... I think that leaving this information out will make it easier to understand.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-:-MlCGGJQ0Zx_EwY9kWRS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nehageorge)

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-:-MlCNKTG1-OZIL3KHOGN:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @nehageorge)

___
*[pkg/internal/sqlsmith/tlp.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70985#-MlC49b4Eh1GBWOeZ2XU:-MlCN66A6NVjZ7Xw4MIy:b75sz2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6d97fbf5633daea81e043daef96af050b482c3/pkg/internal/sqlsmith/tlp.go#L314)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

This should always work for integer fields. However, with floats, we run into rounding issues. I think that we can definitely have a SUM oracle though, as Manuel Rigger discusses it in his [paper](https://www.manuelrigger.at/preprints/TLP.pdf). The implementation would be slightly less simple though, and Manuel discusses that aggregate functions are of lowest priority when implementing TLP, so I don't think it's worth it. 

I'll update the comment to be more clear.
</blockquote></details>

Interesting. Thanks for the explanation.

**Pull request merged**
