### PR TITLE
asim: add assertion, mutation-assertion events

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, the simulator relied on test code to create functions to be called
for delayed events. As we want to introduce more dynamic events through the
randomized testing framework, this approach becomes increasingly complex and
error-prone. In addition, we want to introduce new event types, such as
assertion events and mutation-assertion events to validate the simulation’s
state and verify the effects of prior mutation events.

To achieve these goals, the following changes were made in this patch:
1. Instead of directly adding functions to be invoked to simulator’s
delayEventList, events are now organized into different struct
(`SetSpanConfigEvent`, `AddNodeEvent`, `SetNodeLivenessEvent`, and
`SetCapacityOverrideEvent`). Each struct is equipped to generate its
corresponding function which can be called externally for event execution. These
events can be scheduled with `StaticEvents` using `ScheduleEvent` method with
just the required parameters.
2. `AssertionEvent` struct can now be used to schedule assertion events as part
of the simulation using `ScheduleEvent`.
3. `MutationWithAssertionEvent` can also be used now to schedule mutation events
coupled with subsequent assertion events using the
`ScheduleMutationWithAssertionEvent` method.

Under the hood, these events all implement the event interface. This interface
outlines
1. Func() returns a function that can be called externally.
2. String() returns a formatted output string. To accommodate varying function
types returned by `Func()`, we introduced another interface for different
function types to be used as an event func.

When event executor executes these events at their scheduled time, it retrieves
the functions calling Func() and calls them with the simulator's current state
and history.

Part of: #106192
Release note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
Please only review the last commit. The preceding commits are from https://github.com/cockroachdb/cockroach/pull/109337.

**Review by kvoli — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 22 of 25 files at r4, 1 of 29 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0ZLq26SoZOnCPRP5A):*
nit: You can format to just `#109316`, which will link on github.
___
*[`pkg/kv/kvserver/asim/event/assertion_event.go` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0dqh0EbNup7d-zQ8S:-Nd0dqh0EbNup7d-zQ8T:b-f0mgjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/assertion_event.go#L57)):*
> ```Go
> // when the event executor summarizes the executed events in the end.
> func (ag assertionEvent) String() string {
> 	return ""
> ```

Should this be `ag.reason` instead of `""`?
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0gjK7-YFTYUcxQ9h5:-Nd0gjK7-YFTYUcxQ9h6:bleknmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L88)):*
> ```Go
> 
> func (ae AddNodeEvent) String() string {
> 	return ""
> ```

Should this return an event description?
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0faVL23Bk-X3iVGi5:-Nd0faVL23Bk-X3iVGi6:b-bv1qch) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L92)):*
> ```Go
> 
> func (sne SetNodeLivenessEvent) Func() EventFunc {
> 	var fn MutationFunc = func(ctx context.Context, s state.State) {
> ```

nit: return inline.
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0fTlF9oLu-R1v9BKo:-Nd0fTlF9oLu-R1v9BKp:b-pd7qlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L102)):*
> ```Go
> 
> func (sne SetNodeLivenessEvent) String() string {
> 	return "'"
> ```

Should this return the event description?
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 106 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0iJUo78xorjS6QBCj:-Nd0iJUo78xorjS6QBCk:b-bv1qch) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L106)):*
> ```Go
> 
> func (sce SetCapacityOverrideEvent) Func() EventFunc {
> 	var fn MutationFunc = func(ctx context.Context, s state.State) {
> ```

nit: return inline.
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 114 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0iFcC-Kr6OuCSI_GX:-Nd0iFcC-Kr6OuCSI_GY:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L114)):*
> ```Go
> 
> func (sce SetCapacityOverrideEvent) String() string {
> 	return "'"
> ```

Same as above.
___
*[`pkg/kv/kvserver/asim/gen/event_generator.go` line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0iTWq5N-3941vXAjD:-Nd0iTWq5N-3941vXAjE:b-yh5ist) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/gen/event_generator.go#L27)):*
> ```Go
> 	// Generate returns a list of events, which should be exectued at the delay specified.
> 	Generate(seed int64, settings *config.SimulationSettings) scheduled.EventExecutor
> 	String() string /**/
> ```

Remove the inline `/**/`. 
___
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0n2M41t9T_5dZ1PaS:-Nd0n2M41t9T_5dZ1PaT:b-jqvc1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package scheduled
> ```

Should we add some testing for this functionality, or do you feel its sufficiently tested via the existing datadriven test code?
___
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0lbqz-h0JvARMpR_M:-Nd0lbqz-h0JvARMpR_N:b-w2yjud) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L28)):*
> ```Go
> // managing scheduled events, allowing event registration, tick-based
> // triggering. Please use NewExecutorWithNoEvents for proper initialization.
> type EventExecutor interface {
> ```

nit: could you also copy these comments onto the implementation? This is a personal preference.
___
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0mBQFBZzibNgbQjet:-Nd0mBQFBZzibNgbQjeu:b-8vc59f) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L34)):*
> ```Go
> 	// Start sorts the scheduled list chronologically, ready to execute events for
> 	// simulation.
> 	Start()
> ```

This doesn't feel necessary as an additional function, given it isn't triggering any sort of continuous runner. 

 Could you instead maintain a flag on `eventExecutor`, which is true if ticking has begun, and false otherwise. 

That way, you could check the flag and sort them on the first tick.

What do you think? 
___
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0lq0T90xU6hjLus1I:-Nd0lq0T90xU6hjLus1J:bun5atk) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L87)):*
> ```Go
> 
> func (e *eventExecutor) PrintEventsExecuted() string {
> 	return ""
> ```

Could you add a TODO here, or add the events executed.
___
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0jk0YEn3Z4vKsNXxz:-Nd0jk0YEn3Z4vKsNXy-:b-ao1t1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L135)):*
> ```
> 
> # We expect ranges to be randomly allocated across stores with a replication
> # factor of 1. Assertion failures on some samples are expected due to this
> ```

I think this description could be more specific.

"When the replication factor is 1, rebalancing falls back to adding a replica in order to rebalance. The original replica is expected to transfer its lease, and then be removed. In this setup, it is always possible to be overreplicated if rebalancing is occurring -- as we catch ranges in the middle of rebalancing."
___
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 139 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0jYW1-AbIrRmAnkQf:-Nd0jYW2-Y-AxZ5B4a3V:bapa36s) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L139)):*
> ```
> # leaseholder, it is locked into the current replica distribution. The
> # rebalancer falls back to adding one replica, hoping the rebalancing would
> # happen next time this range is checked. This can case thrashing where settling
> ```

Not from this PR, but `s/case/cause/`
___
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0kRGO49gDMiEsOyal:-Nd0kRGO49gDMiEsOyam:b-k8v0kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L142)):*
> ```
> # is difficult. In addition, we expect all output details to be displayed upon
> # test failure.
> ```

nit: rm empty line.
___
*[`pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0keQjC9_gweRDMF2p:-Nd0keQjC9_gweRDMF2q:brrtqm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go#L252)):*
> ```Go
> 				scanIfExists(t, d, "stores", &numStores)
> 				scanIfExists(t, d, "locality", &localityString)
> 				eventGen.ScheduleEvent(settingsGen.Settings.StartTime, delay, event.AddNodeEvent{
> ```

Nice, this is much cleaner now!

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/event/assertion_event.go` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0dqh0EbNup7d-zQ8S:-Nd1EuxcDNi9PxuXWL7R:bj2m7n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/assertion_event.go#L57)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should this be `ag.reason` instead of `""`?
</blockquote></details>

Printing output issues are handled in this subsequent PR #109602. It also tests the changes introduced in this PR.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0n2M41t9T_5dZ1PaS:-Nd1S2oa8j_oi0V1err-:b6jn78q) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L11)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should we add some testing for this functionality, or do you feel its sufficiently tested via the existing datadriven test code?
</blockquote></details>

Changes introduced in this PR is tested in #109602 as well where mutation and assertion events are executed.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0jk0YEn3Z4vKsNXxz:-Nd1SEUiEMBMgsJYeW1F:b-pmzw0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L135)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I think this description could be more specific.

"When the replication factor is 1, rebalancing falls back to adding a replica in order to rebalance. The original replica is expected to transfer its lease, and then be removed. In this setup, it is always possible to be overreplicated if rebalancing is occurring -- as we catch ranges in the middle of rebalancing."
</blockquote></details>

opps resolving merge conflicted messed this comment up. Didn't mean to change this. Is the current wording better?

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 139 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0jYW1-AbIrRmAnkQf:-Nd1S_LC2weCuvnGJAyC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L139)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Not from this PR, but `s/case/cause/`
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0keQjC9_gweRDMF2p:-Nd1Saz3DgzaeQaKtFMr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go#L252)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Nice, this is much cleaner now!
</blockquote></details>

Done.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0gjK7-YFTYUcxQ9h5:-Nd1Rwor1wn0JJbzjZ3o:beud97r) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L88)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should this return an event description?
</blockquote></details>

Same as above (Resolved in #109602).
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0fTlF9oLu-R1v9BKo:-Nd1Rnho0p5Z2ZVdgVdx:beud97r) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L102)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should this return the event description?
</blockquote></details>

Same as above (Resolved in #109602).
___
*[`pkg/kv/kvserver/asim/event/mutation_event.go` line 114 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0iFcC-Kr6OuCSI_GX:-Nd1RxK69rZ4KKiUZzz-:beud97r) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/event/mutation_event.go#L114)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Same as above (Resolved in #109602).
___
*[`pkg/kv/kvserver/asim/gen/event_generator.go` line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0iTWq5N-3941vXAjD:-Nd1RyyL0t4mxdaYX6bG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/gen/event_generator.go#L27)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Remove the inline `/**/`.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0lq0T90xU6hjLus1I:-Nd1S0CZ-GUy4RK7PMJ-:beud97r) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L87)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you add a TODO here, or add the events executed.
</blockquote></details>

Same as above (Resolved in #109602).

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0mBQFBZzibNgbQjet:-Nd1VGgkCvR40RCLqozQ:b2djhry) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L34)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This doesn't feel necessary as an additional function, given it isn't triggering any sort of continuous runner. 

 Could you instead maintain a flag on `eventExecutor`, which is true if ticking has begun, and false otherwise. 

That way, you could check the flag and sort them on the first tick.

What do you think?
</blockquote></details>

Agreed. I added a flag called `hasStarted` in eventExecutor which does that.

**Review by kvoli — APPROVED** [review]
:lgtm: minor nits on the commit message. 

Nice stuff!

> Reviewed 20 of 25 files at r8, 9 of 11 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-:-Nd1XSdu9PGvsKFbQw9w:b-abdqas)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 4 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd1W8eGBZETGK_poYef):*
nit: the simulator relied on
___
*[`-- commits` line 11 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd1WJg7DkddRUNfj3kr):*
nit the following changes were made
___
*[`pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0mBQFBZzibNgbQjet:-Nd1WheS4lS-THPzMujW:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/scheduled/scheduled_event_executor.go#L34)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Agreed. I added a flag called `hasStarted` in eventExecutor which does that.
</blockquote></details>

Thanks!
___
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0jk0YEn3Z4vKsNXxz:-Nd1WzuUBjuaXQvOSX9R:b-vs1prh) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L135)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

opps resolving merge conflicted messed this comment up. Didn't mean to change this. Is the current wording better?
</blockquote></details>

Looks good!
___
*[`pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0keQjC9_gweRDMF2p:-Nd1X76i3BnUEX1xzWrI:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go#L252)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

?

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109316#-Nd0keQjC9_gweRDMF2p:-Nd1Y9chDsbbxq0EJZCc:bgkob7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d828f8344cce090077c0e8e5570ba5b8086f42/pkg/kv/kvserver/asim/tests/datadriven_simulation_test.go#L252)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

?
</blockquote></details>

Was trying to clear "to_reply" on reviewable to zero haha

**Comment by wenyihu6** [comment]
TFTR!

bors r=kvoli

**Pull request merged**
