### PR TITLE
sql: Create constantFolderVisitor to fold ConstVals using exact arithmetic

### PR DESCRIPTION
**Pull request by nvb**
Create an initial implementation of `constantFolderVisitor`, which will
walk an `Expr` tree and fold all `ConstVals` using exact arithmetic.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6298)

### CODE REVIEW

**Comment by petermattis** [comment]
`foldNumericConstants` isn't called from anywhere. I imagine that is coming in a subsequent PR, but it would be nice to give a preview in the commit message.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/group.go, line 107 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGF3foXIWmWC6QENP8n:-KGF3foXIWmWC6QENP8o:1416772361) ([raw file](https://github.com/cockroachdb/cockroach/blob/d70231e4fdb0039787e57869408d5cdf6048e825/sql/group.go#L107)):*
What is this code movement about? It seems unrelated to `foldNumericConstants`.

---

*[sql/parser/normalize.go, line 502 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGF2IN2Dp1IVcTWBr0C:-KGF2IN31GPikfjpOZIc:721932629) ([raw file](https://github.com/cockroachdb/cockroach/blob/d70231e4fdb0039787e57869408d5cdf6048e825/sql/parser/normalize.go#L502)):*
`constantFolderVisitor` doesn't have any state, so these should be methods on `constantFolderVisitor`, not `*constantFolderVisitor` which will save an allocation which invoking `foldNumericConstants`.

---

*[sql/parser/normalize.go, line 581 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGF2YBuDG5SLYCxgaVS:-KGF2YBvvma8p0OTtD33:141439331) ([raw file](https://github.com/cockroachdb/cockroach/blob/d70231e4fdb0039787e57869408d5cdf6048e825/sql/parser/normalize.go#L581)):*
Is there a reason this only folds numeric constants? What about `'a' || 'b'`? I imagine that is a lot less common, so a TODO or other comment would be fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-:-KGF3LnHupn4bWK0WHgg:534813107)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-:-KGF3til44IAdv8QqsnR:1417088721)*

**Comment by nvanbenschoten** [comment]
Thanks for the review. Added in a note to the commit message about `foldNumericConstants` not yet being called. 

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/group.go, line 107 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGF3foXIWmWC6QENP8n:-KGFqMK5dJe5D2wFKYog:1022791278) ([raw file](https://github.com/cockroachdb/cockroach/blob/d70231e4fdb0039787e57869408d5cdf6048e825/sql/group.go#L107)):*
Yeah it is unrelated, but its just a small change that I didnt think warranted a whole commit. I'm just moving normalization after type checking, where it belongs.

---

*[sql/parser/normalize.go, line 502 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGF2IN2Dp1IVcTWBr0C:-KGFl1PIEcpzEmKDkFVy:1562655775) ([raw file](https://github.com/cockroachdb/cockroach/blob/d70231e4fdb0039787e57869408d5cdf6048e825/sql/parser/normalize.go#L502)):*
Ah yeah, I made this [change](https://github.com/cockroachdb/cockroach/compare/master...nvanbenschoten:nvanbenschoten/type_check#diff-9498abd5bbdfcd73f8064a4f6e918ee1R327) a few commits later, but I'll pull it back to here.

---

*[sql/parser/normalize.go, line 581 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGF2YBuDG5SLYCxgaVS:-KGFlm1H0UIAZTl5OH8C:904693686) ([raw file](https://github.com/cockroachdb/cockroach/blob/d70231e4fdb0039787e57869408d5cdf6048e825/sql/parser/normalize.go#L581)):*
String constants are coming in a subsequent PR!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-:-KGFlsEElMEHiXqi8SkK:-1708050975)*

**Comment by knz** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/normalize.go, line 565 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGHX8bKTlNGDDH03vat:-KGHX8bKTlNGDDH03vau:-1463215137) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/parser/normalize.go#L565)):*
I think the customary arithmetic checks should be done here:
- error on divide by zero unless we have an exact infinity representation
- error on 0/0
- error on xor/and/or when the operand is not an integer
- warning on shifts with an unusually large rhs operand (eg shift larger than 63)

---

*[sql/parser/normalize_test.go, line 97 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGHZ0URFWx6SKTtdV4r:-KGHZ0US_4Q8JahaX3Vk:-1813591729) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/parser/normalize_test.go#L97)):*
there should be tests here for the cases discussed in my comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/normalize.go, line 565 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGHX8bKTlNGDDH03vat:-KGHq2OZGgc_gLC2bT7E:87413021) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/parser/normalize.go#L565)):*
All covered in a later commit :+1: (except for the integer stuff that is covered here using the different maps). The actual approach I take though is just to abort folding and let type checking/normalization/evaluation deal with errors (for consistency).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298)*

**Comment by knz** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-:-KGHumDGiO6i6MPJx_AO:1417088721)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/select.go, line 477 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI163SijST7JFXV7zi:-KGI163SijST7JFXV7zj:1762158650) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/select.go#L477)):*
why do we prefer this? The "ifs" are "distractions" from the normal flow, which IMO is easier to see in the old code (by just ignoring the ifs)..

---

*[sql/parser/normalize_test.go, line 29 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI1svj13unrxxGV3_p:-KGI1svj13unrxxGV3_q:1477389349) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/parser/normalize_test.go#L29)):*
Maybe we should have a few tests that involve non-constants, to make sure those are handled correctly? e.g. `a + 5 * 2 => a + 10`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-:-KGI2D7akDfStF62289x:1417088721)*

**Comment by nvanbenschoten** [comment]
Thanks for the reviews.

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 477 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI163SijST7JFXV7zi:-KGI7PDiJTVl6CEagw0V:-1986064956) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/select.go#L477)):*
It's idiomatic in Go when not declaring any new variables or when their scopes are only needed within a following `if` block to put it all in one line.

---

*[sql/parser/normalize_test.go, line 29 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI1svj13unrxxGV3_p:-KGI8HWKaDQe_SIjBf-l:-1821355468) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/parser/normalize_test.go#L29)):*
Good idea. Done.

Doing so also made it clear that I should later investigate normalizing associative operations before folding. See the TODO I added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-:-KGIAVxQ9vBiTAenGzU9:-1063767573)*

**Comment by petermattis** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/normalize.go, line 582 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGIBEJpe4hpCCQiExlO:-KGIBEJqtkRgnfOlpJUE:-1456011963) ([raw file](https://github.com/cockroachdb/cockroach/blob/889bc6dae78066e0350843d5aa5e592d4ba2baa4/sql/parser/normalize.go#L582)):*
Doesn't `normalize()` already do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/normalize.go, line 582 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGIBEJpe4hpCCQiExlO:-KGIBS913ACTgTAE3zC9:1956285195) ([raw file](https://github.com/cockroachdb/cockroach/blob/889bc6dae78066e0350843d5aa5e592d4ba2baa4/sql/parser/normalize.go#L582)):*
I don't think it would handle `((a +2) + b) + 3` => `(a + 5) + b`, but I would be happily proved wrong. `*ComparisonExpr.normalize` comes close though, so we might be able to write something that would work for both folding and later normalization on nested `*BinaryExpr`s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 477 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI163SijST7JFXV7zi:-KGIDj3BScW181vfbpFf:-2104879316) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/select.go#L477)):*
I think its idiomatic to do that when the modified vars are only relevant inside that if block..

---

*[sql/parser/normalize_test.go, line 29 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI1svj13unrxxGV3_p:-KGIDyJvczH_ouD1xDub:1341471585) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/parser/normalize_test.go#L29)):*
Nice. Yeah, `a + 1 + 2 = (a + 1) + 2` won't really work at this point

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-:-KGIEEAgL9cp8V5wW5s_:1417088721)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/select.go, line 477 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI163SijST7JFXV7zi:-KGIHWnAVfd5Zf3rCZG-:142903981) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/select.go#L477)):*
There are plenty of examples of the pattern throughout our code and the stdlib where that assumption doesn't hold, but since this is primarily code that you work on and you find it distracting, I'm happy to change it back.

Regardless, I'd like to decide on stuff like this once (one way or another) at some point so we can avoid syntax discussions as much as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/select.go, line 477 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI163SijST7JFXV7zi:-KGIKI8xlRP-kmHAWDA0:-1034271193) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/select.go#L477)):*
You have my LGTM either way - if you like it this way, feel free to merge. Agreed on the second point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298)*

**Comment by bdarnell** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/select.go, line 477 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298#-KGI163SijST7JFXV7zi:-KGILJjhZ7Q2c8J4W2rJ:1378401073) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a52561ad261b6588a47e1d087fc188a8a6845be/sql/select.go#L477)):*
Our style rule is to minimize the scope of variables when possible. Since these `ifs` do not introduce new variables (they use `=` instead of `:=`), I think it's better to use separate statements (but don't feel strongly given the prevalence of the combined form in our codebase).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6298)*

**Pull request merged**
