### PR TITLE
sql: hints for CROSS JOIN

### LINKED ISSUE #35695: opt: Extend hints to CROSS JOIN
Extend our hinting syntax to include CROSS JOINS to make it easier to rewrite complicated queries to force specific join types. 

Consider this TPC-H query:
```
SELECT
    o_year,
    sum(CASE WHEN nation = 'BRAZIL' THEN volume ELSE 0 END)
    / sum(volume)
        AS mkt_share
FROM
    (
        SELECT
            extract('year', o_orderdate) AS o_year,
            l_extendedprice * (1 - l_discount) AS volume,
            n2.n_name AS nation
        FROM
            part,
            supplier,
            lineitem,
            orders,
            customer,
            nation AS n1,
            nation AS n2,
            region
        WHERE
            p_partkey = l_partkey
            AND s_suppkey = l_suppkey
            AND l_orderkey = o_orderkey
            AND o_custkey = c_custkey
            AND c_nationkey = n1.n_nationkey
            AND n1.n_regionkey = r_regionkey
            AND r_name = 'AMERICA'
            AND s_nationkey = n2.n_nationkey
            AND o_orderdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
            AND p_type = 'ECONOMY ANODIZED STEEL'
    )
        AS all_nations
GROUP BY
    o_year
ORDER BY
    o_year;
```
It comes with several joins:
```
                                   tree                                   |       field        |                     description
+-------------------------------------------------------------------------+--------------------+-----------------------------------------------------+
  render                                                                  |                    |
   └── sort                                                               |                    |
        │                                                                 | order              | +o_year
        └── render                                                        |                    |
             └── group                                                    |                    |
                  │                                                       | aggregate 0        | o_year
                  │                                                       | aggregate 1        | sum(column63)
                  │                                                       | aggregate 2        | sum(volume)
                  │                                                       | group by           | @2
                  └── render                                              |                    |
                       └── render                                         |                    |
                            └── join                                      |                    |
                                 │                                        | type               | inner
                                 │                                        | equality           | (l_partkey) = (p_partkey)
                                 │                                        | right cols are key |
                                 ├── join                                 |                    |
                                 │    │                                   | type               | inner
                                 │    │                                   | equality           | (l_suppkey, n_nationkey) = (s_suppkey, s_nationkey)
                                 │    │                                   | right cols are key |
                                 │    ├── join                            |                    |
                                 │    │    │                              | type               | inner
                                 │    │    │                              | equality           | (l_orderkey) = (o_orderkey)
                                 │    │    ├── scan                       |                    |
                                 │    │    │                              | table              | lineitem@primary
                                 │    │    │                              | spans              | ALL
                                 │    │    └── join                       |                    |
                                 │    │         │                         | type               | inner
                                 │    │         │                         | equality           | (c_custkey) = (o_custkey)
                                 │    │         ├── join                  |                    |
                                 │    │         │    │                    | type               | cross
                                 │    │         │    ├── lookup-join      |                    |
                                 │    │         │    │    │               | table              | customer@c_nk
                                 │    │         │    │    │               | type               | inner
                                 │    │         │    │    └── lookup-join |                    |
                                 │    │         │    │         │          | table              | nation@n_rk
                                 │    │         │    │         │          | type               | inner
                                 │    │         │    │         └── scan   |                    |
                                 │    │         │    │                    | table              | region@primary
                                 │    │         │    │                    | spans              | ALL
                                 │    │         │    │                    | filter             | r_name = 'AMERICA'
                                 │    │         │    └── scan             |                    |
                                 │    │         │                         | table              | nation@primary
                                 │    │         │                         | spans              | ALL
                                 │    │         └── index-join            |                    |
                                 │    │              │                    | table              | orders@primary
                                 │    │              └── scan             |                    |
                                 │    │                                   | table              | orders@o_od
                                 │    │                                   | spans              | /9131-/9862
                                 │    └── scan                            |                    |
                                 │                                        | table              | supplier@s_nk
                                 │                                        | spans              | ALL
                                 └── scan                                 |                    |
                                                                          | table              | part@primary
                                                                          | spans              | ALL
                                                                          | filter             | p_type = 'ECONOMY ANODIZED STEEL'
(55 rows)

Time: 4.319157ms
```
To force specific join types, a user would need to re-write this query. Cross joins are syntactically closer to how these joins would be re-written and are therefore an easier transformation for this type of query than the currently supported syntax.

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding support for cross join hints, for example `CROSS MERGE JOIN`.

Fixes #35695.

Release note (sql change): it is now possible to specify a HASH /
MERGE / LOOKUP join hint with cross joints (CROSS <hint> JOIN).

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CCC @rmloveland for updating docs.

**Comment by RaduBerinde** [comment]
CC @awoods187

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35700#-:-L_s_o7X6MrprPzcKINc:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by rytaft — APPROVED** [review]
[nit] joints -> joins in the commit message/PR message release note

otherwise, :lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35700#-:-L_sjlNNEY2Inu9_mhzI:b-as2qj2)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — APPROVED** [review]
yep that works :)

**Pull request merged**
