### PR TITLE
colexec: speed up substring operator

### PR DESCRIPTION
**Pull request by yuzefovich**
**lint: add a recently created package to TestGCAssert**

Release note: None

**colexec: speed up substring operator**

This commit speeds up the substring operator by pre-calculating whether
argument vectors have null values.
```
name                                                         old time/op    new time/op    delta
CompareSpecializedOperators/SpecializedSubstringOperator-24    44.1µs ± 0%    30.6µs ± 0%  -30.58%  (p=0.000 n=10+10)

name                                                         old speed      new speed      delta
CompareSpecializedOperators/SpecializedSubstringOperator-24   255MB/s ± 0%   368MB/s ± 0%  +44.06%  (p=0.000 n=10+10)

name                                                         old alloc/op   new alloc/op   delta
CompareSpecializedOperators/SpecializedSubstringOperator-24     0.00B          0.00B          ~     (all equal)

name                                                         old allocs/op  new allocs/op  delta
CompareSpecializedOperators/SpecializedSubstringOperator-24      0.00           0.00          ~     (all equal)
```
My original goal was to add bounds-checks elimination, but that only
showed about 2% speedup, so I decided to not add that (it would double
the amount of generated code). Similarly, about 1.5% speedup would be
achieved if we templated out the nulls as we do in other places, and
I too decided against it.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
@yuzefovich -- this PR didn't have a CI run due to a TC misconfiguration. If you force-push to this branch now you can trigger another CI run.

**Review by rharding6373 — APPROVED** [review]
Nice! :lgtm: 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81532#-:-N2TCU_H63w7uT3ECOWO:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Review by msirek — APPROVED** [review]
Cool!

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81532#-:-N2TDjaTAPELASciV_f8:b-zc539b)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
