### PR TITLE
acceptance: download reference binaries

### PR DESCRIPTION
**Pull request by danhhz**
instead of getting them from docker. The versions really should be bumped in the
same commit that needs the bump. Right now, they are in a separate repo
(https://github.com/cockroachdb/postgres-test).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8453)

### CODE REVIEW

**Comment by dt** [comment]
Any idea how we get circle-ci to cache `bin` ?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-:-KOqDYpniHDzTiimxlMz:b-iwtklu)*

**Comment by tamird** [comment]
https://github.com/cockroachdb/cockroach/blob/master/circle.yml#L32

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[acceptance/reference_test.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGWVMX7e5kYYBk0yg:-KOqGWVMX7e5kYYBk0yh:b-6olv77) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L43)):*
> ```Go
> 	}
> 
> 	t.Logf("Downloading %s", url)
> ```

is this the only use of `t` in this function? seems like it'd be ok to omit.

---

*[acceptance/reference_test.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqFWpiZOpdrWeHPjP7:-KOqFWpiZOpdrWeHPjP8:bfe6jek) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L55)):*
> ```Go
> 	}
> 	defer unzipped.Close()
> 	unzipped.Multistream(false)
> ```

hm. comment?

---

*[acceptance/reference_test.go, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqFcRqmmnMKbmmkNSJ:-KOqFcRqmmnMKbmmkNSK:bl8scn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L58)):*
> ```Go
> 
> 	untarred := tar.NewReader(unzipped)
> 	for header, err := untarred.Next(); ; header, err = untarred.Next() {
> ```

probably will read better as
```
for {
  header, err := ....
  ...
}
```

---

*[acceptance/reference_test.go, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqFmBe3bHSRmv4enDJ:-KOqFmBe3bHSRmv4enDK:b-owyun8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L65)):*
> ```Go
> 			return err
> 		}
> 		if filepath.Base(header.Name) == `cockroach` {
> ```

why the backticks?

---

*[acceptance/reference_test.go, line 66 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqG-YyuHb2sgbv0Mji:-KOqG-YyuHb2sgbv0Mjj:b-258iqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L66)):*
> ```Go
> 		}
> 		if filepath.Base(header.Name) == `cockroach` {
> 			if err := os.MkdirAll(filepath.Dir(outfile), 0777); err != nil {
> ```

seems like 755 would suffice.

---

*[acceptance/reference_test.go, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGMMt98DqumBWvR05:-KOqGMMt98DqumBWvR06:braff7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L75)):*
> ```Go
> 			defer out.Close()
> 
> 			_, err = io.Copy(out, untarred)
> ```

inline on the next line

---

*[acceptance/reference_test.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGQcGx1YrbeVkNtKI:-KOqGQcGx1YrbeVkNtKJ:bkct4sk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L83)):*
> ```Go
> 		}
> 	}
> 	return fmt.Errorf("no cockroach binary found")
> ```

this error is really anemic - by the time you get here you've gone to the network and tried to ungzip and untar the thing; surely there's more detail you can provide.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOqGvf6mqL38Ha8UPNZ:by0id9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
> ```Go
> 
> echo "Read the modified data using the reference binary again."
> bin=/go/src/github.com/cockroachdb/cockroach/bin/cockroach-%s
> ```

this strikes me as potentially not very robust - what would happen in the case of freestanding test binaries?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-:-KOqFIryoIlutwzU_HMZ:b-l966js)*

**Comment by paperstreet** [comment]
TFTRs!

It keeps timing out while starting up the docker image in circleci, but works in teamcity. Maybe the cacheing change in this revision will help?

---

Review status: 2 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[acceptance/reference_test.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGWVMX7e5kYYBk0yg:-KOqPpQGv0ObiYyg8x-4:b-gg1lrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this the only use of `t` in this function? seems like it'd be ok to omit.
</details>
Made it a normal log.Info

---

*[acceptance/reference_test.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqFWpiZOpdrWeHPjP7:-KOqOgu5NoRhiIEXc5l0:b-3g379r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L55)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> hm. comment?
</details>
Not really needed. Deleted instead

---

*[acceptance/reference_test.go, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqFcRqmmnMKbmmkNSJ:-KOqOmBXQLH4ym3LgLGU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L58)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> probably will read better as
> ```
> for {
>   header, err := ....
>   ...
> }
> ```
</details>
Done.

---

*[acceptance/reference_test.go, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqFmBe3bHSRmv4enDJ:-KOqOoMS8kbczhGrDWlg:bsb7ufp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L65)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the backticks?
</details>
Dunno.

---

*[acceptance/reference_test.go, line 66 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqG-YyuHb2sgbv0Mji:-KOqOxEsyEKL5iQ0lf8p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> seems like 755 would suffice.
</details>
Done.

---

*[acceptance/reference_test.go, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGMMt98DqumBWvR05:-KOqP0iGDUpGO6JH_NfC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> inline on the next line
</details>
Done.

---

*[acceptance/reference_test.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGQcGx1YrbeVkNtKI:-KOqPNgq7t6gp6weYowE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this error is really anemic - by the time you get here you've gone to the network and tried to ungzip and untar the thing; surely there's more detail you can provide.
</details>
Done.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOqPViMyISHvMl7IoPV:bf1ssp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this strikes me as potentially not very robust - what would happen in the case of freestanding test binaries?
</details>
I don't quite follow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-:-KOqQQ3vK-gr8ttYFC11:b7pyqee)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOrRY2TXWwn9G699CST:bk5bcsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I don't quite follow
</details>
There's no guarantee that this directory structure is present in the case of someone having compiled the acceptance tests into a standalone binary using `go test -c`. This is not a theoretical concern; we do this on every master build and upload the test binaries to s3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOqHuQyndmXGY4fcrJ3:bb1p5ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> There's no guarantee that this directory structure is present in the case of someone having compiled the acceptance tests into a standalone binary using `go test -c`. This is not a theoretical concern; we do this on every master build and upload the test binaries to s3.
</details>
but this is running inside the `postgres-test` image where we control the dir structure, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOthbNzhGIBBwedxkXO:bqo5uhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> but this is running inside the `postgres-test` image where we control the dir structure, no?
</details>
I must be missing something. `maybeDownloadBinary` is surely invoked outside the `postgres-test` image, right? How does the relative path `../bin` used in that function end up mounted inside the postgres-test container?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOtj7XsHjGoHtN1W6CS:b-3k8hhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I must be missing something. `maybeDownloadBinary` is surely invoked outside the `postgres-test` image, right? How does the relative path `../bin` used in that function end up mounted inside the postgres-test container?
</details>
So the mount happens in `initCluster` where this is added to the binds: ```filepath.Join(pwd, "..") + ":/go/src/github.com/cockroachdb/cockroach",```, so I'm not sure how any of these tests work if run from a standalone binary that isn't executing from the `acceptance` subdir of a checkout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOtlXmftSNpWxj0CsQg:bvx7lq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> So the mount happens in `initCluster` where this is added to the binds: ```filepath.Join(pwd, "..") + ":/go/src/github.com/cockroachdb/cockroach",```, so I'm not sure how any of these tests work if run from a standalone binary that isn't executing from the `acceptance` subdir of a checkout.
</details>
Ah. I think it might still work - it's not clear that anything is actually using the acceptance dir specifically. That mount was added in 7a352f6e14ef8bb50994b1a559c602b0f4e7a9b6 - take a look at that commit message; it's only for pprof.

@paperstreet we need some commentary on this path that explains this subtlety, or else we need to add a different bind that is more deliberate in terms of where it mounts these binaries. In fact, I think I'd prefer that `../bin` be changed to `bin` (so that it's under acceptance/bin normally) and be mounted at `/cockroach-reference-binaries/` inside the container; I think that would be much more explicit and clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOtmWjiBMwODCIVvmey:btm0wg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Ah. I think it might still work - it's not clear that anything is actually using the acceptance dir specifically. That mount was added in 7a352f6e14ef8bb50994b1a559c602b0f4e7a9b6 - take a look at that commit message; it's only for pprof.
> 
> @paperstreet we need some commentary on this path that explains this subtlety, or else we need to add a different bind that is more deliberate in terms of where it mounts these binaries. In fact, I think I'd prefer that `../bin` be changed to `bin` (so that it's under acceptance/bin normally) and be mounted at `/cockroach-reference-binaries/` inside the container; I think that would be much more explicit and clear.
</details>
As long as we're going that route, I'd just make it super explicit what that dir is for -- `.reference-binary-cache` or something.

I'd initially suggested introducing a top-level `bin` dir so we could also start putting our version-pinned tools (errcheck, safesql, etc) there, rather than relying on / clobbering the user's PATH, but I guess there's no particular this test needs to share that dir.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/reference_test.go, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453#-KOqGvf6mqL38Ha8UPNY:-KOtmgD4X3Pmjti7fw4P:bvwe2to) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7fc15f0abeb04ec893acb5a6e0b7cc44e389178/acceptance/reference_test.go#L157)):*
Sure, bikeshed the name as you see fit.

One last thing: currently the `OneShot` containers use the same volume as the rest of the cluster - the comment on `OneShot` ends:
> // Adds the same binds as the cluster containers (certs, binary, etc).

However, this is overkill and can lead to confusing implicit behaviour of the sort we've been discussing here. ISTM that only the the certs bind is needed in the one shot containers. Decoupling that will require changing `l.vols` to a slice, so that we can have a volume container for the certs and another for everything else needed to run a cluster node (logs, binary). This PR need not be saddled with that, but please add a TODO while you're here. I'd be OK with you putting my name on that TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8453)*

**Comment by paperstreet** [comment]
Okay, the time it's taking to debug the circleci failures is not worth the benefit, so I'm closing this for now.

Open issues:
- we seem to be running the acceptance tests with a PWD of "cockroach" on circleci, but "acceptance" locally
- circleci keeps making things as root and then not being able to access them in the test

**Pull request closed without merging**
