### PR TITLE
go.mod: bump Pebble to bfc74496212f

### PR DESCRIPTION
**Pull request by dt**
```
https://github.com/cockroachdb/pebble/commit/bfc74496 define FormatSyntheticPrefixes version
https://github.com/cockroachdb/pebble/commit/a27878fb ingest,manifest,sstable: connect prefix rules in ingest to prefix replacing iterators
https://github.com/cockroachdb/pebble/commit/a452c0e5 manifest: add encoding of prefix rules to manifest entries
https://github.com/cockroachdb/pebble/commit/e7d75289 sstable: add prefixReplacingIterator
https://github.com/cockroachdb/pebble/commit/e40df58f sstable: add prefix arg to buildTestTableWithProvider
https://github.com/cockroachdb/pebble/commit/35cfce46 external_iterator: don't double-close Readers in case of err
https://github.com/cockroachdb/pebble/commit/69994ddb sstable: update comment about SINGLEDEL, foreign ssts and compactions
https://github.com/cockroachdb/pebble/commit/40d5f216 db: code comment about guaranteeing durability of initial state
https://github.com/cockroachdb/pebble/commit/5c5ad7ed keyspan: add Assert iterator
https://github.com/cockroachdb/pebble/commit/bbf7dc40 db: deprecate older format versions
```
Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116866#-:-Nm7NoSGAGgUHE7ipE2U:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @itsbilal)

___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116866#-Nm7NHVs1RnvDt0ai1FU:-Nm7NHVs1RnvDt0ai1FV:bqp36w0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f326dfffa02e3c57f44b2fe035ebcaceef7a4a1d/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L276)):*
> ```Go
> 	stats, err := db.GetEnvStats()
> 	require.NoError(t, err)
> 	// Opening the DB should've created OPTIONS, CURRENT, MANIFEST and the
> ```

[nit] These comments need to be updated (eg there is no more CURRENT). Not exactly sure where 4 and 5 come from, maybe you can print TotalFiles and ActiveKeyFiles to get an idea.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116866)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @RaduBerinde)

___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116866#-Nm7NHVs1RnvDt0ai1FU:-Nm7_Esq6ql7B4RSrYIw:b-fhxhg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f326dfffa02e3c57f44b2fe035ebcaceef7a4a1d/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L276)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] These comments need to be updated (eg there is no more CURRENT). Not exactly sure where 4 and 5 come from, maybe you can print TotalFiles and ActiveKeyFiles to get an idea.
</blockquote></details>

5 comes from: 
MANIFEST-000001 
OPTIONS-000003 
marker.format-version.000004.016 
marker.manifest.000001.MANIFEST-000001 
000002.log

**Comment by RaduBerinde** [comment]
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116866#-Nm7NHVs1RnvDt0ai1FU:-Nm7ekKv2uJ3m6SurUJl:b-tiflbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f326dfffa02e3c57f44b2fe035ebcaceef7a4a1d/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L276)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

5 comes from: 
MANIFEST-000001 
OPTIONS-000003 
marker.format-version.000004.016 
marker.manifest.000001.MANIFEST-000001 
000002.log
</blockquote></details>

That looks expected, not sure why the other one is just 4. (maybe th3 log is empty?)

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
