### PR TITLE
sql: Add user id columns to system tables with usernames/roles

### PR DESCRIPTION
**Pull request by Fenil-P**
Release note (sql change): system. (users, role_members, role_options and database_role_settings) have corresponding id columns. Updated the affected sql syntax to work with the changes.

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 7 of 16 files at r2, 3 of 13 files at r3, 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76612)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Fenil-P)

___
*[pkg/security/user_info.go, line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-Mynagjt7YSv3l-Vg98A:-Mynagjt7YSv3l-Vg98B:bt6xpa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/security/user_info.go#L20)):*
> ```Go
> // Note: avoid using this function when processing strings
> // in requests from external APIs.
> func MakeSQLUserInfoFromPreNormalizedString(username string, ID string) SQLUserInfo {
> ```

Why is ID string here?  It your callers you're casting an oid to string, let's just use oid/uint32 instead of casting .
___
*[pkg/sql/alter_default_privileges.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MynbBLF2qdTV8Po3C6y:-MynbBLF2qdTV8Po3C6z:bri1tgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/sql/alter_default_privileges.go#L147)):*
> ```Go
> 		for _, targetRole := range targetRoles {
> 			if targetRole != params.p.User() {
> 				memberOf, err := params.p.MemberOfWithAdminOption(params.ctx, security.SQLUserInfo{params.p.User(), 0})
> ```

Seems weird that we're using 0 here, ideally we'd also have a `params.p.UserID()` in the short term we can implement `params.p.UserID()` by doing a query on the username.
___
*[pkg/sql/authorization.go, line 582 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MynbuvSCFqu1lUIrYLv:-MynbuvSCFqu1lUIrYLw:bilxfpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/sql/authorization.go#L582)):*
> ```Go
> 			roleName := tree.MustBeDString(row[0])
> 			isAdmin := row[1].(*tree.DBool)
> 			roleID := row[2].(*tree.DOid).String()
> ```

Probably better to not convert to a string
___
*[pkg/sql/username_util.go, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MyncI4oAQQgm0ULIgMi:-MyncI4oAQQgm0ULIgMj:b-4ucmhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/sql/username_util.go#L27)):*
> ```Go
> )
> 
> // GetUserIDWithCache returns id of the user if role exists
> ```

Let's not worry about caching using IDs for simplicity for now and always use `GetUserID` we create an issue to add back the cache after.
___
*[pkg/startupmigrations/migrations.go, line 788 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MyncgfkAL_2Przj5YN1:-MyncgfkAL_2Przj5YN2:bghxr81) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/startupmigrations/migrations.go#L788)):*
> ```Go
> 
> 	h := fnv.New32()
> 	h.Write([]byte(security.RootUser))
> ```

Why do we need this?

**Review by RichardJCai — CHANGES_REQUESTED** [review]
This is great, lays the foundation for adding the system table and a struct for holding the IDs.
I think we're close to being able to merge this as standalone but I'd like to see the meta issue detailing what we need to do after. 

Ie (update logic to resolve based on ID when possible with version gates, migration, re-enable cache, fix to backup restore)

> Reviewed 40 of 40 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-:-MzIreg_1t2h4HG8-ugV:bfudc74)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Fenil-P)

___
*[pkg/sql/authorization.go, line 399 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MzIq--rEJYjE6aa3Cl6:-MzIq--rEJYjE6aa3Cl7:b-y58wjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2c91cbc621a7437f40698b32ad53ba3004523e/pkg/sql/authorization.go#L399)):*
> ```Go
> 		return nil, errors.AssertionFailedf("cannot use MemberOfWithAdminoption without a txn")
> 	}
> 	if member.UserID == 0 {
> ```

I'd prefer if we did the check upfront in the function that calls this, we should be able to call `GetUserID` in the caller functions right?

Also for all callers of `GetUserID` lets make sure to check the error.
___
*[pkg/sql/authorization.go, line 551 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MzIqiMn9Mc7knB6OXk2:-MzIqiMo6xa0RqBLPUyF:b-yjk6rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2c91cbc621a7437f40698b32ad53ba3004523e/pkg/sql/authorization.go#L551)):*
> ```Go
> 			}
> 		}
> 		recurse(member.Username)
> ```

This recurse and membership check should be updated to check based on IDs (if the ID exists) - we can do it in a follow up PR as long as we have an issue tracking it.
___
*[pkg/sql/create_table.go, line 2077 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MzIr1IN5vJDRcoDOyKz:-MzIr1IN5vJDRcoDOyL-:b-v1hcat) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2c91cbc621a7437f40698b32ad53ba3004523e/pkg/sql/create_table.go#L2077)):*
> ```Go
> 			if cdd[i] != nil {
> 				if err := cdd[i].ForEachTypedExpr(func(expr tree.TypedExpr) error {
> 					if vt != nil {
> ```

This is probably not the right place to add this `vt != nil` I think we need to push it deeper into `maybeAddSequenceDependencies` to where the nil ptr ref happens.

**Review by Fenil-P — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76612)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @RichardJCai, and @stevendanna)

___
*[pkg/security/user_info.go, line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-Mynagjt7YSv3l-Vg98A:-MywQfuE7x5fmZfzKGZT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/security/user_info.go#L20)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Why is ID string here?  It your callers you're casting an oid to string, let's just use oid/uint32 instead of casting .
</blockquote></details>

Done.
___
*[pkg/sql/alter_default_privileges.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MynbBLF2qdTV8Po3C6y:-MywSWJh6LvKrwakPlII:b-ay7dxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/sql/alter_default_privileges.go#L147)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Seems weird that we're using 0 here, ideally we'd also have a `params.p.UserID()` in the short term we can implement `params.p.UserID()` by doing a query on the username.
</blockquote></details>

I've added that in the next PR, most functions will either receive a UserInfo struct or fetch the ID before passing the struct.
___
*[pkg/sql/authorization.go, line 582 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MynbuvSCFqu1lUIrYLv:-MywUYrJ0-AUOjGUVcs_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/sql/authorization.go#L582)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Probably better to not convert to a string
</blockquote></details>

Done.
___
*[pkg/sql/authorization.go, line 399 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MzIq--rEJYjE6aa3Cl6:-MzLqU770DDwz8jmsYtm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2c91cbc621a7437f40698b32ad53ba3004523e/pkg/sql/authorization.go#L399)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I'd prefer if we did the check upfront in the function that calls this, we should be able to call `GetUserID` in the caller functions right?

Also for all callers of `GetUserID` lets make sure to check the error.
</blockquote></details>

Done.
___
*[pkg/sql/authorization.go, line 551 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MzIqiMn9Mc7knB6OXk2:-MzLqVg_BDBoDc-rxE9O:bx86rip) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2c91cbc621a7437f40698b32ad53ba3004523e/pkg/sql/authorization.go#L551)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

This recurse and membership check should be updated to check based on IDs (if the ID exists) - we can do it in a follow up PR as long as we have an issue tracking it.
</blockquote></details>

Create the issue: https://github.com/cockroachdb/cockroach/issues/78963 
___
*[pkg/sql/username_util.go, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MyncI4oAQQgm0ULIgMi:-MywWENP2UZVAVXKqi7l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/sql/username_util.go#L27)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Let's not worry about caching using IDs for simplicity for now and always use `GetUserID` we create an issue to add back the cache after.
</blockquote></details>

Done.
___
*[pkg/startupmigrations/migrations.go, line 788 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MyncgfkAL_2Przj5YN1:-MywWpRD6dvsXtVroQPA:b-gja27f) ([raw file](https://github.com/cockroachdb/cockroach/blob/70252ad183b78303b57131d85a4392adfa425ea8/pkg/startupmigrations/migrations.go#L788)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

Whoops, old code from the hash function. Deleted
___
*[pkg/sql/create_table.go, line 2077 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76612#-MzIr1IN5vJDRcoDOyKz:-MzLqds54iJnxSGZYIuD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2c91cbc621a7437f40698b32ad53ba3004523e/pkg/sql/create_table.go#L2077)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

This is probably not the right place to add this `vt != nil` I think we need to push it deeper into `maybeAddSequenceDependencies` to where the nil ptr ref happens.
</blockquote></details>

Done.

**Review by postamar — CHANGES_REQUESTED** [review]
Changes to the schema of system tables should always be accompanied with a tenant migration so as to correctly upgrade existing clusters which were created at an earlier major version.

Furthermore, this current PR would benefit from being broken down into multiple commits, if possible.

Finally, this is a pretty significant change to `master` and as such it would have to wait until the current release is finalized.

**Comment by RichardJCai** [comment]
> Changes to the schema of system tables should always be accompanied with a tenant migration so as to correctly upgrade existing clusters which were created at an earlier major version.
> 
> Furthermore, this current PR would benefit from being broken down into multiple commits, if possible.
> 
> Finally, this is a pretty significant change to `master` and as such it would have to wait until the current release is finalized.

Oh yeah we definitely don't plan to be merging this before the release is finalized.

> Furthermore, this current PR would benefit from being broken down into multiple commits, if possible.
Agreed on this point. Also do you mind if the tenant migration is added in a follow up PR?

**Comment by RichardJCai** [comment]
Taking this over and turning into some smaller PRs

**Pull request closed without merging**
