### PR TITLE
colexec: reuse buckets in the external hash aggregator

### PR DESCRIPTION
**Pull request by yuzefovich**
The way external hash aggregator works is that it splits up the input
data set into partitions, and then each partition in isolation is
processed by an in-memory hash aggregator. The in-memory operator is
reset between each partition. Previously, the in-memory hash aggregator
would create new buckets on each run. This was suboptimal from the
performance perspective but also was leaky in terms of memory
accounting: whenever a new bucket is created, the memory footprint is
registered; however, we didn't shrink the memory account once the bucket
is no longer used. Such pattern could lead to the external hash
aggregator hitting the --max-sql-memory limit not because we were
actually using that much memory but because of this leaky pattern.

Now this problem is fixed by not discarding the buckets and reusing them
after the in-memory hash aggregator is reset. This allows us to continue
not shrink the memory account when a bucket is done for the current
iteration because we are keeping the reference to the bucket for the
next iteration. It also comes with the reduced allocations bringing
a minor perf benefit.

Addresses: #63619.

Release note: None (no stable release with this behavior)

### CODE REVIEW

**Comment by yuzefovich** [comment]
It is missing a unit test (which I intend to add), but I was curious to put this out early to try on the Nathan's cluster. I'll also kick off a benchmark run, but on my local repro it appears to be marginally faster (within a margin of noise though).

**Comment by yuzefovich** [comment]
Microbenchmarks [show](https://gist.github.com/yuzefovich/9bb2a56b0a911f9e42a55082ce805feb) the reduction in allocations, but the change in speed is non universal (some ups, some downs). In any case, I don't think the difference matters much.

**Review by jordanlewis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYLNENHAa8ni5fKdSoT:-MYLNENHAa8ni5fKdSoU:bkn6bqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/76c10cc636c89a61b569d3523bec9c6af4c007bc/pkg/sql/colexec/hash_aggregator.go#L461)):*
> ```Go
> 				// after resetting.
> 				op.buckets = op.buckets[:nextBucketIdx+1]
> 				bucket = op.buckets[nextBucketIdx]
> ```

I'm confused, don't we have to ++ the nextBucketIdx somewhere? Next time we go through the loop, won't we get the very same bucket?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/hash_aggregator.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYLNENHAa8ni5fKdSoT:-MYLPAuhE8gm9V5Meys6:b-sannwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/76c10cc636c89a61b569d3523bec9c6af4c007bc/pkg/sql/colexec/hash_aggregator.go#L461)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm confused, don't we have to ++ the nextBucketIdx somewhere? Next time we go through the loop, won't we get the very same bucket?
</blockquote></details>

`nextBucketIdx` is tracked implicitly by `len(op.buckets)` - the length of that slice always contains the current number of active buckets. I'm not sure whether extracting it into an explicit variable will make things easier, let me know what you think.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYLNENHAa8ni5fKdSoT:-MYLRdxb2MqMfIIamTyt:bo56gvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/76c10cc636c89a61b569d3523bec9c6af4c007bc/pkg/sql/colexec/hash_aggregator.go#L461)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`nextBucketIdx` is tracked implicitly by `len(op.buckets)` - the length of that slice always contains the current number of active buckets. I'm not sure whether extracting it into an explicit variable will make things easier, let me know what you think.
</blockquote></details>

Ohh, I see... I get it. Maybe a comment "increase the length of op.buckets, using previously-allocated capacity" will help, instead of just talking about reusing the previously created bucket.

**Review by yuzefovich — COMMENTED** [review]
Added a test, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-:-MYLY5Kh1aZCq84th942:b-cok7ez)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/hash_aggregator.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYLNENHAa8ni5fKdSoT:-MYLY4_Y4SfiP6R5cVP8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/76c10cc636c89a61b569d3523bec9c6af4c007bc/pkg/sql/colexec/hash_aggregator.go#L461)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ohh, I see... I get it. Maybe a comment "increase the length of op.buckets, using previously-allocated capacity" will help, instead of just talking about reusing the previously created bucket.
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/external_hash_aggregator_buckets_test.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYNY7Pg6lHdVJRTQkm7:-MYNY7Pg6lHdVJRTQkm8:b2gq7gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe0e43e84a43d8ca2edbbe05bcabce38fddbe470/pkg/sql/colexec/external_hash_aggregator_buckets_test.go#L35)):*
> ```Go
> // Note that this test lives in colexec_test package because it needs
> // serverutils package (which would create import cycle with colexec).
> func TestExternalHashAggregatorReusesBuckets(t *testing.T) {
> ```

Nice test. Would there be some value in a unit test that exercised this as well? It seems easy for this test to rot if we change the way the SQL is executed. A unit test that ensures the memory accounts are cleared on Reset seems like it might last longer.
___
*[pkg/sql/colexec/hash_aggregator.go, line 517 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYNXQkz4GR6tViwJsJ6:-MYNXQl-DXBk5bq4cuAG:b-sr5p96) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe0e43e84a43d8ca2edbbe05bcabce38fddbe470/pkg/sql/colexec/hash_aggregator.go#L517)):*
> ```Go
> 	op.bufferingState.pendingBatch = nil
> 	op.bufferingState.unprocessedIdx = 0
> 	if op.numPreviouslyCreatedBuckets < len(op.buckets) {
> ```

Should we always set `numPreviouslyCreatedBuckets` to be `cap(op.buckets)`? I think this logic is correct now, but would unconditionally setting to `cap()` be "more correct" and universal regardless of any transformations we later apply to `op.buckets`?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-:-MYN_N2y7TjqxK46oCkx:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/external_hash_aggregator_buckets_test.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYNY7Pg6lHdVJRTQkm7:-MYNZTRO9ouFwjpRXsAV:bdiq89e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe0e43e84a43d8ca2edbbe05bcabce38fddbe470/pkg/sql/colexec/external_hash_aggregator_buckets_test.go#L35)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nice test. Would there be some value in a unit test that exercised this as well? It seems easy for this test to rot if we change the way the SQL is executed. A unit test that ensures the memory accounts are cleared on Reset seems like it might last longer.
</blockquote></details>

I agree that this test could rot over time, but I couldn't think of anything that would be lower level, more like a unit test.

The thing is that when the in-memory hash aggregator is reset, the memory under the buckets is not actually released, so the memory account doesn't shrink - after all, we are keeping the buckets to be reused on the following partition. (I think such solution is cleaner and slightly less allocation heavy; the alternative would be to try what your patch attempted, but the approach of shrinking on the bucket flush is more error-prone IMO.) The memory will only be released when the corresponding memory account is closed which will happen when the external hash aggregator closes. At this point, we cannot confirm that the buckets were reused between different partition. One way to check the reusage would be to see the reported memory usage of the account, but that would be even more rotting-prone.
___
*[pkg/sql/colexec/hash_aggregator.go, line 517 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63731#-MYNXQkz4GR6tViwJsJ6:-MYNYcP7Ee3JwQaIGH0f:b-qz1c96) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe0e43e84a43d8ca2edbbe05bcabce38fddbe470/pkg/sql/colexec/hash_aggregator.go#L517)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should we always set `numPreviouslyCreatedBuckets` to be `cap(op.buckets)`? I think this logic is correct now, but would unconditionally setting to `cap()` be "more correct" and universal regardless of any transformations we later apply to `op.buckets`?
</blockquote></details>

At least as it is written currently, using `cap(op.buckets)` is incorrect (and I mentioned it in a comment above). The reason is that all buckets between `len` and `cap` haven't been `init`ialized, you could even say that they haven't been allocated because `newAggBucket` hasn't been called for them. Essentially, `op.buckets[i] == nil` for `i` in `[len(op.buckets), cap(op.buckets))` range. Because we're using `append`, Go might allocate `buckets` slice of larger capacity, and not every element is guaranteed to initialize.

**Pull request merged**
