### PR TITLE
*: use `oserror.Is` instead of `os.Is` predicates

### PR DESCRIPTION
**Pull request by knz**
(Meant to also include https://github.com/cockroachdb/errors/pull/54 after it merges.) 

Go 1.13 has standardized the idea of error wrappers, unfortunately
the 4 special predicates in the `os` package have not been updated
accordingly: `os.IsPermission`, `os.IsExist`, `os.IsNotExist` and
`os.IsTimeout` do not properly recognize wrapped errors.

Additionally, the CockroachDB `errors` library did not properly
preserve these special errors over the network across encode/decode
cycles.

This patch corrects the problem by updating the `errors` dependency
to include the new encode/decode logic for `os` errors, as well
as a new `oserror` package with replacement predicates.

The patch also adds a linter to prevent future uses of the `os`
predicates and suggest using `oserror` instead.

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:LGTM:

> Reviewed 63 of 63 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56048#-:-MKpL890172WQVrZQPp8:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by knz** [comment]
i was able to complete this with the gogoproto 1.2 dep (i.e. without the conflict from #56147 )

**Comment by knz** [comment]
bors r=jbowens

**Comment by knz** [comment]
bors r=jbowens

**Pull request merged**
