### PR TITLE
changefeedccl: remove disableDeclarativeSchemaChangesForTest from two tests

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change removes the `disableDeclarativeSchemaChangesForTest` flag from two
changefeed tests and modifies them to match the new behavior.

There are two ways in which the tests are modified:

1. The timestamp associated with the rows we expect to see during a backfill
   are different with the declarative schema changer. Ex. for ADD COLUMN,
   we expect rows with the `ModificationTime` of the descriptor at version 7
   instead of 5.

2. With the new schema changer, we expect to see backfill rows only once.

   With the old schema changer, we would see KV's be re-written
   in-place while the changefeed was running (one "backfill"). Then, when
   schema change becomes "visible", we would stop the changefeed to
   perform another backfill at the schema change timestamp before moving on.

   With the new schema changer, the KVs are not re-written in place, so they are not seen by
   the changefeed until the schema change becomes "visible". When the schema
   change becomes visible, the changefeed stops to emit all the backfill rows
   before continuing.

Informs: https://github.com/cockroachdb/cockroach/issues/106906
Epic: None
Release note: None

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]

**Comment by jayshrivastava** [comment]
bors r=miretskiy

**Comment by Xiang-Gu** [comment]
@jayshrivastava Would it be even better to run those CDC tests under both legacy and declarative schema changers, like what did [here](https://github.com/cockroachdb/cockroach/blob/acd2cfa6cc086cf070907be4229043893fc29db6/pkg/sql/comment_on_column_test.go#L220-L234) for comment tests?

No need to revert this PR or do anything now but I think it would be useful to improve coverage.

**Comment by jayshrivastava** [comment]
@Xiang-Gu This is what I was trying to understand with my question in https://cockroachlabs.slack.com/archives/C0168LW5THS/p1689601008324289?thread_ts=1689355250.009119&cid=C0168LW5THS. What are the cases where we fall back to the legacy schema changer? 
If it's possible for the legacy schema changer to run in production when doing ADD COLUMN or DROP COLUMN, then yes I can re-add the old tests. If it's not possible, than I can leave the tests out because they are dead code. In this case, the behavior is not metamorphic. If we want to test both schema changers, we would need two different tests that test different behavior.

**Comment by Xiang-Gu** [comment]
1. fallback aside, the customer always has the ability to turn off declarative schema changer and start using legacy schema changer (via a session variable), so the legacy schema changer for ADD/DROP COLUMN is not "dead" per se.
2. I tried to take a look at the test but I didn't understand it honestly. So if they are not immune to schema changer implementations (or as you said, not metamorphic), then I do think adding back tests that use legacy schema changer is meaningful.

**Comment by jayshrivastava** [comment]
Great point! I will re-add the legacy tests.

**Pull request merged**
