### PR TITLE
roachtest: rudimentary support for secure clusters

### PR DESCRIPTION
**Pull request by tbg**
TL;DR: roachtest can now start a secure cluster and `c.Conn` will "just work".

- roachprod: improve impl of pgurl
- roachtest: support using Conn() against secure clusters
- roachtest: remove unused method from Cluster interface
- roachtest: remove ad-hoc methods for secure clusters

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
the changes to the ORM tests lgtm! 

there is one more test that maybe needs to get standardized: connectionlatency https://github.com/cockroachdb/cockroach/blob/8009ac6bb63f455a18bb1139d505bdd9930816b7/pkg/cmd/roachtest/tests/connection_latency.go#L41

cc @RichardJCai you might be interested in reviewing this

**Review by stevendanna — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 21 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68101)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/68101#-MfgGL06CMcT-gjBWXYF:-MfgGL06CMcT-gjBWXYG:bg7igkv) (no related file):*
:lgtm: 

---
___
*[pkg/cmd/roachtest/cluster.go, line 1759 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68101#-MfgDYcj0BNRZAmyiT6h:-MfgDYck3DSSC3odY2KM:b-2dcdeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b88353bc7120658dc3683d59866fe49822785f0b/pkg/cmd/roachtest/cluster.go#L1759)):*
> ```Go
> 			return err
> 		}
> 		// Need to prevent world readable files or lib/pq will complain.
> ```

It looks like Get explicitly adds world-readable permission to files after the investigation over in https://github.com/cockroachdb/cockroach/issues/44843

One interesting follow-up might be to extend Get to take a particular target permission, which would also eliminate the race to "fix" the permission after download.

**Review by RichardJCai — APPROVED** [review]

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68101)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/68101#-MfgGL06CMcT-gjBWXYF:-MfmkwdT3J0Z4FS_QlkZ:b-o6cyn1) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

TFTRs! I fixed up the connection_latency test, I just needed to remove the certs creation for testuser to get it to pass.

---
___
*[pkg/cmd/roachtest/cluster.go, line 1759 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68101#-MfgDYcj0BNRZAmyiT6h:-Mfmkd51Bm22-ooYG9Ze:brm7mwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b88353bc7120658dc3683d59866fe49822785f0b/pkg/cmd/roachtest/cluster.go#L1759)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

It looks like Get explicitly adds world-readable permission to files after the investigation over in https://github.com/cockroachdb/cockroach/issues/44843

One interesting follow-up might be to extend Get to take a particular target permission, which would also eliminate the race to "fix" the permission after download.
</blockquote></details>

Going to leave as is for now, but adding an option to change the perms seems reasonable.

**Comment by tbg** [comment]
bors r=stevendanna,richardjcai

**Pull request merged**
