### PR TITLE
Makefile: use install_name_tool to use @rpath for GEOS

### LINKED ISSUE #53498: CockroachDB 20.2 alpha on macOS 10.15 cannot find spatial libraries unless it is in `/usr/local/bin`
Problem:

The CockroachDB 20.2 alpha3 binary does not seem to be able to find the spatial libraries in `/usr/local/lib/cockroach` *unless* the `cockroach` binary is located in `/usr/local/bin`.  If run from other locations on my PATH (such as `~/bin`) `cockroach` cannot find the spatial libraries.

Reproduction:

```
wget https://binaries.cockroachdb.com/cockroach-v20.2.0-alpha.3.darwin-10.9-amd64.tgz
tar xzvf cockroach-v20.2.0-alpha.3.darwin-10.9-amd64.tgz
cd cockroach-v20.2.0-alpha.3.darwin-10.9-amd64

cp cockroach /usr/local/bin/
chmod 755 /usr/local/bin/cockroach

cp cockroach ~/bin
chmod 755 ~/bin/cockroach

mkdir -p /usr/local/lib/cockroach
cp lib/libgeos.dylib /usr/local/lib/cockroach/
chmod 755 /usr/local/lib/cockroach/libgeos.dylib
cp lib/libgeos_c.dylib /usr/local/lib/cockroach/
chmod 755 /usr/local/lib/cockroach/libgeos_c.dylib

/usr/local/bin/cockroach start-single-node --insecure --background --listen-addr=localhost
/usr/local/bin/cockroach sql --insecure -e 'select st_isvalid(st_makepoint(1,2))'
#   st_isvalid
# --------------
#      true
# (1 row)

pkill ^cockroach

/Users/rloveland/bin/cockroach start-single-node --insecure --background --listen-addr=localhost
/Users/rloveland/bin/cockroach sql --insecure -e 'select st_isvalid(st_makepoint(1,2))'
# ERROR: st_isvalid(): geos: error during GEOS init: geos: cannot load GEOS from dir "/usr/local/lib/cockroach": failed to execute dlopen
# Failed running "sql"
```

Expected behavior:

I can run a `cockroach` binary from anywhere on my PATH, like other well-behaved UNIX programs.  There should be no hardcoded expectations within the binary about where it lives in the filesystem relative to the libraries it is accessing.

Environment:

```
$ uname -a
# Darwin Richards-MBP 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
$ /Users/rloveland/bin/cockroach sql --insecure -e 'select version()'
#  CockroachDB CCL v20.2.0-alpha.3 (x86_64-apple-darwin14, built 2020/08/25 00:12:18, go1.13.14)
```

### PR DESCRIPTION
**Pull request by otan**
Before this, cross compiling GEOS into darwin puts the wrong library
paths in:
```
$ otool -L lib.docker_amd64/libgeos.dylib
lib.docker_amd64/libgeos.dylib:
	/go/native/x86_64-apple-darwin14/geos/lib/libgeos.3.8.1.dylib (compatibility version 3.8.1, current version 3.8.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

But is seemingly correct when natively compiling on OSX:
```
$ otool -L lib/libgeos.dylib
lib/libgeos.dylib:
	@rpath/libgeos.3.8.1.dylib (compatibility version 3.8.1, current version 3.8.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

This blocks the dlopen setup we have for GEOS.

Nothing I seem to do with the CMAKE flags or configurations will set the
rpaths/id appropriately.

As such, resign and use the install_name_tool post-installation to use @rpath
so that dlopen works from any location.

Resolves #53498

Release justification: bug fixes and low-risk updates to new functionality

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53532)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @petermattis)

___
*[Makefile, line 781 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53532#-MFoyWKH1_2m-9g1ipK3:-MFoyWKH1_2m-9g1ipK4:b8q62uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/118f8e5813544fa0282bfc5e23e91debadaaa4fb/Makefile#L781)):*
Can you expand on this? I thought rpath was needed for `ld.so` (or whatever the dynamic linker equivalent is on Mac OS X) to find a library. But when we're using `dlopen` we're explicitly specifying the path. So why is `rpath` necessary? My knowledge of this stuff is severely out of date and Linux specific. See https://en.wikipedia.org/wiki/Rpath for my understanding of rpath. The manpage for [`dlopen`](https://www.man7.org/linux/man-pages/man3/dlopen.3.html) says:

> If filename contains a slash ("/"), then it is interpreted as a (relative or absolute) pathname.  Otherwise, the dynamic linker searches for the object as follows (see ld.so(8) for further details)

Are we trying to `dlopen` paths that don't contain a slash? Note that manpage is for Linux. There may be some differences on Mac OS X.

**Comment by otan** [comment]
___
*[Makefile, line 781 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53532#-MFoyWKH1_2m-9g1ipK3:-MFpZrth2jsXSSliVe7f:b-y9bcor) ([raw file](https://github.com/cockroachdb/cockroach/blob/118f8e5813544fa0282bfc5e23e91debadaaa4fb/Makefile#L781)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you expand on this? I thought rpath was needed for `ld.so` (or whatever the dynamic linker equivalent is on Mac OS X) to find a library. But when we're using `dlopen` we're explicitly specifying the path. So why is `rpath` necessary? My knowledge of this stuff is severely out of date and Linux specific. See https://en.wikipedia.org/wiki/Rpath for my understanding of rpath. The manpage for [`dlopen`](https://www.man7.org/linux/man-pages/man3/dlopen.3.html) says:

> If filename contains a slash ("/"), then it is interpreted as a (relative or absolute) pathname.  Otherwise, the dynamic linker searches for the object as follows (see ld.so(8) for further details)

Are we trying to `dlopen` paths that don't contain a slash? Note that manpage is for Linux. There may be some differences on Mac OS X.
</blockquote></details>

The problem as far as I understand is that OSX is strict about rpath locations. The problem can be summed up here: https://stackoverflow.com/a/22560206

libgeos_c.dylib depends on libgeos.dylib.

When cross compiling Darwin on the builder, it sets the rpath id of libgeos.dylib as `/go/native/x86....blah/libgeos.3.8.1.dylib`
This loads fine, but libgeos_c.dylib depends on libgeos.dylib being in `/go/native/...`, which does not exist in any other host system and hence fails to dlopen.
To get this to work, we replace the /go/native/.... to @rpath, which is an OSX specific placeholder that allows it to be anywhere. This allows this to work. 
When compiling GEOS on OSX, `@rpath` is automatically set as the path. It's just cross compiling that is broken. I've tried all the things such as flags in https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling, but it just doesn't seem to work when cross compling.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53532#-:-MFqw25XDf_6xjUeVTYp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rpath)

___
*[Makefile, line 781 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53532#-MFoyWKH1_2m-9g1ipK3:-MFqvqu3CRPZlvgDtFe0:b-ze50wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/118f8e5813544fa0282bfc5e23e91debadaaa4fb/Makefile#L781)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

The problem as far as I understand is that OSX is strict about rpath locations. The problem can be summed up here: https://stackoverflow.com/a/22560206

libgeos_c.dylib depends on libgeos.dylib.

When cross compiling Darwin on the builder, it sets the rpath id of libgeos.dylib as `/go/native/x86....blah/libgeos.3.8.1.dylib`
This loads fine, but libgeos_c.dylib depends on libgeos.dylib being in `/go/native/...`, which does not exist in any other host system and hence fails to dlopen.
To get this to work, we replace the /go/native/.... to @rpath, which is an OSX specific placeholder that allows it to be anywhere. This allows this to work. 
When compiling GEOS on OSX, `@rpath` is automatically set as the path. It's just cross compiling that is broken. I've tried all the things such as flags in https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling, but it just doesn't seem to work when cross compling.

</blockquote></details>

Ugh, this is all sorts of awful. I played around with it for a bit and couldn't get it to work either. If the approach here works, then I'll accept this ugliness.

**Comment by otan** [comment]
hehe yes yes fall to the dark side!!


bors r=petermattis

**Pull request merged**
