### PR TITLE
kvserver: add TestFlowControlSendQueueRangeMigrate test 

### PR DESCRIPTION
**Pull request by kvoli**
First commit from #136330.

---

Add a new rac2 flow control integration test,
`TestFlowControlSendQueueRangeMigrate`.

This test takes the following steps:

```sql
-- We will exhaust the tokens across all streams while admission is blocked on
-- n3, using a single 4 MiB (deduction, the write itself is small) write. Then,
-- we will write a 1 MiB put to the range, migrate the range, and write a 1 MiB
-- put to the migrated range. We expect that the migration will trigger a force
-- flush of the send queue.
```

Part of: https://github.com/cockroachdb/cockroach/issues/132614
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
Should be good for review, ignoring the first commit (I won't merge this until after we merge the split-out fixes from https://github.com/cockroachdb/cockroach/pull/136077). 

ptal @sumeerbhola.

**Review by sumeerbhola — APPROVED** [review]
nice test!

:lgtm: 

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136264#-:-OD6xlij30zRRvcZ3_wQ:b-olg659)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvserverbase/knobs.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136264#-OD6t95K9B7ooNfEAYbX:-OD6t95K9B7ooNfEAYbY:bhi1px6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd62ab6a0922ea87be13e70466dd0fcec2470114/pkg/kv/kvserver/kvserverbase/knobs.go#L57)):*
> ```Go
> 
> 	// OverrideDoTimelyApplicationToAllReplicas overrides setting the timely
> 	// replication directive which force flushes rac2 send queues to all
> ```

This comment is overly broad. This bool only affects below-raft migrations, and it is only making the code pretend that the cluster version is recent enough.  I am guessing this was needed since the test is starting from an older cluster version, in order to exercise migrations, and we don't have two cluster versions more recent that V25_1_AddRangeForceFlushKey since this is a new cluster version.

**Comment by kvoli** [comment]
I'll probably merge this tomorrow morning sometime, after addressing the comment.

**Comment by kvoli** [comment]
TYFTR

bors r=sumeerbhola

**Pull request merged**
